### ISSUE TITLE
 [css-inline-3] Question about the relationship among `text-box-trim`, `text-box-edge` and `text-line-edge`.

### ISSUE THREAD

**Issue by Clqsin45** [w3c/csswg-drafts#10007]
Hi CSS specification authors! 
I'm trying to implemente these properties. 
Reading https://github.com/w3c/csswg-drafts/issues/8829#issuecomment-1699500216, I have this question in my mind. Since the specification is not updated yet, may I ask some quick questions to unblock my implementation work? 

My question might be: In the case below, how should I trim the box? 
```
<div style=”text-box-trim: ? text-box-edge: leading”> 
<span>TEXT</span>
</div>
```

The div tag wants to trim the half leading, while the span does not do so. In this case, should the box of <div> be trimmed to respect text-box-trim/text-box-edge’s value (like A)? Or should it not be trimmed to respect its inline text’s style( as B)? 
![Capture](https://github.com/w3c/csswg-drafts/assets/13186278/16cea43c-3251-47b0-9899-6e1735631637)

(Sorry I'm very new to this world. if I asked an unclear question, please let me know!)

**Comment by Clqsin45** [comment]
cc @fantasai, @kojiishi

**Comment by fantasai** [comment]
text-box-trim on the DIV affects the line box contained by the DIV, and it doesn't impact the span. So the answer is A.

**Comment by fantasai** [comment]
(Also sorry for not responding earlier. Please feel free to email me directly if I'm not paying attention.)
