### ISSUE TITLE
[css-fonts] Grammar of <feature-value-name>

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1000]
The grammar for the value of `font-variant-alternates` https://drafts.csswg.org/css-fonts/#propdef-font-variant-alternates links its values to their respective definitions, for example `stylistic(<feature-value-name>)` is i link to https://drafts.csswg.org/css-fonts/#stylistic.

However once we’re there, `stylistic(<feature-value-name>)` is repeated but without any link. I couldn’t find the definition for the grammar of `<feature-value-name>`. Based on reading other sections of the spec I *think* it’s supposed to be a single identifier. There should be a definition (maybe `<feature-value-name> = <custom-ident>` ? https://drafts.csswg.org/css-values/#custom-idents) and it should be linked every time `<feature-value-name>` is used elsewhere, like for example in https://drafts.csswg.org/css-fonts/#stylistic.

**Comment by SimonSapin** [comment]
Yes, this is editorial. Since filing this issue https://drafts.csswg.org/css-fonts/#propdef-font-variant-alternates has changed and `<feature-value-name>` now is linked. It goes to https://drafts.csswg.org/css-fonts/#typedef-feature-value-name

> The identifiers used within feature value definitions define `<feature-value-name>`s and follow the rules of CSS user identifiers and are case-sensitive.

… which seems to be a convoluted way of saying `<feature-value-name> = <custom-ident>`. Let’s call it good enough.

**Comment by svgeesus** [comment]
Re-opening with an edits needed label and re-assigning to Fonts 4.
