### ISSUE TITLE
[css-anchor-position] Rename `anchor-default` to `position-anchor`

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#10004]
As the spec has sprouted more properties, a nice naming division has developed - all the props applying to the positioned element start with `position-*`, while the ones applying to the anchor element start with `anchor-*`. The obvious exception to this scheme is `anchor-default`, which is set on the positioned element. The [Apple exploration](https://fantasai.inkedblade.net/style/specs/css-anchor-exploration/) renamed `anchor-default` to `position-anchor`, which is a pretty reasonable name.

This also opens up the possibility of using `position` to shorthand the positioning scheme (`position-type: static | relative | etc`) and the default anchor (`position-anchor: --foo`), as the Apple exploration suggested.

**Comment by kizu** [comment]
Sounds good, maybe the only thing to think about: how will this play with the position-container (https://github.com/w3c/csswg-drafts/issues/9868), as both might potentially be dashed idents, and if we'd want to have both in the shorthand, how to differentiate between them?
