### ISSUE TITLE
[css-selectors-4] Grammar of ns-prefix incorrect?

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#10016]
I'm sorry if I missed this but I couldn't find an explanation of this syntax anywhere.  Currently, the syntax for `ns-prefix` is as follows:
https://github.com/w3c/csswg-drafts/blob/79819a4e4a523de50d1bcdcc32a99c4fab2da72f/selectors-4/Overview.bs#L3607

Is it intended that `|` is required if no `ident-token` or wildcard is specified?  That would mean that selectors such as `|*` are valid.  Is that the case?

**Comment by Loirooriol** [comment]
> Is it intended that `|` is required if no `ident-token` or wildcard is specified?

It's not required to specify `|` in a type selector like `div`, because both consumers make it optional: `<ns-prefix>?`

> That would mean that selectors such as `|*` are valid. Is that the case?

Yes. See this XHTML example (requires `application/xhtml+xml`):
```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<style>|* { background: green }</style>
<div xmlns="">Green</div>
</html>
```

In HTML it may be weirder to have elements without a namespace, but also possible:

```html
<!DOCTYPE html>
<style>|* { background: green }</style>
<script>
var el = document.createElementNS("", "div");
el.textContent = "Green";
document.documentElement.appendChild(el);
</script>
```

**Comment by Loirooriol** [comment]
BTW, the meaning is in https://drafts.csswg.org/selectors-4/#type-nmsp

> - `|E`
>    elements with name E without a namespace

And then as per https://drafts.csswg.org/selectors-4/#the-universal-selector it also works if you use `*` instead of an element `E`.

> Like a [type selector](https://drafts.csswg.org/selectors-4/#type-selector), the [universal selector](https://drafts.csswg.org/selectors-4/#universal-selector) can be qualified by a namespace
