### ISSUE TITLE
[css-view-transitions] Make CSSOM interface read-only

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10011]
I think we have a resolution to make new OM interfaces read-only somewhere, but I couldn't find it. https://github.com/w3c/csswg-drafts/issues/6819 / https://github.com/w3c/csswg-drafts/issues/7033#issuecomment-1046662228 etc are pointers tho...

In any case, any strong reason to make https://drafts.csswg.org/css-view-transitions-2/#navgation-behavior-rule-interface writeable? If not, could we just make it read-only?

cc @nt1m @noamr @tabatkins

**Comment by francescorn** [comment]
This is the resolution for making OM interfaces read-only: https://github.com/w3c/csswg-drafts/issues/7850

**Comment by noamr** [comment]
> This is the resolution for making OM interfaces read-only: #7850

This seem to be about nested media-queries... am I missing something?

**Comment by noamr** [comment]
> I think we have a resolution to make new OM interfaces read-only somewhere, but I couldn't find it. #6819 / [#7033 (comment)](https://github.com/w3c/csswg-drafts/issues/7033#issuecomment-1046662228) etc are pointers tho...
> 
> In any case, any strong reason to make https://drafts.csswg.org/css-view-transitions-2/#navgation-behavior-rule-interface writeable? If not, could we just make it read-only?
> 
> cc @nt1m @noamr @tabatkins

It would be a (minor) shame to make them readonly. e.g. `CSSViewTransitionRule.typeList` is a `DOMTokenList` which has `toggle` etc. If this is the way we're going this is not a strong opposition but I'd like to see a clear resolution about this.

**Comment by cdoublev** [comment]
If I am not mistaken, `CSSViewTransitionRule` attributes can still be re-assigned if they are not `readonly`. Is it an oversight?

https://github.com/w3c/csswg-drafts/blob/6e7ae335dc6215e65d7338779f4165de1814351d/css-view-transitions-2/Overview.bs#L423-L424

**Comment by noamr** [comment]
> If I am not mistaken, `CSSViewTransitionRule` attributes can still be re-assigned if they are not `readonly`. Is it an oversight?
> 
> https://github.com/w3c/csswg-drafts/blob/6e7ae335dc6215e65d7338779f4165de1814351d/css-view-transitions-2/Overview.bs#L423-L424

Yes, thanks for catching all these!

**Comment by emilio** [comment]
@noamr it seems a `readonly FrozenArray<CSSOMString>` rather than a new `CSSViewTransitionTypeSet` would perhaps be less code / less special?

**Comment by noamr** [comment]
> @noamr it seems a `readonly FrozenArray<CSSOMString>` rather than a new `CSSViewTransitionTypeSet` would perhaps be less code / less special?

I'm also OK with that, though there is precedent for those readonly setlikes, e.g. [GPUSupportedFeatures](https://gpuweb.github.io/gpuweb/#gpusupportedfeatures), and it seems more "correct" in a way to represent this as a set.

**Comment by emilio** [comment]
@noamr Is there any de-duplication going on during parsing or what not if you specify the same name twice? If not (and that is uncommon), it's more of an array than a set...

**Comment by noamr** [comment]
> @noamr Is there any de-duplication going on during parsing or what not if you specify the same name twice? If not (and that is uncommon), it's more of an array than a set...

Yea, it should appear as a unique-only set in CSSOM, there should be deduping when creating that set by the parser

**Comment by noamr** [comment]
Reopening for setting the attribute to readonly
