### ISSUE TITLE
[css-typed-om] inverting a type should preserve the percent hint

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#10018]
So after looking at some of the spec rules for #10017, I'm concerned that dividing (in `calc()`) by values with percentages produces inconsistent results.  The rules for [invert](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-invert-a-type) invert (and preserve) `percent` types but erase percent hints.  This means when a percentage in the divisor leads to it having a "percent" type it is preserved, but when it leads to a percent hint, it is removed.  For example this means that `calc(30px / 20%)` has a type that involves percentages whereas `calc(30px / (20% + 10px))` does not.  This seems wrong, and it seems like inverting a type should preserve the percent hint rather than erasing it.

**Comment by tabatkins** [comment]
Fixed in <https://github.com/w3c/css-houdini-drafts/commit/c428893f27db25c3df51b389c222dd7ffb8989e9>
