### ISSUE TITLE
[css-align] Fix order of `unsafe`/`safe` keyword wrt alignment keyword?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1001]
Currently `align-self` and `justify-self` are defined to allow ` [ <overflow-position>? && <content-position> ]`. That these keywords allow reordering makes parsing ambiguous in the shorthand, so they are disallowed from the shorthand. However, we could fix the order of the keywords, and that would make them unambiguous in the shorthand. It would, however, violate the "allow reordering unless unambiguous" principle for the longhands.

**Comment by tabatkins** [comment]
Proposal: require safe/unsafe to be first, before the alignment keyword.

**Comment by fantasai** [comment]
Resolved to accept proposal: https://lists.w3.org/Archives/Public/www-style/2017Apr/0027.html

**Comment by javifernandez** [comment]
I've implemented this change for both WebKit and Blink. 

https://bugs.chromium.org/p/chromium/issues/detail?id=802098
https://bugs.webkit.org/show_bug.cgi?id=181793
