### ISSUE TITLE
[css-color-5] Relative color syntax channel keyword multiplication with percentages

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#10041]
`<number> * <percentage>` works in Chrome:

```css
oklch(from red calc(1 * 50%) c h)
```

`l * <percentage>` doesn't work in Chrome.

```css
oklch(from red calc(l * 50%) c h)
```

https://codepen.io/romainmenke/pen/PogPgmV

@svgeesus This is mostly just a sanity check.

As far as I know there isn't anything special here and multiplying channel keywords by percentages should just work.

If so, I will file the needed bugs and add more WPT tests.

**Comment by tabatkins** [comment]
Yes, the channel keywords are numbers, and the channels can be numbers *or* percentages, so this should work.

**Comment by romainmenke** [comment]
Tests have been merged and [bug](https://issues.chromium.org/issues/328954148) has been filed.

I think this can be closed?

Thank you 🙇
