### ISSUE TITLE
[css-cascade-6] Should `@scope`'s `<scope-start>` & `<scope-end>` be unforgiving?

### ISSUE THREAD

**Issue by dshin-moz** [w3c/csswg-drafts#10042]
As per the discussion log in [making has unforgiving](https://github.com/w3c/csswg-drafts/issues/7676#issuecomment-1341347244) in issue #7676, it seemed like the forgiving behaviour was to be restricted to `:is`/`:where`. This is reflected [in the spec's note](https://drafts.csswg.org/selectors-4/#forgiving-selector).

On the other hand, `<scope-start>` and `<scope-end>` currently are specified as `<forgiving-selector-list>`.

**Comment by tabatkins** [comment]
Sigh, yeah, we probably should make them unforgiving. We wanted to make sure that the learnability was reasonable for where selectors were forgiving vs not, and settled on :is()/:where() being the only places where we'd use forgivingness.
