### ISSUE TITLE
[css-cascade-6] Absolutize Relative Selector Syntax within `@scope`?

### ISSUE THREAD

**Issue by dshin-moz** [w3c/csswg-drafts#10047]
[CSS Nesting](https://drafts.csswg.org/css-nesting/#cssom) spec explicitly absolutizes any use of relative selector syntax by inserting `&`. Seems consistent, then, to absolutize relative selector uses in `@scope` by inserting `:scope`.

By extension (Since we're [treating it like](https://drafts.csswg.org/css-cascade-6/#scope-limits) scoped style rules), `<scope-end>` should do the same, if the relative selector syntax is used. (Aside - `<scope-end>` is [solely defined](https://drafts.csswg.org/css-cascade-6/#typedef-scope-end) as `<forgiving-selector-list>`)

**Comment by emilio** [comment]
Ah, I think this is already resolved in https://github.com/w3c/csswg-drafts/issues/9621, right?

**Comment by dshin-moz** [comment]
Ah - missed, that. Thanks!
