### ISSUE TITLE
[css-anchor-position] is !important allowed in @position-try

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#10058]
Should we allow `!important` decls in `@position-try`? I'm inclined to say no - we're already having to do some slightly odd things with the cascade to make things work reasonably well and in a well-defined way (particularly with `flip-*` keywords), so having some parts of the rule also apply in a separate `!important` location would make it a lot *more* complicated for little, if any, benefit to authors.

(And, like, where *exactly* would they go anyway? We resolved that  normal decls here go at "the end of the author origin", and I'm inclined to actually specify that as a separate origin placed right after Author. Whether an "important position-try decl" should follow normal origin-reversing order (being *weaker* than author !important rules) or violate that to still go after the author !important rules would be an important decision, and both options are fairly bad, I think.)

So, propose to disallow !important.

**Comment by andruud** [comment]
I assume disallowing means that declarations with `!important` are invalid parse-time? (Like keyframes).

**Comment by tabatkins** [comment]
Correct.
