### ISSUE TITLE
[css-view-transitions-1] Is `::view-transition:only-child` supported?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10056]
Right now WebKit makes it unparsable, but I think Blink has an implementation returning false (which doesn't really make sense honestly, if there's one, it should probably return `true`).

@noamr @khushalsagar @vmpstr

**Comment by khushalsagar** [comment]
@nt1m the blink behaviour sounds like a bug, filed an [issue](https://g-issues.chromium.org/issues/330315376) to fix this. `::view-transition:only-child` should be unparsable.

The spec text [here](https://drafts.csswg.org/css-view-transitions-1/#:~:text=If%20a%20descendant%20pseudo%20of%20a%20pseudo%2Delement%20root%20has%20no%20other%20siblings%2C%20then%20%3Aonly%2Dchild%20matches%20that%20pseudo.) excludes `::view-transition` from the list of pseudo-elements that support this property. Feel free to suggest an edit if the text is ambiguous.
