### ISSUE TITLE
[css-2017] CSS profiles in future snapshots

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1006]
In [Snapshot 2017 §2.2](https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#profiles), the CSS Mobile Profile 2.0 and CSS TV Profile 1.0 specs are mentioned, but they seem to be “abandoned” according to the [“current work” page](https://www.w3.org/Style/CSS/current-work.en.html).

What are the current status & future of CSS profiles? Links to related discussions are very appreciated.

**Comment by frivoal** [comment]
The profiles have been carried over to the 2017 snapshot from the previous one without much thought given to the topic.

Personally, I don't think defining profiles is a terribly useful thing to do, and would be OK with dropping them from the snapshot for future editions, as well as dropping them from the 2017 snapshot and pushing an update, but that's just me.

Given that the profiles are not that old, it seems likely that some people disagree with me about their usefulness, or at least disagreed until fairly recently.

Agenda+ to see if the WG wants to drop the profiles from the snapshot, and possibly retire them altogether.

**Comment by xfq** [comment]
I see. Thanks for your reply. BTW, what does Agenda+ mean? Does it mean this topic will be discussed in the next WG Telecon?

**Comment by frivoal** [comment]
> BTW, what does Agenda+ mean? Does it mean this topic will be discussed in the next WG Telecon?

Yes, this is how we flag topics we wish to discuss on the call. The label is what matter, but it is good practice to also leave a comment to be explicit about why.

**Comment by fantasai** [comment]
The profiles in the Snapshot are there because other industries reference them in their standards, and they are therefore part of our spec corpus and not one we can drop. We list them as "abandoned" because nobody is working on them.

**Comment by frivoal** [comment]
We resolved to stop linking to these profiles since they are abandoned / obsolete, and I've updated the Editor's Draft accordingly.
