### ISSUE TITLE
[css-cascade-5] browsers do not disallow CSS-wide keywords in layer names

### ISSUE THREAD

**Issue by mayank99** [w3c/csswg-drafts#10067]
[The spec](https://www.w3.org/TR/css-cascade-5/#layer-names) clearly notes the following:

> The CSS-wide keywords are reserved for future use, and cause the rule to be invalid at parse time if used as an `<ident>` in the `<layer-name>`

I found some existing discussion in #6323, which is where the spec decision was made [originally](https://github.com/w3c/csswg-drafts/issues/6323#issuecomment-887663782).

However, it seems like browsers do not currently respect it. (Open [this playground](https://developer.mozilla.org/en-US/play?id=X7mu9nPXm8pIqMJUZ3gCgtn%2Bt2N7BxvGQuco9w0gNXSpdqhFXEp%2FALvKzGQBXXXfVoSnwCNxrXWRRcOU) in all three browsers and click "Run").

This is a problem because it defeats the purpose of reserving keywords for future use.
- In #6323, there was some discussion around using the CSS-wide keywords to reference unlayered styles.
- In https://github.com/WICG/webcomponents/issues/909#issuecomment-1993388146, there's a proposal around using the CSS-wide keywords to place document styles inside shadow DOM.

Maybe this is really a WPT issue, but I think it warrants some discussion here? My main concern is that any websites outside there depending on current browser behavior could break if we start using these "reserved" keywords for new features.

**Comment by mayank99** [comment]
I'm not sure that I should file issues with browsers. Is it really a bug if that's how it works in all browsers for the last two years?

I'm certainly not a fan of the "the browsers didn't follow the spec, so lets change the spec" way of doing things (especially when browser makers are also involved in making the spec). However, I'm trying to be pragmatic here. If browsers change the behavior, there is a risk of breakage.

**Comment by Loirooriol** [comment]
OK sorry, I understood the opposite, that you wanted to change browsers before people start relying on their behavior.

Anyways 2 years is not that much, and I guess most authors aren't naming their layers as CSS-wide keywords, so I suspect it's still possible to change browsers.

I would prefer to not change the spec until it's clear that it's not web compatible.

**Comment by tabatkins** [comment]
While this assumption varies issue-by-issue, I think it's fairly unlikely that anyone is depending on the CSS-wide keywords being usable layer names. Pursuing this as browser bugs first, and only revisiting the spec if there's compat pushback, is the right way forward here.
