### ISSUE TITLE
[css-images-3] Inconsistent but non-normative advice regarding image metadata and streamability/progressive display

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10075]
In [2.1.2. Image Metadata](https://drafts.csswg.org/css-images/#url-metadata):

> Authors must produce their image files so that such metadata occurs before the image data in the image file. (Note: This is the default for most images already.)

> User agents should ignore any layout-impacting metadata (such as orientation or resolution) that occurs after the image data begins in the file. (Note: This rule does not impact metadata that does not affect layout, such as color space information.)

This assumes that layout changes after all the image data has loaded are a problem, while color space changes after all the image data has loaded are a **not** problem. They are.

As an example, PNG [requires](https://w3c.github.io/PNG-spec/#5ChunkOrdering) that all color space-affecting metadata [`cHRM`](https://w3c.github.io/PNG-spec/#11cHRM), [`gAMA`](https://w3c.github.io/PNG-spec/#11gAMA), [`iCCP`](https://w3c.github.io/PNG-spec/#11iCCP), [`cICP`](https://w3c.github.io/PNG-spec/#cICP-chunk) occurs before the image data (and before the palette, if there is one). This is done specifically to avoid a jarring repaint of the image in different colors.

Other image formats might not impose such a constraint, and thus images will be found where that metadata is after the image data.

Consider a 100-frame animation, which is also on a slow connection; once all the image data loads, suddenly the current frame, all subsequent frames (and for looping animations, all subsequent iterations) have a different appearance.

Suggested fix: delete the _informative_ (and thus, non testable) note "This rule does not impact metadata that does not affect layout, such as color space information".

**Comment by svgeesus** [comment]
@tabatkins @fantasai @LeaVerou

**Comment by ByteEater-pl** [comment]
It's unsettling that the fragment mentions files – a concept mostly foreign to Web standards – instead of resource representations. If understood literally, it's narrower and probably doesn't cover over 99% cases of online usage.
