### ISSUE TITLE
[css-2017] Several issues of the indices

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1007]
The indices in Snapshot 2017 have several issues:

1. The Selector Index is [empty](https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#selectors).

2. `@font-face` and `@import` do not appear in the [At-Rule Index](https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#at-rules), although `css-fonts-3` and `css-cascade-3` are [present](https://github.com/w3c/csswg-drafts/blob/0010e3a556ebe27cca78c9d87b78985e0c416d94/css-2017/Overview.bs#L732-L765) in `Overview.bs`.

3. There are two index sections:

* https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#indices
* https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#index

Should the two sections above be put together? If so, is it technically feasible (with the current Bikeshed)?

-----

/cc @frivoal @tabatkins

**Comment by frivoal** [comment]
>    There are two index sections:
>
>    https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#indices
>    https://www.w3.org/TR/2017/NOTE-css-2017-20170131/#index
>
> Should the two sections above be put together?

I wonder if it wouldn't be just as well to discard the second one entirely. I am not convinced it is terribly useful in this document, and if it is a cause of confusion due to the presence of the full indices, maybe we're better off without it.

**Comment by frivoal** [comment]
> The Selector Index is empty.

> @font-face and @import do not appear in the At-Rule Index, although css-fonts-3 and css-cascade-3 are present in Overview.bs.

I have no idea what's causing this. Bikeshed is reporting success without any error or warning, but clearly something is wrong. @tabatkins ?

**Comment by plinss** [comment]
FWFI, both @font-face and @import are in the anchor database and appear to have the proper attributes (at-rule type, exported, etc), so it's not a spec markup issue.

**Comment by SelenIT** [comment]
Properties and values from CSS UI (like `outline`, `box-sizing` and link to it from the `content-box` value etc.) also seem to be missed from the indices. Doesn't this issue has something to do with naming pattern change ('css3-ui'/'css-ui-3' etc.)?

**Comment by svgeesus** [comment]
@keyframes is also missing

**Comment by frivoal** [comment]
@tabatkins Can you figure out what Bikeshed is doing wrong (or what I did to make it do the wrong thing)?

**Comment by frivoal** [comment]
@tabatkins ping.

**Comment by xfq** [comment]
https://drafts.csswg.org/indexes/ looks more complete.

**Comment by frivoal** [comment]
@tabatkins This continues to affect the 2018 snapshot, and I have no idea what's wrong.

**Comment by tabatkins** [comment]
...huh. I assumed that since the Indexes doc was fine, the snapshot would be. Will look into this, weird.

**Comment by frivoal** [comment]
Any clue? I hope we'll wrap up the snapshots at the upcoming f2f, and I'm much rather have this fixed before we published, but as I don't understand what's wrong, I cannot fix it.

**Comment by SelenIT** [comment]
Can't the combination of `status="TR"` for the `<index>` element and the new URLs of the modules in the `specs` attribute be part of the problem? For example, that lists have `css-images-3` among other values, but the TR-published version of CSS Images Level 3 hasn't undergone the Great Renaming yet, so its URL is still [css3-images](https://www.w3.org/TR/css3-images/).

Maybe other TR specs published with old template have also other problems that prevent their terms and definitions from being parsed correctly?

In the Indexes document, the `<index>` elements have no `status` and `specs` attributes, so they might be not affected by this problem.

**Comment by SelenIT** [comment]
Also, in the `specs` attributes of `<index>` element in CSS-2018, the `css-cascade-3` string is listed twice. Probably the second one should be `css-cascade-4`?

**Comment by frivoal** [comment]
> Also, in the specs attributes of <index> element in CSS-2018, the css-cascade-3 string is listed twice. Probably the second one should be css-cascade-4?

yes, thank you. Fixed now.

**Comment by frivoal** [comment]
> For example, that lists have css-images-3 among other values, but the TR-published version of CSS Images Level 3 hasn't undergone the Great Renaming yet, so its URL is still css3-images.

AFAIK, that shouldn't be the issue, the specref database that's used as a basis for that knows they are aliases.

**Comment by xfq** [comment]
And `<index>` doesn't seem to be Bikeshed's documentation...
