### ISSUE TITLE
@mirisuzanne as co-editor for CSS Values 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10082]
> Yeah, that looks like a typo in CSS Values 5. 

> (I'm willing to help edit this spec, if that's useful - since I've been working on it anyway. Not sure about the process for that.)

_Originally posted by @mirisuzanne in https://github.com/w3c/csswg-drafts/issues/6245#issuecomment-1850702734_

**Comment by svgeesus** [comment]
@astearns suggested async resolution, assuming @mirisuzanne is still willing

**Comment by mirisuzanne** [comment]
I am willing, yes.

**Comment by astearns** [comment]
Sorry, I missed that the first time around. No need for an async resolution on this, let’s just do it.

RESOLVED: Add Miriam as a co-editor of css-values-5

(go ahead and add yourself to the editors list)
