### ISSUE TITLE
FPWD for CSS View Transitions L2

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#10096]
[CSS View Transitions Module Level 2](https://drafts.csswg.org/css-view-transitions-2/) is ready for FPWD. Filing this issue to do a formal resolution.

The level has open issues that still need to be resolved for classes and types but there's no open issues for cross-document transitions. @nt1m @fantasai @emilio any pending cross-document transition issues that you can think of?

**Comment by vmpstr** [comment]
@noamr

**Comment by noamr** [comment]
I want to finish the [editorial refactor](https://github.com/w3c/csswg-drafts/pull/10098) but otherwise I think we're good on cross-doc issues.

**Comment by noamr** [comment]
Filed FPWD: https://github.com/w3c/transitions/issues/595

**Comment by khushalsagar** [comment]
FPWD has been published: https://www.w3.org/TR/css-view-transitions-2/.
