### ISSUE TITLE
[css-grid] Define item processing order when resolving intrinsic track sizes

### ISSUE THREAD

**Issue by nicoburns** [w3c/csswg-drafts#10095]
This issue pertains to steps 12.5.3 and 12.5.4 from [css-grid-2] specification (11.5.3 and 11.5.4 in [css-grid-1]):

- https://www.w3.org/TR/css-grid-2/#algo-spanning-items

Step 12.5 imposes some amount of ordering on processing grid items when determining intrinsic track sizes, but some ordering is left undefined. For example, in which order to process items that cross a flexible track. And in which order to to process items that do not cross a flexible track and cross the same number of tracks as each other. The order in which items are processed can / does affect the sizes that the tracks end up (which tracks item sizes are allocated to), so if we wish for css grid to be completely interoperable then the order must be defined.

The following is an example I was recently presented with where my implementation in [Taffy](https://github.com/DioxusLabs/taffy) conflicts with that in Chrome and Firefox (which seem to be interoperable with each other in this case):

```html
<div style="display: grid; width: 320px; height: 640px; grid-template-columns: auto auto 1fr; grid-template-rows: auto auto auto 1fr; justify-content: start; justify-items: start;">
  <div style="background: #59c4f6; width: 100px; height: 50px; grid-row: 1 / span 2; grid-column: 1;"></div>
  <div style="background: #63c466; width: 40px; height: 30px; grid-row: 1 / span 2; grid-column: 2 / span 2;"></div>
  <div style="background: #feb43f; width: 120px; height: 20px; grid-row: 3 / span 1; grid-column: 1 / span 2;"></div>
</div>
```

When resolving column width, Taffy is processing the 3rd item before the 2nd item on the basis that is further to the left in the grid (which causes column widths of [110px, 10px, 200px]). Based on the column sizes it is producing ([100px, 20px, 200px]), Chrome is presumably processing the 2nd item before the 3rd item. Swapping the items in the source code doesn't change this, so it is not source order that Chrome is processing items. I am guessing that it is may be processing items in [grid order](https://www.w3.org/TR/css-grid-2/#grid-order).

As far as I can tell neither implementation violates the spec, but they nevertheless end up with different results. And I am hoping that we can tighten up the spec to prevent this.

**Comment by Loirooriol** [comment]
> in which order to process items that cross a flexible track

All such tracks are handled simultaneously in https://drafts.csswg.org/css-grid-2/#algo-spanning-flex-items

> in which order to to process items that do not cross a flexible track and cross the same number of tracks as each other

These are also handled simultaneously (grouped by span size) in https://drafts.csswg.org/css-grid-2/#algo-spanning-items

Note that https://drafts.csswg.org/css-grid-2/#distribute-extra-space works on a set of intrinsic sizes (from the various items that are simultaneously handled). And the order doesn't matter, as noted:

> Maintain separately for each affected track a planned increase, initially set to 0. (This prevents the size increases from becoming order-dependent.)

Initially:
 - 1st column: base size = 0px, growth limit = infinity
 - 2nd column: base size = 0px, growth limit = infinity
 - 3rd column: base size = 0px, growth limit = infinity

We 1st handle the 1st item (spans a single non-flexible column):
 - 1st column: base size = 100px, growth limit = 100px
 - 2nd column: base size = 0px, growth limit = infinity
 - 3rd column: base size = 0px, growth limit = infinity

Then the 3rd item (spans 2 non-flexible columns):
 - 1st column: base size = 100px, growth limit = 100px
 - 2nd column: base size = 20px, growth limit = 20px
 - 3rd column: base size = 0px, growth limit = infinity

Then the 2nd item (crosses a flexible column):
 - 1st column: base size = 100px, growth limit = 100px
 - 2nd column: base size = 20px, growth limit = 20px
 - 3rd column: base size = 20px, growth limit = 20px

And finally https://drafts.csswg.org/css-grid-2/#algo-flex-tracks expands the 3rd column to fill the 320px of the grid container:
 - 1st column: 100px
 - 2nd column: 20px
 - 3rd column: 200px

**Comment by nicoburns** [comment]
Ah, it's the finite growth limit set when processing the first item that's causing all of the size from the third item to be distributed to the second column. Given that, I think this is simply a bug in my implementation. Thank you for going through the distribution item-by-item like that. That really made it clear where I was going wrong.
