### ISSUE TITLE
[css-display-3] HTML should be an informative, rather than normative, bibliographic reference

### ISSUE THREAD

**Issue by bert-github** [w3c/csswg-drafts#1011]
‘[HTML]’ is in the Normative References[1], but it seems the only mention of things defined by HTML is just after the words "For example" in section 2.5[2]. I think ‘[HTML]’ should be in the Informative References instead.

[1] https://www.w3.org/TR/2017/WD-css-display-3-20170126/#normative
[2] https://www.w3.org/TR/2017/WD-css-display-3-20170126/#box-generation

**Comment by fantasai** [comment]
Assigning to @tabatkins since I can't fix this--the references are auto-generated from Bikeshed due to element references in the prose.

**Comment by tabatkins** [comment]
Fixed. (You can mark individual links or sections as non-normative with a class=non-normative on an ancestor.)
