### ISSUE TITLE
[css-view-transitions-2] Data type for types in script APIs

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#10114]
@emilio brought up that because we want types to be readonly on the CSSViewTransitionRule, it shouldn't be a DOMTokenList. Filing this issue to clarify the data type across all script APIs.

- `startViewTransition` has a `types` param which is currently sequence<DOMString>.
- `CSSViewTransitionRule` has a `types` param which is currently DOMTokenList.
- `ViewTransition` has a `types` param which is DOMTokenList.

The `ViewTransition` is the only one that needs to me mutable. @noamr

**Comment by noamr** [comment]
> @emilio brought up that because we want types to be readonly on the CSSViewTransitionRule, it shouldn't be a DOMTokenList. Filing this issue to clarify the data type across all script APIs.
> 
> * `startViewTransition` has a `types` param which is currently sequence.
> * `CSSViewTransitionRule` has a `types` param which is currently DOMTokenList.
> * `ViewTransition` has a `types` param which is DOMTokenList.
> 
> The `ViewTransition` is the only one that needs to me mutable. @noamr

We can't use `DOMTokenList` because it's tied to an element+attribute.
For `ViewTransition.types`, he closest equivalent would be a [CustomStateSet](https://html.spec.whatwg.org/multipage/custom-elements.html#customstateset). Proposing to have a `ViewTransitionStateSet` that's `setlike` (almost identical to `CustomStateSet`).
We should decide if this set can hold and reflect invalid values (non-idents, `none`, `-ua-*`). Proposing that it's more useful if it can't reflect invalid values.

For `CSSViewTransitionRule.types`, I think we should have a `readonly setlike`, like [`GPUSupportedFeatures`](https://gpuweb.github.io/gpuweb/#gpusupportedfeatures).

**Comment by khushalsagar** [comment]
> We should decide if this set can hold and reflect invalid values (non-idents, none, -ua-*). Proposing that it's more useful if it can't reflect invalid values.

+1 to the set not holding invalid values. We can drop those as a part of the setter algorithm.

> For CSSViewTransitionRule.types, I think we should have a readonly setlike, like [GPUSupportedFeatures](https://gpuweb.github.io/gpuweb/#gpusupportedfeatures).

SGTM

Any suggestion for this: "startViewTransition has a types param which is currently sequence"? There was also a question about potentially dropping this altogether now that mutable types is a trivial way to do the same thing.

**Comment by noamr** [comment]
> > We should decide if this set can hold and reflect invalid values (non-idents, none, -ua-*). Proposing that it's more useful if it can't reflect invalid values.
> 
> +1 to the set not holding invalid values. We can drop those as a part of the setter algorithm.
> 
> > For CSSViewTransitionRule.types, I think we should have a readonly setlike, like [GPUSupportedFeatures](https://gpuweb.github.io/gpuweb/#gpusupportedfeatures).
> 
> SGTM
> 
> Any suggestion for this: "startViewTransition has a types param which is currently sequence"? There was also a question about potentially dropping this altogether now that mutable types is a trivial way to do the same thing.

I'd say either dropping it or keeping it as a sequence is fine.

To clarify, what I propose as a resolution:
- use `ViewTransitionTypeSet` for `ViewTransition.types` (a `setlike` interface). This throws a type error when trying to add `none`, something that begins with `-ua`-, or anything that's not a valid `custom-ident`
- use `CSSViewTransitionTypeSet` for `CSSViewTransitionRule.types` (a readonly `setlike` interface)
- Optionally, remove the `startViewTransition(callbackOptions)` variant.

**Comment by nt1m** [comment]
Should we create a base type that is shared with CustomStateSet?

**Comment by noamr** [comment]
> Should we create a base type that is shared with CustomStateSet?

The `setlike` mixin should be the right way to go about it IMO, there are lots of them around (e.g. `FontFaceSet` and [`Highlight`](https://drafts.csswg.org/css-highlight-api/#highlight).

**Comment by noamr** [comment]
Reciting @emilio's [comment](https://github.com/w3c/csswg-drafts/issues/10011#issuecomment-2020096245), perhaps it would be simpler/more consistent for the CSSOM version to have `FrozenArray<CSSOMString>` rather than a readonly `setlike`, (and allow duplicates there?)
