### ISSUE TITLE
[css-viewport] CSS zoom should affect clip-path: path() strings.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10126]
Right now per spec it doesn't, but that doesn't match implementations, and it makes sense for it to affect it.

We have tests for this (css/css-masking/clip-path/clip-path-path-with-zoom.html etc), so I think just a tweak to the spec should be enough, wdyt @chrishtr?

**Comment by chrishtr** [comment]
Would it need to say [here](https://drafts.csswg.org/css-viewport/#zoom-property) that if the used value of a property is a path, then the path values are multiplied by zoom also? I guess you're right that it only says the used value is "multiplied", which implies it is a number only and not a path.

**Comment by emilio** [comment]
I think it'd probably be easier to just special-case path strings adding to that paragraph. Path strings are kind of an odd one.
