### ISSUE TITLE
[css-values-5] attr-type values are missing type braces

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#10159]
The attr-type values are missing the "type" notation.  I.e. `<string>`, `<url>`, `<ident>`, etc.
https://github.com/w3c/csswg-drafts/blob/10eb9370b6be939c323bfb1b13fa50d0280c5d4e/css-values-5/Overview.bs#L979-L1040

**Comment by pyoor** [comment]
Ah looks like I misinterpreted the spec and these actually are literal string values.  Closing.

**Comment by tabatkins** [comment]
Keywords, not string, but yes.
