### ISSUE TITLE
[css-text-4] Rename `trim-auto` to `trim-both`

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10161]
Given the current set of values, and the fact that `normal` trims adjacent pairs and `trim-start` indicates trimming the start and adjacent pairs, I think `trim-both` might be a better name for `trim-auto` which trims the start, adjacent pairs, and end. Thoughts? CC @MurakamiShinyu @frivoal @kojiishi @myakura

**Comment by MurakamiShinyu** [comment]
I agree it's better naming `trim-both` for "trim both start and end".

**Comment by frivoal** [comment]
`trim-auto` might not be amazing as a name, but "both" is a strage compoment for something that does 3 things: start, middle, and end. To me, the "auto" part mostly refers to the middle part, as that's what differentiates it from `trim-all`.

**Comment by fantasai** [comment]
@frivoal Yeah, but `normal` and `trim-start` also do the middle part.

**Comment by MurakamiShinyu** [comment]
When I suggested (https://github.com/w3c/csswg-drafts/issues/4246#issuecomment-1416647486) to rename `trim-all` (now different thing) to `trim-auto`, I couldn't think of `trim-both` because at that time there was no `trim-start` value and the default included the "trim-end" behavior. But now `trim-both` sounds not strange.

**Comment by MurakamiShinyu** [comment]
This is just an editorial suggestion related on renaming `trim-auto` to `trim-both`, I think it would be better to change the order of the value definitions from  
> \<spacing-trim\> = space-all | normal | trim-both | trim-start | space-first | trim-all  

to  
> \<spacing-trim\> = space-all | normal | space-first | trim-start | trim-both | trim-all

(I think this is more natural: `space-first` is near `normal` and `trim-both` is near `trim-all`)
and the table of the "summary of what the various values do" would be changed to:

<table>
<thead>
  <tr>
    <th>Value
    <th>Trim at line start
    <th>Trim at line end
    <th>Trim adjacent pairs
    <th>Trim everywhere
<tbody>
  <tr>
    <th>space-all
    <td colspan=4>no
  <tr>
    <th>normal
    <td>no
    <td rowspan=3>only if would not fit
    <td rowspan=4>yes
    <td rowspan=4>no
  <tr>
    <th>space-first
    <td>yes except on the first line
  <tr>
    <th>trim-start
    <td rowspan=2>yes
  <tr>
    <th>trim-both
    <td>yes
  <tr>
    <th>trim-all
    <td colspan=4>yes
  <tr>
    <th>auto
    <td colspan=4>user-agent specific / platform dependent
</table>

With this table, it is much understandable that `trim-both` means trim at both line start and line end.

**Comment by MurakamiShinyu** [comment]
The other advantage of the name `trim-both` is that when the opposite value is needed in the future, the name `space-both` can be used.

I'm not sure if `space-both` (space at both line start and line end; trim adjacent pairs) is really needed in CSS, but Adobe InDesign has such a setting in its Mojikumi settings (文字組みアキ量設定), which is called "約物全角" (= "full-width punctuation", but note that adjacent pairs are trimmed).

**Comment by fantasai** [comment]
Edited in, thanks @MurakamiShinyu for all of your comments and suggestions!
