### ISSUE TITLE
[css-view-transitions-1] Support for globs on ::view-transition pseudo selector

### ISSUE THREAD

**Issue by marnec** [w3c/csswg-drafts#10164]
Link to the spec section I'm talking about
(https://www.w3.org/TR/css-view-transitions-1/#pseudo)

Currently pseudo-selectors `::view-transition-old` and `::view-transition-new` follow the syntax: `::pseudo(<pt-name-selector>)`

where `<pt-name-selector>` can be:
 * \*
 * root
 * custom identifier

I think it would be extremely useful to be able to write:

```
::pseudo(card-*)
```

with the intent of applying some style to all elements with `view-transition-name` that starts with `card-`.

This would be especially useful when you work with frameworks where it is easy to assign `vew-transition-name`s dynamically, as for example in:

```html
<img
  [src]="card.imageUri"
  [style.view-transition-name]="id | prepend : 'card-'"
/>
```

Dyanimc `view-transition-name` has the clear advantage of alleviating devs from the need of interloping in the route change process and imperatively swap the view transition names. However, by doing so you lose the ability of applying some style to a specific group of logically connected animations

**Comment by romainmenke** [comment]
This has some overlap with : https://github.com/w3c/csswg-drafts/issues/10001

**Comment by vmpstr** [comment]
We've added [`view-transition-class`](https://drafts.csswg.org/css-view-transitions-2/#view-transition-class-prop) to help deal with the problem of repeated styles. This seems more in like with id/class split in CSS rather than globs and wildcards

**Comment by khushalsagar** [comment]
@marnec based on your reaction, I'm assuming we can close this. Please reopen if not.
