### ISSUE TITLE
[css-conditional] Unbalanced brackets in @supports condition

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1016]
Gecko and Edge seem to reject (return false for `CSS.supports`) a condition if there is any unbalanced bracket, while Blink seems to accept it.

e.g. There are two conditions in Gecko's test suite:
* `not ({ something @with (unbalanced brackets })`
* `(color: green) or an-extension(that is [unbalanced)`

Gecko and Edge return `false` for both, while Blink returns `true` for both.

The spec doesn't seem to have anything about this. The question is, should it allow or disallow unbalanced brackets? Either way, it should probably be stated explicitly in the spec.

**Comment by tabatkins** [comment]
Using Syntax 3 (and invoking the "parse as CSS" entry point) will auto-close any blocks. Using `<any-value>` (which I agree is correct there), however, will cause both of the OP's examples to be invalid, because of the unmatched } and ) tokens.

**Comment by tabatkins** [comment]
In other words, `not ({ something @with (unbalanced brackets })` will parse into the equivalent of `not ({ something @with (unbalanced brackets })})`, with the first } being unmatched, while `(color: green) or an-extension(that is [unbalanced)` will parse into the equivalent of `(color: green) or an-extension(that is [unbalanced)])`, with the first ) after `unbalanced` being unamtched.

**Comment by svgeesus** [comment]
Seems like re-expressing in Syntax 3 would clear the ambiguity and in general make the spec better. @tabatkins sounds like you had a clear idea on that, what to outline what you meant or should I take a crack at it first?

**Comment by svgeesus** [comment]
Uh ... the spec already seems to reference Syntax 3. The [only reference to CSS 2.1](https://drafts.csswg.org/css-conditional-3/#index-defined-elsewhere) is the definition of `width`. 

> general_enclosed links to any in CSS 2.1, which does require balancing.

It did in the [2013 CR](https://www.w3.org/TR/css3-conditional/#general_enclosed) but in [the current draft](https://drafts.csswg.org/css-conditional-3/#at-supports) `<general-enclosed>` [links to MQ5](https://drafts.csswg.org/mediaqueries-5/#typedef-general-enclosed) which does indeed use `<any-value`

So I think this issue is overtaken by events and can be closed.

**Comment by svgeesus** [comment]
@upsuper do you agree?

**Comment by upsuper** [comment]
While I don't understand what do you mean by
> this issue is overtaken by events and can be closed.

As far as we are going to require it to be balanced I'm happy with it. Maybe it would be good to have a wpt and file a bug to those browsers after we close this.

**Comment by tabatkins** [comment]
Yeah, the specs now normatively reference Syntax 3 properly, so everything's well defined. *Missing* closing brackets will be auto-closed by the CSS parser (and thus are perfectly fine), but unbalanced brackets are invalid per the `<any-value>` production.

So `(color: green) or an-extension(that is [unclosed` is valid, `(color: green) or an-extension(that is [unbalanced)` is invalid.
