### ISSUE TITLE
Negative value in <shape-radius> should be invalid

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1017]
It doesn't make sense to have negative radius for shapes, and both Gecko and Blink agree that negative value here should be invalid.

**Comment by astearns** [comment]
Both circle() and ellipse() state that negative values for radii are invalid.

**Comment by upsuper** [comment]
Ah, okay. I guess this is not an issue then. Probably worth moving that statement to `<shape-radius>`, though, since negative radius doesn't sound like something useful.
