### ISSUE TITLE
[css-view-transitions-1] What is the size of the group pseudo for the root element?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10177]
From @mattwoodrow from investigating https://bugs.webkit.org/show_bug.cgi?id=272186:

Chrome seems to be setting the size of their ::view-transition-group element to that of the snapshot containing block. That seems wrong, but visually what you’d expect to happen.

Capture the image algorithm has a special case for sizing the image when capturing the root, I suspect Update pseudo-element styles should have the equivalent wording for setting the width/height style properties.

**Comment by nt1m** [comment]
@noamr @khushalsagar @vmpstr

**Comment by noamr** [comment]
Sounds reasonable to me, will wait for Vlad/Khush to confirm. Happy to make the edit.

**Comment by khushalsagar** [comment]
> That seems wrong, but visually what you’d expect to happen.

Just to confirm, the error is that we're using the border-box for the document element [here](https://drafts.csswg.org/css-view-transitions-1/#style-transition-pseudo-elements-algorithm:~:text=Set%20width%20to%20the%20current%20width%20of%20capturedElement%E2%80%99s%20new%20element%27s%20border%20box.). Instead it should be the snapshot containing block size similar to when we do this for the old DOM [here](https://drafts.csswg.org/css-view-transitions-1/#capture-old-state-algorithm:~:text=Let%20originalRect%20be%20snapshot%20containing%20block%20if%20element%20is%20the%20document%20element%2C%20otherwise%2C%20the%20element%7C%27s%20border%20box.).

SGTM. Thanks for spotting this!

**Comment by mattwoodrow** [comment]
> Just to confirm, the error is that we're using the border-box for the document element [here](https://drafts.csswg.org/css-view-transitions-1/#style-transition-pseudo-elements-algorithm:~:text=Set%20width%20to%20the%20current%20width%20of%20capturedElement%E2%80%99s%20new%20element%27s%20border%20box.). Instead it should be the snapshot containing block size similar to when we do this for the old DOM [here](https://drafts.csswg.org/css-view-transitions-1/#capture-old-state-algorithm:~:text=Let%20originalRect%20be%20snapshot%20containing%20block%20if%20element%20is%20the%20document%20element%2C%20otherwise%2C%20the%20element%7C%27s%20border%20box.).

Yes, exactly. Thank you!
