### ISSUE TITLE
[css-anchor-position-1] Clarify interaction of anchors and positioned elements with content-visibility

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#10184]
In #10040 we've resolved that
> ... if a positioned element is "relevant to the user", any element it's anchoring to remains "relevant to the user" as well.

This particular phrasing poses some implementation difficulties, since we don't typically track whether an arbitrary element is relevant to the user. We only tend to do that in the context of its effect on `content-visibility`.

I think this should say the following:
> if a positioned element is **not skipped**, any element it's anchoring to remains "relevant to the user". 

since being skipped is something that is imposed on the element by `content-visibility`. This does mean that if the anchor and the positioned elements are both off-screen, but the positioned element is not under `content-visibility`, then the anchor will remain relevant to the user. I think that's fine though.

As an aside, I presume that if the positioned element is display: none or something, then it's not actually a positioned element and thus is not anchoring to the anchor

/cc @tabatkins @progers @mfreed7

**Comment by vmpstr** [comment]
An edge case is if the positioned element and the anchor are both in the same `content-visibility` subtree. Then the positioned element is not skipped, and thus the anchor is relevant. This means that this subtree will always be relevant. We should probably have a carve out for this case to allow it to become skipped

**Comment by progers** [comment]
> As an aside, I presume that if the positioned element is display: none or something, then it's not actually a positioned element and thus is not anchoring to the anchor.

Do you mean the scenario where the anchor element itself has display: none? In that case, the [spec](https://drafts.csswg.org/css-anchor-position-1/#name) says that anchor-name only applies to elements that produce a principle box, and this wouldn't happen with display none. Or do you mean the case where the anchored element has display: none; in which case, is the effect observable either way?

**Comment by tabatkins** [comment]
> I think this should say the following:

I'm fine with this rephrasing.

> We should probably have a carve out for this case to allow it to become skipped

Yup, indeed. Gotta prevent cycles in our collector.

> As an aside, I presume that if the positioned element is display: none or something, then it's not actually a positioned element and thus is not anchoring to the anchor

Correct.

**Comment by tabatkins** [comment]
Okay, text rephrased. Let me know if this works for you, @vmpstr ?

**Comment by vmpstr** [comment]
Looks good.

Minor nit:
> ... if a descendant of _el_ is a target anchor element for a positioned element who is not skipped ...

"who" here is ambiguous: it could be the target anchor element or a positioned element. The rest of the text continues with

> ... and whose containing block is not _el_ or a descendant of _el_, ...

Which strongly suggests that we're talking about the positioned element here, since the target anchor element is a descendant of _el_ from the earlier text. So that's why it's a minor nit.

**Comment by vmpstr** [comment]
I think we can close though, and fix up ambiguities as separate editorial changes
