### ISSUE TITLE
[css-text] Should text-wrap-style:balance be allowed to affect the block height?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#10186]
The description of [text-wrap-style: balance](https://drafts.csswg.org/css-text-4/#valdef-text-wrap-style-balance) says that balancing "must not change the number of line boxes the block would contain if [text-wrap](https://drafts.csswg.org/css-text-4/#propdef-text-wrap) were set to auto."

My assumption is that this restriction is intended to ensure that applying the 'balance' setting to a block of text will only adjust the line-breaking used within the block but will not affect layout outside it by changing its dimensions (potentially leading to overflow or moving other elements on the page).

However, this restriction is not actually sufficient to ensure this "safety". Even if the number of line boxes doesn't change, content moving from one line to another may cause changes in line heights and therefore in the overall height of the block. I think that undermines the intention of the "must not change the number of lines" restriction.

[Here's a codepen](https://codepen.io/jfkthame/pen/jORxBPV) with a couple of simple examples. Rendering (in Chrome Canary):
![image](https://github.com/w3c/csswg-drafts/assets/1706499/82b98302-5f11-469a-8177-cf714463c978)

As this demonstrates, the revised line-breaking of text-wrap:balance has the potential to make the block either shorter or taller, either of which might have unexpected consequences for the containing layout.

I propose that we should tighten up the restriction on text-wrap-style:balance to say something like "...must not change the number of line boxes the block would contain if text-wrap were set to auto, nor alter its intrinsic size."

**Comment by astearns** [comment]
The restriction (as I recall) is merely to ensure that the algorithm for balancing lines does not change the number of lines. I think it’s fine for the overall height of the block to vary as in your examples. Do you think there is a benefit to maintaining intrinsic size as well?

**Comment by jfkthame** [comment]
Maybe the number of lines is all that matters? I thought -- perhaps wrongly -- that the idea was to ensure the effect of `balance` is confined to the content within the block, and won't affect layout outside it (so authors can request it in the knowledge that whether or not it's supported, and regardless of the exact algorithm the browser may use, it won't cause other things on the page to shift or break).

I'd be interested to know what other people think about this.

(For the record, I did just recently make a change in Gecko's implementation that ensures the intrinsic size of the block does not change. But maybe that's a stricter requirement than we actually want? Here's what the latest Firefox Nightly does with the codepen example:

<img width="501" alt="image" src="https://github.com/w3c/csswg-drafts/assets/1706499/ed37ff69-897f-4cbe-9618-e931cc72660f">

whereas before the most recent change, it gave the same result as the Chrome screenshot above.)

**Comment by astearns** [comment]
If I were setting the line breaks manually I would prefer the height-constrained result for your first example, and the previous non-height-constrained result for your second example 😁. But that’s just an effect of the particular content, width, and styling, and not something I think we can automate in general.

I look at text-wrap-style: balance as an input to a single composition, communicating a single intent for the block. What happens to the height as that input is flipped doesn’t really matter to me, that’s an entirely different composition. I worry a bit that if we add the height constraint there will be cases where more balanced line breaks would have to be rejected. But I don’t think that worry is enough to reject the idea.

@kojiishi , @fantasai , @frivoal what do you think?

**Comment by astearns** [comment]
Typographically I don’t mind reducing changing the number of lines from MUST to SHOULD (there are edge cases where removing a very short last line can achieve better balance). But I don’t think we should allow more than adding or removing one line. There are definitely cases where a headline could be more “balanced” by doubling the number of lines, but that’s not going to be an intended or good result.

Also, would we need to adjust this metric?

> Line boxes are balanced when the standard deviation from the average [inline-size] of the remaining space in each line box is reduced over the block (including lines that end in a forced break).

Is a comparison of the standard deviation across N-1 or N+1 lines to the standard deviation of N lines still valid?

**Comment by frivoal** [comment]
No strong opinion on allowing +/- 1 line. I do agree that requiring no change in height is likely not a reasonable restriction. Among other things, I think respecting that constrain while taking into account interaction with floats could be a lot more trouble than it is worth.
