### ISSUE TITLE
[css-transitions] Reading computed styles can immediately start then cancel transitions on newly mounted elements

### ISSUE THREAD

**Issue by thecrypticace** [w3c/csswg-drafts#10187]
Hi! I'm looking for some clarification on a particularly weird browser behavior with regards to CSS transitions on newly-mounted elements which I encountered while triaging a bug in a project I maintain for work.

Normally adding classes to an element can cause a transition to play (depending on the CSS properties being changed, state of the element, etc…). However, there's a situation where this doesn't happen correctly. To reproduce this you have to have an element do all of the following within the same frame in the following order:

1. Mount the element to the DOM; AND
2. Read the value of _any_ computed property via `getComputedStyle(…).getPropertyValue()` or `getComputedStyle(…)[property_name]` (note: this can be read from the animating element itself or any element in its subtree); AND
3. Add the class to the element that prepares the transition

When this happens a transition starts and is then immediately cancelled. And there is also an animation present when calling `Element.getAnimations()` when there normally would not be one. It happens in every browser I've tested (Chrome, Firefox, Safari, and Edge) but I can't find anything in the spec that would directly explain this behavior and it's a bit confusing because if you do any of the following, the transition plays as expected:

1. Read a computed property value AFTER adding the class
2. Don't read a computed property value
3. Wait one frame after mounting the element before doing anything else
4. Wait one frame before adding just the class
5. Use an element that is already in the DOM rather than mounting it

I've created two examples to demonstrate this behavior. One of them is a simplified version that demonstrates the issue directly. The other one compares it to some other situations where the transition plays as expected.

Press `toggle` to fade all elements out then press it again to fade them in and you'll see the behavior I'm describing.

- Simple example: https://jsbin.com/huxinohuke/1/edit?html,output
- Complex example: https://jsbin.com/tuyakemiru/1/edit?html,output

The [Starting of transitions](https://drafts.csswg.org/css-transitions-1/#starting) section of the CSS Transitions spec might be relevant here but the fact that this only happens for newly-mounted elements leads me to believe it's a bug and not intended behavior.

My question is basically: Is this the intended behavior? If so, is there a reason for it?

**Comment by xiaochengh** [comment]
I think what you observed is working as intended. In your simple example:

1. The element is mounted
2. Since the element doesn't have any matched `opacity` rules atm, calling `getComputedStyle(...)` sets the element's computed `opacity` to `1`
3. A class is set on the element, but its style hasn't been recomputed yet
4. In the `requestAnimationFrame` callback, its class is changed
5. The element's style is recomputed, and the computed `opacity` value is still `1`

So there's no transition at all, because the element's style is only computed twice, and the computed value remains `1`

**Comment by thecrypticace** [comment]
Given that this even happens when there's a call for _any element in the subtree_ of the transitioning element is there any way to counteract this other than temporarily resetting transition to `none`, forcing a reflow, then restoring its old value? (basically force cancelling the transition that was started because of the call to `getComputedStyle`)

This has been a very real issue that's bitten users of Headless UI multiple times because of third party code calling `getComputedStyle()` that we have no direct control over.

The behavior here feels very counterintuitive and also a bit complex to explain because it only affects newly added elements (or I guess more technically any elements whose computed styles were undefined at the time getComputedStyle was called).

**Comment by xiaochengh** [comment]
> Given that this even happens when there's a call for *any element* in the subtree of the transitioning element

There's no way to recompute the style of a descendent element without recomputing the ancestor, given how style inheritance works. And that will cause a style change on the ancestor.

> is there any way to counteract this other than temporarily resetting transition to none, forcing a reflow, then restoring its old value? 

I think the right fix is: set the element's class first before attaching it to the tree. In your examples, it will be moving step 3 before step 1.

I also don't think there's anything thing to do on the spec side. If you want a switch to control when to ignore style changes and when not to -- that's exactly the `transition` property itself.

**Comment by thecrypticace** [comment]
Okay, that makes sense. Thanks 👍
