### ISSUE TITLE
[css-color-5]  Spec wording on which color keywords are valid

### ISSUE THREAD

**Issue by tiaanl** [w3c/csswg-drafts#10191]
Referring to this line: https://github.com/w3c/csswg-drafts/blob/3b93f2402397add5b201f5628532ee5b29f900bc/css-color-5/Overview.bs#L847

It reads: `...or be specified as a channel keyword referring to one of the channels of the origin color.`

At this point there is no mention of the origin color being converted to the color being specified yet, so the assumption might be that specifying `rgb(from hsl(0, 100% 50%) h s l)` the `h`, `s` and `l` keywords should work.

**Comment by svgeesus** [comment]
Fair enough.

The spec does go on to say

> If the originally specified color space for the [origin color](https://drafts.csswg.org/css-color-5/#origin-color) used a different color function, it’s first converted into the chosen color function, so it has meaningful values for the channels.

But perhaps that does need to be said earlier.

**Comment by svgeesus** [comment]
@tiaanl Is [the spec](https://drafts.csswg.org/css-color-5/#relative-colors) clearer now?

**Comment by tiaanl** [comment]
@svgeesus Much clearer, thanks
