### ISSUE TITLE
[css-anchor-position-1] Bikeshed name of `inset-area`

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#10209]
Una tweeted the other day about Anchor Positioning.
https://twitter.com/Una/status/1777424771254222948

<img width="599" alt="Screenshot 2024-04-15 at 10 31 34 AM" src="https://github.com/w3c/csswg-drafts/assets/108474/361072b0-cb13-4c48-ac03-d6640cb7bd8d">

It reminded me that I do not believe `inset-area` is the best name for this property. It's the area for the thing, cool. But it's insetting from what? Why is it called inset area? If I'm a developer trying to remember the name of the property cold, as I write CSS to create an anchor and put it someplace, why am I going to think "oh, I need to describe the area for the inset"?

I think we can find a property name that describes the tool developers will be reaching for. Perhaps `position-area` or `anchor-area`.

**Comment by nt1m** [comment]
I agree `position-area` is a better name. `inset-area` made more sense when the `inset` properties were reset by `inset-area`, but from what I heard, this is no longer the case, which makes it very confusing.

It also makes sense to make `position-area` a longhand of `position` IMO.

Anything that controls the behavior of `inset` should be `position-*`, `inset-*` should be reserved to longhands of `inset` only.

**Comment by nt1m** [comment]
cc @mfreed7 @tabatkins

**Comment by una** [comment]
@nt1m I disagree that putting `inset-area` in the `position` shorthand makes sense. `inset-area` positioning only works with absolute or fixed positioning, so combining it with other position options (such as relative, or sticky) would be invalid. I.e. `position: relative top span-left` would be invalid if you try to combine them into a shorthand. They seem like very different developer affordances to me.

**Comment by nt1m** [comment]
@una The syntax for the shorthand could be `static | relative | sticky | [ [ absolute | fixed ] || <'position-area'> || <'position-anchor'> ]` or something similar. Or at the very least, `position-area` could be reset-only subproperty of `position`, like `position-anchor` currently is.


Anyway, I'm advocating for the `position-` prefix here, mainly because @fantasai just taught me the spec allows you to use `inset-area` along with `inset` which wasn't clear to me from the naming, e.g.:

```
inset-area: bottom left;
inset: 2px;
```

will move the containing block to the bottom left of the anchor, then inset 2px from that containing block.

It would be a lot more explicit that this is how things work if the property was named `position-area`. With the name `inset-area`, I have a tendency to think that `inset-area` resets `inset` or vice-versa and that only one of the two apply.

**Comment by nt1m** [comment]
I believe the original naming of `inset-area` came from when the spec used to make `inset-area` reset the `inset` values to `anchor(...)`, where the name made sense, but it no longer makes sense with the current definition.

**Comment by mfreed7** [comment]
> I believe the original naming of `inset-area` came from when the spec used to make `inset-area` reset the `inset` values to `anchor(...)`, where the name made sense, but it no longer makes sense with the current definition.

I thought it came from the fact that you were picking an **area** within the **inset-** modified-containing-block? In terms of explaining what this property does for developers, I actually think it's pretty important to tie it to `inset`s, so they know it lives within the IMCB. Calling it `position-area` feels more confusing actually.

**Comment by nt1m** [comment]
> I thought it came from the fact that you were picking an area within the inset- modified-containing-block?

From #9145:
"In the current spec you'd write that as bottom: anchor(top); right: anchor(right);; in this proposal you'd alternately be able to write inset-area: top / start center; and get the same effect."

The very first proposal in that issue saw `inset-area` as an alternative to setting two of the `inset` longhands.

> I thought it came from the fact that you were picking an area within the inset- modified-containing-block? In terms of explaining what this property does for developers, I actually think it's pretty important to tie it to insets, so they know it lives within the IMCB. Calling it position-area feels more confusing actually.

My mental model is that there is a containing block that is picked by `position` that `inset-area` modifies that containing block, just like `position-anchor` does. It does not pick an area inside the containing block, but modifies the containing block itself.

The problem with the `inset-*` naming is that it implies overriding the other `inset` properties. It's not obvious you can use both `inset-area` and `inset` together to inset from the containing block that `inset-area` has defined.

**Comment by fantasai** [comment]
> > I believe the original naming of `inset-area` came from when the spec used to make `inset-area` reset the `inset` values to `anchor(...)`, where the name made sense, but it no longer makes sense with the current definition.
> 
> I thought it came from the fact that you were picking an **area** within the **inset-** modified-containing-block? In terms of explaining what this property does for developers, I actually think it's pretty important to tie it to `inset`s, so they know it lives within the IMCB. Calling it `position-area` feels more confusing actually.

@mfreed7 Actually it's exactly the opposite? `inset-area` specifies the area that **contains** the inset-modified containing block.

Finding the available space for an abspos follows three steps:
1. Identify the containing block generating element (defaulting to initial containing block).
2. If `grid-area` or `inset-area` applies, use the specified area's edges, otherwise use the containing block's padding edge.
3. Apply `inset` properties to reduce to the inset-modified containing block. This is the rectangle the abspos is sized and positioned into.

**Comment by fantasai** [comment]
Considering this together with https://github.com/w3c/csswg-drafts/issues/10321 what renaming allows us to do is to create `position` as a shorthand of all the positioning properties other than `inset` (which is lengths, kinda margin-ish, and feels more separate). Something like:

```
position: <type> <anchor>? [ / <container>]? [ <area> [, <try>]? ]?

Examples:
position: fixed --foo bottom, top;
position: absolute / --container;
position: fixed --foo bottom span-right, flip-block, bottom, top;
position: absolute --foo / --container left;
```

**Comment by una** [comment]
@fantasai - how would this work with `position-try-options`? What if you skip the inset-area and want to use named `@position-try` values instead? I.e. `position: fixed --foo --bottom, --top;`?

**Comment by nt1m** [comment]
Regardless of shorthanding, I think we should do this. It's inconsistent that this is named `inset-area` while all properties that control the containing block are prefixed with `position-`. The shorthanding is a good addition, but my main motivation for this renaming is to make it clear that this changes the containing block, and not the `inset` properties themselves.

@astearns Would it be possible to add this to the next agenda?
