### ISSUE TITLE
[css-tables] <colgroup> width is over-ridden by <col>

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#1022]
We discovered this while writing tests for computing column measures, we need to add to the spec to represent this. Here's the test code:

    <table id="two" cellspacing="0" cellpadding="0">
        <colgroup style="width: 10px;">
            <col style="width: 1px;"></col>
        </colgroup>
        <tr>
            <td style="width: 1px;"></td>
        </tr>
    </table>

**Comment by FremyCompany** [comment]
Closed as dupe of #1025
