### ISSUE TITLE
[cssom-view] Remove `caret range` concept from `CaretPosition` interface

### ISSUE THREAD

**Issue by siliu1** [w3c/csswg-drafts#10230]
Current spec for `CaretPosition` interface has a `caret range` concept which is a live range. The `caret range` is only used to get the client rect of the `CaretPosition`. We should avoid creating the live range upfront because:

  1. the live range is not used at all except for getting client rect.
  2. Maintain live range can be expensive during DOM mutation.
  3. No browsers implemented the algorithm by creating live range upfront. (Firefox and Chromium both create a live range only when `CaretPosition::getClientRect()` is invoked.)
 

Propose to remove `caret range` concept from `CaretPosition` interface.

**Comment by sanketj** [comment]
Completely agree that caret position shouldn't be live or backed by a live range, because of the perf concerns you called out. I think the spec should be updated to explicitly mention that.

**Comment by annevk** [comment]
Yeah, I think the current definition is broken as someone could mutate the range and that would impact the result, which isn't what you want to happen.

**Comment by smaug----** [comment]
yeah, the spec doesn't really make sense. Gecko does internally create a temporary Range just to call getBoundingClientRect and after that the Range is released, so it won't observe mutations to DOM.

I think this stuff comes initially from https://github.com/w3c/csswg-drafts/commit/532723f180343305397c6ede736854cb90ea6e8e

I don't see that being discussed in
https://www.w3.org/Bugs/Public/buglist.cgi?product=CSS&component=CSSOM%20View&resolution=---
So perhaps it came from the mailing list.

Here https://lists.w3.org/Archives/Public/www-style/2009Nov/0244.html
I didn't try to find the relevant TPAC meeting minutes.

Oh, and looks like I complained about the range already 13 years ago :) https://lists.w3.org/Archives/Public/www-style/2011May/0051.html

**Comment by siliu1** [comment]
Thanks for the input. It seems that @smaug---- from Mozilla, @annevk from Apple, and @sanketj and myself from Microsoft/Chromium all agree that `CaretPosition` should NOT be backed by a live range.

@astearns Is it possible to get to resolution of this issue without bringing up to CSSWG meeting? Thanks.

**Comment by siliu1** [comment]
cc'ing Googler @mfreed7.

**Comment by mfreed7** [comment]
> cc'ing Googler @mfreed7.

LGTM. Incidentally, I'm also in favor of going back in time and making **every** range a static range, but that's a tougher lift.

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Remove `caret range` concept (and live ranges) from `CaretPosition` interface.

**Comment by siliu1** [comment]
PR is merged. Closing the issue.
