### ISSUE TITLE
[selectors-4] Undefined term: "Value Selector"

### ISSUE THREAD

**Issue by ToBeJazz** [w3c/csswg-drafts#10239]
I assume that a "Value Selector" here in the title - https://www.w3.org/TR/selectors-4/#attribute-representation - means the symbol(s) in between the attribute and the value, but that is only an assumption.

1. The term "Value Selector" seems to not be properly defined.
2. There's (possibly) a lacking term for the symbol(s) in between the attribute and the value in an Attribute Selector.

**Comment by Loirooriol** [comment]
> the symbol(s) in between the attribute and the value

But that's not a selector. My understanding is that the title means "attribute presence selectors and attribute value selectors", the former being `[attr]` and the later being the other attribute selectors.

> lacking term for the symbol(s) in between the attribute and the value in an Attribute Selector.

In the grammar that's called [`<attr-matcher>`](https://www.w3.org/TR/selectors-4/#typedef-attr-matcher).

Is there any reason you want a term for this?

**Comment by tabatkins** [comment]
Yup, I think you're misreading the heading - it says "Attribute Presence and Value Selectors", meaning it's about "Attribute Presence Selectors" (plain `[foo]`) and "Attribute Value Selectors" (`[foo="bar"]` and the rest).

**Comment by ToBeJazz** [comment]
Now I understand, thx!
