### ISSUE TITLE
[css-grid-3][masonry] merge masonry-auto-flow into grid-auto-flow?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10231]
The `masonry-auto-flow` property does something similar to `grid-auto-flow`; should we merge these two properties?

- https://drafts.csswg.org/css-grid-3/#masonry-auto-flow
- https://www.w3.org/TR/css-grid-2/#grid-auto-flow-property

**Comment by SelenIT** [comment]
There was once an idea to use the special `grid-auto-flow` value [as the only masonry switch](https://github.com/w3c/csswg-drafts/issues/4650#issuecomment-713221727), with no extra values to `grid-*-template` and no extra properties at all. Maybe it could be worth reconsidering?

**Comment by fantasai** [comment]
If we drop `definite-first` (https://github.com/w3c/csswg-drafts/issues/10260) and we drop `next` (https://github.com/w3c/csswg-drafts/issues/10232) then we can just drop the property entirely.

**Comment by tabatkins** [comment]
These shouldn't be merged, imo. They're doing the same things, conceptually, but have a totally different set of controls for those things. We'd just have two divergent syntax branches, with one useful only for Grid and the other useful only for Masonry; we'd have to define default behavior for if you used the wrong set of keywords. That doesn't suggest they're actually useful to be in the same property.

(This is ignoring the larger issue about Masonry being a different display type in the first place; regardless of that, I think they're still best as separate properties. But if it is a separate display type, they're clearly best as separate properties imo.)
