### ISSUE TITLE
[css-display] What are "form controls"?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#1024]
https://github.com/w3c/csswg-drafts/issues/540 introduced language like this:

> This value has no effect on replaced elements and form controls; it computes to inline exactly as if the UA style sheet had specified display: inline !important on such elements.

The term "form controls" is not defined, so I have no idea how to go about implementing this.

@fantasai @zcorpan @MatsPalmgren

**Comment by bzbarsky** [comment]
More generally, though, I think this approach is not great: it inhibits sharing and caching of computed style data in nasty ways, because now you have to worry about which exact elements are being styled, not just the styles themselves, to determine whether you get the same computed styles given identical specified style inputs.

**Comment by emilio** [comment]
I believe it makes sense to just ignore display: contents and make it act as an inline, just as `svg { display: flex }` is treated as block-like, even though it computes to `flex`.

**Comment by MatsPalmgren** [comment]
This is what the CSSWG actually decided:
> RESOLVED: display:contents behaves as display:inline for all replaced elements and all form controls
https://lists.w3.org/Archives/Public/www-style/2017Feb/0062.html

@fantasai It seems to me that the [spec change](https://github.com/w3c/csswg-drafts/commit/c5883769811572326a1f83ec157c1e23855526c2#diff-427e5632e9d9c59b6f288a0677aea6bfR485) doesn't correspond to what was actually decided. ("behaves as" does **not** mean "computes to")

**Comment by SelenIT** [comment]
Shouldn't the term 'replaced elements' be clarified, too? The ["Rendering" section of HTML spec](https://html.spec.whatwg.org/multipage/rendering.html) clearly places "Form controls" into "Non-replaced elements" list. Also, according to the current definition from CSS2.1+

> An element whose content is outside the scope of the CSS formatting model

the `button` element, for example, doesn't fit to the replaced element definition, since its content is the regular HTML DOM subtree, styled with normal CSS by the CSS formatting rules. Moreover, form controls internally presented as UA Shadow DOM components styled with UA built-in styles still belong to the CSS formatting model, and therefore don't completely match the definition of 'replaced elements'.

Doesn't the CSS definition of "replaced elements" need to be updated?

**Comment by zcorpan** [comment]
Nothing claims that `button` is a replaced element, and it isn't one. I think HTML says already which *are* replaced elements. So is there a problem?

**Comment by SelenIT** [comment]
Until HTML clarified their definintion, there was some ambiguity that [allowed](https://bugzilla.mozilla.org/show_bug.cgi?id=733914#c2) to treat `button` as a replaced element.

**Comment by astearns** [comment]
Will defer to the whatwg/html issue on this, and have our specs reference their solution

**Comment by fantasai** [comment]
(And in the meantime have a handwavy definition pointing vaguely at it. ;)

**Comment by fantasai** [comment]
Okay, pushed changes. The handwavy definition is “replaced elements, form controls (i.e. user interface elements whose element type can accept and/or submit user data, such as `<input>` and `<button>`), and (obviously) empty elements”. We'll replace with a link to HTML once we have a target.

Let me know if there's any problem with the changes. Closing until then. :)

**Comment by fantasai** [comment]
Actually, the definition of [submittable element](https://html.spec.whatwg.org/multipage/forms.html#category-submit) is better than that parenthetical, so using that for now.

**Comment by bzbarsky** [comment]
@fantasai What about https://github.com/w3c/csswg-drafts/issues/1024#issuecomment-279634498 ?  Is that being tracked somewhere?

**Comment by fantasai** [comment]
@bzbarsky Yep. #540

**Comment by bzbarsky** [comment]
Ah, great, thank you.
