### ISSUE TITLE
[css-values-5] Does serializing calc-size() ever change the number of arguments?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#10259]
The [definition of `calc-size()`](https://drafts.csswg.org/css-values-5/#calc-size) doesn't mention serialization at all, and I think it probably should.  In particular, the question I have about serialization is whether the number of arguments to `calc-size()` should ever change during a parse-serialize cycle.  I think there are three options:

1. Rerialize to the one-argument form whenever possible, otherwise serialize to the two-argument form.  This has the downside that the two-argument form is often clearer, I think.
2. Remember the number of arguments given and serialize in the form given.
3. Always serialize to the two-argument form.

Based on what `calc-size()` does I don't especially like option 1.  General principles of CSS serialization probably don't like 3, since shorter forms are generally preferred.  And since this question applies to both specified and computed values (though the answer *could* be different for the two), and option 2 is pretty strange for computed values, I also don't particularly like option 2.

cc @tabatkins

**Comment by tabatkins** [comment]
I agree that this needs specification. I lean towards option 3; I agree that in general the two-arg form is clearer.

**Comment by dbaron** [comment]
I've [implemented](https://chromium-review.googlesource.com/c/chromium/src/+/5497408) option 3 in Chromium.

**Comment by dbaron** [comment]
Though thinking about it a little more, I think perhaps another argument against option 3 is that, without it, authors basically never need to write the two-argument form.  For most things authors want, they just want to wrap one or both of the endpoints of an animation in `calc-size()`.  So having the two-argument form appear for those cases might be confusing.

**Comment by tabatkins** [comment]
I'm fine with either 1 or 3, so if you're leaning towards 1 after some thinking, I'm happy to spec that.

**Comment by bramus** [comment]
With [the single-argument form of `calc-size()` being dropped](https://github.com/w3c/csswg-drafts/issues/10478#issuecomment-2274243309), I believe this issue may be closed.
