### ISSUE TITLE
[cssom-view] offsetParent zoom handling seems wrong.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10252]
https://drafts.csswg.org/cssom-view/#dom-htmlelement-offsetparent has:

> The element has a non-default used value of [zoom](https://drafts.csswg.org/css-viewport-1/#propdef-zoom).

But afaict that's not what's implemented in engines. What's implemented is "The element has a different used value of "zoom".

Is my read of the WebKit / Blink code correct @chrishtr? If so we should update the spec. We have tests that depend on that difference.

**Comment by chrishtr** [comment]
> Is my read of the WebKit / Blink code correct @chrishtr? 

Yep [you're right](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/layout_object.cc;l=4467;drc=1e688463e91aa65cd47d54b7c2a8c4516b912646). Good catch. I'll make a PR to fix the spec.
