### ISSUE TITLE
[css-color] is it practical to help building and grounds maintenance occupations match paint color?

### ISSUE THREAD

**Issue by sword-2** [w3c/csswg-drafts#10269]
Would it make sense for the CSS Color Module (reference 1) to say whether it was practical to support building and grounds maintenance occupations to match a paint color when repainting a facility? If the maintenance person would be taking unnecessary risk by trying to match CSS colors, would a warning to not try this be appropriate?

CSS color codes might be derived by operating other systems like a camera, camera lighting tripods, computer monitor, photo color extractor (ref 2), and printer. The CSS color codes could then be offered to the paint vendor to buy a new batch of paint. If the scope has to be limted to CSS, could the CSS represent the paint color(s) if the other equipment it interfaced with was reliable to not make some color alteration?

Advice could help noob reduce risk. I already damaged a photography lighting tripod when it blew over in the wind taking pics of paint samples, thus have not yet done a good work as hoped (Matthew 5:16).  It would be worse if a color was somehow altered by the operator, camera, printer, or color extrator, then bought and applied to the facility.

Reference(s)
1.
CSS Color Module Level 5
https://www.w3.org/TR/css-color-5/
2.
color-palette-extraction
https://github.com/zygisS22/color-palette-extraction

**Comment by Crissov** [comment]
If I understand the issue correctly, you want to be able to provide a *canonical paint color code* for a CSS color. I have [suggested something similar](https://github.com/w3c/csswg-drafts/issues/5730#issuecomment-797352822) a couple of years ago. 
Or maybe you are asking for a conversion algorithm to unambiguously represent any CSS color within an unidentified (universal?) paint color code system.

**Comment by sword-2** [comment]
Your suggestion a couple of years ago, if I understood, was to help facilitate custom color spaces. If there was a space with paint color codes, I would investigate applying some of those colors. Maybe selecting an existing HTML color name that is closest to the color  (https://htmlcolorcodes.com/color-names/) is practical for now, and could avoid more work? Other color spaces (standards) were observed such as sRGB, paint color cards at a paint pro’s store, local home improvement store, SAE-AMS-STD-595 Colors Used in Government Procurement, etc. Your suggestion might facilitate the colors for those groups, but exceeds my scope to say.

A color conversion algorithm (procedure) is an internal detail if custom color matching becomes necessary (HTML color names don’t succeed). If the paint pros are members of the W3C or CSS working groups, maybe they would be best to describe their special equipment, processing algorithms, and color codes. I estimate they are not currently reporting CSS codes, but this exceeds my scope too.

I assumed the color module scope included W3C noob, but could be wrong. Noob involvement could just include warning/caution if they should or should not attempt a paint application. This was unclear with all the apps available to install and websites which allowed color selection.

**Comment by tabatkins** [comment]
I'm sorry, I also can't tell what it is you're asking about. It seems to be something about whether it's appropriate to use CSS colors to define the colors of physical paint?

In general, no, you should be using whatever color description format your paint vendor uses. Matching colors across wildly different mediums with wildly different display physics (computer monitors vs outdoor paint) is a complex and difficult process. The CSSWG is concerned with colors insofar as they're used *on the web*, and somewhat in adjacent media (like printing a web page). Your use-case is far outside of what we work on.
