### ISSUE TITLE
[css-align-3] Incorrect syntax for <baseline-position>

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#10273]
From what I can tell, baseline-position is only intended to accept the following 3 values exactly:
`baseline`
`first baseline`
`last baseline`

If that's correct, the syntax should be:
`[ first | last ]? baseline`

As opposed to using the `&&` which allows for any order of elements.
https://github.com/w3c/csswg-drafts/blob/13e83cee9d7d41054637e43bda7ac9981fade8d0/css-align-3/Overview.bs#L602

**Comment by tabatkins** [comment]
In general, we allow reordering of values when it doesn't otherwise cause ambiguity. `first baseline` is allowed, yes, but it's intended that `baseline first` is also allowed. That's why the grammar is written the way it is. ^_^
