### ISSUE TITLE
Editorial suggestions from HR

### ISSUE THREAD

**Issue by pes10k** [w3c/csswg-drafts#10283]
These issue is from [PINGs HR](https://github.com/w3cping/privacy-request/issues/133) of the "[CSS View Transitions Module Level 2](https://drafts.csswg.org/css-view-transitions-2/)" spec.

These aren't privacy relevant issues, so just filing them as non-blocking suggestions and comments

- I think the same concept / category is referred to both as [page initiated navigation](https://drafts.csswg.org/css-view-transitions-2/#activating-cross-document-view-transition) and [user initiated navigation](https://drafts.csswg.org/css-view-transitions-2/#lifecycle). I think the goal here is just to distinguish CSS-view-transition-relevant navigations from browser initiated navigations (like the URL bar).  But if I'm understanding right and these two terms are describing the same thing, I suggest just using one term throughout the document (either page or user initiated navigations)
- theres a word missing in section 2.1.4, point 2.3 ("This is another opportunity for the author customize the transition")

**Comment by svgeesus** [comment]
@khushalsagar are the two terms the same?

**Comment by khushalsagar** [comment]
Thanks for the thorough review @pes10k. Addressing them here: https://github.com/w3c/csswg-drafts/pull/10284.

@svgeesus the PR above uses the same terms to avoid confusion. The intent is the same, VT excludes navigations initiated via browser UI *except* back/fwd.

**Comment by pes10k** [comment]
@khushalsagar left a minor comment / nit on the PR.  Thank you for being so quick on this!
