### ISSUE TITLE
[css-anchor-positioning-1] [scroll-animations-1] [css-view-transitions-1] Scoping names on elements based on tree scope

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#10304]
Both https://github.com/w3c/csswg-drafts/issues/10145 and https://github.com/w3c/csswg-drafts/issues/10303 are tackling how view-transition-name applies across tree scopes. But the conceptual problem seems common across other features like anchor positioning or scroll driven animations which have a similar pattern of assigning names to elements which are later used for animations/layout tied to a tree scope. Please add if I missed a feature!

Filing this issue to decide whether each feature needs to define their own behaviour when dealing with shadow DOM or do the choices we make on the VT issues make sense across all such naming properties in CSS.

@astearns.

**Comment by fantasai** [comment]
@khushalsagar Would you mind inventorying what we've got / decisions we've made about this so far? :)

**Comment by khushalsagar** [comment]
@flackr pointed out that `@property` declarations behave as per spec, i.e., declarations in the outer scope are visible in inner scope. Here is an example: https://jsbin.com/xoqebek/edit?html,output (credits to @flackr).

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
<div id="host">
  <template shadowrootmode="open">
    <div class=outer>I'm in the shadow DOM using outer names</div>
    <div class=inner>I'm in the shadow DOM using inner names</div>
    <style>
      @property --inner-property {
        syntax: "<color>";
        inherits: false;
        initial-value: green;
      }
      @keyframes inner-anim {
        from { opacity: 1;}
        to { opacity: 0;}
      }
      .outer {
        animation: outer-anim 1s infinite;
        color: var(--outer-property);
      }
      .inner {
        animation: inner-anim 1s infinite;
        color: var(--inner-property);
      }
    </style>
  </template>
</div>
  <style>
    @keyframes outer-anim {
      from { opacity: 1;}
      to { opacity: 0;}
    }
    @property --outer-property {
      syntax: "<color>";
      inherits: false;
      initial-value: green;
    }
    #outer {
      animation: outer-anim 1s infinite;
      color: var(--outer-property);
    }
    #outer-inner {
      animation: inner-anim 1s infinite;
      --inner-property: jfaowiej; /* not a valid color so will be discarded if property registration is used. */
      color: var(--inner-property);
    }
  </style>
  <div id="outer">I'm in outer DOM using outer names</div>
  <div id="outer-inner">I'm in outer DOM using inner names</div>
</body>
```

**Comment by khushalsagar** [comment]
The proposal here seems relevant to this problem: https://github.com/w3c/csswg-drafts/issues/8915#issuecomment-2174193363.

If the idea in the existing spec makes sense then the above proposal could be the opt-in to gate exposing of names as defined in that spec (in terms of priority order). The spec misses defining how an outer tree scope can use names in inner tree scopes but I think that could be as simple as deciding based on the DOM order of the roots associated with descendant tree scopes.

**Comment by noamr** [comment]
> @flackr pointed out that `@property` declarations behave as per spec

Also `@font-face`.

**Comment by noamr** [comment]
I'm not convinced that what's described for at-rule declarations at https://drafts.csswg.org/css-scoping-1/#shadow-names applies to peer-to-peer names like `view-transition-name` and `view-timeline-name`. IMO as a general rule those should be 100% scoped to the tree where they're defined, and there should arguably be a way to pierce through the shadow boundary for particular names (though #10303  might be enough here).

**Comment by khushalsagar** [comment]
Closing this based on the clarification at https://github.com/w3c/csswg-drafts/issues/10325#issuecomment-2207130024.
