### ISSUE TITLE
[css-anchor-position] should alignment safety consider the containing block?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10316]
Alignment has a concept of "safety", which is, we try to bias alignment in a direction that won't result in clipping the content. For `unsafe` centering, we don't care; but for `safe` centering we overflow away from the unscrollable region.

For anchor positioning (and absolute positioning in general to be fair), there's two containers that are of interest: the inset-modified containing block, and the actual containing block.

Should the default behavior and/or the `safe` behavior of an overflowing alignment bias towards staying within the containing block if possible, before finally overflowing the end/end edges?

**Comment by fantasai** [comment]
Proposal here is:

- When `unsafe`, do unsafe alignment into the inset-modified containing block. (No change)
- When `safe`, overflow the IMCB in the "safe" direction. (No change)
- By default, do unsafe overflow of the IMCB, but safe overflow of the CB.
   I.e. as you grow:
    1. Align within the IMCB as specified.
    2. If as you grow you overflow the IMCB, keep aligning as specified.
    3. If as you grow you reach the edge of the CB, don't overflow that edge, grow in the other direction.
    4. If as you grow you overflow the CB, do safe alignment (overflow away from the unscrollable region).

**Comment by bfgeek** [comment]
I suspect that anything changing default alignment won't be web-compatible given how long folks have been relying on abspos layout.

**Comment by tabatkins** [comment]
Yeah, I'm definitely comfortable with keeping the legacy behavior (aka skipping `iii` in the list) for `normal` alignment, and possibly even for start/center/end. It's really only *important* for anchor-center.
