### ISSUE TITLE
[css-anchor-position] Initial value of `position-anchor` should be `auto` not `implicit`

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10312]
The syntax of `position-anchor` is `<dashed-ident> | implicit` with the initial value being `implicit`. “Implicit” is a great spec word, but it is fairly advanced vocabulary and not a term we have put into the authoring syntax space before. The typical keyword for this kind of thing in CSS is `auto`. We should rename it to `auto`.

**Comment by mfreed7** [comment]
This is a reasonable point. +1 to renaming `implicit` to `auto`. Let’s get a resolution on Wednesday if possible. Chromium is happy to ship this change, ASAP.

**Comment by yisibl** [comment]
Is the `implicit` value also removed from `anchor-size()`?

Until then, `anchor-size(implicit width)` is a legal value.

**Comment by astearns** [comment]
@yisibl the syntax change looks right to me (see the change in the `<anchor-element>` component definition)

But there are still several prose references to an `implicit` keyword that should be removed (in 2.1.1 and 2.3)

**Comment by yisibl** [comment]
@astearns So after the syntax change, will `anchor-size(implicit width)` become `anchor-size(width)` ?

**Comment by astearns** [comment]
@yisibl that is my reading. @tabatkins are we correct?

**Comment by tabatkins** [comment]
Correct. The reduced version is *already* correct syntax with that meaning, it just will no longer be valid to write the `implicit` keyword explicitly.
