### ISSUE TITLE
[css-anchor-position] revert-layer should only revert the Position Fallback Origin

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10319]
The current spec defines the Position Fallback Origin with a special rule as follows:

> Similar to the Animation Origin, use of the revert or revert-layer values (or anything else that would rollback the property to the preceding origin) acts as if the property was part of the Author Origin. (Thus, it instead reverts back to the User Origin.)

However the `revert-layer` keyword [does not have this behavior](https://www.w3.org/TR/css-cascade-5/#revert-layer). It's a [special rule](https://www.w3.org/TR/css-cascade-5/#default) that applies only to the `revert` keyword.

It should therefore only apply to the `revert` keyword (and not the `revert-layer` keyword) when used in the Position Fallback Origin also.

**Comment by frivoal** [comment]
A resolution wouldn't hurt, though I suppose this could fall under "Accepted as Obvious Bugfix" too.
