### ISSUE TITLE
[css-anchor-position] anchor-size() argument should be optional

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10318]
The `anchor-size()` function, which is defined as a function of the sizing properties (width/height/etc.) has the following syntax:

```
anchor-size() = anchor-size( <anchor-element>? <anchor-size>, <length-percentage>? )
<anchor-size> = width | height | block | inline | self-block | self-inline
```

That means in most cases, authors will be writing something like `height: anchor-size(height)`. This seems silly. Shouldn't the `<anchor-size>` argument be optional, defaulting to the dimension matching the sizing property's effect?

**Comment by nt1m** [comment]
A function computing to a different value depending on which property it's used on is a bit odd and unlike CSS in general. 

e.g. `height: anchor-size()` and `width: anchor-size()` shouldn't compute to different values.

Something more CSS-like would probably be a keyword: `height: anchor-size` or `height: match-anchor` or similar.

**Comment by fantasai** [comment]
It doesn't seem odd to me. The `anchor()` function itself does that also.

**Comment by tabatkins** [comment]
My only concern is that if we wanted to allow more information to come in (the anchor's margin, or the anchor's right inset-area track, etc), it might not be as clear what the "default" is.

But I don't think I'm opposed to this, if you think that's reasonable given that sort of possible future development.

**Comment by yisibl** [comment]
So how does block-size match the default value?

`block-size: anchor-size()` matches to `block-size: anchor-size(block)`?

**Comment by fantasai** [comment]
@yisibl I think this is the obvious interpretation.
