### ISSUE TITLE
[css-anchor-position] Flat tree vs. anchor-scope

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#10325]
The spec says anchor-scope scopes to "this subtree". It's not clear enough what we mean by that.

I suggest changing to "inclusive [flat tree](https://drafts.csswg.org/css-scoping-1/#flat-tree) descendants".

@tabatkins

**Comment by fantasai** [comment]
See https://github.com/w3c/csswg-drafts/issues/8192 which is about similar concerns. Maybe we could re-use the wording.

(Probably this should be generalized into css-display.)

**Comment by andruud** [comment]
Proposed resolution: `The anchor-scope property scopes to the flat tree`

**Comment by astearns** [comment]
@fantasai do you agree with this wording?

**Comment by fantasai** [comment]
I think it's overly specific, and prefer using the wording from https://github.com/w3c/csswg-drafts/issues/8192#issuecomment-1487567979 (as I said above). The way it's stated now it raises more questions about what else might be operating over the flat tree or not-flat tree.

**Comment by andruud** [comment]
@fantasai OK, so in other words, something like: `features in this specification operate over the flattened element tree` ?

**Comment by khushalsagar** [comment]
Scoping to the flat tree sounds like names in inner tree scope would be visible to the outer tree scope. This is not lining up with the resolution on https://github.com/w3c/csswg-drafts/issues/10145#issuecomment-2100931679 where for view transition the lookup is tree scoped. And conversations on https://github.com/w3c/csswg-drafts/issues/10304 for a general policy for all CSS names.

Also @annevk specifically said by default all CSS names should be tree scoped as a general encapsulation principle for shadow DOM here: https://github.com/w3c/csswg-drafts/issues/10145#issuecomment-2175556049.

**Comment by noamr** [comment]
We've discussed something related in view-transitions: https://github.com/w3c/csswg-drafts/issues/10145#issuecomment-2206800759. To reiterate: we want to make sure that decisions about name encapsulation are consistent across these features. Currently the direction for anchor positioning seems to be to use the flattened tree and have a CSS-based scoping property (`anchor-scope`). If this is the direction then we should do the same for view transitions, and revert the decision to have view-transition-names tree-scoped. CCing @fantasai, @nt1m and @annevk, as I feel that having a consistent view about this problem from Apple would be very helpful to the discussion.

**Comment by andruud** [comment]
Not to worry @khushalsagar and @noamr, anchor lookup is already tree-scoped in the spec, and this issue does not change that. The anchor-scope property is an _additional_ scoping mechanism that can only reduce the scope of things further. It does not change nor loosen the restrictions of tree-scoped lookups.

This issue is about exactly how to "look for" the anchor-scope-element. We either need to look at a given element's flat-tree ancestors, or the light tree ancestors. I do think we need the flat tree ancestors for this to work well, otherwise an anchor styled with ::slotted() can never be in an anchor-scope defined within the shadow root.
See https://github.com/web-platform-tests/wpt/blob/313fd03a0b/css/css-anchor-position/anchor-scope-shadow.tentative.html for an example where the distinction makes a difference.

**Comment by khushalsagar** [comment]
Hmmm yea, I misunderstood. When we say a name is tree scoped it means it *can* be used as a reference by elements in descendant/inner tree scopes. But a name in a descendant tree scope *can not* be referenced by elements in ancestor tree scopes.

This might be worth a note in the scoping spec.
