### ISSUE TITLE
[css-fonts] Should font-synthesis be reset by font shorthand?

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1032]
The spec doesn't mention `font-synthesis` as a subproperty of `font` shorthand, but given its name, it probably should be.

Gecko resets `font-synthesis` when setting `font`, while WebKit doesn't.

Test code:
```html
<!DOCTYPE html>
<div style="font-synthesis: style; font: 14px sans-serif;"></div>
<script>
  alert(document.querySelector('div').style.fontSynthesis);
</script>
```

cc @nattokirai @litherum

**Comment by litherum** [comment]
Why should it be reset when none of its values are present in the shorthand? That doesn't make any sense. Just because it starts with the word `font` doesn't mean that it should be part of the shorthand.

**Comment by upsuper** [comment]
Many other font properties do not have any value present in the shorthand, but they are still reset, which makes sense because author should expect `font` shorthand to reset all the font style, and it is why we have shorthand.

But, yeah, whether `font-synthesis` should be reset in `font` shorthand is probably arguable. It is probably not really counted as a font style property like `font-kerning` or `font-language-override`. (BTW, probably `font-feature-settings` should really be reset by `font` shorthand thereby?)

If it is intentional that `font-synthesis` should not be reset by `font` shorthand, I guess it is at least worth a note in the shorthand section stating something like
> `font-synthesis` is not reset by this shorthand, since it is considered a font style property.

WDYT?

**Comment by litherum** [comment]
I don't think we need a note mentioning that a shorthand doesn't include some other property.

**Comment by litherum** [comment]
I don't have a strong preference. I'm happy to put it in.

**Comment by fantasai** [comment]
There's a similar note wrt `text-emphasis-position`: https://drafts.csswg.org/css-text-decor-3/#text-emphasis-property

**Comment by tabatkins** [comment]
I agree that this shouldn't be reset by 'font'; whether you want to synthesize bolds/etc is *mostly* independent of the font you choose.

**Comment by svgeesus** [comment]
@upsuper do you agree with tab that this should not reset?

**Comment by upsuper** [comment]
I don't have strong opinion either way. Given @tabatkins and @litherum prefer that way, I'm fine with that. I still think it's worth a note in the spec, though.

**Comment by svgeesus** [comment]
Happy to note in the spec that this is not reset by the font shorthand.

**Comment by svgeesus** [comment]
> Why should it be reset when none of its values are present in the shorthand? That doesn't make any sense. Just because it starts with the word font doesn't mean that it should be part of the shorthand.

On the other hand, we already have (my italics):

>> Additionally, it is a shorthand for font-size-adjust, font-kerning, and font-language-override, but as these _cannot be specified in the syntax_, it merely resets these to their initial values.
https://drafts.csswg.org/css-fonts-3/#font-prop

So it certainly seems worthwhile to explicitly state that `font-synthesis` is not set to the initial value by the `font` shorthand.
