### ISSUE TITLE
[cssom] Serialization of CSS declaration block returned from getComputedStyle

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1033]
How should CSS declaration block returned from `getComputedStyle` be serialized? It contains all longhand properties.

Currently, Gecko and Edge return empty string for it, while WebKit and Blink (probably inherit from WebKit) seem to return serialization of all longhand properties (i.e. not trying to generate shorthands). Apparently none follows the spec.

Following the same algorithm for `cssText` of declaration block from `getComputedStyle` is complicated, and probably isn't worth. So I suggest that the spec should either follow Gecko and Edge to return empty string, or follow WebKit and Blink to just return all longhand properties.

I would prefer we just make it return empty string... But there is a webcompat issue reported to Firefox for lack of its support: webcompat/web-bugs#3822. This is a Google website though, so maybe we can just ask Google to fix it and ignore this issue...

**Comment by mrego** [comment]
We've similar issues in CSS Grid Layout spec.
This was an old mail to `www-style`: https://lists.w3.org/Archives/Public/www-style/2015Jul/0242.html

A very basic example:
```js
myGrid.style.grid = "100px / 50px";
console.log("style: " + myGrid.style.grid);
console.log("computedStyle: " + getComputedStyle(myGrid).grid);
```

The output right now in Chrome is:
```
style:
computedStyle: 100px / 50px / none / row / auto / auto / 0px / 0px
```

And in Firefox:
```
style: 100px / 50px;
computedStyle:
```

**Comment by upsuper** [comment]
I don't think that's something related. IIRC in general we don't serialize new shorthands in computed style, only longhands are serialized there. There are several shorthands get serialized in computed style just for backward compatibility.

**Comment by mrego** [comment]
Oops, ok I messed it up, I thought you were talking about shorthands.

**Comment by FremyCompany** [comment]
(Adding myself to the thread; but could you clarify what you think Chrome doesn't do per standards here? I have the impression their behavior is correct in that case at first glance)

**Comment by upsuper** [comment]
> could you clarify what you think Chrome doesn't do per standards here? I have the impression their behavior is correct in that case at first glance

In the spec, the [serialize a CSS declaration block](https://drafts.csswg.org/cssom/#serialize-a-css-declaration-block) algorithm tries to construct shorthands whenever possible. In case of declaration block from `getComputedStyle`, since all longhands are available, most of shorthands would be constructible. However, Chrome doesn't seem to construct any shorthand in that case.

**Comment by tabatkins** [comment]
On the call today WG resolved to accept Firefox's and Edge's behavior, and make the object serialize to th empty string.

I'll file a bug on Chrome to fix this, and start evangelizing at Drive to fix the webcompat bug.

**Comment by FremyCompany** [comment]
Thanks Tab!

**Comment by zcorpan** [comment]
> There are several shorthands get serialized in computed style just for backward compatibility.

Which are these?

**Comment by upsuper** [comment]
Mainly the shorthands which are previously longhands, e.g. `background-position`, `text-decoration`, `overflow`, and `mask`.

**Comment by zcorpan** [comment]
Given the following case, it seems browsers all have some logic to try to serialize as shorthands when possible. It's unclear to me why we want to avoid doing that for `getComputedStyle` specifically?

 http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4948
```
<!DOCTYPE html>
<p style="border:1em solid">
<p style="border:1em solid; border-right-width: 1px">
<p style="border:1em solid; border-right-width: 1px !important">
<script>
for (var p of document.querySelectorAll('p'))
  p.style.color = 'purple';
</script>
```
(check the value of the `style` attributes after the script has run.)

**Comment by emilio** [comment]
@tabatkins Could you link it to the Chrome bug if you can find it please? I think this resolution makes sense, but Chrome hasn't updated its behavior yet :/.

I'll file a WebKit bug pointing to that bug as well.

**Comment by carlosame** [comment]
Like @zcorpan , I do not see for which reason computed styles cannot have a meaningful serialization. A computed style is still a style, after all.

I'm the developer of a CSS tool (a CSSOM library) that happens to behave like Chrome (although there is an optional method that builds the shorthands), and see no reason to change to returning an empty string (what's more, I have users depending on the current behaviour).

**Comment by upsuper** [comment]
@zcorpan @carlosame 

From the implementation side, computed style and specified style are usually stored in different forms in browsers, and when browsers are asked to serialize a computed value, they serialize it from its internal form directly (rather than, say, convert to specified value then serialize the latter), however, shorthand serialization algorithms are usually written to handle declaration block of specified values.

It means that to serialize declaration block from gCS per spec, browsers would need extra work either to implement all shorthand serialization algorithms on computed value as well, or create a declaration block containing every property in their specified value form, and then use the algorithm of specified declaration block to serialize them.

Doing such conversion is not impossible, though. Actually, at least in Gecko, we have such mechanism for animation and transition, because our cascading is based on specified value, but interpolation happens on computed value, so we need to "uncompute" value to cascade animation and transition correctly.

However, many properties are required to serialize differently for gCS, and the "uncompute" mechanism may not exactly match that requirement, so reusing it can potentially further complicate things.

From the use case side, I'd argue that getting a serialization of a declaration block containing every property with shorthand serialized properly is hardly the ideal way for anything.

If you just want to persist and restore all values, you should just iterate all properties in that block, that would almost certainly be faster than relying on browser to generate the serialization of the huge declaration block, then parsing this huge serialization again, as can be seen in the discussion of webcompat/web-bugs#3822.

Also, shorthand serialization are usually for human readability, but would anyone want to read a declaration block serialization containing hundreds of properties?

Given that this needs probably non-trivial extra work on implementations, while it doesn't seem to be very useful, we should probably just make it as simple as possible so that implementations can be interoperable on the behavior.

**Comment by upsuper** [comment]
> but I do not know whether it serializes all the properties or only the cascaded-or-inherited, as I mentioned

Every element has value for every property, so it has to be listing all of them.

> My serializations do not (generally) contain hundreds of properties. I do not include properties that take their initial values due to defaulting (and the count of properties that are cascaded or inherited is what I return in `getLength()`, and not the total amount of properties known to my library).

That is very different from what computed value means to be.

**Comment by carlosame** [comment]
> Every element has value for every property, so it has to be listing all of them.

A computed style needs to be able to retrieve a value for each property (for example with ```getPropertyValue()```), but it is unclear that the gCS serialization _must_ include all of them.

We are discussing about what the serialization should be, and now leaping from "the empty string" to "it has to be listing all of them".

> That is very different from what computed value means to be.

```getLength()``` on a computed style becomes totally meaningless if you do not define it that way.

The basic idea is: if you need the computed value for a given property, use ```getPropertyValue()``` (I also provide ```getPropertyCSSValue()```). But my gCS serialization behaves as described previously, and IMHO is very meaningful (and far better than the empty string).

**Comment by carlosame** [comment]
A small clarification to my previous comment: in my library, the ```getPropertyValue()``` in the computed styles returns a value for properties that aren't found in the ```item``` collection, if the library knows about its initial value. The ```item``` method only returns the properties that were cascaded or inherited.

That's what I meant with:

> if you need the computed value for a given property, use getPropertyValue()

**Comment by karlcow** [comment]
Like @emilio I was looking for the chromium bug links. so here it is.

* [Issue 1146888: CSSStyleDeclaration.cssText should return empty string for computed style](https://bugs.chromium.org/p/chromium/issues/detail?id=1146888)
* [Issue 1192564: window.getComputedStyle(el).cssText returns an empty string](https://bugs.chromium.org/p/chromium/issues/detail?id=1192564)

I can't find the webkit one.

**Comment by graouts** [comment]
This will be fixed in WebKit with [bug 232943](https://bugs.webkit.org/show_bug.cgi?id=232943).
