### ISSUE TITLE
[cssom-view] Change `document.caretPositionFromPoint`'s `shadowRoots` parameter from rest parameter to an array

### ISSUE THREAD

**Issue by siliu1** [w3c/csswg-drafts#10345]
The `shadowRoots` parameter is defined in the [spec](https://drafts.csswg.org/cssom-view/#ref-for-dom-document-caretpositionfrompoint) as a rest parameter of type `ShadowRoot`.

We should change it from rest parameter to a single array of shadow roots. Similar to https://html.spec.whatwg.org/#gethtmloptions. It'd be good to be consistent.

**Comment by siliu1** [comment]
@mfreed7 FYI I opened this issue to update the spec for `document.caretPositionFromPoint` to take a single array of shadow roots instead of using a rest parameter.

**Comment by mfreed7** [comment]
> @mfreed7 FYI I opened this issue to update the spec for `document.caretPositionFromPoint` to take a single array of shadow roots instead of using a rest parameter.

+1. That aligns with `getHTML()` and also allows additional arguments to be added later.

> Doesn't seem unreasonable, but it might be even better to make it a dictionary argument so we can add more arguments there in the future.

+1 to that also. It makes the name of that argument explicit, which is nice, and allows additional arguments in an even better way.

By the way, I think we should make the same change to `getComposedRanges()` for all of the same reasons.

**Comment by siliu1** [comment]
Proposed solution: Put the array of shadow roots into a dictionary which is an argument of `document.caretPositionFromPoint` API. 

```
document.caretPositionFromPoint(double x, double y, optional CaretPositionFromPointOptions options = {});

dictionary CaretPositionFromPointOptions {
  sequence<ShadowRoot> shadowRoots = [];
};
```

**Comment by siliu1** [comment]
> > @mfreed7 FYI I opened this issue to update the spec for `document.caretPositionFromPoint` to take a single array of shadow roots instead of using a rest parameter.
> 
> +1. That aligns with `getHTML()` and also allows additional arguments to be added later.
> 
> > Doesn't seem unreasonable, but it might be even better to make it a dictionary argument so we can add more arguments there in the future.
> 
> +1 to that also. It makes the name of that argument explicit, which is nice, and allows additional arguments in an even better way.
> 
> By the way, I think we should make the same change to `getComposedRanges()` for all of the same reasons.

Filed https://github.com/w3c/selection-api/issues/176

**Comment by siliu1** [comment]
> Proposed solution: Put the array of shadow roots into a dictionary which is an argument of `document.caretPositionFromPoint` API.
> 
> ```
> document.caretPositionFromPoint(double x, double y, optional CaretPositionFromPointOptions options = {});
> 
> dictionary CaretPositionFromPointOptions {
>   sequence<ShadowRoot> shadowRoots = [];
> };
> ```

@astearns Can we get to resolution of this issue asynchronously with the proposed solution? Thanks!

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Add an array of shadow roots to a dictionary which is an argument of the `document.caretPositionFromPoint` API as described in https://github.com/w3c/csswg-drafts/issues/10345#issuecomment-2118164752

**Comment by astearns** [comment]
RESOLVED: Add an array of shadow roots to a dictionary which is an argument of the `document.caretPositionFromPoint API` as described in https://github.com/w3c/csswg-drafts/issues/10345#issuecomment-2118164752
