### ISSUE TITLE
[css-fonts] should there be more options to font-synthesis?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1034]
https://drafts.csswg.org/css-fonts-3/#font-synthesis-prop

Currently, font-synthesis just takes `none | [ weight || style ]` That works fine for dealing with bold and italics, but there are other things that are synthesized that one may want to turn off.

At least the `font-variant-caps: small-caps` and `font-variant-caps: all-small-caps` seem like good candidates.

**Comment by svgeesus** [comment]
Small caps synthesis is already added in css fonts 4.
