### ISSUE TITLE
[css-values-5] should 'calc-size(0)' work?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#10354]
In https://issues.chromium.org/341564374 @yisibl pointed out that `calc-size(0)` doesn't work.  I think this matches the [current spec](https://drafts.csswg.org/css-values-5/#calc-size) which defines the behavior to work like `calc()`, where it was intentional that `calc(0)` doesn't work.

I think despite the parallels with `calc()` we may want to consider making `calc-size(0)` work correctly, because:
* `calc-size()` is explicitly for lengths only so there's less concern about unit algebra making sense
* it would be nice to preserve the principle that "wrap an animation endpoint in `calc-size()`" works in general, and `0` is one of the most common length animation endpoints.

**Comment by Loirooriol** [comment]
To clarify, this is about unitless lengths. `calc(0)` works fine as an `<integer>`.

**Comment by tabatkins** [comment]
Yes, I think allowing a bare `0` is fine; as you say, we have the necessary context to infer the type (the calculation must be a length).

We probably want to do it as a grammar branch, so only a literal `0` with nothing else works. (Such a calculation would otherwise be invalid since it would type as `<number>`, so this is safe.) If the calculation is any more complex than that, we continue to treat it as a number.

**Comment by dbaron** [comment]
I think now that we've dropped the single-argument form in #10478 (and recommended `interpolate-size` as the way to opt in to animations/transitions rather than wrapping values with `calc-size()`), we should probably just keep the current spec for this one and keep `calc-size()` consistent with `calc()`.

**Comment by tabatkins** [comment]
Yeah, this is just covered by the existing rules now that the arguments aren't mingled any longer - `calc-size(0, ...)` is valid (equivalent to `0px`, as it's a `<length-percentage>`), while `calc-size(..., 0)` isn't legal (it's a calculation, so a literal zero is taken as a `<number>`, so it resolves to the wrong type).

**Comment by dbaron** [comment]
With the current spec I think `0` is valid in neither part, since the basis is defined as `[ <intrinsic-size-keyword> | percentage | <calc-size()> | any | <calc-sum> ]`.  (That's also what Chrome implements -- 0 is valid for neither part.)

@tabatkins do you think that should change?
