### ISSUE TITLE
[css-anchor-position] Make anchor-center work without position-anchor

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#10366]
1. Open
```html
data:text/html;charset=UTF-8, <style>
.anchor { anchor-name: --foo; width: 100px; height: 50px; display: block; margin: 30px auto;} 
.anchored{position: absolute; left: anchor(--foo 50%); top: anchor(--foo bottom); 
justify-self: anchor-center; background: green; padding: .5em 2em;}</style>
<button class="anchor">anchor</button>
<div class="anchored">anchored</div>
```

2. The green element is not horizontally centered with respect to the button.

We must add `position-anchor: --foo` for `anchor-center` to take effect. This is often confusing to the user because `<anchor-element>` is already defined on the `left`.

Can we change the status quo?

**Comment by kizu** [comment]
What if the `anchor-center` could have an optional functional form? Like `justify-self: anchor-center(--foo)`? Having an implicit default as `position-anchor` is good, but if we could allow using an explicit anchor name, it could lead to more flexible styles.

**Comment by tabatkins** [comment]
Theoretically possible (as is adding an optional anchor-name to 'position-area' to do the same) but it doesn't seem necessary currently. `anchor-center` and `position-area` are the only features that actively use the default anchor, and it would be really weird to use them both but with different anchors; the implicit behaviors that depends on the default anchor (scroll adjustment stuff) also would be weird if they didn't work correctly with anchor-center and position-area.

So this is something we could do in the future, if there's need, but for now there's no real reason for it imo.
