### ISSUE TITLE
[css-color-5] Clarification on `none` components in relative color syntax.

### ISSUE THREAD

**Issue by tiaanl** [w3c/csswg-drafts#10360]
I have the following examples from wpt:

```
rgb(from rebeccapurple none none none)
rgb(from rebeccapurple none none none / none)
rgb(from rebeccapurple r g none)
rgb(from rebeccapurple r g none / alpha)
rgb(from rgb(20% 40% 60% / 80%) r g none / alpha)
```
all using `none` somewhere in the components.  My expectation from the spec is that each component should stay `none` in the resulting code: `rgb(from rebeccapurple none none none)` becomes `rgb(none none none)`.

But the current wpt contradicts this assumption.
https://github.com/web-platform-tests/wpt/blob/1f9e1af4e5bbd84e79d8c8cd17a135bcf20f6e2d/css/css-color/parsing/color-computed-relative-color.html#L115

**Comment by svgeesus** [comment]
OK it looks like these tests need review as they encapsulate incorrect assumptions.

**Comment by tiaanl** [comment]
Has there been any clarification on the use of  `none` here?

**Comment by LeaVerou** [comment]
Yeah these WPTs are wrong.

**Comment by svgeesus** [comment]
@tiaanl if you make a PR on WPT to fix them, ping me for a review

**Comment by kbabbitt** [comment]
@LeaVerou @svgeesus @tiaanl 

I'm working on updating Blink to match the discussion in this thread. Here's the WPT change; does it look correct? https://chromium-review.googlesource.com/c/chromium/src/+/5905968/3/third_party/blink/web_tests/external/wpt/css/css-color/parsing/color-computed-relative-color.html

**Comment by LeaVerou** [comment]
@kbabbitt Yes, that looks correct! Thank you!

**Comment by cdoublev** [comment]
Note that there is a [resolution](https://github.com/w3c/csswg-drafts/issues/10328) to serialize with `rgb()` rather than `color()` (as currently specified).

**Comment by kbabbitt** [comment]
Thanks Lea.

@cdoublev:
> Note that there is a [resolution](https://github.com/w3c/csswg-drafts/issues/10328) to serialize with `rgb()` rather than `color()` (as currently specified).

From what I saw, the text in that resolution applies to *declared* values. My understanding was that *computed* values would continue to be serialized according to the text in https://drafts.csswg.org/css-color-5/#serial-relative-color starting with "The serialization of the result of a relative color function..." and referring to the table that follows. Several of the examples in https://github.com/w3c/csswg-drafts/issues/10328#issuecomment-2135948165 appear to be consistent with that understanding. Is there something I missed?

**Comment by cdoublev** [comment]
You are right, sorry. I think I was misled by this in the op:

  > My expectation from the spec is that each component should stay `none` in the resulting code

... which should only apply to declared values.

**Comment by kbabbitt** [comment]
The test changes have landed, so I believe this issue can be closed.

**Comment by tiaanl** [comment]
Thanks everyone for resolving this :+1:
