### ISSUE TITLE
[css-cascade-6] Publish an updated WD

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#10370]
Looking at [the current WD of css-cascade-6](https://www.w3.org/TR/css-cascade-6/) it still includes both the strong and weak scoping steps in the cascade. Since then, with the WG we settled on using only weak scoping, among a few other changes & additions, [as listed in the changes](https://drafts.csswg.org/css-cascade-6/#changes-2022-08):

> - Clarified that [scope proximity](https://drafts.csswg.org/css-cascade-6/#scope-proximity) is a single measurement of the steps between a single [scoping root](https://drafts.csswg.org/selectors-4/#scoping-root) and [scoped style rule](https://drafts.csswg.org/css-cascade-6/#scoped-style-rules) [subject](https://drafts.csswg.org/selectors-4/#selector-subject).
> - Removed strong scope proximity. ([Issue 6790](https://github.com/w3c/csswg-drafts/issues/6790))
> - Removed the scoped descendant combinator (deferred). ([Issue 8628](https://github.com/w3c/csswg-drafts/issues/8628))
> - Added the [CSSScopeRule](https://drafts.csswg.org/css-cascade-6/#cssscoperule) interface. ([Issue 8626](https://github.com/w3c/csswg-drafts/issues/8626))

I think it would be good to publish an updated WD as authors that read the WD will be confused: the thing that’s shipping in Safari and Chrome (and Firefox in the future) implements the cascade as currently described only in the ED, not the WD.

Any concerns with this, @mirisuzanne?

**Comment by mirisuzanne** [comment]
No concerns – happy to publish a new WD.

**Comment by mirisuzanne** [comment]
@astearns @atanassov - I think the changes here are all based on resolutions already, but we could get one here if needed. Maybe at the top of tomorrow's meeting, or async?

**Comment by astearns** [comment]
If all of the normative changes are backed by resolutions you can use https://wiki.csswg.org/spec/publish as the resolution link to publish a regular working draft

**Comment by svgeesus** [comment]
@bramus I see that an updated WD has not been published. Editors @fantasai @mirisuzanne @tabatkins Do you need any help?

**Comment by mirisuzanne** [comment]
I think I was wrong about all changes having resolutions. Issue #8380 (the first bullet in your list) hasn't been discussed. So we should get a resolution either here (to publish) or there (to affirm that change).

**Comment by astearns** [comment]
Is that part of the change perhaps related to https://github.com/w3c/csswg-drafts/issues/7233? I’m guessing the clarification was meant to be followed by defining the ~~ combinator, but that got deferred.

**Comment by mirisuzanne** [comment]
Yeah, I think it came out of discussions around 8380 (>>) and 7233 (~~) which got deferred. Because they made that particularly unclear. But I don't see resolution around it. 🤷🏻‍♀️ I don't think it's controversial. Happy to go ahead and publish. Just something I noticed.
