### ISSUE TITLE
[css-font-loading] Remove the FontFaceSet constructor?

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#10390]
https://crbug.com/40287940 tracks this missing constructor in Chromium. However, it's not clear what a developer could do with a constructed `FontFaceSet`.

According to MDN only Safari has the constructor:
https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet#browser_compatibility

The only tests for `new FontFaceSet` in WPT only checks that a `FontFace` object can be added, but nothing else:

https://github.com/web-platform-tests/wpt/blob/master/css/css-font-loading/fontfaceset-add-css-connected.html

Removing it would be a matter of removing this line and anything connected to it:

https://github.com/w3c/csswg-drafts/blob/3a7db3e637ee1c2ddeb91134872ea9872ec46cce/css-font-loading-3/Overview.bs#L510

**Comment by emilio** [comment]
I was about to file the same issue. +1 to remove on our end too. https://issues.chromium.org/issues/40287940 seems to indicate that Safari was on board with removing it a while ago, is that still the case now? cc @nt1m @smfr

**Comment by tabatkins** [comment]
I'm fine with removing it. At the time I wrote this, I was pretty strong on the "we shouldn't have magic objects that can't be constructed" train, and I assume I expected there might be a use for it. But hey, it's years later and no such use materialized, and only one browser even implemented it, so yeah, let's just kill it.

**Comment by vitorroriz** [comment]
I'm not against removing that as it seems there is not much use for the constructor apart from the one Tab pointed out.

**Comment by svgeesus** [comment]
It does seem like there is consensus to just remove it.

**Comment by svgeesus** [comment]
**Proposed resolution:** Remove the FontFaceSet constructor

**Comment by svgeesus** [comment]
(proposed async in case we don't get to it tomorrow on the call)

**Comment by smfr** [comment]
Closed issue I know, but how do you use FontFace in a worker without the constructor? [The spec](https://drafts.csswg.org/css-font-loading/#fontfacesource-workers) says, in a note:

> [FontFace](https://drafts.csswg.org/css-font-loading/#fontface) objects can be constructed and added to it as normal, which affects CSS font-matching within the worker (such as, for example, drawing text into a [OffscreenCanvas](https://html.spec.whatwg.org/multipage/canvas.html#offscreencanvas)).

Lots of offscreen canvas tests (e.g. http://wpt.live/html/canvas/offscreen/text/2d.text.draw.align.center.html) use this, but oddly don't fail in Chrome/Firefox.

**Comment by emilio** [comment]
@smfr this is about the FontFace**Set** constructor, you can still construct FontFace objects just fine.

**Comment by smfr** [comment]
Got it, I just realized that.
