### ISSUE TITLE
[css-view-transitions-1] [css-view-transitions-2] The metadata of the editor’s draft is wrong

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#10394]
The editor’s drafts of the [css-view-transitions-1](https://drafts.csswg.org/css-view-transitions-1/) and [css-view-transitions-2](https://drafts.csswg.org/css-view-transitions-1/) specs are, respectively, marked as CR and FPWD in the source.

After checking with @fantasai yesterday to confirm, these versions should be marked as ED instead. The [Work Status](https://speced.github.io/bikeshed/#metadata-work-status) field could also use an update.

/cc @khushalsagar @vmpstr

**Comment by khushalsagar** [comment]
@fantasai did you mean ED or WD? I thought we switch to WD after FPWD of a spec.
