### ISSUE TITLE
[css-text] automatic hyphens should repect all kinds of manual hyphens

### ISSUE THREAD

**Issue by chenpighead** [w3c/csswg-drafts#1040]
Quote from the [spec.](https://drafts.csswg.org/css-text-3/#valdef-hyphens-auto),

> Automatic hyphenation opportunities within a word must be ignored if the word contains a conditional hyphen (`&shy;` or U+00AD), in favor of the conditional hyphen(s). However, if, even after breaking at such opportunities, a portion of that word is is still too long to fit on one line, an automatic hyphenation opportunity may be used.

However, I think the idea is to let automatic hyphenations always respect the manual ones, which include both conditional hyphens (`&shy;` or U+00AD) and unconditional hyphens (U+2010 or U+002D). So, I'd like to propose that we address this in the specification.

**Comment by Crissov** [comment]
If I understand correctly this is a duplicate of #618.

**Comment by chenpighead** [comment]
Yes, you're right! Sorry for the spam.
