### ISSUE TITLE
[css-color-5] Missing forms to use to serialize color-mix and relative color

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10415]
CSS Colors 5 defines the absolute color function to use to serialize [`color-mix()`](https://drafts.csswg.org/css-color-5/#serial-color-mix) or a [relative color](https://drafts.csswg.org/css-color-5/#serial-relative-color) as a component of a resolved value, which depends on the color space specified in `color-mix()` or of the origin color.

But it does not say anything for `display-p3`, `a98-rgb`, `prophoto-rgb`, `rec2020`, or a custom color space.

I suspect the requirement should be:

  > The form used depends on the color space [specified with "in" | of the ~~origin~~ relative color]: `lab`, `oklab`, `lch`, `oklch`, serialize with the corresponding function, otherwise with `color()` and the corresponding color space (all sRGB functions use the `srgb` color space).

**edit:** I replaced *origin color* with *relative color*, because I think `rgb(from lab(...) ...)` should serialize with `color(srgb ...)`, as hinted by the relative color, not with `lab(...)`, as hinted by the origin color.

**Comment by svgeesus** [comment]
> **edit:** I replaced _origin color_ with _relative color_, because I think `rgb(from lab(...) ...)` should serialize with `color(srgb ...)`, as hinted by the relative color, not with `lab(...)`, as hinted by the origin color.

Yes, indeed.

> But it does not say anything for `display-p3`, `a98-rgb`, `prophoto-rgb`, `rec2020`, or a custom color space.

I agree those should be added (originally, mixing was restricted to a subset of color spaces)
