### ISSUE TITLE
[css-ruby-1] The default ruby-position for vertical-lr text may not be over 

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1042]
4.1. Ruby Positioning: the ruby-position property
https://drafts.csswg.org/css-ruby-1/#rubypos

The TTML spec currently specifies that the default for text in Mongolian is to put annotations on the left side (the 'before' edge of the line box).  CSS Ruby doesn't specifically say that, but implies it.

My understanding is that actually the default for Mongolian is more likely to be the right side, which i think is `under`.  See an example and reasoning at https://github.com/w3c/mlreq/issues/4

I think there should at least be a note in the CSS Ruby spec to warn developers that they can't just rely on abstract geometrical transformation theories to determine the location of the default placement for vertical-lr text.

**Comment by kojiishi** [comment]
`over` for Mongolian (`vertical-lr`) is on right. The `over` is line orientation relative.  `before` is on left, since it's line progression relative.

**Comment by r12a** [comment]
Ah, i see. Thanks @kojiishi. I misinterpreted what `over` means. For the benefit of others reading this (and to remind myself in the future), `over` is described as 

> ruby text appears line-over the base

where `line-over` links to https://drafts.csswg.org/css-writing-modes-4/#line-over, where a distinction is made between `before` and `over` in the case of vertical-lr text.
