### ISSUE TITLE
 [css-anchor-position] position-visibility initial value should be `always`, not `anchors-visible` ?

### ISSUE THREAD

**Issue by chrisdavidmills** [w3c/csswg-drafts#10425]
When writing MDN docs for anchor positioning, I was a bit confused by [`position-visibility`](https://drafts.csswg.org/css-anchor-position-1/#position-visibility) — the spec says "initial value" is `anchors-visible`, but surely it should be `always`?

From testing:

- If you don't set a `position-visibility` value, an anchor-positioned element is always visible provided it is inside the viewport, regardless of the visibility of its anchor. This is the behavior `always` gives as well.
- `anchors-visible`, on the other hand, causes an anchor-positioned element to be hidden if its anchor is not visible at all in the viewport.

[My demo](https://pr33467.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/position-visibility#examples) illustrates the behavior of the currently-supported values, in case that is helpful.

**Comment by tabatkins** [comment]
The current impl in Chrome isn't reflecting the spec; it indeed is using "always" as the initial value. But the spec's text is intentional - if your anchor is off-screen or otherwise scrolled off, you *usually* want it to hide.

**Comment by chrisdavidmills** [comment]
> The current impl in Chrome isn't reflecting the spec; it indeed is using "always" as the initial value. But the spec's text is intentional - if your anchor is off-screen or otherwise scrolled off, you _usually_ want it to hide.

Thanks @tabatkins, that makes sense. So as soon as an element becomes an anchor-positioned element, per spec it should adopt the `anchors-visible` behavior? 

The way we've currently written it reflects the current implementation, so I think it is OK to publish it like that for now. We'll just have to change it once behavior updates.
