### ISSUE TITLE
[css-images][css-sizing][css-content] elements with intrinsic size but no aspect ratio

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1044]
So far we have concepts of replaced elements that have no intrinsic size, an intrinsic size in one dimension, an aspect ratio but no size, and an intrinsic size and aspect ratio. We assume that if you have two of {aspect ratio, width, height} the third is defined, and this is true of things like images and video. However, form controls seem to behave like objects that have an intrinsic width, and intrinsic height, <em>and no intrinsic aspect ratio</em>.

We need our specs to define this class of objects and define behavior accordingly.

**Comment by ByteEater-pl** [comment]
I don't understand. Isn't the aspect ratio by definition the quotient of width and height? It seems that some other definition is in use here but not stated, making this unclear.

**Comment by tabatkins** [comment]
No, not necessarily. An object has an intrinsic aspect-ratio *if*, when you specify a given width or height, it has a preferred height/width based on that. This isn't necessarily true! As the commit says, some form elements have a preferred width and height, but if you override one, it doesn't change the other.  Making a text input wider doesn't change the fact that it wants to be approximately 1em high, for example.
