### ISSUE TITLE
[css-masking] Formatting error in example 17

### ISSUE THREAD

**Issue by johannesodland** [w3c/csswg-drafts#10456]
(Nit)

There's a formatting error in [example 17](https://drafts.fxtf.org/css-masking-1/#example-c0f95fbd). Some elements are output as `lt;svg>` instead of `<svg>`.

<img width="815" alt="image" src="https://github.com/w3c/csswg-drafts/assets/175195/b7dda029-c427-48e9-bb4f-7971642bb85b">

**Comment by SebastianZ** [comment]
Thank you for noting! I've fixed that now. (Just note that the Masking spec. is currently still part of the fxtf-drafts repository.

Sebastian

**Comment by johannesodland** [comment]
> Thank you for noting! I've fixed that now. (Just note that the Masking spec. is currently still part of the fxtf-drafts repository.
> 
> Sebastian

That's quick. Thank you 🙏
