### ISSUE TITLE
[CSS3PAGE]: Page margin content should be able to display complex HTML content

### ISSUE THREAD

**Issue by SetTrend** [w3c/csswg-drafts#10458]
According to [§ 5.2](https://drafts.csswg.org/css-page-3/#populating-margin-boxes), _"a specified [content: normal](https://drafts.csswg.org/css-content-3/#propdef-content) on a page-margin box computes to [none](https://drafts.csswg.org/css-content-3/#valdef-content-none)."_

Many times, however, headers and footers are more than just an image. They may contain complex HTML content, like this:

![Table and Footer](https://github.com/w3c/csswg-drafts/assets/9283914/c8ade65f-816b-4916-b020-2705135ec8e9)

https://github.com/w3c/csswg-drafts/assets/9283914/e0f8d90f-141b-4057-b92b-3fd1b15db857

► [This is the source used for creating below image: Test HTML page.zip](https://github.com/user-attachments/files/15785803/Test.HTML.page.zip)

<br/>

Please amend the specification to accept complex HTML content.

One solution would be to add new properties for display:

|CSS Property|Values|
|-|-|
|Display| ...<br/>top-left-corner<br/>top-left<br/>top-center<br/>top-right<br/>top-right-corner<br/>left-top<br/>left-middle<br/>left-bottom<br/>right-top<br/>right-middle<br/>right-bottom<br/>bottom-left-corner<br/>bottom-left<br/>bottom-center<br/>bottom-right<br/>bottom-right-corner|

So, a `<footer>` HTML element could be assigned one of the above `display` values and styled accordingly.

This would render [At-rules for page-margin boxes](https://drafts.csswg.org/css-page-3/#margin-at-rules) redundant.

**Comment by faceless2** [comment]
This can be done with the `position: running` and `element()` functions in https://www.w3.org/TR/css-gcpm-3/, and both are fairly well supported in print-focused CSS layout engine.

**Comment by SetTrend** [comment]
Thanks for enlightening me! 👍
