### ISSUE TITLE
[cssom-view] Add scrollIntoView parameter to only scroll the nearest scrolling container

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#10451]
Right now the [cssom-view spec](https://drafts.csswg.org/cssom-view/#scroll-a-target-into-view) says that (emphasis mine):

> To scroll a target into view target, which is an [Element](https://dom.spec.whatwg.org/#concept-element) or [Range](https://dom.spec.whatwg.org/#concept-range), with a scroll behavior behavior, a block flow direction position block, and an inline base direction position inline, means to run these steps **for each ancestor element or [viewport](https://www.w3.org/TR/CSS21/visuren.html#x1) that establishes a [scrolling box](https://drafts.csswg.org/cssom-view/#scrolling-box) scrolling box, in order of innermost to outermost scrolling box**:

There are many use cases when building components where it would be nice to only scroll the scroller associated with that component. I propose we add a property to [ScrollIntoViewOptions](https://drafts.csswg.org/cssom-view/#dictdef-scrollintoviewoptions) which limits the scroll to only the nearest scrolling container. E.g.

```
dictionary ScrollIntoViewOptions : ScrollOptions {
  ScrollLogicalPosition block = "start";
  ScrollLogicalPosition inline = "nearest";
  RecursionBehavior scrollers = "all" | "nearest";
};
```

I thought this was already filed but I couldn't find it in search so filing again.

Options to consider:
1. A named parameter, e.g. scrollers = "all" | "nearest"
2. A boolean parameter, e.g. recurse = true | false
3. A capturing ancestor scroller node, e.g. Element? contain = document.scrollingElement

We could also have some combination of these options, e.g. the the named parameter could optionally take an element.

**Comment by argyleink** [comment]
many many folks at CSS Day expressed this as an issue, as the API is what they want, but the side effects of effecting each ancestor are not what they want.

there's also [`scrollIntoViewIfNeeded()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) that could use the same property

**Comment by rol4nd909** [comment]
Yep I was one of them 😊 love to see this coming as an option. Thanks for working on it.

**Comment by flackr** [comment]
Apologies I think this is a duplicate of #9452 so I'll close in favor of that tracking issue which has a bit more history.
