### ISSUE TITLE
[css-sizing] should specify how to handle infinite max-content sizes

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1046]
Infinite max-content sizes are a thing; the spec should say what to do about them.  They at least result from anyplace where the spec tries to reverse-compute percentages, and maybe some other cases.

See, for example, [this testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22width%3A%20max-content%3B%20background%3A%20aqua%22%3E%0A%3Ctable%3E%0A%20%20%3Ctr%3E%0A%20%20%20%20%3Ctd%20width%3D%2260%25%22%3Ex%0A%20%20%20%20%3Ctd%20width%3D%2260%25%22%3Ex%0A%20%20%20%20%3Ctd%3Ex%0A%3C%2Ftable%3E).

(I actually couldn't find the code that explains why Gecko behaves as it does on that.)

**Comment by FremyCompany** [comment]
I believe you don't overflow because of a generalization of the following min(...) statement:
> If the table-root element has 'width: auto', the used width is the greater of min(GRIDMAX, the table’s containing block width), CAPMIN, and GRIDMIN. 
> https://drafts.csswg.org/css-tables-3/#computing-the-table-width

Now reading this and your message I realize the GRIDMIN and GRIDMAX are probably improperly defined in the spec because the algorithm to compute them does not use the percentages in any way. @dbaron can you confirm the text you wrote to define them needs some addition to take care of percentage back-computations? Or am I missing something?

**Comment by fantasai** [comment]
It does seem like in that testcase, Gecko is starting out the table with the content-based size, and then taking the remaining space up to the containing block width, distributing that space to the cells one by one to fulfill their desired percentage of the table (assuming 100% fits the containing block exactly) and giving up once all the excess space has been distributed. That's a fun algorithm, but it doesn't seem like a case of infinite max-content width. :)

**Comment by dbaron** [comment]
I don't see how @fantasai's https://github.com/w3c/csswg-drafts/issues/1046#issuecomment-282116983 is relevant; containing blocks and their widths are an input to layout, not to max-content size calculation.  (max-content size is also an input to layout.)

**Comment by dbaron** [comment]
In response to @FremyCompany's https://github.com/w3c/csswg-drafts/issues/1046#issuecomment-281551260 :  I'm not sure how that spec statement is relevant; the parent div has 'width: max-content', so the containing block width should be the max-content width of the table, not the width of the browser window.  But I think the spec I wrote a while back [explains how percentages should be handled](https://dbaron.org/css/intrinsic/#autotableintrinsic) (though also see the other parts of its [description of automatic table layout](https://dbaron.org/css/intrinsic/#autotable)).

Part of the reason that the test didn't do what I expect, though, is that Gecko has only added unprefixed support for `max-content` in some contexts; for `width`, it needs to be `width: -moz-max-content`.

The other part of the reason that Gecko didn't do what I expected is that tables actually have two different concepts of max-content width, specifically to avoid propagating the infinite max-content widths outside of the table (while still using them for the table's own sizing).  I introduced this as part of the [original reflow refactoring landing](https://bugzilla.mozilla.org/show_bug.cgi?id=300030), so it might be a little hard to track down the history (which is in CVS, but was never imported to either git or mercurial).

So it's actually possible that infinite max-content sizes aren't yet a general concept but are still local to only some areas.

**Comment by tabatkins** [comment]
So, uh, I don't think the notion of "infinite max-content size" is well-defined enough in any spec (I think it only shows up in tables, anyway) for us to actually do anything with yet. Is this right?

(Chrome behaves almost the same as Gecko, except instead of capping the table at the containing block width, it just gets as large as it is possible for an element to get in our engine. The relative ratios of the cells are the same, tho. This behavior seems... less than helpful.)

**Comment by dbaron** [comment]
So part of the weird thing in that testcase is that Gecko doesn't support unprefixed 'width: max-content'.

The other thing that's going on there is that in at least Gecko, we changed the engine not to expose the infinite max-content width outside of tables.  I'd forgotten about this.  The table code computes two different max-content widths, one of which can be infinite (it includes the percent-expansion) and one of which can't (doesn't include the percent expansion), and it uses the one with the percent-expansion internally and exposes the other one to its container.  This was done during the [reflow branch work](https://bugzilla.mozilla.org/show_bug.cgi?id=300030).

**Comment by fantasai** [comment]
OK, closing (with @dbaron's permission) as “Tables (and other things) should just make sure they don't have an infinite max-content size.”
