### ISSUE TITLE
[css-viewport] interactive-widget=resizes-content - will that likely fix issues with fixed headers/footers and on-screen keyboards?

### ISSUE THREAD

**Issue by SimonEast** [w3c/csswg-drafts#10464]
In short: I'd like to clarify whether the current proposed [`interactive-widget=resizes-content`](https://www.w3.org/TR/css-viewport-1/#interactive-widget-section) property is likely to solve issues like the following?

![ezgif-2-6a8f75a47c](https://github.com/w3c/csswg-drafts/assets/813734/c9402114-59c6-4053-987c-573a6d69059e)

In the animation above you'll notice that a typical 3-pane interface (a fixed header and footer, and a scrolling body) works great until the on-screen-keyboard (OSK) is launched and then the layout breaks quite badly:

* The header disappears off-screen
* The entire body becomes much larger than the [visual viewport](https://drafts.csswg.org/cssom-view-1/#visual-viewport) and even the original viewport
* There is now extra white-space underneath the footer
* Scrolling the screen becomes quite difficult as both the document and the center pane now scroll independently and it's possible to get "stuck"

I believe this is due to the _initial viewport_ now being larger than the _visual viewport_. 

I would instead expect to have a simple way to resize the layout, keeping the header and footer in view.

Link to example: https://simoneast.net/PERMANENT/coding-examples/fixed-issues.html
Browser: iPhone Safari 17.4.1

This prototype uses flexbox with `html, body { height: 100% }`, but I also tried many different variations (`position: fixed`, JS with `window.visualViewport`, `vh` units, `dvh` units, etc.) and was surprised to find that there is currently no easy, standards-based solution that currently works in Safari 17 (if there is, and I have merely overlooked it, please point me in the right direction).

So my main question is this: 
**If Safari correctly followed the `interactive-widget=resizes-content` property, would that alone resolve this kind of issue?** 
Or are there additional missing pieces to this that would need to be included in the standard? My hope is that a 3-pane interface such as this could be done cleanly and efficiently in HTML+CSS, without JavaScript.

Thanks for your time.

See also: [Viewport vs Virtual Keyboard Resize Behavior](https://github.com/bramus/viewport-resize-behavior/blob/main/explainer.md), an early guide to this issue which fed into the CSSWG draft.

**Comment by bramus** [comment]
> If Safari correctly followed the `interactive-widget=resizes-content` property, would that alone resolve this kind of issue?

YES.

**Comment by benbenbenbenbenben** [comment]
Late to the party, but if you want to make Safari play nicely when the virtual keyboard opens, there are some tips here: https://stackoverflow.com/questions/78844736/how-to-polyfill-interactive-widget-resizes-content-for-meta-viewport-tag-on/79502312#79502312

**Comment by rhyek** [comment]
Webkit bug tracking this issue: https://bugs.webkit.org/show_bug.cgi?id=259770. `interactive-widget=resizes-content` is apparently not implemented yet in safari at all.

**Comment by claritise** [comment]
iOS26 is out and still no updates from the WK team? Especially with the prevalence of chat based apps today that use this pattern extensively...

**Comment by sandstrom** [comment]
Any news from the Webkit team?

**Comment by bramus** [comment]
To inquire about WebKit’s position and progress, please refer to:

- [WebKit/standards-positions#65](https://github.com/WebKit/standards-positions/issues/65) _(you can thumbs up the first message in the thread to signal interest)_
- https://bugs.webkit.org/show_bug.cgi?id=259770 _(you can add yourself to the CC list to signal interest and receive updates)_
