### ISSUE TITLE
[Container Queries] consider keep links to CQ features in contain-3 or redirect them to conditional-5

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#10472]
With https://github.com/w3c/csswg-drafts/pull/10447 landed, linkes to CQ features in contain-3 no longer works. This breaks bunch of documentations or articles in the wild.

I remember there are drafts that keep ids for removed features (e.g. https://drafts.csswg.org/selectors-3/#content-selectors, which has even notes that it's removed ). I wonder if contain-3 could keep such links and perhaps add notes that they've moved to conditional-5, or some client-side redirect from contain-3 to conditional-5 like WHATWG drafts do. What do you think?

**Comment by frivoal** [comment]
Good point. Will do.

**Comment by frivoal** [comment]
Done: https://github.com/w3c/csswg-drafts/commit/526599ab7d5c65861eca4f43622e5fdf785d9138
