### ISSUE TITLE
[css-color-5] Out of range percentages in `color-mix()` seem to be implemented incorrectly in every major browser?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#10477]
The spec says that [percentages outside [0%, 100%] make `color-mix()` invalid](https://www.w3.org/TR/css-color-5/#color-mix-percent-norm):

> Percentages are required to be in the range 0% to 100%. Negative percentages are specifically disallowed.

However, in my [testing](https://codepen.io/leaverou/pen/bGyvdJw?editors=1100), browsers seem to handle this differently based on whether the percentage is the result of a calculation or not, which seems absurd.
Instead of IACVT, they seem to clamp the result of the calculation to [0%, 100%].

<img width="615" alt="image" src="https://github.com/w3c/csswg-drafts/assets/175836/0b000f29-9184-4722-8bf8-985d218532ff">

However, given the fact that they’re all interoperable about this behavior, I wonder if I’m missing something?

**Comment by cdoublev** [comment]
You are missing [this](https://drafts.csswg.org/css-values-4/#calc-range):

  > Parse-time range-checking of values is not performed within math functions, and therefore out-of-range values do not cause the declaration to become invalid. However, the value resulting from a top-level calculation must be clamped to the range allowed in the target context.

I think this behavior is mainly needed for relative dimensions (whose computed value may or may not be out of range).

**Comment by LeaVerou** [comment]
Thanks! I’ll close this then.
