### ISSUE TITLE
[css-text] Segment Break Transformation Rules at the beginning/end

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1048]
[Segment Break Transformation Rules](https://drafts.csswg.org/css-text-3/#line-break-transform) defines rules based on the character before and after, but does not define when a segment break is at the beginning/end.

I assume it should be removed too, or [Phase I: Collapsing and Transformation](https://drafts.csswg.org/css-text-3/#line-break-transform) should remove leading/trailing space/tab/segment breaks?

/cc @fantasai @upsuper

**Comment by upsuper** [comment]
I don't think it really matters, because they should be trimmed in [Phase II](https://drafts.csswg.org/css-text-3/#white-space-phase-2) anyway.

**Comment by kojiishi** [comment]
Thanks, I remember we had that somewhere but could not find it, thank you for pointing this out.
