### ISSUE TITLE
[css-text-decor-3] language sensitivity of text-underline-position: auto

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10488]
It seems that Firefox (and maybe Chrome?) implement the initial value of `text-underline-position` in a way that's sensitive to the language, and [interprets it](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Chtml%20style%3D%22writing-mode%3A%20vertical-rl%22%3E%0A%3Cstyle%3Ep%20%7B%20text-decoration%3A%20underline%3B%20text-underline-position%3A%20auto%3B%20%7D%3C%2Fstyle%3E%0A%3Cp%3EUntagged%3C%2Fp%3E%0A%3Cp%20lang%3Dja%3EJapanese%3C%2Fp%3E%0A%3Cp%20lang%3Dzh%3EChinese%3C%2Fp%3E%0A%3Cp%20lang%3Dko%3EKorean%3C%2Fp%3E%0A) as `right` for Japanese and Korean. 

This is currently not allowed per spec; instead the spec has UA rules that set the behavior per language.

Do we want to

- Update the definition of `auto` to match Firefox? 
- Or update implementations to match the spec?

**Comment by fantasai** [comment]
Closing as dup of https://github.com/w3c/csswg-drafts/issues/1198 which is largely about this.

**Comment by workspace-githib** [comment]
> It seems that Firefox (and maybe Chrome?) implement the initial value of `text-underline-position` in a way that's sensitive to the language, and [interprets it](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Chtml%20style%3D%22writing-mode%3A%20vertical-rl%22%3E%0A%3Cstyle%3Ep%20%7B%20text-decoration%3A%20underline%3B%20text-underline-position%3A%20auto%3B%20%7D%3C%2Fstyle%3E%0A%3Cp%3EUntagged%3C%2Fp%3E%0A%3Cp%20lang%3Dja%3EJapanese%3C%2Fp%3E%0A%3Cp%20lang%3Dzh%3EChinese%3C%2Fp%3E%0A%3Cp%20lang%3Dko%3EKorean%3C%2Fp%3E%0A) as `right` for Japanese and Korean. 
> 
> 
> 
> This is currently not allowed per spec; instead the spec has UA rules that set the behavior per language.
> 
> 
> 
> Do we want to
> 
> 
> 
> - Update the definition of `auto` to match Firefox? 
> 
> - Or update implementations to match the spec?
