### ISSUE TITLE
[cssom-1][css-page-3] What descriptor does `CSSPageDescriptors.orientation` represent?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10483]
[`CSSPageDescriptors.orientation`](https://drafts.csswg.org/cssom-1/#dom-csspagedescriptors-orientation) was added in #10482:

  > `@page{ orientation: ... }` Is generally treated the same as `@page{ size: ... }` [...]

In Chrome 126 and FF 127:

  ```js
  const sheet = new CSSStyleSheet()
  sheet.replaceSync('@page { orientation: portrait }')
  sheet.cssRules[0].cssText; // @page { }
  ```

Is it intented to be an attribute for [`page-orientation`](https://drafts.csswg.org/css-page-3/#page-orientation-prop)? (#10105) If so, is it intentional that its name is not `pageOrientation`?

**Comment by emilio** [comment]
Cc @alaskanemily

**Comment by AlaskanEmily** [comment]
Yes, I realized this just a little bit ago. I will open a new PR to fix that, it should be `pageOrientation`.

**Comment by emilio** [comment]
Fixed by https://github.com/w3c/csswg-drafts/pull/10521
