### ISSUE TITLE
[css-cascade-6] Can we support implicit scopes in nested settings?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#10497]
We have previously resolved to supply an 'implicit' scope-root inside `<style>`. The root is the parent node of the `<style>` element:

```css
<article id="my-thing">
  <style>@scope { /* similar to `@scope (article#my-thing)` */ }</style>
</article>
```

A different implicit scope-root might be more useful when `@scope` is nested inside other selectors. In that case, I would expect the missing `(<scope-start>)` should default to `(&)`:

```css
article {
  /* un-scoped `article` declarations */

  @scope { /* same as `@scope (&)` */ }
  @scope to (.another-thing) { /* @scope (&) to (.another-thing) */ }
}
```

That isn't exactly a parallel behavior, and I'm not sure if there are edge cases where it might be unclear which is intended. But I think this would be the most useful/expected result from a nested `@scope` syntax.

**Comment by mirisuzanne** [comment]
@andruud could you start running that use-counter now, or should we get a resolution in advance? It seems like there's positive interest in this, and it would be worth taking to the group if we can.

**Comment by tabatkins** [comment]
And this should presumably use the same "same set of elements as the parent" semantic that implicit nested rules get (like `.foo::before { @media (...) { color: red; } }`), so pseudo-elements work properly. (Rather than literally using `&`, which doesn't work with pseudo-elements currently.)

**Comment by andruud** [comment]
@tabatkins I don't think that makes sense.

- A `@scope` rule selects a specific element to become the scoping root.
- A `CSSNestedDeclarations` rule within `@scope` then matches that scoping root with zero specificity, (equivalent to :where(:scope)). https://github.com/w3c/csswg-drafts/issues/10431
- Pseudo-elements can't be scoping roots, and I don't think we should change that. https://drafts.csswg.org/css-cascade-6/#scope-syntax. It is a separate issue in any case.

So I think `&` is fine here.

**Comment by tabatkins** [comment]
Hm, ok. I don't want to rely on pseudo-elements *never* being scoping roots, but if that's currently the case then the difference would be unobservable anyway.
