### ISSUE TITLE
[css2] Percentages used to compute to auto; now compute to a percentage but are used as auto

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#1051]
It seems the group accepted an [errata](http://www.w3.org/Style/css2-updates/REC-CSS2-20110607-errata.html#s.10.5a) in 2013 regarding the computed value of the "height" property. I think that was a mistake and would like to revert that errata. It was applied in those [two](https://github.com/w3c/csswg-drafts/commit/b66760ec149cec9c26d60ccb4ee6347d17bb4e9c) [commits](https://github.com/w3c/csswg-drafts/commit/b61e2a26b218da47cde50a762443f9344bc9737a).

This change requires to complexify all other specs in order to deal with the case of "broken percentages" everywhere we want to deal with the "auto" case. Since most specs didn't this is bound to continue to cause issues when developers reimplement specs or part of specs, like what happened in [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=687551#c17).

Other specs continue to assume the old behavior, like css-sizing (in multiple places). Furthermore, it specifies this behavior for other values like fill-content etc when they can't resolve, like we do for percentages. 

> Note that percentages resolved against the intrinsic sizes (max-content, min-content, fit-content) will compute to auto, as defined by CSS 2.1. 

> [...] if the computed inline-size of the block is fit-content, auto, or stretch, its min-content inline-size contribution is its min-content inline size plus any inline-axis margin, border, and padding. 

> It is appropriate to resolve percentage heights on direct children of table cells if the cell is considered to have its height specified explicitly or the element is absolutely positioned, see CSS 2. It is further clarified that a cell is considered to have its height specified explicitly if the computed height of the cell [...] is a length or percentage.

cc @tabatkins @fantasai @dbaron @SimonSapin @bert-github

**Comment by FremyCompany** [comment]
We resolved in today's call to add some text in css-sizing to emcompass the notion of "height behaving as auto" that other specs can use and link to, so it is extra clear that ignored percentages are in fact considered in those cases where we currently incorrectly wrote "compute to auto". 

We also need to edit at least css-sizing and css-text to refer to that concept (and maybe css 2?)

**Comment by mwenge** [comment]
Hi there, I'm not clear on the outcome here. Have you guys agreed to revert the erratum?

**Comment by SimonSapin** [comment]
(I don’t know the status of this issue, but not everyone involved is a guy.)

**Comment by FremyCompany** [comment]
No the errata will stay, but we agreed the other specs needs to be updated so they take the errata in consideration. This was just forgotten when the errata was made, but the errata didn't intend to change the meaning of those specs.

Btw the errata seems supported in all browsers as this test shows: 
https://jsfiddle.net/nLxyer2c/

This was the only expected effect of the errata. Anything else is probably a spec that needs to be updated.

**Comment by mwenge** [comment]
OK, so nothing for me to do in crbug.com/687551 that prompted this issue?

(Simon - 'guys' is a gender-neutral plural in many parts of the world, including mine. :) )

**Comment by FremyCompany** [comment]
@mwenge You should work on returning to the old Chrome behavior that is also interoperable with other browsers. I will update the spec with the new wording as soon as @tabatkins has some cycle to update css-sizing and I can link to that.

**Comment by tabatkins** [comment]
@mwenge (It's really not; it's weakly gendered in *some* parts of speech (as a greeting), but more strongly gendered in others, and it's never gender-neutral.  There's a ton of words you can use that are gender-neutral; instead of "Have you guys", try "Have y'all", or "Have you folks", or "Has the WG".)

**Comment by tabatkins** [comment]
@FremyCompany Okay, added the term "behaves as auto" (and its obvious conjugations) to Sizing, and made sure that Sizing used the term where appropriate (only one spot in Sizing 3).  Feel free to link to it in Tables now.

**Comment by FremyCompany** [comment]
@tabatkins Thanks, will do 👍
