### ISSUE TITLE
[css-view-transition-2] `view-transition-class` and tree-scoping

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10529]
Following up on #10145, we should determine whether elements can define a `view-transition-class` inside shadow DOM that gets matched to a corresponding class in the pseudo-element (e.g. if the element is a `::part`)..
Based on https://drafts.csswg.org/css-scoping-1/#shadow-names, I think it makes sense to allow that, as a `view-transition-class` is similar to giving an element a `font-family` that's defined in the root inside a `@font-face`.

**Comment by noamr** [comment]
Thinking about this again, `view-transition-class` is not exactly a name-reference, but rather a name by itself, and the reference is in the pseudo-elements. It's more equivalent to container queries where the query has to be below the definition of the name.

I think the right approach here would be that `view-transition-class` is a scoped name, and is read from the same scope as the `view-transition-name`.

The only "quirk" about this is that the shadow DOM can define `view-transition-class: none !important` or some such and make a `::part` not receive a `view-transition-class`. Perhaps that's OK.

**Comment by noamr** [comment]
@nt1m @vmpstr @fantasai @khushalsagar any objections here? I think this is a non-controversial fix.

**Comment by nt1m** [comment]
I guess it would be consistent with the name, which is fine.

**Comment by noamr** [comment]
@astearns ok to do an offline resolution on this one?

**Comment by astearns** [comment]
@noamr more comments and/or thumbs-ups would be good for an async resolution. Add a proposed resolution and the `Async Resolution: Proposed` tag if you’d like to go that route.

**Comment by noamr** [comment]
Proposed resolution: `view-transition-class` is a tree-scoped name. It has to match the tree-scope of the view transition when read. De-facto, this means that it only applies in document-scoped stylesheets, and shadow-DOM can reset it to `none` using `!important`.

**Comment by khushalsagar** [comment]
SGTM. So both `view-transition-name` and `view-transition-class` have to match the tree-scope of the view transition.

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed resolution: view-transition-class is a tree-scoped name.

**Comment by astearns** [comment]
RESOLVED: view-transition-class is a tree-scoped name
