### ISSUE TITLE
[cssom][css-nesting] Error behavior for insertRule with declaration blocks.

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#10520]
In https://github.com/w3c/csswg-drafts/issues/10234 we resolved to give `insertRule` the ability to parse and insert declaration blocks (as `CSSNestedDeclarations` rules).

As of recent spec edits, insertRule is now set up to parse a declaration block (after the regular rule parsing), and **throw an error when that declaration block is empty**. https://drafts.csswg.org/cssom/#insert-a-css-rule, Step 4.

Is this behavior indeed what we want? @emilio points out that it's possibly weird that `potentially-unknown-property:foo` throws, but `potentially-unknown-property: foo; color:red` doesn't.

On the other hand, the following would lead to no `CSSNestedDeclarations` rule when parsed normally:

```
.a {
  .b { ... }
  potentially-unknown-property: foo;
}
```

Whereas this would:

```
.a {
  .b { ... }
  potentially-unknown-property: foo;
  color:red;
}
```

So probably the specified behavior isn't _too_ bad, but I'd like to discuss to either get a stamp for this change, or to see if we can do better somehow.

**Comment by fantasai** [comment]
I think if we are throwing on invalid declarations (at all), then we should not throw on empty. But if we _are_ throwing on invalid declarations, then we should also throw on empty.

**Comment by andruud** [comment]
Throwing on invalid declarations sounds bad for forwards compat, we probably shouldn't try to do that.

> I think if we are not throwing on invalid declarations (at all), then we should not throw on empty.

All right, but we still need to define the behavior when the when the [parsed declarations](https://drafts.csswg.org/cssom/#parse-a-css-declaration-block) is an empty list. I assume we'll just ignore it, i.e. not create/insert a `CSSNestedDeclarations` rule?

**Comment by tabatkins** [comment]
Yeah, while I don't like the OM's lack of errors, we should be consistent here - no error thrown, just nothing happens.

> All right, but we still need to define the behavior when the when the [parsed declarations](https://drafts.csswg.org/cssom/#parse-a-css-declaration-block) is an empty list. I assume we'll just ignore it, i.e. not create/insert a CSSNestedDeclarations rule?

Yeah, consistent behavior between "no decls given at all" and "only invalid decls given" - both result in no decls, so shouldn't create a rule.

**Comment by mdubet** [comment]
Throwing on invalid declarations is clearly a giant forward compatibility can of worms 😬 
Not having a feedback for the CSSOM user that this function call hasn't done anything is _slightly weird_, but better than the other choices.

**Comment by emilio** [comment]
> Yeah, while I don't like the OM's lack of errors, we should be consistent here - no error thrown, just nothing happens.

But insertRule _throws_ on invalid rules right now tho, right?

**Comment by mdubet** [comment]
> > Yeah, while I don't like the OM's lack of errors, we should be consistent here - no error thrown, just nothing happens.
> 
> But insertRule _throws_ on invalid rules right now tho, right?

Yes https://drafts.csswg.org/cssom-1/#insert-a-css-rule

**Comment by tabatkins** [comment]
Resolution is essentially "close no change", fwiw. So I'll go ahead and close. ^_^
