### ISSUE TITLE
[css-animations-1] @keyframes referencing from shadow roots does not match spec in any browser

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10540]
In https://drafts.csswg.org/css-scoping-1/#shadow-names, it is specified that shadow names are inherited and can be used by descendant shadow roots.
However, in the case of `@keyframes`, no browser implements this. see https://css-names-in-the-shadow.glitch.me/anim.html, the 3rd row (inner element, outer keyframes), and despite appearing in the scoping spec, there is no mention of it in the `css-animations` spec.

Proposing to be explicit in the spec about current browser behavior, as changing all the implementations now might be too risky in terms of backwards compat? (If we changed all the implementations, what would probably happen is that things that didn't animate before due to an outer-scope `@keyframes` would now animate.

**Comment by noamr** [comment]
See screenshot of current state from all browsers: ![Image](https://github.com/user-attachments/assets/82fc1c78-8650-43e6-bd74-0e1e59e357a0)

**Comment by kbabbitt** [comment]
Wanted to follow up and say thanks @noamr for collecting compat data on this! Your test page seems like a good candidate for a WPT, so I'd like to suggest turning it into one if you haven't already.

**Comment by noamr** [comment]
> Wanted to follow up and say thanks @noamr for collecting compat data on this! Your test page seems like a good candidate for a WPT, so I'd like to suggest turning it into one if you haven't already.

I did not have time to turn it into a WPT (or a collection of WPTs), help is appreciated!

**Comment by sorvell** [comment]
I'm just noticing that the behavior here seems to be inconsistent in all major engines: Safari 26, Firefox 144, Chrome 141. 

[See example](https://lit.dev/playground/#gist=a8ef381bb0caa4ed8ad0580ac3f533aa)

Safari seems most correct.
