### ISSUE TITLE
[css-anchor-position] [css-transforms] Unclear whether transforms should impact anchor positioning

### ISSUE THREAD

**Issue by RWDavid** [w3c/csswg-drafts#10555]
Here is the spec for anchor positioning:
https://drafts.csswg.org/css-anchor-position-1/

Here is the spec for transforms:
https://drafts.csswg.org/css-transforms/

In either spec, I can't seem to find details on how transforms should influence anchor positioning (if at all). It seems like Chrome's implementation of anchor positioning largely ignores transforms.

**Comment by tabatkins** [comment]
It shouldn't; transforms are post-layout (and generally make the concept of "top/left/etc edges" complex) . Chrome's implementation should *entirely* ignore transforms; if you're seeing any effect of transforms on anchorpos, that's a bug. ^_^
