### ISSUE TITLE
[css-fonts-4] Syntax definition of <generic-family> shouldn't use <custom-ident>+

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#10551]
The syntax for `<generic-family>` is currently defined as

```
<generic-family> = generic( <custom-ident>+ ) | <string> | <custom-ident>+
```

However `<custom-ident>+` and `<string>` are not a part of this syntax, they are part of `<family-name>`. It should be defined something like

```
<generic-family> = generic(<generic-script-specific>) | <generic-complete> | <generic-incomplete>`
<generic-script-specific> = kai | fangsong | nastaliq | ...
<generic-complete> = serif | sans-serif | system-ui | ...
<generic-incomplete> = ui-serif | ui-sans-serif | ui-rounded | ...
```

**Comment by svgeesus** [comment]
To get correct autolinking for the three new-style functional generic families, I had to define entire `generic(foo)`.
