### ISSUE TITLE
[css-mixins] `<combinator>` is already defined in Selectors

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10557]
There is syntax and selector `<combinator>`s, which are different sets:

  - https://drafts.csswg.org/selectors-4/#typedef-combinator
  - https://drafts.csswg.org/css-mixins-1/#typedef-combinator

It would be nice to clarify whether/how productions should be able to expand to a different value definition (syntax) depending on context. As far as I know, [`<bool-test>`](https://drafts.csswg.org/css-values-4/#typedef-bool-test) is the only other production whose value definition is context-sensitive, but it does not explicitly expand to a value definition (with `<bool-test> =`).

**Comment by cdoublev** [comment]
I hope it is fine not top open a separate issue, but the same problem applies to `<type()>`:

  - in [CSS Mixins](https://drafts.csswg.org/css-mixins-1/#typedef-type): `type( <syntax> )`
  - in [CSS Images 4](https://drafts.csswg.org/css-images-4/#funcdef-image-set-type): `type( <string> )`

If production rules should have context-insensitive value definitions, a solution could be to use an inline `type()` definition (like in CSS Images): `<css-type> = <syntax-component> | type( <syntax> )`.

**Comment by tabatkins** [comment]
Yup, I went ahead and deduped the names.
