### ISSUE TITLE
Meta: Prefixed spec labels in issue titles considered harmful

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#1057]
In emails to www-style it’s really helpful for filtering to have threads tagged with `[css-{module-short-name}(-{level})?]` in the `Subject` line, but Github already provides Labels for that. When there is a long prefix or there are multiple – often up to three – prefixes, the subject is sometimes truncated before the essential part. Some overviews like github.com/notifications become almost useles then. Can we get rid of the redundant labels or at least move them to the end of the subject? (I do know that some people prefer to participate via email and bracketed *suf*fixes are unusual there.)

Also, Milestones  and Projects may be appropriate to be used for Levels or “annual” Snapshots. (Projects would probably better match to Agendas, though.)

**Comment by upsuper** [comment]
Most people don't have permission to add label. Not sure if it is possible to allow all people to add labels. 

Also I mostly read discussions from email notification, so the prefix is still useful to me. I can skip issues related to specs I don't follow directly by just reading the title. Not sure about other people.

**Comment by fantasai** [comment]
I'm also email-dominant. (I think the biggest problem with GitHub notifications is the prefixing with [w3c/csswg-drafts] which is *useless*, but I have a script that strips that from my mailbox.)

As you mention, it's mostly the cross-spec issues that are affected, and there aren't terribly many of that. There's the Flex/Grid/Align combos which are fairly common, but they should become rarer as Align stabilizes.

**Comment by SebastianZ** [comment]
I'd be really happy if it were possible for non-members to add labels, though that's currently not possible.
Note that I wrote a message to the GitHub support asking for this feature back in June last year.

Original mail:
>> Some repositories' issue trackers would benefit from allowing users to set certain labels.
>> One of them is https://github.com/w3c/csswg-drafts/issues, where reporters (also the ones that are *not* members of the repository) are currently required to add labels to the summary.
>>
>> This should either be added to the general repository settings or (probably the better place) as an option in the label editor.
>>
>> Sebastian
> 
> Hey Sebastian,
> 
> Thanks for reaching out. I can see how this would be useful for repos with a lot of issue contributors, but who like to keep code access to a minimum.
> 
> I can't make any promises, but I have definitely added it to the feature request list and will share it with the team for consideration.
> 
> Regards,
> Daniel

Also, it would be great if GitHub allowed to filter mail notifications by labels, though there's no option for that, neither.

I've just sent a request for that to the GitHub people.

Therefore, I guess prefixed spec. labels are currently the only way for people to be able to filter them automatically in their mail clients.

Sebastian

**Comment by fantasai** [comment]
Closing this issue as WONTFIX. Feel free to re-open if GitHub ever
  a) allows the public to add labels
and
  b) includes labels in the email headers
