### ISSUE TITLE
[css-view-transitions-2] Optionally capture some properties (e.g. opacity/border) as style instead of snapshot

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10585]
The current way we capture view-transition participating elements is tuned to a flat tree of crossfade+transform animations: we save the element's relevant properties (transform from root, mix-blend-mode, color-scheme) and everything else is baked into the snapshot.

However, #10334 (nested transition groups) makes it so that this pattern might need to be expanded: to display clipping and tree effects in an expected manner, those would have to be copied into the group rather than baked into the snapshot.

The following (non-exhaustive?) list of CSS features would have a different behavior in a nested transition tree:
- tree effects (opacity, filter, image-mask)
- clipping (clip-path, overflow, border-radius)
- 3D (actual transform, preserve-3d, perspective, transform-origin)

The "odd" one out of these is `border-radius` together with `overflow`: since it has a unique effect of clipping its descendant but not clipping the border.

To render a rounded-corner element with nested clipped descendants correctly in terms of paint-order, the entire set of box decorations (backgrounds & borders) would have to be captured and applied to the group.

Also as per the resolution in #8282, we sometimes capture geometry only (when the old element is out of the viewport).
* TBD whether this needs its own bespoke thing or fits in with the capture modes concept.

So at the very least there could be 4 capture modes (each one includes the ones above it):
- `geometry`
- `flat` (geometry + snapshot + blend)
- `composite` (clipping + 3D + tree effects)
- `layered` (borders + background + shadow)
(names bikesheddable to the bone)

Superficially, it would seem like this can be done automatically:
- Use `geometry` when out of viewport
- Use `flat` when in viewport
- Use `composite` when has nested descendants
- Use `layered` when has nested descendants and clipping border-radius

However, the issue with these capture modes is that by default they're *incompatible with each other* - so if we used one capture mode in the old state and one in the new state, the animation and the captured image would be out of sync, creating a buggy-looking animation like this: https://codepen.io/noamr-the-selector/pen/OJeymbe.

One path forward is to enable the author to define the capture mode (based on the above proposal or some other subdivision we decide on), and encourage authors to use this when using nested transitions, but not choose a capture mode automatically (except for `geometry` when out of screen).

**Comment by noamr** [comment]
A syntax alternative can be `view-transition-style: motion || crossfade || composite || decoration || default` where `default` means "motion when out of viewport, motion+crossfade when in-viewport"

**Comment by noamr** [comment]
Notes from internal conversation: for starts, having two modes is enough:
- The current mode, where elements are captured for a crossfade
- The "max" mode: capturing the borders/background/clip/effects/3d as style and morphing them individually rather than as part of the image

Perhaps `view-transition-style: crossfade | morph` ?

To discuss/resolve:
- Should this be configurable separately per-element or once for the whole view-transition? The former feels more flexible perhaps?
- What do we do in case of mismatch?

**Comment by noamr** [comment]
Copying from #9406 for the purpose of the CSSWG breakout.

There are 3 use-cases that can benefit from changing the way we capture in certain scenarios:
1. Groups that have nested descendant with `view-transition-group`: they need to capture opacity, filters, 3D, and sometimes borders, backgrounds & shadows in order to display in a way that doesn't look buggy.
2. Sometimes, regardless of nesting, animating border and `box-shadow` can have a nicer effect than flattening them into the snapshot.
3. When an element comes from far away from the viewport, or if we're moving elements around without changing their content, we could benefit from an optimization of not capturing the old content into a snapshot at all.

I see this as 3 styles of transition, with an `auto` that generates default behavior:
- Crossfade between the old and new element snapshots, like today (`crossfade`?)
- Crossfade the contents and animate the box decorations individually (`morph`?)
- Display the new content only and morph only the box decorations (`shapeshift`?)

`auto` could mean:
- Use `morph` when the group contains other groups
- Use `shapeshift` when animating from very far from the viewport (100vw, 100vh?)
- Otherwise, use `crossfade`

**Comment by Psychpsyo** [comment]
> `auto` could mean:
> 
>     * Use `morph` when the group contains other groups
> 
>     * Use `shapeshift` when animating from very far from the viewport (100vw, 100vh?)
> 
>     * Otherwise, use `crossfade`

Is there a reason for `auto` not using `morph` automatically if two elements with differing 3D transforms (or similar) are being transitioned between?
Because currently, transitioning one 3D transformed element to a differently 3D transformed element just crossfades between the two and it looks rather janky.

**Comment by noamr** [comment]
> > `auto` could mean:
> > ```
> > * Use `morph` when the group contains other groups
> > 
> > * Use `shapeshift` when animating from very far from the viewport (100vw, 100vh?)
> > 
> > * Otherwise, use `crossfade`
> > ```
> 
> Is there a reason for `auto` not using `morph` automatically if two elements with differing 3D transforms (or similar) are being transitioned between? Because like this, transitioning one 3D transformed element to a differently 3D transformed element just crossfades between the two and it looks rather janky.

If an element is flat (doesn't have nested descendants), there shouldn't be a difference regarding the internal 3D transform (e.g. `perspective`), as the image is flattened anyway. The external transform is part of transitioning the geometry in all the styles.

**Comment by bramus** [comment]
> Perhaps `view-transition-style: crossfade | morph` ?

The conversation here uses “capture mode“ as a term a lot, so maybe `view-transition-capture-mode` seems better?

> * Crossfade between the old and new element snapshots, like today (`crossfade`?)

`crossfade` as a value feels weird here because authors can override the animation to something entirely different. IUC this is the current behavior where you get a flattened surface, so maybe `flat` as a value is better here?

> * Crossfade the contents and animate the box decorations individually (`morph`?)



> * Display the new content only and morph only the box decorations (`transpose`?)

This can already be controlled by authors, no?

```css
::view-transition-old(x) { display: none; }
::view-transition-new(x) { animation-name: none; }
```

**Comment by noamr** [comment]
> _(Got my bikeshedding hat on …)_
> 
> > Perhaps `view-transition-style: crossfade | morph` ?
> 
> The conversation here uses “capture mode“ as a term a lot, so maybe `view-transition-capture-mode` seems better?
> 
> > * Crossfade between the old and new element snapshots, like today (`crossfade`?)
> 
> `crossfade` as a value feels weird here because authors can override the animation to something entirely different. IUC this is the current behavior where you get a flattened surface, so maybe `flat` as a value is better here?

Yea, it's whether this property implies "what default transition would this generate" whether "what does it capture".
I thought that referring to the default transition style is more design-oriented and referring to the capture is more technical, but perhaps more precise. This is definitely arguable!

> > * Display the new content only and morph only the box decorations (`transpose`?)
> 
> This can already be controlled by authors, no?
> 
> ```css
> ::view-transition-old(x) { display: none; }
> ::view-transition-new(x) { animation-name: none; }
> ```

Yea, but doing this in advance is an optimization, see #9406. We can also decide to not fold this optimization in the solution for this issue.

**Comment by noamr** [comment]
Summary from internal sync, we concluded that we'd defer the no-content-change to later.
There are 3 options on the table:

1. Change the capture mode by default. Capture box-decorations and tree effects as style, and cross-fade only the contents. This asserts that morphing rather than cross-fading is mostly superior. However, it might make some of today's view transition animate differently, e.g. a different background image between the old and new state would animate discretely.  
2. Make this an opt-in with a new property (`view-transition-style` or `view-transition-capture-mode`), one option is like today, and the other one captures box-decorations & tree effects as style.
3. Add a new property, but give it an `auto` value. The capture-mode will be the same as today, unless the element is a containing group (has nested group descendants). This asserts that flat capturing doesn't make sense at all for a nested group tree, and it allows us to change that without breaking existing content.

Note that (1) would become much stronger once we can automatically animate backgrounds/border-image/masks/clip-path by creating an automatic cross-fade.

**Comment by noamr** [comment]
As part of experimentation, we've identified which properties need to participate in this and how, and also the potential compatibility-breaking parts (though it's not shipped yet, so we don't know if the compatibility breakage happens in practice).

## Categorization
We divide CSS properties into the following categories:

### Copied
Properties that should be captured, and also be rendered into the snapshot

* `overflow`
* `overflow-clip-margin`
* `contain` (potentially just convert `contain: paint` into `overflow: clip`)
* `transform-style` 
* `perspective`
(the last two actually don't have any effect on a flattened snapshot)

### Delegated
Properties that should be captured and delegated to the group, and the snapshot should be rendered without them (note that some of these are shorthands):

* `background`
* `border`
* `border-image`
* `border-radius`
* `box-shadow`
* `clip`
* `clip-path`
* `filter`
* `mask`
* `opacity`

## Notes
* The transform of the element should be copied in 3D space rather than flattened, to preserve the 3D effect of the origin.
* Applying overflow to the snapshot is a design choice, to avoid capturing very big overflowing content. This means that the author cannot use the pseudo-elements to animate scrolling an `overflow: scroll` DIV. However, the overflow is captured without the `border-radius`, which is applied separately as CSS and can be animated, as well as `clip-path` and `clip`.
* If we don't render the border, this affects the border box of the pseudo-elements, and its relationship with nested groups, as the border-box is what's used to determine the pseudo element's position. Suggesting that this change means that we need to project the padding box instead.

**Comment by noamr** [comment]
One issue that came up while prototyping this is that with the new capture mode, you can't simply hide the old/new state by hiding the old/new pseudo, if the old/new state had backgrounds/borders/etc. And to mimic the current behavior, the author would need to change the HTML hierarchy (add a container element).

I'm not sure if this is a desirable outcome. Indeed layered capture provides a more superior experience, but the flat crossfade capture is *simpler*: everything is in the old/new elements and you can always hide one of them. I think this is a point towards keeping the old capture mode as an option and making the decision based on a CSS property (which can be the existing `view-transition-group` property or something new).

**Comment by khushalsagar** [comment]
> Since we want `flat` primarily for compat

Correction, we did find UX cases like sliding old/new content here: https://view-transitions.chrome.dev/pagination/spa/ which would need the image pseudos to have box decorations like the element background. If the background changes, you might want that to slide instead of interpolating as a style on the group.

**Comment by noamr** [comment]
For the sake of avoiding endless scrolling, I'm preparing a PR based on the previous resolution, and let's take the opt-in question (alongside followup questions about the details of the capture mode) to new issues.

**Comment by noamr** [comment]
For the breakout today: see [explainer](https://github.com/WICG/view-transitions/blob/main/nested-explainer.md#layered-capture).

Open questions, given our [quick backwards compat analysis](https://github.com/WICG/view-transitions/blob/main/nested-explainer.md#backwards-compatibility--opting-inout) and prototype
- See that the capture model(([properties](https://github.com/WICG/view-transitions/blob/main/nested-explainer.md#layered-capture) and [geometry](https://github.com/WICG/view-transitions/blob/main/nested-explainer.md#layered-capture)) makes sense.
- opt in/out / what's the default (#11078).
- How to deal with scrollbars (#11079).
