### ISSUE TITLE
[css-contain-1] Use proper HTML in markup example

### ISSUE THREAD

**Issue by thierryk** [w3c/csswg-drafts#1058]
In [section 2 (Strong Containment)](https://www.w3.org/TR/css-contain-1/#contain-property), the markup example is as follow:

```html
<body>
  <aside class='sidebar'>...</aside>
  <article class='messages'>
    <section class='message'>
      Lol, check out this dog: images.example.com/jsK3jkl
    </section>
    <section class='message'>
      I had a ham sandwich today. #goodtimes
    </section>
    <section class='message'>
      I have political opinions that you need to hear!
    </section>
    …
  </article>
</body>
```

I do not think this is a proper use of `<section>` (as sections "should" have headings). Looking at the repetition of the class `message` I'd suggest using a `ul` inside `article` with `li` replacing `section`; but other constructs could work as well&mdash;it is just that I don't think `section` is the right element here.

**Comment by thierryk** [comment]
Another example could be (if the messages were meant to be syndicated):

```html
<body>
  <aside class='sidebar'>...</aside>
  <section class='messages'>
    <h2>Messages</h2>
    <article class='message'>
      Lol, check out this dog: images.example.com/jsK3jkl
    </article>
    <article class='message'>
      I had a ham sandwich today. #goodtimes
    </article>
    <article class='message'>
      I have political opinions that you need to hear!
    </article>
    …
  </section>
</body>
```

**Comment by fantasai** [comment]
`<article>` seems like the correct tag here. Also `class=message` becomes redundant at that point; you can infer it from the containing `<section>`.

**Comment by tabatkins** [comment]
Yeah, `<article>` is right. Tweets are all independent content.

**Comment by tabatkins** [comment]
Feel free to PR. ^_^

**Comment by thierryk** [comment]
[Done!](https://github.com/w3c/csswg-drafts/pull/1060)

**Comment by frivoal** [comment]
Merged. Thanks
