### ISSUE TITLE
[css-sizing-4]: Minor fix: incorrect wpt.fyi link

### ISSUE THREAD

**Issue by estelle** [w3c/csswg-drafts#10602]
Spec URL: https://drafts.csswg.org/css-sizing-4/
Section: More details about this document

Error:

> Test Suite:
> https://wpt.fyi/results/css/css-contain/

Should be:

> Test Suite:
> https://wpt.fyi/results/css/css-sizing/

**Comment by estelle** [comment]
I couldn't find where to edit to submit the PR directly. Sorry.

**Comment by fantasai** [comment]
I think it's getting auto-generated from the fact that there's one test linked from the css-contain suite? Anyway, added an explicit Test Suite line. If that fixes it in the ED, feel free to close the issue. :)

**Comment by estelle** [comment]
Thank you. That fixed it!
