### ISSUE TITLE
[css-view-transitions-2] `view-transition-group` and tree-scoping

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10633]
Follow up on #10334 

It's unclear how to specify `view-transition-group` in terms of shadow trees.
Sure, we can make the `<<custom-ident>>` a tree-scoped reference, which means it can't reference names from a different scope. However, what about `nearest` keyword etc? Keywords are not usually "tree-scoped".

Since `view-transition-name` is tree-scoped and `view-transition-group` doesn't make much sense in isolation from it, suggesting that both idents and keywords in `view-transition-group` are tree-scoped, and this property always resolves to `none` inside a shadow-tree.

//cc @khushalsagar @vmpstr 

See also #10529

**Comment by khushalsagar** [comment]
+1 to tree scoping the property including the keywords. Basically group only applies if its computed value has the same tree scope as the name?

**Comment by khushalsagar** [comment]
Related issue for anchor positioning had the same resolution: https://github.com/w3c/csswg-drafts/issues/10526 and https://github.com/w3c/csswg-drafts/issues/10525.

> this property always resolves to none inside a shadow-tree

I wouldn't quite say that, for scoped transitions inside a shadow tree this value can be not none. But it makes sense to treat the property as unset or initial value if its computed value's tree scope mismatches the tree scope of the transition. That's what we do with names as well right? If a name is using inner tree scope, we ignore it when the transition is started in outer tree scope.
