### ISSUE TITLE
[css-view-transitions-2] Should view-transition-group contain or <ident> take precedence

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#10639]
In https://github.com/w3c/csswg-drafts/issues/10334, we resolved that we will have the following property:

```css
view-transition-group: normal | <ident> | nearest | contain
```
Consider the following structure

```
A  /* view-transition-name: foo */
|
- B /* view-transition-group: contain */
  |
  - C /* view-transition-group: foo */
```

Here `B` should contain all descendants and `C` is saying it wants to be contained by `A`. What should be the behavior? We can either say that `B`'s `contain` wins and we don't respect `C`'s desire to group under `A`, or `B`'s `contain` does not contain `C` because it has an explicit reference to `A`.

I'm leaning towards the latter here loosely because it feels like `C`'s "specificifity" of ident is higher than `B`'s desire to contain everything.

**Comment by noamr** [comment]
I think `<custom-ident>` should win, especially given #10631.
It allows, for example, having a clipping container with `contain` which allows the convenience of not specifying a name for each of its descendant, and then exiting that container if there's an element that needs to animate out of it using the explicit `<custom-ident>`.

**Comment by noamr** [comment]
The resolution happens to be the spec wording already, closing.
