### ISSUE TITLE
[css-color] Should relative color syntax use color() function serialization?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10641]
I think it is a lot easier to serialize as is, than resolve to a `color()` function.

Especially when you start dealing with `currentColor`, system colors, nested functions or CSS variables. The only way to properly round-trip is to serialize as-is. I suggest making that the default and dropping the transformation to the `color()` function.

```
rgb(from currentColor r g b)
rgb(from MenuText r g b)
rgb(from light-dark(red, blue) r g b)
rgb(from color-mix(...) r g b)
rgb(from var(--foo) r g b)
```

@svgeesus @mysteryDate @tiaanl @Emilio Can we make that change?

WebKit has implemented this behavior and has yet to export the WPT: https://github.com/WebKit/WebKit/commit/c05a19a495bdffa90ca2c5707c651dee249b6870

cc @squelart @weinig

**Comment by weinig** [comment]
@nt1m is this roughly the same issue as https://github.com/w3c/csswg-drafts/issues/10327?

**Comment by nt1m** [comment]
Ah great, this was already resolved on! Thanks for pointing it out. 

Duplicate of #10327
