### ISSUE TITLE
[css-view-transitions-2] CSSOM for CSSViewTransitionRule.navigation does not match implementation

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10654]
The spec defines it as:
```
readonly attribute ViewTransitionNavigation navigation;
```

and Blink has:

```
readonly attribute CSSOMString navigation;
```

This is actually visible on the web, and Blink's behavior is tested inside a WPT:

https://searchfox.org/wubkat/rev/b36cbce69fddb7da33823f316bd8ead5bebee970/LayoutTests/imported/w3c/web-platform-tests/css/css-view-transitions/navigation/at-rule-cssom.html#24

The test expects this attribute to be an empty string, which is not possible if you have enumerated values (ViewTransitionNavigation), the CSSOM would return `none` with the enum instead of an empty string in this case.

cc @noamr @khushalsagar @mattwoodrow @vmpstr

**Comment by vmpstr** [comment]
Closing the issue as it sounds like it's just a Chromium bug. Feel free to reopen if I misunderstood

**Comment by noamr** [comment]
Actually I think this is debatable, we don't currently have at rules that use enums in that way, and usually CSSOM doesn't try to be fully type-safe in this way. e.g. if we add new navigation types and some browsers don't support them, this would interpret them as invalid rules rather than rules with empty `navigation`.

**Comment by nt1m** [comment]
Maybe @tabatkins or @fantasai has an opinion here (I really do not have a strong one for this). Aiming for consistency is best (whatever consistency is in this context)

**Comment by noamr** [comment]
OK reading https://drafts.csswg.org/css-counter-styles/#the-counter-style-rule:
"""
This at-rule conforms with the forward-compatible parsing requirement of CSS; conformant parsers that don’t understand these rules will ignore them without error. Any descriptors that are not recognized or implemented by a given user agent, or whose value does not match the grammars given here or in a future version of this specification, must be ignored in their entirety; they do not make the [@counter-style](https://drafts.csswg.org/css-counter-styles/#at-ruledef-counter-style) rule invalid.
"""

I think that this should be the case for this rule as well, and we should change `navigaiton` to be a `CSSOMString` (like https://drafts.csswg.org/css-counter-styles/#the-csscounterstylerule-interface) that returns an empty string when there is no valid navigation rule, as per the current chromium implementation.
