### ISSUE TITLE
[css-shapes-1] `ellipse()` grammar doesn't allow the two-radial-size keyword form

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#10665]
In [CSS Shapes 1](https://drafts.csswg.org/css-shapes/), the grammar for ellipse is:

```
<ellipse()> = ellipse(
  <radial-size>?
  [ at <position> ]?
)
```
where [radial-size](https://drafts.csswg.org/css-images-3/#typedef-radial-size) is
```
<radial-extent> | <length [0,∞]> | <length-percentage [0,∞]>{2}
```

This appears to only allow a single `<radial-extent>` keyword, which would result in a circle. Browsers support two `<radial-extent>` keywords; the `https://wpt.fyi/results/css/css-shapes/parsing/shape-outside-valid.html` WPT has: `ellipse(closest-side closest-side at 60% 70%)` which all browsers support.

So I think the grammar needs updating somehow.

**Comment by cdoublev** [comment]
`<radial-size>` is extended in [CSS Images 4](https://drafts.csswg.org/css-images-4/#radial-size).

**Comment by smfr** [comment]
Ah, that makes sense, thanks!
