### ISSUE TITLE
Examples use incorrect toggle() syntax

### ISSUE THREAD

**Issue by phdave2005** [w3c/csswg-drafts#10670]
* CSS Values and Units Module 5

* Examples 4 and 5 in section 6.3 use a semicolon (;) separator, but should be comma (,)

* [Section 6.3](https://drafts.csswg.org/css-values-5/#toggle-notation)

**Comment by cdoublev** [comment]
They uses a valid syntax (see [3.1.1. Commas and Semicolons in Functions](https://drafts.csswg.org/css-values-5/#component-function-commas): `,` can be replaced with `;` in functions). I do not know if there is a "canonical form" that examples should use though.

**Comment by tabatkins** [comment]
The examples are indeed valid, but I don't actually want to show that off unless necessary. I've gone ahead and switched every example to commas except the few that actually do require it, or that are showing off the semicolon syntax.
