### ISSUE TITLE
[css-conditional-3][meta] Publish CRD

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10672]
Last publication was a [CR Snapshot on 13 January 2022](https://www.w3.org/TR/2022/CR-css-conditional-3-20220113/).

The current ED is dated [27 July 2024](https://drafts.csswg.org/css-conditional-3/) and there have been [5 substantive changes since](https://drafts.csswg.org/css-conditional-3/#changes). 

Also the current ED has WPT annotations and so lists **1706 tests** while the CR has the old widget pointing to the now-abandoned testsuite mirror and declares there are **87 tests**.

We should therefore publish a CR Draft.

@dbaron @fantasai @astearns @atanassov

**Comment by svgeesus** [comment]
Related

 - https://github.com/w3c/csswg-drafts/issues/10671

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Publish an updated CRD of css-conditional-3

**Comment by astearns** [comment]
RESOLVED: Publish an updated CRD of css-conditional-3

**Comment by svgeesus** [comment]
Publication requested 13 Aug expected 15 August

**Comment by svgeesus** [comment]
[Published 15 Aug](https://www.w3.org/TR/2024/CRD-css-conditional-3-20240815/)
