### ISSUE TITLE
[CSS Viewport Module Level 1] GitHub Editor link is broken

### ISSUE THREAD

**Issue by jverkoey** [w3c/csswg-drafts#10680]
https://drafts.csswg.org/css-viewport/ includes a link under "Suggest an Edit for this Spec: " that points to https://github.com/w3c/csswg-drafts/blob/main/css-viewport-1/Overview.bs, which is a 404.

**Comment by svgeesus** [comment]
If you now go to https://drafts.csswg.org/css-viewport-1/ the "suggest edit" will work. Thanks for reporting this!

**Comment by jverkoey** [comment]
Thank you!
