### ISSUE TITLE
[css-shapes-2] Disallow interpolation between `path()` and `shape()`

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#10694]
[Basic Shapes 2](https://drafts.csswg.org/css-shapes-2/#interpolating-shape) says that `path()` and `shape()` should interpolate.

I don't think that's very extensible going forward, where we're likely to add new shape commands that don't correspond to types that can be interpolated with SVG-type path commands, and it doesn't seem particularly useful for authors.

I suggest we disallow interpolation between `path()` and `shape()`.

cc @noamr

**Comment by noamr** [comment]
Yea I think it's not that necessary to have path/shape interpolation.

**Comment by tabatkins** [comment]
I don't understand this objection. Having different value spaces between the two types isn't a problem, so long as one is a superset of the other, and afaik that's precisely what we intend to preserve - every single behavior you can express with `path()` should be expressible with `shape()`, and `shape()` might grow *additional* commands that we don't sync back with SVG.

The intermediate value would just be `shape()` - you'd "upgrade" the `path()` into an equivalent `shape()` and then interpolate using `shape()` rules. This sort of behavior has several existing examples in CSS.

**Comment by smfr** [comment]
It just seems like unnecessary implementation complexity. If an author is using `shape()` in one state, it's likely that they've converted their `path()`s to `shape()`s already.

**Comment by ydaniv** [comment]
I agree with @tabatkins, you should be able to upgrade `path()` and make this seamless to authors. And not unnecessary if you consider the entire ecosystem is still filled with `path()`'s coming from SVG/CSS and tools that generate them. IMO being able to work seamlessly with both will be very valuable.

**Comment by noamr** [comment]
Personally I am OK either way.
@smfr I don't see a problem with future extensibility; `path()` can always be read like a `shape()` with `px` values, and then interpolation can continue from there according to the `shape()` rules.

**Comment by smfr** [comment]
OK, I'll close.
