### ISSUE TITLE
[css-inline-3] Do not expand `text-box` value definition?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10698]
I see two drawbacks to [this](https://drafts.csswg.org/css-inline-3/#text-box-shorthand):

  > **Issue 13:** This propdef table is fully expanded to evaluate and adjust the shorthand’s value space. It simplifies down to `<text-box-trim> || <text-box-edge>` minus the `none` and `auto` keywords.

First, this is error prone and slightly more maintenance work when you add a new longhand value.

Second, depending on the CSS parser, this may require more implementation work than making `none` and `auto` invalid.

***Nit:*** the fully expanded value definition would be `normal | [<'text-box-trim'> || <'text-box-edge'>]`.

**Comment by fantasai** [comment]
This is just a temporary editorial measure to facilitate review. :) Agree we should use the standard notation eventually.
