### ISSUE TITLE
[css-transitions]: Add keyword for adding transitions to existing ones

### ISSUE THREAD

**Issue by SetTrend** [w3c/csswg-drafts#10710]
## Current Situation

Currently, in the following example, the second rule will overwrite the first one:

```css
transition: opacity 400ms ease;
transition: left 350ms ease;
```

So, only `transition: left 350ms ease;` will be in effect. `transition: opacity 400ms ease;` will be ignored

## Desired Situation

Please add an `add` keyword to the different `transition` properties (incl. the shorthand property), so existing transition rules will remain intact while new transitions may be added independently from existing transitions.

### Example

```css
transition: opacity 400ms ease;
transition: add left 350ms ease;
            ‾‾‾
```

… would yield the same result as:

```css
transition: opacity 400ms ease
          , left 350ms ease;
```

**Comment by birtles** [comment]
I think this use case applies to many CSS properties, particularly list-based properties. See the discussion in #1594. If you don't mind, I'd suggest closing this issue in favor of that one.

**Comment by tabatkins** [comment]
Yup, this is a more general issue we've never successfully solved (and trying to solve it for just this case doesn't actually reduce the complexity at all). So, closing as dupe.

**Comment by SetTrend** [comment]
Thanks for pointing me!
