### ISSUE TITLE
[css-overflow-5][css-scroll-snap-2] Snapping and generating scroll-marker pseudo-elements from fragments

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#10715]
For common carousel patterns as outlined in #9745, developers will have content being fragmented into different boxes. Often, developers want to create an interface that scrolls through these fragments by pages, e.g. [demo](https://flackr.github.io/carousel/examples/carousel/image/). Similarly, for existing column fragmentation use cases developers may wish to snap to particular columns. Issues #6017 and #5911 both have prior discussion on snapping specifically.

As with snapping, it would be very convenient to be able to generate a [::scroll-marker](https://drafts.csswg.org/css-overflow-5/#scroll-marker-pseudo) pseudo-element per generated fragment to set up automatic markers based on the available space and number of resulting fragments the content ended up needing.

This explores the two issues together as they feel similar in nature, though we don't necessarily have to resolve on the same solution for both.

For the examples below, we have the following common styles:
```css
.scroller {
  overflow: auto;
  height: 80vh;
  scroll-snap-type: x mandatory;
  columns: 1; /* Fragment content to horizontally scrollable full pages */
}
```

Options:
1.  Support [scroll-snap-align](https://drafts.csswg.org/css-scroll-snap/#scroll-snap-align) (as suggested in #6017) and [::scroll-marker](https://drafts.csswg.org/css-overflow-5/#scroll-marker-pseudo) pseudo-elements on a `::fragment` selector[^1]. This would allow a paginated carousel-like snapping experience to be created as follows:
    ```html
    <style>
      .scroller::fragment {
        scroll-snap-align: center;
        &::scroll-marker {
          content: ' ';
        }
      }
    </style>
    <div class="scroller">
      <!-- flowing content or items, e.g. -->
      <div>Item 1</div>
      <div>Item 2</div>
      ...
      <div>Item n</div>
    </div>
    ```
2. Make [scroll-snap-align](https://drafts.csswg.org/css-scroll-snap/#scroll-snap-align) (as suggested in #5911) and [::scroll-marker](https://drafts.csswg.org/css-overflow-5/#scroll-marker-pseudo) fragment aware. As per @tabatkins [comment](https://github.com/w3c/csswg-drafts/issues/5911#issuecomment-781596466) in the linked issue this seems to be the way that firefox behaves for scroll-snap-align already. If we go this way we may decide whether that [::scroll-marker](https://drafts.csswg.org/css-overflow-5/#scroll-marker-pseudo) should behave the same as well or that it should have a different solution. For our common example, this would require the use of a wrapping element to establish the fragment snap areas and markers:
    ```html
    <style>
      .scroller > div {
        scroll-snap-align: center;
        &::scroll-marker {
          content: ' ';
        }
      }
    </style>
    <div class="scroller">
      <div> <!-- wrapping container generating snap areas and markers -->
        <!-- flowing content or items, e.g. -->
        <div>Item 1</div>
        <div>Item 2</div>
        ...
        <div>Item n</div>
      </div>
    </div>
    ```
3. Introduce fragmentation aware values for these selectors / properties. This would provide a bit more capability as authors could specify for each sytled element which one should have its fragmented parts should generate a snap areas and/or scroll markers. Similar to option 2, this would also require wrapping the content for our common example case:
    ```html
    <style>
      .scroller > div {
        scroll-snap-align: center per-fragment;
        &::scroll-marker(per-fragment) {
          content: ' ';
        }
      }
    </style>
    <div class="scroller">
      <div> <!-- wrapping container generating snap areas and markers -->
        <!-- flowing content or items, e.g. -->
        <div>Item 1</div>
        <div>Item 2</div>
        ...
        <div>Item n</div>
      </div>
    </div>
    ```
4. Support [scroll-snap-align](https://drafts.csswg.org/css-scroll-snap/#scroll-snap-align) (as suggested in #6017) and [::scroll-marker](https://drafts.csswg.org/css-overflow-5/#scroll-marker-pseudo) pseudo-elements on a `::column` selector. This would allow a paginated carousel-like snapping experience to be created as follows:
    ```html
    <style>
      .scroller::column {
        scroll-snap-align: center;
        &::scroll-marker {
          content: ' ';
        }
      }
    </style>
    <div class="scroller">
      <!-- flowing content or items, e.g. -->
      <div>Item 1</div>
      <div>Item 2</div>
      ...
      <div>Item n</div>
    </div>
    ```
   This is similar to option 1, however is more clear about what is being styled. I think developers could think about this as decorating the columns, and the properties may not need to be inherited to the elements in the columns.

[^1]: Note that the current spec uses [::nth-fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment), however having a single element [inherit different styles per fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment:~:text=This%20means%20that%20elements%20split%20between%20fragment%20boxes%20may%20have%20different%20styles%20for%20different%20parts%20of%20the%20element) introduces significant implementation complexity. As such, we would propose initially resolving to go with a single ::fragment style (i.e. the syntax mentioned in the [inline issue](https://drafts.csswg.org/css-overflow-5/#issue-978c73c1))

**Comment by flackr** [comment]
For option 1, there is an added complication that we don't have any way for `@supports` to detect which properties would be currently supported by the `::fragment` selector. E.g. currently you can check for the existence of a property `@supports scroll-snap-align: center)` or a selector `@supports selector(::fragment)` but you wouldn't be able to check whether `::fragment` supports any other properties, like color.

This seems to be a bit of a pre-existing issue with other pseudoclasses having a restricted set of supported properties that we may want to expand upon in the future, but I thought it was worth noting, e.g.
* [::first-line](https://drafts.csswg.org/css-pseudo/#first-line-styling)
* [::marker](https://drafts.csswg.org/css-lists-3/#marker-properties)

**Comment by lilles** [comment]
> 1. Note that the current spec uses [::nth-fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment), however having a single element [inherit different styles per fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment:~:text=This%20means%20that%20elements%20split%20between%20fragment%20boxes%20may%20have%20different%20styles%20for%20different%20parts%20of%20the%20element) introduces significant implementation complexity. As such, we would propose initially resolving to go with a single ::fragment style (i.e. the syntax mentioned in the [inline issue](https://drafts.csswg.org/css-overflow-5/#issue-978c73c1)) [↩](#user-content-fnref-1-ebc26bcde0bfad8bbc5de65798fe150b)

That would be pretty similar to `::first-line`, yes.

For the single `::fragment` case, would you then do inheritance from `::fragment` into the elements laid out into fragments at style recalc time, reflected in getComputedStyle(), or keep a separate set of styles for layout like is done for `::first-line`?

**Comment by flackr** [comment]
> > 1. Note that the current spec uses [::nth-fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment), however having a single element [inherit different styles per fragment](https://drafts.csswg.org/css-overflow-5/#selectordef-nth-fragment:~:text=This%20means%20that%20elements%20split%20between%20fragment%20boxes%20may%20have%20different%20styles%20for%20different%20parts%20of%20the%20element) introduces significant implementation complexity. As such, we would propose initially resolving to go with a single ::fragment style (i.e. the syntax mentioned in the [inline issue](https://drafts.csswg.org/css-overflow-5/#issue-978c73c1)) [↩](#user-content-fnref-1-ebc26bcde0bfad8bbc5de65798fe150b)
> 
> That would be pretty similar to `::first-line`, yes.

I guess unlike `::first-line` all content inherits from `::fragment` since it is all in one of the fragments.

> For the single `::fragment` case, would you then do inheritance from `::fragment` into the elements laid out into fragments at style recalc time, reflected in getComputedStyle(), or keep a separate set of styles for layout like is done for `::first-line`?

I suspect we'd do inheritance from `::fragment` into the elements at style recalc time, but I'm not sure I understand the differences and would welcome guidance here. @bfgeek had concerns with the original nth-fragment as an individual element would have one fragment inherit from one rule and a different one from a different rule, perhaps they can add more detail here?

**Comment by flackr** [comment]
> ACTION: rob to write up ::column option

I've written up a fourth option (so as not to reorder the numbers) for this.
