### ISSUE TITLE
[css-overflow-5] Scroll button pseudo-elements

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#10722]
As part of #9745 I propose adding a pseudo-element which can be created on a scrolling container to provide a button which navigates that scroller. This is a common pattern, typically requiring that developers manually create elements with script to drive these interactions.

Explainer: https://github.com/flackr/carousel/tree/main/scroll-button

E.g. from https://flackr.github.io/carousel/examples/scroll-button/
```css
.scroller {
  overflow: auto;
}
.scroller::scroll-up-button {
  content: "⬆️";
}
.scroller::scroll-down-button {
  content: "⬇️";
}
```

For a more practical example, see the implicit creation of markers in the [carousel demo](https://flackr.github.io/carousel/examples/carousel/image/).

Having these pseudo-elements allows developers to further reduce the amount of extra markup elements they need to add specifically for controls and make their page contents more about the semantics, e.g. a list of content. They can also easily trigger the buttons' presence depending on a state or media query.

Some questions for consideration / resolution:
1. Should the direction be part of the name or a parameter to a common pseudo-element name, e.g. scroll-<direction>-button or scroll-button(<direction>)? My preference is actually for the latter. This may also allow for styling of all scroll-buttons with a single selector.
2. What is the focus / tree order of these buttons? Naively I would think following the block direction, then inline direction, e.g. up, left, scroller, scroller::before, scroller contents, scroller::after, right, down. That said, there are some designs where the scroll buttons are next to each other in focus order, e.g. [the aria apg demo](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/examples/carousel-1-prev-next/) and @argyleink's carousel has them [next to each other](https://gui-challenges.web.app/carousel/dist/) in focus order despite being visually apart.
3. Can we use logical directions? Hopefully yes!
4. How far should clicking one scroll? I think if the scroller has mandatory snap in the scroll axis it should scroll to the next snap area in that axis. Otherwise, I think the most reasonable would be to scroll by a "page" at a time (i.e. the equivalent of the page-up / page-down buttons, typically 85% of the scrollport).

**Comment by SebastianZ** [comment]
To me, this seems to fit more to HTML. Scroll buttons cause an action (scroll up or down) on an element, which is similar to the `popovertarget` attribute in relation to elements with the `popover` attribute.

So we might introduce an attribute like `scrolltarget` that indicates which element to scroll and another one that determines the direction and maybe the amount like `scrollby` (with values like e.g. `pageup`, `pagedown`, `lineup`, and `linedown`) that determines where the element is scrolled to.

Doing so requires more markup, though also gives users more control over it. E.g. they could provide multiple scroll buttons. This also allows for better accessibility by applying appropiate ARIA information. And there wouldn't be any styling constraints.

Sebastian

**Comment by ydaniv** [comment]
> So we might introduce an attribute like scrolltarget that indicates which element to scroll and another one that determines the direction and maybe the amount like scrollby (with values like e.g. pageup, pagedown, lineup, and linedown) that determines where the element is scrolled to.

I like this idea, but I really think it's not mutually exclusive with the OP. IMHO if authors get these buttons created by the UA out of the box and they're stylable, then this covers 80% of use-cases without the need for creating extra markup, and that's a big win. 
Additionally, being able to specify these manually using custom markup would make this feature highly extensible. So I think both solutions should be considered.

**Comment by tabatkins** [comment]
Just as a syntax nit, I think this would be better as a functional pseudo `::scroll-button(...)`. That way you can use `::scroll-button(*)` to apply generic styles to your scroll buttons without repetition (in styles or in selectors), and then `::scroll-button(up)`/etc for the specific styles (like `content` to actually trigger the creation of the ones you want).

**Comment by yisibl** [comment]
I thought of a similar syntax improvement to that proposed by tab a while back.

But there are some subtle differences:

1. `::scroll-button()` It can select all scroll buttons without `*`.
2. Don't use `up/down`, change it to: `::scroll-button(prev)` and `::scroll-button(next)`

**Comment by tabatkins** [comment]
Sure, whether we spell the "select all" case as nothing or `*` doesn't matter. I think we have a bit more precedent on `*` for this sort of thing, but I could be wrong.

For the keywords, note that you can scroll in multiple directions; there will be more than two keywords. I expect the set to be up/down/left/right/block-start/block-end/inline-start/inline-end, and having `prev` and `next` additionally with the behavior of "whichever axis is scrollable, or block if they both are" sounds nice.

**Comment by yisibl** [comment]
> Sure, whether we spell the "select all" case as nothing or * doesn't matter. I think we have a bit more precedent on * for this sort of thing, but I could be wrong.

My main concern was that `*` would lead authors to believe that this function supports CSS selectors.

In addition, can we support scrolling to the scrollbar start and end position here? That is, the first and the last page of the carousel.

**Comment by hvanops** [comment]
@drewstewartdesigns We talked about focus order and tabbing through carousel content just the other day. What do you think about Rob's [proposal above](https://github.com/w3c/csswg-drafts/issues/10722#issuecomment-2338945117)? Is this how you would expect this to work?

**Comment by flackr** [comment]
> > 4. They scroll by one "page" of scroll distance (e.g. similar to page up / down keys on the keyboard), which in most UA's is 85% of the scrollport size in the relevant axis but are adjusted by `scroll-padding`.
> 
> Could it be configurable whether it scrolls one "page" or one snap point/area? I think there are use-cases for both.
> 
> Also, when scrolling a fixed amount like 85% with scroll-snapping, an element that was partly obscured before scrolling can end up being partly scrolled out on the other side without ever being fully visible. This is especially frustrating when scrolling in the inline direction, as text can be cropped across lines, making it unreadable. In these cases, we've added code to ensure that only fully visible elements is scrolled out. Would it be possible to address this issue somehow?

Do you have an example? The way that we avoid this issue for carousel experiences is by ensuring that we have appropriate snap areas. I.e. we will target scrolling 85% but given `scroll-snap-type: x mandatory` it will force it to align to the nearest snap area. I think that defining snap areas would be the recommended way to avoid the scroll resting between lines.

**Comment by johannesodland** [comment]
> Do you have an example? The way that we avoid this issue for carousel experiences is by ensuring that we have appropriate snap areas. I.e. we will target scrolling 85% but given `scroll-snap-type: x mandatory` it will force it to align to the nearest snap area. I think that defining snap areas would be the recommended way to avoid the scroll resting between lines.

I made a quick example here: https://codepen.io/johannesodland/pen/WNqmoYy

Before scrolling: the 3rd item is partially visible on the right side. 
<img width="441" alt="image" src="https://github.com/user-attachments/assets/af6cc89f-16f9-4967-a32b-0a6ccbf96635">


After scrolling 85%: it snaps to item 4, leaving item 3 partially visible on the left side.
<img width="433" alt="image" src="https://github.com/user-attachments/assets/c83dd5c9-ffc5-4393-8626-ea53c27ab905">

**Comment by flackr** [comment]
> I made a quick example here: https://codepen.io/johannesodland/pen/WNqmoYy

Thanks! I think this is a more general problem with scroll-snap. I filed #10914 to work out how we can make this work as expected (i.e. not skipping over content).

**Comment by johannesodland** [comment]
> Thanks @johannesodland! I think this is a more general problem with scroll-snap. I filed #10914 to work out how we can make this work as expected (i.e. not skipping over content).

You're right @flackr. Fixing this in scroll-snap seems right. Thanks for filing 🙏 

It would still be good to be able to scroll snap-area by snap-area, and not page by page though. There are many use-cases for going item by item, i.e. when the snapped item is styled in a special way either through ::snapped or scroll-driven animations.
