### ISSUE TITLE
window.styleMedia is deprecated draft version of window.matchMedia API that is not implemented in Firefox and will be removed from the web platform in future.

### ISSUE THREAD

**Issue by ssmokie** [w3c/csswg-drafts#10724]
* please tag the issue title with the spec's shortname, like `[css-foo]`
  (this is the name from the spec URL, without a level number unless the issue is specific to that level).
  If you're proposing a new feature that doesn't obviously fit in an existing spec, skip this part — don't make something up.

* please be specific (in the title and issue) about what you want to change:
  “make it better” means different things to different people!

* please link to the spec section you're talking about, or at least the spec

**Comment by SebastianZ** [comment]
Correct. There is no `window.styleMedia` API in the current specs, only [`window.matchMedia` in CSSOM View](https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface). So nothing to do here.

Sebastian
