### ISSUE TITLE
[css-overflow-5] Allowing markers to be active even when not scrollable to aligned position

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#10738]
There are many situations in which it may not be possible to scroll to a position that aligns with the natural scrolling position of every marker. For example, in https://flackr.github.io/carousel/examples/carousel/thumbnails/ is is not possible to scroll to a position that centers the first two or last two items. E.g.

In the following scrolling element, it is not possible to scroll the first two boxes to their center snap aligned position:
![scroller](https://github.com/user-attachments/assets/817bcb59-03c5-4fc5-9c98-894cf38c1a92)

This means that if the active marker is determined solely by the item closest to being aligned https://drafts.csswg.org/css-overflow-5/#scroll-container-scroll it will not be possible to show the first two / last two as active.

Should we consider a model where the browser tracks the actual element that has requested to be scrolled into view? This would allow the edge elements to show as active when clicking on those markers. This could have additional benefits if we treat this element as the anchor node for [anchor node selection](https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection) as well. Note that subsequent user scrolling would likely undo the active styling.

Alternately, if we can't solve this in a nice way we could add a note recommending authors avoid these situations by:
* adding padding to the edges of their scrolling element, or
* ensuring their scroll marker elements are scrollport sized, or
* enabling infinite / cyclical scrolling as in #5411

**Comment by tabatkins** [comment]
Hm, so the suggestion would be that, if a scroll-to-element operation is performed, we properly indicate that element as the active one, but if you scroll in any way that's *not* directly to an element (manually, or via scrollTo or scrollBy), we re-select the active element by "closest to aligned" as normal?

That actually sounds pretty reasonable to me. Playing with your example, it's somewhat confusing/weird that clicking on the last several items doesn't do anything, even change the scroll marker. I think it would be a better UI to have the clicked marker styled as active, even if it doesn't actually move the scroller at all.

**Comment by flackr** [comment]
Yup, and further, we could use the scrolled-to-element, when set, as the [anchor node](https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection) which would make navigating to a page with a fragment always keep the targeted fragment visible rather than potentially anchoring to some other element as the page loads.

**Comment by flackr** [comment]
So the proposal is:
We track the last scroll targeted element within each scrolling container, initially null.

When any scroll of a scroll container occurs:
1. If the scroll targets a particular element, (e.g. scrollIntoView, fragment navigation), then that element is used as the last scroll targeted element.
2. Otherwise, if the element snaps to a particular element, that element is selected as the last scroll targeted element.
3. Otherwise, it is set to null.

This last scroll targeted element is used as the [anchor node](https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection) for scroll anchoring, and as the start point to search for the current scroll target for scroll markers.

Some details:
1. If the target is in a nested scroller, should we track the nested scroller instead? I think it's strictly more powerful if we track the targeted element but could see an argument for this.
2. If the target node is removed, presumably we want to forget about it at that point, but this does mean a moved node would be lost.

**Comment by kizu** [comment]
For Table of Contents cases, I can generally remember 3 different types of designs that are related to this issue:

1. The “only the last visible scroll-target is highlighted” (the common use case)
2. The “all visible before and including the last visible scroll-target are highlighted” (the one in this issue + cases when there are many small sections in ToC and we want to mark all of them)
3. _All_ previous scroll-targets are highlighted (when all “already read” sections of a ToC are dimmed, for example).

I wonder if we'd want to have a control over which we choose, and maybe more than one pseudo-class for this? So not just `:target-current`, but two more (needs bikeshedding, but basically `:target-current-visible` for 2 and `:target-previous` for 3 (and, I guess, we could want `:target-next`? alongside))

We could have some logic similar to the one in the latest comment, but I wonder if having more explicit way to control it could be better? (alternative to multiple pseudoclasses could be a separate property that says how the `:target-current` should be selected, I guess?)

**Comment by flackr** [comment]
@kizu this issue is focused specifically on enabling `:target-current` to have a target that best represents the common case of only one target is highlighted. I'm happy to pursue adding other pseudo-classes but I don't think it changes that we should resolve on behavior for this pseudo-class to be able to select a particular element where mutliple share the same scroll aligned position.

**Comment by dbaron** [comment]
FWIW, I like the idea of targeting elements for scroll anchoring; I [suggested it a very long time ago](https://bugzilla.mozilla.org/show_bug.cgi?id=43114#c9) but never got to implementing it.

**Comment by DavMila** [comment]
As we're implementing this in chromium, just wanted to make a note on one detail regarding ::columns, which I don't think has been explicitly talked about but perhaps flows naturally from what's spec'd.
In the following scenario where ::scroll-markers are created both on elements within the container and on the columns of the container:
```
<div class=columns>
  <fragment col1> ::scroll-marker
    <p>1</p> 
    <p>2</p> ::scroll-marker
    <p>3</p>
  </fragment>
  <fragment col2> ::scroll-marker
    <p>4</p>
    <p>5</p> ::scroll-marker
    <p>6</p>
  </fragment>
</div>
```
if `scrollIntoView` is called on `<p>6</p>`, then `<p>5</p>`'s scroll-marker should be selected and not col2's. But, if `scrollIntoView` is called on `<p>4</p>`, then col2 should be the selected scroll-marker and not `<p>2</p>`.
