### ISSUE TITLE
[css-view-transitions-1] Should handle transition frame avoid calling "update pseudo-element styles"  when all animations are paused?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#10735]
https://drafts.csswg.org/css-view-transitions/#handle-transition-frame-algorithm

Right now it calls "update pseudo-element styles" when everything is paused, I'm debugging a VT issue, and it's a lot of noise in the logging, but it's also a waste of cycles.

cc @khushalsagar @noamr @vmpstr

**Comment by nt1m** [comment]
(Since we do have to go through all keyframes anyway to see if we can stop the VT, I suspect we can get whether everything is paused)

**Comment by nt1m** [comment]
> (Since we do have to go through all keyframes anyway to see if we can stop the VT, I suspect we can get whether everything is paused)

I guess it's not quite the case, since we early return if we see a paused animation when checking for running ones

**Comment by noamr** [comment]
I don't think we can do this, because the new element's geometry can change programmatically outside of animations.

**Comment by nt1m** [comment]
Ah right, the new element geometry is translated to the pseudo-element. I was too focused on my issue I forgot about that
