### ISSUE TITLE
[css-easing] `linear` keyword is described as a function in level 1, inconsistent with level 2

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10734]
CSS Easing 2 defines [2.2. The linear easing **keyword**: `linear`](https://drafts.csswg.org/css-easing-2/#valdef-easing-function-linear)] as a [linear easing function](https://drafts.csswg.org/css-easing-2/#linear-easing-function) with two points, [0,0] and [1.1]. It also fully defines the [linear easing **function** `linear()`](https://drafts.csswg.org/css-easing-2/#the-linear-easing-function), with syntax, serialization, etc.

CSS Easing 1 briefly defines [2.1. The linear easing function: `linear`](https://drafts.csswg.org/css-easing-1/#valdef-easing-function-linear) but describes it as a function (despite the lack of `()`), and then later on says that it is "simply the `linear` keyword".

I guess the definition in CSS Easing 1 is an earlier attempt, but now that the definition in CSS Easing 2 is well developed it seems that CSS Easing 1 should be aligned with it. I can see two ways:

1. Define it as a keyword, which it is, but without reference to an undefined (in that level) linear easing function
2. Remove the definition, and just let CSS Easing 2 fully define it.

@birtles @grorg

**Comment by birtles** [comment]
I think part of the confusion is the reference to "function" in level 1 is not referring to a CSS function but rather an easing function.

I don't quite understand the second proposal. The linear easing function needs to existing in level 1.

I think @tabatkins has been tweaking the definitions in level 2 recently so maybe he has thoughts on this.

**Comment by svgeesus** [comment]
> I think part of the confusion is the reference to "function" in level 1 is not referring to a CSS function but rather an easing function.

I agree that is confusing.

**Comment by tabatkins** [comment]
Yeah, "easing function" is just existing terminology that's getting an unfortunate semantic conflict here. (It *is* a function semantically, as it maps an input to an output.)

Have you encountered anyone actually getting confused by this, @svgeesus, or is it just something you noticed?

**Comment by svgeesus** [comment]
The person being confused by it was myself, in the course of adding WPT annotations to Easing 1 and Easing 2 because

 - https://github.com/w3c/csswg-drafts/issues/10688

**Comment by fantasai** [comment]
How about splitting the difference and having the definition be

> The linear keyword produces a linear easing function whose output progress value is equal to the input progress value for all inputs[, i.e. the same function as ''linear(0, 1)''].

with the bracketed part only in L2?

p.s. Level 2 is really hard to read. Can we write specs for humans rather than compilers, please?

**Comment by svgeesus** [comment]
I think that is better, although the bracketed part is not strictly true:

> Although this produces a [linear easing function](https://drafts.csswg.org/css-easing-2/#linear-easing-function), uses of the keyword [linear](https://drafts.csswg.org/css-easing-2/#valdef-easing-function-linear) always serialize as-is, to linear. Whereas the function equivalent linear(0, 1) will serialize to linear(0 0%, 1 100%). These rules are in [Serialization](https://drafts.csswg.org/css-easing-2/#serialization).

So it produces the same effect.

> Can we write specs for humans rather than compilers, please?

I can see both sides of this. Some think this pseudocode algorithmic style is clearer. I don't, because it uses awkward constructs like "continue these steps" and so on that I would rather see expressed as sample code in a real language, so I can run it as well as read it.

I also see the POV where specifications should describe the result and not over-constrain the way it is implemented. This is the "reference implementations considered harmful" POV.

**Comment by tabatkins** [comment]
Yeah, I've been meaning to rewrite the algos a bit, when the pending Agenda+ issues about parsing are resolved.
