### ISSUE TITLE
[css-typed-om] Is using a constructed expression of the form 1px/1px invalid as a <number> 

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#10733]
The WPT test [css/css-typed-om/stylevalue-subclasses/cssScale.tentative.html](https://wpt.fyi/results/css/css-typed-om/stylevalue-subclasses/cssScale.tentative.html) requires that the following throw an exception:

```js
let coord = new CSSMathProduct(CSS.px(1), new CSSMathInvert(CSS.px(1)));
let scale = new CSSScale(coord, 0);
```

with a description calling the product "an invalid division by px/px".

I can't find where (or if) this is required by the current CSS Typed OM draft (and it may just be an invalid test, it is marked tentative), but may be missing it.

Should this be invalid?

**Comment by xiaochengh** [comment]
The test seems wrong. The spec allows px/px.

@devsdk

**Comment by tabatkins** [comment]
Yeah, that is explicitly allowed behavior.  The test is wrong.

**Comment by DevSDK** [comment]
@xiaochengh @weinig  @tabatkins  Yeah. The sepc says it allows it.
Specifically, it was Chromium behaviour (probably still is) . I missed that should not be external WPT test.
I'll fix WPT later :)

**Comment by weinig** [comment]
I took care of updating the test with https://github.com/web-platform-tests/wpt/pull/47897.
