### ISSUE TITLE
[css-shapes-2] Interpolation between `shape()` and `path()` needs more detail

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#10740]
[CSS Basic Shapes 2](https://drafts.csswg.org/css-shapes-2/#interpolating-shapes)  says that `shape()` and `path()` can interpolate if they have the same set of commands, specifically:

> For this purpose, commands are "the same" if they use the same command keyword, and use the same [<by-to>](https://drafts.csswg.org/css-shapes-2/#typedef-shape-by-to) keyword. For [curve](https://drafts.csswg.org/css-shapes-2/#valdef-shape-curve) and [smooth](https://drafts.csswg.org/css-shapes-2/#valdef-shape-smooth), they also must have the same number of control points.

But there's some ambiguity here, because `shape()` takes an initial "from", and it's not clear if that has to correspond to the first Move command in the path. Specifically, it's not clear if these should interpolate:

```
shape(from 0 0, move to 200px 200px, close)
```
and 
```
path(M 100 100 z)
```

Likewise what if the first command in the path is not an absolute move?

```
shape(from 0 0, line to 200px 200px, close)
```
and 
```
path(m 100 100 z)
```

**Comment by smfr** [comment]
cc @noamr @tabatkins

**Comment by noamr** [comment]
Good point, the easiest path forward here I think is that `path()` is always assumed to have `from 0 0`
