### ISSUE TITLE
[css-multicol] specification should define interaction between 'column-span' and 'column-fill'

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1075]
The [multicol spec](https://drafts.csswg.org/css-multicol/) doesn't define the interaction between 'column-fill' and elements that have 'column-span'.  The definition of column-span says:
> Content in the normal flow that appears before the element is automatically balanced across all columns before the element appears.

I think it's reasonably clear that in a non-paged context, this means that `column-fill` is only honored in the part of the multicol after the last `column-span: all` element inside it.  However, it's less clear what happens in paged media.  Reading the text quoted above literally, the spec currently says that `column-fill: balance-all` behavior (rather than `balance`, which is the initial value) is required on any pages of a multicolumn element where a later page has a column-spanning element.

This should actually be defined in a somewhat formal manner.  The current spec appears to be more of a use cases document than a specification on this topic.

/cc @neerjapancholi

**Comment by frivoal** [comment]
I think requiring the balance-all behavior on all preceding pages is an unintended side effect of the imprecise wording you mentioned, and that "balanced across all columns before the element appears." should be scoped to the current fragmentainer.

**Comment by mstensho** [comment]
How about honoring `column-fill` also in column rows *preceding* a spanner, if the value is either `balance` or `balance-all`? If it's `auto`, we obviously have to balance at least the previous column row, but forcing `balance-all` behavior seems unnecessary.

**Comment by astearns** [comment]
Removing agenda+ until #1072 is resolved
