### ISSUE TITLE
[css-anchor-position-1] In the spec the anchor-size() function hasn't been markedup as new sizing value

### ISSUE THREAD

**Issue by OnkarRuikar** [w3c/csswg-drafts#10764]
- as requested in https://github.com/w3c/webref/issues/1312#issuecomment-2296164743

The section [`4.1 The anchor-size() Function`](https://drafts.csswg.org/css-anchor-position-1/#anchor-size-fn) hasn't been framed like the [`3.2. New Sizing Values: the stretch, fit-content, and contain keywords`](https://drafts.csswg.org/css-sizing-4/#sizing-values) section.  
So the `w3c/webref` crawler can't relate the value to the properties that can take it. The section needs to be formatted as explained below:
> As [done in css-sizing-4](https://drafts.csswg.org/css-sizing-4/#sizing-values), css-anchor-position would ideally list the impacted CSS properties in a table with a "New Values" row instead of [only saying so in prose](https://drafts.csswg.org/css-anchor-position-1/#sizing).

Also, the section needs to mention that the value also applies to logical sizing properties. It also needs to mention properties agreed in [the latest resolution](https://github.com/w3c/csswg-drafts/issues/9827#issuecomment-2160430157).

**Comment by tabatkins** [comment]
Added a partial propdef for both anchor() and anchor-size(), thanks. Also updated the anchor-size() usage to allow the new properties.

> Also, the section needs to mention that the value also applies to logical sizing properties.

Why do you think this is necessary? The grammar of the logical sizing properties is just `<'width'>` or the equivalent, so they'll automatically pick up this value if it's defined for 'width', and there's nothing about the behavior of the function that would make it different for logical vs physical properties. Am I missing a requirement about logical props that requires them to be explicitly opted in?
