### ISSUE TITLE
[css-fonts-3] [css-fonts-4] getComputedStyle() and CSSStyleDeclaration of expanded shorthand

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#1076]
In CSS2.1, the `font` shorthand [accepted](https://www.w3.org/TR/CSS21/fonts.html#font-shorthand) values `normal` and `small-caps` for its `font-variant` constituent longhand.

In CSS Fonts level 3, `font-variant` was [expanded](https://drafts.csswg.org/css-fonts/#propdef-font-variant) to accept many new keywords. However, the `font` shorthand was [not similarly expanded](https://drafts.csswg.org/css-fonts/#font-variant-css21-values): It still only accepts `normal` and `small-caps`.

This forces us to ask the question, what is the value of:
```
<div id="test1" style="font: 16px Times; font-variant: historical-ligatures;">Hello World</div>
...
window.getComputedStyle(document.getElementById("test1")).getPropertyValue("font");
document.getElementById("test1").style.font;
```

This is also relevant to the variable fonts discussion: the `font-weight`, `font-stretch`, and `font-style` properties are part of the `font` shorthand, and are also becoming more expressive.

Currently, in WebKit, I'm proceeding as if the expanded values are equivalent to `normal` when constructing these strings. I'm not sure if this is the right way to go.

See also: https://github.com/w3c/csswg-drafts/issues/515

cc @fantasai @tabatkins

**Comment by upsuper** [comment]
The shorthand in this case is not serializable, and should return empty string per spec.

It isn't an unusual case. Many shorthands are unable to express all the combinations of their longhands.

**Comment by litherum** [comment]
@upsuper Do you have a link on where this is described in the spec? I'd love to read more about it.

**Comment by upsuper** [comment]
In CSSOM spec, the [serialize a CSS value](https://drafts.csswg.org/cssom/#serialize-a-css-value) algorithm in step 1.2 says:
> If shorthand cannot represent the values of list in its grammar, return the empty string and terminate these steps.

In general, any shorthand accepts a list of things is more likely to fail to express its longhands, e.g. `animation: a 1s, b 2s; animation-name: a;` cannot be expressed in `animation` shorthand.

(There is a bug in WebKit for this case, though, that it serializes this as `animation: a 1s, 2s` and parses the serialized shorthand to `animation-name: a, initial` which is an invalid declaration.)

**Comment by mrego** [comment]
Would this apply to other shorthands like `flex` (or the different `grid` shorthands)? I was explicitly asking about this in #1041. Thanks!
