### ISSUE TITLE
[css-view-transition-2] Should non-default `view-transition-group` act like `contain`?

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10780]
Right now `view-transition-group` is a bit inconsistent, because:
- `nearest` and `<custom-ident>` refer to nesting from the descendant's point of view
- `contain` refers to nesting from the ancestor's point of view.

Perhaps it would make more sense that `nearest` and `<custom-ident>` would also act as `contain`? I think the discussion in the WG [here](https://github.com/w3c/csswg-drafts/issues/10334#issuecomment-2165761156) was sort of saying it but the resolution was ambiguous.

If we do that, what happens when there's an invalid `<custom-ident>`?

cc @vmpstr @khushalsagar @fantasai, also @ydaniv that raised this concern in the last VT breakout.

**Comment by khushalsagar** [comment]
The reason we added `contain` was so not all children have to set `view-transition-group` for an example like [this](https://github.com/w3c/csswg-drafts/issues/10334#issuecomment-2111871610).

Can you expand on what you're proposing with "nearest and <custom-ident> would also act as contain". I'm guessing `<custom-indent>` implies the parent specifying the list of children nesting to it. I feel like that defeats the purpose of having `contain`...

And not sure how `nearest` would be used if it's on the parent.

**Comment by noamr** [comment]
> The reason we added `contain` was so not all children have to set `view-transition-group` for an example like [this](https://github.com/w3c/csswg-drafts/issues/10334#issuecomment-2111871610).
> 
> Can you expand on what you're proposing with "nearest and would also act as contain". I'm guessing `<custom-indent>` implies the parent specifying the list of children nesting to it. I feel like that defeats the purpose of having `contain`...
> 
> And not sure how `nearest` would be used if it's on the parent.

Let's say this is the hierarchy
```css
html { view-transition-name: root }
  parent { view-transition-name: parent; view-transition-group: nearest; }
    child { view-transition-name: child; }
```
Based on the current spec wording, the `view-transition-group` for `child` would be `root`.
But there is some logic in having it be `parent`, as in, when an element becomes specifically nested, it also becomes nesting, and exiting the nearest group is the exception. In the last WG breakout @fantasai alluded to this being the essence of how this should work. 

I wanted to either re-affirm the current spec wording (`child` would be not be nested in this example), or the other way (`child` would be nested in `parent` in this example).

**Comment by khushalsagar** [comment]
> Based on the current spec wording, the view-transition-group for child would be root.

I thought child in this case would be under `::view-transition` (no parent group). Since `view-transition-group` for child would be `normal` which is spec'd as: "The used value is the element’s nearest containing group name." There is no containing group name in the example above?

> But there is some logic in having it be parent, as in, when an element becomes specifically nested, it also becomes nesting

Maybe we need a combo keyword, since in this situation you want parent to be `nearest` and `contain` at the same time? I don't know if there's precedence for this in CSS, defining which keywords can be combined with each other.

**Comment by noamr** [comment]
OK, I see 3 options here:

1. Keep the current wording
2. `nearest` and `<custom-ident>` implicitly also mean `contain`
3. `contain` can be added as a keyword to `nearest` and `<custom-ident>`, by default they don't contain.

**Comment by ydaniv** [comment]
I still think it's somewhat confusing, plus there may be a scenario for an element to both a containing parent and a contained child. 
I'm also not sure a the combo idea, since it also makes sense to have `contain` by itself. 
Feels like it's either a case of a longhand or two separate properties stuffed together into one, kind of where it started, right?

**Comment by noamr** [comment]
> I still think it's somewhat confusing, plus there may be a scenario for an element to both a containing parent and a contained child. 
> 
> I'm also not sure about the combo idea, since it also makes sense to have `contain` by itself. 

We can still allow that, meaning `normal contain`
> 
> Feels like it's either a case of a shorthand or two separate properties stuffed together into one, kind of where it started, right? 

I wonder if we need this contain keyword at all TBH. This kind of containment can be easily achieved through combinator selectors and perhaps it's better to keep it there rather than create this vt-specific mini-cascade.

**Comment by ydaniv** [comment]
Well, at the end of the day `contain` is mostly sugaring the other values. It's also possible to just remove it for starters.

**Comment by khushalsagar** [comment]
Out of the options in https://github.com/w3c/csswg-drafts/issues/10780#issuecomment-2312503998, my preference would be 3). Not a fan of 2) since it makes it impossible to use nearest/custom-ident without also forcing contain.

**Comment by noamr** [comment]
> Out of the options in [#10780 (comment)](https://github.com/w3c/csswg-drafts/issues/10780#issuecomment-2312503998), my preference would be 3). Not a fan of 2) since it makes it impossible to use nearest/custom-ident without also forcing contain.

Also added option (4).

**Comment by fantasai** [comment]
This was the proposal we resolved on: https://github.com/w3c/csswg-drafts/issues/10334#issuecomment-2165649094

<hr>
Just read though the thread (quickly, so might have missed something). I think what you want (?) is something like

`view-transition-group: normal | <ident> | auto | contain` where

- normal - defaults to placing directly under transition root (current behavior).
- `<ident>` - groups the under the element with the specified `view-transition-name` _and_ automatically changes `normal` descendants to default to this item.
- `auto` or `nearest` - same as `<ident>` but chooses the closest ancestor with `view-transition-name`.
- `contain` - captures descendants to this element, but doesn't affect this element's position in the tree.

The property name hooks into the `::view-transition-group` pseudo-element name, and it is not inherited. It applies to elements with `view-transition-name` only.
