### ISSUE TITLE
[css-flexbox-1] Change flex shorthand of flex:1 back to setting a flex-basis of 0%.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#10782]
https://drafts.csswg.org/css-flexbox-1/#change-2015-flex-basis-zero

```
<!DOCTYPE html>
<body style="flex:1">
<script>
document.body.innerText = getComputedStyle(document.body).flexBasis;
</script>
```

Basically nobody implemented this change when it was made in the spec. ~10 years later all browsers currently set the flex-basis to 0%, instead of 0px.

This change won't be web-compatible now, and should be reverted back to setting 0% as the flex-basis.
(before my time - reading about this - part of the rationale was to help fix the intrinsic-sizing algorithm, but that also isn't web-compatible).

**Comment by Loirooriol** [comment]
Under discussion in #5742
