### ISSUE TITLE
[css-shadow-parts][css-view-transitions] Are view transition pseudo-elements allowed after ::part()?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#10806]
My understanding of the view transition pseudo-elements is that they are all pseudo-elements on the root element.  This means they don't really make sense to be allowed after `::part()`, despite that [the `::part` spec](https://drafts.csswg.org/css-shadow-parts-1/#part) says that all pseudo-elements are allowed after `::part()`.

If we agree in #10786 that the rules on what is allowed after `::part()` are a parse-time restriction, then we probably need to decide whether the view transition pseudo-elements should be allowed.  My current inclination is that they probably shouldn't be since they could never match, but I don't have a strong opinion.

**Comment by nt1m** [comment]
It should probably behave the same way as adding a view transition pseudo-element after a normal element, e.g. parse but not match anything

**Comment by tabatkins** [comment]
Scoped VTs will allow the VT pseudo-els to be used on elements other than the root, so it'll eventually make sense to be able to use them on ::part().

For now, I indeed think that we should allow them to exist but just not match anything.

**Comment by dbaron** [comment]
OK, sounds like making no change is the right path here, then.
