### ISSUE TITLE
[css-view-transitions] State management seems broken in the spec

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10822]
Per spec, this snippet calls the transition callback twice:

```js
document.startViewTransition(async function() {
  console.log("cb");
  document.startViewTransition(() => {});
});
```

This is in fact what happens in Safari TP, and in my experimental Firefox implementation.

This is because [call the update callback](https://drafts.csswg.org/css-view-transitions-1/#call-the-update-callback) says:

  * Otherwise, set callbackPromise to the result of [invoking](https://webidl.spec.whatwg.org/#invoke-a-callback-function) transition’s [update callback](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-update-callback).
  * If transition’s [phase](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-phase) is not "done", then set transition’s phase to "update-callback-called".

But that's already too late, because if something (like `startViewTransition`) skips the transition, the state is not "update-callback-called".

It seems for this specific case, just swapping those two steps should work. But might be worth looking at similar things in the spec.

cc @khushalsagar @vmpstr @mattwoodrow @nt1m

**Comment by emilio** [comment]
cc @noamr too.

**Comment by noamr** [comment]
Good catch, I think swapping them should be sufficient, as the previous steps in `call the update callback` are just setup and don't have any effect.

**Comment by emilio** [comment]
Yeah at first I was more concerned about this being a general problem, but this is the only place where I found the issue so far.

**Comment by nt1m** [comment]
I'm fixing this in WebKit with a WPT: https://github.com/WebKit/WebKit/pull/33091

I'm not sure the exact wording of the current spec PR is right though (I commented there already)
