### ISSUE TITLE
[css-scroll-snap] Should negative scroll-padding be allowed?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1084]
Was flipping through [old comments](https://github.com/w3c/csswg-drafts/issues/395#issuecomment-241158192) and noted that we forgot to consider whether `scroll-snap-padding` should be restricted to non-negative values. In light of that discussion, I think we should go ahead and disallow negative values.

Thoughts?

**Comment by tabatkins** [comment]
Padding is already restricted to non-negative, and scroll-snap-padding's purpose is to make sure the snapped points don't get overlapped by other stuff positioned at the edges of the screen.  A negative scroll-snap-padding would void that, as the scroller *itself* would overlap it.

So :+1:

**Comment by frivoal** [comment]
Agreed. I suspect that if somebody actually came up with use cases, these would more likely be solved by introducing a `scroll-(snap-)margin` and allowing that to be negative.

**Comment by tabatkins** [comment]
Agenda+ to approve this normative change (restricting scroll-padding to non-negative values only).

**Comment by astearns** [comment]
I'm assuming we need one or more testcases for this change

**Comment by astearns** [comment]
Reopening for testcase need.
