### ISSUE TITLE
[css-pseudo] Should ::before / ::after really be part-like?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10846]
When @tabatkins introduced part-like pseudos in the spec (0f41712965), it was added that:

> Both [::before](https://drafts.csswg.org/css-pseudo/#selectordef-before) and [::after](https://drafts.csswg.org/css-pseudo/#selectordef-after) are [part-like pseudo-elements](https://drafts.csswg.org/css-pseudo/#part-like-pseudo-elements); there is no restriction on what properties apply to them.

While it is true that there are no property restrictions on these pseudos, I'm not sure they should be part-like pseudo-elements.

part-like pseudo-elements should have other properties (like supporting further pseudos, or a bunch of pseudo-classes that `::before` and `::after` do not support).

So I'm not convinced `::before` and `::after` should be marked as such?

**Comment by emilio** [comment]
cc @dbaron

**Comment by dbaron** [comment]
I'm inclined to agree although I'm not sure yet.  I was expecting to look into this as part of the "audit" I suggested in #10794.

**Comment by dbaron** [comment]
I think making `::before` and `:after` part-like means that `::before::before` should work.  Supporting potentially infinite levels of `::before`/`::after` seems like it might be problematic.  (Though maybe not?)

**Comment by Loirooriol** [comment]
Note that `::before::marker` works (well, browsers don't support the selector yet, but the `::before` can originate a marker box).

**Comment by tabatkins** [comment]
Hm, I'm fine either way.

**Comment by josepharhar** [comment]
I thought that part-like means that the main/parent element of the pseudo-element has a UA shadowroot, and there is an element in that shadowroot which the pseudo-element points to, but based on this discussion I guess that's not true, thats just how its implemented in blink.

**Comment by kbabbitt** [comment]
> I think making `::before` and `:after` part-like means that `::before::before` should work. Supporting potentially infinite levels of `::before`/`::after` seems like it might be problematic. (Though maybe not?)

FWIW, the spec currently states this is invalid. https://drafts.csswg.org/selectors-4/#sub-pseudo-elements:
> Unless the corresponding [sub-pseudo-element](https://drafts.csswg.org/selectors-4/#sub-pseudo-element) is explicitly defined to exist in another specification, pseudo-element selectors are not valid when compounded to another pseudo-element selector. So, for example, ::before::before is an invalid selector, but ::before::marker is valid (in implementations that support the ::before::marker sub-pseudo-element).
