### ISSUE TITLE
[css-contain-2] Effects of content-visibility on elements that do not generate a box

### ISSUE THREAD

**Issue by sammygill** [w3c/csswg-drafts#10848]
```<!DOCTYPE html>
<html>
<div style="display: contents; content-visibility: hidden;">
  <div>
    <div style="width: 100px; height: 100px; background-color: green;"></div>
  </div>
</div>
</html>
```

In the above example we have `content-visibility: hidden` on an element which has `display: contents`. In this case what should the behavior be of the property, if anything, since the element it is on does not generate a box in the box tree. 

The spec does not seem to say anything explicitly about scenarios like this so I am wondering if the effect would be to just ignore `content-visibility` or if there is a more desirable outcome?

**Comment by Loirooriol** [comment]
The spec seems clear to me. `content-visibility` applies to

> elements for which [size containment](https://drafts.csswg.org/css-contain-2/#size-containment) can apply

And then

> giving an element [size containment](https://drafts.csswg.org/css-contain-2/#size-containment) has no effect if any of the following are true:
> - if the element does not generate a [principal box](https://drafts.csswg.org/css-display-4/#principal-box) (as is the case with [display: contents](https://drafts.csswg.org/css-display-3/#propdef-display) or display: none)

**Comment by sammygill** [comment]
Aha! The does seem to clear it up I missed that first part in the `content-visibility` section.
