### ISSUE TITLE
[css-values-4] Which IEEE-754 semantics do math functions follow?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [w3c/csswg-drafts#10849]
https://drafts.csswg.org/css-values-4/#calc-ieee says that math functions follow IEEE-754 semantics, however IEEE-754 defines many types of numbers (see section _3.6 Interchange format parameters_):
- binary floats with 16 bits
- binary floats with 32 bits
- binary floats with 64 bits
- binary floats with 128 bits
- decimal floats with 32 bits
- decimal floats with 64 bits
- decimal floats with 128 bits

Which one of the should CSS math functions use?

Based on https://github.com/mozilla/pdf.js/pull/18698#issuecomment-2334654444, it seems like some browsers use binary32 while others use binary64.

**Comment by cdoublev** [comment]
I think CSS conformance to IEEE-754 is only related to *the concepts of positive and negative zero, positive and negative infinity, and NaN (not a number)*. CSS assumes [infinite precision](https://drafts.csswg.org/css-values-4/#numeric-types):

  > The precision and supported range of numeric values in CSS is [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined), and can vary based on the property or other context a value is used in. However, within the CSS specifications, infinite precision and range is assumed.

**Comment by Loirooriol** [comment]
#4551 proposed to do calculations with f64, but the resolution was "Math precision in CSS is currently kept undefined".

**Comment by tabatkins** [comment]
Yes, the implication is that they follow 754 semantics *for the purpose of things defined below, in that subsection* - signed zeros, infinities, and NaNs.

Precision and other numeric representation issues have been left intentionally undefined in CSS.
