### ISSUE TITLE
[css-fonts-3][css-fonts-4] Is `CSSFontFaceRule.style` missing `[SameObject,PutForwards=cssText]`?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10842]
All `CSS*Rule.style` attributes except [`CSSFontFace.style`](https://drafts.csswg.org/css-fonts-4/#cssfontfacerule) are defined with `[SameObject,PutForwards=cssText]`:

  - [`CSSKeyframeRule.style`](https://drafts.csswg.org/css-animations-1/#csskeyframerule)
  - [`CSSPageRule.style`](https://drafts.csswg.org/cssom-1/#csspagerule)
  - [`CSSMarginRule.style`](https://drafts.csswg.org/cssom-1/#cssmarginrule)
  - [`CSSPositionTryRule.style`](https://drafts.csswg.org/css-anchor-position-1/#csspositiontryrule)
  - [`CSSStyleRule.style`](https://drafts.csswg.org/cssom-1/#cssstylerule)

Is it intentional?

The practical implication, in current Chrome/FF version:

```js
const sheet = new CSSStyleSheet()

sheet.replaceSync('style {} @font-face {}')

const style = sheet.cssRules[0]
const font = sheet.cssRules[1]

style.style = 'color: green'
style.cssText; // style { color: green }
font.style = 'font-style: italic'
font.cssText; // @font-face {}
```

**Comment by svgeesus** [comment]
I don't know but I spot @emilio as the editor of those other specs so look forward to an explanation

**Comment by emilio** [comment]
Yeah, I don't think it's intentional, we should probably be consistent. That said, in Gecko at least font-face descriptors aren't mutable, see https://bugzilla.mozilla.org/show_bug.cgi?id=443978...

**Comment by svgeesus** [comment]
@cdoublev please feel free to send a PR to make this interface consistent with the others.
