### ISSUE TITLE
[css-values-5] Accept progress notations for any `<number>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10841]
[Progress functional notations](https://drafts.csswg.org/css-values-5/#progress) seems to be restricted to arguments of math functions and mix notations.

  > The resulting ratio can then be input into other calculations, such as a math function or a mix notation.

If it cannot be used to represent a `<number>` in any context, can you please clarify why?

**Comment by cdoublev** [comment]
Somewhat related question: should a progress notation be considered an operator node or a leaf node?

For example, should `opacity: calc(progress(1 from 1 to 1))` serialize with or without the `calc()` wrapper? `calc(1)` (leaf case) should serialize with it and `calc(min(1em / 1px, 1))` (operator case) should serialize without it.

I suspect progress notations (and tree-counting functions and perhaps `random()`) should be considered calculations (but not math functions) and handled like math functions, ie. as operators.

**Comment by fantasai** [comment]
It is certainly intended to be used anywhere as a `<number>`. I've clarified the wording a bit, lmk if that doesn't work for you. :)
