### ISSUE TITLE
[cssom-1] Add an IDL for CSSMarginDescriptors for the CSSMarginRule interface.

### ISSUE THREAD

**Issue by cyraid** [w3c/csswg-drafts#10855]
https://github.com/w3c/csswg-drafts/blob/5a791c2605e639d8f6c349259127801fdb2cd83a/cssom-1/Overview.bs#L2188

Just by following the comment (`attribute must return a <code>CSSMarginDescriptors</code> object for the
margin at-rule, with the following properties:`)
```html
<pre class=idl>
interface CSSMarginDescriptors {
  attribute boolean computed;
  attribute boolean readonly;
  readonly attribute (Element or ProcessingInstruction)? ownerNode;
}
</pre>
```

Something like that could be added? I'm not sure if that's entirely accurate, if someone could double check. This is for the scrapers out there like WebIDL2.

Thanks guys.

Edit: Though I think computed / readonly may need to be readonly? (or not, but it says to have them unset). There also needs to be declarations. Thoughts?

**Comment by cdoublev** [comment]
These properties are neither exposed by [`CSSStyleDeclaration`](https://drafts.csswg.org/cssom-1/#cssstyledeclaration) or `CSSMarginDescriptors`, whose IDL definition is indeed missing (reported in #10106). Perhaps *"internal properties"* should be used instead.

**Comment by cyraid** [comment]
Fair enough, I'll close this because it's a duplicate.
