### ISSUE TITLE
Questions: about relative selectors..

### ISSUE THREAD

**Issue by tomasts248** [w3c/csswg-drafts#10856]
Hello, 
Sorry if this is the wrong place.. but I wasn't sure where should I ask for clarification on this, I asked on forums but I didn't get clarification on this and I know here there are experts on CSS, so I was reading: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector
and I'm not sure which part of the following examples from MDN are the anchor part?
```
:has(+ div#topic > #reference) {
}

:has(> .icon) {
}

dt:has(+ img) ~ dd {
}
```

My bet is that these are the anchors:

```
div#topic > #reference

.icon

img

```

And also if im getting this correctly, a relative selector would be any selector with a function with parameters or that is incorrect? Last which relative selectors can be nested?

**Comment by cdoublev** [comment]
The anchor elements are the other part of your selectors.

https://drafts.csswg.org/selectors/#overview

  > The following table summarizes the Selector syntax:
  >
  > | Pattern              | Represents |
  > | -------------------- | - |
  > | `E:has(rs1, rs2, …)` | an `E` element, if there exists an element that matches either of the relative selectors `rs1` or `rs2`, when evaluated with `E` as the anchor elements |

`*` (universal selector) is implied before a pseudo-selector, like in `:has(+ div#topic > #reference)`, in which it is the (implicit) anchor element.

https://drafts.csswg.org/selectors/#relative

  > Relative selectors begin with a combinator, with a selector representing the anchor element implied at the start of the selector. (If no combinator is present, the descendant combinator is implied.)

A relative selector can currently only appear in `:has()` or as the selector of a [nested style rule](https://drafts.csswg.org/css-nesting-1/#nesting).

For what is worth, I prefer learning CSS by reading the specs rather than MDN, which is still great for a quick overview/refresher.

**Comment by tomasts248** [comment]
> The anchor elements are the other part of your selectors.

I understand now, thank you so much :)

> A relative selector can currently only appear in :has() or as the selector of a [nested style rule](https://drafts.csswg.org/css-nesting-1/#nesting).

Oh sorry if I ask too much things, why is() where() and not() cant contain relative selectors?

> For what is worth, I prefer learning CSS by reading the specs rather than MDN, which is still great for a quick overview/refresher.

Thanks :+1:

**Comment by cdoublev** [comment]
`.parent:has(> .child)` simply makes more sense than `.parent:is(> .child)` (assuming the latter is valid). Besides, `.parent:has(.child)` `.parent:is(.child)` would select different elements.

`:has()` qualifies the selector subject with the relations it *has* with other elements. `:is()`/`:where()`/`:not()` qualify the selector subject with subselectors defining what it *is*.

**Comment by tomasts248** [comment]
Thank you so much understood :+1:
