### ISSUE TITLE
[mediaqueries-5] Incomplete list of changes wrt level 4

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10864]
The [Changes since the Media Queries Level 4](https://drafts.csswg.org/mediaqueries-5/#changes-level-5) is incomplete; it misses out the `video-*` and `dynamic-range` media features , for example.

**Comment by svgeesus** [comment]
So the changes section is ambiguous. The heading says

> Changes since the Media Queries Level 4

(implying, all changes since Level 4). But the text then says:

> The following additions were made to the First Public Working Draft of this module since the [Media Queries Level 4](https://www.w3.org/TR/mediaqueries-4/):

implying, just the changes between Level 4 and FPWD of Level 5.

The minimal change would be to alter the heading so that it is clear these are just the changes for FPWD. If desired, a cumulative summary of "All changes since Level 4" could be added later.

**Comment by SebastianZ** [comment]
> If desired, a cumulative summary of "All changes since Level 4" could be added later.

I've added them now in https://github.com/w3c/csswg-drafts/commit/bc67c7f91ba08c0473129795552148fbbcd949cd.

Sebastian
