### ISSUE TITLE
[css-multicol] column-span examples are unclear about visual/source order of text

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1087]
The examples in the [section on column-span](https://drafts.csswg.org/css-multicol/#column-span) are rather difficult to understand because it's not obvious, looking at the examples visually, what the order of the text in the source document is.

It would probably be much clearer if the text used real sentences rather than bits of alphabet, and in particular real sentences that have a relatively obvious order associated with the pieces of the sentence.

**Comment by rachelandrew** [comment]
I agree, and in general I think these could be made clearer by turning each into an SVG (rather than these mocked up code examples). More like the examples in the grid spec. Unless there is some issue with that I'll create SVG images that clearly show these examples.

**Comment by frivoal** [comment]
No problem at all, we ended up with these drawings because they are simpler to create, not because anyone prefers that sorts of things.

**Comment by rachelandrew** [comment]
I have now replaced all of the examples. I've tried to remain faithful to the intent of the originals. I suggest that if any of the images or indeed the examples themselves still need work individual issues are raised. I have a big Sketch file of all of these so can make any changes that we think would make things clearer, therefore I'll close this issue.

**Comment by frivoal** [comment]
Can you put the Sketch file in the repository, just in case we need to make edits to these 7 years from now and you're not longer editing the spec by then? No need to link to them from anything, just put them in the same directory.

**Comment by rachelandrew** [comment]
good call, I'll tidy it up a bit and do so.
