### ISSUE TITLE
[css-display-4] Special Consideration(s) of Establishing Container Block

### ISSUE THREAD

**Issue by DYCDAMallgren** [w3c/csswg-drafts#10871]
According to https://github.com/w3c/csswg-drafts/blob/main/css-display-4/Overview.bs:

  In general, the [=box edge|edges=] of a [=box=]
  act as the [=containing block=] for descendant boxes;
  we say that a box “establishes”
  the [=containing block=] for its descendants.

And for outside of generality?

[](https://www.w3.org/TR/css-sizing-4/)

**Comment by bramus** [comment]
> And for outside of generality?

Think of descendants that have a `position: absolute` or `position: fixed` declared on them. Those descendants don’t use the direct parent’s box as the CB but they use something else. This is described in https://drafts.csswg.org/css-position/#def-cb

**Comment by DYCDAMallgren** [comment]
> > And for outside of generality?
> 
> Think of descendants that have a `position: absolute` or `position: fixed` declared on them. Those descendants don’t use the direct parent’s box as the CB but they use something else. This is described in https://drafts.csswg.org/css-position/#def-cb

What about display: flex?

https://github.com/w3c/csswg-drafts/blob/main/css-sizing-3/Overview.bs

<pre class=propdef>
	Name: min-width, min-height
	Value: auto | <<length-percentage [0,∞]>> | min-content | max-content | <nobr>fit-content(<<length-percentage [0,∞]>>)</nobr> | <<min-width/calc-size()>>
	Initial: auto
	Applies to: all elements that accept 'width' or 'height'
	Inherited: no
	Logical property group: min-size
	Percentages: relative to width/height of <a>containing block</a>
	Computed Value: as specified, with <<length-percentage>> values computed
	Animation Type: by computed value, recursing into ''min-width/fit-content()''
	</pre>

**Comment by bramus** [comment]
That would be described in the flexbox specification: https://drafts.csswg.org/css-flexbox-1/#flex-containers
