### ISSUE TITLE
Chrome and Edge support the 'auto' keyword for the animation-duration property - did the W3C documentation accidentally miss this?

### ISSUE THREAD

**Issue by phdave2005** [w3c/csswg-drafts#10888]
* CSS Animations Level 1

* The **animation-duration** property - according to the spec - is parsed as `<time [0s,∞]>#`. However, both MDN page AND screenshots from Chrome and Edge show the keyword 'auto' is supported for both non-prefixed and -webkit- prefixed in these chromium browsers (see attached). However, Firefox does NOT support the 'auto' keyword for non-prefixed property (pls see attached). Can this discrepancy between docs and chromium browsers pls be clarified? Is 'auto' a non-standard keyword or did the W3C documentation accidentally miss this keyword as a viable value for **animation-duration**?

* [link to section of spec](https://www.w3.org/TR/css-animations-1/#animation-duration)

![animation-duration-keyword-auto-mdn](https://github.com/user-attachments/assets/f948de9a-8f5d-425b-b963-da03fd43aeb2)
![animation-duration-keyword-auto-not-supported-firefox](https://github.com/user-attachments/assets/4c24db5e-9ed7-4e6e-aaab-fe49d8fcc739)
![animation-duration-keyword-auto-supported-chrome-plus-w3c](https://github.com/user-attachments/assets/caf343b9-ab29-4002-a8b9-78580a012ae9)
![animation-duration-keyword-auto-supported-edge](https://github.com/user-attachments/assets/1809ea7e-cfec-4b01-b865-9fb11ec11cf2)

**Comment by cdoublev** [comment]
It is defined in the [level 2](https://drafts.csswg.org/css-animations-2/#animation-duration). :relaxed:
