### ISSUE TITLE
[css-values-5] <progress> requires easing-function?

### ISSUE THREAD

**Issue by alvaromontoro** [w3c/csswg-drafts#10897]
I was reading the First Public Working Draft of CSS Values and Units Module Level 5 and, in the [section about the `<progress>` type](https://www.w3.org/TR/css-values-5/#progress-type), it indicates that the `easing-function` is required:

```
<progress> = [ <percentage> | <number> | <'animation-timeline'> ]? && by <easing-function>
```

However, in the [examples in the following sections](https://www.w3.org/TR/2024/WD-css-values-5-20240913/#mix), the `by <easing-function>` is omitted in all of them:

```
color: mix(90%, currentcolor, black);
```

It looks like it's optional and the default value is `linear` if none is indicated (I don't know if that is something to call out explicitly.)

**Comment by Loirooriol** [comment]
Fixed by #10781. You can see the updated draft here: https://drafts.csswg.org/css-values-5/#progress-type
