### ISSUE TITLE
[cssom] Special serialization rules for transition shorthand are not specced

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#10901]
It was resolved here to change the serialization rules for the transition shorthand property: https://github.com/web-platform-tests/wpt/issues/43574

As @fantasai pointed out, there is no spec which explicitly says how to do this serialization: https://github.com/web-platform-tests/wpt/issues/43574#issuecomment-1847544320

I got a request [here](https://issues.chromium.org/issues/367304517#comment4) to spec these changes.

**Comment by fantasai** [comment]
Serialization is defined [in CSSOM](https://drafts.csswg.org/cssom/#serializing-css-values). What spec changes are you looking for?

**Comment by josepharhar** [comment]
For the transition shorthand, there are some slightly complex rules we implemented which omit certain longhands during serialization if the longhand has its initial value.

Maybe this existing text is good enough...?

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

> For legacy reasons, some properties serialize in a different manner, which is intentionally undefined here due to lack of resources. Please consult that property’s specification and/or your local reverse-engineer for details.

I don't insist on making changes, but I was asked about the spec for the breaking change I made to comply with https://github.com/web-platform-tests/wpt/issues/43574

**Comment by nt1m** [comment]
Yes this is the text that we've used to guide our change.

**Comment by josepharhar** [comment]
thanks, sounds like no changes are needed
