### ISSUE TITLE
[css-ui] Pseudo-elements for checkmark and dropdown icon for appearance:base `<select>`

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#10908]
In [this issue](https://github.com/w3c/csswg-drafts/issues/10857), I proposed putting `option::before` in the UA stylesheet to create checkmarks and `select::after` to create a dropdown icon.

It was suggested that we could create new pseudo-elements for these instead like `::check` and `::select-arrow`.

I used ::before and ::after because it was simpler than creating new pseudo-elements. If we do create new pseudo-elements, then we need to at least make sure that its easy for authors to completely disable their rendering - which can be done with the ::before/::after solution by putting display:none on them.

(not sure if css-ui is the right spec for this, but maybe that depends on what solution we choose)

**Comment by josepharhar** [comment]
Using ::marker was also mentioned, but I imagine it would make things harder since it has logic tied to list item rendernig that I imagine could be hard to work around.

**Comment by josepharhar** [comment]
Some things I'd like to resolve on, in this order:
1. Should we create new pseudo-elements for the dropdown icon and checkmark? Presumably they would be different.
2. What would their behavior be? Can it be exactly the same as ::before and ::after, or at least have an easy opt-out for authors wanting to remove the checkmark next to options?
3. What should their names be?

**Comment by josepharhar** [comment]
From an implementation point of view, I would prefer to make these like ::before and ::after because I want the content property to work on them, and if it has a backing element in the UA shadowroot then I don't think I can easily make the content property work on them easily due to the current state of chromium.

I don't know whether that means they should be "part-like" or not, but I at least want to think of them as being "before-like"

**Comment by josepharhar** [comment]
I created a PR to define them as ::check and ::select-arrow here: https://github.com/w3c/csswg-drafts/pull/10986

I copied the functionality of ::before/::after and made them part-like pseudo-elements.

**Comment by yisibl** [comment]
Maybe we should consider using the same model as `::select-arrow` for the `::marker` in the details element. This would avoid many of the limitations of `::marker`.

**Comment by josepharhar** [comment]
> I copied the functionality of ::before/::after and made them part-like pseudo-elements.

In the PR, I changed them from part-like pseudo-elements to tree-abiding pseudo-elements which accept all properties.

**Comment by josepharhar** [comment]
Proposed resolution: Add tree-abiding pseudo-elements which accept all properties called `::check` and `::select-arrow` for the option checkmark and select drop-down icon

**Comment by josepharhar** [comment]
Not sure where the IRC notes went, but this was in them:

> ACTION: jarhar to open an issue to determine if pseudo elements (yet to be named) are tree-like or element-like

I think they should be "tree-like" according to this sentence.

It sounded like there was an issue raised about the CSS spec itself not being well defined enough for us to add a pseudo-element for this, and that we should be consistent between the new pseudo-elements we are adding like ::picker and this thing.

I think that ::picker should be "part-like" or "element-backed" because it is a real element in the UA shadowroot which has a popover attribute and a slot inside it to slot child nodes of the select into.

These new elements are intended to replace the ::before and ::after rules I proposed, and all they do is render what we want to put in the content property, so they should not be part-like or element-backed.

I don't understand the concern that these aren't defined well enough. ::picker is an [element-backed pseudo-element](https://drafts.csswg.org/css-forms-1/#picker-pseudo). Is this not well defined?

These new pseudo-elements should be "fully stylable pseudo-elements", [just like ::before and ::after](https://drafts.csswg.org/css-pseudo/#generated-content). This also seems very well defined to me.

**Comment by josepharhar** [comment]
Here is the IRC from the last meeting: https://logs.csswg.org/irc.w3.org/css/2024-10-24/ (thanks for scribing @gregwhitworth!)

We had these resolutions:

> RESOLVED: add pseudo-elements for the select button and option checkmarks which are fully stylable pseudo-elements with content specified by the content property

> RESOLVED: Adopt ::check or ::checkmark for checkbox/radio checks

We still need to choose between ::check or ::checkmark, and we still need to choose a name for the in-page button icon part.

I think that ::checkmark is easier to understand than ::check, so I propose we use ::checkmark.

Some names proposed for the dropdown icon after the in-page button part:
- `::select-arrow`
- `::select-activator`
- `::select-opener`
- `::field-button-open`
- `::open-button`
- `::button-icon`
- `::select-toggle`
- `::select-indicator`
- `::select-icon`
- `::field-popup-icon`
- `::field-open-icon`
- `::field-open-button`
- `::picker-icon`
- `::picker-button`
- `::picker-invoker`
- `::picker-opener`
- `::picker-toggle`
- `::picker-trigger`

We also had a poll for the names which start with ::picker, and here is the results:

1. ::picker-icon 3 votes
1. ::picker-button 3 votes
2. ::picker-opener 2 votes
3. ::picker-trigger 1 vote
4. ::picker-toggle 0 votes
4. ::picker-invoker 0 votes

@nt1m also said that having "picker" in the name means that it's inside the picker.

In my opinion, ::picker-icon is best because the other options like ::picker-button imply that this pseudo-element is the button, but it actually isn't - its just some decoration put inside the button which opens the picker. I also think that it's OK that this has picker in its name despite being outside of the picker. It is relevant because it's an icon which indicates that this button will open a picker.

Proposed resolution: Adopt ::checkmark and ::picker-icon as the names of the pseudo-elements for the option's checkmark and the select's in-page button icon.

**Comment by fantasai** [comment]
I agree with picking a generic name for the picker icon thing. For authors it will be much easier to learn and to style if the pseudo-elements representing this concept share the same name across form controls.
