### ISSUE TITLE
[css-inline] Is `text-box-edge` inherited or not?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#10904]
Recently, the `text-box-edge` property was changed to a non-inherited property in the [spec](https://drafts.csswg.org/css-inline-3/#text-box-edge) and [tests](https://github.com/web-platform-tests/wpt/commit/d85c6acff29191d2cefb65abd2cb3aa8c59b4ca0).

IIUC, the original motivation to split the feature into two properties (`text-box-trim` and `text-box-edge`) was to make the former non-inherited while the latter inherited, so that i18n authors can set the default edges to all descendants depending on their scripts, but now this doesn't seem possible.

If we don't need the use case and both properties are non-inherited, can we merge the two properties back to one property?

I re-read #10675 but I couldn't read this point very well. Can we discuss this point?

@fantasai @nt1m @vitorroriz @Clqsin45 @bfgeek @chrishtr @jfkthame @kidayasuo

**Comment by fantasai** [comment]
The reason I didn't make `text-box-edge` inherited was to allow it to be an override that doesn't affect the content inside. For example if you want to trim a sidebar's top and bottom to a particular edge, but not affect how things inside it trim themselves. The `line-fit-edge` property inherits, so it can set a good default.

But I'm not 100% sure about this interaction, so I agree it's good to discuss it.

**Comment by fantasai** [comment]
Chatted with @jensimmons yesterday; her intuition is the same as yours, @kojiishi, that `text-box-edge` should be inherited.

**Comment by fantasai** [comment]
For clarity, the proposal adopted was: Switch `text-box-edge` to be inherited. `text-box-trim` remains non-inherited. Trimming uses the `text-box-edge` of the line box's containing block; or if trimming an inline box, the `text-box-edge` of the box itself.
