### ISSUE TITLE
[cssom-view] Window#screenLeft/screenTop

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#1091]
https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface

`screenX` and `screenY` are in the spec, but not `screenLeft` or `screenTop`.

These two attributes are in Chromium, EdgeHTML and WebKit, but not Gecko, as tested with:
https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4927

Use counters:
https://www.chromestatus.com/metrics/feature/timeline/popularity/697
https://www.chromestatus.com/metrics/feature/timeline/popularity/698

Risk of removal is hard to judge, but given three implementations standardization should be the default choice.

In Chromium and WebKit, they are simply aliases of `screenX` and `screenY`:
https://chromium.googlesource.com/chromium/src/+/706a26bfd8ee3677c8b59fc1a6859276ab7686c7/third_party/WebKit/Source/core/frame/LocalDOMWindow.h#139
https://trac.webkit.org/browser/trunk/Source/WebCore/page/DOMWindow.h?rev=211654#L170

@zcorpan

**Comment by foolip** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=695572 had been closed as WontFix, i.e., this won't be removed from Chromium because the usage is too high. @tabatkins, can you send a spec change for this, or find someone who can?

**Comment by foolip** [comment]
(It is still the case that this is missing in Gecko only. @emilio may be interested to know this.)

**Comment by emilio** [comment]
Thanks for the heads-up :)

**Comment by emilio** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1498860 to keep track of this.

Looks like there's a spec change ready in #2669, just no editor for the spec... :)
