### ISSUE TITLE
 [css-sizing] aspect-ratio missing combined value definition

### ISSUE THREAD

**Issue by Eccenux** [w3c/csswg-drafts#10933]
[CSS Box Sizing Module Level 4, 20 May 2021](https://www.w3.org/TR/2021/WD-css-sizing-4-20210520/#propdef-aspect-ratio)

There is an error in value. Is:
> `auto || <ratio>`

Should be:
> `auto || <ratio> || auto <ratio>`

The later being mentioned later in the spec:
https://www.w3.org/TR/2021/WD-css-sizing-4-20210520/#valdef-aspect-ratio-auto--ratio

Related issue:  #10906

**Comment by Loirooriol** [comment]
`||` allows combinations, see https://www.w3.org/TR/css-values-4/#comb-any
