### ISSUE TITLE
[css-cascade-5] `revert-layer` in element-attached styles

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#10934]
As per https://drafts.csswg.org/css-cascade-5/#revert-layer, `revert-layer` in _important_ element-attached styles should revert back to the author origin:

> For `revert-layer` in important element-attached styles, however, it only reverts the element-attached styles and the intervening animation origin, and not any of the intervening author-origin important rules.

https://wpt.live/css/css-cascade/revert-layer-009.html however seems to imply this is also the case for _regular_ element-attached styles, with [all vendors agreeing on this behavior](https://wpt.fyi/results/css/css-cascade/revert-layer-009.html?label=experimental&label=master&aligned).

Suggestion to update the spec to the following, dropping the word “important”:

> For `revert-layer` in element-attached styles, however, it only reverts the element-attached styles and the intervening animation origin, and not any of the intervening author-origin important rules.

**Comment by mirisuzanne** [comment]
@bramus Both revert to styles within the author origin. That note is specifically about how to deal with intervening _important_ rules. In the example you linked -- and always when the inline styles are not marked as important -- there are no intervening important rules: 

```txt
- !important UA origin
- !important User origin
- !important Element attached (reverting from here…) ⏪
- !important Lowest Layer (…maintains these layers)
- !important Highest Layer (…)
- !important No Layer (…)
- Animation origin (…but would revert this one) ❌
- Element attached (the linked WP test starts here…)
- No Layer (…and ends up here, which is also correct)
- Highest Layer
- Lowest Layer
- Presentation hints
- User origin
- UA origin
```

**Comment by bramus** [comment]
Very helpful comment. Thanks for clarifying.
