### ISSUE TITLE
[css-mediaqueries] posible error on Example 25

### ISSUE THREAD

**Issue by andresgalante** [w3c/csswg-drafts#1094]
On [Media Queries Level 4 under `width`](https://www.w3.org/TR/mediaqueries-4/#width) the example 25 shows a range with a `min-width`:

`@media (400px <= min-width <= 700px) { … }`

Maybe I am not understanding the spec correctly, but it seems strange to have a range with a `min-width`. Shouldn't that be just `width`? If that's the case I am happy to send a PR.

Thanks a lot!

**Comment by frivoal** [comment]
This is indeed an error, and has now been fixed in the [Editor's Draft](https://drafts.csswg.org/mediaqueries/#width). Thanks for the report.
