### ISSUE TITLE
[css-mixins-1] how do `@function` rules cross shadow boundaries?

### ISSUE THREAD

**Issue by keithamus** [w3c/csswg-drafts#10953]
The `@function` rule defines a custom function to be referred to in other style rules. It needs to be defined how the ident will cross shadow boundaries. Will it be available? Can vended shadow styles clobber?

My recommendation is that they should be available but a shadowroot should be able to clobber within its own scope, and functions defined in a shadow root should not leak into the global styles, if at all possible.

**Comment by tabatkins** [comment]
Yeah, that's the behavior you'd get from the standard "tree-scoped name" and "tree-scoped reference" behavior - you can define things at any scope, and they're visible to things in the same scope *or nested scopes*, but not higher. I suspect it's all we want.

**Comment by mirisuzanne** [comment]
Can this be closed as question answered, or do we need more discussion on this?

**Comment by keithamus** [comment]
Yep, let's close it as I believe it's answered.
