### ISSUE TITLE
[css-view-transitions-2] Clarifications around `view-transition-group`

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#10957]
We recently resolved on `view-transition-group`, but a few things remained unresolved:
- tree scoping: assuming that the `nearest` keyword and others are tree scoped like names. Verifying. (#10633)
- mismatch: what happens when the old/new `view-transition-group` are not the same? (#10631).
- Does `nearest` and `<<custom-ident>>` implicitly also mean `contain`? (#10780)

Proposing:
- `view-transition-group` semantics are tree-scoped
- `view-transition-group` acts like `view-transition-class` in a mismatch (last capture wins)
- `nearest` and `<<custom-ident>>` implicitly also main `contain`

**Comment by fantasai** [comment]
For the last one, I think that was already resolved (by adopting [the proposal as expressed in the issue](https://github.com/w3c/csswg-drafts/issues/10334) prior to the resolution).

**Comment by astearns** [comment]
working on the individual issues instead
