### ISSUE TITLE
[css-support]Add in @support ' else '

### ISSUE THREAD

**Issue by gogas** [w3c/csswg-drafts#1096]
[@suppurt](https://drafts.csswg.org/css-conditional/#at-supports)

The specification says that we can test to support the property of the browser like
`@supports (animation-name: test) { }`
or test for the non-support of a specific CSS property
`@supports not ( hanging-punctuation: first ){`
But why not reduce this code to `if (){} else {}` аs in other programming languages like:
`@supports (filter: grayscale(100%)) {`
   ` img {`
        `filter: grayscale(100%)`
    `}`
`} else {`
    `img {`
        `background-image: url("/image.png");`
    `}`
`}`

**Comment by SebastianZ** [comment]
This is already discussed in #112.

Sebastian
