### ISSUE TITLE
[css-display][css-cascade] Should `display: contents` affect inheritance?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1098]
[`display: contents`](https://drafts.csswg.org/css-display/#valdef-display-contents) replaces an element by its children, so I wonder if the children should still [inherit](https://drafts.csswg.org/css-cascade-4/#inheriting) from that element.

I think it would make more sense if they didn't (except maybe for the `display` property itself?). But on Firefox and Chrome, the inheritance is not affected.

Example (https://jsfiddle.net/xyeL8ewr/):

```html
<div>
  <p>
    <span>Foo</span>
  </p>
  <span>Bar</span>
</div>
```
```css
div {
  color: blue;
}
p {
  display: contents;
  color: red;
}
```

"Foo" is red and "Bar" is blue. But with `display: contents`, it's like if the markup was

```html
<div>
  <span>Foo</span>
  <span>Bar</span>
</div>
```

so maybe both should be blue.

**Comment by SelenIT** [comment]
The spec also has the following statements:

> Note: As only the box tree is affected, any semantics based on the document tree, such as _selector-matching_ and event handling, are not affected.

and
> Markup-based relationships, however, are not affected by these values, as they are solely rendering-time effects.

As the CSS Cascade spec [states](https://drafts.csswg.org/css-cascade/#inheriting),
> Inheritance propagates property values from _parent elements_ to their children. The inherited value of a property on an element is the computed value of the property on the element’s _parent element._

the CSS inheritance concept is also based on the document tree, not the box tree, and shouldn't be affected by any display changes.

I believe that inheriting properties from the "virtual" container that is not directly affected by them may make much sense. For example, inheriting table-specific properties like `border-spacing` from a non-table container like `div` is very useful for styling tables in the user-generated content. In my opinion, inheriting from non-rendered containers may have similar use cases, so neither the spec nor the behavior of browsers needs change.

**Comment by Loirooriol** [comment]
But note inheritance is not always a document tree concept. From [CSS display](https://www.w3.org/TR/css-display-3/#intro),

> Unlike element-generated boxes, whose styles inherit strictly through the element tree, anonymous boxes (which only exist in the box tree) inherit through their box tree parentage.

And some pseudo-elements like [`::first-line`](https://www.w3.org/TR/css-pseudo-4/#first-line-inheritance) have a customized inheritance which doesn't respect the element tree.

Anyways, you are right there might also be some advantage in inheriting from non-rendered containers, and with at least two implementations and a near-CR spec, maybe it's not worth to change.

**Comment by tabatkins** [comment]
No, inheritance is definitely not affected by `display:contents`, and that's very intentional. Inheritance always runs thru the element tree, except for the one case it can't (anonymous boxes).  Pseudo-elements inherit from their originating element.

(Otherwise, how would `display: inherit` work?)

**Comment by upsuper** [comment]
> Pseudo-elements inherit from their originating element.

This isn't necessarily true... e.g. [`:backdrop`](https://fullscreen.spec.whatwg.org/#%3A%3Abackdrop-pseudo-element) defined in the Fullscreen API spec doesn't inherit from anything per that spec.

If you think that is wrong... probably an issue should be filed to that spec.
