### ISSUE TITLE
[css-values-5] Special case equal progress/start/end values in progress functions?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#10980]
Per [spec](https://drafts.csswg.org/css-values-5/#progress-func), the result of `progress(1 from 1 to 1)` is `NaN`, which *might be* censored to `0` at the top-level of a calculation tree (#10979).

This case is very unlikely, but I wonder if it should not also resolve to `0` when it is used in another calculation, rather than infecting it with NaN.

**Comment by tabatkins** [comment]
Ah yeah, this should be special-cased. It being a divide-by-zero is just an accident.
