### ISSUE TITLE
[css-color-5] Is relative colors "omitted alpha" rule useful?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#10991]
https://drafts.csswg.org/css-color-5/#rcs-intro says:

> If the alpha value of the relative color is omitted, it defaults to that of the [origin color](https://drafts.csswg.org/css-color-5/#origin-color) (rather than defaulting to 100%, as it does in the absolute syntax).

That was a bit unexpected to me, and feels it could be for authors as well. Given authors can just type an extra `alpha` on the color, is it really worth the confusion?

cc @svgeesus @weinig

**Comment by svgeesus** [comment]
@LeaVerou

**Comment by LeaVerou** [comment]
Completely agreed, no idea what I was thinking when I wrote that — if I did write that — it’s not part of my [original proposal](https://github.com/w3c/csswg-drafts/issues/3187#issuecomment-499126198); @tabatkins [proposed it later](https://github.com/w3c/csswg-drafts/issues/3187#issuecomment-426458180) though that was in the context of omitting _any_ value, which was still on the table. Looking at [commits](https://github.com/w3c/csswg-drafts/commit/828ac92bbd1a985f16877921e493c52d7094f5d6) it appears that it was you @svgeesus that introduced it?

So I suspect we'll have consensus to remove the rule, the tricky part now is web compat…

**Comment by romainmenke** [comment]
There is interop for the current specification and this behavior is well documented: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_colors/Relative_colors#:~:text=Optionally%2C%20an%20alpha%20channel%20value%20for%20the%20output%20color%20can%20be%20defined%2C%20preceded%20by%20a%20slash%20(/).%20If%20the%20alpha%20channel%20value%20is%20not%20explicitly%20specified%2C%20it%20defaults%20to%20the%20alpha%20channel%20value%20of%20the%20origin%2Dcolor%20(not%20100%25%2C%20which%20is%20the%20case%20for%20absolute%20color%20values).

There also is no way to do feature detection for such a change.

Authors could always write an explicit alpha component even for `100%` during the transition period. Would take a long time, but relatively speaking, still a short term pain point.

**Comment by svgeesus** [comment]
I also feel that the current omitted-alpha  behavior is the most useful one. Avoiding having to type ` / alpha` is better than having to type ` / 1`.

**Comment by emilio** [comment]
To be clear, I don't have a too strong feeling one way or the other. I did find it confusing as an author, and when reviewing code to implement it. But I guess I could see it being useful? It's just a bit "too magic" for my taste. If you accidentally find this behavior and don't want it, it's not super-clear that you need `/ 1` (where that's the default everywhere else).

**Comment by LeaVerou** [comment]
Ok, after reading @tabatkins’s comment, I'm also convinced it’s a good idea 😁

**Comment by kbabbitt** [comment]
+1 for preserving origin alpha. The way I think about it is: in relative color syntax, the author is starting with an origin color and then specifying modifications to it. If they don't say anything about a particular aspect of the origin color, it should be left untouched.

**Comment by svgeesus** [comment]
So, @emilio can we close this?

**Comment by emilio** [comment]
Sure, sounds fine :)
