### ISSUE TITLE
Auto Keyword value type of size Intrinsic vs Extrinsic.

### ISSUE THREAD

**Issue by tomasts248** [w3c/csswg-drafts#11009]
Hi,
I'm not sure about the following:  Is the keyword value auto for Width property, an Extrinsic type of size? while the value "auto" for height would be an Intrinsic type of size? 
Thanks

**Comment by Loirooriol** [comment]
`width: auto` is an [automatic size](https://drafts.csswg.org/css-sizing-3/#automatic-size), which can have various different behaviors, e.g.

 - For non-replaced in-flow blocks with `justify-self: normal` in an horizontal writing mode, it behaves like `stretch` so it's extrinsic.
 - For floats it behaves as `fit-content` instead, i.e. like `stretch` but clamped between `min-content` and `max-content`, so mostly intrinsic I would say.

`height: auto` is also an automatic size, but the rules for automatic sizes tend to be different on the inline and the block axes.

**Comment by tomasts248** [comment]
OK I'm trying to fully understand this: if there's no replaced value with display and not being used by a non normal flow (such as flexbox or grid), then it would be correct to state that width auto is extrinsic type of size, and height auto an intrinsic type? because in width auto depends on the CSS Box Model, and the other on the height of its children.

**Comment by fantasai** [comment]
@tomasts248 Yes, exactly: if a block box is not replaced (and we're in horizontal writing mode), `width: auto` is extrinsic and `height: auto` is intrinsic. However if a block-level box is replaced, or is e.g. a table, then `width: auto` is intrinsic.

**Comment by tomasts248** [comment]
> @tomasts248 Yes, exactly: if a block box is not replaced (and we're in horizontal writing mode), `width: auto` is extrinsic and `height: auto` is intrinsic. However if a block-level box is replaced, or is e.g. a table, then `width: auto` is intrinsic.

Thank you so much!!! Understood!! :+1:
