### ISSUE TITLE
[cssom] [css-overflow-3] Behaviour of getPropertyValue() unclear when the result doesn't match the property grammar

### ISSUE THREAD

**Issue by darrnshn** [w3c/csswg-drafts#1100]
In [getPropertyValue()](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue), for shorthand properties, it says to simply append the value of the CSS declaration of each longhand. However, this might result in something that doesn't conform to the grammar of the shorthand property. For example, the [overflow](https://drafts.csswg.org/css-overflow-3/#propdef-overflow) shorthand only accepts 1 keyword, but `getPropertyValue()` would return a list containing the value for `overflow-x` and `overflow-y`. What should be the correct behaviour of getPropertyValue() in these cases?

**Comment by zcorpan** [comment]
It doesn't say to append the *value* of the longhand, it says to append the longhand itself. And then serialize the list of longhands using https://drafts.csswg.org/cssom/#serialize-a-css-value which says

> Return the result of joining values as appropriate according to the grammar of shorthand and terminate these steps.

That's certainly hand-waving and there may be bugs in the spec's algorithm... but the intent is to serialize something that follows the grammar for the shorthand.

But also see https://github.com/w3c/csswg-drafts/issues/1033

**Comment by darrnshn** [comment]
I see, thanks!
