### ISSUE TITLE
[css-conditional-5] comma-separated container query aren't supported on browsers

### ISSUE THREAD

**Issue by Monknow** [w3c/csswg-drafts#11015]
According to [the spec](https://www.w3.org/TR/css-conditional-5/#example-b320e2d0), it should be possible to query multiple containers with different conditions using a comma-separated list:

> Using a single comma-separated [container query](https://www.w3.org/TR/css-conditional-5/#container-query), we can query multiple containers:
> 
> ```css
> @container card (inline-size > 30em), style(--responsive: true) {
>   /* styles */
> }
> ```
>
>The styles above will apply for an element inside either a container named "card" that meets the [inline-size](https://www.w3.org/TR/css-conditional-5/#descdef-container-inline-size) condition, or a container meeting the [style](https://www.w3.org/TR/css-conditional-5/#container-style-query) condition. 

However, it doesn't seem to work on any browser: https://codepen.io/monknow/pen/BaXQjpm?editors=0110 In the demo, all texts should have a different underline color applied by a container query.

Is there any awareness of this? The spec and most third-party documentation say it should be possible, so just curious to know if it's a bug, a feature to be shipped soon, or a misunderstanding on my end.

Thanks :)

**Comment by Loirooriol** [comment]
Browsers have so many features to work on. Sometimes it may take a long time until they implement something. Note we resolved to add the comma syntax at the end of last year (https://github.com/w3c/csswg-drafts/issues/7551#issuecomment-1854385652), very recent, in comparison there are features that are like 20 years old and still not implemented everywhere.

Some things that you may do: make sure there is an issue about implementing the missing feature in tracker of the browsers that lack it, write blog posts or tweets or whatever that will make people want the feature and vote/star the relevant issue (which might help prioritize it), implement the feature yourself, or pay some company to implement it for you.

**Comment by Loirooriol** [comment]
FYI this is part of the "Container Queries" focus area proposal for interop-2025: https://github.com/web-platform-tests/interop/issues/836
If it gets selected, it's likely that this will be implemented on major browsers during 2025.
