### ISSUE TITLE
[css-anchor-position] "painted strictly before" for acceptable anchor is not the correct term

### ISSUE THREAD

**Issue by jwatt** [w3c/csswg-drafts#11029]
In the [acceptable anchor element](https://drafts.csswg.org/css-anchor-position-1/#acceptable-anchor-element) section, one of the conditions for being an acceptable anchor is:

> `possible anchor` is painted strictly before `positioned el`, ...

Characterising the rules listed under this requirement as "painted strictly before" seems incorrect. Those rules seem to be about what we really require, which is that `possible anchor` is laid out before the positioned element, but the order in which elements are laid out and the order in which they are painted is not necessarily the same (b/c stacking context rules). So the latter term can't be used interchangeably as a proxy for the former.

In [this example from #10419](https://codepen.io/David-Choi-the-reactor/pen/WNBomzM), the fixed pos element is painted **before** the "anchee" element, but "anchee" still can't anchor to it because the order of reflow is the opposite ("anchee" reflows before the fixed pos element).

Can "painted strictly before" in the spec text be replaced with "laid out before"?

**Comment by emilio** [comment]
Yeah, I agree this is about layout order, not paint order. There's nothing (afaict) that prevents you from putting the anchored element behind the anchor or vice versa e.g. via z-index.

**Comment by tabatkins** [comment]
Yup, makes sense. Tweaked to "laid out strictly before".
