### ISSUE TITLE
[css-overflow] Invisible line boxes and `line-clamp`

### ISSUE THREAD

**Issue by andreubotella** [w3c/csswg-drafts#11021]
While talking with @kojiishi earlier today, we noticed that the spec text for `block-ellipsis` and `max-lines` (which are shorthands of `line-clamp`) talks about line boxes in general, without explicitly excluding [invisible line boxes](https://drafts.csswg.org/css-inline-3/#invisible-line-boxes). But currently every browser ignores invisible line boxes for `(-webkit-)line-clamp`, clamping at "Line 4" in this example:

```html
<style>
  .clamp {
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 4;
    overflow: hidden;
  }
</style>
<div class="clamp">
  <div>
    Line 1 <br>
    Line 2 <br>
    Line 3
  </div>
  <div><span></span></div> <!-- Invisible line box! -->
  <div>
    Line 4 <br>
    Line 5
  </div>
</div>
```

Aside from this, there's the question of how to take into account invisible line boxes when clamping based on a height. With `continue: discard` it is possible for an invisible line box to be "immediately preceding a region break" (see also #10868), which per the spec means it should be ellipsized. However, it would be very unexpected to have an ellipsis placed there. With `continue: discard`, I think the previous line box, if there is one, should have the ellipsis.

For `continue: collapse`, in TPAC we agreed that this variant of `line-clamp` would only allow clamping immediately after a line box, whereas `continue: discard` could clamp between lineless blocks (see https://github.com/w3c/csswg-drafts/pull/10816#issuecomment-2392514493). This should be changed to only allow clamping immediately after a _visible_ line box.

cc @frivoal @emilio

**Comment by frivoal** [comment]
I'd say there's two parts:
* I agree that invisible line boxes should not be counted when you're counting lines to find what the clamp point is.
* if, when clamping by height, you end up with invisible line boxes after the last visible one, what happens to them is part of issue https://github.com/w3c/csswg-drafts/issues/10868, so we don't have to handle it separately here.

**Comment by frivoal** [comment]
Well, maybe a third part:
* the ellipsis can only get added to the last visible line, regardless of whether #10868 allows invisible lines to exist after the last visible one in some cases (height-based `continue: discard`)

**Comment by fantasai** [comment]
The spec for invisible line boxes says:

> Such boxes must be treated as zero-height line boxes for the purposes of determining the positions of any descendant content (such as absolutely positioned boxes), and **both the line box and its in-flow content must be treated as not existing for any other layout or rendering purpose.**

We don't want to mention invisible line boxes everywhere we mention line boxes. That would make the spec unreadable. They are effectively `display: none` except as mentioned in this specific paragraph: they do not exist for any other purpose. You cannot count them. You cannot measure them. You cannot introspect their content. They just don't exist.
