### ISSUE TITLE
[css-pseudo] Add boundary element and line break element selector.

### ISSUE THREAD

**Issue by JF98** [w3c/csswg-drafts#11020]
The following English text comes from machine translation and may not be accurate:

`:top-child` is used to select the closest child element to the top of the parent container.
`:right-child` is used to select the closest child element to the right side of the parent container.
`:bottom-child` is used to select the closest child element to the bottom of the parent container.
`:left-child` is used to select the closest child element to the left side of the parent container.

`:wrap-child` selects child elements that are in a wrapped position within the container（"sub-elements arranged in a non-first row）.

If `:top-child` is implemented, then :wrap-child may not need to be added, but can instead be achieved using the following method:
```
.parent > :not(:top-child) {
  /* style */
}
```
We also need you to confirm whether the above suggestions are limited to child elements within the document flow.

**Comment by JoshTumath** [comment]
Do you have a use case for these suggested pseudo-classes?

**Comment by fantasai** [comment]
In general we don't add pseudo-classes that depend on layout, since this can be cyclic.
