### ISSUE TITLE
[css-fonts-4] [color fonts] How to choose predefined palette with font-palette

### ISSUE THREAD

**Issue by RoelN** [w3c/csswg-drafts#1103]
In [Controlling Color Font Palettes: The font-palette property](https://drafts.csswg.org/css-fonts-4/#font-palette-prop) you can choose the default/best-fit palette ("normal"), one for dark or light backgrounds ("light", "dark") and palettes defined by the user through the `@font-palette-values` rule. But if a font comes with multiple predefined palettes, how do I choose one of these without having to create a user defined palette (the only place I see where you can choose one with `base-palette`)?

**Comment by litherum** [comment]
You create a `@font-palette-values` rule with a `base-palette` descriptor and no overriding `<integer>` descriptors. That way, your new rule will inherit all colors from the base palette.

**Comment by litherum** [comment]
The reason why it's important that you create an `@font-palette-values` rule is for font fallback. You don't want to specify the `base-palette` number on an element itself because the number will likely be different for each font in the `font-family` list. Instead, you want to create an `@font-palette-values` rule for each item in the `font-family` list, and each rule will specify the appropriate value for that specific font file.

**Comment by litherum** [comment]
See https://drafts.csswg.org/css-fonts-4/#example-af16bafd

**Comment by RoelN** [comment]
Let's see if I got this straight. I'm want to use two color fonts in a greenish palette. The first font, Bixxxa, already has palette that I can use, but for Bungeehee I need to overwrite one color to get my green palette.

```
@font-face {
    font-family: Bixxxa;
    src: url('./bixxxa.woff') format('woff');
}

@font-face {
    font-family: Bungeehee;
    src: url('./bungeehee.woff') format('woff');
}

@font-palette-values ToxicGreen {
  font-family: Bixxxa;
  base-palette: 3; /* This is Bixxxa's green palette */
}


@font-palette-values ToxicGreen {
  font-family: Bungeehee;
  base-palette: 7; /* This is Bungeehee's green palette... */
  2: lime; /* ...except this is pink, which I overwrite to lime */
}

h1 {
    font-family: Bixxxa;
    font-palette: ToxicGreen;
}

h2 {
    font-family: Bungeehee;
    font-palette: ToxicGreen;
}
```

**Comment by litherum** [comment]
Yep!

You could also say
```css
h3 {
    font-family: Bixxxa, Bungeehee;
    font-palette: ToxicGreen;
}
```

and the ToxicGreen palette would be applied correctly to both fonts in `<h3>`, no matter if the glyphs which get rendered are from Bixxxa or Bungeehee.

**Comment by svgeesus** [comment]
That would be a great worked example for the spec. And it could use those fonts as an example image, too!
