### ISSUE TITLE
[css-view-transitions] Broken state management in "capture the old state"

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#11058]
https://drafts.csswg.org/css-view-transitions-1/#capture-old-state-algorithm has:

> For each element of every element that is connected, and has a node document equal to document, in paint order:
> [...]
> * If usedTransitionNames [contains](https://infra.spec.whatwg.org/#list-contain) transitionName, then return failure.
> [...]
> * Set element's "captured in a view transition" to true.
> * Append element to captureElements.

Note in particular that, if we take the failure path, any previous `element` that has the "captured in a view transition" bit to true doesn't end up in `namedElements`, which means that that bit isn't cleaned-up at all afterwards. That seems wrong? cc @khushalsagar @noamr

**Comment by emilio** [comment]
I think we need to run the:

> For each element in captureElements:
> * Set element’s captured in a view transition to false.

Always before returning.

**Comment by noamr** [comment]
I don't follow. What is the "failure path" in "capture the old state"?

**Comment by emilio** [comment]
The "then return failure"? E.g. consider we visit:

```
<div id="a" style="view-transition-name: --foo"></div>
<div id="b" style="view-transition-name: --foo"></div>
```

We visit `#a`, set a's "captured in a view transition" to true.

Then we visit `#b`, and realize it's a duplicate name, and return failure. `#a` still has "captured in a view transition" set and nothing cleans it up.

**Comment by noamr** [comment]
> The "then return failure"? E.g. consider we visit:

In that case, failure is returned, and the [caller](https://drafts.csswg.org/css-view-transitions-1/#setup-view-transition-algorithm) will skip the view transition, which would also clear the flag [here](https://drafts.csswg.org/css-view-transitions-1/#clear-view-transition).

**Comment by emilio** [comment]
@noamr how? `#a` is not in `namedElements` (also it wouldn't be a new element anyways, even if it returned success)

**Comment by noamr** [comment]
Oh I see, you're right @emilio. Care to PR a fix for this? If not I can get to it soonish.

**Comment by emilio** [comment]
I can try. cc @nt1m (WebKit has this bug, leaving the captured flag set here)
