### ISSUE TITLE
[css-view-transitions] Skip on activation doesn't provide a reason

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#11059]
https://drafts.csswg.org/css-view-transitions-1/#activate-view-transition:

> If transition’s [initial snapshot containing block size](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-initial-snapshot-containing-block-size) is not equal to the [snapshot containing block size](https://drafts.csswg.org/css-view-transitions-1/#snapshot-containing-block-size), then [skip the view transition](https://drafts.csswg.org/css-view-transitions-1/#skip-the-view-transition) for transition, and return.

Skip the transition with what exception or reason? Presumably with an AbortError? Or something else?

cc @noamr

**Comment by nt1m** [comment]
I used `InvalidStateError` like the rest of the algorithm:

> [Capture the new state](https://drafts.csswg.org/css-view-transitions-1/#capture-the-new-state) for transition.
> If failure is returned, then [skip the view transition](https://drafts.csswg.org/css-view-transitions-1/#skip-the-view-transition) for transition with an "[InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) in transition’s [relevant Realm](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-realm), and return.


But yeah we should definitely fix that being unspecified.
