### ISSUE TITLE
[css-view-transitions-2] Using 'was created via cross-origin redirects' Document creation state causes unexpected results

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#11063]
If you navigate into a site via a cross-origin redirect, then the 'was created via cross-origin redirects' bit gets set on the Document.

If you then navigate to a different page within the same site, the navigation is eligible for cross document view transition.

If you then navigate back to the original page, and this uses the BFCache, then this second navigation is not eligible, since the Document is still marked as having been created by a cross-origin redirect.

This seems unexpected to me, as the cross-origin redirect during navigation is unrelated to the current navigation.

**Comment by nt1m** [comment]
cc @noamr @khushalsagar @vmpstr

**Comment by noamr** [comment]
> If you navigate into a site via a cross-origin redirect, then the 'was created via cross-origin redirects' bit gets set on the Document.
> 
> If you then navigate to a different page within the same site, the navigation is eligible for cross document view transition.
> 
> If you then navigate back to the original page, and this uses the BFCache, then this second navigation is not eligible, since the Document is still marked as having been created by a cross-origin redirect.
> 
> This seems unexpected to me, as the cross-origin redirect during navigation is unrelated to the current navigation.

Right, I think we should swap (5) and (6) - this flag should only matter for `navigate` navigations (not `traverse`).
