### ISSUE TITLE
[css-view-transitions-2] when copying css properties for layered capture, resolve lengths to a fixed value

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#11077]
it wouldn't make sense to copy over `padding: 10%` to the `view-transition-group` since the relative lengths are derived from different containing blocks.

@noamr

**Comment by noamr** [comment]
but computed values already include resolved length/percentage into pixels... So I think we're good?

**Comment by khushalsagar** [comment]
Yes, that makes sense!
