### ISSUE TITLE
[css-view-transition] "capture the new state" and "capture the old state" are subtly different.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#11071]
In particular, "capture the new state" doesn't have the condition for:

> If element has more than one [box fragment](https://drafts.csswg.org/css-break-4/#box-fragment), then [continue](https://infra.spec.whatwg.org/#iteration-continue).

Is that intentional? If so it might be worth calling that out explicitly (not sure why that would be?).

cc @noamr @nt1m

**Comment by nt1m** [comment]
I think it is intentional, the "update pseudo-element styles" algorithm, which is ran on every frame and right after "capture new state", would skip the view transition anyway in this case:

https://drafts.csswg.org/css-view-transitions-1/#update-pseudo-element-styles

> Return failure if any of the following conditions is true:
> * capturedElement’s [new element](https://www.w3.org/TR/css-view-transitions-1/#captured-element-new-element) has a [flat tree](https://drafts.csswg.org/css-scoping-1/#flat-tree) ancestor that [skips its contents](https://www.w3.org/TR/css-contain-2/#skips-its-contents).
> * capturedElement’s [new element](https://www.w3.org/TR/css-view-transitions-1/#captured-element-new-element) is [not rendered](https://www.w3.org/TR/css-images-4/#element-not-rendered).
> * capturedElement has more than one [box fragment](https://www.w3.org/TR/css-break-4/#box-fragment).


Fwiw, this check is mostly there as a technical limitation of engines, but in theory if browsers support snapshotting fragmented content, this check shouldn't be there. WebKit doesn't currently have this check (but mostly because there's no great way to reliably check for fragmented content).

**Comment by nt1m** [comment]
cc @khushalsagar @vmpstr who may have more context

**Comment by khushalsagar** [comment]
That is a bug. We should be skipping such elements in "capture the new state" same as "capture the old state".

The later check in https://drafts.csswg.org/css-view-transitions-1/#update-pseudo-element-styles to skip is if that state changes after the transition starts. We've already set up the pseudo-DOM, hard to reason about changing it, so we skip the transition if these invariants change. But when we're deciding on the names at the beginning, we err on ignoring names which don't satisfy these conditions instead.

**Comment by khushalsagar** [comment]
https://github.com/w3c/csswg-drafts/pull/11075 to fix this.

> Fwiw, this check is mostly there as a technical limitation of engines, but in theory if browsers support snapshotting fragmented content, this check shouldn't be there. 

There is context and notes on why we ended up ignoring fragmented elements here: https://github.com/w3c/csswg-drafts/issues/8339. TLDR, the way we set up transform on the group pseudo won't work if we generated a snapshot by unioning all the fragments.
