### ISSUE TITLE
[css-text-4] Japanese text (in #jp-title-break) in Example 24 is unreadable, with dark color-scheme

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#11099]
If you view https://drafts.csswg.org/css-text-4/#jp-title-break with a dark color-scheme-preference in your browser, the Japanese text in the example is barely readable (light-gray-on-white-background).

This is because that section sets `background` while letting the default `color` be inherited through; and if you do that, you end up with a light `color` in a dark-color-scheme.

Here's the relevant style rule in the markup for this page -- note that we're setting `background` but not setting `color`:
https://github.com/w3c/csswg-drafts/blob/8932d2ea030222255c555bbb8608460bf7e7a34a/css-text-4/Overview.bs#L6874-L6885

We perhaps want to add `color:black` or similar, just before `background:white`, so that we're not at the mercy of the inherited color-scheme-defined text-color here (which may or may not be hardcoded white background).

**Comment by dholbert** [comment]
(This is similar to https://github.com/speced/bikeshed/issues/2922 which is about `img` alt-text being unreadable due to a similar `background:white` rule that Bikeshed itself applies behind images.  Though in that bug, the unreadable alt-text eventually gets replaced with an image [assuming things work out properly], so it's a bit less noticeable.)

**Comment by dholbert** [comment]
Here's a screenshot of the first box within example 24, showing how this looks right now, when you view this page in a dark color-scheme (regardless of browser):
![image](https://github.com/user-attachments/assets/a426abfb-8474-47aa-9c58-e06150ca96ce)

**Comment by frivoal** [comment]
Thanks! fixed.
