### ISSUE TITLE
[flex] Sizing images with intrisic aspect-ratio: ¿harmonize with grids?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#1112]
In https://github.com/w3c/csswg-drafts/issues/523#issuecomment-282771617, @mrego mentioned that the change we proposed to Grid to enable images to shrink while maintaining their aspect ratio, but no to fill maintaining their aspect ratio created a potential difference between flex and grid.

Since I had absolutely no idea what flex was doing in that case, I wrote a few test cases and -- surprise! -- we are not interoperable :) The good news is that this means maybe we can try to match what we do in grid, but the bad news is that this means some of us have bugs to fix...

Here are the two test cases:

- [Flex with definite size whose size is smaller than the image it contains (stretch-as-in-shrink)
](https://jsfiddle.net/zcqst2pr/)
![image](https://cloud.githubusercontent.com/assets/364405/24014172/2857bc94-0a41-11e7-8286-2fee87259d45.png)

- [Flex with definite size whose size is bigger than the image it contains (stretch-as-in-grow)
](https://jsfiddle.net/zcqst2pr/1/ )
![image](https://cloud.githubusercontent.com/assets/364405/24014188/3594de1e-0a41-11e7-9d3f-13fd5f97fdea.png)

I had a quick discussion with @fantasai and she seemed to believe Edge is behaving the per-spec in this case. It would be a good idea to think about what we are doing here and maybe try to match this behavior in grid for the /normal/ alignment as much as it makes sense. 

Now that we have both "stretch" to force-stretch and "width:contain" to force-fit, I think it would make sense to try to get the default behaviors of grid and flex match where possible. 

The difference is that grids do not have a preferred axis like flex does, but maybe we could change grid to behave as-if in these cases (the preferred axis being deduced from the writing mode)? Or is there a way to make flexbox functioning more like what we said to do for grids in another way that would make more sense?

Thoughts?

cc @gregwhitworth @tabatkins @dbaron

**Comment by dbaron** [comment]
cc @matspalmgren @dholbert

**Comment by astearns** [comment]
On the call today we gave @FremyCompany an action to write bugs on the browsers that do not match the spec behavior. If fixing those bugs proves problematic, we can discuss how we can harmonize behavior in another way.

**Comment by FremyCompany** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=704294
https://bugzilla.mozilla.org/show_bug.cgi?id=1349738
https://bugs.webkit.org/show_bug.cgi?id=169974

**Comment by FremyCompany** [comment]
I think there are two reasonable behaviors here. 

Either the spec behavior (which Edge matches) or a modified spec behavior that prevents images from shrinking beyond their adjusted size in the flexible axis (adjustment being their cross-axis-height / natural-height * natural-width, instead of natural-width like the spec currently requires).

The advantage of the current spec text is that is does not create an exception for things that have an aspect ratio. 

The advantage of the adjusted spec text would be that images preserve their aspect ratio by default in flex.

**Comment by dholbert** [comment]
I posted some thoughts on the Mozilla bug that @FremyCompany filed. I agree that Edge's results are correct per spec here in all of the cases shown.

**Comment by FremyCompany** [comment]
Harmonization could happen both ways. Here is a plan that would harmonize grids with flex by mapping grid to flex:

- We keep flexbox unchanged (except maybe -- if the group thinks this is worth it -- the adjusted auto flex basis for elements with intrinsic aspect ratio)
- We change grid again to behave exactly like a flex with flex-direction:column (the image having flex: 0 0 auto, or flex: 0 1 auto if we adopt the previously-mentioned change to flex). That means "normal" means "stretch" in the width axis, and "start" in the height axis (if the element has an intrinsic aspect ratio which prevents natural stretching). 
- If you want things to work differently you either want "stretch" in both directions (which you can specify), or a manual "width: contain" which will take the available height and the aspect ratio into consideration when computing the width, and solve the issue for you. 

This means images would by default behave like any other element in a grid, their width is determined first, then their height is deduced given their assigned width. With the caveat images are likely to overflow though since the grid tracks would probably have been sized without considering this. The options mentioned before allow to solve that problem though. To an author this is highly predictable and quickly understandable.

Thoughts? @fantasai @tabatkins @mrego

**Comment by fantasai** [comment]
In general, we have tried to keep Grid’s sizing algorithms symmetric. So I've a preference to keep things as they were [resolved in 523](https://github.com/w3c/csswg-drafts/issues/523#issuecomment-288862103). Using the adjusted auto flex basis (the “transferred size” in the spec) in place of the intrinsic size makes sense, though. If it's a fix we can safely make, it might be worth doing.

**Comment by fantasai** [comment]
It would also resolve some confusion in Grid as well, I think.

**Comment by fantasai** [comment]
(My general feeling is that, from an authoring perspective, a single intrinsic dimension of an image is not really important; it's maintaining the ratio that counts.)

**Comment by FremyCompany** [comment]
@fantasai Ok let's rephrase slightly then.

I am currently evaluating the following idea: elements with ```width:auto;height:auto``` and an aspect ratio would behave like if they had ```width:auto;height: var(width * aspect-ratio)``` instead when alignment is ```normal``` (and maybe also ```stretch```). 

That way we could say that all elements (irrespective of aspect-ratio) behave as ```stretch``` in both directions, but the height only stretches if it is considered auto which would not be the case for an element that has an intrinsic aspect ratio. The fact width gets computed first is not a novelty, this is true in all browsers and all layout modes (by width I mean inline size ofc). 

Then either ```stretch``` would be an agressive ```normal``` that ignores aspect-ratio or maybe we don't even need any different with ```normal``` at all since you can get the stretch behavior using position:absolute +top/left/right/bottom:0 inside your grid area. It is even better because using stretch/normal will cause you to influence the track sizing with your image intrinsic size which is rarely what you want, especially if you want to stretch.

**Comment by cbiesinger** [comment]
How do the test cases look if you also add min-height: 0; min-width: 0;? Just trying to clarify if the bug is in min-size handling or the actual element sizing. For example, why shouldn't the first flex-shrink testcase have a minimum width of 32px since that's the intrinsic size and there's no definitive cross-size?

I do agree that the aspect ratio should be respected.

**Comment by FremyCompany** [comment]
Your second question is the key here. The image should not be 32px because there is a cross-size due to how flex works (the flex container has a definite size in both directions, and items have their height set to whatever value the flexbox resolves to; the next step is the). This was incorporated in the computation of the minimum size, see the following spec text:

> In general, the automatic minimum size is the smaller of its content size and its specified size. 
>
> **However, if the box has an aspect ratio and no specified size, its automatic minimum size is the smaller (15px) of its content size (32px) and its transferred size (15px * 32/32)**. 
>
> If the box has neither a specified size nor an aspect ratio, its automatic minimum size is the content size.

If you set min-width and min-height to 0px, this spec text does not even apply and you will be able to shrink to fit in all cases. 

-----------

The actual question in this thread is whether taking the automatic-minimum-size from the content-size makes sense for boxes that have an aspect ratio and a transferred size, because it results in flexing in the second case which is unexpected. If we changed the spec text to say that if there is an aspect ratio and a transferred size, use that. Otherwise use the content size. Then the first and second test case would match in results.

**Comment by cbiesinger** [comment]
> and items have their height set to whatever value the flexbox resolves to

That isn't really true though. That happens when stretch is resolved, and that happens fairly late in the algorithm:
https://drafts.csswg.org/css-flexbox/#algo-line-stretch

Notably this happens after the cross size of each line is determined. So at the point in time when we calculate the line height, the cross size is not definite and thus does not affect the aspect ratio calculation.

**Comment by FremyCompany** [comment]
> Handle 'align-content: stretch'. If the flex container has a definite cross size, align-content is stretch, and the sum of the flex lines' cross sizes is less than the flex container’s inner cross size, increase the cross size of each flex line by equal amounts such that the sum of their cross sizes exactly equals the flex container’s inner cross size. 

By that logic, wouldn't you always output the image at 32x32 at minimum? align-content:stretch does not allow to shrink, and if you do not consider the flex as imposing its height on the image, the image would get 32x32 which it doesn't in any browser. 

In actuality, this part of the algorithm does not even trigger here because the flex has only one line, and that line therefore takes its cross size from the element directly (see step 8).

The actual behavior we are discussing here is described further in the algorithm:

> 11: https://drafts.csswg.org/css-flexbox/#algo-stretch
> Determine the used cross size of each flex item. If a flex item has align-self: stretch, its computed cross size property is auto, and neither of its cross-axis margins are auto, the used outer cross size is the used cross size of its flex line, clamped according to the item’s min and max cross size properties. Otherwise, the used cross size is the item’s hypothetical cross size. 
> 
> If the flex item has align-self: stretch, redo layout for its contents, treating this used size as its definite cross size so that percentage-sized children can be resolved.
> 
> Note that this step does not affect the main size of the flex item, even if it has an intrinsic aspect ratio. 

The last sentence seems to give Chrome the edge here, though. By that line, we should actually always have a main size of 32px irrespective of whether we shrinked-or-grew the image. So, the algorithm explicitly does not try to preserve the aspect-ratio. I guess the reasoning is that otherwise your line could overflow even if you had set the flex to wrap. That is very unfortunate though, because now you cannot preserve the aspect ratio in a flex.

@fantasai Did I miss something here? Last time you had a look at this, you felt the first rendering was the right one, which was Edge's behavior. Now based on the actual spec text I am not sure anymore.

**Comment by FremyCompany** [comment]
https://jsfiddle.net/zcqst2pr/4/ shows that the shrinking is not due to flexing in Chrome and Firefox (since flex is set to 0). In Edge we overflow the line with two images of 128px width each.

Firefox behavior seems to be a compromise between us and Chrome, as in they accept the aspect-ratio things to take less main space than before, but not more. This ensure there will never be an overflow, but tries to maintain the aspect ratio if possible.

**Comment by gregwhitworth** [comment]
@FremyCompany Do you mind providing screenshots of what you're seeing, as I'm seeing FF/Chrome behaving the same:

![image](https://cloud.githubusercontent.com/assets/865244/24386128/c0e16c6e-1322-11e7-9e42-38a16ff162ee.png)

That or I'm misunderstanding what you mean by this:

> Firefox behavior seems to be a compromise between us and Chrome

**Comment by FremyCompany** [comment]
My bad :) 

As I clarified to you in person today, the new test is not related to the second statement :) The second statement was me trying to understand how Firefox has a behavior similar to Edge's one on the very first test (https://jsfiddle.net/zcqst2pr/) despite not working like Edge at all.

I now clarified that inline so that other people don't end up confused by it; feel free to delete your message.

**Comment by fantasai** [comment]
Note, @tabatkins and I just filed https://github.com/w3c/csswg-drafts/issues/1149 which is related here.

**Comment by tabatkins** [comment]
> > and items have their height set to whatever value the flexbox resolves to
> 
> That isn't really true though. That happens when stretch is resolved, and that happens fairly late in the algorithm:

Nope, it now happens automatically, by virtue of case 1 in https://drafts.csswg.org/css-flexbox/#definite-sizes. This gives the flex item a definite cross size immediately, before flex layout actually runs.

**Comment by fantasai** [comment]
@FremyCompany Do you think this issue still needs to stay open? (#1149 was fixed recently, fwiw.)

**Comment by FremyCompany** [comment]
I think it is fine to close. The topic was discussed in other issues as you mentioned.
