### ISSUE TITLE
Add Sebastian as CSS 2024 co-editor

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#11157]
@SebastianZ has already been doing _a lot_ of work for this spec, we just need a CSSWG resolution to make it official

@astearns I imagine this can be done async?

**Comment by astearns** [comment]
Huh, I thought we had already done this. But I can’t find where, so my apologies @SebastianZ!

As far as I understand, a resolution is not required: chairs can just appoint editors. So I appoint Sebastian Zartner as editor of the CSS Snapshot.
