### ISSUE TITLE
[css-grid] Please move Section 2.4, 'motivation', in the grid spec to the beginning of Section 2 (and minor spelling fixes)

### ISSUE THREAD

**Issue by Tyler-H** [w3c/csswg-drafts#1115]
I'm reading the [spec](https://www.w3.org/TR/css3-grid-layout/) for CSS Grids for the first time, and the ordering of the 'motivation' section seems to be... suboptimal at best. I appreciate an Introduction section, which talks briefly about how to position a grid and size it, but the [Reasoning & Motivation](https://www.w3.org/TR/css3-grid-layout/#background) section should really be at the beginning of the overview (or before the overview even begins, actually), not at the end of the Introduction. All of Section 2.4.x feels like it should be inserted before Section 2.1.

Additionally, can we **please** remove the 's' from the words 'forwards' and 'backwards' in the 2nd bullet point of the [Section 2](https://www.w3.org/TR/css3-grid-layout/#overview) intro? The words are properly 'forward' and 'backward' (just like 'toward' and 'onward' and 'upward' and 'downward'), even if the 's' ending has become common in the same sense as some people now say 'anyways' to mean 'anyway'.

Finally, in the last bullet point of [Section 2.4.1](https://www.w3.org/TR/css3-grid-layout/#adapting-to-available-space), the word 'are' should be changed to 'area'.

**Comment by tabatkins** [comment]
Your reasoning makes sense, so we've moved 2.4.x to be part of the Introduction instead.

Fixed the typo.  "forwards" and "backwards", tho, are commonly accepted English, so they can stay.
