### ISSUE TITLE
[css-conditional-5] scroll-state(overflowing) is confusing because it ignores clipped overflowing content

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#11182]
The `overflowing` scroll state query, whose values are `none | top | right | bottom | left | block-start | inline-start | block-end | inline-end `, is described as

> The overflowing container feature queries whether a scroll container has clipped scrollable overflow rectangle content in the given direction which is reachable through user initiated scrolling. That is, overflowing does not match for a hidden container, nor for a negative scrollable overflow region.

But colloquially, content that overflows and is clipped is still considered overflowing.

If the question is, "can I scroll in this direction", perhaps a better name would be `scrollable`?

**Comment by lilles** [comment]
> If the question is, "can I scroll in this direction", perhaps a better name would be `scrollable`?

Yes, I agree that scrollable would be a better name.

**Comment by yisibl** [comment]
> "can I scroll in this direction"

This is indeed easier to understand and fits the perception of CSS authors.

To accommodate more common scenarios, I've also come up with a new syntax: `scroll-state(scroll-to)` 

[Add scroll-state(scroll-to) container feature queries](https://github.com/w3c/csswg-drafts/issues/11191)
