### ISSUE TITLE
[css-display] Should anonymous boxes always inherit through the box tree?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1118]
[CSS Display](https://drafts.csswg.org/css-display/#intro) says

> anonymous boxes (which only exist in the box tree) inherit through their box tree parentage

I think this implies an anonymous box doesn't inherit from its parent element if the parent has [`display: contents`](https://drafts.csswg.org/css-display/#valdef-display-contents), because that means

> The element itself does not generate any boxes

For example,

```html
<section>
  <div>Foo</div>
</section>
```
```css
section {
  color: red;
}
div {
  color: green;
  display: contents;
}
```

Foo is wrapped inside an [anonymous inline box](https://www.w3.org/TR/CSS2/visuren.html#anonymous), so according to the quote above, it should inherit the red color from its parent box, which is the box of the section, because the div does not generate boxes.

But this seems wrong, because if we had

```html
<section>
  <div><span>Foo</span></div>
</section>
```

then the span would inherit the green color from the div through the element tree.

In Firefox and Chromium the text in the first example is green as expected, I think it's just that the spec is confusing.

**Comment by FremyCompany** [comment]
Can we add a test case here?

**Comment by tabatkins** [comment]
Yeah, I think that terminology is wrong now. We should probably define, for each anonymous box, what its "originating element" is, same as pseudo-elements have, which determines what it inherits from.

**Comment by tabatkins** [comment]
fantasai and I seem to disagree on the behavior - she think the first example should have red text; i find it vaguely horrifying that inserting a non-styled span should have dramatic effects on inheritance in this sole instance.

Assuming we go with "everything should be green", doing this rigorously seems to require us to define "text" as an object in the element tree that has properties (only set via inheritance), and which generates "text" in the box tree accordingly. I'm down with this.

(Alternately, we can do some handwavey "the element that would generate the text's parent box, if it wasn't display:contents". But that's handwavey and nasty; I'd much prefer to get a better, more rigorous description of text in the CSS model.)

**Comment by FremyCompany** [comment]
Wouldn't it be unfortunate if 
```
<hgroup>
  <h1>Introduction</h1>
  <p>...
</hgroup>
```
```
h1::before { content: "Chapter " counter(h1) ": "; }
```
would result in "Chapter 1: " and "Introduction" having different colors?

**Comment by bzbarsky** [comment]
> define "text" as an object in the element tree that has properties (only set via inheritance), and which generates "text" in the box tree accordingly

For what it's worth, this is what Gecko does anyway.  I can't speak for other implementations.

**Comment by Loirooriol** [comment]
Introducing text boxes would need to rewrite inline layout algorithm in order to take them into account. As I said in https://github.com/w3c/csswg-drafts/issues/1249#issuecomment-295437708, I think it would be easier (both conceptually and to spec) to handle this by wrapping each contiguous run of text that is directly contained inside an element into an anonymous inline box, which would inherit from the element. In practice it should almost be the same. Thoughts?

**Comment by astearns** [comment]
I believe the next step is for @tabatkins to come up with a proposal, so I'm removing the agenda+ waiting for that.

**Comment by tabatkins** [comment]
Proposed changes:

* **Display** - Define that the element tree contains text as well as elements.

* **Cascade** - Define how inheritance works over text

* **Scoping** - Rigorously define how text moves around due to shadows

* **Text** - Maybe some minor changes to rigorously talk about text?

* **Text Decor** - clarify whether the magic decoration inheritance is thru the box tree or element tree

* maybe more?

@fantasai and I are gonna explore what the actual edits need to be before we present this to the WG.

**Comment by fantasai** [comment]
#1281 makes it clear that whatever construct we create to handle the properties of text, it shouldn't be a CSS box.

**Comment by tabatkins** [comment]
Okay, we think this is the diff we need:

```diff
diff --git a/css-cascade/Overview.bs b/css-cascade/Overview.bs
index c72e6f1c5..f3ba84b99 100644
--- a/css-cascade/Overview.bs
+++ b/css-cascade/Overview.bs
@@ -45,14 +45,22 @@ Introduction</h2>
 <h3 id="placement">
 Module Interactions</h3>
 
+	<em>This section is normative.</em>
+
	<p>This module replaces and extends
 	the rules for assigning property values, cascading, and inheritance defined in [[!CSS21]] chapter 6.
 
	<p>Other CSS modules may expand the definitions of some of the syntax and features defined here.
 	For example, the Media Queries Level 4 specification,
 	when combined with this module, expands the definition of
 	the <<media-query>> value type as used in this specification.
 
+	For the purpose of this specification,
+	<a>text nodes</a> are treated as <a>element</a> children of their associated element,
+	and possess the full set of properties;
+	since they cannot be targetted by selectors
+	all of their computed values are assigned by <a href="#defaulting">defaulting</a>.
+
 <h2 id="at-import">
 Importing Style Sheets: the ''@import'' rule</h2>
 
diff --git a/css-display/Overview.bs b/css-display/Overview.bs
index b101c6eeb..661556484 100644
--- a/css-display/Overview.bs
+++ b/css-display/Overview.bs
@@ -34,21 +34,25 @@ Introduction</h2>
 
 	<p><em>This section is normative.</em>
 
-	CSS takes a source document, organized as a tree of <dfn lt="element|element tree">elements</dfn>,
+	CSS takes a source document, organized as a tree of <dfn lt="element|element tree">elements</dfn> and <dfn>text nodes</dfn>,
 	and renders it onto a <a href="https://www.w3.org/TR/CSS2/intro.html#canvas">canvas</a> (such as your screen, a piece of paper, or an audio stream).
 	To do this, it generates an intermediary structure,
 	the <dfn export>box tree</dfn>,
 	which represents the formatting structure of the rendered document.
-	Each <dfn export>box</dfn> represents its corresponding <a>element</a> (or <a>pseudo-element</a>)
-	in space and/or time on the canvas.
+	Each <dfn export>box</dfn> in the <a>box tree</a>
+	represents its corresponding <a>element</a> (or <a>pseudo-element</a>)
+	in space and/or time on the canvas,
+	while each <dfn export>text run</dfn> in the <a>box tree</a>
+	likewise represents the contents of its corresponding <a>text nodes</a>.
 
 	To create the <a>box tree</a>,
 	CSS first uses <a href="https://www.w3.org/TR/css-cascade/">cascading and inheritance</a>,
 	to assign a <a>computed value</a> for each CSS property
-	to each element in the source tree.
+	to each <a>element</a> and <a>text node</a> in the source tree.
 	(See [[!CSS3-CASCADE]].)
 
-	Then, for each element, it generates zero or more boxes
+	Then, for each element,
+	CSS generates zero or more boxes
 	as specified by that element's 'display' property.
 	Typically, an element generates a single <a>box</a>.
 	However, some 'display' values
@@ -62,6 +66,9 @@ Introduction</h2>
 	They're often referred to by their 'display' type--
 	e.g. a <a>box</a> generated by an element with ''display: block'' is called a “block box” or just a “block”.
 
+	Similarly, each contiguous sequence of sibling <a>text nodes</a> generates a <a>text run</a>,
+	which is assigned the same styles as the generating <a>text nodes</a>.
+
 	An <dfn lt="anonymous|anonymous box" export>anonymous box</dfn> is is a box that is not associated with any element.
 	<a>Anonymous boxes</a> are generated in certain circumstances
 	to fix up the <a>box tree</a> when it requires a particular nested structure
@@ -76,10 +83,11 @@ Introduction</h2>
 	<a href="https://www.w3.org/TR/css-cascade/#inheriting">inherit</a> through their <a>box tree</a> parentage.
 
 	In the course of layout,
-	a <a>box</a> may be broken into multiple <a>fragments</a>.
-	This happens, for example, when an inline box is broken across lines,
+	<a>boxes</a> and <a>text runs</a> can be broken into multiple <a>fragments</a>.
+	This happens, for example, when an inline box and/or text run is broken across lines,
 	or when a block box is broken across pages or columns.
-	A <a>box</a> therefore consists of one or more <a>box fragments</a>.
+	A <a>box</a> therefore consists of one or more <a>box fragments</a>,
+	and a <a>text run</a> consists of one or more <a>text fragments</a>.
 	See [[CSS3-BREAK]] for more information on <a>fragmentation</a>.
 
 	Note: Many of the CSS specs were written before this terminology was ironed out,
@@ -127,16 +135,18 @@ Box Layout Modes: the 'display' property</h2>
 	Media: all
 	</pre>
 
	The 'display' property defines box's <dfn export>display type</dfn>,
 	which consists of the two basic qualities of how an element generates boxes:
 
 	* the <dfn export local-lt="inner">inner display type</dfn>,
		which defines (if it a <a href="https://www.w3.org/TR/CSS2/conform.html#replaced-element">non-replaced element</a>) the kind of <a>formatting context</a> it generates,
 		dictating how its descendant boxes are laid out.
 		(The inner display of a <a href="https://www.w3.org/TR/CSS2/conform.html#replaced-element">replaced element</a> is outside the scope of CSS.)
 	* the <dfn export local-lt="outer">outer display type</dfn>,
 		which dictates how the box participates in its parent formatting context.
 
+	<a>Text runs</a> have no <a>display type</a>.
+
 	Some 'display' values have additional side-effects:
 	such as ''list-item'', which also generates a ''::marker'' pseudo-element,
 	and ''display/none'', which causes the element's entire subtree to be left out of the box tree.
@@ -498,7 +508,7 @@ Box Generation: the ''display/none'' and ''display/contents'' keywords</h3>
 		<dt><dfn>contents</dfn>
 		<dd>
 			The element itself does not generate any boxes,
-			but its children and pseudo-elements still generate boxes as normal.
+			but its children and pseudo-elements still generate box-tree nodes as normal.
 			For the purposes of box generation and layout,
 			the element must be treated as if it had been replaced in the [=element tree=]
 			by its contents
@@ -525,7 +535,10 @@ Box Generation: the ''display/none'' and ''display/contents'' keywords</h3>
 
 		<dt><dfn>none</dfn>
 		<dd>
-			The element and its descendants generate no boxes.
+			The <a>element</a> and its descendants generate no <a>boxes</a> or <a>text runs</a>.
+
+			Similarly, if a <a>text node</a> is defined to behave as ''display: none'',
+			it generates no <a>text runs</a>.
 	</dl>
 
 	Elements with either of these values do not have <a>inner</a> or <a>outer display types</a>,
diff --git a/css-flexbox/Overview.bs b/css-flexbox/Overview.bs
index 6fabce55e..ec53d00c1 100644
--- a/css-flexbox/Overview.bs
+++ b/css-flexbox/Overview.bs
@@ -561,12 +561,12 @@ Flex Items</h2>
 
 	Each in-flow child of a <a>flex container</a>
 	becomes a <a>flex item</a>,
-	and each contiguous run of text that is directly contained inside a <a>flex container</a>
-	is wrapped in an anonymous <a>flex item</a>.
-	However, an anonymous flex item that contains only
+	and each contiguous sequence of child <a>text runs</a>
+	is wrapped in an <a>anonymous</a> <a>block container</a> <a>flex item</a>.
+	However, if the entire sequence of child <a>text runs</a> contains only
 	<a href="https://www.w3.org/TR/CSS2/text.html#white-space-prop">white space</a>
 	(i.e. characters that can be affected by the 'white-space' property)
-	is not rendered (just as if it were ''display:none'').
+	it is instead not rendered (just as if its <a>text node</a> were ''display:none'').
 
 	<div class="example">
 		<p>Examples of flex items:
diff --git a/css-grid/Overview.bs b/css-grid/Overview.bs
index 315f9d9cc..c2851ed59 100644
--- a/css-grid/Overview.bs
+++ b/css-grid/Overview.bs
@@ -963,15 +963,16 @@ Clamping Overly Large Grids</h3>
 Grid Items</h2>
 
 	Loosely speaking, the <dfn export id="grid-item" lt="grid item">grid items</dfn> of a <a>grid container</a>
-	are boxes representing its in-flow contents:
-	each in-flow child of a <a>grid container</a>
-	becomes a <a>grid item</a>.
+	are boxes representing its in-flow contents.
 
-	Each contiguous run of text that is directly contained inside a <a>grid container</a>
-	is wrapped in an anonymous <a>grid item</a>.
-	However, an anonymous grid item that contains only
-	<a href="https://www.w3.org/TR/css-text/#white-space-processing">white space</a>
-	is not rendered, as if it were ''display: none''.
+	Each in-flow child of a <a>grid container</a>
+	becomes a <a>grid item</a>,
+	and each contiguous sequence of child <a>text runs</a>
+	is wrapped in an <a>anonymous</a> <a>block container</a> <a>grid item</a>.
+	However, if the entire sequence of child <a>text runs</a> contains only
+	<a href="https://www.w3.org/TR/CSS2/text.html#white-space-prop">white space</a>
+	(i.e. characters that can be affected by the 'white-space' property)
+	it is instead not rendered (just as if its <a>text node</a> were ''display:none'').
 
 	<div class="example">
 		<p>Examples of grid items:
```

We reviewed a few other specs that talk about text, particularly Fonts and Writing Modes, and they use "text runs" or "runs of text" in ways that are handwavily-compatible with this "text run" term of art.  They could use some cleaning up eventually, but we don't think their lack of precision is necessary to fix at this moment.

**Comment by Loirooriol** [comment]
- > it is instead not rendered (just as if its <a>text node</a> were ''display:none'').

   I think it should be "text nodes" in plural.

 - > each contiguous sequence of sibling text nodes generates a text run, which is assigned the same styles as the generating text nodes

    Should it be noted that this works because text nodes cannot be targeted by selectors, so they must have the same styles?

 - > but its children and pseudo-elements still generate box-tree nodes as normal

    The introduction should define "box-tree node" as either a box or a text run.

**Comment by bzbarsky** [comment]
> children of their associated element

I assume this is in some sense "before first-line and first-letter are applied"?

**Comment by fantasai** [comment]
@bzbarsky Yeah. The pseudo-elements spec needs to explain itself; currently it does that by pretending to be an element in the inheritance tree (which would effectively hijack the process described here), although there are some complications that need to be properly specced out, e.g. #1097.

**Comment by emilio** [comment]
> > define "text" as an object in the element tree that has properties (only set via inheritance), and which generates "text" in the box tree accordingly
>
> For what it's worth, this is what Gecko does anyway. I can't speak for other implementations.

Just for reference, this is what Blink does too. But it's not what WebKit does. WebKit doesn't store any style for the text nodes, and just assumes text style == parent box style in the relevant places. Fun :)

**Comment by anttijk** [comment]
@emilio Note that this just an optimization and not something fundamental.

I'm not entirely convinced that we need all this additional complexity to solve the original case, or that there is even anything to solve. The current behavior where the text turns red is consistent and not difficult to explain.

**Comment by bzbarsky** [comment]
> The current behavior where the text turns red

Current behavior in WebKit but not in Blink or Gecko, right?

**Comment by anttijk** [comment]
> Current behavior in WebKit but not in Blink or Gecko, right?

Right. That is also the behavior you get from the current specs before the revisions suggested here.

**Comment by anttijk** [comment]
Note that I'm not worrying about implementation complexity, I think we could implement this in WebKit without much trouble.

**Comment by bzbarsky** [comment]
I think it's pretty weird if wrapping a span with no styles applied to it around some text changes the styling of the text.  Can you think of any other cases in CSS where that would happen?

In particular, if someone wants to make the text a link target by putting `<span id="targetname">` around it, having that change the style of the text seems unfortunate.

**Comment by anttijk** [comment]
> I think it's pretty weird if wrapping a span with no styles applied to it around some text changes the styling of the text. Can you think of any other cases in CSS where that would happen?

In this case styles are being applied to the span via inheritance. I don't see a major difference between having explicit rules targeting the span vs targeting it's display:contents parent. The behavior is perfectly consistent.

**Comment by bzbarsky** [comment]
> In this case styles are being applied to the span via inheritance

Sure.

> I don't see a major difference between having explicit rules targeting the span vs targeting it's display:contents parent.

Again, sure, but in your proposed behavior there's a difference: the former would affect the text while the latter would not.

**Comment by tabatkins** [comment]
Right.

Without this "text node"/"text run" concept (just relying on "text is styled according to its enclosing box" concept), the first example in the OP gives red text, because the anonymous inline box that gets generated around the text has to inherit from its parent box, which is generated by the `section`; while in the second example, it gets green text, because it inherits from the `span`'s generated box, and the `span` is able to inherit from the `div` in the element tree.

With this concept, the text node inherits from the div or span in the element tree, getting `color:green` in both cases.

**Comment by anttijk** [comment]
> Again, sure, but in your proposed behavior there's a difference: the former would affect the text while the latter would not.

As far as I can gather you are arguing it is strange and surprising that adding a <span> around a text changes it color here. Obviously it wouldn't be surprising at all if there were an explicit rule targeting the span. I'm arguing that being styled via inheritance is no more surprising and the resulting behavior does not necessarily warrant introducing the entirely new concept of "text node styles".

Occam's razor and all that.

**Comment by tabatkins** [comment]
> Obviously it wouldn't be surprising at all if there were an explicit rule targeting the span and setting the color.

Yes, that would of course be normal and expected. As far as I can tell that's not germane to this issue, tho? Again, the issue is that, without something like what's described here, the inheritance behavior of text depends on whether or not its immediate parent element generates a box. This is inconsistent with how inheritance works for elements, thus the surprise.

> I'm arguing that being styled via inheritance from a display:contents element is no more surprising and the resulting behavior does not necessarily warrant introducing the entirely new concept of "text node styles".

I'm very confused by this statement. You're correct that being styled via inheritance from a display:contents element isn't surprising. That's what we're trying to ensure will happen!  Right now, as vaguely written, text *won't* inherit from a display:contents parent element; our concept of "text nodes" carrying styles ensures that it *does*, like normal elements do.

---

To help alleviate my confusion about what position you're advocating for, @anttijk, can you quickly say what color you expect the text to be in the two examples in the first comment?

**Comment by anttijk** [comment]
> This is inconsistent with how inheritance works for elements, thus the surprise.

We didn't have a case where you could have non-box-generating element with visible text children before display:contents. There is nothing to be inconsistent with; the case is new. It seem that the simplest solution would be that the text properties are defined by the parent box.

> I'm very confused by this statement. You're correct that being styled via inheritance from a display:contents element isn't surprising. That's what we're trying to ensure will happen! Right now, as vaguely written, text won't inherit from a display:contents parent element; our concept of "text nodes" carrying styles ensures that it does, like normal elements do.

I don't find it particularly surprising that a non- box generating element doesn't affect child text node style. In fact that's what I would expect. The text node is behaving as it was a direct child of the box-generating ancestor, something that is easily explained.

Perhaps there is some better example than has been presented here so far why this is a bad or inconsistent? The argument in the original post is that what makes it surprising is that an unstyled element would still be affected via inheritance. I was curious why people found it surprising.

**Comment by tabatkins** [comment]
> We didn't have a case where you could have non-box-generating element with visible text children before display:contents. There is nothing to be inconsistent with; the case is new.

Of course the case is new. But before `display:contents`, "text nodes exists in the element tree, and inherit from their parent element" and "text exists in the box tree, and inherits from its parent box" were *indistinguishable*.  Both behaviors had exactly the same effect (none of the box-tree manipulations that existed prior to `display:contents` changed the parent box of text in a way that would change the inheritance results).

Thus, you could pretend that inheritance always worked thru the element tree, for all styling.  Now, we suddenly have a case that breaks the symmetry, and we have to decide whether we prefer "inheritance always goes thru the element tree" or "inheritance is thru the element tree for elements, and thru the box tree for text".  The former is simpler overall, but requires introducing some new concepts to CSS; the latter requires no new spec concepts, but introduces an asymmetry and results that at least some people find surprising.

Neither way is particularly difficult for implementations, as far as I can tell, and thus I strongly prefer the one that doesn't produce a behavior asymmetry.

> The argument in the original post is that it is surprising that an unstyled element is still being affected via inheritance. I was curious why people found it surprising.

No, you seem to be misunderstanding the example? It's pointing out the difference in the style of *text*; the span is used to *introduce* the styling difference, it's not the point of the example.

The argument in the example is that it would be surprising if the two `target` elements in the markup below ended up with different `color` values:

```html
<parent color:red>
  <child display:contents color:green>
    <target />
  </child>
</parent>
<parent color:red>
  <child display:contents color:green>
    <wrapper>
      <target />
    </wrapper>
  </child>
</parent>
```

In both examples, `target` should have a computed `color` of `green`: in the first example, `target` directly inherits it from `child`; in the second example, `target` inherits from `wrapper`, but `wrapper` just inherits it from `child`, so it should be green as well.

It's weird, then, that if you replace `<target />` with raw text, you'd get a different result - it would be red in the first example, and green in the second.  What's the justification for raw text acting differently here?  Why, if I add a meaningless wrapper element that doesn't interfere with inheritance at all (for scripting purposes, perhaps), do I get a dramatic difference in inherited value?

Our diff fixes the specs so that this all works consistently, whether it's an element or text.

**Comment by anttijk** [comment]
@tabatkins You are just restating the basic facts of the case. I think everyone here understands them already. The actual argument seems to boil down to a personal preference.

I don't think we should abandon the "only elements and pseudo-elements have style" invariant for this. It is valuable in explaining and understanding how CSS works. That this requires little or no spec changes is a bonus.

I'm opposed to making these changes. CSSWG should just clarify that text style is determined by the box tree (if it is currently unclear).

> No, you seem to be misunderstanding the example?

I understand the example perfectly and already explained why I don't find the behavior surprising at all.

**Comment by frivoal** [comment]
> I don't think we should abandon the "only elements and pseudo-elements have style" invariant for this.

This seems less important than the "adding a non styled span in the middle inline content has no effect on rendering" invariant. If we could keep both, that'd be great. But as it seems we cannot, this one seems more important to preserve.

**Comment by anttijk** [comment]
@frivoal There is no such thing as "non-styled span" in a rendered document. In this case the span is getting styled via inheritance which I find no more surprising than being styled by explicit "span { color:green }".

**Comment by frivoal** [comment]
@anttijk I meant a span on which there is no specified styles.

**Comment by fantasai** [comment]
@anttijk It is a general principle here that `a bit of text` and `a <span>bit</span> of text`, where `<span>` has no style rule applying to it, render identically. This invariant is more important than any intuition about how things should work.
