### ISSUE TITLE
[css-scoping] :scope > * matches nothing in shadow trees

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#11188]
In https://github.com/w3c/csswg-drafts/issues/7261 (cc @emilio), @tabatkins concludes that:

> `myshadowroot.querySelector(":scope > *")` returns all the root nodes in the shadow tree.

But no it doesn't: in the context of a shadow tree, the shadow root is specified to be _replaced_ by the shadow host for the purposes of selector matching. This means that the node `:scope` represents here doesn't exist as far as selector matching is concerned. https://drafts.csswg.org/css-scoping-1/#host-element-in-tree

**Comment by tabatkins** [comment]
Oof, that's an accidental interaction. Maybe we can just special-case that and say that, when calling querySelector() on a shadow root, the `:scope` represents the shadow host.

(The shadow root is, itself, not selectable *anyway*, as it doesn't exist in the tree as far as Selectors is concerned.)

**Comment by sorvell** [comment]
Is this issue related / the same? https://github.com/w3c/csswg-drafts/issues/11000#issuecomment-2394745326

**Comment by andruud** [comment]
@sorvell I think that's definitely close enough, thanks.

Closing as duplicate of #11000.
