### ISSUE TITLE
[css-display-3] Specify what forms the containing block for relative, static and sticky positioned boxes

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11196]
According to the [current specification](https://www.w3.org/TR/css-position-3/#def-cb):

"The containing block of a static, relative, or sticky box is as defined by its formatting context. "

However, the [CSS2 specificaiton](https://www.w3.org/TR/CSS2/visudet.html#containing-block-details) states this independently of the formatting context:

"If the element's position is 'relative' or 'static', the containing block is formed by the content edge of the nearest block container ancestor box."

Please specify in the CSS Display Module Level 3 what constitutes the containing block and which edge forms the containing block for relatively and statically positioned boxes within each formatting context.

**Comment by gitspeaks** [comment]
According to [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block)

"If the position property is static, relative, or sticky, the containing block is formed by the edge of the content box of the nearest ancestor element that is either a block container (such as an inline-block, block, or list-item element) or establishes a formatting context (such as a table container, flex container, grid container, or the block container itself)."

**Comment by gitspeaks** [comment]
I'm not referring to the sizing or placement of elements within specific layout contexts, but rather to the definition of the containing block for elements with a ```position``` property of ```static``` or ```relative```.

**Comment by Loirooriol** [comment]
> A [grid item](https://drafts.csswg.org/css-grid/#grid-item) is sized within **the containing block defined by its [grid area](https://drafts.csswg.org/css-grid/#grid-area)**.

You seem to assume that there is one fake containing block for sizing or placement, and one actual containing block? That's not the case.

**Comment by gitspeaks** [comment]
>You seem to assume that there is one fake containing block for sizing or placement, and one actual containing block? 

Not at all. I’m simply not clear on why the statement about the grid item’s sizing within its grid area is relevant to this issue, especially without knowing the configured display property for the element in question.

**Comment by Loirooriol** [comment]
The statement is defining the containing block of a grid item to be its grid area. Note that `position: absolute` or `fixed` would prevent the element from being a grid item, so this doesn't apply.

**Comment by gitspeaks** [comment]
>A [grid item](https://drafts.csswg.org/css-grid/#grid-item) is sized within the containing block defined by its [grid area](https://drafts.csswg.org/css-grid/#grid-area).
>
>The statement is defining the containing block of a grid item to be its grid area. Note that position: absolute or fixed would prevent the element from being a grid item, so this doesn't apply.

This suggests that a grid item with ```position``` property of ```static``` or ```relative``` is not considered a 'positioned box' and should perhaps be explicitly mentioned in the broader definition of the containing block for elements with a ```position``` property of ```static``` or ```relative```, for clarity.

**Comment by Loirooriol** [comment]
You mean in CSS2? CSS Position takes precedence, and defers to the relevant specs like CSS Grid and so on.

**Comment by gitspeaks** [comment]
>You mean in CSS2? CSS Position takes precedence, and defers to the relevant specs like CSS Grid and so on.

Well, that's ultimately up to the CSS spec editors to decide. All I can say is that the [CSS2 spec](https://www.w3.org/TR/CSS2/visudet.html#containing-block-details) for this issue lacks the details found in [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block) regarding table containers, flex containers, and grid containers and does not mention ```position: sticky```. The [current spec](https://www.w3.org/TR/css-position-3/#def-cb) defers the answer to the 'formatting context,' which is not very informative. The [flex spec](https://www.w3.org/TR/css-flexbox-1/#flex-containers) defines a flex container as forming a containing block exactly like block containers by linking to the [CSS2 containing block spec](https://www.w3.org/TR/CSS2/visudet.html#containing-block-details) , which suggests that the containing block for positioned boxes with position of ```static``` or ```relative``` in a flex container is the content edge of the flex container. I haven’t found anything in the Grid spec addressing ```static```, ```relative``` or ```sticky``` positioned boxes (perhaps such boxes don’t apply there).

**Comment by Loirooriol** [comment]
> I haven’t found anything in the Grid spec addressing static, relative or sticky positioned boxes

As I have quote multiple times, the containing block of a grid item is defined to be the grid area. The `position` doesn't matter, as long as it's a grid item.

**Comment by gitspeaks** [comment]
> As I have quote multiple times, the containing block of a grid item is defined to be the grid area. The position doesn't matter, as long as it's a grid item.
 
I'm not disputing that :) I just think it needs to be explicitly mentioned in the spec, which it currently is not.

**Comment by gitspeaks** [comment]
With respect to a grid formatting context, consider simply stating: position: static, relative, or sticky has no effect on grid items.

**Comment by Loirooriol** [comment]
Well that's false, grid items can be relatively or stickily positioned. They just don't stop being grid items.

I don't get why you think it needs clarification, this is no different than `color: red` or `color: blue` don't prevent an element from being a grid item nor affect its containing block, but of course we are not going to explicitly say that.

**Comment by gitspeaks** [comment]
>Well that's false, grid items can be relatively or stickily positioned. 

Great, good know!

> I don't understand why you think it needs clarification.

Because the containing block of a *positioned box* is not necessarily its immediate containing box. You quoted: 'A grid item is sized within the containing block defined by its grid area.' Setting aside the question of whether sizing equals positioning, and assuming a grid item has a default ```position: static```, how do I know the containing block for the grid item doesn’t change when I apply ```position: relative``` or ```position: sticky```? In flow layout, the spec states that for a relatively positioned box, the containing block is the *first positioned ancestor*, which doesn’t necessarily point to any specific containing block within the formatting context.

**Comment by gitspeaks** [comment]
The question is simple: What is the containing block for grid items with position: ```relative``` or position: ```sticky``` in a grid formatting context?

**Comment by gitspeaks** [comment]
> No, it doesn't say that. CSS2 says "nearest block container ancestor box".

Right, regardless, the containing block of a box could be somewhere up the chain once it becomes 'positioned.'

>Again, the containing block for all grid items is their grid area. It doesn't matter if they have position: relative, color: magenta or text-decoration: underline.

Great!

So, in a grid formatting context, the containing block for grid items with position: ```static```, ```relative```, or ```sticky``` is their grid area.

That settles it.

As I've mentioned, I believe this needs to be explicitly mentioned because there is strong precedent (in flow layout) where a box's containing block can change once it becomes 'positioned.' This is not at all comparable to simply changing color: blue to color: red. In any case, I suggest we stop focusing on grid items, as it detracts from the broader requirement to explicitly define the containing block for position: static, relative, or sticky across all formatting contexts, ideally in one central location.

**Comment by gitspeaks** [comment]
An authoritative spec, similar to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block), would be very much appreciated.

**Comment by gitspeaks** [comment]
I should also point out that, regardless of any specific flow layout behavior, the [spec states](https://www.w3.org/TR/css-position-3/#def-cb):

>2.1.Containing Blocks of Positioned Boxes
The containing block of a static, relative, or sticky box is as defined by its formatting context.

This creates a legitimate expectation that the *containing block for positioned boxes* of type ```static```, ```relative```, or ```sticky``` should be clearly defined within the specification of each formatting context

**Comment by Loirooriol** [comment]
Seems clear enough to me:

- Inline layout: https://drafts.csswg.org/css-inline/#model
  > The block container’s [content edges](https://drafts.csswg.org/css-box-4/#content-edge) form the [containing block](https://drafts.csswg.org/css-display-4/#containing-block) for each of the [inline-level boxes](https://drafts.csswg.org/css-display-4/#inline-level-box) participating in its inline formatting context.
- Block layout: no modern spec, refer to CSS2
- Flex layout:
  - https://drafts.csswg.org/css-flexbox-1/#flex-containers
    > Flex containers form a containing block for their contents [exactly like block containers do](https://www.w3.org/TR/CSS2/visudet.html#containing-block-details).
  - https://drafts.csswg.org/css-flexbox-1/#flex-basis-property
    > the flex item’s containing block (i.e. its [flex container](https://drafts.csswg.org/css-flexbox-1/#flex-container))
- Grid layout:
  - https://drafts.csswg.org/css-grid/#grid-area-concept
    > A [grid item](https://drafts.csswg.org/css-grid/#grid-item)’s [grid area](https://drafts.csswg.org/css-grid/#grid-area) forms the containing block into which it is laid out.
  - https://drafts.csswg.org/css-grid/#grid-container
    > The contents of a [grid container](https://drafts.csswg.org/css-grid/#grid-container) are laid out into a [grid](https://drafts.csswg.org/css-grid/#grid), with [grid lines](https://drafts.csswg.org/css-grid/#grid-line) forming the boundaries of each [grid items](https://drafts.csswg.org/css-grid/#grid-item)’ containing block.
  - https://drafts.csswg.org/css-grid/#grid-item-sizing
    > A [grid item](https://drafts.csswg.org/css-grid/#grid-item) is sized within the containing block defined by its [grid area](https://drafts.csswg.org/css-grid/#grid-area).
  - https://drafts.csswg.org/css-grid/#item-margins
    > grid items are independently contained within the containing block formed by their [grid areas](https://drafts.csswg.org/css-grid/#grid-area)
  - https://drafts.csswg.org/css-grid/#placement
    > This grid area defines the [containing block](https://drafts.csswg.org/css-display-4/#containing-block) for the grid item
- Ruby layout: https://drafts.csswg.org/css-ruby-1/#formatting-context
  > Ruby containers are non-atomic inline-level boxes. Like regular inline boxes (see CSS Inline Layout 3 § 2 Inline Layout Model), they break across lines, and their containing block is the nearest block container ancestor.
  > As with the contents of inline boxes, the containing block for the contents of a ruby container (and all its internal ruby boxes) is the containing block of the ruby container.

It's just not much clear for table layout, since we have no proper spec nor interoperability.

**Comment by gitspeaks** [comment]
All of these define the 'containing block' for the formatting context in general, but they do not explicitly define the **Containing Block for Positioned Boxes**, as would reasonably be expected from the spec on **Positioned Boxes**.

**Comment by Loirooriol** [comment]
But that's defined in https://drafts.csswg.org/css-position/#def-cb!
Absolute and fixed positioned boxes are defined in this link.
The only part which is deferred to other specs is for static, relative, or sticky boxes, which is what I posted above.

**Comment by gitspeaks** [comment]
>The only part which is deferred to other specs is for static, relative, or sticky boxes, which is what I posted above.

I disagree. Nothing in what you posted explicitly mentions the **Containing Block for Positioned Boxes**.

To quote directly from the spec:

>The containing block of a static, relative, or sticky box is as defined by its formatting context.

**Comment by gitspeaks** [comment]
The spec is [2.1. Containing Blocks of Positioned Boxes](https://www.w3.org/TR/css-position-3/#def-cb)

**Comment by Loirooriol** [comment]
All boxes have a position. It's either out-of-flow, and the containing block is defined in https://drafts.csswg.org/css-position/#def-cb, or in-flow and the containing block is deferred to other specs.

I don't get what you mean that "the 'containing block' for the formatting context in general" is not for "positioned boxes".

**Comment by gitspeaks** [comment]
>I don't get what you mean that "the 'containing block' for the formatting context in general" is not for "positioned boxes".

I mean that the position property value of child elements isn't considered in the formatting spec when discussing containing blocks.

I'm not interested in knowing that the containing block of a grid item is its grid area. I'm specifically interested in knowing the containing block of a _positioned grid item_ whose ```position``` property is set to either ```static```, ```relative```, or ```sticky```

**Comment by Loirooriol** [comment]
I give up.

**Comment by gitspeaks** [comment]
I didn’t invent the term 'Containing Block for Positioned Boxes'—the spec did.

**Comment by gitspeaks** [comment]
The [spec states](https://www.w3.org/TR/css-position-3/#def-cb):

> The containing block of a static, relative, or sticky box is as defined by its formatting context.

A 'formatting context' is an environment with a set of rules. Not a single formatting spec specifies what the containing block of a static, relative, or sticky box is.

**Comment by astearns** [comment]
@gitspeaks see https://github.com/w3c/csswg-drafts/issues/11196#issuecomment-2474968755 where @Loirooriol went through what each formatting context says about establishing containing blocks. That’s the context’s containing block for static, relative and sticky boxes.

**Comment by astearns** [comment]
It is in each spec - Oriol gave you links. 

A formatting context can establish a containing block. That containing block is used for everything that references a formatting context’s containing block.

We are not going to explicitly enumerate all of the specific uses of containing blocks every time we mention how they are established. That’s a maintenance nightmare.

**Comment by gitspeaks** [comment]
I’m not sure I understand the maintenance concern. 

Here’s how it could be stated clearly:

- Grid formatting context: "The containing block for grid items with position: `static`, `relative`, or `sticky` is their grid area"
- Flex formatting context: "The containing block for flex items with position: `static`, `relative`, or `sticky` is the content edge of their flex container"
- Block and Inline context: "The containing block for elements with position: `static`, `relative`, or `sticky` is the content edge of the nearest block container."

**Comment by astearns** [comment]
Containing blocks are used for many more things than those three position types, and we will also add more formatting contexts over time. Having to update all of the places where we establish containing blocks any time we add a new dependency on a containing block is the nightmare we need to avoid.

I am going to close this issue, as we are not going to be making the change you request in the comment above.

**Comment by gitspeaks** [comment]
>Containing blocks are used for many more things than those three position types, and we will also add more formatting contexts over time.

This is not related to the current issue at all.

I apologize, but in my opinion, the conclusion reached here is unreasonable.

From the [CSS 2 spec](https://www.w3.org/TR/CSS2/visuren.html#positioning-scheme)

9.3.2 Box offsets: 'top', 'right', 'bottom', 'left'

"An **element is said to be positioned** if its ['position'](https://www.w3.org/TR/CSS2/visuren.html#propdef-position) property has a value other than 'static'. **Positioned elements generate positioned boxes**, laid out according to four properties:"

**Comment by gitspeaks** [comment]
@Loirooriol wrote:

>All boxes have a position. It's either out-of-flow, and the containing block is defined in https://drafts.csswg.org/css-position/#def-cb, or in-flow and the containing block is deferred to other specs.

This categorization is incorrect for this issue.

According to the CSS2 specification, the categories are:

1. **Positioned Elements** – those with the position property set to: `relative`, `absolute`, `fixed`, or `sticky`.
2. **Non-positioned Elements** – those with the position property set to: `static`

**Comment by gitspeaks** [comment]
I kindly request that this issue be reopened to allow for public scrutiny.
