### ISSUE TITLE
Clarification on "value propagation to the viewport" in BFC conditions

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11210]
In the [CSS2 spec](https://www.w3.org/TR/CSS2/visuren.html#block-formatting), one of the conditions for establishing a block formatting context includes:

_"block boxes with 'overflow' other than 'visible' (except when that value has been propagated to the viewport)"_

Could we get a bit more clarification on what “value propagation to the viewport” means in this case?

Specifically:

1. How does this propagation happen?
2. Are there examples where this applies? 

Thanks in advance!

**Comment by astearns** [comment]
https://drafts.csswg.org/css-overflow-3/#overflow-propagation

**Comment by Loirooriol** [comment]
Also in CSS2: https://www.w3.org/TR/CSS2/visufx.html#overflow

> UAs must apply the 'overflow' property set on the root element to the viewport. When the root element is an HTML "HTML" element or an XHTML "html" element, and that element has an HTML "BODY" element or an XHTML "body" element as a child, user agents must instead apply the 'overflow' property from the first such child element to the viewport, if the value on the root element is 'visible'. The 'visible' value when used for the viewport must be interpreted as 'auto'. The element from which the value is propagated must have a used value for 'overflow' of 'visible'.

**Comment by gitspeaks** [comment]
It appears that the note, 'except when that value has been propagated to the viewport,' refers to a specific case (possibly where the overflow property of the body element is propagated to the viewport). This does not appear to represent a distinct class of situations for block boxes with overflow other than visible. Therefore, it might be more appropriate to simply outline the specific case where a block box with overflow other than visible does not establish a BFC.

**Comment by Loirooriol** [comment]
I don't know what you mean with "distinct class of situations". The note is necessary in CSS2 because there is no proper distinction of computed vs used values.

In CSS Overflow it's clear that the propagation happens at used-value time, so when we have a modern block layout spec, it will suffice to check for a "used `overflow` value different than `visible`".

**Comment by gitspeaks** [comment]
>I don't know what you mean with "distinct class of situations"

The spec states:

_"block boxes with 'overflow' other than 'visible' (except when that value has been propagated to the viewport)"_

What other examples are there where the overflow value of block boxes propagates to the viewport, aside from the case where the overflow value of the body element propagates to the viewport when its parent html/xhtml element has an overflow value other than visible?
