### ISSUE TITLE
Is a box that establishes a BFC considered a Block Container?

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11217]
Could you clarify if a box that establishes an independent formatting context is considered a block container? The spec is currently unclear on this point.

**Comment by Loirooriol** [comment]
> Is a box that establishes a BFC considered a Block Container?

Yes

> Could you clarify if a box that establishes an independent formatting context is considered a block container?

Not in general.

> a position value of absolute or fixed blockifies a box and forces it to establish an independent formatting context. Is the that box now considered a "Block container" ?

Forcing a box to establish an independent formatting context doesn't turn it into a block container. Either it was already a block container and then it will establish a BFC, or it was something else and will establish a different kind of formatting context, or "establish an independent formatting context" doesn't apply.

**Comment by gitspeaks** [comment]
But setting `position: absolute` forces the principal box to establish an independent formatting context, and we know that an absolutely positioned box establishes a BFC. Therefore, setting `position: absolute` makes the principal box a 'block container' regardless of its display status.

**Comment by Loirooriol** [comment]
> we know that an absolutely positioned box establishes a BFC

False, it can establish other formatting context

> setting position: absolute makes the principal box a 'block container' regardless of its display status

False, it can be another kind of container

**Comment by gitspeaks** [comment]
According to the [spec](https://www.w3.org/TR/CSS2/visuren.html#block-formatting)

Floats, _absolutely positioned elements_, block containers (such as inline-blocks, table-cells, and table-captions) that are not block boxes, and block boxes with 'overflow' other than 'visible' (except when that value has been propagated to the viewport) establish new _block formatting contexts_ for their contents.

**Comment by Loirooriol** [comment]
CSS2 is outdated. As I pointed out in https://github.com/w3c/csswg-drafts/issues/11126#issuecomment-2462012041

**Comment by Loirooriol** [comment]
In case you missed the **big, red, bold warning**:

![](https://github.com/user-attachments/assets/4d934932-14cd-4c0e-841c-e687f37f0782)

**Comment by gitspeaks** [comment]
So the note in the [new spec](https://www.w3.org/TR/css-position-3/#position-property):

> *"A position value of absolute or fixed blockifies the box, causes float to compute to none, and forces the box to establish an independent formatting context."*

This means that:

1. If the box has inner display: `flow`, `flow-root`, or `table`, it will establish a new BFC once it is positioned.
2. If the box has inner display: `flex`, it will establish a new Flex Formatting Context once positioned.
3. If the box has inner display: `grid`, it will establish a new Grid Formatting Context once positioned.
4. If the box has inner display: `ruby`, it will establish a new Ruby Formatting Context once positioned.

**Comment by gitspeaks** [comment]
Can the same be said on [flex item](https://www.w3.org/TR/css-flexbox-1/#flex-item) ?


1. If the flex item box has inner display: `flow`, `flow-root`, or `table`, it will establish a new BFC for its contents.
2. If the flex item box has inner display: `flex`, it will establish a new Flex Formatting Context for its contents.
3. If the flex item box has inner display: `grid`, it will establish a new Grid Formatting Context for its contents.
4. If the flex item box has inner display: `ruby`, it will establish a new Ruby Formatting Context for its contents.

**Comment by Loirooriol** [comment]
Basically, yes. If it's not replaced or some special HTML thing or such.

Also, about ruby, once blockified the principal box is a block container (see #9265) which will then establish a BFC, the ruby formatting context is established by a non-principal inline-level ruby container.
