### ISSUE TITLE
Definition of "block container" is incomplete

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11214]
The [CSS2 definition](https://www.w3.org/TR/CSS2/visuren.html#block-boxes) of "block container" omits flex-level boxes, which can also function as block containers.

Additionally, the [current definition](https://www.w3.org/TR/css-display-3/#block-container) of "block container" does not specify which types of boxes act as block containers, as the CSS2 spec does.

**Comment by Loirooriol** [comment]
> The [CSS2 definition](https://www.w3.org/TR/CSS2/visuren.html#block-boxes) of "block container" omits flex-level boxes

Of course, because CSS2 doesn't have flex layout.

> the [current definition](https://www.w3.org/TR/css-display-3/#block-container) of "block container" does not specify which types of boxes act as block containers

This doesn't need to be in the definition of the term, but it's in the spec: https://www.w3.org/TR/css-display-3/#inner-model

**Comment by gitspeaks** [comment]
>This doesn't need to be in the definition of the term, but it's in the spec: https://www.w3.org/TR/css-display-3/#inner-model

However, in CSS2, this information is included as part of the definition itself, so it would be clearer to add a link to the inner display section in the new term.

Also, while you [mentioned](https://github.com/w3c/csswg-drafts/issues/11126#issuecomment-2462598951)  that a flex-level box acts as a block container, there’s no mention of a 'default' inner display that confirms this behavior, nor is there any indication that this applies to 'out-of-flow' boxes.
