### ISSUE TITLE
[css-pseudo] Should probably have a note about it not being OK to have a UA ::selection rule

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#1122]
Maybe this is already covered by the "The UA should use the OS-default highlight colors when neither color nor background-color has been specified by the author." bit, in that such a rule should be ignored anyway?

But if it should _not_ be ignored, then I think the interaction with https://compat.spec.whatwg.org/#the-webkit-text-fill-color makes it impossible to use one anyway, while keeping the current behavior of browsers.  See https://bugzilla.mozilla.org/show_bug.cgi?id=234102#c60

**Comment by upsuper** [comment]
I think CSSWG should adopt `text-fill-color` and make all places which is about text color use that property instead. It would make `color` a builtin variable which merely provides a "foreground color" but doesn't directly control anything.

**Comment by bzbarsky** [comment]
I don't see how that solves the problem with ::selection interaction and current browser behavior....

**Comment by fantasai** [comment]
@bzbarsky I thought we already had a note about this?

> Note: This paired-cascading behavior does not allow using the normal cascade to represent the OS default selection colors. However it has been interoperably implemented in browsers and is thus probably a Web-compatibility requirement.

Is there something wrong with the note?

**Comment by fantasai** [comment]
I think this is the best I can do with the information I have currently. Feel free to file a new issue if some more specific fix is required.
