### ISSUE TITLE
Can't generate html file for bikeshed file  

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11233]
I would like to submit edits to the spec via a pull request, but I am unable to generate a preview HTML file to verify my changes.

 I attempted to preview the spec using [https://api.csswg.org/bikeshed/](https://api.csswg.org/bikeshed/) by submitting a direct link to the Bikeshed file:  
   [https://github.com/gitspeaks/csswg-drafts/blob/main/css-position-3/Overview.bs](https://github.com/gitspeaks/csswg-drafts/blob/main/css-position-3/Overview.bs).  

   However, I see the following errors:

```
FATAL ERROR: The document requires at least one <pre class=metadata> block.
FATAL ERROR: Spurious / in <input>.
FATAL ERROR: Found unmatched text macro [ABSTRACT]. Correct the macro, or escape it by replacing the opening [ with [
   ```

   I cloned the repository locally and switched to the `main` branch.  In the `css-position-3` directory, I ran:

   ```bash
   bikeshed spec Overview.bs
   ```
   But I get this error:
 
 ```
LINE ~398: Couldn't find section '#inset-area' in spec 'css-anchor-position-1':
[[css-anchor-position-1#inset-area]]
 ✘  Did not generate, due to errors exceeding the allowed error level.
   ```

My Environment:

Bikeshed version: 4.2.7
Spec branch: main
Spec directory: css-position-3/Overview.bs

Could you please help me understand what might be causing these errors and how I can resolve them?

**Comment by Loirooriol** [comment]
The errors should be fixed, but you can use `bikeshed -f spec Overview.bs` as described in https://speced.github.io/bikeshed/#cli-options

**Comment by Loirooriol** [comment]
> Could you please help me understand what might be causing these errors

The error is because of this broken link: https://github.com/w3c/csswg-drafts/blob/a92c32c5c351763a84430bee0cb34e29cd5cf335/css-position-3/Overview.bs#L401

You can see it broken in https://drafts.csswg.org/css-position/#original-cb

It broke in #10592 @nt1m

**Comment by gitspeaks** [comment]
The most recent commit I see is:

[web-animations-2] Change progress to overallProgress (#11184)

Could you confirm if the fix has been merged into the main branch?

**Comment by Loirooriol** [comment]
With "should be fixed" I mean that somebody should fix it rather than relying of `-f`, not that it has been done already.

**Comment by gitspeaks** [comment]
>With "should be fixed" I mean that somebody should fix it rather than relying of -f, not that it has been done already.
>In other words, if you were already planning to send some patches to the spec, this can be a good first bug

Understood. I currently have an edit on a different issue that I'd like to submit. Could you please review it to ensure I've followed the process correctly?

**Comment by gitspeaks** [comment]
Created PR #11239. Not sure about the error check message

**Comment by gitspeaks** [comment]
Can confirm that running `csswg-drafts/css-position-3$ bikeshed spec Overview.bs` results in the message:

✔ Successfully generated, with 146 linking errors.
