### ISSUE TITLE
[css-values] Font-relative lengths section heading is missing 'cap'

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1126]
The heading for https://drafts.csswg.org/css-values/#font-relative-lengths neglects to mention the newly-added ['cap' unit](https://drafts.csswg.org/css-values/#cap).

> 5.1.1. Font-relative lengths: the em, ex, ch, ic, rem, lh, rlh units

**Comment by tabatkins** [comment]
Merged #1134 to fix this.
