### ISSUE TITLE
[css-fonts-3] Is the exclusion of calc() from @font-feature-values intentional?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#1127]
I was writing some code to improve support for `calc()` in gecko
and I happened to accidentally support it in `@font-feature-values`,
specifically the NUMBER in the grammar here:
https://drafts.csswg.org/css-fonts-3/#basic-syntax
The prose says that NUMBER "are limited to integer values 0 or greater".
With that grammar + prose, `calc()` isn't allowed.  If the spec instead used
`<integer>` in the grammar then `calc()` would be allowed per:
https://drafts.csswg.org/css-values/#calc-notation

This makes `feature_value_definition` in `@font-feature-values` 
different from `<feature-tag-value>` in `font-feature-settings`:
https://drafts.csswg.org/css-fonts-3/#feature-tag-value
which use `<integer>` and thus allows `calc()` expressions.

Is this difference intentional?
(If so, it might be worth adding a note, or include a `calc()` in the example
that lists syntax errors, to make that clear.)

**Comment by litherum** [comment]
https://drafts.csswg.org/css-values/#calc-range says "Parse-time range-checking of values is not performed within calc(), and therefore out-of-range values do not cause the declaration to become invalid. However, the used value resulting from an expression must be clamped to the range allowed in the target context."

So it sounds to me like calc() would work. Is there something I'm missing?

**Comment by MatsPalmgren** [comment]
The current `@font-feature-values` grammar simply does not allow `calc()` **at all**.
If you want to allow `calc()` there you need to replace NUMBER with `<integer>` or spell out
a grammar for `calc()` in place.

**Comment by litherum** [comment]
As for the actual question you're asking “is it intentional,” I don't know.

It is, however, valuable to allow calc().

**Comment by svgeesus** [comment]
Agreeing that it is useful to allow calc. 

I suspect it was not intentionally disallowed - some of the text in CSS3 Fonts dates to CSS 2.0 and NUMBER was probably just copied over. It should, as you say, be `<integer>`

**Comment by svgeesus** [comment]
So, agreed editorial and needs edits?

**Comment by litherum** [comment]
Yeah we should make it match font variation settings (and thus allow calc)

**Comment by svgeesus** [comment]
@MatsPalmgren NUMBER changed to <integer> in both Fonts 3 and Fonts 4. All good now?

**Comment by csnardi** [comment]
@svgeesus I think the changes introduced in https://github.com/w3c/csswg-drafts/commit/cb2aec3d9003ca6c026e034e832d6df6ddff09cf were incorrect, as I believe in each of those instances a `<number>` type should be accepted, not only `<integer>`s. However, the changes to Fonts 3 should all be fine.

**Comment by svgeesus** [comment]
@csnardi @MatsPalmgren  Hmm. Actually I didn't really understand why &lt;integer> allowed `calc` while &lt;number> did not. So, what change should be made to Fonts 4 to allow non-integers and also allow `calc`?

**Comment by csnardi** [comment]
@svgeesus I think the difference is that in Fonts 3, `NUMBER` was used which referred to https://www.w3.org/TR/CSS21/syndata.html#tokenization, whereas in Fonts 4 `<number>` was used which referred to https://drafts.csswg.org/css-values-3/#number-value. Since `font-feature-settings` only accepts integer values, I believe that's why @MatsPalmgren suggested using `<integer>` for Fonts 3, since `<number>` and `<integer>` imply support for calc whereas `NUMBER` does not.

**Comment by emilio** [comment]
Also, probably the `<string>` part of the syntax should also be changed or clarified to represent what implementations do. In particular, strings that can't be a proper feature tag are considered invalid declarations:

```css
font-feature-settings: "vert" 1; /* fine */
font-feature-settings: "vertical" 1; /* fine per the syntax, but not a valid declaration on any browser */
```

**Comment by tabatkins** [comment]
@csnardi @svgeesus More specifically, the old grammar approach that Fonts 3 referred to *simply doesn't exist anymore* - CSS is no longer parsed according to CSS 2.1 Appendix G, it's parsed according to the Syntax spec, and generally you can only interact with the results via a standard CSS value-definition grammar (that is, `<number>` or `<integer>` or the like).  `NUMBER` has no meaning at all now. ^_^
