### ISSUE TITLE
[css-position-3] Disassociate sticky positioning from relative positioning

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11298]
The [CSS Position 3 spec, Section 2](https://drafts.csswg.org/css-position-3/#valdef-position-sticky) states:

> `sticky`
>  Identical to relative, except that its offsets are automatically adjusted in reference to the nearest ancestor scroll container’s scrollport ...

The [CSS Position 3 spec, Section 3.4](https://drafts.csswg.org/css-position-3/#stickypos-insets) states:

> Sticky positioning is similar to relative positioning except the offsets are automatically calculated in reference to the nearest scrollport.

Issue:

Sticky positioning is neither identical nor similar to relative positioning. In relative positioning, the element is immediately shifted by the specified offset, while preserving its original space in the layout. In sticky positioning, the element initially remains in its normal flow position, with the offset acting as a threshold that activates sticky behavior during scrolling. Before scrolling, the element behaves as though it is static, not positioned.

Describing sticky positioning in terms of relative positioning is unnecessary and misleading. The spec should describe sticky positioning independently.

**Comment by tabatkins** [comment]
No, they are indeed identical in overall behavior: both keep their elements in-flow, both create abspos containing blocks, and both "leave behind" their geometry in their original position, just shifting the element visually. These properties are not shared by abspos or fixpos.

The differences are in how their 'inset' arguments relate to their shifted position: relative moves the element by the inset, while sticky moves automatically to stay within the scrollport, with a separation from the scrollport edge given by the inset.

So yes, they are indeed largely identical, except for the difference that is called out.

**Comment by gitspeaks** [comment]
>both keep their elements in-flow, both create abspos containing blocks, and both "leave behind" their geometry in their original position, just shifting the element visually. These properties are not shared by abspos or fixpos.

So what? You’ve identified two properties—keeping elements in-flow (e.g "leave behind" their geometry in their original position") and creating abspos containing blocks—that are not shared by abspos or fixpos. Does this really justify explaining sticky positioning in terms of relative positioning? What’s the goal here—saving words?

While sticky positioning does 'leave behind' its geometry in the original position, the conditions under which this happens are fundamentally different from relative positioning. In relative positioning, the inset properties determine the shift in geometry from the outset. Describing sticky as 'identical to relative, except...' is overly simplistic and misleading, as it fails to convey when the 'relative positioning' behavior actually begins to occur.

At the very least, the spec should explicitly state that once a sticky element reaches an inset threshold, its geometry shifts to remain in view within its containing block while still retaining its original in-flow space—similar to how relative positioning behaves.

I suggest you consider this as an open issue.
