### ISSUE TITLE
[css-values] Logical equivalents for vw/vh units

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#113]
People may need to use viewport units in a writing-mode-aware way, so probably we should add logical equivalents for `vw` and `vh`. They could be called `vis` and `vbs` or something like that.

**Comment by bradkemper** [comment]
I understand i for inline, and b for block, but what does s stand for?

I assume the dimension would remain constant based on the writing mode of the root element only, and not vary relative to the element they are used in?

**Comment by upsuper** [comment]
`is` and `bs` means `inline-size` and `block-size` which are the logical equivalents for `width` and `height` in [CSS Logical Properties spec](https://drafts.csswg.org/css-logical-props/#logical-dimension-properties).

**Comment by tabatkins** [comment]
Yeah, I'm fine with this.

**Comment by fantasai** [comment]
I'd drop the s, seems unnecessary.

**Comment by fantasai** [comment]
Btw, here's the www-style thread on this: https://lists.w3.org/Archives/Public/www-style/2015Sep/0253.html

**Comment by tabatkins** [comment]
We resolved in the telcon to add `vi` and `vb`.

**Comment by tabatkins** [comment]
Hm, unexpected complication: I'm defining them to take their direction from the root element, but what do we do when you evaluate them in a context without an element?  Like, in MQ we define `rem` without reference to a root element.  Do we have a usable notion of writing mode at the document level, without referencing elements or CSS?

**Comment by frivoal** [comment]
How about simply going with the initial value of the writing-mode property, which means in an MQ context, vi=vw and vb=vh?

**Comment by tabatkins** [comment]
I suppose we should be using the same concept as [(overflow-block)](https://drafts.csswg.org/mediaqueries/#mf-overflow-block), but that doesn't appear to actually be well-defined.

**Comment by frivoal** [comment]
I agree it should be the same for both, and I think that going with the initial value of the writing mode property (i.e. vertical is block, horizontal is inline) is the  sane thing to do.

**Comment by tabatkins** [comment]
Sounds good to me.

**Comment by fantasai** [comment]
Tab, this goes into L4. Which hasn't forked yet because we've got outstanding issues on L3 and can't republish CR. I've commented it out for now.

**Comment by The-Peppester** [comment]
I am soooo pumped for this. Ben waiting 20 some odd years to have something like vi and vb. Also, you rlly need to additionally add ci and cb which will stand for content inline (width) and content box (height) so you can dynamically scale your content to the size of its inside box. To be honest, im just plain tired of all this crazy hacky, exhausting css whcih makes developers lives alot harder. If web browsers added in just theese 4 units, then CSS would be a billion times easier. Btw. I dont care about how hacky or inefficient the polyfill is for them, I just want em now!
