### ISSUE TITLE
[CSS2] Clarify the relationship between anonymous block boxes and inline element boxes

### ISSUE THREAD

**Issue by gitspeaks** [w3c/csswg-drafts#11324]
The [CSS 2, section 9.2.1.1](https://www.w3.org/TR/CSS22/visuren.html)  states:

> if a block container box (such as that generated for the DIV above) has a block-level box inside it (such as the P above), then we force it to have *only* block-level boxes inside it.

While the specification provides an example involving text sequences, it lacks detailed clarification regarding the behavior of inline elements in such scenarios.

Consider the following example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <style>
    .block {
      width: 200px;
      height: 50px;
      background-color: blue;
    }
  </style>

  <body>
    <div>
      <div class="block">Block Level</div>
      <a style="padding-top: 25px; background-color: red">Inline Level</a>
      <div class="block">Block Level</div>
    </div>
  </body>
</html>
```

Expected Behavior: 

If the inline element is wrapped in an anonymous block box, one would expect the inline element box to contribute to the height of the anonymous block box. This should result in a red box painted below the first blue box, in accordance with block-level layout rules.

Actual  Behavior:

The inline element box appears to escape the anonymous block box, overlapping the first blue `div` . This behavior is unexpected and deviates from the intuitive application of block-level layout rules.

![anonymous](https://github.com/user-attachments/assets/016c59b7-907b-41df-8c6e-2b67a8846551)

**Comment by faceless2** [comment]
This is not a specification issue.

The padding is on the inline element, but that does not contribute to the height of the line box, which determines is the height of the anonymous box. This is described in 10.6.1 of CSS 2.1

> The vertical padding, border and margin of an inline, non-replaced box start at the top and bottom of the content area, and has nothing to do with the ['line-height'](https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#propdef-line-height). But only the ['line-height'](https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#propdef-line-height) is used when calculating the height of the line box.

and in css inline 3

> Additionally, when [line-fit-edge](https://www.w3.org/TR/css-inline-3/#propdef-line-fit-edge) is not [leading](https://www.w3.org/TR/css-inline-3/#valdef-line-fit-edge-leading), the [layout bounds](https://www.w3.org/TR/css-inline-3/#layout-bounds) are inflated by the sum of the [margin](https://www.w3.org/TR/css-box-4/#margin), [border](https://www.w3.org/TR/css-box-4/#border), and [padding](https://www.w3.org/TR/css-box-4/#padding) on each side. In order to allow negative margin values to have an actual effect, negative margins are also accumulated onto the layout bounds of any descendant [inline boxes](https://www.w3.org/TR/css-display-3/#inline-box) participating in the same [inline formatting context](https://www.w3.org/TR/css-inline-3/#inline-formatting-context).

With respect, you have filed quite a few specification issues here and every time you do quite a few hundred people are notified. This is not spec issue, it is simply a misunderstandings of how CSS layout works. For those sort of answers you might be better off on stackoverflow.

**Comment by gitspeaks** [comment]
There seems to be a contradiction here. On one hand, it is stated that:

> "But only the ['line-height'](https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#propdef-line-height) is used when calculating the height of the line box."

Yet on the other hand:

> "When [line-fit-edge](https://www.w3.org/TR/css-inline-3/#propdef-line-fit-edge) is not [leading](https://www.w3.org/TR/css-inline-3/#valdef-line-fit-edge-leading), the [layout bounds](https://www.w3.org/TR/css-inline-3/#layout-bounds) are inflated by the sum of the [margin](https://www.w3.org/TR/css-box-4/#margin), [border](https://www.w3.org/TR/css-box-4/#border), and [padding](https://www.w3.org/TR/css-box-4/#padding) on each side."

This seems inconsistent when considering the definition of layout bounds:

> "The contribution of an [inline box](https://www.w3.org/TR/css-display-3/#inline-box) to the [logical height](https://www.w3.org/TR/css-writing-modes-4/#logical-height) of its [line box](https://www.w3.org/TR/css-inline-3/#line-box), here referred to as its **layout bounds**, is always calculated with respect to its own text metrics, as described below, and is controlled by [line-fit-edge](https://www.w3.org/TR/css-inline-3/#propdef-line-fit-edge) and [line-height](https://www.w3.org/TR/css-inline-3/#propdef-line-height). The sizes and positions of child boxes do not influence its [layout bounds](https://www.w3.org/TR/css-inline-3/#layout-bounds) (nor its own logical height, for that matter, see [inline-sizing](https://www.w3.org/TR/css-inline-3/#propdef-inline-sizing))."

How can the layout bounds contribute to the height of the line box solely based on an inline box's `line-height` and yet be inflated by margin, border, and padding when `line-fit-edge` is not `leading`? If layout bounds are defined only by the text metrics of the inline box, how do padding/border/margin not directly affect the line box height?

**Comment by gitspeaks** [comment]
Additionally, your response does not address the core issue: clarifying the relationship between anonymous block boxes and inline element boxes. Specifically, the specification does not provide any details about how anonymous block boxes interact with line boxes.

**Comment by faceless2** [comment]
> Specifically, the specification does not provide any details about how anonymous block boxes interact with line boxes.

It does, and I know this because when we read the specification it gave us enough information to implement it. CSS layout is complex, but this is the wrong forum to learn about it.
