### ISSUE TITLE
[css-color-hdr] Example of dynamic-range-limit use seems to require inheritance

### ISSUE THREAD

**Issue by jyasskin** [w3c/csswg-drafts#11345]
https://drafts.csswg.org/css-color-hdr/#the-dynamic-range-limit-property says that `dynamic-range-limit` is not inherited, and the [explainer](https://github.com/ccameron-chromium/hdr-headroom-limit/blob/main/EXPLAINER.md) says

> A non-goal of this proposal is to provide a mechanism through which a maximum brightness of HDR content can be enforced on child elements of a given element.

but the [example](https://drafts.csswg.org/css-color-hdr/#ex-hdr-limit-photogrid) uses 

```css
body { dynamic-range-limit: standard; }
```

which seems like it would only work if the property is inherited or it applies to all colors in children.

**Comment by ccameron-chromium** [comment]
The WPT tests assume inherited. Sorry, I didn't notice the difference with the spec. Do you think it makes sense to change the spec to be inherited?

**Comment by svgeesus** [comment]
Fixed by https://github.com/w3c/csswg-drafts/pull/11350
