### ISSUE TITLE
[css-color-hdr] Time for FPWD

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#11344]
CSS Color HDR been [adopted](https://drafts.csswg.org/css-color-hdr/#controlling-dynamic-range), per [CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/9306#issuecomment-1864864440), and also @ccameron-chromium  [has asked for TAG review](https://github.com/w3ctag/design-reviews/issues/1027) of the dynamic range limit functionality, where we read:

> Aiming for Chrome 133 (early January)

so despite there (of course) being some [open issues](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-color-hdr) it seems time to publish a FPWD.

@astearns might be async?

**Comment by svgeesus** [comment]
There are [some WPT tests](https://wpt.fyi/results/css/css-color-hdr?label=experimental&label=master&aligned) and Chrome 133 /Edge 133 pass 100%

**Comment by svgeesus** [comment]
Noting that the last day to request publication is Tues 17 (to be published Thurs 19 Dec) before the publishing moratorium.

**Comment by svgeesus** [comment]
Publication requested 11 Dec, expected 17 Dec 2024

**Comment by annevk** [comment]
No objection to publishing a WD, but shipping seems a bit concerning given issues such as #11307 are not addressed?

**Comment by svgeesus** [comment]
@annevk  agree wrt shipping

**Comment by svgeesus** [comment]
[Published 17 Dec](https://www.w3.org/TR/css-color-hdr-1/)
