### ISSUE TITLE
[selectors-4] About shadow-including descendants

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1135]
For three pseudo-classes ([`:hover`](https://drafts.csswg.org/selectors-4/#the-hover-pseudo), [`:active`](https://drafts.csswg.org/selectors-4/#the-active-pseudo) and [`:focus-within`](https://drafts.csswg.org/selectors-4/#the-focus-within-pseudo)) the spec has a similar text:
> An element also matches :hover if one of its shadow-including descendants matches :hover.

The reference to [*shadow-including descendants*](https://dom.spec.whatwg.org/#concept-shadow-including-descendant) was [introduced back in April 2016 by @tabatkins](https://github.com/w3c/csswg-drafts/commit/eb5e7c1b1546305bda16c6b531bc369de4bc0c81).

However it seems it doesn't match the behavior in either Chrome and Safari.
Using an example from @rune-opera:
```html
  <div id="host">
    <span>Hover me</span>
  </div>
  <script>
    host.attachShadow({mode:"open"}).innerHTML = "<style>#shadowDiv:hover { border: 5px solid green }</style><div id='shadowDiv'><slot></slot></div>";
  </script>
```

In both Blink and WebKit a green border appears on the `shadowDiv` when you hover the `<span>`. This seems the right behavior from the user point of view.
However, the `<span>` is not a shadow-including descendant of the `shadowDiv`. Shouldn't the spec mention the *[flat tree](https://drafts.csswg.org/css-scoping/#flat-tree)* instead?

This discussion started on the [`blink-dev` thread about `:focus-within`](https://groups.google.com/a/chromium.org/d/msg/blink-dev/V3RNBhQelSg/nGRIWjy6CgAJ).

**Comment by rune-opera** [comment]
Note that the Blink implementation walks the layout tree for :hover/:active, not the flat tree, so there can be subtleties.

I've reported https://crbug.com/705984 for display:contents. Firefox also has an invalidation problem with :hover and display:contents https://bugzilla.mozilla.org/show_bug.cgi?id=1351339

**Comment by rune-opera** [comment]
cc editors @tabatkins @fantasai

**Comment by tabatkins** [comment]
Hm, I didn't realize that "shadow-including descendants" doesn't include that case.  That's annoying.  The intention is definitely that they run on the flat tree.

**Comment by tabatkins** [comment]
Suggested edit (for all of the relevant classes, and fixing #1141 too):

> An element also matches '':hover'' 
> if one of its descendants in the <a>flat tree</a>
> (including non-element nodes, such as text nodes)
> matches the above conditions.

Sound good?

**Comment by mrego** [comment]
Yeah, it sounds good. Thanks @tabatkins!

**Comment by mrego** [comment]
So this has just been fixed by @tabatkins at https://github.com/w3c/csswg-drafts/commit/9d0024d535aed8e8d93e0e651b574458ca95aa46

Thanks!
