### ISSUE TITLE
[CSS Writing Modes] The initial value for "direction" is misleading

### ISSUE THREAD

**Issue by schenney-chromium** [w3c/csswg-drafts#11402]
The initial value for [direction](https://drafts.csswg.org/css-writing-modes/#direction) is 'ltr', but that is not what happens in Chromium, WebKit or Gecko. All of those will report the document's HTML [dir](https://html.spec.whatwg.org/multipage/dom.html#the-dir-attribute) attribute value in getComputedStyle(). Obviously if the CSS `direction` is not set but the HTML `dir` is given then HTML will define the rendering.

The motivation for clarifying this in the CSS Writing Modes spec is to have an accurate reference for the behavior of the HTML [CanvasTextDrawingStyles `direction` IDL attribute](https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-direction). If it is clear that the computed style includes the HTML dir information then the HTML spec can just say "use the computed style direction" which covers all the sub-cases in one go.

I would like to add such information to the spec. Any objections?

**Comment by schenney-chromium** [comment]
Forgot the example:
```html
<!DOCTYPE html>
<html dir="rtl">
  <body>
    <p id="paragraph">What direction is this text?</p>
    <script>
      console.log(getComputedStyle(document.getElementById("paragraph")).direction);
    </script>
  </body>
</html>
```

**Comment by Loirooriol** [comment]
But that's just some UA style. If you add `direction: initial` to your example, then it will be `ltr` indeed.

It's basically the same as the initial value of `display` being `inline`, even though for some elements the UA stylesheet sets `display: block`.

**Comment by schenney-chromium** [comment]
I see, you're pointing me to (https://drafts.csswg.org/css-writing-modes/#bidi-example) where there is already a discussion of this. I suppose I'll just need to write more complicated HTML spec text.

**Comment by Loirooriol** [comment]
For HTML see https://html.spec.whatwg.org/multipage/rendering.html#bidi-rendering
