### ISSUE TITLE
[css-fonts-4][varfont] Over specification of axis wording.

### ISSUE THREAD

**Issue by bungeman** [w3c/csswg-drafts#1142]
https://drafts.csswg.org/css-fonts-4/#propdef-font-variation-settings

Replace
> If the same axis name appears twice, the second one supercedes the first.

with
> If the same axis name appears more than once, the value associated with the last appearance supersedes any previous value for that axis.

or something at least as clear (and doesn't mis-spell 'supercedes').

**Comment by litherum** [comment]
Sounds good to me.

In the future, for small stuff like this, feel free to submit a pull request.
