### ISSUE TITLE
[css-images-3] Move underimplemented features to Images 4

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#1148]
image(): https://drafts.csswg.org/css-images-3/#image-notation

Quick test: http://dabblet.com/gist/33ac15e3d6372b2d97b17061783eb40f
The above tests basic functionality for `image()`, `image-set()`, `cross-fade()`, and parsing for `image-resolution`, `image-orientation`, `image-rendering`.

**Results**
`image()`: None
`image-set()`: WebKit, Blink
`cross-fade()`: WebKit, Blink
`image-resolution`: None
`image-orientation`: Gecko
`image-rendering`: Blink, Gecko, WebKit

Since `image()` has not been implemented in any browser, I think it should be deferred to Images 4, so that Images 3 can move forward. It has been sitting in CR for 5 years, and many of its other features seem to have excellent interoperability (even though they still need tests...).

cc @tabatkins @fantasai

**Comment by fantasai** [comment]
Agreed.

**Comment by tabatkins** [comment]
Sad, but yes, agreed.

**Comment by LeaVerou** [comment]
Excellent, thanks for agenda+ing @fantasai!
In the call, I plan to suggest deferring a few other features with 0-1 implementations:

- `image-set()` and `cross-fade()` seem to have some degree of implementation on Blink & Webkit, though they are not yet considered independent implementations (but should be). Perhaps they can stay.
- `image-orientation` is only recognized by Gecko (and no idea how good their implementation is), so I think it should be deferred.
- `image-resolution` is not even recognized by any UAs I tried, so I think it should be deferred.
- Gradient interpolation is also not implemented anywhere, so I think it should be deferred.

**Comment by yisibl** [comment]
`image-set()` and `cross-fade()` +1

**Comment by LeaVerou** [comment]
From today’s call: 

> RESOLVED: Move everything with no impl to next level and mark everything with 1 impl as at risk.
