### ISSUE TITLE
[css-grid] Automatic Minimum Size for grid items should not min against content size

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1149]
Continuing from https://github.com/w3c/csswg-drafts/issues/1117 examples 1/2/5/6...

Grid is using the same "automatic minimum size" algo that Flexbox does, which sets the min to the smaller of the content size and the specified/transferred size.  This is correct for Flexbox - it gives us a reasonable minimum size that the image won't shrink below.  But it serves a different purpose in Grid, effectively setting the layout size of the *track* while the item itself sizes into that containing block, potentially overflowing it. (Or, in other words, Flexbox actually sizes the item with the information; Grid sizes the track, and then the item lays itself out, and we don't want the item to overflow its track by default.)

Therefore, in Grid it doesn't make as much sense to pay attention to the content size when a specified/transferred size exists. So, we think the right fix is to just change Grid's automatic minimum size to be the specified size if it exists, else the transferred size if it exists, else the content size.

This will make examples 1, 2, 5, and 6 all render basically the same way, with a 200px tall first row, and the image filling that row.  (Examples 3, 4, 7, and 8 rely on a different issue, so we won't worry about them here right now.) This gives more sensible results in size-constrained grids when the item's transferred size is larger than its content size, by keeping the contents of the track in sync and avoiding overlap of adjacent grid items.

Note: A similar consideration about overlapping overflow was used in [resolving issue 283](https://github.com/w3c/csswg-drafts/issues/283#issuecomment-268125974).

The proposed fix is to define the automatic minimum size for grid items inline in the spec as: the specified size if it exists, else the transferred size if it exists, else the content size.

**Comment by mrego** [comment]
It's really nice we're finally having a specific text in Grid Layout spec about *automatic minimum size*. IMHO it was pretty complex to understand the text in Flexbox and how it applies to Grid.

About the proposal to use:
> the specified size if it exists, else the transferred size if it exists, else the content size

On a first sight it looks good, I don't know about specific use cases though. Probably web authors should be the want checking what makes more sense for them.

**Comment by atanassov** [comment]
Here's a relevant existing test case we have. Based on the resolution of this issue I would expect the result of the green image to be 1x2 rectangle or 100px x 200px.

https://test.csswg.org/suites/css-grid-1_dev/nightly-unstable/html/grid-minimum-size-grid-items-007.ht

**Comment by fantasai** [comment]
Edits checked in:

> <ins>The automatic minimum size for a grid item in a given dimension is its specified size if it exists, otherwise its transferred size if that exists, else its content size, each as defined in [CSS-FLEXBOX-1].</ins> However, if the grid item spans only grid tracks that have a fixed max track sizing function, its specified size and content size in that dimension (and the input to the transferred size in the other dimension) are further clamped to less than or equal to the stretch fit the grid area’s size (so as to prevent the automatic minimum size from forcing overflow of its fixed-size grid area).

@mrego Would you mind reviewing to make sure this is all sane, since I can't review my own edits? ;) (I mean, I can, but a different set of eyes would be better.)

**Comment by mrego** [comment]
@fantasai I think the new text looks good.

BTW, I'm fixing this on Blink and WebKit and updating the WPT tests accordingly.
