### ISSUE TITLE
[css-inline] initial-letter size should not depend on number of lines

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#115]
There is a note about the interaction between `initial-letter` and ruby, but I don't think that is the solo case. The height of line can be changed by any inline element, e.g. a span with larger font, or an big inline `<img>`. This indicates that there is actually a cyclic-dependency.

I think it should rely on something computable from CSS values, rather than the layout result. Probably the computed `line-height` value or the "step unit" defined in CSS Step Sizing.

**Comment by astearns** [comment]
@upsuper see section 3.5 - the line-height of the containing block is used, not the height results from layout.

**Comment by upsuper** [comment]
Oh, okay. I didn't read there. It's probably worth a note I guess :)
