### ISSUE TITLE
[css-rhythm] [css-rhythm-1] Intro should list block boxes use-case before line boxes

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1152]
https://drafts.csswg.org/css-rhythm/#intro

Basically switch:
* Adjust heights of line boxes to multiples of the specified length.
* Adjust heights of block-level boxes to multiples of the specified length.

To:
* Adjust heights of block-level boxes to multiples of the specified length.
* Adjust heights of line boxes to multiples of the specified length.

And switch this:

By controlling heights of line boxes, lines of text in different fonts can create consistent visuals to help readability.

Also by stacking such line boxes, authors can align lines across columns, pages, scroll-snapped blocks, or multiple blocks placed absolutely, to produce vertical rhythm.

to (something like) :

By stacking blocks at multiples, authors can align lines across columns, pages, scroll-snapped blocks, or multiple blocks placed absolutely, to produce vertical rhythm.

Also, by controlling heights of line boxes, lines of text in different fonts can create consistent visuals to help readability.

**Comment by kojiishi** [comment]
Looks like an editorial request, assigning to fantasai.
