### ISSUE TITLE
[css-rhythm] [css-rhythm-1] swap order of sections 2 and 3 (Line vs Block)

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1153]
Swap the order of these sections:

https://drafts.csswg.org/css-rhythm/#line-height-step
https://drafts.csswg.org/css-rhythm/#block-height

To at least imply a default preferred implementation order.

Per email from @fantasai:
"my advice would be to implement block height stepping first, since it
will more directly solve most of the use cases. I'm less convinced that
line height stepping is necessary"

**Comment by kojiishi** [comment]
Looks like editorial request, assigning to fantasai.
