### ISSUE TITLE
[css-rhythm] [css-rhythm-1] summarize use-case(s) at start of Adjusting Block-level Box Heights

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1154]
Add a short paragraph to this section https://drafts.csswg.org/css-rhythm/#block-height before the x.1 header about the block-step-size property.

Like:

The most common text rhythm problems are situations that need to be solved with block height
stepping. When paragraph text is interrupted by different content such as illustrations and headings, then the rhythm can be thrown off. These are block-level intrusions into the rhythm and the block step properties are designed to preserve rhythm across such different content.

(text taken from portions of an email by @fantasai )

**Comment by kojiishi** [comment]
Looks like an editorial request, assigning to fantasai.

**Comment by fantasai** [comment]
Thanks for the feedback, @tantek! Rewrote the introduction to incorporate the points above. Let me know if it's as clear as you think it needs to be, or if I should make other improvements.
