### ISSUE TITLE
[css-fonts-4] Open ranges aren't allowed

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#1157]
Tab says:

> Note that open ranges (such as (0, 1000)) aren't allowed in CSS.
> Disallowing 0 is fine, but you have to provide a lower bound, such as
> 1, or define a behavior that handles values that approach 0 (such as a
> UA-defined minimum that values are floored to).  Disallowing 1000 (but
> allowing 999.9999999) isn't allowed.  (This is all per CSS design
> principles; there's nothing that magically disallows this stuff except
> convention).

**Comment by fantasai** [comment]
Why is font weight floored at 1 but width floored at zero?

**Comment by litherum** [comment]
`font-weight` accepts a number, and the `font` shorthand accepts a `<length>` for `font-size`, which can also be `0` (because of unitless 0 lengths) so the grammar would be ambiguous if `font-weight` could accept 0.

`font-width` accepts is a percentage, but `font-size` also accepts a percentage, so the `font` shorthand only accepts the [keyword values to `font-width`](https://drafts.csswg.org/css-fonts-4/#font-stretch-css3-values).

**Comment by litherum** [comment]
Is the explanation satisfactory?

**Comment by tabatkins** [comment]
Works for me.
