### ISSUE TITLE
[css-grid] Editorial: Grid Area Section 9. not logically consistant with Section 3.3 definition of Grid Area

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1159]
Requesting/suggesting Editorial clarity of spec in Section 9. vs Section 3.3

First sentence of Section 9 seems to suggest that **grid area** is **rectanglar set of grid cells** this is not logically consistent with Section 3.3 second sentence that defines grid area as made up of **one or more adjacent grid cells**.

Please see the links below for the evidence:

[CSS-Grid] **Section 9:** [Placing Grid Items](https://www.w3.org/TR/css3-grid-layout/#placement):

> Every grid item has a "[grid area](https://www.w3.org/TR/css3-grid-layout/#grid-area)", a rectangular **set** of grid **cells** that the grid item occupies

Please click the link "[grid area](https://www.w3.org/TR/css3-grid-layout/#grid-area)" to section 3.3 Grid Areas
[CSS-Grid] **Section 3.3** [Grid Areas](https://www.w3.org/TR/css3-grid-layout/#grid-area):

> A grid area is the logical space used to lay out one or more grid items. A grid area consists of one or more adjecent grid cells.

Just to make the point stronger, please see the definition of [grid cell](https://www.w3.org/TR/css3-grid-layout/#grid-cell):

> A grid cell is the intersection of a grid row and a grid column. It is the smallest unit of the grid that can be referenced when positioning grid items.

So if [grid cell](https://www.w3.org/TR/css3-grid-layout/#grid-cell) is the smallest unit of the grid that can be referenced when positioning grid items and a [grid area](https://www.w3.org/TR/css3-grid-layout/#grid-area) is consists of one or more adjacent grid cells, then section 9 assertion an grid area is a rectangular set of grid cells that the grid item occupies should be reworded in some manner that is closer to 3.3 definition of [grid area](https://www.w3.org/TR/css3-grid-layout/#grid-area).

I would suggest the correction be something like:

_Every grid item has a grid area, a rectangular region of one [grid cell](https://www.w3.org/TR/css3-grid-layout/#grid-cell) or multiples adjacent cells that the grid item occupies._

- added link to grid cell
- removed the word "set" because it suggest two of something in the css grid spec most of the time
- used the word "region' because it would work naturally with section 7.3 note (just above example 20)
- the word "cells" now absolutlly means ---more then one cell

We all learn by sharing what we know
Robert A. DiBlasi

**Comment by tabatkins** [comment]
All right, @fantasai made some tweaks to make section 3 a little bit clearer.

In general, tho, the two sections are not inconsistent. They're saying similar things in two different ways, and at slightly different levels of detail; that's okay, and often useful for learning.  We're also using "set" correctly here; it doesn't imply two or more, just a collection (which can be just a single item).
