### ISSUE TITLE
[css-values] Ambiguities with 0 valid for all dimensions

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#1162]
**animation example**

With the recent decision that 0 is a valid value for all dimensions, the following changes meaning:

    `animation: 1s 0;`

The 0 would previously have been interpreted as iteration count.

Now it is interpreted as animation-delay, so the iteration count remains 1.

https://drafts.csswg.org/css-animations/#animation

`<single-animation> = <time> || <single-timing-function> || <time> || <single-animation-iteration-count> || ...
`
"Note that order is important within each animation definition: the first value in each `<single-animation>` that can be parsed as a `<time>` is assigned to the animation-duration, and the second value in each `<single-animation>` that can be parsed as a `<time>` is assigned to animation-delay."

**offset example**

With the recent decision that 0 is a valid value for all dimensions,

`    offset: ray(180deg) 0;`

becomes ambiguous: 0 is a valid value for both offset-distance and offset-rotate.

offset-rotate is either 0 or auto.

https://drafts.fxtf.org/motion-1/#offset-shorthand

`Value: ... <offset-path> [ <offset-distance> || <offset-rotate> ]? ...`

**Comment by tabatkins** [comment]
We didn't decide 0 was valid for all dimensions (unless I'm remembering wrong) - just lengths and angles.

That said, the 'offset' problem is definitely still valid.

(I really, *really* hate that the group resolved this way.  Much better to keep the unitless-0 limited to lengths, with the few angle exceptions explicitly called out as exceptions.  Maybe we can get this reversed, with evidence that it's causing grammar problems.)

**Comment by tabatkins** [comment]
Agenda+ to discuss the above - generic "angles can have unitless 0 too" resolution is causing grammar problems. Can we revisit the decision?

**Comment by LeaVerou** [comment]
From today’s call:

> RESOLVED: Only spec the unitless 0 quirk for transforms & gradients

**Comment by tabatkins** [comment]
And edits done to V&U, Images, and Transforms.

**Comment by yisibl** [comment]
https://github.com/w3c/csswg-drafts/commit/602789171429b2231223ab1e5acf8f7f11652eb3

**Comment by yisibl** [comment]
What about  `conic-gradient()` and `filter: hue-rotate()`? Chrome also support `filter: hue-rotate(0)`.

**Comment by ewilligers** [comment]
I have added use counters to Blink. We will know in three months how often unitless 0 is being used in gradients and filter and transform.
