### ISSUE TITLE
2017 Paris f2f dates - can we decide exactly?

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1165]
https://wiki.csswg.org/planning in Upcoming says Aug 1-4 in Paris for f2f.

Could we decide on the exact dates so we can start travel and venue planning/logistics?

cc: @jetvillegas

**Comment by frivoal** [comment]
+1 for deciding quickly.

I'll be around anyway, so any date is fine, but I still need to arrange accommodation, so firm dates are good.

**Comment by FremyCompany** [comment]
I thought those dates were final already.

**Comment by frivoal** [comment]
As far as I remember, we decided on 3 days within August 1-4, but not on whether it would be 1-3 or 2-4. Do I misremember?

**Comment by astearns** [comment]
That's basically what I recall. The fourth day would be a Houdini meeting if it would be useful.

**Comment by fantasai** [comment]
Houdini August 1, CSSWG 2-4.
