### ISSUE TITLE
[css-text-3] Very old Unicode document references

### ISSUE THREAD

**Issue by littledan** [w3c/csswg-drafts#1169]
CSS text level 3 refers to versions of UAX 11, 14, 24 and 29 from more than 10 years ago. This was confusing for me when I was reading the spec and trying to cross-reference the appropriate Unicode document. OTOH CSS cross-references the latest Unicode. The latest versions can be found at the parent directory of the links provided now, e.g., http://www.unicode.org/unicode/reports/tr11/ .

**Comment by frivoal** [comment]
@tabatkins @plinss @tobie I believe this is a tooling issue, as these links are autogenerated based on the name of the spec only, without asking for a specific version. It seems the database backing that up is wildly out of date for these specs. How do we get that up to date?

**Comment by tobie** [comment]
You can just update them here in https://github.com/tobie/specref/blob/master/refs/biblio.json

**Comment by frivoal** [comment]
I thought this was somehow automated. It's not, and we can just send pull requests to update old things without later being overridden my some regeneration of the file from automated sources?

**Comment by tobie** [comment]
It's only automated for resources coming from IETF, W3C and WHATWG for now. That said, if you want to write a script to automatically fetch all Unicode resources… happy to point you in the right direction.

**Comment by tobie** [comment]
If not, just fix these resources manually in biblio.js and you should be fine. 

Note however that there a temporary cert issue with Bikeshed and Specref, so you won't get the updates in Bikeshed until @tabatkins wakes up and fixes all the things.

**Comment by frivoal** [comment]
What's the best way to deal with http://www.unicode.org/reports/tr21/tr21-5.html? the latest version link points to http://www.unicode.org/reports/tr21/, a document that explains that the material has been incorporated into the Core Specification of the Unicode Standard.

Is there a way to mark the reference as superseded in specref? What should it be made to point to?

**Comment by frivoal** [comment]
Same problem for http://www.unicode.org/unicode/reports/tr27/tr27-4.html

**Comment by frivoal** [comment]
Automation would be good. In the meanwhile: https://github.com/tobie/specref/pull/345

**Comment by tobie** [comment]
> Is there a way to mark the reference as superseded in specref?

There's two ways to do that. Either [use `aliasOf`](https://github.com/tobie/specref/blob/c78aab79b09b10b6d75d8062413849c92fad978c/refs/biblio.json#L24-L26), which is radical but works. Or you can use [`obsoletedBy`](https://github.com/tobie/specref/blob/master/schemas/reference.json#L141-L144) which I don't think clients rely on at all.

> What should it be made to point to?

Probably the latest and greatest reference, unless you need to keep a copy of the old one around because you're referencing something specifically about _that_ document, vs. its content.

**Comment by frivoal** [comment]
@tobie 
Updating to the latest standalone version of the document, then adding obsoletedBy sounds like the right thing to do. But we should also teach clients to deal with that. I'll ping Tab for bikeshed, can you poke at others?

**Comment by tobie** [comment]
Why don't you create an issue for that in specref directly? Seems like there's a bunch of things to discuss and get buy in from ReSpec/Bikeshed before moving forward with this.

**Comment by frivoal** [comment]
https://github.com/tobie/specref/issues/347

**Comment by frivoal** [comment]
Closing this issue, as the links are now updated thanks to https://github.com/tobie/specref/pull/345
