### ISSUE TITLE
[css-text-decor] default position for text-decoration-line in vertical text

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1178]
2.1. Text Decoration Lines: the text-decoration-line property
https://drafts.csswg.org/css-text-decor-3/#text-decoration-line-property

This section should probably mention that the actual position of an underline or overline is determined by the current setting of text-underline-position. This is particularly relevant for vertical text, where the line may be drawn on either side of the vertical line, depending on the setting of that property, or in the case of `auto`, of the browser default (which may vary for ja vs zh).

**Comment by fantasai** [comment]
Fixed by adding some notes in https://github.com/w3c/csswg-drafts/commit/08e7b14e6c7a818b27fe6471d068f3dfd4cb51ec . Let me know if these are adequate? I'm happy to take suggestions for improvement. :)

**Comment by r12a** [comment]
LGTM
