### ISSUE TITLE
[css-ruby][css-display] Are ruby containers atomic? Specs contradict

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1180]
CSS Display defines [atomic inline](https://drafts.csswg.org/css-display/#atomic-inline) as

> An inline-level box that is replaced or that establishes a new formatting context

An element with `display: ruby` has the [`inline` outer display role](https://drafts.csswg.org/css-display/#valdef-display-inline), so

> The element generates an inline-level box.

, and has the [`ruby` inner display layout model](https://drafts.csswg.org/css-display/#valdef-display-ruby), so

> The element generates a principal ruby container box, and establishes a ruby formatting context.

Therefore, `display: ruby` should produce an atomic inline box according to CSS Display.

However, [CSS Ruby](https://drafts.csswg.org/css-ruby-1/#formatting-context) explicitly says otherwise:

> Ruby containers are non-atomic inline-level boxes.

**Comment by SelenIT** [comment]
Yes, the ruby formatting context appears to be an exception from the general rule that the inline-level box that establishes a new formatting context is usually atomic. Ruby containers can [break between lines](https://drafts.csswg.org/css-ruby-1/#line-breaks), so they are definitely non-atomic.

I suppose that the CSS Display spec should be changed to something like
> An inline-level box that is replaced or that establishes a new block, flexbox, grid, or table formatting context

An inline-level element can't establish the inline formatting context, and establishing ruby formatting context doesn't make an inline-level box atomic. If new formatting contexts that make inline-level boxes atomic appear in the future, they should be explicitly added to that list.

**Comment by fantasai** [comment]
Ruby containers are weird... they establish a new ruby formatting context, but their content also participates in their parent's inline formatting context. That's going to be odd to explain. :) I'd rather call out ruby as an exception than list out the things that aren't exceptional though.

**Comment by fantasai** [comment]
Okay, this should be fixed now. Let me know if you have an further improvements to suggest on this point.
