### ISSUE TITLE
[css-display] Block containers can also establish an inline formatting context

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1185]
From [CSS 2.1](https://www.w3.org/TR/CSS2/visuren.html#block-boxes),

> A block container box either contains only block-level boxes or establishes an inline formatting context and thus contains only inline-level boxes.

That disappeared from CSS Display. It defines [block container](https://www.w3.org/TR/css-display-3/#block-container) as

> A box whose contents participate in a block formatting context.

But if the box container only contains inline-level boxes, the box container will establish an inline formatting context, and the inline-level boxes will then participate in an inline formatting context, not in a block formatting context. In fact, that's what inline-level boxes do by definition, they participate in an inline formatting context.

**Comment by fantasai** [comment]
@Loirooriol Okay, we've rewritten the definition of “block container” to be, hopefully, more correct with regard to CSS2.1. Please take a look and let us know if it seems alright? :)
  https://drafts.csswg.org/css-display/#block-container

**Comment by Loirooriol** [comment]
Yes, much better :) Maybe I would mention `display` itself in the examples of properties which can make a block container establish a BFC, now that we have `flow-root`. And I would move the note into the definition of block box, and say that, in a similar way, not all block-level boxes are block container boxes.

**Comment by fantasai** [comment]
> Maybe I would mention display itself in the examples of properties which can make a block container establish a BFC, now that we have flow-root.

It's not an exhaustive list, so I would like to continue not pretending to be one. :)

> And I would move the note into the definition of block box

Done.
