### ISSUE TITLE
[css-syntax-3] typo in #tokenizing-and-parsing

### ISSUE THREAD

**Issue by prlbr** [w3c/csswg-drafts#1190]
“Certain points in the parsing algorithm are said to be **a** parse error**s**.”

It should be either plural or singular, shouldn’t it?
https://drafts.csswg.org/css-syntax/#tokenizing-and-parsing

**Comment by xfq** [comment]
I think so.

(The "a" was introduced in commit 94fc7d64c7b894f195bcd4a787d222d83c62f0c7 in 2013.)

**Comment by tabatkins** [comment]
Should be plural. Fixed, thanks.
