### ISSUE TITLE
[cssom-view] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1194]
[Bikeshed has a feature to include CanIUse info panels in specs.](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels)

I'm wondering if CSSOM View would like to use this feature? Here are the spec anchors and corresponding CanIUse features for CSSOM View:

| Spec URL | CanIUse URL |
| ------------- | ------------- |
| https://drafts.csswg.org/cssom-view/#dom-document-elementfrompoint     | http://caniuse.com/#feat=element-from-point |
| https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect | http://caniuse.com/#feat=getboundingclientrect |
| https://drafts.csswg.org/cssom-view/#dom-element-scrollintoview        | http://caniuse.com/#feat=scrollintoview |
| https://drafts.csswg.org/cssom-view/#dom-window-devicepixelratio       | http://caniuse.com/#feat=devicepixelratio |
| https://drafts.csswg.org/cssom-view/#dom-window-matchmedia             | http://caniuse.com/#feat=matchmedia |
| https://drafts.csswg.org/cssom-view/#propdef-scroll-behavior           | http://caniuse.com/#feat=css-scroll-behavior |

**Comment by zcorpan** [comment]
Thanks, added all but `css-scroll-behavior` in https://github.com/w3c/csswg-drafts/commit/91581486a0adee8fb34960059d460327b0ee1c45, blocked on https://github.com/tabatkins/bikeshed/issues/974

**Comment by cvrebert** [comment]
Thank you!
