### ISSUE TITLE
[css-values] Can <resolution> values be negative?

### ISSUE THREAD

**Issue by alancutter** [w3c/csswg-drafts#1196]
https://drafts.csswg.org/css-values/#resolution

The definition for the <resolution> does not exclude negative values. It would be good to clarify this as intentional if it is.

**Comment by frivoal** [comment]
I don't think the definition of the unit should have anything to say about negative values. That should be handled in the definition of the properties (and descriptors) that accept resolution values.

**Comment by alancutter** [comment]
That sounds reasonable.
