### ISSUE TITLE
Update Twitter bot to include links to GitHub commits

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#120]
Could you update https://twitter.com/CSScommits, so that it includes links to the GitHub commit instead of hg.csswg.org? For example, link to https://github.com/w3c/csswg-drafts/commit/e045549b2c9eeb32f8eadc8133da2032608a055b instead of https://hg.csswg.org/drafts/rev/dcf65922dc5c.

The diff highlighting on GitHub is better because it shows you which specific parts of a line have been added/removed.

**Comment by frivoal** [comment]
Also, this may not have been true when https://twitter.com/CSScommits was created, but github now has twitter integration, and setting this up is trivial.
Someone with the right access rights for github and twitter should go to https://github.com/w3c/csswg-drafts/settings/hooks/new?service=twitter, fill in the credentials for https://twitter.com/CSScommits, and we're done.

**Comment by tabatkins** [comment]
I've got the Twitter rights (and am pinging mathias to turn off the Hg bot), and am attempting to either obtain the repo rights or find someone who has them.

**Comment by plinss** [comment]
I have the access on GitHub to do this, but I don't have the CSScommits credentials...

**Comment by tabatkins** [comment]
Yay for crossing in-flight! Pinging plinss on IRC. ^_^

**Comment by plinss** [comment]
GitHub connected to twitter, just need the hg feed turned off so we don't get duplicates

**Comment by tabatkins** [comment]
Should be turned off; I revoked access for the bot that pipes a blog into twitter, which I presume was just pointed at the Hg RSS feed.

Closing unless further issues come up.
