### ISSUE TITLE
[css-ui] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1200]
[Bikeshed has a feature to include CanIUse info panels in specs](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels). ([Example](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect))

I'm wondering if CSS Basic UI would consider using this feature? Here are the spec anchors and corresponding CanIUse features for CSS Basic UI (ignoring the `cursor` features due to ambiguity):

| Spec URL | CanIUse URL|
|----------|------------|
| https://drafts.csswg.org/css-ui-4/#appearance-switching | http://caniuse.com/#feat=css-appearance |
| https://drafts.csswg.org/css-ui/#box-sizing | http://caniuse.com/#feat=css3-boxsizing |
| https://drafts.csswg.org/css-ui/#resize | http://caniuse.com/#feat=css-resize |
| https://drafts.csswg.org/css-ui-4/#text-overflow | http://caniuse.com/#feat=text-overflow |
| https://drafts.csswg.org/css-ui-4/#valdef-user-select-none | http://caniuse.com/#feat=user-select-none |

**Comment by frivoal** [comment]
Seems reasonable. I don't think I've seen it much in other css specs, but unless someone comes up with a good reason why doing this is bad somehow, I'll probably do so.

**Comment by LeaVerou** [comment]
Huge thumbs up for this! That would be fantastic!
