### ISSUE TITLE
[css-fonts-4] incorporate css-font-display draft into css-fonts-4

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1201]
We apparently [had a resolution](https://lists.w3.org/Archives/Member/w3c-css-wg/2017JanMar/0090.html) to take Tab's [css-font-display](https://tabatkins.github.io/specs/css-font-display/) to FPWD, although I can't find the resolution in any minutes (although I do vaguely remember it).

Then we had an [agenda item](https://lists.w3.org/Archives/Public/www-style/2017Feb/0067.html) that included, instead, possibly including it in fonts-4.

The [minutes of the discussion of that item](https://lists.w3.org/Archives/Public/www-style/2017Feb/0088.html) don't seem to include discussion of that topic or any resolution on it.

It seems like we should have a resolution one way or the other so that the font display feature can make progress, since my understanding is that it already has 2 disabled implementations (Gecko and I think Chromium) that are waiting for spec progress to enable the code.

/cc @tabatkins @upsuper

**Comment by kojiishi** [comment]
+KenjiBaheux

**Comment by kojiishi** [comment]
@KenjiBaheux

**Comment by litherum** [comment]
I plan to incorporate it into fonts-4 very soon. I don't think this needs a resolution.

**Comment by litherum** [comment]
Relatedly, there is already an agenda item for taking fonts-4 to FPWD at the F2F. I plan to incorporate it before the F2F, so the FPWD would include font-display.
