### ISSUE TITLE
[cssom-view] "static DOMRect"

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1202]
https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect

> If the *list* is empty return a **static** `DOMRect` object

What precisely does "static" mean here? Neither CSSOM View nor Geometry Interfaces seems to define staticness, either generally or in relation to `DOMRect` specifically. And the [WebIDL `static` keyword](https://heycam.github.io/webidl/#dfn-static-attribute) doesn't seem applicable here.

Perhaps `DOMRectReadOnly` was intended?

**Comment by zcorpan** [comment]
It means not [live](https://html.spec.whatwg.org/#live). I can clarify...

**Comment by cvrebert** [comment]
@zcorpan Are live `DOMRect`s a thing, or are the "not live" notes just for the avoidance of doubt?

**Comment by zcorpan** [comment]
I think there aren't any live DOMRects, but there could be. (DOMQuad used to have a live `bounds` attribute.)
