### ISSUE TITLE
[css-fonts-4] Add font-language-override descriptor

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1203]
There should be a font-language-override descriptor in addition to a property.

There was [a thread](https://lists.w3.org/Archives/Public/www-style/2017Feb/thread.html#msg28) on www-style started by @jfkthame with a bunch of useful detail and discussion in it, but I couldn't find a github issue.

I'm tagging this as css-fonts-4 under the assumption that the font-language-override property is likely going to get deferred from css-fonts-3 because it has only one implementation (I think).  If that's not the case, we should check implementations of the descriptor as well, since font-language-override as a descriptor is implemented in Gecko.

**Comment by litherum** [comment]
Duplicate of https://github.com/w3c/csswg-drafts/issues/1392
