### ISSUE TITLE
[cssom-view] CSS pixels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1204]
https://drafts.csswg.org/cssom-view/#css-pixels

> All coordinates and dimensions for the APIs defined in this specification are in **CSS pixels**, unless otherwise specified.

Shouldn't this section reference https://drafts.csswg.org/css-values/#px (or similar) for the normative definition of a CSS pixel?

**Comment by zcorpan** [comment]
Thanks 👍
