### ISSUE TITLE
[css-grid] 2.4.1 example reference incorrect informational graphic

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1210]
Hello,

I write to you from a web designer point of view and find the non-normative section of the CSS Grid Layout just as important as the normative

I assume I should use the the  Candidate Recommendation (Feb 9) to point out that section 2.4.1
(https://www.w3.org/TR/css3-grid-layout/#adapting-to-available-space) Example 4.
 says:
```
Two columns:
   *  1. the first sized to content,
   *  2. the second receives the remaining space
   *     (but is never smaller than the minimum size of the board
   *     or the game controls, which occupy this column [Figure 3])
```
[figure 3] has nothing to do with the code in example 4

I believe the the spec should refer to [figure 4] or [figure 5]

I would like to point out...the editor's draft still has this incorrect too as April 12 2017.
The relevant section in editors draft is: Section 1.1.1 Adapting Layouts to Available Space
(https://drafts.csswg.org/css-grid/#adapting-to-available-space)
example 1

Thank you for this wonderful CSS Module is will advance the web in so many way!

Robert DiBlasi
We all learn by sharing what we know

**Comment by fantasai** [comment]
Fixed, thanks!
