### ISSUE TITLE
Spec header should ask file to issue at github

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1213]
From @bzbarsky, from [a www-style thread](https://lists.w3.org/Archives/Public/www-style/2017Mar/0045.html):
> Does the writing-modes spec really have no way to file issues other than the mailing list?  Certainly the header claims so.  :(

Is this something we can fix in bikeshed?

**Comment by kojiishi** [comment]
@tabatkins

**Comment by bzbarsky** [comment]
@dbaron fixed this already, after that thread.

**Comment by dbaron** [comment]
Fixed in:
* https://hg.csswg.org/drafts/rev/e7064dca3c6f
* https://hg.csswg.org/drafts/rev/2fe47b543fd2
* https://hg.csswg.org/drafts/rev/6204d8b73221
* https://hg.csswg.org/drafts/rev/3576c5f95707
