### ISSUE TITLE
[cssom-view] CSS pixel nitpicks

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1214]
* The following two definitions mention "number of pixels", but presumably should say "number of CSS pixels" to be precise:
  * https://drafts.csswg.org/cssom-view/#dom-window-screenx
  * https://drafts.csswg.org/cssom-view/#dom-window-screeny
* https://drafts.csswg.org/cssom-view/#set-up-browsing-context-features
  * Steps 7.3.2 and 8.3.2 mention "CSS pixels of target" but neglect to hyperlink the term "CSS pixels".

**Comment by zcorpan** [comment]
Thanks!
