### ISSUE TITLE
[css-images] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1215]
[Bikeshed has a feature to include CanIUse info panels in specs](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels). ([Example](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect); [Example commit](https://github.com/w3c/csswg-drafts/commit/91581486a0adee8fb34960059d460327b0ee1c45))

I'm wondering if css-images would consider using this feature? Here are the spec anchors and corresponding CanIUse features for css-images:

| CSS spec URL(s) | CanIUse feature URL | Level |
|---|---|---|
| https://drafts.csswg.org/css-images-4/#element-notation    | http://caniuse.com/#feat=css-element-function | 4 |
| https://drafts.csswg.org/css-images-4/#cross-fade-function <br>https://drafts.csswg.org/css-images/#cross-fade-function | http://caniuse.com/#feat=css-cross-fade | 3 |
| https://drafts.csswg.org/css-images-4/#image-set-notation <br>https://drafts.csswg.org/css-images/#image-set-notation  | http://caniuse.com/#feat=css-image-set | 3 |
| https://drafts.csswg.org/css-images-4/#repeating-gradients <br>https://drafts.csswg.org/css-images/#repeating-gradients | http://caniuse.com/#feat=css-repeating-gradients | 3 |
| https://drafts.csswg.org/css-images/#image-orientation | http://caniuse.com/#feat=css-image-orientation | 3 |
| https://drafts.csswg.org/css-images/#valdef-image-rendering-crisp-edges | http://caniuse.com/#feat=css-crisp-edges | 3 |

CC: @LeaVerou

**Comment by LeaVerou** [comment]
Totally up for it, but I want to hear from W3C staff first about whether this would cause any issues with publication. If I get the ok from them, I'll add it asap!

cc @svgeesus

**Comment by svgeesus** [comment]
Can't see how that would cause any issues. Seems like a nice value-add.

**Comment by cvrebert** [comment]
Yay! Thanks.
