### ISSUE TITLE
[selectors] * vs *|* as default "of" sub-selector in :nth-child and friends

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1216]
https://drafts.csswg.org/selectors/#the-nth-child-pseudo
> The CSS Syntax Module [CSS3SYN] defines the An+B notation. If S is omitted, it defaults to `*`.

`*` should probably be `*|*` instead. It’s not the same if the stylesheet has a default namespace declared.

**Comment by fantasai** [comment]
Fixed in 335914453ae1e405f5923c327c6ad0dd62710f54, thanks!
