### ISSUE TITLE
[cssom][all specs defining IDL] Consider USVString instead of DOMString, replacing surrogates with U+FFFD

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1217]
CSSOM uses WebIDL’s `DOMString` type for all string parameters and return values. It corresponds to JavaScript strings: arbitrary sequences of 16-bit code units. These are usually interpreted as UTF-16, but they’re not necessarily well-formed in UTF-16: they can contain [unpaired surrogate code units](https://simonsapin.github.io/wtf-8/#surrogates-code-units). I sometimes call this encoding WTF-16.

(Character encoding decoders never emit surrogates when decoding bytes from the network, even when decoding UTF-16BE or UTF-16LE. So surrogates can’t end up in a string that way, only through JS.)

WebIDL also defines `USVString` which is a Unicode string. (A sequence of Unicode scalar values, excluding surrogate code points.) When [converting to it from a JavaScript string](https://heycam.github.io/webidl/#es-USVString), unpaired surrogate are [replaced with the replacement character U+FFFD](https://heycam.github.io/webidl/#dfn-obtain-unicode).

As far as I know all major browser engines currently use WTF-16 internally, so they preserve unpaired surrogates "by default" when strings go through various browser components where no code is actively looking for those.

In Firefox, we’re working on a new style system ([Stylo, a.k.a. Quantum CSS](https://wiki.mozilla.org/Quantum/Stylo)) where strings are represented with Rust’s native `&str` type. `&str` uses UTF-8 bytes for its in-memory representation of Unicode and guarantees (as part of the type’s contract) that these bytes are well-formed in UTF-8. Unicode designed UTF-8 to specifically exclude surrogate code points, in order to be compatible with (well-formed) UTF-16. As a consequence, well-formed UTF-8 (and `&str`) can not represent all JavaScript strings without some sort of escape sequence mechanism.

Stylo currently replaces unpaired surrogates with U+FFFD when converting JS strings to UTF-8. This is equivalent to defining WebIDL interfaces with `USVString` instead of `DOMString`. This is a deviation from specified and currently-interoperable behavior.

It would be possible to make Stylo preserve surrogates (for example by moving everything to [WTF-8](https://simonsapin.github.io/wtf-8/)). However we’re inclined not to. Preserving surrogates is an historical accident, not a feature. I argue that any occurrence of surrogates in a JS string is likely an error, and coming up with an example where not preserving them in CSSOM makes an observable difference is extremely convoluted. For example:

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5012
```html
<!DOCTYPE html>
<style></style>
<script>
document.documentElement.classList.add('\uD800');
document.styleSheets[0].insertRule('.\uD800:before { content: "Surrogates can be used in class names." }', 0);
document.styleSheets[0].insertRule('.\uD801:before { content: "Surrogates seem to be mapped to U+FFFD." }', 1);
</script>
```

So I would like to propose changing CSSOM and other CSS specifications that declare WebIDL interfaces to use `USVString` instead of `DOMString`. This makes CSS syntax “Unicode-clean”, and enable implementations to use UTF-8 internally.

CSSWG discussed and rejected [in 2014](https://lists.w3.org/Archives/Public/www-style/2014Jun/0060.html) a proposal that was effectively the same. However neither `USVString` nor Stylo existed at the time. What has changed is that WebIDL now gives us the tool to easily specify this change, and one major implementation is on a path to likely to make this change.

**Comment by zcorpan** [comment]
Shouldn't the test be `\uFFFD:before`?

**Comment by hsivonen** [comment]
Additional note about `&str` for CSS WG members who don't program in Rust yet:

Since `&str` is the Rust native way of looking at text, being able to use it is very valuable. It means that the style system can call into other Rust code built with the usual Rust assumptions about in-memory data that has textual interpretation.

Preserving unpaired surrogates would mean giving up on the Rust native way of representing in-memory textual data and fighting the Rust ecosystem when it comes to calling into other code, etc.

**Comment by SimonSapin** [comment]
@zcorpan, hmm you’re right. New test case:

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5022
```html
<!DOCTYPE html>
<style></style>
<script>
document.documentElement.classList.add('\uD800');
document.styleSheets[0].insertRule('@media all { \
:root.\uD800:not(.\D801):not(.\uFFFD):before { content: "Surrogates seem to be preserved." } \
:root:not(.\uD800):not(.\uFFFD):before { content: "Surrogates seem to be mapped to U+FFFD in CSSOM but not in DOM." } \
:root.\uD801:before { content: "Surrogates seem to be mapped to U+FFFD in both CSSOM and DOM." } \
}', 0);
</script>
```

(The "both" case is Servo.)

**Comment by svgeesus** [comment]
Unpaired surrogates can only happen when injected by badly-written (or, maybe, malicious?) scripts. There is no actual use case for having them, and being required to preserve them is unfortunate. We should take this opportunity to dump them.

**Comment by tabatkins** [comment]
Per <https://heycam.github.io/webidl/#idl-USVString>, DOMString is meant to be preferred unless there's a good reason to need only scalar values.

In the previous discussion, the major argument against making CSS Unicode-clean was the perf impact of the extra scanning step required. Is that still valid?

**Comment by SimonSapin** [comment]
That advice is debatable: https://github.com/heycam/webidl/issues/84

The performance impact is non-zero for implementations that use WTF-16 internally. (Though I don’t know how significant it is.) In 2014 when all vendors at the table were in that case, “Unicode is nicer” by itself was not a good enough reason. However Stylo is now coming to Firefox, hopefully shipping in November 2017. It currently uses UTF-8 without surrogates internally, and given the trade-off (no use case & low estimated web-compat risk v.s. internal API compat issues of using a different string type) this is unlikely to change before shipping. I want at least to give heads up to the WG that Firefox will likely deviate from currently-interoperable behavior.

**Comment by SimonSapin** [comment]
As far as I can tell a new WebIDL type needs to be defined in WebIDL, so I filed https://github.com/heycam/webidl/pull/347

**Comment by SimonSapin** [comment]
TIL WebIDL has `typedef`.

**Comment by zcorpan** [comment]
We can't use a union type of `DOMString or USVString` because they are both string types and union types must be [distinguishable](https://heycam.github.io/webidl/#dfn-distinguishable).

But we can typedef to only `USVString` and say in prose that it is conforming to use `DOMString` instead (or vice versa).

**Comment by foolip** [comment]
As an FYI, `typedef USVString CSSOMString` made its way into web-platform-tests in https://github.com/w3c/web-platform-tests/pull/6982, and just like an implementation the IDL can only say one thing here, not "this *or* that." Fortunately idlharness.js doesn't automatically exercise the difference between DOMString and USVString and actually can't because one needs to understand the API under test to know where the converted string ends up to read it back.

And this does mean that tests like https://github.com/w3c/web-platform-tests/blob/master/html/dom/usvstring-reflection.html will be impossible to add for CSSOM.
