### ISSUE TITLE
[css-counter-styles] additive-symbols of the same weight

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1220]
https://drafts.csswg.org/css-counter-styles/#additive-tuple
> Each entry in the additive-symbols descriptor’s value defines an additive tuple, which consists of a counter symbol and a non-negative integer weight. Each weight must be a non-negative integer, and the additive tuples must be specified in order of descending weight; otherwise, the @counter-style is invalid and must be ignored.

* This doesn’t say what to do with multiple additive tuples of the same declaration have the same weight, which doesn’t make sense in the algorithm. Since the syntax requires tuples to be in order, it could also reject that case. Firefox does this. The spec should make this explicit.
* This bit of spec says that negative integers or out of order tuples make *the entire rule* invalid, not just the descriptor declaration. This is highly unusual, compared to other descriptors/properties in `@counter-style` or other types of rules. This makes a difference because there could be multiple `additive-symbols` declarations, where an invalid latter one would could the earlier one to be used. This can be useful as a fallback mechanism for using a new feature not implemented everywhere. I think “the @counter-style is invalid” here should be changed to “the declaration is invalid”. Firefox only makes the declaration invalid.

CC @upsuper

**Comment by tabatkins** [comment]
I agree with both of these suggestions.

**Comment by tabatkins** [comment]
Okay, fixing the first by saying "*strictly* descending weight", which rules out same-value tuples.

Fixing the second by switching it to invalidating the declaration only, and making it clear earlier in the spec that you take the last valid instance of each declaration.
