### ISSUE TITLE
[mediaqueries] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1224]
[Bikeshed has a feature to include CanIUse info panels in specs](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels). ([Example](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect); [Example commit](https://github.com/w3c/csswg-drafts/commit/91581486a0adee8fb34960059d460327b0ee1c45))

I wonder if Media Queries would consider using this feature? Here are the spec anchors and corresponding CanIUse features for Media Queries:

| CSS spec URL(s) | CanIUse feature URL |
|----|----|
| https://drafts.csswg.org/mediaqueries-3/#resolution <br>https://drafts.csswg.org/mediaqueries/#resolution | http://caniuse.com/#feat=css-media-resolution
| https://drafts.csswg.org/mediaqueries/#mf-interaction | http://caniuse.com/#feat=css-media-interaction
| https://drafts.csswg.org/mediaqueries/#scripting | http://caniuse.com/#feat=css-media-scripting

**Comment by frivoal** [comment]
@astearns @atanassov As this is a WG wide editorial issue that we haven't quite resolved on yet, I'd like to move it to mediaqueries-5, so as not to block progress to CR on the MQ4 spec.

We can still do it for MQ4 as well when the whole WG decides to do it, but I don't think this is useful to hold this against MQ4 as an open issue to be resolved.

OK?

**Comment by cvrebert** [comment]
@frivoal Did https://github.com/w3c/csswg-drafts/issues/1219#issuecomment-295034986 not resolve it sufficiently?

**Comment by frivoal** [comment]
@cvrebert It kind of does. However, bikeshed will generate the caniuse tables regardless of the status of the document, and taking this in an out all the time depending on whether I am publishing an ED or a draft for TR is error prone.

I've just filed an issue for that on bikeshed: https://github.com/tabatkins/bikeshed/issues/1010

In the meanwhile, I'll add the metadata in the spec, but turned off until either @tabatkins adds the feature to bikeshed or the rest of the WG tells me to stop whining and do it anyway :)

**Comment by frivoal** [comment]
Closing this, as I've set the draft to start generating the tables as soon as https://github.com/tabatkins/bikeshed/pull/1012 is merged in bikeshed.
