### ISSUE TITLE
[css-display] list-item syntax does not allow <display-inside>

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1226]
CSS Display says this in [Generating Marker Boxes: the `list-item` keyword](https://drafts.csswg.org/css-display/#list-items):

> If no `<display-inside>` value is specified, the principal box’s inner display type defaults to `flow`.

However, the syntax of `<display-listitem>` does not allow `<display-inside>`, only `flow` or `flow-root`:

>     <display-listitem> = list-item && <display-outside>? && [ flow | flow-root ]?

Yes, `flow` and `flow-root` are `<display-inside>` values, but this seems a coincidence. The spec should say that, in a `<display-listitem>` value, the `flow` and `flow-root` keywords (if any) behave like they do in `<display-inside>`.

**Comment by tabatkins** [comment]
Fixed to refer to "inner display type value" and "outer display type value", so I don't need to repeat the exact values already allowed in the grammar.
