### ISSUE TITLE
[css-display] Do 'contents' and 'none' have an outer display type?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1227]
CSS Display says in [Box Generation: the `none` and `contents` keywords](https://drafts.csswg.org/css-display/#box-generation):

> Elements with either of these values do not have inner or outer display types, because they don’t generate any boxes at all.

However, in [Automatic Box Type Transformations](https://drafts.csswg.org/css-display/#transformations),

> Some layout effects require blockification or inlinification of the box type, which sets the box’s outer display type, if it is not none or contents, to block or inline (respectively).

Which is it, do elements with `display: contents` or `display: none` have an outer display type with that value, or do they have no outer display types?

**Comment by tabatkins** [comment]
Fixed up the latter sentence to call out those values as not generating a box at all, rather than having an outer display type (since outer display types are owned by boxes, which don't exist at all in this case).

**Comment by tabatkins** [comment]
Fixed in f0a279468
