### ISSUE TITLE
[css-display] Can run-in be inserted as child of block which establishes an inline formatting context?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1228]
CSS Display defines [Run-In Layout](https://drafts.csswg.org/css-display/#run-in-layout) as

> A run-in box behaves exactly as an inline-level box, except:
> 
>  - If a run-in sequence is immediately followed by a block box that does not establish a new formatting context, it is inserted as direct children of the block box [...]
>  - Otherwise, an anonymous block box is generated around the run-in sequence and all immediately following inline-level content (up to, but not including, the next run-in sequence, if any).
>  - A run-in box with a flow inner display type inlinifies its contents. 

The following example is provided:

> 
> ```html
> <dl class='dict'>
>   <dt>dictionary
>   <dd>a book that lists the words of a language in alphabetical
>       order and gives their meaning, or that gives the equivalent
>       words in a different language.
>   <dt>glossary
>   <dd>an alphabetical list of terms or words found in or relating
>       to a specific subject, text, or dialect, with explanations; a
>       brief dictionary.
> </dl>
> ```
> ```css
> .dict > dt {
>   display: run-in;
> }
> .dict > dt::after {
>   content: ": "
> }
> ```
> Which is formatted as:
> <pre><b>dictionary:</b> a book that lists the words of a language
> in alphabetical order and explains their meaning.
> 
><b>glossary:</b> an alphabetical list of terms or words found
> in or relating to a specific subject, text, or dialect,
> with explanations; a brief dictionary.
> </pre>

However, the `dd` establishes an inline formatting context according to [CSS 2.1](https://www.w3.org/TR/CSS21/visuren.html#block-boxes):

> A block container box either contains only block-level boxes or establishes an inline formatting context and thus contains only inline-level boxes.

So I think that either the example is wrong and the `dt` should not be inserted inside the `dd`, or that the definition should allow a run-in sequence to be inserted as direct children of a block box which establishes an inline formatting context.

**Comment by fantasai** [comment]
The latter is clearly the only reasonable interpretation. :) This is going to require some tricky wording fixes, though. :/

**Comment by Loirooriol** [comment]
What about adding the word "block"?

> If a [run-in sequence](https://drafts.csswg.org/css-display/#run-in-sequence) is immediately followed by a [block box](https://drafts.csswg.org/css-display/#block-box) that does not establish a new [block formatting context](https://drafts.csswg.org/css-display/#block-formatting-context) [...]

**Comment by fantasai** [comment]
There's also flex and grid formatting contexts... so really we need to exclude inline. :)

**Comment by fantasai** [comment]
But there's related wording that probably also needs fixup, so we need to audit all of it.

**Comment by Loirooriol** [comment]
As far as I know the only formatting contexts that can be established by a block box are block and inline ones, so flex and grid ones are already excluded.

**Comment by fantasai** [comment]
Oh, yeah. :) That would definitely work then.

**Comment by fantasai** [comment]
All fixed, thank you!
