### ISSUE TITLE
Using <i> elements as <dfn> autolinks

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1230]
Some specs don't include the `Use <i> Autolinks: yes` metadata, but `<i>` elements are used in these specs (and are intended to be autolinks). For example:

* [css-counter-styles](https://github.com/w3c/csswg-drafts/blob/ec1a1061b80da0fd31a50d628529c61b5e8eac32/css-counter-styles/Overview.bs#L90)
* [css-display](https://github.com/w3c/csswg-drafts/blob/ec1a1061b80da0fd31a50d628529c61b5e8eac32/css-display/Overview.bs#L242)
* [css-flexbox](https://github.com/w3c/csswg-drafts/blob/ec1a1061b80da0fd31a50d628529c61b5e8eac32/css-flexbox/Overview.bs#L3889)
* [css-fonts-4](https://github.com/w3c/csswg-drafts/blob/ec1a1061b80da0fd31a50d628529c61b5e8eac32/css-fonts-4/Overview.bs#L784)
* ...

Currently only four CSSWG specs include the `Use <i> Autolinks` metadata:

* [css-text-decor](https://github.com/w3c/csswg-drafts/blob/6305bca262aeef183086b1b0e613ffb21e551472/css-text-decor/Overview.bs#L22)
* [css-break](https://github.com/w3c/csswg-drafts/blob/73df2299ebf24f9f9468f6b38bb5dc5a9e1e8730/css-break/Overview.bs#L19)
* [css-writing-modes-3](https://github.com/w3c/csswg-drafts/blob/0825e5d7d9e748af679acffec68fe85302c7576c/css-writing-modes-3/Overview.bs#L22)
* [css-writing-modes](https://github.com/w3c/csswg-drafts/blob/1f29b4e349e6539745d5d8cc0f90242c986fc6f3/css-writing-modes/Overview.bs#L25)

In the [Bikeshed documentation](https://tabatkins.github.io/bikeshed/#autolink-shortcuts):

> `<i>` elements can be enabled as autolinks as well, using `Use <i> Autolinks: yes` metadata. (The CSSWG has this enabled by default.)

-----

/cc @tabatkins

**Comment by tabatkins** [comment]
Converted Display, so removing the label.

**Comment by tabatkins** [comment]
Converted Flexbox

**Comment by tabatkins** [comment]
Converted Counter Styles

**Comment by fantasai** [comment]
Converted Fonts Level 4 (left the grammar intact, because it needs complete rewriting anyway).
