### ISSUE TITLE
css-animations: Does animation-duration support calc()?

### ISSUE THREAD

**Issue by praveenpuglia** [w3c/csswg-drafts#1238]
https://drafts.csswg.org/css-animations/#animation-duration

From the spec, it's not clear whether `calc()` function can be used for animation duration or not. At the moment, I see Chrome supporting it but firefox doesn't. 

This clearly has advantage in conjunction with CSS custom properties. Here's one such example.
https://codepen.io/praveenpuglia/pen/RVWKew/

**Comment by Loirooriol** [comment]
From [CSS values](https://drafts.csswg.org/css-values-3/#calc-notation),

> The calc() expression represents the result of the mathematical calculation it contains, using standard operator precedence rules. It can be used wherever `<length>`, `<frequency>`, `<angle>`, `<time>`, `<percentage>`, `<number>`, or `<integer>` values are allowed.

**Comment by praveenpuglia** [comment]
That means that I have to see if a bug already exists in Firefox and if not, raise one.

**Comment by fantasai** [comment]
Closing as invalid then? :) Reopen if there's an actual spec bug.

**Comment by birtles** [comment]
For the record, the Firefox bug for this is [bug 956573](https://bugzilla.mozilla.org/show_bug.cgi?id=956573).
