### ISSUE TITLE
[css-color] test

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#124]
test mailing list integration

**Comment by svgeesus** [comment]
it worked!
https://lists.w3.org/Archives/Public/public-css-archive/2016May/0001.html

**Comment by astearns** [comment]
If I reply to a GitHub notification, what happens?

**Comment by jensimmons** [comment]
It posts your reply, and sends it out as an email to anyone subscribed to the thread. See? Like this… sent from my iPhone, riding in a cab, back from the airport…

On May 18, 2016 at 10:09:29 AM, astearns (notifications@github.com(mailto:notifications@github.com)) wrote:

>  
> If I reply to a GitHub notification, what happens?
>  
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub(https://github.com/w3c/csswg-drafts/issues/124#issuecomment-220037577)
>  
>  
>  
>  
>  


--  
Jen Simmons  
Designer & Developer Advocate at Mozilla
Host and Executive Producer of The Web Ahead
http://thewebahead.net
http://jensimmons.com
twitter: jensimmons
