### ISSUE TITLE
[selectors] propagation of the :focus pseudo

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1240]
Unearthed from an old mail by @fantasai:

> I was just reviewing
> https://hg.csswg.org/drafts/rev/2539f118cb22
> 
> I'm not sure if the conformance clause is on the host language spec
> or directly on UAs. This needs to be clearer. If it's on the host
> language, then it should probably be a should and not a must. And
> if it's directly on UAs, then we've probably got a clash with HTML.
> In which case we should be clearer about the fact that our spec is
> asking to override the HTML spec.

**Comment by frivoal** [comment]
The discussion about HTML with the whatwg mentioned in the minutes above stalled here: https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jan/0018.html

Since then Edge, no longer supports bidirectional propagation of `:hover` and `:active`. Also, `:focus` does not propagate from the label to the labelled control (nor the other way around).

I still think bidirectional propagation of `:hover` and `:active` would be nice, but it looks like the consensus is going away from it, and that everybody agrees `:active` and `:focus` are supposed to propagate differently.

So the current phrasing in the spec seems wrong, and should be overturned.

I propose to replace this:

> If the document language has defined additional ways by which an element can match :active, the same ways must apply to elements matching :focus as well, except that the parent of an element that matches :focus must not match :focus.

with that:

> Document languages may define additional ways in which an element can match :focus, except that the parent of an element that matches :focus must not match :focus. (see :focus-within if matching on the parent is desired).

While we're at it, this part of the definition also seems wrong:

> There may be document language or implementation specific limits on which elements can acquire :focus. For example, [HTML5] defines a list of activatable elements.

and should be replaced with

> There may be document language or implementation specific limits on which elements can acquire :focus. For example, [HTML5] defines a list of focusable areas (https://html.spec.whatwg.org/multipage/interaction.html#focusable-area).

**Comment by frivoal** [comment]
Oh, missed that. There's still an open issue on the whatwg that relates to this

https://github.com/whatwg/html/issues/1632

Even then, I think the changes above should be applied. As it is, the spec contradicts HMTL, which is not good. The above changes make it defer to HTML.

We might want instead to try and convince HTML that we want to take over the definition of these pseudo classes (or maybe not), but until then, the above should be an improvement over what's here now.

**Comment by frivoal** [comment]
@tabatkins Does this work better than the previous phrasing?

> Document languages may define additional ways in which an element can match :focus, except that the :focus pseudo class must not propagate to the parent element (see :focus-within if matching on the parent is desired). Note: it may still apply to the parent element if made to propagate due to other mechanisms, but not merely due to being the parent.

**Comment by tabatkins** [comment]
"must not *automatically* propagate" and then 👍
