### ISSUE TITLE
[css-values-4] 'lh' and 'rlh' unit need to explain how to convert to an absolute length

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1253]
The definitions of [the `lh` unit](https://drafts.csswg.org/css-values/#lh) and the `rlh` unit need to explain how to convert a line-height to an absolute length.  In particular, this is interesting for `normal`, and it probably needs to say that it uses the first available font (which isn't the way `normal` works in layout).

(This came out of the discussion the WG is currently having.)

**Comment by frivoal** [comment]
This should be revisited once the definition of line-height itself is clarified, as being discussed in https://github.com/w3c/csswg-drafts/issues/1796

**Comment by frivoal** [comment]
Now that we have fixed #1796, this becomes much more simple to do.
For all values of `line-height` other than `normal`, the answer is now clearly non ambiguous, and for `normal`, I suggest the answer is the height that one would get for an empty line box, containing only the strut, which matches @dbaron 's suggestion to used only the first available font.
