### ISSUE TITLE
[css-values] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1258]
[Bikeshed has a feature to include CanIUse info panels in specs](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels). ([Example](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect); [Example commit](https://github.com/w3c/csswg-drafts/commit/91581486a0adee8fb34960059d460327b0ee1c45))

I wonder if Values&Units would consider using this feature? Here are the spec anchors and corresponding CanIUse features for Values&Units:

| CSS spec URL | CanIUse feature URL |
|----|----|
| https://drafts.csswg.org/css-values/#attr-notation | https://caniuse.com/#feat=css3-attr |
| https://drafts.csswg.org/css-values/#calc | https://caniuse.com/#feat=calc |
| https://drafts.csswg.org/css-values/#ch | https://caniuse.com/#feat=ch-unit |
| https://drafts.csswg.org/css-values/#rem | https://caniuse.com/#feat=rem |
| https://drafts.csswg.org/css-values/#viewport-relative-lengths | https://caniuse.com/#feat=viewport-units |

**Comment by tabatkins** [comment]
Done. ^_^
