### ISSUE TITLE
[css-cascade] Add CanIUse panels

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1259]
[Bikeshed has a feature to include CanIUse info panels in specs](https://tabatkins.github.io/bikeshed/#metadata-include-can-i-use-panels). ([Example](https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect); [Example commit](https://github.com/w3c/csswg-drafts/commit/91581486a0adee8fb34960059d460327b0ee1c45))

I wonder if css-cascade would consider using this feature? Here are the spec anchors and corresponding CanIUse features for css-cascade:

| CSS spec URL | CanIUse feature URL |
|----|----|
| https://drafts.csswg.org/css-cascade/#all-shorthand | https://caniuse.com/#feat=css-all |
| https://drafts.csswg.org/css-cascade/#inherit-initial | https://caniuse.com/#feat=css-unset-value |
| https://drafts.csswg.org/css-cascade/#valdef-all-revert | https://caniuse.com/#feat=css-revert-value |
| https://drafts.csswg.org/css-cascade/#initial | https://caniuse.com/#feat=css-initial-value |

**Comment by tabatkins** [comment]
Thanks for the listing of features!
