### ISSUE TITLE
[css-shapes-1] No definition for arguments to polygon()

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1271]
polygon() arguments are length or percentage representing x/y coords. It's unspecified

- what is the origin?
- which way is positive?
- what are percentages relative to?

**Comment by astearns** [comment]
The section start has: 

`When using this syntax to define shapes, the reference box is defined by each property that uses <basic-shape> values. The coordinate system for the shape has its origin on the top-left corner of the reference box with the x-axis running to the right and the y-axis running downwards. All the lengths expressed in percentages are resolved from the used dimensions of the reference box.`

https://drafts.csswg.org/css-shapes-1/#basic-shape-functions

@fantasai were you looking for anything more here?
