### ISSUE TITLE
[css-grid] Editorial: Missing period (.) in Example 1  Section 2.1. Declaring the Grid

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1275]
Editorial: Missing period (.) in Example 1 [ Section 2.1. Declaring the Grid](https://www.w3.org/TR/css3-grid-layout/#overview-grid) in the second bullet point:

`The following declares a grid with as many rows of at least 5em as will fit in the height of the grid container (100vh). The grid has no explicit columns; instead columns are added as content is added, the resulting column widths are equalized (1fr) Since content overflowing to the right won’t print, an alternate layout for printing adds rows instead`. 

There should be a period(.) after "(1fr)" and before "Since"

 The missing punctuation make the module hard to read for English and and not-English readers.

Requesting this change be made to make the CSS Grid Layout Module easier to read. 

Robert DiBlasi
We all learn by sharing what we know

**Comment by fantasai** [comment]
Fixed, thanks!
