### ISSUE TITLE
[css-grid] 1.1.1  Example 4 code for rows does not match (figure 4 or figure 5)

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1276]
[1.1.1. Adapting Layouts to Available Space](https://www.w3.org/TR/css-grid-1/#adapting-to-available-space) Example 4 code does not match (figure 4 or figure 5) or for that matter even (figrue 3). 

(figure 4 and 5) both display row and column sizes on the parameter of their respective figures.

Notice row code in the i(figure 4 and 5):
`minmax(min-content , 1fr)`

Now look at Example 4 row code:
```
  grid-template-rows:
    /* 3 */ auto
    /* 4 */ 1fr
    /* 5 */ auto;
```
Something does not seem to be correct at this point in the CSS Grid Layout Module.
I suggest  two to possible avenues to follow to help clarify this mismatch of code and image:

1) change the row code on the parameter of (figure 4 and 5) from minmax( min-content, 1fr) to just "1fr" to match the row code in Example 1

or 

2) change the row code in Example 1 to match (figure 4 and 5):
  grid-template-rows:
    /* 3 */ auto
    /* 4 */ minmax(min-content, 1fr)
    /* 5 */ auto;

I am requesting one of these changes be made to the CSS Grid Layout be made for clarity.

Robert DiBlasi
We all learn by lsharing what we know

**Comment by fantasai** [comment]
Fixed, thanks!
