### ISSUE TITLE
[css-grid] Editorial: 1.1.1.  first paragraph second sentence need to be adjusted

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1277]
[1.1.1.  Adapting Layouts to Available Space](https://www.w3.org/TR/css-grid-1/#adapting-to-available-space) first paragraph second sentence states:

`The figures above represent a game with five major components in the layout: the game title, stats area, game board, score area, and control area. The author’s intent is to divide the space for the game such that:`

Please change the "The figures above " to "The figures" 
The word "above" is not correct (graphic is not about game)and not need and leads to confusion in the reading of the CSS Grid Layout Module. 

Request adjusting the second sentence of the first paragraph of [Section 1.1.1](https://www.w3.org/TR/css-grid-1/#adapting-to-available-space) to just "The figures".

Robert DiBlasi
We all leaern by sharing what we know

**Comment by fantasai** [comment]
Fixed, thanks!
