### ISSUE TITLE
[css-grid] Editorial: ﻿1.1.2. Source-Order Independence reference wrong images

### ISSUE THREAD

**Issue by sunright** [w3c/csswg-drafts#1278]
[1.1.2. Source-Order Independence](https://www.w3.org/TR/css-grid-1/#source-independence) second sentence refers to the wrong figures,

`Continuing the prior example, the author also wants the game to adapt to different devices. Also, the game should optimize the placement of the components when viewed either in portrait or landscape orientation (Figures 4 and 5).`

Please change "(Figures 4 and 5)" to {Figures 6 and 7)

Requesting change reference in second sentence of first paragraph of [Section 1.1.2](https://www.w3.org/TR/css-grid-1/#source-independence) from "(Figures 4 and 5)" to (Figures 6 and 7)

Robert DiBlasi
We all learn by sharing what we know

**Comment by tshinnic** [comment]
I noticed this also.  Apparently out-of-sync upon May 2016 version.

Also, in 1.1.1, inside Example 1, there is the line 
```
    *     or the game controls, which occupy this column [Figure 3])
```
This should reference either Figure 4 or Figure 5.  I'm not sure which one better fits the discussion.

Do y'all take PRs for typos?  I have others...

**Comment by tabatkins** [comment]
We *love* typo PRs, plz give them all to us. ^_^

**Comment by fantasai** [comment]
Fixed, thanks!
