### ISSUE TITLE
Proposal: SVG Viewbox be controlled as a CSS propery

### ISSUE THREAD

**Issue by vidhill** [w3c/csswg-drafts#128]
First, original proposition, https://lists.w3.org/Archives/Public/www-svg/2013Dec/0080.html

Yes, I'm trying to bring this to the table again as it did not seem to get much attention/discussion the last time around.
-maybe being on Github will be more conducive to discussion..

I really agree with this proposal, 
being able to modify the viewbox on a SVG element using CSS would allow for very useful applications of SVG in a responsive layout, (See Sara Soueidan's examples below)

Sara Soueidan has a very good article demonstrating a perfect need and use cases for this here: https://sarasoueidan.com/blog/svg-art-direction-using-viewbox/

There were some enthusiastic responses from some SVG heads..

@sdras **Sarah Drasner** [Mail List Reply](https://lists.w3.org/Archives/Public/www-style/2016Apr/0174.html)

@AmeliaBR  **Amelia Bellamy-Royds** [Mail List Reply](https://lists.w3.org/Archives/Public/www-style/2016Apr/0203.html)

@jakearchibald Jake Archibald [Mail List Proposal](https://lists.w3.org/Archives/Public/www-style/2016Feb/0328.html#options3)

**Comment by tabatkins** [comment]
Yup, sorry about the request getting buried. I got swamped for a while and am trying to catch up on proposals.

Yes, viewbox should totes be a property; nearly everything in SVG should be.  A simplified version that solely exposes `none | <length>{4}` would be utterly uncontroversial.  I like, however, the `bounds` value, and having it be defined simply as the stroke bounding box is good.  This is essentially just CSS shrinkwrapping (in theory, of course; it's different in practice).

**Comment by AmeliaBR** [comment]
@tabatkins Are you able to move this issue to the FX repo?  I'd like to keep any view-box spec under the (shared) responsibility of the SVG WG.  

And if you do start drafting something, Tab, I'd be happy to review it.  If you don't get to it, it's still on my eventual To-do list. Just buried under far too many other to-do's!

**Comment by bradkemper** [comment]
Would this affect non-SVG stuff too? I'm no expert on this attribute, but it sounds kind of like a clip-path:inset() effect which also affects the element's instrinsic dimensions, causing it to be scaled so that the new dimensions are contained by the original dimensions. Is that something we want for plain old HTML too?

**Comment by tabatkins** [comment]
@bradkemper I don't *think* so.  This doesn't clip, either; viewBox just (a) from the POV of stuff inside the SVG, sets up the coordinate space they position themselves in (and in particular, what "100%" maps to), and (b) from the POV of stuff outside the SVG, defines the intrinsic aspect ratio of the element.

(a) doesn't mean anything for non-SVG elements.  (b) could theoretically, but it's a very roundabout way to handle aspect ratio, and misses some features we'd like for a real aspect-ratio property, so I don't think we should try to smuggle aspect-ratio into general CSS via viewbox.

**Comment by tabatkins** [comment]
This issue was moved to w3c/fxtf-drafts#7
