### ISSUE TITLE
[selectors] Add selector for blank inputs

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1283]
https://twitter.com/thedamon/status/855440231197278209

> Is anyone in CSS land working on detecting empty inputs? or expanding :empty to cover value for self-closing elements?

**Comment by Loirooriol** [comment]
Using `placeholder=" "` and `:placeholder-shown` seems to work, but probably too hacky and unreliable.

**Comment by FremyCompany** [comment]
Not supported in Edge. There is ```required``` + ```:invalid``` that works as a combo everywhere though.

**Comment by fantasai** [comment]
@FremyCompany That will also match elements that are not empty but whose contents are invalid. So it is not helpful here.

**Comment by FremyCompany** [comment]
@fantasai good point

**Comment by jonathantneal** [comment]
I wrote a script to simulate this effect by adding an `empty-within` attribute to elements that are an empty text control or contain one.

https://jonathantneal.github.io/empty-within/

I hope this can demonstrate the value in such a selector, as well how applicable it may already be.

One thing I have learned in this exercise is that I would not want this blank input selector to target regular elements. For instance, if `:empty` were merely extended to capture empty inputs, then `:has(:empty)` (or something like `:empty-within`) could end up capturing non-form elements, such as decorative markup that was unrelated to the intent of my styling. I hope this makes some sense.

**Comment by tomhodgins** [comment]
I have a number of JS plugins that add this sort of selection support for stying. Including this demo: https://codepen.io/tomhodgins/pen/oLVWJX

I would love the ability to select `<input>` and `<select>` when they have no `value`. It would be wonderful if `[value=""]` was live, but if that's not possible, just allowing you to select empty versus non-empty values would be a big help!

**Comment by AmeliaBR** [comment]
I'll be glad to have this functionality out there, but there will need to be an education effort to counter existing educational content describing the very different `:blank` proposal that is currently in the spec.
