### ISSUE TITLE
[css-counter-styles] `system: extends decimal; fallback: decimal; speak-as: decimal`

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1285]
The `system`, `fallback`, and `decimal` descriptors all use `<counter-style-name>` in their value grammar definition, linking to:

https://drafts.csswg.org/css-counter-styles/#typedef-counter-style-name
> The general form of an `@counter-style` rule is:
>
> ```css
> @counter-style <counter-style-name> { <declaration-list> }
> ```
>
> where `<counter-style-name>` is a `<custom-ident>`.
> If a counter style’s name is an ASCII case-insensitive match for "decimal" or "none", the `@counter-style` rule is invalid.

It is unclear whether the exclusion of "decimal" and "none" is part of the definition of the `<counter-style-name>` type, and therefore also applies when this type is used in descriptors, or whether that only applies to `@counter-style` rules.

Being able to use "decimal" makes sense. In fact that’s even the initial value, in the case of `fallback`. Using `none` less so. Maybe a different behavior is desirable for these two keywords?

By the way, why is "none" excluded when for example "inside" isn’t?

**Comment by upsuper** [comment]
> It is unclear whether the exclusion of "decimal" and "none" is part of the definition of the `<counter-style-name>` type, and therefore also applies when this type is used in descriptors, or whether that only applies to `@counter-style` rules.

I don't think the exclusion of them is part of the definition of the `<counter-style-name>` type, because the last sentence is about "a counter style's name", and then, "the `@counter-style` rule is invalid`. There is nothing about `<counter-style-name>` here.

**Comment by tabatkins** [comment]
Yup, exactly - those are restrictions on `@counter-style` definitions, not on `<counter-style-name>`.

> By the way, why is "none" excluded when for example "inside" isn’t?

`none` is a valid value for `list-style-type`. `inside` is a different property entirely; I opted not to try to include the full set of `list-style` sub-property values.

**Comment by SimonSapin** [comment]
Just to clarify: `system: extends none; fallback: none; speak-as: none` is valid. (Though useless since there can’t be a counter style with that name.)
