### ISSUE TITLE
[css-overflow] Scrollbar layout could be extend to allow for the mobile & mac native scrollbar behavior

### ISSUE THREAD

**Issue by bgirard** [w3c/csswg-drafts#1287]
https://www.w3.org/TR/css-overflow-3/#scrollbar-layout

On mac, only if you have no external mouse plugged in, the scroll bars will not consume any space and will auto hide when not scrolling. It's the same on mobile. Right now the specification doesn't cover that and asks that scrollbar be inserted between the edge and subtract from the dimensions. Should this description be extended to be more flexible?

**Comment by frivoal** [comment]
Thanks for the report. A solution to this problem has been recently added to the css-overflow-4 specification:

https://drafts.csswg.org/css-overflow-4/#scollbar-gutter-property
