### ISSUE TITLE
[css-flex][css-sizing] Should flex-shrinking propagate back down the flex chain?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#1290]
What should happen if you have an auto-sized flexbox that is itself child in yet another flexbox, and the inner flexbox is asked to shrink to fit its parent, but it contains items (that could be shrinked to fit but) would not shrink if the auto flexbox was not itself in a flexbox?

> https://wptest.center/#/xko2l5 (auto flexbox by itself)
> https://wptest.center/#/24hxs8 (auto flexbox in a flexbox)

Firefox and Edge both react the same way here, and the fact the flexbox is itself in a flexbox does not affect its layout. It is layouted as a height:auto flexbox, then the parent flexbox deals with that. In Chrome, however, the fact the flexbox is a shrink-candidate seems to make the flexbox behave as if it had a height set to its final size, and force-skrink its content.

Please note everybody agrees that an auto flexbox that is not a flex item will let its content grow to avoid any scrollbar, per:

> The min-content-size of an element is the smallest size a box could take that doesn’t lead to overflow that could be avoided by choosing a larger size. https://drafts.csswg.org/css-sizing/#min-content 

However, if the flexbox had an height, flexing will apparently allow scrollable elements to shrink below their min-content-size:

> https://wptest.center/#/snl1k1 (flex-shrink default to 1, the element shrinks to fit its parent)

If you put flex-shrink:0 on the scrollable element, all browsers stop shrinking it:

> https://wptest.center/#/hiv3y7 (flex-shrink is now 0, the element overflows)

It is not clear to me that the sizing of the inner flexbox’s items should depend on the fact the flexbox is itself an item in a flexbox. 

cc @tabatkins @fantasai @gregwhitworth

**Comment by Loirooriol** [comment]
The comparison with the horizontal case might also be interesting

1. https://jsfiddle.net/wLuo4a1z/: single flex, no size, flex-shrink:1

    |          | Horizontal case | Vertical case |
    | -------- | --------------- | ------------- |
    | Firefox  | fill-available  | max-content   |
    | Chrome   | fill-available  | max-content   |
    | Edge     | fill-available  | max-content   |

    Of course the horizontal case is fit-content when using inline-flex, that's consistent with the vertical case (with infinite available height).

2. https://jsfiddle.net/Lwvavxu8/: nested flex, with a size, flex-shrink:1

    |          | Horizontal case | Vertical case    |
    | -------- | --------------- | ---------------- |
    | Firefox  | specified width | max-content      |
    | Chrome   | specified width | specified height |
    | Edge     | specified width | max-content      |

    Should the vertical and horizontal cases be consistent? I suspect so, but it has been some time since I last read the spec.

3. https://jsfiddle.net/7of2caeL/: single flex, with a size, flex-shrink:1

    |          | Horizontal case | Vertical case    |
    | -------- | --------------- | ---------------- |
    | Firefox  | specified width | specified height |
    | Chrome   | specified width | specified height |
    | Edge     | specified width | specified height |

    All agree.

4. https://jsfiddle.net/y65krv6k/: single flex, with a size, flex-shrink:0

    |          | Horizontal case | Vertical case    |
    | -------- | --------------- | ---------------- |
    | Firefox  | specified width | max-content      |
    | Chrome   | max-content     | max-content      |
    | Edge     | max-content     | max-content      |

    Firefox is clearly wrong ([bug 876985](https://bugzilla.mozilla.org/show_bug.cgi?id=876985)).

**Comment by FremyCompany** [comment]
Thanks for this nice analysis! 

I'll add this to the next call as a FYI and if no one objects, I'll file a Chrome bug on their behavior. This is probably the easiest way to get to interop in this case.

**Comment by FremyCompany** [comment]
Filed the chrome bug as https://bugs.chromium.org/p/chromium/issues/detail?id=718089

**Comment by cbiesinger** [comment]
I would encourage you to submit the testcases to https://github.com/w3c/web-platform-tests/tree/master/css/css-flexbox-1 as well

**Comment by FremyCompany** [comment]
Noted, added to my backlog

**Comment by zcorpan** [comment]
@FremyCompany can you point to the testcase in web-platform-tests? If there isn't one, this should be open?
