### ISSUE TITLE
[css-table-3] Is the fixed table layout specification stable enough to be implemented?

### ISSUE THREAD

**Issue by KiChjang** [w3c/csswg-drafts#1291]
Per title.

The motivation behind this is primarily due to the under-specified CSS2 fixed table layout specification, which does not take into account quite a few edge cases, and the CSS3 table spec defines algorithms which solves the problem of distributing column widths in a robust manner.

**Comment by FremyCompany** [comment]
Fixed table layout is probably the layout mode that should be the most-exhaustively defined in the current spec, but if you wanted to implement a complete table you'd need the height distribution which is currently the most under-defined. 

I would think the current spec is your best bet if you need to implement some table things, but writing tests and comparing the outcome in browser will prove necessary if you actually need interop. What do you need this for?

**Comment by KiChjang** [comment]
I saw that we have an incorrect implementation of distributing column width sizes in servo/servo#16324, because we are following the incorrect algorithm in the spec. Initially I thought to revert back to the CSS2 table spec behaviour, but quickly found the algorithms for distributing column width to be very under-specified. CSS3 in comparison has a much more robust algorithm for dealing with corner cases that CSS2 either assumes doesn't exist or simply did not account for.
