### ISSUE TITLE
[css-counter-styles] Exclude 'none' from <counter-style-name>

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1295]
https://drafts.csswg.org/css-counter-styles/#typedef-counter-style-name
> The general form of an `@counter-style` rule is:
>
> ```css
> @counter-style <counter-style-name> { <declaration-list> }
> ```
>
> where `<counter-style-name>` is a `<custom-ident>`.
> If a counter style’s name is an ASCII case-insensitive match for "decimal" or "none", the `@counter-style` rule is invalid.

We’ve clarified in #1285 that the last sentence only applies to at-rules, and not other uses of `<counter-style-name>`. This makes sense for `decimal` which is a style that always exists (it just can’t be overridden). Allowing `none` however is useless since it can’t ever refer to an existing counter style.

I suggest changing the spec to make `none` (ASCII-case-insensitive) an invalid value of `<counter-style-name>` in all contexts, like CSS-wide keywords already are.

CC @upsuper, @tabatkins

**Comment by upsuper** [comment]
Gecko currently treats `none` as a predefined counter style in that case, but I think excluding `none` from `<counter-style-name>` makes sense, given that it can never be a counter style, and can never be referred anywhere.

Strictly speaking, this proposal would make `system: extends none` and `fallback: none` invalid, but I don't think that would cause any real problem.

**Comment by tabatkins** [comment]
Yeah, this sounds reasonable.

**Comment by therealglazou** [comment]
+1
