### ISSUE TITLE
[css-align] Overconstrained Baseline Content-Alignment with box-sizing:border-box and a max-height?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#130]
https://drafts.csswg.org/css-align-3/#baseline-align-content
"minimum necessary extra space is added between its start (end) content
edge and its alignment subject’s edge to align its alignment baseline
in that axis"

What should happen when the alignment subject has box-sizing:border-box
and a max-[width|height] in the relevant axis, and adding "minimum
necessary extra space" to meet the baseline would exceed the given
max size?

I can't find anything in the CSS Align spec that says anything about
this case.

I can think of a few alternatives:
A. add padding up to the max size and then add margin after that
   (honor both baseline alignment and the given max-size, but not
    align-self)
B. add padding up to the max size
   (honor the given max-size and align-self, but not baseline
    alignment)
C. ignore the max size
   (honor align-self and baseline alignment, but not the max size)

I think I prefer A, and that B is acceptable, but C is unacceptable.

**Comment by fantasai** [comment]
D. The alignment is honored, as is the max-size, but the content of the box might end up overflowing.

p.s. This has nothing to do with `box-sizing`.
