### ISSUE TITLE
[css-writing-modes] section/subsection confusion sort of marks 'writing-mode' as non-normative

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1307]
[§3. Introduction to Vertical Text](https://drafts.csswg.org/css-writing-modes-3/#vertical-intro) begins with:
> This subsection is non-normative.

This is odd, since it's really a section rather than a subsection.

Furthermore, the section contains [§3.1. Block Flow Direction: the writing-mode property](https://drafts.csswg.org/css-writing-modes-3/#block-flow), which definitely needs to be normative.

It seems like this could use a little bit of clarification by moving the introductory material into an actual subsection (although that has the problem of a toplevel section with no content before the subsection begins), or something else to make it clearer that §3.1 is actually normative.

**Comment by fantasai** [comment]
It uses the word “subsection” instead of “section” to try to indicate that it applies only to the material before 3.1. Not sure what's a better way of indicating that...

**Comment by astearns** [comment]
What if we left the first sentence in the toplevel section (In addition…) then started a subsection immediately after and called it something like "Vertical Text Examples" and marked *that* subsection non-normative?

**Comment by astearns** [comment]
@fantasai please review and merge the PR if it looks OK to you. @dbaron is this change sufficient?

**Comment by dbaron** [comment]
Looks fine to me.  (No idea whether we should call it a section or a subsection, though.)
