### ISSUE TITLE
[css-writing-modes] URL to latest published version does not work

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1311]
The [CSS Writing Modes Level 4 draft](https://drafts.csswg.org/css-writing-modes-4/) has this link

> **Latest published version:**
> https://www.w3.org/TR/css-writing-modes-4/

But that URL gives a 404 error.

This also affects the bibliography of [CSS Flebox](https://drafts.csswg.org/css-flexbox/#biblio-css-writing-modes-4) and [CSS Grid](https://drafts.csswg.org/css-grid/#biblio-css-writing-modes-4), which have that same link.

If Writing Modes Level 4 has not been published yet, I think they should either link the draft or link Writing Modes Level 3.

**Comment by fantasai** [comment]
Assigning to @tabatkins because this is a Bikeshed issue.

**Comment by plinss** [comment]
Not bikeshed, but the spec db, which is me. I added the TR URL when we had a resolution to publish. It just hasn't happened yet. I'll remove the URL later today, but please ping me when it does get published.

**Comment by plinss** [comment]
Ok, actually the Overview.bs file has the TR link in it:
`TR: https://www.w3.org/TR/css-writing-modes-4/`
so it's a spec issue. Though I did remove the TR URL from the spec DB so Bikeshed won't put it back as a default value once this is removed.

**Comment by plehegar** [comment]
https://www.w3.org/TR/css-writing-modes-4/ was published last December. Shouldn't this issue be closed now?

**Comment by Loirooriol** [comment]
Works for me now.
