### ISSUE TITLE
[css-inline] Baseline position may not be interoperable

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1314]
From @dbaron's [comment on Apr 21st](https://github.com/w3c/csswg-drafts/issues/938#issuecomment-296107259), even when `line-height` is set to a value other than `normal` and the used line height is consistent, the baseline position may not be consistent in some browsers.

CSS2 does not define this, and I'm filing this not to loose. Do we want to work on this?

**Comment by litherum** [comment]
Baseline position is dependent on font metrics, which are different between browsers and different between the same browser on different platforms.

**Comment by frivoal** [comment]
This used to be undefined, but has now been sorted out.

* diagram of possibilities: https://lists.w3.org/Archives/Public/www-archive/2017Apr/att-0008/IMG_20170421_173959.jpg
* test results:
  * https://github.com/w3c/csswg-drafts/issues/1797 (excludes black behavior in diagram)
  * https://github.com/w3c/csswg-drafts/issues/1801 (clarifies we get the blue behavior, not the red one)
* Resolution: https://lists.w3.org/Archives/Public/www-style/2017Dec/0007.html
* commit: https://github.com/w3c/csswg-drafts/commit/a3c7617bafdc3ea7201b77dde93719ecc2fea8ca
