### ISSUE TITLE
In the main README, http://dev.w3.org/csswg/ should be a link

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#1315]
Location: https://github.com/w3c/csswg-drafts/blob/master/README.markdown

The URL at the bottom is placed inside a code block, so it’s not an active link. This makes is harder for people to follow it, and some may even assume that it’s not that important. In truth, it may be the most useful CSSWG page for web developers.

I suggest turning it into a real link in the README.

**Comment by dbaron** [comment]
Fixed in 3f61313, as @syncbot noted.  Thanks for the suggestion.

I also made a few other tweaks in later changesets.
