### ISSUE TITLE
[css-grid] Grid implies that items are always resolved against a definite size

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1319]
In the last paragraph of [section 11.1](https://drafts.csswg.org/css-grid/#algo-overview), Grid says:

> Once the size of each grid area is thus established, the grid items are laid out into their respective containing blocks.

This seems to imply that, at this point, the grid areas should be treated as having definite heights and widths, so that %s on grid items *always* resolve.  Is this what we actually wanted?

**Comment by atanassov** [comment]
Yes, after step 4 of section 11.1 grid area dimensions should be treated as definite. 

One clarification we could add (I couldn't find) is that baseline alignment of grid items can also affect the row and column dimensions. For example an auto height row is defined by the max( maxHeightGridItem, maxAscentOfFirstBaselines + maxDescentOfLastBaselines) where maxAscentOfFirstBaselines is based of any two or more items participating in the row that have computed self-align: baseline or self-align: stretch(start) and content-align: first baseline; (similar for maxDescentOfLastBaselines).

I'm not too sure if the clarification above will be helpful for anyone other than implementers but it is an important one to get track resolutions correct.

**Comment by javifernandez** [comment]
> One clarification we could add (I couldn't find) is that baseline alignment of grid items can also affect the row and column dimensions. 
Well, I think that is already in the spec, although maybe expressed not enough clearly, in the following sentence:
https://drafts.csswg.org/css-align-3/#baseline-align-content
> When a box participates in first (last) baseline content-alignment it effectively aligns its start (end) edge with the other boxes in its baseline-sharing group, then gains additional start (end) padding to align its alignment subject’s (i.e. content’s) baseline with those of its baseline-sharing group. See §8.3 Aligning Boxes by Baseline for exact details. This can increase the intrinsic size of the box.

and also here 
https://drafts.csswg.org/css-align-3/#baseline-align-self
> When a box participates in first (last) baseline self-alignment it effectively first aligns its start (end) edge with the other boxes in its baseline-sharing group, then gains additional start (end) margin to align its baseline with those of its baseline-sharing group. See §8.3 Aligning Boxes by Baseline for exact details. This can increase the intrinsic size of the box.

I also agree that these clarifications may be way more interesting for implementors, but they indeed help to understand how the tracks are sized and how they acquired their actual size. 

As a matter fact, my main doubt regarding this concept of "baseline affecting the intrinsic size" is that is somehow disconnected with the track sizing algorithm. There isn't any specification clarifying when it should be run.
