### ISSUE TITLE
[css-grid] Should copy Flexbox and treat stretched items as having definite size

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1320]
Flexbox's layout algorithm, in [step 11](https://drafts.csswg.org/css-flexbox/#algo-stretch), explicitly treats "stretch" items as being definitely sized in the cross axis (redoing layout for the contents if necessary).  This means that % children of the flex item can resolve properly, which is precisely why we added

Grid doesn't appear to have a similar clause; an auto-sized but stretched grid item would, it appears, be treated as indefinite, so %s on its children resolve to auto.  Should we copy over this clause to the Grid layout algo, so more %s are valid?

**Comment by fantasai** [comment]
See #1319 for CSSWG discussion.
