### ISSUE TITLE
[css-counter-styles] CSSCounterStyleRule::name unnecessarily uses CSS syntax

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#1325]
https://drafts.csswg.org/css-counter-styles/#dom-csscounterstylerule-name
> The name attribute on getting must return a CSSOMString object that contains the serialization of the `<counter-style-name>` defined for the associated rule.
>
> On setting the name attribute, run the following steps:
> 
> 1. Parse a component value from the value.
> 2 . If the returned value is an <custom-ident>, […]

Using CSS parsing and seralization here seems unecessary. Within a stylesheet, CSS tokenization rules dictate where an identifier token starts and end, and backslash-escaping can be used to insert arbitrary characters without ending an identifier. But in this API no delimiting is needed, a string already has a clear start and end.

Compare with `CSSKeyframesRule::name`, which is simply “the name of the keyframes”:

https://drafts.csswg.org/css-animations/#dom-csskeyframesrule-name

Test case that shows the difference in Firefox:

```html
data:text/html,<style>@counter-style \@ { symbols: a }@keyframes \@ {}</style><script>document.write(document.styleSheets[0].cssRules[0].name + " " + document.styleSheets[0].cssRules[1].name)</script>
```

@upsuper Do you think it would be web-compatible to change `CSSCounterStyleRule::name` to behave like `CSSKeyframesRule::name`?

CC @tabatkins

**Comment by tabatkins** [comment]
Yeah, I'm fine with changing it to just be the literal name. This predates us making the general decision to not CSS-parse names coming in from JS APIs.

**Comment by upsuper** [comment]
I think that should be fine.
