### ISSUE TITLE
[CSS3 UI] Clarify relation to UA zoom controls for resize property

### ISSUE THREAD

**Issue by alastc** [w3c/csswg-drafts#1328]
I randomly came across the CSS [resize property](https://www.w3.org/TR/css-ui-3/#resize), whilst I'm editing a WCAG 2.1 criteria called "[Resize content](https://github.com/w3c/wcag21/issues/77)".

From my first read, the CSS property appears to be aimed at particular elements, such as text-boxes, where the UA provides a resize mechanism (e.g. the little triangle at the bottom-right). Is that correct?

If so, would it possible to clarify the relationship to the browser's zoom control? 

There is already a note saying 

> "The resizing mechanism is NOT the same as the scrolling mechanism.", 

Something similar such as: "The resizing mechanism is NOT related to any UA mechanism for zooming".

The WCAG SC is still open for public comment, one of those comments suggested renaming it "Zooming content" to differentiate it from text-sizing, presumably that would help separate it from the CSS property as well?

**Comment by frivoal** [comment]
> From my first read, the CSS property appears to be aimed at particular elements, such as text-boxes, where the UA provides a resize mechanism (e.g. the little triangle at the bottom-right). Is that correct?

Yes.

> If so, would it possible to clarify the relationship to the browser's zoom control?

> There is already a note saying

>>    "The resizing mechanism is NOT the same as the scrolling mechanism.",

> Something similar such as: "The resizing mechanism is NOT related to any UA mechanism for zooming".

I guess we could indeed write:

> "The resizing mechanism is NOT the same as the scrolling mechanism, nor is it related to any UA mechanism for zooming.

While I don't think many people are likely to be confused in the absence of this clarification, it certainly doesn't hurt.

@tantek @atanassov @astearns This is is an editorial change. Is it OK for me to apply it without a WG resolution? If not, please agenda+.

**Comment by astearns** [comment]
OK to go without resolution on this one
