### ISSUE TITLE
[css-selector][css-ui] selector for overwrite mode to specify "caret-shape:block"

### ISSUE THREAD

**Issue by yosinch** [w3c/csswg-drafts#133]
Can we have selector for overwrite mode? If we have a selector for overwrite mode, we could write:

```
input, textarea, *[contenteditable=true"]:overwrite { caret-shape: block}
```

**Comment by tabatkins** [comment]
Inputs and textareas today don't respect overwrite (at least in my initial testing) - they always insert.  contenteditable does, but you can opt into that switching with `caret-shape: auto`.

I don't *think* there's an actual need to tell what mode you're in?  (Leaving aside the fact that overwrite mode is the devil.)

**Comment by frivoal** [comment]
I generally agree with @tabatkins, but I will note that  `caret-shape: auto` only has "may" when it comes to switching to a block caret in overwrite mode. I wonder if this should be strengthened.

(That is totally separate from whether there should be an overwrite mode at all, only what happens to an auto shaped caret if you have one and activate it).

**Comment by frivoal** [comment]
Closing this as wontfix, by editor discression, which seems appropriate at this (early) stage of the spec.

@yosinch I'd appreaciate if you could let me know, based on the explantions above, if you can live with that.
