### ISSUE TITLE
[css-borders] border-width keywords

### ISSUE THREAD

**Issue by andresgalante** [w3c/csswg-drafts#1331]
https://www.w3.org/TR/css3-background/#border-width

I've been looking into implementing borders with keywords. I've notice that the definition of `thin` `medium` and `thick` is too loose and it can be interpreted in any way, `thin` `medium` and `thick` can even be equal!

Another thing we can think about is to add a `hairline` keyword, which would render a border “as thin as it can go” solving the issue of users wanting to implement a 1px line no matter the display density. For example if you want to display a `1px` line on a retina display, you'd define it as `.5px`

What do you think?

**Comment by SebastianZ** [comment]
The existing border widths have been defined precisely in #7254. And introducing a `hairline` value is discussed in #3720.

Sebastian
