### ISSUE TITLE
[css2] Four directories for CSS 2?!

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#1335]
We have three copies of CSS 2 in this repo: `css2-testing` (last changed three months ago), `css2` (last changed three months ago), and `css21` (last changed four months ago). This is completely excessive. We also have `css2-src` (last changed two years ago), containing a 2011 Disposition of Comments.

If we want to keep the DoC in the repo, it should be moved into one of the other CSS2 directories.

We should probably also get rid of one of the copies of the spec. `css21` seems to be the one we've stopped using?

cc/ @bert-github

**Comment by gsnedders** [comment]
This seems to have got resolved at some point.

**Comment by gsnedders** [comment]
Oh, no, still two.

**Comment by frivoal** [comment]
Isn't that what we want? 1 for the latest draft with all the changes folded in, one with  few cherry-picked changes that are ready for republication.

**Comment by gsnedders** [comment]
@frivoal That's not what we have now: we have one which is essentially the current REC unchanged, and one with all the changes.

**Comment by frivoal** [comment]
I think that's intentional, because we haven't started cherry picking from into the current REC from the one with all the changes. However, the directories are now ready to start doing just that.

**Comment by gsnedders** [comment]
Fixed by #2544.
