### ISSUE TITLE
[css-transforms] Incorrect autolinking of "transform"

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1336]
In the [definition](https://drafts.csswg.org/css-transforms/#transformable-element) of transformable element:

> [...] an element in the SVG namespace and not governed by the CSS box model which has the attributes transform, patternTransform or gradientTransform [SVG11].

`patternTransform` and `gradientTransform` link to SVG 1.1, but `transform` links to the [CSS property](https://drafts.csswg.org/css-transforms/#propdef-transform), instead of the [SVG attribute](https://www.w3.org/TR/2011/REC-SVG11-20110816/coords.html#TransformAttribute).

Some links in [Chapter 9](https://drafts.csswg.org/css-transforms/#svg-transform) are also incorrect.

**Comment by smfr** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/ed0f4268e7cf2dee5ac896fb8f5ebde2c690a0d6
