### ISSUE TITLE
[css-values-4] <position> is a lie

### ISSUE THREAD

**Issue by nox** [w3c/csswg-drafts#1338]
The specification for [`<position>`](https://drafts.csswg.org/css-values-4/#typedef-position) states that the 3-values syntax from `background-position` is generically forbidden from it.

This contradicts user agents in the wild, which all accept this supposedly-forbidden syntax everywhere `<position>` is used, such as in:

* `mask-position`;
* basic shapes' positions;
* `-radial-gradient()` position.

**Comment by tabatkins** [comment]
Yes, it's a recent decision (the April f2f meeting) to try and limit the usage of 3-value position as much as possible. We'll try and remove support for it from places where we can, and amend the definitions to explicitly use the 3-value-included production when proven necessary.

**Comment by nox** [comment]
@tabatkins Can I assume that the use sites I mentioned will be moved to `<bg-position>`?

**Comment by tabatkins** [comment]
As I said, if it proves necessary (that is, if compat prevents us from restricting them to the new `<position>`).

**Comment by nox** [comment]
Mmh, interesting, the 3-values syntax cannot be ambiguous in those sites, so why try to restrict them?

**Comment by tabatkins** [comment]
Because it's a learning hazard.  The 3-value syntax is basically a legacy mistake; there's no good reason to have it at all, and if we could remove it from every usage site, we would.

**Comment by nox** [comment]
Is there any intent from UAs to unship that syntax from the usage sites you have in mind?

**Comment by tabatkins** [comment]
We're going to attempt that, yes.

**Comment by ewilligers** [comment]
https://github.com/w3c/csswg-drafts/issues/2140 mentions progress in unshipping.
