### ISSUE TITLE
[css-align][css-grid] synthesized baselines are insufficiently specified

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#134]
I'm trying to understand what bullet 3 here means:
https://drafts.csswg.org/css-grid/#grid-baselines

What does "failing that" mean there?  I read it as, "if there
are no grid items", but I don't know if you mean synthesizing
a baseline from a grid item can fail in some way.  Furthermore...

https://drafts.csswg.org/css-align-3/#synthesize-baselines
"To synthesize baselines from a rectangle (or two parallel lines),
synthesize the alphabetic baseline from the lower line and the central
baseline by averaging the positions of the upper and lower lines."

I don't understand what precise code I should write to implement
this paragraph.  Does "averaging the positions" mean I should take
the distance between the two lines and divide it by 2 to get
the alignment baseline to use?  IOW, the synthesized baseline of
a content box is the center of the content box in the relevant axis?

**Comment by MatsPalmgren** [comment]
Oh, I think I got what CSS Align is saying now.  You're describing
two separate types of baselines in one sentence.  To synthesize
an _alphabetic_ baseline - use the lower line.  To synthesize _central_
baseline - use the half-way point between the two lines.

Could you perhaps rephrase it as two separate sentences to
make that clearer?

**Comment by tabatkins** [comment]
Oh, I see the confusion! Yay for ambiguous parses!

Yeah, I can rephrase that.

**Comment by MatsPalmgren** [comment]
While you're here, you might want to change the use of "upper" and
"lower" line which doesn't make much sense in a writing-mode world.
I'm guessing it means start-most and end-most in the relevant axis.

**Comment by tabatkins** [comment]
> What does "failing that" mean there? I read it as, "if there
are no grid items",

Yup, you got it. I've made it more explicit.

> Could you perhaps rephrase it as two separate sentences to
make that clearer?

I added a comma to separate the two instead, so you can't parse them as one extended clause anymore.

> While you're here, you might want to change the use of "upper" and
"lower" line which doesn't make much sense in a writing-mode world.

Yeah, rephrased slightly.
