### ISSUE TITLE
[css-syntax][css-transforms] NaN and Infinity in 'transform'

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#1343]
See https://github.com/w3c/fxtf-drafts/issues/120

The `DOMMatrix` API uses `unrestricted double` IDL type for its attributes, which can use NaN, -Infinity, Infinity. Then `matrix.toString()` might return e.g. "`matrix(Infinity, 0, 0, NaN, 0, 0)`". And that fails to parse when passed to `new DOMMatrix()` constructor since `Infinity` and `NaN` are invalid CSS keywords.

Why not add those keywords to CSS (and a new value type like &lt;unrestricted-number>)? They could still be invalid for everything other than 'transform' or some select places where they could make sense.

**Comment by tabatkins** [comment]
Why allow them?

**Comment by zcorpan** [comment]
https://lists.w3.org/Archives/Public/www-style/2013Sep/0670.html

**Comment by zcorpan** [comment]
Closing per https://github.com/w3c/fxtf-drafts/issues/120#issuecomment-300534962
