### ISSUE TITLE
[css-display-3] Clarify whether display: contents applies to ::before and ::after

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#1345]
I have a (probably bitrotted already) implementation for this in Blink, but I talked about this with @dbaron a while ago and asked me to file this in order to clarify it, given Gecko doesn't implement it.

Gecko always treats `display: contents` in `::before` and `::after` as `display: inline`. It's not clear to me whether display: contents in pseudo-elements is really useful at all, and the implementation is complex. 

It's pretty much non-observable, except for cases like https://github.com/w3c/web-platform-tests/blob/master/css/css-display-3/display-contents-before-after-002.html (where you specify reset properties on the pseudo, like `border`).

I think it's nice for consistency, but I wouldn't be too sad if it didn't apply to these pseudo-elements.

**Comment by Loirooriol** [comment]
It's not much clear, but browsers seem to believe that `display: contents` should join different texts into a single run of text (#1281). Then, in the following example, "FooBar" would be a single flex item:

```html
<div>Foo</div>
```
```css
div { display: flex; justify-content: space-between }
div::after { content: 'Bar'; display: contents }
```

So in this case whether `::before` and `::after` support `display: contents` or not is observable by other means than box-related properties on the pseudo-elements.

I think `display: contents` should apply to these pseudo-elements.

**Comment by tabatkins** [comment]
As @Loirooriol points out, it definitely has an observable effect, and is straightforward to define.  Basically, the following two bits of markup:

```css
<div><span>Foo</span>Bar</div>
```
and
```css
<div>Bar</div>
<style>div::before { content: "Foo"; }</style>
```

...should be completely indistinguishable as far as CSS is concerned.  There is no reason for the two to diverge in any way.

*That said*, I also wouldn't be too sad if we defined that it didn't work.  It's just inconsistent and breaks a constant that has nicely applied to ::before and ::after previously.

**Comment by tabatkins** [comment]
Closing as no change, because the WG decided to stick with it applying, and the effects of that just fall out of the definition.
