### ISSUE TITLE
[css3-positioning] [cssom] getComputedStyle should return "auto" for position:sticky if applicable

### ISSUE THREAD

**Issue by yi-gu** [w3c/csswg-drafts#1346]
Spec section: 
https://www.w3.org/TR/css-position-3/#sticky-pos
https://drafts.csswg.org/cssom/#resolved-values

According to the spec, top/bottom/left/right on getComputedStyle are used values for backwards compatibility with sites relying on the old definition of computed style. However, position offsets have special meaning for position sticky. getComputedStyle should return "auto" for the following element:
`<div style='position:sticky; top: auto;'></div>`
 instead of returning "0px" which is hugely misleading.

Currently, both Firefox 53, Safari 10 return "auto" in this case. Chrome 58 returns "0px" based on the spec but is about to [change](https://bugs.chromium.org/p/chromium/issues/detail?id=703816) to "auto" soon.

**Comment by tabatkins** [comment]
"auto" is definitely what we want.  Position doesn't define the used values properly, but a stickypos element should definitely retain "auto" in used values for t/r/b/l, as that's meaningfully different from a length.  (Vs an abspos, where they indicate "do some math for me to figure out the lengths to use", or relpos, where they just mean "0px".)

**Comment by RByers** [comment]
Thanks Tab.  Also take a look at @flackr's [results](https://bugs.chromium.org/p/chromium/issues/detail?id=703816#c13) for other types of positions across browsers.  It seems there's not really any interoperability here today and we should at least be more clear on what the spec says and ensure we have tests that are failing in some browsers.
/cc @gsnedders

**Comment by gsnedders** [comment]
We probably want to generalise this issue to cover the `position: fixed` case to, given that equally makes no sense and is probably little effort to do on top of this, looking at the Chromium bug.

**Comment by yi-gu** [comment]
Here is the chromium [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=720366&q=reporter%3Ame%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) w.r.t. the return value of fixed positioned elements.

**Comment by equinusocio** [comment]
Hi, what about return if the `position: sticky;` element is sticked or not? Maybe a pseudo-class `:stuck`?

**Comment by nainar** [comment]
@tabatkins as per @gsnedders suggestion should getting the computedStyle for the following: 

<div style='position:fixed; top: auto;'></div>

also return auto?

**Comment by tabatkins** [comment]
I'm not sure of @gsnedders’ reasoning for keeping "auto" around for fixpos. Fixpos is the same as abspos in this regard - "auto" is equivalent to some particular length. (In other words, you could replace the "auto" with an appropriate length and get identical behavior. This is not the case for stickypos.)

**Comment by gsnedders** [comment]
@tabatkins I have no preference here; I just meant the issue itself should consider behaviour for both `position: sticky` and `fixed` without any preference for what the return values should be.

**Comment by tabatkins** [comment]
Okay, well, since `fixed` is identical to `absolute` in behavior here, those two should remain consistent in their treatment. (And thus, continue to return a length as their used value no matter what.)

**Comment by nainar** [comment]
Thanks @tabatkins and @gsnedders :)

**Comment by dvoytenko** [comment]
FWIW, I believe both `position:fixed` and `position:absolute` should resolve `getComputedStyle` to `auto` for `top`/`bottom`/etc when this is what the rules say. It's misleading otherwise. Though, it sounds like there's a new API in works to make it less ambiguous?

**Comment by tabatkins** [comment]
Okay, looks like our rewrite of the spec no longer has any mention of "auto" values turning into anything else for stickypos, so they thus remain "auto" all the way thru to used values.  Since the other positioning schemes do change "auto" values, it *might* make sense to add a note highlighting the stickypos is different, but in normative terms it looks like we're covered now.

**Comment by gsnedders** [comment]
do we have any tests for this in wpt yet?

**Comment by mrobinson** [comment]
It seems that cssom/getComputedStyle-insets-sticky.html tests this behavior.
