### ISSUE TITLE
[css-geometry-1]  DOMMatrixReadOnly string init depends on backwards compatibility syntax

### ISSUE THREAD

**Issue by fserb** [w3c/csswg-drafts#1347]
Spec: https://drafts.fxtf.org/geometry/#dom-dommatrixreadonly-dommatrixreadonly

The `If init is a DOMString` step `3` references `Syntax of the SVG ‘transform’ attribute` of [css transform spec](https://drafts.csswg.org/css-transforms). That syntax is there, according to CSS transform spec:

> To provide backwards compatibility, the syntax of the [SVG] transform presentation attribute differs from the syntax of the [CSS] transform style property as shown in the example above. [...] Authors are advised to follow the rules of CSS Values and Units Module.

It doesn't make much sense to target a new spec with a syntax that is there only for backwards compatibility. I propose we change this `3rd` item to depend on the main CSS transform style syntax defined on CSS Values and Units.

Was there an underlying issue to reference DOMMatrix init with the backwards compatible SVG transform?

**Comment by zcorpan** [comment]
Could you file this at https://github.com/w3c/fxtf-drafts/issues/new?title=[geometry]%20 ? Thx

**Comment by fserb** [comment]
Done: https://github.com/w3c/fxtf-drafts/issues/149
