### ISSUE TITLE
[css-grid] Add baseline alignment as one of the examples for the 2nd pass of the algorithm

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1350]
The [track sizing algorithm](https://drafts.csswg.org/css-grid/#algo-overview) has the following note:
> This cycle is necessary for cases where the inline size of a grid item depends on the block size of its grid area. Examples include wrapped column flex containers (flex-flow: column wrap), orthogonal flows (writing-mode), and multi-column elements.

The list is just some examples, and it doesn't aim to be exhaustive, however we believe it'd be nice to add one more example in the list.

The case is the baseline alignment, for example:
```html
<div style="display: grid; align-items: baseline; border: solid thick;">
  <div style="background: magenta;">Item1<br>Several<br>Lines</div>
  <div style="background: cyan; font-size: 2em; grid-column: 2;">Item2</div>
  <div style="background: yellow; grid-column: 1 / 3;">Item3</div>
</div>
```

![Baseline alignment example that modifies the size of the first row](https://cloud.githubusercontent.com/assets/11602/25948470/d3233cb4-3653-11e7-8e82-2b638e45a42c.png)

In this case the first item (magenta) is moved down due to baseline alignment, so its [min-content contribution changes](https://drafts.csswg.org/css-align/#baseline-align-self).
This cause that we need to do a new pass of the algorithm to compute the size of the rows again.

Could you add this specific case to the list of examples? Thanks!

**Comment by fantasai** [comment]
Note: I just checked in some proposed changes (as green `<ins>` text) to [Resolve Intrinsic Track Sizes](https://drafts.csswg.org/css-grid/#algo-content) ([changeset](https://github.com/w3c/csswg-drafts/commit/02f01299c40db688b3fc514635b4734e03c3ac3e)) for #1039; if we accept those changes, this case wouldn't require a second pass.

**Comment by tabatkins** [comment]
As these changes have been accepted and editted in, this issue is now moot, so I'm closing it.

**Comment by tabatkins** [comment]
@mrego, can you confirm that this works for you?

**Comment by mrego** [comment]
Yes, I'm fine with this.
Thanks to that change we're avoiding the issue described here as we won't need the 2nd pass in this example.
