### ISSUE TITLE
[css-fonts-4] Make 'swap' use the same "tiny block period" as others

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1361]
Issue first reported and discussed here: https://github.com/tabatkins/specs/issues/53

(part of #1357)

Agenda+ since implementations are about to ship.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/6bdfe548c81ccf7581fbc8ebda717c99aea3c3a1
