### ISSUE TITLE
[css-fonts-4] Moving to "swap" should fallback elements rendered as invisible 

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1363]
Issue first reported and discussed here: https://github.com/tabatkins/specs/issues/46

(part of #1357)

Agenda+ since implementations are about to ship.

**Comment by frivoal** [comment]
cc @yoavweiss

**Comment by yoavweiss** [comment]
From my perspective @tabatkins answered the questions I had and corrected my misunderstanding, so no further action is needed.
