### ISSUE TITLE
[css-multicol-1][css-flexbox-1][css-grid-1] Clarify that column-* properties only apply to block containers

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#1364]
Currently, the Flexbox and Grid specifications explicitly exclude the `column-*` properties from applying to [flex](https://drafts.csswg.org/css-flexbox/#flex-containers) or [grid containers](https://drafts.csswg.org/css-grid/#grid-container).

As discussed in #1352, those exclusions should be removed from Flexbox and Grid and Multi-column be updated to clarify that these properties only apply to block containers.

Sebastian

**Comment by Loirooriol** [comment]
It's worth noting that table wrappers are technically block containers. Then, for table elements, should these properties apply to the principal table wrapper box (and thus work) or to the additionally-generated table box (and thus not work)? Analogous for block-level ruby.

**Comment by SebastianZ** [comment]
Thank you for fixing this, Florian!

I've created #1557 covering the removal of the now redundant exclusions of the `column-*` properties from the Flexbox and Grid Layout specifications.

Sebastian

**Comment by SebastianZ** [comment]
For reference, I've closed #1557 in favor of #1560, which doesn't include the merge commits.

Sebastian
