### ISSUE TITLE
[cssom-view-1] Can scrollIntoView param type be more specifc?

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/csswg-drafts#1367]
[The IDL of Element partial interface](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface) defines scrollIntoView receives `boolean` or `object`. Can the IDL be more specific and directly refer ScrollIntoViewOptions as other scroll methods do?

```
void scrollIntoView();
void scrollIntoView((boolean or object) arg);
void scroll(optional ScrollToOptions options);
void scroll(unrestricted double x, unrestricted double y);
void scrollTo(optional ScrollToOptions options);
void scrollTo(unrestricted double x, unrestricted double y);
void scrollBy(optional ScrollToOptions options);
void scrollBy(unrestricted double x, unrestricted double y);
```

**Comment by zcorpan** [comment]
Nope, unfortunately.

WebIDL requires dictionary arguments (unless they have required members) to be marked as `optional`. But legacy requires `scrollIntoView()` to be like `scrollIntoView(true)`. To achieve this the spec uses an overload and a union, and then converts the object to a dictionary in prose. There's no IDL syntax to achieve this weird-but-required-for-compat behavior.

**Comment by SaschaNaz** [comment]
Looking at the internal steps I think it still can be `void scrollIntoView(optional ScrollToOptions options);` and `void scrollIntoView(boolean arg);`, as it can still do the step `If arg is not specified or is true`.

**Comment by zcorpan** [comment]
No, that has different semantics. An omitted dictionary is equivalent to specifying `{}` per WebIDL. So with that IDL, the prose cannot differentiate between omitted argument and an empty dictionary.

**Comment by SaschaNaz** [comment]
Ah, you're right, my fault. But then how about `void scrollIntoView(optional (boolean or ScrollIntoViewOptions) arg = true);`? 

[Web IDL 2.2.3](https://heycam.github.io/webidl/#idl-operations)

>Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified.

>Dictionary types cannot have a default value specified explicitly, so the “unless otherwise specified” clause above can only be invoked for a union type that has a dictionary type as one of its flattened member types.

So I think this way it won't get the unwanted default empty dictionary value `{}`.

**Comment by zcorpan** [comment]
Hmmmm... yes, that could work, I think!

cc @bzbarsky to confirm.

**Comment by bzbarsky** [comment]
Presumably the point is that for compat we want `scrollIntoView()` to act like be `scrollIntoView(true)` but `scrollIntoView(undefined)` to act like `scrollIntoView(false)`; that was certainly the reason for the initial non-use of an optional argument here and use of an overload instead, back when the first arg of the overload was not a dictionary.  If that's the case, it sure would be nice if someone just wrote this down, in a note, or comment, or something, so we don't have to keep coming back to it over and over again.

That said, I don't think Gecko's current IDL for this (presumably based on an earlier spec draft?)  has this property.  It looks like this:

    void scrollIntoView(boolean top);
    void scrollIntoView(optional ScrollIntoViewOptions options);

where `ScrollIntoViewOptions` has `ScrollLogicalPosition block = "start";`.  So passing either no arg or `undefined` will give the same behavior as passing `{ block: "center" }` or `true`.  The IDL in the spec now does have the property that passing nothing and passing undefined have different behavior.  @zcorpan When was it changed from the thing Gecko implements and why?  That might tell us what's going on here.

**Comment by bzbarsky** [comment]
And ccing @kearwood because he might know what was going on with the Gecko behavior change there, when we went from:

    void scrollIntoView();
    void scrollIntoView(boolean top, optional ScrollOptions options);

to what we have now.

**Comment by zcorpan** [comment]
Thanks @bzbarsky. Yes, `undefined` is intended to be like `false`. There is a comment in the source; I should change that to a visible comment:

```
<!-- scrollIntoView() means arg=true but scrollIntoView(undefined) means arg=false, to align with impls. -->
```

Another thing is that passing `{}` is intended to be like `{ block: "center", inline: "center" }`, because that is argued to be a common case in https://www.w3.org/Bugs/Public/show_bug.cgi?id=17152

**Comment by zcorpan** [comment]
If Gecko already treats `undefined` the same as `true`, that suggests `undefined` meaning `false` is not a strong web compat invariant we need to maintain. If so, we can switch to
```
void scrollIntoView(optional (boolean or ScrollIntoViewOptions) arg = true);
```

**Comment by bzbarsky** [comment]
That's possible.  Have you tested what other UAs do?

**Comment by zcorpan** [comment]
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5238

Gecko/WebKit/Chromium treat explicit `undefined` like omitted argument and top-aligns.

EdgeHTML 15 treats it like `false` and bottom-aligns.

**Comment by bzbarsky** [comment]
Sounds like aligning to the majority behavior, which is also simpler to spec, is not unreasonable.  @travisleithead, would that be OK with you?

**Comment by zcorpan** [comment]
Spec PR to make the proposal a bit more concrete: https://github.com/w3c/csswg-drafts/pull/1505
