### ISSUE TITLE
[css-overflow] FPWD as a dependency for [css-contain]

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1374]
From today's transition call for css-contain: what is holding us back from FPWD of css-overflow-4 (which is a normative reference from css-contain-1).

**Comment by svgeesus** [comment]
Comments from Ralph Swick:
> Two questions, Chris.  These are probably best addressed in WG discussion.

> 1. What is holding up FPWD for CSS Overflow 4?  An FPWD can state what parts are less (or more) stable but a CR shouldn't depend upon something that is only an editors' draft, especially if the pertinent definitions have been improved.

> 2. Security considerations should include something about risks and counter-measures if a bad actor misuses these new features; e.g. to alter (and misrepresent) what is rendered to the user.

> Would it be appropriate to have some test cases that misuse the features and test what the implementation does in those situations?

**Comment by svgeesus** [comment]
Second part of that question copied over to a new issue https://github.com/w3c/csswg-drafts/issues/1376

**Comment by tabatkins** [comment]
On Mon, May 15, 2017 at 8:47 AM, Chris Lilley <notifications@github.com> wrote:
> From today's transition call for css-contain: what is holding us back from FPWD of css-overflow-4 (which is a normative reference from css-contain-1).

Doesn't matter; we don't *actually* depend on anything from
overflow-4, we impose a restriction on some of its features.  This is
just an interaction between the two specs; neither spec, on its own,
depends on the other in any way.

This *is* still property a normative reference; if you implement both
specs, these are indeed normative requirements on the interaction. But
they shouldn't count as holding back Contain.

~TJ

**Comment by svgeesus** [comment]
That doesn't answer the question of "what is holding back FPWD of overflow 3, though :)

**Comment by tabatkins** [comment]
I... don't understand the question. Who mentioned overflow-3?

If you meant overflow-4, my point is that it's irrelevant and shouldn't hold back contain-1, which is the subject of this thread.

The title of the issue and the contents of the first post do not agree on what the point of this thread is. >_<

**Comment by fantasai** [comment]
We actually have a FPWD of the features in Overflow 4: that was the original Overflow 3:
  https://www.w3.org/TR/2013/WD-css-overflow-3-20130418/

We cut down the features to what's already implemented in order to get a module that actually defines `overflow-x` and `overflow-y`. However, that spec still requires a lot of work. (Primarily QA/reverse-engineering work.) We should publish an Overflow 4 update as well, I think it hasn't been done because we're reluctant to have two early-stage Overflow WDs concurrently... and in this case the feature set in Overflow 4 isn't actively being update atm anyway.

**Comment by svgeesus** [comment]
Thanks fantasai, that helps explain the situation

**Comment by svgeesus** [comment]
Should I remove the agenda+, in that case?

**Comment by astearns** [comment]
forgot to close the logbot - here's the bit from the call today:

Topic: [css-overflow] FPWD for level 4
astearns: Is it correct that everything in 4 way already in 3?
Florian: Correct. No new features.
astearns: Any objections to FPWD of Overflow 4?
RESOLVED: FPWD of Overflow 4
Florian: I'll also make sure any L3 edits are reflected in L4.
fantasai: I'd recommend just dropping those sections.
Florian: That's better.

https://log.csswg.org/irc.w3.org/css/2017-05-17/#e810098

**Comment by frivoal** [comment]
Question: FPWD of overflow 4 is now in the pipeline. Is that enough to get css-contain going, or would it be better to move the interaction between `contain` and `continue` from css-contain to css-overflow-4? All the other things we need are in css-overflow-3.
