### ISSUE TITLE
[css-background] Change link to issue tracker

### ISSUE THREAD

**Issue by lahmatiy** [w3c/csswg-drafts#1377]
Current version of [CSS Backgrounds and Borders Module Level 3](https://drafts.csswg.org/css-backgrounds-3/) has a link to issue tracker `http://www.w3.org/Style/CSS/Tracker/products/11`. I suppose it should points to github. Is it correct?

**Comment by fantasai** [comment]
Yes. Fixed by spec conversion to Bikeshed. :)
