### ISSUE TITLE
[css-overflow] doesn't explain why 0px width and 0px height boxes produce different scrollable bounds

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#1380]
https://wptest.center/#/y4isq5

It seems that in Chrome and Firefox, the scrollable bounds of an element that has a 0px width is counted as if it had a width of 1px, but the same does happen for an element that as a 0px height. 

Edge doesn't count those elements in the scrollable bounds, without regards for the directionality of the nullity. I have the impression we have saner but less-compatible; we should probably update to match other browsers, but this behavior is not -- to my best knowledge -- defined anywhere.

-------------------

Neither 

> **The scrollable overflow region of a box is the union of:**
> - the box’s own content and padding areas 
> - all line boxes directly contained by the box 
> - the border boxes of all boxes for which it is the containing block, accounting for transforms by projecting each box onto the plane of the element that establishes its 3D rendering context. [CSS3-TRANSFORMS] 
> - the scrollable overflow regions of all of the above boxes (accounting for transforms as described above), provided they themselves have overflow: visible (i.e. do not themselves trap the overflow) and that scrollable overflow is not already clipped (e.g. by the clip property or the contain property). 
> - Optionally, additional padding on the end-edge sides, corresponding to the end-side padding of the scroll container, such that the end edges of its in-flow content coincide with the end edges of its content area when scrolled to the end. 
> 
> http://www.w3.org/TR/css-overflow-3/#scrollable

nor 

> **[The scrollable overflow of a box is the union of:]**
> - the box’s own padding edge (for the box itself) or border edge (for 3d-preserving descendant boxes) 
> - the bounds of any text directly in the box 
> 
> https://drafts.csswg.org/css-overflow/#scrollable-overflow

seem to mention the importance of directionality in the "union" result

**Comment by frivoal** [comment]
@FremyCompany just reminding you of this issue you raised. We're going to talk about css-overflow at the next F2F, so you may want to put this on the agenda. Up to you.

**Comment by tabatkins** [comment]
This was closed by #4791
