### ISSUE TITLE
[css-inline][css-display] Does the root inline box replace anonymous inline boxes?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1383]
CSS Display refers to CSS 2.1 for flow layout, and [9.2.2.1 Anonymous inline boxes says](https://www.w3.org/TR/CSS21/visuren.html#anonymous)

> Any text that is directly contained inside a block container element (not inside an inline element) must be treated as an anonymous inline element.

But [CSS inline](https://drafts.csswg.org/css-inline-3/#root-inline-box) says

> The *root inline box* is an anonymous inline box which is automatically generated to hold all of the inline-level contents of a block container (if it has any).

What happens first? Is the text first wrapped inside an anonymous inline box according to CSS2.1, and then further wrapped inside the root inline box, together with surrounding inline-level boxes?

Or are all inline-level contents (including text) wrapped inside the root inline box, and thus the text is no longer directly contained inside the block container, and therefore no additional anonymous inline box is created to wrap the text?

**Comment by dbaron** [comment]
The "root inline box" concept came later, and was *intended* (by me, at least) to replace the former rule on anonymous inline boxes that you quote.

**Comment by Loirooriol** [comment]
Thanks, that's what I suspected. I think this should be mentioned in a note or something, otherwise people will expect the quote from CSS2.1 to still apply, and won't be clear what should happen.

**Comment by tabatkins** [comment]
Added a note referencing this to Display, in the "block container" definition.
