### ISSUE TITLE
[css-inline][css-pseudo] Interaction of root inline box and ::first-line

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1384]
CSS Inline defines the [root inline box](https://drafts.csswg.org/css-inline-3/#root-inline-box) as

> The *root inline box* is an anonymous inline box which is automatically generated to hold all of the inline-level contents of a block container (if it has any).

CSS Pseudo-elements defines [`::first-line`](https://drafts.csswg.org/css-pseudo-4/#first-line-pseudo) as

> The `::first-line` pseudo-element’s generated box behaves similar to that of an inline-level element, but with certain restrictions.

> A user agent must act as if the fictional start tags of a `::first-line` pseudo-element were nested just inside the innermost enclosing block-level element.

So `::first-line` is a restricted inline-level, and inline-levels are wrapped inside the root inline box, which is inline, and inline-level fragments in the first line are wrapped inside the `::first-line`.

Which one is inside of which one?

**Comment by dbaron** [comment]
I think the root inline box should interact with ::first-line the same way any other inline boxes interact with ::first-line.  I'm not sure we actually agree on what *that* is, though...

**Comment by Loirooriol** [comment]
So the root inline box should be broken, and the fragment in the first line be wrapped inside `::first-line`?

I read your [Inline Box Model proposal](https://dbaron.org/css/2000/01/dibm), which says that each line has its own root inline box. And [Hixie's proposal](http://www.hixie.ch/specs/css/selectors/ProposedChanges.txt) further specifies that it's that root inline box in the first line what is matched by `::first-line`.

I think this made sense, but it seems currently there is a single root inline box in the block container instead of one per line. Maybe `::first-line` could be the fragment in the first line of the root inline box.

**Comment by fantasai** [comment]
@Loirooriol What question are you trying to answer, other than the obvious theoretical one?

**Comment by Loirooriol** [comment]
A practical implication would be #2282

**Comment by frivoal** [comment]
So I think that based on #2282, we've eliminated the possibility of `::first-line` being inside the root inline.

As for the remaining possibilities, I cannot think of a case where that would make a difference, but from a mental model point of view, I think I quite like defining ::first-line to **be** the fragment of the root inline box , rather than wrapping it. It's easier to keep track of fewer boxes, and avoids the need to worry about "Which one is inside of which one?".

**Comment by Loirooriol** [comment]
I don't think we can do that, because there can be multiple `::first-line` (each one originated by a different ancestor).

https://drafts.csswg.org/css-pseudo-4/#first-text-line

> When a [first formatted line](https://drafts.csswg.org/css-pseudo-4/#first-formatted-line) is represented by multiple [::first-line](https://drafts.csswg.org/css-pseudo-4/#selectordef-first-line) pseudo-elements, they are nested in the same order as their [originating elements](https://drafts.csswg.org/selectors-4/#originating-element).
