### ISSUE TITLE
[css-cascade] Are 'Override declarations' still a thing?

### ISSUE THREAD

**Issue by SelenIT** [w3c/csswg-drafts#1385]
Historically, the CSS Cascading and Inheritance spec [lists](https://drafts.csswg.org/css-cascade/#cascade-origin) 'Override declarations' among other cascading origins. But it appears that the spec that they refer to [has never been really implemented](http://stackoverflow.com/a/41417273/2533215), and 'Override declarations' are now a purely theoretical concept with no connection to the reality. What about dropping them at all, in order to make the cascading algorithm simpler?

**Comment by birtles** [comment]
SMIL uses the override level of the cascade for its animation results. However, that was defined before the animations level of the cascade was added and it should probably just contribute to the animations level of the cascade (with CSS animations defined to override SMIL animations as they currently do).

**Comment by SelenIT** [comment]
If I understand correctly, the only place where SMIL spec mentions override CSS declarations [refers](https://www.w3.org/TR/smil/smil30.html#smil-animation-animationNS-AnimationSandwichModel) to the Section 6.1 of the CSS2 spec and to the DOM2CSS spec. Since the formef has currently been superseded by CSS Cascade 3 and the latter seems to be abandoned (probably replaced by CSSOM spec?), maybe we can already make a note in the next level of the Cascade spec like "reference to Override styles in older animation-relates specs should be treated as reference to Animation styles" and simplify the cascade definition?

**Comment by ByteEater-pl** [comment]
Why is there no such note in CSS Cascading and Inheritance Level 4 Editor’s Draft? And what was the implementors' problem with this origin?
