### ISSUE TITLE
[css-fonts] Specify font-language-override as a @font-face descriptor

### ISSUE THREAD

**Issue by nox** [w3c/csswg-drafts#1392]
https://bugzilla.mozilla.org/show_bug.cgi?id=1355364
https://lists.w3.org/Archives/Public/www-style/2017Feb/0028.html

**Comment by litherum** [comment]
We resolved during the Tokyo F2F to do this. I believe there is an outstanding pull request for me to take.

**Comment by litherum** [comment]
Done in https://github.com/w3c/csswg-drafts/commit/e18ba0541e49cc7c5901682ce6fe59ed518af61b

**Comment by litherum** [comment]
Oh wait, this wasn't done yet.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/e0f8bba1471013160028988f1efdfda65fca5634

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/f87f2b35abc12cd119ec0ef82c4d0436a3bbb9f2
