### ISSUE TITLE
[css-align] Values section shouldn't point wholesale to CSS Level 2

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1397]
The [Values section](https://drafts.csswg.org/css-align/#values) of css-align currently says:

> This specification follows the CSS property definition conventions from [CSS2]. Value types not defined in this specification are defined in CSS Level 2 Revision 1 [CSS2].

I think the section this points to has become sufficiently out-of-date by this point that it's probably best to point mostly to the relevant level 3 modules rather than level 2.  Most drafts don't have a section like this one, and I don't think such a section would be needed if bikeshed implemented https://github.com/tabatkins/bikeshed/issues/617

**Comment by fantasai** [comment]
I think for people reading in a non-interactive format (like print), having this statement in addition to the bikeshed links would be useful. That said, updating the boilerplate is probably a good idea; as is making sure it is consistently applied across all of our specs. This Values section is part of our module template.

**Comment by tabatkins** [comment]
On the other hand, these Values sections are usually *straight* boilerplate, copypasted from other specs without really looking, and then left to rot. This spec's Values section shows that off in spades - it has a weird separate treatment of "initial" and "inherit", and doesn't mention the other global values. It should instead just talk about global values and point to Cascade.

We should figure out how to work this into our actual boilerplate so people wont' have to worry about it.

**Comment by fantasai** [comment]
Proposed replacement: 
```
This specification follows the <a href="https://www.w3.org/TR/CSS21/about.html#property-defs">CSS property definition conventions</a> from [[!CSS2]].
Value types not defined in this specification are defined in CSS Values & Units [[!CSS-VALUES-3]].
Other CSS modules may expand the definitions of these value types.

In addition to the property-specific values listed in their definitions,
all properties defined in this specification
also accept the <a>CSS-wide keywords</a> keywords as their property value.
For readability they have not been repeated explicitly.
```

**Comment by fantasai** [comment]
Agenda+ to get review on updating across all specs.

**Comment by tabatkins** [comment]
Which is to say: I updated all the specs that had a Values section to match this wording; I'm happy to do further updates if the WG wants a different boilerplate.  

(There's only 21 specs with a Values section:

* css-align
* css-animations
* css-backgrounds
* css-break
* css-display
* css-line-grid
* css-position
* css-ruby
* css-scroll-snap
* css-shapes
* css-size-adjust
* css-sizing-3
* css-sizing
* css-speech
* css-text-decor-4
* css-text-decor
* css-text
* css-transforms-2
* css-transforms
* css-writing-modes-3
* css-writing-modes

)

**Comment by svgeesus** [comment]
> There's only 21 specs with a Values section:

Does that mean the others don't need one, or just that they don't have one (and should)? I'm finding it difficult to think of a CSS spec (except for Selectors and Namespaces) which won't use values.

**Comment by tabatkins** [comment]
Mostly "don't have one, but could possibly use one". Tho my position is stated in an earlier comment - this is boilerplate, and should be put in the boilerplate section somehow.

(If I can copy-paste the exact same text between 21 specs, and theoretically another 20 or so, then it's *not* something that should be hand-written into specs.)
