### ISSUE TITLE
[css-align] Do all alignment subjects *have* a containing block?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1399]
The [Terminology section](https://drafts.csswg.org/css-align/#terms) of css-align says:

> <b><i>alignment container</i></b>
>    ... This is defined by the layout mode, but is usually the alignment subject’s containing block.

It's not clear to me, however, that all alignment subjects *have* a containing block.  The [definition of containing block](https://drafts.csswg.org/css-display-3/#containing-block) that I found isn't particularly clear about what *has* a containing block -- whether a box has a containing block, or whether a box's margin box has a containing block.

This should probably be clearer, although it's probably doesn't need to be addressed in order to go to CR.

**Comment by fantasai** [comment]
It doesn't matter if all alignment subjects have a containing block or not -- the definition clearly says it's defined by the layout mode. It also says it's *usually* the alignment subject's containing block, but in the cases where it's not, well, that doesn't fall under the usually case. (The usually clause is there to make the spec easier to understand, so everything is not so abstract all the time until you dig 5 layers of definitions deep. At least this way you quickly get the gist of the concept.)
