### ISSUE TITLE
[css-speech] Link syntaxes with CSS Values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#140]
The combinators and multipliers within the syntaxes in CSS Text 3 should link to the CSS Values module like other modules.

Sebastian

**Comment by fantasai** [comment]
CSS Speech is on the old spec preprocessor. This will get fixed once it's converted.

**Comment by SebastianZ** [comment]
> CSS Speech is on the old spec preprocessor. This will get fixed once it's converted.

Right. I've created issue #251 covering the conversion.

Sebastian

**Comment by SebastianZ** [comment]
CSS Speech uses Bikeshed now and with that the syntaxes are linked.

Sebastian
