### ISSUE TITLE
[css-align] positional alignment values depend on alignment subject and container (rectangles) having direction and writing-mode

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1400]
Many of the [positional alignment keywords](https://drafts.csswg.org/css-align/#positional-values) depend on a start-edge or end-edge of either the alignment container or the alignment subject.  This, in turn, require knowing [a direction and writing mode](https://drafts.csswg.org/css-writing-modes/#logical-to-physical).  However, the terminology section above defines the alignment container and the alignment subject as rectangles, which don't have these things.

It seems to me that the alignment container and alignment subject need to be defined as a rectangle associated with a box (or other source of direction and writing mode), and the definitions should be clear about which is the associated box (or direction/writing-mode).  (I think the definitions are *probably* mostly obvious, but I could imagine somebody misinterpreting, e.g., for things like flex lines, grid tracks, or column boxes.)

(There's also mixing of the terms "start edge" and "start side", which should probably be used more consistently... unless there's a distinction that I'm missing.  They're not links, so it's hard to know!)

**Comment by tabatkins** [comment]
Okay, we've defined that the alignment subject/container have writing modes, and defined how they obtain them in all circumstances. Commits are 7a3b35639, f44c052d8, and 01ab57457.

Our usage of "edge" vs "side" is fairly regular - we use "side" when we're referring to a direction, and "edge" when we're referring to the actual edge of the box.
