### ISSUE TITLE
[css-align] definition of 'flex-start' and 'flex-end' are changed (relative to flexbox) to apply to out-of-flow children of flex containers

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1402]
The [definition of `flex-start`](https://drafts.csswg.org/css-align/#valdef-self-position-flex-start) and [of `flex-end`](https://drafts.csswg.org/css-align/#valdef-self-position-flex-end) currently say:

> When used on boxes that are not children of a flex container, this value behaves as start. 

There's also a subtle difference between [flex items](https://drafts.csswg.org/css-flexbox-1/#flex-item) and the "children of a flex container" term used here, since flex items are *in flow* children of a flex container.  Perhaps this should specify flex items?  Or does it intend to apply to out-of-flow children of a flex container as well?  If so, that's a change from flexbox that should probably be noted explicitly, since it's not obvious.

**Comment by tabatkins** [comment]
Yeah, not sure why we went with the "children of a flex container" wording; we really mean flex items, and things pretending to be flex items (such as when figuring out the static position of an an abspos child of a flex container). New wording in the commit above.
