### ISSUE TITLE
[css-align] "fallback-aligned insofar as possible" is vague

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1405]
The [definition of baseline alignment values](https://drafts.csswg.org/css-align/#baseline-values) says:

> If an alignment subject’s position is not fully determined by baseline alignment it and the other participants in its baseline-sharing group are fallback-aligned insofar as possible while preserving their baseline alignment.

This sentence is unclear in a number of ways
* the "If an alignment subject's position" should really refer to the set of positions, since all the positions in the shared alignment context are determined together
* it should probably be clearer that what "not fully determined" means is that the maximum extents (e.g., highest top and lowest bottom) of the things in the context don't fill the container
* what "insofar as possible" means is that for start (end) alignment, the most extreme start (end)-edge in the group is aligned with the start (end) edge of the alignment container

**Comment by fantasai** [comment]
Okay, we've adjusted the wording in the spec to try to make it clearer. However, your definition in bullet 3 is incorrect: if two baseline-sharing items are being baseline content-aligned, and the first item has a smaller first line, but some large padding-top, the "insofar as possible" will slide the baseline-aligned contents up until the top of the contents of the first item hit the padding edge, leaving the second (higher) contents still not touching the top edge of their containing block. So we could not use your definition. That said, we think the result is sufficiently clear as to what's intended.
