### ISSUE TITLE
[css-align] "compatible baseline alignment preferences" is ambiguous

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1407]
The [section on Baseline Alignment Terminology](https://drafts.csswg.org/css-align/#baseline-terms) begins with a [definition of baseline sharing group](https://drafts.csswg.org/css-align/#baseline-sharing-group), whose second point is:

> * Have compatible [baseline alignment preferences](https://drafts.csswg.org/css-align/#baseline-alignment-preference) (i.e., the baselines that want to align are on the same side of the alignment context). 

The "baseline alignment preferences" link currently defines the preferences as `first` or `last`.

This measn that the text outside the parenthetical seems to imply that "compatible" means that a group consists of the items that are all `first`, or separately of the items that are all `last`, whereas the parenthetical seems to imply that the group should be matched by the physical side.  This could matter for, say, baseline alignment of `vertical-lr` and `vertical-rl` table cells against each other.

I think it makes more sense to group by physical side rather than by first/last.

**Comment by dbaron** [comment]
Oh, actually, there's prose saying what I want later in the section, "compatible" just needs to be a link to it.  (And maybe it should be a unique term.)

**Comment by fantasai** [comment]
Fixed by dfn'ing the term and linking across.
