### ISSUE TITLE
[css-align] initial definition of "first/last baseline set" is incorrect

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1408]
The [definition of first (last) baseline set](https://drafts.csswg.org/css-align/#first-baseline-set) starts off with a sentence:

> The first baseline set (and last baseline set) of a box for a given axis is the baseline set nominally associated with the first (last) line of text within the box.

that is basically incorrect, and quite confusing.  The paragraph below then correct this sentence.

But I found this sentence wrong enough (multiple times) while trying to understand the baseline alignment stuff in this spec that I think it should be removed or rephrased to be much more deferential to the per-layout-mode definitions in the paragraphs below it.

(Perhaps part of my issue is that I view the word "line" as a technical term related to inline layout.)

**Comment by fantasai** [comment]
I have no idea why you find this sentence confusing. This is fundamentally what baseline alignment is about. Obviously there are cases where we don't have text to work with, and then we have to make things up, but the sentence does specify “nominally”.

It is important to me that we have up-front definitions that are about the fundamental goal of what we're doing. Jumping straight into obtuse technical details with full exposition of edge cases without any conceptual high-level description does not help the spec make sense imho.

**Comment by astearns** [comment]
Would it help to replace 'line' in the sentence with something a bit fuzzier - “…the first (last) visible text within the box” or “…the first (last) displayed text within the box”?

**Comment by dbaron** [comment]
So if the goal is to give a general description, how about replacing the sentence with something like:
> Each box, for a given axis, has a **first baseline set** (and **last baseline set**) that corresponds roughly to the first (and last) line of text in the box.

(I'm not entirely sure what the "for a given axis" means, though.)

**Comment by fantasai** [comment]
OK, we fixed it as you requested, with a few minor modifications (like using “nominally” rather than “roughly”, which is definitely more in line with what we mean here). Let us know if you have any further concerns!
