### ISSUE TITLE
[css-align] is the subtle syntax difference between align-self and justify-self intended?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1412]
Right now the "Value:" line for [align-self](https://drafts.csswg.org/css-align/#align-self-property) and [justify-self](https://drafts.csswg.org/css-align/#justify-self-property) are almost but not quite the same; they differ by a single "&&".  So in align-self the &lt;overflow-position>? must come before the &lt;self-position>, whereas for justify-self they're allowed in either order.

This syntax difference seems undesirable.

**Comment by dbaron** [comment]
align-content, justify-content, align-items, and justify-items all match align-self.  So it seems like the && in justify-self is the odd one out.

**Comment by dbaron** [comment]
And there are also matching differences in the value definitions in the &lt;dl> below.

**Comment by fantasai** [comment]
This was an error in applying the resolution for fixing the order; looks like I cleaned it out already, so closing as fixed.
