### ISSUE TITLE
[css-align] "aligned subtree" isn't a good term for something that isn't a tree

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1414]
In inline layout, the term "align subtree" refers to something that's tree-shaped:  the layout of an element and its descendants, possibly with some of the descendants excluded.

css-align [uses the term](https://drafts.csswg.org/css-align/#aligned-subtree) to refer to a set of elements in a baseline-sharing group and all of their descendants.  There might be other siblings that aren't part of the group, so this isn't a tree, and I think it shouldn't be referred to as one.

**Comment by dbaron** [comment]
I actually don't think a term is needed here; it can just refer to the boxes in the baseline-sharing group.

**Comment by fantasai** [comment]
Fixed as requested.
