### ISSUE TITLE
[css-align] note about what CSSOM requires should link to the section

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1415]
The [section on baseline alignment values](https://drafts.csswg.org/css-align/#baseline-values) says: 

> Note: Because they are equivalent, and baseline is shorter, the CSSOM serializes first baseline as baseline.

This should link to the definition in question.  (I'm curious where it is, or if it exists!)

**Comment by fantasai** [comment]
The definition <em>was</em> here, in AnneVK's draft:
  https://www.w3.org/TR/2011/WD-cssom-20110712/#serializing-css-values
But it seems to have disappeared in the next revision by Glenn and zcorpan:
  https://www.w3.org/TR/2013/WD-cssom-20131205/#serializing-css-values
We've filed an issue on this regression: https://github.com/w3c/csswg-drafts/issues/1564
We'll update with a link once that's fixed.
