### ISSUE TITLE
[css-align] smart / scroll-safe overflow alignment should be more prominent

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1416]
It's possible to read the title of the [section on overflow alignment](https://drafts.csswg.org/css-align/#overflow-values), the first two paragraphs of it, and the value definitions in the without realizing that it actually specifies *three* values.

This is partly because it seems odd to specify a default value that doesn't have a name -- perhaps it should have a name?  (`scroll-safe`?)

But whether or not it has a name, it should be a good bit more prominent in the title, the second paragraph of the section, and the example.

**Comment by tabatkins** [comment]
Fixed in c0e927cdf
