### ISSUE TITLE
[css-align] Issues with "Applies to:" line of align-content and justify-content

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1417]
The [definitions of `align-content` and `justify-content`](https://drafts.csswg.org/css-align/#content-distribution) both have the same:

> Applies to: 	block containers, flex containers, and grid containers

There are two issues with this.

First, the [details per layout mode on block containers](https://drafts.csswg.org/css-align/#distribution-block) say there that `justify-content` doesn't apply to block containers.  It seems like that should be reflected in the "Applies to" line.

Second, the [details per layout mode on multicol containers](https://drafts.csswg.org/css-align/#distribution-multicol) exists and defines how they apply, yet they aren't reflected in the "Applies to" line.  ([column boxes](https://drafts.csswg.org/css-multicol/#column-box) are block containers, but as far as I can tell the [multicol itself is not](https://drafts.csswg.org/css-display-3/#block-container).)

**Comment by tabatkins** [comment]
Fixed in c2b4cddb0
