### ISSUE TITLE
[css-align] details for multicol containers for align/justify-content don't consider column-span

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1418]
The [details for multicol containers](https://drafts.csswg.org/css-align/#distribution-multicol) for how `align-content` and `justify-content` seem to assume that multicol containers only contain column boxes.  However, with `column-span: all` this isn't really true:  they contain a sequence of:
 * an anonymous box (undefined!) that wraps a set of column boxes
 * an box with `column-span: all`

(Also, I'm not sure "multicol containers" is a defined term, but there probably should be a term!)

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/7da8c25f25a7524c11bd79bc0623a1d5a1161a23, thanks!
