### ISSUE TITLE
[css-flexbox-1] In section 9.9.1, the link for "max-content contributions" of flex items should point to flex-item-specific text

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#1419]
[Flexbox section 9.9.1 "Flex Container Intrinsic Main Sizes"](https://drafts.csswg.org/css-flexbox/#intrinsic-main-sizes) starts out like so:
> 1. For each flex item, subtract its outer flex base size from its max-content contribution size.

Here, "max-content contribution size" is linked to the [generic text about max-content contributions](https://drafts.csswg.org/css-sizing-3/#max-content-contribution) in CSS3-Sizing.  This isn't particularly helpful in hinting at what quantity should actually be used in the arithmetic described here.

Instead, that term should link to [Flexbox section 9.9.3 "Flex Item Intrinsic Size Contributions"](https://drafts.csswg.org/css-flexbox/#intrinsic-item-contributions) which is where we actually mathematically define what the contribution should be *for a flex item*.

**Comment by dholbert** [comment]
I believe there are 5 links that need updating.  Two at the beginning of this section (bolded):
> "...while maintaining the **max-content contributions** of its flex items..."

> 1. For each flex item, subtract its outer flex base size from its **max-content contribution** size.

And three more at the end (bolded):
> The min-content main size of a single-line flex container is calculated identically to the max-content main size, except that the flex item’s **min-content contribution** is used instead of its **max-content contribution**. However, for a multi-line container, it is simply the largest **min-content contribution** of all the flex items

**Comment by dholbert** [comment]
Note that section 9.9.3 (the section that I'm suggesting we link to) *does* contain links to the general CSS3-Sizing definitions of min/max-content contributions.

So we'd still have those definitions wired up here -- we'll just be linking to the more specific & relevant definitions first.

**Comment by fantasai** [comment]
Fixed, thanks!
