### ISSUE TITLE
[css-align] "whichever matches its inline axis" is ambiguous

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1423]
The [section on Baseline Content-Alignment](https://drafts.csswg.org/css-align/#baseline-align-content) says:

> A grid item participates in first (last) baseline content-alignment in its startmost (endmost) row or column (whichever matches its inline axis) if...

The "(whichever matches its inline axis)" here is ambiguous.  It's not clear what "matches" means.

I think the parenthetical should instead say "(whichever axis is parallel to its inline axis)".

**Comment by dbaron** [comment]
Though, really, they could be either parallel or anti-parallel, they just can't be perpendicular!

**Comment by javifernandez** [comment]
I filed issue #425 under the same rationale for Baseline Self-Alignment. As a matter of fact, such text was removed from the Baseline Self-Alignment prose in commit  #2698f3c

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/5a9bbe945978c099f093c0eb314cedb2c7edce72, thanks! (We don't think anti-parallel is a relevant consideration here, they're not directional and in general English anti-parallel is a subset of parallel anyway.)
