### ISSUE TITLE
[css-align] "effectively aligns its start (end) edge with the other boxes in its baseline-sharing group" is confusing

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1424]
While trying to understand baseline content-alignment, I struggled a number of times with the phrase "effectively aligns its start (end) edge with the other boxes in its baseline-sharing group" near the end of the [section on Baseline Content-Alignment](https://drafts.csswg.org/css-align/#baseline-align-content).

It wasn't clear to me what this is trying to say.  And in some ways it's still not clear, even assuming that you don't reduce the constraints that *might* make #1411 a non-issue.

I suppose what it's trying to say is that the constraints on when boxes can participate in baseline content-alignment mean that the margin-edge of all of the boxes will already be aligned before you start the baseline content-alignment process.  But I think this is a result of those constraints, and something that's "already happened" as part of self-alignment (even though I think technically self-alignment happens *after* content-alignment in the block dimension), not something that happens as part of the baseline content-alignment process.

**Comment by fantasai** [comment]
Fixed by deleting the offending sentence. :) The relevant information was already part of an earlier paragraph.
