### ISSUE TITLE
[css-align] are there compatibility issues with replacing overconstraint rules from CSS2?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1428]
The [rules for `justify-self` on blocks](https://drafts.csswg.org/css-align/#justify-block) and the [rules for `justify-self` on Absolutely-Positioned boxes](https://drafts.csswg.org/css-align/#justify-abspos) specify that they replace the overconstraint rules in CSS Level 2 with the rules for justify-self.  This replacement is *not* scoped to values other than `normal`.  I think that is *probably* a good thing.

However, one issue where the overconstraint rules have come up is the question of what `getComputedStyle()` returns for the used values of `margin` (for block) or offset (for abspos) properties.  My memory is that this generally hasn't been particularly conformant to a literal reading of the spec, but this may have changed.

I think it's worth investigating what implementations do for `getComputedStyle()` and margins, and then either:
* scoping this replacement to non-`normal` values (which in some sense would introduce inconsistency), or
* adding a note that this replacement is intentionally intended to include `normal` values as well, and therefore that the used values of margins (for blocks) or offsets (for abspos) are no longer expected to be adjusted for overconstraint.

**Comment by dbaron** [comment]
This also applies to the [rules for `align-self` on Absolutely-Positioned boxes](https://drafts.csswg.org/css-align/#align-abspos).

**Comment by dbaron** [comment]
Also, any differences from CSS 2.1 should be noted explicitly.

**Comment by tabatkins** [comment]
Testing:

# Horizontal, block

```
<!DOCTYPE html>
<div>
 <child>foo</child>
</div>
<style>
div {
width: 300px;
border: solid;
}
child {
display: block;
background: rgba(0,0,0,.2);
width: 100px;
margin: 0 50px;
}
</style>
<script>
var s = getComputedStyle(document.querySelector("child"));
console.log(s.marginLeft);
console.log(s.marginRight);
</script>
```
Result: both Chrome and Firefox return "50px" for both margins, compatible with Align. (They do *not* apply the fixup in an author-observable way.)

# Horizontal, abspos

```
<!DOCTYPE html>
<div>
 <child>foo</child>
</div>
<style>
div {
width: 300px;
height: 100px;
border: solid;
position: relative;
}
child {
position:absolute;
background: rgba(0,0,0,.2);
width: 100px;
margin: 0 50px;
left: 0;
right: 0;
}
</style>
<script>
var s = getComputedStyle(document.querySelector("child"));
console.log(s.marginLeft);
console.log(s.marginRight);
console.log(s.left);
console.log(s.right);
</script>
```
Result: Chrome returns "50px" for both margins and "0px" for both insets, compatible with Align. Firefox returns "100px" for 'right', exposing the used-value fixup in an observable way.

# Vertical, abspos

```
<!DOCTYPE html>
<div>
 <child>foo</child>
</div>
<style>
div {
width: 300px;
height: 100px;
border: solid;
position: relative;
}
child {
position:absolute;
background: rgba(0,0,0,.2);
width: 100px;
height: 50px;
margin: 10px;
top: 0;
bottom: 0;
}
</style>
<script>
var s = getComputedStyle(document.querySelector("child"));
console.log(s.marginTop);
console.log(s.marginBottom);
console.log(s.top);
console.log(s.bottom);
</script>
Result: Chrome returns "10px" for both margins and "0px" for both insets, compatible with Align. Firefox returns "30px" for 'bottom', exposing the used-value fixup in an observable way.

**Comment by tabatkins** [comment]
So looks like Chrome is compatible with the Align text in all cases, but Firefox is only compatible for block flow; for abspos elements, Firefox exposes the fixup and is thus inconsistent with Align.  Since browsers are inconsistent, I suspect we can make this change (at least, Align seems to be honored *more closely* than 2.1 is).

> Also, any differences from CSS 2.1 should be noted explicitly.

Isn't that what the "rules in [2.1] are ignored in favor of alignment as specified here" is saying?

**Comment by fantasai** [comment]
The prose is in the form
> In terms of CSS2.1 formatting [CSS2], the rules for “over-constrained” computations in section 10.3.7 are ignored in favor of alignment as specified here, and the used value of the inset properties are not adjusted to correct for the over-constraint. 

which explicitly specifies a) that it overrides CSS2.1 and b) that used values are affected as we're discussing here. Since resolved values are defined to reference used values, this means the spec should be sufficiently clear on this point.

Adding Agenda+ just to verify with the WG about overriding CSS2.1.

**Comment by gregwhitworth** [comment]
To add to this, Edge produces the same results as Chrome for both test cases.

**Comment by tabatkins** [comment]
Since Align already says it overrides 2.1, there's no change to be made. Closing, but if @dbaron thinks there's anything left to do, please ping this bug. ^_^
