### ISSUE TITLE
[css-align] should justify/align-self on abspos elements apply when offsets are 'auto'?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1429]
The [rules for `justify-self` on absolutely-positioned boxes](https://drafts.csswg.org/css-align/#justify-abspos) and the [rules for `align-self` on absolutely-positioned boxes](https://drafts.csswg.org/css-align/#align-abspos) both currently say that the property is ignored if either offset property in this dimension is `auto`.

First, this should be clearer that an "offset property" is `top`, `right`, `bottom`, or `left` or its logical equivalents (whatever we end up calling them).

However, this rule didn't match my expectation for how this property would behave in this case.  I would have expected the rule to instead be that any `auto` values would be treated as `0`, and then the property would apply.  (It seems better to honor the thing the author asked for than to ignore it, especially when it's this simple!)

Was there a reason not to do this?

**Comment by dbaron** [comment]
Note that doing this does require modifying the `normal` behavior to also be `start` rather than `stretch` when the self-end side offset is zero.  (Or is it end-side rather than self-end-side???)

**Comment by dbaron** [comment]
Or is the intent instead that the rules in the following sections on "Static Position of Absolutely-Positioned Boxes" apply instead?  If so, maybe say that?  (I'm still trying to understand what those rules mean.)

**Comment by dbaron** [comment]
... though if that's the case, there are still some cases where there are some `auto` values but the static positioned isn't used, that fall through the gaps.

Also see #1432.

**Comment by tabatkins** [comment]
Added another parenthetical to address the clarification issue...

Wrt treating a single `auto` as `0`, we decided against it because it would be inconsistent with how auto margins behave, and also would break current behavior in at least some cases. For example, `left: auto; width: 100px; right: 0;` should right-align the abspos, but if we let justify-self apply it would get left-aligned (as the fallback for `stretch`).  We could potentially make `normal` magical here, and let non-`normal` values apply by treating the lone `auto` as `0`, but we try to have `normal` be as close to another equivalent value as possible.

More discussion of double-`auto` in #1432.

**Comment by dbaron** [comment]
I think it would still be helpful to make "inset property" be a hyperlink so people know what it means.

I guess I have a somewhat different opinion of `normal`:  I think what we're trying to do here is build a better set of alignment properties.  So in the cases where the existing behavior is weird, it seems good to limit that weirdness to `normal` and have all the non-default values do more reasonable things.  And in this case it seems pretty reasonable to honor the property in that case.

**Comment by tabatkins** [comment]
We ended up realizing that you were right, and that static position of abspos elements *should* be affected by justify/align-self.  This is now reflected in <https://drafts.csswg.org/css-align-3/#abspos-sizing> for *sizing* the element, and <https://drafts.csswg.org/css-align-3/#align-abspos> (with details in <https://drafts.csswg.org/css-align-3/#static-position-rectangle>) for positioning. 

This was all done as part of #1432. Does this satisfy your concerns?

**Comment by fantasai** [comment]
No response in nearly three months, and also no response to multiple queries of "did you want to review this issue", so closing out as timed out.
