### ISSUE TITLE
[css-fonts] Link syntaxes with CSS Values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#143]
The combinators and multipliers within the syntaxes should link to the CSS Values module like other modules.

Sebastian

**Comment by xfq** [comment]
css-fonts-3 does not use Bikeshed, but the combinators/multipliers in css-font-4 already links to V&U now.

**Comment by fantasai** [comment]
Closing as "wontfix for now; will be automatically fixed if/when css-fonts-3 switches to bikeshed". (Closing because either way it doesn't need to be tracked.)
