### ISSUE TITLE
rename references to "offset properties" to "inset properties"

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1430]
Now that the `offset-*` properties in writing modes have been renamed to the [`inset-*` properties](https://drafts.csswg.org/css-logical/#inset-properties), it seems like the references to the "offset properties" or "box offset properties" should instead be to the "inset properties" or "box inset properties", to match the names of the properties.

We should also probably have a defined term for these that we can link to.

**Comment by fantasai** [comment]
Yeah, the definition would go into the mostly-unmaintained css-position, though. :/
