### ISSUE TITLE
[css-align] Rules for align/justify-self on static position of absolutely-positioned boxes need more detail

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1432]
The alignment spec has [rules for applying `justify-self` to the static position of absolutely-positioned boxes](https://drafts.csswg.org/css-align/#justify-abspos-static) and similar [for `align-self`](https://drafts.csswg.org/css-align/#align-abspos-static).  This section is quite opaque, and could perhaps use an introduction.

I think what this section is trying to say is that for absolutely positioned elements that use their static position, they're aligned within their static-position rectangle (formerly "hypothetical box") using the align-self and justify-self properties.  If that's the idea, it would be nice to have a little bit of prose saying that, and explaining the relationship to the previous section.

But there are also a number of other issues:
* unlike the two sections (for blocks and absolutely-positioned elements) preceding each of these sections, they don't specify any rules about overriding the rules for over-constrained situations, and therefore if the intent is as described above, I think it doesn't actually work
* I don't understand what " The box’s margin box after laying out the box, treated as fixed-size for the purpose of alignment." means
* I don't understand what "(as the fallback for stretch for fixed-size boxes)" means.

**Comment by dbaron** [comment]
Also, for what it's worth, the static position affects the size, since abspos boxes do fit-content sizing inside an available width that's derived from one side being the static position and the other side coming from the containing block... so it's also not entirely clear to me how this section holds together in terms of order of operations.

**Comment by fantasai** [comment]
Fun tests for future reference...
```
http://software.hixie.ch/utilities/js/live-dom-viewer/?<!DOCTYPE html>%0A<style> %0A html { border%3A solid gray%3B width%3A 10em%3B margin%3A 3em%3B height%3A 2em%3B display%3A flex%3B justify-content%3A flex-end%3B }%0A body { position%3A absolute%3B border%3A solid orange%3B }%0A<%2Fstyle>%0A%0Aa b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e 
http://software.hixie.ch/utilities/js/live-dom-viewer/?<!DOCTYPE html>%0A<style> %0A html { position%3A relative%3B border%3A solid gray%3B width%3A 10em%3B margin%3A 3em%3B height%3A 2em%3B display%3A flex%3B justify-content%3A flex-end%3B }%0A body { position%3A absolute%3B border%3A solid orange%3B }%0A<%2Fstyle>%0A%0Aa b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e 
http://software.hixie.ch/utilities/js/live-dom-viewer/?<!DOCTYPE html>%0A<style> %0A html { border%3A solid gray%3B width%3A 10em%3B margin%3A 3em%3B height%3A 2em%3B display%3A flex%3B justify-content%3A flex-end%3B }%0A body { position%3A absolute%3B border%3A solid orange%3B }%0A<%2Fstyle>%0A%0Aa b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e 
```
(Need to put these in the test suite...)

**Comment by tabatkins** [comment]
(The general form of the tests; toggle `justify-content` and `position` on `html` to see the different cases:
```
<!DOCTYPE html>
<style> 
 html { border: solid gray; width: 10em; margin: 3em; height: 2em; display: flex; justify-content: flex-end; position: relative;}
 body { position: absolute; border: solid orange; }
</style>

a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b c d e a b
```
)

These tests demonstrate complete non-interop in this case between Chrome and Firefox.  All of Chrome's behaviors seems to make no logical sense, and one of the situations (`justify-content: flex-end; position: relative`) doesn't seem to make any sense on Firefox either.

So ¯\_(ツ)_/¯

**Comment by tabatkins** [comment]
> I don't understand what "(as the fallback for stretch for fixed-size boxes)" means.

`flex-start` is the fallback value for `stretch` if you're fixed-size. We mandate that the element act as if it's fixed-size here.  In most cases `normal` acts like `stretch`, so we're specially calling out why we say it acts like a different value here. (It *does* act like `stretch`, but immediately falls back to another value, and we'd like to avoid requiring an unnecessary definition-chase to figure out what the behavior is here.)

**Comment by tabatkins** [comment]
If you add more text, and make it increasing numbers so you can actually tell exactly what part of the context you're looking at, Chrome's behavior becomes *even more inexplicable*:

```html
<!DOCTYPE html>
<style> 
 html { border: solid gray; width: 10em; margin: 3em; height: 2em; display: flex; justify-content: flex-end; }
 body { position: absolute; border: solid orange; }
</style>
<body>
<script>
document.body.textContent = Array.from(Array(400), (e,i)=>i).join(" ");
</script>
```

Swap `html` between flex-start (sensible), flex-end (wut), and center (double wut).

**Comment by fantasai** [comment]
OK, so, the basic principle we've been operating off of in the Alignment spec is switching out the “check `direction`” condition in CSS2.1&sect;10 for “check the relevant alignment property”, and relying on the fact that the alignment properties key off of `direction`, providing the same behavior by default but allowing it to be controlled without misusing `direction`.

If we continue with that line of thinking for this issue, we would do the same thing: the behavior of `start` alignment is as defined in CSS2.1, and the behavior of `end` alignment is what it would be if the `direction` was reversed from what it is. Thus, since by default (i.e. for `start` alignment) we use the start edge of the static position containing block and the end edge of the containing block for the available width, then for the opposite alignment (`end`) we would use the end edge of the static position containing block and the start edge of the containing block for the available width.

The remaining question is what to do for `center`. The significant edge is the one that matches the requested alignment: the start-edge reference for `start` alignment, the end-edge reference for `end` alignment. In each of these cases, this is the static position containing block. Thus `center`, which keys off of both start and end edges, should use the static position containing block edges for both. This also has the benefit of providing a behavior that cannot otherwise be gotten—since referencing the start/end edges of the actual containing block is always possible using `left: 0; right: 0`.

So, the proposal is:
- If `justify-content` on the static position containing block is `start`, use the start edge of the 
static position containing block and the end edge of the actual containing block (as CSS2.1 requires).
- If `justify-content` on the static position containing block is `end`, use the start edge of the actual containing block and the end edge of the static position containing block.
- If `justify-content` on the static position containing block is `center`, use the start edge and end edges of the static position containing block.

where the first two are exactly what CSS2.1 requires, except with a conditional on the `justify-content` of the static position containing block substituted for the conditional on `direction` of the static position containing block, and the third is the consequence of extending that logic to centering as best we can.

**Comment by tabatkins** [comment]
Here's a code example showing off the desired how sizing keys off of direction per CSS 2.1, which we'd like to be consistent with for Align. (That is, if you leave `dir` alone and just toggle `justify-content` between `start` and `end`, you should get the same result. Today you... don't.)

[(testcase link)](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5935)
```html
<!DOCTYPE html>
<html style="border: solid gray; width: 10em; margin: 3em; height: 2em; display: flex; justify-content: flex-start;">
<body style="position: absolute; border: solid orange; user-select: none;">
<script>
document.body.innerHTML = "<bdi>(click me to toggle) " + Array.from(Array(200), (e,i)=>i).join(" ") + "</bdi>";
var dir = "left";
var html = document.querySelector("html");
document.body.onclick = function() {
  dir = dir == "left" ? "right" : "left";
  if(dir == "left") {
    html.style.marginRight = "3em";
    html.setAttribute("dir", "ltr");
  } else if(dir == "right") {
    html.style.marginRight = "auto";
    html.setAttribute("dir", "rtl");
  }
}
</script>
```

**Comment by tabatkins** [comment]
Testcase showing the staticpos anchor in an inline context:

```html
<!DOCTYPE html>
<span>text <img src="https://www.xanthir.com/pony"> <span class=abspos>abspos</span> text</span>
<style>
img {
 vertical-align: middle;
}
.abspos {
 position: absolute;
 border: thin solid;
}
</style>
```

**Comment by fantasai** [comment]
OK, so, I *think* we're done with this issue (thanks dbaron, for filing :) 

However, we did make a mistake earlier: when we said we should be keying off of the `justify-content` property of the abspos’s static-position CB, we should actually be keying off of the `justify-self` property of the abspos itself. This is consistent with the principle of how we're replacing “do X or Y based on CB’s `direction`” with “do X or Y based on box’s own self-alignment” across the spec in general. Commits for that changeover in https://github.com/w3c/csswg-drafts/commit/a595144d70e89c858b2589b1e1eb0564bbca936b
Agenda+ to adjust the resolution proposed in https://github.com/w3c/csswg-drafts/issues/1432#issuecomment-387153116 accordingly.

**Comment by fantasai** [comment]
No response in nearly three months, and also no response to multiple queries of "did you want to review this issue" via IRC and email, so closing out as timed out.

**Comment by tabatkins** [comment]
Reopening, as @bfgeek is messing with this code in LayoutNG and thinks we resolved wrong for center alignment.

In particular, he believes that the correct answer is to find the smaller of the start- and end-aligned sizes, then double that. This lets it fill out the abspos containing block as much as it can while still remaining centered on one of the "significant edges" of the staticpos containing block.

This is apparently what Edge does.

**Comment by bfgeek** [comment]
FYI - I added two tests with this behaviour here: https://wpt.fyi/results/css/css-position?label=master&label=experimental&aligned&q=position-absolute-center which EdgeHTML did pass (doesn't as written as used inline-size, block-size properties).

**Comment by tabatkins** [comment]
Closing in favor of moving the center-align niggle to a new issue.

**Comment by dholbert** [comment]
RE the justify-content / align-content changes (in https://github.com/w3c/csswg-drafts/issues/1432#issuecomment-415854208 and the subsequent resolution) -- @fantasai  or @tabatkins , could you check my understanding of where this ended up?

If I'm understanding correctly, I think:
 (1) abspos children of a relpos flex container **should not** have their static position influenced by the flex container's `justify-content` property.
 (2) abspos children of a relpos flex container **should** respect their own `justify-self` property when determining their static position.

The earlier spec text here had said something like "determine the abspos child's static position as if the child were the flex container's sole flex item", which gave the opposite expectations for (1)/(2) above (and that's what I'd implemented a few years back, though I think I need to update that now).

**Comment by dholbert** [comment]
Also, am I correct that...
(3) for an abspos child in a relpos flex container, 'align-self:center' will center in the flex container's block axis, even if the flex container has `flex-direction:column` and has its `align`/`justify` axes swapped for its regular in-flow children?

That seems to be what https://drafts.csswg.org/css-align-3/#align-abspos says, at least (though it's a change from how this used to work).

**Comment by fantasai** [comment]
@dholbert

Wrt (1), yes that is correct.
Wrt (2), not quite correct. `justify-self` and `align-self` don't change the static position itself, they change how the abspos is aligned within its inset-modified containing block. See https://drafts.csswg.org/css-position-3/#abspos-insets
Wrt (3), yes I believe you are correct. The goal was to give abspos a more consistent and straightforward model, in which the inset-modified containing block is calculated possibly affected by the peculiarities of its static position containing block’s layout model; and then the abspos is laid out inside this rectangle the same way in all cases. That the align-self axis of a flex child can change depending on whether it is a flex item or an abspos does seem to fall out of that. :)

If you think there might be some problem with making such changes, let us know!

**Comment by fantasai** [comment]
@dholbert Filed https://github.com/w3c/csswg-drafts/issues/5843 as follow-up, as I think some of the points you brought up warrant further discussion.
