### ISSUE TITLE
[css-align] 'normal' behavior for justify/align-self on grid describes sizing rather than alignment

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1433]
The [definition of `justify-self: normal` for grid](https://drafts.csswg.org/css-align/#justify-grid) and the [same for `align-self`](https://drafts.csswg.org/css-align/#align-grid) say:

> For replaced items, see Grid Item Sizing in [CSS-GRID-1]. 

I don't understand what this means, since it seems to be saying that to understand how to *align* this item, go see this other section that says how to *size* the item.  It still doesn't seem to say how to align it.

**Comment by fantasai** [comment]
Yeah, it looks like we forgot to mention that. Also needed to resync it with changes to Grid. Should be fixed now, thanks!
