### ISSUE TITLE
[css-flexbox-1] Intrinsic sizing algorithm seems to produce 0 for many common cases

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#1435]
I'm reviewing @cbiesinger 's testcase for the (not-implemented-anywhere AFAIK) [flexbox intrinsic sizing algorithm](https://drafts.csswg.org/css-flexbox/#intrinsic-sizes), over in https://github.com/w3c/web-platform-tests/pull/5791 , and I think we might've uncovered some unintended spec behavior with the intrinsic sizing algorithm.  (And maybe it's intended? But it doesn't match biesi's testcase's expectations, so I want to be sure.)

In particular: it seems to me that in many common cases (with empty flex items at least), the algorithm requires that flex items contribute 0 to their container's intrinsic size, and the container will end up with an intrinsic size of 0 as a result.

For example, consider these two cases:
```
  <div style="display:inline-flex;">
    <div style="flex: 1 1 200px"></div>
  </div>

  <div style="display:inline-flex">
    <div style="flex: 1 1 auto; width: 200px"></div>
  </div>
```

Here, you might reasonably expect that each flex item & flex container to be 200px wide. But in both cases, the algorithm ends up sizing the item & container to 0px.  This is because:
 * the items' contributions [depend on their max-content main size](https://drafts.csswg.org/css-flexbox/#intrinsic-item-contributions) which is zero in both cases since they don't have any contents (and an element's min/max-content size isn't influenced by its `flex-basis` or `width`).
 * The spec says the items' `flex-basis` doesn't get to clamp their contributions [because the items are both growable and shrinkable](https://drafts.csswg.org/css-flexbox/#intrinsic-item-contributions).

This behavior (ending up 0-sized) *kind of* makes sense, because the items have no content and no `min-width`/`max-width` properties, which mean's they're "OK" being 0-sized, in a sense -- there's no overflow.  Still: it seems odd for an element with `width:200px` to end up being 0-sized, in a scenario with no constraints.

@tabatkins @fantasai , am I reading the spec correctly here?  And is this zero-sizing the intended spec behavior for cases like this?

**Comment by tabatkins** [comment]
It wasn't explicitly intended, no. But I'm also not sure it's something we actually want to change. ^_^  @fantasai and I will have to think on this.

**Comment by fantasai** [comment]
I think the options we have are:
  * No change: flex basis is ignored for determining min-content/max-content sizes of flex containers, we only care about the min-content/max-content contributions of the item's contents.
  * Treat `width`/`height`, but not `flex-basis` as a floor on the max-content size.
  * Treat `flex-basis`, but not `width`/`height`, as a floor on the max-content size.
  * Take max(`flex-basis`, `width`/`height`) as a floor on the max-content size.

I'm not actually sure what's the best idea here.

@rachelandrew @jensimmons ?

**Comment by dbaron** [comment]
Should these be constraining the max-content contribution (to the parent) rather than the max-content size?  Otherwise I think it breaks the `max-content` (etc.) values.

**Comment by fantasai** [comment]
Yeah, it's the max-content contribution of the items / max-content size of the container we're concerned with here.

**Comment by fantasai** [comment]
Edits checked in! @dholbert, would please let me know if they are satisfactory. :)

**Comment by astearns** [comment]
Reopening for testcase need.

**Comment by zcorpan** [comment]
@tabatkins can you point to the testcase in web-platform-tests? If there isn't one, this should be open?
