### ISSUE TITLE
[css-display][css-pseudo] Interaction of run-in and ::first-line

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1441]
In [Run-In Layout](https://drafts.csswg.org/css-display-3/#run-in-layout), CSS Display says

> If a [run-in sequence](https://drafts.csswg.org/css-display-3/#run-in-sequence) is immediately followed by a block box that does not establish a new [block formatting context](https://drafts.csswg.org/css-display-3/#block-formatting-context), it is inserted as direct children of the block box after its [`::marker`](https://drafts.csswg.org/css-pseudo-4/#selectordef-marker) pseudo-element’s boxes (if any), but preceding any other boxes generated by the contents of the block (including the box generated by the [`::before`](https://drafts.csswg.org/css-pseudo-4/#selectordef-before) pseudo-element, if any).
> 
> The reparented content is then formatted as if originally parented there. Note that only layout is affected, not inheritance, because property inheritance for non-anonymous boxes is based only on the element tree.

First, does "boxes generated by the contents of the block" include block's `::first-line`? If yes, what about `::first-line`s generated by ancestor blocks?

Second, the premise in the last sentence is false. A non-anonymous box fragment can inherit some properties from a `::first-line` pseudo-element, which is based on the box tree. So it's not clear whether a run-in inserted into the next block is supposed to ignore that block's `::first-line` styles or not.

Example:

```html
<section>
  <span>Foo</span>
  <div>Bar</div>
</section>
```
```css
section { color: red }
div::first-line { color: green; background: blue }
```

What color does Foo have? Does it have a blue background behind?

**Comment by Loirooriol** [comment]
If an in-flow `::marker` is inside `::first-line` (being discussed in #1442), then I guess a run-in should also. What happens with inheritance?

**Comment by tabatkins** [comment]
My intuition is that runins should be affected by ::first-line styles, but this'll rely on how we actually, properly, define ::first-line, and so this issue is blocked on that.

**Comment by fantasai** [comment]
Fixed normatively in https://github.com/w3c/csswg-drafts/commit/37c01a4ef94aec7c352c3dc7c5cfc31f8898ed4d (consistent with the text in the subsequent note).

**Comment by Loirooriol** [comment]
Seems OK to me. Well, not sure if this will make `::first-line` even more hard to implement properly, but I'm not an implementator :)
