### ISSUE TITLE
[css-align] Axis rule for align-self/justify-self on static-position of abspos boxes not fully defined

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1443]
The [definition of `justify-self` for the static position of absolutely positioned boxes](https://drafts.csswg.org/css-align/#justify-abspos-static) says:

> justify-self Axis
> The same axis that justify-self corresponds to for in-flow children of the box’s parent 

And the [definition of `align-self` for the static position of absolutely positioned boxes](https://drafts.csswg.org/css-align/#align-abspos-static) says pretty much the same.

The problem with this definition is that this isn't defined for all box types.

I think this should instead be defined as the main/cross axis if the box's parent is a flexbox, and the block/inline axis if the box's parent is not.

(In fact, maybe the axis definitions should, in general, be defined that way?)

**Comment by fantasai** [comment]
Fixed as requested, thanks!
