### ISSUE TITLE
[css-align] should 'place-items' accept 'legacy' values?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1449]
The Value line for the [`place-items` shorthand](https://drafts.csswg.org/css-align/#propdef-place-items) says that it takes an `auto` value for the `justify-items` part of the shorthand.  However, `justify-items` doesn't take such a value; I believe this was intended to be the value that has been renamed to `legacy`.

(Is it intended that values like `legacy left` aren't supported in the shorthand?)

**Comment by fantasai** [comment]
Ok, I dropped the `auto` keyword from the value line. Whether we should allow the various `legacy` values/combos is an open question. I'd lean towards no, but don't have a strong opinion.

**Comment by tabatkins** [comment]
Since there's nothing left to do here, closing.
