### ISSUE TITLE
[css-align] rules on synthesizing baselines are split across two sections

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1450]
At the end of the [section on Baseline Alignment Terminology](https://drafts.csswg.org/css-align/#baseline-terms), there's a rule (a paragraph with two list items following) saying:

> For the purpose of synthesizing baselines of boxes whose block flow direction is parallel to the axis of the alignment context:
> 
> * If the box establishing the alignment context has a block flow direction that is orthogonal to the axis of the alignment context, use its writing mode.
> * Otherwise, assume either horizontal-tb or vertical-lr writing-mode, whichever is orthogonal to the box’s own writing-mode.

I think this should be in the previous section, on [Determining the Baselines of a Box](https://drafts.csswg.org/css-align/#baseline-export), since that's where the rules on synthesizing baselines are.

**Comment by fantasai** [comment]
Okay, I checked in a fix, but I had to actually change some of the prose in addition to moving it because the context wasn't there. I'd appreciate a review from you, @dbaron, and @tabatkins!

**Comment by dbaron** [comment]
Seems fine to me.  (Although I wonder if the "use" in the first bullet should be "assume" like the others.)
