### ISSUE TITLE
[css-display][css-lists] Is a markerly positioned box out-of-flow?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1458]
CSS Lists introduces [`position: marker`](https://drafts.csswg.org/css-lists/#position-marker), and it says

> An element with `position: marker` counts as absolutely positioned.

However, CSS Display says

> A box is out-of-flow if it is floated (via `float`) or absolutely-positioned (via `absolute` or `fixed` positioning).

It does not mention `marker` despite including `fixed`, which also counts as counts as absolutely positioned.

Is `marker` out-of-flow or not?

**Comment by tabatkins** [comment]
It's out-of-flow, yes. We're just being overly specific in Display and tying the concept to specific values rather than the general concept. We'll remove that and just say that it's "via `display`"
