### ISSUE TITLE
[cssom-view][css-position] Scrolling a sticky element into view should use normal flow position for sticky boxes

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#1459]
To [scroll an element into view](https://drafts.csswg.org/cssom-view/#scroll-an-element-into-view) the spec says that you should use the element's bounding border box returned from getBoundingClientRect. For sticky elements which are currently sticking trying to scroll to their current position could result in them moving further away or not being visible due to multiple similar sticky elements (e.g. click on the boxes or anchor links after scrolling down on http://jsbin.com/simivof/edit?html,output). This pattern of the previous sticky title being covering up the next one seems to be a common one.

I think the expected behavior when trying to scroll to a sticky element, at least by anchor, and probably also for scrollIntoView, would be to scroll to the element's normal flow position before applying the sticky offset. This will be a stable position and is most likely to result in the element actually being visible. It's actually hard to get this behavior otherwise as if you wrap a box around the sticky element for an anchor it will contain it and prevent the sticky element from moving.

**Comment by zcorpan** [comment]
@tabatkins opinions on how these should interact?

**Comment by tabatkins** [comment]
I agree that, at least at first glance, it seems like scrolling to the normal-flow position is the better behavior for users.  It's definitely the best behavior for clicking on an anchor link, and I don't see why `scrollIntoView()` should be different from it here.

@flackr Yeah, there's a distinction between "position affected by scrolling" (sticky) and "position doesn't care about scrolling" (fixed). The latter doesn't care where you've scrolled to, so it makes sense that "scrolling it into view" is a no-op.

**Comment by jonjohnjohnson** [comment]
@flackr just wanted to point out in your current jsbin example, it appears that blink now behaves in a way where it does scroll to the top of the 'normal-flow position', except when it seems the focus comes from within the sticky target??? Notice how scrolling halfway passed any sticky block and clicking on that block makes the scroll jump partially back up the page (I believe it's exactly 60px, related to your `top:-60px`), but not to the top of the 'normal-flow position'.

Also, not sure how desirable the 'normal-flow position' is for when the element sticks to the bottom and not the top? Whether sticky elements are all in the same container or in their own individual containers, if sticking to the bottom, scrollIntoView using the top of the screen feels wonky imo.

**Comment by davmillar** [comment]
I agree that scrolling to the normal-flow position seems like the least user-hostile option. I learned the hard way today that Safari on iOS 12.1.1 and Chrome 70.0.3538.67 will scroll the element into place in its current location. e.g. I can click a link to scroll down to a specific sticky header, but if the header is already stuck inside the view, no scrolling takes place.

**Comment by tabatkins** [comment]
All right, defined in <https://github.com/w3c/csswg-drafts/commit/5a8ed5b0c57ab1749ff69ab9c9ec4d5595e68950> that stickypos elements are considered to be at their initial position for the purpose of any scrolling operations - that should cover the CSSOM View methods, and things like clicking an anchor link.

**Comment by flackr** [comment]
Looks good to me, thanks!

**Comment by guiseek** [comment]
in my context, he would push the sticky toolbar off the screen, or enter next to a fab button with absolute.
using the nearest solved.

```ts
querySelector('.table-container').scrollIntoView({
  behavior: 'smooth', block: 'nearest'
});
```

**Comment by flackr** [comment]
Yes, it's going to be a breaking change if we want to improve the status quo - scrolling to the current position. Unfortunately scrolling to the normal flow position (which you can test in chrome with experimental web platform features enabled) is also broken in many common use cases. E.g. a sticky header with an input field that is already in view probably shouldn't scroll. However, if there are possibly other sticky elements overlapping the element of interest then you do want to use the in flow position (exemplified in the OP).
