### ISSUE TITLE
[css-text-decor] Link syntaxes with CSS Values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#146]
The combinators and multipliers within the syntaxes should link to the CSS Values module like other modules.

Sebastian

**Comment by fantasai** [comment]
These will all be fixed the next time these specs are generated with Bikeshed. Please don't open more such issues. (Also if you have a generator issue, just file one across multiple specs, don't file one per spec.)

**Comment by tabatkins** [comment]
That's not necessarily true; several of them are because some grammar definition is missing the `class=prod` that turns on CSS-grammar autolinking.

But yes, when you've got several specs with an identical issue, please just file one issue and add labels for all the specs.  If you wanna be a superhero, put a checkbox-list of the specs that need attention, so we can track and mark progress easily.

**Comment by SebastianZ** [comment]
> Also if you have a generator issue, just file one across multiple specs, don't file one per spec.

> But yes, when you've got several specs with an identical issue, please just file one issue and add labels for all the specs. If you wanna be a superhero, put a checkbox-list of the specs that need attention, so we can track and mark progress easily.

As the move to GitHub is still new, I didn't know how you'd like to have that issue filed, but fair enough, I'll keep that in mind next time. (I could also change one of the issues to hold a checkbox list and close the other ones, if you want to. Just let me know.)

Sebastian

**Comment by frivoal** [comment]
@tabatkins 
> That's not necessarily true; several of them are because some grammar definition is missing the class=prod that turns on CSS-grammar autolinking.

I fixed the CSS-UI spec not by adding class=prod, but by turning a `<table class=propdef>` into a `<pre class=propdef>`

**Comment by tabatkins** [comment]
Yeah, that's because Bikeshed adds a class=prod to the <td> when it generates the table for you. ^_^
