### ISSUE TITLE
[css-grid2] API for querying implicit grids

### ISSUE THREAD

**Issue by MarkUK** [w3c/csswg-drafts#1465]
When using an implicit grid with automatically placed items, there seems to be no way to query the item to identify where it finally ended up, in row and column terms. Similarly it would be useful to be able to query the number of rows and columns in the grid, or get the bounding rect for a particular "cell".

Using `getComputedStyle()`, for example, _does_ return useful values for `grid-template-columns`, but  simply returns "auto" for `grid-column-start` and `grid-row-start` on an item in the grid.

A complementary API to get the element(s) at a particular row/column position would also be useful.

**Use case:** I have a UI layout that automatically places widgets in a grid to maximise the use of the available space. As a convenience I would like my users to be able to move vertically from field to field using the up/down cursor keys. To do this I need to find out the grid position of the current field, and then identify which field is in the cell directly above/below it.

There are, I'm sure, indirect ways to deal with this using `getBoundingClientRect()` or similar, but they are convoluted and fragile compared to being able to ask the grid to report information about itself.

**Comment by fantasai** [comment]
It makes sense to me to have an API for this. I guess the way forward is for people to throw down proposals until one of them “sticks” (feels correct and intuitive enough to use as the basis of the new spec). :)

(Not sure if we'll be able to refine it in time for L2, whose goal is rapid stabilization of subgrid; but leaving it on the L2 tracker just in case.)

**Comment by tabatkins** [comment]
Thanks for the suggestions! I ended up filing #2681 to track the first item (finding the actual location in the grid of a given item).

The other two suggestions seem simple to do on your own if #2681 is accepted; you just need to iterate the grid items and build up a map of their locations yourself.  This won't handle anonymous grid items (created by raw text children of the grid container), but they're honestly an error case; we tried very hard to make anonymous grid/flex items fairly annoying to use, without actually hiding any data. ^_^

**Comment by MarkUK** [comment]
Thanks for opening issue #2681. With regard to the other items, I still think there's a requirement for the second one in particular. Note that the point of it was primarily to be able to find out the pixel positions of each row and column, which I don't think can be done simply by creating a map of the positioned items.

Consider that the row/column positions can be defined with complex CSS, including custom values, fr units, negative indexes, calc() and minmax(), and that the grid can be defined even without any content. The browser knows the calculated position of each row and column, but there's no way for script to query this.

The most obvious use cases can indeed be "solved" by ensuring the grid is fully populated by including empty divs, then using the gCS() (per issue #2681) to build up a map of the grid. But for more complex grids, with overlapping items and blank spaces - or simply if the developer doesn't want to add a load of empty divs - being able to find out the final position of each row and column line would make things a lot simpler.

**Comment by tabatkins** [comment]
The sizes of explicit rows/columns will already be present in `grid-template-rows` and `grid-template-columns` from gCS(), since that also returns the used values, post-layout.  It would just be implicit tracks that you'd have to figure out the bounds of.

And for implicit tracks, is there a use-case for knowing the sizes of tracks that don't have a corresponding item aligned to them? If you don't have an item edge touching a given line, that line basically doesn't exist, anyway.

**Comment by MarkUK** [comment]
You're right about grid-template-rows _et _al_ from gCS(). I'm not sure I was seeing those values in the browser when I first opened this request last year, but can't be certain.

As for implicit tracks, I was thinking along the lines of hit detection for placing items into a sparse grid. E.g. in my case of a UI layout, allowing users to move fields into empty spaces. But any such use case I can think of can be addressed by adding some extra empty divs and doing the hit detection on them (pending issue #2681 ).

Given that the use cases are not likely to be common, and there is a workaround of sorts, I'm closing this. Thanks for your feedback.

**Comment by tabatkins** [comment]
Ah, if your grid is fixed enough to let people drag things into empty spaces, then you don't need a special API at all. ^_^

But anyway, 👍
