### ISSUE TITLE
[css-fonts-4] Confusing informative note about matching font family names

### ISSUE THREAD

**Issue by dscorbett** [w3c/csswg-drafts#1466]
The informative note in [section 5.1 “Case sensitivity of font family names”](https://drafts.csswg.org/css-fonts-4/#font-family-casing) says that “a family name that contains an uppercase A (U+0041) followed by a combining ring (U+030A) will **not** match a name that looks identical but which uses the precomposed lowercase a-ring character (U+00E5) instead of the combining sequence.” However, an *uppercase* A followed by a combining ring does not look identical to a *lowercase* precomposed a-ring.

**Comment by svgeesus** [comment]
Good catch, this should be `uppercase a-ring character (U+00C5)`
