### ISSUE TITLE
[css-display] Interaction of run-in and block inside inline

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1472]
How is this supposed to behave?

```html
<span>
  A
  <b style="display: run-in">B</b>
  <div>C</div>
  D
</span>
```

I guess it's one of these options:

<table>
  <tbody>
    <tr>
      <th align="center">Option 1</th>
      <th align="center">Option 2</th>
    </tr>
    <tr>
      <td valign="top">
        <ol>

<li>The block breaks the inline

```html
<anonymous-block>
  <span>
    A
    <b style="display: run-in">B</b>
  </span>
</anonymous-block>
<div>C</div>
<anonymous-block>
  <span>D</span>
</anonymous-block>
```
</li>

<li>The run-in generates an anonymous block wrapper

```html
<anonymous-block>
  <span>
    A
    <anonymous-block>
      <b style="display: run-in">B</b>
    </anonymous-block>
  </span>
</anonymous-block>
<div>C</div>
<anonymous-block>
  <span>D</span>
</anonymous-block>
```
</li>

<li>The anonymous block generated by the run-in breaks the inline

```html
<anonymous-block>
  <anonymous-block>
    <span>A</span>
  </anonymous-block>
  <anonymous-block>
    <b style="display: run-in">B</b>
  </anonymous-block>
  <anonymous-block>
    <span></span>
  </anonymous-block>
</anonymous-block>
<div>C</div>
<anonymous-block>
  <span>D</span>
</anonymous-block>
```
</li>
        </ol>
      </td>
      <td valign="top">
        <ol>

<li>The run-in is inserted inside the block

```html
<span>
  A
  <div>
    <b style="display: run-in">B</b>
    C
  </div>
  D
</span>
```
</li>

<li>The block breaks the inline

```html
<anonymous-block>
  <span>A</span>
</anonymous-block>
<div>
  <b style="display: run-in">B</b>
  C
</div>
<anonymous-block>
  <span>D</span>
</anonymous-block>
```
</li>
        </ol>
      </td>
    </tr>
    <tr>

<td valign="top">Renders like

```
A
B
C
D
```

</td>
<td valign="top">Renders like

```
A
B C
D
```
</td>
</tr>
</tbody>
</table>

**Comment by SelenIT** [comment]
I believe that, first of all, A and D themselves are wrapped in anonymous block boxes, since the container has at least one block box inside, so they all are in the block formatting container. Given that `run-in` is inserted inside the next block box, I suppose that Option 2, variant 1 is the closest to the answer:

```
<span>
  <anonymous-block>A</anonymous-block>
  <div>
    <b style="display: run-in">B</b>
    C
  </div>
  <anonymous-block>D</anonymous-block>
</span>
```

I don't think it's "splitting the `span`", because in DOM terms both `div` and `run-in` box are still nested in the `span`. But I'm not sure if it's correct from the implementor's point of view.

**Comment by Loirooriol** [comment]
@SelenIT You are right I forgot to wrap the inline fragments inside anonymous block boxes, I have edited it.

When I said that the block splits the span I meant [this](https://www.w3.org/TR/CSS21/visuren.html#img-anon-block):

> When an inline box contains an in-flow block-level box, the inline box (and its inline ancestors within the same line box) are broken around the block-level box (and any block-level siblings that are consecutive or separated only by collapsible whitespace and/or out-of-flow elements), splitting the inline box into two boxes (even if either side is empty), one on each side of the block-level box(es).

This does not affect the DOM, of course. I only tried to represent the various box fragments. It's not clear how this affects the box tree, though, so I filed #1477.

**Comment by SelenIT** [comment]
@Loirooriol I agree with your correction. Yes, the `span` box should be fragmented this way. Now I think that Option 2, variant 2 is exactly what should happen here.

**Comment by fantasai** [comment]
@tabatkins and I agree that this is the most sensible option. Should be fixed in https://github.com/w3c/csswg-drafts/commit/6f6913e20851f50ad81ca3cb43a499c01e8b2186.
Let us know if it needs further clarification.

**Comment by Loirooriol** [comment]
It's OK, thanks. But maybe I would restrict to [CSS2§9.2.1.1](https://www.w3.org/TR/CSS21/visuren.html#anonymous-block-level), because [CSS2§9.2](https://www.w3.org/TR/CSS21/visuren.html#box-gen) is so big.

**Comment by fantasai** [comment]
We wanted to include the full scope of flow layout anonymous box fixup there, so linked up to 9.2.

(The section in between those headings is relatively short and is a good introduction for understanding 9.2.1.1, so it's not a bad place to land anyway.)
