### ISSUE TITLE
[css-break] Ruby containers are not monolithic

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1474]
[CSS break](https://drafts.csswg.org/css-break-3/#ref-for-monolithic-1) says

> inline-block and inline-table boxes (and other inline-level display types that establish a new formatting context) may also be considered monolithic.

Ruby containers are inline-level and establish a new ruby formatting context. But I think they are not monolithic, because [a ruby can break across lines](https://drafts.csswg.org/css-ruby-1/#line-breaks).

Instead, I would say something like

> [atomic inlines](https://drafts.csswg.org/css-display-3/#atomic-inline) (like inline-block and inline-table boxes) may also be considered monolithic.

Related: #1180

**Comment by fantasai** [comment]
Fixed by replacing “new formatting context” with “independent formatting context”.
