### ISSUE TITLE
[cssom-view] Having getClientRects() return a sequence is not Web-compatible

### ISSUE THREAD

**Issue by cdumez** [w3c/csswg-drafts#1479]
Having getClientRects() return a sequence is not Web-compatible:
- https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface
- https://drafts.csswg.org/cssom-view/#extensions-to-the-range-interface

WebKit used to return a ClientRectList type that had an item() operation. We recently updated WebKit to match the specification and return an JS array of DOMRect objects.

However, this broke Google Spreadsheet as explained here:
- https://bugs.webkit.org/show_bug.cgi?id=172703

The relevant Google spreadsheet code seems to be:
function Epb(a) {
    Dpb(a);
    a = xpb(a).Pq().getClientRects();
    return {
        first: a.item(0),
        nV: a.item(a.length - 1)
    }
}

in https://docs.google.com/static/spreadsheets2/client/js/2594367115-ritz_waffle_i18n_core.js

Based on this, we will have to re-introduce a List type with an item() operation in WebKit and I would suggest for the specification to be updated (Maybe DOMRectList?) as well.

**Comment by cdumez** [comment]
cc @rniwa @smfr @zcorpan

**Comment by zcorpan** [comment]
Earlier bugzilla bug for this issue: https://www.w3.org/Bugs/Public/show_bug.cgi?id=26200

cc @bzbarsky @foolip @annevk @domenic

**Comment by bzbarsky** [comment]
Right, the options here are either a DOMRectList or some sort of array subclass thing with item().

**Comment by cdumez** [comment]
In WebKit, we'll introduce a DOMRectList interface but mark it as [NoInterfaceObject] for now.

**Comment by zcorpan** [comment]
Spec reverts at
https://github.com/w3c/fxtf-drafts/pull/186
https://github.com/w3c/csswg-drafts/pull/1499

**Comment by foolip** [comment]
This is now fixed in specs and tests:
https://github.com/w3c/csswg-drafts/pull/1499
https://github.com/w3c/fxtf-drafts/pull/186
https://github.com/w3c/web-platform-tests/pull/6299
