### ISSUE TITLE
[css-backgrounds] Description related to value order of 'border-image-repeat' is incorrect

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#148]
The spec. [currently says](https://drafts.csswg.org/css-backgrounds-3/#the-border-image-repeat):

> The first keyword applies to the horizontal sides, the second to the vertical ones; see Drawing the Border Image.

That seems to be incorrect, because the first keyword sets the behavior for the top, middle and bottom parts of the image, i.e. **all three vertical parts** of the border image area, not the horizontal sides.

Sebastian

**Comment by SelenIT** [comment]
This phrase looks quite ambiguous. On the one hand, the thickness of the top and bottom sides of the border is clearly measured along _vertical_ axis. On the other hand, these parts are usually drawn like kind of _horizontal_ bars, so some people might tend to think of them as of something with horizontal orientation.

 Maybe it would be better to use terms like "top and bottom sides" directly, without trying to find one generalized term for both?

**Comment by SebastianZ** [comment]
> This phrase looks quite ambiguous.

Right. And even when the sentence is interpreted like _horizontal_ bars, `border-image-repeat` also affects the **middle** area when `border-image-source` has the `fill` keyword set.

So, to be totally unambiguous I suggest to replace it by something like this:

"The first keyword applies to the horizontal scaling and tiling of the top, middle and bottom parts, the second to the vertical scaling and tiling of the left, middle and right parts."

Sebastian

**Comment by fantasai** [comment]
Fixed, thanks for the wording!
