### ISSUE TITLE
[css-text-3] letter-spacing computed values don't reflect reality

### ISSUE THREAD

**Issue by nox** [w3c/csswg-drafts#1484]
The [spec](https://drafts.csswg.org/css-text-3/#letter-spacing-property) says that the computed value should be an absolute length, but at least Safari and Firefox preserve the keyword `normal` in computed values.

**Comment by fantasai** [comment]
CSS2 used to treat `normal` different than `0`, so computing differently was a requirement. Now that the spec treats them the same, it's possible to compute through. I'll ask the WG if they want to change the implementations or the spec in this case.

**Comment by FremyCompany** [comment]
Edge also computes to `normal`
