### ISSUE TITLE
[css-backgrounds] Algorithm for drawing the border image doesn't consider 'fill' keyword

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#149]
The algorithm described under [Drawing the Border Image](https://www.w3.org/TR/css3-background/#border-image-process) currently makes no difference whether the `fill` keyword of the of the `border-image-slice` property is set or not. In step 2 it is always talking about "top, middle and bottom" images.

It should be mentioned in the algorithm that in the case the `fill` keyword is not set, it only applies to the top and bottom images.

Sebastian

**Comment by fantasai** [comment]
Not sure it's really needed, but added a bullet to the Tile and Draw section about this anyway.
