### ISSUE TITLE
[css-display] Discrepancies among various run-in definitions

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1491]
The [table of `display` values](https://drafts.csswg.org/css-display-3/#display-value-summary) defines `run-in` as

> [inline box](https://drafts.csswg.org/css-display-3/#inline-box) with special box-tree-munging rules

[Outer Display Roles for Flow Layout](https://drafts.csswg.org/css-display-3/#outer-role) defines it as

> Run-in elements act like inlines or blocks, depending on the surrounding elements.

And [Run-In Layout](https://drafts.csswg.org/css-display-3/#run-in-layout) says

> A run-in box behaves exactly as an inline-level box, except [...]

The first definition seems to imply that run-ins are inline boxes, but with some additional special behavior. The third definition seems to imply that run-ins are not inline boxes, but they behave similarly.

Which is it? For example, if some property says it applies to inline boxes, does it apply to run-ins too?

I think the second definition is just an obsolete copy-paste from CSS2. The run-in never acts as a block (but can generate an anonymous block parent).

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/76a59ebbaccf2613ce6af5f1ea4ccfe67e59cb56
(The first case *is* an inline box, since it is not `run-in flow-root`.)
