### ISSUE TITLE
[css-display] How are 'list-item run-in flow' and 'list-item block flow-root' serialized?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1493]
Some `display` values with `list-item` keyword can be shortened to a single keyword:

 - `list-item block flow` can be shortened to `list-item`
 - `list-item inline flow` can be shortened to `inline-list-item`

Some `display` values with `list-item` keyword require all three keywords:

 - `list-item run-in flow-root`
 - `list-item inline flow-root`

The other `display` values with `list-item` keyword can be shortened to two keywords:

 - `list-item run-in flow` can be shortened to `list-item run-in`
 - `list-item block flow-root` can be shortened to `list-item flow-root`

This question is about the last case. Do they serialize to the two-keyword shortened form, or do they stay in the full form?

[CSS Display](https://drafts.csswg.org/css-display-3/#display-value-summary) says

> Following the precedence rules of “most backwards-compatible, then shortest”, serialization of equivalent display values uses the “Short display” column.

So it seems short forms are preferred, but these combinations do not appear in the summary table!

**Comment by tabatkins** [comment]
The table is an informative guide to help authors, not a normative and complete mapping table.  The note at the end is just that—a note, reminding you that things get serialized to their shortest form, and that the table contains many of those.  But the "3 keywords that can be written as 2" is already covered by that general principle.

(However, see #1564.)

**Comment by fantasai** [comment]
(Marking Wontfix because we won't fix the informative table; but the serialization should be clearly defined in CSSOM, and #1564 is open against it to ensure it contains the general rules for serialization once again.)
