### ISSUE TITLE
[css-syntax] 4.3.5 Consume a string token: double parse error

### ISSUE THREAD

**Issue by waldbaerkoch** [w3c/csswg-drafts#1494]
Input:
```
"foo\<EOF>
```
`"` triggers 4.3.5 Consume a string token. There, after having consumed `foo`:
Next code point is
* U+005C REVERSE SOLIDUS (\\)
  * If the next input code point is EOF _(yes)_, this is a parse error _(1st time)_; do nothing. 

Next code point is 
* EOF
  * This is a parse error _(2nd time)_. Return the <string-token>.

So parse error is invoked twice. The occurence in U+005C REVERSE SOLIDUS (\\) is not necessary.

Johannes

**Comment by tabatkins** [comment]
You're right; removed.
