### ISSUE TITLE
[css-display] Missing definition of 'inline-list-item'

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1495]
The [Precomposed Inline-level Display Values](https://drafts.csswg.org/css-display-3/#legacy-display) section defines the following [`<display-legacy>`](https://drafts.csswg.org/css-display-3/#typedef-display-legacy) keywords:

> - `inline-block`: Behaves as `inline flow-root`. 
> - `inline-table`: Behaves as `inline table`. 
> - `inline-flex`: Behaves as `inline flex`. 
> - `inline-grid`: Behaves as `inline grid`. 

However, `<display-legacy>` allows a 5th possibility: `inline-list-item`.

According to the [summary table](https://drafts.csswg.org/css-display-3/#display-value-summary), it should be

> - `inline-list-item`: Behaves as `list-item inline flow`. 

Or, to maintain a similarity among all these definitions, the equivalent

> - `inline-list-item`: Behaves as `inline list-item`.

**Comment by Loirooriol** [comment]
Or maybe `inline-list-item` should be dropped. All the other precomposed inline-level values are `inline-` followed by an inner display type, and exist for legacy reasons. But `list-item` is not an inner display type, and is a new addition.

**Comment by tabatkins** [comment]
I don't *think* anyone has implemented `inline-list-item` yet - it's just specified over in Lists, as a useful feature.  If so, we should just drop it, and let people write `inline list-item` if they want.

**Comment by astearns** [comment]
we confused the bot - the actual minutes on this issue are

<dael> fantasai: Suggestion was it's a little different then some of the others and do we really need this one. It might be worth dropping that unless someone has impl and wants to keep it.
<dael> astearns: Anyone know if inline-list-item has been imp?
<dael> Rossen_: I don't believe we are.
<dael> astearns: Obj to dropping inline-list-item?
<fantasai> No hits in Mozilla's codebase
<dael> RESOLVED: Drop inline-list-item

**Comment by FremyCompany** [comment]
We need to be kinder with the bot, or it might try to drown itself ;-)

![image](https://user-images.githubusercontent.com/364405/28382688-e6cd3584-6c73-11e7-8f2c-843a9e7a77c7.png)
