### ISSUE TITLE
[css-backgrounds] Properly define 'border image area'

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#150]
A definition of the border image area is [available under the `border-image-width` property](https://drafts.csswg.org/css-backgrounds-3/#border-image-width), though all references to it link to a [sentence under the `border-image-outset` property](https://drafts.csswg.org/css-backgrounds-3/#border-image-area).

It would be better if the border image area was described in its own section and only referenced the properties affecting it.

Sebastian

**Comment by fantasai** [comment]
I've fixed the cross-links, but I don't think this term needs its own section.
