### ISSUE TITLE
[mediaqueries-5] Handling of redefinitions of custom media queries

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1502]
Spec: https://drafts.csswg.org/mediaqueries-5/#custom-mq

The spec doesn't seem to address how multiple definitions of a given custom media query should be handled.

 Example:
```css
@custom-media --my-mq (min-width: 1em);
@custom-media --my-mq (min-width: 1000em);

@media (--my-mq) {
  /* do styles in here apply at 1em, or at 1000em ? */
}
```

**Comment by frivoal** [comment]
Latest one wins seems reasonable. Any better idea?

**Comment by cvrebert** [comment]
Sounds good to me.
