### ISSUE TITLE
[css-position] Should 'table-column{-group}' reference be removed from position: relative spec?

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/csswg-drafts#1507]
In the CSS3 position spec, the 'position' attribute (https://www.w3.org/TR/css-position-3/#position-property or https://drafts.csswg.org/css-position/#position-property) notes that it applies to:

"all elements except table-column-group and table-column"

However later in the spec it specifies what to do for position: relative (and position: sticky, by inference) for table-column-group and table-column:

"table-column-group, table-column do not offset the respective column and has no visual affect when position: relative is applied." (https://www.w3.org/TR/css-position-3/#valdef-position-relative)

Is such a specification required, if the core 'position' attribute is not valid on elements with those display types?

**Comment by tabatkins** [comment]
Done as part of the larger rewrite.
