### ISSUE TITLE
[css-text] Letter spacing is inserted after RTL reordering

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1509]
The last example of [Example 16] in [`letter-spacing`] property says:

> Letter spacing is inserted **after** RTL reordering

But `letter-spacing` affects line breaking, so we need to compute before line breaking.

Is this saying, compute once for line breaking in logical order, then re-compute after line breaking in visual order? Then the line width will not match and it may result in large-lagged lines, correct?

Test: http://output.jsbin.com/hudaxi

[`letter-spacing`]: https://drafts.csswg.org/css-text-3/#letter-spacing-property
[Example 16]: https://drafts.csswg.org/css-text-3/#example-c8bdfa99

**Comment by fantasai** [comment]
Technically, bidi reorder affects line breaking as well, since adjacent letters can have kerning and other effects that alter their width. :) This is not a different consideration.

**Comment by kojiishi** [comment]
We don't compute kerning/joining/etc. using adjacent characters after re-order for the same reason. The current engine can't do it across bidi runs, new engine does it in logical order. Doing them after re-order looks degration to me.

Thank you for the comment, your comment confirmed I'm not misunderstanding nor misreading (unless I'm still misunderstanding something...)

**Comment by kojiishi** [comment]
I heard Mozilla is going to implement this, is that correct? @dbaron @SebastianZ 

At first this was asking clarification but now we seem to have the same understanding, just different opinion which is more important.

Do other impls have opinions? @litherum @FremyCompany

**Comment by FremyCompany** [comment]
I haven't seen letter-spacing usages in the wild that require complex rules for it. 

That doesn't mean there are no such use cases; but I think due to widespread abuse letter-spacing is not a good candidate for being "fixed" at this point.

**Comment by fantasai** [comment]
Proposed that bidi resolution would result in splitting an inline in infinite space will always create two fragments, even if they end up adjacent due to line breaking.

**Comment by fantasai** [comment]
Behavior for letter-spacing (and other things affected, like box-decoration-break), falls out of this definition: in this case, if the two letters end up adjacent but are part of different fragments, the spacing between them will be given by the parent (according to the letter-spacing rules that control letter-spacing at element boundaries). This avoids the measuring problem.

**Comment by kojiishi** [comment]
@fantasai can you help to understand? I understand the proposal solves `border-decoration-break: clone`, but I can't see how it solves `letter-spacing`. By looking at [Example 16], so the proposal is to create (assume `<f>` is the internal fragment):

```html
<p><f>ab</f><span><f>c</f><f>א</f></span><f>בג</f></p>
```
or
```html
<f><p>ab<span>c</f><f>א</span>בג</f></p>
```
I don't know which you intend, nor have not examined if the two differ in results, but either way, common ancestor of `c` and `ג` is `<p>`, so there will be no 2em spacing in the result, if I'm not mistaken.

Or is your proposal includes to change to check logical adjacent character instead of visual adjacent character? Then between `c` and `א` has 2em space, but I can't read from the current spec where that space should go after re-order. Should it belong to `c` or `א`?

Could you point out what I missed?

For your question in F2F, if we were to say "apply to line-right of characters", we could say, for the last character, apply the spacing of common ancestor. I'm ok to use the current way to define it if you can make it to work, but if you prefer the line-right solution, I hope this can work.

[Example 16]: https://drafts.csswg.org/css-text-3/#example-c8bdfa99

**Comment by fantasai** [comment]
Talked with Koji; Agenda+ to resolve on proposal in https://github.com/w3c/csswg-drafts/issues/1509#issuecomment-320209074

**Comment by FremyCompany** [comment]
I see the Agenda+ but I don't see an example explaining this new proposed algorithm. I'd like an image explaining this if possible, or at least a more detailed proposal, because I'm not confident on resolving on something I don't understand.

**Comment by fantasai** [comment]
@FremyCompany It means that in Koji's example above, if we ignore the `<f>` bits: 
```
<p>ab<span>cא</span>בג</p>
```
Because the span will split into two fragments due to bidi reordering on an infinite line, then even if the last two letters don't fit and the two pieces happen to end up together, they are considered to be of two different fragments, and the space between the two letters will be considered to come from the P (the letters’ nearest common ancestor).

**Comment by fantasai** [comment]
Fixed by adding a new subsection to the section on the effects of bidi on the inline box model in CSS Writing Modes (sorry). https://drafts.csswg.org/css-writing-modes-3/#bidi-box-model
