### ISSUE TITLE
[cssom-view] Wrong length variable in "scroll an element into view" algorithm?

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#1515]
Spec: https://drafts.csswg.org/cssom-view/#scroll-an-element-into-view

Steps 9.4 and 9.8 both reference *element* ***width*** despite being for perpendicular axes, which seems strange.
Trying to manually run thru the algorithm, assuming a Latin writing mode, it seems like step 9.4 ought to use an *element* ***height*** variable instead of *element width* ?

**Comment by zcorpan** [comment]
Ummm. Yes, that would make more sense.
