### ISSUE TITLE
 [css-logical-props] Naming of inset-* properties prefix

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#1519]
In issue https://github.com/w3c/fxtf-drafts/issues/51 it was [decided to rename the logical properties](https://github.com/w3c/fxtf-drafts/issues/51#issuecomment-296089562) to avoid the conflict with the motion path properties.

@fantasai chose `inset` as prefix for now.

There's also a [related thread on Twitter](https://twitter.com/csswg/status/855306526973612032) asking for a shorthand for the physical properties `top`, `right`, `bottom`, and `left`.

Sebastian

**Comment by SebastianZ** [comment]
Question is whether the physical and the logical properties should share the same prefix and whether the shorthand should work for both.

For what it's worth, here are the results of the Twitter thread (ordered by times a keyword was suggested or liked and then alphabetically):

- `position-offset` +11
- `bounds` +8
- `box` +8
- `coords` +7
- `location` +7
- `box-offset` +6
- `coordinates` +6
- `distance` +4
- `position` (turned into shortcut and introduce `position-mode` as longhand for current use of property) +4
- `tlbr` +4
- `box-position` +3
- `dimensions` +3
- `move` +3
- `place` +3
- `placement` +3
- `transpose` +3
- `where` +3
- `arrange` (+ fifth argument for z-index) +2
- `box-placed` +2
- `positioned` +2
- `surface` +2
- `cross` +1
- `fix` +1
- `gap` +1
- `glue` +1
- `insets` +1
- `locale` +1
- `nudge` +1
- `origin` +1
- `pin` +1
- `point` +1
- `pos-offset` +1
- `positioning` +1
- `rect` +1
- `push` +1
- `relative-offset` +1
- `relative-position` +1
- `spot` +1
- `trbl` +1
- `whereabouts` +1
- `adjust`
- `allocation`
- `anchors`
- `arranged`
- `bind-top` / `bind-right` / `bind-bottom` / `bind-left`
- `bounding`
- `bound`
- `boundary`
- `box-coords`
- `box-distance`
- `box-edge`
- `cardinals`
- `cart`
- `cartesian`
- `corners`
- `cusp`
- `distribution`
- `edge`
- `edge-points`
- `extent`
- `extremes`
- `fasten-top` / `fasten-right` / `fasten-bottom` / `fasten-left`
- `frame`
- `loc`
- `offsets`
- `points`
- `pos`
- `position-bounds: top, right, bottom, left;` / `position-bounds: x, y;` / `position-bounds: all;`
- `position-box`
- `position-constraints`
- `position-direction`
- `position-margin`
- `position-rect`
- `position-scheme: absolute | relative;` with `position: top right bottom left;` where `position: absolute;` sets `position-scheme`
- `positioned-top` / `positioned-right` / `positioned-bottom` / `positioned-left`
- `perimeter`
- `quad`
- `reach`
- `sides`
- `spacing`
- `tp` / `lt` / `bm` / `rt`

My personal favorite is `position-offset`. And I'd also like `position` to be turned into a shorthand, which allow to set the physical or logical longhands, even though that would require special casing it to not reset the positioning properties and to provide a way to leave values unchanged.
That would allow the logical properties to be `position-inline-start`,  `position-inline-end`,  `position-block-start`,  `position-block-end` and to set them via the `position` shorthand.

Sebastian

**Comment by bradkemper** [comment]
I like `inset`. It is short, and accurately describes what happens to the named edges when given positive lengths. 

I'm also good with `inset-block-start`, etc.

**Comment by fantasai** [comment]
Agenda+ to finalize on a name (for now anyway), since we don't actually have a resolution for this. :) I agree with @bradkemper that `inset` is short, precise, and accurate about what's going on here so I'm leaning towards that. However, thanks for the full report. =)
