### ISSUE TITLE
[css-tables] Boxes don't have element ancestors

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1520]
CSS Tables says that [fixup boxes](https://drafts.csswg.org/css-tables-3/#fixup-boxes)

> get their value from the closest element ancestor of the box.

But boxes don't have element ancestors. I think this text, added in #1059, was not necessary because it's already covered by [CSS Display](https://drafts.csswg.org/css-display-3/#intro):

> Unlike element-generated boxes, whose styles inherit strictly through the element tree, anonymous boxes (which only exist in the box tree) inherit through their box tree parentage.

**Comment by FremyCompany** [comment]
Sounds good, will fix.
