### ISSUE TITLE
[css-counter-styles] Propose to make "disc" not overridable

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1521]
"disc" is the initial value of `list-style-type`, and making it overridable may add some unnecessary complexity to implementation. I hope we can make it not overridable like `decimal`.

So my proposal is:
> Additionally, in the context of the prelude of an @counter-style rule, an ASCII case-insensitive match for "decimal" **or "disc"** is also an invalid <counter-style-name> and makes the @counter-style rule invalid.

**Comment by tabatkins** [comment]
The only reason I made 'decimal' not overrideable is so I had some dependable fallback that didn't lose information.

I don't have a problem with making 'disc' non-overrideable as well, but it would be beyond the original justification for it.

**Comment by upsuper** [comment]
I totally understand the reason why 'decimal' needs to be non-overridable, and yeah, 'disc' doesn't need to be non-overridable theoretically. I just find it annoying when working on our new style system, and I don't think it is really something important worth the complexity to preserve.

**Comment by dbaron** [comment]
@upsuper is making this change in [Mozilla bug 1372488](https://bugzilla.mozilla.org/show_bug.cgi?id=1372488).

**Comment by tabatkins** [comment]
k, let's get it WG-approved.
