### ISSUE TITLE
[fonts-4] @font-palette-values uses illegal integer descriptor names

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1523]
As currently defined, `@font-palette-values` uses some integer descriptor names (to override the colors of particular indexes in the palette). However, [per Syntax](https://drafts.csswg.org/css-syntax/#consume-list-of-declarations), declaration names are restricted to idents only.

Do we want to change `@font-palette-values` to use idents, probably with a prefix before the integer, or do we want to modify Syntax to allow integer names for declarations?  (We shouldn't allow float names, as comparisons become fraught at that point.)

(For example, does `01: red;` work? Does it have the standard "last declaration with a given name wins" behavior if there's also a `1: blue` declaration in the block?)

**Comment by litherum** [comment]
I don't know of any reason to disallow integer names for declarations. Prefixing a number with 0 makes me think it's an octal number.

**Comment by tabatkins** [comment]
> I don't know of any reason to disallow integer names for declarations.

Because it's currently illegal, per Syntax, and will result in those declarations being thrown out as syntax errors. ^_^

> Prefixing a number with 0 makes me think it's an octal number.

That seems irrelevant? The question is what happens when people *do* it, not what you might interpret it as.  (CSS is extremely clear that `05` is just the integer 5.) 

If we want to allow integer declaration names, we have to answer some questions about how they're compared.

**Comment by litherum** [comment]
You misunderstand me.

When I say "I don't know of any reason to disallow integer names for declarations" I mean "I don't know of any reason why Syntax should consider integer names for declarations as illegal"

When I say "Prefixing a number with 0 makes me think it's an octal number" I mean "Requiring prefixing these numbers with 0 is problematic for authors because this number format is already overloaded in other contexts."

**Comment by tabatkins** [comment]
I didn't suggest "requiring prefixing these numbers with 0". That would indeed be crazy.

I'm saying that, *if* we change Syntax to allow integer declaration names, we need to answer the question of what this means:

```
@font-palette-values foo {
  1: blue;
  01: red;
}
```

Is the second one illegal? (It would be very difficult/weird to make it illegal.)  If they're both legal, do they represent the same descriptor, or different ones?  (For the same reason, difficult/weird to make them different descriptors.)  If they're the same descriptor, it seems possibly confusing to authors that two declarations with different names written down are actually the same; in all existing declarations, the names are compared codepoint-by-codepoint, possibly with ASCII case-folding.

I'm not necessarily opposed to this, but we do need to define it one way or another in Syntax.  Or we can define the names to be `index-1`/etc, making the names more descriptive and removing the need for any additional changes in Syntax and browser parsers.

**Comment by litherum** [comment]
Seems that they should both be legal, and they represent the same descriptor (so the "red" one would override the "blue" one). I don't think there will be much confusion about this situation because it's likely to be rare and because it is intuitive.

**Comment by tabatkins** [comment]
So now we come back to my final question: are integer names important enough to justify changing the Syntax spec, versus using a potentially more-descriptive set of names like `index-1`?

**Comment by svgeesus** [comment]
Numeric descriptors seem overly generic (but each says to which at-rule it applies, so I guess other at-rules could also have any numeric descriptors they need).

OTOH having to use some prefix just to get around the rules of the language is a pain. Remember the restriction that IDs could not start with a number, so people who cared about validity had to change id="6" to id="i6" or whatever? Despite the fact that the numeric IDs worked just fine in practice.  An annoyance which HTML5 fixed, of course.

This seems like the same sort of thing, to me.

**Comment by LeaVerou** [comment]
This seems like two separate issues to me:

1. Should we change Syntax to allow for integer descriptors?
2. Should the `@font-palette-values` descriptors be raw integers?

IMO, the answers are Yes and No respectively. Integer descriptors could prove useful in the future, so they should be allowed. However, in the large scheme of things, `@font-palette-values` is a relatively minor feature and we shouldn’t waste such a useful syntactic construct on it. I don’t see why we can’t prefix these properties with something like `color-`. It makes the rule easier to read and the verbosity doesn’t really get in the way, since this is not something authors will type again and again.

**Comment by svgeesus** [comment]
I see that the OpenType spec call these [color records](https://www.microsoft.com/typography/otspec/cpal.htm) so color-nnn is reasonable. How big should the nnn part be, though? [numPaletteEntries](https://www.microsoft.com/typography/otspec/cpal.htm) is uint16 :) so if we aren't going to allow integers then do we need to declare 64k descriptor names? Or can they be defined as &lt;name> "-" &lt;number> ?

**Comment by svgeesus** [comment]
So we resolved to have a bunch of descriptors running from `color-0` to `color-65535` with no leading zeroes. It looks as if the syntax module allows &lt;number> to have a leading + or - though?
https://drafts.csswg.org/css-syntax/#consume-number

**Comment by tabatkins** [comment]
`<number>` is irrelevant here; `color-*` is an ident. The rule would just be that the name is `color-` followed by one or more digits, and the digits must have no leading zeros (unless it's the value `color-0`).

**Comment by litherum** [comment]
Why are we zero-indexing? src() fragment identifiers (representing items inside a TrueType Collection or a WOFF2 Archive) are one-indexed.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/311174c743409cf29519dda2e1aa633060345034

**Comment by astearns** [comment]
> Why are we zero-indexing?

Should this be a separate issue?

**Comment by svgeesus** [comment]
> src() fragment identifiers (representing items inside a TrueType Collection or a WOFF2 Archive) are one-indexed.

No, they aren't ^-^
See RFC 8081, section 4.2.  **Fragment Identifiers for Font Collections**
https://tools.ietf.org/html/rfc8081#section-4.2

**Comment by svgeesus** [comment]
However, more relevantly, the OpenType spec is very clear:

> Colors within a palette are referenced by base-zero index
> https://docs.microsoft.com/en-us/typography/opentype/spec/cpal

**Comment by svgeesus** [comment]
Huh, while I am actually reading the spec; I said

> So we resolved to have a bunch of descriptors running from color-0 to color-65535 with no leading zeroes.

which is wrong because

> This special value does not change across multiple palettes. The maximum palette entry index is 65535 – 1, as the 65536th position is used in the COLR table to indicate the foreground font color.
> https://docs.microsoft.com/en-us/typography/opentype/spec/cpal

**Comment by litherum** [comment]
> > Why are we zero-indexing?
> 
> Should this be a separate issue?

No, I don't have an opinion on this issue. If someone else wants to champion it, they can open it.

**Comment by litherum** [comment]
The fonts spec [used to say](https://www.w3.org/TR/2013/CR-css-fonts-3-20131003/):

> If a container format lacks a defined fragment identifier scheme, implementations should use a simple 1-based indexing scheme

Then you modified it for https://github.com/w3c/csswg-drafts/issues/2205 to use PostScript name

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/631e449370d3853483beca3a2e40d0de4245ed56

**Comment by svgeesus** [comment]
> Then you modified it for #2205 to use PostScript name

Yes. Well, Ken Lunde of Adobe (who knows a thing or two about Collections) told us the numerical-based fragment scheme would break on already-released fonts, so we (the IETF JustFont WG) changed the Internet Draft that became RFC 8081.

But yes, I then updated Fonts 3 so it conformed to RFC 8081.

However, the more important point in this discussion is that OpenType says the palette index is zero based and that modifiable values are in the range 0 to 0xFFFE.
