### ISSUE TITLE
[fonts-4] What's the syntax of the @font-palette-values name?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1524]
The old grammar for @font-palette-values was clearly just copy-pasted from @font-face, and so doesn't include the font-family name after the at-keyword, as shown in all the examples.

What's the syntax supposed to be for this?  Just a `<custom-ident>`? Or `<custom-ident> | <string>`, to allow easier matching with multi-word family names?

(Currently I have it down as just `<custom-ident>` in the new Syntax grammar.)

**Comment by litherum** [comment]
I think I'm misunderstanding you. The level 4 document currently has

> The @font-palette-values rule consists of the @font-palette-values at-keyword followed by a block of descriptor declarations. It has the following syntax:
> 
> ```css
> @font-palette-values <custom-ident> {
>   <declaration-list>
> }
> ```

So it looks like a `<custom-ident>` to me. Are you referring to something else?

**Comment by tabatkins** [comment]
Yes, I just rewrote Fonts 4 to use the Syntax productions instead of the old Appendix G productions.  Thus my parenthetical about what I "currently have it down as".

My question is about what was intended.  The old spec didn't have *anything* between the  `@font-palette-values` token and the `{`, because it was a copy-paste from the `@font-face` definition, which puts its name in a descriptor.  But all the example show it with an ident there.

So do we want just a `<custom-ident>`? Or a `<family-name>`? Or a `<custom-ident> | <string>`?

(I'd recommend against `<family-name>`; it was a terrible legacy mistake that makes parsing really annoying.)

**Comment by litherum** [comment]
This construction doesn't represent a family name; instead the `font-family` descriptor inside the at-rule describes that. This is just a name for the palette which can be reference from elsewhere within CSS. Therefore, we should leave it a `<custom-ident>`. We can open it up to strings later if we see the need to.

**Comment by tabatkins** [comment]
:+1:
