### ISSUE TITLE
[css-scoping] Explanation required : Why only direct children of the shadow host can be slotted?

### ISSUE THREAD

**Issue by praveenpuglia** [w3c/csswg-drafts#1530]
The __Example 4__ [here](https://drafts.csswg.org/css-scoping/#slotted-pseudo) says that
> only direct children of a shadow host can be assigned to a slot.

I couldn't find any explanation as to why it's restricted to only direct children. Should it be mentioned in the spec somewhere as a note or a reference link which expands on it?

Or please tell me if I missed something totally obvious.

**Comment by tabatkins** [comment]
That's just part of how Shadow DOM is defined, over in the [DOM spec](https://dom.spec.whatwg.org/#shadow-trees).  CSS doesn't impose this or care about it, I just called it out in the example to be informative.
