### ISSUE TITLE
[css-color] Example 9 syntax is outdated?

### ISSUE THREAD

**Issue by iccir** [w3c/csswg-drafts#1534]
Example 9 in [Profiled, Device-dependent Colors](https://drafts.csswg.org/css-color/#icc-colors) has colors specified via an 8-bit integer:

```css
color: color(swopc 0 206 190 77);
color: color(indigo 24 160 86 42 0 18 31);
color: color(prophoto 233 150 122);
color: color(p3 97 253 36);
```

From my understanding of section 11.2, these numbers should be be in the range of 0-1.

Also, the example references `p3`. I believe it's now `image-p3`?

**Comment by svgeesus** [comment]
Yes, I missed updating these. Will do, thanks for the report.
