### ISSUE TITLE
[cssom-view] getClientQuads

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#1543]
Right now, it's pretty difficult to get the size and position of an element that's undergone rotational transforms.

`getClientQuads` (on ranges and elements) would return a sequence of `DOMQuad`s representing the shape of the box.

Eg:

<img width="153" alt="screen shot 2017-06-20 at 15 59 06" src="https://user-images.githubusercontent.com/93594/27340134-90b0dc2c-55d1-11e7-9567-3104aec1c9c8.png">

The green box represents the behaviour of `getClientRects`, whereas the blue box represents the behaviour of `getClientQuads`.

**Comment by SebastianZ** [comment]
I assume this is what the [`getBoxQuads()`](https://drafts.csswg.org/cssom-view/#dom-geometryutils-getboxquads) method is meant for, though it's not properly defined yet.

Sebastian

**Comment by jakearchibald** [comment]
Haha yep, it's already there.
