### ISSUE TITLE
Estimated date

### ISSUE THREAD

**Issue by fabdelgado** [w3c/csswg-drafts#1549]
What is the estimated date of becoming a standard for W3C?

**Comment by fantasai** [comment]
Of what?

**Comment by fabdelgado** [comment]
That flexbox is a W3C standard.

**Comment by fantasai** [comment]
Flexbox is currently a Candidate Recommendation, which means it's fine for general use. It will become a REC once we have a complete test suite and two passing implementations; there's no ETA for that at the moment.
