### ISSUE TITLE
[css-display] 'flow' inner display type should never establish a BFC

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1550]
The [`flow`](https://drafts.csswg.org/css-display-3/#valdef-display-flow) inner display type is completely overloaded, it can generate 4 (!!!) different kinds of boxes: inline box, block container that establishes inline FC, block container that integrates into the parent BFC, or block container that establishes BFC.

So I propose that `flow` never establishes a BFC. Instead, all cases which require a BFC are handled by switching the inner display type to `flow-root` at used value time via [becoming a formatting context](https://drafts.csswg.org/css-display-3/#becoming-formatting-context). This would disentangle `flow` and `flow-root`. This change should have no effect in practice.

Something like this:

> **`flow`**
> 
> If its [outer display type](https://drafts.csswg.org/css-display-3/#outer-display-type) is [`inline`](https://drafts.csswg.org/css-display-3/#valdef-display-inline) or [`run-in`](https://drafts.csswg.org/css-display-3/#valdef-display-run-in), and it is participating in a block or inline formatting context, then it generates an [inline box](https://drafts.csswg.org/css-display-3/#inline-box).
> 
> Otherwise it generates a [block container](https://drafts.csswg.org/css-display-3/#block-container) box and integrates its contents into its parent [block formatting context](https://drafts.csswg.org/css-display-3/#block-formatting-context).
> 
> Note: certain circumstances, such as if the block container does not participate in a block formatting context, require the element to [become a formatting context](https://drafts.csswg.org/css-display-3/#becoming-formatting-context), and thus its [inner display type](https://drafts.csswg.org/css-display-3/#inner-display-type) is changed to [`flow-root`](https://drafts.csswg.org/css-display-3/#valdef-display-flow-root).

And in [Becoming a formatting context](https://drafts.csswg.org/css-display-3/#becoming-formatting-context) list these triggers:

 - Block containers that are not block boxes
 - Out-of-flow
 - `overflow` applies and is different than visible
 - The root element

**Comment by Loirooriol** [comment]
Despite mentioning that a block container can establish an inline formatting context, in the proposed text I forgot about that 😆. Anyways, I think this possibility should also be removed (at least for element-generated block containers), see #1617.

**Comment by tabatkins** [comment]
> block container that establishes inline FC, block container that integrates into the parent BFC

I don't see the difference between these two.

> inline box

Yup, inline box vs block box is the result of crossing {block, inline}x{flow}. That's fine.

> block container that establishes BFC.

We resolved that this makes sense to set at used value; making things establish a formatting context will now resolve "block flow" to "block flow-root" at used-value time.

We're currently keeping "what happens if you make 'inline flow', 'inline ruby', or 'block ruby' establish formatting contexts?" undefined; we'll figure it out what 'contain' does on these elements separately.

**Comment by Loirooriol** [comment]
> I don't see the difference between these two.

- block container that establishes inline FC

    This box establishes an inline formatting context. Its contents are all inline-level and participate in that inline formatting context.

 - block container that integrates into the parent BFC

    This box establishes no formatting context. Its contents are all block-level and participate in the parent block formatting context.

**Comment by tabatkins** [comment]
We don't make a real distinction between "filled only with inline content" and "filled only with block content". That's all flow layout.

**Comment by Roman0308** [comment]
[LICENSE.txt](https://github.com/w3c/csswg-drafts/files/1221698/LICENSE.txt)


[LICENSE.txt](https://github.com/w3c/csswg-drafts/files/1221699/LICENSE.txt)

**Comment by fantasai** [comment]
Checked in edits to define that “a block container that establishes a new <a>block formatting context is considered to have a used `display` value of `flow-root`.” This should be a purely editorial change.

@Loirooriol Let me know if that seems acceptable.
Agenda+ to double-check with the WG that this doesn't break anything. :)

**Comment by Loirooriol** [comment]
It's acceptable, but in fact I no longer have a strong opinion about this. I wanted the `flow` inner display type to never establish a BFC, and explain the cases in which a BFC is needed by saying that the used `display` value of the generating element has been changed to `flow-root`.

But this does not work well for `display: block ruby`, because the principal box may need a BFC due to e.g. `overflow: hidden`. I wanted to address this with a new `ruby-root` inner display type (#1700), which was rejected. This means that the establishment of a BFC can't be explained (not exclusively, at least) in terms of the element's display type.

Then, I don't mind noting that if an element with `flow` inner display type generates a block container that establishes a BFC, the result looks like if the element had a `flow-root` inner display type. But this doesn't seem to simplify things, which is what I initially wanted.

**Comment by Loirooriol** [comment]
Wait, it's not correctly written. It seems to imply that, if you have `display: list-item; float: left`, `display: list-item` will behave like `display: flow-root`, losing the marker.

I think it should say "is considered to have a `flow-root` inner display type at used-value time".

**Comment by fantasai** [comment]
@Loirooriol Fixed, thanks. :)
