### ISSUE TITLE
[css-flexbox-1] Two different definitions for flex: initial

### ISSUE THREAD

**Issue by sanoodles** [w3c/csswg-drafts#1555]
Regarding https://www.w3.org/TR/css-flexbox-1

At https://www.w3.org/TR/css-flexbox-1/#flex-initial says "Equivalent to flex: 0 1 auto"

But at https://www.w3.org/TR/css-flexbox-1/#propdef-flex says "Initial: 	1 0 auto"

Seems inconsistent.

**Comment by tabatkins** [comment]
Yup, this was fixed in the ED <https://drafts.csswg.org/css-flexbox/#flex-property>. The correct value is `0 1 auto`.  We just haven't republished the spec yet.
