### ISSUE TITLE
[css-text] Consider different keyword for `line-break: break-all`?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1561]
I found myself that when someone asks me about `break-all`, I ask them "which `break-all`?" since we added this in #1171.

Would it be reasonable to consider different keyword for this?

@frivoal @fantasai

**Comment by frivoal** [comment]
On the one hand, I think all the properties and values related to text wrapping are terribly named. On the other hand, I do not have a better suggestion. On the third hand (!?), within all this mess `line-break: break-all` seems to me to be one of the better names.

I'm not opposed to renaming it, if you have a good idea, but I certainly don't.

**Comment by kojiishi** [comment]
Oh, thank you for the info, I wasn't aware that was the reason. Hm, that's hard, you know I'm not good at giving a name, and I'm good with any name that is not the same keyword as only slightly different feature.

Some brainstorming:
1. `line-break: anywhere`, since other values of `line-break` don't use `break-/keep-*` convention.
2. `line-break: any-characters` -- too long?
3. `line-break: terminal`, from your PR #1438
4. `line-break: ascii-art`

Any particular one you may be ok/like, or some new ideas?

**Comment by patrickdark** [comment]
Suggestions: `inter-character` and `inter-word-character`.

**Comment by fantasai** [comment]
CSSWG resolved to add as `line-break: anywhere`.
