### ISSUE TITLE
[cssom] Spec no longer defines the general "shortest serialization" principle

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1564]
Back in [the 2011 WD](https://www.w3.org/TR/2011/WD-cssom-20110712/#serializing-css-values), there was a set of "serialization principles", giving general guidance about how to select the correct serialization of a CSS property.  In particular, it gave guidance about how to order re-orderable values (use the grammar order) and how to omit omittable values (do so whenever it wouldn't change the result of reparsing, unless it would leave you with an empty value).  The CSSWG still refers to and understands these principles as a general "shortest form" idea.

However, that no longer seems to be present in the current draft. In particular, it's missing from the following [2013 WD](https://www.w3.org/TR/2013/WD-cssom-20131205/#serializing-css-values).  This, or something like it, needs to be reinstated so as to actually give some guidance about how to serialize property values.

(We obliquely refer to this principle in the note at the end of [Align's baseline section](https://drafts.csswg.org/css-align/#baseline-values), and dbaron requests a link to the principle we're alluding to in #1415.)

**Comment by foolip** [comment]
I've run into this in https://github.com/w3c/web-platform-tests/pull/8548 (see @dbaron's comments) and in https://github.com/w3c/web-platform-tests/pull/8602 wrote a test that showed that all browsers except Chrome serialize the text-decoration shorthand to something more compact than the spec suggests. I'm going to revert the pass condition of the test and make it a tentative tests assuming that the spec will come to agree with the 3 instead of the 1.

**Comment by MatsPalmgren** [comment]
Can someone make the necessary edits here please? It seems to cause a lot of confusion about the correct serialization [[1]](https://github.com/w3c/csswg-drafts/issues/2229) [[2]](https://bugzilla.mozilla.org/show_bug.cgi?id=1432654) because this important principle isn't written down in a spec.

**Comment by tabatkins** [comment]
Ugh, we don't have an editor for the spec anymore. I'll do it soon if nobody else does.

**Comment by dbaron** [comment]
I'd note that it's probably worth making it clear that the principles are principles and probably not normative text.  In particular, I probably wouldn't want to see an implementor follow the principles to change something that's currently interoperable to be non-interoperable, but I would like to see the principles drive decisions for new features, and (within the constraints of web compatibility) for existing features that aren't currently interoperable.

I'd also note that some other principles for serialization are:
* serialization should always produce syntax that is valid when reparsed
* the composite function of serialize(parse()) should be idempotent, that is, reparsing and reserializing the result of serialization should produce the same thing you got from the first serialization

**Comment by FremyCompany** [comment]
Just want to make sure that the text we add back does mention that these general principles can be overriden in specifc instances due to web compat or ease of use of an api. Sometimes authors expect one easy-to-parse format over another that would be shorter (`rgba(0, 0, 0, 0)` vs `transparent`) and sometimes new values are added to a property and those new values would allow a shorter form than before, but that would not be web-compatible.

**Comment by dbaron** [comment]
Serializing to the form that's been specified longer is another general principle that should be documented, and generally overrides the principle of trying to be shorter.  (Though at some point we decided to break that for `transparent`, with Gecko being the last implementation to switch.)

**Comment by FremyCompany** [comment]
@dbaron We haven't switched yet in Edge on `transparent` I think
However we serialize the way the author specified so someone using rgba would get rgba.

**Comment by tabatkins** [comment]
Okay, done. I ended up replacing the whole algorithm; it was full of overly-specific and flat-out *wrong* details (some preserved from Anne's older draft, some new).  It now represents the "shortest serialization" principle of Anne's older draft, while being correct overall. It also normatively notes that some properties must serialize differently than this algorithm due to backwards-compat.

There are still a number of details to fix about serializing individual component values, but that'll be addressed by a separate issue.

**Comment by tabatkins** [comment]
@dbaron @FremyCompany Please review?
