### ISSUE TITLE
[css-fonts-4] Links swapped in negative oblique style range matching

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#1567]
In Section 5.2., style matching, for negative values, the rules are:

> If the value of font-style is oblique and the requested angle is less than 0deg and greater than -20deg, follow the steps above [1], except with the negated values and opposite directions. If the value of font-style is oblique and the requested angle is less than or equal to -20deg, follow the steps above [2], except with the negated values and opposite directions.

Where _above [1]_ points to https://drafts.csswg.org/css-fonts-4/#greater-oblique-steps and _above [2]_ points to https://drafts.csswg.org/css-fonts-4/#lesser-oblique-steps 

I believe, these links are swapped. 

A) `#greater-oblique-steps` points to the algorithm outside the 20 degree threshold, searching only towards the outside, then jumping zero and searching the opposite direction. 

B) `#lesser-oblique-steps` points to the algorithm for searching within the degree threshold, first searching towards zero, then outwards to the end of the range, then jumping zero and searching in the opposite direction.

[1] should point to B, [2] should point to [A].

CC @litherum

**Comment by litherum** [comment]
Yes.
