### ISSUE TITLE
[cssom-view] Doubts regarding the overflow directions description

### ISSUE THREAD

**Issue by anawhj** [w3c/csswg-drafts#1569]
This issue would be a very simple problem about [the definition of overflow directions](https://drafts.csswg.org/cssom-view/#overflow-directions).

According to the combination of a block flow direction and an inline base direction, the overflow direction can be determined. For example, if the block flow direction is top-to-bottom and the inline base direction is left-to-right, the overflow direction is rightward and downward. On the basis of [`CSS Writing Mode`](https://drafts.csswg.org/css-writing-modes-4/#text-flow), [`CSSOM View`](https://drafts.csswg.org/cssom-view) describes the combination and the overflow direction accordingly, but I think some cases would be wrong.

In the [`2. terminology`](https://drafts.csswg.org/cssom-view/#terminology) chapter in `CSSOM View`, it specifies that if the block flow direction is left-to-right and the inline base direction is left-to-right, the overflow directions is `rightward and downward`. But as far as my understanding, the overflow directions should be modified to `rightward and upward` in that case. Besides, there would be some errors like this case near the section.

cc - @zcorpan, @frivoal

**Comment by zcorpan** [comment]
Block flow direction being left-to-right and inline base direction being left-to-right is as in this test case, correct?
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5301

As far as I can tell, rightward and downward are the correct overflow directions for this case. Am I missing something?

**Comment by anawhj** [comment]
The overflow direction can be determined through block flow direction, inline base direction, and **inline orientation**. The test case specifies `{writing-mode: vertical-lr; direction: ltr}` that means rightward and downward ([image](https://drafts.csswg.org/css-writing-modes-4/diagrams/line-orient-right.svg)). However, if it specifies `{writing-mode: sideways-lr; direction: ltr}` that means rightward and upward ([image](https://drafts.csswg.org/css-writing-modes-4/diagrams/line-orient-left.svg)). `sideways-lr` is also the block flow direction being left-to-right, but it changes the inline orientation so that the overflow direction is different compared to `vertical-lr`. ([image](https://mdn.mozillademos.org/files/12201/writing-mode-actual-result.png))

In the above situation, I was a little confused when reading the terminology chapter in cssom-view spec, but now I've been clear on that, because `sideways-lr` had recently been deprecated option due to at-risky. So it seems no problem in the cssom-view spec, but someone who isn't familiar with writing-mode spec could be possible to be confused when reading the paragraphs in the terminology chapter of cssom-view spec.

**Comment by zcorpan** [comment]
Ah, OK, yeah I am also easily confused in this area.

It appears Gecko supports `sideways-lr`, but WebKit/Chromium/EdgeHTML do not. Does Gecko plan to remove it? cc @dbaron 

I'm happy to clarify the spec or fix it if it uses incorrect terminology, or add some examples.

**Comment by anawhj** [comment]
I checked that `sideways-lr` [sample app](https://codepen.io/placenamehere/pen/ZBQrzm) runs well in the latest Firefox(55.0.3) while I couldn't find any relevant issue in [bugzilla@mozilla](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=sideways), so it seems no plan to remove it in Gecko for now.
cc @jetvillegas @kojiishi

Regardless of life and death of `sideways-lr`, we could consider to improve the description of the overflow direction in cssom-view spec. It would be important because the spec readers likely isn't familiar with css-writing-mode spec so they will most likely be confused to understand it. As I see, the definition of the overflow direction needs for scrolling area explanation in cssom-view spec. If a [simple image](https://raw.githubusercontent.com/anawhj/experiment/master/overflow_direction.png) in which each cases of the overflow directions are described, could be added in the terminology chapter in cssom-view spec so that it will be clear for spec reader to easily understand it.

In addition, it would be specified where the scroll bar put according to each overflow directions in cssom-view spec.

**Comment by zcorpan** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1399432

**Comment by kojiishi** [comment]
The `sideways-lr` and `sideways-rl` are deferred to L4, not removed, and @anawhj is right that in `sideways-lr` the inline direction is bottom-to-top that the overflow direction is different.

Maybe we want to refer to [Abstract-to-Physical Mappings](https://drafts.csswg.org/css-writing-modes-4/#logical-to-physical) and use logical terms, such as "block-end" and "inline-end"?

**Comment by upsuper** [comment]
I don't think we want to remove `sideways-rl` and `sideways-lr` support from Gecko at the moment, given that it is still part of the spec (just deferred from L3 to L4 due to lack of implementation).

**Comment by anawhj** [comment]
In such a case, it could be a good candidate to use the logical terms (block-end, inline-end) as @kojiishi mentioned. Otherwise we could add the values of writing modes property into the description of each overflow directions in order to avoid confusing.

**Comment by anawhj** [comment]
The change([89e5017](https://github.com/dbaron/csswg-drafts/commit/89e5017fa983ea69ebf8db044a3f7b64140ad3b2)) makes it clear in terms of solving a problem of the confusing terminology.

In the [`CSSOM View`](https://drafts.csswg.org/cssom-view) spec, on the other hands, the `{up, right, down, left}-ward` terms are used in several contexts to mainly describe how scrolling behavior works according to the scrolling box's overflow direction. So if we want to remove the terms as a physical direction, several statements including `*-ward` seems to be rephrased. (When I search 'ward' in the document, I can see the corresponding terms more than fifty in the CSSOM View spec.)

Alternatively, we could consider to revise the description of the six cases for two overflow directions (`{left|right}-ward` and `{up|down}-ward`) depending on the viewport’s or element’s block flow direction and inline base direction. If we apply a factor of `line-orientation` to the description in addition to the existing two factors such as `block flow direction` and `inline base direction`, it makes clear for describing the exact terminology. It seems a intuitive way for understanding the meaning of the conditions, but the css-writing-mode spec describes as follows: (see [the original text](https://drafts.csswg.org/css-writing-modes-4/#horizontal-block-flow))

> To avoid confusion, CSS specifications avoid using the set of of terms, {up, right, down, left}-ward.

**Comment by dbaron** [comment]
https://github.com/w3c/csswg-drafts/issues/1569#issuecomment-405905260 seems like it's probably best put in a separate issue, with a clear description of what the problem is and why it should be fixed.
