### ISSUE TITLE
[css-align] Baseline of a multi-col box?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1572]
[8.1. Determining the Baselines of a Box](https://drafts.csswg.org/css-align/#baseline-export) specifies baselines for several layout models.

Is multi-col part of "block containers", or is it not listed and that should be synthesized?

[A simple test](http://output.jsbin.com/cenefep) indicates that:
* Edge/Gecko/WebKit handles as a box and synthesize.
* Blink as a block container and use the last baseline of the last column.

**Comment by tabatkins** [comment]
Further research [using tables](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/5274) shows that:

* Blink uses the first baseline of the first column (you can play around with the font size of the first lines of each column to verify)
* Firefox/Edge continue to synthesize from the margin box. I didn't test WebKit, but I presume it does the same.

So we have rough interop on multicol not having a native baseline, which isn't particularly useful behavior. In particular, with Grid Layout, this'll become more of a concern; the current behavior (only really visible with inline-block and tables) is probably not hit very often by authors (and for tables, it's just straight up bad behavior).

Blink's behavior for first baseline is reasonable, but its behavior for last-baseline is the worst.

So I think we have two choices:

1. Go with the rough interop and always synthesize from the margin box. This is okay for inline-block, but gives terrible results in table and grid.
2. Go with Blink's first-baseline behavior, but define a better last-baseline behavior. (Probably: lowest baseline among all the columns?)

**Comment by FremyCompany** [comment]
Option 2 looks a bit more useful, but I am not convinced it is worth the effort fixing our code. I'd slightly lean towards Option 1. Maybe use cases showing how this behavior would not play well with non-bfc-pearcing line rythms would convince me.
