### ISSUE TITLE
[css-backgrounds] background-size should be animatable if keywords match

### ISSUE THREAD

**Issue by alancutter** [w3c/csswg-drafts#158]
By my reading of the background-size spec, values that use keywords are not animatable.

https://drafts.csswg.org/css-backgrounds/#the-background-size
> Animatable:	as repeatable list of simple list of length, percentage, or calc (This means keyword values are not animatable.)

This means that you can't animate from `background-size: 10px` to `background-size: 20px` due to the implicit presence of the auto keyword (`background-size: 10px` computes to `background-size: 10px auto`).

Chrome <=50, Firefox, Safari and Edge will animate the above example, IE doesn't animate background-size.
Chrome 51 stopped animating these cases and received a bug report about it: http://crbug.com/616072
Chrome intends to revert its behaviour for compatibility with other browsers and animate background-size when keywords are positionally matched.

**Comment by tabatkins** [comment]
Nope, keywords are animatable.  Check the computed value definition carefully - all values get converted into a pair of length-percentages.

**Comment by shans** [comment]
"Computed value: as specified, but with lengths made absolute and omitted ‘auto’ keywords filled in"

I read that as saying that 'background-size: 10px' computes to 'background-size: 10px auto'. Is that an incorrect reading?

**Comment by alancutter** [comment]
I should be clearer with my example. I propose that `background-size: 50%, cover` and `background-size: 100%, cover` should be able to smoothly interpolate since the auto and cover keywords are matched.

**Comment by tabatkins** [comment]
So hey, I'm a dummy, I was thinking of background-position.

@alancutter That example is *way* more understandable, and I completely agree it should be animatable.
