### ISSUE TITLE
[css-fonts-4] font-variation-settings says it's animation like transform, but it's actually substantially different

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1580]
The [definition of font-variation-settings](https://drafts.csswg.org/css-fonts-4/#propdef-font-variation-settings) says:

> Animating font-variation-settings is possible using a mechanism similar to animating the transform property: Two declarations of font-feature-settings can be animated between if they are "like". "Like" declarations are ones where the same set of properties appear (in any order). If two declarations are "like" then animation occurs pairwise between corresponding values in the declarations. Otherwise, animation is not possible. In this situation, the "from" values of the animation are swapped to the "to" values at an unspecified time during the animation.

This seems inaccurate since animation of `transform` only matches types in the same order, whereas animation of `font-variation-settings` seems to match as long as the same set occurs in any order.

(It should perhaps also say something about the superseding rule applying before the animation rule?)

(I got here from w3ctag/design-reviews#183.)

**Comment by litherum** [comment]
Perhaps I should just move the comparison to `transform` into a note which can also mention the order dependency and the superseding rule application order. Is that sufficient?

**Comment by svgeesus** [comment]
Agree the comparison could be misleading; order definitely matters for transform while I *think* OT features are purposefully orthogonal
