### ISSUE TITLE
[css-display] Inlinified layout-internal not well-defined

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1582]
Now that #1390 removed the issue in the spec, the spec clearly says that e.g. an element with `display: table-row` that is inlinified should have an `inline` outer display type and a `table-row` inner display type. But this kind of box is not defined anywhere!

From #1390 it seems that inlinification should not affect layout-internal boxes.

**Comment by SelenIT** [comment]
Doesn't anonymous box fixup occur in that case, so such box ends up being an inline table?

**Comment by Loirooriol** [comment]
@SelenIT If it's not possible for a layout-internal box to be inlinified, the spec should say so. However, I think layout-internal boxes are inlinified, because inlinification happens before the creation of intermediary anonymous boxes, as explained in the note:

> Note: There are two methods used to fix up box types when a box is mismatched to its context. One is transformation of the computed value of display, such as blockification and inlinification described here. The other, taking place during box tree construction (after computed values have been determined), is the creation of intermediary anonymous boxes, such as happens in tables, ruby, and flow layout.

Therefore, inlinification should have no effect on layout-internal boxes, and then they will generate anonymous boxes after inlinification.

**Comment by fantasai** [comment]
I'm not entirely sure what the issue is here, but I've clarified the spec by pointingout what @SelenIT describes in https://github.com/w3c/csswg-drafts/issues/1582#issuecomment-313394320

**Comment by fantasai** [comment]
Let me know if there's anything further to address.
