### ISSUE TITLE
[css-display] <legend> with no box

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1584]
In [Box Generation](https://drafts.csswg.org/css-display-3/#box-generation), the spec says that `none` and `contents` cannot affect

> whether a [`<legend>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element) is the name of a [`<fieldset>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element). 

But in [Appendix B](https://drafts.csswg.org/css-display-3/#unbox),

> Per HTML, a [`<legend>`](https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element) with [`display: contents`](https://drafts.csswg.org/css-display-3/#propdef-display) is not a [rendered legend](https://html.spec.whatwg.org/multipage/rendering.html#rendered-legend), so it does not have magical display behavior. (Thus, it reacts to [`display: contents`](https://drafts.csswg.org/css-display-3/#propdef-display) normally.)

Not sure what exactly the first quote means with "name of a fieldset", my guess is that it refers to the rendered legend, but that contradicts the 2nd quote. If it means something else, please clarify.

**Comment by tabatkins** [comment]
The "name of a fieldset" is a semantic concept in HTML.  It has nothing to do with how the legend displays.  It's like how `th` elements still label a table row/column even if they're styled the same as `td`s.

**Comment by tabatkins** [comment]
The quoted phrase is also at the end of a longer paragraph listing other similar examples, which starts with an explicit explanation of what the examples are about:

> Markup-based relationships, however, are not affected by these values, as they are solely rendering-time effects. For example, although they may affect which table cell appears in a column, they do not affect which table cell is associated with a particular column element. Similarly, they cannot affect which HTML summary element is associated with a particular table or whether a legend is the name of a fieldset.

**Comment by Loirooriol** [comment]
Then a link to that "name of a fieldset" concept would be useful. I have no idea about what that is, fieldsets have a [`name` attribute](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-name) but that has no relation with legends.

**Comment by fantasai** [comment]
Alright, checked in some changes to be a little more explanatory rather than hooking into a somewhat indeterminate term in the HTML spec. Also filed https://github.com/whatwg/html/issues/3702 to get a bit more clarity on the HTML side.

**Comment by fantasai** [comment]
@Loirooriol Let me know if that adequately addresses your concerns?

**Comment by Loirooriol** [comment]
I think it's still easy to confuse "<{legend}> labeling <{fieldset}> contents" with "rendered legend". But I guess this is a HTML problem more than a CSS one, so it's OK.
