### ISSUE TITLE
[css-fonts-4]Bikeshed linking errors

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1585]
Chris@Epona ~/W3CWeb/WWW/TR/2017/WD-css-fonts-4-20170711
$ bikeshed spec
WARNING: Multiple elements have the same ID 'font-style-matching'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'font-size-adjust-prop'.
Deduping, but this ID may not be stable across revisions.
WARNING: Multiple elements have the same ID 'font-family-desc'.
Deduping, but this ID may not be stable across revisions.
WARNING: The following &lt;var>s were only used once in the document:
  '&lt;family-name>'
  '&lt;number>'
If these are not typos, please add an ignore='' attribute to the &lt;var>.
WARNING: Multiple elements have the same ID 'cssfontfacerule'.
Deduping, but this ID may not be stable across revisions.
LINK ERROR: Ambiguous for-less link for 'font-family', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-palette-values; text:font-family
for-less references:
spec:css22; type:property; for:/; text:font-family
spec:css22; type:property; for:/; text:font-family
&lt;a class="property" data-link-type="propdesc" data-lt="font-family">font-family&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-weight', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-weight
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-weight
for-less references:
spec:css22; type:property; for:/; text:font-weight
spec:css22; type:property; for:/; text:font-weight
&lt;a class="property" data-link-type="propdesc" data-lt="font-weight">font-weight&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-stretch', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-stretch
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-stretch
for-less references:
spec:svg; type:property; for:/; text:font-stretch
&lt;a class="property" data-link-type="propdesc" data-lt="font-stretch">font-stretch&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-style', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-style
spec:css-fonts-4; type:property; for:/; text:font-style
for-less references:
spec:css22; type:property; for:/; text:font-style
spec:css22; type:property; for:/; text:font-style
&lt;a class="property" data-link-type="propdesc" data-lt="font-style">font-style&lt;/a>
WARNING: Your console does not understand Unicode.
  Messages may be slightly corrupted.
LINK ERROR: Ambiguous for-less link for 'font-style', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-style
spec:css-fonts-4; type:property; for:/; text:font-style
for-less references:
spec:css22; type:property; for:/; text:font-style
spec:css22; type:property; for:/; text:font-style
&lt;a class="production" data-link-type="propdesc" data-lt="font-style" data-link-for-hint="font">&lt;&#8216;font-style&#8217;&gt;&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-weight', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-weight
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-weight
for-less references:
spec:css22; type:property; for:/; text:font-weight
spec:css22; type:property; for:/; text:font-weight
&lt;a class="production" data-link-type="propdesc" data-lt="font-weight" data-link-for-hint="font">&lt;&#8216;font-weight&#8217;&gt;&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-family', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-palette-values; text:font-family
for-less references:
spec:css22; type:property; for:/; text:font-family
spec:css22; type:property; for:/; text:font-family
&lt;a class="production" data-link-type="propdesc" data-lt="font-family" data-link-for-hint="font">&lt;&#8216;font-family&#8217;&gt;&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'font-kerning' that are marked for export.
&lt;a class="property" data-link-type="propdesc" data-lt="font-kerning">font-kerning&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'font-language-override' that are marked for export.
&lt;a class="property" data-link-type="propdesc" data-lt="font-language-override">font-language-override&lt;/a>
LINK ERROR: No 'type' refs found for '&lt;font-face-name>' that are marked for export.
&lt;a class="production" data-link-type="type" data-lt="&lt;font-face-name&gt;">&lt;font-face-name&gt;&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'font-face-name'.
&lt;a class="property" data-link-type="propdesc" data-lt="font-face-name">font-face-name&lt;/a>
LINK ERROR: Multiple possible 'propdesc' local refs for 'font-display'.
Arbitrarily chose the one with type 'descriptor' and for '@font-face'.
&lt;a class="property" data-link-type="propdesc" data-lt="font-display">font-display&lt;/a>
LINK ERROR: Ambiguous for-less link for 'block', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:value; for:font-display; text:block
spec:css-fonts-4; type:value; for:@font-face/font-display; text:block
for-less references:
spec:css22; type:value; for:/; text:block
spec:css22; type:value; for:/; text:block
&lt;a class="css" data-link-type="maybe" data-lt="block">block&lt;/a>
LINK ERROR: Multiple possible 'propdesc' local refs for 'font-display'.
Arbitrarily chose the one with type 'descriptor' and for '@font-face'.
&lt;a class="css" data-link-type="propdesc" data-lt="font-display">font-display: auto&lt;/a>
LINK ERROR: No 'at-rule' refs found for '@font-feature-values' that are marked for export.
&lt;a data-link-type="at-rule" data-lt="@font-feature-values">@font-feature-values&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'unicode-range' that are marked for export.
&lt;a class="property" data-link-type="propdesc" data-lt="unicode-range">unicode-range&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'font-feature-settings' that are marked for export.
&lt;a class="property" data-link-type="propdesc" data-lt="font-feature-settings">font-feature-settings&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'normal'.
&lt;a class="property" data-link-type="propdesc" data-lt="normal">normal&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'font-variant-ligatures' that are marked for export.
&lt;a class="property" data-link-type="propdesc" data-lt="font-variant-ligatures">font-variant-ligatures&lt;/a>
LINK ERROR: No 'propdesc' refs found for 'no-common-ligatures'.
&lt;a class="property" data-link-type="propdesc" data-lt="no-common-ligatures">no-common-ligatures&lt;/a>
LINK ERROR: Ambiguous for-less link for 'font-family', please see &lt;https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:css-fonts-4; type:property; for:/; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-face; text:font-family
spec:css-fonts-4; type:descriptor; for:@font-palette-values; text:font-family
for-less references:
spec:css22; type:property; for:/; text:font-family
spec:css22; type:property; for:/; text:font-family
&lt;a class="production" data-link-type="propdesc" data-lt="font-family">&lt;&#8216;font-family&#8217;&gt;&lt;/a>
LINK ERROR: Multiple possible 'descriptor' local refs for 'font-family'.
Arbitrarily chose the one with type 'descriptor' and for '@font-face'.
&lt;a data-link-type="descriptor" data-lt="font-family">font-family&lt;/a>
LINK ERROR: Multiple possible 'descriptor' local refs for 'font-display'.
Arbitrarily chose the one with type 'descriptor' and for '@font-face'.
&lt;a data-link-type="descriptor" data-lt="font-display">font-display&lt;/a>
WARNING: The following (probably auto-generated) link is illegally nested in another link:
&lt;a class="property" data-link-type="propdesc" href="https://www.w3.org/TR/CSS22/visudet.html#propdef-line-height">line-height&lt;/a>
 &#10004;  Successfully generated, with 23 linking errors

**Comment by svgeesus** [comment]
> WARNING: Multiple elements have the same ID 'font-style-matching'.
WARNING: Multiple elements have the same ID 'font-size-adjust-prop'.
WARNING: Multiple elements have the same ID 'font-family-desc'.

Those three were easy and have been fixed.

> WARNING: Multiple elements have the same ID 'cssfontfacerule'.

No they don't. No element in the .bs has that ID. Think these are generated from the IDL

**Comment by svgeesus** [comment]
> LINK ERROR: Ambiguous for-less link for 'font-family'

Worrying, as some are links to the property and some to the descriptor; these need to be distinct. Same comment for the next few errors, property/descriptor disambiguation needed.

**Comment by svgeesus** [comment]
> LINK ERROR: No 'propdesc' refs found for 'font-kerning' that are marked for export.
<a class="property" data-link-type="propdesc" data-lt="font-kerning">font-kerning</a>
LINK ERROR: No 'propdesc' refs found for 'font-language-override' that are marked for export.
<a class="property" data-link-type="propdesc" data-lt="font-language-override">font-language-override</a>
LINK ERROR: No 'type' refs found for '<font-face-name>' that are marked for export.
<a class="production" data-link-type="type" data-lt="<font-face-name>"><font-face-name></a>

Looking into those now.

**Comment by svgeesus** [comment]
Fixed some errors with

&lt;pre class="link-defaults">
spec:css-color-4; type:property; text:color
spec:css22; type:value; for:/; text:block
spec:css-fonts-4; type:descriptor; for:/@font-face; text:font-face-name
spec:css-fonts-4; type:property; for:/; text:font-family
spec:css-fonts-4; type:descriptor; for:/@font-face; text:font-family
spec:css-fonts-4; type:property; for:/; text:font-weight
spec:css-fonts-4; type:descriptor; for:/@font-face; text:font-weight
spec:css-fonts-4; type:property; for:/; text:font-stretch
spec:css-fonts-4; type:descriptor; for:/@font-face; text:font-stretch
spec:css-fonts-4; type:property; for:/; text:font-style
spec:css-fonts-4; type:descriptor; for:/@font-face; text:font-style
spec:css-fonts-3; type:property; for:/; text:font-kerning
spec:css-fonts-3; type:property; for:/; text:font-language-override
spec:css-fonts-3; type:descriptor; for:/@font-face; text:unicode-range
&lt;/pre>

**Comment by svgeesus** [comment]
The recently-documented 'Prepare for TR: yes` metadata also helps here
https://tabatkins.github.io/bikeshed/#metadata-prepare-for-tr

**Comment by litherum** [comment]
I don't know if I'm smart enough to fix this kind of thing. Is there documentation for Bikeshed to help with this stuff?

**Comment by astearns** [comment]
Yes, there is documentation. Not sure if this section is relevant to the remaining errors, though

https://tabatkins.github.io/bikeshed/#autolinking

**Comment by tabatkins** [comment]
@svgeesus I'm not sure how that block fixed anything; all the "descriptor" lines have a bad `for` value (should be `for: @font-face`, no slash), and the ones that are defined for css-fonts-4 are redundant (local definitions *already* auto-win against foreign definitions; the link-defaults block just lets you specify which foreign definition to default to when you don't want to fully-qualify every autolink).  Only the second-to-last and third-to-last lines (specifying properties defined in fonts-3 that haven't been ported to fonts-4 yet) have an effect here, as they'll override the default "never autolink to a different version of the current spec" behavior.

**Comment by svgeesus** [comment]
@tabatkins thanks for the comments. I was adding stuff that bikeshed seemed to be suggesting I add.
@litherum I will correct these (unless you get to it first)
