### ISSUE TITLE
[css-tables][css-ruby] Fixup should create inline-table when parent inlinifies

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1590]
The [fix-up algorithm](https://drafts.csswg.org/css-tables-3/#fixup-algorithm) only creates an anonymous `inline-table` when the parent box is an inline box.

However, this should also happen whenever the parent inlinifies its contents. It's worth noting that, according to [CSS Display](https://drafts.csswg.org/css-display-3/#transformations), inlinification happens before anonymous fix-up, so the fix-up algorithm can't rely on inlinification to make `table` become `inline-table`.

Currently I think inlinification only happens in ruby containers, and run-in boxes with a `flow` inner display type. Gecko is the only proper implementation of ruby, and effectively it seems to generate an anonymous inline-table inside a ruby container. I don't know any implementation of run-ins, but a run-in with a `flow` inner display type seems to be considered an inline box (this should be clarified in #1491); so this case may already be covered by the current spec.

**Comment by fantasai** [comment]
This is a different process than inlinification, which is a computed-time operation. Refiling against CSS Tables: they just need to say that an inline-table is generated inside ruby bases / annotations, just like it is inside regular inline boxes. (As you note, handling within run-ins is clarified in #1491.)
