### ISSUE TITLE
[css-flexbox][css-grid] clarify whether generated content can be a flex/grid item

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#1591]
Chrome, Edge, Firefox and Safari all treat generated content of a flex container as a flex item.  The spec [says](https://drafts.csswg.org/css-flexbox/#flex-items) "Each in-flow child of a flex container becomes a flex item", but I'm not sure if generated content counts as an in-flow child.  It would be good if the spec clarified this, and perhaps had an example with a ::before or ::after being treated as a flex item.

(Similarly for grid.)

**Comment by SelenIT** [comment]
CSS Pseudo-Elements Module Level 4 [says](https://drafts.csswg.org/css-pseudo/#generated-content) that `::before` and `::after` pseudo-elements

> generate boxes _as if they were immediate children_ of their originating element, and can be styled _exactly like any normal document-sourced element in the document tree._

The term "in-flow"[ is defined](https://drafts.csswg.org/css-display/#glossary) in the CSS Display Module Level 3 as a box that is neither floated nor absolutely-positioned.

Doesn't it clearly imply that the `::before` and `::after` pseudo-element that is neither floated nor absolutely-positioned should be treated exactly the same as a normal in-flow element in the same position in the tree, i.e. an in-flow child of the container?

**Comment by tabatkins** [comment]
::before/after is definitely in-flow content by default. There's nothing that would suggest it isn't, and as @SelenIT points out, the Pseudo spec defines them properly.  (If we did assume it wasn't, then *lots* of things would either break or be undefined for them.)

**Comment by heycam** [comment]
OK, that's fair.  I guess I at least would have benefited from a reminder that ::before/::after boxes are included, though.

**Comment by fantasai** [comment]
Problem is, if we put a reminder here, then everywhere we didn't put a reminder they'd be a question of "but what about this property". :) So we're consistently leaving it all out.
