### ISSUE TITLE
[css-text] Error in text-spacing: space-end description

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#1593]
https://drafts.csswg.org/css-text-4/#valdef-text-spacing-space-end

> space-end
> Set fullwidth opening punctuation with full-width glyphs (spaced) at the start of each line.

This should be:
> Set fullwidth **closing** punctuation with full-width glyphs (spaced) at the **end** of each line.

**Comment by frivoal** [comment]
pinging editors @fantasai @kojiishi @astearns

**Comment by frivoal** [comment]
Not an editor of this spec, but fixed it anyway.
