### ISSUE TITLE
[css-flexbox] Outdated information in the "Changes" section?

### ISSUE THREAD

**Issue by SelenIT** [w3c/csswg-drafts#1595]
It appears that the "Changes" section in the spec, especially the parts describing old changes, contains some statements that are now irrelevant, e.g. references to `display-inside`/`display-outside` longhands [in the 2012 clarification sub-section](https://drafts.csswg.org/css-flexbox/#clarify-2012-display-blockification).

Should this info be kept in the spec? On the one hand, it may be helpful to understand the history of the module development. On the other hand, it may be confusing for devs and make them assume that some concepts currently removed from other specs still exist. I'm afraid that the potential harm of the latter overweighs the potential benefit of the former (you can get the history of the module from comparing different /TR/ versions if you really need to).

What would be the best way of mentioning old changes that are no more relevant in the spec?

**Comment by tabatkins** [comment]
I'm inclined to just leave it alone; yes, the changes list gradually becomes outdated, but the alternative is that we police and update our changes list *in addition to* the specs themselves, which is a ton of work for very little reward.

At this point we should probably just remove that older changes list.

**Comment by fantasai** [comment]
We probably need to keep those around until we have interop on the spec, since it's a record of "things implementers need to make sure they got updated from their original attempt at implementation, and therefore a likely source of spec-compatibility bugs".

Anyway, closing this issue. :) We'll clear out the entire changes list at PR.
