### ISSUE TITLE
[css-text-4] typo in 10.1

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#1596]
https://drafts.csswg.org/css-text-4/#valdef-text-spacing-space-end

>space-end
>    Set fullwidth opening punctuation with full-width glyphs (spaced) at the start of each line. 

This definition is the same as `space-start`. I feel that following description is correct.

Set fullwidth opening punctuation with full-width glyphs (spaced) at the *end* of each line.

**Comment by frivoal** [comment]
Thanks for the report. This has already been reported in #1593. Closing as duplicate.

**Comment by momdo** [comment]
Oh... I had missed that PR.
