### ISSUE TITLE
Typo in the [css-grid-1] spec 

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#1602]
There's a typo in the spec, in section 3.3
https://www.w3.org/TR/css-grid-1/#grid-area-concept

It says `A grid area consists of one or more adjecent grid cells.`, when `adjecent` should be spelled `adjacent`.

This bug was reported on Twitter by Ohans Emmanuel. 
https://twitter.com/ohansemmanuel/status/885370706938277889
Thanks Ohans!

**Comment by ohansemmanuel** [comment]
Thanks @jensimmons

**Comment by ohansemmanuel** [comment]
I'll go ahead and delete the issue I filed earlier. So we don't have duplicates flying around.
