### ISSUE TITLE
[css-scroll-snap] Classify pageup/pagedown keys

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1605]
Tab and I were discussing the pageup/pagedown keys and noticed they weren't classified in https://www.w3.org/TR/css-scroll-snap-1/#scroll-types

We propose adding them to the "intended direction and end point" class, since they are definitely directional and also have a fairly explicit idea (to the user as well as the UA) of the amount by which we should scroll (even if that amount is a little fuzzy around the edges for cognitive stitching, it's understood to be a screenful).

**Comment by SebastianZ** [comment]
> it's understood to be a screenful

To be precise, a viewportful.

Sebastian

**Comment by frivoal** [comment]
>  It's understood to be a screenful

> To be precise, a viewportful.

To be pendantic, a optimal-viewing-regionfull. https://drafts.csswg.org/css-scroll-snap/#optimal-viewing-region

**Comment by fantasai** [comment]
CSSWG resolved to have paging operations under "intended direction and end position" and homing operations under "intended end position". This has now been edited in.
