### ISSUE TITLE
[css-align] Which behavior for block's "justify-self: center"?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1612]
There are two possible behaviors for `justify-self:center` on blocks in the presence of a float:

1. Reduce the size of the alignment container by the size of the float's margin box, then center the block in the remaining space (this is the behavior of HTML's `align` attribute)
2. Center the block ignoring the float, then shift it out of the way of the float if necessary. (This is the behavior of centering a BFC with auto margins.)

@fantasai and I are leaning toward option 1, simply because we already have a way to do option 2 in CSS, and both behaviors are useful in different circumstances.  Also, since we're trying to explain the behavior of `align` using `justify-self`, the property should be able to duplicate this behavior.

**Comment by SelenIT** [comment]
Isn't option 1 also what HTML's `center` element does by default (which appears to be implemented via vendor-prefixed values like `-moz-center` /`-webkit-center` for `text-align`)?

**Comment by rachelandrew** [comment]
Option 1 seems as if it would be easier to explain / more like existing behaviour. So unless there are strong arguments for 2, I'd prefer 1.

**Comment by fantasai** [comment]
Testcase: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5281
