### ISSUE TITLE
[css-sizing] stretch-fit sizing doesn't cover grid items, or "theoretical layout"

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1613]
When looking for how big `stretch` should become ([Stretch-Fit Sizing](https://drafts.csswg.org/css-sizing-3/#stretch-fit-sizing)), there are two cases that it looks at:

* the element is root/abspos, in which case it returns the size of the containing block
* otherwise, it does some min/max based on the min/max/ordinary inline-size properties of the element establishing the containing block (or recurses, if `inline-size` isn't definite)

These two cases miss some elements. A grid item would fall into the second bullet, but its containing block (the grid area) is established by the grid container, and you *do not want* the grid container's `width` to be consulted here! Instead, you just want to use the size of the grid area, like the first bullet point.

Similarly, any time we do "hypothetical" layout of an element in the course of running a layout algorithm (like, "layout the element into X space"), we want to use that explicitly-given size; there's no element establishing a containing block at all!

**Comment by fantasai** [comment]
Fwiw, grid item's containing block _is_ the grid area.

**Comment by tabatkins** [comment]
Yes: 

> A grid item would fall into the second bullet, but its containing block (the grid area) is established by the grid container,

The problem is that the containing block is established by *the grid container*, and we don't want the properties of that element here.

**Comment by tabatkins** [comment]
The resolution to #1614 (behave as either `place-self: stretch` or `width/height: auto`, as required) makes this issue moot.
