### ISSUE TITLE
[css-text-3] 'word-break: keep-all' needs to be defined more precisely

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1619]
The current ['word-break: keep-all'](https://drafts.csswg.org/css-text-3/#valdef-word-break-keep-all) has:
> Breaking is forbidden within “words”: implicit soft wrap opportunities between typographic letter units are suppressed, i.e. breaks are prohibited between pairs of letters (regardless of line-break settings) except where opportunities exist due to dictionary-based breaking. Otherwise this option is equivalent to normal. In this style, sequences of CJK characters do not break.

But this isn't very clear which break opportunities should really be suppressed. Blink has an impl, but I'm afraid this isn't interoperable.

One possible idea we could borrow from ICU discussion in [ICU notes F2](http://cldr.unicode.org/development/development-process/design-proposals/specifying-text-break-variants-in-locale-ids#TOC-F2.-keywords--ss---lw-) is:
> For "keepall", if the class is Hangul (H2, H3, JL, JV, JT) or ID, remap to AL

This is a bit different from what the current wording says, but suited for the original purpose and easy to make it interoperable.

I remember, this text was written before we generally try to move Unicode line break property, and was not updated since then while other values such as 'break-all' was changed, is this correct memory, @fantasai ?

**Comment by litherum** [comment]
Retitling due to [Betteridge's law of headlines](https://en.wikipedia.org/wiki/Betteridge%27s_law_of_headlines)

**Comment by fantasai** [comment]
I think the spec is clear: Hangul is covered under the definition of “typographic letter unit”; I don't think there are any Hangul which is not a Letter.

>Breaking is forbidden within “words”: implicit soft wrap opportunities between typographic letter units (or other typographic character units belonging to the NU, AL, AI, or ID Unicode line breaking classes [UAX14]) ...

@kojiishi Let me know if this answers your question.

**Comment by fantasai** [comment]
The behavior for symbols is clarified in https://github.com/w3c/csswg-drafts/commit/b3b36847b440c20b39db3987a3df68e9a892b55a
