### ISSUE TITLE
[selectors-4] Target elements or target elements?

### ISSUE THREAD

**Issue by domenic** [w3c/csswg-drafts#162]
https://drafts.csswg.org/selectors-4/#the-target-pseudo

> The :target pseudo-class matches the document’s target elements. If the document’s URL has no fragment identifier, then the document has no target element.

The intention seems to be that a document can have multiple target elements. (HTML can only have one, but I can see CSS wanting to stay general, for whatever reason.)

If so, the last sentence should probably be "the document has no target element**s**".

This is causing minor confusion in https://github.com/whatwg/html/pull/1370/files/6048d915035fefd69e31f903beac6f53356e4462#r65485805

**Comment by tabatkins** [comment]
I believe it's valid in English to be singular *or* plural there?  (Your link is invalid.)

**Comment by domenic** [comment]
I don't think it makes sense to refer to it in the plural in one sentence, then singular in the next. Let's try:

"The fluffy descriptor matches Domenic's fluffy dogs. If Domenic's dogs are shaved, then Domenic has no fluffy dog."

I guess this is technically true, but still pretty confusing...

**Comment by tabatkins** [comment]
That sounds 100% fine to me.

(That said, I have zero objection to adding an s to that word. I'll do so in a moment.)

**Comment by upsuper** [comment]
A bit out of topic: using plural reminds me that it is possible that a page may actually want multiple targets, for example, in code viewing, you may want to select several lines e.g. L5-L10. But I guess something like this is hard to spec given the current situation...

**Comment by tabatkins** [comment]
Nothing wrong with it - HTML *currently* defines that the target element is just the one referred to by the hash, but we also have special-purpose fragments (Media Fragments) and so there's nothing theoretically stopping us from having a special-purpose fragment that can hit multiple elements.
