### ISSUE TITLE
[css-fonts-4] Should transform/zoom affect optical sizing?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#1620]
I'm investigating what changes should cause a) just re-paint, b) re-measure glyph bounds, or c) re-shape.

Are there any OpenType features that require re-shape when transform/zoom changes? Should this be defined, or should this definition belong to OpenType?

Thoughts appreciated. /cc @litherum @drott @eaenet

**Comment by litherum** [comment]
@robmck-ms wrote up a great description of their research [here](https://github.com/w3c/csswg-drafts/issues/807). I attempted to follow his advice when implementing this in WebKit.

**Comment by kojiishi** [comment]
Thank you, I wasn't aware of that but yes, this is a great description!

I think this is dup to #807 then.

**Comment by fantasai** [comment]
Reopening to suggest that advice be informatively either incorporated or linked from a relevant spec somewhere so that other implementors can find it. :)

**Comment by litherum** [comment]
The advice is incorporated. https://github.com/w3c/csswg-drafts/commit/3911bf24d62822a9250121e0ad7c5f27e5a8c604
