### ISSUE TITLE
[css-display] Position of 'list-item'  when serializing <display-listitem>

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1621]
The [summary table](https://drafts.csswg.org/css-display-3/#display-value-summary) in CSS Display says that `list-item inline flow` serializes to `inline list-item`.

However, the syntax is

```
<display-listitem> = list-item && <display-outside>? && [ flow | flow-root ]? ;
```

Then, according to the ["shortest serialization" principle](https://www.w3.org/TR/2011/WD-cssom-20110712/#serializing-css-values) (which is going to be reintroduced in #1564), it should serialize to `list-item inline`:

> Where multiple CSS component values can appear in any order without changing the meaning of the value (typically represented by a double bar `||` in the value syntax), use the order as given in the syntax.

Therefore, I think either the summary table should say `list-item inline` or the syntax of `<display-listitem>` should move the `list-item` keyword to the end.

**Comment by Loirooriol** [comment]
@tabatkins Then you should also reorder `list-item block flow` and `list-item inline flow` entries in the "Full `display`" column of the summary table.

**Comment by fantasai** [comment]
@Loirooriol Done, thanks.
