### ISSUE TITLE
[css-lists] Drop 'inline-list-item'

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1624]
Per [CSSWG resolution](https://lists.w3.org/Archives/Public/www-style/2017Jul/0015.html), `inline list-item` [was dropped](https://github.com/w3c/csswg-drafts/commit/94b7b00c51be31196521f73543ed5b4bd63486d2) from CSS Display in favor of `inline list-item`. I guess it should also be removed from [CSS Lists](https://drafts.csswg.org/css-lists/#valdef-display-inline-list-item).

**Comment by tabatkins** [comment]
It's been dropped.

**Comment by Loirooriol** [comment]
For reference, dropped in https://github.com/w3c/csswg-drafts/commit/e1720ff0569d4eac1fe695e810b0a92f29e67b90.
