### ISSUE TITLE
[css-display] Bikeshed links CSS Lists but spec text references CSS 2

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1626]
[CSS Display - Generating Marker Boxes](https://drafts.csswg.org/css-display-3/#list-items) says

> the content specified by its [`list-style`](https://drafts.csswg.org/css-lists-3/#propdef-list-style) properties ([CSS 2.1§12.5 Lists](https://www.w3.org/TR/CSS2/generate.html#lists)) [\[CSS2\]](https://drafts.csswg.org/css-display-3/#biblio-css2)

It's confusing that `list-style` links https://drafts.csswg.org/css-lists-3/#propdef-list-style but CSS 2.1§12.5 is referenced instead.

**Comment by fantasai** [comment]
We're referring to the 2.1 spec because CSS Lists L3 is too rough/early of a draft to be referenced. Tab's just tweaked the autolink now, so they should go to the same place.
