### ISSUE TITLE
[css-sizing][css-multicol][css-grid-1] taking into account gaps/gutters in Intrinsic Sizes in Multi-column and Grid Layout

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#163]
https://drafts.csswg.org/css-sizing/#multicol-min-content says:

> 
The min-content inline size of a multi-column element with a computed column-width of auto is the largest min-content inline-size contribution of its contents multiplied by its column-count (treating auto as 1). 

Is that right? How about `column-gap`? Doesn't this make more sense?

> 
The min-content inline size of a multi-column element with a computed column-width of auto is the largest min-content inline-size contribution of its contents multiplied by its column-count (treating auto as 1), plus the column-gap multiplied by column-count minus 1.

Similarly, I think
> The min-content inline size of a multi-column element with a computed column-width not auto is the smaller of its column-width and the largest min-content inline-size contribution of its contents. 

should be

> The min-content inline size of a multi-column element with a computed column-width not auto is the smaller of its column-width and the largest min-content inline-size contribution of its contents, multiplied by by its column-count (treating auto as 1), plus the column-gap multiplied by column-count minus 1.

**Comment by frivoal** [comment]
Actually, it's the same issue in https://drafts.csswg.org/css-sizing/#multicol-max-content and https://drafts.csswg.org/css-sizing/#multicol-max-content-restrained
everytime you multiply something by the `column-count`, you need to add the `column-gap` multiplied by `column-count` minus 1.

**Comment by frivoal** [comment]
> Similarly, I think
> 
>     The min-content inline size of a multi-column element with a computed column-width not auto is the smaller of its column-width and the largest min-content inline-size contribution of its contents.
> 
> should be
> 
>     The min-content inline size of a multi-column element with a computed column-width not auto is the smaller of its column-width and the largest min-content inline-size contribution of its contents, multiplied by by its column-count (treating auto as 1), plus the column-gap multiplied by column-count minus 1.

Actually, scrap that, this part is wrong. The rest still stands.

**Comment by mrego** [comment]
I think we've a similar issue on the [Grid Layout spec](https://drafts.csswg.org/css-grid/#intrinsic-sizes):
> The max-content size of a grid container is the sum of the grid container’s track sizes in the appropriate axis, when the grid is sized under a max-content constraint.
> 
> The min-content size of a grid container is the sum of the grid container’s track sizes in the appropriate axis, when the grid is sized under a min-content constraint.

I guess we should include the [gutters](https://drafts.csswg.org/css-grid/#gutters) here too.

**Comment by tabatkins** [comment]
Yeah, we're missing gaps/gutters in those.

**Comment by tabatkins** [comment]
Okay, so Multicol is done now, and Grid specifically defines that gutters are treated as tracks for the purposes of sizing, so we don't actually need to call out gutters specifically there.
