### ISSUE TITLE
[css-fonts-4] Font shorthand can not reliably parse oblique <angle>, needs <font-style-css3> exception

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#1630]
[The font shorthand property](https://drafts.csswg.org/css-fonts-4/#font-prop) says:

> The font property is, except as described below, a shorthand property for setting font-style, font-variant, font-weight, font-stretch, font-size, line-height, font-family at the same place in the stylesheet. 

For font-stretch and font-variant exceptions are specified which restrict them to a restricted keyword syntax.

For font-style, no such exception is defined yet. 

I believe however, that allowing `oblique <angle>` into the font shorthand syntax causes parsing tokenization ambiguities and would not work reliably. 

I would suggest to change the syntax rule for font-style to use something like

`<font-style-css3> = [normal | italic | oblique]`

**Comment by litherum** [comment]
Yes.

**Comment by litherum** [comment]
I don't think there are ambiguities. Nothing else in the `font` shorthand accepts an angle.

WebKit currently parses the full font-style syntax in the `font` shorthand.

**Comment by drott** [comment]
Thanks for your analysis, I think you're right, since font size and angle need a unit. I had in mind a case like `font: oblique 20 sans-serif;`

Does WebKit serialize an oblique value - say, 35deg - into the computed style of the font shorthand as `... oblique 35deg ...`?

**Comment by litherum** [comment]
I don't have a build handy right now, so I can't check, but from code inspection, it looks like we don't right now ([fontShorthandValueForSelectionProperties()](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/CSSComputedStyleDeclaration.cpp#L2620)). We probably should, though.

**Comment by litherum** [comment]
Is there anything left to do here?

**Comment by drott** [comment]
No, I think this can be closed.
