### ISSUE TITLE
[css-fonts-4] Which font properties should be reset by the font shorthand?

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#1636]
https://drafts.csswg.org/css-fonts-4/#font-prop

The canonical order of the font shorthand is defined by reference to its grammar, but that doesn't take into account properties that are reset to their initial value and can't be specified in the shorthand value (such as font-size-adjust).

**Comment by litherum** [comment]
Yeah, I just need to add something describing exactly which properties are set by this shorthand.

See also: https://github.com/w3c/csswg-drafts/issues/1349

**Comment by litherum** [comment]
Before I can make these edits, I need to run the experiment to see which properties each browser resets already. Hopefully the results of this experiment are fairly consistent across browsers and I can just document what browsers already do. Otherwise, we will need some way to resolve which properties are in the set an which are not.

**Comment by litherum** [comment]
[Archive.zip](https://github.com/w3c/csswg-drafts/files/1166883/Archive.zip)

Here's the test. Unfortunately, it doesn't look like there's a lot of agreement.

**Comment by litherum** [comment]
<img width="1279" alt="screen shot 2017-07-21 at 3 26 30 pm" src="https://user-images.githubusercontent.com/918903/28484806-66fc0a3a-6e29-11e7-8285-bad73bbf87c4.png">

**Comment by litherum** [comment]
![2017-07-22 2](https://user-images.githubusercontent.com/918903/28489284-85d4a736-6e75-11e7-812a-c0de2f8a76f7.png)

**Comment by litherum** [comment]
So, all the browsers support `font-feature-settings` but only Firefox sets it with the shorthand.

**Comment by fantasai** [comment]
@heycam Does the canonical order matter if it can't be represented in the shorthand? The canonical order just exists to define serialization order for reorderable value components, if there's no representation then it can't be part of the order...

**Comment by litherum** [comment]
I assumed you were talking about an explicit list about which properties are reset by the font shorthand. @heycam Are you talking about something else?

**Comment by dbaron** [comment]
Here's a slightly revised version of the test designed to trigger slightly fewer browser bugs and potentially report an orange state in the presence of others.
[test.zip](https://github.com/w3c/csswg-drafts/files/1197271/test.zip)

(Firefox doesn't actually honor the "Computed value: as specified" for font-language-override, and drops things that aren't valid language tags.)

**Comment by dbaron** [comment]
With the revised test:

Chrome 59 screenshot:
![font-chromium](https://user-images.githubusercontent.com/248721/28923664-aaeac204-7856-11e7-90be-e1664c7e8aa0.png)

Chrome 59 with experimental web platform features screenshot:

![font-chromium-experimental](https://user-images.githubusercontent.com/248721/28923704-ca7d972c-7856-11e7-988f-704ee62b6be2.png)

Gecko nightly screenshot:
![font-gecko](https://user-images.githubusercontent.com/248721/28923711-d33a2e52-7856-11e7-8406-ab452dafb3eb.png)

**Comment by litherum** [comment]
WebKit on Sierra

<img width="351" alt="screen shot 2017-08-03 at 4 02 54 pm" src="https://user-images.githubusercontent.com/918903/28925461-4684cbd4-7865-11e7-8cf8-981df7521d11.png">

**Comment by litherum** [comment]
Thanks for fixing the test, @dbaron!

**Comment by litherum** [comment]
The CSSWG discussed this in https://github.com/w3c/csswg-drafts/issues/1349. (But, because this one has the test case, duping that thread to this one)

**Comment by litherum** [comment]
Edge 16

![image](https://user-images.githubusercontent.com/918903/28925927-8db53894-7866-11e7-9e29-9a21a79123dc.png)

**Comment by litherum** [comment]
... and `font-presentation` and `font-synthesis` should not be reset by the shorthand.
