### ISSUE TITLE
[css-display] Run-in insertted after ::marker

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1638]
In [Run-In Layout](https://drafts.csswg.org/css-display-3/#run-in-layout), CSS Display says

> If a run-in sequence is immediately followed by a block box that does not establish a new block formatting context, it is inserted as direct children of the block box after its `::marker` pseudo-element’s boxes (if any)

This is clear for most cases but not completely for some degenerated ones:

 - The `::marker` pseudo-element may have `display: contents` and thus generate no box, but its descendants (created via the `content` property) may do so. For consistency, I guess the run-in should be inserted after the boxes or text runs generated by these descendants.
 - The `::marker` pseudo-element may be wrapped inside an anonymous parent box (unless the run-in munging happens first, which I'm not sure in cases other than CSS2§9.2). For consistency, I guess the run-in should be inserted after that anonymous box.

So it could say something like

> If a run-in sequence is immediately followed by a block box that does not establish a new block formatting context, it is inserted as direct children of the block box after any box or text run which is or contains any box or text run generated by any node in the subtree rooted at the `::marker` pseudo-element.

However, this doesn't seem much natural. That's because `::marker` lives in the (pseudo-)element-tree while the run-in munging is done in the box-tree. Would it be bad to simply insert the run-in at the very beginning of the block box?

**Comment by Loirooriol** [comment]
OK, I just saw CSS Lists has been edited. Now it says that the whole spec is not ready for implementation and `::marker` has been restricted back to what CSS Pseudo says, in particular `display` cannot be used on it. So this issue is not a problem now, but it will be if the `::marker` restrictions are lifted in the future.

**Comment by tabatkins** [comment]
k, closing for now, since it's not relevant unless we make future changes
