### ISSUE TITLE
[css-display] Are run-in sequences recalculated after reinsertions?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1639]
Consider this code:

```html
<span style="display: run-in">Foo</span>
<div>
  <span style="display: run-in">Bar</span>
</div>
```

Foo is inserted inside the div block box. But then, do Foo and Bar become part of the same run-in sequence? Or do they continue being different sequences, and thus are wrapped in different anonymous block boxes? That is, does being reparented recalculate run-in sequences?

**Comment by SelenIT** [comment]
I'd expect them becoming part of the same run-in sequence. Reparenting makes them siblings in the box tree, doesn't it?

**Comment by Loirooriol** [comment]
Yes, intuitively it seems so. But I'm asking because since the munging depends on the run-in sequences, altering them in the process seems potentially problematic. Anyways the algorithm seems stable enough so that this does not matter, probably it's OK.

**Comment by tabatkins** [comment]
I'd prefer them to munge together into one sequence, personally.
