### ISSUE TITLE
[css-display] Do replaced elements have an inner display type?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1642]
[CSS Display](https://drafts.csswg.org/css-display-3/#inner-display-type) says

> The inner display of a replaced element is outside the scope of CSS.

I'm not sure if this means that:

 1. Replaced elements have an inner display type set to some value which is not defined by CSS Display because it's outside the scope of CSS.
 2. Replaced elements don't have an inner display type because how the contents of a replaced element are laid out is outside the scope of CSS.
 3. Whether replaced elements have an inner display type or not is outside the scope of CSS.

The difference matters because in [the glossary](https://drafts.csswg.org/css-display-3/#atomic-inline) there is this sentence:

> Any inline-level box whose inner display type is not flow establishes a new formatting context of the specified inner display type.

With (1) it seems clear that the condition holds, so an inline-level replaced element would establish a new formatting context. But I think this should not be imposed because it's outside the scope of CSS. With (2) or (3) it's not much clear whether the condition holds or not.

Anyways, I don't understand what that sentence is doing in the "atomic inline" entry, I would remove it. Does not seem much related other than atomic inlines being inline-level. And is kinda pointless, given that all the non-replaced non-layout-internal inner display types other than `flow` seem to generate some box which establishes a new FC, independently on the outer display type.

**Comment by SebastianZ** [comment]
Also, what does it mean when you set an inner display type for replaced elements and will the computed value still be "as specified"?

Sebastian

**Comment by tabatkins** [comment]
The intended meaning is 3 (the interior of a replaced element is fully undefined within CSS), but it doesn't matter what goes on inside of a replaced element anyway - it has no children that CSS knows of, and has special layout rules that cover the cases where it might matter that it establishes an FC or not anyway.

> Anyways, I don't understand what that sentence is doing in the "atomic inline" entry, 

It's there to clarify what sorts of things *are* atomic inlines, so the term isn't just floating in the void. ^_^
