### ISSUE TITLE
[css-pseudo] ::marker should inherit style from originating element

### ISSUE THREAD

**Issue by dbates-wk** [w3c/csswg-drafts#1646]
We should add wording to section [List Markers: the ::marker pseudo-element](https://drafts.csswg.org/css-pseudo-4/#marker-pseudo) that ::marker inherits its style from its originating element (the list item). This is the behavior that all modern browsers implement as far as I can tell and is consistent with the second paragraph of section [Lists in CSS 2.1](https://www.w3.org/TR/CSS2/generate.html#lists).

**Comment by dbates-wk** [comment]
@Loirooriol @tabatkins @fantasai

**Comment by tabatkins** [comment]
I think we can just define that all tree-abiding pseudo-elements inherit from their originating element.  At least so far, they're all children of the originating element; we'd have to amend that language if we ever produced something otherwise.

**Comment by dbates-wk** [comment]
> I think we can just define that all tree-abiding pseudo-elements inherit from their originating element. At least so far, they're all children of the originating element; we'd have to amend that language if we ever produced something otherwise.

Sounds good to me. It looks like we could just move the last sentence of the first paragraph in section [Generated Content Pseudo-elements: ::before and ::after](https://drafts.csswg.org/css-pseudo/#generated-content) to the end of the paragraph in section [Tree-Abiding Pseudo-elements](https://drafts.csswg.org/css-pseudo/#treelike) such that it reads:

[[
4. Tree-Abiding Pseudo-elements

These pseudo-elements always fit within the box tree. They inherit any inheritable properties from their originating element; non-inheritable properties take their initial values as usual.

4.1. Generated Content Pseudo-elements: ::before and ::after

When their computed content value is not none, these pseudo-elements generate boxes as if they were immediate children of their originating element, and can be styled exactly like any normal document-sourced element in the document tree.

::before
Represents a styleable child pseudo-element immediately before the originating element’s actual content.
....
]]
