### ISSUE TITLE
[css-values] OK to have fragment-only URLs always refer to the host document?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#165]
I just wrote <https://drafts.csswg.org/css-values/#local-urls> to discharge the resolution we made at the SF f2f, and while writing it I ran into one bit that we hadn't actually discussed: what to do about fragment-only URLs *in an external stylesheet*.  (The discussion we had at the f2f was just about URLs that would normally resolve to an element in the document, which implies the CSS is inline.)

I went ahead and defined that fragment-only URLs *always* refer to the host document, because it seems useful for SVG, and because CSS documents have no fragment semantics and don't look like they ever will.  Is this ok?

**Comment by fantasai** [comment]
This was resolved today https://lists.w3.org/Archives/Public/www-style/2016Jun/0026.html and edited into the spec accordingly.
