### ISSUE TITLE
Merge the rest of fonts-3 into fonts-4

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1653]
https://drafts.csswg.org/css-fonts-4/ describes a font-feature-settings property, but not a descriptor.  https://drafts.csswg.org/css-fonts-3/ describes both.  Was dropping the descriptor a mistake?  (If not, it seems like it should be listed in an explicit changes section... but I wouldn't be happy about that change, since as it seems like it should be a descriptor for the reasons I described in #1652.)

**Comment by dbaron** [comment]
See the [relevant part of fonts 3](https://drafts.csswg.org/css-fonts/#font-rend-desc).  Some other bits might be missing.

**Comment by litherum** [comment]
The draft is incomplete. I'm still in the process of moving pieces of 3 to 4.

**Comment by litherum** [comment]
Generalizing this to fit the rest of fonts-3.

**Comment by svgeesus** [comment]
@dbaron parts of Fonts 4 are still a delta spec. Typically there is an inline issue noting where content needs to be migrated over from Fonts 3. Previously we were reluctant to move content over that could still be changing, as edits would then need to be kept in sync over the two levels. That is less of an issue now that Fonts 3 is headed for updated CR and (hopefully fairly soon) Proposed Rec. Also, Fonts 3 is the old `.src.html` format while Fonts 4 is `bikeshed`, which hindered copying content over.
The intent is that Fonts 4 becomes a true superset of Fonts 3.

**Comment by dbaron** [comment]
So I think either:
* it should be much clearer about where parts still need to be copied, or
* it should have a big "not ready for implementation" warning

Otherwise implementors will look at it, be confused, and potentially even remove features from implementations.

(I think the thing that led me to file this issue was a Gecko implementor being confused.)

**Comment by dbaron** [comment]
(I think it would probably help if the notices of things needed to be copied used the names of the properties/descriptors that need copying, so that they're found through textual search of the spec.)

That said, it looks like the particular thing I filed the issue about *is* now in fonts 4.

**Comment by svgeesus** [comment]
I would strongly prefer to avoid the 'not ready for implementation' warning since all the major browsers are implementing variable fonts and color font support from this Level 4 specification.

I'm happy for there to be clearer and more easily searched for descriptions of the missing parts

**Comment by litherum** [comment]
I think there's a third option: I just do the merging soon

**Comment by xfq** [comment]
fonts-3 is published as a REC. Perhaps we can merge the rest of fonts-3 into fonts-4 now?

**Comment by svgeesus** [comment]
Yes, it is just a question of setting the time aside to do that. It is on my to-do pile.
