### ISSUE TITLE
[css-syntax] Reason for limited whitespace definition?

### ISSUE THREAD

**Issue by RByers** [w3c/csswg-drafts#1654]
[css-syntax defines whitespace](https://drafts.csswg.org/css-syntax/#whitespace) to include:
```
U+000A LINE FEED
U+000D CARRIAGE RETURN
U+000C FORM FEED
U+0009 CHARACTER TABULATION
U+0020 SPACE
```
Why not `U+00A0 NO-BREAK SPACE` or other [Unicode WS characters](https://en.wikipedia.org/wiki/Whitespace_character#Unicode)?

In [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=748966#c2) a developer complained that someone found it confusing that what appeared to him like a space in his editor caused his CSS property to be ignored.

**Comment by Lewiscowles1986** [comment]
I'd like to add to this, that a confusion I believe could be common for lay-web-users and troubleshooters would be that characters like 

`U+00A0` [no breaking space](http://www.fileformat.info/info/unicode/char/00a0/index.htm) when combined with `U+00C2` (preceding) following `U+0020` render as-if two single space characters. The only way to visualise this as-is, via a raw-byte representation.

[see line 140](https://pastebin.com/uWSWZitt) or 
 [here direct](https://github.com/RByers/rbyers.github.io/blob/f46484f36e72a17ed956bf6f5b2031a6addde3b8/sb/css-nbsp.html#L5)

**Comment by tabatkins** [comment]
CSS's definition of whitespace matches HTML's definition.  Both are smaller than the rather expansive definition of whitespace that JS allows; they both are strictly limited to the ASCII range.  (JS's definition means tying to a particular Unicode revision, or accepting that the definition of whitespace can change over time. Neither are particularly good, and Unicode's current definition of "whitespace" includes some surprising characters, like the [Ogham space mark](http://www.fileformat.info/info/unicode/char/1680/index.htm), which doesn't *look* like whitespace.

**Comment by RByers** [comment]
Makes sense, thanks for the details @tabatkins!
