### ISSUE TITLE
[css-cascade] Change the precedence order of cascading origins to match reality better?

### ISSUE THREAD

**Issue by SelenIT** [w3c/csswg-drafts#1658]
Currently, the CSS Cascade spec states that animation declarations [shouldn't override](https://drafts.csswg.org/css-cascade/#cascade-origin) important author declarations. In fact, they do in all browsers except Firefox. There are some articles that appear to describe this overriding as a standard behavior ([1](https://escss.blogspot.com/2015/04/animaciones-transiciones-contra-important.html), [2](https://paulbakaus.com/2017/07/27/more-important-than-important/)), so devs may start to believe that this is how it should be (e.g. [3](https://twitter.com/iamvdo/status/890862651324104704)). The [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=552085) about this has been reported in 2015, but still there seems to be no visible intent to fix it. Unfortunately I have no data if the corresponding bugs were reported to Safari and Edge.

Wouldn't it be easier to change the behavior of Firefox than to persuade all other browser vendors to change their behavior according to the current spec? Wouldn't it make sense to change the spec to match the reality of the majority of the browsers?

**Comment by emilio** [comment]
Well, chrome (probably WK too?) really has more bugs wrt animations, that really go into the same bucket of "you should consider also which rules are in the other levels of the cascade before animating, not just the existing computed style"...

```html
<!doctype html>
<style>
@keyframes bounce {
  from { font-size: 10px; }
  to { font-size: 40px; }
}

div {
  width: 10em;
  height: 10em;
  background: red;
  animation: bounce infinite 5s ease;
}
</style>
<div></div>
```

**Comment by tabatkins** [comment]
Yeah, Chrome considers its current behavior a bug, actually.  I'd prefer to keep the spec as-is for now.

**Comment by SelenIT** [comment]
Well, if Chrome team agrees that it's a bug, I'd ask to close this issue. But... can't the CSSWG help prioritize these animation-related bugs for Chrome team and get them fixed eventually? :)
