### ISSUE TITLE
[css-grid] Is it possible to have different grid column gaps for different rows?

### ISSUE THREAD

**Issue by praveenpuglia** [w3c/csswg-drafts#1661]
The question pretty much sums it up. Currently, there's no way we can have a single grid container with multiple rows and apply different grid column gaps between cells. 

Right now, they way I do it is wrap the elements in another grid container and define the new grid-column-gap there.

I am not sure of possible breaks it might bring into the system but would love to have inputs on it.

**Comment by rachelandrew** [comment]
That wouldn't be a grid, it sounds like flexbox would be the solution to that problem. Hopefully at some point we will get a flex-gap similar to grid-gap which would mean you could control the gaps between flex items better.

**Comment by praveenpuglia** [comment]
More thoughts - I now think that it's best we don't have it because that might push us developers to go really flat and not maintain dom hierarchy / semantics using grid as excuse.

**Comment by SebastianZ** [comment]
This looks like a duplicate of #1659.

Sebastian

**Comment by praveenpuglia** [comment]
Yeah! That issue will close this one if repetition of a grid-gap pattern is allowed on both axis. Closing this.
