### ISSUE TITLE
[css-fonts] issues with font-family descriptor in @font-palette-values rule

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#1669]
The `@font-palette-values` rule has a `font-family` descriptor[1] that is supposed to associate it with a particular font ("This palette will only ever be applied to the font with this name").

However, this seems problematic to me, as `font-family` does not identify "a particular font" but a family that may contain an arbitrary number of faces; and (thanks to the magic of `unicode-range`) any given face might refer to an arbitrary number of font resources. Each of these may have its own palettes.

Therefore, when the `base-palette` descriptor[2] "specifies a palette in the font...", it is (AFAICS) not fully specified which font resource (and therefore which palette) is meant.

[1] https://www.w3.org/TR/2017/WD-css-fonts-4-20170711/#font-family-2-desc
[2] https://www.w3.org/TR/2017/WD-css-fonts-4-20170711/#base-palette-desc

**Comment by litherum** [comment]
Because the other font selection properties (`font-weight`, `font-style`, `font-stretch`) won't change during font fallback for a particular element, `font-family` is sufficient to be applied differently to different fonts during fallback on a particular element. `@font-palette-values` is applied independently to each element, so it seems well-defined to me.

Am I misunderstanding you?

**Comment by jfkthame** [comment]
Hmm, OK; I think I hadn't fully grasped the implications of `@font-palette-values` being "applied independently to each element".

That still leaves the question of a single face (family/weight/style/stretch combination) that is backed by multiple font resources (via `@unicode-range`), where each resource has its own independent palettes. Does `@font-palette-values` in fact need to be resolved independently for each character [cluster] of each element, after per-character fallback has been performed?

I'm concerned at how complex and perhaps expensive this is sounding, but admittedly that's without having attempted any kind of implementation.

**Comment by svgeesus** [comment]
> That still leaves the question of a single face (family/weight/style/stretch combination) that is backed by multiple font resources (via @unicode-range), where each resource has its own independent palettes.

Hmm, good point. Compound fonts would be problematic with the current approach.

**Comment by litherum** [comment]
> Does `@font-palette-values` in fact need to be resolved independently for each character [cluster] of each element, after per-character fallback has been performed?

Right now, yes. This is how `@font-feature-values` already works. In our implementation (which doesn't exist yet), I don't expect this to be more difficult than `@font-feature-values`.
