### ISSUE TITLE
[css-pseudo] purpose of focus-within?

### ISSUE THREAD

**Issue by jimmywarting** [w3c/csswg-drafts#1670]
Just discovered [focus-within](https://drafts.csswg.org/selectors-4/#the-focus-within-pseudo).
what dose it solve that `:has()` pseudo class can't fix?

eg: 
```css
form:has(:focus) { }
form:focus-within { }
```

I mostly think it's seems unnecessary to have focus-within, just adds more code, a yet another way of doing things

**Comment by Loirooriol** [comment]
`:has` is not in the [dynamic profile](https://drafts.csswg.org/selectors-4/#dynamic-profile) because it's too expensive. This means you can only use it in `querySelector` or similar JS APIs, but not in CSS stylesheets. `:focus-within` can be used in both profiles.
