### ISSUE TITLE
[css-fonts-4] Computed value for shorthand font: should describe serialization for font-variant-css21 and font-stretch-css3

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#1671]
The [font shorthand](https://drafts.csswg.org/css-fonts-4/#font-prop) describes the computed value as:

> see individual properties

However, the serialization of the computed value for `font-variant-css21` and more importantly `font-stretch-css3` does not fit under this description. Can we clarify that serialization of a computed style value for the font shorthand fails if the values do not match any of the keyword values described in those two compatibility longhands? And if the values do match those backwards-compatibility longhands then they are serialized as keywords, not as a percentage in the case of font-stretch-css3?

**Comment by upsuper** [comment]
I believe the "computed value" field there is unrelated to how the computed value is serialized.

Actually, shorthands in general don't have computed value themselves at all. They are split into their subproperties during parsing.

**Comment by drott** [comment]
Yes. What I suggest to clarify is that a `getComputedStyle(someElement).font` serialization cannot be produced in case `font-stretch` contains a value that does not fit any of the keyword values of `font-stretch-css3`. If it does match one of those keywords in its value, serialize the value of font-stretch as keywords, not as percentages (as which the computed value of font-stretch is to be serialized regularly).

**Comment by upsuper** [comment]
I don't think there is even consensus whether `font` should be serialized from `getComputedStyle`. I don't think Gecko does that. In general, Gecko doesn't serialize shorthands for resolved value at all, except for those which were a longhand.

**Comment by litherum** [comment]
So you're just saying that, if `getComputedStyle(someElement).font` produces a result, it should be round-trippable? If so, I agree.

@upsuper We should probably open a separate issue asking the general case if you ask getComputeStyle() for a shorthand, and not discuss that here.

**Comment by drott** [comment]
> If getComputedStyle(someElement).font produces a result, it should be round-trippable.

Yes, and it would help if cases for when it cannot produce a result would be defined, especially with regards to `font-stretch-css3` and `font-variant-css21`.

**Comment by litherum** [comment]
It’s defined (for all shorthands) to be empty if any of the subproperties have values that are not accepted by the shorthand.

**Comment by drott** [comment]
Right, the shorthand only accepts the keywords from `font-stretch-css3` but looking at the computed value of font-stretch, it explains it should be serialized to `Computed value: | numeric weight value (see description)`. This is the contradiction I would like to see resolved. What do you think about clarifying the serialization as keyword in the shorthand section?

**Comment by litherum** [comment]
Oh, you're saying that, if we follow specs as they stand today to the letter, it would be impossible to have a non-empty computed value. Is that right?

**Comment by litherum** [comment]
Oh, wow, it's really bad that the `font-stretch` property's computed style says "weight" 😢

**Comment by drott** [comment]
> Oh, you're saying that, if we follow specs as they stand today to the letter, it would be impossible to have a non-empty computed value. Is that right?

Yes, even if it said: numeric stretch value as <percentage>. We would serialize to a percentage, which would match none of the `font-stretch-css3` keywords.

**Comment by drott** [comment]
Thanks for the update. Are you sure this is `as specified` instead of something like `numeric stretch value as percentage`? What about the computed value during an animation?

**Comment by litherum** [comment]
Why do you think it should be a percentage? Seems to me that `font-stretch: expanded` should have a computed style of `expanded`.

**Comment by litherum** [comment]
Actually, now that I think about it, we may actually need to preserve existing behavior. Today, if you style something with `font-style: expanded`, the computed style of the `font-style` property is `expanded` (and isn't a number). This behavior is what WebKit does today. Depending on web compatibility, it may be required.

**Comment by drott** [comment]
I understand the compatibility concerns, but I see some consistency issues as well. What about the case when you animate from say `condensed` to `extra-expanded` and query for the computed value during the animation? Would you prefer a situation in which the computed value toggles between percentage and keywords? E.g.: ...123%, 124%, expanded, 126%... 

Otherwise I agree on the part where an extra bool should not be necessary to detect the keyword-matching values.

**Comment by litherum** [comment]
> Would you prefer a situation in which the computed value toggles between percentage and keywords?

I think yes, because compatibility is more important than consistency.

**Comment by drott** [comment]
Just to clarify: How does WebKit serialize the computed style value of font-weight a) in the font: shorthand, b) for the font-weight property: Does it serialize font weight `400` and `700` as `normal` and `bold` respectively, or as `400` and `700` numbers?

**Comment by litherum** [comment]
We will always use keywords if possible.

**Comment by fantasai** [comment]
Current proposal (in the spec) is to keep the computed value of `font-stretch` as a percentage, but require percentages matching a keyword to be serialized out as that keyword for the purpose of `getComputedStyle()`. Agenda+ to discuss that.

(I didn't understand the issue about the `small-caps` keyword. Afaik, it's still just a keyword?)

**Comment by astearns** [comment]
@fantasai should this go on the weekly agenda, since we didn't get to it at the F2F meeting?

**Comment by atanassov** [comment]
@astearns yes, pulling to this week's call

**Comment by svgeesus** [comment]
@litherum said:

> We should probably open a separate issue to investigate the general case for what happens if you ask getComputeStyle() for a shorthand

Agreed, and that is https://github.com/w3c/csswg-drafts/issues/2529  **[cssom] getComputedStyle and shorthands.**

**Comment by litherum** [comment]
I'm happy with @fantasai's suggestion about the computed value of `font-stretch` being a percentage, but `getComputedStyle()` returns strings for certain percentage values.

**Comment by svgeesus** [comment]
computed value: percentage

*usually

**Comment by drott** [comment]
Thanks, I am happy with this resolution.

**Comment by svgeesus** [comment]
Just checking this is resolved. I see in the spec:

> For compatibility with [CSS-FONTS-3], getComputedStyle() serializes values that correspond to one of the font-stretch keywords as that keyword (instead of as a <percentage>).

@litherum are further edits needed or can this be closed?

**Comment by svgeesus** [comment]
This looks to have been resolved, as the current spec text is

```html
{{getComputedStyle()}} always serializes its value as a <<percentage>>, 
regardless of how the value was specified by the author, or whether
 or not a keyword happens to map to the value.
```
