### ISSUE TITLE
[css-display] Must a non-box-generated containing block be the initial containing block?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1672]
The [containing block](https://drafts.csswg.org/css-display-3/#containing-block) definition says

> a containing block is not a box (it is a rectangle), however it is often derived from the dimensions of a box. If properties of a containing block are referenced, they reference the values on the box that generated the containing block. (For the initial containing block, the values are taken from the root element.)

But what if something references a property of a containing block that has not been generated by any box, and is not the initial containing block?

According to CSS 2 and CSS Position, I think this case is not possible, but then you should say so. Otherwise, if it's possible, define what should happen.

**Comment by tabatkins** [comment]
Other than the ICB, containing blocks are always generated by a box.

**Comment by Loirooriol** [comment]
@tabatkins This has not been clarified in CSS Display, and one can't trust CSS Position because it's not maintained. So this issue is not fixed.

**Comment by tabatkins** [comment]
As far as I know, nothing needed to be clarified - other than the ICB, every containing block *is* generated by a box, so any question about CBs that aren't generated by boxes (other than the ICB) is moot.

But yeah, one can't trust Position.

**Comment by Loirooriol** [comment]
> other than the ICB, every containing block *is* generated by a box

It's this statement what I think is not clear. It would be useful to include it in the definition.

**Comment by fantasai** [comment]
I'm not sure we need to preclude the possibility in the future--though I don't see us doing it in the future, I don't think we gain anything by locking down the definition here, either. So I think it's fine to leave the definition as-is, and if we end up with more cases like the ICB, define how they work when we create them.
