### ISSUE TITLE
[css-fonts] Clarify font-display descriptor value names

### ISSUE THREAD

**Issue by jetvillegas** [w3c/csswg-drafts#1676]
An issue is noted in the spec re: the allowed values for font-display:
https://drafts.csswg.org/css-fonts-4/#issue-01b739ba

Blink has shipped with the names per spec. Gecko plans to do the same. Strike the spec issue as resolved? /cc: @tabatkins

**Comment by litherum** [comment]
Why don't we resolve the issue once Gecko ships, to give people time to comment?

**Comment by jetvillegas** [comment]
We could do that, though our ability to change syntax is greatly reduced once multiple browsers ship.
