### ISSUE TITLE
[flexbox] Confusing sentence in a note about order and navigation

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1677]
The following sentence (the last one in [section 5.4.1. Reordering and Accessibility](https://drafts.csswg.org/css-flexbox-1/#order-accessibility) in flexbox) is problematic:

> However a UA that uses order in determining sequential navigation, but does not otherwise account for spatial relationships among elements (as expressed by the various layout features of CSS including and not limited to flex layout), is non-conforming.

It looks like it is trying to introduce a conformance requirement in a note, which is not OK.

What is is actually trying to do is to illustrate a way than an implementation could fail to honor the normative conformance requirement already introduced by the second sentence of the section:
> Likewise, order does not affect the default traversal order of sequential navigation modes (such as cycling through links, see e.g. tabindex [HTML5]).

**Comment by astearns** [comment]
Since the conformance requirement already exists, I'm not sure the example in the note needs to reinforce it. What if we changed the sentence in the note to something like:

> But order is not the only (or even the first) CSS property that would need to be considered for a spatial navigation feature. A well-implemented spatial navigation feature would need to consider all the layout features of CSS that modify spatial relationships.

**Comment by fantasai** [comment]
Works for me. Did you mean first as in "earliest defined" or first as in "primary"?

**Comment by astearns** [comment]
I meant primary, but I suppose it works either way.

**Comment by fantasai** [comment]
In that case I'll s/first/primary/. :)

**Comment by tantek** [comment]
Alan's proposed changed sentence is an improvement, with either first/primary (editor discretion). LGTM.
