### ISSUE TITLE
[css-flexbox-1] Reordering and Accessibility note language

### ISSUE THREAD

**Issue by atanassov** [w3c/csswg-drafts#1678]
The language in the Note at the end of section 5.4.1 uses the words "non-conforming". We shouldn't be using normative language in notes, thus, this requires rewording. 

> However a UA that uses order in determining sequential navigation, but does not otherwise account for spatial relationships among elements (as expressed by the various layout features of CSS including and not limited to flex layout), is non-conforming.

https://drafts.csswg.org/css-flexbox-1/#order-accessibility

**Comment by frivoal** [comment]
closing as dup of #1677
