### ISSUE TITLE
[css-flexbox] Definiteness of flex items' main size depend on flex-basis's definiteness

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#1679]
From [email](https://lists.w3.org/Archives/Public/www-style/2017Jan/0068.html):

>I've been looking through a few non-interoperable parts of flexbox again recently, and have run into <https://codepen.io/gsnedders/pen/WRZQrx?editors=1100#0> again. Notably, Edge and Firefox both pass this test case, and Chrome and Safari fail. Except, as it turns out, the behaviour in Chrome and Safari is right. (Actually, the behaviour in Safari is wrong, it just happens to be right for that test case, but let's never mind details!)
>
> I can't work out is where the behaviour in Edge and Firefox comes from, though maybe it is down to interpretation of the spec prior to <https://github.com/w3c/csswg-drafts/commit/2f0ad00527a726c92a6567b210696142e8c2b722> and whether you need to measure content in this case? Though that doesn't seem true? I haven't dug too deep into this though!
>
> That said, what I'm really here to ask is when and why we decided to go with the behaviour the spec and Chrome now have and hence against the Edge/Firefox behaviour. This seems to be something that trips web authors up a fair bit (there's *lots* of bugs in the Chromium bug tracker about this!). Something to point people at as to, "hey, here's why the spec does this nowadays, and why we think this is better behaviour", ideally—though obviously a blog post summarising it may well be needed!

Note that since this was written, Safari's behaviour is now genuinely right, because it now [shares its flexbox implementation with Chrome](https://bugs.webkit.org/show_bug.cgi?id=168657).

**Comment by gsnedders** [comment]
https://codepen.io/gsnedders/pen/GvjRNN is one of the original cases that I started having problems with; unlike the codepen linked above it doesn't have the flex container having a definite size.

**Comment by gsnedders** [comment]
The conclusion at the F2F was to get opinions from implementors: @dholbert @FremyCompany @cbiesinger.

**Comment by gsnedders** [comment]
@gregwhitworth asked me to see what happened with Grid in this case, so I threw together https://codepen.io/gsnedders/pen/ZJpYBY (this is essentially a minimally different example, just using grid); Firefox, Chrome, and Safari do what I expect there. (Up-to-date Edge is still downloading as I write this.)

**Comment by gsnedders** [comment]
Microsoft EdgeHTML 16.16257 passes both flex and grid variants.

So we have interop on grid doing what most authors seem to expect; we have Firefox and Edge doing what authors expect with flexbox and Chrome and Safari not.

**Comment by gregwhitworth** [comment]
Yeah, I would strongly oppose changing our implementation to the one that authors expect, especially since the other engines are doing this in the grid case and we've tried, in many areas to keep flex/grid consistent. So if this works in Grid, and two impl can do it - then I think that Blink/Webkit should make it work for author ease and platform consistency.

**Comment by gsnedders** [comment]
> Yeah, I would strongly oppose changing our implementation to the one that authors expect, especially since the other engines are doing this in the grid case and we've tried, in many areas to keep flex/grid consistent. 

You mean away from the one that authors expect, I assume? Edge does what authors expect today.

**Comment by gregwhitworth** [comment]
@gsnedders yes you're right, I updated the comment so people don't get confused.

**Comment by tabatkins** [comment]
Issue here is that Grid's behavior comes from the fact that, while there may be some definite/indefinite shenanigans while figuring out how large the tracks are, once you do so, the tracks (and thus, the grid areas) have a definite size in px.  If you then stretch the grid item into that space, they're considered definite as well, so child %s resolve.

Flexbox doesn't have this two-tier notion. There's nothing in the spec currently to support the flex item's main size being treated as definite in this case; it's auto-height, and none of the special cases in [Flexbox/9.8](https://drafts.csswg.org/css-flexbox/#definite-sizes) apply.  If you or a Firefox dev can tell us how you're getting it to have a definite size, that would be great. ^_^

**Comment by dholbert** [comment]
Quoting @tabatkins :
<blockquote>
There's nothing in the spec currently to support the flex item's main size being treated as definite in this case; it's auto-height, and none of the special cases in Flexbox/9.8 apply. If you or a Firefox dev can tell us how you're getting it to have a definite size, that would be great. ^_^
</blockquote>
In Firefox, we simply haven't gotten to implementing this chunk of spec text (making main-size definiteness depend on flex-basis's definiteness).  [bug 1092007](https://bugzilla.mozilla.org/show_bug.cgi?id=1092007) is filed on that, though.

I tend to think it's a change we should make.

**Comment by gregwhitworth** [comment]
We also haven't updated our implementation since 2015 for this section of spec text. By simply applying a definite `flex-basis` and a `height` of 0 in the demo above, this makes Chrome interoperable with Firefox and Edge. This leads me to wonder if the performance argument (what was brought up [~3 years](https://lists.w3.org/Archives/Public/www-style/2014Jul/0010.html) ago) is worth the author confusion here, and while I understand why inline & block direction are different - currently FF/Edge react the same for the author in either `row` or `column` directions which further makes me desire the implementations of FF/Edge. I think we may have done a bit of pre-optimization when discussing this in 2014, I truly think we should remove the constraints for 2 under section `9.8` as that's what we're doing.

**Comment by fantasai** [comment]
Edits checked in. @gregwhitworth @gsnedders would you mind reviewing the edits to make sure that's what you intended?

**Comment by gregwhitworth** [comment]
Yep, just removal of the definite flex basis - looks good.

**Comment by gsnedders** [comment]
To check: in https://codepen.io/gsnedders/pen/GvjRNN `.flex-container` is definite, right (given the `height: 0` makes it so)? If so, then I'm okay.

**Comment by fantasai** [comment]
@gsnedders Yes, because both the `height` and the `min-height` are definite in this example. (`height` is fixed, and `min-height` is resolved against a definite height).

**Comment by astearns** [comment]
Reopening for testcase need.

**Comment by gregwhitworth** [comment]
@fantasai @gsnedders I created a testcase for this - please review at earliest convenience.

**Comment by gregwhitworth** [comment]
The test for this one has been merged, so I'll be removing the label for tests.
