### ISSUE TITLE
[css-counter-styles] Invalid @counter-style should just not define a counter style, not be ignored

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1682]
In <https://github.com/w3c/csswg-drafts/issues/1133>, we just decided that an `@font-face` rule without its minimum required descriptors should be treated as *valid* (so it shows up in the OM), but just doesn't define a font face for the document.

We should be consistent in applying this decision, which means that an `@counter-style` rule without its minimum required descriptors (`system` and either `symbols` or `additive-symbols`) is valid, but does not create a counter style for the document.

**Comment by upsuper** [comment]
Hmmm... OK... If @dbaron doesn't file a bug, I'll do so tomorrow. (Just to avoid filing duplicate bugs like this time :)

**Comment by upsuper** [comment]
Also, to make it clear, I suppose `@counter-style` rules which use an invalid name (`none`, `decimal`, or `disc`) are still invalid, and still shouldn't show up in the OM. Is that correct?

**Comment by upsuper** [comment]
(FWIW, re-purposed an old [Gecko bug 1299097](https://bugzilla.mozilla.org/show_bug.cgi?id=1299097) for this change.)

**Comment by tabatkins** [comment]
I can go either way on that.  I think I'd prefer to treat it as invalid and drop it.

**Comment by tabatkins** [comment]
@upsuper re: invalid names

Yeah, I intend that to actually invalidate the rule, tho I could go either way if necessary.

**Comment by xiaochengh** [comment]
Hi,

The edit work seems incomplete. The spec still gives a number of scenarios that the @counter-style rule is invalid. There are also some inconsistencies, for example:

> If the system is `cyclic`, the `symbols` descriptor must contain at least one counter symbol, or else the @counter-style rule is invalid.

> The @counter-style rule must have a valid `symbols` descriptor ... otherwise, the @counter-style does not define a counter style (but is still a valid at-rule).

Should I understand the intention as: as long as the at-rule has a correct syntax, then it's valid and appear in OM; it defines a counter style only when the required descriptors have correct values.

In other words, `@counter-style inherit {}` is invalid and shouldn't be in OM; while `@counter-style foo {}` is valid but doesn't not define a counter style.
