### ISSUE TITLE
[css-tables-3] Editorial: "min-content width" is unlinked and has a weird definition

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#1687]
https://drafts.csswg.org/css-tables-3/#min-content-guess says
> Then, valid sizing methods are to be assigned to the columns by sizing type, yielding the following guesses:
> 1. The min-content guess is the set of column width assignments where each column is assigned its **min-content width**

"min-content width" isn't linked. There is a 
min-content-width definition at https://drafts.csswg.org/css-tables-3/#min-content-width but it doesn't seem to fit: 

> the intermediate min-content width for span N, where N is the number of columns in the table

It doesn't seem to fit because that definition refers to the whole table, not just to one column. Which is weird, because it's in the "Column Measures" section.

**Comment by fantasai** [comment]
Maybe referencing https://drafts.csswg.org/css-sizing-3/ ?

**Comment by FremyCompany** [comment]
I clarified the spec as I had mentioned in the email thread. 
The "min-content width for span N, whre N is the number of columns in the table" is a per-column measure (the value of N just reflects that you have to start by taking into account only cells that do not span first, then cells that span only two columns, etc.. until N)

This naming was inherited from a previous spec and was unclear I'll admit. I changed it to "min-content width of a column based on cells that span up to N columns"
