### ISSUE TITLE
[css-tables-3] Editorial: clarification for "Columns whose size is computed as a sum..."

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#1688]
https://drafts.csswg.org/css-tables-3/#width-distribution-in-fixed-mode says
> Columns whose size is computed as a sum of a percentage and a pixel length must be sized as if they counted as two columns, one with the pixel value, the other with the percentage value.

What does this mean and how is it different from auto width distribution? Is "computed as a sum" referring to columns that have width specified as calc()?

**Comment by FremyCompany** [comment]
This was indeed a text added after we resolved that ```width: calc(50% + 50px)``` should work in fixed mode on columns.

**Comment by davidsgrogan** [comment]
Are you sure that was the resolution? Maybe I'm looking in the wrong place but I found these:
https://github.com/w3c/csswg-drafts/issues/94
https://log.csswg.org/irc.w3.org/css/2016-07-27/#e708168

Then the end of https://drafts.csswg.org/css-values/#calc-computed-value says mix-unit calc expressions in table parts may be treated as auto.

I guess the part of the spec I quoted up top is defining the behavior for implementations that don't treat them as auto.

And from the sizing-type definition in https://drafts.csswg.org/css-tables-3/#width-distribution-algorithm, I see that calc values would fall under the auto-column definition, so maybe that answers my question about how is this different than auto width distribution: auto tables treat calc widths as auto and fixed tables can treat them as auto or resolve them against the table width?

**Comment by FremyCompany** [comment]
Well, no, you cannot resolve percentage away because they do weird things when the table is constrained, even in fixed mode.

I agree that the spec text here does not map to what the resolution says, I'll maybe remove it (or, rather, mention that a browser MAY decide to interpret calc that way, but are not required to do so; if they don't they are however required to treat them as auto like in non-fixed table layout mode)

**Comment by FremyCompany** [comment]
A browser supporting the calc would display the two tables of https://wptest.center/#/q1juv4 the same (well, maybe with a 1px difference due to the missing border)

**Comment by davidsgrogan** [comment]
I think the last rule in https://wptest.center/#/q1juv4 should be td:nth-child(3) instead of td:nth-child(2). With that, Chrome/FF/Edge display the tables the same. But I think this adaptation shows what you mean https://jsfiddle.net/dgrogan/uk4h5u8p/
(differences are nth-child(3) and s/100px/20px/)
