### ISSUE TITLE
[css-tables-3] Editorial: Explanation needed for width distribution figure

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#1689]
I don't understand the schema diagram (figure 3) from https://drafts.csswg.org/css-tables-3/#width-distribution-algorithm

Maybe describe what the red and green arrows mean, and/or what the colors of the boxes represent (red, yellow, orange, green, blue) (red means needed to shrink from the previous step?), and/or what the double-ended table width arrow colors mean (black, red, green) and/or what the up-and-to-the-right double arrows mean in the text.

**Comment by FremyCompany** [comment]
Good point. I'll add a legend to the spec :)

> each drawing represent a way of sizing the columns
> the four cases in the left are the sizing guesses described above in the spec: min-content, min-content percentage, min-content-specified, and max-content
> the cases on the right are interpolations required for sizes that do not match exactly one of the four guesses

> green arrows is the direction you should take if you have extra space to distribute after applying the current method
> red arrows is the direction you should take if you have distributed too much space by applying the current method

> each type of column (auto, px, %) has its own color (yellow, blue, orange).
> in an interpolation: columns that get shrinked down from previous guess will be painted red
> in an interpolation: columns that get expanded from previous case will be painted green
