### ISSUE TITLE
[css-grid][css-multicol][css-flexbox][css-tables] Proposal for Various Gap Issues

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1696]
We've had some feedback on gaps, the one prompting this discussion being that authors are finding it awkward that the `grid` shorthand resets the gaps, preferring that it does not and that it is treated similar to spacing controls such as grid container padding and grid item margins. (https://github.com/w3c/csswg-drafts/issues/1036)

Unwinding the threads of discussions and resolutions, and discussing with several people at the F2F here, we have the following proposal:

- Disconnect the `grid-gap` properties from the `grid` shorthand, resolving https://github.com/w3c/csswg-drafts/issues/1036
- Undo the [resolution](https://lists.w3.org/Archives/Public/www-style/2015Sep/0093.html) changing `column-gap` and `row-gap` to `grid-column-gap` and `grid-row-gap`.
  - As before that resolution, `column-gap` is shared with multi-col and `normal` computes to zero except on multi-column elements.
- Apply `column-gap` and `row-gap` to flex containers, resolving a strong demand from flexbox users to have this spacing control. (See [Rachel's message to www-style](https://lists.w3.org/Archives/Public/www-style/2016Feb/0333.html) and https://github.com/w3c/csswg-drafts/issues/592 with special note of [erikjung's comment](https://github.com/w3c/csswg-drafts/issues/592#issuecomment-279491532))
- As a clean-up measure, have these properties obsolete `border-spacing` (which inherits, which is weird) by having them defer to `border-spacing` when specified as `normal` and override it otherwise.

**Comment by fantasai** [comment]
Note: We would need to (at least temporarily, possibly permanently) maintain aliases from `grid-*-gap` to the unprefixed properties like we do for `page-break-*`, since grid layouts are deployed already.

**Comment by bdc-stripe** [comment]
I'm very sympathetic to that idea. Nitpick: does that mean we'd only have a shorthand gap property for grid (assuming we keep the aliases) ?

**Comment by rachelandrew** [comment]
I'd be happy with that as long as we have the aliasing and I think authors would be very keen with getting these for flex.

**Comment by atanassov** [comment]
@bdc-stripe, no, the gap shorthand should work for any layout that accepts gaps

**Comment by bdc-stripe** [comment]
@atanassov Ok cool (didn't see a proposal for `gap`).

**Comment by SelenIT** [comment]
@fantasai, does https://github.com/w3c/csswg-drafts/issues/1036#issuecomment-320241018 mean that the last bullet point regarding tables has just been rejected?

**Comment by tabatkins** [comment]
Yes, at least for now (and probably permanently), we're not going to apply row-gap and column-gap to tables.

**Comment by fantasai** [comment]
WG resolution: https://logs.csswg.org/irc.w3.org/css/2017-08-04/#e847329
Proposal has been accepted, minus the tables part because nobody wants to deal with tables.

**Comment by fantasai** [comment]
Edits checked in, closing issue. :) Expect to republish to /TR at the end of the month.

**Comment by yisibl** [comment]
Please start the Flexbox 2 specification as soon as possible.

**Comment by zxti** [comment]
Hello from 2019! Is there a rough ETA for `gap` in flexbox?

**Comment by rachelandrew** [comment]
@zxti gap has been specified for Flexbox. It is part of the Box Alignment specification. https://www.w3.org/TR/css-align-3/#gaps

If you are referring to browser implementation then Firefox has already implemented this. Other browsers have not as yet, but this isn't the place to chase that. The bug for Chrome is for example here https://bugs.chromium.org/p/chromium/issues/detail?id=762679
