### ISSUE TITLE
[css-display] Inlinified 'block ruby' should generate an inline-block wrapper

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1700]
When a `block flow` element is inlinified, it becomes `inline flow-root` (i.e. inline-block) in order to preserve the block container.

Shouldn't the same happen for `block ruby`? If you request your ruby container to be wrapped inside a principal block container (e.g. because you want to use `width` or `height`), shouldn't the block container be preserved (in the form of as inline-block) in case the element is unexpectedly inlinified by some ancestor?

I think so. There should be a `ruby-root` inner display type and, just like `flow` becomes `flow-root` during inlinification, `ruby` should become `ruby-root`.

**Comment by fantasai** [comment]
I don't think there's a use case for this, and letting `block ruby` convert to `inline ruby` is fine. If you want it to be atomic, you probably should be using flexbox, not the inline formatting model.

**Comment by Loirooriol** [comment]
@fantasay More than flexbox I guess I should separate the `block ruby` element into a parent with `display: block` and a child with `display: ruby`. But I don't like adding elements just for styling purposes. This could be an use-case for [`::contents`](https://github.com/w3c/csswg-drafts/issues/2406), though.

```css
.block-ruby { display: block }
.block-ruby::contents { display: ruby }
```
