### ISSUE TITLE
[css-scroll-snap] Consider more specific guidance for scroll-into-view

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1707]
From a discussion about `scrollOptions` in https://github.com/whatwg/html/pull/2787#issuecomment-318849888 ...

> As for the preferred position of the focused element, the [CSS Scroll Snap module](https://www.w3.org/TR/css-scroll-snap/) already defines various parameters for the preferred scroll positions for viewing an element, and imho it is better to re-use these rather than establish a contradictory and less powerful set of arguments in the .focus() API. The `scroll-padding` property already specifies that it applies, and probably `scroll-snap-margin` should as well. The spec currently avoids specifying that focusing operations inherently trigger snapping to the element’s snap position, but it does specify that (even when snapping is off), a #fragmentID-targetted element should snap into position... so if this is desired behavior we can look into defining that behavior as well. In any case, it doesn't seem like this belongs specifically in the JS API, unless for some reason the behavior of an API call needs to differ from that of a user-triggered event.

Possible guidance to consider:
  * Suggesting that scroll-into-view operations consider scroll-snap-margin in addition to scroll-padding
  * Recommending that UAs use the element's snap position if it has one and snapping is on.
  * Allowing UAs to use the suggested snap position, if the element has defined one, even if snapping is off.

**Comment by syj10** [comment]
As described in https://drafts.csswg.org/cssom-view-1/#dom-element-scrollintoview,
users can specify the alignment of ScrollIntoView by ScrollIntoViewOptions or a boolean.
My questions is, if the javaScript calls element.scrollIntoView({block: "start", inline: "start"}), but the element itself defines its snap alignment as "center". Should the snap alignment override SIV alignment, or the SIV alignment override snap alignment?

**Comment by syj10** [comment]
Thanks for the clarification!
Does this also apply to element.scrollTo(x, y) and element.scrollBy(dx, dy)?

Correct me if I'm wrong.
1. If it's a smooth-scroll, the scroller first animates to the input position, then animates to the snap position.
2. If it's an instant-scroll, the scroller directly goes to the snap position.
3. When we call scrollIntoView() without options, it would still use the default start-alignment[1]. And if it defines snap-alignment-end, it would land on the end-alignment after SIV.

[1] https://drafts.csswg.org/cssom-view-1/#enumdef-scrolllogicalposition

**Comment by fantasai** [comment]
I think ideally the UA would calculate the final resting place and animate directly to that. As for scrollIntoView()'s defaults, imho it needs to defer them to scroll-snap.
