### ISSUE TITLE
[css-fonts] The CSSFontFeatureValuesRule interface has only one implementation

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1713]
I wrote a few tests for https://drafts.csswg.org/css-fonts/Fonts.html#om-fontfeaturevalues
Pending review, these are staged at https://www.w3.org/People/chris/fwf/

It looks like only Firefox implements this interface. Chrome, Edge and Safari fail all tests.

This interface should probably be moved from Fonts 3 to Fonts 4. Unless at least one browser steps up to implement in the next month or two?

**Comment by litherum** [comment]
Are you talking about just the OM, or the whole block itself? I [marked](https://github.com/w3c/csswg-drafts/commit/e717903b844e40672d3eb96a9e68687c412c3cda) the at-rule itself at-risk a few months ago.

**Comment by svgeesus** [comment]
I meant the OM, because it seems that has less implementations than the at-rule. If the at-risk was intended to cover both (which seems reasonable, though perhaps t to an outside reviewer) then that should be clarified next time we publish.

**Comment by svgeesus** [comment]
I'm satisfied with the resolution.
This requires edits to both font-3 (to remove) and fonts-4 (to add). As far as I can see, in fonts-3 the feature is marked as at-risk but has not been removed; so this issue should stay open for tracking.
