### ISSUE TITLE
[css-fonts] the font-language-override property has only one implementation

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1714]
https://drafts.csswg.org/css-fonts/Fonts.html#font-language-override-prop

Gecko passes; Chrome, Edge, Safari fails. It looks like this should be moved from Fonts 3 to Fonts 4.

Related: https://github.com/w3c/csswg-drafts/issues/1392 https://github.com/w3c/csswg-drafts/issues/1104

**Comment by svgeesus** [comment]
Satisfied with resolution, still needs edits so leaving open

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/64cb44b49218aed353bee63049d2ea76e16b6c5e
