### ISSUE TITLE
[css-display] Should 'run-in flow-root' blockify to 'block' or 'flow-root'?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1715]
I was drawing a diagram to understand the CSS Display transformations after the F2F resolutions and how a hypothetical `ruby-root` could fit in there.

[![diagram-small](https://user-images.githubusercontent.com/7477678/29187145-001bf1a4-7e0f-11e7-8ccb-fd0846c7e779.png)](https://user-images.githubusercontent.com/7477678/29187009-96422abe-7e0e-11e7-8bdf-1c4dbee2481f.png)

I noticed that it's not clear how `run-in flow-root` should blockify, and you didn't discuss this in the F2F.

It was resolved that `inline flow-root` blockifies to `block flow` because `inline flow-root` is syntactically equivalent to `inline-block`, and `inline-block` must blockify to `block` because of backwards compatibility.

A `run-in flow-root` is basically an inline-block with some special tree munging. So it could make sense to let `run-in flow-root` be consistent with `inline-block` and also blockify to `block flow`.

The other possibility would be to keep it simple and only change the outer display type, i.e. blockify to `block flow-root`.

In practice, the difference should not matter much because I expect blockifications to trigger becoming a formatting context. But it will affect `getComputedStyle`, of course.

I don't have a strong opinion, but maybe I prefer consistency with `inline flow-root`.

**Comment by tabatkins** [comment]
Agenda+ to verify making "run-in flow-root" blockify to "block flow", to match the behavior of "inline flow-root" (aka "inline-block").

**Comment by frivoal** [comment]
+1 to the above change.

Incidentally, the full table make sense to me, and I'd like to use it as a basis to close https://github.com/w3c/csswg-drafts/issues/1457. Following up in that issue.

**Comment by astearns** [comment]
reopening for the agenda+

**Comment by Loirooriol** [comment]
Just for reference, this is the updated table:

![diagram-small2](https://user-images.githubusercontent.com/7477678/38340146-2b961fee-3872-11e8-82b5-f2d893eba466.png)
