### ISSUE TITLE
[css-fonts] font-min-size should win over font-max-size in case of conflict

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1723]
The spec currently says “If the 'font-min-size' property is computed to be larger than the 'font-max-size' property, then the two properties are ignored.”

Ignoring both isn't very user friendly. In case of conflict elsewhere, CSS uses the min, so that's what we should do here.

**Comment by tabatkins** [comment]
:+1: And the reason for CSS making min win by default is that mins are often applied for basic legibility purposes, while maxes are often applied for aesthetic purposes.  The former is more important to preserve than the latter; in particular, when they *clash*, violating legibility doesn't preserve aesthetics at all, while violating aesthetics at least preserves legibility.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/99275cecc401f40287323f6ccd839349f6bc0315
