### ISSUE TITLE
[cssom-view]  Stop using "incumbent settings object"?

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1725]
"Incumbent settings object" is utilized in several places in CSSOM View, although there's a warning in the [HTML Standard](https://html.spec.whatwg.org/multipage/webappapis.html#realms-settings-objects-global-objects):

> Warning! The incumbent and entry concepts should not be used by new specifications, as they are excessively complicated and unintuitive to work with. We are working to remove almost all existing uses from the platform: see [issue #1430](https://github.com/whatwg/html/issues/1430) for incumbent, and [issue #1431](https://github.com/whatwg/html/issues/1431) for entry.

**Comment by domenic** [comment]
I would be very surprised if implementations used incumbent here. It would mean that if you did

```js
<script>
const w = window.open();
w.moveTo(x, y);
</script>
```

it would move the containing window (containing the script element), and not the opened window.

So this is likely a spec bug. It would be great to have someone write tests though, especially to distinguish between current and relevant.
