### ISSUE TITLE
[css-fonts-3] 6.1. Glyph selection and positioning should be marked as informative

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1728]
6.1. Glyph selection and positioning has a couple of statements that look like they might be normative, but all of them are in fact summaries of conformance statements in other sections. For clarity, the tutorial-like section 6.1 should me marked as informative.

**Comment by litherum** [comment]
The whole 6.1 section?

**Comment by svgeesus** [comment]
yes

**Comment by litherum** [comment]
ok

**Comment by svgeesus** [comment]
Satisfied, but leaving open as needs edits

**Comment by svgeesus** [comment]
OK, no longer needs edits, closing
