### ISSUE TITLE
[css-grid] fit-content() vs 'stretch' alignment

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1732]
@rachelandrew and @mrego [found some problems with the spec](https://bugs.chromium.org/p/chromium/issues/detail?id=755994#c2) for `fit-content()` and its interaction with `stretch` content alignment of the tracks:

> So I thought this was a clear issue and I've already a patch for it. But now reading the specs I'm not 100% sure, so let's clarify this before landing the patch.
> The relevant sections of the spec are:
> * 11.8. Stretch auto Tracks (https://drafts.csswg.org/css-grid/#algo-stretch)
>  This step sizes expands tracks that have an auto max track sizing function by dividing any remaining positive, definite free space equally amongst them.
> * fit-content( <length-percentage> ) (https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-fit-content)
>  Represents the formula min(max-content, max(auto, argument)), which is calculated similar to auto (i.e. minmax(auto, max-content)), except that the track size is clamped at argument if it is greater than the auto minimum.
> 
> The max track sizing function for the fit-content() tracks is "max(auto, argument)".
In the case "auto" is the maximum should it be considered an "auto max track sizing function" or not?
> 
> Would be ok to avoid stretching in all cases? Should we stretch any of them?
> 
> IMHO, I believe that we should avoid stretching for fit-content(). That would be simpler to implement too. But I'd love to hear the feedback from Rachel and Tab on the topic. Thanks!

When we wrote the spec for `fit-content()`, the `auto` in the formula was intended as a replacement for the `min-content` argument of the shrink-to-fit formula, as is made clear in the parenthetical “(i.e. minmax(auto, max-content))”. Removing the word `auto` and substituting the parenthetical in its place makes the intended behavior much clearer.

However, there is a remaining question: should that `max-content` argument actually be `auto`, i.e. respond to stretching (which is the only difference between `auto` maximums and `max-content` maximums)? It would still be clamped by the argument as Rachel requests, since once the track hits that limit it should be treated as a fixed-size track:

> For this purpose, ''fit-content()'' tracks are treated as ''max-content'' until they reach the limit specified as the ''fit-content()'' argument, after which they are treated as having a <a>fixed sizing function</a> of that argument.

I'm leaning towards yes, since having `fit-content()` behave exactly like `auto` aside from clamping at its argument seems like a useful and friendly behavior, but other thoughts welcome~

**Comment by mrego** [comment]
If I'm understanding your proposal, you mean that the `fit-content()` tracks will grow up to the `fit-content()` argument.
So for example a track with `fit-content(200px)` if it has a content of `50px`, it'll be stretched to `200px` (if the available space is enough) but not larger than that.

Probably that can make sense from the authors point of view, but it'll make more complex the implementation of the stretch phase of the algorithm.
For example if we have a grid with `1200px` width and these columns: `fit-content(200px) auto fit-content(450px)`. Imagine they've no contents yet so with `justify-content: start` all of them are 0px.
I guess we'd need to do something like this to stretch them:
1) We've `1200px` available so we divide them between the 3 columns: `400px` each.
   1st column can only grow up to `200px`. 2nd and 3rd columns grow to `400px`.
   At this point we've: `200px 400px 400px`.
2) We still have `200px` available, we divide now only between the 2 columns that still can grow: `100px` each.
   2nd column grows to `500px`, but 3rd column can only grow up to `450px`.
   Now we've: `200px 500px 450px`.
3) At the end we still have `50px` available, and only 2nd column can grow (the other two have already reached their limit).
   2nd column grows to `550px`.
   The final result would be `200px 550px 450px`.

Probably we'd need to specify how this will work in [11.8. Stretch auto Tracks](https://drafts.csswg.org/css-grid/#algo-stretch).

BTW, this is an editorial nit, but shouldn't the 11.8 section mention that tracks only stretch if `justify|align-content` is `stretch`. That's somehow mentioned in the [summary of the track sizing algorithm](https://drafts.csswg.org/css-grid/#algo-overview):
> Finally, the grid container is sized using the resulting size of the grid as its content size, and the tracks are aligned within the grid container according to the align-content and justify-content properties.

**Comment by svillar** [comment]
> I'm leaning towards yes, since having fit-content() behave exactly like auto aside from clamping at its argument seems like a useful and friendly behavior, but other thoughts welcome~

That's was my first thought when @mrego told me about the issue. Whoever (now with my implementor hat on) there are edge cases. For example, what about a fit-content(100px) track hosting a 200px item? It'll be sized to 200px, so we have already surpased the limit, would it make sense not to stretch it? I don't know :smile: I guess we need the opinion of the authors here to know what do they expect.

From the implementation POV I think either solution would be fine anyway.

**Comment by javifernandez** [comment]
With this proposal contradicts, if we don't add additional info, what the Alignment spec states about the 'stretch' value:

> If the combined size of the alignment subjects is less than the size of the alignment container, any auto-sized alignment subjects have their size increased equally (not proportionally), while still respecting the constraints imposed by max-height/max-width (or equivalent functionality), so that the combined size exactly fills the alignment container. 

There are different cases:
  1- not possible to use all the available space
  2- tracks grow not equally

**Comment by mrego** [comment]
Could you please re-discuss this topic and make a resolution?
* 23 August you talked about 1 week to check the examples and define the expected behavior.
* 30 August you didn't discuss further.

This is not something big but it's currently an interop issue, so it'd be nice to know what's the expected behavior to update implementations.
Thanks!

**Comment by rachelandrew** [comment]
I've shown `fit-content` now to a few people and asked opinions. People generally expect it not to grow past the clamping, so my opinion is that for author friendliness the value passed in should be a max, and other tracks should stretch.

**Comment by mrego** [comment]
A test has been added as part of the Blink patch to modify the behavior: https://github.com/w3c/web-platform-tests/pull/7436

The test is: https://github.com/w3c/web-platform-tests/blob/master/css/css-grid-1/alignment/grid-fit-content-tracks-dont-stretch-001.html
