### ISSUE TITLE
[css-sizing] definition of "stretch-fit size" is not great

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1733]
The definition of "stretch-fit size" is not great and we should fix it.

**Comment by tabatkins** [comment]
Per @fantasai, invalid, as we cant' figure out what problem she was referring to.

**Comment by tabatkins** [comment]
Nm, we found what was wrong.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/f5f655bc98a8dfce25473ecf563f230fa3bf6d35
