### ISSUE TITLE
[mediaqueries] rename pointer/hover to main-pointer/hover

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#174]
https://drafts.csswg.org/mediaqueries/#mf-interaction

The relationship between pointer/hover and any-pointer/hover is pretty confusing imho. I've been trying to think how to make it more intuitive, but the best I can come up with is just renaming pointer/hover to make it clearer the distinction. :/

**Comment by tabatkins** [comment]
This has been shipping with the current names in Chrome for quite a while, so we'd prefer not to change it.

Also, it's a longer term without, imo, much additional clarification.  It's fairly obvious that the unqualified "pointer" refers to the main pointer when contrasted with "any-pointer" already.

And, establishing a main-* prefix pattern isn't friendly to future cases where we design a feature with the assumption of only one whatever-it's-about, but later realize that some devices can have two or more whatever-it's-about's with different capabilities.  We wouldn't have used main- on the initial one.  (That's what happened with pointer and hover, actually.)

**Comment by frivoal** [comment]
I agree with Tab.

Also, having a short name and a long name tends to encourage people to use the short one if they haven't particularly thought about it, which here is generally the right thing to do, so I'd like to keep that.

**Comment by frivoal** [comment]
@fantasai Your proposal has been rejected, could you please confirm that you can live with that?

**Comment by fantasai** [comment]
I'm okay with that.
