### ISSUE TITLE
[css-multicol] Contradictions about whether zero is allowed for 'column-width'

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#1741]
In May 2011 @dbaron raised [this issue](https://lists.w3.org/Archives/Public/www-style/2011May/0338.html) against multicol:

> [http://dev.w3.org/csswg/css3-multicol/#cw](http://dev.w3.org/csswg/css3-multicol/#cw) seems to give two different answers as to whether zero is a legal value for column-width:
>   _Computed value: the absolute length, zero or larger_
> and then:
>  _Specified values must be greater than 0._

> I feel quite strongly that zero should be allowed, because I'm strongly opposed to CSS having any value range restrictions that require an open range (i.e., one where the endpoints are not allowed).

> I think open ranges are a problem both because:

> (1) They seem likely to lead to interoperability problems if people want to try to get the "minimal value", since rounding may vary between implementations.

> (2) We have multiple features that require clamping values to the allowed range:
> (a) calc()
> (b) interpolation in transitions or animations, when the cubic-bezier() timing function has Y1 or Y2 values outside of the 0-1 range and clamping to an open range does not make sense.  Sensible clamping requires a closed range.

> So I think either '0' needs to be allowed or, if that makes the algorithm nonsensical, the range restriction needs to be changed to start at some other value.

As far as I can tell this wasn't addressed, opening here for further discussion.

**Comment by rachelandrew** [comment]
There is discussion in 2013, raised by @tabatkins regard column widths of 0. See [https://lists.w3.org/Archives/Public/www-style/2013Oct/0416.html](column-width bound (>0) is illegal)

**Comment by tabatkins** [comment]
Yeah, we've pretty strictly applied the "no open ranges" rule, except when compat restricts us (like in `transform-origin`).  I think the right answer here is obvious - allow zero, require UAs to clamp to a UA-specific minimum value, suggested to be `1px`.

**Comment by ewilligers** [comment]
I just came across this inconsistency while testing column-width animation, and was about to create an issue recommending that we accept any non-negative value, when I search and found that this issue had already been raised.

> They seem likely to lead to interoperability problems

It has ([Test](https://jsfiddle.net/ericwilligers/g9wqkent/)):

Firefox accepts 0px and 0em as specified values for column-width. Other browsers reject these values.

Edge never gives 0px as a computed value of column-width (e.g. as the result of a calc expression, or when font-size is 0px), instead it gives a fraction of a pixel. Other browsers can give 0px as a computed value of column-width.

**Comment by mstensho** [comment]
Allowing column-width:0 makes sense, but if column-gap is also 0 at the same time, we'll end up with an infinite used column-count, and there'll be no progression in the inline direction. Apart from that, the only interesting implication of infinite column-count that I can think of, spec-wise, is column balancing:

```
<div id="mc" style="column-width:0; column-gap:0;">
  <div style="height:10000px;"></div>
</div>
```

With auto height and column balancing and an infinite number of columns, we'll end up with a silly height of #mc. We have 10000px to distribute over ∞ columns, so even a height of 0 would do in that sense, except that then we'd have no block progression, and luckily a fragmentainer is required to be >= 1px tall [1]. So we'll "only" end up with 10000 columns?

[1] https://www.w3.org/TR/css-break-3/#breaking-rules

**Comment by dbaron** [comment]
I tend to think that for animation, the clamping should be at used value time rather than computed value time.

**Comment by rachelandrew** [comment]
So in terms of wording for the spec. The current wording for computed value is correct "the absolute length, zero or larger"?

And this new wording should replace, "[Specified values must be greater than 0](https://drafts.csswg.org/css-multicol/#valdef-column-width-length)" with something like:

"Specified values of 0 are allowed, however the used value of any value less than 1px will be clamped at 1px."

**Comment by ewilligers** [comment]
> "Specified values of 0 are allowed, however the used value of any value less than 1px will be clamped at 1px."

It needs to be clear if specified values may be negative (no) or between 0 and 1 (yes).

We could have the common wording "Negative values are not allowed." and "the absolute length" instead of having unusual wording for the specified and computed values. And add "Used values will be clamped to a minimum of 1px."
