### ISSUE TITLE
[css-multicol] Can overflow content influence column height?

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#1745]
An issue raised in [October 2013 on www-style](https://lists.w3.org/Archives/Public/www-style/2013Oct/0396.html):

> An issue come up today in a discussion with a seasoned multicol
implementer: does overflow content influence column height?
>
> Consider a multicol element with two columns, and column breaks after
each paragraph:
>
> article { columns: 2; background: yellow }
> p { break-after: column }
>
> Then you pour three `p` elements into the `article`: two one-liners and then one long paragraph (say, 10 lines). What's the resulting height of the article? 1 or 10 lines (disregarding padding for a moment).
>
> I can see two alternatives:
>
> (1) the multicol element is made high enough to fit all columns. In this case, there will be three columns: two with one line each, and a third column -- outside the multicol element -- with 10 lines. The yellow box will be high enough to fit the third column, even if it shown outside the multicol element.
>
> (2) the multicol element is made high enough to fit all columns that end up inside the box. So there will be two columns with one line of text each inside the multicol element, and then there will be 10 overflow columns outside.
>
> I think I have a slight preference for (2).
>
> Implementations vary, and it's hard to test as not all support explicit column breaks.

In comments [1](https://lists.w3.org/Archives/Public/www-style/2013Oct/0397.html), [2](https://lists.w3.org/Archives/Public/www-style/2013Oct/0423.html) on this issue @astearns and @tabatkins seem to agree on 2.

**Comment by tabatkins** [comment]
Yeah. If coming at this from nowhere, I'd probably answer (1), but the existing behavior of balancing and spanning leans me heavily towards (2), as Alan argued in the past.

**Comment by mrego** [comment]
BTW, this is an example for this issue: https://codepen.io/mrego/pen/GxLQJm

In WebKit and Chromium the mutilcol container has 1 line height. Like the overflow columns.

In Edge it has a bigger height, and the overflow columns also have that height.

It seems `break-after: column;` is not supperted on Firefox yet.
