### ISSUE TITLE
[css-grid] grid-{row, column}-gap <percentage> value has no mention of what the percentage refers to.

### ISSUE THREAD

**Issue by teoli2003** [w3c/csswg-drafts#175]
In https://drafts.csswg.org/css-grid/#propdef-grid-row-gap , the value <percentage> has been recently added.

In the property box, there is still a Percentage: n/a. Nothing in the following paragraph too.
It should mention that the percentage refers to the dimension of the grid container (If I have understood https://lists.w3.org/Archives/Public/www-style/2016Apr/0351.html correctly), and the property box should be amended.

**Comment by fantasai** [comment]
Fixed, thanks!
