### ISSUE TITLE
[css-text] Tease apart the idea of 'syllable boundaries'?

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1750]
https://drafts.csswg.org/css-text-3/#valdef-word-break-break-all

> In several other writing systems, (including Chinese, Japanese, Yi, and sometimes also Korean) a soft wrap opportunity is based on syllable boundaries, not word boundaries. In these systems a line can break anywhere except between certain character combinations. Additionally the level of strictness in these restrictions can vary with the typesetting style.

Maybe change the second sentence to say: 
"In these systems a syllable is represented by a single character, and a line can break anywhere except between certain character combinations."

Why make that distinction? Javanese and Balinese are scripts that don't use spaces to separate words or syllables and, unlike Thai, wrap between orthographic syllables (not words or characters), ie. a sequence of characters which may be longer than a grapheme cluster, for example, quite often including Cons+virama+Cons+VSign+Diacritic).  That's a different approach to wrapping based on syllable boundaries from the one described in the spec.  Tibetan, of course, is similar in this respect, in that it wraps syllables rather than words, and has no spaces in a sentence, although in that case for the most part (but not always) the syllables are clearly marked with tsek characters.

Perhaps it might be worth including a sentence to allude to scripts that wrap by syllable, when that is not a single character. (And perhaps i should write an article similar to the one on justification, but about line-breaking...)

**Comment by fantasai** [comment]
OK, rewrote that paragraph to include Javanese &co. @r12a Let me know if it looks OK now?
