### ISSUE TITLE
[css-display][css-contain] Rename "Becoming a formatting context"

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1758]
CSS Display (or is it CSS Contain?) has this transformation called ["Becoming a formatting context"](https://drafts.csswg.org/css-display-3/#becoming-formatting-context). I think the name is confusing because it makes a box establish a formatting context, not become one (that wouldn't make much sense). It should be renamed to something like "Becoming a formatting context **root**".

**Comment by frivoal** [comment]
This seems reasonable to me. This seems purely editorial on something that doesn't have traction yet, so I don't think I need a group resolution, and I'll just do it.
