### ISSUE TITLE
[css-scroll-snap] point value of scroll-snap-type is at risk but never mentioned

### ISSUE THREAD

**Issue by alrdytaken** [w3c/csswg-drafts#1759]
In ````Status of this document```` it says:
`````
The following features are at-risk, and may be dropped during the CR period:
• point value of scroll-snap-type
`````
But in the specs ````point```` already isn't mentioned anywhere as possible value of ````scroll-snap-type````.

https://www.w3.org/TR/2017/CR-css-scroll-snap-1-20170824/

**Comment by tabatkins** [comment]
Fixed, thanks!
