### ISSUE TITLE
Arrow-index property [css4-ui]

### ISSUE THREAD

**Issue by bradkemper** [w3c/csswg-drafts#1762]
https://www.w3.org/TR/css-ui-4/

I think that besides a tab-index property, we should have an arrow-index property. 

When designing component-like things, or when trying to make things such as menus or fake SELECTs behave more like native elements for keyboard users, a recommended technique is to use a roving tabindex. The purpose of it is so that there will be only one tab stop for the component when someone is tabbing through the document, but arrow keys can be used to focus the various sub-elements of the component. But that requires some often complex JavaScript. 

So, if we had a `tab-index` property in CSS (or `tab-next` or whatever) to determine what can be focused via the tab key, and in what order, it would be nice to have a separate property to set what can be focused via arrow keys, and in what order. So, for most elements, the initial value would be `arrow-index:-1` (meaning that users cannot change focus via the arrow keys), but we might need something like 'arrow-index:auto', to account for the way arrow keys can change the focus among radio buttons with the same name. `arrow-index:0` (or any positive number) would enable the element to be accessed via arrow keys. Another property on an ancestor or on one thing that selected several elements at once, could isolate the arrow keys to only focus within a certain context. For instance, `div.menu { arrow-group: isolate} div.menu a { arrow-index:0 }` would mean that you could use the arrow keys to change focus between the anchors within the menu, but could not arrow to something outside of that menu (even if it was another menu with the same class).

Also, though I'm not sure it is necessary, it might be good to have two properties: `arrow-index-x` and `arrow-index-y`, so that authors can turn on/off arrow focusing independently for each direction.

**Comment by bradkemper** [comment]
Or maybe radio buttons could be explained with this:

`input[type=radio][name] { arrow-group: isolate}   input[type=radio] { arrow-index:0 }`

But that would mean somehow that it would isolate the arrowing to radio buttons with the same name, not just to radio buttons with any name.

**Comment by frivoal** [comment]
The `nav-*` properties and a potential `tab-index` or `nav-next` are modifying an existing behavior of the browser. Tab focusing and spatial navigation are assumed to be supported things the browser can already do, and the properties just influence the order in which you focus things.

Unless I am missing something, the arrow focusing you're speaking of isn't a pre-existing thing supported by the browser.

That doesn't mean nothing can be done, but that seems like a larger chunk of new functionality, which needs to define how it interacts with other key related events and the like. I'm not 100% sure this would belong in a CSS spec.

**Comment by bradkemper** [comment]
There is arrow focusing with radio button groups, and SELECT OPTIONs.  In the same way that ‘tab-index:0’ could bring tab focusing to any element, I’d like to bring that arrow focusing behavior of radio buttons to any element. 

For component-like things, like menus, the recommended behavior is that there should be only one tab stop, and that arrow keys move the focus within the component. Currently this involves a lot of keystroke trapping and a technique called roaving focus (or roaming focus) to accomplish, using a lot of JavaScript. 

I am suggesting a simpler CSS method, where it could look something more like this:
```
[role=menu] {
    arrow-group:isolate 
    /* so arrowing does not take you from inside the menu to outside the menu, and arrow-index on the menu’s descendants only affects the arrowing order of those descendants and not other elements  */
}
[role=menuitem] {
    tab-index: none;
    arrow-index:0;
}
[role=menu]:not(:has-focus) >[role=menuitem]:first-child {
    tab-index: 0;
}
```
And that would mostly take care of tabbing in and out of a menu, and arrowing to the menu items. It would be so much simpler than the ways we have to deal with things like this now for keyboard access.

**Comment by bradkemper** [comment]
A slightly fancier version of `arrow-index` would have a 2-component number value, the first number for horizontal arrows and the second number for vertical arrows.

**Comment by frivoal** [comment]
Closing in favor of https://github.com/WICG/spatial-navigation

That's still in the infancy stage, but it is the forum that the CSS-WG has chosen to discuss this sort of topics.

@bradkemper I believe your issue fits within the general framework of the discussions over there and doesn't need a disctinct issue in that repo, but if you feel otherwise, please open an new issue there, and link back to this one for background.
