### ISSUE TITLE
[css-box-3] Does visibility:collapse gets inherited as collapse or hidden from a box where it is used as hidden

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#1763]
Looking at https://drafts.csswg.org/css-tables-3/ it's not clear what the behavior of this testcase should be:

    <table style="visibility: collapse">
      <tbody style="visibility: visible">
        <tr>
          <td>
            Some text
          </td>
        </tr>
      </tbody>
    </table>
    <script>
      alert(document.querySelector("td").offsetWidth);
    </script>

Does this table have an anonymous table column group that inherits the "collapse" visibility style (in which case 0 should maybe be alerted)?  Or is there no table column group here at all, and the width should be the width of the text in the cell?

Firefox seems to implement the former behavior (0 is alerted).  Chrome and Safari have no support for `visibility: collapse` on table-column-group boxes at all, so alert the width of the text, but they do that even if I add an explicit `<colgroup>`, and show the text, in which case it seems clearly wrong.  

Edge alerts the width of the text, but it does that even if there's an explicit `<colgroup>`, even though in that case it doesn't show the text.  I'm not sure whether that's the right behavior or not,  In any case, in the testcase above in Edge the text _is_ shown, which means edge doesn't create an anonymous column-group box, or at least doesn't inherit visibility into it...

**Comment by FremyCompany** [comment]
```visibility:collapse``` does not apply to table elements. It only applies to non-cell table-internal elements.

> If used on elements other than rows, row groups, columns, or column groups, 'collapse' has the same meaning as 'hidden'. 
> www.w3.org/TR/CSS2/visufx.html#visibility

this is also clarified here

> Visible tracks: For the purpose of this algorithm, a column or row is considered a visible track if neither its corresponding table-track nor its table-track-group parent (if any) have visibility set to collapse.
> https://drafts.csswg.org/css-tables-3/#bounding-box-assignment

if you look at anonymous element creation, you'll see that no anonymous column element is ever created, so that should settle the case for your specific example.

as for inheritability if the ```<col>``` was written in markup, I would assume "collapse" computes to "hidden" and is inherited as such in the case mentioned here but I will admit it is not written anywhere. I would argue though that if that needs to be clarified, it should be clarified in the spec that defines the visibility property:

> https://drafts.csswg.org/css-box-3/#visibility-prop

**Comment by FremyCompany** [comment]
I checked and everybody inherits as "collapse" so there is no need to clarify further the follow-up issue.

**Comment by FremyCompany** [comment]
Just to clarify, the answer is no. There is never any mention in the spec of generating table-column or table-column-group elements (and the fact language in the spec says "(if any)" should be sufficient to make it clear that this is intended)

**Comment by bzbarsky** [comment]
> I would assume "collapse" computes to "hidden"

Why would it do any such thing?  Visibility computes "as specified" and always has.

For the actual issue I reported, what's not clear to me is whether the spec assumes that the column and colgroup boxes always exist, in its algorithms.  It certainly seems to assume that "columns" exist and at the same time talks about "columns" synonymously with "column boxes" in various places.  This leads to a lack of implementation clarity, as evidenced by the utter lack of interop described above.

**Comment by FremyCompany** [comment]
I disagree, the spec uses two different names for columns and the table-column boxes. The spec keep saying (if any) when talking about the element associated to a conceptual column. Also the spec has:
> Each row of the grid **might** correspond to a table-row, and each column to a table-column.

Now, spec text has come from multiple specs and we are not infaillible, so if there are instances where we meant "table-column" where we wrote "column", we should fix these. Do you have any such instance?

**Comment by FremyCompany** [comment]
I just quickly reviewed the 300+ usages of "column" in the spec, and didn't find more than three cases where the spec is misusing one term for the other:

**In cell measurements:**

> The outer min-content width of a table column or column group is max(min-width, width). 

Should be changed to "width of a table-column or table-column-group" to be more clear

**In column measurements:**

> A column is constrained if the column group (if any), the column (if any), or any of the cells spanning only that column has a computed width that is not "auto", and is not a percentage. 

Should be changed to "A column is constrained if its corresponding table-column-group (if any), table-column (if any), or any of the cells spanning the column only..."

**In background painting:**

> its originating column

Should be changed to "its originating table-column (if any)" 

**Please tell me if you see any other.**
