### ISSUE TITLE
[css-grid] Missing Figure 1 in Spec

### ISSUE THREAD

**Issue by samuells** [w3c/csswg-drafts#177]
**CSS Grid Layout Module Level 1** Spec refers to Figure 1, but in the document is no Figure 1. 

In the section [2.1. Background and Motivation](https://drafts.csswg.org/css-grid/#background)

> Figure 1 illustrates a basic layout which can be achieved with grid layout.

**Comment by samuells** [comment]
There is probably a general problem with figures naming. Figures are named only with even numbers.

**Comment by fantasai** [comment]
This is a Bikeshed spec generator problem, filing over there...
