### ISSUE TITLE
[css-ui] Review of the optional test failures in the css-ui-3 test suite

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1770]
Optional tests with no passing implementation
---

| SHOULD / MAY | Test | Assert | Note |
|------------------|-----|--------|-----|
| SHOULD | [outline-005](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-005/format/html5/) | To the extent that the outline follows the border edge, it should follow the border-radius curve. | Safari does follow this, but only when outline-style is auto, which isn't captured by the test.|
| SHOULD | [outline-014](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-014/format/html5/) [outline-015](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-015/format/html5/) [outline-016](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-016/format/html5/) | Both the height and the width of outside of the shape drawn by the outline should not become smaller than twice the computed value of the outline-width property, to make sure that an outline can be rendered even with large negative values. User Agents should apply this constraint independently in each dimension. If the outline is drawn as multiple disconnected shapes, this constraint applies to each shape separately. | This is a recommendation on how to handled an error case. <br><br>Firefox passes [outline-013](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-013/format/html5/) which is the base variant for the same thing, while these 3 poke at more elaborate cases.|
| SHOULD | [text-overflow-018](http://test.csswg.org/suites/css-ui-3_dev/nightly-unstable/html/text-overflow-018.htm) | Selecting the ellipsis should select the ellipsed text|
| MAY | [resize-008](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-008/format/html5/) [resize-009](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-009/format/html5/) [resize-010](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-010/format/html5/) [resize-011](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-011/format/html5/) [resize-013](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-013/format/html5/) [resize-014](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-014/format/html5/) | UAs may apply the resize property to `<img>`(008) / `<svg>`(009) / `<picture>`(010) / `<object>`(011) / `<canvas>`(013) / `<video>`(014)  regardless of the value of the overflow property. | Safari and Chrome have started doing it on iframes ([resize-012](https://test.csswg.org/harness/test/css-ui-3_dev/single/resize-012/format/html5/))|
| MAY | [cursor-image-013](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-image-013/format/html5/) [cursor-image-014](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-image-014/format/html5/) [cursor-image-015](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-image-015/format/html5/) [cursor-image-016](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-image-016/format/html5/) | For cursors, UAs may support gradients (013) / the image() function (014) / the image-set() function (015) / the cross-fade() function (016)| `cusror:<url>`=OK (css-values-3), `cusror:<image>`=FAIL (css-images-3 / css-images-4)|
| MAY | [cursor-text-002](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-text-002/format/html5/)|User agents may automatically display any angle of I-beam/cursor for text that is rendered at any particular angle||

Optional tests with *only one* passing implementation
---

| SHOULD / MAY | Test | Assert | Note |
|------------------|-----|--------|-----|
| SHOULD | [text-overflow-019](https://test.csswg.org/harness/test/css-ui-3_dev/single/text-overflow-019/format/html5/)|If all of the ellipsed text is selected, UAs should show selection of the ellipsis.|Safari OK|
| SHOULD | [text-overflow-021](https://test.csswg.org/harness/test/css-ui-3_dev/single/text-overflow-021/format/html5/)|When an element with ellipsis is scrolled, more content should be revealed| Firefox OK|
| SHOULD | [outline-013](https://test.csswg.org/harness/test/css-ui-3_dev/single/outline-013/format/html5/) | Negative values on outline-offset should not cause the height and the width of outside of the shape drawn by the outline to become smaller than twice the computed value of the outline-width property | Firefox OK|
| MAY | [cursor-text-001](https://test.csswg.org/harness/test/css-ui-3_dev/single/cursor-text-001/format/html5/) | User agents may automatically display a horizontal I-beam/cursor (e.g. same as the vertical-text keyword) for vertical text. | Firefox OK|

---

Note: It is ambiguous whether Blink and Webkit are separate implementations or not, as they share the same base for most of the code, but have separate fixes applied in some cases. The above result are true even if they are counted as one.

**Comment by frivoal** [comment]
My take on these results:

All these are acceptable failures and should not warrant an change in the spec, possibly with the exception of outline-005, and text-overflow-018.

SHOULD / No implementation:
---
* outline-005: One browser does the recommended thing in a subset of the cases. Others don't. Maybe we want to continue encouraging this, or maybe we give up.

* outline-014 to outline-016: Recommendation on error handling. Firefox does better than the rest. This is a question of quality of implementation. No need to change.

* text-overflow-018: This is a question of quality of implementation, but no implementation tries. Maybe we want to continue encouraging this, or maybe we give up.

MAY, No implementation:
---
* resize-008 to resize-014: This is a forward compat hatch. resize-012 has been used by two browser. Keep.

* cursor-image-013 to cursor-image-016: This is a forward compat hatch. Keep.

* cursor-text-002: This is an open door for better quality of implementation / interaction with transforms. Keep.

SHOULD, 1 implementation:
---
* text-overflow-019: Quality of implementation, 1 browser doing better. Keep.

* text-overflow-021: Quality of implementation, 1 browser doing better. Keep.

* outline-013: Quality of implementation, 1 browser doing better. Keep.

MAY, 1 implementation:
---
* cursor-text-001: Quality of implementation &amp; integration with writing-modes, 1 browser doing better. Keep.

**Comment by frivoal** [comment]
At the last F2F, I was task with going through the failures of the optional tests on css-ui-3, to figure out if they were acceptable failures or if we should fix somethings. The previous two comments are the results of that investigation: the first one being the objective results, and the second one my take on them.

Agenda+ to see if we want to make any modification to the spec based on this or not.

**Comment by fantasai** [comment]
I agree with @frivoal's conclusions in https://github.com/w3c/csswg-drafts/issues/1770#issuecomment-326241391. Happy to keep as-is for the ones which have no recommendation.

**Comment by FremyCompany** [comment]
> SHOULD | text-overflow-021 | When an element with ellipsis is scrolled, more content should be revealed

I am not sure about that one, but I'm fine with keeping things as-is.
