### ISSUE TITLE
[css-align] typos

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1772]
discrepency -> discrepancy
axises -> axes

**Comment by tabatkins** [comment]
"Axises" isn't a typo. I'll fix the other one. ^_^

**Comment by r12a** [comment]
> "Axises" isn't a typo.

Oh. So is it a CSS technical term?  I don't think it's an Americanism. (And i doubt it's about deer http://www.dictionary.com/browse/axises)

**Comment by tabatkins** [comment]
I REFUSE TO APPLY ARCHAIC FAKE-LATIN PLURALIZATION TO OUR GLORIOUS LANGUAGE, THEY WERE INVENTED BY PRESCRIPTIVIST GRAMMARIANS WITH A HARDON FOR LATIN.

;)

**Comment by r12a** [comment]
As thou wilt, thus shall it come to pass. ;-)
