### ISSUE TITLE
[css-values][cssom] Which unit to serialize <resolution> with?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#178]
CSSOM defines that `<resolution>` values must be serialized with the dpcm unit.  I don't think anyone does that, and it seems like the least useful of all the resolution units.

Most useful is probably dppx, but dpi is also common.  Which one should we use?

**Comment by astearns** [comment]
The working group resolved to use dppx https://lists.w3.org/Archives/Public/www-style/2016Jun/0118.html. Removing the agenda tag
