### ISSUE TITLE
[css-writing-modes][css-values] Font metrics calculation on elements which writing-mode doesn't apply to

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1782]
I realized that this could be an issue when I was thinking about #1773.

There are some elements that [`writing-mode`](https://drafts.csswg.org/css-writing-modes-3/#block-flow) doesn't applied to, specifically, table row groups, table column groups, table rows, table columns, ruby base container, and ruby annotation container, per css-writing-modes spec. However, there are some [font-relative units](https://drafts.csswg.org/css-values-3/#font-relative-lengths) defined in css-values which depend on `writing-mode` property.

The question is, for an element which `writing-mode` doesn't apply to, should the font-relative units be computed based on the value of the computed (but not applied) `writing-mode`, or the used `writing-mode` (from some ancestor)? I guess the same question applies to [logical properties](https://drafts.csswg.org/css-logical/) as well.

The description of "Applies to" in CSS 2.1 says
> All elements are considered to have all properties, but some properties have no rendering effect on some types of elements.

I guess it indicates that the computed value should probably be used? It also seems to me that it could be hard to have style computation based on used value, because that would create more complicated dependencies.

Probably the spec should mention that, although `writing-mode` doesn't apply to these elements, the style computation is still done based on the computed value of `writing-mode` of the same element.

**Comment by kojiishi** [comment]
This looks reasonable to me to use computed values of `writing-mode` for unit resolutions and logical properties. @nainar, thoughts from the style engine?

**Comment by fantasai** [comment]
Agreed that we should just use the computed style for simplicity. Agenda+ for WG confirmation.

**Comment by fantasai** [comment]
Proposed text: replace Applies to lines for `writing-mode` and `text-orientation` with “all elements”, and add the following paragraph (where?):

>Table row groups, table column groups, table rows, table columns, ruby base containers, and ruby annotation containers use their formatting context’s <a>writing mode</a> for layout. Their 'writing-mode', 'direction', and 'text-orientation' properties are otherwise ignored, except insofar as they affect computed values that depends on them (through e.g. <a>inheritance</a>,
  computed <a>font-relative lengths</a> or <a href="https://www.w3.org/TR/css-logical/">flow-relative properties</a>).

**Comment by upsuper** [comment]
Would it make more sense to put this into CSS 2 stating something like "Applies to" doesn't affect CSS computation?

**Comment by dbaron** [comment]
[Section 6.1.2](https://www.w3.org/TR/2011/REC-CSS2-20110607/cascade.html#computed-value) already says:
> The computed value exists even when the property does not apply, as defined by the 'Applies To' line. However, some properties may define the computed value of a property for an element to depend on whether the property applies to that element.

which I think is clear enough one of the underlying points here.  It should probably be part of a level 3 draft somewhere if isn't already, though.

(Linking to the 2.1 REC rather than editor's drafts because I've lost track of which editor's draft is which, and which editor's draft (if any) is reliable.)

**Comment by dbaron** [comment]
It's actually in [section 4.4](https://drafts.csswg.org/css-cascade/#computed) of css-cascade as well:
> The computed value exists even when the property does not apply (as defined by the “Applies To” line). However, some properties may change how they determine the computed value based on whether the property applies to the element.

**Comment by fantasai** [comment]
@upsuper Changes checked in. Would you let me know if the new wording is acceptable?

**Comment by upsuper** [comment]
Yeah, I think that works.

**Comment by frivoal** [comment]
Is that change considered normative? Should there be tests? I mean, tests are always good, but are they required here?

**Comment by frivoal** [comment]
I made test cases for this in https://github.com/w3c/web-platform-tests/pull/8929. Review welcome.

By the way, why is this issue not closed yet? We usually don't keep issue open just for missing tests, and I cannot find anything else missing here.

**Comment by fantasai** [comment]
It was left open waiting for Xidorn's reply; should be closed now that he's given it (and you've updated the tags ;).
