### ISSUE TITLE
[mediaqueries-4] Confused about the Boolean value of media features

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#1786]
[Section 2.4.2. Evaluating Media Features in a Boolean Context](https://drafts.csswg.org/mediaqueries-4/#mq-boolean-context):

> If the feature would be true for any value other than the number `0`, a `<dimension>` with the value `0`, or the keyword `none`, the media feature evaluates to `true`. Otherwise, it evaluates to false.

If I understand correctly, this means that if I, for example, wanted to determine whether `(orientation)` evaluates to `true`, I would have to check if at least one of  `(orientation: portrait)` and `(orientation: landscape)` evaluates to `true`. If it does, that would meet the “any value” requirement mentioned in he quote above.

However, I’m having trouble finding the spec section that states that any keyword value other than `none` evaluates to `true`, which I assume to be the case. Could you point me in the right direction?

**Comment by simevidas** [comment]
Ah, I think I’ve figured it out. All keyword values with the exception of `none` evaluate to `true`, because they represent something that *can* be true in certain conditions. It is logically impossible for a keyword value to never be true, unless it were explicitly defined to never be `true`, which wouldn’t make sense.

That being said, the quote in my original post implies that there exist media features that evaluate to `false` in a Boolean context. Could you give an example of such a media feature? This doesn’t seem possible, since `0` and `none` are the only falsy media feature values.

**Comment by simevidas** [comment]
Ok, I think I’ve figured it out now. It depends on the *environment* in which the CSS is evaluated. So, for example, the `pointer` media feature accepts three values: `none`, `coarse`, and `fine`. In environments without a pointing device, both non-`none` values evaluate to `false`, and hence, `(pointer)` itself evaluates to `false`. On the other hand, in environments with any kind of pointing device, at least one of the non-`none` keywords will evaluate to `true`, and so `(pointer)` will be `true`, because it meets the “any value” requirement from the original quote above.

**Comment by tabatkins** [comment]
Yeah, the MQ keywords aren't variables, they're, well, queries.  `(orientation: landscape)` is a question asking "is the orientation currently landscape?", which is either true or false, not something fetching the fixed-per-UA value of a `landscape` variable.
