### ISSUE TITLE
[css-writing-modes] Missing Testcases

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1792]
Need to make sure we have tests for these:

https://lists.w3.org/Archives/Public/www-style/2017May/0002.html
https://lists.w3.org/Archives/Public/www-style/2015Sep/0326.html

(I suppose WPT has some process for tracking such things as missing coverage but until it's documented in http://web-platform-tests.org/ I'm just going to assume it doesn't exist.)

**Comment by frivoal** [comment]
@fantasai regarding https://lists.w3.org/Archives/Public/www-style/2015Sep/0326.html :

We already have this test: https://github.com/w3c/web-platform-tests/blob/master/css/css-writing-modes/writing-mode-parsing-svg1-001.html which checks that the legacy svg values compute to the right thing. I've just created https://github.com/w3c/web-platform-tests/pull/8931 based on the file you attached to https://lists.w3.org/Archives/Public/www-style/2015Sep/0326.html to also check that this aliasing mechanism isn't messing with bidi. Do you think we need anything more for this topic? (I'll look into the other mail separately).

**Comment by frivoal** [comment]
Made a pull request for https://lists.w3.org/Archives/Public/www-style/2017May/0002.html too:

https://github.com/w3c/web-platform-tests/pull/8932

**Comment by frivoal** [comment]
Test cases merged, closing.
