### ISSUE TITLE
[css21][css-inline] Position of the baseline inline-level boxes with non normal line-height

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1801]
**This is part of the #1796 series. Read that issue for context**

----
1.

All browsers (Safari, Chrome, FF, Edge) agree, that the position of the baseline within an inline level box with the line-height property set to something other than normal **does not depend on on fallback fonts**.

[Test source](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/line-height-002.html)
[Ref source](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/reference/line-height-002-ref.html)
[Live test](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/line-height-002.html)
[Live ref](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/reference/line-height-002-ref.html)

----
2.

All browsers (Safari, Chrome, FF, Edge) agree, that the position of the baseline within an inline level box with the line-height property set to something other than normal **is set based on the primary the primary font**.

[Test source](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/line-height-003.html)
[Ref source (mismatch)](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/reference/line-height-003-ref.html)
[Live test](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/line-height-003.html)
[Live ref (mismatch)](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/reference/line-height-003-ref.html)

----
1+2 => This is the blue behavior in [this diagram](https://lists.w3.org/Archives/Public/www-archive/2017Apr/att-0008/IMG_20170421_173959.jpg).

We should spec that.

----
3.

More specifically, all browsers (Safari, Chrome, FF, Edge) agree that the position of the baseline within an inline level box with the line-height:normal and in a inline-level box with the line-height  property manually set to the height you'd get with `line-heigh:normal` (assuming only the primary font is used) are the same.

This is unsurprising, but it is good to have it confirmed.

[Test source](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/line-height-004.html)
[Ref source](https://github.com/frivoal/web-platform-tests/blob/line-height-experiments/css/css-line-height/reference/line-height-004-ref.html)
[Live test](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/line-height-004.html)
[Live ref](https://rawgit.com/frivoal/web-platform-tests/line-height-experiments/css/css-line-height/reference/line-height-004-ref.html)

---

However, see #1798 for a possible exception to point 2 and 3.

**Comment by frivoal** [comment]
This, combined with https://github.com/w3c/csswg-drafts/issues/1797, means that CSS21's "10.8.1 Leading and half-leading" is incorrect, and in particular its especially the 3rd paragraph, since that effectively describes the black behavior in [the Tokyo diagram](https://lists.w3.org/Archives/Public/www-archive/2017Apr/att-0008/IMG_20170421_173959.jpg). The first sentence of the fourth paragraph is incorrect as well (paraphrase: "therefore, [something that does not result from what we just said]), and should be dropped as well.

These third paragrpahs and first sentence of the 4th one should be replaced with something like:
> When the value of the `line-height` property is something other than `normal`, determine the leading L to add, where L = 'line-height' - AD of the first available font. Half the leading is added above A of first available font and the other half below D of first available font, giving the glyph and its leading a total height above the baseline of A' = A + L/2 and a total depth of D' = D + L/2. Glyphs from fonts other that the first available font do not impact the height of the inline box.

**Comment by dbaron** [comment]
Perhaps even with "height of the inline box" at the end replaced by "height or baseline of the inline box".

**Comment by fantasai** [comment]
CSSWG minutes and resolution: https://lists.w3.org/Archives/Public/www-style/2017Dec/0007.html
