### ISSUE TITLE
[css-flexbox] Clarify sentence construction in max-content flex fraction step

### ISSUE THREAD

**Issue by astearns** [w3c/csswg-drafts#1803]
The first step in https://drafts.csswg.org/css-flexbox/#intrinsic-main-sizes has a fairly complex second sentence. I had to read it twice to note that the parentheticals referred to the same result in the first clause. Scanning quickly I assigned the parentheticals to their closest sentence part. I think my problem is that the parenthetical came after the preposition.

In other words, in this construction "if the result is not zero, divide it by {(some parenthetical) its foo}" I'm scanning {} as a prepositional phrase that's the object of the verb. It took me a bit to notice the word 'result' and fix my confusion.

I think it would be clearer to say "if the result is not zero, divide a positive result by … or a negative result by …"

**Comment by fantasai** [comment]
We don't really need to call out zero here, do we. Fixed with that simplification, let me know if it works @astearns ? :)

**Comment by astearns** [comment]
Could you add "divide" to the second path?

**Comment by fantasai** [comment]
Done.
