### ISSUE TITLE
[css-lists] Almost all the spec is inside an example

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1806]
Example 2 is not closed, so the following spec contents are inside it.

The example just contains a description with no code, so not sure if it should be entirely removed, or if the code should be restored from before e1720ff0569d4eac1fe695e810b0a92f29e67b90

**Comment by tabatkins** [comment]
Ah, I meant to remove that example. Sorry about that. ^_^

(I really should put in that check for examples that have way too many children; this has happened several times.)

**Comment by Loirooriol** [comment]
Fixed by b7240faefc48371a74c1b20f2fd35c901b04535d.
