### ISSUE TITLE
[css-lists] Examples use properties not allowed in ::marker

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1807]
According to [CSS Lists](https://drafts.csswg.org/css-lists/#marker-pseudo),

> Only a limited set of properties can be used on the ::marker pseudo-element. This list is defined in CSS Pseudo-Elements 4 §4.2 List Markers: the ::marker pseudo-element.

[CSS Pseudo](https://drafts.csswg.org/css-pseudo-4/#marker-pseudo) says that only font properties, `color` and `text-combine-upright` apply to `::marker`.

However, in CSS Lists, various of examples use properties like `content`, `text-align`, `width`, `display`, `unicode-bidi`, `position`.

**Comment by SelenIT** [comment]
The CSS Pseudo spec has the following note:
> It is expected that future specifications will extend this list of properties; however _at the moment_ marker box layout is not fully defined, so only these properties are allowed.

Since the CSS Lists spec seems significantly less mature than CSS Pseudo spec, maybe it's expected that at the time CSS Lists spec is released all the open issues with marker box layout definition will be resolved and this limitation becomes outdated?

**Comment by gsnedders** [comment]
@SelenIT I believe that is the case. (i.e., you should consider List a future specification wrt Pseudo)

**Comment by Loirooriol** [comment]
If some properties can't be added to CSS Pseudo until CSS Lists is more mature, then I think these extra properties should be listed in CSS Lists meanwhile.

**Comment by fantasai** [comment]
OK, I've fixed most of these except what's in the default UA rules. We'll need to figure those out a bit more, so filed https://github.com/w3c/csswg-drafts/issues/3809

**Comment by fantasai** [comment]
(We dropped the section on marker positioning, so cutting down css-lists-3 to match what's in css-pseudo-4 and css2.1, more or less.)

**Comment by fantasai** [comment]
And fixed by adding https://github.com/w3c/csswg-drafts/issues/3809 and aligning with the list in css-pseudo-4.
