### ISSUE TITLE
[css-display] Do empty text nodes generate text runs?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1808]
Do text nodes with an empty string value generate a text run or not?

The difference will affect [run-in layout](https://drafts.csswg.org/css-display-3/#run-in-layout):

> If a run-in sequence is immediately followed by a block box [...]

And it's also observable in flow layout. According to [CSS 2.2](https://www.w3.org/TR/CSS22/visuren.html#inline-formatting),

> Line boxes that contain no text [...] must be treated as not existing [...]

I guess "text" refers to text runs. See https://jsfiddle.net/rs94bpay/

```html
<div><div>Foo</div></div>
```
```css
div {
  white-space: pre;
  border: 1px solid blue;
}
```
```js
document.querySelector('div').prepend('');
```
Firefox does not discard the line because of the text node, Chrome and Edge do.

**Comment by SelenIT** [comment]
The behavior of Firefox looks like a bug. The script doesn't add any white space characters that should be taken into account by `white-space` property. Interestingly, the same issue occurs for `body > div::before { content: '' }` instead of prepending empty string with the script.

**Comment by fantasai** [comment]
That's super weird, and it's definitely a bug. Different DOMs that output the same source code should not result in different CSS output, ever.

@SelenIT ::before { content: '' } is a little different, it causes the ::before pseudo-element to exist, and empty inline boxes count as content that causes a line box to exist.

**Comment by SelenIT** [comment]
> empty inline boxes count as content that causes a line box to exist

They do, but shouldn't they be treated as "not existing for any other [than positioning out-of-flow descendants] purpose" [phantom line boxes](https://www.w3.org/TR/CSS22/visuren.html#phantom-line-box)?

**Comment by Loirooriol** [comment]
@fantasai If I understand correctly, you mean that

 - An empty text node generates no text run.
 - A `::before` or `::after` with `content: ''` generates an empty text run.

Is that correct?

**Comment by fantasai** [comment]
@Loirooriol A `::before` or `::after` with `content: ''` generates a box containing nothing.

**Comment by fantasai** [comment]
@SelenIT That depends on if they are assigned any other styles. :)
