### ISSUE TITLE
[css-fonts] Animation on the condensed-expanded axis

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#1811]
> Animation of font stretch: Font stretch is interpolated in discrete steps. The interpolation happens as though the ordered values are equally spaced real numbers. The interpolation result is rounded to the nearest value, with values exactly halfway between two values rounded towards the later value in the list above.
https://drafts.csswg.org/css-fonts/Fonts.html#font-stretch-prop

With the advent of variable fonts, which can have a condensed-expanded axis, do we really want to mandate in Fonts 3 that `font-stretch` is animated by quantization to nine discrete steps? Options:

1. Remove the wording about animation of font-stretch from Fonts 3, leaving it undefined
2. Say something about variable fonts, in passing, like 'for fonts which are not Variable Fonts, font stretch is interpolated in discrete steps"
3. Do nothing, let Fonts 4 define animation better, don't test too hard for Fonts 3 (just a single test with a non-variable font).

**Comment by litherum** [comment]
Font weights are also rounded in level 3, and the WG already has a resolution about how this gets generalized for level 4. I see no reason why stretch should behave any differently.

**Comment by svgeesus** [comment]
Okay, as long as we are not painting ourselves into a corner. I worried that implementers would disregard those parts of Fonts 3, as they stat to implement Fonts 4. if that is not the case I am fine to close this issue.
