### ISSUE TITLE
[css-flexbox] Flexbox spec currently has "Printer" as its title

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#182]
STR:
 1. Visit https://drafts.csswg.org/css-flexbox/
 2. Look at page title (in browser title bar, as well as the title printed at the top of the page)

ACTUAL RESULTS:
The title is "Printer" for some reason.

EXPECTED RESULTS:
The title should be "CSS Flexbox Layout Module Level 1" or something like that.

**Comment by dholbert** [comment]
It looks like the spec does have an `<h1>` element about "Printer" in an example, further down the page. I'm guessing Bikeshed is getting confused and thinking that `<h1>Printer</h1>` is meant to be the page's title.

**Comment by dholbert** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/426803/15994353/10d689ec-30b7-11e6-95c8-a3d9fa13ee76.png)

**Comment by tabatkins** [comment]
Whoops, indeed, recent change I made to let people put actual markup/attrs in their H1 (for i18n/etc) by just reusing the actual H1 in the document if present is misfiring here.

**Comment by tabatkins** [comment]
And fixed in Bikeshed. Flexbox will rebuild shortly and have the correct title. ^_^

**Comment by dholbert** [comment]
Looks like this is indeed fixed in the flexbox spec. Thanks!
