### ISSUE TITLE
[css-syntax-3] <hash-token> seems to get type ID for sequence "#-\" followed by EOF 

### ISSUE THREAD

**Issue by bathos** [w3c/csswg-drafts#1821]
In [consume a token](https://drafts.csswg.org/css-syntax-3/#consume-token), the following steps are given for handling "#":

> If the next input code point is a name code point or the next two input code points are a valid escape, then:
> 1. Create a `<hash-token>`.
> 2. If the next 3 input code points would start an identifier, set the `<hash-token>`’s type flag to "id".
> 3. Consume a name, and set the `<hash-token>`’s value to the returned string.
> 4. Return the `<hash-token>`.

The "would start an identifier" check confirms that the backslash of an escape is not followed by a newline, even if the first char is hyphen, but confirming that such a backslash is not followed by EOF is deferred to "consume an escaped codepoint", via "consume a name" (step 3). Although indicated to be an error, this still yields the name that has been processed so far, and this will happen after the type flag has already been set.

I’m not sure if it really matters in practice (perhaps this is even intentional), but it struck me as odd that (assuming I’m reading it correctly) this would mean that the sequence `U+0023 U+002D U+005C EOF` would produce a hash token whose type is set to ID, even though "-" isn’t a valid ID.

**Comment by tabatkins** [comment]
Hm, this seems to be a bug in [check if two code points are a valid escape](https://drafts.csswg.org/css-syntax/#check-if-two-code-points-are-a-valid-escape), actually. `\EOF` isn't a valid escape; it's a bare `\` character.  I think I need to check for that and return false.

It probably doesn't matter in practice, but it's definitely not intentional.  I'll fix after getting confirmation from the WG.

**Comment by tabatkins** [comment]
Thanks for the report, @bathos! Fixed.

**Comment by astearns** [comment]
Syntax is in CR, so we should keep the issue open until we have a test.

Also the change, even though it's really minor, should be listed in the changes section.

**Comment by tabatkins** [comment]
Ah, right, it does belong in Changes.

(And yeah, as Elika expressed elsewhere, GitHub's natural flow of auto-closing issues based on commit message makes this "keep it open until testcase" thing kinda annoying. You have to tiptoe around mentioning the issue so as to not trigger one of the closing phrases.)

**Comment by zcorpan** [comment]
@tabatkins can you point to the testcase in web-platform-tests? If there isn't one, this should be open?

**Comment by tabatkins** [comment]
Per #3182, we messed up on this; this particular case *should* produce a hash token of "ID" type. Test case will go in #3182.
