### ISSUE TITLE
[css-writing-modes] Clarify meaning of note in "7.3. Orthogonal Flows"

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1825]
At the bottom of [7.3. Orthogonal Flows](https://drafts.csswg.org/css-writing-modes-3/#orthogonal-flows), there this note:

> Note that this section requires that when an auto-sized child box establishes an orthogonal flow, the used size of the child is calculated to fit its content; and this resulting content-based size is used as input to the inline-axis min-content and max-content of the parent.
> 
> This means that when applying shrink-to-fit formula to a box such as an inline-block, float, or table-cell, if its child establishes an orthogonal flow, the calculation dependency must be changed so that the sizing phase of the child runs first and its used block size becomes an input to the inline-size shrink-to-fit formula of the parent.

I was having an offline discussion, and we couldn't agree about exactly what this meant.

One interpretation (mine) was this meant:

> Note that this section requires that when <del>an auto-sized child box</del><ins>a child box auto-sized in the logical height axis</ins> establishes an orthogonal flow, the used <del>size</del><ins>logical height</ins> of the child is calculated to fit its content; and this resulting content-based size is used as input to the inline-axis min-content and max-content of the parent.

Another one was that this may be outdated wording, and that since we no longer have [auto-multicolumn](https://www.w3.org/TR/css-writing-modes-3/#auto-multicol) and its requirements to do shrink to fit, and that it should be updated or maybe removed.

Or maybe we were both missing the point. If I was reading this correctly, I suggest updating the wording to my suggestion above. Otherwise, I'd appreciate a clarification.

**Comment by fantasai** [comment]
Your interpretation is correct afaict. I will clarify the note.
