### ISSUE TITLE
[css-text-decor] images are missing

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1827]
... from https://drafts.csswg.org/css-text-decor-3/

(I tried reloading a couple of times, and a couple of browsers).

**Comment by fantasai** [comment]
Yeah, because @tabatkins moved the images and didn't update their links in 31043718b836ddcbe284aea7b9c5d33db403bed1 :[ Probably other specs are broken too. T_T

**Comment by tabatkins** [comment]
Wow, jeezus, how did I forget to update the actual links? Definitely bad on me, sorry about that.
