### ISSUE TITLE
[css-pseudo-4] styling the spelling error marker

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1828]
With the `::spelling-error` pseudo introduced [in css-pseudo-4](https://drafts.csswg.org/css-pseudo/#highlight-selectors), if you want for example to highlight spelling mistakes with a green wavy underline, you can do this:
```css
::spelling-error {
  text-decoration: wavy green underline;
}
```
However, this only works if the browser's original spelling mistake marker was created using the same mechanism in the UA stylesheet. If it is created some other way, what you'd get instead would be this:
![screenshot_from_2017-09-22_10-54-09](https://user-images.githubusercontent.com/113268/30741284-2b20a43a-9fcf-11e7-9458-e97e698eaa89.png)

Since that's not what the author would want, I think we should normatively require that browsers that support `::spelling-error` and `::grammar-error` must create the error indicators using these pseudos in the UA stylesheet.

**Comment by tabatkins** [comment]
That's literally the entire intent of the feature, yes, so if it's not yet clear in the text, it should be made so.

(You don't have access to the spelling/grammar checker yourself, all you have is the ability to style its output via these pseudo-elements. If your styling didn't override the built-in one, it would be 100% useless.)

**Comment by FremyCompany** [comment]
I agree

**Comment by frivoal** [comment]
Added a pull request (#1881) to try and address this based on what we discussed during the call. Feedback appreciated
