### ISSUE TITLE
[css-flexbox-1] Wrong comment about `flex` defaults

### ISSUE THREAD

**Issue by philix** [w3c/csswg-drafts#183]
In the table about the `flex` propery, the initial property is said to be `1 0 auto` (https://www.w3.org/TR/css-flexbox-1/#flex-property)

But a comment below says `The initial values of the flex components are equivalent to flex: 0 1 auto`.

**Comment by tabatkins** [comment]
As noted in the PR, the correct initial values are equivalent to "flex: 0 1 auto" (but also shorthands don't have initial values, so the spec is wrong in multiple ways right now).

**Comment by tabatkins** [comment]
And fixed now.
