### ISSUE TITLE
[css-text-3] Fix "Applies to" lines

### ISSUE THREAD

**Issue by mfluehr** [w3c/csswg-drafts#1833]
The spec draft lists the `hanging-punctuation` property's "applies to" value as "inline elements." Is this correct? This value doesn't seem to be used anywhere else.

https://drafts.csswg.org/css-text-3/#hanging-punctuation-property

**Comment by fantasai** [comment]
It's old-style (CSS2.1-era) wording for “inline boxes”. Looks like the Applies to lines in the whole spec are problematic, though, so expanding your issue to cover all of them. :)

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/3ee791a19062bab41952615b29e307c6956b7130 ! Thanks for the report~
