### ISSUE TITLE
[meta][several specs] Fix markup to not start lines with >

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1840]
Per <https://github.com/w3c/csswg-drafts/commit/6722380c13ab90dc33d7a5b5ccbff095a5610fb7#commitcomment-24667401>, several specs linebreak in the middle of a tag, starting the next line with the closing `>` character. This activates Bikeshed's new support for Markdown blockquotes, and results in some messed up HTML.

Tagging the relevant specs in labels, remove the spec from the labels when it's fixed and close the issue when they're all fixed.

**Comment by rachelandrew** [comment]
I'll fix multicol.

**Comment by frivoal** [comment]
Fixed the rest, and a few more place that had the same pattern.
