### ISSUE TITLE
[css-animations] Add a way to fill in a keyframe other than the 0% or 100% keyframe using the underlying style

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#1842]
Currently if you don't have a 0% or 100% keyframe, a keyframe is synthesized using the un-animated / underlying animated style (see #1841). It's odd, however, that this behavior only ever applies at the endpoints and you can never, for example, have a 50% keyframe where the property value is taken from the underlying style.

**Comment by AmeliaBR** [comment]
Could we overload [the `revert` keyword](https://drafts.csswg.org/css-cascade-4/#valdef-all-revert) just a little bit more, to give it special behavior in keyframes?  It already has different behavior depending on the origin of the rule it's in, and animations are [treated as a separate origin for the cascade](https://drafts.csswg.org/css-cascade-4/#cascading-origins).

**Comment by birtles** [comment]
I think `revert` might make sense for the underlying animated style, but in #1841 I'm proposing that we use the underlying animation's style in which case I don't think `revert` makes sense (since we'd be apply other styles from the same origin).

**Comment by fantasai** [comment]
What about `revert-layer`? Essentially overloading each animation’s style rules as being a distinct “cascade layer”...

CC @mirisuzanne

**Comment by mirisuzanne** [comment]
`revert-layer` makes sense to me for this, at least on first glance.

**Comment by Loirooriol** [comment]
Already in the spec and ratified in https://github.com/w3c/csswg-drafts/issues/7083#issuecomment-1083631261 ?

**Comment by mirisuzanne** [comment]
I don't think there's anything more to do here, no.

**Comment by mirisuzanne** [comment]
Sorry, should have marked this first as pending commenter response. @birtles feel free to reopen if you think we need additional changes.
