### ISSUE TITLE
"Mirror of CSS WG Editor Draft repository" is confusing

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#1844]
The repo descriptions says that this is a mirror of a Mercurial repo, which I had taken to mean that submitting PRs here is pointless. Which repo is the sources of truth, and can this be clarified?

**Comment by plinss** [comment]
PRs here are welcome (but please make PRs from a personal fork rather than a branch in the repo). The repository is bidirectionally synced with the Mercurial repo, so both are considered "truth" and working group members can commit to either based on their tooling preferences.

**Comment by foolip** [comment]
How can they both be the source of truth? Has it just never happened that both repos have been updated at the same time to create a conflict? (I'm assuming both repos are supposed to have exactly the same commits, not just end up in the same end state.)

**Comment by plinss** [comment]
> How can they both be the source of truth?

That's simply the nature of distributed version control systems. There's nothing about any repo that makes it more "truthy" than another (aside from an imposed human convention).

> Has it just never happened that both repos have been updated at the same time to create a conflict? 

Yes, just like if I commit to a local repo around the same time as you do, then we both push. It's just branches that get merged (or rebased).

> (I'm assuming both repos are supposed to have exactly the same commits, not just end up in the same end state.)

Again, they do get the same commits, after all the pushing, pulling and merging is done. Just the nature of DVCS.

**Comment by foolip** [comment]
It sounds like the shape of DAG will not be the same, though, so that if one converted one of the repos to the other VCS, one wouldn't end up with the same thing. That's fine I guess.

Can this be documented? And can the fact that a Mercurial mirror exists be hidden in that documentation, so that newcomers don't need to wonder if contributing on GitHub is OK?

**Comment by plinss** [comment]
If someone does a local hg<->git conversion at the moment the outputs won't match, but that's only because as the hg-git sync tool has versioned over the years the output has been altered, so changeset hashes wont match unless the same versions are used for the same changesets. But we don't support that workflow (and there shouldn't be an end-user need, they can simply clone the other repo).

I'm happy to take a PR for the README :-) Otherwise I may take a crack at some improved wording when I get the chance.

**Comment by foolip** [comment]
I've sent https://github.com/w3c/csswg-drafts/pull/1846. That and changing the repo description to just "CSS Working Group Editor Drafts https://drafts.csswg.org/" would fix this issue in my estimation.

**Comment by plinss** [comment]
Done

**Comment by foolip** [comment]
Thanks, that's much better!
