### ISSUE TITLE
[css-counter-styles] Content language, not document language

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#1845]
Here's the original request:

> 3.9 Speech Synthesis: the speak-as descriptor 
> http://dev.w3.org/csswg/css-counter-styles/#counter-style-speak-as 
> 
> I guess that 'in the document language' actually means in the language most recently declared for the text where the counter appears, which may not be the same as that declared for the document as a whole. 
> 
> if that is indeed what is meant, i such we make an editorial change to replace 'in the document language' with something more precise. 
> 
> (btw, bullets is the only value that doesn't say 'in the document language", but i think it or its replacement is equally applicable here. If the list is in French, the French word for the UA defined phrase needs to be used.)

Here's the thread:
https://www.w3.org/Mail/flatten/index?subject=i18n-ISSUE-362&list=www-style

Here's the commit:
https://github.com/w3c/csswg-drafts/commit/e277d2dbe3e6191e9d64ec45ec3d27726ad0ad3c

**Comment by fantasai** [comment]
Hi @r12a, this is the element that generates the counter, so the list-item element.

Bullet lists don't use counters. That's just regular generated content.
