### ISSUE TITLE
[css-values] Wrong autolinks

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1854]
In https://drafts.csswg.org/css-values-3/#integers :

> The first digit of an integer may be immediately preceded by - or + to indicate the integer’s sign.

'+' links to the next-sibling combinator, which is incorrect here.

There are also some other similar errors in this specification, for example, '+' in `<number>`, `*` in `calc()` etc.

**Comment by tabatkins** [comment]
Ah, those probably shouldn't be autolinks at all; I'm just trying to style them in the CSS fashion. Will change them.

**Comment by fantasai** [comment]
Fixed, thanks!
