### ISSUE TITLE
[agenda] [schedule]  W3C Recommendation plans

### ISSUE THREAD

**Issue by ppKrauss** [w3c/csswg-drafts#1860]
[css-break-3](https://www.w3.org/TR/css-break-3/) is a "W3C Candidate Recommendation" since  9 February 2017. As section "Status of this document", the  document is intended 

> to become a W3C Recommendation (...) will remain a Candidate Recommendation at least until 1 May 2017

so, there are a date for "become a W3C Recommendation"?  Can be 2018, 2019... Or is necessary to be 2017?

**Comment by fantasai** [comment]
The date there is a minimum period for CR, not the expected time it will remain in CR. The CSSWG generally avoids giving an expected completion date for anything as they are pretty much always very, very off.

p.s. Discussions that aren't spec issues should probably go on www-style.

**Comment by ppKrauss** [comment]
Hi @fantasai , the *issue* here is a suggestion to edit README including a brief explanation, like your paragraph,  about  "no expected completion date". It is simple and a very important information (for all public and any one that is thinking to elaborate an issue to add here).
