### ISSUE TITLE
[css-print][meta] css-print left unnumbered

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1862]
Despite [the great numbering](https://github.com/w3c/csswg-drafts/commit/b667648046860289ec447feddbad987969929ed2), css-print's directory is still unnumbered.

Simple oversight, or was there some reason to leave it out?

**Comment by tabatkins** [comment]
It's not a module and will never be updated; I also left css-mobile and similar alone.

**Comment by frivoal** [comment]
Ah, oops. I mistook it for css-page. Makes sense now.
