### ISSUE TITLE
[css-grid] New stretch "auto" tracks steps needs more text for indefinite height grid containers

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1866]
In issue #1150 we added a new step to the Grid Track Sizing algorithm: [11.8. Stretch auto Tracks](https://drafts.csswg.org/css-grid/#algo-stretch).

We've implemented that in Blink and WebKit but found a [regression](https://bugs.chromium.org/p/chromium/issues/detail?id=773625) due to this change.
The example is really simple (the trick is in the `min-height` part):
```html
<div style="display: grid; min-height: 200px; border: solid thick;">
  <div style="background: cyan; font: 20px/1 Monospace">item</div>
</div>
```

![Current status vs expected one](https://user-images.githubusercontent.com/11602/31539680-a7a6bc98-b009-11e7-9aa3-9a81bb649a24.png)

In this case the height of the grid container is indefinite, the size of the row is calculated as the height of the text (20px) . Then when we are in the *Stretch auto Tracks* step we don't stretch the track as the free space is not definite.
The expected result is that the row has 200px height, however it has just the text height (20px).

The problem is that this new step lacks some text like the one we have for [flexible tracks](https://drafts.csswg.org/css-grid/#algo-flex-tracks):
> If using this flex fraction would cause the grid to be smaller than the grid container’s min-width/height (or larger than the grid container’s max-width/height), then redo this step, treating the free space as definite and the available grid space as equal to the grid container’s content box size when it’s sized to its min-width/height (max-width/height).

I believe we'd need to add something like this to the new step too, to avoid this issue.

**Comment by tabatkins** [comment]
Fixed, thanks! Let us know if the edits are adequate.

**Comment by mrego** [comment]
Thanks for the quick fix, the text looks good to me.
I'd add a new test case with the fix in Blink.

**Comment by mrego** [comment]
Test case added in w3c/web-platform-tests#7782.
