### ISSUE TITLE
[css-contain] Clarify style containment effect 1

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1872]
I don't understand what the first effect of [style containment](https://drafts.csswg.org/css-contain/#containment-style) is supposed to do.

> The following properties must have no effect on descendants of the element:
> - `break-*` (and the related aliases)
> - `bookmark-*`
> - `string-set`

For starters, the definitions of `bookmark-*` and `string-set` don't make sense (see #1830 and #1829). In fact I think the whole CSS Content spec should be marked as "Not ready for implementation" or something until it is rewritten. So I don't think these properties should be mentioned in CSS Contain, which is a CR.

So let's focus on `break-*`. I don't understand the effect. Does it mean that `break-*` properties in selectors that match descendants do not have any effect? Or that `break-*` property values on the contained element don't affect descendants? For example, from [unforced breaks](https://drafts.csswg.org/css-break-3/#unforced-breaks),

> if all of them are `auto` and a common ancestor of all the elements has a `break-inside` value of `avoid`, then breaking here is not allowed.

If this ancestor is the contained element, does it mean that `break-inside: avoid` has no effect, is treated as `auto`, and thus a break between its descendants is allowed?

If so please clarify the sentence to something like

> The following properties, when set on the contained element or one of its ancestors, must have no effect on descendants of the element

But then I'm not much sure about how this is different from [scoped properties](https://drafts.csswg.org/css-contain/#scoped-property) described in effect 2.

**Comment by frivoal** [comment]
I've made the editorial changes based on the previous discussion (move some effects of style containement from css-contain to css-content, clarify that `break-*` means `break-after` and `break-before`, not `break-inside`), but we still need to resolve whether or not style containment affects `break-before` and `break-after`.

Based on the discussion minitued above, I think a good case has been made that it should not, and that we should remove that from the spec, but @tabatkins seemed to think that maybe it should.

Agenda+ to sort this out. @tabatkins if you have not changed your mind, please have some arguments ready.

**Comment by Loirooriol** [comment]
Fixed in 763c0f1fc2d4e23a9f71f748e0371bd5ef244f48
