### ISSUE TITLE
[css-foreground] It's like color but innovative

### ISSUE THREAD

**Issue by Array23** [w3c/csswg-drafts#1874]
So instead of having color, we would be taking pixels, from layer, and basically I know knock out text is possible in css, but it taxes some efforts to make, and it's not so layerable...

**foreground**
So first we have a **foreground( _boxfill_ element )** than we add up color(possible rgba) on it.
Box fill is something like color, or image url, svg, anything... Possible of multiple overlaying layers...

We take where font is and apply knock-out text on foreground, so we'll have foreground in text's pixels only... Like knock out text...

**Comment by tabatkins** [comment]
It sounds like you're asking for the [Fill & Stroke spec](https://drafts.fxtf.org/fill-stroke/).
