### ISSUE TITLE
[css-boxfill] Boxfill

### ISSUE THREAD

**Issue by Array23** [w3c/csswg-drafts#1876]
```
background: 
      layer( url('img-background') ).opacity(0.6).method(multiply),
      layer( #232323 )
      ;

```
bottom layer at the bottom;
```
    layer(<what we can now write in background>)[.opacity / decimal or percentage, depends if ends up with '%'].mode(<blending mode>) ]
   layer(/// more background layer... lower layer... you know background in [background/foreground concept of each layers would be typed later])
```

could be used on foreground also, you know what I mean... I have written about foreground elsewhere...

**Comment by Array23** [comment]
This layer stacking could be actually processed on additional singleton stacking processing unit, so it would get done just once for the internet, and you would result having something like having compacted it into prerendered images.

Every later could also be associated with GIMP BATH querry string, that thing would actually get all opensource gimp layer and selection processing, and proccess it from a fail, it would load a file, could lazy load(animate_into) lazy processed layer. It would lead to really dynamic design, that could have content related associations... (INTERNET WOULD DREAM IN PICTURES RELATED TO CONTENT)

**Comment by Array23** [comment]
I really miss GIMP in CSS and I really miss css in GIMP...

**Comment by tabatkins** [comment]
It looks like you're asking for the [filter() function](https://drafts.fxtf.org/filter-effects/#FilterCSSImageValue), which luckily already exists!

---

(Tangent: the `[css-foo]` tags at the start of the issue are meant to be existing CSS spec shortnames usually, to help people filter things in their email. Making up your own terms doesn't help; either use the correct spec tag, or add a tag at all.)

**Comment by Array23** [comment]
You can use that filter on the layer if you want, but filter is not layer you can filter, you should get more into semantics and spatial lingluistics.

**Comment by Array23** [comment]
Also filter and fill are function for SVG. I'm not using SVG and I don't want to. I want my text to be filtered and foregrounded be H1 and nothing else. You just want to write more code, so demand to replace you by machine would be bigger.
