### ISSUE TITLE
[css-inner-navigation] Brackets, calc()

### ISSUE THREAD

**Issue by Array23** [w3c/csswg-drafts#1877]
First we need to have some blocks...
```
div {
?:(~selector)-abc;
 heigh: 420px;
 background: #232323;
 foreground: #ececec; }{
?:abc-fonts;
 font-size: 16px;
 }
div div.class {
height: calc( (\div-abc.height / 100 )*20) // even better would be calc(<20%||0.2> of \div-abc.height);
width: calc(2 of \abc-fonts); // is 200% of whatever abc-font-size ends up to be...
```

So we have here few things 
_**#1**_
Aliases, ... `?` property is alias of bracket, that can be used in calc.
_**#2**_
Brackets,... One selector can have multiple CSS rules... // ruins backwards compatibility, but with aliasing is awesome... Can come handy when you edit css by javascript, you must unserialize and reserialize whole box, ... This makes it chunked so less resources needed... Also I'm going to write something about this in EMCA... I have some improvement, in css handling by script... It just have some backwards compatibility issues, because there are arrays in place where object is needed, also object, where faster would be array... 
_**#3**_
calc can handle different css property as number... yes, it does stuff like 100% of body - 1.61* padding of something... Makes things easier when you want to gold cut everything...
_**#4**_
background and foreground, I have mentioned that elsewhere

**Comment by tabatkins** [comment]
I can't figure out what you're trying to suggest here. It looks like multiple inter-related suggestions, but none of them are called out in enough detail for me to figure out what any of them are.

Can you separate these suggestions out, and elaborate on what each is, and more importantly, what problem you have today with your stylesheet that you are attempting to solve with each of these suggestions?

**Comment by Array23** [comment]
Read it 4 times, I don't have to write 4x longer text for somebody to understand.

**Comment by astearns** [comment]
Yes you do, when someone asks a reasonable question. I'm closing this issue because we can't figure out what you're asking for. If you're willing to be more responsive, please do open new issues (one per request).
