### ISSUE TITLE
[css-images] Poor figure

### ISSUE THREAD

**Issue by heftig** [w3c/csswg-drafts#188]
![Figure 4](https://drafts.csswg.org/css-images-3/images/pixel-art-small.png)
Figure 4 in [Example 27](https://drafts.csswg.org/css-images-3/#example-9bb15a38) seems to be a downscale of figure 8, and not, as suggested, the original image that figure 6, 8 and 10 are scaled from.

Figure 4 should be replaced with the [original hq2x demo image](https://web.archive.org/web/20131209152736/http://www.hiend3d.com/img/test_original.gif):
![HQX demo image](https://web.archive.org/web/20131209152736/http://www.hiend3d.com/img/test_original.gif)

**Comment by tabatkins** [comment]
Thanks! I couldn't find the original image, so I'm glad to get this fixed and remove the "ringing" in the image. ^_^
