### ISSUE TITLE
[css-text-3] Line breaking opportunities at the boundary of a white-space:pre inline element

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#189]
Browsers differ in behavior when faced with the following, if the line-end would normally fall between お and か (i.e. at the boundary of the `span`):

`<p>あいうえお<span style="white-space:pre">か</span>きくけこ</p>`

Live example here: http://jsbin.com/bedumox/edit?html,css,output

Firefox and Edge (and presto) allow the break between お and か. Safari and Chrome don't. Language tagging and the switching the `word-break` property between `auto` and `break-all` does not make any difference.

I suspect the Firefox / Edge behavior is correct, and the the Chrome / Safari behavior is a side effect of a bug of theirs that suppresses break opportunities at element boundaries [1][2], but I did not manage to find a justification either way in the spec for the case I am discussing here.

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=282134
[2] https://bugs.webkit.org/show_bug.cgi?id=158771

**Comment by upsuper** [comment]
I believe the behavior of Chrome / Safari is definitely wrong. Considering CSS Ruby, by default `<rb>` has `white-space: nowrap`. If line breaking is not allowed before a span with `white-space: nowrap`, then basically the whole ruby is not breakable.

Basically, I don't think `white-space` can control the boundary of the span it is set on.

**Comment by frivoal** [comment]
@upsuper I agree. Next question: do you see something in the spec that already says that? Maybe it is there, but I cannot find it.

**Comment by upsuper** [comment]
It seems not. I cannot find anything either. Probably the spec should explicitly state that wrapping on boundaries of an inline box is controled by its parent's `white-space`.

**Comment by frivoal** [comment]
@upsuper Yes, wrapping on boundaries of an inline box being controlled by its parent's white-space sounds like the right thing to do and the right way to say it.

@fantasai @kojiishi, what do you editors think?

**Comment by kojiishi** [comment]
I think "it's parent" is correct.

**Comment by frivoal** [comment]
Agenda+ because we seem to have a start of a consensus, and I'd like to get a resolution so that I can send a pull request and a test or two.

**Comment by frivoal** [comment]
@r12a @fantasai You should probably discuss whether or not this is i18n related rather than go back and forth on adding the label.

The effects of this bug are not language specific, but it does affect Chinese/Japanese documents (and presumably other non space separated languages) more often that it affects English or other Latin-alphabet languages.

I think it is reasonable to mark as i18n any bug that predominantly English speaking editors / WG members might otherwise dismiss as a corner case because it doesn't affect them much even though speakers of other languages may run into it often.

**Comment by r12a** [comment]
@frivoal apparently Fantasai deleted all the i18n tags by mistake. I'm reinstating here (and will look for others that need reinstating when i get time). Thanks.

**Comment by FremyCompany** [comment]
Browsers seem not to allow breaking in this case:
```<p>abc<span style="white-space:pre"> d </span>ef</p>``` (https://jsfiddle.net/x5L636t8/).

What is different about your case that makes you think breaking should be allowed?
@frivoal

**Comment by FremyCompany** [comment]
Ok, just figured out that the characters before and after the span are ideographics, which allow breaking before or after. So, since I see Firefox (first column), Edge (second) and Chrome (third) all featuring a different behavior here, I guess what we should be doing is matching Firefox, right?

![image](https://cloud.githubusercontent.com/assets/364405/17821240/7974cb2a-6605-11e6-8492-e14016f39023.png)

**Comment by frivoal** [comment]
> What is different about your case that makes you think breaking should be allowed?

If you manually convert the spaces in the span to &amp;nbsp; and shrunk the span to exclude the spaces but still include the letter in the middle, there would still be no break allowed when the surrounding text is latin, and there would still be if it is CJK. => Element boundaries should not affect the line break.

> I guess what we should be doing is matching Firefox, right?

Yes

**Comment by frivoal** [comment]
@fantasai why `Closed Rejected as Invalid` ? Didn't we resolve in favor of the white-space property having no effect at the boundaries of inline element, which should be processed according to the white-space property of the parent?

**Comment by r12a** [comment]
@fantasai please provide a rationale when closing issues. Thanks.

**Comment by fantasai** [comment]
Already covered in https://drafts.csswg.org/css-text-3/#line-break-details (third from the bottom)

**Comment by r12a** [comment]
Summary in spec:

> For soft wrap opportunities before the first or after the last character of a box, the break occurs immediately before/after the box (at its margin edge) rather than breaking the box between its content edge and the content.
