### ISSUE TITLE
[css-cascade] Incomplete (?) section on Specified Values

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#1890]
The section on "Specified Values" in CSS Cascade ([Level 3 CR](https://www.w3.org/TR/css-cascade-3/#specified), [Level 3 ED](https://drafts.csswg.org/css-cascade-3/#specified), [Level 4 ED](https://drafts.csswg.org/css-cascade-4/#specified)) currently reads:

> ### 4.3. Specified Values
>
> The specified value is the value of a given property that the style sheet authors intended for that element. It is the result of putting the cascaded value through the defaulting processes, guaranteeing that a specified value exists for every property on every element.
>
> In many cases, the specified value is the cascaded value. However, if there is no cascaded value at all, the specified value is defaulted. The initial and inherit keywords are handled specially when they are the cascaded value of a property,

And that's it, ending with a comma.  Is that just a punctuation typo, or is there supposed to be more here?  The actual content describing the special handling is in Section 7, "Defaulting", which is linked from the words "defaulting process" in 4.3.

**Comment by tabatkins** [comment]
That looks like I did indeed just trail off and not finish the sentence.

**Comment by fantasai** [comment]
Old version of the spec, for reference: https://www.w3.org/TR/2005/WD-css3-cascade-20051215/#input
