### ISSUE TITLE
[css-overflow] body overflow propagation is less defined than it was in CSS 2.1

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#1905]
CSS2.1 says (at <https://www.w3.org/TR/CSS21/visufx.html#overflow-clipping>):

> When the root element is an HTML "HTML" element or an XHTML "html" element, and that element has an HTML "BODY" element or an XHTML "body" element as a child, user agents must instead apply the 'overflow' property from the first such child element to the viewport, if the value on the root element is 'visible'.

while https://drafts.csswg.org/css-overflow-3/#overflow-propagation says:

> UAs must apply the overflow property set on the root element to the viewport. For HTML UAs, if this would result in the viewport having visible overflow, the UA must instead apply the overflow property set on the body element to the viewport.

The CSS2.1 version defines what to do when there are multiple `<body>` elements, but the draft css-overflow version does not.  This should be fixed, and web platform tests added.

**Comment by bzbarsky** [comment]
I should note that I did some testing, with both multiple `<body>` and a mix of `<body>` and `<frameset>` and UAs are not terribly consistent about implementing this stuff when there is a `<frameset>` followed by a `<body>` as in this testcase:

    <!DOCTYPE html>
    <script>
      onload = function() {
        document.body.remove();
        var f = document.createElement("frameset");
        document.documentElement.appendChild(f);
        var b = document.createElement("body");
        b.style = "overflow: scroll; margin: 100px; width: 100px; height: 100px; border: 1px solid green; position: absolute; top: 0; left: 0";
        b.textContent = "The body should NOT have a scrollbar, while the viewport should have one";
        document.documentElement.appendChild(b);
      }
    </script>

Observed behavior is:

1. Safari doesn't apply the scrollbar style to the body, but doesn't propagate it to the viewport either.
2. Firefox applies the scrollbar style to the body and does not propagate to the viewport; I am fixing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1411138
3. Chrome applies the scrollbar style to the body and does not propagate to the viewport.
4. Edge applies the scrollbar style to the body and does not propagate to the viewport.

None of these are compliant with the CSS 2.1 spec at all...

**Comment by frivoal** [comment]
Since we do not have full interop, we have room to decide what is preferable. Agenda+ to get the CSSWG to talk through this.

**Comment by bzbarsky** [comment]
For what it's worth, Firefox will be shipping the CSS2.1 behavior next month.  I believe this behavior makes the most sense, because it matches the definitions cssom-view uses for https://drafts.csswg.org/cssom-view/#the-html-body-element and interacts sanely with https://drafts.csswg.org/cssom-view/#potentially-scrollable

Otherwise, the CSSOM definition of "potentially scrollable" would not match what's actually going on with overflow style propagation to viewport.  In other words, we could have a situation in which the `<body>` has scrollbars (separate from the viewport) but is not "potentially scrollable" from the cssom-view point of view.

**Comment by frivoal** [comment]
So, the proposal would be to update overflow-3 to match CSS2.1 on this. If others agree, I'm OK with it as well.
Presumably, the Gecko update came with some tests. Could I interest you in submitting them to wpt if we resolve in agreement to your suggestion?

**Comment by bzbarsky** [comment]
> So, the proposal would be to update overflow-3 to match CSS2.1 on this.

Sounds good!

> Could I interest you in submitting them to wpt

Yes, you could.  :) In fact, I did that already, as part of the Gecko fix.  See reftests at <http://w3c-test.org/css/CSS2/visufx/overflow-propagation-001a.html>, <http://w3c-test.org/css/CSS2/visufx/overflow-propagation-001b.html>, <http://w3c-test.org/css/CSS2/visufx/overflow-propagation-001c.html> and reference at <http://w3c-test.org/css/CSS2/visufx/support/overflow-propagation-001-ref.html>.  I figured adding tests testing the CSS2.1 behavior under css/CSS2 was reasonable...

**Comment by bzbarsky** [comment]
Oh, and I guess Safari passes those tests too, in spite of not propagating to the viewport.   Writing reftests with overflow:scroll vs overflow:hidden is complicated because of scrollbar auto-hiding on various OSes... :(

**Comment by frivoal** [comment]
So the tests you submitted check part of the problem, but not the whole thing. As far as I can tell, the missing tests do not exist in the old CSS21 test suite either. Do you want to write them and I review, or does the other way around sound more attractive?

Either way, I've filled https://github.com/w3c/web-platform-tests/issues/8694 to keep track of the missing tests. Let's refocus this bug on fixing css-overflow.

**Comment by bzbarsky** [comment]
> Either way, I've filled w3c/web-platform-tests#8694 to keep track of the missing tests

I'll follow up there.  Thanks!

**Comment by frivoal** [comment]
@fantasai said (in a mail):
> This one really doesn't need WG time. We should just fix the spec to match 2.1.

I put it on the agenda on the odd chance that there was a reason for the spec being the way it now is. Since it looks like there's not need for discussion, I'll just fix this.
