### ISSUE TITLE
[css-ui-4][css-sizing] Moving box-sizing to the right spec

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#1906]
CSS-UI  has a [section defining box-sizing](https://drafts.csswg.org/css-ui-4/#box-sizing). It's in this spec because we expected CSS-UI-3 to be the first to reach REC. Now that we're resolved to take it to PR, that part of the plan is mostly complete. But box-sizing does not really belong in there.

Moreover, it is currently written as a monkey-patch over the relevant sections of CSS2.1, which is really hard to read (and easy to overlook when reading 2.1).

We should probably move the relevant sections of 2.1 to css-sizing, with the box-sizing patch applied, maybe with some modernizing of the terminology (some adjustments might be in order to keep up with the more precise terminology we use these days, or to take the new vocabulary introduced by writing modes / logical properties into account as well).

Once that's done, CSS-UI-4 can just keep a stub pointing people who got there via a permalink to the new home of that property.

**Comment by tabatkins** [comment]
I'm fine with this. @fantasai, any objections?

**Comment by tantek** [comment]
Also fine with this.
