### ISSUE TITLE
[css-ruby] White space collapse between ruby annotations

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1909]
Copy from [my email to www-style](https://lists.w3.org/Archives/Public/www-style/2015Jul/0091.html):
> It seems the current spec is not very clear about how white space collapse should happen on ruby annotations.
>
> There is a sentence says "Where undiscarded white space is collapsible, it will collapse following the standard white space processing rules", but I don't find anywhere mentions the normal white spaces inside ruby annotation.
>
> Let's see an example. If we have a ruby tag like:
> ```
> <ruby>
>   <rb>a</rb><rb>b</rb>
>   <rt>x␣</rt><rt>␣y</rt>
> </ruby>
> ```
>
> If we consider the two ruby text boxes are in the same line, and thus use the standard processing rules to handle the white spaces here, we would get the same result as:
> ```
> <ruby>
>   <rb>a</rb><rb>b</rb>
>   <rt>x␣</rt><rt>y</rt>
> </ruby>
> ```
>
> But it doesn't seem to make sense having a different result between this code and
> ```
> <ruby>
>   <rb>a</rb><rt>x␣</rt><rb>b</rb><rt>␣y</rt>
> </ruby>
> ```
>
> Hence I propose that we do not collapse white space across the boundary of ruby text box.

**Comment by upsuper** [comment]
@kojiishi's [reply](https://lists.w3.org/Archives/Public/www-style/2015Jul/0220.html):
> Yeah, so Xidorn's point is that two different way to write markup for the same semantics causing difference, which does make sense to me.
>
> Is this from real use cases? While it logically makes sense, I guess the use of spaces in ruby is rare, and putting spaces at the begin/end of <rt> is even rarer that I'm not excited to add special casing here.

And [my reply](https://lists.w3.org/Archives/Public/www-style/2015Jul/0223.html) to Koji:
> No, not from real use cases. I noticed this when I was fixing some bug related to ruby with whitespace, and the behavior I proposed is what Gecko currently implemented.

**Comment by upsuper** [comment]
Since whitespace should rarely show up in ruby annotations, especially at the beginning, we can probably just ignore it, or mention that it is implementation-dependent?

**Comment by fantasai** [comment]
> Since whitespace should rarely show up in ruby annotations, especially at the beginning, we can probably just ignore it, or mention that it is implementation-dependent?

White space is important for annotations that aren't CJK, though. :)

The spec currently implies that white space collapses across annotations which are adjacent in the markup, and this is I think appropriate. It also implies that they don't collapse across annotations which belong to different ruby segments, and I think this is also appropriate. When annotations and bases are adjacent in the source markup, they're assumed to be part of the same "word", and are allowed to collapse together depending on 'ruby-merge'. For separate ruby segments, however, we don't know whether the author intended them as separate words or not and have to assume they're independent.

What we don't cover though is handling white space collapsing at the beginning and end of a segment. Should that collapse away? If there is a need to keep some spacing between the segments, it could maybe be handled by https://github.com/w3c/csswg-drafts/issues/3498 ...

**Comment by upsuper** [comment]
That's fair. I guess we can probably close this then.
