### ISSUE TITLE
[css-sizing] Defer 'stretch' and 'fit-content' keywords to level 4

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1912]
<https://drafts.csswg.org/css-sizing-3/#size-keywords>

@fantasai and I have been reviewing the 'stretch' keyword, and in the process touching the 'fit-content' keyword (as it relies on a similar concept), to try and resolve #1614 and #1733. We're hitting a lot of confusing issues, tho, and still haven't given a lot of thought to how this should integrate with "contain" sizing.

We'd like to just go ahead and punt both of these features to level 4, so we can get level 3 cut and shipped to CR in a timely manner.

(We'd like to keep the fit-content() function - it doesn't have any of these problems, and is very straightforward to define and implement; it's just built directly on top of the min-content/max-content keywords.)

**Comment by fantasai** [comment]
Done.
