### ISSUE TITLE
[css-sizing] Restrict 'stretch' and 'fit-content' to width/height and max-*

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1913]
The definitions of `stretch` and `fit-content`/`fit-content()` don't seem to make any sense for the `min-*` properties, or at least have extremely minimal use-cases (we can't think of any) and so aren't worth the effort of impl/testing.

We've gone ahead and removed them from the propdefs, just need WG approval for it.

**Comment by jensimmons** [comment]
I'd like to comment, but do not understand the issue enough.

`fit-content` = `min(max-content, max(min-content, <length-percentage>));`

Are you talking about removing the `max(min-content,` part?
And just make it `minmax(max-content, <length-percentage>);`?

Or I could ask it this way: How does `fit-content` use a minimum value now? I didn't think it did. Or, er, what does this mean:
> The definitions of stretch and fit-content/fit-content() don't seem to make any sense for the min-* properties

Explanation needed. Thanks.
