### ISSUE TITLE
[css-scoping-1] Specificity of :host, ::slotted, and :host-context doesn't seem to be defined?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#1915]
Which is important for cascade order.

I think there are similar issues with other selectors like `:matches` and such, but those seem to have been resolved (I think?) and now matches is defined as:

>  The specificity of a :matches() pseudo-class is replaced by the specificity of its selector list argument. (The full selector’s specificity is equivalent to expanding out all the combinations in full, without :matches().)

Anyway. Blink calculates it dynamically based on the biggest specificity of the compound selectors that match. But as far as I can tell there's no spec that defines this (sorry if I overlooked it).

There's a problem with calculating specificity dynamically, which is that doing it converts the specificity not in just a function of the selector, but also in a function of the element, which is unfortunate (specially since that affects style sharing, since you can't assume that proving you match all the same selectors you have the same style, you also need to prove you match the exact same sub-selectors).

Also, doing it in a way that is not inconsistent requires matching through all the selectors, instead of just one, which isn't particularly great, but also not a big deal I suppose.

**Comment by Loirooriol** [comment]
Related: #1027 and #1170

**Comment by tabatkins** [comment]
My thought was just that it would have the standard specificity of a pseudo-class, and the contained selector wouldn't matter; that's why nothing else is specified, so it's covered by the Selectors default.

**Comment by emilio** [comment]
> My thought was just that it would have the standard specificity of a pseudo-class, and the contained selector wouldn't matter; that's why nothing else is specified, so it's covered by the Selectors default.

That definitely works for me, but it's not what Blink implements, nor WebKit, cc @rniwa

**Comment by emilio** [comment]
@lilles do you have any opinion here?

**Comment by lilles** [comment]
Having the same specificity for the two rules below sounds unfortunate to me as I can imagine you'd want to do host overrides on classes/attributes on the host element, but I don't know to what degree it's used in practice:

:host(.pink) { color: pink }
:host { color: green }

**Comment by notwaldorf** [comment]
I have definitely seen a pair of `:host {...}` and `:host{.pink}` selectors for custom elements for theming apps, so I definitely think that's a case to consider.

**Comment by emilio** [comment]
Sure. This is only relevant if `:host` came later of `:host(.pink)`, but I agree. I just want to get this spec'd. Presumably this can be resolved at the same time as #2271, and ideally with #2158, to avoid going back to eternal discussion like #1027.

**Comment by emilio** [comment]
Oh, the incompatibility is more subtle:

```html
<!doctype html>
<div id="host"></div>
<script>
  host.attachShadow({ mode: "open" }).innerHTML = `
    <style>
      :host div[foo] {
        width: 100px;
        height: 100px;
        background: green;
      }
      div[foo] {
        background: red;
      }
    </style>
    <div foo></div>
  `;
</script>
```

Gecko shows red because it accounts the `:host` pseudo-element specificity plus the inner selector's specificity. Blink only seems to account for the inner selector's specificity only.

Is this expected? I'd expect the specificity to be added, and thus `:host div` be a more specific selector than `div`.

**Comment by emilio** [comment]
Turns out I had reported this to blink before... https://github.com/w3c/csswg-drafts/issues/1915

**Comment by rniwa** [comment]
FWIW, WebKit also renders it green.

**Comment by emilio** [comment]
Yeah, I gave up and fixed it on Blink, before it keeps biting us.

**Comment by emilio** [comment]
I think it would though, wouldn't it? The specificity of `*` is zero.

**Comment by emilio** [comment]
In any case, I agree this is inconsistent with `:matches` and `:not`... I guess we need another discussion about this? I think in this case it makes sense to account for the `:host` specificity as well because `:host` is (unlike `:not` / `:matches`) selecting something, instead of just applying a union or negation operation to another selector.

So it makes more sense IMO to treat it as `div:host` would be treated than as `:matches(div)` is.

**Comment by lilles** [comment]
I'm fine with whatever includes the specificity of the sub-selectors, but I think we need to explicitly specify it in the spec. The non-functional :host follows from pseudo class specificity, but :host() doesn't, I think.

**Comment by emilio** [comment]
Yeah, that's fair. I'll add this back to the agenda to get that point clarified.

To be clear, the question is whether the specificity of `:host(<selector>)` should be the specificity of `:host` + the specificity of `<selector>`, or just the specificity of `<selector>`.

WebKit and Gecko do the first right now, Blink does the second. Testcase is:

```html
<!doctype html>
<div id="host"></div>
<script>
  host.attachShadow({ mode: 'open' }).innerHTML = `
    <style>
      :host(*) div {
        width: 100px;
        height: 100px;
        background: green;
      }
      div {
        background: red;
      }
    </style>
    <div></div>
  `;
</script>
```

**Comment by lilles** [comment]
Yes. There is also ::slotted() which is a pseudo element. Is there a separate issue for that one?

**Comment by emilio** [comment]
I don't think so, guess we can discuss it here as well. Though I think `::slotted` doesn't really matter because its specificity IIRC can't conflict with something that isn't another `::slotted` selector.

**Comment by smfr** [comment]
@rniwa any opinion?

**Comment by bathos** [comment]
In Chrome, using `adoptedStyleSheets` for what I would expect is a core use case — a common reset sheet used by various elements with shadow roots — I was surprised to find that if the common reset sheet has e.g. `* { foo: bar }`, then no `::slotted(...)` rule can override `foo` for any element, except through use of `!important`.

Is that consistent with the currently specified behavior, or is this a Chrome-specific issue? It’s not clear to me from reading this thread what the decision was.

**Comment by lkraav** [comment]
> Is that consistent with the currently specified behavior, or is this a Chrome-specific issue? It’s not clear to me from reading this thread what the decision was.

Yep, global styles are higher specificity than `::slotted()`

**Comment by lilles** [comment]
> > Is that consistent with the currently specified behavior, or is this a Chrome-specific issue? It’s not clear to me from reading this thread what the decision was.
> 
> Yep, global styles are higher specificity than `::slotted()`

Strictly, specificity is not the correct term here, it's about the cascading order and the cascade criteria added here:

https://drafts.csswg.org/css-scoping/#shadow-cascading

* {} and ::slotted() are never compared wrt specificity. If they are in the same shadow tree, they will never match the same elements, and if they are in different trees, the mentioned cascading order will take precedence over specificity and !important is the only way to make the other rule apply.

**Comment by bathos** [comment]
Yep, I was talking about scenarios where the slot content belongs to one shadow (with the reset adopted) and the slot (and the use of `::slotted()`) belong to another (which also has the reset adopted, though that doesn’t contribute to the effect).

This behavior seems to mean a lot of what would normally go in a generic, shared reset sheet isn’t viable with custom elements unless one can say for sure that they don’t and will never need to (for example) set a border color on a slotted input element or a font-weight on a slotted h2.

However I see now that this isn’t the same as the issue this thread concerns. Thanks for clearing it up.

**Comment by ExE-Boss** [comment]
See also: #3995

**Comment by jorgecasar** [comment]
@lilles how can solve this situation?

```html
<style>
/* extract from reset.css */
h1 {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}
</style>
<fancy-heading>
  # shadow-dom
   <style>
      ::slotted(h1) {
        font-size 2rem;
        margin-bottom: 1rem;
      }
  </style>
  #/ shadow-dom
  <h1>My title</h1>
</fancy-heading>
```

You can't override that from the `fancy-heading` Web Component. Both are applying to the same element in the tree and always won the specificity war the external stylesheet.

I guess that should be a way to win this war from the web component to avoid side effects. At least, `::slotted(h1)` should win

Full example here:

https://webcomponents.dev/edit/eQFJPlOvQMIuUZj71ohV/README.md

**Comment by emilio** [comment]
If you want to override it from the component, that's what `!important` is for.

**Comment by jorgecasar** [comment]
Then I will have mi components styles plenty of `!important` to ensure the consistency of my Design System.

And If I open muy styles with `::parts()` the user should use `!important` to override the values again.

I had to move all elements from light DOM to shadow DOM to ensure styles are applied without external surprises because I don't want to have my code plenty of `!important`.

I guess it was not well resolved the style management of the light DOM. Or at least the spec is not clear and all devs I ask thought that `::slotted(h1)` should win the `h1` in global styles.

I hope we can define other way in the future to improve de Developer Experience.

**Comment by jorenbroekema** [comment]
That indeed makes for some truly terrible developer experience for custom elements using ShadowDOM, as it would require me to rewrite all my styles that use `::slotted` to have an `!important` out of precaution, to prevent that global stylesheets overrides it.

```css
.accordion ::slotted([slot='invoker']) {
  margin: 0;
}

.accordion ::slotted([slot='invoker'][expanded]) {
  font-weight: bold;
}

.accordion ::slotted([slot='content']) {
  margin: 0;
  visibility: hidden;
  display: none;
}

.accordion ::slotted([slot='content'][expanded]) {
  visibility: visible;
  display: block;
}
```

becomes:

```css
.accordion ::slotted([slot='invoker']) {
  margin: 0 !important;
}

.accordion ::slotted([slot='invoker'][expanded]) {
  font-weight: bold !important;
}

.accordion ::slotted([slot='content']) {
  margin: 0 !important;
  visibility: hidden !important;
  display: none !important;
}

.accordion ::slotted([slot='content'][expanded]) {
  visibility: visible !important;
  display: block !important;
}
```

That also means that if I have a web component extension class that wants to extend my component with overrides, they themselves will be forced to do the same thing as well.

I would definitely prefer it if:

```
Specificity of ::slotted() is 1 pseudoclass + specificity of argument.
```

Similar to `:host`, for pretty much the same reasons.

**Comment by jorgecasar** [comment]
@jorenbroekema other way is to use custom properties everywhere because I just tested, and once you put `!important` in your component, there is no way to override it from outside.

It's really painful if you want to build a Design System using the light DOM. It seems standard is forcing us to put all the content in the shadow DOM, with its problems. Then we will need declarative Shadow DOM, SSR, etc...

**Comment by jorenbroekema** [comment]
> once you put !important in your component, there is no way to override it from outside.

Yeah that's a big downside since you want your users to do styling overrides on LightDOM, as this is basically their content, their territory..

So correct me if I'm wrong but you have to choose between:

- Stuff outside **always** overrides your slotted selector (default behavior)
- Stuff outside **cannot** override your slotted selector (if you use !important inside your slotted selectors)
- Custom CSS props with fallbacks as default value, everywhere 🤷 :

```css
.accordion ::slotted([slot='invoker']) {
  margin: var(--accordion-invoker-margin, 0);
}
```

**Comment by emilio** [comment]
I mean, the way `!important` was designed to work on shadow DOM was to, by default, allow the "outside" to style its stuff as it wants, but let the component use `!important` for stuff it relies on.

For the example of the accordion, it probably makes sense that, given hiding stuff is core to it, `display: none` / `visibility: hidden` should probably be `!important`. I see no reason why `font-weight` / `margin` / etc should be `!important` there unless I'm missing something though.

Anyways, it seems to me like if the current model doesn't solve some of the use-cases, those should probably be discussed in a separate new issue, rather than a 4 year old closed issue.

**Comment by jorgecasar** [comment]
Here other example. You have some generic styles for headings, paragraph, etc.. to ensure your web looks fine.

I wants component called hero for the home page or a card to list products. The will have a heading inside. I could style this elements because of the generic selector styles.

```
<fancy-hero>
  <h1>My site is awesome</h1>
  <h2>It use Web Components</h2>
</fancy-hero>

<h2>My products</h2>

<ul>
  <li>
    <fancy-card>
      <h1>Product one</h1>
      <p>It use Web Components</p>
    </fancy-card>
  </li>
</ul>
```

Currently, you have to put important in all styles of your component that apply to avoid being apply to the elements inside your components.

If you try to upgrade a legacy proyecto with tons of css your components are very fragile. And `!important` solution gets very bad press among developers.

**Comment by jorenbroekema** [comment]
One of the main reasons why I dislike `!important` so much here "as a solution" is that it forces the reliance on cascading order.

Imagine a web component and an extension of it:

```js
class FooExt extends FooEl {
  styles() {
    return `
      ${super.styles}
      
      ::slotted(#foo) {
        border-color: green !important;
      }
    `;
  }
}
```
The border color will only be green if this CSS part is later in the cascade than `super.styles`, because they both have `!important`. However, it's much cleaner if I can use CSS specificity e.g. by using an ID selector (`#foo`). This makes things less fragile and gives developers more control in my opinion, because it's a lot easier in practice to fight specificity wars than to fight cascade wars.
