### ISSUE TITLE
[css-ruby] text-orientation of bopomofo annotation

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1916]
Copy from [my email to www-style](https://lists.w3.org/Archives/Public/www-style/2015Aug/0265.html):
> I propose that we should add "text-orientation: upright" to the "rt:lang(zh-TW)" rule.
>
> The reason is that, all the tone marks in bopomofo (U+02CA, U+02C7, U+02CB, U+02D9) have Vertical_Orientation property "R" while the bopomofo characters are all "U". It means, without explicitly setting text-orientation to upright, the text run would break between them, which makes it impossible to use font feature to place the tone mark properly.

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0269.html) from @fantasai:
> I think it would make more sense to have Unicode update UTR50 to make these characters upright in mixed-orientation text (or otherwise tailor it within CSS as a whole). It's not just a problem with ruby.

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0284.html) from me:
> Well, that could be tricky, because those characters might also be used with latin scripts. I'm not sure anyway.
>
> Koji, any thoughts?

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0313.html) from @kojiishi:
> Unified code points tend to be controversial, and I'm not sure how much common these code points are in Latin usages. I can ask at Unicode ML.

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0315.html) from @fantasai:
> Latin mostly uses the combining-mark form, rather than the modifier letter form. Also for mixed vertical text, we're biased mostly towards CJK usage (which bopomofo counts as). So I think we're okay.
>
> Still would like Unicode signoff, too, of course.

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0326.html) from @kojiishi:
> One confirmation; if we were to propose a change, should the first tone mark also included? From wikipedia[1], I understand Bopomofo does not use the first tone mark but Pinyin does.
>
> Better to include but not required for Bopomofo usages?
>
> [1] https://en.wikipedia.org/wiki/Bopomofo#Tonal_marks

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Aug/0328.html) from me:
> The bopomofo handbook [1] from Taiwan says that, the first tone "can be omitted" [2]. I read this as a recommendation instead of a requirement, and thus I'd suggest if we do this change, we should also include the first tone, although it may not be used as usual as other four tones.
> 
> [1] http://www.edu.tw/files/site_content/M0001/juyin/ (Chinese)
> [2] http://www.edu.tw/files/site_content/M0001/juyin/tt4.htm?open (Chinese)

**Comment by xfq** [comment]
FYI - see recommendation from ucd-dev in [F5](https://www.unicode.org/L2/L2020/20175-utc164-properties-rec.pdf).

It will be discussed in UTC next week.

**Comment by frivoal** [comment]
It looks like UTC planned to agree with @fantasai, but I don't know where to find the actual conclusion. Could you supply a link to those? If they did, that would solve the issue.

Either way, this really is a Unicode thing, so while it is a very relevant question in general, for the purpose of css-ruby as a spec, it is out of scope, we should close.

**Comment by frivoal** [comment]
@xfq, it looks like UTC planned to agree with @fantasai, but I don't know where to find the actual conclusion. Could you supply a link to those? If they did, that would solve the issue.

Either way, this really is a Unicode thing, so while it is a very relevant question in general, for the purpose of css-ruby as a spec, it is out of scope, we should close.

**Comment by xfq** [comment]
See https://www.unicode.org/L2/L2020/20172.htm#164-A57

My understanding is that Unicode hopes to better maintain the Bopomofo encoding, rather than patching `Vertical_Orientation` to solve the immediate problems, so the proposal was that a whole Bopomofo encoding and presentation document should be submitted to Script Ad Hoc and UTC.
