### ISSUE TITLE
[css-ruby] Ruby text and browser minimal font size

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1917]
Copy from [my old email](https://lists.w3.org/Archives/Public/www-style/2015Aug/0150.html):
> Most browsers have an option called "Minimum font size" or something similar, which enables users to enforce a proper font size for them to read.
> 
> But this feature generally doesn't work fine with ruby. If the base text of ruby is not larger than the minimum font size, the ruby text would end up having the same size with its base text. It seems to be unfortunate.
>
> There are some existing workarounds for authors to ensure the minimum font size in their page not being smaller than the user setting. But generally, the "minimum font size" is for the main text, not ruby. It doesn't make sense to enlarge text of a whole page by 1x just for ensuring that ruby is shown properly.
>
> I guess that user agents should probably ignore the minimum font size setting for ruby text elements and their descendents. And this might be worth a mention in the spec.
>
> One thing I'm concerned is that, ignoring this setting on certain elements effectively opens a door to authors to completely escape from it, which might also be unfortunate.
>
> Thoughts?

**Comment by upsuper** [comment]
[Reply](https://lists.w3.org/Archives/Public/www-style/2015Sep/0001.html) from 千葉 淳一  (Chiba Junichi):
> I noticed the same thing you mentioned while I was making a ruby sample. A pair of Kanji with mono-ruby (two hiragana each) happened to have an extra space between the ruby base characters due to the browser's minimum font size.
>
> The rendering with an extra space was not what I expected.
>
> > I guess that user agents should probably ignore the minimum font size setting for ruby text elements and their descendents. And this might be worth a mention in the spec.
>
> I agree.
> The minimum size should not work for the ruby characters because of its original purpose:
> provide phonetic annotation using "ruby" sized typeface (smaller font size than the body elements).
>
> > One thing I'm concerned is that, ignoring this setting on certain elements effectively opens a door to authors to completely escape from it, which might also be unfortunate.
>
> One suggestion to keep the door small enough is to define the minimum size for ruby separately.
> I believe 50% of the minimum body size set by the user agent is one reasonable min value, regarding that the current draft mentions "typically sized to 50% when used as annotations".
> It shall be 30% for bopomofo. Or 30% for Japanese too, because somebody may want to put three hiragana for one base without adding spaces to the base characters.
>
> I wonder if there are other doors we should be aware of.

**Comment by upsuper** [comment]
> One thing I'm concerned is that, ignoring this setting on certain elements effectively opens a door to authors to completely escape from it, which might also be unfortunate.

Some new thought on this: I don't think this is something we really need to be concerned, because modern CSS already has approaches to bypass the minimum font restriction, if authors really want. e.g. they can use transform to resize the whole area to produce a smaller size.

**Comment by fantasai** [comment]
Spec currently says “UAs implementing a user-controlled “minimum font size” feature should consider scaling that minimum down for ruby annotations.” in the (informative) Default Style Sheet appendix. We could make that normative, but otherwise I think we're covered here? (There's no normative definition of the “minimum font size” currently.)

**Comment by upsuper** [comment]
The existing text sounds good. I agree that we don't need normative for this.
