### ISSUE TITLE
[css-gcpm] Editor's Draft misses link to latest published version

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#192]
The [Editor's Draft is for the CSS Generated Content for Paged Media Module](https://drafts.csswg.org/css-gcpm-3/) is missing the link to the [latest published Working Draft](https://www.w3.org/TR/css-gcpm-3/).

Other modules have a link labeled 'Latest published version:' for this.

Sebastian

**Comment by tabatkins** [comment]
Fixed, thanks.
