### ISSUE TITLE
[css-flexbox][css-sizing] Move min-width and min-height partial definitions to css-sizing

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#1920]
CSS Flexbox provides partial definitions of `min-height` and `min-width` with the new `auto` initial value.

This kind of things should not be allowed. How is someone looking for the initial value of these properties supposed to know that it's defined in Flexbox? 

So I think these definitions should be moved to wherever makes sense. Probably this would be css-box, but it seems it has been abandoned. So css-sizing seems the best option.

Then css-sizing would define `auto` as the initial value, and say that it represents the "automatic minimum size" which, unless otherwise defined by the layout model, is `0`. CSS Flexbox and CSS Grid should only define this automatic minimum size in their layouts.

**Comment by fantasai** [comment]
Makes sense to me. Agenda+ to get WG approval.
