### ISSUE TITLE
[css-grid] Percentage tracks and indefinite sizes

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1921]
This is an issue extracted from #509 (so we can leave #509 only for percentage gaps/gutters).

The behavior of percentage rows has been [modified back in September](https://github.com/w3c/csswg-drafts/commit/15cf0c6d56efdbb44383134ebe19dff672b01546) to reflect a resolution from [Seatle F2F meeting on January](https://lists.w3.org/Archives/Public/www-style/2017Feb/0061.html).
The [new text of the spec](https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-length-percentage) says:
> If the size of the grid container depends on the size of its tracks, then the `<percentage>` must be treated as auto, for the purpose of calculating the intrinsic sizes of the grid container and then resolve against that resulting grid container size for the purpose of laying out the grid and its items.

All the implementations have shipped the previous behavior (percentage rows are treated as `auto` and never resolved) and are interoperable regarding this. In addition, AFAIK nobody has updated them to follow the new behavior described in the spec.

At the same time we believe that implementing the new behavior might not be that easy, mainly because of the height is usually an output of the width, and you cannot do the same operations in both axis.

I've wrote [a codepen trying to explain one of the issues](https://codepen.io/mrego/pen/pdvWBB?editors=1100#0) which is the fact that we might need an extra pass of the track sizing algorithm to properly follow this resolution.

The problem is a combination of spanning items with percentage tracks.

* **Columns** `grid-template-columns: auto 10% auto`
  We don't find issues here, during the intrinsic width computation the percentage is treated as `auto`. In the example the columns have `84px 324px 84px`, so the intrinsic width is `492px`.
  ![Status during intrinsic phase](https://user-images.githubusercontent.com/11602/32200616-de08e03c-bdd2-11e7-886a-5667c40f5b4a.png)
  Then during the layout phase we resolve the percentage column against the intrinsic width, 10% of `492px` which would be `49px`, and the 1st and 3rd column are still `auto` so they grow as needed to fit the spanning item (final sizes are `221.5px 49px 221.5px`).
  ![Final result after resolving the percentage during layout](https://user-images.githubusercontent.com/11602/32200629-ed1b19b4-bdd2-11e7-87ad-b06cecce259a.png)

* **Rows** `grid-template-rows: auto 10% auto`
  This is the tricky part as there isn't a phase to compute the intrinsic height.
  So during layout we initially treat the percentage row as `auto`. In the example the rows are `20px 100px 20px`.
  ![Initial result while treating the percentage row as "auto"](https://user-images.githubusercontent.com/11602/32200672-21e84e00-bdd3-11e7-9240-52bfa0cd316c.png)
  Then if we decide to use that as *intrinsic* height (`140px`) the 2nd row should be resolved as 10% of `140px` which is `14px`. At this point we'll have the following rows `20px 14px 20px`, if we don't do an extra pass we'll have overflow with `auto` rows which doesn't make sense.
  ![Result after resolving the percentage track during the first pass](https://user-images.githubusercontent.com/11602/32200693-3fa41820-bdd3-11e7-8649-ee7271a0a88b.png)
  To get a good result we'd need to do an extra pass of the track sizing algorithm considering a fixed size for the percentage row, something like `grid-template-rows: auto 14px auto`. In that case the `auto` tracks will grow as needed to accommodate the sapping item (the final sizes are `63px 14px 63px`).
  ![Final good result after doing a 2nd pass](https://user-images.githubusercontent.com/11602/32200725-5eb9d5a6-bdd3-11e7-8163-1ffc138131b3.png)

The purposes of this issue are 2:
1. Verify that this is the expected behavior, and probably modify the spec accordingly to explain these extra pass (and maybe how all this can be combined with orthogonal spanning items if that brings or not more issues).
2. Check with other implementors if they're willing to support this new behavior for percentage rows (CC @atanassov and @MatsPalmgren).

Thanks for your time and sorry for the neverending story. 😇

**Comment by fantasai** [comment]
To clarify, the spec is currently written in conformance with the above resolution (see https://drafts.csswg.org/css-grid-1/#valdef-grid-template-columns-length-percentage and https://drafts.csswg.org/css-grid-1/#intrinsic-sizes). But overall what's happening doesn't seem to be very clearly described.

Afaict, we could describe what is happening as the following (which is then implemented differently in UAs in order to optimize the number of passes):

1. Size the Grid Container (per axis, for both axes)
  - If it is definite, just get that size.
  - If it is indefinite, run the grid sizing algorithm under min/max-content constraints, treating percentages as auto, in order to find the indefinite size.
2.  Size the Grid
  - Run the grid sizing algorithm under normal constraints: auto behaves as auto, and percentages resolve against the size of the grid container as calculated in step #1.

Does this seem correct, or are there shortcuts under #1 that aren't reflected here?

**Comment by mrego** [comment]
> Does this seem correct, or are there shortcuts under #1 that aren't reflected here?

Yes, probably that would be fine, despite Blink/WebKit implementation don't do that. So for us it'll imply an extra pass as described in #1 but probably that's just an implementation detail that shouldn't be considered in the spec.

Regarding this change, I've been checking it again and all browsers (Chromium, Firefox, Edge and Safari) have the old behavior (percentage rows are treated as `auto` and never resolved), so we currently have interoperability here.
We're not planing to change Blink/WebKit implementations until other browsers do it, so please @dholbert, @MatsPalmgren, @atanassov notify here when you update this.
At the same time we're going to add a use counter, as this has been working like this for a long time (3 Chromium versions, 4 Firefox versions, 1 Edge version and 2 Safari versions) and `height: auto` is the default, so we want to know how many websites will be affected if we implement this change.

**Comment by mrego** [comment]
About the use counter, it should start to appear in the following link once the initial data gets gathered: https://www.chromestatus.com/metrics/feature/timeline/popularity/2248

**Comment by tabatkins** [comment]
Okay, the number looks like it's below our informal threshold, but is rising steadily - at this rate, it'll cross the .03% in two or three months.  This is probably just rising with Grid usage in general.

**Comment by mrego** [comment]
Note that Grid Layout usage is still quite low ~0.50% yet: https://www.chromestatus.com/metrics/feature/timeline/popularity/1693

**Comment by MatsPalmgren** [comment]
I'm slightly in favor of the proposal for two reasons:
1) it does what the author asked for
2) it's symmetric to how percentage column track sizes are handled

I'd like to note though that it's a performance issue since we have to re-run the grid sizing algo (both axes) with the intrinsic size as a definite block size if there is a percentage row track size. (The usage counter above indicates that's likely rare though...)

**Comment by MatsPalmgren** [comment]
Given that we sometimes should do two passes of grid sizing, where the first pass is akin to an "intrinsic sizing" pass, I think the spec should say explicitly that both passes are supposed to run the algo under "no constraint". And that the grid container's block-axis size is definite and final after the first pass.

**Comment by mrego** [comment]
Since Firefox implemented the change for gutters (#509) for [Firefox 62](https://hg.mozilla.org/mozilla-central/rev/be1b4c042170) we decided to implement this change for row tracks together with the change for row gutters in [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=846187). And we have plans to do it in WebKit too.
In Chromium 69 there is a warning about this change of behavior that will happen in Chromium 70 that will be released in October 2018.

We analized the sites hitting the use counter, only a few (8 out of 178) were broken due to this change, and the workaround to keep the old behavior was as simple as using `auto` in the percentage rows.
We contacted those sites and explained how to fix the problem.
More info about all this in the following intent-to-implement-and-ship mail thread in blink-dev:
https://groups.google.com/a/chromium.org/d/msg/blink-dev/CJgcT4hR7Rk/58WfZNbWBQAJ

It'd be nice if Firefox and Edge implement this too, there are tests in WPT checking this changes.

**Comment by mrego** [comment]
JFYI, we have implemented the [changes in WebKit too](https://trac.webkit.org/changeset/234687/webkit).

**Comment by dholbert** [comment]
> It'd be nice if Firefox and Edge implement this too, there are tests in WPT checking this changes.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1481876 to cover this change for tracks (i.e. percent-sized grid rows) in Firefox.  (Not sure about the timeline of when we'll get to it, though.)

**Comment by fantasai** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/3418 on the clarifications suggested in https://github.com/w3c/csswg-drafts/issues/1921#issuecomment-344442739 so I can close out this issue.
