### ISSUE TITLE
[css-inline] Should initial-letter-wrap: all consider text-shadow or other effects?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1922]
Based on the twitter conversation [ending in this tweet](https://twitter.com/davidbaron/status/924503049237807104) (note that the first tweet in the thread cites a tweet that is itself a thread) I'm wondering whether `initial-letter-wrap` should consider `text-shadow` or other effects.

This example of a first-letter using a font that's somewhat like text-shadow:
![Image of first letter using font that's somewhat like text-shadow](https://pbs.twimg.com/media/DNR3giUVAAAj3-6.jpg:small)
(which comes from [this tweet](https://twitter.com/mfyfyr/status/924495300697268224)) seems relevant.  This example can't actually be done with text-shadow, I think -- it would have to be done using a specialized font.  But maybe there are similar examples that would use text-shadow?

Is it worth making implementations consider `text-shadow` for `initial-letter-wrap`, or is that too obscure?

**Comment by astearns** [comment]
This example can't be done without exclusions, as without exclusions there is no way to break up the four lines in the middle. I don't think it's generally a good idea to do this, but this example is particularly bad with these unhyphenated (and syllabically-challenged) breaks:
ex perience
expr essed

Aside from that, I can see the benefit to avoiding the ink from a text shadow. I'd probably want to see evidence that people were converting their type effects to images and using shape-outside to achieve this effect before asking browsers to bake it in.

**Comment by bradkemper** [comment]
I would expect the text-shadow to not take up space, just like box-shadow doesn’t. And use `shape-outside:polygon()` for when that isn’t enough (though that would be laborious if you had to do it for more that one paragraph).

**Comment by fantasai** [comment]
I agree with @bradkemper here. Shadows don't take up space in CSS, not even for expanding scrollable overflow. You can do this with shape-outside, or by using SVG to represent the L and calculating the shape via `shape-image-threshold`.
