### ISSUE TITLE
[css-shadow-parts] Easier same-name forwarding

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1923]
If you're forwarding a part from a sub-component, and want to just use the same name, right now you have to explicitly say "foo=>foo". That repetition seems silly for what I expect to be a common case. Should add a forwarding syntax that just reused the name.

**Comment by fergald** [comment]
This was closed by 450d6714bddcfcdd52a8e1dafeeab2c28698c78f.
