### ISSUE TITLE
[cssom] [cssom-view] Use mixins in IDL definitions

### ISSUE THREAD

**Issue by TimothyGu** [w3c/csswg-drafts#1928]
- https://drafts.csswg.org/cssom-1/
- https://drafts.csswg.org/cssom-view-1/
- Any other text defining interfaces with Web IDL

[Mixins](https://heycam.github.io/webidl/#idl-interface-mixins) have been added to Web IDL to replace the [[NoInterfaceObject](https://heycam.github.io/webidl/#NoInterfaceObject)] extended attribute + `implements` statement.

See https://github.com/heycam/webidl/pull/433.

/cc @tobie

**Comment by tobie** [comment]
Please close as duplicate of #1932 and #1931 which are automatically generated and can be tracked. (Sorry for the hassle and the noise).
