### ISSUE TITLE
[css-list] `counter()` should not be allowed in anywhere `<string>` is accepted

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1929]
Brought by @Loirooriol in [#1026 (comment)](https://github.com/w3c/csswg-drafts/issues/1026#issuecomment-341435007), CSS Lists currently says:
> Counters ... can be used by an author anywhere that accepts a `<string>`.

This can potentially be problematic given my argument in [#1026 (comment)](https://github.com/w3c/csswg-drafts/issues/1026#issuecomment-341295647).

So what needs to be resolved here would be: should the counter functions be expanded at computed-value time (so that children inherit the expanded counter rather than the counter functions themselves), or at used-value time (so that children inherit the counter functions, and only replace it with the string when the value is used for rendering).

It seems to me that both approaches have some issues.

Making counter functions expanded at computed-value time means browsers may need to invalidate computed value when some siblings or siblings of ancestors change. This is probably doable but can be complicated with little benefit. It also means we would be changing how counter functions are handled in `content` property (which is currently expanded at used-value time), but this may not be a big deal as it may only affect anything other than the returned value from `getComputedStyle`.

Having them expanded at used-value time would be a lot more troublesome as we would need to expand every place which `<string>` may be accepted to also keep the details of counter functions, and calculate them when they are used. That could be a decent amount of boilerplate code. Furthermore, consider that `<family-name>` can be `<string>`, and `font-family` is inherited, it could make font even funnier to play with (from the browser engine side).

I think basically the issue is that, allowing counter functions elsewhere outside `content` property doesn't show much usefulness, so it doesn't seem to be worth its implementation complexity.

**Comment by fantasai** [comment]
CSS2 didn't allow counters anywhere except content, so per https://lists.w3.org/Archives/Public/www-style/2015Mar/0363.html and https://lists.w3.org/Archives/Public/www-style/2015Mar/0498.html I'm cutting that out.

**Comment by tabatkins** [comment]
I don't agree with this.

Xidorn's objection is *far more general* - they're arguing for never allowing the value of a counter to be exposed in any way, except for 'content'. We need to discuss that more explicitly, rather than naively aligning with CSS2's limited definition.

**Comment by fantasai** [comment]
There are other open issues on generalizing the use of counters outside of 'content', e.g. https://github.com/w3c/csswg-drafts/issues/1026 This issue is closed.
