### ISSUE TITLE
[css-multicol] Inconsistency with margin collapsing across columns 

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#1939]
Imagine you have a series of paragraphs, wrapped in an article element. 
Each paragraph has a 1em margin above and below, `p {margin: 1em 0;}`. 
You also apply `article {columns: 4;}` to create four columns of the paragraph text. 
Here's a demo: https://codepen.io/jensimmons/pen/OOXXvW

The problem: in the first column, the paragraph does not have a collapsing top margin, so the paragraph is pushed down 1em. In the other columns, the margin does collapse. Plus, we don't really have interop across browsers for this behavior.

(In the demo, I've applied `break-inside: avoid;` as well to get the paragraphs to start at the beginning of a column. Feel free to remove it to see how things behave differently without it.)

It would make much more sense for margins to collapse in all columns, imo. If we decide we must have margins not collapsing in the first column, then we should at least make that consistent across all columns.

**Comment by dauwhe** [comment]
We depend on margins not collapsing in the first fragmentainer in paged media, and in things like EPUB reading systems where pagination is implemented via multicol. I would certainly wonder why I couldn't put a top margin on the first element. Could this use case be addressed with selectors to treat the first element differently?

**Comment by fantasai** [comment]
Note that margins are preserved at forced breaks also. It's only at implicit breaks that they disappear. There was some discussion about a property to control this, e.g. `margin-break: auto | discard | keep`. See https://lists.w3.org/Archives/Public/www-style/2009Mar/0065.html

**Comment by jensimmons** [comment]
It seems this is what the specification indents — at least such an outcome is shown in one diagram: 

![css multi-column layout module level 1 2017-11-05 22-11-18](https://user-images.githubusercontent.com/108474/32427657-636633ea-c276-11e7-9245-c0b30027fb81.jpg)

I can't see why an author would ever want this outcome, however. Developers I talk to consider this a bug, and get the impression they can't trust multicolumn.

**Comment by jensimmons** [comment]
The other place margin collapsing is mentioned is this:

> A multi-column element establishes a new block formatting context, as per CSS 2.1 section 9.4.1.
> 
> A top margin set on the first child element of a multicol element will not collapse with the margins of the multicol element.

**Comment by rachelandrew** [comment]
I think this is an area where web authors using multicol and people working with paged media are going to differ in opinion, which would make an additional property to allow a choice to be made useful.

**Comment by jensimmons** [comment]
This https://github.com/w3c/csswg-drafts/issues/253 may solve this usecase.

**Comment by fantasai** [comment]
Closed out #253, so closing this out as well since it seems to solve it. Please re-open if not. :)
