### ISSUE TITLE
[css-ui-4] Spatial Navigation needs a new home in WICG

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#1948]
Spatial Navigation likely needs to be its own spec, with markup, style, script pieces, developed in a WICG repo.

A few things to consider:
* tabindex, previous nav-index
* making things focusable (or not)
* grouping / focus-grouping
* spatial navigation within a web component, across / into / out of web components
* accessibility concerns with the above and prior approaches, e.g. https://lists.w3.org/Archives/Public/www-style/2013May/0076.html

**Comment by jihyerish** [comment]
Now we have a new home in here! :
https://github.com/WICG/spatial-navigation

**Comment by frivoal** [comment]
Closing this issue since we have the new repo in wicg. All the things @tantek mentioned still need discussing but the "needs a home" part is done.

**Comment by frivoal** [comment]
Slightly abusing the "by CSSWG Resolution"  label, but even though the word "resolution" isn't in there, here's a link to the chair saying that we should do so, based on the consensus in the room:
https://logs.csswg.org/irc.w3.org/css/2017-11-07/#e907696
