### ISSUE TITLE
[css-ui-4] Scoping navigation/focus subtrees (nav-dir, etc.)

### ISSUE THREAD

**Issue by cookiecrook** [w3c/csswg-drafts#1949]
Re-adding from https://lists.w3.org/Archives/Public/www-style/2013May/0076.html

As specified, nav-index has the same serious negative implications of positive integer values of tabindex, where in order to be specified usefully, each node has to know about the layout order of every other node in the document. If you're only specifying nav index on first level branches, this is fine, but there is no good way to use this on leaf nodes, and it has severe consequences for breaking index order of keyboard navigation.

This particular problem *might* be solvable with an additional property used on parent or ancestor nodes such as:

	nav-context:  ignore (default) | relative | absolute;

Or potentially by allowing the nav-index context to inherit and cascade. For example:

	[role="toobar"] {
		nav-index: 0; /* retain default tab order until you the user reaches this element or a descendant. */
		nav-context: relative; /* sets the root nav context for this container */
	}
	[role="toobar"] button#b1 {
		nav-index: 1; /* first focusable element within the toolbar; does not override root tab order. */
	}
	[role="toobar"] button#b2 {
		nav-index: 2; /* second focusable element within the toolbar; does not override root tab order. */
	}

**Comment by frivoal** [comment]
Based on the CSS-WG having decided to push this general topic to WICG (see [meeting minutes](https://logs.csswg.org/irc.w3.org/css/2017-11-07/#e907534)), I'm closing this issue in favor of https://github.com/WICG/spatial-navigation/issues/10.

To be clear, this is not meant to be a rejection of what has been proposed here, only moving the discussion to a group that is tailored for this problem space and to which the CSSWG has decided to move the discussion to.

This specific thread has been documented in the [wiki page dedicated to collecting discussions on this topic](https://github.com/WICG/spatial-navigation/wiki/Historical-discussions-of-reordering-sequential-navigation).
