### ISSUE TITLE
[css-scroll-snap] should scroll-snap-margin lose it's snap?

### ISSUE THREAD

**Issue by astearns** [w3c/csswg-drafts#1954]
Given #1707, does it make sense to rename scroll-snap-margin to scroll-margin? This would match scroll-padding. Taking -snap- out of the name would make it slightly less likely that people would assume it only has an effect when scroll snapping is turned on.

**Comment by fantasai** [comment]
FYI: https://www.chromestatus.com/metrics/css/popularity doesn't mention scroll-snap-margin at all. Not sure if that means there's zero or the counting is broken. :)

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/0b1ff98e52898d61044780f86d56384602397914
