### ISSUE TITLE
standardization of scrollbar color properties

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1955]
[Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=77790).

Getting an issue on file since we're discussing this face-to-face now.

**Comment by nainar** [comment]
The discussion didn't get logged here. So here is the start of the IRC log: https://logs.csswg.org/irc.w3.org/css/2017-11-07/#e908987

**Comment by dbaron** [comment]
Fixed by f20b12113eef2bb86bb068b0272cb34163e4bea9

**Comment by tantek** [comment]
https://drafts.csswg.org/css-scrollbars-1/
