### ISSUE TITLE
[css-multicol] Referring to the multicol element / container

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#1965]
In the current multicol Working Draft the element that has `column-count` or `column-width` applied is referred to as the multicol _element_. In the discussions at TPAC @fantasai noted there is some confusion around what we call this element.

I noted that people were often referring to it as the multicol _container_ in the meeting, which matches how we talk about flex and grid containers.

The current definition is [here](https://drafts.csswg.org/css-multicol-1/#the-multi-column-model).

It seems that it would make sense to describe the multicol element/container in the same way as flex and grid, raising this issue for discussion of that.

**Comment by frivoal** [comment]
Makes sense. So something like this?

```
A <dfn lt="multi-column container|multicol container" export>multi-column container</dfn>
(or <em>multicol container</em> for short)
is the box generated by an element whose 'column-width' or 'column-count'
property is not ''column-width/auto'' and therefore acts as a container for
multi-column layout.
```

**Comment by rachelandrew** [comment]
Yes, essentially editing mention of _element_ to _container_ where it is used in this context.

Is this something we need to bring to a meeting? If so I could add it to the agenda for the next call.

**Comment by FremyCompany** [comment]
+1

**Comment by jensimmons** [comment]
I’m all for this. “Container” is now the defacto word for a parent element where the formatting context / layout method is changed. Multicolumn element sounds old and out of date. Multicolumn container sounds like “hey maybe I should take a look at that thing again.”

+1

**Comment by astearns** [comment]
I'm happy to bring this up on a call and get a resolution for this, but I think in general a resolution should not be required for this kind of change. I'm assuming there is no normative requirement for implementations being modified here - it's just spec terms we're changing for clarity.

(and I'm +1 as long as well all agree never to coin a 'multicoltainer' term)

**Comment by fantasai** [comment]
Hi @rachelandrew, Tab and I made a couple changes to complete this issue (letting you know for future reference, if you need to change an exported term):

- We added an oldids attribute to the `<dfn>` for multi-column container so that old links to that definition won't break with the terminology change.
- We update all the other specs in the repository (except for css-box and css-template which are unmaintained and outdated) to refer to the new terms.
