### ISSUE TITLE
[css-multicol] Should reference to breaking values be removed from the introduction?

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#1966]
Since the CR of 2011 the break properties as defined for multi-column layout have been moved to the css-break specification.

In the [introduction](https://drafts.csswg.org/css-multicol/#introduction) to the multicol specification, in the section describing new properties and values is Example 7, referring to the new values of `column` and `avoid-column`. As these are now defined in the fragmentation module and not here, I'm suggesting we remove this from the introduction here or change the reference to point to css-break, mentioning that fragmentation information is detailed there.

**Comment by frivoal** [comment]
Section 5 needs to stay, to redirect people to the right place if they came here from a link looking for the break properties, but for the rest, I agree with you that this is no longer the right spec to introduce them.

**Comment by rachelandrew** [comment]
yeah I wasn't intending to remove section 5 - just that bit of the intro which is a bit odd now the values aren't _introduced_ in this spec.
