### ISSUE TITLE
[mediaqueries] How do media queries with calc() where it can be resolved early serialize?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#1968]
It's not clear to me from the spec text that media queries serialize with the specified or the "computed" value when integers or numbers are involved.

In particular, should these two serialize identically?

```html
<!doctype html>
<style>
  @media (min-aspect-ratio: 1 / 1) { }
  @media (min-aspect-ratio: calc(1) / calc(1)) { }
</style>
<script>
  alert(document.styleSheets[0].cssRules[0].cssText)
  alert(document.styleSheets[0].cssRules[1].cssText)
</script>
```

**Comment by frivoal** [comment]
The resolution of https://github.com/w3c/csswg-drafts/issues/434, I think we should do the same here, and simplify (and clamp, if necessary) early.

However, there's one part of the resolution I don't understand, which was highlighted by @tabatkins in that discussion: we simplify and clamp early, but then we put a calc() around the result of the simplification.

If we apply the same logic to media queries, this means that
`@media (min-aspect-ratio: calc(3 - 2) / calc(5 - 4)) { }`
and 
`@media (min-aspect-ratio: calc(1) / calc(1)) { }`
would serialize the same, but
  `@media (min-aspect-ratio: 1 / 1) { }`
would not.

I am not sure I follow why. @tabatkins can you explain?

**Comment by emilio** [comment]
FWIW that's what currently Firefox implements for normal declaration blocks / computed values.

That is:

```html
<!doctype html>
<style>
  #foo { line-height: calc(1 + 3); }
</style>
<script>
  alert(document.styleSheets[0].cssRules[0].cssText)
</script>
```

Alerts `line-height: calc(4)` on Firefox, but `line-height: 4;` on chromium / blink.

For media queries I didn't know whether we should do that or not, because it's not clear whether it's a computed or a specified value (thus this issue).

**Comment by frivoal** [comment]
@tabatkins ping

**Comment by tabatkins** [comment]
Yeah, the resolution ended up what in what I think is the best situation - simplify/clamp as early as possible. In MQs, that's always possible, since the allowed relative units can be absolutized immediately.

We retain the calc() wrapper so that the value keeps the same "shape", particularly in TypedOM.

**Comment by frivoal** [comment]
> We retain the calc() wrapper so that the value keeps the same "shape", particularly in TypedOM.

That's the part I'm not 100% I understand the benefit of, but alright.

**Comment by csnardi** [comment]
For the two browsers that currently implement this (Firefox and WebKit), both examples above serialize to `(min-aspect-ratio: 1 / 1)`. I'm working on implementing this in Chrome, and the current setup would serialize the same as Firefox/WebKit. It would seem this isn't spec-compliant behavior, but since 2/4 browsers are currently shipping without the `calc()` wrapper, maybe that should be changed?

**Comment by frivoal** [comment]
That sounds worth bring back to the WG. Agenda+

**Comment by emilio** [comment]
Does WebKit actually ship this? https://bugs.webkit.org/show_bug.cgi?id=181716 was resolved two days ago.

**Comment by csnardi** [comment]
My definition of ship may have been a bit loose; it should be in the next Safari TP. (It should also be noted that I was the implementer there)

**Comment by emilio** [comment]
Now I look at it, FF still doesn't ship this (it'll be on FF59), but will soon (it's the next release).

> Yeah, the resolution ended up what in what I think is the best situation - simplify/clamp as early as possible. In MQs, that's always possible, since the allowed relative units can be absolutized immediately.

I'm not sure we should convert relative units to absolute units (even though it's doable, and in fact trivial).

That'd be inconsistent with how every browser serializes something like:

```css
@media (min-width: 10em) {}
```

(which preserves the unit).

In any case, the following:

```css
@media (min-width: calc(1em + 10px)) {}
```

Should serialize either as `calc(1em + 10px)` or as `26px`, IMO. @csnardi what does WebKit do there?

Firefox right now preserves the specified value as-is, which is kind of inconsistent with what we do for numbers, because `calc(10px)` serializes as `calc(10px)`, not as `10px`, unlike `calc(1)`, which serializes to `1`.

That's an artifact of how it was implemented and I'm happy to make whatever change the WG decides is sane :)

**Comment by csnardi** [comment]
@emilio WebKit serializes that as `calc(1em + 10px)`. After more testing, it appears that calc with a length in all properties (in both WebKit and Chrome) is serialized to `calc(<length>)` whereas calc with a number is serialized to `<number>`.

**Comment by emilio** [comment]
Thanks! That matches Firefox as of right now.

Also just realized that we can't just absolutize the lenghts, because the initial font size used for `em` and such depends on the zoom level, so we would have to reparse the media queries instead of re-evaluate them when the zoom level changes, which would be unnecessarily complex.

**Comment by dbaron** [comment]
It seems like dropping `calc()` lead to a risk of producing something that's syntactically invalid.  For example, the `aspect-ratio` media feature requires positive integers, but range restrictions generally change from parse-time to compute-time inside of `calc()` (although is this still true for `calc()` in media queries?).

This means, I think (but maybe I'm wrong??), that:

```css
@media (aspect-ratio: calc(-1) / calc(-1)) { ... }
```

is syntactically valid, but if it were serialized as:

```css
@media (aspect-ratio: -1 / -1) { ... }
```

then that would be an invalid media feature value, which when reparsed and serialized again would produce:

```css
@media not all { ... }
```

This breaks two of the fundamental principles of serialization (always serialize to valid syntax, serialize to something that when reparsed will serialize to the same thing).

**Comment by emilio** [comment]
At least Firefox and WebKit (I suspect Blink too), serialize directly to:

```css
@media not all { ... }
```

Which means that the rule is invalid at parse time. That's probably ok, but it's definitely observable.

IIUC, clamping after parsing would involve evaluating that media query as if it was `(aspect-ratio: 1 / 1)`, right? Happy to make that change.

**Comment by frivoal** [comment]
PRs to handle this:
*bikeshed: https://github.com/tabatkins/bikeshed/pull/1300
*spec: https://github.com/w3c/csswg-drafts/pull/2887

**Comment by frivoal** [comment]
Oops, comment posted in the wrong issue. Removing and reposting to the right place

**Comment by tabatkins** [comment]
The spec is now clear that math functions are simplified immediately at parse time as much as possible, then again at computed/used value time (which isn't relevant for MQs).

Since MQs can convert all units to their canonical one, this means that all math functions in MQs should be resolvable immediately upon parsing.

Serialization is clear that fully-collapsed calc()s only serialize as their argument (without the `calc()` wrapper) if you're serializing a computed-time or later value. MQs are not computed or later, so they should never remove their calc() wrapper.

Note that, as currently specified, non-calc() math functions do not disappear if they're top-level even if they can be fully resolved; they retain their identify as the specific function and simplify their arguments. So a `sin(.5)` will serialize as such, not as `.479...`.

Since this should all be answered in the spec, I'm closing this issue. Feel free to reopen if there are any issues or confusing bits.

**Comment by emilio** [comment]
@tabatkins so do the new calc() changes mean that stuff like `z-index: calc(-1);` should produce something like `0` rather than `calc(-1)` from `div.style.zIndex` for example?

**Comment by emilio** [comment]
That's a behavior change, it'd be nice to have tests for it.

**Comment by tabatkins** [comment]
No, I said the exact opposite. ^_^

> Serialization is clear that fully-collapsed calc()s only serialize as their argument (without the calc() wrapper) if you're serializing a computed-time or later value. MQs are not computed or later, so they should never remove their calc() wrapper.

**Comment by tabatkins** [comment]
(Deleted previous comment, I misread.)

Yes, it does mean that, but also, that's been the documented behavior for a good while; it's not a new consequence of my edits. I can go dig up the resolution covering it if you'd like.

(See <https://drafts.csswg.org/date/2019-09-21T18:35:38/css-values-4/#calc-serialize> for this being present before my latest round of edits; the original change that added this is [four years old](https://github.com/w3c/csswg-drafts/commit/1d4c6ed63fc09a67c2ba0cc762d4e3d4f812c826).)

**Comment by tabatkins** [comment]
OR WAIT DANG IT I STILL MISREAD

No, `div.style.zIndex` is a specified value, it'll won't drop its calc() wrapper in any circumstance. The dropping only happens at computed-value time or later.  (That was also specified four years ago, but in [a different commit](https://github.com/w3c/csswg-drafts/commit/1511bc3554223f226ca921978f7e1bf264904ef8).)

**Comment by emilio** [comment]
Ok, that seemed to conflict with your quote above abut "math functions are simplified immediately at parse time as much as possible".

I was reading that as "calc() can go away too if possible" (that's a simplification we do at computed-value time). https://drafts.csswg.org/css-values-4/#calc-computed-value seems to imply that is a valid simplification. It'd be nice to clarify in the spec that dropping calc() at parse time is _not_ a valid simplification.

**Comment by tabatkins** [comment]
"Simplified" doesn't have a technical meaning. ^_^ 

I'm a little confused - you're linking to the text about computed value, but implying it says something about specified value? The "calc() wrapper goes away" isn't even specified in that section, it's part of [serialization](https://drafts.csswg.org/css-values-4/#serialize-a-math-function), and is clear about the condition that it occurs in.

**Comment by emilio** [comment]
I was linking to the computed value section because it says:

> with used value time information, a math function always simplifies down to a single numeric value.

Which to me _seemed_ to imply that simplifying the computed value to a single numeric value (which I expect to mean "drops the calc from the internal representation") was also a valid part of the simplification algorithm referenced from that section.

But if the calc going away is only meant to be a serialization tweak, not part of the simplification algorithm, that's good to know. No further questions spec-wise I guess...

I assume then this is only observable from typed OM... Is that right? My reading of the spec says that `line-height: calc(1px)` is supposed to be a math function value in typed OM, not a `CSSUnitValue`, which is 100% not what Blink does... Blink drops the calc() at parse-time. Are there tests for this?

**Comment by tabatkins** [comment]
> I assume then this is only observable from typed OM... Is that right? My reading of the spec says that line-height: calc(1px) is supposed to be a math function value in typed OM, not a CSSUnitValue, which is 100% not what Blink does... Blink drops the calc() at parse-time. Are there tests for this?

TypedOM doesn't currently have the same "drop the wrapper" rules in its reification stuff, no. It might be better to be consistent there, tho? I don't have a strong preference either way, but I do like consistency when possible.
