### ISSUE TITLE
[css-shadow-parts] Separate the mechanism to define part and theme

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#1972]
We would like the mechanism to define `::part` and `::theme` be separated to let components decide which parts should be theme-able.

**Comment by rniwa** [comment]
Strawman proposal would be to add two content attributes: `part` and `theme`.

**Comment by tabatkins** [comment]
Yeah, I think I agree with this.  I'd like to get a Polymer opinion, but I'm inclined to accept right now.

**Comment by daKmoR** [comment]
I'm in favor of this change :) would solve my use case as well :)
