### ISSUE TITLE
[css-inline][css-text-4] Allow padding to be applied at line start and end

### ISSUE THREAD

**Issue by palemieux** [w3c/csswg-drafts#1973]
_Per the 20171109 joint TTWG/CSS meeting_

As illustrated at [linePadding.pdf](https://github.com/w3c/csswg-drafts/files/1462732/linePadding.pdf) and specified at https://tech.ebu.ch/docs/tech/tech3380.pdf, a common captioning style requires the background of a line area to be extended at line start and line end. This styling capability is not currently supported by CSS.

See for example regions 3 and 4 at https://codepen.io/palemieux/pen/vyzbqW . Region 1 and 2 illustrate a region with and without line padding applied.

This capability mirrors the `ebutts:linePadding` styling attribute at https://www.w3.org/TR/ttml-imsc1.0.1/#linepadding , which is demonstrated in the following sample document, which can be rendered at http://sandflow.com/imsc1proc/index.html .

```
<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
 xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
 xmlns:ebutts="urn:ebu:tt:style" xml:lang="en" ttp:timeBase="media" xmlns:ebuttm="urn:ebu:tt:metadata" >
    <head>
        <metadata>
            <ebuttm:documentMetadata>
                <ebuttm:conformsToStandard>urn:ebu:tt:distribution:2014-01</ebuttm:conformsToStandard>
                <ebuttm:conformsToStandard>http://www.w3.org/ns/ttml/profile/imsc1/text</ebuttm:conformsToStandard>
            </ebuttm:documentMetadata>
        </metadata>
        <styling>
            <style xml:id="baseStyle" tts:color="#FFFFFF" tts:textAlign="center" tts:lineHeight="100%"/>
            <style xml:id="blackBackground" tts:backgroundColor="#000000"/>
            <style xml:id="greenBackground" tts:backgroundColor="#00FF00"/>
            <style xml:id="withLinePadding" ebutts:linePadding="0.5c"/>
        </styling>
        <layout>
            <region xml:id="area1" tts:origin="5% 10%" tts:extent="90% 20%" tts:displayAlign="center"/>
            <region xml:id="area2" tts:origin="5% 70%" tts:extent="90% 20%" tts:displayAlign="center"/>
        </layout>
    </head>
    <body>
        <div style="baseStyle">			
            <p xml:id="s1" region="area1" begin="00:00:01" end="00:00:09">
                <span style="greenBackground">Centered text on two lines<br/>without padding.</span>
            </p>
            <p xml:id="s2" region="area2" style="withLinePadding" begin="00:00:01" end="00:00:09">
                <span style="blackBackground">Centered text on two lines<br/>with padding.</span>
            </p>
        </div>
    </body>
</tt>
```

**Comment by fantasai** [comment]
Not sure if this fits better into css-inline or css-text, but it's definitely a layout issue, not a backgrounds one--the backgrounds need more space to draw into.

**Comment by fantasai** [comment]
Edited into the draft at https://drafts.csswg.org/css-text-4/#line-padding-property

Just need to also do #1975 and then should be ready to publish a new WD. ^_^

**Comment by nigelmegitt** [comment]
Thanks for that @fantasai - looks really good. I have one small concern that the example description could be misleading and made a proposal in a comment on the commit at https://github.com/w3c/csswg-drafts/commit/7fd0270a4de93bdfb0eb31ac528d403697f23932#r30504756 but am not sure the best way to make that change. There doesn't seem to be a pull request associated with this issue and I'm still getting to grips with the working style of CSS WG, so apologies for that.

**Comment by fantasai** [comment]
@nigelmegitt Great! Checked in your suggestion. Thanks so much for the review!!

> There doesn't seem to be a pull request associated with this issue and I'm still getting to grips with the working style of CSS WG, so apologies for that.

Usually the editor(s) will push directly to the ED if they're reasonably certain of the change. We'll use PRs if there seems to be a need for review before it goes online, or if proposing edits to someone else's spec.
