### ISSUE TITLE
[css-inline] Allow background of an inline area to extend to before-and after-edges of the line area

### ISSUE THREAD

**Issue by palemieux** [w3c/csswg-drafts#1974]
_Per the 20171109 joint TTWG/CSS meeting_

As illustrated at [fillLineGap.pdf](https://github.com/w3c/csswg-drafts/files/1462792/fillLineGap.pdf), a common captioning style requires the background of inline areas to extend to the before-and after-edges of the containing line area. This styling capability is not currently supported by CSS.

This capability mirrors the `itts:fillLineGap` styling attribute at https://www.w3.org/TR/ttml-imsc1.0.1/#itts-fillLineGap

**Comment by astearns** [comment]
@palemieux what should happen when the line boxes are actually separated (here by a float outside the paragraph)?

![image](https://user-images.githubusercontent.com/1380751/33152913-09ba92ac-cf94-11e7-80fc-6b8cc99ce744.png)

Is the only requirement that the background extend to the edges, or should we define it to create a contiguous background area in a case like this?

**Comment by palemieux** [comment]
@astearns What would the background look like in the illustration above with zero padding?

**Comment by astearns** [comment]
With a background on a span containing the text:

![image](https://user-images.githubusercontent.com/1380751/33153921-9eb5a626-cf99-11e7-999b-79bec5ab0976.png)

**Comment by palemieux** [comment]
@astearns Thanks! and what would be the line boxes in that example? In particular, is the after edge of the line box that contains "some" aligned with the bottom of the green square?

**Comment by astearns** [comment]
No, this is a case where line box stacking does not give a result where the before and after edges coincide. Each line box is exactly the same height - the float rules just move the second line down below the float

**Comment by palemieux** [comment]
So, in this scenario and according to the current definition, the background would not be continuous.

The result would be presumably different if the green square were inline the paragraph (instead of a float).

**Comment by nigelmegitt** [comment]
This case does not generally arise in subtitles and captions; if it did, I would expect a gap in the background areas, i.e. the rule to align the span background before and after edges with the line area before and after edges would still seem acceptable to me. The alternative might be a very large background block containing no foreground content.

To flip that around, what if someone wanted that background block to be contiguous in the block progression direction but tight to line areas in the inline progression direction? I don't see how that could sensibly be done - it's asking to align not with the current line area's before and after edges but the previous line area's after edge and the next  line area's before edge. I suppose that could be another keyword option, but I'd give it lower priority.

**Comment by fantasai** [comment]
https://www.w3.org/TR/css-inline-3/#line-fill
