### ISSUE TITLE
[css-selectors-4] user-error is listed as a pseudo class when it should read :user-invalid

### ISSUE THREAD

**Issue by estelle** [w3c/csswg-drafts#1976]
https://drafts.csswg.org/selectors-4/#user-pseudos - is it :user-invalid. There are several occurrences of :user-error

**Comment by Loirooriol** [comment]
Already reported in #1329

**Comment by fantasai** [comment]
Fixed, thanks! https://github.com/w3c/csswg-drafts/commit/b3d287cce333d3ca2053cf74f46e78c6a1bbee9e
