### ISSUE TITLE
[css-align] Does `left` and `right` apply to <self-position> or <content-position>?

### ISSUE THREAD

**Issue by huijing** [w3c/csswg-drafts#1980]
When referring to the spec, under section 4.1 on Positional Alignment (on line 323 of the `Overview.bs` file), the last 2 values on the definition list are `left` and `right`.
> left (self, content)
...
> right (self, content) 
...

In the paragraph of grammar terms below the list, neither <self-position> nor <content-position> include`left` and `right` in their lists. Where does `left` and `right` apply?

**Comment by SelenIT** [comment]
It seems that these values were removed from the spec [at some point](https://github.com/w3c/csswg-drafts/issues/1403#issuecomment-311722607), but not from all places. I assume they should be removed from the list you refer to as well.

**Comment by fantasai** [comment]
They were not removed, they are merely restricted to `justify-self`, so we couldn't include them in the shared `<self-alignment>` grammar set. Remember that there is a difference between a non-terminal grammar term and a property's value space!

**Comment by SelenIT** [comment]
@fantasai, thanks a lot for the clarification!
