### ISSUE TITLE
[css-counter-styles] New CR publication?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#1987]
Counter Styles is fully up-to-date in edits, with an accurate [Changes section](https://drafts.csswg.org/css-counter-styles/#changes-jun-2015) and [DoC](https://drafts.csswg.org/css-counter-styles/issues-cr-20150611). Can we resolve to publish it as a new CR? Last publication was in June 2015.

**Comment by gsnedders** [comment]
@fantasai What test cases are needed?

**Comment by fantasai** [comment]
@gsnedders CSSWG requested one test per change. https://lists.w3.org/Archives/Public/www-style/2017Nov/0017.html It's not clear if that exists.

**Comment by gsnedders** [comment]
@fantasai so it's a case of "we don't know if we need any more test cases", rather than we definitely do?
