### ISSUE TITLE
[css-text] Control characters

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1990]
There was a long thread in www-style discussing about how control characters should be rendered, and that resulted in the following text in css-text-3:
> Control characters (Unicode category Cc) other than tab (U+0009), line feed (U+000A), form feed (U+000C), and carriage return (U+000D) must be rendered as a visible glyph and otherwise treated as any other character of the Other Symbols (So) general category and Common script. 

It seems to me that no browser is currently shipping this behavior, and IIRC we wanted to coordinate shipping this behavior together so that websites know it is an intentional behavior change for the platform.

I'd like to ask are we still want to do so? Firefox has implemented a switch for the new behavior since long ago, and we have it enabled by default for Nightly and early Beta. We are able to ship this change at any time, but we don't want to ship it without intent from other vendors. (And although it is not a big deal, the switch itself still adds some burden to maintaining, especially given that this switch wasn't supposed to stay for long.)

@gregwhitworth, @tabatkins, @litherum have Edge / Blink / WebKit implemented this switch? Can we start coordinating shipping the new behavior again?

**Comment by kojiishi** [comment]
Blink has shipped this change in M56, the tracking bug at [crbug.com/530342](https://crbug.com/530342).

**Comment by upsuper** [comment]
@kojiishi It seems that on Blink, the characters are only visible on Windows by default.

Referring @jfkthame's comment from [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1329613#c7):
> I think what you're seeing may be that they are simply passing the characters through to the rendering system and drawing whatever the current font offers, which on Windows turns out to be ".notdef" glyph boxes, but could be zero-width invisible glyphs or blank spaces or whatever happens to be in the font. That doesn't seem a very satisfactory implementation to me.

**Comment by kojiishi** [comment]
Thanks, it's our misunderstanding if that's the original intention.

We have [crbug.com/689599](https://crbug.com/689599) to render something when font doesn't have glyphs, but we thought it's a different topic.

@gregwhitworth can you help us to understand which was the intention?

**Comment by upsuper** [comment]
The spec says:
> Control characters (Unicode category Cc) other than ... must be rendered as a visible glyph

which seems to indicate that UA should probably not pass through to font, as font can make the character invisible (and some of them actually do so).

**Comment by kojiishi** [comment]
Ah, that's one interpretation I can agree now with your explanation, but I can still read it differently, since a "glyph" for me is the one from a font, and I didn't imagine a synthesized graphics is a "glyph". Now I understand the text is a bit ambiguous when the font doesn't have the glyph, or have a glyph that doesn't have a ink. The latter is even more complex, I guess it involves heuristic? I'm curious how Gecko implemented it.

This was a request from @gregwhitworth to make browsers interoperable IIUC (correct?), I'm interested to hear which was his intention.

**Comment by jfkthame** [comment]
For control characters (category Cc) gecko never attempts to draw a glyph from the font; it draws these (if the pref to make them visible is enabled) with the same "hexbox" code it uses as a last-resort rendering for printable characters that are not supported by any available font: a simple box with the character code in tiny hexadecimal digits inside.

**Comment by gregwhitworth** [comment]
@kojiishi No this was not a change that I wanted, more that I wanted the breaking change to ship in more than 1 UA so they don't get "bugs".  We do similar to what to @jfkthame has stated, but have yet to turn it on by default. But yes, if the font doesn't have it you should render something as showing nothing kind of defeats the purpose and results in you being in the same state as before where authors can inadvertently have control characters that mess up other peripherals that depend on those CC without meaning to.

**Comment by kojiishi** [comment]
Thank you for the clarification, @jfkthame and @gregwhitworth, I understand how it is supposed to work now. This is a feature that ignores glyphs in the font even if it has for Cc code points, and renders synthesized graphics instead. /cc @eaenet

Then we haven't implemented this yet.

**Comment by kojiishi** [comment]
Probably related, we're seeing the L-SEP glyph (in the font) rendered, since our change only in Chrome ([stackoverflow](https://stackoverflow.com/questions/39603446/why-is-this-symbol-showing-up-on-chrome-and-not-firefox-or-edge)). This is Zl category and isn't default-ignorable as per the [Unicode data](http://www.unicode.org/Public/UNIDATA/DerivedCoreProperties.txt).

Can I understand that, when other browsers enabled this, Chrome will match to other browsers?

**Comment by kojiishi** [comment]
...never mind, sorry for the noise, I remember we only care Cc category.
