### ISSUE TITLE
[css-grid] The definition of grid span

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#1994]
The [definition for grid span](https://drafts.csswg.org/css-grid-1/#grid-span) says:

> How many grid tracks the grid item occupies. A grid item’s grid span is always definite, defaulting to 1 if it can’t be otherwise determined.

I don't understand the definition here. In the [definition for grid track](https://drafts.csswg.org/css-grid-1/#grid-track):

> Grid track is a generic term for a grid column or grid row—in other words, it is the space between two adjacent grid lines.

If a grid item occupies two rows and three columns, what is the grid span of that grid item? Is it five (2 + 3)? Or is it six (2 * 3)?

**Comment by xfq** [comment]
Or is it two in terms of rows, and three in terms of column?

**Comment by SelenIT** [comment]
> Or is it two in terms of row, and three in terms of column? (I mean, a grid item has two grid spans.)

I believe, that's the correct understanding. The grid item has two grid spans, one for each axis. In the given example, it spans 3 grid tracks along the inline axis and 2 grid tracks along the block axis.

**Comment by tabatkins** [comment]
Yeah, a span of 2 in terms of row, and 3 in terms of columns. Virtually everything about grids is agnostic to the direction, and works in one axis at a time.

**Comment by xfq** [comment]
Thanks.

IMHO the definition text of grid span should be clearer, although I don't have a good proposal for the improved dfn for the moment.

**Comment by xfq** [comment]
Thanks Tab & fantasai! It looks okay to me now. ^_^
