### ISSUE TITLE
[css-lists] Grammar for counter names should be consistent.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#1996]
https://drafts.csswg.org/css-lists-3/#funcdef-counter says:

```
counter( <ident>, [ <counter-style> | none ]? )
counters( <ident>, <string>, [ <counter-style> | none ]? )
```

However counter-increment and such say:

```
[ <custom-ident> <integer>? ]+ | none 
```

Looks like `<ident>` and `<custom-ident>` should be used consistently. I suspect we want to use `<custom-ident>` everywhere?

**Comment by fantasai** [comment]
Looks like this was fixed in cb834e9c
