### ISSUE TITLE
[css-overflow] add overflow-block and overflow-inline to support CSS Writing Modes

### ISSUE THREAD

**Issue by a2sheppy** [w3c/csswg-drafts#2000]
Currently, neither css-overflow (https://drafts.csswg.org/css-overflow) nor css-logical (https://drafts.csswg.org/css-logical/) define a method for specifying values for the `overflow` property based on the current writing direction. Instead, you can only specify the overflow in terms of the X and Y axes. This is highly limiting when trying to adapt to a multi-locale environment where you may need to set overflow based on the direction of text flow.

Either in css-overflow or in css-logical (whichever is appropriate), there should be a definition for how to set overflow based on the text flow rather than strict X/Y directions.

**Comment by Loirooriol** [comment]
It would also be nice if `overflow` accepted two keywords (one for each physical direction) and optionally a flow-relative switch (see #1282).

**Comment by a2sheppy** [comment]
Obviously per the title of this issue, I think adding `overflow-block` and `overflow-inline` properties to CSS makes sense, given how other related properties are handled.

I agree though that supporting a syntax like the following would also be helpful:

`overflow: relative? && [ <length> | <percentage> | auto ]{1,2}`

(or `logical` instead of `relative`, whichever is settled upon in the end elsewhere in CSS-land)

**Comment by frivoal** [comment]
Seems to me that this should go into css-logical (1 or 2, I don't care strongly). @fantasai @atanassov what do you think?

As for adding the `relative` or `logical`, I think it would be weird to do it only for overflow, and not for other shorthand properties that can have either physical or logical longhands.  @a2sheppy, do you want to open a separate issue about that, or do you think there is a reason why this would need to exist for this but not for other properties?

**Comment by frivoal** [comment]
@Loirooriol I see, sorry for the misunderstanding. In that case, yes, I agree, and the only question left for me is which spec the logical longhands of overflow go to. I'd suggest css-logical over css-overflow, but I'm not stuck on that.

**Comment by a2sheppy** [comment]
@frivoal I'm not sure which spec the logical longhands belong in either, although I think I lean toward css-logical as well. I'll file a ticket there and let y'all sort things out. :)

**Comment by a2sheppy** [comment]
Actually, does issue #1282 already address this? It refers to `margin` but seems to be just using it as an example (since it says "`margin`-like" shorthands. Would that not include `overflow`?

**Comment by frivoal** [comment]
@a2sheppy #1282 works for the addtion of the `relative` keyword, and this ticket works for the addition of the logical long hand. We're just waiting for an upcoming CSS-WG teleconference call to decide whether we agree (I expect we will), and which spec we put it in (I expect css-logical).

**Comment by dbaron** [comment]
I think it should go in whichever of css-overflow or css-logical is the *less* stable specification.  I think that's currently css-logical, but I'm not confident of that judgment.

**Comment by fantasai** [comment]
It should go into css-overflow-3; css-logical-1 only defines stuff in earlier modules (e.g. CSS2.1), newer ones are expected to define their own logical equivalents. (I can't say that css-logical-1 and css-overflow-3 are particularly different wrt stability anyway. They both should be in CR, but need a bit of work / trimming down to get there.)

**Comment by jonjohnjohnson** [comment]
Since this relates to scrolling and box offsets, just wanted to bring up...
```css
.stick-to-overflow-relative-axis {
  position: sticky;
  inset-block-start: 0;
}
```
[Make Position 3 dependent on Logical?](https://drafts.csswg.org/css-position-3/#sticky-pos)
