### ISSUE TITLE
[css-fonts] Spec Not Update to Include Feature Now Implemented

### ISSUE THREAD

**Issue by jpmedley** [w3c/csswg-drafts#2002]
The `FontFace.display` property [has been implemented](https://codereview.chromium.org/2640753002) in [Chrome 57](https://storage.googleapis.com/chromium-find-releases-static/ec8.html#ec812adbe02d56c9efafcaa77c7dfd9121510959). It's rumored to be implemented in other browsers as well. Per [MDN instructions](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Write_an_API_reference#Structure_of_a_property_page) the MDN page describing it must contain a link to the spec. 

Unfortunately, I can find no spec containing this property, though I'm told by reliable sources that it is supposed to be.

https://drafts.csswg.org/css-fonts-4/

**Comment by svgeesus** [comment]
Related:
https://github.com/w3c/csswg-drafts/issues/1360
https://github.com/tabatkins/specs/issues/54

Is this a property or a descriptor? Isn't the descriptor in https://drafts.csswg.org/css-fonts-4/#font-display-desc ?

From my reading of https://github.com/w3c/csswg-drafts/issues/1360 I think the corresponding interface would be added to https://drafts.csswg.org/css-fonts-4/#om-fontface but has not yet been added.

**Comment by litherum** [comment]
This is a dup of https://github.com/w3c/csswg-drafts/issues/1360
