### ISSUE TITLE
[css-scrollbars-1][unclear-issue]

### ISSUE THREAD

**Issue by retyui** [w3c/csswg-drafts#2007]
Link to spec: https://drafts.csswg.org/css-scrollbars-1/
These new css properties allow you to influence only the color of the scrollbar.
Is it inherent in the complexity of realization? 
would like ::-webkit-scrollbar CSS pseudo-element?

**Comment by tabatkins** [comment]
I'm not sure what you're trying to say here?

**Comment by Nadya678** [comment]
> scrollbar-3dlight-color, scrollbar-arrow-color, scrollbar-base-color, scrollbar-darkshadow-color, scrollbar-face-color, scrollbar-highlight-color, scrollbar-track-color, scrollbar-shadow-color. 

**Definitive "NO" for this solution.** 

I propose:
`::scrollbar` - it describe position, base colour, width/height of the scrollbar.
`::scrollbar-thumb` - it describes with use of standard styles the thumb of scrollbar. Including center icon (background-image) if present.
`::scrollbar-prev` - button for scroll left or top, 
`::scrollbar-next` - button for scroll right or bottom, 
 ::scrollbar-grip` - resizing handle. 

Pseudoclasses:
`:vertical, :horizontal, :disabled` (none to scroll if overflow:scroll),` :end `(position is maximum), `:start` (thumb position is 0).

We don't need scrollbar-3dlight-color etc. It is possible to describe scrollbar with use of standard styles for example border-bottom. 

Reason: The manipulation of scrollbars shall be complete. The scrollbar is composed with real elements: background, thumb, buttons and there shall be reflected in CSS. 
**The scrollbar-darkshadow-color is not applicable for smartphone scrollbar look.**

**Comment by Nadya678** [comment]
Additionally:

Security problem of the css-scrollbars-1 @ 14 Nov 2107 draft:
ThreeDFace, ThreeDDarkShadow etc. can be used to detect user colour composition in OS. If user has set non-standard composition in their OS (for example Windows Classic in Windows 8.1, extended personalized themes etc.), the browser will inherit these colours and in computed values or copied area (with JavaScript both) the real colour values of these 8 values. There may be tracked 8 colours (each of them having three 0..255 values) and additionally there is able to track original width and height of scrollbar. **There is 25-byte length identifier that can be unique and help to thrack the user!** It is strong impact for privacy and security. 

Thus: the standard width/height of scrollbar shall be standarized to 17px (it is the most often value), the colours of each pseudoelement of scrollbar also shall be standarized for PC browsers ans smartphones. Web-developers shall be possible to mainpulate these values but shall bot be able to read colours of OS composition. 

If the ThreeDDarkShadow etc. are used in any workind draft/recommendation, PLEASE define standard values for them. For example ThreeDDarkShadow ::= #808080 (I propose grayscale for them).

**Comment by ExE-Boss** [comment]
> Edit: If the width of scrollbar will be defined as 16px and user will select zoom:200% in their browser settings, the scrollbar shall have visual size equivalent to 32px (200%*16px). This also shall be clarified in future draft.

From testing, I’ve determined that Firefox doesn’t scale the scrollbars.
