### ISSUE TITLE
[CSS-align][CSSOM] New attribute for block level vertical centering the content

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2017]
It is easy for me to define:
```
html
{
   display:table;
   width:100%;
   border:none;
   border-spacing: 0px;
   height:100%;
}
body
{
   display:table-cell;
   vertical-align:middle; 
   /* here add padding to make area for fixed-positioned elements like menu, nav-bar*/
}
```

but centering of content inside other elements is hard. There is no ideal solution. 

Can you add style: 
`display: block-cell` (and probably `inline-block-cell`)?
Display like block but with working: `vertical-align:bottom` and `vertical-align:middle;`

I know, I can use flexbox but... I must add additional container to do it and flexbox has additional adverse effects for elements inside it.

**Comment by Nadya678** [comment]
BTW. If in the example is more text inside `<body/>` - which element should have defined scrollTop property? 

- `<body/>`
- `<html/>`
- document
- window?

**Comment by tabatkins** [comment]
This is already defined in the spec you link to: [`align-content: center` on a block will vertically center the content](https://drafts.csswg.org/css-align/#distribution-block) (once browsers implement the alignment properties on blocks).

**Comment by Nadya678** [comment]
Thank you for explanation. This style will solve this problem if it will be implemented. 
BUT what about CSSOM [scrollTop] for `display:table` on `<html/>` element described here? Shall I put new issue?

**Comment by tabatkins** [comment]
Yeah, that sounds like a totally separate issue.
