### ISSUE TITLE
[css-fonts-4] Define the font hierarchy (installed; preinstalled; system; etc.)

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2019]
Let's pretend you're on a computer with a font named "Helvetica" installed. If you then say document.fonts.load() with "Helvetica", you should get 0 results. (Similarly if you iterate across document.fonts).

Also, if you add a new FontFace object to document.fonts with the family name "Helvetica" and call load() with "Helvetica", it should only ever be possible to get the FontFace object you just added.

This should be true for document.fonts as well as any FontFaceSet objects you create via "new".

I don't believe the spec has any language about preinstalled fonts.

**Comment by litherum** [comment]
This is the behavior that Chrome and Firefox have (and I'm [changing](https://bugs.webkit.org/show_bug.cgi?id=180164) WebKit to match them).

**Comment by tabatkins** [comment]
This is already specified. `.load()` is very explicit about this (it calls "find the matching font faces" without the "allow system fonts" flag), while the `FontFaceSet` itself implicitly defines this, in that it defines that @font-face rules get added to it, and allows authors to add more to it; there's no text defining how system fonts get put into it, or how they'd be represented.

**Comment by litherum** [comment]
I see. I was confused because of terminology. "System font" usually means `system-ui`. "Preinstalled" is a better term.

**Comment by tabatkins** [comment]
It's reasonable to have a definition for that category, I guess. I see your older #1052 about this.  Wanna put a definition of "installed font" into Fonts, and I can link to that?

**Comment by litherum** [comment]
Sure.

**Comment by litherum** [comment]
http://litherum.blogspot.com/2016/09/font-taxonomy.html

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/a6ef2d9420509ec3a9ac9c9f899d4d0588381381
