### ISSUE TITLE
[css-values][css-color] Generic hexadecimal number notation

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#2024]
- [CSS Color: Hex Notation](https://drafts.csswg.org/css-color/#hex-notation)
- [CSS Values: Integers](https://drafts.csswg.org/css-values/#integers)
- [CSS Syntax: Hash Token](https://drafts.csswg.org/css-syntax/#typedef-hash-token)

Inside the [`color()` function](https://drafts.csswg.org/css-color/#color-function) and perhaps elsewhere, some authors may prefer to enter numeric values in hexadecimal notation, especially for 8-bit integer values. Currently, CSS only supports hexadecimal numbers as (shortened) tuples in `<color>` (`#F00`) and for Unicode code points (`\0F00`). Notation variants popular in other languages, e.g. `0xF00` or `hF00`, will not work well in CSS Syntax. Unitless integers cannot generally be used inside `color()` because floats between 0 and 1 are frequently used there (although CSS's classic native notation is percentages for those #2021).

If authors regularly feel the need to enter hexadecimal numbers indeed, CSS should support an alternative integer notation inspired by RGB triplets. To avoid confusion with the three-digit shorthand `#F00`, however, it probably makes sense to restrict these numbers to one or two digits: `#0`..`#F` and `#00`..`#FF`, i.e. value ranging from 0 through 255. It would be needed to decide whether `#F` equaled `#0F` or `#FF`.

I'm not convinced myself this syntactic sugar is actually needed, but its merits and costs should be evaluated anyway.

**Comment by svgeesus** [comment]
I'm not seeing any particularly compelling case for this latest proposal.

**Comment by Crissov** [comment]
Like I said, this is more an _advocatus diaboli_ proposal.

**Comment by tabatkins** [comment]
Proposals for the heck of it aren't very useful. Unless you have some actual use-cases for this (problems you're having that would be made easier by something like this), I'm going to close it.

**Comment by Crissov** [comment]
The use case was the examples quoted in #2021:
>    color: color(swopc 0 206 190 77);
>    color: color(indigo 24 160 86 42 0 18 31);
>    color: color(prophoto 233 150 122);
>    color: color(p3 97 253 36);

which show 8-bit integer values inside `color()`. I assume that some authors would prefer to write them with hexadecimal numbers instead of percentages or 0..1 floats.

Given a tracker, such pseudo-proposals are useful in that the WG can provide a reason for closing them and then proceed to do so. This way, people can easier check whether their idea has been evaluated and dismissed already (or can be pointed here by others).

**Comment by tabatkins** [comment]
The person in that issue didn't ask for hex, or indicate that the lack of a hex notation was causing them any problem.  That's what I mean by "problems you're having that would be made easier by something like this" as a prerequisite for feature requests.
