### ISSUE TITLE
[css-color-3] CR SoTD needs: relationship of this specification to the previous Recommendation

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#2026]
Per transition approval on behalf of the Director, the new CSS3 Color CR needs an explicit relationship of this specification to the previous Recommendation in the SoTD before being published. cc: @svgeesus @dbaron

Something like: 
"The new Edited Recommendation will supersede the existing Recommendation."

**Comment by svgeesus** [comment]
Added "It is expected that, once approved, the new Edited Recommendation 
    will supersede the existing Recommendation."
