### ISSUE TITLE
[css-timing-1] Add syntax to section headings

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2027]
For sections that define a particular piece of syntax, Tab and I try to put the syntax in the heading so that they are easy to find in the Table of Contents, like this: https://drafts.csswg.org/css-values-3/#toc

I think the Timing Functions spec would benefit from this practice.

Also I would move the <single-timing-function> production definition from its own 2-line section at the end of the spec into section 2. Timing Functions. This way the syntax definition serves as an overview and ToC of the section.

**Comment by birtles** [comment]
Fixed by ee3b72b0f176ecf3c041ff2284281530be7c8165 and 3da5bcfd37e28ffd968f3efcb4d4702ccdb61c45
