### ISSUE TITLE
[css-timing-1][css-transitions-1] <single-*> seems excessively specific

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2028]
The Transitions and Timing specs have productions like `<single-timing-function>`, but there is no `<multiple-timing-function>` production or anything like that to contrast with, so it seems to me it would make sense to just call these e.g. `<timing-function>`.

**Comment by birtles** [comment]
I'd love to understand better how the references get generated for these specs. I've fixed this in css-timing but I can't update css-transitions and css-animations until some reference database gets updated it seems. I'm not sure when that happens.

**Comment by birtles** [comment]
Note to self: web-animations also needs to be updated.

**Comment by birtles** [comment]
Link database has still not been updated.

**Comment by birtles** [comment]
Link database has been updated so I've fixed this in css-transitions-1, css-animations-1, and web-animations-1 in 9d436bbfb4f529e541817010348427c9b5deb7e2 and submitted PR #2161 for css-values-3 and css-values-4.

**Comment by fantasai** [comment]
Wow, however did you figure out what I was talking about given half the comment was invisible? :) Fixed by adding `quote`.

I'm not sure how often the link database updates, but it should be at least once a day; if not, poke @plinss about it. Bikeshed needs to run `bikeshed update` sometimes to get the latest.

Merged the PR.

**Comment by birtles** [comment]
I think when I clicked the "edit" link it showed me the markup 😉.

Yes, there was a problem with the cron job that updates link database getting stuck while Tab was away and unable to access the machine he needed to un-stick it. (@plinss showed me how to use `bikeshed update --force` to update the database anyway, but by the time I got back to this the cron job was running again.)

Thanks for merging the PR!
