### ISSUE TITLE
[css-content] paragraph relating to negative quote depths from CSS2 is missing from CSS3

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#2038]
CSS 2.1 has this to say about the "quote" property in https://www.w3.org/TR/CSS21/generate.html#quotes-specify:

> 'Open-quote' refers to the first of a pair of quotes, 'close-quote' refers to the second. Which pair of quotes is used depends on the nesting level of quotes: the number of occurrences of 'open-quote' in all generated text before the current occurrence, minus the number of occurrences of 'close-quote'. If the depth is 0, the first pair is used, if the depth is 1, the second pair is used, etc. If the depth is greater than the number of pairs, the last pair is repeated. **A 'close-quote' or 'no-close-quote' that would make the depth negative is in error and is ignored (at rendering time): the depth stays at 0 and no quote mark is rendered (although the rest of the 'content' property's value is still inserted).**

The sentence in bold has not been migrated to CSS3 (see https://www.w3.org/TR/css-content-3/#quotes-property)

Without it, what to do if the depth is negative remains undefined. I presume the behaviour has not changed, and this is just a cut and paste error.

**Comment by fantasai** [comment]
Thanks, fixed!
