### ISSUE TITLE
[css-animations-2] CSS animation keyframes should define how the composite value is set

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2057]
_From @birtles on October 8, 2015 1:13_

[CSS Animations 2](https://drafts.csswg.org/css-animations-2/) defines an [animation-composition](https://drafts.csswg.org/css-animations-2/#animation-composition) property which can also be used within a @keyframes rule. If this property is not specified we need to define whether it is null or if it is resolved to the value specified on the target element. After discussing with @heycam, we think it should be resolved to the value on the target element (i.e. "replace" in most cases). That parallels what we do for animation-timing-function.

_Copied from original issue: w3c/web-animations#135_

**Comment by fantasai** [comment]
@birtles I believe this is currently edited in, feel free to close if so or flag Needs Edits if it needs something more. :)
https://drafts.csswg.org/css-animations-2/#keyframe-processing

**Comment by birtles** [comment]
> @birtles I believe this is currently edited in, feel free to close if so or flag Needs Edits if it needs something more. :)
> https://drafts.csswg.org/css-animations-2/#keyframe-processing

Yep, looks good to me. Thanks!
