### ISSUE TITLE
[web-animations-1] Add parameter to getAnimations for getting animations in descendants too

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2058]
_From @birtles on March 17, 2016 0:48_

As discussed and minuted here: The ideas we came up with are here: https://docs.google.com/document/d/1lQbgJ0fZYGn1_qboj59G-MOILK33z4kmBdjgtSHF2gA/edit#heading=h.cioj28lsgoa2

A more concrete elaboration on that proposal is described here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1254761#c0

_Copied from original issue: w3c/web-animations#146_

**Comment by birtles** [comment]
I discussed this with Antoine at one point and I think we were leaning against adding this.

**Comment by birtles** [comment]
_From @graouts on November 21, 2017 8:52_

Yes, I don't think this is warranted, JavaScript can be efficiently used to filter results of getAnimations() calls. I suggest we close this.

**Comment by birtles** [comment]
Yeah I agree about dropping the filter feature. I wonder if we might still want something along the lines of `{ subtree: true }` for getting all animations from a node and its descendants (like MutationObservers). We've actually implemented that in Firefox but only turned it on for internal users--we use it for our DevTools and for UI code.

If we do go ahead with that then we might want something more extensible than a bool (although at the same time aligning with MutationObserver is nice). I'm not sure if we'll eventually need a third value for crossing shadow DOM boundaries or if that's even possible?

**Comment by annevk** [comment]
Please don't cross shadow tree boundaries if that ends up exposing information about the shadow tree.

**Comment by birtles** [comment]
@annevk Would it be ok to expose animations from a shadow tree if the shadow root is open?

**Comment by tabatkins** [comment]
We don't generally draw a distinction there, I think.

**Comment by annevk** [comment]
Yeah, the main difference with open is for `Element#shadowRoot` and `Event#composedPath()`, but encapsulation in general should still hold.

**Comment by birtles** [comment]
Ok, I'm assuming that encapsulation applies even if the author were to explicitly pass a flag such as `{ composed: true }` ([as suggested here](https://bugzilla.mozilla.org/show_bug.cgi?id=1519514#c38)).
