### ISSUE TITLE
[web-animations-1] Replace AnimationEffectTiming(ReadOnly) with setTiming() ?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2065]
_From @birtles on September 14, 2016 7:47_

Just a thought about how we could simplify the API and make it more consistent.

Currently, we manage timing properties using the following interfaces:
- [`AnimationEffectTimingProperties`](https://w3c.github.io/web-animations/#dictdef-animationeffecttimingproperties) &mdash; property bag for passing to constructors etc.
- [`ComputedTimingProperties`](https://w3c.github.io/web-animations/#the-computedtimingproperties-dictionary) &mdash; extends `AnimationEffectTimingProperties` with some extra properties we compute
- [`AnimationEffectTimingReadOnly`](https://w3c.github.io/web-animations/#the-animationeffecttimingreadonly-interface) &mdash; Live object with getters for reading the specified timing properties. Fortunately, this happens to have the same members as `AnimationEffectTimingProperties` so you can pass it to constructors/methods that expect a `AnimationEffectTimingProperties` and it should work.
- [`AnimationEffectTiming`](https://w3c.github.io/web-animations/#the-animationeffecttiming-interface) &mdash; Subclass of `AnimationEffectTimingReadOnly` that adds getters for the different parameters (used by mutable effects, i.e. those not tied to CSS)

In practice it looks like this:

``` js
// Set up a new animation
const anim = elem.animate({...}, { duration: 2000, fill: 'auto' });

// Read back the specified values
anim.effect.timing.duration; // 2000
anim.effect.timing.fill; // 'auto'

// Read back computed values
anim.effect.getComputedTiming().duration; // 2000
anim.effect.getComputedTiming().fill; // 'none'
// NOTE: |fill| and |duration| are a little bit special in that they allow 'auto'
// values that get computed into something else. It's not particularly useful, though,
// until we have groups (where, e.g., a group's auto duration computes to the length
// of its children).

// Read other computed values
anim.effect.getComputedTiming().activeDuration // 2000
anim.effect.getComputedTiming().progress // 0.0

// Update specified values
anim.effect.timing.duration *= 2;
anim.effect.timing.iterations++;
```

The parallel here is with style:
- `anim.effect.timing` =~ `elem.style` (sort of, kind of)
- `anim.effect.getComputedTiming` =~ `window.getComputedStyle(elem)`

_However_, for keyframes we do something completely different. We don't have live keyframe objects since that would be hard and instead we just use [`getKeyframes()`](https://w3c.github.io/web-animations/#dom-keyframeeffectreadonly-getkeyframes) and [`setKeyframes()`](https://w3c.github.io/web-animations/#dom-keyframeeffect-setkeyframes).

In addition, keyframe offsets can be computed. The author can omit them and we'll fill them in. We _don't_ just fill in the `offset` member with the computed value when we return keyframes using `getKeyframes()`, however, since if we did that you couldn't take the result of `getKeyframes()` and pass it to `setKeyframes()` on another effect without freezing the offsets at that point (and losing the ability to auto-distribute keyframes from then on). Instead, we return the computed offset as a separate member: `computedOffset`.

So my thought here was:
- Drop `AnimationEffectTimingReadOnly`.
- Drop `AnimationEffectTiming`.
- Drop `effect.timing`.
- Rename `effect.getComputedTiming()` to `effect.getTiming()`.
- Extend `ComputedTimingProperties` to include `computedDuration` and `computedFill`.
- Add `effect.setTiming()` that takes an `AnimationEffectTimingProperties` (which `ComputedTimingProperties` extends so you could pass the result of `getTiming()` to `setTiming()`).

Advantages:
- 2 fewer interfaces
- Fewer live objects
- Consistency within the API &mdash; keyframes and timing properties follow the same idiom
- Bulk setting of timing properties is easier

Disadvantages:
- More awkward to update an individual timing property, e.g.

``` js
// Current API
anim.effect.timing.duration *= 2;
// Proposed API
const updatedTiming = anim.effect.getTiming();
updatedTiming.duration *= 2;
anim.effect.setTiming(updatedTiming);
```
- More inefficient to update individual timing properties since you need to read and write these property bags. From what I understand, at least for Gecko, that can be quite slow.

I do wonder how common those last two items are, though. (And for the first one, if you're just blindingly overwriting the value, you can use Object.assign() or, one day, the object spread operator to write it more compactly.)

The other consideration is this proposal _may_ be less forwards compatible. For example, suppose we extend `iterations` to take a keyword value. Presumably it will still compute to a float. Code that currently calls `anim.effect.getComputedTiming().iterations` would continue to work when this new property is used. However, under this proposal, code that calls `anim.effect.getTiming().iterations` would need to be updated to call `anim.effect.getTiming.computedIterations` instead.

That said, I think we already have this problem in that anyone currently calling `anim.effect.timing.iterations` and assuming it will be a float (which I expect is not uncommon since it's less to type than `anim.effect.getComputedTiming().iterations`) will have the same problem.

@shans, @dstockwell Any thoughts about this?

@heycam, @bzbarsky Is returning snapshot objects generally the preferred approach over maintaining live objects?

_Copied from original issue: w3c/web-animations#168_

**Comment by birtles** [comment]
_From @alancutter on September 14, 2016 7:56_

One slight downside to dropping `effect.timing` is its no longer possible to see the specified value of `fill` or `duration` as they get "resolved" in [`getTiming()`](https://w3c.github.io/web-animations/#dom-animationeffectreadonly-getcomputedtiming).

Dropping the live `effect.timing` object SGTM though, I don't think there are many use cases for it not being a snapshot.

**Comment by birtles** [comment]
> One slight downside to dropping effect.timing is its no longer possible to see the specified value of fill or duration as they get "resolved" in getTiming().

The proposal here is that `getTiming().fill` returns the specified value, e.g. `"auto"`, and we add a `computedFill` member for the computed value, e.g. `"none"`. Likewise for `duration`.

**Comment by birtles** [comment]
_From @bzbarsky on September 15, 2016 2:37_

> Is returning snapshot objects generally the preferred approach over maintaining live objects?

It really depends on the situation and the design considerations (performance tradeoffs, how the objects will typically be used, etc).

**Comment by birtles** [comment]
@BorisChiou, @hiikezoe let me know if you have any thoughts. Just to clarify one point of confusion, the idea is that you'd have:

``` js
anim.effect.getTiming().duration // "auto"
anim.effect.getTiming().computedDuration // 0
```

**Comment by birtles** [comment]
_From @hiikezoe on September 20, 2016 22:39_

I like this idea.  
We do update individual property in many places in test code but I don't think it's common to change individual property dynamically in the real world.

**Comment by birtles** [comment]
_From @shans on September 29, 2016 4:28_

The _More awkward to update an individual timing property_ disadvantage is a major disadvantage, I think.

Modification of animations in-flight is a major capability that the unshipped parts of the API will give us, and this proposal makes that significantly harder for timing properties.

Anecdata-ly, I found myself doing this a reasonable amount when playing with the polyfill.

In contrast, looking at the advantages:
- _2 fewer interfaces_ - this means nothing to web developers.
- _Fewer live objects_ - sort of, but it's not likely that people will actually 'tear off' and store the timing.
- _Consistency within the API — keyframes and timing properties follow the same idiom_ - obviously we're trading off consistency with the style approach here. Not sure we buy anything.
- _Bulk setting of timing properties is easier_ - not really, unless you're talking about the very specific use case of bulk updating a large set of animations to all have exactly the same timing. Even here, wrapping the update in a loop will end up looking almost exactly the same.

**Comment by birtles** [comment]
_From @dstockwell on September 29, 2016 5:32_

> The More awkward to update an individual timing property disadvantage is a major disadvantage, I think.

I thought that's how we ended up with the current design. Getting/setting timing being a more frequent use case than getting/setting keyframes, so we thought it OK to be different/harder.

**Comment by birtles** [comment]
I don't think setting individual timing properties after setting up the animation is common since in most cases doing that that will cause the animation to jump which is generally undesirable. (Test code etc. being obviously quite different since you're not concerned with smooth motion.)

Regarding bulk updating, it was partly an observation from seeing people like [Paul & Surma](https://www.youtube.com/watch?v=rn5s6H_Yamo) use the API and store a separate timing object for passing to `animate()`. It seems a bit odd that you can pass that to `animate()` but beyond that point you can't use it to update an animation.

I think consistency within the API is more important than consistency with the style API since internal consistency trumps external consistency and it's not actually a good parallel with the style API anyway (since the style API doesn't actually represent specified style, but only style specified on the style attribute).

**Comment by birtles** [comment]
See also https://github.com/w3ctag/design-principles/issues/34

**Comment by birtles** [comment]
Just to close the loop on this, I discussed this with Shane and Ian in November 2016 and I think we were thinking that with the addition of `setTimingProperty` for updating an individual property, this might be ok.
See [meeting minutes](https://docs.google.com/document/d/1oqxM46jdM4fWKqRAEmy1KE5FTgW0dvIOo273B5mM8Ao/edit?ts=581fea65#heading=h.q7xdq6xj5ze5).

**Comment by birtles** [comment]
I had a go at implementing this in Firefox just to see how it feels. The modified IDL I used is:

```webidl
dictionary EffectTiming {
  double                              delay = 0.0;
  double                              endDelay = 0.0;
  FillMode                            fill = "auto";
  double                              iterationStart = 0.0;
  unrestricted double                 iterations = 1.0;
  (unrestricted double or DOMString)  duration = "auto";
  PlaybackDirection                   direction = "normal";
  DOMString                           easing = "linear";
};

dictionary PartialEffectTiming {
  double                              delay;
  double                              endDelay;
  FillMode                            fill;
  double                              iterationStart;
  unrestricted double                 iterations;
  (unrestricted double or DOMString)  duration;
  PlaybackDirection                   direction;
  DOMString                           easing;
};

dictionary ComputedEffectTiming : EffectTiming {
  unrestricted double   computedDuration = 0.0;
  FillMode              computedFillMode = "none";
  unrestricted double   endTime = 0.0;
  unrestricted double   activeDuration = 0.0;
  double?               localTime = null;
  double?               progress = null;
  unrestricted double?  currentIteration = null;
};

interface AnimationEffectReadOnly {
  ComputedEffectTiming getTiming();
  void setTiming(optional EffectTiming timing);
  void updateTiming(optional PartialEffectTiming timing);
};
```

As you can see I took the liberty of renaming some of the dictionaries at the same time. (Now that we no longer have `AnimationEffectTiming(ReadOnly)` we now longer need the `Properties` on `AnimationEffectTimingProperties` but I decided to try and simplify the names further still.)

The `Partial` naming is based on [`Partial`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#partial-readonly-record-and-pick) from TypeScript.

The two questions I have before specing this are:

1) Obviously adding `setTiming` and `updateTiming` to `AnimationEffectReadOnly` don't make sense so where should they go? On `KeyframeEffect` itself? Or should we fix this and issue #2068 at the same time?

     For solving #2068 we'd rename the interface `AnimationEffect` and work out how these methods work when applied to animations tied to markup (CSS animations/transitions).

2) Is having `computedDuration` and `computedFill` a bit weird? Is it weird that `activeDuration` is a computed property but `duration` is not? E.g. if you do:
```js
const timing = anim.effect.getTiming();
timing.duration = 3000;
timing.activeDuration = 6000;
anim.effect.updateTiming(timing);
```

only `duration` will have any effect, `activeDuration` will be ignored.

Also, it just occurred to me, might it be useful to have `setTiming` / `updateTiming` return the updated computed timing so you can chain calls together?

I'm not sure if there's a way of expressing partial dictionaries in WebIDL that's less redundant that what I have above.

**Comment by bzbarsky** [comment]
> I'm not sure if there's a way of expressing partial dictionaries in WebIDL that's less redundant that what I have above.

There isn't, for the meaning of "partial" used here (which is different from what Web IDL means by "partial dictionary", as defined at <https://heycam.github.io/webidl/#dfn-partial-dictionary>).

**Comment by birtles** [comment]
Great, thanks Boris!

Yes, I should avoid Partial. I wonder if there's a better term for distinguishing between a dictionary where all members have default values and one without any. Possibly `ResetEffectTiming` for the one with default values? Or even just `DefaultEffectTiming`?

**Comment by birtles** [comment]
After few further thoughts on this API.

**Observation 1: `updateTiming` feels a little awkward.**

[`setState`](https://reactjs.org/docs/react-component.html#setstate) in React merges the provided keys with the existing state. It might be more natural/familiar to have `setTiming` do likewise and, if necessary, add `replaceTiming` or `resetTiming` to clobber existing state.

I say _if necessary_ because I wonder what the use cases are for resetting all timing where you're not already specifying all the members. e.g. if you're doing `effectA.setTiming(effectB.getTiming())` then you don't need the reset behavior since you're specifying all the members already. React [dropped `replaceState`](https://github.com/facebook/react/issues/3236) since they found it unnecessary and harmful in some cases.

**Observation 2: We may want to introduce `resetTiming` for CSS animations/transitions later**

See discussion in #2068.

The proposal there is we would have a subclass of `KeyframeEffect` used by CSS animations/transitions that adds `resetTiming()` which could be used to make overriden timing properties revert to tracking markup.

One possibility, and this might be a bit too complex, is to introduce `resetTiming` on `AnimationEffect` itself with the behavior that it takes an `EffectTiming` dictionary _without default values_, and for each unspecified value we have the following behavior:

* If this is a markup-bound animation, use the value provided by markup (e.g. `transition-duration`, `animation-duration`) -- basically drop any overidden value.
* Otherwise, use the default value from `DefaultEffectTiming` or whatever we call it.

That way, on a markup-bound animation, `effect.resetTiming()` removes all overrides. On other animations it resets everything, and `effect.resetTiming({ duration: 3000 })` resets everything exception the duration.

I suspect that might be conflating two concepts however, and we should probably have separate methods for resetting to the Web Animations default vs resetting to the markup value.

**Comment by graouts** [comment]
Thanks for putting this all together @birtles. I'm in support of dropping the `ReadOnly` interfaces. I think the only real disadvantage here is the loss of a simple way to update timing properties individually, which I think is a real use case. One in particular to me is developer tools, such as the WebKit Web Inspector, where we'll definitely want to offer a way, graphical or more code-oriented, to toy with individual timing properties. But I think we can have a good answer to that if we make members of `AnimationEffectTimingProperties` optional and treating unspecified values as a way to **not** overwrite the current values. That means that we should be able to do this:

```javascript
// Current API
anim.effect.timing.duration *= 2;
// Proposed API
anim.effect.updateTiming({
    duration: anim.effect.getTiming().computedDuration * 2
});
```

In practice it's pretty similar to what you were proposing but somehow feels lighter-weight to me. And in cases where you want to set the new duration to a value that is not tied to a previous value, then it starts being a lot nicer:

```javascript
anim.effect.updateTiming({ duration: 2000 });
```

As for the name, if we allow for `AnimationEffectTimingProperties` values to be optional, then I think `updateTiming()` is a superior name since we're not setting all timing properties, but just some based on the keys specified in the provided dictionary.

Otherwise, if we provide a complete snapshot coming out of `getTiming()`, I think `setTiming()` is a better name, since you're really setting all properties.

**Comment by flackr** [comment]
Thinking aloud,
* The need to prefix some specified properties with `computed` and provide the specified as well seems a bit strange.
* The update/reset/set API's seem a bit hard to reason about. As far as I can tell, there is some internal state as to what has been overridden?

> But I think we can have a good answer to that if we make members of `AnimationEffectTimingProperties` optional and treating unspecified values as a way to *not* overwrite the current values.

As a strawman proposal along these lines, what if :
* `anim.effect.timing` are optional overrides for the animation timing (initially blank when getting a CSS animation).
* `anim.effect.getTiming()` returns a snapshot of specified properties (CSS + overrides from timing)
* `anim.effect.getComputedTiming()` returns a snapshot of the final values, including computed duration and fill.

Then you can easily override a property:
```js
anim.effect.timing.duration = 3000;
```
Copy an animations specified timing to another:
```js
anim2.effect.timing = anim1.getTiming();
// Optionally make additional modifications to timing
```
Revert to CSS values:
```js
anim.effect.timing.duration = null; // or undefined, or delete the member.
```

This is somewhat analogous to inline style, CSS style, and computed style, though making use of snapshots to avoid live objects.

**Comment by birtles** [comment]
Thanks for the feedback!

> ```javascript
> // Current API
> anim.effect.timing.duration *= 2;
> // Proposed API
> anim.effect.updateTiming({
>     duration: anim.effect.getTiming().computedDuration * 2
> });
> ```

How is this different to the proposal in this issue? It seems identical to me?

> * `anim.effect.timing` are optional overrides for the animation timing (initially blank when getting a CSS animation).
> * `anim.effect.getTiming()` returns a snapshot of specified properties (CSS + overrides from timing)
> * `anim.effect.getComputedTiming()` returns a snapshot of the final values, including computed duration and fill.

I can see the advantage this approach offers with regards to overrides, but I feel like this is a little confusing. If I want to know the duration of an animation, which of the three possible places do I look?

Also, WebIDL doesn't allow dictionaries as attribute types so I'm not sure what sort of object `timing` would end up being.

So I guess I still lean towards a write-only approach like `setTiming()` or `updateTiming()` although I prefer the `setTiming()` name (but still keeping the same merge behavior) based on its parallel with React's `setState()`.

Keeping `getTiming()` and `getComputedTiming()` separate might be a good idea though.

**Comment by graouts** [comment]
@birtles The way I thought it differed was that you could pass an imcomplete set of properties and not have to start from the output of getTiming() first.

As for the name, `setTiming()` still sounds to me like we're replacing all properties, while `updateTiming()` indicates select properties can be set. Maybe `setTimingProperties()` or `updateTimingProperties()` would be clearer. I don't really give much weight to how React might or might not do something, JS frameworks come and go, Web APIs are forever (for better or worse). But I wouldn't oppose `setTiming()` vs. `updateTiming()`, I think both can work.

@flackr I don't think there is a clear enough difference just by looking at names between `.timing`, `getTiming()` and `getComputedTiming()`.

**Comment by birtles** [comment]
> @birtles The way I thought it differed was that you could pass an imcomplete set of properties and not have to start from the output of getTiming() first.

@graouts Oh sorry, no the WebIDL lets you pass an incomplete set of properties (that's what the very confusing `partial` naming was supposed to convey). So I think we're on the same page here.

> As for the name, `setTiming()` still sounds to me like we're replacing all properties, while `updateTiming()` indicates select properties can be set.

Ok, I can live with `updateTiming()`. I'd rather keep these names short, if possible, so I'd prefer not to add `Properties` to the end.

Just a thought, does `changeTiming()` make any sense? The reason is I'm currently working on the name for the method to update the playback rate while maintaining the current time and I'm wondering if `changePlaybackRate()` makes sense. I'm not sure why, but `updatePlaybackRate()` feels clunky somehow.

> @flackr I don't think there is a clear enough difference just by looking at names between `.timing`, `getTiming()` and `getComputedTiming()`.

I wonder what you think about modifying @flackr's proposal to include just `getTiming()` and `getComputedTiming()` (i.e. no `.timing`). It would avoid the awkwardness of having `getTiming()` return `duration` AND `computedDuration`, not to mention returning `duration` (a specified value) AND `activeDuration` (a computed value).

**Comment by graouts** [comment]
I really am fine with any name, with a preference for either `changeTiming()` and `updateTiming()`.

As for reading timing, `getTiming()` and `getComputedTiming()` with no accessor sounds fine too.

**Comment by flackr** [comment]
> If I want to know the duration of an animation, which of the three possible places do I look?

I was thinking that you'd look at getComputedTiming(), but I admit it is confusing. I can live with overrides being tracked internally after calling `updateTiming()` and not having an accessor.
