### ISSUE TITLE
Fix link errors reported by Bikeshed

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#208]
Bikeshed notes several referencial errors in the following specifications:
- [x] [CSS Color 4](https://drafts.csswg.org/css-color-4/)
- [x] [CSS Counter Styles 3](https://drafts.csswg.org/css-counter-styles-3/)
- [x] [CSS Extensions 1](https://drafts.csswg.org/css-extensions/)
- [ ] [CSS Font Loading 3](https://drafts.csswg.org/css-font-loading-3/)
- [x] [CSS Images 4](https://drafts.csswg.org/css-images-4/)
- [x] [CSS Inline Layout 3](https://drafts.csswg.org/css-inline-3/)
- [ ] [CSS Logical Properties 1](https://drafts.csswg.org/css-logical-props-1/)
- [ ] [CSS Multicol 1](https://drafts.csswg.org/css-multicol-1/)
- [ ] [CSS Multicol 2](https://drafts.csswg.org/css-multicol-2/)
- [ ] [CSS Pseudo-Elements 4](https://drafts.csswg.org/css-pseudo-4/)
- [ ] [CSS Round Display 1](https://drafts.csswg.org/css-round-display-1/)
- [ ] [CSS Scoping](https://drafts.csswg.org/css-scoping-1/)
- [ ] [CSS Scroll Snap 1](https://drafts.csswg.org/css-scroll-snap/)
- [ ] [CSS Shapes 2](https://drafts.csswg.org/css-shapes-2/)
- [ ] [CSS 2015](https://drafts.csswg.org/css-2015/)
- [ ] [CSS Step Sizing 1](https://drafts.csswg.org/css-step-sizing-1/)
- [ ] [CSS Tables 3](https://drafts.csswg.org/css-tables-3/)
- [ ] [CSS Transforms 1](https://drafts.csswg.org/css-transforms/)
- [x] [CSS User Interface 3](https://drafts.csswg.org/css-ui-3/)
- [x] [CSS User Interface 4](https://drafts.csswg.org/css-ui-4/)
- [ ] [CSS Writing Modes 3](https://drafts.csswg.org/css-writing-modes-3/)

_Note that I didn't include WG Notes, CSS Expressive Generalizations and Gadgetry 1 and the documents listed under 'Other Documents' at https://drafts.csswg.org/. If considered valuable, the section should be added there, too._

Sebastian

**Comment by frivoal** [comment]
For CSS-UI-3, I get this:

> LINK ERROR: Multiple possible 'element' refs for 'svg'.
> Arbitrarily chose the one in svg2.
> If this is wrong, insert one of the following lines into a <pre class=link-defaults> block:
> spec:svg2; type:element; text:svg
> spec:svg2; type:element; text:svg

This looks like an error with bikeshed of with the link data rather than with my spec.

@tabatkins, any suggestion?

**Comment by tabatkins** [comment]
Ugh, this isn't a Bikeshed error, it's SVG using markup patterns that make Shepherd's best-effort parser think it's defining the SVG element twice (and I don't blame it).

**Comment by plinss** [comment]
CSS-UI-3 errors fixed in the spec parser (and maybe a few others too). Be sure to run 'biksshed update' to get new anchor data

**Comment by svgeesus** [comment]
This was reported in 2016 (and several specs fixed as a result).

It isn't clear, given the rapid pace of spec changes in general, whether there are still errors in these specifications in 2024. Also, since no errors were listed, it is pretty hard to check.

I suggest in future opening specific issues on each specification that has link errors, rather than one mega-issue like this.
