### ISSUE TITLE
[web-animations-1] Step 1 of "Updating the finished state" is unclear

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#2088]
Reading the steps for [Updating the finished state](https://drafts.csswg.org/web-animations-1/#updating-the-finished-state), I'm a little confused by step 1:

> Let the unconstrained current time be the result of calculating the current time substituting an unresolved time value for the hold time if did seek is false. If did seek is true, the unconstrained current time is equal to the current time.

I don't understand what "calculating the current time substituting an unresolved time value for the hold time" means. Does it mean to compute the current time with the steps defined in [The current time of an animation](https://drafts.csswg.org/web-animations-1/#the-current-time-of-an-animation) but replacing any mention of "hold time" with "unresolved time value"? In other words, compute the current time disregarding any currently set value for hold time?

**Comment by birtles** [comment]
Yes, that's right.
