### ISSUE TITLE
[css-color-3] Dangling link to `appearance` property in CR of Color-3

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#2089]
From https://github.com/w3c/csswg-drafts/issues/1982#issuecomment-349893590

> In [css-color-3] §4.5.1 CSS2 system colors, the note at the bottom references the “CSS3 UI appearance property” and links to css-ui-3, but the property has been moved to Level 4.

> Either the link in [css-color-3] should be updated, or a note should be added to [css-ui-3] clarifying the appearance property has been moved.

Fix the link in the proposed Rec by pointing to UI 4? Or remove the reference entirely?

**Comment by tabatkins** [comment]
I think we can just drop it. It's not doing too much interesting there.

**Comment by GloverDonovan** [comment]
I did a grep for `#appearance` and found it in `Overview.src.html` but not in `Overview.html`. What's the difference between the two?

The section in question appears to be commented out in https://www.w3.org/TR/css-color-3/. Does this mean it's already fixed?

**Comment by frivoal** [comment]
> What's the difference between the two?

`Overview.html` is generated from `Overview.src.html` using the [old processor tool](https://wiki.csswg.org/tools/spec-processor) that we used to use before we switched to [bikeshed](https://tabatkins.github.io/bikeshed/). Unfortunately, that tool is only accessible to group members.

However, for the sake of a pull request, only editing Overview.src.html should be enough. Maybe leave a comment in the pull request saying that whoever merges it should remember to re-run the processor afterwards.

> I did a grep for #appearance and found it in Overview.src.html but not in Overview.html

Not sure why that is. It is there as well: https://github.com/w3c/csswg-drafts/blob/master/css-color-3/Overview.html#L4605 Are you looking at some other file or version?

**Comment by GloverDonovan** [comment]
Found the problem. `.hgignore` ignores all files matching `*/Overview.html` (which [ripgrep](https://github.com/BurntSushi/ripgrep) uses by default). I had to tell `rg` to not honor ignore files before it could search through `Overview.html`.

Thanks for the information. I'll update `Overview.src.html` soon (which should also get rid of `appearance` being in the index after running the processor).

**Comment by GloverDonovan** [comment]
Actually, does this entire section need to be updated as well? I assume that css-ui-3 and css-ui-4 are related to the different levels of the CSS specification and that `appearance` is currently a part of the level 4 specification (i.e. not level 3).

**Comment by frivoal** [comment]
The whole note should be dropped. 

`appearance` was once expected to be able to make ordinary elements look like native controls and to be able to make native controls look like ordinary elements. The current version of the specification only supports doing the later, but that note was written assuming it could do the former. So the note is essentially wrong, and should be removed.
