### ISSUE TITLE
[css-grid] when to apply the clamping for fit-content() tracks?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#209]
The specification of fit-content() track sizes is rather vague:
https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-fit-content

My understanding is that a "fit-content(X)" track size should behave as
"minmax('auto', 'max-content'))" while running the "Resolve Intrinsic Track
Sizes" algorithm:  https://drafts.csswg.org/css-grid/#algo-content
with the additional tweak that if the track's base size becomes larger
than X then it is clamped to X.

Is that correct?

If yes, then I have more questions:
1. should the clamping be applied at every step of the algorithm, or only
after the algorithm is done (i.e. between 12.5 and 12.6)?
2. should the "growth limit" be clamped at any point while running
the algorithm?  (I'm guessing not, since "12.6 Maximize Tracks" says to
clamp it there, but the spec could be clearer on this)
https://drafts.csswg.org/css-grid/#algo-grow-tracks

Thanks,
Mats

**Comment by fantasai** [comment]
This is a good point. Originally, I thought that just clamping the growth limit before maximizing the track would work, so I had edited that in. However, in the case of an item spanning both a fit-content() track and a max-content track, this won't give the right behavior: we want the max-content track to absorb any extra space needed for the item into its growth limit once the fit-content() track has hit its maximum.

We're not yet sure of the exact edits to make this fix, but we should definitely fix it. In the meantime... note that the auto minimum is stronger than the specified maximum in fit-content().

**Comment by tabatkins** [comment]
Looks like we want:

1. Initially, set the growth limit to the fit-content() argument.
2. In 12.5.1, let this fall into the "max-content maximum" case, and apply clamping.
3. In 12.5.2, let this fall into the steps 5 and 6, and clamp both times (in the distribution algo).

Then "Maximize Tracks" can drop the mention of fit-content(), because the growth limit will already have been handled.

**Comment by MatsPalmgren** [comment]
Thanks for the quick response!  I agree that integrating the fit-content() clamping into
the track sizing algorithm is a good idea.

I hacked our layout to test this feature a bit and it seems like the steps Tab
suggested above leads to the fit-content() track growing beyond what it would
be if it were "minmax(auto,max-content)" - is this expected?
I'm using "grid-template-columns: fit-content(40%) minmax(100px, 1fr);"
and when the window is wide enough that 40% is larger than the largest of the
item max-content contributions in the first column then the first column is 40%.
However, if I remove Tab's step 1, then it seems to work as expected.

I'm still a bit unsure what the exact behavior should be though, so it would good
if you can provide a Grid example I can use to verify I'm implementing this correctly...

**Comment by tabatkins** [comment]
Oh, you're right, it shouldn't get larger than max-content.  We should *just* be clamping, ignore step 1.  (This should act exactly like minmax(auto, max-content) except with the clamps.)

**Comment by fantasai** [comment]
Okay, I checked in some changes. Mats, Tab, please take a look and let me know if anything doesn't seem quite right? :)
