### ISSUE TITLE
[css-counter-styles] Classification for 'cjk-earthly-branch' and 'cjk-heavenly-stem'

### ISSUE THREAD

**Issue by c933103** [w3c/csswg-drafts#2096]
In https://drafts.csswg.org/css-counter-styles/#predefined-counters , 'cjk-earthly-branch' and 'cjk-heavenly-stem' are currently listed as an alphabetic system, so that after a, b, c, d .... z the last symbol in the list being used, it would become aa, ab, etc. for the next entry.

However, it seems more suitable for them to function as either cyclic, fixed, or another undefined style, instead of the alphabetic currently defined in the document?

For example, the use of earthly branch and heavenly stem in naming days and years seems to be cyclic.

On the other hand, when using the system in Chinese chemical naming as well as for representing unidentified individuals in Japanese legal system seems to go up to the max of the list only. After that it either changed to Chinese numeric numbering or switch to another system

And then, third case that I see, for example for some temple lots, is similar to "alphanumeric", however, instead of go from a,b,c,d...z,aa,ab, if it is known that the list have more than 10 or 12 items (length of each system), then it would start from aa as the first list item. Is there any existing algorithm in the system that can represent the style?

**Comment by upsuper** [comment]
cc @r12a @w3c/clreq

**Comment by tabatkins** [comment]
Yeah, I'll leave determination of what the best repetition behavior is to the experts, and update the spec if necessary.

> And then, third case that I see, for example for some temple lots, is similar to "alphanumeric", however, instead of go from a,b,c,d...z,aa,ab, if it is known that the list have more than 10 or 12 items (length of each system), then it would start from aa as the first list item. Is there any existing algorithm in the system that can represent the style?

No direct algorithm, but you can explicitly start the counter at a higher value to get it to begin at "aa".

**Comment by tabatkins** [comment]
Marking as "Comment Satisfied" since the PR closing this was submitted by the CLReq people. Needs a WPT test to confirm that it doesn't loop around to alphabetic any longer.
