### ISSUE TITLE
[css-counter-styles] Suggestion for new styles

### ISSUE THREAD

**Issue by c933103** [w3c/csswg-drafts#2097]
Proposed addition to https://drafts.csswg.org/css-counter-styles/#predefined-counters :

suzhou-numeral

The rule for this numeral is displayed at https://en.wikipedia.org/wiki/Suzhou_numerals - as sometimes it needs to rotate some numeral, I guess it should be a complex counter.

cjk-tally-mark

```
@counter-style cjk-tally-mark{
  system: additive;
  additive-symbols: 5 "\1D376", 4 "\1D375", 3 "\1D374", 2 "\1D373", 1 "\1D372";
  /* Relevant chracters still in proposal status in Unicode, see https://blogs.adobe.com/CCJKType/2016/01/ideographic-tally-marks.html */
  suffix: " ";
}
```

cjk-stem-branch

```
@counter-style cjk-stem-branch {
  system: cyclic;
  symbols:
 "\7532\5B50"" "\4E59\4E11" "\4E19\5BC5" "\4E01\536F" "\620A\8FB0" "\5DF1\5DF3" "\5E9A\5348" "\8F9B\672A" "\58EC\7533" "\7678\9149";
  /* 甲子 乙丑 丙寅 丁卯 戊辰 己巳 庚午 辛未 壬申 癸酉 */
 "\7532\620C" "\4E59\4EA5" "\4E19\5B50"" "\4E01\4E11" "\620A\5BC5" "\5DF1\536F" "\5E9A\8FB0" "\8F9B\5DF3" "\58EC\5348" "\7678\672A";
  /* 甲戌 乙亥 丙子 丁丑 戊寅 己卯 庚辰 辛巳 壬午 癸未 */
 "\7532\7533" "\4E59\9149" "\4E19\620C" "\4E01\4EA5" "\620A\5B50"" "\5DF1\4E11" "\5E9A\5BC5" "\8F9B\536F" "\58EC\8FB0" "\7678\5DF3";
  /* 甲申 乙酉 丙戌 丁亥 戊子 己丑 庚寅 辛卯 壬辰 癸巳 */
 "\7532\5348" "\4E59\672A" "\4E19\7533" "\4E01\9149" "\620A\620C" "\5DF1\4EA5" "\5E9A\5B50"" "\8F9B\4E11" "\58EC\5BC5" "\7678\536F";
  /* 甲午 乙未 丙申 丁酉 戊戌 己亥 庚子 辛丑 壬寅 癸卯 */
 "\7532\8FB0" "\4E59\5DF3" "\4E19\5348" "\4E01\672A" "\620A\7533" "\5DF1\9149" "\5E9A\620C" "\8F9B\4EA5" "\58EC\5B50"" "\7678\4E11";
  /* 甲辰 乙巳 丙午 丁未 戊申 己酉 庚戌 辛亥 壬子 癸丑 */
 "\7532\5BC5" "\4E59\536F" "\4E19\8FB0" "\4E01\5DF3" "\620A\5348" "\5DF1\672A" "\5E9A\7533" "\8F9B\9149" "\58EC\620C" "\7678\4EA5";
  /* 甲寅 乙卯 丙辰 丁巳 戊午 己未 庚申 辛酉 壬戌 癸亥 */
  suffix: "、";
}
```

**Comment by upsuper** [comment]
The latter two should probably go to [Ready-made Counter Styles](https://www.w3.org/TR/predefined-counter-styles/). You can open new issue there directly.

I have no idea about suzhou-numeral. Maybe [CLReq](https://w3c.github.io/clreq/) should add a section describing list styles used in Chinese. It is not clear to me whether it's really worth adding given its complexity and probably lack of use.

**Comment by upsuper** [comment]
cc @r12a I guess you may be interested in tracking it for i18n?

**Comment by c933103** [comment]
For Suzhou-numeral, they are still being used in number labelling in various aspect although they are increasingly rare (If we use https://www.ethnologue.com/about/language-status EGIDS to measure then it have reached about 7 or 8a in Hong Kong and Macau while reached 8b or 9 in other Chinese speaking area). 

As most of the usage of this type of numeral is in number marking aspect especially in traditional commercial activity, I am not really sure about if this type of numeral has been used in making list.

**Comment by c933103** [comment]
As of list style that are commonly used in Chinese, I think 95%+ case are cathced by the use of Hinduarabic numeral, latin alphabet upper/lower case, Roman numeral upper/lower case, chinese formal/informal, as well as their parenthesised or circled variants or squared variants. Usage of cjk-earthly-branch already exists in the spec and cjk-stem-branch I proposed can probably be said as limited to certain fields? For the ideographic tally mark, they are mainly used for tally, and I think I have see them used in ordered list too, but I don't have a concept of in which situation would it be used.

**Comment by r12a** [comment]
I added cjk-tally-mark and cjk-stem-branch to the Ready-made Counter Styles ED (See https://github.com/w3c/predefined-counter-styles/issues/18 and https://github.com/w3c/predefined-counter-styles/issues/19).

**Comment by tabatkins** [comment]
It sounds like this issue can be closed, since Suzhou numerals aren't shown to be used in list numbering, and the other suggestions have been added to Ready-Made Counter Styles already.  Is this correct?

**Comment by r12a** [comment]
@tabatkins  Yes.  The additions aren't yet in TR, but are in the ED, and i'm hoping to synch them quite soon.

**Comment by r12a** [comment]
Now in the /TR version of the document.

https://www.w3.org/TR/predefined-counter-styles/#cjk-tally-mark
https://www.w3.org/TR/predefined-counter-styles/#cjk-stem-branch

Should we close this issue?

**Comment by fantasai** [comment]
@r12a If you say so :)
