### ISSUE TITLE
[css-shadow-parts] Motivation missing reasons

### ISSUE THREAD

**Issue by tmlayton** [w3c/csswg-drafts#2099]
I‘m excited for css-shadow-parts! A bit of feedback on the draft – the [Motivation](https://tabatkins.github.io/specs/css-shadow-parts/#motivation) section explains why this proposal is better than others, but as far as why this is valuable in general it just says "for obvious reasons". I wouldn‘t say the reasons are immediately obvious for everyone. For example, our product design system at Shopify doesn‘t have any concept of theming so that problem is not top-of-mind for me. I personally would like to see some more details on the reasons why this useful.

**Comment by tabatkins** [comment]
That probably does need some expansion, but there *is* some explanation there already:

> (The ubiquity of UA-specific pseudo-elements for the various input elements shows this.)

But yeah, I'll make it less patronizing.

**Comment by fergald** [comment]
Please reopen if you think this needs more elaboration.
