### ISSUE TITLE
[css-align][css-inline] Deal with first vs last baseline

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#210]
The CSS Box Alignment spec introduces the ability to choose the last baseline instead of the first for baseline-aligning boxes. This ability needs to also be ported to the `vertical-align` property (in CSS Inline Layout). Note, the `vertical-align` property is especially wonky because for inline-tables it uses the first baseline and for inline-blocks it uses the last.

The current syntax in Box Alignment is to contrast `baseline` (imported from Flexbox) with `last-baseline` (new in Box Alignment). However, using prefixed keywords would result in a combinatorial explosion if we added it to the `alignment-baseline` subproperty of `vertical-align`.

Some solutions to this problem:
1. Explode `alignment-baseline`. 
2. Use `last` and `baseline` as separated keywords in `align/justify-self/content` as well as `alignment-baseline`.
3. Use `last-baseline` in `align/justify-self/content` and `last baseline` in `alignment-baseline`.
4. Introduce a new property to choose `first` vs `last` for `vertical-align`, and have `last-baseline` decompose to `last` in that property plus `baseline` for `alignment-baseline`.
5. Introduce `first-baseline` and `last-baseline` to `alignment-baseline`(to match Align), but also allow `first` and `last` space-separated prefixes for all values of `alignment-baseline`(to avoid explosion). (This means that both `first-baseline` and `first baseline` would be valid, but eh?)
6. Something else?

**Comment by fantasai** [comment]
Discussion on the WG call rejected 1 & 3, seem to have a slight preference for 4. We should probably investigate whether/how 'alignment-baseline' is applied to non-inlines, since that might make a difference here as well.

**Comment by FremyCompany** [comment]
Just said on today's call I had a preference for a "baseline-choice: first / last".

**Comment by FremyCompany** [comment]
Fantasai pointed out we want an auto value to reflect tables choosing the first and inline-block the last by default.

**Comment by tabatkins** [comment]
Resolution was to change the alignment properties to have `[ first | last ]? baseline`.

**Comment by fantasai** [comment]
Fix checked in https://github.com/w3c/csswg-drafts/commit/4f6d5ad1bc4dc0be3ca61c894191a397b7005d21
