### ISSUE TITLE
[css-shaders] CSS Shaders Security

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2100]
I cannot log in to public discussion of this and I cannot post solution.

I propose the shaders be disabled on https pages (like banks' pages). Additional X-Shader-Option:DENY, SAMEORIGIN (like for frames) header to deny it also in normal http sites (not encrypted). This shall prevent steal of data. 

I prefer security than graphic effects.

**Comment by tabatkins** [comment]
CSS Shaders are not an active technology, precisely because of the security/privacy concerns that we couldn't work around. (Plus some implementation problems.)
