### ISSUE TITLE
[css-flexbox] Leftover from #1920

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2103]
[CSS Flexbox](https://drafts.csswg.org/css-flexbox/#min-size-auto) says

> To provide a more reasonable default minimum size for flex items, this specification introduces a new `auto` value as the initial value of the `min-width` and `min-height` properties defined in CSS 2.1.

But since #1920 is is false, now this new initial value is defined in CSS Sizing.

So Flexbox should say something similar to [CSS Grid](https://drafts.csswg.org/css-grid/#min-size-auto):

> To provide a more reasonable default minimum size for flex items, this specification defines that the `auto` value of `min-width`/`min-height` applies an automatic minimum size in the main axis to flex items whose `overflow` is `visible` in the main axis.

Additionally there is a problem with the bikeshed syntax, https://github.com/w3c/csswg-drafts/blob/206de7888ae48025ebda609f3c1dceec5e27d57e/css-flexbox-1/Overview.bs#L908

is displayed as `‘height: auto’`, which is so misleading. If you use the quote above, this paragraph should probably be deleted anyway.

**Comment by fantasai** [comment]
Done.
