### ISSUE TITLE
[css-transforms-2] `scale` property behavior differs from `scale()` function

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2109]
This is basically just re-opening issue #856 but without the focus being interop.

> `transform: scale(2)`

is equivalent to `transform: scale(2, 2)`, i.e. scaling both x/y.

> `scale: 2`

is equivalent to `transform: scale(2, 1)`, i.e. scaling x only.

That seems inconsistent and surprising. I've yet to meet anyone who expects that `scale: 2` scales in only x.

I understand that `scale` can be used for 3D transforms, but `scale3d()` requires three arguments so I don't think there's any parallel between the arguments used there and here.

CC: @ewilligers @FremyCompany @gregwhitworth

**Comment by tabatkins** [comment]
So here's the problem. You can apply `scale: X` to 3d content. Does `scale: 2` expand in your proposal to `scale: 2 2 1` or `scale: 2 2 2`? 

If the former, that's confusing - on 3d content, `scale: 2` will expand your stuff in the xy plane, but the z plane is left alone.  This breaks expectations with 2d-authored content.

If the latter, that's confusing - what does `scale: 2 3` expand to?

We went with the third confusing option: it expands to `2 1 1`, so only the axises you specify expand at all.  This breaks expectations with `scale(2)`, tho.

Since all the options were bad, we went with the one that's bad in a consistent way, at least.

**Comment by birtles** [comment]
`scale: 2 2 1` seems best to me. I expect > 95% of the time people will be using it with 2D content -- and `scale` most naturally corresponds to `scale()`, not `scale3d()`. Once you're working with 3D content you already expect to be specifying three numbers.

**Comment by birtles** [comment]
I guess what I'm saying is, make `scale` consistent with `scale()`, not `scale3d()`.

**Comment by AmeliaBR** [comment]
Would it be possible to have `scale: 3` expand to `scale: 3 3 3`?  If the current z-axis position is 0, scaling it has no effect. _Except_ if it then upgrades to "3D transform" mode and causes complications that way.

If that's the case (complications from switching to 3D mode), the default should be as @birtles proposed, and have a single value behave the same as the `scale()` function.

**Comment by Crissov** [comment]
> Name: [scale](https://drafts.csswg.org/css-transforms-2/#propdef-scale)
> Value: none | \<number>{1,3}
>
> The `scale` property accepts 1-3 values, each specifying a scale along one axis, in order X, Y, then Z. Unspecified scales default to `1`.

In general, there are two *consistent* expansions of a single value for a property: either repeat it for all possible values (_a &rarr; a a a_) or set one to the explicit value and reset the rest to the default value (_a &rarr; a 1 1_). The more *useful* and, preferably, *intuitive* one of those choices should be specified, but *inconsistent* expansions are not unheard of if they are justified. In this case, resetting unspecified values is neither useful nor intuitively expected, while repeating them is useful and intuitively expected for only one of two scenarios, but that is still more than none. The inconsistent expansion _a &rarr; a a 1_ leads also to useful and expected results in only one of two scenarios, but it's the more common one.

| code | syntax | 2D context | 3D context |
| ---- | ---- | ---- | ---- |
| `scale: 2` = `scale: 2 2 2` | **consistent** | unintuitive + harmful | **intuitive + useful** |
| `scale: 2` = `scale: 2 1 1` | **consistent** | unintuitive + **harmless** | unintuitive + **harmless** |
| `scale: 2` = `scale: 2 2 1` | inconsistent | **intuitive + useful** | unintuitive + harmful |

That means, although all three choices are bad, they are not equally bad. Repetition is the least bad. However, we need also to consider the case where two out of three values have been set explicitly. There are (at least) four possible expansions for the third value: reset to default (_a b &rarr; a b 1_), repeat the first (_a b &rarr; a b a_) or the last (_a b &rarr; a b b_) value and set it to a calculated value(_a b &rarr; a b c_). Resetting is intuitively compatible with the less-favored option for the single-value case, whereas both repetition variants are consistent but arbitrary and hence not intuitive, and the derivation is neither consistent nor (generally) intuitive. 

| code | syntax | 2D context | 3D context |
| ---- | ---- | ---- | ---- |
| `scale: 2 3` = `scale: 2 3 1` | **consistent + systematic** | **intuitive + useful** | unintuitive + ambivalent |
| `scale: 2 3` = `scale: 2 3 2` | **consistent** + arbitrary | unintuitive + harmful | unintuitive + ambivalent |
| `scale: 2 3` = `scale: 2 3 3` | **consistent** + arbitrary | unintuitive + harmful | unintuitive + ambivalent |
| `scale: 2 3` = `scale: 2 3 2.5` | inconsistent + arbitrary | unintuitive + harmful | unintuitive + ambivalent |

That means, a choice needs to be made whether the expansions of a single value and of two values into three values should be consistent with each other or if there is enough reason to treat them differently. I believe there is. The most useful and still intuitive and somewhat consistent solution is to repeat a single value thrice, but to set the third value to `1` if only two values are provided.

> Value: \<'scale-x'> \<'scale-y'> \<'scale-z'>? | <number>
>
> The `scale` property accepts 1-3 values, each specifying a scale along one axis, in order X, Y, then Z. 
> If the last, Z value is left unspecified, it defaults to `1`.
> If only a single value is specified, all axis scale values are set to this same value.

| code | draft | proposed |
| ---- | ---- | ---- |
| `scale: 2` | `scale: 2 1 1` | `scale: 2 2 2` |
| `scale: 2 3` | `scale: 2 3 1` | `scale: 2 3 1` |

**Comment by Nadya678** [comment]
Why you want to add "scale"? the transform:scale(2) is sufficient. Too many of unnecessary properties.

**Comment by emilio** [comment]
I also kind of fail to see the point of the separate properties, fwiw. I get that you may want to cascade them separately, I guess, but it makes `transform` inconsistent overall. For example, `transform: none` wouldn't be enough for an element to be completely untransformed.... Maybe it's worth another issue though, to keep this on topic.

**Comment by ewilligers** [comment]
Author intent would be clearer if we required at least two scales with `none | <number>{2,3}`

translate could optionally be similar: `none | <length-percentage>{2} <length>?`

**Comment by Nadya678** [comment]
But in transform style is there order of values is important for example: 
transform: scale(2), blur(5px), translateX(2px, 2px);
and 
transform: translateX(2px, 2px), blur(5px), scale(2);

do you know how big perfornmance impact has "more CSS styles"? Test Mozilla Firefox current version and Mozilla Firefox 3. scale as separate style is not needed.

**Comment by birtles** [comment]
> Would it be possible to have scale: 3 expand to scale: 3 3 3? If the current z-axis position (and z-axis transform origin) is 0, scaling it has no effect. Except if it then upgrades to "3D transform" mode and causes complications that way.

I spoke to @mattwoodrow about this:

> Our current behaviour is to force an active layer if the resulting transform contains any sort of 3d components, so expanding it to 'scale: 2 2 2' would be a regression for us. It's fairly easy to change that, but harder to know if any web content is depending on the behaviour.
>
> If I recall correctly blink does something similar, but instead uses the presence of 3d transform function (scale3d, transform3d etc), regardless of what the values passed are. They could probably go either way, depending on how they interpret 'scale: 2 2 2'.

So it sounds like it would be some work to make `scale: 2` expand to `scale: 2 2 2` and I wonder if it is worthwhile (I would be glad to be told otherwise though!). Matt also asked if it makes sense to introduce a separate `scale3d` property.

> If that's the case (complications from switching to 3D mode), the default should be as @birtles proposed, and have a single value behave the same as the scale() function.

I (unsurprisingly) still think this is the preferred behavior here.

CC: @mstange

**Comment by Crissov** [comment]
@Nadya678 The order of functions inside the `transform` property is relevant, but the `translate`, `scale` and `rotate` properties cascade normally by specifity. That means they are only equivalent in trivial cases. Both approaches are useful in different scenarios.

**Comment by tabatkins** [comment]
@birtles Right, I'm pretty sure that having it expand to `2 2 2` is the worst of the three options.  It triggers spurious 3d-ness, as you note, and it also doesn't give a clear answer for what to do with `scale: 2 3`.

The other two options are still both bad, and I don't have a *very* strong opinion on which one to use, but my reasoning for/against each is already stated above. If you'd like to litigate this in the group, feel free - I can live with either option.

**Comment by birtles** [comment]
Thanks Tab. Yes, it sounds like the next step is to bring it before the group. I'll be in Toronto next week so I should be able to make the telcon then.

**Comment by smfr** [comment]
FWIW, WebKit also uses 3D-style transform functions (e.g. scale3D(), or what would be a three-argument scale:) as a trigger to do GPU compositing.

**Comment by AmeliaBR** [comment]
@smfr Not just WebKit. And the spec makes other distinctions for 3D-transformed elements versus elements with only 2D transformations. So it's probably important that all the individual transform properties clearly distinguish between 2D and 3D forms.

**Comment by tabatkins** [comment]
Fixed in 48f19e8
