### ISSUE TITLE
[css-fonts] Consider specifying UA should not perform system fallback for Unicode PUA

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#2110]
[5.2 Font Style Matching, step 7](https://drafts.csswg.org/css-fonts/#font-style-matching) explains that system font fallback is to be performed on a per character basis.

Is there consensus for clarifying system font fallback by specifying that system font fallback should/(must?) not be performed for trying to find a glyph for codepoints in the [Unicode Private Use Area and the supplemental Private Use Areas](http://www.unicode.org/versions/Unicode10.0.0/ch23.pdf#G19184)?

**Comment by litherum** [comment]
How would the (U+F8FF Apple Logo) character work? I don’t think anyone explicitly lists the specific font it’s in.

**Comment by litherum** [comment]
Does any browser currently have this proposed behavior?

**Comment by drott** [comment]
> How would the (U+F8FF Apple Logo) character work? I don’t think anyone explicitly lists the specific font it’s in.

I guess if we standardize the recommendation as "should", you could make an exception for U+F8FF? Or use 🍏 + VS15? Or propose to standardize something in Unicode, e.g. GENERIC CORP LOGO + TAG SEQUENCE...TAG TERM for corporate logos? 

On a more serious note: The background for this proposal is that the PUA semantics are defined to be custom to the font - using system wide fallback for them is highly unlikely to return meaningful results to avoid .notdef's.

> Does any browser currently have this proposed behavior?

[We're implementing it in Blink](https://bugs.chromium.org/p/chromium/issues/detail?id=795225) after we discovered that we occasionally receive unsuitable fallback results from the system when querying for PUA codepoints while for example a web icon font has not loaded yet.

**Comment by litherum** [comment]
Unicode has policies against encoding corporate logos (for good reason). Even 🍏 + VS15 would violate this policy.

How does the browser know which font is the one which contains the PUA characters? For example, someone’s font family list may first contain a Chinese font and then an English font, with the English font containing the PUA character (and the Chinese font containing no PUA characters at all). This is a situation where Web content currently relies on font fallback for PUA characters. (Also the Apple logo, as I mentioned above.)

**Comment by litherum** [comment]
If your text engine is finding a broken font, shouldn’t your fix the text engine rather than introduce a new standard?

**Comment by drott** [comment]
> How does the browser know which font is the one which contains the PUA characters? For example, someone’s font family list may first contain a Chinese font and then an English font, with the English font containing the PUA character (and the Chinese font containing no PUA characters at all). This is a situation where Web content currently relies on font fallback for PUA characters. (Also the Apple logo, as I mentioned above.)

As explained in the initial issue description, I am only suggesting to standardize this for **system font fallback**, not for the fallback through the font-family list. I agree resolving PUA usage requires traversing through the family names specified in the font-family list.

But what happens after that: After the font-family list is exhausted, system font fallback occurs, in which usually the engine asks the OS APIs to return a font for a character which it otherwise does not have a glyph for.

The point here is that asking the OS API to return something for PUA characters does not have a well defined behavior.

Example: A web icon font uses its own arbitrary assignment of icon codepoints in PUA to certain icon semantic, but the system fallback codepoint search returns a Devanagari font which for some reason makes use of PUA since that happens to be the only font with PUA coverage on the system. Displaying a Devanagari glyph while the web icon font loads does not make any sense.

> If your text engine is finding a broken font, shouldn’t your fix the text engine rather than introduce a new standard?

I am arguing that no engine can reliably find system fallback fonts for PUA codepoints, as the semantics of codepoints in PUA are intentionally undefined. The benefit in standardizing not to do system fallback for PUA would be that we avoid each engine using whatever random semantically unsuitable font for PUA that it finds on the system. I think the best rendering for not found PUA glyphs would be to display HEX codes using a LastResort blocky rendering, like FF does.

**Comment by Crissov** [comment]
A common scenario where using system fonts for PUA codepoints as a fallback leads to undesired results is indeed an icon font (e.g. [Typicons at U+E000..F1FF](http://s-ings.com/typicons/)), being unavailable but using partially the same codes as the system emoji font does for pre-Unicode compatibility (e.g. Apple Color Emoji for SoftBank [ca. U+E000..E4FF](http://unicode.org/~scherer/emoji4unicode/snapshot/full.html)), although mostly icon fonts use U+F*xyz* and legacy emojis U+E*xyz* (or even U+FE*xyz*).

There are other fields that have coordinated PUA usage across fonts: constructed scripts (esp. [CSUR](http://www.evertype.com/standards/csur/)) and historic scripts (e.g. [MUFI](http://folk.uib.no/hnooh/mufi/)). I'm just pointing this out to make sure nobody thinks it would be okay to limit lookup of PUA characters to the first font in the stack.

**Comment by SergeyMalkin** [comment]
Restricting fallback for whole PUA right in the spec is too broad. There are system fonts covering legacy encodings, like SimSun-ExtB or Mingliu-HKSCS. Logic to fallback or not to fallback to them depends on the OS, document, user settings or maybe something else. 

I understand potential problems with falling back to icon fonts where it is not desirable. This may happen if you are "carelessly" harvesting all installed fonts for any character, including PUA. But this doesn't have to be done this way.

**Comment by drott** [comment]
Thanks for your feedback, Sergey.

> Logic to fallback or not to fallback to them depends on the OS, document, user settings or maybe something else.

I'd be curious to see test cases for this in a layout engine / browser context if you have them. Perhaps we can gain insights about real-world PUA fallback behavior.

> This may happen if you are "carelessly" harvesting all installed fonts for any character, including PUA. But this doesn't have to be done this way.

Similarly, I'd be curious to know which rules or algorithmic approaches you suggest to apply here, except hardcoding fallback fonts for PUA ranges that have turned into conventions.

In any event, thanks to you and litherum@ for sharing your thoughts and discussing this. I gather there is currently no desire to spec this suggestion. Let's close this issue then.

**Comment by SergeyMalkin** [comment]
One possibility is to use known set of fonts on the system based on document language and/or user settings. For example, Edge defaults to SimSun for PUA and switches to MingLiu_HKSCS when user has Hong Kong locale enabled in settings.

**Comment by drott** [comment]
Reopening for discussion. I suggest to mark this as fixed, for the following reasons:

If I am not mistaken in my interpretation of the spec, I found that not doing system fallback for PUA is in fact already spec'ed (thanks to Kunihiko Sakamato for pointing this out in [Chromium issue 803305](https://bugs.chromium.org/p/chromium/issues/detail?id=803305#c8)

https://drafts.csswg.org/css-fonts/#char-handling-issues

> If a given character is a Private-Use Area Unicode codepoint, user agents must only match font families named in the ‘font-family’ list that are not generic families. If none of the families named in the ‘font-family’ list contain a glyph for that codepoint, user agents must display some form of missing glyph symbol for that character rather than attempting system font fallback for that codepoint. 

It's been there for 2years+: https://github.com/w3c/csswg-drafts/blob/master/css-fonts-3/Fonts.src.html#L2667

**Comment by svgeesus** [comment]
> The background for this proposal is that the PUA semantics are defined to be custom to the font - using system wide fallback for them is highly unlikely to return meaningful results to avoid .notdef's.

Mostly, yes (there are some exceptions, like [CSUR](http://www.evertype.com/standards/csur/)).

> the semantics of codepoints in PUA are intentionally undefined

They should be, yes (CSUR is an _intentionally informal_ arrangement for developers of fonts for conlangs)

> https://drafts.csswg.org/css-fonts/#char-handling-issues

Right, agree this actually covers this already.

**Comment by drott** [comment]
Closing as specification already covers this issue and mandates using a missing glyph symbol, not perform fallback.
