### ISSUE TITLE
[css-transforms-2] Should individual transform properties accept unitless 0 angle as a value?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2116]
Right now they don't per spec.

This came up over https://bugzilla.mozilla.org/show_bug.cgi?id=1207734.

@birtles seemed to think it was good for consistency. I tend to agree, but I also dislike having to add yet another exception to that rule, so I don't have any strong opinion. 

Chromium's impl doesn't allow it.

**Comment by emilio** [comment]
cc @ericwilligers

**Comment by ewilligers** [comment]
I think the guideline is to never support unitless 0 angle unless we need to for reasons of legacy compatibility.

Allowing unitless 0 also makes `0 1 0 0` harder to read - it isn't instantly obvious if the author intended rotation around the x or y axis.

The axis() with reordering proposal in #1269 would help here - the author's intent is clear with `axis(0 1 0) 0deg` or `0deg axis(1 0 0)` - but it also weakens the compatibility argument for unitless 0.

**Comment by emilio** [comment]
> I think the guideline is to never support unitless 0 angle unless we need to for reasons of legacy compatibility.

Yeah, that was what I expected to here. I'm glad I caught that on review then :P 

>Allowing unitless 0 also makes 0 1 0 0 harder to read - it isn't instantly obvious if the author intended rotation around the x or y axis.
>
> The axis() with reordering proposal in #1269 would help here - the author's intent is clear with axis(0 1 0) 0deg or 0deg axis(1 0 0) - but it also weakens the compatibility argument for unitless 0.

Indeed, those are both fair points.

@birtles would you be fine with closing this without a spec change?

**Comment by birtles** [comment]
Yeah, if the guideline is not to add 0 unless absolutely necessary, that sounds fair enough.
