### ISSUE TITLE
[css-display] textPath and SVG unboxing for display:contents

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#2118]
When implementing [1] in Blink, the following came up as a question during code review:

fs@opera.com: "I find it a bit odd that &lt;tspan&gt; gets this treatment, but not &lt;textpath&gt;, since they are both "inline level" text content elements - that's a spec issue though..."

@tabatkins 

[1] https://drafts.csswg.org/css-display/#unbox-svg

**Comment by fantasai** [comment]
I'm guessing it's a specification error, then.

**Comment by tabatkins** [comment]
No, it's meant to be exhaustive, I just didn't realize that `textPath` existed.  It should indeed be treated the same as `tspan`

**Comment by tabatkins** [comment]
All right, fixed in 1432231d5. I reviewed the Element Index in SVG2 and also added `a` and "unknown elements" (which are defined to render like `g`) to the list, along with an note explaining the reasoning for the groups.

**Comment by fantasai** [comment]
I'd prefer if we didn't put exhaustive lists of non-CSS constructs in our CSS specs. It's fine to be comprehensive if we can, but our lists should be open-ended so that changes in the external technology don't automatically create errors in our specs.

**Comment by AmeliaBR** [comment]
Would it be better to link to SVG element-category definitions?

- `Root <{svg}>` would be "an `<svg>` element with CSS box layout" (in fact, I'd strongly argue _against_ using the word "root" if you want this behavior to apply to `<svg>` that is a child of an HTML element, and is therefore not the root of its document.)

  > ''display: contents'' behaves as ''display: none''.

- `<{tspan}>, <{textPath}>` would be [text content child elements](https://svgwg.org/svg2-draft/text.html#TermTextContentChildElement).

   `Nested <{svg}>, <{a}>, <{g}>, and unknown elements` would be [all other SVG container elements](https://svgwg.org/svg2-draft/struct.html#TermContainerElement) that are also [renderable elements](https://svgwg.org/svg2-draft/render.html#TermRenderableElement).

  Only ` <{use}> (treated as a Shadow DOM container)` would need to be called out separately

  > ''display: contents'' strips the element from the formatting tree,
  > and hoists its contents up to display in its place.

- any other SVG elements

  > ''display: contents'' behaves as ''display: none''.

**Comment by fantasai** [comment]
@AmeliaBR Yes, I think that would be much better. Would you mind drawing up a pull request (or just committing against this issue number if you prefer)?

**Comment by AmeliaBR** [comment]
@fantasai, I'll try to get that for next week.

________________________

For anyone else reviewing this issue, there's some relevant background in https://github.com/w3c/csswg-drafts/issues/540

**Comment by AmeliaBR** [comment]
@fantasai 

I've pushed edits [to a new branch](https://github.com/w3c/csswg-drafts/compare/display-contents-svg?expand=1).  Three commits: the first one to address this issue, and then two for #2502 (new text and an inline issue pointing back to GitHub).

I haven't worked with Bikeshed before, and don't have a build system set up locally, so I'm not sure I've got the linking syntax correct. Please review that (& the text) and correct or merge if OK.
