### ISSUE TITLE
[css2] typo

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#2132]
https://drafts.csswg.org/css2/syndata.html#color-units

> Users agents may perform higher quality mapping of colors from one gamut to another.

It seems me that "User agents" is correct.

**Comment by ewilligers** [comment]
This is already fixed in https://www.w3.org/TR/css-color-3/

**Comment by fantasai** [comment]
@ewilligers That's a different spec, though. :)

@momdo I don't think we have an active editor for CSS2 at the moment. Also not sure if anyone knows how to run the CSS2 spec processor... but tagging it for whenever that all gets sorted.

**Comment by frivoal** [comment]
> Also not sure if anyone knows how to run the CSS2 spec processor

For the css2 staging spec at least, this should do it:
```
cd csswg-drafts/css2
make
```

For the stable version (/css21), that should work as well, but there are a few differences in the Makefile, and it doesn't run on my machine.

**Comment by frivoal** [comment]
I've [fixed it](https://github.com/w3c/csswg-drafts/commit/0b331afcb77d23f589281e0d181fa0abdd03606d) in the staging spec. If that's good enough, feel free to close this issue.

**Comment by gsnedders** [comment]
> If that's good enough, feel free to close this issue.
doing as such
