### ISSUE TITLE
[css-text] Make ::first-letter { text-transform: capitalize } a no-op for text in languages that don't have letter case

### ISSUE THREAD

**Issue by amire80** [w3c/csswg-drafts#2135]
Consider the following code:
```html
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>first-letter issue demo</title>
  <style type="text/css">
    .cap::first-letter {
      text-transform: capitalize;
    }
  </style>
</head>

<body>
<div dir="rtl" lang="ar">
<p dir="ltr" lang="en">Incorrect, with capitalize:</p>
<p class="cap">عائلة</p>
<p dir="ltr" lang="en">Correct, without capitalize:</p>
<p>عائلة</p>
</div>
</body>
</html>
```

In the latest versions of Firefox and Chrome the rendering of the Arabic text in the section marked as "incorrect" is broken: the first letter is disconnected from the rest of the word. I guess that the rendering engines try to apply separate styling to the first letter and disconnect it, which is unnecessary because capitalization cannot work anyway.

While "first-letter" may have some useful meaning in all writing systems, "capitalize" is meaningless in writing systems that don't have letter case. Applying these rules to text in these writing systems should do nothing. I'm not sure how exactly this is supposed to be written, but this should be defined explicitly as a no-operation on the standards level.

The relevant standards section is probably 
https://www.w3.org/TR/css-text-3/#text-transform-property

See the related discussion at https://lists.w3.org/Archives/Public/www-international/2017OctDec/0142.html

**Comment by amire80** [comment]
I also reported these related issues:

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1427032

Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=797571

**Comment by fantasai** [comment]
Thanks for reporting the bugs. As for the spec, it is already specified here: https://www.w3.org/TR/css-text-3/#boundary-shaping

**Comment by litherum** [comment]
The spec says "Text shaping must not be broken across inline box boundaries when there is no change in formatting." so it seems to me this is just a browser bug and not a spec bug.
