### ISSUE TITLE
[css-values] Retiring support for 3-valued positions (excluding background)

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2140]
The CSS [\<position\> spec](https://drafts.csswg.org/css-values-4/#typedef-position) changed early this year, so that 3-valued positions (`left 10% top`) would no longer be part of \<position\> syntax, for any properties other than background-position.

The change was accompanied by a motive:

> Note: The background-position property also accepts a three-value syntax. This has been disallowed generically because it creates parsing ambiguities when combined with other length or percentage components in a property value.

I added Blink use counters at the time, and we now have data.

[ThreeValuedPositionBackground](https://www.chromestatus.com/metrics/feature/timeline/popularity/2001) >1%

[ThreeValuedPositionBasicShape](https://www.chromestatus.com/metrics/feature/timeline/popularity/2002) 0.00004% ([spec](https://drafts.csswg.org/css-shapes-1/#funcdef-circle))

[ThreeValuedPositionGradient](https://www.chromestatus.com/metrics/feature/timeline/popularity/2003) 0.001% ([spec](https://drafts.csswg.org/css-images-4/#valdef-conic-gradient-position))

[ThreeValuedPositionObjectPosition](https://www.chromestatus.com/metrics/feature/timeline/popularity/2004) 0.00007% ([spec](https://drafts.csswg.org/css-images-3/#propdef-object-position))

[ThreeValuedPositionPerspectiveOrigin](https://www.chromestatus.com/metrics/feature/timeline/popularity/2005) 0.000001% ([spec](https://drafts.csswg.org/css-transforms-2/#perspective-origin-property))

All of the main browser engines still support 3-valued positions as <position> values (apart from Edge for perspective-origin, but it doesn't accept 4-valued perspective-origin values either).

Does the Working Group ratify the retiring of 3-valued positions (excluding background)? Are browser vendors in agreement to remove support?

**Comment by Nadya678** [comment]
What is added value in this part of draft? Is there possibility to add any illustration to the draft that is impossible to style with standard styles?

**Comment by fantasai** [comment]
Question: Does the Blink use counter exclude 3-value syntaxes that use the 'center' keyword (since that doesn't take an offset)?

**Comment by ewilligers** [comment]
The Blink use counter excludes syntaxes that have an offset immediately after "center". The counter is only for 3-value syntaxes that match the \<bg-position\> syntax,

```
[ center | [ left | right ] <length-percentage>? ] &&
[ center | [ top | bottom ] <length-percentage>? ]

```

The logic is essentially as follows: The first value is an identifier. Exactly one of the next two values is an identifier, the other is a \<length-percentage\>. If the second value is an identifier, it is not "center". Otherwise, the first value is not "center". "left" | "right" appear at most once. "top" | "bottom" appear at most once.

**Comment by fantasai** [comment]
> The Blink use counter excludes syntaxes that have an offset immediately after "center". The counter is only for 3-value syntaxes that match the <bg-position> syntax

Right, I'm pointing out that 3-value syntaxes that use 'center' as one of the keywords (e.g. `center top 3px`) are still valid with the change -- it's the 3-value syntax without center (e.g. `top left 3px`) that would become invalid.

**Comment by ewilligers** [comment]
The syntax for [position](https://drafts.csswg.org/css-values-4/#typedef-position) has limited alternatives:

```
<position> = [
  [ left | center | right ] || [ top | center | bottom ]
|
```
1 or 2 values
```
  [ left | center | right | <length-percentage> ]
  [ top | center | bottom | <length-percentage> ]?
|
```
1 or 2 values
```
  [ [ left | right ] <length-percentage> ] &&
  [ [ top | bottom ] <length-percentage> ]
]
```
4 values

> Right, I'm pointing out that 3-value syntaxes that use 'center' as one of the keywords (e.g. center top 3px) are still valid with the change

How is that still valid?

**Comment by fantasai** [comment]
The current spec for this is https://drafts.csswg.org/css-backgrounds-3/#the-background-position which includes 

```
<bg-position> = [  [ left | center | right | top | bottom | <length-percentage> ]
|
  [ left | center | right | <length-percentage> ]
  [ top | center | bottom | <length-percentage> ]
|
  [ center | [ left | right ] <length-percentage>? ] &&
  [ center | [ top | bottom ] <length-percentage>? ]
]
```

**Comment by ewilligers** [comment]
Web platform tests have been added, e.g. https://wpt.fyi/results/css/css-images/parsing/object-position-invalid.html

Blink retires support in Chrome 68.

**Comment by BorisChiou** [comment]
I just filed an issue for Chrome because it seems `mask-position` also uses <position>, but Chrome doesn't retire its 3-valued positions.
https://bugs.chromium.org/p/chromium/issues/detail?id=980731&can=2&q=mask-position

**Comment by BorisChiou** [comment]
Sorry, my bad. Chrome doesn't support `mask-position`, so this issue should be invalid. Thanks for the feedback in that issue. Firefox will retire the 3-valued syntax soon. Thx.
