### ISSUE TITLE
[css-align][css-multicol] Make "column-gap: normal" to be 1em in multi-column per spec

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#2145]
Specs:
* https://drafts.csswg.org/css-align/#valdef-row-gap-normal
  > The normal represents a UA-dependent length on multi-column elements, and computes to 0px in all other contexts.
* https://drafts.csswg.org/css-multicol-1/#valdef-column-gap-normal
  > Identical to <length-percentage>, but with a UA-specified length. A value of 1em is suggested.

There's an [issue in `css-align`](https://drafts.csswg.org/css-align/#issue-cdd740cf) about this:
> ISSUE 4: Should normal just compute to 1em in multicol?

I've realized there's a WPT test checking exactly that: http://w3c-test.org/css/css-multicol/multicol-gap-001.xht
Right now is marked as optional, but it passes in all the browsers I checked: Chromium, Safari, Firefox and Edge.

Maybe it's possible to update the specs and make this test mandatory. WDYT?

**Comment by rachelandrew** [comment]
Do we know what non-web browser UAs are doing here? I imagine they may be using something different.

**Comment by frivoal** [comment]
At least Vivliostyle, Prince, and Pdfreactor use `1em` as well. I do not have an Antenna House install to test, but i'd be surprised if it differed.

**Comment by frivoal** [comment]
@MurakamiShinyu Do you know what the behavior of AH formatter is for this? Is column-gap normal 1em, or some other value?

**Comment by MurakamiShinyu** [comment]
AH formatter uses 1em as well.

**Comment by frivoal** [comment]
In that case, I think we should just resolve that it's 1em, and remove the "UA defined" bit, as that doesn't seem to help anyone.

**Comment by rachelandrew** [comment]
I agree, it seems that there is interop on this, so there seems no sense in leaving room for ambiguity.

**Comment by rachelandrew** [comment]
failed to reference the issue, but commit is here for multicol https://github.com/w3c/csswg-drafts/commit/bf382681a7645464271ff381a7b70ba79bbbabc8
