### ISSUE TITLE
[web-animations] "Lost" of history by moving spec from fxtf to csswg 

### ISSUE THREAD

**Issue by dirkschulze** [w3c/csswg-drafts#2147]
@birtles Why was the spec moved from fxtf to csswg? This way the history before the move is not easily accessible anymore unless one knows exactly where it is coming from. Was there any need to move the spec?

**Comment by birtles** [comment]
Yes, because it was not getting enough visibility in the FXTF repository. I sent several mails to w3-css-wg about this including asking how to preserve history but unfortunately didn't get an answer in time.
