### ISSUE TITLE
[css-fonts-4] typo: miscounted number of generic font families

### ISSUE THREAD

**Issue by mlc** [w3c/csswg-drafts#2148]
`css-fonts-4` [section 2.1.1](https://drafts.csswg.org/css-fonts-4/#generic-font-families) begins by describing behavior for "all five generic font families", but then goes on to list nine such families. I would suggest removing the word "five" (twice in the same sentence), replacing it with "nine" (ditto), or explaining how five of the families behave differently from the other four.

Thanks!

**Comment by litherum** [comment]
We should just remove the redundant numbers altogether.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/64a6f626e7796f39989eb2073edb0c01d9056024

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/d219169f0c7b585f2129c808a30a2dd4141fa0eb

**Comment by mlc** [comment]
thanks for having a look!
