### ISSUE TITLE
[css-grid] Issue 7 Add example of fixed size spanner getting extra space from content distribution

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#215]
[11.5. Aligning the Grid](https://drafts.csswg.org/css-grid/#grid-align)

I was working on some examples and built this which may be a good example for this section.

[gist](https://gist.github.com/rachelandrew/83e96245de648df14a95089f8ba7cbdd)
[CodePen](http://codepen.io/rachelandrew/pen/vKyJXv/)

> I have a grid container sized in absolute units, with grid tracks also sized using absolute units. The sum of the tracks in both directions is smaller than the container.

> Using the keyword values space-around and space-between increases the spacing between tracks. Any grid area that spans one of these gaps thus gains width or height as the space is added to the total width/height.

![fixed-size-spanner-extra-space](https://cloud.githubusercontent.com/assets/2764898/16261444/7e7fa948-3863-11e6-8792-dde2418f84ad.png)

**Comment by tabatkins** [comment]
Nice, that looks great. I assume that first one is using gutters to produce the small constant spacing?

**Comment by rachelandrew** [comment]
Yes - I thought it might make it more obvious that the spacing also increases the desired absolute gap.

**Comment by tabatkins** [comment]
Makes sense. I'll just need to convert this to SVG and embed it - thanks for the example!

**Comment by fantasai** [comment]
Added in commit 22b395cbc4c934b2c91a46df83561b02a2be0074 ! Thanks so much~ @tabatkins can convert it to SVG whenever he gets around to it, imho it's more important to have an image than an SVG image. ;)
