### ISSUE TITLE
[css-position-3] Typos/Issues in the Sticky Positioning section

### ISSUE THREAD

**Issue by Tyler-H** [w3c/csswg-drafts#2152]
In [Sticky Positioning](https://www.w3.org/TR/css-position-3/#sticky-pos), I've noticed quite a few grammatical errors/incomprehensible passages. Each one is contained in a quote block, followed by my remarks and/or replacement suggestions.

> A stickily positioned box establishes **a new a new** containing block [...] 

(redundant phrase outlined in bold).

I recommend reordering the following sentence:
> For stickily positioned elements, left, right, top and bottom are offsets from the respective edges of its flow box which are used to constrain the element’s offset. 

To:

> For a stickily positioned element, left, right, top, and bottom are [offsets which are] used to define the element's offset from the respective edges of its flow box.

(The bit in brackets is optional; I think the passage works well, if not better, without it). 

Also, the term "flow box" is very esoteric, and never explicitly defined. It took me something like 15 minutes to intuit that it is just the containing block. Could we just replace instances of 'flow box' here with 'containing block'?

This would also facilitate the improved readability of the following paragraph:

> 1. A rectangle is computed relative to the containing block of the stickily positioned element, by insetting its flow box rectangle on each side by offsets computed from the left, right, top and bottom properties of the stickily positioned element. 

By rewriting it as:

> 1. A rectangle is computed relative to the containing block of the stickily positioned element by insetting the rectangle on each side by offsets computed from the left, right, top, and bottom properties of the stickily positioned element.

...which I think reads much better.

> When computing **containement** of the stickily positioned element within its containing block

(extra e in containment)

> Note that a stickily positioned element with non-auto top style and auto bottom style will only ever be pushed down by sticky positioning; it will never be offset upward**s**.

(The actual spelling is upward. Upwards is a variant that's taken hold due to some folks' tendency to add an 's' to directional words like "upward, forward, backward, onward, toward". Unfortunately I didn't catch this error in time for animation-fill-mode properties, but luckily this is just prose, not a keyword)

**Comment by Nadya678** [comment]
For me main problem is: The sticky will not work with thead, tr (table-rows) etc. **I need it here!** For always visible header if i scroll table right or down. Without any script.

**Comment by Tyler-H** [comment]
@Nadya678 That comment doesn't seem to address anything in my bug report. Are you sure you posted it in the right one?

**Comment by Nadya678** [comment]
Yes. I Want not to duplicate the bug isseus. "Issues in the Sticky Positioning section"

Quote:

> The effect of position: sticky on table elements is the same as for position: relative

in my opinion this sentence should be removed and the behaviour for all elements (and display values) should be the same.

**Comment by fantasai** [comment]
Hi @Nadya678, I appreciate you not wanting to post a duplicate issue, but your issue is really quite different from the one @Tyler-H has posted here -- his is about a handful of wording fixes, yours is about a particular functionality that's problematic. Please do file a separate issue; that the *title* of this one is vague enough to accommodate almost anything isn't a reason to pile all the issues with 'sticky' into this one issue. :)

**Comment by fantasai** [comment]
@Tyler-H OK, we've rewrote most of this section and also fixed the typo that remained. :) Thanks~
