### ISSUE TITLE
[css-align-3] Image link is broken

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#2154]
In this section https://drafts.csswg.org/css-align-3/#gap-shorthand, the image link in EXAMPLE 6 is broken.

Broken link: https://drafts.csswg.org/css-align-3/images/gutters-gaps.svg

Original link: https://drafts.csswg.org/css-grid/images/gutters-gaps.svg

I guess, the SVG file should be moved from /css-grid to /css-align-3.

**Comment by frivoal** [comment]
> I could only find css-grid-1 and css-grid-2 in the source files. I assume that the css-grid directory is automatically created for css-grid-1?

Yes. The source has numbered directories, and the server has a config file to create an alias for the one which is considered the current latest version. Grid 2 is still experimental, so the alias is currently to css-grid-1.
