### ISSUE TITLE
[selectors-4] Rename :nth-column to :nth-col

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2157]
There was a concern raised (by dbaron I think, though I'm not sure) that if we introduced a `::column` pseudo-element for multicol, it would be very confusing if we also have `:nth-column()` which has nothing to do with multicol. We don't use abbreviations much in CSS syntax, but table markup in HTML already uses `col` as an abbreviation in many places (the `<col> and <colgroup>` elements, values of the `scope` attribute, the `colspan` attribute, etc.) so maybe using that abbreviation here would be an appropriate way out of the potential conflict.

**Comment by acpirate** [comment]
would :nth-table-column() be too verbose?

**Comment by tabatkins** [comment]
Shorter's always better than longer, subject to understandability concerns.

I'm fine with `:nth-col()`, and like your HTML-based reasoning.
