### ISSUE TITLE
[css-pseudo] ::first-letter should include whitespace

### ISSUE THREAD

**Issue by csnardi** [w3c/csswg-drafts#2164]
The section on ::first-letter says nothing about whitespace, and [a css-backgrounds WPT test](https://github.com/w3c/web-platform-tests/blob/master/css/css-backgrounds/first-letter-space-not-selected.html) even tests that whitespace is not selected by ::first-letter. However, all implementations fail this test:

- Edge selects whitespace no matter if it is followed by a non-whitespace character or not
- Firefox only selects whitespace that is not followed by a non-whitespace character
- Chrome (and I assume WebKit) only selects whitespace that is followed by a non-whitespace character

Given that all implementations select whitespace of some sort in ::first-letter, but each does it differently, it is probably appropriate to clarify this in the spec.

**Comment by Nadya678** [comment]
But the name is ::first-LETTER. Whitespace is not letter and also digits are not letters. 
But in this case if all browsers behave in the same manner, the description shoud be edited.

**Comment by Nadya678** [comment]
Test also this on Firefox. It means first **letter**. 
https://jsfiddle.net/gpq6ncwg/

**Comment by csnardi** [comment]
A real-world example of the interoperability confusion is https://bugs.chromium.org/p/chromium/issues/detail?id=638267.

**Comment by csnardi** [comment]
Another real-world example: https://bugs.webkit.org/show_bug.cgi?id=163216. Since WebKit selects spaces everywhere, `A "b"` will have `A "` selected.

**Comment by fantasai** [comment]
We've clarified in https://github.com/w3c/csswg-drafts/issues/5154 that we capture *intervening* white space, between a preceding or following punctuation character and the first letter. So I think this issue technically is closed. But the example @csnardi points out shows that this is pretty broken in some cases, so I filed https://github.com/w3c/csswg-drafts/issues/5830 as a follow-up.
