### ISSUE TITLE
[css-shapes] ellipse with single <shape-radius>

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2175]
The [ellipse](https://drafts.csswg.org/css-shapes-1/#funcdef-ellipse) shape used by [clip-path](https://drafts.fxtf.org/css-masking-1/#the-clip-path), [shape-outside](https://drafts.csswg.org/css-shapes-1/#shape-outside-property), [offset-path](https://drafts.fxtf.org/motion-1/#offset-path-property) is defined to accept \<shape-radius\>{2}, i.e. two \<shape-radius\> values.

However, Safari also accepts a single \<shape-radius\> for shape-outside, and Blink also accepts a single \<shape-radius\> for clip-path and shape-outside.

**Comment by ewilligers** [comment]
I just noticed

> \<shape-radius\> = ...
> ... If omitted it defaults to closest-side.

This may be the justification for accepting one radius value, but I suspect

`ellipse( <shape-radius>{1,2}? [ at <position> ]? )
`would be clearer.

**Comment by fantasai** [comment]
@ewilligers If we're using the “If omitted it defaults to closest-side” clause to justify the singe `<shape-radius>` case, then it would mean a single `<shape-radius>` expands to that in one axis and `closest-side` in the other. Then it's unspecified which side, but also it's inconsistent with how CSS works, where an omitted second value is doubled.

So clearly something needs to be fixed in the spec here! What's the implemented behavior so far? :)

**Comment by ewilligers** [comment]
Both Blink and Webkit treat `ellipse(20% at 30% 40%)` as `ellipse(20% closest-side at 30% 40%)`. Further, they serialize each as `ellipse(20% at 30% 40%)`.

Edge and Firefox don't support basic shapes.

**Comment by upsuper** [comment]
> Edge and Firefox don't support basic shapes.

Firefox supports basic shapes in `clip-path`, and `shape-outside` is currently behind pref `layout.css.shape-outside.enabled` because there are still something not fully implemented.

**Comment by svgeesus** [comment]
>  I suspect `ellipse( <shape-radius>{1,2}? [ at <position> ]? )` would be clearer.
I agree, that makes it clear that either one or two radii can be specified.

However, it is still odd that `ellipse(20% closest-side ...)` has a handy shortcut while `ellipse(closest-side 20% ...)` does not.

**Comment by AmeliaBR** [comment]
As a CSS author, I would expect that `ellipse(50px at center)` would expand to `ellipse(50px 50px at center)`.

If the Blink/WebKit behavior is adopted instead, I definitely don't think that the serialization should drop `closest-side` when specified as the second radius value.

**Comment by svgeesus** [comment]
> As a CSS author, I would expect that ellipse(50px at center) would expand to ellipse(50px 50px at center).

To be honest that is what I would expect, also.

**Comment by smfr** [comment]
https://bugs.webkit.org/show_bug.cgi?id=181745

**Comment by fantasai** [comment]
Note: elliptical radial gradients also require two arguments: https://www.w3.org/TR/css3-images/#radial-gradients

**Comment by AmeliaBR** [comment]
More than a year later, I note that Chrome hasn't changed their implementations (I just got dinged on the lack of interop when trying to test other things).  What were the results of your use counter, @ericwilligers ? Is it safe to remove, or do we need to revisit the resolution?

**Comment by ewilligers** [comment]
Blink use counts for ellipse:
[BasicShapeEllipseNoRadius](https://chromestatus.com/metrics/feature/timeline/popularity/2326) 0.00005% 
[BasicShapeEllipseOneRadius](https://chromestatus.com/metrics/feature/timeline/popularity/2327) 0.00002% 
[BasicShapeEllipseTwoRadius](https://chromestatus.com/metrics/feature/timeline/popularity/2328) 0.1% 

It is safe to remove: [Blink issue](https://bugs.chromium.org/p/chromium/issues/detail?id=899150)
