### ISSUE TITLE
[css-ui] Typo in image cursors?

### ISSUE THREAD

**Issue by edent** [w3c/csswg-drafts#2176]
https://www.w3.org/TR/2017/PR-css-ui-3-20171214/#cursor

> Note: The CSS Working group initially indented support for all SVG, intrinsically sized or not.

I think this should be:

> Note: The CSS Working group initially *intended* support for all SVG, intrinsically sized or not.

**Comment by svgeesus** [comment]
@frivoal typo pointed out in AC review of ui-3. I assume we can just agree and fix it in the Recommendation.

**Comment by frivoal** [comment]
Thanks. I've fixed the ED in level 3 and 4. I agree this can be fixed directly in the REC, without any need to cycle anything.
