### ISSUE TITLE
[css-transforms-1] Remove all uses of 4x4 matrices in transforms 1

### ISSUE THREAD

**Issue by dirkschulze** [w3c/csswg-drafts#2186]
Level 1 still mentions 4x4 matrices a lot. Should be replaced and moved to transforms-2.

**Comment by smfr** [comment]
We agree to keep the use of 4x4 matrices in transforms-1, but to avoid any matrices with 3d components. Section 4.2 needs to be edited to avoid mentioning matrix3d(): https://drafts.csswg.org/css-transforms/#serialization-of-the-computed-value
