### ISSUE TITLE
[css-multicol-1] Incorrect markup/styling leads to bogus punctuation

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2187]
from https://lists.w3.org/Archives/Public/www-style/2018Jan/0043.html

> >  just saw that blue quote not behind the curly brace but on a new line.
> > Found this in the examples 10,11 and 21.
> > Regards,
> >
> > ---------------------------------------------------------------------
> > Dennis Heuer
> > 
> 
> Dennis is correct. The blue quotes should not be there.
> 
> Example 10:
> https://www.w3.org/TR/css-multicol-1/#example-3694c0ea
> 
> Example 11:
> https://www.w3.org/TR/css-multicol-1/#example-5c1712e2
> 
> Example 21:
> https://www.w3.org/TR/css-multicol-1/#example-59dd6b8a
> 
> 
> <pre class="css">h2 { column-span: all; background: silver }
> </pre>
> 
> Source/cause is:
> 
> line 155 in the document:
> 
> .css::before, .property::before, .descriptor::before {
>    content: "‘";
> }
> 
> .css::after, .property::after, .descriptor::after {
>    content: "’";
> }
> 
> Gérard

Note that this problem is only on TR, not in the ED.

@rachelandrew 
Is this something you recently fixed in the ED, or is this due to using a different stylesheet on TR? If the former, we can just close this issue, but if the later, we should fix this.

**Comment by tabatkins** [comment]
It's a markup issue - `<pre class=css>` triggers the quote-marks styling of inline CSS fragments (what you get when you double-single-quote something). I think I changed them to `<pre highlight=css>`, which gets the styling that we want.
