### ISSUE TITLE
[css-align] justify-items synxtax doesn't allow 'overflow [leff | right]' 

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#2188]
After soe changes, due to ambiguities with the place-self and place-items shorthands, it was decided to restrict the position of the overflow-alignment values. That's fine. However, I'm not sure the current syntax for the justify-items is the one we were looking for: 

https://drafts.csswg.org/css-align-3/#propdef-justify-items
> | normal \| stretch \| \<baseline-position\> \| [ \<overflow-position\>? \<self-position\> ] \| [ legacy \|\| [ left \| right \| center ] ]

If I understood it correctly, the syntax above parses as invalid CSS declarations like 'overflow leff'. As a matter of fact, overflow-positions is only valid if used with a self-position. However, the justify-self syntax parses as valid the combination with 'left' and 'right' as well. 

Is this the intended behavior ?

**Comment by fantasai** [comment]
Looks indeed like an error in the grammar. Probably it should be 

```
<overflow-position>? <self-position> |  legacy ||  <overflow-position>? [ left | right | center ]
```

**Comment by javifernandez** [comment]
Umm, the new proposed syntax allows "legacy safe left" and "unsafe right legacy" . Are we sure we want overflow-position in combination with 'legacy ? According to the specs, the 'legacy' keyword exists to implement the legacy alignment behavior of HTML’s <center> element and align attribute, so I don't think the overflow-position makes sense there.

**Comment by javifernandez** [comment]
What abut this ?
&lt;overflow-position&gt;? [ &lt;self-position&gt; | left | right ]  | legacy || [ left | right | center ]

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/3e27468e1212912376e9e7d787f0bb60f5169375 ! Thanks~ :)
