### ISSUE TITLE
[cssom] getComputedStyle for inline style and multiple globals

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#219]
See
https://lists.w3.org/Archives/Public/www-style/2014Dec/0137.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1109033
https://github.com/jquery/jquery/issues/2622

Test
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4279
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4280

Apparently the inline style should be applied. (And `getComputedStyle` when called on an element from another global needs to consider style changes for that element, although how that works isn't really defined yet.)

**Comment by zcorpan** [comment]
Test case: [multiple-globals.zip](https://github.com/w3c/csswg-drafts/files/341293/multiple-globals.zip)

**Comment by zcorpan** [comment]
Discussion on www-style
https://lists.w3.org/Archives/Public/www-style/2016Jun/0183.html

**Comment by FremyCompany** [comment]
Merging with #1548 
(as far as I can see the behavior of all browsers was the same on these saved two doms)
