### ISSUE TITLE
[css-values] Definition of 2D Positioning: the <position> type

### ISSUE THREAD

**Issue by lahmatiy** [w3c/csswg-drafts#2193]
The latest version of CSS Backgrounds and Borders Module Level 3 has changed definition of `<bg-layer>` and `<final-bg-layer>` to use `<bg-position>` instead of `<position>`. I did a little research into the difference and found that CSS Values and Units Module Level 4 has its own syntax of `<position>` with notes:

> Note: The background-position property also accepts a three-value syntax. This has been disallowed generically because it creates parsing ambiguities when combined with other length or percentage components in a property value.

It's good to know. But there are a couple of problems:

- CSS Values and Units Module Level 4 (WD) – doesn't reflect changes about `<position>` in `Changes` section
- CSS Values and Units Module Level 3 (CR) – still refers to CSS Backgrounds and Borders Module Level 3 with no notes about the difference

I believe it should fixed in one way or another to be less confused: add a notes to `<position>` section and an entry to Changes section to L3, or add an entry to Changes section in L4.

**Comment by fantasai** [comment]
Afaict, css-values-3 and css-values-4 have identical text, which defines a syntax and defers interpretation to css3-background, which defines a superset of said syntax. So I don't see a problem.

As css-values-4 is a new spec, its changes section will consist only of differences from css-values-3 upon publication of FPWD.

Closing as invalid.

**Comment by lahmatiy** [comment]
> Afaict, css-values-3 and css-values-4 have identical text

No, they are not identical or I'm looking wrong urls.

### CSS Values and Units Module Level 3 (CR)
https://www.w3.org/TR/css-values-3/#position
https://www.w3.org/TR/css-values/#position
![image](https://user-images.githubusercontent.com/270491/35765499-e3ae3c5a-08d5-11e8-8777-17be1aa64730.png)

### CSS Values and Units Module Level 4 (WD)
https://drafts.csswg.org/css-values/#position
![image](https://user-images.githubusercontent.com/270491/35765472-67dcccb8-08d5-11e8-93ac-0e27b7a73920.png)

**Comment by fantasai** [comment]
https://drafts.csswg.org/css-values-3/

I've been trying to get the copy on www.w3.org updated since August, but the CSSWG was really dragging its heels on https://github.com/w3c/csswg-drafts/issues/434 . I checked in the edits last night, though, so assuming I get approval next Wednesday, we should be able to publish in 2 weeks. (CR updates take a long time, unfortunately. 🙁 )
