### ISSUE TITLE
Test-suite, Ahem font

### ISSUE THREAD

**Issue by tobireif** [w3c/csswg-drafts#2200]
I just was going through the test-suite, in three browsers, submitting results automatically and manually. Then I noticed ~"This test requires the Ahem font to be installed" - thus probably many test results were false.

Would it be possible to @font-face the Ahem font? (Everywhere, or for each test that requires it).

Then testing won't go wrong as it just did.

**Comment by gsnedders** [comment]
FWIW, this would be better discussed on the w3c/web-platform-tests repository.

This has been discussed on several occasions before [citation needed], but I think we've always decided that it's simply too much effort to go through and add `@font-face` to every test case that uses it.

**Comment by frivoal** [comment]
@gsnedders That's understating it: the current policy is actually not to add `@font-face` for Ahem in new tests. I'd be happy to change that, but that's what it is for now, IIUC.

**Comment by liamquin** [comment]
On Fri, 2018-01-19 at 01:00 +0000, Geoffrey Sneddon wrote:
> 
> [...] I think we've always decided that it's simply too much effort
> to go through and add `@font-face` to every test case that uses it.

Isn't there a move for browsers to ignore installed fonts and use only
embedded plus serif/sans/mono/fantasai/cursive or whatever the list is?

What if the test harness JavaScript code injected @font-face for Ahem
to every test??

CSS never did have a way to distinguish two fonts of the same name but
from different foundries (there's a sans-serif text face called Symbol,
for example, which is not at all the same as Adobe Symbol), nor to
request a specific-or-later version of a font, but i'm not aware of any
other fonts called "ahem", so the only problem is not having installed
the font, not getting the wrong font.


-- 
Liam Quin, W3C, http://www.w3.org/People/Quin/
Staff contact for Verifiable Claims WG, SVG WG, XQuery WG

Web slave for http://www.fromoldbooks.org/

**Comment by tobireif** [comment]
> FWIW, this would be better discussed on the w3c/web-platform-tests repository.

Thanks for the info, next I'll try to remember to submit any issues there.

> the current policy is actually not to add @font-face for Ahem

I'd prefer it if no test would require any specific font. But when a test writer has good reasons to require a specific font, then that font should be right there, without requiring the test-suite user to do anything regarding any required assets (fonts, images etc). @font-face is a great way to load the required font. When I supply test cases for issue reports I can't require the visitor to install the required font, so I make sure it's right there using @font-face, eg:

https://bugs.chromium.org/p/chromium/issues/detail?id=800693
->
https://tobireif.com/non_site_stuff/test_case_for_font_position_report/

I ran the CSS Grid test-suite, and I inadvertently supplied potentially-incorrect test results because the tests that require a specific font don't @font-face it. The note I then saw at a later point in time is not sufficient: I already had submitted hundreds of results (running the suite in 3 browsers) before I saw the note telling me to install a font on my machine, as if we are still in a time where @font-face didn't exist 😀

You can @font-face any respective required font(s) where necessary (or eg make sure that no existing or future test requires any fonts) - or you'll probably get even more incorrect test results by people who want to contribute by running the test suite, but aren't familiar with the implicit requirements that are only obvious among test-suite contributors, WG members, etc.

By the way, I'd be quite busy if every site required me to install a font, so I don't do that 😀 Supplying the font using @font-face is easy for future tests, and perhaps a script could ensure it for the existing ones. Or eg
> the test harness JavaScript code [could] inject[...] @font-face for Ahem to every test[...]

**Comment by gsnedders** [comment]
This issue was moved to w3c/web-platform-tests#9105
