### ISSUE TITLE
[web-animations-1] Should async playback methods return the `ready` Promise?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2206]
It's common when using the API to write:

```js
anim.play();
anim.ready.then(() => {
   // do stuff
});
```

or,

```js
anim.play();
await anim.ready;
// do stuff
```

This would be much simpler if `anim.play()` simply returned the `ready` Promise so you could write:

```js
anim.play().then(() => {
   // do stuff
});
```

or,

```js
await anim.play();
// Do stuff
```

Likewise, of course, for `pause()`, `reverse()`, `updatePlaybackRate()`.

We've discussed this in the past and the trouble has always been that we were concerned that people would assume that the Promise returned was the `finished` Promise and erroneously write:

```js
anim.play().then(() => {
   // Animation is finished now, do cleanup.
});
```

My hunch is that the convenience of being able to wait on the result of `play()`, `pause()`, `reverse()`, and `updatePlaybackRate()` outweighs the risk that a few people will get it wrong but I'm not sure. I'm used to async methods being fine-grained but that might just be the APIs I tend to use. Perhaps a significant number of people would expect waiting on `anim.play()` to resolve when the animation was finished, I'm not sure.

**Comment by graouts** [comment]
My immediate expectation when seeing:

```javascript
anim.play().then(() => {
    // do stuff
});
```

was indeed that it would run the callback _after_ the animation had finished. That's just how it reads to me.

**Comment by graouts** [comment]
What are the expected uses cases for the `ready` promise? Sync other operations to start in unison? Anything else?

From my own experience, I think post-animation cleanup tasks are quite common, and I would favour returning the `finished` promise if we were to return anything for `play()`.

**Comment by birtles** [comment]
Yes, after I left the office on Friday I was thinking about this some more and came to the same conclusion that we should return the finished promise from `play()` and `reverse()`.

There aren't really any strong use cases for the `ready` promise. Like you said, it's mostly useful for synchronization. For example, if you start an animation you don't know the actual `startTime` until it finishes painting. So if you want to synchronize something with a newly-started animation you'd need to wait on `ready`.

I think my thinking was biased by the fact that I am writing so many web-platform-tests for this where we wait on `ready` to check values like `startTime` ― not a very typical use case!

**Comment by birtles** [comment]
I wrote the spec text for this and implemented it but then I discovered that if we make the return type of an operation a Promise-type, WebIDL automatically turns exceptions into rejected promises. See [create an operation function](https://heycam.github.io/webidl/#dfn-create-operation-function), step 2, "And then, if an exception E was thrown:" branch, step 1.

That seems unfortunate since it would mean that these methods can no longer return the `ready`/`finished` promises. For example, under normal circumstances if you called `reverse()` on a finished animation we'd return the animation's (possibly updated) _current finished promise_. However, if you called it on an animation that can't be reversed we **don't** want to mutate the animation's _current finished promise_ since a failed call should leave the animation unmodified (strong exception safety). While we can simply return a different rejected Promise in that case it would mean the return value of `reverse()` is no longer strictly equivalent to the _current finished promise_.

Furthermore, if we make this change any existing code relying on exceptions (is there any?) will break, and all callers are effectively forced into using the Promise API--and if they only care about detecting exceptional circumstances they need to write code to distinguish between cancellation and failure cases.

e.g.

```js
// I really only care if the following call passes or not
anim.reverse().catch(err => {
  // If the animation was canceled at some unspecified time later, I don't care.
  if (typeof err.name === 'string' && err.name === 'AbortError') {
    return;
  }
  // I do care about other errors though.
  throw err;
});
```

I'm a bit stuck as to what we should do here.

**Comment by birtles** [comment]
In case I/someone wants to pick this up later:
Spec changes: https://github.com/birtles/csswg-drafts/commit/4c66f8f3c6825f31bb6cb7ed329ba6cbbb667ff2
Initial Gecko patch: https://gist.github.com/birtles/877e3d98d69fc6e4b3cb8db1702c543b

**Comment by birtles** [comment]
We (Apple, Google, Mozilla) discussed this back in March. Minutes as follows:

> * Problem is that if we do this, exceptions that threw exceptions now start to return rejected Promises.
Is that ok? useable? compatible?
> * The console still logs them, which is good. (Chrome, Firefox?, Safari?)
> 
> **Decision:** we want to do this, but need to decide if we want to get data on it or not.
> 
> * https://www.chromestatus.com/metrics/feature/timeline/popularity/555
> * reverse() is used ~0.0001% of page views--and presumably the number of calls that throw exceptions is far less still
> * Not being able to easily distinguish between aborting and errors is just a consequence of abandoning cancelable promises on the Web platform.

Usage of `reverse()` seems to have spiked since then, but is still only 0.008% and, again, presumably the number of calls that throw is far far less than that.

Based on that, I'm going to go and merge the relevant PR.

**Comment by birtles** [comment]
Having merged this and begun to implement I am concerned that this will make the API harder to use due to "Unhandled Promise rejection" warnings (and errors in some frameworks).

In particular, consider the following code:

```js
button.onClick(() => {
  animation.cancel();
});
// ...
animation.pause();
```

If the click occurs while the animation is still pause-pending we'll get a unhandled Promise rejection, which, at very least, will clutter up the console. 

Instead the author needs to write:

```js
animation.pause().catch(() => { /* Ignore */ });
```

or `try { } catch (e) { }` if they are using `async/await`.

This is even more likely in the case of `play()` where if the animation is aborted any time before it finishes the returned Promise will be rejected. Fortunately it does not affect `Element.animate()`.

I'm not sure if there's any way around this. If anyone knows, please let me know.

**Comment by birtles** [comment]
I discussed this with @graouts and @flackr yesterday and decided to revert this change because:

* It will cause users who simply want to call `play()` to have to explicitly catch and ignore rejected Promises to avoid console warnings.
* Such warnings will only fire depending on when the animation is canceled making for potentially hard-to-debug occasional console warnings.
* It is a little inconsistent to have `play()` return the `finished` promise while `pause()` etc. return the `ready` promise. Requiring the author to explicitly specify the Promise on which they wish to wait avoids confusion.
* It makes it harder for authors to distinguish between rejections in `reverse()` etc. due to not being able to reverse vs the animation being canceled.
* It requires implementations to always generates these Promise objects even when they are not used.
