### ISSUE TITLE
[css-backgrounds-3] # in value notation undefined because ref is to CSS2

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2209]
Section two states:

> This specification follows the CSS property definition conventions from [CSS2].

And, e.g., `background-repeat`'s value is defined as `<repeat-style># `.

However, CSS2's property definition value doesn't define `#`.

Presumably the fix is to simply refer to CSS Values and Units.

**Comment by fantasai** [comment]
Need to create some standardized boilerplate to propagate out, but this should be sufficient for css-backgrounds-3 for now.
