### ISSUE TITLE
[cssom] serialising declarations with multiple components doesn't work

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2212]
See https://drafts.csswg.org/cssom/#serializing-css-values.

Given a CSS declaration of `quotes: 'a' 'b`:

Step 1 does nothing. Step 2 creates a list. Step 3 calls [serialize a CSS component value](https://drafts.csswg.org/cssom/#serialize-a-css-component-value) with `'a' 'b'`. This is nonsense because `a` `b` is not a component.

**Comment by fantasai** [comment]
@gsnedders Fixed in https://github.com/w3c/csswg-drafts/commit/599e2042a736b0e3073f1f52df4770447fc7e770 !
