### ISSUE TITLE
[css-scroll-snap] Is scroll-margin applied before or after transform?

### ISSUE THREAD

**Issue by syj10** [w3c/csswg-drafts#2214]
https://drafts.csswg.org/css-scroll-snap-1/#propdef-scroll-margin
The spec says, 

> The scroll snap area is the rectangular bounding box of the transformed border box, plus the specified outsets, axis-aligned in the scroll container’s coordinate space.

Does that mean "transform the border box, then add the specified outsets", or "add the specified outsets to the border box and transform the result"?

**Comment by Nadya678** [comment]
Yes. It is needed. By default the :target scrolls to border but in part cases the scrolling should intuitive be greater if you have a top fixed positioned menu.

**Comment by fantasai** [comment]
It means the first one: you take the bounding box of the transformed border box, and then add the specified outsets. That is, the outsets are added to the “rectangular bounding box” not to the “transformed border box”.
