### ISSUE TITLE
[css-fonts-4] Matching fallback fonts when a variation font is defined by @font-face rule

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/csswg-drafts#2218]
In "[Matching font styles](https://drafts.csswg.org/css-fonts-4/#font-style-matching)", step 4 refers to "[Feature and variation precedence](https://drafts.csswg.org/css-fonts-4/#apply-font-matching-variations)", where steps 2 and 3 define precedence for font variation properties. However, nothing is mentioned about the processing of [OpenType registered variation axis tags](https://www.microsoft.com/typography/otspec/dvaraxisreg.htm) (such as 'wght', 'wdth', 'ital', etc.).

Let's assume that an author selects a desired variation font that is defined using @font-face rule, and defines "Arial" as a fallback font family. The primary font choice is defined with its weight axis value selected using font weight property descriptor:
`@font-face {
   font-family: myVariableFontA;
   font-weight: 700;
}
`
According to the font style matching algorithm, if `myVariableFontA` fails to load, a browser should select "Arial Bold" as a fallback font.

However, if the same variable font supports multiple variation axes, the author could use @font-face rule to define e.g. condensed bold face using two or more variation settings in a single line using font-variation-settings
`@font-face {
   font-family: myVariableFontA;
   font-variation-settings: 'wght' 700, 'wdth' 70;
}
`
If `myVariableFontA` fails to load, "Arial Bold Condensed" should be chosen as a fallback font; however, the font style matching algorithm is completely silent about how known / registered variation tags should be treated as part of the font property settings. (The same is true even if only a single variation axis tag is defined by font-variation-settings - known / registered tags should be processed and matched the same way as their explicitly defined counterparts (font-weight, font-style, font-stretch, etc.).

**Comment by litherum** [comment]
If I understand you correctly, you are talking about the case:

```
@font-face {
    font-family: “myVariableFontA”;
    font-weight: 700;
}
<div style=“font-family: ‘myVariableFontA’, ‘Arial’>...</div>
```

We definitely shouldn’t be using a previous font’s `@font-face` block in order to apply styles to successive fonts. If a font can’t be loaded, it’s item in the `font-family` list should be totally ignored. Anything else will confuse authors, and would also confuse editing tools.

The behavior for known axes and unknown axes are treated the same in the spec. The difference in behavior is between `font-variation-settings` and `font-*` properties.

**Comment by vlevantovsky** [comment]
Spec changes that we discussed and captured in comments to issue #2221 would resolve this issue as well.

**Comment by svgeesus** [comment]
> Spec changes that we discussed and captured in comments to issue #2221 would resolve this issue as well.

Fixed by https://github.com/w3c/csswg-drafts/commit/683605e1c7c9ef1b54c64161760ec4ade505843c
