### ISSUE TITLE
[css-fonts-4] [editorial] Duplicate entries in "Feature and variation precedence"

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/csswg-drafts#2219]
In [Feature and variation precedence](https://drafts.csswg.org/css-fonts-4/#apply-font-matching-variations), entries 4 and 5 are identical.

**Comment by GloverDonovan** [comment]
Hello,

Which entry should be removed? One of them uses `'font-feature-settings'` and the other one uses `'font-feature-settings!!descriptor'`. I'm not familiar with the code base so I don't know the difference between the two.

**Comment by frivoal** [comment]
Keeping the `'font-feature-settings!!descriptor'` one sounds better. [Bikeshed](https://tabatkins.github.io/bikeshed/) (the preprocessor we use) seems to be able to find the right definition anyway, it might also have linked to the property by the same name, so being explicit that we're trying to link to the descriptor is good.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/4e7de0f80383586e191f4da1ec079cf4c08978a9
