### ISSUE TITLE
[css-tables] 2.2.1 Add in caveat for flex and grid items

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#222]
According to this [resolution from the Paris F2F](https://log.csswg.org/irc.w3.org/css/2015-08-25/#e581286), the fixup is not as clean in a grid or flex context. We need to add this to section 2.2.1

**Comment by tabatkins** [comment]
Flex and Grid both explicitly call out that box-tree fixup happens *after* blockification.

**Comment by gregwhitworth** [comment]
Cool, but we should add a note for this so that anyone addressing tables that may not be aware of the flex/grid specific changes knows to check these.
