### ISSUE TITLE
[css-fonts-4] Proposed revisions to "Low-level font variation settings control".

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/csswg-drafts#2221]
In section 8.2 "[Low-level font variation settings control](https://drafts.csswg.org/css-fonts-4/#font-variation-settings-def)", the 5th paragraph says "Axis values not present in the font are ignored and therefore have no effect; a user agent must not attempt to synthesize fallback behavior based on these axis tags." I am not sure how to interpret this in the context of font fallback selection, and whether the specified behavior would always produce a desirable outcome - I think that a revision to this would be needed.

Let's consider the following example where an author would like to use @font-face rule to define myVariableFontA using a variation font resource that supports both 'wdth' (in 50 to 200 range) and 'wght' (in 100 to 900 range) axes, with its capabilities similar to what is illustrated by [this OpenType spec example](https://www.microsoft.com/typography/otspec/otvaroverview.htm#CSN). Let us also assume that the platform-supplied variable font SysVariableFontB implements a condensed typeface supporting only weight variation axis in the range of 300 to 600, and is available to be used as a fallback choice.

The primary font choice is defined as `@font-face { font-family: myVariableFontA; font-variation-settings: 'wght' 700, 'wdth' 70; }` where both variation axis have values assigned in their valid and supported value range specifying bold condensed typeface. 

If my primary font choice myVariableFontA fails to load, the SysVariableFontB would be used as a fallback font; however, this font doesn't support 'wdth' variation axis, and, being a condensed typeface by design, only supports a limited 300..600 range of weight variation. 

What would happen in this case? Would the required behavior of ignoring unsupported axis value be applied to the fallback font? It's understandable that the width axis is not supported by the fallback font and has to be ignored, but my primary font choice calls for 'wght' settings of 700 that are also outside of fallback font range of 300..600. The "ideal" behavior would be to use fallback SysVariableFontB with its nearest max supported 'wght' settings of 600, but, according to the spec as written, it looks like the unsupported value of 700 should also be ignored and the regular default weight of 400 would be applied - hardly the best choice from author's point of view.

I suggest to revise the 5th paragraph of section 8.2 to say that
- if the variation axis (defined by font-variation-settings) is not supported by the font the settings should be ignored;
- if the variation axis is supported but the defined value is out of supported range, the nearest value on supported range boundaries should be used.

**Comment by litherum** [comment]
> use @font-face rule to define myVariableFontA using a variation font resource that supports both 'wdth' (in 50 to 200 range) and 'wght' (in 100 to 900 range) axes

...

> `@font-face { font-family: myVariableFontA; font-variation-settings: 'wght' 700, 'wdth' 70; }`

The content should be saying `@font-face { font-family: myVariableFontA; font-weight: 100 900; font-stretch: 50% 200% }`

The `@font-variation-settings` descriptor doesn’t affect font selection, so “SysVariableFontB would be used as a fallback font” is right. But the `@font-face` block for SysVariableFontB wouldn’t specify `wdth 70` (because it doesn’t support the `wdth` axis), so the UA wouldn’t even try to apply the `wdth` axis in the first place.

In the example you gave, what is the element’s style which is referencing these fonts?

**Comment by vlevantovsky** [comment]
The example I provided meant to illustrate the referencing element. My point wasn't about UA not trying to apply 'wdth' settings to a fallback font - like I said in the example description, my choice of a condensed variable font as a fallback is based on my prior knowledge that the primary font I want to use is going to be used with the width settings of 70%. However, the issue here is that my fallback font doesn't support the same range of weight variation - primary font supports font weight 100 .. 900, while a fallback font only supports 300 .. 600. 

The particular paragraph of the spec I quoted speaks about axis values (which is not the same as axes present or missing). My concern is that, as currently specified, a weight setting value of 700 defined for a primary font would be completely ignored as out of range for a fallback font, resulting in using the default value of 400 (regular weight), where the ideal outcome would've been clamping the weight settings and using the maximum weight of 600 supported by a fallback font.

**Comment by litherum** [comment]
The 6th paragraph states:

> Axis values greater or less than the range supported by the font are clamped to the closest value supported by the font.

It sounds like this is the same as your proposal. Am I misunderstanding your proposal?

**Comment by vlevantovsky** [comment]
I am not sure how to reconcile the sentences in 5th and 6th paragraphs then, where one is saying "Axis values not present in the font are ignored and therefore have no effect" and another one saying "Axis values greater or less than the range supported by the font are clamped". Considering that we have 'name'/value pair for each axis, is it possible that in first case you meant to refer to missing axis names (i.e. a font doesn't support the axis 'name', therefore a value for this axis is ignored)?
And what about the case where e.g. I define:
`body {
  font-family: myVariableFontA, Helvetica;
  font-variation-setting: wght 700;
}`
where I expect myVariableFontA be applied in bold, and if the font gets substituted with Helvetica - would a browser recognize the bold setting for a fallback font?

**Comment by vlevantovsky** [comment]
After discussing this during F2F break, the following are things to do:
1) Add text encouraging authors to use predefined font properties for known/standardized variation axis, e.g. use 'font-weight 700' instead of 'font-variation-setting: wght 700';
2) Add text clarifying that the use of font variation settings does not affect font selection where fallback font is to be used, where using font properties for the same axis would have an effect on font selection. Discourage using mix of known and custom axis tags within the same font-variation-setting control.
3) in section 8.2, clarify wording of the 5th paragraph for axis handling, saying e.g.: "If a given axis is not supported by a font, its value setting is ignored and therefore has no effect; ... "
4) Similarly, it might be useful to modify the language of the 6th paragraph to say: "If a variation axis is supported by a font but its set value is greater or less than the predefined font range, it will be clamped to the closest value supported by the font."

**Comment by litherum** [comment]
Yep, these are good edits.
