### ISSUE TITLE
[website] inaccessible popover

### ISSUE THREAD

**Issue by pixelass** [w3c/csswg-drafts#2222]
When accessing the page https://drafts.csswg.org/css-transforms/ I see a popover that can only be closed by clicking a very thin lined (X) in the top right corner. 

The ESC button does not close the popover. 
The popover is not accessible via tab navigation.

Aside from that the popover seems to be unrelated to the content I wanted to access.
I used a clean browser in several networks and ran several checks to ensure it didn't come from my computer.

![screen shot 2018-01-23 at 19 46 23](https://user-images.githubusercontent.com/1148334/35294711-8c79b02e-0077-11e8-9451-a37f097f3efd.png)

**Comment by AmeliaBR** [comment]
@svgeesus Can you revert the code that added the "Battle For the Net" pop-up widget, please?  I'm not sure where the code is located; it does not appear to be in this repo. But I'm going from [this tweet](https://twitter.com/svgeesus/status/941091118313328642) that you were involved in adding it.

The points @pixelass made (above, and in #2216) are all valid. If you're going to create a pop-up, at least make sure it follows best practice. But I'd add: 

- It's a call to action for US-only political activity, but is shown to visitors from every country.
- The cookie that remembers that you've closed it only lasts a day, so those of us who use csswg.org on a regular basis have seen this far too many times over the past few weeks.

BTW:

- Was there any working group discussion about adding this?
- Is there any working group policy about who can make such a change & why?
- Is there any W3C policy about working groups engaging in political advocacy? The W3C [accepts US tax-deductible charitable donations](https://www.w3.org/Consortium/sponsor/) via MIT, and political advocacy could compromise that.

**Comment by astearns** [comment]
The working group did discuss this and resolved to put the banner up. We'll discuss when to take it down tomorrow.

**Comment by tomhodgins** [comment]
If it will take a discussion to change it, let me add that I feel similar to @pixelass, and as somebody who frequently _used to_ link CSS learners and clients directly to CSSWG drafts nearly daily, after having enough people concerned over what they see and ask me if the CSSWG site has been hacked or compromised—I've had to stopped linking people to it :/

The design and content of the popup are intended to shock and manipulate, the headline contains a lie. Trying to create an emotional response via manipulation it is _totally unprofessional_ and undermines the authority the CSSWG website tries to have.

It's a shame that people have leveraged the influence they have over an international group for the purpose of promoting national politics.

**Comment by Nadya678** [comment]
The pop-over only haunting me. If I had seen it first time, I fully rescanned my computer with antivirus with nonOS mode enabled and then ask other that it also see. I do not read it. If I see red alerts with request personal data or IBAN number I always panic. Please remove it and use less invasive method. For example link to the petition. 

BTW. Not only I did panic. 

This "popover" disabled me from seeing CSSWG for 2 days.

**Comment by astearns** [comment]
The popup has been changed to a banner.

**Comment by Nadya678** [comment]
@astearns The banner is less invasive and do not trigger panic but please show us votes of CSSVG members for and against the banner?

**Comment by tomhodgins** [comment]
Thank you for removing the original popup, I've started linking people to these draft specs again— recently I shared the current media queries draft and css values draft because they're ahead of the current specs and there's some really good information in there that just isn't covered anywhere else.

Thanks so much for making these drafts professional again!
