### ISSUE TITLE
Quirks mode and display styles for table elements

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2225]
Does any specification describe how should behave **table elements** with set `display:block` in quirks mode?

I detected that MSIE and Firefox behave differently. 
Firefox respects display:block for table elements, MSIE still display them as table, table-row, table-cell. 

Should it be clarified?

**Comment by FremyCompany** [comment]
https://wptest.center/#/d2my74
Given IE/Edge is the only engine still doing that thing, I don't believe we want to specify it.

**Comment by Nadya678** [comment]
If the PHP error will occur (with default configuration, then the <!DOCTYPE html> is not the first node (the first node is <br/> in this case) and the quirksmode will enable. Then all tables on smartphone are unreadable if the IE/EDGE behaviour is implemented. 

Privately I guess to remove "quirks mode" form CSS specification. It only makes browsers slower, the developers should repair their websites.

**Comment by FremyCompany** [comment]
Removing quirks mode is not an option, a lot of websites depend on those behavior. Removing IE/Edge's behavior for tables is something we could take a look at, but we would do so based on seeing records of broken sites. 

@Nadya678 Did you try to control-f5 refresh on wptest.center? I updated the site in early january to support IE, and this is working for me, but you could still have the old code in cache (I cache aggressively). If that does not fix it, feel free to send me an email at frremy microsoft.com with the error message you are seeing in the console.
