### ISSUE TITLE
[web-animations-1] Does an exception thrown by the call to play() be propagated up in reverse()?

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#2226]
In the procedure to [reverse an animation](https://drafts.csswg.org/web-animations-1/#reverse-an-animation), step 3 is defined as follows:

> Run the steps to play an animation for animation with the auto-rewind flag set to true.
>
> If the steps to play an animation throw an exception, restore the original playback rate by re-running > the procedure to silently set the playback rate with the original playback rate.

Does this mean that the exception needs to be propagated as well? That's not my reading, but this test in reversing-an-animation.html makes it sound like it should:

```javascript
test(t => {
  const div = createDiv(t);
  const animation = div.animate({}, { duration: 100 * MS_PER_SEC,
                                      iterations: Infinity });
  animation.currentTime = -200 * MS_PER_SEC;

  assert_throws('InvalidStateError',
    () => { animation.reverse(); },
    'reverse() should throw InvalidStateError ' +
    'if the playbackRate > 0 and the currentTime < 0 ' +
    'and the target effect is positive infinity');
}, 'Reversing an animation when playbackRate > 0 and currentTime < 0 ' +
   'and the target effect end is positive infinity should throw an exception');
```

**Comment by birtles** [comment]
Yes, the exception should be propagated. I'll clarify that as part of the changes I'm making to playback rate handling (which I'll hopefully merge today).
