### ISSUE TITLE
[css-align] Serialization of the alignment properties.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2229]
Should properties serialize the default values? Right now Blink and WebKit do so, which I think it's a bug.

In particular:

```css
align-items: unsafe start;
```

Serializes in Blink as `unsafe start`, and only `start` in FF. I think the computed value should serialize to the shortest form possible.

This is annoying because it causes a lot of WPT failures on Gecko.

**Comment by emilio** [comment]
cc @javifernandez

**Comment by emilio** [comment]
There's a similar issue with `first baseline`, where FF only serializes to `baseline`.

**Comment by emilio** [comment]
Also cc @matspalmgren, who also had an opinion on this IIRC.

**Comment by javifernandez** [comment]
Umm, I understand your point about _first baseline_ and I'm working now on matching FF on this regard. I haven't considered the case of _<overflow-position> <self-position>_  tough. Is it the same case ? cc @fantasai to gather more opinions. 

I think this is not the only CSSOM related issue we have, and I'm not sure we have a clear agreement about all these issues (see #1041 or #1033 for example) . I wouldn't mind to work on them as soon as we reach an agreement.

**Comment by javifernandez** [comment]
Some other examples are #418 #878 #1004

**Comment by MatsPalmgren** [comment]
CSS values should always be serialized to their shortest form.  (It's a [bug in the CSSOM spec](https://github.com/w3c/csswg-drafts/issues/1564) that it no longer explicitly spells that out.)  Regarding `first baseline` specifically, it's explicitly specified in [CSS Box Alignment](https://drafts.csswg.org/css-align-3/#typedef-baseline-position), which says: 
> Note: Because they are equivalent, and 'baseline' is shorter, the CSSOM
> serializes 'first baseline' as 'baseline'.

**Comment by fantasai** [comment]
What @MatsPalmgren said. Closing in favor of #1564, please re-open if there's some other consideration specific to css-align.

**Comment by MatsPalmgren** [comment]
It's worth noting though that `unsafe` isn't the default value in UAs that implements the behavior described under ["(no value specified)"](https://drafts.csswg.org/css-align-3/#typedef-overflow-position).
In an UA that implements that behavior, `align-items: unsafe start;` should in fact serialize to `align-items: unsafe start;` (IIUC).
