### ISSUE TITLE
[css-sizing] Computing min-width/min-height: auto to zero

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2230]
When exactly does 'auto' compute to zero?

http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%20%20html%20%7B%20display%3A%20flex%3B%20%7D%0A%3C%2Fstyle%3E%0ATest%0A%3Cscript%3E%0A%20%20w(window.getComputedStyle(document.body%2C%20null).getPropertyValue(%27min-height%27))%3B%0A%3C%2Fscript%3E

The  wording in Flexbox https://www.w3.org/TR/css-flexbox-1/#min-size-auto isn't particularly clear.

> On a flex item whose overflow is visible in the main axis, when specified on the flex item’s main-axis min-size property, specifies an automatic minimum size. It otherwise computes to 0 (unless otherwise defined by a future specification). 

Does it compute to zero
- on flex items, in the main axis, when 'overflow' is visible?
- on flex items, in the main axis, always? (Firefox does this)
- on flex items, in both axes? (Chrome does this)

We should probably bias towards computing to `auto` in as many cases as is Web-compatible, but we should also fix the spec to say exactly what happens.

**Comment by Loirooriol** [comment]
I get other results:

 - On Chrome and Edge, on flex items, `auto` always computes to itself in both axes, even if `overflow` is not `visible`.
 - On Firefox, on flex items, `auto` computes to itself in the main axis when `overflow` is `visible`. Otherwise it computes to 0.

**Comment by dholbert** [comment]
I'm confused about the resolution here. The end of the minutes had this:
> Rossen_: Sounds like we have 3 impl shipping the proposed behavior.
> 12:32 PM Rossen_: I'm going to call for objections. Any objections?
> 12:32 PM RESOLVED: compute min-width/min-height: auto to zero

I assume the 3 impl are Webkit/Blink/Edge, but according to https://github.com/w3c/csswg-drafts/issues/2230#issuecomment-361013696 , those 3 impls all compute min-width/min-height:auto *to itself* in both axes, which is not what the resolution said to do.

Can someone clarify what the resolution was?

**Comment by tantek** [comment]
Also please clarify whether this resolution is ONLY for grid and flex items, or has broader scope.

**Comment by fantasai** [comment]
Fixed the minutes, clearly they were wrong. Grid and flex items only; other things can be considered as separate issues on a case by case basis.

**Comment by tantek** [comment]
From IRC: <blockquote>Rossen_: RESOLVED: computed value of min width and min height is auto even if it's internally resolved to 0 for layout purposes</blockquote>
and yes for grid & flex items only, anything else file that separate

**Comment by fantasai** [comment]
I believe this is fixed in the specs; please re-open if there is anything unclear about it in css-grid/css-flexbox/css-sizing!
