### ISSUE TITLE
[css-text-3][CSS2] bidi white space collapsing, with bidi control characters

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2233]
[CSS2](https://www.w3.org/TR/CSS2/text.html#white-space-model) (and also [CSS-TEXT-3](https://drafts.csswg.org/css-text-3/#white-space-phase-1)) is pretty clear about how control characters should be processed when doing white space collapsing:

> For each inline element (including anonymous inline elements), the following steps are performed, **treating bidi formatting characters as if they were not there**: 
> ...

However, it seems that all browsers agree not to do that:
http://jsbin.com/locakid/edit?html,output

They do it correctly when the bidi situation is caused by markup/properties, but not when it comes from bidi control characters.

This causes https://github.com/w3c/web-platform-tests/issues/5460

We need either to fix the specs or to fix the browsers. Browsers all behaving the same makes me doubt changing this is web compatible, but bidi or i18n experts should chime in about how important this is.

@fantasai, what do you think?

**Comment by fantasai** [comment]
I doubt there's a Web-compat issue here--if you're collapsing spaces, you expect the spaces collapsed, and as an author you're not particularly aware of bidi characters. That said, I don't consider this an important situation to handle correctly, so it might not be worth asking the browsers to fix it.

**Comment by fantasai** [comment]
There's already a test for this, it's bidi-003, written by Hixie a long time ago. It's not complete, since it only handles some bidi control characters, but it exists.

**Comment by frivoal** [comment]
Right. This whole issue started by noticing the test failed, so I was a bit to quick in saying we need more tests. We always need more tests to be more exhaustive, but the base case of this issue is covered. Removing the "Needs Testcase" label.

**Comment by frivoal** [comment]
There's nothing left to do here, so closing.

Not entirely sure if this should count as "resolved as accepted" or "resolved as rejected", since the bug was an open question, not a request for a particular behavior, but "accepted" gets us more green, and I'm happy with the conclusion, so green sounds good.
