### ISSUE TITLE
[css-writing-modes] Should max-height also limit orthogonal flows?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2239]
Imagining a vertical flow inside a horizontal document: right now if the containing block of the orthogonal flow has a fixed `height`, we use that as a limit on the height of the orthogonal flow; otherwise we use the nearest fixed-size scrollport or the ICB. Should we also consider `max-height`?

**Comment by FremyCompany** [comment]
I always thought this behavior would make sense. 

What is way less clear is whether working on updating orthogonal writing mode is what browser vendors should be doing right now... or, you know, fixing all these flexbox spec violations ;)

**Comment by frivoal** [comment]
@fantasai I've added variants of the available size tests to account for min-width as discussed on the call yesterday in the https://github.com/w3c/web-platform-tests/pull/9255 Pull request.
