### ISSUE TITLE
[selectors-4] circular references in section 3.1

### ISSUE THREAD

**Issue by therealglazou** [w3c/csswg-drafts#2240]
I see a few issues in that section.

Issue 1:
--------

> The subject of a selector is the element(s) that selector is defined to be about:
>
> ...
>     For a complex selector, it is any element that matches the last compound selector in the selector.
> 

The above is wrong: it says the element "matches" the last compound
selector. Which means "only". A more correct prose would say it matches
the last compound selector while its context matches the other compound
selector in the complex selector AND the relationships expressed by the
combinators...

Issue 2:
--------

  The definition of "subject of selector" relies on a mix of
  "represented" and "matches". I think it's wrong because below "match"
  is itself defined in reference to "subject"... We then have an
  circular ref there.

Proposal:
---------

I think we have too many circular definitions right now in that section
3.1. Here's a different proposal:

>   The term selector can refer to a simple selector, compound selector,
>   complex selector, or selector list.
> 
>   A simple selector is a single condition on an element. (...) A given
>   element is said to match a simple selector when it makes the
>   corresponding condition true.
> 
>   A compound selector is a sequence of simple selectors that are not
>   separated by a combinator. It represents a set of simultaneous
>   conditions on a single element. (...) A given element is said to
>   match a compound selector when it matches all simple selectors
>   in the compound selector.
> 
>   A combinator is a condition of relationship between two elements
>   represented by the compound selectors on either side of the
>   combinator. (...) Two given elements are said to match a combinator
>   when the condition of relationship between these elements is true.
> 
>   A complex selector is a sequence of one or more compound selectors
>   separated by combinators. It represents a set of simultaneous
>   conditions on a list of elements in particular relationships. (...)
>   A given element is said to match a complex selector when it exists
>   a list of elements individually matching each corresponding compound
>   selector in the complex selector, each pair of consecutive elements in
>   that list matches the combinator separating the two corresponding
>   compound selectors, and the last element in that list is the given
>   element.
> 
>   A list of simple/compound/(...)
> 
>   For simple, compound or complex selectors, the subject of that
>   selector is any element matching that selector. For a selector
>   list, the subject of that selector list is any element matching any
>   selector in the list.

**Comment by fantasai** [comment]
Daniel, thank you **so much** for this. This is a subtle and fiddly section that's never been quite right. I've gone ahead and cleaned up this section following your advice, with some additional wording changes. Please have a look at the resulting changes and let me know if it works, and if I've messed anything up in translation?

**Comment by Loirooriol** [comment]
I prefer Daniel's proposal here:

> A given element is said to match a complex selector when it exists
a list of elements individually matching each corresponding compound
selector in the complex selector, **each pair of consecutive elements** in
that list matches the combinator separating the two corresponding
compound selectors

better than

> A given element is said to match a complex selector when there exists
a list of elements, each matching a corresponding compound selector
in the complex selector, **with their relationships matching the combinators
between them**, and with the given element matching the last compound selector.

The latter is less precise and can seem over-constrained, e.g. if you have `a + b c`, one may think that the elements matched by `a` and `c` must match both combinators between them (i.e. the element matched by `c` should be both the next sibling and a descendant of `a`, which is not possible).

And I would also say "matching **the** corresponding" instead of "matching **a** corresponding".

**Comment by fantasai** [comment]
Thanks for the review, @Loirooriol ! I pushed some edits to bring it closer to the former phrasing.

> And I would also say "matching the corresponding" instead of "matching a corresponding".

I definitely debated that back and forth (between "a", "the", and "its") for awhile, but ended up resolving on "a" as the best option there. It's definitely a little more awkward than I would like ideally, but I suspect fixing it would involve some more substantial rephrasing which I cannot figure out.
