### ISSUE TITLE
[css-values-4][cssom] <resolution> serializes to 'dppx', not 'x'

### ISSUE THREAD

**Issue by csnardi** [w3c/csswg-drafts#2241]
After #461, [Values 4 states that](https://drafts.csswg.org/css-values-4/#resolution):

> All \<resolution\> units are compatible, and 'x' is their canonical unit.

However, [the CSSOM spec](https://drafts.csswg.org/cssom/#serializing-css-values) for serializing \<resolution\> says:

> The resolution in dots per CSS pixel serialized as per \<number\> followed by the literal string "dppx".

The Typed OM spec also makes no mention of 'x', [only 'dppx'](https://drafts.css-houdini.org/css-typed-om-1/#dom-css-dppx).

Should the canonical unit for \<resolution\> be changed back to 'dppx'? Changing all of these serializations to 'x' from 'dppx' might not be web-compatible, and would result in differences in serialization among browsers that have/have not added 'x' as a unit of resolution.

**Comment by csnardi** [comment]
This also raises: how should 'x' be serialized alone? Should it become 'dppx'? Or remain as 'x'?

**Comment by upsuper** [comment]
Looks like `x` and `dppx` are actually the same unit. Probably we should just change Vaues 4 to state `dppx` is the canonical unit rather than `x`, given it is mentioned in other places, and it feels more meaningful.

**Comment by csnardi** [comment]
Makes sense; but then would e.g. '1x' be serialized to '1dppx'? It seems the previous resolution didn't have a clear answer to this; the relevant discussion from #461 is below:

> \<dael\> fantasai: We've never had alias units, so what do you get if you serialize it back out.
> \<dael\> leaverou: dpx?
> \<leaverou\> s/dpx/dppx/
> \<dael\> TabAtkins: It's only image resolution and webkit image set, so let's see what webkit does and do what they say. It'll b e x or dppx.
> \<dael\> smfr: Pretty sure it's x
> \<dael\> fantasai: If you put in dppx do you get out x?
> \<dael\> TabAtkins: In specified style no. We don't need fancy. They're different units with a 1 to 1 ratio. In computed when you canonicalize you go to probably x.

This seems to suggest that there are two different units rather than one unit with two names, which doesn't seem to be clear in the spec. I'm also not sure if this makes the most sense, as they really are the same unit, just specified in two different ways.

**Comment by foolip** [comment]
@tabatkins should this have the "needs testcase" label or what will traxk the eventual creation/updating of tests?

@csnardi I guess you mean to add tests as part of the implementation?

**Comment by csnardi** [comment]
Yep, the plan is to add tests while implementing. It looks like @emilio also might be adding tests in https://bugzilla.mozilla.org/show_bug.cgi?id=1460655, but I think that's for the Firefox version of https://github.com/w3c/web-platform-tests/blob/master/css/mediaqueries/test_media_queries.html and not the WPT version.

**Comment by emilio** [comment]
Oh I didn't know that that test was in WPT. I'll modify the WPT test too.
