### ISSUE TITLE
[css-values] Actually describe how/whether computed math functions are simplified from specified ones

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#2245]
In [V&U](https://drafts.csswg.org/css-values/#calc-computed-value), the computed value of a math function is described as just absolutizing the units.  But then when you [*serialize* the function](https://drafts.csswg.org/css-values/#serialize-a-calc-value), you do a more elaborate simplification process, so that, for example, `calc(5 * (1px + 2em))` serializes to `calc(5px + 10em)`.

Whether we simplify eagerly or just at serialization time isn't observable in old CSS (since there's no behavior difference between the two forms, and you have to serialize it to examine it directly), but it *is* observable in TypedOM, which produces equivalent `CSSMathValue` trees from a `calc()`.  As currently specified, the serialization of the above value as a Typed OM value would differ from its serialization via CSSOM, which seems bad.

Should we specify that simplification happens eagerly, so that all ways of observing the value agree on its form?

**Comment by tabatkins** [comment]
Agenda+ because this came up again with our implementor (see <https://github.com/w3c/css-houdini-drafts/issues/913>).

My opinion is that yes, we should definitely simplify the underlying value eagerly, so any representation of the value (stringified or reified) sees the same structure.

**Comment by andruud** [comment]
> so any representation of the value (stringified or reified) sees the same structure.

That makes sense.

What if you create an underlying value `calc(5 * (1px + 2em))` using Typed OM objects? Will that get simplified too, or will simplification only apply to values that are parsed?

**Comment by tabatkins** [comment]
It's not an underlying value until you .set() it; at that point, the two input methods should act the same, and the underlying value should be simplified.

**Comment by andruud** [comment]
> It's not an underlying value until you .set() it

That's what I meant. I didn't mean that `CSSStyleValue`s should somehow simplify "live". :-)

> the two input methods should act the same, and the underlying value should be simplified.

OK, this means we never have to store non-simplified underlying values. Nice. cc @xiaochengh

**Comment by tabatkins** [comment]
I've begun speccing all the changes needed to actually define the internal value of math functions and how to simplify them at <https://drafts.csswg.org/css-values-4/#calc-internal>. The big missing piece left is serializing.

**Comment by tabatkins** [comment]
Over the last several commits, I've edited V&U 4 to properly handle all the new math functions.

* Math functions now form a "calculation tree" as their internal representation.
* Specified exactly how to parse a stream of component values into a calculation tree.
* Specified exactly how to simplify a calculation tree (in a way that *should*, if I've done things right, always result in a sum of simple numeric values when you feed it any old-style calc)
* Specified exactly when simplification happens (immediately upon parsing, and again at computed-value time and used-value time).
* Specified exactly how to serialize a math function and its calculation tree.

Please review <https://drafts.csswg.org/css-values/#calc-internal> and subsequent sections, and let me know if there are any problems!

**Comment by xiaochengh** [comment]
@tabatkins Thanks for making things work!

I'm not sure if I'm understanding the handling of percentages correctly. Could you clarify?

> If root is a percentage that will be resolved against another value, and there is enough information available to resolve it, do so

Can we be more specific about "enough information available"? IIUC we shouldn't resolve % in <length-percentage> at & before computed time. However, at least in some cases, we already have that information at computed time (e.g., when the parent element has a fixed width).

> If root is a Min, Max, Clamp, Sin, Cos, Tan, Asin, Acos, Atan, Atan2, Pow, Sqrt, or Hypot node, and all of its children are numeric values with enough information to computed the operation root represents, return the result of running root’s operation using its children

For min/max/clamp(%), this seems to have something to do with #4227. Or we probably need to be more specific about "enough information" again.

---

One last thought, it's probably better to add some examples or notes. As this version is less declarative than the previous one, it's harder to figure out the expected result without following the algorithm step-by-step. Can we add some notes for some simple/common cases? For example, when there's no non-calc math functions (which I believe is the most common case), the result is a summation of numeric values of different units that can't be further merged.

**Comment by tabatkins** [comment]
> IIUC we shouldn't resolve % in at & before computed time. However, at least in some cases, we already have that information at computed time (e.g., when the parent element has a fixed width).

Some %s should be resolved at computed-value time.  'width' isn't one of those, because layout hasn't been done yet. This wording shouldn't be less specific than the old wording, which was:

> Where percentages are not resolved at computed-value time, they are not resolved in math functions, e.g. calc(100% - 100% + 1px) resolves to calc(0% + 1px), not to 1px. If there are special rules for computing percentages in a value (e.g. the height property), they apply whenever a math function contains percentages.

(Note to myself: I could probably carry over some of the wording of that last sentence. That's not relevant to what you are asking, tho.)

> For min/max/clamp(%), this seems to have something to do with #4227. Or we probably need to be more specific about "enough information" again.

No, it's independent of that; how #4227 is resolved will affect this (by defining when the comparison is allowed to be resolved), but this doesn't affect #4227.

> One last thought, it's probably better to add some examples or notes. As this version is less declarative than the previous one, it's harder to figure out the expected result without following the algorithm step-by-step. Can we add some notes for some simple/common cases? For example, when there's no non-calc math functions (which I believe is the most common case), the result is a summation of numeric values of different units that can't be further merged.

Yup, I need to add more examples of the new stuff, indeed.

And yes, when you limit the input to what was allowed before we added unit algebra and math functions, the intention is that this *should* produce a sum of unmergeable numeric values.
