### ISSUE TITLE
[selectors-4] update HTML link?

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#2250]
It's now https://html.spec.whatwg.org/multipage/semantics-other.html#selectors. The old one redirects, but it's without HTTPS and relies on JavaScript to redirect fully.

**Comment by fantasai** [comment]
Fixed, thanks! (Also went through and updated the rest of the links.)

**Comment by fantasai** [comment]
I couldn't find a target for the previously-existing `dropzone` attribute, though, so I deleted the sentence referring to it... I suspect the drag-and-drop section needs a thorough review (and possible deletion) from someone who understands the HTML feature's current state.
