### ISSUE TITLE
[selectors-4] :defined

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#2258]
HTML defines `:defined`: https://html.spec.whatwg.org/multipage/semantics-other.html#selector-defined.

1. Is that enough for a definition of a new pseudo-class?
2. Is it fine for HTML to define this?
3. Should Selectors contain a registry of externally defined selectors?

(I'm asking this in part since we're considering a `:heading(level)` pseudo-class.)

See also: https://github.com/w3c/webcomponents/issues/665.

cc @domenic @snuggs

**Comment by fantasai** [comment]
Can I get a layperson's definition of :defined and what it's used for? :)

Wrt :heading(), we've gotten requests for this an declined them so far. If it's something we want to add, we can add it to Selectors--it's definitely not an HTML-specific concept, so it should go into Selectors and not HTML.

**Comment by annevk** [comment]
`:defined` matches all elements that had no problem during construction, roughly. It's useful since you can now implement your own element class and sometimes you want to match elements for which the constructor has not yet run (or vice versa).

As for headings, that sounds reasonable, though we'll run into the data model issue again (though arguably we do already for other things, so it doesn't necessarily add to the problem).

**Comment by snuggs** [comment]
To embellish on @annevk's statement with an example.

```html
<foo-bar></foo-bar>

<style>
  foo-bar { visibility: hidden }
  foo-bar:defined { visibility: show }
</style>
```

If a user wanted to preserve real estate but not display until element is `defined`.

@annevk does that help or hurt?

**Comment by snuggs** [comment]
@annevk @fantasai is this good to close now that is on track with CSS Level4?

**Comment by annevk** [comment]
I think it would make sense to close this when the PR that adds this to Selectors Level 4 lands.

**Comment by hober** [comment]
> I think it would make sense to close this when the PR that adds this to Selectors Level 4 lands.

As w3c/csswg-drafts#3735 landed a while ago, can we close this issue now?
