### ISSUE TITLE
[css-values] Inconsistent position serialization

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2274]
The `position` [spec](https://drafts.csswg.org/css-values/#position) mentions

> The canonical order when serializing is the horizontal component followed by the vertical component.

but does not discuss if the serialization should contain the author's supplied keywords or if they should be converted to equivalent percentages.

The spec also doesn't mention if 'center' should be added or removed when serializing. (Edge and Safari sometimes serialize `center center` as `center`.)

Browsers are currently inconsistent with themselves and each other:

| 10% | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | 10% center | 10% | 10% center | 10% center | 
| background-position: `<bg-position>` | 10% center | 10% | 10% center | 10% center | 
| object-position: `<position>` | 10% center | 10% 50% | 10% center | 10% center | 
| perspective-origin: `<position>` | 10% center | 10% 50% | 10% center | 10% center | 
| shape-outside: circle(at `<position>`) | 10% 50% | 10% | 10% | 10% 50% | 

| 20% 30px | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | 20% 30px | 20% 30px | 20% 30px | 20% 30px | 
| background-position: `<bg-position>` | 20% 30px | 20% 30px | 20% 30px | 20% 30px | 
| object-position: `<position>` | 20% 30px | 20% 30px | 20% 30px | 20% 30px | 
| perspective-origin: `<position>` | 20% 30px | 20% 30px | 20% 30px | 20% 30px | 
| shape-outside: circle(at `<position>`) | 20% 30px | 20% 30px | 20% 30px | 20% 30px | 

| 30px center | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | 30px center | 30px | 30px center | 30px center | 
| background-position: `<bg-position>` | 30px center | 30px | 30px center | 30px center | 
| object-position: `<position>` | 30px center | 30px 50% | 30px center | 30px center | 
| perspective-origin: `<position>` | 30px center | 30px center | 30px center | 30px center | 
| shape-outside: circle(at `<position>`) | 30px 50% | 30px center | 30px center | 30px 50% | 

| 40px top | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | 40px top | 40px top | 40px top | 40px top | 
| background-position: `<bg-position>` | 40px top | 40px top | 40px top | 40px top | 
| object-position: `<position>` | 40px top | 40px 0% | 40px top | 40px top | 
| perspective-origin: `<position>` | 40px top | 40px top | 40px top | 40px top | 
| shape-outside: circle(at `<position>`) | 40px 0% | 40px top | 40px top | 40px 0% | 

| bottom 10% right 20% | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | right 20% bottom 10% | right 20% bottom 10% | right 20% bottom 10% | right 20% bottom 10% | 
| background-position: `<bg-position>` | right 20% bottom 10% | right 20% bottom 10% | right 20% bottom 10% | right 20% bottom 10% | 
| object-position: `<position>` | right 20% bottom 10% | calc(80%) calc(90%) | right 20% bottom 10% | right 20% bottom 10% | 
| perspective-origin: `<position>` | right 20% bottom 10% | undefined | right 20% bottom 10% | right 20% bottom 10% | 
| shape-outside: circle(at `<position>`) | 80% 90% | bottom 10% right 20% | bottom 10% right 20% | 80% 90% | 

| bottom right | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | right bottom | right bottom | right bottom | right bottom | 
| background-position: `<bg-position>` | right bottom | right bottom | right bottom | right bottom | 
| object-position: `<position>` | right bottom | 100% 100% | right bottom | right bottom | 
| perspective-origin: `<position>` | right bottom | right bottom | right bottom | right bottom | 
| shape-outside: circle(at `<position>`) | 100% 100% | bottom right | bottom right | 100% 100% | 

| center | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center center | center | center center | center center | 
| background-position: `<bg-position>` | center center | center | center center | center center | 
| object-position: `<position>` | center center | 50% 50% | center center | center | 
| perspective-origin: `<position>` | center center | center 50% | center center | center center | 
| shape-outside: circle(at `<position>`) | 50% 50% | center | center | 50% 50% | 

| center 50px | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center 50px | center 50px | center 50px | center 50px | 
| background-position: `<bg-position>` | center 50px | center 50px | center 50px | center 50px | 
| object-position: `<position>` | center 50px | 50% 50px | center 50px | center 50px | 
| perspective-origin: `<position>` | center 50px | center 50px | center 50px | center 50px | 
| shape-outside: circle(at `<position>`) | 50% 50px | center 50px | center 50px | 50% 50px | 

| center bottom | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center bottom | bottom | center bottom | center bottom | 
| background-position: `<bg-position>` | center bottom | bottom | center bottom | center bottom | 
| object-position: `<position>` | center bottom | 50% 100% | center bottom | center bottom | 
| perspective-origin: `<position>` | center bottom | center bottom | center bottom | center bottom | 
| shape-outside: circle(at `<position>`) | 50% 100% | center bottom | center bottom | 50% 100% | 

| center center | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center center | center | center center | center center | 
| background-position: `<bg-position>` | center center | center | center center | center center | 
| object-position: `<position>` | center center | 50% 50% | center center | center | 
| perspective-origin: `<position>` | center center | center center | center center | center center | 
| shape-outside: circle(at `<position>`) | 50% 50% | center center | center center | 50% 50% | 

| center left | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | left center | left | left center | left center | 
| background-position: `<bg-position>` | left center | left | left center | left center | 
| object-position: `<position>` | left center | 0% 50% | left center | left center | 
| perspective-origin: `<position>` | left center | left center | left center | left center | 
| shape-outside: circle(at `<position>`) | 0% 50% | center left | center left | 0% 50% | 

| left | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | left center | left | left center | left center | 
| background-position: `<bg-position>` | left center | left | left center | left center | 
| object-position: `<position>` | left center | 0% 50% | left center | left center | 
| perspective-origin: `<position>` | left center | left 50% | left center | left center | 
| shape-outside: circle(at `<position>`) | 0% 50% | left | left | 0% 50% | 

| left bottom | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | left bottom | left bottom | left bottom | left bottom | 
| background-position: `<bg-position>` | left bottom | left bottom | left bottom | left bottom | 
| object-position: `<position>` | left bottom | 0% 100% | left bottom | left bottom | 
| perspective-origin: `<position>` | left bottom | left bottom | left bottom | left bottom | 
| shape-outside: circle(at `<position>`) | 0% 100% | left bottom | left bottom | 0% 100% | 

| left center | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | left center | left | left center | left center | 
| background-position: `<bg-position>` | left center | left | left center | left center | 
| object-position: `<position>` | left center | 0% 50% | left center | left center | 
| perspective-origin: `<position>` | left center | left center | left center | left center | 
| shape-outside: circle(at `<position>`) | 0% 50% | left center | left center | 0% 50% | 

| right 30% top 60px | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | right 30% top 60px | right 30% top 60px | right 30% top 60px | right 30% top 60px | 
| background-position: `<bg-position>` | right 30% top 60px | right 30% top 60px | right 30% top 60px | right 30% top 60px | 
| object-position: `<position>` | right 30% top 60px | calc(70%) 60px | right 30% top 60px | right 30% top 60px | 
| perspective-origin: `<position>` | right 30% top 60px | undefined | right 30% top 60px | right 30% top 60px | 
| shape-outside: circle(at `<position>`) | 70% 60px | right 30% top 60px | right 30% top 60px | 70% 60px | 

| right 40% | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | right 40% | right 40% | right 40% | right 40% | 
| background-position: `<bg-position>` | right 40% | right 40% | right 40% | right 40% | 
| object-position: `<position>` | right 40% | 100% 40% | right 40% | right 40% | 
| perspective-origin: `<position>` | right 40% | right 40% | right 40% | right 40% | 
| shape-outside: circle(at `<position>`) | 100% 40% | right 40% | right 40% | 100% 40% | 

| top | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center top | top | center top | center top | 
| background-position: `<bg-position>` | center top | top | center top | center top | 
| object-position: `<position>` | center top | 50% 0% | center top | center top | 
| perspective-origin: `<position>` | center top | 50% top | center top | center top | 
| shape-outside: circle(at `<position>`) | 50% 0% | top | top | 50% 0% | 

| top center | Chrome 64 | Edge 16 | Firefox 58 | Safari 11 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | center top | top | center top | center top | 
| background-position: `<bg-position>` | center top | top | center top | center top | 
| object-position: `<position>` | center top | 50% 0% | center top | center top | 
| perspective-origin: `<position>` | center top | center top | center top | center top | 
| shape-outside: circle(at `<position>`) | 50% 0% | top center | top center | 50% 0% |

**Comment by ewilligers** [comment]
Some more test results (I will copy them across to Markdown tables):
['top 10% left 20%'](https://docs.google.com/document/d/1mYCBLbFRdLqiBCWhqIU9CRThI-dJQNDx1LSiNnekNPA/edit)
['0% 50%'](https://docs.google.com/document/d/1OkuC9LARZ4s53iNfvOOuZrzRc5kTuuvtvXKCn3FRkFk/edit)

**Comment by ewilligers** [comment]
All of the above were specified values. There is also variation in **computed values**.

| left 10% top | Chrome 67 | Edge 17 | Firefox 60 | Safari 11.1 | 
| --- | --- | --- | --- | --- | 
| background-position: `<bg-position>` | left 10% 0% | 10% 0% | 10% 0% | left 10% 0% | 

| right 10% top | Chrome 67 | Edge 17 | Firefox 60 | Safari 11.1 | 
| --- | --- | --- | --- | --- | 
| background-position: `<bg-position>` | right 10% 0% | right 10% top 0% | 90% 0% | right 10% 0% | 

| top 10% left 20% | Chrome 67 | Edge 17 | Firefox 60 | Safari 11.1 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | left 20% top 10% | 20% 10% | 20% 10% | left 20% top 10% | 
| background-position: `<bg-position>` | left 20% top 10% | 20% 10% | 20% 10% | left 20% top 10% | 
| object-position: `<position>` | 20% 10% | 20% 10% | 20% 10% | 20% 10% | 
| perspective-origin: `<position>` | 20px 0px | 50px 0px | 20px 0px | 20px 0px | 
| shape-outside: circle(at `<position>`) | 20% 10% | undefined | undefined | 20% 10% | 

| 0% 50% | Chrome 67 | Edge 17 | Firefox 60 | Safari 11.1 | 
| --- | --- | --- | --- | --- | 
| background-image: radial-gradient(at `<position>`, red, blue) | 0% 50% | 0% 50% | 0% 50% | 0% 50% | 
| background-position: `<bg-position>` | 0% 50% | 0% 50% | 0% 50% | 0% 50% | 
| object-position: `<position>` | 0% 50% | 0% 50% | 0% 50% | 0% 50% | 
| perspective-origin: `<position>` | 0px 0px | 0px 0px | 0px 0px | 0px 0px | 
| shape-outside: circle(at `<position>`) | 0% 50% | undefined | 0% 50% | 0% 50% | 

([raw results](https://docs.google.com/document/d/1mYCBLbFRdLqiBCWhqIU9CRThI-dJQNDx1LSiNnekNPA/edit))

**Comment by emilio** [comment]
FWIW, Servo's / Firefox's logic for computed `<position>`:

  https://searchfox.org/mozilla-central/rev/403038737ba75af3842ba6b43b6e2fb47eb06609/servo/components/style/values/computed/position.rs#43

And specified:

  https://searchfox.org/mozilla-central/rev/403038737ba75af3842ba6b43b6e2fb47eb06609/servo/components/style/values/specified/position.rs#159

**Comment by BorisChiou** [comment]
It seems this issue is resolved, so could anyone please help update the spec?

**Comment by tabatkins** [comment]
Should be well-defined now. The minutes were slightly unclear, but we believe what's now specified in <https://github.com/w3c/csswg-drafts/commit/0742ad6e372782b46cca9708fa293e2b5abab219> matches the details and the intent of the conversation.

**Comment by fantasai** [comment]
Marking Needs Edits for the referencing specs (css-backgrounds, etc.)

**Comment by cdoublev** [comment]
Can I assume the expected changes are as follows?

```diff
If three values are given, the missing offset is assumed to be zero.
+
+ Serializing the 'background-position' is the same as [[css-values-4#position-serialization]].
+ If three components are specified:
+
+   * 'center' is replaced with 'left 50%' when it is the first component, otherwise with 'top 50%'
+   * an omitted offset is replaced with '0 %'
 ```

**Comment by fantasai** [comment]
For `<bg-position>`’s 3-value syntax, we currently have interop across all browsers on serializing 3-value inputs as 3-value output, exactly preserving the author's specified components (but rearranging them to horizontal-vertical order, if needed), see [testcase](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cbody%20style%3D%22background-position%3A%20left%2025px%20top%2C%20left%20top%2025px%2C%20left%2010px%20center%2C%20center%20top%2010px%2C%20top%2010px%20left%22%3E%0A%0A%3Cscript%3E%0Aw(document.body.style.backgroundPosition)%3B%0Aw(getComputedStyle(document.body).backgroundPosition)%3B%0A%3C%2Fscript%3E).

Agenda+ to discuss reverting the previous resolution to force these into 4-value serializations, and preserving the author's 3-value expression.

**Comment by cdoublev** [comment]
Then is there any reason to keep serializing 1-value inputs with 2 values?
