### ISSUE TITLE
[css-fonts] description of font-style:italic is wrong

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2278]
The description of the 'italic' value at [1] says "Matches against a font that is labeled as an oblique face, or an italic face if one is not."

This is clearly inverted; it should prefer to match italic, or oblique if italic is not available.

[1] https://drafts.csswg.org/css-fonts-4/#valdef-font-style-italic

**Comment by svgeesus** [comment]
Hi Jonathan. Thanks, yes, this is a copy-paste error.

Fonts 3 says 

> **italic**
>    selects a font that is labeled as an italic face, or an oblique face if one is not 
> **oblique**
>    selects a font that is labeled as an oblique face, or an italic face if one is not 

Fonts 4 adds an optional angle to the oblique value, but the italic value should be unchanged.

**Comment by litherum** [comment]
Whoops, sorry

**Comment by svgeesus** [comment]
Fixing now

**Comment by svgeesus** [comment]
Huh. normal 

> Matches against a face that is classified as a normal face, one that is neither italic or obliqued. This represents an oblique value of "0".

```
@font-face {
  font-family: foo;
  src: url(foo-book.woff);
}
@font-face {
  font-family: foo;
  font-style: oblique;
  src: url(foo-obl.woff);
}
p { 
  font-family: foo;
  font-style: oblique 0 
}
```

So that matches foo-book because it asks for an angle of zero? Or foo-obl because that is the only one declared as oblique?
