### ISSUE TITLE
[css-grid] nit: the description of the conditions for when Automatic Minimum Size applies could be clearer

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2283]
https://drafts.csswg.org/css-grid/#min-size-auto
The first paragraph ends with:
> and which span at least one track whose min track sizing function is `auto`.

It's ambiguous if that means "in any axis" or "in the specified axis".
I suggest you append "in that axis" to the above sentence to make it unambiguous.

(The "whose `overflow` is `visible`" part is unambiguous by accident since `visible` in one axis implies it's `visible` in both axes.)

**Comment by fantasai** [comment]
Fixed, thanks!
