### ISSUE TITLE
[web-animations-1] getKeyframes() processing steps need updating after null composite

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#2289]
In KeyframeEffectReadOnly::getKeyframes(), we now say that `composite` should always be set with a default of `null` in the non-normative section:

> **composite**
> The keyframe-specific composite operation used to combine the values specified in this keyframe with the underlying value.
> 
> This member will be null if the composite operation specified on the keyframe effect is being used.

However, in the (normative) processing steps below, we say:

> 2. Set offset, computedOffset, easing members of output keyframe to the respective values keyframe offset, computed keyframe offset, and keyframe-specific timing function of keyframe.
>
> 3. If keyframe has a keyframe-specific composite operation, set composite to that value.

I believe we should get rid of 3. and update 2. to read:

> 2. Set offset, computedOffset, easing, composite members of output keyframe to the respective values keyframe offset, computed keyframe offset, keyframe-specific timing function and keyframe-specific composite operation of keyframe.

**Comment by birtles** [comment]
Yeah, this is one of the (many) awkwardnesses of having a separate model and API. The intention was that "null" is just an API concept corresponding to the absence of a keyframe-specific composite operation. However, we already talk about null offset values so we should just talk about null composite operations too.

**Comment by birtles** [comment]
2625ca2c83d3eeaff8b2aafa680a02872f0f5e5e fixes the obvious grammatical error in that previous commit too.
