### ISSUE TITLE
Does a previously clear-ed float still contribute geometry?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#2291]
Here is an interop issue between Chrome/Safari and Edge/Firefox:
> https://wptest.center/#/487ld5
> ![image](https://user-images.githubusercontent.com/364405/35994201-90968bba-0cc4-11e8-971d-06b2bd93d5aa.png)
> ![image](https://user-images.githubusercontent.com/364405/35994266-bfadca6c-0cc4-11e8-9ff6-19da68946602.png)

In the testcase, a float is colliding another float that has already been cleared but reappear in the constraint space due to a negative margin set in the flow. Chrome/Safari ignores that collision, while Firefox/Edge honor it.
 
I don't think there is a relevant text to clarify the expected behavior here since:

> In CSS 2.1, if, within the block formatting context, there is an in-flow negative vertical margin such that the float's position is above the position it would be at were all such negative margins set to zero, the position of the float is undefined. 
> www.w3.org/TR/CSS2/visuren.html#float-position

That being said, we could clarify this particular case by answering the following question:

**Does a previously clear-ed float still contribute geometry?**

**Comment by Nadya678** [comment]
This difference is probably triggered by different implementation of `<br/>` in browsers. `clear:both` used on other element doesn't make any problem. `clear:both` added on `<br/>` has the different effect across browsers. 

BTW. What is default stylesheet for `<br/>`? Replaced element? I cannot add border to it.

**Comment by jonjohnjohnson** [comment]
FWIW, depending on when/how the "geometry" of the previously cleared float is changed, chrome will respect or ignore the collision. View this behavior when adding/removing the `width: 50vw`, `margin: auto`, or `margin-bottom: -60px` on it's descendant.

**Comment by Loirooriol** [comment]
If I copy the html and css from https://wptest.center/#/487ld5 and use them in jsfiddle or a local file, then Chrome behaves like Firefox and Edge. Is wptest.center doing something weird?

@Nadya678 I get the same problem when not using `<br>` (in wptest.center).

> What is default stylesheet for `<br/>`?

`<br/>` is rendered using "magic", see #610, [resolution](https://lists.w3.org/Archives/Public/www-style/2017Feb/0062.html), [mail thread](https://www.w3.org/Search/Mail/Public/search?hdr-1-name=subject&hdr-1-query=Explaining+%3Cbr%3E&index-type=t&type-index=www-style).

**Comment by birtles** [comment]
> If I copy the html and css from https://wptest.center/#/487ld5 and use them in jsfiddle or a local file, then Chrome behaves like Firefox and Edge. Is wptest.center doing something weird?

Locally I see that sometimes Chrome puts it on the left but after reloading puts it on the right. Likewise after resizing the wptest.center version a few times I see it ends up on the right. There seems to be some instability there.

**Comment by FremyCompany** [comment]
@birtles I can confirm that resizing the window on wptest.center sometimes yields to the float "moving" to the right. It seems like this is just a Chrome bug then. 

I filed https://bugs.chromium.org/p/chromium/issues/detail?id=811031
