### ISSUE TITLE
Privacy, safety vs. Experimental technologies of Moz and Cr

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2292]
Please ban these experimental technologies: 

> This is an experimental technology
> Check the Browser compatibility table carefully before using this in production.
> 
> Touch.radiusX Read only
>     Returns the X radius of the ellipse that most closely circumscribes the area of contact with the screen. The value is in pixels of the same scale as screenX.
> Touch.radiusY Read only
>     Returns the Y radius of the ellipse that most closely circumscribes the area of contact with the screen. The value is in pixels of the same scale as screenY.
> Touch.rotationAngle Read only
>     Returns the angle (in degrees) that the ellipse described by radiusX and radiusY must be rotated, clockwise, to most accurately cover the area of contact between the user and the surface.
> Touch.forceRead only
>     Returns the amount of pressure being applied to the surface by the user, as a float between 0.0 (no pressure) and 1.0 (maximum pressure). 

And also other that can be used to profilling and deanomimization of users.

**Comment by Loirooriol** [comment]
Are you talking about [Touch Events](https://w3c.github.io/touch-events/)? I think you should complain in https://github.com/w3c/touch-events

**Comment by tabatkins** [comment]
Yup.
