### ISSUE TITLE
[css-align][css-multicol] Gutter properties computed value

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#2294]
These are the links to both specs:
* https://drafts.csswg.org/css-align/#column-row-gap
* https://drafts.csswg.org/css-multicol/#column-gap

In `css-align` it says:
> Computed value: as specified, with &lt;length>s made absolute, and normal computing to zero except on multi-column elements

In `css-multicol` it says:
> Computed value: | as specified, with &lt;length>s made absolute

I'm not sure if this difference is on purpose or not.
I understand that with the current text the computed value of `column-gap: normal` would be:
* `0px` if it's not a multicol container
* `normal` if it's a multicol container

But now that we're generalizing the properties to apply in other layout models (like grid and flexbox), it seems weird that we have a difference there.
Currently `getComputedStyle()` is returning `normal` in all browsers but Edge (where it returns `0px`).

I guess we could change this and we have 2 options:
* We can say that it's the computed value for `normal` is `normal`.
* Or that the computed value for `normal` is the used value.

Note that if the computed style of `normal` is `normal`, then that value won't be animatable. However if it's the used value (`0px` or `1em` in multicol) then it'll be animatable.

[ Edited by @dbaron to fix &lt;production>s that were getting interpreted as HTML tags. ]

**Comment by frivoal** [comment]
It seems to me that an author writing `column-gap: inherit` is not completely crazy. If you have a multicol inside a grid, or a grid inside a multicol, you might want to inherit the gap so that it's the same in both. In that case, you probably want `normal` to resolve to an absolute width, so that both the parent and the child can have the same gap.

Based on that, I suggest that normal should compute to a width always.

Your point about animation goes in the same direction.

This is a technically breaking change for multicol, but I have a very hard time thinking of situations where that would have any negative impact.

**Comment by fantasai** [comment]
If you care that much about your gaps, you're probably specifying their sizes explicitly anyway.

I think it's fine to have 'normal' compute to 'normal'. Also it would be necessary to do this if we adopt https://github.com/w3c/csswg-drafts/issues/2285.

**Comment by frivoal** [comment]
> If you care that much about your gaps, you're probably specifying their sizes explicitly anyway.

Right, probably. But then again, that argument only says why it is not necessary to make the change, not why it's a bad change.

Transitioning from whatever it is right now (which may be normal) to a specified length sounds useful too, and normal not computing to a length gets in the way of that.

> 'normal' computing to 'normal' would be necessary to do this if we adopt #2285.

I don't follow. Why? Normal could mean "get the value of the parent" in subgrid, while still computing a a value (absolutized length if it's a length, or percentage if that's what you get from the parent).

**Comment by MatsPalmgren** [comment]
Having the computed value of one property depend on the computed values of other properties is problematic in general.  In this case, it would depend on the computed values for `column-width`, `column-count`, `display` etc.  Please also note that whether you actually get column boxes or not is decided during box construction and depends on more things than just computed values (it's not supported on most form control elements, etc). If I understand the spec correctly, these computed values would depend on the actual box type (which is decided after all computed values have already been resolved).  While that can be implemented, it requires some ugly hacks and has performance penalties.

I'd prefer to make `normal` compute to `normal`.

**Comment by frivoal** [comment]
ah, yes. I wasn't looking at the full picture, but that made sense.

**Comment by fantasai** [comment]
@MatsPalmgren Since we don't use gaps for block containers that aren't multicol, we could make it just depend on the `display` value. But that doesn't help if we want to try for https://github.com/w3c/csswg-drafts/issues/2285 .
