### ISSUE TITLE
[css-shapes] Why does this spec need to special-case serialization of <position>?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2301]
See https://github.com/w3c/web-platform-tests/pull/9339#issuecomment-362977519.

The spec says:

> The <position> values (including the defaults) in ellipse() and circle() serialize to their 2- and 4-value forms only, preferring the 2-value form when it can be expressed without calc(), preferring left and top origins, and preferring 0% over a zero length.

Firefox right now special-cases that to follow the spec, but I think it'd be more sane and consistent to just use the regular serialization. Is there any reason that sentence was added to the spec?

**Comment by fantasai** [comment]
See related issue in https://github.com/w3c/csswg-drafts/issues/2274  ...

**Comment by ewilligers** [comment]
This has been resolved in
https://github.com/w3c/csswg-drafts/issues/2274#issuecomment-402322967
and the spec should be updated by removing the relevant language from the shapes spec. All `<position>` values serialize the same way.

**Comment by astearns** [comment]
I've removed the wrong text from css-shapes.
