### ISSUE TITLE
[css-ui] [css-color] Tangent on system colors and appearance being both deprecated

### ISSUE THREAD

**Issue by sabithpocker** [w3c/csswg-drafts#2302]
I am quoting from an [outdated document here](https://www.w3.org/TR/2003/CR-css3-color-20030514/#css-system) (_as it is the only place a reason is mentioned for the deprecation of System Colors_)

> The CSS2 System Color values have been deprecated in favor of the CSS3 UI 'appearance' property for specifying the complete look of user interface related elements.

It now _appears_ that `appearance` won't be taking up this responsibility and this quoted line has been removed from later versions of the document. The reason why System Colors was deprecated and if `appearance` will provide an alternative remains vague as of now.

How do we proceed with scenarios where we have to style elements to look as native as possible?

**Comment by svgeesus** [comment]
System colors were introduced from Java, which wanted to make native-looking dialogs matching the then-current windowing systems (Windows 95 and MacOS 7). It was unable to do even that, and the introduction of titlebar gradients in Windows 98 made it clear that chasing platform look would always be an elusive, moving target.
In addition, the security implications of being able to accurately fake native UI were becoming apparent.
`appearance` was an attempt to match native appearance without specifying exactly what that was like. The timeframe there was the appearance of brightly-colored iMacs whose UI theming reflected the case color (there was a `flavor` keyword for that, too). these proposals were too vaguely worded to really be implementable, saw little developer interest and thus were also dropped.

> How do we proceed with scenarios where we have to style elements to look as native as possible?

With great caution and a full understanding of the spoofing risks involved; by deciding exactly what UI on what platform at what point in time you want to emulate; and with the realization that your styling will be fragile and need re-doing every few years.

**Comment by sabithpocker** [comment]
Sounds totally sane. Closing this issue.

**User Agent Colors** that would expose a subset of colors used in **User Agent Style Sheet** is something I am thinking about right now, but I am pretty sure that you guys have gone through this before going for `flavor`.  Such a color-set (_actually just exposing a subset of color set used by UA_) can make a web-page look kind of native in respective User-Agents.
