### ISSUE TITLE
[css-backgrounds] Change canonical serialization for box-shadow

### ISSUE THREAD

**Issue by csnardi** [w3c/csswg-drafts#2305]
[The spec](https://drafts.csswg.org/css-backgrounds/#typedef-shadow) declares the syntax for a shadow in `box-shadow` to be:

    <shadow> = inset? && <length>{2,4} && <color>?

However, Firefox, WebKit, and Chrome all serialize this as `<color>? && <length>{2,4} && inset?`. This matches the serialization for `drop-shadow()` (see https://drafts.fxtf.org/filter-effects/#funcdef-filter-drop-shadow) and `text-shadow` (see https://drafts.csswg.org/css-text-decor-3/#text-shadow-property), which both are declared as `<color>? && <length>{2,3}`.

For consistency, `<shadow>` should be defined as:

    <shadow> = <color>? && <length>{2,4} && inset?

in order for serialization to match 3 out of the 4 major browsers and `text-shadow`/`drop-shadow()`.

**Comment by fantasai** [comment]
Pushed out tentative edits, waiting for WG approval.

**Comment by csnardi** [comment]
@fantasai I created two PRs for tests that should verify this change; they should be linked to this issue.

**Comment by TalbotG** [comment]
@csnardi If you need more tests, you know that I have 15 tests targeting box-shadow in

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-021.xht
...
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/box-shadow-036.xht

**Comment by csnardi** [comment]
@TalbotG Thanks, I didn't know that! I'll take a look at them a little bit later and add in any parsing cases I missed to the first pull request linked above.

**Comment by csnardi** [comment]
@fantasai Friendly reminder if you have some time for reviewing https://github.com/w3c/web-platform-tests/pull/9800 and https://github.com/w3c/web-platform-tests/pull/9519 which should close out this issue.

**Comment by csnardi** [comment]
I think the needs testcase label can be removed now.
