### ISSUE TITLE
[css-text-3] possibly incorrect description of "text-align-last: auto"

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#2308]
From the editors draft at https://drafts.csswg.org/css-text-3/#propdef-text-align-last

> If auto is specified, content on the affected line is aligned per text-align unless text-align is set to justify, in which case it is start-aligned. All other values have the same meanings as in text-align.

In this text, "text-align" should be replaced with "text-align-all". "text-align" is a shortcut property so its value should not be referenced, as it is simply setting other properties. As it is defined now, you wind up in this situation:
```
text-align: left;
text-align-all: right;
text-align-last: auto;
```
the last line will be left-aligned, which is not right. Or even correct. Hopefully I have justified my position?

**Comment by fantasai** [comment]
Fixed, thanks!
