### ISSUE TITLE
[css-ui-4][user-select] user-select:all and contenteditable

### ISSUE THREAD

**Issue by yoichio** [w3c/csswg-drafts#231]
https://drafts.csswg.org/css-ui-4/#propdef-user-select

if we have
`<div contenteditable style="user-select:all;">foobar</div>`,
how focus and caret should work?

Can user put a caret inside the text or not?
If can, shift+arrow still selects all? It may be annoying.

For now, Firefox supports as `-moz-user-select:all` but it behaves very weird: 
user can put a caret only on the head of text and can input characters but can't move caret.

Chrome starts to support `-webkit-user-select:all` in the canary channel but user can't focus because Chrome interprets `user-select:all` as user can't put focus and extent into the element.

**Comment by upsuper** [comment]
It seems to me the current spec is pretty clear that `user-select` should be computed to `contain` if the element is editable, no matter what its specified value is. So for your question, I think the answer is that everything should behave as if there is no `user-select` is specified. Any different behavior sounds like a bug.

**Comment by frivoal** [comment]
Right, @upsuper is correct about what the spec currently says, and I think this is reasonable. Note that you can change what the value of user-select is on descendants of an editable element, but on the editable element itself, it computes to contain.

Also, note that contenteditable=true is underspecified, only loosely interoperable, and browser vendors do **not** have an active plan about achieving it, so while we can say some high level sensible things, I do not expect to be able to fully specify how contenteditable=true and user-select interact and have browser vendors comply. As such, I think we will probably have to leave that interaction somewhat undefined.

**Comment by yoichio** [comment]
Oh, I found.
> The computed value is the specified value, except:
> on editable elements where the computed value is always `contain` regardless of the specified value

Thanks.
