### ISSUE TITLE
[CSS2] How do zero-width floats affect subsequent content

### ISSUE THREAD

**Issue by mstensho** [w3c/csswg-drafts#2312]
https://www.w3.org/TR/CSS22/visuren.html#float-position doesn't seem to mention anything particular about zero-width floats. Should a zero-width margin box be considered to be a margin box at all?

```
<div style="width:100px;">
  <div style="float:right; width:0; height:50px;"></div>
  <div style="overflow:hidden; margin-right:-100px; height:200px; background:green;"></div>
</div>
```

Chrome, Edge and Firefox all show a green square here. The relevant spec wording:

"The border box of a table, a block-level replaced element, or an element in the normal flow that establishes a new block formatting context (such as an element with 'overflow' other than 'visible') must not overlap the margin box of any floats in the same block formatting context [...]"

So a zero width float has no outer/margin box at all?

At the same time, all the browsers mentioned agree that zero-width floats should affect the block position of subsequent floats and blocks affected by clearance:

```
<div style="width:200px; background:green;">
  <div style="float:right; width:0; height:100px;"></div>
  <div style="float:left; clear:right; width:0; height:50px;"></div>
  <div style="float:left; width:0; height:100px;"></div>
  <div style="overflow:hidden; clear:both; height:200px; background:lime;"></div>
</div>
```

Here we get a green square above a lime square.

**Comment by gsnedders** [comment]
Is this essentially the same as #576, just the float-preceding case rather than the float-subsequent case?

**Comment by mstensho** [comment]
I don't think so. Please note that the examples that were meant to be part of the initial comment here were invisible, because I had forgotten a few backticks. Fixed now. The floats in my examples have non-zero height, which is an important detail (which was impossible to deduce from the text alone).

**Comment by gsnedders** [comment]
To be fair, I did look very quickly through all the open CSS2 issues and didn't think about them much. :)

**Comment by Loirooriol** [comment]
As I see it, it's still possible to overlap a float even if it has an area of 0. Along the same lines, #5641 said that boxes with an area of 0 can intersect the viewport.

It's worth noting that there are some browser differences depending on which dimension is 0:

```html
<!DOCTYPE html>
<div style="margin-left:50px; width:100px;">
  <div style="float:left; width:0px; height:50px; outline:solid red"></div>
  <div style="float:right; width:0px; height:50px; outline:solid red;"></div>
  <div style="float:left; clear:both; width:25px; height:0px; outline:solid green"></div>
  <div style="float:right; clear:both; width:25px; height:0px; outline:solid green;"></div>
  <div style="float:left; width:0px; height:50px; outline:solid blue"></div>
  <div style="float:right; width:0px; height:50px; outline:solid blue;"></div>
  <div style="overflow:hidden; width:200px; margin:0 -50px; height:150px; background:cyan;"></div>
</div>
```

| Gecko, WebKit | Blink | Spec |
| - | - | - |
| ![](https://github.com/w3c/csswg-drafts/assets/7477678/e7993bc6-f47f-4ed3-8e0c-6de2748f6772) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/076f7458-cce0-47f2-91cb-707d9628756d) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/42ada657-57d6-4647-9245-b36c989a385c) |

**Comment by Loirooriol** [comment]
Another testcase:

```html
<!DOCTYPE html>
<div style="overflow: hidden; width:50px; border: solid; margin: 10px">
  <div style="float:left; clear:left; width:25px; height:10px; background:magenta"></div>
  <div style="float:left; width:0px; height:25px; outline:solid orange"></div>
  <div style="overflow:hidden; width:40px; height:50px; background:cyan;"></div>
</div>
<div style="overflow: hidden; width:50px; border: solid; margin: 10px">
  <div style="float:left; width:10px; height:25px; background:magenta"></div>
  <div style="float:left; clear:left; width:25px; height:0px; outline:solid orange"></div>
  <div style="overflow:hidden; width:40px; height:50px; background:cyan;"></div>
</div>
```

| Gecko | WebKit | Blink | Servo | Servo+patch |
| - | - | - | - | - |
| ![](https://github.com/w3c/csswg-drafts/assets/7477678/843c3fee-3811-4a40-b29a-4c8756c18c4d) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/cd6fd273-ff92-4579-87df-f3bdf3df888f) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/816292df-f962-4215-b603-d37ad3d6bfe9) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/0d794d61-136c-4519-89f3-168bffa4313a) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/bd352a42-a3a7-4e80-8972-b970b94239af) |

Basically

| | Avoids 0px wide floats | Avoids 0px tall floats |
| - | - | - |
| Gecko | ❌ | ❌ |
| WebKit | Sometimes | ❌ |
| Blink | ❌ | ✅ |
| Servo | ✅ | ❌ |
| Servo+patch | ✅ | ✅ |

I was actually interpreting the spec to mean "Servo+patch", and I have written a patch for Servo to implement that. But then I noticed this in https://drafts.csswg.org/css2/#floats

> A line box is next to a float when there exists a vertical position that satisfies all of these four conditions: (a) at or below the top of the line box, (b) at or above the bottom of the line box, (c) below the top margin edge of the float, and (d) above the bottom margin edge of the float.
> Note: this means that floats with zero outer height or negative outer height do not shorten line boxes. 

Effectively, both Blink and Servo+patch are then wrong here:

```html
<!DOCTYPE html>
<div style="float: left; width: 10px; height: 10px; background: cyan"></div>
<div style="float: left; clear: left; width: 100px; outline: solid magenta"></div>
lorem ipsum
```

| Gecko / WebKit / Servo | Blink / Servo+patch |
| - | - |
| ![](https://github.com/w3c/csswg-drafts/assets/7477678/e58c8123-ecc6-4a9b-97c9-14ec6ecce885) | ![](https://github.com/w3c/csswg-drafts/assets/7477678/4d0a43e2-b6d9-4180-964b-27cf3c749747) |

I'm not convinced it makes sense for independent formatting contexts to avoid 0px tall floats if text shouldn't avoid them.

And then it could be said that 0px wide floats shouldn't be avoided either for consistency?
