### ISSUE TITLE
[css-sizing] typos

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2315]
https://drafts.csswg.org/css-sizing-3/#auto-box-sizes
in the first sentence: s/fromy/from/

https://drafts.csswg.org/css-sizing-3/#fit-content-block-size
in the first sentence: s/finite/definite/
These words have roughly the same meaning in CSS, but "definite" has a normative [definition](https://drafts.csswg.org/css-sizing-3/#definite) and the phrase "If the available space is definite" is used in multiple places [elsewhere](https://drafts.csswg.org/css-sizing-3/#ref-for-available%E2%91%A8) so I think it should be preferred.

https://drafts.csswg.org/css-sizing-3/#box-sizing
> The box-sizing property switches the box model between asssigning finite sizes such as `<length>`s and `<percentage>`s ...

s/asssigning/assigning/
Maybe "finite" should be "definite" here too? If not, then "finite" is probably not the word to use here.

**Comment by GloverDonovan** [comment]
I fixed the typos, but I personally find the third sentence confusing.

> The box-sizing property switches the box model between assigning ... (implied `and <verb>ing`)

The word `between` implies that there are multiple things being talked about, i.e. "between assigning and `<something else>`".

**Comment by fantasai** [comment]
@MatsPalmgren OK, fixed typos and switched the last one to fixed.

@GloverDonovan Yes, you're right. I adjusted the wording, let me know if it still seems off? I've been staring at it a bit too long to know anymore.

**Comment by GloverDonovan** [comment]
Definitely better than before. I don't know enough about the spec to rewrite this sentence, but I'd personally change the last part from "the *content box* and the *border box*" to "the *content box* and *border box* values". What do you think?
