### ISSUE TITLE
[css-align][css-flexbox] Align & Flex specs disagree about fallback behavior for align-content/justify-content: space-between

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#2316]
The flexbox specs and alignment specs both have instructions about the fallback behavior of `justify-content: space-between`, and they contradict each other.

The flexbox spec says it falls back to 'flex-start':
> If...there is only a single flex item on the line, this value is identical to 'flex-start'.
https://drafts.csswg.org/css-flexbox-1/#valdef-justify-content-space-between
https://drafts.csswg.org/css-flexbox-1/#valdef-align-content-space-between

Whereas the align spec says it falls back to 'start':
> The default fallback alignment for this value is 'start'.
https://drafts.csswg.org/css-align/#valdef-align-content-space-between

Note that 'start' and 'flex-start' sound similar but are subtly different in a flexbox context, so the distinction is important.

Could these specs be clarified to be non-contradictory on this point?

(I think the flexbox spec just needs an update.... I guess flexbox doesn't know about 'start' and 'end' keywords and the other "new" things in the css-align spec, so maybe it's tricky to reference those from flexbox. Still: the current text that I quoted above ["this value is identical to 'flex-start'"] is clearly incorrect & problematic, if the align spec is really authoritative on this point.)

**Comment by SelenIT** [comment]
Given that implementations match the Flexbox spec, this looks much like a bug in the Box Alignment spec. IMO, it should have the same wording as for the 'stretch' value:
> The default fallback alignment for this value is flex-start. (For layout modes other than flex layout, flex-start is identical to start.)

**Comment by fantasai** [comment]
Fixed, thank you @dholbert for filing and @SelenIT making sure I caught the note from the `stretch` definition!
