### ISSUE TITLE
[CSS2] Building CSS2

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2317]
@bert-github 

For the css2 staging spec (`/css2`), this builds the spec:

```sh
cd csswg-drafts/css2
make
```

This works just fine on my machine. For the stable version (`/css21`), that should work as well, but there are a few differences in the Makefile, and it doesn't run on my machine.

1) Are the differences in the Makefile intentional / necessary?
2) Can the Makefile from `/css21` be fixed? If it is not broken, can its dependencies be documented?

**Comment by gsnedders** [comment]
This has effectively been fixed, though we should document it better.
