### ISSUE TITLE
[selectors-4] nth-child omits n=0 case

### ISSUE THREAD

**Issue by fergald** [w3c/csswg-drafts#2321]
https://drafts.csswg.org/selectors-4/#the-nth-child-pseudo

"The An+B notation and its interpretation are defined in CSS Syntax 3 §6 The An+B microsyntax; it represents any index i = An + B for any positive integer n."

So e.g. 2n+1 would not match the 1st child.

The link is to

https://drafts.csswg.org/css-syntax-3/#anb-microsyntax

"The An+B notation defines an integer step (A) and offset (B), and represents the An+Bth elements in a list, for every positive integer or zero value of n, with the first element in the list having index 1 (not 0)."

The spec should mention the zero case (and probably also that the list is 1-indexed).

**Comment by Nadya678** [comment]
It is clear. 

>The An+B notation also accepts the **even** and odd keywords, which have the same meaning as **2n** and 2n+1, respectively.

https://drafts.csswg.org/css-syntax-3/#anb-microsyntax

**Comment by fergald** [comment]
The css-syntax-3 doc is correct. The selectors-4 doc is incorrect because, unlike the css-syntax-3 doc, it does not allow n=0 (0 is not a positive integer).

**Comment by Nadya678** [comment]
Thus correct positive -> non-negative. or "the n is greater or equal 0". The new spec must be compatible with current version.

**Comment by tabatkins** [comment]
Yeah, that's a bug in Selectors.
