### ISSUE TITLE
[css-mediaqueries] Include @media 'shape' in the descriptor table?

### ISSUE THREAD

**Issue by Malvoz** [w3c/csswg-drafts#2327]
Should the [`@media` descriptor table](https://drafts.csswg.org/mediaqueries/#media-descriptor-table) include the [`shape`](https://www.w3.org/TR/css-round-display/#shape-media-feature) media feature?

**Comment by tabatkins** [comment]
Nah, that's just the index of things defined in *this* spec (for quick reference, so you don't have to hunt thru the spec), not a global listing of descriptors.

**Comment by Malvoz** [comment]
Thanks, that wasn't clear to me. Still learning to navigate the specs I guess.

**Comment by tabatkins** [comment]
No problem! Questions are cheap to ask and easy to close. ^_^
