### ISSUE TITLE
[css-values] calc() should round when it's used as an <integer>

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#2337]
Right now, calc() carefully tracks whether a numeric expression (no units or %s) is guaranteed to resolve to an integer, or might resolve to a more general number.  This allows it to be used in places like `z-index` safely.

However, it excludes some expressions that would be integral if evaluated - for example, *any* division makes it non-integral, even in an expression like `calc(4 / 2)`.

This restriction also seems somewhat inconsistent with calc()'s treatment of range restrictions - if you specify `width: calc(-1px);`, it's valid (and equivalent to 0px), but if you specify `z-index: calc(4 / 2);`, it's invalid.  It seems like this was accidentally motivated by what can be expressed directly in the grammar (integer vs real) vs what has to be expressed in prose as an additional constraint (range restrictions), but these really shouldn't be treated differently.

In particular, this causes some trouble for TypedOM, which wants to make it so that `CSSUnitValue`s (corresponding to plain numbers and dimensions) get the same protection against being out-of-range that calc() does, but now we've realized that there's no such "should be an integer, is actually a real" protection that we could also apply.

So! I propose that we remove the tracking of `<integer>` vs `<number>` in `calc()` (it's already no longer tracked in the typing algorithms of Typed OM, which will be used in calc(), per WG resolution, when I finally write up the unit-algebra text), and instead say that if a calc() ends up being non-integral when an integer is required, it is automatically rounded to the nearest integer.

(Detail: I provisionally propose we use "toward positive infinity" rounding, same as JS's `Math.round()`. Does CSS already have any rounding we should match instead?)

**Comment by alancutter** [comment]
> I provisionally propose we use "toward positive infinity" rounding, same as JS's Math.round(). Does CSS already have any rounding we should match instead?

This matches integer animation rounding.
https://www.w3.org/TR/css-transitions-1/#animtype-integer

**Comment by Nadya678** [comment]
I think the precision of returned values (for non-integer) should be "unrestricted double" 

According to the draft that defines getBoundingClientRect https://drafts.fxtf.org/geometry-1/#domrect
the precision of height and width should not be less that the defined for compatibility.

**Comment by tabatkins** [comment]
This is about abstract CSS values, not any JS API.

**Comment by FremyCompany** [comment]
Edge already supports that, and rounds down towards 0. 

> https://wptest.center/#/udafb2 (Calc rounding to integers)

I would have a weak preference for not having to change that, but if there are people with strong opinion in favor of rounding up, I could be convinced otherwise.

**Comment by tabatkins** [comment]
The fact that CSS already animates integers by rounding towards positive infinity is, I think, a pretty strong argument for calc() doing the same thing by default.
