### ISSUE TITLE
Create "topic: shadow" label

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#2340]
Would it be possible to create a "topic: shadow" label to be able to track issues such as https://github.com/w3c/csswg-drafts/issues/1995 and others? If you're comfortable giving me edit access I'd be happy to help triaging.

That'd make it easier to track upstreamed work from w3c/components.

cc @tabatkins @TakayoshiKochi

**Comment by tabatkins** [comment]
I just bugged @astearns to give you edit access to the repo.

**Comment by plinss** [comment]
Access granted...
