### ISSUE TITLE
[css-color-4] In color-mod(), allow multiplying by a number instead of percentage

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#2341]
The various [color modifier functions in Colors 4](https://drafts.csswg.org/css-color-4/#modifying-colors) currently only support percentages in multiplicative modifiers. Why not plain numbers? Like:

```
color-mod(purple alpha(*0.5))
/* equal to color-mod(purple alpha(*50%)) */

color-mod(var(--foreground) rgb(*1.7))
/* equal to color-mod(var(--foreground) rgb(*170%)) */
```

**Comment by tabatkins** [comment]
Closing because now moot, since I removed it. ^_^
