### ISSUE TITLE
[css-flex] Min-content sizing currently too smart to be web compatible?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#2353]
Hi css-flexers from all around the world,

I just wanted to report that our attempt to update our flex implementation sizing algorithm to match the spec encountered a few hiccups, but this one seems like the most concerning so far:

> https://wptest.center/#/677dj4 (CSS Flexbox min-content size seems problematic)
> ![image](https://user-images.githubusercontent.com/364405/36609259-1e76af92-1881-11e8-8c6b-1cfb35d9d6e2.png) vs ![image](https://user-images.githubusercontent.com/364405/36609533-fabe1148-1881-11e8-9ab0-b5a93da1f05c.png)

The pattern we are seeing is authors using `<div style="background: url(icon.png); width:32px; height:32px">` in min-content sized/constrained flexboxes, and the icon ends up disappearing because flex-shrink defaults to 1 by default.

I think we should update the specification such that an explicit width acts as a minimum width (even though it could theorically be shrunk).

> In general, the automatic minimum size of a flex item is its specified size if it is defined, or its content size otherwise. However, if the box has an aspect ratio and no specified size, its automatic minimum size is the smaller of its content size and its transferred size. If the box has neither a specified size nor an aspect ratio, its automatic minimum size is the content size.

instead of

> In general, the automatic minimum size of a flex item is the smaller of its content size and its specified size. However, if the box has an aspect ratio and no specified size, its automatic minimum size is the smaller of its content size and its transferred size. If the box has neither a specified size nor an aspect ratio, its automatic minimum size is the content size.

**Comment by FremyCompany** [comment]
cc @fantasai @tabatkins @dholbert

**Comment by FremyCompany** [comment]
Another option is to introduce `flex-shrink-mode: prescriptive | corrective` which defaults to `corrective` (but defaults to `prescriptive` if flex is defined but omitted?), and acts as a toggle for whether the shrink is considered during the min-content-sizing phase or not.

**Comment by dholbert** [comment]
> The pattern we are seeing is authors using <div style="background: url(icon.png); width:32px; height:32px"> in min-content sized/constrained flexboxes

There, the icon (i.e. the div) would only shrink if the flexbox is skinnier than 32px, right?  So, it sounds like the issue is that you're getting is that the "min-content sized/constrained flexbox" is too skinny here.

Does the flex container's min-content sizing algorithm produce something less than 32px in this case?  If so, maybe that's what we should amend?

**Comment by FremyCompany** [comment]
@dholbert that is my proposal indeed. the spec says that you take the minimum of the specified width of the flex item and its content width; since there is no content in the icon div, the content width is 0px and it completely erases the specified width.

**Comment by fantasai** [comment]
Tab and I think @dholbert’s explanation in https://github.com/w3c/csswg-drafts/issues/2353#issuecomment-368155601 makes the most sense as a way to address this, so we've drawn up some edits for it, see https://drafts.csswg.org/css-flexbox-1/#change-2017-flex-min-contribution

@dholbert @FremyCompany Please let us know if this seems like a good way to solve the problem. We'll also be running it past the CSSWG shortly to confirm with them as well.
