### ISSUE TITLE
[web-animations-1] Clarification about "make animation’s start time unresolved"

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#2359]
In several procedures, the Web Animations spec says to "make animation’s start time unresolved". Does this mean that implementations should use the [setting the start time of an animation](https://drafts.csswg.org/web-animations/#setting-the-start-time-of-an-animation) procedure or simply make the stored *startTime* value unresolved?

**Comment by graouts** [comment]
I'm pretty sure the spec means simply to set the stored *startTime* value.

**Comment by birtles** [comment]
Let's add wording up front to call out the difference between setting a value versus running a procedure to update it.
