### ISSUE TITLE
[css-position-3] Blockified absolutely-positioned inline elements

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2369]
Consider the following:

```html
<div>Hello <span style="position: absolute; width: 20px; height: 20px; background: red;"></span>World</div>
```

In all browsers, this is rendered by putting the red square's block-start and inline-start coordinate at the spot in the text where it would have appeared had it been `position: static`.

![screen shot 2018-02-27 at 11 08 27 pm](https://user-images.githubusercontent.com/918903/36774502-307cd2a8-1c13-11e8-81c8-c6f9909e8594.png)

According to [CSS 2.1](https://www.w3.org/TR/CSS2/visuren.html#dis-pos-flo),

> the box is absolutely positioned, the computed value of 'float' is 'none', and display is set according to the table below. The position of the box will be determined by the 'top', 'right', 'bottom' and 'left' properties and the box's containing block.

However, I couldn't find any text about setting the 'top', 'right', 'bottom' or 'left' properties in this situation.

Even worse, [css-position-3](https://drafts.csswg.org/css-position-3/#dis-pos-flo) seems to say this situation shouldn't blockify:

- Rule 1 doesn't apply because `display` isn't `none`.
- Rule 2 doesn't apply because the value of `float` isn't `left` or `right`.
- Rule 3 doesn't apply because `float` is `none`.
- Rule 4 doesn't apply because the element is not the root element.
- Rule 5 says nothing about blockifying.

**Comment by litherum** [comment]
@fantasai or @tabatkins might know what to do.

**Comment by upsuper** [comment]
For CSS 2.1, I believe the behavior is described in [10.3.7 Absolutely positioned, non-replaced elements](https://www.w3.org/TR/CSS2/visudet.html#abs-non-replaced-width) which states that when all of `top`, `right`, `bottom`, and `left` are `auto` (which is their initial value), the element is positioned as if it has `position: static`. So they don't need to be set in this situation unless author specifies something.

**Comment by litherum** [comment]
Cool, thanks for finding that!

We should probably leave this bug open about the css-position-3 part.

**Comment by fantasai** [comment]
We rewrote the spec, I think this is fixed now.

**Comment by fantasai** [comment]
@litherum Would you mind reviewing, and closing out if you think everything's been correctly addressed?
