### ISSUE TITLE
[css-multicol] column-rule-width,column-rule-style should refer to line-style,line-width

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2379]
The current grammar rules are

[border-style](https://drafts.csswg.org/css-backgrounds-3/#propdef-border-style): <[line-style](https://drafts.csswg.org/css-backgrounds-3/#typedef-line-style)>{1,4} 

[border-width](https://drafts.csswg.org/css-backgrounds-3/#propdef-border-width): <[line-width](https://drafts.csswg.org/css-backgrounds-3/#typedef-line-width)>{1,4} 

[column-rule-style](https://www.w3.org/TR/css-multicol-1/#crs): <‘[border-style](https://drafts.csswg.org/css-backgrounds-3/#propdef-border-style)’>

[column-rule-width](https://www.w3.org/TR/css-multicol-1/#crw): <‘[border-width](https://drafts.csswg.org/css-backgrounds-3/#propdef-border-width)’>

These would suggest that column-rule-style is a shorthand for border-style, and column-rule-width is  shorthand for border-width. Further, they suggest that up to 4 values are permitted for column-rule-style and column-rule-width.

I suspect the intended grammar rules are:

[column-rule-style](https://www.w3.org/TR/css-multicol-1/#crs): <[line-style](https://drafts.csswg.org/css-backgrounds-3/#typedef-line-style)>

[column-rule-width](https://www.w3.org/TR/css-multicol-1/#crw): <[line-width](https://drafts.csswg.org/css-backgrounds-3/#typedef-line-width)>

**Comment by tabatkins** [comment]
> These would suggest that column-rule-style is a shorthand for border-style, and column-rule-width is shorthand for border-width.

No it does not.  That grammar form has nothing to do with shorthands, it just says "this property has the same syntax as that property". (Bullet 3 in <https://drafts.csswg.org/css-values/#component-types>.)

> Further, they suggest that up to 4 values are permitted for column-rule-style and column-rule-width.

This is indeed an error, and it confuses me that this error was ever made in the first place.  Your suggested fix is correct.
