### ISSUE TITLE
[css-images-4] Clear conic-gradient() for shipping

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#2383]
Chrome implemented conic-gradient() last year behind a flag and now wants to ship. Some internal teams have expressed interest in using conic-gradient on consumer products, and they would rather see the feature shipped than provide back-doors.

I checked and there are no open issues about conic-gradient here. Chrome's implementation has also been tested a fair bit by authors creating demos and beyond a few rendering quality issues with the GPU backend, there are no outstanding problems.

Spec-wise, conic-gradient has been in some Images draft for five years or so.

I think it makes sense to clear this for shipping, and is certainly better than the alternative. 

Adding this to the agenda so we can discuss this Wednesday.

**Comment by LeaVerou** [comment]
Chrome Intent to Ship: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/ySuNvyaB8jY

**Comment by ewilligers** [comment]
Chrome has shipped. Can this issue be closed or is there more to do?
