### ISSUE TITLE
[css-sizing-3] Ensure import of tests posted to www-style

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2387]
https://lists.w3.org/Archives/Public/www-style/2013Jan/0046.html This thread contains a testcase.
https://lists.w3.org/Archives/Public/www-style/2015Aug/0129.html This is a link to Blink's sizing tests.

CC @foolip

**Comment by foolip** [comment]
Is the idea here to auto-file bugs about test cases posted on www-style?

**Comment by fantasai** [comment]
@foolip No, just to make sure those particular testcases don't get lost; the relevant issue discussions were on www-style, so I needed to make an otherwise-blank issue here in GH to attach the Needs Testcase tag. :)

**Comment by fantasai** [comment]
Filed https://github.com/web-platform-tests/wpt/pull/27909 for Ojan's testcase.
