### ISSUE TITLE
[css-2015][css-2017][css-2018] List features cleared for shipping

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2388]
We have a policy of discouraging shipping implementations for anything which hasn't been cleared by the CSSWG, either by the spec reaching CR or by us resolving on an exception to indicate that we've reviewed it and think it's stable enough. It's easy to see what's in CR, it's harder to find the list of exceptions: we should put them in the snapshot.

Here's a start:

* Flow-relative equivalents of sizing, border, margin, and padding properties
* Transforms, Animations, Transitions
* min-content, max-content keywords for sizing properties
* Box Alignment (through dependency in Grid)

Diff of proposed text (can merge the two lists if preferred):

```
diff --git a/css-2017/Overview.bs b/css-2017/Overview.bs
index ed27757..f1e339d 100644
--- a/css-2017/Overview.bs
+++ b/css-2017/Overview.bs
@@ -497,6 +497,7 @@ Experimentation and Unstable Features</h4>
        In exceptional cases,
        the CSSWG may additionally, by an officially-recorded resolution,
        add pre-CR features to the set that are considered safe to release for broad use.
+       See [[#CR-exceptions]].
 
        Note: Vendors should consult the WG explicitly and not make assumptions on this point,
        as a pre-CR spec that hasn't changed in awhile is usually more out-of-date than stable.
@@ -647,6 +648,36 @@ Preserving the Openness of CSS</h5>
        <a href="http://lists.w3.org/Archives/Public/public-css-testsuite">public-css-testsuite@w3.org</a>
        mailing list.
 
+<h2 id="CR-exceptions">
+Safe to Release pre-CR Exceptions</h2>
+
+       The following features have been explicitly and proactively cleared
+       by the CSS Working Group for broad release
+       prior to the spec reaching Candidate Recommendation:
+       <ul>
+               <li>The flow-relative equivalents of
+               the sizing properties ('width', 'height', etc.),
+               the border properties,
+               the margin and padding properties.
+               See <a href="https://lists.w3.org/Archives/Public/www-style/2015Jul/0040.html">explanation</a>
+               and <a href="https://www.w3.org/TR/css-logical-1/">specification</a>.
+
+               <li>The ''min-content'' and ''max-content'' keywords of the sizing properties.
+               See <a href="https://lists.w3.org/Archives/Public/www-style/2015Aug/0109.html">decision</a>
+               and <a href="https://www.w3.org/TR/css-sizing-3/#sizing-values">specification</a>.
+       </ul>
+
+       The following features have been explicitly and retroactively cleared
+       by the CSS Working Group for broad release
+       prior to the spec reaching Candidate Recommendation:
+       <ul>
+               <li>Everything in
+               <a href="https://www.w3.org/TR/css-animations-1/">CSS Animations Level 1</a>,
+               <a href="https://www.w3.org/TR/css-transitions-1/">CSS Transitions Level 1</a>,
+               and
+               <a href="https://www.w3.org/TR/css-transforms-1/">CSS Transforms Level 1</a>.
+       </ul>
+
```

**Comment by frivoal** [comment]
Looks good to me.

I don't remember off the top of my head if there's anything that should be added to this list, but at least what you listed seems right, and the wording looks clear to me.

**Comment by svgeesus** [comment]
Depending on the discussion at this week's call, `conic-gradient() ` could also be added to that list.
https://github.com/w3c/csswg-drafts/issues/2383

**Comment by SelenIT** [comment]
Maybe the new `display` values, such as `flow-root` (implemented in Gecko and Blink) and `contents` (shipped in Gecko for 3 years, about to be shipped in WebKit and Blink) should also be added to the "stable enough" list?

**Comment by dbaron** [comment]
Some of the new things in selectors4, perhaps?  (Some of them certainly *are* shipping, like [:focus-within](https://caniuse.com/#feat=css-focus-within)... and certainly the selectors that were in the [2004 CR](https://www.w3.org/TR/2004/CR-css3-ui-20040511/) of css3-ui but have been removed from more recent drafts and haven't been in a CR of the draft they currently live in.)

**Comment by dbaron** [comment]
Also, if this is the working group's policy, I think it would also be helpful to have a list of the specs that have at some point in the past been in CR.  We have specs that have been in CR, but that have had very substantial changes since the CR (e.g., ruby and text were last in CR in May 2003; I think some features in them may also have been explicitly cleared to ship).

I also think that if we build a list of things that have been cleared to ship, we should make some attempt to make that list exhaustive.  There are a bunch of those hidden in meeting minutes in various places over the past decade.  And the list of features that are actually shipping is substantially larger than the set of features allowed by the policy as written, and I think much of that was done with the approval of the working group, although perhaps not by the fully formal process laid out [in the snapshot](https://drafts.csswg.org/css-2018/#experimental).  (And, hmmm... that section seems to have a bunch of the text that duplicates what @fantasai proposes at the top of this issue.)

**Comment by Arezohayeman** [comment]
#2388

**Comment by fantasai** [comment]
(@dbaron It's a diff, it's quoting parts of that section. :)

**Comment by ericwilligers** [comment]
The individual transform properties [translate, scale, rotate](https://drafts.csswg.org/css-transforms-2/#individual-transforms) are nearly ready to ship - #2520 needs to be resolved and the tests need to reflect the distinction between 2D and 3D transforms. (Blink might ship [offset-anchor](https://drafts.fxtf.org/motion-1/#offset-anchor-property) at the same time as translate, scale, rotate)

**Comment by dbaron** [comment]
some of the variable fonts features in css-fonts-4 seem to be shipping (were they already cleared to ship somewhere?)

**Comment by svgeesus** [comment]
They are, yes.

**Comment by smfr** [comment]
I have some concerns about this "clear to ship" process. Clearing a feature for shipping doesn't seem to be based on any testing or implementation criteria, so anyone is free to push their pet feature as "clear to ship", bypassing the normal process which is based on spec status. I think we should only used the "clear to ship" exception in exceptional circumstances, and not for things like conic gradient or rotate/translate/scale. Those should be handled via spec acceleration or splitting. When we do use the exception process, there should be testing and implementation criteria.

**Comment by frivoal** [comment]
@smfr I agree with you that this "clear to ship" should be used for exceptions, and that normal cases should be handled via spec acceleration or splitting.

Do you "just" want to us be more careful in the future about how we grant exceptions, or do you want to try and overturn the resolution that granted exceptions for conic gradient or rotate/translate/scale?

---
That does not change the fundamental part of this issue, which is that we list the exceptions we have granted, so I'll move forward with the edits, but if we do overturn these resolutions, I'll update the list accordingly.
