### ISSUE TITLE
[css-module-bikeshed] Add 'Privacy and Security Considerations' section

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#240]
To pass the Bikeshed parsing without warnings there should be a *Privacy and Security Considerations* section added.

This also pushes editors to add that information to their specs.

Sebastian

**Comment by SebastianZ** [comment]
After discussiong PR #241 with @frivoal it came to my mind that maybe the editors wait until their spec. stabalized, i.e. is in CR or PR, to add that section and use the Bikeshed warning as note that they still need to add it. Is that assumption correct?

If not, should an issue be added to the spec. for this as suggested by Florian?

Sebastian

**Comment by tabatkins** [comment]
No, there's no actual reasoning behind leaving it out, besides that it's additional effort and usually low-value for CSS specs.

Marking the contents as an issue is fine.

**Comment by SebastianZ** [comment]
Ok, I've done that in #241.

Sebastian

**Comment by tabatkins** [comment]
danke!

**Comment by SebastianZ** [comment]
Bitte! :smile:
