### ISSUE TITLE
[css-color-3] stray semicolon in darkolivegreen example color

### ISSUE THREAD

**Issue by lurch** [w3c/csswg-drafts#2401]
In the "Extended color keywords" section ( https://www.w3.org/TR/css-color-3/#svg-color ) the second cell in the `darkolivegreen` row of the table has a stray semicolon (which appears to be a typo).

In the view-source:
```html
    <tr>
     <td class=c style="background:darkolivegreen">

     <td class=c style="background:#556b2f"> ;

     <td><dfn id=darkolivegreen>darkolivegreen</dfn>

     <td class=c style="background:silver">#556b2f

     <td class=c style="background:silver">85,107,47
```

This semicolon isn't present for any other colors, e.g.
```html
    <tr>
     <td class=c style="background:darkorange">

     <td class=c style="background:#ff8c00">

     <td><dfn id=darkorange>darkorange</dfn>

     <td class=c style="background:silver">#ff8c00

     <td class=c style="background:silver">255,140,0
```

**Comment by svgeesus** [comment]
Well spotted! Yes, this is an inadvertent typo. I will fix it when the document is republished.

**Comment by svgeesus** [comment]
Fixed in [ED](https://www.w3.org/TR/css-color-3/#svg-color) and [REC](https://www.w3.org/TR/2018/REC-css-color-3-20180619/#svg-color)
