### ISSUE TITLE
[cssom] Consider changing the definition of getComputedStyle when called from a different document to match reality.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2403]
Somewhat related to https://github.com/w3c/csswg-drafts/issues/1548 and https://github.com/w3c/csswg-drafts/issues/1964.

Right now the spec doesn't really match any implementations. Implementations usually return the style of the element styled as the document it's in (Firefox doesn't in some cases, I can try to explain if people are curious).

In any case, for a visible iframe and an element in the document, the behavior of all engines is definitely not the one required by the spec in https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle:

> Note: This means that even if obj is in a different document (e.g. one fetched via XMLHttpRequest) it will still use the style rules associated with the document that is associated with the global object on which getComputedStyle() was invoked to compute the CSS declaration block.

And they just return the style of the element for the document they're in.

cc @lilles @FremyCompany @bzbarsky @dbaron

**Comment by FremyCompany** [comment]
+1 to mandating to return the style based on the document the node is attached to.

For nodes that are not in any document, I'm tempted to say we should specify the behavior of Chrome/Webkit and return an empty string for all properties.

**Comment by lilles** [comment]
+1 for getComputedStyle to return style based on the node's document.

**Comment by emilio** [comment]
Resolution for this lives at #1548.
