### ISSUE TITLE
[css-align][css-grid] Incorrect grid's intrinsic size when applying baseline-alignment

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#2409]
Lets consider the following case:

```
<div style="display: inline-grid; grid: 100px 200px / auto auto; justify-items: baseline">
  <div style="grid-row: 1; grid-column: 1; width: 125px; background: blue"></div>
  <div style="grid-row: 2; grid-column: 1; font: 50px Ahem;  writing-mode: vertical-rl; background: purple">É É ÉÉ</div>
</div>
```
The first item has fixed size, it can participate in baseline alignment along the row/inline-axis. 
The second item, even though it's orthogonal, can participate in baseline alignment align the row/inline-axis, since it doesn't imply a sizing cyclic dependency in such axis (rows are fixed sized).

So, both items can participate in baseline alignment along the row/inline-axis, due to the justify-items property and since they both share the _first column_ as Baseline Alignment Context.

Another point to consider in this example is that the first item is an empty box, hence it should synthesize its baseline using its border-box _under_ edge.  Since we are aligning along the row/inline-axis, this edge is the _left_ edge. 

The second item has vertical-rl writing mode, so we can use its natural baseline because it's parallel to the Baseline Alignment Context (orthogonal to the baseline axis). This natural baseline correspond to the 'left' edge of the first line of text. 

The problem comes from  the fact that the second item is vertical-rl, so it's right aligned. Before performing the layout, such item's container is the grid box, which has indefinite height. Hence, the item's text is laid out in a single line.  

![baseline-bug-2](https://user-images.githubusercontent.com/2230241/37064213-5527b3be-219c-11e8-90e8-4a8c442c34e8.png)

After performing the layout, and the corresponding tracks sizing algorithm, the second item has to break the text in two lines. This changes completely the baseline alignment and differ from the baseline shims used during the intrinsic size computation.

**Comment by javifernandez** [comment]
I can agree that dealing with orthogonal items during intrinsic size computation is complex and that we may have to accept wrong or weird results under such scenarios. However, I raised this issue just because we tried to solve these issues by integrating the Baseline Alignment logic inside the Track Sizing Algorithm.

I have a quite complete implementation now and it works very well in most of the cases; I've got several tests with orthogonal and relative sizes and the statement about avoiding cyclic dependencies helps a lot to simplify these cases (and I think it make much sense). 

So far, this is the only case that seems to behave unexpectedly, but of course this is debatable; it may be one of the cases that we must live with because of how orthogonal items behave during the sizing algorithm. However, Baseline Alignment along the row/inline axis is only possible using orthogonal items, so I think we should analyze this case. It's also worth mentioning that this issue only occurs when using RL writing modes.

**Comment by javifernandez** [comment]
I think this is more an implementation issue, the spec is indeed very clear.  Since we are implementing the baseline algorithm as part of the track sizing algorithm, there are cases where we don't have set yet the grid area size, hence the grid item still uses the grid container to figure put the available size. 

It's kind of a chicken-egg problem; we could extract the info about the grid area's size directly from the style, although the track sizing algorithm was not completed yet. I'll need some time to think about it, but thanks for the feedback.

**Comment by tabatkins** [comment]
Yeah, pulling out the extra data from the style before track sizing is completed is the point here. ^_^ This is *solving* the chicken/egg where the element's size depends on the track's size and vice versa.

**Comment by javifernandez** [comment]
Well, we can just extract the data from the style because we may have Content-Distribution alignment, which may affect the final row area size. Regarding your second statement, the track's size doesn't depend on the item size, so no cyclic dependency in this case.

**Comment by tabatkins** [comment]
In the general case the track size can depend on the item size (if the content requires less space than the max track sizing functions).

**Comment by fantasai** [comment]
Closing this out as invalid since there seems to be nothing to do here, please re-open if something needs fixing. ^_^
