### ISSUE TITLE
[css-display-3] Example of blockification of display property not quite correct 

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#2419]
In example 2 under section 2.7 - the discussion of "blockification" states:

"Absolute positioning or floating an element blockifies the box’s display type. [CSS2]"

Not quite true, otherwise these would be identical
```
<div>Inline <span style="display:inline; position: absolute">absolute</span></div>
<div>Inline <span style="display:block; position: absolute">absolute</span></div>
```
As this is just an example, I would suggest changing the text to "Floating an element blockifies the box’s display type", which is unequivocally true.

**Comment by tabatkins** [comment]
No, abspos absolutely blockifies the display type.  It's just that when calculating the static position (where the abspos sits when you don't specify top/right/etc), you *ignore* 'position' and its effects.
