### ISSUE TITLE
[css-overflow] How does max-lines interact with hidden content?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2421]
```html
<div id="a" style="width: 0; max-lines: 2">
  <div id="b" style="max-lines: 1">Lorem ipsum</div>
  dolor
</div>
```

Due to `#b`'s `max-lines: 1`, only `Lorem` is displayed and `ipsum` is discarded.

But `#a` has `max-lines: 2`. Does `ipsum` still count as one line, and thus `dolor` is discarded?

**Comment by Loirooriol** [comment]
> We would get the wrong number of lines from the users's point of view.

Yes, but this objective is hard to generalize. What if I use `max-height: 1lh; overflow: clip` instead of `max-lines: 1`? Visually it would be the same, but now both lines would be counted...

**Comment by frivoal** [comment]
The "what about lines in overflow:clip` part question solves itself if:
* we decide in #1971 that `overflow:clip` creates a BFC, and
* we decide in ##2429 that max-lines skips counting lines in descendant BFCs.

I am not expressing either being for or against either of these, but they're dependencies, so we should look into this issue after we look into these.

**Comment by frivoal** [comment]
Given that we've resolved #2429 to make `max-lines` skip counting lines in descedant BGCs, but #1971 to say that `overflow:clip` does not create a BFC, the question remains open for `overflow:clip`.

I don't think there's any technical reason to make `max-lines` skip the descendants of `overflow:clip`, so we could close this as no change. On the other hand, maybe it is counter intuitive that we'd be counting invisible lines.

**Comment by heycam** [comment]
I agree that `overflow: clip` shouldn't affect whether a line is counted for `max-lines`.  `overflow: clip` to me is mostly a visual effect (and I think the name "clip" suggests that too).  You can also have lines partially visible when using `overflow: clip`, another indication that it is working visually rather than fragmenting away content that is overflowing.

**Comment by frivoal** [comment]
Right. We should close this as no change.

**Comment by Loirooriol** [comment]
So `max-lines: 1` moves the second line to another region and it's not counted, and `max-height: 1lh; overflow: clip` counts it?

Some clarification would be useful, maybe a note or example.

**Comment by anjia** [comment]
Yeah, I agree there is no change.

`max-lines:1` makes `ipsum` discarded, because `max-lines` does the layout.
`max-height: 1lh; overflow: clip` makes `ipsum` counted, because `max-height` does the layout and `overflow` just does a visual effect.
