### ISSUE TITLE
[css-grid][cssom] Disallow repeat() syntax in grid-template-rows/columns resolved values

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2427]
https://drafts.csswg.org/css-grid/#resolved-track-list
> A contiguous run of two or more tracks that have the same size and associated line names may be serialized with the repeat() notation. 

I tend to think that the above sentence should be removed from the spec and that the resolved values should always use the expanded form, i.e one value per track.  UAs are currently returning incompatible values: Edge use `repeat()` syntax and other UAs don't.  It's a burden for script to have to deal with two formats.  I think one-value-per-track is far easier to work with so I propose we settle on that as the mandatory format.

**Comment by mrego** [comment]
Yes, I agree it'd be nice to just have one option here, and avoiding `repeat()` seems the simplest one.
This will also help to simplify some of the WPT tests, as they need to check both options right now.

I created a very simple example to show the issue: https://wptest.center/#/nsrrq1
I guess we need @atanassov feedback about this, if Microsoft people are fine I guess the rest won't have any concern.

**Comment by FremyCompany** [comment]
If Edge is actually the only browser using `repeat` then I guess it's only a matter of time before we get a compat case involving that. My initial reaction would be converge on the behavior of the majority in this case. I didn't think this through though, just a quick opinion.

**Comment by atanassov** [comment]
I'm not sure I quite agree with the argument here. Dealing with repeating syntax isn't new - see repeating gradients as an example. Expanding to a variable list that happened to fit a given content (in the case of auto placement) will give authors more trouble for parsing that if they deal with the short form. 

My preference would be for keeping the current text and open bugs for other impls to catch up.

**Comment by javifernandez** [comment]
Hi,

On 29/03/18 22:09, fantasai wrote:
> We /can/ have |getComputedStyle| use |repeat()| syntax according to
> some set of collapsing rules, but we /can't/ make it mirror the
> structure of the specified style. Keeping in mind that we are
> serializing the /used value/ here, the options here are:
>
>   * Don't use |repeat()| in serialization. Easy, not nice for scaling
>     up to giant grids.
>   * Use |repeat()| in serialization to collapse any sequence of
>     identically-sized columns. Simplest option.
>   * Use |repeat()| in serialization to collapse any sequence of
>     identically-sized columns only if they happen to be sourced from
>     the same specified |repeat()|. NOTE: A specified |repeat()| can be
>     split into a sequence of multiple serialized |repeat()|s and/or
>     externally-listed sizes if the repeated track list contains sizes
>     that are not |<length-percentage>|. E.g. |20px repeat(6, auto)|
>     can serialize out as |20px repeat(2, 20px) 35px repeat(3, 19px)|
>     if that is what the track sizes end up as.
>   * Some other option which is less aggressive than the previous, e.g.
>     only collapse columns if they're in a |repeat()| that only
>     contains |<length-percentage>| track listings.
>
>


I think the last option is feasible, form the implementation point of
view, and I think it address the main purpose of serializing computed
values using the repeat notation. Limiting it to same-equal tracks seems
useless to me, I'd rather avoid using repeat notation at all for
serialization. The third option seems too much complex to me.

**Comment by mrego** [comment]
> * Don't use `repeat()` in serialization. Easy, not nice for scaling up to giant grids.
> * Use `repeat()` in serialization to collapse any sequence of identically-sized columns. Simplest option for using `repeat()`.

I'd go for either one of these 2 options, I don't see the benefit of doing something more complex than that.

**Comment by FremyCompany** [comment]
I would just note that in addition to the size difference, you also have to take care of the line names being the same for the duration of the repetition. Still siding on the don't use repeat side, because 3 browsers are already doing that.

**Comment by mrego** [comment]
@atanassov please confirm you're fine with this as I'd like to update the tests accordingly.
