### ISSUE TITLE
[css-overflow] Which descendants are skipped in max-lines?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2429]
[`max-lines`](https://drafts.csswg.org/css-overflow-3/#max-lines) is defined with

> A region break is forced after its Nth descendant in-flow line box, where N is the specified value of max-lines. The contents of descendants that are scroll containers or that are not block containers are skipped over while counting line boxes.

But I'm not sure if that's enough:

 - Lines inside table captions

   Despite @FremyCompany's complaints, the table wrapper box establishes a BFC and thus is technically a block container. That's not really the case on most browsers, though. Table captions are also block containers, so their lines are not skipped. Is this expected? Not sure.

 - Lines inside inline-blocks

   As said in #2408 they are block containers but should be skipped

 - Ruby

   I don't know much about ruby but I guess ruby annotations should probably be skipped. Less sure about ruby bases.

 - `overflow: clip`

   This is not a scroll container but visually is identical to `overflow: hidden`, whose lines are skipped because it's a scroll container.

 - Out of flow

   The spec mentions "in-flow line box". But only things with `float` or `position` can be out-of-flow. Line boxes live in the fragment tree and don't own `float` not `position` properties, so I think they will always be in-flow (but possibly inside an out-of-flow container).

   Either properly define what "in-flow" and "out-of-flow" means for line boxes or skip the contents of out-of-flow descendant boxes. 

 - Other BFC roots

   I'm not convinced `max-lines` should work across formatting context boundaries, even if it's only a BFC.

**Comment by fantasai** [comment]
- We should clarify that the table wrapper box is skipped.
- Neither line boxes nor out-of-flows are introspected. I would have thought this was obvious, but we can add a clarification to this effect.
- `overflow: clip` is covered in #2421 due to your comment there.
- working across formating context boundaries is covered in #2408 afaict.
Removing from agenda; first two issues are bugfix/editorial.

**Comment by Loirooriol** [comment]
> working across formating context boundaries is covered in #2408 afaict.

That issue covers FFC and GFC but not BFC boundaries. You can use `display: flow-root`, `contain`, etc. to have an inflow block box that is not a scroll container but establishes a BFC. Should line boxes inside it be skipped?

**Comment by fantasai** [comment]
Sure it does, they're discussed in multiple comments in that issue.

**Comment by frivoal** [comment]
it was, but the original issue was about something else, and the conclusion did not cover that question, so it is relevant to discuss here.

Personally, I don't have a particularly strong opinion, but here is the rationale: (copying a comment from another thread):

> @fantasai and I considered that possibility, but we thought it was better not to skip:
> * We did not think it would make a big difference in implementation complexity
> * Counting lines in nested BFCs doesn't seem to introduce strange corner cases
> * The various reasons block container get BFCfied did not seem to be particularly relevant to the issue of counting lines, do we expect authors will prefer it this way
> * Authors can always turn their BFCs into some other kind of formatting contexts if they want to exclude them (e.g. a single item vertical flexbox)
>

**Comment by Loirooriol** [comment]
Exactly. And CSS Display says

> Exclusions are able to affect content across formatting context boundaries. (At time of writing, they are the only layout feature that can.)

If `max-lines` starts hiding contents across formatting context boundaries, the quote should be updated. But breaking this invariant doesn't seem nice.
