### ISSUE TITLE
[css-conditional] More DRY with different types of conditionals have same contents?

### ISSUE THREAD

**Issue by jonjohnjohnson** [w3c/csswg-drafts#2437]
https://drafts.csswg.org/css-conditional-3/

I don't have any proposal, but I often have to duplicate huge blocks of css when progressively enhancing my applications...

```css
@supports (position:sticky) {
[a bunch of styles]
}

@media (min-height: 30em) {
[same bunch of styles]
}
```

Not saying it's a straight forward thing to combine different types of conditionals with a `,` or to possibly add @support stuffs into the custom media queries of [media queries level 5](https://drafts.csswg.org/mediaqueries-5/), but I'd love to cut out a lot of the duplicate css from this type of situation.

**Comment by tabatkins** [comment]
Yup, already tracked in the [@when/@else proposal](https://github.com/w3c/csswg-drafts/issues/112) ^_^

**Comment by jonjohnjohnson** [comment]
@tabatkins Rats! Shoulda searched more diligently through the issues and of course checked your private trove of specs!
