### ISSUE TITLE
[css-transforms-2] individual transform properties should have default value of 'none'.

### ISSUE THREAD

**Issue by shans** [w3c/csswg-drafts#244]
.. and non-none values should establish a stacking context & containing block for consistency with transforms 1.

Spec link: https://drafts.csswg.org/css-transforms-2/#individual-transforms

**Comment by shans** [comment]
email from Matt Rakow: 

"Hi all,

Any non-"none" value for the transform property causes the element to establish a stacking context and containing block.  The individual transform properties are not currently specified as establishing either of these; should they (I think yes)?

If yes, when?  Do these properties also need a "none" value as the default?

Thanks,
-Matt"

**Comment by shans** [comment]
Having a default 'none' (and every other value establishing a stacking context) is probably best so that animations that sweep through the zeroes (translate: 0px, rotate: 0deg, and scale: 1) don't pop in and out of stacking context/containing block.

**Comment by ChumpChief** [comment]
I support the addition of a "none" value as the default for each of these properties.  More discussion at:
http://lists.w3.org/Archives/Public/www-style/2016Jun/0170.html
http://lists.w3.org/Archives/Public/www-style/2016Jun/0171.html
