### ISSUE TITLE
[css-font-loading] Typo in the IDL of FontFaceSource

### ISSUE THREAD

**Issue by fred-wang** [w3c/csswg-drafts#2441]
See https://drafts.csswg.org/css-font-loading/#font-face-source:

      [Exposed=(Window,Worker)
       NoInterfaceObject]
      interface FontFaceSource {
        readonly attribute FontFaceSet fonts;
      };

The two extended attributes should be separated by a comma.

cc @heycam

**Comment by mrego** [comment]
So this seems just a typo, @fred-wang was trying to fork this repo and provide a PR but it seems the GitHub fork is failing for him.

@tabatkins maybe you can just fix this yourself.

**Comment by tabatkins** [comment]
Looks like someone already got to it, but didn't tag the issue. ^_^

**Comment by fred-wang** [comment]
Ok it was 922a43a3d9e1170b17b11699dd565465ce67432a ; thanks.
