### ISSUE TITLE
[css-color][css-color-3] Needs header link to Editor’s Draft

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#2445]
As is common convention in our modern specs, the header section needs a link to the [CSS Color Level 3 Editor's draft](https://drafts.csswg.org/css-color-3/) (however that draft itself needs regenerating, it says "Editor's Draft 7 July 2014" currently).

We need to update the [Editor's draft source](https://github.com/w3c/csswg-drafts/blob/master/css-color-3/Overview.src.html) with a link to the [viewable Editor's Draft](https://drafts.csswg.org/css-color-3/), and then regenerate the [Editor's draft Overview.html](https://github.com/w3c/csswg-drafts/blob/master/css-color-3/Overview.html).

Labels: css-color-3, Needs Edits

(Originally published at: http://tantek.com/2018/074/b2/css-color-3-needs-link-editor-draft)

**Comment by dbaron** [comment]
If I hadn't already submitted the comments, I would have referenced this issue from [Mozilla's comments on the css-color-3 PR](https://lists.w3.org/Archives/Public/public-new-work/2018Mar/0007.html).

**Comment by svgeesus** [comment]
> As is common convention in our modern specs, the header section needs a link to the CSS Color Level 3 Editor's draft (however that draft itself needs regenerating, it says "Editor's Draft 7 July 2014" currently).

CSS Color 3 is unfortunately one of the few specs using the old CSS preprocessor that Bert wrote, and which is no longer maintained. That means that regenerating the draft from the `.src` means running that preprocessor, then fixing up all the things it gets wrong (lots of boilerplate errors, wrong process document link, generates HTML 4.01, several references are incorrect or not in the old, unmaintained references database it uses, etc).

I agree that the build version of the spec needs to be updated, and i will do that.
