### ISSUE TITLE
[css-text] All IN characters?

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#2447]
https://drafts.csswg.org/css-text-3/#line-break-property

> • breaks between inseparable characters such as ‥ U+2025, … U+2026 i.e.
characters with the Unicode Line Break property IN. (See LineBreak.txt
in [UNICODE].)

The quoted text above is slightly ambiguous. I took it to mean that this rule "applies to all characters with the Unicode Line Break property IN, such as ‥ U+2025, and … U+2026"

The other possible meaning, given the order in the spec, is that this rule applies to characters such as ‥ U+2025, … U+2026 *and those two are* characters with the Unicode Line Break property IN

I suggest (if i understood correctly) rewording to say:

> • breaks between characters with the Unicode Line Break property IN, i.e. inseparable characters such as ‥ U+2025, and … U+2026. (See LineBreak.txt in [UNICODE].)

**Comment by fantasai** [comment]
Added parentheses to disambiguate the sentence parsing. :) Lmk if this is acceptable~

**Comment by r12a** [comment]
Ok, thanks. You can close this.  (Should i close it, or do you prefer to do it?)

**Comment by frivoal** [comment]
> (Should i close it, or do you prefer to do it?)

Either way works, but it's done now :)
