### ISSUE TITLE
[css-variables-1] Please clarify in the Intro about custom properties *cascading*

### ISSUE THREAD

**Issue by Tyler-H** [w3c/csswg-drafts#2451]
The CSS Variables spec Intro [concludes](https://www.w3.org/TR/css-variables-1/#intro) by saying 

>  and the change will propagate to all uses of that variable automatically.

But this isn't quite true. It will only propagate to all *cascaded* uses of that variable automatically, no? If that's correct, it would be useful to help clear up some confusion with authors thinking a CSS variable can be used in elements that do not cascade from the element where the custom property was declared. 

If correct, I suggest simply adding in the word *cascaded* there:

> and the changes will propagate to all cascaded uses of that variable automatically.

**Comment by tabatkins** [comment]
I don't think this is unclear in the intro, and the correction doesn't help (and possibly makes it worse) - it suggests that there are *non-*cascaded uses of a variable.

The cascade is intrinsic to the "use" of a variable here; using a `var(--foo)` on an element without a connection to any `--foo` property is the same as using a JS variable in one function that's only defined in an unrelated function.
