### ISSUE TITLE
[css-grid] Intrinsic size of grid container should include the gutters

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#246]
5.2. Sizing Grid Containers:
"The max-content size of a grid container is the sum of the grid container’s track sizes in the appropriate axis, when the grid is sized under a max-content constraint.

The min-content size of a grid container is the sum of the grid container’s track sizes in the appropriate axis, when the grid is sized under a min-content constraint."
https://drafts.csswg.org/css-grid/#intrinsic-sizes

I think both min-/max-content size should include the gutters in the relevant axis.
Perhaps this is implicit from "each gutter is essentially treated as an extra track of the specified length" in 11.1, but I think it would be clearer to mention them explicitly in 5.2.

**Comment by mrego** [comment]
Yeah I agree it would be nice to clarify it.

BTW, this was already commented in issue #163 but @tabatkins closed it without changing the wording in the spec.

**Comment by tabatkins** [comment]
Right, in #163 I commented 

> Grid specifically defines that gutters are treated as tracks for the purposes of sizing

And in Grid, in the `grid-*-gap` section, it says

> For the purpose of track sizing, each gutter is essentially treated as an extra track of the specified length.

**Comment by svillar** [comment]
FWIW we've been always doing this
