### ISSUE TITLE
[cssom] Bikeshed build broken by "Use Web IDL's new-ish interface mixins concept"

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#2460]
https://drafts.csswg.org/cssom/ hasn't been updated after https://github.com/w3c/csswg-drafts/pull/2123 and https://drafts.csswg.org/bikeshed/cssom/ says:
```
FATAL ERROR: Line doesn't match the grammar `k:v; k:v; k:v`:
ProcessingInstruction includes LinkStyle;
Traceback (most recent call last):
  File "/sites/api.csswg.org/bikeshed/bikeshed.py", line 5, in 
    bikeshed.main()
  File "/sites/api.csswg.org/bikeshed/bikeshed/cli.py", line 202, in main
    doc.preprocess()
  File "/sites/api.csswg.org/bikeshed/bikeshed/Spec.py", line 125, in preprocess
    self.lines = datablocks.transformDataBlocks(self, self.lines)
  File "/sites/api.csswg.org/bikeshed/bikeshed/datablocks.py", line 81, in transformDataBlocks
    doc=doc)
  File "/sites/api.csswg.org/bikeshed/bikeshed/datablocks.py", line 644, in transformInclude
    el = "
Please correct the error and update the source file.

Last Bikeshed run at 2018-03-20 15:26:10 PDT
```

I've also filed https://github.com/tabatkins/bikeshed/issues/1207

**Comment by foolip** [comment]
@romandev @tabatkins

**Comment by foolip** [comment]
Beyond fixing this, I wonder if Travis can be set up to try to build PRs and fail for cases like this?

**Comment by tabatkins** [comment]
Any actual python errors bubbling up are serious bugs on Bikeshed's part; we *should* fall over noisily here so I see it and fix it.

**Comment by tabatkins** [comment]
In this case, the bug is that Bikeshed is incorrectly classifying this as an include-block, because the line (a) starts with `<pre`, and (b) includes the substring "include". :(

<https://github.com/tabatkins/bikeshed/issues/1207> is tracking this now.

**Comment by tabatkins** [comment]
All fixed now!
