### ISSUE TITLE
[css-ui-4] outline-style values are not the same as border-style

### ISSUE THREAD

**Issue by impressivewebs** [w3c/csswg-drafts#2466]
In the section on `outline-style`:

https://drafts.csswg.org/css-ui-3/#outline-style

Next to "Value" it says:

    auto | <border-style>

The term `<border-style>` then links to this page:

https://drafts.csswg.org/css21/box.html#propdef-border-style

Which lists the valid `border-style` values from CSS2 here:

https://drafts.csswg.org/css21/box.html#value-def-border-style

The values listed there include the value `hidden`. But the `hidden` value is not valid for the `outline-style` property (all the others are fine). So, I believe the primary document should be updated to either point to a different listing of the values that excludes `hidden`, or else the values for `outline-style` should be listed on that original page (which would seem to make more sense).

**Comment by frivoal** [comment]
Good point. The text after the property declaration defines it, so in the end the spec does say the right thing, but I agree it is not a good way of putting it.

**Comment by frivoal** [comment]
Fixed in css-ui-4: https://github.com/w3c/csswg-drafts/commit/75b3756f1c833fbef7fa7afdf401d7dec887b683

@svgeesus : I believe this is a purely editorial fix that can be added to level 3 as well without disturbing the PR->REC transition. Do you agree? If so, I'll make the fix. Otherwise, I think we'll just have to live with old specs having worse wording than the newest ones.

**Comment by Loirooriol** [comment]
@frivoal I think `<outline-style> := auto | <outline-style>` is a circular definition which makes no sense. If you don't want to list all possible values in the definition table, say something like "See prose".

**Comment by frivoal** [comment]
@Loirooriol different types: on the left side, it's a property (bikeshed syntax `'outline-style'`), on the right side it's a production (bikeshed syntax `<<outline-style>>`), defined further in the text. But ok, using the same word for both may be resolved without ambiguity by software, it's still super confusing, sorry. Fixing that.

**Comment by Loirooriol** [comment]
Ah, right, the definition was `<'outline-style'> := auto | <outline-style>`. Well, now it's more clear, thanks!

**Comment by frivoal** [comment]
@svgeesus ping:
> I believe this is a purely editorial fix that can be added to level 3 as well without disturbing the PR->REC transition. Do you agree? If so, I'll make the fix. Otherwise, I think we'll just have to live with old specs having worse wording than the newest ones.

**Comment by frivoal** [comment]
@atanassov @astearns CSS-UI-3 is now REC. is fixing this in level 4 enough (in which case we can close)?
