### ISSUE TITLE
[web-animations-1] Clarification needed on parsing/handling iteration duration

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/csswg-drafts#2471]
The spec needs to clarify better how the iteration duration (https://drafts.csswg.org/web-animations-1/#iteration-duration) is parsed and how it is handled. I think there are two main sub-issues here:

  i. A step should be added (or step 3 should be amended) in https://drafts.csswg.org/web-animations-1/#update-the-timing-properties-of-an-animation-effect to also throw if 'duration' is a string but not the value 'auto'.

  ii. We need some wording around handling an 'auto' iteration duration. We could copy the style of 'fill' in the EffectTiming interface - https://drafts.csswg.org/web-animations-1/#dom-effecttiming-fill - but that may still be a little unclear since iteration duration is still clearly defined (and used) as a number in the rest of the spec, and step 5 of https://drafts.csswg.org/web-animations-1/#update-the-timing-properties-of-an-animation-effect heavily implies you would convert 'auto' there.

From IRC:

10:41 AM <smcgruer> birtles: Are values other than 'auto' valid for the iteration duration value? If not, should step 3 of https://drafts.csswg.org/web-animations-1/#update-the-timing-properties-of-an-animation-effect specify also that we should check whether the value is 'auto' and bail if it's not?
10:42 AM <smcgruer> I'm also not clear from the spec when 'auto' should be parsed, I assume it's implicit in the "duration → iteration duration" step since most of the spec treats 'iteration duration' as a number
10:43 AM <smcgruer> Oh wait, but getTiming() has to return 'auto' so I guess it has to live
6:29 PM <birtles> smcgruer: Yeah, that could definitely be more clear. I think it might come down to this sentence, "In this level of this specification, the string value auto is equivalent to zero." But "equivalent" is way too under-specified.
6:29 PM <birtles> Yeah, 'auto' needs to be preserved.
6:30 PM <birtles> This is actually more clear in level 2 which has the "intrinsic iteration duration" concept.
6:30 PM <birtles> Something got lost when I split the levels out.
6:31 PM <birtles> It has, "The string value auto is used to indicate that the iteration duration reflects the animation effect’s intrinsic iteration duration."
6:31 PM <birtles> And then it has various definitions for the intrinsic iteration duration.
6:31 PM <birtles> Do you mind filing an issue?

**Comment by birtles** [comment]
> 10:41 AM birtles: Are values other than 'auto' valid for the iteration duration value? If not, should step 3 of https://drafts.csswg.org/web-animations-1/#update-the-timing-properties-of-an-animation-effect specify also that we should check whether the value is 'auto' and bail if it's not?
> 10:42 AM I'm also not clear from the spec when 'auto' should be parsed, I assume it's implicit in the "duration → iteration duration" step since most of the spec treats 'iteration duration' as a number
> 10:43 AM Oh wait, but getTiming() has to return 'auto' so I guess it has to live
> 6:29 PM smcgruer: Yeah, that could definitely be more clear. I think it might come down to this sentence, "In this level of this specification, the string value auto is equivalent to zero." But "equivalent" is way too under-specified.
> 6:29 PM Yeah, 'auto' needs to be preserved.
> 6:30 PM This is actually more clear in level 2 which has the "intrinsic iteration duration" concept.
> 6:30 PM Something got lost when I split the levels out.
> 6:31 PM It has, "The string value auto is used to indicate that the iteration duration reflects the animation effect’s intrinsic iteration duration."
> 6:31 PM And then it has various definitions for the intrinsic iteration duration.
> 6:31 PM Do you mind filing an issue?

I'm pretty sure the birtles/smcgruer in that log have been switched.
