### ISSUE TITLE
Is it possible to have an "Edit on GitHub" or "Propose A Change" link to specs that points to a .bs file?

### ISSUE THREAD

**Issue by praveenpuglia** [w3c/csswg-drafts#2472]
Wondering if it's possible to add a link to the `.bs` file that generates the Spec in the spec itself. This will help in quickly editing sentences and send PRs.

**Comment by fantasai** [comment]
We need to wrap up https://github.com/w3c/csswg-drafts/pull/2320 but should be doable.

**Comment by tabatkins** [comment]
Already done, actually, I'd just accidentally only put it in the non-ED defaults. Fixed now: https://github.com/tabatkins/bikeshed/commit/96e00f859430c6bacc739269225efc27ed4bce92
