### ISSUE TITLE
[css-fonts-4] §7.2 Feature and variation precedence ignores `font-variant` descriptor

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2478]
See https://drafts.csswg.org/css-fonts-4/#feature-variation-precedence

In CSS Fonts 3, features implied by the `font-variant` descriptor are incorporated at step 2 of the Feature Precedence rules: https://www.w3.org/TR/css-fonts-3/#feature-precedence.

However, in the current draft of Fonts 4, the corresponding section (now Feature and variation precedence) omits any mention of the `font-variant` descriptor (although it still accounts for the `font-variant` property).

Presumably, if the `font-variant` descriptor is intended to work as in Fonts 3, it should be handled in a new step inserted between rules 5 and 6 in the current text.

**Comment by svgeesus** [comment]
Agreed; analogy with Fonts 3, where the descriptor is step 2, before step 3 about `font-feature-settings descriptor` descriptor, then in Fonts 4 that should be between steps 5 and 6.

@litherum I'm assuming this omission is an error, rather than being a deliberate removal?

**Comment by svgeesus** [comment]
I notice this is changed already, Step 10 says

> Font features implied by the value of the font-variant property, the related font-variant subproperties and any other CSS property that uses OpenType features (e.g. the font-kerning property) are applied.
