### ISSUE TITLE
[mediaqueries] behavior of `any-pointer: none`

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#248]
In [the section of `pointer`](https://drafts.csswg.org/mediaqueries/#pointer), the spec says `none` is matched if
> The primary input mechanism of the device does not include a pointing device.

In [the section of `any-pointer` and `any-hover`](https://drafts.csswg.org/mediaqueries/#any-input), the spec says:
> The any-pointer and any-hover media features are identical to the pointer and hover media features, but they correspond to the union of capabilities of all the pointing devices available to the user.

It is unclear to me in what case should `any-pointer: none` match? Should it match only if the device has completely no pointing device, or always match because device should always have some non-pointing input mechanism?

**Comment by fantasai** [comment]
It should only match if the device has completely no pointing device.

**Comment by tabatkins** [comment]
Every pointing device is either "coarse" or "fine".  The only way you can match "none" is if there aren't any to union, like fantasai says. I can clarify that a bit, tho.
