### ISSUE TITLE
[cssom] "partial interface CSSStyleDeclaration {   [CERe..."

### ISSUE THREAD

**Issue by lukebjerring** [w3c/csswg-drafts#2486]
The following snippets are not specification IDL, but example output, so should be flagged as `note` (or `example`) to be ignored by IDL scrapers.

https://drafts.csswg.org/cssom/#example-5b8953f5

> partial interface CSSStyleDeclaration \{
>   \[CEReactions\] attribute \[TreatNullAs=​EmptyString\] CSSOMString \_camel\_cased\_attribute;
> \};

> partial interface CSSStyleDeclaration {
>   [CEReactions] attribute [TreatNullAs=EmptyString] CSSOMString _webkit_cased_attribute;
> };

> partial interface CSSStyleDeclaration {
>   [CEReactions] attribute [TreatNullAs=EmptyString] CSSOMString _dashed_attribute;
> };

**Comment by zcorpan** [comment]
They are normative, and are more templates than example output.

These have `class="idl extract"`, so IDL scraper can ignore them.

That said, I don't mind changing things here. :-)

**Comment by emilio** [comment]
Err, yes, sorry @zcorpan. I had this in my local tree it seems, and forgot that I had submitted it separately as #2865.

Thanks for the heads up, will revert for now.

**Comment by zcorpan** [comment]
Closing per https://github.com/w3c/csswg-drafts/pull/2865#issuecomment-897958516
