### ISSUE TITLE
CSS Grid properties, Not working on IE11.

### ISSUE THREAD

**Issue by adsingh14** [w3c/csswg-drafts#2489]
Hi !
Is there any way to run CSS Grid properties on IE11?

> I've been tested that code on IE11 yet which doesn't compatible even I used `-ms-` as prefix.

**Code**: https://codepen.io/adsingh14/pen/YaVyjO

_Running on IE11(on Win 7) :-_
![image](https://user-images.githubusercontent.com/35252877/38151226-0c3e85c8-3480-11e8-989e-f9dd2cb2ca7f.png)

**Comment by svgeesus** [comment]
This isn't a general CSS support forum. This GitHub repo is for development of the CSS specifications.

(The example you posted works fine in Edge 17, by the way)

**Comment by jonjohnjohnson** [comment]
@adsingh14 As [https://caniuse.com/#search=grid](https://caniuse.com/#search=grid) shows, ie11 uses an older version of the spec. Through that link, you should be able to find the relevant information to alter your code by hand with fallbacks. But, I'd recommend using [autoprefixer](https://github.com/postcss/autoprefixer), which you can also enable in the css settings of your codepen to see if that suits you.

**Comment by adsingh14** [comment]
**[ISSUE RESOLVED]**
