### ISSUE TITLE
[css-ui] Spec input-security property

### ISSUE THREAD

**Issue by hober** [w3c/csswg-drafts#2495]
An increasing number of sites have switched their login forms from using `<input type=password>` to `<input type=text>` for password input, in order to provide the ability to toggle display of the password text. This has the unfortunate side effect of preventing client-side password/account managers from correctly filling the form. We should spec the ability to toggle display of the contents of `<input type=password>` to help sites avoid breaking such account managers.

WebKit implements `<input type=password>` styling with a `-webkit-text-security` property, for which there are several polyfills out there for other browsers (e.g. noppa/text-security), so perhaps it's the right cowpath to pave here.

It's worth noting that it's sometimes desirable to obscure the text of other inputs—`<input type=tel>`, for instance.

**Comment by FremyCompany** [comment]
![image](https://user-images.githubusercontent.com/364405/38278955-148d1728-3753-11e8-800d-6541a2a030a5.png)
![image](https://user-images.githubusercontent.com/364405/38278968-1e286da0-3753-11e8-971b-ba43671c4621.png)

**Comment by FremyCompany** [comment]
The button is only available if you are typing the password. Autofilled values and javascript-filled passwords are not accessible through that button (but of course are via the DevTools)

**Comment by jonjohnjohnson** [comment]
What if `text-transform` accepted a string, which covers more bases than the styles `-webkit-text-security` offers? Though less specific to security, it could be useful for "spoiler" visuals?

```css
text-transform: '\0020\00B7\0020';
```

**Comment by frivoal** [comment]
@jonjohnjohnson Not saying this is the right answer for this particular issue, but if we're talking about allowing authors to define arbitrary text-transforms, I have this proposal: https://specs.rivoal.net/css-custom-tt/

**Comment by hober** [comment]
@fantasai sure, adding a value to `text-transform` seems reasonable to me. While `-webkit-text-security` takes several values (offhand there's `disc`, `square`, and `circle`), I think we only need one, which means "please obscure the text in the manner of a native password field" or the like.

**Comment by hober** [comment]
See also https://technology.blog.gov.uk/2021/04/19/simple-things-are-complicated-making-a-show-password-option/

**Comment by yazeer-afk** [comment]
`text-security` attribute does not support Firefox yet?
