### ISSUE TITLE
[css-text-3] line breaks and ideographic space

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2500]
(reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1450228)

Browsers differ in how they handle line breaks for  IDEOGRAPHIC SPACE (U+3000):
* Firefox allows break before and after
* Chrome and Safari forbid a break before, and allow a break after
* Edge forbids a break before and allow a break after, but also allows hanging overflow

[try it here](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Ap%20%7B%0A%20%20%20%20width%3A%2010em%3B%0A%7D%0A%3C%2Fstyle%3E%0A%3Cp%3E%E3%81%82%E3%81%84%E3%81%86%E3%81%88%E3%81%8A%E3%81%A0%E3%82%8D%E3%81%86%E3%81%8B%EF%BC%9F%E3%80%80%E3%81%9D%E3%82%8C%E3%81%AF%E4%BD%95%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AB%EF%BC%81%E3%80%80%E7%A7%81%E3%81%AF%E3%80%81%E3%81%8B%E3%81%8D%E3%81%8F%E3%81%91%E3%81%93%E3%81%A0%E3%80%82%3C%2Fp%3E)

Quoting @MurakamiShinyu

> This is important because IDEOGRAPHIC SPACE is normally used after "！" or "？" in the middle of a paragraph to keep 1em space after such punctuation marks as explained in JLREQ [3.1.6 Positioning of Dividing Punctuation Marks (Question Mark and Exclamation Mark) and Hyphens](https://www.w3.org/TR/jlreq/#positioning_of_dividing_punctuation_marks)

That logic would favor Edge's behavior.

UAX-14 says that IDEOGRAPHIC SPACE (U+3000) has class BA (for break after), which would support the behavior of Chrome/Safari/Edge over Firefox's, but:
* I cannot I cannot find any reference in css-text-3 to UAX-14's BA class
* The line-break property does not mention IDEOGRAPHIC SPACE (U+3000)

Should we reference the BA class somehow?
Should we directly list DEOGRAPHIC SPACE (U+3000) in some level of line-break?
Should we say something about allowing/requiring it to hang?

**Comment by fantasai** [comment]
CSS Text Level 3 does not normatively define the line breaking behavior of every character. Nor does it normatively reference UAX14's tables, because while they are a good start, they do not represent the ideal breaking behavior of every language.

We could add specific rules for ideographic space. Allowing it to hang seems reasonable: if @MurakamiShinyu agrees we should specify that I'm happy to do it. Note that if it hangs, it effectively is BA because it's effectively zero-width when occurring at the end of the line. ;)

**Comment by MurakamiShinyu** [comment]
Yes, I agree the behavior allowing hanging is preferable.

**Comment by frivoal** [comment]
@MurakamiShinyu Do you have a suggestion about whether to hang multiple ideographic spaces? Or maybe we should hang one and wrap the rest?

**Comment by frivoal** [comment]
https://github.com/w3c/csswg-drafts/commit/f55dc746ad6d18264916591d04f88038a6cf0bbb hangs the whole sequence of ideographic spaces at the end of the line, let us know if that's fine.

**Comment by frivoal** [comment]
Tests: https://github.com/web-platform-tests/wpt/pull/13338

**Comment by frivoal** [comment]
@macnmm 
Either of the following two comments should become new issues if you want to continue discussing them. I'm responding here for now, but if you think the case isn't closed, I'd appreciate if you could file them separately

---
I don't think we define U+2003 as hanging. Should we, for reasons other than CJK? currently, we only hang U+0020 and U+3000. Should that be generalized to all sorts of spaces? Many-but-not-all sorts of spaces?

---

As for having a switch, we effectively have one: `white-space: break-spaces` disallows spaces from hanging / being removed, and requires them to wrap instead. It does not allow (by itself) wrapping before U+3000, since that still has the UAX14 line breaking class of BA, but if there's a series of U+3000, the subsequent ones will wrap, and if the first one doesn't fit, it will bring the preceding character together with it to the next line.

`white-space: break-spaces` isn't a switch that only does that, though. It also stops sequences of U+0020 from collapsing, and preserves line breaks from the source, just like `white-space: pre-wrap` would.

Whether that's acceptable or not, I am not sure, it depends on the use case. Which brings me to: what is the need that drives wrapping U+3000 in the InDesign roman paragraph composer? Is that because of a particular need, or does it just falls out of not handling CJK characters specially, but isn't particularly need driven?

**Comment by macnmm** [comment]
The need was an edge case when converting old file formats in which the user used U+3000 to indent or place text on embox boundaries on the page, expecting them to wrap like other CJK characters would. 
My memory of this is that both composers had this behavior; I was surprised there is a difference when I just checked, but have not dug into why the J composers now hang U+3000, when my memory was that they wrap in both.

**Comment by frivoal** [comment]
That use case doesn't really seem to apply to the web.
