### ISSUE TITLE
[css-align] initial value for `gap` differs from `row-gap` and `column-gap`

### ISSUE THREAD

**Issue by pkuczynski** [w3c/csswg-drafts#2504]
`gap` is a shorthand for `row-gap` and `column-gap`, but its initial value differs with initial values of those properties

https://www.w3.org/TR/css-align-3/#gap-shorthand

**Comment by frivoal** [comment]
You are right, it should say "see individual properties". This has already been corrected in the latest draft: https://drafts.csswg.org/css-align/#gap-shorthand
