### ISSUE TITLE
[css-fonts] value of `font-style`: `normal` vs. `oblique 0deg;`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2505]
At https://drafts.csswg.org/css-fonts-4/#valdef-font-style-normal, the draft spec says that `normal` 

> represents an oblique value of "0".

However, it is not clear to me from the spec exactly what this means. Given a non-variable font, with the typical Regular and Italic faces, which face will `font-style: oblique 0deg;` select?

(According to my testing, Chrome and MSEdge disagree on the answer to this.)

And with regard to animation, we find

> If both "from" and "to" values are "oblique", then yes, as an `<angle>`. Otherwise, no.

Does `normal` count as `oblique 0deg` for this purpose, such that `font-style` could be animated as an `<angle>` from `normal` to `oblique 15deg` or not?

**Comment by FremyCompany** [comment]
Sorry when I said CSS 2, I mean CSS-FONTS-3:
> User agents are permitted to distinguish between italic and oblique faces within platform font families but this is not required, so all italic or oblique faces may be treated as italic faces.
