### ISSUE TITLE
How do layout and size containment interact with column/page fragmentation?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2527]
During the discussion we just had in the face-to-face in #1457, @smfr mentioned the interaction of containment and boxes with multiple fragments.  It's not clear how this will work.

For example, if an element inside a multicol has layout and size containment, its contents shouldn't affect its layout.  So even if it has a width and height, its contents can't affect where it fragments.  It seems like, then, the only two choices are that (a) it doesn't fragment or (b) it fragments as though it could break anywhere.  I suspect (b) is probably better.

**Comment by frivoal** [comment]
Proposed solution, discussed with @tabatkins @dbaron @smfr @eaenet:

> Elements with size containment are [**monolythic**](https://drafts.csswg.org/css-break/#monolithic) for the purpose of fragmentation (see [[CSS-BREAK-3]).
