### ISSUE TITLE
[css-borders-4] Issues with listifying border-color

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#2532]
This is related to #1172.

In the [2017 Tokyo F2F we resolved](https://lists.w3.org/Archives/Public/www-style/2017May/0049.html) on listifying `border-color` with the design allowing for future listification of `border-width` and `border-style`.
We decided on `border-color` being the property that sets the number of borders, since a common case is having multiple borders with the same width and we didn't want authors to have to repeat the width of each stripe.

However, this has very unexpected and confusing repercussions. It means that setting `border-color` can increase the total border width. In the following:

```css
border-width: 10px;
border-color: red, black, white;
```

the resulting border width is actually 30px! (since `border-width` is expanded, per usual listification rules) This has never arisen before because none of our other listified properties stack this way, they are all independent layers.

Furthermore, another issue is that listification typically repeats the same syntax that a property already has. Since `border-color` accepts 1-4 colors for each side, this results in very weird listified syntax that inverts the relative power of space and comma to the exact opposite of how it would be expected to work. Look at this code and visual result:

```css
border-color: skyblue orange yellowgreen indianred, black yellow
```

![image](https://user-images.githubusercontent.com/175836/38607092-1198f110-3d78-11e8-9982-ad39e0faf6d4.png)

This is a completely nonsensical way to specify border colors. People think of all colors for a side as a group, they don't group colors by whether they are innermost or outermost.

For these reasons, @fantasai and I are exploring alternative syntaxes that cover most use cases with a more intuitive syntax.

The primary use cases we must definitely cover are:

- Multiple border stripes of equal width should be effortless, with no width duplication.
- Different width stripes with fixed ratios between them (e.g. two 1fr stripes with one 2fr color between them)
- A mix of fixed and flexible width stripes (e.g. two 1px black borders with blue between them that occupies the entire rest of the border). `fr` units deal very nicely with this.
- We don't think different styles are particularly useful here. Almost all use cases we've seen are about solid borders. Therefore, we're ok with having multiple colors for different styles just be defined as a cutout of the solid case.
- Are different colors per side useful?

## Idea 1: Making `border-color` accept a list of color stops

While this may sound like a convenient re-use, it has several issues. Unlike gradients, in borders stripes are more often desired (are gradients even that useful here?) so we'd need to change how the syntax behaves anyway. Re-using a concept from somewhere else (like gradients) but subtly changing it is confusing.
Also, color stops are specified with absolute positions across the gradient line, whereas with borders you more often than not want them to "stack" and define widths instead of starts and ends (also so you can use `fr` units, which would be convenient here, as discussed above).

## Idea 2: `stripes()` + `border-color`

This would define a `stripes((<color> && <length-percentage>?)#)` function that creates a one dimensional image. Lengths would also accept `fr`. This can be used anywhere that images are accepted, including backgrounds, as long as there is handling for 1-dimensional images. Possibly these could also be used in place of the gradient line in all our gradient functions.

**Why 1-dimensional?** Because otherwise, it would be problematic when combined with `border-radius`. It's tricky to define something reasonable for how a 2D image curves around the corner, and ignoring `border-radius` is suboptimal for most use cases.

So, the original use case of equal width black and white borders would be:

```css
border-color: stripes(black, white);
```

Other cases:

Code | Meaning
|----|-------|
`stripes(2px white, black 1fr, 2px white)` | Two 2px white borders with black in between them
`stripes(red, green, blue)` | 3 equal width stripes, starting from red on the outside, green in the middle, blue on the inside
`stripes(red 1fr, green 2fr, blue 1fr)` | 25% red on the outside, 50% green in the middle, 25% blue on the inside.
`stripes(red)` | Same as `border-color: red`
`stripes(red 30%, green)` | Same as `stripes(red 30%, green 1fr)`: 30% red and 70% green.

## Idea 3: Adding a `border-stripes` (name TBB) property that accepts a *1-dimensional image* (as described above) or a list of colors and widths.

The main problem with this is the way it interacts with `border-color`. Unless there is a transparent stripe, `border-color` will have no effect when this property is set. One of the most confusing things about CSS is when a property enables/disables another property. I'd rather not introduce even more of that.

**Comment by SebastianZ** [comment]
In my pull request to add `stripes()` I imagined it to be context sensitive, in contrast to 0-dimensional and 2-dimensional images.

@LeaVerou wrote in the PR:
> It has been a long time, but IIRC the resolution of these discussions, we would define 1 dimensional images, and `stripes()` would just produce a 1 dimensional image. Right now in CSS we have 2d images (gradients, urls etc), and 0 dimensional images (`image(<color>)`). I see that in this PR, `stripes()` is defined as its own type, and can only be used in properties that explicitly allow it. We'd like to be a bit more general than that.

@LeaVerou How do you imagine `stripes()` to work more generally and still cover the use case of multiline borders and outlines? How would painting 1-dimensional images be defined? Should it be also added to `<image>` like 0-dimensional images were via `image()`? If so, how would that work together with `border-color`?

I imagine `stripes()` or genereally 1-dimensional images to behave differently for different properties. I.e. regarding the use case of multiline borders the stripes are painted around the border.
Though in other contexts they may be interpreted differently. E.g. they could be used in a radial gradient as a replacement for the existing color stop syntax like `radial-gradient(stripes(red, yellow, lime, blue))` as an equivalent for `radial-gradient(red 25%, yellow 25%, yellow 50%, lime 50%, lime 75%, blue 75%)`.

If `stripes()` should be defined as an image (and by that be included in `<image>`), I'd rather add a way to define it in `border-image` / `border-image-source` and disable the slicing there.

Though in any case it still requires to define for each context how the stripes should be painted.

Sebastian

**Comment by svgeesus** [comment]
>  How would painting 1-dimensional images be defined?

It is already common to use effectively 1D images on backgrounds (_n_ x 1pixels), duplicating the image to fill the background. This can also be thought of as a brush.

This would be similar, except the brush is moved along the border, perpendicular to each edge.

**Comment by tabatkins** [comment]
There's no "natural" way to tile a 1d image into 2d; at minimum, vertical or horizontal tiling are both completely reasonable. We could choose one way arbitrarily if we wanted, I suppose.

**Comment by SebastianZ** [comment]
For the record, I have updated my PR to include the points discussed here.

Sebastian

**Comment by SebastianZ** [comment]
I didn't hear back on my questions and changes to the PR, so I thought maybe that could quickly be clarified in the next call, because I'd love to finish up this change.

Sebastian

**Comment by LeaVerou** [comment]
> > Yes, 1 dimensional images are still `<image>`.
> 
> I assume by that you mean to add `stripes()` to `<image>` but in properties like `border-color` and `outline-color` only `stripes()` is allowed, not the whole `<image>` syntax, right?

These properties should accept a 1 dimensional image, not `stripes()` specifically. That way, we can add more forms for creating 1 dimensional images in the future or functions that operate on them and not have to update a bunch of grammars. In general, defining input in terms of types is better than defining it in terms of syntax.


> 
> > I suppose we'd need to define some handling for when a 1d image is used raw in places that expect a 2d image. E.g. it could be converted to a 2d image via horizontal or vertical repetition (or stretching). 🤷🏽‍♀️
> 
> > There's no "natural" way to tile a 1d image into 2d; at minimum, vertical or horizontal tiling are both completely reasonable. We could choose one way arbitrarily if we wanted, I suppose.
> 
> Tiling or stretching sounds reasonable. Just to be clear we're on the same page here, I have two examples for a 100px by 100px image using `stripes(red, yellow, lime, blue)`:
> 
> Horizontal tiling: ![stripes(red, yellow, lime, blue) interpreted with horizontal tiling](https://user-images.githubusercontent.com/958943/154155035-6fb894aa-1382-454f-8f69-318c1d85b36e.png)
> 
> Vertical tiling: ![stripes(red, yellow, lime, blue) interpreted with vertical tiling](https://user-images.githubusercontent.com/958943/154155571-11bacdd1-b6b6-4461-998f-e202b8d7bef8.png)
> 
> Correct?
> 
> If so, I'd aim for the same behavior as for `linear-gradient()`, i.e. draw them from top to bottom, tiling (or stretching) them horizontally (like in the first example above). This will also allow to use it in `linear-gradient()` as mentioned earlier without surprises.

Just to be clear, `strips()` in `linear-gradient()` (or `radial-gradient()`, or `conic-gradient()`) would get the directionality of the gradient. The default directionality we are discussing here only applies when a 1 dimensional image is used by itself in contexts that expect a 2d image. E.g. when you do `background: stripes(...);`.

**Comment by SebastianZ** [comment]
> > > Yes, 1 dimensional images are still `<image>`.
> > 
> > I assume by that you mean to add `stripes()` to `<image>` but in properties like `border-color` and `outline-color` only `stripes()` is allowed, not the whole `<image>` syntax, right?
> 
> These properties should accept a 1 dimensional image, not `stripes()` specifically. That way, we can add more forms for creating 1 dimensional images in the future or functions that operate on them and not have to update a bunch of grammars. In general, defining input in terms of types is better than defining it in terms of syntax.

Good point! I've changed the definition accordingly.

> Just to be clear, `stripes()` in `linear-gradient()` (or `radial-gradient()`, or `conic-gradient()`) would get the directionality of the gradient. The default directionality we are discussing here only applies when a 1 dimensional image is used by itself in contexts that expect a 2d image. E.g. when you do `background: stripes(...);`.

Yes, that's also how I expected it to work. Thanks for clarifying that! Once the function is added, I'll create a new issue to add it to the gradient functions.

Sebastian

**Comment by fantasai** [comment]
If we want stripes() to work in 2D, we should define a 2D stripes function, which can re-orient the stripes as appropriate. It's not worth the implementation/testing/documentation effort to have a stripes() function available in all 2D contexts that can only do horizontal stripes. IMHO.

**Comment by SebastianZ** [comment]
The idea is to let one-dimensional images work in both one-dimensional and two-dimensional contexts.
In 1D contexts like `border-color` and `outline-color` they are context-sensitive.
In 2D contexts they are horizontal by default. We could additionally define a 2D variant of that function that allows rotating them. Though as [pointed out earlier](https://github.com/w3c/csswg-drafts/issues/2532#issuecomment-1040505437) by @LeaVerou, the plan is to also allow 1D images in gradient functions. So re-orientation would be done via `linear-gradient()`.  Another way to achieve that is the `@image` rule suggested in https://github.com/w3c/csswg-drafts/issues/6807.

So I wonder whether a separate 2D stripes function would be worth the redundancy. We might remove `<1d-image>` from direct usage in `<image>`, though, and already add it to the gradient functions.

Sebastian

**Comment by SebastianZ** [comment]
> <fantasai> topic: [css-background-4] Issues with listifying border-color
> <fantasai> github: https://github.com/[/issues/2532](https://github.com/w3c/csswg-drafts/issues/2532)
> <fantasai> lea: Let's wait until Sebastian can attend

Sorry for not attending! I'll try to be there on the next call.

Sebastian

**Comment by SebastianZ** [comment]
Just as reference, I've removed `<1d-image>` from `<image>` from my PR as we resolved on and split out the discussion about it into #7241. In addition to this, I've created #7244 to discuss adding stripes as gradients or as gradient-like functions.

Sebastian

**Comment by SebastianZ** [comment]
The `stripes()` function is now defined as part of [`<image-ID>` in CSS Images 4](https://drafts.csswg.org/css-images-4/#typedef-image-1d) and used for [`border-color` in CSS Borders 4](https://drafts.csswg.org/css-borders-4/#the-border-color).

Therefore I believe this can be closed.

Sebastian
