### ISSUE TITLE
[css-fonts-4] Angle for oblique->normal threshold should be lower end of common obliques not 20

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2539]
The font matching algorithm searches upward from the specified angle to more slanted fonts if the angle is > 20deg, and downward towards normal fonts if it is < 20deg. This threshold should not be the most common angle of obliques, but rather the lower end of that range, otherwise requests for an oblique angle which is reasonably oblique but not so much as the average will end up with a normal font.

**Comment by svgeesus** [comment]
Sure - because of https://github.com/w3c/csswg-drafts/issues/2295 the 20deg in this algo should be 14deg, anyway.

**Comment by fantasai** [comment]
It should be lower than that, is my argument.

**Comment by svgeesus** [comment]
Hmm I see the spec still uses 20 deg in the `font-style` part of the  [font matching algorithm](https://drafts.csswg.org/css-fonts-4/#font-matching-algorithm)

**Comment by svgeesus** [comment]
And just checking (since there are 8 occurrences of `20deg` in the spec currently) this is _just for oblique_ right, not for italic.

**Comment by svgeesus** [comment]
Also does this _common scale_ mapping need to be changed?

> User agents are not required to distinguish between italic and oblique fonts. In such user agents, the font-style matching steps above are performed by mapping both italic values and oblique angles onto a common scale. The exact nature of this mapping is undefined, however, an italic value of 1 must map to the same value that an oblique angle of 20deg maps to.

**Comment by svgeesus** [comment]
All occurrences of 20deg related to oblique, so in the end they were all changed to 11.
