### ISSUE TITLE
[css-fonts-4] Content authors want to modify style based on the presence of color fonts

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2540]
Perhaps we could figure out a way to use `@supports` to see if color fonts are supported?

**Comment by Jolg42** [comment]
Thanks @litherum for opening the issue ;-)

_This issue is related with the color font `format()` specifier: https://github.com/w3c/csswg-drafts/issues/633_

Based on creatives’ feedback regarding the use of color fonts on the web, there are cases when color fonts will lack of a viable fallback design, which will require specific layout adjustments.

For instance:
1. The color font may have been designed without any fallback glyphs
2. The fallback glyphs may be irrelevant (i.e. when fallback glyphs are automatically created: a colored alphabet that fits within square shapes would be converted into illegible black squares)
3. The fallback font may require different CSS styling (i.e. when its metrics are different from the color font)  

In these cases, adding a feature detection of font formats (including color) would give web designers greater control over the fallback experience - specially during the transition phase until broad color font support is reached.

One potential solution could be to leverage `@supports` to identify the supported font flavors (this would be handy for both color and variable fonts).

One could argue that a fallback font should always be designed and match the color version, but from a creative’s standpoint, some color fonts will simply never have a fallback version (for aesthetic or practical reasons, as the the complexity and amount of work needed to create a color font with its fallback would prevent many to venture into color font creation).

What do you think?

**Comment by SergeyMalkin** [comment]
Is the main complaint here is that UA doesn't support color fonts or color font is supported, but lack non-color fallback glyphs? There are several reasons, besides UA not supporting color fonts, why having fallback glyphs in color font is important:

- Canvas or SVG may need to extract glyph geometry for fill/stroke/clip operations.
- Text shadow is rendered as solid color without colors.
- You can have b/w printer where colors are disabled. In this case I don't want to change layout based on printer model, so font should be the same. Although, we can use color glyphs rendered in greyscale, as images. 

This is not about UA support for color fonts, but functionality that _requires_ fallback glyph to be present. If one of those is used on your page, you better have font that has fallback glyphs. If it is not, why do you care about fallback glyphs?

#633 talks about @font-face functionality that allow UA download fonts with format that it supports. Whatever font is downloaded from list of urls in src descriptor, should have same or similar layout characteristics. If color formats is supported as part of formats() filter, we are getting font that works in your UA automatically.

**Comment by RoelN** [comment]
A solution like this could also be used to download only the supported format. E.g. download SVG in Firefox and Edge, but COLR in Chrome when it doesn't support SVG. You would prevent sending unsupported formats to browsers, or creating huge all-formats-in-one-font files.

**Comment by tabatkins** [comment]
@RoelN That's already handled by the `format()` function in the `@font-face/src` descriptor; you can list the required features the file needs, and the UA will skip over it if they don't support the feature.

I'm in favor of figuring out an `@supports` syntax for this. Per usual with `@supports`, this ideally would let browsers reuse the same parsing logic they already have for the `format()` feature detection.

**Comment by svgeesus** [comment]
This has now been added, see the explainer 

- [`font-tech()` and `font-format()` `<supports-feature>` Extensions to CSS `@supports`](https://github.com/w3c/csswg-drafts/blob/main/css-conditional-5/font-tech-format-explainer.md)

The explainer includes examples based on the presence of color fonts, and also availability of different types of color fonts.
