### ISSUE TITLE
[css-text] Bad box terminology for text-wrap

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2545]
From https://drafts.csswg.org/css-text-4/#text-wrap,

> Applies to: all elements

Should probably be "Applies to: inline boxes and block containers"

> Same as `wrap` for inline-level elements.

Should probably be "Same as `wrap` for inline boxes." in both occurrences

> Same as `wrap` for block-level elements

Should probably be "Same as `wrap` for block containers"

> For block-level elements that contain line boxes as direct children

Should probably be "For block containers that contain line boxes as direct children". But I think line 'boxes' only exist in the fragment tree so they are not really children of a box. So "For block containers that establish an inline formatting context".

Additionally, it seems `wrap` and `nowrap` don't really apply to block containers, their effect is only via inheritance to inline boxes. Consider clarifying this.

**Comment by fantasai** [comment]
Cleaned up the wording, thanks! https://drafts.csswg.org/css-text-4/#text-wrap
