### ISSUE TITLE
[css-values] Quotes and serialization of urls

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2547]
Serialization of [urls](https://drafts.csswg.org/css-values/#urls) is not consistent between browsers, and the specs appear to be silent.

Any URL in 'cursor' or 'background' or ... is not enclosed in quotes when serialized by Safari.

Any URL in 'cursor' or 'background' or ... is enclosed in double quotes when serialized by Blink or Firefox.

Any URL in 'background' or ... is enclosed in double quotes when serialized by Edge.

Any URL in 'cursor' is not enclosed in quotes when inline style is serialized by Edge, and is enclosed in single quotes by Edge getComputedStyle. This may be an Edge bug specific to cursor.

[Test page](https://jsfiddle.net/ericwilligers/zazenw8e/)

**Comment by tabatkins** [comment]
Yeah, and I think that's a good thing to stick with.

**Comment by ewilligers** [comment]
Closing as spec is sufficiently clear. Browser bugs:
https://bugs.webkit.org/show_bug.cgi?id=28869
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16900961/
