### ISSUE TITLE
[css-multicol] What happens to the mbp of the empty fragment created by a spanner being first-child of an element

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#2552]
In working on #1072 I built some tests and noticed something which seems suboptimal. 

Where the spanner is the first child of an element with margin, padding and borders implementations then split those across the columns. [I have a test case here](https://codepen.io/rachelandrew/pen/aYQeqZ/) and below is a screenshot of this in Chrome 65. 

<img width="636" alt="chrome-split-mpb" src="https://user-images.githubusercontent.com/2764898/38673943-1a9ba31c-3e53-11e8-9e6e-c5871bd7b357.png">

The margin is in column box 1, then the top border, then the padding with a left and right border. This seems logical although probably not what anyone wants. Either way, we don't have any text describing what should happen in this case.

**Comment by mstensho** [comment]
Isn't this covered by the spec?

https://drafts.csswg.org/css-multicol/#spanning-columns

> A spanning element may be lower than the first level of descendants as long as they are part of the same formatting context. If the fragment before the spanner is empty, nothing special happens; the top margin/border/padding is above the spanning element, as an empty fragment.

Not quite sure what "empty fragment" means, though.

**Comment by mstensho** [comment]
Isn't this covered by the spec?

https://drafts.csswg.org/css-multicol/#spanning-columns

> A spanning element may be lower than the first level of descendants as long as they are part of the same formatting context. If the fragment before the spanner is empty, nothing special happens; the top margin/border/padding is above the spanning element, as an empty fragment.

Not quite sure what "empty fragment" means, though.
