### ISSUE TITLE
[css-step-sizing] property name in example doesn't match spec

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#256]
The example linked from the spec (snap-height.html, which works in Canary) uses the `snap-height` property, but the spec calls the same property `line-height-step`.

**Comment by RByers** [comment]
Looks like this is still an issue.  @kojiishi, should be  a quick trivial fix - right?

**Comment by kojiishi** [comment]
Yeah, I didn't want to rename when the spec was unstable, but now we've got FPWD, and Canary was updated to the new name. I'll update the example.

**Comment by kojiishi** [comment]
...and I need to remove the baseline feature we removed before FPWD. That was changed after this bug was filed, but I think the intention includes this fix too.
