### ISSUE TITLE
[css-cascade] Probably css-cascade shouldn't say that there's a specified value for every property and element.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2562]
https://drafts.csswg.org/css-cascade/#specified says:

> guaranteeing that a specified value exists for every property on every element.

Similarly, https://drafts.csswg.org/css-cascade/#intro says:

> The cascading and defaulting process takes a set of declarations as input, and outputs a specified value for each property on each element.

Those two paragraphs, and probably a couple more, should mention "for each element of the flat tree", or something like that, probably, to be in accordance with the resolutions in #1964 and #1548.

**Comment by fantasai** [comment]
Fundamentally, CSS has an abstract concept of a document tree which is given as input to CSS. Shadow DOM has decided to compose the flat tree and give it to CSS for presentation. You can give it other kinds of trees, it doesn't have to be a DOM tree.

Where and how best to define the interaction of CSS and Shadow DOM--the fact that DOM hands over the flat tree, and not some other construct, for CSS to style--isn't entirely clear to me... In a sense, it's the DOM's semantics that says "this is what should be presented to the user", so I could make a pretty good argument that the DOM should be the one defining that we use the flat tree. (If we used a different tree technology, there wouldn't be a “flat tree” definition to use, but if DOM was presented with some other style sheet technology, it would still need to define that it's the flat tree that gets presented.) But in any case, we'll probably want to gather all of these issues and solve them together, as clearly the current situation is a bit incoherent.

**Comment by fantasai** [comment]
@emilio https://drafts.csswg.org/css-cascade-4/#value-stages has the following text:

> Elements that are not connected or are not part of the document’s flattened element tree do not participate in CSS value processing, and do not have declared, cascaded, specified, computed, used, or actual values, even if they potentially have style declarations assigned to them (for example, by a style attribute).

I think that should cover it?

**Comment by fantasai** [comment]
This was added in https://github.com/w3c/csswg-drafts/commit/880486514241f763de8f63bc09937f909bb13a65 two months ago. I think that closes this issue. :)
