### ISSUE TITLE
[css-multicol] margin box of column-spanning element interrupt column content, including column-rule

### ISSUE THREAD

**Issue by TalbotG** [w3c/csswg-drafts#2579]
[6.1 'column-span' Working draft](https://www.w3.org/TR/css-multicol-1/#column-span)
[6.1 'column-span' Editor's draft](https://drafts.csswg.org/css-multicol/#column-span)

Proposal
-----------
Somewhere inside section 6.1, the following sentence should be added:
"
The margin box of column-spanning element interrupt column content, including column-rule.
"

**Comment by rachelandrew** [comment]
There is an example further on in that section explaining that margins do not collapse. 

When we have a spanner, we get a new set of column boxes after the spanner. A 'column row', and I think the margin collapsing rules are defined. It isn't so much an "interruption" of the content, as the column does not continue on the other side of the break. The column boxes end with the spanner, we then start over again with the next set.
