### ISSUE TITLE
Declare CSS2 as superseded

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2589]
The process now allows us to [declare specifications as superseded](https://www.w3.org/2018/Process-20180201/#rec-rescind); I hope we can all agree that CSS 2.1 superseded 2.

I suggest we request the Director begin an Advisory Committee review of a proposal to supersede [CSS2](https://www.w3.org/TR/1998/REC-CSS2-19980512/) (and the [edited recommendation published in 2008](https://w3.org/TR/2008/REC-CSS2-20080411/)).

Proposed rational: CSS 2.1 heavily revises CSS2 and is a far better specification for documented behaviour, as is shown by its implementation report.

**Comment by svgeesus** [comment]
LGTM

**Comment by astearns** [comment]
We probably do not need to use meeting time for this.

This comment is a call for consensus on the proposal in the [first comment](https://github.com/w3c/csswg-drafts/issues/2589#issue-314947641). Please reply before the end of May 1 2018 either with a thumbs-up or a comment stating your objection.

**Comment by fantasai** [comment]
I thought we effectively did that when we published https://www.w3.org/TR/2009/CR-CSS2-20090423/ and merged the shortnames. I mean, where would we publish the superseded REC? We're publishing CSS2.1 at /TR/CSS2 already.

**Comment by astearns** [comment]
We did effectively do that. This is just formally doing it again, since the formal process is now available to us.

Unfortunately, it looks to me like the process doc is completely silent on whether/how to publish a superseded rec. The bit about publishing only refers to obsolete or rescinded recs. I suspect that's an oversight.

**Comment by gsnedders** [comment]
@fantasai 

Presumably at https://www.w3.org/TR/2018/REC-CSS2-2018mmdd/, which I admit is somewhat confusing when it's essentially an older document than https://www.w3.org/TR/2011/REC-CSS2-20110607/ albeit sharing the short name. Will need to make sure `tr.rdf` reflects the proper reality of the world.

@astearns It does:

> The process for declaring a Recommendation Superseded is the same as for declaring it Obsolete, below; only the name and explanation change.

So you just follow the bit about Obsolete Recs.

**Comment by dbaron** [comment]
(As a side note, https://www.w3.org/TR/REC-CSS2/ still points to CSS 2, not 2.1, but it was a commonly-cited "latest version" url around 1998-2003, so it should be updated [as the WG resolved](https://log.csswg.org/irc.w3.org/css/2018-04-12/#e1004079).)

**Comment by fantasai** [comment]
Yeah, I think we should handle this by just fixing the places where CSS2 still points at CSS2.0 to point at CSS2.1, as we intended when we merged the shortnames. What we did is not intrinsically different from taking a REC back to WD and then putting it back in REC again; this is different from superseding a REC, it's maintenance of the REC.

We will use the superseded status on CSS2 once we've finished replacing it with CSS3 modules and no longer need to maintain it.

**Comment by astearns** [comment]
I'm reading @fantasai's comments as an objection to superseding CSS2, since CSS2 encompasses 2.0, 2.1 and the ongoing maintenance. Anyone care to argue further on this? I confess that aside from fixing confusing links I don't have a strong opinion on this.
