### ISSUE TITLE
[css-grid-2] spanning all rows in an implicit grid

### ISSUE THREAD

**Issue by o-t-w** [w3c/csswg-drafts#2594]
It would be useful to be able to span to the last row (e.g. 1 / -1) for implicit grids. I have a grid where new content will be added, so I have no idea how many rows there might be or what the number of the last row will be.

My use case: I have a position: sticky button that I want to span the space of one column but stay within view as the user scrolls. I therefor need to make the div that contains the button span all rows of the grid

**Comment by tobireif** [comment]
Also see https://github.com/w3c/csswg-drafts/issues/2402 .

**Comment by mrego** [comment]
Yes, better close this issue and discuss in the other one.
