### ISSUE TITLE
[css-transforms-2] Individual transform properties are currently spec'd as applying to all elements

### ISSUE THREAD

**Issue by ChumpChief** [w3c/csswg-drafts#260]
Spec link: https://drafts.csswg.org/css-transforms-2/#individual-transforms

This differs from the transform property, which is currently spec'd as applying only to transformable elements:
http://www.w3.org/TR/css-transforms-1/#transform-property

I think the "transform" and individual transform properties should apply to the same set of elements.  For now I think that means the individual transform properties should apply to transformable elements only unless/until the behavior of transforms on other elements is specified.

**Comment by tabatkins** [comment]
Yes, this is just an oversight. They should definitely apply to the same set of elements.

**Comment by ewilligers** [comment]
I fixed this in https://github.com/w3c/csswg-drafts/pull/705 without noticing the issue had already been reported.

This issue can be closed.

**Comment by ChumpChief** [comment]
Looks good, thank you!
