### ISSUE TITLE
[css-fonts-4] font-stretch computed value.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2605]
https://drafts.csswg.org/css-fonts-4/#font-stretch-prop says:

> Computed Value: as specified.

I think the computed value should be a `<percentage>`, perhaps with a `getComputedStyle` quirk to keep the keyword serialization in the case where the percentage matches one of the keywords?

That being said, the following page shows `100%` on Chrome, so it means that they managed to ship it without the quirk, which is simpler:

```html
<!doctype html>
<div id="test" style="font-stretch: normal"></div>
<pre>
<script>
  document.write(getComputedStyle(test).fontStretch);
</script>
</pre>
```

I don't have Edge or Safari around to test this (Epiphany builds without var fonts).

We plan to implement Chrome's behavior here unless we need the old behavior for compat.

cc @drott @litherum @FremyCompany

**Comment by emilio** [comment]
Looks like safari does return keywords here, that is `font-stretch: 150%` computes to `extra-expanded`, so there's no interop here. Any opinion about what's the best thing here?

Safari's behavior seems more backwards-compatible, but Chrome's is probably simpler.

Also, note that Chrome does go back to keywords when needed to serialize the font shorthand.

**Comment by svgeesus** [comment]
with `font-stretch: extra-condensed`
Chrome: **62.5%**
Firefox: **extra-condensed**
Edge: **62.5%**

and with `font-stretch: 79%` (does not map to a keyword):
Chrome: **79%**
Firefox: **normal**
Edge: **79%**

Firefox was correct per Fonts 3 spec, as percentages were disallowed! But that was changed in Fonts 4, given that variable fonts could have any percentage value. Edge and Chrome already accept percentages.

**Comment by emilio** [comment]
> Firefox was correct per Fonts 3 spec, as percentages were disallowed (so it falls back to the initial value). But that was changed in Fonts 4, given that variable fonts could have any percentage value. Edge and Chrome already accept percentages.

Yeah, I'm fixing this in Firefox, thus the issue :).

We're going to behave like Chrome / Edge for now, mostly for simplicity. But probably at least the spec should be changed to compute to `<percentage>`.

Afterwards we can specify Safari's behavior re. keywords if needed with a getComputedStyle quirk, but if people have managed to ship without it I'd be fine just sticking with the simple thing.

**Comment by svgeesus** [comment]
Marking as edits needed for the resolving to percentage part; cc @litherum regarding allowing mapping back to keywords for matching percentages.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/107bc185a9f4659663257c44793d61177582cdc4
