### ISSUE TITLE
[css-fonts-4] Editorial: font-stretch should probably animate as a <percentage>

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2606]
https://drafts.csswg.org/css-fonts-4/#font-stretch-prop says that it animates as `<number>`. That property doesn't accept a `<number>` whatsoever, should it say that it animates as a `<percentage>`?

**Comment by svgeesus** [comment]
Yes, you are quite correct!

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/107bc185a9f4659663257c44793d61177582cdc4
