### ISSUE TITLE
[css22] Character encoding of documents

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#261]
Original:
https://lists.w3.org/Archives/Public/www-style/2015Sep/0140.html

This proposal is adding `<meta http-equiv>` to HTML source of CSS 2.2.

**Comment by xfq** [comment]
https://drafts.csswg.org/css2/ has `<meta content="text/html; charset=utf-8" http-equiv="Content-Type">` now.

Can we close this issue?
