### ISSUE TITLE
[css-flexbox-1] Fragmentation rules around break propagation are confusingly-written

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2614]
https://github.com/w3c/web-platform-tests/issues/7958

**Comment by fantasai** [comment]
OK, I made some clarifications to Fragmentation and to Flexbox, specifically, pulled out break propagation into [its own section into css-break-3](https://drafts.csswg.org/css-break-3/#break-propagation) and clarified that:

- out-of-flows don't propagate their break values up to their parents
- layout modes like Flexbox have more specific propagation rules which override the one in css-break-3
- Flexbox uses order-modified document order in determining first/last child

Agenda+ since this has normative implications

**Comment by gregwhitworth** [comment]
@fantasai With regards to flex change specifically - this is how I understood the previous spec text to work so no argument from me. I think the clarity provide by this change will make it much more approachable by anyone; so, it's a good improvement. Finally, the addition of the note regarding the computed value clarifies the confusion the test author had. Thanks for doing this.
