### ISSUE TITLE
[css-grid-2] Subgrid local line names

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2622]
The original per-axis subgrid proposal https://www.w3.org/TR/2015/WD-css-grid-1-20150917/ had included syntax for local line names. The subgrid also receives the line names assigned by its parent. When both are provided, should the local line names be _in addition to_ the line names of the parent or should they _override_  (hide) the line names of the parent?

**Comment by tabatkins** [comment]
My original intention was to have both.

**Comment by fantasai** [comment]
OK, I committed changes to drop the issue from the spec and clarify that the names combine.
@MatsPalmgren I think switching based off a keyword is not a bad idea, but let's wait and see if there's a demand for it. :)
