### ISSUE TITLE
[fx-filter-effects-2] Add @filter rule

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#2625]
@tabatkins created a [draft of an `@filter` rule spec.](https://tabatkins.github.io/specs/css-filter-rule/) some time ago after some [discussion about the current `filter` and `backdrop-filter` properties being somewhat limited](https://lists.w3.org/Archives/Public/public-fx/2016JanMar/0026.html).

Could this draft be incorporated into the Filter Effects Module Level 2?

Sebastian

**Comment by dirkschulze** [comment]
@SebastianZ Could you move this issue to https://github.com/w3c/fxtf-drafts please?

**Comment by SebastianZ** [comment]
Thank you for the hint, @dirkschulze, and sorry for the delay! I've filed https://github.com/w3c/fxtf-drafts/issues/292 now.

Sebastian
