### ISSUE TITLE
[css-lists][cssom] Should the serialization of counter-reset/increment include default values?

### ISSUE THREAD

**Issue by squelart** [w3c/csswg-drafts#2635]
In the CSSOM general principles of serialization: https://drafts.csswg.org/cssom/#serializing-css-values
> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

This would suggest that if a counter-reset or counter-increment was declared with no values, its serialization should *not* include the default value (resp. 0 or 1).

E.g.: `<body style="counter-increment: abc" onload="alert(document.body.style.counterIncrement)">` should display "abc".
Edge 42 does this.
However Firefox 60, Chrome 66, and Safari 11.1 currently display "abc 1".

So, should the general rule be followed, or should there be a special case for counters? (Or something else?)

**Comment by squelart** [comment]
This should probably have the "css-list-3" label (can't seem to be allowed to add it)

See initial Firefox-related discussion: https://bugzilla.mozilla.org/show_bug.cgi?id=1408257

Note: Newbie here, sorry if I used the wrong vocabulary above!

**Comment by upsuper** [comment]
Given the principle, I believe the default value should be omitted. We should add a web-platform test and file bugs to the corresponding browsers.

**Comment by tabatkins** [comment]
Yeah, should be omitted unless there's web-compat to deal with.

**Comment by fantasai** [comment]
Fixed in 848b8c611bffea756866a53972ce531b8a649e4d

**Comment by fantasai** [comment]
Marked "Obvious Bugfix" because we're supposed to stay in sync with 2.1.

**Comment by ewilligers** [comment]
> Fixed in 848b8c611bffea756866a53972ce531b8a649e4d

I don't see how that change addresses this issue.

**Comment by fantasai** [comment]
@ewilligers Yeah, I don't know why I posted that comment here. :/ Must've mixed up this issue with #4163.

That said, I don't think any edits are needed here, so marking the issue closed.
