### ISSUE TITLE
[css-fonts-4] MapClass is removed from IDL spec

### ISSUE THREAD

**Issue by saschanaz** [w3c/csswg-drafts#2639]
[CSSFontFeatureValuesMap](https://www.w3.org/TR/2018/WD-css-fonts-4-20180410/#cssfontfeaturevaluesmap) uses MapClass extended attribute:

```webidl
[MapClass(CSSOMString, sequence<unsigned long>)]
interface CSSFontFeatureValuesMap {
  void set(CSSOMString featureValueName,
           (unsigned long or sequence<unsigned long>) values);
}
```

But it's removed and replaced by `maplike`: https://github.com/heycam/webidl/commit/1bc1e2904d3cd90d7856e184cb4b5f10d26b8d96 (Although the commit message improperly refers MapClass as MapLike)

**Comment by svgeesus** [comment]
[MapLike](https://heycam.github.io/webidl/#idl-maplike

**Comment by svgeesus** [comment]
Fixed by https://github.com/w3c/csswg-drafts/commit/713ace77005823ee071975f9728f5cf84ec2fc12
