### ISSUE TITLE
[css-grid-2] Define containment for subgrids

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2641]
A subgrid doesn't establish a new grid formatting context: it extends its parent’s, with various interactions between the two. This is intentional. (It's the whole point of subgrid.) But for an element with `contain: layout`, we have to define what happens. Presumably the subgrid is no longer a subgrid, but what does it do with its tracks?

- Do they resolve the same as `none` or do we infer the number of tracks from the number of tracks it spans in the parent?
- If the latter, where do they get their size, from `grid-auto-*`?
- What if it has no grid parent from which to determine the span?

(Whichever options we choose, probably the general case of a subgrid without a parent grid should have consistent behavior. Currently we've specced it to behave as `grid: none`.)

**Comment by tabatkins** [comment]
It definitely needs to have the appropriate number of tracks in itself as specified by its span.

I *think* it should copy over the computed values of the corresponding tracks from its parent grid as its own tracks; that'll give a good result most of the time without having a layout-time dependency.

If no parent, hm, probably from `grid-auto-*`, yeah. They're explicit grid tracks, but the implicit grid is the only place we can get information from.

**Comment by fantasai** [comment]
> I think it should copy over the computed values of the corresponding tracks from its parent grid as its own tracks; that'll give a good result most of the time without having a layout-time dependency.

Yeah, but it still allows the parent grid to have an effect on the subgrid; e.g. line names will transfer over and possibly conflict, and the track sizes end up controlled by the parent even though it's not a back-and-forth interaction like in an actual subgrid. Isn't the point of layout containment to not do that?

**Comment by tabatkins** [comment]
Only computed values will transfer from parent to child; there's no layout-time connection between the two.  The point of layout containment is that you can layout the element's parent without having to care about the element's contents, and that's still true (exactly as true as if the contained element is a normal grid).
