### ISSUE TITLE
[cssom] [css-scoping] Stylesheet title and Shadow DOM

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2646]
See the following test-case:

```html
<!doctype html>
<div id="host"></div>
<script>
  host.attachShadow({ mode: "open" }).innerHTML = `
    <style>
      div { color: purple; }
    </style>
    <style title="Foo">
      div { color: green; }
    </style>
    <style title="Bar">
      div { color: red }
    </style>
    <div>Which color am I?
  `;
  console.log(host.shadowRoot.styleSheets[0].title);
  console.log(host.shadowRoot.styleSheets[1].title);
  console.log(host.shadowRoot.styleSheets[2].title);
</script>
```

For this very simple test-case:

 * Blink shows red (which means that they apply all the stylesheets).
 * WebKit shows green (do they apply the "preferred" sheet per subtree? Or they just tweak the global state?).
 * Gecko shows green because it tweaks the global state, but with patches of mine they'd turn purple. I guess I'll turn it red now, but worth considering this.

Blink also doesn't set the stylesheet `title` property. @lilles is there any reasoning for that? Looks like a bug to me.

cc @rniwa

**Comment by emilio** [comment]
Looks like WebKit's behavior is intentional, given that the selected and preferred name lives in `StyleScope`.

So I'll implement out of simplicity Blink's behavior, but happy to change to whatever the WG decides.

**Comment by emilio** [comment]
cc @tabatkins, in case you have any opinion on this.

**Comment by lilles** [comment]
See https://github.com/w3c/webcomponents/issues/535

**Comment by tabatkins** [comment]
I have no particular opinion, as I've never used `title` on a stylesheet and don't really understand it.  The conclusion from the thread that @lilles linked makes sense to me.

**Comment by rniwa** [comment]
This was previously discussed at https://github.com/w3c/webcomponents/issues/391

I guess we had a consensus that style element inside a shadow tree shouldn't affect the preferred stylesheet of the document, we didn't agree on whether `title` is ignored inside a shadow tree or not.

**Comment by lilles** [comment]
@rniwa I think we agreed on that in https://github.com/w3c/webcomponents/issues/535 for which the spec edit was made.

**Comment by rniwa** [comment]
Ok, sounds like we just have a bug in WebKit then. It appears that this is already addressed by https://github.com/whatwg/html/pull/1675 ?  Perhaps CSS OM spec should have a note referring there.

**Comment by emilio** [comment]
Yeah, agreed this is not a lack of definition. Probably the SVG spec should also say the same. In any case, I'll leave this open to add a note to CSSOM.

**Comment by emilio** [comment]
I'm adding WPTs for this in https://bugzilla.mozilla.org/show_bug.cgi?id=1447009, fwiw.
