### ISSUE TITLE
[css-animations] Change AnimationEvent 'elapsedTime' parameter to double?

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/csswg-drafts#2651]
Currently elapsedTime is a float: https://drafts.csswg.org/css-animations/#dom-animationevent-elapsedtime

elapsedTime, of type float, readonly , of type float, readonly
The amount of time the animation has been running, in seconds, when this event fired, excluding any time the animation was paused. The precise calculation for of this member is defined along with each event type.

But the web-idl spec says: https://heycam.github.io/webidl/#idl-float

Unless there are specific reasons to use a 32 bit floating point type, specifications should use double rather than float, since the set of values that a double can represent more closely matches an ECMAScript Number.

Is there a good reason we're using float for AnimationEvent?

**Comment by stephenmcgruer** [comment]
FYI @birtles

**Comment by birtles** [comment]
I don't know of any. This predates my involvement in the spec.

**Comment by birtles** [comment]
This was fixed by 60876441cad93aab6b4ec8a4c0419a5b68dc2460.
