### ISSUE TITLE
[css-images-4] image-set 1x equivalence

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#2653]
Would an `image-set()` with a single `1x` image be equivalent to not using `image-set()` to begin with? Or is there a scenario where a browser should not meet the `1x` threshold?

```pcss
header {
  background-image: image-set(url("image@1x.png") 1x);
}
```

In other words, presuming the above code, is there a scenario where a browser supporting `image-set` would not attempt to use `image@1x.png`?

**Comment by tabatkins** [comment]
> Would an image-set() with a single 1x image be equivalent to not using image-set() to begin with?

Yes.

`image-set()` never fails to choose an image; the `<resolution>` just helps determine *which* of the images is chosen. (And then affects determining the intrinsic size from the pixel width/height.)

**Comment by jonathantneal** [comment]
Thank you, @tabatkins ! That resolves my issue. Closing!
