### ISSUE TITLE
[css-flexbox][css-grid] Floor outer sizes at zero where needed

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2655]
There are a number of places where we use the outer size (margin-box size) of a box in layout calculations, e.g. in Flexbox and Grid Layout. We should make sure that we're flooring it at zero in the places where it needs to be floored (and not in the places where it needs to be not floored).

**Comment by tabatkins** [comment]
@fantasai and I independently reviewed Flexbox, and think all the outer references are either clamped appropriately or don't need to be clamped (and added a note about it *not* being clamped in one spot), so I'm removing the flexbox tag.

**Comment by fantasai** [comment]
Ran an audit over grid. I don't think there was much to do since the tracks get floored at zero to begin with.

**Comment by fantasai** [comment]
Ran an audit over grid wrt inner vs outer sizes also.
