### ISSUE TITLE
[css-display] Define default display types in the right section

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2658]
It's not a big deal, but I think it's a bit confusing that the default inner display type value is defined in [Outer Display Roles for Flow Layout](https://drafts.csswg.org/css-display-3/#outer-role), and the default outer display type value is defined in the [Inner Display Layout Models](https://drafts.csswg.org/css-display-3/#inner-model). I think the opposite would make more sense.

**Comment by fantasai** [comment]
Oy. There's a good argument for either way: the argument for leaving it as-is, is that in the section defining a particular set of keywords, it's more clearly explained that keyword means in isolation. Probably if the default was simple, I'd lean towards accepting your change... but the "default" outer display type used when an outer display type isn't specified is actually dependent on which inner display type was specified. (It usually implies 'block', but 'ruby' implies 'inline'.)

Also, outer display types are only implied if an inner display type is specified and vice versa: if a layout-internal display type is specified, there is no default outer display type or inner display type, as the concept doesn't apply. Ditto 'none' and 'contents'.

... So altogether, I'm leaning towards rejecting this editorial change. I'll check with @tabatkins, though.

**Comment by tabatkins** [comment]
Hmmm, I think I agree with @fantasai. While it's definitely true that we usually define what an omitted production means in the section that defines the production, here I think it's clearer to define what a keyword by itself means (and thus, what the other keyword will default to). The two productions are intricately linked, not largely independent as most productions are, so defining them in isolation ("block means X, inline means Y, omitted means either block or inline, depending on this other thing") isn't as fruitful.

**Comment by Loirooriol** [comment]
Your arguments are reasonable, I'm fine with no change.
