### ISSUE TITLE
[css-sizing-3] min-content/max-content on input element

### ISSUE THREAD

**Issue by o-t-w** [w3c/csswg-drafts#2663]
When using an element with contenteditable, it is fairly easy to make its box be the size of its contents. I would like to do the same thing with a form input element. I have tried min-content/max-content/fit-content in Chrome and Firefox but they don't respect the width of the text. I had a look through the spec and couldn't tell if this was compliant. If it is spec compliant, I am going to say that it is very annoying behaviour.

**Comment by jonjohnjohnson** [comment]
Relevant -> https://github.com/w3c/csswg-drafts/issues/2141

**Comment by fantasai** [comment]
This was added as part of #2141; please feel free to file bugs on implementations as needed. :)
