### ISSUE TITLE
[css-ui-4] Require link-pointer when pointer is over a link

### ISSUE THREAD

**Issue by tobireif** [w3c/csswg-drafts#2664]
It would be great if the CSS spec would specify that the pointer must get rendered as link-pointer (as if value "pointer" is set) (shown eg as a hand/glove) when it is hovering over a linked area (eg an "a" element in SVG).

https://drafts.csswg.org/css-ui-3/#cursor

https://bugs.chromium.org/p/chromium/issues/detail?id=841146

**Comment by frivoal** [comment]
This should be solved by an addition in the UA stylesheet. I am not opposed to saying so in the CSS-UI spec, but it seems to me that the SVG spec is a better place for that.

Thoughts? (cc @AmeliaBR )

**Comment by AmeliaBR** [comment]
I agree that it makes sense to add to [the SVG user-agent stylesheet](https://svgwg.org/svg2-draft/styling.html#UAStyleSheet). There is a similar rule in [the HTML user-agent stylesheet](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3). Some but not all browsers apply the rule to SVG links.

@tobireif Could you file the matching issue on the SVG repo, linking back here?

But the concept of "link" is more generic than any particular element namespace. So, it also makes sense to consider whether a general rule is appropriate in CSS UI.

**Comment by frivoal** [comment]
I am not too enthusiastic about listing in css-ui all the possible types of hyper links that exist in all possible types of markup (there are not that many popular markup languages, but still), but I think a general statement like "UAs must apply `cursor: pointer` to hyperlinks for all supported document formats via the UA stylesheet, using a normal (i.e. not !important) declaration" would be OK, and then individual markup languages like SVG would make the more specific requirement about what that means exactly for them.

**Comment by frivoal** [comment]
Agenda+ to get confirmation from the CSSWG that the addition of that sentence is OK:

> UAs must apply `cursor: pointer` to hyperlinks for all supported document formats via the UA stylesheet, using a normal (i.e. not !important) declaration.

**Comment by tobireif** [comment]
Thanks Florian!

**Comment by AmeliaBR** [comment]
> I am not too enthusiastic about listing in css-ui all the possible types of hyper links that exist in all possible types of markup

I was assuming that the guidance could build on the `:link` and `:visited` pseudoclasses.  This is what the HTML user agent stylesheet uses. I assume the difference between browsers is whether they restrict the rule by element namespace or not.

But Florian's open-ended prose description works. [The Selectors spec](https://drafts.csswg.org/selectors-4/#location) doesn't really bother trying to define what is and isn't a hyperlink, either.

**Comment by frivoal** [comment]
Test pull request over here: https://github.com/web-platform-tests/wpt/pull/11396

**Comment by tobireif** [comment]
Thanks all!
