### ISSUE TITLE
[css-values] Resolution of math functions

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2665]
From https://drafts.csswg.org/css-values-4/#calc-notation,

> A math function can be used wherever `<length>`, `<frequency>`, `<angle>`, `<time>`, `<percentage>`, `<number>`, or `<integer>` values are allowed.

From https://drafts.csswg.org/css-values-4/#calc-type-checking,

> A math function has a resolved type, which is one of `<length>`, `<frequency>`, `<angle>`, `<time>`, `<percentage>`, `<number>`, or `<integer>`.

From https://drafts.csswg.org/css-values-4/#type-checking-exprs,

> A math function resolves to `<length>`, `<angle>`, `<time>`, `<frequency>`, `<resolution>`, `<flex>`, or `<percentage>` according to which of those productions its type matches.

Why are `<number>` and `<integer>` in #1 and #2 but not in #3?

Why are `<resolution>` and `<flex>` in #3 but not in #1 nor #2?

Is it necessary to repeat this list three times?

**Comment by tabatkins** [comment]
> Why are <number> and <integer> in #1 and #2 but not in #3?

Accident.

> Why are <resolution> and <flex> in #3 but not in #1 nor #2?

For flex, we have <https://github.com/w3c/css-houdini-drafts/issues/734> still open.

I... actually didn't realize calc() wasn't defined over `<resolution>`. I'll add it to that issue.

> Is it necessary to repeat this list three times?

No, I need to do some more cleanup.

**Comment by tabatkins** [comment]
Fixed the first.

Went ahead and edited the spec to fix the second, tho technically we do need the resolution to make it valid.  But I think it's a foregone conclusion.

Fixed the third by removing one of the lists, along with a lot of now-redundant instructions for how to determine the type of a math function.  Still need the other two, as far as I can tell.
