### ISSUE TITLE
[css-backgrounds-3] background-size with "<length-percentage> auto" and gradient image is not interoperably implemented

### ISSUE THREAD

**Issue by ChumpChief** [w3c/csswg-drafts#2675]
Per https://drafts.csswg.org/css-backgrounds-3/#valdef-background-size-length-percentage

> The first value gives the width of the corresponding image, the second value its height. If only one value is given the second is assumed to be auto.
> A percentage is relative to the background positioning area.
> An auto value for one dimension is resolved by using the image’s intrinsic ratio and the size of the other dimension, or failing that, using the image’s intrinsic size, or failing that, treating it as 100%.

Since gradients have no intrinsic size (per https://drafts.csswg.org/css-images-3/#gradients), I believe Firefox has the spec-compliant rendering on this test page:
https://jsfiddle.net/mecvebx8/

Edge/Chrome/Safari currently produce the same non-spec-compliant rendering.  I don't have a particular preference for either behavior, but would like to reach full interoperability between implementers with a matching spec.  Do we all agree that the spec/FF behavior is the correct/desirable behavior, and are other implementers open to making the change to match?  We can make the change in Edge if others are also on board.

The same discrepancy in implementation also exists for mask-size.

**Comment by tabatkins** [comment]
Assuming that Firefox is treating the middle case like the last one (100%), then yeah, it's correct and the other browsers are wrong.

**Comment by TalbotG** [comment]
Issue 711489: background-size with only one [ <length | <percent> ] value with gradient incorrectly rendered
https://bugs.chromium.org/p/chromium/issues/detail?id=711489

Bug 170834: background-size with 2nd value is 'auto' and the image has no intrinsic size and no intrinsic ratio incorrectly rendered 
https://bugs.webkit.org/show_bug.cgi?id=170834

with 6 available tests

**Comment by fantasai** [comment]
Proposal is to close this with no change to spec, requesting WebKit and Blink to fix to match Firefox + spec.

**Comment by TalbotG** [comment]
Issue 935057: background-size with only one [ `<length | <percent>` ] value with SVG image with no intrinsic ratio incorrect
https://bugs.chromium.org/p/chromium/issues/detail?id=935057
