### ISSUE TITLE
[css-grid] Clarification about <auto-track-list> and <line-names> syntaxes

### ISSUE THREAD

**Issue by lahmatiy** [w3c/csswg-drafts#2676]
Spec: https://drafts.csswg.org/css-grid/#typedef-auto-track-list

The spec defines `<auto-track-list>` syntax as following:
```
[ <line-names>? [ <fixed-size> | <fixed-repeat> ] ]* <line-names>? <auto-repeat>
[ <line-names>? [ <fixed-size> | <fixed-repeat> ] ]* <line-names>?
```

I suppose `|` combinator is missed in that syntax.

`<line-names>` is defined as following:
```
'[' <custom-ident>* ']'
```

According to this syntax, an empty brackets is a valid value for the `<line-names>`. It looks odd, I guess `*` multiplier should be replaced for `+`.

**Comment by tabatkins** [comment]
> I suppose | combinator is missed in that syntax.

No, it's written correctly. The point is that you can have *one* `<auto-repeat>`, but then as many `<fixed-repeat>`s as you want before/after it.

> According to this syntax, an empty brackets is a valid value for the <line-names>. It looks odd, I guess * multiplier should be replaced for +.

I don't see anything particularly wrong with allowing `[]` there. Yeah, it defines no line names, but that seems clear. And allowing it has some good points: it can make it slightly easier for code-generators (don't need to test for the presence of line names and manually omit the `[]` when generating a template); and it can help visually line things up if people are naming lines between *most* of the tracks and want the symmetry of having an empty `[]` calling out that there's no named lines there.
