### ISSUE TITLE
[css-fonts-4] Confusing sentence about the color-0 descriptor

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2678]
See https://www.w3.org/TR/css-fonts-4/#palette-integer-desc

I don't understand the sentence (referring to 'color-<integer>' descriptors):

> These descriptors are zero-indexed, so the initial palette in the font is represented by the color-0 descriptor.

In what sense does the 'color-0' descriptor "represent the initial palette in the font"? Surely it simply refers to the color at index 0 in the palette being specified. Or am I totally missing something?

**Comment by svgeesus** [comment]
Yes, the palette selection is done by the `base-palette` descriptor. This text is about individual palette entries in the selected palette.

So that should be something like 

>  so the color specified by the first palette entry in the selected palette is overidden by the color-0 descriptor.

(The term `palette entry` taken from the [CPAL spec](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal) )

**Comment by litherum** [comment]
Yeah, I didn’t want to use the word “first” because I thought that would be confusing. I’m happy to clarify the sentence if we can find the right language.

**Comment by svgeesus** [comment]
@litherum I see your point but, from the CPAL spec:

> The **first** color record of each palette is provided in the colorRecordIndices array.

> The **first** palette, palette index 0, is the default palette

> Offset from the beginning of CPAL table to the **first** ColorRecord.

> Index of each palette’s **first** color record in the combined color record array.

So I think it is okay to use first here, as the CPAL spec uses it the same way.

**Comment by svgeesus** [comment]
Better suggested wording (re-using CPAL terminology):

> so the color specified by the first color record in the selected palette is overidden by the color-0 descriptor.
