### ISSUE TITLE
[css-lists] How do counters and Shadow DOM interact?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2679]
Should counters inherit via the flattened tree or the document tree? The spec seems to indicate the second, but usual CSS inheritance works in terms of the first.

It should definitely mention something other than "document order", since elements inside shadow trees do not belong to a document.

cc @upsuper

**Comment by tabatkins** [comment]
That is an *excellent* question.

And hm, that suggests we need to revisit our use of "document order" in other specs as well - if the shadow host is `display:grid`, for instance, we need a clear answer as to what order elements are auto-positioned.

(I think for cases likes Grid and Flexbox it's clearly the flat tree.  Counters, acting as pseudo-inheritance, are less obvious.)

**Comment by dbaron** [comment]
Shouldn't basically everything in CSS that happens after selector matching (i.e., inheritance or later) operate solely on the flattened tree?  It seems like shadow DOM has split an existing concept and we need to split our references to that concept... but people shouldn't interpret failure to update specs as signaling intent (or suggesting to implement the wrong behavior).

**Comment by dbaron** [comment]
(deleted previous incorrect comment that I made; my head is still stuck in the XBL model where inheritance operates on the flattened tree... which I guess isn't true for Shadow DOM?)

Two thoughts:
* shadow DOM has split an existing concept into two (and continued using the old name for one side of the split, which is perhaps a mistake).  People shouldn't read much into existing specs that predate the split referring to the original term as taking a position on which side of the split is the right one.
* I think counters and quotes should do the same thing; they're defined pretty similarly.

**Comment by tabatkins** [comment]
>  which I guess isn't true for Shadow DOM?

Correct, inheritance still works on the original DOM tree, with shadow trees appended. (In particular, light-dom children of a shadow host inherit directly from the shadow host, not whatever `slot` they might get distributed to.)

> I think counters and quotes should do the same thing; they're defined pretty similarly.

Agreed. Both of them are just manually implementing a variant inheritance.

**Comment by AmeliaBR** [comment]
I agree that for layout and rendering, "document order" should always be the flattened tree order.  Maybe it's worth adding a generic interpretation guideline somewhere to that effect, until all specs can be updated to newer language?  Somewhere in [CSS Scoping](https://drafts.csswg.org/css-scoping-1/), maybe?

On the specific issue:

Counter incrementing already skips over un-rendered elements (`display: none`), meaning it operates at rendering time, not on the raw DOM. So incrementation would probably need to operate on the flattened tree.

I'm inclined to suggest that counter resets and nested scope should also work in the flattened tree.  But I'm also having a hard time coming up with practical examples of it making a difference.  Shadow trees can only (currently) "slot" DOM elements that are direct children of the custom element, so you can't pull an element outside of a nesting context (all of the element's DOM ancestors will also be flattened tree ancestors). You _can+ insert it into new nested structures (adding new shadow elements between the slotted element and its DOM parent), but that would only make a difference to nested counters if the shadow elements reset the same counter.

Which brings up another question: how are counter names scoped when it comes to shadow trees?  If you have counters in the scoped stylesheet and counters in the main document stylesheet, and they happen to have the same name, would the values get intermingled?

Another possible complication: if counter resets operate on the rendering tree, wouldn't that also prevent using counter resets on `display: contents` elements, providing unexpected results if you applied `display: contents` to a  `<ol>`?

**Comment by emilio** [comment]
> Correct, inheritance still works on the original DOM tree, with shadow trees appended. (In particular, light-dom children of a shadow host inherit directly from the shadow host, not whatever slot they might get distributed to.)

Wait, what? Inheritance does definitely happen on the light tree, as this test-case shows:

```html
<!doctype html>
<div id="host" style="color: red">
  <span>I should be green.</span>
</div>
<script>
  host.attachShadow({ mode: "open" }).innerHTML = `<slot style="color: green"></slot>`;
</script>
```

It shows red in older chromium versions because `<slot>` wasn't part of the flat tree there.

**Comment by tabatkins** [comment]
Oh whoops, I'm totally misremembering my own dang spec text. Yeah, it works thru the flattened tree.

That makes this easy then - counters (and quotes) work thru the flattened tree as well.

I do say this non-normatively in <https://drafts.csswg.org/css-scoping/#shadow-gloss>:

> However, the shadow tree, when it exists, is used in the construction of the flattened element tree, which CSS uses for all purposes *after* Selectors (including inheritance and box construction).

**Comment by MatsPalmgren** [comment]
ping @fantasai It seems we have consensus here that counters (and quotes) works thru the flattened tree. Can we have the css-lists spec updated please?

**Comment by fantasai** [comment]
@MatsPalmgren Done in 3f70d30b33f29992133f128230301545f3eb8be2
