### ISSUE TITLE
[cssom] Consider removing setPropertyValue / setPropertyPriority.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2680]
They haven't been implemented anywhere even though they're in the spec since forever, and I'm trying to get every UA to do the spec'd thing in setProperty and finally be interoperable here.

They'd also do the wrong thing with logical properties, etc.

So it would be nice if, lacking a good use-case for this and implementation interest, this was removed from the spec.

This is conceptually something that could be done, however we'd end up with a bit of pain trying to define how it should interact with mutation observers and such, which is something that no UA has implemented interoperably in setProperty until lately.

@zcorpan @dbaron wdyt?

**Comment by zcorpan** [comment]
OK with me. They were added to give web developers an opt in to saner behavior than `setProperty`, by request from @dbaron, iirc, but if they haven't been implemented then they should be removed.

**Comment by emilio** [comment]
I think you can opt-in into @dbaron's proposed behavior now with `setProperty('foo', 'value', getPropertyPriority('foo'))` after #1898, and they would have the same problem as #1898 as written, so I think we should remove.
