### ISSUE TITLE
[css-grid-1] gCS() of grid-row-start/etc properties should return used values?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#2681]
In #1465, an author requested a way to find out what grid area a grid item ends up occupying, after placement.  This seems like a reasonable request!  There also seems to be a straightforward way to achieve it - specify that the *used values* of the grid-row-start/etc properties are the line numbers the item actually lands on, and then specify that gCS() returns the used value of those properties.

(We already have a precedent of several grid-related properties returned used valued for gCS().)

Browser compat on what's returned for those properties today seems to be relatively consistent on returning the specified values, so this would be breaking compat. Whether that's important or not is unclear.

-------

The rest of the requests in #1465 (finding out how many rows/columns are in the implicit grid, and finding out what items overlap a given area) can both be determined from this one change, as you can just iterate over the grid items and build up a map of where they live yourself. We shouldn't need to add any API surface for those.

**Comment by emilio** [comment]
cc @MatsPalmgren

**Comment by fantasai** [comment]
We should put an issue note in the draft though.

**Comment by MatsPalmgren** [comment]
> Do impl preserve that info after layout? not sure they do

Gecko: no we don't, fwiw.

What value should be returned for `auto` on a grid-aligned abs.pos. child?

Note: returning used values means we have to flush any pending style / layout changes to get the correct value.  This can lead to performance issues.

**Comment by fantasai** [comment]
> What value should be returned for auto on a grid-aligned abs.pos. child?

I think the only sensible thing to do would be to return `auto`, since nothing else would make sense.

> Note: returning used values means we have to flush any pending style / layout changes to get the correct value. This can lead to performance issues.

This is true if the author pulls gCS on e.g. `grid-template-columns` as well, though, right? We're already returning used styles for that.

**Comment by fantasai** [comment]
Agenda+ to check in with implementers on this issue, since it's been ~6 months.

**Comment by fantasai** [comment]
Note this means that if authors want this information exposed, if we don't report this info through gCS() we'll need to come up with a specialized API just for Grid.

**Comment by Peppertop** [comment]
Thanks for discussing this. It seems odd to me that there's a part of the layout engine that can automatically place items, but then no practical way to find out about those placement choices. gCS() would seem to have been a fairly lightweight way to expose that information (compared with a dedicated API), so it's a shame there's no traction there.
