### ISSUE TITLE
[web-animations-1] Should setting the startTime of a play-pending animation to `null` have side effects?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2691]
Typically setting the start time of an animation should cancel any pending tasks. This provides applications with a way to synchronously seek/sync animations. Furthermore, by setting the start time to `null` applications can perform a synchronous pause.

However, if an animation is play-pending its start time will already be unresolved (`null`).

If the animation is play-pending when script sets the start time to `null` what should happen?

a. The change is redundant and should be ignored. (Seems intuitive from a JS point of view, redundant changes have no side effects.), _or_
b. The pending play task is canceled. (Currently speced behavior. Allows applications to perform a synchronous pause even in the play-pending state.)

i.e.

```js
const anim = elem.animate(...);
// anim.pending === true
// anim.startTime === null
// anim.currentTime === 0

anim.startTime = null;
// Is the animation still play-pending here?
```

(Firefox actually does (a) as an optimization but the spec says we should do (b) and I'm wondering which to fix.)

/cc @stephenmcgruer @flackr @graouts @dadaa

**Comment by birtles** [comment]
Interesting, I was actually leaning towards (b) since it gives author consistent behavior -- setting `startTime` to `null` always does a synchronous pause whether you're pending or not.

**Comment by stephenmcgruer** [comment]
In which case something to discuss at our next sync I think! @graouts - any opinion?

**Comment by birtles** [comment]
Discussed this yesterday with @graouts @stephenmcgruer @flackr and agreed that we should go with (b), i.e. no change to the spec.

Part of the reasoning is that this not only makes it easy to synchronously pause without having to check the pending state, but it is also consistent with the fact that setting the `startTime` always finishes a pending-play, regardless of whether or not the value you set is `null`.

Firefox will be updated in [Mozilla bug 1478213](https://bugzilla.mozilla.org/show_bug.cgi?id=1478213) where I will also add a test for this.

**Comment by birtles** [comment]
A test for this is added in: https://github.com/web-platform-tests/wpt/pull/12195
