### ISSUE TITLE
[css-scrollbars] Scrollbar properties on the root element should be propagated to viewport

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2696]
Scrollbar properties on the root element should be propagated to viewport, similar to what we do for overflow properties. Otherwise, there would be no way to style scrollbars of viewport.

**Comment by tantek** [comment]
Thanks &lt;https://github.com/upsuper&gt; and good call. Do you have any preferred wording for this, or shall I clone language from &lt;https://drafts.csswg.org/css-overflow/#overflow-propagation&gt; ?

(Originally published at: http://tantek.com/2018/143/t2/)

**Comment by upsuper** [comment]
I think we only need
> UAs must apply the scrollbar-* values set on the root element to the viewport.

Sentences for overflow after that are basically for webcompat reason, which we shouldn't take. That's not something we want to spread.

Maybe we should add a note to mention that this is different from overflow that values on that `<body>` wouldn't be propagated to viewport.

**Comment by tantek** [comment]
&lt;https://github.com/upsuper&gt; your suggested text makes sense to me, and I have also added an explicit note so implementers hopefully don’t accidentally propagate body to viewport.

Please take a look at the prose after the property value table at &lt;https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color-properties&gt; and if the updates are sufficient to resolve this issue, go ahead and close.

(Originally published at: http://tantek.com/2018/143/t5/)

**Comment by upsuper** [comment]
The spec currently only has scrollbar color properties so far, but I think this should probably apply to any future scrollbar properties as well (e.g. something controlling the width of scrollbar)? We may want to put it in an independent section or so, I guess...

But the current wording is enough for resolving this issue so I'm going to close it for now.
