### ISSUE TITLE
[css-grid] Applying 'align-content' content distribution to row estimation in step 1 in Grid Sizing algo

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2697]
Follow-up from #2557.

The [row size estimation for step 1](https://drafts.csswg.org/css-grid/#algo-overview) mentions "if any row with a definite max track sizing function had that size and all other rows were infinite". I tend to think this implies that if _all_ rows have a definite max track sizing function, and the container has a definite block-size, that `align-content` should be applied. @javifernandez' example in #2557:
```html
<div style="display: inline-grid; grid-template-rows: 50px 50px; height: 200px;  font: 20px/1 Ahem; justify-content: start; align-content: space-between;">
   <div style="grid-row: span 2; background: cyan; writing-mode: vertical-lr">XXX XX X XX X XXX</div>
</div>
```

should render exactly the same as if we add `grid-row-gap:100px`:
```html
<div style="display: inline-grid; grid-template-rows: 50px 50px; grid-row-gap:100px; height: 200px;  font: 20px/1 Ahem; justify-content: start; align-content: space-between;">
   <div style="grid-row: span 2; background: cyan; writing-mode: vertical-lr">XXX XX X XX X XXX</div>
</div>
```

So I propose we add `align-content` content distribution for this specific case (all rows have definite max size) to the row estimation heuristics for step 1.

**Comment by fantasai** [comment]
Sounds good to me. Agenda+ for objections. :)

**Comment by fantasai** [comment]
Fix checked in. Let me know if there are any errors!
