### ISSUE TITLE
[css-logical] Logical caption-side issues

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2698]
CSS Logical says

> The existing `top` and `bottom` values are idiosyncratically redefined as assigning to the block-start and block-end sides of the table, respectively.

What about `left` and `right`? According to [CSS Tables](https://drafts.csswg.org/css-tables-3/#caption-side-property), Gecko is the only implementation, and there they seem to refer to what would be the inline-start and inline-end sides of the table if `direction` was `ltr`. They don't refer to the physical left and right.

> The mapping on this property uses the writing mode of the element’s containing block (that is, the table wrapper box).

But CSS Tables doesn't say that the `writing-mode` value of the table element is used in the table wrapper box, this means it's used in the table grid box instead. However, setting `writing-mode` on the table element affects the position of its caption on both Firefox and Chrome.

Also, the spec says "uses the writing mode". Writing Modes spec explains this depends on all `writing-mode`, `direction`, and `text-orientation`, but I think it's easy to misunderstand and believe that only `writing-mode` is included. I would explicitly mention all properties, just like in most other sections.

**Comment by fantasai** [comment]
CSS Tables does not correctly define the way properties are applied to tables. That's a general problem with that spec... in general, all inheritable properties are applied to the table wrapper box.

Added definitions for left and right in d9196916a5351d59b8dc34be90241c55985dc7c1
