### ISSUE TITLE
[css-inline-3] Improve list of properties applying to initial letters

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2700]
The list of properties that apply to initial letters seems unnecessarily restrictive. E.g. fill/stroke should apply. What restrictions are actually necessary?

**Comment by fantasai** [comment]
@dauwhe and I are thinking to say that any properties that apply to an inline box also apply to an initial letter, except for `vertical-align` and friends.

**Comment by frivoal** [comment]
You need to exclude `font-size` as well:
* We're calculating the size of the initial letter differently anyway
* That's what safari does (except for a bug where `font-size:0` makes the whole initial letter disappear)
* It's useful to set the font-size to a large value, to be used as a fallback if the initial-letter property is not supported, without having that interfere somehow with the initial-letter

**Comment by fantasai** [comment]
'font-size' affects how ems are calculated, though, so it has to apply. We don't want to change the length computation rules for initial letters.

**Comment by emilio** [comment]
Why does forbidding specifying font-size in `::initial-letter` require changing length computation rules? I'd assume inheritance would work normally. Anyway no big deal, was just curious.

**Comment by frivoal** [comment]
I guess it can be described as applying, then we add a note clarifying that it has no effect on the sizing of the initial letter itself, only on font-relative length units.
