### ISSUE TITLE
[css-flex] Direction, flexbox, and auto-generated text wrapper

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#2702]
Is there a good reason why Chrome and Firefox render the two last elements of this test case differently?

> https://codepen.io/anon/pen/Gdboby

To me it looks like the two scenarios are exactly the same.

Raising because of https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17629262/

cc @fantasai @tabatkins

**Comment by tabatkins** [comment]
Yeah, this doesn't make sense. The anonymous wrapper around line 3 should be treated equivalently to the explicit span in line 4, and produce the same results. Looks to be a bug.

**Comment by MatsPalmgren** [comment]
I filed a bug on Gecko [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1465990).

**Comment by tabatkins** [comment]
And I filed https://bugs.chromium.org/p/chromium/issues/detail?id=848504

**Comment by FremyCompany** [comment]
Sounds good, thanks for tracking that.
