### ISSUE TITLE
[css-inline] Initial letter, sizing, and overflow

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2703]
(this is a follow up from #947)

1. How does an initial letter contribute to the min-content intrinsic size?

   Suggestion:
   * The exclusion area's enlargement caused by `initial-letter-wrap: grid` doesn't count
   * We should count from the start edge of the containing block content area to the end border edge of the initial letter. both in the inline and block directions. we could go to the end margin edge, but on the end side it is a mean to separate from the surrounding content, and if there's no content, there's nothing to separate from.

2. If the containing block is not tall / wide enough, does the initial letter cause scrollable overflow?

   My suggestion, linked to the answer to the previous question:
  
   Only to the extend that the (end side) border edge of the initial letter overflows. Overflow of the end side margin or `initial-letter-wrap: grid`-induced exclusion area is not useful to scroll to.

**Comment by fantasai** [comment]
I think for intrinsic sizing, we consider the margin box of the initial letter.
For overflow, we consider its border box.
This is what typically happens for boxes, anyway.

**Comment by fantasai** [comment]
Intrinsic size contributions use the outer edges: https://drafts.csswg.org/css-sizing-3/#contributions
Scrollable overflow uses the border edges: https://drafts.csswg.org/css-overflow-3/#scrollable

I don't think we need to make any edits to css-inline-3, unless css-overflow-3 later adds some kind of exceptional behavior for inline boxes, in which case we might need clarifications here.

**Comment by frivoal** [comment]
It's not exactly what I had in mind, but it's close enough, and consistency with the rest of the box model outweighs any possibly nitpick I might have had.
