### ISSUE TITLE
[css-inline-3] Should initial-letter apply to inside ::marker pseudos?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2705]
We allow `initial-letter` to apply to the first inline-level box in a block container, should that include `::marker` elements that are formatted as `list-style-position: inside`?

**Comment by frivoal** [comment]
@dauwhe do you have examples either way?

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/ed91e7a82d58095dfa5e3436ef4dc96f98119f76
