### ISSUE TITLE
[css-sizing] Incorrect use of the word "compute" in definition of intrinsic keyword values

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2708]
The [min-content](https://drafts.csswg.org/css-sizing-3/#valdef-width-min-content) and max-content values are defined as "otherwise compute to the property’s initial value".  I read that as "otherwise (in the block-axis) the computed value of this property is the property’s initial value".  This is not what UAs actually implement and would be problematic to implement since it would introduce a dependency on the `writing-mode` property.  For example:

```html
<div style="height: min-content">
  <div  style="height: inherit"></div>
</div>
```
The spec suggest that the inner element should inherit the value `auto`.  This seems wrong to me, it should inherit the value `min-content` (and this is what UAs currently implements).

I suggest you reword it as "otherwise the _used value_ is the property’s initial value".

**Comment by fantasai** [comment]
Well, the used value is a length, so we'll have to word it some other way...

**Comment by tabatkins** [comment]
Agenda+ to confirm that (a) the behavior change is desirable, and (b) that our edits (switching to "behaves as") are satisfactory.
