### ISSUE TITLE
different default values for `flex-grow` and `flex`

### ISSUE THREAD

**Issue by xianshenglu** [w3c/csswg-drafts#2710]
[flex-grow](https://drafts.csswg.org/css-flexbox-1/#flex-flex-grow-factor)

> This <number> component sets flex-grow longhand and specifies the flex grow factor, which determines how much the flex item will grow relative to the rest of the flex items in the flex container when positive free space is distributed. **When omitted, it is set to 1.**

There is an error :

**When omitted, it is set to 0.** not 1.

As you can see here [flex-grow](https://drafts.csswg.org/css-flexbox-1/#propdef-flex-grow)

**Initial: | 0**

**Comment by SelenIT** [comment]
It looks that `flex-grow` as a separate property has different default value than `flex-grow` as a `flex` shorthand component. If the `flex` property has only `flex-basis` component (e.g. `flex: 100px`), browsers interpret this as `flex: 1 1 100px`, not `flex: 0 0 100px`.

**Comment by xianshenglu** [comment]
Well, I find out. [Here](https://drafts.csswg.org/css-flexbox-1/#flex-grow-property)

> Authors are encouraged to control flexibility using the flex shorthand rather than with flex-grow directly, as the shorthand correctly resets any unspecified components to accommodate common uses.

So, This means that if you use `flex` and don't specify `flex-grow`'s value,the  `flex-grow` should be 1 according to [flex-property](https://drafts.csswg.org/css-flexbox-1/#flex-property).

And if you don't use `flex` and  `flex-grow` ,the value of `flex-grow` should be 0 according to [flex-grow](https://drafts.csswg.org/css-flexbox-1/#propdef-flex-grow)

Both cases don't specify the value of `flex-grow` . However , we get different default value because of the definitions above. That's really weird.

@SelenIT ,You are basically right. However, the same thing doesn't happen to `flex-shrink` which means there is a little error in the example you  proposed.

Anyway, Is that reasonable for different default value?

**Comment by tabatkins** [comment]
Yes, the different default value is definitely intentional; when you set something like `flex: 200px`, you want it to start at 200px and grow, so it needs to default to 1.  But we want flex items to default to not growing at all, for simplicity, so the initial value is `0`.
