### ISSUE TITLE
[css-fonts] list of generic font-family keywords is out of date

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2721]
In section [2.1.1 Generic Font Families](https://drafts.csswg.org/css-fonts-4/#generic-font-families), there are a total of 9 generic family keywords. However, the last four (`system-ui`, `emoji`, `math`, `fangsong`) are missing from the list given in the definition of [`<generic-family>`](https://drafts.csswg.org/css-fonts-4/#generic-family-value) just a little earlier.

Are the four new values considered stable enough for implementations to go ahead and support them?

**Comment by svgeesus** [comment]
Thanks @jfkthame, fixed.
