### ISSUE TITLE
 Add margin to ScrollIntoViewOptions

### ISSUE THREAD

**Issue by davidbukacek** [w3c/csswg-drafts#2730]
Alignment to the edge of the element may not always be fully desirable. Therefore, it would be good if we could affect the position by specific margin.

Margin would work on a similar principle as rootMargin of the IntersectionObserver method (https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/rootMargin)

Possible use
<pre>
element.scrollIntoView({block: 'end', inline: 'end' margin: '0 10px 0 10px'});
element.scrollIntoView({block: 'start', inline: 'start', margin: '50% 0 50%'});
</pre>

Specification: https://drafts.csswg.org/cssom-view/#dom-element-scrollintoview

**Comment by jonjohnjohnson** [comment]
@davidbukacek what are your thoughts on the `scroll-margin` and `scroll-padding` properties described in [css-scroll-snap](https://drafts.csswg.org/css-scroll-snap-1/)? Surely not really programmatic, but might cover the necessity you bring up about "alignment to the edge" not always being desirable?

**Comment by davidbukacek** [comment]
Properties `scroll-margin` and `scroll-padding` looks quite nice.

I have one more question: 

If I want to run some action after finishing the scroll animation, then in the case of setting `behavior: smooth` I have no easy way to know the end of the animation.

It would be nice if the `scroll`, `scrollTo`, `scrollBy `and `scrollIntoView `returns a `Promise`. What do you think?

**Comment by jonjohnjohnson** [comment]
@davidbukacek -> https://github.com/w3c/csswg-drafts/issues/1562
