### ISSUE TITLE
[css-value] Fragment URLs

### ISSUE THREAD

**Issue by CJKu** [w3c/csswg-drafts#274]
https://lists.w3.org/Archives/Public/www-style/2016Jul/0025.html

While implementing fragment urls[1] inside gecko, I have come across a
behavior which can not find definition on the  spec.

When a SVG use element[2] references to a graphic element(located in
another document) with a local-ref url. By referring behavior on most
modern browsers, I think the correct behavior is to resolve the local-ref
url by base of the referenced document.

Here is an example: ref-external.svg uses a rect in ref-resource.svg
**ref-external.svg**
```
<svg>
  <!-- draw in blue -->
  <linearGradient id="grad1 ">
    <stop offset="0.0" stop-color="blue"/>
  </linearGradient>

  <use xlink:href="ref-resource.svg#myrect">
</svg>
```
**ref-resource.svg**
```
<svg>
  <!-- draw in red -->
  <linearGradient id="grad1 ">
    <stop offset="0.0" stop-color="red"/>
  </linearGradient>

  <rect id="myrect" x="200" y="125" width="200" height="125" stroke="none"
fill="url(#grad1)" />
</svg>
```

While rendering **ref-external.svg**, I would expect(can be wrong) seeing a
red rectangle on the screen, since url(#radialGrad1) will be resolved as
  http://.../ref-source.svg#grad1
not
  http://.../ref-external.svg#grad1.

Have clear definition of how resolving local-ref of
an anonymous clones element is super useful.

[1] https://drafts.csswg.org/css-values/#local-urls
[2] https://svgwg.org/svg2-draft/struct.html#UseElement

**Comment by fantasai** [comment]
I think this should be clarified by the SVG spec defining <use>.

**Comment by nikosandronikos** [comment]
@AmeliaBR has a massive PR (#206) waiting to be merged that totally rewrites the sections of SVG 2 that deal with the use element. We'll be discussing the PR this week during the telcon and will hopefully merge after that.

You can see the built spec on this branch:
https://ameliabr.github.io/svgwg/build/publish/struct.html#UseElement

This issue appears to be clarified there in the following text:

>  If the referenced element is in an external file, then all URL references in attributes and style properties must be made absolute (relative to the base URL of the source file) before copying the value to the element instances. The shadow tree itself uses the same base URL as the document that includes it.

**Comment by AmeliaBR** [comment]
Yes, this is exactly the sort of situation I was considering when I added in that requirement.  It will sometimes mean that the URL references points back to the external file instead of to another cloned element in the shadow tree as an author might expect, but the final result should be the same.

@CJKu If you're working on the Gecko implementation, I would be glad to hear your feedback on the proposed new text.  Do leave a comment on the PR (w3c/svgwg#206) if you can think of anything else that is undefined or problematic.

**Comment by fantasai** [comment]
Amelia, does that mean we can close this issue here? :)

~fantasai

**Comment by AmeliaBR** [comment]
Yes, I think we've got it covered.  Close away, @fantasai !

Relevant paragraph of the [SVG 2 editor's draft, soon to be in CR](https://svgwg.org/svg2-draft/struct.html#UseShadowTree):

> <p>
If the <a href="struct.html#TermReferencedElement">referenced element</a> is in an external file,
then all <a href="linking.html#TermURLReference">URL references</a> in attributes and style properties
must be made absolute as described in <a href="linking.html#processingURL-absolute">Generating the absolute URL</a>,
before copying the value to the <a href="struct.html#TermElementInstance">element instances</a>.
The shadow tree itself uses the same document base URL
as the document that includes it.
</p>

**Comment by fantasai** [comment]
Excellent!

**Comment by ByteEater-pl** [comment]
Should be "resource", not "file".
