### ISSUE TITLE
Inferring test suite links

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#2747]
Most of our specs have a nice little panel with test coverage summaries, links to the tests, and also per-section panels with tests for that section.

In pre-bikeshed specs that was done by editing in a script:

```
<script defer="" src="https://test.csswg.org/harness/annotate.js#!css-grid-1_dev/css-grid-1" type="text/javascript"></script>
```
The `.bs` files don't have that script, and don't have anything obvious in the meta from which the link is created. The bikeshed documentation [talks about links to wpt with the &lt;wpt&gt; tag](https://tabatkins.github.io/bikeshed/#testing) but is silent where the test coverage panels magically appear from.

The bikeshed [boilerplate include files for CSS WG](https://github.com/tabatkins/bikeshed/tree/master/bikeshed/boilerplate/csswg) also don't seem to have any template that gets filled in for the test suite links.

And yet, some specs _have tests_, and _don't_ have test coverage panels, and I can't see how to correct that. For example, [Fonts 4 has tests](http://test.csswg.org/harness/results/css-fonts-4_dev/grouped/) and [the spec has no panel](https://drafts.csswg.org/css-fonts-4/).

So what am I missing here.

**Comment by tabatkins** [comment]
The magical test-box that gets put in some specs is based on something in Shepherd and the older separate CSSWG testing system; it has nothing to do with WPT.  @plinss has more details on it.

**Comment by tabatkins** [comment]
Hm, that said, Fonts 4 is definitely in test.csswg.org, and in Shepherd, and [in Bikeshed](https://github.com/tabatkins/bikeshed/blob/master/bikeshed/spec-data/readonly/test-suites.json#L114-L121), so I'm not sure why it wouldn't be generating a panel.

**Comment by tabatkins** [comment]
Oh, it's because "Prepare for TR: yes" is set. I don't emit the test-suite data for TR-bound documents. Just remove that.  (You only need it when manually prepping for TR, or for double-checking ahead of time. Echidna will auto-add it when generating its file without you doing anything.)

**Comment by svgeesus** [comment]
> Oh, it's because "Prepare for TR: yes" is set. I don't emit the test-suite data for TR-bound documents. 

@tabatkins please stop removing that for /TR docments. I have been publishing them with the test panel for over a year now.

**Comment by tabatkins** [comment]
Oh, sure, I was removing it because I thought that's what W3C people would want. ^_^

**Comment by svgeesus** [comment]
> Oh, sure, I was removing it because I thought that's what W3C people would want. ^_^
Webmaster did, at one point, but is more chill about it now and it adds obvious value :)
