### ISSUE TITLE
[css-color] color({num}3,4) "shorthand"/alternate for rgb

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#275]
We should consider a version of color() that doesn't take a profile name and defaults to a version of rgb() but with sensible parameters.

e.g. color(1.0 0 0) is red, or rgb(255, 0, 0)
e.g. color(0 1.0 0 0.5) is 50% transparent green, or rgba(0, 255, 0, 0.5)

Notice we don't have the weirdo mix of 0-255 and 0-1!!

In other words, if the first parameter is a number, the whole thing is a color in sRGB.

**Comment by frivoal** [comment]
I have no strong opinion for or against this. I can see why you may want this, but I don't think the need is that pressing. I'm OK either way.

However, if we do that, I think we should keep the coma between the optional color profile and the parameters, unlike what https://github.com/w3c/csswg-drafts/issues/266 is proposing.

I don't want `color(0 0 1)` to mean blue while `color(O 0 1)` (that's an upper case o) to mean the `0 1` color in the color profile defined by `@profile O { src: url('O.icc'); }`. This would be unambiguous for parsers, but error prone for humans.

If we have a comma in there, `color(0 0 1)` and `color(O, 0 1)` are still sort of close, but far enough in my view.

**Comment by svgeesus** [comment]
> Notice we don't have the weirdo mix of 0-255 and 0-1!!
Yes. This is currently annoying, and gets more weird once people start using 10bit and 12bit components. is 50 50/255 or 50/4096? Keeping it all to a 0.0 ... 1.0 range is clear, bit depth neutral, and has no backwards-compat disadvantages.

**Comment by svgeesus** [comment]
I noticed recently that canvas has two different behaviours: legacy sRGB, which means "this is supposed to be sRGB but eh, just throw the colors at the screen" and sRGB, which means "this really is sRGB, color manage it like any other calibrated colorspace"
I wonder therefore (we haven't got onto conformance criteria yet, but we will) whether rgb() might map to "legacy sRGB" and color() with the default sRGB colorpace map to "sRGB".

**Comment by Crissov** [comment]
There already is consistent `rgba(60%, 70%, 80%, 90%)`, though, which should arguably be equal to `rgb(60%, 70%, 80%, 90%)` or `rgb(60% 70% 80%, 90%)` or`rgb(60% 70% 80% 90%)`.

**Comment by tabatkins** [comment]
> I wonder therefore (we haven't got onto conformance criteria yet, but we will) whether rgb() might map to "legacy sRGB" and color() with the default sRGB colorpace map to "sRGB".

No, CSS colors are color-managed sRGB.

**Comment by svgeesus** [comment]
> No, CSS colors are color-managed sRGB.

Happy to see you agree, I have been asserting that since 1996 and that is what all CSS1, CSS2 say but periodically people like to assert the opposite.

I just mentioned it since we should track what canvas is doing regarding color.

Getting back to the original issue, i agree that the first parameter to color() should be optional and, if omitted, default to sRGB.

**Comment by tabatkins** [comment]
Done.
