### ISSUE TITLE
Add support for a new list counter named 'persian-alpha' [css-persian-alpha]

### ISSUE THREAD

**Issue by Huji** [w3c/csswg-drafts#2753]
The [https://www.w3.org/TR/css-lists-3/#propdef-list-style-type](list-style-type) property accepts several values such as `decimal`, `lower-alpha`, `armenian`, or `persian`.

In Persian, there are two ways in which footnotes are marked: using a numeric counter (similar to 1, 2, 3, ...) or using an alphabetic counter (similar to a, b, c, ...). The former is already part of CSS3 (`list-style-type: persian`). I would like to ask for the latter to also be added.

I have created a JSFiddle at https://jsfiddle.net/a8obup7r/8/ which demonstrates the desired output (try it with a Mozilla browser). Since there are thirty two letters in Persian alphabet, there are also thirty two symbols used.

Note that it is customary for the first one to not be a single letter "ا" but rather a three letter spelled-out name of that letter, ie "الف". Note also that it is customary for the 31st one to not be the letter "ه" in its loose form, but to be the character in its attached form "ھ".

**Comment by tabatkins** [comment]
The set of predefined counter styles is limited just to those that were predefined in CSS 2.1 (which is a pretty arbitrary set), plus a few that were difficult to reproduce with the @counter-style rule.  I don't think implementors are interested in adding new ones.

However, the [Predefined Counter Styles doc](https://www.w3.org/TR/predefined-counter-styles/) is where we moved a ton of other styles that can be written with @counter-style, and they'd be glad to accept additions like this.

**Comment by tabatkins** [comment]
Nits on your @counter-style rule - you used `suffix=" "` with a `=`, rather than a `:`.

Is this really meant to `cyclic`, so the 33rd item gets الف as well? Or should it be `alphabetic`, so the 33rd is <bdi>الفالف</bdi>, then 34th is <bdi>الفب</bdi>, etc?

**Comment by Huji** [comment]
> Nits on your @counter-style rule - you used suffix=" " with a =, rather than a :.
Sorry. Removed. It was not necessary.

> Is this really meant to cyclic, so the 33rd item gets الف as well? Or should it be alphabetic, so the 33rd is الفالف, then 34th is الفب, etc?
Alphabetic is the right way. jsFiddle updated accordingly.

**Comment by Huji** [comment]
> However, the Predefined Counter Styles doc is where we moved a ton of other styles that can be written with @counter-style, and they'd be glad to accept additions like this.

Good call. I did not know about that. It already has a persian-alphabetic list, which is close enough to what I had proposed, but I would like to make a suggestion to change it. Where do I make that suggestion?
