### ISSUE TITLE
[css-display] Use "computes to" instead of "behaves as" for display: contents on unusual elements.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2755]
https://drafts.csswg.org/css-display/#unbox says:

> display: contents behaves as display: none.

Which means that the computed value of `display` should still be `contents`. This adds unnecessary complexity, and this is not how all engines implementing this section right work.

In particular, it requires a mapping from element to "is really display contents", or something of the sort. Firefox used to have that, but it caused a lot of performance issues for no gain, so I removed it in https://bugzilla.mozilla.org/show_bug.cgi?id=1303605.

(Note that I removed that mapping earlier without realizing the correctness issue it introduced, https://bugzilla.mozilla.org/show_bug.cgi?id=1453702, which I fixed computing to none instead of contents, which also aligns with Blink and WebKit).

**Comment by emilio** [comment]
cc @lilles since he implemented the Blink style fixup, but I think he wouldn't have any objection about changing this, given it would adapt the spec to how Blink, Firefox and WebKit implement.

**Comment by lilles** [comment]
Huh. I thought we did store the original display for computed style before adjusting. I think we're fine with either resolution.

**Comment by lilles** [comment]
I misunderstood our OriginalDisplay() thing. Not used for getComputedStyle(). I support resolving this as proposed.

**Comment by tabatkins** [comment]
Sounds fine to me. @fantasai, any objection?

**Comment by fantasai** [comment]
WFM. Would be relatively easy to implement for SVG, MathML, etc just by having a UA !important rule, too.

**Comment by fantasai** [comment]
Uh, ignore that last sentence, it makes no sense.
