### ISSUE TITLE
[mediaqueries] Change dci-p3 back to p3

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#276]
The commit b7e9438393033fad1e390f41a4558cb735b3507c changed the p3 value in the color-gamut media query to dci-p3. I suggest that should be reverted.
1. Unlike the color() function, the identifier here is supposed to be intentionally vague. "P3" refers to a set of similar profiles, so there is no point singling one out in particular. What's the point of saying "DCI P3" if the display supports "Adobe RGB", which is considered close enough to return true?
2. "DCI P3" isn't much more accurate than just "P3" anyway. My version of Photoshop supports 7 different profiles with "P3" in the name, 6 of which have "DCI P3" in the name. And funnily enough, it's the odd one out, "Display P3", that you probably want to use on current Apple hardware. I didn't suggest "display-p3" when proposing this feature 😄 
3. [Clearly not a strong reason!] WebKit has already implemented and promoted "p3". There is a small window of opportunity to change this before iOS 10/Sierra, and I'm willing to do so, but I will have to wonder whether it is worth keeping "p3" around 😦

**Comment by zcorpan** [comment]
I think people will be confused if MQ and css-color use different names, and impossible to remember which one to use where. I don't care which of dci-p3 or p3 (or other), but I think it should be consistent. (The definition can still say "this means one of these 7 profiles or something close enough" or whatever.)

**Comment by svgeesus** [comment]
I agree they should be consistent between MQ and css-color. I don't have a strong feeling n dci-p3 and p3 but for css-color, which is not intended to be vague, dci-p3 specifies a 1/2.6 transfer curve which there also seems to be an Apple p3 which uses either 1/2.2 or the sRGB transfer curve (I have seen reports of both, and no clear documentation on what apple uses exactly. Is that the Display P3?).

So on the one hand, DCI P3 is more accurate, which matters for the css-color case.

On the other, other hand, p3 is shorter.

Dino, if you have some icc profiles for these p3 colorspaces, I would love to take a look at them.

**Comment by grorg** [comment]
@svgeesus there are some details on the Display P3 profile here: [http://www.astramael.com](http://www.astramael.com) and on [Anandtech](http://www.anandtech.com/show/10265/understanding-the-97-ipad-pros-true-tone-display)

You're right about Display P3 using a gamma of 2.2, rather than 2.6 from DCI P3. 

Again, I don't think this matters for the color-gamut query. If a system can output the range of DCI P3, it almost certainly can do Display P3. There is no point being specific: "p3" is good enough.

It's a nice goal to use the same as the color() function, but that's the one that has to be specific. Like I said, my version of Photoshop has 6 different DCI P3 profiles.

I don't know what other vendors are planning, but since there is hardware and software being sold in volume today that supports Display P3, it might be nice to have a "display-p3" shortcut for color().

**Comment by tabatkins** [comment]
I'm on record as supporting shipping a bunch of pre-defined profiles for color(); the less likely we can make it that you need to load a profile via http, the better.

If we end up with multiple p3 variants in color(), then I def support switching the MQ to just `p3`.  If we have a single color() p3 variant, then I support naming them *both* `p3`, and clarifying which one, precisely, is being referred to in Color.

**Comment by svgeesus** [comment]
Agree that if we end up with multiple P3-like spaces than the MQ should go back to being just p3.

**Comment by svgeesus** [comment]
I'm fine with changing this back to p3 in MQ4.

**Comment by frivoal** [comment]
Sure. @svgeesus, I suggest you go ahead and make the change as part of resolving https://drafts.csswg.org/mediaqueries-4/#issue-156eb0fd (and hopefully https://drafts.csswg.org/mediaqueries-4/#issue-2650c6fe at the same time).

**Comment by svgeesus** [comment]
P3 is defined by two SMPTE standards (costing $240 and $80 respectively). 2020 is defined by an ITU standard 9which is freely available).
I added a biblio.json with those references.
https://github.com/w3c/csswg-drafts/commit/7c94e1d92482adc84f66126e7ba9a63068b1a484

**Comment by frivoal** [comment]
Closed in https://github.com/w3c/csswg-drafts/commit/bf5a90d3e131cd9c5969746aaca25c3f5758ebe6
