### ISSUE TITLE
[css-backgrounds] <color> in <shadow> should default to currentcolor

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2766]
Currently the spec says:
> Specifies the color of the shadow. If the color is absent, the used color is taken from the color property.

It seems to behave like `currentcolor` nowadays, but it would have different behavior in terms of interpolating. I think we should probably make it default to `currentcolor` instead. I see no reason we need a separate no-color value case.

(It's not clear to me whether it should go to level 3 or 4.)

**Comment by svgeesus** [comment]
> (It's not clear to me whether it should go to level 3 or 4.)

When we get agreement on this, it would be a change to color 4 and an erratum on color 3.

**Comment by upsuper** [comment]
Let's put it into agenda... but next telecon is not apac timezone one which can be hard for me to take part in so maybe sydney f2f...

**Comment by upsuper** [comment]
This also affects `drop-shadow()` in Filter Effects, which has similar statement:
> the missing used color is taken from the color property.

It should use currentcolor as well, I suppose.

**Comment by svgeesus** [comment]
I agree that referencing `currentColor` is the correct way to go here for both `shadow` and `drop-shadow()`.
