### ISSUE TITLE
[css-images] Spec "image-orientation: none" (and add deprecation note for <angle>)

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#2767]
In https://log.csswg.org/irc.w3.org/css/2017-04-20/#e799459 , the CSSWG had this resolution:
````
RESOLVED: Deprecate <angle> in image-orientation and add a 'none' value
````

It looks like this hasn't made it into the spec yet, though. The relevant spec text is here (which does not mention `none` at all):
https://drafts.csswg.org/css-images/#propdef-image-orientation

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/a4b5b28f6d882d49605019e3da6b79b50bc65f7d
Thanks!
