### ISSUE TITLE
[mediaqueries-4][mediaqueries-5] Is <mf-range> syntax correct?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2790]
https://drafts.csswg.org/mediaqueries-4/#mq-syntax says:

```
<mf-range> = <mf-name> [ '<' | '>' ]? '='? <mf-value>
           | <mf-value> [ '<' | '>' ]? '='? <mf-name>
```

That means that `width 500px` is a valid production, for example, without any operator, neither `=` or `>` / `<`.

Is this intentional? If so, is it worth a test / clarification?

**Comment by emilio** [comment]
cc @zcorpan

**Comment by emilio** [comment]
Err, sorry @zcorpan, meant to mention @frivoal :)

**Comment by tabatkins** [comment]
Whoops, no, that's not intended.  Should be 

```
<mf-range> = <mf-name> [ [ '<' | '>' ]? '='? ]! <mf-value>
           | <mf-value> [ [ '<' | '>' ]? '='? ]! <mf-name>
```

Or perhaps just replace that middle bit with `<mq-comparison>`, defined as:

```
<mq-comparison> = [ '<' | '> ] '='? | '='
```
