### ISSUE TITLE
[css-fonts-3] Request transition to Proposed Recommendation

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#2795]
The Fonts 3 testsuite now shows only  [one failing test](https://test.csswg.org/harness/results/css-fonts-3_dev/grouped/filter/1/) which is for `font-feature-values`. We resolved to remove that feature, deferring it  to Fonts 4, which I just did. It was marked as at-risk in the March 2018 CR. I have [a one-line pull request on web platform tests](https://github.com/web-platform-tests/wpt/pull/11563) which updates the `rel=help` to point to Fonts 4 instead of Fonts 3.

Once that change is accepted there will be **zero failing tests** and we have **met our CR exit criteria**.

I would like a CSS WG resolution to request transition to Proposed Recommendation for Fonts 3.

**Comment by svgeesus** [comment]
Remaining [Fonts 3 issues for Disposition of Comments](https://github.com/w3c/csswg-drafts/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Acss-fonts-3+sort%3Aupdated-desc+) deferred to Fonts 4.

**Comment by svgeesus** [comment]
[Disposition of Comments](https://drafts.csswg.org/issues?spec=css-fonts-3&doc=pr-2018)

[One remaining open issue](https://github.com/w3c/csswg-drafts/issues/2796), was already at-risk in CR, some uncomfortable with downgrading from `must` to `should`. No implementations.

**Comment by astearns** [comment]
(removing the Agenda+ label. We'll revisit this once the updated CR gets to the point where we can ask for PR again)

**Comment by svgeesus** [comment]
[PR transition request](https://github.com/w3c/transitions/issues/56)
denied due to two small normative changes
[Updated CR transition request](https://github.com/w3c/transitions/issues/57)
spec published [26 June 2018](https://www.w3.org/TR/2018/CR-css-fonts-3-20180626/)

Exclusion period ends 25 August 2018.

Expect that spec to then move to PR without any edits beyond styling/status

**Comment by xfq** [comment]
[PR published](https://www.w3.org/TR/2018/PR-css-fonts-3-20180814/). Should we close the issue?
