### ISSUE TITLE
[css-fonts-3] Dropping "synthesizing super/sub-scripts" requirement

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#2796]
[Fonts 3 says](https://www.w3.org/TR/css-fonts-3/#font-variant-position-prop) " In the case of OpenType fonts that lack subscript or superscript glyphs for a given character, user agents must synthesize appropriate subscript and superscript glyphs. ".

In the features at risk for the March 2018 CR:

> Synthesis of the ‘font-variant-position’ property 

So, how to handle dropping this?

1. Remove the sentence
2. Change `must` to `should` or even `may`

**Comment by fantasai** [comment]
I think this is an important requirement: losing the synthesis backup means a page's content can become garbled, either incomprehensible and/or incorrect. We need to get implementations to fix it, and I would be uncomfortable going to REC with this feature if it's not implemented safely.

**Comment by svgeesus** [comment]
Notice that the requirement at-risk here is not "synthesizing super/sub", which implementations have done since forever. Instead, if an OpenType font has special sup/sub glyphs for some, but not all, of the characters that a given page needs, the requirement is to **synthesize all of them** rather than using a _mix_ of some synthesized and some designed sup/sub glyphs (which is readable but ugly).

In the figure below, the font has a superscript 2 and does not have a superscript a. In red is the naive but ugly implementation where these are both superscript, but do not fit well together. The central part shows the designed superscript 2 not being used, so that the superscript 2a is consistent.

![superscript-alt-synth](https://user-images.githubusercontent.com/2506926/41600800-d464ea2a-73a4-11e8-96e0-c1f7977ba721.png)

**Comment by svgeesus** [comment]
Fonts 3 [introduced the font-synthesis property](https://drafts.csswg.org/css-fonts-3/#font-synthesis-prop), covering fake-bold and fake-italic/oblique. Fonts 4 [extends this to fake-smallcaps](https://drafts.csswg.org/css-fonts-4/#font-synthesis-prop). Perhaps a better way to deal with this would be to add fake sub/sup to font-synthesis in Fonts 4?

**Comment by svgeesus** [comment]
OK so, change must to should.

**Comment by frivoal** [comment]
I am not sure I agree. Change the order of 2 and a in the example above, and the read case then reads like `2^(a^2)`, which seems it would be confusing and a source of misunderstandings.

**Comment by svgeesus** [comment]
Fixes noted by @fantasai on the call:
https://github.com/w3c/csswg-drafts/commit/8e85d311e4c298494777a573da503363245a6ff3
