### ISSUE TITLE
[css-text-4] hyphenate-character doesn't accept just a character

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2809]
https://drafts.csswg.org/css-text-4/#hyphenate-character

```css
Name: 'hyphenate-character'
Value: | auto | <string>
```

Shouldn't it accept just a single character? Or the prose should say everything except the first code point (or grapheme cluster) should be ignored? Or perhaps the property should be renamed to hyphenate-string?

**Comment by kojiishi** [comment]
cc @r12a

**Comment by kojiishi** [comment]
Good point. All hyphenations Android supports today are one code point ([Hyphenator.cpp @ android.googlesource.com](https://android.googlesource.com/platform/frameworks/minikin/+/master/libs/minikin/Hyphenator.cpp))

**Comment by litherum** [comment]
One code point is probably not what we want because of the combining emoji that can be multiple code points.

**Comment by litherum** [comment]
That being said, I don’t think it’s very valuable to put emoji or tons of stacked combining marks in the string. Perhaps a better solution is for the property to just accept keywords for the various popular kinds of hyphens.

https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/-webkit-hyphenate-character/

**Comment by r12a** [comment]
fwiw, I checked out the use of `hyphenate-character` at the link in https://github.com/w3c/csswg-drafts/issues/2809#issuecomment-402877863.  I could only find it being used in two sites (exlibris and hurriyetaile), and in both cases the 'string' identified was "\2010", ie. not a string at all. 

I don't know of any real world hyphenation approach that uses multiple characters, or have decompositions into multiple characters  (though that's not to say that there aren't any).

**Comment by fantasai** [comment]
Committed text allowing (MAY) the UA to limit the hyphenation string to a single typographic character unit in https://github.com/w3c/csswg-drafts/commit/bfb538a8a9bba5b464df192b56ff3a660c511e8e

I wanted to check with the WG on a few points, though:

- Should we limit it to a single character unit or the UA's choice of N character units?
- Should this affect the computed value or only the used value?

Also, @r12a, do you have an example I can use that's not "\2010"? It's not a very good example for the spec since `hyphenate-character: "\2010"` is essentially a no-op...

**Comment by litherum** [comment]
> Committed text allowing (MAY) the UA to limit the hyphenation string to a single typographic character unit in [bfb538a](https://github.com/w3c/csswg-drafts/commit/bfb538a8a9bba5b464df192b56ff3a660c511e8e)
> 
> I wanted to check with the WG on a few points, though:
> 
> * Should we limit it to a single character unit or the UA's choice of N character units?

Let the UA just do the right thing here. If the author supplies some ridiculous long string, I don't think I would consider content "broken" that cuts it in one place as opposed to another place. So it's probably okay if browsers differ here.

> * Should this affect the computed value or only the used value?

It's conceivable that an implementation might decide to cut the string at different places depending on the font size and the width of the containing block. This information isn't known at style resolution time, so not affecting computed value would be better.

> * Should it be MAY or MUST?

I'd say MUST, because if the UA doesn't do any cutting at all, it's broken.

> 
> Also, @r12a, do you have an example I can use that's not "\2010"? It's not a very good example for the spec since `hyphenate-character: "\2010"` is essentially a no-op...

**Comment by kojiishi** [comment]
> Also, @r12a, do you have an example I can use that's not "\2010"? It's not a very good example for the spec since `hyphenate-character: "\2010"` is essentially a no-op...

How about [U+1400 CANADIAN SYLLABICS HYPHEN](http://www.fileformat.info/info/unicode/char/1400/index.htm)?

**Comment by fantasai** [comment]
@litherum OK, uncommented the N-character variant of the prose and specified the used value. :)

@kojiishi Great, I updated the example. If anyone knows a language code for it, that might be nice to add to the example as well.

**Comment by r12a** [comment]
> If anyone knows a language code for it, that might be nice to add to the example as well.

Based on fig. 1 at http://std.dkuug.dk/jtc1/sc2/wg2/docs/n3427.pdf, you could safely use `ojs`.

**Comment by fantasai** [comment]
@r12a Thanks, done. :)
