### ISSUE TITLE
[css-text-4] What happens when the hyphenation string is wider than a line?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#2810]
https://drafts.csswg.org/css-text-4/#hyphenate-character

What happens when the hyphenation string is wider than a line? Should we hyphenate the hyphenation? Or ignore the string altogether? What about kerning pairs between the hyphenation string and the text getting hyphenated?

If the spec is going to accept a full string instead of just a single character, it should at least mention what happens here (though single characters can be wide too).

**Comment by litherum** [comment]
Also: Arbitrary strings can have line breaking positions inside them. What should we do?

**Comment by fantasai** [comment]
IIRC, we talked about allowing the UA to limit the hyphenation character to a single “typographic character unit”. I think this is reasonable and we should allow it. The open questions on this point are:

- Should we limit it to a single character unit or the UA's choice of N character units?
- Should this affect the computed value or only the used value?

**Comment by fantasai** [comment]
Closing out in favor of https://github.com/w3c/csswg-drafts/issues/2809 which is covering this ground. I'll repost the open questions there.
