### ISSUE TITLE
lightslategray mentioned twice as colour

### ISSUE THREAD

**Issue by dilyanpalauzov** [w3c/csswg-drafts#2812]
Why are 

lightslategray | #778899 | 119 136 153 ,
slategray | #708090 | 112 128 144 and
darkslategray | #2F4F4F | 47 79 79

included twice at  https://drafts.csswg.org/css-color/#named-colors?

**Comment by dbaron** [comment]
Once is with the "gray" spelling (preferred en-US spelling) and once is with the "grey" spelling (preferred en-GB/en-CA/etc. spelling)
