### ISSUE TITLE
[selectors-4] Add functional notation to :local-link selector? :local-link(n)?

### ISSUE THREAD

**Issue by jonjohnjohnson** [w3c/csswg-drafts#2814]
https://drafts.csswg.org/selectors-4/#the-current-pseudo

See -> https://wiki.csswg.org/ideas/current-url-selector

> The current link pseudo-class selector would have the following pattern: `E:current(n) {}`

Please read the wiki page linked above, I won't rehash all it has to say here. I am wondering if this was ever shot down and if not, what folks think about it now? Because I cannot help but imagine it as extremely useful, especially keeping in mind the `:has()` relational pseudo-class allowing a "current" anchors parent element to also be selected.

The key here being, the functional notation as opposed to the the current language of the spec.

_Edited - :local-link is the selector in the spec_

**Comment by Loirooriol** [comment]
[`:local-link`](https://drafts.csswg.org/selectors-4/#the-local-link-pseudo)`(n)`?

**Comment by jonjohnjohnson** [comment]
@Loirooriol oh I forgot seeing it had a new name a while back, but still missing the functional notation for directory depth, which would enable particular breadcrumb and local/external stylings? Maybe I should add "functional notation" to the title?

**Comment by fantasai** [comment]
Sorry, it was resolved to drop it, and then we added the simplified version back. See https://github.com/w3c/csswg-drafts/issues/2010 :)
