### ISSUE TITLE
[css-pseudo-4] Should CSSPseudoElement.type value include the "::" prefix?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#2815]
When I implemented CSSPseudoElement.type in Gecko, the advice I was given was to use the "::" prefix for "::before" and "::after". That would match the naming we using for [`TransitionEvent.pseudoElement`](https://drafts.csswg.org/css-transitions/#Events-TransitionEvent-pseudoElement) and [`AnimationElement.pseudoElement`](https://drafts.csswg.org/css-animations/#dom-animationevent-pseudoelement) at least.

**Comment by tabatkins** [comment]
Yes plz

**Comment by fantasai** [comment]
The draft currently asks if `letter` and `line` should be `first-letter` and `first-line`. I'm hoping that if we're adding the `::` then that definitely happens so it actually matches the relevant pseudo-class names.
