### ISSUE TITLE
[css-text-decor] Define how text-decoration-skip{,-ink} interacts with text-decoration

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2817]
`text-decoration` style properties are non-inherited (as they should), while `text-decoration-skip` and `text-decoration-skip-ink` are inherited (as they should as well).

They are all fine in themselves, but there would be a problem on how they should interact, or more specifically, should the "skip" behavior of a text decoration line come from the element where the text is in, or from the element where the decoration line is originated from?

For example, something like
```html
<style>
div {
    text-decoration: underline;
    text-decoration-skip-ink: auto;
}
span {
    text-decoration-skip-ink: none;
}
</style>
<div>For <span>example</span></div>
```

should "example" have ink skipping?

Note that, current implementations of `text-decoration-skip-ink` (WebKit and Blink) don't support non-inherited text decoration, and thus they may not have this confusion at the moment. But since we want non-inherited text decoration, so it's worth making clear in the spec.

**Comment by fantasai** [comment]
Added clarification for `text-decoration-skip-ink`; it was already specified for `text-underline-offset` and `text-underline-position`.
