### ISSUE TITLE
Tabulation characters in mixed directionality

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#2842]
By looking at [crbug.com/318717](http://crbug.com/318717) with @fantasai, I wasn't sure what the right answer for this.

[test @ jsbin](http://jsbin.com/yaxaxer/edit?html,output)

Windows result, Gecko, Blink, Edge, LayoutNG from left. WebKit on Mac is the same as Gecko/Blink.
![image](https://user-images.githubusercontent.com/1274377/42019397-099b7dba-7af0-11e8-851f-2522aebd1f76.png)

**Comment by upsuper** [comment]
According to the HTML spec, element with `dir` attribute has `unicode-bidi: bidi-override;` and their corresponding direction. Based on the CSS Writing Modes spec, `<div dir=ltr><span dir=rtl>&#9;0</span></div>` is equivalent to a "LRO RLO S EN PDF PDF".

Looks like rendering it as `<number><tab>` is more correct? And vice versa for the last item.

**Comment by kojiishi** [comment]
> element with `dir` attribute has `unicode-bidi: bidi-override`

Isn't it `bidi-isolate` instead? So, `LRI RLI S EN PDI PDI`? The [Unicode tool](http://unicode.org/cldr/utility/bidi.jsp) doesn't have isolate, so I guess I have to write a program to check ICU behavior.

**Comment by upsuper** [comment]
Gecko's ua sheet uses `unicode-bidi: isolate` but HTML spec [says `bidi-override`](https://html.spec.whatwg.org/multipage/rendering.html#bidi-rendering)... I don't remember which one is correct...

**Comment by kojiishi** [comment]
The second one is for `iso-8859-8`, and the first one is regular UA sheet.

I gave `RLI S EN PDI` to ICU, which resolved to `0 0 2 0`. The same level as `RLE S EN PDF`, which [reorders to `<tab>0`](https://unicode.org/cldr/utility/bidi.jsp?a=%E2%80%AB%090%E2%80%AC&p=Auto) order.

**Comment by kojiishi** [comment]
But thank you, trying to match to UAX#9 is a good idea, I don't know why I didn't think about it. So maybe, if we think we should simply follow UAX#9 in this case, this is just a question about writing-modes.

**Comment by upsuper** [comment]
Gecko does seem to have a different resolution on that specific sequence given the following testcase:
```html
<!DOCTYPE html>
<style>
div {
  font-family: monospace;
  white-space: pre;
  background: yellow;
  display: inline-block;
}
</style>
<div>&#x2066;&#x2067;&#9;0&#x2069;&#x2069;</div>
```

I think we are using ICU internally as well :/

**Comment by fantasai** [comment]
Just reviewed UAX9, I think it makes sense.

**Comment by kojiishi** [comment]
Thanks, then either LayoutNG or Gecko doing incorrect pre-processing before giving the text to ICU. I'll double check.

**Comment by fantasai** [comment]
Added a note to the spec referencing UAX9: https://github.com/w3c/csswg-drafts/commit/a15dde8ece9bca55adc7a76070a9a5549fe963b9
Closing this issue out. :)
