### ISSUE TITLE
[css-overflow] convert -webkit-line-clamp alias requirement into a spec issue

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#2847]
https://drafts.csswg.org/css-overflow-3/#line-clamp

The spec currently requires that a `-webkit-line-clamp` alias for `line-clamp` be supported.  It's not yet clear that a simple alias is a net win for Web compatibility, since Blink and WebKit's `-webkit-line-clamp` implementation requires `display: -webkit-box; -webkit-box-orientation: vertical;` for the line clamping behavior to kick in.  We're concered that there may be content that sets `-webkit-line-clamp` on elements that aren't `display: -webkit-box; -webkit-box-orientation: vertical;` and end up truncating their content in browsers other than Blink and WebKit.

I suggest that this be turned into a spec issue until we determine what is the best approach for handling `-webkit-line-clamp`.

**Comment by frivoal** [comment]
Good point. I *hope* that a simple alias will work, but it is far form sure that it will, for the reasons you said. Marked this as an issue in the spec, linking back to this github issue.

**Comment by MatsPalmgren** [comment]
I briefly tested `-webkit-line-clamp` in Chrome  and I'm rather confused about the results.
Here's an [example](https://bug866102.bmoattachments.org/attachment.cgi?id=8988785). In Chrome 68, an ellipses is inserted after "4" in the first two boxes and there's no ellipses in the third box.
@frivoal is that the expected result according to the spec?

**Comment by heycam** [comment]
I think it depends what `display: -webkit-box;` really means.

Per spec, without it, I would expect all three sub-tests to render the same, with an ellipsis after the "3" and all subsequent lines fragmented away.  This is because the `max-lines` applies to the parent div, and the child div's lines are in the same block formatting context as the parent's.

But if you interpret `display: -webkit-box;` as being like creating a flex item, then that does establish an independent formatting context.  In that case I would expect the first two sub-tests to be the same as before (ellipsis after "3"), but the third sub-test would look like it does in Chrome now, i.e. no ellipsis and no lines fragmented away, since the container div only generates two line boxes in its block formatting context (the "1" and the "7").

**Comment by frivoal** [comment]
Updated the spec to reflect what @heycam found to be necessary for webcompat, after discussing it with @heycam, @fantasai, @emilio.

Agenda+ to ask the WG to confirm [this commit](https://github.com/w3c/csswg-drafts/commit/2cc319448f4732c127fa43213ce7cf7d96de04ac).

**Comment by heycam** [comment]
If you could also confirm https://github.com/w3c/csswg-drafts/pull/3697 at the same time that would be great, thanks.

**Comment by frivoal** [comment]
Thanks for #3697, that was a good clarification.
