### ISSUE TITLE
[css-overflow] confusing to have both overflow-block and block-overflow properties

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#2849]
https://drafts.csswg.org/css-overflow-3/

I think it's confusing that there are both overflow-block and block-overflow properties.  Maybe we can rename block-overflow?  I don't have a good suggestion, but given text-overflow is something equivalent for the inline direction, maybe whatever word fits `inline : text :: block : <something>`?

**Comment by jonjohnjohnson** [comment]
Looks like a dup of -> https://github.com/w3c/csswg-drafts/issues/2561

**Comment by heycam** [comment]
Yes, thanks!
