### ISSUE TITLE
Need spec for margin/padding and box-styling terminolgy

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2851]
We don't have a home for CSS2.1 8.1, 8.3, 8.4. https://www.w3.org/TR/CSS2/box.html
(Borders are covered in the Backgrounds module.)

It might make sense to have a CSS Box Styling Module L3 to cover these topics. No new features for this level, just have a place to define these L2 concepts. Alternately, also steal the border properties from css-backgrounds-3.

Propose to name it css-box, which would let us overwrite the dangerously outdated block layout spec.

**Comment by tabatkins** [comment]
Oooh, yes, I agree with all of this.

**Comment by gsnedders** [comment]
Is there any reason why we aren't just doing this in 2.2?

**Comment by astearns** [comment]
It's better to create a new updated module than re-publish all of 2.2 with only one part updated. “Here's a new module superseding more of CSS2” is a better message than “Here's an updated CSS2, but only pay attention to the updates in these bits”

**Comment by tabatkins** [comment]
Yeah, per the minutes:

> TabAtkins: and continue on our slow grind to obsolete CSS 2.1

**Comment by gsnedders** [comment]
If so, is why are we working on CSS 2.2 at all instead of just publishing any errata as new modules?

**Comment by gsnedders** [comment]
As a sidenote, we should surely handle this the same as #2740? Should we have a discussion somewhere (here?) about a general policy as to what goes into 2.2 and what goes into level 3?

**Comment by fantasai** [comment]
@gsnedders #2740 has nothing to do with this issue. It's applied largely to Chapter 10.
