### ISSUE TITLE
[css-grid] grid-line custom identifier auto?

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2856]
Blink and WebKit reject grid-row-end `1 auto`.
Edge and Firefox accept grid-row-end `1 auto` and serialize it as `1 auto`.

Blink and WebKit reject grid-row-end values `span 1 auto`, `span auto 1` and `1 auto span`.
Edge and Firefox accept these and serialize all of them as `span 1 auto`.

Testing with uppercase makes it clear that `span` is being accepted as a keyword and `auto` is being accepted as a custom identifier:
http://jsfiddle.net/ericwilligers/meya2q7d/

All browsers reject the following:
`auto 1`
`span span 1`, `span 1 span` and `1 span span`
`1 span auto`, `auto 1 span` and `auto span 1`

The relevant grammar for `<grid-line>` is
```
<grid-line> =
  auto |
  <custom-ident> |
  [ <integer> && <custom-ident>? ] |
  [ span && [ <integer> || <custom-ident> ] ]
```

Are `auto` or `span` permitted as a `<custom-ident>`?

The [custom-ident spec](https://drafts.csswg.org/css-values-4/#identifier-value) may be relevant:

> Note: When designing grammars with `<custom-ident>`, the `<custom-ident>` should always be "positionally unambiguous", so that it’s impossible to conflict with any keyword values in the property.

I don't see a reading of the spec where `span 1 auto` would be permissible but not `span 1 span`.

**Comment by mrego** [comment]
Some excerpts from Grid Layout spec:
* https://drafts.csswg.org/css-grid/#named-lines
  > A line name cannot be span, i.e. the <custom-ident> in the <line-names> production excludes the keyword span.
* https://drafts.csswg.org/css-grid/#line-placement
  > In all the above productions, the <custom-ident> additionally excludes the keyword span.

Also from CSS Values and Units spec:
* https://drafts.csswg.org/css-values/#custom-idents
  > This generic data type is denoted by <custom-ident>, and represents any valid CSS identifier that would not be misinterpreted as a pre-defined keyword in that property’s value definition.

There is also a related issue #494 and some old threads in www-style:
* https://lists.w3.org/Archives/Public/www-style/2014Feb/0735.html
* https://lists.w3.org/Archives/Public/www-style/2016Mar/0247.html

**Comment by fantasai** [comment]
Seems to me the spec is clear that `span` isn't valid as a `<custom-ident>`. But it does raise the question of whether `auto` should be similarly excluded.
