### ISSUE TITLE
[css-overflow-3] max-lines not forwards compatible with fragmented overflow

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2860]
@dbaron pointed out some forwards-compatibility concerns with the proposed behavior for `max-lines`, which would discard extra content by default: in the future, an author would want to combine `max-lines` and overflow fragments (e.g. `continue: fragments`), and in an older client the content would get discarded.

See https://lists.w3.org/Archives/Public/www-style/2018May/0041.html

**Comment by fantasai** [comment]
One way to solve this would be backporting `continue: auto | discard` so that `max-lines` will _not_ discard by default, only when `continue: discard` is specified. Thus an implementation of `max-lines` + `continue: fragments` will not discard the content (as the author did not intend). In this case, we'd extend `line-clamp` to also set `continue: discard` so that it preserves its current behavior.

However, in this case, it would end up overflowing the box, which is maybe not a great improvement.

**Comment by frivoal** [comment]
> One way to solve this would be backporting continue: auto | discard so that max-lines will not discard by default, only when continue: discard is specified. Thus an implementation of max-lines + continue: fragments will not discard the content (as the author did not intend).

I support this. 

> If we do this, we'd extend line-clamp to also set continue: discard so that it preserves its current behavior.

This too. To make it easy to set everything in one go, we should also extend the syntax of line-clamp to `none | <integer> <'block-overflow'>?`

> However, in this case, it would end up overflowing the box, which is maybe not a great improvement.

No, we should just say that max-lines only applies to fragmentainers. Making it apply to non fragmentainers (by limiting the height or something) looks very much like a footgun to me. Plus it means we'd have to implement something totally different for that case.
