### ISSUE TITLE
[css-fonts-4] oblique angle for synthesis in vertical text

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2869]
We discussed this and deferred from Fonts 3, but what does it mean to synthesize oblique fonts in vertical text?

**Comment by fantasai** [comment]
Previous discussion: https://lists.w3.org/Archives/Public/www-style/2013Jul/0065.html

**Comment by fantasai** [comment]
Images from discussions: https://lists.w3.org/Archives/Public/www-archive/2018Jul/0003.html

**Comment by svgeesus** [comment]
>5 and 6 for italic and obliques with positive angles

Checking before editing that this means _5 for italic_, and _6 for obliques with positive angles_, and _undefined for obliques with negative angles_

**Comment by fantasai** [comment]
@svgeesus It means positive angles skew such that the line-over edge shifts towards the line-right side while the line-under edge shifts towards the line-left side, for both italics and obliques (synthesized). Negative angles skew the other direction. (They're not undefined, they're the opposite of positive.)

**Comment by jonjohnjohnson** [comment]
@fantasai is it always considered physical "line-right side" and "line-left side" and not logical "line-end side" and "line-start side"?

**Comment by svgeesus** [comment]
@jonjohnjohnson This will be physical rather than logical, because that is how OpenType defines it:

> Scale interpretation: Values can be interpreted as the angle, in counter-clockwise degrees, of oblique slant from whatever the designer considers to be upright for that font design.
