### ISSUE TITLE
[css-logical][css-backgrounds] Do border-block and border-inline reset border-image?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2874]
CSS Logical adds [`border-block` and `border-inline`](https://drafts.csswg.org/css-logical/#propdef-border-block) shorthands.

They don't have physical equivalents so it's not completely clear whether they reset `border-image` like the `border` shorthand does.

I wouldn't expect `border-image` to be reset by `border-block` and `border-inline`, but I have been asked this while implementing them in Chromium.

**Comment by mrego** [comment]
I don't know if it'd be worth to clarify this, as in the [`border` shorthand](https://drafts.csswg.org/css-backgrounds-3/#border-shorthands) we have:
> The border shorthand also resets border-image to its initial value.
However in [css-logical we don't have anything like that](https://drafts.csswg.org/css-logical-1/#propdef-border-inline).

Then we could write a simple test to verify this and be sure that all the implementations do the same here, it can be tempting to reuse the `border` shorthand code somehow and reset `border-image` in the logical shorthands too.

**Comment by fantasai** [comment]
No, they don't. Only `border` does. I think the spec is super clear on this point:

> These two shorthand properties set the border-block-start & border-block-end and border-inline-start & border-inline-end, respectively.

So marking as invalid.
