### ISSUE TITLE
[css-scrollbars] Shorthand for scrollbar colors (maybe also colors + width)?

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2879]
Authors would generally want to set both scrollbar colors together, so it may make sense to have a shorthand for them. Maybe something like `scrollbar-color` with two colors?

cc @tantek

**Comment by jonjohnjohnson** [comment]
How about `scrollbar-style` over just `scrollbar` for the catch-all shorthand?

**Comment by fantasai** [comment]
A `scrollbar` shorthand would be a nice way to reset everything back to auto, regardless of what scrollbar controls we might have in the future, so maybe that's helpful.

Definitely in favor of a `scrollbar-color` shorthand.

**Comment by upsuper** [comment]
There was concern raised in our Intent to Implement that, what should happen when one of the color is specified, while the other is not. It's probably a reasonable concern, and the UA would probably be required to either derive the other color to ensure contrast, or avoid showing custom scrollbar in that case.

I'm now thinking about using a single `scrollbar-color` longhand property to replace the current two properties. It would accept value `auto | <color>{2}`, so that giving a single value is invalid, and it would either have two colors, for face and track respectively, or just `auto`.

What do you think about this?

**Comment by upsuper** [comment]
So I don't think a shorthand consisting of `scrollbar-color` and `scrollbar-width` should block FPWD. We may consider this later, but I tend not to add it in general.

@tantek brought to me that a `scrollbar` shorthand may be a parallel to other shorthands like `border` and `outline`, but I'll argue that it's not the case.

The difference is that, all subproperties of `border` / `outline` are serving the single use case to style border / outline of the given element, and thus they are all non-inherited.

While `scrollbar-color` and `scrollbar-width` seem to be for styling scrollbars, they are actually serving different use cases: `scrollbar-color` is for theme consistency, usually set for the whole page, while `scrollbar-width` is for hiding scrollbar or making it thinner for specific element where normal scrollbar doesn't fit. Because of that, the former is inherited while the latter is not.

Because of that, I don't think a general `scrollbar` shorthand is really desirable, and I don't think it need to block FPWD.

**Comment by fantasai** [comment]
@upsuper I think the resolution to https://github.com/w3c/csswg-drafts/issues/2993 supersedes this one, so should close the issue? (You're the original commenter, so...)

**Comment by upsuper** [comment]
OK, let's close it. If we want the `scrollbar` shorthand we can open a new one I guess.
