### ISSUE TITLE
[css-nesting] Define how invalid nested rules should be handled

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2880]
There are several cases in the spec that a nested rule becomes invalid, but it doesn't mention how an invalid nested rule should be handled.

Should the specific sub-rule be dropped, or should its parent rule be treated invalid as well?

My intuition is that probably only the invalid sub-rule should be dropped, but it's not clear to me whether the other way around would be better.

**Comment by tabatkins** [comment]
Only the invalid sub-rule should be dropped.

**Comment by jonathantneal** [comment]
Should this section be updated to include invalid rules or invalid nesting rules (emphasis added):

> Unexpected **at-rules** (which could be all of them, in a given context) are invalid and should be ignored by the consumer.
> — https://drafts.csswg.org/css-syntax/#parse-list-of-declarations

**Comment by tabatkins** [comment]
Went ahead and put in some explicit text just to make it 100% clear.
