### ISSUE TITLE
[selectors] Should empty string link match :visited?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2884]
Should this match `:visited`?

```html
<a href="">Link</a>
```

An empty URL points to the base URL, so assuming there is no `<base>` and history is enabled, I guess `:visited` should match.

However, there are various WPT tests like https://github.com/web-platform-tests/wpt/blob/6562ed003eebcd25d093ae52d68de28a0ae0d786/css/CSS2/selectors/link-visited-selector-001.xht which are manual. If the above is supposed to work, why not make them   automated by linking the current page?

And Edge seems to have some weird bugs, like `<a href="">` matching `:visited` in jsfiddle but not in jsbin. However, this seems to work everywhere:

```js
document.querySelector('a').href = location.href
```

So can you confirm that this is supposed to work?

**Comment by tigt** [comment]
Could you link to the jsbin you men tioned? It may append a cachebusting querystring to its preview `<iframe>`, causing `<a href="">` to expand to a URL the browser *hasn’t* visited.

**Comment by Loirooriol** [comment]
The jsbin was http://jsbin.com/kuhaxer/1/edit?html,css,output

However, I also tried a plain local HTML file (both with file:// and http://localhost/) and :visited didn't match.

However, it matched in https://jsfiddle.net/9f1eqyon/1/

**Comment by fantasai** [comment]
Yes. There's nothing special about href="", as long as it points to the current page (depends on the BASE tag), it should be considered visible. I can't seem to duplicate your problems here -- the jsbin works, local files containing

```
<a href="">test.html</a>
<a href="test2.html">test2.html</a>
```
work as expected. So closing out the issue as invalid.

**Comment by fantasai** [comment]
Ohyeah, the reason the tests there are manual are because all tests during CSS2 development were manual, so there wasn't a perceived benefit in making them automatable. :) Now that we have automation systems, it would be fine to update them to be automated.

**Comment by Loirooriol** [comment]
> the jsbin works

Even in Edge? It still fails for me there. But if it's supposed to work instead of undefined behavior, then it's a bug.

So I guess https://cs.chromium.org/search/?q=file:third_party\/WebKit\/LayoutTests\/fast\/css\/logical-box-border-color-visited-link-\d%2B\.html and https://searchfox.org/mozilla-central/search?q=&case=false&regexp=false&path=layout%2Freftests%2Fcss-visited%2Flogical-box-border-color-visited-link- could be moved to WPT.

**Comment by emilio** [comment]
Note that IIRC in Gecko visited link coloring is async even if `href` is empty.

We could probably special-case the `href=""` case, somehow to have deterministic output for reftests... WDYT @dbaron?
