### ISSUE TITLE
[css-nesting] Semantic of nesting selector is unclear

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2895]
The current spec says
> When used in the selector of a nested style rule, the nesting selector represents the elements matched by the parent rule.

It is unclear whether `&` in a selector means an element matched by the parent rule, or any elements matched by the parent rule. This affects what would happen when multiple nesting selectors appear in a single complex selector.

For example, should `a, b { & c & { } }` matches nothing (in the former semantic that a `&` always means a single element at a time, and since an element cannot be its descendant, this selector is nonsense), or `:matches(a, b) c :matches(a, b)` (in the latter semantic).

This may significantly affect how nesting rules would be implemented, and I suppose the former semantic may be easier to implement efficiently.

**Comment by upsuper** [comment]
Maybe it doesn't really matter... I don't know.

**Comment by bradkemper** [comment]
It would be the `:matches(a, b) c :matches(a, b)` one. But it isn't nonsense. The inner a and b could match the same selector without being the same element. Imagine if it was `:matches(div, span) p :matches(div, span)`, for instance, which is a real world equivalent. That would match `div p div`, `span p span`, `div p span`, and `span p div`. Those do actually exist in the wild.

**Comment by tabatkins** [comment]
The quoted spec text means exactly what it says - it "represents the elements matched by the parent rule", in the same way as `.foo` represents "the elements with a `foo` class". And in both examples, it makes perfect sense to repeat the selector twice in a larger selector; each instance stands for the same set, but any particular match will choose different elements from that set. (Well, most of the time; using it in function like `:is()` can represent the same element twice.)
