### ISSUE TITLE
[css-nesting] Maybe require all selectors in :matches() / :not() either have or not have nesting selector?

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2896]
The spec currently says
> A list of selectors is nest-containing if all of its individual complex selectors are nest-containing.

I'm wondering whether the same requirement should be applied recursively to selector list inside, i.e. for selector lists inside `:matches()` and `:not()`, all selectors in them should be either nest-containing or not together.

The same reasoning of editting hazard can apply here as well. This may also affect how this can be implemented (e.g. you can make assumption on that an element matched by nested rule must have itself or an ancestor of it matched, although that assumption may also require disallowing `:not(&)`).

**Comment by Loirooriol** [comment]
`:nth-child` and `:nth-last-child` also accept a selector list

**Comment by tabatkins** [comment]
Closing, as this issue is now moot (the requirement disappeared when we rejiggered how nesting rules worked).
