### ISSUE TITLE
[css-scrollbars] Define what scrollbar "track" and "face" are

### ISSUE THREAD

**Issue by a2sheppy** [w3c/csswg-drafts#2898]
In [section 2](https://drafts.csswg.org/css-scrollbars-1/#scrollbar-color-properties), the terms "scrollbar-track" and "scrollbar-face" are used without defining what these are. The terms used to describe the components of a scrollbar vary from platform to platform, so the ones chosen here must be defined to ensure that all readers are on the same page.

Presumably the track is the main bar background area; the "face" is the more confusing term. Is that the draggable widget (which I have called an "elevator" since sometime in the mid-1980s despite various other terms floating past me over the years)? Does the face include the arrows at the end(s) of the scroll bar? If so, is it the background of the arrow's box, the foreground? Or is it the scrollbar's bounding box? Or something else entirely? Or is it intended to be up to the client to decide what to do with these values?

**Comment by upsuper** [comment]
The dragging area is the "face" and the area serving as a track of the dragging area is "track". And everything else intends to be platform-dependent, like whether arrows should take "face" color or "track" color or neither (e.g. no arrows at all, or use some color derived from either or both specified colors).

**Comment by SelenIT** [comment]
Some of the documented examples (e.g. [TweetDeck](https://github.com/webcompat/web-bugs/issues/9791#issuecomment-403218773). mentioned [in the rationale that pseudo-elements are not needed](https://www.w3.org/wiki/Css-scrollbars#TweetDeck), but apparently under-examined back then) also display intent to control the shape (rounded corners) and minimum size of the dragging area. Are there any chances that the spec will take these aspects into account?

**Comment by a2sheppy** [comment]
@upsuper That's about what I thought. It would be wise, IMO, to have that information laid out explicitly in the spec.

**Comment by fantasai** [comment]
Wikipedia lists some various terms for the thumb: https://en.wikipedia.org/wiki/Scrollbar
I think “grip” seems the most self-evident out of all of them, maybe it's worth considering `s/scrollbar-face-color/scrollbar-grip-color/g`. Agreed that the spec should describe the parts of the scrollbar it's talking about, though.

**Comment by smfr** [comment]
"Face" is a weird name for the draggable bit. On macOS we call it the "knob" or "thumb". I support "track" for the other part.

**Comment by tabatkins** [comment]
Agree; "knob" and "track" seem like a good pair of words.

(I do hear "thumb" quite a bit, but *only* for scrollbars; it seems like maybe a weird artifact of some historical naming scheme? Weird anyway.)

**Comment by SelenIT** [comment]
FWIW, the word "thumb" is also used in browser-specific pseudo-elements name for the quite similar part of the value slider (`<input type="range">`). Interestingly, _all_ engines that have such styling option [use that name](https://www.tjvantoll.com/2013/04/15/list-of-pseudo-elements-to-style-form-controls/#input_range).

**Comment by a2sheppy** [comment]
I definitely agree with "track" for what it's worth; I would use "thumb" for the draggable widget for two reasons: first, because as @SelenIT points out, there is precedent, and second, because the word "knob" does have an unfortunate slang meaning that could wind up the target of some "humor."

**Comment by upsuper** [comment]
I tried to add some explanation of this in #3065.

**Comment by SelenIT** [comment]
IMO the description is OK (though I'm still a bit skeptical about the coloring-only approach in general, honestly).
