### ISSUE TITLE
[css-color] Grays

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#290]
https://drafts.csswg.org/css-color/#grays
> As decided at San Francisco, this syntax is an alias to Lab with a=b=0.

This was a larger issue, but was solved at the San Francisco 2016 f2f. Grays are now syntactic sugar for L=gray, a=b=0.

**Comment by myfonj** [comment]
For those wondering, proposal #3298 `Alias "grey()" to "gray()"?` is _Closed Rejected as Wontfix by Editor Discretion_.
