### ISSUE TITLE
[css-images] drop image-orientation angle values

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#2900]
https://drafts.csswg.org/css-images/#the-image-orientation

The spec mentions in an issue that the angle values for `image-orientation` will probably be dropped. In [bug 1473450](https://bugzilla.mozilla.org/show_bug.cgi?id=1473450) I just removed Firefox's support for the angle values, and I don't think there were any other implementations. So it may be a good time to remove them now.

**Comment by fantasai** [comment]
These values need to stay in the spec because they were referenced from some specifications for printer implementations (and implemented in those implementations). We can remove them in L4, though.

**Comment by tabatkins** [comment]
But for a previous issue (#2767) we *did* resolve to mark them as optional and deprecated.

I just pushed a commit (<https://github.com/w3c/csswg-drafts/commit/3c40a0d7c4fa4fe2bb4fafc225c82556d80f6d16>) that makes this distinction even clearer.

Does this work for you, @heycam?
