### ISSUE TITLE
Add new units 'vl', 'vb' to represent the logical viewport length of vw, vh

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#2901]
Please consider adding new units 'vl', 'vb' to represent the logical viewport length of vw, vh.

Which corresponds to which is simply determined by the current writing-mode of the applied element.

This is very useful for writing-mode responsive design.

**Comment by tabatkins** [comment]
Today's your lucky day - these already exist! ^_^ https://drafts.csswg.org/css-values/#viewport-relative-lengths

**Comment by Zhang-Junzhi** [comment]
@tabatkins Wow, nice! Thank you, I didn't notice that's in Level 4
