### ISSUE TITLE
[css-overflow-3] Allowing (or not) alternate ellipsis behavior for block-overflow

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#2905]
The spec says:
> If there is no next fragmentation container and thus the remainder of the content after the break would be discarded, then the UA may visually replace the contents of the line, as it does for text-overflow.

in https://github.com/w3c/csswg-drafts/issues/390#issuecomment-372143424, Mats Palmgren said:

> I think this "may" should be changed to a "must", or alternatively, the entire sentence be removed. I don't see any upsides to allowing UAs to have incompatible behavior for this common case.

The idea was that the behavior allowed by this "may" sentence was worse, and that we wanted browsers to do the full thing, but that it was more involved, and that doing it as a visual replacement was a tolerable approximation (only in the case of no subsequent fragmentainer).

If implementors are OK with going with the full thing, I'd be happy about deleting that.

**Comment by frivoal** [comment]
Follow up from @fantasai 

> Your third option for placing the ellipsis seems pretty reasonable to me. When drafting up the spec we wanted to allow implementations to re-use as much of the existing text-overflow machinery as possible, hence the MAY -- as long as you're otherwise discarding content after the break, placing it effectively “underneath” the ellipsis for event handling is fine. It's only when the content needs to be pushed to another container that we need to make the ellipsis replace it layout-wise rather than just paint-wise.
> 
> In typical cases, the author will not be able to tell the difference between the two behaviors. But layout replacement can affect the height of the line, which makes it a more complicated mechanism to implement correctly (and as noted, can introduce cycles, which then need to be broken). I would rather not require that extra complexity for this case, where it is not needed and the behavior change in real layouts is slight. (At some point, as we expand CSS's ability to break flows between boxes, we may want to require layout replacement here, to make discarded flows consistent with continued ones; but since such a change seems unlikely to break pages, it seems safe to allow the easier thing now.)

**Comment by frivoal** [comment]
in https://github.com/w3c/csswg-drafts/issues/390#issuecomment-372143424 @MatsPalmgren also said:

> >    The means of breaking any resulting cycles is up to the UA.
>
> Again, vague spec text like this will likely lead to incompatible behavior in different UAs. I'd prefer the spec to say something concrete about how to solve it and make that behavior mandatory.

**Comment by kojiishi** [comment]
It's not clear what "visually replace the contents" means, but from "as it does for text-overflow", if it means UA to layout all the remainder of the content but clipped, I hope us not to require it.

In Sydney, I remember we discussed to make them as if they're `display: none`. We didn't resolve IIUC but that would be more preferrable.

**Comment by frivoal** [comment]
This is not supposed to be about all the remaining content, only about the content in the last line before the break. This is about how to hide enough of it that there is room for the ellipsis on that line.

**Comment by kojiishi** [comment]
Oh, I see, only about the part hidden by ellipsis. Thank you for the correction.

For that part, I haven't done much serious investigation for how to implement, but if we want to honor the break opportunities and its related CSS properties, I think we'll want to use layout. I'm hoping we can re-use existing code for hyphenation for this purpose.

If it's only at grapheme boundary, I agree that using `text-overflow` code might be easier. But then changing it to MUST may make us harder to support break opportunity properties in future.

**Comment by frivoal** [comment]
The preferred behavior has been merged in (See https://github.com/w3c/csswg-drafts/pull/3263). However, as have left the allowance for the alternative behavior, with a clarifying note saying that this is less preferred, and may be removed in later levels.

The reason for keeping it is that as Mozilla is looking at implementing this, @heycam said he prefered to do the visual replacement behavior in the initial phase, to avoid blocking the whole feature on a relatively minor part of it.

In the long run, I believe we all agree as to what the desirable behavior is, so this is just a question of whether we allow ourselves to take some shortcuts initially or not.

Agenda+ to confirm

**Comment by frivoal** [comment]
After further discussions with @heycam, we've concluded that the spec should just describe the desired behavior, and that while implementations may chose to take shortcuts in the initial implementation, the spec shouldn't concern itself with that.
So, we now have:
* Specified a behavior for inserting the ellipsis that doesn't cause loops
* Removed the allowance for doing something simpler
* Added a note in the -webkit- compat section that legacy implementations may be somewhat weird, but that we hope to fix that in due time.
