### ISSUE TITLE
[css-text] A single leading white-space should prevent word breaking honoring white-space: pre-wrap

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#2907]
Lets considering this simple test case:

```
<!DOCTYPE html>
<style>
div {
  font-family: Ahem;
  font-size: 20px;
  line-height: 1;
  white-space: pre-wrap;
  width: 2ch;
  border: 2px solid blue;
}
.ch1 {
  width: 1ch;
}
.break-all {
  word-break: break-all;
  border-color: red;
}
.break-word {
  word-wrap: break-word;
  border-color: orange;
}
.break-break-word {
  word-break: break-word;
  border-color: purple;
}
</style>
<div>  xx</div>
<div class="ch1"> xx</div>
<div class="break-word"> xx</div>
<div class="ch1 break-word"> xx</div>
<div class="break-break-word"> xx</div>
<div class="ch1 break-break-word"> xx</div>
<div class="break-all"> xx</div>
<div class="ch1 break-all"> xx</div>
```
The spec prose about the **pre-wrap** value is clear in this case: 

https://drafts.csswg.org/css-text-3/#white-space-phase-1
> If white-space is set to pre or pre-wrap, any sequence of spaces is treated as a sequence of non-breaking spaces. However, a soft wrap opportunity exists at the end of the sequence. 

So, we got, as expected, the same result in all lf the major browsers:

<table>
<tr><td colspan="5">Case 1.1: &lt;div>  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42541255-ecc44e0e-84a1-11e8-8490-c8765036499f.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541255-ecc44e0e-84a1-11e8-8490-c8765036499f.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541255-ecc44e0e-84a1-11e8-8490-c8765036499f.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541255-ecc44e0e-84a1-11e8-8490-c8765036499f.png"/></td></tr>
<tr><td colspan="5">Case 1.2: &lt;div class="ch1">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42541972-f0fb3eb2-84a4-11e8-9727-dcfba94e7740.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541972-f0fb3eb2-84a4-11e8-9727-dcfba94e7740.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541972-f0fb3eb2-84a4-11e8-9727-dcfba94e7740.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541972-f0fb3eb2-84a4-11e8-9727-dcfba94e7740.png"/></td></tr>
</table>

If we use the **word-wrap: break-word** in combination with the _pre-wrap_, we introduce additional breaking opportunities to avoid the overflow:

<table>
<tr><td colspan="5">Case 2.1: &lt;div class="break-word">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42564082-1a4e23e6-8500-11e8-9a6f-2905e24fa787.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42564083-1a6d2174-8500-11e8-9a45-eff2254498ad.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42564083-1a6d2174-8500-11e8-9a45-eff2254498ad.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42564083-1a6d2174-8500-11e8-9a45-eff2254498ad.png"/></td></tr>
<tr><td colspan="5">Case 2.2: &lt;div class="ch1 break-word">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42565064-ae196ae8-8502-11e8-9e88-cfde8b13ae24.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42565064-ae196ae8-8502-11e8-9e88-cfde8b13ae24.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42565064-ae196ae8-8502-11e8-9e88-cfde8b13ae24.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42565064-ae196ae8-8502-11e8-9e88-cfde8b13ae24.png"/></td></tr>
</table>
 
Chrome diverges from the behavior the rest of the browsers follow in the case 2.1. I think it's a clear bug, since the leading _white-space_ is an actual breaking opportunity that avoids the overflow, hence, no need to apply the _word-wrap_ property in this case, which will imply breaking the word. In the case 2.2, though, all the browsers are interoperable and there is no way to avoid breaking the word. I'd like to remark that all of them apply the _pre-wrap_ value and breaks in the leading white-space. 

I think there are no doubts, so far, but lets consider now what would happen if we use the **work-break** property instead of the _word-wrap_. As far as I understand, the _word-wrap_ property is applied **after** considering all the breaking opportunities, and only in the case that the word still overflows, we can apply the additional line-breaking opportunities, depending on the specific value of the _word-wrap_ property.

However, in the case of the _word-break_ property, the new breaking opportunities must be evaluated at the same time than the ones provided by the white-space property. Lets consider now the case of **word-break: break-word**; this is how each browser behaves in this case:

<table>
<tr><td colspan="5">Case 3.1: &lt;div class="break-break-word">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42566889-563c2be8-8508-11e8-961a-cfb7efa1e4b7.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42566888-561aae6e-8508-11e8-931d-f3a01a778476.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42566888-561aae6e-8508-11e8-931d-f3a01a778476.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42566888-561aae6e-8508-11e8-931d-f3a01a778476.png"/></td></tr>
<tr><td colspan="5">Case 3.2: &lt;div class="ch1 break-break-word">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42567870-8221b0d6-850b-11e8-8c13-862f60bd99c0.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42567871-823accf6-850b-11e8-91de-b8c136f65c22.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42567870-8221b0d6-850b-11e8-8c13-862f60bd99c0.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42567871-823accf6-850b-11e8-91de-b8c136f65c22.png"/></td></tr>
</table>

Chrome also diverges in Case 3.1 from the rest of the browsers; however, **Firefox and Edge don't implement the break-word** value, since it was removed in the last draft of the CSS Text spec. Hence, the comparison is only valid with Safari, which I think implements the right behavior. As it was commented in Case 2.1, the word shouldn't be broken if there are other breaking opportunities before, in this case, the leading _white-space_. This is also the default behavior applied by Firefox and Edge since they parse the _break-word_ as invalid.

Finally, lets evaluate what happens if we use **word-break: break-all** value, which is still defined in the last draft of the spec and indeed implemented by all the browsers:

<table>
<tr><td colspan="5">Case 4.1: &lt;div class="break-all">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42568895-ec0b7a06-850e-11e8-9507-67ce36f6276b.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42568895-ec0b7a06-850e-11e8-9507-67ce36f6276b.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42568896-ec2eca88-850e-11e8-9ea8-ad87fbf21e80.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42568895-ec0b7a06-850e-11e8-9507-67ce36f6276b.png"/></td></tr>
<tr><td colspan="5">Case 4.2: &lt;div class="ch1 break-all">  xx&lt;/div></td></tr>
<tr><td>Chorme</td><td>Firefox</td><td>Safari</td><td>Edge</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42569274-495c1f8e-8510-11e8-9e44-ce2e988ea840.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42569275-497cfc54-8510-11e8-920e-749b40c25349.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42569275-497cfc54-8510-11e8-920e-749b40c25349.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42569275-497cfc54-8510-11e8-920e-749b40c25349.png"/></td></tr>
</table>

Only Safari shows a different behavior in Case 4.1, which uses the leading white-spaces as priority breaking opportunity, so it doesn't need to break the word. As it was commented before, I think this is the correct and most coherent behavior; I don't see why we need to break the word if it's not necessary. 

The case 4.2 is different, since even breaking at the leading white-space, there is no enough space for the word, hence, honoring the _break-all_ value, the word is broken to avoid the overflow. Chrome is diverging in this case and it actually lead to overflow, which I think it's incorrect because it's perfectly avoidable.

The following table describes my proposal for each of the cases analyzed before:

<table>
<tr><td>Case 1.1</td><td>Case 1.2</td><td>Case 2.1</td><td>Case 2.2</td><td>Case 3.1</td><td>Case 3.2</td><td>Case 4.1</td><td>Case 4.2</td><tr>
<tr><td colspan="2" align="center">pre-wrap</td><td colspan="2" align="center">pre-wrap+word-wrap</td><td colspan="2" align="center">pre-wrap+break-word</td><td colspan="2" align="center">pre-wrap+break-all</td><tr>
<tr><td><img src="https://user-images.githubusercontent.com/2230241/42541255-ecc44e0e-84a1-11e8-8490-c8765036499f.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42541972-f0fb3eb2-84a4-11e8-9727-dcfba94e7740.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42564083-1a6d2174-8500-11e8-9a45-eff2254498ad.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42565064-ae196ae8-8502-11e8-9e88-cfde8b13ae24.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42566888-561aae6e-8508-11e8-931d-f3a01a778476.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42567870-8221b0d6-850b-11e8-8c13-862f60bd99c0.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42568896-ec2eca88-850e-11e8-9ea8-ad87fbf21e80.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/42569275-497cfc54-8510-11e8-920e-749b40c25349.png"/></td></tr>
</table>

My proposal **matches Safaris's behavior** in all the cases and it basically avoids to break the word in any case if there are other soft-breaking opportunities before.

**Comment by kojiishi** [comment]
I think the expectations for case 1.1 and case 4.1 are opposite. Is that mistake or intention?

**Comment by javifernandez** [comment]
> I think the expectations for case 1.1 and case 4.1 are opposite. Is that mistake or intention?

The case 1.1 was incorrect , indeed. My proposal for case 4.1 was correct, though.
I already updated the data.

**Comment by SelenIT** [comment]
My intuitive expectation from `word-break:break-all` is that each letter is treated as a separate "word" (as CJK ideographs usually do), so I expect the break opportunities on each word boundary to have the same priority (i.e. the break opportunity after the white space should _not_ be prioritized above the break opportunity between the letters). That's why I expect the example 4 to render the same way as example 3 in Chrome. This is also consistent with what _most_ browsers do (so it would need only Chrome to fix behavior in 4.2 and Safari to fix behavior in 4.1 to get the complete interoperability across browsers).

**Comment by kojiishi** [comment]
> The case 1.1 was incorrect , indeed. My proposal for case 4.1 was correct, though.
I already updated the data.

Thank you for the clarification. Then I agree, except 4.1.

**Comment by kojiishi** [comment]
Can you please clarify, whether this issue is proposing a change to the current spec, or asking confirmation of your understanding of the current spec?

**Comment by javifernandez** [comment]
I'm asking confirmation of my understanding of current spec, indeed. I could't find where in the spec is stated that opportunities generated by break-all should go first than the ones provided by pre-wrap.

The second paragraph of the Line Breaking section states the following: 

https://drafts.csswg.org/css-text-3/#line-breaking

> Wrapping is only performed at an allowed break point, called a soft wrap opportunity. When wrapping is enabled (see white-space), the UA must minimize the amount of content overflowing a line by wrapping the line at a soft wrap opportunity, if one exists.

I understand from that that wrapping, when enabled, should be one of the first steps. Then, in the white-space processing phase, the spec states the following:

https://drafts.csswg.org/css-text-3/#white-space-phase-1

> If white-space is set to pre, pre-wrap, or break-spaces any sequence of spaces is treated as a sequence of non-breaking spaces. However, a soft wrap opportunity exists at the end of the sequence.
> 
> Then, the entire block is rendered. Inlines are laid out, taking bidi reordering into account, and wrapping as specified by the white-space property.

My understanding of the current spec is that in the cases we are evaluating here, the line-wrapping after the single leading white-space should happen first and, only then, apply additional breaking opportunities if needed, to avoid overflow.

**Comment by SelenIT** [comment]
I can't find anywhere in the spec that the white-space processing phase should come _after_ the wrapping. My understanding is that the white-space processing phase should come _before_ it, because otherwise the browser wouldn't know whether this space would be removed or not, so it would not be able to determine whether the wrapping after the initial white space is needed.

I assume that `word-wrap: break-all` simply increases the number of possible places where wrapping can occur, _if needed_, and when the better opportunity is present, then the break after the space becomes not needed.

**Comment by javifernandez** [comment]
> I can't find anywhere in the spec that the white-space processing phase should come after the wrapping. My understanding is that the white-space processing phase should come before it, because otherwise the browser wouldn't know whether this space would be removed or not, so it would not be able to determine whether the wrapping after the initial white space is needed.

I'm not sure whether we are under violent agreement here :) my point is that white-space processing should be first, indeed. That's why I think that in the cases we are evaluating, we should wrap the text so that the word is moved down to the next line. Then, only if it still overflows, we can apply additional breaking opportunities, like the ones provided by break-all. That's what I understand from the following sentence:

https://drafts.csswg.org/css-text-3/#line-breaking
> the UA must minimize the amount of content overflowing a line by wrapping the line at a soft wrap opportunity, if one exists.

**Comment by SelenIT** [comment]
I believe so should work `overflow-break: break-word`, but not `word-break: break-all`. Since `work-break` is already applied, the content has soft break opportunities before/after any character (i.e. letters effectively don't make a "word" anymore), so one letter _would not_ cause overflowing, but two letters would, so _the second_ letter should be wrapped to the new line. In my understanding, the word "additional" for the wrap opportunities created by `word-break` doesn't mean "secondary" (and doesn't imply that other wrap opportunities were "primary"), it just means that the content has more wrap opportunities with the `break-all` value than without it.

**Comment by kojiishi** [comment]
> Then, only if it still overflows, we can apply additional breaking opportunities, like the ones provided by break-all.

This is not correct. The `overflow-wrap` property is for this purpose, it re-run the line breaker with additional break opportunities.

However, the `word-break` property and the 'line-break' property gives the additional break opportunity in all cases, regardless of it overflows or not. In other words, these properties are to change the break opportunities.

If the line overflows with the given break opportunities, then the `overflow-wrap` property kicks in.

**Comment by javifernandez** [comment]
I can understand and agree that breaking opportunities introduced by break-all have the same priority than the ones introduced by pre-wrap. However, how we can decide then what opportunity is better ? In the cases we are evaluating here, we can either break after the leading white-space or after the first character. Both prevents overflow (assuming 2ch width). Should we leave it open to the UA then ?

**Comment by SelenIT** [comment]
My understanding is that among the wrap opportunities with the same priority the last opportunity that still prevents overflow should be preferred. I expect that the browser will try to put in the line as much content as it's possible with the current settings, with no "premature" wrapping.

**Comment by javifernandez** [comment]
Ok, makes sense.

**Comment by kojiishi** [comment]
That looks good to me.

I noticed I mostly just repeated what @SelenIT said, should have read more before I comment, sorry for the dup content and thanks for @SelenIT!

**Comment by frivoal** [comment]
Unless someone wants to suggest a spec change based on the above analysis (which I don't think is the case based on previous comments), I think we can close this. Anyone disagrees?

**Comment by frivoal** [comment]
This was really a discussion / quesiton, not an actual issue report against the spec. Since the discussion is concluded, I'm closing.
