### ISSUE TITLE
[css-color] fallback syntax

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#291]
https://drafts.csswg.org/css-color/#icc-colors

> color() fallback should be like font list fallback, as decided at San Francisco. Recursive?

Fallback syntax is currently underspecified. Maybe it should be a <color> value or maybe it allows the full range of color specifications including lab(), color() and so on. Maybe just one value or maybe a (comma separated, like the font stack fallback syntax) list.

My preference would be to allow the full range of color specifications and to allow a list (so for example I could put something with a large ICC profile as the first choice, but give an lab fallback and then an sRGB fallback after that).

**Comment by svgeesus** [comment]
later in the same section (these two issues are the same)
> Further define a fallback color, as decided at San Francisco. Can be an sRGB fallback or indeed another color() function.

**Comment by tabatkins** [comment]
Unsure what's hard here.  fallback should clearly just be a `<color>`.

**Comment by bradkemper** [comment]
Having more than one fallback of color() values means deeper and deeper nesting inside parentheses, which looks bad. If commas were eliminated for everything other than separation of the items in the fallback list, then nested functions wouldn't be needed (just complete compound values separated by commas).

Slashes could be used to separate color channels from alphas and profile names.

**Comment by svgeesus** [comment]
The ICC feature was moved to Color 4

**Comment by svgeesus** [comment]
The ICC feature was moved to Color 4

**Comment by svgeesus** [comment]
Closing, the [`color()` fallback](https://drafts.csswg.org/css-color-4/#color-function) was defined long ago
