### ISSUE TITLE
[css-align] [css-flexbox] [css-overflow] [css-rhythm] [css-shapes] [css-ui] Missing quotes around property refs

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#2912]
According to the [Value Definition Syntax](https://drafts.csswg.org/css-values/#component-types), for "types that that have the same range of values as a property bearing the same name", "the type name is the property name (**complete with quotes**)".

If I'm reading the above syntax correctly, the quotes appear to be missing in a few property definitions and should be added in:
- Alignment: [`place-items`](https://drafts.csswg.org/css-align/#propdef-place-items)
- Flexbox: [`flex-flow`](https://drafts.csswg.org/css-flexbox/#propdef-flex-flow)
- Overflow: [`line-clamp`](https://drafts.csswg.org/css-overflow/#propdef-line-clamp)
- Rhythm: [`block-step`](https://drafts.csswg.org/css-rhythm/#block-step)
- Shapes Level 1: [`polygon()`](https://drafts.csswg.org/css-shapes-1/#funcdef-polygon)
- Shapes Level 2: [`path()`](https://drafts.csswg.org/css-shapes-2/#funcdef-path)
- UI: [`outline`](https://drafts.csswg.org/css-ui-4/#propdef-outline)

**Comment by tabatkins** [comment]
The markup is correct, this is a Bikeshed bug. I'll look into it.

**Comment by tabatkins** [comment]
I like, this is a markup error. They're written in the source file as `<'justify-items'>`, when they should be `<<'justify-items'>>`, to get properly recognized as grammar non-terminals. In the absence of that they're just getting recognized as property/value links, with raw text `<` and `>` characters. (Luckily the single quotes prevent them from being parsed as start tags!)

**Comment by fantasai** [comment]
Ok, I committed changes to fix all these. Couldn't figure out what error you were referring to for css-shapes-1/2, though?

Thanks for the report!!

**Comment by astearns** [comment]
fixed fill-rule with https://github.com/w3c/csswg-drafts/commit/81afc493bdd8f083b2c7eb55106d226cbe21ea3e
