### ISSUE TITLE
[css-grid] What value for position:absolute's getComputedStyle left (for display:grid)

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#2913]
The value interoperably returned by Chrome and Firefox for this case doesn't round trip:
https://wptest.center/#/31dvt6

Should I filed bugs for the browsers, or is that the expected behavior?

**Comment by tabatkins** [comment]
Definitely not intended, it should be zero.  gCS() should *never* be returning values that don't round-trip (except, *maybe*, for rounding issues or something).

**Comment by fantasai** [comment]
Closing out Invalid, yes, please file bugs.

**Comment by FremyCompany** [comment]
Ok, thanks for confirming my point of view; bugs now filed:
> https://bugs.chromium.org/p/chromium/issues/detail?id=867616
> https://bugzilla.mozilla.org/show_bug.cgi?id=1478485
