### ISSUE TITLE
[css-fonts] Missing quotes in <feature-value-block> dfn

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#2915]
The [`<feature-value-block>` definition](https://drafts.csswg.org/css-fonts-4/#font-feature-values-syntax) uses `{` and `}` without quotes. These characters have special meanings in the [Value Definition Syntax](https://drafts.csswg.org/css-values-4/#component-types) and should be "enclosed in single quotes".

**Comment by litherum** [comment]
So the Bikeshed source should look like `'{'`?

**Comment by tabatkins** [comment]
Nope, these are allowed to be used literally when writing rule definitions, see <https://drafts.csswg.org/css-syntax/#rule-defs>.
