### ISSUE TITLE
[css-backgrounds] Incorrect value dfn for border-color and background-clip

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#2916]
The [`border-color` definition](https://drafts.csswg.org/css-backgrounds-4/#propdef-border-color) seems to be using parentheses for grouping instead of brackets as described in [Component value combinators](https://drafts.csswg.org/css-values-4/#component-combinators). Correct value should be `[<color>{1,4}]#`.

Also, the "Value" header link is wrong, it should target `https://drafts.csswg.org/css-backgrounds-4/#values` as in all other property definition tables.

Similarly, I would expect to be able to parse the [new values of `background-clip`](https://drafts.csswg.org/css-backgrounds-4/#background-clip) using the usual Value Definition Syntax. For that to be possible, value should be `text | border`, and not `text, border`.

**Comment by tidoust** [comment]
I don't want to make things unnecessarily complicated but something I had overlooked in this case is that the [definition of `background-clip`](https://drafts.csswg.org/css-backgrounds-3/#propdef-background-clip) is `<box>#`, and "New value" actually extends `<box>` (defined as `border-box | padding-box | content-box`), not the property itself.

In other words, the spec probably wants the final property to be defined as `[ border-box | padding-box | content-box | text | border ] #` and not as `<box># | text | border`, the latter being what a strict application of the rules would yield.

**Comment by tabatkins** [comment]
Ah, indeed.

**Comment by tabatkins** [comment]
Well, hm. I don't want to repeat the `<box>` values. I think what I want to do is redefine the property entirely to `<bg-clip-value>#`, and then define that to be `<box> | border | text`.
