### ISSUE TITLE
[css-grid] Not clear how to read the <name-repeat> dfn

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#2917]
The [`<name-repeat>` definition](https://drafts.csswg.org/css-grid-2/#typedef-name-repeat) is currently set to `repeat( [  | auto-fill ], +)`.

I'm not clear how to interpret that value:
- Does `[ | auto-fill ]` mean an empty value is allowed?
- What does the `+` apply to? Shouldn't the definition use `#` (and drop the comma)?

**Comment by tabatkins** [comment]
That was a typo in the spec source - the non-terminals weren't written right, so Bikeshed didn't turn them into links, and they instead got parsed as start tags. ^_^
