### ISSUE TITLE
[css-color] predefined spaces

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#292]
> Decided at San Francisco to add a larger set of common predefined spaces like AdobeRGB, ProPhoto RGB, and so on. Also coated and uncoated swop, etc, etc.

Needs further discussion.

**Comment by tabatkins** [comment]
Elaborate on what else needs to be discussed, so we can prep for the call?

**Comment by grorg** [comment]
Why don't we start with a small set of predefined spaces? In this case I don't see much point defining shortcuts until there is demand.

At the moment, Apple only needs "Display P3" (we can provide the ICC file if there are no references available).

The next most important (IMO) is AdobeRGB, because it is so popular in digital cameras. Then maybe ProPhoto RGB.

I don't think we need to have anything more than this at the moment. If we do, I expect implementations to start getting reluctant.

**Comment by grorg** [comment]
Actually, maybe I misinterpreted the request. I'm fine with defining shortcuts to well-known profiles, as long as I don't have to provide support for all of them 😄 

I'm not even sure we should require support for any particular profile?

**Comment by svgeesus** [comment]
So this could be done two ways. 

One is to provide the same info we do for dci-p3 and rec.2020 - a table of red, green, blue and white chromaticities and the transfer curve. That allows conversion to Lab and thus to any other colorspace, for colors in gamut. It does not define handling for colors outside of gamut (and I think we should define it, including black point compensation, equivalent to the "relative colorimetric" rendering intent so in-gamut colors are faithfully preserved and we can have interop.

The other is to provide an ICC profile and require browsers to act as if this has been specified with an @profile with a local descriptor (rather than a src). That gives you whatever rendering intent (or intents, for those few profiles that have more than one) the profile specifies and gives you whatever handling of out of gamut colors that intent has. (for perceptual intent, it will also affect in-gamut colors). And it requires deciding on ICC v.2 or ICC v.4.

I think my preference would be to do the table like dci-pr3 and rec.2020 have. Dino, an ICC profile would still be very helpful to me because I can look inside it and see what it says.  Also agree about AdobeRGB (once we get assurance from Adobe about the trademark issue) and ProPhoto, both for the digital SLR crowd.

**Comment by svgeesus** [comment]
It would be good to add a predefined CMYK space, but we don't have to do that in this level. 

On the one hand, CMYK (and other printer) profiles are much larger than RGB ones, so having a fallback to a predefined CMYK colorspace avoids delays while a large profile loads.

On the other hand, CMYK profiles are more likely to be used in print or mixed print/web workflows which may well use offline rendering to PDF for the print part and can stand to wait for a profile to load. And SWOP is US-centric, so adding just that one could be problematic.

I don't oppose adding a CMYK predefined profile in this level, but won't object of we don't, either. it depends more on what the likely users and implementors, such as publishers, want.

**Comment by svgeesus** [comment]
20 July 2016 CSS telcon:
RESOLVED: add AbobeRGB and ProPhotoRGB as predefined spaces. Allow either the table of numbers or an ICC v.4 profile with relative colorimetric intent
RESOLVED: Add a single CMYK profile, with relative colorimetric intent, mainly to use as a fallback

**Comment by cabanier** [comment]
> RESOLVED: add AbobeRGB and ProPhotoRGB as predefined spaces. Allow either the table of numbers or an ICC v.4 profile with relative colorimetric intent

You can include the AdobeRGB name in the spec but you will have to sign a license agreement with Adobe.
However, you can come up with your own name of a profile that uses identical values and say that it's "compatible with Adobe RGB"

**Comment by svgeesus** [comment]
Thanks Rik. I'm discussing the licensing issue with Steve Zilles. Hopefully we can do better than "compatible with".

**Comment by cabanier** [comment]
> Hopefully we can do better than "compatible with".

Well, the wording has to be similar to that and it should be "Adobe RGB" and not "AdobeRGB"

**Comment by svgeesus** [comment]
Closing as done, for the RGB spaces mentioned by @grorg and opening a new issue for the predefined CMYK bit.
