### ISSUE TITLE
[css-fonts] Unexpected "see prose" value for src descriptor

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#2920]
In most CSS specs, the "Value" cell contains a string that follows the [Value Definition Syntax](https://drafts.csswg.org/css-values-4/#value-defs). However, the [`src` descriptor](https://drafts.csswg.org/css-fonts-4/#descdef-font-face-src) has "see prose" as value which does not describe the actual value that the descriptor can have. While this is clear for human beings, this makes automatic extraction of values from the spec difficult.

In Level 3, the descriptor was defined as `[ <url> [format(<string> #)]? | <font-face-name> ] # `. Is that no longer possible?

**Comment by litherum** [comment]
This is no longer possible, due to https://github.com/w3c/csswg-drafts/issues/633

The parsing rules are no longer "parse the value according to this grammar." Instead, there are loops involved, etc.
