### ISSUE TITLE
[css-inline] Should dominant-baseline inherit?

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#2926]
We have inconsistencies between specifications and between implementations.

It isn't clear if dominant-baseline was intentionally made inherited when it moved from SVG to CSS Inline 3, or if this change was accidental during transcription.

https://www.w3.org/TR/css-inline-3/#propdef-dominant-baseline
Inherited: yes

>     commit 107993abb5a370cb1fb7d343a2bb93c4d4cc3135
>     Author: fantasai <fantasai.cvs@inkedblade.net>
>     Date:   Wed Feb 11 07:01:56 2015 -0500
>     [css-inline] Draft vertical-align stuff imported from SVG.
> 

https://www.w3.org/TR/SVG11/text.html#DominantBaselineProperty

> Inherited:    no

https://svgwg.org/svg2-draft/propidx.html

> "This appendix is informative, not normative."
> Name, Inh.
> dominant-baseline, no
> 

https://drafts.csswg.org/css-writing-modes-3/#baseline-alignment
talks about parent’s dominant baseline and child’s dominant baseline.

Blink: does inherit

>     https://codereview.chromium.org/1241163002 (2015)
>     Update dominant-baseline property as inheritable property
>     as per spec.
>     http://dev.w3.org/csswg/css-inline/#dominant-baseline
> 

Edge: does not inherit
Firefox: does not inherit
Safari: does not inherit

**Comment by tabatkins** [comment]
Almost certainly a mistake, there's no reason we'd have changed this during the port, that would break things.

**Comment by tabatkins** [comment]
@fantasai Just to confirm, this was a mistake, right? Easy fix if so.

**Comment by fantasai** [comment]
`dominant-baseline` should definitely inherit. Otherwise it would reset itself to the initial value every time someone introduces a `<span>` or `<a>`!

**Comment by fantasai** [comment]
And then you couldn't set it on a document and expect it to take effect across the entire thing, properly excepting sections which need a different `dominant-baseline`.

The change was deliberate. The SVG1.1 definition of `auto` has more magic than ours: it behaves like `inherit` when you set it on a descendant of a `<text>` element. You can get away with that if you don't have much structure, as SVG1.1 text doesn't, but it is unworkable in a structured markup language like HTML.

**Comment by fantasai** [comment]
Agenda+ to bring this to the attention of the rest of the WG.
