### ISSUE TITLE
[css-logical][quirks] Should logical properties allow the unitless length quirk?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2928]
According to https://quirks.spec.whatwg.org/#the-unitless-length-quirk, some properties which accept a `<length>` must also accept a `<quirky-length>` in quirks mode.

Various of these properties have corresponding logical properties, which behave more or less like an alias. Should the logical properties accept a `<quirky-length>` too?

I was assuming that it shouldn't be accepted. However, I noticed that Chromium allows it in [these logical properties](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/parser/css_property_parser_helpers.h?l=43&gs=kythe%253A%252F%252Fchromium%253Flang%253Dc%25252B%25252B%253Fpath%253Dsrc%252Fthird_party%252Fblink%252Frenderer%252Fcore%252Fcss%252Fparser%252Fcss_property_parser_helpers.h%2523ELcMnFMw0FiSYjySI9soH2cMoXCO3OJ6%25252BhKfFjoqfh8%25253D&gsn=kAllow&ct=xref_usages):
 - `scroll-margin-block-end`, `scroll-margin-block-start`, `scroll-margin-inline-end`, `scroll-margin-inline-start`
 - `scroll-padding-block-end`, `scroll-padding-block-start`, `scroll-padding-inline-end`, `scroll-padding-inline-start`

It's not allowed in the [other logicals](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/parser/css_property_parser_helpers.h?l=43&gs=kythe%253A%252F%252Fchromium%253Flang%253Dc%25252B%25252B%253Fpath%253Dsrc%252Fthird_party%252Fblink%252Frenderer%252Fcore%252Fcss%252Fparser%252Fcss_property_parser_helpers.h%2523nhabkiztQB4yWSkXYJIDlbGwlEQmdFMz6Ag05c20bo4%25253D&gsn=kForbid&ct=xref_usages).

I didn't test them all but it seems that Firefox doesn't allow unitless lengths either.

**Comment by tabatkins** [comment]
Given the inconsistent support for it in our properties, it seems clear that it's just an accident, not an intentional choice. We should stick with "not allowed", as that quirk doesn't need to be spread any further.

**Comment by ewilligers** [comment]
Now [fixed](https://chromium-review.googlesource.com/c/chromium/src/+/1144991) in Blink, with all browsers passing the WPT. This issue can be closed.

**Comment by Loirooriol** [comment]
OK, thanks
