### ISSUE TITLE
[css-scroll-snap] Different browsers implement keypress scrolling differently

### ISSUE THREAD

**Issue by cruxicheiros** [w3c/csswg-drafts#2929]
**Relevant section:** https://drafts.csswg.org/css-scroll-snap/#scroll-padding
**Related to thread** "define scroll amount by CSS" http://lists.w3.org/Archives/Public/www-style/2018Jul/subject.html

CSS Scroll Snap introduces the attribute `scroll-padding` which allows CSS style sheets to specify an offset that the page will not scroll into when the `space` or `page down` buttons are used to scroll. This is important because otherwise, text that the user had not yet scrolled to would be hidden behind the header.

However, Firefox attempts to automatically detect sticky headers and does this already (described in [this Bugzilla post](https://bugzilla.mozilla.org/show_bug.cgi?id=780345). From my testing, Chrome, Edge, and Opera do not have this feature, making Firefox the odd one out.

I have created a [demo site](https://cruxicheiros.github.io/scrollamountdemo/) to help easily demonstrate this difference.

The reason this is relevant to CSS Scroll Snap is that with its introduction, guidance should be given on how scrolling should work when the attribute is not present. Scrolling behaviour should be standard across browsers.

Firefox's approach has benefits in that it fixes the problem `scroll-padding` aims to solve on already-existing websites. Therefore it might be beneficial for other browsers to do similarly. However, this could result in clashes when `scroll-padding` is used in a stylesheet on a website the browser has detected as using a fixed header and has already applied an offset to.

Firefox's detector, however, is not perfect and does not work on all sites. [This page is an example where the offset should be applied and isn't.
](http://www.thisisplace.org/i/?id=0150beca-e3f5-47e0-bc74-9ccc5ef1db8a)

Thank you.

**Comment by majido** [comment]
> Firefox's approach has benefits in that it fixes the problem scroll-padding aims to solve on already-existing websites. Therefore it might be beneficial for other browsers to do similarly. 

Perhaps it is beneficial for other browsers to implement this. But that is not something that we need to spec but rather an optimization that each browser can decide on. Similar to how the actual amount that implementations consider a "page" is implementation specific.

More concretely, Firefox detection is based on a heuristic with many caveats. I don't think we should specify anything like that. 

The good news is that now their behavior can be described based on the new concept ('scroll port viewing region'?) introduced in the specification. Perhaps we can/should add a note that implementations are allowed to adjust scroll port viewing region if there is  not user specified `scroll-padding`.

> However, this could result in clashes when scroll-padding is used in a stylesheet on a website the browser has detected as using a fixed header and has already applied an offset to.

I think this will be a bug for browsers that have additional heuristics. In particular, if authors have
specified a `scroll-padding` the browser should not employ additional heuristics. See my suggestion above to add a note that should clarify this.

**Comment by fantasai** [comment]
It seems like `scroll-padding` should have `auto` as its initial value, then. This makes the interaction with author-specified `scroll-padding` very straightforward. (I remember suggesting this at some point, and it was decided not to complicate things by adding it. But if Firefox is already using some heuristics, then it might be worth doing.)

Whether we specify the heuristics or not is a different question, but also one worth investigating.

**Comment by majido** [comment]
Introducing 'auto' as initial value sounds good to me.

As for specifying a heuristic, are there example of cases where this was done. I am curious what something like that may look like. It will be also valuable to hear Firefox experience with their heuristic before going down this route.

**Comment by astearns** [comment]
@majido do you know of any WPT tests that check the initial value that would need to be changed?

**Comment by majido** [comment]
I am not aware of any such test. We don't have wpt CSS syntax parsing and initial value tests for css-scroll-snap.

**Comment by tabatkins** [comment]
@cruxicheiros Can you confirm that the edits in 9e4d465 satisfy you?

**Comment by cruxicheiros** [comment]
@tabatkins This resolves it. Thanks.
