### ISSUE TITLE
[css-color] Specification for DCI P3

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#294]
https://drafts.csswg.org/css-color/#predefined

> The defining spec for dci-p3 is not freely available. It costs USD 240. There is a Wikipedia article, which is non-authoritative and of unknown accuracy (particularly for the transfer function and viewing conditions).

wikipedia: https://en.wikipedia.org/wiki/DCI-P3

**Comment by svgeesus** [comment]
Unverified, but another reason to check the actual specification:
> P3 has a different white point than ITU 709 does. ITU 709 monitors are calibrated for a white point of **D65**, whereas P3 uses a white point of **D61**. 
http://www.dvinfo.net/article/optical-science/is-p3-the-new-4k.html

**Comment by svgeesus** [comment]
Confirmed at TPAC Lisbon by Pierre-Anthony Lemieux - what the spec calls DCI P3 is not actually defined in any spec, the transfer function is wrong and it is not used to ship video content to consumers.
What we have is similar to Apple 'display P3' which uses the P3 primaries, a D65 whitepoint (unlike P3) and a 2.2 gamma (unlike P3).

**Comment by tantek** [comment]
"wide color" / "Display P3" appears to be gaining some awareness / traction / support, e.g. https://engineering.instagram.com/bringing-wide-color-to-instagram-5a5481802d7d so we really need to get ahead of this or else we'll just end up specing whatever it is that Apple has decided to implement.

**Comment by svgeesus** [comment]
Related to https://github.com/w3c/csswg-drafts/issues/295

**Comment by svgeesus** [comment]
Closing as moot; CSS Color 4 uses `image-p3` which uses the same primary chromaticities as DCI P3, but differs in transfer function, whitepoint, and viewing conditions.
