### ISSUE TITLE
[css-contain] Is it ok that contain:layout is a CB for fixpos/abspos descendants but doesn't establish a stacking context?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2942]
[The containment spec for `contain:layout`](https://drafts.csswg.org/css-contain/#containment-layout):
* says that `contain:layout` establishes a containing block for absolutely positioned and fixed positioned descendants, but
* does not say that it establishes a stacking context.

This is the first feature in CSS that I'm aware of with this combination.  I think it's worth some consideration of whether this combination is sensible.  Do the painting rules for abspos and fixpos elements contained by such an element work in a reasonable way?

/cc @MReschenberg

**Comment by tabatkins** [comment]
The combination wasn't on purpose; I just didn't realize that the two were tied together like that.

**Comment by dbaron** [comment]
I'm not sure how tied together they are -- but if we're going to keep it this way, somebody needs to think it through.

**Comment by dholbert** [comment]
RE how tied together they are:

Right now, the [CSS painting order algorithm](https://drafts.csswg.org/css2/zindex.html#painting-order) has three different mentions of a special category: `positioned descendants and descendants which actually create a new stacking context`.

Fun fact: up until now, this category has basically been 100% equivalent to "the set of all elements that establish a containing block for abs-pos descendants".  (Please correct me if I'm wrong, but I'm pretty sure these are 100% equivalent!)  However -- with the current contain:layout spec-text, these two categories will be slightly disjoint.  Specifically, `contain:layout` elements will be in the latter category (they establish a containing block) but they might not be in the former category (they're not necessarily positioned themselves, nor do they create a stacking context).

So I think the questions here are:
 - In the CSS Painting Order algorithm, would we want `contain:layout` elements to be included or excluded from the pieces about "positioned descendants and descendants which actually create a new stacking context"?  (And to what extent does this matter?)
 - Does this matter enough to create this new special-case (things which **are** abpsos containing blocks but **are not** themselves positioned nor do they form stacking contexts)?

**Comment by dbaron** [comment]
And @dholbert wrote [comments 13 through 16 of bug 1472919](https://bugzilla.mozilla.org/show_bug.cgi?id=1472919#c13) that show that Gecko code currently assumes this combination doesn't exist, and behaves incorrectly as a result.

**Comment by frivoal** [comment]
As we're not trying to introduce any new complicated thing here, I'd be perfectly fine with creating a new stacking context as well even if it isn't strictly necessary, if that makes things simpler, which seems to be the case in Gecko.

Is that OK for blink? @eaenet @mrego

**Comment by dholbert** [comment]
>  Some of the stacking context triggers do not imply containing block for abs pos. Opacity is one example.

Ah, thank you - that's a good counterexample.  So the two groups aren't 100% equivalent as I'd initially stated, but rather: one group is a subset of the other. Let me restate my observed "rule" more carefully, with that in mind:

Up until now, if an element forms a containing block for abs pos descendants, then that always implies it is in this special "is positioned or forms stacking context" category that's referenced several times in the painting spec.  (And there are a few other things in that category, like "opacity" as you noted.

`contain:layout` would be the first (I think?) exception to this "rule" -- it forms an abs pos containing block, but it's not in the special "is positioned or forms stacking context" category.

> However, I think that making contain:layout a stacking context would be a good change

Great! I'm glad we're in agreement. Thanks for chiming in.

**Comment by mrego** [comment]
I agree with the idea and I think it should be fine to implement it in Chromium.

BTW, I realized that despite paint containment is creating a stacking context in Chromium, it's doing it more than expected even for elements where paint containment doesn't apply. See https://crbug.com/868102

**Comment by frivoal** [comment]
Made a PR for this (#2962). Standing ready to merge if we resolve in favor.

**Comment by dbaron** [comment]
I updated [my big stacking context test](https://dbaron.org/css/test/2018/stacking-context-z-order) to reflect this resolution.

**Comment by frivoal** [comment]
@dbaron is this something you expect to extract individual test cases from and submit to wpt?

**Comment by chrishtr** [comment]
Yes we need testcases submitted to WPT, combined with changes to implementations to adopt
this resolution. I can get that done for Chrome. Can Gecko please implement in parallel?

**Comment by MReschenberg** [comment]
Gecko WIP can be found here https://bugzilla.mozilla.org/show_bug.cgi?id=1472919

**Comment by mrego** [comment]
I have these tests from my experiments in Chromium: https://github.com/web-platform-tests/wpt/pull/12269
