### ISSUE TITLE
[css-scrollbars-1] Rename `scrollbar-width` to `scrollbar-thickness`

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#2966]
https://drafts.csswg.org/css-scrollbars-1/#scrollbar-width

As a scrollbar width only sounds like the thickness of a vertical scrollbar. For a horizontal scrollbar, the meaning of width doesn't seem very clear, the bar thickness is more likely called height of a horizontal scrollbar.

Thickness is just a direction-neutual word. So what about renaming `scrollbar-width` to `scrollbar-thickness`?

**Comment by tabatkins** [comment]
`thickness` is long and not used elsewhere in CSS.

While I don't think `-width` is particularly problematic (it's fairly clear what it refers to from context), is there a reason we're not just using `-size`?

**Comment by Zhang-Junzhi** [comment]
I originally thought of size, but then I thought size also sounds like a scrollbar's inner size, in other words, sounds like the size in the scroll direction. Thickness seems less likely to mean that(this is just my personal sense on the two words. However, I am not a native speaker, ).

**Comment by Zhang-Junzhi** [comment]
But I still prefer size to width.

width is no less ambiguous than size, since size is at least more direction-neutual.

**Comment by jonjohnjohnson** [comment]
> Regarding the concern about terminology raised by <https://github.com/silverwind> about using "width" for horizontal scrollbars, vs the suggested alternative "thickness", note that CSS already has a notion of modifying the width of horizontal and vertical "bars" in the 'border-width' and 'outline-width' properties.

> In particular note the pre-existing 'border-top-width' and 'border-bottom-width' properties (<https://drafts.csswg.org/css-backgrounds-3/#border-width>) which specifically apply to horizontal borders. Thus I think it is both ok and desirable to use "width" to refer to the scrollbar size as well, since it is consistent with those existing properties, and matches what web developers will likely already be familiar with in CSS.

@tantek https://github.com/w3c/csswg-drafts/issues/1958#issuecomment-402576465

**Comment by Zhang-Junzhi** [comment]
There are also properties such as `line-height`, `vertical-align`, `top`(value), `bottom`(value), which were named due to the historical reason, those concepts were introduced before `writing-mode` was introduced(though `border-width` isn't the case), but similar properties and values that were introduced later didn't follow such historical convention(e.g. align-content, start, end), thus turned out for a new property or new value name to be not necessarily consistent with similar older ones.

Also, I personally don't have a strong opinion on using thickness, just perfer a direction-neutual word, if we are worried about naming convention, at least the word `size` is something that is commonly used in CSS.

**Comment by Zhang-Junzhi** [comment]
And further, there's one other thing to be considered:

Maybe some day we may also eventually want to provide ability to control the length of a scrollbar's inner length(the one perpendicular to "width"), so at an early age, the room for naming of the future property may also be considered.

Had we already used `-width`, then later the name for a scrollbar's inner length would have to be accommodate itself to `scrollbar-height`. At the time we have both `-width`, `-height`, ambiguity would be increased for a horizontal scrollbar.

**Comment by fshafique** [comment]
Is there a reason why `-length` cannot be used as the other dimension?

I don't know any other CSS property that uses it, but it also sounds better than `-height` when used with horizontal scrollbars.

**Comment by frivoal** [comment]
In addition to the reasons discussed above, this is no longer practical to change, since it has been shipping for a while in Firefox with the `scrollbar-width` name.
Closing no change.
