### ISSUE TITLE
[css-scrollbars] light/dark colors

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2967]
I think it was Xidorn who explained that one of the main use cases for scrollbar colors was to choose between light/dark scrollbars. If that's one of the most common sue cases, then it seems to me that this should be a choice we can provide to the authors, where they don't have to choose specific colors, but just say whether they want light scrollbars or dark ones, and the UA can fill in something platform-appropriate.

These would be additional keywords for the `-color` properties: I'm not suggesting that we remove `<color>`.

**Comment by jonjohnjohnson** [comment]
Definitely in favor of this, when safari already uses heuristics (things like the html, but not body elements background color?) to set their scrollbar as dark or light. A few times, I've inadvertently let those heuristics set the scrollbar in a way where my internal dom styling doesn't jive well.
