### ISSUE TITLE
[css-text-4] hyphenate-character doesn't just put hyphen at end of line 

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#2975]
8.1. Hyphens: the hyphenate-character property
https://drafts.csswg.org/css-text-4/#hyphenate-character

> If a string is specified, it appears at the end of the line before a hyphenation break.

I can't find an example at the moment, but i'm pretty sure i have come across languages that put the hyphen at the beginning of the second line, rather than before the hyphenation break.  This appears to be supported by the Unicode Standard, which says: 

> A common default rendering is to insert a hyphen before the line break, but this is insufficient or even incorrect in many situations.

**Comment by litherum** [comment]
I hope we don’t need a new property or new syntax for this. Can the UA use the lang attribute and just do the right thing?

**Comment by r12a** [comment]
Yes, that's what i was assuming for the normal case, ie. where you're doing what a language normally does during hyphenation. 

If you're using `hyphenate-character: "\01F449"` for fun, then i don't know whether people using that language would expect the 👉 to appear at line start.

**Comment by Crissov** [comment]
Isnʼt that quote more about not adding an additional hyphen when you are, for instance, breaking an already hyphenated word?

**Comment by Crissov** [comment]
Would `hyphenate-character: "\0A\1F449"` work, by the way?

**Comment by r12a** [comment]
@Crissov I almost wrote another issue about this, but in the sentence

> This property specifies strings that are shown between parts of hyphenated words.

'between parts of hyphenated words' is somewhat ambiguous, but i assumed it refers to strings defined using `hyphenate-character` which are inserted between words that are split using hyphenation (ie. not necessarily hyphenated in the sense of words-with-hyphens-in-them).

**Comment by r12a** [comment]
> Can the UA use the lang attribute and just do the right thing?

@litherum  it may be worth noting that presumably the UA has to do its own thing to an extent anyway, since it needs to change things in Dutch like cafeetje → café-tje, autootje → auto-tje, or skiërs → ski-ers, not ski-ërs. Maybe that would also apply to the position of the 'hyphen' at line end/start.

**Comment by kojiishi** [comment]
IIUC this was one of the motivations @litherum [proposed keywords for `hyphenate-character` in #2809](https://github.com/w3c/csswg-drafts/issues/2809#issuecomment-402877863)?

**Comment by r12a** [comment]
> I can't find an example at the moment, but i'm pretty sure i have come across languages that put the hyphen at the beginning of the second line, rather than before the hyphenation break. 

Unicode Standard, v11, p536:
> In  writing  Mongolian  and  Todo,  U+1806  mongolian  todo  soft  hyphen is used at the beginning  of  the  second  line  to  indicate  resumption  of  a  broken  word.  It  functions  like U+2010 hyphen, except that U+1806 appears at the beginning of a line rather than at the end.

**Comment by faceless2** [comment]
Given the point of hyphenate-character is to allow overriding the current language's default hyphen, I'm not sure you can just rely on the language to do the right thing.

* in english, `hyphenate-character: auto` will add U+002D to the end of the first line.
* in mongolian, `hyphenate-character: auto` will add U+1806 tp the start of the second line.
* what do I do if the language is english and I specify `hyphenate-character: "\1806"`?

But I really like @crissov's (low-key) idea of using a newline. If the hyphenate-character has a newline, split at the first newline and put the first half and the end of the first line, and the second half at the start of the second line. If not, it goes at the end of the first line. Covers every situation, and no new property required.

```
p { hyphens: auto; hyphenate-character: "…\A…" }
<p>Welcome to Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch!</p>
```

Welcome to Llanfair...
...pwllgwyngyllgoge...
...rychwyrndrobwllll...
...antysiliogogogoch!

**Comment by jfkthame** [comment]
> But I really like @Crissov's (low-key) idea of using a newline. If the hyphenate-character has a newline, split at the first newline and put the first half and the end of the first line, and the second half at the start of the second line. If not, it goes at the end of the first line. Covers every situation, and no new property required.

I'm a bit uncomfortable with this, as it's impossible for an author to know whether this extended functionality is supported or not; given that it's a fairly obscure case, and may involve some implementation complexity, it may be preferable to make it clearly distinct from the "normal" case where the `hyphenate-character` string simply appears before the break.

An alternative way to extend the property would be to allow an optional second value; if two strings are provided, then the first string (which could be empty) appears before the break, and the second string after the break. This allows for graceful degradation in the usual CSS way if the browser doesn't support the extended syntax.

**Comment by fantasai** [comment]
My preference here is to leave the position of a single-string value up to the language, and only replace the character rather than changing its insertion behavior.

If we want control over where it goes, though, things get a bit more complicated. I agree with @jfkthame that if we're having separate values for before/after the break, it would make sense to use two strings to indicate that. But then how do we handle rules such as “hyphen goes on the first line, unless the word was hyphenated already in which case it goes on both lines”?

**Comment by fantasai** [comment]
Agenda+ to propose that a single-string value only changes what character is inserted, and does not change where it is inserted.

**Comment by frivoal** [comment]
Made the fix in https://github.com/w3c/csswg-drafts/commit/2a23164c4841ee644a56d5f09b65a7473c6f551c. Let me know if there's anything wrong with it.
