### ISSUE TITLE
[css-align] "the relevant computed self-alignment property" is unnecessarily vague (it can only be "align-self")

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#2986]
https://drafts.csswg.org/css-align/#baseline-align-content has some hand-wavy language that tries to be generic over self-alignment properties:

> If its baseline alignment preference is “first” (“last”),
> the relevant computed self-alignment property is either align-self/stretch or self-start (self-end)

This "relevant computed self-alignment property" text is now unnecessarily vague/generic -- it can only be "align-self", right?  (i.e. that phrase should just be replaced with "its computed align-self", I think)

That's the only "relevant ... self-alignment property" that could be cooperating here in the align-content axis. (And this chunk of spec is *only relevant in the align-content axis*, ever since https://github.com/w3c/csswg-drafts/issues/1184 was resolved)

CC @fantasai  @tabatkins

**Comment by dholbert** [comment]
Quoting my suggest:
>  (i.e. that phrase should just be replaced with "its computed align-self", I think)

Actually, this^ isn't quite right either.  The spec **doesn't really** want to check whether the computed `align-self` is `stretch`, because that doesn't account for `align-self:auto` (which behaves as `stretch` under default conditions) and `align-self:normal` (which behaves as `stretch` for some boxes, e.g. flex items).

Perhaps we should keep the sentence hand-wavy, though (e.g. "computed align-self is...stretch"), and then add an explanatory afterthought to say that for the purposes of this check, "stretch" includes other values that are defined to behave as `stretch`, including e.g. `auto` when the parent has `align-items:stretch`...?

**Comment by tabatkins** [comment]
> This "relevant computed self-alignment property" text is now unnecessarily vague/generic -- it can only be "align-self", right? (i.e. that phrase should just be replaced with "its computed align-self", I think)

Nope, which axis is align/justify for the -self properties is determined by the *containing block's* writing mode, which has no relation to your own writing mode. So it can be either one (tho it will often by align-self, yes).

> Actually, this^ isn't quite right either. The spec doesn't quite want to check whether the computed align-self is precisely the value stretch

You're right; we've fixed this to use "behaves as".

**Comment by dholbert** [comment]
Ah, OK - I think I understand.

So for a grid item whose writing-mode is orthogonal to its parent grid, for example: if the item has `align-content: baseline; justify-self:baseline`, then `align-content` would defer to `justify-self` in determining its sizing/positioning in that axis (the parent's inline axis i.e. the item's block axis) -- correct?

(I initially filed this bug with flexbox in mind, where `justify-self` has no effect, which is why I was confused.)

**Comment by tabatkins** [comment]
Yes.
