### ISSUE TITLE
containment probably shouldn't apply to most SVG elements

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#2987]
layout, size, and paint containment probably shouldn't apply to SVG elements other than `svg` and `foreignObject`.  Currently the spec excludes elements that "do not generate a principal box"... but I don't actually see anything in the relevant definitions that says that these SVG elements don't generate a principal box.

I think it should be the case that they don't, and therefore that layout, size, and paint containment don't apply, but this ought to be defined.  (It's also not 100% clear about things like outer `svg`, `svg` within an SVG structure, and `foreignObject`.)

**Comment by tabatkins** [comment]
At the moment SVG elements don't generate any boxes at all, as they're not defined to interact with the CSS box model in any way, besides the outermost SVG in an HTML document.

**Comment by dbaron** [comment]
What about a `foreignObject` containing HTML?  I'd think that has a box, and `contain: paint` could apply to it.

**Comment by tabatkins** [comment]
The `<foreignObject>` still doesn't, it just provides an ICB to the contained `<html>` element, which *does* generate a box.

**Comment by AmeliaBR** [comment]
> The `<foreignObject>` still doesn't, it just provides an ICB to the contained `<html>` element, which does generate a box.

You can't have an `<html>` or `<body>` inside a `<foreignObject>` in inline SVG parsed by the HTML parser.

Ideally, the foreignObject would provide a fixed-height containing block (most browsers do _not_ currently treat it as if it had a fixed height, so you can't set `height: 100%` on a child) for all child CSS boxes, but I'm not sure whether it is necessary to define it as a CSS box.

Basically, a `foreignObject` is a CSS box in the sense of having an inner display type (flow-root), but it does not have an outer display type.

More generally, see @tabatkins's [comment on the filter / containing block issue](https://github.com/w3c/fxtf-drafts/issues/307#issuecomment-410373975):

> The proper resolution to this boils down to "actually define how SVG operates in the CSS box model finally", correct?

**Comment by AmeliaBR** [comment]
Focusing on the original issue, [containment](https://drafts.csswg.org/css-contain/):

The `<svg>` element that defines an SVG canvas (that is, root element or a direct child of a non-SVG-namespaced element), _does_ have an outer CSS layout box, and so `contain: paint` would be useful. These always currently `contain: size` in practice, although that could change if we ever add auto-calculated `viewBox` based on the content bounding box. Pending resolution on proper behavior of positioned elements inside foreignObject, such an element.

For other SVG elements on which [`overflow` applies](https://svgwg.org/svg2-draft/render.html#OverflowAndClipProperties), much the same points could be made, and so containment could make sense there, too.

For other SVG elements, which don't have boxes other than those defined by their contents or drawing commands, containment doesn't make sense without a lot of special definitions..

**Comment by dbaron** [comment]
So it seems like the right thing to implement is that containment should apply to outer `<svg>` but nothing else in SVG.

(Note that for containment to make sense, it needs to be clear what it means for an element to establish a containing block for absolutely positioned and fixed positioned elements; see w3c/fxtf-drafts#307.)

**Comment by frivoal** [comment]
@dbaron and @AmeliaBR , you seem to be in agreement. Could one of you propose a phrasing to be added to the spec?

Agenda+ to try and get closure on this.

**Comment by AmeliaBR** [comment]
Sorry I missed the discussion.

I agree that the "outer" SVG should support the containment properties. The wording should be something like "an `<svg>` element that has an associated CSS layout box" to be consistent with other specs.

As selectors, that looks like:

``` css
@namespace svgns url(http://www.w3.org/2000/svg);

svg:root, /* root svg, starts an SVG canvas */
:not(svgns|*) > svg, /* svg that is a child of a non-svg element, also starts a canvas */
foreignObject > svg /* a new SVG canvas inside a foreignObject */
{ /* containment works */}
```

I still think it would be perfectly sensible for `<foreignObject>` and other elements that support `overflow: hidden` to also support containment, but I also think that's something that could be left undefined/unsupported for now.

**Comment by frivoal** [comment]
Actually, I'm removing the "needs testcase" label here, as there isn't really anything to test. We just defined that the property does not apply to elements where it wouldn't be clear what applying means... It doesn't really seem meaningful to try and test for the lack of effect. If anyone catches a browser accidentally doing something when it should do nothing, we can add tests to wpt to make sure that doesn't happen again, but until then I think no test is needed for this.
