### ISSUE TITLE
[css-inline-3] Need name for inline-content-box-height-calculation-mode property

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2989]
We need an actually usable name for the unnamed property we resolved to add in response to https://github.com/w3c/csswg-drafts/issues/1974

See https://drafts.csswg.org/css-inline-3/#inline-box-dimensions

**Comment by jonjohnjohnson** [comment]
Need anything more creative than `line-box-mode`/`inline-box-mode`?

**Comment by nigelmegitt** [comment]
Can I suggest `line-box-content-height` as a long but semantically close fit to what the property does? I can!
