### ISSUE TITLE
[css-align] Shouldn't 'left'/'right' keywords definitions be simplified?

### ISSUE THREAD

**Issue by SelenIT** [w3c/csswg-drafts#2991]
Currently, the CSS Box Alignment spec [has the following note](https://drafts.csswg.org/css-align/#valdef-justify-content-left) about `left` and `right` alignment values:
> If the property’s axis is not parallel with either left↔right axis, this value behaves as start.

But given that these values are restricted to `justify-*` properties, isn't the property's axis parallel with the _line left↔right axis_ in all cases except the `flex-direction: column` case in Flexbox layout? And if the `writing-mode` is vertical/sideways, than the main axis of the column-oriented flex container would be parallel with the _physical left↔right axis_. Also, the only `justify-*` property that is not ignored in Flexbox layout is `justify-content`.

So, if I haven't miss anything, the only situation where the the axis of the property that accepts the `left` and `right` values is not parallel with with either left↔right axis is the `justify-content` property in Flexbox layout where `flex-direction: column; writing-mode: horizontal-*` are in effect. If it is true, wouldn't the spec become more readable if we state this only exception explicitly? E.g.,

> For the `justify-content` property of a flex container with horizontal writing mode and `flex-direction: column`, this value behaves as `start`.

**Comment by fantasai** [comment]
Flag as needs edits to add a note. Agree 100% with @tabatkins logic.
