### ISSUE TITLE
[css-scrollbars] Maybe merge the scrollbar color properties into one

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2993]
As I mentioned in [#2879 (comment)](https://github.com/w3c/csswg-drafts/issues/2879#issuecomment-409113109), there was [a concern](https://groups.google.com/d/msg/mozilla.dev.platform/X_tv4aH4NxQ/y_iyHJwsCAAJ) raised that what should happen if only one of the two scrollbar color properties is specified.

The current spec says
> If scrollbar-track-color computes to auto, and scrollbar-face-color is not auto, it is used to color the scrollbar track.

which is obviously undesired. (This means you would have the scrollbar all in the same color, which is almost guaranteed to be very poor for accessibility on most platforms.)

Also nothing is mentioned for the reverse case.

I think it generally makes little sense to specify only one of the two, and it is a reasonable concern that it may lead to a style which works on some platforms but not others in some cases.

So I'm thinking about whether we should just merge the two properties into one, `scrollbar-color` which has syntax `auto | <color>{2}`, so that there are always two colors specified. (And we reserve the future possibility to convert it to a shorthand, or require only one color and derive the other.)

**Comment by tabatkins** [comment]
This sounds reasonable. While color-changing the scrollbar during the life of the page is definitely something with use-cases (Gmail does this on hover of a scrollable element, for example), they'll typically change together, so it's no hardship to specify them together.

**Comment by upsuper** [comment]
Regarding the naming, do you think the merged property should be `scrollbar-color` or `scrollbar-colors`? Maybe the former, given we have shorthands like `border-color`?
