### ISSUE TITLE
[css-selectors-4] Add new :snap pseudo-class

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#2999]
https://www.w3.org/TR/selectors-4/

Add a :snap pseudo-class for use with scroll-snapping.
Bikeshed the name as appropriate.  :snap would be consistant with :focus.

Use case:
One might want to style the snapped item differently than the unsnapped item(s).
E.g. adding a thick border to emphasize the currently snapped item, or de-emphasize the not-currently-snapped item(s) via a filter property.

**Comment by jonjohnjohnson** [comment]
Have a feeling that this feature, "a selector that depends on layout", falls victim to the same reasons why something like ":stuck" just isn't a viable pseudo-class...

- https://wiki.csswg.org/faq#selectors-that-depend-on-layout
- [1660 [css-position] Events for stickiness changes](https://github.com/w3c/csswg-drafts/issues/1660)
- [1656 [css-selectors] :stuck pseudo-class feature suggestion](https://github.com/w3c/csswg-drafts/issues/1656)

**Comment by tabatkins** [comment]
And in particular, you can turn something *un*snapped with a property, at this had the same property cycles, yeah. 😭
