### ISSUE TITLE
[css-align] Mixing baseline self-alignment with random content alignments

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3006]
It doesn't seem to be clear what happens with, e.g., `align-self: baseline; align-content: center;`

**Comment by tabatkins** [comment]
Wait, hmm, you have to do layout of the element before you can self-align anyway, because you need a size. So I guess there's nothing wrong with content-alignment affecting where the baseline sits when self-aligning.

**Comment by frivoal** [comment]
Is this the problem we're talking about:
https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=6101

If `align-self: baseline` is supposed to align the baseline of the item with the first baseline of the grid, we'd have a problem, but I think it is supposed to align with the first baseline of the grid row, and that makes everything OK: first, layout the items, then baseline align them with each other, and figure out the height of the grid row from that, then now that you know its size, you can do `align-content:center` with no particular issue.

Or am I missing something?

**Comment by frivoal** [comment]
aha! Makes more sense. So the issue would be this:
1. Place your content within yourself -> this affects your layout/size
2. Then, place yourself within your parent based on aligning baselines -> this affects your position, which may affect the layout/size of your parent in some cases.
3. If your size was set in a way that depends on the size of the parent, then you need to relayout yourself, and that would cause a loop.

However, it seems this can only happen if:
* the parent has a non definite size that is resolved based on layout of its content.
* the item is sized in a way that depends on the parent's size even if it is non definite.

I don't think this situation actually exists.

Or am I still missing something?

**Comment by tabatkins** [comment]
Right, I think you've got it now, and I also think this can't occur currently, but @fantasai was trying to explain a situation where this could occur on the call. I couldn't follow along her verbal explanation and asked for a written-out example here in this thread.

**Comment by tabatkins** [comment]
Closing, but flagging for a testcase to make sure this combo does indeed work as intended.
