### ISSUE TITLE
[css-box-3] Should we move the border property defs from css-backgrounds-3 to css-box-3?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3007]
Now that we've trimmed down the box module, deferring box generation to css-display and block layout to a forthcoming css-block module, should we move the border properties from css-backgrounds-3 to css-box-3?

Pros: Makes more sense?
Cons: They've been in css-backgrounds-3 for more than a decade.

Discuss!

**Comment by astearns** [comment]
What about a note in css-box-3 mentioning that you might expect the properties there, but for historical reasons they're over in backgrounds?

**Comment by SelenIT** [comment]
IMHO, borders belong where they currently are more than just for historical reasons. The only aspect of borders that effectively participates in the box model construction seems to be the _size_ of the _border area_, that is, `border-width`. Other border aspects (`border-color` and `border-style`, let alone `border-image`) are about _rendering_ borders, not about box geometry. I believe it makes sense to keep those aspects together with other rules of _painting different areas_ of the element (like `background-clip`/`-origin`, which also refer to box model parts). A note and a cross-reference would be a great solution for me.

**Comment by fantasai** [comment]
OK. There was a cross-reference from the intro, but I added a dedicated section for it. @astearns @SelenIT Let me know if this looks good to you! https://drafts.csswg.org/css-box-3/#borders

**Comment by astearns** [comment]
Looks fine to me. I’d probably use “describe” or “indicate” rather than “delineate,” but I‘ll leave that up to you.

**Comment by SelenIT** [comment]
Looks great! Only the comma between "...the edges of the box" and "The border properties..." looks like a minor typo (shouldn't it be a full stop)?
