### ISSUE TITLE
[css-syntax] between codepoint A and B is confusing

### ISSUE THREAD

**Issue by Netmosfera** [w3c/csswg-drafts#3008]
I hope this kind of super pedantic bug reports are welcome - if they are not please tell me and this will be the last one. This is fine because it's easy:

> **digit**
> A code point between U+0030 DIGIT ZERO (0) and U+0039 DIGIT NINE (9).

However this is not:

> **non-printable code point**
> A code point between U+0000 NULL and U+0008 BACKSPACE, or U+000B LINE TABULATION, or a code point between U+000E SHIFT OUT and U+001F INFORMATION SEPARATOR ONE, or U+007F DELETE.

I asked around to native english speakers and one answered **_When my son is learning to drive and I say stay between the lines I don't expect him to drive on them._** :-D

So for a starter I would change that to:

> A code point **from** U+0030 DIGIT ZERO (0) **to** U+0039 DIGIT NINE (9).

But for more explicitness, I would also add notation for intervals, or, better:
 
> A code point from U+0030 DIGIT ZERO (0) (inclusive) to U+0039 DIGIT NINE (9) (inclusive).

Thank you in advance.

**Comment by tabatkins** [comment]
You're right, "between" is ambiguous. I'll be clear that they're both inclusive ranges.
