### ISSUE TITLE
sticky issue with select element

### ISSUE THREAD

**Issue by prosperva** [w3c/csswg-drafts#3009]
I have a select in the middle of a page and that select is set to be sticky when the user scrolls. But when I click on it, the page scrolls back up. See this fiddle:

http://jsfiddle.net/0nxvjt46/24/

**Comment by tabatkins** [comment]
Confirmed that this happens in Chrome. Looks like this is a side effect of it getting focused, and the code that brings focused elements into view isn't aware of sticky positioning.

I filed a Chrome bug for this: <https://bugs.chromium.org/p/chromium/issues/detail?id=873233>

**Comment by tabatkins** [comment]
(This does *not* happen in Firefox. I can't test Safari or Edge at the moment.)
