### ISSUE TITLE
[css-scroll-snap] initial position of (e.g. overflowed) content

### ISSUE THREAD

**Issue by doriantaylor** [w3c/csswg-drafts#3014]
Currently looking at the [Scroll Snap CR](https://www.w3.org/TR/css-scroll-snap-1/), trying to parse out if there is a provision for declaratively setting the initial scroll position of a content box, for instance with an `overflow: auto` or an iframe.

A use case would be e.g. a Slack-like messaging app where the page loads with the main content already scrolled to the bottom of the box.

Am I in the right department?

**Comment by majido** [comment]
This is the right department.

My understanding of the specification is that when `mandatory` snap type is used it should cause the initial scroll position to be snapped. Here is the particular section that I am basing this opinion on:

[mandatory strictness](https://www.w3.org/TR/css-scroll-snap-1/#valdef-scroll-snap-type-mandatory) definition declares "If specified on a scroll container, the scroll container is required to be snapped to a snap position when there are no active scrolling operations."

I consider initial load to fall into this category but @fantasai and @tabatkins will correct me!

However AFAIK no implementation follows this currently. We have a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=866127) to track this on Chromium side.

**Comment by tabatkins** [comment]
Yes, initial load counts. The scroll position is *always* governed by snapping rules, unless you are currently in the middle of a scrolling operation.

That said, putting a mandatory snap point at the bottom is probably bad, as it means you can't scroll upwards!  (Putting a *proximity* one there is a good idea tho, as it helps you when scroll close to it, and "sticks" you to the bottom as new content gets added.)

The correct way to handle this is with `align-content`, as specified in [Align 3](https://drafts.csswg.org/css-align/#overflow-scroll-position); `overflow-y: scroll; align-content: end;` should start the element out scrolled to the bottom. This isn't *generally* implemented yet, but it happens to work already in Chrome in the specific case of of a `flex-flow: column-reverse` flexbox. ^_^

**Comment by tabatkins** [comment]
(Closing as "invalid" just because the requested functionality already exists per spec, it just needs to be implemented.)

**Comment by doriantaylor** [comment]
I see; looks like a known bug ([FF](https://bugzilla.mozilla.org/show_bug.cgi?id=1042151)) ([Cr](https://bugs.chromium.org/p/chromium/issues/detail?id=411624)) that's been on the books for a while.
