### ISSUE TITLE
[css-overflow-4] Can we add ::nth-page() pseudo-element?

### ISSUE THREAD

**Issue by rakutenjeff** [w3c/csswg-drafts#3017]
In https://drafts.csswg.org/css-overflow-4/#paginated-overflow I think we need style regarding different page (such as ::nth-fragment at https://drafts.csswg.org/css-overflow-4/#fragment-pseudo-element).

The use case is in some digital book (epub) which is rendered with pagination publisher wanted to use different background image at left and right page (or say odd or even page).  I remember saw something like nth-column somewhere but that would limit pagination have to be implemented with multi-columns.

**Comment by astearns** [comment]
That's covered in paged media

https://drafts.csswg.org/css-page-3/#spread-pseudos

**Comment by rakutenjeff** [comment]
Hmm, it's digital book not printed book. And this is for the case that publisher or reading system need to use css-overflow-4 paginated-overflow to implement pagination on screen (say mobile, or desktop). So, IMP it's not exactly paged media.

**Comment by astearns** [comment]
Fair enough. My first thought would be that reading systems should probably implement paged media concepts that are relevant (rather than inventing new things for not-printed instances).

**Comment by rakutenjeff** [comment]
Yes I can understand. It was my first thought too. Currently for reading system there are some difficulty to use page media implement pagination. 1st thing is page media is not implemented enough yet in UA that reading system (which is based on UA) can use. And this is why reading systems were keeping trying to find css alternative way to implement pagination. 2nd thing is paged media seems more friendly to printing html (correct me if I am wrong) and might not actually can be adapted to digital book well, for example I remember some UA disabled javascript for @page (Maybe that's outdated, correct me if I am wrong here as well) but digital book is more like web page but paginated (with animation, javascript etc.).

But yes, welcome any suggestion about how to resolve pagination for digital reading.

**Comment by frivoal** [comment]
I think the paginated overflow defined in css-overflow-4 is not sufficiently well defined yet to be sure exactly how all the constructs of paged media apply to it, and what needs to be added. It is possible that a new selector may be in order, but I think we're not there yet.

In the meanwhile, the features of css paged media are meant to be used in print as well as for digital books. The fact that they are not as implemented as we'd like is unfortunate, but we cannot fix the fact that features that are defined are not implemented by defining more features, which initially won't be implemented either.

**Comment by rakutenjeff** [comment]
Yes I can understand why don't want to invent new feature if seems unnecessary. But now seems we have a dead loop here. Reading System (RS) needs pagination, but since paged media is not useful yet RS have to try alternative CSS => Then RS needs alternative CSS to be improved to fit better for pagination => CSS said no you are supposed to use paged media.

**Comment by rakutenjeff** [comment]
Ok, lemme close this for now. The thing is if there is anything we can do to resolve this dead loop I would very like to try however I can not see any way yet. Would like to have any suggestion.

**Comment by frivoal** [comment]
> Ok, lemme close this for now.

Thanks.

> seems we have a dead loop here

We have a problem, but not really a loop. Yes, we won't have a solution until Reading systems implement the feature, but we cannot fix that by defining a different feature to solve the same problem.

What needs to happen is for the feature to be implemented, and you need to convince implementers of that (or to be an implementer). Adding things to a spec does not solve that.

Alternatively, someone could try to make a convincing case that the feature as defined now should not be implemented, should be dropped from the spec, and should be replaced by something else. But we should not be adding multiple solutions to the same problem in the hope that one will be implemented.
