### ISSUE TITLE
[css-color] Converting Between Uncalibrated CMYK and RGB-Based Colors

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#302]
https://drafts.csswg.org/css-color/#cmyk-rgb

> This section now needs to clearly distinguish between calibrated (icc-based) color on the one hand, and uncalibrated device-cmyk on the other. This particularly affects conversion to and from RGB.

Resolution depends on #301

**Comment by cabanier** [comment]
The PDF reference manual [1] sections 6.2.3 and 6.2.4 define a different conversion based on BlackGeneration and UnderColorRemoval.
Since those seem a bit easier(ie no divisions), maybe we can adopt them

1: [www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf](url)

**Comment by svgeesus** [comment]
The spec section cited says that BG and UCR are *not* used:
(sorry for the inaccessible screenshot, the PDF spec disallows copying text!)
![cmyk-to-rgb-pdf](https://user-images.githubusercontent.com/2506926/53294408-ab77a580-37ee-11e9-8d60-c372d1fe570b.png)
However, agree; these simple conversions are commonly cited, they are not specific to PDF; and the spec now uses them.
