### ISSUE TITLE
[css-color] CNS

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#303]
https://drafts.csswg.org/css-color/#modifying-colors

> Actually add the CNS thing.

**Comment by svgeesus** [comment]
On reflection, the issue (CNS named colors) is unrelated to the section it is in (color calculations) and thus the issue can be closed.

**Comment by xfq** [comment]
The [inline issue](https://drafts.csswg.org/css-color/#issue-61f9b559) also needs removing (or moving to another section), I think?

**Comment by tabatkins** [comment]
No, the function was originally called `color()` and was meant to be the host for CNS; it was then co-opted to also do color modifications.  Now that it's named `color-mod()`, yeah, CNS doesn't belong there.  If/when we add CNS, we'll do it in some new function.

**Comment by tabatkins** [comment]
(But yeah, the inline issue needs removal, and the grammar needs to be changed to define `color-mod()` rather than `color()`.)
