### ISSUE TITLE
[css-logical] Explicitly define each logical property group

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3033]
The spec says

> Each set of related flow-relative longhand properties and their parallel physical properties form a logical property group. For example, the padding-* properties form a single logical property group, the margin-* properties form a separate logical property group, etc.

The term "set of related properties" is ambiguous and the example is not clear enough. For example, I'm not sure if all `border-*` belong to the same logical property group, or if there are three different groups for `border-*-width`, `border-*-style` and `border-*-color`. I guess the latter suffices for #2924

To make it clear, in each relevant section I would explicitly list the logical property group, e.g.  in https://drafts.csswg.org/css-logical/#margin-properties I would say

> The properties margin-block-start, margin-block-end, margin-inline-start, margin-inline-end, margin-top, margin-bottom, margin-left, and margin-right form a logical property group.

**Comment by FremyCompany** [comment]
I assumed there would be three groups indeed. Serialization to super-shorthands like border remain an interesting problem, but probably doesn't require the concept of group as much.

**Comment by Loirooriol** [comment]
In https://github.com/w3c/csswg-drafts/issues/3030#issuecomment-414021593 @dbaron also said

> `border` is also special because its longhands include three logical property groups, for `border-color`, `border-style`, and `border-width`.

**Comment by fantasai** [comment]
Made some clarifications. Note that only longhands can form a logical property group, shorthands don't. Lmk if this is clear enough.

**Comment by Loirooriol** [comment]
I think it would be clearer to explicitly define all logical property group, but I guess this avoids the confusion with borders.

https://github.com/w3c/csswg-drafts/blob/e7dc18e2a5a260e164790cc2cb611ce37db3c395/css-logical-1/Overview.bs#L299

Nit: the border radius properties form a logical property group but they affect box corners, not box sides nor box dimensions.

**Comment by fantasai** [comment]
> I think it would be clearer to explicitly define all logical property group

I think we should defer that aspect of this issue to #2822

Pushed a more complete rewrite of this section, btw. Hopefully it's better now.
  https://drafts.csswg.org/css-logical-1/#box

Please close out this issue if you are satisfied, or complain at me if you are not. :)

**Comment by Loirooriol** [comment]
`Logical Property Group: <identifier>` from #2822 will satisfy me.

But note the nit remains, border radius properties affect box corners, not box sides nor box dimensions.

> setting equivalent styles on the various sides or dimensions of a box
