### ISSUE TITLE
[css-logical] Border radii are not shorthands

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3035]
https://drafts.csswg.org/css-logical/#border-radius-shorthands defines "Flow-relative Border-radius Shorthands".

Not sure if I'm missing something, but I think these are longhands instead of shorthands.

**Comment by Loirooriol** [comment]
https://github.com/w3c/csswg-drafts/commit/99b9ea16eadc2d095094ecc9411535a6a20acd57 fixed the text in the section title, but the ID is still wrong

https://github.com/w3c/csswg-drafts/blob/7f6b96445a4a5b60c80c816af4719e58cc2acb09/css-logical-1/Overview.bs#L648

**Comment by ewilligers** [comment]
I have rebased https://github.com/w3c/csswg-drafts/pull/3036 to only fix the id.
