### ISSUE TITLE
[css-box-3] Missing table-cell in “Applies to:” line for padding

### ISSUE THREAD

**Issue by triple-underscore** [w3c/csswg-drafts#3039]
CSS Box Model Module
( https://www.w3.org/TR/css-box-3/#padding-physical / 
https://drafts.csswg.org/css-box-3/#padding-physical )
The “Applies to:” line in the `padding-*` property definition table states
“all elements except internal table elements”,
which seems to over-exlude the table-cell ( and differs from CSS2's box model)

**Comment by SelenIT** [comment]
Table-caption elements also should not be excluded, IMO.

**Comment by triple-underscore** [comment]
Yeah, although the term “internal table elements” already does not include table-caption
(assuming it refers to the term defined in the CSS Display module:
https://drafts.csswg.org/css-display-3/#internal-table-element
)

**Comment by fantasai** [comment]
Fixed, thanks for the report @triple-underscore !
