### ISSUE TITLE
[css-grid] What track sizes match the concept of "intrinsically-sized track" ?

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#3042]
The inline-axis and block-axis alignment sections have the following statement:

https://drafts.csswg.org/css-grid/#row-align
> If baseline alignment is specified on a grid item whose size in that axis depends on the size of an intrinsically-sized track (whose size is therefore dependent on both the item’s size and baseline alignment, creating a cyclic dependency), that item does not participate in baseline alignment, and instead uses its fallback alignment.

I'm not sure whether some possible values of the [track sizing functions](https://drafts.csswg.org/css-grid/#algo-terms) may or not produce an **intrinsically-sized track**. So, I'll collect some cases here that I think they match and other I'd have doubts;  

1. auto -> minmax(auto, auto): **yes**
2. min-content -> minmax(min-content, max-content): **yes** 
3. fit-content -> minmax(auto, fit-content): **yes**
4. max-content -> minmax(max-content, max-content): **yes**
5. 1fr -> minmax(auto, 1fr): **??**
6. minmax(auto, 20px): **yes**
7. minmax(20x, auto): **yes**
8. minmax(min-content, 20px): **yes**
9. minmax(20px, min-content): **yes**
10. minmax(20px, 1fr): **??**

Basically, in the Chrome and Webkit implementation we are considering that any **content-sized** track (I'll fill a new issue about this term too) will produce intrinsically-sized tracks. Additionally, we consider a track as content-sized if either its min-sizing function or its max-sizing function is a content-sized value (auto, min-content or max-content).

Finally, my doubts regarding the flex tracks are related to their dependency with the available size, which will come from the grid container's inline and block size. We assume in both, Chrome and WebKit that a **flex track in a indefinite sized container should be considered as content-sized**. I couldn't find in the spec where this is specified; maybe we should if it's not the case. I'll file a new issue about this if it's worth discussing it.

I've got more questions, which may be related with this one. However, I'll fill separate issues for now; we can merge then if we think all of them are part of the same issue.

**Comment by fantasai** [comment]
Wrt examples, 5=yes, 10=no.

**Comment by javifernandez** [comment]
What about case 10 in a grid with indefinite size ?  Shouldn't we consider this track as intrinsically sized according to the following statement ?

https://drafts.csswg.org/css-grid/#fr-unit
> When the available space is infinite (which happens when the grid container’s width or height is indefinite), flex-sized grid tracks are sized to their contents while retaining their respective proportions.

**Comment by tabatkins** [comment]
Reviewing the spec, it looks like we didn't consider the interaction of baseline alignment and fr values in indefinitely-sized containers.  I think Chrome/WebKit's current behavior, of treating such tracks as intrinsically-sized and thus triggering fallback alignment for extrinsically-sized baseline-aligned items, is reasonable.

We should clarify the spec on this point, and also how baseline alignment is applied in fr tracks with indefinite free space.

**Comment by javifernandez** [comment]
I've added a few tests to cover this issue, and specially issue #3046. See bellow and maybe add feedback about their correctness or whether we would need more. Otherwise, I guess can can remove the Need Testcase label.

I'm still implementing the new behavior, as resolved in  issue #3046, which will change a few cases of these tests, though.

- [grid-self-baseline-not-applied-if-sizing-cyclic-dependency-001.htm](https://github.com/web-platform-tests/wpt/blob/master/css/css-grid/alignment/grid-self-baseline-not-applied-if-sizing-cyclic-dependency-001.html)
- [grid-self-baseline-not-applied-if-sizing-cyclic-dependency-002.htm](https://github.com/web-platform-tests/wpt/blob/master/css/css-grid/alignment/grid-self-baseline-not-applied-if-sizing-cyclic-dependency-002.html)
- [grid-self-baseline-not-applied-if-sizing-cyclic-dependency-003.htm](https://github.com/web-platform-tests/wpt/blob/master/css/css-grid/alignment/grid-self-baseline-not-applied-if-sizing-cyclic-dependency-003.html)
