### ISSUE TITLE
[css-transitions] why doesn't transitionend event fire in some cases?

### ISSUE THREAD

**Issue by mkay581** [w3c/csswg-drafts#3043]
In [the spec for transitionend event](https://drafts.csswg.org/css-transitions/#transitionend), it mentions that the `transitionend` event does not fire 

> in the case where a transition is removed before completion, such as if the `transition-property` is removed

I take it that it also does not fire in cases where the element is removed from the DOM, like if set to `display:none`, etc. Was this decision intentional? why does it not fire in these cases?

I have started a [wait-for-element-transition library](https://github.com/mkay581/wait-for-element-transition) because current `transitionend` is not always reliable when you want to just write one set of code for both animated and non-animated set of elements or in the case where whether a set of elements can be animated is unknown. My lib allows a consumer to wait for an element to transition by returning a promise that resolves. The promise will resolve immediately if element is removed from DOM (or if `display:none` is applied) after the transition has started.

I would rather not have to use a library for this so just wondering if there is a possibility to update the spec to support this use case.

Thanks for your time!

**Comment by Loirooriol** [comment]
Have you tried the `transitioncancel` event?

**Comment by mkay581** [comment]
I've seen it but I didn't think the "canceled" event was relevant. The spec doesn't go into anymore detailed other than firing when its "cancelled". But not sure what that means. Does removing the `transition-property` from an element or changing to `display:none` call `transitioncancel`?

**Comment by Loirooriol** [comment]
The spec says https://drafts.csswg.org/css-transitions/#ref-for-transition-cancel

> If an element is no longer in the document, implementations must cancel any running transitions on it

https://drafts.csswg.org/css-transitions/#ref-for-transition-cancel%E2%91%A0

> If the element has a running transition or completed transition for the property, and there is not a matching transition-property value, then implementations must cancel the running transition

**Comment by mkay581** [comment]
Ok thanks for that information. I missed the text in that first link you posted. So looks like `transitioncancel` could work when element css is changed  (i.e. to `display:none` or if transition properties are removed from element's css) after a transition has begun or will eventually begin. Great!

But how would I wait for a group of elements to transition and some of them dont have transition properties on them at all? In my library, I resolve the "waiting promise" immediately. So I guess I would still need my library to simplify interoperability of (animatable vs non-animatable elements) in these cases?

**Comment by birtles** [comment]
You'd listen for `transitionrun` events. If you got a `transitionrun` event you will either get a `transitionend` or `transitioncancel`.

(Once we ship `getAnimations()` you'll also just be able to wait on `Promise.all(elem.getAnimations().map(animation => animation.finished))` since the `finished` promise rejects if the animation is canceled.)

**Comment by mkay581** [comment]
I see. So `elem.getAnimations()` may be what I'm looking for to detect when an element has no animations. I am reading the spec on the `getAnimations()` but can't find anywhere that describes what should happen when an `elem` has no animations to get. Would I be able to do something like `getAnimations().length === 0`? which would mean no animations are present? and I can resolve promise immediately in my library?

**Comment by mkay581** [comment]
Awesome. This is great information @birtles. I will optimize waitForTransition and use that until `getAnimations()` is finalized. I will close this ticket now since my questions have been answered. Thanks!

**Comment by loia5tqd001** [comment]
> Ok thanks for that information. I missed the text in that first link you posted. So looks like `transitioncancel` could work when element css is changed (i.e. to `display:none` or if transition properties are removed from element's css) after a transition has begun or will eventually begin. Great!
> 
> But how would I wait for a group of elements to transition and some of them dont have transition properties on them at all? In my library, I resolve the "waiting promise" immediately. So I guess I would still need my library to simplify interoperability of animatable vs non-animatable elements in these cases?

This issue discussion has just saved my day
