### ISSUE TITLE
[css-grid] Definition of content-sized track

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#3044]
The grid spec uses the concept of a content-sized track, but it doesn't define it explicitly. There is a link that points to the CSS Flexible Box spec, which provides the following definition for the content-size term:

https://www.w3.org/TR/css-flexbox-1/#content-size
> The content size is the min-content size in the main axis, clamped, if it has an aspect ratio, by any definite min and max cross size properties converted through the aspect ratio, and then further clamped by the max main size property if that is definite. 

The link is in the "Significant adjustments and fixes section", so I guess the link inclusion is not intentional and definitively not part of the spec. Hence, I think we should define it properly, either in the grid spec or perhaps in a more general sizing spec (css-sizing ?)

These are a few examples of the use of this term in the grid spec:

https://drafts.csswg.org/css-grid/#grid-auto-flow-property
> Example 24 -  /* Define three columns, all content-sized,

https://drafts.csswg.org/css-grid/#algo-spanning-items
> 3- Increase sizes to accommodate spanning items crossing content-sized tracks: Next, ...

For the record, in the Chrome and WebKit implementation we are interpreting a content-sized track as any of the following values: 

- auto
- min-content
- max-content

However, I think the **fr** value is a special case on this regard, or at least, we are assuming that in our implementation. We are assuming that a flex track in a indefinite size container should be considered as a content-sized track; is this assumption valid ? Is there any statement in the grid spec, or any other, specifying that ? If it's not specified, should we include something in the grid spec, at least ?

**Comment by tabatkins** [comment]
There's no need to define this term; it's not used in any normative portion of the spec. (It only shows up in the intro, in an example, and previously in the *heading* to an algorithm section; we've just swapped that to "intrinsically-sized" as it's more correct anyway.)

**Comment by javifernandez** [comment]
ok
