### ISSUE TITLE
HTTPS connection to drafts.csswg.org fails in Firefox

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3048]
When I try to load https://drafts.csswg.org I get

> ### Secure Connection Failed
> An error occurred during a connection to drafts.csswg.org. A required TLS feature is missing. Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING 

It works if I disable security.ssl.enable_ocsp_must_staple

**Comment by tabatkins** [comment]
cc @plinss

**Comment by plinss** [comment]
Hmm, looks like we're not getting OCSP responses for the ECDSA certificate, looking in to it

**Comment by plinss** [comment]
I turned off the OCSP_MUST_STAPLE option in the certificate until this gets resolved, should be working now
