### ISSUE TITLE
[css-color] blending options

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#305]
https://drafts.csswg.org/css-color/#blend-adjuster

> This blends the two colors in a way that pays attention to alpha, similar to how compositing does. Is there a better formula? The current one was determined empirically to give good results, but isn’t motivated by any theory.

**Comment by upsuper** [comment]
The alpha channel of the result color being the average of the two colors looks pretty weird. Should that be the linear interpolation given the percentage? The current algorithm means `color(color_a blenda(color_b 100%))` may not be `color_a` and `color(color_a blenda(color_b 0%))` may not be `color_b`.

**Comment by svgeesus** [comment]
See also #445

**Comment by svgeesus** [comment]
This section was ong ago removed, so the issue is moot.
