### ISSUE TITLE
[css-syntax] Redundant step in consume url token algo

### ISSUE THREAD

**Issue by Netmosfera** [w3c/csswg-drafts#3054]
I'm not entirely sure, but I think... in section [4.3.6](https://drafts.csswg.org/css-syntax-3/#consume-url-token) the step 3:

> 3. If the next input code point is EOF, this is a parse error. Return the \<url-token\>.

Is redundant with the step in the loop (4):

> **EOF**
> This is a parse error. Return the \<url-token\>.

I suggest step (3) to be removed as it's already covered by the loop.

**Comment by tabatkins** [comment]
Yes, it's redundant. (It's possible it wasn't previously; I know I've tweaked this section before.)
