### ISSUE TITLE
[css-ui-3] calls itself Working Draft

### ISSUE THREAD

**Issue by dansoper** [w3c/csswg-drafts#3062]
https://www.w3.org/TR/2018/REC-css-ui-3-20180621/#intro contains the words “This Working Draft incorporates...” but it is not a Working Draft. Perhaps this should be added to the list of errata?

**Comment by frivoal** [comment]
Good point. Fixed for the editor's draft (https://github.com/w3c/csswg-drafts/commit/0d7f01e28dc0da4ee787b80ab46d657ae06c2900). @svgeesus is this something you can fix in place in the REC?

**Comment by svgeesus** [comment]
[Erratum added](https://www.w3.org/Style/2018/REC-css-ui-3-20180621-errata.html)
