### ISSUE TITLE
[css-align] gap properties for block layout

### ISSUE THREAD

**Issue by benface** [w3c/csswg-drafts#3068]
From the [CSS Box Alignment Module Level 3](https://drafts.csswg.org/css-align/#gaps) Editor’s Draft:

> The gap property, and its row-gap and column-gap sub-properties, provide this functionality for multi-column, flex, and grid layout.

Shouldn't `gap` and `row-gap` be functional in block layout too?

e.g.
```
<ul style="row-gap: 2em;">
    <li>
        No space above this item
    </li>
    <li>
        Space between this item and the ones above and below it
    </li>
    <li>
        No space below this item
    </li>
</ul>
```

Of course you can get the same effect with margins, but the `gap` properties are considerably more elegant/cleaner.

**Comment by tabatkins** [comment]
Margin collapsing and floats and similar complexities of block layout make this much more complicated than for flex/grid/multicol, so we're not planning on trying to make it work. :/

**Comment by benface** [comment]
Yeah, I don't have a solution for that. I was hoping this could allow us to overrule margin collapsing completely. I didn't think about floats though. Oh well, I guess it's always possible to make that `<ul>` a column flex container.

**Comment by jonjohnjohnson** [comment]
@fantasai https://github.com/w3c/csswg-drafts/issues/2848 ???

**Comment by fantasai** [comment]
Added draft of `margin-trim` to http://drafts.csswg.org/css-box-3/#margin-trim

@benface Would you mind having a look and letting me know if this addresses your use cases? Also if you have any thoughts on the open issues. :)

**Comment by benface** [comment]
@fantasai Yes, that would allow some kind of gap functionality in block layout. :) Thank you!

**Comment by ByteEater-pl** [comment]
@fantasai
> `margin-trim: none |  in-flow | all`

How about adding {1,2} to enable different settings for before and after?
