### ISSUE TITLE
[css-break] what happens to block margins that aren't between block-level boxes?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#3073]
There's a [section](https://drafts.csswg.org/css-break/#break-margins) of the spec that defines what happens to block margins that are between block level boxes:

>  When an unforced break occurs between block-level boxes, any margins adjoining the break truncate to the remaining fragmentainer extent before the break, and are truncated to zero after the break. When a forced break occurs there, adjoining margins before the break are truncated, but margins after the break are preserved. Cloned margins are always truncated to zero on block-level margins. 

But what about margins that aren't between block level boxes, such as a `margin-block-start` of the first child of a block formatting context (BFC), or a `margin-block-end` of the last child of a BFC?

Also see [bug 1487927](https://bugzilla.mozilla.org/show_bug.cgi?id=1487927) about how this relates to column-balancing inside of a multicol... in interesting ways.

**Comment by fantasai** [comment]
Note that you're only allowed to break there if there's a gap: https://www.w3.org/TR/css-break-3/#possible-breaks

**Comment by fantasai** [comment]
I think the multicol balancing case wasn't really thought through on this point... Probably the margin should be truncated to zero both before and after an unforced break. I'm uncertain what should happen with a forced break though... Probably the margin should count as content on the earlier fragmentainer for the purpose of balancing, but should be allowed to truncate if the fragmentainer height is too short to include the margin.

**Comment by fantasai** [comment]
Proposal: treat these margins exactly like margins between siblings, i.e. margins before/after an unforced break are truncated to zero, margins after a forced break are preserved, and margins before a forced break are truncated.

@dbaron Does that make sense to you?

**Comment by fantasai** [comment]
(@dauwhe says this makes sense to him, fwiw.)

**Comment by dbaron** [comment]
It's not entirely clear to me what will happen in all the balancing cases; it might produce some surprising results.  I guess truncation is at least well-defined in that moving content from one column to another will not cause the column losing content to grow or cause the column gaining content to shrink... at least as long as there aren't negative margins.

(I think the author of [this testcase](https://bug1487927.bmoattachments.org/attachment.cgi?id=9005766) wasn't expecting any truncation, though, and was expecting margins to continue across multiple columns.  I guess my original concern wasn't really a fundamental problem, but rather the violation of expectations.)

**Comment by rachelandrew** [comment]
I think web authors probably won't _expect_ truncation, however I think @fantasai's proposal will give the most pleasing results ultimately, and if the behaviour is well defined and can be explained (and is consistent cross-browser) then I think it works.

**Comment by fantasai** [comment]
@dbaron Wrt the author of the testcase not expecting truncation... truncation is what currently happens if you break between siblings, so I think it would be more surprising if it didn't happen after the last child?

**Comment by mstensho** [comment]
cc me

**Comment by mstensho** [comment]
cc me

**Comment by fantasai** [comment]
Edits committed. @mstensho / @dbaron can I get a review? :) I'll submit for republication once you sign off on the edits.

**Comment by mstensho** [comment]
@fantasai Looking good!
