### ISSUE TITLE
[css-logical-1] Readability/Understandability: In Section 4.1, reorder some text to block then inline

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#3077]
In section:
Logical Height and Logical Width: the 'block-size' and 'inline-size' properties
https://drafts.csswg.org/css-logical-1/#dimension-properties

change from:

  <pre class="propdef">
  Name: block-size, inline-size
  Value: <<'width'>>
  Initial: auto
  Applies to: Same as 'width' and 'height'
  Inherited: No
  Percentages: As for the corresponding physical property
  Computed value: Same as 'width', 'height'
  Animatable: Same as 'width', 'height'
  </pre>

 These properties correspond to the
  'width' and 'height' properties.
  The mapping depends on the element's 'writing-mode'.

<pre class="propdef">
  Name: min-block-size, min-inline-size
  Value: <<'min-width'>>
  Initial: 0
  Applies to: same as 'width' and 'height'
  Inherited: No
  Percentages: As for the corresponding physical property
  Computed value: Same as 'min-width', 'min-height'
  Animatable: Same as 'min-width', 'min-height'
  </pre>

  These properties correspond to the
  'min-width' and 'min-height' properties.
  The mapping depends on the element's 'writing-mode'.

<pre class="propdef">
  Name: max-block-size, max-inline-size
  Value: <<'max-width'>>
  Initial: none
  Applies to: same as 'width' and 'height'
  Inherited: no
  Percentages: As for the corresponding physical property
  Computed value: Same as 'max-width', 'max-height'
  Animatable: Same as 'max-width', 'max-height'
  </pre>

  These properties correspond to the
  'max-width' and 'max-height' properties.
  The mapping depends on the element's 'writing-mode'.

to: 

  <pre class="propdef">
  Name: block-size, inline-size
  Value: <<'width'>>
  Initial: auto
  Applies to: Same as 'height' and 'width'
  Inherited: No
  Percentages: As for the corresponding physical property
  Computed value: Same as 'height', 'width'
  Animatable: Same as 'height', 'width'
  </pre>

These properties correspond to the
  'height' and 'width' properties.
  The mapping depends on the element's 'writing-mode'.

<pre class="propdef">
  Name: min-block-size, min-inline-size
  Value: <<'min-width'>>
  Initial: 0
  Applies to: same as 'height' and 'width'
  Inherited: No
  Percentages: As for the corresponding physical property
  Computed value: Same as 'min-height', 'min-width'
  Animatable: Same as 'min-height', 'min-width'
  </pre>

  These properties correspond to the
  'min-height' and 'min-width' properties.
  The mapping depends on the element's 'writing-mode'.

<pre class="propdef">
  Name: max-block-size, max-inline-size
  Value: <<'max-width'>>
  Initial: none
  Applies to: same as 'height' and 'width'
  Inherited: no
  Percentages: As for the corresponding physical property
  Computed value: Same as 'max-height', 'max-width'
  Animatable: Same as 'max-height', 'max-width'
  </pre>

  These properties correspond to the
  'max-height' and 'max-width' properties.
  The mapping depends on the element's 'writing-mode'.

**Comment by fantasai** [comment]
OK, fixed in the editor's draft at https://drafts.csswg.org/css-logical-1/#dimension-properties Let me know if anything seems off!
