### ISSUE TITLE
[css-content] spec doesn't describe how content:<image> handling works

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#308]
While [3eef526b41b7](https://hg.csswg.org/drafts/rev/3eef526b41b7) and [da3321fc5996](https://hg.csswg.org/drafts/rev/da3321fc5996) (see also #216) updated css-content-3 to say that the 'content' property accepts &lt;image> values, no other parts of the spec appear to have been updated.

In particular, [2.2. URI](https://drafts.csswg.org/css-content/#content-uri) is still totally in terms of &lt;url>.

The spec needs to describe how &lt;image> values work, in terms of the definitions provided in [css-images](https://drafts.csswg.org/css-images/), at the level of detail needed to implement interoperably.

This is apparently already implemented in some engines (e.g., Blink, IE, Edge), and there's a [Mozilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1285811) on implementing in Gecko.

**Comment by dbaron** [comment]
An example question that this spec should answer is:  while we know that the <code>width</code> property doesn't apply to the image in <code>content: "hello" url(foo.png) "world"</code>, does it apply to the image in some cases (e.g., if the image is alone (might be a compat risk if it's after a comma), or only if the image is before a comma)?

Also, I realize that perhaps section 2.2 is about the &lt;content-list> part of the definition, and maybe that should remain about &lt;url>.  However, the handling of &lt;image> values still needs to be defined.

**Comment by tabatkins** [comment]
Should be done. I explicitly separated out the "single image" case from the "content list" case, and defined each of the cases in greater detail.
