### ISSUE TITLE
[Pseudo-classes]Do we need :visible, :hidden ?

### ISSUE THREAD

**Issue by lu-yuan** [w3c/csswg-drafts#3081]
* please tag the issue title with the spec's shortname, like `[css-foo]`
* please link to the spec section you're talking about, or at least the spec

**Comment by frivoal** [comment]
This is unfortunately impossible to add, as it would introduce circular dependencies.

As this is a common request, we have an entry in the FAQ about this problem: https://wiki.csswg.org/faq#selectors-that-depend-on-layout
