### ISSUE TITLE
[css-transforms-2] Interpolation of perspective.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3084]
I think it's really weird that `perspective` the transform function gets interpolated differently than `perspective` the property.

https://drafts.csswg.org/css-transforms-2/#propdef-perspective says:

>  Animatable: as length

However for the transform function it says:

> The transform functions matrix(), matrix3d() and perspective() get converted into 4x4 matrices first and interpolated as defined in section Interpolation of Matrices afterwards.

I just fixed the `perspective()` function interpolation in Gecko in https://bugzilla.mozilla.org/show_bug.cgi?id=1488414. I haven't tested what other browsers do for the `perspective` property yet, but I wanted to leave this filed because it seems that if this inconsistency is intended, it should be at least be clarified and explicitly pointed out.

**Comment by emilio** [comment]
cc @hiikezoe

**Comment by emilio** [comment]
cc @dirkschulze

**Comment by hiikezoe** [comment]
https://codepen.io/anon/pen/eLEPWm
Here is an example for 'transform: perspective' and perspective interpolations.

As for the perspective property, Chrome, Edge, Firefox and Safari do interpolate as length (i.e. linear interpolation)

As for the perspective function in transform property, Chrome and Safari do the way what the spec defines (thought I haven't verified the calculation result), Firefox does linear interpolation (but emilio fixed it in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1488414)).  Edge shows somewhat different result.

**Comment by smfr** [comment]
Animating test: https://codepen.io/smfr/pen/bGbXPgQ

**Comment by dbaron** [comment]
The group resolved almost a year and a half ago to close this issue with no change unless @emilio objected.  It seems to me it's been long enough for him to object, so we should probably close this now.

**Comment by emilio** [comment]
Yeah, no objection at all, but I wasn't asked directly and I probably either missed or overlooked that sentence in the minutes, so I didn't know closing this was blocked on me... :)

Thanks for closing this @dbaron :)

**Comment by smfr** [comment]
See also https://github.com/web-platform-tests/wpt/pull/28036
