### ISSUE TITLE
[selectors-4] Could we add :mouse-focus or :keyboard-focus?

### ISSUE THREAD

**Issue by AlphaGo88** [w3c/csswg-drafts#3092]
Hello!

[the focus pseudo](https://drafts.csswg.org/selectors-4/#the-focus-pseudo)

Sometimes we want to distinguish between a keyboard focus and a mouse focus. For example, when the element is focused by a mouse click, we want to hide the outline. It would be great if this can be done by css rather than javascript.
Something like `:mouse-focus` or `:keyboard-focus` would help.

**Comment by bkardell** [comment]
There is `:focus-visible` https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible which might give you what you really want, but a specific use case would help if not

**Comment by AlphaGo88** [comment]
Thanks a lot!
