### ISSUE TITLE
[css-position] computed value of inset properties should not be auto in static positioning if another value was specified

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3099]
According to https://drafts.csswg.org/cssom/#resolved-value-special-case-property-like-top

> If the property applies to a positioned element [...]. Otherwise the resolved value is the computed value. 

An element with `position: static` is not positioned, so the resolved value is the computed value.

According to https://drafts.csswg.org/css-position-3/#box-offsets-trbl,

> Computed value: For position: static, `auto`.

So I would expect this:

```js
element.style.top = "10px";
getComputedStyle(element).top; // "auto"
```

However, all Firefox, Chromium and WebKit return `"10px"` instead.

Either CSSOM or CSS Position is wrong.

**Comment by emilio** [comment]
The computed value of `top` in that case is `10px`, I think this is not a bug. The value is not used, but I think this is invalid and both specs are right.

**Comment by emilio** [comment]
(Please reopen if I got that wrong)

**Comment by Loirooriol** [comment]
> The computed value of `top` in that case is `10px`

This seems good to me but the spec says it computes to `auto`.

I can't reopen.

**Comment by emilio** [comment]
Oh, right. I think this is a bug in css-position then.

**Comment by fantasai** [comment]
CSS2 says 10px, and it wins against css-position in any arguments: https://www.w3.org/TR/CSS2/visuren.html#position-props
