### ISSUE TITLE
[css3-lists] Link from list-style-property to inline-list-item is broken

### ISSUE THREAD

**Issue by RByers** [w3c/csswg-drafts#311]
The [definition of list-style-property](https://drafts.csswg.org/css-lists-3/#list-style-position-property) mentions "display: inline-list-item".  But the link points to https://drafts.csswg.org/css2/visuren.html#propdef-display which doesn't define `inline-list-item` at all.

Should it point instead to https://drafts.csswg.org/css-lists-3/#declaring-a-list-item which adds the `inline-list-item`?   Or better yet can that text now be removed and instead we point to https://drafts.csswg.org/css-display/#typedef-display-legacy?

**Comment by xfq** [comment]
The link points to https://drafts.csswg.org/css-display-3/#propdef-display now.

**Comment by xfq** [comment]
For the record, `inline-list-item` was removed from css-display in https://github.com/w3c/csswg-drafts/commit/94b7b00c51be31196521f73543ed5b4bd63486d2

The link to it in css-lists was removed in https://github.com/w3c/csswg-drafts/commit/e1720ff0569d4eac1fe695e810b0a92f29e67b90
