### ISSUE TITLE
[css-text-3] Always hang trailing spaces to ensure interop under non-start alignment

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3116]
Currently the spec says that UAs can either hang spaces at the end of the line or visually collapse spaces that overflow. This is fine for left-aligned text, it doesn't really affect layout, but for right-aligned or centered text, it affects alignment: UAs doing the former ignore the spaces for text alignment, but the latter include them (or some of them) when performing text alignment.

Proposal is to require hanging the spaces (this is a technical term in CSS Text meaning they aren't measured for fit or alignment in the line box), and to *additionally* allow the UA to visually-collapse any spaces that overflow. Behavior should be identical in left-aligned text, but will yield consistent behavior in centered and right-aligned text.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/e625f72b7dee716bef3be9ddf23dc173aba93118

**Comment by frivoal** [comment]
https://github.com/web-platform-tests/wpt/issues/13019

**Comment by frivoal** [comment]
Test PR in: https://github.com/web-platform-tests/wpt/pull/13333
