### ISSUE TITLE
[css-text-decor-4] Rethinking text-underline-offset

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3118]
There are a couple problems with the current formulation of `text-underline-offset`.

- `text-underline-offset` is meant to be a delta added to wherever the underline happened to be placed, but the location where the underline is placed varies between different browsers and operating systems. The use case this is supposed to solve is "my underline is just a little too high, let's nudge it down a little bit" but because different browsers choose the locations differently, the current formulation doesn't satisfy this use case
- What does it mean if both `text-underline-offset: from-font` and `text-underline-position: under` are applied to the same element? Such a formulation seems fairly meaningless.

In order to fix these problems, I propose the following changes:
1. Add another value to `text-underline-position` named something like `standard`. Come up with some standard formula for the placement of the underline that all browsers can agree on, and state it in the spec. Importantly, don't make this the initial value - it's just an option that authors can specify if they want consistent underlines. I'm not particular on what specific formula is used, but I'll propose `font-size / 16` to get the conversation started. (This formula scales linearly with font size, and default-sized text gets a 1px underline gap, which is compatible with most (all?) browsers today)
2. Move the `from-font` value from `text-underline-offset` to `text-underline-position`.
3. Update the grammar of `text-underline-position` such that you can't specify more than one of [auto, standard, under, from-font].
4. Now, `text-underline-offset` really can be just a delta, so there's no need for an `auto` value. Remove the `auto` value and have it just take a `<length>`.
5. While we're at it, `text-underline-offset` should be able to take a percentage, which gets multiplied by the font size. This would be a good way to make the underline scale as the font size grows.

**Comment by litherum** [comment]
cc @fantasai

**Comment by fantasai** [comment]
Hi! I think you're a bit confused. :)

> text-underline-offset is meant to be a delta added to wherever the underline happened to be placed, but the location where the underline is placed varies between different browsers and operating systems.

`text-underline-offset` is defined to set “the offset of underlines from their initial position” where the “initial position” is defined in the table below. It is not up to the UA, that is what the `auto` value means. Zero sets the underline at exactly that position.

> What does it mean if both text-underline-offset: from-font and text-underline-position: under are applied to the same element? Such a formulation seems fairly meaningless.

Good question. `from-font` should probably resolve to zero in this case.

<hr>

> Add another value to text-underline-position named something like standard.

I'm not convinced this is necessary if we address your other issues... but open to hearing your arguments. :)

> Move the from-font value from text-underline-offset to text-underline-position.

`text-underline-position` is more fundamental positioning--it can swap which side of the text the underline is on, etc.; `from-font` is really about just adjusting the offset, so I think it really does belong here.

> While we're at it, text-underline-offset should be able to take a percentage, which gets multiplied by the font size.

This is a severe oversight and we should definitely fix it. We should maybe try to be consistent about this across this property, `letter-spacing` and `word-spacing` (https://github.com/w3c/csswg-drafts/issues/2165), and ideally, `line-height`... Maybe in a separate issue, though?

**Comment by fantasai** [comment]
Another option for `from-font` + `under` would be to calculate the distance from the alphabetic baseline to the font's preferred position, and then use that as the offset from the zero-offset `under` position.

**Comment by litherum** [comment]
> `text-underline-offset` is defined to set “the offset of underlines from their initial position” where the “initial position” is defined in the [table below the propdef](https://drafts.csswg.org/css-text-decor-4/#underline-offset). It is not up to the UA, that is what the `auto` value means. Zero sets the underline at exactly that position.

Ah, I see. You're right, I didn't realize that this length refers to an offset *from the baseline* instead of an offset *from the browser's `auto` placement*. So `0` would be a terrible value that no one should ever use.

In that case, I guess my complaint is really about the name. Perhaps `text-underline-position` would be better, but that's already taken 😕

> 
> > What does it mean if both text-underline-offset: from-font and text-underline-position: under are applied to the same element? Such a formulation seems fairly meaningless.
> 
> Good question. `from-font` should maybe resolve to zero in this case. Or maybe calculate the distance from the alphabetic baseline to the font's preferred position, and then use that distance as the offset from the zero-offset `under` position.

Applying the font's distance to under-underlines is never what you want. Picking 0 would be better than that.

On the other hand, if you move the value to `text-underline-position`, you can mechanically forbid this from happening, which seems better.

> 
> > Add another value to text-underline-position named something like standard.
> 
> I'm not convinced this is necessary if we address your other issues... but open to hearing your arguments. :)

As above, I was just confused about this part. I retract this part of the proposal.

> 
> > Move the from-font value from text-underline-offset to text-underline-position.
> 
> `text-underline-position` is more fundamental positioning--it can swap which side of the text the underline is on, etc.; `from-font` is really about just adjusting the offset, so I think it really does belong here.

I don't quite understand the difference between "fundamental positioning" vs "non-fundamental positioning". They both are about positioning.

Perhaps an even better solution would be to join the two properties into one, so you could say something like

- `text-underline-position: under 2px` to mean "2px beyond the under-underline".
- `text-underline-position: from-font 12.5%` to mean "bump up the displacement from the font file by font-size / 8"
- `text-underline-position: baseline 6.25%` is the formula I mentioned above about "standard" placement
- `text-underline-position: left baseline 6.25%` is the same thing, but specifies that underlines go on the left in vertical writing mode
- `text-underline-position: under from-font` is a syntax error

> 
> > While we're at it, text-underline-offset should be able to take a percentage, which gets multiplied by the font size.
> 
> This is a severe oversight and we should definitely fix it. We should maybe try to be consistent about this across this property, `letter-spacing` and `word-spacing` (#2165), and ideally, `line-height`... Maybe in a separate issue, though?

https://github.com/w3c/csswg-drafts/issues/3121

**Comment by fantasai** [comment]
> I don't quite understand the difference between "fundamental positioning" vs "non-fundamental positioning". They both are about positioning.

Yeah, but one is setting the origin and the other is setting the offset. It's a bit like the relationship of `background-origin` and `background-position`...

I guess the important question is really, do these two things need to cascade together or are there typical cases where you'd set one value independently of the other?

**Comment by drott** [comment]
> I guess the important question is really, do these two things need to cascade together or are there typical cases where you'd set one value independently of the other?

I don't have a strong preference on whether they should be one property or two. But I'd prefer to ultimately spec something that makes it hard to apply invalid combinations, such as as the "under" plus "from-font" combination.

**Comment by anjia** [comment]
Hi, I prefer `from-font` is the value of `text-underline-offset`, then we can use it as followings.

```css
text-underline-position: left;
text-underline-offset: from-font;
``` 
and

```css
text-underline-position: right;
text-underline-offset: from-font;
``` 

Because if `from-font` is the value of `text-underline-position`, it seems impossible to meet the same effects. I'm not sure whether the following codes or something else can do that, according to the proposal made by @litherum above. So, @litherum, could you please explain further for me? Thank you :)
```css
text-underline-position: right from-font;
text-underline-position: left from-font;
```
> Perhaps an even better solution would be to join the two properties into one, so you could say something like ...

**Comment by anjia** [comment]
> I guess the important question is really, do these two things need to cascade together or are there typical cases where you'd set one value independently of the other?

I think the two separate properties are better, since other shorthand CSS properties are like this, such as `text-decoration` `border` `background` `flex` etc.

**Comment by litherum** [comment]
The resolution:
1. The grammar for text-underline-position becomes `auto | [ [ under | from-font] || [ left | right ] ]`
2. The grammar for text-underline-offset becomes `auto | <length>`

And the behavior:
1. `auto` / `auto` = what we do now
2. `auto` / `<length>` = put it at `<length>` away from the baseline (aka `<length>` clobbers `auto`)
3. `under` / `auto` = put it at the bottom of the descender
4. `under` / `<length>` = put it at the bottom of the descender plus the length (aka `<length>` adds to `under`)
5. `from-font` / `auto` = put it where the font says to put it
6. `font-font` / `<length>` = put it where the font says to put it plus the length (aka `<length>` adds to `font-font`)

**Comment by litherum** [comment]
Also, because I didn't have a GitHub issue for it, Resolved: `text-decoration-width` is now `text-decoration-thickness` is under this issue too

**Comment by fantasai** [comment]
@litherum Have a look and lmk if the edits are OK? https://drafts.csswg.org/css-text-decor-4/#text-underline-position-property

**Comment by litherum** [comment]
“Zero position.” I like it.
