### ISSUE TITLE
Test the number of lines of a plaintext edit control

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#3120]
Could we add a media feature (or selector, or other means) for testing if a multipleline plaintext edit control (i.e., `textarea`) has one line or multiple lines, or more generally, testing the number of lines of the edit control? One potential issue is circular dependency, tho, since it seems to depend on layout.

(H/t to @miccycn who contributed this use case.)

**Comment by xfq** [comment]
Perhaps not only for plaintext edit control, but also for other elements that can contain multipleline plaintext.

**Comment by xfq** [comment]
> I think this falls under https://wiki.csswg.org/faq#selectors-that-depend-on-layout

Seems so. I'll wait a bit more to see if anyone has any comment, and otherwise close this issue.

**Comment by upsuper** [comment]
I agree with @fantasai this seems to be exactly the case of selectors depending on layout. Closing.

**Comment by jonjohnjohnson** [comment]
It's reasonable that this was closed, but the OP also mentioned a media feature. And the chromium side of things is (hopefully) paving the way for some eventual "element query" feature built on top of `contain`, making something like "if this element is completely contained and is taller than `2.5ex`, please enable these styles" seem not all that outta hand to me?

**Comment by Crissov** [comment]
If you want to count lines that result from the text being flowed with “soft” line breaks according to its box constraints, this involves circular dependencies with other styles. However, if you want to count the number of explicit “hard” line breaks, this only depends on the contents. Iʼm not sure whether this would be very useful, though.
