### ISSUE TITLE
[css-text-decor-4] text-underline-offset and text-underline-width has no easy way of being proportional to font size

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3121]
https://drafts.csswg.org/css-text-decor-4/#underline-offset

Perhaps it should also take a percentage, which gets multiplied by the font size?

**Comment by litherum** [comment]
```html
<div id="outer" style="font-size: 32px; text-underline-offset: 12.5%">
    <div id="inner" style="font-size: 16px; text-decoration: underline> ... </div>
</div>
```

The observed offset on the inner element should be 2px

```html
<div id="outer" style="font-size: 32px; text-underline-offset: 12.5%; text-decoration: underline">
    <div id="inner" style="font-size: 16px;> ... </div>
</div>
```

The observed offset on the inner element should be 4px because of the [decorating box](https://drafts.csswg.org/css-text-decor-3/#decorating-box).

**Comment by litherum** [comment]
Also, text-underline-width should get it too.

**Comment by benface** [comment]
Would it make sense to introduce a new unit that is relative to the font size like `em` but that doesn't compute to an absolute value? Also for #2165.

**Comment by litherum** [comment]
Ah, I see. Cool.

**Comment by litherum** [comment]
The resolution for https://github.com/w3c/csswg-drafts/issues/2165 should cover this.
