### ISSUE TITLE
[css-text-4][css-flex][css-grid] 'auto' value needed for text-space-trim to cover white space discarding between flex and grid items?

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#3124]
If the child text between [flex](https://drafts.csswg.org/css-flexbox/#flex-items) and [grid items](https://drafts.csswg.org/css-grid/#grid-items)  only consists of white space, it is not rendered.

This is as if [`text-space-trim`](https://drafts.csswg.org/css-text-4/#white-space-trim) was set to `discard-before discard-after` for those items. Though the default value of `text-space-trim` is `none`, which contradicts the whitespace discarding logic in flex and grid layout.

Therefore I think an `auto` value needs to be introduced for `text-space-trim` and be made the initial value.

The computed value may then still be `auto`, or be either `none` or `discard-before discard-after` depending on the layout type.

Sebastian

**Comment by SebastianZ** [comment]
I don't want this white space to appear but to explain why there is no white space. And this explanation can happen via `text-space-trim`.

Sebastian

**Comment by fantasai** [comment]
If there's no use case, then there's no need to add the feature. Adding feature is work not just for the spec editors, but also for implementers and testers. And it also increases the knowledge overhead for authors and educators. We do not add features just because it sounds nice, we add them because they're useful.

If all you need is an explanation, then it's this: text runs consisting of white space are always discarded except when occurring as inline-level content. We don't need a property to exist to “explain” why this happens.

**Comment by SebastianZ** [comment]
> We do not add features just because it sounds nice, we add them because they're useful.

I didn't say to add it because it "sounds nice" but to make `text-space-trim` conform to the following statement in CSS Flexbox and CSS Grids:

> However, if the entire sequence of child text runs contains only white space (i.e. characters that can be affected by the white-space property) it is instead not rendered (just as if its text nodes were display:none).

While the [definition of `text-space-trim`](https://drafts.csswg.org/css-text-4/#white-space-trim) says it applies to all elements, according to the above sentence it does *not* seem to apply to flex and grid items, right?

> text runs consisting of white space are always discarded except when occurring as inline-level content.

Can you point me to the spec. where this is defined, please? (The citation above only specifies the discarding of white space for flex and grid items, but I coun't find this general definition yet.)

Sebastian

**Comment by fantasai** [comment]
> While the definition of text-space-trim says it applies to all elements, according to the above sentence it does not seem to apply to flex and grid items, right?

Updating the Applies to line to be more precise makes a lot more sense than adding a new feature that has no use case, though?

> Can you point me to the spec. where this is defined, please? (The citation above only specifies the discarding of white space for flex and grid items, but I coun't find this general definition yet.)

There's no general statement anywhere afaik, since white space discarding is defined per layout mode, but it is true.

**Comment by SebastianZ** [comment]
> > While the definition of text-space-trim says it applies to all elements, according to the above sentence it does not seem to apply to flex and grid items, right?
> 
> Updating the Applies to line to be more precise makes a lot more sense than adding a new feature that has no use case, though?

Yep.

> > Can you point me to the spec. where this is defined, please? (The citation above only specifies the discarding of white space for flex and grid items, but I coun't find this general definition yet.)
> 
> There's no general statement anywhere afaik, since white space discarding is defined per layout mode, but it is true.

Especially, I couldn't find the one that says that this applies to block-level elements. I guess it would be easier to maintain and reference if the statement was centralized somewhere instead of duplicating it for every layout mode.

Sebastian
