### ISSUE TITLE
[css-grid] Allow grid-positioning of indirect children

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#313]
Copied from https://www.w3.org/blog/CSS/2015/08/10/css-grid-pls-review/comment-page-1/#comment-13462

The fact that Grid Layout restrict positioning to immediate child nodes of the container appears to me as overly restrictive.

Here is a use case of indirect child nodes participating in grid positioning (similar to outlook 2015):

Consider a layout where the navigation area (“NAV”) sits to the left of the content area (“CONTENT”). The application presents a system of say four subsystems. Each subsystem has one or more forms which should fill the whole content area while being activated.
The Navigation bar has a noop button each on the top (“TOP”) and the bottom (“BOT”), each outside of the “NAV” grid area. Beetween them, there is a button for each of the subsystem (inside the “NAV” grid area).

When clicked, the subsystem buttons below slide towards the bottom, and for each form of the subsystem, a individual button is displayed inside the free area. If one of the forms for the subsystem had been displayed before, it will show up in the content area, otherwise, a default frontmatter is displaed. Clicking one of the subsystem buttons whill result in the correponding subform being displayed in the content area. Clicking on a different subsystem button results in an analoguous behavior, making the other subsystem’s form buttons and forms disappear.

Structurally, the data would by organized by subsystem such that each subsystem contains one or more groupings each associated with a form for that subsystem. Each grouping goes into the content area but also provides for a clue for a form button below the subsystem button.

It would by rather straightforward to build this application with a framework like AngularJS.

```ystem
  -subsystem 1
     common data 1
     group 1_1
     group-specific data 1_1
     group 1_2
     group-specific data 1_2
     group 1_3
     group-specific data 1_3
  -subsystem 2
     common data 2
     group 2_1
     group-specific data 2_1
  -subsystem 3
     common data 3
     group 3_1
     group-specific data 3_1
     group 3_2
     group-specific data 3_2
     group 3_3
     group-specific data 3_3
    -subsystem 4
     common data 4
     group 4_1
     group 4_1
     group-specific data 4_1
     group 4_2


+----------------+---------------------------------------------+
|  "TOP" bnNOOP  |  "CONTENT" Currently Form 3_2 with data     |
+----------------+   from common data 3 and group 3_2          |
|  "NAV"         |                                             |
|  (System as    |                                             |
|  flexbox       |                                             |
| containg the   |                                             |
| buttons below  |                                             |
| without bnNOOP)|                                             |
+----------------+                                             |
|  bnSubsystem 1 |                                             |
+----------------+                                             |
|  bnSubsystem 2 |                                             |
+----------------+                                             |
|  bnSubsystem 3 |                                             |
+----------------+                                             |
|  +----------+  |                                             |
|  | Form 3_1 |  |                                             |
|  +----------+  |                                             |
|  +----------+  |                                             |
|  | Form 3_2*|  |                                             |
|  +----------+  |                                             |
|  +----------+  |                                             |
|  | Form 3_3 |  |                                             |
|  +----------+  |                                             |
|                |                                             |
|                |                                             |
+----------------+                                             |
|  bnSubsystem 4 |                                             |
+----------------+                                             |
|  "BOT" bnNOOP  |                                             |
+----------------+---------------------------------------------+
```

The sequence of subsystems and its immediate children does not reveal enough of the data structure to fill the grid as desired.

Please consider to allow for placement of indirect children of grid containers. Of course, if there is a descendant grid container, then all of its descendants with a declared grid-area should go either into the outer grid or the inner grid whichever contains the closest matching grid-area name declaration.

**Comment by tabatkins** [comment]
This use-case is complex and so I haven't fully grokked it, but what part of this isn't already addressed by either subgrids or `display:contents`?

**Comment by fantasai** [comment]
I think, if you have a nested form structure, it gets very difficult to make it really work. E.g.
```
  <section>
    <label>button</label>
    <form> ... </form>
  </section>
```

We could use `display: contents` to strip the <section> and auto-place all the buttons into the first column, but there's no way to place the form into a grid slot _that spans all those rows_. And if you have sub-forms, then I'm not sure what you'd do. Regions could solve this easily, because it can rearrange the content. If you're willing to potentially have a scrollbar for the form area, you could also do it with abspos, because abspos can jump the containing block ancestry into the main grid--but you can't do it in-flow otherwise, not without the descendant grid-positioning that was in Bert's original proposal.

**Comment by fantasai** [comment]
So, basically, I think we need to defer this to Grid Level 2, and introduce something like `position: grid` for in-flow jumping.
