### ISSUE TITLE
[filter-effects] color-interpolation-filters initial value

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3131]
[SVG 1.1](https://www.w3.org/TR/SVG11/painting.html#ColorInterpolationFiltersProperty) and Chrome/Edge/Firefox/Safari have `linearrgb` as the initial value for `color-interpolation-filters`.

However, the initial value is currently specified as `auto` in
https://drafts.fxtf.org/filter-effects/#ColorInterpolationFiltersProperty

The change occurred during

> commit 14055772983bd639684ac221640e4ac2c30a59cb
> Author: Dirk Schulze <krit@webkit.org>
> Date:   Fri Nov 8 16:57:03 2013 +0100
> 
>     [filter-effects] Clarify that filter primitives operate in a different coordinate space then the CSS grid.

Was the initial value changed accidentally?

**Comment by AmeliaBR** [comment]
Confirming that SVG 1.1 used `linearRGB` as the default:
https://www.w3.org/TR/SVG11/painting.html#ColorInterpolationFiltersProperty

**Comment by svgeesus** [comment]
This looks like an inadvertent change and IMO should be reverted.

**Comment by svgeesus** [comment]
On the other hand, filters-1 has the line "'color-interpolation-filters' has no affect for Filter Functions. Filter Functions must operate in the sRGB color space." from this commit 9 months ago, https://github.com/w3c/fxtf-drafts/commit/687458d890df26b01a9032462c8547cd9798a558 with the commit message "editorial change".  It is a substantive change.

**Comment by svgeesus** [comment]
SVG chose linear RGB for filter effects for a sound reason, based on color theory (it is an additive colorspace, meaning that arithmetic operations on values in linear RGB give the correct result). For anyone unaware, there is a good [YouTube video](https://www.youtube.com/watch?v=LKnqECcg6Gw) which explains this in a visual and easy to understand manner.

**Comment by AmeliaBR** [comment]
The `color-interpolation-filters` setting has no effect on the shorthand filter functions, so it's initial value also has no effect.

An initial `auto` setting *could* be used to let browsers make the SVG filter elements use sRGB if it means they can use the same optimized / GPU code paths as the shorthand functions.  But I'm not sure if any browsers do that for `auto` (which has always existed as a valid value, just not the default).

If browsers *do* use sRGB sometimes or all the time for `auto`, then changing the initial value would change lots of existing content that assumes linear calculations.

**Comment by tabatkins** [comment]
> On the other hand, filters-1 has the line "'color-interpolation-filters' has no affect for Filter Functions. Filter Functions must operate in the sRGB color space." from this commit 9 months ago, w3c/fxtf-drafts@687458d with the commit message "editorial change". It is a substantive change.

The commit you link to *is* an editorial change - it's just fixing punctuation. It has no connection to that line substantively. The actual addition of that text was from the previous day: <https://github.com/w3c/fxtf-drafts/commit/420aeacd020b971fa23676a0e28ce6ae6eeb890d>

**Comment by svgeesus** [comment]
Good catch, git blame only blames the latest person to touch a given line. And the commit you linked to was re-wording 

> Filter functions must operate in the sRGB color space.

Needs more digging to see when that was added, and why.

**Comment by svgeesus** [comment]
Okay, that text has been there (and thus, the spec has been self-contradictory) for a while. The [25 November 2014 WD](https://www.w3.org/TR/filter-effects/) also says that, while later [contradicting it](https://www.w3.org/TR/filter-effects/#FilterPrimitivesOverviewIntro):

> The color space in which a particular filter primitive performs its operations is determined by the value of the property color-interpolation-filters on the given filter primitive. A different property, color-interpolation determines the color space for other color operations. Because these two properties have different initial values (color-interpolation-filters has an initial value of linearRGB whereas color-interpolation has an initial value of sRGB), in some cases to achieve certain results (e.g., when coordinating gradient interpolation with a filtering operation) it will be necessary to explicitly set color-interpolation to linearRGB or color-interpolation-filters to sRGB on particular elements. Note that the examples below do not explicitly set either color-interpolation or color-interpolation-filters, so the initial values for these properties apply to the examples.

What I suspect happened is that `sRGB colorspace` was used loosely to mean the set of primary chromaticities and whitepoint of sRGB, without considering the transfer function. That makes sort-of sense, as the three values are "use sRGB", "use sRGB but in linear light space" or "pick either of those depending on speed and accuracy". In turn, this clearly distinguishes these filters from, say, the Adobe Photoshop-compatible blend modes (which are in the NTSC colorspace, or at least use the equations for that space to calculate `luma`).

So, what I think we need:
- revert the change that made auto be the initial value. That is not Web compatible.
- clarify the color space description.

I'm happy to propose better text for the clarification.

**Comment by tabatkins** [comment]
> Good catch, git blame only blames the latest person to touch a given line.

In the GH UI, there's a little button between the commit message and the line that looks like several stacked pieces of paper. You can press it to automatically see the blame for the previous commit on the file, which makes it *much* easier to track a change backwards thru irrelevant commits.

> And the commit you linked to was re-wording

Ah whoops, yup, didn't catch that the line existed in the previous too, because it was further down in the diff.

**Comment by dirkschulze** [comment]
PR landed as well as test.
