### ISSUE TITLE
[css-values] Define <'property-name'> notation to exclude listification

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3146]
The CSS property definition syntax has the handy `<'property-name'>` notation, which imports the entire value space of that property (aside from the CSS-wide keywords).

It's super useful, except a large number of places where we *would* use it (and did in CSS2) are places where we've listified the property value. This results in a lot of custom non-terminal grammar productions which are simply the entire value space of the property except without the listification, e.g. in css-backgrounds and css-animations.

I suggest we define `<'property-name'>` to just drop top-level listification. This would allow us to clean up our grammar productions, getting rid of these routine non-terminals and inlining a large number of simple productions into the property definition tables where they are easier to see and index.

**Comment by tabatkins** [comment]
I like this suggestion.

This would exclude things like `<'background'>`, which has a special last value and so isn't a simple listified value, right?
