### ISSUE TITLE
[web-animations][css-grid][css-flexbox][css-multicol] Animating layout-parameter integers

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3147]
There's a couple places where we have integers which, if altered, have pretty major impact on layout. Should these animate as integers or discretely (as if they were incompatible keywords)?

- `order` property
- `grid-area` and its longhands
- `column-span`
- `initial-letters` drop value [maybe this one is not so bad]

**Comment by fantasai** [comment]
Also, `column-span`...

**Comment by tabatkins** [comment]
As integers, all of them. If you want a discrete animation, `steps()` exists for a reason.

**Comment by fantasai** [comment]
@tabatkins I think some of these can, depending on the implementation, impact the box tree structure. I'm not convinced that kind of teardown is something we want to require supporting in an animation, so it's possible some of these might need to be "not animatable" actually. In which case we should probably look at 'float' and 'position' as well....

**Comment by fantasai** [comment]
https://logs.csswg.org/irc.w3.org/css/2018-10-04/#e1086698
