### ISSUE TITLE
[css-scoping-1] ::placeholder selector inside ::slotted() not working

### ISSUE THREAD

**Issue by jorenbroekema** [w3c/csswg-drafts#3150]
Referencing this issue https://github.com/w3c/csswg-drafts/issues/1747

Working as intended:
`
::slotted(::hover){
  color: red;
}
`

Not working:
`
::slotted(::placeholder){
  color: red;
}
`

From the issue I am referencing, it seems like it is supposed to not work in both scenarios, as option 3 was chosen to be allowed and option 2 was not. So basically, ::slotted()::hover should work but ::slotted(::hover) should not. At least, this was my interpretation of that issue. 

Could someone give some clarification on what should work and what should not, and perhaps why in my case the ::placeholder selector within ::slotted does not work?

**Comment by emilio** [comment]
`:hover` is a pseudo-class, `::placeholder` a pseudo-element. `::slotted(::placeholder)` should not work, though arguably `::slotted(*)::placeholder` should, per that issue.

**Comment by emilio** [comment]
Actually I think this is a valid issue. The resolution in #1747 only referenced tree-abiding pseudos (::before / ::after).

I actually have an implementation that works for all pseudos, but I don't plant to land it without a resolution here.

**Comment by lilles** [comment]
According to css-pseudo-4, the tree-abiding pseudos are: ::before, ::after, ::marker, ::placeholder. So it currently follows from the specs that ::placeholder should be allowed after ::slotted().

There's no limitation in Blink that makes it hard to support any kind of pseudo elements after ::slotted(), but the previous CSSWG resolution was to limit this.

Reported Blink issue: https://crbug.com/902518

**Comment by emilio** [comment]
Ah, alright, true that. I'll fixup firefox as well.

**Comment by emilio** [comment]
(I agree this is invalid then, just a browser bug)

**Comment by emilio** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1505213 fwiw :)

**Comment by lilles** [comment]
Wasn't quite as simple in Blink: https://chromium-review.googlesource.com/c/chromium/src/+/1323049

**Comment by jholt1** [comment]
Adding here in case others are searching for this:

Webkit has yet to fix the bug https://bugs.webkit.org/show_bug.cgi?id=223814
