### ISSUE TITLE
[web-animations-1][css-ui] Animating user-interaction controls

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3153]
Related to #3147 and #3148 

There's a couple places where we have properties that control user interaction, such as in `nav-up` and `user-select`. Should these be considered animatable as “discrete” (flip at 50%) or as “not animatable” (ignored in keyframes, not transitioned, like `display`)?

**Comment by frivoal** [comment]
Makes sense to me. I don't see why `user-select` should be "not animatable". I don't believe flipping the value should change the ranges already selected, if any. It just affects how users can change the selection. So "discrete" seems fine. Not that I expect this to be terribly useful to animate, but "not animatable" is largely limited to the things that can't be animated, not the things for which it is useless to do so.

(`nav-up` and friends were already taken care off in 6bcd8e88b28723e725facbe07dac5f9ab7e21d1a).

I suspect it's just a mistake that was introduced when we switched to the new format for defining animatability.

@tabatkins You're the one who made the commit setting it up this way, any insight?

**Comment by heycam** [comment]
Agree with @frivoal. We already have to behave in a particular way if e.g. `user-select` is changed from script after a selection intersecting that element has been made, so I don't think it's an argument for making it not animatable.
