### ISSUE TITLE
[css-grid-1] Define computed value of grid-template-rows/columns

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3154]
The computed value of grid-template-rows/columns is somewhat handwavy. It's not exposed by getComputedStyle() since that returns the resolved value, but we should be more precise here so that it's clear e.g. `minmax(auto, auto) [] 4px` can interpolate with `auto 10px`.

**Comment by fantasai** [comment]
So I checked in changes to clarify this, currently the spec says

> the keyword `none` or a list, alternating each item as either a (potentially empty) list of identifiers or a `minmax()` or `repeat()` notation, representing each `<track-size>` as a `minmax()` notation and each `<length-percentage>` computed 

It needs some follow-up to clarify that the computation nests into `repeat()`, and that there is a name list at both the start and end of each track listing (at the top level and within each repeat).

Gonna file a separate issue on interpolation.

**Comment by tabatkins** [comment]
Agenda+ to confirm that our edits are good.

**Comment by fantasai** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/3201 on interpolation.
