### ISSUE TITLE
[css-page-3] should border-short-style be border-style?

### ISSUE THREAD

**Issue by dd8** [w3c/csswg-drafts#3156]
border-short-style: is listed as a supported CSS 2.1 property in @page rules, but border-short-style isn't a CSS 2.1 property

Should this say border-style?

https://drafts.csswg.org/css-page-3/#page-property-list

**Comment by SimonSapin** [comment]
This looks like a typo for `border-style`.

**Comment by ylafon** [comment]
Also, could this be published on TR as a WD at some point? The last version on TR is more than five years old.
Thanks

**Comment by AlbertWiersch** [comment]
Was going to say the same thing... looks like this simple type has still not been fixed.

**Comment by SebastianZ** [comment]
I went ahead and fixed this. Thank you for the report!

Sebastian
