### ISSUE TITLE
[css-display] The principal box is unique

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3157]
From 6ed5a5512c71078be96a49cfc7ba093524c91d9e, https://drafts.csswg.org/css-display/#intro says

> Typically, an element generates a single &lt;a>principal box&lt;/a>

This seems to imply that in some cases there may be more than one principal box.

This contradicts https://drafts.csswg.org/css-display/#principal-box:

> When an element generates one or more boxes, **one** of them is the principal box

And my understanding was that the uniqueness was ratified in #1604

Instead, I would say

> Typically, an element generates a single &lt;a>box&lt;/a>, the &lt;a>principal box&lt;/a>, which represents the element and contains its contents in the &lt;a>box tree&lt;/a>.

**Comment by fantasai** [comment]
Fixed.
