### ISSUE TITLE
[css-display] Parent box of run-in or non-principal box

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3158]
https://drafts.csswg.org/css-display-3/#css-parent-box says

> The ***parent box*** of an element’s principal box is (except in the case of run-in) the principal box of its nearest ancestor element that generates a box.

Run-in boxes are described as an exception, but their "parent box" is not properly defined. Should be done in https://drafts.csswg.org/css-display-3/#run-in-layout. Intuitively it will be the "block box that does not establish a new block formatting context" to which the run-in sequence "is inserted as direct children".

And also the "parent box" of a non-principal box is not defined. In all element-generated cases it seems to be the principal box of the generating element. For anonymous boxes, maybe the nearest ancestor in the box tree which is a principal box.

**Comment by fantasai** [comment]
I don't think we need to define that if Box A is made to be a direct child of box B, Box B is the parent of Box A. That's implied because we're assuming people understand the semantics of English.

Is there something else I'm missing here?

**Comment by Loirooriol** [comment]
@fantasai I'm complaining that the definition is not clear. Frankly I'm not sure whether this "parent box" concept just refers to the parent (the graph theory concept) in the box tree?

In that case I don't get why you are providing some kind of partial definition. It's confusing because it's looks like you are trying to define something different than the trivial concept, but it's not properly defined. And as you say, it's implied, so I would just remove it.

If this is a different concept, the definition should state the difference clearly, like

> The **parent box** of a box is its nearest ancestor in the box tree which is not an element-generated non-principal box.

**Comment by fantasai** [comment]
The sentence you're quoting in the OP is there because otherwise we've defined that there's an element tree (which has parent-child relationships), and each element generates a box, but it's not otherwise defined how the boxes are related into a tree.

As for “I'm complaining that the definition is not clear”, what, specifically, is not clear?

**Comment by Loirooriol** [comment]
> what, specifically, is not clear?

Well, it seems the definition is excluding element-generated non-principal boxes for some reason. And it's not clear whether this is intentional.

Like if you have a `<tbody>` which is a children of a `<table>`, the definition implies that the parent box of the table-row-group box is the table wrapper box instead of the table grid box.

> it's not otherwise defined how the boxes are related into a tree

OK, it seems what you are trying to impose is

> In the box tree, the boxes generated by an element are descendants of the principal box of any ancestor elements.

I would prefer something like that: it's not a concept definition but an instruction for the tree construction, and has no vague exception. Sure, it's still not completely detailed, but this can't be done in a single sentence.

**Comment by fantasai** [comment]
> Well, it seems the definition is excluding element-generated non-principal boxes for some reason. And it's not clear whether this is intentional.

Aha. That's definitely an error. :)

> In the box tree, the boxes generated by an element are descendants of the principal box of any ancestor elements.

Hm, that's a good one. I've rearranged some of the sentences and incorporated yours, it's now a separate paragraph before the one defining "anonymous boxes", like this:

> In constructing the box tree, boxes generated by an element are descendants of the principal box of any ancestor elements. In the general case, the direct parent box of an element’s principal box is the principal box of its nearest ancestor element that generates a box; however, there are some exceptions, such as for run-in boxes, display types that generate multiple container boxes (such as tables), and intervening anonymous boxes.

What do you think?

**Comment by Loirooriol** [comment]
That's great, thanks! Well, as a mathematician I would use "Usually" instead of "In the general case" since being an ancestor is more general than being a parent, though I guess the expressions are synonyms in normal English

**Comment by fantasai** [comment]
The "general case" is the parent box being the principal box of the nearest ancestor element that generates a box. :)

Switched to like and moved parenthetical. Current text: 

> In constructing the box tree, boxes generated by an element are descendants of the principal box of any ancestor elements. In the general case, the direct parent box of an element’s principal box is the principal box of its nearest ancestor element that generates a box; however, there are some exceptions, such as for run-in boxes, display types that generate multiple container boxes (such as tables), and intervening anonymous boxes.

**Comment by fantasai** [comment]
Agenda+ to confirm, and request republication. List of changes at https://drafts.csswg.org/css-display-3/#changes ; specific changes can be seen at [diff of Introduction](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-display-3%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-display-3%2F#intro), [abspos definition](https://drafts.csswg.org/css-display-3/#absolutely-positioned), [note about broken 'display: contents' implementations](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-display-3%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-display-3%2F#box-generation)

**Comment by fantasai** [comment]
Disposition of Comments https://drafts.csswg.org/css-display-3/issues-cr-2018
