### ISSUE TITLE
[css-conditional][quirks] Quirks mode and @supports/CSS.supports

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3162]
from https://lists.w3.org/Archives/Public/www-style/2015Nov/0338.html by @zcorpan 

> What is the interaction between

> https://drafts.csswg.org/css-conditional/#at-supports
> https://drafts.csswg.org/css-conditional/#the-css-interface

> ...and...

> https://quirks.spec.whatwg.org/#the-hashless-hex-color-quirk
> https://quirks.spec.whatwg.org/#the-unitless-length-quirk

> Testing in  
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3765 it  
appears that in Blink/WebKit/Gecko apply the quirks in @supports, but not  
in CSS.supports(). Presto doesn't apply the quirks to @supports and  
doesn't have CSS.supports(). I haven't checked IE/Edge. I suggest we  
specify what Blink/WebKit/Gecko do.

**Comment by zcorpan** [comment]
This has been specified and tested by now, so I think we can close this.

**Comment by svgeesus** [comment]
Thanks @zcorpan was the fix in css-conditional or in quirks?

**Comment by zcorpan** [comment]
Quirks.
