### ISSUE TITLE
[css-cascade] Allowing @import to be conditional on @supports queries

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3165]
from https://lists.w3.org/Archives/Public/www-style/2015Jan/0292.html by @tabatkins 

> Right now, @import can only be made conditional on Media Queries, by
putting a media query after the URL in the rule.

> However, it would also be useful to let it be conditional on the
result of an @supports query.  That way, for example, one could send
some small, compact code using modern features, and if an @supports
query returns false, instead @import larger, more complicated code
(perhaps generated by a preprocessor from your base code) to do the
styling instead.  This avoids having to send both sets of styles to
most people; only down-level browses would have to spend the
additional bandwidth.

> I propose that we allow this by adding a
"supports(<supports-condition>)" function to the end @import grammar,
like:

> ```
> @import [ <url> | <string> ] [ <media-query-list> ||
> supports(<supports-condition>) ]? ;
> ```

> In other words, you can supply a media condition and/or a supports
condition.  If we add more conditional rules, we can add more to this
clause as well.

> Thoughts?

**Comment by svgeesus** [comment]
from by @dbaron 

> Sounds good.

> Previously discussed in
https://lists.w3.org/Archives/Public/www-style/2011Jun/0329.html
and deferred to level 4 in:
https://lists.w3.org/Archives/Public/www-style/2012Oct/0275.html

> Presumably we'd want to have a requirement that UAs actually *not*
load the sheets through such a supports-query when it fails to
match?  (Also, CSSImportRule.styleSheet MUST be null, even if the
sheet is loaded through some other link.)

**Comment by fantasai** [comment]
https://www.w3.org/TR/css-cascade-4/#conditional-import
> Additionally, if a <supports-condition> blocks the application of the imported style sheet, the UA must not fetch the style sheet (unless it is loaded through some other link) and must return null for the import rule’s CSSImportRule.styleSheet value (even if it is loaded through some other link).

Afaict this is already fixed? @svgeesus can you confirm?

**Comment by svgeesus** [comment]
Yes, looks like it!
