### ISSUE TITLE
[css-conditional] CSSMediaRule media readonly or forwards to mediaText?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3166]
from https://lists.w3.org/Archives/Public/www-style/2014Jun/0279.html by Bogdan Brinza @boggydigital

> Looking at http://dev.w3.org/csswg/css-conditional/#cssmediarule vs http://dev.w3.org/csswg/cssom/#the-cssmediarule-interface  our developer noticed that CSSMediaRule definition is present in both and there is an inconsistency:

> ```
> [cssom]
> interface CSSMediaRule : CSSGroupingRule {
>   [SameObject, PutForwards=mediaText] readonly attribute MediaList media;
> }; 

> [css-conditional]
> interface CSSMediaRule : CSSConditionRule {
>     readonly attribute MediaList media;
> }
> ```

> The difference is PutForwards=mediaText and we'd like to clarify what is the expected behavior here - should media forward to mediaText or should it be really readonly? 

> Currently IE forwards media to mediaText, but I couldn't get Chrome or Firefox to do the same - 
> http://jsfiddle.net/boggydigital/D2CXn/

**Comment by upsuper** [comment]
I think we should be able to close this issue now. Both specs have agreed that it should forward to `mediaText`, and both Firefox and Chrome have this behavior.
