### ISSUE TITLE
[css-variables][css-conditional] passing lone surrogates to CSS.supports()

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3168]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0546.html by @heycam 

> The definition of the two argument version of CSS.supports() says:

>   When the supports() method is invoked with two arguments property and
   value, it must return true if property is a literal match for the
   name of a CSS property that the UA supports, and value would be
   successfully parsed as a supported value for that property. (Literal
   match means that no CSS escape processing is performed, and leading
   and trailing whitespace are not stripped, so any leading whitespace,
   trailing whitespace, or CSS escapes equivalent to the name of a
   property would cause the method to return false.)

> What is the set of custom property names that the UA supports?  Is it 
all property names that begin with "var-" and are at least 5 characters 
long?  And are these Unicode characters, or UTF-16 code units?

> I am wondering about:

>   CSS.supports("var-\ud800", "a")

> If we are thinking of property names as being sequences of UTF-16 code 
units, then there is no way of writing that property name, since 
`var-\d800` will be interpreted the same as `var-\fffd`.  And if that's 
the case, should "var-\ud800" be considered to be the name of a 
supported (custom) property?

> If we are thinking of property names as being sequences of Unicode 
characters, then we need to specify how the first argument string is 
interpreted.  If we used 
http://dev.w3.org/2006/webapi/WebIDL/#dfn-obtain-unicode then that 
string would get converted to the sequence of characters <'v', 'a', 'r', 
'-', U+FFFD>, and then we do have the name of a supported (custom) property.

> A related case is:

>    CSS.supports("var-\0", "a")

> Again, in CSS syntax `var-\0` would be treated the same as `var-\fffd`, 
but if we're doing a literal match of the property name, then there is 
no way we could ever have a custom property named with a NUL in its name.

**Comment by tabatkins** [comment]
Per Syntax, if you specify an escape for a lone surrogate, it returns U+FFFD. CSS is defined in terms of codepoints, not any particular encoding.

Per Conditional, CSS.supports(property, val) compares the property (in a case-insensitive manner) directly to our known properties, without running CSS parsing on it. So there's no way to do a CSS escape in the string, that'll just be interpreted as an ident with those characters escaped in.

You *can* write `@supports (--\0: foo) {...}` in a stylesheet; to do the same in the JS API, you can use a *JS escape*, like `CSS.supports("--\0", "foo")` - this will *happen* to produce the same thing - a property name composed of two dashes and a null.

Whether `CSS.supports("--\ud800", ...)` is testing for two dashes followed by U+D800, or two dashes followed by U+FFFD, depends on whether `CSSOMString` is defined as DOMString or USVString.

I don't *think* it's possible to actually produce a custom property whose name contains a U+D800 character, but I'm not 100% sure - if you send it in UTF-16 with an appropriate encoding set at a higher level, I think you might be able to create a lone surrogate? Unclear. Anyway, both variants are valid custom property names per the grammar.

----------

So, nothing in this email requires action.

**Comment by fantasai** [comment]
@heycam Can you confirm that Tab's response addresses your issue?
