### ISSUE TITLE
[css-sizing] width: fill needs clarifications

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#317]
Maybe I'm just dense, but I am afraid I don't quite understand `width: fill` (as defined [here](https://drafts.csswg.org/css-sizing-3/#valdef-width-fill) ).

Modulo writing modes, what does `width: fill` do that `box-sizing:border-box; width: 100%;` doesn't? Assuming there is a difference, (and the definitions don't seem completely equivalent, even if at a high level they look similar), a note and/or an example showing what it's for and how it works would be most welcome.

**Comment by mrego** [comment]
> what does width: fill do that box-sizing:border-box; width: 100%; doesn't?

I believe they're different, for example if you have a margin on the element:
```html
  <div style="width: 200px;">`
    <div style="margin-left: -50px;`>item</div>`
  </div>
```

If you use `width: 100%;` on the item, it'll have a size of 200px. However if you use `width: fill;` it'd be 250px.
The same happens if the margin is positive `margin-left: 50px;` the size would be 200px (`100%`) or 150px (`fill`).

**Comment by tabatkins** [comment]
'fill' is just an explictly named version of the ordinary block "auto" behavior, so you can invoke it even for boxes that have a different "auto" behavior like tables.

**Comment by frivoal** [comment]
@tabatkins gotcha. A note to that effect would be nice to have.

**Comment by fantasai** [comment]
Added. Please take a look, I'm happy to take suggestions for better wording. :)

~fantasai

**Comment by frivoal** [comment]
Looks good to me.
