### ISSUE TITLE
[css-variables][css-conditional] bad-string and bad-url tokens in non-custom properties that reference variables

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3170]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0525.html by @heycam 

> \<bad-string> and \<bad-url> tokens are disallowed in \<any-value>, which 
is used as the value for custom properties and also as the fallback for 
variable references.  But they are not disallowed at the top level of a 
non-custom property that has variable references (and thus invokes the 
"property value containing a variable must be assumed to be valid at 
parse time" requirement).  So:

>   @supports (color: var(a, "
>             ))                         { ... fails ... }
>   @supports (color: var(a, url("b" c)) { ... fails ... }
>   @supports (var-a: "
>             )                          { ... fails ... }
>   @supports (var-a: url("b" c))        { ... fails ... }

> But:

>   @supports (color: var(a) "
>             )                          { ... succeeds ... }
>   @supports (color: var(a) url("b" c)) { ... succeeds ... }

> Should we make these fail too?

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0529.html by @SimonSapin 

> Ah, interesting case. IMO we should change css-variables to make this 
invalid in all contexts (not just @supports.) That is:

>   Declarations with variables references do not have their value 
checked against the grammar of the property at parse time. Instead (this 
is the new part) the value must match <any-value>.

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0539.html by @tabatkins 

> Yeah, this seems reasonable to me.  We don't want to spread
computed-time-invalid further than necessary

**Comment by tabatkins** [comment]
Yup, done in both Conditional and Variables.

**Comment by svgeesus** [comment]
@heycam satisfied with the resolution?
