### ISSUE TITLE
[css-variables][css-conditional] is trailing semicolon valid in @supports conditions

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3171]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0506.html by @heycam 

> I want to confirm that syntactically valid variable declarations and 
> references in an @supports condition won't cause the condition to fail. 
>  Specifically:

> ```
>   @supports (color: var(a))             { ... succeeds ... }
>   @supports (color: 2px var(a))         { ... succeeds ... }
>   @supports (color: var(a) ! important) { ... succeeds ... }
>   @supports (var-a: abc)                { ... succeeds ... }
>   @supports (var-a: var(a))             { ... succeeds ... }
>
>   @supports (color: var(a,))            { ... fails ... }
>   @supports (color: var(a) ! something) { ... fails ... }
>   @supports (var-a: abc;)               { ... fails ... }
>   @supports (var-a:)                    { ... fails ... }
> ```

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0509.html by @tabatkins 

> Interesting question.  I believe that since it just checks for parsing
errors, but doesn't interpret anything, that all your examples are
correct.

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0511.html by @SimonSapin 

> Le 25/08/2013 08:01, Cameron McCormack a écrit :
>>     @supports (var-a: abc;)               { ... fails ... }

> This one should be the same as

>   @supports (color: green;)

What do we want these to do?

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0512.html by @tabatkins 

> Yes, it is - note the equivalent statement without the semicolon in
the "passes" section of his email.

> Per the Conditional spec's grammar, having a semicolon at the end is invalid.

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0527.html by @SimonSapin 

> Yes, this is what I’m reading from the spec as well, but I seem to 
remember F2F discussions where dbaron wanted this to be valid because 
people might just add the semi-colon by habit. Or did I make this up?

**Comment by svgeesus** [comment]
from https://lists.w3.org/Archives/Public/www-style/2013Aug/0538.html by @tabatkins 

> Oh, that might be true; I don't recall.  David, do you remember if
this was something you wanted?  If so, I can make the necessary edit
to Conditional.

**Comment by svgeesus** [comment]
@heycam you may have missed that I ported your issue to GitHub.

@dbaron @tabatkins looks like we need a brief discussion to close this one off.

**Comment by tabatkins** [comment]
The `var()` and `--foo: ...` issues are settled; they parse, so they pass.

There was that sub-thread about a trailing semicolon, which is the only unresolved part here.

**Comment by svgeesus** [comment]
Okay so about the remaining "trailing semicolon" issue. Is it valid? I guess not [as @tabatkins already said](https://github.com/w3c/csswg-drafts/issues/5558#issuecomment-700850412) in [issue 5558](https://github.com/w3c/csswg-drafts/issues/5558) so we can close this one too? @fantasai ?

**Comment by svgeesus** [comment]
@tabatkins  is trailing semicolon still open or can we close this. I recall recent discussion about adding harmless semicolons.

**Comment by tabatkins** [comment]
For quick testing, [here's a testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%40supports%20(background%3A%20green)%20%7B%0A%20body%20%7B%20background%3A%20green%3B%20%7D%0A%7D%0A%40supports%20(background%3A%20red%3B)%20%7B%0A%20body%20%7B%20background%3A%20red%3B%20%7D%0A%7D%0A%3C%2Fstyle%3E)

In both Chrome and Firefox, shows green (so semicolons aren't valid)
