### ISSUE TITLE
[css-conditional][cssom] Why CSSConditionRule?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3172]
from https://lists.w3.org/Archives/Public/www-style/2013Jun/0331.html by @zcorpan 

> In http://lists.w3.org/Archives/Public/www-style/2012Aug/0749.html it 
was decided to mint the `CSSConditionRule` interface and have 
`CSSSupportsRule` and `CSSMediaRule` inherit from it.

> I don't understand the usefulness of exposing a new property on 
`CSSMediaRule` that does the same thing as `mediaText`. Also, `conditionText` 
has different requirements for `CSSMediaRule` and `CSSSupportsRule`. Why do 
we want to have the same attribute for things that are different? 
https://bugzilla.mozilla.org/show_bug.cgi?id=814907#c3 suggests 
`@-moz-document` is again different.

> I think it would be better continue with just having `.mediaText` on 
`CSSMediaRule`, drop the `CSSConditionRule` interface, and let 
`CSSSupportsRule` and `CSSDocumentRule` have `.conditionText` with the 
interface-specific requirements.

**Comment by zcorpan** [comment]
I believe this has been implemented, so I would be ok with closing (but it would be nice to make sure there are tests for this).
