### ISSUE TITLE
Editing resolutions from Minutes F2F 2013-06-05 Wed PM IV: Syntax and Conditional Rules, Variables

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3174]
from https://lists.w3.org/Archives/Public/www-style/2013Jun/0683.html 
issue opened to be sure the resolutions were implemented

> Conditional Rules / Syntax
> --------------------------

>   RESOLVED: Whenever error-recovery closes open blocks, urls, strings,
             functions, brackets, etc., it implies the minimal tokens to
             close those constructs.

>   RESOLVED: \[EOF] turns into U+FFFD except when inside a string, in which
             case it just gets dropped.

>   RESOLVED: Clarify that badstring and baduri make @supports rules invalid

>   RESOLVED: !important allowed in @supports

>   RESOLVED: Publish CR with updates for CSS3 Conditional Rules

**Comment by tabatkins** [comment]
> RESOLVED: Whenever error-recovery closes open blocks, urls, strings,
functions, brackets, etc., it implies the minimal tokens to
close those constructs.

Implicitly covered by the current definition of parsing.

> RESOLVED: [EOF] turns into U+FFFD except when inside a string, in which
case it just gets dropped.

Ooh, that's *not* what Syntax currently specifies, but it is indeed what browsers (at least Chrome and Firefox, which I can easily test) do.

I'll file this as a separate Syntax issue.

> RESOLVED: Clarify that badstring and baduri make @supports rules invalid

Implicit in the definition of parsing already. (Neither of those tokens are in the specified grammar for the rule.)

> RESOLVED: !important allowed in @supports

Yes, explicitly allowed in the spec.

> RESOLVED: Publish CR with updates for CSS3 Conditional Rules

Given that the last /TR publication was CR on April 4 2013, we never did this one!

**Comment by svgeesus** [comment]
> Given that the last /TR publication was CR on April 4 2013, we never did this one!

I know. 

Actually I was following up [this discussion from Sydney 2018](https://lists.w3.org/Archives/Public/www-style/2018Jul/0018.html) where we also _almost_ but _didn't actually_ publish an update. 

> Conditional Rules
> =================
> 
>  dbaron: I don't know about the edits since last CR, but I know of
>          one issue that's somewhat substantive.
>  <dbaron> https://github.com/w3c/csswg-drafts/issues/1016
>
>  fantasai: Big changes were editorial and converting to Bikeshed.
>  fantasai: Substantive is whitespace around "and"/etc, and allowing
>            .supports() to drop parentheses around a single condition.
>  fantasai: Those went in, but there was no CR update.
>  Rossen: So how about we take this into break and discuss publishing
>          CR after?
>  fantasai: Yeah, maybe dbaron and TabAtkins can discuss that.

**Comment by svgeesus** [comment]
OK so all the technical issues fall into "already covered by parsing" or "separate issue on Syntax" and the only remaining issue is "republish" so in the interests of doing that, closing this issue.
