### ISSUE TITLE
[css-variables] Handling of revert keyword in custom property

### ISSUE THREAD

**Issue by justinmichaud-2** [w3c/csswg-drafts#3179]
https://drafts.csswg.org/css-variables/

I am wondering how the 'revert' keyword should be handled in a custom property.

http://jsfiddle.net/0d6Lsfr2/3/

Currently, Safari sets the value of the custom property to the inherited value, or otherwise the initial value. Chrome and Firefox both set the value of the property to the text 'revert', as seen in the test case above. 

What should be the correct behavior? It seems to me that revert should be treated in the same way as initial or inherit, which all three browsers handle in the same way. I can't find anything in the spec about this.

Thanks!

**Comment by FremyCompany** [comment]
I don't think Chrome and Firefox support the `revert` value, do they?

**Comment by FremyCompany** [comment]
(if they did, they should behave like Safari, except if the propery is specified not)

**Comment by justinmichaud-2** [comment]
I didn’t think of that. Everything makes sense then, thanks!
