### ISSUE TITLE
[css-text-4] Clarify text-spacing: punctuation

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#318]
French text is commonly marked up with regular spaces (U+0020) where the [french typographic guidelines](http://unicode.org/udhr/n/notes_fra.html) refered to by css-text-4 call for various kinds of non breaking spaces. Sometimes it is marked up with the correct (according to that guideline) kind of spaces. Sometimes it is marked up with the some other kind of spaces (U+00A0 where the guideline says there should be U+202F). Sometimes it is marked up with no space in some of these places.

How should `text-spacing: punctuation` react in these various situations? the current wording (“is inserted where required”) suggest you always add a space (of the right kind), but if there's already one there, that doesn't sound helpful.

How about:
1. If there is a U+0020 where the guideline says there should be something else, replace the U+0020 with what the guideline says. (rationale: U+00A0 and U+202F are hard to type, and people will write U+0020 instead out of convenience).
2. If there is a U+00A0, where the guideline says there should be U+202F, replace it with U+202F. (rationale: U+202F is harder to type than U+00A0 and, and people will write U+00A0 instead out of convenience).
3. If there is some other kind of space where the guidelines says there should be a U+0020, don't change it. (rationale: spaces other than U+0020, and to a limited degree U+00A0 are hard to type, and any other kind of space should be assumed to be deliberate).
4. If there is no space where the guidelines says there should be U+0020, don't add anything. (rationale: U+0020 is easy to type, and if the author wanted a space there, they'd put one. The lack of a space is therefore likely to be deliberate, maybe because this is a case of unconventional use of the punctuation).
5. If there is no space where the guideline says there should be U+00A0 or U+202F, insert the right kind. (rationale: these spaces are hard to type, and therefore sometimes skipped. English typing habits also lead to people forgetting to type these spaces. And if you really did not want these spaces inserted, you can always do `text-spacing: none` instead of `text-spacing: punctuation`).
6. if there is a space of any kind where the guideline says there should be none, leave it there. (rationale: something where there should be nothing is likely to be deliberate)

**Comment by da2x** [comment]
This would also be useful for other languages. The pair `f?` require extra spacing in more languages than just French. Fonts rarely contain kerning pair metrics for this pair.

**Comment by frivoal** [comment]
https://github.com/w3c/csswg-drafts/issues/4246#issuecomment-1404738513, if adopted, would cover for this with `text-autospace: punctuation insert` vs `text-autospace: punctuation replace`

**Comment by frivoal** [comment]
Satisfied by https://github.com/w3c/csswg-drafts/commit/29661048af03edf0c093f339e03afc41803c6238 and https://github.com/w3c/csswg-drafts/commit/5fe43af7bc0fd72426c1936457e78414ac9e93b3
