### ISSUE TITLE
[css-syntax] Correctly handle "escaped EOF"

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3182]
Per our June 2013 resolution (recorded in <https://github.com/w3c/csswg-drafts/issues/3174>), the correct way to handle an "escaped EOF" (that is, a stylesheet ending in a `\`) is to produce a U+FFFD, except in strings, where it is ignored.

Currently, Syntax correctly specifies that you ignore an escaped EOF in a string, but for anything else, it ends the current token, then reconsumes the `\` as a fresh token, which ends up producing a DELIM token containing `\`.

It looks like I can't just simply modify that clause in "Consume a token", because implementations don't end the preceding token.

[Test case](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6237):
```html
<!DOCTYPE html>
<style>.foo {--foo:foo\</style>
<style>.foo {--foo:foo \</style>
<style>.foo {--foo:"foo\</style>
<script>
for(var sheet of document.styleSheets) {
  w(sheet.cssRules[0].cssText);
}
</script>
```

**Comment by tabatkins** [comment]
Current behavior of the testcase:

## Chrome

```
log: .foo { --foo:foo�; }
log: .foo { --foo:foo �; }
log: .foo { --foo:"foo"; }
```

## Safari 

```
log: .foo { --foo: foo�; }
log: .foo { --foo: foo �; }
log: .foo { --foo: "foo"; }
```

## Firefox

```
log: .foo { --foo:foo\�; }
log: .foo { --foo:foo \�; }
log: .foo { --foo:"foo"; }
```

## Edge

```
log: .foo { --foo:foo\; }
log: .foo { --foo:foo \; }
log: .foo { --foo:“foo\; }
```
(Yes, Edge *really* printed these, every single one of which isn't even *remotely* correct.)

----

So, Edge is clearly super-wrong. Chrome and Safari agree, and obey the old resolution. (How they did so, when the spec doesn't say to do that, I'm not sure...)  Firefox obeys the resolution, but unnecessarily escapes the U+FFFD when serializing.

Darn, I was hoping *somebody* implemented the thing I already had specced, so I didn't have to change anything. ^_^

**Comment by tabatkins** [comment]
...huh. Plugging the first test-case into [the dingus](https://rawgit.com/tabatkins/parse-css/master/example.html), I get the same result as Chrome/WebKit (a U+FFFD that doesn't interrupt the token). This suggests that I changed the spec at some point to the current text. I'll have to research why I did this.

**Comment by tabatkins** [comment]
Ah, found it: https://github.com/w3c/csswg-drafts/issues/1821

I was trying to fix `#-\EOF` getting recognized as an ident, but looking at impls, they do indeed treat that as an ident type. (The dingus doesn't, so that's a bug...) I just need to revert that "fix".

**Comment by tabatkins** [comment]
Agenda+ to verify I can fix this.  The fix is that an "escaped EOF" (aka a `\` at the end of a stylesheet) should return U+FFFD, not a \ as the spec currently mandates. (Except in strings, where it's just silently ignored.)  This matches all browsers now that Edge is going away - the only difference is that Firefox *serializes* such an EOF differently than Chrome/WebKit. (But that's not a Syntax problem, it's a CSSOM problem.)

A side effect of this is that ending a stylesheet with `-\EOF` will create an ident. This matches browser behavior, so it should be fine.

**Comment by emilio** [comment]
It would be amazing to add a WPT for this if we specify it.

**Comment by tabatkins** [comment]
Yup def. I pushed a few updates last week when closing out issues that I need to write WPTs for too; I'll do that this week.

(For that matter, I think y'all's serialization implementation is wrong here, and will cause you to spuriously fail the test I would write for this issue.)

**Comment by emilio** [comment]
Hmm, why? The serialization roundtrips, doesn't it? cc @SimonSapin

**Comment by tabatkins** [comment]
It roundtrips, yeah, but the escape is unnecessary. Everything outside of ASCII range is fine to be emitted directly; escaping it is basically a no-op.

There's nothing in CSSOM's serialization rules that say to escape that character.

**Comment by tabatkins** [comment]
All right, fix committed in spec, and test will be committed as soon as Travis cycles.
