### ISSUE TITLE
Add background-rotate property that we  just have to rotate the background without affecting the text and only one layer

### ISSUE THREAD

**Issue by piaoxuelia** [w3c/csswg-drafts#3183]
I want to make an animation like this, the background keeps rotating at a constant speed，but now，
I must have three layers, the cyan layer, the rotating translucent  background layer and the text .
![image](https://user-images.githubusercontent.com/7304235/46254570-f30a3780-c4c3-11e8-84e5-0d977a787475.png)

the background-rotate property can resolve this problem,  only one layer is ok.

**Comment by piaoxuelia** [comment]
We can do this animation using CSS-animation to control the rotation speed，background-rotate to control the angle of the background.

**Comment by inoas** [comment]
Background rotation must define if clipping happens or not?

**Comment by upsuper** [comment]
There was a property defined in css-logical for rotating background image called [background-image-transform](https://www.w3.org/TR/2017/WD-css-logical-1-20170518/#background-image-transform-prop), but it was for a different use case and has been removed recently.

If we want to add the property for this use case, we may still want to call it `background-image-transform` and probably allow it to accept the same syntax as `transform`. Considering `background-image` is a list of images, this property may want to be a list as well.

**Comment by bradkemper** [comment]
With the existing background properties, you wouldn’t really need scale() or translate(). Personally, I don’t think skew() or matrix() would be anywhere near as useful as rotate. So I’d be happy with background-rotate. 

I think the whole tile should rotate around it’s center, without changing where the center of other tiles is: background-size would only be based on un-rotated images. Thus, corners might overlap a little when rotated.

**Comment by Loirooriol** [comment]
#4706 was analogous, it proposed a `background-filter` property, but it was rejected in favor of `filter()`.

For consistency, maybe CSS Transforms should define a `transform()` or `rotate()` function that can be used anywhere an `<image>` is expected, rather than adding more `background-*` properties. Like

```css
background-image: transform(url(background.jpg), rotate(180deg));
```

This would allow to transform images not just for backgrounds but also for things like border images or maybe cursors.

**Comment by leandroruel** [comment]
in cases where we have backgrounds that we desire to rotate, we have to rotate the whole element through css transforms, but if we want add it to a <body> element, would be great if we could add a property: background-rotate so we can rotate the whole bg image easily like:

```html
<style>
   body {
     background-image: url(pattern.png);
     background-repeat: repeat-y;
     background-rotate: 180deg;
  }
</style>
```

this will avoid have to rotate the element and instead we only rotate the background.

also, about the comment of @Loirooriol i think a new property is still valid for specific cases, where if any developer needs add the property with javascript.

**Comment by SebastianZ** [comment]
> also, about the comment of @Loirooriol i think a new property is still valid for specific cases, where if any developer needs add the property with javascript.

Manipulation via JavaScript is also possible with @Loirooriol's suggested solution, but it is more cumbersome if you just want to rotate the background image.
Though adding a `transform()` function also has two big advantages. It can be used everywhere where images are allowed and you can apply more transformations than just rotations.

Sebastian

**Comment by leandroruel** [comment]
also make transitions more smoother

**Comment by SebastianZ** [comment]
For reference, in #6807 a more general solution for image manipulations is discussed which covers this use case but goes far beyond the possibilities of a `transform()` function.

Sebastian

**Comment by LeaVerou** [comment]
Since there was no response by the OP and this is was a primary use case for `@image`, let’s close this too. @piaoxuelia feel free to comment if you disagree.
