### ISSUE TITLE
[css-scroll-snap] scroll-padding-block/inline and auto

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3189]
The following properties have `auto` as their initial value, but their grammars only accept `<length>` values:

- scroll-padding-block
- scroll-padding-block-end
- scroll-padding-block-start
- scroll-padding-inline
- scroll-padding-inline-end
- scroll-padding-inline-start
 
https://drafts.csswg.org/css-scroll-snap-1/#padding-longhands-logical

**Comment by fantasai** [comment]
Good catch! Fixed, thanks so much for your attention to detail!!

**Comment by ewilligers** [comment]
The grammar for [`scroll-padding`](https://drafts.csswg.org/css-scroll-snap-1/#propdef-scroll-padding) uses `[` `]`.

I suspect `scroll-padding-block` and `scroll-padding-inline` need square brackets to, so they can accept `auto 10px` and `10px auto` and `auto auto`.

**Comment by fantasai** [comment]
Man, even typoed the commit message *and* have a grammar error. I can't do anything right in this issue. T_T

Is the spec correct yet, @ewilligers ?

**Comment by ewilligers** [comment]
Looks good, thank you.
