### ISSUE TITLE
[css-color] new predefined colors

### ISSUE THREAD

**Issue by andrew79pl** [w3c/csswg-drafts#3192]
Hello everyone
I have a proposal for you. Is it possible to set two new predefined colors?

lighterblue 3050ff
bluesmoke eeeef8

Best regards
Andrzej Guligowski, Poland

**Comment by svgeesus** [comment]
No.

If you have a serious need, in your own stylesheets, use CSS variables:

```
--weed-green: hsl(120, 20%, 60%);
div.spliff {
  background: var(--weed-green);
}

**Comment by tabatkins** [comment]
To be more specific, the CSS set of named colors originate from (one version of) the X11 color set, used by a number of Unix variants and other programming systems. ([Alex Sexton gave a *very* funny and informative talk about the history of these colors.](https://www.youtube.com/watch?v=HmStJQzclHc))

When we added named colors to CSS, we just took one of the sets that existed at the time and used it. We've only added to this set *once*, as a memorial gesture to somebody very important to the history of CSS. We don't expect to do this again, as the named colors are weird and bad in general, and expanding them doesn't bring any significant value.

Plus, as Chris said, you can now do it yourself with custom properties.
