### ISSUE TITLE
[css-values-3] serialization of fragment URLs in image properties

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#3195]
https://drafts.csswg.org/css-values-3/#local-urls

Should properties that take `<url>`s as images serialize fragment URLs as just the fragment or as the full, resolved URL?  The spec doesn't make any distinction between `<url>`s for images and non-images (such as various SVG properties like `marker-start`).  The fragment URL concept was introduced to make it easier to use local references for non-image properties when the base value might change, and local URLs don't really make sense for images.

Test: https://mcc.id.au/2018/10/url-fragment-serialize.html

<details>
<summary>Results</summary>
<table>
<tr><th><th colspan=2>background-image<th colspan=2>mask-image<th colspan=2>filter<th colspan=2>marker-start
<tr><th><th>specified<th>computed<th>specified<th>computed<th>specified<th>computed<th>specified<th>computed

<tr><th>Chrome<td>url("#x")<td>url("https://mcc.id.au/2018/10/url-fragment-serialize.html#x")<td><td><td>url("#x")<td>url("#x")<td>url("#x")<td>url("#x")

<tr><th>Edge<td>url("#x")<td>url(https://mcc.id.au/2018/10/url-fragment-serialize.html#x)<td><td><td>url(#x)<td>none<td>url("#x")<td>url("#x")

<tr><th>Firefox<td>url("#x")<td>url("https://mcc.id.au/2018/10/url-fragment-serialize.html#x")<td>url("#x")<td>url("https://mcc.id.au/2018/10/url-fragment-serialize.html#x")<td>url("#x")<td>url("#x")<td>url("#x")<td>url("#x")

<tr><th>Safari<td>url("https://mcc.id.au/2018/10/url-fragment-serialize.html#x")<td>url("https://mcc.id.au/2018/10/url-fragment-serialize.html#x")<td><td><td>url("#x")<td>url("#x")<td>url("#x")<td>url("x")

</table>
</details>

 

All four browsers I tested serialize the computed value of `background-image` with a fragment as the entire resolved URL. (Safari is an odd one out in serializing the entire resolved URL for the specified value, too. And there's a bug in the `marker-start` computed value serialization.)

I think it makes sense to treat image and non-image `<url>` values the same way wrt fragment URLs, but since nobody implements this behavior I wanted to check to make sure it's what we all agree with before changing.

**Comment by tabatkins** [comment]
Local urls make plenty of sense for images - they can point to an inline `<svg id=foo>`, right? (Or to a mask/etc defined inside an inline SVG.)

I think that fragment-url behavior should apply globally. I'll bet that the current serializations don't *actually* reflect round-trippable behavior.

**Comment by heycam** [comment]
No, you can't refer to a local `<svg>` element as an image with any property. (Though Gecko's `-moz-element(#foo)` syntax allows referencing any element's rendering as an image.) For mask references, they must be to a `<mask>` element, not to an `<svg>` that is used as a mask image.

**Comment by emilio** [comment]
I think we should be consistent here and serialize just in a single way, local refs remaining unresolved. WDYT @tabatkins?

**Comment by emilio** [comment]
Sure, my point is that this doesn't match implementations, but we can try to change to unify here. Last time I checked only a few tests relied on this.

**Comment by tabatkins** [comment]
@emilio We can't tell if you're unhappy with the WG resolution or not? Could you clarify what you would like to happen here, if anything?

**Comment by emilio** [comment]
I'm not unhappy with the resolution, sorry, I think it makes perfect sense.

My only point was that people may rely on the existing behavior (hopefully not), so we may need to revisit if the change is not compatible. But that's not anything particularly new so :)
