### ISSUE TITLE
[css-ui] Add value `horizontal-text` to property `cursor`

### ISSUE THREAD

**Issue by Zhang-Junzhi** [w3c/csswg-drafts#3196]
There are currently two kinds of "text" icon in `cursor` at [ui-4 draft](https://drafts.csswg.org/css-ui-4/#valdef-cursor-text): `text` and `vertical-text` .

For `text`, the spec says the UA can either always render the cursor as in horizontal writing mode, or render it based on the writing-mode value. IMO, this has two issues:

1. This is logical asymmetry. Why can `text` be specially treated as always for horizontal writing mode as an alternative, why can't it be treated as always for vertical writing mode?

2. Also this is problematic if the designer really wants the cursor to depend on the writing mode, because according to the spec, the behaviour of the `text` doesn't garantee the cursor is writing-mode dependent.

I suggest we change the `text` to be always writing-mode dependent, and add a new value `horizontal-text` to `cursor`. I don't think there are compatibility problems in the real world, as the writing mode isn't widely used for now. The earlier we change it, the smaller the problem it would cause.

**Comment by tabatkins** [comment]
Those sorts of "can be A or B" spec texts usually mean that, at the time the spec was written, browsers had both of those behaviors, and there wasn't a clear preference for everyone to shift one way or the other. If this has shifted, and browsers now agree on a behavior, we can easily change!

That said, while this spec text is *weird*, there's not a strong benefit in doing anything here, as the current values *do* suffice for authors. If you just set `text` on any with a horizontal writing mode, and `vertical-text` on anything with a vertical writing mode, you're guaranteed to get the correct cursor at all times. In some browsers the `vertical-text` isn't required, as `text` would work correctly, but nobody is hurt by applying `vertical-text` to vertical text.

(You can't reliably apply a horizontal-text bar to vertical text with the existing values, but that's *really weird to do*, so it's not an important lack to solve.)

**Comment by Zhang-Junzhi** [comment]
> If you just set text on any with a horizontal writing mode, and vertical-text on anything with a vertical writing mode, you're guaranteed to get the correct cursor at all times

Thanks for the reply.

What you said is applicable in pure CSS method when you already know the writing mode of the parent of the target element beforehand.

But please consider there are cases when the developer wants to write a reusable widget which can be used in senarios where the writing mode is unknown beforehand. And That was what I encountered before I posted this issue. So, the method isn't applicable. I do think it's necessary to resolve it.

**Comment by frivoal** [comment]
For that case, should we just put pressure on UAs to make `text` always match the writing mode (I.E. by making it a must in level 4), and then deprecating `vertical-text`, since there would be no use left for it?

**Comment by Zhang-Junzhi** [comment]
I second @frivoal

**Comment by frivoal** [comment]
Agenda+ to propose changing from may to must about `cursor: text` displaying a rotated cursor for vertical text.

**Comment by svgeesus** [comment]
I agree, automatic alignment (with `must`) is preferable

**Comment by SelenIT** [comment]
What about elements with selectable text (either horizontal or vertical) rotated by 90deg via `transform` for some design/presentation purposes? Isn't it a possible use case for applying a text cursor perpendicular to the actual text direction to such elements?

**Comment by Zhang-Junzhi** [comment]
yes, maybe we should also consider `frantsform`.

And further, `transform` for any angles other than a right angle might need to be considered too.

IMHO, I suggest the spec recommend UAs to render a horizontal or vertical text cursor, depending on which one has a angle less than 90 degree with the current text.

**Comment by litherum** [comment]
What about stacked vertical text? The characters are horizontal but the line is vertical.
