### ISSUE TITLE
[css-grid] Stretching Fixed-size Tracks

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#320]
So I was just adding more examples to the Grid spec, and I think we should revisit the decision of which tracks 'align/justify-content: stretch' applies to. Currently it only applies to auto-sized (i.e. content-sized) tracks. However, I do expect something like
```
  grid-template-columns: repeat(auto-fill, 5em);
  justify-content: [whatever]
```
to be a common use case, and the fact that all the alignment values except `stretch` have their intended effect, and can be easily switched among, seems odd.

In contrast, I expect wanting content-sized items to be stretched while fixed-size tracks in the same grid are not, to be a less common case. In any case, thoughts on this point?

**Comment by mrego** [comment]
Just a quick thought, if we decide to stretch fixed-size tracks, as `stretch` is the default value for `justify-content`, a very simple grid example will stretch horizontally to take whole viewport (dunno if we want that to be the default behavior).

So this example:
```html
  <div style="display: grid; grid-template-columns: 100px 100px;">
    <div style="background: magenta;">item 1</div>
    <div style="background: cyan;">item 2</div>
  </div>
```

Would be the same than using `grid-template-columns: 1fr 1fr;`.
Dunno if that's what we want by default in all the grids, but IMHO the first time you use them you might be quite confused.

**Comment by rachelandrew** [comment]
That sounds very confusing. I'd expect 100 pixel tracks **not** to stretch as a default behaviour.

**Comment by fantasai** [comment]
The default value for align/justify-self has to be stretch, but for align/justify-content we could easily make it start -- the real default is 'normal'.

**Comment by tabatkins** [comment]
Yeah, I'm very confused about this too. `stretch` *very explicitly* doesn't stretch things with a definite size in Flexbox already; why would you expect it to stretch definite-size things in Grid?

Like, all the other values work *because they're not trying to change the size of the tracks*, just their positions.  Only `stretch` does that.
