### ISSUE TITLE
[css-align][css-flexbox][css-grid] Can baseline content-aligned items and baseline self-aligned items align together?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3200]
There's a note in CSS Grid ([11.5 step 1](https://drafts.csswg.org/css-grid-1/#algo-baseline-shims)) saying that these are handled as separate categories, but nothing in css-align says so. And also the Grid Container Baselines section ([10.6 in Grid](https://drafts.csswg.org/css-grid-1/#grid-baselines)) also seems to imply that there is only one set of baselines. So we need to be clear about which is true.

Secondly, if they are in fact two different sets of baseline-aligned things, then which set is used when propagating the baseline up the box tree? E.g. a grid container with 50% items baseline content-aligned and baseline self-aligned, which is itself baseline (content- or self-) aligned in a parent grid or flexbox.

Proposal: Align the note and clarify css-align to match 10.6 in Grid: there is only one baseline that is shared across items in an alignment context, and both types of baseline alignment use it.

**Comment by fantasai** [comment]
@dholbert @MatsPalmgren @javifernandez Thoughts?

**Comment by dholbert** [comment]
> Proposal: Align the note and clarify css-align to match 10.6 in Grid: there is only one baseline that is shared across items in an alignment context, and both types of baseline alignment use it.

Just to clarify, by "only one baseline" I think you really mean "only one pair of baselines" (first/last), right?  (and "only" = there isn't a separate set for self-alignment vs. content-alignment)

This sounds reasonable to me, anyway.

**Comment by fantasai** [comment]
@dholbert Right.

> This sounds reasonable to me, anyway.

Cool. :)

**Comment by javifernandez** [comment]
> Proposal: Align the note and clarify css-align to match 10.6 in Grid: there is only one baseline that is shared across items in an alignment context, and both types of baseline alignment use it.

I think the proposal makes sense.

**Comment by fantasai** [comment]
OK, fixed the bad note in css-grid-1, and added a clarifying note in css-align-3. @tabatkins can you verify the edits and make sure they're in the best place? :)
