### ISSUE TITLE
[css-grid-1] Interpolating track listings

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3201]
Currently grid-template-rows/columns interpolate “per computed value”, which means that if the number of tracks differs, or any track changes to/from a particular keyword value to any other value, or if a line name is added/removed at any position, the entire track listing is interpolated as “discrete”. But we have some more granular options:

- Check interpolation type per track, rather than for the entire list, before falling back to discrete. I.e. a length-percentage track can animate between two values while an adjacent auto track flips discretely to min-content.
- Allow discrete interpolation of line name changes independently of track sizes.
- Allow interpolation of mismatched track list lengths, by filling in missing values from `grid-auto-rows/columns`.

Wanted to hear back from implementers what they think is reasonable here. CC @MatsPalmgren @mrego @javifernandez @birtles

**Comment by birtles** [comment]
> Note that in w3c/svgwg#543 implementors were unhappy about "splitting up" the interpolation of a single property such that some parts could interpolate discretely due to a mismatch while the rest still interpolated normally.

Specifically, I think Blink had difficulty with this for path commands in particular. In Gecko/Servo it makes no difference--rather we had to add code to achieve the less granular fallback behavior.

Going forward, I think we should prefer more localized/granular fallback for the reasons I outlined in that issue.

That said, I definitely agree we want to avoid dependencies between properties when doing interpolation.
