### ISSUE TITLE
[css-conditional-4] selector() feature query function for selector support

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#3207]
I think one feature we should add to Conditional Rules Level 4 is a feature query function to test for selector support, presumably called `selector()`.

I've started a [draft of an explainer for this](https://github.com/dbaron/css-supports-functions/blob/master/explainer.md), from which I quote the relevant section:

-----

Having feature queries based on selectors is probably the highest priority addition, both because it seems the most likely to be important in the near future, and because it is the simplest.  It has come up recently because CSS authors using the features in the [CSS Scrollbars Module Level 1](https://drafts.csswg.org/css-scrollbars-1/) may want to query for support of those features, and may also want to query for support of the `::-webkit-scrollbar` pseudo-element.

I believe a possible syntax for such a feature was discussed at one point early in the development of `@supports`, but I can't find meeting minutes of the discussion.  I think the best way to extend the syntax is using a `selector()` function, as in:

```css
@supports (scrollbar-width: thin) or selector(::-webkit-scrollbar) {
  #chatwindow { overflow: scroll; scrollbar-width: thin }
  #chatwindow::-webkit-scrollbar { width: 5px }
}
```

It is worth noting that this usage requires that the `selector()` feature query function *not* copy the quirks that are present in selector parsing, where all `::-webkit-*` pseudo-elements behave as though they're supported (and allow the selector to parse).  Instead, inside of the `selector()` feature query function, this quirk should not be present, and a `selector()` function containing a `::-webkit-*` pseudo-element should only be true if the pseudo-element is *actually* supported.

Other than this, the function should work just as the tests for support/validity work in the [rules on handling invalid selectors](https://drafts.csswg.org/selectors-4/#invalid).

**Comment by tabatkins** [comment]
I agree that this is useful and high-priority among possible @supports additions, and think that's the right syntax.

**Comment by inoas** [comment]
Great idea!

What about other selectors and matching them?

```css
@supports selector(<) {
    // use imaginary future < selector
} else @supports selector(:visible) {
    // use imaginary future :visible selector
} else {
   // use some conventional selector
}
```

p.s.: no endorsement for those imaginary selectors

**Comment by tabatkins** [comment]
`selector(<)` would likely fail; it doesn't match the selector grammar.  But you could write `selector(a < b)` and it would match in a hypothetical world were we added that combinator.

`selector(:visible)` would definitely work, exactly the same as dbaron's other examples.

`else` is *also* something we should add: http://tabatkins.github.io/specs/css-when-else/ ^_^

**Comment by inoas** [comment]
so maybe ```selector-operand(<) {}```? not sure forcing one to add virtual dom elements to check for selector operand support sounds so sane to me...

**Comment by tabatkins** [comment]
? You don't have to add any elements. You just have to create a well-formed selector, so we can do a trivial "does this parse as a selector" check. You already know for a fact that `a` and `b` are valid tagname selectors.

**Comment by fantasai** [comment]
`selector(* > *)` would also work if you don't want to choose arbitrary tag names.

**Comment by ExE-Boss** [comment]
I was planning to suggest this.

Also, when it comes to functional selectors, I presume that the brackets are necessary (eg.&nbsp;`selector(::slotted(*))` will need to be used)

This would also go hand in hand with https://github.com/w3c/csswg-drafts/issues/3082.

**Comment by emilio** [comment]
I think I'd prefer if we just used the `<selector>` syntax. Using a `<selector-list>` looks like different arguments to the function, and it wouldn't be clear whether the semantics are `all` or `any`.

**Comment by emilio** [comment]
Plus the `<selector>` syntax can be extended later if needed, but not the other way around.

**Comment by emilio** [comment]
I meant `<complex-selector>`, btw.

**Comment by ExE-Boss** [comment]
I think we should just be checking syntactic correctness.

**Comment by emilio** [comment]
A missing namespace is a parse error everywhere else, I'd rather be consistent on _rejecting_ it, since not doing that introduces a special-case, and other APIs like `querySelector` already throw on that, like (for example, `document.querySelector("a|b")` throws, doesn't return null).

**Comment by emilio** [comment]
FWIW the namespace question came during the code review of https://bugzilla.mozilla.org/show_bug.cgi?id=1499386.

**Comment by ExE-Boss** [comment]
I have now updated [the relevant MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports):
- https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#Function_syntax
- https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#Testing_for_the_support_of_a_selector

**Comment by jonjohnjohnson** [comment]
I know we are talking about syntax for a **feature** query, and a lot has already been brought up, but wanted to make sure it was addressed that previously the concept of a "selector" query was mentioned to match a selector against the current state of the document.

In https://github.com/w3c/csswg-drafts/issues/112#issuecomment-221672439 @tabatkins  said...

> @fantasai So if we pretend there's a selector() function that is true if something on the page matches that selector, I think you'd write:
> 
> @when selector(body.toc-inline) or (media(width < 28em) and not selector(body.toc-sidebar)) {
>   /* inline ToC styling */
> } @else {
>   /* sidebar ToC styling */
> }

Figured it worth mentioning, even if some other syntax like `query()` could be better.

**Comment by tabatkins** [comment]
Yeah, that's a completely unrelated proposal.

**Comment by astearns** [comment]
From the IRC log above:

RESOLVED: Create CSS conditional rules level 4
RESOLVED: Accept selector feature functions for selector support in @supports, accepting a single complex selector as an argument.
RESOLVED: Namespaces are either always valid or valid when they're declared.

**Comment by emilio** [comment]
We're not shipping it without writing the spec.

**Comment by yisibl** [comment]
chrome has shipped https://bugs.chromium.org/p/chromium/issues/detail?id=979041#c13
