### ISSUE TITLE
[css-text] WPT text-indent-percentage-001.xht checks for deprecated behavior

### ISSUE THREAD

**Issue by szager-chromium** [w3c/csswg-drafts#3218]
This test:

css/css-text/text-indent/text-indent-percentage-001.xht

... needs to be updated to test for the newly-specified behavior:

https://github.com/w3c/csswg-drafts/issues/2394

**Comment by upsuper** [comment]
You should probably raise this in wpt repo rather than here.

**Comment by szager-chromium** [comment]
Done:

https://github.com/web-platform-tests/wpt/issues/13581
