### ISSUE TITLE
[css-multicol] Improve column-fill and make it backward-compatible

### ISSUE THREAD

**Issue by mstensho** [w3c/csswg-drafts#3224]
Chromium, Edge and WebKit all seem to implement column-fill:auto as specified in the CR: https://www.w3.org/TR/2011/CR-css3-multicol-20110412/#cf

In particular, when block size is unconstrained, balancing is forced.

Example:
```
<div style="columns:3; column-fill:auto;">
  column-fill is auto.<br>
  Height is unconstrained<br>
  The old spec says to force balancing in such situations.<br>
  The new spec does not say anything about to that effect.<br>
</div>
```

Gecko doesn't force balancing in this case, while all the other do it. Gecko appears to follow the new spec: https://drafts.csswg.org/css-multicol/#cf for column-fill:auto. It does have issues with column-fill:balance if height is non-auto, though:

```
<div style="columns:3; height:20em; column-fill:balance;">
  column-fill is balance.<br>
  Height is non-auto, and large.<br>
  This should still be balanced<br>
  although everything *could* fit in the first column<br>
</div>
```

All spec versions require the above to be balanced, but Gecko doesn't do it. But note that if you shrink the height from 20em to e.g. 10em it gets balanced - so this looks like a bug and not deliberate behavior.

The spec was changed in 2012 by Håkon Wium Lie:
https://github.com/w3c/csswg-drafts/commit/e0a990c7e6514f95f1d0c3d6ccb08f4552365f44

Given that Gecko has bugs in its implementation, and given that all the others still follow the old spec, I think we have an opportunity to fix the new spec. Most importantly, I'd like the spec to be backward-compatible, so that column-fill:auto forces balancing if block size is unconstrained (and before each spanner).

If we really want a mode that never forces balancing, how about introducing column-fill:fill for that? That mode could even refrain from balancing before spanners (and only break if there are explicit breaks).

**Comment by fantasai** [comment]
@mstensho Makes sense to me. I think you meant s/constrained/unconstrained/ in the 2nd to last paragraph though?

**Comment by mstensho** [comment]
@fantasai That's indeed what I meant. :) Edited. Thanks a lot!

**Comment by jensimmons** [comment]
To try and understand this issue, I just dropped the examples into a CodePen: https://codepen.io/jensimmons/pen/XxBVLz?editors=1000

**Comment by jensimmons** [comment]
To better understand this issue, I dropped these examples in a CodePen: https://codepen.io/jensimmons/pen/XxBVLz?editors=1000

**Comment by rachelandrew** [comment]
yes it does - I've not had chance yet

**Comment by rachelandrew** [comment]
[There are some examples to go with this writeup](https://codepen.io/rachelandrew/pen/gZedrZ).

The issue as raised is that currently Blink, WebKit and Edge all have implemented `column-fill: auto` as in an older version of the multicol spec (the one which was at CR before we went back to a WD), the implementations follow text which said:

> "In continuous media, this property [column-fill] will only be consulted if the length of columns has been constrained. Otherwise, columns will automatically be balanced."

If you look at the examples in any of those browsers you can see that example 1, with no height has balanced and example 2, with a height has filled columns in turn to the specified height.

This text was commented out [in 2012](https://github.com/w3c/csswg-drafts/commit/e0a990c7e6514f95f1d0c3d6ccb08f4552365f44). Firefox has implemented to not balance an unconstrained multicol container.

I haven't looked a lot at non-browser UAs but Prince is doing the same thing as Firefox (so not balancing an unconstrained container, giving us one column of text).

**The proposal is to update the spec to match what Blink/WebKit/Edge are doing.**

Additional suggestions are **to include `min-` and `max-` constraints** as also being a reason to consult column-fill and not balance when it is auto. My examples 3 and 4 show a multicol container with a min-height of 200 pixels with a larger and smaller amount of content.

There is a use case for including min- as a constraint which is the one where you have a multicol container and sometimes the amount of content added leaves you with one or two lines of text in each column. In that scenario it would be much better to have a single column than spread the content out across multiple columns. Adding a `max-` constraint might be problematic if sometimes there was a lot more content than expected. As an author I'd find it useful behaviour to be able to set a `min-height` constraint and `column-fill: auto` and the columns fill sequentially with no balancing until that min-height is reached. At that point start balancing.

We also have issue #3064 asking for this behaviour.

**There is also a suggestion to introduce `column-fill: fill` as a never balance mode**:

> "If we really want a mode that never forces balancing, how about introducing column-fill:fill for that? That mode could even refrain from balancing before spanners (and only break if there are explicit breaks)."

There was also discussion in terms of defining what min and max content mean, with @fantasai suggesting that:

> "current proposal, if there's no min/max constraint, and the height is specified to be an automatic size, it's equivalent to min-content".

I think the things we need to decide upon are:

1. Should we update the spec to return to the behaviour as implemented in Blink/WebKit/Edge that `column-fill: auto` balances an unconstrained container, and does not balance a constrained container?
2. Should we include min and max as constraints as requested in #3064 
3. Do we want to introduce a never balance mode as suggested by Morten with `column-fill: fill`?

**Comment by frivoal** [comment]
My take on this:
1. yes, especially if we also do 2
2. yes
3. possibly, but not in level 1. I'd put that in level 2

**Comment by mstensho** [comment]
Looks like this resolution didn't make it into the spec - i.e. according to the spec, `column:fill-auto` is always honored (except before spanners), even if block-size of the multicol container is unconstrained.

Also, Chromium follows the "new" spec now [1]. WebKit still doesn't, and will force-balance if block-size of the multicol container is unconstrained, like the spec used to say back in the days (before this issue was filed).

[1] Fixed three years ago: https://chromium-review.googlesource.com/c/chromium/src/+/4173395

So... all good, I suppose? Especially if WebKit also fixes it.
