### ISSUE TITLE
[css-transitions-2] Effect of manipulating a CSSTransition via the Web Animations API on the list of running transitions

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#3233]
The CSS Transitions spec, in the [Starting of Transitions](https://drafts.csswg.org/css-transitions-1/#starting) section, discusses the notion of a [running transition](https://drafts.csswg.org/css-transitions-1/#running-transition). The content of that list is made clear in the context of resolving styles and dealing with the various `transition-` properties, but I'm not certain what should happen when a running transition is manipulated via the Web Animations API.

Consider this example:

```javascript
const target = document.querySelector("div");
target.style.transition = "margin-left 1s"

requestAnimationFrame(() => {
    // This starts a transitions, the element now has a running transition.
    target.style.marginLeft = "200px";
});

setTimeout(() => {
    const transition = target.getAnimations()[0];
    // This will yield a "transitioncancel" event. Is this animation now no longer
    // considered to be a running transition?
    transition.timeline = null;
    setTimeout(() => {
        // This will resume the animation for the last quarter of its duration.
        // Is this animation now a running transition or just some animation
        // outside of the list of running transitions? 
        transition.timeline = document.timeline;
    }, 250);
}, 500);
```

Essentially, my question boils down to whether an animation is considered a _running transition_ just by virtue of having been created via a CSS `transition` property and being in a _running_ play state, or is it considered to be a _running transition_ only when created via a CSS `transition` property and until it enters a play state other than _running_.

**Comment by graouts** [comment]
@birtles @flackr @stephenmcgruer

**Comment by graouts** [comment]
I think this might be related to issue #2948.

**Comment by birtles** [comment]
This will be defined in CSS Transitions 2.

(But for what it's worth, I believe it should be the latter and will be defined in terms of the [owning element](https://drafts.csswg.org/css-transitions-2/#owning-element-section) concept such that it is only a _running transition_ when it has an owning element.)
