### ISSUE TITLE
[css-break-4] Add CSS Break 4

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#3234]
The CSS Fragmentation Module Level 3 is now in CR and there is already some discussion about adding a `margin-break` property (see #253 and #1939) and [a few others](https://github.com/w3c/csswg-drafts/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Acss-break-4) to the next level of the specification.

Therefore I believe it's now time to start working on the Level 4 document, so discussion for future fragmentation features has a place.

Sebastian

**Comment by fantasai** [comment]
Done.
