### ISSUE TITLE
[css-transforms-2] Allow interpolating from rotate[XYZ]?(0deg) to rotate[XYZ]?(__deg) by interpolating the angles

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#3236]
e.g. interpolating from `rotate(0deg)` to `rotateX(360deg)` by interpolating the angles rather than falling back to matrix interpolation.
Test case: https://thimbleprojects.org/mozillalearning/213517/

Blink has special case code for when one argument has an angle of roughly zero:

  https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/transforms/rotation.cc?l=67&rcl=d89a726271a6b6934ec72510c2da3f4495729e5b

The other UAs don't. Strictly speaking, the spec doesn't currently allow this. It only has:

> For interpolations with the primitive rotate3d(), the direction vectors of the transform functions get normalized first. If the normalized vectors are equal, the rotation angle gets interpolated numerically. Otherwise the transform functions get converted into 4x4 matrices first and interpolated as defined in section Interpolation of Matrices afterwards.

However, it seems to match what the author would expect so I suggest we update the spec to require this.

**Comment by tabatkins** [comment]
I strongly agree that rotates with parallel vectors should animate by angle.

(Maybe also anti-parallel?)

**Comment by birtles** [comment]
I'm not sure this is about parallel vectors (although I'm definitely out of my depth when it comes to 3D math) but special-casing the `rotate[XYZ]?(0deg)` case to match the axis of the other rotation value.

For the specific content that prompted this issue the values are 'rotate(0deg)' and 'rotateX(360deg)' which produces vectors of `[0, 0, 1]` and `[1, 0, 0]` respectively.

**Comment by birtles** [comment]
There are a few other conditions where Blink will match up otherwise mismatched vectors:

  https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/transforms/rotation.cc?l=58-99&rcl=d89a726271a6b6934ec72510c2da3f4495729e5b

I don't suppose someone who worked on this code would care to spec this behavior (@alancutter perhaps?).

**Comment by tabatkins** [comment]
Oh, sorry, I didn't recognize that it was the 0deg that was important there! There's too much going on in the function names. ^_^

So yeah, I *also* totally agree with this, a 0deg rotate should be compatible with *any* other rotation, regardless of axis.

**Comment by ewilligers** [comment]
It was added to Blink when individual transform properties were being implemented.
