### ISSUE TITLE
[css-scrollbars] Resolved value of scrollbar-color

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#3237]
In the initial implementation of `scrollbar-color` in Gecko, I followed the way color properties are handled for gCS, basically according to the following sentence in CSSOM spec:
> A resolved value special case property like color defined in another specification ... The resolved value is the used value.

But it is not clear to me whether this is actually useful at all, and should we make it follow other color properties to be the "special case" for gCS.

Although Gecko currently implements the "special case" way, i.e. `auto` is computed to two colors, I'm happy to make it not the case, because that's actually simpler. Also with the introduction of `light` and `dark`, maybe it makes sense to say `auto` doesn't necessarily mean two colors, so it shouldn't be resolved to two colors?

Anyway, I think this needs to be made clear in the spec one way or the other.

cc @tantek

**Comment by heycam** [comment]
I think it's confusing for getComputedStyle not to return auto for scrollbar-color if that's what the specified value is.  There's no real color value that is the used value here, if you are using native theming.

**Comment by ewilligers** [comment]
`outline-color` and `caret-color` are similar to `scrollbar-color`.

Edge gives `invert` as the initial computed value for `outline-color` (consistent with spec) but Chrome/Firefox/Safari give rgb(...).

**Comment by upsuper** [comment]
That's because gCS returns resolved value, and resolved value of color properties are used value, not computed value.

**Comment by tantek** [comment]
The CSS Scrollbars editor’s draft has an update to the Computed value for scrollbar-color of:

specified keyword or two computed colors

which reflects the above resolution as of 2018-10-23: [https://github.com/w3c/csswg-drafts/issues/3237#issuecomment-432224775](https://github.com/w3c/csswg-drafts/issues/3237#issuecomment-432224775)

That just leaves adding it to the changes section.

(Originally published at: https://tantek.com/2020/023/t3/)
