### ISSUE TITLE
[css-page-3] Whitespace between @page and page selector

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#3239]
In [§ 4.3. @page rule grammar](https://www.w3.org/TR/2018/WD-css-page-3-20181018/#syntax-page-selector) of css-page-3:

```css
@page { ... }
@page :left { ... }
@page :right { ... }
@page LandscapeTable { ... }
@page CompanyLetterHead:first { ... } /*  identifier and pseudo page. */
@page:first { ... }
@page toc, index { ... }
@page :blank:first { ... }
```

I'm wondering if `@page:first { ... }` is correct or not?

**Comment by tabatkins** [comment]
That's probably unintentional, but it's also technically valid. The grammar doesn't explicitly require whitespace between `@page` and the following stuff, so per the standard grammar rules, all that's required is that the tokenizer properly separate things. `@page:first` correctly tokenizes (as AT-KEYWORD DELIM IDENT), so it should parse.

**Comment by tabatkins** [comment]
How do implementations handle this?

**Comment by faceless2** [comment]
* We allow it
* Prince allows it
* VivlioStyle allows it
They are the only three I tested.

**Comment by tabatkins** [comment]
Thanks, I'm gonna go ahead and close this, then, since absent any prose requiring whitespace there, this is definitely valid per CSS Syntax and the [Value Definition Syntax for blocks](https://drafts.csswg.org/css-syntax/#rule-defs).
