### ISSUE TITLE
[selectors-4] Rename :matches() to :is()

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3258]
Breaking this one out from https://github.com/w3c/csswg-drafts/issues/2143#issuecomment-433627117 ; @gibson042 wrote:

> @fantasai We may not live in an ideal world, but I think we do live in one that's close enough to introduce `:is()` and redefine `:matches()` as a deprecated alias of it. What do you think?

The benefits would be: It's much shorter to type, and it makes a clear pairing with :not(), which is its opposite.
The downsides would be: It's already shipping in WebKit as `:matches()`.

Here's the snippet of [prior CSSWG discussion](https://lists.w3.org/Archives/Public/www-style/2018Jul/0027.html), excerpted from [the naming of `:where()`](https://github.com/w3c/csswg-drafts/issues/2143#issuecomment-433627117):

```
  frremy: Why use the :matches() name at all, it's a bad name
  leaverou: We're stuck with it anyway
...
  leaverou: Would you object to :is() if it did what :matches()
            currently does, and :match() is the 0 specificity one?
  fantasai: No, I would not
...
  frremy: :matches() was called that way because the DOM API is called that
  fantasai: Actually, it's very old, original :matches() proposal was from hixie
            a long time ago, before :any()
  <dbaron> I implemented :-moz-any() in Gecko in 2010 in
           https://bugzilla.mozilla.org/show_bug.cgi?id=544834
  ericwilligers: It has been in webkit for a long time
  astearns: How much web content uses :matches?
  iank: Not a lot, looking at usecounter
  ericwilligers: usecounter may be wrong

  Rossen: Is either 2 or 7 an option? they involve changing :matches. webkit people,
          can we do that?
  myles: We could
  myles: We would be moderately interested in updating, but it's low priority
  dino: Why ?
  fantasai: Because a well-named proposal otherwise is :is(), but it is bad if
            it's specificity doesn't match :not()
  fantasai: So we could change :matches() to be the 0 specificity one,
            freeing :is() to do what :matches() does now
...
  [subsequently eliminated :matches() from the list of proposals for #2143,
   so this was not further discussed]
```

I believe other implementations besides WebKit are getting close to shipping `:matches()` so if we're renaming this, we need to do it asap.

**Comment by gibson042** [comment]
We both agree that `:is()` and `:not()` make a better nonzero-specificity pair than `:matches()` and `:not()` and that it would be good to rename `:matches()` to `:is()` if possible.

I also make the further claim that even if `:matches()` _cannot_ be renamed, the semantic value of the `:is()`+`:not()` pair is sufficiently high to introduce `:is()` anyway, and further to recast `:matches()` as a (deprecated) alias thereof (i.e., `:is()` as the preferred spelling and the primary entity in documentation).

**Comment by inoas** [comment]
Deprecating `:matches()` in favour of `:is()` is the way to go. In about 10 years we can talk again about re-using `:matches()` for something else/with different specificity. Until then autoprefixers will take care about injecting dupes of `:is()` as long as there is sufficient user agent base not supporting `:is()`.

**Comment by SelenIT** [comment]
I agree that, since the WebKit's implementation of `:matches()` is now not conforming to the changed spec, it would be better to drop `:matches()` at all (like `:any()`) and rename this functionality with the improved specificity rules to `:is()`. But I suppose that after such a change there should be a signal for the vendors that _this time_ the new definition of `:is()` is _really_ stable and it's safe to implement it. Maybe it's time to defer the less stable Selector features (like `:has()` and Live/Snapshot "profiles") to Level 5 and make the rest of Level 4 features transition to CR as fast as possible?

Also, is the current implementation of `:nth-*-child(... of S)` in WebKit conforming to the current spec? Doesn't it currently have the same problem as the implementation of `:matches()`?

**Comment by ExE-Boss** [comment]
I am in favour of doing this, the only issue is that [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:matches#Browser_compatibility) and [Can&nbsp;I&nbsp;use…](https://caniuse.com/#feat=css-matches-pseudo), this is being implemented and shipping in some browsers.

**Comment by ExE-Boss** [comment]
Also, before I forget, how about considering `:or()` instead? (to better match the `or` operator in programming languages).

**Comment by Loirooriol** [comment]
@ExE-Boss I think `:or()` would be confusing, `foo:or(bar)` seems to mean "`foo` or `bar`" to me, i.e. same as `foo, bar`.

**Comment by ewilligers** [comment]
> I am in favour of doing this, the only issue is that [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/:matches#Browser_compatibility) and [Can&nbsp;I&nbsp;use…](https://caniuse.com/#feat=css-matches-pseudo), this is being implemented and shipping in some browsers.

We don't need to consider implementations behind a flag or vendor prefix. Only Safari is shipping `:matches`.

**Comment by bkardell** [comment]
It strikes me that different things appear to be logical depending on which particular things we are looking at the time.  The name for some functional "do any of these things match" has taken a lot of twists and turns over the years, for various reasons in various contexts.  The DOM APIs today, for example, have `matches()` which tests whether the element matches any of the selectors.  What we are talking about are, kind of pseudos that do that too, so it seems there is some symmetry there as spec'ed today. Maybe that is interesting? In any case, I'm really not sure, and I'm not making any specific case - but given the number of threads on many related things all dealing with naming and desire to flip about - I wonder if It might be somehow worthwhile to consider contexts, history and relationships here?

For example, I've seen what I thought were compelling cases why `:any(...)` makes sense as the name of the pseudo in CSS, but never a proposal that that would have made a good name in the DOM for something that does kinda the same thing.  There, it was pretty much between `.matchesSelector`, `.matches` and `.is`.  The first was deemed too verbose in DOM and woudn''t make a lot of sense in CSS.  The last makes a lot of sense in CSS but in the DOM, on an element, was potentially problematic.

If we are now talking about 3 things - and one is special in that it has no specificity, perhaps having that thing have close symmetry with the single similar DOM method makes some kind of sense?

**Comment by fantasai** [comment]
@bkardell I think symmetry with :not() is more important here than symmetry with the DOM method. Note that all of these can be placed inside the DOM method (which is well-named for what it does anyway). Also the DOM method doesn't have specificity either, so making it different is maybe useful? :)

**Comment by domenic** [comment]
Were any tests updated with this change, or bugs filed against browser implementations? It seems like web platform tests still test for :matches() at the moment (e.g. [matches-nested](https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/css/selectors/matches-nested.html) is one of many files in [this noisy search](https://github.com/web-platform-tests/wpt/search?q=%22%3Amatches%22&unscoped_q=%22%3Amatches%22) that look affected), which makes me wonder how likely browsers are to follow this change.

**Comment by ewilligers** [comment]
Only four tests (those in `css/selectors` by Victoria Su) are relevant. I'll update those when I update Blink, as I did ([CL1](https://chromium-review.googlesource.com/c/chromium/src/+/1296606) [CL2](https://chromium-review.googlesource.com/c/chromium/src/+/1303356)) for the TPAC rename to `:where` that made the name `:is` available.

**Comment by hax** [comment]
Custom element has added the `is` attribute, currently there is no specific syntax for `is` like `.class` or `#id`. If no other background, I worry about that devs could be confused what `a:is(b)` mean (select `<a is=b>`?)

**Comment by yisibl** [comment]
@ewilligers When is Chrome planning to fully implement Selector Level 4?

**Comment by ewilligers** [comment]
> @ewilligers When is Chrome planning to fully implement Selector Level 4?

The semantics for `:is()` and `:where()` may stabilize this month, when https://github.com/w3c/csswg-drafts/issues/3264 is decided. I had not anticipated that their names and semantics would take a year to stabilize.

Chrome should be able to ship `:is()` and `:where()` in Q2 2019 (with WPTs this quarter). These are first priority as people currently use `:-webkit-any()`. `:not()` and `nth-child()` and `nth-last-child()` with general selector lists should be able to ship at the same time.

There are are variety of [open issues](https://github.com/w3c/csswg-drafts/labels/selectors-4) for Selectors Level 4; I decline to estimate when they will be resolved, and when the various new features will ship.
