### ISSUE TITLE
[css-grid] How to serialize the strings in grid-template-areas?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3261]
['grid-template-areas'](https://drafts.csswg.org/css-grid/#grid-template-areas-property) takes several strings as its value, each representing one row of the grid. These strings are then parsed into area labels.

We're basically using strings here as a convenient way to delimit the rows.  They're *not* strings in the traditional sense, where their value contains uninterpreted text; instead, they're just a funny way of writing an ident sequence. Several implementations thus just *store* the property's value as a sequence of area labels, and regenerate the string on demand when needed for serialization purposes.

This means that, in Chrome/WebKit/Edge, a declaration like `grid-template-areas: "  a \9 b ";` is serialized in computed values as just `"a b"`, the simplest string that has the same effect.  Only Firefox preserves the precise string, serializing as `"  a \9 b "`. [Testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6327)

Firefox is technically correct here, in that strings are preserved and serialized exactly as entered in every other case. But I don't think the other browsers are necessarily *wrong* here; these aren't traditional strings, and it's reasonable to "forget" what the original string was in favor of just preserving the meaning. Currently the tests for this feature are written with the assumption of simplification; [here's a Moz bug about the failure](https://bugzilla.mozilla.org/show_bug.cgi?id=1500590) and [a Chrome bug they opened pointing out this violates CSSOM's serialization rules](https://bugs.chromium.org/p/chromium/issues/detail?id=897444).

Should we declare one way or the other correct? Or allow them both?

**Comment by fantasai** [comment]
We should have interop here. I'm OK for the computed value to be simplified, it kinda makes sense to do that. Likely the specified value should not be, though.

**Comment by tabatkins** [comment]
Right, specified values generally keep the exact value entered (maybe modulo some whitespace folding, but that shouldn't apply inside a string like this). I'm mostly just interested in computed value here.

(That said, it looks like Chrome simplifies the specified value too: [updated testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6335). I think we should consider that a bug on Chrome.)

**Comment by mrego** [comment]
> (That said, it looks like Chrome simplifies the specified value too: updated testcase. I think we should consider that a bug on Chrome.)

Yes we have issues with specified values already in `grid-template-columns|rows`: https://bugs.chromium.org/p/chromium/issues/detail?id=716114

So it's not expected similar issues are present in other grid layout properties like `grid-template-areas`.

**Comment by ewilligers** [comment]
Current browsers give the same string value for the specified value that they give for the computed value.

Test page: https://jsfiddle.net/ericwilligers/pw9bkh62/

| Supplied | Firefox specified/computed | Blink/Edge/Safari specified/computed |
|--|--|--|
| '"  a  \t  b  "' | '"  a  \\9   b  "' | '"a b"' |
| '"c\td"' | '"c\\9 d"' | '"c d"' |
| '"first ..."' | '"first ..."' | '"first ."' |

**Comment by mrego** [comment]
Thinking about this a little bit more, maybe not keeping the specified value is an issue for CSS editors.
I remember @therealglazou talked about that problem in the Chromium issue I linked before.

If an user sets:
```
head  head   nav ..... corner
.... ....... nav aside ......
.... content nav aside ......
```
And then this is lost and you get back:
```
head head nav . corner
. . nav aside .
. content nav aside .
```

It might be not a big deal, but it's probably not nice I guess.  :confused:

**Comment by heycam** [comment]
I didn't think of that and I think it's a good point.

**Comment by emilio** [comment]
But that already happens in a bunch of other places... I think that ship is lost already for the general case, but if somebody cares strongly enough...

**Comment by heycam** [comment]
But are there any other properties that encourage visual formatting within the string like grid-template-areas?

**Comment by emilio** [comment]
Maybe not... I don't know :)

**Comment by tabatkins** [comment]
> But are there any other properties that encourage visual formatting within the string like grid-template-areas?

No, this is the only one that does something like this. Every other place we use a string, they're either passing actual textual data, or naming something.

**Comment by fantasai** [comment]
@emilio @heycam Should the discussion here be reopened or should I edit in the resolution from https://github.com/w3c/csswg-drafts/issues/3261#issuecomment-436828363 ?

**Comment by emilio** [comment]
I think given the comments here a bit more discussion may be worth it.

**Comment by fantasai** [comment]
I'm not sure that arguing for consistency with repeat() makes sense here. The rules for unwinding repeat() notations are for getComputedStyle, which returns used values. This question is about specified values.

**Comment by fantasai** [comment]
Anyway, edited in. Reopen if there's something unclear.

**Comment by mrego** [comment]
> I'm not sure that arguing for consistency with repeat() makes sense here. The rules for unwinding repeat() notations are for getComputedStyle, which returns used values. This question is about specified values.

Yeah I was somehow mixing both things.

The problem is that in Chromium/WebKit that for `grid-template-rows: repeat(4, 20px)` we return as specified value `20px 20px 20px 20px` ([bug #716114](https://bugs.chromium.org/p/chromium/issues/detail?id=716114)) and also as computed value (I'm sorry but I haven't investigated this well enough to know how complex/easy it would be to fix it).
However Firefox only does it for the computed value, and returns `repeat(4, 20px)` as specified value.

So one question could be if we should we change `grid-template-columns|rows` to be consistent to `grid-template-areas` regarding specified values being the same than computed values?

**Comment by fantasai** [comment]
@mrego I think the computed value definitely needs to maintain the repetition--for keyword repeat values like auto-fit and auto-fill it's certainly required because the resolved repeat value depends on layout. (Note that getComputedStyle does not return the computed value of grid-template-rows, it returns the used value.)
