### ISSUE TITLE
[css-scroll-snap] Typo in section 9.1. "Changes Since 14 December 2018 CR" title

### ISSUE THREAD

**Issue by Chealer** [w3c/csswg-drafts#3269]
In the title of [section 9.1](https://www.w3.org/TR/css-scroll-snap-1/#changes-20171214), "2018" should read "2017".

**Comment by fantasai** [comment]
Thanks! I had fixed it in the Editor's Draft, but there was another similar error just above, so both should be fixed and will appear in the next publication. :)

**Comment by Chealer** [comment]
Thanks to you
