### ISSUE TITLE
[css-values][css-color] apparent contradiction

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3270]
(found by @TalbotG)

[css-values-3 (and 4)](https://www.w3.org/TR/css-values-3/#numeric-types) say that
> Properties may restrict numeric values to some range. If the value is outside the allowed range, the declaration is invalid and must be ignored.

However, there is at least one exception: the [`rgb()`](https://drafts.csswg.org/css-color-3/#annotation_rgb-color) function, which says:
> Values outside the device gamut should be clipped or mapped into the gamut when the gamut is known

and gives examples of values below 0 or above 255.

So, since there are some cases of properties doing restriction on the range other than at parsing time, we should probably change the sentence in css-values to something like this:

> Properties may restrict numeric values to some range. Unless specified otherwise, if the value is outside the allowed range, the declaration is invalid and must be ignored.

This makes it clear which requirement takes precedence instead of just having a contradiction.

**Comment by TalbotG** [comment]
Also:
> out-of-range values [inside calc() function] do not cause the declaration to become invalid. However, the value resulting from an expression must be clamped to the range allowed in the target context.

[8.1.4. Range Checking [inside calc() function]](https://www.w3.org/TR/css-values-3/#calc-range)

**Comment by Crissov** [comment]
🤔 Inside `rgb()`, they are not numeric property values but function arguments.
