### ISSUE TITLE
[css-text-decor-4] Are text decorations visual overflow or layout overflow?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3272]
Neither the level 3 spec nor the level 4 spec mentions the word "overflow."

Now that we can place underlines in arbitrary places, we need to decide if they cause scrollbars or not.

It's easier to implement if they don't. But underlines do provide semantic meaning to text.

**Comment by fantasai** [comment]
They should be ink overflow, just like glyph bounds that are beyond the ascent/descent.
