### ISSUE TITLE
[css-grid] Rename "min-size contribution"

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3277]
The term "min-size contribution" is confusingly similar to "min-content contribution". The two terms are also *close* in meaning, but quite distinct in details, making the whole thing more confusing. We should come up with a better, more distinct name.

The current name was chosen because it's the contribution you get from paying attention to the min-width/height property (aka "min-size" property) rather than width/height like min-content contribution uses. It also reflects the interesting interaction that `min-width:auto` has with fixed grid tracks, where the size gets clamped to the sum of the track sizes it spans.

@fantasai suggests "minimum contribution"; it's still a "contribution" in spirit, as it's largely calculated the same way as the other contributions. But the term "minimum" is grammatically distinct from "min-content", in a way that "min-size" isn't.

I think that's an improvement, but I'm not sure it's good enough yet to be worth the change. Need some thought on this.

**Comment by fantasai** [comment]
Made the switch. Reopen with suggestion if you want something different.
