### ISSUE TITLE
[mediaqueries-5] Clarification on prefers-color-scheme issues

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/csswg-drafts#3278]
[Whilst working on trying to implement this for Firefox ](https://bugzilla.mozilla.org/show_bug.cgi?id=1494034#c7) I and @emilio noticed some ambiguity with [the spec text](
https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme).

> The prefers-color-scheme media feature is used to detect if the user has requested the system use a light or dark color theme.

1. Does it really matter if this is a system or user agent preference? For example in non supporting operating systems Firefox could choose to pass `light` and `dark` when the user has enabled these themes and `no-preference` when they haven't.

2. `(prefers-color-scheme)` never appears to match, however shouldn't it match whenever the user has a preference? Especially given the boolean context statement.

3. We are at slight risk of sites never supporting no-prefererence given safari is only using `light`/`dark` and always returning true for `no-preference`.

/cc @grorg @emilio

**Comment by emilio** [comment]
cc @smfr, is WebKit's behavior intentional? If so, knowing the reasoning would be helpful to know what to implement.

**Comment by xeenon** [comment]
Apple's implementation matches `light` or `dark` always when the system / app / view UI is running in light or dark mode — it is a binary choice on macOS — the user / app / view / system has no choice but to be in one of the two modes.

In Safari `no-preference` is basically treated like a hypothetical `prefers-color-scheme: either` — kind of like what you suggest for `(prefers-color-scheme)`. 

Given that `(prefers-color-scheme)` does not read well or convey much intent, we decided to make it invalid. But again, we can change it — and it would always be `true` for us. Conversely `no-preference` would always be `false` for us.

**Comment by xeenon** [comment]
I filed a bug for WebKit here: https://bugs.webkit.org/show_bug.cgi?id=191654

**Comment by grorg** [comment]
Typically we try to make the "empty" form have a falsey value for these `prefers-` queries.

**Comment by grorg** [comment]
I agree that's a bit weird for this query, because it isn't clear if no preference is explicit or not. But the no-preference value is supposed to be false. @xeenon has already fixed the bug in WebKit.

As for the other points:

1. Agreed. It could be the UA setting.
2. Yes, I think `(prefers-color-scheme)` should match if the user has explicitly selected a scheme. I don't know why you'd want to author that though.

**Comment by grorg** [comment]
I'll update the specification to clarify point 1. What are people's opinions on 2? Should no-preference mean "I don't care" or should it mean "only if i haven't chosen a scheme"?

**Comment by emilio** [comment]
Thanks @grorg, that all makes sense!

I (but note I'm not an expert in this area) personally think `no-preference` should be exclusive to any of the other values matching (that is, you should never get into a state where `(prefers-color-scheme: {light, dark})` and `(prefers-color-scheme: no-preference)` apply at the same time. Also, it probably makes sense to require at least one of the values to match over all?

I think I'd be confused as an author if that was not the case, but again I'm not author nor an expert in this area, so my opinion probably doesn't have that much value :-)

**Comment by jonathanKingston** [comment]
> I (but note I'm not an expert in this area) personally think no-preference should be exclusive to any of the other values matching (that is, you should never get into a state where (prefers-color-scheme: {light, dark}) and (prefers-color-scheme: no-preference) apply at the same time. Also, it probably makes sense to require at least one of the values to match over all?

That seems to be my understanding of how this should work also. I think it is fair that Safari for example might decide never to match for `no-preference` as they are always `light` or `dark`.

As for Firefox, for the short term `no-preference` might be used on platforms where we don't have an OS setting. Firefox likely will be using `no-preference` for users who don't want to convey their preference also like Tor users.

My views are:
- `no-preference` should never match when `light` or `dark` does.
- `(prefers-color-scheme)` should match if `light` or `dark` matches but not match when `no-preference` matches.

**Comment by danosek** [comment]
Here are my thoughts from **designer's perspective**. I know you're there is a gray area regarding definition of `@media (prefers-color-scheme: no-preference)` and `@media (prefers-color-scheme)` but let me explain the bigger picture with [this example](https://codepen.io/danoshekk/full/XoWOrZ).

I the near future (I hope), there should be no distinction between light and dark theme, as there is no distinction between user's device screen size. We should only to adapt the content and its visual properties to match user's device (whether it's a size or theme preference to something else) with media queries.

The thing is, you should only clearly define default design when there is no support for `prefers-color-scheme`. In the end, this design is just one of the themes - light or dark. It only depends whether your default design should be light or dark. That's it :)

**Comment by lilles** [comment]
Having the keywords being mutually exclusive makes sense to me as well. IIRC, in Mojave you cannot have no-preference. If that's the case, authors will probably not end up having three different designs, but have either the light or the dark being the default, like:

```
@media (prefers-color-scheme: dark), (prefers-color-scheme: no-preference) {}
@media (prefers-color-scheme: light) {}
```

I have not checked with ChromeOS/Android if they will have a no-preference, but privacy/finger-printing was brought up as an issue on blink-dev (like mentioned above for Firefox as well).

**Comment by dannote** [comment]
As for now "light" and "dark" actually mean "as is" and "a specially crafted dark mode" respectively and I can't imagine what will "no-preference" mean in these terms. Maybe we should keep it binary?

**Comment by freund17** [comment]
I imagine this feature like this:

## As a web developer...

...you are presented with 4 cases you might want to cover:

```css
@media (prefers-color-scheme: dark)
```

If your app has a dark-mode, use it.

```css
@media (prefers-color-scheme: light)
```

If your app has a light-mode, use it.

```css
@media (prefers-color-scheme: no-preference)
```

Use whatever mode you, as a developer/designer, thought of as the more suited for your app.
For an image galary app this might mean "dark".
For a text processing app this might mean "light".
Whatever you think of as the "better" mode for your app.

```css
@media (prefers-color-scheme)
```

Simply means that the webbrowser at hand supports communicating it's users color-scheme preference.
If it doesn't, you will probably want to use the same as if "no-preference" were submitted.
However you might want to use this information to conditionally show/hide manual theme-selection buttons, when the same information can be provided via the users browser.

## In a supporting webbrowser...

...I imagine there to be the following settings (maybe with per-domain overrides):

```
System
```

Forward the preferred color-scheme by the OS.
If the OS doesn't have a concept of color-schemes, set "no-preference".


```
No Preference
```

Let the website decide what is best.

```
Light
```

Send "light" as your preference.

```
Dark
```

Send "dark" as your preference.


## Closing thoughts

Remember, that you, as a developer, are always able to override the "prefers-color-scheme"-value.
For example, if the user explicitly selects a theme in your app.

This feature - at least in my eyes - is most useful to

a) get the fist time visitor directly into his favourite theme
b) have a website responding to the system color-scheme (which might depend on the time of day) and have it in sync with all other applications on the user's device

**Comment by GamePad64** [comment]
So, I think, that this media query should support not only light/date modes, but also high-contrast and so on (using -ms-high-contrast as a reference). So, it should be extensible for future use.

**Comment by MatsPalmgren** [comment]
I think multiple UAs will soon ship this feature, so it would be good to have a decision on this.

CC @tabatkins

**Comment by emilio** [comment]
So concrete questions:

 * What should the feature evaluate in the boolean context (that is, what should `@media (supports-color-scheme)` evaluate to?
    * Chromium implements: `(prefers-color-scheme)` == `not (prefers-color-scheme: no-preference)`.
    * Safari and @MatsPalmgren's patch to Firefox always evaluate `(prefers-color-scheme)`.
 * Should UAs implicitly change this for printing and such? I tend to think they don't, but I don't have a massively strong preference.

**Comment by emilio** [comment]
>     * Safari and @MatsPalmgren's patch to Firefox always evaluate `(prefers-color-scheme)`.

Though note that for Safari `(prefers-colors-scheme) == not (prefers-color-scheme: no-preference)` also holds, since they don't have `no-preference`.

**Comment by xeenon** [comment]
WebKit matches `light` when printing.

**Comment by grorg** [comment]
I'll update the spec.

**Comment by emilio** [comment]
Thanks @grorg!

**Comment by sbrl** [comment]
As a user, I want to be able to choose whether I prefer a light or dark theme in my browser, rather than go hunting through my operating system's settings (which I've done, and I can't seem to find anything - I'm using XFCE4 on Linux).

As the very least, I'd like a button that takes me to the right place in my desktop environment's settings.

**Comment by smfr** [comment]
That sounds like a feature request for your browser vendor.

**Comment by grorg** [comment]
I finally got around to clarifying the specification, particularly that the preference can come from the system or the user agent. We resolved that the boolean expression, while confusing and/or useless, should remain as is to be consistent with other queries.

In my testing, it seems Safari + Chrome + Firefox all agree on `@media (prefers-color-scheme)`.
