### ISSUE TITLE
[css-contain] contain: style does not seem useful.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3280]
This is about https://drafts.csswg.org/css-contain/#containment-style.

I wonder what's the use-case for this. In particular, the following optimization that the spec describes:

> Whenever a property is changed on a descendant of the containing element, calculating what part of the DOM tree is "dirtied" and might need to have its style recalculated can stop at the containing element.

Is just not true, since you need to compute the style of ancestors in order to inherit from them.

It's also hard to envision any kind of style-recalc optimization, since any style change may make that element become or stop-being style-contained, and you need to handle stuff like `contain: inherit`.

Given:

 * contain: style is broken on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=855798
 * The complexity of implementing it correctly in Firefox is high.
 * There's no potential optimization to be had out of this (if only, you could optimize counter updates, but that benefit is IMO overruled by the complexity of "unscoping" the counters when `contain: style` stops applying dynamically, and the fact that counters are uncommon).

I wonder what's the point of implementing it.

**Comment by emilio** [comment]
cc @dholbert

**Comment by emilio** [comment]
In particular, by definition, optimizing style recalc based on a CSS property value is just impossible.

cc @frivoal as well.

**Comment by mrego** [comment]
Note that in Chromium there are several bugs related to `contain: style`:
* https://bugs.chromium.org/p/chromium/issues/detail?id=855798 (already linked by @emilio)
* https://bugs.chromium.org/p/chromium/issues/detail?id=869296
* https://bugs.chromium.org/p/chromium/issues/detail?id=882383
* https://bugs.chromium.org/p/chromium/issues/detail?id=882385

**Comment by ewilligers** [comment]
My understanding was that the motivation was counters.


> In particular, the following optimization that the spec describes:
> 

> > Whenever a property is changed on a descendant of the containing element, calculating what part of the DOM tree is "dirtied" and might need to have its style recalculated can stop at the containing element.


> 
> Is just not true, since you need to compute the style of ancestors in order to inherit from them.
> 

The spec is not talking about computing the style of ancestors.

Assume the ancestor has `contain: style`. If a descendant is added or removed, or has a style change to introduce or remove a counter increment, you don't need to update counters in the ancestor's subsequent siblings (or any element outside the ancestor subtree).

**Comment by emilio** [comment]
> The spec is not talking about computing the style of ancestors.

Well, that's what I read given "might need to have its style recalculated can stop at the containing element". If it's not talking about style recalc then it should not mention style recalc and should be reworded.

In any case I understand that the only feasible optimization here is counter updates (see the first comment where I mention "if only, you could optimize counter updates"). I just don't think I agree adding a feature like this is useful if this is the only optimization you can get out of it. Are counters in general (and dynamically inserted counter increments / resets in particular) used enough / enough of a bottleneck to justify the complexity of this? My guess is not.

**Comment by tabatkins** [comment]
While counters are the primary use-case here, any further features we develop where one property defines a (global) name and another property references it will benefit similarly. 

`contain: style` isn't necessarily meant as a perf win, but as an understandability win when composing things, as you don't have to worry about colliding values. If you style-isolate your component, you can increment counters freely within it, safe in the knowledge that you won't accidentally increment a counter from the outside document, or even create a counter scope that'll be visible in siblings.

> Is just not true, since you need to compute the style of ancestors in order to inherit from them.

The text you quoted is *explicitly* talking about dirty-bit propagation, *not* a more generic "there's no style connection between the inside and outside". As far as I can tell, this objection is thus invalid?

**Comment by emilio** [comment]
> The text you quoted is explicitly talking about dirty-bit propagation, not a more generic "there's no style connection between the inside and outside". As far as I can tell, this objection is thus invalid?

I'm not sure which dirty-bit propagation you're talking about, can you elaborate? But when something in the DOM changes you may need to flag ancestors / siblings for recalc (due to `:empty` / `:nth-child` / etc).

**Comment by mrego** [comment]
@frivoal the [spec stills says](https://drafts.csswg.org/css-contain/#containment-style):
> 1. Whenever a property is changed on a descendant of the containing element, calculating what part of the DOM tree is "dirtied" and might need to have its style recalculated can stop at the containing element.

This doesn't talk about conuters and quotes, which are the only things affected by style contaiment. So I guess we should remove/reword this sentence.

**Comment by frivoal** [comment]
We stopped including style containment in strict containment, and marked it at risk, but haven't changed how it works, so it's expected that this sentence would be unchanged. If there's something wrong with it, it feels like a separate issue.

But that sentence doesn't seem wrong to me. If you're changing a property, such as changing the `content` property from `none` to `open-quote`on a descendant of the containing element, without style containment, you have to check on the tree outside the containing element if there are other uses of `content` that generate quotes, as they may have to be recalculated. With style containment on, you don't. So that sentence seems correct. You don't this so?

**Comment by mrego** [comment]
I understand the sentence as something more generic "whenever a property is changed on a descendant", it seems unrelated to counters or quotes but a more general comment, maybe it'd be nice to talk specifically about counters and quotes in that sentence.
That's why it caused some confusion to me.

Anyway we can open a different issue to modify that sentence if you feel like that, feel free to close this one.
