### ISSUE TITLE
[selectors] Add a "case-sensitive" attribute-matcher flag

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3282]
A while back we added a "case-insensitive" flag for attribute-matching, to help model how a number of HTML attributes matched their value case-insensitively.

However, per <https://github.com/whatwg/html/issues/4158>, the `type` attribute, at least, *always* matches case-insensitively, no matter whether you provide the flag or not. (This is a legacy weirdness thing, not an intentional design.)  This, then, makes it *actually impossible* to implement the `ol` styling rules in CSS; they can only be applied magically or via JS examining the actual value of the attribute.

Perhaps we could add a "case-sensitive" flag that forces matching to be done case-sensitively, even in cases like this where it's case-insensitive by default? @annevk suggests a `c`, which is as good as anything else.

**Comment by Loirooriol** [comment]
Dupe of #2101?

**Comment by tabatkins** [comment]
Indeed, thanks! Closing this in favor of discussion over there.
