### ISSUE TITLE
[css-images] image-rendering should support SVG 1.1 values

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3283]
[SVG 1.1](https://www.w3.org/TR/SVG11/painting.html#ImageRenderingProperty)'s image-rendering allows
auto | optimizeSpeed | optimizeQuality

[CSS Images](https://drafts.csswg.org/css-images/#the-image-rendering) currently allows
auto | smooth | high-quality | crisp-edges | pixelated

Safari 11.1 supports
auto | crisp-edges | pixelated | optimizeSpeed | optimizeQuality

Blink supports
auto | pixelated | -webkit-optimize-contrast
-webkit-optimize-contrast is a non-standard naming for crisp-edges
There is also [non-working](https://crbug.com/901669) code for optimizeSpeed | optimizeQuality

Firefox supports
auto | crisp-edges | optimizespeed | optimizequality

Edge does not support the property ([test page](https://jsfiddle.net/ericwilligers/8ayzskhn/)).

These results suggest:

- high-quality should be renamed to optimizeQuality
- optimizeSpeed should be added
- Implementations should be asked if they intend to support smooth

**Comment by ewilligers** [comment]
I missed

> This property previously accepted the values optimizeSpeed and optimizeQuality. These are now deprecated; a user agent must accept them as valid values but must treat them as having the same behavior as pixelated and auto respectively, and authors must not use them.

Why doesn't optimizeQuality map to high-quality?

**Comment by tabatkins** [comment]
`high-quality` implies more than the old `optimizequality` did; it's something that should be used sparingly on a page (like `will-change`, it implies expensive things on the part of the UA). `auto` is the correct behavior for `optimizequality`.

Also, at the time I wrote that paragraph `high-quality` didn't exist. But mainly the first thing. ^_^

**Comment by ewilligers** [comment]
>  `auto` is the correct behavior for `optimizequality`.

Why not `smooth`?

> **[optimizeQuality](https://www.w3.org/TR/SVG11/painting.html#ImageRenderingProperty)**
> Indicates that the user agent shall emphasize quality over rendering speed. The user agent shall employ a resampling algorithm at least as good as bilinear resampling.
> 

> **[smooth](https://drafts.csswg.org/css-images/#the-image-rendering)**
> The image should be scaled with an algorithm that maximizes the appearance of the image. In particular, scaling algorithms that "smooth" colors are acceptable, such as bilinear interpolation. This is intended for images such as photos.

**Comment by tabatkins** [comment]
Ah, now *that's* purely because we didn't have `smooth` at the time (`auto` served that purpose). I'd be fine with changing that.
