### ISSUE TITLE
var function inside attribute selectors

### ISSUE THREAD

**Issue by bertdida** [w3c/csswg-drafts#3284]
I propose to allow var function inside attribute selectors, something like `[attribute=var(--variable)]`.

**Comment by tabatkins** [comment]
Unfortunately, this isn't possible. Variables draw their values from custom properties, and so you need to have some element to get those from. But selectors obviously don't have an element associated with them; they *select* the elements! So, you can't use a var() like this.

That said, [`env()`](https://drafts.csswg.org/css-env/) will allow this once custom environment variables are defined; they *aren't* associated with any element (they're global values instead).
