### ISSUE TITLE
[css-syntax] The tokenizer input should probably be a stream of scalar values, not codepoints

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3307]
In <https://github.com/WICG/construct-stylesheets/pull/61#discussion_r232381468>, Boris points out that the Syntax spec specifies that the input to the tokenizer is a stream of code points, and wonders if I actually mean scalar values there. (That is, all codepoints except surrogates.)

I think at the time I wrote this, USVString didn't yet exist, and the distinction between the two wasn't really present in specs. But if I were writing it today, I'm pretty sure I'd use scalar values.

In particular, note that [you can't produce a surrogate code point from an escape](https://drafts.csswg.org/css-syntax/#consume-escaped-code-point), which suggests that I assumed *no* surrogates would show up in the stream.

So, I think I should switch the spec over to referring to scalar values, and have a conversion step for going from codepoints to scalars (probably just converting non-scalars to U+FFFD? I'll look at impls and see what's up).

[Test case](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/6360):
```html
<!DOCTYPE html>
<style></style>
<script>
document.querySelector("style").textContent = ".fo\ud800o { color: blue; }";
w([...document.styleSheets[0].cssRules[0].selectorText].map(x=>x.codePointAt(0).toString(16)));
</script>
```

Looks like Chrome retains the character as U+D800, while Firefox censors it to U+FFFD. Perhaps this is just related to which definition each uses for CSSOMString?

**Comment by tabatkins** [comment]
(I can't attend this week's meeting, so consider this an Agenda+ for *next* week, unless someone feels like presenting it based on the below.)

Details:

* per <https://drafts.csswg.org/css-syntax/#input-byte-stream>, the decode operation is used to turn bytes into codepoints; this algorithm will only return scalar values (never surrogate codepoints)
* per <https://drafts.csswg.org/css-syntax/#consume-escaped-code-point>, using a codepoint escape will always produce scalar values (never surrogate codepoints)
* the only way, currently, to produce a surrogate codepoint is by directly assigning a DOMString with one in it via an OM operation
* Firefox doesn't do this; presumably because they use USVString for their CSSOMString, assigning a string with a surrogate in it will replace the surrogate with U+FFFD.
* Syntax already has *some* codepoint filtering built in: <https://drafts.csswg.org/css-syntax/#input-preprocessing> replaces newlines with a canonical newline, and replaces NULL with U+FFFD (same as trying to escape a null).

So, my proposal is that we add another codepoint-filtering rule that turns surrogates into U+FFFD, effectively meaning that all the algorithms take streams of scalar values. This will match Firefox's behavior, and overall harmonize the various entry points with each other about which codepoints can be used.

**Comment by SimonSapin** [comment]
> Perhaps this is just related to which definition each uses for CSSOMString?

Yes, exactly. Firefox (since 57) treats string in CSSOM effectively as `USVString`. I proposed changing the CSSOM spec to use `USVString` in https://github.com/w3c/csswg-drafts/issues/1217, but other implementations were opposed. This is why we introduced `CSSOMString`: to allow each implementation to pick either.

I’m a bit surprised that maintainers of Blink and EdgeHTML and WebKit have changed their mind since last year, but if they have I’m glad we can simplify the spec.

@tabatkins When do this in the tokenizer algorithm rather than removing `CSSOMString` and using `USVString` in CSSOM?

**Comment by SimonSapin** [comment]
s/When/Why/

**Comment by tabatkins** [comment]
> Why do this in the tokenizer algorithm rather than removing CSSOMString and using USVString in CSSOM?

Because it's weird to have the tokenizer algorithm technically allow it in this one case; I'm aligning all the entry points to have the same set of allowed codepoints.

That said, you're right that this change makes it so that we can also just change CSSOM to use USVString, I think.

**Comment by SimonSapin** [comment]
What one case do you mean and how is it allowed? If "the input stream" (before substitution/processing) is defined as scalar values rather than code points, the surrogate case just does not exist in css-syntax. Then it up to users of that entry point (rather than the bytes based one) to provide scalar values. In DOM/CSSOM, this happens to be USVString. (I guess we’d need some more prose in HTML for `<style>` and in css-style-attr.)

**Comment by SimonSapin** [comment]
CC @bfgeek and @litherum, who opposed a similar change previously.

**Comment by tabatkins** [comment]
Chatted with @bfgeek today and traced our code a bit. The objection to USVString in CSSOM is separate from the acceptance of this filtering in the CSS parser, so we're fine with the spec change here in Syntax, but not to simplifying CSSOMString in CSSOM.

Basically, IDL's requirements for USVString are strict, and require codepoint filtering immediately upon the value entering the system. Switching the OM to USVString would mean a *separate* pass over each string, to replace surrogates, then the parser would run over the string and do its own substitutions as it worked.

On the other hand, just adding surrogates to the list of filtered codepoints can be done at the same time as the other filterings, on-demand during parsing, so no additional passes over the strings (just a bit more comparisons).

So yes, while the *author-observable effects* of parser-filtering or just switching to USVString are identical, the internal effects are different unless we do some custom contortions of our IDL code, which we'd rather not do, at least not right now.
