### ISSUE TITLE
[cssom] LinkStyle.sheet to return CSSStyleSheet instead of StyleSheet?

### ISSUE THREAD

**Issue by saschanaz** [w3c/csswg-drafts#3311]
https://drafts.csswg.org/cssom/#the-linkstyle-interface

>The associated CSS style sheet of a node is the CSS style sheet in the list of document or shadow root CSS style sheets of which the owner node implements the LinkStyle interface.
>```webidl
>interface mixin LinkStyle {
>  readonly attribute StyleSheet? sheet;
>};
>```
>The sheet attribute must return the associated CSS style sheet for the node or null if there is no associated CSS style sheet.

The prose says `sheet` returns a CSS style sheet but the IDL says it returns a superclass instance (`StyleSheet`). Can we fix the IDL to return `CSSStyleSheet`?

**Comment by tabatkins** [comment]
While the IDL is technically correct, I see from your linked issue how it can cause some problems.  I agree that we should be treating the `StyleSheet`/`CSSStyleSheet` distinction as a legacy mistake; the `.type` attribute is already fixed to always return `"type/css"`, after all.

I'm fine with this change. Pinging @emilio.

**Comment by upsuper** [comment]
Maybe we should just merge the two types and make one an alias of the other?

**Comment by emilio** [comment]
> Maybe we should just merge the two types and make one an alias of the other?

Well, that's observable I guess, since the prototypes would change, so that's a bit riskier... But yeah changing the IDL here should be harmless.

**Comment by tabatkins** [comment]
Yeah, merging has side effects. *Probably* fine, but there's little value in doing so, so eh.

**Comment by tabatkins** [comment]
(Feel free to merge #3313 yourself, @emilio, or Agenda+ it if you feel like you want review.)

**Comment by upsuper** [comment]
The main reason I brought merging is that, it's not clear what should be returned from `StyleSheetList.item` and `StyleSheet.parentStyleSheet`. If we admit that there's going to be only one type of `StyleSheet`, shouldn't they all return `CSSStyleSheet`?

**Comment by tabatkins** [comment]
Yes, presumably we should update all the IDL to return CSSStyleSheet instead.
