### ISSUE TITLE
[css-break-3] Should 'break-before' / 'break-after' have an 'always' value?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3318]
We decided not to have an 'always' value for break-* because it wasn't clear to us whether this should create a break within the nearest fragmentation context, or all the way up to the top level. (Imagine a multicol inside paged media: does 'always' create a column break or a page break?)

However, it looks like IE implements an 'always' value, which has fairly high usage: https://developer.microsoft.com/en-us/microsoft-edge/platform/usage/css/break-before/
We should maybe figure out what it does and spec that.

**Comment by fantasai** [comment]
OK, I ran some tests. 'break-before: always' in Edge triggers a page break, but only when printing. I don't think this makes particularly much sense, though.

We have the following options:

- A) We define 'break-before: always' to trigger a break at the innermost fragmentation context
- B) We define 'break-before: always' to trigger a break through all available fragmentation contexts.
- C) Edge removes 'break-before: always' from its implementation.
- D) We define 'break-before: always' to be an alias of 'break-before: page'.

My preference would be A if possible, since I suspect it's going to be the most useful behavior. On pages without multicol, the behavior would be the same as Edge has currently. B) Would be more compatible with what Edge is doing right now on pages with multicol. It would additionally trigger breaks in multicol on screen, but pages depending on that are broken already since those breaks already trigger in print. C) seems acceptable, but the usage numbers seem a little high on Edge so it could be problematic. D) is my least favorite option.

**Comment by kojiishi** [comment]
Noticed [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before) says:
> `always` ... This is an alias of `page`, and has been kept to facilitate the transition from page-break-after, which is a subset of this property.

**Comment by fantasai** [comment]
Edited in https://github.com/w3c/csswg-drafts/commit/7886989108b874f85db313f061462ccfeed6a76a
