### ISSUE TITLE
[css-flexbox][css-align] baseline-alignment fallback: flex-start vs start/self-start

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#332]
When items can't be baseline-aligned, they are fallback-aligned. In flexbox, this falls back to `flex-start`. In the alignment spec, it falls back to `start`. Both of these seem wrong. It should fall back to `self-start` (or its equivalent), which is the direction that things appear to align to if you have a mix of content with different amounts of text.

(`last-baseline` should of course align to `self-end`).

https://drafts.csswg.org/css-flexbox/#valdef-align-items-baseline
https://drafts.csswg.org/css-align/#valdef-justify-content-baseline

**Comment by FremyCompany** [comment]
@fantasai This issue could be safely closed now given how we resolved and #197 and #373, right?

**Comment by fantasai** [comment]
No, this is a separate issue.

**Comment by tabatkins** [comment]
Now that everything can be baseline-aligned (we just synthesize baselines as necessary), this issue is moot.
