### ISSUE TITLE
[css-???] Standardise a binary representation for CSS

### ISSUE THREAD

**Issue by ExE-Boss** [w3c/csswg-drafts#3334]
JavaFX uses a binary stylesheet format to allow faster loading times when loading styles.

[RFC&nbsp;7049](https://tools.ietf.org/html/rfc7049) defines a binary equivalent to JSON and WebAssembly is working to be the binary counterpart to JavaScript.

I’d like to see the CSSWG standarsise a binary format for CSS to complete the above mentioned binary representations.

## Pros:
- Faster loading and parse times (as a binary format doesn’t require tokenisation, it’s easier to parse for low memory systems)

**Comment by plinss** [comment]
See https://github.com/EXIficient/exificient-for-css

Hasn't been much uptake.

**Comment by ExE-Boss** [comment]
The issue with using EXIficient for&nbsp;CSS is&nbsp;that it’s&nbsp;not as&nbsp;efficient as&nbsp;it&nbsp;could&nbsp;be, given that EXIficient is&nbsp;primarily a&nbsp;binary serialisation format for&nbsp;XML, and&nbsp;therefore it&nbsp;needs to&nbsp;be&nbsp;converted from the&nbsp;XML&nbsp;DOM to&nbsp;CSSOM before it&nbsp;can be&nbsp;used.

**Comment by emilio** [comment]
I guess a good thing to pitch this would be to prove that CSS parsing / downloading is a significant enough bottleneck for web applications (might or might not be). That's the premise that would justify adding such thing.

The next thing would be to propose a format that is both extensible, and proven more compact / efficient than CSS, and finally design a way to progressively enhance it, that is, that authors could specify a css file as a fallback for browsers not supporting the new thing or what not.

**Comment by dbaron** [comment]
@darobin might have an opinion here.

**Comment by svgeesus** [comment]
At least for XML, EXI is best with a tightly constrained vocabulary in terms of content models, attributes, and attribute values. The efficiency drops as soon as new values, attributes, or elements are added.

I guess the same would be true for a binary representation of a CSS stylesheet; it would need a complete list of property names, and the list of property values for each (plus at rules). Given the rate at which CSS changes, this would seem to call for _weekly_ updates to the binary format.

A binary serialization of CSSOM could be interesting, but includes all the properties and values on each node. Selectors plus the cascade and inheritance are effectively a compression step, compared to explicitly listing for all nodes.

**Comment by litherum** [comment]
This proposal is for a performance optimization. I’d like to see a characterization of the performance improvement numbers before we pursue this.
