### ISSUE TITLE
[css-values] Expand “UA” abbreviation

### ISSUE THREAD

**Issue by j9t** [w3c/csswg-drafts#3337]
Minor issue, just a suggestion: https://www.w3.org/TR/2018/WD-css-values-4-20181010/ speaks about “UAs” much of the document (starting in §2.3) without expanding the term; if anything then only in §6 and later is there mention of “user agents.” I suggest that for such abbreviations, the first mention is spelled out alongside its abbreviation, as with “user agents (UAs)” or such.

The suggestion is based on the idea that we’re well familiar with these abbreviations, but not everyone might.

**Comment by fantasai** [comment]
This makes sense, but, it seems like it'd be really hard to make sure we got it right for every spec, given UA doesn't appear in any of the early sections/boilerplate.

We do define the term in the CSS2 intro/glossary at
  https://www.w3.org/TR/CSS2/conform.html#user-agent

And there is also a W3C Glossary, which should probably also define it
    https://www.w3.org/2001/12/Glossary
But unfortunately it's not maintained so I filed an issue about that against the AB here:
    https://github.com/w3c/AB-memberonly/issues/107

We also have an outstanding issue about incorporating CSS2 intro materials into the CSS Snapshot at https://www.w3.org/TR/CSS/ , which we should also get around to.

That still doesn't help much with discoverability though... :/

**Comment by fantasai** [comment]
@j9t OK, I've added a glossary to the CSS Snapshot at https://drafts.csswg.org/css-2022/#intro :) This will give us a place to cross-link “UA” to throughout all of our specs.

Thanks for filing this issue, we probably wouldn't have gotten around to it without your prompting.

**Comment by j9t** [comment]
Nice—thanks for looking into this!
