### ISSUE TITLE
[css-grid] comma in repeat()

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#334]
In light of recent discussions on commas inside functional notations (issue #266, https://wiki.csswg.org/ideas/functional-notation#general-principles) ... shouldn't the comma in `repeat()` be dropped?

**Comment by FremyCompany** [comment]
It could be confusing though because repeat(3 0) would be a valid way to create 3 empty tracks.

**Comment by rachelandrew** [comment]
I think it would be very confusing. The comma is useful here and I see no benefit from removing it.

**Comment by fantasai** [comment]
The benefit would be to have the contents of the functional notation follow the syntax conventions of CSS property values.

**Comment by FremyCompany** [comment]
An option would be to do ```repeat(3x [line] 100px)``` or ```repeat(3: [line] 100px)```

**Comment by FremyCompany** [comment]
Actually the first one isn't a good idea, 3x looks like 3px where you forgot the p.

**Comment by svillar** [comment]
I also find the syntax without the comma very confusing. And in any case the WG is not proposing to change anything in grid, nor even minmax() which is considered a math-y function.

**Comment by tabatkins** [comment]
@fantasai  and I have talked about this, and agreed not to change Grid in this respect.
