### ISSUE TITLE
[fill-stroke] [filter-effects] [css-color] percentage opacity

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3342]
The opacity properties define their syntax using [`<alpha>`](https://www.w3.org/TR/css-color/#typedef-alpha-value).

In [CSS Color 3](https://drafts.csswg.org/css-color-3/#transparency), alpha only accepted number values.

In CSS Color 4, alpha accepts percentages in addition to numbers.
 
Blink/Edge/Firefox/Safari do not accept percentages for any of the opacity properties - [test page](https://jsfiddle.net/ericwilligers/zmgy8735/).

Blink and Firefox do accept percentage alpha in rgba() color values.

Was the change to support percentages intended only for color functions, with opacity properties affected accidentally, or are browsers intending to support percentages in *-opacity?

Affected properties:
- [opacity](https://drafts.csswg.org/css-color/#propdef-opacity)
- [flood-opacity](https://drafts.fxtf.org/filter-effects/#FloodOpacityProperty)
- [fill-opacity](https://drafts.fxtf.org/fill-stroke/#fill-opacity) (also in [SVG2](https://svgwg.org/svg2-draft/painting.html#FillOpacity))
- [stroke-opacity](https://drafts.fxtf.org/fill-stroke/#stroke-opacity) (also in [SVG2](https://svgwg.org/svg2-draft/painting.html#StrokeOpacity))
- stop-opacity (in [SVG2](https://svgwg.org/svg2-draft/pservers.html#StopOpacityProperty))

**Comment by tabatkins** [comment]
It was intentional to cover both; it would be weird to have opacity in color functions accept a wider syntax than opacity in `opacity`.

**Comment by emilio** [comment]
Should specified opacity serialize as a number for backwards compat, or as a percentage?

They always serialize as numbers in colors, IIRC.

**Comment by ewilligers** [comment]
> Should specified opacity serialize as a number for backwards compat, or as a percentage?
> 
> They always serialize as numbers in colors, IIRC.

Yes, Blink/Firefox serialize them as numbers in specified colors.

[CSS OM](https://drafts.csswg.org/cssom/#serializing-css-values) specifies that alphavalue serializes as a number (with specific rounding rules).

Note 1. This is an argument against https://github.com/w3c/csswg-drafts/issues/3139, at least in the context of Color 4

Note 2. We should have consistency: `<alphavalue>` in CSSOM, `<alpha-value>` in CSS Color 4.

**Comment by ewilligers** [comment]
Adding to agenda to hear from other browsers before shipping.

**Comment by dirkschulze** [comment]
The SVG WG discussed replacing `<alphavalue>` with `<number>` before because of the lack of support of percentage. So far we still reference the syntax of the `opacity` property. @ewilligers The Blink patch you are talking about, would that address all `*-opacity` properties or just `opacity` itself?

**Comment by ewilligers** [comment]
All of them

**Comment by AmeliaBR** [comment]
The tagging unfortunately makes it seem as if support for percentage opacity was rejected, but to be clear: the resolution was to *keep* percentage alpha/opacity values in the spec (the issue was asking if we should keep or revert).
