### ISSUE TITLE
[css-sizing] Suggestion: A limit-width that plays the role of a max-width but has higher priority than min-width and width, even if of lower (!) value

### ISSUE THREAD

**Issue by frevds** [w3c/csswg-drafts#3347]
Scenario: 

`<div style="min-width: 800px; max-width: 100%"> Free content allowed to define its width </div>`

What happens is that the DIV is always at least 800px wide, even if there is not enough space, due to the way the width is calculated (see spec below). 

What I cannot express in CSS is what I want: The container shall be _less_ than the min-width of 800px if the 100% I consider my maximum limit is less than the assigned minimum of 800px. Max-width simply has no priority over min-width. 

Afaik it is not possible to achieve this without scripting, which constitutes a need to introduce a new limit-width (and limit-height likewise). 

`<div style="min-width: 800px; limit-width: 100%"> Free content allowed to define its width </div>`

> The following algorithm describes how the two properties influence the used value of the 'width' property:
> * The tentative used width is calculated (without 'min-width' and 'max-width') following the rules under "Calculating widths and margins" above. 
> * If the tentative used width is greater than 'max-width', the rules above are applied again, but this time using the computed value of 'max-width' as the computed value for 'width'.
> * If the resulting width is smaller than 'min-width', the rules above are applied again, but this time using the value of 'min-width' as the computed value for 'width'.

To implement a limit, the procedure requires an addition at the end: 
> * If the resulting width is larger than 'limit-width', the rules above are applied again, but this time using the value of 'limit-width' as the computed value for 'width'.

**Comment by cpplearner** [comment]
I think this can better be solved by [the min() function](https://drafts.csswg.org/css-values-4/#calc-notation).

**Comment by frevds** [comment]
@cpplearner You're right, thanks for pointing out. I didn't know about it yet (being CSS4 draft). 

That would reduce it to

`<div style="min-width: min(800px, 100%);"> Free content allowed to define its width </div>`

..and be way more efficient in the computation, saving one step.

**Comment by gibson042** [comment]
The draft of Values and Units Level 4 introduces math functions
<https://drafts.csswg.org/css-values-4/#calc-notation> that provide this
capability:

<div style="min-width: min(800px, 100%); max-width: 100%"> Free content
allowed to define its width </div>
