### ISSUE TITLE
[css-overflow-3][css-sizing-3] Define contribution of scrollbars to min-content/max-content sizes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3348]
@cbiesinger noticed that we don't seem to spec whether/how scrollbars contribute to the intrinsic size contributions. Firefox, for example, includes the scrollbar width when 'scroll' but not 'auto'; Blink includes the scrollbar whenever present. See <a href="http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22float%3A%20left%3B%20border%3A%20solid%3B%20overflow%3A%20auto%3B%20height%3A%201em%22%3Etest%3Cbr%3Ethis">testcase</a>.

**Comment by frivoal** [comment]
Is this the right way to ask the question though? Spec quote from the part that defines [Intrinsic contributions](https://www.w3.org/TR/css-sizing-3/#intrinsic-contribution):

> A box’s min-content contribution/max-content contribution in each axis is the size of the content box of a hypothetical auto-sized float that contains only that box

That's about the content box, so to me, it's pretty clear that they should not include the scrollbar size, as that's not in the content area. However, when you calculate the outer size, starting from the content size, you should add the padding, scrollbar gutter, border and margin, and if you skip adding the scrollbar gutter, you get weird results.

**Comment by frivoal** [comment]
So I think that what we need is a clarification in css-sizing-3 and/or css-box-4 (probably the later) that the border edge goes around not just the content+padding+border area, but also includes the gutter area, that the margin/outer edge builds from there, and that when you're computing the sizes of these things, you have to take account for the size of the gutter.

**Comment by frivoal** [comment]
css-overflow [has this](https://drafts.csswg.org/css-overflow-3/#scrollbar-layout):
> Any space taken up by the scrollbars should be taken out of (subtracted from the dimensions of) the containing block formed by the element with the scrollbars.

which is probably a bit too casual in its phrasing. If we're doing available width sizing, then yes, we start with the dimension of the containing block, and substract the m/b/p *and* the size of the gutter, but otherwise, when we're sizing from the content box outwards, then the size of the scrollbar gutter needs to be *added* to the the inner size, along with m/b/p, to get to the outer size.

**Comment by fantasai** [comment]
@frivoal The sentence you quote in https://github.com/w3c/csswg-drafts/issues/3348 you're not reading carefully enough, it's the size of the content box of the float which contains the box, not the content box of the box itself...

**Comment by frivoal** [comment]
> When the box is sized to fit its contents,
> this reserved space is added to the size of its contents.
> It is otherwise subtracted from space alotted to the [=content area=].

"When the box is sized to fit its contents" is that equivalent to all forms of intrinsic sizing, or only `fit-content()`? It reads as if it is the latter, but I think it should be the former.

**Comment by fantasai** [comment]
OK, fixed. Resulting text is in https://drafts.csswg.org/css-overflow-3/#scrollbar-layout
