### ISSUE TITLE
[css-env-1] environment variables as redundant mechanism

### ISSUE THREAD

**Issue by srsgores** [w3c/csswg-drafts#3350]
After reading [the proposal spec on CSS environment variables](https://drafts.csswg.org/css-env-1/), I find the proposed `env` keyword redundant and misleading:

1. Introduces a new function which essentially does the same thing as `var()`
2. Lacks a clear specificity on how `var()` plays with `env()`
3. Adds another level of complexity to CSS for new learners which may impede or slow down learning

Instead, I propose using the familiar `var` keyword already available.  UAs can predefine custom properties to known variable names.  It seems to me that the draft tries to solve a problem that really isn't there for most authors.

For fallbacks, the author may define those using the normal `:root` or specificity.

Instead of focusing on creating a new function, let's focus on a naming convention for UAs to follow that standardizes the variable names we can use.

**Comment by Loirooriol** [comment]
See #3285, `env()` is more like `calc()` or `attr()` rather than `var()`.

**Comment by tabatkins** [comment]
Yup, env() serves a different purpose from var(), tho the two are roughly similar.
