### ISSUE TITLE
When is CSS sub grid coming out

### ISSUE THREAD

**Issue by SephReed** [w3c/csswg-drafts#3356]
I know this isn't a real issue.  But I don't know a better way to poke you peeps.  We need css grid!  I'm running into issues with not having it on *every* project ever since I started using css grid.

**Comment by jonjohnjohnson** [comment]
@SephReed I'd suggest attempting to reach out to the editors of individual specs via twitter. Of course you may need to search a bit to find their handles.

As far as https://drafts.csswg.org/css-grid-2/#subgrids goes, it lists three editors, of which I'd suggest asking @fantasai / https://twitter.com/fantasai.

Also, feel free to check out open issues for the grid-2 spec:
https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+grid+label%3Acss-grid-2

And probably close this issue?
