### ISSUE TITLE
Starting point isn't changed when searching outside of a container

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3358]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/128
Originally created by @hugoholgersson on *Thu, 01 Nov 2018 20:33:20 GMT*

---
I created a Chromium-bug that describes this in problem in more detail: https://crbug.com/900499.

The current algorithm (pictured in 7.2) does not change the starting point* when climbing to an ancestor container.

\* In Chrome we use the term "search origin" instead of "starting point".

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/128#issuecomment-436926230
Originally created by @jihyerish on *Thu, 08 Nov 2018 09:18:35 GMT*

---
Oh, I see. Then I can see two topics here:

[[Topic 1]]()
If the starting point inside the scroll container becomes out of the view, reset the starting point to the scroll container.
[[Topic 2]]()
Use the bounding border box(visual bounding box) of the scroll container only when searching *outside*.

Topic 1 is also related to https://github.com/WICG/spatial-navigation/issues/129.
I think we need to discuss more about it.

But for Topic 2, why do you think that the scope for searching the candidate is the visual bounding box only when the focus moving outside?
Does it mean that if the focus is about to move inside the scroll container and the scroll bar is at the end, the focus will move to the first element in the scroll container which is offscreen?

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/128#issuecomment-436942513
Originally created by @hugoholgersson on *Thu, 08 Nov 2018 10:11:47 GMT*

---
>But for Topic 2, why do you think that the scope for searching the candidate is the visual bounding box only when the focus moving outside?

Look at @junhoseo's [test case](https://chromium-review.googlesource.com/c/chromium/src/+/1253523/8/third_party/WebKit/LayoutTests/fast/spatial-navigation/snav-search-outside-of-focused-scroller.html). It demonstrates why we cannot use the scroll container's edge when searching outside of the [focused] scroll container.

> Does it mean that if the focus is about to move inside the scroll container and the scroll bar is at the end, the focus will move to the first element in the scroll container which is offscreen?

Spatnav should never move focus to an offscreen element... When moving towards a scroll container, no matter if it contains visible focusables or not, focus should [first go to the scroll container](http://bit.ly/snav2) itself. (Remember that [scroll containers are focusables too](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Fku6784p0wI/3MyOMTk7BwAJ).)

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/128#issuecomment-436164659
Originally created by @hugoholgersson on *Tue, 06 Nov 2018 08:07:23 GMT*

---
> if the starting point which is a decendent of the scrollable element becomes out of the view, the starting point needs to be changed to the bounding border box of the scrollable element.

Yes, that's what I mean, but this is _only when searching outside_ the scroll container.

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/128#issuecomment-436155195
Originally created by @jihyerish on *Tue, 06 Nov 2018 07:23:42 GMT*

---
In current spec, the focus moves inside or outside of the scrollable element depending on the bounding border box of the scrollable element.
(The definition of the boundary box in the spec: https://wicg.github.io/spatial-navigation/#boundary-box)

I'm not sure I understand clearly about your point. 
Am I understanding right about your opinion as below?:

- if the starting point which is a decendent of the scrollable element becomes out of the view, the starting point needs to be changed to the bounding border box of the scrollable element.

**Comment by jihyerish** [comment]
The issue migration script created some duplicates. #3391 is the same as this one.
So I'll close this issue.
