### ISSUE TITLE
Improve the name of window.navigate

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3362]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/120
Originally created by @frivoal on *Wed, 17 Oct 2018 05:21:10 GMT*

---
Previously in #70, we discussed whether `window.navigate()` was a great name for this API or not. It seems like it could be confused with navigating to a new URL, so some better name would be good.

However, no suggestion so far seems to work:
* `focusNavigate()` or other names invoking focus are wrong, because it can also scroll things instead of focusing them
* `directionalNavigate()` or `spatialNavigate()` or similar are also problematic, because this method should be possible to extend to sequential navigation by passing it a `"prev"` or `"next"` argument, and that does not work with such names.

So, leaving this issue open to see if we can do better.

**Comment by frivoal** [comment]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/120#issuecomment-434350580
Originally created by @hugoholgersson on *Tue, 30 Oct 2018 15:36:17 GMT*

---
`stepFocusOrScroll`

**Comment by jihyerish** [comment]
The issue migration script created some duplicates. #3387 is the same as this one.
So I'll close this issue.
