### ISSUE TITLE
Take shadow DOM into account

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3364]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/21
Originally created by @frivoal on *Fri, 16 Feb 2018 06:28:28 GMT*

---
The spec does not currently say anything about shadow DOM. It most certainly should say something.

**Comment by jihyerish** [comment]
The issue migration script created some duplicates. #3381 is the same as this one.
So I'll close this issue.
