### ISSUE TITLE
Clarify "starting point" terminology

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3372]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/91
Originally created by @frivoal on *Thu, 02 Aug 2018 08:36:44 GMT*

---
**spatial navigation starting point** is a term defined by the spec. *startingPoint* is a variable in the spatial navigation steps algorithm. The two things refer to related but different concepts. The fact that their names are so close is really confusing, so we should rename one (or both).

**spatial navigation starting point** refers to the point indicated by the user (for example by clicking somewhere) where they want the navigation to start from. There may be no such point.

*startingPoint* refers to where the algorithm will search from. If the user has indicated no particular point, it is the currently focused element (or the document if nothing is focused). If the user has indicated a point, the search starts from there.

Note: The HTML spec in the section that defines sequential navigation has the same problem (this section in spatial navigation is inspired by the HTML spec).

**Comment by jihyerish** [comment]
The issue migration script created some duplicates. https://github.com/w3c/csswg-drafts/issues/3389 is the same as this one.
So I'll close this issue.
