### ISSUE TITLE
[css-nav-1] Clarify "starting point" terminology

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3389]
---

Migrated from https://github.com/WICG/spatial-navigation/issues/91
Originally created by @frivoal on *Thu, 02 Aug 2018 08:36:44 GMT*

---
**spatial navigation starting point** is a term defined by the spec. *startingPoint* is a variable in the spatial navigation steps algorithm. The two things refer to related but different concepts. The fact that their names are so close is really confusing, so we should rename one (or both).

**spatial navigation starting point** refers to the point indicated by the user (for example by clicking somewhere) where they want the navigation to start from. There may be no such point.

*startingPoint* refers to where the algorithm will search from. If the user has indicated no particular point, it is the currently focused element (or the document if nothing is focused). If the user has indicated a point, the search starts from there.

Note: The HTML spec in the section that defines sequential navigation has the same problem (this section in spatial navigation is inspired by the HTML spec).

**Comment by jihyerish** [comment]
@frivoal 
Then, the _startingPoint_ would be the _search origin_ (or starting origin)?

Also, if the _spatial navigation starting point_ is a point, how does it affect for defining the _search origin_ and _currently focused element_?
I think in this case, 
1) The _search origin_ and _currently focused element_ are not identical.
   - _search origin_: a point by clicking
   - _currently focused element_: an element which gains the focus by clicking

2)  The best candidate selecting algorithm will search from _search origin_ (defined as the point).

Do I understand right?

**Comment by frivoal** [comment]
> I think in this case, 
> 1) The _search origin_ and _currently focused element_ are not identical.
>    - _search origin_: a point by clicking
>    - _currently focused element_: an element which gains the focus by clicking
> 
> 2)  The best candidate selecting algorithm will search from _search origin_ (defined as the point).
> 
> Do I understand right?

Almost:
1) The _searchOrigin_ is the currently focused element, unless the browser decides to have a _spatial navigation starting point_ inside the currently focused element, in which case the _searchOrigin_ is that instead. Browsers don't have to have a _spatial navigation starting point_. If they do, it is typically set by clicking. But they could set it by some other way, and they don't have to set it at all.
2) The best candidate selecting algorithm will search from _searchOrigin_, that can be a point (if there was a _spatial navigation starting point_), or a node.

**Comment by jihyerish** [comment]
@frivoal. Thanks, now I understand it clearly.
