### ISSUE TITLE
[css-nav-1] changing the spatnav scroll controls from JS to declarative

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3401]
During TPAC, several engineers from Google (including I believe @eaenet and @chrishtr ) expressed concern over the `navbeforescroll` event, on the grounds that having to run any kind of synchronous JS right before scrolling (and even more so in the middle of scrolling, as could be the case if the user tries to repeatedly navigate in the same direction) was a performance concern.

Changing from an even to an observer would slightly attenuate that concern as it is cheaper, but not completely as that still involves running JS synchronously at that point.

In theory, I believe the 3 events (`navbeforescroll`, `navbeforefocus`, and `navnotarget`) are necessary and sufficient to be able to intercept spatnav before anything happens. However, in practice, I can only think of one use case that calls for `navbeforescroll`: the one illustrated in [example 5](https://drafts.csswg.org/css-nav-1/#focus-only), which allows the authors to switch the behavior from searching for candidates from within just the visible elements in the container to within all elements in the container regardless of visibility.

In [the spatial navigation steps](https://drafts.csswg.org/css-nav-1/#spatial-navigation-steps ), steps 5.1 and 7 invoke [`finding focusable areas`](https://drafts.csswg.org/css-nav-1/#find-focusable-areas), relying on the optional `visibleOnly` argument defaulting to `true`. Invoking it with `visibleOnly` set to `false` would switch to the other behavior we're trying to cover here.

Providing a declarative solution to this problem is very easy, and has none of the performance downsides: an inherited css property whose computed value on `searchOrigin` in step 5.1 or on `container` in step 7 would act as the switch between the two modes. Strawman name:
```css
spatial-navigation-candidates: visible | all
```

If we add this, I think we could remove `navbeforescroll` and not lose any useful capability, solving the performance concern.

**Comment by jihyerish** [comment]
I agree with removing `navbeforescroll` event, in terms of the scroll latency.

After dropping `navbeforescroll` event, when the `navnotarget` event occurs?
(1) When there isn’t any candidate in the spatial navigation container and it cannot be scrolled at the same time. (current spec)
(2) When there isn’t any visible candidate in the spatial navigation container no matter what it can be scrolled more or not.

**Comment by frivoal** [comment]
If `spatial-navigation-candidates: visible` (the initial value), then it would be (1). If `spatial-navigation-candidates: all`, then it would be:
(3) when there isn't any candidate (visible or not) in the spatial navigation container no matter what it can be scrolled more or not.

**Comment by jihyerish** [comment]
I agree with the overall definition of `navnotarget` after dropping `navbeforescroll`.

But the moment when `navnotarget` occurs differs from the condition of candidates (all or visible) seems unnatural to me. It causes inconstant behavior when the scroll container can be scrolled more or not.

Instead, how about define the CSS property as below?

```css
spatial-navigation-behavior: auto | focus | scroll 
(or spatial-navigation-action)
```

* `auto`: The directional input will move the focus to the visible candidates inside the spatial navigation container. If there isn't any visible candidate, the user can manually scroll the container. (current spec)
* `focus`: The directional input will move the focus to candidates(visible or not) inside the spatial navigation container. The user cannot manually scroll the container.
* `scroll`: The directional input will only scroll the spatial navigation container. Moving the focus inside the container doesn't work with the directional input.
  
  * e.g. The container made by the iframe with RSS feeds. In this case, the author may want to make it scroll, not move the focus inside it.

I guess in comparison with your proposal,
`spatial-navigation-candidates: visible` works the same with `spatial-navigation-behavior: auto`
and
`spatial-navigation-candidates: all` is same with `spatial-navigation-behavior: focus`.

Also, the definition of `navnotarget` would be changed to "The event occurs when there won't be any **action with the directional input** for the spatial navigation container before going up the tree to search candidates in the nearest ancestor spatial navigation container".

"**action with the directional input** " above will be 
moving the focus and scrolling if the container is specified as `spatial-navigation-behavior: auto`,
or
just moving the focus (without scrolling) if the container is specified as `spatial-navigation-behavior: focus`.

This way can support the feature of `navbeforescroll` and solve the performance issue.
More detail about the feature of `navbeforescroll`, there will be
(1) Move the focus directly to the invisible candidates in the spatial navigation container
(2) Move the focus directly to a virtual candidate which will be created and added inside the spatial navigation container when the scroll reaches to the end (as the virtual scroller).

(1) is implemented with `spatial-navigation-behavior: focus`.

(2) can be implemented using `navnotarget` and `spatial-navigation-behavior: focus` as below:
   i) when the spatial navigation container (the related target of `navnotarget`) is specified with `spatial-navigation-behavior: focus`
   ii) `navnotarget` occurs if there isn't any candidate (visible or not) in the spatial navigation container no matter what it can be scrolled more or not

**Comment by jihyerish** [comment]
If `navbeforescroll` is removed, there will be no way to block scrolling behavior. 
Therefore it's hard to implement the infinite scroll in the page with the spatial navigation.

But it's much easier if we have the suggesting property, 'spatial-navigation-behavior' CSS Property.
It defines how the directional input behaves for the scrollable element.
`spatial-navigation-behavior: focus` can separate the native scroll and the spatial navigation behavior.
We have `navnotarget` to know the end of the current scroller and prevent the focus to move out of the spatial navigation container.

You can see the detail and how it works in the following page:
https://raw.githack.com/jihyerish/spatial-navigation/spatnav-behavior/demo/virtual-scroller/navnotarget_ver.html
