### ISSUE TITLE
[css-fonts-4] Should font-size-adjust have a from-font value?

### ISSUE THREAD

**Issue by bernhardf-ro** [w3c/csswg-drafts#3402]
Assuming that `font-size-adjust` is primarily used to adjust portions of text that deviate from the default font of the document, e.g. keywords marked as code or automatic fallback, authors would benefit from a `from-font` value that computes to `(1ex/1em)` or "_the `number` that causes equal behavior to the `none` keyword for the current font_". This would eliminate the need to manually approximate the `number` value, making the property more straight-forward to use.

**Comment by svgeesus** [comment]
`font-size-adjust` now [has a `from-font` value](https://drafts.csswg.org/css-fonts-5/#valdef-font-size-adjust-from-font)
