### ISSUE TITLE
[css-selectors] [proposal] New pseudo-class :modified for inputs

### ISSUE THREAD

**Issue by zoliszabo** [w3c/csswg-drafts#3408]
Like the title of this issue says, I want to propose a new pseudo-class called **`:modified`**, which would apply to inputs (e.g. `input[type=text]`, `select`, `textarea`) whose value was modified compared to their initial value (on page load or the moment of their addition to the DOM).

I think it would fit this category:
https://www.w3.org/TR/selectors-4/#input-value-states

Example:
```
input {
    font-weight:normal;
}
input:modified {
    font-weight:bold;
}
```
The above would highlight modified inputs with bold font.

What do you think?

**Comment by Loirooriol** [comment]
Seems a dupe of #1533

**Comment by zoliszabo** [comment]
@Loirooriol That's right. I'll close this issue. Thank you for pointing it out.
