### ISSUE TITLE
[css-grid] Example 4 from specification

### ISSUE THREAD

**Issue by Gunyon** [w3c/csswg-drafts#3410]
I try to learn css-grid and there is a confusing situation in the example 4 form the [specs](https://www.w3.org/TR/css-grid-1/#overview-placement).

These expressions do not seem to be equivalent

`grid-area: header-start / sidebar-start / footer-end / sidebar-start;`

`grid-row: header-start / footer-end;  grid-column: sidebar-start / footer-end;`

**Comment by fantasai** [comment]
Wow, that's a lot of typos in there! Should be fixed in https://github.com/w3c/csswg-drafts/commit/09f6107883f2e8a292dc0a2855af8af2291612d5, let me know if I screwed it up.

**Comment by Gunyon** [comment]
there are no more confusions, thanks
