### ISSUE TITLE
[css-align][css-flex] Doubt about baseline alignment

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#3416]
Some links to the specs:
* https://drafts.csswg.org/css-align/#baseline-rules
* https://drafts.csswg.org/css-flexbox/#flex-baselines

I've some doubts about how baseline alignment should work in the case of flex vs inline-flex.
Let's compare the behavior of block vs inline-block with flex vs inline-flex in the following examples.

```html
<h2>Case 1)</h2>
foo
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: inline-block; width: 50px; height: 50px; background: magenta;">
  </div>
</div>
bar
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: block; width: 50px; height: 50px; background: cyan;">
  </div>
</div>
baz
```

![Output of case 1)](https://user-images.githubusercontent.com/11602/49722008-f1978100-fc63-11e8-9e81-0f2d6c76d543.png)

For this example all browsers behave the same.
In this case the magenta box is an `inline-block` which determines the baseline of the outer box, so the 50px margin are not taking into account to compute the baseline.
However the cyan box is a `block`, in that case it's not used to compute the baseline, and the `50px` margin on the outer box are taken into account for the baseline.

```html
<h2>Case 2)</h2>
foo
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: inline-flex; width: 50px; height: 50px; background: magenta;">
  </div>
</div>
bar
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: flex; width: 50px; height: 50px; background: cyan;">
  </div>
</div>
baz
```

![Output of case 2)](https://user-images.githubusercontent.com/11602/49722040-0a079b80-fc64-11e8-89a0-499d69537cc8.png)

Here in Chromium/WebKit the `flex` case (cyan) behaves the same than the `flex-inline` (magenta). However in Firefox/Edge it works the same than the inline-block vs block case.
I believe Firefox/Edge are the ones right in this case.

But let's see what happens when we add one level more:

```html
<h2>Case 3)</h2>
foo
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: inline-block;">
    <div style="width: 50px; height: 50px; background: magenta;">
    </div>
  </div>
</div>
bar
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: block;">
    <div style="width: 50px; height: 50px; background: cyan;">
    </div>
  </div>
</div>
baz
```

![Output of case 3)](https://user-images.githubusercontent.com/11602/49722062-17bd2100-fc64-11e8-8246-f147306695ce.png)

This still works the same than the case 1) and behavior is the same in all browsers.

But what happens with flexbox:
```html
<h2>Case 4)</h2>
foo
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: inline-flex;">
    <div style="width: 50px; height: 50px; background: magenta;">
    </div>
  </div>
</div>
bar
<div style="display: inline-block; margin-bottom: 50px;">
  <div style="display: flex;">
    <div style="width: 50px; height: 50px; background: cyan;">
    </div>
  </div>
</div>
baz
```

![Output of case 4)](https://user-images.githubusercontent.com/11602/49722090-299ec400-fc64-11e8-8157-9679c2745ebf.png)

In this case all browsers mach again, and cyan box works the same than magenta box.
The 50px margin is not used to compute the baseline.

TBH, I'm not really sure why case 3) is different from 4). Or if behavior in 4) is right or not.
You can play with this examples live at: https://jsbin.com/tetatemiqo/1/edit?html,output

**Comment by mrego** [comment]
I want to fix the interop issue between Firefox and Blink/WebKit for case 2) where Firefox is right (see [Chromium bug #671132](https://bugs.chromium.org/p/chromium/issues/detail?id=671132)).
However I'd love to clarify the case 4) just in case it needs or not some behavior change.

**Comment by javifernandez** [comment]
Just a comment regarding Case 2; I think Chromium/WebKit are correct in this case, due to this statement of the Flex spec:

https://drafts.csswg.org/css-flexbox-1/#flex-baselines
> Otherwise, if the flex container has at least one flex item, the flex container’s first/last main-axis baseline set is generated from the alignment baseline of the startmost/endmost flex item. (If that item has no alignment baseline parallel to the flex container’s main axis, then one is first synthesized from its border edges.)

So, the baseline of the inline-flex container is determined by its only flex item, which has no natural baseline, so it's synthesized using its border edge.

**Comment by mrego** [comment]
After talking to @dholbert during the last CSWG F2F meeting in San Francisco, I agree with him that Firefox behavior is right in all the cases.

The relevant spec text is:
* [Old version from CSS2](https://www.w3.org/TR/CSS22/visudet.html#leading):
  > The baseline of an 'inline-block' is the baseline of its last line box in the normal flow, unless it has either no in-flow line boxes or if its 'overflow' property has a computed value other than 'visible', in which case the baseline is the bottom margin edge.
* [New text from css-align](https://drafts.csswg.org/css-align/#baseline-export):
  > However, for legacy reasons, if an inline-block is a scroll container or contains no in-flow line boxes, its first and last baseline sets are synthesized from its margin box.

Case 1) All browsers do the same. When we have an `inline-block` wrapping an empty `block`, it's considered it doesn't have *in-flow* line boxes, and that's the reason why the margin box of the `inline-block`is used to determine the baseline.

Case 2) The same kind of reasoning applies in this case. The wrapping `inline-block` considers that it has no *in-flow* line boxes, because its content is just an empty flexbox container. So it should use the margin box to determine the baseline (like Firefox does).

Case 3) Here all browsers agree again. The inner `block` has no baseline due to the following text from the spec:
> If there is no such line box or child, then the block container has no baseline set.
As it has no baseline, all browsers follow the same bahavior than Case 1).

Case 4) Here Flexbox spec enters:
> Otherwise, if the flex container has at least one flex item, the flex container’s first/last main-axis baseline set is generated from the alignment baseline of the startmost/endmost flex item.
As the flexbox container has one children, it's baseline is generated from that children. For that reason the margin box of the `inline-block` is not used to determine the baseline.

Please @dholbert comment or clarify antyhing here, as articulating all this with words is kind of complicated.

I have a patch to make Chromium match Firefox in all these cases, so I hope the explanation above is right and this is the expected behavior.

So, I'm closing this unless someone doesn't agree and wants to reopen it and provide some extra feedback/arguments on this topic.

**Comment by dholbert** [comment]
@mrego, your summary makes sense to me, and matches my recollection of our discussion. Thanks!
