### ISSUE TITLE
[css-pseudo-4] clarify ::selection applies to programatically created selection

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#3425]
In https://drafts.csswg.org/css-pseudo-4/#selectordef-selection the spec says:

> The ::selection and ::inactive-selection pseudo-elements represent the portion of a document that has been highlighted by the user.

However, it is possible that web apps can create selections with DOM Ranges and Selection APIs. And `::selection` applies to those programatically created selections. Perhaps spec should take such non-user initiated selection into account?

**Comment by fantasai** [comment]
OK, I made some updates. @myakura Can you look over it and let me know if it needs further adjustment?

**Comment by myakura** [comment]
@fantasai looks good. thanks!
