### ISSUE TITLE
[css-ui-4] cursor should use <image> not <url>

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3432]
Issue [originally raised on www-style in 2012](https://lists.w3.org/Archives/Public/www-style/2012Jul/0276.html) by @tabatkins and [copied over to tracker](https://www.w3.org/Style/CSS/Tracker/issues/269) by @fantasai 

(CSS Images 3 says](https://drafts.csswg.org/css-images-3/#placement)

> This module defines and extends the &lt;image> value type defined in [CSS-VALUES-3]. It also replaces the &lt;url> type with &lt;image> in the background-image, cursor, and list-style-image definitions in CSS1 and CSS2

However, [CSS UI 4 uses &lt;url>](https://drafts.csswg.org/css-ui-4/#propdef-cursor)

> [ [&lt;url> [&lt;x> &lt;y>]?,]*
[ auto | default | none |
context-menu | help | pointer | progress | wait |
cell | crosshair | text | vertical-text |
alias | copy | move | no-drop | not-allowed | grab | grabbing |
e-resize | n-resize | ne-resize | nw-resize | s-resize | se-resize | sw-resize | w-resize | ew-resize | ns-resize | nesw-resize | nwse-resize | col-resize | row-resize | all-scroll |
zoom-in | zoom-out
] ] 

_I didn't see this in closed issues, feel free to close if this is a duplicate._

**Comment by frivoal** [comment]
In the definition of the values for this property, threre's this sentence:

> Conforming User Agents may, instead of `<url>`, support `<image>` which is a superset. 

Do you think we should move away from that, and just use `<image>`? Conceptually, I'd have no problem with it, but I don't believe that the UAs actually support `<image>` values other than URLs, so going with more than a *may* seems maybe a bit optimistic.

**Comment by frivoal** [comment]
Based on the explanation above. I'm planning to close as wontfix/invalid. Now's the time to disagree if you'd like to stop me.

**Comment by svgeesus** [comment]
That seems fair enough to me.
