### ISSUE TITLE
[css-text-decor-3] ruby with dots examples seem incorrect

### ISSUE THREAD

**Issue by macnmm** [w3c/csswg-drafts#3436]
On several of the visual examples of dotted emphasis, the dot placement is too close to the base text.
https://www.w3.org/TR/css-text-decor-3/images/text-emphasis-ja.png
The emboxes of the base text and dotted emphasis glyphs should touch and not overlap. The size of the dotted glyphs' emboxes are normally 50% of those of the base text, although sometimes further scaling of glyphs is necessary for larger dots.

**Comment by fantasai** [comment]
OK, I made the images look pretty. Hopefully it's OK, the emphasis dot positions are still approximate. :)

**Comment by macnmm** [comment]
If Murakami-san is fine I am fine.

**Comment by fantasai** [comment]
Wait, as this a response to this issue or issue https://github.com/w3c/csswg-drafts/issues/3437 ?

**Comment by fantasai** [comment]
OK, great!
