### ISSUE TITLE
[css-text-decor-3] ruby dotted emphasis seem incorrect #2

### ISSUE THREAD

**Issue by macnmm** [w3c/csswg-drafts#3437]
For ruby plus dotted emphasis, I do not think the dots would be set as in the example: https://www.w3.org/TR/css-text-decor-3/images/text-emphasis-ruby.png

I think they all would be moved up, similar to the stipulation for underline of text of varying sizes in https://www.w3.org/TR/css-text-decor-3/images/underline-single.png
[Please verify with other experts as to this edge case.]

**Comment by upsuper** [comment]
From [previous discussion](https://lists.w3.org/Archives/Public/www-style/2013Feb/0109.html) on this topic, I believe it is handled this way intentionally.

**Comment by fantasai** [comment]
Closing out per previous discussion. Hopefully Level 2 will allow more control over this, as Antenna House has developed. :)

**Comment by fantasai** [comment]
@macnmm Let me know if this is acceptable or if you like us to reconsider.

**Comment by macnmm** [comment]
If Murakami-san is fine I am fine.
