### ISSUE TITLE
[css-text-decor-3] suggestion to support obituary line style

### ISSUE THREAD

**Issue by macnmm** [w3c/csswg-drafts#3438]
In Japanese newspaper decoration, there is a form of overline (right side in vertical) used in obituaries, similar to the "accounting underline" shown in https://www.w3.org/TR/css-text-decor-3/images/underline-position-under.png

https://assets.shaso.jp/wp-content/uploads/2016/01/16040358/142cd3d08e8332a0f30b5c0bc2560a31.jpg

Its placement is different from normal overline (set more outside the line, not touching the embox) and is thicker than overline. Perhaps inclusion of an example like this could be useful?

**Comment by jonjohnjohnson** [comment]
@macnmm Maybe I'm misunderstanding you, but it seems what you are describing should be covered in the properties/features of both...

- https://drafts.csswg.org/css-text-decor-3/
- https://drafts.csswg.org/css-text-decor-4/

**Comment by fantasai** [comment]
The spec seems correct, but the illustrations have the line a bit too close. Updated the images @macnmm Let me know if they look OK? 

Old: https://www.w3.org/TR/2018/CR-css-text-decor-3-20180703/#underline-left
New: https://drafts.csswg.org/css-text-decor-3/#underline-left

**Comment by macnmm** [comment]
@fantasai For normal underline/overline, the former graphic was ok in terms of its placement. For "accounting underline" or "obituary line", your new graphic is more correct in terms of being slightly farther from the text, but usually in Japanese the line is made thicker as well.
Since the graphic seems to be intended to depict normal underline, the original graphic is actually closer. It is hard to tell as the embox boundaries are not clear (I will email you a picture to show what I am talking about).

**Comment by fantasai** [comment]
Ok, reverted. Seems like there's nothing to do here, then?

**Comment by fantasai** [comment]
We have `text-underline-offset` and `text-underline-thickness` in L4 for customizing the underline position/thickness.

**Comment by fantasai** [comment]
We also need to define these positions a little more precisely in L4. :)
