### ISSUE TITLE
[css-box-4][css-break-4] Do terms like "truncate", "discard" and "trim" require more specification? (margin-break/margin-trim)

### ISSUE THREAD

**Issue by bernhardf-ro** [w3c/csswg-drafts#3443]
https://drafts.csswg.org/css-break-4/#break-margins
https://drafts.csswg.org/css-box-3/#propdef-margin-trim
- "are **discard**ed or kept"
- "are **trim**med"
- "are **truncate**d"
- "are **truncate**d _to zero_"
- ("**truncate** _to the remaining fragmentainer extent_")

I wonder if such property definitions should either specify the behavior in more detail before using those terms or define the terms somewhere. To me and my colleagues they are not entirely clear. I have collected some of our points of confusion:

1. Does "_truncate_" without a target mean "_truncate to zero_"?
2. Does "_truncate to X_" mean "_set value to X_" or "_set value to X if it is larger than X_" (so "_truncate to zero_" would not change negative values)?
3. Same as 1. and 2. but for "_trim_"
4. Does "_discard_" mean "_set value to zero_" (in contrast to things like "skip any processing that requires the value and do some special alternative steps...")?
5. If those change the value, can we assume it is the _used value_ (e.g. of margin-top) that is changed, not affecting inheriting children but the resolved style for `getComputedStyle`?

Any clarification, here or in the specifications, would be appreciated.

**Comment by fantasai** [comment]
1. Does "truncate" without a target mean "truncate to zero"?

This probably depends on the context of the sentence, the one I see is referencing truncation to zero in the previous sentence.

2. Does "truncate to X" mean "set value to X" or "set value to X if it is larger than X" (so "truncate to zero" would not change negative values)?

The latter, per English definition. You can't increase the size of something by truncating it.

3. Same as 1. and 2. but for "trim"

Same.

4. Does "discard" mean "set value to zero" (in contrast to things like "skip any processing that requires the value and do some special alternative steps...")?

Yes.

5. If those change the value, can we assume it is the used value (e.g. of margin-top) that is changed, not affecting inheriting children but the resolved style for getComputedStyle?

Yes.

**Comment by bernhardf-ro** [comment]
Thanks for the clarifications. You covered everything we needed. So we can join the more specific discussions about the properties when anything comes up.
