### ISSUE TITLE
[css-values-4] Round to integer only at end of computation or conversion

### ISSUE THREAD

**Issue by TalbotG** [w3c/csswg-drafts#3444]
In this
[calc-integer.html](http://w3c-test.org/css/css-values/calc-integer.html)
test authored by @emilio , at lines 44-46, we have:

    specified: "calc(calc(1 / 3) * 3)",
    computed: "1",
    description: "Only rounds at the end of the conversion"

The statement "Only rounds at the end of the conversion" makes sense but I do **not** read a normative statement of this sort anywhere in the CSS4 Values specification.

[5.1.1 Combination of &lt;integer&gt;](https://www.w3.org/TR/css-values-4/#combine-integers)

[9.1 Mathematical Expressions: calc(), min(), max(), and clamp()](https://www.w3.org/TR/css-values-4/#calc-notation)

**Comment by astearns** [comment]
@TalbotG by my reading the statement is in 9.1.4: 

> if a math function that resolves to `<number>` is used somewhere that only accepts `<integer>`, the computed value and used value are rounded to the nearest integer

The value of the interior calc in that test is not in a place that only accepts `<integer>`, so no rounding happens.

It would probably be good to have an example for this.

**Comment by TalbotG** [comment]
Okay, I see. It's a tricky subtest. 
I am closing this issue.

> It would probably be good to have an example for this.

There are 2 sub-tests in @emilio test where a &lt;number&gt; is rounded to the nearest integer.


    specified: "calc(1 / 2)",
    computed: "1",
    description: "Rounds up if fractional part is >= 0.5",
 
and

    specified: "calc(1 / 3)",
    computed: "0",
    description: "Rounds down if fractional part is < 0.5",
