### ISSUE TITLE
[css-grid] computed grid-row-start with default span integer

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3448]
https://drafts.csswg.org/css-grid/#grid-placement-span-int
> `span && [ <integer> || <custom-ident> ]`
> If the `<integer>` is omitted, it defaults to 1. Negative integers or zero are invalid.

grid-row-start  `"span i"` computes to `"span 1 i"` on Blink/WebKit, but computes to `"span i"` on Edge/Firefox.

grid-row  `"span i / auto"` computes to `"span 1 i / auto"` on Blink/WebKit, but computes to `"span i / auto"` on Edge, empty string on Firefox.

For many properties, the shortest serialization principle often leads to keywords being omitted, but it is unusual for numeric values to be omitted.

**Comment by tabatkins** [comment]
None of these are "computing to" anything. They're *serializing as* "span i" or "span 1 i".  All browsers compute them to the same internal value.

Per the shortest serialization principle, the `1` should be omitted from the serialization here. There's nothing special about numeric values vs keywords; numerics get omitted all the time (in shorthands, particularly).

**Comment by ewilligers** [comment]
http://jsfiddle.net/ericwilligers/nawfLdp8/

When we read the specified value, all browsers give `"span i"` and `"span i / auto"`

When we call getComputedStyle(), Blink and WebKit give `"span 1 i"` and `"span 1 i / auto"`, while Edge and Firefox omit the `1`.

**Comment by mrego** [comment]
JFTR, Chromium bug related to this issue: http://crbug.com/916827
