### ISSUE TITLE
[css-color-4] Allow percent as well as float 0.0 to 1.0 in color() args

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3450]
@faceless2 said

> allowing a percentage as a synonym for 0..1 may be more natural, e.g. color(swopc 0 85% 70% 42%)

which is worthy of separate discussion.

**Comment by BrentARitchie** [comment]
The spec already allows this for several types: namely ```<rgb-component>``` and ```<alpha-value>``` in the ```rgba()``` function. So I think that it would be natural to define it as a ```<number-percentage>```. The change still allows the full range of real numbers to be used, just in a different format. ie. 300% = 3 or 450% = 4.5, etc..

**Comment by svgeesus** [comment]
While allowing, say, 50% as a synonym for 0.5 seems unproblematic, doing so would impact https://github.com/w3c/csswg-drafts/issues/278 were @tabatkins argues for adding percentage units to the L* value. So 50 and 50% would be synonymous, except now the spec would need to clarify that here, 50% means 50 not 0.5.

Apart from that one issue, I don't see an issue with allowing percentage units as well as floats here. I don't want to hold up this issue for #278 so I'm going to agree with @faceless2 here and solve that other issue separately.

**Comment by svgeesus** [comment]
Existing tests need to be updated to also check the percentage values.

**Comment by svgeesus** [comment]
With the recent [resolution to 4649](https://github.com/w3c/csswg-drafts/issues/4649#issuecomment-572168734) adding `lab` to the `color()` function, this issue would require stating that all percentages resolve to 0.0 .. 1.0 *except* that for `lab` the first percentage resolves to 0.0 to 100.0.

**Comment by Crissov** [comment]
Why, though? 

L\* in `Lab()` has always been a percentage, it is just often written without the percent sign outside CSS. This is already noted in the spec as a result of #4477.

**Comment by svgeesus** [comment]
Because all the other percentages resolve to 0.0 to 1.0, and because this issue is _as well as_

**Comment by Crissov** [comment]
So does L\* in `lab(…)` and `color(lab,…)`. Itʼs always `100%` = `1.0` = `1` within CSS; only *outside* CSS you would *ever* encounter `100.0` = `100` = `100%`. 

I see no WG resolution to make `lab(50 …)` or `color(lab, 50 …)` resolve to the same color as `lab(0.5 …)` or `color(lab, 0.5 …)`. They might be clamped to `lab(1.0 …)` or `lab(100% …)` though.

**Comment by svgeesus** [comment]
Percentages as well as floats were [added in **Allow percent as well as float 0.0 to 1.0 in color() args**](https://github.com/w3c/csswg-drafts/commit/3ef889d3a8e5bb50d759f81737b5b72203ba63f2#diff-4dcdf0ecb00e997ce9e5b7d522a0cb62)

**Comment by svgeesus** [comment]
[WPT tests for color() in progress](https://github.com/web-platform-tests/wpt/pull/22756)

**Comment by svgeesus** [comment]
> WPT tests for color() in progress

Tests now updated to take into account review feedback
