### ISSUE TITLE
[css-syntax-3] Typo in 4.3.8

### ISSUE THREAD

**Issue by alin04** [w3c/csswg-drafts#3451]
Typo in https://www.w3.org/TR/css-syntax-3/#starts-with-a-valid-escape

> If the first code point is not U+005D REVERSE SOLIDUS (\), return false.

should say 

> If the first code point is not U+005C REVERSE SOLIDUS (\), return false.

Note the unicode is incorrect for reverse solidus.

**Comment by tabatkins** [comment]
That's been fixed in the Editor's Draft for a while, I just haven't republished a WD for a while either. Thanks, tho!
