### ISSUE TITLE
[css-backgrounds-4] Borders with cut corners

### ISSUE THREAD

**Issue by peteroupc** [w3c/csswg-drafts#3457]
For your information and discussion.

I have noticed that in the Google Developer blog, [an article recently published](https://developers.googleblog.com/2018/12/building-shape-system-for-material.html) noted a gap in border support in the Web Platform.  Namely, the Web Platform currently doesn't support borders with cut corners (as opposed to round or square corners), and the Material Design team is working on using the Houdini API, which is "not ready yet", to provide such borders.

However, I feel that supporting cut corners "natively", in addition to rounded corners, will give Web developers another option in designing their Web pages (not just for Material Design's purposes).  Perhaps this can be implemented using additional CSS properties (e.g., `cut-border-radius`) that work analogously to `border-radius`.

**Comment by SebastianZ** [comment]
That is already defined in the Backgrounds and Borders 4 spec. as [`corner-shape: bevel;`](https://drafts.csswg.org/css-backgrounds-4/#corner-shaping). (And there are even a few more corner shapes you can specify.

Sebastian

**Comment by peteroupc** [comment]
Thanks for pointing that out.  In that case, I find it strange that the article I cited didn't cite `corner-shape: bevel` or the other recent standardization efforts of the W3C with respect to CSS border styling, or whether the Material Design team was much aware of them.  Unfortunately, there is no feedback or comment page in that article, so getting them aware of this issue page can be hard.

**Comment by SebastianZ** [comment]
The main reason why the article doesn't mention `corner-shape` is probably that the Material Design team wanted to base their shape system on existing technology - and `corner-shape` is not implemented in any browser yet, unfortunately (and the specification even claims "not ready for implementation").

But it could also be that they didn't know about the standardization efforts. Luckily, I saw that the article does have a comment form below, so I mentioned it there.

Sebastian

**Comment by fantasai** [comment]
Yeah, css-backgrounds-4 isn't even FPWD, it's mostly just brainstorming and bits of resolutions with half-baked spec text... It needs a lot of work to grow up into a real spec. :)

**Comment by SelenIT** [comment]
Maybe something more flexible like allowing to use `<basic-shape>` values as `border-image-source` could simplify creating boxes with differently shaped corners without requiring tons of new keywords for each of them?

**Comment by bradkemper** [comment]
Don’t forget that you can use border-image to create whatever corners you like, and can use SVG for the image if you want. I’m not saying we shouldn’t have ‘corner-shape’, but ‘border-image’ is available and reliable already.

**Comment by fantasai** [comment]
`corner-shape: [ round | angle ]{1, 4}` edited in.

**Comment by yisibl** [comment]
Why was notch/scoop deleted? I think they are very useful.
![image](https://user-images.githubusercontent.com/2784308/80737310-e76e6f00-8b45-11ea-8037-5c2af8a097f9.png)
https://css-houdini.rocks/corner-shape/
