### ISSUE TITLE
Web SQL Database and Firefox

### ISSUE THREAD

**Issue by Zefling** [w3c/csswg-drafts#3459]
Currently, the work on the spec of  Web SQL Database are stopped. But, with the dead of EdgeHTML, Firefox will be the only one browser not support this dead spec... I find this situation strange.

https://caniuse.com/#feat=sql-storage

What is the W3C's point of view?

**Comment by upsuper** [comment]
This is definitely unrelated to CSS WG... I have no idea where to ask this, though...

**Comment by Zefling** [comment]
Oups, sorry.

**Comment by frivoal** [comment]
This is indeed out of scope for the CSSWG, but here are some pointers.

The https://www.w3.org/TR/webdatabase/ specification was produced (then retired) by the Web Application working Group. That group no longer exists, but it's successor is the [Web Platform Working Group](https://www.w3.org/WebPlatform/WG/). It's [github](https://github.com/w3c/WebPlatformWG) or its [mailing list](https://lists.w3.org/Archives/Public/public-webapps/) is probably a good place to ask.

In the end though, it's not really about what the W3C wants to do, but what its members and the implementers want to do, as W3C is  a venue to facilitate the discussion, not the actual decision maker. In light of the recent [Magellan](https://www.slashgear.com/sqlite-magellan-bug-affects-chrome-based-browsers-thousands-of-apps-16558106/) security problem, I suspect Mozilla is [quite happy about their decision not to support Web SQL](https://twitter.com/pcwalton/status/1073756784836263936), so I'd be surprised if they changed their mind. But you should ask them, either talking by Mozilla directly, or in the previously mentioned Web Platform Working Group.
