### ISSUE TITLE
[css-syntax] "Drop first @charset rule" seems unneeded.

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3464]
In the comments in <https://github.com/WICG/construct-stylesheets/issues/84>, @bzbarsky expresses some confusion as to the point of the "drop the first @charset rule" in the "parse a stylesheet" algorithm. After some review, I agree with him: I'm also confused!

I think this was added to express the previous Blink behavior of keeping @charset rules in the CSSOM, except for the first which was dropped.  (Firefox apparently never dropped the first one...)  Later, I went more scorched-earth and just declared that there was no such thing as a @charset rule (just an encoding declaring that happened to resemble one...), and so *all* @charset rules should be dropped from the CSSOM.

Since browsers seem to follow the newer Syntax advice to just drop all @charset rules, we can eliminate the explicit "drop first" rule from the spec.

Agenda+ to confirm with WG, as this spec is CR. ^_^  (I should also probably ask for republication, if I don't already have a pending permission...)

**Comment by fantasai** [comment]
(Fwiw, since it's CR, you'll need a DoC and a Changes list to publish.)

**Comment by tabatkins** [comment]
Tested in <https://github.com/web-platform-tests/wpt/commit/388ba3a049a3473b1945b9f8f81e9d6e342a249e>
