### ISSUE TITLE
[css-sizing] Percentage margins and intrinsic sizes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#347]
Testcase: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4345

Gecko renders as an author would expect: float is shrink-wrapped around its content with no overflow, and margins are 25% of their containing block. Blink and Edge overflow.

According to author > implementer > spec, we should all follow Gecko's lead here, but that requires buy-in from everyone else. :)

**Comment by MatsPalmgren** [comment]
Here's a testcase with some examples - the box at the top is a flexbox and the second is a block, both with percentage padding, and the two boxes at the end are grids with percentage padding/margin and percentage `grid-gap` and grid-item percentage padding:
https://people-mozilla.org/~mpalmgren/tests/grid/percent-intrinsic-sizing.html
and here's how it renders in Firefox Nightly and Chrome Canary respectively:
https://people-mozilla.org/~mpalmgren/tests/grid/percent-intrinsic-sizing.png
