### ISSUE TITLE
[css‑grid][selectors‑4] How does the Column combinator (`||`) interact with other specifications (mainly CSS Grid)?

### ISSUE THREAD

**Issue by ExE-Boss** [w3c/csswg-drafts#3471]
- https://drafts.csswg.org/selectors-4/#the-column-combinator
- https://drafts.csswg.org/css-grid/ (https://drafts.csswg.org/css-grid-2/)

How does the Column&nbsp;combinator (`||`) interact with CSS&nbsp;Grid?

And what about flexbox and the multi&#x2011;column layout?

**Comment by SelenIT** [comment]
Currently, the spec says that

> Column membership is determined based on the semantics of the document language only: whether and how the elements are presented is not considered.

I'm afraid that the general logic [regarding selectors that depend on layout](https://wiki.csswg.org/faq#selectors-that-depend-on-layout) would prevent applying column combinators to grid items. Regarding (multi-line) flexbox, there are no connection between items in different flex lines, so column combinator is likely not relevant there. And regarding CSS columns (and similar future fragmentation mechanisms), maybe reusing the pattern of the [page selectors](https://drafts.csswg.org/css-page-3/#page-selectors) would be more suitable for them?

**Comment by ExE-Boss** [comment]
Well, the column combinator can’t be used to disable the grid that it’s used to select columns inside of.

**Comment by SelenIT** [comment]
But something like this would be potentially possible:

```
.grid-item-1 {
   grid-column: 1 / span 1;
}
.grid-item-1 || .grid-item-2 {
   grid-column: 5 / span 1;
}
```
In theory, this could be resolved by restricting the subset of CSS properties that can be applied to this selector, but this would probably mean too much complexity for both spec and implementation...
