### ISSUE TITLE
[css-text-3] Normatively reference Unicode

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3474]
We might want to normatively reference Unicode, to pull in all its mandatory rendering requirements (like Arabic shaping, correctly handling ZWJ, etc.).

**Comment by fantasai** [comment]
Added

> CSS is built on [UNICODE]. UAs that support Unicode must adhere to all normative requirements of the Unicode Core Standard, except where explicitly overridden by CSS. UAs that use a different encoding are not explicitly supported by the CSS specifications; they are, however, expected to fulfill the same text handling requirements by assuming an appropriate mapping between that encoding and Unicode.

Agenda+ to request review.

**Comment by tabatkins** [comment]
Sounds good to me, and I like the wording.
