### ISSUE TITLE
[css-color] What happens in color() if you pass numbers to a named colorspace, or vice versa? 

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#348]
I'm rewriting the `color()` section a bit, and I realized that error-handling for passing the wrong *type* of argument to `color()` isn't defined.  That is, what if you write `color(rec2020 "foo")`?

Similar cases: `color(pantone .1 .2 .3)` (expects a string, gets numbers), and `color(pantone "foo")` (correctly gets a string, but an unknown value).

I think the latter two should maybe fallback?  The first one could maybe do that too, but alternately it could just fill in all channels with 0.

**Comment by svgeesus** [comment]
I would say  for all these type-error, non-matching cases (also one where the colorspace identifier has not been declared in an @profile) it goes to the next fallback (rather than be discarded, for example).

It might be an idea to declare that there is an implicit final fallback and that the result is transparent black. Or would that prevent people doing their own fallback for non-css-4-color UAs, like:

border-color: #357;
border-color: color(whatever they type here);

I think that would be okay.

**Comment by svgeesus** [comment]
btw there is more than one pantone color set, so just the name 'pantone' is not a good one for examples.

**Comment by tabatkins** [comment]
> I would say for all these type-error, non-matching cases (also one where the colorspace identifier has not been declared in an @profile) it goes to the next fallback (rather than be discarded, for example).

kk, that works for me.

> It might be an idea to declare that there is an implicit final fallback and that the result is transparent black. 

I just opened a separate issue for this.

> Or would that prevent people doing their own fallback for non-css-4-color UAs, like:

Can't detect these errors at parse-time anyway, so you have to provide your final fallback twice: once in a separate declaration for legacy UAs, and once at the end of `color()` for modern UAs.

> btw there is more than one pantone color set, so just the name 'pantone' is not a good one for examples.

Cool, can you give me a decent example name?  I haven't written any named-color examples in the spec yet, but I need to.

**Comment by svgeesus** [comment]
see http://www.pantone.com/graphics?from=topNav
example names might be Pantone Metallics, Pantone Pastels & Neon, Pantone Process.
useful tool for examples http://www.pantone.com/color-finder

**Comment by tabatkins** [comment]
thanks! wrt to the main topic of this issue, I made them all do fallback. Providing too many or too few numeric arguments is still fine (ignored or defaulted to 0), but all the other mistakes trigger fallback.

**Comment by bradkemper** [comment]
@svgeesus all the Pantone color names are unique though, right? So you could have an unambiguous `pantone "OBQO-C"` which would be the process color simulation of `pantone "128 C"`. 

By the way, "Pantone" is a registered trademark. Not sure what the licensing situation is, or if their legal team would allow it to be used in all lower case.

**Comment by bradkemper** [comment]
In their chip books, they put the ® (r) on every single chip.

**Comment by svgeesus** [comment]
> By the way, "Pantone" is a registered trademark.
Yes, I am aware of the Pantone IPR situation, and it seems that they may be open to clarifying and re-evaluating their earlier position a little.
