### ISSUE TITLE
[css-color] What to do if there's no valid fallback?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#349]
The current spec doesn't define what color to resolve `color()` to when all the options cause fallback.  For example, what do you get from `color(nonsense-colorspace .1 .2 .3)`?

I think the only two reasonable options are opaque black, or transparent black.  Given that the opacity defaults to 100% if omitted, I'm leaning toward opaque black.  

On the other hand, we default to "transparent" in similar cases, like `image()`, which represents a transparent image with no intrinsic dimensions if all the alternatives are invalid, exactly as if you'd put `image("nonsense", transparent)`.  This might be explainable by the different assumed contexts - most elements don't have background images so defaulting to invisible is fine, but most colors are used to make things visible so defaulting to an opaque color is better.

**Comment by svgeesus** [comment]
I agree there should be a defined fallback and that black is the obvious one. On balance, I like the opaque black better - if it is an authoring mistake, it is easily spotted and corrected by them. Invisible ink is just mysterious to the author trying to debug their stylesheet..

**Comment by tabatkins** [comment]
k, i used opaque black

**Comment by frivoal** [comment]
I don't know if it would be the right answer, but I think there are more alternatives to consider than black and transparent black.

What about using currentColor? This might not be a great fallback when used as a background color, but neither is black, and when used as a foreground color, it might end up being useful more often than black is.

**Comment by Crissov** [comment]
I believe @frivoal is right, `currentcolor` would be the desired fallback for foreground properties like `color` and `border-color`, but `transparent` would be more appropriate for `background-color` etc. Using `black` (or `white` or `transparent`) everywhere would be harmful in more cases. What you really want is something like partial `inherit` or `default`.

**Comment by frivoal** [comment]
Maybe we want to define something like current-background-color. In general, that'd be useful. and if we had that, maybe the fallback of color() should be context sensitive, be either currentColor or current-background-color depending on the property it's used it. Or maybe that's overkill, I'm not sure.
