### ISSUE TITLE
[css-scroll-anchoring-1] Should changes to 'overflow-anchor' invalidate the scroll anchor?

### ISSUE THREAD

**Issue by eqrion** [w3c/csswg-drafts#3494]
#3476 adds some more details for when scroll anchors should be invalidated.

Should changes to the 'overflow-anchor' property invalidate the current scroll anchor?

I think that makes sense, as a change to 'overflow-anchor' can change the effective anchor node. However, we don't invalidate after every property that could change the effective anchor node, such as 'border' (#3321).

I guess maybe changing 'overflow-anchor' has a high intention that you want to change the effective anchor node?

cc @dholbert @dbaron @skobes

**Comment by chrishtr** [comment]
I don't think this is controversial at all, let's just make the change. PR in review.

**Comment by chrishtr** [comment]
Update: I reverted the original pull request here; reasoning in the PR:

https://github.com/w3c/csswg-drafts/pull/4692
