### ISSUE TITLE
[css-lists][css-pseudo] the 'content' property should apply to ::marker

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3499]
The spec for the [`content`](https://drafts.csswg.org/css-content-3/#content-property) property says that it applies to [tree-abiding pseudo-elements](https://drafts.csswg.org/css-pseudo-4/#treelike).  [`::marker`](https://drafts.csswg.org/css-pseudo-4/#marker-pseudo) is a tree-abiding pseudo-element, however it explicitly excludes the `content` property.

I think this is a mistake, the `::marker` pseudo would be much more useful if `content` could be used on it. Making `::marker` more like `::before/::after` would also make it easier to understand, to specify and implement, since it wouldn't need to be treated specially.  I think this would benefit all stake holders:

- spec authors: could stop duplicating parts of `content` in [list-style-image](https://drafts.csswg.org/css-lists-3/#image-markers) and [list-style-type](https://drafts.csswg.org/css-lists-3/#text-markers) and instead share more spec text for `::marker/::before/::after`.
- implementors: instead of writing [a lot of specialized code](https://searchfox.org/mozilla-central/source/layout/generic/nsBulletFrame.cpp) for "list markers", we could re-use the code we already have for `::before/::after`to also handle `::marker`. This means less code to write and maintain.
- authors: adding support for the `content` property would make `::marker` significantly more powerful.
- end users: hopefully, the improvements in all levels above will result in richer content and less buggy and more compatible browsers for users to enjoy.

**Comment by frivoal** [comment]
WFM. And then we just define that the `content: normal` (which is the initial value) computes to do the right thing based on the list-style-* properties.

**Comment by emilio** [comment]
FWIW there's a precedent for `content` not applying to tree-abiding pseudos, like ::placeholder.

**Comment by ExE-Boss** [comment]
In all current major browsers, string `attr()` values are fully supported on the `content` property.

It’s the fallback value and typed `attr()` values that are unsupported.

**Comment by patrickdark** [comment]
Hmm... I was thinking of https://bugzilla.mozilla.org/show_bug.cgi?id=1481150, where `content: attr()` should generally work on everything.

**Comment by fantasai** [comment]
@MatsPalmgren If you have this implemented, I'm happy to add it to the spec. But let me know if you think it'll add a hard dependency on defining marker layout? In which case maybe I'd suggest adding it as a note of future expectations for when we actually have a definition of marker layout...

**Comment by MatsPalmgren** [comment]
@fantasai we've implemented it by following the same code path as for `::before/::after` in box construction / layout (when `content` is specified). We've added a few tweaks for `list-style-position:outside` to make it compatible with our old layout that we should specify (in css-lists). We haven't implemented  `position:marker` at all and I believe it wouldn't be web-compatible as currently [specified](https://drafts.csswg.org/css-lists/#position-marker) because "counts as absolutely positioned" would give it the wrong stacking level for painting. We also haven't implemented the `marker-side` property (yet). I'll file a separate spec issue with the details on how we do layout for `outside`. Layout for `inside` should work pretty much exactly as for `::before/::after`.

If `content` isn't specified, then we still use our legacy layout code (aka nsBulletFrame). We've only updated it to use the new `list-item` counter and use `::marker` styles. My goal for the future is to generate a content node from `list-style-type` etc and then use the same layout code for everything (and then remove nsBulletFrame).

I don't think you need to block this on layout details for `list-style-position:outside` since that's under-specified  anyway at the moment and the tweaks we added are fairly minor and not really related to the `content` property per se.

**Comment by fantasai** [comment]
@MatsPalmgren Yeah, `position: marker` and `marker-side` are quite explicitly marked as DO NOT IMPLEMENT in the spec. :) https://www.w3.org/TR/css-lists-3/#positioning-markers https://drafts.csswg.org/css-lists-3/#positioning They'll probably be deferred to L4 for the next publication...

**Comment by MatsPalmgren** [comment]
@fantasai I filed #3771 with some more details on our new `list-style-position:outside` layout and some thoughts on `position:marker`.

**Comment by fantasai** [comment]
@MatsPalmgren - Tab and I cleaned up the Lists spec last week and defined the content interaction more precisely in https://drafts.csswg.org/css-lists-3/#content-property so I think this should be pretty straightforward to add now. Agenda+ to confirm incorporating it into that section and adding it to the list of properties in css-pseudo-4.

**Comment by fantasai** [comment]
Was also noted that we should definitely add some examples to the spec for common cases like 2.4.7 list numbering.
