### ISSUE TITLE
[css-custom-properties] Document :host, :host-context styling, scoping

### ISSUE THREAD

**Issue by kevinSuttle** [w3c/csswg-drafts#350]
https://drafts.csswg.org/css-variables/
http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/#toc-style-host

**Comment by tabatkins** [comment]
These are all defined in the [Scoping spec](https://drafts.csswg.org/css-scoping/). If you ever have trouble finding something, the [CSS Index](https://drafts.csswg.org/indexes/) can often help with that; in particular, a Ctrl+F for ":host" would lead you right to where it's defined. ^_^
