### ISSUE TITLE
[css-shadow-parts][css-pseudo] ::part* and *::before* and *::after* pseudo elements

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3510]
(Split from issue #3467, reported by @stefsullrew)

It appears the `::before` and `::after` pseudo elements/selectors do not function with *::part*. Is this intentionally blocked, if so why? If not are there plans to add this functionality in the future?

```
// add an asterisk prefix to the title part
x-foo::part(title)::before {
    content: '*';
    color: red;
    margin-right: 0.25rem;
}
```

**Comment by lilles** [comment]
That sounds like a bug. Also, iterating more on that you should probably be able to say:

::slotted(component)::part(title)::before

but not (only possible if a slot element is exposed as a part):

part(title)::slotted(div)::before

**Comment by lilles** [comment]
For reference, the spec says ::before/::after is allowed after ::part: https://drafts.csswg.org/css-shadow-parts/#part

**Comment by fergald** [comment]
This was a chrome implementation issue that has now been fixed (along with ::placeholder). Web Platform tests have also been added for all 3.

**Comment by frivoal** [comment]
(marking as invalid + commenter satisfied as that this was not a spec bug, and that the implementation bug was resolved the way the commenter asked.)
