### ISSUE TITLE
Typo in Conic Gradient

### ISSUE THREAD

**Issue by derekjohnson** [w3c/csswg-drafts#3512]
Not sure what the short name is, sorry. Possibly [css-images-4]?

Example 13 at https://www.w3.org/TR/css-images-4/#example-e6ba6030 says "the only effect of the center center is a 2D translation of the gradient". Should it not be "the only effect of the center position is a 2D translation of the gradient"?

**Comment by svgeesus** [comment]
Thanks for the bug report!

The error has [already been corrected in the Editor's Draft](https://drafts.csswg.org/css-images-4/#example-0a9f6351)
