### ISSUE TITLE
[css-text-3] unclear detail of white space collapsing?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3513]
[Section 4.1](https://drafts.csswg.org/css-text-3/#white-space-phase-1) says:

> Any space immediately following another collapsible space [...] is collapsed to have zero advance width.

Shouldn't that be:

> Any **collapsible** space immediately following another collapsible space [...] is collapsed to have zero advance width.

I'd rather be a little redundant to avoid suggesting that sequences mixing collapsible and non collapsible space do collapse.

**Comment by fantasai** [comment]
It's pretty clear from the wording introducing this particular list. Also if we were to be redundant here, we'd need to be redundant in every other item of this list. Given that I think I lean towards not making the change here...

**Comment by frivoal** [comment]
I wondered about this bit of sentence because I wanted to be sure what the spec said for cases like
```html
<span style=white-space:pre>a </span><span style=white-space:normal> b</span>
```
or
```html
<span style=white-space:normal>a </span><span style=white-space:pre> b</span>
```
collapse or not? I think the answer is not to collapse in both cases, but with the current phrasing, I wasn't 100% sure for case 2.

> we'd need to be redundant in every other item of this list

Well, the entries on this list are supposed to be talking about collapsible spaces, so if there's only one mention of spaces in one entry, then surely it's about collapsible spaces. But this entry talks about spaces **and** collapsible spaces, and I couldn't be sure whether the commission of collapsible in one of the references but not the other was just because it was "obvious" from context, or if it was meant to draw a contrast. Hence filing this bug. The presence of the word "another" gives a good hint, so I won't be too sad if we close this as wontfix, but I'd prefer minimizing the chances of misunderstanding.

**Comment by fantasai** [comment]
I'd have to rewrite all the entries in that entire list. :/
