### ISSUE TITLE
[css-text-3] suppressing wrap opportunites next to replaced elements and atomic inlines

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3514]
[Section 5.1 of css-text-3](https://drafts.csswg.org/css-text-3/#line-breaking) says this:

> The line breaking behavior of a replaced element or other atomic inline is equivalent to an ideographic character (Unicode linebreaking class ID [UAX14]), and additionally, for Web-compatibility, introduces a soft wrap opportunity between itself and any adjacent U+00A0 NO-BREAK SPACE character.

This seems fine, including the bit about the extra wrap opportunity as that's needed for compat. But as far as I can tell, implementations not only do that, but also introduce a soft wrap opportunity between the atomic-inline-treated-as-an-ideograph and **any** break-suppressing character, such as NARROW NO-BREAK SPACE (`&#8239;`) or  WORD JOINER (`&#8288;`), not just NBSPs.

It's pretty annoying to have characters in unicode that are explicitly about line breaking opportunities, and not be able to use them.

If this is unfortunately needed for web compat, the spec should say so (and maybe add a note telling authors who actually want no break how to get that).

If it is not a compat problem, I'm thinking of adding a note in the spec indicating that this extra wrapping opportunity is only for NBSP, writing a test case to check that, and filing bugs against browsers.

**Comment by fantasai** [comment]
Just write a testcase. This was already discussed. We had to make NBSP an exception.
