### ISSUE TITLE
[css-text-3] computed value of word-spacing:normal

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3515]
[the propdef table of word-spacing](https://drafts.csswg.org/css-text-3/#word-spacing-property) says:
> Computed value: the keyword normal or an absolute length

The definition of normal says:

> Computes to zero.

These are contradictory. I suspect we want to align with `letter-spacing`. In that case, we should keep the prose, fix the propdef table, and add:
> For legacy reasons, a computed word-spacing of zero yields a resolved value (getComputedStyle() return value) of normal. 

If not, we should change the prose to "behaves as zero" instead of "computes to zero".

**Comment by fantasai** [comment]
No, this is a case where it really does compute to zero. Fixed the Computed value line. (letter-spacing was different because in CSS2 0 and normal had specified different behaviors, but that's not true for word-spacing.)

**Comment by fantasai** [comment]
(I'm guessing this error was introduced when we revamped the computed value lines in September.)

**Comment by fantasai** [comment]
(I'm guessing this error was introduced when we revamped the computed value lines in September.)

**Comment by frivoal** [comment]
tested in https://github.com/web-platform-tests/wpt/blob/master/css/css-text/parsing/word-spacing-computed.html
