### ISSUE TITLE
[css-text-3] remove unhelpful references to some line breaking classes

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3516]
> Regardless of the white-space value, lines always break at each preserved forced break character: thus for all values, line-breaking behavior defined for the BK, CR, LF, CM, NL, and SG line breaking classes in [UAX14] must be honored.

However:
*  The CR class is just U+0D, which is already handled in Section White Space Processing Details. Doesn’t that make this statement moot for that class?
* The LF class is just U+0A, which isn’t preserved “regardless of the white-space value”. Also, it is adequately described in the white space section for the cases where it is not discarded.
* How is CM a forced break?
* How is SG a forced break? Also, UAX 14 says: The use of this line breaking class is deprecated. 

=>  Suggestion: remove CR LF CM and SG from this sentence (keep BK and NL).

**Comment by fantasai** [comment]
Yes, I think you're right.

**Comment by frivoal** [comment]
That looks like no change in behavior, just text clarification. OK to land an edit without a WG resolution?

**Comment by fantasai** [comment]
Yes. :)
