### ISSUE TITLE
[css-text-3] missing reference to ZWJ

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3517]
[css-text-3 section 5.1](https://drafts.csswg.org/css-text-3/#line-break-details) says:

> Except where explicitly defined otherwise (e.g. for line-break: anywhere or overflow-wrap: anywhere) line breaking behavior defined for the WJ, ZW, and GL line-breaking classes in [UAX14] must be honored. 

Shouldn’t that include the ZWJ class as well?

**Comment by fantasai** [comment]
Yes. That class didn't exist in the 2013 edition...
