### ISSUE TITLE
[css-text-3] Out of Flow elements and word boundaries

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3518]
Just like we clarify (in [css-text-3 section 5.1](https://drafts.csswg.org/css-text-3/#line-break-details)) that out of flow elements don't create wrapping opportunities, we probably also should clarify that they don't create word boundaries for the purpose of the [text-transform property](https://drafts.csswg.org/css-text-3/#text-transform-property) either.

Related:
https://github.com/web-platform-tests/wpt/blob/master/css/css-text/text-transform/text-transform-capitalize-033.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1508066
https://bugs.chromium.org/p/chromium/issues/detail?id=906369
https://bugs.webkit.org/show_bug.cgi?id=191807

cc: @emilio, @mstensho

**Comment by fantasai** [comment]
Added “Out-of-flow elements and inline element boundaries must not introduce a text-transform word boundary and must be ignored when determining such word boundaries.”

Closing out as Editor Discretion based on the above discussions, unless @litherum objects.
