### ISSUE TITLE
[css-mediaqueries] prefers-color-scheme and printing

### ISSUE THREAD

**Issue by quasicomputational** [w3c/csswg-drafts#3522]
Spec: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme (drive-by note: the section title is a copy-pasto)

What should the interaction of prefers-color-scheme and printing be? I'm specifically worried that 'prefers-color-scheme: dark' might naively cause printer ink worth more than the GDP of Hampshire to be used.

Some options off the top of my head, but I'm sure there are others:
* When printing, recommend (require?) that 'prefers-color-scheme: light' matches, because paper has a 'light' colour scheme. Is there such a thing as light-on-dark printing where this would be inappropriate?
* Have no preferred colour scheme when printing (a no-list of inappropriate media), or perhaps for all media except screens (a yes-list of appropriate media); queries involving prefers-color-scheme should always be false in those cases. This has a good forwards compatibility story if something else gets decided later.

**Comment by MatsPalmgren** [comment]
I think multiple UAs will soon ship this feature, so it would be good to have a decision on this.

**Comment by tabatkins** [comment]
Ultimately this is a UA matter; this MQ's resolution is based on how the UA chooses to represent the user's needs.

I feel like printing should prefer a light color scheme, regardless of what people prefer to look at on their screen. A note in that section saying so seems pretty reasonable?

**Comment by MatsPalmgren** [comment]
Seems reasonable to me.

**Comment by freund17** [comment]
I don't see the reason for having `prefers-color-scheme` behave differently, while in a printing context.
There already is `@media print` to detect, whether we are printing or not.
But the users color-preference did not change.

I understand the concern of wasting ink, but that has always been the case when developers/designers did not handle the `print`-case.

I have the feeling we are trying to be to clever here and making everything unnecessarily more complicated...

**Comment by grorg** [comment]
I'll update the spec.
