### ISSUE TITLE
[css-flexbox] Definite sizes section could use clarification

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#3531]
https://drafts.csswg.org/css-flexbox/#definite-sizes

Upon re-reading this section, I have a few suggestions for it:
* Item 3 is only referring to flex items who are stretch-aligned, I believe. Also, instead of sayings "items ... are ... definite" it should say "cross-sizes of items" are definite.
* Item 1 is not necessary, I believe. It follows automatically from item 3 / stretch handling combined with the fact that flex lines in single-line flex containers are sized to the container. So it seems this could be turned into a note / optimization opportunity (because you can avoid an extra layout pass in this case)

cc @fantasai

**Comment by tabatkins** [comment]
It looks like Elika's edit addresses your first bullet point.

I just pushed an edit handling your second; you're right, once we genericize the language in Item 3, it covers the Item 1 case entirely, so I just moved Item 1 to being a note.

**Comment by fantasai** [comment]
The second commit https://github.com/w3c/csswg-drafts/commit/6dd2edc2724d78b4d14d7c4e1bfaa7fcae01b5be is actually not editorial. We depend on the stretched size being definite when sizing the item in [step 3](https://www.w3.org/TR/css-flexbox-1/#algo-main-item), so we can't collapse these two points.

**Comment by fantasai** [comment]
[Two issues reported in this issue: one was accepted as editorial, the other rejected as invalid.]

**Comment by cbiesinger** [comment]
sounds good.
