### ISSUE TITLE
[css-box-3] Border box missing scrollbar in calculation?

### ISSUE THREAD

**Issue by TremayneChrist** [w3c/csswg-drafts#3536]
https://drafts.csswg.org/css-box-3/#border-box

![image](https://user-images.githubusercontent.com/1519516/51477163-7b685d00-1d7f-11e9-8a4e-2d15c76e8b75.png)

"The four sides of the border edge together define the box’s border box, which contains the box’s content, padding, and border areas."

What happens when scrollbars sit between the **padding edge** and **border edge**?

![box](https://user-images.githubusercontent.com/1519516/51476884-b1591180-1d7e-11e9-9dd8-aac402eaeb8d.png)

**content** + **padding** + **border areas** no longer adds up to the actual **border box**, as **content** is reduced to fit the **scrollbar**.

**Comment by jonjohnjohnson** [comment]
Your quote shows the word "contains" not "adds up"? Implementations are already consistent in how they treat these boxes, with and without scrollbars. And the content box might not be reduced depending on `box-sizing` [value](https://drafts.csswg.org/css-ui-3/#box-sizing) and non-auto values for `width` allowing the border box to actually grow if "classic" scrollbars are present. There's also language in the upcoming [css-overflow-4](https://drafts.csswg.org/css-overflow-4/#scollbar-gutter-property) around `scrollbar-gutter` that you may find informative. I think across other modules these interactions are well documented, but I'm guessing you're thinking they should also be linked/noted here?

**Comment by fantasai** [comment]
The calculations are covered in https://drafts.csswg.org/css-overflow-3/#scrollbar-layout and also as @jonjohnjohnson points out, the spec does say "contains" which is strictly true. :)

Closing as invalid/out-of-scope.
