### ISSUE TITLE
[css-ui][css-pseudo] clarify outline's behavior on pseudo elements

### ISSUE THREAD

**Issue by mattdrose** [w3c/csswg-drafts#3539]
https://drafts.csswg.org/css-ui-4/#outline-props

The outlines spec isn't clear when it comes to pseudo elements. This means that behaviour differs greatly between browsers.

Safari: Outline doesn't affect pseudo elements
Firefox: Outline will expand to include pseudo elements
Chrome: Outline will only include pseudo elements when: 1) the block is relative 2) the outline-style is `auto`

Codepen example: https://codepen.io/mattdrose/pen/OreqYg

I especially find Chrome's behaviour odd, and thus [opened an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=923504#c3). Triaging is difficult, however, since the spec is so loose on expected behaviour—you can't detect what is and isn't a bug.

I know this isn't the only issue of it's kind (outlines affect on [descendant's also varies](https://github.com/w3c/csswg-drafts/issues/2846) is also inconsistent). I personally believe that narrowing down outlines affect on pseudo elements and descendants would help browsers, developers, and end users alike.

**Comment by Loirooriol** [comment]
I don't think tree-abiding pseudo-elements should be treated in any special way. In your example you use `position: absolute`, some browsers render the outline ignoring out-of-flow descendants and some render it bigger. The exact behavior is undefined, but should be the same whether you have a pseudo-element or a normal descendant.
