### ISSUE TITLE
[css-align] editorial: typos in §10. Appendix A: Static Position Terminology

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3548]
https://drafts.csswg.org/css-align-3/#staticpos-rect
> The static positions of a block-level box are defined in [CSS2] Chapter 10

Is the plural "positions" intentional? If so, it's not clear to me what it means. I think the term you're looking for is "static position" (or "static position rectangle"). (this occurs in Block Layout and Inline Layout)

> static positionCSS2§10.6.4). 

Looks like it was meant to be a link? (under Block Layout)

> and positioned at its inline-start static position

Is missing a period to end the sentence. (under Inline Layout)

> See [[!css-flexbox-1#abspos-items]]. 

Looks like it was meant to be a link? (under Flex Layout)

> ... the grid-placement properties instead establishes its static position rectangle.

The phrasing seems odd to me.  Shouldn't the "instead" be at the end? (under Grid Layout)

> 	See [[!css-grid-1#static-position]]. 

Looks like it was meant to be a link? (under Grid Layout)

It seems all direct links to a CSS2 section here goes to https://www.w3.org/TR/CSS21/...
I think it would be better to link to https://www.w3.org/TR/CSS22/... instead, since the former displays a big red warning box.

**Comment by MatsPalmgren** [comment]
>The static positions of a inline-level box ...

an? (under Inline Layout)

**Comment by tabatkins** [comment]
> Is the plural "positions" intentional?

Yes. See [CSS2 10.3.7](https://drafts.csswg.org/css2/visudet.html#abs-non-replaced-width), which defines a static position for each inset property.

> [link, period, link, link]

Fixed.

> [instead]

It can go on either side, but sure, we moved it to the end.

> [pointing to CSS2.2]

We've updated the links to point to /TR/CSS2. This does need repub, tho.

> "a inline"

fixed
