### ISSUE TITLE
[css-values] Define value syntax that limits <integer>, <number>, <length>, etc. to ranges

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#355]
Many properties only accept positive values.  Negative values are illegal, and are parse errors.  This is currently only defined in prose for the relevant property.  Examples: width, height, line-height.

In contrast, other properties have logical bounds, but values outside these bounds are parsed as normal and only clamped at used value time. Examples: opacity, numeric parameters in color functions.

I'm sure it would be useful for both authors and implementers if the property value syntax explicitly indicated whether negative values would be a parse error or not.  That requires new value types in [CSS Values & Units](https://drafts.csswg.org/css-values/).

I'm not sure if there are any other common "illegal value" restrictions currently defined in prose, but it's worth looking around to see if there are, and if they can also be standardized into the value definition syntax.

**Comment by tabatkins** [comment]
Well, "positive" is only allowed for integers, not numbers or dimensions, because it constitutes an open range otherwise, which is informally disallowed.  We do use non-negative (sometimes paired with prose that floors it at some non-zero value), but that's harder to express easily.

**Comment by AmeliaBR** [comment]
Mathematically, "positive" usually means zero or greater, which is what I was thinking of, although depending on how the CSS parser handles -0, you might need some extra text in there.

"non-zero positive integer" would be another possible type, if that's actually required anywhere.

**Comment by frivoal** [comment]
> "non-zero positive integer" would be another possible type, if that's actually required anywhere.

It is: https://github.com/w3c/csswg-drafts/issues/341#issuecomment-234938653

**Comment by tabatkins** [comment]
> Mathematically, "positive" usually means zero or greater, which is what I was thinking of, although depending on how the CSS parser handles -0, you might need some extra text in there.

That's not really true in my experience? Zero is neither positive nor negative, and there's a lot of stuff backing that up: the relatively common usage of "non-negative" in precise technical contexts, the implementations of sign() functions in various languages, the fact that +0 and -0 are mathematically equivalent, etc.  CSS has been pretty precise about this, because we've gotten bug reports about "why isn't 0 valid?" when we were imprecise and just used "positive".  At best, whether 0 is considered "positive" or not is ambiguous and context-sensitive.

**Comment by AmeliaBR** [comment]
> At best, whether 0 is considered "positive" or not is ambiguous and context-sensitive.

OK, I agree that a completely unambiguous terminology would be better. But the rest of my suggestion still stands: can we define `<non-negative-integer>`, `<non-negative-length>`, etc., data types, so that these restrictions do not have to be defined in prose?

**Comment by fantasai** [comment]
I don't have a problem with this in theory, but in practice <non-negative-integer> eats up a large part of the measure and grammars with more than a handful of possible value components, it triggers more wrapping and makes them harder to read. So while defining these limits in prose is not ideal, I'm less than enthusiastic about adopting these new types. :(

**Comment by tabatkins** [comment]
We can go with shorter names; `<p-integer>`, `<nn-integer>`, etc. Unsure if that's worthwhile.

**Comment by AmeliaBR** [comment]
Yes, I'm certainly not stuck on the syntax. I just want the full parsing requirements to be unambiguously defined by the grammar.

Another approach would be to express it numerically, something like `<length >= 0>`, `<integer > 0>`, except without `>` characters!  `<length gte 0>` and `<integer gt 0>`?

**Comment by AmeliaBR** [comment]
The discussion on clamping column width values (#1741) made me think of this again.

One final option for terminology: Take a cue from WebIDL, and use "unsigned" for values that cannot be negative. So it would be `<unsigned-integer>`, `<unsigned-number>`, `<unsigned-length-percentage>`, etc.  For the rare cases: `<non-zero-unsigned-integer>`.

That said, I still think I prefer an explicit constraints syntax, like `<length min 0>`, as it is easier to understand on its own.

Regardless of the syntax, I still would very strongly like to add this option to the CSS grammar, so that all parser constraints on values can be expressed in the grammar.

So, I'm requesting this for the WG agenda, with the following questions for discussion:

- Should the [CSS Value Definition Grammar](https://www.w3.org/TR/css3-values/#value-defs) be expanded to allow it to express all parser-level constraints on allowed values?

- If so, how should the constraints be expressed?
  1. By adding new data type names for all existing constrained types (non-negative numbers, non-negative lengths, strictly positive integers, etc.)?
  2. Or, by adding a generic way of indicating maximum and minimum values for any numeric type?

If we can get a resolution on those points, then we can bikeshed the exact syntax in a more focused way.

**Comment by AmeliaBR** [comment]
I'd like to get a resolution on this at the February F2F.

Specifically, I'm advocating for the syntax that uses SGML-style attributes (`<number min=1 max=10>`).  It's a familiar syntax for pretty much anyone who is working with CSS, it is explicit about the meaning, and it has the potential to be extended in the future.

For now, we would be adding `min` and `max` attributes to all [numeric](https://drafts.csswg.org/css-values/#numeric-types), [length](https://drafts.csswg.org/css-values/#lengths), and [other quantity](https://drafts.csswg.org/css-values/#other-units) data types, including combinations such as `<length-percentage>`.

The `min` and `max` values would be inclusive.  As Tab mentions earlier in the thread, we don't want open-ended bounds for non-integer values (e.g., to allow 0.00000000001 but not 0) because that gets into messy areas of numeric precision.  For integer values, it is easy to just shift the minimum/maximum to the next allowed value (that is, to specify `<integer min=1>` instead of "integer greater than 0").

I haven't had a chance to do a comprehensive review of how many properties this would effect, but here are some examples from CSS Fonts Level 4:

- [font-size](https://drafts.csswg.org/css-fonts-4/#font-size-prop)

  `<absolute-size> | <relative-size> | <length-percentage min=0>`

- [font-weight](https://drafts.csswg.org/css-fonts-4/#font-weight-prop):

   `[normal | bold | <number min=1 max=1000>]| bolder | lighter`

- [font-stretch](https://drafts.csswg.org/css-fonts-4/#font-stretch-prop):

  `normal | <percentage min=0%> | <font-stretch-keyword-value>`

- [font-style](https://drafts.csswg.org/css-fonts-4/#font-style-prop)

  `normal | italic | oblique <angle min=-90deg max=90deg>?`

As discussed previously, this syntax only covers parser-enforced restrictions on values, not clamping that happens at computed-value or used-value time.  Specifically, any value that doesn't meet these constraints on the data type would make the surrounding declaration [invalid](https://drafts.csswg.org/css-syntax-3/#css-invalid), per CSS Syntax:

> After each construct (declaration, style rule, at-rule) is parsed, the user agent checks it against its expected grammar. If it does not match the grammar, it’s invalid, and gets ignored by the UA, which treats it as if it wasn’t there at all.

Currently, the parser-level constraints on CSS values are defined by prose that states that certain values are invalid.  E.g., the prose for `font-weight` currently says "Only values greater than or equal to 1, and less than or equal to 1000, are valid, and all other values are invalid."

The proposed change would encode those constraints directly in the [CSS Values grammar](https://drafts.csswg.org/css-values/#value-defs).

**Comment by fantasai** [comment]
I'd prefer to use mathematical range notation. It's a lot more compact, and part of keeping these grammars readable is keeping them compact enough to be visually parsed.

```
<angle [-90deg,90deg]>
```
Alternately some form of colloquial range notation (same rationale).

```
<integer 1+> <integer 0+> <percentage -100% to 100%> <percentage 0 to 100%>
```

(Maybe replace "to" with a proper n-dash. ;)

**Comment by AmeliaBR** [comment]
@fantasai  Okay, so that's two additional syntaxes, for three alternatives so far.

So people can really compare, here's what they look like for the font properties I used in my [comment above](https://github.com/w3c/csswg-drafts/issues/355#issuecomment-458324757), along with my summary of pros and cons:

## Attribute notation

- font-size:  `<absolute-size> | <relative-size> | <length-percentage min=0>`

- font-weight: `[normal | bold | <number min=1 max=1000>] | bolder | lighter`

- font-stretch: `normal | <percentage min=0%> | <font-stretch-keyword>`

- font-style: `normal | italic | oblique <angle min=-90deg max=90deg>?`

Pros

- familiar syntax
- easy to read
- extensible to other types of constraints

Cons

- verbose

## Bracket range notation

- font-size:  `<absolute-size> | <relative-size> | <length-percentage [0,]>`

- font-weight: `[normal | bold | <number [1,1000]>] | bolder | lighter`

- font-stretch: `normal | <percentage [0%,]> | <font-stretch-keyword>`

- font-style: `normal | italic | oblique <angle [-90deg, 90deg]>?`

Pros

- compact
- uses a recognized syntax for people with a mathematical background
- similar to the [syntax used for describing a number of repeated tokens](https://drafts.csswg.org/css-values/#component-multipliers)

Cons

- similar to the syntax used for describing a number of repeated tokens
- the single-sided bounds syntax (`[0,]` for zero and up) may be confusing for those not familiar with mathematical range notation

## Human-readable range notation

- font-size:  `<absolute-size> | <relative-size> | <length-percentage 0+>`

- font-weight: `[normal | bold | <number 1 to 1000>] | bolder | lighter`

- font-stretch: `normal | <percentage 0%+> | <font-stretch-keyword>`

- font-style: `normal | italic | oblique <angle -90deg to 90deg>?`

Pro

- compact
- written the way you would read it

Cons

- The `+` notation can get lost among % signs or units.
- No syntax for a maximum bound without a minimum bound (but I don't think we have any use case for this).

> (Maybe replace "to" with a proper n-dash. ;)

Nope. The whole idea is to make a grammar that is easier to auto-parse! Subtle typographic niceties not allowed! Especially because I want to eventually use the chosen syntax within author-supplied values to Houdini APIs.

**Comment by tabatkins** [comment]
> * the single-sided bounds syntax (`[0,]` for zero and up) may be confusing for those not familiar with mathematical range notation

Would it be troublesome to do `[0,∞]`? We promised to keep CSS grammar ASCII-only, but not the description of its syntax. ^_^ (And I'm okay with an ∞ showing up in Houdini code.)

**Comment by fantasai** [comment]
@tabatkins I thought about that as well. :) I say we go ahead and use it, but also accept the missing infinity version so that people who have trouble typing it don't have to.

**Comment by Crissov** [comment]
Brackets and dots notation
----------------

An ellipsis made of three dots `...` (not U+2026 `…`) could stand in for an infinity sign.

* font-size:  `<absolute-size> | <relative-size> | <length-percentage [0, ...]>`
* font-weight: `[ normal | bold | <number [1, 1000]> ] | bolder | lighter`
* font-stretch: `normal | <percentage [0%, ...]> | <font-stretch-keyword>`
* font-style: `normal | italic | oblique <angle [-90deg, 90deg]>?`

Dots notation
----------------

This could be coupled with two dots to indicate a closed range, which in turn is just a variation of the _human-readable range notation_ with `..` substituting `to` and `...` for `+`.

* font-size:  `<absolute-size> | <relative-size> | <length-percentage: 0 ...>`
* font-weight: `[ normal | bold | <number: 1 .. 1000> ] | bolder | lighter`
* font-stretch: `normal | <percentage: 0% ...> | <font-stretch-keyword>`
* font-style: `normal | italic | oblique <angle: -90deg .. 90deg>?`

**Comment by svgeesus** [comment]
Bikeshed needs to be updated to work wit this, apparently

**Comment by AmeliaBR** [comment]
Bikeshed issue: https://github.com/tabatkins/bikeshed/issues/1441

I'll make the tracking issue for the edits once that is resolved.

**Comment by tabatkins** [comment]
Bikeshed's updated, plz make tracking issues @AmeliaBR ^_^

**Comment by AmeliaBR** [comment]
Darnit. I had such a good excuse for not working on this. Ok, I'll tackle that this weekend.

**Comment by AmeliaBR** [comment]
Ok, change of plans. I decided it's just as easy to make the edits as to make a few dozen issues. But I came up with a stylistic question:

Should I only be adding the bracket range notation to the blue-box definition, or also to prose references to syntax parts?  I'm currently adding it in where there is a definition list that breaks out the syntax pieces, but am not otherwise adding it to prose.

I'm also leaving in all the prose restrictions (e.g. "negative values are invalid" or "negative values are not allowed").

**Comment by tabatkins** [comment]
> Should I only be adding the bracket range notation to the blue-box definition, or also to prose references to syntax parts? I'm currently adding it in where there is a definition list that breaks out the syntax pieces, but am not otherwise adding it to prose.

I'm copying it to the `dt`s defining individual grammar chunks; it's a relevant piece of information, and readers are well-served by surfacing it right at its actual point of definition.

I *am* removing prose restrictions that are entirely obviated by the grammar change, tho; we don't say in prose that a value "must be a length, or else it's invalid", etc., so when the grammar expresses that it's non-negative, no need to say that explicitly again in prose.
