### ISSUE TITLE
[css-fonts-3] Typo in onload eventHandler

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#3553]
The following pages include an encoded '<' character in the onload eventHandler.

```
window.onload = function () {
  if (!("devicePixelRatio" in window && window.devicePixelRatio > 1)) return;
  var i, hiresElements = document.getElementsByClassName("hires");
  for (i = 0; i &lt; hiresElements.length; i++) {
    var h = hiresElements[i];
    if (h.tagName != "IMG") continue;
    var src = h.getAttribute("src");
    var src2x = src.replace(/\.\w+$/, function(m) { return "@2x" + m; });
    h.src = src2x;
  }
}
```
https://github.com/w3c/csswg-drafts/blob/40eeef57df9ac1c6908588332d3bd6a10eb17bb8/css-fonts-3/Overview.html#L6417
https://github.com/w3c/csswg-drafts/blob/40eeef57df9ac1c6908588332d3bd6a10eb17bb8/css-fonts-3/Fonts.html#L6423

**Comment by svgeesus** [comment]
Re-opening until the same edits are made to the errata.

**Comment by svgeesus** [comment]
Errata fixed
