### ISSUE TITLE
[css-sizing] The resolved value of min-size: auto should also be 0 when there is no box

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3557]
From https://drafts.csswg.org/css-sizing/#valdef-width-auto, about `min-width/height: auto`,

> For backwards-compatibility, the resolved value of this keyword is zero for boxes of all [CSS2] display types: block and inline boxes, inline blocks, and all the table layout boxes.

Both Firefox and Chromium also seem to resolve it to 0 for `display: none/contents`. I guess `display: none` needs it for backwards-compatibility, and `display: contents` should be consistent with `none`. So the spec should include these cases.

**Comment by fantasai** [comment]
Agenda+ to request confirmation.

**Comment by fantasai** [comment]
Proposed text: “It also resolves to zero when no box is generated.” This covers 'display: none', descendants of 'display: none', and 'display: contents'.
