### ISSUE TITLE
[selectors-4] selector inheritance?

### ISSUE THREAD

**Issue by flavi1** [w3c/csswg-drafts#3560]
Hello.
Should it be great to integrate LCSS selector inheritance to CSS4 spec?
(idea from https://github.com/flavi1/lcss)

Example
=======

Just transform this :
```
@(#parent1) {
  @(.sub1.myClass > span, .sub2.active) {
    body { color: #888; }
    @media print {
      body { color: #333; }
    }
  }
  @(.sub3) {
    code { color: red; }
  }
  code { color: blue; }
}

@(#parent) {
  .sous-style {
    display: none;
  }
}
```

To this :

```
#parent1 .sub1.myClass > span body, #parent1  .sub2.active body {
 color: #888; 
}

@media print {
#parent1 .sub1.myClass > span body, #parent1  .sub2.active body {
 color: #333; 
}


}

#parent1 .sub3 code {
 color: red; 
}

#parent1 code {
 color: blue; 
}

#parent .sous-style {

    display: none;
  
}

```

Think about playing with  css files importations,  "var(--my-var, defalut_val)", and "--my-var: assigned_val;"

**Comment by bradkemper** [comment]
How about this?

https://tabatkins.github.io/specs/css-nesting/

**Comment by jonjohnjohnson** [comment]
I'm guessing you can close this as a duplicate and add your concerns/suggestions to issues already filed...
- [#2701 [css-nesting] request to pick up the css-nesting proposal](https://github.com/w3c/csswg-drafts/issues/2701)
- https://github.com/w3c/csswg-drafts/issues?utf8=✓&q=is%3Aissue+is%3Aopen+nesting

**Comment by flavi1** [comment]
Oh... Sorry for duplication, and thanks for the related links.
