### ISSUE TITLE
[css-text] `line-break: anywhere` but normal breaking at spaces

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#3561]
We added `line-break: anywhere`, but resolved to break at preserved spaces too.

Looking at requests from authors ([crbug.com/720205](http://crbug.com/720205) and [an author page linked from it](http://sinst.html.xdomain.jp/zengaku/jkkn/chrome_bug5.html)), what author wants is Gecko/WebKit behavior, which is break before/after any punctuation, but not at preserved spaces.

I understand some members do want to break at preserved spaces, and but including it breaks the original requests.

Can we add a value to help the original request?

**Comment by kojiishi** [comment]
[A test showing cases @jsbin](https://jsbin.com/henigah/edit?html,output)

IIUC what authors want at [crbug.com/720205](http://crbug.com/720205) is Gecko/WebKit behavior on these two cases, but neither value of the spec provide it.

**Comment by fantasai** [comment]
Hi Koji, I'm a little confused exactly what you're requesting here. As long as break-spaces is not specified, a space at the end of the line will not take up any space. So there will not be any break that wraps a space to the beginning of a line. Are you talking about a different kind of space?

**Comment by kojiishi** [comment]
Thanks, that's great. Currently the [`line-break: anywhere`](https://drafts.csswg.org/css-text-3/#valdef-line-break-anywhere) states that:
> There is a soft wrap opportunity around every typographic character unit, including around any punctuation character or **preserved spaces**

Should "around preserved spaces" be applied only when `break-spaces` is also specified?

**Comment by fantasai** [comment]
@kojiishi Hm, I'm not sure.

Technically, when spaces hang (default behavior) it doesn't matter whether there is a break opportunity or not around them, they'll still "fit" on the line so we won't break before them even if there is an opportunity... So I think either way you get the behavior you want for `line-break: anywhere` (except when `break-spaces` is specified of course).

cc @frivoal

**Comment by kojiishi** [comment]
Oh, I see, I was under impression that only non-breakable sequences can hang, since hanging is a type of emergency operations for CJK to avoid expansions or lagged lines, but probably not for other writing systems.

I'm good with the interpretation, @frivoal great if you can confirm the text has nothing to do unless `break-spaces` is specified.

**Comment by kojiishi** [comment]
> so soft wrap opportunities don't do anything

Thank you for the confirmation. If a definition in the spec doesn't do anything, isn't it better to not to have it?

If you want that effect only when `break-spaces` is specified, writing so helps easier to understand, and helps not to spend time to wonder if there were any other intention.

**Comment by javifernandez** [comment]
As far I understand it, the new 'break-spaces' value already provides soft wrap opportunities around preserved spaces. What does this combination with line-break: anywhere provide ? 

https://drafts.csswg.org/css-text-3/#valdef-white-space-break-spaces
> A line breaking opportunity exists after every preserved white space character, including between white space characters.

**Comment by frivoal** [comment]
> As far I understand it, the new 'break-spaces' value already provides soft wrap opportunities around preserved spaces. What does this combination with line-break: anywhere provide ?

`line-break: anywhere` isn't just about spaces, but on the topic of spaces, it changes one thing of the behavior of `white-space:break-spaces`  when used together: `white-space:break-spaces` introduces break opportunities **after** every space. That means that between the last letter of a word and the first space, there isn't one.  If you add`line-break: anywhere`, then there is also a break opportunity there.

**Comment by kojiishi** [comment]
So, IIUC:
* `line-break: anywhere` changes nothing about breaking before/after spaces.
* `white-space: break-space` disallows hanging spaces, and adds break opportunities after every spaces, including between spaces.
* `white-space: break-space` when used with `line-break: anywhere` adds break opportunities before spaces too.

Is this correct?

If so, it'd be very helpful if the spec has these conditions more straight.

**Comment by frivoal** [comment]
Basically yes, and I'm all for making the spec clearer if it isn't now, but to me the way you describe it more confusing than what's in the spec (even though I now understand what you mean):
>     * `line-break: anywhere` changes nothing about breaking before/after spaces.

well, it changes nothings about breaking before or after **preserved spaces** when there are no preserved spaces. Other kinds of spaces (nbsp, narrow non breaking spaces, etc) do get break opportunities. Also, line-break is about breaking **opportunities**, not forced breaks, so it has no effect when you don't need to wrap at all, as is the case when preserved spaces hang (pre-wrap), or when wrapping is disabled entirely (pre, nowrap).

Maybe we can keep the normative prose as it is, and add a note like:

> Note: `anywhere` only allows preserved spaces at the end of the line to be wrapped to the next line when white-space is break-spaces, because in other cases:
> * preserved spaces at the end/start of the line are discarded (`normal`, `pre-line`)
> * wrapping is forbidden altoghether (`nowrap`, `pre`)
> * wrapping spaces is unecessary as they hang (`pre-wrap`).
>
> When it does have an effect on preserved spaces, with `break-spaces`, it allows breaking before the first of a sequence of preserved spaces, which `break-spaces` does not do on its own.

**Comment by javifernandez** [comment]
> `line-break: anywhere` isn't just about spaces, but on the topic of spaces, it changes one thing of the behavior of `white-space:break-spaces` when used together: `white-space:break-spaces` introduces break opportunities **after** every space. That means that between the last letter of a word and the first space, there isn't one. If you add`line-break: anywhere`, then there is also a break opportunity there.

I see; although the same happens when combining white-space: break-spaces and overflow-wrap: break-word, right ? In that case there is also a break opportunity  between the last letter of a word and the first space.  Are these two combinations totally equivalent  ?

**Comment by frivoal** [comment]
> I see; although the same happens when combining white-space: break-spaces and overflow-wrap: break-word, right ? In that case there is also a break opportunity between the last letter of a word and the first space. Are these two combinations totally equivalent ?

Yes, it is similar, but no, it is not totally equivalent: `overflow-wrap: break-word` or  `overflow-wrap: anywhere` (together with `white-space:break-spaces`) will add a wrapping opportunity between the last letter of the word and the first space after it **if** there's no other wrapping opportunity in the line.

**Comment by frivoal** [comment]
tested by line-break-anywhere-005.html
