### ISSUE TITLE
[css-text] Connected scripts should behave like cursive scripts

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3566]
https://drafts.csswg.org/css-text-3/#cursive-tracking

“if the UA cannot expand text from a cursive script without breaking its cursive connections, it must not apply spacing between any pair of that script’s typographic letter units at all (effectively treating each word as a single typographic letter unit for the purpose of letter-spacing).”

Devanagari isn't "cursive" but it is "connected." It should probably behave like the above quote describes. Therefore, the spec should probably switch the word "cursive" with the word "connected."

**Comment by litherum** [comment]
cc @r12a @fantasai

**Comment by litherum** [comment]
Also: Is the identification of script supposed to be done by `lang=` or by code point or by font?

**Comment by nedley** [comment]
Devanagari allows for [letter spacing](http://w3c.github.io/ilreq/#h_letter_spacing).

**Comment by fantasai** [comment]
What @nedley said, and per code point, see https://www.w3.org/TR/css-text-3/#character-properties and https://www.w3.org/TR/css-text-3/#script-groups (I could have sworn I had more categories in that last appendix. Excuse me while I do some archaeology...)

**Comment by litherum** [comment]
After further discussion inside Apple, it appears that this issue would better be served by evangelization, rather than a CSS spec change.
