### ISSUE TITLE
[css-grid] max<min comparison in minmax()

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3567]
From https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-minmax

> - `minmax(min, max)`
>    Defines a size range greater than or equal to `min` and less than or equal to `max`. If `max < min`, then max is ignored and `minmax(min,max)` is treated as `min`. 

It's not clear whether the last sentence means that `minmax(min,max)` should be treated as `min` before starting the sizing algorithm, i.e. that both the initial min and max track sizing functions should be `min`, or whether it refers to

> In all cases, if the growth limit is less than the base size, increase the growth limit to match the base size.

which keeps appearing along the algorithm, and the initial min and max track sizing functions will still be the specified values.

In the former case, please define how to perform the comparison if `min` and `max` are not both `<length>` or resolveable `<percentage>`.

**Comment by fantasai** [comment]
It's the latter. The point of the descriptions up front is so that we know what we're trying to do. Putting the entire algorithm into the description of each value of the property isn't workable.

**Comment by fantasai** [comment]
OK, tweaked the wording. LMK if it looks OK now.

**Comment by Loirooriol** [comment]
Still doesn't seem 100% clear to me, but now it's better, thanks.
