### ISSUE TITLE
[css-grid] fit-content() definition not clear

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3569]
From https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-fit-content,

> - `fit-content( <length-percentage> )`
>    Represents the formula `min(max-content, max(auto, argument))`, which is calculated like `minmax(auto, max-content)`, except that the track size is clamped at `argument` if it is greater than the `auto` minimum.

This definition seems very confusing to me. For starters, `auto` has different meaning as a minumim than as a maximum, so it's not clear how `min(max-content, max(auto, argument))` should be calculated.

In "the track size is clamped at `argument`", it's not clear whether this is a flooring or a ceiling. Usually "clamp" refers to an interval, not a single value.

In "if it is greater" it's not clear whether "it" refers to `argument` or to the track size.

**Comment by fantasai** [comment]
How about
“Represents the formula max(minimum, min(limit, max-content)) where _minimum_ represents an `auto` minimum (which is often, but not always, equal to a `min-content` minimum) and _limit_ is the argument to fit-content(). This is essentially calculated as the smaller of ''minmax(auto, max-content)'' and ''minmax(auto, limit)''.”
?

**Comment by Loirooriol** [comment]
That's much, much better, thanks!

**Comment by fantasai** [comment]
Done.
