### ISSUE TITLE
[css-multicol] box-decorations on boxes fragmented by a column-span (example 21 / figure 11)

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3575]
https://drafts.csswg.org/css-multicol-1/#example-c0153f49

The red border in figure 11 looks wrong to me.  I think only the first fragment should have a block-start border and only the last fragment should have a block-end border.  Intermediary fragments should not have block-start/end borders. (All fragments should have inline-start/end borders though.)  I'm assuming [`box-decoration-break`](https://drafts.csswg.org/css-break-3/#break-decoration) has its initial value in this example.  `box-decoration-break:clone` should make all fragments have borders on all sides, as usual.

**Comment by rachelandrew** [comment]
@MatsPalmgren this was added in relation to this issue https://github.com/w3c/csswg-drafts/issues/1072#issuecomment-379555974 and yes I think you are right and this is my diagramming error.

**Comment by MatsPalmgren** [comment]
Yes, it looks good now.  Thanks.
