### ISSUE TITLE
[css-tables][css-position] sticky cols

### ISSUE THREAD

**Issue by inoyakaigor** [w3c/csswg-drafts#3577]
I want to suggest an idea that can help to display large tables: sticky position for table columns (for easy horizontal scroll). It is basic functionality in desktop programs like MS Excel. Currently we can find many solutions for this based on some CSS tricks and additional JS calculations but all of this is worst and have a lot of restrictions and errors in edge cases.

### Basic concept:
* `position: sticky` only for first column
* `position: sticky` inside `<td>` styles makes this column stuck
* `position: sticky` for `<tr>` makes row stuck

Of course there are a big number edge cases (e.g. which behavior should be with `table-layout: fixed`?) and all of it will be resolved if this idea will develop

**Comment by SelenIT** [comment]
Technically, `position: sticky` is already supported for table cells ([see example](https://codepen.io/paulobrien/pen/LBrMxa)), so this approach already works in modern browsers. Some browsers still don't apply `position: sticky` to entire table rows and row groups, but this is just their [known implementation bug](https://github.com/w3c/csswg-drafts/issues/2155) that eventually will be fixed. Also, selecting the cells belonging to the same column may be rather tricky if the table has merged cells, but this should be addressed by the [column combinator](https://drafts.csswg.org/selectors-4/#the-column-combinator) proposed in the CSS Selectors Level 4 spec.

**Comment by inoyakaigor** [comment]
@SelenIT I forgot to add what i mean about sticky column: sticky column to easy horizontal scroll. I'll update the initial message.

**Comment by inoyakaigor** [comment]
@inoyakaigor yes that is what I said
