### ISSUE TITLE
[css-grid] auto min size definition is circular

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3581]
From https://drafts.csswg.org/css-grid/#min-size-auto,

> However, if the grid item spans only grid tracks that have a fixed max track sizing function, its specified size suggestion and content size suggestion in that dimension (and the input to the transferred size suggestion in the other dimension) are further clamped to less than or equal to the stretch fit the grid area’s size (so as to prevent the content-based minimum size from forcing overflow of its fixed-size grid area).

This assumes that the grid area’s size is known, but the sizing algorithm uses the used value of the minimum size e.g. in https://drafts.csswg.org/css-grid/#min-size-contribution

> The minimum contribution of an item is the outer size that would result from assuming the item’s used minimum size (min-width or min-height, whichever matches the relevant axis) as its preferred size

The condition already checks that the track sizing function is fixed, so I would just clamp by that value instead of by the grid area’s size which may not be known yet.

**Comment by fantasai** [comment]
Can't just use the track sizing function, because there's multiple tracks involved here, but I see what you're saying, we need to clamp by what the grid area would be if the min functions were all zero (effectively).

**Comment by Loirooriol** [comment]
Can't you just sum all the track sizing functions, and the gaps in between?

**Comment by fantasai** [comment]
Alright, lmk if that works?

**Comment by Loirooriol** [comment]
That works for me.

However, gutters behave basically like tracks, so maybe a gutter with indefinite percentage should prevent the clamping, just like a track with an indefinite percentage would do?

Though https://drafts.csswg.org/css-align/#ref-for-typedef-length-percentage%E2%91%A1 says that indefinite percentage gaps should be resolved against zero, which is consistent with your edit.

**Comment by fantasai** [comment]
No they definitely should not prevent the clamping. That wouldn't give useful results in real life.
