### ISSUE TITLE
[css-scroll-snap] Snapping to center of zoomed image in gallery

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/csswg-drafts#3583]
Re: [Motivating Examples](https://www.w3.org/TR/css-scroll-snap-1/#examples) 

How does the spec or site code handle situations for the following use case in the event of zoomed images in a photo gallery?

Steps:

1. Site visitor scrolls through the gallery to a particular image.

2. Browser snaps image to center point as a result of the CSS in the example.

3. Site visitor pinch-zooms to expand the image such that the image is now much larger than the viewport or provided visible area. I suspect this particular concern is more properly directed at a different spec in its own separate issue, but am mentioning it in order to be rigorous.

Expected behavior: Zoomed image stays zoomed.

Feared behavior: Zoomed image snaps back to original size at the center point.

4. Visitor attempts to pan around the enlarged image in order to see all of the image contents. This is the primary focus of concern for this issue.

Expected behavior: Visitor can pan around the image freely with no further snapping taking place.

Feared behavior: Any time the visitor pans toward the edge of the image, the browser snaps the image back to center point and/or resets the zoom.

5. The site visitor inadvertently overshoots the edge of the image. This is related to the previous step. Please advise if this needs to be a separate issue.

Desirable behavior: 
The image snaps back to the nearest non-overshooting point.
or
The image remains overshot where the visitor left it.

Feared behavior: Any time the visitor inadvertently overshoots the edge of the image, the browser snaps the image back to center point, resets the zoom, or snaps to the center point of the next or previous image.

**Comment by fantasai** [comment]
See https://www.w3.org/TR/css-scroll-snap-1/#snap-overflow
If this is not implemented correctly, file bugs against the implementations.
If you think the spec is unclear, please be more precise about what you find unclear.

**Comment by fantasai** [comment]
[Sorry, tagged commit to wrong issue.]

**Comment by pfgithub** [comment]
https://output.jsbin.com/ruhajoz

https://user-images.githubusercontent.com/6010774/169926383-dc68bd0c-f0ca-4f32-937f-446a8572e5a7.mov

- Zoom in on a touchscreen device or with a trackpad (so it makes the VisualViewport not cover the entire viewport)
- Notice how it is possible to pan left and right, but not up and down on the card

For image galleries, this makes a really bad user experience. This recording is from Firefox, the same issue is seen on Chrome and iOS safari.

I think this is in the spec - it talks about scroll snapping being relative to the visual viewport, which changes when zoomed in

**Comment by pfgithub** [comment]
@CharlesBelov That example has the cards set to overflow:hidden, so the issue you saw is unrelated to scroll snap. Here's a fixed example that demonstrates the scroll snap problem better:

https://output.jsbin.com/wagifehito

And a video (if it works):

https://user-images.githubusercontent.com/6010774/170128820-4149d07a-3229-4579-acc9-7aeb50d0054e.mov
