### ISSUE TITLE
[css-borders-4] Invalid value for border-color

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#3586]
According to the https://drafts.csswg.org/css-values-3/#component-multipliers

`
A hash mark (#) indicates that the preceding type, word, or group occurs one or more times, separated by comma tokens (which may optionally be surrounded by white space and/or comments). It may optionally be followed by the curly brace forms, above, to indicate precisely how many times the repetition occurs, like <length>#{1,4}.
`

The border-color should be `<color>#{1,4}` instead of `<color>{1,4}#`

https://github.com/w3c/csswg-drafts/blob/0abf9c8232377af38149293038548da8e58779b5/css-backgrounds-4/Overview.bs#L188

**Comment by fantasai** [comment]
No, it should be what it is. But it's confusing, so it should have brackets. `[<<color>>{1,4}]#`

**Comment by fantasai** [comment]
Although there's outstanding edits missing on this section, which might render this issue irrelevant...

**Comment by SebastianZ** [comment]
The syntax changed to `[ <color> | <image-1D> ]{1,4}`. Therefore there are no ambiguities anymore because of the hash mark.

Sebastian
