### ISSUE TITLE
[css-flex] which margin definition for intrinsic sizing?

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#359]
I'm opening this on behalf of Christian Biesinger as he posted a question to www-style. Moving the thread here:

> I learned today that not all browsers ignore percentage margins for
> intrinsic width computations. In this testcase:
> http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%20%20div%20%7B%20float%3A%20left%3B%20border%3A%20solid%3B%20%7D%0A%20%20p%20%7B%20margin%3A%2010%25%3B%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%3E%0A%20%20%3Cp%3Ethisisaword%3C%2Fp%3E%0A%3C%2Fdiv%3E
> 
> Chrome/IE 11/Edge overflow the box, whereas in Firefox they don't. I
> actually have no idea how they implement this! I'm also unsure what the
> spec requires...
> 
> -Christian
> 
> On Mon, Jul 25, 2016 at 5:24 PM, Christian Biesinger <cbiesinger@google.com>
> wrote:
> 
> > Hello!
> >
> > Question about https://drafts.csswg.org/css-flexbox/#intrinsic-main-sizes
> >
> > This algorithm wants to use the outer flex base size. But in general, for
> > intrinsic sizing purposes, percentage margins get treated as zero. Should
> > that be used here as well?
> >
> > Also, is there a reason why min-size is ignored for the purpose of this
> > algorithm?
> >
> > thanks,
> > -Christian
> >

**Comment by frivoal** [comment]
I think this is the same issue as #347, so we should probably merge them. Is there info in one of them that's not in the other?

**Comment by gregwhitworth** [comment]
Yep it is, looked for issues by label. Thanks!! :)
