### ISSUE TITLE
[css-pseudo-4] Specify better handling of text shadows for ::selection

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3605]
There's an issue in the spec:

> What should happen with text shadows? Drawing them in their original color is disconcerting if that color is not a shade of gray. Maybe if the overlay has a background, suppress any text shadows below it?

I'm still of the opinion that the suggested behavior is the best behavior, would like to hear back if it's OK to spec.

**Comment by dbates-wk** [comment]
I don't have a moment right now (02/13)  to ponder this. So, I will need to get back to you. Here's a tidbit for now. WebKit supports specifying a text-shadow for ::selection today though repaint rects likely don't account for it. So, messed up repainting. Here's where WebKit gather's the CSS text shadow for ::selection as part of painting: <https://trac.webkit.org/browser/trunk/Source/WebCore/rendering/TextPaintStyle.cpp?rev=240887#L152>

**Comment by dbates-wk** [comment]
A picture is worth a thousand words. Picture please? Didn't open the spec., to find your quote (yet), are we talking about the originating element's style has a text-shadow? If so, it seems to match my intuition (and Apple's Pages - see below) that ::selection paints on-top of the originating element's style (or whatever the top-most styling is for the element).

<img width="340" alt="image" src="https://user-images.githubusercontent.com/20798617/52763849-480d9c80-2fd2-11e9-9b10-97ce02211032.png">

**Comment by dbates-wk** [comment]
Or are we talking about ::selection having a text-shadow? Maybe I should read the spec. :/
