### ISSUE TITLE
[css-pseudo-4] Identity of Element.pseudo() return value

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3607]
@heycam wrote in https://github.com/w3c/csswg-drafts/issues/3541#issuecomment-459936846:

<hr>

We need some wording about the identity of the object returned by `pseudo()`, for example whether it's required to be the same object each time you call it on an element with a given type.

Now that I think about it, if we do require that the same object is returned, what does it mean for the `CSSPseudoElement` object if we restyle the element and the pseudo goes away (and so `null` would be returned from another call to `pseudo()`)?  Is the `CSSPseudoElement` detached in some way?  If we restyle again and the pseudo-element is recreated, does the old `CSSPseudoElement` remain functional?  Might it be simpler to always return an object for a supported pseudo type, regardless of whether the pseudo currently exists?

**Comment by emilio** [comment]
We discussed a bit about it in #3603. I think I'd prefer for the return value to not guarantee identity. I can imagine people poking at a bunch of pseudos on all elements on a webpage, and having to keep storage for them on the DOM nodes to guarantee identity sounds like a bit of  a pain. But I can poke to some of the DOM / HTML folks for feedback on that, maybe I'm being a bit over-paranoid.

**Comment by tabatkins** [comment]
My main argument for keeping identity stable (and thus caching objects upon first access) is that they're *effectively* DOM nodes (no children or attributes, but they have style, at least), and DOM nodes can be compared by object identity. I suspect it will be useful to be able to ask "is the pseudo in this variable also present in this array?", etc. Without stable object identity, this will be a much more annoying question to answer.

Having a stable identity doesn't prevent them from being collected; the DOM node should only have a weak reference to its pseudos. So if someone iterates the tree and pings every pseudo, it'll result in an explosion of pseudo nodes, but if they're not holding onto them they'll all die in the next collection.

This means they're observably not the same object in the presence of expandos, but I'm okay with that. I just don't want people to be able to ask for a pseudo, store it, then ask again and get a different object that's not === to the first.

**Comment by annevk** [comment]
I think you either need to preserve a 1:1 relationship, always return a new object, or perhaps return a new object per task on the event loop (though this gets complicated). Some kind of weak references isn't the way to go. Note that with many objects their associated style objects would also be many (that relationship has to be 1:1 presumably) and they'd all end up being proxies for the actual style or some such. That seems somewhat complicated to define. Unless you invalidate the objects per task or some such.

**Comment by tabatkins** [comment]
It's "always the same object, up to observability constraints". So if you don't hold a reference and don't set any expandos, the object can be freed and a fresh one given later, but otherwise it must be cached.

**Comment by annevk** [comment]
I missed you had already resolved this to a satisfactory outcome. I mainly meant to outline constraints on the solution space. Making `[SameObject]` useful is tracked by https://github.com/heycam/webidl/issues/212 by the way.

**Comment by Loirooriol** [comment]
> if you don't hold a reference and don't set any expandos, the object can be freed

This includes weak references, right?

```js
var s = new WeakSet();
s.add(element.pseudo(type)); // Store weak reference
// later
s.has(element.pseudo(type)); // Should be true because GC shouldn't be observable
```

**Comment by fantasai** [comment]
Edited. @tabatkins mind reviewing?
