### ISSUE TITLE
[css-flexbox-1] Should the intrinsic sizing algorithm take min-size into account, too?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#361]
https://drafts.csswg.org/css-flexbox/#intrinsic-main-sizes

Asks to "then clamp that result by the max main size property.". Why only max and not min?

**Comment by fantasai** [comment]
I think the reason we left that out was because the size, prior to clamping, is guaranteed to be at least the min-size. However, you're right that we need to floor at the min-size: because clamping by the max-size alone, without consideration of the min-size, could result in violating the min-size.

**Comment by fantasai** [comment]
@cbiesinger Let me know if that fix looks good to you. :)
