### ISSUE TITLE
[css-grid] "Distribute space to base sizes up to growth limits" unclear

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3615]
From https://drafts.csswg.org/css-grid/#extra-space, "Distribute space to base sizes up to growth limits":

> Find the *item-incurred increase* for each spanned track with an affected size

It's not clear whether "item-incurred increase" is a definition or a reference to some existing concept. I think the former, but it's not clear at first sight. I believe definitions should be in bold italic text, not just italic.

> by distributing the space equally among them,

Does "them" refer to the spanned tracks or the affected size? I guess the latter. Also, it can seem this distribution is increasing the affected sizes, while in fact I understand that it goes to the item-incurred increase (and this is its definition).

> freezing tracks as their size reaches their growth limit 

It's not clear which size this is talking about. I guess it refers to the affected size plus the item-incurred increase.

> Note: If the affected size was a growth limit, this step has no effect.

In that case I think the step is still defining "item-incurred increase", which is referenced by later steps. Isn't this an effect? The note could clarify that the "item-incurred increase" is then 0.

**Comment by fantasai** [comment]
> It's not clear whether "item-incurred increase" is a definition or a reference to some existing concept. I think the former, but it's not clear at first sight. I believe definitions should be in bold italic text, not just italic.

It's a variable, and thus marked up with `<var>`.

> Does "them" refer to the spanned tracks or the affected size? I guess the latter.

Right.

> It's not clear which size this is talking about. I guess it refers to the affected size plus the item-incurred increase.

Right.

**Comment by fantasai** [comment]
Checked in some changes. Let me know if it's sufficient.

**Comment by Loirooriol** [comment]
> I guess it refers to the affected size plus the item-incurred increase.

Could you please clarify this in the spec?

**Comment by fantasai** [comment]
Done.
