### ISSUE TITLE
[css-grid] Sizing algorithm for span >= 2 should be a generalization of span 1

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3616]
I don't understand why there is a track sizing algorithm using [items with a span of 1](https://drafts.csswg.org/css-grid/#algo-single-span-items) (and intrinsic minimum and non-flexible maximum), and another one for [items with a span >= 2](https://drafts.csswg.org/css-grid/#algo-spanning-items) (not spanning tracks with flexible maximums).

I think both cases should use the same algorithm, just with the [extra space distribution](https://drafts.csswg.org/css-grid/#extra-space) being more trivial to perform for items with a span of 1. However, they aren't exactly the same:

 - With span >= 2, tracks with intrinsic minimums end up at least as big as the minimum contribution. For span 1, this is only ensured for `auto` minimums.
 - With span >= 2, an `auto` minimum under a sizing min/max-content constraint behaves as `min/max-content`. With span 1 it's not exactly like this, because the value is later clamped between the minimum contribution and the max track sizing function (or fit-content argument).

Why the differences?

**Comment by fantasai** [comment]
Wrt the first point, the following inequality holds: minimum contribution &le; min-content contribution &le; max-content contribution. This allowed us to have a simpler structure for span=1. (We could have written super generalized algorithm, but this would have been harder for readers to follow. It's easier to think about the span=1 case using the simplified algorithm, and then work up to spanning items, where there is some extra complexity.)

Wrt the second point. see https://github.com/w3c/csswg-drafts/issues/2303#issuecomment-435212567 :)

**Comment by Loirooriol** [comment]
> minimum contribution ≤ min-content contribution

OK I was strongly suspecting this, but it's not obvious, because the definition of the minimum contribution is complex, and requires a deep understanding of css-sizing. Maybe add a note?

> We could have written a super generalized algorithm, but this would have been harder for readers to follow.

Then could you also add another note saying that applying the algorithm for spanning items to non-spanning ones would produce the same result, it would just be less simple?

> Wrt the second point. see [#2303 (comment)](https://github.com/w3c/csswg-drafts/issues/2303#issuecomment-435212567) :)

That looks good, thanks.

**Comment by fantasai** [comment]
> Then could you also add another note saying that applying the algorithm for spanning items to non-spanning ones would produce the same result, it would just be less simple?

At what point in the section do you think this is helpful to point out?

**Comment by Loirooriol** [comment]
Well for example in https://drafts.csswg.org/css-grid/#algo-single-span-items after "consider the items in it with a span of 1" it could say that it's just a simplification, but with the same result, of the algorithm for spanning items.

Or maybe in https://drafts.csswg.org/css-grid/#algo-spanning-items after "Repeat incrementally for items with greater spans until all items have been considered" it could say that performing an initial iteration for items with a span of 1 would have the same effect as running the non-spanning algorithm.

**Comment by fantasai** [comment]
@Loirooriol Done. Close out the issue if you are satisfied? :)

**Comment by Loirooriol** [comment]
Yes, thanks!
