### ISSUE TITLE
[css-grid] Sizing algorithm should work for span > 2

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3617]
https://drafts.csswg.org/css-grid/#algo-spanning-items has an algorithm for items with a span of 2. Items with a span of 1 are handled beforehand. Items with a span greater than 2 are not explicitly handled anywhere. Why?

I tried this example: https://jsfiddle.net/qg5v0zLa/

The grid container has an explicit width of 200px. The columns are sized with `min-content max-content`, and extra ones with `0`. The grid item has a min-content contribution of 50px and a max one of 100px.

If the grid item spans 2 columns, they become `25px 75px` according to https://drafts.csswg.org/css-grid/#algo-spanning-items.

But if the item spans 3 columns, https://drafts.csswg.org/css-grid/#algo-grow-tracks should be reached with base sizes of `0 0 0` and growth limits of `infinity infinity 0`, so the columns should become `100px 100px 0`.

This is not what Firefox and Chromium do, though. The columns end up being `25px 75px 0px`, as expected.

So instead of "items with a span of 2" the spec should say "items with a span of at least 2"

**Comment by fantasai** [comment]
You missed the last sentence: “Repeat incrementally for items with greater spans until all items have been considered.”

It has to be ordered this way or you don't get a tight fit where needed.

**Comment by Loirooriol** [comment]
Ah, you are right, I missed that XD
