### ISSUE TITLE
[css-grid-1] Add more directional values to grid-auto-flow

### ISSUE THREAD

**Issue by perymimon** [w3c/csswg-drafts#3622]
please consider to normalize `grid-auto-flow` with all value of `flex-direction` meen add `row-reverse` and `column-reverse`

and consider also to add the following values or similar with the same meaning to the spec:

`longest-dimension` : for auto flow to column or row the longest one;
`shortest-dimension`: for auto flow to column or row the shortest one;
`longest-dimension-reverse` : for auto flow to column or row the longest one but in reverse order;
`shortest-dimension-reverse`: for auto flow to column or row the shortest one but in reverse order;

-------

[grid-auto-flow-property](https://drafts.csswg.org/css-grid-1/#grid-auto-flow-property)
[flex-direction](https://drafts.csswg.org/css-flexbox-1/#flex-direction-property)

**Comment by perymimon** [comment]
`longest`, `shortest` `longest-reverse` and `shortest-reverse` should be more slik

**Comment by fantasai** [comment]
Hi @perymimon, I think it's not really possible to do longest/shortest because often the size of the grid container is dependent on how content is laid out inside it. But row-reverse/column-reverse should be doable and certainly makes sense to add.

**Comment by MatsPalmgren** [comment]
What is the use case for this?

**Comment by astearns** [comment]
I'd like to see a bit more here before this goes on the meeting agenda. I definitely agree with Mats that we need use cases to guide the discussion.

**Comment by fantasai** [comment]
@astearns This isn't the first time I've seen this request, and the workarounds being used were changing the grid's `direction` to get the reverse behavior. I'd rather avoid people doing that.

**Comment by CyberAP** [comment]
A simplest use-case is when your responsive layout differs from the placement of elements in DOM.

```html
<div class="columns">
  <div class="item">FOO</div>
  <div class="item">BAR</div>
</div>

<style>
.columns
{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
}

@media (max-width: 600px)
{
  .columns
  {
    grid-template-columns: auto;
    grid-auto-flow: row-reverse;
    /* BAR renders before FOO */
  }
}
</style>
```

And I actually need that a lot. Writing `.columns > :nth-child(1)` is cumbersome.

**Comment by perymimon** [comment]
trivial use case for reverse is content that writing from right to left. like Hebrow and arbic

Another one is when I build a game and want players cards flow from right to left

**Comment by fantasai** [comment]
> Trivial use case for reverse is content that writing from right to left. like Hebrew and Arabic

This is automatically handled. Reverse direction in Hebrew would go from left to right, because by default Grid and Flex will use right-to-left.

**Comment by fantasai** [comment]
The proposal here is to add `row-reverse`, `column-reverse`, and maybe also `wrap-reverse`, to `grid-auto-flow`--consistent with `flex-flow`.

**Comment by fantasai** [comment]
I've edited the row-reverse, column-reverse, and wrap-reverse values into the css-grid-3 editor's draft.
