### ISSUE TITLE
[css-inline][css-box-3] Define "line box" and "inline(-level) box" somewhere

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#363]
As far as I can tell, the CSS 2.1 definitions of [line box](https://www.w3.org/TR/CSS2/visuren.html#line-box) and [inline box/inline-level box](https://www.w3.org/TR/CSS2/visuren.html#inline-boxes) have not been repeated as formal definitions in any of the CSS level 3 text layout specs.

I'm not sure whether the intention is to place all the definitive definition for them in [Basic Box Model 3](https://drafts.csswg.org/css-box-3/), but for "line box" in particular, the current rough & outdated draft points to CSS Text 3, which no longer defines the term.  [CSS Inline 3](http://www.w3.org/TR/css-inline-3/) would seem to be a logical place for that definition -- it is where you get redirected if you follow http://www.w3.org/TR/css3-linebox from [an ancient draft spec](https://www.w3.org/TR/2002/WD-css3-linebox-20020515/#LineBox) -- but it never defines its terms.

**Comment by fantasai** [comment]
On 07/31/2016 03:22 PM, Amelia Bellamy-Royds wrote:
> As far as I can tell, the CSS 2.1 definitions of line box <https://www.w3.org/TR/CSS2/visuren.html#line-box> and inline
> box/inline-level box <https://www.w3.org/TR/CSS2/visuren.html#inline-boxes> have not been repeated as formal definitions in
> any of the CSS level 3 text layout specs.
>
> I'm not sure whether the intention is to place all the definitive definition for them in Basic Box Model 3
> <https://drafts.csswg.org/css-box-3/>, but for "line box" in particular, the current rough & outdated draft points to CSS Text
> 3, which no longer defines the term. CSS Inline 3 <http://www.w3.org/TR/css-inline-3/> would seem to be a logical place for
> that definition -- it is where you get redirected if you follow http://www.w3.org/TR/css3-linebox from an ancient draft spec
> <https://www.w3.org/TR/2002/WD-css3-linebox-20020515/#LineBox> -- but it never defines its terms.

Yeah, this would definitely go in CSS Inline once we draft up the relevant prose. However, that hasn't been done yet. Is there 
a problem with referencing CSS2.1?

Note that inline box and inline-level box are defined in CSS Display.

~fantasai

**Comment by AmeliaBR** [comment]
@fantasai 
SVG 2 can keep the CSS 2.1 reference for now, we'd just been trying to update all the cross-references to point to the latest modules wherever applicable.  With the big red warning that pops up for 2.1, I always feel a little uncertain relying on it, now!  "Line box" was particularly bad with the circular re-direct definitions in outdated draft specs, so I wanted to give a heads up.

To make this easier in the future, it might be worth adding a list of terms (linked to their canonical definitions) to the CSS Snapshot note, if anyone can figure out how to generate it.

**Comment by fantasai** [comment]
Auto-generation of terminology indexes is being worked on, but it unfortunately doesn't really include CSS2.1. :) The sections of 2.1 that haven't been replaced are still canonical, fwiw. And in any case if there is a conflict we do try to update both specs. CSS3 modules that replace 2.1 sections are generally better written, so are better references, and are of course more complete where we have added new features; but CSS2.1 should not in any case be *wrong*.

I'll close this issue for now, then. :)
