### ISSUE TITLE
[css-flexbox] Incorrect initial values

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#3636]
[CSS Flexible Box Layout Module Level 1](https://drafts.csswg.org/css-flexbox-1/#propdef-align-content) states that the initial value for `align-content` is `stretch`. Browsers and [CSS Box Alignment Module Level 3](https://drafts.csswg.org/css-align-3/#align-justify-content) give the initial value as 'normal'.

[CSS Flexible Box Layout Module Level 1](https://drafts.csswg.org/css-flexbox-1/#propdef-align-items) states that the initial value for `align-items` is `stretch`. Browsers and [CSS Box Alignment Module Level 3](https://drafts.csswg.org/css-align-3/#propdef-align-items) give the initial value as 'normal'.

[CSS Flexible Box Layout Module Level 1](https://drafts.csswg.org/css-flexbox-1/#propdef-justify-content)  states that the initial value for `justify-content` is `flex-start`. Browsers and [CSS Box Alignment Module Level 3](https://drafts.csswg.org/css-align-3/#align-justify-content) give the initial value as 'normal'.

**Comment by fantasai** [comment]
This difference is similar to how CSS2 gives the initial value of min-width as zero, whereas css-sizing gives it as auto. See note in https://drafts.csswg.org/css-flexbox-1/#alignment

**Comment by ewilligers** [comment]
Thanks for clarifying. I suspect this can be closed.

Tests: https://github.com/web-platform-tests/wpt/pull/15293
