### ISSUE TITLE
[css-multicol] pseudo-algorithm refers to "track size", terminology not already used in the spec

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#3649]
In a workshop with a group of authors it was noted that the pseudo-algorithm (https://drafts.csswg.org/css-multicol-1/#pseudo-algorithm) refers to track size. However this is the first time that _tracks_ are mentioned in the multicol spec.

This was added based on this [resolution](https://lists.w3.org/Archives/Public/www-style/2016Jan/0031.html), to unify grid and flexbox. However it seems that we need to define tracks somewhere as the sudden appearance of this stood out to authors.

**Comment by frivoal** [comment]
Referring to columns would seem more appropriate there. Unless the meaning is intended to be different somehow, in which case we really need a definition :)

**Comment by rachelandrew** [comment]
I think this should be columns, I don't see any reason to say tracks, so I suggest that we edit this to say:

> For the purpose of finding the number of columns, the UA must floor the column size to a UA-specified value to avoid division by zero. It is suggested that this floor be 1px or less.

I'll add it to the agenda of a future call as it was put in there based on a resolution.
