### ISSUE TITLE
[css-shapes] Serialization of `circle(at center)` contradicts itself

### ISSUE THREAD

**Issue by Manishearth** [w3c/csswg-drafts#365]
https://drafts.csswg.org/css-shapes/#basic-shape-serialization

The spec mentions that while serialization, we should:

> \[omit] components when possible without changing the meaning

However, in the examples below, it also mentions that `circle(closest-side at center)` should serialize to `circle(at 50% 50%)`. Earlier it's mentioned that `at center` is the default, so really this should be `circle()`.

**Comment by astearns** [comment]
The <position> values serialize to their 2- or 4-value forms only, so even a default circle() gets forced into it's 2-value form. I don't precisely recall the reason we settled on this, but it is one less code path for checking the serialized value. Do you have a reason to prefer adding the 0-value form for this one case, or were you just checking for consistency in the examples?

**Comment by Manishearth** [comment]
No, just checking for consistency. Could this be more explicitly mentioned? As it stands this is only concretely specified by the examples; the spec text itself should be clearer about this.

**Comment by astearns** [comment]
Thanks for checking!

It is mentioned in the second paragraph of 3.3 above the examples. I've added "(including the defaults)" to the normative text to make this particular case more explicit.

**Comment by fantasai** [comment]
On 08/01/2016 09:45 AM, astearns wrote:
> Closed #365 <https://github.com/w3c/csswg-drafts/issues/365>.

Would be worth putting on the agenda; I'm not super familiar with
the serialization rules, but I don't recall any other examples
where CSS doesn't drop optional default values in a serialization.

~fantasai
