### ISSUE TITLE
[css-logical] More shorthands, e.g. margin-start

### ISSUE THREAD

**Issue by valtlai** [w3c/csswg-drafts#3651]
Spec: https://drafts.csswg.org/css-logical/#box

I would propose more flow-relative shorthand properties:

| Property | Corresponds to
|---|---
| margin-start | margin-block-start, margin-inline-start
| margin-end | margin-block-end, margin-inline-end
| inset-start | inset-block-start, inset-inline-start
| inset-end | inset-block-end, inset-inline-end
| padding-start | padding-block-start, padding-inline-start
| padding-end | padding-block-end, padding-inline-end
| border-start | border-block-start, border-inline-start
| border-end | border-block-end, border-inline-end

They could make CSS more DRY.

```css
/* For example, the following: */
inset-start: 0;

/* would be equivalent to: */
inset-block-start: 0;
inset-inline-start: 0;

/* and sometimes to: */
inset: 0 auto auto 0;
```

There’s already shorthands for the block and inline directions (e.g. `margin-block`, `margin-inline`) but not for the start or end directions (`margin-start`, `margin-end`).

**Comment by Loirooriol** [comment]
Are you asking just for completeness, or do you have some usecase where this would be useful?

**Comment by valtlai** [comment]
@Loirooriol The example is an use case, but I wonder maybe there’s more where the properties I propose would make CSS more DRY. I agree these shouldn’t be just for completeness.

So, if anyone has more use cases, please comment.

**Comment by jonjohnjohnson** [comment]
If I ever want to set multiple offsets/edges to the same value, it's (almost always) either in the same axis or it's in all edges. It's rare where I've only wanted both start/end edges to have the same value, and even when, I don't think it's meaningful to have a shorthand for `-start` properties compared to when I equally rarely set the same value to adjacent start and end properties, such as `inset-inline-end` alongside `inset-block-start`. Simply, I don't think the starts and ends in opposing axes share much in common in most cases, unlike the axis shorthands, `-inline`/`-block`.
