### ISSUE TITLE
[css-text-4] text-wrap:multi-line value is removed , but still mentioned in the note

### ISSUE THREAD

**Issue by SergeyMalkin** [w3c/csswg-drafts#3652]
"The multi-line and balance values are intended as opt-in choices to take more time for better results"

https://github.com/w3c/csswg-drafts/blob/78dc281b2c8454d763dd3d4cef728cbe4a300256/css-text-4/Overview.bs#L272

**Comment by xfq** [comment]
For the record, it was removed in https://github.com/w3c/csswg-drafts/commit/a0c27afa0a50c462584511e617a20b687eb892af

**Comment by xfq** [comment]
CSSWG has resolved to add it back (see https://github.com/w3c/csswg-drafts/issues/672#issuecomment-468069570), so closing this issue.
