### ISSUE TITLE
[css-overflow-3] Define how child margin-boxes contributes to scrollable overflow (ISSUE 6)

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3653]
https://drafts.csswg.org/css-overflow-3/#scrollable
> The UA may additionally include the margin areas of boxes for which it is the containing block.
> The conditions under which such margin areas are included is undefined in this level.
> ISSUE 6. This needs further testing and investigation; is therefore deferred in this draft.

Firefox and Chrome handles margins differently (see testcases in [bug 1527539](https://bugzilla.mozilla.org/show_bug.cgi?id=1527539)).  This might lead to web-compat problems.
It looks like Chrome includes the block-end margin of children when calculating the overflow for Grid and Flexbox layout, whereas Firefox doesn't.  Both includes it in block layout though, well at least in most cases...  (exact details TBD)

(Fwiw, the relevant block layout code in Gecko lives [here](https://searchfox.org/mozilla-central/rev/e6520f0a4dd5d7474c32a1164744953ea59be0d0/layout/generic/nsBlockFrame.cpp#1522-1565) in case anyone wants to decipher when the margin is included in `blockEndEdgeOfChildren` there.)

**Comment by upsuper** [comment]
It's worth checking with Chrome team about their behavior of LayoutNG, their next generation layout engine. I have heard that for many cases, they have different behavior than their current engine.

**Comment by emilio** [comment]
cc @kojiishi @bfgeek, do you know what does LayoutNG do here?

**Comment by fantasai** [comment]
Probably should include margins here, alongside padding. Same principle: authors expect spacing to be there when they request spacing, regardless of which side of the scrollbox the item is on. Agenda+ to discuss.

Previous resolutions related to this topic: https://github.com/w3c/csswg-drafts/issues/3665
