### ISSUE TITLE
[css-animations-1] Spelling error under section 4.2

### ISSUE THREAD

**Issue by impressivewebs** [w3c/csswg-drafts#366]
https://drafts.csswg.org/css-animations-1/#valdef-animation-name-keyframes-name

It says:

> The animation will use the keyframes with the name specified by the `<keyframes-name>`, if they exist. If no @keyframes rule with tha name exists, there is no animation.

I'm assuming "tha" should be "that".

**Comment by praveenpuglia** [comment]
Can I send a PR for this? I know this is so obvious but the idea of sending a PR to CSSWG thrills me! :)

**Comment by astearns** [comment]
please do!
