### ISSUE TITLE
[resize-observer] disconnect(): Remove this from Document.resizeObservers slot.

### ISSUE THREAD

**Issue by cathiechen** [w3c/csswg-drafts#3662]
https://drafts.csswg.org/resize-observer-1/#dom-resizeobserver-disconnect

> 3. Remove this from Document.resizeObservers slot.

There might be an issue.
If disconnect() is called in callback, we are deleting the observer from Document.resizeObservers which is in use.

**Comment by gregwhitworth** [comment]
Thank you so much - great catch, in order to fix this issue we've removed the following:

> Remove this from Document.resizeObservers slot.

This is currently how it is implemented in Chromium today. Let us know if you have any other feedback.

**Comment by cathiechen** [comment]
Great! Thanks :)
