### ISSUE TITLE
[css-media-queries-5] environment-blending use cases

### ISSUE THREAD

**Issue by SCKelemen** [w3c/csswg-drafts#3666]
In [Section 2.2 (Detecting the display technology: the environment-blending feature)](https://drafts.csswg.org/mediaqueries-5/#environment-blending) of the [Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5) specification, [Issue 4](https://drafts.csswg.org/mediaqueries-5/#issue-c4eeab17) questions the need for the [subtractive blending mode](https://drafts.csswg.org/mediaqueries-5/#valdef-media-environment-blending-subtractive). Another consideration for this feature could include e-ink displays such as e-readers, as well as other e-ink display such as the e-ink barcodes. A subtractive mode, combined with the proposed [Light-Level](https://drafts.csswg.org/mediaqueries-5/#light-level) query and the screen [update](https://www.w3.org/TR/mediaqueries-4/#update) query could provide useful semantics for targeting e-ink displays. E-Ink displays are evolving, and now support multiple colors. They are composed of multiple layers of colored particles which overlap each layer. These color layers don't usually mix.

**Comment by tabatkins** [comment]
e-ink displays are "opaque" in this feature, no? The display is a combination of the (dark) ink and the (light) opaque display; there's not really any transparency. This is distinct from the subtractive example given, such as mirrors, where "white" is actually "whatever the mirror is showing".

**Comment by SCKelemen** [comment]
🤔  
hmmm, I didn't read it that way. I guess that make sense, but let me consider it a bit longer.

**Comment by tabatkins** [comment]
It could be made clearer, definitely. The intent is to capture whether the screen colors are *totally* under the author's control, or if dark/light colors instead show something outside of their control.

**Comment by SCKelemen** [comment]
I agree. I think my previous suggestion applies given this information, but I the specification could probably be made clearer.
