### ISSUE TITLE
[css-flexbox] "Changes" section is missing a change

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#3668]
There is no mention of this change in the changelog at the end of the spec:
https://drafts.csswg.org/css-flexbox/#changes

https://github.com/w3c/csswg-drafts/commit/60dc925ff47587dbdb2f487a64da098bdf60d745

**Comment by cbiesinger** [comment]
That is, https://github.com/w3c/csswg-drafts/commit/60dc925ff47587dbdb2f487a64da098bdf60d745 is not mentioned in https://drafts.csswg.org/css-flexbox/#changes

**Comment by fantasai** [comment]
I believe it is mentioned here: https://drafts.csswg.org/css-flexbox/#change-201403-max-intrinsic

**Comment by fantasai** [comment]
Here's the email that raised that issue (since it was filed before GH): https://lists.w3.org/Archives/Public/www-style/2014Aug/0277.html
