### ISSUE TITLE
[css-flexbox] min size of flex items: specified size has superfluous requirement?

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#3669]
https://drafts.csswg.org/css-flexbox-1/#min-size-auto says

> the content-based minimum size of a flex item is the smaller of its content size suggestion and its specified size suggestion.

Then both content size suggestion and specified size suggestion are clamped by the max main size property if that is definite.

I think specified size doesn't need to be clamped by its max main size property if content size is, because min(min(specified, max), min(content, max)) == min(specified, min(content, max))

If that's right, then the parenthetical can be removed from https://drafts.csswg.org/css-flexbox-1/#specified-size-suggestion

> If the item’s computed main size property is definite, then the specified size suggestion is that size ~~(clamped by its max main size property if it’s definite)~~. It is otherwise undefined.

If that's wrong, and there's a case where clamping matters, please let me know so I can implement it in Blink! :)

/cc @cbiesinger

**Comment by fantasai** [comment]
I think while you are technically correct, the formula simplifies down in the way you describe, it's easier to understand what's happening if we clamp each input first (that way it's clear no matter what, we've always clamped to the correct range), and then do the comparisons.

**Comment by fantasai** [comment]
Please let me know if you're OK with this conclusion!

**Comment by davidsgrogan** [comment]
Sounds fine, as long as we're on the same page about behavior, which looks like we are.
