### ISSUE TITLE
mysqli_connect failure in drafts.csswg.org

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3672]
https://drafts.csswg.org/ is down:

> WARNING: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

cc @plinss

**Comment by Loirooriol** [comment]
It's working fine now.

**Comment by plinss** [comment]
We've been getting hit periodically by a badly behaved spambot which effective DoSs the site crashing the DB server. I'm working on countermeasures.

Thanks for the report, but I have two different monitoring services that notify me when the site goes down, so it generally isn't necessary to report issues like this. If it's down and not back up in a few minutes, I'm either asleep or somewhere where I can't get to the server.

**Comment by Malvoz** [comment]
This is happening again.
