### ISSUE TITLE
[css-sizing-3] Add definition for "intrinsic size"

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3680]
We have definitions for a lot of sizing terms, but not "intrinsic size". We should add it.

**Comment by Loirooriol** [comment]
Isn't this already in https://drafts.csswg.org/css-sizing/#intrinsic-sizes?

**Comment by frivoal** [comment]
It kind of is, except the term "intrinsic size" itself isn't defined with a `<dfn>`, causing attempts to cross link to it as a defined term using bikeshed to fail.
