### ISSUE TITLE
[css-color] context aware transparent

### ISSUE THREAD

**Issue by waterplea** [w3c/csswg-drafts#3682]
https://drafts.csswg.org/css-color/#transparent-color

Right now keyword `transparent` equals to `rgba(0, 0, 0, 0)` and Safari is the only browser that follows it. Yes, even IE interprets it smartly. That is if we make linear gradient from blue to transparent all browsers will interpret it as rgba(0, 0, 255, 1) to rgba(0, 0, 255, 0). This is great and every browser does so, however for Safari you cannot write color transitions like that and have to specify both colors explicitly.

**Comment by jonjohnjohnson** [comment]
@waterplea I think your concerns are covered/solved in the resolution of https://github.com/w3c/csswg-drafts/issues/2722

If so, this could be closed as a duplicate. If not, maybe describe what you think is missing in reference to the commit f6909a1 that closed it out?

**Comment by waterplea** [comment]
Right, sorry, didn't find it in search
