### ISSUE TITLE
[css-lists] Make it clear what repeating a counter name in counter-increment/set/reset does

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3687]
The spec is very unclear about what happens when you use the same counter name multiple times in the counter-* properties. In implementations, `counter-increment: foo 1 foo 1;` is equivalent to `counter-increment: foo 2;`. Similarly, `counter-reset: foo 0 foo 2` is equivalent to `counter-reset: foo 2`.

So the clear answer is that we iterate the list of counter/value pairs, handling each in turn. Repeating a name is valid.

**Comment by fantasai** [comment]
CSS2 is very clear on this point fwiw: https://drafts.csswg.org/css2/generate.html#counters

**Comment by fantasai** [comment]
I believe this is now clear:

- counter-reset now specifies “If multiple instances of the same <counter-name> occur in the property value, only the last one is honored.”
- counter-increment and counter-set now specify “If multiple instances of the same <counter-name> occur in the property value, they are all processed, in order. Thus increments will compound, but only the last set value will take effect.”

**Comment by fantasai** [comment]
Marked Obvious Bugfix because we're syncing with CSS2.1
