### ISSUE TITLE
[css-overflow-3] -webkit-line-clamp need not support a <'block-ellipsis'> value

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#3695]
https://drafts.csswg.org/css-overflow-3/#webkit-line-clamp

The new definition of -webkit-line-clamp looks good, but now that we are not trying to make it a pure alias for line-clamp, we should not support parsing the <'block-ellipsis'> value in it.  This isn't supported by implementations.

**Comment by frivoal** [comment]
Closed by merging: https://github.com/w3c/csswg-drafts/commit/fd2db4a3642f3b56ab1a90695a587aa173579032
