### ISSUE TITLE
[css-grid] The value of the fixed track sizing function doesn't seem to matter when resolving intrinsic track sizes

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3706]
From https://drafts.csswg.org/css-grid/#algo-spanning-flex-items,

> Increase sizes to accommodate spanning items crossing flexible tracks: Next, repeat the previous step instead considering (together, rather than grouped by span size) all items that do span a track with a flexible sizing function while [...] distributing space only to flexible tracks (i.e. treating all other tracks as having a fixed sizing function **of their current base size**)

If I'm not missing anything, the "Resolve Intrinsic Track Sizes" algorithm doesn't use the value of the track sizing function in case it's fixed. So it doesn't seem to matter whether it's treated as the current base size, 0, 100px, or any other fixed value. I think the sentence could be shortened to

> distributing space only to flexible tracks (i.e. treating all other tracks as having a fixed sizing function)

**Comment by fantasai** [comment]
That wouldn't explain what value to use as the fixed sizing function. The current wording says to use the current base size. Fixed tracks will have their base sizes set to that size already in https://drafts.csswg.org/css-grid-1/#algo-init

**Comment by Loirooriol** [comment]
Exactly, https://drafts.csswg.org/css-grid-1/#algo-init uses the value of fixed track sizing functions in order to set initial base sizes and growth limits. But https://drafts.csswg.org/css-grid-1/#algo-content doesn't seem to care about the value of fixed track sizing functions, it references base sizes and growth limits instead.

So what I'm saying is that https://drafts.csswg.org/css-grid/#algo-spanning-flex-items is overriding the track sizing function of some tracks, but not their base sizes nor growth limits. It's these base sizes and growth limits what will be used when doing the "repeat the previous step". The specific value of the overriding track sizing function won't be used anywhere, so it doesn't matter.

Since it doesn't matter it's fine if you want to leave it as "their current base size", I was just suggesting that the sentence can be simplified.
