### ISSUE TITLE
[css-scroll-snap] Make it more obvious that scroll-padding/scroll-margin have effects outside snap containers

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3721]
This seems to be a common slip-up, which isn't surprising, since the spec was originally written to only apply to snap containers.

**Comment by jonjohnjohnson** [comment]
https://github.com/w3c/csswg-drafts/issues/2428

**Comment by fantasai** [comment]
Agenda+ to request republication.

**Comment by jonjohnjohnson** [comment]
@fantasai if you think the changes and upcoming discussion in this issue warrant closing #2428, please do so. I'll be glad it's at least covered here, even if slightly discouraged that something I thoughtfully filed flew under the radar.
