### ISSUE TITLE
[css-variables] Token sequence size limit

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#3733]
Should we add a size/complexity limit on the token sequence produced by var()-references?

@emilio created [a test](https://github.com/web-platform-tests/wpt/blob/master/css/css-variables/variable-exponential-blowup.html) which (if allowed to complete) would spend 30GB+ (IIRC). This test uses JS, but it's easy to achieve the same with just manually typing 30ish lines of CSS.

Sidenote: Mozilla [already added](https://hg.mozilla.org/integration/autoland/rev/3e5ea9da2cbb) a 1MB limit.

**Comment by AmeliaBR** [comment]
A limit of some sort makes sense (and should be documented) but it should be set to be as large as any legal value you support for a CSS property — including data URIs for images.

**Comment by Loirooriol** [comment]
Please don't enforce a specific maximum, see https://github.com/w3c/csswg-drafts/issues/3462#issuecomment-451322112

> Must support up to X <del>degree of nesting</del> <ins>size</ins>; can support more but are not required to; must fail in a particular standardized way when the limit is exceeded.

**Comment by tabatkins** [comment]
Yup, I'm fine with specifying that limits are allowed (and encouraged!). The best behavior is likely just "drop all tokens after the limit".

**Comment by AmeliaBR** [comment]
> The best behavior is likely just "drop all tokens after the limit".

Wait, so you're suggesting they should pass through part of the value?  That seems very bad and inconsistent with normal CSS error handling.  I'd say that if you can't handle the entire value as set by the author, you treat it as an invalid declaration or invalid result of a `var()` function.

**Comment by tabatkins** [comment]
Yeah, you're right.

**Comment by tabatkins** [comment]
@emilio In the WPT for this, Firefox still times out. Is your mitigation recent or something, and not yet picked up by the WPT bots?

**Comment by tabatkins** [comment]
Ah, looks like the FF fix was backed out for linting failures. ^_^  Welp, it's a nice failing test for everyone right now, then.

**Comment by emilio** [comment]
Which version of Firefox are you using? It landed in 65 (it surely relanded, otherwise the test wouldn't be upstream). https://cras.sh/crash.html doesn't crash on Firefox, for that matter, nor does http://w3c-test.org/css/css-variables/variable-exponential-blowup.html.

Or am I missing something? I'd be interested if so :).

**Comment by tabatkins** [comment]
I'm not using anything, but the WPT TaskCluster instance, apparently using FF Nightly, is timing out on [my test](https://github.com/web-platform-tests/wpt/pull/15875):
<https://tools.taskcluster.net/groups/NeZQtx9rQ6O08PnfyLtA4Q/tasks/UqF3N5yyQ3-1Zie-2K47UA/runs/0/logs/public%2Flogs%2Flive.log>.

(I didn't realize you'd committed a similar test already.)

**Comment by tabatkins** [comment]
The only difference I can see is that I wrote mine out manually, vs yours in JS (shouldn't be a difference) and mine expands to 10^20 at max, while yours tops out at 2^30 (~10^12).

**Comment by emilio** [comment]
That test doesn't test anything? It doesn't have a `test(function() {})`?

**Comment by tabatkins** [comment]
Doesn't need to; a vacuous test passes as long as it doesn't crash.

**Comment by tabatkins** [comment]
(At least according to @domenic ^_^)

**Comment by emilio** [comment]
I'm pretty sure that's not the case. I can reproduce the timeout if I check out your test locally, but that's because the harness expects at least one test to run.

As soon as I apply:

```diff
diff --git a/css/billion-laughs.html b/css/billion-laughs.html
index 0d80bbb7d7..648d750e09 100644
--- a/css/billion-laughs.html
+++ b/css/billion-laughs.html
@@ -46,3 +46,9 @@ an impl that correctly implements the mitigation described in the spec
 will instead execute this no-op page
 and thus "pass" it by default.
 -->
+<script>
+let t = async_test("Foo");
+onload = t.step_func_done(function() {
+  document.documentElement.offsetTop; // ensure layout runs.
+});
+</script>
```

The test passes just fine as expected. @jgraham do you know what's the expected behavior of a test without a test function?

**Comment by tabatkins** [comment]
Ah, kk. Well, since your test already exercises the functionality anyway, I'll go ahead and delete mine. ^_^

**Comment by tabatkins** [comment]
Domenic clarifies that he said "a test without assert()", not "a test without test()", tho he recognizes the distinction wasn't particularly clear. ^_^

**Comment by emilio** [comment]
Ah, that's true :)
