### ISSUE TITLE
[css-fonts] consider not making font-min-size and font-max-size affect font-size computed value

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3739]
Spec: https://drafts.csswg.org/css-fonts-4/#propdef-font-min-size

I think these two properties should only affect the used font-size value, not the computed one.

It's a bit weird that, as specified, `font-min-size`s computed value affects `font-max-size`s _used_ value, but `font-size`s _computed_ value.

Affecting the computed value implies that it also affects font-relative lengths. This causes unintended consequences when users override it with a larger font size, like:

https://bugs.chromium.org/p/chromium/issues/detail?id=937689

In Gecko the user-preferred minimum font-size only affects the used font-size, which I think has less potential to break websites.

**Comment by emilio** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=944002 is another example of site broken on chromium when overriding author preferences.

**Comment by fred-wang** [comment]
Another argument in favor of this proposal is for the implementation of math-script-level ( #31 ). The computed font-size can be decreased/increased by increasing/decreasing the script-level. This can be reverted by decreasing/increasing the script-level by the same amount. However, that's no longer possible if the computed font-size is clamped by font-min-size/font-max-size when it goes below/above the min-size/max-size.

**Comment by litherum** [comment]
@fantasai

**Comment by svgeesus** [comment]
I saw this counter-argument [on the chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=937689#c10):

> Our behavior here is intentional, we choose to respect the users minimum font size over what the site has specified. This is an accessibility feature and we consider legibility to be the more important consideration in this case.

**Comment by fantasai** [comment]
If an author is using em and rem units correctly (i.e. for things that should scale with the text), then they need to match the font size that is actually in use. E.g. `line-height: 1em` will overlap text if you resolve ems before applying `font-min-size`. Likewise paddings, margins, and images designed to be multiples of the text size should be keying off the actual used font size and not some theoretical value that's not being used.

**Comment by fred-wang** [comment]
> In Gecko the user-preferred minimum font-size only affects the used font-size, which I think has less potential to break websites.

I removed the math-script-level tests for font-min-size and font-max-size and instead replace it with a test to check interaction with user-preferred minimum font-size: https://github.com/web-platform-tests/wpt/pull/17228
