### ISSUE TITLE
[css-pseudo] Highlight pseudo-el cascade rules doesn't match reality

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#374]
All browsers (now?) agree in nearly all details for how to render ::selection (and presumably will apply the same to the other highlight pseudo-els). However, the spec text _drastically_ conflicts with this.

In particular, IE/FF/Blink all:
- have some default UA styles for the highlight
- each element's segment of the highlight is styled according to _that element's_ ::selection rules
- if a given element doesn't style the highlight at all, it uses the UA rules (instead of inheriting them from the originating element or using initial values)
  
  (Definition of "doesn't style at all" is slightly inconsistent - all agree that an empty style rule for the element doesn't style it, and all agree that a highlight-valid property in the style rule does style it. IE assumes that a property that doesn't apply to the highlight (such as `display`) doesn't count as styling, while FF and Blink treat it as styled.)

There was some discussion/resolution about this in the past, of which the current spec text is apparently the result, but iirc browsers previously didn't agree as strongly so we believed there was some room to dictate a maximally "useful" result. However, they currently strongly agree (with only very minor differences) on what I described above. We should change the spec to match current browser behavior, which, while not _ideal_, is serviceable, simple, and mostly consistent with how other pseudo-elements work.

**Comment by fantasai** [comment]
The current mismatch you're complaining about (that an unstyled ::selection uses the initial styles, not that of its parent ::selection), is not even useful, not just “not ideal”. I'm open to discussing this, but I also think we should consider what would actually be useful to Web authors, not just what's currently implemented.

**Comment by tabatkins** [comment]
The vast majority of ::selection styling is simple whole-page theming, with a naked `::selection { ... }` selector. That sort of usage doesn't care which strategy we use.

So then it's a question of whether making a much less common usage of the feature work somewhat better is worth the *significantly* increased complexity of a completely novel inheritance algorithm.

**Comment by fantasai** [comment]
(Added to the TPAC agenda.)

**Comment by gregwhitworth** [comment]
I disagree with the statement that everything seems the same. Unless I'm missing something here, I think this is a decent testcase to what you're referring to: http://jsbin.com/xamafaxudu/edit?html,css,output

**Dragging selection from basic paragraph to psuedo:**
Chrome: No styles
Edge: Styles
Firefox: No styles on the paragraph nor the psuedo

**Double clicking the psuedo content:**
Chrome: No styles
Edge: No styles
Firefox: No styles

**Double clicking the paragraph:**
Chrome: Styles
Edge: Styles
Firefox: No Styles

Again, I may be missing something here, but at the very least there is a decent amount of interop issues here. I personally prefer the Edge behavior but think that the double clicking should behave the same as a regular box.

**Comment by dbaron** [comment]
See [a post I wrote in 2008](https://lists.w3.org/Archives/Public/www-style/2008Oct/0268.html) layout out options for fixing `::selection`.

**Comment by upsuper** [comment]
> Dragging selection from basic paragraph to psuedo:
> Chrome: No styles
> Edge: Styles
> Firefox: No styles on the paragraph nor the psuedo
> 
> Double clicking the psuedo content:
> Chrome: No styles
> Edge: No styles
> Firefox: No styles

So what's happening here is that, Gecko doesn't allow selecting pseudo content consistently, and Blink and Edge allow that in some case but not others.

> Double clicking the paragraph:
> Chrome: Styles
> Edge: Styles
> Firefox: No Styles

There are two possible reasons for this:
1. Gecko currently only supports prefixed `::-moz-selection` while your testcase only includes `::selection`
2. There is probably some bug in Gecko that selection inside `<iframe>` isn't style correctly. When I pop out the result to whole page, it seems that the selection is styled as expected.

**Comment by upsuper** [comment]
> There is probably some bug in Gecko that selection inside <iframe> isn't style correctly. When I pop out the result to whole page, it seems that the selection is styled as expected.

This seems to be some issue specific to how JS Bin works... it doesn't seem to be a general issue, and I have no idea how it happens at the moment... I've filed [a Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1415264) for this.

**Comment by dbaron** [comment]
Though actually all 6 links in [section 3.3](https://drafts.csswg.org/css-pseudo/#highlight-bounds) are probably relevant.

**Comment by fantasai** [comment]
See also the [previous WG discussion on ::selection](https://lists.w3.org/Archives/Public/www-style/2014Dec/0299.html).

**Comment by fantasai** [comment]
Closing this issue in favor of https://github.com/w3c/csswg-drafts/issues/2474
