### ISSUE TITLE
[css-scroll-snap-1] Clarify that scroll-padding and scroll-snap-type on root propagate to viewport

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3740]
We propagate various properties that control overflow from the root to the viewport, e.g. `overflow`, `scrollbar-width`, etc. `scroll-snap-type` and `scroll-padding` aren't expected to be any different about this point, but it probably should be stated explicitly (as it is in css-scrollbars).

**Comment by fantasai** [comment]
Agenda+ to confirm substantive change, republish CR.

**Comment by hiikezoe** [comment]
@fantasai, if I understand correctly the agreement on the IRC log, [Example 5](https://drafts.csswg.org/css-scroll-snap-1/#example-9c13f414) should use html instead of body?  I am confused about the example.

**Comment by fantasai** [comment]
@hiikezoe Yes. Thanks. Fixed. :)
