### ISSUE TITLE
[css-backgrounds] `background-size` at-risk?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3742]
The [background-size](https://drafts.csswg.org/css-backgrounds-3/#background-size) property should probably be marked at-risk. [Test results show](https://test.csswg.org/harness/results/css-backgrounds-3_dev/grouped/filter/1/) that there is only one passing implementation, Gecko.

A bug should be filed on Safari. [Chrome has a bug already](https://bugs.chromium.org/p/chromium/issues/detail?id=942975)

It isn't the entire property which is problematic, just the case where one of width or height is specified on an SVG background image. `background-size` with two `[ <length-percentage> | auto ]` values with SVG image with _omitted width_ and _non-percent height_ 

So this looks like a fairly tractable bug to fix and meet CR exit criteria and get interop.

**Comment by fantasai** [comment]
I feel like they should just fix the bug? Alternately we can mark this particular case undefined, if it's blocking REC.
