### ISSUE TITLE
[media-queries][css-sizing] Support <number> (and therefore calc) as a <ratio>

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#3757]
The new [`aspect-ratio` property in css-sizing-4](https://drafts.csswg.org/css-sizing-4/#aspect-ratio) re-uses [the `<ratio>` data type defined for the aspect-ratio media query](https://drafts.csswg.org/mediaqueries-4/#aspect-ratio), which currently only excepts rational fractions defined as `<integer> / <integer>`.

For flexibility, I propose extending the `<ratio>` type to support:

- a single `<number>` value (so that you could specify `aspect-ratio: 1.5` instead of `aspect-ratio: 3/2`)

- maybe, an arbitrary numerical fraction (`aspect-ratio: 3.3/2.2`)

- maybe, a fraction of lengths (`aspect-ratio: 1ch/1em`)

The "maybes" are because — for the property, if not the media query — they could be replaced with `calc()` functions if (a) a single number value (the result of the math expression) is accepted as a ratio, and (b) for length fractions, [calc division of values with units](https://drafts.csswg.org/css-values/#calc-type-checking) is actually implemented.

**Comment by jonjohnjohnson** [comment]
@AmeliaBR Quick question, maybe you can infer from the spec text better than I, before I open up a separate ticket... I see mention of `inline-size` and `block-size` and writing modes in relation to [Example 3](https://drafts.csswg.org/css-sizing-4/#ref-for-horizontal-writing-mode) specifically. But should I assume `aspect-ratio` will simply be physical mapping x/y, then hopefully receives the eventual [Flow-Relative Keyword](https://github.com/w3c/csswg-drafts/issues/1282) for logical mapping?

**Comment by AmeliaBR** [comment]
@jonjohnjohnson That's actually a really good question — mind opening a separate issue?

**Comment by jensimmons** [comment]
Before we decide anything, please read this page about aspect ratios: https://en.wikipedia.org/wiki/Aspect_ratio_(image)

It's common to express an aspect ratio as a ratio — for example `16/9` is expressed as `1.77:1`. Or shortened to `1.77`. I'd rather we don't invent new web-only ways to express something.

**Comment by AmeliaBR** [comment]
@jensimmons So, you're saying that a single number with decimals is sensible, in addition to the ratio of integers, but everything else is just complicating things without benefit? (and, as I noted in the first issue, can be replaced with `calc`, anyway)

**Comment by tabatkins** [comment]
I agree that we should widen the grammar to `<number> / <number>`; restricting it to `<integer>` doesn't match common practice and doesn't actually help us with anything.

Given that, I don't think we need to provide a single-number pattern; `1.77 / 1` seems fine?

**Comment by jonjohnjohnson** [comment]
I'd be remiss to not bring up @jensimmons comment about calc'n on top of aspect ratio behavior on the grid related issue...

> Fluid video (that has an aspect ratio, like 16x9), with fixed-height controls running along the length of the video directly underneath. 
>```
>.video {
>  width: 100%;
>  height: calc(.5625tr + 25px);
>}

https://github.com/w3c/csswg-drafts/issues/333#issuecomment-432230212

Could it be possible to support this somehow with `calc()` in the `aspect-ratio` property? The only way I imagine this behavior would be covered, albeit using extra elements, [is if `box-sizing` being set to `content-box`](https://github.com/w3c/csswg-drafts/issues/4007), then offset the ratio size by using `padding`/`border` with a descendant was positioned accordingly?

**Comment by tabatkins** [comment]
Yes, using a-r on the content box, then using padding/border to get the extra space, is the only way (currently) to do that. We should probably track that case tho (an aspect ratio, plus/minus some extra space in either or both axises) as another issue.

**Comment by emilio** [comment]
How should this serialize? The current proposed patch for the feature in Firefox serializes `1.77` as `1.77 / 1`.

I think we should omit the `/ 1` part if the denominator is one. That is technically a breaking change, since if you wrote `(aspect-ratio: 2 / 1)`, you'd get `(aspect-ratio: 2)` rather than the historic `(aspect-ratio: 2 / 1)`, but I think we should be able to get away with it. Thoughts?

**Comment by emilio** [comment]
(Proposed patch is at https://bugzilla.mozilla.org/show_bug.cgi?id=1565562).

**Comment by emilio** [comment]
Also, how should ranges here work? Right now we're enforcing positive-integers at parse time, but doing positive numbers seems against common behavior of having open ranges.

**Comment by AmeliaBR** [comment]
Yes, if we allow arbitrary decimal numbers (0.0000000001) than we need to allow 0 for consistency with the rest of CSS.  There's some wording about handling zero in the width/height media queries that might be relevant here.

For serialization, I think backwards compatibility is worth maintaining. So is keeping numeric precision: we shouldn't turn and exact `2/3` into an imprecise decimal. So, either keep the value as specified (fraction or number) or always insert the redundant `/1` if the specified value was a single number.

**Comment by fantasai** [comment]
+1 to @AmeliaBR's comment. We do have a principle to serialize to the not-shortest representation when the shortest one is less backwards-compatible, and this would be such a case.

**Comment by emilio** [comment]
What do we want to do with stuff like `0/0` and such?

**Comment by AmeliaBR** [comment]
> What do we want to do with stuff like 0/0 and such?

We have a separate discussion about that in #3768 when it comes to calc, and decided to serialize as is. So, I guess the same could apply here.

**Comment by carlosame** [comment]
Unless I'm missing something, the new syntax would allow ratios composed by `calc()` values like `aspect-ratio: calc(...) / calc(...)`, is that right?

Why not do that with just a single `calc()` and leave ratios as integers?

**Comment by emilio** [comment]
That is right. But you already can do `aspect-ratio: calc(..) / calc(..)` as long as they end up resolving to an integer, right? So that wouldn't be backwards compatible.

**Comment by carlosame** [comment]
> But you already can do `aspect-ratio: calc(..) / calc(..)` as long as they end up resolving to an integer, right?

Not in my implementation, and I guess that was a bug then...

**Comment by fantasai** [comment]
Negative numbers are not allowed in `<ratio>`, see https://www.w3.org/TR/mediaqueries-4/#aspect-ratio
The rules for calc() will clamp negative values accordingly.

**Comment by AmeliaBR** [comment]
> Negative numbers are not allowed in <ratio>

That's the existing syntax, the question is whether to keep that when switching to `<number>`.  This is important when using calc values: do the results of the calc values get clamped to be no less than 0 before or after you do the division? E.g., is something that computes to `calc(-10) / calc(-5)` a valid ratio equal to 2/1, or is it an invalid 0/0 ?

I added a few more tests to my [CodePen](https://codepen.io/AmeliaBR/pen/8458d7a2c47d923f12165a9c7c01f252?editors=0111), currently calc expressions that evaluate to negative values seem to be clamped to 0 then discarded because 0 is also invalid?

**Comment by carlosame** [comment]
I'd appreciate a comment about how precision would affect the matching of media queries when numbers with decimals are used. Consider a viewport or page with a 4/3 ratio, and the following media feature tests:

`max-aspect-ratio: 4/3`
`max-aspect-ratio: calc(4/3)`
`max-aspect-ratio: 1.3333`

My current code would match the first two, but not the third. What if more decimals were added to it?

Perhaps that is specified in a more general way elsewhere, but could not find it.
