### ISSUE TITLE
[css-color] "full numbers, not just integers"?

### ISSUE THREAD

**Issue by impressivewebs** [w3c/csswg-drafts#376]
Re: https://drafts.csswg.org/css-color/#rgb-functions

In the description of the rgb functions it says, in part:

> the CSS syntax allows full `<number>`s, not just `<integer>`s, for authoring convenience

This seems to imply that the numbers can be decimals (e.g. `rgb(3.4, 34.6, 144.7)`. The [number type description](https://drafts.csswg.org/css-values-3/#number-value), which the above quote links to, explains that a `<number>` can be fractional. But I don't see this working in an rgb function. Can this section clarify a little better what exactly is meant by "full numbers, not just integers"?

**Comment by SebastianZ** [comment]
> This seems to imply that the numbers can be decimals (e.g. rgb(3.4, 34.6, 144.7). The number type description, which the above quote links to, explains that a <number> can be fractional.

Correct. That is because the `<number>` values in CSS Colors 4 is a relaxation of the [definition in CSS Colors 3](https://drafts.csswg.org/css-color-3/#rgb-color), which only allowed `<integer>` values.

> But I don't see this working in an rgb function.

As far as I know, there is no user agent supporting this yet.

Sebastian

**Comment by tabatkins** [comment]
Correct, UAs just haven't caught up to this yet.

**Comment by impressivewebs** [comment]
Ah ok... Good to know. Thanks guys.

**Comment by SebastianZ** [comment]
FWIW, I've just created an [enhancement request](https://bugzilla.mozilla.org/show_bug.cgi?id=1291878) for Gecko asking for this.

Sebastian
