### ISSUE TITLE
[css-lists][css-pseudo] Add ::marker to interface CSSPseudoElement

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3763]
https://drafts.csswg.org/css-pseudo-4/#csspseudoelement

Firefox is shipping support for ::marker in v68, including animation support.
Safari supports it since v11 according to [caniuse](https://caniuse.com/#search=%3A%3Amarker).

**Comment by fantasai** [comment]
Added. Agenda+ to confirm.
