### ISSUE TITLE
[css-lists] Clarify whether ::before and ::after pseudo-elements can be list-items and increment the list-item counter.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3766]
The following renders differently across browsers:

```html
<!doctype html>
<style>
  li::before, li::after { content: "Before"; display: list-item; }
  li::after { content: "After"; }
</style>
<ol>
  <li>Foo
```

List item is defined in https://drafts.csswg.org/css-lists/#list-item / https://drafts.csswg.org/css-lists/#declaring-a-list-item, but it doesn't clarify if ::before or ::after are supposed to increment the list item counter.

cc @MatsPalmgren @fantasai @tabatkins

**Comment by Loirooriol** [comment]
In https://github.com/w3c/csswg-drafts/issues/1793#issuecomment-380762861 it was resolved that

> RESOLVED: marker exists on all elements, on ::before and on ::after but no box unless it's display: list-item

So ::before and ::after can be list-items and have a marker.
Then I would also expect the list-item counter to be increased.

**Comment by fantasai** [comment]
@emilio Any list item in the box tree will increment the counter, ::before/::after aren't excluded here: if it's allowed to be a list item, then it increments list-item. I think the spec is clear on this point, lmk if you'd like something edited?

**Comment by emilio** [comment]
@fantasai I think that the sentence "list items generate ::marker pseudo-elements" is a bit confusing, since pseudos don't generate other ::marker pseudos generally.

Maybe a note noting that the ::marker pseudo-elements generated by ::before and ::after are not addressable via selectors would clarify it? It's not clear to me what the model is there.

**Comment by FremyCompany** [comment]
I agree with @Loirooriol, we agreed last time that `::before` and `::after` can be list-items and have a marker, but that you can't address them; based on that, the tree can at most contain one level of nesting of generated content (Edge never supported even that, and `::before` couldn't be a list item, but I think other browsers do support that)

**Comment by fantasai** [comment]
Added a clarification along the lines of https://github.com/w3c/csswg-drafts/issues/3826#issuecomment-483320040
