### ISSUE TITLE
[css-values-4] How to serialize infinite values?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3768]
In an expression like `calc(1/0 * 1px)`, it resolves to ∞px. Per the simplification rules currently defined, this should serialize without the calc() wrapper. What should a value like that serialize *as*, tho?

I'm considering specifying that infinite values serialize as a `1/0` expression, even tho divisions are technically resolved away before serialization happens.

**Comment by AmeliaBR** [comment]
Note that whatever you choose would also be used for NaN, per [this line](https://drafts.csswg.org/css-values/#top-level-calculation):

> If a top-level calculation (a math function not nested inside of another math function) would produce a NaN, it instead produces +∞. 

Your suggestion seems the simplest from a syntax perspective, if we just need something for serialization. It's a little bit confusing that you simplify down other functions only to replace them with a different function, but the important part is that the end result is clearly defined.

Would your simple version then be `calc(1px/0)`, with `1px` replaced by whatever is the canonical unit for the correct dimension?

**Comment by tabatkins** [comment]
> Would your simple version then be calc(1px/0), with 1px replaced by whatever is the canonical unit for the correct dimension?

Yes.

**Comment by tabatkins** [comment]
So this is actually a larger issue; in level 3 I could always simplify a valid calculation into a summation of ordinary units, and the current serialization text assumes that is still true. Adding in the min/max/clamp functions invalidated that (requires a summation of units and an arbitrary number of functions), but adding in unit algebra blew it away completely. There are now valid calculations that I can't simplify down further than an operator-tree.

So, to what degree to I want to simplify? I could still require simplifying mult/div by numbers, and require that summations be sorted in the existing specified way, to maintain compat with Level 3 calc() simplifications. I don't *think* I want to go any further than that; even if I could simplify in some cases (like simplifying `1in / 10px * 1em` to just `9.6em`) it would be complex to specify and not really clear to authors what's happening, I think.

So my proposal is precisely that:

* mult/div by a literal number must be simplified away
* summations must be sorted in a compatible way to the old specification
    - ordinary units are sorted alphabetically by unit (with number and % in their specified positions), followed by functions and more complex sub-calculations (wrapped in parens) in source order.
* infinite values are serialized as `1/0`, with the numerator having the appropriate canonical unit for the type


Still not completely sure what to do with NaNs. They're fully infectious; a NaN argument to any function results in NaN, and a NaN at any depth in a calculation causes the top-level calculation to be NaN. Maybe simplify the whole thing to `calc(1/0)`? Do this even if the original math function wasn't calc(), like `clamp(0px/0, 1px, 50px)` serializing to `calc(1/0)`? That has a possibility of being valid, tho; `z-index` would accept that value. I think I need to define an always-invalid math function form, like a literal `calc()`, which is *grammatically* valid in itself, but has no type and thus is invalid in all contexts it can ever be placed.

**Comment by tabatkins** [comment]
Hm, further details on NaN:

* Actually, I do know what type a NaN is; I can do type calculations at parse time, before I know what the values are. (And that's necessary to be able to do grammar validation of calc() at all.) So I could serialize NaN as an appropriate infinite calc(), if I want.
* on the other hand, maybe I just want to go the other way and invoke "invalid at computed-value time" for NaNs. This would mean no simplification (or confusing function-switching) necessary, but I'm not sure how difficult invoking that machinery is. Need implementor opinions on this.

**Comment by Loirooriol** [comment]
IMO it would be unexpected to serialize NaN as `calc(1/0)`. `calc(0/0)`, with the numerator having the appropriate canonical unit for the type, would make more sense.

**Comment by tabatkins** [comment]
Ah yeah, makes sense.

**Comment by tabatkins** [comment]
All right, specced. This happens at the top-level math function; I'm not trying to be smart and do the magic serialization at the deepest point or anything.
