### ISSUE TITLE
[css-overflow] Overflow propagation when the element propagated from is display: none

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3779]
https://drafts.csswg.org/css-overflow/#overflow-propagation says that some overflow properties should be propagated to the viewport from the html or body element:

However this happens regardless of the display value of the document element or the body. For example, the following examples show scrollbars:

* `data:text/html,<html style="display: none"><body style="overflow: scroll">`
* `data:text/html,<html style="display: none; overflow: scroll">`

This is the only case where Gecko needs to resolve a style in a `display: none` subtree for rendering (apart of getComputedStyle), and I find it somewhat silly.

Seems enough of an edge-case that could probably be changed. I wonder if there would be interest from other vendors in doing this change?

cc @lilles

**Comment by emilio** [comment]
Basically, my point is that this should be closer to the background style propagation, which only happens if the document element is actually displayed.

**Comment by fantasai** [comment]
I think from an author standpoint this case doesn't matter, so personally I don't care. Happy to do whatever is expedient for implementers.

**Comment by lilles** [comment]
Fine for us from an implementation pov.

**Comment by lilles** [comment]
Chrome even propagates the background, which is not according to spec.

**Comment by lilles** [comment]
For backgrounds: https://bugs.chromium.org/p/chromium/issues/detail?id=947873

**Comment by lilles** [comment]
There is the same issue for https://drafts.csswg.org/css-writing-modes-3/#principal-flow

Chrome starts with the horizontal scrollbar to the right for direction:rtl regardless of display:none or not on body below.

```
<!DOCTYPE html>
<style>
  html { overflow: scroll; width: 5000px; height: 100px }
  body { direction: rtl; display: none }
</style>
<body></body>
```
