### ISSUE TITLE
[css-images] linear-gradient syntax oopsie

### ISSUE THREAD

**Issue by benjamin-otte** [w3c/csswg-drafts#3781]
https://drafts.csswg.org/css-images-3/#linear-gradients defines linear gradients as  
`linear-gradient() = linear-gradient(  [ <angle> | to <side-or-corner> ]? , <color-stop-list>)`
but should probably define them as
`linear-gradient() = linear-gradient(  [ <angle> | to <side-or-corner> , ]? <color-stop-list>)`
because otherwise  
`linear-gradient(red,blue)`  
would be incorrect and
`linear-gradient(,red,blue)`
would need to be used.

**Comment by cpplearner** [comment]
See https://drafts.csswg.org/css-values-4/#comb-comma

**Comment by benjamin-otte** [comment]
It's even linked, nice. Looks like I've never clicked on the comma.
