### ISSUE TITLE
[css-text-3] "hang" definition refers to punctuation, but also applies to white space

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#3784]
https://drafts.csswg.org/css-text-3/#white-space-phase-2 talks about sequences of collapsible white space at the end of a white-space:pre-wrap element hanging by linking to https://drafts.csswg.org/css-text-3/#hang, but that section only talks about punctuation.  Maybe it needs to be adjusted to make sense for white space too.

**Comment by fantasai** [comment]
OK, reworded things a bit. @litherum would you mind reviewing to make sure I didn't edit the prose to say something stupid? :)

**Comment by frivoal** [comment]
I'm not @litherum , but I did have a comment on the edit you made: https://github.com/w3c/csswg-drafts/commit/e41d2248bb2a15ae607e42489491730d27394539#r33167130

**Comment by litherum** [comment]
Looks fine
