### ISSUE TITLE
[selectors] Add :picture-in-picture pseudo-class

### ISSUE THREAD

**Issue by svoisen** [w3c/csswg-drafts#3796]
See https://wicg.github.io/picture-in-picture/#css-pseudo-class

The Picture-in-Picture WICG spec proposes adding a pseudo for the picture-in-picture element. 

Blink has an intent-to-ship for this pseudo: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/X-qPSmdSR_g/StUMNNiQAwAJ

**Comment by gregwhitworth** [comment]
So the currently active specification for PIP is indeed this WICG one: https://wicg.github.io/picture-in-picture/

**Comment by fantasai** [comment]
@gregwhitworth Are there any plans to put it through a standards process or is it planning to live in WICG forever?

**Comment by gregwhitworth** [comment]
@fantasai I spoke with the PM that is driving this spec work and they said that they intend to migrate it to the Media WG which is actively being chartered, so once that is completed you should see it migrate there.
