### ISSUE TITLE
[css-images] Consider changing initial value of 'image-orientation' to from-image

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#3799]
Spec: https://drafts.csswg.org/css-images/#propdef-image-orientation

See related issue in HTML: https://github.com/whatwg/html/issues/4495 (and earlier discussion in https://www.w3.org/Bugs/Public/show_bug.cgi?id=25508 )

> *or*, we could change the initial value of image-orientation from `none` to `from-image` (cc @tabatkins ), so all images are rotated "correctly" by default. [Use counter data from 2016](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25508#c27) found affected images to be ~0.00% of all images.

Browsers not respecting EXIF orientation of images by default everywhere on the web seems to continue to be an [annoyance](https://stackoverflow.com/questions/35011966/why-my-image-is-rotate) for web developers. Earlier [analysis](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25508#c16) suggests that it would be a net benefit to make this change, and the risk of breakage is at most ~0.00% of images. There has been [interest](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25508#c22) from some implementors to try to change the default, but it hasn't happened yet (except for iOS Safari to some extent).

**Comment by drewm** [comment]
I'm a commercial CMS developer and encounter people confused by the current default not acting in the same way as literally all the rest of the software they're using. Nobody I've encountered is seeing this and just leaving it _wrong_ on their site, so low in-the-wild numbers make sense, but also mask the level of frustration and extra work that might result from the current default. 

If changing the default would only impact images that contain orientation data with a value other than `1` (0deg), which are therefore currently rendering incorrectly, I'd suggest that's a very sensible change to make.

As a side note, the spec for `from-image` focuses on the `angle` value. As half of the 8 EXIF values are for `flip`, I think it would be beneficial to mention that too, lest it gets overlooked.

**Comment by zcorpan** [comment]
New use counter data:
https://github.com/whatwg/html/issues/4495#issuecomment-484084805

**Comment by tabatkins** [comment]
Agenda+ to discuss this.  Elika and I are fine with making the change; the only reason we haven't done so is for compat reasons.

However, Blink's data shows that there are trillions of images for which this would produce no change, and ~200 *million* (aka roughly .00001%) that would have a behavior change; it's likely that a significant chunk of those would be *improved* by the behavior change, as they're currently rotated wrongly, but we can't tell how many that would be the case for.

In any case, this seems like a very safe change to make, and it appears from author feedback that it would improve the general authoring experience (by making the web match most other image renderers by default).

**Comment by fantasai** [comment]
Some earlier discussion on this issue: https://lists.w3.org/Archives/Public/www-style/2012Mar/0006.html and https://lists.w3.org/Archives/Public/www-style/2012Feb/0311.html and https://lists.w3.org/Archives/Public/www-style/2012Jan/0573.html

**Comment by smfr** [comment]
As a data point, WebKit (stupidly) respects EXIF orientation in iOS but not macOS, which has been a continual source of confusion. I'm happy to have this standardized, forcing us to rip off the band-aid and do it everywhere.

**Comment by fantasai** [comment]
This was fixed by @tabatkins  in https://github.com/w3c/csswg-drafts/commit/bacb9b7b91d0dd6cc5fdc1e469570972dc8805aa#diff-8125531432177df24536a45faa47a870

**Comment by zcorpan** [comment]
Thanks!

Next steps:

* write wpt tests
* comment in existing browser bugs, or file new ones, to implement this change
* maybe write something to make web developers aware of this change, and what they should do if their existing workaround breaks

**Comment by zcorpan** [comment]
Also see https://github.com/w3c/csswg-drafts/issues/4165

**Comment by AmeliaBR** [comment]
> what they should do if their existing workaround breaks

Specifically, it would be nice if someone could put together a feature-detection test, something that could be submitted to Modernizr or used on its own.  The support test (for content images, anyway) could load a minimal 1×2px JPEG data URI with the relevant EXIF tag to rotate it to 2×1, and then read back the dimensions. (Not sure how you'd extend that to detecting support in background images, where there's no way to read back the dimensions.)

**Comment by eeeps** [comment]
Do we need a note that the orientation metadata must appear before the image data, for it to have an affect?

See:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1627423#c3
- https://bugs.webkit.org/show_bug.cgi?id=210021#c4

**Comment by tabatkins** [comment]
I opened an issue (#4929) to make it a normative statement instead.
