### ISSUE TITLE
[css-color-4] Support high-contrast/dark mode colors

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3804]
With Dark Mode and MSFT's “high contrast” mode (which is more accurately a “specific contrast” mode since it also represents low-contrast settings), we anticipate that authors will want the ability to re-use relevant system colors. Revisiting the CSS System Colors, @tabatkins and I have come up with the following list of colors (based on the available [MSFT high-contrast settings](https://raw.githubusercontent.com/MicrosoftEdge/MSEdgeExplainers/master/HighContrast/TurnOnHighContrast.jpg)) which we propose to add*/undeprecate for these purposes:

- Canvas* (we'd have liked to call this “Background” but that's already used for something else)
- Text*
- LinkText*
- VisitedText*
- Highlight
- HighlightText
- GrayText (could be aliased to InactiveText or DisabledText for clarity)
- ButtonFace (could be aliased to Button for consistency)
- ButtonText

Note: MSFT doesn't distinguish visited vs. unvisited links, but as some systems may we included keywords for both variants: they can be mapped to the same color as needed.

**Comment by smfr** [comment]
WebKit's user agent CSS file contains the following system color values:

background-color: -apple-system-control-background;
background-color: ButtonFace;
color: -webkit-activelink;
color: -webkit-link;
color: ActiveButtonText;
color: ButtonText;
color: GrayText;
color: text;

So of those, the ones not covered by your list above are:

background-color: -apple-system-control-background;
color: -webkit-activelink;
color: ActiveButtonText;

**Comment by fantasai** [comment]
We mainly wanted to hit the colors that are needed to handle forced-colors mode. (MSFT's contrast feature or similar), so our initial list was intentionally limited to the colors MSFT uses in that mode: those are the colors that authors need to be able to access. Extending system colors more generally is possible, but we felt it would be a separate issue so as not to complicate solving this particular problem asap. Not sure how the Apple colors fit into that idea? (What even is -apple-system-control-background)

**Comment by smfr** [comment]
-apple-system-control-background is what we use to render the background of some <input> elements.

**Comment by AmeliaBR** [comment]
How are the proposed `Canvas` and `Text` colors different from the CSS2 `Window` and `WindowText` colors?  Are these expected to be the same colors, but just with better names?

In general, I'd prefer not to introduce new keywords/aliases if there isn't a strong reason for them, since user agents are going to need to continue to support the old keywords anyway.

I agree that new named colors are required for the link and visited link colors. I think it makes sense to also include an active link color.  It's fairly traditional to have a separate color for that (usually red) in the user agent stylesheet, even if it's not a big accessibility issue.  I'd recommend calling them `VisitedLinkText` and `ActiveLinkText` to be unambiguous since there are other `ActiveSomething` keywords.

Similarly, Simon: do you know why `-apple-system-control-background` required its own keyword & couldn't use one of the predefined ones? Is it a case that Apple UI uses the same color for many different things, which might not be all drawn in the same color in a different UI?  Meaning: is this logically more of a color variable rather than a color of a specific thing?

**Comment by smfr** [comment]
I couldn't see any system colors in https://www.w3.org/TR/css-color-3/#css2-system that are equivalent to an input's background color, hence `-apple-system-control-background`.

If we do bring back the system colors, can we give them nice hyphenated names ("active-link-text")?

**Comment by AmeliaBR** [comment]
> I couldn't see any system colors … that are equivalent to an input's background color

That's a good point. Another missing value. All the three-d sides of a button, and nothing for a text input.  WHCM re-uses the button colors for inputs, but that's not true for system themes in general.

**Comment by dbaron** [comment]
> I couldn't see any system colors in https://www.w3.org/TR/css-color-3/#css2-system that are equivalent to an input's background color, hence -apple-system-control-background.

Early drafts of css3-ui had `Field` and `FieldText` for text fields (see [my 2001 description of their importance](https://lists.w3.org/Archives/Public/www-archive/2019Apr/0000.html) or the [original member-only post](https://lists.w3.org/Archives/Member/w3c-css-wg/2001AprJun/0091.html)) and those are implemented in Gecko with prefixes.

**Comment by fantasai** [comment]
> How are the proposed Canvas and Text colors different from the CSS2 Window and WindowText colors? Are these expected to be the same colors, but just with better names?

@AmeliaBR It's not very clear what they mean from the spec, but at least some implementations return Window which are not equivalent to the canvas background. So to prevent anything bad happening, we're introducing new keywords.

> If we do bring back the system colors, can we give them nice hyphenated names ("active-link-text")?

Added to the List of Mistakes, because, yeah. That said, since all color names -- system colors, X11 colors, currentcolor -- are following the mashwordstogether pattern, I think we might want to just stick with it here. :/

> I couldn't see any system colors in https://www.w3.org/TR/css-color-3/#css2-system that are equivalent to an input's background color, hence -apple-system-control-background.

Tab and I would be OK to add in Field and FieldText if y'all feel it's needed; we left them out of our original list mainly because MSFT's forced-colors implementation didn't seem to distinguish between those and Canvas/Text, and we were aiming at a minimal set to start. (We didn't want to pull in all of https://www.w3.org/TR/2000/WD-css3-userint-20000216#color and tackle the issue of system colors generally here, just get the minimum set needed to support forced-colors mode. If we were pulling anything out of that draft, though, Field/FieldText would've been it, to correspond with ButtonFace/ButtonText.)

**Comment by tabatkins** [comment]
Closing since the merge in https://github.com/w3c/csswg-drafts/commit/8bb901999787c4e5a6b2af2a0d5049d995b8dc50 addressed this issue.

**Comment by snuggs** [comment]
@tabatkins @fantasai happen to know why `Text` was declared in list above but not in https://www.w3.org/TR/css-color-4/#css-system-colors
?

Thanks in advance!
