### ISSUE TITLE
[css-color-adjust-1] color-adjust initial value should be auto

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3805]
To make it easier to extend color-adjust to other use cases, I think it makes sense to make the initial value `auto` and have it compute to different values depending on what adjustment is being performed. E.g. in print mode, it might compute to `economy`, but on a typical screen it will always compute to `exact`.

(One extension we might consider is something to represent automatic color luminance inversions; this is not the same as `economy`, but could be reasonably represented in `color-adjust` if we make it extensible in this way. See [discussion on Apple's color-filtering](https://lists.w3.org/Archives/Public/www-style/2018Jul/0023.html).)

**Comment by tabatkins** [comment]
(Closed after discussion with fantasai; her use-cases were addressed in other ways already.)
