### ISSUE TITLE
[css-lists-3] counter-set vs counter-increment

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3810]
Re: [Counter properties in CSS Lists Editor's Draft](https://drafts.csswg.org/css-lists-3/#counter-properties)

There's some ergonomc awkwardness about `counter-set` vs `counter-increment`, e.g. in https://github.com/w3c/csswg-drafts/issues/3686 it's pointed out that you'd have to zero out the list-item increment when setting the counter for `<li value=...>`. (This particular case is technically problematic as well as unweildy because it'd get wiped out by an author `counter-increment` declaration; but there's some awkwardness either way and it doesn't cascade well for anyone.)

I'm wondering if instead of applying `counter-reset`, then `counter-set`, then `counter-increment`, we should apply `counter-reset`, then `counter-increment`, then `counter-set`? Then when you “set” a counter on an element, you actually get that value back, which seems a little more intuitive (and also solves the list-item problem).

**Comment by fantasai** [comment]
It also gives better cascading behavior in general (not just for the author/ua list-item negotiation).

**Comment by AmeliaBR** [comment]
Does `counter-set` have any implementations? That could create compat issues.

If there's no compatibility objections, I agree that it is preferable if `counter-set` overrides any increments.  If I specify `counter-set: chapter 5`, that's probably what I want.

The downside is that `counter-reset: chapter 5` would work differently; an increment declared on the same element would add to the initial value.  But that's less likely to be a problem once `counter-set` is supported; `counter-reset` can be used as intended, on the parent element that defines the counter scope.

**Comment by emilio** [comment]
There's Gecko's implementation, but that's not on release yet so we can change that without much hassle I'd guess.

But I'd rather get a speedy resolution than doing it once it's hit release.

cc @MatsPalmgren in case he has objections.

**Comment by MatsPalmgren** [comment]
I like this proposal. It makes `counter-set` simpler to use for authors and implementors alike. In particular, we can now map `<li value=N>` to just `counter-set: list-item N` making it independent of any `counter-increment` the author might have on that element (as @heycam noted as a problem in https://github.com/w3c/csswg-drafts/issues/3686#issuecomment-479360022).

(I'm fixing Gecko [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1542594).)
