### ISSUE TITLE
[css-scroll-snap-1] Clarify which writing-mode is used for scroll-snap-align, scroll container or snap position element?

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#3815]
I've been thinking it's for sna-position element, but [jfkthame thinks it's for scroll container](https://phabricator.services.mozilla.com/D21628#inline-153048).

Here is an example that the writing-mode for snap position element differs from scroll container's value;
https://codepen.io/anon/pen/vMyRVV

**Comment by fantasai** [comment]
Good question! I'm surprised we didn't spec this interaction. The box alignment properties use the container's writing mode, so I think it makes sense here to use the scroll container's writing mode (i.e. the writing mode of the alignment container). https://www.w3.org/TR/css-align-3/#positional-values

**Comment by fantasai** [comment]
(If in the future we want to use the element's own writing mode to resolve the logical values, we can add self-start/self-end keywords.)

**Comment by tabatkins** [comment]
Yes, given the container properties definitely use the container's writing mode, I think it's most useful to default the descendant's properties to use the same.

**Comment by majido** [comment]
I agree with the proposed solution. It makes sense to be consistent with box alignment properties and it feels most natural to me.

Having said that I don't think Chromium current implementation is correct. [Here](https://codepen.io/anon/pen/WWabNz) is a slightly modified version of the original example where I gave second container `direction: rtl` which I take it that with the proposed solution should interpret `start` as aligning the snap area to the **right** side of the scroll container. Which we don't at the moment. I will file a chromium bug for this.

**Comment by hiikezoe** [comment]
> Having said that I don't think Chromium current implementation is correct. Here is a slightly modified version of the original example where I gave second container direction: rtl which I take it that with the proposed solution should interpret start as aligning the snap area to the right side of the scroll container. Which we don't at the moment. I will file a chromium bug for this.

Just FYI, Firefox has also the issue on the example. I filed bug https://bugzilla.mozilla.org/show_bug.cgi?id=1546835.

**Comment by tabatkins** [comment]
Agenda+ to confirm the conclusion.

**Comment by fantasai** [comment]
Holding off on edits to consult i18n.

**Comment by r12a** [comment]
> Holding off on edits to consult i18n.

The previous resolution to associate the start/end location with the container box sounds appropriate to me. I'm worried i might be missing something. @fantasai was there something that you were expecting that we might say?

**Comment by r12a** [comment]
Btw, the editor's version has the CR livery, instead of ED – which confused me for a few moments.  I was expecting it to have a red ED label top right.

**Comment by fantasai** [comment]
@r12a I was thinking about it, and there's a reasonable argument to be made for the other way around. E.g. if you have a bunch of "cards" which are in a horizontal row swipy view, and you specify `start` alignment, and each one is in a different language... you align them all, and I guess you could argue either way for which side Arabic snaps to when the cards are smaller than the viewport, but if the cards are *larger* than the viewport... then you might want it to snap to the card's own start edge. No?

**Comment by fantasai** [comment]
Agenda+ to review the use cases

**Comment by litherum** [comment]
When the two writing modes are orthogonal, which values should be used to compare when computing "element is larger"?

**Comment by fantasai** [comment]
@litherum You use the size in the relevant axis. Scroll snapping is essentially one-dimensional.

**Comment by jonjohnjohnson** [comment]
> @litherum You use the size in the relevant axis. Scroll snapping is essentially one-dimensional.

@fantasai Can you elaborate on "essentially one-dimensional? I've used 2-dimensional scroll snapping on a scroll container than has an inner layout of `grid` with content flowing through the inline and block dimensions. Would the block overflow here be the one essential dimension/axis?
