### ISSUE TITLE
[css-text-3] letter-spacing & kerning

### ISSUE THREAD

**Issue by prjnt** [w3c/csswg-drafts#3816]
Part of commit caf1e4747f2bd906bb9f671af8c463b28b97deda to the editors' draft of css-text-3 (https://drafts.csswg.org/css-text-3/#letter-spacing-property) is to say that letter-spacing is applied after kerning.  What is the intent of this addition?  Kerning should ideally depend on the applied letter-spacing: e.g. the best kerning of nj (conjoin, injure) is influenced by the tail more for loose than tight tracking.

I suggest saying that letter-spacing is applied "in addition to" rather than "after" kerning.

(Granted, this is only a problem for any user agent that synthesizes kerning, and I do not offhand know of any that currently do.  The objection doesn't directly apply to variable fonts, because they aren't affected by the letter-spacing property, though cf. https://github.com/w3c/csswg-drafts/issues/2102 .)

**Comment by fantasai** [comment]
Done! Thanks for the suggestion~
