### ISSUE TITLE
[resize-observer] The phrase "if Element has display" doesn't make sense

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#3819]
The ResizeObserver intro section (https://drafts.csswg.org/resize-observer/#intro ) currently ends with this text:

> Observation will fire when observation starts if Element has display, and Element’s size is not 0,0.

The phrase "if Element has display" doesn't really make any sense -- could we clarify that?

**Comment by emilio** [comment]
I assume it should use https://html.spec.whatwg.org/#being-rendered

**Comment by gregwhitworth** [comment]
Yes, thanks @emilio - I think what the initial think was something along the lines of "display does not compute to none" but that is much more concise. I'll update it.

**Comment by fantasai** [comment]
Generating a box and “being rendered” might not necessarily the same thing, there's an open issue on that wrt elements with `display: contents`. https://github.com/whatwg/html/issues/1837 Probably want to be more explicit about that.
