### ISSUE TITLE
[css-contain] Unclear what contain:size does for replaced elements

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#382]
In the spirit of what it does for non-replaced elements (treat as having no contents, so it'll shrink to zero in most layouts), a replaced element should act like it has no intrinsic dimensions either.

**Comment by frivoal** [comment]
Sounds good to me. Just be careful in the phrasing to scope this “act like it has no intrinsic dimensions” thing to size calculations only. We don't want to imply that intrinsic dimensions should stop mattering for other things, such as object-fit for example.

**Comment by frivoal** [comment]
Also, I don't think it should get rid of intrinsic aspect ratios.

**Comment by fantasai** [comment]
On 09/05/2016 12:57 AM, Florian Rivoal wrote:
> Also, I don't think it should get rid of intrinsic aspect ratios.

Then it would require loading and analyzing the contents.
At which point it may as well have its intrinsic width and height, too.

~fantasai

**Comment by frivoal** [comment]
Yes, I suppose it was late when I wrote that.
