### ISSUE TITLE
[css-tables-3] Blink includes border-spacing in row{,-group} sizes; gecko does not

### ISSUE THREAD

**Issue by davidsgrogan** [w3c/csswg-drafts#3822]
Blink adds adjacent border-spacing to offsetWidth, offsetHeight, getBoundingClientRect, etc for table rows* and row-groups. It should only include border-spacing that is internal to those boxes, as Gecko does.

* row heights are the only thing Blink gets right. row widths, section widths, and section heights are all wrong.

See http://w3c-test.org/css/css-tables/border-spacing-included-in-sizes-001.tentative.html

**Comment by davidsgrogan** [comment]
I propose to settle on Firefox behavior:

<ul>
<li>border-spacing before the first section or after the last section is not
included in any section's height.
<li>border-spacing between sections is not included in any section's height.
<li>
border-spacing before the first cell or after the last cell is not included in
the width of the row or section.
<li>
border-spacing is not included in the height of any row. (Blink agrees here.)
</ul>

**Comment by FremyCompany** [comment]
Hey David,

At first sight, the recommandation you are making is already what is specified in the Bounding Box Assignment section of the spec, is that correct?

    The position of any table-cell, table-track, or table-track-grouping box within the table 
    is defined as the rectangle whose:
    
        width/height is the sum of:
            the widths/heights of all spanned visible columns/rows
            the horizontal/vertical border-spacing...
                ...times the amount of spanned visible columns/rows minus one 
    
        left/top location is the sum of:
            for top: the height reserved for top captions (including margins), if any
            the padding-left/padding-top and border-left-width/border-top-width of the table
            the widths/heights of all previous visible columns/rows
            the horizontal/vertical border-spacing...
                ...times the amount of previous visible columns/rows plus one 



https://www.w3.org/TR/css-tables-3/#bounding-box-assignment

**Comment by FremyCompany** [comment]
(if you agree, I can add a clarifying note mentioning the properties you wrote down, in addition to the formula I already wrote in the spec; that might be more obvious to people when those are stated plainly than hidden in a formula like things are right now)

**Comment by davidsgrogan** [comment]
Ah, yes, the spec is already consistent with the proposal.

I agree some clarification would be beneficial... like you say, I don't think there's a way to connect the height/width in the [tables positioning section](https://www.w3.org/TR/css-tables-3/#bounding-box-assignment) to the [CSSOM Layout Box](https://drafts.csswg.org/cssom-view/#css-layout-box) which governs offsetHeight and friends.

I think you're considering something like the following?

> Note: The width/height/left/top calculated above defines the dimensions of the CSS Layout Box, which means that they are accessible via the [offset* properties](https://drafts.csswg.org/cssom-view/#extensions-to-the-htmlelement-interface).

**Comment by FremyCompany** [comment]
https://github.com/w3c/csswg-drafts/commit/942a46a1db056174fbb11cdf94bf2de3b14fc0e3
