### ISSUE TITLE
[css-ui-4] editorial: text-overflow link is 404

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3825]
https://drafts.csswg.org/css-ui-4/#text-overflow
links to https://www.w3.org/TR/css-overflow-4/#text-overflow
but the TR spec doesn't contain any `text-overflow` spec text.
The draft does though: https://drafts.csswg.org/css-overflow-4/#text-overflow
so assume this is the link you intended.

**Comment by fantasai** [comment]
:/ I think we missed out on updating css-overflow-4 is the problem.

**Comment by fantasai** [comment]
Actually, nm. I was mixing up L3 and L4. Fixed in https://github.com/w3c/csswg-drafts/commit/8d2c0b825eac289cffce12df7ed3cb0c83603ddc
