### ISSUE TITLE
[css-lists] Interaction of ::marker with other pseudo-elements.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3826]
A few different questions that occurred to me, that should probably be tested and clarified on the spec, and they interact with each other.

### Do `::before` and `::after` generate markers?

In #3766 it was clarified that they increment the list-item counter and are considered list items. But do they generate marker boxes?

Browsers generally do (Edge didn't use to though, so we may have some leeway). It's a bit weird that we're generating nested pseudo-elements.

### If they do... Do those markers generated by pseudo-elements match selectors from the page?

WebKit and Gecko's implementation do show two red bullets here:

```html
<!doctype html>
<style>
  li::after {
    content: "After";
    display: list-item;
  }
  ::marker {
    color: red;
  }
</style>
<ul>
  <li>Bar
```

But then that means that you can address a marker generated by a pseudo-element with selectors. Which is inconsistent in the sense that it doesn't happen for `::before` and `::after`. Which carries me to the next question...

### If they do... Does `display` apply to `::marker`? And thus, can `::marker` boxes be list items?

If we allow `content` on marker, they can just be a normal box, affected by `display`, and thus have `display: list-item` on them. If generated markers can be list items, then:

 * Do they increment the `list-item` counter?
 * Do they generate other markers?

I really hope the answer to these two question is "no", but otherwise, how should this work?

```html
<!doctype html>
<style>
  li::after {
    content: "After";
    display: list-item;
  }
  ::marker {
    display: list-item;
    content: counter(list-item) ".";
  }
</style>
<ol>
  <li>Foo
  <li>Bar
```

I think `::marker` shouldn't be a list-item, even if it's a box with `display: list-item` like @fantasai clarified in #3766, and that it should not increment the list-item counter nor generate other markers.

**Comment by emilio** [comment]
> WebKit and Gecko's implementation do show two red bullets here:

This is apparently wrong, I don't know what I was testing, but loading that again on WK doesn't show the red marker. So I think those markers shouldn't be addressable by selectors.

But the third question is probably worth answering.

**Comment by emilio** [comment]
And the first, probably... I'd prefer if they wouldn't generate markers. Because then you don't have to have pseudo-elements generating other pseudo-elements, even if those can't be addressed by content.

**Comment by emilio** [comment]
> And the first, probably... I'd prefer if they wouldn't generate markers. Because then you don't have to have pseudo-elements generating other pseudo-elements, even if those can't be addressed by content.

Basically, if we generate those markers, the [UA sheet for marker](https://drafts.csswg.org/css-lists-3/#ua-stylesheet) needs to be defined in some magic way that also matches pseudo-element markers, somehow. I'd rather avoid that.

**Comment by MatsPalmgren** [comment]
I don't think you should take that UA sheet too seriously. It's wrong in a number of ways. I'm guessing its purpose is mainly to explain how the CSS built-in `list-item` counter works using the familiar HTML list elements as an example, even if it's not precise. Obviously you can't match "`display` has the value `list-item`" in a selector etc.

**Comment by MatsPalmgren** [comment]
Regarding your questions, I think `::before/::after/::marker ` should all be list items when styled with `display:list-item` and generate a marker.  A pseudo's marker can't be addressed by a selector _currently_ , but I see no reason why that could't be added in a future version of the Selectors spec. It seems to me we shouldn't exclude that possibility.

**Comment by emilio** [comment]
It seems to me then that `::marker { display: list-item }` would generate an infinite amount of list items, which is not great.

**Comment by MatsPalmgren** [comment]
No, because `::marker` is the same as `*::marker` and `*` only matches ordinary elements, not pseudo-elements. You can't set `display` (or any properties) on any deeper level markers since there's no selector for it.

**Comment by jonjohnjohnson** [comment]
> You can't set display (or any properties) on any deeper level markers since there's no selector for it.

@MatsPalmgren would you then suggest that selectors like `::before::marker`/`::marker::marker` be valid (https://drafts.csswg.org/selectors-4/#pseudo-element-structure) to actually be stylable/useful?

**Comment by MatsPalmgren** [comment]
Right,  I'm not really suggesting any particular syntax, but we might want to add a selector to address nested pseudos like that in the future so I think it's premature to forbid `::marker`s on pseudos now just because we _currently_ can't style them.

(But yes,  `::before::marker/::marker::marker/::before::marker::marker` etc seems reasonable. We might also want some selector syntax to address markers on any level, for convenience. The second syntax clearly needs to have some built-in limitations to avoid creating infinite levels of markers though, say by ignoring `display:list-item` in such rules.)

**Comment by Loirooriol** [comment]
I think most of this was already resolved in https://github.com/w3c/csswg-drafts/issues/1793#issuecomment-380762861

 - Do `::before` and `::after` generate markers?
   Yes, but the marker will have no box if the `::before` or `::after` doesn't have `display: list-item`, as usual.
 - Do those markers generated by pseudo-elements match selectors from the page?
   As Mats says I don't think `::marker` should select these markers, because `::marker` means `*::marker`, and `*` only matches elements.
   But something like `::before::marker` might be allowed in the future.
 - Does `display` apply to `::marker`? And thus, can `::marker` boxes be list items?
   Currently `display` does not apply to `::marker` (https://drafts.csswg.org/css-pseudo-4/#marker-pseudo), so they cannot be list items.
And even if they could, the resolution in #1793 said that marker pseudo-elements (in the element tree, not marker boxes) are only originated by elements, `::before` and `::after`, but not by other markers. Otherwise the element tree would have an infinite depth.

**Comment by SebastianZ** [comment]
> ### If they do... Do those markers generated by pseudo-elements match selectors from the page?
>
> WebKit and Gecko's implementation do show two red bullets here:

Gecko's implementation obviously does, but has a bug when changing the styles. I've reported that as [bug 1544959](https://bugzilla.mozilla.org/show_bug.cgi?id=1544959).

>> * Does `display` apply to `::marker`? And thus, can `::marker` boxes be list items?
>
> Currently `display` does not apply to `::marker` (https://drafts.csswg.org/css-pseudo-4/#marker-pseudo), so they cannot be list items.

In the Firefox implementation at least `display: none` obviously applies to it and causes the marker(s) not to be displayed. The other display values including `list-item` have no effect on it, though.

Sebastian

**Comment by tabatkins** [comment]
Agree with all of Mats' answers. ::before/after generate ::marker, 'display' doesn't apply to ::marker, and a `::marker` selector can't select the marker on the ::before because it's not visible in the tree (you'd need `::before::marker`)

**Comment by emilio** [comment]
The way I read @MatsPalmgren is that display should apply to marker (when using `::content` at least)... right?

**Comment by MatsPalmgren** [comment]
Right, as I've said [before](https://github.com/w3c/csswg-drafts/issues/3809#issuecomment-480862184), I'm opposed to introducing arbitrary unnecessary styling restrictions on `::marker`. It's much simpler for everyone (spec authors, implementors, authors) if it behaves the same as `::before/::after`.

There are still some uncertainty about the exact layout model for outside markers (#3771), so feel free to add an ISSUE note about that in the spec, but my gut feeling is that we can allow pretty much  all of CSS on those too. We definitely should allow `display:none` to suppress the box.

I don't see a reason treat `content`/non-`content` markers differently. (Gecko _currently_ has two code paths, where the non-`content` legacy code path has some restrictions, but I consider that to be a temporary implementation bug that we'll fix soon.) Given that `::marker` is relatively new, I don't see any web-compat concerns that could justify introducing styling restrictions.

**Comment by fantasai** [comment]
Emilio responded in the minutes, so marking Commenter Satisfied.
