### ISSUE TITLE
[cssom] IndexSizeError vs RangeError

### ISSUE THREAD

**Issue by FarSeeing** [w3c/csswg-drafts#3828]
The [CSS Object Model spec](https://drafts.csswg.org/cssom/#css-rules) says that both inserting and deleting rule should throw `InvalidStateError` on exception:
>If index is greater than length, then throw an IndexSizeError exception.

At the same time [Web IDL linked page](https://heycam.github.io/webidl/#indexsizeerror) says that `InvalidStateError` is deprecated and `RangeError` should be used instead:
>The DOMException names marked as deprecated are kept for legacy purposes but their usage is discouraged.

What do you think about updating spec to mention `RangeError`?

**Comment by emilio** [comment]
I assume this depends on how much do we expect people to rely on `IndexSizeError`, and on whether somebody is willing to change behavior here.

**Comment by mfreed7** [comment]
My understanding here is that `IndexSizeError` is deprecated for *new* specs that need to throw an Exception, not that existing specs that are already written to throw an `IndexSizeError` (such as `deleteRule()`) should be changed to now throw a `RangeError`.

**Comment by emilio** [comment]
That is right. Is there any reason other than `IndexSizeError` being deprecated on new specs to change it? Which benefit would it bring compared to the potential breakage?

**Comment by tabatkins** [comment]
Yeah, deprecated just means we don't use it anymore; there's no reason to change legacy specs currently using it. That would just be churn for no benefit.
