### ISSUE TITLE
[css-writing-modes] Abstract wording slightly inexact

### ISSUE THREAD

**Issue by aphillips** [w3c/csswg-drafts#3829]
CSS Writing Modes Level 4
https://www.w3.org/TR/css-writing-modes-4/

This issue was created by the I18N WG a while ago, but never submitted. It is editorial only and I18N discussed it [here](https://www.w3.org/2019/04/11-i18n-minutes.html#item06).

Currently the abstract says:

>    CSS Writing Modes Level 4 defines CSS support for various international writing modes, such as left-to-right (e.g. Latin or Indic), right-to-left (e.g. Hebrew or Arabic), bidirectional (e.g. mixed Latin and Arabic) and vertical (e.g. Asian scripts).

The terms 'right-to-left', 'bidirectional', and 'vertical' are slightly inaccurate here. While the spec understands the issues, a casual reader looking at the spec would have incorrect assumptions about RTL scripts reinforced and might have the impression that vertical writing is either the default for CJK or only a CJK artifact. While the abstract is trying to convey what the doc is about without being overly pedantic, perhaps a bit of editing would be useful here. I'd suggest something like:

>    CSS Writing Modes Level 4 defines CSS support for various international writing modes, such as the vertical presentation of text (which is most common in Asian scripts) or support for horizontal presentation, including directional variation in bidirectional scripts (predominantly right-to-left text in scripts such as Arabic and Hebrew).

**Comment by fantasai** [comment]
New abstract reads: CSS Writing Modes Level 3 defines CSS support for various writing modes and their combinations, including left-to-right and right-to-left text ordering as well as horizontal and vertical orientations.

@aphillips Let me know if this is acceptable.

**Comment by aphillips** [comment]
@fantasai this looks pretty good to me, although the original used the term "bidirectional" (which I think is helpful) and the term "presentation" with vertical/horizontal, which reinforces a useful concept (unlike bidi, vertical is a presentation and not a property of text). I know my suggestion doesn't pass the pedantry test and I am Satisfied by this change.
