### ISSUE TITLE
[filter-effects] An incorrect 'GitHub Issues' link

### ISSUE THREAD

**Issue by RazrFalcon** [w3c/csswg-drafts#3830]
https://www.w3.org/TR/filter-effects/ has a *GitHub Issues* link that uses an outdated label `filter-effects-1`. It should be `fx-filter-effects-1`.

**Comment by dirkschulze** [comment]
@RazrFalcon Not sure if I understand. Why the `fx-` prefix? Also, the correct place to file GitHub Issues is https://github.com/w3c/fxtf-drafts/labels/filter-effects-1

**Comment by RazrFalcon** [comment]
I thought that the correct link is https://github.com/w3c/csswg-drafts/labels/fx-filter-effects-1

>Also, the correct place to file GitHub Issues is https://github.com/w3c/fxtf-drafts/labels/filter-effects-1

Maybe. https://www.w3.org/TR/filter-effects/ link this repo.

**Comment by svgeesus** [comment]
> Maybe. https://www.w3.org/TR/filter-effects/ link this repo.

@dirkschulze it looks like the bikeshed source file needs to declare the github repo, because (as noted) otherwise published specs point to the wrong place to raise issues.
