### ISSUE TITLE
[cssom][css-logical-props] Resolved value of logical properties

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#384]
There is a list in CSSOM spec about properties which should return used value instead of computed value for declaration from `getComputedStyle`.

The question is, whether their corresponding logical properties should return used value as well? e.g. `width` should return used value, but should `inline-size` and `block-size` return used value?

My understanding is that, the list exists purely for historical reason, so we don't want to add any new property into that list, and consequently the new logical properties should not be put there either.

If that is the case, I think it's worth at least a note in the CSSOM spec that "any other property" includes the corresponding logical properties from CSS Logical Properties spec.

**Comment by fantasai** [comment]
I would actually lean towards having the same behavior for logical and physical equivalents. They are in a weird way aliases to the same property.

**Comment by zcorpan** [comment]
I tend agree with @fantasai. It also seems somewhat easier for developers to adopt logical properties if they behave the same as physical here.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4382
In Gecko `blockSize` returns the empty string. WebKit and Chromium don't implement block-size.
