### ISSUE TITLE
[css-color-4] Computed & used value of `transparent`

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#3842]
> The computed value and used value of ''&lt;color>/transparent'' is ''rgba(0, 0, 0, 0)''.

Originally reported as an inline issue by @tabatkins 

> Gecko disagrees, and serializes any &lt;&lt;color>> with an alpha channel of 0 as transparent.
> No other browser does that though.

**Comment by birtles** [comment]
> Gecko disagrees, and serializes any <<color>> with an alpha channel of 0 as transparent.
> No other browser does that though.

I tried reproducing that behavior locally on Nightly but couldn't. Is there a test case for that?

**Comment by svgeesus** [comment]
This was an old issue I ported from being inline in the spec, onto GitHub. If it is no longer the case, I'm happy to close it.

**Comment by upsuper** [comment]
> I tried reproducing that behavior locally on Nightly but couldn't.

It was fixed in [bug 1339394](https://bugzilla.mozilla.org/show_bug.cgi?id=1339394).
