### ISSUE TITLE
[css-color-adjust-1] Add 'color-scheme: auto'?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3849]
Rune's version of color-scheme gives "light" as the initial value, and assumes "light" if the user doesn't express a preference.

This is definitely what's required for web compat in general, but there are still minority user agents that do *not* render with a "light" style by default (and just accept that they're not always web-compatible).

I propose adding an "auto" value to 'color-scheme' to act as an initial value instead, indicating that the author has no idea what color schemes are, and so the UA should use the legacy "default" color scheme ("light" for maximum web-compatibility).  This is currently in the spec, so you can see what it looks like.

**Comment by MatsPalmgren** [comment]
@tabatkins I can't find this "css-color-adjust-1 spec" you are referring to.  Link please?

**Comment by tabatkins** [comment]
@MatsPalmgren The drafts server was stuck on a draft generation task from last night; the new spec should be up at https://drafts.csswg.org/css-color-adjust-1/ in a little while.

**Comment by quasicomputational** [comment]
I think this is a good idea and it lets UAs DTRT in more cases. My only worry is that `color-scheme: auto` reads like it means something like 'use whatever colour scheme you want', rather than 'fall back to the default colour scheme, which is probably light for compatibility'. Can it be bikeshedded to `color-scheme: legacy` or `color-scheme: compat` or something?

**Comment by tabatkins** [comment]
Yeah, on consideration, I think "none" would be the better term here actually. The property expresses which color schemes you're capable of handling, and the default is to assume they can't handle anything besides the default, thus "none".

**Comment by AmeliaBR** [comment]
> My only worry is that color-scheme: auto reads like it means something like 'use whatever colour scheme you want', 

I agree.

> the default is to assume they can't handle anything besides the default, thus "none".

I'm not sure that's better. It could be confused for `appearance: none`, suggesting that it would turn off all user agent color settings.

I like `default` or `legacy` as keywords for the generic scheme.  That also gives user agents the option to create _nicer_ `light` color schemes in the future, without worrying about compatibility with the legacy late-90s default color scheme.
