### ISSUE TITLE
[css-color-adjust-1] Allow a page to express a theme pref when the user doesn't

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3850]
Rune's spec's processing algorithm handled two cases: letting the page pref win (using "only"), user pref be damned; and letting the user pref win (not using "only"), page pref be damned.  If the user doesn't express a preference, and the page doesn't *force* one, the page automatically gets rendered with "light".

This misses an important use-case, where a page would like to express a *default* preference for one color scheme, but let the user pref, when it exists, win out. (That is, a page might *prefer* dark-mode and want dark form controls/etc by default, but be fine with rendering in light mode if the user actually wants light mode.)

I've modified Rune's algorithm in the spec to allow this: if the user doesn't have a preference, then the first understood value in 'color-scheme' is used. So a page that prefers dark-mode but doesn't want to force it can say `color-scheme: dark light` and get what it wants.

Does this sound reasonable?

**Comment by quasicomputational** [comment]
I like the idea and it should definitely produce better results in terms of more people's preferences being more satisfied. But there's a loose end left, since I dunno what's meant to happen if step 4 is reached - none of the rest of the text deals with the used colour scheme being null. Should it be `no-preference` instead, for compatibility?

**Comment by tabatkins** [comment]
Oh, sorry, that's leftover text from when I was using 'null' to indicate no preference. I'll fix.

**Comment by FremyCompany** [comment]
This sounds reasonable to me.

**Comment by lilles** [comment]
Closing based on resolution: https://github.com/w3c/csswg-drafts/issues/3850#issuecomment-497021324
