### ISSUE TITLE
[css-color-adjust-1] Define what happens to SVG in forced colors mode

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3855]
It's not clear what should happen to SVG elements in forced colors mode. Do text content elements get backplates? Is anything else affected? What do we need to put in the spec to correctly handle SVG?

**Comment by fantasai** [comment]
Specced that `<svg>` elements get `forced-color-adjust: none` while `<text>` and `<foreignObject>` turn it back to `auto` for now. @AmeliaBR and @atanassov might have further comments on what should happen here...

**Comment by AmeliaBR** [comment]
Setting `forced-color-adjust: none` on SVG elements by default would _break_ any SVG that uses `currentColor` for accessibility purposes (to intentionally sync with any forced color changes).  So that's a definite no-go.

That said, I wouldn't recommend that user agents directly adjust any colors on SVG other than for text, and they should only adjust text colors if they are adding in the glyph backplate effect to preserve contrast.

(Authors could of course use the media query & system colors to create a color scheme for data viz or icons that respects the user's palette while still going beyond what `currentColor` can do.  See [Eric Bailey's CSS-Tricks article](https://css-tricks.com/accessible-svgs-high-contrast-mode/) for examples.)

**Comment by AmeliaBR** [comment]
FYI, EdgeHTML currently doesn't do anything with SVG text when WHCM is on: no backplate, and no change to the fill color (unless the author is using `fill: currentColor`).

**Comment by AmeliaBR** [comment]
To sum up my previous comment as a concrete recommendation:

- Remove the [current spec text](https://drafts.csswg.org/css-color-adjust-1/#forced-color-adjust-prop) defining UA stylesheet rules about `forced-color-adjust` and SVG elements.

- Add an item to the list of [Properties Affected by Forced Colors Mode](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties), `fill: currentColor !important; fill-opacity: 1 !important`, but add a qualification that this should only apply for HTML elements and for SVG `text` elements (or descendants of `text`), and should only apply on SVG if the user agent is able to generate an opposing-color text backplate.

  The exact color of the backplate would as usual depend on the context — e.g., inside a `<button>`, where `currentColor` would be `ButtonText`, the backplate color would be `ButtonFace`.

**Comment by AmeliaBR** [comment]
> Why would that break anything? It doesn't have any effect on <color> values.

It resets `color` and therefore `currentColor` & the ability of `currentColor` to sync according to the forced-color mode.

Currently, if I create an SVG icon and set it `color: purple` and `fill: currentColor`, the fill will change in high contrast mode to the WHCM text color or button color, depending on context.  If you set `forced-color-adjust: none` on the same element, it would stay purple.

**Comment by kbabbitt** [comment]
> * Add an item to the list of [Properties Affected by Forced Colors Mode](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties), `fill: currentColor !important; fill-opacity: 1 !important`, but add a qualification that this should only apply for HTML elements and for SVG `text` elements (or descendants of `text`), and should only apply on SVG if the user agent is able to generate an opposing-color text backplate.

+1 for `fill-opacity: 1 !important` (and `stroke-opacity: 1 !important`) being added for forced colors mode.

**Comment by amaher23** [comment]
I was hoping to re-address this issue, specifically regarding what should happen to SVG `<text>` in forced colors mode. After discussing this with @atanassov, there appear to be a couple concerns with setting `forced-color-adjust: auto;` for such elements:

1. Adjusting the styles for SVG textual elements creates an inconsistent experience when the rest of the SVG element is not being styled for forced colors mode.
2. More importantly, the backplate becomes difficult to define in this case. For example, what should the backplate look like for text on a path?

Considering this, I would suggest that we do not apply forced colors to SVG  `<text>`, and only apply `forced-color-adjust: auto;` to `<foreignObject>` SVG elements.
