### ISSUE TITLE
[css-color-adjust-1] Forced Colors Mode issues

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#3860]
In section
3.1. Properties Affected by Forced Colors Mode
<https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties>

-scrollbar-colors: revert !important;
+scrollbar-color: revert !important;
as it got renamed.

-outline-color: revert !important
+outline-color: revert !important; 
missing semicolon

Consider these, too:
+-webkit-text-fill-color: revert !important;
+-webkit-text-stroke-color: revert !important;
as they're in the compatibility spec <https://compat.spec.whatwg.org/#text-fill-and-stroking>
though they may well be implemented as aliases.

**Comment by smfr** [comment]
Let's not use the term "nits". That refers to screen brightness.

**Comment by BillGoldstein** [comment]
Or perhaps use shorthand
+-webkit-text-stroke: revert !important;
(which is also in compat standard), instead of longhand
+-webkit-text-stroke-color: revert !important;

**Comment by tabatkins** [comment]
> Let's not use the term "nits". That refers to screen brightness.

???

**Comment by AmeliaBR** [comment]
> ???

My reaction, too. But per [Wikipedia](https://en.wikipedia.org/wiki/Candela_per_square_metre) “Nit (nt) is a non-SI name also used for [a candela per square metre] (1 nt = 1 cd/m2). The term nit is believed to come from the Latin word nitere, to shine.”

I would not normally consider that specialized usage a conflict with the colloquial meaning of "nit" as "minor bug, like a louse", as in "nit-picking".  But if if confused a native English speaker like Simon, no harm, it could certainly confuse non-native speakers who work with computer graphics but not with English idioms.

___________

All of which isn't relevant to @BillGoldstein's original suggestions, which makes good points, but is a bit of a mixture of items that need to be addressed separately.

@tabatkins, can you follow up on the typos?

For the `-webkit-` fill and stroke properties, we should probably discuss them in combination with the standard `fill` and `stroke`, maybe as part of #3855, about handling SVG.  There, I suggested using a `fill: currentColor` for SVG, but a `revert` could also work in that case.

**Comment by fantasai** [comment]
Fixed the typos, pushed the -webkit-text issue out to https://github.com/w3c/fxtf-drafts/issues/400
