### ISSUE TITLE
[css-text] impact of unstyled inlines on hyphenation

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3862]
Should unstyled inlines affect [hyphenation](https://drafts.csswg.org/css-text-3/#propdef-hyphens)? In other words should `high<span>way</span>` or `highwa<span>y</span>` be allowed to hyphenate differently from `highway`?

We have a general principle that unstyled inlines don't affect anything, but I can't put my finger on anything that turns this general principle on actionable spec text in the case of hyphenation.

I suggest adopting and adjusting the related wording from `text-transform`, and adding it to the hyphens property definition:

> For the purpose of the `hyphens` property, what constitutes a “word“ is UA-dependent. However, out-of-flow elements and inline element boundaries must be ignored when determining word boundaries.

**Comment by tabatkins** [comment]
Agree; I note that Blink's current behavior *does* disable the hyphen in your first example, where the inline is up against the hyphenation opportunity.

**Comment by frivoal** [comment]
Ok, edits are in place for inline element boundaries, but during the call we forgot to discuss a part of what I had written in the original issue: do out of flow element in the middle of the word also make no difference? For consistency with them having no effect on `text-transform:capitalize`, I'd say they don't, but the justification seems less strong, and I'd also be OK with leaving that up to the UA.
