### ISSUE TITLE
[css-text] Styling of soft hyphens

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3863]
If you put a span around a `&shy;` style it (for example, change the color), and the word does get hyphenated (due to the `hyphens` property being `manual` or `auto` and running out of space on the line), does the style get applied to the visible hyphen that gets inserted, or not?

[The spec](https://drafts.csswg.org/css-text-3/#propdef-hyphens) currently doesn't say.

As shown in [this example](https://jsbin.com/kapokixoti/edit?html,css,output), all browsers (FF, Chrome, Safari) do apply the style of the span around the soft hyphen onto the inserted hyphen, so I think it would make sense to spec it that way.

**Comment by frivoal** [comment]
oops, forgot to link to the example: https://jsbin.com/kapokixoti/edit?html,css,output

**Comment by tabatkins** [comment]
Agreed, it should, both from a theory standpoint and, luckily, from a impl-compat standpoint. ^_^

**Comment by fantasai** [comment]
That hyphen is represented by the U+00AD codepoint, so yes, that is what should happen. I think this would just be a clarification, tbh.
