### ISSUE TITLE
Can you provide a way to download css files?

### ISSUE THREAD

**Issue by mhxy13867806343** [w3c/csswg-drafts#3864]
Hello, I am very happy to see my post (I am not very good in English)
Can the official website provide the function of downloading resources (such as files and pictures) for css?
Looking forward to your reply

**Comment by tabatkins** [comment]
I'm not sure what you're asking about here.

If you're asking about being able to download images/etc specified in CSS, that's already handled by your browser's dev tools, and possibly the right-click menu. CSS, the language, has nothing to do with that.

If you're asking about using CSS to specify that something on the page should *trigger* a download, then that's already handled by HTML via the `<a download>` attribute. It's not currently something that CSS is intended to handle.
