### ISSUE TITLE
Other issues with css

### ISSUE THREAD

**Issue by mhxy13867806343** [w3c/csswg-drafts#3865]
Can css provide loops and objects like js, as follows
Css{
   Url:for i in range(1,20)
}
Css[key]{
Video:url('a.mp4')
}

**Comment by svgeesus** [comment]
"This washing machine appears to be unable to even reheat pizza"

**Comment by tabatkins** [comment]
Hi! Unfortunately, it's not clear from your examples what you're asking for. I'll close this issue, but if you can describe the problem you're trying to solve with more detail, either in this issue or a new issue, we can discuss the feature.

**Comment by svgeesus** [comment]
CSS is declarative. It does have variables (custom properties), but they can't hold multiple values because there is no order of execution.

[Declarative vs. Imperative languages](https://medium.com/front-end-weekly/imperative-versus-declarative-code-whats-the-difference-adc7dd6c8380)
