### ISSUE TITLE
[css-text] pre-wrap and tabs at the end of the line

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3869]
The spec doesn't say what happens to preserved tabs at the end of the line in the modes where wrapping is allowed (`pre-wrap` and `break-spaces`).

* For pre-wrap, based on testing, they should be handled like preserved spaces in the same situation: become part of the unbreakable sequence of tabs and spaces (and ideographic spaces) that hangs and that has a wrapping opportunity at the end of it.

* for `break-spaces`, the value is new enough that interop data isn't very meaningful, but I'd suggest being consistent and also doing the same thing as preserved spaces: cannot hang, wrap opportunity after every preserved tab, plus a wrap opportunity between the last letter of a word and the tab that imediately follows it if `line-break` is `anywhere`.

**Comment by fantasai** [comment]
So it seems like no one is arguing for anything other than "can't hang, wraps like a fat space" for break-spaces, and the open question is on what to do in the normal pre-wrap case...

- We didn't really discuss much whether a mixed sequence of tabs and spaces should be breakable or not, but in any case implementations don't break in such sequences so we should go with that.
- We're not agreed on whether tabs are allowed to “hang” at the end of the line or not. (Hanging means they aren't measured when we measure the size of text on the line for the purposes of line breaking, sizing, alignment, or justification.)

An additional note is that the size of a tab depends on where in the line it appears -- not on adjacent context, but on actual position.

There are not many use cases for trailing tab characters; one brought up was TSV files, where trailing tabs are significant and denote separate fields.

**Comment by frivoal** [comment]
I'll go with the assumption @fantasai was making: no breaking between tabs (or spaces) in a sequence of them. So the remaining question seems to be: hang or no hang. Here's an example:

Let's assume a Tab Separated Value file like this:
```
<style>.tsv { white-space: pre-wrap; }</style>
<pre class=tsv>Field1&#9;Field2&#9;Field3&#9;Field4
A&#9;B&#9;&#9;
1&#9;2&#9;3&#9;4
</pre>
```
It would render something like that ("_" mark tab-induced shifts)
```
Field1__Field2__Field3__Field4
A_______B_______________
1_______2_______3_______4
```
Now, let's say we set `pre { width: 16ch; }`.

If Tabs hang, it looks like this:
```
|Field1__Field2__|
|Field3__Field4  |
|A_______B_______|________
|1_______2_______|
|3_______4       |
```
If they don't:
```
|Field1__Field2__|
|Field3__Field4  |
|A_______        |
|B_______________|
|1_______2_______|
|3_______4       |
```

And for what it's worth, if we did allow wrapping between tabs and disallow hanging, we'd get this:
```
|Field1__Field2__|
|Field3__Field4  |
|A_______B_______|
|________        |
|1_______2_______|
|3_______4       |
```

Here's a live demo of that example:
https://jsbin.com/regoquzame/edit?html,css,output

* Firefox does behavior 2 (don't hang)
* Safari and Chrome do behavior 1 (do hang)

**Comment by frivoal** [comment]
tests here: https://github.com/web-platform-tests/wpt/pull/17957
