### ISSUE TITLE
[css-color-4] Prevent fingerprinting with deprecated system colors

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#3873]
In #3804, we agreed to un-deprecate system colors that have important use cases for accessibility (high contrast mode) and dark mode theming.

I'd like to suggest that the spec get more strict about what "deprecated" means for the remaining colors.  Specifically, **user agents should not expose any user-specific data through the deprecated color names**; they should standardize the values for these colors so that they can't be used as fingerprinting data. The colors could still be adjusted for browser & OS, with light & dark mode variants, since that doesn't expose any new information relative to what's already exposed by user agent strings and media queries.

Of the colors that we are keeping deprecated, the problematic one that I know of is `Background`.  In [the spec](https://drafts.csswg.org/css-color-3/#css-system), this is the "desktop background".  On my windows system, both Firefox and EdgeHTML do expose my custom OS desktop background color. Chrome instead exposes my custom OS theme accent color. Which are sufficiently different that I can't see any user benefit from theming to match my colors, but I can see a significant fingerprinting vector.

PS, [Codepen with all the system colors & their definitions, on various colored backgrounds](https://codepen.io/AmeliaBR/full/JbaZLX), if you want to poke around to see what is being exposed for you

**Comment by svgeesus** [comment]
related to #3847

**Comment by tabatkins** [comment]
Agenda+ to see if we can upgrade the current text "encouraging" either using static defaults or mapping to the undeprecated system colors to being a MUST.

**Comment by fantasai** [comment]
Dropping a note here to say: don't forget to say how these values compute, if they compute to other keyword values or to a fixed color or to themselves. (I'm guessing fewer keywords that compute to themselves here is better for implementations.)

**Comment by tabatkins** [comment]
Depends on whether we want them to respond to color-scheme or not.

**Comment by AmeliaBR** [comment]
> Depends on whether we want them to respond to color-scheme or not.

Given that these are legacy values for legacy compat & we don't want authors using them in new content, we can probably safely define them all as light mode values.  If you want to use system colors in a dark mode theme, only use the non-deprecated values.

But, there should probably be a clear warning to authors about that!

**Comment by tabatkins** [comment]
Yeah that sounds reasonable.

**Comment by svgeesus** [comment]
Allright, no-one had any suggestions so:

- anything to do with borders is mapped to `ButtonBorder` because that is the only non-deprecated border color
- backgrounds are mapped to `Canvas`
- text names are mapped to `CanvasText`
- `ThreeDFace` is mapped to `ButtonFace`
- oh and InactiveCaptionText` is mapped to `GrayText` because it is inactive

and all of that is MUST.

Will browsers sign up to implement these changes so that the deprecated system colors are consistently anti-fingerprinting on all browsers on all platforms?
