### ISSUE TITLE
[selectors-4] Need to allow stacked pseudo-element selectors in the grammar

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#3876]
In Lists, we've resolved that ::before and ::after can be set to "display: list-item", thus generating markers. However, [per Selectors grammar](https://drafts.csswg.org/selectors/#typedef-compound-selector), it's not valid to then write a selector like `ol::before::marker`. (You can stack pseudo-*classes* after your pseudo-element, but not more pseudo-elements.)

This seems unfortunate; if a ::before can *generate* a marker, you should be able to *style* that marker.

Additionally, I know that WebKit-derived browsers, at least, *do* allow pseudo-element stacking, to handle styling some of the UA-specific pseudo-elements.

So, we should change Selectors grammar to allow stacking multiple pseudo-elements in a single compound selector. (Individual grammar restrictions will still restrict what sort of stacks are valid; `::before::before` will be an invalid selector, just like `::before:invalid` is invalid today even tho `::before:hover` is valid.)

Since certain pseudo-classes are reasonable to apply to either of the pseudo-elements in the stack, the two need to be arbitrary interleavable. (For example, `::before:hover::marker`.) This gives us a grammar of:

```
<compound-selector> = [ <type-selector>? <subclass-selector>*
                        [ <pseudo-element-selector> | <pseudo-class-selector> ]* ]!
```

**Comment by ExE-Boss** [comment]
Yeah, this is&nbsp;also necessary because of&nbsp;`::part(…)` and&nbsp;`::slotted(…)`, which allow this&nbsp;as&nbsp;well.

**Comment by Jamesernator** [comment]
Firefox already supports `::slotted(...)::before` and such so parsing them isn't webkit unique.

**Comment by emilio** [comment]
::slotted is different, as it selects elemetns.

**Comment by ExE-Boss** [comment]
Yeah, but&nbsp;the&nbsp;way they are&nbsp;currently specified and&nbsp;implemented violates the&nbsp;current `<compound‑selector>` grammar.

**Comment by tabatkins** [comment]
Yup, this is a long-needed grammar change to reflect reality. The fact that the Scoping spec *explicitly* allowed `::slotted()::before` even tho it was grammatically invalid per Selectors just shows that we were behind the ball there. ^_^

**Comment by ExE-Boss** [comment]
Currently, the grammar contains: `[ <pseudo-element-selector> <pseudo-class-selector>* ]*`, where the wrapping group has `*` instead of `?`, which reads to me as:
```
  ╭─────────────────────────────────────────────────────────────────────╮
  │                               ╭─────────────────────────────────╮   │
╟─┤                               │ ╭─────────────────────────────╮ │   ├─╢
  │ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┱─╯ ╰─┲━━━━━━━━━━━━━━━━━━━━━━━━━┱─╯ │   │
  ╰─┨ <pseudo-element-selector> ┠─────┨ <pseudo-class-selector> ┠───̶╰̶─̶╮̶─╯
   ╭┺━━━━━━━━━━━━━━━━━━━━━━━━━━━┛     ┗━━━━━━━━━━━━━━━━━━━━━━━━━┛     │
   ╰──────────────────────────────────────────────────────────────────╯
```
Which would indicate support for multiple pseudo elements.

**Comment by tabatkins** [comment]
...indeed it does. Cool.

**Comment by ExE-Boss** [comment]
I&nbsp;still think the&nbsp;syntax could be&nbsp;simplified.
