### ISSUE TITLE
[css-text] Hanging/collapsing of fixed-width spaces not specified

### ISSUE THREAD

**Issue by briansmith** [w3c/csswg-drafts#3879]
https://www.w3.org/TR/css-text-3/#white-space-rules says "White space processing in CSS affects only the document white space characters: spaces (U+0020), tabs (U+0009), and segment breaks."

However, it is often/usually desirable for the collapsing/hanging behavior to apply to fixed-width spaces when the fixed-width space would cause a line break. Consider:

```html
<p>1&#x205f;+&#x205f;1&#x2005;=&#x2005;2</p>
```
Which renders as:
> <p>1&#x205f;+&#x205f;1&#x2005;=&#x2005;2</p>

The spaces on either side of the `+` are U+205F Medium Mathematical Space and the spaces on either side of the `=` are U+2005. (This is the spacing recommended in http://www.unicode.org/notes/tn28 for these operators.)

Lines wrap at fixed-width spaces already (at least in the browsers I tested). However, in the browsers I tested, these fixed-width spaces do not currently collapse or hang at the end of a line like U+0020. Either collapsing/hanging of these spaces like U+0020 should be the default behavior, or there should be some way to opt into them being treated like U+0020 for the purposes of collapsing/hanging.

**Comment by frivoal** [comment]
Doing something like this could mean changing either or both of these sentences in [4.1.2](https://drafts.csswg.org/css-text-3/#white-space-phase-2) to cover more types of spaces, (maybe U+2000 to U+200A and U+205F)
* > A sequence at the end of a line (ignoring any intervening inline box boundaries) of collapsible spaces (U+0020) and/or ideographic spaces (U+3000) whose white-space value collapses spaces is removed. 
* > If there remains any sequence of white space and/or ideographic spaces (U+3000) at the end of a line: 
  > [... rules about pre-wrap and break-spaces..]

Conceptually, that makes sense to me.

**Comment by litherum** [comment]
There's like a million billion different flavors of spaces in Unicode. What was the reasoning for not including them since their inception?

**Comment by fantasai** [comment]
@litherum Legacy, I imagine. We can gather them up and call them by category Zs, fwiw. http://www.fileformat.info/info/unicode/category/Zs/list.htm Hanging Ogham Space Mark is a bit odd, though, since it's usually visible.

**Comment by briansmith** [comment]
> <fantasai> fantasai: I think we knew that nbsp couldn't hang

I'm not disagreeing, but I don't understand that is special about nbsp that makes it necessary for it to be excepted.

**Comment by fantasai** [comment]
@briansmith It has a lot of legacy usage in holding space for various layouts, so changing its behavior is very risky from a Web-compat perspective.
