### ISSUE TITLE
[css-grid-1] Broken anchor links on section 6. Grid Items

### ISSUE THREAD

**Issue by huijing** [w3c/csswg-drafts#3883]
In the introductory paragraph of section [6. Grid Items](https://www.w3.org/TR/css-grid-1/#grid-items), the anchor links to `text-runs` and `anonymous` for CSS Display Level 3 don't link to anything. Proposing to change them to `https://www.w3.org/TR/css-display-3/#css-text-run` and `https://www.w3.org/TR/css-display-3/#css-anonymous` respectively. Will submit a pull request for this.

**Comment by fantasai** [comment]
The links used to be valid. The Bikeshed markup change in https://github.com/w3c/csswg-drafts/commit/effd3aac inadvertently changed the IDs, and those changes got published to /TR. :/
