### ISSUE TITLE
[css-text] inline elements should not introduce a forced line break or soft wrap opportunity

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#3886]
The spec already says that out of flow elements do not introduce a forced line break or soft wrap opportunity, but it doesn't say that inline elements don't either. It should.

We already have a test for that (https://wpt.fyi/results/css/css-text/line-breaking/line-breaking-015.html). wpt.fyi reports passing in all browsers other than chrome, but it does pass in Chrome 76 on my machine not sure if that's a matter of version or of environment.

**Comment by kojiishi** [comment]
I think this is related with #3897, and that the text might be better to include what @jfkthame pointed out.

Example:
```
<div><break-all><nowrap>1234567</nowrap><nowrap>1234567</nowrap></break-all></div>
```

In this case, there should be a break opportunity between "7" and "1", but great if @fantasai can confirm her intent.

**Comment by frivoal** [comment]
I don't think it's strongly related. If you change the style of an inline element to something that has different line breaking rules, that has an impact (and I'll follow up on that in #3897), but if there's not style change (or style changes unrelated to line breaking), the presence of an element boundary itself shouldn't make any difference: that's what we discussed here.
