### ISSUE TITLE
[css-contain][css-grid] contain:size for grid containers is underspecified

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3892]
[Size containment](https://drafts.csswg.org/css-contain/#containment-size) needs more details to be implementable for Grid containers.  Specifically, is grid item placement considered part of "sizing"?
The grid spec has [Placement](https://drafts.csswg.org/css-grid/#placement) as a separate step before [Grid Sizing](https://drafts.csswg.org/css-grid/#layout-algorithm), which seems to imply that placement should be done as usual.
The spec mentions that properties like `grid` should be taken into account, but the used value for the underlying properties (`grid-template-columns/rows`) are affected by placement, for example by placing items into the implicit grid, or `repeat(auto-fit)`, here's a [testcase](https://bug1488878.bmoattachments.org/attachment.cgi?id=9062783).

The two alternatives for implementing `contain:size` I can think of are:

    1. place items into the grid as usual
    2. run Track Sizing algo but pretend we have no items
    3. calculate the container's size from the track sizes as usual

or:

    1. without placing any items first, run Track Sizing algo and pretend we have no items
    2. calculate a size from those tracks, then discard those tracks
    3. place items into the grid as usual
    4. run Track Sizing algo but pretend we have no items
    5. use the size from step 2 as the container's size

The first alternative would be slightly more efficient, and also easier to implement. The second  alternative likely leads to overflow when the placement creates tracks as in the given testcase.

**Comment by tabatkins** [comment]
> Size containment needs more details to be implementable for Grid containers. Specifically, is grid item placement considered part of "sizing"?
> The grid spec has Placement as a separate step before Grid Sizing, which seems to imply that placement should be done as usual.

Can you elaborate on what you think isn't covered by size containment? The definition of it is exactly two things:

> 1. When calculating the size of the containing element, it must be treated as having no contents.
> 2. Elements with size containment are monolithic.

This seems pretty clear - you size the grid container as if it's empty. By definition, then, placement doesn't take place beforehand, because there's nothing to place.

**Comment by MatsPalmgren** [comment]
Well, there's an intermediary level between the grid container and its contents, which is the tracks. The "containing block" for an item isn't the grid container, it's its grid area which is defined by the tracks. It isn't clear to me how the tracks should be calculated under `contain:size`.

I guess what you're suggesting then is:
```
1. without placing any items first, run Track Sizing algo and pretend we have no items
2. calculate the grid container size from those tracks, then discard those tracks
3. layout the grid container as usual but with the size from 2 as the definite final size
   of the grid container (this will create tracks and size them from the items as usual,
   although the track sizes will have no influence on the grid container's size, but will
   possibly create overflow?).
```
or something else?

**Comment by tabatkins** [comment]
Yes, that's the behavior that'll flow from the current definition of Size Containment, if we don't do anything special for Grid.

This basically lets you skip 11.4 and 11.5, which are the complicated/expensive parts of track sizing; the remainder is trivial in comparison.

**Comment by mrego** [comment]
BTW, I agree with @tabatkins here, as we should consider that the grid container has no items basically all auto-fit tracks are dropped (we can just ignore them).

I've just implemented size containment support for grid in Blink and added a WPT test covering several cases (including some `auto-fit` ones): http://w3c-test.org/css/css-contain/contain-size-grid-003.html

**Comment by tabatkins** [comment]
All right, sounds like the issue is a no-op, then? I'll close; we can re-open if necessary.
