### ISSUE TITLE
[css-fonts] font-size:-webkit-xxx-large

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#3907]
We have `x-large` and `xx-large` but no `xxx-large`.

`-webkit-xxx-large` has been around so long it used to be called `-konq-xxx-large`.

Is there interest in wider adoption of such a font size? We'd like to drop the prefix.

**Comment by emilio** [comment]
FWIW Gecko has `xxx-large` to represent values for legacy font-sizes greater than 7, we just don't parse or serialize that, and only set that from the attribute mapping code. But you can see its effect in:

`data:text/html,<font size="7">Foo`

**Comment by emilio** [comment]
(So it seems reasonable to just not make it magic and unprefix to me)
