### ISSUE TITLE
[css-sizing] Define a term like "uses fit-content inline sizing" (like floats)

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#3928]
For https://github.com/whatwg/html/pull/4143 I tried to define that buttons size in the inline direction like floats do, i.e. "shink-to-fit" (CSS 2.2 terminology) or "shrink-wrap" (HTML used this terminology until I changed it in that PR now), if the inline-size is auto.

It seems reasonable to define a term that means exactly this, that can be used by floats, abspos, `button`s, `legend`s, and whatever else uses this behavior.

In IRC, @dbaron said

> I think it would be reasonable to define the term as "uses fit-content inline sizing" or something like that.  (It's also nice when the term matches a name in author-exposed syntax like fit-content.)

**Comment by fantasai** [comment]
I think you can just say that for a button that's a block or inline block, the used value of `auto` is `fit-content`.

**Comment by fantasai** [comment]
Or maybe, more accurately, “behaves as” `fit-content`. I'm guessing for Web-compat we can't actually set it that way in CSS. :)

**Comment by fantasai** [comment]
(Sorry, accidentally hit the close button earlier.)

**Comment by fantasai** [comment]
Oh! I just remembered that we added a term for handling cases like this: just say “In the inline axis, the automatic size is the fit-content size.” https://drafts.csswg.org/css-sizing-3/#automatic-size
