### ISSUE TITLE
[css-pseudo-4] need for clarification on how ::selection text-shadows work

### ISSUE THREAD

**Issue by Gankra** [w3c/csswg-drafts#3932]
* [Relevant Part Of The Spec](https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos)
* [Additional Discussion in Firefox's Issue Tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1543773#c6)

The spec doesn't seem completely clear on what should happen when there are text-shadows defined by a ::selection pseudo-selector.

I have written a [live demo that demonstrates/discusses how different browsers work here](https://bug1543773.bmoattachments.org/attachment.cgi?id=9064764). But here's a better description:

* **Chrome**: clips ::selection shadows to the highlight, but doesn't disable non-::selection shadows (as if the ::selection was a distinct element, and not a restyling?). More specifically, if a character is selected, its ::selection shadows will be drawn clipped to the highlight, but its non-::selection shadows will be drawn *clipped-out* from the highlight. Notably, shadows of characters that *aren't* selected but still from the same element *aren't* clipped by the highlight.

* **Safari**: seems to be implementing the same logic as chrome, but has extremely buggy clipping/invalidation of the shadows and sometimes ends up drawing shadows outside of the highlight or even when the text isn't selected.

* **Firefox**: clips ::selection shadows to the bounds of the entire text frame. This lets shadows escape the highlight as long as there's text there, but will clip them otherwise. However, the bounds used by firefox for this clipping include the area covered by non-::selection shadows, so non-::selection shadows can expand the area ::selection shadows can escape to. Unlike chrome/safari, firefox completely disables all the non-::selection shadows for the characters that are selected (as if they were being normally overridden by cascading).
  * **Webrender Backend**: Inherits firefox's shadow cascading logic, but doesn't yet clip ::selection shadows any differently from normal ones.

So the questions we have are:

* Should ::selection text-shadows be clipped differently from normal text-shadows? And if so, should they specifically be clipped to the highlight?

* Should ::selection text-shadows cascade and overwrite normal text-shadows, or are selections supposed to act like a new element with a separate text-shadow property? If the latter, should normal shadows be clipped/overwritten by the highlight?

**Comment by Gankro** [comment]
FWIW the folks I have discussed this with at Mozilla seem to like Webrender's behaviour (cascade the ::selection text-shadow as a completely normal, non-specially-clipped, text-shadow). They regard Firefox's special clipping behavior to be an implementation bug, and not intentional (which makes sense if you dig into the implementation details).

**Comment by fantasai** [comment]
Wrt first question, I don't think there's any need for ::selection text-shadows to be clipped differently from normal text-shadows.

Wrt the second question, there was some discussion about it in https://github.com/w3c/csswg-drafts/issues/3605 ; the conclusion was that the ::selection’s text-shadow wins, and UAs are expected to set it to 'none' by default. I'm now thinking about how the mechanics of that are going to work for ::spelling-error and ::grammar-error, and I'm not sure how to describe it....

**Comment by fantasai** [comment]
because for those pseudo-elements, we'd want text-shadows to not be suppressed by default, but it's not clear how the property values interact!

**Comment by fantasai** [comment]
To summarize, the things we seem to want are:

- Author can set text-shadow on a highlight pseudo and have it take effect.
- The default case of selection with a background suppresses document text-shadows, for readability.
- ::spelling-error and ::grammar-error, by default, do not suppress text shadows.

Possible models to make things happy:

- Non-transparent background on any layer disables shadows on layers below
- Background on any layer paints over shadows on layers below (but they may show through if semi-transparent or larger than the background area).
- ???

**Comment by fantasai** [comment]
Related question: if multiple layers specify a text-shadow and there's no backgrounds involved...

- Draw only the topmost non-`none` shadows?
- Draw all of them?
- [Drawing only the topmost value, with `none` suppressing shadows below it, is unworkable due to the desire for ::spelling-error and ::grammar-error to not suppress shadows by default.]

**Comment by TalbotG** [comment]
[6 tests on text-shadow and ::selection](http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/) 

5 of them are manual tests.

I have many more ::selected tests (including 7 new text-shadow ones) but due to webhosting server migration with DNS change, I can not upload those additional tests and I can not update the current 6 ones.

**Comment by fantasai** [comment]
@Gankra @frivoal OK, I've updated the spec with the CSSWG resolutions; text-shadows are now defined to be stacked up under/over the highlight backgrounds. Please let me know if anything seems off. (But note that nobody implements this kind of layering atm.)

**Comment by frivoal** [comment]
The edits linked above seem clear to me, and to correctly reflect the way the WG decided to solve this issue.

**Comment by delan** [comment]
G’day @fantasai @Gankra, I found this issue long after [updating some ::selection text-shadow tests](https://crrev.com/c/2624328) to reflect the new spec behaviour. I didn’t realise specs could actually [reference WPT cases](https://github.com/w3c/csswg-drafts/blob/3e610ca1e6cbeabe6e90f14688d4d265a2ccd8f1/css-pseudo-4/Overview.bs#L538-L539) until I stumbled upon [the bikeshed button](https://drafts.csswg.org/bikeshed/css-pseudo-4/):

![screenshot](https://user-images.githubusercontent.com/465303/104865625-9a128600-5990-11eb-8671-56dd9bdfd24c.png)

Sorry for breaking that. I’ve replaced those two with [highlight-painting-order.html](https://wpt.live/css/css-pseudo/highlight-painting-order.html) which:

* checks the relative painting order of text, original shadows, ::selection background, and ::selection shadows
* asserts that the ::selection shadows are unclipped and independent of the original shadows

**Comment by TalbotG** [comment]
Delan,

Thank you for reporting these problems.

I added 
css/css-pseudo/selection-text-shadow-006-manual.html
css/css-pseudo/selection-text-shadow-016.html
css/css-pseudo/selection-text-shadow-016-ref.html
in [PR20802](https://github.com/web-platform-tests/wpt/pull/20802)
and then I bikeshed-added these in [PR5006](https://github.com/w3c/csswg-drafts/pull/5006)

So I will verify again my work (in the next 2-3 days), trying to find (and fix) what caused the bikeshed FATAL errors.

Gérard

**Comment by delan** [comment]
@TalbotG I removed them because the changes they needed, both for the new spec and new browser quirks that broke them, would have neared a rewrite anyway, and I had already designed [a reliable reftest](https://bucket.daz.cat/work/igalia/0/3.html) that subsumes their functionality.

**Comment by TalbotG** [comment]
Delan,

I have bikeshed-added a link to your highlight-painting-order.html test 
(along with links to 31 other tests) and I have removed the links to
selection-text-shadow-006-manual.html
selection-text-shadow-016.html
in [PR5899](https://github.com/w3c/csswg-drafts/pull/5899) . So the 2 Bikeshed Errors should disappear when the bikeshed/css-pseudo-4/ gets regenerated .

**Comment by delan** [comment]
Wonderful! Thanks @TalbotG.
