### ISSUE TITLE
[selectors-4] "effective media volume is mutable" pseudo-class for media elements

### ISSUE THREAD

**Issue by hober** [w3c/csswg-drafts#3933]
Split out from #3821.

In [§11 Resource State Pseudos](https://drafts.csswg.org/selectors/#resource-pseudos) we currently have the `:playing` and `:paused` pseudo-classes, which collectively address the use case of a custom "play/pause" media control which should appear as a play button or as a pause button depending on the current play state of the associated media element. In addition to the cases covered in #3821, a bunch of us (@beccahughes @mounirlamouri @padenot @jyavenard @eric-carlson @jernoble et al.) would like to mint a new pseudo-class to expose whether or not setting [the **volume** IDL attribute](https://html.spec.whatwg.org/multipage/media.html#dom-media-volume) would result in the element's [**effective media volume**](https://html.spec.whatwg.org/multipage/media.html#effective-media-volume) actually changing.

With such a pseudo-class, it would be be possible (without script) to show or hide custom volume controls based on whether or not using such a control would actually result in a user-audible change.

I have no specific proposal for a name. Bikeshedding very welcome. @AmeliaBR has [several suggestions](https://github.com/w3c/csswg-drafts/issues/3821#issuecomment-491097390).

**Comment by hober** [comment]
For context, see the discussion on #3821 starting with @tabatkins' [comment](https://github.com/w3c/csswg-drafts/issues/3821#issuecomment-487171357).

**Comment by AmeliaBR** [comment]
Copying over the [initial suggestions from the other issue](https://github.com/w3c/csswg-drafts/issues/3821#issuecomment-491097390):

For starting the bikeshed debate on that separate issue (please copy over once there's somewhere to copy to):

- `:adjustable-volume`
- `:not(:user-volume)`
- `:not(:volume-locked)`
- `:volume-unlocked`
- Or maybe a set of `:volume()` variations, like `:volume(muted)`, `:volume(locked)`, `:volume(max)`…

**Comment by jensimmons** [comment]
@hober just dropped ( in IRC at the CSSWG) possible code syntax for a usecase:
```
div.controls:volume(locked) { display: none; }
```

**Comment by tabatkins** [comment]
Extracting from minutes: If we resolve on adding a volume-level pseudo (#4001), then we should revisit the naming of this and merge "muted", "locked", and "volume-level" all into one pseudo, presumably with the syntax:

```
:volume( locked || muted || <volume-value> )
<volume-value> = [ '<' | '>' ] '='? [ <number [0,1]> | <percentage [0%,100%]> ]
```
