### ISSUE TITLE
[css-overscroll-behavior-1] FPWD request

### ISSUE THREAD

**Issue by majido** [w3c/csswg-drafts#3939]
Requesting to publish css-overscroll-behavior-1 as FPWD.

Last discussion on this topic was in TPAC 2018 and notes are [here](https://lists.w3.org/Archives/Public/www-style/2018Dec/0000.html). The two issues that were brought up have been resolved:

1.  Per offline discussion with @astearns, I have confirmed that IP is no longer a concern. 
2. [Logical longhands](https://github.com/w3c/csswg-drafts/issues/2473) have been added.

**Comment by smfr** [comment]
https://drafts.csswg.org/css-overscroll-behavior/

**Comment by majido** [comment]
CSSWG RESOLVED: Publish css-overscroll-behavior-1 FPWD

Details [IRC logs](https://logs.csswg.org/irc.w3.org/css/2019-05-22/#e1178335):

AmeliaBR Topic: css-overscroll-behavior-1 FPWD | 09:18:04 PDT
# | AmeliaBR ???: We discussed at F2F, there were some concerns about longhands. I need to check with astearns, but I think I've addressed the edits. | 09:18:52 PDT
# | florian sounds good to me | 09:18:55 PDT
# | fantasai s/???/majidvp/ | 09:19:21 PDT
# | fantasai s/need to check/checked/ | 09:19:30 PDT
# | AmeliaBR majidvp: There are two implementations already, in Chrome and Firefox. | 09:19:36 PDT
# | fantasai s/astearns/astearns about IPR and it's OK, because of CG commitments/ | 09:19:46 PDT
# | AmeliaBR Rossen_: So are you asking for FPWD or CR? A fast path to CR? | 09:19:59 PDT
# | AmeliaBR majidvp: Yes. | 09:20:05 PDT
# | AmeliaBR Rossen_: And you say that you've already confirmed that you don't expect major IP concerns. So we can move forward with FPWD. | 09:20:46 PDT
# | AmeliaBR … Any objections/concerns? | 09:20:55 PDT
# | AmeliaBR florian: Ship it! | 09:21:01 PDT
# | AmeliaBR RESOLVED: Publish css-overscroll-behavior-1 FPWD

**Comment by xfq** [comment]
[Published 6 June](https://www.w3.org/TR/2019/WD-css-overscroll-1-20190606/), as `css-overscroll` shortname.
