### ISSUE TITLE
ResizeObserverEntry either needs to have its JS constructor removed, or define how its members are initialized when constructed

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#3946]
Quoting https://drafts.csswg.org/resize-observer-1/#resize-observer-entry-interface :
```webidl
[Exposed=Window, Constructor(Element target
)]
interface ResizeObserverEntry {
    readonly attribute Element target;
    readonly attribute DOMRectReadOnly contentRect;
    readonly attribute ResizeObserverSize borderBoxSize;
    readonly attribute ResizeObserverSize contentBoxSize;
};
```

Is it really intentional that this interface has a web-exposed constructor? i.e. is it really intended that web content can do `var foo = new ResizeObserverEntry(someElem)`?

If it's not supposed to be web-exposed (and I suspect it's not?), let's remove the `Constructor(...)` from its WebIDL.

Otherwise -- i.e. if the constructor is supposed to be web-exposed -- then the spec needs to explain what the member-variables (contentRect, {border,content}BoxSize) should be initialized to in that scenario.  Right now those members are all defined in terms of the size/rect "...when `ResizeObserverCallback` is invoked" -- but in this case of a JS-constructed ResizeObserverEntry, there is no `ResizeObserverCallback` involved / invoked. There is only a passed-in element.

CC @atotic @gregwhitworth

**Comment by dholbert** [comment]
Note that Chrome dev channel currently rejects `new ResizeObserverEntry(elem)` with `TypeError: Illegal constructor`.  Here's a fiddle to demonstrate that:
  https://jsfiddle.net/dholbert/w9L0dc1f/

In contrast, Firefox happily constructs a ResizeObserverEntry, though it may null-deref if you try to do anything with that object per https://bugzilla.mozilla.org/show_bug.cgi?id=1552911 because its contentRect/borderBoxSize/contentBoxSize are undefined.

**Comment by dholbert** [comment]
Two followup notes:

(1) It looks like this `Constructor(Element target)` IDL dates back to this 2016 commit in the WICG repo:
https://github.com/WICG/ResizeObserver/commit/32515cb4b3732ae9b36439114faa41420c81e2ff#diff-ec9cfa5f3f35ec1f84feb2e59686c34dR145

I suspect Chrome never implemented this constructor, though, so maybe it's not really needed/useful?


(2) Replying to my initial comment here -- things are defined a bit better than I'd thought.   I realized that the spec **does** define what these variables should be initialized to, in the JS-exposed constructor.  e.g.:
```
new ResizeObserverEntry(target)
   [...]
   Set this.borderBoxSize slot to result of computing size
   given target and observedBox of "border-box".
```
https://drafts.csswg.org/resize-observer-1/#dom-resizeobserverentry-resizeobserverentry

So, this means that the JS `var foo = new ResizeObserverEntry(elem)` needs to synchronously flush layout and do a bunch of measurements, which I guess is fine, but do we really need it?

**Comment by dholbert** [comment]
> In contrast, Firefox Nightly happily constructs a ResizeObserverEntry, though it may null-deref [...] per https://bugzilla.mozilla.org/show_bug.cgi?id=1552911

Note: we just landed a patch in that bug to remove the ResizeObserverEntry constructor (so now we match Chrome, and both Firefox/Chrome diverge from what the spec says).

**Comment by atotic** [comment]
I think ResizeObserverEntry constructor should be dropped from the spec. 
@gregwhitworth ?
Chrome issue was filed a long time ago, but dropped off the radar. https://crbug.com/674520

**Comment by dlibby-** [comment]
I think the constructor should be dropped from the idl, but the language around how to populate a ResizeObserverEntry should be moved to the "Broadcast active observations" section.

I've Agenda+'d this to discuss on next week's call

**Comment by bkardell** [comment]
Confirmed the WebKit implementation also does not expose the constructor, fwiw..

**Comment by annevk** [comment]
Per @domenic this is fixed.
