### ISSUE TITLE
[web-animations-1] Add `getAnimations()` to `ShadowRoot`

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#3951]
Currently the following will return an empty array:

```js
const shadow = host.attachShadow({ mode: 'open' });
const elem = document.createElement('div');
shadow.appendChild(elem);
elem.animate(...);

// Get the animations from the host
// --> Returns empty array because getAnimations does not cross shadow-tree boundaries
host.getAnimations({ subtree: true });
```

To make working with shadow trees easier we could add:

```webidl
partial interface ShadowRoot {
  sequence<Animation> getAnimations();
};
```

(Or should we add this to `DocumentFragment` instead?)

**Comment by emilio** [comment]
Is it worth it to have it in DocumentFragment? No fragment other than shadowroot can ever be connected to the document...

But if so, maybe worth having it in ContainerNode? That'd handle all of {Document, DocumentFragment, Element}.

**Comment by birtles** [comment]
> But if so, maybe worth having it in ContainerNode? That'd handle all of {Document, DocumentFragment, Element}.

Yeah, we want different behavior for `Document` and `Element` however (`Document` doesn't need the `{ subtree: true }` flag since it should always be true there). I'll just add it to `ShadowRoot` for now.

**Comment by emilio** [comment]
Maybe worth just using the [`DocumentOrShadowRoot` mixin](https://dom.spec.whatwg.org/#mixin-documentorshadowroot) then?

**Comment by birtles** [comment]
> Maybe worth just using the [`DocumentOrShadowRoot` mixin](https://dom.spec.whatwg.org/#mixin-documentorshadowroot) then?

That sounds perfect. Thanks!
