### ISSUE TITLE
[mediaqueries-5] prefers-color-scheme wording

### ISSUE THREAD

**Issue by cookiengineer** [w3c/csswg-drafts#3954]
I was currently reading the Draft to `prefers-color-scheme` and I'm wondering... shouldn't it be named `bright` and `dark` instead of `light` and `dark`?

I mean, it's called `dark` and not `heavy`, right?

Link to spec: https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

**Comment by tabatkins** [comment]
Words have multiple meanings. ^_^  'light' antonyms 'dark' quite commonly; e.g. 'light red' vs 'dark red'.

(Bright isn't actually right word for this, as it often means "vibrant" or "saturated". It *can* be used for white/etc, but it's rarely used for pastels, which are definitely "light".)
