### ISSUE TITLE
[css-sizing-3] Rename spec to CSS Box Sizing

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#3962]
Current title of the css-sizing-3 is "CSS Intrinsic and Extrinsic Sizing", which was accurate when we first drafted up the spec since it only addressed those topics. But now it hosts the full definition of all the sizing properties, so a rename is in order. I propose "CSS Box Sizing".

**Comment by rachelandrew** [comment]
Makes a lot of sense to me (and is also a lot easier to say on stage).
