### ISSUE TITLE
[css-nav-1] Predefined algorithm for spatial navigation

### ISSUE THREAD

**Issue by jihyerish** [w3c/csswg-drafts#3964]
When we first introduced spatial navigation, I also had suggested some features that can customize the default spatial navigation behavior.
One of those was [`nav-rule`](https://github.com/WICG/spatial-navigation/wiki/Proposal-of-spatial-navigation-on-TPAC-2017#nav-rule-property-cssui4) which changes the default focus navigation algorithm(or function).

I'd like to bring this up again. 
It would be helpful for the author to use the predefined function which is used for deciding what will be the most desirable element to move the focus next among candidate elements.

The [distance function](https://drafts.csswg.org/css-nav-1/#find-the-shortest-distance) for the default spatial navigation behavior in the spec was decided depending on [UX test cases](https://wicg.github.io/spatial-navigation/tests/ux/list.html).
In certain cases which aren't counted in the test cases, other algorithms suit better than the default.
For example, for the page perfectly filled within a grid layout.
Moving the focus to the closest element only considering the one axis corresponding to navigation direction would be more reasonable. (If the right or left arrow key is pressed, only consider the distance along the x-axis.)
To define the distance function like this is straightforward and it may be used frequently.

Therefore the CSS property which can specify the predefined distance function would be useful.
The author doesn't have to implement such functions.

It would be defined as below:

```
spatial-navigation-function: normal | grid
```
- Value:
  - normal: Moves the focus with the default focus navigation algorithm defined by UA
  - grid: Moves the focus to the closest element only considering the one axis which corresponds to the direction of navigation.
- Inherited: Yes

[This demo](https://raw.githack.com/WICG/spatial-navigation/develop/demo/calendar/index.html) shows how this property works.

**Comment by dbaron** [comment]
This seems like it could be a reasonable thing to do, but I'm a little concerned about the wording in your description.  Saying that you're only considering a single axis seems to imply that distance in the other axis is not considered -- whereas I would think for what you describe you would instead need to penalize distance in the other axis more severely than the current algorithm does, in order to continue moving straight along the desired axis.  (Would that happen as a result of changing the `orthogonalWeight` in the distance function, or something like that?)

**Comment by jihyerish** [comment]
Oh, my description was ambiguous. The way to calculate the distance for the `grid` value is different from the distance function in the spec, and it doesn't use the distance function.

For `grid` value, three factors are considered when we calculate the distance:
(1) The distance along the axis which corresponds to the direction of navigation
(2) The amount of alignment
(3) The Euclidean distance

If there are more than one aligned candidates in the navigation direction:
  - Among the aligned candidates, select the best one as a result of the calculation from (1)
  - In case of best candidates more than two, select the best one with the minimum (2).

Else if there isn't any aligned candidate in a given direction
   - Among other(not aligned) candidates, select the best ones as a result of calculation from (1)
   - In case of best candidates more than two, select the best one with the minimum (3).

Therefore, this won't affect the `orthogonalWeight` in the distance function.
