### ISSUE TITLE
[css-sizing-3] Why was min-content, etc. redefined to do nothing in the block axis?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#3973]
https://drafts.csswg.org/css-sizing-3/#sizing-values

> min-content
> If specified for the inline axis, use the min-content inline size; otherwise behaves as the property’s initial value.

Why is it now defined this way (it didn't use to be)? This makes it impossible to use this property in min/max-block-size properties, which is useful.

(Chrome's UI was using it, until https://chromium-review.googlesource.com/c/chromium/src/+/1599691 broke it when we matched the spec)

**Comment by cbiesinger** [comment]
@fantasai @tabatkins

**Comment by cbiesinger** [comment]
This is now also inconsistent with flexbox's min-height: auto, which references the min-content size, which was not changed.

https://drafts.csswg.org/css-flexbox/#min-size-auto
https://drafts.csswg.org/css-sizing-3/#min-content

**Comment by Loirooriol** [comment]
Related: #3684

**Comment by mstensho** [comment]
@mstensho

**Comment by dbaron** [comment]
Do you have a link to the old definition?

**Comment by Loirooriol** [comment]
@dbaron I guess the change was https://github.com/w3c/csswg-drafts/commit/2eda98a1fce8d1ece006c9f667547d85b88196fc, so previously it was

> **min-content**
> Use the min-content inline size or min-content block size, as appropriate to the writing mode.

https://drafts.csswg.org/date/2016-12-29T05:58:14/css-sizing-3/#size-keywords

**Comment by dbaron** [comment]
So given the way min-content and max-content sizes [are defined](https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes), I don't think it's clear what that means, since the size of a float in the block dimension depends on the inline-size of its containing block, and this definition doesn't say what inline-size to use.  Then again, this lack of clear definition of intrinsic sizes in the block dimension is a longstanding problem; see #2890.

I would definitely by opposed to adding this back if the behavior isn't clearly defined.  (If it is defined, then my position likely depends on the definition.)  I think defining it requires at a minimum fixing #2890.)

**Comment by tabatkins** [comment]
We've reverted the change to make everything compute to 'auto' in 45d446438. 'auto', specifically, invokes too much additional magic, which was causing some issues, as cited by @cbiesinger. 

Leaving the issue open to:
1. hopefully get some info from @cbiesinger as he promised ^_^
2. spend time in a few weeks to deal with 2890 in a systematic fashion.

**Comment by Loirooriol** [comment]
@tabatkins Not sure if I'm missing something, but your commit just changed "behaves as the property’s initial value" (i.e. `auto`) to "compute to `auto`". So it's basically the same, but messing with inheritance, against the resolution from #2708?

**Comment by tabatkins** [comment]
...huh, that's not what I meant. Must have copypasted a little too blindly. @fantasai and I will revisit this, sorry about that.

**Comment by janosh** [comment]
This redefinition causes unexpected and differing behavior (compared to Chrome and Safari) when combined with `position: sticky;` [as explained here](https://bugzilla.mozilla.org/show_bug.cgi?id=1597055).

**Comment by Loirooriol** [comment]
> ...huh, that's not what I meant. Must have copypasted a little too blindly. @fantasai and I will revisit this, sorry about that.

@tabatkins ping ^

**Comment by Loirooriol** [comment]
So just to see if I understand 64d08603ce6f37d3cfcc3e70c8462b523e3a42bb, if I have
```css
#grid {
  display: grid;
  block-size: min-content;
  grid-template-rows: minmax(50px, 100px);
}
```

then the height should be `50px` and not `100px`? Chromium used to behave like this, but changed in https://crbug.com/906039

Also, now the spec says "unless otherwise specified, this is equivalent to its automatic size", not "behaves as the property’s initial value". Does this mean that in
```css
#grid-item {
  display: block;
  min-block-size: min-content;
  block-size: 0;
}
```
the item is supposed to behave like `block-size: auto` instead of using an automatic minimum size (that would be 0)? Chromium also used to do this, but changed in https://crbug.com/902863

**Comment by cbiesinger** [comment]
I believe I'm to write up Chrome's behavior (before we removed it), not write a full spec. so here it is--

We treat this very similar to height: auto -- at the end of layout, we store the height that the box ended up with before clamping it according to height/min-height/max-height. There is no need (and really, no way) to calculate this in a separate pass because never need this value outside of layout.

For orthogonal flows, we basically treat this like height: auto again. In the typical case they need to be laid out to find their width; so this fits in well with that.

The only downside is that percentages do resolve to the value they have during layout. This isn't a problem in practice. (Come to think of it, maybe the spec requires us to always resolve percentages relative to height: min-content as auto... not sure). The only place that does require special handling is flex (and, I assume, grid) due to the multi-pass layout that shrink an object -- you don't want a height: 100% child prevent flex-shrinking. So for this case, when we do the initial pass to resolve flex-basis: auto and min-height: auto, we set a flag to treat percentages as auto, which will get fixed up during the flexing pass.

**Comment by cbiesinger** [comment]
This issue also makes it harder for Blink to implement the correct min-block-size: auto behavior for aspect-ratio.

**Comment by tabatkins** [comment]
@cbiesinger As far as we can tell, the current state of the specs accurately captures what you're saying here. min/max-content resolves to the min/max-content size, as defined by the layout mode; by default, we say that this is equal to the automatic size in the block axis, but allow layout modes to override that (https://drafts.csswg.org/css-sizing/#valdef-width-min-content). Grid and Flexbox both explicitly override that by defining exactly what the min/max-content sizes are in both axises, in dedicated sections of their specs (https://drafts.csswg.org/css-grid/#intrinsic-sizes and https://drafts.csswg.org/css-flexbox/#intrinsic-sizes).

Is there anything missing there, or mis-defined such that your preferred behavior isn't allowed?

**Comment by davidsgrogan** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1135207 in response to https://github.com/w3c/csswg-drafts/issues/3973#issuecomment-672193190

**Comment by cbiesinger** [comment]
Tab -- ok, yeah, my understanding is that the current text makes this div:
```html
<div style="height: 0px; min-height: min-content; overflow: hidden;">
XXX
</div>
```
be the height of the text. If that's right, I am happy.

**Comment by tabatkins** [comment]
Yup, that's correct.

**Comment by fantasai** [comment]
Agenda+ to confirm https://github.com/w3c/csswg-drafts/issues/3973#issuecomment-672193190
