### ISSUE TITLE
[css-inline-3] make `text` of `leading-trim` interoperable?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#3978]
Unfortunately all impls compute different positions for `text-top`, and that the [`leading-trim: text`](https://drafts.csswg.org/css-inline-3/#valdef-leading-trim-over-text) value using it doesn't make this property interoperable. I would like the property to provide at least one value that is interoperable across platforms (browsers/OS).

I discussed with @litherum on this before. IIUC we would like to have two text-top/bottom metrics; one which is interoperable, another which is compatible with the current layout engine of the platform.

How about something like:

| Value | Description |
----|----
| **_platform-text_** | Use the text-top/bottom metric. This value matches to metric used by the layout, but may vary by platform. |
| **_typo-text_** | Use the text-top/bottom metric using `sTypoAscender`/`sTypoDescender` from [`os/2`](https://docs.microsoft.com/en-us/typography/opentype/spec/os2) table in OpenType fonts, or the tightest metrics on other font systems that can provide multiple text metrics. |
| **_em-height_** | Use the text-top/bottom metrics using the synthesized em-height metrics. The em-height metrics is computed by normalizing the `typo-text` metrics to 1em. For example, the text-top em-height for OpenType is computed by `sTypoAscender / (sTypoAscender + sTypoDescender) * font-size`. |

The _em-height_ is a metric invented by Gecko, @jfkthame explained [here](https://github.com/whatwg/html/issues/2470#issuecomment-291425136).

@fantasai

**Comment by litherum** [comment]
> @litherum ... would like to have two text-top/bottom metrics

This isn’t quite an accurate characterization. I said it didn’t sound like a bad idea; I didn’t say I want it.

**Comment by kojiishi** [comment]
Oh, sorry and thank you, apparently I misunderstood, apologies and thank you for clarifying that. @fantasai was hesitant to support platform-specific text metrics in this new property, I'm happy to go without it.

**Comment by litherum** [comment]
I wonder if having interoperable values for `text-top` is enough, because of integral rounding that happens in the block axis. As far as I know, this rounding isn't specified anywhere, and I wouldn't be surprised if it was implemented differently in each browser. In WebKit, we've even considered removing this rounding entirely (though we haven't done it).

`leading-trim` applies to block containers, which I believe will cause each paragraph of content to have this 1px rounding difference, meaning that the differences will stack. Given that ascents themselves are calculated differently in different browsers and platforms, differences across platforms arising from `leading-trim` will likely be smaller than differences arising from regular text metrics. However, if this proposal is the first step in a larger effort of standardizing all text metrics across browsers/platforms, the rounding behavior might either thwart the effort or have to be specified itself.

**Comment by kojiishi** [comment]
Thank you for the feedback. I was originally thinking about big differences in the 3 ascent/descent metrics, which often gives a largely (>10 pixels) different positions on large font size. But if we can also make rounding behavior interoperable, I think it's a great achievement. It is a bit larger topic, because this issue was talking only about values that derives from ascent/descent, but rounding applies to all values of [`leading-trim`](https://drafts.csswg.org/css-inline-3/#leading-trim-property).

When thinking about rounding behavior, I can think of multiple levels.
1. Floating point rounding when computing ascent/descent by `value * font-size / em_unit`.
2. Rounding it to fixed point.
3. Rounding it to CSS or physical pixel.

I guess you're talking about rounding at step 3, correct? Step 1 produces slightly different values depends on CPU/FPU, and step 2 is known to be different by each browser, I think these two are hard to standardize.

Do you have any preferred way to do this? I don't have much experiences of what kind of rounding to physical pixels can render glyphs best.

**Comment by kojiishi** [comment]
Thinking further, I think rounding deserves its own issue, opening a new one.

**Comment by tobireif** [comment]
Related: https://github.com/w3c/csswg-drafts/issues/2228

It would be great if the linked issue will get fixed by this ticket here 😀

**Comment by tobireif** [comment]
> RESOLVED: Spec that text-top/bottom and background boxes of inlines ought to match
> RESOLVED: make leading-trim's text value match the same value for text-top/text-bottom/etc

Will the issue described at https://github.com/w3c/csswg-drafts/issues/2228 get fixed by the above decisions?

**Comment by litherum** [comment]
> Will the issue described at #2228 get fixed by the above decisions?

No.

**Comment by faceless2** [comment]
> we should try to request vendors to describe what's happening to have better spec text

Because it's relevant to this issue as well, a note that I've written up the details of how each browser chooses font metrics at https://github.com/w3c/csswg-drafts/issues/2228#issuecomment-631657902

**Comment by fantasai** [comment]
Follow-up for defining interoperable ascent/descent metrics via @font-face is https://github.com/w3c/csswg-drafts/issues/4792
