### ISSUE TITLE
[css-color-adjust-1][mediaqueries-5] Clearly define what 'light' and 'dark' mean

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#3983]
A common theme came up in discussions of #3853 (about `sepia`), #3849 (about `normal` not always being the same as `light`) and #3859 (about an `any` option for the `color-scheme` property): `light` and `dark` themes don't always have to be the same from browser to browser.  But a web page author needs confidence that if they say they support the theme, it won't result in a broken site.

To me, the most important way something can be “broken” by colors is if it fails contrast minimums.

I therefore propose that we include explicit requirements for browser's built-in light & dark schemes, based on the WCAG contrast formula. For example, for `light` mode we could say:

- The default canvas color (and new [`canvas` system color](https://github.com/w3c/csswg-drafts/issues/3804)) must meet AAA contrast for all text sizes when compared against `#333` text.

- The default text color (`text` color keyword) must meet AAA contrast for all text sizes when compared against `#ccc` background color.

A `dark` scheme would have the requirements reversed.

That way, an author could use the built-in `light` theme canvas color and set their own text colors, knowing the contrast will be good enough so long as their chosen text colors are at least as dark as `#333` (or whatever cut-offs we choose).

Now, only talking about contrast leaves a lot of room to move.  Maybe too much.  A `yellow` on `darkblue` scheme would meet the definition of a `dark` scheme above, but it might clash on many websites designed for current dark mode schemes.  So maybe we also want maximum saturation level or other restrictions.

 But my point is, if we want to allow authors to use a color-scheme but selectively override parts of it, they need to know what they can expect.  So, while we may also want to keep a broad definition of what light & dark mean (possibly broad enough that `light` could include sepia schemes), we need to limit how broad it can get.

Spec links:
https://drafts.csswg.org/css-color-adjust-1/#preferred
https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

**Comment by tabatkins** [comment]
Note that sepia does indeed pass WCAG AAA, with a contrast ratio against white of 8.47.

Overall this seems like a good idea.

**Comment by svgeesus** [comment]
I see this text in the spec, which is simultaneously precise and imprecise (my bold):

> Additionally, if the UA determines (**based on Lab lightness**), that the canvas color is clearly either dark or light (for some reasonable UA delineation of “dark” or “light”), then it must match the appropriate value of the prefers-color-scheme media query and express a corresponding user preference for color-scheme.

Now, since L=50 is defined to be exactly mid-way, visually, between light and black then basing this on CIE Lightness is a good start. But then the spec text veers off into untestable handwaving while still using an RFC2119 must. I don't see why. Here is some suggested wording that splits lightness into thirds: light, mid/no-preference, and dark:

> Additionally, if the UA determines,based on Lab lightness, that the canvas color is clearly either dark (L < 33%) or light (L >67%) , then it must match the appropriate value of the prefers-color-scheme media query and express a corresponding user preference for color-scheme.

**Comment by fantasai** [comment]
Added a note as resolved in https://github.com/w3c/csswg-drafts/issues/3983#issuecomment-499240804 and adjusted the color-scheme assumption rules as suggested by @svgeesus in https://github.com/w3c/csswg-drafts/issues/3983#issuecomment-585326098 (which is really a separate issue, but anyway). Specified the range in between as explicitly UA-defined.
