### ISSUE TITLE
[css-ui] "control" is undefined

### ISSUE THREAD

**Issue by jugglinmike** [w3c/csswg-drafts#3990]
gh-3971 generalized the specification's references to "form controls" to simply "controls". However, neither term has a precise definition in either CSS or HTML. This is particularly hazardous because the term "control" may be interpreted to involve interactivity, but (as noted in gh-3971) it is actually intended to include non-interactive elements like `<meter>`.

https://drafts.csswg.org/css-ui-4/#control-styling

**Comment by bkardell** [comment]
Probably much to the dismay of everyone, I would like to ask the potentially naive, and maybe already asked question: is a control really just something which has shadow dom?  Like, if you don't hinge it on something like 'interactive element' and it gets wonky and hard to define -- doesn't it wind up being more or less anything with a shadow dom and the conversion more or less the same as those being had by folks producing custom elements with the same sorts of concerns/disagreements about whether you should expose parts/thems them and how?

**Comment by jugglinmike** [comment]
So long as we're being naive... If "control" were defined as "anything with a shadow DOM," then could `appearance: none` simply be interpreted as "do not render the shadow DOM"?

**Comment by SelenIT** [comment]
Does the term _control_ used here differ from the term _widget_ used in the "Rendering" section [of the HTML standard](https://html.spec.whatwg.org/multipage/rendering.html#widgets)? If the difference is not substantial, maybe it would make sense to reuse the same term in both places?

**Comment by jugglinmike** [comment]
HTML doesn't define the term "widget" in a way that Bikeshed is aware of. We could link informally using anchor tags, but that's prone to rot. To properly reference the term "widgets" here, we'll need to update HTML to formally define it.

@frivoal could you verify that replacing the undefined term "control" with [the term "widget" as defined in HTML](https://html.spec.whatwg.org/#widgets) is appropriate?

**Comment by jugglinmike** [comment]
@frivoal I'd be happy to submit a patch changing "control" to "widget," but I'd like to confirm that such a change would be acceptable. Can you let me know?

**Comment by zcorpan** [comment]
I think "widget" for these things is OK.

"Widget" is also a term in ARIA, which is a class of roles, closely related to these but also including e.g. `link` (which wouldn't be an HTML/CSS "widget").

**Comment by jugglinmike** [comment]
Thanks, @zcorpan! I've proposed the first step (defining the term) over in whatwg/html:

https://github.com/whatwg/html/pull/4725

**Comment by zcorpan** [comment]
@gregwhitworth it covers these elements for HTML:

https://github.com/whatwg/html/pull/4857/files#diff-41cf6794ba4200b839c53531555f0f3998df4cbb01a4d5cb0b94e3ca5e23947dR112406-R112411 of which `progress` and `meter` are non-interactive. But there are also elements that seem like widgets or components but don't have any special treatment for the `appearance` property (e.g. `details`/`summary`), and so aren't "widgets" with this definition.
