### ISSUE TITLE
[css-text-decor] text-decoration-width claims to be a sub-property of text-decoration, but text-decoration disagrees.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3993]
https://drafts.csswg.org/css-text-decor-4/#text-decoration-width-property says (emphasis mine):

> This property, **which is also a sub-property of the text-decoration** shorthand, sets the stroke thickness of underlines, overlines, and line-throughs.

However that links to https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration, which makes no mention of this property.

How does the text-decoration shorthand impact this? Does it reset `text-decoration-width` to `auto`? Or does it actually allow parsing `text-decoration-width`?

**Comment by emilio** [comment]
cc @litherum

**Comment by fantasai** [comment]
Looks like the definitions from L3 generally haven't been imported to L4. The answer should be, "text-decoration is able to parse it in", so

```
text-decoration:  | | <'text-decoration-line'> || <'text-decoration-style'> || <'text-decoration-color'>
```

becomes 

```
text-decoration:  | | <'text-decoration-line'> || <'text-decoration-style'> || <'text-decoration-color'>|| <'text-decoration-thickness'>
```

**Comment by dholbert** [comment]
Note that this property is [now named `text-decoration-thickness` (not `-width`) in the ED](https://github.com/w3c/csswg-drafts/commit/ffbfa0685c9a1714411b19c0b4abab6a01d5bd48).

--> Editing the title of this issue accordingly.
