### ISSUE TITLE
[css-display] The 'flow' keyword is redundant

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#3998]
It looks like all variations that includes the [`<display-inside>`](https://drafts.csswg.org/css-display/#typedef-display-inside) `flow` keyword computes to the same value when `flow` is removed, so the keyword looks redundant to me. (Maybe it's a remnant from when `display-inside` was a longhand and thus needed an initial value?) I tend to think we shouldn't add extra keywords that have no effect so I'd prefer to remove it (at least for now).

**Comment by tabatkins** [comment]
I'm not a huge fan of a behavior only being communicated thru the absence of a value; when possible, I prefer an explicit value being allowed, even if omitting it would give the same result in all cases. It makes the feature much easier to reason and talk about. This is why we've kept 'flow' here.

(It is indeed a remnant of the separated properties, tho.)

**Comment by tabatkins** [comment]
Agenda+ to see if the WG is okay with resolving as WONTFIX (keeping the value).

It's currently shipping in Firefox, at least, but not in Chrome.
