### ISSUE TITLE
[css-inline] Is overflow created by `leading-trim` ink-overflow or scroll-overflow?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#4010]
[`leading-trim`](https://drafts.csswg.org/css-inline-3/#leading-trim-property) can cause overflows in block direction. Should these overflow be ink-overflow or scroll-overflow?

@fantasai

**Comment by fantasai** [comment]
Good question. I haven't thought about it so deeply. My first thought was ink overflow, but on second thought all it does is make the line box slimmer, and overflowing boxes in a line box are scrollable overflow. See [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cp%20style%3D%22overflow%3A%20scroll%22%3E%0ALine%201%20%3Cspan%20style%3D%22margin%3A%20-2em%200%3B%20height%3A%204em%3B%20width%3A%202em%3B%20border%3A%20solid%20green%3B%20display%3A%20inline-block%22%3EIB%3C%2Fspan%3E%3Cbr%3E%0ALine%202)

**Comment by fantasai** [comment]
[another testcase, this time inline element](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cp%20style%3D%22overflow%3A%20scroll%3B%20line-height%3A%201em%22%3E%0ALine%201%20%3Cspan%20style%3D%22font-size%3A%2010em%3B%20vertical-align%3A%20middle%22%3EIB%3C%2Fspan%3E)

**Comment by fantasai** [comment]
So I think a good rule is, the overflow is whatever it would be if the line box is smaller than expected?

**Comment by litherum** [comment]
yes, agree with @fantasai
