### ISSUE TITLE
[css-text-decor] text-decoration level 4 refers to a non-existent value of text-underline-position

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#4017]
In the description of the `text-underline-offset` property at https://www.w3.org/TR/css-text-decor-4/#underline-offset, in the table describing the initial position of the underline, there is a reference to an `over` value of `text-underline-position`.

However, where `text-underline-position` is defined at https://www.w3.org/TR/css-text-decor-3/#text-underline-position-property, there is no such value; it lists only `auto | [ under || [ left | right ] ]`. So `over` doesn't exist (and `left` and `right` are unaccounted-for in the table mentioned above).

**Comment by fantasai** [comment]
Fixed.
