### ISSUE TITLE
[css-syntax] Tokenization rules don't allow parsing of CSS variables

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#4018]
Very simple one this. The tokenizer under section [4.3.1](https://drafts.csswg.org/css-syntax/#consume-token) doesn't allow a double hyphen to start an ident-like token, which means CSS variables wouldn't be parsed.

Needs changing from this:

> Otherwise, if the input stream starts with an identifier, reconsume the current input code point, consume an ident-like token, and return it.

to something like this:

> Otherwise, if the input stream starts with either an identifier, or a U+002D followed by an identifier, then reconsume the current input code point, consume an ident-like token, and return it.

**Comment by tabatkins** [comment]
"starts with an identifier" correctly returns true for `--foo`, right?

> **U+002D HYPHEN-MINUS** <br>
> If the second code point is a name-start code point or a U+002D HYPHEN-MINUS, or the second and third code points are a valid escape, return true. Otherwise, return false.

**Comment by faceless2** [comment]
Argh. Sorry Tab, I've wasted your time on this. Yes, [consume a name](https://drafts.csswg.org/css-syntax/#consume-name) does consume zero or more U+002D at the start. Really sorry, not sure how I missed that. I need to go and look through our parser code.
