### ISSUE TITLE
[css-text-decor] text-decoration level 4 clarification on text-underline-offset positive/negative lengths

### ISSUE THREAD

**Issue by charliemarlow** [w3c/csswg-drafts#4021]
For `text-underline-offset` at [https://drafts.csswg.org/css-text-decor-4/#underline-offset](https://drafts.csswg.org/css-text-decor-4/#underline-offset), it says that "Positive lengths represent inward distances; negative lengths outward". This seems to suggest that a positive length would move the underline up, intersecting with the text that it is underlining and eventually sitting "above" the text like an overline. A negative length, however, would travel "down" the page. Is this the correct way to interpret that section of the spec? 

In [Safari Technology Preview 70](https://webkit.org/blog/8496/release-notes-for-safari-technology-preview-70/), `text-underline-offset` has been implemented, but positive values move the text downwards on the page away from the underlined text. Negative values have the same effect as setting `text-underline-offset` to 0.

**Comment by emilio** [comment]
cc @litherum

**Comment by jfkthame** [comment]
Trying to think as an author, it seems more natural to me that a positive text-underline-offset would move the underline away from the baseline of the text (so downwards, in common horizontal-tb writing mode). That's what Safari Tech Preview does, but it's the opposite of what the spec currently says, as I understand it.

Given that AFAIK no-one else has implemented this yet, I'd suggest the language in the spec should be reversed so as to match Safari's behavior.

> Negative values have the same effect as setting text-underline-offset to 0.

Just FTR, this isn't what I see: in Safari Tech Preview, negative text-underline-offset moves the line up through the text, or eventually entirely above it. Which is what I'd expect, modulo the reversal of direction compared to the current spec draft.

**Comment by dbaron** [comment]
I'd note that I had experience in the distance past dealing with different OS APIs for underline offsets (the underline offset that comes out of the font metrics) having different signs.  So there's a historical precedent of inconsistency in this space.

**Comment by kojiishi** [comment]
> Given that AFAIK no-one else has implemented this yet, I'd suggest the language in the spec should be reversed so as to match Safari's behavior.

+1.

**Comment by jensimmons** [comment]
We just resolved on what this should do, and I believe we resolved the correct way (ie, what Authors want/expect). But since doing polls on Twitter is far too easy, I thought, heck, let's see what hundreds of random people think.... So here's a poll. It will likely confirm we did the right thing: https://twitter.com/jensimmons/status/1143945231152422914

**Comment by jensimmons** [comment]
>Rationale for 1: its more like `outline-offset` where a positive offset value pushes outwards. — https://twitter.com/dorebank/status/1143945887120596994

**Comment by dbaron** [comment]
Also note that #4059 was spun out of this discussion, covering whether there should be limits on how far `text-underline-offset` can go.

**Comment by fantasai** [comment]
This was fixed in 9d6d9fa419
