### ISSUE TITLE
[css-display] Add 'display:contents list-item' ?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4022]
https://drafts.csswg.org/css-display/#propdef-display
Given that a `display:contents` element can generate `::before/::after` boxes, it seems reasonable that it should also be able to generate a `::marker` box. The box would be forced to be `list-style-position:inside`, just like for `display:inline list-item`.

**Comment by tabatkins** [comment]
I mean, it *could*. But does it need to?

**Comment by astearns** [comment]
@tabatkins one of the use cases you pointed to for subgrid last week was the table of contents for specs. While that specific case doesn't use list markers I can definitely imagine a TOC situation that did. Wouldn't you expect the display:contents workaround to work pretty much the same as subgrid in that case?

**Comment by tabatkins** [comment]
Agenda+ to confirm that we're okay closing WONTFIX, just due to lack of use-case.

There's nothing *theoretically* wrong with this, it's just extra complexity without justification so far.
