### ISSUE TITLE
[css-fonts] <font> links incorrectly

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#4030]
In https://drafts.csswg.org/css-fonts-4/#absolute-size-mapping <font> links to SVG rather than HTML.

Discovered while working on https://github.com/whatwg/html/pull/4695.

**Comment by tabatkins** [comment]
Hm, that's because Bikeshed only sees that definition.

Looking in the HTML spec, it looks like all of the "legacy" elements are marked up as plain `dfn`, with no additional markup. Those'll all need `data-dfn-type=element` to expose them to Bikeshed properly.

**Comment by plinss** [comment]
Shepherd's spec parser has a heuristic to mark all the element `dfn`s in the HTML as elements without the `data-dfn-type` (they all have anchors matching the pattern 'the-&lt;name&gt;-element'). I think the issue here is that HTML doesn't define the `font` element any more...

**Comment by tabatkins** [comment]
It does (<https://html.spec.whatwg.org/multipage/obsolete.html#font>), it's just off in a different section and doesn't have any of the indicators of being an element dfn.

**Comment by annevk** [comment]
Okay, I'll create a PR and you can review it to see if it fits the bill.

**Comment by annevk** [comment]
https://github.com/whatwg/html/pull/4701

**Comment by svgeesus** [comment]
(also I guess it links to [the `font` element in SVG 1.1](https://www.w3.org/TR/SVG11/fonts.html#FontElement) because `font` was removed in SVG2.

**Comment by plinss** [comment]
Ok, bikeshed now sees the font element in HTML, but <font> is still linking to SVG here. Bikeshed is producing the warning:

> LINK ERROR: Multiple possible 'font' element refs.
Arbitrarily chose https://www.w3.org/TR/SVG11/fonts.html#FontElement
To auto-select one of the following refs, insert one of these lines into a &lt;pre class=link-defaults&gt; block:
spec:html; type:element; text:font
spec:svg; type:element; text:font
&lt;{font}&gt;
