### ISSUE TITLE
[css-multicol] column-fill should behave more similarly in paginated and continuous contexts

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#4036]
Following the fix for #3224, the behavior of `column-fill` appears to be unnecessarily different between paginated and continuous contexts.

I would suggest fixing this asymmetry by changing the sentence that begins:

> In continuous contexts, this property will only be consulted if the length of columns has been constrained in the block dimension, ...

to instead begin:

> In continuous contexts, and for the last fragment in fragmented contexts, this property will only be consulted if the length of columns has been constrained in the block dimension, ...

This change will make the behavior for the last fragment in a fragmented context match the behavior in a continuous context, which I think is a good thing.  This makes layouts more consistent when they're transferred between fragmented and unfragmented contexts; e.g., a web page changes less as a result of being printed.

<del>In other words, what I'm suggesting is that balancing would be determined by this table (where yes/no is whether to balance), with the * indicating the cases I propose to change:</del>

| <del>value</del> | <del>length</del> | <del>fragmented context, not last fragment</del> | <del>fragmented context, last fragment</del> | <del>continuous context</del> |
| --- | --- | --- | --- | --- |
| <del>`auto`</del> | <del>any</del> | <del>no</del> | <del>no</del> | <del>no</del> |
| <del>`balance`</del> | <del>constrained</del> | <del>no</del> | <del>yes</del> | <del>yes</del> |
| <del>`balance`</del> | <del>unconstrained</del> | <del>no</del> | <del>no*</del> | <del>no</del> |
| <del>`balance-all`</del> | <del>constrained</del> | <del>yes</del> | <del>yes</del> | <del>yes</del> |
| <del>`balance-all`</del> | <del>unconstrained</del> | <del>yes</del> | <del>no*</del> | <del>no</del> |

**Comment by mstensho** [comment]
Your suggestion seems fine.

However, I have a hard time understanding how that would result in such a table.

The first row: column-fill:auto should force balancing in a continuous context, unless block-size is constrained. So you probably need to split the first row in two, one for constrained length (no balancing no matter what), and one for unconstrained length (balance in continuous media). That would represent the reality of today.

Furthermore, balance-all, unconstrained block-size, and last fragmentainer (last row, second-to-last cell): This one should say "yes", shouldn't it? We definitely want to balance if balance-all is specified. Always. So the last cell in the last row should also say "yes".

The "no*" in the third row doesn't seem right, either. If height is unconstrained, we should balance the last fragmentainer. I think you want to say "yes*".

I'm imagining this:
If column-fill is balance-all: Always balance, everywhere.
If column-fill is balance: Always balance, except when participating in an outer fragmentation context and it is not the last fragmentainer.
If column-fill is auto: Never balance, unless block-size is unconstrained. Even if block size is unconstrained, do not balance if we're participating in an outer fragmentation context and it is not the last fragmentainer.

**Comment by dbaron** [comment]
Yeah, you're right, I had the table wrong; I was working too quickly and got the defaults backwards.  I guess the table should be:

| value | length | fragmented context, not last fragment | fragmented context, last fragment | continuous context |
| --- | --- | --- | --- | --- |
| `auto` | constrained | no | no | no |
| `auto` | unconstrained | no | yes* | yes |
| `balance` | any | no | yes | yes |
| `balance-all` | any | yes | yes | yes |

If you agree this is correct, then maybe instead of the wording change I propose, it would be better to move that extra paragraph into the definition of `auto`.

**Comment by mstensho** [comment]
> Yeah, you're right, I had the table wrong; I was working too quickly and got the defaults backwards. I guess the table should be:

Yes, that looks right to me!

> If you agree this is correct, then maybe instead of only making the wording change I propose, it would be better to also move that extra paragraph into the definition of `auto` and reword appropriately.

That's also a very good idea.

**Comment by dbaron** [comment]
I also just wrote [some examples](https://dbaron.org/css/test/2019/csswg-drafts-issue-4036) to look at browser behavior.  The examples aren't even useful on Gecko or WebKit due to other bugs; it appears that Chromium would need to change behavior if we make this change.

**Comment by mstensho** [comment]
Yes, Chromium still doesn't consider min-height or max-height when determining constrainedness. There's https://bugs.chromium.org/p/chromium/issues/detail?id=967329 , which was reported for the max-height case. I'll change that bug to also cover the min-height case.

Also note that Chromium doesn't recognize the "balance-all" value at all. That's https://bugs.chromium.org/p/chromium/issues/detail?id=909596

Thanks.

**Comment by frivoal** [comment]
I sympathize with @dbaron 's request for a cleaner system and symmetry between the continuous and fragmented context.

However, there's a use both for balancing and not balancing the last page even when the height is not constrained. We could change the behavior as suggested and add the missing one later as an extra keyword, but multicol in fragmented media is routinely used in print and pdf formatters, and they implement the spec as it currently is, balancing the columns on the last page even with no height constrain when `column-fill` is `balance`, and not balancing when `column-fill` is `auto`. Given that, this class of user agents are likely to have a compat requirement to keep this behavior, and won't change. I think it would be very unfortunate to fork the language, and for print formatters and browsers to have different behavior on multi-column.

(I have tested Prince and PDFreactor and they are interoperable. Vivliostyle has some bugs, but for that aspect it is interoperable as well.)

All in all, I think we should reject the proposal.

**Comment by dbaron** [comment]
A few points I'd like to highlight from the discussion in the teleconference yesterday:
* @frivoal raised the issue that changing this as I initially proposed would be inconsistent with the behavior of print formatters
* #3224 was originally resolving an issue where today's browsers behave differently (Gecko on one side, Blink and WebKit (and EdgeHTML) on the other side), but we weren't aware (I think) of compatibility problems caused by that difference
* my concern in this issue was inconsistency between formatting of multicol on screen and when printed; users printing from web browsers expect the printing to produce something generally similar to what they see on screen (and the developers often haven't considered or tested printing behavior).  My underlying principle is that the last fragment in a paginated context should behave like the behavior in a continuous context; this is particularly important because the *last* fragment is often the *only* fragment, and it is bad for something that is not actually fragmented to behave in a substantially different way on paper.

So the option that seemed the most attractive in the teleconference was to revert the change in #3224 and ask Blink and WebKit to to change their behavior.

At the same time... we should probably also clarify what the `height: auto` behavior is in this case.  What do browsers do, and what do print formatters do?

(I think reverting the decision also avoids having to figure out which cases where the height is influenced by the flex or grid algorithms count as a constrained height and which ones don't.)

**Comment by dbaron** [comment]
To be extra clear:  I'd like to get feedback from Blink and WebKit implementors about the previous comment, and whether they're willing to implement it.

**Comment by astearns** [comment]
@mstensho @hober Any comment on this so we can make progress?

**Comment by mstensho** [comment]
You're asking if I'm okay with #3224 being reverted and willing to implement it in Blink?
Sure, but then we won't have to clarify what column-fill:auto + height:auto means, do we? The spec, prior to #3224 said that column-fill:auto means that we should never balance (except before spanners), didn't it?

**Comment by rachelandrew** [comment]
Are we in a position to progress on this? I'd like to republish the WD soon as there have been a lot of changes, but one of those is the issue we're considering reverting. So it would be good to make that decision first.
