### ISSUE TITLE
[css-images] Computed gradient colors

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#4042]
Suppose an author sets various `<image>` properties to gradients with color keywords, e.g. `linear-gradient(45deg, blue, orange)` . Should `getComputedStyle()` results show gradients with color keywords or `rgb` functions?

Firefox gives `rgb` functions. Blink, Edge 18 and Safari give color keywords.
https://jsfiddle.net/ericwilligers/qzp4wy03/

Should we change the "Computed value" text for [shape-outside](https://drafts.csswg.org/css-shapes-1/#shape-outside-property)

> ..., the `<image>` with its URI made absolute, otherwise as specified.

=>

> ..., the `<image>` with its URI made absolute and colors computed, otherwise as specified.

[background-image](https://drafts.csswg.org/css-backgrounds/#background-image) and [border-image-source](https://drafts.csswg.org/css-backgrounds/#border-image-source) would need a similar change if they referenced the CSS Images 3 definition of `<image>`, but they currently don't.

No change would be needed for [list-style-image](https://drafts.csswg.org/css-lists-3/#propdef-list-style-image)

> computed value of the `<image>`, or `none`

**Comment by AmeliaBR** [comment]
I would expect the color format to be serialized in the same form as `<color>` types in other properties.

Rather than define this every time a property includes an `<image>` type, it would be nice if we could define the computed/serialized form for a gradient function itself.  And then use the "computed value of the `<image>`" wording for properties.

**Comment by tabatkins** [comment]
Yeah, we just need a definition for "computed `<image>`" that can be reused, it's silly to copy boilerplate like this that gets out of sync.

**Comment by ewilligers** [comment]
This also affects lengths (radial-gradient, conic-gradient). Firefox and Edge make lengths absolute, Blink and Safari do not (e.g. getComputedStyle() gives results with ex).

**Comment by AmeliaBR** [comment]
Agenda+ to get a resolution, unless @ewilligers would rather we wait until the next APAC-friendly meeting?

**Comment by ewilligers** [comment]
No need to wait. I expect there is simply a browser bug in Blink, Edge 18 and Safari. There appears to be consensus about adding computed image.
