### ISSUE TITLE
[css-color-4] Hyphens in colorspaces

### ISSUE THREAD

**Issue by jstblck** [w3c/csswg-drafts#4056]
Since the modified version of DCI-P3 in CSS 4 is the same as the version already in use by Apple, would it not make more sense to use the same name, ie `display-p3` instead of `image-p3`?

[From CSS 4](https://www.w3.org/TR/css-color-4/#valdef-color-image-p3):
> It uses the same primary chromaticities as DCI-P3, but with a D65 whitepoint and the same transfer curve as sRGB.

[From Apple](https://developer.apple.com/documentation/coregraphics/cgcolorspace/1408916-displayp3):
> This color space uses the DCI P3 primaries, a D65 white point, and the same gamma curve as the sRGB color space.

'Display P3' is also used on some forums and in places on Wikipedia with the above meaning.

Also, for consistency, should Adobe RGB (1998) be named `adobe-rgb-98` or preferably just `adobe-rgb`, and ProPhoto RGB named `prophoto-rgb`?

This would make the naming scheme the common name (but with a hyphen replacing any spaces) with, if necessary, the version (such as the year for Adobe RGB) as a hyphen-separated suffix.

**Comment by svgeesus** [comment]
Thanks for your comments.

The P3 colorspace was introduced into CSS Color at the request of Apple. We originally called it DCI P3 because that was what we thought it was. As more information emerged (different whitepoint, different viewing conditions and transfer curve) the naming was discussed in the CSS WG. image-p3 is the name that emerged as the favourite. Representatives from Apple were involved in those discussions.

`Adobe RGB (1998)` is the official, trademarked, name of the Adobe colorspace. For licensing, trademark and copyright reasons, that phrase can't be used to describe the colorspace used in CSS. (I know). Nor can we use the phrase `Adobe` which would be a registered trademark infringement. 

By the way there were several variants of the Adobe colorspace, so the 1998 specifier is an important part. This is why CSS has a colorspace called `a98rgb`.

It might indeed be more consistent to write `a98-rgb` and also `prophoto-rgb` which would also be easier to read.

**Comment by grorg** [comment]
FWIW, I prefer the name `display-p3`

**Comment by svgeesus** [comment]
Well, ok then! Lets get the CSSWG to change that,

**Comment by astearns** [comment]
We switched from display-p3 to image-p3 in 2016, but I can’t actually find the discussion behind making the change https://github.com/w3c/csswg-drafts/pull/557/commits/619c1fd210c3a9b1f580e735cf57217d81a6ffc3

**Comment by jstblck** [comment]
Thank you for your reply @svgeesus.

> The P3 colorspace was introduced into CSS Color at the request of Apple. We originally called it DCI P3 because that was what we thought it was. As more information emerged (different whitepoint, different viewing conditions and transfer curve) the naming was discussed in the CSS WG. image-p3 is the name that emerged as the favourite. Representatives from Apple were involved in those discussions.

I'm suprised that Apple didn't want it to be called `display-p3` instead of `image-p3`.

> `Adobe RGB (1998)` is the official, trademarked, name of the Adobe colorspace. For licensing, trademark and copyright reasons, that phrase can't be used to describe the colorspace used in CSS. (I know). Nor can we use the phrase `Adobe` which would be a registered trademark infringement.
> 
> By the way there were several variants of the Adobe colorspace, so the 1998 specifier is an important part. This is why CSS has a colorspace called `a98rgb`.
> 
> It might indeed be more consistent to write `a98-rgb` and also `prophoto-rgb` which would also be easier to read.

It's a shame `adobe` can't be used. Would `a-rgb-98` be better? That seems more consistent but also easy to read and wright.

I just think the built-in profiles need a naming scheme. Ideally, one that's consistent, easy-to-parse, and scaleable.

**Comment by svgeesus** [comment]
In terms of consistent hyphenation: everyone writes `srgb` (well, they write `sRGB`) and `s-rgb` would be odd.

 On the other hand `prophotorgb` is a bit long and hard to read, `prophoto-rgb` might be an improvement. And if we did that, then `a98-rgb` would also be reasonable.

Leaving issue open for further discussion on those.

**Comment by svgeesus** [comment]
> I'm suprised Apple didn't want it to be called display-p3 instead of image-p3.

We were unable to find an actual resolution to use `image-p3` and indeed, on the call today Apple expressed a preference for `display-p3` as indeed did everyone else who had an opinion. So I just made that change.

**Comment by svgeesus** [comment]
I should also add the [Apple definition of DisplayP3](https://developer.apple.com/documentation/coregraphics/cgcolorspace/1408916-displayp3) to the [spec ref database](https://github.com/tobie/specref) and then add that reference to CSS Color 4.

**Comment by svgeesus** [comment]
I added the AdobeRGB (1998) reference: https://github.com/w3c/csswg-drafts/commit/e2dfded4284fa84acef31ff7ad4c591715c0ee6f and https://github.com/tobie/specref/commit/99a7d7dd2d12e278c41f24b521207b74323787a1

**Comment by Crissov** [comment]
sRGB, ppRGB, aRGB?

**Comment by jstblck** [comment]
I'm glad that `image-p3` will now be called `display-p3`.

> In terms of consistent hyphenation: everyone writes `srgb` (well, they write `sRGB`) and `s-rgb` would be odd.

I don't think sRGB should be named `s-rgb`.

The current built-in profiles are: sRGB, Display P3, Adobe RGB (1998), ProPhoto RGB, and Rec 2020. These are the common names.

I suggest that we first replace the spaces with hyphens (eg `srgb`, `display-p3`, `adobe-rgb` (1998), `prophoto-rgb`, and `rec-2020`).

Then if necessary, I suggest we add a hyphen and the version to the end (eg `adobe-rgb-1998` or `adobe-rgb-98` [I'm not sure which]). Currently, this is only necessary for Adobe RGB.

Also if necessary, I suggest we shorten or replace trademarked names (eg `adobe-rgb-1998`/`adobe-rgb-98` could be shorted to `a-rgb-1998`/`a-rgb-98`). Again, this is only necessary for Adobe RGB currently.

The naming scheme would then be the common name (unless trademarked and with hyphens instead of spaces), and if necessary, a hyphen and the version added to the end (such as the year for Adobe RGB).

PS: Is it a policy of the W3C that its standard don't include trademarks, or is it that Adobe would object to us using its name?

[According to Adobe](https://www.adobe.com/digitalimag/adobergb.html):

>Legal note regarding color-space naming: Only the Adobe RGB (1998) ICC profile created by Adobe Systems Incorporated can accurately be referred to as "Adobe RGB (1998)." ICC profiles created by other vendors, even if they conform to the color image encoding described in the Adobe RGB (1998) color image encoding document, cannot be referred to as "Adobe RGB (1998)." If vendors choose to create their own profile according to this specification, and they want to indicate to their customers that this profile was written in accordance with Adobe's specification, then an alternate phrasing is required, such as "compatible with Adobe RGB (1998)."

Does that mean that Adobe would allow something like `adobe-rgb-1998-compatible`? I'm not suggesting we use that, but maybe they would allow it to be shortened to `adobe-rgb-1998`/`adobe-rgb-98`?

**Comment by tabatkins** [comment]
Summarizing the proposal:

* Add hyphens in the obvious places to make 'prophoto-rgb' and 'rec-2020' 
(consistent with 'display-p3')
* Add hyphens to 'a98rgb' in one of the following ways:
	* a-98-rgb
	* a-rgb-98
	* a-rgb-1998
	* adobe-rgb-98
	* adobe-rgb-1998

**Comment by svgeesus** [comment]
Or a98-rgb? (consistent with prophoto-rgb rather than pro-photo-rgb)?

> PS: Is it a policy of the W3C that its standard don't include trademarks, or is it that Adobe would object to us using its name?

Both :)

**Comment by svgeesus** [comment]
Changed to `display-p3`, `prophoto-rgb`,  `a98-rgb` and `rec-2020`

**Comment by tabatkins** [comment]
This works for me. You still want telcon discussion, Chris, or are you fine with this?

**Comment by Crissov** [comment]
I know, “Rec. 2020” is common jargon for ITU-R Recommendation BT.2020, and thus `rec-2020` does make sense, but wouldnʼt `bt-2020` or `itu-2020` work just as well while being a bit more specific? 🤷‍♂️

**Comment by tabatkins** [comment]
We did briefly chat about this on telcon, just to confirm that it was indeed sufficiently addressed here in the thread and didn't need discussion. ^_^

@jstblck, can you confirm you're happy with the names Chris changed to?

**Comment by karip** [comment]
The rec-2020 name isn't anymore matching the rec2020 name in [color gamut media query](https://www.w3.org/TR/mediaqueries-4/#color-gamut). It would be nice if the same name is used in both specs so it is easier to remember.

(on the other hand, media queries uses p3 instead of display-p3, so maybe this isn't a huge issue.)

**Comment by AmeliaBR** [comment]
@karip, good point, maybe open a separate issue, since it's less clear which set of tokens should be changed (these ones or the media query ones).

But we might have a compat issue now with changing the media query — it's [supported in Chromium and WebKit](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/color-gamut#Browser_compatibility).

**Comment by jstblck** [comment]
> @jstblck, can you confirm you're happy with the names Chris changed to?

Sorry for the delayed response. I'm happy with the changes.

**Comment by svgeesus** [comment]
@karip wrote:
> The rec-2020 name isn't anymore matching the rec2020 name in color gamut media query. It would be nice if the same name is used in both specs so it is easier to remember.

> (on the other hand, media queries uses p3 instead of display-p3, so maybe this isn't a huge issue.)

Both tre, and I think not a problem. Color 4 uses the terms rec-2020 and display-p3 to mean specific, objectively quantifiable things. MQ uses them to mean losse, subjective things - in effect MQ has three buckets to describe the color gamut:

- barely good enough (sRGB) or below
- wideish, but not super wide (p3) 
- super wide (rec2020), mainly for upwards compatibility.

A display which covers 100% of "Adobe RGB (1998)" but only covers most of Display-p3, for example, would still fall into the "wideish gamut" bucket and match a p3 query.
