### ISSUE TITLE
[css-grid][css-flexbox] Blockification section should use the computed value, not the box of the element

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4065]
Right now https://drafts.csswg.org/css-grid/#grid-item-display says:

> The display value of a grid item is blockified: if the specified display of an in-flow child of an element generating a grid container is an inline-level value, it computes to its block-level equivalent. (See CSS2.1§9.7 [CSS21] and CSS Display [CSS3-DISPLAY] for details on this type of display value conversion.)

Similarly https://drafts.csswg.org/css-flexbox/#flex-items says:

> The display value of a flex item is blockified: if the specified display of an in-flow child of an element generating a flex container is an inline-level value, it computes to its block-level equivalent. (See CSS2.1§9.7 [CSS21] and CSS Display [CSS3-DISPLAY] for details on this type of display value conversion.)

As @Loirooriol pointed out in https://bugzilla.mozilla.org/show_bug.cgi?id=1562039, this doesn't match browsers, and browsers use the computed display value of the closest non-`display: contents` ancestor, even if the element doesn't become a flex or grid container (due to it being replaced for example, or it being in a `display: none` subtree).

I think the spec in this case should match browsers in this case, in order to not make style of children depend on layout box construction. This also matches how the [CSS 2 fixups](https://drafts.csswg.org/css2/visuren.html#dis-pos-flo) work. The root element is blockified even if it's a replaced element or wouldn't generate an inline-level box otherwise.

**Comment by Loirooriol** [comment]
Also for Houdini Layout with `childDisplay = "block"`. https://drafts.css-houdini.org/css-layout-api/#layout-api-box-tree

**Comment by tabatkins** [comment]
Agenda+ for WG resolution on the change. Before the call, do these edits work for you, @emilio?

**Comment by Loirooriol** [comment]
> If the computed display value of an **element**’s nearest ancestor **element**

Are pseudo-elements considered to be elements? If you use `display: grid` on an element, its `::before` is blockified. And once `display: list-item grid` is allowed, and you use it on a `::before`, I guess `::before::marker` will be blockified too.

**Comment by tabatkins** [comment]
Yes, tree-abiding pseudo-elements live in the element tree.

**Comment by emilio** [comment]
Yes, the edits work for me.
