### ISSUE TITLE
[selectors] The grammar of id-selector

### ISSUE THREAD

**Issue by esdoppio** [w3c/csswg-drafts#407]
In the [grammar](https://drafts.csswg.org/selectors-4/#grammar) section,

> `<id-selector> = <hash-token>`

with a note at the bottom:

> In &lt;id-selector>, the &lt;hash-token>’s value must be an identifier.

Apart from that the note is really easy to be missed. Why not just

```
<id-selector> = '#' <ident-token>
```

**Comment by fantasai** [comment]
I believe the reason is that something that looks like '#' `<ident-token>` will be tokenized as a `<hash-token>` by the tokenizer before we get to the parsing stage here. But @tabatkins would know for sure.

**Comment by therealglazou** [comment]
> I believe the reason is that something that looks like '#' <ident-token> will be tokenized as a <hash-token> by the tokenizer before we get to the parsing stage here

Precisely.

**Comment by tabatkins** [comment]
Correct.
