### ISSUE TITLE
[css-transforms-1] 2D rotations are not actually defined in a clear way

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#4077]
https://drafts.csswg.org/css-transforms-1/#RotateDefined says:

>  A 2D rotation with the parameter alpha is equivalent to a 3D rotation with vector [0,0,1] and parameter alpha. 

Presumably this is meaning to reference the definition at https://drafts.csswg.org/css-transforms-2/#Rotate3dDefined but that's not at all clear from the text.  This definition should have a link to css-transforms-2.

**Comment by dirkschulze** [comment]
I think we simply removed the 3D part and missed to update the 2D transform descriptions.

**Comment by dirkschulze** [comment]
@bzbarsky I restored the original text and images. CSS Transforms 1 is not supposed to reference level 2. (Since the latter builds up on top of the former.)

**Comment by bzbarsky** [comment]
Hmm.  I guess that works, through if x = y = 0 and z = 1, the matrix can be written _much_ more simply...
