### ISSUE TITLE
[css-syntax] 4.3.11. Consume a name

### ISSUE THREAD

**Issue by burlog** [w3c/csswg-drafts#408]
Hi guys,

I want to ask about one strange part of "consume a name" algorithm:

https://drafts.csswg.org/css-syntax/#consume-name

If the input is "\0075\0072\006C\0028" this algorithm returns string "url(". The left parenthenses is part of name because the "escape" branch doesn't check that the returned code point can be "a name code point". Is it desired behaviour or is it a bug?

Thanks.

**Comment by SimonSapin** [comment]
Yes, allowing code points that normally can’t be in names/identifiers is the point of escaping.
