### ISSUE TITLE
[css-syntax] Serialization rules need to account for '%'

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4088]
https://drafts.csswg.org/css-syntax/#serialization has a nice table after:

>  For any consecutive pair of tokens, if the first token shows up in the row headings of the following table, and the second token shows up in the column headings, and there’s a ✗ in the cell denoted by the intersection of the chosen row and column, the pair of tokens must be serialized with a comment between them. 

That table is not correct, since it doesn't account for the `%` delimiter (which note, is different from a `percentage` token). Firefox implements this table to the letter which means something like the following incorrectly works in Firefox:

`data:text/html,<div style="--x: 20; width: var(--x)%; height: 50px; background: green"></div>`

cc @simonsapin @tabatkins

**Comment by tabatkins** [comment]
Tested in https://github.com/web-platform-tests/wpt/commit/dacb51937397fd06727727614e255f223e7cb9f3

**Comment by emilio** [comment]
Oh, awesome, thank you! I added a test for the Firefox bug in https://github.com/web-platform-tests/wpt/commit/153ad37b47b49489c467ac70d665b603cc29a2b5 too, but your extensive test-cases are more than appreciated ^.^

**Comment by emilio** [comment]
I filed https://bugs.webkit.org/show_bug.cgi?id=199646 / https://bugs.chromium.org/p/chromium/issues/detail?id=982476, since it seems that WebKit and Blink fail all the tests :(
