### ISSUE TITLE
[cssom-view] Algorithm of `Element.offsetParent`

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#409]
The current spec says `offsetParent` should return an ancestor if
> The computed value of the `position` property is not `static`.

It doesn't seem to me it is quite useful to query an ancestor who has some specific `position` value. Isn't it supposed to return the first ancestor which is a containing block of absolutely-positioned descendants?

**Comment by upsuper** [comment]
cc @zcorpan

**Comment by zcorpan** [comment]
Do browsers do something differently for this?

**Comment by upsuper** [comment]
Firefox currently returns the containing block of absolutely-positioned descendant, Chrome seems to follow what the spec says.

**Comment by zcorpan** [comment]
Thanks. Do you have a test case at hand so we can also check WebKit and Edge?

**Comment by upsuper** [comment]
No at this moment, but I can create one later today if needed.

**Comment by zcorpan** [comment]
Per the definition at https://drafts.csswg.org/css-position/#containing-block "the containing block is established by the nearest ancestor with a position other than static" (or ICB, in which case `offsetParent` returns `body`). So that aspect is the same, or am I missing something?

**Comment by upsuper** [comment]
`transform` with value other than `none` also creates a containing block, so does `will-change` with value `position` or `transform`.

Actually, I'd argue that a fixed-positioned element caught by an ancestor with `transform` should also has non-null `offsetParent`.

**Comment by upsuper** [comment]
This is a testcase with which we can compare behavior of different engines: https://bug1294667.bmoattachments.org/attachment.cgi?id=8781553

It seems WebKit always returns `<body>` which is useless anyway. Blink returns `#outer` only when `position: something`. Gecko returns `#outer` for all cases which create a containing block.

**Comment by upsuper** [comment]
And Edge always returns `<body>` like WebKit.

**Comment by zcorpan** [comment]
I discussed this with @rune-opera and @mstensho-opera and they said they think the Gecko behavior makes most sense. I tend to agree. We can make the spec say "first ancestor which is a containing block of absolutely-positioned descendants" instead.  But would be good to hear from WebKit and Edge people also. @hober, @atanassov ?

**Comment by smfr** [comment]
WebKit's code is here: https://trac.webkit.org/browser/trunk/Source/WebCore/rendering/RenderObject.cpp#L1869
We walk the parent chain looking for things that are positioned, with special casing for tables and things with zoom.

**Comment by upsuper** [comment]
@smfr Looking at the code, I think it should mostly match Blink's behavior. Not sure why the testcase shows something different... Anyway, what do you think about the proposal of changing the algorithm here?

**Comment by FremyCompany** [comment]
Here is the behavior I see in Edge:
```
outer.style	inner.offsetParent
/* empty */	body
position: relative	outer
transform: translate(0)	body
will-change: position	body
will-change: transform	body
```

**Comment by FremyCompany** [comment]
Sorry, I retract what I just said, the test case isn't working properly for us because we do not support setting the style property as a string, we just don't throw when you do it but it has no effect. In addition, we do not support ```will-change```.

Here is what we actually return for cases we support:
```
/* empty */
body

position: relative
outer

transform: translate(0)
outer
```

https://jsfiddle.net/nqgL7L2e/

**Comment by kojiishi** [comment]
Blink code [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/layout/LayoutObject.cpp?sq=package:chromium&dr=CSs&rcl=1472109603&l=2893), FYI.

**Comment by zcorpan** [comment]
Filed bugs:
https://bugs.webkit.org/show_bug.cgi?id=161788
https://bugs.chromium.org/p/chromium/issues/detail?id=645397
