### ISSUE TITLE
[css-fonts] font-variant-numeric should not have titling-caps

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#4093]
It appears the CSS Fonts 3 grammar
`normal | [ <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero ]`
was accidentally changed when it was brought into CSS Font 4
`normal | [ <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero ] titling-caps`
The examples do not have titling-caps, and browsers do not expect titling-caps.

The relevant change is https://github.com/w3c/csswg-drafts/commit/b5beab956

**Comment by svgeesus** [comment]
Yeah, that makes no sense. _Mea culpa_.
