### ISSUE TITLE
[css-fonts-3] http/https error in cross-origin example in 4.7

### ISSUE THREAD

**Issue by bert-github** [w3c/csswg-drafts#4098]
The example of the effect of CORS in [section 4.9 ‘Font fetching requirements’](https://www.w3.org/TR/css-fonts-3/#font-fetching-requirements) says that the font specified with `src: url(https://example.com/fonts/simple.woff)` fails to load, due to having a different scheme than the document. However, the scheme, ‘https’, is actually the same.

Probably the example was meant to have ‘http’ instead of ‘https’: `src: url(http://example.com/fonts/simple.woff)`

**Comment by nicktrav** [comment]
Came here to report the exact same thing!

**Comment by cadonau** [comment]
Hello everyone,
I noticed the same thing regarding the scheme.
I didn't think a reference of the commit to my fork (542ad1d9855c0295f24e56b3abff204a536f91af) would already appear, here.
Would it be okay to open a pull request?

**Comment by svgeesus** [comment]
Also [added to Fonts 3 errata](https://www.w3.org/Style/2018/REC-css-fonts-3-20180920-errata.html)

**Comment by cadonau** [comment]
@svgeesus Thank you for fixing it properly!
