### ISSUE TITLE
[css-pseudo-4] painting of the cursor and the caret with highlight pseudos

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4100]
https://drafts.csswg.org/css-pseudo-4/#highlight-styling says that highlight pseudos can take the `caret-color` and `cursor` properties, but https://drafts.csswg.org/css-pseudo-4/#highlight-painting doesn't say how they're rendered.

Possibilities:
* the topmost one wins
* the topmost non `auto` wins

**Comment by fantasai** [comment]
Related question: is there a use case for this and any implementation interest? Because if not I'm happy to defer this question and the feature entirely to L5. :)
