### ISSUE TITLE
[css-shapes] Accept percentage for shape-image-threshold

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#4102]
The current spec of [`shape-image-threshold`](https://drafts.csswg.org/css-shapes/#shape-image-threshold-property) uses `<number>` as its value. However, it seems this property is also kind of alpha value, and #3342 suggests we add `<percentage>` for opacity related properties. Therefore, I just wonder should we update `shape-image-threshold` to accept `<alpha-value>`?

cc @ericwilligers @emilio

**Comment by ewilligers** [comment]
No objections.
