### ISSUE TITLE
[css-scroll-snap-1] expected behavior when scrolling past a container's last visible element

### ISSUE THREAD

**Issue by justingrant** [w3c/csswg-drafts#4111]
What's expected behavior when scroll snap is enabled and the user tries to scroll past the last snap position?  Example: https://codepen.io/anon/pen/orOmeP.  I'm asking because: 
* WebKit (Mac Safari, iOS any) will scroll to the end, leaving nothing visible in the viewport.
* Blink (desktop Chrome) will refuse to scroll past the last visible element.

Which is correct?  Or is this behavior currently unspecified?

FWIW, the current WebKit behavior causes a race condition that [breaks](https://github.com/bvaughn/react-window/issues/290) current "virtual scrolling" implementations like Facebook's [react-window](https://github.com/bvaughn/react-window) that use JavaScript to JIT add/move absolutely-positioned elements in an otherwise-empty, very long container to simulate scrolling through a long list. Safari will scroll to the end of the content before the virtual-scrolling script has a chance to move elements to the user's new scroll position.  Desktop Chrome doesn't have this problem.

If this behavior isn't specified today, then I'd suggest adopting the Chrome behavior as default in the standard. If it is specified, then is there any standardized way for infinite-scroll implementations to get the Chrome behavior?

**Comment by jonjohnjohnson** [comment]
Blink - https://bugs.chromium.org/p/chromium/issues/detail?id=953979
Gecko - https://bugzilla.mozilla.org/show_bug.cgi?id=1545316

IMHO the start/end scrolling boundaries of a scroll container should implicitly create snap boundaries so that users can scroll back to the same position/boundary a scroll container originally loads in against.

**Comment by jonjohnjohnson** [comment]
Oh wait, this is actually a dup of an issue, https://github.com/w3c/csswg-drafts/issues/4037, that I filed last month 😆

**Comment by justingrant** [comment]
Hi @jonjohnjohnson - #4037 definitely looks like the same issue. I'll close this issue and ~argue~ discuss with you over there. ;-)
