### ISSUE TITLE
[css-inline] dominant-baseline initial value "normal" not mentioned anywhere else

### ISSUE THREAD

**Issue by heycam** [w3c/csswg-drafts#4115]
https://drafts.csswg.org/css-inline-3/#dominant-baseline-property

The initial value `normal` isn't listed in the allowed values for the property.  Is `auto` the intended initial value?  (The css/css-inline/inheritance.html WPT tests for this `normal` value.)

**Comment by ewilligers** [comment]
Each browsers has initial value `auto`. We should change the spec and the test.

https://wpt.fyi/results/css/css-inline/inheritance.html?label=master&label=experimental

**Comment by ewilligers** [comment]
@fantasai Was this a typo when bringing the property across from SVG in https://github.com/w3c/csswg-drafts/commit/107993abb5a370cb1fb7d343a2bb93c4d4cc3135 ?

**Comment by fantasai** [comment]
@ewilligers Yes, I think so. I'll fix it. :)
