### ISSUE TITLE
[css-animations-1] Figure 1 from example 4 is missing

### ISSUE THREAD

**Issue by rillig** [w3c/csswg-drafts#4119]
https://www.w3.org/TR/2018/WD-css-animations-1-20181011/#example-10d90bd9 looks like this:

![image](https://user-images.githubusercontent.com/3233724/61319828-5c1b2b80-a808-11e9-987b-f71047e4721c.png)

Figure 1 is not visible. This is because the HTTP request for `./animation1.png` generates a 404. The image is present in the GitHub repository though.

**Comment by birtles** [comment]
I guess someone forgot to include that file when they published the last WD. It's there in [the ED](https://drafts.csswg.org/css-animations/#example-10d90bd9).

@svgeesus Do you know if someone on the publications team can add `animation1.png` without having to republish?

**Comment by svgeesus** [comment]
Yes, it was missing. There was just `Overview.html` and `default.css` in there. I added the missing file from the ED.
