### ISSUE TITLE
[css-syntax-3] Input stream processing can calculate wrong encoding 

### ISSUE THREAD

**Issue by dd8** [w3c/csswg-drafts#4126]
There's a difference between the encoding calculated by the css-syntax-3 spec and the CSS 2.1/2.2 spec, demonstrated by this file:
http://test.csswg.org/suites/css2.1/20110323/html4/support/at-charset-001.css

It's served as Content-Type: text/css; charset=shift_jis. It also starts with a Shift_JIS byte sequence that happens to match the UTF-8 BOM (great test case)

ef bb bf 2e e5 b9 b3 e5 92 8c 0d 0a 7b 0d 0a 20 |............{.. |

CSS 2.1/2.2 specifies that Content-Type wins over any BOM:
https://drafts.csswg.org/css2/syndata.html#charset

css-syntax-3 uses the 'Decode' algorithm and says the decode algorithm gives precedence to a byte order mark (BOM), and only uses the fallback when none is found.
https://drafts.csswg.org/css-syntax/#input-byte-stream

This CSS 2.x algorithm gets the correct encoding for the test file (Shift_JIS) but the CSS 3 algorithm gets the wrong encoding (UTF-8). Chrome and Firefox both seem to use the 2.x method of calculating encoding for CSS.

FWIW I think the 'Decode' algorithm works well with HTML (and XML) because they're most likely to begin with `<!DOCTYPE` `<!--comment` `<html` or whitespace so can't accidentally match the BOM with an ASCII compatible encoding. I think 'Decode' works less well for CSS which can start with any non-ASCII code points as part of a CSS selector.

**Comment by tabatkins** [comment]
There's actually many differences between the Syntax and 2.1 handlings of encodings! Generally, Syntax no longer goes out of its way to support non-ASCII-compatible encodings; more specifically, it favors using UTF-8, the modern web's encoding.

As such, I don't consider these divergences to be errors per se; many corner cases changed between 2.1 and Syntax. In particular, I was actively trying to align with HTML here, so we have less independent decoding algorithms on the web. 

Do you have evidence that the specified behavior is breaking pages?

**Comment by tabatkins** [comment]
Circling back around: do you have any evidence of pages breaking due to this behavior?

**Comment by dd8** [comment]
> It's served as Content-Type: text/css; charset=shift_jis. It also starts with a Shift_JIS byte sequence that happens to match the UTF-8 BOM (great test case)
`ef bb bf 2e e5 b9 b3 e5 92 8c 0d 0a 7b 0d 0a 20 |............{.. |`

>> Circling back around: do you have any evidence of pages breaking due to this behavior?

Not other than the test case ... but I don't see enough CSS files using scripts where this might be a problem to provide enough data either way.

There are likely to be encodings other than Shift-JIS where `ef bb bf 2e` can appear as valid characters at the start of a file.

I guess my concerns are two-fold:

1) there's a coupling between BOM sniffing and the syntax of the document being sniffed - it's more reliable with some document types because their syntax makes it unlikely/impossible to have  non-ASCII characters at offset zero

2) this coupling means sniffing can become less reliable due to syntax changes unrelated to CSS. For example, HTML introducing custom element names means `ef bb bf 2e` is more likely to appear at offset zero in CSS as the name of an element style rule.

**Comment by tabatkins** [comment]
If there's not enough CSS files using non-UTF-whatever encoding to tell, that's probably reasonable evidence that it's not a problem in practice either. ^_^

In general I want to avoid proliferating unique charset-sniffing code without reason. Anyone using an encoding other than UTF-8 is asking for trouble, and for no real benefit to themselves; the world would be better off with less encodings causing confusion.

So, absent any compat pain from sniffing causing issues, I'm going to keep CSS Syntax aligned with HTML. (After all, CSS2 had specialty sniffing code for UTF-32 and EBCDIC! No loss removing those!)

**Comment by tabatkins** [comment]
Agenda+ to get WG confirmation that leaving the Syntax spec as it is (matching the sniffing behavior of HTML) is fine.

**Comment by gsnedders** [comment]
See also https://www.w3.org/Style/css2-updates/REC-CSS2-20110607-errata.html#s.4.4 in the CSS 2 errata, #992 for bug report in the errata, and #2777 for the current CSS 2 work.

**Comment by gsnedders** [comment]
https://wpt.fyi/results/css/css-syntax/charset?label=master&label=experimental&aligned purports to test charset handling, and https://bugzilla.mozilla.org/show_bug.cgi?id=796882 purports to make the BOM override everything in Firefox.

**Comment by tabatkins** [comment]
All right, <https://wpt.fyi/results/css/css-syntax/charset/page-windows-1251-css-utf8-bom.html> already tests that a UTF-8 BOM on the stylesheet overrides the environment encoding, and I've now committed <https://wpt.fyi/results/css/css-syntax/charset/page-windows-1252-http-windows-1251-css-utf8-bom.html> which tests that it similarly overrides charset coming from HTTP.
