### ISSUE TITLE
[css-color] Define “computed color”

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4136]
A number of properties have “Computed value: computed color”, it would be nice if these were linked to a definition; however there is no definition of “computed color”.

So this issue is 1) define “computed color” as a term 2) update specs to cross-reference it.

Bonus points to make this an editorial update to css-color-3 as well.

**Comment by frivoal** [comment]
colors-4 has a section on how computed and used values are determined for colors. It needs some work, but is probably an OK starting point. It doesn't use the words "computed color", but that's minor editorial massaging.

https://drafts.csswg.org/css-color-4/#resolving-color-values
