### ISSUE TITLE
[css-animations] Hardware acceleration explicit support proposal 

### ISSUE THREAD

**Issue by rolivo** [w3c/csswg-drafts#4146]
I work a lot with css animation, wonderful experience thank you.  
Mozilla has an option to force the use of the gpu on a page which gives better performance (much better) to the animations.
I am not an expert but I understand that the use or not of the gpu in the animations is based on heuristics, but in practice I have noticed that the animations work better with the forced use of the gpu, so my proposal is the following:

Add the property:
animation-gpu with two auto and accelerated values

something like that:
animation-gpu: auto | accelerated.

they could also be added to the shorthand "animation"

I understand that there are other ways to force hardware acceleration but in practice they are complex and could be further simplified with the above proposal.

**Comment by birtles** [comment]
What is the option that Mozilla offers that you are referring to? (`layers.acceleration.force-enabled` perhaps?)

**Comment by rolivo** [comment]
@birtles I have only tested it in linux, in the context menu of a window an option should appear that says "run with graphics card"

**Comment by birtles** [comment]
@rolivo I'm afraid this sounds awfully implementation specific. UAs need to be free to optimize and innovate with how they use resources to render content.

WebRender, for example, takes a very different approach to how content is rendered (largely doing away with layers) that would not be possible if specifications required a particular implementation approach.

It seems to me like 'will-change' is providing the functionality you describe. Namely, hinting to the browser that the element will likely be animated so it should prepare to optimize its rendering accordingly.

**Comment by rolivo** [comment]
I have avoided mentioning the "will-change" property because I was thinking of a simpler solution.
As a web developer it would be really useful for me to have a property that would allow me to do the following:

animation: example 5s linear 2s accelerated;

But I am not an expert and as you mention it would be complex for implementers, the "will-change" property seems good to me as well.

**Comment by birtles** [comment]
Ok, thanks. I hope you don't mind if I close this then since I think 'will-change' covers the intention of the proposed property.

**Comment by rolivo** [comment]
Ok, thank you for your time.
