### ISSUE TITLE
[css-tables] <button>, padding, and border-collapse:collapse

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#415]
According to the <a href="https://drafts.csswg.org/css-tables-3/#collapsed-style-overrides">CSS Tables 3 Spec:</a>
> 
> When a table is layouted in collapsed-borders mode, the following rules apply: 
> - The padding of the table-root element is ignored (as if it was set to 0px). 
>

Based on the following test case (https://jsfiddle.net/kLo6n71a/), it looks like only Edge works properly in case the table-root is a ```<button>``` element. I still would like to resolve on not changing the spec in this case, because what other browsers are doing seem like a bug. 

Opinions?

**Comment by zcorpan** [comment]
`button` is special in various ways and there are open issues in HTML on what its default rendering should be.

https://github.com/whatwg/html/issues?q=is%3Aissue+is%3Aopen+button+label%3A"topic%3A+rendering"
+
https://www.w3.org/Bugs/Public/show_bug.cgi?id=23893

I don't know if those affect this particular issue or not but maybe?

**Comment by FremyCompany** [comment]
Oh, yes, that is it, thanks! 

It looks like non-Edge browsers just plain refuse ```display:table``` on the button but the fixup-generated table root inherits ```border-spacing``` from it. 

I think the fact buttons cannot be ```display:table``` is a bug, but that is not a table bug per se. I am going to leave the spec as-is, but it is interesting to note that ```<button>``` still doesn't work interoperably in 2016...
