### ISSUE TITLE
[css-values] Sync the trig/pow functions with JS more

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4158]
The new trig/pow functions were written based on my own observations of the JS functions. The JS test suite is woefully inadequate, testing virtually no behavior details, so I didn't think I could do any better.

It turns out that the JS spec actually *does* specify these functions in precise detail, so I should go ahead and match it exactly. https://tc39.es/ecma262/#sec-math.pow

**Comment by Loirooriol** [comment]
@tabatkins You didn't address #4157: the spec says `sqrt(X)` and `pow(X, .5)` are equivalent, but for `X = −∞` the former is NaN and the latter is +∞

**Comment by tabatkins** [comment]
Ah, fine. Fixed in 487c2e1.
