### ISSUE TITLE
[css-fonts-4] wording in 9.3 font-variant-emoji property

### ISSUE THREAD

**Issue by PeterCon** [w3c/csswg-drafts#4166]
The paragraph describing [Presentation Participating Code Points](https://drafts.csswg.org/css-fonts-4/#presentation-participating-code-points
) currently has "...contributing to a **Unicode Presentation Sequence**" (emphasis added). That term is not defined in this spec or by Unicode. Rather, Unicode uses "emoji presentation sequence" (not capitalized) — see [UTS #51, section 1.4.3](https://www.unicode.org/reports/tr51/#Emoji_Variation_Sequences). I suggest changing to "... contributing to a Unicode emoji presentation sequence".

Similarly, I suggest changing "Presentation Participating Code Points" to "Emoji Presentation-Participating Code Points".

**Comment by svgeesus** [comment]
@PeterCon thanks for the bug report, fixed as per your suggestions.
