### ISSUE TITLE
Add Index of Examples in the Appendix

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4169]
Most CSS specs have a bunch of Examples embedded in the document.  It would be really useful to me if there was a generated index in the appendix with links to them to make it easy to access them directly.

CC @tabatkins

**Comment by fantasai** [comment]
@MatsPalmgren Mind refiling this against Bikeshed? https://github.com/tabatkins/bikeshed/issues

**Comment by MatsPalmgren** [comment]
Oops, sorry I didn't know there's a separate repo for that.
And there's already an open issue for it: https://github.com/tabatkins/bikeshed/issues/1149
