### ISSUE TITLE
[css-color-adjust-1] Clear expectations for properties affected by forced colors in animation keyframes?

### ISSUE THREAD

**Issue by melanierichards** [w3c/csswg-drafts#4176]
Suppose an author defines an animation outside of the `forced-colors` MQ, declaring property values in its keyframes which are [typically reverted](https://www.w3.org/TR/css-color-adjust-1/#forced-colors-properties) in forced color modes: https://jsfiddle.net/9ezqLfmt/

Prior implementations in MS browsers would allow this animation to run with the property values as specified by the author outside of the MQ, only updating the forced system colors for the given properties at the end of the animation. So in the given example, the `background-color` animates from red to yellow, then finally is computed to the value of the `Window` system color.

This is a bit jarring for the user. The better experience is probably to ensure that whatever UA guidance is given for the properties in [Properties Affected by Forced Colors Mode](https://www.w3.org/TR/css-color-adjust-1/#forced-colors-properties) applies to these properties inside of animation keyframes (animation origin) as well. Perhaps this is a given, but it might be worth explicitly calling out in the spec to avoid multiple interpretations or author confusion (given historical implementations).

**Comment by melanierichards** [comment]
This might actually be clear enough if cross-referencing [the revert keyword](https://www.w3.org/TR/css-cascade-4/#default) in css-cascade-4. Happy to close if it doesn't bear repeating.

**Comment by fantasai** [comment]
@melanierichards Added a cross-reference to css-cascade-4: https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties
Let me know if that's adequate! (And/or feel free to close the issue. :)

**Comment by melanierichards** [comment]
LGTM, thanks @fantasai!

+ @atanassov @amaher23 in case they have any additional feedback.
