### ISSUE TITLE
[css-sizing] Specify fun replaced element %-block-size behaviour.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#4177]
See random example:
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=7106

If a shrink-to-fit element has a replaced descendant which has a %-block-size. FUN THINGS HAPPEN with the min/max content sizes.

The %-block-size resolves against some value, and through the intrinsic-size reflects, and can contribute to the min/max content size of any parent elements.

I don't believe this is specified anywhere?
I think everyone has implemented this for compat reasons. (yay).

**Comment by bfgeek** [comment]
This should also be disabled for an element which has containment applied.

**Comment by bfgeek** [comment]
@chrishtr @tabatkins

**Comment by fantasai** [comment]
@bfgeek Not sure this is unspecified, isn't it how percentages are defined to work? The only cases where percentages aren't supposed to resolve is if the containing block's height depends on its content, but in this case it depends on its own containing block which is fine. And the intrinsic sizes of images is specced in https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-width

> if 'width' has a computed value of 'auto', 'height' has some other computed value, and the element does have an intrinsic ratio; then the used value of 'width' is:
>    (used height) * (intrinsic ratio)

Marking invalid for now, lmk if I'm missing something.

**Comment by fantasai** [comment]
Sorry skipped a step - intrinsic size of images is actually defined in https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes

> The min-content size of a box in each axis is the size it would have if it was a float given an auto size in that axis (and no minimum or maximum size in that axis) and if its containing block was zero-sized in that axis. (In other words, the minimum size it has when sized as “shrink-to-fit”.)

which defers to CSS2.1 Chapter 10.
