### ISSUE TITLE
[css-contain] editorial: "element" should be "box"

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4189]
https://drafts.csswg.org/css-contain-1/#containment-size
"... or if the element is a table, " (first sentence)

It would be clearer if you wrote "or if the box is a table box" given that the word "table" is linkified to https://drafts.csswg.org/css-display-3/#valdef-display-table. Ditto for other uses of "element is a ..." in this spec.

The term "containing element" occurs frequently in this spec. It appears there is no explicit definition of this term. As I understand it, what you mean is an element that has a principal box that satisfies the conditions in each section respectively. It's probably better to use the term "containing box" to refer to that box directly instead. 
Quoting [_size containment_](https://drafts.csswg.org/css-contain-1/#containment-size) as an example:
> If the element does not generate a principal box (as is the case with display: contents or display: none), or if the element is a table, or if the element is an internal table element, or if the element is an internal ruby element, or if the element’s principal box is a non-atomic inline-level box, size containment has no effect. Otherwise, giving an element size containment has the following effects:

I think it would be clearer to say:

> If an element does not generate a principal box (as is the case with `display: contents` or `display: none`), or if it's a table box, or an internal table box, or an internal ruby box, or a non-atomic inline-level box, then size containment has no effect. Otherwise, the principal box is a _containing box_ for size containment and it has the following effects:

(and replace "containing element" with "containing box" in the text that follows)

**Comment by frivoal** [comment]
Fair point. I don't think this caused ambiguities in practice (so fixing it isn't a normative change), but it was sloppy wording. Will fix.

**Comment by frivoal** [comment]
Made a pull request to address this: https://github.com/w3c/csswg-drafts/pull/4190. Review welcome.
