### ISSUE TITLE
[css-values] Range constraints and functions

### ISSUE THREAD

**Issue by ewilligers** [w3c/csswg-drafts#4191]
Width and duration properties may not be negative. Is `min(1em - 30px, 10px - 1em)` a valid width? Is `calc((sin(1em / 1px) - 2) * 1s)` a valid duration?

Mathematically, they are always negative, but it isn't clear if the parser is required to detect this and reject the values, or if the parser should accept the values, with clamping happening later.

**Comment by faceless2** [comment]
css-values-3 has, in section 8.1.4:

> Parse-time range-checking of values is not performed within calc(), and therefore out-of-range values do not cause the declaration to become invalid.

Percentages used in calc functions can and will change as the window is resized; same with font units if the font uses a vw/vh. So both your examples above are potentially subject to fairly frequent reevaluation and are definitely not always negative.

My understanding was that having CSS declarations become valid or invalid dynamically is not something that is desired - the same approach is used in css-variables, for example.

**Comment by ewilligers** [comment]
Thanks, I had missed the sentence

> Parse-time range-checking of values is not performed within math functions, and therefore out-of-range values do not cause the declaration to become invalid.
