### ISSUE TITLE
[css-fonts] Clarify initial value of 'font-family'

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#4192]
https://drafts.csswg.org/css-fonts-4/#font-family-prop

> Initial: depends on user agent

Is the keyword `inherit` a conforming initial value?

It seems like in WebKit, if you specify `font-family: initial` on an element, it will inherit the font-family from the parent, instead of getting whatever the root element would have if it had no author CSS specified.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/7116

The text "test" is in the `fantasy` font-family in WebKit, but in `serif` in Blink and Gecko.

In CSS2, there was no `initial` keyword, so this was not observable. But now it is, and it is not interoperable between browser engines.

Which behavior is intended? Like WebKit, or like Gecko/Blink? I assumed it would work like in Gecko/Blink. In any case, it would be good to make the spec require something more than "depends on user agent".

cc @nattokirai @litherum @svgeesus

**Comment by fantasai** [comment]
That's... interesting. No, the keyword `inherit` is not a conforming initial value. Cascade defines the initial value as the value the root element takes by default (as well as the value that non-inherited properties take by default). There's clearly some computed value on the root element: that value must be the “initial value” per CSS, and it must also be the value that's returned when the keyword `initial` is set, per the definition of `initial`. It's also worth noting that neither `initial` nor `inherit` can be specified values or computed values, they can only be cascaded values and the specified value becomes whatever those keywords represent. https://www.w3.org/TR/css-cascade-3/#defaulting

I think that makes this issue invalid, and WebKit has a bug.

> In any case, it would be good to make the spec require something more than "depends on user agent".

I'm not aware of a need for the UAs to align on a particular font-family value, if you have one in mind I think you need to explain why it's needed in a separate bug? :)

**Comment by svgeesus** [comment]
Is Webkit treating `body` as the same as `:root` here? That is a bug.

As @fantasai says, there is no obvious value for the initial font-family that we could standardize on.

**Comment by zcorpan** [comment]
> Is Webkit treating `body` as the same as `:root` here?

No. `initial` doesn't mean the value the root element *has*, rather the value it *would have*. So setting font-family on the root shouldn't have an effect on what `initial` keyword does.

Changing the test to style a `div` instead of `body` doesn't change the result in WebKit.

Anyway, if it is already well-defined that `inherit` can't be an initial value, then no need to change the spec. 

WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=200709

**Comment by zcorpan** [comment]
(The de facto initial value seems to be `serif`, but I don't think it's necessary to make it de jure.)
