### ISSUE TITLE
[css-selectors] Sequence of Simple Selectors beginning selector incorrect?

### ISSUE THREAD

**Issue by karlhorky** [w3c/csswg-drafts#4196]
In the [Selectors Level 3 spec](https://www.w3.org/TR/selectors-3/#selector-syntax), it mentions (emphasis mine):

> A sequence of simple selectors is a chain of simple selectors that are not separated by a combinator. It always **begins with a type selector or a universal selector**.

Is this correct? I've been writing sequences beginning with pseudo-classes (such as `:nth-child(1):hover`) for a long time - is that an implementation defect of browsers?

**Comment by tabatkins** [comment]
No, it's not correct, which is why that language doesn't appear in the current Selectors draft. ^_^

<https://www.w3.org/TR/selectors/#syntax> says:
> A compound selector is a sequence of simple selectors that are not separated by a combinator, and represents a set of simultaneous conditions on a single element. If it contains a type selector or universal selector, that selector must come first in the sequence. Only one type selector or universal selector is allowed in the sequence.

**Comment by karlhorky** [comment]
Ok thanks for the (very quick) answer!

I guess these error fixes are not backported to latest versions of older versions of the spec due to the maintenance overhead it would cause?

**Comment by tabatkins** [comment]
Generally, yeah.
