### ISSUE TITLE
[css-lists-3] Compute non-existent `list-style-type` <counter-style> to `decimal`?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4210]
In https://lists.w3.org/Archives/Public/www-style/2016May/0076.html @upsuper wrote:
> Recently, there is a behavior change in Gecko which makes list-style-type be computed to 'decimal' when the specified counter style doesn't exist, rather than keeping the specified nonexistent one. This change helps us save a string for common cases, and simplify some
code. None of which is a big deal, though.
>
> I'm not completely sure what does the spec say for this case. It seems to me the old behavior is more conformant, but I guess the new behavior might be perferable, since it makes the computed value match the used value. So I propose changing the spec to this behavior.
>
> What do you think?

@tabatkins replied
> I'm fine with this if others are; I don't see any particular reason to keep the non-existent type in computed style.  Whichever way is more convenient for implementations is ok with me.

Any other opinions, or should we update the spec to match Gecko?

**Comment by emilio** [comment]
I don't think Gecko does that anymore?

```
document.body.style.listStyleType = "Foobar"
document.body.style.listStyleType // "Foobar"
getComputedStyle(document.body).listStyleType // "Foobar"
```

**Comment by upsuper** [comment]
I think the behavior was changed in [bug 1524328](https://bugzilla.mozilla.org/show_bug.cgi?id=1524328).

So I guess maybe we should say the computed value of `list-style-type` is unspecified... It would probably be the easiest...

**Comment by tabatkins** [comment]
I don't see why we should go with unspecified, if we can settle on an answer. That's only really something we do if we have multiple incompatible impls and no good way to find consensus between them.

As I said before, I don't think there's any particularly good reason to choose one way or the other, so we should do whatever is easiest. Looks like leaving the style around in computed style works best, as it lets Firefox delay having to resolve that style until later in the pipeline. I imagine Blink would benefit similarly (tho right now we don't implement @counter-style at all, so it's just an invalid declaration right now).
