### ISSUE TITLE
[css-sizing] Aspect-ratio min-size needs to check for "auto", not non-zero

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4217]
In <https://drafts.csswg.org/css-sizing-3/#intrinsic>: 

> Otherwise if the box has a definite non-zero min-width or min-height, use that size and calculate the other dimension using the aspect ratio; if both dimensions have a definite minimum, choose the one that results in the larger overall size.

This should probably be checking for non-"auto", not non-zero. (Open ranges are bad.)

**Comment by fantasai** [comment]
Checked for `definite` generally, since `min-content` and percentages are non-auto but still problematic. Lmk if that seems correct.

CC @Loirooriol for sanity-checking :)

**Comment by Loirooriol** [comment]
@fantasai I think that could clarify that the value to be checked for definiteness is the computed value, not the used value, since in most cases an `auto` minimum size resolves to a definite `0`.

**Comment by fantasai** [comment]
Currently specced as `if the box has a [=definite=] non-''min-width/auto'' value`, thanks to ce03a20e79

**Comment by tabatkins** [comment]
@Loirooriol We went ahead and simplified it further, to explicitly check for a computed `<length>`. Since this isn't matching impls or anything, just trying to make a slightly smarter default than 300x150, we figure that's probably okay. This work for you?

**Comment by Loirooriol** [comment]
Checking for a computed `<length>` seems a bit strange to me, because `100%` is a `<percentage>`, but `calc(100% + 100px)` is a `<length>` when used in `min-width` if I get https://drafts.csswg.org/css-values-4/#determine-the-type-of-a-calculation right?

**Comment by tabatkins** [comment]
Not quite! Following the definitions, the type of `100% + 100px` is obtained by [adding the types](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-add-two-types) of 100% and 100px; following that link to TypedOM, we find that the resulting type is "length, with a percent hint set to length".

Then, a calc() matches a production if its type [matches that production](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-match); following the link again to TypedOM, a type with a percent hint can not match `<length>` (because it contains a non-resolved percentage that we're inferring to be compatible with `<length>`).

**Comment by tabatkins** [comment]
@Loirooriol So, with that explanation, does the spec seem okay?

**Comment by Loirooriol** [comment]
Yes, then it looks good to me
