### ISSUE TITLE
[css-sizing-3] max-content contribution of replaced only-aspect-ratio elements might be improvable

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4218]
We appear to have no interop on this case: 

```html
<!DOCTYPE html>
<div style="width: max-content; border: thick double;">
<svg style="float:left;" viewBox="0 0 200 100"></svg>
```

Chrome gives it 0x0, Firefox gives it ICB width and then ratio height. The spec says 300px width and ratio height.

We suggest to go with FF's behavior, as this seems more useful than 0, and less arbitrary than 300px.

**Comment by jensimmons** [comment]
I agree.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/57e26804d894b88849d1a099595de4c73e598256
