### ISSUE TITLE
[css-sizing-3] Cleanup wording around available size "being" a constraint

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4219]
Flexbox says that available sizes can *be* a "min/max-content constraint" (and Sizing carries that notion into its definition of available size). But nothing ever mentions what this means.

What we probably meant is that in such a case, anything that tries to use the available size in a calculation instead reverts to sizing under a min/max constraint. But that's not stated anywhere. It also might be the case that every situation that wants this is already specifying "if sized under a min/max siznig constraint..." and thus doesn't need this additional level of indirection.

**Comment by fantasai** [comment]
I'm not sure what you want fixed here. Append “which forces boxes to be laid out under that constraint” to the definition of Available Space? Something else?
