### ISSUE TITLE
[css-cascade-3] defines "origin" which conflicts with HTML

### ISSUE THREAD

**Issue by jyasskin** [w3c/csswg-drafts#422]
https://drafts.csswg.org/css-cascade-3/#origin defines origin as `<dfn class="dfn-paneled" data-dfn-type="dfn" data-export="" id="origin">origin</dfn>`, which collides with [HTML's definition](https://html.spec.whatwg.org/multipage/browsers.html#concept-origin). You could add a [`for`](https://github.com/tabatkins/bikeshed/blob/master/docs/definitions-autolinks.md#specifying-what-a-definition-is-for) value to CSS's definition in order to disambiguate it.

**Comment by tabatkins** [comment]
Cascade 4 switches it over to "cascade origin", to avoid the conflict.  I just updated Cascade 3 to use the same term.  The TR versions will still have issues, tho.  (I really need to get the obsoleting machinery working...)
