### ISSUE TITLE
[css-writing-modes-4][css-flexbox-1] Orthogonal column flex containers

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4221]
If you have a column flexbox that is orthogonal to its parent, and whose flex items are parallel (not orthogonal), per spec we pass the parent's infinite available block size to the flexbox's inline size, which then passes to the flex item, giving the flex item an infinite available inline size without the flex item itself being orthogonal.

Implementations don't seem to do this. They apply the ICB clamping to the flexbox itself, then the flex items just lay out into that (finite, definite) size.

Assuming this is what we want, we'll need to tweak Flexbox's wording a little bit, and possibly Writing Modes to match.

Repro:
```html
<!DOCTYPE html>
<div style="display: flex; writing-mode: vertical-rl; flex-flow: column; border: 40px double;">
 <span>foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo </span>
 <span>foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo </span>

<style>
span { border: orange solid 40px;; }
```

**Comment by frivoal** [comment]
@tabatkins flexbox isn't REC yet, so it's not a dependency of writing-modes-3. Can we tag this against writing-mode level 4, or is this something that *must* be fixed in L3?

**Comment by tabatkins** [comment]
I don't care what it's tagged to, but if we do come up with something for this soonish, we should make the edits in WM3 as well. ^_^

**Comment by fantasai** [comment]
Retagged to WM4, made L3 undefined in this aspect (so that it's only defining sizing on CSS2.1 display types).

**Comment by fantasai** [comment]
Spec for WM4: https://www.w3.org/TR/css-writing-modes-4/#orthogonal-layout
Implementations, as Tab mentioned, cap the orthogonal flex/grid container itself rather than passing infinity through and letting descendant block containers cap.

The original thought behind passing infinite available space through vs using the viewport as a cap:
    * For lines of text, laying out as max-content is problematic because it's hard to read such text. It's much, much more useful to wrap it to the viewport size.
    * For flex and grid, laying out at max-content isn't as much of a problem because you're not reading line by line and having to scroll up and down for each line in the same way. (But the flex *items* should cap at the viewport size if they contain text, for the reason above.)

So there are two interesting questions here:
    * Which do we think is the better behavior for CSS: capping the orthogonal item itself, or capping only block containers?
    * If we think it's better to not cap orthogonal flex and grid containers themselves (but rather the block containers within them), is it worth asking implementations to change?
