### ISSUE TITLE
[css-text-3] hanging-punctuation effect on inline/block bounds

### ISSUE THREAD

**Issue by stantonma** [w3c/csswg-drafts#4222]
https://drafts.csswg.org/css-text-3/#hanging-punctuation-property

Hanging punctuation is defined to allow glyphs to display outside of the line box. However it's not clear if the bounds for things like border, background-color, and selection should include the overhang or not.

Safari's implementation includes the bounds if applied inline, but the overhang does not seem to affect the box bounds. This behavior is fine with me, but wondering if we should standardize it somewhere.

**Safari Rendered Output**

![Screen Shot 2019-08-19 at 3 45 53 PM](https://user-images.githubusercontent.com/51447838/63304632-8abd7380-c298-11e9-89d6-b4a8c3721420.png)

https://codepen.io/stantonm/pen/ZEzpJpY

**Comment by frivoal** [comment]
Hanging has no effect on the block box or the, so the first part of the screenshot is clearly right.

I think that the second paragraph in https://drafts.csswg.org/css-text-3/#hanging implies that the behavior in the second part of screenshot is right too.

However, it may be worth making that explicit.

**Comment by fantasai** [comment]
I think the spec is pretty clear on that point:

> A hanging glyph is still enclosed inside its parent inline box [...]  Effectively, the hanging glyph character advance is re-interpreted as an additional negative margin on the affected edge of its parent inline box; the line is otherwise laid out as usual.

Closing out as invalid, re-open with an explanation if you think that's not sufficient.
