### ISSUE TITLE
restored definition of automatic block sizing pulls in issues related to intrinsic sizes in the block dimension

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#4231]
I have one concern about the primary [paragraph](https://drafts.csswg.org/css-writing-modes-3/#orthogonal-layout) that was just restored in #4220.

The text of this paragraph seems to unnecessarily redefine the automatic size in the block dimension in a complicated way that pulls in all of the issues in #2890.

It seems to me that the point of the paragraph is to produce a different automatic size in the inline dimension (which is the block dimension of the parent), which is the dimension in which the `min-content` and `max-content` concepts are clearly defined.  I think it's quite reasonable in that dimension.

In the block dimension, I *think* the intent of the paragraph is to produce the same rules as the default behavior:  the automatic size is the result of layout (since I think the `min-content` and `max-content` sizes in the block dimension are supposed to be the same, which makes the fit-content expression given equal to both of them).  But it does that by referring to concepts that aren't clearly defined (see #2890) and which might be interpreted in other ways.

I would prefer if this paragraph instead just redefined the automatic size in the inline dimension and left the automatic size in the block dimension alone.

(That said, I'm thinking about this primarily for a `display: block` orthogonal flow, and haven't really thought through what the automatic sizes are for `flex` or `grid`.)

**Comment by fantasai** [comment]
“and left the automatic size in the block dimension alone” means what, exactly?

**Comment by dbaron** [comment]
deferring to the existing definition of automatic block size that already exists for its `display` type

**Comment by dbaron** [comment]
[IRC discussion](https://log.csswg.org/irc.w3.org/css/2019-08-21/#e1218950)

**Comment by fantasai** [comment]
Verified via IRC
