### ISSUE TITLE
[cssom] Rename [ArrayClass] in [LegacyArrayClass]

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/csswg-drafts#424]
CSSOM [uses the `[ArrayClass]` extended attribute](https://drafts.csswg.org/cssom/#the-medialist-interface) on `MediaList`, `StyleSheetList` and `CSSRuleList`.

That extended attribute is now [called `[LegacyArrayClass]` in WebIDL](http://heycam.github.io/webidl/#LegacyArrayClass), so the IDL definitions should be updated to match.

**Comment by zcorpan** [comment]
Thank you!
