### ISSUE TITLE
[css-scroll-anchoring-1] Can anchor node be an inline-block?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4247]
If you go to [this test-case](https://bug1540203.bmoattachments.org/attachment.cgi?id=9088572), then scroll so that the red box is only partially visible, then click it, what should happen?

Firefox and Chrome disagree on this one, and I think Firefox is right per spec. However the user expected Chrome's behavior.

In particular:

 * Firefox chooses the text as the scroll anchor, and thus when the box grows the text keeps its position relative to the viewport.

 * Chrome seems to choose the red box as an anchor, and thus when it grows it moves the text down.

I think per spec Firefox is right. https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection says:

> The anchor node is either a non-anonymous block box or a text node.

Where block box is https://drafts.csswg.org/css-display-3/#block-box. An inline-block element is clearly not a "block box" (its display outside is `inline`), so the next eligible anchor node is the text.

However it seems Chromium does select inline-blocks as anchor nodes?

Is this an oversight in the specification, or a bug in Chromium?

cc @skobes @eqrion @dholbert

**Comment by skobes** [comment]
I think this is a spec bug; we did not intend to exclude inline-block elements from being anchor nodes.

Probably any box-shaped element should be suitable for anchoring to.

**Comment by emilio** [comment]
What should the spec say about stuff like inline-blocks or inlines split across multiple lines?

**Comment by emilio** [comment]
In particular, the spec says:

> The scroll anchoring bounding rect of a DOM node N is N’s scrollable overflow rectangle if N is a block box, or the bounding rect of its line boxes if N is a text node. 

Also, the spec seems messy here. N cannot be both a box and a node.

**Comment by emilio** [comment]
Also, blink seems to [skip inlines](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/layout/scroll_anchor.cc?l=276&rcl=79f03ab2a29a9977b9ad444d9c29530a4273da30), how does that make sense while not skipping inline-blocks?

So, basically, the blink condition for whether something it's an acceptable anchor if I'm reading the code right is:

```cpp
!IsAnonymous() && !IsInline() && (IsText() || IsBox())
```

What does `IsBox()` really mean? what is the rect that blink uses for boxes that are not blocks? Why does the above condition make sense?

**Comment by skobes** [comment]
An inline-block has a "layout box" in Blink.  Like a block, it occupies a rectangular space, so its coordinates are simple to reason about.

Blink skips inlines because we didn't want to worry about elements that are split across lines.  I suppose we could have taken an enclosing rect around the line boxes similar to what we do for text nodes, but we didn't find cases where this seemed important.

We do anchor to <img> elements.

**Comment by emilio** [comment]
Right, I see that an inline-block returns true for `IsBox()` in Blink, so does probably LayoutReplaced and all that.

But we need to come up with a definition that we can interoperably implement. "Everything that inherits from LayoutBox in Blink but it's not a LayoutInline" is not a sensible thing to put on a spec.

**Comment by skobes** [comment]
https://www.w3.org/TR/css-display-3/ has some concepts that may be useful here, such as "block container" and "replaced element".

**Comment by emilio** [comment]
Sure, but is that what Blink implements? There's a whole bunch of stuff inheriting from LayoutBox, not all of those are block containers or replaced.

**Comment by skobes** [comment]
I think those are the important ones.  We can patch for other cases as they arise.  I wouldn't overfit the spec to the exact set of things that make `IsBox()` true.

**Comment by emilio** [comment]
I don't think that approach really works to get interoperable implementations...

We should define exactly what it's supposed to be an anchor, and we should adjust implementations to follow it.

Do you think everything but [inline boxes](https://www.w3.org/TR/css-display-3/#inline-box) and [ruby containers](https://drafts.csswg.org/css-ruby-1/#ruby-container) would be a good definition? Those are the only non-text things that can split across lines, afaict.

**Comment by skobes** [comment]
Sounds good to me.
