### ISSUE TITLE
[cssom][css-cascade] What should getComputedStyle say for 'line-height: normal'

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#4249]
https://drafts.csswg.org/cssom/#resolved-values
for line-height, it says

> The resolved value is the used value.

For a test like this

```
<!DOCTYPE html>
<input id=input>
<script>w(getComputedStyle(input).lineHeight)</script>
```

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/7159

Safari gives `13px`, Chrome and Firefox give `normal`.

Given the definition of used value, I think Safari is correct.

What is correct if we assume "used value" is right?

If CSSOM currently matches Safari, should it be changed to match Chrome & Firefox instead?

**Comment by emilio** [comment]
Firefox has this behavior behind a pref on Nightly / Beta only. I plan to turn it on-by-default on the next release cycle if no regressions are found.

This was done in https://bugzilla.mozilla.org/show_bug.cgi?id=1536871 as a result of the discussion in https://github.com/w3c/csswg-drafts/issues/3749, so closing as that issue has way more context.
