### ISSUE TITLE
[css-grid] Missing information about baseline participation of a grid item

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#425]
At some point, we had the following text in the Grid Baseline section of the Grid Layout specification:

"A <a>grid item</a> <dfn export id="baseline-participation">participates in baseline alignment</dfn> in a particular dimension if its value for 'align-self' or 'justify-self', as appropriate, is ''baseline'' and its inline axis is parallel to that dimension."

This text has been removed, but there is still a broken link to the baseline-participation. Either the broken link is an error to be fixed or we miss the removed text. In any case, I think the text about grid item's baseline participation is something useful, but perhaps I'm missing some other issue where that was discussed already.

**Comment by javifernandez** [comment]
It seems the removed text has been moved to the Alignment specs:

1- Referring to the participation in an baseline self-alignment 
  - https://drafts.csswg.org/css-align/#baseline-align-self

2- Referring to the participation in a baseline content-alignment
  - https://drafts.csswg.org/css-align/#baseline-align-content

I wonder where the link in the Grid Layout spec should point to, considering that the section in question is defining how to determine the baselines of a grid container.

**Comment by MatsPalmgren** [comment]
css-align 4.2 is probably a better place to link to:
https://drafts.csswg.org/css-align/#baseline-values

**Comment by javifernandez** [comment]
Umm, however, the text in question talks about when a grid item participates in a baseline-alignment in a particular dimension.

**Comment by MatsPalmgren** [comment]
css-align 4.2 defines when a grid item participates in baseline alignment (with "alignment  subject" = "grid item" etc).  What css-grid "11.6. Grid Container Baselines" talks about is how such a baseline (the baseline of a group of baseline-aligned items in the first/last track) may be used as the first/last baseline of the grid container itself.

**Comment by fantasai** [comment]
Yeah, I need to clean up the baseline section. I'm partway through edits, hopefully finish up this weekend. :)

Btw, see also https://github.com/w3c/csswg-drafts/issues/373#issuecomment-242863486 which is an open issue...

**Comment by fantasai** [comment]
OK, I've fixed the broken link. @javefernandez, can you let me know if there are any dangling references or anything else that's broken/confusing?

**Comment by javifernandez** [comment]
The link is now pointing to the section defining Baseline Alignment, as Mats suggested. I'm not totally sure if that section describes, completely, what "an item participates in Baseline Alignment" means; Mats stated that it's clear enough, though.

My main doubts comes from the fact that I'm not sure, reading that text, whether an orthogonal item can participate in a Baseline Alignment (self or content) or not. The sections I pointed out in my first comment precisely explain that issue, so somehow I miss that in the new text. 

It's true that the link has been changed and now, it does not refer to the "participation" but to the Baseline Alignment definition itself.

**Comment by fantasai** [comment]
OK, made some edits. Let me know if it's okay yet?

**Comment by javifernandez** [comment]
The text is much clearer now, but I think there are still issues. 
You made recently some changes in the section 8.2. Baseline Alignment Terminology [1] which I think are not reflected in the new text you added in section 6.4. Baseline Self-Alignment:

"A grid item participates in first (last) baseline self-alignment in either its row or column (whichever matches its inline axis) if its justify-self or align-self property (whichever affects its block axis) computes to first baseline (last baseline). "

I think that we had agreed on the idea that an grid item can participate in both, row and column alignment context; the "either row or column" is not accurate and "whichever matches its inline axis" makes no sense now. Also, we can use both, justify-self and align-self properties to apply self-baseline alignment to an item in both axis. The "whichever affects its block axis" makes no sense either.

1- https://drafts.csswg.org/css-align-3/#baseline-terms

**Comment by fantasai** [comment]
Good catch! Fixed. Anything else? :)
