### ISSUE TITLE
[web-animations] Please replace "Promise objects" section

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-drafts#4250]
https://drafts.csswg.org/web-animations-1/#promise-objects

Please use the WebIDL definitions: https://heycam.github.io/webidl/#es-promise-manipulation

**Comment by birtles** [comment]
Fixed by 0d82749f2438b6ec7496c9207b961b300e26d8eb.

**Comment by upsuper** [comment]
A side note, if you create an issue with wrong content, please don't just edit it to the real content, but close it and open a new one or at least post your content as a reply.

There are people read issues via emails, and this kind of issues are really unhelpful for them. Also W3C has an email-based [archive](https://lists.w3.org/Archives/Public/public-css-archive/) for all the discussion. By doing nontrivial in place editing, you are effectively bypassing that archive, and it would look like https://lists.w3.org/Archives/Public/public-css-archive/2019Aug/0508.html
