### ISSUE TITLE
[css-animations][web-animations][css-font-loading][cssom-view][css-transitions][resize-observer] Update to constructor operations

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-drafts#4253]
See https://github.com/heycam/webidl/issues/778.

* [x] css-animations-1
* [x] css-animations-2
* [x] css-font-loading-3
* [x] css-transitions-1
* [x] css-transitions-2
* [x] cssom-view-1
* [x] resize-observer
* [x] web-animations-1
* [x] web-animations-2

**Comment by birtles** [comment]
Currently blocked on bikeshed support (https://github.com/tabatkins/bikeshed/issues/1513).

**Comment by tabatkins** [comment]
Not blocked.

**Comment by birtles** [comment]
I've updated all the animations specs. Someone still needs to fix `css-font-loading-3`, `cssom-view-1`, and `resize-observer`, however.

**Comment by tabatkins** [comment]
Thanks Brian! I finished out the rest.
