### ISSUE TITLE
[css-text] text-transform should happen after white-space collapsing but before Trimming and Positioning

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4254]
The [definition of the `text-transform` property](https://drafts.csswg.org/css-text-3/#text-transform-property) includes this sentence:

> Text transformation happens after [white space processing](https://drafts.csswg.org/css-text-3/#white-space-rules), which means that full-width only transforms U+0020 spaces to U+3000 within preserved white space.

This puts it after [Phase I: Collapsing and Transformation](https://drafts.csswg.org/css-text-3/#white-space-phase-1), which seems intentional, but also after [Phase II: Trimming and Positioning](https://drafts.csswg.org/css-text-3/#white-space-phase-2), which does not. I don't see any reason why we'd want a space-converted-to-a-ideographic-space at the end of a line to be handled differently from a native ideographic-space at the end of a line.

I'm less sure about Segment Break Transformation Rules, but it feels like doing the transform after that is ok, and probably simpler for implementations.

I would therefore propose changing that sentence to:

> Text transformation happens after [Phase I: Collapsing and Transformation](https://drafts.csswg.org/css-text-3/#white-space-phase-1) and [Segment Break Transformation Rules](https://drafts.csswg.org/css-text-3/#line-break-transform) but before [Phase II: Trimming and Positioning](https://drafts.csswg.org/css-text-3/#white-space-phase-2). This means that full-width only transforms U+0020 spaces to U+3000 within preserved white space.

cc: @fantasai

**Comment by frivoal** [comment]
Actually, since the Segment Break Transformation Rules are invoked from the middle of Phase I, I guess my suggestion above to put text-transform after both is the only reasonable choice, as "after phase I, before Segment Break Transformation Rules" would be nonsensical.

**Comment by fantasai** [comment]
Good catch. I think that sentence is from before when U+3000 was collapsed away. As you note, Segment Break Transformation is part of Phase I, so let's drop "and Segment Break Transformation Rules", but otherwise looks like a correct fix.
