### ISSUE TITLE
[mediaqueries] device-width media feature and privacy

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#426]
https://drafts.csswg.org/mediaqueries/#descdef-media-device-width

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=29577

resulting in

https://github.com/w3c/csswg-drafts/commit/dc36ecd7a46b173f958dafa736a84eb9753afb7b

MQ spec should replace "screen" with "Web-exposed screen area" (xref cssom-view, or we can move the definition somewhere else).

cc @cvrebert

**Comment by zcorpan** [comment]
I suppose this would also affect 'device-aspect-ratio'...

**Comment by frivoal** [comment]
Aligning with cssom-view on this makes sense to me.

Besides, those media queries are deprecated anyway, so I have no particular qualm about tweaking them, especially to protect privacy.

**Comment by cvrebert** [comment]
Great work Simon! ❤️
