### ISSUE TITLE
[css-text-3] Segment Break Transformation Rules and wbr

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4260]
The [Segment Break Transformation Rules](https://drafts.csswg.org/css-text-3/#line-break-transform) allow text like this:
```
aaaa&#x200b;
bbbb
```
to be rendered as if it were
```
aaaa&#x200b;bbbb
```

This is nice, but in other circumstances, using U+200B does the same thing as using `<wbr>`. Since this rule does not speak of `<wbr>`,
```
aaaa<wbr>
bbbb
```
would be rendered into
```
aaaa<wbr> bbbb
```
rather than
```
aaaa<wbr>bbbb
```
That seems unfortunate, as `<wbr>` is largely the same as U+200B except with the ability to be targeted by selectors.

**Comment by fantasai** [comment]
It's up to HTML to define WBR as equivalent to U+200B, not CSS. Closing as out-of-scope.

**Comment by frivoal** [comment]
Sure, but we could offer a hook for that: "U+200B, or constructs considered equivalent by the host language."

**Comment by fantasai** [comment]
I don't think one is necessary. HTML should define it to be exactly equivalent for rendering. If we make an exception here, we have to track everywhere we need to make an exception.
