### ISSUE TITLE
[css-shapes-2] The new definition of '<basic-shape>' should include 'path()'

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#4270]
The [definition of `<basic-shape>`](https://drafts.csswg.org/css-shapes-2/#typedef-basic-shape) for `shape-inside` in [css-shapes-2] doesn't include `path()` now. We define [`path()`](https://drafts.csswg.org/css-shapes-2/#funcdef-path) as a delta of supported basic shapes in [css-shapes-2], and it seems no other places mention it.
IIRC, at least four properties use `<basic-shape>`:
1. [`shape-outside`](https://drafts.csswg.org/css-shapes/#shape-outside-property): The link of `<basic-shape>` in its value definition links to [the definition of `<basic-shape>` in [css-shapes]](https://drafts.csswg.org/css-shapes/#typedef-basic-shape)
2. [`shape-inside`](https://drafts.csswg.org/css-shapes-2/#shape-inside-property): The link of `<basic-shape>` in its value definition links to [its own definition of `<basic-shape>` in [css-shapes-2]](https://drafts.csswg.org/css-shapes-2/#typedef-basic-shape).
3. [`clip-path`](https://drafts.fxtf.org/css-masking-1/#the-clip-path): The same as that of `shape-inside`.
4. [`offset-path`](https://drafts.fxtf.org/motion-1/#offset-path-property): The same as `clip-path` and `shape-inside`. However, it also defines a different syntax of `path()` because `fill-rule` doesn't make sense on `offset-path`.

IMO, the link of the value definition of `<basic-shape>` for `shape-outside`, `shape-inside`, and `clip-path` should link to the same place, and it'd be better to mention `path()` together, to avoid confusing people. Or make all four links of `<basic-shape>` in the value definitions of these properties link to the same place, but add a note for `offset-path` which doesn't use the syntax of `path()` defined in [css-shapes-2].

Thanks.

**Comment by ewilligers** [comment]
I would be ideal if these properties and `d` all used the same path function. I would like to be able to animate a number of these properties through one custom property animation - https://github.com/w3c/css-houdini-drafts/issues/820 .

Among the options are

1. Simply noting in the definition that `fill-rule` is not permitted in `d` and `offset-path`

2. an explicit `fill-rule` in `d` overrides the [fill-rule](https://svgwg.org/svg2-draft/painting.html#FillRuleProperty) property for that path

3. `fill-rule` is not permitted in `d`, and has no effect in `offset-path`

4. `fill-rule` has no effect in `d` and `offset-path`, and is omitted during their serialization.

**Comment by BorisChiou** [comment]
Sounds great. Linking these properties and `d` to the same `path()` function and adding some restrictions or notes for some properties make sense.

**Comment by dirkschulze** [comment]
@ewilligers IMO we should discuss `path()` for `d` attribute/property independent of the decision to back port `path()` to basic-shapes-1. Right now, `<basic-shape>`s are only used by the CSS properties `shape-outside` (`shape-inside' level 2), `clip-path` and `offset-path`.

**Comment by astearns** [comment]
I've moved the definition of path() back to shapes level 1 with https://github.com/w3c/csswg-drafts/commit/a2e5fe5aae9130ba411fcbb8e23cb9f38cc20087

I added some text about implicitly closing an open path for shape-outside and clip-path. I assume that's not desired for offset-path
