### ISSUE TITLE
[css-shapes-2] The readiness to ship for new path() function

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#4271]
`path()`, which [defined in [css-shapes-2]](https://drafts.csswg.org/css-shapes-2/#funcdef-path), is a new supported basic shape. It seems Safari supports it for `clip-path` already, and Firefox would like to ship it for `clip-path` in [bug 1488530](https://bugzilla.mozilla.org/show_bug.cgi?id=1488530) (i.e. `clip-path: path()`). I would like to make sure is it ready to ship? What does CSS working group think about the shipping of `path()` function?
Thanks.

**Comment by astearns** [comment]
I think this would be a good thing to discuss at our upcoming meeting (and here in this thread until the meeting happens). 

We could bring in `path()` to level 1 and republish that (with a bunch of other changes that have been piling up). Or we could keep it in level 2 and get a sense from the group whether it would be good to ship (personally, I think it would be fine). 

I have a slight preference for the former path. What do others think?

**Comment by BorisChiou** [comment]
Agree. Either level 1 or level 2 is ok to me. However, there is a thread to discuss `responsive path` in twitter [1], so it'd be better to have a discussion about `path()` in the next upcoming meeting.
[1] e.g. https://twitter.com/AmeliasBrain/status/1166752022504148993

**Comment by astearns** [comment]
We just discussed this and decided to add path() to level 1: https://github.com/w3c/csswg-drafts/issues/4270#issuecomment-531669816
