### ISSUE TITLE
[css-text-decor] Clarifying skip-ink:auto behavior in relation to CJK text

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#4276]
See Issue 8 in [CSS Text Decoration Module Level 4](https://drafts.csswg.org/css-text-decor-4/#issue-01cb5447).

Currently, it appears that Webkit and Blink browsers forcibly disable ink-skipping behavior (as if `text-decoration-skip-ink:none` were in effect) for a hardcoded list of “CJK” characters.

However, they disagree on the exact set of characters for which skipping is disabled. In particular, Blink seems to add a large but (apparently) rather ad hoc [collection of punctuation and other symbols](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/third_party/blink/renderer/platform/text/character_property_data.h#12) that are not especially associated with CJK text. Hence, these characters don’t get ink-skipping behavior in Chrome even though they may equally well be used in the context of Latin or other scripts, not just in CJK contexts. On the other hand, in Webkit they do get skipped, whether used in Latin or CJK contexts. (Compare testcase: https://jsfiddle.net/rhLjauq4/ in Chrome vs Safari.)

In Gecko’s implementation (not yet enabled in release builds, but available for testing in Firefox nightlies), we’ve taken a slightly different approach. Rather than a fixed set of *characters* for which ink-skipping is disabled, which is problematic precisely because of the large number of “common” characters — mainly punctuation and symbols — that are used in both CJK and non-CJK contexts, the decision whether to disable skip-ink is taken on a per-script-run basis. CJK ideographs are of course recognised as belonging to a CJK script, but in addition, “common” characters will be merged into the same script run when used in a CJK context, and so the same non-skipping behavior will be applied to them *in CJK context only*.

I think it would be helpful for authors if there were agreement as to which characters are or aren’t eligible for skip-ink behavior when `auto` is in effect. Given the substantial number of ambiguous “common” characters, a simple partitioning of individual characters (as currently implemented in Webkit and Blink, AFAICT) is not a particularly good solution. I expect layout engines already do some kind of script-run analysis in order to handle font selection and shaping appropriately, and therefore using script runs as the basis for deciding when to disable ink skipping should not be overly burdensome, and I believe results in more useful behavior. Would the WG and other browser developers be prepared to converge on this approach, and include it in the text-decoration spec?

**Comment by myakura** [comment]
perhaps related: #707

**Comment by fantasai** [comment]
@jfkthame Define “in CJK context”?

**Comment by jfkthame** [comment]
I'm assuming browsers already do script run analysis as part of the rendering process. A Script=Common character, then, is regarded as occurring in CJK context (and therefore skip-ink should not apply to it) if script run analysis assigned it to a run of CJK text.

I'm not sure an exactly-specified algorithm for script run resolution is necessary here (though see http://www.unicode.org/reports/tr24/tr24-29.html#Implementation for some guidance); the details could be left as a quality of implementation issue, at least initially.

**Comment by litherum** [comment]
WebKit uses the Unicode block to detect this.

**Comment by litherum** [comment]
Wasn’t there some discussion about this being done by a user-agent style sheet by selecting elements with the lang attribute set to CJK languages?

**Comment by kojiishi** [comment]
Blink uses heuristic, and it is different from the script-run analysis we use for shaping.

**Comment by kojiishi** [comment]
We also include some non-CJK characters because we've got rather strong feedback saying they look poor and weird in Blink, although they look ok in WebKit. This depends on font rasterizer, how we render underlines, how we skip ink, and a few more. I prefer to keep `auto` as a value for such purposes as we may want to adjust them as our underlying technology changes. I support adding `all` for interoperability as you suggested in #4277 though.

**Comment by jfkthame** [comment]
> Wasn’t there some discussion about this being done by a user-agent style sheet by selecting elements with the lang attribute set to CJK languages?

Yes - I would have liked to try this in Firefox, but it seems there's too much CJK content that appears on pages without being lang-tagged. E.g. if I search via an English-language search engine for a Chinese phrase, I get lots of result links that are in Chinese, but are not tagged as lang=zh. If skipping is enabled based on the fact that they're on an en-GB page, they look terrible.

**Comment by jfkthame** [comment]
> We also include some non-CJK characters because we've got rather strong feedback saying they look poor and weird in Blink

OK, so I assume this is why [characters like dagger† and double-dagger‡ are included](https://jsfiddle.net/rhLjauq4/) in the set of non-inkskippable chars in Blink. But I wonder - was the feedback that they "looked poor" referring to them in a Latin-script context, or was it in relation to use of these characters in a CJK context? ISTM that *failing* to ink-skip them within English text, where nearby descenders are being skipped, looks odd.

**Comment by kojiishi** [comment]
> was the feedback that they "looked poor" referring to them in a Latin-script context, or was it in relation to use of these characters in a CJK context?

There are two cases; one is that they are unified code points, and we don't implement smarter IsCJK function for those code points. Dagger and double-dagger are in this category. We hope to improve this in future.

The other case is some characters in Latin-script context. IIRC Consolas has rather tall slashes (solidius), and URLs using Consolas looked poor ([jsbin](https://jsbin.com/qihuziw/edit?html,output)), and URLs with underlines were too common to ignore. Maybe there are a few more fonts, and "//" skipping ink for proportional fonts looked even weird. Blink's internal function [CanTextDecorationSkipInk()](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/text/character.cc?type=cs&q=CanTextDecorationSkipInk&sq=package:chromium&g=0&l=176) implements this.

We checked WebKit behavior. On Mac/iOS, monospace fonts have shorter glyphs, and WebKit has less gaps than Blink does. Blink rounds in the direction to widen the gap, and rounding is done by CSS pixels, not by device pixels. Checked Gecko too, it looks like Gecko has more gaps that they don't interfere with underlines. We hope to improve this too, so I feel better if we don't define them in the spec.

**Comment by kojiishi** [comment]
FYI, sharing a few feedback we've got at blink-dev when we shipped, in case this explains better: [1](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Pp4CqxTJKjo/oi9Bfi0WAQAJ), [2](https://groups.google.com/a/chromium.org/d/msg/blink-dev/47BHtmz0jVY/Y6PSL7rOBwAJ)

**Comment by macnmm** [comment]
When I read "in CJK context" I assume this brings with it a number of CJK typographic conventions like where underline normally is placed relative to the CJK embox, and thus whether the skip-ink feature would be usable as in a typical Latin-based descender-skipping context. Lined emphasis in CJK did not typically skip (or draw behind) the glyphs, but it does get positioned such that collisions are more rare, making it quite different from typical Latin underline. I would think whether or not the underline is contiguous is also a factor in determining behavior (and CJK context). Thoughts?

**Comment by jfkthame** [comment]
> When I read "in CJK context" I assume this brings with it a number of CJK typographic conventions like where underline normally is placed relative to the CJK embox, and thus whether the skip-ink feature would be usable as in a typical Latin-based descender-skipping context.

I think this is what `text-underline-position: under` is intended to achieve, and if this were applied, the problem of skip-ink behavior producing poor results for CJK text would largely be mitigated. But not all browsers support `text-underline-position: under`, and even when they do, there'll be lots of existing content that doesn't apply it.

(Fonts designed primarily for CJK use could also set their `underlineOffset` parameter so as to place the underline lower than fonts designed for Latin; but even if they did this -- which many don't -- not all browsers respect the font's setting anyway.)

I suppose one option would be to have browsers automatically switch underline positions between a default that's suitable for Latin text and a position for CJK text on a character-by-character basis, but I expect this could give very messy results for mixed-script content. Turning ink-skipping on/off based on the script of the text seems like a better mitigation, although the "right" solution is for authors to use the tools -- such as `text-underline-position` and `text-underline-offset` -- that allow them to place the underline more appropriately.

**Comment by jfkthame** [comment]
Given that there is not a single canonical algorithm for determining the boundaries of script runs in arbitrary text, and given that some implementors want to retain the freedom to make adjustments based on user feedback, I don’t think we can or should currently specify precise, normative requirements for how `text-decoration-skip-ink` behaves down to the level of every individual character.

However, the spec could usefully include a (non-normative) note to offer guidance to implementors and pointers to the Unicode specifications that should provide the basis for behavior here.

I've opened https://github.com/w3c/csswg-drafts/pull/4737 with some proposed draft text for consideration; I hope this will be a useful starting point.

**Comment by fantasai** [comment]
Agenda+ to review @jfkthame’s proposed changes in https://github.com/w3c/csswg-drafts/pull/4737/files

**Comment by litherum** [comment]
I thought the WG agreed to gate this skipping behavior on the lang= attribute, rather than Unicode properties. Am I misremembering?

**Comment by faceless2** [comment]
The proposal from @jfkthame is fairly close to the same process you have to go through for OpenType layout - each character has to be assigned to a script, with common, inherited or unknown characters adopting the script of their neighbouring characters. These are [OpenType Script codes](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags) rather than Unicode Script codes, but for the scripts discussed in the proposal there's no ambiguity mapping between them.

I don't think the exact algorithm is specified - I think lots of people use Harfbuzz these days, perhaps someone that knows it can comment better ([ref](https://github.com/harfbuzz/harfbuzz/blob/master/src/hb-buffer.cc#L617))

I can't comment on whether the proposed algorithm is the right one. But if it is, and if you're doing OpenType layout and can retrieve the script property it assigns to each run of text, then reusing it for ink skipping seems to be a good idea.

**Comment by jfkthame** [comment]
> I thought the WG agreed to gate this skipping behavior on the lang= attribute, rather than Unicode properties. Am I misremembering?

I think you're misremembering (at least according to my memory, which of course is fallible!)

The trouble with gating on `lang=` is that it's so often not appropriately set. This is particularly true for dynamic pages (e.g. search results) and pages hosting user-generated content, where the author cannot predict what languages will be present, but there are also cases of primarily-CJK pages tagged with `lang=en`, or no `lang` attribute at all, where using the attribute to control skipping behavior will give inferior results.
