### ISSUE TITLE
[css-text-decor] Consider adding an `all` value to `text-decoration-skip-ink`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#4277]
With `text-decoration-skip-ink: auto`, ink-skipping is applied to most content, but not to CJK text. This makes sense for common fonts, where the default underline position, designed to work with Latin glyphs, clashes with so many CJK glyphs that skip-ink behavior largely destroys underlining.

This means, however, that it is impossible for an author to specify that they actually *do* want skip-ink behavior to be used with CJK text. This might be desired in cases where the underline position (either specified by the font, or explicitly controlled by the author using `text-underline-offset`) is such that it does *not* clash with most glyphs, but only with occasional exceptionally-deep shapes. With more calligraphic font styles, in particular, the glyphs may not all sit solidly on the same baseline as tends to be the case in square printed styles.

I propose there should be an `all` value (or `always`, or other name to be bikeshedded) for `text-decoration-skip-ink`. The initial value would remain `auto`, so that the browser will do “the right thing” by default, but `all` makes it possible for the author to opt in to ink-skipping behavior even for CJK glyphs where `auto` would disable it.

See the right-hand example here, illustrating how skip-ink behavior might reasonably be applied even to CJK text when using a calligraphic font:

![image](https://user-images.githubusercontent.com/1706499/64248978-80db7780-cf0a-11e9-8bf7-374474e96c4a.png)

**Comment by upsuper** [comment]
I wonder what should happen if the font failed to load and it fallback to some normal font.

This makes me think it should probably be controlled by `@font-face` or so somehow rather than this property.

**Comment by drott** [comment]
I support the proposal for a new non default keyword to include CJK in ink-skipping, such as `all`. I don't think there is a need to make it dependent on the success of the styled primary font-family to be available. As jfkthame@ explained, if CJK in-skipping is desirable, it would have to be explicitly selected by placing the new keyword, and potentially in addition to styling the `text-underline-offset`. I think these two options give reasonable control to avoid an accidental, undesirable application of ink-skipping to the text decoration.

**Comment by litherum** [comment]
The presence of text-underline-offset makes this a good idea.

**Comment by jensimmons** [comment]
I just commented on the call that I think this is a good idea. Just thought I'd add that this will help with teaching as well. Having `none` and `always` makes `auto` make more sense. It's something in-between. It's clearer that `auto` means the browser will decide, sometimes yes, sometimes no.

**Comment by jensimmons** [comment]
In typing my last comment, I wondered if... well
`none` and `always`?

Wouldn't it make more sense for a pair of words to be 
`none` and `all`
or
`never` and `always`

It's a grammatical mismatch that will make it hard for authors to remember the `yes do it all the time` keyword. 

@fantasai Why did you want to use `always` instead of `all`?

**Comment by fantasai** [comment]
@jensimmons `all` implies to me that there's some collection of things to refer to, whereas `always` implies a sort of rule for how you do things. It seemed to me that ink-skipping fits better into the latter category.

**Comment by jfkthame** [comment]
In the related issue #2818, @upsuper commented:

> But similar to @jensimmons in #4277 (comment) I personally think `all` is better than `always` as well. The `all` here implies that we apply the skip-ink to all characters touching underline / overline, overriding browser heuristic of conditional applying. And indeed pairing `none` with `always` doesn't feel very sensible.

I'm also inclined to agree with this; `none | auto | always` feels awkward. It should be either `never | auto | always` or `none | auto | all`, and given that we've already shipped `none | auto`, we can't really go for `never` instead of `none`.

So before we go ahead and implement this (which I think we're ready to do more-or-less immediately), can we please reconsider making the new value `all`? Thanks.

**Comment by jfkthame** [comment]
@fantasai We're ready to implement this new value in Firefox (there's a reviewed patch just waiting to land in https://bugzilla.mozilla.org/show_bug.cgi?id=1611965), but I think there's quite a bit of support for the value `all` in preference to `always`; in addition to @jensimmons and @upsuper's comments (above), I asked @dbaron in person and he also favored `all`.

Could the WG please look again at this and either confirm it wants to stick to `always` despite feedback preferring `all`, or rename the new value as requested here?
