### ISSUE TITLE
[cssom][css-images] CSS.elementSources incompatible with CSS being an IDL namespace

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#428]
From https://www.w3.org/Bugs/Public/show_bug.cgi?id=29623

https://drafts.csswg.org/css-images-4/#elementsources

reads

```
partial interface CSS {
  [SameObject] readonly attribute Map elementSources;
};
```

If we switch CSS over to be IDL namespace instead of interface, it can only use operations, not attributes, as far as I can tell.

`elementSources` is not implemented anywhere, is it? Should we change it to an operation when switching to IDL namespace? Or should namespaces be able to use attributes in Web IDL?

**Comment by nox** [comment]
AFAICT that specification is wrong anyway, because it's an attribute so `CSS` should be instantiated first, but then the code snippet said:

```js
CSS.elementSources.set('fancy', bg);
```

Which clearly is trying to use `elementSources` has a static attribute.

**Comment by zcorpan** [comment]
Yep, indeed.

On a related note `document.cssElementMap` was removed from HTML in https://github.com/whatwg/html/pull/258 (due to lack of implementations for years).

**Comment by bzbarsky** [comment]
The use of `Map` here is a concern as well.  It causes some implementation issues and couples layout to scripting in ways that are not necessarily desirable.  A maplike would make a lot more sense.

Anyway, we could add attribute support to namespaces.  We just didn't have any use cases so far, and it's hard to design in a vacuum....

**Comment by tabatkins** [comment]
Yeah, that spec version is way out of date and needs to get some stuff dropped.
