### ISSUE TITLE
[css-transitions-2] transition-timing-function and getComputedTiming()

### ISSUE THREAD

**Issue by george-steel** [w3c/csswg-drafts#4288]
Should the easing function specified in `transition-timing-function` be applied to the global timing function of the CSSTransition's KeyframeEffect (and be returned by `getComputedTiming()`) or should it be applied to the first keyframe? First keyframe is consistent with CSSAnimation while global timing seems to be implied by the reversing behavior, as the global progress it talks about is affected by the easing function and it would make sense if getComputedTiming returned this value.

**Comment by birtles** [comment]
That's a great question. In Firefox we apply it to the first keyframe for consistency with CSS animations, but I can see how it might be more intuitive for an author if it applied to the effect instead (so you can substitute out the keyframe values without affecting the easing).

Furthermore, regarding the reversing behavior you identified, it looks like we ran into the same issue in Firefox and have an outstanding issue to moving the easing to the effect instead ([code comment](https://searchfox.org/mozilla-central/rev/588814f2edddf0e132d77d326ddae50911e8bad1/layout/style/nsTransitionManager.cpp#695-699), [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1292001)).

**Comment by graouts** [comment]
We discussed this during the [2019-09-10 telcon](https://docs.google.com/document/d/1j3oeLpgX6kneG9lEgZQ80kitdyN-vbAYGPiwtYyN3tw) and I agree that this is desirable. I think at this stage we have general agreement to pursue this, @george-steel could you make a spec edit and create a pull request?
