### ISSUE TITLE
[css-multicol-1] which paragraph says count+width not making sense?

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#4291]
> However, as described below, setting both the width and number of columns rarely makes sense.

https://drafts.csswg.org/css-multicol/#example-38b72848

Although I'm pretty bad at reading, I couldn't find below where it's described. Example 4 doesn't seem to say that.

**Comment by frivoal** [comment]
I agree, I cannot find the "below". Also, this statements is pretty strange. It's judgemental, but I don't agree with it. I think we should just drop it.

@rachelandrew , what do you think?

**Comment by rachelandrew** [comment]
Yep, I had wondered about it too. I think we can just remove that? If so I'll do it.

**Comment by myakura** [comment]
I just found MDN explains it pretty well (guess who wrote it ;-))
https://developer.mozilla.org/docs/Web/CSS/CSS_Columns/Basic_Concepts_of_Multicol#Using_column-count_and_column-width_together

perhaps the spec say similar. adding a note to tell setting these two might end up fewer columns is helpful for authors.

**Comment by frivoal** [comment]
Yeah, we can just delete that, no need to go through the working group for that, it's just a weird little bit of non normative prose.
