### ISSUE TITLE
[css-flexbox] min-height section should reference definite sizes instead of mentioning "does not prevent percentage resolution"

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#4310]
https://drafts.csswg.org/css-flexbox/#min-size-auto

> Nonetheless, although this may require an additional layout pass to re-resolve percentages in some cases, this value (like the min-content, max-content, and fit-content values defined in [CSS-SIZING-3]) does not prevent the resolution of percentage sizes within the item.

That should just say something like "This value does not prevent the block-size from being definite when it otherwise would be"

@fantasai @tabatkins

**Comment by tabatkins** [comment]
I've rephrased the paragraph, check it over @cbiesinger?

(First paragraph already existed and is unaltered, just providing it for context since the new phrasing in the second paragraph references it more directly.)

> For the purpose of calculating an intrinsic size of the box
> (e.g. the box’s <a>min-content size</a>),
> a <a>content-based minimum size</a> causes the box’s size in that axis to become indefinite
> (even if e.g. its 'width' property specifies a <a>definite</a> size).
> Note this means that percentages calculated against this size
> will [=behave as auto=].
> 
> For other cases, it does not force the box's size to become indefinite.
> However, if a percentage resolved against the box's size <em>before</em> this minimum was applied,
> it must be re-resolved against the new size after it is applied.

**Comment by tabatkins** [comment]
ping @cbiesinger (or @davidsgrogan?)

**Comment by davidsgrogan** [comment]
LGTM
