### ISSUE TITLE
[css-scroll-anchoring-1] position: sticky should probably be excepted, too

### ISSUE THREAD

**Issue by stuartpb** [w3c/csswg-drafts#4318]
https://drafts.csswg.org/css-scroll-anchoring/#anchor-node-selection lists `position: fixed` as an exclusion condition for anchor selection, but, as worded, would not skip over an element with `position: sticky`.

**Comment by emilio** [comment]
Discussed in #3319. TL;DR: You're right, this needs specs changes.

Closing in favor of that issue.
