### ISSUE TITLE
[scroll-animations] ScrollTimeline fill-mode has asymmetric interaction with animation fill modes.

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#4325]
ScrollTimeline's fill mode is a bit awkward to use. See this demo here:
https://jsbin.com/haworeb/edit?html,output

The ScrollTimeline is active from scroll offset 25 to 75 to observe the asymmetric behavior:
* Before the ScrollTimeline range, if the ScrollTimeline has `fill: both` or `fill: before` the currentTime is 0 so regardless of the effect's fill, the effect has it's initial value.
* After the ScrollTimeline range, if the ScrollTimeline has `fill: both` or `fill: after` the currentTime is the effect duration which means that the effect's fill mode decides whether the last value fills.
* If ScrollTimeline has `fill: none` the effect's fill mode doesn't matter.

I think this makes the fill on ScrollTimeline difficult to use since you need to pair it with the effect. I think that as a developer it would be easier if ScrollTimeline didn't have fill, and just exceeded the time range (i.e. < 0 or > timeRange) when it was outside of the scroll range. This way I would only have to worry about the effect's fill. Do you think there are use cases for separately wanting to rely on the scroll timeline's fill?

**Comment by majido** [comment]
The discussion for this issue happened mostly on #2066 (In particular see this [comment](
https://github.com/w3c/csswg-drafts/issues/2066#issuecomment-577424074)).

I will summarize my understanding of the consensus here:

- Remove ScrollTimeline.fill
- Introduce readonly attribute [timeline](https://drafts.csswg.org/web-animations-1/#animationtimeline) state in Web-Animation that can be:  {`Inactive`, `BeforeStart`, `InRange`, `AfterEnd`}
- In the case of ScrollTimeline
  - `Inactive`: No source, or non-scroller source   => timeline.currentTime is undefined.
  - `BeforeStart`:  when scroll offset < start           => timeline.currentTime is 0
  - `InRange`:       when start <= scroll offset < end => timeline.currentTime is calculated based on existing formular.
  - `AfterEnd`:       when end <= scroll offset   => timeline.currenTime is timeRange.
- Update animation and animation effect [active time](https://drafts.csswg.org/web-animations-1/#active-time) and [phase](https://drafts.csswg.org/web-animations-1/#before-phase) calculation to take the timeline state into account. For example when a timeline is in `InBefore` state then all its running attached animation effect would be in their `before` phase as well and similarly for other states. In another word, the active time of an animation effect would be determined from both the state of its timeline and then the current time of its timeline. This needs to be formalized in more details.

**Comment by majido** [comment]
BTW I am a bit hesitant to use the name 'state' for this concept on Timeline. The concept most closely map to [phase](https://drafts.csswg.org/web-animations/#animation-effect-phases-and-states) but not exactly. So if anything we should call it `Timeline.phase`.

Animation Effect phase can be `before`, `active`, `after`. The proposed concept for state has these three plus `inactive`.  So it is not a perfect map but close enough. I wonder if we should just include `inactive` as a phase for both timeline and animation effect?

**Comment by majido** [comment]
@JTensai  removed the fill in this [PR](
https://github.com/w3c/csswg-drafts/pull/4750/files#diff-459bc557d35b07abf7c4b3daa343a46bL561).

However including in it, the fix for making the [end scroll offset inclusive](https://github.com/WICG/scroll-animations/issues/19) for Issue 19 was also removed. 

So now scroll timeline has the following behaviour:

  1. **scroll offset < start** 
       - timeline is in `before` phase (timeline.currentTime is 0)
        - animation is in `before` phase and its backward fill is activated if specified.
  2. **start <= scroll offset < end**
     -  timeline is in `active` phase (timeline.currentTime is calculated based on existing formula
     - animation phase and output is based on timeline's current time.
  3. **end >= scroll offset**  
      - timeline is in `after` phase (timeline.currenTime is timeRange)
      - animation is in `after` phase and its backward fill is activated if specified.

This has simplified the model quite a bit. But we are still considering "end scroll offset" as exclusive and at that position the timeline's is considered in after phase. So animations should have `fill:forwards` to have value in that position. This was considered bad by [Issue 19](https://github.com/WICG/scroll-animations/issues/19).

So I think we should add back that fix or add text to the spec asking people to use "fill: forward" for such animations.

**Comment by birtles** [comment]
> So I think we should add back that fix or add text to the spec asking people to use "fill: forward" for such animations.

Yes, I suspect adding back that fix might make sense.

**Comment by JTensai** [comment]
I am in the process of adding the exception back into the phase calculation for scroll timelines :)

**Comment by JTensai** [comment]
I believe the last remaining tasks for this issue are the following:

* Animations need to add the concept of `hold_phase` similar to `hold_time` it will make sure that effects behave correctly under circumstances such as pausing the animation and scrolling, or setting animation current time when the timeline is inactive.

* Update animation and animation effect [active time](https://drafts.csswg.org/web-animations-1/#active-time) and [phase](https://drafts.csswg.org/web-animations-1/#before-phase) calculation to take the timeline state (or hold phase) into account.

**Comment by flackr** [comment]
I believe with the addition of "progress timeline boundary" checks to [web-animations-2](https://drafts.csswg.org/web-animations-2/#animation-effect-phases-and-states) as well as not clamping the currentTime of view timelines #7432 that this issue is fixed. During the scroll or view timeline's active duration the effect is applied, and outside of it the fill of the effect is used.
