### ISSUE TITLE
[scroll-animations] Unclamped start and end element-based offsets are hard to work with

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#4327]
This issue is separating out a particular concern in https://github.com/WICG/scroll-animations/issues/51 where offsets can be outside the scrollable range which means that your animation will start partway through, a distance depending on the geometry of the page. In https://flackr.github.io/scroll-timeline/demo/parallax/unclamped.html you can see that this has made animations at the start and end of the scroller start / end partway through the animation.

I think as a developer this unclamped behavior is hard to reason about (i.e. I have to use a different parallax boundary for elements which start on screen from those which scroll into view - but that's dependent on the size of the viewport). This seems to eliminate some of the benefits of element-based offsets as the developer has to again worry about resizing / shifting of elements.

I think that we should clamp offsets outside of the scroll range (as in https://flackr.github.io/scroll-timeline/demo/parallax/ ) for better developer ergonomics.

**Comment by majido** [comment]
I agree that the unclamped behavior is hard to reason about and perhaps unexpected. 

Let's default to clamped behavior and in future it is easy to expose a method for authors to explicitly ask for unclamped behavior.

**Comment by majido** [comment]
The element-based offset has been added to the specification. And the current specified behavior is to [clamp the offset](https://github.com/w3c/csswg-drafts/blob/5a49df2060abefbc05c85d751429776c5e46edf0/scroll-animations-1/Overview.bs#L553). Considering this fixed.

> 1.  Clamp the value of <var>scroll offset</var> to be within the {{source}}'s
     scroll range.
