### ISSUE TITLE
[shape-outside] Rotated ellipse shape

### ISSUE THREAD

**Issue by caub** [w3c/csswg-drafts#433]
Is it possible to have a shape like this [rotated ellipse](https://peeterjoot.files.wordpress.com/2012/08/2drotationofellipsefig2.png) with shape-outside?

**Comment by astearns** [comment]
Not currently, but it should be something we address in future module levels.

**Comment by caub** [comment]
Ok, thanks, it should be also consistent with clip-path I guess (closing?)
