### ISSUE TITLE
[css-grid] Bad bikeshed formatting in https://drafts.csswg.org/css-grid/#grid-placement-slot

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4332]
Load https://drafts.csswg.org/css-grid/#grid-placement-slot, you will see

![css-grid-bad](https://user-images.githubusercontent.com/7477678/65200892-8cf73580-dac3-11e9-95aa-6a6705ccfa53.png)

I guess it should look like this:

![css-grid-good](https://user-images.githubusercontent.com/7477678/65200889-8963ae80-dac3-11e9-9e4a-454f585f1162.png)

It seems bikeshed gets confused by `''<<custom-ident>>-start''` and `''<<custom-ident>>-end''`

https://github.com/w3c/csswg-drafts/blob/1eced002d3eed4f549ff62bf08b3e3b03e7c9fc3/css-grid-1/Overview.bs#L2871

Not sure if this is a bikeshed problem or if it expects another syntax to be used in this case.

Cc @tabatkins

**Comment by tabatkins** [comment]
Well, you can't nest links like that, even *if* my parser wasn't slightly wrong in this situation.

Since what's desired is just the "looks like a value" styling, the double-single-quotes should be swapped out for `<css>...</css>`.

**Comment by Loirooriol** [comment]
> Well, you can't nest links like that

Maybe it could produce `<span class="css">` instead of a link, like it happens for `''1''`. But `<css>...</css>` works fine, thanks.
