### ISSUE TITLE
[mediaqueries-4] Unicode non-ascii for range comparison

### ISSUE THREAD

**Issue by ylafon** [w3c/csswg-drafts#4333]
Currently comparison is done using ascii `<=` and `>=`.
Could ≤ (U+2264) ≥ (U+2265) be accepted as well?

**Comment by tabatkins** [comment]
No. ^_^

CSS very intentionally avoids using non-ASCII for any official part of its syntax.

(We actually made a resolution on that several years ago, semi-jokingly. But for real, no non-ASCII.)
