### ISSUE TITLE
[css-grid] Spaces in grid-template-areas serialization

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4335]
See https://crbug.com/1005364 regarding

```js
element.style.gridTemplateAreas = '". . a b" ". .a b"';
element.style.gridTemplateAreas; // '". . a b" ". .a b"' in Firefox
                                 // '". . a b" ". . a b"' in Blink, Webkit
```

According to https://drafts.csswg.org/css-grid/#valdef-grid-template-areas-string

> Both the specified value and computed value of a `<string>` value of grid-template-areas serializes each null cell token as a single "." (U+002E FULL STOP) and each sequence of whitespace as a single space (U+0020 SPACE).

And by omission I guess that a lack of whitespace shouldn't be serialized as a space?

However, it seems confusing to me because the resolution in https://github.com/w3c/csswg-drafts/issues/3261 was against preserving the precise string when serializing `grid-template-areas`, and in favour of normalizing it. And according to https://drafts.csswg.org/css-grid/#valdef-grid-template-areas-string,

> A sequence of whitespace, representing nothing (do not produce a token).

So if whitespace doesn't produce tokens when parsing, it doesn't seem unreasonable for me to not track whether some optional space between tokens of different type was specified or not. Then the possibilities are always adding a space separator between tokens like `". . a b" ". . a b"`, or only doing it if necessary (between tokens of the same type) like `". .a b" ". .a b"`.

**Comment by mrego** [comment]
I don't have a strong opinion, but something like `". . a b" ". . a b"` looks less confusing to me than `". .a b" ". .a b"`.

**Comment by Loirooriol** [comment]
So I think the spec should say that each list of tokens is serialized into a `<string>` as follows:

 - Null tokens serialize as a single `.`
 - Named cell tokens serialize as a sequence of the code points in the name
 - The token serializations are concatenated using a single space ` ` as a separator.

**Comment by tabatkins** [comment]
Yes, I think all cells should be space-separated; relying on parsing quirks (the fact that `.foo` and `foo.` will always tokenize as two separate tokens) in serialization is generally bad.

**Comment by fantasai** [comment]
OK, we've specified the serialization of template strings more precisely:

> When serializing either the specified or computed value of a `<<string>>` value of 'grid-template-areas', each null cell token is serialized as a single "." (U+002E FULL STOP), and consecutive cell tokens are separated by a single space (U+0020 SPACE), with all other white space elided.

Agenda+ to confirm.
