### ISSUE TITLE
scroll offset values should use length-percentage type to allow calc()

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#4340]
The [`startScrollOffset` and `endScrollOffset`](https://wicg.github.io/scroll-animations/#dom-scrolltimeline-startscrolloffset) points on a scroll timeline are currently defined with the following CSS grammar:

    auto | <length> | <percentage>

That should be

    auto | <length-percentage>

in order to allow `calc()` expressions combining lengths and percentages, such as `calc(100% - 5rem)`.

Same for the [`<scroll-offset>`](https://wicg.github.io/scroll-animations/#typedef-scroll-offset) part of the `scroll()` function definition.

**Comment by majido** [comment]
Thanks for the suggestion. The above spec change should fix this.

Note we already have a [test](https://github.com/web-platform-tests/wpt/blob/master/scroll-animations/constructor.html#L108
) to verify length and percentages can be used in a calc for these offsets. 


/cc @andruud FYI.
