### ISSUE TITLE
New values for old properties 

### ISSUE THREAD

**Issue by bradkemper** [w3c/csswg-drafts#4342]
If I’m understanding it correctly, `animation-duration` would become much less meaningful most of the time when used with scroll animations. But what if it accepted lengths and percentages? 100% would mean it ended at the end of the scroll. 50em would mean it ended when it had scrolled 50ems past where it started. Negative values would measure from the end of the container instead of the beginning. 

`animation-delay` would also be a length or percentage that determined when the animation started. 0% would mean it starts as soon as scrolling began at the start edge. 100px would mean it starts when the 100px mark scrolls past the start edge. 

With these, you would no longer need startScrollOffset or endScrollOffset as values of animation-timeline. 

`animation-direction` loses meaning if the animation is based on the scroll position. So this could accept block, inline, horizontal, and vertical values. Then you don’t need ScrollDirection as a separate value in `scroll-animation`.

**Comment by flackr** [comment]
I don't know if it's a good idea to reinterpret animation-direction, as that seems quite different but I could see supporting lengths for duration being fairly intuitive. We've discussed similar ideas in #7044 and #7575.

**Comment by flackr** [comment]
I believe given the resolution to accept lengths for animation ranges in #7575 that this use case is covered.
