### ISSUE TITLE
`scroll()` grammar isn't written right to allow optionality

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4349]
Currently, the grammar for `scroll()` is:

```
scroll([element(<id-selector>)[, <scroll-direction>[, <scroll-offset>[, <scroll-offset>[, <time>[, <single-animation-fill-mode>]]]]]])
```

I presume this *wants* to make any amount of suffix optional. To achieve that, it needs a bunch of `?`s after each of the `]` at the end.

**Comment by majido** [comment]
Per #4338 we dropped function notation in favor of @timeline rule. So closing this issue since it is no longer applies.
