### ISSUE TITLE
writing-mode propagation from body to document element is annoying

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4357]
So in https://github.com/w3c/csswg-drafts/issues/3066 we resolved (hesitantly) that we'd propagate the `writing-mode` from the `<body>` element to the `<html>` element, at used value time.

As far as I can tell, WebKit and Blink propagate the writing-mode to the viewport, but not to the root, and the actual propagation to the root would be hard for them to implement it.

@aethanyc has an implementation of this in Firefox (https://phabricator.services.mozilla.com/D45481, https://bugzilla.mozilla.org/show_bug.cgi?id=1102175).

Handling correctly the edge cases like:

 * Inserting a new `<body>` element before the existing primary body.
 * Removing and handling the style changes on the primary `<body>` element.
 * Propagating the used writing mode to all the anonymous boxes generated by the `<html>` element, if it has `display: table`, for example.

Takes quite a bit of pretty unfortunate special-casing that in my (personal) opinion is not worth it.

Given that that resolution doesn't point to a clear path path to interop (since WebKit / Blink are quite unlikely to adopt it from what I can tell, since they don't store the writing mode separately from the style), can we instead not do any propagation (i.e., do what Gecko does right now), and maybe add warnings to the console when the `<body>`s writing-mode / direction / text-orientation differs from the `<html>`?

**Comment by emilio** [comment]
cc @fantasai @frivoal

**Comment by emilio** [comment]
cc @jfkthame too

**Comment by emilio** [comment]
So talked offline with @frivoal and noticed that Gecko does _some_ ([code](https://searchfox.org/mozilla-central/rev/7531325c8660cfa61bf71725f83501028178cbb9/layout/generic/nsGfxScrollFrame.cpp#5411)) of the propagation to the viewport, kinda, only for scrollbar directionality.

This was introduced by @dbaron in [bug 192767](https://bugzilla.mozilla.org/show_bug.cgi?id=192767).

So I guess the constraints are:

 1. We want to keep existing content working (at the very least orient the root scrollbars in the right direction when `<body>` is `rtl`).
 2. We want interop.
 3. We want to avoid orthogonal flows (though this may be less important than the previous two).

Both current Gecko behavior and the resolution in #3066 achieve (1) and (3). So if any of those are implementable by other engines I'm fine with either (not terribly happy about #3066, but...).

Gecko can also pretty easily I'd think just propagate the whole writing-mode to the viewport. That gives us (1) and (2) but not (3).

**Comment by emilio** [comment]
The Gecko code is pretty weird, too, it looks at the body even if the scrollbars come from the `<html>` element... That's fixable of course.

**Comment by atanassov** [comment]
Similar to `overflow` and `direction`, this is one of these quirks we'll have to keep for some time. We have it implemented in the current version of Edge and IE. FWIW we will come to implement it in the Chromium version of Edge if someone doesn't get it done ahead of us.

**Comment by emilio** [comment]
Direction and overflow are not propagated to the root. Overflow is only propagated to the viewport, and direction in Gecko isn't propagated at all as far as I can tell, modulo the quirk I described above about scrollbar directionality.

**Comment by atanassov** [comment]
Ugh, old habits - we have an element (hidden) for the viewport that we call "Root" in IE/Edge... hence I was confirming our behavior that matches Blink/Webkit and achieves 1 and 2 but not 3. 

I'll try to see what an implementation in Blink looks like before dismissing the possibility of it being landed there.

**Comment by emilio** [comment]
Reworded the title (s/root/document element/) to avoid confusion.

**Comment by lilles** [comment]
Blink is storing the writing-mode on its ComputedStyle. We discussed this in a Taxi in Fukuoka, and I think a feasible solution (avoiding a lot of if-branching in the code) was to add a used writing-mode value to the ComputedStyle object which would have the same value as the computed value in all cases but for the root element in the case where writing-mode for body differs from the root element. After updating styles for body, we would check if the body and root element differ in their computed styles, and if so clone the root ComputedStyle and set the used writing-mode to that of the body.

It doesn't sound all that crazy, but not all that great either.

**Comment by aethanyc** [comment]
For what is worth, Gecko's used [`WritingMode`](https://searchfox.org/mozilla-central/rev/01d1011ca4a460f751da030d455d35c267c3e210/layout/generic/WritingModes.h#133-145) is stored on frame tree (reneder tree) class, and is synthesized from CSS 'direction', 'writing-mode', and 'text-orientation' properties. So when Gecko propogates used `WritingMode` from body to html, it effectively propogates all the three properties.

**Comment by lilles** [comment]
For review: https://chromium-review.googlesource.com/c/chromium/src/+/1852786

**Comment by lilles** [comment]
Landed on Chromium master.

The change made these tests pass:

css/css-writing-modes/wm-propagation-002.html
css/css-writing-modes/wm-propagation-body-033.html
css/css-writing-modes/wm-propagation-body-037.html

I had to modify these tests (upstreamed to wpt) which were relying on the direction being different on the html and body elements:

css/css-writing-modes/normal-flow-overconstrained-vlr-005.xht
css/css-writing-modes/normal-flow-overconstrained-vrl-004.xht

**Comment by frivoal** [comment]
Fixes in Blink and Gecko have landed. Thanks to all involved. Closing.
