### ISSUE TITLE
[css-grid-2][css-grid] `grid-template-rows/columns` Computed / Resolved Values for 'subgrid' values

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4362]
CSS Grid specifies `grid-template-rows/columns` [computed values](https://drafts.csswg.org/css-grid/#computed-tracks) and [resolved values](https://drafts.csswg.org/css-grid/#resolved-track-list). Note however that this is only for _Track Listing_ values and thus does not include the extension for `subgrid` values made in [CSS Grid 2](https://drafts.csswg.org/css-grid-2/#subgrid-per-axis).

I can't find anything in either spec that defines how this is supposed to work for `subgrid` values and I think this needs to be explicitly defined somewhere. I'd suggest that CSS Grid 2 add a section/paragraph to say how the computed/resolved `subgrid` values works. I tend to think that similar rules should apply in this case, namely that `repeat()` and empty _line-names_ are preserved in the computed value, and that the resolved value contains expanded _line-names_ for the explicit grid (which in a subgridded axis is its entire span) with any excess lines in the computed value dropped. IOW, the same rules as for _Track Listing_ but without the track sizes (and prefixed with `subgrid`).

IIUC, the rules regarding _Track Listing_ were somewhat influenced by backward compatibility concerns with Microsoft's non-standard implementation. There are no such concerns for `subgrid` but it seems reasonable to use the same rules for the new values for consistency and to avoid confusion.

For example, assuming the subgrid's column axis spans 4 tracks, the _resolved value_ for `grid-template-columns: subgrid [a] repeat(auto-fill, [b]) [c]` is `subgrid [a] [b] [b] [b] [c]` and `grid-template-columns: subgrid [a] [a] [a] [a] repeat(auto-fill, [b]) [c] [c]` resolves to `subgrid [a] [a] [a] [a] [c]`.

**Comment by MatsPalmgren** [comment]
I forgot to ask about trailing lines with no names. If we have for example:
```css
  grid-column: span 4;
  grid-template-columns: subgrid [] [a];
```
should that resolve to `subgrid [] [a] [] [] []` or `subgrid [] [a]`?
The general principle of shortest possible serialization would suggest the latter, but I think there's also some utility in the former since it makes it possible for script to figure out how many tracks the subgrid spans (which might be hard to deduce otherwise - for example if line names were used to position the subgrid). (I have no personal preference, it's trivial to implement either.)

**Comment by tabatkins** [comment]
All right, we specified this in <http://dev.w3.org/csswg/css-grid-2#resolved-track-list>, let us know what you think or if anything can be improved?

**Comment by MatsPalmgren** [comment]
Interesting, it seems we have a different idea of what the `grid-template-rows/columns` _[used value](https://drafts.csswg.org/css-cascade-4/#used-value)_ is. The linked definition says:
> The **used value** is the result of taking the computed value and completing any remaining calculations to make it the absolute theoretical value used in the layout of the document.

As I read that, the _used value_ can only ever include names from the _computed value_, not any names from ancestors.  The algorithm for line name matching would then consult all the used values (from the subgrid and its ancestor grid(s)) in concert to resolve a name for item placement. (That's how it's implemented it in Gecko at least.  At no point do we have a data structure that holds all the names merged together.)

The spec text however, seems to suggest that the subgrid's _used value_ holds all the names merged together ("whether the names were explicitly created for the subgrid or adopted from the parent grid").

Including the names from ancestors is quite a bit more complicated to implement. Is this justified by a use case?  It also seems a bit weird that adopted names from ancestors should taint the round-trip value.

Personally, I'd rather not include the ancestor names, but I don't feel strongly about it.

If ancestor names are to be included, then the spec should probably define the merge order so that it can be implemented interoperably. E.g.
```css
.grid { grid-template-columns: [a] auto; }
.subgrid { grid-template-columns: subgrid [b]; }
```
Is the resolved value `subgrid [a b]` or `subgrid [b a]`?

**Comment by tabatkins** [comment]
> As I read that, the used value can only ever include names from the computed value, not any names from ancestors. 

I'm not sure how you're getting that from the description.

> Personally, I'd rather not include the ancestor names, but I don't feel strongly about it.

We thought you were asking for that, which is why we included it. ^_^ We can definitely remove it.

**Comment by MatsPalmgren** [comment]
> I'm not sure how you're getting that from the description.

The "taking the _computed value_ and completing any remaining calculations" part seems to imply only a fairly narrow set of calculations on the computed value itself, such as resolving `auto`/percentages to definite lengths etc.  It didn't occur to me that "remaining calculations" could include a fairly complex merging of used values from ancestors.

> We thought you were asking for that, which is why we included it. ^_^

Sorry for not being more precise.

> We can definitely remove it.

Great! Then I think we should narrow it down to just the local names.

**Comment by fantasai** [comment]
> It didn't occur to me that "remaining calculations" could include a fairly complex merging of used values from ancestors.

Well, the list of all the values including the ancestor values is what you are *using* to perform layout, so yes, the used value should include all of those. :)

> Great! Then I think we should narrow it down to just the local names.

No problem with that.

**Comment by fantasai** [comment]
OK, updated the spec to latest proposal for now. Agenda+ to check with the WG whether the resolved value should include or exclude line names adopted from the parent grid.

**Comment by MatsPalmgren** [comment]
>  the list of all the values including the ancestor values is what you are using to perform layout

Well, we don't include line names derived from `grid-template-areas` either (even from the same element). What we use in Layout is a set of data structures with line names from multiple sources: the computed values of `grid-template-rows/columns/areas` from the subgrid itself and its ancestors. It seems you're imagining a hypothetical _used value_ that doesn't actually exist while we're performing layout.

That said, `getComputedStyle` can of course be defined to return whatever we want in this case... even if it means synthesizing a _used value_ that never existed. I'm just saying that it's likely harder to implement (I haven't tried tho).

The spec looks fine to me now.

**Comment by Loirooriol** [comment]
What if the parent grid specifies the name `foo` for some line, and the subgrid specifies the local names `foo` and `bar` to that same line?

> a list representing each of its lines as a line name set of all the line’s names excluding those adopted from the parent grid

Does "excluding" mean that `foo` won't be included because it's adopted from the parent grid, even if it's also local? This seems undesirable. So instead of "all the line’s names excluding those adopted from the parent grid" the spec could say "the local line names specified on the subgrid" or something.
