### ISSUE TITLE
[css-values-4] Issue with calculation simplification and math functions

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#4372]
[Current spec](https://drafts.csswg.org/css-values-4/#math-function-simplify-a-calculation) says:

> To simplify a calculation:
> ...
> 2. Resolve all multiplications and divisions.
> ...

However, consider the case where one of the operands is a math function, e.g.,

`min(10px, 1em) * 2`

In general, multiplications and divisions don't seem resolvable in this case. While we can "merge" the multiplicative factor into a comparison function, this trick doesn't work for other functions.

As a result, the following requirement is also unachievable:

> The result must be a summation of unique units and/or math functions.

We might still end up with a complicated expression with math functions as leaf nodes.

**Comment by tabatkins** [comment]
Yup, that text is pre-functions, and needs to be rewritten substantially. I've got this partially fixed in one of my local repos, and will prioritize finishing it up for you.

**Comment by tabatkins** [comment]
Done. (Missed this one in my closing-spree last week.)
