### ISSUE TITLE
[css21][css-grid][css-flexbox][css-align] Baselines of empty boxes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#439]
Afaict, the CSS2.1 spec does not say what to do with the baseline alignment of empty inline tables. IE and Chrome use the bottom margin edge. Firefox uses the bottom border edge.
  http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%3ETest%20%3Cdiv%20style%3D%22display%3A%20inline-table%3B%20background%3A%20blue%3B%20width%3A%2010px%3B%20height%3A%2010px%3B%20margin%3A%2010px%3B%20border%3A%20solid%20orange%22%3E%3C%2Fdiv%3E

The Grid and Flexbox specs currently say to use the bottom content edge for empty grid/flex containers.

We should spec something consistent for all three.

**Comment by fantasai** [comment]
Half-baked Proposal: State that such boxes have no baseline, and one is synthesized by the context--using the margin box for inline baseline-alignment, and the border box (as we just resolved) for flex/grid baseline-alignment.

**Comment by atanassov** [comment]
CSSWG Resolution: Have grid and flexbox keep saying that empty boxes have no baseline and they're synthesized with bottom border edge.

https://lists.w3.org/Archives/Public/www-style/2016Sep/0028.html

**Comment by gsnedders** [comment]
@fantasai this is only partly fixed, right? it doesn't look like we ever resolved anything about inline-table.

**Comment by gsnedders** [comment]
Also, to note:

> Afaict, the CSS2.1 spec does not say what to do with the baseline alignment of empty inline tables. IE and Chrome use the bottom margin edge. Firefox uses the bottom border edge.

Chrome's behaviour at least is more complicated than that, c.f.:

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/8159

Chrome clearly computes a baseline for the row, and then sets the baseline of the table based on that. (Note additionally that AFAICT CSS2 doesn't say what the baseline of an empty table-row is.)
