### ISSUE TITLE
[css-pseudo-4] clarify relation of floats to whether or not a ::first-letter exists

### ISSUE THREAD

**Issue by marrus-sh** [w3c/csswg-drafts#4392]
[CSS Pseudo-Elements Module Level 4](https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo) states:

> The ::first-letter pseudo-element represents the first typographic letter unit [CSS3TEXT] on the first formatted line of its originating element, if it is not preceded by any other content (such as images or inline tables) on its line.

To me it is not clear whether floats count as “other content […] on its line”. In particular the following case seems ambiguous:

```html
<style>
p::first-line { color: blue }
p::first-letter { color: red }
</style>
<p><span style="float:right">?</span>Foo</p>
```

In Firefox, `::first-line` matches “Foo” (so it *is* the first formatted line) but `::first-letter` does not match “F”.

(Firefox also exhibits this behaviour for absolutely-positioned elements, which seems more clearly a bug. Chrome, on the other hand, marks “F” as red when preceded by either a float or an absolutely-positioned element.)

Since a float is arguably not “on a line” it would be nice if it were clarified which is normative behaviour…

1. If floats are not “on the line”, then this makes `::first-letter` more clearly defined in terms of the line box, but gets a little paradoxically confusing because `::first-letter` can *itself* be floated (making it no longer actually the first letter “on its line” and hypothetically introducing a *new* first letter).

2. If floats *are* “on the line”, then this makes a floated `::first-letter` more consistent (it has not left the line) but makes the definition of what exactly the line *is* more confusing.

(Note that `initial-letters` relies on some implicit expectations about where `::first-letter` appears; [CSS Inline Layout Module Level 3](https://drafts.csswg.org/css-inline/#first-most-inline-level) states:

> Specifically, initial-letters applies to any inline-level box—including any such ::first-letter or ::marker box—that is the first child of its parent box[…]

Does a float prevent `::first-letter` from being the first child of its parent box? Or is its parent box in this context the line box, which the float does not belong to? Thankfully, `initial-letters` does not apply to a `::first-letter` which is *itself* floated regardless, as it is not an inline-level box.)

**Comment by faceless2** [comment]
Not an official response, but below is how we've implemented it and (as I recall) it it matched our comparative testing with the browsers, with regard to first-letter at least.

Floats are not classed as being "on a line", so are as transparent as absolutes. The selector applies to the incoming node tree, so there's no ambiguity if, once the selector has matched and been applied, the box it generates is also floated.

The `initial-letters` bit you refer to _does_ refer to the box tree, but (with the restriction you noted, that it cannot apply to a first-letter which is _itself_ floated) it's effectively the same thing, provided that - as stated above - floats are not classed as being "on a line".

**Comment by fantasai** [comment]
Agree with @faceless2, floats are not on a line, they're out of flow. Chrome's behavior is correct, and Firefox admits it has a bug there.

The initial-letter text you quote pertains only to inline-level boxes, and floats are not inline-level.

We do need a clarification about floated ::first-letter, which is a weird case, though.

**Comment by fantasai** [comment]
OK, added a clarification that styling ::first-letter can't change what is the ::first-letter.

> User agents may apply other properties as well. <ins>However, in no case may the application of such unlisted properties to ::first-letter change what first-letter text is represented by that ::first-letter.</ins>

Also ripped out some of the old terrible examples and rewrote most of the section.

@marrus-sh Let me know if this works for you, or if you need something else!

**Comment by marrus-sh** [comment]
that works for me, thanks!

**Comment by fantasai** [comment]
Great, closing out!
