### ISSUE TITLE
[css-pseudo] Properties applicable to Highlights

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4401]
The [css-pseudo ED](https://drafts.csswg.org/css-pseudo/#highlight-styling) currently says:

> The highlight pseudo-elements can only be styled by a limited set of properties that do not affect layout. 
>
> … 
>
> ISSUE 1 
>  Are there any other properties that should be included here?

Since none of the `background` sub-properties affect layout, it seems logical to allow them all, not just `background-color`.

Unlike `border`, `outline` and its sub-properties do not affect layout and should therefore be supported as well.

Iʼm pretty sure that most [fill and stroke](https://drafts.fxtf.org/fill-stroke-3/) properties also qualify; theyʼre limited to `stroke-color`, `fill-color` and `stroke-width` at the moment.

**Comment by fantasai** [comment]
background other than background-color are dependent on the size of the box also, which is why they aren't allowed

**Comment by Crissov** [comment]
Okay, then at least “that so not affect layout” would need some rewording (unless my English skills are failing me here).

**Comment by Dalzhim** [comment]
Could the `outline-*` family of properties be included as well?

**Comment by fantasai** [comment]
@Dalzhim Yes, see https://www.w3.org/TR/css-text-decor-4/

**Comment by fantasai** [comment]
@Crissov That information was in the source code because it seemed like TMI for the spec, but since you requested it's now in the spec. Lmk if that works for you.
