### ISSUE TITLE
[css-text-3] treat all-neutral lines same as empty ones for plaintext alignment

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4405]
[note added 9 Oct @15:35 by @r12a 
For an overview of the thread leading up to this [see here](https://www.w3.org/Mail/flatten/index?subject=First+strong+on+strings+surrounded+by+isolate+controls&list=public-i18n-bidi)]

From Aharon Lanin https://lists.w3.org/Archives/Public/public-i18n-bidi/2016JulSep/0028.html

> I do not think that there is a problem with the directionality algorithm. Aside from alignment, it makes no difference whether that isolate paragraph is displayed as LTR overall or RTL overall. And for much more important and common cases of all-neutral text - phone numbers and, to a smaller extent, dates, times, and signed numbers - its being LTR by default is extremely important.
>
> I do think that there is a problem with the definition of start alignment, which is not controlled by Unicode, but by various other specs, such as CSS. The problem affects the alignment of all-neutral paragraphs generally, like the examples cited above, not just the corner case of an isolate. Start alignment is generally defined as "left" for an LTR paragraph, and "right" for an RTL paragraph, and this means that an all-neutral paragraph, which is LTR by the UBA, is left-aligned - even if the alignment outside that paragraph is right. This makes the all-neutral paragraph needlessly different from its surroundings and usually looking pretty bad.
>
> The solution is to make start alignment match the alignment outside the paragraph if the paragraph's directionality is determined from its content and its content is all-neutral.
>
> In the context of CSS, the relevant spec is that of the start and end edges of a line box whose containing block has ‘unicode-bidi: plaintext’ (https://www.w3.org/TR/css-text-3/#bidi-linebox). It already makes an exception for an empty line box, which "takes its inline base direction from the preceding line box (if any), or, if this is the first line box in the containing block, then from the ‘direction’ property of the containing block." I think that this exception should be broadened to an all-neutral line box.

**Comment by fantasai** [comment]
Formal minutes of the 24 January 2020 discussion: https://lists.w3.org/Archives/Public/www-style/2020Feb/0019.html

**Comment by fantasai** [comment]
Replied to the original post on public-i18n-bidi here: https://lists.w3.org/Archives/Public/public-i18n-bidi/2020AprJun/0000.html

**Comment by amire80** [comment]
Just a little comment for now; maybe I'll have something deeper to say later.

There is at least one writing system in which phone numbers are not written from left to right: [N'Ko](https://en.wikipedia.org/wiki/N%27Ko_script). It is used increasingly in digital communication; for an example, see [this New York Times story from 2011](https://www.nytimes.com/2011/12/11/magazine/everyone-speaks-text-message.html), and since then it grew even more.

So, while you should assume that phone numbers, zip codes, credit card numbers, etc. are written from left to right in _most_ languages, you cannot assume it for _all_ languages. Perhaps it's enough to make this exception just for N'Ko (although maybe there are other languages that have such a feature, I'm not 100% sure).

**Comment by fantasai** [comment]
@amire80 N'Ko would need to encode its numbers under an RTL override, as the Unicode Bidi Algorithm doesn't handle language-specific alterations like that. But this bug is not about changing the ordering of characters, it's only about alignment.

**Comment by amire80** [comment]
AFAIK, N'Ko numbers don't need RTL override, but works automatically right to left. And this language does need right-hand alignment for numbers.

**Comment by faceless2** [comment]
N'Ko digits are strong RTL, so they should be reordered correctly without any special handling.

https://www.compart.com/en/unicode/U+07C0

**Comment by fantasai** [comment]
Aharon's reply: https://lists.w3.org/Archives/Public/public-i18n-bidi/2020JulSep/0000.html

**Comment by fantasai** [comment]
Interest to hear from @jfkthame / @litherum / @kojiishi .

Specwise, I think this means we'd classify lines as either rtl, ltr, or neutral, where neutral means LTR for reordering and "match previous line" for alignment.
