### ISSUE TITLE
[css-grid-2] Subsetting grid-template-areas in subgrids

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4411]
Pulling out one of @MatsPalmgren's issues from https://github.com/w3c/csswg-drafts/issues/2564

<hr>

**@MatsPalmgren wrote:**

ISSUE 4: line name matching for `grid-template-areas` that are (partly) outside of the bounds of the subgrid needs to be defined

The way I solved this is to view the areas themselves as sliced by the subgrid and then generate [implicit area names](https://drafts.csswg.org/css-grid/#implicit-named-line) for that slice, for example:

```html
<div style='display:grid; grid-template-areas: "a a a a a a a a a a"'>
  <div style="display:grid; grid:auto/subgrid; grid-column: 6 / span 5">
    <x style="grid-column: a">x</x>
  </div>
</div>
```

Resolves to 1 / 6, because the subgrid sees a `a-start` line at its line 1 and `a-end` at line 11.  That is, the areas in ancestor grids that have an edge outside the subgrid generates its corresponding implicit area name at the subgrid edge instead.  This matters because for example:

```html
<div style='display:grid; grid-template-areas: "a a a a a a a a a a"'>
  <div style="display:grid; grid:auto/subgrid [a-start] [a-start]; grid-column: 6 / span 5">
    <x style="grid-column: a-start 2">x</x>
  </div>
</div>
```
Resolves to 2 / 3, because the `a-start` of the parent grid coincides with the explicit `a-start` at line 1 in the subgrid.

Note that implicit area names are still generated for all grids though, so for example:

```html
<div style="display:grid; grid-template-areas: '. . . . . . a a a a'">
  <div style="display:grid; grid:auto/subgrid; grid-column:2/-1; grid-template-areas: '. . a'">
    <div style="display:grid; grid:auto/subgrid; grid-column:2/-1; grid-template-areas: '. . a'">
      <div style="display:grid; grid:auto/subgrid; grid-column:2/-1; grid-template-areas: '. . a'">
        <x style="grid-column: a-start 4">x</x>
      </div>
    </div>
  </div>
</div>
```

have `a-start` lines at line 1 (from the outermost subgrid), line 2, line 3 (from the innermost subgrid) and line 4 (from the root grid) so `a-start 4` is resolved as 4 in this case.

<hr>

**@fantasai replied:**

ISSUE 4: This is an interesting case, I hadn't really thought about it. Named areas don't really "exist" in Grid; they're just a shorthand syntax for adding *-start and *-end line names to the grid.  (Note that you can use `grid-area: a` solely by manually adding `a-start`/`a-end` lines to the grid, avoiding `grid-template-areas` entirely.) So I would have expected that we'd just inherit the -start/-end line names that happen to cross into the subgrid, without doing anything special.

If we resolve by simply ignoring the line names outside the subgrid’s spanning area, then the -start/-end lines outside the subgrid area would just get dropped. The item would then position against the subgrid's fake-implicit grid lines, and subsequently get clamped to the actual bounds of the subgrid, yielding the same behavior you propose.

<hr>

**@MatsPalmgren replied:**

> ISSUE 4: [...] Named areas don't really "exist" in Grid; they're just a shorthand syntax for adding *-start and *-end line names to the grid.

The names in `grid-template-areas` specifies which **tracks** are covered by an area, the `-start/-end` lines are byproduct of that...

>  (Note that you can use grid-area: a solely by manually adding a-start/a-end lines to the grid, avoiding grid-template-areas entirely.)

Indeed, and in a non-subgrid world I would agree that they are entirely equivalent.  However, in a subgrid world, a subgridded axis "shares" the tracks with its parent grid so it seems logical to me that the names in the parent `grid-template-areas` are shared by the subgrid for the slice of the area that the subgrid covers.  Here's a simpler example:
```html
<div style='display:grid; grid-template-areas: "a a a a a"'>
  <div style="display:grid; grid:auto/subgrid; grid-column:2/span 3">
    <x style="grid-column:a-start">x</x>
  </div>
</div>
```
I think the `<x>` item should start at line 1 in the subgrid, because the subgrid's first track is in the "a" area (i.e. the second track in the parent grid) and thus it sees an `a-start` at line 1 since the "a" area, from its perspective, starts there.  You're suggesting that since the parent's `a-start` is outside the subgrid it's invisible, hence it resolves the same as "`grid-column:foo`" which gives the result `3 / 4`, so it doesn't give the same result. It seems we agree that `a-start` should match the first line in the subgrid though. I just don't understand how you get that result with your explanation. Could you elaborate?

**Comment by fantasai** [comment]
> I just don't understand how you get that result with your explanation. Could you elaborate?

@MatsPalmgren I think I was misinterpreting the search direction, thought that `grid-*-start` would look to the implicit lines before line 1 if it did not find the specified named line. It's doesn't seem to be particularly explicit in the Grid spec, but it seems like it would actually only search the implicit lines after the last line, so my suggestion wouldn't work.

I think we have four options here:

- A) Define that a subgrid subsets its parent grid’s template based on what part of it is covered, and ensures that its edges provide the requisite -start/-end lines at its edges. (This makes templates more of a "thing", rather than a mere translation into line names that can subsequently be forgotten.)
- B) Define that the `grid-*-start` property searches the implicit lines before the first line instead of the lines after the last line if a specified line name is missing, similar to how `span foo` searches in opposite directions based on whether its a `grid-*-start` or `grid-*-end` value.
- C) Define that, while implicit lines have most names in the infinite space of possible names, only lines before the first line also have names ending in -start, and only lines after the last line have names ending in -end.
- D) Don't handle template subsetting; the cases you describe will be a type of error.

B & C imply changes to Grid Level 1 behavior, but really only to error cases (missing line names).

**Comment by mirisuzanne** [comment]
I would have expected an A-variation that is still based on line-names rather than tracking areas as a "thing". If parent line names (including `*-start`, `*-end`, and arbitrary names) are considered "available" to the subgrid, but clamped to the subgrid edges – that doesn't require tracking the template area, only the lines that are generated. Those line-names would stack-up at the edge of the subgrid if they are defined outside the available space.

I made [a pen of the demos above](https://codepen.io/mirisuzanne/pen/ZEEbxro) if anyone else finds a visual helpful…

**Comment by rachelandrew** [comment]
Behavior A makes the most sense to me, it seems easily explained to authors and I think will be logical to anyone encountering grid and subgrid for the first time. If you place something into an area partly covered by a subgrid it then goes into the part that is available, and `foo-start` and `foo-end` will then map to the bounds of that area when used to place things in the subgrid.

I've been playing around with a bunch of naming usecases recently and I can't think of good use cases for the other behaviors at the moment. I think template subsetting as described in A could be useful though.

**Comment by fantasai** [comment]
@rachelandrew A, B, and C will all have that effect. The question is how we want to get there.

@mirisuzanne OK, so that's a new option :) So we've got

- A) Define that a subgrid subsets its parent grid’s template based on what part of it is covered, and ensures that its edges provide the requisite -start/-end lines at its edges. (This makes templates more of a "thing", rather than a mere translation into line names that can subsequently be forgotten.)
- B) Define that the `grid-*-start` property searches the implicit lines before the first line instead of the lines after the last line if a specified line name is missing, similar to how `span foo` searches in opposite directions based on whether its a `grid-*-start` or `grid-*-end` value.
- C) Define that, while implicit lines have most names in the infinite space of possible names, only lines before the first line also have names ending in -start, and only lines after the last line have names ending in -end.
- D) Define that all line names from the parent grid that are before the subgrid are assigned to the subgrid's first line, and all line names after the subgrid are assigned to the last line.
- E) Don't handle template subsetting; the cases you describe will be a type of error.

**Comment by rachelandrew** [comment]
what I was saying was that I don't see use cases for the other behaviors which seem more complex to me, but maybe they aren't in reality.

**Comment by fantasai** [comment]
@rachelandrew Well, for the grids that effectively define grid areas using -start/-end lines rather than an ascii template, the other options would let those work equivalently. Which is probably a concrete benefit to B/C/D vs A. (The other one being that templates have up til now been just a convenient way to assign those line names, not an entity of themselves, so would maybe make sense to continue that attitude.)

@mirisuzanne One concern with your approach, suppose the author is repeating the pattern `[outer-start] [inner-start] [inner-end] [outer-end]` throughout a grid, each set representing a "column" of content. If the subgrid takes up, say, four columns but there are six columns in the parent grid, then the first and last lines of the subgrid gets assigned all four names instead of just `[outer-start]`, which is probably not what we want since the first item positioned to `inner-start` will start at what the author thinks of as an `outer-start` line.

**Comment by mrego** [comment]
I've been checking this thing and I believe I like C, however I'm worried about the compatibility risk and if we're going to break websites doing this change. Maybe we should add a use counter, to check if people are using random line names to place elements or not.
A safer approach would be go with B, and eventually move to C if the use counter is low.

One thing I don't like about current implementation is that these 2 cases are not identical:
```html
<div style="display: inline-grid; border: solid thick;
            grid-auto-rows: 50px;
            grid-template-columns: repeat(5, 50px);
            grid-template-areas: 'a a a a a';">
  <x style="grid-column: a; background: magenta;">i1</x>
  <div style="display: grid;
              grid: auto / subgrid;
              grid-column: 3 / span 3;">
    <x style="grid-column: a-start; background: cyan;">i2</x>
  </div>
  <div style="display: grid;
              grid: auto / subgrid;
              grid-column: 3 / span 3;">
    <x style="grid-column: a; background: yellow;">i3</x>
  </div>
</div>

<hr>

<div style="display: inline-grid; border: solid thick;
            grid-auto-rows: 50px;
            grid-template-columns: [a-start] repeat(5, 50px) [a-end];">
  <x style="grid-column: a; background: magenta;">i1</x>
  <div style="display: grid;
              grid: auto / subgrid;
              grid-column: 3 / span 3;">
    <x style="grid-column: a-start; background: cyan;">i2</x>
  </div>
  <div style="display: grid;
              grid: auto / subgrid;
              grid-column: 3 / span 3;">
    <x style="grid-column: a; background: yellow;">i3</x>
  </div>
</div>
```

![Output in Firefox nightly 71.0a1](https://user-images.githubusercontent.com/11602/66838742-81354c80-ef65-11e9-8303-e9820f7faaff.png)

I'd expect both render the same and work, like it happens for the first one, but the 2nd one is doing something different.

**Comment by MatsPalmgren** [comment]
@fantasai 
> A, B, and C will all have that effect.

They behave slightly differently though. For example:
```css
.grid { grid-template-areas: "a a a a a a a a a a"; }
.subgrid { grid-template-columns: subgrid [a-start];  grid-column: 3 / span 5; }
.item { grid-column: a-start 2; }
```
With A, the subgrid's explicit `a-start` is the same line as its implicit `a-start` from the `a` area, so `a-start 2` doesn't match an explicit line and the item ends up in the last track of the subgrid. With B, no explicit line match either but now we match the implicit line before the subgrid, which we'll clamp to line 1 in the subgrid.

B has the effect that for example `x 3` can be before `x 2`, which seems confusing:
```css
grid-template-columns: [x] 0 [x];
```

C needs to define what a missing `-start/-end` lines resolves to.  The way it works now is that all implicit lines matches all names so there are never any matching errors really (which is an easy and consistent model to understand IMO).  What does `a-start 30` resolve to in the first example above if lines after the subgrid's last line don't match `-start` names?

D will also have some surprising effects due to collapsing all names to the edge line. e.g.
```css
.grid { grid-template-columns: [a] 0 [a] 0 [a] 0 [a]; }
.subgrid { grid-template-columns: subgrid;  grid-column: 10 / span 5; }
```
which is the subgrid is equivalent to `subgrid [a]` which means `a 2` etc will behave strangely. I also don't like that _explicit_ line names outside the subgrid can affect the matching inside the subgrid. Insulating the subgrid from unrelated line name changes seems like a good property to have.

E: I like this option more the more I think about it. It's a very simple model.

(Was D supposed to be what @mirisuzanne suggested? If so, I understood her suggestion differently. She only said that "A-variation that is still based on line-names rather than tracking areas" so I don't think she meant to include **all** line names (as in D), but only implicit ones associated with the `grid-template-areas`. I might have misunderstood though.)

**Comment by MatsPalmgren** [comment]
So, in the order I prefer the alternatives:

* E: This is a very simple model - it should be easy to implement and teach. It doesn't require changes to Grid 1 and it insulates the subgrid from all line names that are outside its extent.

* A: (either area-based, as currently implemented in Gecko, or a more line-based version as @mirisuzanne suggested) This is a somewhat more complicated model, but still fairly simple to implement and teach. It insulates the subgrid from **explicit** line names in the parent grid that are outside its extent.

* D: Conceptually a simple model but I think it's a lot harder to implement than it sounds.  Also, collapsing all outside names to the subgrid's edges leads to rather weird behavior that doesn't seem very useful. Arbitrary line name changes outside the subgrid can affect matching inside the subgrid which seems undesirable.

* B and C: These are more complicated models to understand and have weird effects.  They also aren't compatible with Grid 1, which is interoperably implemented and shipped by multiple UAs for several years (possible web-compat fallout, implementation regressions, etc). I'm fairly strongly opposed to these options since they are invasive and thus disproportionate to solve the problem at hand.

(I'll take a stab at implementing E to see what falls out and report back...)

**Comment by MatsPalmgren** [comment]
@mrego Yes, you're making a good observation. We only implemented the matching for **implicit line names** associated with explicit areas (i.e. `grid-template-areas`), not for implicit areas in the parent grid.  This is indeed slightly asymmetric.

**Comment by MatsPalmgren** [comment]
So, I implemented E and as expected it's fairly straight-forward (in our case just removing the code that currently implements A). I think E can be summarized as: _explicit_ line names in ancestors are visible to the subgrid on the lines it shares with its ancestors; other ancestor line names are invisible.

**Comment by tabatkins** [comment]
Ah, so if the subgrid *fully* overlaps a parent's grid area, the subgrid's children still don't see those lines?

That's a consistent position I can get behind.

**Comment by MatsPalmgren** [comment]
Right, `grid-template-areas`  creates _implicit_ named lines which (for option E) effectively means it can't affect any subgrids at all. (The subgrid itself can still use `grid-template-areas` locally for its items of course.)

**Comment by Dan503** [comment]
> Ah, so if the subgrid fully overlaps a parent's grid area, the subgrid's children still don't see those lines?

I think that is unintuitive and not particularly useful.

The way I imagine it working is that the sub-grid kind of crops the parent grid areas.

```css
.parent-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  grud-template-areas: "a a a a";
}

.sub-grid {
  display: grid;
  grid-template-columns: subgrid;
  grid-column: 2 / 4;
}

.sub-grid-cell {
  grid-area: a;
}
```

```
Parent grid:  |a-start     |             |               |       a-end |

Sub grid:     |            |a-start      |          a-end|             |
```

**Comment by MatsPalmgren** [comment]
> The way I imagine it working is that the sub-grid kind of crops the parent grid areas

FYI, that's basically option A) above or some variation of it.

**Comment by tabatkins** [comment]
Okay, so I think we've got two consistent proposals I'm happy to live with:

1. Slightly reify grid-template-areas, and exclude all template-created line names from inheriting into subgrids.
    * This means that *no* parent areas are usable in a subgrid, if they were created by grid-template-areas.
    * If an author manually creates an area by specifying foo-start/end lines in the parent grid, they will inherit in and be usable if both the start and end lines overlap the subgrid; a partially-overlapping area will still give you the broken results that the current spec gives you for all partially-overlapping areas.
2. Slightly reify grid-template-areas, and add line names of areas that *partially* overlap the subgrid to the start/end of the subgrid, effectively subsetting the grid area into the subgrid.
    * This means that *all* parent areas are usable in a subgrid. 
    * Just like (1), if an author manually creates areas by specifying foo-start/end lines, they'll only be usable if they fully overlap the grid area; they won't get the "subsetting" effect that template-created areas get.

The other proposals, while attractive in some ways, have too many problems to be seriously considered imo.
