### ISSUE TITLE
[selectors] Make sure :is()/:not()/etc work well with pseudo-elements

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4417]
In the past I've resisted things like `.foo:is(.bar, ::before)`, because the ::before part is technically changing the subject of the compound selector, something no other selector can do.

But this just leaves a functionality gap, since pseudo-elements don't have a combinator dedicated to them to allow matching plainly. Selector syntax is awkwardly designed around pseudo-elements, but we're stuck with it, and should accept that pseudo-elements are part of the compound selector grammar and are allowed to change the subject in a real way.

Thus we should make sure that :not()/etc work properly with them too.

(There's no reason to use :not() with any of the current pseudos, but `::part(foo):not(::part(bar))` makes sense and is useful.)

**Comment by Loirooriol** [comment]
#2284 resolved to defer this to L5

**Comment by tabatkins** [comment]
Ah, thanks, this is a dupe then. (I'll copy over my message.)
