### ISSUE TITLE
[css-text-3] Bidi and pre-wrap end of line spaces

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4422]
This is split form https://github.com/w3c/csswg-drafts/issues/4308: that one is about collapsible spaces, but there seems to be a similar issue for pre-wrap spaces, where the interaction of bidi and of the handing of end-of-line spaces is poorly defined and not interoperable.

https://jsbin.com/rixamas/edit?html,css,output

<table>
<thead><tr><th  colspan=4>Unwrapped</th></tr></thead>
<tbody><tr><td  colspan=4><img src="https://user-images.githubusercontent.com/113268/66836307-0fc4c080-ef9c-11e9-9242-4f7243056395.png" alt="Unwrapped rendering"></td>
<thead><tr><th>Chrome</th><th>Firefox</th><th>Safari</th><th>Edge 18</th></tr></thead>
<tbody><tr><td><img src="https://user-images.githubusercontent.com/113268/66836378-2d922580-ef9c-11e9-8f3c-71813657bbb6.png" alt="Chrome Rendering"></td>
<td><img src="https://user-images.githubusercontent.com/113268/66836415-3a167e00-ef9c-11e9-9abd-6bc06f0a7825.png" alt="Firefox Rendering"></td>
<td><img src="https://user-images.githubusercontent.com/113268/66836434-46024000-ef9c-11e9-9084-c07bf33afe23.png" alt="Safari Rendering"></td>
<td><img src="https://user-images.githubusercontent.com/113268/66836460-52869880-ef9c-11e9-8097-89306a1abf4a.png" alt="Edge Rendering"></td></table>

I agree  mostly with Edge (except for the lack of hanging of the last space) <s>or safari (except they clip the spaces they hang, which the spec does allow)</s> (edit: actually, I failed to notice at first, but safari has a bug in the 7ch case). In other words, here's what I think we should do:

<img width="218" alt="should" src="https://user-images.githubusercontent.com/113268/66836500-63370e80-ef9c-11e9-879f-091d4d26c6d9.png">

**Comment by frivoal** [comment]
Made a pull request (https://github.com/w3c/csswg-drafts/pull/4429) to try and define this behavior. Feedback welcome.

**Comment by frivoal** [comment]
More details about my logic:
1. Firefox's behavior at 6ch is bad because a `pre-wrap` space that should be in the middle of the line disappears (the green one)
2. Chrome's behavior at 6ch is bad because text overflows (`ا`) even though there are wrapping opportunities on the line
3. Safari and Edge are both good at 6ch.
4. Safari is broken at 7ch because it fails to reorder the green space
5. Edge, Chrome, and Firefox are all good at 7ch.
6. Safari, Chrome, and Firefox's behaviors are all acceptable at 8ch, the difference is that Safari and Firefox chose to collapse the advance width of the hanging space that overflows (the yellow one), as allowed but not required by the last sentence of 4.1.3 point 4 bullet 2.
7. Edge's behavior at 7ch is bad because it wraps an end-of-line space that ought to hang (the yellow one), as per 4.1.3 point 4 bullet 2.
8. All browsers are good at 8ch.

Most of the criteria underpinning that logic were already in the spec, but not all. The proposed PR adds those of 1. and 2.

**Comment by kojiishi** [comment]
I think we should match to UAX#9. In 3.4 Reordering Resolved Levels, the rule [L1] defines how to handle trailing spaces.

[L1]: http://unicode.org/reports/tr9/#L1

**Comment by jfkthame** [comment]
> I think we should match to UAX#9. In 3.4 Reordering Resolved Levels, the rule [L1](http://unicode.org/reports/tr9/#L1) defines how to handle trailing spaces.

This seems to imply that the Safari result is correct for 7ch ("trailing whitespace will appear at the visual end of the line", which means the green space should remain at the right-hand edge, not be reordered adjacent to the red one). But then ISTM the Firefox result for 6ch makes sense: the line-break is the same as the 7ch case, but the trailing green space (at the right-hand edge) is allowed to hang or be suppressed.

**Comment by kojiishi** [comment]
Blink is likely to fail, we haven't implemented L1 yet. Wanted to do in LayoutNG but faced a few difficulties. Last I checked, probably 3-4 years ago, Gecko didn't implement L1 either. It'a great surprise WebKit implements L1, great work @litherum.

**Comment by fantasai** [comment]
OK, so, I think we should accept Florian's PR https://github.com/w3c/csswg-drafts/pull/4429/files because it's a good clarification. Otherwise it seems like we don't have to do anything here, other than maybe add tests for UAX9L1.
