### ISSUE TITLE
[css-tables-3] Empty row-group height clarification

### ISSUE THREAD

**Issue by atotic** [w3c/csswg-drafts#4423]
Asking for spec clarification, because implementations disagree:
Does empty row group get sized to 0,0?

FF does this.
Chrome/Safari give first row group dimensions of an empty cell.
Edge adds border-spacing inline size to row-group width.

Got a w.p.t testcase coming up, I think it is a definite, not a tentative.

    <x-table style="border-spacing: 10px; background: yellow; position: relative;border: 40px solid green; border-width: 20px 40px">
        <x-thead></x-thead>
        <x-tbody></x-tbody>
        <x-tbody></x-tbody>
        <x-tbody></x-tbody>
        <x-tfoot></x-tfoot>
    </x-table>

**Comment by FremyCompany** [comment]
Your example seem to be a case of https://www.w3.org/TR/css-tables-3/#empty-table
Is the current text satisfactory to you?

**Comment by FremyCompany** [comment]
And if your question is what getBoundingClientRect returns, I would assume that it returns 0 width 0 height but the correct position for those groups (they do not span any row/column).

**Comment by atotic** [comment]
As part of my work on understanding height redistribution of tables, I continued investigating treatment of empty TR/TBODY* elements in #4418. The results of investigation are now folded into #4418 , so I will close this issue.

What I've found is that 0-height elements do not grow, unless they are the only element that can grow.
