### ISSUE TITLE
[css-rhythm][css-values][css-cascade] length-precision for Actual Values

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4440]
- [CSS Rhythmic Sizing](https://drafts.csswg.org/css-rhythm/) only deals with box and line heights for now
- [_actual value_](https://drafts.csswg.org/css-cascade/#actual-value)
- [`<length>`](https://drafts.csswg.org/css-values/#lengths)
- affects: #3720

Browsers may need to round the _used value_ to a different _actual value_ in order to match the capabilities of the output device, e.g. integer values of device pixels. Authors may be fine with or even benefit from a less precise _actual value_, e.g. when they are designing every length with a _step value_ of `1px` (CSS pixels) anyway. Instead of (or in addition to) introducing a per-case math function like `round()` or `mod()` #2513, I would like to propose a cascading property to specify the desired accuracy of transforming any _calculated value_ into a _used value_ (which the browser may still need to change for the _actual value_).

```` ebnf
length-precision: [auto | high | low | <length> | <step-unit> | <storage-unit> | integer] || [<round>]
<step-unit>: pixel | dot | twip | emu | um
<storage-unit>: [<positive-integer> bit] | [signed? [nibble | byte | [half | short | long | double | quad] [float? | int]] | char] /* probably unnecessary */
<round>: up | down | nearest | to-zero | from-zero | floor | ceil
````

- **`auto`** (or `medium`): *default*, depends solely on the capabilities of the user agent and hardware setup, should be smaller than `1px`
- `higher`: if possible, a higher precision than used by default, e.g. by storing more bits per value, thus probably increasing display quality and decreasing rendering speed
- `lower`: a lower precision than used by default, e.g. by storing less bits per value, thus probably decreasing display quality and increasing rendering speed
- `<length>`: all _computed lengths_ should be rounded to an integer multiple of the length specified, e.g. `1px`
- `um`, `mu`, `micro`, `micron` or `micrometer`: same as `0.001mm`, a micrometer (The SI prefix symbol `µ`, i.e. a Greek small _mu_ or _my_, can be substituted by `u` if the former is not available in the character set.)
- `twip`: same as `0.05pt`, a twentieth of a point
- `emu`: all _computed lengths_ should be rounded to an integer multiple of the English-Metric Unit defined for OpenXML, where 36 emu = 1 micrometer
- `pixel`: all _computed lengths_ should be rounded to an integer multiple of *device pixels*, where each pixel consists of the same number of (colored) sub-pixels; smaller or equal to `1px`
- `dot`: all _computed lengths_ should be rounded to an integer multiple of the *smallest graphic element* the output device can address, e.g. sub-pixels for screens; smaller or equal to `pixel`
- `integer` or `int`: all _specified lengths_ should be rounded to an integer multiple of the unit specified, before being converted to the canonical unit `px` for the _computed value_
- `<storage-unit>`: absolute and relative lengths in computed, used and actual values should be treated as if they were limited to *n* bits or, if `signed` is specified, n−1 bits, with _n_ = {1: `bool`, 4: `nibble`, 8: `byte`, 16: `half`, 21: `char`, 24: `short`, 32: `float`/`int`, 48: `long`, 64: `double`, 128: quad }. 

The rounding behavior is based on an extended set of keywords taken from [css-rhythm](https://drafts.csswg.org/css-rhythm/#block-step-round).

- `up`: If the absolute value is not an integer multiple of the _step value_, it is increased to the next one, e.g. `-1.5px` to `-1px` and `1.5px` to `2px` for a _step value_ of `1px`.
- `down`: If the absolute value is not an integer multiple of the _step value_, it is decreased to the previous one, e.g. `-1.5px` to `-2px` and `1.5px` to `1px` for a _step value_ of `1px`.
- `normal`: The value is either increased (as for `up`) or decreased (as for `down`) – whichever results in the smallest absolute change, e.g. `-1.3px` to `-1px` and `1.3px` to `1px` for a _step value_ of `1px`. If both options would result in the same amount of change, the size is increased, e.g. `1.5px` to `2px` for a _step value_ of `1px`.. 
- `to-zero` or `zero`: same as `down` for positive values, same as `up` for negative values, e.g. `-1.5px` to `-1px` and `1.5px` to `1px` for a _step value_ of `1px`. `0` is left unchanged.
- `from-zero` or `to-infinity` or `infinity`: same as `up` for positive values, same as `down` for negative values, e.g. `-1.5px` to `-2px` and `1.5px` to `2px` for a _step value_ of `1px`. `0` is left unchanged.
- `ceil` or `ceiling`: like `up`, but if the _step unit_ is `auto`, it is treated like `1px`
- `floor`: like `down`, but if the _step unit_ is `auto`, it is treated like `1px`
- `nearest`: like `nearest`, but with increase as for `ceil` and decrease as for `floor`

**Comment by tabatkins** [comment]
I'm very sorry, @crissov, but as usual I'm going to have to ask for at least a hint of actual use-cases here - some sort of problem we could actually examine that might be helped by this suggestion. Without that, none of this design work does anything for us, as we have no way to tell what parts are necessary and what parts are overdesigned or not the right solution.

For example, without use-cases, I could imagine that snapping lengths to whole `px` *might* be useful, but I can't tell whether it actually is or not, or whether the central premise of doing this on a global level for an element vs on individual lengths via a math function is better. The entire rest of the proposal, lacking any use-cases to the contrary, look like complete over-engineering to my initial review. Many of the suggestions here would also require significant engineering work thru the entire style system, such as setting particular sub-pixel precisions or bit-widths that don't accord with the current (purposely unspecified) values used by actual implementations; without *very strong* use-cases, we can probably reject those offhand.

I'm going to close this issue. If you can provide use-cases for these suggestions, we can reopen and discuss at that time.
