### ISSUE TITLE
[css-backgrounds] Lack of "start" and "end" keywords

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#4450]
> This was originally discussed by email, and we are moving the discussion to GH. See https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-340&list=www-style
> Raised by: Addison Phillips
> Opened on: 2014-02-20

Document: http://www.w3.org/TR/2014/WD-css3-background-20140204/

Section 3.6 "Positioning Images", the keywords "left" and "right" are defined but not the direction-independent "start" and "end" keywords.

We feel that there might be cases where one might want to set the start or end edge of a background or of a border in which the starting edge is determined based on the container's direction.

**Comment by SebastianZ** [comment]
Those keywords are already defined for `background-position` in [level 4 of the specification](https://drafts.csswg.org/css-backgrounds-4/#the-background-position).

Sebastian

**Comment by xfq** [comment]
Should we close this issue now?

**Comment by tabatkins** [comment]
yup
