### ISSUE TITLE
[css-backgrounds] border-left-* and border-right-*

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#4451]
> This was originally discussed by email, and we are moving the discussion to GH. See https://www.w3.org/Mail/flatten/index?subject=I18N-ISSUE-341&list=www-style
> Raised by: Addison Phillips
> Opened on: 2014-02-20

Document: http://www.w3.org/TR/2014/WD-css3-background-20140204/

Section 4. Similar to I18N-ISSUE-340, should there be a border-start-\* and border-end-\* set of keywords, allowing one to control the leading/trailing edge of borders dependent on the container direction?

**Comment by Loirooriol** [comment]
Do you mean like [logical borders](https://drafts.csswg.org/css-logical/#border-properties)? We already have all these properties:

- border-block, border-inline, border-block-start, border-block-end, border-inline-start, border-inline-end
- border-block-width, border-inline-width, border-block-start-width, border-block-end-width, border-inline-start-width, border-inline-end-width
- border-block-style, border-inline-style, border-block-start-style, border-block-end-style, border-inline-start-style, border-inline-end-style
- border-block-color, border-inline-color, border-block-start-color, border-block-end-color, border-inline-start-color, border-inline-end-color
- border-start-start-radius, border-start-end-radius, border-end-start-radius, border-end-end-radius

Note that the mapping uses the writing mode of the element itself, not the one of the container.

**Comment by xfq** [comment]
Should we close this issue now?

**Comment by tabatkins** [comment]
Yup.
