### ISSUE TITLE
[css-contain] Editorial: suggest rephrasing in Introduction

### ISSUE THREAD

**Issue by chrisn** [w3c/csswg-drafts#4466]
I'm doing my W3C AC review of CSS Containment Module Level 1, and have one minor comment about this text in the [Introduction][1]:

> so innocuous changes to a page may inadvertently make it flunk the heuristics and fall into a slow mode.

I suggested rephrasing, as "flunk" is a region specific colloquialism. It's also not clear what "fall into a slow mode" is referring to (the page itself or the rendering of the page).

I humbly suggest, for example:

> so innocuous changes to a page may inadvertently make it fail such heuristic tests, causing rendering to fall into a slow code path.

[1]: https://www.w3.org/TR/2019/PR-css-contain-1-20191015/#intro

**Comment by frivoal** [comment]
Thanks for the feedback. Your suggestion seems reasonable to me.

@astearns @atanassov This would be a completely editorial edit to a non normative section. I'd normally accept that without going through the WG, but we are in Proposed Rec. Should I Agenda+ to get a formal WG resolution, or can I just fix this? Or maybe you can declare a resolution here without a call.

**Comment by astearns** [comment]
I prefer we just fix it - it's purely editorial.

**Comment by tabatkins** [comment]
Yeah just fix it.

**Comment by svgeesus** [comment]
This can be just fixed. The edit should be made to the copy of the PR that becomes the Rec, as well as in the ED bikeshed source.
The editorial change will be noted in the director's decision to the AC.

**Comment by frivoal** [comment]
Fixed in the ED for level 1 and 2, and included in the (new) DoC:
* https://drafts.csswg.org/css-contain-1/issues-2019-10-pr
* https://drafts.csswg.org/css-contain-2/issues-2019-10-fpwd
