### ISSUE TITLE
[css-fonts] Add a ui-sans-serif keyword to go with ui-serif

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#4468]
A follow-up to #4107:

In that issue we agreed to add [`ui-serif`, `ui-monospaced`, and `ui-rounded`](https://drafts.csswg.org/css-fonts-4/#standard-font-families) to allow access to variants of system fonts other than the standard `system-ui` font.  However, this set of names assumes that `system-ui` is a sans-serif style, which may not always be true.

There should be a `ui-sans-serif` keyword for authors who want to specifically request the system's sans serif style. The `system-ui` keyword would continue to be the primary font used by the system interface, regardless of style. These two keywords might map to the same font; the difference is in intent.

**Comment by Crissov** [comment]
The result of the discussion in #4397, which is about Nastaliq and styles or hands of other non-European scripts, should probably also inform the decision which UI fonts should be accessible through CSS, and perhaps voice versa (re _rounded_).
