### ISSUE TITLE
[css-fonts] Inconsistency between `monospace` and `ui-monospaced`

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#4469]
The new UI font keywords recently added to Fonts 4 includes [`ui-monospaced`](https://drafts.csswg.org/css-fonts-4/#ui-monospaced-def) (note the "d" at the end). In contrast, the existing generic keyword is `monospace` (no "d").

There is already lots of potential for authoring confusion over whether to include the "d" at the end of `monospace` or not, because both terms are used interchangeably in typography (monospace font or monospaced font). I don't think it is helpful to have two keywords in CSS with different grammatical inflections, it will make it that much harder to remember which version is correct.

**Comment by ExE-Boss** [comment]
Let’s&nbsp;fix&nbsp;that before any&nbsp;browser ships&nbsp;this.

We&nbsp;don’t&nbsp;want yet&nbsp;another&nbsp;item to&nbsp;add to&nbsp;the&nbsp;ever&nbsp;expanding [list&nbsp;of&nbsp;legacy **CSSWG**&nbsp;mistakes](https://wiki.csswg.org/ideas/mistakes).

**Comment by litherum** [comment]
Whoops!! Yes, let’s fix this immediately

**Comment by litherum** [comment]
I think this counts as editorial, so I should be able to just make the edit.
