### ISSUE TITLE
[css-color] Merge Lab() and LCH() in CIE()? 

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4481]
With CIE lightness becoming a `<percentage>` per #4477, it becomes possible to unify Lab and LCH in a single functional notation. Iʼm not sure this is a useful thing to do, but perhaps others do. 

CIELAB _a_ and _b_ might not be percentages in disguise, but CIELUV _u_ and _v_ apparently are. 

~~~~
cie() = cie( 
 /* Lab */    <number>{3} 
 /* Lab */ | [<percentage> && <number>{2}] 
 /* Luv */ |  <percentage>{3} 
 /* Luv */ | [<number> && <percentage>{2}] 
 /* LCH */ | [<number>{2} && <angle>] 
 /* LCH */ | [<percentage> && <number> && <angle>] 
           [ / <alpha-value> ]? 
           ) 
~~~~

By this reasoning, though, `rgb()` should consequently also support `<angle> && <percentage>{2}` for either HSL or HWB, or `<angle> <percentage>{2}` for one of them and `<percentage>{2} <angle>` for the other.

~~~~
rgb() = rgb(
 /* RGB */    <number>{3} 
 /* RGB */ |  <percentage>{3}
 /* HSL */ | [<angle> <percentage>{2}] 
 /* HWB */ | [<percentage>{2} <angle>] 
           [ / <alpha-value> ]? 
           )
~~~~

**Comment by tabatkins** [comment]
Ooh, I *really* don't think this is a good idea. The fact that the grammars don't *technically* clash doesn't mean merging them makes sense.

We're not trying to conserve function names here; that namespace is wide open. Having the color functions all be separate functions that name their arguments in the same fashion seems far friendlier to authors than asking them to memorize a number of argument-order patterns and divine which color space is being used.

**Comment by Crissov** [comment]
Iʼm absolutely fine with rejecting this idea, although Luv support _might_ still be worthwhile. It originally was just a point in favor of enforcing explicit units wherever they apply.
