### ISSUE TITLE
[css-color] Allow <angle> or <hue> in color() 

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4489]
> [`color()`](https://drafts.csswg.org/css-color/#color-function) `= color( [ <ident>?` **`[ <number>+ | <string> ]`** `[ / <alpha-value> ]? ]# , <color>? )`

This allows either a named color or a _tuple of unit-less numbers_ to identify or specify a color within a custom color space. Wouldnʼt it be useful to also support `<percentage>` (or `<alpha-value>` = `<cmyk-component>`) and `<angle>` (or `<hue>`) for custom color components since try are used in predefined color notations? 

See #4477 for CIE lightness as a percentage.

**Comment by faceless2** [comment]
The values given to any ICC profile for conversion are 0 to 1. You can map percentages to this (and do, in #3450), but angles etc. would require knowledge which isn't readily available.

**Comment by Crissov** [comment]
Oops! This issue is mostly a duplicate of #3450 indeed. I will limit its scope to polar coordinates, i. e. `<angle>`.

**Comment by Crissov** [comment]
PS: [`@color-profile`](https://drafts.csswg.org/css-color/#at-profile) could get a descriptor to distinguish color space notations using names, channels (e. g. RGB and CMYK), Cartesian (e. g. Lab and Luv) or polar coordinates (i. e. anything with hue). UAs could then simply ignore uses of `color()` where the provided component types do not match the descriptor.

**Comment by Crissov** [comment]
PS: [`@color-profile`](https://drafts.csswg.org/css-color/#at-profile) could get a descriptor to distinguish color space notations using names, channels (e. g. RGB and CMYK), Cartesian (e. g. Lab and Luv) or polar coordinates (i. e. anything with hue). UAs could then simply ignore uses of `color()` where the provided component types do not match the descriptor.

**Comment by svgeesus** [comment]
Closing because the current spec allows percent already

```
color() = color( [ [<ident> | <dashed-ident>]? [ <number-percentage>+ | <string> ] 
[ / <alpha-value> ]? ]# , <color>? )
```
none of the predefined spaces in `color()` use a hue or angle, and ICC profiles take parameters in the range 0.0 to 1.0, not angles, as already mentioned.

**Comment by Crissov** [comment]
I expected nothing else. Perhaps I should have rephrased the issue to: _Allow polar coordinates for arbitrary color spaces_. 

```` ebnf
color([ <ident>? 
        [ <string>
        | <polar>
        | <component>+ 
        ] [ / <component> ]? 
      ]#[, <color> ]?)

<polar> = <hue> || <component>{0,2}
<component> = <number> | <percentage>
````
