### ISSUE TITLE
[css-color][css-values] Merge <alpha-value> and <cmyk-component> in <color-component>

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#4494]
As already mentioned in #4477, [`<alpha-value>`](https://drafts.csswg.org/css-color/#typedef-alpha-value) is redundant with [`<cmyk-component>`](https://drafts.csswg.org/css-color/#typedef-cmyk-component), because both are effectively defined as `<number [0.0, 1.0]> | <percentage>`. Since `color()` shall allow either type as well #3450, it would make sense to have a single value type `<color-component>` for all of these, even if we can never have a generic `<number-percentage>` type in [css-value](https://drafts.csswg.org/css-values).

**Comment by svgeesus** [comment]
> <alpha-value> is redundant with <cmyk-component>, 

Sure, if all you care about is syntactic level and nothing about documentation, understandability or semantics.

Closing this as pointless.

**Comment by Crissov** [comment]
I care about ease of understanding of specifications.

**Comment by Crissov** [comment]
Also, apparently `<alphavalue>` is going to be killed in #3139.
