### ISSUE TITLE
[css-animations-2] List of pseudo-elements in composite order is non-exhaustive

### ISSUE THREAD

**Issue by george-steel** [w3c/csswg-drafts#4502]
In the definition of Animation [composite order](https://drafts.csswg.org/css-animations-2/#animation-composite-order), the list of pseudo-elements only includes `::marker`, `::before`, and `::after`. Since many other pseudo-elements exist, and there is no section of the spec restricting animations to these particular pseudo-elements, How should we resolve this? I can think of a few possibilities.

1. Replace the specific list with "pseudo-elements in alphabetical order by selector", as is done to order transitions by property.
2. Add an entry for "other pseudo-elements in alphabetical order by selector".
3. Add a canonical ordering to the pseudo-element spec and reference it. This would have to keep up with changes.
4. Add a restriction on which pseudo-elements may be animated to css-animations-1 and web-animations

**Comment by george-steel** [comment]
@birtles @stephenmcgruer

**Comment by birtles** [comment]
At this point I tend to lean towards (4) (and work out the ordering for other pseudos once UAs actually need to animate them).

I don't particularly like (1) since I believe the `::marker`, `::before`, `::after` ordering makes most sense when authoring.

**Comment by george-steel** [comment]
My personal leaning is towards 2.

In the current spec, all pseudo-elements should be able to be targeted for animations (since we removed the requirement for EventTarget to make sense for the pseudo-element) and only animating before, after, and marker is a partial implementation. Restricting which pseudo-elements may be animated seems rather arbitrary.

**Comment by birtles** [comment]
I guess the question is, is Blink looking to implement animation for other pseudos in the near future? If not, I don't think we should spec it yet.

**Comment by george-steel** [comment]
I'm hoping to do so as long as the code doesn't fight back too much. Our current implementation of hanging Animations off of blink::PseudoElement objects (likely the source of the restriction) has lifecycle issues and needs refactoring anyways, fixing it might make all pseudo-elements animatable.
