### ISSUE TITLE
[css-pseudo] ::first-letter should skip all decendant ::markers, not just the block's own ::marker

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4503]
[Finding the First Letter](https://drafts.csswg.org/css-pseudo-4/#application-in-css) says:
> If an element is a list item (display: list-item), the ::first-letter applies to the first letter in the principal box after the marker.

That seems to suggest that for:
```html
<!DOCTYPE HTML>
<style>
div {
  display: list-item;
  list-style-type: lower-alpha;
  margin-left: 50px;
}
#f::first-letter { font-size:400% }
</style>
<div id="f"><div>item</div></div>
```
the `::marker` for the inner `<div>` should be selected as the `::first-letter`?
Or am I simply misreading the intent of the spec here? I interpret the "an element is a list item" as being the one with the `::first-letter` style on it. If the intention is that it applies to the element itself _and all descendants too_ then I'd appreciate if that ambiguity could be removed.

Firefox, Chrome or Safari are compatible though - they select the "i" as the `::first-letter`.
 (Firefox currently does include markers when styled with `::marker { content: '...' }` though, which I intend to [fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1595103).)

Furthermore, adding `list-style-position: inside` makes no difference.  The spec says:
> User-Agents may ignore ::first-letter on list items with list-style-position: inside.

(this note seems to imply that only the top element is considered in the exemption of the marker earlier)

I think the spec should be updated to reflect reality:
1. we should skip markers of descendants too
2. remove the note about `list-style-position: inside`

IOW, all `::marker` boxes should be skipped when finding a `::first-letter`.

That reflects what UAs currently implements and that behavior makes sense. I don't really see a reason for why authors would ever want to include the marker text when searching for a `::first-letter`. If that's a use case we need to support then maybe we could add a `::marker::first-letter` selector specifically for that.

CC @Loirooriol

**Comment by Loirooriol** [comment]
I agree, excluding the own marker but including the marker of the descendants seems very inconsistent.

Excluding all markers may also be a bit strange, since `#f > ::marker` is generated between `#f::before` and the text run `item`, both of which are included when finding the first letter. But I think this is preferable.

**Comment by MatsPalmgren** [comment]
>  is generated between #f::before and the text run item

No, the `::marker` box comes before `::before` per [css-lists](https://drafts.csswg.org/css-lists/#marker-pseudo).

Also, a list item `::marker` has a very clear semantic meaning of being a label for the item and not being a part of the item's content. `::before/::after` are a bit more general purpose and usually they render as being part of the paragraph.  Furthermore, a `::marker` is typically just a digit/letter whereas `::before/::after` is typically at least a phrase or sentence. So excluding (all) markers and including `::before/::after` seems reasonable to me.

**Comment by Loirooriol** [comment]
Yes, your reasoning for excluding all markers makes sense.

**Comment by fantasai** [comment]
Yeah, I agree. I think that sentence just didn't think of the case of multiple markers.

**Comment by fantasai** [comment]
OK, I rewrote the ::first-letter section (finally) in https://github.com/w3c/csswg-drafts/commit/683cfb00340d75ae627da1d965d802398e1574c0
Rewrote the text about list-item markers as 

> For this purpose, any marker boxes are ignored, as if they were out-of-flow. However, if an element has in-flow ::before or ::after content, the first-letter text is selected from the content of the element including that generated content.

See https://drafts.csswg.org/css-pseudo-4/#first-letter-pseudo

@Loirooriol Mind reviewing? :)

**Comment by Loirooriol** [comment]
LGTM. Just noting the spec still says

> if the first-letter text is not at the start of the line (for example due to bidirectional reordering, or due to a list item marker with `list-style-position: inside`), then the user agent is not required to create the pseudo-element(s).

which @MatsPalmgren wanted to remove. I don't have a strong opinion.
