### ISSUE TITLE
[css-break] Tall unbreakable content - overflow or slice?

### ISSUE THREAD

**Issue by mstensho** [w3c/csswg-drafts#4509]
When we have truly unbreakable content (such as a line, an image or a border) that's taller than the fragmentainer, we can generally do one of two things: either slice it into multiple fragmentainers, or let it overflow the fragmentainer, in the block direction. I can't find this clearly specified anywhere. Seems to me that for printing, for instance, we want slicing (or content would be lost). For multicol, on the other hand, just letting it overflow the column seems appropriate. Gecko does that, Blink doesn't.

```
<div style="columns:3; height:100px; column-fill:auto; background:yellow;">
  <div style="border-top:150px solid hotpink;">
    line 1<br>
    line 2<br>
  </div>
</div>
```

There's really only one (class A, B or C) break opportunity here - between the two lines, and Gecko does exactly that. It puts the entire border plus the first line (even if it's too tall) in the first column and the second line in the second column.

Maybe each spec that uses block fragmentation should also specify what to do with unbreakable overflow? Maybe css-break should also say something more about it? https://drafts.csswg.org/css-break/#unforced-breaks and https://drafts.csswg.org/css-break/#transforms mention slicing.

**Comment by fantasai** [comment]
Afaict it's clearly specified:

https://www.w3.org/TR/css-break-3/#possible-breaks

>  Some content is not fragmentable, for example many types of replaced elements [CSS21] (such as images or video), scrollable elements, or a single line of text content. Such content is considered monolithic: it contains no possible break points. Any forced breaks within such boxes therefore cannot split the box, and must therefore also be ignored by the box’s own fragmentation context.
>
> In addition to any content which is not generally fragmentable, UAs may consider as monolithic any elements with overflow set to auto or scroll and any elements with overflow: hidden and a non-auto logical height (and no specified maximum logical height).
> 
> Since line boxes contain no possible break points, inline-block and inline-table boxes (and other inline-level display types that establish an independent formatting context) may also be considered monolithic: that is, in the cases where a single line box is too large to fit within its fragmentainer even by itself and the UA chooses to split the line box, it may fragment such boxes or it may treat them as monolithic. 

https://www.w3.org/TR/css-break-3/#unforced-breaks

> Finally, if there are no possible break points below the top of the fragmentainer, and not all the content fits, the UA may break anywhere in order to avoid losing content off the edge of the fragmentainer. In such cases, the UA may also fragment the contents of monolithic elements by slicing the element’s graphical representation. However, the UA must not break at the top of the page, i.e. it must place at least some content on each fragmentainer, so that each fragmentainer has a non-zero amount of content, in order to guarantee progress through the content.

**Comment by fantasai** [comment]
Marking invalid, feel free to reopen if you think something is still missing.

**Comment by mstensho** [comment]
Ok, so this means that neither Blink nor Gecko is violating any specs in their multicol implementations, although they behave differently? I'd like this to be specced, but maybe it belongs in the multicol spec? Then again, things like CSS regions probably want to do the same thing.

**Comment by rachelandrew** [comment]
Seems like something we should have in multicol, I guess if in the future Regions then was going to have the exact same behaviour it could be moved elsewhere. If we don't have interop then I think we  need to clarify how this should behave for multicol.

**Comment by astearns** [comment]
If there's something to spec here, it should be in css-break. One reason we did not require overflow for multicol (allowing MAY for slicing) is that both behaviors are useful. If your multicol element is in a scrollable page, then overflow is fine. But if you're using multicol to display pages in a book reader where the user can't scroll to see the content, slicing is better.

**Comment by MatsPalmgren** [comment]
The given example seems entirely academical to me. Borders that are larger than the entire size of the fragmentainer isn't something that occurs in practice. So I don't see a need to spec this particular edge case. The spec is already clear that slicing borders are strongly discouraged.

If anything, I'd like to see the "you MAY slice monolithic content" escape hatch **removed** so that CSS fragmentation behaves more like it does in physical printed media. You would **never** see a sliced border there!

The path to better interop here is to agree to stop slicing altogether and instead implement what css-break actually recommends, because it's pretty good. This is the path Gecko will take. (And the problem in Chrome isn't just borders, it's also [grid rows](https://bugs.chromium.org/p/chromium/issues/detail?id=613341) and a whole range of other situations, as @mrego alludes to with "The whole engine has issues with fragmentation". I'm hoping LayoutNG will bring some improvements to Chrome's fragmentation...)

**Comment by mstensho** [comment]
Yes, LayoutNG will bring some much needed improvements, such as having the layout engine actually do block fragmentation, rather than pretending that it's a single tall strip that gets sliced into columns during painting and hit-testing. :)

The border example is academical, perhaps. But what about a tall image, then? Same thing. Overflow or slice?

**Comment by MatsPalmgren** [comment]
I believe treating tall images as monolithic by default is the best option, as the spec suggests. The current behavior in Gecko is [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1372836) in my opinion (and Chrome appears to do better there). Again, you would never see a photograph being sliced between columns or pages in a printed magazine. I don't see why CSS layout should do that by default.  Granted, a browser needs to handle all possible content, so we need to handle the edge case where an image is taller than its fragmentainer for example. Slicing is one option, but we could also try scaling it down until it fits for example. Fwiw, in the bug above, I suggested adding `img, video, ... { break-inside:avoid; }`in our UA sheet to improve our layout, which would also give authors a way to override that default behavior if they wish. Giving authors more control over the mechanism (slice/scale/overflow/truncate/ellipsing/etc) seems like a good idea too.

**Comment by MatsPalmgren** [comment]
Also, we could have different fallback behavior for the tall image case in column and print layout. My personal preference would probably be to scale it in print media and overflow in column layout (i.e. it would stick out as overflow below the column). Assuming `img { break-inside:avoid; }` is the default, the image would have the entire column/page for itself so I think it would be rare (on real web pages) that it still wouldn't fit.
