### ISSUE TITLE
[css-position] Does position:fixed create a stacking context?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#451]
From [Minutes Telecon 2015-07-01](https://www.w3.org/blog/CSS/2015/07/02/minutes-telecon-252/):

> **Resolved**: Make `position: fixed` a full stacking context
> - Rossen will write the text change in place it in the [Positioning](http://dev.w3.org/csswg/css-position/) spec. Bert will then take the same text and add it as an errata to [CSS 2](http://dev.w3.org/csswg/css2/cover.html).

I found the changes in the [CSS 2 spec](https://drafts.csswg.org/css2/changes.html#s.9.9.1).

However, the definition of [`z-index: auto`](https://drafts.csswg.org/css-position/#valdef-z-index-auto) in CSS Position does not have that change, and I can't find anything which explains that `position: fixed` creates a stacking context.

Did the WG change their minds? Did Rossen forgot to update CSS Position?

**Comment by Tyler-H** [comment]
This is more pressing; people are starting to ask questions about this behavior and the spec still says no. This is leading to differing behaviors in Chrome vs Firefox, etc. http://stackoverflow.com/questions/40551057/positionfixed-within-positionfixed-which-browsers-right/

**Comment by atanassov** [comment]
You're right, this was supposed to be merged into the positioning spec as well - on it now. Thanks.
