### ISSUE TITLE
[css-values] Contradictory statements regarding allowability of ∞

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4514]
According to https://drafts.csswg.org/css-values-3/#numeric-ranges and https://drafts.csswg.org/css-values-4/#numeric-ranges,

> CSS theoretically supports infinite precision and infinite ranges for all value types; however in reality implementations have finite capacity. UAs should support reasonably useful ranges and precisions. Range extremes that are ideally unlimited are indicated using ∞ or −∞ as appropriate.

But in https://drafts.csswg.org/css-values-4/#calc-range,

>  By definition, ±∞ are outside the allowed range for any property

This seems contradictory. If I understand correctly, the former quote means that infinity is theoretically allowed, but in practice it's not possible. The latter quote means that infinity is invalid both theoretically and in practice.

I prefer the latter, and replace things like `<integer [0,∞]>` with `<integer [0,∞)>` since  `∞ ∉ ℤ`.

**Comment by tabatkins** [comment]
I'm not going to add a half-open-range syntax variant just to express that "literally infinity" isnt allowed but 10^100 is. ^_^

The statements aren't contradictory in general; the ∞ is a syntax convenience to indicate no explicit end to the range on that side. That "theoretically" is talking about an ideal, abstract Platonic ideal of CSS, not saying that there's a sense in which a CSS implementation actually supports infinite values.

**Comment by Loirooriol** [comment]
It's clear that implementations can't support infinite values.

What's unclear is whether the abstract Platonic ideal of CSS supports them or not. The 1st quote says it does. The 2nd quote says it doesn't.

If you want to allow infinite values in the abstract Platonic ideal of CSS to avoid add a half-open-range syntax variant, then it's fine, but just be consistent and instead of

> By definition, ±∞ are outside the allowed range

say something like

> In practice, ±∞ are outside the allowed range

**Comment by tabatkins** [comment]
That's only inconsistent if you choose to read the "by definition" line as meaning "by definition of the platonic ideal of CSS", rather than "by definition of CSS in practice". ^_^

But sure, *that* change I'm okay with.

**Comment by Loirooriol** [comment]
That said, if you allow infinity, you get into problems fast. For example, in https://drafts.csswg.org/css-grid/#extra-space

> Subtract the corresponding size (base size or growth limit) of every spanned track from the item’s size contribution

What happens in Platonic CSS if both are infinite? ∞ - ∞ is indeterminated...
