### ISSUE TITLE
[css‑syntax] The current definition of `ws*` contains a duplicate path

### ISSUE THREAD

**Issue by ExE-Boss** [w3c/csswg-drafts#4521]
The&nbsp;current&nbsp;definition of&nbsp;`ws*`&nbsp;is&nbsp;`<whitespace‑token>*`:

[<img alt="Screenshot_2019-11-19 CSS Syntax Module Level 3 – ws-diagram" src="https://user-images.githubusercontent.com/3889017/69181474-72672a00-0b0f-11ea-9eb3-529ce11b8b08.png" height="80px" align="top"/>](https://drafts.csswg.org/css-syntax/#ws*-diagram)

The&nbsp;definition of&nbsp;`<whitespace‑token>` is&nbsp;`whitespace+`:

[<img alt="Screenshot_2019-11-19 CSS Syntax Module Level 3 – whitespace-token-diagram" src="https://user-images.githubusercontent.com/3889017/69181723-e86b9100-0b0f-11ea-99a5-ee03d9d66ea2.png" height="71px" align="top"/>](https://drafts.csswg.org/css-syntax/#whitespace-token-diagram)

This&nbsp;means that&nbsp;the&nbsp;current&nbsp;definition of&nbsp;`ws*`&nbsp;is&nbsp;equal&nbsp;to:

[<img alt="Screenshot_2019-11-19 Railroad Diagram Generator – flattened-ws-diagram" src="https://user-images.githubusercontent.com/3889017/69181775-01744200-0b10-11ea-88d5-a34f0fefc927.png" height="88px" align="top"/>](https://tabatkins.github.io/railroad-diagrams/generator.html#Diagram(%0A%09ZeroOrMore(%0A%09%09OneOrMore(%0A%09%09%09NonTerminal(%0A%09%09%09%09'whitespace'%2C%20%0A%09%09%09%09%7B%20href%3A%20'https%3A%2F%2Fdrafts.csswg.org%2Fcss-syntax%2F%23whitespace-diagram'%20%7D%2C%0A%09%09%09)%2C%0A%09%09)%2C%0A%09)%2C%0A)%3B%0A)

This&nbsp;means that&nbsp;`ws*` can&nbsp;be&nbsp;simplified to&nbsp;just&nbsp;`<whitespace‑token>?`:

[<img alt="Screenshot_2019-11-19 Railroad Diagram Generator – simplified-ws-diagram" src="https://user-images.githubusercontent.com/3889017/69182220-dd653080-0b10-11ea-8283-fff00ed24840.png" height="71px" align="top"/>](https://tabatkins.github.io/railroad-diagrams/generator.html#Diagram(%0A%09Optional(%0A%09%09NonTerminal(%0A%09%09%09'%3Cwhitespace-token%3E'%2C%20%0A%09%09%09%7B%20href%3A%20'https%3A%2F%2Fdrafts.csswg.org%2Fcss-syntax%2F%23whitespace-token-diagram'%20%7D%2C%0A%09%09)%2C%0A%09)%2C%0A)%3B%0A)

**Comment by tabatkins** [comment]
Nope, it's valid as-is. Note that comments do *not* produce tokens, but *can* separate tokens that would form a single token if they were adjacent without the comment.

That is, `foo /**/ bar` contains four tokens - a "foo" ident, a whitespace, a whitespace, and a "bar" ident. The two whitespace tokens match `ws*` together.

**Comment by tabatkins** [comment]
(taking the thumbs-up response as the commenter being satisfied ^_^)
