### ISSUE TITLE
clarify to what extent new system color are about system settings versus browser settings

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#4533]
A number of new [system color keywords](https://drafts.csswg.org/css-color-4/#css-system-colors) in css-color-4 (in particular, `Canvas`, `CanvasText`, `LinkText`, `VisitedText`, and `ActiveText`) have the characteristic that they're both browser settings and system settings.  In other words, there might be an operating system color for link text configured that's *different* from the color for link text configured in the browser.

I think it should be clearer which of these colors the keywords are intended to reference.  I don't have a strong opinion, although I think I'm inclined towards the browser setting for them rather than the system one.  (If there are good use cases for both, it's possible two sets of keywords might be needed.  Gecko currently has `-moz-`-prefixed equivalents for both variants of `LinkText`.)

**Comment by dbaron** [comment]
(This came from [Mozilla bug 1590894](https://bugzilla.mozilla.org/show_bug.cgi?id=1590894).)

**Comment by svgeesus** [comment]
Normally I would expect browser settings to override more general system setting. But from what I understand, forced color mode is a system-level override for all applications. So the answer depends on whether forced color mode is in effect.

**Comment by svgeesus** [comment]
Clarified by https://github.com/w3c/csswg-drafts/commit/dd84ae811c37b2efda40295ec1b25a758813171e and https://github.com/w3c/csswg-drafts/commit/1e166b95c911e32de612129c65ae8254d74bcf46
