### ISSUE TITLE
[mediaqueries] The <general-enclosed> production contains unbalanced parentheses

### ISSUE THREAD

**Issue by papandreou** [w3c/csswg-drafts#4534]
In https://www.w3.org/TR/mediaqueries-4/#mq-syntax the `<general-enclosed>` production contains an unmatched end parenthesis:

```
<general-enclosed> = [ <function-token> <any-value> ) ] | ( <ident> <any-value> )
```

I think it should have been:

```
<general-enclosed> = [ <function-token> ( <any-value> ) ] | ( <ident> <any-value> )
```

**Comment by Loirooriol** [comment]
The opening parenthesis is included in `<function-token>`.
See https://drafts.csswg.org/css-syntax-3/#ref-for-typedef-function-token%E2%91%A0,

```
<function-token> = <ident-token> (
```

**Comment by dbaron** [comment]
Correct, the `<function-token>` contains the parenthesis.

**Comment by papandreou** [comment]
Ah, thanks -- sorry for the noise! I'm working on a CSS fuzzer and had implemented `<function-token>` wrong, so ended up with the unbalanced parentheses 🤪
