### ISSUE TITLE
[css-display] Terminology: is replaced content a type of independent formatting context?

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#4539]
I really like that this spec introduces the concept of [independent formatting context](https://drafts.csswg.org/css-display-3/#independent-formatting-context). CSS 2 went through some convoluted paraphrases when it meant this.

I have a terminology question that likely doesn’t have any direct normative consequence. Is it useful to think of [replaced content](https://drafts.csswg.org/css-display-3/#replaced-element) as one among other types of independent formatting context?

Declaring it is seems to simplify a model such that the behavior of a box that [establishes an independent formatting context](https://drafts.csswg.org/css-display-3/#establish-an-independent-formatting-context) is entirely determined by its context (and, for flow layout, its outer display type) and its type of independent FC.

On the other hand, [flow layout](https://drafts.csswg.org/css2/visudet.html) and [grid items](https://drafts.csswg.org/css-grid/#grid-item-sizing) both specify different sizing rules for replaced v.s. non-replaced content. So perhaps it’s best to keep the concept of independent FC for non-replaced content? ([Tables in CSS2](https://drafts.csswg.org/css2/tables.html#table-display) however specifically call out replaced table cells as no different from other table cells. Flexbox doesn’t specify anything specific to replaced flex items.)

(The context of this question is that we’re reconsidering the structure and names of some Rust type inside Servo’s layout code.)

**Comment by Loirooriol** [comment]
See the somewhat similar #1642, the answer seems to be that it's undefined within CSS.

**Comment by tabatkins** [comment]
We've gone ahead and added a sentence saying that replaced elements are always independent formatting contexts. This is a practical requirement anyway to ensure we dont' *have* to care about what's inside of them, so it does make sense to make it clear.
