### ISSUE TITLE
[css-shapes] Fetching data: URLs

### ISSUE THREAD

**Issue by youennf** [w3c/csswg-drafts#454]
https://drafts.csswg.org/css-shapes/#propdef-shape-outside is using fetch with cors anonymous mode to retrieve resources.
To enable access to data URLs, the Same-Origin data URL flag should be set.

**Comment by youennf** [comment]
Related topic in https://github.com/whatwg/fetch/issues/381

**Comment by xfq** [comment]
The same-origin data-URL flag was removed in whatwg/fetch#387, so I guess this issue can be closed now?
