### ISSUE TITLE
[cssom] "If property is not a custom property, follow th..."

### ISSUE THREAD

**Issue by Pomax** [w3c/csswg-drafts#4542]
https://drafts.csswg.org/cssom/#example-666534ab

> If property is not a custom property, follow these substeps:​ 

This set of procedural steps forgets to explicitly mention what should happen when the property _is_ a custom property. As currently written, the steps suggest that `getProperty` and `setProperty` doesn't even work for for custom properties, which is clearly not the case given that they work fine in every browser that supports those.

It might also be a good idea to have a section note that links to the part of the spec that talks about the `element.style` object, with some text _there_ that explains that `getProperty`/`setProperty` are in fact _required_ for custom properties, as something like this will work for any plain property but silently fail for any custom property:

```js
// single assignment
element.style["background"] = "#555";
element.style["--border-style"] = "1px solid black";

// batch assignment
let newStyles = {
  background: "#555";
  "--border-style": "1px solid black"
};
Object.assign{newStyles, element.style);
```

**Comment by AmeliaBR** [comment]
The bit about "If property is not a custom property" only affects the sub-steps 2.1 and 2.2, which are about adjusting the case and then checking whether the property name is recognized. The rest of the algorithm still applies for custom properties (those that start with `--`), which are treated as literals without any case adjustments.

See related discussion in #1316 about why simple JS getter/setters would be difficult to spec for arbitrary property names.

I agree with you that there should be more prominent notes for authors, though. I added a reminder to the still-open issue in 1316.

**Comment by Pomax** [comment]
Ah, I see. Thanks!
