### ISSUE TITLE
[css-grid] Unclear which "flexible track" is used when finding the used flex fraction

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4544]
https://drafts.csswg.org/css-grid/#algo-flex-tracks defines how to find the "used flex fraction":

> First, find the used flex fraction: [...]
> The used flex fraction is the maximum of:
> -  **If the flexible track’s flex factor** is greater than one, the result of dividing the track’s base size by its flex factor; otherwise, the track’s base size.
> -  The result of finding the size of an fr for each grid item that crosses a flexible track, using all the grid tracks that the item crosses and a space to fill of the item’s max-content contribution.

It's confusing when the definition says "the flexible track’s flex factor". Which flexible track? If you don't look at https://drafts.csswg.org/css-grid/#flex-fraction, this can make it seem like each track has it's own flex fraction or something.

I think it would be clearer like this:

> First, find the **grid**'s used flex fraction: [...]
> The used flex fraction is the maximum of:
> -  **For each flexible track,** if the track’s flex factor is greater than one, the result of dividing the track’s base size by its flex factor; otherwise, the track’s base size.
> -  **For each grid item that crosses a flexible track**, the result of finding the size of an fr using all the grid tracks that the item crosses and a space to fill of the item’s max-content contribution.

**Comment by Loirooriol** [comment]
Oh, and I guess the used flex fraction is also not clear when there are no flex tracks (and thus no grid items crossing flex tracks either). It wouldn't be unreasonable to assume that the maximum among no values is -∞, but 0 seems better. So maybe add a 3rd bullet with 0.

**Comment by fantasai** [comment]
@Loirooriol There isn't a need for a used flex fraction when there are no flex tracks, so it doesn't matter if it's undefined, right?

**Comment by Loirooriol** [comment]
@fantasai Sure, in practice the value doesn't matter. So saying "If there is no flexible track, the flex fraction is undefined" would also be fine. But right now it's not explicitly undefined, it's just unclear, which doesn't seem optimal. Because at this point a spec reader may not know yet that the flex fraction won't be used if there are no flex tracks. So it can cause confusion.

**Comment by Loirooriol** [comment]
BTW, faf173cf6654a14e51c0e8498db01a0496adbdb7 duplicated the "for each" instead of just moving it, I have fixed it in 8a2f5a22a859c841ef16e8c439372a6722602caa.
