### ISSUE TITLE
[css-scrollbars][css-scrollbars-1] What about a pseudo-element?

### ISSUE THREAD

**Issue by Cadienvan** [w3c/csswg-drafts#4547]
https://drafts.csswg.org/css-scrollbars-1/

It's my first time posting an issue here so sorry if I'm doing something wrong.

In my opinion, scrollbars are pretty important and have been a really big issue for us developers for a long time. I just saw this spec for the 1st time and wondered: "Why is this spec related to container element properties? Isn't it better to push it as a new pseudo-element, following the [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) non-standard spec?"
In that way, we could achieve cleaner code such as:
```
::scroll-bar{
  ...my style
}
```
instead of styling our scrollbars in every single element with the universal selector `*`.

As I see this spec is already in stage 1, I wonder if such a discussion has already taken place and, if it did, why did the csswg go in the properties direction.

**Comment by jonjohnjohnson** [comment]
@Cadienvan After checking out these other threads, I think you might be able to close this and add any outstanding thoughts to them.

- #107
- #1956
- #1958
- #1960
- #2966

**Comment by Cadienvan** [comment]
Thank you. I'll start by closing this one and think about how to properly write my thoughts in a clear comment.
