### ISSUE TITLE
[css-device-adapt] consider adding user-overscroll-action descriptor

### ISSUE THREAD

**Issue by majido** [w3c/csswg-drafts#455]
We are collaborating on a new [declarative API](https://github.com/WICG/user-gesture-nav) to give developer a reliable way to control overscroll actions (e.g., swipe navigations, pull-to-refresh, etc.). 

Our initial thinking was to use a new CSS attribute but it was [pointed out](https://github.com/WICG/user-gesture-nav/issues/1#issue-164104801) that perhaps a descriptor in the viewport meta tag is a better API particularly because all of the overscroll actions that we care about are only meaningful for viewport.

The proposal is to add `user-overscroll-action` which will be similar to `user-scalable` property in the viewport meta in the sense that it provides a directive to user agent on how to interpret a user action in this case overscroll as opposed to zoom. 

Do you think such a proposed descriptor is appropriate for `css-device-adapt`?

/cc @smaug----

**Comment by majido** [comment]
Friendly ping :smiley:  (I assume relevant editors triage these issues once get labeled) 

As explained we are looking to find the most appropriate API for exposing such controls. Here are the options we have considered so far:
1. A generic CSS attribute (this was the original [proposal](https://github.com/WICG/user-gesture-nav) and it is what we are currently implementing in Blink behind a flag)
2. A new property on viewport meta as part of css-device-adapt (this issue)
3. As an extension to existing "-ms-scroll-chaining" and spec'ed as part of CSSOM View (this was [proposed](https://github.com/w3c/csswg-drafts/issues/769) quite recently)

At this point I prefer options 2 or 3 if possible. I appreciate your feedback on this issue which would help guiding us in deciding which of these options to pursue further.

**Comment by xfq** [comment]
IIUC, this is now called `overscroll-behavior`?

**Comment by jonjohnjohnson** [comment]
Guessing this can be closed in light of https://github.com/w3c/csswg-drafts/issues/2179 resolution ?

**Comment by frivoal** [comment]
I think so. @majido , is that OK with you?

**Comment by majido** [comment]
Yes. Please close.

**Comment by xfq** [comment]
Closing.
