### ISSUE TITLE
[css-values-4] Specify that calculation trees explicitly work in double precision

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4551]
In [this twitter thread by @starsandrobots](https://twitter.com/starsandrobots/status/1199757377286754309), a CSS hack is shared that, in Chrome, causes values to snap to multiples of 1024px. This is because Chrome evaluates calc()s in  f64 precision, and the hack uses very large values that overflow the safe-integer range of a double by several bits.

In general CSS precision is intentionally unspecified (tho not *explicitly* unspecified; I should fix that...), to allow impls freedom to use their desired size of LayoutUnit, pack values into optimized structs, etc., so numeric precision/width can vary across impls and across properties in a single impl. But it seems likely that, within a calc(), impls will use a single consistent precision (since otherwise it would require multiple separate implementations of calculation trees and all the math functions for each numeric type).

Currently this precision also varies across impls (the hack doesn't work in Firefox, since they use f32s in calculation trees), but it seems likely that we can standardize this value across impls, and as people get used to using more complex calc()s, it's likely they'll come to depend on particular precisions, accidentally or purposefully. Since the Typed OM exposes numbers in f64s (JS's native numeric type), I think we should specify that calculation trees do their work in that precision too.

Thoughts? @emilio @heycam @domenic @smfr @bfgeek @xiaochengh

**Comment by smfr** [comment]
WebKit stores values internally as doubles, so I have no problem specifying double precision for calc values.

**Comment by emilio** [comment]
I don't understand why making `calc()` special here. If I understand correctly, [Blink](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/geometry/length.h) and [WebKit](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/Length.h) store every other non-calc() length as float.

I actually see no occurrence of `double` in [WebKit's `CalculationValue.cpp`](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/CalculationValue.cpp), @smfr what am I missing?

I think the difference here is that the WebKit CSS parser does operate on `double` and they then truncate to float rather than Gecko's, which uses `float` everywhere... But maybe I am missing something here.

**Comment by smfr** [comment]
> I actually see no occurrence of `double` in [WebKit's `CalculationValue.cpp`](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/platform/CalculationValue.cpp), @smfr what am I missing?

The values are stored via CSSPrimitiveValue, which has 'double num' in its union.

**Comment by emilio** [comment]
Sure, but that means that the actual math for `calc()` happens in float precision right?

**Comment by SelenIT** [comment]
The popularity of [the StackOverflow answer](https://stackoverflow.com/a/53146935) referenced in the twitter tread linked above also appears to demonstrate the need in the functionality similar to `Math.floor()` (to get the "step function" behavior).

**Comment by Loirooriol** [comment]
@SelenIT See #2513

**Comment by tabatkins** [comment]
Yeah, floor/mod/round are all reasonable requests for additional functions.

("mod" especially was proposed as part of the original calc() proposal over a decade ago; it was left out at the time because it created the "unexpected zero division not detectable at parse-time" problem that we can now handle.)

**Comment by smfr** [comment]
> Sure, but that means that the actual math for `calc()` happens in float precision right?

You're right, Length stores values in floats. So WebKit will do parse-time simplification in double precision, but will use floats later at computed value time.
