### ISSUE TITLE
[web-animations-1] Should ready / finished rejections be marked as handled?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#4556]
In https://github.com/web-platform-tests/wpt/issues/18932 there was some discussion about unhandled rejections for the `.ready` promise and I wasn't sure what the correct behavior should be.

This morning I discovered https://github.com/whatwg/streams/issues/547 where for streams we decided to explicitly mark rejections for "state promises" like `.ready` as handled. I wonder if we should be doing the same for `.ready` and `.finished` for the `Animation` interface?

**Comment by flackr** [comment]
This sounds reasonable to me. I was honestly surprised that the ready promise rejected when we in fact "handled" the requested actions. I think it would make sense to do the same here.

**Comment by graouts** [comment]
Agreed.

**Comment by birtles** [comment]
I worked on an initial patch for this for Firefox which should include WPT for this spec change:

https://hg.mozilla.org/try/rev/54bc69142ded40d5a5e5b8fef909bfd3fe1dab3e#l6.2

**Comment by birtles** [comment]
WPT for this change: https://github.com/web-platform-tests/wpt/pull/22314

**Comment by graouts** [comment]
For reference, this change's implementation is tracked as [WebKit bug 209240](https://bugs.webkit.org/show_bug.cgi?id=209240).
