### ISSUE TITLE
[css-values] Time type does not specify if unit is needed for magnitude of zero

### ISSUE THREAD

**Issue by nickshanks** [w3c/csswg-drafts#4569]
Lengths allow unitless `0`.
Angles note (in css-values-3; as I read it) that "0" means zero degrees from North/up in certain extant properties, but that new properties will always require the unit.
The definition of the &lt;time> type does not specify either way.

We now have divergent implementations. Safari allows unitless specification for durations with no magnitude, Chrome and Firefox do not.

**Comment by nickshanks** [comment]
Trying to attach a HTML file doesn't work, so I've copied and pasted it below:

```
<!DOCTYPE HTML>
<style>
	:root {
		background-color: lightblue;
		transition: background-color 3s;
		transition: background-color 0;
	}
	:root:hover {
		background-color: darkblue;
	}
</style>
<p>In Safari, the background colour will change immediately, not fade, on hover.</p>
```

**Comment by Loirooriol** [comment]
From https://drafts.csswg.org/css-values-3/#time

> Time values are dimensions

Where https://drafts.csswg.org/css-values-3/#dimension

> The general term dimension refers to a number with a unit attached to it

So `0` is not a dimension. So unless otherwise defined, I wouldn't consider `0` to be allowed as a `<time>`. Then Chrome and Firefox would be right.

**Comment by smfr** [comment]
WebKit fixed this (see webkit.org/b/203484) so I think this issue can be closed.

**Comment by ewilligers** [comment]
The spec is clear: https://drafts.csswg.org/css-values-4/#dimensions

> When written literally, a dimension is a number immediately followed by a unit identifier ...
> 
> CSS uses `<dimension>`s to specify distances (`<length>`), durations (`<time>`), frequencies (`<frequency>`), resolutions (`<resolution>`), and other quantities.
> 

`<length>` is an exception as it allows 0, as explained in the definition of `<length>`. `<angle>` is not an exception, but some legacy properties accept either `<angle>` or `<zero>` (the literal `0`), hence the note in the definition of `<angle>`.

Covered by animation-delay and animation-duration WPTs:
https://wpt.fyi/results/css/css-animations/parsing/animation-delay-invalid.html?label=master&label=experimental&aligned
https://wpt.fyi/results/css/css-animations/parsing/animation-duration-invalid.html?label=master&label=experimental&aligned
Ideally, transition-duration would also have a WPT excluding 0:
https://wpt.fyi/results/css/css-transitions/parsing/transition-duration-invalid.html?label=master&label=experimental&aligned
