### ISSUE TITLE
[css-text] Atomic inlines being equivalent to ID for line breaking is not web-compatible

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#4576]
The current CSS Text [Line Breaking Details] says:

> The line breaking behavior of a replaced element or other atomic inline is equivalent to an ideographic character (Unicode linebreaking class ID [UAX14]), and additionally, for Web-compatibility, introduces a soft wrap opportunity between itself and any adjacent U+00A0 NO-BREAK SPACE character.

We've got a report saying this is not web-compatible. Tested that all browsers always break before and after atomic inlines.

Is this an intentional change that all other browsers are willing to match?

@fantasai @litherum @emilio @jfkthame

[Line Breaking Details]: https://drafts.csswg.org/css-text-3/#line-break-details

**Comment by frivoal** [comment]
My understanding was that "equivalent to ID" is considered the more useful behavior in theory, but that it alone is not be web compatible. However, Equivalent to ID **and** breaks between adjacent U+00A0 was expected to be web compatible. Have you found other cases where the specified behavior would cause breakage?

**Comment by kojiishi** [comment]
Two cases were reported; atomic inline + ':' U+003A COLON and atomic inline + ';' U+003B SEMICOLON. In both cases, authors expect there's a break opportunity between them.

**Comment by kojiishi** [comment]
This issue was reported at
https://crbug.com/1025715: No breaking opportunity between SVG and ':' character

**Comment by litherum** [comment]
I guess the question is: Is there a use case for wanting strict line-breaking in a paragraph, but still wanting breaking opportunities on both sides of images? I think yes, these two things are fairly distinct, and it's entirely reasonable for an author to want this combination of behaviors.

**Comment by litherum** [comment]
I suppose another option is to add a new value to the [`wrap-before` and `wrap-after` properties](https://drafts.csswg.org/css-text-4/#wrap-before). Maybe something like `wrap-before: ideograph` or something.

**Comment by frivoal** [comment]
> I guess the question is: Is there a use case for wanting strict line-breaking in a paragraph, but still wanting breaking opportunities on both sides of images?

In that case, you could use

p { word-break: strict; }
img { word-break: auto; }

**Comment by frivoal** [comment]
I've made the edit corresponding to the resolution, and landed the corresponding test updates. Closing this issue, as that solves the original problem reported.

I've opened https://github.com/w3c/csswg-drafts/pull/4755 for the remaining part of this discussion, which is about adding a way to opt out of this compat mode and get some more text-like behavior on inline images.

**Comment by fantasai** [comment]
@frivoal Please open issues, not pull requests, for follow-up issues. I've filed https://github.com/w3c/csswg-drafts/issues/4949 for discussion.
