### ISSUE TITLE
[Request] [css-pseudo] Selector :viewport

### ISSUE THREAD

**Issue by oleedd** [w3c/csswg-drafts#4581]
To select elements which are in viewport at the moment - user can see them (or its position if hidden) without scrolling.

**Comment by Loirooriol** [comment]
See https://wiki.csswg.org/faq#selectors-that-depend-on-layout for why

>  I would like a :on-screen pseudo class to select elements which are currently in the viewport

can't be done.

**Comment by oleedd** [comment]
The thing is it is extremely useful in JS (with `querySelector()`).

**Comment by oleedd** [comment]
@Loirooriol
There is a solution for infinity loop - to forbid changing of position for such elements (with error in console or just not working). What about this?

**Comment by Loirooriol** [comment]
Please read https://wiki.csswg.org/faq#selectors-that-depend-on-layout, it explains why that doesn't work either.

**Comment by oleedd** [comment]
@Loirooriol
There is a solution for infinity loop - to forbid changing of position for such selectors (with error in console or just not working). What about this? And wiki says "but this works for this case". It is definitely better than nothing.

**Comment by oleedd** [comment]
No need problem abilities like Toggle States. The talking is only about `:on-screen` which can be done.

**Comment by Loirooriol** [comment]
> In effect, if we ever add a selector that can depend on properties, then we can never add another selector that would depend on other properties ever. Which one goes first? Something that we can only do once, ever, and that will affect our ability to evolve CSS in the future, is probably a bad idea for the language.

**Comment by oleedd** [comment]
And what is bad? In case of `:hover`, browsers blink in infinity loop, so the problem is visible. The developer will see this and fix. And no one will take away an element from viewport when it is there.

**Comment by oleedd** [comment]
And what is bad? In case of `:hover`, browsers blink in infinity loop, so the problem is visible. The developer will see this and fix. And no one will take away an element from the viewport when it is there.

**Comment by Loirooriol** [comment]
The provided link already explains [Why Doesn't This Argument Apply To :hover?](https://wiki.csswg.org/faq#why-doesn-t-this-argument-apply-tohover)

**Comment by oleedd** [comment]
No, it doesn't. Why is infinity loop bad when it is visible? I don't talk about cases when it is not visible and don't know them.

**Comment by Loirooriol** [comment]
Please read the linked article. Selectors can't depend on layout (unless some constraints are apply like in container queries). Otherwise it would be circular, which is bad, for the reasons explained there. I don't know what you mean with visible or non-visible cases.

**Comment by oleedd** [comment]
I have read it several times. Browsers blink on infinity loop, then it is visible and will be fixed. Why is it bad? Idk about invisible loops but the article talks a little about this.

**Comment by Loirooriol** [comment]
`:hover` is not great but is not bad, just a dependency on hit-testing. A dependency on layout is what's really bad.

**Comment by oleedd** [comment]
And why is `:viewport` bad? Browsers will blink the same way as at `:hover`. The developer will see the problem and fix it. And it is much more unlikely to make a mistake and loop this.

**Comment by Loirooriol** [comment]
Just reading you description:

> To select elements which are in viewport at the moment - user can see them (or its position if hidden) without scrolling.

So you want to select elements depending on whether they have a non-zero intersection with the viewport, or something along these lines. This is a dependency on layout. It's not like `:hover`.

**Comment by oleedd** [comment]
Ok, I have a solution.
The article says about disallowing properties which can cause a loop. It is a bad idea because too many checks. And these properties may be used correctly, without a loop.
The solution:
Browsers should detect css loops and stop such rules and notify about the problem. For example, they detect JavaScript loops and stop them with a an error.

**Comment by oleedd** [comment]
Ok, I have a solution.
The article says about disallowing properties which can cause a loop. It is a bad idea because too many checks. And these properties may be used correctly, without a loop.
The solution:
Browsers should detect css loops and stop such rules and notify about the problem. For example, they detect JavaScript loops and stop them with an error.

**Comment by oleedd** [comment]
Ok, I have a solution.
The article says about disallowing properties which can cause a loop. It is a bad idea because too many checks. And these properties may be used correctly, without a loop.
The solution:
Browsers should detect css loops, stop such rules and notify about the problem. For example, they detect JavaScript loops and stop them with an error.

**Comment by Loirooriol** [comment]
Detecting loops at run-time is already covered in the article:

> Yet another way you could try to remediate all this would be to do a run-time detection of whether there is a loop in that particular page and disable all the selectors (or properties) involved in that loop. However, this check would have a performance impact, would still have the confusing and hard to debug “action at a distance” problem, on top of which it would require significant changes in browser architecture.

**Comment by oleedd** [comment]
It is not hard for browsers now. They are very smart now. I think that this opinion is outdated. If they can detect js loops, they can do this for css loops too.

**Comment by oleedd** [comment]
And they should do this only for rules with such selectors, not for all. Not a big problem.

**Comment by tabatkins** [comment]
Your question has been fully answered by Oriol. This precise idea has been rejected in the past, and gets suggested so often that we have an explicit FAQ entry for it. All of the reasoning in the FAQ still applies today.
