### ISSUE TITLE
[css-sizing-4] Use cases for explicit intrinsic-size

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4585]
This issue is to collect use cases for overriding the intrinsic size of an element with some other value. Branched off of https://github.com/w3c/csswg-drafts/issues/4531#issuecomment-564655162

**Comment by chrishtr** [comment]
@dbaron @bfgeek 

Quick reminder to add use cases you can think of.

**Comment by chrishtr** [comment]
Second quick reminder. The plan of record is to review found use cases at the CSSWG meeting next week and use the results to choose the API shape for intrinsic-size in #4531 .

**Comment by dbaron** [comment]
So [Mozilla bug 433621](https://bugzilla.mozilla.org/show_bug.cgi?id=433621) was filed to request such a property.  It came from [Mozilla bug 402567](https://bugzilla.mozilla.org/show_bug.cgi?id=402567) which was about choosing **different options for whether to pass intrinsic width up through scrollframes**.  This feature seemed to be requested specifically for tables in [Mozilla bug 409736](https://bugzilla.mozilla.org/show_bug.cgi?id=409736), and also in [Mozilla bug 415533](https://bugzilla.mozilla.org/show_bug.cgi?id=415533), which seems to be about the particular case of tables that vary in width but wish to clip/scroll the content of cells when they're wide, but still size to the content of those cells if they're narrow.  These were also tied to [Mozilla bug 407257](https://bugzilla.mozilla.org/show_bug.cgi?id=407257) which was a layout bug in Firefox in GMail's contacts pane.  A similar behavior was also explicitly requested by a developer in [Mozilla bug 442330](https://bugzilla.mozilla.org/show_bug.cgi?id=442330).

**Comment by dbaron** [comment]
I'd note, however, that the scrollframes thing came up multiple times specifically because we *changed* behavior, so developers saw that multiple options were possible and wanted the ability to choose between them.  I still think there are other usecases that exist but that people aren't raising because they don't see the possibilities.

**Comment by cbiesinger** [comment]
So I think dbaron's use case is actually pretty different from what we want for the contain:size version of the property.

For contain-intrinisic-size, we want to be able to specify explicit lengths to apply while contain:size is present.

For dbaron's use case, you want 2-3 keywords to control how intrinsic sizes bubble upwards. Sort of, but perhaps not exactly, like the auto vs legacy keywords in the draft.

So I would propose:
- Add a property intrinsic-size-control: foo|bar|baz (...I'm not good with names), for dbaron's use cases.
- Add contain-intrinsic-size for the use cases in https://github.com/w3c/csswg-drafts/issues/4531

These are pretty independent from each other and can be shipped separately.

Unfortunately I'll have to miss the discussion at tomorrow's f2f.

**Comment by fantasai** [comment]
So far I'm seeing several desired behaviors:
- current behavior (for Web-compat reasons)
- zeroing out the min-content contribution of scrollframes (see dbaron's comment above and https://github.com/w3c/csswg-drafts/issues/1865)
- zeroing out the min-content contribution when there's a percentage size (to emulate replaced elements) https://github.com/w3c/csswg-drafts/issues/5549

**Comment by fantasai** [comment]
None of these are explicit values, though, just different behaviors. So what we'd be looking at is a property with keyword values.

**Comment by fantasai** [comment]
@jensimmons brought up an interesting use case around responsive typography, e.g. using variable axes to reduce the width of the text in the top row to match the size of a column whose width is dictated by the rest of its contents and not the content in the top row.

Looking deeper, however, this would be a case where dropping all the way down to zero isn't actually what we'd want: that would create overflow if the rest of the contents were too narrow and/or make the text unreadably narrow. So what's really desired in this case is to set the min-content size to a percentage of what it otherwise would be, e.g. if the text is 25% compressible without affecting readability, set the min-content size to 75% of what it otherwise would be. So another possibility we might consider is allowing the the min-content size property to take a percentage, which represents that percentage of what it otherwise would be. (Alternatively, maybe the min-content calculations can themselves account for the compressability. But just wanted to note the use case here for further thought.)
