### ISSUE TITLE
[css-sizing] Revert 45d4464, it violates the resolution from #2708

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4587]
#2708 had a clear resolution: intrinsic keyword values in the block axis should just behave as `auto`, but not compute to `auto`. The spec was changed in b603bfb33da70080b83f78e74f41c8af89b9b88b.

Later, #3973 asked to obey the intrinsic keyword values instead of making them behave as `auto` in the block axis. 45d4464388696ff6d98f1f2fa8be8ca04dae0f26 was supposed to do this change but:
 - It just made intrinsic keywords compute back to `auto`, basically reverting b603bfb33da70080b83f78e74f41c8af89b9b88b, against the resolution from #2708
 - It didn't address #3973 either, since computing to `auto` implies behaving as `auto`.
 - The changes did the opposite of what the commit message said

Please revert it. CC @tabatkins, @fantasai

**Comment by fantasai** [comment]
Deferring discussion back to #3973.
