### ISSUE TITLE
[css-highlight-api] negative priorities

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4593]
Assuming we continue having numerical priorities (see #4591):

* If priorities are stored as integers (see #4592), should we allow negative ones?

* If negative integers or doubles are used, does a negative priority mean placement below the built-in highlights in the stacking order, and a positive number above them?

**Comment by hober** [comment]
If we go with numbers at all for this, I think we should allow negative numbers. A library author may want to say "my feature is cool, but if anything else is using the highlight api on this page, they should win over me."

**Comment by sanketj** [comment]
@frivoal @hober @fantasai I don't see any additional problems with negative numbers, my thought is that we should allow them. That would be consistent with z-index. Are you all okay with that?

**Comment by frivoal** [comment]
yes, let's allow them.

**Comment by sanketj** [comment]
Left the priority attribute as (implicitly) 'signed'. Closing this issue.
