### ISSUE TITLE
[css-color-adjust] Used color-scheme should affect the root element color, not initial color

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#4608]
The current spec draft says in chapter 2 that the following must match the users preferred color-scheme:

"the initial color of the background canvas find what we name this in other specs, the initial value of the color property, and the system colors".

For the color property, this does not match what Safari, and Chrome behind a flag, implements. Instead there is a UA rule setting a system color for the root element whose used value depends on the used value of color-scheme. Both implementations have a used value for color:initial of black (as per the css-color spec) regardless of color-scheme.

Proposal: change the spec to say that the color is a system color(?) set on the root element for UA style whose used value is based on the used color-scheme.

**Comment by tabatkins** [comment]
I'm inclined to still consider this a bug in the current engines - what would be the purpose of making `color: initial` still produce black in dark-mode?  Is there some implementation difficulty in adjusting this value?

Notably, a current weirdness of the styling for our specs has (for some reason) all the index terms styled with an explicit `color: initial;`, which is causing some minor problems in our attempt to switch to dark mode. If `initial` adjusted based on color-scheme it would fix that. I suspect many uses of `color: initial` on the web are the same, and would work better if the `initial` value adjusted itself.

**Comment by tabatkins** [comment]
Brought up privately by @lilles: Right now, both Chrome and Safari's actual used value for the root color is a used-time-resolving color (`text` for Safari, a UA-sheet-only prefixed value for Chrome), so it'll switch between dark and light depending on the `color-scheme` value in effect for a given element. I think that's what we want the default to be.

I think the resolved value of the various color-taking properties are defined to present the used value, tho, so they'd still be `black` in gCS() for light-mode. So I'm not sure exactly what our compat constraints are here.

Can we just change the initial value of 'color' to be `text`?

**Comment by AmeliaBR** [comment]
> Can we just change the initial value of 'color' to be text?

[`CanvasText`](https://drafts.csswg.org/css-color/#valdef-system-color-canvastext), but yes, that sounds like the most sensible solution. Resolved value would be RGB (consistent with resolution in https://github.com/w3c/csswg-drafts/issues/3847#issuecomment-547990842), so no observable difference unless using color schemes or using TypedOM to distinguish between computed and resolved.

It could also be consistent with the current behavior in Firefox, which still allows users to set their preferred initial text color (which is used both for the root and for `color: initial` in general). The user settings could be applied as a customization of the system color scheme.

In contrast, making the initial value of the property be color-scheme dependent seems kind of weird from a cascade perspective.

**Comment by lilles** [comment]
css-color-4 spec changed as per resolution with wpt test landed. No need to change the css-color-adjust spec as that already referred to the initial value of the color property.
