### ISSUE TITLE
[css-pseudo] Who is currently using CSSPseudoElement and what events can target them?

### ISSUE THREAD

**Issue by sanketj** [w3c/csswg-drafts#4619]
As far as I understand, the main motivation for making CSSPseudoElement an EventTarget was the web animations API. However, the web animations spec has since dropped its dependency on CSSPseudoElement (#4437 ). So I was wondering if there are any other specs that currently depend on  CSSPseudoElement, and whether there are any spec'ed events that have a CSSPseudoElement target?

**Comment by Loirooriol** [comment]
It's not clear if web animations can get rid of CSSPseudoElement in the nested case, see #4487

**Comment by frivoal** [comment]
As far as I can tell, this is more of a question than an issue, and we're trying to get people's attention to answer it. Since Github alone hasn't worked so far, Agenda+ to draw attention to it.

**Comment by hober** [comment]
cc @graouts @megangardner

**Comment by graouts** [comment]
Web Animations was using `CSSPseudoElement` for a while but that dependency was removed to be able to move towards finalization of Web Animations 1.0.
