### ISSUE TITLE
[css-highlight-api]: Highlight constructor should accept 0 or more AbstractRanges instead of an optional sequence

### ISSUE THREAD

**Issue by sanketj** [w3c/csswg-drafts#4620]
This can be achieved with the `...` syntax, like append/prepend use here: https://dom.spec.whatwg.org/#parentnode. If more than one highlight need to be added, they can be specified with additional parameters. This will avoid having to create a sequence when creating a Highlight with one range object.
So we would be able to do:
```
    let highlightRange = new Range();
    let highlight = new Highlight('example-highlight', highlightRange);
    CSS.highlights.add(highlight);
```
instead of:
```
    let highlightRange = new Range();
    let highlight = new Highlight('example-highlight', [highlightRange]);
    CSS.highlights.add(highlight);
```

**Comment by sanketj** [comment]
@frivoal I'm happy to take care of this if you're okay with it.

**Comment by frivoal** [comment]
Thanks, that's an excellent suggestion, much better than what I had.

**Comment by frivoal** [comment]
It was an easy fix, so I just went ahead and did it. Sorry, I probably should have let you do it since you offered to and it's your suggestion… 🙇
