### ISSUE TITLE
[css-color] gray() function produces a  warm, D50 white

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#4622]
The gray() function is defined in terms of CIE Lab, with the a and b chromatic axes set to 0. In the spec currently, Lab is defined relative to a D50 whitepoint, in accordance with typical (print) industry practice and for compatibility with most spectrophotometer default settings.

In consequence, `gray(100)` will give an `Lab` value of 100 0 0

```
D50 = [100, 0, 0];  // Lab 100 0 0
Array(3) [ 100, 0, 0 ]
D50_XYZ = Lab_to_XYZ(D50);  //Convert to CIE XYZ
Array(3) [ 0.96422, 1, 0.82521 ]
D50_XYZ_D65 = D50_to_D65(D50_XYZ); // Bradford chromatic adaptation transform from D50 to D65
Array(3) [ 0.9504700036079999, 1.0000000624270002, 1.088830036462 ]
D50_RGB = gam_sRGB(XYZ_to_lin_sRGB(D50_XYZ_D65));  // convert to sRGB
Array(3) [ 0.9999999809955643, 1.000000034987241, 1.0000000100781432 ]
```
this gives an sRGB value of 
`rgb(99.99999809955643% 100.0000034987241% 100.00000100781432%)`
which will be clipped on `g` and `b` to 100%
but is a warm white. 

Converting the D65-adapted white back to Lab:

```
wrong = XYZ_to_Lab(D50_XYZ_D65);  // convert unadapted XYZ to Lab
Array(3) [ 100.00000241384396, -2.388102770071454, -19.362232628332656 ]
```

The difference is certainly noticeable (ΔE 2000 is 13.64).

**Comment by jrus** [comment]
> but is a warm white.

1 part in 20 million doesn’t seem like an unreasonable rounding error ...

> Converting the D65-adapted white back to Lab:

You didn’t do the reverse chromatic adaptation from D65 back to D50 so this is expected.

**Comment by jrus** [comment]
> If you want to short circuit it and avoid stray rounding errors you could explicitly implement a univariate function taking in L* and spitting out three identical values for sRGB. 

To be explicit, you can first convert L* to XYZ Y (still D50 whitepoint), then you can combine the steps of taking Y -> XYZ, i.e. Y -> [0.34567Y / 0.35850, Y, 0.29583Y / 0.35850], whatever chromatic adaptation matrix you like, and a conversion from XYZ -> RGB; this can be distilled down to a single scalar to multiply by the D50 Y value to get the D65 RGB values. Finally you can apply your RGB gamma function.

**Comment by tabatkins** [comment]
Sorry to say this in a way that is going to sound rude, but: what's your point here, Chris?  ^_^

As @jrus says, the deviation here from pure sRGB white is ridiculously small, *far* below the threshold which would produce rendering differences.

Even if it did produce something that would round to a unit of difference between the channels, is that an issue?

**Comment by jrus** [comment]
It might however be worth explicitly pointing out in the spec that you can simplify this down to two nonlinear functions applied to a single value and then spread across three outputs, cutting out the matrix multiplications and redundant gamma and L* functions.

**Comment by svgeesus** [comment]
> Sorry to say this in a way that is going to sound rude, but: what's your point here, Chris? ^_^

My points were twofold:

- its wrong, and undesirable, and doesn't give `rgb(100% 100% 100%)` at maximum
- it ties into an issue that I am about to open, based o technical feedback from the ICC, which is that the chromatic adaptation to D50 makes sense in a print, print proof, soft-proof environment but can, and should, be skipped in a primarily display-oriented environment where all the common spaces use a D65 media white.

**Comment by svgeesus** [comment]
> So in short: this transformation boils down to 2 steps:
>
>    Apply the nonlinear transformation L* ↦ Y
>    Letting linear R = G = B = Y from step 1, apply the gamma encoding to convert RGB ↦ R′G′B′.

That is a transformation in XYZ, which is a von Kries chromatic adaptation.

**Comment by tabatkins** [comment]
> My points were twofold:

kk, these are reasonable then. I'm still somewhat curious about how a deviation from triple-100% by ~a millionth of a percent is something to worry about, but if it's just a technical bugaboo you want to fix, sounds fine.

Does the D65 white give exactly-100% answers?

**Comment by svgeesus** [comment]
> Does the D65 white give exactly-100% answers?

Yes.

**Comment by smfr** [comment]
If we change gray() to use a D65 white point, are we also going to change lab() and lch() to use the same white point?

**Comment by svgeesus** [comment]
Yes, we would.

My only hesitation is that spectrophotometers give an Lab readout relative to a D50 white (as they are primarily used in the print industry, and by designers working with print, which has had reliable color management for a couple of decades). 

I have asked a contact at X-Rite whether their spectros can be optionally  set to give a D65 readout. I'm currently traveling and don't have access to my i!Pro 2 to try it out.

**Comment by jrus** [comment]
> If we change gray() to use a D65 white point, are we also going to change lab() and lch() to use the same white point?

It doesn’t matter either way. The end result of gray() in any arbitrary whitepoint composed with a Bradford-style CAT is going to result in exactly the same output.

That was the point of my previous comment.

**Comment by svgeesus** [comment]
> (except for trivial rounding errors on the order of whatever rounding you applied to your matrix coefficients).

Yes, the rounding errors are what I was seeing.

@jrus thanks for your thoughtful comments which are much appreciated. This particular issue is now closed, because the CSS WG decided today to remove the `gray()` function entirely, but I encourage you to send further review comments on this specification. I would also encourage you to join the [Color on the Web Community Group](https://www.w3.org/community/colorweb/).
