### ISSUE TITLE
[css-pseudo-4] Painting selection background outside inline replaced content

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4624]
@TalbotG noticed that Blink paints the area below a baseline-aligned highlighted image, but Firefox does not. Currently the spec only allows painting highlights within the border box of an image; should we adjust it to allow painting within the full height of the line box for inline replaced elements or somesuch?

**Comment by TalbotG** [comment]
> Blink paints the area below a baseline-aligned highlighted image, but Firefox does not.

Test:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-045-new.html

Expected result:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/ref-nothing-below.xht

**Comment by kojiishi** [comment]
This is intentional, Blink wants to paint the whole line box, and also gaps between lines when lines wrap.

I believe WebKit has the same behavior too, no? @litherum

**Comment by TalbotG** [comment]
Epiphany Technological Preview 3.34.0-32-g514d1bfb6 (WebKitGTK 2.26.1) has the same behavior as Blink (Chromium 78 and 81); it paints the whole line box.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/a414c09598705843fadce743ad5fe30c790b253f via  https://github.com/w3c/csswg-drafts/issues/5395
