### ISSUE TITLE
[css-pseudo-4] Original color of highlight pseudo inside ::first-letter/::first-line

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4625]
Currently, if an author specifies a background color for selection highlights but does not specify a `color`, we use the color of the originating element.

This gets really interesting in the presence of ::first-letter or ::first-line... basically, highlighting the text changes its color, because it's now looking up the color of the paragraph element instead of the ::first-letter or ::first-line element.

Probably this behavior would be OK in the case of selections, but it's probably quite unexpected if we're handling ::spelling-error or ::grammar-error. It would mean that a spelling error in the first line would end up with the paragraph text color even if the rest of the line has its own color.

What do we want to do about this?

Issue found via @TalbotG’s proposed test active-selection-027 in https://github.com/web-platform-tests/wpt/pull/20028 see [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=7628)

**Comment by TalbotG** [comment]
Original test:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-027.html

and its reference:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-027-ref.html

**Comment by TalbotG** [comment]
Blink and Gecko differ in their renderings of these 2 tests.

Active selection and first-letter pseudo-element tests:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-024-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-025.html

Reference files:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-024-ref-new.html

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-025-ref.html

**Comment by heycam** [comment]
I think it's preferable to take the color from the ::first-letter/line pseudo, for both regular selections and spelling highlights.  Same for generated content pseudos, if a browser supports selecting in those.

**Comment by chrishtr** [comment]
Update: I followed up with some other Chromium engineers and we concluded it wouldn't be too hard to implement this resolution.

**Comment by TalbotG** [comment]
New tests based on this resolution:

active selection, `::first-letter` and no `'color'` declaration, only `'background-color'`:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-025-new.html

Reference file:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-025-ref-new.html

active selection, `::first-line` and no `'color'` declaration, only `'background-color'`:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-027-new.html

Reference file:
http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/active-selection-027-ref-new.html
