### ISSUE TITLE
[css-pseudo-4] Layering of highlight pseudo backgrounds

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4626]
Currently the spec specifies that e.g. if ::selection and ::spelling-error and ::grammar-error all apply to the same piece of text and each specifies a background color, these are layered, which will be noticeable if any of them are semi-transparent.

Just want to confirm that this is the model we want. (The alternative would be that only the topmost color paints, unless it is the keyword `transparent` or something.)

**Comment by megangardner** [comment]
I believe that is what we want. I would also say that we would want that behavior of layering between custom highlights and ::spelling-error ::grammar-error and ::selection as well.

**Comment by tabatkins** [comment]
Confirm that I think this is what we want. If the pseudos partially overlap, it's valuable to be able to see the distinct boundaries (if the page caters to this by using partially-transparent colors)
