### ISSUE TITLE
[css-text] The computed value and animation type of tab-size

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#463]
The current spec says the computed value of `tab-size` is "the specified integer or length made absolute", however the animation type is "length".

It seems to me animation is based on computed value, which means either `<integer>` value is not interpolatable, or `<integer>` should be converted into `<length>` when it becomes computed value.

**Comment by upsuper** [comment]
I'm pretty sure we don't want to convert `<integer>` into `<length>` for computed value, because that would affects inheritance. It means `<integer>` is not interpolatable... which the spec should probably say explicitly.

**Comment by fantasai** [comment]
This was actually reported in https://www.w3.org/mid/20151022224025.GA28022@pescadero.dbaron.org
and was resolved in https://www.w3.org/mid/CADhPm3u95z0_xB8eRsmv=EGgb8+8yXDEnw-EAVp3eqrGjs9ykQ@mail.gmail.com
and should now be fixed. :)

**Comment by TalbotG** [comment]
@frivoal ,  
Test on computed value of tab-size:

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/tab-size-computed-value-001.html

**Comment by TalbotG** [comment]
Since [PR26981](https://github.com/web-platform-tests/wpt/pull/26981) has been approved and merged, I am removing the Needs Testcase (WPT) label. Leaving the Needs Testcase (WPT) label as is would only contribute to confusion and loss of time.
