### ISSUE TITLE
[css-ruby] Size and position of empty ruby level containers

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#4631]
The spec currently says:
> Each *ruby base container* is sized and positioned to contain exactly all of its *ruby bases*’ margin boxes.

and
> Each *ruby annotation container* is sized and positioned to contain exactly all of its *ruby annotations*’ margin boxes.

However, it is unclear what should happen when a ruby level container doesn't have any child.

I suggest that for empty ruby base container, it should probably behave as if there is an empty ruby base inside, so that it would laid out like a normal empty inline element.

I'm not sure what would be a useful behavior for ruby annotation container. I kinda tend to think that it should keep being zero size in that case, but we may need to define its position somehow as well?

This issue is raised because of [a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1603354) to Gecko after I [changed the behavior](https://bugzilla.mozilla.org/show_bug.cgi?id=1565681) to match the spec.

**Comment by fantasai** [comment]
> I suggest that for empty ruby base container, it should probably behave as if there is an empty ruby base inside, so that it would laid out like a normal empty inline element. 

I agree with this 100%. Ruby shouldn't lay out differently on an empty base vs. a zero-width glyph.

> I'm not sure what would be a useful behavior for ruby annotation container. I kinda tend to think that it should keep being zero size in that case, but we may need to define its position somehow as well?

I think we might want to go with the same principle, lay out as if it contained a zero-width glyph. Otherwise stacking levels could get confused.
