### ISSUE TITLE
[css-sizing-4] "scroll container" probably needs to be more precise.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#4635]
https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum

It is possible for something to be a scroll container along one axis, e.g. "overflow-x: auto". This rule probably only wants to apply when the "ratio-dependent axis", is the same as the scroll container axis?

**Comment by Loirooriol** [comment]
It's not possible, see https://drafts.csswg.org/css-overflow-3/#overflow-properties

Only the `visible` and `clip` values avoid a scroll container, and

> Computed value: as specified, except with `visible`/`clip` computing to `auto`/`hidden` (respectively) if one of `overflow-x` or `overflow-y` is neither `visible` nor `clip`.

The `overflow-x: auto` that you mention behaves as either `scroll` or `hidden`, both of which make a scroll container (even if there is no scrollbar, you can scroll with JS).
