### ISSUE TITLE
[css-sizing-4] Give explicit control to author for "minimum" aspect-ratio, vs. "strict" aspect-ratio?

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#4636]
https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum

There are two clear use cases for AR. One where it applies as a "minimum" and one where it is "strict" (always maintains the aspect-ratio).

It is common for a web developers to apply a "max-height: 100px;" rule to scrollable containers. E.g.
```html
<div style="width: 100px; aspect-ratio: 1/1; max-height: 200px;">
   content
</div>
```

In the above example you aren't able to specify that you'd like the aspect ratio to apply as a minimum, i.e. if  "content" is 120px high it'll trigger scrollable overflow, when they may want to to reach 200px before overflow is triggered.

Is it worth having an explicit keyword for giving control over this behaviour? E.g. `aspect-ratio: 1/1 strict;` 

A potential similar usecase applies when using the min-height in this manner. E.g. a "minimum" aspect-ratio, with a min-height rule.

**Comment by dvoytenko** [comment]
This behavior makes sense to me, but I'd reverse it and make it `strict` mode default.

**Comment by fantasai** [comment]
This was discussed already in https://github.com/w3c/csswg-drafts/issues/3268 ; see

Minutes: https://lists.w3.org/Archives/Public/www-style/2019May/0009.html
Spec: https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum

I think it should give pretty reasonable behavior in most cases. Does this address your use case?

**Comment by fantasai** [comment]
Closing out since the use case is addressed. Open an new issue with an explanation of what you want changed if the current spec is insufficient?
