### ISSUE TITLE
[css-sizing-4] Give examples for how the aspect-ratio affects the {min,max}-content size of a box.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#4637]
https://drafts.csswg.org/css-sizing-4/#ratios

E.g.
```
<div style="height: 100px; aspect-ratio: 1/1;">
  <span style="display: inline-block; width: 50px;"></span>
  <span style="display: inline-block; width: 150px;"></span>
</div>
```

And how this affects other things like the flex algorithm.

**Comment by cbiesinger** [comment]
Especially it would be useful if the spec were clearer on how the min/max content contribution is affected by aspect ratio

**Comment by fantasai** [comment]
So I think given https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum the way this works is:
1. `width: auto` is resolved to `width: 100px` on the container.
2. If the `min-width` is `auto`, then it resolves to `150px` and thereby increases the min-content size and contribution of the container. If the `min-width` is set to zero (or any value <= 100px), then it has no effect.

**Comment by fantasai** [comment]
Clarified that `auto` means "assume no intrinsic size" when applying aspect ratio calculations.

**Comment by fantasai** [comment]
@bfgeek @cbiesinger  Closing as fixed. Re-open if something remains unclear.

**Comment by bfgeek** [comment]
```<div style=”height: 100px; width: auto; max-width: min-content; aspect-ratio: 1/1;”></div>```

Should the width of this element by 0px or 100px;

**Comment by tabatkins** [comment]
Given the discussion in #5032, it should be 100px.
