### ISSUE TITLE
The opacity property should affect nothing but opacity

### ISSUE THREAD

**Issue by tobireif** [w3c/csswg-drafts#464]
The opacity property should affect nothing but opacity.

In some cases, setting/changing opacity changes the stacking order / changes which items overlap which. That is very surprising for the user of your technology / the SVG/web developer, and it is very inconvenient because it can require time and effort to work around the issue.

Please make sure that the presence or absence of any opacity values never affect anything except opacity.

**Comment by frivoal** [comment]
Thanks for the feedback. Even though the behavior you describe can be counter intuitive, there are justifications for it. However, debating the pros and cons of these justifications and side effects is a moot point: this has worked this way for a long time, so many web sites depend on this behavior, would break if browsers were to change.

**Comment by fantasai** [comment]
Closing, as this is something we can't fix even if we wanted to, not without a time machine...

**Comment by tobireif** [comment]
Please re-open, and please see https://github.com/w3c/svgwg/issues/264 - the discussion happens there, and is 100% relevant to CSS (not just SVG).

**Comment by tabatkins** [comment]
As I explained in the SVG bug, and just re-explained with more detail, it's literally impossible to do so.  This bug won't be reopened.

(We can't even fix it with a time machine, @fantasai, unless by that you mean "make opacity a leaf effect only", which is just giving a different effect, not fixing the problem. ^_^)
