### ISSUE TITLE
[dialog element] <dialog> positioning should be describable in CSS

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#4645]
HTML describes the ["centered alignment" of a dialog element](https://html.spec.whatwg.org/multipage/interactive-elements.html#centered-alignment) in somewhat opaque prose.

Blink's implementation of this is a [hack in their rendering code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/layout/layout_block_flow.cc?q=ComputeAbsoluteDialogYPosition&ss=chromium&originalUrl=https:%2F%2Fcs.chromium.org%2F)

This needs to be described in terms of CSS (ideally as some rules in the UA stylesheet). Apparently it's not implementable in CSS, which is a problem. First, UAs should not have to add custom layout code for the dialog element, and second authors should be able to achieve the same positioning behavior for their own elements.

**Comment by annevk** [comment]
There's also `<center>` and `<div align>`, which use https://html.spec.whatwg.org/multipage/rendering.html#align-descendants apparently. Seems weird indeed that HTML has so many non-CSS centering mechanisms.

**Comment by tabatkins** [comment]
`<center>` and `[align]` *should* both be describable via `justify-items: legacy center;` (/`legacy right` or `legacy left`); that's what we designed those values for. It does depend on browsers implementing `justify-self` on `display: block`, which hasn't happened yet. We'd be very interested to know if there are quirks we aren't handling there.

As for `<dialog>`, if I'm reading it correctly it means:

* at the time the dialog is first rendered, lay it out as an abspos non-replaced element.
* if the height is less than the height of the viewport, center it in the viewport, adjusting 'top'/'bottom' appropriately to achieve this. (Note: abspos positioning, *not* fixpos positioning! Scrolling the viewport should allow the dialgo to scroll off the screen!)
* if it's taller than the viewport, adjust 'top'/'bottom' to align it with the block-start edge of the viewport.
* if the size of the viewport changes, redo the layout+centering
* if the dialog stops being rendered, then starts again (display:none then non-none, for example), redo the layout+centering

I think that's it?

So the centering behavior, first, is a basic `align-self: safe center;` into the alignment container. 

The missing piece is just setting up the alignment container, as neither abspos nor fixpos give the desired rectangle.  This instead requires a stateful rendering-sensitive "snapshot" of the current viewport position relative to the rest of the document. The timing issue already exists for things like animations, which start their timeline when an element first generates a box, so we can lean on that concept.

I forget - I think dialog is supposed to display in the top layer, too? Is that a necessary thing to capture here?

**Comment by smfr** [comment]
Top layer rendering is clearly speced, so this is just about positioning.

**Comment by annevk** [comment]
(Though note https://fullscreen.spec.whatwg.org/#rendering. Moving that to CSS would be appreciated as well.)

**Comment by keithjgrant** [comment]
I would love to be able to transition/animate these in _and_ out, too, though that may be a separate problem altogether

**Comment by fantasai** [comment]
Details on the proposal:
* The dialog is assigned to the "top layer" (which needs to be defined in css-position-3 once it's rewritten).
* DOM snapshots the top/bottom of the viewport as inset property values when the dialog is opened, and rewrites those values if the viewport is resized.
* The dialog is also assigned `align-self: safe center`; this takes care of the centering within the viewport.

I think the one question I can think of wrt CSS interaction is where the `inset` values are injected, if it's at the preshint level or into the style attribute or something else. Depends on what's reasonably implementable and what's reasonably Web-compatible...

@keithjgrant Together with selecting on [open], I think this should allow for animations and transitions of most aspects of dialog layout.

@annevk Does that make sense, or do you need more info for the HTML spec parts of this?

**Comment by annevk** [comment]
That sounds like an okay plan. I'm not sure I understand "Closed Accepted by CSSWG Resolution" as there still seems to be quite a bit of work outstanding.

@tabatkins for `<center>` and `align=""`, is there some issue to track on that?

**Comment by keithjgrant** [comment]
> Together with selecting on [open], I think this should allow for animations and transitions of most aspects of dialog layout.

When browsers first added support, this allowed for animating in, but not animating out. Once the dialog closed, it was immediately removed from view by the browser and no CSS I tried was capable of altering this behavior...

This still seems to be the case in Chrome, though Firefox has improved things a little. In Firefox, `display: block` can be used to show a "closed" dialog (so e.g. a fade-out animation can be applied on close). Firefox positions the dialog with an inline `top` and `z-index`, which are only added while open, so these would have to be manually re-calculated to match after the close attribute is removed. In any case, it seems browsers are taking a kind of "whatever works" approach to how these are styled & stacked in a top rendering layer — getting those clearly defined will be a win.

**Comment by SebastianZ** [comment]
> This still seems to be the case in Chrome, though Firefox has improved things a little.

It has to be said that [Mozilla has not shipped its implementation yet](https://bugzilla.mozilla.org/show_bug.cgi?id=840640).

> In Firefox, `display: block` can be used to show a "closed" dialog (so e.g. a fade-out animation can be applied on close). Firefox positions the dialog with an inline `top` and `z-index`, which are only present while open, so these would have to be manually re-calculated to match after the close attribute is removed.

As far as I can see, `top` and `z-index` are not set inline, at least on Windows 10, though [here are the styles](https://searchfox.org/mozilla-central/rev/f36cb2af46edd2659f446b7acdb2154e230ee445/layout/style/res/html.css#813-830) that are currently used for the element:
![Dialog element styles in Gecko](https://user-images.githubusercontent.com/958943/76678396-cc688f80-65d7-11ea-9f0c-c14d17f92080.png)

Sebastian

**Comment by keithjgrant** [comment]
Oh right. I forgot I'm on FF Nightly here

**Comment by fantasai** [comment]
@annevk That mapping is covered by https://github.com/whatwg/html/issues/3428

Afaict, this issue is basically solved on the CSS side, except insofar as the "top layer" is still defined in Fullscreen rather than in a CSS spec. If that should be moved over, it deserves its own issue since it's not about DIALOG specifically...

I'll copy over the conclusions from this issue into the WHATWG issue.

**Comment by fantasai** [comment]
Filed the "define Fullscreen rendering in CSS" issue in https://github.com/w3c/csswg-drafts/issues/4998

**Comment by emilio** [comment]
@fantasai @annevk what about having two attributes on the dialog that map to these properties? That would reuse the general attribute-mapping mechanism which seems sane to me.

**Comment by emilio** [comment]
(This is about the viewport insets, of course).

Context: Gecko is looking at implementing dialog positioning, and having a layout engine hack seems really sad.

**Comment by emilio** [comment]
We could potentially also do it without magic attributes and just storing the offsets in the `HTMLDialogElement` instance itself, I guess, then injecting the rules in the cascade at the pres hints level, but I'm not sure if there's a precedent for such a thing.

**Comment by annevk** [comment]
So to be clear, the problem here is

> DOM snapshots the top/bottom of the viewport as inset property values when the dialog is opened, and rewrites those values if the viewport is resized.

right? It wasn't entirely clear to me how we would implement that specification-wise. Are new values that act like that another possibility we could consider? If this is a useful primitive, I'm not sure why CSS shouldn't offer it natively.

(Using content attributes for styling seems to go against separation of markup and style, but I might be misunderstanding something. Your final solution would work, but would still make HTML own some layout logic it probably shouldn't.)

**Comment by emilio** [comment]
So the current thing is pretty weird. As far as I can tell, fixed dialogs are not an issue, but abspos dialogs somehow depend on the current root scroll position from where the dialog is open.

Implementing this in the layout engine itself is pretty unfortunate IMHO. Also the current specified behavior of repositioning whenever the viewport size changes has some pretty weird effects in presence of scrolling. (You position the dialog, scroll down so that the dialog is out of view, resize the window and the dialog is back up again, that looks borked).

Can we discuss alternatives?

 * Either snapshot the state in the DOM, and make DOM read the scroll position from `showModal()` and maybe react to resizes and such. Probably such a declaration would be inserted in the presentational hints level in the cascade, so that authors can override it.

 * Maybe, instead, make dialogs have something like `max-height: 100vh`, and force them to be scrollable? That makes fixed-positioned dialogs more sound / appealing. I need to admit I'm not sure what the usecase for an absolutely positioned dialog is in the first place, that's not how any other dialog like OS dialogs work, afaict.

@smfr I wonder what your thoughts on this are?

**Comment by emilio** [comment]
(Tagging as agenda+ as I to double-check with the working group whether the resolution above still stands, how it would behave for abspos dialogs, and if so, what are the specifics of how the snapshotted offsets end up in the cascade)

**Comment by smfr** [comment]
My preferred approach would be to always host the dialog inside a position:fixed container and describe something that makes the dialog scrollable if taller than the screen. But I'm not sure that gives the desired positioning behavior. I'm not a fan of the "snapshot the scroll position" approaches.

**Comment by smfr** [comment]
Dumb question: what is the dialog's containing block for a modal dialog?

**Comment by emilio** [comment]
> My preferred approach would be to always host the dialog inside a position:fixed container and describe something that makes the dialog scrollable if taller than the screen.

I agree actually! So maybe the dialogs should just be `max-height: 100vh; overflow: auto;` or something of that sort. Was that something like what you had in mind? Or some other kind of magic?

> Dumb question: what is the dialog's containing block for a modal dialog?

I think right now it depends, if it's fixedpos it'd be the viewport, if it's abspos it'd be the ICB.

**Comment by smfr** [comment]
Part of the desire here was 

> authors should be able to achieve the same positioning behavior for their own elements.

so if we allow the abspos behavior, we should also add some new CSS to allow authors to apply this to their own elements. That's not something I relish doing, since we'd then probably need the same special-casing for all the properties that force containing-block-for-positioned-descendants (filters, transforms etc).

This is a strong argument to just go with the fixed pos approach. Do we know if the "should be able to scroll the dialog out of view" behavior is a strong requirement? Who came up with it?

**Comment by annevk** [comment]
Here's some of the history found through `git log --grep=dialog` in rough chronological order:

* https://github.com/whatwg/html/commit/2fb24fcf3f916236e8767e2cb72b23e5c75b77e9
* https://github.com/whatwg/html/commit/2a390c07ba4256a9ca59623bd21604293a0ec59a
* https://github.com/whatwg/html/commit/42aa0d1b4e7b76212fdb74f2e9678304e89fd7ab
* https://www.w3.org/Bugs/Public/show_bug.cgi?id=23298
* https://github.com/whatwg/html/commit/3339345f402fa0ad97e1d0416187d7d681a10f74
* https://www.w3.org/Bugs/Public/show_bug.cgi?id=20418
* https://www.w3.org/Bugs/Public/show_bug.cgi?id=24991

Things related to the first commit:

* https://lists.w3.org/Archives/Public/public-whatwg-archive/2012Apr/thread.html#msg26
* https://lists.w3.org/Archives/Public/public-whatwg-archive/2012Apr/0127.html
* https://wiki.whatwg.org/wiki/Dialogs (this seems quite relevant)

I didn't really spot anything that suggested these tradeoffs were considered in detail.

It seems @mattto and @tabatkins were involved so maybe they can provide some context, though it's also been many years.

**Comment by bfgeek** [comment]
I can spend some time adding some use-counters to the Blink implementation to see what is being used. What do folks want to know?

If we can go for position fixed behaviour we could define this as a "center" static-position.

**Comment by gregwhitworth** [comment]
> <dael> TabAtkins: If we ever do want to attach to an element some mech is the thing being used to position non-anchor dialogs. If we switch non-anchor to fixedpos we have to figure out how to do it for non-anchored.

> <dael> iank_: I think a different solution for anchoring down the road

I think we should open a seperate issue for this because authors do want this capability outside of the specific `<dialog>` need (eg: tooltips, dropdown menus, etc). So this should be thought about sooner rather than later. In the research that @annevk shared there are many examples that are not centered and are anchored to an element. While I get the implementation concerns I'm also curious of making the dialog itself the scroller via overflow behavior is the right way. Most of the scenarios that come to mind however normally don't fit in what seems to be the primary definition (based on what is shipping) as a `<dialogue>`.

cc: @melanierichards

**Comment by bfgeek** [comment]
Agenda+ for https://github.com/whatwg/html/pull/5936#issuecomment-704783321

**Comment by fantasai** [comment]
@bfgeek I think this deserves its own issue? Also are there other use cases for `:modal` or is it just for flipping the DIALOG element between `position: absolute/fixed`?

**Comment by LeaVerou** [comment]
Regarding `:modal`, it seems to me that `modal` should really be an attribute, just like `open`. Then, not only would that state be targetable with normal attribute selectors, but with the added benefit of being able to create modals with HTML. It always puzzled me why there is an `open` attribute, but not a `modal` attribute.

**Comment by gregwhitworth** [comment]
+1 to what @LeaVerou - ironically we had this discussion in March of 2019 and likewise wanted an attribute

https://twitter.com/LeaVerou/status/1102862914749452289

**Comment by gregwhitworth** [comment]
> emilio: might want to fix it, but it's a separate issue
> ...
> iank_: I don't think having an attribute API for dialog is a good idea

@bfgeek @emilio @LeaVerou the aspect of open being an attribute 

I would like to call attention to a resolution in Open UI regarding the open attribute/property on the `<select>` that would behave the way in which authors would expect it to (eg: open/close based on the attributes existence).

https://github.com/WICG/open-ui/pull/236

cc: @una @dandclark @melanierichards

**Comment by mangelozzi** [comment]
I see this issue is closed, but I don't understand how one is supposed to position the dialogue? E.g. some wish to position the dialog at the top of the screen?

**Comment by SebastianZ** [comment]
As shown in [my previous comment](https://github.com/w3c/csswg-drafts/issues/4645#issuecomment-599029691), the dialog is centered via `margin: auto;` by default. So, you can position it at the top by adding `margin: 0;`.

Sebastian
