### ISSUE TITLE
[css-color-4] Should gray() accept percentage for lightness?

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#4648]
https://www.w3.org/TR/css-color-4/#grays

As the spec says, `gray(a / b)` is equivalent to `lab(a 0 0 / b)`. However,` lab()` and` lch()` both take a percentage as the lightness argument, but `gray()` is specified to take a number (where 50 is equivalent to 50%). That's confusing if we expect authors to think of gray() as just a shorthand for lab().

So I suggest we spec gray as:
`gray() = gray( <percentage>  [ / <alpha-value> ]? )`

**Comment by AmeliaBR** [comment]
I strongly agree with this. I don't think we have any other color functions where numbers are mapped in the range 0-100. If we're using a 0-100 range, it makes sense to use a proper percentage type.

**Comment by Crissov** [comment]
Yes, this the only logical consequences of #4477 (or #3450 and #278), but pending the resultion of #4621. Furthermore, #4494 would perhaps allow `gray(50%)` to equal `gray(0.5)`, but not `gray(50)`.

**Comment by svgeesus** [comment]
Agreed, this just needs the edits. I made them for `lab()` and `lch()` but failed to also make them for `gray()`.
