### ISSUE TITLE
[css-color-4] Should the color() function accept 'lab' as a color gamut keyword

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#4649]
https://www.w3.org/TR/css-color-4/#color-function

Since we're adding support for lab/lch/gray colors, it seems reasonable for the `color()` function to accept 'lab' as a predefined colorspace (we would need to be explicit about the white point). I also wonder if we should also accept 'xyz'.

**Comment by svgeesus** [comment]
> Since we're adding support for lab/lch/gray colors

Yes, I was very pleased to [see that you were](https://bugs.webkit.org/show_bug.cgi?id=205675)!

>  it seems reasonable for the color() function to accept 'lab' as a predefined colorspace (we would need to be explicit about the white point). 

It could, certainly. That would just be a somewhat more verbose alias for the `lab()` function, right?

```
border-color: lab(65.5% -38.8 -6.9);
border-color: color(lab 65.5% -38.8 -6.9);
```
> I also wonder if we should also accept 'xyz'.

Would that be absolute, or relative to the media white?

**Comment by smfr** [comment]
> It could, certainly. That would just be a somewhat more verbose alias for the `lab()` function, right?
> 
> ```
> border-color: lab(65.5% -38.8 -6.9);
> border-color: color(lab 65.5% -38.8 -6.9);
> ```

Yes, I think so.

> > I also wonder if we should also accept 'xyz'.
> 
> Would that be absolute, or relative to the media white?

I don't know what would be useful to authors. Maybe color() should let you specify the white point?

**Comment by svgeesus** [comment]
Ah. No, XYZ is independent of whitepoint. What I mean is that with relative XYZ, the luminance (Y) is scaled to 100 for the media white; while for absolute XYZ the Y is in candelas per square meter (so can take a very wide range of real-world values).

I'm not sure what XYZ adds, from an authoring standpoint. It is more user-hostile then sRGB (but is at least linear-light, not gamma corrected). I'm aware it is one of the two profile connection spaces in an ICC workflow (the other is D50 Lab), which I suspect is why you suggested it?

**Comment by Crissov** [comment]
> That would just be a somewhat more verbose alias for the `lab()` function, right?
>
>     border-color: lab(65.5% -38.8 -6.9);
>     border-color: color(lab 65.5% -38.8 -6.9);

The current [ED](https://drafts.csswg.org/css-color/#color-function) prescribes `<number>`, i. e. does not allow `<percentage>` (nor `<angle>` #4489) at all, but this should change soon by way of either #3450 or #4494. 

> `color() = color( [ <ident>? [ <number>+ | <string> ] [ / <alpha-value> ]? ]# , <color>? )`

**Comment by LeaVerou** [comment]
On one hand, this is extra testing and documentation work for little benefit.
On the other hand, I can see use cases if the gamut keyword is in a variable. But those cases are rather limited.

**Comment by una** [comment]
It seems like with our limited [examples](https://drafts.csswg.org/css-color-5/) for color modification using lab as a default space, we've been seeing a lot of out-of-gamut results -- would this be a solution to provide fallbacks for those results?

**Comment by svgeesus** [comment]
@una 

> It seems like with our limited examples for color modification using lab as a default space, we've been seeing a lot of out-of-gamut results 

Yes, although partly that is because the examples have been using colors like `red` and `yellow` which are maximally saturated and thus right up against the corners of the RGB color cube. So even a small adjustment tends to push them outside the gamut. More normal real-world colors are less likely to fall outside of gamut when manipulated.

> would this (color()) be a solution to provide fallbacks for those results?

It would, although gamut mapping to the closest in-gamut color is a more foolbroof and automatic method.

I have been wondering too about another function which takes a list of colors plus a colorspace, and returns the set of colors all adjusted together such that the most out of gamut color is *just* inside (and the rest are adjusted too, so their relative relationships are intact).

**Comment by LeaVerou** [comment]
> I have been wondering too about another function which takes a list of colors plus a colorspace, and returns the set of colors all adjusted together such that the most out of gamut color is just inside (and the rest are adjusted too, so their relative relationships are intact).

That's quite manual too. It would be nice to have an opt-in to do this for entire elements automatically.
