### ISSUE TITLE
[css-scroll-snap-1] Snapping on both axes allows re-snap after layout to choose inconsistent snap targets

### ISSUE THREAD

**Issue by yi-gu** [w3c/csswg-drafts#4651]
According to the [spec](https://drafts.csswg.org/css-scroll-snap-1/#re-snap):

> If the scroll container was snapped before the content change and that same snap position still exists (e.g. its associated element was not deleted), the scroll container must be re-snapped to that same snap position after the content change.

The issue is that if there are multiple snap areas aligned on the same axis, then any of those snap areas can be the "associated element" for the same snap position. Therefore the re-snapping after layout could return any one of the snap areas.

Different associated elements for the same snap position should be clarified by the spec.

> Note: re-snapping after layout is currently only available on Chrome M80 and it's behind the flag chrome://flags/#enable-experimental-web-platform-features.

Example:
1. On mobile, go to https://alsan1998.github.io/grid_cats
2. Scroll to snap to the white cat whose coordinate is (1,1).
3. Rotate the phone. Re-snapping works well.
4. Rotate it back. Scroll snap to the cat (1,2) below.
5. Rotate the phone. The scroller may be snapped to an area that wasn't the one in the center of the screen. e.g. re-snapped to (1,1) rather than (1, 2). Repeat steps 2-5 if not see.

**Comment by yi-gu** [comment]
@majido FYI

**Comment by fantasai** [comment]
I suspect in the multiple elements involved case, the spec should leave it up to the UA which one to choose. I doubt we know for sure what heuristic would be best in these cases, excepting cases where the user has focused an element in which case the focused element should be the one that remains snapped.

So my proposal would be something like

> If multiple elements were snapped before the change, which element is re-snapped after the change is up to the UA. However, if any of them have focus, that one must be chosen.

**Comment by fantasai** [comment]
Edits checked in as 

> If multiple boxes were snapped before and their snap positions no longer coincide, then if one of them is focused or targetted, the scroll container must re-snap to that one and otherwise which one to re-snap to is UA-defined. (The UA may, for example, track which element is snapped as layout shifts align and unalign the snap positions of other elements.)

@yi-gu Is this resolution satisfactory?

@tabatkins i can haz review on edits?

**Comment by fantasai** [comment]
r=@tabatkins
