### ISSUE TITLE
[css-color] colorspace of untagged video greater than 1080p

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#4655]
in [Color Spaces of Untagged Colors](https://drafts.csswg.org/css-color-4/#untagged), recommendations are given for video below 720p (i.e. NTSC- and PAL-esolution video), 720p, and 1080p.

There are no recommendations for 4k or 8k video.

They should probably recommend Rec.2020 for SDR 4k video.

**Comment by svgeesus** [comment]
also in that section,  **specified in html** should probably be a link to the HTML LS.

**Comment by Crissov** [comment]
> since untagged video should be presumed to be in ITU.
> 
> - At below 720p, it is Recommendation [ITU-R BT.601] 

Would it make sense to add the color space**s** from Rec. 601 for explicit use in `color()`? 

[ITU-R BT.601]: <https://www.itu.int/rec/R-REC-BT.601/> "Recommendation ITU-R BT.601-7 (03/2011), Studio encoding parameters of digital television for standard 4:3 and wide screen 16:9 aspect ratios"
