### ISSUE TITLE
[css-align] Center alignment can be improved

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4659]
(Separating out from <https://github.com/w3c/csswg-drafts/issues/1432#issuecomment-513028325>.)

Ian believes we can improve on the center-alignment rules.

In particular, he believes that the correct answer is to find the smaller of the start- and end-aligned sizes, then double that, aligning it to the abspos containing block edge that was chosen. This lets it fill out the abspos containing block as much as it can while still remaining centered on one of the "significant edges" of the staticpos containing block.

This is apparently what Edge does. Everyone else does some other "entertainingly wrong" (Ian's words) behavior.

> FYI - I added two tests with this behaviour here: wpt.fyi/results/css/css-position?label=master&label=experimental&aligned&q=position-absolute-center which EdgeHTML did pass (doesn't as written as used inline-size, block-size properties).

**Comment by tabatkins** [comment]
@bfgeek I've forgotten why I found your argument for this compelling when you presented it to me. Can you provide some example of the behavior, and why the other behaviors are bad?

**Comment by tabatkins** [comment]
I wrote down Ian's suggested behavior wrong; his intention is to essentially let it grow in both directions from the center of the staticpos containing block, stopping when it hits one of the edges of the abspos containing block.

The mechanics, then, are find the smaller of the distances from the *center* of the staticpos containing block to the abspos containing block edge, then double that and stick it to the abspos containing block edge that was selected, then center the item in that space.  This makes sense!

**Comment by fantasai** [comment]
OK, we made edits for this (and updated the diagram). See https://drafts.csswg.org/css-align-3/#abspos-sizing Agenda+ to discuss/approve.

**Comment by mrego** [comment]
We're somehow "overflowing" the static containing block, would `overflow-position` values `safe` and `unsafe` have any effect?

I'm also wondering what's the use case, and why we want to grow out of the static containing block when you use `justify-self: center` on an abspos element that uses the static position.

**Comment by bfgeek** [comment]
@mrego By default absolute/fixed positioned object always can grow outside the static containing block (from CSS21).

You can become start/end aligned depending if the absolute/fixed positioned object is within an LTR/RTL context. This normalizes the behaviour for "center" with how this currently works.

**Comment by mrego** [comment]
Got it now, it probably makes sense yeah.
