### ISSUE TITLE
[css-display-3] Can't understanding element and text nodes

### ISSUE THREAD

**Issue by Jiang-Xuan** [w3c/csswg-drafts#4663]
* please link to the spec section you're talking about, or at least the spec

https://www.w3.org/TR/css-display-3/#intro

> CSS takes a source document, organized as a tree of elements and text nodes, and renders it onto a canvas (such as your screen, a piece of paper, or an audio stream). 

Element and text node are defined here, but there is  no detailed explanation of what is  element and text node. Can we give a detailed explanation here.

For example:

```html
<div>
  Some text
  <div>Another some text</div>
</div>
```

Is `Some text` a text node here?

Thanks for all responses. 👋

**Comment by Loirooriol** [comment]
The DOM spec defines [DOM elements](https://dom.spec.whatwg.org/#concept-element) and [DOM text nodes](https://dom.spec.whatwg.org/#interface-text).

The element tree then contains elements (DOM elements + tree-abiding pseudo-elements) and text nodes (DOM text nodes).

So I think this will be clear once the spec defines how the element tree is created (#1810).

> Is `Some text` a text node here?

It's a text node, but note it also includes the surrounding spaces and newlines.

**Comment by Jiang-Xuan** [comment]
@Loirooriol Thanks for your response, very helpful. Hope the Working Group can give that spec as soon as possible.

Appreciation!

**Comment by tabatkins** [comment]
Yes, it's referring to the same concepts as the DOM spec.

**Comment by Jiang-Xuan** [comment]
@tabatkins I think it is possible to indicate the reference here.

**Comment by fantasai** [comment]
We could add DOM as an example, but fundamentally CSS does not require the DOM specifically. It just requires a tree of elements and text nodes, and if you want to use it on a different type of document tree it's fine.
