### ISSUE TITLE
[css-background-3] Normative definition of 'background-repeat: round' was deleted

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#4667]
It appears that https://github.com/w3c/csswg-drafts/commit/99928abc9bcab32c3222919673dd507ea9ca2ebc#diff-45a08deb47626c42f650a06376ebadebL1058-L1065 accidentally removed normative text.

As a result, this part of https://www.w3.org/TR/2017/CR-css-backgrounds-3-20171017/#the-background-size

> If background-repeat is round for one (or both) dimensions, there is a second step. The UA must scale the image in that dimension (or both dimensions) so that it fits a whole number of times in the background positioning area. In the case of the width (height is analogous):
>
> If X ≠ 0 is the width of the image after step one and W is the width of the background positioning area, then the rounded width X' = W / round(W / X) where round() is a function that returns the nearest natural number (integer greater than zero).

… has its latter paragraph removed in https://drafts.csswg.org/css-backgrounds/#background-size

There are other removals that look suspicious in a "fix markup" commit. I haven’t checked other commits.

CC @tabatkins

**Comment by fantasai** [comment]
Thanks for the report @SimonSapin !

**Comment by tabatkins** [comment]
I don't understand why that text is in a `blockquote` to begin with.
