### ISSUE TITLE
[css-values] Add sign() math function

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4673]
Can we add the analogous of the ECMAScript `Math.sign()`? That is
 - `sign(x)` is `1` if `x > +0`
 - `sign(+0)` is `+0`
 - `sign(-0)` is `-0`
 - `sign(x)` is `-1` if `x < -0`
 - `sign(NaN)` is `NaN`

For non-zero values it can be achieved with `x / hypot(x)` or `clamp(-1, x / 0, 1)`, but these are NaN for zero.

I think `sign()` can be very useful given that CSS doesn't have conditionals (#3455).

For example:
```css
width: calc(if (100vw > 100px) then (1em) else (1lh));
```
is not possible, but with `sign()` I could use 
```css
--cond: sign(max((100vw - 100px) / 1px, 0));
width: calc(1em * var(--cond) + 1lh * (1 - var(--cond)));
```

Or #2513 is discussing a `round()` function that rounds to the nearest, or upwards in case of tie. So `round(2.5)` would be 3 and `round(-2.5)` would be -2. But what if in case of tie I want to round towards 0, or away from zero? It's very simple with `sign()`:

```css
round(-hypot(x)) * sign(-x) /* round towards 0 in case of tie */
round(hypot(x)) * sign(x) /* round away from 0 in case of tie */
```

**Comment by AmeliaBR** [comment]
While I have no direct objection to a `sign()` function, I'd much rather address your particular use cases directly, with rounding options and with conditional functions.

**Comment by Loirooriol** [comment]
But conditional functions were rejected in #3455 because they are too powerful. With `sign()` we can have some kind of conditions but it's just arithmetic so it's fine.

And about rounding options, it was just an example, but there are many others. 
For example, in case of tie maybe someone wants to choose the nearest even number, e.g. 6.5 rounds to 6 and 7.5 rounds to 8 (a bit strange but some language does this by default if I recall correctly).

So my point is that native CSS can't offer all possible behavior customizations, because there are so many options. Instead we should let authors achieve what they want with `sign()`, and if some behavior is very popular but not much readable with `sign()`, then add a nicer way in CSS.

The example could be

```css
--is-tie: calc((1 - hypot(sign(2*x - ceil(x) - floor(x)))) * sign(ceil(x) - floor(x)));
calc(round(x/2)*2 * var(--is-tie) + round(x) * (1 - var(--is-tie)));
```

**Comment by tabatkins** [comment]
Added sign() in 8e3fb63a.
