### ISSUE TITLE
[css-align][css-grid] Do grid items that have "no baseline set" participate in baseline alignment?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#4675]
Do grid items that have "no baseline set" participate in baseline alignment?

The css-align spec says about blocks:
"If there is no such line box or child, then the block container has no baseline set."
https://drafts.csswg.org/css-align/#baseline-export

So it's clear that grid items that are empty block containers have "no baseline set".

What is unclear is if we should synthesize a baseline and participate in the baseline alignment, or if such items don't participate in baseline alignment at all and instead use their [fallback alignment](https://drafts.csswg.org/css-align-3/#valdef-justify-self-first-baseline)?

(Filed from discussion in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1609403).)

CC @javifernandez

**Comment by javifernandez** [comment]
I think Chrome is failing in the following tests for this same reason:

- [grid-item-input-type-number.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-align/baseline-rules/grid-item-input-type-number.html)
- [grid-item-input-type-text.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-align/baseline-rules/grid-item-input-type-text.html)

In these cases, the problem is how to determine the baseline of a grid container, which has an orthogonal item. As orthogonal item, it doesn't have a natural baseline. My understanding of the spec is that the grid container should use that item, which should synthesized its baseline, to generate the grid container's baseline.

https://drafts.csswg.org/css-grid/#grid-baselines

> 2- Otherwise, if the grid container has at least one grid item, the grid container’s first (last) baseline set is generated from the alignment baseline of the first (last) grid item in row-major grid order (according to the writing mode of the grid container). If the item has no alignment baseline in the grid’s inline axis, then one is first synthesized from its border edges.

**Comment by javifernandez** [comment]
@MatsPalmgren isn't your comment [here](https://github.com/w3c/csswg-drafts/issues/721#issuecomment-264314099) implying that grid items with no baseline should synthesize it, especially when the user specified explicitly via the alignment properties.

**Comment by javifernandez** [comment]
As a matter of fact, @MatsPalmgren filed a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1321655) precisely to allow orthogonal grid items to participate, with the synthesized baseline, in baseline alignment. 

I guess the question that still stands is whether any item with no baseline must follow that approach. The spec is not clear regarding the need of items with no baseline to synthesize it in any case, it just mentions how to do it in case of needing to do so. 

Unless mats disagree, I think we can all agree that any item with no baseline should participate in baseline alignment, if any of the CSS Box Alignment properties state so, using the synthesized baseline. This is coherent with what we have decided to do for orthogonal items. If we all agree on this, we may want to add some edits in the spec to be more clear about this.

I thought that the following statement of the CSS Box Alignment spec was enough for determining the participation of any grid item, either it has a natural baseline or not: 

https://drafts.csswg.org/css-align/#baseline-align-self
>  A grid item participates in first/last baseline self-alignment in its startmost/endmost row or column if its align-self or justify-self property (respectively) computes to first baseline/last baseline. 

However, Mats seems to disagree and would rather to state clearly that items with no natural baseline also participate.

**Comment by fantasai** [comment]
@MatsPalmgren @javifernandez We made some edits to clarify the spec, can you let us know if they look correct?

**Comment by javifernandez** [comment]
I'm satisfied with the changes.
