### ISSUE TITLE
[css-multicol] Defining what happens with column-fill in unconstrained containers for continuous and fragmented contexts

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#4689]
A previous version of the multicol specification contained the paragraph:

> "In continuous media, this property [column-fill] will only be consulted if the length of columns has been constrained. Otherwise, columns will automatically be balanced."

This was commented out in the spec in [2012](https://github.com/w3c/csswg-drafts/commit/e0a990c7e6514f95f1d0c3d6ccb08f4552365f44).

Chrome and Webkit implemented column-fill as per this line in the spec. Therefore the value of `column-fill` is only consulted if (in horizontal-tb) a `height` has been given.

The initial value for `column-fill` is `balance` so content is balanced across columns. If we use `column-fill: auto` the browser should fill columns sequentially.

See [this CodePen](https://codepen.io/rachelandrew/pen/gZedrZ).

In example 1 we have an unconstrained container and `column-fill: auto`. Chrome is ignoring `column-fill` and continues to do the default of balancing. Firefox is consulting the `column-fill` property and because the container is unconstrained fills the first column with all content.

In example 2 we do have a height on the container and so both browsers do the same thing - filling the columns sequentially.

We resolved in https://github.com/w3c/csswg-drafts/issues/3224#issuecomment-468089503 to return the spec to match the Chrome implementation, and also to add min and max-height as a constraint that would trigger this behavior.

Then in https://github.com/w3c/csswg-drafts/issues/4036 we reverted this change, leaving the behavior undefined.

In #4036 @dbaron suggested changing the text to say:

> "In continuous contexts, **and for the last fragment in fragmented contexts**, this property will only be consulted if the length of columns has been constrained in the block dimension"

and also [provided a table](https://github.com/w3c/csswg-drafts/issues/4036#issuecomment-503648397) of what the different values would mean. The Yes/No column is whether we balance (yes) or not (no) and the asterisk the values that would change.

So we need to decide what happens when a multicol container is not constrained and `column-fill` is `auto`. Do we return to the previous spec behavior (like Chrome and Webkit) or do what Firefox does and always honor `auto`?

If we do return to the previous behavior, do we make the addition that @dbaron suggested and in fragmented contexts *also* consult the property when we are in the last fragment?

**Comment by rachelandrew** [comment]
@mstensho in https://github.com/w3c/csswg-drafts/issues/4036#issuecomment-508378790 you said:

> "You're asking if I'm okay with #3224 being reverted and willing to implement it in Blink?
Sure, but then we won't have to clarify what column-fill:auto + height:auto means, do we? The spec, prior to #3224 said that column-fill:auto means that we should never balance (except before spanners), didn't it?"

We have resolved that the spec will match Firefox's behavior. Could you raise issues if there is anything you think needs extra definition? I'll also be raising the browser bugs for this. If you don't think there is anything else, then that would be helpful too as it's the final piece before going to CR.

**Comment by mstensho** [comment]
Per my testing, Firefox doesn't balance content before spanners if column-fill is auto (and height isn't sufficiently constrained, if at all), effectively putting everything into one column (unless there are forced breaks). Isn't this a bit weird / useless?

**Comment by frivoal** [comment]
I think we should always balance before spanners. As far as I can tell that's what the spec says to do:

> the columns before the spanning element are balanced and shortened to fit their content.

**Comment by rachelandrew** [comment]
Yes the column-fill stuff we were debating didn't mention anything about the situation when there is a spanner I don't think. So the Firefox behavior (of putting everything into one column if height isn't constrained) is what we agreed on, however do we need to clarify whether that does or does not happen before a spanner. Does the specced spanner behavior trump the column-fill instruction?

**Comment by frivoal** [comment]
> Does the specced spanner behavior trump the column-fill instruction?

I believe it should. I don't know of any use case for a spanner without balancing the part of the fragment above it.
