### ISSUE TITLE
[css-selectors] Improve the usefulness of specificity of Tags & IDs

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#4690]
In an effort to modernize the CSS Cascade, and make it more suitable for projects with multiple Authors writing code over many years, @mirisuzanne is thinking about [Origins (and how we might extend their power)](https://github.com/w3c/csswg-drafts/issues/4470), and about the Specificity of Selectors. 

For context:
The [Selectors Level 4](https://www.w3.org/TR/selectors/#specificity-rules) defines three levels of sectors / three levels of specificity:
> A selector’s specificity is calculated for a given element as follows:
> count the number of ID selectors in the selector (= A)
> count the number of class selectors, attributes selectors, and pseudo-classes in the selector (= B)
> count the number of type selectors and pseudo-elements in the selector (= C)
> ignore the universal selector

Miriam wrote [on Twitter](https://twitter.com/MiriSuzanne/status/1219289524880044032):

> Specificity only has three layers, & only the middle (classes/attributes) layer is flexible enough for most use cases. IDs can only be used once per page, & tags need to be reused semantically. They're useful but very limited.
> 
> When everything is in a single layer, minute changes can have major impact. Everything relies on careful counting of selectors, and careful management of source order. Specificity should be more robust.
> 
> We need ways to create custom tag-layer – & reusable id-layer – selectors.

Let's talk about this. What would it look like to extend selectors so that:
• IDs can be used more than once per page
• The 'tag layer' has more customizability
• And / or other ways to empower Authors to use all three layers of specificity, instead of flattening their work into one layer.

**Comment by emilio** [comment]
>  • IDs can be used more than once per page

This is already the case, isn't it?

**Comment by mirisuzanne** [comment]
According to the [HTML living standard](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute), IDs must be unique on a page:

> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character.

I think there are very good reasons for that – IDs are used to select a single element on the page in various form/ARIA related uses – so I'm not sure that making IDs more flexible is an option here. and it does make sense to me that a unigue-ID direct selection would live at the highest level of specificity. The same is true for tag names living at the lowest level. The two use-cases that would be particularly helpful in development are:

1. The ability to create more flexible/targeted "defaults" that are easy to override. That could happen in a number of ways, including the proposed `!default` flag (#2272), custom origins (#4470), a new layer of specificity, or flexible (class-like) additions to the tag layer.
2. The ability to consider some repeatable "components" more specific than other repeatable "patterns" – like an "article-summary" card is more specific than the "card" pattern it uses, even though both repeat on a page.

While point 2 can be handled with multiple classes, it feels like we're missing out on the power that specificity layering would provide to ensure that specific components always override more general patterns, which always override broad defaults. 

I don't think we need a lot of layers – 3-5 seems about right – but our current 3 don't provide the flexibility required for the common use-cases.

**Comment by SebastianZ** [comment]
> According to the [HTML living standard](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute), IDs must be unique on a page:
> 
> > When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree and must contain at least one character.

Right, but what Emilio referred to was that the [Selectors spec. also handles the case of invalid HTML documents defining multiple IDs](https://drafts.csswg.org/selectors-4/#id-selectors):

> An ID selector represents an element instance that has an identifier that matches the identifier in the ID selector. (It is possible in non-conforming documents for multiple elements to match a single ID selector.)

Sebastian

**Comment by mirisuzanne** [comment]
Sure. I guess I'd question if that's really something to encourage? Unique IDs seem important for various semantics/accessibility issues, and I'd want to be careful about pushing a solution that might cause more accessibility issues.

**Comment by SebastianZ** [comment]
Of course it's rather something that should be discouraged. As you say, IDs should be unique. I just mentioned that in regard of Jen's point of IDs being used more than once on a page and Emilio's response to it.

Sebastian

**Comment by mirisuzanne** [comment]
@jensimmons Is this something we still want to look into more? I think we've basically covered the use-cases here with a combination of `@layer` (as a higher-level structural fix), and `:where()`/`:is()` allowing more detailed specificity manipulation. Should we close the issue?

**Comment by jensimmons** [comment]
If you think it's covered, then it sounds good to me.

**Comment by Loirooriol** [comment]
@ThomasGutmann That's what https://drafts.csswg.org/css-cascade-6/#scope-combinator is trying to introduce.

But you can already have something like that with custom properties:

```css
#my-module { --color: blue }
#my-module ul.foos li { color: var(--color); }
#my-foo { --color: red; }   
```

**Comment by ThomasGutmann** [comment]
Thanks, @Loirooriol, for your answer.

My point is that the CSS “specificity” is not really inutitiv, and it rewards over-determined selectors and leads to HTML code wich is cluttered with classes and IDs. [My website](https://ThomasGutmann.de) has easy HTML and almost non design and still I stumbled over the problem where I couldn’t style a specific element because of other selectors.
Your example presuppose that I know about the one #my-foo when writing the general selectors, but an easy KISS (“Keep it simple, stupid!”) approach with the CSS basics should lead to the target, too.
The new introduced mechanics seem like workarounds to me.
Kind Regards,
Thomas

**Comment by mirisuzanne** [comment]
@ThomasGutmann everything we do here has to be backwards-compatible. We can introduce new features that are unknown in older browsers, but we can't change the behavior of existing CSS syntax. So to that extent, everything we do has to _work around_ what already exists.

There would be ways to work around compatibility problems, by introducing new selector syntax – but I would expect that to have the same issues we're facing with `>>` and `~~` (which try to address the same problem in a different way). See #8380 

(More generally, I would recommend opening new issues for a proposal like this, and linking to prior discussions where they are relevant)
