### ISSUE TITLE
[css-values-4] Casing of 'infinity' and 'nan' keywords

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4698]
We just resolved to add "infinity", "-infinity", and "NaN" keywords to calc(), to aid in serializing infinite/NaN values.

It's obvious that, like in the rest of CSS, these are recognized ASCII case-insensitively; "InFiNiTy" is perfectly valid and produces an infinity value. But what casing should we serialize these values with?

I think it's reasonable to mandate that "NaN" is serialized with that exact casing. It's a weird term, and it's *always* spelled that exact way; I've never seen it written as "nan", which is what you'd get from the default keyword-serialization rules.

I'm less sure we should do anything for the infinities. Javascript happens to spell them with an initial cap, as `Infinity` and `-Infinity`, but this isn't remotely a universal practice. I think we can get away with these serializing per the normal rules, as "infinity" and "-infinity".

I've currently written the spec to reflect these two; if nobody objects we can just leave it as I wrote it.

**Comment by Crissov** [comment]
… or use `not-a-number` or `non-number`, or multiple more explicit values like `division-by-zero`.

**Comment by tabatkins** [comment]
Insofar as people care about such values at all, sticking close to the existing universal terminology is probably ideal.

Anyway, no objections in three weeks, I'll go ahead and close. People can feel free to object again when they start implementing. ^_^
