### ISSUE TITLE
[css-color-4] Lch limits on hue value are a bit too limiting

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#4703]
The hue value in Lch is wrapped to the range 0..360° at parse time:

>  If the provided value is negative, or is greater than or equal to 360deg, it is set to the value modulo 360.

...which seems like a very sensible thing to do, until you try to make a gradient between two colors on either side of 0°.

For example, if I tried to make an Lch gradient from purple (eg hue 335°) through red (hue 0°) to orange (eg hue 60°), I have to split this into two segments - from 335° to 359.999°, and from 0° to 60°. Were it not wrapped, I would be able to transition from hue -25° to 60°.

Hue in HSL is not limited at all, which I think is the best option: a gradient from 0° to 180° is different to one from 0° to 900°, despite the start and end colors being identical. If it is to be limited, it should be at least over a range of 720°

Was previously discussed in https://github.com/w3c/csswg-drafts/issues/289

**Comment by tabatkins** [comment]
Yes, this should definitely use the same language as hsl(), defining an equivalence class over hue angles rather than changing the angle in any way.

**Comment by jrus** [comment]
This should map angles from 0 to 360 (or if you like, –180 to 180), but gradients should always take the shortest arc.

**Comment by Crissov** [comment]
If youʼd specified the gradient from −20° through 30°, Iʼd agree, but with 340° thatʼs an assumption that is not clearly better than the other way around.

**Comment by jrus** [comment]
It should be common for an author to get their coordinates (including hue angle) from some graphical tool, and exceedingly rare for someone to want a single gradient segment that goes the long way around the hue circle (even less so for the 3x around the hue circle proposed above).

If someone really wants to go the long way around, it’s an easy workaround to add additional gradient stops. But not defaulting to the short arc around the circle is going to lead to a lot of confusion.

**Comment by faceless2** [comment]
What about a gradient from 0 to 180? Or 180° to 0°? If you clamp angles to _any_ range, at some point you are going to run into this situation and will need to make an arbitrary decision on which way to iterate.

Same for the situation where you want to create a continuous color range from 0..360°, which is not an unusual thing to want. Yes, you can split it into two segments, but why should you have to?

If you don't clamp the values, you don't have to do either of these. Given there's also no technical reason this has to be done, and that it's not currently done for HSL which is already being used in the wild, I'm not sure I see the benefit in taking a different approach for Lch.

**Comment by jrus** [comment]
> What about a gradient from 0 to 180? Or 180° to 0°?

Pick either way, doesn’t really matter. People should not generally be making a single gradient segment close to this wide, except for a toy tech demo.

> continuous color range from 0..360°, which is not an unusual thing to want

It is not a common thing to want in any practical use on a website or infographic or map ...

It might be desirable in someone’s toy tech demo?

But trying to do this in terms of CIELAB LCh coordinates is generally going to lead to poor results, because the gamut is not big enough to accommodate all hues to the same chroma, so what you’ll end up with is a bunch of artifacts where the gamut clipping boundaries were found.

To get decent looking results you’ll want to pick the chroma of intermediate waypoints to avoid clipping.

> HSL

HSL (a) leads to horrible results in basically all contexts, so is a poor inspiration for anything, because (b) it is one of the simplest possible ways of squishing a cube to fit inside a cylinder, without any reference to human perception, only geometric convenience. The result of that is that the cylinder is the gamut, so if you interpolate between any two points in cylindrical coordinates you will remain in the gamut.

> If you don't clamp the values, you don't have to do either of these.

Yes, but what you will get is extreme confusion and lots of poor results.

**Comment by tabatkins** [comment]
Gradients currently don't care about the color angle at all; they convert the color into RGB and then linearly interpolate the RGB components.

When we do allow specifying interpolation in gradients, I expect it'll match how gradients are already defined to interpolate their angles - it interpolates the angles numerically exactly as you specify, so 10deg to 350deg goes the long way around the circle.

**Comment by tabatkins** [comment]
Gradients have angles for other reasons than colors. ^_^ `linear-gradient(50deg, red, white)`, for example, which angles the linear gradient to 50deg CW from vertical.

Nobody implements the fancier gradient interpolation yet (they just do a cross-fade between the two endpoints), but when they *do*, it'll work as I described/linked.

**Comment by svgeesus** [comment]
> Yes, this should definitely use the same language as hsl(), defining an equivalence class over hue angles rather than changing the angle in any way.

On my to-do list

**Comment by jrus** [comment]
> Gradients have angles for other reasons than colors. ^_^ `linear-gradient(50deg, red, white)`, for example, which angles the linear gradient to 50deg CW from vertical.

But this is a single angle, not a way of interpolating between angles ...

**Comment by svgeesus** [comment]
> This is a bit off topic here, but I wouldn’t know where to raise it

It will get lost here. Raised for you https://github.com/w3c/csswg-drafts/issues/4754

**Comment by triple-underscore** [comment]
Along with the commit https://github.com/w3c/csswg-drafts/commit/ef3269f022324d4cb0203085e9d934716cfa0f38,
still needs an edit for css-color-4 § Changes, that the following sentence should  be removed:
> Clarify hue in LCH is modulo 360deg

**Comment by svgeesus** [comment]
Oh, good catch.

**Comment by svgeesus** [comment]
Changing to 

> Clarify hue in LCH is modulo 360deg (change now reverted)

because a draft was published with that change.
