### ISSUE TITLE
[css-pseudo-4] Clarify when selections are inactive

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4719]
The spec gives an example of when selections are inactive, but maybe we can provide more details on what defines a selection being inactive? I think it's when it can't be copy/pasted because those events are going to some other target, but honestly I'm not sure what the definition is.

**Comment by TalbotG** [comment]
Eg an text `<input>` that has selected content and then loses focus:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/inactive-selection-031.html

**Comment by fantasai** [comment]
We decided to remove ::inactive-selection, so this question isn't relevant anymore...
