### ISSUE TITLE
[css-values] round(strategy, A, ±∞)

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4725]
https://drafts.csswg.org/css-values-4/#round-infinities says

> In `round(A, B)` [...] If A is finite and B is infinite, the result is 0⁺ if A is 0⁺ or positive finite, and 0⁻ if A is 0⁻ or negative finite.

First, I assume `round(A, B)` actually means `round(strategy, A, B)`. Otherwise the spec should define what to do for non-`nearest` strategies.

But then, consider `round(up, 1, ±∞) = +0`. IMO it doesn't make much sense that if we round 1 upwards, we get a smaller value! Analogous for `round(down, −1, ±∞) = −0`.

Also, returning 0 for an infinite precision seems to imply that 0 is a multiple of infinity. But `0 * ∞ = NaN`, not `0`. This makes me a bit uneasy, though I guess it's fine if you consider limits.

So I think there are 2 reasonable approaches:

 - Say that `round(strategy, A, ±∞)` is always NaN.
 - For `A` finite, say that `round(strategy, A, ±∞) = lim_{x→∞} round(strategy, A, x)`, i.e.
    - `round(up, A, ±∞)` is `+∞` if `A > 0`, `−0` if `A < 0`, or `A` otherwise.
    - `round(down, A, ±∞)` is `−∞` if `A < 0`, `+0` if `A > 0`, or `A` otherwise.
    - `round(to-zero, A, ±∞)` is `−0` if `A < 0`, `+0` if `A > 0`, or `A` otherwise.
    - `round(nearest, A, ±∞)` is `−0` if `A < 0`, `+0` if `A > 0`, or `A` otherwise.

    That is,

    - If `A < 0`, the result is `−∞` for `down`, or `−0` for other strategies.
    - If `A > 0`, the result is `+∞` for `up`, or `+0` for other strategies.
    - If `A = ±0`, the result is `A`.

**Comment by tabatkins** [comment]
Yup, my brain was assuming nearest there. `round(up 1, ∞)` should definitely return ∞.

> Also, returning 0 for an infinite precision seems to imply that 0 is a multiple of infinity. But 0 * ∞ = NaN, not 0. This makes me a bit uneasy, though I guess it's fine if you consider limits.

Yes, you usually have to consider the limit behavior for infinities; `round(1, very-large-finite-number)` definitely rounds to zero, so infinity should act the same.

On the other hand...

> Say that round(strategy, A, ±∞) is always NaN.

This works for me too. I don't think this is an important case to care about.

**Comment by tabatkins** [comment]
Argh, never mind, my aesthetic sense is telling me I'm not allowed to say it's NaN when there are clear limit values. >_<

**Comment by Loirooriol** [comment]
@tabatkins So I guess `round(strategy, ±∞, ±∞)` should also depend on `strategy`?

 - `round(up, +∞, ±∞) = ∞`
 - `round(up, −∞, ±∞) = NaN` since the limit in not unique, e.g.
   ```
   lim_{x→−∞} round(up, x, 2x) = −0
   lim_{x→−∞} round(up, x, x) = −∞
   ```
 - `round(down, −∞, ±∞) = −∞`
 - `round(down, +∞, ±∞) = NaN` since the limit in not unique, e.g.
   ```
   lim_{x→+∞} round(down, x, 2x) = +0
   lim_{x→+∞} round(down, x, x) = +∞
   ```
 - `round(to-zero, ±∞, ±∞) = NaN` since the limit in not unique, e.g.
   ```
   lim_{x→±∞} round(to-zero, x, 2x) = ±0
   lim_{x→±∞} round(to-zero, x, x) = ±∞
   ```
 - `round(nearest, ±∞, ±∞) = NaN` since the limit in not unique, e.g.
   ```
   lim_{x→±∞} round(nearest, x, 3x) = ±0
   lim_{x→±∞} round(nearest, x, x) = ±∞
   ```

**Comment by tabatkins** [comment]
Given that several of the possibilities are NaN, I'm comfortable with making that situation NaN in all strategies.
