### ISSUE TITLE
[resize‑observer] Why does `ResizeObserver` default to `"content‑box"`?

### ISSUE THREAD

**Issue by ExE-Boss** [w3c/csswg-drafts#4739]
It’s&nbsp;been agreed&nbsp;upon [that&nbsp;defaulting to&nbsp;`"content‑box"` is&nbsp;a&nbsp;legacy&nbsp;mistake](https://wiki.csswg.org/ideas/mistakes), so&nbsp;what’s&nbsp;the&nbsp;rationale behind&nbsp;having a&nbsp;new&nbsp;API default&nbsp;to&nbsp;`"content‑box"`?

**Comment by dlibby-** [comment]
At this point we can probably chalk this up to another legacy mistake - the default was chosen for compatibility with the legacy ResizeObserverEntry's contentRect property, which originally was the only observable box/size/rect.

Basically callers that don't pass a box may be relying on observing the content-box and we need to preserve this behavior.
