### ISSUE TITLE
[css-values-4] Simplification algorithm should account for products of min / max.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4744]
https://drafts.csswg.org/css-values-4/#simplify-a-calculation-tree

Step 8 wouldn't simplify something like `a * min(b, c)` into `min(a * b, a * c)` (or the equivalent `max` if `a` is negative), and it probably should.

**Comment by emilio** [comment]
That is an ok answer for me for me I guess. I think 

In a world where the only other functions are `min` / `max` / `clamp`, you can redistribute product and then forget about multiplication pretty much right after parsing.

But I guess since we added a bunch of new functions where the product doesn't distribute so easily, or at all, then probably not worth it.

**Comment by tabatkins** [comment]
Sounds good. :+1:
