### ISSUE TITLE
[css-tables] border-radius in collapsed mode

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#475]
Compat Issues: No

**Description:**
The behavior currently specified in CSS 2.1 is not implemented by anyone. 

The simplest path to interop is to forbid the behavior completely.

**Proposed Option:**
Border-radius should be entirely ignored in collapsed-mode, on both table-root and table-cells.

**CSS 2.1 Option:** 
Border-radius should apply on the table-root, but its extent cannot be bigger than the cell forming the corner

**Testcases:**
https://jsfiddle.net/wazhrfe3/2/

**Browsers Passing Test:**
Chrome | Firefox | Opera | Safari

**Comment by FremyCompany** [comment]
The CSSWG resolved this issue during TPAC2016. 

Border-radius should have no effect on tables in collapsed mode.
