### ISSUE TITLE
[css-values] should clamp get simplified to min or max when possible?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4757]
That is, should `clamp(10em, 11em, 1000px)` be simplified to `min(11em, 1000px)` or such?

**Comment by Loirooriol** [comment]
This seems worse than #4756. I think that magically changing the function would be confusing.
Would you special case `clamp`, or also `max(10em, min(11em, 1000px))`?

**Comment by emilio** [comment]
Probably not, fair enough. Clamp seemed like an easy one because you know it has three arguments, unlike min / max which can have arbitrarily many.

Anyhow I'm just filing issues as I write code for stuff that I have decided _not_ to do, btw. ;)

This simplification doesn't seem too complicated, but agreed it could be somewhat confusing.

**Comment by tabatkins** [comment]
I would strongly prefer *not* to do this. ^_^
