### ISSUE TITLE
Consideration of keyup event for Polyfill instead of keydown

### ISSUE THREAD

**Issue by joe-watkins** [w3c/csswg-drafts#4758]
> In the polyfill, keydown event and mouseup event are used for the spatial navigation.

I'm curious to see if there is a great case for leveraging a `keydown` event as apposed to a `keyup` event. Keyboard users who may have mobility/dexterity type disabilities could benefit from an event that they have more control over the timing of it being fired. e.g. someone with tremors using a keyboard.

WCAG 2.1 A 2.5.2 Pointer Cancellation currently speaks to this concept for touch/mouse. (should clearly extend to keyboard events IMO)
https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/#252-pointer-cancellation-a

Browser manufacturers may be looking to the polyfill for guidance and I was interested in seeing if maybe a `keyup` event could be the default vs requiring an override. 

https://wicg.github.io/spatial-navigation/#handling-browser-events

**Comment by jihyerish** [comment]
Thanks for raising this issue!

However, this issue is about the spatial navigation polyfill, not the spec.
Issues about the polyfill have been discussed in https://github.com/WICG/spatial-navigation,
so I've migrated this issue to https://github.com/WICG/spatial-navigation/issues/214.
