### ISSUE TITLE
[css-sizing-3] Bug in max-content definition?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/csswg-drafts#4764]
@zurc reported this [bug in the wrong repo](https://github.com/w3c/wot-binding-templates/issues/90)
> https://drafts.csswg.org/css-sizing-3/#valdef-width-max-content reads  'Use the min-content size in the relevant axis...'
>  should it be 'Use the max-content size...' instead?

**Comment by fantasai** [comment]
Fixed, thanks!!
