### ISSUE TITLE
[css-tables] min-height on a table-row

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#477]
**Compat Issues:** Yes

**Description:**
When a min-height is specified on a table-row (tr):
- Blink and Gecko ignore the minimum height.
- Edge applies it (like min-width)

**Proposed Option:**
Ignoring min-height on table-rows

**CSS 2.1 Option:** 
Height distribution is undefined

Testcases:
https://jsfiddle.net/wj5tjvcy/

**Comment by FremyCompany** [comment]
Accepted it but mark it as risk
