### ISSUE TITLE
[css-text-3] Adjust definition of word-break to handle letters with not-yet-existing UAX14 classifications

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4781]
There's some discussion around fixing Javanese line breaking by introducing new UAX14 categories... which brings me to the realization that we should make sure our specs are drafted in a way that will accommodate such future updates to UAX14.

**Comment by fantasai** [comment]
@frivoal Mind reviewing?

**Comment by frivoal** [comment]
Looks good. We'll need to write tests whenever UAX14 does this kind of update, as otherwise this spec text is very subtle and easy to miss, but it seems correct to me, so we will be able to add tests based on the spec whenever that kind of UAX14 update does happen.

**Comment by fantasai** [comment]
The tests we should add are to ensure `word-break` affects: Letters from every UAX14 in which there are letters, and also including those in Javanese (which might end up re-coded under UAX14 in the next version), as well as Symbols under the categories listed as affected in css-text-3.
