### ISSUE TITLE
Invalid WebIDL for ResizeObserverEntry

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#4782]
The Web IDL definitions of the `borderBoxSize`, `contentBoxSize`, and `devicePixelContentBoxSize` attributes of the `ResizeObserverEntry` interface are not valid per the Web IDL spec because "[Sequences must not be used as the type of an attribute](https://heycam.github.io/webidl/#idl-sequence)".

The Web IDL spec recommends using a getter operation instead.

**Comment by stephenmcgruer** [comment]
Dupe of https://github.com/w3c/csswg-drafts/issues/4683 ?

**Comment by tidoust** [comment]
Indeed, I missed that one!
