### ISSUE TITLE
[css-color] Include code for converting gray colors to sRGB colors

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#479]
https://drafts.csswg.org/css-color/#gray-to-rgb

This section should include the actual transformation as pseudo-code or an implementation in JavaScript.

It's nice that it says the computation is easy, and lists the steps, but it should just include code. This will make life easy for implementers, as well as someone writing tests.

**Comment by svgeesus** [comment]
The steps relate to the functions in
https://drafts.csswg.org/css-color/#color-conversion-code
but yes, I can easily add a function that expands gray(L) to Lab(L,0,0) and then does Lab to sRGB.

**Comment by grorg** [comment]
Ah, I didn't see them. Thanks, that's fine.
