### ISSUE TITLE
[css-fonts] Reconsider the definition of "first available font"

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#4796]
The spec currently [says](https://drafts.csswg.org/css-fonts/#first-available-font):

> The **first available font**, used for example in the definition of font-relative lengths such as 'ex' or in the definition of the 'line-height' property is defined to be the first available font that would match the U+0020 (space) character given font families in the 'font-family' list (or a user agent’s default font if none are available).

I recently landed a patch to make Gecko conform more closely to this behavior, but backed it out because it caused significant regressions. On looking into things, I think the behavior specified here is not in fact desirable or helpful, and should be altered.

The problem arises because of the text "that would match the U+0020 (space) character". This, by any logical reading I can think of, means that a font that does not support U+0020 is not eligible to be considered the *first available font*, and therefore the next in the list (or the browser's default) must be used as the basis for 'ex' or line-height computations.

This leads to poor behavior when a site does something like

    .foo {
        font-family: "my-icons", "Blank";
    }
    @font-face {
        font-family: "my-icons";
        src: url("my-icons.woff2") format("woff2");
    }
    @font-face {
        font-family: "Blank";
        src: url("data:font/opentype;base64,T1RUTwAKAIAAA ....");
    }

(this is simplified from CSS on tumblr.com), where "my-icons" is an icon font that supports *only* a set of PUA codepoints; it does not have any regular ASCII characters, not even `<space>`; and "Blank" is the [Adobe Blank](https://github.com/adobe-fonts/adobe-blank) font in base64 format. It's presumably used here to avoid the PUA codepoints for the icons getting rendered as hexboxes/last-resort glyphs/tofu/whatever while waiting for the real icon font to load.

However, when the browser needs to refer to the ascent and descent of the *first available font* during computation of [leading and half-leading](https://drafts.csswg.org/css2/visudet.html#leading), or to resolve a [font-relative unit](https://drafts.csswg.org/css-values-4/#font-relative-lengths) such as 'ex', it should -- if it accurately implements this part of the spec -- ignore the "my-icons" font, because that font does not "match the U+0020 (space) character", and therefore it must look at "Blank" to get the metrics to use.

This is unfortunate in this example because "Blank" has a 'cmap' table that maps all one million-plus possible Unicode codepoints to its 2K empty glyphs, and although the font data is not especially huge, it may take a long time to load this font.

It would be similarly unfortunate if the second font were a large webfont resource that would end up getting downloaded only to provide the size of the 'ex' unit (for example), or the normal line height of an empty element. But that seems to be what the spec text requires.

My testing indicates that browsers currently *do* use metrics from the "my-icons" font in an example like this, contrary to the spec. If the `@font-face` rule is given a `unicode-range` descriptor that excludes U+0020, then they do *not* treat it as the *first available font*, which corresponds with the cases discussed in #1765.

I think the problem is that in addressing the earlier issue, the spec text defining *first available font* was written in such a way that it appears to care about *actual character support* in the font, whereas what was really of interest was *potential character coverage as specified by `unicode-range`*.

My suggestion, therefore, is to modify the definition quoted above to something like:

> The **first available font**, used for example in the definition of font-relative lengths such as 'ex' or in the definition of the 'line-height' property is defined to be the first available font that is not excluded by a `unicode-range` descriptor from matching the U+0020 space character, given font families in the 'font-family' list (or a user agent’s default font if none are available).

A webfont without an explicit `unicode-range` descriptor, or a locally-installed font used directly via `font-family: <name>`, will always be eligible to be the *first available font*, regardless of whether it supports U+0020 or not. Only webfonts that *explicitly* (using `unicode-range`) declare their non-support for U+0020 will be excluded.

**Comment by svgeesus** [comment]
Related: https://github.com/w3c/csswg-drafts/issues/1800 https://github.com/w3c/csswg-drafts/issues/1804 and

> [WebKit doesn’t do this; it just uses the primary font, and if the primary font doesn’t support “0” then it uses that font’s .notdef glyph. No downloads necessary](https://github.com/w3c/csswg-drafts/issues/3135#issue-362776570).

and

> [So my preference would be an ordered list of things to try:

 *   the width of the "0" glyph. if it doesn't have one,
 *   the width of the .notdef glyph. if it doesn't have one (and thus, the font is broken),
 *  use 0.5em](https://github.com/w3c/csswg-drafts/issues/3135#issuecomment-424837225)

**Comment by svgeesus** [comment]
I am supportive of the specific text proposed by @jfkthame but would like to hear from other implementers

**Comment by kojiishi** [comment]
Blink's logic is in [FontFallbackList::DeterminePrimarySimpleFontData](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/font_fallback_list.cc?type=cs&sq=package:chromium&g=0&l=129):
```c++
    if (font_data->IsSegmented() &&
        !ToSegmentedFontData(font_data)->ContainsCharacter(kSpaceCharacter))
      continue;
```
and as far as I can read from our code, [SegmentedFontData::ContainsCharacter](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/segmented_font_data.cc?type=cs&sq=package:chromium&g=0&l=43) does not seem to check `cmap`.

@jfkthame, do you have a simple test case I can double check? /cc @drott

**Comment by jfkthame** [comment]
@kojiishi See http://wpt.live/css/css-values/ex-unit-004.html. This was designed to test the behavior as currently written in the spec: it uses the `ex` unit on an element where the first font listed in `font-family` is a font that does not include a `space` character and therefore (per current spec) should *not* be used as "first available font". All browsers currently fail this test -- they *do* use the test font as the basis for `ex`.

Adding a `unicode-range: U+78;` descriptor to the `@font-face` rule that loads the `ExTestNoSpace` font in that test makes it pass in both Firefox and Chrome, as they then *do* ignore that font for "first available font" purposes; this is the behavior I'm suggesting the spec *should* require.

**Comment by kojiishi** [comment]
> See http://wpt.live/css/css-values/ex-unit-004.html

Thank you, confirmed the code above does not check `cmap`, only checks `unicode-range`.

**Comment by faceless2** [comment]
@jfkthame's proposal works for us, for what that's worth.

For reference I want to flag up [issue](https://github.com/web-platform-tests/wpt/issues/17170) with the related test http://wpt.live/css/css-values/ch-unit-017.html which is - as currently specified - incorrect, because the font being used for font metrics _doesn't_ include the space character. This change proposed in this issue would make that test work as described.

**Comment by svgeesus** [comment]
The resolution as listed makes little sense and the large number of s/foo/bar in the IRC (which don't get applied, when content goes to the issue) makes it even harder to figure out.

**Comment by svgeesus** [comment]
I'm guessing that

`RESOLVED: The first available font is the first font in the font-family list whose unicode-range includes the space character`

is meant?

**Comment by litherum** [comment]
Yes.

**Comment by svgeesus** [comment]
And it does not matter whether the font actually has a glyph for that character?

**Comment by kojiishi** [comment]
> And it does not matter whether the font actually has a glyph for that character.

Yes. As @dbaron mentioned, the text @jfkthame proposed is what the resolution is meant.

**Comment by svgeesus** [comment]
http://wpt.live/css/css-values/ex-unit-004.html this test needs to be altered so the previous fail condition is now the pass condition

**Comment by nigelmegitt** [comment]
Just been drawn to this via https://github.com/w3c/ttml2/pull/1242#discussion_r683631831 and I have a question. Given the updated text defines "[first available font](https://www.w3.org/TR/css-fonts-4/#first-available-font)" in terms of the [unicode-range](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range) property, which itself is a descriptor that is defined for [`@font-face`](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range), what is the intent relating to fonts that are available, installed, and referenced by `font-family` _without_ an `@font-face` rule?

Since such fonts do not have an applicable `unicode-range` property, they can never be the "first available font", even if they do support the 0x0020 code point. Is there an assumption that the character map for each font in the `font-family` list will be queried (of course, after applying any `@font-face` rules)? If so, it seems like we should use some other term than `unicode-range`. For example could we change:

> the first font whose [unicode-range](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range) includes the U+0020 (space) character

to

> the first font whose [character map](https://www.w3.org/TR/css-fonts-4/#descdef-character-map) includes the U+0020 (space) character

?

**Comment by jfkthame** [comment]
I suppose my unspoken assumption has been that installed fonts referenced directly by family name implicitly have a Unicode range of U+0000 - U+10FFFF, i.e. just like a `@font-face` resource with no *explicit* `unicode-range`, they can be used for any character supported by their character map.

I think the reason "first available font" is defined in terms of unicode-range rather than character map is that unicode-range is available to the browser without having to download the resource.

**Comment by nigelmegitt** [comment]
Thanks @jfkthame, good to know we agree on the intent. My concern is more definitional: fonts simply do not have a `unicode-range` as defined; only `@font-face` rules have that descriptor. I agree that the UA has access to the set of unicode points that each available font claims to support, but that's a _different thing_ to `unicode-range`, as things are defined today, is it not?

**Comment by jfkthame** [comment]
Agreed; by a literal reading of the definition it seems there's no way for a directly-referenced font to satisfy it, which I'm sure was never the intended outcome.

The spec is also clear ([see the **Note**](https://www.w3.org/TR/css-fonts-4/#first-available-font)) that being considered the "first available font" is *not* dependent on actually having a glyph for the space character. So the font's *character map* (or its *effective character map*, in the case of a `@font-face` resource) is *not* taken into consideration. Only the `unicode-range` descriptor can disqualify a potential candidate.

My conclusion is that any font mentioned directly in the `font-family` list is a valid candidate for "first available font", without regard to its actual character repertoire, much like a `@font-face` resource with no `unicode-range` (because the initial value of the descriptor is the complete range of Unicode).

So you're right, the text of the spec should be clarified; but I don't think it should be changed to refer to character map.

**Comment by svgeesus** [comment]
We [used to have the concept of a font database](https://www.w3.org/TR/2008/REC-CSS2-20080411/fonts.html#q1), and `@font-face` _adding to_ that database. IIRC this was kind of like a hidden set of `@font-face` with `local` src, describing all the local fonts.

The implication of that model would be that the descriptors would have their initial values, so the `unicode-range` would be the initial "all of Unicode" range.

I wonder if we could usefully resurrect that concept?

Alternatively we could just use a negative:

> The first available font, used for example in the definition of [font-relative lengths](https://drafts.csswg.org/css-values-4/#font-relative-length) such as [ex](https://drafts.csswg.org/css-values-4/#ex) or in the definition of the [line-height](https://drafts.csswg.org/css2/#propdef-line-height) property, is defined to be the first font whose glyph for the U+0020 (space) character is not excluded by [unicode-range](https://drafts.csswg.org/css-fonts/#descdef-font-face-unicode-range), given the font families in the [font-family](https://drafts.csswg.org/css-fonts/#propdef-font-family) list (or a user agent’s default font, if none are available).

**Comment by jfkthame** [comment]
> The first available font, used for example in the definition of [font-relative lengths](https://drafts.csswg.org/css-values-4/#font-relative-length) such as [ex](https://drafts.csswg.org/css-values-4/#ex) or in the definition of the [line-height](https://drafts.csswg.org/css2/#propdef-line-height) property, is defined to be the first font whose glyph for the U+0020 (space) character is not excluded by [unicode-range](https://drafts.csswg.org/css-fonts/#descdef-font-face-unicode-range), given the font families in the [font-family](https://drafts.csswg.org/css-fonts/#propdef-font-family) list (or a user agent’s default font, if none are available).

The phrasing "whose glyph for the U+0020 (space) character" could be thought to imply that the font necessarily must *have* such a glyph.

Maybe something more like "the first font for which the character U+0020 (space) is not excluded by a [unicode-range](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range) descriptor"?

Alternatively, we could keep the current text "the first font whose [unicode-range](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range) includes the U+0020 (space) character", but add a note that "installed fonts referenced directly by family name, rather than via `@font-face` rules, are considered to have a unicode-range that covers the entire Unicode code space".

**Comment by nigelmegitt** [comment]
Both these solutions are slightly missing the point, that fonts don't have a `unicode-range`, only `@font-face` rules do. Nevertheless, there _is_ some applicable set of code points associated with each available font, and it's _that_ which we should reference. I'm neutral on whether we should care about an actual glyph being present at U+0020, but for computation of line height, we clearly do need to care that the font defines some size in the block progression direction that can be used.

**Comment by faceless2** [comment]
> "installed fonts referenced directly by family name, rather than via @font-face rules, are considered to have a unicode-range that covers the entire Unicode code space".

This feels like a good solution to me - until this discussion I'd assumed that's how it worked anyway.

I don't think we should check if the local font has U+0020 actually defined. We explicitly don't do this for web-fonts, it would be inconsistent to require it for local fonts. If for any reason this behaviour needs customising it can be done so with

`@font-face { font-family: "Arial"; src: local(Arial); unicode-range: nnn; }`

**Comment by svgeesus** [comment]
> "the first font for which the character U+0020 (space) is not excluded by a [unicode-range](https://www.w3.org/TR/css-fonts-4/#descdef-font-face-unicode-range) descriptor"?

I like that more precise wording

**Comment by svgeesus** [comment]
> "installed fonts referenced directly by family name, rather than via @font-face rules, are considered to have a `unicode-range` that covers the entire Unicode code space".

Good to make that explicit also. It is a common assumption, but the spec doesn't actually say anything like this.
