### ISSUE TITLE
[css-color] Serializing color() values

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#480]
How should values defined using color() be serialized in computed style?
1. Should color(a b c) or color(srgb a b c) values be output as rgb()?
2. Should color(someprofile a b c) values that end up inside sRGB be output as rgb()?

**Comment by SebastianZ** [comment]
I tend to agree with [Tab's statement to treat `rgb()` as legacy syntax](https://github.com/w3c/csswg-drafts/issues/266#issuecomment-230898208). Therefore I think it should compute to `color(a b c)` in those cases.

Sebastian

**Comment by svgeesus** [comment]
I agree with Tab and SebastianZ

**Comment by grorg** [comment]
Treating it as legacy syntax is fine for input. But the output from computed style is probably parsed by a lot of content on the Web. If that all of a sudden changes to something unexpected, the world will collapse, the seas will rise, and Trump may get elected.

**Comment by upsuper** [comment]
Agree with @grorg, unless someone can prove that changing this output is web-compatible.

**Comment by grorg** [comment]
Wow. I'm regretting my last statement now.

**Comment by cabanier** [comment]
:-( 
It's all your fault!

**Comment by frivoal** [comment]
Reposting a comment I made in #742 as I am closing that one as duplicate:

---

[The css-color-4 definition of the computed value of the color property](https://drafts.csswg.org/css-color/#propdef-color) says :

> Computed value: 	an RGBA color

That doesn't sound right:

* This is not entirely clear what is meant by that. The simplest interpretation is that the value should be computed to the `rgba()` function, but maybe something else is intended.
* If computing to `rgba()` is intended, this appears to contradicts [css-color-3](https://drafts.csswg.org/css-color-3/#color0). The rule there is phrased in a somewhat ambiguous way, but seems to imply that basic colors, hex colors, and `rgb()` colors should be computed to the six digit hex value or `rgb()` functional value, while other notations should be preserved as specified.
* Browsers today (checked Chrome, Firefox, Safari, Edge, Presto) interoperably return `rgb()` (not `rgba()`) as the computed value of hex colors or named colors when exposing it through getComputedStyle. In contradiction of css-color-3, All also do so for `hsl()` colors. And but all but Edge also for `rgba()` and `hsla()` colors with an alpha of 1 (Edge compute both to `rgba()`).
* How to convert `color()` colors to `rgba()` is non trivial and lossy. It needs to happen eventually to be able to paint, but computed value time seems wrong.

If the level 4 text is meant to be different from the level 3, we should errata level 3, and be clearer about what exactly is meant. But given the compat data and the newer color functions, neither "always `rgba()`" nor “as specified, except but #rrggbb `rgb()` and named colors” seems to be the right answer. I think we should specify what is already inter-operable (and see if Edge is willing to join everyone else on computing `rgba(*,*,*,1)` and `hsla(*,*,*,1)` to `rgb()`.

The new color functions that do not yet have a compat baggage, so we should probably be clear before they get one. We could keep them as specified, or maybe convert them to a base notation: `gray()`and `lch()` -> `lab()`, `hwb()` and `hwb()`-> `color()`, omit the alpha component when it is 1.

As for the comma-less version of rgb() and hsl(), we also should decide if the compute to the legacy syntax (with commas), preseve them as written, or compute to `color()`...

**Comment by grorg** [comment]
Resolved. An input of "color" always serializes as "color" Everything else is undefined.

Extra requirement is that "color" serialization doesn't truncate trailing 0 values. e.g. color(srgb 1 0 0).
It is required to drop the "/ 1" for alpha though (if alpha is 100%).

**Comment by zcorpan** [comment]
Should this go into cssom?

**Comment by tabatkins** [comment]
Probably, yes.

**Comment by frivoal** [comment]
Shouldn't that rather go to https://drafts.csswg.org/css-color-4/#resolving-color-values <https://drafts.csswg.org/css-color-4/#resolving-color-values> ?

**Comment by svgeesus** [comment]
> Shouldn't that rather go to https://drafts.csswg.org/css-color-4/#resolving-color-values <https://drafts.csswg.org/css-color-4/#resolving-color-values> ?

Yes. Removing color-3 tag.

**Comment by csnardi** [comment]
The issue of serializing colors specified through `rgb()` with decimal channels still hasn't been resolved; the discussion above seemed to imply that `rgb(0.1, 0.1, 0.1)` should be serialized to `rgb(0, 0, 0)` even if the UA does not round the channel when painting.

[The CSSOM spec](https://drafts.csswg.org/cssom/#serializing-css-values) is no clearer; first it is said the "shortest base-ten *integer* serialization" should be used, but the following 7 lines use the "shortest base-ten serialization".

**Comment by svgeesus** [comment]
I agree it is not yet resolved. And the `integer` part would be an issue; particularly for those color systems that use a bit-depth-neutral  0.0 to1.0 range!

**Comment by svgeesus** [comment]
@grorg wrote:

> Resolved. An input of "color" always serializes as "color" Everything else is undefined.

> Extra requirement is that "color" serialization doesn't truncate trailing 0 values. e.g. color(srgb 1 0 0).
It is required to drop the "/ 1" for alpha though (if alpha is 100%).

Those two resolutions are now in the specification

@csswg wrote

>  RESOLVED: color() functions, if they have a choice between percentage and number, they should use number
> RESOLVED: the `color(lab ...)` function, like the rest of the color() values, are in the 0-1 (or 0% - 100%) range. And they serialize the same as other color() values (as a 0-1 number).

Those two as well.

However, on the 22 Oct 2020 TPAC call, it was also resolved to split out serialization from the specified, computed, used and actual values section into a new section, and I am still working on that, so leaving this open for now.

**Comment by svgeesus** [comment]
> The css-color-4 definition of the computed value of the color property says :

>>    Computed value: an RGBA color

> That doesn't sound right:

The spec no longer says that. Hasn't for some years. (I'm just going through the thread again to be sure nothing was missed).

**Comment by svgeesus** [comment]
All dealt with, CSSWG resolutions implemented, see see [Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values)

>    Should color(a b c) or color(srgb a b c) values be output as rgb()?

No, they are output as `color()`

>    Should color(someprofile a b c) values that end up inside sRGB be output as rgb()?

No, they are output as `color()` as well.

@grorg do these edits resolve all of your concerns?
