### ISSUE TITLE
[css-text-3] tiny editorial issue in § 4.1 The White Space Processing Rules

### ISSUE THREAD

**Issue by TalbotG** [w3c/csswg-drafts#4810]
In the first Note starting [§ 4.1. The White Space Processing Rules](https://www.w3.org/TR/css-text-3/#white-space-rules) , also found in the Editor Draft
https://drafts.csswg.org/css-text-3/#white-space-rules
 , there seems to be a tiny editorial mistake:

"The set of characters considered document white space (part of the document content) and that consider**ed** syntactic white space (part of the CSS syntax) are not necessarily identical."

I think the sentence should be instead:

"The set of characters considered document white space (part of the document content) and that consider**s** syntactic white space (part of the CSS syntax) are not necessarily identical."

Otherwise, the sentence seems awkward or confusing.

Or maybe (seems even better now that I read it) the sentence should be rather (**without "that"**):

"The set of characters considered document white space (part of the document content) **and considered** syntactic white space (part of the CSS syntax) are not necessarily identical."

**Comment by fantasai** [comment]
Fixed as "and those considered syntactic white space (part of the CSS syntax)". Thanks for the report!
