### ISSUE TITLE
[css-scroll-snap] [css-scroll-anchoring] Clarify the interaction between snapping and scroll anchoring

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4830]
Intuitively it seems like snapping should win, but it is the kind of thing that should probably be in a spec? :-)

**Comment by tabatkins** [comment]
Yup, agreed. Hm, not sure which spec should define it - I think I lean to scroll-anchoring?

**Comment by argyleink** [comment]
I have a slide presentation frameworky thing I made that uses scroll snap and scroll anchoring (for deep links). I think it's a great use case and example space for the what and why of this issue. Find it here https://slyd.netlify.com/#natural-flow

**Comment by argyleink** [comment]
https://drafts.csswg.org/css-scroll-snap-1/#re-snap

**Comment by tabatkins** [comment]
All right, we've got text in Scroll Anchoring now that limits it only to valid snap positions when the scrollport is currently snapped.  I've gone ahead and republished, as well.
