### ISSUE TITLE
[css-media-queries-5] Add security and privacy section to "prefers-reduced-data"

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#4832]
[Spec Link](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-data)

During [the WG call](https://github.com/w3c/csswg-drafts/issues/2370#issuecomment-594960678) it was requested/proposed that a section regarding security and privacy be added to the spec for the media query `prefers-reduced-data` to cover fingerprinting concerns.

**Comment by yoavweiss** [comment]
SaveData's privacy section is defined at https://wicg.github.io/savedata/#privacy-considerations

Can we resolve this by pointing to that?

Also, is there a privacy section for the prefers-reduced-motion MQ?

**Comment by astearns** [comment]
There should be a top-level privacy section for the whole spec, which should include some analysis of prefers-reduced-motion, too. I’d prefer it stood alone - a link out to a WICG document probably is not sufficient.
