### ISSUE TITLE
[media-queries-5] should "prefers-reduced-data" be binary or not

### ISSUE THREAD

**Issue by argyleink** [w3c/csswg-drafts#4833]
[Spec Link](https://drafts.csswg.org/mediaqueries-5/#prefers-reduced-data)

During [the WG call](https://github.com/w3c/csswg-drafts/issues/2370#issuecomment-594960678) it was requested/proposed that confirmation and research be done to ensure that data-saver shouldnt feature enums (low, medium, high, etc) or a range/spectrum/etc **instead of** a binary preference. The concern is that the current spec is only solving the current state of data saver preferences, and potentially isn't thinking enough about future queries that developers may need. 

This issue is to hold the discussion around the values accepted for the media query `prefers-reduced-data`.

**Comment by yoavweiss** [comment]
The MQ as currently specified maps the [JS API](https://wicg.github.io/savedata/#navigatornetworkinformation-interface) into CSS.

If it were to be extended in the future, what would prevent us from extending it at that point in time?

**Comment by argyleink** [comment]
Research shows me we're on track with a binary toggle. The user is flipping a switch to indicate the preference, just like `prefers-reduced-motion`.

<details>
<summary>iOS: Low Data Mode</summary>

<img width="320" src="https://user-images.githubusercontent.com/1134620/76005678-38544500-5ec0-11ea-88e7-d9e1c7c0107b.png"/>

</details>

<details>
<summary>Android: Data Saver</summary>

![image](https://user-images.githubusercontent.com/1134620/76005750-502bc900-5ec0-11ea-8475-ccb025c24d28.png)

</details>

Windows has ways to limit data, but doesn't have a system wide switch for it. Would love to hear if there's plans for it or not. 

Worth noting too that these data saver modes can be toggled much easier than reduced motion, they're accessible from "quick settings" areas of each platform.

**Comment by frivoal** [comment]
Agenda+ to see if there's anything new on this topic, or if we should close in favor of the binary toggle status quo
