### ISSUE TITLE
[css-mediaqueries-5] Note/Issue on not shipping early proposals

### ISSUE THREAD

**Issue by astearns** [w3c/csswg-drafts#4834]
One of the things we talked about adding to the level 5 spec is an issue warning against shipping prefers-reduced-data, as we are just now starting to discuss that feature:

https://github.com/w3c/csswg-drafts/issues/2370#issuecomment-594960678

Looking at the entire spec, I'm not sure any of the proposals there are ready to ship. The lack of a privacy section is the most glaring omission (captured here: https://github.com/w3c/csswg-drafts/issues/4832 ), but I think there are still a lot of discussion needed for the entire doc.

What if we added a Note to the intro to go along with the diff spec Note asking implementers to hold off shipping anything in this spec until we’ve done the work and cleared things feature-by-feature? What do you think, @tabatkins @frivoal @grorg?

**Comment by argyleink** [comment]
has time hardened the syntax?
how come reduced data feels flagged as more of a privacy threat than reduced motion?
