### ISSUE TITLE
[css-cascade][cssom] Issues with legacy name alias

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#4839]
https://drafts.csswg.org/css-cascade-4/#legacy-name-alias

> legacy name aliases
> When the old property’s syntax is identical to **or a subset of the value space of** the new property’s syntax, the two names are aliased with an operation on par with case-mapping: at parse time, the old property is converted into the new property. This conversion also applies in the CSSOM, both for string arguments and property accessors: requests for the old property name transparently transfer to the new property name instead.

Which property, if any, uses a subset of the value space?

As far as I can tell, the only uses of the "legacy name alias" concept are `-webkit-appearance`  and `word-wrap` , neither of which are specified as having a subset of the value space of the new property's syntax.

```
$ git grep "legacy name alias"
css-cascade-4/Overview.bs:              <dt><dfn lt="legacy name alias">legacy name aliases</dfn>
css-cascade-4/Overview.bs:                              <css>old-name</css> is a <a>legacy name alias</a> for <css>new-name</css>,
css-text-3/Overview.bs:    <p>For legacy reasons, UAs must treat 'word-wrap' as an [=legacy name alias=]
css-ui-4/Overview.bs:as a [=legacy name alias=] of 'appearance'.
```

https://compat.spec.whatwg.org/ doesn't reference this concept, but it probably should. `-webkit-linear-gradient()` and friends aren't simple aliases, but also aren't subsets. How is this handled in serialization?

The definition of legacy name alias also monkey patches CSSOM. I think it should be defined in the relevant algorithms in CSSOM, like https://drafts.csswg.org/cssom-1/#dom-cssstyledeclaration-getpropertyvalue and https://drafts.csswg.org/cssom-1/#dom-cssstyledeclaration-setproperty

cc @emilio @tkent-google @tabatkins @miketaylr

**Comment by miketaylr** [comment]
Maybe `-webkit-background-size` is an example that uses a subset of unprefixed `background-size`'s value space? 

https://github.com/whatwg/compat/issues/28

**Comment by emilio** [comment]
> https://compat.spec.whatwg.org/ doesn't reference this concept, but it probably should. -webkit-linear-gradient() and friends aren't simple aliases, but also aren't subsets. How is this handled in serialization?

They also aren't properties :-)

In Gecko, we parse some webkit gradients but upgrade them to modern syntax when possible.

**Comment by fantasai** [comment]
@zcorpan An example might be `word-wrap`, which only accepted `normal` and `break-word`; we added an `anywhere` value. But didn't define `word-wrap` to not accept the new value, which is an interesting detail we forgot to consider.

**Comment by fantasai** [comment]
Agenda+ to ask the WG whether legacy name alias properties should be "upgraded" to accept new syntaxes added to their aliased property (being strictly a name alias), or whether they should be syntactically frozen (have stricter restrictions on value space).

[Also to assign the CSSOM edits to someone.]

**Comment by zcorpan** [comment]
I think it's simpler to let aliases have exactly the same value space. That we don't want people to use the old property name isn't a good reason to add complexity, imo.
