### ISSUE TITLE
[css-values-3] Drop the Values 3 version of attr() back to single-arg form

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4840]
Values 3 still has the older 2-arg form of attr(), before the significant changes we agreed on to make it more implementable. This appears to be the only significant thing in the draft that would block it from going to REC.

Can we either (1) rewrite it to the single-arg version that's always a `<string>` and only usable in 'content', or (2) drop it entirely from this version, as the single-arg syntax is already well-defined in css-content?

(And then, presumably, do the final cleanup work to get this ready for REC.)

**Comment by fantasai** [comment]
I would go with option (1).

**Comment by tabatkins** [comment]
Closing since we punted the whole feature to L5.
