### ISSUE TITLE
subtree-visibility CSS property

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#4843]
I would like CSSWG feedback on the proposed [subtree-visibility CSS property](https://wicg.github.io/display-locking/index.html).

subtree-visibility solves the same use cases as the previous `rendersubtree` element attribute that was presented to the CSSWG at TPAC 2019. [1] The changes are:
* Now a CSS property with only 3 values (`visible`, `auto`, `hidden`).
* `hidden` subtrees, and `auto` subtrees that are offscreen, are invisible; otherwise visible
* "invisible" is semantically very similar to what `visibility:hidden` does today
* `auto` subtrees are also exposed to accessibility and all UA features such as find-in-page
* There is no activation event or updateRendering method
* UA is encouraged but not required to skip rendering work for invisible subtrees

I'd appreciate feedback on all of the feature of course, but in particular:
* Naming
* Semantics related to boxes and flat trees

Chromium has implemented this CSS property fully, and if all goes well hoping to ship it. There is an explainer [here](https://github.com/WICG/display-locking/blob/master/README.md). It can be turned on for testing via chrome://flags/#enable-experimental-web-platform-features.

Related issues include #4531 and  #4229.
----

[1] Unofficial Meeting notes from Dael Jackson below:

rendersubtree
-------------

  - chrishtr introduced the proposal for a rendersubtree attribute.
      Proposal text:
https://github.com/WICG/display-locking/blob/master/README.md
      Proposed PR: https://github.com/whatwg/html/pull/4862
      Github issue: https://github.com/whatwg/html/issues/4861
  - The 'rendersubtree' attribute controls whether the subtree is
      laid out and rendered or not, in order to allow browsers to be
      more performant and authors to reserve space for an element that
      is not yet loaded. This also introduces an "activation" concept
      which allows the browser to choose to render.
  - Several members expressed concern that this felt more like a CSS
      property. The reason it was not written to be is because the UA
      is allowed to overwrite it.
  - The use case for 'invisible' and not 'activatable' is so the author
      can prevent not-yet-rendered content from being shown. It was
      suggested the default should be 'activatable' since authors might
      not think through all cases of 'invisible' if it's the default.
  - It was suggested to add callbacks for the activation actions so
      authors could listen for the changes.
  - The difference between this and 'contain: all' is that this would
      prevent animations from loading. Meanwhile, the difference to
      'display: none' is that the layout work is still done in this
      case.
  - More info at https://github.com/whatwg/html/issues/4861

**Comment by fantasai** [comment]
> Chromium has implemented this CSS property fully, and if all goes well hoping to ship it.

Is Chrome planning to write a consensus-backed spec and publish it through the CSSWG as an official feature before shipping it, or is this issue just about getting a cursory review prior to to implementing and shipping off Chrome's explainer in the WICG? It's not clear to me whether you're asking CSSWG to adopt the feature for standardization, or just to make some review comments quickly before some imminent shipping deadline...

**Comment by chrishtr** [comment]
> It's not clear to me whether you're asking CSSWG to adopt the feature for standardization, or just to make some review comments quickly before some imminent shipping deadline... Is Chrome planning to write a consensus-backed spec and publish it through the CSSWG as an official feature before shipping it, assuming CSSWG approves your proposal, or is this issue just about getting a cursory review prior to to implementing and shipping off Chrome's explainer in the WICG?

Yes I would like the CSSWG to adopt this spec soon, though I didn't ask for that in today's call. (The same goes for `contain-intrinsic-size` BTW.)

I don't just want a cursory review, I would like substantial feedback on this API. Further, there is  an actual [draft spec](https://wicg.github.io/display-locking/index.html), not just an explainer.

While it's true that Chromium has implemented this feature and hopes to ship it soon, there has been a lot of public discussion and feedback from many parties on it and previous iterations, including the CSSWG. Further review and feedback is not just a formality, I really do want more feedback to identify any concerns or ways it could be improved.

**Comment by chrishtr** [comment]
Hi all, any feedback on this CSS property?

Any issue with the name? Semantics?

Agenda+ to request final review of this feature's shape.

**Comment by chrishtr** [comment]
Here are some potential issues to resolve:

https://github.com/WICG/display-locking/issues/126 (is "auto" a good name for a non-default state?)

https://github.com/WICG/display-locking/issues/127 (is "subtree" a good word to use?)

There are also some other open issues on the spec:
https://github.com/WICG/display-locking/issues

**Comment by fantasai** [comment]
@chrishtr IMHO `auto` is acceptable for a non-default state, its primary meaning is "this does some special non-straightforward calculation and/or is UA-defined". Wrt `subtree`, I agree with dbaron, it's not a term we use in CSS. Would suggest `content` instead, which we do use.

**Comment by FremyCompany** [comment]
FWIW, I think this is a good proposal. Thanks @chrishtr et al. for working on this!

**Comment by tabatkins** [comment]
Hmm, `content-visibility` isn't bad, yeah. It does indeed match the meaning of, say, `display:contents`, and still clearly indicates that it doesn't affect the visibility of the element itself.  👍

**Comment by dholbert** [comment]
One bit of feedback from reading the spec:

The concept of "skipped" is a bit fuzzy right now. The spec defines it in a *descriptive* way right now, as if it's a classification that some elements naturally fall into:
 > skipped: an element is **considered skipped if** its subtree is not painted or hit-tested.

... but then later it uses the term as if it's an classification that can be applied by the UA, which has prescriptive requirements (e.g. `subtree-visibility:hidden` is defined saying "The element is skipped.").

These usages need to be harmonized, probably by rewriting the definition of "skipped" such that it's prescriptive rather than descriptive.  e.g. perhaps rephrasing as "if an element is *skipped*, it must not be painted or hit-tested [...]" or similar.

**Comment by dholbert** [comment]
Another bit of feedback on a sentence in the green note below the property-definition:
> The fact that off-screen elements with subtree-visibility: auto are skipped is a rendering performance optimization.

This wants `s/that/that some/`

(Otherwise, it can be misread as implying that *all* off-screen elements with `subtree-visibility: auto` will be "skipped". And that's not true, per the definition of "auto" - there are more requirements besides simply being offscreen.)

**Comment by fantasai** [comment]
We agreed to move subtree-visibility into the CSSWG. Proposed to merge it into css-contain-2, as they are pretty tightly related.

**Comment by frivoal** [comment]
Moving it to contain-2 makes sense to me. Should Tab or I be taking an action to do this, as Editors of contain-2, or should we be getting a new co-editor?

**Comment by chrishtr** [comment]
Vladimir Levin is joining the CSSWG, and would like to be a new co-editor of this spec. @vmpstr

**Comment by chrishtr** [comment]
Done.
