### ISSUE TITLE
[cssom] Should the margin at-rules and CSSMarginRule be dropped?

### ISSUE THREAD

**Issue by saschanaz** [w3c/csswg-drafts#4849]
There hasn't been a single implementation since fcce4aaed2c3d42b19168a323b18d3c3424f9f02 defined it back in 2013. What's the current status of it, should it be dropped or is anyone working on an implementation?

**Comment by tabatkins** [comment]
The OM rule's lack of implementation is due to the lack of implementation of the at-rules themselves, right? At least in Chrome, they're dropped as syntax errors, so of course we wouldn't expose the OM side either.

We shouldn't remove the OM so long as the at-rules are expected to be implemented.

**Comment by carlosame** [comment]
> There hasn't been a single implementation since [fcce4aa](https://github.com/w3c/csswg-drafts/commit/fcce4aaed2c3d42b19168a323b18d3c3424f9f02) defined it back in 2013.

I am not aware of browser implementations, but FWIW it is implemented in css4j:

https://css4j.github.io/api/2.0/io/sf/carte/doc/style/css/CSSMarginRule.html

**Comment by saschanaz** [comment]
>We shouldn't remove the OM so long as the at-rules are expected to be implemented.

Not sure I understand, you mean at least one browser is working on `@top-left` etc.?

**Comment by carlosame** [comment]
The Firefox issue for implementing margin rules is this one:

https://bugzilla.mozilla.org/show_bug.cgi?id=856371

and apparently there isn't a lot of activity (last update 4 years ago).

**Comment by tabatkins** [comment]
What I mean is that every at-rule needs an OM representation; they're 1:1. We shouldn't drop the OM unless we're dropping the at-rule as well.

**Comment by carlosame** [comment]
Reacting to the title change, I do not see why the at-rules should be dropped. CSS authors definitely want this functionality and, while browsers are lagging behind a bit (see [Chromium issue 320370](https://bugs.chromium.org/p/chromium/issues/detail?id=320370) and [Webkit bug 85062](https://bugs.webkit.org/show_bug.cgi?id=85062)), others are supporting it (not only the css4j library, for example I have seen references about AH software supporting them to print PDFs).

**Comment by saschanaz** [comment]
>while browsers are lagging behind a bit

I think that's why I opened this. I wasn't sure there are any intent to implement, and it turns out that both of the bugs are inactive.

**Comment by carlosame** [comment]
> I think that's why I opened this.

Those rules are of minor priority to browsers, but of major importance to those focusing on printing paged media.

**Comment by fantasai** [comment]
There's multiple implementations of the margin at-rules, just not in browsers. I don't think we can drop them.
