### ISSUE TITLE
[css-values] Take a dependency on Infra string

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#4851]
That way we don't end up with two dfns of string. Spotted by @andreubotella in https://github.com/whatwg/encoding/pull/199.

**Comment by tabatkins** [comment]
Yeah, that's reasonable. Done in ed9468f9f.

**Comment by annevk** [comment]
Thanks Tab, but https://drafts.csswg.org/css-values-3/#strings continues to define this and is apparently still indexed.

**Comment by tabatkins** [comment]
And done, tho the definitions are still present in the /TR versions. However, that *should* avoid getting grabbed by anything in whatwg, since they're all "current" status.

**Comment by annevk** [comment]
Those are also not in Shepherd I hope?

**Comment by tabatkins** [comment]
Why wouldn't they be?

**Comment by annevk** [comment]
I guess I never really thought about it much, but I was hoping there would be one canonical place for each thing.
