### ISSUE TITLE
[css-transforms] Update 'issues list' link to GitHub?

### ISSUE THREAD

**Issue by RByers** [w3c/csswg-drafts#486]
Looks like most recent issues on this spec are [here in GitHub](https://github.com/w3c/csswg-drafts/issues?utf8=%E2%9C%93&q=is%3Aissue%20%5Bcss-transforms%5D), while those [at Bugzilla](https://www.w3.org/Bugs/Public/buglist.cgi?query_format=advanced&product=CSS&component=Transforms&resolution=---&cmdtype=doit) as linked by the spec appear old.

The "Issues link" in the spec should probably be updated to GitHub.  Perhaps the few remaining bugzilla bugs should also be migrated over (or archived)?

**Comment by smfr** [comment]
Bugzilla bugs have been migrated over to GitHub.

**Comment by smfr** [comment]
dc6f45df5793e267a0d15c19a8f2996a227a5847
