### ISSUE TITLE
[css-transforms] inconsistency of computed value serialization (transform should be a resolved value special case property so getComputedStyle() returns matrix())

### ISSUE THREAD

**Issue by george-steel** [w3c/csswg-drafts#4869]
For the transform property, the spec says that
> Computed value: as specified, but with lengths made absolute
> Value: none \| `<transform-list>`
> `<transform-list>` = `<transform-function>+`

and provides a procedure for serializing transform individual transform functions. This seems to imply that the [*computed value*](https://drafts.csswg.org/css-cascade/#computed) should be serialized as a list of functions. Furthermore, there are procedures such as interpolation which expect computed values to be lists of functions.

Later in the spec there is a section
> Serialization of the computed value of `<transform-list>`

which gives a procedure specifying conversion to a matrix, an operation which does not round-trip (round-tripping is necessary for css transitions) and relies on the box size (not allowed for computed values). Although this makes sense for serializing the [*resolved value*](https://drafts.csswg.org/cssom-1/#resolved-value) (which is returned by `getComputedStyle()`) specifying this happens to the *computed value* looks like a confusing typo to me.

This may be a historical oversight from before the difference between computed and resolved value (sometimes historically referred to as computed value serialization) was fully clarified. We should correct this.

**Comment by george-steel** [comment]
@birtles @stephenmcgruer

**Comment by george-steel** [comment]
Also, if there is no layout box, should we perform the conversion with a (0,0) box size (what firefox does) or should we simple return the computed value as the resolved value (what all other properties do except for line-height). Chrome currently simply gives up and returns none here.

**Comment by george-steel** [comment]
@emilio

**Comment by emilio** [comment]
> This may be a historical oversight from before the difference between computed and resolved value (sometimes historically referred to as computed value serialization) was fully clarified. We should correct this.

Yeah, I think transform to `matrix()` serialization should be a resolved value operation.

> which does not round-trip

Can you elaborate? I think it should roundtrip... When doesn't it?

See also https://github.com/w3c/csswg-drafts/issues/3305 where some related differences this came up.

**Comment by dbaron** [comment]
Yeah, I think what needs to happen here is that transform should (like transform-origin) be defined as a [resolved value special case property](https://drafts.csswg.org/cssom-1/#resolved-value-special-case-property), and the [relevant section](https://drafts.csswg.org/css-transforms-1/#serialization-of-the-computed-value) should be rewritten accordingly.
