### ISSUE TITLE
[css-values] Quirky lengths and math expressions

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4874]
Quirks mode allows to specify lengths without units, so do some SVG properties like `stroke-width`. However, when you mix this with calc() units, stuff gets complex very fast (`calc()` becomes ambiguous) and the results across browsers become a bit bizarre.

Trivial example ([link](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!doctype%20html%3E%0A%3Cdiv%20id%3Da%20style%3D%22stroke-width%3A%20calc(2%20*%202)%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20id%3Db%20style%3D%22stroke-width%3A%20calc(2px%20*%202)%22%3E%3C%2Fdiv%3E%0A%3Cscript%3E%0Aw(getComputedStyle(a).strokeWidth)%3B%0Aw(getComputedStyle(b).strokeWidth)%3B%0A%3C%2Fscript%3E)):

```html
<!doctype html>
<div id=a style="stroke-width: calc(2 * 2)"></div>
<div id=b style="stroke-width: calc(2px * 2)"></div>
```

All browsers agree on the computed value of `#b`, being `4px` as expected. For `#a`, we get:

 * Firefox: Computed value is the initial value (`1px`) because the expression doesn't parse (Firefox doesn't propagate this quirk into `calc()`).
 * WebKit: It parses, computed value is `0px`.
 * Blink: It parses, computed value is `2px`.

I think having the ambiguity of whether a `<number>` should be treated something is a `<length>` or not inside math expressions is not worth it and it's only going to get more complex as we add more math functions. Thus I'd like to standardize on Firefox's behavior, if other people agree.

Otherwise we could try to parse / resolve `calc()` both as a `<number>` and a `<length-percentage>`, I guess, which would allow for the previous example, but would disallow stuff like `calc(4 * 100% + 4)` or such...

Relevant links:

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1258270#c5 started this.
 * https://bugs.chromium.org/p/chromium/issues/detail?id=1061714
 * https://bugs.webkit.org/show_bug.cgi?id=209116

cc @tabatkins @lilles @andruud

**Comment by emilio** [comment]
cc @smfr too :)

**Comment by emilio** [comment]
Also, note that I really think that Firefox's behavior is more desirable for the "regular length in quirks mode case". I think the "svg-originated property" case is a bit more debatable, but I still think it's better.

**Comment by plinss** [comment]
Huge +1 on this. Quirks mode was designed for backwards compatibility for features that pre-dated 1998. It was *never* intended to propagate into anything new. All new features should be standards mode only.

**Comment by AmeliaBR** [comment]
We already have agreement that inside a calc expression, numbers are always treated as numbers, not lengths. So a `calc(10 + 2px)` would always be invalid.

The question is, if the final evaluated result is a number (`calc(100/3)`), is that OK? Can it be mapped from number to length after the calculation is complete, or does the mapping need to happen at parsing time?

> so do some SVG properties

For SVG 2, we have two rules for this:

- For SVG-specific properties like [`stroke-width`](https://svgwg.org/svg2-draft/painting.html#StrokeWidth), the property grammar now explicitly allows a `<number>` type as an alternative to a `<length>` or `<length-percentage>`. So, a calc expression that evaluates to a number _should_ be fine. (Actual browser support for calc in SVG stuff is a mess of inconsistency, though).

- For properties defined by other CSS specs, like `font-size`, unitless lengths are allowed in the SVG presentation attribute only, and the SVG 2 spec currently explains this by [an algorithm](https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value) that upgrades all `<length>` values in the grammar to `<length>|<number>`, and so on.
  
  But I'm not sure how implementable that is if we combine it with `calc()` expressions and things like TypedOM that need access to a standard serialization of the specified value. So if you can think of a better way to define this, consistent with how you want to handle quirks mode, that would probably work here, too.

**Comment by emilio** [comment]
> For SVG-specific properties like stroke-width, the property grammar now explicitly allows a `<number>` type as an alternative to a `<length>` or `<length-percentage>`. So, a calc expression that evaluates to a number should be fine. (Actual browser support for calc in SVG stuff is a mess of inconsistency, though).

I think what Firefox implements is basically this, but with `<number-token>` instead of `<number>`. Supporting `calc()` resolving to a number would be doable, but not sure it's worth doing, because it's the wrong thing to do for quirks, and I'd rather not introduce yet another svg-specific parsing mode.

**Comment by faceless2** [comment]
> For SVG-specific properties like stroke-width, the property grammar now explicitly allows a `<number>` type as an alternative to a `<length>` or `<length-percentage>`. So, a calc expression that evaluates to a number should be fine. (Actual browser support for calc in SVG stuff is a mess of inconsistency, though).

My understanding of this is a little different. For non-quirks mode:

1. Dimension properties specified as presentation attributes can be specified as numbers or lengths -  both`<line stroke-width="2">` and `<link stroke-width="2px">` mean the same thing.

2. But if the same properties are specified as CSS, which includes the "style" attribute, then they are parsed as CSS declaration lists, are subject to CSS parsing rules and units are required. So you can do `<line style="stroke-width: 2px">` but _not_ `<line style="stroke-width: 2">`

This describes the behaviour of Firefox, Webkit etc. for attributes like width, x, r etc. 

If quirks mode allows length properties to be parsed without units in CSS, then I think that really needs to apply to all length properties - regardless of which specification they're defined in. So `<line style="stroke-width: 2">` is as valid as `<rect style="width: 200">` or `<text style="font-size: 20">`.

What this means for "calc" I don't know. Personally I completely agree with @plinss  on this, it should be invalid. You can't evolve quirks mode to keep up with changes in the specification.

But, if the decision is made that `<div style="width: calc(300 + 3)">` is valid, then I think you necessarily have to allow `<line style="stroke-width: calc(300 + 3)">`. Treating them differently depending on where they're defined is going to cause [problems](https://www.w3.org/TR/fill-stroke-3/#stroke-width)

---

Additional point, very specific to SVG2. This [states](https://svgwg.org/svg2-draft/types.html#presentation-attribute-css-value) all presentation attributes are parsed using the grammar and types defined in CSS, modified so that wherever`<length>` is allowed, you're also allowed `<number>`. My reading of this is that `<line stroke-width="calc(20px + 20px)">` is valid in SVG2, although it's certainly not in SVG1 and this syntax is unsupported in any browser. As @emilio  has already pointed out, it's also impossible to modify this grammar to allow numbers where a length is allowed. It's quite possible I've got this wrong, but perhaps this section of the SVG2 spec might benefit from clarification.

**Comment by tabatkins** [comment]
Firefox has the correct behavior. Quirky lengths aren't any different from unitless zeros - inside a calc(), they're a "number", and the type-checking rules don't allow numbers to be added to non-numbers, etc.

Both Blink and WebKit are wrong, and wrong in *bizarre and clearly incorrect* ways.

Amelia is right that properties which are defined with an explicit `<number>` in their grammar (which then interpret it as a px length) should accept `calc(2 * 2)`, and interpret it as 4px. But without that, the quirky-length behavior is a parsing quirk like unitless zeros, and doesn't allow length-accepting properties to take a calc() that resolves to a number.

**Comment by AmeliaBR** [comment]
Again, for SVG there are two different sets of behavior: properties like `stroke-width` which allow unitless numbers anywhere, _including_ in CSS declarations, versus those (like `font-size`) that only allow it in presentation attributes.

I agree that it makes sense to harmonize the second case with other quirky CSS parsing. We can change the SVG spec to link to wherever in CSS that's defined, and just say that SVG presentation attributes use quirky parsing.

But `stroke-width` (and `stroke-dasharray` and a bunch of other SVG-specific style properties) are different. They take unitless numbers regardless of whether they are defined in attributes or in style declarations. In SVG 1 it was handwavy and spec'd that numbers are valid lengths for these properties. But it's now defined explicitly in SVG 2 using CSS grammar: numbers and lengths are parsed as separate things, but either are valid. Numbers should only be converted to length at used value time, similar to how `line-height` works.

That seems to be how it works in Chromium: numbers and calc resulting in numbers are both fine in the stroke properties, regardless of attributes or style declarations.  Firefox is inconsistent with the spec by only allowing literal numbers. But again, they support it in both style properties and attributes. [Test case](https://codepen.io/AmeliaBR/pen/ExjLyJz?editors=1100)

Meanwhile, for `font-size` (same test case link), both browsers are consistent in not supporting unitless numbers for CSS declarations, but allowing literal numbers in the attributes. Chromium has the same buggy behavior for calc in attributes as Emilio described above for quirky lengths: it's accepted at parse, but then at computed time it becomes `font-size: 0px`. (Firefox just ignores the calc as invalid.) So, at least we already have consistency that this is being treated the same as other quirky CSS parsing!

**Comment by faceless2** [comment]
My error, I'd missed that `stroke-width` in SVG is explicitly defined to accept a number in the grammar. For reference I think the complete list of properties defined in SVG where the grammar defines a number can represent a length is:

* stroke-width
* stroke-dasharray
* stroke-dashoffset

Unfortunately each of these is also defined in css-fill-stroke-3 as taking a `<length-percentage>` only - I know that spec isn't implemented by anyone yet, but this inconsistency should probably be resolved.

**Comment by lilles** [comment]
This is strictly not about quirkiness in Blink, it is about incorrectly allowing calc expressions which mix percentages and numbers, lengths and numbers, and all three of lengths, percentages and numbers.

I have a CL up for review in Blink (which still accepts calc() for <number> which should be per spec):

https://chromium-review.googlesource.com/c/chromium/src/+/2134251/
