### ISSUE TITLE
Migrate CSS2 prop/value/type dfn to Bikeshed/Shepherd syntax

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#4880]
Shepherd currently has [magic support](http://hg.csswg.org/dev/specification/file/4a110a36c1cc/python/specification/specificationparser.py#l998) for how CSS2 is marked up; this will break when we republish as we'll no longer be using `a[name]` for them.

While we could just modify Shepherd here, for propdefs it's essentially no work (changing the build system), and for the others it's probably worthwhile in case we want to move CSS2 to BS in future.

**Comment by tabatkins** [comment]
Note that Shepherd will not use the weird heuristics if the dfn is marked up normally for Bikeshed, so no changes to Shepherd *should* be required as we update things.

**Comment by gsnedders** [comment]
> Note that Shepherd will not use the weird heuristics if the dfn is marked up normally for Bikeshed, so no changes to Shepherd _should_ be required as we update things.

The heuristics rely on `a[name]` and we can't use `a[name]` as it isn't conforming [[HTML]] [[PUBRULES]].

**Comment by tabatkins** [comment]
I'm confused; your response feels like a non sequitur.

What I mean is that if we update things to be marked up properly for Bikeshed, Shepherd will automatically pick those up instead of trying to use heuristics, so we shouldn't need to do anything with Shepherd's code. We can just update css2 to use bs markup and we'll be fine.

**Comment by plinss** [comment]
Shepherd also has a number of other heuristics, as long as the anchor has or is inside an ancestor with a 'propdef'/'valuedef'/'valdef'/'vdef'/'typedefdef' class you'll be fine. But I agree, modifying the css2 build system to output proper dfn markup will be better for everyone. Seems like you're modifying it anyway to remove the a[name]s.

**Comment by gsnedders** [comment]
I think we're talking past each other. Yes, if we use `<dfn>` everything will just work.
