### ISSUE TITLE
[css-flexbox] How to determine the main/block size of a column flex container?

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#4905]
A somewhat early step of the Flex Layout Algorithm is: https://drafts.csswg.org/css-flexbox/#algo-main-container
>  Determine the main size of the flex container using the rules of the formatting context in which it participates. For this computation, auto margins on flex items are treated as 0. 

Let’s say that that we have a column flex container in horizontal writing mode (so the main size is the block size which is the height) with `height: auto`.

Let’s also that that it is block-level, so the relevant definition is: https://drafts.csswg.org/css2/visudet.html#normal-block
> The element's height is the distance from its top content edge to the first applicable of the following: […]

This definition for the height of block-level boxes relies on the content being fully laid out, which is not the case this early in the Flex Layout Algorithm.

Am I missing something or is this under-specified? Should there be something that specifies that `height: auto` resolves to `height: max-content` in that case, "redirecting" to the rules in https://drafts.csswg.org/css-flexbox/#intrinsic-sizes?

**Comment by fantasai** [comment]
We added a note defining that the automatic block size of a block-level flex container is its max-content size... technically that definition doesn't belong here, but in the spec defining block layout.

Filed https://github.com/w3c/csswg-drafts/issues/5197 as a follow-up on CSS2 to at least get it to not conflict even if it's not possible to make it quite as tight a connection as we would in a CSS3+ spec.

Let us know if this works for you. @SimonSapin

**Comment by SimonSapin** [comment]
"automatic block size" has link markup in 84dabef612960fb8e85e2a0522e164f0f1a25c6f (presumably intended to link to https://drafts.csswg.org/css-sizing/#automatic-size, which I just learned is a formal concept we have) but it is not a link in in https://drafts.csswg.org/css-flexbox/#algo-main-container.

Shouldn’t the first new sentence be normative rather than in a note?

The new text says "The Block Layout spec should define this equivalency" but should it really? If it’s specifically about flex containers.

**Comment by fantasai** [comment]
> Shouldn’t the first new sentence be normative rather than in a note? The new text says "The Block Layout spec should define this equivalency" but should it really?

No, it's Block Layout that decided that every box should use its max-content block size. Items in Flex Layout and Grid Layout, for example, don't use their max-content block size by default. (This should be normatively defined somewhere, but since it really doesn't belong in *this* spec we're leaving it as a note.)
