### ISSUE TITLE
[css-flexbox] Collecting items into lines: use hypothetical main sizes?

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#4906]
https://drafts.csswg.org/css-flexbox/#algo-line-break
> collect consecutive items one by one until the first time that the next collected item would not fit into the flex container’s inner main size

What does it mean for items to “fit”? Given that this step comes soon after computing a *hypothetical main size* for each flex item it would make sense to rely on those (plus main axis padding and borders and margins, with zero for `auto` margins), but that is not defined.

**Comment by Loirooriol** [comment]
Isn't it already defined in the next paragraph?

> For this step, the size of a flex item is its outer hypothetical main size.

**Comment by SimonSapin** [comment]
Hmm it looks like I just missed this when reading that section. Sorry!
