### ISSUE TITLE
[css-sizing-4] [mediaqueries-4] [css-values-4] Definition of <ratio> should probably be in css-values

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#4908]
Both css-sizing-4 and mediaqueries-4 use a <ratio> type:
https://drafts.csswg.org/css-sizing-4/#aspect-ratio
https://drafts.csswg.org/mediaqueries-4/#typedef-ratio

The former links to the latter for its definition, but it seems it would be better if it were defined in the "CSS Values and Units" spec instead.

**Comment by tabatkins** [comment]
Yeah, we considered this previously, but left `<ratio>` alone in MQ because it was still the only consumer, and we generally want to keep V&U only for cross-language types.

But now that `<ratio>` *is* used across multiple specs, yeah, it probably should migrate to V&U.
