### ISSUE TITLE
[css-logical-props] `border‐radius`

### ISSUE THREAD

**Issue by zamfofex** [w3c/csswg-drafts#491]
`border‐radius` was left out of [css-logical-props](https://drafts.csswg.org/css-logical-props/) for no aparent particularly good reason.

I think the following properties should be present in the spec:

```
border-start-start-radius
```

```
border-start-end-radius
```

```
border-end-start-radius
```

```
border-end-end-radius
```

The first part would be related to the block axis and the second part to the inline axis.

And alternative would be `border-block-start-inline-start-radius`, but that feels unnecessarily verbose.

**Comment by chharvey** [comment]
I would also suggest adding the following shorthands, if you want to put a border-radius on only one side of a box. Each shorthand syntax would be:
```
<length-percentage>{1,2} [ / <length-percentage>{1,2} ]?
```

(Similar to the [`border-radius` shorthand](https://drafts.csswg.org/css-backgrounds-3/#border-radius).)

property | shorthand for
--------- | -------------
`border-block-start-radius` | `border-start-start-radius` `border-start-end-radius`
`border-block-end-radius` | `border-end-start-radius` `border-end-end-radius`
`border-inline-start-radius` | `border-start-start-radius` `border-end-start-radius`
`border-inline-end-radius` | `border-start-end-radius` `border-end-end-radius`

**Comment by fantasai** [comment]
It was left out because css-logical is mainly about the CSS2-level properties: newer modules are expected to define their logical features themselves, and for css-backgrounds that will be in Level 4.

**Comment by fantasai** [comment]
CSSWG resolution on this topic: https://lists.w3.org/Archives/Public/www-style/2015Feb/0504.html

**Comment by chharvey** [comment]
Another thing to consider is the order of the two-value syntax for ellipse radii.

In the current spec, `border-top-left-radius: 55px 25px;` sets the x-radius (horizontal) to 55px and y-radius (vertical) to 25px. However if we want to use the convention "block before inline" this may have to be reconsidered.

On one hand, it would be much more consistent to have Y before X for everything, so authors don't have to remember which properties are “X before Y” (like background-size) and which are “Y before X” (like margin). But I think that's more of a theoretical than practical way of thinking.

On the other hand, if the x- and y- axes of the ellipse truly don't depend on direction/writing-mode, then it might be best to keep as is.

**Comment by SebastianZ** [comment]
@zamfofex The properties suggested by you already [made it into the spec.](https://drafts.csswg.org/css-logical-1/#border-radius-properties) in the meantime.

@chharvey:
> I would also suggest adding the following shorthands, if you want to put a border-radius on only one side of a box.

Those were [added to CSS Borders 4](https://drafts.csswg.org/css-borders-4/#corner-sizing-side-shorthands).

> Another thing to consider is the order of the two-value syntax for ellipse radii.

Browsers shipped the properties with the horizontal-first syntax a long time ago. So changing the order now would be web-incompatible.

I think it's safe to close this issue now. If I am missing something, please feel free to reopen it or file new issues.

Sebastian
