### ISSUE TITLE
[css-grid] Does grid-template-areas really expand the explicit grid?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#4914]
From https://drafts.csswg.org/css-grid/#implicit-grids

> The `grid-template-rows`, `grid-template-columns`, and `grid-template-areas` properties define a fixed number of tracks that form the explicit grid.

I'm not convinced about the latter. For example, consider

```css
#grid {
  display: grid;
  grid-template-areas: '. .';
  grid-template-columns: 10px;
  grid-auto-columns: 20px;
}
```

If the explicit grid has 2 columns due to `grid-template-areas`, which is the track sizing function of the 2nd one? The spec says that `grid-auto-columns` is only for implicit tracks!

> The grid-auto-rows and grid-auto-columns properties size these implicit grid tracks.

Then https://drafts.csswg.org/css-grid/#propdef-grid-auto-columns seems to redefine implicit tracks in a way that ignores `grid-template-areas`:

> If a grid item is positioned into a row or column that is not explicitly sized by grid-template-rows or grid-template-columns, implicit grid tracks are created to hold it.

I have tested it a bit and it seems that Chromium and Firefox are consistent in this regard:
 - Evidence that extra tracks from `grid-template-areas` are explicit:
   - They are created even if there is no item in them.
   - Extra lines are not considered to have all names in https://drafts.csswg.org/css-grid/#grid-placement-int.
 - Evidence that extra tracks from `grid-template-areas` are implicit:
   - They are sized using `grid-auto-columns/rows`.
   - <del>They are not included in the resolved value of `grid-template-rows`/`grid-template-columns`.</del> [This was reverted due to web compat, now all tracks are included. And not including tracks created with `grid-template-areas` could have been an overlook.]

So maybe we need a middle concept between explicit and implicit, and define things correctly.

**Comment by MatsPalmgren** [comment]
My 2 cents: I suspect it's too late to make changes that affects layout, for web-compat reasons. I think we should update the spec to reflect what UAs are currently doing. IOW, I want all four bullet points above remain true; except perhaps the last one given that we recently changed that and that it only affects CSSOM, not layout.

**Comment by tabatkins** [comment]
The point of distinguishing between "explicit grid" and "implicit grid" is that the explicit grid was, well, explicitly defined: it's the rows and columns that the author explicitly indicated they're planning for.  Under this understading, g-t-a definitely should be considered as defining the explicit grid.  Explicitly *sizing* the tracks isn't required under this definition, however.

So the current situation, while not quite *planned for*, is totally fine in my book, even if we weren't likely already constrained by web compat as Mats says.

So, yeah, we should just fix up the prose around grid-auto-rows/columns to apply to any track that isn't explicitly sized by grid-template-rows/columns.

**Comment by Loirooriol** [comment]
OK, so then a grid can have:
 1. Leading implicit tracks (implicitly sized)
 2. Explicitly sized explicit tracks
 3. Implicitly sized explicit tracks
 4. Trailing implicit tracks (implicitly sized)

**Comment by fantasai** [comment]
Fix checked in. Agenda+ to confirm.

**Comment by fantasai** [comment]
[Quick testcase to show the case under discussion](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3Ediv%20%3E%20div%20%7B%20border%3A%20double%3B%20%7D%3C%2Fstyle%3E%0A%3Cdiv%20style%3D%27display%3A%20grid%3B%20border%3A%20solid%3B%20grid-template-areas%3A%20%22a%22%20%22b%22%20%22c%22%3B%20grid-template-rows%3A%2010px%2010px%3B%20grid-auto-rows%3A%2040px%2020px%27%3E%0A%3Cdiv%3E%3C%2Fdiv%3E%3Cdiv%3E%3C%2Fdiv%3E%3Cdiv%3E%3C%2Fdiv%3E%3Cdiv%3E%3C%2Fdiv%3E%3Cdiv%3E%3C%2Fdiv%3E%3Cdiv%3E%3C%2Fdiv%3E)
````
<!DOCTYPE html>
<style>div > div { border: double; }</style>
<div style='display: grid; border: solid; grid-template-areas: "a" "b" "c"; grid-template-rows: 10px 10px; grid-auto-rows: 40px 20px'>
<div></div><div></div><div></div><div></div><div></div><div></div>
````
