### ISSUE TITLE
[css-color-adjust-1] Is forced color computed or used value?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4915]
Follow-up to https://github.com/w3c/csswg-drafts/issues/4175

We are now computing `background-color` based on the computed 'color' value. (Specifically, we're keying off the computed `color` to find a color, and forcing all but the author’s specified alpha channel to match that color.)

Is this computation at computed-value time or used-value time for `background-color`?

**Comment by tabatkins** [comment]
It has to be at used-value time, due to the system color keywords not resolving until then, right?

**Comment by andruud** [comment]
If the adjusted `background-color` exists computed-value time, it means there are two right answers (/two wrong answers?) for what the computed-value is for `background-color`. The author alpha doesn't exist separately from `background-color`, hence the computed value of `background-color` must be computed to know the author alpha. We shouldn't then suddenly redefine the computed value after it has already been determined the first time. So used-value time seems like a better choice.

**Comment by AmeliaBR** [comment]
It would be a little weird if all the other forced-color effects are available at computed time, but background-color is naively reported without adjustments.

> It has to be at used-value time, due to the system color keywords not resolving until then

Yes, but the other colors at least compute correctly to a system color.

Ideally, we would define the computed value of background-color using one of the Colors Level 5 mixing functions: this system color, but adjusted to use that alpha.

> the computed value of background-color must be computed to know the author alpha. We shouldn't then suddenly redefine the computed value after it has already been determined

This is also true, and trickier to work around.

Logically, we want to treat `background-color` as if it is a shorthand for `background-color-color` and `background-color-alpha`. The author computed `background-color` sets both of these hypothetical longhands, and then the forced user agent style overrides the first but not the second. Using that shorthand/longhand model, the overriding would happen at computed value time.

A comparison would be `font: caption; font-size: 16px`. There is no way to serialize a `font` shorthand representing the combined result without first substituting the expanded value of the system font keyword.

But of course, the difference is that system fonts _are_ substituted at computed time, and they _do_ have longhand properties that can inherit only part of that value. So, I'm not sure we can reuse that model without a serious re-think to all this.

**Comment by svgeesus** [comment]
@tabatkins wrote:

> <TabAtkins> `color-mix(appropriate-system-color, specified-color a(100%))`

[As specified](https://drafts.csswg.org/css-color-5/#color-mix), that will do the [color interpolation(https://drafts.csswg.org/css-color-5/#interpolation) in the LCH colorspace, which is the default. That might not be what is wanted however. I can think of two other options:

`color-mix(appropriate-system-color, specified-color a(100%) srgb)`

That will mix in the (gamma corrected, i.e. non-linear-light) sRGB colorspace, which is what the current implementations do when mixing colors. It gives the wrong (too dark) result but is compatible with lots of software which also does it the wrong way :) It is also constrained to the sRGB gamut, which is temporarily fine but won't be over time as some system colors may be specified in, for example, `display-p3`.

`color-mix(appropriate-system-color, specified-color a(100%) xyz)`

That will get you linear-light mixing, _ie_ the correct result for the physical mixture of two lights, and avoids gamut mapping. It gives the same result as mixing in linear-light sRGB, except without the gamut limitation.

**Comment by tabatkins** [comment]
This might be moot anyway (if it's specified as happening at used-value time, from other issues), but if we do keep with "forced-colors mode causes the computed value to be a color-mix() function", it's *only* mixing alpha (and "mixing" only in a degenerate sense; it's just taking the source color's alpha entirely); the rest of the channels are taken solely from the system color. So the colorspace we mix in is moot.

**Comment by fantasai** [comment]
Given the resolutions to adopt @FremyCompany's proposals in #4915, I would like to re-open this issue (see https://github.com/w3c/csswg-drafts/issues/4178#issuecomment-700481333).

The concept we adopted in #4178 was to treat non-system colors as “out of gamut”, effectively. Mapping out-of-gamut colors is a used-value time operation, not a computed-value time operation. There's an added benefit to making this a used-value time operation: it also makes the question of transitions and interpolation (see #5419) go away. So my proposal is that we go with making this a used-value time operation rather than a computed-value time operation.

Next question is, should we do the same for the other affected properties (which are not color properties) and force their used values to the initial value, instead of their computed values?

**Comment by fantasai** [comment]
Another (important, imho) benefit of forcing colors at used-value time is that they will inherit as the author-specified value, so if a subtree opts out of forced colors, it will use the author-specified colors, not a mix of author-specified and forced colors.

**Comment by alisonmaher** [comment]
I wanted to +1 @fantasai's point in the [above comment](https://github.com/w3c/csswg-drafts/issues/4915#issuecomment-707969753).

In particular, forcing at used-value time will likely be helpful for the following case:
```
<style>
  body {
    color: red;
  }
</style>
<body>
  <svg>
    <rect width="100" height="100" fill="white"/>
    <text x="0" y="15" fill="currentColor">Test</text>
  </svg>
</body>
```

We set `forced-color-adjust: none` on `SVG` elements in Forced Colors Mode. Thus, in the above example, when Forced Colors Mode is enabled to the white-on-black theme, the `SVG` rectangle will remain filled with `white`, but since the text `fill` is set to `currentColor`, it will become unreadable since it will inherit a white forced color from its parent.

If we were to force colors at used-value time, instead, the text fill would pick up `red` and would remain readable in Forced Colors Mode.

So although changing this to used-value time may complicate the implementation a bit, I do think that there is value in changing this to a used-value time operation.

**Comment by piotrekprzychodzen30-web** [comment]
https://github.com/w3c/csswg-drafts/issues/4915
