### ISSUE TITLE
[css-color-adjust-1] Should probably not honor non-url background images

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4916]
We had to do this because too many people complained when we started doing the backplating.

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1617678
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1616440
 * https://bugzilla.mozilla.org/show_bug.cgi?id=1617151

What we implemented is making background-image `revert` unless all the values are `url()` functions:

 * https://searchfox.org/mozilla-central/rev/4ccefc3181f9d237ef4ca8bd17b4e7c101ddf7b5/servo/components/style/properties/cascade.rs#397

But open to other suggestions :-)

**Comment by tabatkins** [comment]
The other reasonable possibility @fantasai and I can come up with is to descend into gradients and adjust all their color-stops the same way as background-color (turning their color channels to match the forced bg color, but leaving their opacity intact).

(If anyone ever implements `stripes()` or `image()`, I suppose they'd need the same treatment.)

**Comment by atanassov** [comment]
Resolved by the WG and PR landed. Closing.
