### ISSUE TITLE
[css-color-adjust-1] Why special-casing background-image for inputs?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#4917]
https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties has a somewhat odd condition:

> Additionally, on on user input controls (except button-like controls) only, background-image.

Two questions:

 * Why special-casing input / textareas? I've never seen a textarea styled with `background-image` so I'm actually surprised that this special-casing is necessary.

 * If it is necessary, that sentence seems a bit ill-defined. Is `<input type=color>` a button-like control? What about `<select>`?

cc @atanassov

**Comment by amaher23** [comment]
@emilio I believe this was a remnant of Legacy Microsoft Edge behavior. I agree that this shouldn't be necessary, especially with the backplate feature, and I would support removing this from the spec.

**Comment by fantasai** [comment]
> Why special-casing input / textareas?

We inherited this from Microsoft's definition, so that's a question for @atanassov and @melanierichards  :)

> If it is necessary, that sentence seems a bit ill-defined. Is <input type=color> a button-like control? What about <select>?

It's ill-defined because appropriate behavior can vary by platform. CSS/HTML doesn't define what controls "look like" buttons, but that's intended the criteria here...

**Comment by atanassov** [comment]
We actually don't need this behavior given that the backplate is now covering all of these scenarios. I recommend removing the text from the spec and closing this issue.

**Comment by alisonmaher** [comment]
Resolved by the WG and PR landed. Closing.
