### ISSUE TITLE
[css-writing-modes] addition of "writing-mode:upright-tb;" and "text-orientation: upwards;"

### ISSUE THREAD

**Issue by gminky** [w3c/csswg-drafts#4921]
Hello.
I want to propose about new value"upright-tb"(Top-to-bottom block flow direction. The writing mode is horizontal, while the typographic mode is vertical.) for "writing-mode."

Because, these are used in Japanese 法律(national law) and 省令(ministarial ordinance), and  都道府県/市町村条例(municipality's / prefectural ordinance).
<img src="https://user-images.githubusercontent.com/52011692/80130665-ec767000-85d3-11ea-8d20-825ecb56d403.png" width="50%">

So, I think there are some needs to adopt this.

Therefore, I think upright should be defined as "glyph-top=inline-start", sideways  should be defined as "glyph-top≠inline-start".
Thank you.

<img src="https://user-images.githubusercontent.com/52011692/80286156-b9171b00-8764-11ea-9a1c-aae82b003953.png" width="50%">

* [example](https://github.com/w3c/csswg-drafts/files/4533745/DisplayServlet.pdf) for "writing-mode: horizontal-tb;" [a](https://twitter.com/gminky_/status/1247151848458313731), [b](https://twitter.com/gminky_/status/1247152683011604481), [c](https://twitter.com/gminky_/status/1247153377034698752), [d](https://twitter.com/gminky_/status/1247153826076831747), [e](https://twitter.com/gminky_/status/1247154614203346946), [f](https://twitter.com/gminky_/status/1247155668626202630), [g](https://twitter.com/gminky_/status/1247156469125898242), [h](https://twitter.com/gminky_/status/1247159131338756096) (blue.), [i](https://twitter.com/gminky_/status/1254091286006517761)
* example for "HORIZONTAL-IN-VERTICAL TEXT" in upright-tb [a](https://twitter.com/gminky_/status/1247155668626202630/photo/2) [b](https://twitter.com/gminky_/status/1247155668626202630/photo/4) (picture in same tweet, green.)

* [CSS Writing Modes 4･writing-mode](https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode)
* [Styling vertical Chinese, Japanese, Korean and Mongolian text](https://www.w3.org/International/articles/vertical-text/#tcy)
* Case in MS Word. 
1st case=horizontal-tb; 2nd case=vertical-rl; 3rd case=sideways-rl; 5th case=upright-tb;
<img src="https://user-images.githubusercontent.com/52011692/80130012-eb910e80-85d2-11ea-8415-1d94b6e2284a.png" width="40%">
<img src="https://user-images.githubusercontent.com/52011692/83725418-df41ac00-a67c-11ea-9339-14b661eb005a.png" width="40%">

**Comment by upsuper** [comment]
I'm not convinced.

That example of `upright-tb` looks like `vertical-rl` with the whole area rotated, and it seems to be just for fixed layout like paper where the width and height is given, and thus it should be easily achievable with combination of existing properties.

Given the complexity of implementing writing modes in engines (that you need to make a whole bunch of calculations work), I don't think it makes sense to do this in the writing mode level.

**Comment by gminky** [comment]
Thank you for your comment.
How about this case?
![image](https://user-images.githubusercontent.com/52011692/81780548-a6a52b80-9531-11ea-9265-dd6154b4c099.png)

**Comment by upsuper** [comment]
This example totally blows my mind...

This case would not work under the writing mode model either, because you can't mix different writing modes in the text flow. This has been made clear in the level 3 [spec](https://drafts.csswg.org/css-writing-modes-3/#block-flow):
> If a box has a different writing-mode value than its parent box (i.e. nearest ancestor without display: contents):
> * If the box would otherwise become an in-flow box with a computed `display` of `inline`, its `display` computes instead to `inline-block`.
> * If the box is a block container, then it establishes an independent block formatting context.
> * More generally, if its specified inner display type is `flow`, then its computed inner display type becomes `flow-root`.

However, I think it's probably achievable via extending `text-orientation` to support rotating characters in horizontal writing modes. With that you would be able to do things like this.

**Comment by gminky** [comment]
@upsuper 
Thank you so mach.

So, you mean like this↓?

`<div style="writing-mode: vertical-rl;"><p>別記様式第１号中「<span style="text-orientation: upwards;">又はかきく</span>」を「<span style="text-orientation: upwards;">、かきく</span>」に改める。</p></div>`

**Comment by gminky** [comment]
[A part of "Manual of Legal work" of Hiroshima Prefecture](https://twitter.com/gminky_/status/1268210069163794443).

**Comment by frivoal** [comment]
It feels like this would be some kind of `text-orientation: forced-sideways` inside of `writing-mode: horizontal-tb`. But I'm kind of scared about the details of how that'd work. Is it identical to what text-orientation: upright` inside of `writing-mode: vertical-rl` would look, just rotated 90 degrees? For Kanji / kana, that seems to be the case, but how about punctuation? A vertical opening parenthesis rotated 90 degrees doesn't necessarily look the same as a horizontal parenthesis. Which of the two would we want? What does this do to non-Japanese text? Is there any interraction with bidi? Anything odd happening if you start putting text-decoration, text-emphasis, or ruby on these things?

**Comment by gminky** [comment]
>Is it identical to what `text-orientation: upright` inside of `writing-mode: vertical-rl` would look, just rotated 90 degrees?
Yes. And Same at `Rotate Asian characters 270°` in MS Word.

↓　In MS Word case.
>punctuation
![image](https://user-images.githubusercontent.com/52011692/83722574-3002d600-a678-11ea-98ef-1c7f1527b073.png)

>text-decoration, text-emphasis
![image](https://user-images.githubusercontent.com/52011692/83722852-a8699700-a678-11ea-85e3-57e8ab536f60.png)
![image](https://user-images.githubusercontent.com/52011692/83723236-54ab7d80-a679-11ea-848b-888c5387b030.png)

>ruby
![image](https://user-images.githubusercontent.com/52011692/83723122-1ca43a80-a679-11ea-990c-3890f3ce651c.png)

**Comment by gminky** [comment]
![image](https://user-images.githubusercontent.com/52011692/85545050-8ac79600-b656-11ea-9bec-291dc38e7a94.png)
from [Osaka's Official document](https://commons.wikimedia.org/wiki/File:%E6%9D%A1%E4%BE%8B%E3%80%81%E8%A6%8F%E5%89%87%E3%81%AE%E6%94%B9%E6%AD%A3%E6%96%B9%E5%BC%8F%E3%81%AE%E6%96%B0%E6%97%A7%E5%AF%BE%E7%85%A7%E8%A1%A8%E6%96%B9%E5%BC%8F%E3%81%B8%E3%81%AE%E5%A4%89%E6%9B%B4%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%EF%BC%88%E5%B9%B3%E6%88%9022%E5%B9%B4%EF%BC%97%E6%9C%88%EF%BC%91%E6%97%A5%E5%A4%A7%E9%98%AA%E5%BA%9C%E7%B7%8F%E5%8B%99%E9%83%A8%EF%BC%89.pdf)

**Comment by macnmm** [comment]
I guess if your view of the world is that boxes are always upright, and the lines and characters within them have to use line layout-level selectors to orient themselves, then adding a writing mode may make sense. However, implementers would want all the rules of vertical typography and this example to be shared, so to do so we would rotate the port and just do vertical layout therein as normal.
I see this example as a rotated frame, not as individually distinct lines that happen to be horizontal with rotated characters...

**Comment by frivoal** [comment]
As https://user-images.githubusercontent.com/52011692/81780548-a6a52b80-9531-11ea-9265-dd6154b4c099.png shows, it isn't just a trick to rotate the entire page (if it were, we could have dealt with it using https://drafts.csswg.org/css-page-3/#page-orientation-prop)

I guess one of the questions this raises, and for which the Japanese government likely provides no guidance, is what happens if you throw Arabic in there: do you get the same effect as if it was set with vertical-rl / upright, rotated, or do you get normal horizontal rtl arabic, and therefore bidi. I suspect that if we do it using `text-orientation: forced-sideways`, then you'd likely get the former, but since `text-orientation` applies to inlines, you could set different values on different runs of text, and get the later.

**Comment by gminky** [comment]
I think the problems of `writing-mode: upright-tb;` or `text-orientation: upwards;` is already fixed in MS Word and we can refer it.

**Comment by gminky** [comment]
By the way, I wonder why `sideways-rl` is adopted.

**Comment by himorin** [comment]
> I guess one of the questions this raises, and for which the Japanese government likely provides no guidance, is what happens if you throw Arabic in there: do you get the same effect as if it was set with vertical-rl / upright, rotated, or do you get normal horizontal rtl arabic, and therefore bidi. I suspect that if we do it using `text-orientation: forced-sideways`, then you'd likely get the former, but since `text-orientation` applies to inlines, you could set different values on different runs of text, and get the later.

some examples: p26 of https://www.soumu.go.jp/main_content/000688866.pdf, or p2 of https://www.soumu.go.jp/main_content/000675267.pdf
(also refer thread at https://github.com/w3c/jlreq/issues/214...)
