### ISSUE TITLE
[css-images-4] Undefined Hue angle when interpolating from neutrals

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#4928]
_Edit:_ skip [to here](https://github.com/w3c/csswg-drafts/issues/4928#issuecomment-912920699) to see the interaction with gradient stop interpolation

[Noticed by Mike Bostock](https://observablehq.com/d/3cef25e76ec972cf) in the context of D3, but applicable to the color modification functions in Color5, too:

> When you interpolate two colors in HCL colorspace, if one of the colors has undefined chroma or hue, the interpolator uses the chroma or hue from the opposite color. This can sometimes result in out-of-gamut colors that cannot be displayed in RGB colorspace. You may therefore wish to use Lab colorspace instead, or to specify the chroma explicitly to disable inheritance.

There are [lots of helpful examples](https://observablehq.com/d/3cef25e76ec972cf)

**Comment by danburzo** [comment]
When interpolating a color whose hue is undefined with a color with a defined hue, it works well for the undefined hue to be considered equal to the defined one. 

A `lab(L 0 0)` color (equivalent to the deprecated `gray()` syntax) will produce `lch(L 0 0)`. When a color authored in a different color space is converted to `lch()` and its chroma ends up 0, it's fair to consider its hue undefined, to enable the behavior above. However, when authored in `lch()` directly, a color with zero chroma (e.g. `lch(50 0 0)`) I guess we should honor the explicit hue?

**Comment by danburzo** [comment]
Hmm, I haven't fully fleshed out the idea, but could we do a _chroma premultiplication_ (for `lch()`) or _saturation premultiplication_ (for `hsl()`) similar to an _alpha premultiplication_? That would make colors with a small chroma component conntribute less of their hue to the interpolation and might satisfy @tabatkins [math requirements](https://github.com/w3c/csswg-drafts/issues/4647#issuecomment-624790084)?

I'll try a demo to see if it pans out.

**Comment by danburzo** [comment]
I've made an [interactive notebook](https://observablehq.com/@danburzo/chroma-premultiplication) to try it out. It works surprisingly well! It handles graciously and continuously zero, and near-zero, chroma:

<img width="893" alt="Screenshot 2020-07-14 at 15 02 12" src="https://user-images.githubusercontent.com/205375/87423521-1fcd0780-c5e3-11ea-86bc-8be9dc86b122.png">

But it's arguably not the "correct" interpolation with noticeably large chroma:

<img width="911" alt="Screenshot 2020-07-14 at 15 02 44" src="https://user-images.githubusercontent.com/205375/87423533-265b7f00-c5e3-11ea-9774-cf7aadaf4238.png">

**Comment by svgeesus** [comment]
> But it's arguably not the "correct" interpolation with noticeably large chroma

That was my conclusion also. A smooth transition away from the `NaN` fixup works for the "almost zero chroma" case at the expense of making all the small to large chroma values result in non-perceptually-uniform hue ramps. An abrupt transition is awkward. Maybe a fast transition where the chroma is still in the "very tiny but not zero" range?

**Comment by svgeesus** [comment]
Currently, the [spec says]()

> If one of the angles has the value NaN, then for interpolation, NaN is replaced by the value of the other hue angle. If both angles have the value NaN, then for interpolation, NaN is replaced by the value 0 for both angles.

(we already have [Achromatic colors converted to hue-ish spaces should treat hue as "missing", not NaN]( https://github.com/w3c/csswg-drafts/issues/6107) so don't focus on the specific `NaN` or `missing`)

This avoids the area of not-really-perceptually-uniform by making the cutoff between "has a defined hue" and "achromatic" very close to the achromatic axis, so we et well defined behavior in all cases.

Is that sufficient, or is more needed?

**Comment by danburzo** [comment]
I think for the scope of `css-color-4` that note is sufficient. (Since it appears the `longer` hue interpolation leaves identical angles untouched, I don't see any possible interactions between hue fixup and `NaN` hues).

In the context of `css-images`, I assume for gradients this adjustment is made on a piecewise basis. So the `#888` in `linear-gradient(red, #888, green)` gets `red`'s hue on the first segment and `green`'s hue on the second.

**Comment by svgeesus** [comment]
Thanks for the confirmation regarding css color 4.

Re-tagging to css images and leaving open, so we don't forget

**Comment by svgeesus** [comment]
@danburzo wrote:

> In the context of `css-images`, I assume for gradients this adjustment is made on a piecewise basis.

Yes, and the spec now says so explicitly.

> So the `#888` in `linear-gradient(red, #888, green)` gets `red`'s hue on the first segment and `green`'s hue on the second, if the interpolation happens in a cylindrical polar space.

I have just added that exact example to CSS Images 4.
