### ISSUE TITLE
[media-queries-level-5]: Docs for where custom MQs ended up

### ISSUE THREAD

**Issue by kevinSuttle** [w3c/csswg-drafts#493]
- please tag the issue title with the spec's shortname, like `[css-foo]`
- please link to the spec section you're talking about, or at least the spec
  https://drafts.csswg.org/mediaqueries/

https://lists.w3.org/Archives/Public/www-style/2016Jun/0158.html

> - RESOLVED: Move custom MQ to level 5 (issue #9).
> 
> Issue # 9
> 
> Rossen: Issue # 9
>  fantasai: This one isn't 100% baked so defer it to level 5.
>  Florian: I'm okay with it. I think TabAtkins intended to move to
>            houdini?
>  TabAtkins: We'll move it where it needs to be. Doesn't matter.
>  Rossen: Objections to move custom MQ to level 5?
> 
>  RESOLVED: Move custom MQ to level 5 (issue #9).

Doesn't appear here: 
https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Amediaqueries-5

**Comment by frivoal** [comment]
It's here now: https://drafts.csswg.org/mediaqueries-5/
