### ISSUE TITLE
[CSS-localMemory-rule] CSS needs rule references to localMemory values, to be responsive to user input.

### ISSUE THREAD

**Issue by Dorson** [w3c/csswg-drafts#4933]
[css-localMemory-rule]

CSS needs to be able to set style rules in reference to the values that were saved in the localMemory of the browser. Like for color settings, or text size settings, or position settings.

_Here is an example to understand why._

CSS rule example for the user-set color preferences.
Similar as we do in the attribute selector rules :
```
html[localMemory( ColorTheme == dark )] { background: black ; }
..or...
html[localMemory( ColorTheme == green )] { background: green ; }
```

OR as we do in the media rules :

```
@localMemory( ColorTheme == dark ) {
      body { background: black ;  }
}
```

Such rules would be able to set the black background for the html tag, if the LocalMemory cell list of ColorTheme had the "dark" entry value in the list.

The read-only access to the localMemory of the browser would make the CSS truly dynamic and responsive to the user input. Users apps would be able allow to set and remember the personal style settings. Positions of the movable page elements would be possible to be remembered, if the user wanted to do so.

The write access changes should be still left to the JavaScript side.

**Good Day fellow travelers !**

**Comment by emilio** [comment]
I assume `localMemory` means `localStorage`?

**Comment by tabatkins** [comment]
This should be addressed when we add custom media queries; on page load you can query `localStorage` yourself and set the MQs accordingly.

It wouldn't be appropriate for CSS to directly interface with `localStorage`; that is one of *many* ways to store local state in a page. (And in general, one of the less good ones, due to it providing sync access to a potentially-slow storage backend.)

**Comment by Dorson** [comment]
Yes, CSS should directly interface with localStorage values OR similar, alternative settings memory, **because user style settings are set in there.**  Read-only access is OK for that.


It's the job of the CSS to comply with the style rules that the user selected and saved.

In the current state, we are left to use the JavaScript to do the job of the CSS, when we need to remember and set the same CSS class rules for user preferences, and set them again on every page load by JavaScript, instead of directly making style rules that refer to the  localStorage values for the user style settings.


It's NOT about the  localStorage  itself. Could be any other memory storage. It's about the access to style setting values that were made by the user.
