### ISSUE TITLE
[css-contain] Add contain-paint-margin CSS property

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#4934]
As mentioned in wicg/display-locking#147, the addition of `contain:paint` to `subtree-visibility:auto` elements constrains use of ink overflow to the border box of the element. This is good for avoiding flicker and limiting raster costs, but makes it difficult or awkward for developers to support content that has legitimate ink overflow.

This can be fixed by a new `contain-paint-margin` CSS property that allows the `contain:paint` clip to be expanded by a fixed amount. Syntax:

```contain-paint-margin: none | <width height>```

Here width and height are positive, physical lengths. `none` has the same effect as `0px 0px`.

Even in cases where a developer is not using `subtree-visibility` but wishes to apply `contain:paint`, this property will still be useful as a way to allow a fixed amount of ink overflow.

**Comment by frivoal** [comment]
I'm confused. If you allow ink overflow to escape, even by some known distance, how can you still do the optimizations enabled by the fact that contain:overflow usually allows nothing to escape? Alternatively, if you're not interested in the optimizations, why are you using contain:paint ?

**Comment by chrishtr** [comment]
> If you allow ink overflow to escape, even by some known distance, how can you still do the optimizations enabled by the fact that contain:overflow usually allows nothing to escape?

`contain:paint` on an element allows the browser to be sure that nothing in the painted subtree of the element exceeds that element's border box. This can be use to optimized away/schedule raster and related rendering work when the element is scrolled offscreen.

Expanding the border box by a fixed, and known-to-the-browser amount, still allows such optimizations to apply, but the browser just needs to account for the additional space. The same optimizations can still apply. It's just a somewhat bigger raster area.

**Comment by smfr** [comment]
Does this property ever cause things to be clipped when they weren't before, or is it just advisory? For example, does a box with `contain-paint-margin: 20px; box-shadow: 0 0 50px black` get a clipped shadow?

**Comment by chrishtr** [comment]
@smfr it would not receive a clip in that case. The clip would only apply if `contain:paint` or `overflow:clip` were present.

**Comment by frivoal** [comment]
Right. It's not a "please clip" property, it's a "if you would clip, please do so a bit further out" property.

An interesting question is whether it should apply to clip path or not. If it does, It probably should do so in a way that is similar to how shape-margin affects: take a single, possibly negative, value.

If we keep it to just contain:paint and overflow:clip, supporting 1 to 4 values to be able to differentiate between top / bottom/ left / right seems more useful, but I don't think that'd be possible to extend to clip-path.

As for negative values, I/we said during the call that there probably was no use for them, and therefore we should reject them. Actually, I'm not sure: if you know your box as 20px worth of blank padding on all sides in which nothing will ever intrude, you might want to clip to that using a negative clip-margin, which would allow the browser to skip repainting even if some of the element is on screen, as long as it's not more than those 20px.

**Comment by AmeliaBR** [comment]
> An interesting question is whether it should apply to clip path or not.

I would strongly argue no. The geometric nature of the clipping is too different. We can leave open the possibility of a `clip-path-margin` in the future if a need ever arises, but for now the most important thing is to make sure that the name of _this_ property is clear that it doesn't affect `clip-path` clipping.

Based on the agreement in the call, I'd lean towards the name `overflow-margin` (although that might be confused for something that affects scrolling), `overflow-paint-margin`, or `overflow-clip-margin`. Focusing on overflow emphasizes that this is about clipping the child content, not the painting of this element itself. (If _we_ were all confused about that, other people are going to be confused about it.) Another option would be to name it `content-paint-margin` to match with the `content-visibility` name we chose in #4843 .

**Comment by chrishtr** [comment]
Update on rounded corners: a question was raised during the call yesterday about whether the clip must take into account rounded corners. In the call we said no. Turns out `contain:paint` does [require taking into account corner clipping](https://drafts.csswg.org/css-contain-2/#containment-paint), which makes sense because its clipping behavior is defined to be equivalent to `overflow:clip`.

Chromium and Gecko both implement this behavior for `contain:paint`. Example [here](https://codepen.io/chrishtr/pen/gOaeKQW).

I don't think there will be any significant problem implementing clipping behavior, at least in Chromium there will not. We already implement all of the complexities of these rounded corners, up to and including GPU-composited code paths.

I think the right behavior is to apply the margin before applying the algorithms of [clipping behavior](https://drafts.csswg.org/css-backgrounds-3/#corners). Otherwise I think it would be hard to reason about for developers. Therefore in the example I linked above, if a margin of 20px was applied, the resulting clip shape would be a circle of diameter 140px; it's a circle because the example has `border-radius: 50%`.

**Comment by chrishtr** [comment]
I like the suggestion of `overflow-clip-margin`. This makes it clear that it has to do with the overflow clip.

**Comment by frivoal** [comment]
That all makes sense to me.

What do you think about the questions I asked in https://github.com/w3c/csswg-drafts/issues/4934#issuecomment-625694061 about negative values and about longhands?

**Comment by chrishtr** [comment]
> What do you think about the questions I asked in [#4934 (comment)](https://github.com/w3c/csswg-drafts/issues/4934#issuecomment-625694061) about negative values and about longhands?

The longhands you mentioned sounds fine. AIUI you're proposing it have the same longhands as the `margin` CSS property right? That was what was part of the resolution last week I think.

For negative values: sure, sounds fine to me. `margin` has them also, so why not. I can't think of a way this would make the implementation much harder either.

**Comment by AmeliaBR** [comment]
I think negative values are problematic, since that could mean clipping the scrollbar on scrollable content. (For the `contain-paint` case, which works with `overflow: auto`/`scroll`.) Also, the use cases I can think of are graphical effects rather than performance optimizations, so it's not really consistent with the intent of the property.

I also agree with following the `margin` syntax. I'm not sure that it's necessary (vs having a single value for all directions), but it's clear & consistent.

**Comment by fantasai** [comment]
I would suggest we start off with a single value here. If we need to split it out, we can do it later. But that's 8 longhands for a single property... I'm not sure that we really need that much control in this case. If it's requested in the future we can split it out.

I think `overflow-margin` is fine. We don't need to make it longer imho: overflow is about contents that overflow the box, which is what we're talking about here.

**Comment by chrishtr** [comment]
I would be fine with the single value for now, agree the complexity is not justified until there is a known use case.

Re `overflow-margin`: the problem is that we don't want it to apply to values of `overflow` other than `clip`, to avoid excessive complexity relating to scrolling, scrollbars, layout overflow and so on. `overflow-clip-margin` communicates that restriction more clearly.

**Comment by frivoal** [comment]
For negative margins, I'm convinced by the argument that this would make interaction with scrollbars needlessly complicated.

So, as far as I can tell, the current consensus-in-progress is that:
- it's called either `overflow-margin` or `overflow-clip-margin`
- it takes a single value, and doesn't have longhands (but could be expanded later if need be)
- negative values are invalid
- it does not add a margin to clip-path
- it does take rounder corners into account, to avoid a discontinuity between `overflow-clip-margin: 0` and `overflow-clip-margin: 1px`

**Comment by chrishtr** [comment]
> So, as far as I can tell, the current consensus-in-progress is that:

Agreed.

**Comment by frivoal** [comment]
Reopening, as I think @tabatkins' edits don't quite nail it.
Fixes I've done already:
* Define negative values to be invalid (in prose and using the range syntax)
* Move the description of the interaction between paint-overflow and overflow-clip-margin from css-contain L1 to L2 (L1 is at REC already, and doesn't need to define interaction with features introduced after it)

Things I haven't done yet, but think we should consider:
* The current way this is set up in spec terms is awkward, due to action at a distance: overflow-clip and paint containment are defined in terms of the padding edge, which is not defined to be affected by oveflow-clip-margin. Then overflow-clip-margin says it changes where these properties apply, and paint containment (but not overflow-clip) has an extra bit of text that contradicts the earlier statement that we clip at the padding edge, and says we clip further out taking overflow-clip-margin into account. Instead of doing this, I suggest:
  - defining a new term, like `overflow clip edge`
  - defining `overflow-clip` and `paint overflow` to clip at the `overflow clip edge`, instead of the `padding edge`
  - define how `overflow-clip-margin` makes the `overflow clip edge` expand outwards from the `padding edge`

**Comment by frivoal** [comment]
See https://github.com/w3c/csswg-drafts/pull/5134 for an attempt at doing what I suggested in the previous comment.

**Comment by tabatkins** [comment]
> Define negative values to be invalid (in prose and using the range syntax)

Whoops, sorry about that.

> Move the description of the interaction between paint overflow and overflow-clip-margin from css-contain L1 to L2 

👍 

> The current way this is set up in spec terms is awkward

My assumption was that interactions in the same spec have a low enough "distance" that the action is fine, but I'm fine with making things more explicit as well.

**Comment by tabatkins** [comment]
Merged #5134, so I'll go ahead and re-close. Thanks for the review, @frivoal!
