### ISSUE TITLE
[css-grid] Is `span` keyword excluded from Named Grid Lines <custom-ident>?

### ISSUE THREAD

**Issue by tomalec** [w3c/csswg-drafts#494]
The ["7.2.1. Named Grid Lines" Section](https://drafts.csswg.org/css-grid/#named-lines) defines the syntax as just 
>`[<custom-ident>*]`

Where [CSS Values for `<custom-ident>` says](https://drafts.csswg.org/css-values-4/#custom-idents)
>  Specifications using `<custom-ident>` must specify clearly what other keywords are excluded from `<custom-ident>`, if any

I would assume that `span` should be excluded not to collide with [Line-based placement properties](https://drafts.csswg.org/css-grid/#line-placement)

Am I correct?

**Comment by tomalec** [comment]
Or are following valid? 
```css
grid-row: span; 
grid-column-end: span span 2;
```

**Comment by mrego** [comment]
I believe this is already covered at the end of the section:
> In all the above productions, the <custom-ident> additionally excludes the keyword span.

**Comment by tomalec** [comment]
Wow, that's it, but I didn't and wouldn't expect to see the explanation that far (7.2->9.3). 

Per _exceptio probat regulam_, should I assume that all following occurrences of `<custom-ident>` (for example in 9.4) could potential contain `span` (it's not say they cannot) or are they just references to this specific instance of `<custom-ident>` that could not.

If the latter why can we cay that for in all cases `<custom-ident>` excludes `span` and if we say so I would rather provide such exception where we introduce it for the first time, not somewhere in the middle.

**Comment by tomalec** [comment]
My bad, sorry, It was mentioned closer, in 7.2.
> In `<line-names>`, the `<custom-ident>` additionally excludes the keyword `span`

But maybe to avoid such confusion, and changing/adding a meaning retrospectively by ."In all the above productions". We could use just (already specified) `<line-names>` (for all `<custom-ident>` excluding the keyword span).

(Note, I'm willing to prepare PR if needed ;) )

**Comment by MatsPalmgren** [comment]
I think this general clause in [css-values] applies:
https://www.w3.org/TR/css3-values/#custom-idents
> represents any valid CSS identifier that would not be misinterpreted as a pre-defined keyword in that property’s value definition

**Comment by mrego** [comment]
A few lines later the [css-values] spec says:
> Specifications using <custom-ident> must specify clearly what other keywords are excluded from <custom-ident>, if any—for example by saying that any pre-defined keywords in that property’s value definition are excluded.

BTW, I remember [a thread about this topic](https://lists.w3.org/Archives/Public/www-style/2016Mar/0247.html).

**Comment by fantasai** [comment]
> A few lines later the [css-values] spec says:

Which is a conformance criterium on specs, not on implementations. ;)

We can't use `<<line-names>>` in place of `<<custom-ident>>` in section 9 because it includes the surrounding brackets, which aren't included as part of the value syntax in `grid-area` and its longhands. 

I tweaked the wording of the statement a bit and move it into the line names section, let me know if that helps.

**Comment by tomalec** [comment]
Thanks :)
