### ISSUE TITLE
[css-flexbox][maybe others] Layout algo is too specific about sizing of the container

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#4956]
The [flexbox layout algo](https://drafts.csswg.org/css-flexbox/#layout-algorithm) has *very specific rules* for determining the main (step 4) and cross (step 15) size of the flex container.

But these rules are wrong! Step 4 is handwavey (which @SimonSapin has complained about in the past) and Step 15 is overly specific and would prevent, say, a flex container that is a grid item from getting stretched (I think?)

What we want to instead do is define a "content size" (which step 4 and 15 do admirably), and then defer to a generic algo shared by all (maybe not Table?) layout modes that sizes the container based on its content size.

This "content size" is also the size of the "alignment subject" for content alignment (the align-content/etc properties).

**Comment by SimonSapin** [comment]
> (which @SimonSapin has complained about in the past)

I assume you mean https://github.com/w3c/csswg-drafts/issues/4905. When discussing this with @dholbert and @emilio we concluded that `block-size: auto` for block boxes is effectively `block-size: max-content`. So it might be good to rely on css-sizing’s existing definitions.

**Comment by tabatkins** [comment]
Looks like we just addressed this issues today, while fixing other issues from @SimonSapin. ^_^
