### ISSUE TITLE
[css-sizing-3][css-images-3] Distinguish intrinsic size's two definitions with two terms

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4961]
We have used the term “intrinsic size” to refer to two slightly different concepts (that overlap) in our spec:
- the inherent size of a replaced element (which sometimes exists)
- min-content and max-content sizes (which always exist, and are derived from the content)

We need to have separate terms for these so there's no confusion.

**Comment by fantasai** [comment]
Related discussion https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263

**Comment by SimonSapin** [comment]
In Servo code we’ve been using "intrinsic sizes" for the optional width, optional height, and optional ratio inherent to replaced elements, and "content sizes" for `min-content` and `max-content` (per the term used in those keywords). I’m not super happy with the latter since it’s easy to confuse with the (computed or used) size of the content area https://drafts.csswg.org/css2/box.html#box-content-area

**Comment by fantasai** [comment]
HTML spec seems to use the term “natural width” and “natural height” for the first concept https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

So maybe “natural size” for the intrinsic size of replaced elements and “intrinsic size”for the content-based sizes?
A few other options from the thesaurus include “inherent”, “innate”, “essential”, and “inbuilt”. Maybe “inbuilt” since we're talking about sizing information built into the replaced element...?

**Comment by rachelandrew** [comment]
I think I've been using natural size when describing replaced elements, certainly when teaching in person/online. "The natural size of the image ..." referring to the actual dimensions of the the thing. It may be that came from reading the HTML spec at some point if that is how they are described there. So I'd agree with @fantasai to use natural size for replaced elements and intrinsic size for content.

**Comment by SimonSapin** [comment]
Natural size sounds good to me, and consistency with HTML seems worthwhile.

HTML defines natural size as [density-corrected](https://html.spec.whatwg.org/multipage/images.html#density-corrected-intrinsic-width-and-height). I *think* we want that.

> When an img element has a current pixel density that is not 1.0, the element's image data must be treated as if its resolution, in device pixels per CSS pixels, was the current pixel density. The image's density-corrected intrinsic width and height are the [intrinsic width and height](https://drafts.csswg.org/css-images/#intrinsic-dimensions) after taking into account the current pixel density.

This is based on a css-images definition, so changing that may require coordination with HTML.

The density in question is [from `srcset`](https://html.spec.whatwg.org/multipage/images.html#pixel-density-descriptor) (through [update image data](https://html.spec.whatwg.org/multipage/images.html#updating-the-image-data:current-pixel-density) and [select an image source](https://html.spec.whatwg.org/multipage/images.html#select-an-image-source) algorithms).

**Comment by fantasai** [comment]
Tab and I made the edits for this today. Will need to republish css-images-3 so that other TR specs can cross-link to it correctly.
