### ISSUE TITLE
[writing-modes] Boustrophedon

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#4966]
I wonder if this bidi behavior is worth adding facilities for in CSS: https://en.wikipedia.org/wiki/Boustrophedon. Alternate lines have horizontally reversed characters, so the flow of reading flows back and forth across the page. It's sort of like specifying `<bdo>` on every other line.

(It's low priority, but maybe worth considering?)

**Comment by Crissov** [comment]
It has been mentioned before, but was not considered worthy of addition at the time. 

- [2016 Nov](https://lists.w3.org/Archives/Public/www-style/2016Nov/0031.html)
- [2004 May](https://lists.w3.org/Archives/Public/www-style/2004May/0350.html) 
- [2001 Feb](https://lists.w3.org/Archives/Public/www-style/2001Feb/0086.html) 

Historically, there have been variants with non-mirrored, horizontally mirrored, vertically and horizontally mirrored glyphs.

**Comment by tabatkins** [comment]
Yeah, since its usage is purely historical, with no living language using it, it hasn't been considered worth puzzling out the difficulties, and spending time speccing/implementing/testing it.

**Comment by AmeliaBR** [comment]
It would be a very interesting case study for early experiments with a Houdini inline text layout module, though… (e.g., as discussed in https://github.com/w3c/css-houdini-drafts/issues/854)

**Comment by fantasai** [comment]
Thanks for digging up the history, @Crissov  :)

Closing out based on previous CSSWG decisions. @litherum Please re-open and tag against css-writing-modes-5 if you think this is actually worth spending time on.
