### ISSUE TITLE
[css-ruby] Does line-height have an effect on any of the ruby boxes?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4979]
[Section 3.5 of the css-ruby spec](https://drafts.csswg.org/css-ruby-1/#line-height) talks about the effect `line-height` on a ruby container has on the line in which it is. That makes sense, and that should stay.

The same implies, without really saying so, that `line-height` on the ruby container has no effects on the inside layout of the ruby container. I think we should define it to have no such effect.

Also, no other part of the spec talks about the applicability of `line-height` onto any of the internal ruby boxes (ruby bases, ruby annotations, ruby base containers, ruby annotation containers). I think we should define it not to apply.

Reasoning for `line-height` having no effects on anything inside the ruby layout:
* The various kinds of ruby boxes are to varying degrees analogous to inline boxes, and `line-height` has no effect on the inside of an inline box (only on the size of the line around it, which is why it's also kept as having an effect on the outside of ruby containers).
* It's simpler
* It's not necessary
* That's the way Firefox implements it

**Comment by yisibl** [comment]
I'm confused. Why does line-height not work in ruby? It will be difficult to get the `<rb>` centered vertically within the border.

![image](https://github.com/w3c/csswg-drafts/assets/2784308/f7eb3901-f2bd-4bdd-9073-307fe89635b8)


```html
  <ruby>
    <rb>李</rb>
    <rt>lǐ</rt>
  </ruby>

<style>
rb {
  width: 1.25ic;
  height: 1.25ic;
  line-height: 1.25ic;
  text-align: center;
  border: 1px solid red;
}
</style>
```
