### ISSUE TITLE
[css-display-3] Should it be 'display: contents' here?

### ISSUE THREAD

**Issue by Jiang-Xuan** [w3c/csswg-drafts#4990]
![image](https://user-images.githubusercontent.com/13357301/80049270-fe5d0200-8544-11ea-8f35-e8d0e2d40390.png)

https://www.w3.org/TR/2019/CR-css-display-3-20190711/#box-generation

Should it be 'display: contents' here? 🧐

**Comment by Jiang-Xuan** [comment]
@fantasai

**Comment by Loirooriol** [comment]
No, it's `display: none`. Since the rendering is not entirely controlled by CSS, you can't just replace the element with its contents.

**Comment by Jiang-Xuan** [comment]
@Loirooriol thank you 🙏, I understand
