### ISSUE TITLE
[css-text-3] Should enclosed counting rods / tai xuan jing / yi jing hexagrams be space-discarding? 

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#4993]
In #337 we decided to key line-break transformation behavior by Unicode Block. Most of the blocks are pretty straightforward: Han, Kana, Yi, and CJK punctuation blokcs discard, and everything else converts to a space. But there are a few interesting cases...

One interesting case are some symbols that seem to originate primarily in CJK usage:
https://en.wikipedia.org/wiki/Yijing_Hexagram_Symbols_(Unicode_block)
https://en.wikipedia.org/wiki/Taixuanjing
https://en.wikipedia.org/wiki/Counting_Rod_Numerals_(Unicode_block)

Our intent is to discard if it's safe to do so (Chinese / Japanese context) but not otherwise (Korean, English, etc.). Note that we only discard if both sides (before and after) the line break are part of the space-discarding character set.

What should we do with these blocks?

**Comment by kojiishi** [comment]
From the example pictures submitted to Unicode, none of them use spaces to delimit words, so I prefer to include, but I'm fine not to if others think so.

**Comment by dscorbett** [comment]
Is it worth keeping the hexagrams’ behavior consistent with the monograms’ and trigrams’ in Miscellaneous Symbols?

**Comment by r12a** [comment]
> discard if it's safe to do so (Chinese / Japanese context) but not otherwise (Korean, English, etc.).

I wasn't able to find the text in https://drafts.csswg.org/css-text-3/#line-break-transform that indicates how the browser determines whether it's in a CJ context or not.

My current thinking is that it will be important to identify language settings before applying the discard rules.

**Comment by r12a** [comment]
For example, the counting rods block also contains Western tally marks, and it may be better to keep spaces between those if they appear on either side of a line break in English content.

**Comment by frivoal** [comment]
> I wasn't able to find the text in https://drafts.csswg.org/css-text-3/#line-break-transform that indicates how the browser determines whether it's in a CJ context or not.

For now, it doesn't. It could be change to take the `lang` attribute into account if we wanted to introduce some notion of a language dependent context.

**Comment by fantasai** [comment]
@r12a @frivoal I think the CSSWG wanted to avoid introducing language-dependency for the space-discarding rules.

My take on this, based on @dscorbett’s comment, is to exclude these characters from the space-discarding set. Based on that I propose to close this issue as no change.

**Comment by kojiishi** [comment]
Looks good to me.
