### ISSUE TITLE
[css-cascade] Where do Cascade Layers fit in the cascade?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5003]
This is in relation to #4470 custom-origin proposal, and [Cascade 5](https://drafts.csswg.org/css-cascade-5/#cascade-layering).

While originally based on the concept of “origins” as a useful way to balance larger-scale cascade layers, this feature isn’t necessarily tied to the current rules for origins and importance — which exist to balance power at an even larger scale between authors and users/user-agents. Instead, 

In order to address the use-cases described in early conversations (`Reset < Design System < Overrides`, `Reset < Defaults < Patterns < Layouts < Components`, `CMS Core < CMS Extend < Base Theme < Site Styles`, `Old Styles < New Styles`), “custom origins” only need a higher weight than specificity. Given that, I think it would work best as a new cascade layer between scope & specificity. 

That would mean:

- Authors get a new “top-level” cascade option above specificity, and not limited by selector practicalities, but still confined to origin & scope.
- The feature would not impact existing origin/importance and scope/shadow-dom rules, potentially rendering #4984 moot.

**Comment by mirisuzanne** [comment]
The [working proposal](https://gist.github.com/mirisuzanne/4224caca74a0d4be33a2b565df34b9e7#where-do-cascade-layers-fit-in-the-cascade-5003) for adding layers to the cascade sort order is:

1. Origins & Importance
2. Context (eg Shadow DOM)
3. **Layers**
4. Specificity
5. Source Order

This avoids a lot of implementation complexity around Shadow DOM context, while still giving authors a way to group and layer selectors at a level above specificity.

**Comment by mirisuzanne** [comment]
This has been drafted in [Cascade 5](https://drafts.csswg.org/css-cascade-5/#cascade-sort) with one small variation to define how layers interact with the `style` attribute. The resulting sort order is:

1. Origins & Importance
2. Context (eg Shadow DOM)
3. **Style Attributes**
4. **Layers**
5. Specificity
6. Source Order

Which results in `style` rules remaining at the top of a given origin for both important and normal styles:

1. ❗️Author 
   1. ❗️**Style Attribute**
   2. ❗️Defined Layers (in reverse order)...
   5. ❗️*unlayered*
2. *Animations*
3. Author
   1. **Style Attribute**
   2. *unlayered*
   3. Defined Layers (in declared order)...

**Comment by tabatkins** [comment]
Yeah, this seems reasonable to me overall.

**Comment by mirisuzanne** [comment]
This is the model that we resolved to move into Cascade level 5 and the FPWD. Closing as resolved. If anyone has more specific issues with this approach, that can be discussed in a new thread.
