### ISSUE TITLE
[scroll-animations] Consider renaming @timeline to @scroll-timeline

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#5008]
I find it odd that `@timeline` requires a `timeline-type` property, it feels to me that the at-rule name itself should fully qualify the type of timeline we're dealing with. As such I would suggest `@scroll-timeline` as a better name for the new at-rule as it stands, requiring one less CSS property to be defined. I think this also makes it simpler to specify where `scroll-`prefixed properties are applicable.

**Comment by majido** [comment]
I don't mind doing this. The initial idea was to have the same rule type (`@timeline`) for both scroll timeline and time timeline. But given that there is currently no value in having a time timeline in CSS then perhaps we should avoid paying the extra ergonomics cost is not worth it.

It would be easy to have an @timeline in future that does both without much of an implementation cost as far as I can tell.

**Comment by majido** [comment]
At our recent F2F we decided to adopt this proposal. I will update the spec to reflect this.

**Comment by majido** [comment]
This is now fixed.
