### ISSUE TITLE
[cssom] Is LegacyNullToEmptyString allowed on CSSOMString?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5010]
WebIDL:
> The [LegacyNullToEmptyString] extended attribute must not be associated with a type that is not DOMString. [[1]](https://heycam.github.io/webidl/#LegacyNullToEmptyString)

But cssom uses it in many places, and associates it with CSSOMString. Came up since Blink's IDL compiler won't accept [LegacyNullToEmptyString] on CSSOMString, which (so far) appears to be the right behavior.

**Comment by tabatkins** [comment]
I mean, clearly it's not allowed.  But perhaps it should be? Or it looks like maybe we can just move it to the DOMString in the typedef?

**Comment by emilio** [comment]
I think it should be allowed on USVString at least. I opened https://github.com/heycam/webidl/pull/915 for that.

Moving to the DOMString in the typedef doesn't quite work as not all CSSOMStrings use it.
