### ISSUE TITLE
[mediaqueries] Define Media Groups: continuous vs paged, etc.

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5019]
https://www.w3.org/TR/CSS2/media.html#media-groups needs to live somewhere, or at least some of it does.

**Comment by frivoal** [comment]
We already talked about that in https://github.com/w3c/csswg-drafts/issues/2413, and concluded that this did not need to be ported: is was poorly defined, and its only known use, the "Media" entry in propdef table wasn't even using it properly or consistently. So all specs were updated to drop Media entry in propdef tables, and instead include normative prose in the few cases where there was anything useful to say.

Did you run into another reason why this would actually be needed?

**Comment by frivoal** [comment]
Agenda+ to preferably resolve as wontfix (since I don't see anything new since #2413), or at least defer to MQ4 and not have this stand between MQ4 and an updated CR.

**Comment by fantasai** [comment]
We depend on those definitions in https://www.w3.org/TR/css-position-3/#def-cb and it would be nice to have something other than CSS2.1 to point at.

**Comment by frivoal** [comment]
paged vs continuous seems doable, without vagueness: when you overflow the ICB in the block axis, do you get fragmentation or scroll bars. I think we could indeed define that one. I don't think the rest of the the Media Group distinctions are worth doing anything about.

In that case, I propose to add the `continuous media` and `paged media` definitions into https://drafts.csswg.org/mediaqueries-4/#mf-overflow-block

Which raises an interesting question: which of `continuous media` and `paged media` should `@media (overflow-block:none)` and `@media (overflow-block:optional-paged)` be classified at? For `none`, it doesn't really make a difference (but I'd go with `paged media`), but for `optional-paged` it would. There too, I'd go with `paged media`, to get the per-page replication of fixed-pos elements.
