### ISSUE TITLE
Feature for Display property: Seperation of visibility and layout behaviour

### ISSUE THREAD

**Issue by sir-script** [w3c/csswg-drafts#5022]
Hi guys,

first of all, sorry for my bad english...

During my life as a web developer it comes often to situation, 
where you only need to toggle the "visibility" of some elements.

I use display:none for this situation, 
because the hidden element should not take some kind of extra space.
But you need to know the previous state of the display property,
if you want to show the element again with the exact look and feel.

display: flex -> display:none -> should be display:flex...
display: block -> display: none -> should be display:block...

Would it be possible to seperate the visibility and "layout" behaviour
of the display property in future specs?

Spec: https://www.w3.org/TR/css-display-3/

Cheers and thanks in advance.

Michael

**Comment by faceless2** [comment]
This idea has come up before - see https://github.com/w3c/csswg-drafts/issues/343 (and https://github.com/w3c/csswg-drafts/issues/4897).

**Comment by sir-script** [comment]
@faceless2 nice :), thanks for the really quick processing. I understand... To find a good name is always a challenge. It will be a great feature :)

**Comment by tabatkins** [comment]
Yup, since this is already tracked (and I still strongly hope we can get it done!), I'll close this as a dupe, thanks!
