### ISSUE TITLE
[css-text] Editorial nit for example 8

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#5024]
4.1.3. Segment Break Transformation Rules
https://drafts.csswg.org/css-text-3/#line-break-transform

Example 8.
I think the line break after the first line of the Chinese example is unfortunate, because the untrained eye won't be able to immediately detect that the line-break wasn't turned into a space (line ends with ，). Why not pull 在 up onto the first line?

**Comment by frivoal** [comment]
On the one hand, you're right that it's not visually obvious there's not an extra space for people who don't know that this punctuation sign is a wide one. On the other hand, this example demonstrates that the segment break transformation works fine with punctuation marks at the end of the line, and making the change you suggest would loose that.

**Comment by r12a** [comment]
Yes, i figured that was why you did it, but it seemed to me that the disadvantage for most readers outweighted the advantage for those with enough awareness to interpret correctly what was happening.

**Comment by frivoal** [comment]
Maybe we can replace the`，` with a `！`? Since it is a centered punctuation mark, there's no risk that it looks like a space got injected, and we can still demostrate that you can line break around punctuation. The phrasing is less natural, but the text still makes sense.

**Comment by r12a** [comment]
Mmm. It's not centred in Simplified Chinese, only Traditional, eg. go [here](http://localhost/pickers/hani/?text=%E8%BF%99%E4%B8%AA%E6%AE%B5%E8%90%BD%E6%98%AF%E5%91%A2%E4%B9%88%E9%95%BF%EF%BC%81%20%E5%9C%A8%E4%B8%80%E8%A1%8C%E5%86%99%E4%B8%8D%E8%A1%8C%E3%80%82%E6%9C%80%E5%A5%BD%20%E7%94%A8%E4%B8%89%E8%A1%8C%E5%86%99%E3%80%82) and select  the PingFang SC font.  (You may find [this table](https://r12a.github.io/scripts/han/#phrase) useful)

Also, this doesn't currently work as expected with all punctuation. For example, if you swap the `，` with a `⁈` you get a space after. :(

Btw, there's also a typo in the flattened version: missing 写.

**Comment by r12a** [comment]
Also, the markup for the example doesn't have a lang attribute:

```
<figure>
<pre>这个段落是呢么长，
在一行写不行。最好
用三行写。
</pre>
     <p>这个段落是呢么长，在一行不行。最好用三行写。</p>
```
These being han characters, that may lead to some unpredictable results for readers.

**Comment by frivoal** [comment]
> Btw, there's also a typo in the flattened version: missing 写.

and
> Also, the markup for the example doesn't have a lang attribute

Fixed: https://github.com/w3c/csswg-drafts/commit/3fc426828bb564f53822eb3b45a5219c093ffd15

**Comment by frivoal** [comment]
@fantasai and @kojiishi, what do you think?

**Comment by fantasai** [comment]
I think having the example handle punctuation is good; the second line already shows the case between two Letters.

> For example, if you swap the ， with a ⁈ you get a space after. :(

@r12a, If you want to discuss this comment, please file it separately. We do already have a related discussion in https://github.com/w3c/csswg-drafts/issues/5017 But a few points to note: we've been asked by some implementers to keep things block-by-block since this code is "hot", and we've been asked to avoid switching behavior based on language (which has bad implications for both perf and portability).

**Comment by frivoal** [comment]
So, other than the fixes already made and mentioned in https://github.com/w3c/csswg-drafts/issues/5024#issuecomment-626096274, the proposal would be to close this with no change, the rationale being that while it may not be immediately visually obvious to the non trained eye what's going on, trained/careful eyes will understand, and it is better for the example to cover this situation than not.

@r12a is that acceptable to you?

**Comment by r12a** [comment]
> >For example, if you swap the ， with a ⁈ you get a space after. :(

> @r12a, If you want to discuss this comment, please file it separately. We do already have a related discussion in #5017 

I was just trying to say that 

> we can still demostrate that you can line break around punctuation

is only true for _some_ punctuation.

**Comment by r12a** [comment]
Then my suggestion would be to replace the zh-Hans language tag with zh-Hant.  That will produce a centred punctuation, which still makes the point but is (slightly) less open to the possible misunderstanding we started with.  

I'd be happier if you made that change, but i leave it up to you.

**Comment by frivoal** [comment]
Switching to zh-Hant seems like a reasonable compromise, I'll do that.
