### ISSUE TITLE
[css-position-3] Define what out of flow means

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5027]
https://www.w3.org/mid/121317FE-7226-4FD0-A6F5-C2419BEBD904@rivoal.net

**Comment by frivoal** [comment]
So far, this is a defined term in css-display: https://drafts.csswg.org/css-display-3/

**Comment by Loirooriol** [comment]
Seems to me that some terms defined in CSS Display could be moved to CSS Position:
 - https://drafts.csswg.org/css-display-3/#containing-block
 - https://drafts.csswg.org/css-display-3/#containing-block-chain
 - https://drafts.csswg.org/css-display-3/#initial-containing-block
 - https://drafts.csswg.org/css-display-3/#out-of-flow
 - https://drafts.csswg.org/css-display-3/#in-flow

**Comment by fantasai** [comment]
@Loirooriol containing block is a pretty fundamental concept to layout: if we removed positioning entirely from CSS, it would still be needed. So I think the fundamental definition belongs in Display. Position just has the most complicated set of rules, and it crosses through various layout modes, so it's got more text about it than other layout models.
