### ISSUE TITLE
 [css-overflow] scrollbar-gutter: allow "auto" to be omitted

### ISSUE THREAD

**Issue by felipeerias** [w3c/csswg-drafts#5029]
[The signature of `scrollbar-gutter` (spec)](https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property) indicates that one of `auto`, `stable` or `always` must be present, optionally followed by `both` and/or `force`:

    auto | [ stable | always ] && both? && force? 

(please let me know if I am reading this incorrectly)

Since `auto` is the value by default, I would like to suggest that it could be omitted from the `scrollbar-gutter` declaration if the author is using `both` and/or `force`.

So, these declarations would be valid:

    scrollbar-gutter: both;
    scrollbar-gutter: force;
    scrollbar-gutter: force both;
    scrollbar-gutter: both force;

And their effect would be exactly the same as:

    scrollbar-gutter: auto both;
    scrollbar-gutter: auto force;
    scrollbar-gutter: auto force both;
    scrollbar-gutter: auto both force;

**Comment by tabatkins** [comment]
Ah, not quite - the `|` binds most loosely, so the allowed values are `auto` by itself, or `stable`/`always`, optionally with `both` and/or `force`. You can't combine both/force with auto.

**Comment by felipeerias** [comment]
I see, thank you.
