### ISSUE TITLE
[css-color-adjust] color-invert CSS property

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5037]
This would invert the existing colors on the property. e.g. white text becomes black, black background becomes white.

Motivation: helps site authors implement a dark theme incrementally.

More details here: https://github.com/minorninth/forced-dark-mode/blob/master/explainer.md#css-invert-property

@minorninth

**Comment by Malvoz** [comment]
To the CSSWG, I think https://github.com/w3c/csswg-drafts/issues/4623 and https://github.com/w3c/csswg-drafts/issues/2875 are ultimately discussing the same thing so perhaps want to merge into 1 issue.

**Comment by chrishtr** [comment]
I agree, they look like ultimately the same use case.

**Comment by fantasai** [comment]
Closing out in favor of https://github.com/w3c/csswg-drafts/issues/2875 which is a better proposal.
