### ISSUE TITLE
[mediaqueries] Which levels should the dynamic-range and video-* media features be in

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5042]
In issue https://github.com/w3c/csswg-drafts/issues/4471, which was tagged against media queries **level 5**, we resolved to add the dynamic-range and a few video-* media features.

PR https://github.com/w3c/csswg-drafts/pull/4678 made these changes to media queries **level 4**.

Which of the two do we want these into?

As a reminder, MQ4 is in CR, while MQ5 is FPWD.

I'm tempted to put all of that into level 5, as adding new features after getting to CR is a good way to be stuck in CR for a long time. At the same time, `color-gamut` is in level 4, and having `dynamic-rage` defined along with it is quite topical.

**Comment by svgeesus** [comment]
> At the same time, color-gamut is in level 4, and having dynamic-rage defined along with it is quite topical.

True but as a counter argument, the wide color gamut features are in [CSS Color 4](https://drafts.csswg.org/css-color-4/) and the HDR features, and it is [still being discussed what they should actually be[(https://w3c.github.io/ColorWeb-CG/) haven't even been outlines in CSS Color 5 yet.

On the other hand, MQ is merely testing for presence/absence, not giving that much detail on how HDR is handled.
