### ISSUE TITLE
[mediaqueries] length units in video-* media features.

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5044]
The [definition](https://drafts.csswg.org/mediaqueries-5/#video-width) of the `video-width` media feature (same thing for `video-height`) includes this:

> lengths are interpreted according to [[#units]].
 
This means (I believe) that we're doing things like measuring in CSS px, not in device pixels, as we always do everywhere.

However, I suspect that this isn't actually what implementations plan to do, and a 4K TV probably wants to report 3840 × 2160 (and a resolution of 1dppx), regardless of viewing distance.

If so, we should probably change the above phrasing, or at the very least add a note saying that implementations are likely to anchor the css px unit to physical device pixels rather than to the angular definition.

If we do intend the usual unit gymnastics, the above phrasing is fine, but a note should probably be added, as this may be unexpected / surprising.

**Comment by simontWork** [comment]
Would it be possible for you to expand upon "anchor the css px unit to physical device pixels rather than to the angular definition."  Does this mean that the pixel definition is normally related to angle subtended (and hence, viewing distance)?

**Comment by svgeesus** [comment]
`px` has both the [original (angle subtended) definition and a physical (1/96 inch)](https://drafts.csswg.org/css-values-4/#absolute-lengths) definition.

The term [anchored](https://drafts.csswg.org/css-values-4/#anchor-unit) also explains which definition to use n which circumstance.

However, it only defines two options and this specification uses a third, which should be added to V&U 4:

-    by relating the physical units to their physical measurements, or
-    by relating the pixel unit to the reference pixel. 

add
-   by relating the pixel unit to a physical device pixel, regardless of size

**Comment by Crissov** [comment]
> I suspect that this isn't actually what implementations plan to do, and a 4K TV probably wants to report 3840 × 2160

Why would this be okay for `video-…` media features when it is not for any other part of MQ nor CSS?

**Comment by smfr** [comment]
Some questions:
* What does `video-width` measure for a non-fullscreen browser window?
* Does video-width take display resolution (i.e. 2x or 3x Retina scaling) into account, which would make it different from the `width` media query.

**Comment by frivoal** [comment]
> What does video-width measure for a non-fullscreen browser window?

To be of any use, it would need to be the size of the window I think, but then again, are there devices/OSes which use the notion of a video plane *and* have non full screen windows?

> Does video-width take display resolution (i.e. 2x or 3x Retina scaling) into account, which would make it different from the width media query?

That's the key question, and based on the discussion on the call, what I think I'm hearing is that the video-width would be calculated at 1x, so on a 2x Retina screen, video-width would be twice as big as width. But that's not a clean fit with how the rest of css works…

**Comment by fantasai** [comment]
If video-width is to be measured in device pixels, it should not be using `<length>`. It should just be an `<integer>`.

**Comment by chrisn** [comment]
Device pixels are needed for the video plane so that the web app can select the correct video resolution. It's important to avoid rescaling the video during playback, where possible.

> What does video-width measure for a non-fullscreen browser window?

For TV devices, I'd expect this to still return the native resolution of the full screen video plane. We can use existing media queries for the browser window size.

> If video-width is to be measured in device pixels, it should not be using <length>. It should just be an <integer>. 

This sounds good to me.

cc @mwatson2, @vi-dot-cpp, @chcunningham for additional input from Media WG members.

**Comment by mwatson2** [comment]
+1 to @chrisn's comments.

We need to decide which version of the video to stream. If the device has enough physical pixels on the screen to make delivery of 4K worthwhile, we'll stream that, even if the window is not - now - fullscreen but might be later. We want to build up a video buffer, so we request media in anticipation of future needs. There is a slight difference here for video compared to how you might handle images where you might download the resolution you need now and fetch a new one if the window is resized.

If the device does not have enough physical pixels to make 4K worthwhile, we'll deliver HD as this would be an overall better UX (less chance of rebuffering, greater possibility to avoid scaling artifacts).

The desire above applies whether or not the device has a separate video plane architecture, but I think there are sufficient properties already to determine the physical pixel resolution in the single-plane case.

**Comment by chcunningham** [comment]
Hey Gang, I want to follow up from the CSS : Media WG call.

The call helped me to understand some issues with specifying that video- queries use device pixels: 1) fixing resolution to 1 dppx is unusual 2) what do we do with 'em' 3) what do we do for fullscreen vs not

I have a few ideas. I'm not an expert in CSS units... hopefully this isn't too naive. 

What if we spec that video-* uses css pixels just like non-video, and just leave implementers with the _option_ to setup their video plane w/ resolution = 1dppx such that this is effectively device pixels where desired. IIUC, this isn't really novel. Implementers of existing media queries already enjoy this flexibility. 1dppx is valid and even common. The question of 'what do for em/fullscreen' is then answered: same thing we do already under these conditions elsewhere. 

I think this is also more correct for non-TV implementers. When you don't have a separate video plane, the simplest design is that video-* answers match that of non-video. 

I do see a potential wart (but I think its manageable). The earlier idea to spec that its actually device pixels makes media queries straightforward for callers. Folks like Netflix have a fixed number of resolutions available for a given title, so they only need a handful min-video-height queries). But if resolution is allowed to vary, it seems you have to binary search that value first to know what scale factor to apply. Is there some MQ syntax sugar that makes this easy? Even a true binary search seems pretty doable. 

Alternatively, we could take all of the above arguments about using CSS pixels and flexible resolution, and carry those to a proposal for Screen attributes. No binary search. On the call, I think a rep from Apple (was it @smfr ?) indicated this raised fingerprinting concerns. The binary search for this info is pretty trivial, so MQ seems not meaningfully more privacy protecting?

**Comment by chcunningham** [comment]
Hi group. Just checking in on my last comment. Happy to meet to discuss further if that helps.

**Comment by chcunningham** [comment]
@tabatkins @frivoal and I chatted virtually. They prefer adding video-width/height to the Screen interface as opposed to 
MQ attributes. The Screen path avoids users having to binary search for the value. Dynamic-range doesn't have this pitfall, so it still makes sense as a MQ attribute.

**Comment by zcorpan** [comment]
Do you need this info for all screens?

https://webscreens.github.io/window-placement/#dictdef-screeninfo

**Comment by svgeesus** [comment]
> Maybe TVs only render video in full screen

Mostly, but they also have picture-in-picture for thumbnail videos etc

**Comment by chcunningham** [comment]
> Do you need this info for all screens?

Probably only necessary for the "current" Screen (so current Screen semantics should work). Would be nice to have an event if the screen changed though.

**Comment by chrisn** [comment]
There's a related issue on the Window Placement API: https://github.com/webscreens/window-placement/issues/20

**Comment by jpiesing** [comment]
> Seems ok for full screen video cases, but its not great for video that's inline among other elements. Maybe TVs only render video in full screen (@jpiesing let us know)? Is that something we can rely on going forward?

@chcunningham Unfortunately it's more complex. TVs will;
- Display video intended to be full screen as full screen
- Scale video intended to be full screen either down to partial screen or up so that some of the video is cropped
- Display video intended to be partial screen as partial screen

Thjs is a little out of my area of expertise & this explanation may not be 100% correct but it's close ...
When I refer to video being "intended" be a particular size, one of the tricks used in video distribution is to reduce the encoded resolution but keep the decoded resolution unchanged. Video could have a decoded ("intended") resolution of 1920x1080 but an encoded resolution of 960x540.

**Comment by chcunningham** [comment]
Sorry for the long pause. @frivoal reminded me this remains open. Lets fix it!

Given @jpiesing's  [https://github.com/w3c/csswg-drafts/issues/5044#issuecomment-723032003](comment above), I'd like to pursue the second option I suggested:

> add deviceVideoPixelRatio to Screen. You can then determine the "video" pixels of anything, including screen (width, height), window (availWidth, availHeigh), as well as inline

Only I guess I should revise that add the attribute to Window, not Screen (since that's where devicePixelRatio ended up).

Authors would then right code like so...

_full screen case_

```
targetResolution = screen.width * window.deviceVideoPixelRatio;
```

_inline case_

```
targetResolution = element.clientWidth * window.deviceVideoPixelRatio;
```

And then fetch video assets according to whatever is closest to targetResolution.

@smfr @zcorpan @emilio: would you mind if I send a PR to add this to cssom-view?

**Comment by frivoal** [comment]
Agenda+ to discuss the above proposal

**Comment by chrisn** [comment]
> Authors would then write code like so...
> 
> _full screen case_
> 
> ```
> targetResolution = screen.width * window.deviceVideoPixelRatio;
> ```
> 
> _inline case_
> 
> ```
> targetResolution = element.clientWidth * window.deviceVideoPixelRatio;
> ```

This direction looks good to me.

> Probably only necessary for the "current" Screen (so current Screen semantics should work). Would be nice to have an event if the screen changed though.

I agree. I don't think new events are needed if applications can use the [`video-resolution` media query](https://drafts.csswg.org/mediaqueries-5/#video-resolution), similar to [this example](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio#monitoring_screen_resolution_or_zoom_level_changes).

**Comment by chcunningham** [comment]
Sorry, I was on the call but had mic issues. I don't object to removing these media queries. I've filed #6891 to host the follow up discussion.
