### ISSUE TITLE
[css-ruby] [editorial] Reconsider the use of the term "formatting context"

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5047]
During the F2F this month, we're discussing many issues about ruby layout. In particular, we're resolving that line-height applies the same way it does for nested `<span>`s. It's already true that ruby participates in line justification within its containing line.

The term "formatting context" indicates a large amount of independence, but ruby seems to act more like `<span>`s than it does `float`s or `inline-block`s. Our layout team has been led astray by this term being used in the spec. It's probably worth reconsidering whether or not this term is invoked.

(For comparison, the definition of `text-emphasis` doesn't use this term.)

**Comment by frivoal** [comment]
I think based on the terminology established by css-display-3, this is indeed a ["formatting context"](https://drafts.csswg.org/css-display-3/#formatting-context), but it is not an ["independent formatting context"](https://drafts.csswg.org/css-display-3/#independent-formatting-context).

So the terminology is being used correctly, but that doesn't mean it's not misleading.

**Comment by frivoal** [comment]
An easy way out would be simply to add a note in css-ruby, right next to where we say ruby containers  establish a formatting context:

> However ruby containers also establish a ruby formatting context that builds further structure around their segment of the inline formatting context. <ins>Note: this is <em>not</em> an independent formatting context</ins>

**Comment by tabatkins** [comment]
Yeah, the terminology is well-defined; I *could* see us coming up with a different name, but I'm less sure that we can come up with a related term for "independent formatting context" that doesn't cause the same confusion.

**Comment by frivoal** [comment]
@litherum , after https://github.com/w3c/csswg-drafts/commit/76b18974bf52eb446219b4a1b09566cd06c95400, this ought to be clearer now. Can you have a look over at https://drafts.csswg.org/css-ruby-1/#formatting-context (giving bikeshed enough time to rebuild) and confirm this is now ok to close?
