### ISSUE TITLE
[css-color-4] Is color space name case sensitive?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#5052]
I can't find anything in [the definition of `<ident>`](https://drafts.csswg.org/css-values-4/#typedef-ident) that restricts it to being case sensitive or not, so I assume it depends on usage (this seems to be the case in other places that use `<ident>`, such as [custom properties](https://drafts.csswg.org/css-variables/#example-81b6bcdd).

There is nothing about case sensitivity in [the definition of color()](https://drafts.csswg.org/css-color-4/#color-function). WebKit, which is the only current implementation, seems to treat it as case insensitive. [demo](https://dabblet.com/gist/35558d661baf6345cfde3db2c52b882c).

Not sure if there are any color spaces that are only distinct by capitalization. There are certainly some that are weird if lowercased, e.g. [xyY](https://en.wikipedia.org/wiki/CIE_1931_color_space#CIE_xy_chromaticity_diagram_and_the_CIE_xyY_color_space), but I'm leaning towards case-insensitivity, unless someone can produce an example of color space names that actually clash if same cased.

If we change this to case sensitive, we should probably do so ASAP before other implementations.
If we don't, we should still clarify in the spec.

CC @svgeesus @tabatkins

**Comment by tabatkins** [comment]
The predefined ones are ASCII case-insensitive, as they're [predefined keywords](https://drafts.csswg.org/css-values/#keywords).  (If we ever want to add some that do vary only on case, we'll just have to come up with a different name for one.)

The author-defined ones are case-sensitive, as they're [dashed idents](https://drafts.csswg.org/css-values/#dashed-idents).

**Comment by svgeesus** [comment]
[CSS properties accept two classes of identifiers: pre-defined keywords and author-defined identifiers.](https://drafts.csswg.org/css-values-4/#typedef-ident)

The link to pre-defined keywords is how one finds these are ASCII case-insensitive, same as any other predefined keyword. Is that self-documenting enough, or should additional reinforcement be added in CSS Color 4?

**Comment by tabatkins** [comment]
CSS *generally* is case-insensitive, so there's no need to repeat that when it's true.

I think it's worthwhile to point out when something is case-sensitive, even if it *is* well-defined already; it's a rare exception and it helps authors to call it out.

**Comment by svgeesus** [comment]
Closing as it is clear the color space names are case-insensitive and no edits needed.
