### ISSUE TITLE
[css-fonts] generic family for Pi, Picture, Symbols fonts 

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#5054]
Symbol fonts are containers for vector graphics, ideally stored with PUA Unicode code points. They are an anti-pattern, but they exist and will not go away soon. Where they are used and fail to load for whatever reason, one of two things will be shown: either a _no glyph box_ or a glyph from a random installed font that happens to use the same PUA code point. The latter frequently happens with pre-standard emojis on iOS.

I wonder whether a new generic font family like `symbol` could help to avoid this problem if specified as the last fallback to indicate that actually no fallback should be used.

**Comment by tabatkins** [comment]
Oh, this ended in a different place than I expected!

So you're asking for a generic font that matches all codepoints but has no glyphs?

(I think calling it "symbol" would be misleading, but the idea seems reasonable.)

**Comment by AmeliaBR** [comment]
I agree with Tab that a `symbol` generic font would be confusing, because people would expect it to actually provide symbols and if they aren't Unicode standard glyphs that wouldn't be possible to do reliably.

But, a way for authors to say “don't fall back” (or maybe to offer their own fallback glyph?) sounds logical.

**Comment by frivoal** [comment]
If we add this, `blank` would seem like a reasonable name to me.

But I'm not sure we should.

Some of the motivation for this overlaps with the [font-display property](https://drafts.csswg.org/css-fonts-4/#font-display-desc).

Symbol fonts used with codepoints that match emoji / other reasonable fall back values don't really need this.

Symbol fonts used with PUA / inappropirate code points are, as called out in the opening comment, an anti pattern. So I'm not sure we should make their usage easier.

**Comment by Crissov** [comment]
The actual name or alternative solution is of course very much up to debate, but Iʼm glad you agree that this might be useful to have.

**Comment by litherum** [comment]
> a glyph from a random installed font that happens to use the same PUA code point.

IIRC the spec already has text forbidding this. I know Chrome has special code forbidding falling back to an undesired font for PUA code points, and we have a bug to do the same thing in WebKit. I’d like to copy Chrome’s behavior here.

In particular, PUA code points are special, and shouldn’t fall back to an undesired font, even if there is a font on the system that can support them.

**Comment by svgeesus** [comment]
> If a given character is a Private-Use Area Unicode codepoint, user agents must only match font families named in the font-family list that are not generic families. If none of the families named in the font-family list contain a glyph for that codepoint, user agents must display some form of missing glyph symbol for that character rather than attempting system font fallback for that codepoint. When matching the replacement character U+FFFD, user agents may skip the font matching process and immediately display some form of missing glyph symbol, they are not required to display the glyph from the font that would be selected by the font matching process.
[5.4. Character handling issues](https://drafts.csswg.org/css-fonts-4/#char-handling-issues)

**Comment by svgeesus** [comment]
So, is the existing quoted spec text sufficient here, to prevent undesired fallback for PUA characters?

**Comment by Crissov** [comment]
If I'm reading it correctly, it should be sufficient indeed.
