### ISSUE TITLE
[css-grid] Possibility of having gaps only on specific columns/rows

### ISSUE THREAD

**Issue by huijing** [w3c/csswg-drafts#5056]
While attempting to recreate the design in the image below, there is a column of content which has a sort of margin between itself and its adjacent column. However, there are no other such column gaps in the rest of the design. Currently, I would add an empty track for that purpose but wondered if there was a possibility of having grid gaps only on specific columns or rows.

![overlay-2](https://user-images.githubusercontent.com/1461498/81472898-6726c880-922d-11ea-9588-9289a282ae96.jpg)

The most related issues I can find are https://github.com/w3c/csswg-drafts/issues/1659 and maybe https://github.com/w3c/csswg-drafts/issues/2748, because the W3C discussion log mentions the consideration required for items that span across gaps, which is evident in the image example above.

Gap is currently defined in CSS Box Alignment Module Level 3 (https://www.w3.org/TR/css-align-3/#gaps).

**Comment by MatsPalmgren** [comment]
This is already covered by #1659 isn't it? You could do the above design with `column-gap: repeat(3,0) 1em repeat(auto-fill,0)` for example, right?
