### ISSUE TITLE
[css-inline] The web de-facto requires nonnegative line gap metrics in fonts

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5064]
Firefox and Chrome both run web fonts through the [OpenType Sanitizer](https://github.com/khaledhosny/ots), which rewrites the font file. One of the things it does is clamp line gap metrics so that they aren't negative.

WebKit got a compatibility bug about this, since WebKit wasn't doing the same clamping. I've committed a [change](https://bugs.webkit.org/show_bug.cgi?id=211683) in WebKit to align with the other browsers and perform the clamping.

Because now all the browsers agree, and it is de-facto required for the web, the CSS fonts spec should say so (somewhere).

**Comment by astearns** [comment]
Is the line gap metric clamping the only thing this sanitizer does that you think is required for web compat?

Are these metrics allowed to be negative per the OpenType spec?

**Comment by litherum** [comment]
> Is the line gap metric clamping the only thing this sanitizer does that you think is required for web compat?

This is the only thing I'm aware of today. Perhaps we will discover more in the future.

> Are these metrics allowed to be negative per the OpenType spec?

The spec says they are of signed type. It doesn't say anything about negative values. https://docs.microsoft.com/en-us/typography/opentype/spec/hhea and https://docs.microsoft.com/en-us/typography/opentype/spec/os2

**Comment by litherum** [comment]
Oh, this probably also affects the grammar of `line-gap-override` in css-fonts

**Comment by litherum** [comment]
> Oh, this probably also affects the grammar of `line-gap-override` in css-fonts

Oh, looks like this was already done in 348ed3540c4d7a353c813fce14ce4526d0910a17
