### ISSUE TITLE
[css-scroll-snap-1] scrolling due to focus movement should include scroll-padding

### ISSUE THREAD

**Issue by alastc** [w3c/csswg-drafts#5066]
For keyboard/switch users who effectively tab through a page, a sticky footer (going forwards) or a sticky header (going back up the page) will obscure the view of the focused element. 

[Asking around](https://twitter.com/alastc/status/1260347064002756610), people suggested the [scroll-padding property](https://drafts.csswg.org/css-scroll-snap-1/#propdef-scroll-padding), which appears to work in Chrome but not Firefox. ([Test case](https://alastairc.uk/tests/wcag22-examples/sticky-footer3.html).)

I can't see anything on whether a browser should treat tabbing through the page as something that is affected by scroll-padding. (Although I don't read CSS specs very often, perhaps I missed it?).

Could something be added to indicate a standard behaviour for this? E.g. at the end of the [intro for 4.2](https://drafts.csswg.org/css-scroll-snap-1/#scroll-padding): "... or simply to put more breathing room between a targetted element and the edges of the scrollport. Targetted elements must also include focusable elements which gain focus when the user is tabbing through the page."

The wording is probably not appropriate for a CSS spec, but I hope you get the idea.

-Alastair
Co-chair, Accessibility Guidelines Working Group

**Comment by alastc** [comment]
Just to note, I've raised a bug on Firefox for this as well:
https://bugzilla.mozilla.org/show_bug.cgi?id=1642922

**Comment by fantasai** [comment]
This is already implied in the spec:

> **These offsets reduce the region of the viewport that is considered “viewable” for scrolling operations**: they have no effect on layout, on the scroll origin or initial position, or on whether or not an element is considered actually visible, but **should affect whether an element or the caret is considered scrolled into view**, and reduce the amount of scrolling for paging operations (such as using the PgUp and PgDn keys or triggering equivalent operations from the scrollbar) so that within the optimal viewing region of the scrollport the user sees a continuous stream of content.

Maybe we just need to add an example.

**Comment by fantasai** [comment]
@alastc Added (e.g. for targetting or focusing operations) to the scroll-into-view clause. Let me know if that seems adequate!

**Comment by alastc** [comment]
Hi @fantasai, yep "focusing operations" covers the use-case. And the Firefox bug was resolved, so the main browsers align now.

Thanks, feel free to close.
