### ISSUE TITLE
[css-grid] editorial: ambiguities in §12.5

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#507]
There are a couple of ambiguities in §12.5. Resolve Intrinsic Track Sizes,
under "For auto minimums: ", 2nd paragraph:

> Otherwise, set its base size to the maximum of its items’ **_min-size contributions_**: the value specified by its respective min-width or min-height properties (whichever matches the relevant axis) if the specified **size** is auto, or else the item’s min-content contribution.
1. it's not clear what the word size is referring to there, it could be a reference to the min-width/height values earlier in the same sentence ,or it could be a reference to the width/height properties (whichever is relevant for the axis).
   It appears that @tabatkins already agreed that it's the latter and that the text needs to be clearer:
   https://bugzilla.mozilla.org/show_bug.cgi?id=1255393#c4
2. it's not clear how far the definition of the term 'min-size contributions' reaches.
   Is it the entire text that follows, or is it just up to the first comma and that the "or else the item’s 
   in-content contribution" is not part of the definition, but rather something that just relevant to
   computing the value to be used for the "auto minimums" clause?
   (I will assume for now that the definition includes all the text up to the final period.)

In general, I think it would be a good idea to break out each definition of a term to
a standalone paragraph, rather than embedding it together with other text. 
Perhaps in a separate chapter early in the document, like how it's done in css-sizing:
https://drafts.csswg.org/css-sizing/#terms

**Comment by fantasai** [comment]
Okay, I did some rewording. Should be fixed now, let me know if it's still a problem.

**Comment by MatsPalmgren** [comment]
Point 1 is clear now, thanks.  It seems you did not address point 2?

**Comment by tabatkins** [comment]
Done. I just pushed the definition to a separate sentence, so there's no way to misinterpret its bounds.
