### ISSUE TITLE
[css-break-3] sentence on truncating cloned margins/border/padding at break points says block-end twice

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#5070]
The [section on unforced breaks](https://drafts.csswg.org/css-break-3/#unforced-breaks) currently has the text:

> If even that does not lead to sufficient break points, [cloned margins/border/padding](https://drafts.csswg.org/css-break-3/#valdef-box-decoration-break-clone) at the block-end side are truncated; and if more room is still needed, [cloned margins/border/padding](https://drafts.csswg.org/css-break-3/#valdef-box-decoration-break-clone) are truncated at the block-end side as well. 

The "if more room is needed" clause is saying the same thing as the previous clause, which doesn't make sense.

I suspect it probably intended to say **block-start** rather than **block-end** side for the "if more room is needed" behavior at the end of the sentence.

**Comment by fantasai** [comment]
Yes, you're right. Relevant WG resolution at https://lists.w3.org/Archives/Public/www-style/2015May/0279.html
