### ISSUE TITLE
[css-overflow-4] Custom ellipsis character

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5071]
css-ui-3 specifies that UAs use the ellipsis character for ellipsis when `text-overflow: ellipsis` is specified. It seems there is [demand](https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5) for allowing a custom character, to handle for example scripts that are not western.

Has this idea been proposed before? I can't find an open issue for it.

**Comment by astearns** [comment]
There used to be a <string> value that I think was meant to be an alternate character, and according to the www-style archives Firefox had an implementation.

https://lists.w3.org/Archives/Public/www-style/2011Jun/0329.html

I also found a mention that some languages use a 6-dot ellipsis?

https://lists.w3.org/Archives/Public/www-style/2008Aug/0008.html

**Comment by chrishtr** [comment]
Is block-ellipsis also relevant? https://drafts.csswg.org/css-overflow-3/#propdef-block-ellipsis

**Comment by Crissov** [comment]
Some people would probably also prefer an arrow, chevron or triangle pointing in the block progression or line direction. Not to mention texts like “TBC”, “continues”, “[trunc.]”, “More” or “Read more”.

**Comment by SebastianZ** [comment]
> ... and according to the www-style archives Firefox had an implementation.

Not only had but still _has_, see https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow#Examples.

Actually, I am surprised it isn't in the specification anymore. Previously it was defined here:

https://www.w3.org/TR/2003/CR-css3-text-20030514/#text-overflow-ellipsis

Sebastian

**Comment by MatsPalmgren** [comment]
It's specced in [css-overflow-4](https://drafts.csswg.org/css-overflow-4/#text-overflow). Firefox supports `[ clip | ellipsis | <string> ]{1,2}` and we shipped that years ago.

**Comment by SebastianZ** [comment]
Oh, right! How could I miss that? So I guess this issue can be closed, right?

Sebastian

**Comment by chrishtr** [comment]
Yes, I think so.
