### ISSUE TITLE
[css-text] The 'anywhere' value of line-break

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#5072]
https://drafts.csswg.org/css-text-3/#status

The [anywhere](https://drafts.csswg.org/css-text-3/#valdef-line-break-anywhere) value of the [line-break](https://drafts.csswg.org/css-text-3/#propdef-line-break) property is currently marked as at-risk.

Use cases of this value exist, such as [newspapers in Taiwan and Hong Kong](https://w3c.github.io/clreq/#prohibition-rules-none). So we want to ask what we can do to remove this value from the list of at-risk features?

This comment was discussed by the i18n WG.

**Comment by frivoal** [comment]
At risk isn't particularly tied to the presence/absence of use cases, but rather to doubts as to whether it will be implemented before transitioning from CR to PR.

That said, it's good to know about additional use cases for this. Maybe it could be mentioned in an example? 

As for at-risk, now that the feature is implemented in multiple browsers, I don't think it is needed anymore, and we should remove it.

**Comment by r12a** [comment]
The i18n WG discussed this issue today and believes that it no longer needs resolution.
