### ISSUE TITLE
[css-display] typo

### ISSUE THREAD

**Issue by beantaxi** [w3c/csswg-drafts#5078]
From Section 1: Introduction

link: "Bidirectional Reorderign Algorithm in CSS Writing Modes"

'Reorderign' is misspelled.

Thanks!

**Comment by frivoal** [comment]
This typo has been fixed a little while back: 94bb5f34e98f69cf375c4046e08488ddcad783fa.

It should no longer be present either in the editor's draft nor in the published version on w3.org/TR
