### ISSUE TITLE
[css-values-4] Consider changing the specified behavior of <ratio>: 0 / 0

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5084]
https://drafts.csswg.org/css-values-4/#ratios says:

> The computed value of a <ratio> is the pair of numbers provided, unless both numbers are zero, in which case the computed value is the pair (1, 0) (same as 1 / 0).

Is there a strong reason this is a computed value change rather than just a "behaves as"?

There isn't really a problem with this, but it feels odd to make it serialize to something else for no good reason, and it seems weird to serialize to `0 / 0` in specified values and `1 / 0` in computed values.

**Comment by Loirooriol** [comment]
I guess this can affect interpolations from/to `0 / 0`depending on #4953

**Comment by tabatkins** [comment]
I don't think that's important, since `0 / 0` is an error case anyway. ^_^

But yeah, I think we were just imprecise in wording there. Should be fine to just make it behave as `1/0`, but continue to compute to `0/0`, if that's easier/better in the implementation.

**Comment by cbiesinger** [comment]
So, in the wpt/css/css-sizing/aspect-ratio/parsing/contain-intrinsic-size-valid.html test, it expects that the *serialized* value of 0/0 is 1/0. The spec only says the computed value should be 1/0. Is the test correct?

**Comment by tabatkins** [comment]
It depends on which value is being serialized. The test is incorrect, since it's serializing the specified value; that should still be `0 / 0`.

**Comment by tabatkins** [comment]
I've fixed the test, btw.

**Comment by cbiesinger** [comment]
I thought I fixed the test :p

**Comment by tabatkins** [comment]
lol, i think i didn't merge the PR for mine

**Comment by tabatkins** [comment]
All right, I changed the spec to just make 0/0 *behave as* 1/0, rather than computing to it. This means that a 0/0 ratio will serialize as 0/0 in all value stages.
