### ISSUE TITLE
[css-align] Content-distribution keywords that fall back to "center" can't be made safe

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#5088]
If you use content-distribution keyword, like "space-between" on a flexbox or grid, and the content overflows the container, it defaults to unsafely centering the content.

But you can't specify safe alignment with a content-distribution keyword! So there's just no way for an author to deal with this, except guess at the screen sizes where it might overflow and use an MQ to change it to something safe.

I propose that we specify that the distribution keywords that currently fall back to "center" instead fall back to "safe center".

(If UAs would just implement the "smart" overflow behavior - be unsafe unless it would push content into the unscrollable area - we'd be fine as-is. But nobody's doing that, grrr.)

**Comment by dholbert** [comment]
> If you use content-distribution keyword, like "space-between" on a flexbox or grid, and the content overflows the container, it defaults to unsafely centering the content.

I think you mean `space-around` or `space-evenly`, right?  (Not `space-between` -- that one [falls back to `flex-start`](https://drafts.csswg.org/css-align/#valdef-align-content-space-between). The other two do fall back to `center` though. Testcase: https://jsfiddle.net/dholbert/f1b4eo0n/

> I propose that we specify that the distribution keywords that currently fall back to "center" instead fall back to "safe center".

This proposal seems reasonable to me.

**Comment by MatsPalmgren** [comment]
I don't see why `safe center` is generally a better fallback behavior.  If it creates unscrollable overflow then sure, but that's what the magic "no value" is for, right? UAs should just implement that instead IMO. Also, it sucks to retroactively change interoperable features that's already been shipped for years by multiple UAs. We should try to avoid that unless it's obvious the feature has major issues when used in practice. I don't see any evidence of that here. For these reasons I'm opposed to this change.

FWIW, it seems like a design error to me that the overflow behavior is built-in without giving authors any way to override it.  There used to be a way to specify a fallback behavior explicitly (which Gecko implemented and then had to remove :disappointed:). I think we should re-introduce that feature (#1002).  We're just waiting on the CSSWG to come up with a syntax there...  We can ship that fairly quickly once we have the syntax.
