### ISSUE TITLE
[css-color-adjust] Re-add `only` to mean "don't auto-adjust me", per WebKit's behavior

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#5089]
Last year, in issue #3881, there was some side discussion that suggested WebKit was doing reacting to 'color-scheme' in a way not described by the spec. I summarized it in [this comment](https://github.com/w3c/csswg-drafts/issues/3881#issuecomment-490113295):

>> We described this last year in #3299, which is still open. Indeed, it does look like that original intent (color scheme transformations at least) was lost in translation.
> 
> Ah, you're referring to "If the user's preference does not match something in the list, the UA is allowed to apply transformations to the content (e.g. apply high-contrast)." from Simon's post.
> 
> If that's the extent of it, opting the page into forced-colors mode, then that's fine, it's just a separate feature that's technically orthogonal to this.
> 
> But if y'all are planning on doing something separate from forced colors, please actually describe it in a new issue so we can talk about it. We're trying our best to make sure these features are described accurately and fully, so authors can have a reasonable idea of how their pages will look. If the "same" feature ends up still acting substantially differently between browsers, then there's no point to it being standardized at all.

No one from WebKit responded after that, so I'm still not sure whether WebKit implemented 'color-scheme' as described in the spec (+ maybe an (allowed) switch into "forced colors mode", as described in the spec, if the user preference isn't reflected in 'color-scheme'), or if they're doing something novel and not reflected in any spec.

@smfr, @hober, @dino, can y'all figure this out for me? WebKit invented this feature and shipped it before a spec existed, so we've been forced to specify it after-the-fact by reverse engineering. If we've gotten it wrong, please tell us how.

**Comment by smfr** [comment]
I don't think WebKit is doing anything novel. We just have light and dark modes, no forced colors.

**Comment by xeenon** [comment]
The `color-scheme` property allows iOS and macOS Mail know which color scheme to use for an email message, as it can affect the auto-darkening transformations that get applied to the message’s colors. Declaring color-scheme: light dark in a rich email message lets Mail know it supports its own styling for dark mode. You can also specify light only, informing Mail that it should not transform your light color scheme email message.

**Comment by tabatkins** [comment]
Okay, adjusted the title to reflect this.

Now that we've dropped the spec's *previous* definition of "only", which did *not* do what y'all are describing, we can discuss re-adding it to *do* what y'all are describing. ^_^

**Comment by smfr** [comment]
I'm not sure how "only" morphed. The [original proposal](https://lilles.github.io/specs/supported-color-schemes.html#supported-color-schemes) has:

> only
Ask the UA to use one of the listed color schemes when the UA preferred color scheme is not listed in the supported color schemes. This can typically be used force a dark theme rendering when the preferred color scheme is light.

**Comment by tabatkins** [comment]
It didn't morph (from that definition). That definition is "if the user preference doesn't match author preference, the author preference wins", which is exactly what the spec recently said (before I removed it this morning). That's also exactly what Safari does, if I'm understand you correctly. (Now it's the behavior of the spec in all cases, fwiw.)

The difference is if the author and user preferences don't match, but the author *didn't* use the "only" keyword.  Rune reverse-engineered the algo (8.2 in his proposal) to be "use the browser default in that case". Safari apparently actually does "auto-fix the author's colors to match the user preference".

This issue is now about: what are those auto-fixes, and should we specify that in the spec?

**Comment by AmeliaBR** [comment]
So, if we were to spec the Mac Mail behavior, my current understanding is that it would be something like:

> If the user's preferred color scheme is not among the listed color schemes (in the [`color-scheme` property](https://drafts.csswg.org/css-color-adjust/#color-scheme-prop)), the user agent **may** switch to `forced-colors` mode or otherwise modify the displayed colors to meet the user's preference (e.g., by using an inverted-color display).  The `only` keyword indicates that this type of modification is likely to be detrimental to the user experience.

There would need to be a note warning that `only` is just a suggestion: user agents may still use forced-color mode if that's what the user needs, and that all web content should be designed with that in mind. There should also be examples of sensible uses of `only` (e.g., color swatches on an store website, partially-transparent images that would disappear if the email's background color were inverted).

One other complication that would need to be defined: if you use `only` on a part of the page, how does that interact with [`forced-color adjust`](https://drafts.csswg.org/css-color-adjust/#forced), if a forced-color like effect gets applied to the rest of the page?

**Comment by AmeliaBR** [comment]
Also…

Since `forced-colors` is a media query, which could be used to set `color-scheme`, which could affect whether or not the browser decides to opt in to a forced colors-like scheme, how do we deal with this circularity? Maybe the decision to do a fix-up / forced color change based on the `color-scheme` meta tag only, and `forced-color-adjust` (rather than an `only` keyword in the `color-scheme` property) would still be required if you wanted to opt-out parts of the page.

Do the Mail / WebKit color adjustments currently apply on the whole page only, or do they support the CSS `color-scheme` on subtrees?

**Comment by lilles** [comment]
Android WebView has an API for doing auto-darkening for the whole document. We opt out of auto-darkening if the used color-scheme on the root element is 'dark'. The 'only' keyword has no effect.

**Comment by xeenon** [comment]
Mail / WebKit color adjustments currently apply on the whole page only.

**Comment by tabatkins** [comment]
Agenda+ to request that we defer this unless/until browsers start wanting to ship auto-darkening.

**Comment by tabatkins** [comment]
@smfr The spec originally reflected your original proposal (#3299) quite closely. IIRC, we ended up deciding to fold the "auto-darkening" part into FCM, since that was doing essentially the same thing, and trying to slice hairs on what sort of forced adjustments were "color-scheme" and which were FCM didn't seem particularly useful.

Then, without forced adjustment happening, the interaction of user and author preferences and how that changed when `only` was missing or present ended up really over-complicated, so we chopped it down to the model the spec has today.

Do you still feel that FCM isn't appropriate to model auto-darkening? If so, could you explain in more detail? And are the details of what auto-darkening does different from what FCM is specified to do?

**Comment by tabatkins** [comment]
For reference: #3881 is where we resolved to remove the "only" keyword. You can infer from the discussion there that we'd already settled on the auto-adjusting happening elsewhere (from FCM, instead), and this issue was us gradually realizing that without auto-adjusting, "only" wasn't doing anything useful.

**Comment by tabatkins** [comment]
Ah yeah (sorry for the serial comments, y'all, I'm trying to unwind this into a coherent thread), in [a comment upthread](https://github.com/w3c/csswg-drafts/issues/5089#issuecomment-634931195), I asked:

> This issue is now about: what are those auto-fixes, and should we specify that in the spec?

And nobody from Apple responded with details. @xeenon [responded](https://github.com/w3c/csswg-drafts/issues/5089#issuecomment-650821600) with "Mail / WebKit color adjustments currently apply on the main frame only." to a comment from Rune about Android's exploration of auto-darkening, but that's all we've got so far.

So, @smfr or @xeenon or @dino or anyone else, could we get details on what exactly auto-darkening entails, particularly if/how it differs from [Forced Colors Mode](https://drafts.csswg.org/css-color-adjust/#forced)?

**Comment by tabatkins** [comment]
Been discussing a bit with some other engineers.

Looks like currently, we have at least three independent auto-darkening efforts:

* iOS auto-darkens web content in some apps, such as Mail, but not (yet?) in general Safari
* Samsung auto-darkens web content in general (if you turn on a pref, I presume?)
* Chrome Webview has an option to enable auto-darkening, and we have a flag on Canary that can flip it on for arbitrary web content

So this is more widespread than I'd thought, and we do indeed need some spec text for it. And none of the three 
I'm aware of do this via a mechanism resembling Forced Colors Mode, as the spec currently assumes.

At *bare minimum*, we need the following:

1. Describe when auto-darkening can happen.
2. Describe how to opt-out of it.

Ideally, we'd additionally have a well-specified algorithm for how auto-darkening works. Without that, authors might test their page in one browser, note that the auto-darkening gives an acceptable result, and leave it be without writing an explicit dark theme; then in another browser with a different auto-darkening mechanism, it might look broken. That's bad for everyone! But I recognize this is still the early days, and specific details of how to do it best might still be too up in the air to nail down in spec text yet.

----------

So I propose:

1. Specify that if the user's preferred color-scheme is *not* present in the list of 'color-scheme' keywords, 
	the user agent *may* make the user's preferred color scheme a "forced color scheme".

	A "forced color scheme" will at minimum have [the effects specified for 'color-scheme' currently](https://drafts.csswg.org/css-color-adjust/#color-scheme-effect), such as adjusting browser UI and setting the system colors appropriately. It may have arbitrary additional effects, currently explicitly undefined, on colors and/or images on the element.

	However, if the user's preferred color-scheme *is* present, this won't happen, and you'll *just* the specified effects for the used color-scheme.

2. Re-add the "only" keyword to opt-out of "forced color scheme" on the element.

**Comment by tabatkins** [comment]
Re-adding Agenda+ to discuss the proposal above, hopefully resolving on that as the direction.

**Comment by chrishtr** [comment]
I think this amounts to the same resolution already arrived at this morning, right? i.e. "Re-add **only** to mean "don't auto-adjust me", per WebKit's behavior", meaning `only` is an opt-out of a browser heuristic.

**Comment by tabatkins** [comment]
It's definitely implementing the gist, I just want to make sure the group is fine with the specifics. ^_^

**Comment by tabatkins** [comment]
Okay, @fantasai and I drafted up an initial spec for "only" and auto-adjustment. Commit is <https://github.com/w3c/csswg-drafts/commit/20a7101b4f1e93d35e7a6814324f8fd33d3b581f>, and it'll show up in the drafts server shortly.

@smfr, @chrishtr, @xeenon, mind reviewing?

**Comment by chrishtr** [comment]
Reviewed and left two comments, one a nit. Otherwise looks great to me.

**Comment by smfr** [comment]
Some info on auto-darkening in Apple Mail: the intent is to change the appearance of email content from light to dark, but in a way that preserves some of the authoring intent. It does this by inverting the perceived lightness of CSS colors at paint time, while mostly preserving the color hue. Some CSS colors ("system colors") are not inverted, but use values supplied by the OS which have specific dark-mode values (like the quoted text colors for example). Images are not inverted and their presence may disable auto-darkening, but this could change in future.

This differs from forced colors mode in that some authoring intent is preserved; the user is not in control of the colors.

**Comment by smfr** [comment]
Another nuance in the original proposal which I want to make sure is captured: we didn't want to write it with the assumption that "light" and "dark" would be the only modes available. It allowed for the UA to have a mode that authors were not aware of, and for content to have modes that a UA did not support. For example, if an author said `color-scheme: light dark` and the UA had a `sepia` mode that was active, we wanted to allow the UA to apply `sepia` (presumably by picking the light mode, and then applying adjustments). `only` was included to allow the. author to preclude the UA from doing any conversions to modes which they had not specifically authored for.

**Comment by tabatkins** [comment]
> Some info on auto-darkening in Apple Mail [snip]

Yup, this should all be allowed by the spec text. I think it's important to *eventually* standardize, at least roughly, on what "auto-darkening" means (authors are going to end up depending on the behavior, and having it standardized is thus better for users of browsers the authors didn't test on), but for now it's wide-open. The only requirement is that you *do* apply the "used color scheme" changes exactly as specified, but you can do whatever else you need to the colors/images on the element in addition.

> Some CSS colors ("system colors") are not inverted, but use values supplied by the OS which have specific dark-mode values

Yeah, there's no actual "inverting" specified; I presumed that Chris was using the term generically to mean "switched to a dark-mode set". The "used color scheme" details make it clear that the UA just needs to change the system colors to be appropriate to the chosen color scheme, but puts no restrictions on what those colors might be.

> Images are not inverted and their presence may disable auto-darkening, but this could change in future.

This is allowed; the spec is intentionally very vague about what triggers "override the color scheme", just that the user indicates they have an overriding preference, and the UA *may* do something about it.

> Another nuance in the original proposal which I want to make sure is captured: we didn't want to write it with the assumption that "light" and "dark" would be the only modes available.

Don't worry, the spec is still written generically in this respect, with the assumption that additional color schemes can be added in the future.

> `only` was included to allow the. author to preclude the UA from doing any conversions to modes which they had not specifically authored for.

Yup, that's exactly what it does. The "override the color scheme" behavior can only happen if the author doesn't say "only"; if they do, then they're guaranteed to get a color scheme from the ones they listed (assuming the UA supports one of them), with no adjustments besides the necessary ones specified by the "used color scheme".

**Comment by smfr** [comment]
I'm fine with the proposal in https://github.com/w3c/csswg-drafts/issues/5089#issuecomment-844525850
