### ISSUE TITLE
[css-scoping] [selectors] <compound-selector-list> should somehow affect :is() / :where() parsing

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5093]
https://drafts.csswg.org/css-scoping/#host-selector takes a `<compound-selector-list>` (that is, doesn't accept combinators). This is good, as otherwise it'd break the shadow tree encapsulation.

However strictly per the syntax technically something like `:host(:is(div div))` should parse. I think this is a spec bug.

**Comment by emilio** [comment]
Maybe `:is()` and `:where()` should be more subtly defined. I'd expect `::part(foo):is(:hover,:active)` to parse, just like the individual selectors would, but I don't think `::part(foo):is([attr="value"])` should parse.

**Comment by emilio** [comment]
This may also be an issue for pseudo-elements, so `::pseudo:is(:hover)` may be fine, but `::pseudo:is(p)` doesn't make sense.

**Comment by andruud** [comment]
Also, should `::pseudo:is()` allowed?

I think probably yes (but matches nothing).

**Comment by tabatkins** [comment]
@fantasai checked in an edit to fix this:

> The [=logical combination pseudo-classes=]
> are allowed anywhere that any other [=pseudo-classes=] are allowed,
> but pass any restrictions to their arguments.
> (For example, if only [=compound selectors=] are allowed,
> then only [=compound selectors=] are valid within an '':is()''.)

Just need CSSWG thumbs-up for the edit.
