### ISSUE TITLE
[css-borders-4] `border-color` property's grammar doesn't agree with its example

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5103]
From https://drafts.csswg.org/css-backgrounds-4/#the-border-color:

> Name: | border-color
> -- | --
> Value: | `<color>#{1,4}`

The `#{}` syntax is [defined](https://drafts.csswg.org/css-values-4/#component-multipliers) as such:
> A hash mark (#) indicates that the preceding type, word, or group occurs one or more times, separated by comma tokens ... It may optionally be followed by the curly brace forms, above, to indicate precisely how many times the repetition occurs, like `<length>#{1,4}`.

But then css-backgrounds-4 goes on to list an example:

> `border-color: skyblue orange yellowgreen indianred, black yellow;`

I don't think this example conforms to the property's grammar according to the definition listed above.

**Comment by SebastianZ** [comment]
So it looks like the syntax should rather be `<color>{1,4}#` or `[ <color>{1,4} ]#`.

Sebastian

**Comment by fantasai** [comment]
@litherum ... Just so you know, I don't think this is a spec that should be referenced by anybody right now. ^_^;; It's got a "don't implement yet" warning and isn't FPWD for a reason.

Agreed there's an error here, but I think the resolution was to change the grammar to `background-color: [ <color> | <image-1D> ]{1,4}`.

**Comment by SebastianZ** [comment]
> Agreed there's an error here, but I think the resolution was to change the grammar to `background-color: [ <color> | <image-1D> ]{1,4}`.

It's `border-color`, but yes. It got changed to `[ <color> | <image-1D> ]{1,4}` meanwhile. So this issue is solved now.

Sebastian
