### ISSUE TITLE
[css-speech] Make `speak: auto` respond to `visibility`

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#511]
Issue reported by Matt King and Jesse Beach: the `auto` value of `speak` should respond to `visiblity` as well as `display: none`.

**Comment by Crissov** [comment]
… or should there be `audability`?

**Comment by aaaxx** [comment]
Related: #560.

**Comment by bocampbell** [comment]
Passed around IBM Accessibility group. Positive feedback, no objections.

**Comment by fantasai** [comment]
This was resolved to accept in https://lists.w3.org/Archives/Public/www-style/2017Feb/0004.html
