### ISSUE TITLE
[css-2020] Should cascade 3 and 4 both be in the snapshot?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5111]
(Following up form https://github.com/w3c/csswg-drafts/issues/4715#issuecomment-629066522, as that's a bit of a separate topic from the overall 4715 issue).

In https://github.com/w3c/csswg-drafts/issues/4715, we agreed to include cascade 4 in the snapshot. Cascade-3 is already there though.

I don't think anything in cascade 3 is wrong, but it is a little confusing to list both as being the official definition.

Should we just drop cascade 3 from the snapshot?  Should we move it to a (newly created) section that lists specs that are stable and correct, but retired due to being superseded by newer ones?

That sort of seems useful, to distinguish such specs from other old RECs which are unmaintained and wrong. People should be reading cascade-4, but they're not going to run into problems if they read cascade-3. On the other hand, the same isn't true about reading CSS2.0 instead of CSS2.1.

**Comment by AmeliaBR** [comment]
The snapshot [already mentions](https://drafts.csswg.org/css-2020/#css) that level 4 supersedes level 3, (just as it mentions that other specs replace certain sections of CSS 2.1):

> CSS Cascading and Inheritance Level 4 [CSS-CASCADE-4]
> Extends and supersedes [CSS-CASCADE-3], describing how to collate style rules and assign values to all properties on all elements. By way of cascading and inheritance, values are propagated for all properties on all elements.

But it would be helpful, at the very least, to edit the entry for level 3 to indicate that it is fully superseded. And maybe to group the two together in the list, so it is easier to see them as a pair.

But dropping fully superseded specs, or creating a separate list of them, makes sense too.

> to distinguish such specs from other old RECs which are unmaintained and wrong

That would be the distinction [in the W3C process](https://www.w3.org/2019/Process-20190301/#rec-rescind) between a “superseded” spec and an “obsolete” one. I don't know if we want to mention obsolete specs at all in the snapshot, though.

**Comment by fantasai** [comment]
I think for snapshot purposes, we only need to link to the latest one that qualifies.

**Comment by frivoal** [comment]
Done in https://github.com/w3c/csswg-drafts/commit/cfedc276ad8a3ca5ea8cbee9962c27f2a09b3afa
