### ISSUE TITLE
[css-inline-3] initial-letters-wrap: first, whitespace collapse needs defining

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#5120]
See https://drafts.csswg.org/css-inline-3/#example-8c68c539

```html
<style>
p::first-letter {
    initial-letters: 3 3;
    initial-letters-wrap: first;
}
</style>
<p>A bout of illness...</p>
```

In the example shown above, the visual effect is that the "b" of "bout" is left aligned to the right edge of the initial-letters box. The whitespace preceding "bout" is discarded.

This appears to be by design (@dauwhe can perhaps confirm one way or another). But what is the mechanism for this whitespace collapse? Does it collapse when `white-space: pre`? Do we collapse just one space, or many? Is it all characters of class Zs?

I am leaning towards collapse all Zs, all the time in this case. I could imagine `white-space` other than normal might be used for poetry layout, for example, but even then it seems likely the word following the initial letter has to be aligned with the box. If more control is desired, authors have `shape-margin`.

**Comment by fantasai** [comment]
Generally we only collapse collapsible white space, so I imagine that's what we'd do here as well. Is there a use case for collapsing other Zs ?

**Comment by fantasai** [comment]
https://www.w3.org/TR/css-text-3/#white-space-rules

**Comment by faceless2** [comment]
To me it looks like the whitespace isn't exactly collapsing here - it's represented by the space between the initial letter and the rest of the box. At least, that's my understanding of the intention - I don't have a concrete use case.

But yes, I suppose it is probably simplest if it's treated as if it were white-space at the start of a line, and then follow the normal rules for collapsing at this point. I still think this needs stating explicitly, as according to the box model it's collapsing zero or more whitespace between two inlines to nothing, which wouldn't normally happen.

**Comment by fantasai** [comment]
@faceless2 Agreed it needs to be specified explicitly. (And it's collapsing because it's not there; spaces represented by a line break are also considered to be collapsed. ;)

**Comment by dauwhe** [comment]
> This appears to be by design (@dauwhe can perhaps confirm one way or another).

Yes, by design. 

Isn't this something of an issue for all initial-letters? WebKit seems to ignore any white space between the initial letter and subsequent text. Could this be a general rule? All I'm saying with `initial-letter-wrap: first` is that if there is whitespace between the initial letter and subsequent text, don't wrap that first line.

**Comment by faceless2** [comment]
Ha. Yes, I suppose it is an issue for all initial-letters. This is the only example from the spec where the first letter is followed by a space, which is probably why it didn't occur to me.

So same conclusion I guess, but applied to a broader subject: we collapse white-space following the initial letter as if it were at the start of the line.

**Comment by fantasai** [comment]
So... here's a question. What about a raised initial? Don't we need to preserve white space when the sink is 1?

**Comment by dauwhe** [comment]
> So... here's a question. What about a raised initial? Don't we need to preserve white space when the sink is 1?

Yes. 

I also wonder about justified text on a line with an initial letter. Even if it's a pure raised cap, if the initial letter is a standalone, the space after it should probably be available for justification.

**Comment by fantasai** [comment]
@dauwhe OK, so the proposed behavior is: “if sink > 1, collapse away any white space”?

**Comment by johannesodland** [comment]
There are some examples where the first line run into the initial letter when sink > 1: 

http://www.typografi.org/dropcaps/assets/sideeksempel_760px_bred.jpg
http://www.typografi.org/dropcaps/initialer.html
http://theworldsgreatestbook.com/book-design-part-6/

If white-space is automatically collapsed, wouldn't these designs be impossible?
