### ISSUE TITLE
[cssom] is setting Element.style as a string specified anywhere? ElementCSSInlineStyle only has the getter

### ISSUE THREAD

**Issue by pygy** [w3c/csswg-drafts#5127]
I'm coming at this from https://github.com/microsoft/TypeScript/issues/13466 which correctly points out that there is no setter for `style` in the old spec for `ElementCSSInlineStyle`. TS stops at that, and setting `HTMLElement.style` is thus a type error (same for `SVGElement`, both inherit from the mixin).

So I went out fishing for a spec for the setter and came out empty handed. The new CSSWG spec also lacks a setter... Is there such a thing, somewhere?

**Comment by Loirooriol** [comment]
Yes, in CSSOM: https://drafts.csswg.org/cssom/#elementcssinlinestyle

```webidl
interface mixin ElementCSSInlineStyle {
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
```

Where `PutForwards=cssText` means (https://heycam.github.io/webidl/#PutForwards)

> If the [PutForwards] extended attribute appears on a read only regular attribute declaration whose type is an interface type, it indicates that assigning to the attribute will have specific behavior. Namely, the assignment is “forwarded” to the attribute (specified by the extended attribute argument) on the object that is currently referenced by the attribute being assigned to.

**Comment by emilio** [comment]
Yes, `[PutForwards]` is what does the magic here.

**Comment by pygy** [comment]
Thanks Emilio!
