### ISSUE TITLE
[css-overflow] Should `overflow-clip-margin` take percentages?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5130]
When we resolved in #4934 to introduce `overflow-clip-margin`, we did not discuss whether it should take a `<length>` or a `<length-percentage>`.

`margin` takes a `<length-percentage>`, but [the new spec text](https://drafts.csswg.org/css-overflow-3/#overflow-clip-margin) defines `overflow-clip-margin` to take a `<length>`. We didn't discuss that point. On the one hand, analogy with `margin` would suggest `<length-percentage>`. On the other hand, `overflow-clip-margin` is mainly expected to be used to account for things like shadows and outlines, which do not take percentages. I'm leaning towards leaving it as a `<length>`, but not 100% sure, and we didn't discuss.

**Comment by fantasai** [comment]
Let's just take a `<length>`. I don't think the use cases presented so far indicate the need for a percentage.

**Comment by tabatkins** [comment]
Yup, I intentionally omitted percentage due to lack of use-case; as you say, the things that you mainly need to worry about clipping don't take percentages anyway.  We can add it later if necessary.

**Comment by chrishtr** [comment]
Closing per comments above as no change.
