### ISSUE TITLE
How to refer to the corner-shaped padding/border/content edges

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5132]
Are the padding/border/content edges rectangular, and then border-radius / corner shaping gets applied, yielding the ???? (shaped padding/border/content edges ?), or are padding/border/content edges themselves modified by border-radius / corner?

In other words, when you want to refer to the shaped padding edge, do you just use cross-ref to padding edge, and let other specs work their magic to shape that appropriately, or do you have to refer to border radius and other kinds of corner shaping?

Reading https://drafts.csswg.org/css-box-4/, there's no mention of radius, corners, or shapes, so that would lead me to believe that the padding/border/content edge are rectangular, and if you want the shaped version, you have to invoke that yourself (or find some term that does that, but I couldn't find it).

On the other hand, https://www.w3.org/TR/css-backgrounds-4/#the-border-radius, seems to suggest that the padding/border/content edge themselves do get shaped, which would mean that you don't need to reach for extra terminology or invoke the effect explicitly.

In addition to being verbose, having to explicitly invoke the effect yourself means that any spec that wants to talk about these edges needs to take a dependency not just on backgrounds-3, but also backgrounds-4 to make sure corner-shape is accounted for as well, and possibly future specs if we add more things later.

I'd suggest that css-box-4 should introduce the terms `shaped padding/border/content edge` and `unshaped padding/border/content edge`, in addition to the existing ambiguous terms that can continue to be used in the cases where the difference doesn't matter. css-box-4 would explicitely depend on css-background-3 to take border-radius into account, but need not depend on backgrounds-4 for `corner-shaping`: backgrounds-4 can itself use that new terminology to say that it modifies it.

**Comment by LeaVerou** [comment]
I've sent regrets for todayi's call but I'm fine with the proposed change.

**Comment by astearns** [comment]
adjusted/unadjusted?

**Comment by frivoal** [comment]
Captured in the minutes, but not in the resolution: We're specifically looking for an adjective to qualify the "???? padding/border/content edges", so that the term without the adjective can remain in common use for the cases where that distinction doesn't matter.

**Comment by frivoal** [comment]
> adjusted/unadjusted?

Doesn't  conflict with anything, so that's good, but it seems very generic, and it doesn't seem obvious to me: "adjusted in what way?". Cross linking with the spec defining it will help, but a transparent term would be better IMHO.

**Comment by fantasai** [comment]
“corner-shaped xxx edge” vs “unshaped xxx edge” with “xxx edge” as the ambiguous term?

**Comment by fantasai** [comment]
I went with “shaped edge” and “unshaped edge”. Agenda+ to confirm and republish.
