### ISSUE TITLE
[css-flexbox] Prose about white space characters links to the white-space property

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#5146]
https://drafts.csswg.org/css-flexbox/#flex-items
> However, if the entire sequence of child text runs contains only [white space](https://www.w3.org/TR/CSS2/text.html#white-space-prop) (i.e. characters that can be affected by the [white-space](https://drafts.csswg.org/css-text-4/#propdef-white-space) property) it is instead not rendered (just as if its [text nodes](https://drafts.csswg.org/css-display-3/#text-nodes) were display:none).

The first link is to https://www.w3.org/TR/CSS2/text.html#white-space-prop which is for the `white-space` property in CSS2. It doesn’t (directly) define a set of characters. Should this link go to https://drafts.csswg.org/css-text/#white-space instead?

**Comment by fantasai** [comment]
@SimonSapin Yes. Done. (I suspect css-text-3 wasn't mature enough to use as a reference when this was drafted up.)
