### ISSUE TITLE
[css-sizing-4] Should aspect-ratio be used for abspos `top: 0; bottom: 0;`?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#5151]
https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes
https://drafts.csswg.org/css-sizing-4/#aspect-ratio

In this code:
```html
<div style="width: 500px; height: 100px; position: relative;">
  <div style="background: green; aspect-ratio: 1/1; position: absolute; left: 0; top: 0; bottom: 0;"></div>
```

Should the width be computed using the aspect-ratio, since top and bottom establish a size that could be used?

Note that the first link says not to:

> For boxes with an intrinsic aspect ratio, but no intrinsic size:
>If the available space is definite in the inline axis, use the stretch fit into that size for the inline size and calculate the block size using the aspect ratio.

**Comment by cbiesinger** [comment]
cc @fantasai

**Comment by fantasai** [comment]
Interesting question. I'd say yes, it should, since `right` is `auto`. But I think the specs are not clear on that point, and we should fix them.

**Comment by Loirooriol** [comment]
Note that this produces a 500x500 box (not 100x100) in both Firefox and Chromium:

```html
<div style="width: 500px; height: 100px; position: relative;">
  <svg viewBox="0 0 1 1" style="background: green; position: absolute; left: 0; top: 0; bottom: 0;"></svg>
```

**Comment by tabatkins** [comment]
Talking with @fantasai and @cbiesinger, we're optimistic that we can change that specific behavior (replaced element with only an aspect ratio, with three abspos sides specified) to instead use the 100px height as its major dimension and treat width as ratio-dependent (producing a 100x100 image)

**Comment by fantasai** [comment]
Drafted some wording for this in https://github.com/w3c/csswg-drafts/commit/9594b70729ff481ea933a3e3d07a85423122e0eb

Agenda+ to review with the CSSWG.
