### ISSUE TITLE
[css-pseudo-4] ::first-letter should include space separators

### ISSUE THREAD

**Issue by johannesodland** [w3c/csswg-drafts#5154]
Some languages requires a space separator between the first-punctuation and the first letter. Both the punctuation and the space separator should be included in the ::first-letter pseudo element.

Browsers treat this differently at the moment. Safari includes spaces, while Chrome does not. 
https://bugs.chromium.org/p/chromium/issues/detail?id=638267.

At the moment the spec does not specify that space should be included: https://www.w3.org/TR/css-pseudo-4/#first-letter-pseudo

Examples: 

**French**
The opening quotation mark in French cannot go without a space: 
« Voulez-vous un sandwich, Henri ? » 

Source: https://en.wikipedia.org/wiki/Quotation_mark#French

**Norwegian**
Some quotation marks in Norwegian (replikkstrek) cannot go without a space: 
– Pettersen, ropte hun, – kom inn og få kaffe. 

Source: https://www.sprakradet.no/sprakhjelp/Skriveregler/tegn/Tankestrek/

**Comment by johannesodland** [comment]
See #2040 for suggested `::first-punctuation` pseudo class.

**Comment by johannesodland** [comment]
The following example can be used to test how different browsers renders the ::first-letter pseudo element:

https://codepen.io/johannesodland/pen/LYGYWyY

**Comment by johannesodland** [comment]
This 10 year old bugzilla issue describes the same thing:

https://bugzilla.mozilla.org/show_bug.cgi?id=602459

**Comment by fantasai** [comment]
Current spec prose for reference: 

> Punctuation (i.e, characters that belong to the Punctuation (P*) Unicode general category [UAX44]) that precedes or follows the first typographic letter unit must also be included in the ::first-letter pseudo-element.

I believe the pattern we want to collect is: ` (P+Z*)?[LN]+(Z*P+)?` (where each letter stands for its Unicode category). So proposed wording:

> Punctuation (i.e, characters that belong to the Punctuation (P*) Unicode general category [UAX44]) that precedes or follows the first typographic letter unit<ins>, as well as any intervening space separators (characters that belong to the Spaces (Zs) Unicode general category),</ins> must also be included in the ::first-letter pseudo-element.

Agenda+ to confirm.

**Comment by dbaron** [comment]
If that was supposed to be regular-expression-ish, I'd have expected the equivalent of the prose to be something more like (with slightly different notation) `([P]+[Zs])*([L]|[N])([Zs][P]+)*`.

**Comment by r12a** [comment]
(I think your grammar also needs to indicate that this appears at the beginning of the paragraph.)

**Comment by fantasai** [comment]
@r12a The grammar isn't going into the spec, and the spec already anchors it to the first Letter/Number.

**Comment by fantasai** [comment]
@johannesodland So Tantek insists on seeing real-world examples where this behavior is necessary, since he doesn't believe the change is worth making to the spec otherwise. Do you happen to have any examples of existing typography showing the desired behavior?

**Comment by plinss** [comment]
I think another important aspect is, are there use cases/examples for *not* including spaces in the first letter? e.g. is there existing content where someone deliberately put a space after punctuation so that the following letter was not considered to be in the ::first-letter. In english at least, I can't come up with a valid use case where this would be desirable, where I can come up with use cases where the space should be included.

If there are valid use cases in both directions, then perhaps we need an additional control to determine what's included in ::first-letter.

**Comment by r12a** [comment]
I'll look around for some examples. Perhaps i can rope in some help from folks in France, but Florian may also know where to look. 

One thing to consider: the space between punctuation and text in French is commonly not an ordinary space, but rather a NNBSP or other such thinner spaces.  We might, just a thought off the top of my head, want to consider whether only these types of space trigger the text to be kept together – which would probably address the concern of @plinss  for false positives, _if_ that turns out to be a significant concern, but we'd also need to ensure that those spaces are captured in any rules.

Wrt current behaviour, i have some results and a link to a test that cover the 3 main engines and 3 types of space, at https://github.com/w3c/line_paragraph_tests/issues/54.

**Comment by TalbotG** [comment]
Just to be sure... 
**::first-letter should not apply to initial spaces**, according to the following test and its author, Ethan Malasky

http://wpt.live/css/css-backgrounds/first-letter-space-not-selected.html

its reference
http://wpt.live/css/css-backgrounds/reference/first-letter-space-not-selected-ref.html

In my opinion, the test above is correct.


::first-letter applying to PunctuationCharacter+Space+LetterOrNumber is different and can make sense (depending on language). 

According to Unicode, there are many kinds of spaces (gc = Zs) and many kinds of punctuation characters which would eventually apply regarding this issue:

Code   Name
U+0020 space
U+00A0 no-break space
U+1680 ogham space mark
U+2000 en quad
U+2001 em quad
U+2002 en space
U+2003 em space
U+2004 three-per-em space
U+2005 four-per-em space
U+2006 six-per-em space
U+2007 figure space
U+2008 punctuation space
U+2009 thin space
U+200A hair space
U+202F narrow no-break space
U+205F medium mathematical space
U+3000 ideographic space

Pc 	Connector_Punctuation a connecting punctuation mark, like a tie
Pd 	Dash_Punctuation 	a dash or hyphen punctuation mark
Ps 	Open_Punctuation 	an opening punctuation mark (of a pair)
Pe 	Close_Punctuation 	a closing punctuation mark (of a pair)
Pi 	Initial_Punctuation 	an initial quotation mark
Pf 	Final_Punctuation 		a final quotation mark
Po 	Other_Punctuation 	a punctuation mark of other type

**Comment by xfq** [comment]
FWIW, here are some examples of first letter styling in French:

![example1](https://user-images.githubusercontent.com/2863444/87621536-95f07c00-c753-11ea-8f28-ddf690df902f.png)

-----

![example2](https://user-images.githubusercontent.com/2863444/87621547-9ab53000-c753-11ea-993f-e4e2ada34f96.jpeg)

-----

![example3](https://user-images.githubusercontent.com/2863444/87621650-d5b76380-c753-11ea-9cfe-39e3ad5307b5.png)

-----

References:

* http://www.mobileread.mobi/forums/showthread.php?t=119418&page=23#post2479698
* https://twitter.com/sophianf/status/740835674522275840 (this one looks like a ligature)
* https://manualzz.com/doc/20239639/quelques-exemples-de-lettrines

**Comment by dbaron** [comment]
Of those three examples ("— « M", "«L'", and "«E"), only the second one (the L) seems doable with `::first-letter`, since the first and the third have the punctuation sized with the non-drop-cap text, and the third is also aligned with it.  The third also pretty clearly doesn't have a space, though the first looks like it probably does, and I think the second perhaps does not.

**Comment by johannesodland** [comment]
Typografi.org has an example of the norwegian remark punctuation ("replikkstrek"). It can be seen in the following sentence:

– Bare vent litt, jeg må fange en squirtle her.
http://www.typografi.org/dropcaps/assets/sitatstrek-anf%C3%B8rselstegn_714.jpg
http://www.typografi.org/dropcaps/initialer.html

The author notes that the preferred option is to style the punctuation away. To be able target punctuation for styling we also need the ```::first-punctuation``` suggested by @fantasai in https://github.com/w3c/csswg-drafts/issues/2040.

**Comment by johannesodland** [comment]
I'll write a few words about why I brought up this issue. 

I work in the norwegian public broadcasting company. We've tried to use the ```::first-letter``` to style drop caps but it fails. Sentences starting with "remark punctuation" (– Bare vent litt)  is prominent in news and magazine-style articles. But whenever ```::first-letter``` is applied to these sentences the results is inconsistent between browsers, and the desired effect is not achieved. 

In an article we published in 2017 we deliberately changed the language and dropped starting sections with these sentences to avoid this problem: https://www.nrk.no/sperret-inne_-slatt-og-lenket-fast-1.13769828

Typography literature tells us to hide the punctuation, or move it into the margins (hanging punctuation). Most examples I can find in todays print newspapers hide the punctuation. (typography teaching book from 1952: https://www.nb.no/nbsok/nb/a627d2b30ca616ba40bcd2100bf63e1f?index=3#59)

On the web we can not simply remove the punctuation. We need to support older browsers and progressively enhance the layout. The punctuation can be hidden only when ```::first-letter``` is supported.

Including space separators in ```::first-letter``` will not solve the problem with hanging or hidden punctuation, but it will be a necessary step on the way. A ```::first-punctuation``` would be really helpful. 

I fear that if ```::first-letter``` does not support space between the punctuation and the letter, it will be unusable for the Norwegian language.

**Comment by johannesodland** [comment]
The meeting mentions compat between Gecko and Blink.

I don't think theres compat between Gecko and Blink. They treat punctuation and space somewhat differently. 

**Chrome:**
Does not include any characters when sentence starts with "« ". Includes the punctuation but not the space and the following character when starting with "– ".

<img width="255" alt="Screenshot-Chrome" src="https://user-images.githubusercontent.com/175195/88254014-08adaa00-ccb4-11ea-950d-5b6e1f2af3af.png">

**Firefox:**
Does not include any characters when sentence starts with "« " or "– ".

<img width="255" alt="Screenshot–Firefox" src="https://user-images.githubusercontent.com/175195/88254022-0b100400-ccb4-11ea-872b-9a492499b787.png">

**Safari:**
Includes punctuation and space when starting with "« ". Only includes punctuation when starting with "– ".
<img width="377" alt="Screenshot-Safari" src="https://user-images.githubusercontent.com/175195/88254019-09ded700-ccb4-11ea-9069-9441120759d2.png">

**Comment by fantasai** [comment]
@dbaron Wrt https://github.com/w3c/csswg-drafts/issues/5154#issuecomment-659160837 this distinction appears in languages (like English) that don't use spaces between the quote mark and the drop-cap, and is an issue against `initial-letter` currently, see issue #2040. If you're going to take that as a reason to make a distinction here that excludes the punctuation from ::first-letter, then logically we would have to do the same thing also where there is no intervening space.

**Comment by johannesodland** [comment]
> <astearns> I think we should allow the regular space, even though I'm fussy about typography
> <TabAtkins> florian: At least in French, it's pretty common to say ordinary spaces, probably same in Norwegian. So I'd include standard space.

We use a regular space between the punctuation and the first letter in norwegian: 
`– Pettersen, ropte hun, – kom inn og få kaffe.`


> <florian> http://www.typografi.org/dropcaps/assets/sitatstrek-anf%C3%B8rselstegn_714.jpg
> <TabAtkins> florian: So in this example we actually do want the included thing to be large.
> <TabAtkins> florian: In other cases we wont' want the punct large, but those apply equally to the exisdting punct-letter without space.

There are several examples where the punctuation is styled with the same size as the letter. The author notes that it's preferable to hide the punctuation, as in the lower example. Sometimes the punctuation is styled smaller and placed into the margin. I think the best thing would be to support all three versions. This issue should be seen together with #2040

**Comment by johannesodland** [comment]
Received two more examples from norwegian print: 
One with `«` and one with `–`. Note that there is a regular space between the `–` and the `J` in the text:  `– Jo, eg tror me gjer det`


![ex2](https://user-images.githubusercontent.com/175195/89707431-20e91e80-d96e-11ea-82fd-b9bdec0d1540.jpg)

![ex1](https://user-images.githubusercontent.com/175195/89707428-1c246a80-d96e-11ea-9ca3-ec122ab9323e.jpg)

**Comment by fantasai** [comment]
@johannesodland Thanks for the ping. :) And also all of the great examples. Edits are in. I think the spec would benefit from a good example / illustrations. Do you think you could hack your examples in https://github.com/w3c/csswg-drafts/issues/5154#issuecomment-662822822 to look the way they *ought* to, and we can include them in the spec?

**Comment by johannesodland** [comment]
@fantasai Sorry for answering this late. I didn't see the comment. 

I'm a little bit wary of adding the examples, because in the end one ought to adjust the style of the punctuation as well. This is tracked in https://github.com/w3c/csswg-drafts/issues/2040.

I have created a test-case of the examples here: https://github.com/web-platform-tests/wpt/pull/25828
These are based on the first-letter-004 tests. Maybe they are useful as examples?

**Comment by johannesodland** [comment]
I created a reference of the initial test-page here: 
https://codepen.io/johannesodland/pen/vYKYPjj
