### ISSUE TITLE
[css-text] Missing words in hyphenation: auto guidance

### ISSUE THREAD

**Issue by buttercookie42** [w3c/csswg-drafts#5156]
It seems like the [note regarding the behaviour of the `hyphenation: auto` property](https://drafts.csswg.org/css-text-3/#valdef-hyphens-auto) is possibly missing a word or two?
> Note: In some languages (such as English but not German), it may appropriate to avoid having hyphenation opportunities in mixed case words, as those may indicate proper nouns. This type of heuristic is however not mandated by this specification, as is up to the User Agent and its language-specific hyphenation resource.

should probably actually read
> Note: In some languages (such as English but not German), it may **be** appropriate to avoid having hyphenation opportunities in mixed case words, as those may indicate proper nouns. This type of heuristic is however not mandated by this specification, as **it** is up to the User Agent and its language-specific hyphenation resource.

?

**Comment by frivoal** [comment]
Good catch, thank you. This is now fixed.
