### ISSUE TITLE
[css-fonts-4] [varfont] Consider renaming "variation fonts" with "variable fonts"

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#516]
The official name for OpenType variation fonts are "variable fonts." However, TrueType used (uses?) the term "variation" instead.

"Variation" may be confusing because it is very similar to "Variant" which is used in the font-variant properties, which have nothing to do with variations.

"Variable" may be confusing because CSS Variables already exist and are completely unrelated.

**Comment by svgeesus** [comment]
A quick google shows "variable fonts" with lots of hits in the first few pages about the new OpenType 1.8 stuff and "variable fonts" with less hits, some about GX. So I have a weak preference for "variable fonts" as the name.

**Comment by litherum** [comment]
I think you typed "variable fonts" twice. Did you mean for one of those "variable fonts" to actually be "variation fonts"?

**Comment by behdad** [comment]
The team intended the technology to be called "OpenType Font Variations", and actual fonts "variable fonts".

**Comment by litherum** [comment]
TrueType GX fonts should still be able to be controlled with this new stuff. There's no reason to make this stuff OpenType-specific. (Same thing with font features - AAT fonts respond to features too)

**Comment by litherum** [comment]
The spec currently uses "font variations" in most places, which is correct. I fixed the incorrect uses and added a note for the terminology saying that the technology is "font variations" and an instance of one is a "variable font."

**Comment by litherum** [comment]
Also, because the properties should be named font-*, it is much more natural to write font-variation instead of font-variable. So I didn't rename the properties.
