### ISSUE TITLE
[scroll-animations] The selector() function vs. similar cases

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5166]
Not necessarily a spec issue, I'm just wondering why the `source` descriptor currently accepts `selector(<id-selector>)`, rather than just `<id-selector>`.

I'm not implying that it doesn't make sense or that it's somehow very bad, I just want to ensure that we're as consistent across specs as we can be. In particular, [nav-up (etc)](https://drafts.csswg.org/css-ui-4/#nav-dir) accepts an `<id>` directly. (Are there other similar cases)?

**Comment by andruud** [comment]
cc @majido

**Comment by SebastianZ** [comment]
There is also the `element()` function of CSS Images 4 that takes an ID selector.

I think always requiring a `selector()` function is more future proof, as it explicitly marks it and allows the it to be extended to take other selectors. Allowing the selector to be placed directly _may_ cause conflicts with keywords and other syntax definitions.
And of course it is more consistent to always use the same way to specify selectors.

So I vote for using `selector()` in `nav-up` and Co. and replacing `element()` by `selector()`.

Sebastian

**Comment by andruud** [comment]
Ah, thanks for pointing out `element()` @SebastianZ. Agree that direct selector isn't a good pattern. E.g. it's ambiguous if you have `<color> | <id>` and parse `#facade` against that grammar.

**Comment by majido** [comment]
FWIW, this was something the I brought about the syntax in F2F discussion when it was first proposed (See #4338). And the resolution was to use `selector()` instead of `element()` for the exact reasons @SebastianZ  pointed out. 

Closing since there is no other action AFAICT.

**Comment by SebastianZ** [comment]
> Closing since there is no other action AFAICT.

What is still needed is to update CSS UI 4 and CSS Images 4 to also use `selector()`.

Sebastian

**Comment by SebastianZ** [comment]
@majido Could you please reopen this issue, so it's not forgotten that CSS UI 4 and CSS Images 4 still need to be changed accordingly? Thank you!

Sebastian

**Comment by majido** [comment]
I can re-open this issue and tag the other spec but I worry that it may be confusing as the initial discussion is scroll-linked animations. Seems a better approach is to create a new issue and link back to this one for historical context. wdyt?

**Comment by SebastianZ** [comment]
> Seems a better approach is to create a new issue and link back to this one for historical context. wdyt?

It took me a few months 😅 but I finally created #5811 to discuss this separately.

Sebastian
