### ISSUE TITLE
[scroll-animations] @scroll-timeline in shadow trees

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5167]
Should we temporarily spec that `@scroll-timeline` is ignored in shadow trees, and add a note that this will change in the future? (See similar text in css-properties-values-api).

There is currently ongoing work in the WG regarding how @-rules and "name-defining things + references" in general should work in shadow trees, and it's a quite complicated problem to solve.

It doesn't really make sense to attempt to solve this "locally" via the scroll-animations spec, and the feature will be held back for a long time (probably) if we choose to block on this.

cc @majido

**Comment by tabatkins** [comment]
Yes, disallow until we finally get people to pay attention to the "at-rules in shadow trees" issue and solve it properly.

**Comment by majido** [comment]
+1 to @tabatkins suggestion. This was in fact something that was [discussed in F2F](https://github.com/w3c/csswg-drafts/issues/4338) when we resolved to use the @timeline rule. 

Making it clear in the spec sgtm.
