### ISSUE TITLE
[css-color-5] Add blurple as an official CSS color

### ISSUE THREAD

**Issue by magnus195** [w3c/csswg-drafts#5169]
We got a new color circulating the internet. It's a color everyone has seen but which doesn't work on CSS. I'm talking about **blurple**. I was trying to make a "Sign in with Discord" button and was shocked that it didn't exist.

It is the main color of Discord, but also pretty nice to look at. That's why I'm voting for adding it.
The color code for regular blurple is `#7289DA` or `rgb(114, 137, 218)`. Dark blurple is `#4E5D94` or `rgb(78, 93, 148)`.

![image](https://user-images.githubusercontent.com/22998711/83799717-825aeb80-a6a6-11ea-91a7-6d24182ff375.png)

**Comment by astearns** [comment]
We are not planning on adding any more named colors to CSS

https://wiki.csswg.org/faq#adding-more-named-colors
