### ISSUE TITLE
[css-fonts-4] [varfont] Applying a variation with font-variant-settings should actually clamp the applied value to the range the font supports

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#517]
For variation fonts, if you say something like: `font-weight: 814;` but the font file only supports weights of 400-700, then we should clamp 814 to that range and end up applying a weight of 700 instead.

**Comment by litherum** [comment]
This clamping should not occur for the low-level font-variant-settings property.

**Comment by Crissov** [comment]
We could also clamp only `<percentage>` values and always take `<number>` literally.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/2bf006e9dc9b863e6f457d77b2a4f4f223c8313a specifies how to do the clamping for `font-weight`, `font-stretch`, and `font-style`. Specifically, the clamping of those properties interact with font selection.

For font-optical-sizing, there is nothing to clamp because the values are just "none" and "auto".

As per https://github.com/w3c/csswg-drafts/issues/517#issuecomment-248776254, this clamping shouldn't occur for font-variation-settings.

Therefore, this should be done.

**Comment by behdad** [comment]
> For variation fonts, if you say something like: font-weight: 814; but the font file only supports weights of 400-700, then we should clamp 814 to that range and end up applying a weight of 700 instead.

The clamping happens in rendering software anyway.  However, what needs CSS support is IMO, if @font-face declares a range narrower than what the font supports, then browser should clamp to the @font-face range indeed, even though the font supports wider.

**Comment by litherum** [comment]
The clamping does not happen in CoreText.

The values in @font-face are only designed to be used for font selection, ad therefore should not affect which variation values get applied.

**Comment by behdad** [comment]
> The values in @font-face are only designed to be used for font selection, ad therefore should not affect which variation values get applied.

"which variation values get applied" *is* font selection!  Same way that unicode-range limits a font, @font-face ranges must limit the font IMO.

**Comment by svgeesus** [comment]
Yes, this would be consistent with what we do with unicode-range for example - if the descriptors have a narrower range than what the font actually supports, then we enforce those restrictions. Because the stylesheet designer had some reason to do so (not liking glyphs in a particular unicode range / not liking the bolder weights so preventing them from being used).

**Comment by litherum** [comment]
It's fairly clear that everyone wants clamping. I'll change the spec to do that.

**Comment by litherum** [comment]
I migrated @behdad's issue to https://github.com/w3c/csswg-drafts/issues/782

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/52b802ac38619286a30662dceb71b8a29fa72f42
