### ISSUE TITLE
[css-color-5] Mixing alpha

### ISSUE THREAD

**Issue by kbabbitt** [w3c/csswg-drafts#5176]
In #4915 the working group [resolved](https://github.com/w3c/csswg-drafts/issues/4915#issuecomment-631574709) that in forced colors mode, the color-mix function would be used for background-color, in order to apply the computed color's alpha to the appropriate system color.

At the moment [color-mix](https://drafts.csswg.org/css-color-5/#color-mix) does not specify a way to mix the alpha channel. Noting that `a` is currently used for the like-named channel in lab colorspace, and alpha is (at least theoretically) independent of colorspace, my suggestion is to add `alpha` to the production for `color-adjuster`:

```
<dfn>color-adjuster</dfn> = <<rgb-adjuster>> | <<hsl-adjuster>> | <<hwb-adjuster>>
    | <<xyz-adjuster>> | <<lab-adjuster>> | <<lch-adjuster>> | alpha
```

**Comment by svgeesus** [comment]
![image](https://user-images.githubusercontent.com/2506926/98118927-95bbee00-1eb4-11eb-8931-ebf07a4bff7c.png)

**Comment by svgeesus** [comment]
Missing premultiplication is now fixed, see [Interpolating with alpha]( https://drafts.csswg.org/css-color-5/Overview.html#interpolation-alpha) - which applies to all color interpolation, not just for `color-mix()`

**Comment by svgeesus** [comment]
As suggested, alpha was [added to color-adjuster](https://drafts.csswg.org/css-color-5/Overview.html#typedef-color-adjuster)

**Comment by svgeesus** [comment]
@kbabbitt do these changes resolve your comment?

**Comment by kbabbitt** [comment]
@svgeesus Thanks for the updates! Yes, these changes resolve my comment.
