### ISSUE TITLE
[css-inline-3] line-height < 1 in a margin-box line layout model

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5178]
We had discussed a new mode that switches inline boxes to use their margin-box height instead of the 'line-height' when sizing the line box. This works when there's sufficient slack in the inter-line spacing, however when 'line-height' is less than 1 any inline box would necessarily cause the line box to expand. Somehow we have to apply negative half-leading to these inline boxes.

So far I can think of two sensible ways to do this:

- Apply the negative half-leading to the content-box edges, reducing the content-box size (and consequently the margin-box size) of the inline box.
- Apply the negative half-leading to the margin-box edges, reducing the margin-box directly, but leaving the content box (and consequently the inline's background painting area) unchanged.

The difference here really is whether the visible background painting area / border box is affected by the size reduction. (I'll note that we don't have negative padding, so while the author can easily expand the visible box, it's not otherwise possible to shrink it.)

**Comment by frivoal** [comment]
I don't think we should mess with the content boxes; we can just define the layout bounds (which are set to the margin box) to be reduced by the necessary amount of (negative) leading.

This means that the painting of the inline element won't be affected, but I think that's the right call. In all other situations, changing line-height has no effect on the background/borders/etc of inlines, so it shouldn't here either (which is what would happen if we applied the negative leading directly to the content box).

**Comment by fantasai** [comment]
Resolved in https://lists.w3.org/Archives/Public/www-style/2020Jun/0019.html
