### ISSUE TITLE
[css-fonts-4] [varfont] Fonts may have their own internal mapping of keyword names to values

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#518]
Variation fonts may have their own internal mappings of keyword names to values. For example, a font may state that "condensed" may correspond to a "wght" axis value of "78.2".

CSS may want to have an explicit table of mappings for keywords to values for font-weight, font-stretch, and font-style.

Alternatively, the spec might benefit if the font file is consulted instead. Doing this would separate the notion of a keyword from the notion of a value (so, for font fallback, a keyword might be applied as a different value in two fonts used in the same element).

**Comment by litherum** [comment]
The OpenType spec [lists](https://www.microsoft.com/typography/otspec/os2.htm#wdc) width percentages of reach of the width keywords.

Value | Description | C Definition | % of normal
------------ | ------------- | ------------ | -------------
1 | Ultra-condensed | FWIDTH_ULTRA_CONDENSED | 50
2 | Extra-condensed | FWIDTH_EXTRA_CONDENSED | 62.5
3 | Condensed | FWIDTH_CONDENSED | 75
4 | Semi-condensed | FWIDTH_SEMI_CONDENSED | 87.5
5 | Medium (normal) | FWIDTH_NORMAL | 100 
6 | Semi-expanded | FWIDTH_SEMI_EXPANDED | 112.5
7 | Expanded | FWIDTH_EXPANDED | 125 
8 | Extra-expanded | FWIDTH_EXTRA_EXPANDED | 150 
9 | Ultra-expanded | FWIDTH_ULTRA_EXPANDED | 200

**Comment by Crissov** [comment]
Using the ITU radio spectrum as an inspiration, this should be extended to `super-*`, `extremely-*` and `tremendously-*` (and `very-*` would of course be an alias to `extra-*`). 😜

I wonder, though, why there’re no `70.7%` and `141%` √2 presets (as well as `84.1%`, `119%` and so on). Keywords for irrational values are much more useful than those for simple rational values.

As far as I know, Opentype fonts may also provide default and localized names for indexed features such as `ss01`, but [`@font-feature-values`](https://drafts.csswg.org/css-fonts-3/#font-feature-values) does not provide means to access them yet. Anyhow, it’s probably a good idea to make css-fonts work similar in both cases.

**Comment by litherum** [comment]
Dup of https://github.com/w3c/csswg-drafts/issues/525
