### ISSUE TITLE
[css-flexbox] Replaced flex items

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#5188]
Flex items can be generated by replaced elements, but I don’t find anything about this case in https://drafts.csswg.org/css-flexbox/ (except in a note about blockification of the `display` property).

https://drafts.csswg.org/css-flexbox/#cross-sizing says to "perform layout" without further details, but as far as I know there isn’t a definition of layout for replaced element that is independent of their context / layout mode. CSS 2 has separate sections for inline replaced elements, for block elements in normal flow, etc.

Should there be a normative sentence that https://drafts.csswg.org/css2/visudet.html#inline-replaced-width and https://drafts.csswg.org/css2/visudet.html#inline-replaced-height apply?

For comparison, https://drafts.csswg.org/css-grid/#intrinsic-sizes is more specific.

**Comment by fantasai** [comment]
Hi @SimonSapin, we've clarified that performing layout invokes the same rules as for block-level layout. Let us know if this addresses your issue.

Note: The section you're referring to defines the sizes of a grid container, not a grid item, so isn't analogous here.

**Comment by SimonSapin** [comment]
I copied the wrong link for Grid, I meant https://drafts.csswg.org/css-grid/#grid-item-sizing

Either way, yes ab0e4fe looks good. Thanks!
