### ISSUE TITLE
[css-fonts-4] [varfont] Italic & Oblique benefit from not including a <number>

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#519]
[Migrated](https://github.com/w3c/csswg-drafts/issues/498#issuecomment-248186701) on behalf of @nattokirai:

For variable fonts in OpenType, two axes have been defined, the 'ital' axis and the 'slnt' axis (for slant). The value of 'italic' should map to the value defined in the 'STAT' table. The value of 'oblique' should map to the value defined in the 'STAT' table. If the value is 'italic' and the 'ital' axis does not exist, look for the value of 'oblique' and use the 'slnt' axis instead. Similarly for when 'oblique' is specified but no 'slnt' axis exists. If neither axis exists, use synthetic oblique. Other combinations of values along either the italic or slant axes can be expressed using the font-variation-settings property.

**Comment by Crissov** [comment]
JFTR, that would mean, `font-style: normal | italic | oblique` would remain unchanged.

I‘ve seen backwards italic, semi-slant italic and upright italic fonts before, so I don’t get why these should be excluded. (I would use <percentage> and <angle> instead of <number>, but that’s a different issue.)

**Comment by litherum** [comment]
I know of a case where reverse-obliqued text is typographically valuable in some situations, but regularly-obliqued text is typographically valuable in other situations, where both situations use the same font. This would be a reason to allow the number.

I'd be interested to hear what other browsers have to say. (Does Jonathan Kew have a GitHub account?) cc @SergeyMalkin @PeterCon

**Comment by litherum** [comment]
Is there any other support for this proposal? I'm thinking about closing it.

**Comment by davelab6** [comment]
> Is there any other support for this proposal? I'm thinking about closing it.

I like this proposal! :) 

> I‘ve seen backwards italic, semi-slant italic and upright italic fonts before, so I don’t get why these should be excluded

Those are much more rare cases, though; `normal | italic | oblique` is a short hand, which this proposal makes work in a simple way for VF. Simplicity is important and valuable. 

Indeed, oblique is already a rare option, a subtlety of typography :) The rarer cases can be handled by (more complex) vf css settings. 

> Does Jonathan Kew have a GitHub account?

Yes, @jfkthame

**Comment by litherum** [comment]
Are we still interested in pursuing this? The last comment was over a year ago.

**Comment by fantasai** [comment]
To clarify the above resolution, as far as we can tell, there's no field in OpenType that would let us know what the font designer's preferred oblique angle would be. We're therefore using 14 as the default slant. If OpenType later adds a field for "default angle for obliques", then we can consider using that instead of 14.

**Comment by PeterCon** [comment]
It's not clear what the issue is. Is it specifically related to variable fonts, or just any font? And is it about what the UA should do with "font-style:oblique", with no number specified?

**Comment by fantasai** [comment]
@PeterCon We are actually quite confused as to what the issue actually is about, the conversation above is our best attempt to address it. :)

**Comment by fantasai** [comment]
If there's something we've missed, please let us know!

**Comment by PeterCon** [comment]
If a number is provided and it's a variable font with a slnt axis, then the UA can provide that angle --- or the min/max if beyond the axis range of the font.

If a number is provided and it's _not_ a variable font, then the UA could select an oblique font from the family, if present, even if the angle isn't exactly as specified. (Btw, the italicAngle field in the 'post' table is meant to indicate what the angle is of a static oblique/italic font.) Or, hypothetically, the UA synthetically slant the Regular from that family (if present) to the specified angle. In practice, though, platforms won't synthesize oblique to _arbitrary_ angles, but will synthesize to some specific angle.

If a number is _not_ provided and the font _is_ a variable font with a slnt axis, then I can understand there being uncertainty as to what angle should be requested. Potentially, a [format 3 Axis Value Table](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-table-format-3) (AVT) in the 'STAT' table could be used for this. An AVT describes a particular value on a particular axis for the family, and format 3 allows the developer to indicate a "style-linked" paired value to the "Regular" instance. The spec gives examples of format 3 being used, e.g., for wght = 400 "Regular" to indicate that the style-linked pairing is wght = 700; and it gives an example for the 'ital' axis of ital = 0 "Regular" having a style-linked pairing of ital = 1. So, potentially, for a font with a slnt axis, a format 3 AVT could be used for slnt = 0 to indicate a style-linked pairing on the slnt axis of whatever angle the font designer considers the preferred "Oblique" value. 

We didn't consider this particular situation, and so this use of a format 3 AVT hasn't been called out. But if it can solve a CSS problem, then perhaps it could get called out in some way. There'd still be a need to educate font tool vendors and font developers.

**Comment by jfkthame** [comment]
> Or, hypothetically, the UA synthetically slant the Regular from that family (if present) to the specified angle. In practice, though, platforms won't synthesize oblique to arbitrary angles, but will synthesize to some specific angle.

Hypothetically? No, that's more than hypothetical: that's exactly what Firefox does (as of release 62, currently in beta). So using a family that has no static oblique or italic face, an example like

    data:text/html,<div style="font:50px impact;font-style:oblique 10deg">one <span style="font-style:oblique 20deg">two <span style="font-style:oblique 30deg">three

will slant the three words by successively larger angles. And

    data:text/html,<div style="font:50px impact;font-style:oblique -20deg">reverse

will render with a left-leaning slant, exactly as the author requested.

**Comment by PeterCon** [comment]
Well, I bet that's a first. Do you know of any platform or app that would synthesize slant at varying angles? Just because it's possible, and probably even fairly easy to do, is it a good thing? I'll bet type designers won't be excited to find there are new ways their fonts can be munged. Perhaps teachers in design programs will end up giving their students warning of one more thing to avoid., and perhaps it could lead to page designers avoiding use of "oblique<num>" altogether. I suppose the argument in favour is that, in a fallback situation, it will be truer to the design intent to synthesize the requested angle than a fixed, arbitrary angle.

**Comment by jfkthame** [comment]
> Do you know of any platform or app that would synthesize slant at varying angles?

Skimming comments at https://graphicdesign.stackexchange.com/questions/42412/how-do-i-italicize-fonts-that-dont-have-an-italic-variant-in-illustrator, it seems that InDesign offers a Skew option in the Character palette. And people then start discussing the exact angles they prefer...

It's also been possible for years in XeTeX, which allows a font to be loaded with a specific slant factor.

I expect some type designers will be horrified, but given that `font-style:oblique` allows the author to request a specific `angle`, why *wouldn't* we respect that when synthesizing a slanted face?

**Comment by PeterCon** [comment]
Ah, XeTeX. Clearly an independent development from this in Firefox. ;-)

I'm somewhat surprised, though, that Adobe would put skew in a character palette. But that is probably an independent development.

I'm not making a strong argument against this. It's just not something I would have prioritized as a feature: fonts can now be made with arbitrary type-designer-controlled slant, so why munge other fonts...

**Comment by svgeesus** [comment]
@petercon 
> fonts can now be made with arbitrary type-designer-controlled slant, so why munge other fonts...

Yes, if the fallback font happens to be a variable font. But we can't guarantee that, and the CSS spec needs to give guidance on what to do when an oblique font is requested (with a given angle) and no variable font with a `slnt` axis is in the font stack, so it has to be synthesized.

(Note that CSS also allows a stylesheet to disallow fake bold, fake italic, and now fake smallcaps too).

**Comment by svgeesus** [comment]
> Is there any other support for this proposal? I'm thinking about closing it.

> RESOLVED: Close the issue no-change, fantasai to write a comment for opentype spec authors
