### ISSUE TITLE
[css-fonts-4] font-language-override tag is not necessarily 3 letters

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#5195]
The [spec](https://www.w3.org/TR/css-fonts-4/#font-language-override-string-value) says that the value of `font-language-override` is a "single three-letter case-sensitive OpenType language system tag". However, while it's true that most OT langsys tags are three letters, this is not actually a requirement; the [OT spec](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags) has a few 4-character tags.

(Actually, they're all 4-character, because the ones that look like 3-letter tags are padded with a trailing space.)

The characters involved are not necessarily limited to letters, either. Although the spec says that "[b]y convention, registered language system tags use three or four capital letters", the list has a couple of examples that include a digit 0.

**Comment by heycam** [comment]
For those that have a space as the fourth character, should we match if the space is included as well as if it's excluded (the current behavior)?

**Comment by jfkthame** [comment]
I think so; it would seem a bit perverse not to, given that's the "real" tag. Accepting the 3-letter form is simply a convenience.

More generally, any string shorter than 4 characters should be padded with trailing spaces to a length of 4; in theory, a font could implement a language system with a tag `"X   "` -- although I'm sure such a tag will never end up in the registered list -- and `font-language-override: "X"` should work to access it.

**Comment by svgeesus** [comment]
Thanks, good catch. I will fix the spec to note that this is a 4-character string and that shorter strings specified in CSS get trailing-space padded to 4. Sound good?

**Comment by jfkthame** [comment]
SGTM, thanks.
