### ISSUE TITLE
[scroll-animations-1] Something is odd with the handling of `source` in the ScrollTimeline constructor

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#5202]
The [`ScrollTimeline` constructor](https://drafts.csswg.org/scroll-animations-1/#dom-scrolltimeline-scrolltimeline) text has the following:

> Creates a new ScrollTimeline object using the following procedure:
> 1. Let timeline be a new ScrollTimeline object.
> 1. Let source be the result corresponding to the first matching condition from below.
>     **If the source value of options is non-null,**
>     * Let source be source
> 
>     **Otherwise (source is null):**
>     * Let source be the scrollingElement of the Document associated with the Window that is the current global object.
> 
>     Note: source may still be null after this step, e.g. if the Document has no scrollingElement.
> 1. Set the source of timeline to source.

Which is odd because `source` is not nullable in the `ScrollTimeline` spec. So how can we assign `source` if it is null?

Also, "Let source be source" is odd. Clearly it means the `source` member of `options` but it needs to say that.

**Comment by birtles** [comment]
If we decide that a `source` can be `null` then procedures like the one to [resolve a container-based offset](https://drafts.csswg.org/scroll-animations-1/#resolve-a-container-based-offset) will need to be updated to say what to do in that case.

**Comment by birtles** [comment]
I notice that the procedure to [resolve an element-based offset](https://drafts.csswg.org/scroll-animations-1/#resolve-an-element-based-offset) handles a null `source` so I suspect the IDL and "resolve a container-based offset" need to be updated (we should also check the other algorithms too, however).

**Comment by majido** [comment]
I guess the idea is that if the `ScrollTimelineOptions` may have a null source (which is the default value). And if that is given as input we resolve it to root scroller. So constructed timeline will never have a null source.

However thinking about this more, I wonder we should allow a three state in our handling
- Unspecified: Use default value as document scroller e.g., `new ScrollTimeline({source: null})`  
- Explicitly set to null:  set source to to null  e.g., `new ScrollTimeline({source: null}) `
- Explicitly set to element:  set source to element  e.g., `new ScrollTimeline({source: $div}) `


This is similar to how timeline is handler on `Animation` constructor.
I can make this change and clear up the wording mistake as well.

**Comment by birtles** [comment]
> I guess the idea is that if the `ScrollTimelineOptions` may have a null source (which is the default value). And if that is given as input we resolve it to root scroller. So constructed timeline will never have a null source.

But the spec explicitly says that the Document can have no scrollingElement and hence source can be null?

> However thinking about this more, I wonder if we should allow a three state in our handling:
> 
> * Unspecified: Use document scroller e.g., `new ScrollTimeline({}); /*or*/ new ScrollTimeline()`
> * Explicitly set to null:  set source to to null  e.g., `new ScrollTimeline({source: null}) `
> * Explicitly set to element:  set source to element  e.g., `new ScrollTimeline({source: $div}) `

That would solve this issue (once we also define the behavior when source is null, e.g. in the "resolve a container-based offset" algorithm). I'm not sure if it's _useful_ to be able to do that, but maybe it's fine.

**Comment by majido** [comment]
Spec is fixed. I have filed a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1100907) to fix Chromium implementation.
