### ISSUE TITLE
[scroll-animations-1] Where is the range of threshold values checked?

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#5203]
For element-based offsets, the [`threshold` member](https://drafts.csswg.org/scroll-animations-1/#dom-elementbasedoffset-threshold) has the following description:

> A double in the range of [0.0, 1.0] that represent the precentage[sic] of the target that is expected to be visible in source's scrollport at the intersection offset.

But we don't seem to validate anywhere that that is the case. Should be check it in the constructor for `ScrollTimeline`?

**Comment by birtles** [comment]
That said, I'm not sure if we want to enforce that range or not. Maybe -0.1 is a useful measure? If so, we should probably say that.

**Comment by bramus** [comment]
Having the ability to — for example — set `end 1.2` as the from-offset sure comes in handy, as it allows you to add some “breathing room” to all of your animations.

A from-offset of `selector(#element) end 1.2` basically translates to “the element is 1/5th over the bottom edge”. In that case the animation will not start when `#element` is stuck against the bottom, but only after it's "120%" into the scrollport.


Also see https://github.com/w3c/csswg-drafts/issues/6068, where taking `scroll-padding` into account is suggested.

Both these use-cases could be allowed I guess:

- Over/undershooting the `threshold` is calculated in relation to block-size of the `#element`
- `scroll-padding` (if expressed as a percentage) is calculated in relation to the block-size of the scrollport

**Comment by MattWilcox** [comment]
I'd prefer it to not clamp to a "valid range" when that "valid range" is entirely arbitrary and restricts design possibilities.

**Comment by flackr** [comment]
I suspect this may still be applicable for View Timelines, i.e. a desire to be able to extend the effective element size for the purpose of its fit to the view timeline. In scroll snap terms this would be scroll-margin. Note that scroll-margin does not seem to accept a percentage currently so `view-timeline-inset` seems at least as flexible as what you can do with scroll snap as you can simply add / subtract what the offset relative to the element should be from the inset.

**Comment by fantasai** [comment]
@flackr Isn't this exactly what `view-timeline-inset` is for? Or am I missing something?

**Comment by flackr** [comment]
Right, the gap between `view-timeline-inset` and `end: 1.2` is if you specify `view-timeline-inset: 20%` my understanding is it will be 20% of the scroll range rather than 20% of the element. I don't think this will be significant and imagine we don't need to worry about this.

The percentages we have in the spec don't seem to have precise limits so I'd propose we close this one.

**Comment by fantasai** [comment]
@birtles @bramus Can you confirm if you're ok to close based on @flackr's [comment above](https://github.com/w3c/csswg-drafts/issues/5203#issuecomment-1405629005)?

**Comment by birtles** [comment]
It looks like the `threshold` member no longer exists so it seems fine to close this.
