### ISSUE TITLE
[css-inline-3][css-display-3] both define inline formatting context

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#5209]
This is preventing https://github.com/whatwg/quirks from building.

**Comment by frivoal** [comment]
This is temporary. css-inline is intended to take over that definition, and is making good progress towards that. It should soon be removed from css-display-3, once css-inline-3 is confirmed to be doing it right.

**Comment by annevk** [comment]
Could it not export it until it's time? Having two specifications that are both indexed by Shepherd export the same term creates a lot of downstream hassle.
