### ISSUE TITLE
[css2?] Define when border rounding happens, and to which properties it applies

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5210]
See https://crisal.io/words/2020/06/13/rounding-borders.html

At least the rounding up to device pixels happens consistently at computed value time:

 * https://searchfox.org/mozilla-central/rev/8a85578c00ea55174276b4dcfe2a43e1387144fe/servo/components/style/gecko/values.rs#41-49
 * https://webkit-search.igalia.com/webkit/rev/357f5ddb37eef4235a7ca33367f9833b4204705e/Source/WebCore/style/StyleBuilderConverter.h#297
 * https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/css/resolver/style_builder_converter.cc;l=1077;drc=6993ed8e5cdcfbae4e5ff7891ddfb4de128dd846

Shipping Gecko and WebKit (my post was wrong, Blink and WebKit diverge, will fix) also floor to dev pixels at computed value time. Blink floors at rendering time, which I think is more unfortunate.

**Comment by emilio** [comment]
Did some digging and Blink behavior is inherited from WebKit, but WebKit changed it to match Gecko in https://bugs.webkit.org/show_bug.cgi?id=15612.

**Comment by emilio** [comment]
cc @mrego who was touching border rounding in Blink recently.

**Comment by gsnedders** [comment]
On the whole this ties into the larger issue as to whether we should define rounding behaviour in CSS, which… we appear not to have an issue for?

**Comment by graouts** [comment]
I came across this trying to fix `css-backgrounds/animations/border-width-interpolation.html` for WebKit. Maybe this test should be changed to not test values where this behavior is somewhat undefined?

**Comment by wangxianzhu** [comment]
> Did some digging and Blink behavior is inherited from WebKit, but WebKit changed it to match Gecko in https://bugs.webkit.org/show_bug.cgi?id=156121.

Blink diverged from WebKit more after https://codereview.chromium.org/2640143005 (support subpixel layout of borders, April 2017).

Browser: Rounding in layout / Rounding in computed style:
Firefox: Yes / Yes
WebKit before April 2016: Yes / No
WebKit after April 2016: Yes / Yes
Blink before April 2017: Yes / No
Blink after April 2017: No / No
[Possible future Blink change](https://crbug.com/1201762): Yes / Yes

**Comment by progers** [comment]
Chromium is attempting to unify on the behavior used by Gecko and WebKit:
blink-dev intent-to-ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/0uq_S5p6uZg/m/ReHlihKaAwAJ
chromium bug: https://crbug.com/1201762

**Comment by tcaptan-cr** [comment]
The Chromium change that unifies the behavior with Gecko and WebKit is now complete, and we could update the spec to define the border-width rounding at computed value time.

A proposed wording for the spec definition could be:
```
The border-width length should be snapped to the nearest device pixel at computed value time
based on the following rounding formula:
  If the border-width length is greater than 0 device px and less than 1 device px
  it should be rounded up to 1 device px.

  If the border-width length is greater than 1 device px
  it should be floored down to the nearest device pixel.
```


The clarification of the rounding behavior has also been discussed in [issue 2114](https://github.com/w3c/csswg-drafts/issues/2114)

**Comment by dbaron** [comment]
A few thoughts on a spec definition for this:

Given that it applies to multiple properties (I think `border-*-width`, `outline-width`, and `column-rule-width`), you want to have a definition in one place that can be referenced by the definitions of all three properties.  So I'd suggest something like:

> To <b>snap a length as a border width</b> means to convert that length (presumed to already be nonnegative) as follows:
> - if the length is greater than 0 and less than 1 [device pixel](https://drafts.csswg.org/css-values-4/#device-pixel), it should be rounded up to 1 device pixel;
> - if the length is greater than 1 device pixel, it should be rounded down to the nearest integer number of device pixels.

Given a definition like that, the "Computed value" lines could then say something like "absolute length, snapped as a border width" where "snapped as a border width" links to the above definition.

**Comment by MrHBS** [comment]
@emilio @dbaron @fantasai Would one of you guys do the edit? Or I'll try to open a PR.

**Comment by tabatkins** [comment]
Done! Sorry, the resolution came in while I was on birthday vacation, so I missed it.

**Comment by MrHBS** [comment]
@tabatkins Very nice! Thank you! Just 2 more things to mention:

1 - You might want to look at #7473 and #2114 to see if they are still relevant after this change.

2 - CSS Cascading and Inheritance says:

> A [used value](https://www.w3.org/TR/css-cascade-5/#used-value) is in principle ready to be used, but a user agent may not be able to make use of the value in a given environment. For example, a user agent **may only be** able to render borders with integer pixel widths and may therefore have to approximate the [used](https://www.w3.org/TR/css-cascade-5/#used-value) width.

I think this needs a tweak since border widths are always integers now?

**Comment by tabatkins** [comment]
For 1, thanks, I've commented or closed, as appropriate.

For 2, not *necessarily* - there's nothing in CSS requiring that a px is an integer multiple of device pixels, so that statement can still be reasonable. ^_^
