### ISSUE TITLE
[scroll-animations-1] Handling of unspecified value for source seems incorrect

### ISSUE THREAD

**Issue by majido** [w3c/csswg-drafts#5211]
Here is the wording for source descriptor:

> otherwise if not specified or none then it is the the scrollingElement of the Document associated with the Window that is the current global object.

Note that 'source' is defaulted to 'none' which is interpreted as document root scroller. This seems like a bad choice to have none mean something. We should probably use 'auto' for this purpose and reserve 'none' for situation where source is null.

**Comment by andruud** [comment]
I agree, `auto` is better.

**Comment by majido** [comment]
Spec is fixed. I have filed a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1100907) to fix Chromium implementation.
