### ISSUE TITLE
[css-speech-1] Possible invalid quoting in property types

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#5222]
Apologies if this is incorrect but looking at the draft specification for CSS WebSpeech shows that CSS property types are not properly quoted:
https://drafts.csswg.org/css-speech-1/#rest-props-rest

These should be rendered as ` <'rest-before'> <'rest-after'>?`

However, the spec here appears to include the correct quotes:
https://github.com/w3c/csswg-drafts/blob/5a49df2060abefbc05c85d751429776c5e46edf0/css-speech-1/Overview.bs#L737

Am I simply looking at an outdated version of the spec?

**Comment by Loirooriol** [comment]
The bikeshed should use `<<'rest-before'>> <<'rest-after'>>?` so that the result looks like `<'rest-before'> <'rest-after'>?`.

**Comment by pyoor** [comment]
Is there any reason this hasn't been addressed?  Would it help if I submitted a PR with the proposed changes?

**Comment by fantasai** [comment]
@pyoor Sorry! Just didn't notice the issue. Should be fixed now. Thanks for the report!!
