### ISSUE TITLE
[css-values-4] Bugs in definition of exceptions for font-relative length units

### ISSUE THREAD

**Issue by zjopy** [w3c/csswg-drafts#5228]
When a font-relative length unit is used to set the value of the property that it's defined on, the exceptions defined at the end of [font-relative lengths](https://drafts.csswg.org/css-values-4/#font-relative-length) take effect.

The idea is, to instead use the computed value of the same property of the parent element (case 1). And if no parent element exists, then use the initial value of that property (case 2).

So, or example:

- `em`(and `ex`, `ch`, `ic`, `cap`) for `font-size` property of element (other than root element) is case 1.
- `em` (and `ex`, `ch`, `ic`, `cap`) or `rem` for `font-size` property of root element is case 2.
- `lh` for `line-height` property of element (other than root element) is case 1.
- `lh` or `rlh` for `line-height` property of root element is case 2.

The textual form of these exceptions is kind of hard to read, and probably caused the author to introduce the following logical bugs.

---

The [spec](https://drafts.csswg.org/css-values-4/#font-relative-length) states for `lh` and `rlh`:

> when `lh` or `rlh` units are used in the value of the line-height property on the element they refer to, they resolve against the computed `line-height` and font metrics of the parent element—or the computed metrics corresponding to the initial values of the `font` and `line-height` properties, if the element has no parent.

In the above table this sentence would translate to the third row being

- `lh` **or `rlh`** for `line-height` property of element (other than root element) is case 1.

In summary, the `rlh` unit, when used for the `line-height` property of a non-root element, uses the computed value of the `line-height` property of the parent element, which makes it identical to the `lh` unit in this case. This must be a bug, right? The `line-height` of a non-root element should surely be possible to set relative to the `line-height` of the root element.

---

Another bug is the loose formulation of the previous sentence. The [spec](https://drafts.csswg.org/css-values-4/#font-relative-length) states:

> When used in the value of the `font-size` property on the element they refer to, they [all these font-relative units] resolve against the computed metrics of the parent element—or against the computed metrics corresponding to the initial values of the `font` and `line-height` properties, if the element has no parent.

By using "they", the sentence targets all font-relative units.

Firstly, this includes the `rem` unit, leading to the same bug for `rem` as described above for `rlh`. The `rem` unit, when used for the `font-size` property of a non-root element, uses the computed value of the `font-size` property of the parent element, which makes it identical to the `em` unit in this case. The `font-size` of a non-root element should surely be possible to set relative to the `font-size` of the root element (and is what people usually use `rem` for).

Secondly, this mixes font-relative units and line-relative units. For `lh` and `rlh` the `font-size` property should be irrelevant. Conversely, for `em`, `rem`, `ex`, `ch`, `ic`, `cap` the `line-height` property should be irrelevant.

**Comment by Loirooriol** [comment]
> In summary, the rlh unit, when used for the line-height property of a non-root element, uses the computed value of the line-height property of the parent element

No, the spec says "when [...] used [...] on the element they refer to". The `rlh` unit refers to the root element. So if you use it in a non-root element, the condition won't apply, and it will still be relative to the line-height of the root element.

> Firstly, this includes the `rem` unit, leading to the same bug for `rem` as described above for `rlh`.

No, for the same reason.

> Secondly, this mixes font-relative units and line-relative units. For `lh` and `rlh` the `font-size` property should be irrelevant.

It's relevant, because we don't want cycles like

```css
#element {
  font-size: 1lh;
  line-height: 1em;
}
```

In #2115 I initially proposed detecting cycles with a directed dependency graph, and treat things like `font-size: 1lh` normally if there was no cycle. But from the minutes:

> florian: We could have a less blunt approach, but I don't think there's use cases for the more subtile variants.
> myles: I agree we shouldn't be in the business of trying to do a complex dependency analysis.
> RES0LVED: define lh unit resolution to be that of the parent when the lh unit is spec on line-height or font-size

**Comment by zjopy** [comment]
@Loirooriol Thanks, I indeed seem to have missed the "the element they refer to" part for the first two "bugs".

For the third, if I understand correctly,

```css
#element {
  font-size: 1lh;
}
```

takes the `line-height` of the parent element, even though the `line-height` of the element would be fine perfectly well defined? And conversely

```css
#element {
  line-height: 1em;
}
```

takes the `font-size` of the parent element, even though the `font-size` of the element would be fine perfectly well defined?

Ok, at least I understand the reason behind this. Since this isn't a bug I'll close this issue.

**Comment by Loirooriol** [comment]
Yes, `font-size: 1lh` resolves to the computed `line-height` of the parent, even if there is no cycle.

But `line-height: 1em` resolves the the computed `font-size` of that element, not the parent. The above ensures that this won't be cyclic.

So basically, for a non-root element, you first compute `font-size`, resolving font-relative units with the parent. This sets the all non-root units except `lh`. Then you compute `line-height`, using the previously calculated units, but resolving `lh` with the parent. This sets the `lh` unit.
