### ISSUE TITLE
[css-color-4] Transfer function for ProPhoto RGB

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5229]
In the [predefined colorspaces](https://drafts.csswg.org/css-color-4/#predefined), the transfer function for `prophoto-rgb` is stated to be 1.8.

In [Design and Optimization of the ProPhoto RGB Color Encodings](http://www.realtimerendering.com/blog/2011-color-and-imaging-conference-part-vi-special-session/), by the authors of ProPhoto RGB, the transfer function is described thus:

> a nonlinear encoding (1/1.8 power **with a linear toe segment**) was added to create the ROMM (Reference Output Medium Metric) RGB color space, intended for display-referred data.

On the ICC website, an extract of [ISO 22028-2:2013](http://www.color.org/chardata/rgb/ROMMRGB.pdf) (which defines ROMM, and thus ProPhoto RGB shows an equation

```
If Rr, Gr, or Br are less than 0.001953
R = Rr*16 
G = Gr*16 
B = Br*16 

If Rr, Gr, or Br are greater than or equal to 0.001953 
R = Rr^1/1.8
G = Gr^1/1.8
B = Br^1/1.8
```

The [Wikipedia article](https://en.wikipedia.org/wiki/ProPhoto_RGB_color_space) appears to be accurate and describes a similar toe, with a breakpoint at _Et_ 

```
Et = 16 ** (1.8 /(1 - 1.8) = 2 ** -9 = 1/512 = 0.0019525
```

which is the same as the ISO standard but with an explanation of the magic number (and one more digit of precision).

I have heard that an ICC profile distributed by Adobe with Photoshop is described as ProPhoto but uses a simple 1.8 gamma with no toe. (I have also heard that they distribute a similar ICC profile described as sRGB with a simple 2.2 gamma). This may be the origin of the 1.8 gamma often described for ProPhoto RGB. Also, on an 8-bit (0 to 255) system, the breakpoint occurs midway between codes 0 and 1 so has no effect. However, due to the very wide gamut, at least 10 and more likely 12 bits of precision are needed to avoid banding, so the toes does affect the rendered result.

I intend therefore to change the transfer curve in the specification, and the sample code, setting the constant for the breakpoint as 1/512.

**Comment by svgeesus** [comment]
I see [Bruce Lindbloom](http://www.brucelindbloom.com/index.html?WorkingSpaceInfo.html) also gives the gamma as a simple 1.8

**Comment by svgeesus** [comment]
The [original Kodak specification for ProPhoto RGB](https://www.kodak.com/global/plugins/acrobat/en/professional/products/software/colorFlow/romm_rgb.pdf) is 404 and their current website has no search function.

**Comment by svgeesus** [comment]
From the Kodak whitepaper:

> One  potential  use  of  the  ROMM RGB  color  space  is  as  a  working  color  space  for Adobe Photoshop software.  However, it should be noted that Adobe Photoshop software currently limits the nonlinearity that can be used to define a valid working space **to be a simple  gamma  function**.  However,  both  the  Adobe  Photoshop  software  implementation,as  well  as  the  Kodak  Color  Matching  Module  (CMM)  implementation  automatically impose  a  “slope  limit”  of  16  at  the  dark  end  of  the  tone scale.  Although  a  profile  that explicitly  incorporates  the  nonlinearity  with  the  slope  limit  can  not  be  used  by  Adobe Photoshop  software,  a  profile  using  a  simple  gamma  function  nonlinearity  produces  the net effect of Eq. (2) when used by Adobe Photoshop software or the current version of the Kodak CMM. Therefore, to ensure Adobe Photoshop software compatibility, the ROMM RGB  ICC  profile  created  by  Eastman  Kodak  Company  uses  a  simple  gamma  function nonlinearity without the slope limit, rather than the form shown in Eq. (2). At some point in the future it may be possible to produce a new ICC profile that explicitly incorporates the slope limit if Adobe were to modify the Photoshop software software to remove this artificial  restriction.    Although  this  would  not  have  any  effect  on  the  results  obtained using  Adobe  Photoshop  software  or  the  Kodak  CMM,  it  would  increase  the  likelihood that  equivalent  results  would  be  obtained  using  different  CMMs  that  may  or  may  not include the same slope limiting feature

**Comment by Myndex** [comment]
Adobe ICC profiles for RGB spaces by and large use the simple exponent method and not the piecewise, and this includes their profiles for sRGB and Rec709 that ship with AfterEffects. 

As a side note, ProPhoto is pretty useless for 8bit RGB, the ∆E errors are substantial. Even 10bit is not enough, though 15 or 16 is okay. The only "real" use case for it is being able to edit images destined for 4+ color printing while remaining in an RGB space. Hence the 1.8 gamma and the D50 wp.  

When doing pre-press, editing images in CMYK is gruesome — ProPhoto alleviates much of that. But ProPhoto is a **terrible** colorspace for many common use cases such as images for display on RGB monitors or for cinema/video applications — **_ProPhoto is a really bad workflow choice_** for those.
