### ISSUE TITLE
[css-position-3] why the stacking context part is missing?

### ISSUE THREAD

**Issue by Afif13** [w3c/csswg-drafts#5230]
I recently notice that this part: https://www.w3.org/TR/2016/WD-css-position-3-20160517/#det-stacking-context is no more present in the actual version of the Spec: https://www.w3.org/TR/css-position-3/ 

Where I can find it now? In which Spec?

**Comment by Loirooriol** [comment]
The spec doesn't exist yet, see #4965

**Comment by fantasai** [comment]
Current version of Stacking Context is in CSS2: https://www.w3.org/TR/CSS2/zindex.html
As Oriol mentions, we don't have an L3 version of it yet.
