### ISSUE TITLE
[css-overflow-4] scrollbar-gutter should not be inherited

### ISSUE THREAD

**Issue by felipeerias** [w3c/csswg-drafts#5231]
[The `scrollbar-gutter` spec](https://www.w3.org/TR/css-overflow-4/#scollbar-gutter-property) states that the value of this property is **inherited**.

So, when a container uses e.g. `scrollbar-gutter: always force;` to reserve space for the scrollbar, then all of its children will also reserve the same amount of space inside their respective boxes.

This behaviour is likely to break the layout and doesn't seem to be what the author intended.

Proposal: update the `scrollbar-gutter` spec with `Inherited: no`.

**Comment by frivoal** [comment]
I agree. The main reason for inheriting would be to change the default from `auto` to `stable` by setting it on the root, but that can be achieved with a `*` selector as well, and other cases seem much more likely to be decided on a scroller per scroller basis. And as you said, the `force` value inherits particularly poorly.

**Comment by frivoal** [comment]
Btw, the original discussion on inheritance is minuted here: https://lists.w3.org/Archives/Public/www-style/2017Feb/0059.html We were on the fence about inherited vs not, with some people leaning one way and some leaning the other, but nobody feeling very strongly. But that discussion is prior to the introduction of the `force` value, so I think it makes sense to flip.
