### ISSUE TITLE
[css-pseudo-4] Add a highlight pseudo-element for find-in-page or scroll-to-text

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5233]
Right now you can customize the color of a selection highlight via [::selection](https://drafts.csswg.org/css-pseudo-4/#highlight-pseudo-element), but there appears to
be nothing for user agent-specified selections such as find-in-page and scroll-to-text-fragment.

How about we add `::ua-selection` ?

**Comment by chrishtr** [comment]
One possible concern would be a developer setting those colors to something with no contrast to the other text on the page, but I'm not sure if that is any worse than other things the developers could do to fight with the user or make mistakes regarding contrast.

If that is a significant concern, we could add normative language to require a certain amount of contrast with the background of the text, and if there isn't then allow UAs to ignore the color.

**Comment by chrishtr** [comment]
There is also the window.find API, which currently causes a selection highlight, not a find-in-page highlight.

**Comment by emilio** [comment]
In gecko the selection that `find-in-page` and `window.find` use is the same, we just paint it with a different style in the find-in-page case. Also there's another case which is the 'highlight-all' option, in which case we do use a different selection, but with yet another set of colors. So there are three cases here:

 * Regular selection / regular color (`window.find`).
 * Regular selection / find-in-page color (find-in-page primary match).
 * Find-in-page selection.

In gecko the find-in-page color is called `attention` style (I think it's used also for a couple other things), fwiw.

This is somewhat similar to the discussions we've had about styling the inactive window selection, where it seemed that people preferred a pseudo-class that applied to the existing `::selection` pseudo somehow rather than a whole new pseudo-element, but I could be misremembering.

**Comment by dbaron** [comment]
I'd [previously suggested](https://lists.w3.org/Archives/Public/www-style/2010May/0298.html) that CSS have a mechanism for multiple named selections and an API for creating them, and a find-in-page selector (or more than one of them) could fit in to that.

**Comment by emilio** [comment]
That seems somewhat related to [this proposal by Microsoft](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/31d126afcf74ecd7a02a14a57b4fc0291e21896b/highlight/explainer.md).

**Comment by hober** [comment]
Put this in the Thursday milestone so that @megangardner can attend.

**Comment by chrishtr** [comment]
I did some research into additional use cases and considerations.

@tantek brought to my attention explorations like [Marginalia](https://indieweb.org/marginalia) from IndieWeb. The idea there is to use a fragment identifier to indicate responses or comments on sites. On that page, it suggests that "As a first step, marginalia can be displayed as normal post-level comments at the bottom of the post but with a reference/fragmentioned link to the context-phrase.". Such a UI would require the site's script to understand the fragment identifier and modify DOM accordingly; a pseudo-element is much too restrictive in expressivity. In that case a script-exposed state such as that proposed [here](https://github.com/WICG/scroll-to-text-fragment/issues/128), and/or a script event indicating highlighting as proposed [here](https://github.com/WICG/display-locking/blob/master/explainers/beforematch.md) would be make sense.

However, for simple styling of default User Agent affordances such as the color of the scroll-to-text highlight, it makes more sense to simply expose the highlight pseudo-element for this purpose, and specify which CSS properties apply to it. An alternative of requiring script to do it would be very difficult for page authors to implement, in part because it needs to happen very earlier in the page load lifecycle.

It's possible to imagine a User Agent that does not use *only* a highlight to indicate scroll-to-text (e.g. maybe there would be an overlay UI of some kind), but it seems unlikely that this would occur without a highlight, because a highlight + scrolling is a very effective and established way for a User Agent to indicate text on a page that the user is interested in and plays nicely with the style and layout concepts of the web.

I'd like to move for us to adopt a highlight pseudo for find-in-page and scroll-to-text. We could even add one for each, since as mentioned in the CSSWG meeting notes the use cases are different.

**Comment by bryanmcquade** [comment]
This sounds like it could potentially be useful. Have we heard from developers/publishers that they want the ability to customize the highlight style & would make use of this if we provided the capability? We have heard some feedback that the current yellow color is not pleasant and are exploring other colors, so I'm wondering if that would be sufficient to address any current concerns vs whether devs feel they need the ability to further customize. Some quotes / concrete examples from devs of how they would override the highlight style to improve the UX on their site (e.g. screenshot of current yellow highlight and the alternative style they'd use instead) could help us here.

**Comment by chrishtr** [comment]
@bryanmcquade  I think any color will be incompatible with some sites, since the color scheme of sites varies greatly. We already have pseudo elements to override colors of other similar concepts like spelling and grammar underlines, and I think this feature falls into the same pattern.

**Comment by litherum** [comment]
On macOS and iOS, the yellow bubble isn't actually part of the page - it's on its own layer floating above the page. Because of that, we don't really have infrastructure to style part of the bubble in one color and the rest in another color; we kind of have to just pick a single color for the entire bubble. The spec should be flexible enough to allow for this constraint.

**Comment by tabatkins** [comment]
> we kind of have to just pick a single color for the entire bubble. The spec should be flexible enough to allow for this constraint.

This is reasonable - should be fine to allow UAs to take the style from the nearest common ancestor of the highlighted fragments and use it across the selection, if that's required for their rendering.

**Comment by litherum** [comment]
> nearest common ancestor

This may end up being a color that is wildly different from any color that other UAs show. We might want a different heuristic.

**Comment by fantasai** [comment]
Closing this out in favor of #5522 and #5929. @chrishtr If I missed something else here, please pull it out into a separate issue? :)

**Comment by chrishtr** [comment]
@fantasai sounds good, thanks.

**Comment by fantasai** [comment]
@samuelbradshaw See https://github.com/w3c/csswg-drafts/issues/3812 for that discussion
