### ISSUE TITLE
[css-inline-3] vertical-align syntax / canonical ordering

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5235]
Minor syntactic questions on vertical-align now that it's a multi-valued shorthand:

- Should we allow the `auto` value of `baseline-source` in the shorthand?
It's not clear what it refers to, is not useful (it's the default behavior), and is left out of serialization anyway... and if at some point we have some longhand that has a meaningful `auto` value, it would prevent being able to specify that. So I've a slight preference to keep it out of the shorthand.

- What's the best canonical ordering of the values?
Seems like `baseline-source` should go first since English has that preference built into its grammar, but is there a preferred order for `alignment-baseline` vs. `baseline-shift`? (I'm leaning towards making `alignment-baseline` go first.)

- css-align restricts the position of `first | last` to right before the `baseline` keyword. Should we similarly restrict it in `vertical-align`? Or let it be reordered since it's parseable either way?

**Comment by MatsPalmgren** [comment]
@fantasai
> [css-align-3] Allow reordering of first|last vs baseline keywords.

Doesn't that make `place-items: baseline last baseline` ambiguous?
