### ISSUE TITLE
[css-inline-3] leading-trim through to descendant line boxes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5237]
The current definition of `leading-trim` relies on the concept of “first formatted line”. This was done for two reasons:
- it drills down through unstyled block boxes, which is helpful to the author and absolutely necessary given the way we generate anonymous block boxes
- it correctly aborts on nested formatting contexts, replaced elements, etc.

However, it might be a bit too aggressive, as it also drills through *styled* block boxes. Consider

```
  <section style="leading-trim: start">
     <div class="warning" style="border: solid 10px; padding: 0.2em">...</div>
     <p>Whatever normal paragraph.</p>
  </section>
````

The .warning would probably be a bit surprised if the section trimmed its half-leading when it didn't request such trimming itself.

I think we might want to borrow the logic from margin collapsing, and not drill into boxes with non-zero padding/border. Whether or not the margins could have collapsed seems closely related to whether or not this block’s own content edge is adjacent to its descendant's first/last line box and therefore whether it should be controlling the leading on that line.

**Comment by fantasai** [comment]
Proposed definition:
> Trim the _block-start_ side of the _first formatted line_ to the corresponding 'text-edge' metric of its _root inline box_. If there is no such line, <ins>or if there is intervening non-zero padding or borders,</ins> there is no effect.

Agenda+ to confirm as requested by previous discussion.

**Comment by AmeliaBR** [comment]
On the name question: we don't actually use “leading” to describe space between lines anywhere in CSS, do we? Could this be `line-height-trim` or something similar?

(I myself initially assumed it was “leading” meaning “trim off the starting bit, above the first line”, not “trimming off the extra lead/metal from your type pieces so you can pack them in more compactly”.)

**Comment by zed-vector** [comment]
Amelia, 'leading' means (a) the strips of lead added between lines of type to **increase** the line spacing, and (b) the amount by which the line height is so increased.
