### ISSUE TITLE
[css-fonts-4] [varfont] font-stretch should accept <number> to support calc()

### ISSUE THREAD

**Issue by bramstein** [w3c/csswg-drafts#524]
The current draft for variable font support [defines `font-stretch`](https://drafts.csswg.org/css-fonts-4/#font-stretch-prop) to accept the following values:

``` css
normal | ultra-condensed | extra-condensed | condensed | semi-condensed | semi-expanded | expanded | extra-expanded | ultra-expanded | <percentage>
```

Even though `<percentage>` may seem like a natural fit (and even suggested by the [OT variable font spec](https://www.microsoft.com/typography/otspec/fvar.htm#VAT)), it excludes the use of `calc()` to dynamically calculate a value along the `wdth` axis.

There have been several attempts at using a condensed typeface at narrow viewports (most notably on A List Apart). It is plausible that web developers will want to dynamically calculate a value for `font-stretch`, so `<number>` seems more appropriate to me (though as a work around, the lower level `font-variation-settings` could also be used).

**Comment by bramstein** [comment]
Alternatively, `font-stretch` could also accept `<number>` in addition to `<percentage>`.

**Comment by litherum** [comment]
getComputedStyle() should probably return the percentage, though.

**Comment by fantasai** [comment]
Seems reasonable to me. `calc()` users can always multiply by `100%`, so this would really be more of a convenience.

**Comment by fantasai** [comment]
It might be worth checking in on other places where we use percentages while we're thinking about this.

**Comment by svgeesus** [comment]
I agree that with variable fonts, it is more natural to specify a number than to be restricted to a quantized set of keywords or be forced to use the  low-level font-variation-settings.

**Comment by tabatkins** [comment]
I don't understand - what is the benefit of number over percentage?  What problem does percentage cause?

**Comment by tabatkins** [comment]
(If it's the bug in the calc() spec that means calc() isn't allowed to resolve to a bare `<percentage>`, but it can resolve to a `<number>`, that's a bug for us to fix.  Other specs shouldn't work around it.)

**Comment by litherum** [comment]
According to https://drafts.csswg.org/css-values-3/#calc-notation

> [calc] can be used wherever ... <percentage> ... values are allowed.

> <calc-value> = <number> | <dimension> | <percentage> | ( <calc-sum> )

So there's no reason why `calc(20% * 3)` wouldn't work.

**Comment by tabatkins** [comment]
Ah, so we did fix that, good. ^_^

**Comment by litherum** [comment]
Removing the Agenda+ tag because it seems that everyone agrees that `<percent>` is sufficient.

**Comment by litherum** [comment]
And, because there are no actual edits that are necessary, there's nothing to do, so this can just be closed.
