### ISSUE TITLE
[css-flexbox] Should clarify if aspect ratio calculations use border-box or content-box

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#5246]
E.g. here:
https://drafts.csswg.org/css-flexbox/#min-size-auto

The transferred size uses the aspect ratio, but it's not clear whether it should use the content box or border box for the calculation.

Also, here:
https://drafts.csswg.org/css-flexbox/#algo-main-item
the calculation says explicitly that the inner cross size is used, which contradicts https://drafts.csswg.org/css-sizing-4/#valdef-aspect-ratio-ratio which says that box-sizing determines whether to use content-box or border-box

**Comment by cbiesinger** [comment]
(however, the inner is probably correct for replaced elements with an intrinsic aspect ratio, which probably (?) shouldn't use box-sizing)

cc @fantasai

**Comment by fantasai** [comment]
@cbiesinger Checked in edits to remove the explicit mention of "inner". Do you think this is acceptable to close now?

**Comment by cbiesinger** [comment]
Thanks, that helps. I think it would be nice if there was a link to someplace that explicitly defines which box-sizing to use though.

**Comment by fantasai** [comment]
@cbiesinger I think at some point when the aspect ratio spec and related terminology is more stable, we'll end up adding a lot of cross-links across all our layout specs, but at this point if I add a note pointing to sizing-4 here, I have to add one everywhere else in the spec that mentions “aspect ratio” and I think that's too many notes... If you're implementing `aspect-ratio`, the spec for `aspect-ratio` is pretty explicit about which box to use.
