### ISSUE TITLE
[css-fonts-4] [varfont] access to named instances

### ISSUE THREAD

**Issue by gferreira** [w3c/csswg-drafts#525]
Reading the overview [here](https://litherum.blogspot.com.br/2016/09/variable-fonts-in-css-draft.html), I miss a way to access pre-defined instances by name. While it's great to be able to choose a value for each parameter numerically, in most common cases it will be easier for font users to choose one among several named instances provided by the type designer.

Here’s an example to illustrate what I mean:

```
10. Use named, pre-defined variation instances contained in the font

@font-face {
  font-family: "MyVariableFamily";
  src: url("MyVariableFamily.otf");
}

<div style="font-family: MyVariableFamily; font-name: 'SemiBold'>hamburgefonstiv</div>
<div style="font-family: MyVariableFamily; font-name: 'Light Condensed';">hamburgefonstiv</div>
<div style="font-family: MyVariableFamily; font-name: 'Black Extended Rounded'>hamburgefonstiv</div>

```

note: probably related to [this](https://github.com/w3c/csswg-drafts/issues/518).

**Comment by gferreira** [comment]
Another syntax idea, similar to font IDs in SVG fonts:

```
@font-face {
    font-family: "MyVariableFamily";
    src: url("MyVariableFamily.woff#Bold-Condensed");
    font-weight: bold;
    font-stretch: condensed;
}
```

**Comment by robmck-ms** [comment]
Relating this back to my STAT table issue #539: It would be helpful to leverage the STAT table to provide names that we can use in font properties.

Context (so we're all on the same page):
- The fvar table in a variable font defines a set of named instances that are equivalent to a font. E.g. "Condensed Bold". These could be used as in both the above proposals
- The STAT table defines a set of named points along each axis. You can think of these as click stops on each axis. E.g. "Normal" and "Condensed" on the width axis, and "Semilight" and "Bold" on the weight axis. This is handy not only for being able to parse names in the fvar table into their components, but for addressing instances (even those that may not be listed as a named instance in the table).

Thus, for a family with weight and width axes, the STAT table might define points for "Light", "Semilight", "Regular", "Semibold", and "Bold" on the weight axis, and "Condensed", "Semi-Condensed", "Normal", "Wide", and "Super Wide" for the width axis. Then, the fvar would define instances as follows:
- "Light Condensed"
- "Semilight Condensed"
- "Condensed"
- ...
- "Bold Super Wide"

Note that fvar need not define all the possible permutations described in STAT, so you may have some interesting instances in the font that aren't listed in fvar. 

Ok, so on to my proposal:
1) Allow STAT defined names in standard font properties. E.g.:
`font-weight: "Semi-condensed";
font-stretch: "Super Wide";`

2) Allow STAT defined names in the second proposal above. E.g.:
`   src: url("MyVariableFamily.woff#Semilight+Ultra-Wide");`

or maybe
`   src: url("MyVariableFamily.woff?wght=Semilight&wdth=Ultra-Wide");`

Obviously, if all font designers list all the permutations of STAT in named instances in fvar, then the @font-face src proposal isn't very interesting. The proposal for using names in font properties is the main one I'm interested in.

**Comment by jpamental** [comment]
I outlined this in #1289 but am copying this over here as an example for how we might be able to do this in CSS:

```
@font-face {
        font-family: Hamstervar;
        src: url("Hamstervar-VF.ttf");
        font-stretch: normal;
        font-weight: normal,
        font-variation-settings: "wdth" 85, "wght" 327; 
}

@font-face {
        font-family: Hamstervar;
        src: url("Hamstervar-VF.ttf");
        font-weight: bold,
        font-variation-settings: "wght" 572; 
}

@font-face {
        font-family: Hamstervar;
        src: url("Hamstervar-VF.ttf");
        font-stretch: expanded;
        font-weight: bold,
        font-variation-settings: "wdth" 112, "wght" 572; 
}

```

In this way we tell the browser _how to apply_ the keywords, in this way using `font-variation-settings` to effectively map the values we want to the keywords expected.

**Comment by o-t-w** [comment]
There are so many thousands of choices within a variable font and that can be somewhat overwhelming, so named instances are incredibly important. Professional typographers are highly skilled people who will have carefully choose their named instances.
