### ISSUE TITLE
[css-color-5] Which color do percentages in color-mix() apply to?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#5258]
I've just seen [this discussion](https://github.com/w3ctag/design-reviews/issues/526) and [this PR](https://github.com/w3c/csswg-drafts/pull/5256) by @dbaron about an error in the calculations for `color-mix(red, yellow 65%)` and noticed something else: The calculations are done as if this means 65% red and 35% yellow. 

However, it is not defined anywhere which color the percentage applies to. This is all that I can see [mentioned](https://drafts.csswg.org/css-color-5/#color-mix) about the `<number-percentage>`:
> When a plain number or percentage is specified (without a color-adjuster), it applies to all color channels in the given colorspace equally.
> If the plain number or percentage is omitted, it defaults to 50% (an equal mix of the two colors).

I think it would make much more sense to have it apply to the color it's closer to, i.e. yellow. Not only is this easier to read and more natural, but it also extends nicely to [multiple colors, which we're already discussing](https://github.com/w3c/csswg-drafts/issues/4711) In fact, we should allow **either or both** colors to have a percentage (and normalize accordingly if it doesn't add up to 100%). Actually, @una in this thread [used such a syntax naturally](https://github.com/w3c/csswg-drafts/issues/4711#issuecomment-582682708), which is another indication it would be user friendly.

If co-editors @svgeesus @una @argyleink agree, I could make the change.

PS: While we're at it, do we really need a `<number-percentage>`? All examples I've seen everywhere, including ours use a percentage. It's very confusing to have numbers that mean percentages, but don't have a % sign, and there's no reason to. Am I missing something?

**Comment by argyleink** [comment]
Yes, let's make this change. I think there's overlapping work between this change and the changes @svgeesus indicates in https://github.com/w3c/csswg-drafts/issues/4711#issuecomment-633258586? From what I understand, allowing multiple colors and the syntax it's encouraging, accomplishes the same goal as the intent in this proposal; the % lives with the color(s).

**Comment by svgeesus** [comment]
I agree: percentage only, and closest to the color it is a percentage of. The calculations and the diagrams are unaffected.

Also [@tabatkins suggested](https://github.com/w3c/csswg-drafts/issues/4711#issuecomment-631022384) putting the colorspace first.

**Comment by snigo** [comment]
I 100% agree that percentage should indicate opacity of the second color.
You also need to keep in mind that I might wanna mix already semi-transparent colors:
```css
/* A. with providing opacity */
color-mix(#f002 #ff08 50%); /* Basically same as mixing #f002 with #ff04 which suggests I can do next */

/* B. without providing opacity */
color-mix(#f002 #ff04); /* which suggests that third argument must have 100% default value */
```

**Comment by LeaVerou** [comment]
@snigo The percentage is not opacity, it's a percentage along the interpolation line. There's no conflict with alpha, alpha is just another channel to be interpolated.

**Comment by svgeesus** [comment]
```css
/* A. with providing 50% opacity on the second color */
color-mix(#f02 #ff00887F); /
```

[4- and 8-digit hex includes alpha](https://drafts.csswg.org/css-color-4/#hex-notation)

**Comment by snigo** [comment]
@LeaVerou Thanks for your reply! Just to confirm, will this result in `#ff03`?
```css
color-mix(red #ff03 100%);
```

For some reason my brain fights this ))

**Comment by svgeesus** [comment]
Yes, you have a mixture slider that goes from one color to the other, and the 100% says the slider is hard over to the `#ff03` end

**Comment by svgeesus** [comment]
Syntax now updated by @LeaVerou so that the percenage immediately follows each color; examples updated just now to follow the new syntax.
