### ISSUE TITLE
[scroll-animations] Behavior of scroll-linked animations in the first frame

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5261]
As specified currently, if the author manages to create a `ScrollTimeline` _before_ the first frame has been produced, then:

 - When the [timeline is sampled](https://drafts.csswg.org/scroll-animations-1/#avoiding-cycles), layout will not have have happened yet, hence:
  - The source will _not_ have a CSS layout box, so the timeline is [inactive](https://drafts.csswg.org/scroll-animations-1/#phase-algorithm) for that frame, and there is no effect value.
 - The next frame, the timeline is sampled again, and this time layout _has_ run, so the source now has a layout box, and the timeline is active.

This means there is an initial "flash of no effect value" before the animation takes effect on frame 2.

For the JS API, we could probably mitigate this without any _technical_ difficulty by letting `ScrollTimeline` constructor force a style recalc and layout, and then sample once immediately.

For the CSS API, it's quite a bit worse, since it's the style calculation _itself_ that discovers that a `ScrollTimeline` is needed. In other words, we're already standing in the middle of style recalc when creating `ScrollTimelines`, so we can't force style and layout at that time.

So the question is how to deal with this.

1. Accept the limitation
2. Somehow do multiple passes of style/layout to get the information we need
3. Provide a reasonable default and give the author tools to tweak the initial phase of the timeline
4. Something else

@birtles @flackr @lilles @majido

**Comment by flackr** [comment]
> As specified currently, if the author manages to create a `ScrollTimeline` _before_ the first frame has been produced, then:
> 
> * When the [timeline is sampled](https://drafts.csswg.org/scroll-animations-1/#avoiding-cycles), layout will not have have happened yet, hence:
> * The source will _not_ have a CSS layout box, so the timeline is [inactive](https://drafts.csswg.org/scroll-animations-1/#phase-algorithm) for that frame, and there is no effect value.
> * The next frame, the timeline is sampled again, and this time layout _has_ run, so the source now has a layout box, and the timeline is active.
> 
> This means there is an initial "flash of no effect value" before the animation takes effect on frame 2.
> 
> For the JS API, we could probably mitigate this without any _technical_ difficulty by letting `ScrollTimeline` constructor force a style recalc and layout, and then sample once immediately.

The [specification around this](https://drafts.csswg.org/scroll-animations-1/#avoiding-cycles) is pretty vague. You could interpret it to mean that when we sample animations (which would be when generating the next frame after construction in JS) we could ensure that style and layout are clean which would allow for the creation of the layout box.

> For the CSS API, it's quite a bit worse, since it's the style calculation _itself_ that discovers that a `ScrollTimeline` is needed. In other words, we're already standing in the middle of style recalc when creating `ScrollTimelines`, so we can't force style and layout at that time.
> 
> So the question is how to deal with this.
> 
> 1. Accept the limitation
> 2. Somehow do multiple passes of style/layout to get the information we need
> 3. Provide a reasonable default and give the author tools to tweak the initial phase of the timeline
> 4. Something else
> 
> @birtles @flackr @lilles @majido

I'm leaning towards allowing a multiple style/layout passes. This would be similar to how ResizeObserver [performs multiple style and layout cycles](https://drafts.csswg.org/resize-observer/#html-event-loop) however I would suggest that we only do this in the case where the ScrollTimeline was created in the current cycle, to allow for the creation of the CSS layout box, and not repeat if the scroll timeline's animation modifies layout as this would be significant a performance pitfall if it happened every frame.

**Comment by majido** [comment]
> 1. Accept the limitation

I don't know how bad would an initial "flash of no effect value" before the animation takes effect on frame 2 is.
It only matters if the animation has a valid value for initial scroll offset. Also a fairly easy mitigation exists where author can given the target of the animation an initial style value that is equivalent to animation effect at initial scroll offset.

But I agree not requiring authors to worry about it is better.

> 2. Somehow do multiple passes of style/layout to get the information we need

I am with @flackr that if we are allowed to do this then it solves the issue in the general case and does not burden the authors.  Also agree that we should limit this for the first time a timeline is constructed.

Would we ever need to have more than two passes? In the first pass we construct the timeline and layout its scroll source. In the second pass we initialize the timeline which initialized its animations which can invalidate style and layout again. I don't expect any script to run in between these two passes so on second pass we shouldn't construct any new timelines. So perhaps two pass is enough.

I checked and [resize observer](https://caniuse.com/#feat=resizeobserver) is supported by all major engines which is a good sign. Though I am not sure if they all support this multi-pass behavior as specified.


> 3. Provide a reasonable default and give the author tools to tweak the initial phase of the timeline

I couldn't come up with a good idea here but here are some thoughts:
 - One idea I had was to have scroll timelines to be initialized with `before` phase. This would solve the issue for animations with   `backwards` fill mode but it is not a general solution.
- Another idea was to assume an initial scroll offset zero. But with things like css scroll snap which modify initial scroll offset zero is simply not correct in general case.
- I don't think we need to give a way for authors to tweak initial value/phased of the timeline. As I mentioned before just providing an initial style for the animation target is a cleaner way to do this.

**Comment by birtles** [comment]
> So the question is how to deal with this.
> 
> 1. Accept the limitation
> 2. Somehow do multiple passes of style/layout to get the information we need
> 3. Provide a reasonable default and give the author tools to tweak the initial phase of the timeline
> 4. Something else

I haven't thought about this particularly deeply but I'd probably prefer to avoid (3) since it sounds like adding more ongoing complexity. (2) sounds attractive if possible.

**Comment by lilles** [comment]
> I'm leaning towards allowing a multiple style/layout passes. This would be similar to how ResizeObserver [performs multiple style and layout cycles](https://drafts.csswg.org/resize-observer/#html-event-loop) however I would suggest that we only do this in the case where the ScrollTimeline was created in the current cycle, to allow for the creation of the CSS layout box, and not repeat if the scroll timeline's animation modifies layout as the author has done something wrong if this happens, and this would be a significant performance pitfall if it happened every frame.

What's the definition of a ScrollTimeline being created in the current cycle for animation-timeline/@scroll-timeline? Is it that the computed value of animation-timeline changes and that the name matches a @scroll-timeline with the source matching an element? Could we have a situation where animation-timeline flips back and forth for each style/layout pass? Or is that guaranteed not to happen because animation-timeline has animatable:no?

**Comment by andruud** [comment]
OK, sounds like there's support for trying (2) (possibly for lack of a better option).

> What's the definition of a ScrollTimeline being created in the current cycle for animation-timeline/@scroll-timeline? Is it that the computed value of animation-timeline changes and that the name matches a @scroll-timeline with the source matching an element?

Yes, except the source doesn't necessarily have to match an element at that time. (And it doesn't have to be a response to a change in animation-timeline specifically. It could also happen e.g. if a `@scroll-timeline` is inserted.

> Would we ever need to have more than two passes?

I don't think so. I think we'll do at most one additional pass, and then if the source still lacks a layout box for whatever reason, then the timeline is just inactive that frame.

> Could we have a situation where animation-timeline flips back and forth for each style/layout pass?

I don't think so, but if we do at most one extra pass, it should anyway be fine?


More thinking out loud on approach (2):

 - This is not only a "first frame" problem, but can also happen e.g. if we already have an existing `@scroll-timeline` with some source `#foo` that initially doesn't exist, and then `#foo` appears at some time later. (And similar scenarios).
 - Hence we could possibly define the approach approximately like this: if, after style calculation, there's a timeline with a _source_ that's layout-dirty, do another pass. (With a max of one additional pass).
 - I would be super-sceptical to (2) if ResizeObserver didn't already do multiple passes. (So ... thank you ResizeObserver!)
 - I slightly wonder how sustainable it is to keep adding passes for new features, but at least our extra pass should be shareable with ResizeObserver passes (I think/hope). So at least it's not additive.
 - getComputedStyle would return the "wrong" result before the first frame has been run. I assume this must also be the case for some ResizeObserver scenarios.
 - My initial thought is that the JS API should behave the same way, just so we have less "unique" behaviors.
 - Watch out for features that deliberately leave the tree in a dirty state, e.g. display locking. (I don't remember the current name of this feature).

**Comment by flackr** [comment]
@andruud Please check my PR and see if you think it is sufficient. I tried to be very specific about exactly when in the event loop updates happen.

Note that unlike your proposal, JS constructed animations still sample at the beginning of the frame. I feel like trying to defer script constructed animations adds unnecessary complexity - though it does mean that we have to freshen style and layout additionally during step 7.10 for those animations but I believe we already have to do this for event dispatch. If we want to defer them we'll have to track newly constructed timelines beyond the scope of one event loop update.

**Comment by andruud** [comment]
@flackr Thanks for taking this. Looks reasonable overall, I left some comments.

I assume we're pretending that other troublemakers (css-toggle, css-anchor, container queries) don't exist at the moment. Ultimately we'll need to know the order of various passes.

> Note that unlike your proposal, JS constructed animations still sample at the beginning of the frame. I feel like trying to defer script constructed animations adds unnecessary complexity - though it does mean that we have to freshen style and layout additionally during step 7.10 for those animations but I believe we already have to do this for event dispatch.

I disagree, I think it's eagerly doing style and layout in the lifecycle that adds unnecessary complexity. Even what Blink is currently doing for JS constructed timelines seems preferable.

> If we want to defer them we'll have to track newly constructed timelines beyond the scope of one event loop update.

That seems entirely doable for both spec and implementation. :-)
