### ISSUE TITLE
[css-inline] HTML taking a dependency on ascent/descent metric

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#5266]
FYI: HTML is taking a dependency on https://drafts.csswg.org/css-inline/#ascent-metric (and descent) in https://github.com/whatwg/html/pull/5429. It'd be appreciated to get a heads up if these break at some point in the future.

cc @jfkthame @yiyix

**Comment by fantasai** [comment]
@annevk That seems fine in theory, but I do want to point out that the ascent/descent metrics as used by CSS are non-interoperable across implementations. (There's some discussion of this in https://github.com/w3c/csswg-drafts/issues/2228 and some follow-up in https://github.com/w3c/csswg-drafts/issues/4792 ) I'm not sure what the state of the CanvasAPI is on that front.

**Comment by annevk** [comment]
What I'd personally like is for canvas to use the same underlying drawing primitives so "ideally" it would be equally non-interoperable until that is either sorted or accepted as implementation-defined behavior. @jfkthame can speak much more to all this though.

**Comment by fantasai** [comment]
@annevk Sounds good. You might also want to cross link into the definitions for “alphabetic baseline”, “hanging baseline”, and “ideographic baseline” in https://www.w3.org/TR/css-inline-3/#baseline-types

I filed https://github.com/w3c/csswg-drafts/issues/5312 on the emHeightAscent and emHeightDescent metrics.

**Comment by annevk** [comment]
Done in https://github.com/whatwg/html/pull/5723. I think this can be closed then. And we can use #5312 to track the remainder.
