### ISSUE TITLE
[css-contain-2] interaction between content-visibility and overflow-clip-margin

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5271]
Per [css-contain-2 §4](https://drafts.csswg.org/css-contain-2/#content-visibility):

> An element is relevant to the user if any of the following conditions are true:
> 
> * The element is "on-screen": its containing box's border box intersects with the viewport, or a user-agent defined margin around the viewport.

paint containment normally clips to the padding box, which is normally smaller than the border box, so the above should be fine in general. However paint containment can be made to apply to a larger area using overflow-clip-margin. In that case, it seems that the element should also be considered relevant to the user if its overflow clip edge (i.e. padding edge +  overflow-clip-margin) intersects with the viewport.

Moreover, since its only the contents of a skipped element that are not painted, rather than the element itself, it doesn't seem like the border box is the relevant one. So I don't feel we need to worry about the union of, or the larger of, the border box and the overflow clip edge, and in the sentence quoted above, we can just replace border box with overflow clip edge.

**Comment by chrishtr** [comment]
I agree with these comments. Florian, would you be ok making the spec edit you just mentioned?
