### ISSUE TITLE
[mediaqueries-4] Drop overflow-block:optional-paged

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5287]
The [`overflow-block` media feature](https://drafts.csswg.org/mediaqueries-4/#mf-overflow-block) describes the behavior of the device when content overflows the initial containing block in the block axis. The `none`, `scroll`, and `paged ` values correspond to well known behaviors, but `optional-paged` is more theoretical/speculative, and doesn't really correspond to anything that currently exists.

It was meant to match things like the (presto-based) Opera <=12 presentation mode. This was a user-activated mode, fundamentally similar to `scroll` (overflow triggers scrollbars; the ICB is the viewport, not the page area; and the whole css-page model doesn't apply), but in addition, it allowed the author to insert forced fragmentation breaks, leading to something akin to a paginated behavior. This was meant for making things like slide decks.

While I think experimenting with that sort of things is great, no current user agent behaves like that, so no current user agent will match that particular value. This makes it not useful.

Further, if someone were to experiment again within that space, we cannot be sure that the behavior they'd land on would be the same as the one opera had and that is currently used in the spec as the definition of `optional-paged`, which would make the value misleading.

If someone ever ships something of that nature, we should definitely look into making sure that whatever behavior they end up with can be covered by media queries, but until that happens, I think we should drop this speculative value.

**Comment by fantasai** [comment]
I think it makes more sense to mark it at-risk, and drop it when you go to REC if there's no implementation.

**Comment by frivoal** [comment]
I'd be OK with  at-risk, but I'd actually prefer removing it: the problem is not merely lacking implementations of this media query, but rather that it is unclear to me whether that media query is specified right: the class of UA it purports to describe doesn't currently exist, and if something similar were to be created, we don't know that they would actually behave the way the spec claims they would.

**Comment by fantasai** [comment]
It did exist in the past, though, so it's not merely theoretical. Also, removing it from the specs means any UA that has such a combination mode would almost certainly just assume there's no value that matches their behavior and will pick one (or both) of the existing values to match. Leaving it in the spec is more likely to result in them filing an issue about the description being slightly off.

**Comment by frivoal** [comment]
If you want to leave it in at-risk, I'd suggest switching it from counting as "paged media" to counting is "continuous media" for the purpose of defining these two terms, as the historical opera behavior had more in common with the former than the later in terms of definition of the ICH, responding the the viewport meta tag, not responding to `@page`, etc.

My preference towards removing it is in part because I don't like answering these questions in the abstract (what would the viewport units have matched in opera 12's presentation mode had it had them), but if we're leaving it in, that historical behavior was closer to continuous than to paged.
