### ISSUE TITLE
[scroll-animations] Elements returned from selector() should be live

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5289]
It's possible for the `source` of a `@scroll-timeline` to change its meaning between frames. E.g. for `source:selector(#foo)`, which element is identified by `#foo` can change if attributes are moved around or elements are added/removed. When this happens, the subsequent frame / updating-of-the-scroll-timeline-state should then reflect whatever the new DOM state is.

This applies to element-based offsets as well.

cc @majido

**Comment by flackr** [comment]
I think with the new API that we have no element references after the decision to remove container references #7046. There are timeline references but it is more obvious when those refer to a different timeline that it should replace the timeline. Is there still a change needed here in the new spec?

**Comment by andruud** [comment]
@flackr Yes, agree it's obvious in the new API, closing.
