### ISSUE TITLE
[css-grid] What is the computed value for a single value <flex> track sizing?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#529]
https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-flex
"When appearing outside a minmax() notation, implies an automatic minimum (i.e. ''minmax(auto, `<flex>`)'')."

It's not clear to me if what "implies" means, is it:
1. the computed value should be minmax(auto, `<flex>`)
or
2. the computed value is `<flex>` but the used value for the min-sizing function is 'auto'

**Comment by fantasai** [comment]
IIRC, CSSOM dictates that CSS syntax should be serialized to the shortest valid output, so a) the abstract "computed value" is whatever you want to store in your engine and b) the serialization of both is <flex>. @tabatkins or @dbaron could correct me if I'm wrong...

**Comment by MatsPalmgren** [comment]
OK, makes sense.

**Comment by fantasai** [comment]
Note: CSSOM needs to reinstate the prose around requirement, see https://github.com/w3c/csswg-drafts/issues/1564
