### ISSUE TITLE
[css-inline] Misplaced keywords in the property definition table of the alignment-baseline

### ISSUE THREAD

**Issue by triple-underscore** [w3c/csswg-drafts#5291]
The Value field of the table (both the current [Editor’s draft](https://drafts.csswg.org/css-inline-3/#alignment-baseline-property) and [Working draft](https://www.w3.org/TR/css-inline-3/#alignment-baseline-property)) includes keywords `bottom`, `center` and `top`, without no description in the prose following the table, which are keywords for another longhand baseline-shift.
Perhaps, they  should have been removed along with some recent commits.

**Comment by fantasai** [comment]
Indeed. Thanks for the report. :)
