### ISSUE TITLE
[css-text-3][css-fonts-3][css-text-decor-3] Distinguish applying to text vs applying to boxes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5303]
We've historically only used the 'Applies to' lines to apply to boxes, but it seems we do need to distinguish whether something applies to an inline box vs. line box vs. text:

- For ::marker, a lot of properties don't apply to the marker box, because we don't know what kind of box an outside marker is yet. But they should inherit through to the text and apply there.
- For `display: contents`, properties can be applied to an element that generates no box, but still be pass through to its text.

So I'm thinking we should update the propdef tables of properties that apply to text to say "and text", so we can better define how these cases work. I think the rough idea is to do that for:
- `color` (and maybe all of css-color-adjust?)
- all font properties
- all inheritable css-text-decor properties
- all properties in css-text that apply to inline boxes?

and, going forward, not do that for any properties that rely on knowing box geometry.

(See https://www.w3.org/TR/css-display-3/#intro for discussion of boxes/elements/text runs etc.)

Does this make sense?

**Comment by Loirooriol** [comment]
My assumption was that all inherited properties that apply to inline boxes, also apply to text.

Seems my assumption was wrong in the case of `line-height` on Firefox, but on Chromium it does apply to text.

**Comment by frivoal** [comment]
Proposed PR in https://github.com/w3c/csswg-drafts/pull/5761

**Comment by TalbotG** [comment]
CSS3Text property (white-space) that applies to inline boxes also apply to text

Tests: 
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-007.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/white-space-applies-to-text-008.html

References:
http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-007-ref.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Text/reference/white-space-applies-to-text-008-ref.html

I will update [PR26877](https://github.com/web-platform-tests/wpt/pull/26877) in a few min.
