### ISSUE TITLE
[css-variables] CSS-wide keywords in fallbacks

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5325]
Suppose we have: `div { display: var(--undefined,inherit); }`

The _cascaded value_ for `display` is in this example a sequence of tokens (not a CSS-wide keyword), hence the [explicit defaulting](https://drafts.csswg.org/css-cascade/#defaulting-keywords) behavior in the cascade is not triggered. At computed-value time, the `var()` substitutes to `inherit`. This is valid per [css-values](https://www.w3.org/TR/css3-values/#component-types) which states that the grammar of all properties are understood to also allow `unset | initial | (etc)`. This means we end up with a valid value of `inherit` that we somehow have to deal with computed-value time.

It seems useful to be able to use CSS-wide keywords in the fallback, especially with `revert`. We should consider specifying that if a declaration ends up with a CSS-wide keyword after var() substitution, it's resolved at computed-value time similarly to how it's normally done cascade-time. (I'll just have to think about whether this triggers any of the Bad Stuff from #4155).

Or failing that, make it IACVT, but we shouldn't leave it undefined.

**Comment by andruud** [comment]
@tabatkins Do you have any thoughts on this?

**Comment by tabatkins** [comment]
Currently it's not undefined, it just doesn't do what you probably want, as it subs in the literal keyword "inherit" which is almost never valid.

That said, if it's okay implementation-wise, I'm fine with triggering the other global-keyword behaviors, since we can already trigger inherit/initial via IACVT.  We have to be a little stricter that this only occurs if the `var()` is the sole value of the property - is that okay?

It would also mean that there's some behaviors that are *only* obtainable via `var()` fallback, not as the value of a variable. To get a variable to be able to contain global keywords, we'd have to do some minor hackery; I don't think it's that important, but still.  

I suppose that's already true with things like subbing in another variable's value for the fallback; to get this behavior as a first-class value, we'd need to add delayed evaluation for variables. I have a proposal for that tucked away, but I don't think it's worth bringing out right now, and anyway, it won't interfere with resolving this issue in the simple way.

**Comment by andruud** [comment]
> Currently it's not undefined, it just doesn't do what you probably want, as it subs in the literal keyword "inherit" which is almost never valid.

That's a good point. I'm not sure why I thought it was undefined. :upside_down_face:

> if it's okay implementation-wise

Like you say we're already required to support this behavior via IACVT. The exception is revert at computed-value time, which is _no longer_ required by anything else after the recent edit to css-color-adjust-1. So `var(--unknown, revert)` would be the new reason for why impls must support revert at computed-value time. Bummer.

> We have to be a little stricter that this only occurs if the var() is the sole value of the property - is that okay?

Should be OK, but why is that necessary to specify? Can't we just handle the CSS-wide keyword if we somehow end up with it? E.g. `display: var(--unknown, inherit) var(--also-unknown, )` would substitute to `display:inherit` (whitespace omitted) and could therefore trigger inherit-behavior? Seems easier to handle this as "after substitution, try to parse a CSS-wide keyword and handle it as such if successful".

**Comment by emilio** [comment]
> Seems easier to handle this as "after substitution, try to parse a CSS-wide keyword and handle it as such if successful".

This is what Gecko does, afaict.

**Comment by Loirooriol** [comment]
> fantasai: Works for me. I would like revert to work but want to make sure it does before we spec

@fantasai `revert` as a fallback is implemented in Firefox. Chromium currently treats it as `unset` ([source code](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/css/resolver/style_cascade.cc;drc=4157bfe188b1da73ef93f5d1f4dc0121f0208ff9;l=61-67)). [Testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Aol%2C%20ul%20%7B%0A%20%20list-style-type%3A%20lower-roman%3B%0A%20%20list-style-type%3A%20var(--does-not-exist%2C%20revert)%3B%0A%7D%0A%3C%2Fstyle%3E%0A%3Col%3E%0A%20%20%3Cli%3E%F0%9F%A0%94%20Should%20be%20%221.%20%22%3C%2Fli%3E%0A%3C%2Fol%3E%0A%3Cul%3E%0A%20%20%3Cli%3E%F0%9F%A0%94%20Should%20be%20%22%E2%80%A2%20%22%3C%2Fli%3E%0A%3C%2Ful%3E).

**Comment by andruud** [comment]
> Chromium currently treats it as `unset`

That was done as temporary behavior pending the outcome of this discussion. Supporting it in Chromium should be easy.

**Comment by miragecraft** [comment]
It's been two years, will we be getting revert keyword support in fallback soon?

**Comment by tabatkins** [comment]
Sorry for the delay, but spec edit done. Just need tests for this behavior now.

**Comment by coderfin** [comment]
> > Chromium currently treats it as `unset`
> 
> That was done as temporary behavior pending the outcome of this discussion. Supporting it in Chromium should be easy.

@andruud 

Since this work is `easy` any way would could get this prioritized for chrome?  It is working great in other browsers.

**Comment by Loirooriol** [comment]
Blink implemented and added tests in https://chromium-review.googlesource.com/c/chromium/src/+/3934282
