### ISSUE TITLE
[css-inline-3] Initial-letter alignment when 'over-sunk'

### ISSUE THREAD

**Issue by zed-vector** [w3c/csswg-drafts#5329]
https://www.w3.org/TR/css-inline-3/#initial-letter-styling

Example 7 shows a case where the **size** of the initial letter is less than the **sink** and states that the alignment would be on the alphabetic baseline only. The effect is ugly and 'wrong'.

In this case, the alignment should be at the top, leaving any gap below. The use case is in trying to emulate letterpress printing in which only a limited set of discrete type font sizes was available to the printer. It makes no odds in setting up the type in the chase (I have actually done this, long ago) whether the initial letter type character is packed above or below, so it would have been packed upwards for the sake of appearance. 

As a secondary suggestion, if initial-letter could have another value, to specify the initial letter font size (as, for example, a multiple of the surrounding text size, or with a keyword to indicate that the `<number>` value should be so interpreted) the effect would be easier to achieve and would base an 'over-sunk' character on top alignment only, so making the complex height calculation unnecessary in this case. 

It may well be that the effect I suggest could be achieved in CSS by other means, but initial-letter should include it as that is the
obvious place to look.

**Comment by fantasai** [comment]
So, there's two ways we could handle this:

- When size > sink, align to the bottom metric; but when size < sink, align to the top metric.
- Use the range between the top and bottom metrics of the paragraph as the alignment container, and the top and bottom metrics of the initial letter as the alignment subject, and honor `align-self` to dictate the alignment when they don't match up, defaulting `normal` to baseline alignment as dictated by the initial letter’s `alignment-baseline`.

The second option is strictly more powerful. We could also try to do both simultaneously, but that might get a bit confusing...

**Comment by fantasai** [comment]
Note, the first option also seems to handle some of the concerns in #5015, see https://github.com/w3c/csswg-drafts/issues/5015#issuecomment-660776373

**Comment by faceless2** [comment]
To illustrate the difference between the two, as currently defined now when size < sink, the content is aligned with the bottom alignment point.

![image](https://user-images.githubusercontent.com/989243/88727479-a6c3c900-d127-11ea-91be-2c485edd1614.png)

What fantasai is proposing is aligning with the top alignment points where size < sink, which looks like this:

![image](https://user-images.githubusercontent.com/989243/88727198-05d50e00-d127-11ea-832a-b7e6bb741c31.png)

I think it's a good solution myself, it solves my issues with Indic scripts and I believe it resolves @zed-vectors concerns too.

**Comment by fantasai** [comment]
Ok, edits checked in. See new https://drafts.csswg.org/css-inline-3/#initial-letter-block-position (once the draft server updates). @faceless2 Would you mind reviewing? @zed-vector Are the changes acceptable to you?

**Comment by zed-vector** [comment]
@fantasai , thank you for that. It looks OK to me, however in Example 7 in https://drafts.csswg.org/css-inline-3/#sizing-drop-initials the text and .png presumably need to be fixed too. It currently reads:
"initial-letter: 2.51 3
    The size of the initial letter does not have to be an integral number of lines. In this case only the **bottom** aligns."

**Comment by fantasai** [comment]
@zed-vector Done. Thanks! :)
