### ISSUE TITLE
[css-inline-3] Wrong Unicode code point for Hebrew maqaf (U+05B3)

### ISSUE THREAD

**Issue by triple-underscore** [w3c/csswg-drafts#5337]
In [appendix A.1](https://drafts.csswg.org/css-inline-3/#baseline-synthesis-fonts):
> The top edge of the center of the Hebrew maqaf (U+05B3 “־”) can be taken as the Hebrew hanging baseline.

According to [the Unicode chart for Hebrew](https://www.unicode.org/charts/PDF/U0590.pdf), the code point for Hebrew maqaf should be U+05BE.

(In the same appendix, there is also seemingly a wrong term `ideograph-central` baseline, which would be `central` baseline.)

**Comment by fantasai** [comment]
Fixed -- by referencing Hebrew He instead as suggested in https://github.com/w3c/csswg-drafts/issues/5244#issuecomment-665127983 actually :) Thanks for the error report.
