### ISSUE TITLE
[css-selectors] Support `.` (dot) notation for non-XHTML namespaces

### ISSUE THREAD

**Issue by sebastien** [w3c/csswg-drafts#534]
Regarding https://drafts.csswg.org/selectors-4/#class-html

Browsers currently render CSS stylesheets using the `.classname` (_dot notation_) differently from the `[class~="classname"]` notation depending on the node's namespace.

For instance, Firefox treats both cases the same for non-XHTML XML nodes while Chrome only applies the `[class~=...]` form in http://ffctn.com/doc/chrome-test-style.xml

The issue has been around for a while (see [Bugzilla #7758](https://bugzilla.mozilla.org/show_bug.cgi?id=7588) and [Chromium #69444](https://bugs.chromium.org/p/chromium/issues/detail?id=649444#c6)), and boils down to this:
- The [spec is clear](https://bugzilla.mozilla.org/show_bug.cgi?id=7588#c2) in saying that dot-notation is meant for (X)HTML nodes
- However, the common practice is that developers prefer/use the dot-notation
- Developers willing to use CSS stylesheets for non-XHTML namespace XML currently can't reliably use the dot-notation because of the different interpretations by browsers
- As a result, one option to do so would be to write the CSS in dot-notation and then transpile it to `[class=~...]` notation, which would lead to having either two stylesheets (one per notation) or a default stylesheet in `[class=~...]` notation instead of the dot-notation.

Given that the dot notation is an alternative syntax to the `[class=~...]` (at least according to [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=7588#c2)), it would be good if it had the same treatment across all browsers.

Ultimately, I feel XML does not deserve to be treated as a second-class citizen of the web, and would benefit get the same level of tooling support as HTML. Maybe the spec can help by clarifying that if an XML node has a `class` attribute, then any corresponding dot-notation CSS selector should match?

**Comment by dbaron** [comment]
Gecko changed its behavior in [bug 741295](https://bugzilla.mozilla.org/show_bug.cgi?id=741295) to support class and id on all elements, as specified by the DOM spec (at the time, at least).

**Comment by sebastien** [comment]
Would you have a link to the DOM spec in question? I can propagate the info back to the Chromium ticket.

**Comment by dbaron** [comment]
I think the relevant parts are probably its [definition of ID (and the note following)](https://dom.spec.whatwg.org/#concept-id) and its [definition of className and classList (and the note following)](https://dom.spec.whatwg.org/#dom-element-classname).

**Comment by sebastien** [comment]
Thanks a lot, this is exactly what I need :+1:

**Comment by sebastien** [comment]
Ok, so it seems it's going to be fixed in Chrome https://bugs.chromium.org/p/chromium/issues/detail?id=649444#c10 -- not sure if the issue is still relevant now. Thanks a lot!
