### ISSUE TITLE
[css-variables] Disallow animation-tainted substitutions in any non-animatable property

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5341]
Currently, if a custom property is animation-tainted, it's [not allowed to substitute](https://drafts.csswg.org/css-variables/#substitute-a-var) that custom property into `animation-` properties, nor the `display` property (with some conditions).

This means (since it's not mentioned), that it's allowed to substitute an animation-tainted custom property into `direction` and `writing-mode` (among others), effectively making those properties animatable. This makes it unnecessarily complicated to specify a reasonable behavior for css-logical properties in animation keyframes, since the physical properties involved change during the animation.

Properties are probably 'not animatable' [for a reason](https://drafts.csswg.org/web-animations/#not-animatable), so it seems bad to create a loophole where unwanted complexity can "escape".

I propose that we (unconditionally) disallow animation-tainted custom property substitutions in any property that's 'not animatable'.

For what it's worth, Chrome already has this behavior (possibly since the beginning), and I've seen no complaints.

**Comment by andruud** [comment]
cc @tabatkins

**Comment by tabatkins** [comment]
Yes, this seems reasonable to me.
