### ISSUE TITLE
[css-color-adjust] Animation type of forced-color-adjust

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5342]
Since `forced-color-adjust` is quite special in that its _computed value_ determines cascade-time behavior, does it make sense to "dampen" some of this complexity by making the property 'not animatable'?

I noticed that `direction` and `writing-mode` are 'not animatable', and they are involved in a similar computed-value-time/cascade-time interaction.

I'm just wondering if we should err on the side of less complexity for weirdo-properties like `forced-color-adjust` :-).  Just a thought. cc @fantasai

**Comment by fantasai** [comment]
Makes sense to me. Agenda+ to ask the WG what they think; this is primarily a question for implementers. :)
