### ISSUE TITLE
[meta] Opportunity for data-driven decisions

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#5343]
For those who are not aware, the [HTTPArchive](https://httparchive.org/) crawls the top 5.6 million websites, which are then queryable via Google’s BigQuery. Since last year, they have started publishing a ["Web Almanac"](https://almanac.httparchive.org/en/2019/), with analysis of various metrics for each Web technology, a collaborative effort of many people, content authors, reviewers, analysts. As an example, here is the [2019 CSS chapter](https://almanac.httparchive.org/en/2019/css), by our @una and @argyleink. 

For this year, I have accepted the role of content lead for the CSS chapter. Our @rachelandrew and @svgeesus are also co-authors and our @fantasai and @mirisuzanne in the reviewers. We need to finalize the metrics that we are going to hand off to the analysts ASAP, but before we do so, I figured it would be good to reach out to the WG, since access to such metrics could be immensely useful in developing specs as well. The primary goal of computing these statistics should be to answer the question "What is the state of CSS in 2020?", but I believe there is significant overlap between these metrics and metrics that would help our spec editors make informed, data-driven decisions. This is an opportunity to get such metrics computed with minimal effort on our part, all that's needed is to just post what the statistic should measure.

I have created a repo for these stat suggestions [here](https://github.com/leaverou/css-almanac/issues) and built an app for easier one-click voting via 👍 reactions here, to assist prioritization: https://leaverou.github.io/mavoice/?repo=leaverou/css-almanac&labels=proposed%20stat

If you have any ideas, please post them as soon as possible. Agenda+ to ensure people don’t miss this (expected telcon time < 3 mins).

**Comment by SebastianZ** [comment]
@LeaVerou Are you still searching for ideas or can this issue be closed?

Sebastian
