### ISSUE TITLE
[css-color] 12-bit Hex Notation

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#5344]
I donʼt like hexadecimal triplet (or quartet) notation for RGB(A) color values, because I think it is 

- firstly too opaque, in that for many people the _hex_ in the tech slang term “hexcode” understandably resonates with _magic spell_, 
- and secondly too technology-specific, in that RGB becomes constrained to 8-bit sRGB. 

However, it remains immensely popular, so take the following as an _advocatus diaboli_ proposal.

It has not been brought up as a part of #3249, but since each hexadecimal digit represents a nibble, i.e. 4 bits, a logical extension to

- #rgb (3 hexdigits, 4-bit channel or component, 12-bit color),
- #rgba (4, 4, 16),
- #rrggbb (6, 8, 24) and
- #rrggbbaa (8, 8, 32) 

notations would be

- **#rrrgggbbb** (9, 12, 36) and
- **#rrrgggbbbaaa** (12, 12, 48). 

10-bit color channels cannot be represented well this way. 

Although #rgb can simply map unto #rrggbb or #rrrgggbbb by repeating the digit, this is not possible in general for mapping #rrggbb unto #rrrgggbbb.

**Comment by zamadatix** [comment]
> and secondly too technology-specific, in that RGB becomes constrained to 8-bit sRGB.

> 10-bit color channels cannot be represented well this way.

The proposal doesn't seem to provide any practical gain towards the problem statement.

**Comment by svgeesus** [comment]
> I donʼt like hexadecimal triplet (or quartet) notation for RGB(A) color values

or do I, which is why all the modern stuff is tending towards a bit-depth neutral formulation with a float [0 .. 1] or 0% to 100% representation

Adding convoluted hexadecimal representations merely obscures this goal.
