### ISSUE TITLE
[css-lists] UA styles for ::marker are duplicated and out of sync

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#5346]
From https://drafts.csswg.org/css-lists/#marker-properties

> UAs must add the following rule to their default style sheet:
> ```css
> ::marker, ::before::marker, ::after::marker {
>   unicode-bidi: isolate;
>   font-variant-numeric: tabular-nums;
>   white-space: pre;
> }
> ```

From https://drafts.csswg.org/css-lists/#ua-stylesheet

> ```css
> li::marker {
>   unicode-bidi: isolate;
>   font-variant-numeric: tabular-nums;
> }
> ```

They got out of sync. It would probably be better to avoid the duplicity and define the UA styles for markers in a single place.

**Comment by twilco** [comment]
Is that single place here: https://html.spec.whatwg.org/multipage/rendering.html#lists?

From https://drafts.csswg.org/css-lists/#ua-stylesheet:

> This section is informative, not normative. The [HTML] [Rendering](https://html.spec.whatwg.org/multipage/rendering.html#lists) chapter defines the normative default properties that apply to HTML lists;
