### ISSUE TITLE
[css-text-4] should the text-spacing property work with OpenType 1.8 updates?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#535]
The OpenType 1.8 spec updated the text for [halt](https://www.microsoft.com/typography/otspec/features_fj.htm#halt) and [vhal](https://www.microsoft.com/typography/otspec/features_uz.htm#vhal) to include that these features should be used to trim full-width characters to half-width for applications that conforms to JLREQ.

Should the [text-spacing](https://drafts.csswg.org/css-text-4/#text-spacing-property) property be updated to use these features?

/cc @MurakamiShinyu @fantasai @frivoal

**Comment by frivoal** [comment]
@kojiishi Nice catch. Yes that totally makes sense. Of course, not all fonts support this, so the current behavior should be used for fonts that don't, but for those that do, this is the way to go.

Just to be clear, this would affect the following values, right:
- `trim-start`
- `trim-end`
- `allow-end`
- `trim-adjacent`

**Comment by kojiishi** [comment]
Huh, should have posted after more investigations. Turns out:

* Works good for Yu families, both TT/CFF versions.
* Does **not** work for Hiragino, Meiryo, MS Gothic.

Hiragino has `halt` feature, strange it doesn't work.

But anyway, this doesn't look like a very attractive option. Maybe we add this as MAY, and avoid our use of "3/4 width" to match the behavior?

**Comment by fantasai** [comment]
@kojiishi, updated the spec. Please review and close the issue if it's OK? :)
