### ISSUE TITLE
[css-grid-1] Spanning items increase doesn't handle min-content maximums

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5352]
In “Increase sizes to accommodate spanning items content-sized tracks”, we handle

1. auto minimums
2. min-content minimums
3. max-content minimums
5. auto maximums
6. max-content maximums

It seems, however, that we don't handle the delta between an item’s auto and min-content contributions when min-content is specified as a maximum. :(

**Comment by Loirooriol** [comment]
Dupe of #4790

**Comment by fantasai** [comment]
There's no such thing as an auto maximum, actually. This error was introduced when we dfn'ed “min-size contribution” https://github.com/w3c/csswg-drafts/commit/f48098caaf4c7988d51c5598d276aabb70cf8a5b and needs to be reverted.
