### ISSUE TITLE
[mediaqueries-5] Typo "change" for "chance" in 2.4.4. Using “min-” and “max-” Prefixes On Range Features

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/csswg-drafts#5355]
* please link to the spec section you're talking about, or at least the spec
https://www.w3.org/TR/mediaqueries-5/#mq-min-max

Example 17 reads:
Using the example above, changing the second comparison value to 320.01px significantly reduces the change that a viewport width on a device would fall between the cracks.

I believe it would correctly read:
Using the example above, changing the second comparison value to 320.01px significantly reduces the chance that a viewport width on a device would fall between the cracks.

**Comment by frivoal** [comment]
Thanks! Fixed now.
