### ISSUE TITLE
[mediaqueries-5] redundant media feature

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5359]
Given that we now have `prefers-contrast: high | low` and `prefers-color-scheme: light | dark`, do we still need `light-level`?

It seems to me that user agents could react to the situations described by `light-level: washed` and `light-level: dim` by setting an appropriate combination of values through `prefers-contrast` and `prefers-color-scheme` (possibly giving the user a choice as to how they want the mapping to work).

In that case, we wouldn't really need the `light-level` at all, would we?

In fact, macOS does something that isn't quite that, but goes in that direction: in addition to its light and dark modes, it has an auto mode that picks between light or dark depending on the time of the day. Maybe instead of the `light-level` feature, we could add a Note indicating that UAs are may (should?) infer preferences like `prefers-contrast` or `prefers-color-scheme` based on environmental factors, such as light levels, time of the day, etc.

**Comment by frivoal** [comment]
Effectively, we have solved ["issue 6"](https://drafts.csswg.org/mediaqueries-5/#issue-86dff265) from the spec by introducing prefers-contrast and prefers-color-scheme without noticing we did. 

> Using this media feature for accessibility purposes overlaps a lot with the high-contrast media feature proposed by Microsoft. Can we adjust this so that it covers all use cases for both, or somehow modify them to work in an orthogonal, rather than overlapping, fashion? 

Now that we have, we can retire light-level.

**Comment by frivoal** [comment]
BTW, If we go that way, https://github.com/w3c/csswg-drafts/issues/1727 can be closed.

**Comment by svgeesus** [comment]
The CSS `light-level` seems over-vague and generally not useful. Compared to the Ambient Device Sensor [`light-level`](https://w3c.github.io/ambient-light/#current-light-level) which gives the background illuminance in lux and is thus directly actionable:

- moving from device colorimetry to color appearance models
- adjusting overall system gamma for video, to take into account lighter or darker than nominal background illuminance

**Comment by tabatkins** [comment]
That lack of precision is intentional and a feature of the MQ, and has been discussed with the Device Sensor people in the past. MQs aren't generally usable for responding to fine gradations.
