### ISSUE TITLE
[css-scroll-snap] snap alignment of LTR boxes inside RTL scroller is undefined

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#5361]
https://drafts.csswg.org/css-scroll-snap-1/#scroll-snap-align

Consider a `direction: rtl; overflow-x: scroll, scroll-snap-type: x mandatory` scroller, and inside a box with `direction: ltr; scroll-snap-align: start;`. Which edges of the enclosed box align with which edge of the enclosing scroller?

Firefox and Chrome have different behavior.

[Testcase](https://codepen.io/smfr/pen/vYLMgJv)

**Comment by fantasai** [comment]
See https://github.com/w3c/csswg-drafts/issues/3815
