### ISSUE TITLE
[css-grid-1] Flexible tracks with auto min don't handle min-content constraint sizing

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5369]
Follow-up to #4783: Now that the automatic minimum size of items crossing flexible tracks is zeroed out... we are not accounting for their min-content sizes at all when the grid is sized under a min-content constraint.

https://drafts.csswg.org/css-grid-1/#algo-flex-tracks handles max-content constraints in consideration of max-content sizes, but under min-content constraints any flex tracks get sized as zero. Ideally, a grid with one 1fr track should size similarly to a block container, and that analogy fails here.

We may want to consider accommodating min-content sizes of auto-min flex tracks specially somehow.

Note: We don't exactly have interop on this case. See [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22width%3A%202px%22%3E%0A%3Cdiv%20style%3D%22display%3A%20grid%3B%20border%3A%20solid%3B%20float%3A%20left%3B%20grid-template-columns%3A%201fr%201fr%22%3E%0A%3Cdiv%20style%3D%22grid-column%3A%201%20%2F%20-1%3B%20background%3A%20aqua%22%3Etest%3C%2Fdiv%3E%0A%3Cdiv%20style%3D%22border%3A%20solid%20orange%22%3E%3C%2Fdiv%3E%3Cdiv%20style%3D%22border%3A%20solid%20teal%22%3E%3C%2Fdiv%3E) in Chrome vs Firefox.

**Comment by Loirooriol** [comment]
So you want to change the resolution from #3683?

Wouldn't this already be covered by https://drafts.csswg.org/css-grid/#track-size-intrinsic-min

> First increase the base size of tracks with an intrinsic min track sizing function by distributing extra space as needed to accommodate these items’ minimum contributions.
> If the grid container is being sized under a min- or max-content constraint, use the items’ limited min-content contributions in place of their minimum contributions here.

Zeroing out the automatic minimum size shouldn't have affected the limited min-content contributions in flex tracks (I hope this will be web compatible).

**Comment by Loirooriol** [comment]
![](https://user-images.githubusercontent.com/7477678/88809903-f1d7ed80-d1b4-11ea-9f52-b0903adbbf02.png)

Your testcase looks like that image in Chromium if I apply my patches for:
 - Handling intrinsic contributions of spanning items with flex tracks
 - Zeroing out the automatic minimum size of spanning items with flex tracks
 - Using the limited min-content contribution instead of the minimum contribution when sizing under a min-content constraint

**Comment by fantasai** [comment]
> So you want to change the resolution from #3683?

No...

> Wouldn't this already be covered by https://drafts.csswg.org/css-grid/#track-size-intrinsic-min

I think you're right. Missed that paragraph. :)
