### ISSUE TITLE
[css-position-3] Auto margin resolution isn't symmetrical.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#5374]
https://drafts.csswg.org/css-position-3/#abspos-margins

> Otherwise, the remaining space is calculated as the size of its inset-modified containing block in the relevant axis minus the box’s used size in the relevant axis, and this remaining space is divided among any auto margins in the relevant axis. However, if the remaining space is negative and both margins are auto, the start margin resolves to zero and the end margin receives the remaining space.

There is a sutle different between the horizontal and vertical (or inline, and block? - needs research) algorithms:
https://drafts.csswg.org/css-position-3/#abs-non-replaced-width
https://drafts.csswg.org/css-position-3/#abs-non-replaced-height

See this testcase:
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=8318

In the vertical (or block, but which block?) direction negative auto margins get distributed evenly between the top and bottom, where-as horizontal (or inline) the inline-start margin is zero.

**Comment by bfgeek** [comment]
cc/ @fantasai 

Unsure what all the UAs do for different writing modes.

**Comment by Loirooriol** [comment]
> In the vertical (or block, but which block?)

Chromium seems to use the wm of the abspos in order to decide between the above, and Firefox the wm of the containing block.
https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/8321

**Comment by fantasai** [comment]
@Loirooriol For this kind of thing, we generally use the writing mode of the containing block, so I think Firefox is more correct in that respect.

**Comment by fantasai** [comment]
Edits checked in to make the behavior match CSS2, translating to vertical writing modes per containing block.

**Comment by tabatkins** [comment]
And specifically, we aligned with Firefox's behavior (using containing block for both the axis and direction), because using the WM of one element but the direction of another, like Chrome does, is almost always wrong.

**Comment by bfgeek** [comment]
Are there additional tests for this now?

**Comment by fantasai** [comment]
We now have an official CSSWG resolution on this point.
