### ISSUE TITLE
[math] math style (minimizing logical height of an equation)

### ISSUE THREAD

**Issue by bkardell** [w3c/csswg-drafts#5387]
(Part of #5384 - MathML Core related CSS)

In some cases in mathematical rendering it is desirable to minimize the logical height of an equation.  This is generally done by common norms about font-sizing adjustments to parts of the equation, how some operators are drawn, how/where scripts are measured, and how vertical gaps and shifts are applied.  Below is an example of the same equation rendered in two common ways, the one on the left applying the common rules to minimize the logical height, the one on the left, not.

![math with normal and compact math-styles](https://mathml-refresh.github.io/mathml-core/examples/example-math-style.png)

For this purpose, we introduce the `math-style` property with values `normal` (default) and `compact`.

MathML supported this via an attribute called `displaystyle` which was either the string 'true' or the string 'false' ()the rules and the term were derived from The TeXbook).  [MathML-Core introduces](https://mathml-refresh.github.io/mathml-core/#the-math-style-property) the `math-style` CSS property and defines how it works for rendering and layout. It maps this attribute's values as a presentational hint to the CSS property for reasons of compatibility with widely deployed content and the existing ecosystem of tools, but strongly recommends authors use CSS.

Tests in https://github.com/web-platform-tests/wpt/tree/master/css/css-fonts/math-script-level-and-math-style

**Comment by fred-wang** [comment]
@bkardell @fantasai  Given https://github.com/w3c/csswg-drafts/pull/5536#issuecomment-697114884 and that the definition is already present in https://w3c.github.io/mathml-core/#the-math-style-property I guess we can close this, as that was done for https://github.com/w3c/csswg-drafts/issues/5388 and https://github.com/w3c/csswg-drafts/issues/5389  ?
