### ISSUE TITLE
[math] "cramped" script style

### ISSUE THREAD

**Issue by bkardell** [w3c/csswg-drafts#5388]
(Part of #5384 - MathML Core related CSS)

Mathematical rendering contains lots of 'scripted' concepts - that is, subscripts, superscripts, underscripts, overscripts, tensors and so on.  The way that they are positioned is contextually dependent. A (simple) example of this can be seen in the case of exponents within a square root vs normally. The example below, illustrates this, in which the exponent is tighter to the base when inside a square root.

![example of contextually dependent rendering of an exponent](https://mathml-refresh.github.io/mathml-core/examples/example-math-shift.png)

TeXbook (and the spec algorithms) refer to this as "cramped" style.  [MathML-Core introduces the `math-shift` property](https://mathml-refresh.github.io/mathml-core/#the-math-shift) to expose these two modes with values `normal` (default) and `compact`.  Recommended UA styles apply the common rules, but leave authors the ability to tweak and extend.

**Comment by AmeliaBR** [comment]
So, is the suggestion to add a new property, or to add new values to baseline-shift / vertical align? I'd prefer the second, so it would be a case of `vertical-align: compact-super` vs `vertical-align: super`.

But then we might need some magic behavior for the new keyword if it is supposed to work correctly with both manually-sized superscripts and superscript glyphs from the font.
