### ISSUE TITLE
[css-cascade-3] Publish Cascading and Inheritance 3 as a REC

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#5396]
We should close the only open issue, #5313 (there's a PR for it: #5358). In the [test suite](https://test.csswg.org/harness/results/css-cascade-3_dev/grouped/), 96 of 105 required tests meet CR exit criteria.

There doesn't seem to be any non-trivial change since the last CR.

**Comment by fantasai** [comment]
96/105 is not 100%. Has anyone analyzed the failures to see why they're failing? Also, do we actually have coverage of the spec? Number of tests isn't an indicator of coverage, it's just a number that doesn't mean very much.

**Comment by frivoal** [comment]
A fair few of the missing tests involve things like "load this file as the UA style sheet", or "select the alternative stylesheet", which aren't things that browsers are required to be able to do. So maybe they're not quite test failures. But nonetheless, we would indeed need a coverage analysis and an actual look into what tests are failing / missing and why to see if we're good to go or not.

**Comment by fantasai** [comment]
Implementation Report: https://drafts.csswg.org/css-cascade-3/implementation-report

**Comment by fantasai** [comment]
I added a few tests. Assuming the CSS2 test suite has full coverage of its own features, we now have full coverage of Level 3.

**Comment by svgeesus** [comment]
> A fair few of the missing tests involve things like "load this file as the UA style sheet", or "select the alternative stylesheet", which aren't things that browsers are required to be able to do.

Those should be marked as optional tests in that case. IIRC CSS2 required this, so it has already been tested in the past.

**Comment by frivoal** [comment]
I think the behavior to be followed *if* there is a different file as the UA style sheet, or *if* the UA let's the user selects an alternative stylesheet is required. However, whether or not these features exist in the first place is largely a matter of UX, and we cannot really required anything.

Regardless, AFAIK, the spec has not changed with respect to these things from CSS2, and CSS2 is a REC already, so we're fine here.

@fantasai's report shows that we're clean on things that are new to level 3, so all in all, I think we're good to go.

**Comment by svgeesus** [comment]
Agreed with Agenda+ to discuss transition to Proposed Recommendation. 
Assuming that succeeds, who will open the issue on the transitions repo?

**Comment by svgeesus** [comment]
[Proposed Rec requested 9 Sept 2020](https://github.com/w3c/transitions/issues/264), [approved 18 Dec 2020](https://github.com/w3c/transitions/issues/264#issuecomment-748273582)

Publication as PR requested 21 Dec, expected 22 Dec

**Comment by fantasai** [comment]
REC published https://www.w3.org/TR/2021/REC-css-cascade-3-20210211/
