### ISSUE TITLE
[web-animations-1] Play state of an animation with an unresolved timeline

### ISSUE THREAD

**Issue by kevers-google** [w3c/csswg-drafts#5400]
Recently the rules for determining the play state of an animation were updated to add the condition of having an unresolved start time for the animation to be idle. This constraint was added to accommodate non-monotonically-increasing (i.e. scroll) timelines which should not be flagged as idle if they have a start time but an inactive timeline; however, it does break the play state for cases where the timeline is unresolved.  Explicitly setting the start time of an animation with an unresolved timeline should leave the animation in an idle state. This issue can be resolved by relaxing the constraint to require that either the start time or the timeline be unresolved.

https://drafts.csswg.org/web-animations-1/#play-states

**Comment by kevers-google** [comment]
cc @birtles @ogerchikov @majido @flackr 

Related to issue: https://github.com/w3c/csswg-drafts/issues/2066

Changes to how play state is calculated for supporting scroll timelines introduced changes in the behavior of set timeline. These side effects would not have been visible in WPT tests in Blink since setting the timeline was not supported. 

Suggesting the following change to play state:

 All of the following conditions are true:
    The current time of animation is unresolved, and
    the start time of animation is unresolved **or the timeline is unresolved**, and
   animation does not have either a pending play task or a pending pause task,

→ idle

If the timeline is explicitly set to null, should the play state be allowed to be in a running state?  

With this change, the changes in support of scroll timelines do not introduce inconsistencies between browsers for null timelines.

**Comment by flackr** [comment]
Just for clarification, by unresolved timeline I assume you mean there is no associated timeline for the animation?

**Comment by kevers-google** [comment]
Correct

**Comment by flackr** [comment]
This makes sense to me. Can you make a PR?

We have some testing of setting timelines in web-animations/timing-model/animations/setting-the-timeline-of-an-animation.html and Firefox and Safari are passing these tests - do we have test coverage which was broken by this change and/or will we after we make it?

**Comment by kevers-google** [comment]
Firefox is passing due to not having the test for startTime being unresolved in the idle check. 
https://searchfox.org/mozilla-central/source/dom/animation/Animation.cpp#480

The following test was updated with the algorithm change and currently fails on Firefox and Safari:
wpt/web-animations/timing-model/animations/setting-the-timeline-of-an-animation.html

Once setTimeline is supported in Blink the following tests will have new failure reasons based on the plate state:
wpt/css/css-animations/event-dispatch.tentative.html
wpt/css/css-transitions/event-dispatch.tentative.html

See the tests titled "Active -> Idle, setting Animation.timeline = null"

Gladly make the PR

**Comment by birtles** [comment]
> however, it does break the play state for cases where the timeline is unresolved. Explicitly setting the start time of an animation with an unresolved timeline should leave the animation in an idle state.

I'm not sure I quite follow this part. I _think_ it actually makes sense to me that the animation is finished/running at this point?

> Suggesting the following change to play state:
> 
> All of the following conditions are true:
> The current time of animation is unresolved, and
> the start time of animation is unresolved **or the timeline is unresolved**, and
> animation does not have either a pending play task or a pending pause task,
> 
> → idle

Is there precedent for distinguishing between the lack of an associated timeline and an associated but inactive timeline? I thought we always treated those two as the same? (i.e. the lack of an associated timeline can be thought of as being associated with a "null timeline" that is always inactive).

> If the timeline is explicitly set to null, should the play state be allowed to be in a running state?

I _think_ so?

**Comment by kevers-google** [comment]
We have precedence for the play state being restricted to the idle or paused when the timeline is explicitly null. This was captured in the following WPT test:
  * wpt/web-animations/timing-model/animations/setting-the-timeline-of-an-animation.html
      * After clearing timeline on finished animation it is idle
      * After clearing timeline on running animation it is idle
 
The expectations were updated in  https://chromium-review.googlesource.com/c/chromium/src/+/2150687; however, the expectations no longer align with the test description.  The text associated with these tests could be updated if the new behavior is in fact what we want. 

Though one can think of an animation with a null timeline as one that is always inactive, the distinction is that the animation will never tick until the timeline is changed.  In the case of scroll timelines, the inactive state is transient. 

A benefit of restoring the previous behavior for play state of a null timelines is that we then have consistent behavior across browsers.  Mutable timelines is likely to have cross browser support before scroll timelines. Having said that,  I'm OK with going either way on this, but would like to see consistency with the test expectations and descriptions.

**Comment by kevers-google** [comment]
Missed two other relevant tests (again from setting-the-timeline-of-animation.html):
    * After setting timeline on an idle animation with a start time it is running
    * After setting timeline on an idle animation with a sufficiently ancient start time it is finished

Both of these tests assert that an animation with a null timeline remains idle after the start time is set.  Again, the tests could be updated if we are content with the implication of recent spec changes on the play state.

**Comment by birtles** [comment]
> We have precedence for the play state being restricted to the idle or paused when the timeline is explicitly null. This was captured in the following WPT test:
> 
> * wpt/web-animations/timing-model/animations/setting-the-timeline-of-an-animation.html  
>   * After clearing timeline on finished animation it is idle
>   * After clearing timeline on running animation it is idle
> 
> The expectations were updated in https://chromium-review.googlesource.com/c/chromium/src/+/2150687; however, the expectations no longer align with the test description. The text associated with these tests could be updated if the new behavior is in fact what we want.

I think the tests and descriptions are somewhat irrelevant to determining the specified behavior. They should simply be capturing what the spec text says so what I'm curious about is if the spec ever differentiates between the lack of an associated timeline and an associated but inactive timeline for the purposes of timing calculations. If it doesn't (and as best I recall it doesn't), it seems like we probably shouldn't introduce that distinction here.

> Though one can think of an animation with a null timeline as one that is always inactive, the distinction is that the animation will never tick until the timeline is changed. In the case of scroll timelines, the inactive state is transient.

Yes, but I wonder if that should matter? With regards to the determining the play state, it seems like it shouldn't depend on whether the timeline could become active or not?

> Having said that, I'm OK with going either way on this, but would like to see consistency with the test expectations and descriptions.

Yes, agreed!

I find these changes very difficult to reason about (which is really my fault for failing to get spec in a better shape before it was shipped) and was very concerned about the original change to the play state algorithm (which added the condition for an unresolved start time). Assuming we stick with that, however, I think we should _not_ add the condition regarding an unresolved timeline because:

* We typically treat the lack of an associated timeline and an inactive timeline as the same for the purpose of timing calculations
* It would be odd to further extend this condition to include inactive timelines because then the play state would suddenly change when the timeline became active and it probably shouldn't do that (except with regards to the finished state)

**Comment by kevers-google** [comment]
I'm cool with leaving the play state procedure as is, and updating the test expectations. Unfortunately, most of the behavioral changes were not visible due to lacking mutable timeline support in Blink.  For the most part, these changes will not affect behavior in stable releases since mutable timelines have not shipped. 

One case where a difference is visible:

const animation = new Animation(..., null);
animation.startTime = ...;
  
This example, will produce 'runniung' on Chrome, and 'idle' on Safari and Firefox (Last I checked, they do not have the unresolved start time constraint in the play state calculation).  Having said that, without mutable timeline support this animation is not particularly interesting.

Another side effect of the recent play state change is that we will not longer cancel a running CSS transition or animation if the timeline is explicitly set to null.  Perhaps this is a good thing as the new behavior is consistent with not suddenly changing state when the timeline becomes inactive (other than no longer being able to be in a finished state). Nonetheless, I believe this is covered by WPT tests that will need to be updated to reflect the behavior of the specced behavior.

@flackr Thoughts?

**Comment by kevers-google** [comment]
Correction to the last comment. We'll still see transitions in the phase of the animation when transitioning to a null timeline. So, we can have the animation with playState = 'running' but phase='idle'. Tested here:

external/wpt/css/css-transitions/event-dispatch.tentative.html

**Comment by flackr** [comment]
@kevers-google I don't think we need to be concerned if there will be slight behavioral changes with animations on null timelines. I think @birtles is right that so far the spec has not differentiated not having an associated timeline from having an inactive timeline, and it seems like we don't need to do this to get our desirable trait of animations continue running if the timeline goes inactive and active again. We should update the test expectations to match the spec.
