### ISSUE TITLE
[css-lists] Consider new value for counter-reset

### ISSUE THREAD

**Issue by lcchueri** [w3c/csswg-drafts#5402]
Use case: To help solve issues #[3746](https://github.com/w3c/csswg-drafts/issues/3746) and #[5389](https://github.com/w3c/csswg-drafts/issues/5389) , which both needs counting sublevels of sub/super scripts for MATHML.

To use as many generic CSS properties for MathML as possible, I propose to use the list counters in a more generic way:

Considering also, from issue #[1026](https://github.com/w3c/csswg-drafts/issues/1026), _enabling the use of counter() inside calc()_  for property font-size, these counter may be used to control font-size and other styles.

Proposition A:
Consider **<counter-name> parent** as new value for **counter-reset**
**\<counter-name\> parent** value removes the innermost counter that originates from a sibling or its child, instantiating a counter of given name from parent element with the parent counter value.

for example, UA style for sup/sub element would be something like

sub, sup {
counter-reset: countSubLevel parent;
counter-increment: countSubLevel +1;
font-size: calc(20px-counter(countSubLevel));
}

Proposition B:
Or, instead of new value for counter-reset, may be a new property named counter-remove, as:

property: counter-remove
value: \<counter-name\>+ | none
inherited: no

counter-remove removes counters names from counter set of the element that comes from siblings and their child.

It happens after New Counters are instantiated and before counter values are incremented.

**Comment by faceless2** [comment]
This specific proposal doesn't look like it would solve the case for MathML font sizing. The algorithm makes reference to two constants from the OpenType MATH table when the internal script-level counter is 1 or 2, falling back to a power function (0.71 ^ level, IIRC) beyond that. You couldn't represent that with a calc() expression.

I'm also against `counter-remove`, solely because counter scoping rules are complicated enough already.

However, the concept of creating a new counter but copying its value from the parent - your "`counter-reset: countSubLevel parent`" - is pretty trivial to implement, for us anyway. It also feels like it somehow might be incredibly useful, I just can't quite put my finger on why. In your example you're effectively using it to count how deep your element is in the element tree. I wonder what other use-cases we could find for that?

**Comment by lcchueri** [comment]
The purpose of both propositions is to produce information measurable about depth (sub-level) of the structure.  

The example I gave with **font-size: calc(20px-counter(countSubLevel))** was a silly one. Just to demonstrate that information produced about sub-level being consumed at other place.

For the remaining of the problem, creating new functions like **power(n, m)** may help. Or one like [*decode*](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions040.htm) function of Oracle-database-SQL for select by the sub-level which expression to use.

Propose these expressions **power** and **decode** for the complete solution is not in the scope. To have a way to expose depth by reusing list counters is the proposition.

**Comment by lcchueri** [comment]
Republishing A-proposition, hoping to do a better explanation.

The A-proposition **counter-reset: <counter-name> parent**, first copies all counters from sibling (or parent), as [section 4.4.1](https://www.w3.org/TR/css-lists-3/#inheriting-counters), and changes how it operates in step 3 of algorithm of [section 4.4.2](https://www.w3.org/TR/css-lists-3/#inheriting-counters), copying value from parent instead a given integer.

BEGIN

 1. Let counters be element’s CSS counters set.

 2. Let innermost counter be the last counter in counters with the name name. If innermost counter’s originating element is element or a previous sibling of element, remove innermost counter from counters.

 3. Append a new counter to counters with name name, originating element element, and 
 
  1. If initial value is an integer initializes with this.

  2. Else if string **parent**, gets the initial value from parent element's counter with the same name.

END

**Comment by lcchueri** [comment]
Republishing B-proposition, with algorithm.

B) a new property **counter-remove** 

property: counter-remove
value: <counter-name>+ \ none
inherited: no

operation of **counter-remove** would precede counter-reset.

It removes named counters coming from the preceding sibling (if exists), so can be reused the named counters of the parent element (if they are in parent's counter set)

This way, each sibling will have the same start value coming from it's parent. So post operation counter-increment, will indicate the same level value for all siblings.



Section [4.4.1](https://www.w3.org/TR/css-lists-3/#inheriting-counters) algorithm for **counter-remove**. New steps 3 and 4 expands from original algorithm step 3.

BEGIN
 
1. Let _element counters_ be an initially empty CSS counters set representing element’s own CSS counters set.

2. If _element_ is the root of its document tree, return. (The element has an initially-empty counter map and inherits nothing.)

3. If the _element_ has a preceding sibling

  1. Let _counter source_ be the CSS counters set of _element_’s preceding sibling.

  2. Let _sibling element_ be the _element_’s preceding sibling

  3. Let _counter to remove_ be the CSS property counter-remove named counters.

  4. For each (_name_, _originating element_, _value_) of _counter source_:

    1. If _counter to remove_ also contains a counter with the same _name_ and _originating element_ is the _sibling element_, then remove a copy of _value source_’s counter (_name_, _originating element_, _value_) from _counter source_.

4. Else Let _counter source_ be the CSS counters set of _element_’s parent.

5. Let _value source_ be the CSS counters set of the element immediately preceding _element_ in tree order.

6. For each (_name_, _originating element_, _value_) of _value source_:

  1. If _counter source_ also contains a counter with the same _name_ and _originating element_, then append a copy of _value source_’s counter (_name_, _originating element_, _value_) to _element counters_.

END

**Comment by fantasai** [comment]
The purpose of counters is to count siblings, not depth. If math needs a depth counter, let's add a depth counter as a separate feature.

**Comment by lcchueri** [comment]
@fantasai , I see your point.
 
Reviewing @faceless2 comment and reviewing issues #[3746](https://github.com/w3c/csswg-drafts/issues/3746) and #[5389](https://github.com/w3c/csswg-drafts/issues/5389), I see I misunderstood the problem. Count depth needs a arbitrary start point in the structure, values would be absolute and would not help calculation of properties relative to the parent's properties. And also would inform which kind of elements were between the start of counting and the point being evaluated. So would be a problem to arbitrary choose which element to start counting.

The core of of the problem of both issues just needs knows de upper element's properties, and calculate its own properties from it. So, counting depth is useless.

I conclude the entire concept of counting depth is useless. I apologize.
