### ISSUE TITLE
[css-overflow] Is it necessary to support nested scrollers for html and body?

### ISSUE THREAD

**Issue by george-steel** [w3c/csswg-drafts#5403]
Moved from <https://crbug.com/580570> (2016):

> The CSS spec says that "html { overflow: scroll; }" and "body { overflow: scroll; }" are equivalent - in both cases you're just setting the scrolling mode of the viewport.  But "html, body { overflow: scroll; }" is special - in that case body actually get's its own scrolling box independent from the viewport.

> This is widely supported, but can be a little confusing. Let's explore whether this behavior is really necessary for web compatibility.  We could potentially simplify things by saying that overflow applied to body ALWAYS applies to the viewport.

This is currently the case in [css-overflow-3](https://drafts.csswg.org/css-overflow-3/#overflow-propagation) which says that
> UAs must apply the overflow-* values set on the root element to the viewport. However, when the root element is an [HTML] html element (including XML syntax for HTML) whose overflow value is visible (in both axes), and that element has a body element as a child, user agents must instead apply the overflow-* values of the first such child element to the viewport. The element from which the value is propagated must then have a used overflow value of visible.

This further clarified in [cssom-view](https://drafts.csswg.org/cssom-view/#potentially-scrollable) and is the current behavior in both chrome and firefox as confirmed by https://codepen.io/george-steel/pen/mdPdQgw, which produces two sets of scrollbars.

Is there any use for this behavior, or should be simplified?

**Comment by emilio** [comment]
How do you plan to simplify it? Just making the `<body>` never scrollable? (Just curious, because I'm not 100% sure if it'd be an actual simplification implementation wise otherwise).

**Comment by george-steel** [comment]
Later in the bug, the proposal was to make the body never to be a scrollable box, and for the viewport to be scrollable if either the html or body elements (or both) should scroll. (Note: I didn't write the original bug, just moved it here in the triage process.)

**Comment by frivoal** [comment]
The current behavior is weird, but as far as I know has been that way forever, so I'd be very surprised if it was web-compatible to simplify. If there's evidence that we can change things without breaking loads of sites, let's hear it, this could be a chance to get rid of one wart on the platform. But I'm skeptical that we can actually change this.

**Comment by george-steel** [comment]
I can't think of any uses this might break, but I would be curious to see a counterexample if you can come up with one. The only one I can think of is trying to put a border around the effective viewport (which would already break with pinch-zoom.

**Comment by emilio** [comment]
Something that would break would be:

```css
html { overflow: auto }
body { overflow: hidden; height: 100vh; width: 100vw; }
```

With a lot of tall content. But hard to know whether somebody would do that.

**Comment by frivoal** [comment]
Agenda+ to ask the WG if there is implementer interest in exploring this. (if not, we should close)
