### ISSUE TITLE
[css-overflow] overflow-clip-margins -> clip-box + hit-margin

### ISSUE THREAD

**Issue by c-smile** [w3c/csswg-drafts#5404]
Document https://www.w3.org/TR/css-overflow-3 defines [overflow-clip-margins](https://www.w3.org/TR/css-overflow-3/#propdef-overflow-clip-margin).

Problem is that `overflow-clip-margin` does not address event handling and associated mouse hit test issues.

Consider this:
```
textarea {
   overflow: clip;
   overflow-clip-margin: 100px;
}
```
How UA shall handle clicks on text rendered outside of padding box? 

To address this I propose to replace `overflow-clip-margin` by `clip-box` property instead:
```
clip-box: default | content-box | padding-box | border-box | hit-margin-box;
```
Where hit-margin-box tells that clip box has to be set to box defined by `hit-margin` property.
`hit-margin`  is similar to `margin` but has no effects other than expanding (or shrinking) mouse hit-test area of the element.

Having the clip-box in place will also help to solve other clipping problems. Consider this

```
  input[type="search"] {
     padding-left: 2em; /* room for the icon */ 
     background: url(looking-glass-icon.svg) no-repeat 0.5em 50%;
     overflow:clip; 
     clip-box: content-box; /* text will not be drawn on top of the icon */
  }
```
There is no way in CSS to achieve this effect at the moment rather than composing such basic element from multiple DOM elements. 

Yet `hit-margin` will solve other usability issues, like:
```
@media handheld {
   button.small {
     size: 1em;
     hit-margin: 2em; /* extending hit margin on mobiles so it can be clicked by finger */
   } 
}
```

**Comment by tabatkins** [comment]
Inflating the hit area is a separate issue; it's not something we were aiming to do with this property at all.

**Comment by c-smile** [comment]
> Inflating the hit area is a separate issue; it's not something we were aiming to do with this property at all.

If it is a separate issue then it should be clearly stated how `overflow-clip-margin` a) affects hit-testing and b) how it will interact with "hit-margin" (or whatever property it will be).

But the `overflow` concept (scrolling and clipping) directly relates to hit testing. So I think that something  like `hit-margin`  has to be a part of css-overflow module anyway.

**Comment by tabatkins** [comment]
It affects hit testing to the degree that `overflow: clip` does; it just modifies the size of the clipping rectangle being applied.

It does not *grow* the hit-testing region on its own, which is what your proposal is about; that's why you're suggesting a new, separate feature.

**Comment by chrishtr** [comment]
Unfortunately, hit testing is poorly specified at present.

However, I think it's pretty clear already how `overflow-clip-margin` should affect hit testing: content not clipped out is visible to hit testing; content clipped out is not. The hit testing region is not grown on its own by this feature.

**Comment by tabatkins** [comment]
No edits needed here, since this just leans on the (relatively unspecified, but this doesn't make it any worse) hit-testing behavior of overflow:clip elements.  Otherwise the feature is currently WAI.
