### ISSUE TITLE
[css-sizing-4][css-flexbox] How to calculate the content-based minimum sizes when applying aspect-ratio on the flex container

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#5406]
This question is from the tentative [wpt](https://github.com/web-platform-tests/wpt/blob/master/css/css-sizing/aspect-ratio/flex-aspect-ratio-008.tentative.html) (note: its expected result is a 100x100 green square):
```
<div style="display: flex; flex-direction: column; flex-wrap: wrap; width: 200px; aspect-ratio: 4/1;">
  <div style="background: green; width: 100px; height: 50px;"></div>
  <div style="background: green; width: 100px; height: 50px;"></div>
</div>
```
This is a little be unclear to me about how to apply automatic content-based minimum sizes (from [aspect-ratio](https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum)) on the flex container.

Based on the spec in [[css-sizing-4]](https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum):
> In order to avoid unintentional overflow, the automatic minimum size in the ratio-dependent axis of a box with a preferred aspect ratio that is neither a replaced element nor a scroll container is its min-content size clamped from above by its maximum size.

It seems this rule also applies to the flexbox. So, based on this rule and [the determination of the main size of the flex container in [css-flexbox]](https://drafts.csswg.org/css-flexbox-1/#algo-main-container), if the main size of the flex container is computed by aspect-ratio, we may have to increase the main size based on its content, right?

So the questions are:
* Do we just use the _outer hypothetical main size_ of each flex item to calculate the main size, and compare this with the main size of the flex container from aspect-ratio (i.e. `flexContainerMainSize = std::max(mainSizeFromContent, mainSizeFromAspectRatio)`)?
* What happens if those flex-items don't have definite used flex basis? Should we treat all of them as min-content, and get the min-content main size for the flex container, and then compare this with the main size of the flex container (from aspect-ratio)? This may do multiple times for flex layout.

I'm not sure which way is reasonable for flexbox, or maybe I miss something.

Perhaps we should address/insert a new step in which we take automatic content-based minimum sizes (for aspect-ratio) on the flex container into account, in [flex layout algorithm in [css-flexbox]](https://drafts.csswg.org/css-flexbox-1/#layout-algorithm).

Thanks.

cc @fantasai @bfgeek @dholbert @cbiesinger

**Comment by cbiesinger** [comment]
I don't remember what I was thinking when I wrote the testcase but I now think the testcase is wrong and we should use the aspect-ratio based height for determining the line length for wrapping, i.e. this specific testcase should be 50px high. The automatic min height should only come into play if a single flex item is taller than the aspect-ratio derived height.

This matches @fantasai 's initial thought.

@tabatkins thoughts?

**Comment by dholbert** [comment]
@BorisChiou: 
> Do we just use the outer hypothetical main size of each flex item to calculate the main size, and compare this with the main size of the flex container from aspect-ratio (i.e. flexContainerMainSize = std::max(mainSizeFromContent, mainSizeFromAspectRatio))?

For single-line flex containers, yeah, I think that's a reasonable approximation of what the spec asks for.

Strictly speaking: to determine the min-content size here, we should be following https://drafts.csswg.org/css-flexbox-1/#intrinsic-main-sizes (which is effectively trying to reverse-engineer the flex algorithm to produce the flex container size that would avoid overflow), I think.

For multi-line flex containers, though, there's a special-case at the bottom of that section:
```
  However, for a multi-line container, it [the min-content main-size]
  is simply the largest min-content contribution of all the flex items
  in the flex container.
```
where `min-content contribution` is defined at https://drafts.csswg.org/css-flexbox-1/#intrinsic-item-contributions .

That special-case means biesi's assessment here is wrong, and we should technically wrap in this testcase. (Its flex container's min-content height [the lower-bound that aspect-ratio can shrink it to here] is 50px, which comes from the individual items, rather than coming from the sum of the items' heights.

**Comment by fantasai** [comment]
As noted by @dholbert, the min-content size of a flex container is explicitly defined in the Flexbox spec. In this case it ends up being 50px (the largest min-content height among the flex items). The `aspect-ratio` sets the height based on the width--which is definite, thus resulting in a definite height (50px), which remains unaffected by the `min-height` (also 50px). That resulting definite height is then used to constrain the line length when wrapping the flex items into flex lines.

Assuming everyone agrees that this already-specified behavior is ideal, we think we can close this issue as no change? And get that tentative WPT fixed, of course.

**Comment by BorisChiou** [comment]
Thanks for these feedback. I'm OK with no change and close this issue. I can update the tentative WPT.

**Comment by cbiesinger** [comment]
Test updated in https://github.com/web-platform-tests/wpt/pull/26147

Can probably close this and remove the "Needs Testcase (WPT)" label?
