### ISSUE TITLE
[css-values-4] Consider giving viewport units more definition

### ISSUE THREAD

**Issue by abrad1212** [w3c/csswg-drafts#5408]
Mobile browsers are really different in calculating such units. Mobile Safari doesn't account for the address bar, nor does it calculate for the bottom navigation bar in the app. This has resulted in really _hacked together_ solutions that break every time iOS updates. Mobile chrome does something similar.

A definition such as _Equal to 1% of the height of the initial containing block. Not including obstructions to the viewport such as address bars/URL bars, bottom navigation bars, and or anything else that could obstruct any part of the viewport._

Sorry if this doesn't belong here, this is something that has been frustrating me for some time now.

**Comment by jonjohnjohnson** [comment]
I think you'll see movement in solving this problem in these issues:

- https://github.com/w3c/csswg-drafts/issues/4329
- https://github.com/w3c/csswg-drafts/issues/4691
- https://github.com/w3c/csswg-drafts/issues/5232

If any of those are on the right track, you might wanna add your thoughts to them and close this to consolidate things.

**Comment by jonjohnjohnson** [comment]
@tabatkins should this be closed in favor of what's been happening in #6454 / #6453
