### ISSUE TITLE
[css-grid-1] stuff I noticed while publishing grid 1

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5427]
$ bikeshed spec
FATAL ERROR: &lt;l> element doesn't contain a recognized autolinking syntax:
&lt;l spec="css-align-3">&lt;fake-maybe-placeholder bs-autolink-syntax="''align-self/center''">align-self/center&lt;/fake-maybe-placeholder>&lt;/l>
ERR Did not generate, due to fatal errors

**Comment by svgeesus** [comment]
Not that I can find such a &lt;l. element anywhere, but I have to use `bikeshed -f` anyway to generate.

**Comment by tabatkins** [comment]
Hm, could you provide the full source you're using that obtains this? The current source doesn't show this error; the only output is a warning about WPT stuff.

**Comment by svgeesus** [comment]
I'm not getting that error anymore either. It may have been the specific bikeshed revision in use? Closing as cannot replicate
