### ISSUE TITLE
[web-animations-1] Animation::CurrentTime/ID WebIDL

### ISSUE THREAD

**Issue by verbessern** [w3c/csswg-drafts#5429]
I think, that because the current time is actually a value that is calculated in "4.4.3. The current time of an animation", then in the WebIDL the `current time` should not be defined as an attribute, but as two functions: get/set. That will also remove the first step of the "silently set the current time" algorithm because the seek time can be defined to be a `finite double` in the "set" function. The "get" will remain to be unrestricted double as it is now. 

The `id` attribute of an `Animation`, that is only used for debug purposes, and by my opinion its not a task of a specification to define how the objects are going to debugged, neither to how they will be distinguished between each other, if that is nowhere used in the specification itself. If other specifications are using that field, then maybe that should be defined in the relevant specifications and their WebIDL.

**Comment by birtles** [comment]
> I think, that because the current time is actually a value that is calculated in "4.4.3. The current time of an animation", then in the WebIDL the `current time` should not be defined as an attribute, but as two functions: get/set.

It's quite acceptable to use an attribute to report a calculated value and this particular approach was taken to match the [`HTMLMediaElement.currentTime`](https://html.spec.whatwg.org/multipage/media.html#media-elements) attribute. Furthermote, this is not shipping in all major browser engines so changing it would not be Web compatible.

> The `id` attribute of an `Animation`, that is only used for debug purposes, and by my opinion its not a task of a specification to define how the objects are going to debugged

This simply provides a common metadata field that can be conveniently set using the `animate()` method and which browser DevTools can agree upon as the identifier to use when displaying animations.
