### ISSUE TITLE
[css-fonts-4] [varfont] Relative weight / width adjustments

### ISSUE THREAD

**Issue by behdad** [w3c/csswg-drafts#543]
Petr van Blokland asked me to relay this.  It would be very handy if one can say things like:
```
font-weight: +50; 
font-width: -10;
```
I don't know if that's possible using current CSS technology (calc?), but I agree it's very interesting.  That's basically an extension of "bolder" / "lighter".

**Comment by behdad** [comment]
For reference: https://github.com/w3c/csswg-drafts/issues/498

**Comment by petrvanblokland** [comment]
It also relates to issue #536. I posted some more thoughts and case descriptions there.

**Comment by litherum** [comment]
Seems to me this is the same as https://github.com/w3c/csswg-drafts/issues/536. If I am mistaken, please feel free to reopen this issue.
