### ISSUE TITLE
[css-sizing-4] Allow specifying only one dimension for intrinsic sizing

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#5432]
We have a definition of [contain-intrinsic-size](https://drafts.csswg.org/css-sizing-4/#intrinsic) which specifies both width and height dimensions of the intrinsic size.

For a case of vertical scrolling, we found that it is a common desire to have the width of an element be as wide as the scroller and the height be dictated by contain-intrinsic-size. This is particularly useful with [content-visibility: auto](https://www.w3.org/TR/css-contain-2/#using-cv-auto) which puts in size containment when the elements scroll off screen.

We've been recommending things like `contain-intrinsic-size: 1px 400px;` where 400px is the desired height, but it's a bit awkward. It would be nicer and more ergonomic to be able to specify just the height of the intrinsic size.

Is it possible for us to make the contain-intrinsic-size a shorthand for contain-intrinsic-width and contain-intrinsic-height (and possibly block-size and inline-size?) with `auto | <length>` or something similar

That way, developers would have an option of specifying just one of the two dimensions

/cc @tabatkins @chrishtr

**Comment by vmpstr** [comment]
To clarify, for block containers:

`contain-intrinsic-height: 500px;`

would be equivalent to

`contain-intrinsic-size: 0 500px;` (unless of course there is a `contain-intrinsic-height` specified).

**Comment by vincentriemer** [comment]
I like the idea of having shorthand properties, but it does bring up the question of how this works in relation to logical properties.

While I don't see it in the spec, `contain-intrinsic-size` could *theoretically* map to `block-size` and `inline-size` without changing its name but with the shorthand properties there'd have to be both `width/height` and `inline-size/block-size` variants.

**Comment by vmpstr** [comment]
I think the spec talks about physical dimensions (width / height) as being the two components of `contain-intrinsic-size`. At the very least it would have to specify one or the other, so that different implementations can agree.

But you bring up a valid point that if this becomes a shorthand, then we really would want 4 new properties: 2 for physical dimensions and 2 for logical dimensions.
