### ISSUE TITLE
[css-scroll-snap] More granular control over scroll-snap-stop

### ISSUE THREAD

**Issue by johannesodland** [w3c/csswg-drafts#5467]
The ``scroll-snap-stop`` property currently supports two values, either ``normal`` or ``always``. (https://drafts.csswg.org/css-scroll-snap-1/#scroll-snap-stop)

In a scroll container with many snap positions this has the following effects:
- normal: It's easy to scrub through the container to get to any part, but it's easy to miss a snap position without noticing.
- always: It's really hard to scroll through the container, but the user does not miss a single snap position.

When using scroll snap for longer scroll containers the author has to choose between these two extremes. A more granular approach could give more control to the author. I.e. a property called ``scroll-snap-strength`` where a value of 0 equals ``normal`` and 1 equals ``always``.

As the underlying used for snapping is left for the UA to decide ``strength`` might not be the best word for this property. The intention is to give more granular control than the two extremes that are specced today.

Example scroll snapping article: 
https://www.nrk.no/hvis-insektene-forsvinner-1.15029017

**Comment by SebastianZ** [comment]
Note that `scroll-snap-stop` is meant to be set on elements _within_ the scroll container, not on the scroll container itself. That already provides granular control over where the scroll operation should end. At least that's what I understand when reading the spec., though it could be a little bit clearer on that, e.g. by saying "Applies to: all elements within a scroll container" instead of just "all elements".

As far as I can see, the example page you linked to currently doesn't make use of `scroll-snap-stop`, so it's hard to say what the expected effect is in that case, but that page could use `scroll-snap-stop: always;` on important slides, so the scroll operation definitely stops there while other slides are scrolled over.

Sebastian

**Comment by SebastianZ** [comment]
Ah, I just saw that the specification _is_ already quite clear on that by placing it in the "Aligning Scroll Snap Areas: Properties on the elements" section.

Sebastian

**Comment by tabatkins** [comment]
Can you elaborate more on what sort of behavior you're wanting here?  In particular, an example page where you have a lot of stops relatively close together, and you want (some of?) them to somehow be "stronger" than the default stop distance, would be helpful, as I don't understand quite what behavior you're wanting.

**Comment by johannesodland** [comment]
I've built two code pen examples to illustrate the current behaviour as a starting point for the discussion. 

In these examples we use CSS Scroll Snap for "full page" scroll snapping. Each element have a height of 100vh and are of equal importance.

**scroll-snap-stop: normal;**
https://codepen.io/johannesodland/pen/WNwEbEX 

When set to `normal` it is easy for the user to "overshoot" when scrolling (At least in some UA implementations). The user might scroll past a few snap positions when trying to scroll to the next. On the plus side, it is easy to scroll through the container to snap points further down.

We've received feedback from users not feeling in control. 

![scroll-snap-stop-normal](https://user-images.githubusercontent.com/175195/91698749-81393d80-eb73-11ea-8fda-61b2989f957c.gif)


**scroll-snap-stop: always;**
https://codepen.io/johannesodland/pen/LYNjEYv

When set to `always` it is impossible to "overshoot". Scrolling stops at the snap-point. It is however difficult to scroll fast to a snap point later in the scroll container. The user has to scroll through each snap point, which can be tedious.

![scroll-snap-stop-always](https://user-images.githubusercontent.com/175195/91698768-89917880-eb73-11ea-8c27-e1c0d6300b79.gif)


With the current spec authors are left to choose between two extremes with their respective tradeoffs. With `normal` it is easy to overshoot when scrolling (depending on UA implementation). With `always` it is tedious to scroll through many snap points. 

If we use physics to illustrate, we can say that the scrolling content has momentum, and that each snap point exerts a force on the content. Snap points with `normal` have a weak force that is easy to scroll by, and snap points with scroll-snap: `always` have a strong force. 

Could there be a way to give authors more granular control over how strongly the content snaps?

**Comment by SebastianZ** [comment]
I get the point now. So the request is to make the snap positions "stickier" than `normal` but not enforce to stop at them like `always` does.

One thing to note here is that the spec. currently leaves the definition of the snapping mechanics undefined, meaning that UAs can implement different behaviors for the `normal` value. So it might rather be an implementation issue you're facing.

I think the question here is whether you just want `normal` to be stickier or if there are use cases in which you'd want some scroll snap areas to be stickier than others (but not force snapping to happen).

Sebastian

PS: Just for reference, there's a bug in the Chromium implementation of `scroll-snap-stop: always;`, see https://bugs.chromium.org/p/chromium/issues/detail?id=1122774.

**Comment by johannesodland** [comment]
> I get the point now. So the request is to make the snap positions "stickier" than `normal` but not enforce to stop at them like `always` does.

That's the idea. I'm not sure it's possible to do the way scroll snapping is specified, but giving authors _some_ more control would go a long way. 

> One thing to note here is that the spec. currently leaves the definition of the snapping mechanics undefined, meaning that UAs can implement different behaviours for the `normal` value. So it might rather be an implementation issue you're facing.

It might be an implementation issue, but as the snapping mechanics are left undefined it is hard to say. It seems like the UA in the example video uses low friction for the fling, causing the natural end-point to be several pages down, past many snap points. It then follows the spec and chooses a snap point to minimize the distance between the snap point and the natural end-point. 

This seems correct according to the spec, but the result is that the user overshoots and does not feel in control.

> I think the question here is whether you just want `normal` to be stickier or if there are use cases in which you'd want some scroll snap areas to be stickier than others (but not force snapping to happen).

In the current case it would help if it was possible to make every scroll snap area stickier (increase friction for the whole scroll container). The goal is to make it easy for the user to scroll "page by page" or "scroll area by scroll area" while still being able to scroll fast through the content if needed. 

I can definitely see use cases where making some scroll snap areas, such as the beginning of a section, be stickier than others while not forcing snapping to happen.

**Comment by johannesodland** [comment]
@SebastianZ I just got hold of a Windows laptop, and was able to reproduce an issue in Chrome 85. The issue is related to the one you reported. Scrolling one small "tick" with a mouse wheel causes the scroll container to scroll down and snap twice: 

https://bugs.chromium.org/p/chromium/issues/detail?id=1132177

This also happens with scroll-snap-stop: normal. This issue might be the cause of the reports I've gotten of users not being in control.
