### ISSUE TITLE
[css-overflow-3] typos in Example 5 

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#5468]
-Sample rendering given #a { line-clamp: 5; } b { line-clamp: 2; }
+Sample rendering given #a { line-clamp: 5; } #b { line-clamp: 2; }

-Sample rendering given #a { line-clamp: 3; } b { line-clamp: 2; }
+Sample rendering given #a { line-clamp: 3; } #b { line-clamp: 2; }

**Comment by fantasai** [comment]
Fixed, thanks!
