### ISSUE TITLE
[scroll-animations-1] selector(<id-selector>) in quirks mode

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5471]
> When matching against a document which is in quirks mode, IDs must be matched ASCII case-insensitively; ID selectors are otherwise case-sensitive. [[source](https://drafts.csswg.org/selectors/#id-selectors)]

Is `selector(<id-selector>)` case-insensitive in quirks mode? I'm not sure what the precedent is here, but I'd prefer if quirkiness didn't "carry over" to new APIs. Case-insensitivity would also make the implementation slower and more complicated, since we can't just look up the ID in a hash table anymore.

**Comment by tabatkins** [comment]
Generally speaking, we're fine with not infecting new features with quirks, as long as avoiding that doesn't cause undue implementation issues.  So yeah, this could use some clarification that ensures it stays case-sensitive.

**Comment by flackr** [comment]
I think this is obsolete with the declarative rewrite of the spec which no longer has any selector() function.
