### ISSUE TITLE
[cssom] styleSheets IDL attribute must exist on DocumentOrShadowRoot, not Document

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#548]
CSS OM spec should directly define [`styleSheets` IDL attribute](https://drafts.csswg.org/cssom/#dom-document-stylesheets) on [`DocumentOrShadowRoot` interface](https://dom.spec.whatwg.org/#documentorshadowroot) to match the [latest shadow DOM specification](https://www.w3.org/TR/shadow-dom/#extensions-to-the-documentorshadowroot-mixin).

**Comment by rniwa** [comment]
@hayatoito @annevk

**Comment by annevk** [comment]
I suspect it's up to @zcorpan to define this?

**Comment by zcorpan** [comment]
Also https://drafts.csswg.org/cssom-view/#extensions-to-the-document-interface

**Comment by rniwa** [comment]
Yeah those CSS OM view methods are also supposed to be on [`DocumentOrShadowRoot` interface](https://dom.spec.whatwg.org/#documentorshadowroot).

**Comment by hayatoito** [comment]
Shadow DOM spec now defines the following methods on DocumentOrShadowRoot:
https://w3c.github.io/webcomponents/spec/shadow/#extensions-to-the-documentorshadowroot-mixin

```webidl
partial interface DocumentOrShadowRoot {
    Selection?        getSelection();
    Element?          elementFromPoint(double x, double y);
    sequence<Element> elementsFromPoint(double x, double y);
    CaretPosition?    caretPositionFromPoint(double x, double y);
    readonly attribute Element?       activeElement;
    readonly attribute StyleSheetList styleSheets;
};
```

Out of them, it would be nice that CSS OM would define:
```
partial interface DocumentOrShadowRoot {
    readonly attribute StyleSheetList styleSheets;
};
```

CSS OM View should have:
```idl
partial interface DocumentOrShadowRoot {
    Selection?        getSelection();
    Element?          elementFromPoint(double x, double y);
    sequence<Element> elementsFromPoint(double x, double y);
    CaretPosition?    caretPositionFromPoint(double x, double y);
};
```

DOM Standard should have:
```
partial interface DocumentOrShadowRoot {
    readonly attribute Element?       activeElement;
};
```

..and [Selection API](http://w3c.github.io/selection-api/) should have:

```idl
partial interface DocumentOrShadowRoot {
    Selection?        getSelection();
};
```

**Comment by annevk** [comment]
`activeElement` should be in the HTML Standard I think.

**Comment by hayatoito** [comment]
Thanks. I am sorry for the wrong information. I have updated [my comment](https://github.com/w3c/csswg-drafts/issues/548#issuecomment-271505245) directly.

**Comment by rniwa** [comment]
@emilio : could you fix this in CSS OM?

**Comment by emilio** [comment]
Yes, happy to.
