### ISSUE TITLE
[css-syntax-3] <percentage-token> type flag is never set

### ISSUE THREAD

**Issue by Fayti1703** [w3c/csswg-drafts#5483]
[Tokenization](https://drafts.csswg.org/css-syntax-3/#tokenization) defines the `type` flag on three tokens -- `<number-token>`, `<percentage-token>` and `<dimension-token>`, and assigns it a default value of "integer".

[Consume a numeric token](https://drafts.csswg.org/css-syntax-3/#consume-numeric-token) specifically sets the `type` flag on `<number-token>`s and `<dimension-token>`s to the one in the `number` returned from [Consume a number](https://drafts.csswg.org/css-syntax-3/#consume-a-number), using the wording
> create a &lt;xxx-token&gt; with the same value and type flag as *number*

However, this `type` flag isn't assigned for `<percentage-token>`s, as that just says
> create a &lt;percentage-token&gt; with the same value as *number*, and return it.

A strict reading of the spec suggests that therefore, a `<percentage-token>` always has a `type` of "integer", even if it's `value` is, for instance, `50.90`, which seems wrong.

**Comment by tabatkins** [comment]
Huh, that's a clear mistake. Thanks for the catch!

**Comment by triple-underscore** [comment]
I don't think it was a mistake, because the type flag is not defined for `<percentage-token>`.
The spec states [in section 4](https://drafts.csswg.org/css-syntax-3/#tokenization):
> `<number-token>`, `<percentage-token>`, and `<dimension-token>` have a numeric value. `<number-token>` and `<dimension-token>` *additionally* have a type flag set to either "integer" or "number". The type flag defaults to "integer" if not otherwise set. `<dimension-token>` additionally have a unit composed of one or more code points.

(and there is no such kind of things defined for `<percentage-token>` anywhere else.)

**Comment by tabatkins** [comment]
Ah, you're right! Dang it, I *thought* it was weird I had such an obvious error! Okay, I'll revert, but put a note into the source to remind myself in the future.

**Comment by fantasai** [comment]
Reverted the text; leaving this open for Tab to add his note later.
