### ISSUE TITLE
[resize-observer] "loop limit exceeded" only when making window smaller, but not when making it bigger.

### ISSUE THREAD

**Issue by trusktr** [w3c/csswg-drafts#5487]
I have a weird issue. When I resize the window and make it bigger, the single ResizeObserver that I have on my element works fine. When I make the window 1 px smaller, I get the "ResizeObserver loop limit exceeded" error.

Any ideas why it might happen only when downsizing the window but not when upsizing it? (Could it potentially be a browser bug?)

**Comment by trusktr** [comment]
I think this is a browser bug.

The following is the demo that gives me the error. it is inside the iframe to the right of the code box. Try to make the window smaller to trigger the error: https://lume.io/docs/#/examples/shadow-dom

Now here is an exact replica of the demo, this time running in a Codepen iframe, and there is no such error no matter how you resize your window: https://codepen.io/trusktr/pen/eYZRwLy

This _seems_ to be an indication of a browser bug.

The code that creates the ResizeObserver is here: https://github.com/lume/lume/blob/abf7ad8fd7f33bdd7a3cbd6897f4a2b5433d7327/packages/lume/src/core/Scene.ts#L483-L517

As you see in that code, it logs `Make new resize observer!`, and this appears in the console only _once_. There is only a single ResizeObserver that observes the `div` element, and the ResizeObserver _**does not touch the div element, does not change its size in any way.**_

Does anyone else think this seems like a browser bug?

**Comment by trusktr** [comment]
Ah, nevermind, I updated the pen (https://codepen.io/trusktr/pen/eYZRwLy) so that it catches `error` events on `window`, and I do in fact see the same errors in the codepen demo.

**Comment by trusktr** [comment]
I'm not sure what's happening (first-time RO user here). The spec says 

> Infinite loop is prevented by shrinking the set of nodes that can notify at every iteration. In each iteration, only nodes deeper than the shallowest node in previous iteration can notify.
> 
> An error is generated if notification loop completes, and there are undelivered notifications. Elements with undelivered notifications will be considered for delivery in the next loop.

Should this message be a warning instead of an error? Seems like that's the intent

**Comment by trusktr** [comment]
I just tested in Firefox and do not get any such error. Chrome browser bug?

**Comment by Loirooriol** [comment]
It seems a Chromium bug already fixed by [r772560](https://chromium.googlesource.com/chromium/src/+/3e11eeb97304cc6ce871f86ad0fd0bb1d6683dc2), 85.0.4159.0

**Comment by trusktr** [comment]
Indeed it seems to have been fixed, I am not seeing the errors anymore on the original example, although I have updated it (not 100% sure I did not eliminate the code that had the issue).
