### ISSUE TITLE
[css-text] 'tab-size' de facto applies to inline boxes

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#5489]
From https://drafts.csswg.org/css-text-3/#propdef-tab-size

> Applies to: block containers

However, all Chromium, WebKit and Firefox also support it in inline boxes. [Testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22white-space%3A%20pre%3B%20tab-size%3A%20100px%3B%20-moz-tab-size%3A%20100px%22%3E%0A%20%20A%26%239%3B%3Cspan%20style%3D%22tab-size%3A%2050px%3B%20-moz-tab-size%3A%2050px%22%3EB%26%239%3BC%3C%2Fspan%3E%0A%3C%2Fdiv%3E)

```html
<!DOCTYPE html>
<div style="white-space: pre; tab-size: 100px; -moz-tab-size: 100px">
  A&#9;<span style="tab-size: 50px; -moz-tab-size: 50px">B&#9;C</span>
</div>
```
looks more or less like
```
A              B       C
```

So I guess the spec should be changed to reflect reality?

**Comment by frivoal** [comment]
Matching reality is good, so yes, we should change. But what is the behavior exactly? A tab character isn't a shift *by* a particular amount, it is a shit *to* a tab stop. I guess we just compute the potential tab stops independently for each preserved tab character?

If so, the following sentence

> Tab stops occur at points that are multiples of the tab size from the block’s starting content edge.

just needs to be changed to 

> Tab stops occur at points that are multiples of the tab size from the starting content edge of the preserved tab's containing block’s.

I think that's what browsers do. An alternative model where tab stops of different sizes somehow stack up seems complicated and unnecessary.

**Comment by frivoal** [comment]
Made a couple of basic WPT tests backing this proposed resolution up: https://github.com/web-platform-tests/wpt/pull/25373

They pass in Safari and Chrome, and would pass in Firefox if used the -moz- prefixed syntax instead of the unprefixed one, which Firefox does not yet support.

**Comment by fantasai** [comment]
The reason the spec defines it on the block container and not the inline is so that tab stops line up even when the font changes within the paragraph. It was very intentionally specced this way.

**Comment by Loirooriol** [comment]
@fantasai What about saying that `tab-size` applies to inlines, but `<number>` values refer to the space character’s advance width of the block container?

This would still give authors more freedom to change the `tab-size` value in inlines, and would be closer to existing implementations, while still avoiding that pitfall when changing the font?

Though current implementations do break the alignment when the font changes. [Testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22white-space%3A%20pre%3B%20tab-size%3A%2050%3B%20-moz-tab-size%3A%2050%3B%22%3E%0A%20%20%3Cspan%20style%3D%22font-family%3A%20Ahem%22%3EA%26%239%3BB%3C%2Fspan%3E%3Cbr%2F%3E%0A%20%20%3Cspan%20style%3D%22font-family%3A%20monospace%22%3EA%26%239%3BB%3C%2Fspan%3E%3Cbr%2F%3E%0A%20%20%3Cspan%20style%3D%22font-family%3A%20serif%22%3EA%26%239%3BB%3C%2Fspan%3E%3Cbr%2F%3E%0A%20%20%3Cspan%20style%3D%22font-family%3A%20sans-serif%22%3EA%26%239%3BB%3C%2Fspan%3E%3Cbr%2F%3E%0A%3C%2Fdiv%3E)
