### ISSUE TITLE
[css-grid-1][css-grid-2] editorial: link https://drafts.csswg.org/css-grid/ to css-grid-2

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#5493]
The link https://drafts.csswg.org/css-grid/ currently links to css-grid-1. I would expect it to link the latest complete CSS Grid spec, which is css-grid-2.  (It appears that all of css-grid-1 has now been incorporated into css-grid-2 so that it's now the latest spec that one should reference.)

**Comment by fantasai** [comment]
Fixed.
