### ISSUE TITLE
[css-syntax-3] Typo in the description of "non-ASCII"

### ISSUE THREAD

**Issue by BigBadaboom** [w3c/csswg-drafts#5496]
The description of "non-ASCII code point" in [section 4.2](https://drafts.csswg.org/css-syntax/#tokenizer-definitions) states:

> non-ASCII code point
A code point with a value equal to or greater than U+0080 &lt;control&gt;.

I'm not sure what this "&lt;control&gt;" is meant to mean here.  I assume it's just a typo?

**Comment by Loirooriol** [comment]
U+0080 is a `<control>` character, see https://www.unicode.org/charts/nameslist/n_0080.html

**Comment by tabatkins** [comment]
Yup, that's just the actual name of the codepoint. ^_^
