### ISSUE TITLE
[css-color-5] Add value multiplier for color-contrast()

### ISSUE THREAD

**Issue by sangwoo108** [w3c/csswg-drafts#5497]
https://drafts.csswg.org/css-color-5/#colorcontrast

Hi, all

the second parameter of color-contrast() is a list  of two or more colors. Would it be better if we add value multiplier?

```diff
- color-contrast( <color> vs <color>#  )
+ color-contrast( <color> vs <color>#{2,} )
```

**Comment by tabatkins** [comment]
`{2,}` to indicate two or more.

**Comment by svgeesus** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/81d9d324b5bea4157683010a7ebd78a98cb45601#diff-2035345378942a021190ce428e1f91413c366fec038ea7c90ec1a446100c4f5e
