### ISSUE TITLE
Incomplete shade in box-shadow

### ISSUE THREAD

**Issue by msudgh** [w3c/csswg-drafts#550]
Hi,
During the development of a project i need to styled a div with box-shadow but the result was different.
my parent div that it's my container styled with a box-shadow and this div separate to two div. Left div styled with a `background: #fff` and on the other hand right div styled with a `background: linear-gradient(102deg, #3728AF 0%, #C16AD5 100%);`.
![image](https://cloud.githubusercontent.com/assets/11756815/18945366/1fc27634-8637-11e6-86d8-eca37cb54a6b.png)

**Comment by SebastianZ** [comment]
This seems unrelated to the [related CSS specification](https://drafts.csswg.org/css-backgrounds-3/#the-box-shadow) and is rather an incorrect usage of the `box-shadow` property or a bug in Firefox.

I suspect you defined some offsets in your `box-shadow` definition. To get a centered box-shadow you need to set the first two values to 0, e.g. `box-shadow: 0 0 50px rgba(0, 0, 0, 0.2)`.

Sebastian
