### ISSUE TITLE
[css-cascade-4] Could you clarify if a web page’s DOM tree itself is an encapsulation context?

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#5501]
Regarding the new Context criterion

> A document language can provide for blending declarations sourced from different encapsulation contexts, such as the nested tree contexts of shadow trees in the [DOM]. 

https://drafts.csswg.org/css-cascade-4/#encapsulation-contexts

Is a web page’s own DOM tree also an encapsulation context?

For example, if a page has a custom element with a shadow DOM, are there two encapsulation contexts (the page’s own tree and the nested shadow tree), or is there only one encapsulation context (the nested shadow tree)?

**Comment by tabatkins** [comment]
Is there any consequence to the decision either way?

(The use of "different" implies you start in one, tho.)

**Comment by simevidas** [comment]
Ah, I remembered that style rules from the other page aren’t matched against elements in the shadow tree, and vice versa.

So when does this blending of declarations from different encapsulation contexts during the cascade happen in HTML in practice? Could you give an example?

**Comment by tabatkins** [comment]
When the outer page uses a `::part()` rule to target an element in a shadow, or a shadow uses a `::slotted()` rule to target elements from the light.

**Comment by simevidas** [comment]
Ah, I see 👍
