### ISSUE TITLE
[css-shadow-parts-1] 2.2 exportparts example doesn't match syntax specified

### ISSUE THREAD

**Issue by chrisosaurus** [w3c/csswg-drafts#5504]
https://www.w3.org/TR/css-shadow-parts-1/#exportparts-attr
"2.2. Forwarding a Shadow Element: the exportparts attribute"
specifies the syntax for exportparts

```
The exportparts attribute is parsed as a comma-separated list of part mappings. Each part mapping is one of:

innerIdent : outerIdent
this adds «[ outerIdent → innerIdent ]» to el’s part name map.

ident
Is shorthand for ident : ident.

anything else
Ignored for error-recovery / future compatibility.
```

The example includes a snippet

```
<template id="c-e-outer-template">
  <c-e-inner exportparts="innerspan textspan"></c-e-inner>
</template>
```

**Note the missing colon** (`:`) from the `exportparts` attribute value.

(based on the comments within the example)
I think this snippet should contain an `exportparts` attribute value `"innerspan : text"` like so

```
<template id="c-e-outer-template">
  <c-e-inner exportparts="innerspan : textspan"></c-e-inner>
</template>
```

**Comment by tabatkins** [comment]
This was fixed a few years ago (<https://github.com/w3c/csswg-drafts/commit/8de4db29272dc246f4160dcacf2a18134ddc9c11>), we just haven't republished with the fix. ^_^

**Comment by alice** [comment]
@tabatkins 
Can we reopen this until the fixed version is published? I was tripped up by this for a good half an hour on Monday.
