### ISSUE TITLE
[resize-observer] IDL index incorrectly includes ResizeObservation

### ISSUE THREAD

**Issue by saschanaz** [w3c/csswg-drafts#5508]
https://drafts.csswg.org/resize-observer/#resize-observation-interface
https://drafts.csswg.org/resize-observer/#idl-index

It's just an example and should be excluded from the index.

>ResizeObservation is an example struct that can be used in implementation of Resize Observer. It is being included here in order to help provide clarity during the processing model. It effectively holds observation information for a single Element. This interface is not visible to Javascript.

**Comment by annevk** [comment]
Per @domenic this is fixed.
