### ISSUE TITLE
[css-fonts-4] font-stretch is unfortunately named

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#551]
Most designers' intuition seems to be that this property affects (the typographical sin of) geometrical scaling. We should make an alias which has a better name.

**Comment by litherum** [comment]
One possibility: ```font-width```. This is in line with the TrueType and OpenType spec.

**Comment by svgeesus** [comment]
I agree that this name has, in practice, caused confusion. In a world where fake bold and fake italic (obliquing) are common, people often assume that font-stretch geometrically stretches or shrinks the glyph outlines. Also, to date there were not so many WebFonts deployed with condensed or expanded versions, so this property and associated descriptor were not much used.

I agree that now is the right time to deploy an alias, before variable fonts make condensed and expanded forms far more common. `font-width` seems much better. In general, aligning closely with OpenType is better.

Also, mea culpa. I came up with the name `font-stretch`, didn't much like it, asked for better names and none were suggested so we stuck with it.

**Comment by liamquin** [comment]
On Thu, 2016-09-29 at 12:09 -0700, Chris Lilley wrote:
> I agree that this name has, in practice, caused confusion. In a world
> where fake bold and fake italic (obliquing) are common, people often
> assume that font-stretch geometrically stretches or shrinks the glyph
> outlines.

Which in at least on implementation I use, it does. And it's a useful
feature at times - e.g. if you use it with the stroked (not filled)
version of Courier, the result can be very acceptable.

Maybe access to the font transformation matrix should be added at the
same time this is clarified? Or maybe it's not worth-while, given that
you can open the font in a font editor and adjust it.

Liam



-- 
Liam R. E. Quin <liam@w3.org>
The World Wide Web Consortium (W3C)

**Comment by LeaVerou** [comment]
Totally agree, `font-width` would be a much better name.
Given that it's [only used on 3% of websites](https://www.chromestatus.com/metrics/css/timeline/popularity/80), perhaps we could deprecate it without serious backwards compat issues?

**Comment by jpamental** [comment]
If we wanted to make `font-width` the 'real' name but can also create an alias, couldn't we rename the property to `font-width` and add an alias for `font-stretch` and eventually deprecate that?

**Comment by Crissov** [comment]
`font-width` sounds as if you could switch between fixed/monospaced and variable/proportional/dynamic with it. It’s also easily associated with half-width sinograms etc. as in [`font-variant-east-asian: <east-asian-width-values>`](https://drafts.csswg.org/css-fonts-3/#font-variant-east-asian-prop) (OTF `fwid` and `pwid`, not `hwid`, `twid` or `qwid`) and [`text-transform: full-width`](https://drafts.csswg.org/css-text-3/#text-transform-property).

**Comment by jpamental** [comment]
@Crissov I think the challenge is being mindful of terminology from type design and typography while still being accurate. In this case, `font-width` is the term that resonates most and aligns more closely with existing terminology from the design world, whereas `font-stretch` sounds more like something you're generally not supposed to do with type (stretch it artificially).

I'm not sure that this is a clear-cut recommendation one way or the other, but in balance I've heard from a whole bunch of type designers/typographers that they feel `font-width` is preferable, so I definitely lean much more in that direction. (Not that it's up to me, but I'm doing my best to ensure the design community is 'in the conversation', so to speak)

**Comment by Crissov** [comment]
There are lots of unfortunate naming choices in CSS (e.g. `border-radius` instead of `corner-radius` or hyphen-less `currentcolor`). As far as I know, none of them have been improved (or deprecated) unless the new alternative also added new features (e.g. comma-less `rgb()` with “alpha” opacity). Would `font-width` do more than `font-stretch` does already?

Similar changes I could imagine:

- `font-height` as an extended superset of `font-size`, `font-size-adjust` and `line-height`, also dealing with optical sizes and sizing by cap-height vs. _x_-height vs. _dp_-height vs. _Å_-height vs. CJK-height etc.
- `font-slope` or `font-slant` to deal with `oblique` (vs. `upright`) and arbitrary/variable angles, whereas `font-style` became a shorthand for this and other sub-properties for `italic` vs. `roman` (vs. `swash` vs. `cursive`/`continuous`/`connected`) or serifs, in a way that encompassed at least Arabic and East-Asian hands as well.

**Comment by litherum** [comment]
> There are lots of unfortunate naming choices in CSS (e.g. `border-radius` instead of `corner-radius` or hyphen-less `currentcolor`). As far as I know, none of them have been improved (or deprecated) unless the new alternative also added new features

You hit the nail on the head. Closing.

**Comment by nicksherman** [comment]
> unless the new alternative also added new features

If the idea of `font-width` is expanded to include support for the registered `width` axis from the new OpenType variations spec, you could indeed say that new features are being added, not only making the name imply additional capabilities, but also tying it more solidly (and intuitively) to the thing it affects.

**Comment by nicksherman** [comment]
Another thought on @Crissov’s comments …

> As far as I know, none of them have been improved (or deprecated) unless the new alternative also added new features

The main difference with most of the other unfortunate naming choices is that `font-stretch` support still hasn't been widely implemented (if at all).

Between this and the expansion of functionality with variable fonts I mentioned before, I really hope this is enough to convince @litherum to open this issue up again. It seems much more logical to improve the naming for a thing that still hasn't been implemented than it would be to have to explain to confused developers and designers for the rest of time that `font-stretch` isn't actually doing what the name implies.

**Comment by liamquin** [comment]
On Tue, 2016-12-06 at 14:05 -0800, Nick Sherman wrote:
> 
> The main difference with most of the other unfortunate naming choices
> is that `font-stretch` support still hasn't been widely implemented
> (if at all).

AntennaHouse Formatter implements it, synthesizing a font of the
appropriate width if necessary.

I think YesLogic's PrinceXML also implements it, but does not seem to
synthesize a font if needed.

The CSS font model doesn't seem to let you say, "I want _this_ font
with _this_ transformation done to it" except for very limited cases -
the renderer will synthesize a font that renders in blue if needed, or
that has underlines, or is slanted, but you can't take the slanted font
and unslant it, or the condensed font and expand it. Nor I think can
you choose the first font family from a list where roman, italic, roman
small caps, discretionary ligatures and historical ligatures are all
present. I still sometimes see Times Roman "fi" ligatures on a page
using Helvetica.

But the fix isn't to rename font-stretch. It might be to add an @font-
family or something, I'm not sure.

**Comment by mediumjones** [comment]
MDN has updated [their definition](https://developer.mozilla.org/en/docs/Web/CSS/font-stretch) of `font-stretch` to what it **is not**, due to exactly this concern.

**Comment by cjdunn** [comment]
I agree that this is a confusing term and that font-width would be a much more accurate term. Especially as OT 1.8 Variable Font support increases, a logical name will be crucial for understanding what this property actually does. It refers to the width of a font and does not refer to mechanically stretching a font, therefore font-width is much more accurate. Please change the name to font-width.

**Comment by chrisarmstrong** [comment]
Font-width would definitely be more appropriate, as well as being more in keeping with other CSS terms, e.g. border-width (increasing border width & font-width would have a similar visual effect)

**Comment by denmch** [comment]
I think `font-width` is the best possible name and shouldn't cause confusion with a distiinction between variable width and monospace fonts since that's a difference between font families and not normally a property within a font family. 'Width' is the normal term covering normal, condensed, and expanded forms within a font family.

**Comment by liamquin** [comment]
On Mon, 2017-02-27 at 14:55 -0800, CJ Dunn wrote:
> [...] It refers to the width of a font and does not refer to
> mechanically stretching a font, 

I do know of at least one implementation that synthesizes a font of the
given "stretch" if needed. But then, this also happens for bold and
italic or oblique.

**Comment by cjdunn** [comment]
@liamquin Hmm. I'm referring to what [Mozilla says](https://developer.mozilla.org/en/docs/Web/CSS/font-stretch) about this property:

> This property does not change the geometry of an arbitrary font by stretching or shrinking it. Like font-feature-settings or font-variant, it is merely a means to choose the most appropriate face of the font, if this one offers several of them.

**Comment by chrisarmstrong** [comment]
@cjdunn doesn’t that describe font-weight also?

**Comment by cjdunn** [comment]
@chrisarmstrong No. An example of weight would be Light, Bold, Black. An example of Width would be Extra Compressed, Condensed, Wide.  

Specific font examples: 
–Benton Sans Extra Compressed Bold (Width = Extra Compressed, Weight = Bold)
–Benton Sans Wide Light (Width = Wide, Weight = Light) 

See: 
[https://fontbureau.typenetwork.com/news/article/new-benton-sans-wide](![benton-sans-range](https://cloud.githubusercontent.com/assets/3900241/23385698/98644e8c-fd1f-11e6-8878-f8d4c55756d7.png))

**Comment by chrisarmstrong** [comment]
@cjdunn yep I meant this bit can also refer to font-weight:

> it is merely a means to choose the most appropriate face of the font, if this one offers several of them.

Either way my question doesn't add much to the discussion so I'll remove it, however your answer should be useful to others :)

**Comment by colinmford** [comment]
I think I would prefer pretty much anything over `font-stretch`, and while `font-width` can cause a little bit of confusion, width is a standard term that many font vendors use. I also second @nicksherman's point about it being more closely related to the standard variable fonts `wdth` axis.

**Comment by sairuspatel** [comment]
Yes to `font-width` for several of the reasons mentioned in this thread, but mostly because it closely aligns with OpenType’s `OS/2.usWidthClass` field and `wdth` axis. OT font variations are a super opportunity for CSS to make this kind of adjustment.

**Comment by dauwhe** [comment]
I wonder if we need a more flexible model to account for complex font families. The [Adobe Kepler ](https://www.myfonts.com/fonts/adobe/kepler/)family has 168 members, with a facet of optical weight (subhead | display | caption | regular) in addition to font-weight, font-stretch, and font-style. [Knockout](https://www.typography.com/fonts/knockout/styles/) has nine weights ranging from "flyweight" to "sumo", and four widths, with naming utterly unrelated to existing CSS values.

**Comment by denmch** [comment]
I don't think a more flexible model is necessary. Optical weight is more about use cases (i.e., is it being used for an h1 and so very large, etc.) and so is natural to set as a separate family. And you can specify weight numerically (100–900), which already covers the 9 weights of the Knockout example. But font-width is a perfect addition to add robustness.

**Comment by alyssamichelle** [comment]
I think `font-width` makes more sense than `font-stretch`. I think @jpamental [said it perfectly.](https://github.com/w3c/csswg-drafts/issues/551#issuecomment-252640667) `font-stretch` makes me think of something you _are not_ supposed to do with your type.

**Comment by jpamental** [comment]
With regard to @denmch 's comment - It's worth noting that optical weight already has another named axis of variation within the variable font world that is more about x-height proportion that 'visual weight' per se. I'm glad there's more discussion regarding `font-width` vs `font-stretch` though - it's well worth talking this through and trying to get it as 'right' as we can!

**Comment by litherum** [comment]
Every browser other than WebKit has already shipped `font-stretch`, so it isn't going away (and I'm currently in the middle of implementing it in WebKit).

The variations piece of `font-stretch` should not be pulled into its own property. It's more important to extend an already-existing property for variations (rather than introduce a new property) than it is to correct a naming mistake.

Are there any other proposals of how to handle this unfortunate naming choice?

**Comment by jpamental** [comment]
@litherum I thought early on it was mentioned that aliasing was a possibility? If so, could we sort of swap it 'under-the-hood' so that the 'real' property is `font-width` and `font-stretch` is aliased to it, so it could then be deprecated over time? (maybe wishful thinking?)

**Comment by litherum** [comment]
Yes, aliasing has been proposed, and shown to be ineffective (best summarized in https://github.com/w3c/csswg-drafts/issues/551#issuecomment-253339556 )

**Comment by thundernixon** [comment]
Just to chime in, even though `font-stretch` isn't the only unfortunately-name property, it is specifically named as something that many designers are trained is a formally terrible thing to do. "Stretching" is reserved for novices or for deliberately rule-breaking design, whereas "font-width" is the vernacular name for a feature of typographic control that will see more and more use with upcoming variable font technology. As the web becomes a richer and richer typographic tool, it seems like a good opportunity to also embrace a few pieces of mainstream type terminology. 

Finally, I do see that `font-stretch` has momentum, but if WebKit were to do it better, wouldn't that take care of a large percentage of browser users from the get-go, and help prove whether such a concept has value? I might be misunderstanding the coverage of this piece of development, but even if this is Safari-only, positive change has to start somewhere.

**Comment by liamquin** [comment]
On Tue, 2017-02-28 at 13:15 -0800, thundernixon wrote:
> Just to chime in, even though `font-stretch` isn't the only
> unfortunately-name property, it is specifically named as something
> that many designers are trained is a formally terrible thing to do. 

"Anyone who would letterspace lower case [blackletter] would steal
sheep, said Fred Goudy. There are actually uses for changing the font
transformation matrix / "stretching", "skewing", "shearing" in the
hands of experts - although, as you point out, this property doesn't
actually take a font and "stretch" it with isotropic scaling, but
rather selects a font with the given set width (or, possibly, and this
clearly needs to be clarified as implementations differ, synthesizes it
from an OpenType variation axis or by scaling an existing font).

I can imagine introducing a font-width property that only selects and
never synthesizes, and clarifying that font-stretch can synthesize.

I can also imagine introducing a font-transform property and clarifying
that font-stretch does not synthesize, but that may break some existing
content (or the change not be implemented) - e.g. AntennaHouse
Formatter synthesizes.

An example of wanting to transform fonts happens when you're applying a
2d transform but want the individual glyphs to be unaffected, and don't
want to (or can't) add additional markup.

**Comment by nicksherman** [comment]
@litherum 

> Every browser other than WebKit has already shipped font-stretch, so it isn't going away (and I'm currently in the middle of implementing it in WebKit).

These implementations are _very_ new though, correct? And as @thundernixon mentioned, your implementation in WebKit would immediately address a large percentage of browser coverage when it goes out.

> it's been widely implemented, and is already in use on the web

Do you have any reference or stats on this? I would be very surprised if there were any more than a few dozen websites in existence that make use of the `font-stretch` property. And any of them that have made use of that property surely understand that it is not a reliable thing without WebKit support.

> Yes, aliasing has been proposed, and shown to be ineffective

The argument that aliasing didn’t work in other different situations (situations that may have been further along in implementation and time beforehand) seems to be a very broad generalization of the potential effectiveness of such an idea. Is there any harm in deploying an alias as @svgeesus, @jpamental, and the earlier version of yourself suggested?

**Comment by LeaVerou** [comment]
> it's been widely implemented, and is already in use on the web

Not much, only 3.16% of websites:
https://www.chromestatus.com/metrics/css/popularity#font-stretch

**Comment by nicksherman** [comment]
4 years later, I'd like to re-ask @litherum the question that wasn't answered here back in 2017:
Is there any harm in deploying an alias as @svgeesus, @jpamental, and the earlier version of yourself suggested?

**Comment by murtaugh** [comment]
Thumbs up for revisiting this issue. In my mind, as someone who has been building websites since before CSS existed, "it's not the only bad name" isn't a good enough reason to not alias `font-stretch`. CSS will be more welcoming to designers and people trained in the proper use of type if the terminology in CSS matches their expectations.

**Comment by svgeesus** [comment]
> Not much, only 3.16% of websites:
> https://www.chromestatus.com/metrics/css/popularity#font-stretch

Latest data from the HTTP Archive 2020 Almanac shows usage at half a million websites, or 9% of all sites surveyed.

**Comment by piperhaywood** [comment]
Would still love love love to see a `font-width` alias for `font-stretch`! It seems like a pretty darn good compromise and would bring so much clarity to discussion and education around the use of this property.

I know that @litherum [mentioned that aliasing has be shown to be ineffective](https://github.com/w3c/csswg-drafts/issues/551#issuecomment-283124801), but to me, [the comment they referred to](https://github.com/w3c/csswg-drafts/issues/551#issuecomment-253339556) only demonstrates that the introduction of an alias wouldn’t conform to the reasons for previous aliases, not that its actual effectiveness is diminished. 

By waiting to introduce an alias, the percentage of websites using `font-stretch` just continues to go up. The percentage of Chrome page loads using `font-stretch` is now 3x what it was when @svgeesus posted over a year and a half ago, probably largely a result of Google Fonts introducing variable fonts.

If there’s a really strong reason why an alias shouldn’t be introduced then that makes sense. But I’m not sure that the argument against it thus far outweighs the benefit.

**Comment by nicksherman** [comment]
Yes, at this point (6 years later!) with Webkit's implementation of `font-stretch` now shipping, and especially with Google Fonts now making use of it, we are probably past the point where outright replacement of the name would be practical. But there is still a very strong case for establishing an alias of `font-width` for all the reasons discussed before.

**Comment by litherum** [comment]
> Is there any harm in deploying an alias

Yes: maintenance cost. It’s yet one more thing added to the web platform, one more thing whose effects have to be tested. If you set one, does the other one’s computed style change? Do they appear distinct in the CSSOM? Do we use the shorthand mechanism to alias them?

And the new name wouldn’t let authors accomplish anything that they couldn’t already accomplish today. It would take the same grammar and the same values; it’s not reformulating the functionality like grid-template-columns; and there is no new functionality here.

The case for font-width would be easier to make if there were new features here, similar to the relationship between tables and CSS grid. But it seems like we’re just talking about a pure alias here.

**Comment by scottkellum** [comment]
Thank you for re-opening this @svgeesus!

Some thoughts to echo what has been said before:

Font-width is what I always slip up and say while font-stretch makes me feel like I’m doing bad typography. Distorting fonts is generally considered bad typographic practice and when I hear “stretch” I always assume it means geometrically distort outlines. In no circumstances would I ever use the word “stretch” to describe font widths.

`font-stretch` is confusing and I’m sure we will see wider adoption and less confusion if this is aliased.

**Comment by ashleykolodziej** [comment]
This is wild - from an outside perspective, I genuinely thought this was a deprecated property. The thought process that led to that was something like:

- Yikes, who stretches type?
- Oh, we made all kinds of inadvisable design choices in the 90s.
- Ahh, yeah that’s probably it. Must just be a leftover of that era, moving on.

Width is more intuitive to me for sure, not just because of the OpenType naming convention, but because it is more consistent with my mental model of how the units for this property work. I’m used to thinking of something having a width of 50%, and having that be half the width of the default state. I’m not used to stretching an item to 50%, because stretching implies that things get longer or wider, not more compressed. 

I really appreciate this discussion, as well as the concern with technical debt and testing regarding adding an alias. I’ll learn either way, but I thought it was interesting that this conflicted so much with what I was taught to do as a designer that my brain invented an origin story to make it stop.

**Comment by litherum** [comment]
(I do agree the property should have been named font-width back when it was originally invented. I guess we can add this to the list of [CSS Mistakes](https://wiki.csswg.org/ideas/mistakes).)

**Comment by liamquin** [comment]
I'm aware of at least one fairly widely used commercial implementation that does indeed stretch a font along the inline axis when font-stretch is applied. I think it's synthesizing the width if a font isn't available, which is maybe not unreasonable.

**Comment by rutherfordcraze** [comment]
I don’t have much to add here except agreement with the recent comments. In all other contexts, I’ve only ever understood ‘stretch’ to be something you’re explicitly _not supposed to do_ with type. `font-width` would be more accurate, and significantly less confusing for existing type users learning CSS.

(And even as a long-time CSS user, I still find myself falling back to `font-variation-settings` or setting `font-synthesis: none` unnecessarily, because subconsciously I worry `font-stretch` will distort the type if other widths aren’t available.)

**Comment by svgeesus** [comment]
A [Twitter poll](https://twitter.com/svgeesus/status/1592956077959942145) found that most people don't know what `font-stretch` property does and had never used it. Those who hazarded a guess slightly favored the (incorrect) "it stretches the glyphs" interpretation (which the spec currently forbids) over the correct, "it selects a width variant" option.

![image](https://user-images.githubusercontent.com/2506926/202566685-82ca4cd3-f08d-4b3b-9420-e10d9977a549.png)

The [same poll on Mastodon](https://mastodon.social/@svgeesus/109355099109547015) reversed the slight lead among those guessing what it does (perhaps due to promotion on type.social) but again most respondents had not used it.

![image](https://user-images.githubusercontent.com/2506926/202567132-91b1aa78-dbe9-4b86-8049-246e430777d3.png)

**Comment by svgeesus** [comment]
> I'm aware of at least one fairly widely used commercial implementation that does indeed stretch a font along the inline axis when font-stretch is applied. I think it's synthesizing the width if a font isn't available, which is maybe not unreasonable.

The spec [specifically forbids this](https://drafts.csswg.org/css-fonts-4/#font-stretch-prop):

> User agents must not synthesize stretched faces for font families which lack actual stretched faces.

**Comment by alyssamichelle** [comment]
As suggested by @turtleguyy, a suitable substitute for `font-stretch` would be `font-chonkiness`.

**Comment by svgeesus** [comment]
> If you set one, does the other one’s computed style change? Do they appear distinct in the CSSOM? Do we use the shorthand mechanism to alias them?

I would propose:

- defining the property name as `font-width`
- declaring that "for historical reasons" a deprecated alias is accepted, `font-stretch`
- setting `font-stretch` actually sets `font-width`, they are not two separate properties
- getting either `font-stretch` or `font-width` gives you the computed value of `font-width`
- removing all uses of "stretch" in the property description

**Comment by faceless2** [comment]
FWIW I'm with @litherum on this one. 28% of websites is a huge proportion: regardless of that poll it's clear this property is very, very widely used. I imagine if you ran the same poll for `font-width` you'd get similar results. 

Existing sites won't change because it doesn't add anything, new ones are at best going to use both "just in case". And as for font-aware designers knowing not to stretch text - well, they've managed to adapt to `font-weight: bolder` not necessarily making things bolder and 1pt not necessarily meaning 1/72". I am confident that designers can figure this one out, particularly as it's widely documented and used.

**Comment by svgeesus** [comment]
> I can reach out to the Almanac folks for more detailed stats about font-stretch usage if that would be useful.

Knowing usage on the Google Fonts CDN vs not, would be illuminating

**Comment by svgeesus** [comment]
In a one-paragraph description, [Can I use has to include a disclaimer](https://caniuse.com/css-font-stretch):

> If a font has multiple types of variations based on the width of characters, the font-stretch property allows the appropriate one to be selected. **The property in itself does not cause the browser to stretch to a font.**

**Comment by nicksherman** [comment]
> Knowing usage on the Google Fonts CDN vs not, would be illuminating

Looking at the historical data for usage of the `font-stretch` property over time gives a pretty good idea of both when Google Fonts flipped the switch and how large of a portion of usage they represent:

<img width="861" alt="font-stretch_over_time" src="https://user-images.githubusercontent.com/1265313/202767570-d07a7028-0450-4668-aa0a-260ab403fffc.png">

**Comment by rviscomi** [comment]
28% of pages include a `font-stretch` declaration. 22% of pages use `font-stretch` as a `@font-face` descriptor, 8% of pages declare it as a property in a style rule (some pages use it both ways).

17% of pages include a `font-stretch` declaration served by the Google Fonts CDN, `fonts.googleapis.com`, all of which are `@font-face` descriptors. That makes up about 60% of pages that use it at all and 78% of all pages that use it in `@font-face` rules.

88% of `font-stretch` declarations have a value of `100%`. 11% of declarations have a value of `normal`. Here's a table comparing usage of all keyword values, including `100%` for comparison:

value | % of usage | % of pages | # pages
-- | -- | -- | --
100% | 88.3% | 18.2% | 5,286,325
normal | 11.3% | 11.7% | 3,389,997
expanded | 0.0% | 0.2% | 58,958
inherit | 0.0% | 0.2% | 49,132
condensed | 0.1% | 0.2% | 45,043
initial | 0.0% | 0.0% | 7,910
ultra-condensed | 0.0% | 0.0% | 5,306
semi-expanded | 0.0% | 0.0% | 4,439
semi-condensed | 0.0% | 0.0% | 3,545
ultra-expanded | 0.0% | 0.0% | 3,085
extra-condensed | 0.0% | 0.0% | 2,692
extra-expanded | 0.0% | 0.0% | 1,851
unset | 0.0% | 0.0% | 977
revert | 0.0% | 0.0% | 5
revert-layer | 0.0% | 0.0% | 0

**Comment by svgeesus** [comment]
Thanks, @rviscomi !

So, 99.6% of usage is, redundantly, setting it to the initial value.

**Comment by liamquin** [comment]
On Fri, 2022-11-18 at 11:26 -0800, Chris Lilley wrote:
> 
> So, 99.6% of usage is, redundantly, setting it to the initial value.
> 

And i wonder how many of those are in boilerplate @font-face
declarations...


-- 
Liam Quin, https://www.delightfulcomputing.com/
Available for XML/Document/Information Architecture/XSLT/
XSL/XQuery/Web/Text Processing/A11Y training, work & consulting.
Barefoot Web-slave, antique illustrations:  http://www.fromoldbooks.org

**Comment by Lorp** [comment]
Seems like a really good change. Two questions:

* How would it work with [`Window.getComputedStyle()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)? Would there be a "font-width" entry as well as "font-stretch", and they’d be guaranteed identical?
* Are there precedents for this kind of aliasing in CSS? Are prefixed properties handled in a similar way in relation to unprefixed?

**Comment by ryanbugden** [comment]
Just chiming in to say: yes to font-width, deprecate font-stretch.

**Comment by svgeesus** [comment]
Putting this back on the agenda to choose between two options:

**1) Add `font-width` which is an exact alias for `font-stretch`.**

Adds no new features. Old sites won't update. However 99.6% of existing `font-stretch` is redundantly setting it to the initial value. Causes problems if both are used (with different values) and clutters the CSS OM.

**2) Add a more visible note to explain the bad name**

- the name is _historical_ and _unfortunate_
- it **does not** geometrically stretch the glyphs

The spec already forbids stretching:

> User agents must not synthesize stretched faces for font families which lack actual stretched faces.

But making that clear earlier in the property description might help

**Comment by litherum** [comment]
the web is full of unfortunate naming mistakes. why is this one special?

**Comment by nicksherman** [comment]
> the web platform is full of unfortunate naming mistakes. why is this one special?

Among other issues, this is particularly bad because the name implies the opposite of what it should actually do. It is more than unfortunate, it is directly misleading and confusing.

**Comment by svgeesus** [comment]
>  why is this one special?

Maybe the OP knows?

**Comment by litherum** [comment]
(The op closed this issue 7 years ago)

**Comment by cjdunn** [comment]
> **1) Add `font-width` which is an exact alias for `font-stretch`.**

Option 1 makes the most sense to me, thank you for including this!

**Comment by jpamental** [comment]
I think Nick hits the big point , which is that it’s more than just unfortunate; it actually harms adoption by a broader audience of designers “It is more than unfortunate, it is directly misleading and confusing.”So if we have the opportunity to add an alias to get proper terminology in there why wouldn’t we want to do that?Jason On Sep 20, 2023, at 10:45 AM, CJ Dunn ***@***.***> wrote:﻿

1) Add font-width which is an exact alias for font-stretch.

Option 1 makes the most sense to me, thank you for including this!

**Comment by dryan** [comment]
Option 1 seems like the best choice to me. I do wonder if there should also be a `font-inline-size` alias as well?

**Comment by fantasai** [comment]
@dryan Fair point, that it's not always a width. I don't think we need physical vs. logical properties here, though, just maybe ideally a name that works for both. On that note, @jpamental Would `font-pitch` work?

**Comment by nicksherman** [comment]
It’s also worth noting that “pitch” traditionally refers more specifically to the number of characters from a typeface that can be expected to fit in a given distance of line length (typically 1 inch). For example, "12-pitch" = 12 characters per inch.

I don’t understand the continued reluctance to just use the most obvious, reasonable, spec-consistent, and accessible term of `font-width`.

**Comment by svgeesus** [comment]
So the question is, whether implementers are willing to deal with the overhead of a property alias and a descriptor alias to finally get rid of this wart?

IF so, my proposal is:

- A property `font-width` exists (with largely same description that `font-stretch` currently has).
- For historical reasons, a property `font-stretch` exists which is an alias of `font-width`
- Setting `font-width` also sets `font-stretch` to the same value
- Setting `font-stretch` also sets `font-width` to the same value
- Getting either property returns that one value.

also

- a descriptor `font-width` exists on `@font-face` (same spec text as current `font-stretch` descriptor)
- for historical reasons, a descriptor `font-stretch` also exists which has the same meaning as `font-width` and is treated as being the same
- as with [other `@font-face` descriptors](https://drafts.csswg.org/css-fonts-4/#font-face-rule) we use the "last one wins":

> When a given descriptor occurs multiple times in a given `@font-face` rule, only the last descriptor declaration is used and all prior declarations for that descriptor are ignored.

**Comment by jpamental** [comment]
I think it's been summed up enough by others, but just adding my two cents
that I don't think `font-pitch` is the right answer; `font-width` is more
descriptive and in line with existing terminology in the fonts themselves
and in the type and graphic design world in general. Chris' proposal seems
reasonable.

Jason

**Comment by frivoal** [comment]
> my proposal is:
> 
> - A property `font-width` exists (with largely same description that `font-stretch` currently has).
> - For historical reasons, a property `font-stretch` exists which is an alias of `font-width`
> - Setting `font-width` also sets `font-stretch` to the same value
> - Setting `font-stretch` also sets `font-width` to the same value
> - Getting either property returns that one value. 

I agree, though I'd note I think we should define it specifically as a [legacy name alias](https://drafts.csswg.org/css-cascade-5/#legacy-name-alias) and rely on existing spec to characterize how the aliasing works, rather than custom define it. I think that gives the behavior you're aiming for.

**Comment by svgeesus** [comment]
Ah cool, I was unaware we already had a specified way to do this.

**Comment by svgeesus** [comment]
@drott any comments on [the proposal](https://github.com/w3c/csswg-drafts/issues/551#issuecomment-1755972551) given that the majority of existing `font-stretch` usage is from Google Fonts (setting the property to the initial value)?

**Comment by drott** [comment]
While I agree that the mismatch between name and axis in variable axis is unfortunate, I don't think it's a good use of time and energy to work on a deprecation only for the purpose of a rename with no functional change for a feature that's actively in popular use.  If no full deprecation is planned, long term, I don't think we're helped much with an alias.

With regards to the axis mismatch, I don't see this as a major problem. It's by the way perhaps worse for `font-style` and the `ital`, `slnt` axis - and in that area we do have some actual problems to solve for which we have strong developer signal, which may be a better use of time in comparison.

I agree with your own argument, @svgeesus that it clutters the CSS OM and introduces a bit of confusion and requires additional rules how to resolve alias vs. underlying property. 

No objections to 
>  *2) Add a more visible note to explain the bad name*

adding extra explanations to the wording being sub-optimal and historical.

**Comment by svgeesus** [comment]
As @rviscomi pointed out, 99.6% of usage is, redundantly, setting it to the initial value. So it isn't actively in popular use to actually _do_ something.

**Comment by liamquin** [comment]
I'd say that it's quite widely used in print stylesheets, e.g. with AntennaHouseFormatter, which DOES use font-stretch to stretch the font - more precisely i think as with font style, and weight, it chooses a matching font if there is one and synthesizes one if there isn't. I don't really see why you want font-stretch to behave differently in that regard. And it's actually technically easier than synthesizing small caps, italics, bold.

When i tried in PrinceXML, i found that the software behaved as if it had stretched the font, but font selection then failed in the resulting PDF.  I don't recall testing in Weasyprint or PDFReactor.

You aren't going to be able to measure the prevalence of something in off-web stylesheets by looking at Web statistics, unfortunately.

**Comment by scottkellum** [comment]
@liamquin I may not be reading that correctly so correct me if I’m wrong here: Do these tools synthesize stretched styles? If so that behavior does not adhere to [the font-stretch spec](https://drafts.csswg.org/css-fonts/#font-stretch-prop).

> User agents must not synthesize stretched faces for font families which lack actual stretched faces.

This proposal will not take away the font-stretch property, it will create a more accurate name. “Stretching” implies a scale transformation of the outlines. That is not what the `font-stretch` property does. This property selects a font width that has been defined by the designer of the font without stretching or distortion of outlines. This is extremely confusing as the name used implies behavior that is explicitly disallowed in the spec. For backwards compatibility the `font-stretch` property will still work alongside the more accurate `font-width` property.

**Comment by liamquin** [comment]
@scottkellum yes, there are implementations that can synthesize font-stretch (or could when i checked some time in the past 5 years), just as they could synthesize bold and italic. I'm aware it doesn't meet the spec. I don't imagine that renaming it to font-width will change this; you can do font-style: italic, and get a fake italic, so it's pretty absurd that setting font-width when the requested width isn't available can't make a faux condensed (regardless of how ugly it might look). I agree it's not what the spec says. When the spec differs from what implementations do, and from what users expect, there's always the possibility of changing the spec to conform to expectations and to implementations.

This confusion in CSS between font creation/distortion and font selection has always been a problem.

**Comment by Crissov** [comment]
[PrinceXML](https://www.princexml.com/doc/styling/#text-formatting): 

> … the property `font-stretch` might be used, but note that it does not change the geometry of any arbitrary font by stretching or shrinking it - instead, it merely instructs Prince to choose the most appropriate face of the font, if the selected font offers several ones. 
> Also note that this property is not supported for system fonts on Windows.

https://github.com/Kozea/WeasyPrint/issues/7

https://www.pdfreactor.com/product/doc_html/#font-stretch

**Comment by Crissov** [comment]
What about changing `font-stretch` to become a shorthand property that explicitly supports asking for synthesized stretched fonts when no pre-designed ones are available, while a new `font-width` sub-property only supports the current feature set?

**Comment by jfkthame** [comment]
I don't think we should be changing the behavior of the existing property. That would have potentially unexpected effects on existing content.

What we could consider, I think, is introducing a new `font-synthesis-width` property to explicitly enable the use of synthetic width (stretch) variants of fonts when no suitable pre-designed width variant is available. Typographic purists will presumably complain, but given that we have synthesis for other attributes, I don't think there's a strong argument to resist supporting it for width as well. Designers who care about typographic excellence don't have to use it!

**Comment by nt1m** [comment]
WPT coverage:
- name alias: https://github.com/web-platform-tests/wpt/blob/855859bf3f61ab1a6532a6b98fd92137baf2fabc/css/css-fonts/parsing/font-stretch-alias.html
- animations: https://github.com/web-platform-tests/wpt/blob/855859bf3f61ab1a6532a6b98fd92137baf2fabc/web-animations/animation-model/animation-types/property-list.js#L591-L594

**Comment by svgeesus** [comment]
https://github.com/web-platform-tests/wpt/pull/51775

**Comment by yisibl** [comment]
This will also affect the APIs in Canvas. https://github.com/whatwg/html/issues/11324

**Comment by emilio** [comment]
@svgeesus seems this missed updating `FontFaceDescriptors` etc right?

**Comment by drott** [comment]
> [@svgeesus](https://github.com/svgeesus) seems this missed updating `FontFaceDescriptors` etc right?

Which gets addressed in https://github.com/w3c/csswg-drafts/pull/14197
