### ISSUE TITLE
[css-contain] Computed value of shortcut values

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#5511]
[`contain`](https://drafts.csswg.org/css-contain/#contain-property) has 2 shortcut values, `strict` and `content`:

> **strict**: This value turns on all forms of containment except style containment for the element. In other words, it behaves the same as `contain: size layout paint;`. 
> **content**: This value turns on all forms of containment except size containment and style containment for the element. In other words, it behaves the same as `contain: layout paint;`.

But do they compute to themselves, or do they compute to the expanded list of values?

```js
document.documentElement.style.contain = "content";
getComputedStyle(document.documentElement).contain;
// "content" in both Chromium and Firefox

document.documentElement.style.contain = "layout paint";
getComputedStyle(document.documentElement).contain;
// "content" in Chromium, "layout paint" in Firefox
```

So Chromium expands the shortcuts in the computed value, and when serializing it uses the [shortest serialization principle](https://drafts.csswg.org/cssom/#serializing-css-values)

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

And in Firefox the specified value computes as-is, so `content` and `layout paint` are considered to be different values that just happen to produce the same behavior.

Who is correct? Firefox obeys "Computed value: specified keyword(s)", but "[`contain: content`] behaves the same as `contain: layout paint;`" could be understood to mean that they have the same computed value.

**Comment by SebastianZ** [comment]
One solution for that is to add a note to step 2 of the serialization algorithm to handle that case. Something like

> If either of the above syntactic translations would be less backwards-compatible or doesn't have a distinct representation, do not perform them.

With that addition in place, the longhand values are kept in case two representations conflict.

Sebastian

**Comment by tabatkins** [comment]
Hmm. So, the shortcut values don't do anything that's not expressible by just writing some of the longhands. So shortest-serialization would normally imply that a specified `contain: layout paint;` should serialize as `contain: content;`.

However, in <https://github.com/w3c/csswg-drafts/issues/5506#issuecomment-692724381> Oriol points out that if we introduce more shorthands that no longer form a strict hierarchy (currently they do), we'll have to deal with ambiguous shortest serializations. Not necessarily a problem, we can just spec our way out of it if necessary.

I'm inclined to specify that the computed value is the set of containments being applied, and they serialize using SSP. That would allow the internal impl to be a bitfield, which is reasonable, and I don't anticipate ever adding something that wouldn't be part of that. I'm happy to specify the application of SSP more specifically, too, to make sure that this is utterly clear.

**Comment by emilio** [comment]
FWIW Firefox Nightly doesn't give the results from the OP, it gives `contain` both for specified and computed value.

**Comment by Loirooriol** [comment]
@emilio Testing latest 2020-10-20 Firefox nightly this still produces `"layout paint"` for me:

```js
document.documentElement.style.contain = "layout paint";
getComputedStyle(document.documentElement).contain;
```
