### ISSUE TITLE
[cssom] Add IDL "MathMLElement includes ElementCSSInlineStyle;"

### ISSUE THREAD

**Issue by fred-wang** [w3c/csswg-drafts#5513]
cc @bkardell 

This is currently specified in MathML Core:

https://mathml-refresh.github.io/mathml-core/#dom-and-javascript

but it should probably be moved to the CSSOM spec:

https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-mixin

Something like:

------------

If the user agent supports MathML, the following IDL applies: [MathMLCore]

MathMLElement includes ElementCSSInlineStyle;

**Comment by fred-wang** [comment]
(Incidentally, this is already implemented in all browsers and tested in WPT)

**Comment by astearns** [comment]
The CSSWG discussed this today: https://logs.csswg.org/irc.w3.org/css/2020-09-17/#e1353029

RESOLVED: accept a PR to add CSSOM for MathML
