### ISSUE TITLE
[css-sizing-4] Support percentage lengths in contain-intrinsic-size

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#5514]
It would be useful to be able to specify containment sizing based on the width/height of the container. e.g.

`contain-intrinsic-size:100% 50%` would be to be 100% width and 50% height.

If we also add auto keywords we could support aspect-ratio:

`contain-intrinsic-size: 100% auto; aspect-ratio: 2/1`

This will allow subtrees that have `content-visibility: auto` to have an easier time with responsive design. Otherwise you might need approximations like:

`contain-intrinsic-size: min(var(--main-width), 600px) min(calc(var(--main-width) * 0.813333), 488px` (real example from a page using the property).

@cramforce @vmpstr @cbiesinger

**Comment by vmpstr** [comment]
"auto" keyword may go hand-in-hand with #5432

**Comment by chrishtr** [comment]
Some examples are in [this link](https://www.industrialempathy.com/posts/designing-even-larger-applications/). In that page, each image has `contain-intrinsic-size` and `content-visibility: auto`, but it is also laid out responsively.

**Comment by tabatkins** [comment]
We skipped percentages currently just due to trying to keep it as simple as possible, and lack of obvious use-cases. I'm happy to add them back in if we do have obvious use-cases, which it looks like we do, and we're happy with the added complexity, which it looks like we are. 👍

**Comment by chrishtr** [comment]
Ok let's do it. I do recall that that was the only reason we didn't so far. @tabatkins can we just make the edit withour further CSSWG discussion?

**Comment by chrishtr** [comment]
Chromium is happy with the added complexity given the upside for ergonomics of partner sites.

**Comment by fantasai** [comment]
Wait, I'm confused. Isn't the point of `contain-intrinsic-size` to provide an intrinsic size? Percentages by definition are the opposite of an intrinsic size, and definitely can't provide one. Is the effect you're trying to control just the scrollbar, while providing a zero intrinsic size or what?

> @tabatkins can we just make the edit without further CSSWG discussion?

This is my rubric for deciding whether I can close an issue:
* Editorial - no substantive change
* Bugfix - fixes an obvious error with an obvious solution
* CSSWG Resolution - resolved by the CSSWG, edits made, and the commenter agreed or was explicitly overruled
* Editor Discretion -  This is the tricky one; used in cases where
    * Solution isn't an obvious bugfix.
    * Impact of the solution is minor and localized:
        * There is no cross-module impact.
        * There is no cross-module consistency or integration concern.
        * It is unlikely to affect implementation architecture.
    * No syntax/API is affected.
    * There is consensus on the thread at least among the people involved in the discussion; **and**  nobody else in the CSSWG or its community is likely to care / have an informed opinion that I should be soliciting.
    * Spec is still a WD; (if it's CR, I might still edit it into the ED first and ask for WG signoff afterwards though).

[I also use Editor Discretion occasionally to close issues as No Change in cases where the commenter is clueless or the requested change would clearly violate a WG design principle.]

I don't think this discussion qualifies as Editorial, Bugfix, or Editor Discretion, so it would go to the CSSWG.

**Comment by chrishtr** [comment]
> Wait, I'm confused. Isn't the point of `contain-intrinsic-size` to provide an intrinsic size? Percentages by definition are the opposite of an intrinsic size, and definitely can't provide one. Is the effect you're trying to control just the scrollbar, while providing a zero intrinsic size or what?

The purpose of `contain-intrinsic-size` is to provide a sizing that represents the subtree's layout size without having to compute the subtree layout. In the example I linked to, the element with `contain-intrinsic-size` is an image; the contain-intrinsic-size would need to simulate the responsive layout of that image.

**Comment by bfgeek** [comment]
For the above cases the same effect can be achieved by specifying `width: 100%` with an `aspect-ratio` ?

**Comment by cbiesinger** [comment]
We think this is not needed anymore.
