### ISSUE TITLE
A bunch of specs say "CSS-wide keywords keywords" (repeating the word "keywords") in their "Value Definitions" section

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#5516]
This applies to various specs, as well as the sample "Foo" spec:
https://drafts.csswg.org/css-module-bikeshed/#values
https://www.w3.org/TR/css-display-3/#values
https://www.w3.org/TR/css-sizing-3/#values
...and more.

These specs all say (emphasis added):
>  all properties defined in this specification also accept the CSS-wide **keywords keywords** as their property value

I think the second "keywords" is a typo, right?

Google Search to find the affected specs:
https://www.google.com/search?client=firefox-b-1-d&q=site%3Aw3.org+%22CSS-wide+keywords+keywords%22

CC @tabatkins @fantasai

**Comment by dholbert** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/426803/93276937-d8473100-f775-11ea-90ef-43803506fa9f.png)

**Comment by svgeesus** [comment]
Ah, the [notorious CSS Foo](https://drafts.csswg.org/css-module-bikeshed/) is the culprit!

Its the template for new specs, so the error propagates. Fixing it there will stop any new specs from having this error. The old ones still need to be fixed.
