### ISSUE TITLE
[resize-observer] observe() not triggering initial callback

### ISSUE THREAD

**Issue by trusktr** [w3c/csswg-drafts#5529]
Has this more recently changed to where `new ResizeObserver(...).observe(el)` no longer triggers an initial observation? Or do I experience a browser bug?

Running this in Chrome console does not show any output:

```js
new ResizeObserver(() => console.log('change')).observe(document.body)
```

If we don't get the initial firing of the callback, how do we manually calculate the `borderBoxSize` and `contentBoxSize` arrays? It seems fairly complicated to come up with that data (and that's why it's nice to receive it in the callback).

**Comment by trusktr** [comment]
Ok, now it is working. Between then and now, I restarted Chrome, and now I see console output. Not sure what happened.

**Comment by trusktr** [comment]
Aha! I found where it does not trigger: when I `observe` a `<span>` element, there is no observation.

**Comment by trusktr** [comment]
Here is a live example: https://plnkr.co/edit/hhv6HRhjINxQocbX

**Comment by trusktr** [comment]
In the following example, I am using a `<p>` inside a `<div>` (instead of a `<span>` inside a `<p>`) to achieve almost the same effect, and the example shows that `observe` does fire initially when used on the `<p>`: https://plnkr.co/edit/uxo1Fal0SGD6tqmJ

But also, I see that the `borderBoxSize` and `contentBoxSize` arrays contain only one item each. I thought there would be 3 items each because the column splits the `<p>` into three parts. Is this a bug?

**Comment by trusktr** [comment]
I opened https://bugs.chromium.org/p/chromium/issues/detail?id=1137180

**Comment by dlibby-** [comment]
Per the spec, what you're seeing is by design (at least for observing <span> not triggering callbacks).
Observations do not fire for non-replaced inline Elements.

For returning fragments - yes that is currently not yet implemented.
