### ISSUE TITLE
[css-fonts] Reduce layout shift via @font-face descriptor(s) overriding inline spacing 

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#5533]
In #4792, we agreed to add @font-face descriptors to override ascent, descent and line gap of a font, which allows us to match the line height metrics between fallback and primary font, and hence, reduce layout shift.

In https://github.com/w3c/csswg-drafts/issues/4792#issuecomment-689099191 I also proposed `advance-override` to override the inline spacing and further reduce layout shift. The proposal still has several problems and hence remains under discussion.

So I opened this issue to specifically discuss if we should add new descriptor(s) to @font-face to override the inline spacing for matching text widths and reducing layout shift; And if we should, how should the new descriptor(s) work.

**Comment by tabatkins** [comment]
To start, it might be useful to divide the discussion into monospace fonts and variable-width fonts.

For monospace fonts, the proposal is straightforward I think. You have a primary font, and you want the fallback font to have an identical advance so it keeps to the grid. So we can just override the advance with a manually-set value, done.  (Do we want to center the glyph into the specified advance?)  This also prevents fallback to things like emoji fonts from screwing up your monospace grid, at least if we do it right.

Variable-width is potentially more difficult:

* Is a constant adjustment to the advance the best we can do? Or would it be better to have a %-based change, on the logic that a "skinnier" font is still likely to have a very similar width for its `i` to a wide font, but characters like `w` are likely to be a lot more different between the two.
* Do we need more complex logic for spacing, a la `letter-spacing`, so you don't get potentially-unsightly gaps at box edges?

**Comment by frivoal** [comment]
I am not sure that "monospaced" fonts are that simple in an i18n context. For instance, I believe that for CJK, "mono-spaced" is actually "dual-spaced", with full width glyphs being typically 1em wide, and half-spaced glyphs being half that size. Adding a single measurement to all glyphs wouldn't actually work then, would it?

**Comment by xiaochengh** [comment]
We've done some manual testing of two versions of adjustment:
- `advance-override`: Add a fixed amount to all glyph advances
- `advance-proportional-override`: Multiply the glyph advances by a given percentage

(The names are bad but I don't have a better idea...)

[Test result details](https://github.com/w3c/csswg-drafts/files/5404524/cls-with-hacks.html.pdf)

We found one case with legibility issues: when the font is too bold, reducing the advances may squeeze the characters together, making text hard to read. `advance-override` even made all the word boundaries disappear, while `advance-proportional-override` still preserves word boundaries.

Other cases seem fine. Anyway, it would be great if someone professional in Persian or Hindi could take a look at those test cases, as I am very unfamiliar with these scripts.

---

As a side note, I'm not sure how much we should be concerned about legibility issues. Our main focus is reducing CLS, so in most cases the overridden text should just appear as a flash. It's an issue only when the web font fails to load, and the fallback font differs from the web font so much that the overridden text becomes hard to read, in which case maybe it's better to use a different fallback font.

**Comment by jfkthame** [comment]
Personally, I'm unconvinced this is a good idea at all. Glyph spacing is an integral part of the font design, and arbitrarily overriding the spacing of glyphs -- not for a specific design intent such as letter-spacing but just to try and match metrics of some other font -- is never likely to look good.

To minimize layout shift, specify fallback fonts that have similar metrics to the desired webfont. If they're different enough that layout shift will be a significant problem, then they're also different enough that forcing them to match the intended font will be a distortion.

If it's more important to avoid layout shift than to use the designer's "ideal" font, then add a `font-display` descriptor to make it optional, and if it doesn't load quickly enough, just continue to use a fallback (with its own proper glyph spacing, not shoehorned into the metrics of the font that didn't load).

**Comment by jfkthame** [comment]
An alternative way to try and minimize layout shift if a fallback font is used would be to have a descriptor that allows a scaling factor to be applied to the font (thus improving the metrics-match by scaling the font as a whole, rather than by distorting its glyph widths).

**Comment by xiaochengh** [comment]
> If it's more important to avoid layout shift than to use the designer's "ideal" font, then add a font-display descriptor to make it optional, and if it doesn't load quickly enough, just continue to use a fallback (with its own proper glyph spacing, not shoehorned into the metrics of the font that didn't load).

Here we want both stable layout and the designer's ideal font, so `font-display` can't achieve the purpose. Instead,
we're using quality of fallback font typography as the cost of the tradeoff. 

> An alternative way to try and minimize layout shift if a fallback font is used would be to have a descriptor that allows a scaling factor to be applied to the font (thus improving the metrics-match by scaling the font as a whole, rather than by distorting its glyph widths).

This sounds like a viable idea. I'll do some testing with it.

Btw there's some similarity with #126, just for the record.

**Comment by jfkthame** [comment]
> Here we want both stable layout and the designer's ideal font, so `font-display` can't achieve the purpose. Instead,
> we're using quality of fallback font typography as the cost of the tradeoff.

It's possible the desired font will fail to load altogether, and the user will be left looking at the fallback font; it would be sad if they're left with not just a fallback font, but a fallback font with distorted spacing.

**Comment by xiaochengh** [comment]
Hmm, scaling the font size does seem to work better... See screenshots:

[cls-with-size-hacks.pdf](https://github.com/w3c/csswg-drafts/files/5419537/cls-with-size-hacks.pdf)

**Comment by litherum** [comment]
According to the discussion, I think this should be marked as a dup of https://github.com//issues/450

**Comment by chrishtr** [comment]
This should be discussed along with #126.

**Comment by chrishtr** [comment]
Regarding issue #450, I think it's more like a dup of #126.

I think it's good to focus on `advance-override` here, with the use case of reducing layout shift when a web font loads.

**Comment by xiaochengh** [comment]
Here's a proposal for the upcoming vf2f discussion:

```
advance-override: <percentage>
```

This is a new descriptor of @font-face that scales the advance width of every glyph of the font face by the given factor. The default value is `100%`.

We have implemented it in Chrome behind a flag, and have observed it working reasonably well. 

Regarding some previously discussed topics:

- Property or descriptor: We want to make it easy to implement and easy for web developers to adopt, and avoid all the complications in font face selection. Our proposal satisfies all, while we are not aware of any such property-based approach. See more discussions in #126. 

- `font-display`: Other than `optional`, `font-display` values do not change layout shifts. `optional` eliminates layout shift at the cost of having a lower chance to use the desired web font. We want to keep the desired web font, while reduce the layout shift cause by the fallback font, which usually doesn't stay long on the screen.

- Legibility/Typography: Legibility of fallback font will become worsened as a cost to reduced layout shift, but in many cases it should still be acceptable. Also note that it matters only when the web font completely fails to load. If the fallback font and the web font differ too much, we would recommend not using `advance-override`, but simply using a better fallback font as a straightforward solution.
  - @jfkthame suggested changing the fallback font size to match the web font while preserving legibility, which we actually have prototyped in Chrome and seen some good results. The problem is that we don't know how to spec it nicely as a descriptor. One of the ideas is "scaling the used font size by the given factor", but `font-size` is a property that has one value per element, while @font-face descriptors work on a per-glyph basis even in the same element.

- Relationship with `letter-spacing` property: They look similar but work at different levels, and don't interfere with each other. `advance-override` changes the advance widths of glyphs, and then `letter-spacing` adds spacing between the glyphs. Therefore, issues of `letter-spacing` (like #1518) do not apply.

- Naming: I think `advance-override` is a good enough summary of what it does -- overriding the advance width of every glyph of the font face. Alternatives are `advance-multiplier` or `advance-someotherverb` to avoid confusion with `ascent-override` etc. and indicate that the % refers to a different value.

**Comment by drott** [comment]
@chrishtr points out that the use case aimed at is
> […] the use case of reducing layout shift when a web font loads.

@xiaochengh can you clarify the relationship between this proposal and #126, and [for your proposal](https://github.com/w3c/csswg-drafts/issues/5533#issuecomment-773709932) can you confirm that the `advance-override` you're proposing applies to the actual font specified in `src:` of the @font-face when loaded? I assume, to use this for reducing layout-shift and specifying an advance-override for fallback fonts, you would work with `src: local(...)` to refer to local fallback font names, or how would you establish the connection? I assume the intention is not to have the primary font's advances permanently overridden as the end result after all fonts have loaded, but instead only show the condensed/stretched layout temporarily?

**Comment by nigelmegitt** [comment]
>     * Naming: I think `advance-override` is a good enough summary of what it does -- overriding the advance width of every glyph of the font face. Alternatives are `advance-multiplier`

+1 to `advance-multiplier` - otherwise I'd expect to be able to use other units than `<percentage>` and set an absolute value, which seems like an unhelpful approach. This name is much clearer, in a "does what it says" kind of way.

**Comment by tabatkins** [comment]
> @xiaochengh can you clarify the relationship between this proposal and #126,

No *direct* relation, at least for the issue that r12a raises in the original post of the thread, but it sits in a related space. This is for the more common case when both the primary and fallback font are visually similar and don't need any major adjustment, but just need slight tweaks to make their advances line up better.

> can you confirm that the advance-override you're proposing applies to the actual font specified in src: of the @font-face when loaded?

It applies to whatever font the @font-face ends up representing. I didn't really understand your question, but hopefully that answers it sufficiently?

> I assume, to use this for reducing layout-shift and specifying an advance-override for fallback fonts, how would you establish the connection in the font-stack, would you work with src: local(...) to refer to local fallback font names, or through other means?

This works entirely thru @font-face, so yes, if you want to adjust a local font for use as a fallback, you'd use `src: local()`.

> I assume the intention is not to have the primary font's advances permanently overridden as the end result after all fonts have loaded, but instead only show the condensed/stretched layout temporarily?

No, this is permanent; if it was temporary, it would cause the very layout shift we're trying to avoid.  Your primary font presumably won't have a multiplier, and will display normally; you generally will only apply this to your fallback to make it match the primary more closely, so that when the fallback is swapped out there's as little layout shift as possible.

**Comment by chrishtr** [comment]
> No, this is permanent; if it was temporary, it would cause the very layout shift we're trying to avoid. Your primary font presumably won't have a multiplier, and will display normally; you generally will only apply this to your fallback to make it match the primary more closely, so that when the fallback is swapped out there's as little layout shift as possible.

This is one of the reasons why it's a good idea to use a new font face that is used just in the fallback path, and that wraps the
local font.

Regarding timeouts: perhaps as a future feature we could consider adding a timeout parameter to these descriptors or the font face selection algorithm.

**Comment by fantasai** [comment]
Just wanted to note, the proposed name was `advance-override` to coordinate a bit more closely with ascent-override etc. which also modify the metrics of the font.

**Comment by chrishtr** [comment]
Looks like the resolution may not have been recorded, but there was a resolution 3 days ago to go ahead and add the feature as a font-face descriptor with the design generally along the lines of what Xiaocheng proposed in this issue.

**Comment by fantasai** [comment]
The resolution was recorded in the official minutes https://lists.w3.org/Archives/Public/www-style/2021Feb/0015.html just seems like the IRC bot didn't catch it.

**Comment by fantasai** [comment]
Agenda+ to ask if we should close this issue as no-change, now that we have `size-adjust`.

**Comment by chrishtr** [comment]
+1 to closing the issue.

**Comment by svgeesus** [comment]
+1
