### ISSUE TITLE
alignment properties in block layout.

### ISSUE THREAD

**Issue by jacobbogers** [w3c/csswg-drafts#5546]
*[css-align]
Specifc [§ The justify-content and align-content Properties][1]

**align-content** is stated to work for  _block containers_
> block containers, multicol containers, flex containers, and grid containers

As of this writing is their real support for the box alignment properties in block layout.?

[css-align-3][1]
[1]: https://drafts.csswg.org/css-align/#align-justify-content

**Comment by fantasai** [comment]
Unsupported as of now. It's on the to-do list of various browser engines, but not a priority.

Closing out since this is not a spec issue.

**Comment by jacobbogers** [comment]
Thanks for taking the time to answer (it was not a spec issue so double thanks)

**Comment by jacobbogers** [comment]
How can i found out what is implemented (chromium) or what is going to be implemented in near future for the various rendering engines/browsers? I am looking for some kind of dev- mailing list or something

**Comment by astearns** [comment]
@jacobbogers this site has a lot of links to project-specific lists and bug trackers:

https://wpc.guide/who-to-talk-to/

**Comment by jacobbogers** [comment]
> @jacobbogers this site has a lot of links to project-specific lists and bug trackers:
> 
> https://wpc.guide/who-to-talk-to/

outstanding! thanks alot
