### ISSUE TITLE
[css-fonts] font-size-adjust: percentage

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5547]
https://www.w3.org/TR/css-fonts-4/#font-size-adjust-prop

The value supplied to font-size-adjust represents the fraction of the font-size which the [aspect value](https://www.w3.org/TR/css-fonts-4/#aspect-value) should fill. Presumably this should be a percentage instead of a raw number?

We probably can't remove the raw number, since it's shipping in Firefox, but we can at least make the grammar `none | <number> | <percentage>`.

**Comment by litherum** [comment]
@jfkthame

**Comment by fantasai** [comment]
I'd rather not add percentage as a synonym of number. It doesn't get us anything new, and will block us if at some point we want something new mapped to percentages.

**Comment by litherum** [comment]
Right, makes sense.
