### ISSUE TITLE
[css-writing-modes] percentage size of orthogonal box in auto-sized container resolves against ICB

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#555]
gtalbot submitted a set of tests that render the same in Edge, Blink, and Gecko but don't match the Writing Modes spec. We should probably update the spec in this case.

The situation is a percentage-inline-size element establishing an orthogonal flow inside an auto-sized parent. The spec doesn't say anything special, but one would imply from CSS2.1 that the percentage should be treated as auto. But it seems to resolve against the initial containing block. (Though I'm not 100% sure if that's actually what is going on.)

http://gtalbot.org/BrowserBugsSection/CSS3WritingModes/s732-sizing-orthog-vrl-in-htb-024.xht

**Comment by kojiishi** [comment]
Isn't [7.3.1. Available Space in Orthogonal Flows](https://drafts.csswg.org/css-writing-modes-3/#orthogonal-auto) the definition for this case?

> the available inline space to be indefinite. In such cases a percentage of the containing block’s inline size cannot be defined, and inline axis computations cannot be resolved. In these cases, the initial containing block’s size is used as a fallback variable in place of the available inline space for calculations that require a definite available inline size.

Blink falls back to ICB logical height if the CB's logical height is not fixed and available logical height is not definite. Code [here](LayoutBox::perpendicularContainingBlockLogicalHeight).

**Comment by kojiishi** [comment]
ping @fantasai -- can you confirm if this is talking about 7.3.1, or something else?

**Comment by kojiishi** [comment]
ping @fantasai -- can you confirm if this is talking about 7.3.1, or something else?

**Comment by kojiishi** [comment]
Sorry, wrong issue ^

**Comment by fantasai** [comment]
@kojiishi I think you're right on the description, and the testcase doesn't have any percentage, so I don't know what this issue is about. :) Closing as invalid.
