### ISSUE TITLE
[css-inline-3] [css-display-3] Root inline box description conflicts with "Inline Layout Box Model" diagram

### ISSUE THREAD

**Issue by twilco** [w3c/csswg-drafts#5555]
Quoting https://drafts.csswg.org/css-inline-3/#model:

> The block container also generates a root inline box, which is an anonymous inline box that holds all of its inline-level contents.  (Thus, all text in an inline formatting context is directly contained by an inline box, whether the root inline box or one of its descendants.)

And quoting https://drafts.csswg.org/css-display-3/#block-container:

> A block container that contains only inline-level content establishes a new inline formatting context. The element then also generates a root inline box which wraps all of its inline content. Note, this root inline box concept effectively replaces the "anonymous inline element" concept introduced in CSS2§9.2.2.1.

These passages imply that each block container only generates a singular root inline box, and that this root inline box wraps _all_ inline-level content present in the block container.  However, that immediately conflicts with the "Inline Layout Box Model" diagram that is also in https://drafts.csswg.org/css-inline-3/#model, which shows multiple root inline boxes each wrapping separate pieces of inline-level content within the block container:

![CSS Inline Layout Box Model, shows three root inline boxes nested within separate line boxes](https://user-images.githubusercontent.com/6610100/94390016-1568d700-0117-11eb-81a0-4a60cac2b294.png)

This notion of multiple root inline boxes also seems to be well established outside the spec — see https://github.com/w3c/csswg-drafts/issues/1477#issue-232094849 and https://github.com/w3c/csswg-drafts/issues/1477#issuecomment-313249280, both of which layout the given example with multiple root inline boxes.

What is correct — multiple root inline boxes per block container, or one?

**Comment by Loirooriol** [comment]
I think there is a singe root inline box, which can have multiple fragments. And the diagram  is pointing to some of these fragments.

**Comment by fantasai** [comment]
Exactly as @Loirooriol explains, the diagram is pointing to the various fragments of the root inline box. Perhaps it would be better to place the diagram after the section describing fragmentation into line boxes.

**Comment by fantasai** [comment]
@twilco Moved the diagram. Let me know if this is adequate or if there's some other clarification that would help?

Note that #1477 is about block-in-inline splits, which is a bit of a different case. (For one thing, it involves inlines being split across multiple block containers.)

**Comment by twilco** [comment]
Thanks, that spot looks better.  This makes sense to me now, so closing this out.
