### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#5556]
https://drafts.csswg.org/ responds with:

> WARNING: mysqli_connect(): (HY000/2002): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

**Comment by plinss** [comment]
Fixed

**Comment by svgeesus** [comment]
Drafts server is down. No error message, just a timeout. Traceroute just loops on * * * without terminating.

Recent uptime seemed good:

![image](https://github.com/user-attachments/assets/72f518b6-2cdc-4127-b1e5-6060b6e89d56)

**Comment by svgeesus** [comment]
@plinss

**Comment by svgeesus** [comment]
wiki.csswg.org also down

**Comment by svgeesus** [comment]
Still down (telcon about to start)

**Comment by plinss** [comment]
Appears up to me and no incidents in the logs. If it's still down for you this might be the IDP system blocking your IP

**Comment by plinss** [comment]
(Note that the IDP system does block IPs for rate limit violations)

**Comment by svgeesus** [comment]
For debugging:

IPv6: ? [2a02:587:e912:2f00:34a3:2af:8d0e:df37](https://whatismyipaddress.com/ip/2a02:587:e912:2f00:34a3:2af:8d0e:df37)

IPv4: ? [85.72.151.162](https://whatismyipaddress.com/ip/85.72.151.162)

**Comment by plinss** [comment]
Yep rate limit violation:
`crowdsec.log:time="2024-07-31T07:14:30-07:00" level=info msg="(core.csswg.org@45.79.94.155/crowdsec) crowdsecurity/nginx-req-limit-exceeded by ip 85.72.151.162 (GR/6799) : 4h ban on Ip 85.72.151.162"
`

**Comment by svgeesus** [comment]
Thanks for confirming, @plinss 

I was looking at a lot of specs (for CSS 2024) but surprised that one manual user, even with like 50-100 open tabs, would trigger rate limiting.

**Comment by plinss** [comment]
The current rate limits are somewhat arbitrary and can certainly be adjusted if regular users are hitting them. It's a matter of finding a balance between patterns of normal use and badly behaving bots, which are constantly hitting the server and were sucking up an obscene amount of resources before the current rate limit/ban system went into effect.

In general the limits are 1 request/second over a 10 minute window, with bursts allowed over short periods to fetch linked resources. The burst rate is higher for image folders, but in theory, a single spec loading over 200 resources could trigger a rate limit. Note that when a rate limit is hit, the server starts returning 429 codes, so a well-behaved bot should back off. It's only when rate limits are triggered multiple times over a short period that the IP ban comes into effect.

For your incident, you hit 6 rate limits over 13.5ms (likely just too many resources for a single spec). I just bumped the burst limit for images to 300.

Also note that bans are cumulative, e.g. 4 hours for first ban, 8 for second, 12 for third, etc. We currently have some offenders at 92 hour bans, and thanks to CrowdSec's blocklists we're currently blocking 52634 known bad IPs.

**Comment by svgeesus** [comment]
Cheers @plinss for the thorough explanation.

I wonder if this is related to our getting 1Gbps fiber internet here in our flat in Athens :)

Well I guess I will know if I hit an 8h second ban :)
