### ISSUE TITLE
[css-conditional-3] Allowing semicolons

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5558]
@SimonSapin [wrote on www-style in 2013](https://lists.w3.org/Archives/Public/www-style/2013Aug/0527.html)

>>Le 25/08/2013 21:36, Tab Atkins Jr. a écrit :
>> On Sun, Aug 25, 2013 at 1:08 PM, Simon Sapin <simon.sapin@exyr.org> wrote:
>> Le 25/08/2013 08:01, Cameron McCormack a écrit :
>>
>>>      @supports (var-a: abc;)               { ... fails ... }
>>
>> This one should be the same as
>>
>>    @supports (color: green;)
>>
>> What do we want these to do?
>

>> Yes, it is - note the equivalent statement without the semicolon in
>>the "passes" section of his email.
>>
>> Per the Conditional spec's grammar, having a semicolon at the end is invalid.

> Yes, this is what I’m reading from the spec as well, but I seem to 
> remember F2F discussions where dbaron wanted this to be valid because 
> people might just add the semi-colon by habit. Or did I make this up?

**Comment by tabatkins** [comment]
This is tested in <https://wpt.fyi/results/css/css-conditional/at-supports-038.html?label=experimental&label=master&aligned> and everyone passes the current text (disallowing `;` in a supports condition), so I don't think we should change anything.

**Comment by svgeesus** [comment]
Thanks, Tab. I agree that if it is already interoperable we should not change anything.
