### ISSUE TITLE
[css-conditional-3] Are there issues with !important in @supports?  (Is the grammar wrong?)

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5559]
@SimonSapin [wrote on www-style in 2013](

>Le 30/04/2013 07:44, John Daggett a écrit :
>> I've updated the CSS3 Fonts draft based on Simon's feedback.
>>
>>> AFAICT, the point of <descriptor_declaration> is to not have the <prio>
>>> production for !important. You could, like @supports, refer to
>>> <declaration> defined in the Core Grammar instead.
>> Does @supports specifically ban the <prio> production?  I don't see
>> the language in there for that.  It's a relatively minor point but I
>> added the production to be clear that '!important' has no function in
>> @font-face rules (there have been issues brought up in the past in
>> relation to this).

> I just assumed that because @supports defines <declaration> explicitly 
> by referring to Chapter 4:
>
>   declaration : property S* ':' S* value;
>
> rather than Appendix G:
>
> declaration
>   : property ':' S* expr prio?
>    ;

> But I was wrong. !important is allowed and has no effect. This is 
> specified in section 6, just before section 6.1:

>> A trailing ‘!important’ on a declaration being tested is allowed,
>> though it won't change the validity of the declaration.
>>
>> For example, the following rule is valid:
>>
>> @supports (display: flexbox !important) {
>>   // ...
>> }

**Comment by svgeesus** [comment]
@SimonSapin a few questions:

1. Is this just about @supports or is it about `!important` in descriptors in general
2. Does the point you made by referring to CSS2.1 grammar still hold now that Conditional 3 uses the CSS Syntax module instead?
3. Are you saying that

- `!important` in descriptors is allowed, valuable, and we should test it 
- `!important` in descriptors is allowed, unfortunately, and we change the grammar to disalow it
- something else?

**Comment by tabatkins** [comment]
Just to confirm, [here's a testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%40supports%20(background%3A%20red)%20%7B%0A%20body%20%7B%20background%3A%20red%3B%20%7D%0A%7D%0A%40supports%20(background%3A%20green%20!important)%20%7B%0A%20body%20%7B%20background%3A%20green%3B%20%7D%0A%7D%0A%3C%2Fstyle%3E)

Chrome and Firefox both show green (!important is allowed)

**Comment by Loirooriol** [comment]
So is this expected?

```js
CSS.supports("background: green !important"); // true
CSS.supports("background", "green !important"); // false
```

**Comment by fantasai** [comment]
@Loirooriol Mind filing that as a separate issue?

**Comment by svgeesus** [comment]
@fantasai `Closed - no change` so which edits?

**Comment by fantasai** [comment]
@svgeesus Idk, maybe I was looking at the wrong issue or something. :)
