### ISSUE TITLE
[css-conditional-3] The CSSGroupingRule interface

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5560]
There is a WPT [test for The CSSGroupingRule interface](https://test.csswg.org/suites/css-conditional-3_dev/nightly-unstable/html/test_group_insertRule.htm) which [has passes in Chrome, Firefox, and Safari](https://test.csswg.org/harness/details/css-conditional-3_dev/test_group_insertrule/).

That interface [exists in the 2013 CR](https://www.w3.org/TR/css3-conditional/#the-cssgroupingrule-interface) and [not in the current ED](https://drafts.csswg.org/css-conditional-3/#the-cssgroupingrule-interface). The [changes section](https://drafts.csswg.org/css-conditional-3/#changes) does not mention removing it.

Was it removed deliberately and if so why, it it bad in some way, given there are three implementations?

Was it removed accidentally and if so, I guess it should be added back?

**Comment by SebastianZ** [comment]
A quick look at the change history shows that it was removed from the spec. last year because it is [already defined in CSSOM](https://drafts.csswg.org/cssom/#the-cssgroupingrule-interface). See #3528 for more info.

Sebastian

**Comment by svgeesus** [comment]
Cheers! So that test should be updated so the spec link points there.

And we need tests for all the other APIs, which are untested.
