### ISSUE TITLE
[css-values-4] Should ratios always get serialized with both components?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#5561]
https://drafts.csswg.org/css-values-4/#ratio-value

Currently, a ratio like "16 / 1" will get serialized as "16". But for a ratio, that seems unintuitive. Should ratios always get serialized with the slash?

(@dvoytenko  fyi)

**Comment by tabatkins** [comment]
I'm weakly in favor of this; relying on shortest-serialization-principle to turn `16 / 1` into `16` does feel a little weird here.

The question is just whether it's weirder for a ratio with an explicit `/1` to get serialized without it, or for a ratio that's just a number to get serialized with a `/1`. I think the first one is weirder.

**Comment by cbiesinger** [comment]
@fantasai points out https://lists.w3.org/Archives/Public/www-style/2019Oct/0001.html

**Comment by fantasai** [comment]
Yes, they should be serialized qirh both components always. See @AmeliaBR's comments in https://github.com/w3c/csswg-drafts/issues/3757#issuecomment-525845920 which we resolved to accept in https://lists.w3.org/Archives/Public/www-style/2019Oct/0001.html

**Comment by cbiesinger** [comment]
Thank you, the change looks good.
