### ISSUE TITLE
[css-cascade] Define "Applies to" better

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5565]
(Forked from https://github.com/w3c/csswg-drafts/issues/1861#issuecomment-691751716)

The precise effect of "applying" or "not applying" tends to vary a fair bit. The statement in [cascade-3](https://drafts.csswg.org/css-cascade-3/#applies-to) is generic enough that it's probably fine in all cases, but I am not sure it helps more than it hurts when it comes to gray zones and other ambiguities.

For instance, css-text has a bunch of things that apply to inline boxes. If you try and apply them to block boxes, it inherits into the (possibly anonymous) inline boxes, and has an effect that way. This is not in contradiction with the spec's statement, since indeed, there is no effect on the block box, and its only through inheritance that anything happens, but the statement does not shed any light on this situation.

Another one would be `writing-mode` and `text-orientation`, which don't apply to various table parts, yet still influence the calculation of [font relative length units](https://drafts.csswg.org/css-values/#font-relative-length) on these same elements through the computed value. Still not necessarily a contradiction if you're strict about it, but not really helping either.

PR https://github.com/w3c/csswg-drafts/pull/5562 is one attempt to improve this. We could also make a separate section about this.

cc: @fantasai @tabatkins

**Comment by frivoal** [comment]
@tabatkins has merged #5562, which addresses this. I am satisfied, so closing.

If anyone else wants to argue about a tweak or a different way of doing this, you can file a separate issue or pull request with your specific grievances about how the spec now is.

**Comment by fantasai** [comment]
Reopening because this needed fixing in L4 as well, and probably need to do a bit more thinking about where it fits editorially since that note basically hijacked the entire section which was supposed to be about Used Values, not about defining Applies to
