### ISSUE TITLE
[css-display] Should <display-legacy> values be aliased at parse time?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#5575]
https://drafts.csswg.org/css-display-3/#typedef-display-legacy defines some `<display-legacy>` values which are equivalent to a  `<display-outside> || <display-inside>` combination:

| Short `display` | Full `display`   |
| --------------- | ---------------- |
| inline-block    | inline flow-root |
| inline-table    | inline table     |
| inline-flex     | inline flex      |
| inline-grid     | inline grid      |

And then the spec says

> Following the precedence rules of “most backwards-compatible, then shortest”, serialization of equivalent display values uses the “Short display” column.

What seems clear to me is that short and full displays have the same computed value, so we must have

```js
document.body.style.display = "inline flow-root";
getComputedStyle(document.body).display; // "inline-block"
```

What is less clear to me is whether the aliasing happens only at computed value time, or earlier at parse time:

```js
document.body.style.display = "inline flow-root";
document.body.style.display; // "inline flow-root" or "inline-block" ??
```

Firefox says "inline-block", Chromium doesn't support the multi-values syntax yet.

While it's common to serialize declared values without optional components when the default value was provided (according to the shortest serialization principle), or with missing optional values that were omitted (against the SSP), or with a normalized order when there are multiple components, it seems less common to completely replace the declared value with another one.

For example, Chromium doesn't do it for `contain`:

```js
document.body.style.contain = "paint layout";
getComputedStyle(document.body).contain; // "content" in Chromium, "layout paint" in Firefox
document.body.style.contain; // "layout paint" in Chromium & Firefox
```

**Comment by emilio** [comment]
I suspect the code @bfgeek was referring to is [this](https://github.com/jquery/jquery/blob/a684e6ba836f7c553968d7d026ed7941e1a612d8/src/effects.js#L171) code from jquery. I expect a fair amount of code like that not stop working if we decide to make them separate values with different serializations.

Of course, that's the same kind of thing that would happen if we added a new display type, but it seems a bit unfortunate to enforce everyone to deal with a new name for an old thing :)

Again, I won't object to such thing and I think that even though it's a breaking change for Gecko it's probably an ok change to make, if we go that route, but I'd love to have some feedback from JS frameworks as well if someone has contacts in that space.

**Comment by astearns** [comment]
@stubbornella do you have an opinion on this, or know anyone who could weigh in?

**Comment by tabatkins** [comment]
> Of course, that's the same kind of thing that would happen if we added a new display type, but it seems a bit unfortunate to enforce everyone to deal with a new name for an old thing :)

Yeah, as fantasai and others discussed during the call, focusing on "this will break old code that doesn't expect it" is gonna be true for every new feature we ever introduce, and is particularly true for this precise code when we add new display types (such as the half-dozen math-related display types we also decided to add during this call). I'm not sure why we're so pressed about this in particular - it's not changing any existing code, it's just new code written using the new syntax that will cause libraries like this to break (just like they would with `display:math`).

**Comment by tabatkins** [comment]
Re-reviewing this, @fantasai and I still prefer to leave the new forms as separate values that just act identically. This doesn't change behavior for any code that currently uses a legacy value, and if code breaks with one of the new forms, it'll break with any other new display value, too, so there's not a lot we can do there.

Agenda+ to confirm that this is okay (or decide the opposite). Also need to decide whether computed-value serialization will use the legacy keywords due to the shortest-serialization principle, or if we want to still consider them distinct values that act identically there, too.
