### ISSUE TITLE
[css-backgrounds-3] Invalid CSS value syntax for 'final-bg-layer'

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#5576]
The syntax specified for the `final-bg-layer` type is incorrect:
```
<final-bg-layer> =  <\'background-color'> || <bg-image> || <bg-position> [ / <bg-size> ]? || <repeat-style> || <attachment> || <box> || <box>
```

Note the forward slash in `<\'background-color'>`

**Comment by fantasai** [comment]
It's been fixed in the ED, but the /TR copy hasn't been updated in 3 years (!)
