### ISSUE TITLE
[css-grid][css-grid-2]"subgid" should be "subgrid" in 7.2.3.1

### ISSUE THREAD

**Issue by Clarkkkk** [w3c/csswg-drafts#5579]
In both https://www.w3.org/TR/css-grid-2/#repeat-syntax and https://drafts.csswg.org/css-grid/#repeat-syntax, the second last paragraph:
It can only be used with the **subgid** keyword and cannot specify track sizes, only line names.
should be
It can only be used with the **subgrid** keyword and cannot specify track sizes, only line names.

**Comment by SebastianZ** [comment]
Thank you for the hint, @Clarkkkk! I've created a Pull Request to fix it.

Sebastian
