### ISSUE TITLE
[selectors] Restrict :is/:where/etc based on context

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5581]
By default, :is() (and friends) accept complex selectors. However, we likely want to narrow what is allowed inside :is() based on the context where it's used. For example, for :host(:is(...)), only compound selectors should be allowed, and for ::before:is(...), only user action pseudo-classes.

**Comment by Loirooriol** [comment]
Seems a duplicate of #5093

**Comment by andruud** [comment]
Ah, thank you @Loirooriol
