### ISSUE TITLE
[css-values] Duplicate references

### ISSUE THREAD

**Issue by momdo** [w3c/csswg-drafts#559]
In https://www.w3.org/TR/2016/CR-css-values-3-20160929/#references :
- [CSS-BACKGROUNDS-3] and [CSS3BG]
- [CSS-IMAGES-3] and [CSS3-IMAGES]
- [CSS-COLOR-3] and [CSS3COLOR]
- ([CSS-CASCADE-4] and [CSS3CASCADE])

These references are overlapping (or different version forms).

**Comment by tabatkins** [comment]
Fixed!
