### ISSUE TITLE
[css-contain] Terminology question

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5590]
Taken from a comment of @MatsPalmgren in https://github.com/w3c/csswg-drafts/issues/4931#issuecomment-615146842

> BTW, is "_containing box_" really a good term to use? Isn't "_container's box_" clearer? Or perhaps "[_principal box_](https://drafts.csswg.org/css-display/#principal-box)" would be better since it's an already established term.

I feel that @MatsPalmgren has a point. Between "[containing block](https://drafts.csswg.org/css-display-3/#containing-block)" and "[block container box](https://drafts.csswg.org/css-display-3/#block-container)", we have enough similar/confusing terminology already, and adding _containing box_ to that isn't great, and we probably should have picked something better. Since this is just terminology, with no impact on any implementation, we can still change if we find something better.

That said, I don't think "container's box" helps with the terminology overload.

"principal box" isn't wrong, but it's not specific enough either, because we're trying to talk about a particular one. The definition for which we'd like a name is:
> The principal box of the element to which containment is applied

Maybe "containment box", possibly qualified to "size containment box", "layout containment box", or "paint containment box" as appropriate? This is still a bit too close for comfort to "containing block" and "block container box", but at least the word "containment", even if similar, is never used in any other context.

cc @tabatkins

**Comment by rachelandrew** [comment]
Agreed, I think containment box would definitely be better than anything that might tangle the definition in people's minds with _containing block_.
