### ISSUE TITLE
[css-values] `url()`, cacheing, and incognito mode

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5591]
Originally raised [over here](https://github.com/w3c/csswg-drafts/issues/5553#issuecomment-704424447) during security and privacy review for downloadable ICC color profiles. But it applies to all resources (images, etc) in CSS so is best documented on `url()` (and on any successor to `url()` be that called `fetch()` or `src()` or whatever)

The [definition of the `url()` function](https://drafts.csswg.org/css-values-4/#urls) should clarify that

> the referenced file is persisted in your browser cache per standard resource caching rules, and is cleared in the same way.

**Comment by fantasai** [comment]
@svgeesus We added a note about caching, let us know if this is satisfactory.

**Comment by svgeesus** [comment]
LGTM
