### ISSUE TITLE
[mediaqueries]  Recursive/Incorrect identity '<media-in-parens>' syntax in w3.org specs

### ISSUE THREAD

**Issue by AvtomatK** [w3c/csswg-drafts#5593]
In section "_3 Syntax_" of the specifications: "_media queries-4_" and "_mediaqueries-5_", in the identity definition of **< media-in-parens >** there is a "definition recursion" together with **< media-condition >**, that is, **< media-condition >** is defined with **< media-in-parens >** and viceversa, creating a "chicken and egg paradox".

I would appreciate an explanation if I am wrong, thanks.

https://www.w3.org/TR/mediaqueries-4/#mq-syntax
https://www.w3.org/TR/mediaqueries-5/#mq-syntax

**Comment by AvtomatK** [comment]
I think the recursion was intentional...

**Comment by tabatkins** [comment]
Yup, it's a recursive production, that's intentional.
