### ISSUE TITLE
[w3.org - CSS Current Work Homepage]  Specification link redirects you to the wrong place

### ISSUE THREAD

**Issue by AvtomatK** [w3c/csswg-drafts#5597]
The "CSS Conditional Rules Level 4" (FPWD) specification link redirects you to "CSS Conditional Rules Level 3" in CSS current work homepage of w3.org.

https://www.w3.org/Style/CSS/current-work

**Comment by tabatkins** [comment]
Not even a redirect, the link is just plain wrong. @fantasai?

**Comment by AvtomatK** [comment]
Yes, I used the wrong word, it's just the wrong link.

**Comment by fantasai** [comment]
It looks like this was fixed at some point. Thanks for the report, @AvtomatK :)
