### ISSUE TITLE
[css-2020] Clear 'aspect-ratio' for shipping

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5598]
Since Chrome [intends to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/TF41VMfLhMI/m/vEU0Wl7kBwAJ) and Mozilla is implementing also, should we add `aspect-ratio` to the list in https://www.w3.org/TR/css/#CR-exceptions for 2020?

**Comment by frivoal** [comment]
Done through commit f7835959887eccf5a8da804349605f1303230ed6
