### ISSUE TITLE
[css-flexbox-1] Initial Value for flex-grow incorrect?

### ISSUE THREAD

**Issue by impressivewebs** [w3c/csswg-drafts#5602]
[Here you'll find a few paragraphs describing flex-grow and flex-shrink](https://drafts.csswg.org/css-flexbox-1/#valdef-flex-flex-grow). It says for `flex-grow`:

> When omitted, it is set to 1.

Is this a mistake? According to [the property definition table](https://drafts.csswg.org/css-flexbox-1/#flex-grow-property) the initial value is 0. So it seems this should be corrected to:

> When omitted, it is set to 0.

**Comment by tabatkins** [comment]
No, it's correct. This one's a bit funky - the flex-grow component of the 'flex' longhand does *not* default to the initial value of the 'flex-grow' property.

**Comment by impressivewebs** [comment]
@tabatkins Ah that's interesting. So, is there something you could add to that explains this a bit? Because it appears to be a contradiction. Or is it explained somewhere else?

**Comment by tabatkins** [comment]
Check the note at the end of that subsection, just before the 7.1.1 heading. ^_^
