### ISSUE TITLE
[scroll-animations] Possible infinite loop with element-offset

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#5609]
In https://drafts.csswg.org/scroll-animations-1/#element-based-offset-section
The timeline of the animation is decided by (roughly) the distance between the viewport edge and an element's edge.
However, the animation itself can affect that edge - e.g. if it's animating the `height` property.

So, if I'm not missing something, there could be a situation where the progress of the animation flickers endlessly.
This is already the case with hover pseudo elements (hovering on an element might cause a repositioning that would change the hover state).
Is this a problem? Maybe somehow the algorithm already deals with it?

**Comment by flackr** [comment]
The ability to cause cycles is explicitly called out in the spec [here](https://drafts.csswg.org/web-animations-2/#avoiding-cycles). In particular we avoid tight layout cycles but it is possible to construct an animation which flickers frame by frame like with hover.
