### ISSUE TITLE
[cssom-view] Separate getBoundingClientRect algorithm from the public API

### ISSUE THREAD

**Issue by szager-chromium** [w3c/csswg-drafts#5614]
The IntersectionObserver spec refers to "the getBoundingClientRect() algorithm", which isn't actually a thing. We need to split out the algorithm from the public API, so that other specs can refer to the algorithm.

https://github.com/w3c/IntersectionObserver/issues/55

**Comment by zcorpan** [comment]
#7446 fixed this.
