### ISSUE TITLE
[css-grid-1] Fix aspect-ratio errors in css-grid-1

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5615]
Commit https://github.com/w3c/csswg-drafts/commit/72f2bb240038bf00ada76dbac004105138231866 which attempted to clarify the interaction of `aspect-ratio` with grid item sizing introduced some errors in the most recent CR. This has been fixed in https://github.com/w3c/csswg-drafts/commit/72f2bb240038bf00ada76dbac004105138231866

The resulting text is https://drafts.csswg.org/css-grid-1/#grid-item-sizing

Agenda+ to verify the resulting text and republish as CRD. CC @cbiesinger @Loirooriol

**Comment by Loirooriol** [comment]
> This has been fixed in 72f2bb2

I guess you mean ee91993c92ba7d119a6b89c64667094511d67272. Looks good to me, but css-grid-2 will need to be fixed too.
