### ISSUE TITLE
[css-values][all] Define all URL usages in terms of Fetch

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#562]
The platform has settled on using the Fetch model to define fetching. CSS currently hand-waves a bunch of this, and as a result there are some browser-compat issues with corner cases, like what referrer to use in various situations.

[WebAppSec defines some of this behavior _for_ us](https://github.com/w3c/webappsec-referrer-policy/issues/5#issuecomment-249556892) ([and here](https://github.com/w3c/webappsec-referrer-policy/pull/34/files#diff-117d6498d2aa8019cc0abf5eeb87a9fa)), which we should move into a CSS spec.

(This is mostly a tracking bug to remind me to do this, and track links to useful resources. If anyone else clueful would like to help, feel free.)

**Comment by noamr** [comment]
I don't believe this is going to be difficult to accomplish.
Where should a common algorithm for fetching style resources sit? `[css-values]`?

**Comment by tabatkins** [comment]
My own experience so far suggests that it definitely *is* difficult to accomplish. ^_^ But I'd absolutely welcome help in defining this, if you have better insight into the problem.

Currently our attempts at fetching things are spread between CSSOM (for top-level stylesheet; currently broken and not invoking the Fetch algos correctly) and Cascade (for @import; currently being written by me in an attempt to use the Fetch algos correctly but definitely currently broken too).

I *suspect* that url() usage in *properties* should generally be quite easy; there's a *lot* less observable behavior we have to worry about, but there's still *some* piping of document state thru stylesheets that probably needs to be done in CSSOM. Values & Units is indeed the appropriate place to define the *general* handling of url() tho; PRs absolutely welcome.

**Comment by noamr** [comment]
> My own experience so far suggests that it definitely _is_ difficult to accomplish. ^_^ But I'd absolutely welcome help in defining this, if you have better insight into the problem.
> 

Fair enough :) this was a motivated offer of help rather than an attempt to belittle the challenge

> Currently our attempts at fetching things are spread between CSSOM (for top-level stylesheet; currently broken and not invoking the Fetch algos correctly) and Cascade (for @import; currently being written by me in an attempt to use the Fetch algos correctly but definitely currently broken too).
> 
> I _suspect_ that url() usage in _properties_ should generally be quite easy; there's a _lot_ less observable behavior we have to worry about, but there's still _some_ piping of document state thru stylesheets that probably needs to be done in CSSOM. Values & Units is indeed the appropriate place to define the _general_ handling of url() tho; PRs absolutely welcome.

They’re coming, be warned. 😉 
Will probably have a multi-spec PR with some open issues in the next couple of days

**Comment by noamr** [comment]
@tabatkins I believe this can be closed.
