### ISSUE TITLE
[css overflow-clip-margin] What does overflow-clip-margin impact?

### ISSUE THREAD

**Issue by sky2** [w3c/csswg-drafts#5620]
Hello,
I'm in the process of implementing overflow-clip-margin in chrome and a question has come up as to what overflow-clip-margin applies to. Does it only impact the paint effects of the box itself? What about child paint effects and child spill out?

**Comment by sky2** [comment]
We are planning on doing the following:
1. box decorations of overflow:clip element remain as-is and are not clipped in presence of overflow-clip-margin
2. area of descendants exposed by overflow-clip-margin contribute to layout overflow of ancestor

**Comment by tabatkins** [comment]
overflow-clip-margin doesn't affect anything on its own; it just expands the [overflow clip box](https://drafts.csswg.org/css-overflow-3/#overflow-clip-edge), which is used by `overflow: clip` and `contain: paint`.

Those latter properties define how they interact with paint and geometry.
