### ISSUE TITLE
[css-grid-1] Raw bikeshed markup is present in grid chapter 11.3

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#5626]
Chapter 11.3 ( https://drafts.csswg.org/css-grid-1/#algo-track-sizing ) currently has a 5-step listing, with step 5 showing up in the HTML as:
```
[[#algo-stretch|Expand Stretched auto Tracks]]
```

That looks like bikeshed markup that didn't get interpreted properly (maybe due to a typo somewhere).

**Comment by dholbert** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/426803/96171413-b9090400-0ed9-11eb-869d-8cb8e5f19150.png)

**Comment by Loirooriol** [comment]
Regressed in 0f7451779854492c1c47a3dab29f5688075190e9. I guess bikeshed is getting confused by the `<css>auto</css>`?

**Comment by tabatkins** [comment]
Yes, this is a [known issue](https://github.com/tabatkins/bikeshed/issues/832) that I have code almost complete to fix; I'll try and prioritize wrapping it up.

**Comment by tabatkins** [comment]
No need for edits on Grid's side, I've fixed the Bikeshed issue. I'll push the fix tomorrow, as I need to file a few fix-PRs on some specs that'll get broken by the fix. ^_^
