### ISSUE TITLE
[cssom] [mediaqueries] Media query serialization doesn't work for newer spec features

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5627]
I recently became confused because WebKit / Blink sorted the media features in media query lists, but @lilles [did point out](https://bugs.chromium.org/p/chromium/issues/detail?id=1138859) to me that https://drafts.csswg.org/cssom/#serialize-a-media-query does say that:

> 5. Sort the media features in lexicographical order.

But this has gone very out of date with newer mediaqueries features (like nested expressions, etc), which for now only Gecko supports. This also gets more interesting when we support the multi-value expression syntax in https://github.com/w3c/csswg-drafts/issues/2791...

Gecko has never implemented the sorting step, so I'd propose to drop it: we don't know of any compat issue due to that, it was just that I was looking at interop around `MediaQueryList` as a result of a Gecko bug. Also, Gecko's behavior is more intuitive to me but maybe I'm biased :)

If we don't drop it, we need to define how the sorting works for stuff like nested expressions and such. Basically, we'd need to define sorting among two arbitrary `<media-condition>`s.

Thoughts?

**Comment by lilles** [comment]
Drop sorting. I can't imagine anyone relying on non-interoperable re-ordering of media query expressions (famous last words).

Blink also currently removes duplicates, which isn't part of the algorithm, but is indicated by an example in the spec. We should remove that too.

**Comment by tabatkins** [comment]
Yup, we should just preserve the expression as-is.

I'll go fix the example that shows off deduplication.
