### ISSUE TITLE
Define "descriptor" and "property" somewhere

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#5633]
As far as I can tell, we don't actually `<dfn>` "descriptor" or "property" anywhere. We touch on this in Syntax, § 5 Parsing, defining [declaration](https://drafts.csswg.org/css-syntax-3/#declaration):

> Declarations are further categorized as "properties" or "descriptors", with the former typically appearing in qualified rules and the latter appearing in at-rules. (This categorization does not occur at the Syntax level; instead, it is a product of where the declaration appears, and is defined by the respective specifications defining the given rule.)

It's come to my attention that some people who've been around for browsers for a long time don't understand the difference here, and we don't really ever make this super clear.

Looking at CSS Fonts for example: the only explicit clue between https://drafts.csswg.org/css-fonts/#font-family-prop and https://drafts.csswg.org/css-fonts/#font-family-desc is the titles of each section. We say the latter is "For: `@font-face`", but that's about it, and what exactly "For" means isn't totally clear.

This ends up relevant in places like CSSOM where we talk about "supported CSS properties" but it doesn't cross-reference anything for what a property is!

**Comment by svgeesus** [comment]
_Mea culpa, mea maxima culpa._

The specification which introduced the term "descriptor" used it a tone of times and never once defined it.

[Web Fonts
W3C Working Draft 21-July-1997](https://www.w3.org/TR/WD-font-970721#fontdesc)

But hey, [CSS1 was pretty hazy about properties](https://www.w3.org/TR/REC-CSS1-961217#css1-properties) too:

> Style sheets influence the presentation of documents by assigning values to style properties. This section lists the defined style properties, and their corresponding list of possible values, of CSS1.

**Comment by svgeesus** [comment]
This is something I tend to need to cover when presenting about webfonts.

* [Properties & descriptors](https://www.w3.org/Talks/2017/font-level-up/#propvsdesc-code) by example
* [Properties & descriptors](https://www.w3.org/Talks/2017/font-level-up/#propvsdesc) by definition

**Comment by fantasai** [comment]
Ok, we've added dfns for property and descriptor and also improved the definition of declaration (and defined 'property declaration' and 'descriptor declaration') in https://github.com/w3c/csswg-drafts/commit/be5e75b6cd2ab613d5085183067c739c1d295c0e
