### ISSUE TITLE
Move -webkit- prefixed aliases into flexbox?

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#5634]
https://compat.spec.whatwg.org currently defines a whole load aliases for flexbox which are implemented across all major browsers today. It would be nice to move these into the main flexbox spec, rather than have them defined elsewhere.

Specifically, the following should be [legacy name aliases](https://drafts.csswg.org/css-cascade/#legacy-name-alias):

* -webkit-align-content
* -webkit-align-items
* -webkit-align-self
* -webkit-flex
* -webkit-flex-basis
* -webkit-flex-direction
* -webkit-flex-flow
* -webkit-flex-grow
* -webkit-flex-shrink
* -webkit-flex-wrap
* -webkit-justify-content
* -webkit-order

(Note that this issue is _not_ about the older -webkit-box-* properties, where behaviour does differ from the modern spec in all browsers.)

**Comment by fantasai** [comment]
I'd be OK with putting these into an appendix of the Flexbox spec as a UAs MAY and authors SHOULD NOT or something.

**Comment by gsnedders** [comment]
CSS UI 4 makes them a must-level requirement:

> For compatibility with legacy content, UAs that support user-select must also support -webkit-user-select as an alias.
and
> For compatibility with legacy content, UAs must also support -webkit-appearance as a legacy name alias of appearance.

CSS Overflow 3 does likewise:

> For compatibility with legacy content, UAs that support line-clamp must also support the -webkit-line-clamp property.

**Comment by fantasai** [comment]
Note: Obsolete legacy (standard!) stuff for SVG is marked as optional in CSS Writing Modes, fwiw: https://www.w3.org/TR/css-writing-modes-3/#svg-writing-mode

**Comment by tabatkins** [comment]
On the other hand, the obsolete SVG values for `image-rendering` are marked as MUST.

**Comment by bfgeek** [comment]
An example of only looking at a specific "set" of properties:
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cdiv%20style%3D%22display%3A%20-webkit-box%3B%22%3E%0A%20%20%3Cdiv%20style%3D%22-webkit-box-ordinal-group%3A%202%3B%22%3EA%3C%2Fdiv%3E%0A%20%20%3Cdiv%20style%3D%22order%3A%203%3B%22%3EB%3C%2Fdiv%3E%0A%3C%2Fdiv%3E

**Comment by gsnedders** [comment]
> @bfgeek: When you move this into flexbox make sure youd on't list as aliases, they're more complex then that. Compat spec was lying a bit there.

At least in WebKit, the -webkit-flex-* properties _are_ aliases. And as I said in the original issue here:

> (Note that this issue is not about the older -webkit-box-* properties, where behaviour does differ from the modern spec in all browsers.)

The -webkit-box-* properties definitely _aren't_ aliases, and the Compat spec is wrong there (see https://github.com/whatwg/compat/issues/87)
