### ISSUE TITLE
[CSS-Fonts] Need method to interpolate variable font settings

### ISSUE THREAD

**Issue by scottkellum** [w3c/csswg-drafts#5635]
There is currently no way to interpolate [font variation settings](https://drafts.csswg.org/css-fonts-4/#descdef-font-face-font-variation-settings) fluidly across widths (viewport or element widths). This is [expected behavior from many font authors](https://www.instagram.com/p/B81EnHGBtW3/) but is impossible to do in CSS.

This can not be done in `calc()` (via clamp or CSS locks) due to CSS unit typing as font variation settings require a type of &lt;number> and viewport units are incompatible &lt;length> typed.

## Proposals

- I would propose adding a way to bind viewport/element dimensions to animations, allowing people to interpolate properties across sizes. This is related to the [CSS Scroll Linked Animations](https://drafts.csswg.org/scroll-animations-1/#scrollable-animation-usecase) draft, but expands it to bind to width. This dramatically expands the scope of this issue, but allows interpolation of all properties across varying widths and enabling far more control around style changes across page and element scaling than media queries or element queries allow.
- Allow for some sort of unit logic in `calc()` that can re-type a value, although this seems kind of clumsy to me as it is limited in use cases, and the math has the potential to be concluded and cumbersome. Calc() functions are also shifted as the user’s base font size changes making it unreliable.

**Comment by litherum** [comment]
IIRC there's already an effort to be able to put a length in the denominator of a calc division, so you could do something like `100vh/1px` or something. That seems like the most natural solution for this.

**Comment by tabatkins** [comment]
Yeah, you can divide the unit away to get a raw number, which'll then type-check in calc(). Just requires UAs to finish implementing the calc() changes.

**Comment by scottkellum** [comment]
@litherum @tabatkins Is there a link to the calc() changes? Very curious how this will work with CSS unit types.

**Comment by svgeesus** [comment]
The relevant specification is [CSS Values & Units 4](https://drafts.csswg.org/css-values-4/#changes-recent). It is just a case of the implementations catching up to what is already specified.
