### ISSUE TITLE
[css-env-1] Add more examples to clarify the interaction of dual-screen env variables with scrolling and zooming

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#5636]
The changes proposed in #5622 talk about layout, but not scrolling and zooming. I'd like more clarity on how scrolling and zooming work in these dual-screen contexts, either with more example, or more text.

**Comment by dlibby-** [comment]
Addressed by adding description/images in a reply to 5622. PTAL, thanks!
