### ISSUE TITLE
[css-cascade] ignoring @charset (editorial nit, I18N)

### ISSUE THREAD

**Issue by aphillips** [w3c/csswg-drafts#5637]
2.1. Conditional @import Rules
https://www.w3.org/TR/css-cascade-3/#at-import

> Any @import rules must precede all other valid at-rules and style rules in a style sheet (ignoring @charset), or else the @import rule is invalid. 

The phrase "ignoring @charset" might be slightly confusing. Should it say "except @charset" or perhaps rephrase as:

> Any @import rules must preceded all other valid at-rules and style rules in a style sheet except for @charset...

**Comment by svgeesus** [comment]
> Any @import rules must preceded all other valid at-rules and style rules in a style sheet except for @charset...

That reads much better, to me.

Same text in [Cascade 4]https://www.w3.org/TR/css-cascade-4/#at-import) and [Cascade 5](https://drafts.csswg.org/css-cascade-5/#at-import)

**Comment by fantasai** [comment]
The wording was chosen because @charset is technically defined to not be an at-rule in css-syntax, so it's technically not an exception.

Propose to close no change. @aphillips Any further thoughts?

**Comment by aphillips** [comment]
No objection to closing. While `@charset` is technically not an at-rule, I still think my wording is clearer---but it's not a normative problem, just more difficult to understand.
