### ISSUE TITLE
[css-color-4] Update the system color pairings with the new system colors

### ISSUE THREAD

**Issue by andreubotella** [w3c/csswg-drafts#5639]
Issue #4924 added the new system colors `Mark`, `MarkText` and `ButtonBorder`, but it didn't update the system color pairings to include them. "`Mark` background with `MarkText` foreground" is an obvious addition, but the color combinations for `ButtonBorder` would need more than that.

If I'm reading "Understanding WCAG" correctly, the following adjacent color contrasts would be needed:
- A `ButtonFace` or `Field` background with a `ButtonBorder` border and adjacent color `Canvas`.
- A `Canvas` background with a `ButtonBorder` border and adjacent color `Canvas` (since it was mentioned in #4924 that `ButtonBorder` could also be used for styling `<hr />` elements).

And `Highlight` and `Mark` might also be added as alternatives to `Canvas` for those contrasts.

**Comment by svgeesus** [comment]
Thanks for the report, now fixed
