### ISSUE TITLE
[css-inline] use an initial letter which has a descender in 3.6. Space Around Initial Letters

### ISSUE THREAD

**Issue by chenpighead** [w3c/csswg-drafts#564]
From the [spec.](https://drafts.csswg.org/css-inline/#initial-letter-exclusions), we'd like to see an initial letter should not  crash into other texts if the initial letter has a descender. However, the example is using a initial letter with capital "J", which has no descender. We might want to use a more accurate letter (maybe a lowercase letter?) to do the explanation.

**Comment by dauwhe** [comment]
In this font, the capital "J" extends far below the alphabetic baseline. I thought this would be a more realistic example than a lowercase letter that also extended well below the baseline, as lowercase letters are seldom used as initial letters. But as these aren't technically descenders, I'll edit the text, and perhaps adding a more explicit indication of the baseline would make the illustration more clear.

**Comment by dauwhe** [comment]
I've added a visual indication of the baseline in Figure 8, as well as adding text to the caption to clarify the letter extends well below the baseline. Fixed via 9657e7d.
