### ISSUE TITLE
[css-color] chapter 9.1 is not needed

### ISSUE THREAD

**Issue by cabanier** [w3c/csswg-drafts#565]
https://drafts.csswg.org/css-color/#gray-to-rgb

The spec already defines how to map from lab.
Spec should also be cleaned up so it's clear what transformations are needed and at what point they execute.

**Comment by svgeesus** [comment]
That section is needed, at least the first step!
I would be fine with condensing the remaining steps to a reference to the Lab section, but it seemed clearer to simply list them.

**Comment by cabanier** [comment]
It seems that section 9 already lists what to do.
I also noticed that our authoring applications has a different conversion from gray to Lab. I can look into what formula we're using if you want.

**Comment by svgeesus** [comment]
it does, but the other sections have an explicit list of steps so it seems better for consistency to have them here too.

No, I don't particularly want devicegray or anything like that. Tab had a whole pile of code in earlier drafts, trying to work out a hueristic for making nice gray ramps. All that went away as unneeded once the WG decided to treat gray as an alias for L, so I don't want to change that now.
