### ISSUE TITLE
[css-sizing] add fill(<length-percentage>) / rename stretch keyword for width/height?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5650]
Was reading some of the discussions on dialog styling, where one of the issues was trying to max-size something to fit the viewport minus margin/border/padding. Using calc() doesn't play with the cascade very well, but the `stretch` keyword (previously `fill-available`) does. However it only fills the containing block: if you want to fill to a different size, you can't.

I was wondering if we wanted to introduce a `fill()` function similar to `fit-content()` (and maybe rename `stretch` back to `fill` for consistency if it hasn't been implemented anywhere)?

That would allow things like `max-height: fill(100vh)` regardless of where you are in the document.

**Comment by Loirooriol** [comment]
I think it would be good to keep `stretch` for consistency with https://drafts.csswg.org/css-align/#valdef-justify-self-stretch
This new function could be called `stretch()` too.

**Comment by chrishtr** [comment]
Hi could you give an example where this new function would be used?
