### ISSUE TITLE
[scroll-animations-1] Order of pause, setTimeline

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5653]
With `@scroll-timeline` it's possible to switch the timeline and pause the animation at the "same" time. E.g. you can toggle a class like: `.switch { animation-timeline: other; animation-play-state: paused; }`.

During setTimeline, we don't expect the current time to change if the animation is paused [[1]](https://github.com/w3c/csswg-drafts/pull/5423#discussion_r470261956), but we _do_ expect the current time to "reset" if the animation is playing, hence it matters which order we do things in:

- If we pause first, then set the timeline, the current time will not be updated until we resume, and we'll be paused on the old timeline.
- If we set the timeline first, then pause, the current time is updated right away, and we'll be paused on the new timeline.

Note a huge deal I think, we just need to specify what should happen.

cc @kevers-google @ogerchikov

**Comment by flackr** [comment]
As a developer I think I would expect to set the timeline first, then pause, as the pause being applied in the same update as the new animation-timeline implies to me that it is meant to pause in the new timeline.

**Comment by BorisChiou** [comment]
In Gecko, we set the timeline first, and then handle play state. I also prefer to setting the timeline first.

**Comment by fantasai** [comment]
Updated in https://github.com/w3c/csswg-drafts/commit/214aa298df040e89ed54200486e725ca85b9c8bc to say:

> When multiple 'animation-*' properties are set simultaneously, 'animation-timeline' is updated first, so e.g. a change to 'animation-play-state' applies to the simultaneously-applied timeline specified in 'animation-timeline'.

@flackr @andruud Let me know if this works for you.

**Comment by graouts** [comment]
The relevant WPT test is being updated in https://github.com/web-platform-tests/wpt/pull/51098.
