### ISSUE TITLE
[cssom] Color properties should use "used value" as "resolved value"

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#566]
In the new CSS Color spec, computed value of `<color>` could be either a numeric color or `currentcolor` keyword. However, color properties currently always return numeric color value, and web content may depend on that behavior. I think we should probably make those properties use "used value" as "resolved value" for `getComputedStyle`.

**Comment by upsuper** [comment]
Also that matches behavior of browsers which have implemented computed-value time `currentcolor` keyword.

**Comment by frivoal** [comment]
Agenda+ because https://github.com/w3c/csswg-test/pull/1161 is blocked by this.

**Comment by tabatkins** [comment]
WG resolved to accept this.

**Comment by svgeesus** [comment]
also clarified on call, no impact of this change on css3-color or css4-color.

**Comment by frivoal** [comment]
The WG resolved (ah!) in favor of making `<color>` properties use used values as resolved values.

@therealglazou @zcorpan I think you guys are the editors, can you do the update?
