### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5662]
The new version of the pubrules checker (updated to cope with the Sept 2020 Process update) gave a warning when I was checking [CSS Highlight API](https://www.w3.org/TR/2020/WD-css-highlight-api-1-20201022/):

> Please make sure the expressions in document are neutral, "master" found in document. Check W3C Manual of Style for more information.

This relates to https://github.com/w3c/idcg/issues/17

So is it time we just renamed the `master` branch to `main`? Because it wasn't really language used in the spec; it was the name of the GitHub branch.

**Comment by plinss** [comment]
I'm supportive of this change.

When it happens, please coordinate with me as the draft server needs to be updated to serve the correct branch.

We should also do the fxtf and houdini branches at the same time.

**Comment by tabatkins** [comment]
Yup, been wanting to do this for a while, just haven't gotten the energy to do it.

**Comment by svgeesus** [comment]
If people have committed but un-pushed edits to `master` is there a chance that they accidentally get pushed to `master` and don't show up on `main`? I don't want anyone to lose edits.

**Comment by frunkad** [comment]
GitHub is making it easier for repositories to switch to main later this year. (https://github.com/github/renaming)

Thought I had chip in 😅

**Comment by svgeesus** [comment]
OK so how do we move this forward? On all the CSS repos:

-    w3c/css-a11y
-    w3c/css-houdini-drafts
-    w3c/csswg-apiclient
-    w3c/csswg-drafts
-    w3c/csswg-www
-    w3c/fxtf-drafts

**Comment by astearns** [comment]
I expect nothing was depending on the default css-a11y branch name, so I changed it just now.

@rachelandrew is there any reason not to rename the default branch in csswg-www immediately?

For the rest, I assume we need to coordinate with @plinss. Should we set up a time that would work for you Peter? How much work on the draft server is needed for this change?

**Comment by plinss** [comment]
It's just a config setting which branch to serve as the default. Switch away and ping me when it's done, only takes a minute on my end.

**Comment by astearns** [comment]
OK, I have renamed the default branch for the *-drafts and apiclient repos. So please update the config @plinss

**Comment by plinss** [comment]
Done

**Comment by xfq** [comment]
Can we close this issue now?
