### ISSUE TITLE
[css-flexbox] Should definite cross size be used to compute flex item's transferred size suggestion?

### ISSUE THREAD

**Issue by aethanyc** [w3c/csswg-drafts#5663]
As @davidsgrogan noticed in [this comment](https://github.com/web-platform-tests/wpt/pull/26250#issuecomment-716387767), for transferred size, the spec says:

> If the item has a preferred aspect ratio and its computed cross size property is definite

In [9.8](https://drafts.csswg.org/css-flexbox-1/#definite), the definite rule says:

    the outer cross size of any stretched flex items ... is considered definite.

Should the stretched definite cross size be used in computing transferred size?  Or in other words, should the transferred size defined as **If the item has a preferred aspect ratio and a definite cross size, then ...**? (similar to the flex algo [3B](https://drafts.csswg.org/css-flexbox-1/#algo-main-item) where a definite cross size is used to compute flex base size)

Consider [the following example](https://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8622):
```
<div style="display:flex; width:0; height: 50px;">
  <img style="" src="https://placehold.it/300x100" >
</div>
```
It's obvious that the image has no specified size suggestion and the content size suggestion is 300px. Currently Firefox Nightly gives the image 150px width as it does use definite cross size and aspect-ratio to compute to transferred size. Chrome and Safari gives the image 300px width. (I guess both implementations think the image has no transferred size.) 

cc @tabatkins @dholbert

**Comment by davidsgrogan** [comment]
I think Chrome matches the spec here[1] but firefox's behavior is better[2], so we should change the wording of [transferred size suggestion](https://drafts.csswg.org/css-flexbox-1/#transferred-size-suggestion) from

> If the item has a preferred aspect ratio and its **computed cross size property is definite**

to something like

> If the item has a preferred aspect ratio and its **outer cross size is definite**

Which matches the wording in 9.8 and makes clear that items with definite sizes imposed by the 9.8 rule qualify for the transferred size suggestion.

[1] The _computed cross size property_ in the example above is not definite, which means there is no transferred size suggestion.

[2] Because Chrome's behavior in https://jsfiddle.net/dgrogan/jd76er1y/ is gross. One image has its aspect ratio respected but the other confusingly doesn't. In Firefox both images have their aspect ratio respected.

**Comment by tabatkins** [comment]
Okay, <https://github.com/w3c/csswg-drafts/commit/0c1a35dd5d938c9d6e5d11cd144f5f45c4460d4a> fixes up the terminology to hopefully make this clearer; at the time we wrote the min-auto section of the spec, we didn't have terminology like "preferred size" defined, so we had to refer directly to the properties; I recall us finding that awkward but not having a better option at the time.

Is it clear that if one of the preferred sizes for a box is definite, the rest are too, so long as they're calculated by fixed values? Like if the outer size is definite, and margin/border/padding are all definite values, that the inner size will be definite as well?

**Comment by tabatkins** [comment]
(We aligned Grid with this same terminology as well, and took some time to make sure the two texts were as parallel as possible; some tiny discrepancies had come in accidentally.)

**Comment by tabatkins** [comment]
(Posting on behalf of @fantasai, whose internet just broke)

> I'm pretty sure our intent was that Firefox's behavior is correct. The difference in terminology is largely because we didn't have such specific sizing terms at the time Flexbox was drafted. :) We've checked in changes to align the terminology. Let us know if this seems to resolve the issue, or if there's more to sort out.
[Agenda+ to confirm changes with the CSSWG.]

**Comment by davidsgrogan** [comment]
Thanks, this all looks good, I'd call it resolved.

> Is it clear that if one of the preferred sizes for a box is definite, the rest are too, so long as they're calculated by fixed values? Like if the outer size is definite, and margin/border/padding are all definite values, that the inner size will be definite as well?

Yep, that makes sense.

**Comment by aethanyc** [comment]
The edited spec looks good to me.

**Comment by davidsgrogan** [comment]
The wpt test landed for this in http://wpt.live/css/css-flexbox/flex-aspect-ratio-img-row-013.html. Tomorrow's chrome canary will pass it.
