### ISSUE TITLE
[css-color-4] Minimum bit depth for serializing color() values.

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5667]
As a first step, [I said that 8 bits is the minimum for RGB and CMYK spaces](https://drafts.csswg.org/css-color-4/Overview.html#serializing-color-function-values). Much commercial software uses 8bits for CMYK, and the entire Web is on 8bit sRGB currently. The wider the gamut, the more bits are needed to avoid banding. If values are stored in linear-light you also need more bits compared to a gamma-encoded or L* encoded space (because the steps are unevenly distributed, perceptually).

But:

 * 10 bits is better for P3 and a98rgb, to have the same spacing as 8bit sRGB
 * 10 is suboptimal for 2020 but allowed; 12 is recommended, The Rec BT.2020 standard _does not even allow 8_, what should we do here
 * prophoto-rgb really needs 16 due to the superwide gamut

For all of these, 16bit unsigned integer or half float is a more reliable and realistic storage format. So can we increase the minimum? Need implementer input here.

(Color.js uses JavaScript number, i.e. double precision float, for component value storage and calculation).

**Comment by svgeesus** [comment]
Agenda+ mainly to stimulate discussion, and feedback from implementers.

**Comment by svgeesus** [comment]
I understand that internally, Webkit is storing values in gamma-encoded display-p3 with a half-float encoding (and with values outside the range 0 to 1 allowed, I think, but not certain) @smfr  @grorg 

I understand from @tabatkins that Blink is considering using an internal representation of half-float, gamma-encodes, sRGB values; again with values outside the range 0 to 1 allowed.

I haven't heard what Gecko is considering but would love to know.

**Comment by smfr** [comment]
The way WebKit stores color values isn't necessarily the same as the pixel format used for drawing buffers.

In WebKit, non sRGB color values are stored as float[4]. Drawing buffers might be non-clamped 8-bit, 10-bit, or half-float depending on the platform.

**Comment by svgeesus** [comment]
How can 8 or 10 bit be non-clamped?

**Comment by svgeesus** [comment]
> In WebKit, non sRGB color values are stored as float[4]. 

OK so whatever we decide regarding minimum bit depth for serialization, Webkit would comfortably meet it

**Comment by svgeesus** [comment]
> astearns: Sounded like people are okay with spec something here

I [added a table of minimum bit depths for round-tripping](https://github.com/w3c/csswg-drafts/commit/b90ecde35a58c6e7499fe9cd6883239b21df0a50)
