### ISSUE TITLE
[css-sizing-4][css-contain-2] Revisiting auto-sizing when size-containment applies

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#5668]
The [`content-visibility: auto`](https://www.w3.org/TR/css-contain-2/#content-visibility) value causes the user agent to apply [size-containment](https://www.w3.org/TR/css-contain-2/#containment-size) under certain conditions (generally, when content is outside of the viewport)

There is also another property that was added, [`contain-intrinsic-size`](https://www.w3.org/TR/css-sizing-4/#intrinsic-size-override), which helps with adoption of `content-visibility: auto`. It allows the developer to specify a "placeholder" size when size-containment is present. 

One undesired effect of content-visibility: auto is that the scrollbar thumb tends to jump around when content enters and exits the visibility region. This is due to the fact that we keep adding and removing size containment in order for us to optimize rendering of skipped content. The contain-intrinsic-size property helps, but the size still keeps changing between the "real" intrinsic size and `contain-intrinsic-size` placeholder. The two sizes are frequently different.

My proposal is that we consider adding another value for `contain-intrinsic-size`, which would use known intrinsic size _at the time size containment was last added_, with a fallback value if size containment was present before the initial layout of the contents. It would basically freeze the intrinsic size when containment is added and use that.

The syntax would be something like the following:
`contain-intrinsic-size: auto 0 auto 100px`
which would mean:
* If size containment was present before the initial layout of the contents, then this is the same as `contain-intrinsic-size: 0 100px`
* If size containment was added after the initial layout of contents, then this is the same as the intrinsic size of contents at the time that size containment was last added

For context, this is similar to a previous proposal, which was rejected: https://github.com/w3c/csswg-drafts/issues/1043.
I think this proposal is sufficiently different in that we already have the "use this (intrinsic) size when size containment is present" property. The addition is just to prefer using the real intrinsic size if it is available at the time size containment applies.

One con of the approach is that the timing of when to measure intrinsic size isn't clear. When size containment applies, we should read off the last computed intrinsic size. However, this value could be different depending on when the UA decides to update the intrinsic size. So this may cause some observable implementation differences.

**Comment by cbiesinger** [comment]
Hmm, it seems like it will be very tricky to get interop on this one, depending how it's specified.

**Comment by vmpstr** [comment]
Putting this on the agenda mostly to gather feedback about the general direction: Can we have something that 'remembers' the size when size-containment applies

**Comment by dholbert** [comment]
Yeah, I'm uneasy about this... If I'm understanding the proposal correctly, it sounds like it introduces a new bit of non-determinism, or at least a dependency on the exact sequence of events (and the timing of layouts) in a way that feels like it goes against how CSS usually works.

**Comment by tabatkins** [comment]
I think it introduces no more non-determinism or dependency than animations already introduce, yeah? An animation's start time, and thus its effect on the page at any given moment, depends on when the animation style started applying, which seems identical to the case here.

**Comment by tabatkins** [comment]
All right, first draft of the `c-i-s: auto` behavior is in the spec. Whenever ResizeObserver would look for size changes, it records the sizes of c-i-s:auto elements, and c-i-s:auto then uses that size.

Lmk if this looks good? I'm especially uncertain of how to phrase the timing for the ResizeObserver reference.

**Comment by vmpstr** [comment]
I left a couple of comments. Please let me know if you prefer to have the discussion in this issue instead, for posterity

**Comment by tabatkins** [comment]
Unless it's a very specific nitpick of a line in the comment, I generally prefer comments to go in the issue, as it's easier to keep track of them.

------

**[@vmpstr said:](https://github.com/w3c/csswg-drafts/commit/16aad72a7c438e6a98a399cca0161a82d6f3a2c0#r46759280)**
> The problem here is for an optimization that content-visibility: auto provides to be effective, we need to ensure that we can skip layout of the contents as soon as we render the element.

You're right; I misremembered what content-visibility:auto did, and thought it applied size containment, meaning we *had* to get an experimental layout in anyway (and at that point, might as well do it early for all cases). But nope, an element with *skipped contents* gets size containment; once an "auto" element is not skipped, it lays out without size containment (assuming nothing else is applying it, of course).

So yeah, I definitely could just wait for that layout to happen and start recording the size *then*; before that (while it's skipped), it just doesn't have a remembered size.

--------

Question: should it forget its last remembered size if it loses `contain-intrinsic-size:auto`? I presume we don't want to record this information for *all elements all the time*, so the restriction to only do the recording when c-i-s:auto is on makes sense, but is it better to forget the size when c-i-s:auto no longer applies, or remember it permanently from then on (even tho it won't be used until you set c-i-s:auto again)?

The way the spec is currently written, once an element records a size it keeps it forever, but I'm happy to make it forget (presumably with the same timing?).

**Comment by vmpstr** [comment]
It makes sense for us to forget the size. 

I'm thinking from the perspective of an element that has neither size containment nor contiain-intrinsic-size. In this case, it seems wasteful to remember any type of size because nothing really applies here. However, I can then apply size containment, wait a bit, and apply contain-intrinsic-size: auto. I think it's fair to say that we use a placeholder size in that case, _not_ the remembered size. If you agree with that line of reasoning, then I think that generalizes to us forgetting the value once contain-intrinsic-size: auto is removed.

I'm unfamiliar with the details of the CSS timings, but I'd like to point out a case like "remove contain-intrinsic-size: auto. and then add it in the same function without any forced style in between". Here, we would probably not forget the value, right? And if there was a forced style in between, we would forget the value?

**Comment by tabatkins** [comment]
> If you agree with that line of reasoning, then I think that generalizes to us forgetting the value once contain-intrinsic-size: auto is removed.

Yup, agreed.

> I'm unfamiliar with the details of the CSS timings, but I'd like to point out a case like "remove contain-intrinsic-size: auto. and then add it in the same function without any forced style in between". Here, we would probably not forget the value, right? And if there was a forced style in between, we would forget the value?

Yes, since we resolved that recording the size happened at the time resizeobservers are fired, I'm planning on making the forgetting happen at the same time. So if you really want to make sure it's forgotten, you may have to wait a frame.

**Comment by vmpstr** [comment]
Gotcha, this sounds good to me! Thanks
