### ISSUE TITLE
Old versions on drafts.w3.org

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5672]
I notice that the [ED of CSS Color 4](https://drafts.csswg.org/css-color-4/) is Editor’s Draft, 21 October 2020, which is missing [20 or so commits from yesterday](https://github.com/w3c/csswg-drafts/commits/master/css-color-4/Overview.bs).

Anyone else seeing old versions? The bikeshed icon doesn't indicate any problem, and says that  it was last run

> Last Bikeshed run at 2020-10-28 00:30:42 PDT

which is after those commits.

Shift-reload doesn't produce any change.The HTTP last modified date is Wednesday, 28 October, 2020, 09:30:42

**Comment by plinss** [comment]
Fixed. This was caused by branches getting out of sync between the git repo and the mercurial repo and mercurial was thinking the wrong branch was master.

**Comment by svgeesus** [comment]
Thanks, @plinss !!
