### ISSUE TITLE
[selectors-4] Text of the "Compound selector" definition misses the Pseudo-elements part

### ISSUE THREAD

**Issue by SelenIT** [w3c/csswg-drafts#5676]
Currently, the [formal grammar](https://drafts.csswg.org/selectors-4/#typedef-compound-selector) of the Compound selector is

```
<compound-selector> = [ <type-selector>? <subclass-selector>*
                        [ <pseudo-element-selector> <pseudo-class-selector>* ]* ]!
```
i.e. pseudo-elements (possibly pseudo-classed) can be part of Compound selector.

However, [the definition of Compound selector](https://drafts.csswg.org/selectors-4/#compound) in prose states that

> A **compound selector** is a sequence of simple selectors that are not separated by a combinator, and represents a set of simultaneous conditions on a single _element_.

and the formal grammar of the simple selector excluded pseudo-elements (since the resolution of #386). (As a side note, the current formal grammar seems to imply that the "bare" pseudo-element, like `::before`, technically falls under the Compound selector definition.)

Shouldn't the text of the Compound selector definition be amended somehow to make it more clear that pseudo-elements also belong to it?

**Comment by Loirooriol** [comment]
I guess this is basically the issue at the end of that section:

> ISSUE 1 - Pseudo-elements aren’t handled here, and should be.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/80e9be7590682b23f1ff568b212836612852a219 and https://github.com/w3c/csswg-drafts/commit/ae832ae12bf12c90815e6e3a3e879c8da8dcd99d

Compound selectors still don't include pseudo-elements, but we added a new term “pseudo-element compound” to address that and integrated it into the definition of complex selectors.

**Comment by Loirooriol** [comment]
> A complex selector is a sequence of one or more compound selectors and/or pseudo-compound selectors
separated by combinators.

So `div::before` and `::before::marker` are not complex selectors since the compound/pseudo-compound selectors are not separated by combinators?

**Comment by tabatkins** [comment]
No, they're complex selectors. The text is just written in a slightly ambiguous way, because precisely reflecting the grammar into English would be very fiddly and it's not necessary, since the grammar is the part that's normative.

**Comment by Loirooriol** [comment]
The text is still normative. It's fine if the text is looser than the grammar, but if it's stricter then it's adding additional constraints. So I would change to:

> A complex selector is a sequence of one or more [compound selectors](https://drafts.csswg.org/selectors-4/#compound) and/or [pseudo-compound selectors](https://drafts.csswg.org/selectors-4/#pseudo-compound)**<ins>, possibly</ins>** separated by [combinators](https://drafts.csswg.org/selectors-4/#selector-combinator).

**Comment by tabatkins** [comment]
All right, ended up rewriting the complex selector section a bit, and tweaking pseudo-compound as well.
