### ISSUE TITLE
[selectors] What is the reasoning for ignoring defaullt namespaces only on the subject for :is() / :where() / :not()?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5684]
`:is()` / `:where()` / `:not()` have this sentence in them:

> Default namespace declarations do not affect the compound selector representing the subject of any selector within a :is() pseudo-class, unless that compound selector contains an explicit universal selector or type selector.

I kinda get why that may be useful for `:not()` and why you _might_ want it only on the rightmost compound. Though the behavior for `:is()` / `:where()` is a bit weirder, I feel like it'd be better to ignore the default namespace in the whole inner selector...

Or at least I don't see why you might want that behavior on `:is()` / `:where()`... And it'd be nice to make all three consistent (I don't have a strong opinion on the subject vs. whole selector for `:not()`, though it's better if they're implemented the same).

cc @andruud @tabatkins

**Comment by emilio** [comment]
I guess the idea is that the default namespace for the compound has already been applied to the left of the `:is` effectively?

**Comment by emilio** [comment]
For `:not`, it seems a bit weird because you're negating the default namespace, so I can see someone saying `:not(.foo > .bar)` to want `.foo` to include or not include the default namespace...

**Comment by tabatkins** [comment]
> I guess the idea is that the default namespace for the compound has already been applied to the left of the :is effectively?

Correct. The general intuition is that, given a selector `AB`, replacing that with `A:is(B, C)` should match all the same elements, and possibly more. If that line wasn't there, then going from `svg|a:hover` to `svg|a:is(:hover, :focus)` would cause the selector to stop matching anything at all when a non-SVG default namespace was in effect.

Same argument for the other combo pseudo-classes; they're all intended to be useful as syntax sugar, and ignoring the default namespace as specified is required for that to work intuitively.

(Hm, the same argument probably applies for `:nth-child()`; going from `AB` to `A:nth-child(n of B)` shouldn't reduce the number of matched elements. We should fix that.)

**Comment by tabatkins** [comment]
And, uh, apologies for missing this three years ago, it had a very simple answer.

**Comment by Loirooriol** [comment]
I think it can be confusing that the meaning changes depending on the context. Wouldn't it have been better to just drop
> If a [default namespace](https://drafts.csswg.org/css-namespaces-3/#default-namespace) is declared, [compound selectors](https://drafts.csswg.org/selectors/#compound) without [type selectors](https://drafts.csswg.org/selectors/#type-selector) in them still only match elements in that default namespace.

Authors could use an explicit `*` to restrict to the default namespace if they wanted.

Possibly not web-compatible to change now, but I think default namespaces aren't actually used that much...

**Comment by tabatkins** [comment]
Sure, changing that behavior would probably be better, but making a backwards-incompatible change was larger than what we wanted to do. If we think it's reasonable, tho, I'm fine with it.

**Comment by Loirooriol** [comment]
BTW, this is implemented buggy in WebKit:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<style>
/*<![CDATA[*/
@namespace url("http://example.com/foo");
@namespace svg url("http://www.w3.org/2000/svg");
svg|svg { background: cyan }
svg|svg:is(:hover, :focus) { background: green }
/*]]>*/
</style> 
<svg tabindex="-1" id="svg" width="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"></svg>
</html>
```

The default namespace prevents `:hover` from matching, but `:focus` can match. It's the opposite for `:is(:focus, :hover)`.
