### ISSUE TITLE
[css-counter-styles] Clarify how @counter-style name lookup works with shadow DOM

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#5693]
1. How should @counter-style rules defined in shadow DOM work. The current spec totally ignores it and says

> Defining a @counter-style makes it available to the entire document in which it is included.

The current behavior (available in Firefox only) is:
- @counter-style defined in the main document is available to the entire document
- @counter-style defined in shadow DOM is ignored ([bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1672302)). This is due to #1995 

The spec should probably be revised to match the proposal in #1995 

---

2. How do `extends` system and `fallback` descriptor search for the correct rule with shadow DOM?

This is more complicated. If we have a @counter-style rule in a stylesheet that is reused by multiple shadow DOMs, where does it search for the rule to extend or fallback? Obviously we can't just search within the same stylesheet, while searching the entire document and ignoring scoping also seems wrong.

The proposal in #1995 doesn't work, either, because a @counter-style rule isn't associated with any tree scope when defined. And it may be reused by multiple tree scopes.

Note: The situation is similar to @property. We currently don't allow @property in shadow DOMs but it's likely to change (https://github.com/w3c/css-houdini-drafts/issues/939)

**Comment by xiaochengh** [comment]
Here's a proposal based on [CSS-SCOPING-1](https://drafts.csswg.org/css-scoping/#shadow-names), and compatible with Firefox's behavior that a global `@counter-style` rule can be access within a shadow tree.

As specified in [CSS-SCOPING-1](https://drafts.csswg.org/css-scoping/#shadow-names):
- Each `@counter-style` rule defines a **tree-scoped name**
- Each counter style name reference defines a **tree-scoped reference**. This includes:
  * `system: extends` and `fallback` descriptors
  * `list-style-type` property
  * `counter()` and `counters()` functions in `content` property

To dereference a tree-scoped reference, we first look for names within the same tree scope; If there's no match, we recursively walk up to the parent tree scope and search until a matching name is found.

Note that the current spec of CSS-SCOPING-1 only searches the same tree scope, which makes @counter-style defined in the main document inaccessible from shadow trees.

**Comment by tabatkins** [comment]
Yeah, it should work exactly the same way as for @font-face, aka "not remotely defined right now, but I have a years-old proposal for fixing it that I need *someone* to sign off on implementing".

**Comment by tabatkins** [comment]
The current spec in Scoping *intentionally* doesn't walk up the tree, to better increase encapsulation, but I suppose it makes sense that these refs can "inherit" down into shadows. I suspect it better matches the mishmash of behavior for scoped references browsers currently have, anyway; at least, I think "you can always use the stuff from the top-level doc" is pretty common among them.

I'll go adjust Scoping to match that, and then explicitly ref it here.

**Comment by fantasai** [comment]
Agenda+ to review fix with the CSSWG.
