### ISSUE TITLE
[css-conditional-3]: Inconsistent phrasing around placement of @import rules

### ISSUE THREAD

**Issue by jyasskin** [w3c/csswg-drafts#5697]
https://drafts.csswg.org/css-conditional-3/#contents-of talks about `@import` being disallowed inside conditional rules, but doesn't use the same **must** language as https://drafts.csswg.org/css-conditional-3/#use. Unless there's something I'm missing about CSS editorial style, these should probably be consistent.

https://drafts.csswg.org/css-conditional-3/#use is phrased as restricting where `@import` rules can appear, but if that were actually its purpose, it ought to repeat or be unified with the restriction from https://drafts.csswg.org/css-conditional-3/#contents-of that `@import` and friends can't appear inside a conditional rule. But I think it's actually specifying that conditional rules must not appear *before* `@import` and friends. If that's your intent, it might be clearer to say it that way.

**Comment by svgeesus** [comment]
> https://drafts.csswg.org/css-conditional-3/#contents-of talks about @import being disallowed inside conditional rules, but doesn't use the same must language as https://drafts.csswg.org/css-conditional-3/#use. Unless there's something I'm missing about CSS editorial style, these should probably be consistent.

That is because it is inside an example.

The normative statement is the [definition of &lt;stylesheet>](https://drafts.csswg.org/css-syntax-3/#typedef-stylesheet).

The further explanation says that

> they can accept any rule that is normally allowed at the top-level of a stylesheet, and _not otherwise restricted_

There is then an example of something (`@import`) which _is_ further restricted. Examples are not normative. Although, this particular example uses the word MUST which is bad practice and should be reworded.

**Comment by svgeesus** [comment]
The normative definition restricting `@import` is in [CSS Cascade 5](https://drafts.csswg.org/css-cascade-5/#at-ruledef-import)

**Comment by svgeesus** [comment]
@jyasskin does that explanation make sense? If so we can close the issue; but if not, I have Agenda+ the issue for the next CSS telcon (9 Dec). Might you be able to join the call, in that case? It is 12 noon US East Coast.

**Comment by jyasskin** [comment]
I hadn't read "Any `@import` rules must precede all other valid at-rules and style rules in a style sheet (ignoring `@charset`)" from https://drafts.csswg.org/css-cascade-5/#at-import. It's not totally obvious that a "style sheet", used there, is a different thing from a `<stylesheet>`, used as the content of the at-rules, but also seems clear enough that I'm happy to close that part of the issue.

I think my second paragraph, about https://drafts.csswg.org/css-conditional-3/#use, is less resolved.
Having read that bit of css-cascade, I now think that the second paragraph of https://drafts.csswg.org/css-conditional-3/#use is redundant with it since [the conditional rules are at-rules](https://drafts.csswg.org/css-conditional-3/#processing), and "Any `@import` rules must precede all other valid at-rules". [`@namespace`](https://drafts.csswg.org/css-namespaces-3/#syntax) has similar wording in its spec. [`@charset`](https://drafts.csswg.org/css-syntax-3/#charset-rule) is unique and ... not actually a rule anymore ... but already defined not to follow anything else. If there are rules that are only restricted relative to style rules but not at-rules, this paragraph would still have an effect, but it could then benefit from a different set of examples. Maybe replace it with a note?

I'm happy to dial into the 9 Dec telecon.

**Comment by svgeesus** [comment]
Thanks @jyasskin.

@astearns @atanassov would it be possible to have this early on the agenda, so that @jyasskin doesn't need to call in for the whole hour? 

CSS Conditional 3 is now [in the queue for updated CR](https://github.com/w3c/transitions/issues/291) so I would like to get any edits arising from this issue cleared up before it is published.

**Comment by jyasskin** [comment]
I'm happy to dial in for the whole meeting. I should know more about the CSSWG anyway. :)

**Comment by fantasai** [comment]
This seems editorial, I'm not sure it warrants telecon time? I agree with both comments in https://github.com/w3c/csswg-drafts/issues/5697#issuecomment-736914928 and I think we can just fix it. That said, happy for @jyasskin to attend a CSSWG call either way. :)

**Comment by fantasai** [comment]
OK, rewrote https://drafts.csswg.org/css-conditional-3/#use @jyasskin Lmk if it seems acceptable!

Wrt “style sheet” vs `<stylesheet>`, I actually think it is worth fixing, and that we should fix that by changing `<stylesheet>` to some other name to avoid this confusion.

**Comment by jyasskin** [comment]
That looks good, thanks! Do you want to keep this issue open for the `<stylesheet>`->something else change or track that in a better-named issue?
