### ISSUE TITLE
[css-contain-2] content-visibility should not be animatable

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#5708]
[`content-visibility`](https://www.w3.org/TR/css-contain-2/#content-visibility) is specified as discretely animatable. `contain` on the other hand is specified as not animatable. Since `content-visiblity` values change the type of containment values applied, I think it makes sense for `content-visibility` to not be animatable as well.

I also don't know any specific use-cases that would be solved by letting `content-visibility` be animatable.

**Comment by chrishtr** [comment]
Agreed, let's make it non-animatable
