### ISSUE TITLE
[css-2021] Consider adding Transforms 2?

### ISSUE THREAD

**Issue by rolivo288** [w3c/csswg-drafts#5714]
CSS transform level 2 has been implemented in most browsers for quite some time even ie ( https://caniuse.com/transforms3d ) besides being widely used. Could it be marked as stable in CSS Snapshot 2020?

**Comment by Loirooriol** [comment]
Seems https://drafts.csswg.org/css-transforms-2/#individual-transforms is only implemented in Firefox?

**Comment by rolivo288** [comment]
> Seems https://drafts.csswg.org/css-transforms-2/#individual-transforms is only implemented in Firefox?

@Loirooriol  You are correct at the moment the translate, scale, and rotate properties are only implemented in firefox, however at least in chrome it is intended to implement them. On the other hand, the rest of the properties have been implemented for a long time and are widely used, so the rest of the properties could not be added as safe features in https://drafts.csswg.org/css-2020/#CR-exceptions ?

**Comment by svgeesus** [comment]
@Loirooriol 

> Seems https://drafts.csswg.org/css-transforms-2/#individual-transforms is only implemented in Firefox?

Right, which makes the [Chrome status "no signals from Firefox"](https://chromestatus.com/features/5705698193178624) somewhat baffling.

**Comment by fantasai** [comment]
OK, well, we discussed and decided not for 2020. :) Maybe 2021.
