### ISSUE TITLE
[cssom] getComputedStyle can return null?

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#572]
Related to
https://github.com/w3c/csswg-drafts/issues/571
and maybe
https://github.com/w3c/csswg-drafts/issues/219

In Gecko, the following alerts null

```
<!DOCTYPE html>
<iframe style=display:none srcdoc="<style>body{background:blue}</style>x"></iframe>
<script>
onload = () => {
alert(window[0].getComputedStyle(window[0].document.body))
}
</script>
```

In WebKit/Chromium/Edge 13 it alerts [object CSSStyleDeclaration].

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4543

cc @bzbarsky

**Comment by bzbarsky** [comment]
I consider this a bug in Gecko (which causes web compat problems) that I'm trying to fix.  The work on fixing it is where the investigation that led to https://github.com/whatwg/html/issues/1813 came from.

**Comment by zcorpan** [comment]
Thanks!
