### ISSUE TITLE
[css-sizing-3] Mention css-wiriting-mode spec in terminology section explicitly

### ISSUE THREAD

**Issue by himorin** [w3c/csswg-drafts#5725]
coming from i18n review (https://github.com/w3c/i18n-request/issues/133#issuecomment-725195691) for 
https://www.w3.org/TR/2020/WD-css-sizing-3-20201023/, but this is a suggestion and not a part of change request.

In section 2. terminology, words referring (as term-ref link) `css-writing-modes-4` are used, such as block size or inline size, and also listed in `Terms defined by reference` section, but no explicit wording of `css-writing-modes` there.
It could be better for readers to have some text like `CSS Writing Modes’ Abstract Box Terminology` (clipped from css-logical, introduction section) in section 2. terminology.

**Comment by fantasai** [comment]
@himorin Thanks for the comment! We've added a reference to Writing Modes, let us know if this addresses your issue or if you have any suggestions for improvement!

**Comment by himorin** [comment]
Thank you for update in 53127dd, and I believe text got clearer!
