### ISSUE TITLE
[css-transforms] rotate should clearly specify that it is clockwise

### ISSUE THREAD

**Issue by Lorp** [w3c/csswg-drafts#5726]
The [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) specification should state explicitly that it is a clockwise rotation.

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-transforms/#funcdef-transform-rotate already says

> specifies a 2D rotation by the angle specified in the parameter about the origin of the element, as defined by the transform-origin property. For example, rotate(90deg) would cause elements to appear rotated one-quarter of a turn **in the clockwise direction**.

**Comment by Lorp** [comment]
Thanks. I was actually thinking about the MDN documentation. I suggest that the section on Rotation in [MDN: \<transform-function\>](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function) would benefit from rotation direction being specified.

**Comment by Loirooriol** [comment]
Ah, then, MDN is a wiki open to collaboration, so you can edit the article yourself if you want to improve it. Anyways this is not the proper place to discuss about MDN, so I'm closing the issue if you think the actual spec is fine.
