### ISSUE TITLE
[css-values-4] Clarify that function component values need to be followed by parentheses

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#5728]
In https://drafts.csswg.org/css-values-4/#component-types the different component value types are defined.

And Function definitions are mostly specified separetely from where they are used, so they are referenced by non-terminal values like `<image()>` in https://drafts.csswg.org/css-images-4/#image-values.

So far, there is no note in the specification how the names of those values should look like. This causes some confusion like in https://github.com/w3c/fxtf-drafts/issues/410.

In order to clarify that and make it consistent across specifications, I suggest to formalize that the names of those values need to be followed by an opening and a closing parenthesis.

Sebastian

**Comment by Loirooriol** [comment]
So for example in https://drafts.csswg.org/css-grid/#repeat-syntax, you would rename `<track-repeat>`, `<auto-repeat>`, `<fixed-repeat>`, `<name-repeat>` to `<track-repeat()>`, `<auto-repeat()>`, `<fixed-repeat()>`, `<name-repeat()>`?

What if you have a disjunction of different function values, like in [`<transform-function>`](https://drafts.csswg.org/css-transforms/#typedef-transform-function)? Should it be `<transform-function()>`?

**Comment by SebastianZ** [comment]
Yes, or do it the other way round and don't allow parentheses within those names. The point here is to have a clear definition for how they should look like to get consistency.

Sebastian

**Comment by tabatkins** [comment]
Note that switching all our `<url>` references to `<url()>` would be *absolutely wrong*, since `src()` is another `<url>` value.

**Comment by tabatkins** [comment]
Added definitions of `<foo()>` and `<@foo>` to the appropriate specs. Since you approved the plan before the CSSWG resolution, I'm assuming satisfied; lmk if there are any issues otherwise.
