### ISSUE TITLE
[css-pseudo] Privacy considerations for external resources

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#5731]
The  privacy and security section [1] talks about reading out computed style for ::spelling-error and ::grammar-error being a privacy issue.

1. I propose to add that loading external resources should be blocked. The currently allowed external resources are cursors, I think.

Consider:

```
<style>
  span::spelling-error { cursor: url(leakinfo), wait }
</style>
<span>WordInPersonalDictionary</span>
```

2. Add the ::target-text pseudo element to the list in that section

[1] https://drafts.csswg.org/css-pseudo-4/#highlight-security

**Comment by ByteEater-pl** [comment]
Just load it anyway, even if there are no errors initially.

**Comment by hober** [comment]
We should probably treat these like `:visited`.

**Comment by lilles** [comment]
> We should probably treat these like `:visited`.

Yes, but unlike :visited it's not a problem to expose the styles via getComputedStyle() or computedStyleMap since the values from getComputedStyle(span, "::spelling-error") do not depend on whether there is a spelling error or not in the span.

**Comment by ArthurSonzogni** [comment]
Within  ::spelling-error and ::grammar-error, the CSS property 'cursor' with the url(..) value would give a way to exfiltrate user's dictionnary.
I agree this value should be removed/ignored.

You said data-url might be an allowed exception. Are we sure there are no ways to know a data-url request was made?
1. Resource timing API: I did some local testing and also asked Yoav Weiss. Those are excluded.
2. Service worker: I believe from memory those are never allowed to serve a data-url.
3. The new performance.measureMemory(): It's a bit far fetched, but I guess some inference seems possible. Displaying the image would consume some memory.

Being able to customize the cursor for grammar errors seems a niche use case. Removing this shouldn't hurt, right?

**Comment by schenney-chromium** [comment]
Only a limited number of properties are allowed inside ::spelling and other highlight pseudos, and none of those properties can load external resources. Closing this issue as resolved. https://drafts.csswg.org/css-pseudo-4/#highlight-styling
