### ISSUE TITLE
[css-cascade][Editorial] Why list the global values for `all`?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#5740]
https://drafts.csswg.org/css-cascade/#all-shorthand

> Value: initial | inherit | unset | revert

These keywords are valid in every other CSS property, yet we don’t list them explicitly. Why should `all` be an exception? This means that if we add another global keyword, we need to remember to add it here too, and old versions of the spec will be out of sync.

I'd propose changing it to: 

> Value: (Only global values)

or

> Value: (nothing)

or something along these lines and explain in the prose.

Also, we should avoid using "global keywords" in the value, as we may introduce some kind of global value that is not a keyword in the future.

**Comment by tabatkins** [comment]
We did so just to make the allowed values obvious and locally-defined.  I don't have a strong opinion either way, but I do like having it be easy to see all the global keywords near `all`'s definition.

**Comment by LeaVerou** [comment]
I certainly see the usability benefit of having all keywords there, but I also see the maintainability drawback of duplicating information. No strong opinion either.

**Comment by fantasai** [comment]
@LeaVerou They're both defined in the same spec, so I'm in favor of the usability benefit of making them explicit. If at some point we end up defining lots of global values in lots of places and it becomes a maintenance problem, we can change it then.
