### ISSUE TITLE
The Grand Unification Proposal

### ISSUE THREAD

**Issue by bencemeszaros** [w3c/csswg-drafts#5743]
Hello Everyone,

My name is Ben and I am a first time contributor on this platform. I have been working with web technologies for five years now and have developed a few websites with many different tools but during my work I always felt frustrated with how the three major web technologies, HTML, CSS and JavaScript were designed and how they performed. Two years ago with the help of my small team and a few friends we began analyzing them in detail to find out why. Throughout this process we have discovered that there are several underlying problems with the structure of these languages that were especially apparent when they were performing together. We have collected our findings in a master document and also formulated a proposal in response that I would like to share with all of you.

What I am about to propose might sound at first extreme, crazy or even outrageous that might upset some people or come off as arrogant, ignorant or even offensive. This is not my intent whatsoever. I recognize all of your hard work, time and dedication and I do not mean to criticize or hurt anyone. My sole objective is to give an unbiased and overall assessment from a practical standpoint. My intent is to make web technologies better by pointing out long standing conceptual issues and propose a solution that could resolve them in order to enable the web to thrive in the future and in the long run. My concept is complex, but as a whole, it is straightforward and logical. For this reason please take the time to consider all of my angles and suggestions together, without judging individual parts that might sound radical or unusual. If you feel that I have made an error, this is not the place for this discussion or have any other feedback feel free to let me know here or in email and I will be more than happy to act accordingly.

Thank you,
Ben

The Grand Unification of Web Technologies

Abstract
After 30 years, developers are still struggling to build websites efficiently. Our hypothesis is that this is due to severe and acute design flaws in HTML, CSS and the architecture of the web. To test this, we have analyzed HTML, CSS and JavaScript together, focusing on their collective capabilities and joint performance especially when creating a website. We have found that JavaScript vastly outperforms HTML and CSS in every way, it is advanced enough to build entire websites without any help from HTML and CSS, and that these websites are far more versatile and organic than their conventional counterparts. We have found that consequently, using HTML (and markup languages in general) as the backbone of any website is an obsolete concept that blocks innovation and fundamentally limits current and future web capabilities and developments. We have also found that building visible layouts with markup languages and CSS is inherently impossible without programming principles such as functions, variables or conditions, but also discovered that CSS has already begun to mimic some of these principles although in a makeshift manner. We have found many further redundancies and inconsistencies between the three main languages and within HTML and CSS that further obstruct and unnecessarily complicate the workflow of millions of website developers and therefore harm billions of users worldwide as well. Our analysis concluded that further development of HTML and CSS in their current forms is ill-advised and instead their tasks should be merged with JavaScript and should continue their evolution there. The results of our analysis and the basic principles of this proposed unified system can be found in this document. Our primary goal with this document is to draw the attention of the developers of all major browser engines, Blink, WebKit and Gecko and invite them and anyone else interested to share their opinions about this proposal and the idea of a new, unified open web standard built around JavaScript.

The rest of the document can be found here: https://docs.google.com/document/d/1Ys-2Pb6PUVl8-5BMhM770trKNp_DmGrfskDlp-L_WSs/edit?usp=sharing

**Comment by tabatkins** [comment]
This is not an appropriate venue to discuss replacing the entire web tech stack.
