### ISSUE TITLE
[css-position] What is the behavior of an absolutely-positioned <br>?

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#5749]
https://drafts.csswg.org/css-position/#position-property is clear that position applies to the `<br>` element, and that "the box is taken out of flow such that it has no impact on the size or position of its siblings and ancestors, and does not participate in its parent’s formatting context." It also say "A position value of absolute or fixed blockifies the box and causes float to compute to none."

This implies that the `<br>` should not trigger a line break here:
```
text
<br style="position: absolute;">
here
```

However, WebKit and Blink both trigger a line break. Gecko does not.

**Comment by smfr** [comment]
Similar story with `float`:
```
text
<br style="float: left;">
here
```

**Comment by fantasai** [comment]
@smfr I agree with Gecko here fwiw. Having it continue to trigger a line break would make `<BR>` behave rather differently from any other out-of-flow.

**Comment by fantasai** [comment]
Agenda+ to suggest closing no change.

**Comment by smfr** [comment]
WebKit bug: webkit.org/b/230048
