### ISSUE TITLE
[css-box-4] margin-trim or trim-margin

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#5750]
In September the group resolved to rename `ledding-trim` to `trim-ledding`.
https://lists.w3.org/Archives/Public/www-style/2020Sep/0001.html

This makes me wonder if `margin-trim` gets the same facelift.
https://drafts.csswg.org/css-box-4/#margin-trim

**Comment by fantasai** [comment]
That was subsequently rename to `text-box-trim`; so closing as no longer relevant. :)

(Also, it's nice to keep all the margin-related properties sorting together.)
