### ISSUE TITLE
[css-highlight-api] Should the HighlightsRegister be renamed to HighlightsRegistry

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#5760]
https://www.w3.org/TR/css-highlight-api-1/#highlightsregister

An object that you register things on is a "registry". The list of registered objects is a "register". I think in this use case, "registry" makes more sense.

Prior art: ServiceWorkerRegistration, RTCIdentityProviderRegistrar, CustomElementRegistry

**Comment by frivoal** [comment]
Works for me. As far as I know, the only implementation is the one [in safari](https://developer.apple.com/safari/technology-preview/release-notes/#r99), so if you don't mind changing, I see no downside.

**Comment by dandclark** [comment]
This sounds like a good change, I agree that we should align with these other API names.

**Comment by dandclark** [comment]
Hmm, looking again at the prior art pointed out by @smfr I wonder if the plural should also be removed, making it `HighlightRegistry`.  I don't have a good semantic argument for or against this change but it would align with these other APIs, e.g. the current API is *not* named CustomElement<i>s</i>Registry.

**Comment by sanketj** [comment]
+1 for HighlightRegistry

**Comment by sanketj** [comment]
+1 for changing the name to `HighlightRegistry` (assuming Safari implementors don't have any concern with making this update)
