### ISSUE TITLE
[css-fonts-3] Consider marking @font-feature-values at risk

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#577]
As far as I know, Firefox is the only browser which implements this at-rule.

**Comment by jpamental** [comment]
Is there a reason why this wouldn't be implemented? Seems like if we want to get away from having to use `font-feature-settings` isn't this the right way to do it?

**Comment by litherum** [comment]
The criteria for at-risk has nothing to do with how useful something is. It only has to do with the status of its implementation. If you think it shouldn't be at-risk, you should petition browser vendors to implement it.
