### ISSUE TITLE
[css-highlight-api] i18n self review

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5771]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    It does not.
    
2. [x] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    It does not introduce any new typographical capabilities. It does allow applying a restricted subset of CSS's usual features to arbitrary ranges within the document. No i18n related issue is though to arise from that, and in any case, this merely builds up on built-in highlight pseudos as found in https://drafts.csswg.org/css-pseudo-4/#highlight-pseudos. Should there be any issue (and I don't think there is), they likely stem from that underlying technology rather than from this extension of it.

3. [X] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    It does not.

    However, it allows the *author* to do point to text fragments. It uses the pre-existing [Range object](https://dom.spec.whatwg.org/#range) from the DOM specification for that. Authors should be careful when doing so to avoid accidentally putting fragment boundaries in the middle of grapheme clusters. The Range object allows for that, but admittedly does not facilitate it. If it would be deemed useful to give authors advice about careful usage of the Range object to avoid getting into difficult i18n situations, it would seem more appropriate to include that advice in the upstream DOM specification.

4. [X] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    It does not.

5. [X] _If the spec (or its implementation) sorts text_

    It does not.

6. [X] _If the spec (or its implementation) captures user input_

    It does not.

7. [X] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    It does not.

8. [X] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    It does not.

9. [X] _If the spec (or its implementation) defines markup._

    It does not.

10. [X] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    It does not.

11. [X] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    It does not.

12. [X] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    It does not.

**Comment by sanketj** [comment]
@frivoal Do you know what is left for us to complete the i18n review for css-highlight-api-1? This is one of the only remaining issues against css-highlight-api-1.

**Comment by frivoal** [comment]
This was filed for the FPWD review. as far as that goes, we should consider it complete. We are expected to send another review request/notification prior to entering CR, but as comparatively little changed between the two, it should be a mostly a formality.

**Comment by aphillips** [comment]
Thanks for this self-review!

Note about this item:

>> If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc.
> It does not.
> However, it allows the author to do point to text fragments. It uses the pre-existing [Range object](https://dom.spec.whatwg.org/#range) from the DOM specification for that. Authors should be careful when doing so to avoid accidentally putting fragment boundaries in the middle of grapheme clusters. The Range object allows for that, but admittedly does not facilitate it. If it would be deemed useful to give authors advice about careful usage of the Range object to avoid getting into difficult i18n situations, it would seem more appropriate to include that advice in the upstream DOM specification.

It's a little narrow to view "user" in our checklist only as the _end-user_, since authors are likely to be the "users" of this feature. :-)

I believe we have commented about Range objects and the I18N challenges that emanate from the DOM Range in the past. It is probably a good idea to provide a health warning about about these types of issues, even if we "take it up" with the DOM spec, although I note that the API can't really *do* anything about these issues.

Some thought might be given to providing examples (or linking to them in the I18N space) for bidi considerations and also for doing things like highlighting a combining mark or base character...

**Comment by aphillips** [comment]
PS> You don't have to wait to request an I18N review--in fact we strongly encourage getting your I18N review done before entering CR. We don't charge extra if you end up needing a second review...

**Comment by sanketj** [comment]
> I believe we have commented about Range objects and the I18N challenges that emanate from the DOM Range in the past.
@aphillips Were these challenges called out in a Github issue? If you could share a link to the thread, that would be great.

I acknowledge the internationalization challenges called out, but these are all challenges with DOM ranges themselves and thus also manifest for users/authors who use ranges independent of the highlight API. We could consider adding some normative text to the [DOM range spec](https://dom.spec.whatwg.org/#ranges), but the spec hasn't changed in this aspect for years so it's unclear how useful adding such a warning now would be.

**Comment by sanketj** [comment]
@aphillips Thanks for the clarification. I've published a PR to add a warning to the highlight API: #8647. PTAL.

I've also filed an issue against the range spec in case there is interest in adding a more general warning there.

**Comment by sanketj** [comment]
The issue of adding a warning to the DOM range spec is tracked here: https://github.com/whatwg/dom/issues/933.

**Comment by sanketj** [comment]
@aphillips Do you think we can complete this i18n review since we have added the warning to the spec?

**Comment by sanketj** [comment]
@aphillips Sounds good. We'll plan to send out the formal i18n review before we go to CR. I don't anticipate significant changes that will impact i18n between now and then but will keep you posted if there are. Thanks for the help and review!
