### ISSUE TITLE
[css-syntax] <stylesheet> grammar construct should be named differently since it's not a "style sheet"

### ISSUE THREAD

**Issue by jyasskin** [w3c/csswg-drafts#5774]
As discussed in https://github.com/w3c/csswg-drafts/issues/5697#issuecomment-736914928, "`@import` rules must precede all other valid at-rules and style rules in a ***style sheet***" ([[css-cascade]](https://drafts.csswg.org/css-cascade-5/#at-import)), but that's not the same "style sheet" as is spelled "`<stylesheet>`" and appears inside things like the [conditional at-rules](https://drafts.csswg.org/css-conditional-3/#at-supports). This isn't a terrible problem, but it's also a bit confusing.

@fantasai [suggested](https://github.com/w3c/csswg-drafts/issues/5697#issuecomment-741884022) the right fix is to rename [`<stylesheet>`](https://drafts.csswg.org/css-syntax-3/#typedef-stylesheet). The telecon discussion suggested to explicitly ask @tabatkins if they object.

**Comment by tabatkins** [comment]
I don't object, just not sure what new name to use, since `<stylesheet>` means "anything allowed in a stylesheet (except those are only allowed in a top-level context, like `@import`)".

**Comment by svgeesus** [comment]
`<stylesheet-body>` perhaps, and the part where `@import` etc live could be `<stylesheet-head>` and thus, a stylesheet is  `<stylesheet-head>` `<stylesheet-body>`

**Comment by fantasai** [comment]
I was going to suggest `<styleset>` but @svgeesus’s suggestion is a nice idea. Do we allow @font-face and @keyframes inside conditional rules yet, though? Because if not then there's a top-level vs. encased distinction rather than a header vs. body distinction.

**Comment by tabatkins** [comment]
After discussing with @fantasai we decided that `<stylesheet-body>` makes the most sense, even if we don't use any sort of *-head production. (I'm just personally not a fan of "styleset".)

We'll defer actually making the change until January, since virtually all of the specs currently using it are pending publication currently, and will go up before a new Syntax /TR will. We'll just do some editorial repubs for all of them later once Syntax gets republished.

**Comment by tabatkins** [comment]
I ended up making this moot with the new Syntax text, since I changed all the productions anyway. Nothing is named `<stylesheet>` anymore. (Things that previously used it now just use `<rule-list>`.)
