### ISSUE TITLE
[selectors] :autofill pseudo-class

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5775]
See https://github.com/whatwg/html/issues/6181 for the reasons why I think we should add this pseudo-class.

I think this is mostly uncontroversial, is there any reason people would think this is a bad idea / bad naming?

**Comment by Loirooriol** [comment]
Can you clarify what exactly it matches? Like if an `<input>` is autofilled, and then the user changes the value, does it still match?

**Comment by emilio** [comment]
That is to-be-defined in https://github.com/whatwg/html/issues/6181, but it shouldn't match when the user edits the value. All browsers agree on that.

**Comment by Loirooriol** [comment]
css-pseudo is for pseudo-elements, this is a pseudo-class, so I guess it would be in selectors?

**Comment by heycam** [comment]
Would we also require that UA styling of autofilled form fields be done in CSS so that the author can override them?

**Comment by frivoal** [comment]
No strong objection to this, but just a note: I think we should consider whether there are privacy implications to this, and whether we should do anything to mitigate them. Whether a browser autofills something depends on whether a user as visited a site before or nor, whether the user has saved some information for that particular type of field or not, etc. This feels like a (small) source of information about the user, as well as a potential source of finger printing.

Admittedly, as @fantasai pointed out, sites can already infer that information by looking at whether forms field have been filled in withing less than 1 second of loading the site or something like that. At the same time, this would offer an easier way to access that information, which would work even when JS is turned off.

This is probably not a fatal flaw, but it seems worth considering.

**Comment by emilio** [comment]
I _think_ at least Gecko doesn't auto-fill without user action, which mitigates the fingerprinting risk here, AIUI.

**Comment by emilio** [comment]
Ok, I think the spec work here should be done in html. @frivoal do you need the issue open for the privacy tracker bits? Otherwise maybe we should close this.

**Comment by emilio** [comment]
Oh, I guess we do have duplicate definitions for a bunch of these pseudo-classes in html/selectors...

**Comment by yisibl** [comment]
After removing the prefix, can the user overwrite the browser's default style?
https://stackoverflow.com/questions/2338102/override-browser-form-filling-and-input-highlighting-with-html-css

**Comment by jdragonbae** [comment]
> I _think_ at least Gecko doesn't auto-fill without user action, which mitigates the fingerprinting risk here, AIUI.
@emilio: 
Hello, emilio.
I wonder the meaning of that Gecko doesn't auto-fill without user action. Could you let me know more detail about this one? The firefox version (88.0.1) seems to auto-fill without user action like Chromium.

**Comment by Iconejey** [comment]
I guess you are talking about styling inputs when the browser/user uses autocomplete, right? There already is a pseudo-class in CSS using `input:-webkit-autofill` but the code often gets ugly:

```css
input:-webkit-autofill {
  -webkit-text-fill-color: white;
  -webkit-box-shadow: 0 0 0 30px lightblue inset;
}
```

Having to deal with `-webkit-text-fill-color` and `-webkit-box-shadow` to change text and background colors is counter intuitive in addition to being hard to make it work on browsers like Chrome where you have to deal with the browser's default styling and make everything `!important`.

An `:autofill` pseudo-class in my opinion is a great idea if browsers allow us to do something like this:

```css
input:autofill {
  color: white;
  background-color: lightblue;
}
```

I found some [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill#:~:text=input%20%7B%0A%20%20border%3A%203px%20solid%20grey%3B%0A%20%20border-radius%3A%203px%3B%0A%7D%0A%0Ainput%3A-webkit-autofill%20%7B%0A%20%20border%3A%203px%20solid%20blue%3B%0A%7D%0Ainput%3Aautofill%20%7B%0A%20%20border%3A%203px%20solid%20blue%3B%0A%7D) on developer.mozilla.org with a code example using `:autofill` but I couldn't find when the article was published. I tried using it in Chrome 90.0.4430.212 but it didn't recognise it (neither did VS Code).

I truely hope this becomes standard soon.

**Comment by emilio** [comment]
> I wonder the meaning of that Gecko doesn't auto-fill without user action. Could you let me know more detail about this one? The firefox version (88.0.1) seems to auto-fill without user action like Chromium.

Can you elaborate? On Linux, on Nightly at least, what I see is that if I go to a page where I have credentials saved, I need to click on the `<input>` and then I get a dropdown with users which would autofill my user and password, like this:

![image](https://user-images.githubusercontent.com/1323194/120788758-fdace280-c530-11eb-90ba-b5503a7f6db9.png)

I can ask around to see if it's somehow different across platforms or settings though.

**Comment by emilio** [comment]
Ah, I got an answer back. Apparently we do autofill without user interaction, but:

 * Only if the origin matches exactly with the same domain (e.g., if you have a login for signup.amazon.com we won't autofill amazon.com, but we'll autocomplete).
 * Only in non-private browsing mode.

This is also user-configurable via `signon.autofillForms=false` (it's true by default).

**Comment by jdragonbae** [comment]
> Ah, I got an answer back. Apparently we do autofill without user interaction, but:
> 
> * Only if the origin matches exactly with the same domain (e.g., if you have a login for signup.amazon.com we won't autofill amazon.com, but we'll autocomplete).
> * Only in non-private browsing mode.
> 
> This is also user-configurable via `signon.autofillForms=false` (it's true by default).

Thanks for the details. Should we any further discussion on privacy issues? I think the `-webkit` prefix has the same issue.

**Comment by yisibl** [comment]
@emilio The default style of input:autofill in Firefox can cause errors in some page styles. Is there a similar problem in the newly implemented WebKit?

https://login.taobao.com/member/login.jhtml

https://user-images.githubusercontent.com/2784308/124411180-a04dc080-dd7e-11eb-8380-80ec3ca16d6f.mp4

**Comment by yisibl** [comment]
@Iconejey Yes, we now have to use a very hacky method to overwrite Chrome's default style, because `box-shadow: none` has no effect.

```css
input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0 1000px #fff inset;
    box-shadow: 0 0 0 1000px #fff inset;
}
```

**Comment by fantasai** [comment]
Edited in. @emilio Let me know if this definition is missing anything?

Also if we need to define :-webkit-autofill in the spec, please file an issue about it and let me know how the parsing should work (we don't have parse-time aliases in the Selectors spec yet afaict). :) Thanks~

**Comment by fantasai** [comment]
@emilio Nevermind, found https://github.com/w3c/csswg-drafts/issues/5847

**Comment by emilio** [comment]
@yisibl we don't use `filter` for autofill anymore, for what is worth.

@fantasai looks good, thanks!
