### ISSUE TITLE
[css-color-adjust] It's a bit unfortunate that user stylesheets can't specify arbitrary colors.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#5779]
I don't _think_ this is enough of an issue to revert the resolution of https://github.com/w3c/csswg-drafts/issues/4915, but I don't think it was discussed there so I wanted to raise it just in case there's any case we hadn't thought about.

One of the nice things of the `revert`-based forced-colors is that user and user-agent stylesheets worked as-is. We fixed UA stylesheets to use system colors where they weren't doing so, so that's covered, but user stylesheets won't be able to specify arbitrary colors anymore.

I think most of the use cases that I could think of for having arbitrary colors in a user sheet if you're using forced-colors are either minor, covered by system colors, or spec issues (#5778).

But there are probably other use cases which I might have missed (I know lots of extensions inject user stylesheets, for example...), so I think it'd be worth a look from other WG/community members just in case.

**Comment by tabatkins** [comment]
If they're targetting a specific thing, user stylesheets can use `forced-color-adjust: none` and then use whatever colors they want; if they're spamming colors generally across the page so that that's not appropriate, uh, wouldn't they just change their forced colors to match that preference, then?
