### ISSUE TITLE
[css-color-5] Interpolation of system color keywords

### ISSUE THREAD

**Issue by kbabbitt** [w3c/csswg-drafts#5780]
#3847 resolved that system color keywords should compute to themselves. There was a question left open regarding interpolation. There have been fragments of further discussion around this, but I haven't seen a formalized resolution, so I wanted to raise it as its own issue.

https://github.com/w3c/csswg-drafts/issues/3847#issuecomment-548097809 suggested that system colors should be treated the same as currentcolor: convert to a used value and interpolate based on that, per https://drafts.csswg.org/css-color-5/#interpolation:
> Interpolating to or from currentcolor is possible. The numerical value used for this purpose is the used value.

https://github.com/w3c/csswg-drafts/issues/5392#issue-672967371 suggested using color-mix() to interpolate between system color keywords. For example, if we're running an interpolation between the system color keywords `canvas` and `menu`, and the timing function just returned a value of 0.4, the interpolated value would be `color-mix(canvas 40%, menu)`.

Though the color-mix() suggestion was mine, I'm not particularly attached to it. The "resolve to used value" behavior seems less likely to introduce compat issues, and after implementing #3847 in Blink behind a flag, I discovered that it already had the "resolve to used value" behavior.

Either way, I'm hoping we can get the desired behavior covered in the spec. What does the working group think?

**Comment by emilio** [comment]
> https://github.com/w3c/csswg-drafts/issues/3847#issuecomment-548097809 that system colors should be treated the same as currentcolor: convert to a used value and interpolate based on that, per https://drafts.csswg.org/css-color-5/#interpolation

Hm? That's definitely not what Firefox does. What Firefox does for currentcolor is effectively `color-mix`: https://searchfox.org/mozilla-central/rev/4415bec7a49c50a338167d9c8934527b9cae59d0/servo/components/style/values/generics/color.rs#36-43

That is observable via inheritance. I guess inheritance is less of an issue for system color keywords though? cc @upsuper

**Comment by kbabbitt** [comment]
> Hm? That's definitely not what Firefox does. What Firefox does for currentcolor is effectively `color-mix`: https://searchfox.org/mozilla-central/rev/4415bec7a49c50a338167d9c8934527b9cae59d0/servo/components/style/values/generics/color.rs#36-43

Whoops, you're right. I should have tested this myself before commenting on it. Thanks for pointing it out.

**Comment by svgeesus** [comment]
@kbabbitt @emilio  so [in CSS Color 4] we still have:

> Interpolating to or from currentcolor is possible. The numerical value used for this purpose is the used value.
> https://drafts.csswg.org/css-color-4/#interpolation

followed by a link to #445 where I said:

> If there is only one special keyword, handling it isn't too bad. If we also need to consider the percentage of system colors, or add new functionality like currentBackground then this becomes rather more complex.

It sounds like, instead of the used values, the proposal is that the result of `color-mix() would need to be:

1. the percentage of all actual resolved colors
2. the percentage of `currentColor`
3. the percentage of `Canvas`
4. ...
19. the percentage of `GrayText`

This seems very complex and heavyweight. Do I understand the proposal correctly?

**Comment by tabatkins** [comment]
That's correct, tho most of those would be zero in anything but specially-constructed hostile examples.

**Comment by svgeesus** [comment]
> That's correct, tho most of those would be zero in anything but specially-constructed hostile examples.

So TypedOM would return a 19-element array, most of which is zeroes?

**Comment by emilio** [comment]
@svgeesus I agree that's extremely complex, and that's why I proposed doing https://github.com/w3c/csswg-drafts/issues/6773 (because there are other issues that solves too).

**Comment by svgeesus** [comment]
Right, and this also affects the long-running https://github.com/w3c/csswg-drafts/issues/445

We seem to have been kicking these related issues around for a while and I want to see them resolved one way of the other

**Comment by tabatkins** [comment]
> So TypedOM would return a 19-element array, most of which is zeroes?

No? It would, I assume, have a list of color/% pairs, as many as needed to represent the value. The abstract computed value doesn't have a 1:1 correspondence to what we serialize *or* reify.

(and it might simplify further, as Emilio said)

**Comment by svgeesus** [comment]
This is now a non-issue due to the resolution of

- https://github.com/w3c/csswg-drafts/issues/6773
