### ISSUE TITLE
A slip in the docs for "font-synthesis"? [css-fonts-4]

### ISSUE THREAD

**Issue by hugonteifeh** [w3c/csswg-drafts#5790]
Hey everyone 👋 !

Looking at the docs for [font-synthesis](https://www.w3.org/TR/2020/WD-css-fonts-4-20201117/#font-synthesis), I see that its value is `none | [ weight || style ]` yet its initial value is `weight style small-caps`. Where does `small-caps` come from?

**Comment by svgeesus** [comment]
hanks for the bug report! Yes, the value was [copied across from CSS Fonts 3](https://www.w3.org/TR/css-fonts-3/#font-synthesis-prop), which only covered weight and style, without noticing that a new [font-synthesis-small-caps](https://drafts.csswg.org/css-fonts-4/#font-synthesis-small-caps) longhand property had been added. So the shorthand needs to be updated.

**Comment by svgeesus** [comment]
Ok, [the draft is now updated](https://drafts.csswg.org/css-fonts-4/#font-synthesis)
