### ISSUE TITLE
[css-cascade] Do we need a keyword similar to `revert`, but for cascade layers?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5793]
Cascade Level 4 added the [`revert` keyword](https://drafts.csswg.org/css-cascade/#default) for rolling back values to their definition in the previous origin.

In the draft Cascade 5 specification we provide [cascade layers](https://drafts.csswg.org/css-cascade-5/#nested-layers), which are conceptually similar to origins – but controlled by authors. It might be helpful to provide a similar syntax for rolling back to the value defined in previous layers.

**Comment by fantasai** [comment]
We should make sure that the preshint rules are given their own layer so that this works to unwind author rules without affecting preshint mapping. See #5836.

**Comment by mirisuzanne** [comment]
In another conversation, @fantasai suggested `revert-layer` as the keyword – and that makes sense to me as an initial proposal. 

This would roll back the cascaded value of a declaration to the previous layer with a value specified, as if no current-layer rules were specified for this property on this element.

**Comment by fantasai** [comment]
Forgot to tag https://github.com/w3c/csswg-drafts/commit/23e8ba69714a7e3287fd829cac6efac20df7218f and https://github.com/w3c/csswg-drafts/commit/090abe4e68e0dde233fa02c33a11add766787be9 here. Anyway, that wraps up the edits, closing out.

**Comment by mirisuzanne** [comment]
I saw that the Chrome [intent to prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/chiJ2GIECPc/m/sIF9pfsdAAAJ) (from @xiaochengh) and [platform status](https://chromestatus.com/feature/5663362835808256) mention this as a part of the spec that they do not intend to implement, for complexity/performance reasons: 

> We will not implement the 'revert-layer' keyword due to its high complexity and likely negative performance impact.

I don't know if that's something we need to revisit in the spec, but I wanted to make sure that's documented here.
