### ISSUE TITLE
[css-overflow-3] Clarify when overflow-clip-margin has an effect

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#5800]
[overflow-clip-margin](https://drafts.csswg.org/css-overflow-3/#propdef-overflow-clip-margin) has some text when defining the value that reads as follows:

```
If the element does not have overflow: clip (or another property defined to
respect this property), this property has no effect.
```

I think it's ambiguous what `this` refers to when talking about another property:
Is this saying "another property that respects overflow: clip"
or "another property that respects overflow-clip-margin"

I think it's the latter. But in general, do we need this text? It seems like we can just define `overflow-clip-margin` as affecting `overflow clip edge` unconditionally. Then, if some property clips to `overflow clip edge` then it will be affected by `overflow-clip-margin`

For context, `contain: paint` is such a property that clips to `overflow clip edge`, and I think that it should be affected by `overflow-clip-margin`, but one can read it differently.

**Comment by vmpstr** [comment]
@fantasai just to clarify, we can't remove the sentence because there are properties that clip specifically to `overflow clip edge` but _don't_ respect `overflow-clip-margin`? Is there an example?

**Comment by dholbert** [comment]
Another nit about this spec snippet -- we should rephrase `(or another property...)`.

Expanding slightly, it's saying `If the element does not have...another property defined to...`  And this phrasing is problematic because, strictly speaking, every element *has* every property.  I think this means "a value of some other property that is defined to...." or something along those lines.

**Comment by tabatkins** [comment]
I moved the initial sentence down into a note - the property's sole effect is to modify the overflow clip edge, so it doesn't need to specify what properties *use* that edge to do something, but it's still worthwhile to point out the effects in a note.

Also rephrased it a bit to get around @dholbert's issue.
