### ISSUE TITLE
[css-overflow-3] Add box-edge values to overflow-clip-margin

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5801]
There's a lot of confusion documented in this bug https://bugs.chromium.org/p/chromium/issues/detail?id=99364 about how border-radius affects clipping. (It curves its own box edges, but it doesn't cause an element with `overflow: hidden` to start clipping its descendants to its content edge instead of its padding edge.)

The use case could be easily handled by adding keywords like `content-box`/`padding-box`/`border-box` to the new `overflow-clip-margin` property, though. They would set the zero position of the offset to that edge.

CC @laukstein

**Comment by smfr** [comment]
How does this interact with overflow:scroll? Does it affect the placement of scrollbars?

**Comment by fantasai** [comment]
@smfr The property doesn't apply to scroll containers, only `overflow: clip` and anything else defined to emulate it.
