### ISSUE TITLE
[css-align-3] A few typos in css-align-3

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#5802]
Reporting a few typos I ran across when re-reading css-align-3 today:

Typo 1:
[Appendix A: Static Position Terminology](https://drafts.csswg.org/css-align-3/#static-position-rectangle):
In the "Flex Layout" section, there's link that mentions grid but intends to mention flexbox (" See _static position of a **grid** container child_ in [CSS-FLEXBOX-1]. ")

s/grid/flex/ might fix this, but also, the linked text is actually pointing to a section whose name is "Absolutely-Positioned Flex Children", so maybe that's the phrase we should use here? (It seems like it's trying to quote a section title when saying "See $foo").  Either way seems fine to me.

Typo 2:
[6.1.2. Absolutely-Positioned Boxes](https://drafts.csswg.org/css-align-3/#justify-abspos) (for justify-self)
"The block’s containing block’s inline axis" -- this wants s/The block/The box/

**Comment by fantasai** [comment]
Fixed, thanks!!
