### ISSUE TITLE
[css-images] Clarify relationship between level 3 and 4

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/csswg-drafts#5804]
CSS Images 4 seems to be described as a superset of CSS Images 3:
> It includes and extends the functionality of CSS level 2 [CSS2] and in the previous level of this specification [css3-images].

Yet, it doesn't seem to be actually a superset, e.g. `object-position` is not included in level 4.

A specific illustration of this is that its list of terms defined by references includes 16 terms from Level 3: circle,  concrete object size,  contain constraint,  cover constraint,  default object size,  default sizing algorithm,  ellipse,  linear-gradient(),  natural aspect ratio,  natural dimension,  natural height,  natural size,  natural width,  object size negotiation,  object-position,  radial-gradient()

**Comment by LeaVerou** [comment]
Images 4 is a delta spec, it hasn't yet pulled in all of Images 3, it mainly includes the additions/differences.

**Comment by dontcallmedom** [comment]
thanks - it would be useful if that could be made explicit in the spec.

For instance, earlier versions of CSS Grid had the following language
> This level is currently maintained as a diff spec over the level 1 module

**Comment by svgeesus** [comment]
Yes, it is certainly worth it for Images 4 to say

1. that is is a delta
2. that not all of Images 3 has been folded in

I recall, earlier in the development of Fonts 4, that Mozilla engineers were removing an already-implemented feature "because it isn't in the latest spec". So avoiding that sort of miscommunication can be vital.

**Comment by tidoust** [comment]
If level 4 is a delta spec, shouldn't https://www.w3.org/TR/css-images/ target level 3? It currently returns level 4 (cc @deniak)

This would also make things consistent with the drafts CSS server, as https://drafts.csswg.org/css-images/ currently returns level 3.

**Comment by deniak** [comment]
> If level 4 is a delta spec, shouldn't https://www.w3.org/TR/css-images/ target level 3? It currently returns level 4 (cc @deniak)

@svgeesus @LeaVerou can you confirm the level 3 should be the "default" version?

**Comment by LeaVerou** [comment]
The thing is, it's mature enough that it really *shouldn't* be a delta spec. 
@tabatkins @fantasai Perhaps it's time to de-deltify it?

**Comment by fantasai** [comment]
Yeah, it's time to de-deltify.

@deniak I think Level 3 would be an acceptable default version for now, yes. I'll issue a request to update once we get an update ready.

**Comment by deniak** [comment]
Thanks for the confirmation. https://www.w3.org/TR/css-images/ now points to the level 3.
