### ISSUE TITLE
[css-contain-1] Minor editorial

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5806]
@frivoal  This wording

> 	Given than the effect on is identical, this allows implementations not to store the precise syntax through which this was achived

is a bit odd, and also has a typo (achived). The effect _on what?_ Also the avoidance of the split infinitive, although _theoretically_ correct, sounds clumsy.

Perhaps

> 	Given that the effect is identical, this allows implementations to not store the precise syntax through which this was achieved

**Comment by svgeesus** [comment]
(This is not a blocker for publication, just a suggestion)

**Comment by florian** [comment]
Wrong @ mention.

Can you please be more careful with this? This is the 5th I'm getting an email notification from you even though you intended to notify some other Florian.

**Comment by frivoal** [comment]
"on" looks like stray text, and should indeed be deleted. What's wrong with split infinitives? Sounds fine to me… But not being a native speaker, "sounds fine to me" isn't a very good guideline to go by.

**Comment by svgeesus** [comment]
Also "Given **than**" instead of "Given **that**".

**Comment by frivoal** [comment]
> Also "Given than" instead of "Given that".

Done.

**Comment by svgeesus** [comment]
OK, great!
