### ISSUE TITLE
[css-scoping] Proposal for light-dom scoping/namespacing with re-designed `@scope` rule

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#5809]
This would likely require additions to both [CSS Scoping](https://drafts.csswg.org/css-scoping/) and [CSS Cascade](https://drafts.csswg.org/css-cascade/). See my [full explainer](https://github.com/oddbird/css-sandbox/blob/main/src/scope/explainer.md) for more details.

As I've been working on proposals around cascade layers & component queries, there is another aspect of "cascade modernization" that comes up regularly: scope. I'm aware that there is some hesitancy on the issue, since the [initial specification][] was never implemented, and Shadow DOM was seen as a path forward (potentially a replacement). I think that time (and further development of Shadow-DOM) has helped clarify two quite different use-cases:

1. Total isolation of a DOM subtree/fragment from the host page, so that no selectors get in or out unless explicitly requested.
2. Lighter-touch component namespacing, and prioritization of "proximity" when resolving the cascade.

Shadow-DOM addresses the first, but it comes with a lot of overhead that is required for "full isolation". Meanwhile authors rely on convoluted naming conventions (like [BEM][]) and JS tooling (such as [CSS Modules][], [Styled Components][], & [Vue Scoped Styles][]) for the second use-case… which has been thoroughly discussed in various forms:

- [Bring Back Scope](https://github.com/w3c/csswg-drafts/issues/3547)
- [Selector Boundaries](https://github.com/w3c/csswg-drafts/issues/5057)
- [CSS Namespaces](https://github.com/w3c/csswg-drafts/issues/270)
 
[initial specification]: https://www.w3.org/TR/css-scoping-1/
[BEM]: http://getbem.com/
[CSS Modules]: https://github.com/css-modules/css-modules
[Styled Components]: https://styled-components.com/
[Vue Scoped Styles]: https://vue-loader.vuejs.org/guide/scoped-css.html

[Note: This doesn't attempt to resolve all the use-cases discussed in those threads. The discussion so far has often conflated the two approaches to scope, and I'm trying to divide them out. I think that still leaves a number of "isolation-first" cases that would best be addressed with changes that build on top of shadow-DOM - such as these ideas [explored by Yu Han](https://docs.google.com/document/d/1hhjmuQE6BTTnAyKP3spDr8sU6lpXArh8LDfihZh78hw/edit?usp=sharinghttps://docs.google.com/document/d/1hhjmuQE6BTTnAyKP3spDr8sU6lpXArh8LDfihZh78hw/edit?usp=sharing).]

### 1. Provide a "lower boundary" or "slot" syntax 

This would make it possible to scope fragments rather than entire DOM sub-trees. @giuseppeg [has suggested a syntax](https://github.com/w3c/csswg-drafts/issues/3547#issuecomment-524206816) that I think is a good starting-point for more bikeshed discussion:

```css
@scope (from: .carousel) and (to: .carousel-slide-content) {
  p { color: red }
}
```

In my mind, only the first ("from") clause should be required, and may not need explicit labeling. It would likely accept a single (complex) selector:

```css
@scope (.media-block) {
  img { border-radius: 50%; }
}
```

In terms of selector-matching, this would be the same as `.media-block img`, but with slightly different cascade implications (see below). The second ("to") clause would be optional, and accept a list of selectors that represent lower-boundary "slots" in the scope. The targeted lower-boundary elements are included in the scope, but their descendants are not:

```css
@scope (.media-block) to (.content) {
  img { border-radius: 50%; }
  .content { padding: 1em; }
}
```

Which would only match `img` and `.content` inside `.media-block` -- _but not if there are intervening `.content` between the scope root and selector target_. This follows the current selector-scoping behavior of various popular tools.

I'm not convinced that `to` is necessarily the right keyword (others have proposed `until`) or if we should even consider using a functional syntax, or calling calling the lower boundary "slots":

```css
@scope root(.media-block) slots(.content) { /* ... */ }
```

More discussion would be useful.

### 2. Make the cascade effects of scoping much less intrusive (weighted below specificity)

When scopes do overlap, it's useful to recognize the _proximity_ of a scope (inner scope takes precedence) in the cascade. This is not currently represented in CSS. Descendant selectors rely on source order rather than proximity:

```css
/* link colors for light and dark backgrounds */
.light-theme a { color: purple; }
.dark-theme a { color: plum; }
```

When these color themes are nested, the dark theme will always take precedence:

```html
<div class="dark-theme">
  <a href="#">plum</a>

  <div class="light-theme">
    <a href="#">also plum???</a>
  </div>
</div>
```

Both shadow DOM and the original spec give scoped context a very powerful impact on the cascade — overriding even specificity. The original spec also inverted scope-layering for `!important` declarations. This follows the logic of more highly-isolated use-cases, where there is more clear distinction between the inner scope and the outer host. But in the more common lightly-scoped cases, a more nuanced interplay between specificity and scope is helpful. Most existing tools only add minimal cascade weight to scoped selectors, like a single attribute selector.

I propose re-adding "scope proximity" to the cascade specification _after/below_ selector specificity, but above/before source-order. That would help resolve our example above:

```css
@scope (.light-theme) {
  a { color: purple; }
}

@scope (.dark-theme) {
  a { color: plum; }
}
```

```html
<div class="dark-theme">
  <a href="#">plum</a>

  <div class="light-theme">
    <a href="#">purple</a>
  </div>
</div>
```

While still allowing more _specific_ selectors to override scope when desired.

If authors desire more layering impact similar to the initial spec, that is now available using [Cascade Layers](https://drafts.csswg.org/css-cascade-5/#layering) — and the two features can be combined.

## A path forward

This still needs a lot of work, but my goal here is to open discussion around a path forward for light-DOM scope/namespacing. I have a much more detailed [explainer](https://github.com/oddbird/css-sandbox/blob/main/src/scope/explainer.md) for my thought-process — but there are a lot of open questions, and I'd like to: 

- gauge CSSWG interest before going deeper
- get more people involved with fleshing out the details

Happy for comments, thanks!

**Comment by nemzes** [comment]
Love the proposal. A bit of bike-shedding to get things started: what about "within" and "without" instead of "from" and "to"? It's not the most common use of "without", but to me it sounds like the most fitting word. "To" and "until" imply linearity, which can be misleading.

**Comment by nemzes** [comment]
How would scoped selectors like `:hover` and `:focus-within` behave if the triggering element is a child that is not in scope?

**Comment by nex3** [comment]
*(Context: I'm the tech lead for CSS infrastructure at Google)*

This sort of declarative, light-DOM scoping would be very useful for our widest use-case of component-based styles that may either be rendered server-side or client-side, and that sometimes need escape hatches to do global styles. We would probably take measures to enforce that component scopes corresponded one-to-one with templates, so that we could reason locally about those styles for various optimization passes. This is something that's historically been very difficult to do safely in CSS, so a scope mechanism enabling it is very exciting.

**Comment by jimmyfrasche** [comment]
Re https://github.com/oddbird/css-sandbox/blob/main/src/scope/explainer.md#can-scoped-selectors-reference-external-context

If "scoped selectors should be otherwise unaware of the scope" wouldn't that mean that both divs in the example below are blue?
```html
<div class=x>
  <div class=component>
    <div class=x>
      <div class=x>x</div>
      <div class=y>y</div>
    </div>
  </div>
</div>
<style>
@scope (.component) {
  .x .x { color: blue; }
}
</style>
```

My preference would be for an explicit `.my-host-page :scope .my-component-part` (if for no other reason than to make it clear what's intended!) with just disallowing it entirely a distant second.

**Comment by mirisuzanne** [comment]
My [scope slides](https://slides.oddbird.net/csswg/f2f2102/#slide-26) are also [archived as a PDF](https://lists.w3.org/Archives/Public/www-archive/2021Feb/att-0002/Container_Queries_Proposal_-_vF2F_2021-02-09.pdf) (along with the container-query proposal), for anyone interested. Scope proposal begins at slide 26. 

I expected my proposal to make scope proximity _less powerful_ than selector specificity might be surprising compared to previous proposals. But I didn't come to that proposal lightly – it's based on a lot of conversations, and research of the existing tools. In an [informal Twitter poll](https://twitter.com/mirisuzanne/status/1351247559738621952): 


> What color would you expect to see on a paragraph that is matched by both these CSS rules?
> 
> ```css
> @​scope (aside) {
>   p { color: green; }
> }
> 
> aside#sidebar p { color: red; }
> ```

75% of the responses expected specificity to override scope (paragraph text is red). And that makes sense to me for several reasons:

- In current tooling, scope proximity doesn't exist (there's no way to express it in the CSS output). Instead the intent of proximity is achieved only through lower-boundaries. If you don't want styles to leak in from an outer scope, you add lower boundaries to that outer scope.
- In this proposal authors can define an outer scope, and _decide_ if it should flow into nested scopes, or have boundaries applied. Component authors could write strongly contained styles with lower boundaries, and also achieve something like the [Vue "deep" selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors) by having a second scope rule without lower bounds. Rather than making the internal scope powerful so that "no styles get in" we give the external scope boundaries so that "no styles get out".
- If scope proximity overrides specificity, it becomes nearly impossible for authors to penetrate that boundary. The entire goal of this proposal as an alternative to shadow-DOM is that we make the boundaries more flexible, and author-controlled.
- The use-cases I saw where proximity is essential (eg nested light/dark modes) also tended to have the equal specificity, because the goal is to apply variations of the same styles. In that case, we can _fall back_ on proximity without needing it to be powerful.

**Comment by astearns** [comment]
Post-meeting discussion continued: https://www.w3.org/2021/03/10-css-minutes.html#t07

**Comment by OliverJAsh** [comment]
Regarding [the namespace problem](https://css.oddbird.net/scope/explainer/#the-namespace-problem), consider this example:

```css
.title {
  color: blue;
}

@scope (article) {
  .title { font-size: 2em; }
  .meta { font-style: italic; }
}
```

```html
<article>
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>
```

(Example based on https://css.oddbird.net/scope/explainer/#avoid-naming-conflicts-without-custom-conventions.)

I presume the styles for both `title` classes would be applied (the global class and the scoped class)? What if (for whatever reason) I only want to use the global styles and not the scoped styles? With existing tooling we would be able to do something like this:

```css
.title {
  color: blue;
}

.article {
  &__title { font-size: 2em; }
  &__meta { font-style: italic; }
}
```

```html
<article class="article">
  <!-- Here I'm deliberately *not* using the scoped styles -->
  <span class="title">Hello, World!</span>
  <span class="article__meta">foo</span>
</article>
```

Ideally we would have the flexibility to decide whether we want to:

- just use the global class styles
- just use the scoped class styles
- use both (the global and scoped class styles)

**Comment by mirisuzanne** [comment]
> Ideally we would have the flexibility to decide whether we want to (for each usage):
> 
> - just use the global class styles
> - just use the scoped class styles
> - use both (the global and scoped class styles)

I think those are interesting use-cases, but I don't see any clear way for `@scope` to handle those distinctions better than selectors already do. The final decision here always has to be made on the HTML side, and that's what selectors are for. 

In this proposal, you could set it up selectors exactly the same way as before. But it would also let you clarify the decision once, at the component level:

```css
/* it's not really "global" if it has exclusions… we can clarify those */
@scope ( html ) to ( .exclusive ) {
  .title { color: blue; }
}

/* make the article scope more explicit/optional with a class */
@scope (article.scoped) {
  .title { font-size: 2em; }
  .meta { font-style: italic; }
}
```

Now we can make that decision to use `.scoped` or `.exclusive` in the html:

```html
<!-- global only -->
<article>
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>

<!-- scoped only -->
<article class="scoped exclusive">
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>

<!-- both together -->
<article class="scoped">
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>
```

**Comment by OliverJAsh** [comment]
Interesting, thanks for your response!

This is a contrived example but what if I want to use the scoped `meta` class alongside the global `title` class? E.g. in BEM:

```html
<article class="article">
  <!-- Here I'm deliberately *not* using the scoped styles -->
  <span class="title">Hello, World!</span>
  <span class="article__meta">foo</span>
</article>
```

I guess you could do something like this:

```css
@scope ( html ) to ( .exclusive ) {
  .title { color: blue; }
}

@scope (article) {
  .meta { font-style: italic; }
}

@scope (article.withTitle) {
  .title { font-size: 2em; }
}
```

```html
<article>
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>
```

```html
<article class="withTitle exclusive">
  <span class="title">Hello, World!</span>
  <span class="meta">foo</span>
</article>
```

**Comment by DarkWiiPlayer** [comment]
@jimmyfrasche 

> If "scoped selectors should be otherwise unaware of the scope" wouldn't that mean that both divs in the example below are blue?

Personally, that's what I find intuitive in this case: the middle `.x` is a) inside the scope and b) inside an `.x`, so the rule *should* apply to it.

If you want only the inner `.x` to be matched by the rule, something like `:scope .x .x { ... }` makes more sense to me.

**Comment by chrishtr** [comment]
Ok to close this issue? The spec is now created. Hopefully nothing else is being tracked here?

I've also opened #6790 about strong vs weak.

**Comment by prlbr** [comment]
Thank you @mirisuzanne and everyone. It is awesome to see scoping on this promising path forward now.

**Comment by cvrebert** [comment]
Spec link: https://drafts.csswg.org/css-cascade-6/#scoped-styles
(Would've been nice if the PR/commit cross-referenced this issue.)

**Comment by mirisuzanne** [comment]
After working on a new draft with @fantasai, I'd like to bring it back up for a move to FPWD.
