### ISSUE TITLE
[css-flexbox][css-overflow]Where is the relationship between flexbox and overflow defined?

### ISSUE THREAD

**Issue by hgl** [w3c/csswg-drafts#5812]
I wonder where is the relationship between flexbox and overflow defined? I skimmed both flexbox 1 and overflow 3 editor’s drafts, couldn’t find the answer. 

Specifically, I’m trying to understand this behavior: in a single-line column flex container whose first child has flex:none, whether or not the second flex: 1 child, which has long content,  overflows the flex container, seems to depend on if it has a non-’visible’ overflow.

Currently, it has the same height as its content under ‘visible’, but I expect it to have the same height as the available flex space, not as its content, and only its content overflows. Isn’t that how overflow: auto could work in the first place?

Would love to find the part where this is explained.

**Comment by Loirooriol** [comment]
That would be https://drafts.csswg.org/css-flexbox-1/#min-size-auto

> To provide a more reasonable default minimum size for flex items, the used value of a main axis automatic minimum size on a flex item that is not a scroll container is a content-based minimum size; for scroll containers the automatic minimum size is zero, as usual.

The `overflow` property defines whether the flex item will be a scroll container.
You can also use `min-height: 0` if you don't want the automatic minimum size, but don't want to turn the flex item into a scroll container.

**Comment by hgl** [comment]
I kept having maximum width in mind when looking the explanation, but now it totally makes sense. Thanks!
