### ISSUE TITLE
[css3-text] Missing percentage in definition of word-spacing

### ISSUE THREAD

**Issue by ByteEater-pl** [w3c/csswg-drafts#5818]
One of at-risk features in the spec is "the percentage values of `word-spacing`". However, the values are just `normal | <length>`. Probably `<length-percentage>` was intended.

**Comment by frivoal** [comment]
Actually, it was intentionally removed (and deferred to level 4), but we apparently forgot to remove the mention of it from the list of at-risk features.
See https://github.com/w3c/csswg-drafts/issues/2165 for the Level 4 discussion

**Comment by frivoal** [comment]
I have removed the stray reference from the Editor's draft. @svgeesus do you think you could make the equivalent fix on the TR copy, or do we need a whole new publication to clean that up?
