### ISSUE TITLE
[selectors] :focus-visible on a <select> element

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#5822]
Spec: https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo

Checking the WPT tests for `:focus-visible` I've just found that Chromium and Firefox behave differently for the case of a `<select>` element focused via mouse click. 

A very simple example would be something like:
```html
<style>
:focus-visible {
  outline: 5px solid green;
}

:focus:not(:focus-visible) {
  outline: 0;
  background-color: red;
}
</style>
<select id="target">
  <option>Click me!</option>
  <option>foo</option>
  <option>bar</option>
</select>
```

When you click the `<select>` element in Chromium you get a green outline (so `:focus-visible` matches), but in Firefox you get a red background.
You can test it live in at: https://codepen.io/mrego/pen/xxEXWBg

I guess the relevant test on the spec is this:
> * Any element which supports keyboard input (such as an input element, or any other element which may trigger a virtual keyboard to be shown on focus if a physical keyboard is not present) should always match :focus-visible when focused.

`<select>` somehow supports keyboard input, as you can move up&down on the different options, so I guess that's why Chromium make it match `:focus-visible`.
BTW something similar happens with radio buttons, that you can use the keyboard arrows to move between them, however in that case when you click on a radio button neither Chromium or Firefox match `:focus-visible`.

CC @alice @emilio @robdodson

**Comment by emilio** [comment]
I think that the Firefox behavior is preferable here. To me at least dropdown selects are more similar to `<button>` than to other `<input>` elements. Also, I don't think I'm concerned about not showing outlines in this case, as when the select is focused there's a clear indicator of that (the dropdown).

>  BTW something similar happens with radio buttons, that you can use the keyboard arrows to move between them, however in that case when you click on a radio button neither Chromium or Firefox match :focus-visible.

That's working definitely as expected. That's regular focus navigation which always matches `:focus-visible` and is different to clicks.

**Comment by emilio** [comment]
Hmm, Chrome's behavior seems a bit more subtle. Both browsers match `:focus` at the same time:

```
data:text/html,<style>:focus { outline: 1px solid green }</style><select><option>abc</option><option>def</option></select>
```

But it seems that chrome by default doesn't show outlines if the dropdown is open:

```
data:text/html,<select><option>abc</option><option>def</option></select>
```

But it does match `:focus-visible` (?):

```
data:text/html,<style>:focus-visible { outline: 1px solid green }</style><select><option>abc</option><option>def</option></select>
```

That's very odd and it means that authors can't really accomplish the native behavior. I think Chrome behavior is wrong, it should either not match `:focus-visible` when the dropdown is open, or it should behave like Firefox.

**Comment by bkardell** [comment]
I think the real test is captured in "would it show you a virtual keyboard" and that it also supports up/down key navigation is somewhat a distraction.  If you use the keyboard, it should show, if you don't here, I think it shouldn't.

It is interesting that the chrome behavior doesn't actually match the native behavior... Can we fix that? Or confirm it we agree it should match and which end it should be fixed on (ie, is focus-visible behavior here wrong, or native?)

**Comment by alice** [comment]
The behaviour of not showing the focus outline, but matching `:focus-visible` when the select is open is curious. My recollection is that we use similar code paths for `:focus-visible` and for showing the focus outline. Has anyone filed a chrome bug for that yet?

**Comment by mrego** [comment]
As it seems we all agree this is a Chromium bug and it doesn't need edits on the spec, I'm closing this issue and I've just reported the bug at https://crbug.com/1169708.

Thanks for the comments!

**Comment by mrego** [comment]
Reopening this as maybe we were not in agreement before.

This problem of `<select>` matching `:focus-visible` was reported in Chromium in https://crbug.com/1148007, and that was [closed as WONTFIX by @alice with the following comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1148007#c7):
> `<select>` is an interesting case. I know that it is an element that does take focus on click in Safari, to make the platform conventions on macOS. (You can reproduce this on https://boom-bath.glitch.me/tabindex.html which has a comprehensive suite of elements to test with.) The reason for this is that you can type the first few letters of an option to quickly jump through a long list.  
> 
> I think for similar reasons, it does take focus on mobile web browsers on iOS, as iOS shows a native picker at the bottom of the screen. I'm not sure what Android does these days.
> 
> I do think this is working as intended - when clicking a select element, the focus style gives you a hint that you might want to use the keyboard to interact with it, even if you weren't previously using the keyboard.

I tend to agree with the bug report that either the spec should be clearer or this behavior should be changed.
Actually I have [a patch to change that and align Chromium with Firefox on this](https://chromium-review.googlesource.com/c/chromium/src/+/2644906).


About the weird issue that @emilio found, with `:focus-visible` matching when outline wasn't show. I believe this is due to a Chromium bug, that [the click on the `<select>` is not considered a mouse click](https://source.chromium.org/chromium/chromium/src/+/b2c2a7a8bc510a4a06a43456b69cf58b8908a7b2:third_party/blink/renderer/core/html/forms/select_type.cc;l=234), so it believes it's a keyboard focus and for that reason it matches `:focus-visible`. I had to fix that on my previous patch too.

**Comment by emilio** [comment]
I still think treating dropdown `<select>`s like `<button>` makes more sense than treating them like other text-input things like `<input type=text>`. Sure, it reacts to _some_ keyboard input, but so does `<button>`, which activates with the spacebar or enter or what not.

**Comment by mrego** [comment]
Other things that react to a keyboard input is a `<input type="checkbox">` that you can use spacebar to check/uncheck it, or `<input type="range">` that you can use the arrows to move it. Both don't match `:focus-visible` after click, but start matching if you use the keyboard to interact with them.

**Comment by robdodson** [comment]
> About the weird issue that @emilio found, with :focus-visible matching when outline wasn't show. I believe this is due to a Chromium bug, that the click on the <select> is not considered a mouse click, so it believes it's a keyboard focus and for that reason it matches :focus-visible.

I think this seems like a Chromium bug. It doesn't seem like `:focus-visible` should match if the default focus indicator is not being shown.

Btw I thought I did a test on this and saw that Firefox 84 did show a focus ring on select but when I upgraded to 85 it stopped. I may have totally imagined this but is there an easy way to check?

**Comment by emilio** [comment]
We enabled `:focus-visible` in 85, so sounds likely: https://bugzilla.mozilla.org/show_bug.cgi?id=1445482

**Comment by robdodson** [comment]
I also wonder if this should be left up to the individual browsers? I think we anticipated there might be some disagreements on the margins which is why this language was used in the spec:

> User agents can choose their own heuristics for when to match :focus-visible; however, the following (non-normative) suggestions can be used as a starting point

For what it's worth, I can see an argument being made for select in either direction. button and radio allow for activation (spacebar) and directional (arrow) actions. Select does all of that but it also allows for character input (you can type an option) which makes it sort of input-like as well.

I wonder if it might be expedient for us to keep the existing focus ring behavior in the various browsers so it doesn't block shipping the change in Webkit, while continuing the discussion to see if we want to make follow on changes to how select works?

**Comment by mrego** [comment]
I'm fine with leaving this "undefined" and each browser decide what to do here. If we want to do that, probably we should remove the `<select>` from `focus-visible-002.html` test and put that as an internal Chromium test.

Still I believe it'd be better if we have an agreement and we could follow it in all implementations, so web authors and users don't get confused by the differences. But it looks like that's not possible right now.

**Comment by alice** [comment]
Browsers already make different choices about whether to focus `<select>` on click, and whether to show a default focus style. I think it's more important to be internally consistent within each browser between `:focus-visible` and the browser's default behaviour than to be consistent across browsers here.

**Comment by mrego** [comment]
> Browsers already make different choices about whether to focus `<select>` on click, and whether to show a default focus style. I think it's more important to be internally consistent within each browser between `:focus-visible` and the browser's default behaviour than to be consistent across browsers here.

I'm fine with leaving this open to each browser.

**Comment by mrego** [comment]
Sorry I clicked the button by mistake, I wanted to ask a last question about Chromium's behavior (maybe this should be discussed in Chromium bugzilla though).

Just to make sure what would be the expected behavior in Chromium.
When you click the `<select>` the first time and it gets opened, as it doesn't show a focus ring it shouldn't match `:focus-visible` (that would be a behavior change as currently it does match `:focus-visible`). But when you click on an option or outside the element and it gets closed, as it shows a focus ring it should match `:focus-visible`. 
Or we want to change the initial behavior so on the first click it shows a focus ring and keeps matching `:focus-visible`?

**Comment by alice** [comment]
I think let's be consistent with the existing behaviour, i.e. show a focus ring and match `:focus-visible` only when focus returns to the "button" part of the element, after the pop-up closes.

**Comment by mrego** [comment]
Ok, I guess we can then close this issue. Thanks for all the feedback here.
