### ISSUE TITLE
[css-color] predefined-00*.html tests reference value is incorrect (or rather can't match the tests).

### ISSUE THREAD

**Issue by samweinig** [w3c/csswg-drafts#5832]
The tests matching the path http://wpt.live/css/css-color/predefined-00*.html  (e.g. http://wpt.live/css/css-color/predefined-001.html) use http://wpt.live/css/css-color/greensquare-ref.html as their reference (via `<link rel="match" href="greensquare-ref.html">`) but that green square is not the same green as the tests want.

The tests want a green of `background-color: #009900`.
The expected (greensquare-ref.html) has a green of `background-color: #008000;`.

**Comment by svgeesus** [comment]
You are right, I updated the tests in response to comments but did not update the reference (which is shared among many tests) I will create a different reference for these tests. Thanks for the bug report!

**Comment by svgeesus** [comment]
@samweinig please review, https://github.com/web-platform-tests/wpt/pull/27209
