### ISSUE TITLE
[css-scroll-snap-1] scroll-padding-block and scroll-padding-inline only apply to scroll containers

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#5845]
`scroll-padding-block` and `scroll-padding-inline` are the shorthand properties for [`scroll-padding-inline-start`, `scroll-padding-block-start`, `scroll-padding-inline-end`, and `scroll-padding-block-end`](https://drafts.csswg.org/css-scroll-snap-1/#propdef-scroll-padding-inline-start) and define the edges of the scrollport of a scroll container.

Though the [properties definition claims that they apply to all elements](https://drafts.csswg.org/css-scroll-snap-1/#propdef-scroll-padding-block). So that should be corrected to say "scroll containers".

Sebastian

**Comment by fantasai** [comment]
Fixed, thanks. :)
