### ISSUE TITLE
[cssom][css-color] Need clarification on serialization of `rgb` & `rgba` in light of css-color-4's syntax changes

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#585]
CSSOM has an explicit algorithm for how to serialize CSS values. For colors, it says to serialize as `rgb()` vs `rgba()` depending on whether they have an alpha of one:

> <color>
>    If <color> is a component of a resolved or computed value, then return the color using the `rgb()` or `rgba()` functional notation as follows: 
> 1. If the alpha component of the color is equal to one, then return the serialization of the `rgb()` functional equivalent of the opaque color.
> 2. If the alpha component of the color is not equal to one, then return the serialization of the `rgba()` functional equivalent of the non-opaque color. 

https://drafts.csswg.org/cssom/#serializing-css-values

This makes perfect sense, in a world where `rgb()`/`rgba()` syntaxes differ (and where only `rgba()` allows for transparency).

HOWEVER, css-color-4 is broadening the `rgb()` syntax so that it accepts transparent colors.  It only mentions `rgba()` as an afterthought, as an alias "with identical grammar" to `rgb`, which only exists "for legacy reasons":
https://drafts.csswg.org/css-color-4/#rgb-functions

SO: now that `rgba()` is a legacy alias, and it's trivial to serialize transparent colors with `rgb()`, should we simplify the CSSOM serialization algorithm to always use `rgb()`?  Or should we hold onto its dependence on `rgba()`, for backwards-compat purposes with websites that might expect the old serialization behavior?

And, in particular -- if an author specifies e.g. `color: rgb(10,20,30,0.5)`, are implementations expected to serialize that with `rgba` even though the author used `rgb`?

**Comment by cabanier** [comment]
If an author used rgb(10,20,30,0.5), that should be the way it's returned in the computed style.
CSSOM has to be updated to reflect this.

**Comment by dholbert** [comment]
Pushing back slightly: what would be the point of maintaining state about whether the author used `rgb` vs `rgba`?  If we're going to that trouble, should we also record whether the author used comma syntax vs. comma-less syntax, so we can faithfully recreate their chosen syntax when serializing, too?  (I hope not.  I'm just not sure where to draw the line on which of the author's stylistic choices get preserved for serialization.)

**Comment by cabanier** [comment]
The value doesn't need to be returned exactly the same way it was set. If an author uses the new syntax, it would be weird if the computed style reflects to old legacy syntax.
We will likely need both.

**Comment by SebastianZ** [comment]
Note that the authored syntax is needed for debugging purposes. (Every browser development tool has an option to switch the display of colors to the authored value.)

Besides that, I think it's fine to compute legacy `rgba()` values to `rgb()` with alpha channel as long as that change is web compatible.

Sebastian

**Comment by cabanier** [comment]
> as long as that change is web compatible.
It's very likely that this is not the case as it will change existing behavior and script won't see the alpha anymore or get confused about the extra parameter

**Comment by SebastianZ** [comment]
>> as long as that change is web compatible.
> 
> It's very likely that this is not the case as it will change existing behavior and script won't see the alpha anymore or get confused about the extra parameter

Yes, it's likely. Though that's something that should be checked.

Sebastian

**Comment by tabatkins** [comment]
I *suspect* that we're trapped by legacy compat, and have to keep the existing CSSOM rules.  If anyone would like to try and serialize to rgb(), tho, please be my guest.

**Comment by astearns** [comment]
https://github.com/w3c/csswg-drafts/issues/1004#issuecomment-714541161 has resolutions for this issue
