### ISSUE TITLE
[css-cascade-5] Rename @layers to @layer

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5855]
The degenerate syntax for declaring a layer is `@layer name;`. We also have `@layers name1, name2, name3;` for doing multiple at once; I think it should just have the same at-keyword: `@layer`. No reason we can't, and it avoids confusing authors about the 's'.

**Comment by tabatkins** [comment]
Well, the degenerate syntax for a single layer is actually `@layer foo {}`.

But yeah, assuming there's no weird parsing quirks in impls with having an at-rule be ended *either* by a block or a semicolon, then I'm fine with this.
