### ISSUE TITLE
[css-cascade-5] Define preshint as its own cascade layer, below all other author layers

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5856]
We're effectively doing this already via a specificity hack, but now that we have layers we can define it as its own layer and not worry about specificity.

**Comment by fantasai** [comment]
Fwiw, this would also solve https://github.com/w3c/csswg-drafts/issues/5836 when the layer-specific revert is used in the author’s base layer.

**Comment by frivoal** [comment]
In case anybody else is like me and needs to do a bit of digging to figure out what "preshint" is, it's referring to what's discussed there: https://html.spec.whatwg.org/#the-css-user-agent-style-sheet-and-presentational-hints

And yes, I think this is a good idea.
