### ISSUE TITLE
[mediaqueries] Account for minimum font size in relative length media queries

### ISSUE THREAD

**Issue by leefloyd** [w3c/csswg-drafts#5858]
When a browser has a minimum font-size that is larger than the default font-size, the initial font-size used in media queries is relative to the smaller value. For a site that has been coded to scale with relative lengths, this can cause many layout issues as breakpoints no longer align with what has effectively become relative size of the content. Relative units in declarations _are_ affected by minimum font-size, but media queries are not affected.

In the context of this following statement, I think the initial value of the font size should be defined as the greater of the user-specified sizes—either default or minimum font-size.
"Relative length units in media queries are based on the initial value, which means that units are never based on results of declarations."

https://www.w3.org/TR/mediaqueries-5/#units

**Comment by frivoal** [comment]
I agree with you. As long as browsers are not implementing the minimum font-size via some property (applied in the UA stylesheet), then there shouldn't be any technical reason why doing what you suggest should be unfeasible.

**Comment by lilles** [comment]
Minimum font-size does not affect em/rem lengths in computed values on elements. Blink aligned with Firefox for M79 fixing [308862](https://crbug.com/308862). The reason for fixing it was that a minimum font-size would break a lot of real-world layouts. We discovered that when there was a bug which accidentally wrote a minimum font-size of 6px from the settings UI and we got many reports about it.

The typical failing sites would set the font-size on the html element to a size lower than the minimum font-size expecting rem units for other elements to not be affected by the minimum font-size.

So, I don't think the statement about relative units in the first comment is accurate. At least not for Chrome or Firefox. The width and height of this box is 100px regardless of minimum font-size:

```
<style>
  div { font-size: 1px; width: 100em; height; 100em; background: green }
</style>
<div></div>
```

**Comment by leefloyd** [comment]
With typical browser defaults, this box would be 100px wide.
If I change my default font size to 24px, the box will be 150px wide. 
If I leave my default font size at 16px but change my minimum font size to 24px, the box will remain 100px wide. Thus, text content inside the box will be enlarged but the box will remain the same size. Media queries cannot be used to detect/correct this scenario since they will still be relative to the 16px default font size as well.

```
<style>
  div { width: 6.25rem; height: 6.25rem; background: green }
</style>
<div>This text should fit comfortably inside</div>
```

**Comment by leefloyd** [comment]
I like that wording! Thanks all!
