### ISSUE TITLE
[css-images-4] Include gradients in the cross-fade() notation

### ISSUE THREAD

**Issue by m6o** [w3c/csswg-drafts#5860]
Currently, the cross-fade() notation allows including colors (https://drafts.csswg.org/css-images-4/#cross-fade-function).

Also allow including gradients.

`cross-fade() = cross-fade( <cf-image># )`
`<cf-image> = <percentage>? && [ <image> | <gradient> | <color> ]`

If a `<gradient>` is provided, it represents a gradient image with “automatic” dimensions (it doesn’t participate in the sizing of the result image at all; see details in the sizing details below).

This allows images to be cross-faded to gradients, but also allows mixing gradients of different functions. 

The cross-fade() notation may then be used for interpolating gradients which do not conform to the restrictions currently specified for interpolating gradients (https://drafts.csswg.org/css-images-4/#interpolating-gradients). Ideally these transitions are translated to a cross-fade internally.

**Comment by SebastianZ** [comment]
Gradients are already allowed through the `<image>` value, which also covers the use case of interpolating between arbitrary gradients.

The algorithm you linked to even refers to `cross-fade()` for cases, in which the other interpolation methods fail.

Sebastian

**Comment by m6o** [comment]
Thanks for the reply.

Closing this because there is nothing to add.
