### ISSUE TITLE
[css-flexbox][css-grid] order property definition only mentions "flex items"

### ISSUE THREAD

**Issue by juliandescottes** [w3c/csswg-drafts#5865]
I was looking for the list of elements to which the "order" CSS property applies to, and the only one I found was https://www.w3.org/TR/css-flexbox/#order-property

It says `order` "Applies to:  flex items", but `order` also applies to grid items (per https://www.w3.org/TR/css-grid/#order-property). Maybe the property definition should be updated to mention it also applies to grid items?

**Comment by SebastianZ** [comment]
Maybe it should even be moved out of the Flexbox specification into one, which both specs refer to, maybe extend CSS Box Alignment's scope to cover it, or a totally new one that also includes `z-index` from CSS 2.

But I agree that as a first step, the Flexbox definition should include that it also applies to grid items.

Sebastian

**Comment by fantasai** [comment]
CSS Display might be another candidate for the property, maybe a better fit than a stacking context or alignment spec.

**Comment by SelenIT** [comment]
To me, alignment seems a slightly better choice than display spec, because the behavior of `order` is affected by the `display` value of the container, not the elements themselves, similarly to how alignment properties are, and the alignment spec already has a section for the behavior of alignment properties in different formatting contexts/schemes. Or maybe visual and non-visual ordering of items is worth its own distinct module, perhaps combined with spatial navigation and related a11y aspects?

**Comment by Loirooriol** [comment]
`order` reorders boxes, so CSS Box might also be a candidate.

**Comment by SebastianZ** [comment]
In the discussion participants were biased by initially mentioning Display as the preferred spec. The alternatives (Alignment, Box, new spec.) were not discussed.

I don't have a strong opinion on that topic, though when making a decision all options should be considered.

Sebastian

**Comment by fantasai** [comment]
Alignment is about the positioning of boxes relative to their containing blocks, and `order` has nothing to do with that. So I think it wouldn't make sense there.

CSS Box Model focuses on margins and paddings and defining the various box areas. I don't think `order` really fits into there either.

CSS Display focuses on the construction of the box tree, and `order` effectively reorders elements in the box tree. This is why I think it's the best fit.

Note the +1 from @rachelandrew, who teaches this stuff. If she felt it was an uncertain fit, I think she would not have marked +1.

**Comment by SebastianZ** [comment]
@fantasai Thank you for the explanation for why you decided moving it to the Display module!

I previously wrote to _extend_ the Alignment module to move it there, as I thought it would fit best there, or create a completely new spec. for it, but anyway, your explanation is fine for me.

Sebastian

**Comment by tabatkins** [comment]
Fixed in 0259f1f7d
