### ISSUE TITLE
[css-color-adjust-1] Missing forced color properties

### ISSUE THREAD

**Issue by alisonmaher** [w3c/csswg-drafts#5873]
Similar to #5778, it appears there are a few missing CSS color properties that we may want to consider [adjusting in Forced Colors Mode](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties):

- `caret-color`
- `flood-color`
- `lighting-color`
- `stop-color`

**Comment by SebastianZ** [comment]
Also, `fill` and `stroke` are shorthands in the Fill and Stroke specification and should probably be replaced by the more specific [`fill-color`](https://drafts.fxtf.org/fill-stroke-3/#fill-color) and [`stroke-color`](https://drafts.fxtf.org/fill-stroke-3/#stroke-color).

Having said that, [`fill`](https://svgwg.org/svg2-draft/painting.html#SpecifyingFillPaint) and [`stroke`](https://svgwg.org/svg2-draft/painting.html#SpecifyingStrokePaint) are also defined in SVG 2, and there they are longhands and don't have equivalent `fill-color` and `stroke-color` pendants.

Sebastian
