### ISSUE TITLE
[css-ruby] (Ab-)using `ruby` for HTML footnotes?

### ISSUE THREAD

**Issue by tomayac** [w3c/csswg-drafts#5891]
Hi editors and experts of CSS Ruby Annotation Layout Module Level 1,

I have been experimenting with using `ruby` for HTML footnotes and written up my findings in a [blog post](https://blog.tomayac.com/2021/01/24/ruby-html-footnotes/). My core question is: is this an abuse of ruby? Is it a stretch? I'd be very interested in hearing your thoughts. Thanks in advance!

Cheers,
Tom

**Comment by svgeesus** [comment]
Although ruby was introduced to HTML & CSS primarily because of its use in Asian languages, nothing about it is specific to that. Similarly, although it is often used to give a phonetic pronunciation, ruby is not specific to that so other uses are okay.

And yes it is really odd that HTML has nothing for directly expressing an inline note (a footnote is just one presentation possibility, more suitable to paginated content). 

So I would not say it is an abuse. It is a bit creative, but mostly because people only think of the most common use cases.

**Comment by tomayac** [comment]
Thanks for the reassuring confirmation of my reading of the spec. As a follow-up question then: should UAs be supposed to allow me to customize how `rt` gets displayed? For example, Firefox supports the text book ruby use case with pure UA stylesheets perfectly, but has [issues](https://github.com/tomayac/blogccasion/issues/27) with the way I try to style it. Thanks for your ideas in advance!

**Comment by myakura** [comment]
One thing to note is that there are chances your footnotes do not look as intended. If you read your blog post on RSS reader, your author stylesheet will be stripped and making it hard to read.

Here's a screenshot taken on Feedly:
![screenshot](https://user-images.githubusercontent.com/413984/105728737-d7b67680-5f6f-11eb-88e9-56f7d7d246af.png)

**Comment by tomayac** [comment]
That's right, acknowledged in https://github.com/tomayac/blogccasion/commit/1acee15507dbcd923929be1e55763bc301b84b52. I also still need to tackle `print` styling.

**Comment by frivoal** [comment]
Another thing you might want to consider is how this is going to get rendered by screenreaders. I don't believe there is anything firmly established yet, but given that ruby is sometimes used for additional information, screenreaders may read both the base and the annotation, which would work well for your case. However, ruby is most often used for pronunciation, and screen readers tuned to that usage would only read one of the base or the annotation (likely the annotation), that would not play well with your proposed use.

**Comment by tomayac** [comment]
> Another thing you might want to consider is how this is going to get rendered by screenreaders. 

Thank you, acknowledged in https://github.com/tomayac/blogccasion/commit/bcd64029ed6d39c25d68eaddb3109fa792b50c0e. 

If anyone from the WG has an opinion on it, I'm still interested in hearing thoughts on *"should UAs be supposed to allow me to customize how `rt` gets displayed? For example, Firefox supports the text book ruby use case with pure UA stylesheets perfectly, but has [issues](https://github.com/tomayac/blogccasion/issues/27) with the way I try to style it."* Thanks in advance!

**Comment by fantasai** [comment]
Per CSS, you should be able to customize the rendering of anything other than replaced/semi-replaced elements.* But Firefox is the only browser that supports the CSS ruby model; the other browsers have all hard-coded it, the way table layout used to be hard-coded into browsers before they supported the CSS2 table display values.

That said, the markup you choose should generally be something that degrades reasonably when not using CSS. :) Ruby might work OK for short footnotes like citation info, but long ones seem problematic...

<small>* Footnote: ;) There's a few HTML elements whose rendering can't be described in CSS yet, so those aren't always customizable.</small>

Does that answer your question?

**Comment by tomayac** [comment]
> Does that answer your question?

Perfectly. **Thanks** everyone for your time and wisdom. I'm closing this Issue then; and, based on everyone's feedback, will keep using `ruby` for my footnotes/annotations 😃.
