### ISSUE TITLE
[css-color-4] Make it more clear which predefined colorspaces allow percentages in the color() function

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#5894]
It would be useful to make it very clear which of the predefined colorspaces (https://www.w3.org/TR/css-color-4/#predefined) accepted by the color function allow or disallow percentages. 

For example, I would assume color(srgb 50% 50% 50%) is valid, but color(xyz 50% 50% 50%) is not (since you can't take 50% of +infinity). color(lab ) is currently clear as it states: `The lab [CIELAB] colorspace accepts one percentage and two numeric parameters,...`

**Comment by svgeesus** [comment]
Oh good point. XYZ was added later, and I forgot to disallow percentages. I should add an explicit statement on each colorspace.

**Comment by svgeesus** [comment]
@weinig hopefully that change makes everything explicit?

**Comment by weinig** [comment]
Looks great! (Only slightly related, the Editors Draft link on https://www.w3.org/TR/css-color-4/ seems to go to an index page now).

**Comment by svgeesus** [comment]
Trying just now, the ED link seems to go to https://drafts.csswg.org/css-color/ which is the same as https://drafts.csswg.org/css-color-4/

**Comment by Crissov** [comment]
Wouldn't it be simpler and more consistent to always make `0.5` equal to `50%` inside `color()`?

**Comment by svgeesus** [comment]
> Wouldn't it be simpler and more consistent to always make 0.5 equal to 50% inside color()?

No.
