### ISSUE TITLE
[css-color-adjust-1] Better explanation for `color-schemes` in spec?

### ISSUE THREAD

**Issue by alice** [w3c/csswg-drafts#5897]
Coming here from the [TAG review](https://github.com/w3ctag/design-reviews/issues/583) for css-color-adjust-1.

Based on the spec alone, we had trouble understanding what the `color-schemes` property was used for. The explanation Tab gave in the linked issue was helpful; it would be good if more of that explanation was present in the spec.

Even with that context, the code examples don't really clarify much, since they're identical. Could we have some more nuanced code examples?

It would also be helpful to have some examples which demonstrate the failure case which occurs when this property isn't available.

**Comment by fantasai** [comment]
@tabatkins and I did a substantial rewrite of this section which we hope addresses the concerns here. We haven't gotten to improving the examples yet, but we will do that also.

We don't believe this needs time on the F2F agenda.

**Comment by alice** [comment]
In that case, I would like to see a clearer explanation of how the "normal" value would be used in practice. 

Might it be better renamed as something like "none", to indicate that no color scheme is available to match to, and that "normal" *doesn't* imply a light colour scheme (as some may expect)?

**Comment by tabatkins** [comment]
All right, explained "normal" a little more (you wouldn't use it on purpose, it's just the default value).

Also merged the two examples with identical code, and added more examples of when you'd use single values. I didn't tag the commit properly; it's b3c3be5a2.
