### ISSUE TITLE
[css-color-adjust-1] Are `normal` and `light` synonymous for `color-schemes`?

### ISSUE THREAD

**Issue by alice** [w3c/csswg-drafts#5898]
Coming here from the [TAG review](https://github.com/w3ctag/design-reviews/issues/583) for css-color-adjust-1.

I note that "normal" is more or less synonymous with "light", in practice. Why have two values which mean roughly the same thing? Could "normal" be replaced with "light" as the default?

**Comment by hober** [comment]
Closing given the resolution above.
