### ISSUE TITLE
[css-conditional-3] [css-fonts-4] Allow CSS.supports('font-family: system-ui') for feature detection

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#590]
https://drafts.csswg.org/css-conditional-3/#the-css-interface
https://drafts.csswg.org/css-fonts-4/#extended-generics

Context: blink-dev [Intent to Implement and Ship: The “system-ui” generic font family](https://groups.google.com/a/chromium.org/d/msg/blink-dev/hvN9YVvIb5c/5DrcunKSCAAJ) where I wonder "Would there really be any privacy concern in allowing support for an alias like this to be detected? It seems about as harmless as CSS.supports('font-family: sans-serif')."

I couldn't actually find which specs makes it currently not work, help @kojiishi?

It seems like a good idea to support this for all generic font families, to disable any code that might be making guesses based on other information.

**Comment by upsuper** [comment]
I don't think using `'font-family: system-ui'` works here, because simply wrapping it with parens `'(font-family: system-ui)'` makes it pass on all browser. We may need a function syntax for this kind of thing.

**Comment by kojiishi** [comment]
Spec-wise, `CSS.supports` defines:
> value would be successfully parsed as a supported value for that property

and `system-ui` is a valid [font_family_name](https://drafts.csswg.org/css-fonts-3/#fontfamilyname), so it should return true.

A function syntax as suggested by @upsuper might work, but probably the first thing to discuss is what are the cases where cascading [font_family_name_list](https://drafts.csswg.org/css-fonts-3/#fontfamilynamelist) cannot solve but `CSS.supports` can. Do you have any examples in mind?

**Comment by foolip** [comment]
My assumption was that implementations that don't support this also don't parse it successfully, but apparently that's not the case.

I'm OK with closing this if nobody has good ideas.

**Comment by litherum** [comment]
It appears that nobody has any good ideas.
