### ISSUE TITLE
[css-color-4] Example 20 has an erroneous % in the alpha serialization output

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#5903]
In Example 20 in the section https://drafts.csswg.org/css-color/#serializing-color-function-values, the following results incorrectly puts a % sign on the alpha serialization.

> is the string "color(prophoto-rgb 0.28 0.403 0.423 / 0.85%)", if three decimal places are retained.

The alpha value should be just `0.85` (I think. I can't quite tell where it states that alpha is serialized as <number> and not a percentage for color functions, but since all the other values do, it should probably should as well).

**Comment by svgeesus** [comment]
Thanks again for the detailed feedback! You are correct, there should not be a percentage.

This is [explicitly stated](https://drafts.csswg.org/css-color-4/#serializing-alpha-values)

> If the alpha is any other value than 1, it is explicitly included in the serialization, as a <number>, not a <percentage>. The value is expressed in base ten, with the "." character as decimal separator. The leading zero must not be omitted. Trailing zeroes must be omitted.

So the example you cited is clearly incorrect.

**Comment by weinig** [comment]
> This is explicitly stated.

Heh, yeah, that's pretty clear. Not sure how I missed it, just looking in the wrong places. In light of that, there is at least one other example that has this wrong:

Example 17 in https://drafts.csswg.org/css-color-4/#serializing-lab-lch

Is 

> is the string "lch(56.2% 83.6 357.4 / 93%)"

should be:

> is the string "lch(56.2% 83.6 357.4 / 0.93)"

**Comment by svgeesus** [comment]
Thanks, I checked all the serialization examples (searched "is the string") and those were the only two.
