### ISSUE TITLE
[css-color-4] Clarify which transfer function to use for color(rec2020 ...)

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#5907]
The normative definition for color(rec2020 ...) at https://drafts.csswg.org/css-color-4/#valdef-color-rec2020 says to use a transfer function value of `1/2.4` (with a note) whereas the sample conversion code at https://drafts.csswg.org/css-color-4/#color-conversion-code uses a different value of `0.45`. (This could just an issue of updating the sample code to account for this).

A few things to note:
- It looks like color.js (https://github.com/LeaVerou/color.js/blob/master/src/spaces/rec2020.js) uses `1/2.4`.
- From testing, it seems like CoreGraphics, the graphics library on macOS and iOS, uses the `0.45` when using the kCGColorSpaceITUR_2020 named color space. (This is not a blocker for us, I can perform the conversion manually, but it would be a bit unfortunate for CSS and CoreGraphics to disagree here, if people are trying to use color values interchangeably.)

**Comment by svgeesus** [comment]
I was discussing this with Chris Cameron from Google earlier this week. The unreferenced quote is from BT.2020-2, **Parameter values for ultra-high definition television systems for production and international programme exchange** page 5, note 4. Which seems to directly contradict the table on page 4 of the same specification. The notes is not saying what is _correct_, but rather what is _commonly done_ and _maybe good enough_.

https://www.itu.int/rec/R-REC-BT.2020-2-201510-I/en

Having checked BT.2020 I am comfortable removing the note and referencing BT.2020 directly. Which as you point out is what the sample code already does. So it is more a case of updating the spec to match the sample code and BT.2020

I will update color.js to use 0.45 per spec, too.

**Comment by svgeesus** [comment]
> From testing, it seems like CoreGraphics, the graphics library on macOS and iOS, uses the 0.45 when using the kCGColorSpaceITUR_2020 named color space.

To clarify, it uses that except for the linear portion near zero, right?

**Comment by weinig** [comment]
> To clarify, it uses that except for the linear portion near zero, right?

Correct.

**Comment by svgeesus** [comment]
[fix sample code for rec2020 transfer function](https://github.com/w3c/csswg-drafts/commit/c9a6f043a067b7811f2c80833b1966b88ba13c49#diff-3afab410617d295a0a2ff34a4f372c890d9f4ebe62d1588de2a0fbe1c4ed3b3f)

**Comment by svgeesus** [comment]
@weinig [added WPT tests](https://github.com/web-platform-tests/wpt/pull/27416)
