### ISSUE TITLE
[css-transforms-1] Application of transforms to positioned inlines

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#5909]
This is a direct follow on to https://github.com/w3c/csswg-drafts/issues/908, which decided on the following text:

> Alternately, “all elements except non-replaced inline boxes, table-column boxes, and table-column-group boxes” (blacklist, rather than whitelist, approach) if that is easier.

All browsers currently also apply this to non-replaced inlines _if they're absolutely positioned_. So I think the text needs updating to reflect this.

**Comment by Loirooriol** [comment]
But absolute positioning implies blockification, so it stops being an inline. https://drafts.csswg.org/css-display-3/#transformations

**Comment by faceless2** [comment]
Fair enough :-) Obviously there remains a distinction between absolutely positioned `display:inline` and `display:block`, as they have different static positions. But yes, the spec says they're no longer inline, so there's no ambiguity.
