### ISSUE TITLE
[css-values-4] Add <rounding-strategy> syntax to defininition list

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#5915]
The `<rounding-strategy>` syntax is missing from the following list:
https://github.com/w3c/csswg-drafts/blob/9c1c802bd4a8f3610b57157d5ee911879beb5c40/css-values-4/Overview.bs#L3745-L3767

For completeness, we should include:
`<rounding-strategy> = <dfn>&lt;rounding-strategy></dfn> = nearest | up | down | to-zero`

**Comment by SebastianZ** [comment]
It can't be specified with `<dfn>` because it's already defined in the prose. So it should probably also like to the text.

Sebastian

**Comment by fantasai** [comment]
Fixed, thanks for the report!
