### ISSUE TITLE
[css-shadow-parts-1] The part pseudo-element should support animations

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#5917]
In working on a proposal to potentially unlock checkbox/radio styling I utilized a web component to mimic my pseudo elements. One example I wanted to show was animation of the checkmark itself but this was blocked due to `part()` not being animatable while other pseudo-elements are. Here is a reduction of the issue:

https://jsbin.com/rofuqawuji/edit?html,css,js,console,output

cc: @tabatkins since we already discussed this issue.

**Comment by gregwhitworth** [comment]
I'm going to take a glance at the spec and see if this is something I can land a PR for.

**Comment by tabatkins** [comment]
This isn't a problem with ::part(); there's nothing about it that stops things from animating, and no edit to the shadow-parts spec will fix it. This is a problem with Shadow DOM and CSS's name-defining constructs, and the solution is outlined in <https://github.com/w3c/csswg-drafts/issues/1995> (I've just updated the original post to take into account the feedback and compromises from later in the thread, so there's no need to read past the original post unless you want context.)
