### ISSUE TITLE
[css-text-3] ednit: hyphenation may not visually indicate split

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#5938]
5.4. Hyphenation: the hyphens property
https://www.w3.org/TR/2020/CR-css-text-3-20201222/#hyphenation

> Hyphenation is the controlled splitting of words where they usually would not be allowed to break to improve the layout of paragraphs, typically splitting words at syllabic or morphemic boundaries, and visually indicating the split (usually by inserting a hyphen, U+2010).

Since it could be read in two ways, i assume that 'typically' also modifies 'indicating' – ie. that the spec doesn't bar the possibility that hyphenation produces no visual indication?

**Comment by tabatkins** [comment]
Yes (tho this is all non-normative intro text)

**Comment by r12a** [comment]
Perhaps remove the comma after boundaries?

**Comment by r12a** [comment]
The following is a test for a feature enabled by PLH to allow people who can edit issues to assign labels to an issue. The addition will take place when the tool is run (daily).
[[
+i18n-tracker
]]
