### ISSUE TITLE
[css-color-5] Hue interpolation when using 2 different normalization strategies

### ISSUE THREAD

**Issue by devmattrick** [w3c/csswg-drafts#5964]
In the [CSS Color Module 5 color-mix spec](https://drafts.csswg.org/css-color-5/#color-mix), it allows for both arguments of the function to be hue interpolated with _different_ normalization strategies. For example:

```css
color-mix(lch(52% 58.1 257.1) hue shorter 75.23%, lch(56% 49.1 22.7) hue decreasing 24.77%);
```

In this case, the shorter interpolation strategy is applied to the first color, giving us:
```
h1 = 257.1, h2 = 22.7
h2 - h1 = 22.7 - 257.1 = -229 < -180
```
The [css-color-4 spec](https://drafts.csswg.org/css-color-4/#hue-interpolation) states that in the case where `h2 - h1 < -180`, `h2 += 360`. It is unclear to me if the 360 addition to the second color's hue should be ignored entirely, added before the second interpolation is applied, or added after the second interpolation is applied. If the value is not ignored, can the second algorithm then affect the hue of the first color? Continuing the example, using the decreasing strategy:

```
h1 = 22.7, h2 = 257.1
h1 < h2
```
So we need to add 360 back to the first color's hue. Would this affect the second color again (as in, would we need to reapply the "shorter" interpolation again)? Could this result in an infinite loop?

Sorry if this is unclear I did my best explaining it but I definitely could be missing something. Thanks for reading!

**Comment by svgeesus** [comment]
@devmattrick  wrote

> it allows for both arguments of the function to be hue interpolated with different normalization strategies. 

Ouch, yeah, good catch! I can't think of a reasonable use case for that, I guess it just falls out of how the syntax is expressed. Clearly, the two hues need to be mixed using a single normalization strategy.

One way to fix this is to make the syntax a bit more complex so the first hue can have a normalization strategy and the second can't. Another is to require them to both be the same (I don't like that one, having to repeat a value is bad) and the third way is to say that the first 9or last, whatever) strategy wins.

The spec should however be clear that the hue normalization is for mixing **pairs** of hues.

**Comment by svgeesus** [comment]
Aaand I thought this was a new issue but actually it predates the `color-mix()` simplification.

So, this is already taken care of.

**Comment by devmattrick** [comment]
Oh awesome, the simplification is definitely easier to understand/ implement! Thanks!
