### ISSUE TITLE
letter-spacing should take a percentage that scales each individual glyph's advance?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5965]
In https://github.com/w3c/csswg-drafts/issues/5533, we resolved to add `advance-override` which takes a percentage, which scales up each individual glyph's advance.

Maybe `letter-spacing` should be able to achieve a similar effect?

**Comment by fantasai** [comment]
Um. I can't imagine anyone *wanting* tracking that's proportional to the glyph advance width in a proportional font, it would look really messed up for 'm' to have more spacing than 'i', right?

**Comment by litherum** [comment]
Why should `advance-override` be different from `letter-spacing` then?

**Comment by fantasai** [comment]
@litherum Because it's trying to fake being a different font, not trying to add tracking. Tracking should be added via letter-spacing.
