### ISSUE TITLE
[css-ruby] alternating sides for ruby-position

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#5971]
Several people have suggested ([Xidorn](https://lists.w3.org/Archives/Public/www-style/2009May/0189.html), [Roland](https://lists.w3.org/Archives/Public/www-style/2009May/0189.html)) that there should be a value (possibly called `auto`, or `alternate`),
that alternates between 'over' and 'under' when the ruby has multiple levels of interlinear annotation.

> My [Xidorn’s] proposal is: This value is not computed to anything else. And during the
positioning, this value is equal to "over" for rtc in odd indexes, and "under" for rtc in even indexes.

> Overall, it sounds reasonable to [fantasai], but I think we should have a way to specify the first level, rather than always being over. Maybe `[ over | under ] || alternate` instead? Or something else?

This value should probably be the initial value.

**Comment by jensimmons** [comment]
Could you add a code example to this, @frivoal ? Of what's being proposed.

**Comment by frivoal** [comment]
Here's an example. It's a little contrived in order to keep it in English for readability's sake, but the same idea would apply, and be more common, in Japanese or Chinese.

```html
<ruby>
  <rb>S<rb>Q<rb>L</rb>
  <rtc><rt>Structured <rt>Querry <rt>Language</rtc>
  <rtc>Sequel</rtc>
</ruby>
```

This would look like this:

> <img width="214" alt="Screen Shot 2021-02-19 at 9 07 50" src="https://user-images.githubusercontent.com/113268/108438143-fb7c8c00-7291-11eb-92ea-37ee2a8c7c33.png">


However, when you have two levels of ruby, the typical expectation is that instead of stacking up, they go on alternate sides, like this:

> <img width="203" alt="Screen Shot 2021-02-19 at 9 07 41" src="https://user-images.githubusercontent.com/113268/108438163-046d5d80-7292-11eb-83b1-836d7b495ca1.png">


As the spec stands today, you can achieve it using `ruby-position`. For instance:
```css
rtc:last-of-type {
   ruby-position: under;
}
```

That's cool, but:
1. You have to ask for it explicitly, even though it's the most commonly desired outcome
2. The selector in the example above is specific to the markup pattern used in that example, and no generic selector that would work across all pages can be written (rtc and rt elements can, and typically are, omitted in most situations)

However, if instead of `over`, the initial value of `ruby-position` was `alternate` (a keyword we'd need to introduce), it would work outside of the box, without a need for manually opting into it.

The other variant being proposed is instead of `over | under | alternate`, we could have `[over | under ] || alternate`. `alternate` or `over alternate` would do the same as the above example (first annotation over, then alternate), while `under alternate` would put the first annotation under, and then alternate.

**Comment by astearns** [comment]
In reading the resolution I parsed `alternate` in the 'alternative' sense, and for a split-second worried that we had not specified what that alternative value was. Could `switch` perhaps be a better value name?

**Comment by frivoal** [comment]
you're alternating between sides, first over, then under, then over, then under… I think alternate is a better name for that than switch, so I'd rather stick to it.

**Comment by frivoal** [comment]
@upsuper

**Comment by astearns** [comment]
Yep, that’s fine. And we already use `alternate` in `animation-direction`.

**Comment by upsuper** [comment]
@kojiishi @tkent-google Are you planning to support this in RubyNG?
