### ISSUE TITLE
[css-fonts-5] Allow tweaking font-size at per-fallback granularity

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#5976]
This issue is split off from https://github.com/w3c/csswg-drafts/issues/126

There are 2 use cases:
- Being able to tweak the look of fallback fonts while web fonts are loading. The goal is to reduce the effects of the visual reflow when the web font does finally load (aka "flashiness")
- Being able to tweak the look of fallback fonts for characters which are unsupported by the primary font. (I'm sure we've all seen cases where a rogue "é" somewhere on the page is rendered in some horrific and particularly noticeable fallback.)

The goal is to allow pages the ability to say something like "for this fallback font, use font size X, but for this other fallback font, use font size Y."

In https://github.com/w3c/csswg-drafts/issues/126#issuecomment-776063005 we resolved to do this sort of thing via `@font-face` descriptors.

Note that something similar (though less flexible) can be done already with [`font-size-adjust`](https://drafts.csswg.org/css-fonts-4/#font-size-adjust-prop). So this bug isn't very high priority, as that will probably work for many of these situations.

**Comment by svgeesus** [comment]
> Note that something similar (though less flexible) can be done already with font-size-adjust. 

For text a) whose characters use the Latin (or possibly Cyrillic or Greek) scripts, and b) thus the glyphs have a meaningful x-height, and c) where the difference between the fallback and the web font is a significant difference in x-height, then yes.

Otherwise, (i.e. for most of Unicode) `font-size-adjust` offers no benefit.

**Comment by svgeesus** [comment]
@litherum @r12a 

> There are 2 use cases:

There are 3 use cases, the third being

- Being able to tweak the look of fallback fonts where different fonts in the font stack have very different visual sizes, for the script being rendered.
-

**Comment by litherum** [comment]
> @litherum @r12a
> 
> > There are 2 use cases:
> 
> There are 3 use cases, the third being
> 
> * Being able to tweak the look of fallback fonts where different fonts in the font stack have very different visual sizes, for the script being rendered.

I think that's the same as the second case. Maybe I was unclear in my description?

**Comment by r12a** [comment]
To my mind it's a different use case – one that is not to do with ransom noting, ie. displaying the text on a single platform where the chosen font lacks glyphs, but rather substituting (fully complete) fonts for each other on different platforms.  As a _use case_ that's different.

However, https://github.com/w3c/csswg-drafts/issues/126#issuecomment-777479537 describes another use case that is quite close to your point 2, where a font doesn't contain Latin glyphs needed for acronyms, names, or quoted text, etc.

**Comment by litherum** [comment]
> but rather substituting (fully complete) fonts for each other on different platforms. As a use case that's different.

Okay, that makes sense. Got it.

**Comment by svgeesus** [comment]
> I think that's the same as the second case. Maybe I was unclear in my description?

Not at all. (Except if one argues that a font which doesn't exist has support for zero characters. But even then, calling the non-existent font `primary` seems odd).

**Comment by litherum** [comment]
This topic is a dup of https://github.com/w3c/csswg-drafts/issues/6075
