### ISSUE TITLE
[css-grid] Confusing definition of auto repeat tracks computation

### ISSUE THREAD

**Issue by svillar** [w3c/csswg-drafts#598]
Section 7.2.2.2 https://drafts.csswg.org/css-grid/#auto-repeat specifies how to compute the number of auto-repeat tracks depending on some factors. It turns out that it is subject to different interpretations.

Let's translate it first to pseudocode (I'm skipping some things like using 1 if any repetion overflows for the sake of simplicity)

```
if (size or max-size are specified)
  use size or max-size
else 
  if min-size is definite
    use min-size
```
At least is what we have understood in Chromium and WebKit when we implemented it. This means that we always use size or max-size if any of them are definite, and *only* the min-size if both of them are indefinite.

However it seems that FF is doing it differently according  Mats' comment here https://bugs.chromium.org/p/chromium/issues/detail?id=648814#c2. He considers that min-size should be always considered in the computation if it's definite. Which interpretation is correct?

**Comment by svillar** [comment]
Closing this because it's still not clear that there is a disagreement. I'll reopen if it still applies.

**Comment by fantasai** [comment]
Yeah, I think the spec is clear on Mats's point. “When auto-fill is given as the repetition number, if the grid container has a definite size or max size in the relevant axis, then the number of repetitions is the largest possible positive integer that does not cause the grid to overflow its grid container.”
