### ISSUE TITLE
[css-flexbox] clarify whether collapsed flex items influence the flex container's intrinsic main size

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#5985]
The ["flex container intrinsic main sizes" spec-text (section 9.9.1)](https://drafts.csswg.org/css-flexbox-1/#intrinsic-main-sizes) doesn't currently say anything special about excluding or special handling for collapsed flex items.  It probably should.

I think they are intended to have zero contribution to the container's main size, based on a side-comment in the ["Collapsed Items" section, section 4.4](https://drafts.csswg.org/css-flexbox-1/#collapsed-flex-item) -- that section says: "...collapsing or uncollapsing items may change the flex container’s main size", but never says precisely how.  (That section does say that these items turn into zero-main-size "struts", but that happens after the container's intrinsic sizing.)

Probably https://drafts.csswg.org/css-flexbox-1/#intrinsic-main-sizes step 1 needs:
```
s/For each flex item/For each flex item (excluding collapsed flex items)/
```
...or something along those lines.

**Comment by dholbert** [comment]
actually, step 3 is the most important step to adjust: `add each item’s flex base size to the product of [...]`.  We need to define things such that this added quantity ends up at 0, for collapsed flex items (or simply exclude collapsed flex items from the "add each item's..." operation here.)

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1692366 on fixing this in Firefox/Gecko (to exclude collapsed items from the container's main-axis intrinsic sizing)

**Comment by fantasai** [comment]
@dholbert Edits checked in, let us know if we missed anything?
Agenda+ to verify with the CSSWG.

**Comment by dholbert** [comment]
The edits look good to me. Thanks!

**Comment by tabatkins** [comment]
Implicitly tested by https://github.com/web-platform-tests/wpt/blob/master/css/css-flexbox/flexbox-collapsed-item-horiz-001.html
