### ISSUE TITLE
[css-color-adjust-1] accent-color in Forced Colors Mode

### ISSUE THREAD

**Issue by alisonmaher** [w3c/csswg-drafts#5987]
It seems like we should probably add `accent-color` to the list of properties that are [adjusted in Forced Colors Mode](https://drafts.csswg.org/css-color-adjust-1/#forced-colors-properties).

Forcing this to `auto` seems like the obvious choice, similar to `scrollbar-color`. However, what should happen if `forced-color-adjust` is set to `none` or `accent-color` is set to a system color? Should we ignore those and force `accent-color` to `auto` no matter what, or should we honor the adjust rules to allow author customization?

**Comment by FremyCompany** [comment]
If adjust is set to none, I don't think accent color should be reset.

It probably isn't necessary to do anything with this property btw, because in forced colors mode, browsers can just decide not to use the accent color in their design, right ?

**Comment by alisonmaher** [comment]
@FremyCompany yeah, honoring `forced-color-adjust` and leaving it up to the UA in terms of how to handle `accent-color` in their form control design makes sense to me.
