### ISSUE TITLE
[css-grid] Non-replaced items with aspect ratio should be handled

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#5988]
https://www.w3.org/TR/css-grid-1/#grid-item-sizing

> If the grid item is a replaced element with a natural size in the relevant dimension (or with a preferred aspect ratio and a size in the other dimension) the grid item is sized as for align-self: start

The parenthetical should probably also apply to non-replaced elements with an aspect ratio.

@tabatkins @fantasai

**Comment by Loirooriol** [comment]
See latest draft: https://drafts.csswg.org/css-grid-2/#grid-item-sizing

> If the grid item has no preferred aspect ratio, and no natural size in the relevant axis (if it is a replaced element)

**Comment by tabatkins** [comment]
Yup, this is fixed in the EDs.
