### ISSUE TITLE
[css-ruby-1] inter-character ruby on right or inline-end side of bases?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6001]
Inter-character bopomofo annotations are go on the **right** side of the character they annotate. We wanted to confirm if that's the correct answer in bidi situations, or if it should be the inline-end side.

(Given that right-to-left Chinese is a thing that exists, and it would almost certainly also place annotations on the right side, our inclination is to keep this definition as placement on the right.)

**Comment by xfq** [comment]
Filed https://github.com/w3c/clreq/issues/350

**Comment by fantasai** [comment]
Closing no change, confirmed that inter-character places on the (physical) right side.
