### ISSUE TITLE
[css-sizing-3] Clarify 300px size of replaced elements

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6019]
https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-width states:
> Otherwise, if 'width' has a computed value of 'auto', but none of the conditions above are met, then the used value of 'width' becomes 300px. If 300px is too wide to fit the device, UAs should use the width of the largest rectangle that has a 2:1 ratio and fits the device instead.

CSS Sizing might want to bake this rule into https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes

**Comment by tabatkins** [comment]
Already done in that section, at least for the 300x150 part. The "largest 2:1 rectangle that fits" part of the text is not carried over, but as far as we can tell, it's not web-compatible either, so we're going to write it off as hopeful specifiction and not carry it over.
