### ISSUE TITLE
[css-color-4] Update Accessibility Considerations statement 

### ISSUE THREAD

**Issue by digilou** [w3c/csswg-drafts#6035]
Related to: 
* [CSS A11y TF #34](https://github.com/w3c/css-a11y/issues/34)
* #4943 

Per APA on 17 Feb 2021:
Please update the wording in the [CSS Color Module Level 4's Accessibility Considerations](https://www.w3.org/TR/css-color-4/#a11y-sec) section.

Current wording:
>This specification encourages browsers to ensure adequate contrast for specific system color foreground/background pairs. A harder requirement with specific AA or AAA contrast ratios was considered, but since browsers are often just passing along color choices made by the OS, or selected by users (who may have particular requirements, including lower contrast for migraine or epilepsy sufferers), the CSSWG was unable to require a specific contrast level.

Requested wording to use people-first language:
"This specification encourages browsers to ensure adequate contrast for specific system color foreground/background pairs. A harder requirement with specific AA or AAA contrast ratios was considered, but since browsers are often just passing along color choices made by the OS, or selected by users (who may have particular requirements, including lower contrast for people living with migraines or epileptic seizures), the CSSWG was unable to require a specific contrast level."

**Comment by svgeesus** [comment]
@digilou thanks, fixed!
