### ISSUE TITLE
[css-color-5] Clarification needed on type of r, g, b constants in "relative color syntax" for rgb()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6044]
In CSS Color 5's Relative color syntax, https://drafts.csswg.org/css-color-5/#relative-RGB, the spec is inconsistent on the types/semantics for the r, g, and b, constants. The normative text says "r", "g", and "b" are percentages ("r is a <percentage> that corresponds to the origin color’s red channel after its conversion to sRGB"), but in Example 13, it is intermixing them with non-percentages:

```css
    rgb(from indianred 255 g b)
```

It seems like this should resolve to

```css
    rgb(255 36.0784% 36.0784%)
```
which is invalid.

In the investigative implementation in WebKit, to keep the example working, I implemented it to assume that "r", "g", and "b" can either be numbers or percentages, but they all have to be the same and match the constants as well. So in the example above, since the first parameter is 255, it forces "g" and "b" to use their numeric forms, and therefore resolves to:

```css
    rgb(255 92, 92)
```

Which is what the example says is the result.

This leaves a weird case of no numeric constant being used for any parameter, like:
 
```css
    rgb(from indianred calc(r+1) calc(g+1) calc(b+1))
```

in which case we need some default type. I have picked percentages, since that is what the spec text currently says is the type, but I am not sure if that is desirable.

**Comment by LeaVerou** [comment]
Just as an FYI, after #5782, we are thinking of axing this entire syntax in favor of functions to get component values which are a) closer to what authors are already using in preprocessors and b) allow for vastly more use cases, as they enable use cases where components are combined from multiple colors (previously awkwardly handled by `color-mix()` with adjusters). 

@tabatkins While these edits are most likely welcome (I haven't checked with @una @svgeesus and @argyleink), could you please give a heads up to the editors of specs you modify so that we know what's going on without having to look at the entire commit history? Even better, please discuss any substantive edits with us first?

**Comment by samweinig** [comment]
> Just as an FYI, after #5782, we are thinking of axing this entire syntax in favor of functions to get component values which are a) closer to what authors are already using in preprocessors and b) allow for vastly more use cases, as they enable use cases where components are combined from multiple colors (previously awkwardly handled by color-mix() with adjusters).

Very cool.

**Comment by tabatkins** [comment]
> @tabatkins While these edits are most likely welcome (I haven't checked with @una @svgeesus and @argyleink), could you please give a heads up to the editors of specs you modify so that we know what's going on without having to look at the entire commit history? Even better, please discuss any substantive edits with us first?

While it was a decent editorial edit, mechanically it wasn't substantive. I was just fixing some errors and doing one minor change to rgb() to make it actually match with the examples.

**Comment by astearns** [comment]
> While it was a decent editorial edit, mechanically it wasn't substantive. I was just fixing some errors and doing one minor change to rgb() to make it actually match with the examples.

Let’s add decent editorial edits to the list of things that should require editorial review, then.
