### ISSUE TITLE
[css-color-5] What should happen in color-mix() if two opposing hue adjusters have different interpolation modifiers?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6048]
In CSS Color 5's color-mix() function, https://drafts.csswg.org/css-color-5/#color-mix, what should happen if two opposing hue adjusters have different modifiers? For example:

```css
color-mix(lch, red hue longer 75%, blue hue shorter 25%);
```

Which hue interpolation (https://drafts.csswg.org/css-color-5/#hue-interpolation) algorithm should be used in this case?

**Comment by Myndex** [comment]
IMO and as I mentioned in my lengthy post in #4711 only color(1) should have adjusters and percentages.

The operational theory I am following in this is similar to a "transfer mode" where layer A affects the underlying layer B.

Thus: in color-mix(), color(2) is the underlying color that is to be affected. Color(1) is the color that has some or all attributes affecting color(2).

Of course this is not what the spec says now, but I think it is a more useful way to implement...

**Comment by LeaVerou** [comment]
@weinig The other editors and I have resolved to remove the adjusters from `color-mix()` as we want to keep `color-mix()` simple and plan to address their use cases with different syntax (that we are still discussing). So this and a few other issues can be closed once I push the changes.

**Comment by LeaVerou** [comment]
Since per editor resolution we removed adjusters from `color-mix()`, I'm going to go ahead and close this issue.
