### ISSUE TITLE
[css-color-5] Should there be a comma between mix-components in color-mix()?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6049]
In CSS Color 5's color-mix() function, https://drafts.csswg.org/css-color-5/#color-mix, should there be a comma between mix-components? For example, which of the following is correct:

```css
color-mix(lch, red 40%, blue);
```

or 

```css
color-mix(lch, red 40% blue);
```

The grammar indicates no comma:

```
color-mix() = color-mix(<colorspace>?, <mix-component>#{2})
<mix-component> = <color> [ <percentage> | <color-adjuster>+ ]?
```

but all the examples have commas.

I personally think the comma makes it more readable.

**Comment by Loirooriol** [comment]
But the grammar indicates comma? `<mix-component>#{2}` has a [hash mark](https://drafts.csswg.org/css-values-4/#mult-comma) which

> indicates that the preceding type, word, or group occurs one or more times, separated by **comma** tokens

**Comment by weinig** [comment]
Ah, I missed that. Ok, then that clarifies things. Thanks.
