### ISSUE TITLE
[meta] Specs on drafts.csswg.org have not been updated for almost two months

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#6052]
I'm not sure what happens, but it seems all specs on https://drafts.csswg.org/ have not been updated since 6 Jan, which is almost two months ago. Anyone knows what's happening? Is there something I'm missing? Are the specs moved somewhere else?

**Comment by plinss** [comment]
The specs were updating properly. The problem is that a recent commit deleted and replaced a branch which got the mercurial side of things confused, so the server switched back to serving an older commit. I sorted out the branches so it should be back to normal.

**Comment by tabatkins** [comment]
On Sun, Feb 28, 2021 at 10:45 AM Peter Linss <notifications@github.com> wrote:
> The specs were updating properly. The problem is that a recent commit deleted and replaced a branch which got the mercurial side of things confused, so the server switched back to serving an older commit. I sorted out the branches so it should be back to normal.

I think last time we asked about this was at least a year ago, but are
there still users of the Mercurial version of the repo such that it's
worthwhile to continue doing this inherently error-prone bridging
across the data models? Just committing to git-only would prevent
these data model mismatches from occurring again.
