### ISSUE TITLE
[css-color-5] Consider moving colorspace parameter in color-adjust() to beginning to match color-mix() and ease parsing

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6053]
In the current CSS Color 5 draft's color-adjust() function, https://drafts.csswg.org/css-color-5/#coloradjust, the colorspace is argument is last, which is inconsistent with color-mix(), where it is first, and makes parsing a bit more complicated since we don't know which adjusters are allowed until after we have parsed them.

Please consider moving the colorspace to the beginning, changing the grammar from:

```
color-adjust() = color-adjust( <color> [ color-adjuster <colorspace>? ]? )
```

to

```
color-adjust() = color-adjust(<colorspace>?, <color> [ color-adjuster ]? )
```

**Comment by Myndex** [comment]
How about moving the "colorspace" in color-mix to the end? And also, not calling it colorspace as in most cases it is not a different colorspace and is only a different color notation?

**Comment by samweinig** [comment]
Moving colorspace to the end of color-mix() would make parsing quite a bit more inefficient as you would not know which adjusters were valid as you were parsing them. If adjusters are going to be validated based on colorspace, I think it makes sense for it to come first.

**Comment by LeaVerou** [comment]
We actually made some changes to the color space argument, mandating an `in` keyword before it which allows it to be anywhere in the function. Could you take another look?
We also removed adjusters, so that shouldn't be an issue now.

**Comment by samweinig** [comment]
The current spec (or what I get when I load https://drafts.csswg.org/css-color-5/#coloradjust anyway) has the following grammar now:

> color-adjust() = color-adjust( <color> [ color-adjuster [ in <colorspace> ]? ]? )

Which seems to still have adjusters (though it is no longer defined what a color-adjuster production is).

**Comment by LeaVerou** [comment]
Whoops, I completely missed that this was about `color-adjust()` and not color mix.
I should also resurrect the color adjuster definition and move it there. Thanks!

**Comment by svgeesus** [comment]
Closed by WG resolution to [drop `color-adjust()`](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914)
