### ISSUE TITLE
[css-color-5] Consider allowing multiple color-adjusters to be used in color-adjust()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6054]
In the current CSS Color 5 draft's color-adjust() function, https://drafts.csswg.org/css-color-5/#coloradjust, only 0 or 1 color-adjusters are allowed per the grammar. While clearly one could nest color-adjust() calls, it seems like it would be more consistent with color-mix() to allow multiple adjusters (within the picked colorspace).

**Comment by LeaVerou** [comment]
Note that if we allow multiple adjusters we'd need to resolve these against `color-adjust()`: #6045 #6048

Though an easy way out would be to define multiple adjusters as sugar over nested `color-adjust()` calls.

**Comment by argyleink** [comment]
Can [the HTTParchive](https://docs.google.com/spreadsheets/d/1sMWXWjMujqfAREYxNbG_t1fOJKYCA6ASLwtz4pBQVTw) data help us here? see how often there's multiple adjustments? 
or, I do like the idea of shipping the feature, that requires nesting for multiple adjustments, now and adding sugar later.

**Comment by svgeesus** [comment]
Closed by WG resolution to [drop `color-adjust()`](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914)
