### ISSUE TITLE
[css-flexbox] Transferred minimum size should be clarified

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#6058]
https://drafts.csswg.org/css-flexbox/#min-size-auto

> transferred size suggestion
> If the item has a preferred aspect ratio and its preferred cross size is definite, then the transferred size suggestion is that size (clamped by its minimum and maximum cross sizes if they are definite), converted through the aspect ratio. It is otherwise undefined.

That section talks about just the preferred aspect ratio, which (as far as I understand) does not include an aspect ratio set through the aspect-ratio property. However, I assume (?) the intent is that it should?

@fantasai @tabatkins

**Comment by Loirooriol** [comment]
See https://drafts.csswg.org/css-sizing-4/#aspect-ratio, `aspect-ratio` sets the preferred aspect ratio, not to be confused with the natural aspect ratio.

**Comment by cbiesinger** [comment]
Oh I forgot. Thanks! Closing this then.
