### ISSUE TITLE
[css-color-5] More clarity around the percentage in color-mix()

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6064]
[The defintition of `color-mix()` in CSS Colors level 5](https://drafts.csswg.org/css-color-5/#color-mix) includes a `<percentage>` value for defining the relative weight of the colors being mixed. That weight is given to one of the two colors, with the remaining percentage given to the other color.

From the examples, I can infer that the given weight is used for the _first_ color, and the remaining percentage is applied to the _second_ color – `color-mix(red 80% blue in lch)` will be 80% red and 20% blue – but I don't think that's clearly stated anywhere. It also seems to contradict this note:

> Note: As a corrollary, 0% just returns the first color converted to the specified colorspace, 100% returns the second color converted to the specified colorspace, and 50% produces an equal mix of both.

I would expect that to be the opposite. 

- If we apply `0%` of the first color, we should get the second one converted to a given colorspace.
- If we apply `100%` of the first color, we should get that same color, but converted.

(I'm not sure if there's also a way to make this more clear in the syntax, but that's a separate issue. I have to look this up every time I use the Sass function as well. My mind refuses to retain this information…)

**Comment by LeaVerou** [comment]
Yup, that's an excellent point. The percentage could be interpreted as "X% of the first color" or "X% along the progression". Currently the grammar is written with the first definition in mind (hence why the percentage cannot be after the second color) but the prose describes the second definition.
Perhaps we should make this more clear with syntax (e.g. with an `of` keyword)

**Comment by argyleink** [comment]
agree that the `Note` is opposite. I've submitted a PR adjusting the note #6065 

thoughts on adding 2 keywords so it's suuuuper clear?.. 

```css
color-mix(0% of red with blue in lch)
color-mix(100% of red with blue in lch)
color-mix(80% of red with blue in lch)
```

**Comment by Myndex** [comment]
The following may be tangential to this thread, but:

0% should always have the same result, regardless of linear or the gamma for gamma encoded space.
100% should also.

However 50% should be expected to be very different depending on the gamma or linearness of the space, and just as an FYI, alpha values are affected by the gamma of the color values, so an alpha of 0.5 effectively has a different perceptual effect for different colorspaces, i.e. if you have a color in linear space with an alpha of 0.5, when converting that color to a gamma encoded space, the alpha also needs to be adjusted/converted.

**Comment by LeaVerou** [comment]
@Myndex Could you please open another issue and clarify what change you are proposing? As you were previously advised, posting tangentially related issues into other threads means your points are easily lost.

**Comment by LeaVerou** [comment]
Note that re-introducing commas can also help readability here, with or without the `of` keyword (`20% of red, white`). I've opened an issue about this in #6066

Another thing to resolve on wrt percentages is that perhaps we should allow percentages for either of the colors, instead of only for the first, and specify what happens when both are provided (they are scaled down proportionally, just like `border-radius`).

**Comment by Myndex** [comment]
> @Myndex Could you please open another issue and clarify what change you are proposing? As you were previously advised, posting tangentially related issues into other threads means your points are easily lost.

Hi Lea @LeaVerou   Sorry... Not sure what or if what I am saying is relevant as it looks like there are some bigger changes I'm not aware of, I'll try and get more up to speed before spinning wheels....    :)

**Comment by tabatkins** [comment]
> <fantasai> leaverou: if we handle percentages < 100% by mixing with transparent, it has special interpolation handling so [????]
> <leaverou> s/[????]/we don't want to do that/

Heya @LeaVerou, could you explain what you mean here?

**Comment by LeaVerou** [comment]
That was my mistake, it's **two** legacy colors interpolating that have the [legacy behavior](https://drafts.csswg.org/css-color-4/#interpolation-space:~:text=In%20that%20case%2C%20user%20agents%20may,in%20the%20sRGB%20space%20by%20default.), not one legacy color interpolating with a non-legacy color.
Also, legacy interpolation happens when the host syntax does not define the interpolation space, and we just made it mandatory for `color-mix()`, so that's yet another reason why this doesn't apply.

**Comment by tabatkins** [comment]
Ah, k, so does that imply that we *could* meaningfully mix together `transparent` and two other arbitrary colors in any of our defined colorspaces?

**Comment by svgeesus** [comment]
I think previous edits have ow resolved this. Lea clarified the grammar so that the color and the percentage of that color are clearly grouped; Adam edited the "corrollary" note so it no longer contradicts the grammar.

>     If we apply 0% of the first color, we should get the second one converted to a given colorspace.
>    If we apply 100% of the first color, we should get that same color, but converted.

This is now explicitly stated.
