### ISSUE TITLE
[css-tables] Should min-width support percentages?

### ISSUE THREAD

**Issue by FremyCompany** [w3c/csswg-drafts#607]
Edge and Chrome ignores "min-width: %" while Firefox applies it properly.
Firefox continues to apply a "min-width: %" when a "width: px" is specified (the width is then ignored).

We would like to spec Edge/Chrome behavior here. Any opinion?
cc: @dbaron

**Comment by FremyCompany** [comment]
**Summary of the issue**
> Edge and Chrome ignores "min-width: %" while Firefox applies it. 

**Face to face recommendation**
> Resolve that min-width is ignored when its value is a percentage on table-internal elements

**Examples**
> https://wptest.center/#/tdspq9

**Comment by gregwhitworth** [comment]
It's worth noting webkit matches Chrome/Edge in the testcase as well: https://jsfiddle.net/gvco0t54/
 
![image](https://user-images.githubusercontent.com/865244/28835507-d3653dc6-76e5-11e7-987a-0c58a48f8980.png)
