### ISSUE TITLE
[css-sizing-3] max-content sizes of replaced elements errors

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6072]
https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes which discusses the max-content sizes of replaced elements is a bit off in a few ways:

* The conditional for when this text triggers hooks the text into the undefined cases in CSS2.1, but the text defines a bunch of cases to which the conditional doesn't apply.
* The conditional is above bolded text, so it's not obvious that it limits the text below it.
* The text claims to apply to boxes with / without preferred aspect ratio, but it really should apply specifically to replaced elements.
* The first bullet point of the last case can't apply under the conditional, and is non-Web-compatible otherwise, so should be deleted.

Original commit of this section: https://github.com/w3c/csswg-drafts/commit/c42c80f64a0fe6b1ea05678a16862eb0880b4b76

**Comment by fantasai** [comment]
Original commit of this section: c42c80f64a

**Comment by fantasai** [comment]
@cbiesinger @dholbert Mind reviewing the updated section? :)

**Comment by cbiesinger** [comment]
In this line:
> Note: Note that when the box has a [=preferred aspect ratio=],
I would remove the "Note that" as it's repetitive.

Otherwise, looks good, except I have no idea if removing 300x150 from boxes with an aspect ratio is web compatible.

**Comment by dholbert** [comment]
Looks good to me.
