### ISSUE TITLE
[css-text-decor-4] Add 'inset' keyword to text-shadow

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#6074]
The [`box-shadow`](https://drafts.csswg.org/css-backgrounds-3/#box-shadow) property takes an optional `inset` keyword allowing the shadow to be displayed inside the box, allowing to create "pushed in" effects.

The same should be possible for text shadows. Especially for big bold texts like in headlines this would be valuable to give them a special touch.

Therefore, I suggest to add the optional `inset` keyword to the [`text-shadow`](https://drafts.csswg.org/css-text-decor-4/#text-shadow-property) property. Effectively, this makes its syntax the same as the one for `box-shadow`.

Sebastian

**Comment by Loirooriol** [comment]
But currently, text shadows "never overlay the text itself". Would it be different for inset text shadows? Or would they only be visible if the text is not fully opaque?

**Comment by fantasai** [comment]
Yeah, inset text shadows would have to be painted over the text for sure.

**Comment by Myndex** [comment]
For something bold it would make it easier to sculpt 3D looking glyphs. There are ways to sort of get that effect now...

I'd like to see the "offset" property that box-shadow has added to text-shadow, as that would allow for some fun multi outline effects.

There are accessibility concerns here though and the potential for mis use that damages readability...

**Comment by SebastianZ** [comment]
> I'd like to see the "offset" property that box-shadow has added to text-shadow, as that would allow for some fun multi outline effects.

The x and y offset values are actually the mandatory part of `text-shadow`. E.g. `text-shadow: 2px 2px;` creates a shadow that has a two pixels offset in both directions. Furthermore, `text-shadow` already takes a list of shadows. So `text-shadow: -2px -2px, 2px 2px;` is already valid.

Also note, that [Text Decoration 4 already added a spread radius](https://drafts.csswg.org/css-text-decor-4/#text-shadow-property). So the only difference to `box-shadow` is currently the `inset` keyword. That's also what I wrote in my initial post.

> There are accessibility concerns here though and the potential for mis use that damages readability...

The readability issues actually already exist right now, depending on how you define the shadow(s). (Take the second example from above.) The `inset` keyword wouldn't change that.

Sebastian

**Comment by SebastianZ** [comment]
For what it's worth, here's a related feature request for Gecko including a sample image:

https://bugzilla.mozilla.org/show_bug.cgi?id=577672

Sebastian

**Comment by SebastianZ** [comment]
@fantasai Since that's a straight forward addition with known use cases, could this be added to the agenda to get a decision?

Once it's decided to add it, I can write up some spec. text for it.

Sebastian

**Comment by LeaVerou** [comment]
While we're at it, can we add spread? That's far more frequently needed than `inset` (though both are useful).

**Comment by SebastianZ** [comment]
As mentioned in a previous comment, the [spread radius is already part of Text Decoration 4](https://drafts.csswg.org/css-text-decor-4/#ref-for-propdef-text-shadow②).

Sebastian

**Comment by SebastianZ** [comment]
If you're interested in following the implementation issues, here they are:

WebKit: https://wkb.ug/76997
Chromium: https://crbug.com/1226531
Gecko: https://bugzil.la/655590

Sebastian

**Comment by fantasai** [comment]
Filed follow-up issues in response to smfr's comments in https://github.com/w3c/csswg-drafts/commit/13442dd8d665b07b4867af4358a8850de4bc5a8f :
* https://github.com/w3c/csswg-drafts/issues/7250
* https://github.com/w3c/csswg-drafts/issues/7251
