### ISSUE TITLE
[css-fonts-4] “Font fetching requirements” doesn’t fully specify necessary requirements

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/csswg-drafts#6076]
The *Font fetching requirements* section of the CSS Fonts 4 spec doesn’t fully specify the requirements necessary for a UA to actually perform a font-fetch request and do something with the response.

https://drafts.csswg.org/css-fonts-4/#font-fetching-requirements

A patch (https://github.com/w3c/csswg-drafts/pull/5838) was recently merged that I wrote to add a part of the necessary requirements; but even with that change in place, there are still missing pieces:

* The spec text defines how to construct a request but should also explicitly set the request mode to `cors`.
* The spec doesn’t define what to do with the request; it needs to have something like, “Let *response* be the result of _∞fetching∞_ *request*, where _∞fetching∞_ links to the fetch algorithm in the Fetch spec.
* The spec doesn’t define what to to with the response it gets back.

@annevk

**Comment by svgeesus** [comment]
> The spec doesn’t define what to to with the response it gets back.

Could you point to an example of a similar spec which does define what to do with the response?

**Comment by sideshowbarker** [comment]
> Could you point to an example of a similar spec which does define what to do with the response?

Among CSS specs, in the CSSOM spec, the **Fetching CSS style sheets** algorithm:

https://drafts.csswg.org/cssom/#fetching-css-style-sheets

…and the call points for that in **Requirements on User Agents Implementing the xml-stylesheet processing instruction**:

https://drafts.csswg.org/cssom/#ref-for-fetch-a-css-style-sheet

…and in **Requirements on User Agents Implementing the HTTP Link Header**:

https://drafts.csswg.org/cssom/#ref-for-fetch-a-css-style-sheet①
