### ISSUE TITLE
[css-overflow-4] viewport propagation of scrollbar-gutter

### ISSUE THREAD

**Issue by felipeerias** [w3c/csswg-drafts#6079]
https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property

The `overflow-*` values set on the root or body elements are propagated to the viewport following the rules specified in section [3.5. Overflow Viewport Propagation](https://www.w3.org/TR/css-overflow-3/#overflow-propagation) of the CSS Overflow spec. The element from which the value was propagated will subsequently get a used value of `visible`.

The purpose of this issue is to ask what happens when `scrollbar-gutter` is used on an element from which overflow may be propagated to the viewport.

The expected outcome IMHO would be that the element gets a gutter that matches the scrollbar used by the viewport.

In any case, I think that the spec should cover this situation

**Comment by felipeerias** [comment]
If the value of `overflow-guter` is propagated to the viewport, then section 6 in _CSSOM View Module_ should be amended so `clientWidth` on the root/body takes the presence of a scrollbar gutter into account:

    The clientWidth attribute must run these steps:
    ... 
    
    2. If the element is the root element and the element’s node 
    document is not in quirks mode, or if the element is the HTML 
    body element and the element’s node document is in quirks mode, 
    return the viewport width excluding the size of a **rendered** 
    scroll bar (if any).

https://www.w3.org/TR/cssom-view-1/#dom-element-clientwidth

**Comment by felipeerias** [comment]
Related: #5254

**Comment by felipeerias** [comment]
I have added a small example to the explainer (it only works on experimental code at the moment):

https://github.com/felipeerias/scrollbar-gutter-explainer/blob/master/examples/scrollbar_gutter_example_08.html

This is the result of applying `scrollbar-gutter: stable both;` on the body. In the image on the left the content doesn't cause scrolling; in the image on the right, it does.

![body](https://user-images.githubusercontent.com/1412060/113871194-9bb05500-97ed-11eb-9e95-03e6a966692b.png)

The gutters match the scrollbars created by the viewport, which IMHO would be the expected outcome.

**Comment by frivoal** [comment]
Fixed in 0280a0a
