### ISSUE TITLE
[selectors] Pseudo-class for details

### ISSUE THREAD

**Issue by AndySky21** [w3c/csswg-drafts#611]
[Pseudo-classes](https://drafts.csswg.org/selectors/#pseudo-classes)

Given the description for pseudo-classes and the fact that element interactivity is meant to be handled by UAs instead of relying upon scripts, it would be logical and consistent with other interactive elements if `<details>` open state were matched by an `:open` pseudo class.
On the other hand (and as stated by @chaals), this would would provide a CSS styling hook without the need for UAs to add/remove a content attribute according to user interaction. As a consequence, `<details>.open` IDL property will be allowed to reflect the element state instead of the content attribute.

Related issue: https://github.com/w3c/html/issues/600

**Comment by annevk** [comment]
This shouldn't be needed as you can just use `details[open]` for this.

**Comment by chaals** [comment]
In https://github.com/w3c/html/issues/600 I concluded that there is no real value in changing, so no real value in minting another pseudo-class...

**Comment by fantasai** [comment]
Alright, closing per @annevk and @chaals's comments. Going with invalid rather than wontfix because the premise of not being able to use `[open]` is invalid, but if you'd prefer it marked wontfix lemme know. ;)

**Comment by fantasai** [comment]
@AndySky21 Let me know if this works for you!
