### ISSUE TITLE
[css-fonts] Description of the interaction of `size-adjust` and metrics override descriptors is misleading

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6111]
The text at https://github.com/w3c/csswg-drafts/pull/6108/files/c869db8d5e728ecc0d38f7bf21794ffd0cfdeb62#diff-81d7e2706905db1ad619f5ef68e5c0ca8f0dcedfa14ca44cb151444f6048d987R204-R206 is a bit misleading, I think. The `{ascent|descent|line-gap}-override` descriptors *don't* multiply "the relevant metrics" by the given percentage; they *replace* the metrics derived from the font with metrics computed from the used font size.

**Comment by fantasai** [comment]
Current wording is “The corresponding metric is replaced by the given percentage multiplied by the used font size.” 
https://drafts.csswg.org/css-fonts-5/#font-metrics-override-desc
Seems like that should work?
