### ISSUE TITLE
[css-grid] Clarification how should %-rows resolve.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#6118]
Consider the following testcase ( https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=9084 )

```html
<!DOCTYPE html>
<div style="display: grid; width: 200px; grid-template-rows: 200%; grid-template-columns: 100px 100px; border: solid;">
  <div style="height: 100px; background: orange;"></div>
  <div style="background: cyan;"></div>
</div>
```

Here there is a pretty large difference between webkit/blink & firefox/edge. webkit/blink appear to be re-resolving rows against a (now definite) block-size.

I don't think this is in the spec, however it somewhat matches what happens in the inline-direction with all browsers, e.g. ( https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=9085 )

```html
<!DOCTYPE html>
<div style="display: inline-grid; grid-template-rows: 100px 100px; grid-template-columns: 200%; border: solid;">
  <div style="width: 100px; background: orange;"></div>
  <div style="background: cyan;"></div>
</div>
```

**Comment by bfgeek** [comment]
@fantasai @tabatkins we are up to the point in Blink's new grid implementation where we are determining when we need to re-resolve rows/columns, and this came up as not clear from the specification.

@KurtCattiSchmidt fyi.

**Comment by Loirooriol** [comment]
This is a recurring topic which was last discussed in #5566. @atanassov objected to aligning with Firefox since it would break the symmetry. So webkit/blink are right.

The spec already implies that, https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-length-percentage

> If the size of the grid container depends on the size of its tracks, then the `<percentage>` must be treated as `auto`, for the purpose of calculating the intrinsic sizes of the grid container and then resolve against that resulting grid container size for the purpose of laying out the grid and its items.

There is #3418 about adding further clarifications.

**Comment by bfgeek** [comment]
@Loirooriol Thanks for the clarification, we'll follow the current blink/webkit behaviour, and add a few more tests.
