### ISSUE TITLE
[css-selectors] Query a parent node begining from a child node

### ISSUE THREAD

**Issue by rianby64** [w3c/csswg-drafts#612]
Hello! I'd like to know your opinion about this idea

```javascript
el.querySelector('#add-subitem').addEventListener('click', e => {
  var li = e.target.parentNode.parentNode.parentNode.parentNode.parentNode;
  // this could be simplified via 
  //    e.target.querySelector('< li')
  // as the oposite to 
  //    li.querySelector('#add-subitem')
});
```

If already exists the [operator](https://www.w3.org/TR/css3-selectors/#child-combinators) ```>``` that search a child, so, what about if add a new operator in order to search from a child node up to its parent?

I mean, as I show in the example above, instead of writing parentNode a lot of times, I could use an operator(```<``` or something else) that finds the parent based on a condition.

Thanks for your attention!

**Comment by topaxi** [comment]
You can already achieve this with the `element.closest()` method.

```js
el.querySelector('#add-subitem').addEventListener('click', e => {
  var li = e.target.closest('li');
});
```

**Comment by rianby64** [comment]
I know! I know there's a good way to avoid ```.parentNode.parentNode.parentNode...```
@topaxi , thanks a million.
