### ISSUE TITLE
[css-font-loading] editorial: the definition of document.fonts is really hard to find

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#6125]
https://drafts.csswg.org/css-font-loading/#font-face-source

It took me quite some time to find that this is the place where `document.fonts` is specified.  I'd appreciate if this could be made clearer.

Suggestions:
* perhaps mention document.fonts right in the Introduction and link it to #font-face-source to make it clear that this is the specification that defines document.fonts
* change "The FontFaceSource mixin" chapter title to include "document.fonts"
* at a minimum, linkify the first occurrence of document.fonts

**Comment by tabatkins** [comment]
Good idea, done.
