### ISSUE TITLE
[css-values][css-var] Numeric dashed ident

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#6131]
Are all-numeric [`<dashed-ident>`s](https://drafts.csswg.org/css-values-4/#dashed-idents) like `--123` valid in general and as a [`<custom-property-name>`](https://drafts.csswg.org/css-variables-1/#defining-variables) in particular?

The [informative grammar for `<ident-token>`](https://drafts.csswg.org/css-syntax-3/#ident-token-diagram) seems to allow them and [they are supported apparently](https://jsfiddle.net/dc94uamb/).

If they are intentionally valid indeed, I’d welcome this being mentioned in one of the specs, e.g. in an example.

**Comment by tabatkins** [comment]
Yes, they're valid.

I'm not sure they would need to be called out in an example? Is there some particular reason spec readers should be informed that they're possible to use?
