### ISSUE TITLE
[css-fonts-5] Description of `size-adjust` descriptor is misleading

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6133]
Regarding `size-adjust`, the [current draft](https://drafts.csswg.org/css-fonts-5/#font-metrics-override-desc) says:

> For `size-adjust`, when the descriptor value is a percentage, all metrics values of this font, including glyph advance sizes, are resolved as the given percentage multiplied by the used font size.

This is not correct, I think. It says that every metric -- so that'd be ascent, descent, x-height, cap-height, etc -- as well as every glyph advance will end up with the same value: the used font size multiplied by the `size-adjust` percentage.

I think it should say something more like:

> All metrics values of this font, including glyph advances, are scaled by the given percentage, as are the rendered glyph images. However, the computed font size (and hence units such as `em` that depend on it) are unaffected.

**Comment by fantasai** [comment]
@jfkthame I think this was fixed in https://github.com/w3c/csswg-drafts/commit/df024473bfb1a1e548a3ff42b25d70c92b98e67b#diff-3e391c0014318f36debe3e04cffbfc458ebcae3176bda0b904641e758106bbd1
