### ISSUE TITLE
[css-color-5] What does it mean to specify more than one adjuster identifier in color-adjust()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6134]
In the grammar for color-adjust(), https://drafts.csswg.org/css-color-5/#coloradjust, it seems like it is allowing for some odd things, like specifying multiple adjuster identifiers at once. For instance, the srgb-adjuster, https://drafts.csswg.org/css-color-5/#typedef-srgb-adjuster, is specified as:

```
<srgb-adjuster> = red || green || blue
```

and I believe the `||` means "one or more of them must occur, in any order" (https://drafts.csswg.org/css-values-4/#comb-any).

So this means you could do something like:

```
color-adjust(peru red green 10% in srgb)
```

and I am not sure what that would mean.

Perhaps the single `|` was intended?

```
color-adjust() = color-adjust( <color> [ <color-adjuster> && [ in <colorspace> ]? ]? )
<color-adjuster> = [ [
      <srgb-adjuster> | <hsl-adjuster> | <hwb-adjuster>
    | <xyz-adjuster> | <lab-adjuster> | <lch-adjuster>
  ] | alpha ] <percentage>?
<srgb-adjuster> = red | green | blue
<hsl-adjuster> = <hue-adjuster> | saturation | lightness
<hwb-adjuster> = <hue-adjuster> |  whiteness | blackness
<xyz-adjuster> = x | y | z
<lab-adjuster> = lightness | a | b
<lch-adjuster> = lightness | chroma | <hue-adjuster>
<hue-adjuster> = hue [shorter | longer | increasing | decreasing | specified ]?
```

**Comment by svgeesus** [comment]
Good catch! Yes absolutely, this should be `|` sorry about that.
