### ISSUE TITLE
[css-fonts] Clarify how 'size-adjust' works with text decoration

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#6138]
This is an issue raised from a [code review](https://chromium-review.googlesource.com/c/chromium/src/+/2773716/1..5/third_party/blink/web_tests/external/wpt/css/css-fonts/size-adjust.tentative.html#b1).

The interaction between `size-adjust` and `text-underline-offset` and `text-decoration-thickness` may not be completely straightforward. Hence, a Note paragraph is needed to clarify that `em`- or percentage-based length values are not affected, but `auto` and `from-font` values are affected since they use metrics provided by the font.

**Comment by tabatkins** [comment]
I believe it should be specified to work exactly the same as `font-size-adjust`; I think this agrees with what you wrote. Right, @fantasai?

**Comment by fantasai** [comment]
Yeah, this should just fall out of the definition. It could be an example, though.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/d94d5a94ed9605318dc0c05553520a377aa181dc
Mistagged the commit though. :(
