### ISSUE TITLE
[css-color-5] Questions about color-adjust()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6140]
I have a few questions about the current CSS Color 5 color-adjust() function (https://drafts.csswg.org/css-color-5/#coloradjust), and thought perhaps throwing them in one issue would make sense. (if you would prefer I break these up, I'd be happy to).

1. What should the behavior be when no percentage is provided? In the current grammar, we have `<percentage>?`, which means the percentage can be elided. I am not sure this is useful, so perhaps we should just make it required.

2. What is the use of allowing the `<color-adjuster>` itself to optional. Seems like it should be required.

3. How does the hue modifier (e.g. `shorter`, `longer`, etc.),  change the behavior of color adjusting? I had it in my mind that the modifier only had an effect on interpolation between two hues. Perhaps it isn't needed not that the adjusters are not used for color-mix()?

**Comment by svgeesus** [comment]
> What should the behavior be when no percentage is provided? 

I can't think of a useful default, so suggest the percentage be mandatory

> What is the use of allowing the `<color-adjuster>` itself to optional

There can be more than one, but the grammar should be "one or more" not "zero or more"

> How does the hue modifier (e.g. shorter, longer, etc.), change the behavior of color adjusting?

I think this got added when the modifiers were added to `color-mix`, perhaps without much thought, and that fr a single color you just need a (signed) hue modifier.

**Comment by svgeesus** [comment]
> I think this got added when the modifiers were added to color-mix, perhaps without much thought, and that for a single color you just need a (signed) hue modifier.

It looks like this was an inadvertent effect of simplifying `color-mix`, where it was originally defined but then got dropped.

I changed the parameter on `color-adjust()` to be a simple hue, and restored `<hue-adjuster>?` to color-mix.

**Comment by svgeesus** [comment]
Good points. 

Percentages and color-adjuster are no longer optional. Color space is still optional, with LCH as the default.
