### ISSUE TITLE
[css-color-5] Consider making colorspace required for color-adjust()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6141]
Much like colorspace is now required for color-mix() (see https://github.com/w3c/csswg-drafts/issues/6051), I think the colorspace should be required for color-adjust(). Repeating what I stated in the previous issue:

> I would like to suggest we remove the default value and always require a colorspace to specified. In general, I think requiring explicit color spaces is beneficial to avoid circumstances like we have now with implicit sRGB, where the best choice is no longer what we think it is. If in the past, we had required all colors / transformations of colors to be tagged, it would be much easier to change things today, as finding all the uses of sRGB in a codebase would be just searching for that explicit usage.
>
> It's always possible to add a default later, if it becomes a burden, but it is much harder to remove one, so I think being conservative for now is the right tradeoff to make.

When doing this, we should also consider moving it to the beginning to match color-mix(), which is captured in https://github.com/w3c/csswg-drafts/issues/6053

**Comment by svgeesus** [comment]
Closed by WG resolution to [drop `color-adjust()`](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914)
