### ISSUE TITLE
[css-text-3] The processing order of tab stops

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#615]
CSS Text, Appendix A, [Text Processing Order of Operations](https://drafts.csswg.org/css-text-3/#order) says [white space processing part II](https://drafts.csswg.org/css-text-3/#white-space-phase-2) should occur before letter-spacing and word-spacing.

This step includes expanding [tab stop](https://drafts.csswg.org/css-text-3/#tab-stop) to a horizontal shift, which requires the current horizontal position as an input.

Shouldn't this be done after letter-spacing and word-spacing?

**Comment by kojiishi** [comment]
On second thought, line breaker needs to know the expanded width to compute the line width. So this should be either a) computed in the line breaker, or b) computed before the line break but reset when wrapped before the tab.

**Comment by fantasai** [comment]
Okay, I made this step an unordered list. I think it doesn't make sense to be ordered, since they apply across the line together, not one operation after the other as you say.

Let me know if this is okay.
