### ISSUE TITLE
Same behavior or alias for text-justify: inter-character and text-justify: distribute

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6156]
A few years ago, we decided to have two names for one behavior for the text-justify property: one because we though it was a good name (`inter-character`) and one as a deprecated value because it was implemented already even if we didn't particularly like it (`distribute`).

Currently, we're defining these two as just having the same behavior. Maybe that's fine. Or maybe one should compute to the other so that they get merged when you're observing things in the OM.

It appears that Firefox does compute `distribute` to `inter-character` (and other than Edge, it's the only current implementation of the property).

I propose we specify, as Firefox does, that `distribute` computes to `inter-character`.

**Comment by emilio** [comment]
I filed https://github.com/w3c/csswg-drafts/issues/6193 about specifying aliases at parse-time.
