### ISSUE TITLE
[css-display] `display: grid` doesn't establish a GFC for subgrids

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#6157]
A mentioned in https://github.com/w3c/csswg-drafts/issues/2598#issuecomment-387162013, https://drafts.csswg.org/css-display-3/#valdef-display-grid says

> **grid**
>  The element generates a principal grid container box, and establishes a grid formatting context.

However, subgrids don't establish a GFC. See https://www.w3.org/TR/css-grid-2/#grid-container

> A grid container that is not a subgrid establishes an independent grid formatting context for its contents.

**Comment by tabatkins** [comment]
Yes, this is true, I suppose we can be a little clearer with subgrid there.
