### ISSUE TITLE
[css-ui-4] accent-color OS scheme fingerprinting

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#6158]
[accent-color](https://www.w3.org/TR/css-ui-4/#widget-accent) does not and should not return the OS accent color scheme. The OS accent color may be used in place of accent-color to color form controls when accent-color is not specified or is set to auto, but the page should not be able to figure out what the OS accent color is due to fingerprinting.

In [this comment](https://github.com/w3c/csswg-drafts/issues/5187#issuecomment-789018527), @caraitto suggested that we should explicitly say in the spec that the OS color scheme cannot be determined by reading the accent-color property. Should we add it?

cc @fantasai @mfreed7

**Comment by josepharhar** [comment]
Great! @caraitto does this suffice?

**Comment by caraitto** [comment]
Sorry for the delay, yes that sounds fine.

**Comment by josepharhar** [comment]
> Sorry for the delay, yes that sounds fine.

Thanks!
