### ISSUE TITLE
[css-fonts] extend font-size-adjust to take a pair of values: <metric> <number>

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6160]
https://drafts.csswg.org/css-fonts/#font-size-adjust-prop

The idea of `font-size-adjust`, to take a meaningful metric for matching up the apparent visual size of disparate fonts, and harmonize it across whatever fonts end up getting used, is in principle a useful one. I think it has a few problems in practice, though:

(a) The meaning of the value is obscure; the ratio of ex-height to font size is not a number that designers are generally thinking about. `font-size-adjust: 0.5` sounds like it would halve the size of the font, but that's not at all what it does.

(b) It's difficult to come up with the appropriate value, even once its meaning is understood; you either have to dig around in font metrics to calculate it, or go by trial and error. We should have an `auto` value that gets the ex-height from the first available font, and then harmonizes everything else with it. (This has been proposed in #5539.)

(c) The big flaw is of course its Latin-centric nature; it is relying on a metric that isn't meaningful for most of the world's writing systems, and is unlikely to be set in a usefully equivalent way across lots of non-Latin fonts. We need alternatives that make sense for Arabic, Devanagari, Chinese, Mongolian, etc., etc.

So I propose we extend `font-size-adjust` to take two values, a ’metric’ and a number.

The ’metric’ value lets the author specify which of a number of font metrics is to be harmonized, instead of only allowing ex-height. So you could say

    font-size-adjust: ascent 0.8;

and the browser would adjust the sizing of all fonts to have an ascent value equal to 0.8em. Some other possibilities:

    font-size-adjust: ex-height 0.45; /* like current font-size-adjust behavior */
    font-size-adjust: cap-height 0.6; /* use cap-ht rather than ex */
    font-size-adjust: descent 0.3; /* less commonly wanted, probably, but no reason not to expose it */
    font-size-adjust: extent 1.0; /* scale so that total of ascent+descent equals 1em */
    font-size-adjust: ic-width 0.9; /* ideographic character advance, as per the ic unit */
    font-size-adjust: average-width 0.5; /* questionable how reliable this is, but no harm in making it available */

For any of these, the value `auto` means to derive the value from the first available font; in practice I suspect this would often be the most sensible choice for the value:

    font-size-adjust: extent auto; /* match total extent to first available font */

It's still not clear to me how well this would work across writing systems with radically different designs; e.g. trying to visually harmonize a Nastaliq Urdu font with a Latin fallback (let alone with, say, a Thai or Tibetan face), it's unclear that there is any specific metric that will give ideal results. But I think it would give designers quite a bit more control, and even for purely Latin content it may sometimes be more useful to match, for example, cap-height rather than ex-height.

**Comment by litherum** [comment]
@jfkthame spec edits are blocked on you providing a list of metrics which will be accepted as the first argument.

**Comment by fantasai** [comment]
We probably want to keep the names aligned with https://www.w3.org/TR/css-inline-3/#text-edges one way or another, btw.

**Comment by fantasai** [comment]
TMI about ideographic, but needs to be considered: there are multiple relevant metrics. They're mostly equal to 1em in _most_ fonts, but for non-square ideographic fonts they actually do differ.

The `ideographic` keyword in `text-edge` references the `ideo` and `idtp` baselines. The distance between these two would be what you'd want to measure if we imported it as a possibility for `font-size-adjust`. But technically, there are two metrics involved here, one from the horizontal writing mode tables and one from the vertical writing mode tables. If we add this value, we need to be clear that its computation depends on writing mode. But I'm not sure it's needed; afaik, it will almost always be 1em.

The `ic` unit references the ideographic character advance, specifically by pulling out the advance of 水. It responds to changes in writing mode so if you have a squat font it'll be longer in horizontal writing modes than in vertical ones. My suggestion would be to define `ic` likewise computing based on the writing mode. This means that `font-size-adjust` with the same font might calculate different adjustment factors depending on the `writing-mode`, if one of the fonts affected is non-square. But that's what will give the intended result of normalizing the advance.

We could also have `ic-height` and `ic-width` separately, but I suspect `ic-height` would be confused for the `ideographic` metric, and I'm not sure there's much of a use case for using an axis-specific value...

The third metric is the ideographic character face metrics, which correspond to the `icft` and `icfb` baselines and is typically slightly smaller than 1em. This metric is represented using the `ideographic-ink` keyword in `text-edge`, and is also what we use for drop-cap sizing. Normalizing these across fonts would account for varying amounts of built-in spacing / size of the character within the em square. I don't know how much this is a desired feature; it might be useful to ask people who work with CJK fonts.

**Comment by fantasai** [comment]
Suggested initial list: `ex`, `cap`, `ic`, `ch`. (With `ex` being the implied default, of course.)

I'm a little concerned about adding `ascent` or `extent`; a number of fonts have excess ascent to leave space for diacritics and stuff, and that extra space is a substantial proportion of the ascent of other fonts that cut the metric right at the Latin typographic ascent. So you'll get crazy results, depending on the fallback stack. (See slide 23 in https://fantasai.inkedblade.net/style/talks/vertical-rhythm/slides.pdf for an illustration.)

**Comment by astearns** [comment]
Let’s have @jfkthame (and possibly others?) respond here before we put this on the agenda again.

**Comment by jfkthame** [comment]
> Suggested initial list: `ex`, `cap`, `ic`, `ch`. (With `ex` being the implied default, of course.)

Yes, these seem a good starting point.

(Do we want to use these short names that look like units, or would it be more readable to use `ex-height`, `cap-height`, `ic-width`, `ch-width`?)
 
> I'm a little concerned about adding `ascent` or `extent`; a number of fonts have excess ascent to leave space for diacritics and stuff, and that extra space is a substantial proportion of the ascent of other fonts that cut the metric right at the Latin typographic ascent. So you'll get crazy results, depending on the fallback stack.

In general for visually harmonizing a mixture of fonts, it's more important to consider the height than the advance of the glyphs, so in practice I think `ascent` and `extent` are more useful measures than `ch` or `ic` (with the possible exception of monospaced situations where the desire is to maintain consistent advances -- which *does* often apply to CJK, of course, and so `ic` has its place).

It's true that results may be quite variable, depending how font designers have set their metrics; but that's a risk even with something as "simple" as ex-height, given that it is not always set accurately in fonts (just this week I ran into a case where the sxHeight field in the font was only about 1/3 of the actual ex-height of the glyphs, with the result that `font-size-adjust` makes that face huge). And when it comes to non-Latin faces, where any "ex" or "cap" height may be quite arbitrary, adjusting based on `ascent` or `extent` probably has *at least* as good a chance of being useful.

Moreover, I could imagine an author finding this useful for webfont resources, where `ascent-override` and `descent-override` could be used to determine what should be regarded as each font's "extent", overriding the whims of designers; then `font-size-adjust: extent <number>` would work nicely to harmonize multiple webfonts (e.g. a set of faces covering a range of different scripts).

(That would be largely equivalent to using `size-adjust` to tweak the scaling of each face, but expressing it in terms of setting the ascent/descent of each face and then letting `font-size-adjust` figure out the relationships might be convenient for a designer. It would also have the potential benefit of at least trying to do something reasonable with any system fallback font that may get involved, subject to the variability depending on how that font's designer chose to set the extent.)

So I'd be in favor of including `ascent` and `extent`, despite the fact that they'll be less than perfect.

**Comment by tabatkins** [comment]
Insofar as they match existing units I think just using the unit name makes a lot of sense.

**Comment by fantasai** [comment]
@jfkthame Given that one of the purposes (and therefore effects) of font-size-adjust is to also adjust any fallback fonts on the system, and you can't override their ascent/descent metrics, I think `extent` will end up being something that seems to work until it really really doesn't, and therefore probably isn't a good idea.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/1fae25fa283c708f7c71254b254a951cb3be3c63
