### ISSUE TITLE
[css-grid] Clarify `subgrid` when forced to establish independent FC

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#6164]
https://drafts.csswg.org/css-grid-2/#subgrid-listing defines `subgrid` with:

> If there is no parent grid, this value is equivalent to the initial value, `none`, and the grid container is not a subgrid.

I think this should also say that `subgrid` also behaves as `none` if the grid container is forced to [establish an independent formatting context](https://drafts.csswg.org/css-display-3/#establish-an-independent-formatting-context) (e.g. via `contain: layout`).

Because according to https://drafts.csswg.org/css-grid-2/#grid-containers

> a subgrid’s contents participate in its parent grid formatting context; thus a subgrid does not establish an independent formatting context.

**Comment by fantasai** [comment]
Fix checked in. @Loirooriol Close out the issue if it looks alright!
