### ISSUE TITLE
[css-grid] Clarify `subgrid` "equivalent" to `none`

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#6165]
https://drafts.csswg.org/css-grid-2/#subgrid-listing defines `subgrid` with:

> If there is no parent grid, this value is equivalent to the initial value, `none`, and the grid container is not a subgrid.

What does "equivalent" mean? Does `subgrid` compute to `none` in that case? Or is it just at used-value time?

In Firefox it's the latter: if you use `inherit` in a child grid, you do get a subgrid. [Testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Adiv%20%7B%20display%3A%20grid%3B%20grid-template-columns%3A%20subgrid%3B%20grid-auto-columns%3A%20100px%3B%20%7D%0Adiv%20%3E%20div%20%7B%20grid-auto-columns%3A%2010px%3B%20%7D%0Aspan%20%7B%20background%3A%20cyan%3B%20%7D%0A%3C%2Fstyle%3E%0ATEST%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20inherit%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%0A%3Cbr%3E%0ASUBGRID%20REFERENCE%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20subgrid%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%0A%3Cbr%3E%0ANESTED%20GRID%20REFERENCE%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20none%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E)

However, what's the computed value, then? The spec table says

> Computed value: the keyword `none` or a computed track list

Where https://drafts.csswg.org/css-grid-2/#computed-track-list

> The computed track list of a standalone axis is a list alternating between line name sets and track sections, with the first and last items being line name sets.
> 
> The computed track list of a subgridded axis is the subgrid keyword followed by a list of line name sets representing each line in that axis.

However, if `subgrid` behaves as `none`, there is no subgridded axis?

**Comment by fantasai** [comment]
Thinking about it some more, maybe it shouldn't behave as none, but instead do something like have the right number of explicit rows and columns but size them all using `grid-auto-*`? That might be more useful to authors while doing development, since at least the items will have the correct relationship to each other even if the tracks aren't sized appropriately: treating as `none` means the grid would collapse down to a single auto-flowed column. CC @jensimmons @rachelandrew

**Comment by Loirooriol** [comment]
How do you find "the right number of explicit rows and columns"?

**Comment by fantasai** [comment]
@Loirooriol If the grid has span values, could take it from that. If not, and it has line names, could guess from that. And otherwise default to one track.

On further reflection, though, and discussing with @jensimmons, it's probably better if the subgrid layout just disintegrates when it's not in a parent grid, to make it more obvious that something significant is wrong.

**Comment by fantasai** [comment]
Anyway, to answer your questions:
> What does "equivalent" mean? Does subgrid compute to none in that case? Or is it just at used-value time?

Generally speaking, if we don't say “compute” anywhere, the computed value is not affected.

 > However, if subgrid behaves as none, there is no subgridded axis?
 
I think you're technically correct. Not sure how to reword things cleanly... here's an attempt:

```diff
diff --git a/css-grid-2/Overview.bs b/css-grid-2/Overview.bs
index 292862de7..a15d8be75 100644
--- a/css-grid-2/Overview.bs
+++ b/css-grid-2/Overview.bs
@@ -1557,7 +1557,7 @@ Explicit Track Sizing: the 'grid-template-rows' and 'grid-template-columns' prop
                        Excess <<line-names>> are ignored.
 
                        If there is no [=parent grid=],
-                       this value is equivalent to
+                       the [=used value=] is
                        the initial value, ''grid-template-rows/none'',
                        and the [=grid container=] is not a [=subgrid=].
 
@@ -2011,7 +2011,8 @@ Flexible Lengths: the ''fr'' unit</h4>
 <h4 id='computed-tracks'>
 Computed Value of a Track Listing</h4>
 
-       The <dfn>computed track list</dfn> of a [=standalone axis=]
+       For a [=track list=] specifying a [=standalone axis=],
+       the <dfn>computed track list</dfn>
        is a <a spec=infra>list</a>
        alternating between [=line name sets=] and [=track sections=],
        with the first and last items being [=line name sets=].
@@ -2023,14 +2024,18 @@ Computed Value of a Track Listing</h4>
 
        * a ''minmax()'' functional notation representing a single track's size,
                with each <<length-percentage>> computed
+               (a <dfn>computed track size</dfn>)
        * a ''repeat()'' functional notation representing a repeated track list section,
                with its <<integer>> computed
                and its <<track-list>> represented as a [=computed track list=]
+               (a <dfn>computed repeat notation</dfn>)
 
-       The [=computed track list=] of a [=subgridded axis=]
+       For a [=track list=] specifying a [=subgridded axis=],
+       the [=computed track list=]
        is the ''subgrid'' keyword followed by
        a <a spec=infra>list</a> of [=line name sets=]
-       representing each line in that axis.
+       and [=computed repeat notations=]
+       representing the line names specified for that axis.
 ```

**Comment by Loirooriol** [comment]
But the above doesn't seem to clarify the computed value?

I mean, if when there is no parent grid, `subgrid` doesn't define a subgridded axis (so it's standalone), then how does work?

> For a track list specifying a standalone axis, the computed track list is a list alternating between line name sets and track sections, with the first and last items being line name sets.

Which track sections, if the syntax is `subgrid <line-name-list>?`, without track sizes?

I don't know, maybe the axis should be subgridded at computed value time, but standalone at used value time?

Or just saying that `subgrid` computes to `none` may be simpler.

**Comment by fantasai** [comment]
> I mean, if when there is no parent grid, subgrid doesn't define a subgridded axis (so it's standalone), then how does work?

It's specifying a subgridded axis, you just don't actually get one, is how I'm thinking about it. Open to alternate phrasing, if you have a better suggestion. You are a co-editor of this module, after all. :)

> Or just saying that subgrid computes to none may be simpler.

I'm not sure it matters much from an authoring perspective either way, but the only existing implementation doesn't do this...

**Comment by fantasai** [comment]
Committed an attempt at rephrasing. Open to other suggestions.

**Comment by Loirooriol** [comment]
I think it's fine after avoiding the computed value dependency. Then whether an axis is subgridded is only known at used-value time.
