### ISSUE TITLE
[css-contain] How does @container resolve when no ancestor containers have been defined?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6178]
Conditions in the `@container` rule currently query the _nearest ancestor with appropriate containment_ for each element selected inside the conditional block. If there are no ancestors with appropriate containment, we could simply consider it a false condition. 

On the other hand, we might be able to fallback to a query of the viewport or `:root` element. That fallback would behave similar to a media-query, though possibly with advantages (like access to the actual root font-size, rather than the browser default). On first glance, that seems like the best option. It means that container queries always have an implicit container, and always respond to the best of their ability. But in some cases it sets up a false assumption that the viewport size has _anything at all_ useful to provide, or can be substituted directly in a useful way.

I expect authors to run into issues either way, but:

- If we do not provide an implicit fallback, authors can always add root containment to create their own
- If we do provide an implicit fallback, authors don't have any way to _avoid it_ without creating more nested containers

Based on that, I might be leaning towards _no implicit fallback root_.

**Comment by kizu** [comment]
I vote for an implicit fallback root option.

My reasoning: with MQ it is a common practice (questionable, but exists) to define all the styles only for the appropriate scopes. If someone would apply this for the CQ, then if they would have an explicitly defined container, the styles would work perfectly. However, in case the container would lose its containing property or the component would be inserted somewhere without it, the styles would stop from working completely (or would lose some important parts if some of the common styles were moved outside of the CQ, but the important parts were divided by width scopes only).

On the other hand, I can't think of a use case where authors would want to avoid the implicit fallback.

> If we do not provide an implicit fallback, authors can always add root containment to create their own

I find this a false assumption, if we're looking at a single component separated from any context, it can't set the containment around itself on its own. Making it so the authors are **required** to set the containment in every case makes the components much less reusable.

**Comment by mirisuzanne** [comment]
I took [this question to Twitter yesterday](https://twitter.com/MiriSuzanne/status/1387535566535725057), and the conversations have been interesting. A few things to note:

- There is a common first-instinct to expect a root/viewport as a fallback. It is, in many ways, the outermost container on a page, and reasonable to think about it that way.
- As people dig in, there are some clear problems with responding to the root/viewport, which will likely return much larger dimensions than are actually available to a given component. If authors take a mobile-first, progressive-enhancement approach to their queries, the "small-screen" default (without queries) will be a "safer" fallback in many cases. We can see this in the [codepen demo by @dvdherron](https://codepen.io/dvdherron/pen/YzpywrZ), by changing the selector on the first block of CSS to `html`, or removing it entirely). In this case the default without queries behaves better than a root fallback. It seems like there are many cases where a root fallback could make things worse. 
  ![three blockquotes responding to different sized containers - small, medium, and large](https://user-images.githubusercontent.com/104161/116590123-a20c8b00-a8da-11eb-8cb7-bf6aa7b14a84.jpg)
  ![the same quotes in the same containers, but all using the largest version based on viewport size, so the quote in the smallest container is very squished](https://user-images.githubusercontent.com/104161/116590119-a0db5e00-a8da-11eb-9a64-82e789d0511b.jpg)
  ![all three quotes using the smallest layout, so there is sometimes extra space, but none of them are clearly broken](https://user-images.githubusercontent.com/104161/116590111-a042c780-a8da-11eb-8634-1216c16d08aa.jpg)
- Still, many people have other reasons that they want to set containment on the root. While media-queries rely on "viewport" values (default browser em size, etc), a root container query may be responsive to actual font size (using ems in the query), or [other properties and states](https://github.com/w3c/csswg-drafts/issues/5989) of the root element. 

I don't think either approach will "just work" as a fallback in all situations, but my conclusion here is:

- We should allow root containment, but
- We should leave it up to authors to apply as they see fit
