### ISSUE TITLE
[css-color-5] Is color-adjust() needed, now that we have relative color syntax?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#6179]
Originally, [`color-adjust()`](https://drafts.csswg.org/css-color-5/#coloradjust) was the only way to modify a starting color in carefully specified ways. However, we've since added the [relative color syntax](https://drafts.csswg.org/css-color-5/#relative-colors), doing something very similar.

In fact, as far as I can tell, relative color syntax *completely subsumes* color-adjust(). At least in the current grammar, color-adjust() can only adjust a single channel (tho there's a good chance we'll change that; see [Lea's comment](https://github.com/w3c/csswg-drafts/issues/6142#issuecomment-813678225)), and it can only do so as a % adjustment. Relative color syntax, on the other hand, can adjust all the channels at once, and can do arbitrarily complicated mathematical adjustments to them, including but definitely not limited to % adjustment.

It also just seems a little easier to read, in my opinion: compare `color-adjust(lch, red h 20%)` vs `lch(from red l c calc(h * .2))`.

I think at this point, addressing the issues with `color-adjust()` (allowing multiple channels, allowing more complex mathematical adjustment) would just be bringing it into alignment with relative color-syntax, not giving any additional features.

**Comment by LeaVerou** [comment]
Indeed, originally (check out the June 2019 F2F minutes) they were meant as alternatives of which we'd only keep one, but the editors have been so far unsuccessful in converging to one of the two. 

Note that your two examples are not equivalent: the adjusters in `color-adjust()` are relative, so `20%` I believe *increases* lightness by 20%, just like `-20%` reduces it. Though that lack of clarity may be another argument against it…

Note that both of these are mid-level (`color-adjust()` being slightly more high level than RCS), and we do eventually need a lower level syntax that will enable use cases like combining channels from different colors etc. Based on the research on Sass usage that I've done for the Almanac (see #5782), it seems that what authors are using in preprocessors are functions to get individual color components (e.g. `lightness($color)`), which seems a good path forwards, though we'd need to prefix them by color space (except `alpha()`).

**Comment by tabatkins** [comment]
> Note that your two examples are not equivalent: the adjusters in color-adjust() are relative, so 20% I believe increases lightness by 20%, just like -20% reduces it. Though that lack of clarity may be another argument against it…

Yeah I noticed that afterward. I think that behavior might be fine in a vacuum, but in conjunction with relative color syntax, it's def confusing.

> [discussion about extracting channels]

Yup, that's definitely a separate thing to talk about (and I agree, a good idea).

**Comment by svgeesus** [comment]
> Originally, color-adjust() was the only way to modify a starting color in carefully specified ways. However, we've since added the relative color syntax, doing something very similar.

Note that these were **both added at the same time**, [per CSSWG resolution](https://lists.w3.org/Archives/Public/www-style/2019Jul/0008.html). The spec also explicitly notes that we intend to merge, modify, or drop so that we end up with one final way, rather than two ways.

**Comment by svgeesus** [comment]
> I think at this point, addressing the issues with color-adjust() (allowing multiple channels, allowing more complex mathematical adjustment) would just be bringing it into alignment with relative color-syntax, not giving any additional features.

I agree. The main missing function in RCS is a relative version of `color()`. Although, since we simplified `color()` by dropping the fallback list, that task looks simpler.

**Comment by LeaVerou** [comment]
> > I think at this point, addressing the issues with color-adjust() (allowing multiple channels, allowing more complex mathematical adjustment) would just be bringing it into alignment with relative color-syntax, not giving any additional features.
> 
> I agree. The main missing function in RCS is a relative version of `color()`. Although, since we simplified `color()` by dropping the fallback list, that task looks simpler.

Note that in another issue I proposed `@color-profile` should have a descriptor to specify component names. This would allow us to have RCS for custom color spaces (and we can just predefine for the predefined spaces).

**Comment by svgeesus** [comment]
@LeaVerou  wrote:

> Note that in another issue I proposed @color-profile should have a descriptor to specify component names. 

This descriptor has [been added](https://drafts.csswg.org/css-color-4/#descdef-color-profile-components)

> This would allow us to have RCS for custom color spaces (and we can just predefine for the predefined spaces).

Relative color syntax for the ``color()`` function has also [now been added](https://drafts.csswg.org/css-color-5/#relative-color%E2%91%A0), which references the ``components`` descriptor in the case of ``dashed-ident`` as color space.

@tabatkins wrote:

> Relative color syntax, on the other hand, can adjust all the channels at once, and can do arbitrarily complicated mathematical adjustments to them, including but definitely not limited to % adjustment.

Yes. It is (with the latest additions) strictly more powerful, arguably easier to read too.

I think the draft should be published with the current state of both `color-adjust()` and `RCS`; but we are now close to being able to decide the ultimate single way forward.

**Comment by svgeesus** [comment]
[Color 5 was published 1 June](https://www.w3.org/TR/css-color-5/) with both `color-adjust()` and the full RCS; since that publication the ED has gained a section on [Serialization](https://drafts.csswg.org/css-color-5/#serial) for RCS, `color-contrast()` and `color-mix()` (see https://github.com/w3c/csswg-drafts/issues/6206 ).

Before I put effort into serialization of `color-adjust()`, or work on related issues https://github.com/w3c/csswg-drafts/issues/6180 https://github.com/w3c/csswg-drafts/issues/6181 https://github.com/w3c/csswg-drafts/issues/6141 let's have some more discussion and, ideally, resolution of this present issue.
