### ISSUE TITLE
[css-text-3] hyphenation priority

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#618]
The spec already says this:

> Automatic hyphenation opportunities within a word must be ignored if the word contains a conditional hyphen (&amp;shy; or U+00AD), in favor of the conditional hyphen(s). However, if, even after breaking at such opportunities, a portion of that word is is still too long to fit on one line, an automatic hyphenation opportunity may be used. 

This is good, but the same logic should be applied to words that have a hard hyphen in them. If we are facing "ex-patriation", it should be first hyphenated as "ex-" and "patriation", even if the word is in a hyphenation dictionary with additional hyphenation points listed.

**Comment by Crissov** [comment]
No, this doesn’t work well enough for all languages, e.g. German “E-Mailadresse” preferably breaks between ‘l’ and ‘a’. After U+002D, there probably is a preferred hyphenation point (unless there’s just a single letter in front of it), but a hard hyphen, unlike a soft hyphen, is no indication that the author’s trying to manually provide all acceptable hyphenation opportunities.

**Comment by SebastianZ** [comment]
According to [duden.de](http://www.duden.de/sprachwissen/rechtschreibregeln/bindestrich#K26) "E-Mailadresse" is incorrect. According to the rule there, all words *must* be separated by hyphens, so the correct spelling for it is ["E-Mail-Adresse"](http://www.duden.de/suchen/dudenonline/e-mail-adresse).

But ["Mailadresse"](http://www.duden.de/rechtschreibung/Mailadresse) (without the "E-") is obviously valid and your rule applies to it. I.e. while hyphenation is valid between every syllable, it's preferred between word boundaries.

Sebastian

**Comment by Crissov** [comment]
Take German state names as an example then, e.g. _Nord·rhein-West·falen_ and _Baden-Württem·berg_ with secondary hyphenation points indicated by `·` (and tertiary ones omitted).

**Comment by frivoal** [comment]
@Crissov Not sure what your example is supposed to illustrate. I think you are disagreeing with my suggestion, but the way I read your example, since the `·` are secondary hyphenation points, it means that the `-` are primary ones, which then matches what I suggested.

**Comment by Crissov** [comment]
These are possible results according to your spec quote:

    Nordrhein-
    Westfalen

    Nord-
    rhein-
    West-
    falen

but these hyphenations would also be acceptable, although not preferred:

    foobarbaz Nord-
    rhein-Westfalen

    Nordrhein-West-
    falen foobarbaz

According to the quoted text, there *must* not be breaks at `·` unless there’s already a break after `-`, which here results in an extra line and more whitespace at the end of the lines than necessary:

    foobarbaz 
    Nordrhein-
    Westfalen

    Nordrhein-
    Westfalen
    foobarbaz

**Comment by frivoal** [comment]
I see, makes sense.

Do you think we could go with something like this then:

> Hyphens (U+002D and U+2010?) contained in the word should be treated as higher priority than automatic hyphenation opportunities, unless the language-appropriate hyphenation resource explicitly contradicts this.

Another way to say the same thing would be:

> If language-appropriate hyphenation resource does not contain information about the priority of automatic hyphenation opportunities relative to hyphens (U+002D and U+2010?) contained in the word, the later must be treated as having higher priority.

On the other hand, regardless of the hyphenation resource or the rule above, if an implementation of line breaking does not have a general concept of levels of priority for soft wrap opportunities, then the above rule does not mean much. In that case, should we prefer treating all hyphenation opportunities the same, or applying to hyphens the same logic as to soft hyphens? I'd favor the later, but this is not obvious.

Also, it seems to me that the concept of prioritized hyphenation opportunities is at odds with the [hyphenate-limit-zone](https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-zone) property from level 4. As currently defined, it seems to require that parts of words be pulled back from the subsequent line to fill the current one (up to a limit specified by the property), and that does not seem to allow for prioritization. Maybe that should be changed to also have an auto value that would allow for prioritization, and/or to have two values rather than one: one that indicates the minimum amount of left-over space before you're allowed (but not required) to hyphenate, the other one being the maximum amount of left-over space before you're required to hyphenate even if that means using low priority hyphenation points.

(This may be a separate issue. Should I file it separately?)

**Comment by Crissov** [comment]
It sounds better, but I’d need to reread the rest of the spec and think a bit more about it than I can right now. Perhaps there could be something about syllabic vs. morphemic vs. lexemic hyphenation opportunities to specify language-dependent priorities.

**Comment by frivoal** [comment]
Agenda+ing, because this should be addressed as part of the css-text-3 disposition of comments.

**Comment by frivoal** [comment]
The resolution is to leave this and questions of hyphenation prioritization undefined and up to the UA.

The parallel with &amp;shy; was mistaken, because &amp;shy; is used to explicitly override incorrect dictionary based hyphenation, which isn't true of regular hyphens.
