### ISSUE TITLE
[css-color-5] How exactly does the hue adjuster in color-adjust() work?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#6180]
In ['color-adjust()`](https://drafts.csswg.org/css-color-5/#coloradjust), the spaces with hue have a hue-adjuster that looks like (grammar folded together):

`hue [shorter | longer | increasing | decreasing | specified ]? <percentage>?`

This seems odd in at least two ways.

1. Adjusting a hue by percentage seems like it's a domain error. Hue is a circular range; it doesn't have a *meaningful* zero to adjust toward or away from. In HSL, `blue hue 50%` changes the hue from 240deg to 120deg, but `green hue 50%` adjusts it from 120deg to 60deg; I don't think there's a meaningful sense in which green is "half" of blue, or yellow is "half" of green.

2. The shorter/longer/etc keyword seems to not do anything? That keyword is for choosing between several behaviors of interpolating between two hues; that doesn't appear to be relevant here. The spec just refers to the definition of the keywords, but doesn't explain what they actually do, or have an example of it.

**Comment by svgeesus** [comment]
Closed by WG resolution to [drop `color-adjust()`](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914)
