### ISSUE TITLE
[css-color-5] What exactly is the behavior of the % adjuster in color-adjust()?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#6181]
All of the adjusters in [`color-adjust()`](https://drafts.csswg.org/css-color-5/#coloradjust) are defined to take a `<percentage>`. There's no spec text defining what that % actually *does*, however.

The sole *example* appears to indicate that the % is directly added/subtracted from the value: `color-adjust(peru lightness -20%)` has its effect explained as "adjusted lightness is 62.2532% - 20% = 42.2532%", a straight subtraction of 20% (x - 20%), rather than a reduction *to* 20% (x * .2) or a reduction *by* 20% (x * .8).

There's nothing *theoretically* wrong with this behavior, but it doesn't carry over to non-% channels, like "hue". This needs to be well-defined.

-------

(Or we can just drop color-adjust() and let the much more obvious (imo, at least) behavior of using calc() on channels from the relative color syntax handle all of this. See #6179.)

**Comment by LeaVerou** [comment]
See [my comment](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-814203475) on #6179.

**Comment by tabatkins** [comment]
I'm not sure how that comment addresses this topic? Could you elaborate?

**Comment by LeaVerou** [comment]
I was agreeing with your last sentence:

> Though that lack of clarity may be another argument against it…

**Comment by svgeesus** [comment]
Closed by WG resolution to [drop `color-adjust()`](https://github.com/w3c/csswg-drafts/issues/6179#issuecomment-871569914)
