### ISSUE TITLE
[css-cascade-3] Add Security & Privacy appendix

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#620]
Please consider adding a Security & Privacy Considerations appendix, at a minimum with answers to the Security & Privacy questionnaire.

https://www.w3.org/TR/security-privacy-questionnaire/

In particular we need to at least say something about @import and CORS, and perhaps interaction with CSP. That has potential (likely) to add normative requirements for implementations. If it's "too late" to add any such normative requiements, they should at least be added as informative guidance, and then made normative in css-cascade-4.

If it helps, I can try answering it and submitting a pull request accordingly.

**Comment by SebastianZ** [comment]
This is part of issue #207.

Sebastian

**Comment by fantasai** [comment]
Let's put some actual text here.

**Comment by fantasai** [comment]
Tab committed some changes for this to https://drafts.csswg.org/css-cascade-3/#priv-sec
Agenda+ for WG review.

**Comment by svgeesus** [comment]
In general the text there looks good to me; I haven't checked much for things which should be there but are not.

Although, _perhaps_ [Script Execution](https://www.w3.org/TR/security-privacy-questionnaire/#string-to-script) could apply, if a externally imported stylesheet causes some custom code or Houdini APIs to be called? Although I think CORS would apply to that script.

**Comment by svgeesus** [comment]
Thanks for the explanation @tabatkins makes sense to me.
