### ISSUE TITLE
should it be possible for an element with contain:paint to be part of a transform-style:preserve-3d scene?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#6202]
Right now the specs [for `contain:paint`](https://drafts.csswg.org/css-contain-1/#containment-paint) and [for `transform-style`](https://drafts.csswg.org/css-transforms-2/#transform-style-property) allow an element with `contain: paint` to be part of a 3D scene.  If such an element both has `transform-style: preserve-3d` *and* has a parent that does, then this means that its children (or further descendants, if the children have `transform-style: preserve-3d`) are rendered as part of its parent's (or further ancestor's, if the ancestor chain has `transform-style: preserve-3d` further up) 3D scene.

While the intended guarantees of `contain: paint` aren't clearly defined, it seems a bit nonintuitive to me that it would allow children to escape the container in this way.

What is the desired behavior here?

**Comment by frivoal** [comment]
I'm not sure. Given that paint-contained element cannot have visible overflow, is there really an issue?
If I understand correctly, their content would get positioned into the ancestor's 3D scene, but whether they get painted or not is still depends on whether they overflow the bounds of the containing element, as it would with any other ancestor with overflow:clip. (in the case of non-clip, non-visible overflow, the problem doesn't arise, as the other values cause flattening).

If this is a misunderstanding, and elements that are part of a 3D scene do not get clipped at the boundaries of an overflow:clip element, then I suspect the correct answer is to add `contain: paint` to the list of property/value pairs that force the element to have a used style of flat for preserve-3d in https://drafts.csswg.org/css-transforms-2/#grouping-property-values

**Comment by chrishtr** [comment]
Contain:paint's clip is the same as an overflow:clip. I don't remember why that restriction is there in the transforms spec, can we just make overflow:clip a grouping property?

**Comment by tabatkins** [comment]
I agree that `contain:paint` should be a grouping property, yes.

And I think it makes sense for `overflow:clip` to be one too; it's not clear to me why it would make sense, or what it would mean, for a clipped-overflow element's descendants to be able to escape it in 3d.

**Comment by smfr** [comment]
Filed issue 6373 on `will-change: contain` and stacking context.

**Comment by dbaron** [comment]
To follow up on this mornings discussion -- I noticed that the compositing spec [says](https://drafts.fxtf.org/compositing-1/#csscompositingrules_CSS) (for HTML but not SVG):

> Everything in CSS that creates a stacking context must be considered an ‘isolated’ group.

This makes the results I'm seeing in [my test](https://dbaron.org/css/test/2018/stacking-context-z-order) make a lot more sense -- but then I no longer understand what the distinction is between a stacking context and a grouping property.  Is it a distinction that's only relevant to SVG?

**Comment by frivoal** [comment]
Fixed the spec in https://github.com/w3c/csswg-drafts/commit/4ab5eede9d9ead25796c2ef8fe64ccc90e2f42d2. Opened a separate issue (#6374) to follow up on `overflow: clip`.

If any other subthread of this issue needs continued discussion, I suggest opening a separate issue.

@dbaron, if that seems fine by you, can you close the issue?

**Comment by dbaron** [comment]
Seems fine to me.
