### ISSUE TITLE
[css-color-5] Clarify serialization of color-mix()

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6206]
In the recently added color-mix() test in WPT, https://github.com/web-platform-tests/wpt/blob/master/css/css-color/color-mix-basic-001.tentative.html, Firefox and WebKit already disagree on the results.

Firefox (and the test, since it was imported from Firefox) is currently serializing the result of a color-mix in srgb as:

```css
color-mix(in srgb, blue, red  50%)  -> rgb(128, 0, 128)
```

whereas WebKit is serializing it as:

```css
color-mix(in srgb, blue, red  50%)  -> color(srgb 0.5 0 0.5)
```

I chose the `color(srgb ...)` syntax serialization for WebKit for two reasons.

1. The use of `srgb` as the color space in the `color-mix()` gave it symmetry.
2. The use of the `color(srgb ...)` syntax gives more precision in WebKit, and therefore a mix could be more precise.

Either way, I think this should be clarified in the spec.

(Side note, I have a bunch of tests for [color-mix()](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-color-mix.html), [color-contrast()](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-color-contrast.html), and [relative color syntax](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-relative-color-syntax.html), but have not proposed them for WPT since the specs were still actively moving targets, but if they would be useful, I would be happy to make a PR for WPT.)

**Comment by emilio** [comment]
> (Side note, I have a bunch of tests for [color-mix()](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-color-mix.html), [color-contrast()](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-color-contrast.html), and [relative color syntax](https://trac.webkit.org/browser/webkit/trunk/LayoutTests/fast/css/parsing-relative-color-syntax.html), but have not proposed them for WPT since the specs were still actively moving targets, but if they would be useful, I would be happy to make a PR for WPT.)

I think this issue is a good argument for exporting them to WPT, even if as `.tentative`, as I did :)

**Comment by weinig** [comment]
> I think this issue is a good argument for exporting them to WPT, even if as `.tentative`, as I did :)

:) I agree, just want to double check with the editors.

**Comment by svgeesus** [comment]
@weinig wrote:

> I chose the `color(srgb ...)` syntax serialization for WebKit for two reasons.

> 1. The use of `srgb` as the color space in the `color-mix()` gave it symmetry.
> 2. The use of the `color(srgb ...)` syntax gives more precision in WebKit, and therefore a mix could be more precise.

I agree with point 1, and point 2 was accepted by WG Resolution and is now [explicit in the spec](https://drafts.csswg.org/css-color-4/#serializing-color-function-values):

> <p>For the predefined color spaces,
>	the <em>minimum</em> precision for round-tripping is as follows:</p>
   
color space | Minimum bits
-- | --
srgb | 10





> Either way, I think this should be clarified in the spec.

Yes, Color 5 needs a serialization section.

**Comment by svgeesus** [comment]
Yes, lets have the tentative tests committed to wpt

**Comment by svgeesus** [comment]
@weinig does [this look okay to you](https://drafts.csswg.org/css-color-5/#serial)

**Comment by weinig** [comment]
Sorry for the delay in response. 

This looks ok to me, but has one oddity, though I am not sure it is actual a problem and might be a good thing. The oddity is that normal `hsl()` and `hwb()` colors currently serialize as `rgb()`, and therefore this would be the first place where `hsl()` and `hwb()` are being serialized out. I actually prefer this, but I wanted to call it out as an interesting difference. WebKit doesn't currently do this, but supporting it would be trivial, and I am happy to update to this serialization.

We may also want to specify the minimum precision (number of bits-per-channel) for these forms as is done for the main color serialization - https://drafts.csswg.org/css-color-4/#serializing-color-function-values.

**Comment by svgeesus** [comment]
> this would be the first place where hsl() and hwb() are being serialized out. I actually prefer this, but I wanted to call it out as an interesting difference.

Good point and we should indeed discuss which outcome we want and why.

> We may also want to specify the minimum precision (number of bits-per-channel) 

Yes, good catch, we should.

**Comment by svgeesus** [comment]
> The oddity is that normal hsl() and hwb() colors currently serialize as rgb(), and therefore this would be the first place where hsl() and hwb() are being serialized out.

The more I think about this, the more it seems unintentional and should be replaced by a reference to the Color 4 serialization algorithm (which would mean `hsl()` and `hwb()` would serialize as `rgb(num num num)`)

**Comment by svgeesus** [comment]
Agenda+ as relevant to https://github.com/w3c/csswg-drafts/issues/7310

**Comment by svgeesus** [comment]
CSS Color 5 [already implements the resolution](https://drafts.csswg.org/css-color-5/#serial-color-mix)
