### ISSUE TITLE
[web-animations-1] Publish new Working Draft

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#6211]
Hi,

I would like to publish a new working draft of Web Animations level 1.

It has been over 2 years since the last working draft was published. In that time [the following changes](https://drafts.csswg.org/web-animations-1/#changes-since-last-publication) have been made:

* Made the definition of a current animation effect incorporate the associated animation’s playback rate (#3193).
* Updated the steps for resolving which properties to use when calculating [computed keyframes](https://drafts.csswg.org/web-animations-1/#computed-keyframes) when physical and logical properties are used.
* Introduced steps for removing animations that have been overridden: [§ 5.5 Replacing animations](https://drafts.csswg.org/web-animations-1/#replacing-animations).
   * Added a new [remove event](https://drafts.csswg.org/web-animations-1/#remove-event) to signal when this process occurs.
   * Added corresponding IDL members to the [`Animation`](https://drafts.csswg.org/web-animations-1/#animation) interface: `replaceState`, `onremove`, `persist`.
* Added the [`commitStyles`](https://drafts.csswg.org/web-animations-1/#dom-animation-commitstyles) method to the [`Animation`](https://drafts.csswg.org/web-animations-1/#animation) interface to allow preserving the result of an animation that has been removed.
* Added an [`options`](https://drafts.csswg.org/web-animations-1/#dom-animatable-getanimations-options-options) parameter to the [`getAnimations()`](https://drafts.csswg.org/web-animations-1/#dom-animatable-getanimations) method on the [`Animatable`](https://drafts.csswg.org/web-animations-1/#animatable) interface to allow fetching all animations on descendants of a particular element.
* Moved the definition of [`getAnimations()`](https://drafts.csswg.org/web-animations-1/#dom-documentorshadowroot-getanimations) from the `Document` interface to the `DocumentOrShadowRoot` interface mixin so that it can be used with `ShadowRoot`s as well.

As far as I know, all these changes have been implemented in all three major browser engines.

With regards to progressing the spec to REC, the last major issue is #5394 which all the major browser vendors have agreed upon. I have started on the spec/test/implementation work but it will take more time. After that, the remaining issues are hopefully minor.

I don't expect to be on the call unfortunately.

**Comment by birtles** [comment]
@fantasai I was wondering what "this" is from your comment:

> fantasai: Can we disable test harness, publish, and repub when we figure this out?

Is there something I need to disable before publishing the WD?

**Comment by tabatkins** [comment]
If you're on most current `main` of Bikeshed, the testharness annotations are disabled for CSSWG specs currently, so it'll work.

**Comment by birtles** [comment]
Thanks! I recently switched to installing bikeshed through `pip3` rather than a local checkout so I guess I'm not.
(I've updated it a few hours ago but `bikeshed --version` just returns `???`.)

**Comment by birtles** [comment]
I finally got a trunk version of bikeshed running. I fixed the dark mode colors from https://github.com/w3c/csswg-drafts/commit/95863149cdad6812d3038fe8aa8b4b6c623bc3a6 too since the validator didn't like `rgba()` without commas.

However, now I get stuck with `The document could not be published: Cannot read property 'message' of undefined`

Log here: https://labs.w3.org/echidna/api/status?id=66c32572-9e9a-4583-b819-0543b13837f7

@fantasai Any idea who I should ask?

**Comment by tabatkins** [comment]
Ooof, that looks like a bug in the publication code. @plehegar?

**Comment by svgeesus** [comment]
@birtles if it is still not working by Wednesday let me know and I will publish it manually. (Or try to, since we don't know what triggers the error)

**Comment by birtles** [comment]
@svgeesus Thanks! I just retried now and I get the same error ([log here](https://labs.w3.org/echidna/api/status?id=747352f8-4008-4973-a508-f220008ce2cf)).

(Note to self: When publishing in the morning in Japan, you need to add `Date: <yesterday's date in yyyy-mm-dd format>` or else Specberus complains, "The publication date of this document must be set to today".)

**Comment by svgeesus** [comment]
Hmm

> [EXCEPTION] The document could not be parsed, it's neither a TR document nor a Member Submission.
> [EXCEPTION] The document date could not be parsed.

Pubrules checker is unhappy :(

**Comment by svgeesus** [comment]
https://github.com/w3c/specberus/issues/1234

**Comment by birtles** [comment]
New WD is published: https://www.w3.org/TR/2021/WD-web-animations-1-20210518/
ED has been updated accordingly (or at least it will be once CI finishes running).
