### ISSUE TITLE
[css-color-4][css-color-5] Consistently spell as "color space"

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#6217]
The Color specs inconsistently spell the term as "colorspace" and "color space". Color 4 currently *prefers* "colorspace" (5x as many usages), but [Google Trends](https://trends.google.com/trends/explore?date=all&geo=US&q=%22color%20space%22,colorspace) suggests the internet in general slightly prefers "color space".

This impacts APIs - in <https://github.com/whatwg/html/pull/6562#discussion_r615015648> the 1-vs-2 word spelling is discussed so it's clear whether the camelCase spelling should be "colorspace" or "colorSpace". There's already a web api using "colorSpace", so the thread is settling on that.

We should be consistent and spell it "color space" across the Color specs as well. Even if there's some good reason to use "colorspace", keeping things consistent across the web APIs is important.

**Comment by tabatkins** [comment]
(Raising this as an issue just so @svgeesus can object if necessary; otherwise I'll happily make the edits.)

**Comment by svgeesus** [comment]
I'm less interested in what people use informally on the Web ad more interested in the correct technical term. Checking the indexes and glossaries of five books on color theory, color management, color appearance modelling and gamut mapping shows that _all_ have **color space** 

So, +1 to that.
