### ISSUE TITLE
[css-color-5] "color space" rename broke section ID and value space linking

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#6224]
See comments on the change in question:
https://github.com/w3c/csswg-drafts/commit/dc433b5b0bcd2a4bbfce046cbedb74eafe8d77ba#r49688047
https://github.com/w3c/csswg-drafts/commit/dc433b5b0bcd2a4bbfce046cbedb74eafe8d77ba#r49688231
https://github.com/w3c/csswg-drafts/commit/dc433b5b0bcd2a4bbfce046cbedb74eafe8d77ba#r49688389

**Comment by tabatkins** [comment]
fixed

**Comment by foolip** [comment]
Which commit fixed this? I can't see any commits in https://github.com/w3c/csswg-drafts/commits/main that seem related.

**Comment by tabatkins** [comment]
I haven't pushed the commit yet because I was fixing some other bits in another commit. ^_^ Sorry about that, pushed now.
