### ISSUE TITLE
[css-images-4] image() fragment cannot be created from var()

### ISSUE THREAD

**Issue by jsnkuhn** [w3c/csswg-drafts#6226]
The currently proposed image fragment syntax cannot be created from a css variable since css variables can't be used to create larger tokens.

Firefox's old -moz-image-rect syntax allows construction from css variables:
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-image-rect 

Codepen comparing `-moz-image-rect()` with the current proposed `image()`:
https://codepen.io/jsnkuhn/pen/JjEpbwy?editors=1100 

https://drafts.csswg.org/css-images-4/#image-fragments

**Comment by jsnkuhn** [comment]
maybe a `fragment()` function? Something similar to css clip-path like `rect()` or svg's `viewbox()` could be generalized for image fragment use?

**Comment by Loirooriol** [comment]
I guess #542 would allow this

**Comment by tabatkins** [comment]
Yup, this is basically a dup of #542
