### ISSUE TITLE
[css-pseudo] Can ::spelling-error and ::grammar-error occur anywhere?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#623]
https://drafts.csswg.org/css-pseudo/#highlight-selectors

Generally, spelling/grammar mistake markers are only expected in editable content. 

The behavior exhibited by chrome and safari (but not Firefox and Edge) in the following example feels like a bug to me. Something is editable and gets focused (and editted), so spelling mistakes get highlighted. Then when it is made non editable. I would expect the markers to go away, but they do not.

http://output.jsbin.com/caqusop

While I think that's wrong, there's nothing in the css-pseudo spec (or any other spec I am aware of) to support that opinion. Should there be?

Should we say that the ::spelling-error and ::grammar-error pseudos can only occur as children of editable elements, and the browsers must not highlight such things in non editable content?

Or should we instead say that browser can make them match anywhere, but mandate (or merely recommend?) a UA stylesheet that by default only highlights them when they are in editable content?
```
:read-write ::spelling-error {
  text-decoration: red dotted underline;
}
:read-write ::grammar-error {
  text-decoration: green dotted underline;
}
```

Or should we just leave it up to the UA, and report these against browsers separately not as a case of standards violation but as a case of bad UX?

**Comment by bradkemper** [comment]
It's a good point. I don't think "children of editable elements" is the right phrasing, since it should apply to deeper descendants too. But the spec should say that browsers must not apply that style to elements within editable content. 

I think browsers could still determine on their own if losing focus means that an element is no longer editable at that moment.

**Comment by frivoal** [comment]
> I don't think "children of editable elements" is the right phrasing, since it should apply to deeper descendants too.

You're right. Consider this a typo / mis-speaking. I did intend descendants, not children.

That said, having though about it some more, since descendants of editable elements are themselves editable in the general case (and if they're not, for example when contenteditable=false has been applied on them directly, they probably shouldn't get spelling or grammar error markers either), what we're looking for is probably applying to editable / user-alterable elements only, without consideration for ancestry.
I.e. `:read-write::spelling-error` and rather `:read-write ::spelling-error`

> I think browsers could still determine on their own if losing focus means that an element is no longer editable at that moment. 

That sounds fair to me.

**Comment by kojiishi** [comment]
This looks like already spec'ed in [Spelling and grammar checking](https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking):

> If checking is disabled, the user agent should not indicate spelling or grammar errors for that text.

so filing bugs to browsers looks reasonable to me. +@yosinch

**Comment by frivoal** [comment]
@kojiishi Thanks, I hadn't caught that. I agree this should solve the issue.
