### ISSUE TITLE
[css-fonts-3] Change @font-face and @font-feature-values syntax definitions to use CSS syntax and link to those definitions

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#624]
The current definition of the [`<family-name>`](https://drafts.csswg.org/css-fonts-3/#family-name-value) type is:

> The name of a font family of choice such as Helvetica or Verdana in the previous example.

And the [`<feature-index>` and  `<feature-value-name>`](https://drafts.csswg.org/css-fonts-3/#font-specific) types are currently defined like this:

>  … the @font-feature-values rule is used to define values for a specific font family or set of families that associate a font-specific numeric `<feature-index>` with a custom `<feature-value-name>`, which is then used in this property to select specific alternates

This is somewhat vague, as there are no references to the related [syntax definitions](https://drafts.csswg.org/css-fonts-3/#basic-syntax).

The definitions should be changed to use the syntax from the [CSS Syntax Module](https://drafts.csswg.org/css-syntax/).

I.e. they may look like this:

```
@font-face = @font-face { <declaration-list> }
```

where `<declaration-list>` can only contain the @font-face descriptors.

and

```
@font-feature-values = @font-feature-values <family-name># { <rule-list> }

<family-name> = <string> | <custom-ident>+

<feature-value-block> = <feature-type> { <declaration-list> }

<feature-type> = @stylistic | @historical-forms | @styleset | @character-variant | @swash | @ornaments | @annotation

<feature-value> = <integer>+
```

where `<rule-list>` can only contain `<feature-value-block>` rules, `<feature-type>` takes all font specific property names of `font-variant-alternates` prefixed with '@', `<declaration-list>` can only contain feature value definition properties holding `<feature-value>` values and the `<integer>` values in `<feature-value>` denote the feature indices.

The references to these syntax definitions should then link to them.

Sebastian

**Comment by tabatkins** [comment]
Updated @font-face and @font-palette-values.

@font-feature-values hasn't been moved to Fonts 4 yet, and I'm not about to go screw around with Fonts 3.

**Comment by svgeesus** [comment]
Yes, I need to port this over to Fonts 4, at which time it will use the CSS Syntax definitions.

We also resolved to remove @font-feature-values from Fonts 3 due to lack of two implementations, so that will deal with the obsolete syntax aspect for that part at least.

**Comment by svgeesus** [comment]
The relevant section now removed from Fonts 3. I'm editing the text now in Fonts 4 to use the syntax suggested in the initial post.
