### ISSUE TITLE
[css-foo]

### ISSUE THREAD

**Issue by RMKoRn** [w3c/csswg-drafts#6240]
* please tag the issue title with the spec's shortname, like `[css-foo]`
  (this is the name from the spec URL, without a level number unless the issue is specific to that level).
  If you're proposing a new feature that doesn't obviously fit in an existing spec, skip this part — don't make something up.

* please be specific (in the title and issue) about what you want to change:
  “make it better” means different things to different people!

* please link to the spec section you're talking about, or at least the spec

**Comment by RMKoRn** [comment]
i don't know what im doing im just doing something that web viewer ask me to do I apologize in advance for my actions. 
 Please send feedback by filing issues in GitHub (preferred), including the spec code “css-conditional” in the title, like this: “[css-conditional] …summary of comment…”. All issues and comments are archived. Alternately, feedback can be sent to the (archived) public mailing list www-style@w3.org. 
thats all i know im  trying to learn. thank you for your time. rmkorn

**Comment by RMKoRn** [comment]
i almost deleted it that was close

**Comment by astearns** [comment]
Do you have feedback for the css-conditional specification, @RMKoRn?

**Comment by RMKoRn** [comment]
no sir i wouldn't know what to say im sorry

**Comment by astearns** [comment]
No worries. Please use one of your own repositories to play around with the GitHub issue UI. There are several hundred people who are getting notifications every time you modify this issue.
