### ISSUE TITLE
CSS snapshot 2021

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6243]
Do we want the 2021 snapshot to be made early or late in the year? If early, we'd better get going soon.

(Note: for the 2020, we wanted to make it early, but failed, and it came out on December 22)

**Comment by fantasai** [comment]
Midyear seems like a good target, if it comes out in December I don't mind. :) But we should start tracking what we need to add.

**Comment by astearns** [comment]
Does anyone have proposed changes? Should any modules in the stable list from last year get promoted to “official”? 

https://drafts.csswg.org/css-2020/#fairly-stable

Or are there modules that should be promoted from or added to the rough interoperability list?

https://drafts.csswg.org/css-2020/#rough-interop

**Comment by svgeesus** [comment]
The stable definition is:

> The following modules have completed design work, and are fairly stable, but have **not received much testing** and implementation experience yet.

Given that, and looking at CSS Color 4 which has [two passes for most tests](https://test.csswg.org/harness/results/css-color-4_dev/grouped/), has undergone [wide review](https://github.com/w3c/csswg-drafts/issues/4943) and is being prepared for CR soon, I think it will soon be ready to move from **stable** to **official**

**Comment by svgeesus** [comment]
Also given the level of implementer interest and the [pretty good test results](https://test.csswg.org/harness/results/css-fonts-4_dev/grouped/) then CSS Fonts 4 should be added to the **rough interop** bucket.

**Comment by fantasai** [comment]
* Lists 3 might be ready for "rough interop"; other than marker-side it's mostly implemented.
* Counter Styles 3 might be ready for "official definition"?
* Logical Properties 1 should be in "rough interop"
* Unsure about the status of "overscroll-behavior", it's possibly ready for "rough interop"?
* css-position-3 should be in "rough interop"
* Scrollbars 1 should be in "stable with limited implementation"
* css-sizing-3 should probably be in "rough interop" rather than "stable" since it's not CR yet...
* resize-observer maybe goes in "rough interop"?
* web animations 1 could maybe go into "rough interop"?

**Comment by frivoal** [comment]
(date-adjusted placeholder at https://drafts.csswg.org/css-2021/)

**Comment by svgeesus** [comment]
> Also given the level of implementer interest and the pretty good test results then CSS Fonts 4 should be added to the rough interop bucket.

I see that hasn't happened, but don't see any arguments against it.

**Comment by svgeesus** [comment]
I have now massaged the snapshot to pass pubrules. However, the [linkcheck is failing](https://validator.w3.org/checklink?uri=https://www.w3.org/TR/2021/NOTE-css-2021-20211221/&recursive=on) because [drafts.csswg.org is down again](https://github.com/w3c/csswg-drafts/issues/6725)

**Comment by svgeesus** [comment]
Publication requested 19 Dec, expected 21 Dec

**Comment by svgeesus** [comment]
[CSS 2021](https://www.w3.org/TR/2021/NOTE-css-2021-20211221/) 21 Dec 2021
