### ISSUE TITLE
[css-contain-2] Used value of contain

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#6246]
The spec says that `content-visibility` can ["turn on"](https://drafts.csswg.org/css-contain-2/#skips-its-contents) layout/style/etc containment, but it's not clear what effect (if any) this has on the computed/used value of `contain`.

I think the most logical thing would be to specify that if `content-visibility` is such-and-such, then the _used_ value of `contain` becomes this-and-that, and specify that the resolved value is the used value.

I bring this up because the Blink implementation of `content-visibility` modifies the _computed_ value of `contain`, which seems heavy-handed. Introducing computed-value time dependencies between properties comes at a price. We should avoid doing so unless it's crucial.

cc @vmpstr

**Comment by emilio** [comment]
I agree, fwiw.

**Comment by tabatkins** [comment]
I agree it shouldn't alter the computed value, and didn't intend for it to. Do we really need to expose the active set of containments in gCS()? (I'm fine if we do need to, I just want to make sure there's a need and it's not just taken for granted.)

**Comment by tabatkins** [comment]
(My intention, fwiw, is that it had no effect whatsoever on the 'contain' property. An element having certain containments is just a quality it can possess, and the 'contain' property is *one* way of applying them, not the only way. But if we think it's useful to communicate the current set of containments, then doing so via the resolved value of 'contain' does indeed seem like the most straightforward way to do so.)

**Comment by andruud** [comment]
As far as I'm concerned, not affecting `contain` at any value stage is even better. You're right that I just took it for granted that we wanted to expose the active containments. I don't know if it's really needed. @vmpstr: Any thoughts on that?

> My intention, fwiw, is that it had no effect whatsoever on the 'contain' property

By default I would have interpreted the spec that way as well (after all it doesn't explicitly mention messing with the `contain` value). But the Blink impl. made me doubt what the intent was.

**Comment by vmpstr** [comment]
As long as the effects of containment still apply when the content-visibility spec says such containment is turned on (which is true), I don't really think we need to change `contain` value.

There may be a chance that developers rely on this as a way to know whether content-visibility: auto element is currently being skipped or not via presence of size containment. However, I don't think they should be, and the spec never intended that.

It seems like this is a "no change needed" for the spec, and simply a bug in Blink. WDYT?

**Comment by andruud** [comment]
> no change needed [...], bug in Blink

Works for me.
