### ISSUE TITLE
[css-display-3] Make it explicit that inlinification and blockification happen at computed value time

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6251]
[Inlinification and blockification](https://drafts.csswg.org/css-display-3/#transformations) describe a few transformations that happens to the value of the display property under some specific circumstances.

The spec does not specify if these changes are made to the computed or used value of the display property. (The one exception in that section being “a display of contents computes to block on the root element.”)  The note in that section claims that this is a computed value time transformation but I cannot find normative text to back it up. 

Given the note, and given that (as far as I can tell) implementations do indeed do that transformation at computed value time, it's probably worth saying so explicitly in normative text. Maybe just state something like:
> The transformations listed above change the [=computed value=].

**Comment by fantasai** [comment]
Note: There's a test for this and ruby in http://wpt.live/css/css-ruby/block-ruby-002.html
