### ISSUE TITLE
[css-pseudo] highlight pseudos and custom properties

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#6264]
https://drafts.csswg.org/css-pseudo-4/#highlight-styling

> [ISSUE 1] Are there any other properties that should be included here?

Should custom properties be allowed on highlight pseudos? What about use of cascading variables? If so, does the rule stating that non-inherited properties are to be treated as inherited, apply to [registered custom properties](https://drafts.css-houdini.org/css-properties-values-api-1/#the-propertydefinition-dictionary) where inherit = false?

I suppose these features are ok, given that we’ve completely isolated [highlight inheritance](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade) from originating element inheritance. As a result, defining or changing a custom property value should already be unable to “escape” and affect layout.

**Comment by delan** [comment]
(ping @frivoal, or maybe @fantasai?)

**Comment by tabatkins** [comment]
Ah yeah, custom properties should be allowed. Hm, we should make sure the same applies to other non-tree-abiding pseudos; custom properties should always be available.

(`var()` is always allowed; that's not restrictable. It just needs custom properties to be allowed to be meaningful. ^_^)

> If so, does the rule stating that non-inherited properties are to be treated as inherited, apply to registered custom properties where inherit = false?

Good question. Hm. I suspect yes, they should have the same fallback inheritance, for the same reason we fallback-inherit the existing properties. I wouldn't be broken-hearted if we decided the other way for impl reasons, but I'd prefer giving them the same behavior.

(Just to be clear for people, like me, who weren't aware of [this rule](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade): properties like 'background' don't inherit *normally*, but if nothing else defines them, they'll try to inherit from the parent *highlight* of the same type, so you can set 'background' on a block's highlight and the highlights within it will work as expected. This way you don't have to predict exactly what element to set things on.)

**Comment by delan** [comment]
Thanks @tabatkins! I think I’ll try to implement this [in Chromium](https://crrev.com/c/2850068), then come back and add this to the agenda.

For now it looks like we need two spec changes: [#highlight-styling](https://drafts.csswg.org/css-pseudo-4/#highlight-styling) should include custom properties in its list, and [#highlight-cascade](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade) should clarify that the “regardless” rule applies even to registered custom properties where [the inherit flag](https://drafts.css-houdini.org/css-properties-values-api-1/#determining-registration) is false.

**Comment by LeaVerou** [comment]
Are there any pseudos in which custom properties should *not* be allowed? If not, can we enable them on all of them in one fell swoop so we don't need to explicitly enable them for every pseudo-element?

**Comment by delan** [comment]
> Are there any pseudos in which custom properties should _not_ be allowed?

I’m not aware of any, for what it’s worth, but maybe some of the other members can say for sure.

**Comment by Loirooriol** [comment]
> Hm, we should make sure the same applies to other non-tree-abiding pseudos; custom properties should always be available.

And also to tree-abiding ones like ::marker. They aren't listed in https://drafts.csswg.org/css-lists/#marker-properties
