### ISSUE TITLE
[css-fonts] How does animation work with the extension of `font-size-adjust`?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6277]
This is a followup to https://github.com/w3c/csswg-drafts/issues/6160, where we resolved to extent `font-size-adjust` to accept the name of a metric (rather than only considering ex-height) in addition to a number.

It occurs to me that this raises a question for animation. Currently, the single value of `font-size-adjust` can be animated as a number; but once we extend the property to take a metric as well, what would it mean to animate between values that are based on different metrics - e.g. between `font-size-adjust: ex 0.4` and `font-size-adjust: cap 0.7`?

In principle it might be nice to compute the resulting used size of each character in the content, and animate this. But the result of `font-size-adjust` may be different on a per-character basis, depending on what fallback fonts actually get chosen, so the cost/complexity of this seems excessive for such an obscure case.

So I suggest that given the potential trickiness of implementation here, we just say that if the metric differs, the animation type falls back to discrete.

**Comment by emilio** [comment]
Yeah, animations generally happen at computed value time, so this is the most sensible option, IMO

**Comment by tabatkins** [comment]
Yup, agree. Match up the metrics or fail.

**Comment by svgeesus** [comment]
Retagging since [this is in Fonts 5](https://drafts.csswg.org/css-fonts-5/#font-size-adjust-prop)

**Comment by svgeesus** [comment]
Also closing because the spec already says:

> discrete if the keywords differ, otherwise by computed value type
