### ISSUE TITLE
[css-multicol] Should contained out-of-flow descendants affect column balancing?

### ISSUE THREAD

**Issue by mstensho** [w3c/csswg-drafts#6279]
Out-of-flow positioned boxes usually don't affect the size of their ancestors (with the exception of any scrollbars that an OOF might cause).

However:

```
<p>Should there be a yellow 100px tall multicol container below, with three
  columns, with one blue square in each?</p>
<div style="columns:3; background:yellow;">
  <div style="position:relative;">
    <div style="position:absolute; width:100px; height:300px; background:blue;"></div>
  </div>
</div>
```

Gecko and Blink show three blue squares in a 100px tall yellow multicol container here, i.e. the OOF affects the height of the multicol container. Is this how we want things?

**Comment by rachelandrew** [comment]
CodePen https://codepen.io/rachelandrew/pen/30b942f144550fa53394da7cfa4cbafd
