### ISSUE TITLE
[css-contain] 'contain: stricter' like strict + style

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#6287]
#3280 marked `contain: style` as at-risk, and dropped it from the `strict` and `content` shortcuts.

But since #6272 it's no longer at-risk.

Do we need a new shortcut like `strict` but including style containment? Like `contain: stricter`?

I guess this could be useful for container queries, instead of having to specify `contain: layout size style`, just `contain: stricter` would do the trick.

Or maybe just change `strict` to include `style`? But it may be too late for compat.

**Comment by mirisuzanne** [comment]
This seems related to #6174 – creating an explicit syntax for query-containers.

If the purpose of style containment is currently only for container queries, I'm not sure that a variant of `strict` is either the most clear, or the most flexible for specifying 1d or 2d size containment variants.

**Comment by frivoal** [comment]
> Or maybe just change strict to include style? But it may be too late for compat.

Is someone able to run a query on sites that use `contain: strict` to determine how many would render differently if they were switched to `contain: layout style paint size`. In theory, it's different, so it could break things, but whether or not this actually causes problems in the wild is less certain, given than the effects of style containment are quite limited.

**Comment by frivoal** [comment]
Or maybe this is a good motivation to reopen https://github.com/w3c/csswg-drafts/issues/5506 and take the alternative resolution there.

**Comment by mrego** [comment]
[In the discussion when `style` was marked as *at risk* dropped from `strict`](https://github.com/w3c/csswg-drafts/issues/3280#issuecomment-467588765), @tabatkins suggested that we'd later will have to add `contain: all` to include `style`. I kind of like more `all` than `stricter`

Though what @frivoal said about usage on the wild might get us a chance to just add it back again, dunno.

**Comment by chrishtr** [comment]
I think the best thing would be to re-add `style` to `strict`, if it's web compatible. I'd be willing to try this for Chromium, I think there is a very good chance it will not be a problem.
