### ISSUE TITLE
[css-fonts-4] Unclear text in 2.2 "Font weight"

### ISSUE THREAD

**Issue by PeterCon** [w3c/csswg-drafts#629]
Section: https://drafts.csswg.org/css-fonts-4/#font-weight-prop

The following sentence is unclear:
"Most user agents model a font has having a particular weight which often corresponds to the list above."

Guessing at the intended meaning, the following wording is proposed:

"Most user agents model a font as having a particular weight which often corresponds to one of the numbers in the nine-step scale mentioned above."

**Comment by litherum** [comment]
You are right. Feel free to create pull requests for these kinds of issues.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/3fcbf9f035123d411cca1a740d16aae6221a3a25
