### ISSUE TITLE
[css-overscroll] Whether to move position:fixed elements during overscrolling

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#6299]
As of now, Chrome and Safari move position:fixed element during overscrolling and Firefox does (since [bug 1704503](https://bugzilla.mozilla.org/show_bug.cgi?id=1704503)) to match their behavior. But WebKit thinks it's [a bug](https://bugs.webkit.org/show_bug.cgi?id=206227).

**Comment by hiikezoe** [comment]
CC @smfr

**Comment by smfr** [comment]
One question is whether they move at all. The other question is whether that is detectable by the page (e.g. via getBoundingClientRect()).

**Comment by bmathwig** [comment]
Would it be possible to revive this discussion? The Microsoft Edge PWA team has a use-case where fixed position elements not being included in the overscroll effect would be beneficial.

**Comment by smfr** [comment]
We currently consider it a bug that WebKit moves fixed elements on over scrolling.

**Comment by bmathwig** [comment]
Edge will also treat it as a bug and fix accordingly. @atanassov Can we add this as an agenda item for resolution in a future WG meeting? It might be as simple as making a note in the spec about it.

**Comment by bmathwig** [comment]
Link to Chromium changes for this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=585766#c26

**Comment by flackr** [comment]
> One question is whether they move at all.

I think that is the main issue being questioned here. My opinion is that as fixed pos elements do not move with scroll they probably also shouldn't move with overscroll. However, this could make certain kinds of affordances challenging - e.g. if the browser wants to show some information at the top in the "revealed" part of the page the fixed pos elements may occlude this.

> The other question is whether that is detectable by the page (e.g. via getBoundingClientRect()).

I don't have strong opinions, though it is important that on android we stretch during overscrolling which would be even more awkward to represent. I think overscrolling could be considered purely a UA effect with no developer visible effect - this is what Chrome does right now.

**Comment by chrishtr** [comment]
> I don't have strong opinions, though it is important that on android we stretch during overscrolling which would be even more awkward to represent. I think overscrolling could be considered purely a UA effect with no developer visible effect - this is what Chrome does right now.

+1 that it shouldn't be developer-exposed.

**Comment by chrishtr** [comment]
Re JS APIs: currently, Gecko and Chromium's implementations of overscroll do not affect any developer APIS, and are purely a "UA affordance" in that sense.

Overscroll implementations differ between platforms (e.g. I know of at least 3 approaches: rubber-band/translate [iOS/Mac], stretch [Android current], glow [old Android]), and it's good to allow UAs to try out different affordances.

Pull-to-refresh was a use case @smfr mentioned as being helped by the current negative scroll offfset approach in Safari.

Therefore, I propose:
* Specify that overscroll does not affect any JS APIs
* Solve pull-to-refresh (which I agree is worth solving) with other APIs that will be independent of the approach to overscroll, and work on platforms without overscroll affordances

**Comment by flackr** [comment]
> * Solve pull-to-refresh (which I agree is worth solving) with other APIs that will be independent of the approach to overscroll, and work on platforms without overscroll affordances

And platforms with different overscroll affordances which are not translations (i.e. at this point, Android)

**Comment by smfr** [comment]
So if we specify that overscroll does not affect any JS APIs, then it becomes impossible for a page to use JS to position an element with fixed-like behavior during overscroll. Is that OK?

**Comment by chrishtr** [comment]
> So if we specify that overscroll does not affect any JS APIs, then it becomes impossible for a page to use JS to position an element with fixed-like behavior during overscroll. Is that OK?

I think that's ok in general.

If there are specific compelling use cases that are not yet solved, we can solve them with new CSS properties or other APIs. Do you have one in mind other than pull-to-refresh?

**Comment by jonjohnjohnson** [comment]
What about #4011 & #3801?

**Comment by chrishtr** [comment]
> What about #4011 & #3801?

#4011 ("Should overscroll ("rubber-banding") be observable?") would be closed as WontFix if we go with the approach I'm suggesting.

For #3801 ("Content has no way of understanding whether it is being overscrolled or whether scroll has ended"), I'm suggesting we add APIs focused on common use cases, such as pull-to-refresh, and solve them holistically, taking into account all relevant factors, including overscroll.

**Comment by atomiks** [comment]
This is a nice change 👍  

However, I think this should also apply to `position: sticky`. In Chrome Canary, the "fixed" elements on [this page](https://docs.github.com/en/get-started) still move with the page scroll as they use `position: sticky`.

**Comment by flackr** [comment]
> However, I think this should also apply to `position: sticky`. In Chrome Canary, the "fixed" elements on [this page](https://docs.github.com/en/get-started) still move with the page scroll as they use `position: sticky`.

This was part of the resolution https://github.com/w3c/csswg-drafts/issues/6299#issuecomment-1076552713, it's just not fully implemented yet. As long as the containing block doesn't prevent it sticky elements should be free to shift with the overscroll as well.
