### ISSUE TITLE
[css-multicol] Add examples of columns in vertical text

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#6301]
https://www.w3.org/TR/css-multicol-1/

The i18n WG was glad to see that the spec mentions that column directions are logical and will look different in vertically set text.  Thank you.  However,  the text describing that could be missed if you blink, and therefore we would like to suggest the addition of a note which gives examples of columns in both Japanese and Mongolian, just to ensure that implementers (and content authors) have a clear picture of how this should work.

The note should probably introduce the idea that columns run horizontally in vertically-set text, and explain that the block flow direction can vary. It may also be an opportunity to remind readers that 'width' refers to the length of the text line, rather than the physical horizontal width of the column.

There should probably also be tests for vertically set text (maybe there already are?).

Here are a couple of images you could use as illustrations.  It might be good to add arrows indicating the reading direction, but we supply the images raw for now.

Japanese (columns read RTL):

![Screenshot 2021-05-21 at 10 55 01](https://user-images.githubusercontent.com/4839211/119120358-18a53000-ba24-11eb-9d24-07ab270a8468.png)

Mongolian (columns read LTR):

![columns_horizontal](https://user-images.githubusercontent.com/4839211/119120444-307cb400-ba24-11eb-9a2d-d6d4b14179b2.png)

**Comment by xfq** [comment]
Related info in *lreq documents:

* [clreq](https://w3c.github.io/clreq/#major_differences_between_horizontal_and_vertical_writing_modes)
* [jlreq](https://w3c.github.io/jlreq/#fig_ad1_19)
* [klreq](https://w3c.github.io/klreq/#para-diffs)
* [mlreq](https://www.w3.org/International/mlreq/#h_columns)

**Comment by macnmm** [comment]
Could also include Chinese newspaper example with both RTL for body text and LTR for captions…

**Comment by rachelandrew** [comment]
@frivoal the above issue was raised with regard to the horizontal review on multicol, this is very much your area. Happy to do create and add an example, but I just wanted to ping you for your thoughts on what might be best to include before I draft something.

**Comment by acli** [comment]
The issue with Chinese is more complicated. I grew up with papers that had RTL vertical text with RTL heads (whether horizontal or vertical). I used to work in a newspaper publisher (quite a while ago) and was told because there’s no horizontal RTL support in layout software, people actually typeset the RTL heads by typing the heads backwards.

We also now have even LTR vertical text (it’s been at least a decade now, if not longer) and obviously, there’s no layout software that can do this because non–Chinese speakers wouldn’t know there’s such a thing.

**Comment by frivoal** [comment]
While it's nice to show that columns in a vertical text are a thing, this is a sufficiently complicated and subtle topic I'm not sure we should get too far into vertical text questions in the multicol spec. Something like the Mongolian example above is probably fine, as it's just multicol in vertical, but the earlier Japanese example involves page floats, and getting into mixed writing modes example with some text being vertical and some being horizontal, and dealing with whether the horizontal bits are LTR or RTL seem way out of scope for multicol. If we want a vertical-rl example as well, it should be something rather simple only involving multicol (possibly with spanners), to avoid overwhelming the reader.

I am a firm proponent of making sure all these things work and of enabling complex examples with mixed writing modes and mixed conditionality, but I don't think multicol is the right place to get into that.

**Comment by acli** [comment]
I don’t think the Japanese example is complicated. There’s no concept of RTL Japanese in Unicode (it’s not done in Japanese these days in any case, as far as I understand; RTL horizontal text is only an issue in traditional Chinese), so ignoring the floated figure, all we have is a head followed by an RTL div in four columns. It isn’t really any more complicated than the Mongolian example.

**Comment by r12a** [comment]
While i agree that the Japanese example isn't complicated, i also agree that the heading is not relevant here, and need not be in the example. The point of the example is solely to remind implementers that the flow of _multi-column text_ will be different in vertically-set documents.   

How about just using a schematic such as the following, where the middle represents Japanese/Chinese, and the right is Mongolian

![Screenshot 2021-06-24 at 08 44 38](https://user-images.githubusercontent.com/4839211/123223240-a1eacf00-d4c8-11eb-9f87-9189866bacf0.png)
:

**Comment by rachelandrew** [comment]
@r12a I like that, I think it demonstrates how it should work without introducing additional complexity that doesn't really belong in this spec.

**Comment by rachelandrew** [comment]
@r12a I added images as requested, let me know if this is a satisfactory resolution. Thank you!

Added as example 12, in the section The Multi-Column Model: https://drafts.csswg.org/css-multicol/#the-multi-column-model

**Comment by r12a** [comment]
Thanks, the note and figure look good to me.

(The arrows in the figure seem to be at an angle.  It may be a visual illusion, or may be intended.  Not particularly important, but i was curious.)
