### ISSUE TITLE
[css-contain-3] What happens when the queried dimension is not contained by the nearest container?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6303]
When we have nested containers, with different contained axes, do we only query the nearest container -- or do we query the nearest container _which has the proper containment_? For example:

```html
<style>
  @container (block-size >= 100px) {
    p { background: green; }
  }
</style>

<html style="contain: size layout style; block-size: 200px;">
  <main style="contain: inline-size layout style">
    <p>query</p>
  </main>
</html>
```

1. If we query the nearest ancestor that is a container (`main`), the match is `false` because the block-size is not contained, and cannot be queried
2. If we look for the nearest ancestor _with block containment_  (`html`), the match is `true` because the block size matches the given condition

I _think_ in this case we want option 2, and should only consider an ancestor to be "a container" if it meets all the required containment criteria. But maybe I'm missing something?

@andruud @lilles - do you have thoughts on this?

**Comment by lilles** [comment]
What if you have multiple conditions whose closest container with the necessary containment is different?:
 
```css
@container (block-size >= 100px) and (inline-size >= 100px) {}
```

**Comment by mirisuzanne** [comment]
Yeah, that concern makes sense to me - I don't think we should go down that path. If we allow queries to search for proper containment, then the individual queries act as an implicit way of selecting their own containers. That could get pretty complicated, and hard to debug.

In which case, it's may be even more important that you are [able to name containers, and query them explicitly](https://github.com/w3c/csswg-drafts/issues/6176).
