### ISSUE TITLE
[css-color-adjust] viewport propagation of forced-color-adjust

### ISSUE THREAD

**Issue by alisonmaher** [w3c/csswg-drafts#6307]
We propagate `background-color` from the root/body to the viewport. However, we don't similarly propagate `forced-color-adjust`, which can lead to unexpected results in forced colors mode.

For example, in the following case, we propagate a `background-color` of red to the viewport in forced colors mode because `forced-color-adjust` is set to `none`. However, because colors are now forced at used value time, when we re-resolve the background color at the viewport, we end up forcing the background to `Canvas`, since `forced-color-adjust` at the viewport computes to `auto`.
```
<style>
  :root {
    background-color: red;
    forced-color-adjust: none;
  }
</style>
```

The proposal would be to propagate `forced-color-adjust` to the viewport, as well, since the used value of `background-color` is dependent on `forced-color-adjust`.

It was resolved in issue #6079 that "No future properties should propagate from body". So, if we decide to only propagate `forced-color-adjust` from the root and not the body, are we ok with the following case resulting in a non-red background in forced colors mode?
```
<style>
  body {
    background-color: red;
    forced-color-adjust: none;
  }
</style>
```

**Comment by fantasai** [comment]
@alisonmaher Edits checked in, let us know if it looks OK!

**Comment by alisonmaher** [comment]
@fantasai Looks good to me, thanks!
