### ISSUE TITLE
[css-color-5] Add target luminance contrast keywords AAA and AAA-large to color-contrast()

### ISSUE THREAD

**Issue by BillGoldstein** [w3c/csswg-drafts#6311]
[[css-color-5]](https://drafts.csswg.org/css-color-5/#colorcontrast) Add target luminance contrast keywords **AAA** and **AAA-large** to color-contrast(),
where AAA=7 and AAA-large=4.5 as per [WCAG2.1 Success Criterion 1.4.6 Contrast (Enhanced)](https://www.w3.org/TR/WCAG21/#contrast-enhanced)

**Comment by svgeesus** [comment]
Good catch, I don't know why I missed those out, sorry.
