### ISSUE TITLE
[css-variables] Empty custom property (--) works in every browser, against spec

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6313]
[Per spec](https://drafts.csswg.org/css-variables/#defining-variables), the `--` custom property is reserved by CSS for future use:
> The `<custom-property-name>` production corresponds to this: it’s defined as any `<dashed-ident>` (a valid identifier that starts with two dashes), **except `--` itself, which is reserved for future use by CSS**.

However in my testing it works in every browser ([testcase](https://codepen.io/leaverou/pen/vYxZWYj)), as yet another property, and is already used by people in situations where brevity is important (it was brought to my attention from a https://cssbattle.dev solution ).

What should we do? Should we file bugs with all UAs and hope for the best, or change the spec?

Related:
* https://dev.to/afif/what-no-one-told-you-about-css-variables-553o#10-they-can-have-strange-syntaxes
* https://stackoverflow.com/questions/67066696/is-a-valid-css3-identifier

ping @tabatkins

**Comment by Loirooriol** [comment]
This was resolved in #2692

> RES0LVED: Reserve -- for future use and it is not a valid custom property name

But if implementations didn't change, it may be too late for compat?

**Comment by tabatkins** [comment]
Resolved, and editted in a few months later, both in 2018 <https://github.com/w3c/csswg-drafts/commit/45929663250db0e805ae6ecdac136307e6c8163d>.

I strongly suspect that `--` isn't used in practice on real sites, just on those code golfing sites. I think breaking them is perfectly fine. ^_^  On a real site, variable usage is setting things with nice names so they're understandable elsewhere in the stylesheet, and `--` is antithetical to that.

**Comment by bradkemper** [comment]
Is there a way to get data about how much it is actually being used? Seems like we are just guessing so far.

**Comment by LeaVerou** [comment]
Yes, we could query HTTPArchive data. That should be a pretty easy thing to query.

**Comment by emilio** [comment]
I wrote a Firefox patch here: https://bugzilla.mozilla.org/show_bug.cgi?id=1467309. It'd be great if someone could check httparchive, though I suspect this should be fairly low-risk... @tabatkins, do you know how could I check it?

**Comment by LeaVerou** [comment]
I’m not Tab, but since I'm involved with HTTPArchive and to my knowledge he is not, I hope it's ok if I answer?

I have already asked them, the problem is their last dataset of parsed CSS is from 2020 due to a bug. If we're fine getting data from August 2020, we could get it now, otherwise we'd need to wait a few months.

**Comment by emilio** [comment]
Ah, for sure Lea, thanks so much! I didn't know you were involved with HTTPArchive :)

**Comment by emilio** [comment]
(I think data from 2020 _might_ be fine, custom properties have been working for a long time)

**Comment by LeaVerou** [comment]
So, in the 2020 dataset it's only used in 4 pages ([link](https://discuss.httparchive.org/t/how-prevalent-are-empty-custom-properties-in-css/2153/2)), so if this trend has not changed then there's no compat issue at all.

**Comment by emilio** [comment]
Thanks a lot lea! I checked those pages and even though they do stuff like `--:0rem` they don't seem to reference `var(--)` or `var(--,` anywhere, so there's no rendering change on those pages, which is great. I'll try to land my patch and if it sticks it should be in Firefox 91.

**Comment by tabatkins** [comment]
Yeah, August 2020 should be fine for compat data, thanks so much for diving into that, @LeaVerou!

Thanks for experimenting, @emilio; assuming it sticks we can close this no change (and I can file more bugs).

**Comment by tabatkins** [comment]
The fourth url found by httparchive is in fact using `--` in exactly the way I intended, as an `all` for variables, so that's nice. ^_^

**Comment by ExE-Boss** [comment]
## Status updates
<dl>
<dt>Firefox</dt><dd>

Fixed in **Nightly**.
</dd>
<dt>Chrome</dt><dd>

Has an open bug to fix this: <https://crbug.com/1220145>
</dd>
</dl>
