### ISSUE TITLE
[css-contain][filter-effects] paint containment vs filter effects

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6325]
The intent of paint containment is (among other things) that:
> If the containment box is off-screen or obscured, the UA can directly skip trying to paint its contents, as they’re guaranteed to be off-screen/obscured as well.

That doesn't seem to account for [filter effects](https://drafts.fxtf.org/filter-effects/). If you put a blur filter (for example) on an ancestor of an element of paint containment, it can spread the pixels of the contained element beyond the geometry of that element, with no particular boundary. So the contained element may be off-screen, but you still need to repaint it so that the on-screen pixels of the parent with a filter an be rendered correctly.

Is this OK because filters are a composite-time operation rather than paint-time operation, or something like that?

Is this bad and we somehow forgot to take it into account?

**Comment by chrishtr** [comment]
Paint containment is only for the contents, not the element itself. Filters from content will be clipped. So I think it's WAI.

**Comment by frivoal** [comment]
Filters *from* the content will be clipped, but filters from parents will need to take into account changes in the content, even if that content is offscreen, which seems to me to break the guarantee that if some paint-contained element is off-screen, you can skip repainint it even when the content changes.

**Comment by chrishtr** [comment]
> Filters _from_ the content will be clipped, but filters from parents will need to take into account changes in the content, even if that content is offscreen, 

Why is that? The source rect for the filter takes into account any clipping of content, so the contain:paint clip should prevent this from happening.

**Comment by frivoal** [comment]
> The source rect for the filter takes into account any clipping of content, so the contain:paint clip should prevent this from happening.

The source rect takes into account clipping, so pixels that would be out of the contained element before filters are applied are clipped and not taken into account by the filter, and that's fine, but the filter itself spreads things around, without being limited to clipping on descendants.

Here, for instance, I have a paint-contained element with a red background, with a blur filter on the parent of the container applied when you hover. Also a blue line overlayed on top to see where the boundaries of the element with containment are. No red leaks out of the contained element normally, but some amount of red can be seen outside of that boundary when you hover and apply the blur filter.

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=9421

Here, it's the same idea, but nested within an element with overflow hidden with a black border. Things are sized so that the (unblured) red square with paint containment is just out of view. If you hover the document, it gets blurred, and some red can be seen. And if you hover the black bordered box, the red background is changed to blue, and that can be seen too.

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=9422

So, In that example, I am changing the background color of an off screen element with paint containment, and I still need to re-render it to get the on-screen pixels correct. That seems to defeat the point of paint containment to me.

**Comment by frivoal** [comment]
cc: @tabatkins

**Comment by chrishtr** [comment]
I see, thanks for clarifying your concern.

> That seems to defeat the point of paint containment to me.

I don't think it defeats the point. The point is to contain the paint of the contents (i.e. descendants), not the element itself, so that we don't need to render the contents in order to know whether we need to do that work. We just need to determine the paint bounds of the element.

Determining the paint bounds of the contents is quite expensive, whereas determining the paint bounds of the element is not.
