### ISSUE TITLE
[CSS] scroll snap not working in [React]

### ISSUE THREAD

**Issue by oussama1478** [w3c/csswg-drafts#6327]
Hello, I tried to use scroll-snap CSS in the horizontal scroll (React Js) but is not working.

there is the code: https://codesandbox.io/s/frosty-solomon-2x80o?file=/src/App.js

**Comment by fantasai** [comment]
Hi @oussama1478, this is the repository for issues against the CSS specifications at W3C. If you want to file an issue against React, you should file it with them.
