### ISSUE TITLE
[css-fonts] Add COLRv1 keyword to `<color-font-technology>` production

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6329]
_Context:_ On the background of our plans to introduce COLR v1 color fonts we have requests from partner for feature detection for font formats, in particular COLRv1.

To the line
`<color-font-technology> = [COLR | SVG | sbix | CBDT ]`
I suggest to add a specific item `COLRv1` or `COLRV1`.

_Reasoning:_ Table version 1 brings a whole set of a new capabilities that differs from table version 0 graphical capabilities (think flexible vector graphics (v1) vs. stacked uni-colored glyph layers (v0)). UAs should be able to distinguish and load only the [right supported font based on the `supports` sequence of the `format()` function](https://drafts.csswg.org/css-fonts/#font-face-src-parsing) in the `@font-face` `src:` line.

**Comment by svgeesus** [comment]
Yes, there is a clear need to differentiate these due to the very different capabilities

**Comment by Lorp** [comment]
I agree it’s needed. Would it be a good idea to allow case-insensitive?

It also makes me think CSS would benefit from a generic versioning syntax for supported technology, such as `COLR>=1` (and maybe other operators [copied from npm](https://docs.npmjs.com/cli/v7/using-npm/semver#caret-ranges-123-025-004)).

**Comment by svgeesus** [comment]
> Would it be a good idea to allow case-insensitive?

The casing is just for readability of the specification (in ths case, the same spelling as OFF and OpenType); CSS keywords are ASCII-case-insensitive

> In the value definition fields, keywords
with a pre-defined meaning appear literally. Keywords are CSS identifiers and are interpreted ASCII case-insensitively (i.e., [a-z] and [A-Z] are equivalent).
[CSS values 4](https://drafts.csswg.org/css-values-4/#keywords)

**Comment by RoelN** [comment]
For clarity, options will be `COLR` and `COLRv1` — no `COLRv0`?

I hope there won't be more fragmented versions for color fonts (~four~ five versions are enough I hope), but if there will be versions like `COLRv1.0.17` in the future I like @Lorp's idea.

**Comment by svgeesus** [comment]
> For clarity, options will be COLR and COLRv1 — no COLRv0?

Unless we can get rapid implementer agreement to change `COLR` to `COLRv0` which would indeed be clearer.

The two are very significantly different, as you know (v1 has linear, radial and conic gradients, masking, and variable support) so they do need clearly distinct labels. .

As to splitting the labels into a token plus a numeric version, we don't have anything like that in CSS so coming up with a general numeric versioning scheme would likely delay the introduction of this by quite some time.

**Comment by svgeesus** [comment]
So I propose

`<color-font-technology> = [COLRv0 | COLRv1 | SVG | sbix | CBDT ]`

**Comment by Lorp** [comment]
Note that a COLRv1 implementation supports COLRv0, so "COLR" does make some sense. What did you think of the versioning syntax, @svgeesus?

**Comment by svgeesus** [comment]
> Note that a COLRv1 implementation must support COLRv0, so "COLR" does make some sense.

Until there is a COLRv2 which must support COLRv1 and COLRv0 and then we wish we hadn't used COLR.

The point is to be able to serve a COLRv0 font to an implementation that doesn't support COLRv1

> What did you think of the versioning syntax, @svgeesus?

See [above](https://github.com/w3c/csswg-drafts/issues/6329#issuecomment-855816954)

Speaking of versioning there is also , in OpenType 1.9, [a v0 and v1 of CPAL](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/cpal). But I guess that isn't an issue.

**Comment by drott** [comment]
+1 for 
`<color-font-technology> = [COLRv0 | COLRv1 | SVG | sbix | CBDT ]`
or 
`<color-font-technology> = [COLR | COLRv1 | SVG | sbix | CBDT ]`

Both work from Chrome's perspective. So far we did not support the `format() ... supports ...` syntax so we can add it with either `COLRv0` or `COLR`.

**Comment by svgeesus** [comment]
For those following along at home, [OpenType 1.9 COLRv1 definition](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/colr) which has nice pictures

**Comment by svgeesus** [comment]
```html
<pre class="prod"><dfn id="color-font-technology-values">&lt;color-font-technology&gt;</dfn
  > = [COLRv0 | COLRv1 | SVG | sbix | CBDT ]</pre>
```

**Comment by svgeesus** [comment]
@RoelN wrote:

> I hope there won't be more fragmented versions for color fonts (~four~ five versions are enough I hope)

A very fair point BUT

Two of those are raster formats which were introduced in a rush to get color emoji deployed on handsets. They are on the wrong side of history in my opinion, and are included here for completeness.

One of them is a vector format which does (on the plus side) have hinting but doesn't have much graphical expressivity and has no variable support.

One of them is a vector format which does (on the plus side) have graphical expressivity but doesn't have hinting and has no variable support. I also don't see easy ways to add the missing features.

So (and this may surprise some, given who is saying it) COLRv1 which is vector,  has hinting, has graphical expressivity, and most importantly has variable support is the clear winner on technical grounds and I can't wait to see wider support.

The choice between one color format which does it all and four which don't should be an easy one to make.

**Comment by RoelN** [comment]
> One of them is a vector format which does (on the plus side) have hinting but doesn't have much graphical expressivity and has no variable support.

If you're referring to COLRv0, this has variable support, right? See this [shit](https://pixelambacht.nl/demo/mrpoo/) here.

**Comment by svgeesus** [comment]
Variable for the color part, not just the glyph outline part

**Comment by RoelN** [comment]
Gotcha ✔️

**Comment by litherum** [comment]
This is fine.

**Comment by svgeesus** [comment]
Closing as resolved
