### ISSUE TITLE
[cssom-view] Merge visualViewport into working group

### ISSUE THREAD

**Issue by bokand** [w3c/csswg-drafts#6339]
Hi all,

The visualViewport proposal is now implemented and shipped in all of Blink, WebKit, and Gecko. I think it'd make sense to put it on a standards track at this point.

I imagine CSSOM-View is probably the right place but don't have a strong opinion. 

WDYT?

[Spec](https://wicg.github.io/visual-viewport/index.html)
[Explainer](https://github.com/WICG/visual-viewport)

**Comment by theres-waldo** [comment]
> <fremy> fantasai: one more comment
> <fremy> fantasai: it's a bit weird how things happened here
> <fremy> fantasai: we are not doing standardization, we are doing documentation
> <fremy> fantasai: I don't find this workflow appropriate
> <fremy> fantasai: so I agree to do it here, but it's worth nothing I think it is not a good workflow
> <fantasai> fantasai: It's too late to make any changes now, it's not exactly accurate to say you're shifting it to the CSSWG for the "standardization" process

Hi, I'm one of the Firefox engineers who worked on this feature.

For my future reference, could you clarify what, if anything, we should have done differently? Should we have kept the feature disabled by default until the W3C process completes? Should Chrome have done the same?

Thanks, and my apologies if we didn't follow the process correctly.

**Comment by tabatkins** [comment]
You were fine. The WICG document was produced with significant cross-browser discussion and agreement; that's the important part. Checking in with the CSSWG when producing a document intended to eventually be absorbed by the WG is good practice, to make sure there's wider review, but looking over your issues list I see a lot of familiar names, so I'm not too concerned about narrow review.  (This is *especially* true when doing new properties or values, as there's significant expertise in the WG that might not be shared by experienced engineers ouside the WG, but for a straightforward JS API like this it's much less of an issue.)

The only thing that might have been done slightly better is that it looks like this was shipped before any patent agreements covered it; that comes for free when publishing a Rec-track document in a WG, but has to be done manually in a CG with a separate agreement. (Maybe y'all did go thru that process; I can't tell without digging into your archives.) That's just exposing browsers to some potential risk, which is mitigated by having it published thru a WG with wide membership like ours.
