### ISSUE TITLE
[css-flexbox] wrong initial value for flex shorthand

### ISSUE THREAD

**Issue by raphaelgoetter** [w3c/csswg-drafts#634]
About CSS Flexible Box Layout Module Level 1 : 
https://www.w3.org/TR/css-flexbox-1/#flex-property

I think there's an error on Flexbox spec about `flex` shorthand initial value: it is set to "1 0 auto", but actually should be "0 1 auto" since:
-  `flex-grow` initial value is `0`
-  `flex-shrink` initial value is `1`
-  `flex-basis` initial value is `auto`

**Comment by SebastianZ** [comment]
This was already fixed in issue #183. The [latest editor's draft](https://drafts.csswg.org/css-flexbox/#flex-property) now just says "see individual properties".

Sebastian

**Comment by raphaelgoetter** [comment]
Hello,

The value seems still set to "Initial: 1 0 auto" on the previous link : https://www.w3.org/TR/css-flexbox-1/#flex-property

**Comment by fantasai** [comment]
Should be fixed now, sorry, took awhile to get it published. :)
