### ISSUE TITLE
[css-fonts] Drop bracket matching step from `@font-face` src: line parsing

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6340]
For context, the original resolution from which the spec text for parsing the `src:` line of the `@font-face` descriptor was tracked in issue #633. This issue is related to #6328.

The current [spec text says](https://github.com/w3c/csswg-drafts/blob/main/css-fonts-4/Overview.bs#L1880):

> The value of the 'src!!descriptor' descriptor is parsed piecewise.  First, opening and closing parentheses are matched. If these parentheses cannot be matched, the value is a parse error. Matching the parentheses has the effect of partitioning the value into multiple regions, each of which is either inside outermost parentheses or outside outermost parentheses.  Once the value is partitioned, all the commas outside outermost parentheses are located. The value is then split at these comma locations.

Why do we need the bracket matching? In my quick analysis, at least WebKit and Blink do not do that but the top level step for parsing the `src:` descriptors value is to split this into a comma separated list of values, then parse these individually. I am not so familiar with reading Rust code, but [it roughly looks like](https://searchfox.org/mozilla-central/source/servo/components/style/font_face.rs#380) Gecko parses this as a comma separated list at the top level as well? (@jfkthame, could you comment?).

I suggest to drop this text and explain that the first segmentation step is separating by commas, then parsing each individual value separately, unless I am missing something on why this might be needed. To me it seems this would not conflict with any of the second level parsing of individual source values. (It does not look to me as commas would have any other meaning in this descriptor except separating sources, do they?)

This would also address the TODO issue in the text and explain that after comma separation, values that are not parsed correctly are dropped from the list and not considered as downloadable resources.

**Comment by svgeesus** [comment]
Right, because after segmentation on commas the procedure is

> Each item in the split value is then parsed against this grammar:

and the grammar includes parentheses. Also [Fonts 3 didn't define parsing this way](https://www.w3.org/TR/css-fonts-3/#src-desc) so I suspect implementations just extended what they already had for Fonts 3.

@litherum you [added that section](https://github.com/w3c/csswg-drafts/commit/4d3684100754e06cf840a46b7d198df5066902dd) could you explain the reasoning?

**Comment by svgeesus** [comment]
Also [this resolution](https://github.com/w3c/csswg-drafts/issues/633#issuecomment-380469287):

> RESOLVED: Parse the value of src throwing out invalid parts like media queries and not like selectors. aka **You split on the commas** and throw out the pieces you don't understand not the whole thing.

**Comment by svgeesus** [comment]
I suspect the split on parantheses came about because [at one point](https://github.com/w3c/csswg-drafts/issues/633#issuecomment-339058646) we were considering syntax like

```css
@font-face {
  font-family: heading-font;
  src: url(fancy-font.woff2) format("woff2;tables=CPAL,FVAR"),
        url(fallback-font.woff2) format("woff2"),
        url(fallback-fallback-font.woff) format("woff"),
        url(how-old-is-your-browser-font.ttf) format("ttf");
}
```

Note the commas inside the overloaded format specifier.

But we ended up not doing that, so segmenting first on balanced parentheses no longer has any value.

**Comment by svgeesus** [comment]
Agenda+ in case there are any good arguments in favor of the balanced-parens initial step. Otherwise, I'm fine dropping that part to improve internal spec consistency and also better align with actual implementations

**Comment by jfkthame** [comment]
If the first step is to split on commas, what happens if there's a URL that includes a comma?

**Comment by svgeesus** [comment]
comma is in the set [`sub-delims`](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) which also says

> If data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

I guess that was never an issue for CSS Fonts 3, which didn't have the split-on-balanced-parens step?

**Comment by jfkthame** [comment]
I don't think @drott's original comment here:

> In my quick analysis, at least WebKit and Blink do not do that but the top level step for parsing the `src:` descriptors value is to split this into a comma separated list of values, then parse these individually

can be quite accurate, given that an example like:

```
@font-face {
  font-family: test;
  src: url(data:font/ttf;base64,AAEA[...snipped...]QjUA);
}
```

successfully loads the base64-encoded font resource in all of Safari, Chrome and Firefox. If they were splitting the `src:` value on comma as a *top-level step*, surely that wouldn't work. They'd end up seeing two items, neither of them complete or parsable.

**Comment by tabatkins** [comment]
I'll note that I added an algo to Syntax for this exact case (for other reasons) that behaves correctly, so the spec can just invoke that: <https://drafts.csswg.org/css-syntax/#parse-comma-separated-list-of-component-values>

**Comment by tabatkins** [comment]
(CSS specifications can't specify text-level parsing details anyway; by the time they *have* a value that they know is part of a particular property, it's already been tokenized and had basic parsing done on it, per spec. The above algo works at the correct level.)

**Comment by drott** [comment]
Thanks @jfkthame and @tabatkins for observations and clarifications. Of course, Jonathan, you're right that the data url scheme you're giving as an example does work. And it's also true that the CSS parsing operates on a token stream, not on a character stream.

What I looked at during my analysis for WebKit and Chrome were these bits of code for where a font face src descriptor is parsed:
ConsumeFontFaceSrc [Chrome](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/parser/at_rule_descriptor_parser.cc;l=140;drc=9de41c281bbe975c886fb14bc13b1df6c06f3864;bpv=1;bpt=1) and consumeFontFaceSrc in [WebKit](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/parser/CSSPropertyParserWorkerSafe.cpp#L247)

In particular, the behavior of the parser here consuming and progressing to each next value comma-token by comma-token. But indeed while still inner component values such as `url()` can contain commas which are consumed in nested parsing functions called `consumeFontFaceSrcLocal` and `consumeFontFaceURI`. So my earlier description of first separating by commas is not quite accurate. 

With that clarified, I am still convinced that the prose for separating by bracket matching should be dropped as that's definitely not what's happening or needed.

Because @tabatkins provides this very useful reference, as an additional improvement to the current text, we may want to refer to ["5.3.10. Parse a comma-separated list of component values"](https://drafts.csswg.org/css-syntax/#parse-comma-separated-list-of-component-values) as the algorithm for parsing this value, assuming that it's fully applicable: In that respect, are url(...) and local(...) defined as function tokens?

**Comment by tabatkins** [comment]
Yeah, per the Syntax spec, they definitely get parsed as function tokens. (Depending on its contents, `url()` might get parsed as a url-token, but for these purposes that's identical.)

**Comment by litherum** [comment]
The idea was just that I didn’t want “foo, bar(baz, quux)” to be broken into 3 pieces: “foo” “bar(baz” and “quux)”. If there’s logic elsewhere that already satisfies this desire, I’m happy to use it instead.

**Comment by drott** [comment]
Thanks for commenting, @litherum. To summarize, I suggest to improve this section by dropping 

> The value of the 'src!!descriptor' descriptor is parsed piecewise. First, opening and closing parentheses are matched. If these parentheses cannot be matched, the value is a parse error. Matching the parentheses has the effect of partitioning the value into multiple regions, each of which is either inside outermost parentheses or outside outermost parentheses. 

> Once the value is partitioned, all the commas outside outermost parentheses are located. The value is then split at these comma locations.

> Each item in the split value is then parsed against this grammar:

and instead say:

> The src: descriptor value must be parsed according to section ["5.3.10. Parse a comma-separated list of component values"](https://drafts.csswg.org/css-syntax/#parse-comma-separated-list-of-component-values). Then each component value is parsed according to this grammar: <grammar>

I also suggest to address "ISSUE 4" and the definition of "thrown out" by saying:

> If a component value is parsed correctly and is of a format and font technology that the UA supports, add it to the list of supported sources. If parsing a component value results in a parsing error or its format or technology are unsupported, do not add it to the list of supported sources. 

> If there are no supported entries at the end of this process, the value for the src: descriptor is a parse error.

**Comment by svgeesus** [comment]
Thanks for the suggested wording, @drott I just added it.

**Comment by drott** [comment]
Yes, I support resolving with this change. Unfortunately I have a conflict and can't attend today's call, but at least @lilles said they'd be there from our side.

**Comment by svgeesus** [comment]
@jfkthame okay to close this?

**Comment by svgeesus** [comment]
[the updated section of the spec](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing)

**Comment by jfkthame** [comment]
Yes, sounds OK to me.

**Comment by tabatkins** [comment]
+1 to committed change, but @svgeesus INCONSISTENT TABS AND SPACE INDENTATION???

You could also just link the algorithm directly with `[=parse a comma-separated list of component values=]`, but that's a nit.

**Comment by svgeesus** [comment]
Linking to the algorithm directly might well have been better, yes.

I'm aware that Tabs vs. Spaces is one of the _GREAT HOLY WARS OF OUR TIME_ and I am really not interested in signing up as a combatant.
