### ISSUE TITLE
[css-sizing-3] Add <marquee> to list of compressible elements

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6342]
Several of us were discussing compressible elements yesterday, and it was noted that `<marquee>` should be added to the list of compressible elements, since this is what seems to be implemented. If there's no objection to doing so, @tabatkins and I will add it to the list.

**Comment by tabatkins** [comment]
The core functionality of `marquee` seems to be fundamentally compatible with the notion of compressible, even ignoring the back-compat argument. ^_^
