### ISSUE TITLE
[mediaqueries] display mode media feature

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6343]
In https://github.com/w3c/manifest/issues/975, @marcoscaceres said:

>While the CSS crew is here, somewhat unrelated, but related, could we move "display mode media feature" to MQ5?

The current spec is over here: https://www.w3.org/TR/appmanifest/#the-display-mode-media-feature
Support according to MDN: 
![Screen Shot 2021-06-03 at 13 39 24](https://user-images.githubusercontent.com/113268/120587887-29689380-c471-11eb-84bd-0ce44999363c.png)

**Comment by frivoal** [comment]
I'd say that we should indeed merge it into the main MQ spec.

**Comment by marcoscaceres** [comment]
Great! Let me know if I can be of help in moving stuff over.

**Comment by frivoal** [comment]
Waiting for clarifications in https://github.com/w3c/manifest/issues/1023

**Comment by marcoscaceres** [comment]
Looking forward on your thoughts on the proposal in w3c/manifest#1023

**Comment by frivoal** [comment]
Publication has happened (since we're no worse off than we were before the transfer), so closing. Will follow up in the other issue.
