### ISSUE TITLE
[css-variables] Whitespace-trimming and custom properties.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6345]
Today, these things are invalid syntax per spec:

 * `--a:;`
 * `width: var(--b,);`
 * `width: var(--c,/**/);`

However these are valid:

 * `--a: ;`
 * `width: var(--a, );`

As per https://github.com/w3c/csswg-drafts/issues/774#issuecomment-313257194, we're supposed to trim whitespace from declaration values. I was looking at implementing this in Gecko (while I was going through CSS variables failures) and I think we should make the former examples also valid, if we want to keep the resolution in #774.

We should also consider trimming whitespace from the fallback value, too...

For reference, this contains the test changes: https://phabricator.services.mozilla.com/D116459

**Comment by tabatkins** [comment]
`--a:;` is valid per spec; <https://drafts.csswg.org/css-variables/#defining-variables> got changed [a while back](https://github.com/w3c/csswg-drafts/commit/258841cd179386b6300997926ed81be265b92317) to make the `<declaration-value>` optional.

I'm okay with making the other two valid; it would just mean putting in a specific exception to the [general comma-omission rules](https://drafts.csswg.org/css-values/#comb-comma).

**Comment by LeaVerou** [comment]
I agree that if `--a:;` is valid, then empty values should be valid as fallbacks. Otherwise you can end up with `var(--b,var(--a))` being valid or invalid based on whether there's whitespace after the comma!

**Comment by LeaVerou** [comment]
About trimming, one potential issue is that it could break uses of the [space toggle](https://css-tricks.com/the-css-custom-property-toggle-trick/) if JS is involved to read the variable value.

**Comment by emilio** [comment]
(FWIW there's a resolution, though `Resolved` was in lowercase so the bot didn't pick it up):

> Resolved: Accept the proposal
