### ISSUE TITLE
[css-overflow-4] rename scrollbar-gutter:both

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6349]
`both` refers to both-sides, but that may not be obvious to authors without reference to the specification or documentation. `both-sides` would be clearer, but longer. `symmetrical` is also clearer, but also longer and harder to spell. While still not as short, `mirror` might be a good compromise between length and understandability.

**Comment by tabatkins** [comment]
Definite 👎 on `symmetrical`, that double mm is a hard one.

I'm fine with `both-sides`, it's clear and obvious what it does

**Comment by frivoal** [comment]
Yeah, y and i and doubled consonants are a challenge.

You don't like `mirror`? That's my favorite by quite a bit

**Comment by tabatkins** [comment]
As a purely aesthetic judgement, I don't like it as much. Not particularly bothered by it, I suppose.

**Comment by felipeerias** [comment]
I would prefer `both-sides`, as it seems clearer than `mirror`.

In the context of CSS, the word "mirror" is often used to talk about transforms and similar effects, so it might be confusing to use it here to mean that something applies to both sides of an element.

@frivoal @tabatkins

**Comment by frivoal** [comment]
I like `mirror`, as I find it both short and clear, but I have no objection to `both-sides` either. Let's see what the group thinks.

**Comment by jonjohnjohnson** [comment]
> This property affects the presence of scrollbar gutters placed at the inline start edge or inline end edge of the box.

"Sides" feels somewhat linked to the horizontal axis, so when the logical inline axis is vertical, "sides" are the top/bottom edges?

I do agree that `both` doesn't seem clear enough. How about `balanced`, since it's about balancing the content in the center? Or `both-edges`, since "edge" is not only in the quote above, but also commonly used in relation to logical dimensions?

**Comment by mirisuzanne** [comment]
Is there a chance that we'll eventually want scrollbar gutters on the block axis, and if so, does that impact the naming here?
