### ISSUE TITLE
[css-grid-2] Subgrid and scrollbars

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6350]
css-grid-2 is explicit that the margin/border/padding of a subgrid gets taken into account in the sizing of its parent grid's tracks, and also that the overflow property does work on subgrids. However, it's not very clear that the size of the scrollbar gets taken into account as well.

Here's a bit of a contrieved example, first without a scrollbar:
```html
<div id=grid>
  <a></a><b></b>
  <div id=subgrid>
    <div id=item></div>
  </div>
</div>
<style>
#grid {
  display: grid;
  grid-template-columns: auto min-content;
  width: max-content;
}
#subgrid {
  display: grid;
  grid-template-columns: subgrid;
  grid-column: span 2;
  border-right: solid 16px orange;
  padding-right: 16px;
  background: yellow;
  height: 100px;
  overflow: clip;
}
#item {
  background: blue;
  height: 150px;
  width: 100px;
}
b {
  background: teal;
  height: 16px;
}
a {
  background: pink;
  height: 16px;
}
</style>
```
Assuming I understand the spec correctly, the expected rendering is:
![Screen Shot 2021-06-04 at 14 03 47](https://user-images.githubusercontent.com/113268/120748412-b2e59780-c53d-11eb-8a4e-6bf9df2107fc.png)

This is indeed what Firefox does, as you can see in http://software.hixie.ch/utilities/js/live-dom-viewer/saved/9360

Now, if we add `#subgrid { overflow-y: scroll; }`, I'd expect no difference to the layout in the case of overlay scrollbars, but in the case of classic scrollbars, I'd expect the scrollbar to be inserted between the yellow and the orange box, and which should make the the width of second grid column (and the teal box at the top) grow by the size of the scrollbar.

Assuming we agree on that, I'd also expect that
* if there was no padding or border on the subgrid, and only the scrollbar, it would still be in that second grid column, whose size would still take it into account.
* if we have `overflow-y: auto` rather than overflow scroll, the scrollbar would still be in that second grid column, whose size would still take it into account.

cc: @fantasai @Loirooriol

**Comment by Loirooriol** [comment]
This doesn't seem specific of scrollbars, it seems Firefox is not taking borders and margins into account either? Just the padding. [Testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cstyle%3E%0A%23grid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20width%3A%20max-content%3B%0A%20%20border%3A%20solid%3B%0A%7D%0A%23subgrid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20grid-template-columns%3A%20subgrid%3B%0A%7D%0A%23item%20%7B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border%3A%205px%20solid%20lime%3B%0A%20%20box-sizing-border-box%3B%0A%7D%0A%3C%2Fstyle%3E%0ABAD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22overflow%3A%20scroll%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%205px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%2015px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22margin%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cbr%3EGOOD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22padding%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E)

**Comment by emilio** [comment]
cc @aethanyc

**Comment by frivoal** [comment]
I think Firefox has a bug as soon as overflow is anything other than visible or clip, but from a spec point of view the text forgot about the scrollbars, and probably should be clarified.

**Comment by Loirooriol** [comment]
Maybe the spec should just refer to the [outer size](https://drafts.csswg.org/css-sizing-3/#outer-size)? This includes padding, borders, margins and scrollbars without having to list them all.

**Comment by aethanyc** [comment]
> This doesn't seem specific of scrollbars, it seems Firefox is not taking borders and margins into account either? Just the padding. [Testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cstyle%3E%0A%23grid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20width%3A%20max-content%3B%0A%20%20border%3A%20solid%3B%0A%7D%0A%23subgrid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20grid-template-columns%3A%20subgrid%3B%0A%7D%0A%23item%20%7B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border%3A%205px%20solid%20lime%3B%0A%20%20box-sizing-border-box%3B%0A%7D%0A%3C%2Fstyle%3E%0ABAD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22overflow%3A%20scroll%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%205px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%2015px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22margin%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cbr%3EGOOD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22padding%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E)

Yes, this is a bug, and should already be fixed in Firefox 90 ([Bug 1709491](https://bugzilla.mozilla.org/show_bug.cgi?id=1709491)). And grid area and grid item's margin is going to be included in the scrollable overflow area in [Bug 1527539](https://bugzilla.mozilla.org/show_bug.cgi?id=1527539).

Coincidentally, I'm also investigating Firefox's behavior on subgrid and scrollbars for a while in [Bug 1711803](https://bugzilla.mozilla.org/show_bug.cgi?id=1711803). My thought was that the subgrid has only explicit grid area, and the scrollbar size shouldn't affect the subgrid area whether it is overlay or classic. See [bug 1711803 comment 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1711803#c2). However, I don't feel strong about it. If the spec is clear that we should take the classic scrollbar's size it into account, i.e., we like Firefox's current behavior. I'm totally OK with it.

cc @MatsPalmgren @dholbert

**Comment by frivoal** [comment]
@aethanyc
> should already be fixed in Firefox 90 

Based on a very limited amount of testing, Firefox 90 indeed does what I'd expect. ❤️ 

As for [Bug 1711803](https://bugzilla.mozilla.org/show_bug.cgi?id=1711803), maybe I'm missing some subtlety, but as far as I understand it, the current behavior is the desirable one. Non overlay scrollbars do take space, and they take that space between the padding and the border, so if we don't take that space into account in operations that look at how bing margin/border/padding are, we're going to end up reserving the "wrong" amount of space, and this will end up being out of whack.

Yes, the fact that with `overflow:auto`, that space changes depending on whether you're actually overflowing or not is unpleasant, but that's why we need [`scrollbar-gutter: stable`](https://drafts.csswg.org/css-overflow-4/#valdef-scrollbar-gutter-stable).

**Comment by aethanyc** [comment]
@frivoal Thanks for the explanation. After understanding the purpose of `scrollbar-gutter`, now I can see [Bug 1711803](https://bugzilla.mozilla.org/show_bug.cgi?id=1711803) doesn't make sense. I've closed the bug.

**Comment by Loirooriol** [comment]
@aethanyc The first case in [here](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cstyle%3E%0A%23grid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20width%3A%20max-content%3B%0A%20%20border%3A%20solid%3B%0A%7D%0A%23subgrid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20grid-template-columns%3A%20subgrid%3B%0A%7D%0A%23item%20%7B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border%3A%205px%20solid%20lime%3B%0A%20%20box-sizing-border-box%3B%0A%7D%0A%3C%2Fstyle%3E%0ABAD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22overflow%3A%20scroll%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%205px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%2015px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22margin%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cbr%3EGOOD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22padding%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E) still seems wrong, though? Also, unstable layout if I add/remove a border dynamically.

**Comment by aethanyc** [comment]
> @aethanyc The first case in [here](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3Cstyle%3E%0A%23grid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20width%3A%20max-content%3B%0A%20%20border%3A%20solid%3B%0A%7D%0A%23subgrid%20%7B%0A%20%20display%3A%20grid%3B%0A%20%20grid-template-columns%3A%20subgrid%3B%0A%7D%0A%23item%20%7B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border%3A%205px%20solid%20lime%3B%0A%20%20box-sizing-border-box%3B%0A%7D%0A%3C%2Fstyle%3E%0ABAD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22overflow%3A%20scroll%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%205px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22border%3A%2015px%20solid%20orange%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22margin%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cbr%3EGOOD%3F%0A%3Cdiv%20id%3Dgrid%3E%0A%20%20%3Cdiv%20id%3Dsubgrid%20style%3D%22padding%3A%2015px%3B%20overflow%3A%20hidden%3B%22%3E%0A%20%20%20%20%3Cdiv%20id%3Ditem%3E%3C%2Fdiv%3E%0A%20%20%3C%2Fdiv%3E%0A%3C%2Fdiv%3E) still seems wrong, though? Also, unstable layout if I add/remove a border dynamically.

@Loirooriol Thanks! I filed [bug 1715178](https://bugzilla.mozilla.org/show_bug.cgi?id=1715178).

**Comment by tabatkins** [comment]
Added explicit reference to scrollbar gutters (it'll link up once we fix Overflow to export the term properly). Assuming this is a Commenter Satisfied, since it's precisely what @frivoal asked for. ^_^
