### ISSUE TITLE
[css-overflow] 'overflow' property values aren't properly linkified in definition of scrollbar-gutter 'stable' value

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#6357]
The definition of "scrollbar-gutter: stable" (at https://drafts.csswg.org/css-overflow-4/#scrollbar-gutter-property ) has some keyword names that look they're intended to linkified to definitions but aren't currently.

In particular:
 - there's a reference to "overflow/scroll" and "overflow/auto" (with property-name and slash) which look like they're not getting recognized/escaped properly.
 - Also, there's a reference to "hidden" which is blue but not linkified, possibly because its quote marks are mismatched (looks like a backtick before and basic vertical-bar single-quote after, at least in the rendered output).

See screenshot:
![image](https://user-images.githubusercontent.com/426803/121072114-a489bc80-c785-11eb-894b-a0b02c3a7c1c.png)

CC @frivoal who's been working on this text I think.

**Comment by frivoal** [comment]
Works now.
