### ISSUE TITLE
[css-color-4] text of MarkText example reads FieldText instead of MarkText

### ISSUE THREAD

**Issue by michaelficarra** [w3c/csswg-drafts#6362]
All of the other examples use text that matches the colour name, except this one. 

https://drafts.csswg.org/css-color/#ex-SystemCombo

![image](https://user-images.githubusercontent.com/218840/121207075-d9514e80-c82d-11eb-810c-3fea6e80df75.png)

**Comment by svgeesus** [comment]
Thanks!
