### ISSUE TITLE
CSS Indexes - publish to TR?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6363]
The [CSS Indexes](https://drafts.csswg.org/indexes/) are a great resource. They have never been published to /TR though. (The index claims that [it has](https://www.w3.org/TR/2021/NOTE-indexes-20210608/) but is incorrect).

And they are way better than the, (official _looking_ but ignoring **all ED**s) [List of CSS properties, both proposed and standard](https://www.w3.org/Style/CSS/all-properties).

Can we resolve to go to FP WG Note on this? And then update regularly, preferably automatically?

**Comment by SebastianZ** [comment]
> And they are way better than the, (official _looking_ but ignoring **all ED**s) [List of CSS properties, both proposed and standard](https://www.w3.org/Style/CSS/all-properties).

Note that that page has an option to toggle the display of editor's draft properties. And while I agree that the CSS Indexes should be published to /TR, I think both indexes have their advantages.

Sebastian

**Comment by svgeesus** [comment]
Ok well it seems there is no great enthusiasm to do this, so I guess it can be closed
