### ISSUE TITLE
[css-images-4] Add color space parameter to all gradient functions

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6369]
We should add an `in <colorspace>` keyword to all gradient functions to customize the color space interpolation happens in. Probably also need to be able to provide color-space specific parameters, like `hue-shorter` for polar spaces too.

**Comment by svgeesus** [comment]
I agree, as already used on [`color-mix()`](https://drafts.csswg.org/css-color-5/#color-mix) and [`color-adjust()`](https://drafts.csswg.org/css-color-5/#coloradjust), `in <colorspace>` is the natural way to extend gradients from their current sRGB-only state.

Ans yes, for [cylindrical polar color spacea](https://drafts.csswg.org/css-color-4/#cylindrical-polar-color) like HSL, HWB and LCH, an optional keyword for the [hue direction](https://drafts.csswg.org/css-color-4/#hue-interpolation) is needed. The default value would be the shorter hue arc.

**Comment by LeaVerou** [comment]
Editorial: We should define a `<color-interpolation>` production for this that everything else can refer to. We should not be duplicating this syntax all around CSS.
We should prefix the hue interpolation keyword with `hue-`, as it may not make sense out of context (even in `color-mix()` it's weird, e.g. it's non-obvious what `shorter` in `color-mix(in lch shorter, lime, red)` does.

**Comment by svgeesus** [comment]
> We should prefix the hue interpolation keyword with hue-, as it may not make sense out of context (even in color-mix() it's weird, e.g. it's non-obvious what shorter in color-mix(in lch shorter, lime, red) does.

Maybe we should also add the `hue-` prefix right in CSS color 5, in that case.

**Comment by LeaVerou** [comment]
> > We should prefix the hue interpolation keyword with hue-, as it may not make sense out of context (even in color-mix() it's weird, e.g. it's non-obvious what shorter in color-mix(in lch shorter, lime, red) does.
> 
> Maybe we should also add the `hue-` prefix right in CSS color 5, in that case.

I don’t understand what you’re proposing. Add it where?

**Comment by tabatkins** [comment]
I think Chris is just agreeing with you that we should rename the hue-interpolation keywords generally to have a hue- prefix. ^_^

Anyway agree, the gradient grammars can easily handle having these added in.

It looks like the hue-interpolation keyword is placed after or between colors, not used as a general method over the entire interpolation, right? So we'd put it in the `<color-stop-hint>` productions and say that it's either invalid or just meaningless if you're not transitioning in a hue-ful color space, while the `in <color-space>` production goes in the prelude.

**Comment by LeaVerou** [comment]
Oh yeah, the production I was proposing should definitely go in Color, I didn't realize that was ambiguous.
Though it may need to be Color 4, as [that's where interpolation is defined](https://drafts.csswg.org/css-color-4/#interpolation).

I think something like:
```
<color-interpolation> = in <color-space> [ <hue-interpolation> ]?
<hue-interpolation> = shorter | longer | increasing | decreasing | specified
```

If we want that kind of granularity, we should add the entire `<color-interpolation>` syntax to `<color-stop-hint>`, not just a part of it. This way people can also customize the color space the transition happens in. Hence the production would become:

```
<linear-color-hint> = <length-percentage> || <color-interpolation>
```

Note that there should still be a `<color-interpolation>` param in the first argument of gradients, to cover the vastly more common case of wanting to specify an interpolation strategy for the entire gradient.

> It looks like the hue-interpolation keyword is placed after or between colors

I had not actually realized this, this is new edit. I …don't think this should be the case. This is an argument for the _interpolation_, not an argument for the _color_.

**Comment by weinig** [comment]
There is also some discussion of this in https://github.com/w3c/csswg-drafts/issues/5833.

**Comment by svgeesus** [comment]
This has now been done, see CSS Color 4: [13.1. Color space for interpolation](https://drafts.csswg.org/css-color-4/#interpolation-space) which defines

> &lt;color-interpolation-method> = in [ <&lt;ectangular-color-space> | &lt;polar-color-space> &lt;hue-interpolation-method>? ]

which is used in CSS Images 4:

[3.1. Linear Gradients: the linear-gradient() notation](https://drafts.csswg.org/css-images-4/#linear-gradients)
[3.2. Radial Gradients: the radial-gradient() notation](https://drafts.csswg.org/css-images-4/#radial-gradients)
[3.3. Conic Gradients: the conic-gradient() notation](https://drafts.csswg.org/css-images-4/#conic-gradients)
