### ISSUE TITLE
[css-cascade] Remove scoped styles

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#637]
The `<style scoped>` was removed from HTML (whatwg/html#552 & w3c/html#231). Should 'Scope' be removed from the [cascade](https://github.com/w3c/csswg-drafts/blob/e9ecba7e0293c5c150d3c6ae1559da5194cb89a3/css-cascade/Overview.bs#L688)?

**Comment by keithjgrant** [comment]
There is a related editor’s draft for [Scoping Module level 1](https://drafts.csswg.org/css-scoping/) , though I don’t think much will come of it at this point (as much as I wish it would)

**Comment by keithjgrant** [comment]
FWIW, even if “scoped styles” aren’t going to be a thing (outside of the Shadow DOM), I like the way it’s explained in the Cascade spec now. Inline styles fit more neatly as a part of Scope, rather than an odd exception to the rules of Specificity.

**Comment by xfq** [comment]
> FWIW, even if “scoped styles” aren’t going to be a thing (outside of the Shadow DOM), I like the way it’s explained in the Cascade spec now. Inline styles fit more neatly as a part of Scope, rather than an odd exception to the rules of Specificity.

Agreed.

**Comment by xfq** [comment]
Related: Selectors L4 also [mentions](https://github.com/w3c/csswg-drafts/blob/73df2299ebf24f9f9468f6b38bb5dc5a9e1e8730/selectors/Overview.bs#L1932) the scoped `<style>` element in HTML.

**Comment by fantasai** [comment]
Scoping has multiple effects, which can theoretically be triggered independently:
- scoping of selectors is in Selectors
- scope-precedence in the cascade is in Cascade

Since scoped styles have been mostly abandoned, the CSSWG resolved to drop scoping from Cascade L3. It's still in L4, however, in case anyone needs to refer to it. :)

**Comment by fantasai** [comment]
WG resolution recorded at https://lists.w3.org/Archives/Public/www-style/2017Feb/0069.html
