### ISSUE TITLE
[css-fonts-5] Is the 'size-adjust' descriptor stable enough to ship?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6371]
We have implemented https://drafts.csswg.org/css-fonts-5/#size-adjust-desc in Firefox nightly builds, and it seems to work fine.

Do we consider the spec for this feature stable enough to ship, or should we hold it back as nightly-only for a while yet?

**Comment by fantasai** [comment]
Probably should merge in outstanding edits and publish FPWD first, but, it seems fairly straightforward otherwise?

**Comment by svgeesus** [comment]
I agree with @fantasai that clearing up the `needs edits` and resolving on FPWD should be done first (but soon!).

**Comment by jfkthame** [comment]
@litherum, could you confirm whether you're OK with this, or have any concerns? Thanks!

**Comment by chrishtr** [comment]
Shall we close this issue now? It seems done.

**Comment by svgeesus** [comment]
The only related open issues are

 [Add font-size descriptor to @font-face which allows ranges (for optical sizing)](https://github.com/w3c/csswg-drafts/issues/806) which, I think, is mainly confusing properties and descriptors. It is an older issue and predates a lot of changes in the spec. That issue can probably be closed.

[font-size Descriptor for ex Unit](https://github.com/w3c/csswg-drafts/issues/731) which is again old and I think is satisfied by the newly-expanded `font-size-adjust`.

And the FPWD mentioned earlier in this issue has been published, a while ago.

I would be okay with closing this issue.

**Comment by chrishtr** [comment]
Ok I'll go ahead and close this issue. Thanks!
