### ISSUE TITLE
[css-fonts-4] The 'features' value of 'font-technology' needs a parameter to identify the specific feature/shaping technology

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6372]
In the [`font-technology`](https://drafts.csswg.org/css-fonts-4/#font-technology-values) options for the `supports` clause of the `src` descriptor, the `color(...)` value takes an argument that identifies which specific color technology is used.

However, `features` does not currently have a similar argument; I think it should. There are at least three distinct font-feature technologies in current use that each may (or may not) be individually supported by a given user agent: OpenType layout (GSUB/GPOS tables), AAT (morx/kerx tables), and Graphite (Silf and related tables). Given that not all browsers support all of these, the bare keyword `features` is insufficient to determine whether a given resource should be used.

Therefore, I propose that `features`, like `color()`, should take a keyword argument specifying which font feature technology is present; possible values would be `ot` (or `opentype`?), `aat`, and `graphite`. This allows browsers to load only font resources they can properly use, and enables authors to provide alternative fonts if needed.

**Comment by svgeesus** [comment]
This sounds very reasonable to me, and I somewhat prefer `opentype` to `ot`.

**Comment by svgeesus** [comment]
Okay I just added

```html
<pre class="prod"><dfn id="font-feature-technology-values">&lt;font-feature-technology&gt;</dfn> = [opentype | aat | graphite]</pre>
```

**Comment by svgeesus** [comment]
@jfkthame does that look good to you?

**Comment by svgeesus** [comment]
And I need to add a reference for Graphite. OpenType and AAT are already in the references. Specref doesn't have anything. I guess [Graphite technical overview](https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_techAbout) is appropriate?

**Comment by jfkthame** [comment]
Yes, looks OK to me.
For a reference, another option would be [Graphite home](https://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_home). But perhaps the tech overview is a good entry point for this purpose. I don't feel strongly one way or the other.

**Comment by svgeesus** [comment]
[Added Graphite reference](https://github.com/w3c/csswg-drafts/commit/6d6487905330db2b62ac4e7277f4a03b57ecfa59)
