### ISSUE TITLE
[css-grid] Positioned items don't participate in the grid container baseline

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#639]
The [grid container baseline definition](https://drafts.csswg.org/css-grid/#grid-baselines) talks generally about "grid items".

IMHO, it would be nice to explicitly exclude absolutely-positioned grid items, as they don't participate on the layout of the grid as stated in [10.1](https://drafts.csswg.org/css-grid/#abspos-items):
> does not contribute to the sizing of any grid tracks or affect the size/configuration of the grid in any way

**Comment by dholbert** [comment]
FWIW, I believe this is already pretty unambiguous in the spec.

There is no such thing as an "absolutely positioned grid item", spec-wise.  The term "grid items" is already defined as only including *in-flow* children.  This is clarified in both the section on grid items and the section on abspos children:

> Loosely speaking, the **grid items** of a grid container are boxes representing its **in-flow contents**
https://drafts.csswg.org/css-grid/#grid-item
[...]
> An **absolutely-positioned child** of a grid container is out-of-flow and **not a grid item**
https://drafts.csswg.org/css-grid/#static-position

**Comment by mrego** [comment]
Yeah I was missing the "each in-flow child of a grid container becomes a grid item" in the definition.
This is not needed indeed. Thanks!
