### ISSUE TITLE
[css-sizing-4] 'screen' or 'viewport' as possible value for aspect-ratio

### ISSUE THREAD

**Issue by Th3S4mur41** [w3c/csswg-drafts#6392]
The [current specification for `aspect-ratio`](https://drafts.csswg.org/css-sizing-4/#aspect-ratio) allows explicit ratios, or the "natural" aspect ratio from a replaced element. There is however no way to follow the viewport's aspect-ratio.

Wouldn't it be nice to be able to do something like `aspect-ratio: screen`?

Not sure if screen or viewport would be the best value here though?!

**Comment by SebastianZ** [comment]
What would be the use cases for having an aspect ratio of the screen or the viewport?

Sebastian

**Comment by Loirooriol** [comment]
Why not `aspect-ratio: calc(1vw / 1vh)`?

**Comment by jonjohnjohnson** [comment]
> Why not `aspect-ratio: calc(1vw / 1vh)`?

And even more so with the new `dv*` & `sv*` units? https://github.com/w3c/csswg-drafts/issues/4329#issuecomment-863677668 / https://github.com/w3c/csswg-drafts/issues/6113#issuecomment-863669068

**Comment by Th3S4mur41** [comment]
@SebastianZ I was thinking about different art direction scenarios... A bit like with the <picture> element.
I wanted to create a page with various element following the viewport size as a direction to keep a kind of visual constant.

**Comment by fantasai** [comment]
Closing out as a solved question via https://github.com/w3c/csswg-drafts/issues/6392#issuecomment-864275613 Lmk if this is unsatisfactory. :)
