### ISSUE TITLE
[css-contain-3] Define a syntax for style-based container queries

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6396]
Container Queries should allow us to write conditional rules based on the computed styles of an ancestor container, since, according to @andruud:

> Knowing the computed style (and even layout) of the container before evaluating the container query is already needed for normal (size) queries.

I'm branching this issue off from #5989 (What container features can be queried?) and #5624 (Higher level custom properties that control multiple declarations) – to specifically discuss syntax for querying a container's computed styles as part of [css-contain-3](https://drafts.csswg.org/css-contain-3/#style-container).

Several of the use-cases mentioned so far (actual syntax TBD):

1. testing for a discrete value on a property, eg `(background-color = red)` or `(--pill = on)`
2. testing that a custom property has any not-guaranteed-invalid value, eg `(--is-small)`
3. testing range comparisons of length values, eg `(50vw < 400px)` or `(--small > 50vw)`

And some of the issues to address:

- We need to define how discrete values are compared (is it a token sequence? how is whitespace handled? etc)
- Custom properties used in range queries may need to be registered with `@property`
- Some values (like `%` lengths) evaluate differently on different properties. What do they mean in a query?

I'd like to get more use-cases and issues documented here, so that we can work through them in more detail.

**Comment by andruud** [comment]
We can't do `(background-color = red)` though, right? (E.g. `width` is both a feature and a property).

**Comment by mirisuzanne** [comment]
@andruud that's right, we have to work around features like `(width =  30em)`, `(width >=  30em)`, `(min-width: 30em)`. Maybe a wrapping `property()` or `computed()` function?

**Comment by fantasai** [comment]
Agenda+ to add style queries. Proposal:
- style queries use `style()` function; for disambiguation, size queries use `size()` function
- style queries query the computed value, with the value in the query also computed wrt the query container element
- style queries cannot query ranges (for simplicity initially, and to avoid confusion since many computed values resolve to lengths but are not comparable to lengths until after the computed value stage)
- style queries can be combined using the boolean logic and syntax from @supports

Note: @mirisuzanne and I drafted this proposal into the ED at https://drafts.csswg.org/css-contain-3/#style-container in https://github.com/w3c/csswg-drafts/commit/f209f6a01a65a210acf100db9036dcccdc2c0baa

**Comment by andruud** [comment]
Nice.

So you opted to not have `<general-enclosed>` at all? Just asking since it would make e.g. `size(width > 10px) or future(something)` a parse error.

**Comment by mirisuzanne** [comment]
@andruud We absolutely need to think through the behavior we want here for future syntax. I think we also might want to consider defaulting queries without a function to be `size` queries - but that likely needs conversation in the WG.

**Comment by fantasai** [comment]
@andruud `<general-enclosed>` needs to parse without invalidating the entire rule, but it's not valid syntax. If you put random stuff in there, the browser shouldn't choke on it -- but neither should your syntax checker say your style sheet has no errors.

**Comment by andruud** [comment]
@fantasai My point was that as currently proposed, the browser _would_ "choke on it". :slightly_smiling_face:

**Comment by mirisuzanne** [comment]
@tabatkins Does this need to be re-opened and addressed?

**Comment by deanleigh** [comment]
Will style-based container queries support elements styled with data-attributes please?
I use things like this a lot where utility classes can be added programmatically in CMS UI and manipulated in the front end with JS:
`data-screen-col_12="justify-content:space-between;"`
Would that register as a 'style'  ?

**Comment by tabatkins** [comment]
No, that's just an arbitrary string as far as the browser is concerned. If you then manually apply that string to the `style` attribute, it will work.

**Comment by deanleigh** [comment]
My bad explanation sorry - I am currently using them as utility classes with media queries
So `data-screen-col_12="justify-content:space-between;"` is referenced in my stylesheet like so where `$more-than-12-col` is a Sass variable for a breakpoint:

`@media only screen and (min-width: 1600px) {
    .feature__menu[data-screen-col_12~="justify-content:space-between;"] {
        .feature-layout__group {
            justify-content: space-between;
        }
    }`

Would the new syntax recognise the data-attribute and its value as a style?*

`@contains (min-width: 1600px) and style([data-screen-col_12="justify-content:space-between;])` {
 justify-content: space-between;
}

*not sure if this would be the correct syntax?

**Comment by James0x57** [comment]
for it to respond to your style you'd have to query the style like so:
```css
.feature__menu {
  & .feature-layout__group {
    container-type: style;
    ...
    @container style(justify-content: space-between) {
      /* add Extra Styles that only apply when this element has justify-content set to space-between */
      ...
    }
  }
}
```

because your existing system is adding `justify-content: space-between` when the data attribute is on the parent, those Extra Styles will only<sup>[1]</sup> be there when your feature__menu element has `data-screen-col_12` attribute containing `justify-content:space-between;`

If you need to add more styes only based on the data attribute selector though, you can add more styles the same way you're already adding `justify-content: space-between` and don't need a style container query.

<sub>[1] unless something else will set justify-content to space-between too</sub>

**Comment by deanleigh** [comment]
> for it to respond to your style you'd have to query the style like so:
> 
> ```css
> .feature__menu {
>   & .feature-layout__group {
>     container-type: style;
>     ...
>     @container style(justify-content: space-between) {
>       /* add Extra Styles that only apply when this element has justify-content set to space-between */
>       ...
>     }
>   }
> }
> ```
> 
> because your existing system is adding `justify-content: space-between` when the data attribute is on the parent, those Extra Styles will only[1] be there when your feature__menu element has `data-screen-col_12` attribute containing `justify-content:space-between;`
> 
> If you need to add more styes only based on the data attribute selector though, you can add more styles the same way you're already adding `justify-content: space-between` and don't need a style container query.
> 
> [1] unless something else will set justify-content to space-between too

Finally got around to testing this but with no luck:
[](https://codepen.io/deanleigh/pen/YzYVGKp?editors=1000)

**Comment by mirisuzanne** [comment]
@deanleigh no one has implemented style container queries at this point, even in a prototype - so there's no testing to be done. But `style([data-screen-col_12="justify-content:space-between;])` will not be valid or meaningful, because (as Tab said above) `[data-screen-col_12="justify-content:space-between;]` is not a style, it's an attribute selector that happens to have some CSS-like information inside it. That attribute can be used to select and _apply_ a style, but the attribute itself is not a style. You can query `style(justify-content:space-between)` to match a container with that style applied, and you can apply that style using your attribute -- but those are two unrelated steps as far as CSS is concerned.

**Comment by deanleigh** [comment]
Sorry @mirisuzanne I pasted as a reply to an old post where I mistakenly thought style would work like more like :where()
The codepen has my example with what I believe is the correct syntax*
* I feel very bad now for causing you to explain it to me again

**Comment by mirisuzanne** [comment]
no worries!
