### ISSUE TITLE
[css-contain-3][cssom-1] Define a syntax for observing container queries

### ISSUE THREAD

**Issue by jonathantneal** [w3c/csswg-drafts#6401]
<a name="prompt-1" href="#prompt-1"># 1</a>. Should Container Queries allow us to observe [containment](https://drafts.csswg.org/css-contain-3/#containment-types) by an ancestor?

<details><summary><em>Example 1</em></summary>

```js
element.withinContainer("(width >= 640px)")
```
```ts
interface Element {
  withinContainer<query extends string>(query: query): ContainerQueryList<query>
}

interface ContainerQueryList<query extends string> extends EventTarget {
  query: query
  matches: boolean
  containers: EventTarget[]
}
```
</details>

<a name="prompt-1a" href="#prompt-1a"># 1a</a>. Should Container Queries allow us to observe containment changes by an ancestor?

<details><summary><em>Example 1a</em></summary>

```js
element.withinContainer("(width >= 640px)").onchange = (event) => {}
```
```ts
interface ContainerQueryListEvent<query extends string> extends Event {
  query: query
  target: ContainerQueryList<query>
  matches: boolean
  containers: EventTarget[]
}
```
</details>

<a name="prompt-2" href="#prompt-2"># 2</a>. Should Container Queries allow us to observe containment on an element with containment?

<details><summary><em>Example 2</em></summary>

```js
element.matchContainer("(width >= 640px)")
```
```ts
interface Element {
  matchContainer<query extends string>(query: query): ContainerQueryList<query>
}
```
</details>

<a name="prompt-2a" href="#prompt-2a"># 2a</a>. Should Container Queries allow us to observe containment changes on an element with containment?

<details><summary><em>Example 2a</em></summary>

```js
element.matchContainer("(width >= 640px)").onchange = (event) => {}
```
</details>

<a name="prompt-3" href="#prompt-3"># 3</a>. Should Container Queries allow us to observe containment using another abstraction, akin to observing media queries?

<details><summary><em>Example 3</em></summary>

```js
matchContainers("(min-width: 640px)")
```
```js
matchContainers("(min-width: 640px)").onchange = (event) => {}
```
```ts
function matchContainers<query extends string>(query: query): ContainerQueryList<query>
```
</details>

**Comment by mirisuzanne** [comment]
How does this overlap or combine with the `matchContainer` method (and related discussion about observers) in #6205?

**Comment by jonathantneal** [comment]
Yea, totally! Ha, I actually only knew about #6205, which, I know, technically makes no sense.
