### ISSUE TITLE
[css-contain-3] container-name string vs ident

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6405]
https://drafts.csswg.org/css-contain-3/#container-name accepts either a string or a custom ident, with identical semantics. We should probably stick to one of the two. Given that this is a name that originates in css and is used in css, I don't think we have a particular need to accomodate for names that don't fit a custom ident, so I'd suggest dropping strings.

**Comment by Loirooriol** [comment]
For other named at-rules:

- `@color-profile`: `<dashed-ident> | device-cmyk`
- `@counter-style`: `<custom-ident>`
- `@custom-media`: `<dashed-ident>`
- `@custom-selector`: `<dashed-ident>`
- `@font-palette-values`: `<custom-ident>`
- `@keyframes`: `<custom-ident> | <string>`
- `@layer`: `<ident> [ '.' <ident> ]*`
- `@property`: `<dashed-ident>`
- `@scroll-timeline`: `<custom-ident> or <string>`

**Comment by mirisuzanne** [comment]
By accepting a string, we allow attribute patterns like:

```css
[container-name] {
  container-name: attr(container-name);
}
```

I don't see that as a deal-breaker, but it does seem nice-to-have, and based on prior art?

**Comment by frivoal** [comment]
It's still not implemented anywhere, but using css-values-4 syntax, you could achieve that without needing strings:
```css
[container-name] {
  container-name: attr(container-name ident);
}

**Comment by tabatkins** [comment]
Yeah, I'm fine with keeping it as it is right now (accepting both, with them living in the same namespace). It's not a pattern we'll want to continue for the indefinite future, but nothing is harmed, and some use-cases are helped, by allowing it right now.

**Comment by andruud** [comment]
> living in the same namespace

That means any string that would match `<custom-ident>` when "ident-ified" by the computed-value process would need to be disallowed?

**Comment by tabatkins** [comment]
I'm not sure what you mean by that. I mean that `foo` and `"foo"` should represent the same container name.

**Comment by tabatkins** [comment]
We don't *necessarily* need to make `"initial"` invalid, but I think it would be a good idea, yeah. You can't construct a custom-ident with that value (unlike things like `"1em"` or `"foo bar"`, which can be done with escapes).

**Comment by nt1m** [comment]
I agree supporting both string and ident is not ideal in the long run. It's typically the type of thing that becomes a quirk on the web platform and small maintenance burden for the engine (which accumulate).

For the attr() use case, since vendors currently only implement attr() for ::before/::after atm, I would expect the generalization of attr() to also cover `attr(container-name ident)`.

**Comment by yisibl** [comment]
> @font-palette-values: <custom-ident>

Update:  `@font-palette-values` changed to `<dashed-ident>`
