### ISSUE TITLE
[css-cascade-5] Do conditional rules impact layer order?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6407]
In [CSS Cascading & Inheritance L5](https://drafts.csswg.org/css-cascade-5/) we define the `@layer` rule, and the way layers "stack" in priority based on the order they are first encountered. These will stack so the higher numbers override the lower numbers:

```css
@layer one;
@layer two;
@layer three;
```

In general, layers should interact well with conditional rules. In isolation these two rules should mean the same thing:

```css
@layer one { 
  @media (width > 500px) { /* styles */ }
}

@media (width > 500px) {
  @layer one { /* styles */ }
}
```

If the media-condition is true, then the styles are applied in the specified layer (`one`). But it's a bit less clear how the second example (layer inside condition) should impact the order of multiple layers:

```css
@media (width > 500px) {
  @layer one { /* styles */ }
}

@layer two;
@layer three;
@layer one;
```

Does layer `one` come first, last, or does it update dynamically based on the evaluation of the condition? I think the two options are roughly:

1. Layers are always added to the order, no matter how the condition might resolve. It's as though the layer rules "bubble up" to be defined outside the condition, but the styles are still conditional. This matches my instinct, personally.
2. Layer order is dynamic, based on conditions? It's interesting to consider, but could get pretty surprising…

This question is also relevant to other conditions, such as `@supports` or `@container`.

**Comment by andruud** [comment]
In isolation I like the bubbling suggestion. But I wonder if it's too great an "exception" to how conditionals usually work, and whether adding such special-snowflake behaviors actually end up _more_ surprising. In your latest example, re-ordering based on viewport width just looks like what the author is asking for to me. :-)

There are other options though:

3. Separate layer ordering declarations from layer usage and make it invalid to order things in conditionals, or (similar):
4. Make `@layer foo {}` a parse error inside a conditional unless `foo` has been (successfully) declared previously.

**Comment by xiaochengh** [comment]
I think there are two questions here:

1. Do we want conditional layer reordering?

It seems really broken to me that layers can be conditionally re-ordered. And what's the use case?

2. If we don't allow it, which syntax do we use?

I prefer the bubbling option, which looks the simplest to me.

**Comment by mirisuzanne** [comment]
I don't think we really can disallow layers inside media (parse error), or even apply the styles without contributing to layer-order. Sites sometimes use an html media attribute on most or all linked stylesheets (eg `media="screen"` or light/dark mode, etc). We'd be making it nearly impossible to use layers while also using that media attribute. I would find it very confusing if adding `media="screen"` to a stylesheet totally changed how all my layers work. 

@tabatkins also pointed out that once we allow layers inside conditional styles, we can't entirely avoid the dynamic behavior. Browsers often lazy-load stylesheets with an unmatched media attribute. If the media eventually matches, and those styles load late, either approach (always apply, or dynamically apply-on-match) will need to apply those changes once the sheet has loaded. That may be an argument for embracing the dynamic behavior, and making it the spec default.

If we do go that rout, though, we would need a special case for container queries, which do not have any global "matched" state.

**Comment by mirisuzanne** [comment]
To summarize all of the options, and their implications:

1. Parse error – `@layer` inside a conditional is ignored, along with all nested styles. I don't think this is viable, since adding `media="screen"` to a stylesheet could turn the entire file into one large parse error.
2. Never contribute - `@layer` works inside conditionals, but without contributing to layer order. Again, I don't think this is viable, for similar reasons. We would also have to determine how layers are ordered if they _only_ appear inside conditions. Would that be a parse error?
3. Always contribute - When we say `@layer` statements are ranked in order of first appearance, we mean it, even if that appearance happens inside a conditional. From an author perspective, it is as though the layers "bubble up" to the top level. While this is mostly stable, it is possible for some styles to lazy-load (especially when using unmatched media attributes), so there are cases where a late-loading stylesheet could change the order of layers dynamically.
4. Fully dynamic - `@layer` rules inside conditional rules only apply to layer order when the condition is met. This matches the behavior of lazy-loading stylesheets based on the media attribute, but would add a lot more potentially dynamic layer re-ordering based on media changes. Since `@container` conditions have no global value, but evaluate for individual elements, we would need a special case (option 1 or 2?) for handling layers inside container queries.

**Comment by andruud** [comment]
Fully dynamic for `@media` and `@supports` + parse error for `@container` sounds good to me.

**Comment by lilles** [comment]
@tabatkins said:

"Assuming layered styles are okay inside of container queries generally (I think so, but futhark can correct), then I suggest if a @layer is *introduced* in a @container, it's treated as always being introduced there, regardless of the @container matching or not."

I agree.

**Comment by mirisuzanne** [comment]
I agree. I'll begin drafting that language, and we can bring it back to the group for a formal resolution (pending further feedback).

**Comment by mirisuzanne** [comment]
Proposed resolution: If a layer is introduced in a non-global condition like @container, it's added to the layer order as though the condition is true.
