### ISSUE TITLE
[selectors-4] should the >> syntax for the descendant combinator still exist?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#641]
Depending on the resolution of #640, I think we should perhaps consider removing the >> synonym for the descendant combinator, currently [specified in selectors-4](https://drafts.csswg.org/selectors-4/#descendant-combinators).  It's not clear to me if the extra syntax is still worthwhile if >>> is removed.

**Comment by SebastianZ** [comment]
The `>>` syntax also serves the purpose of clarification. `a >> b` is more explicit than `a b`.

Sebastian

**Comment by Ms2ger** [comment]
I think that would have been a fine argument when CSS1 was being developed, but I believe at this point having two syntaxes for the same thing would reduce clarity.

**Comment by TakayoshiKochi** [comment]
Adding one data point:
according to http://caniuse.com/#search=%3E%3E Safari 10 and Safari Technology Preview
already implements `>>`.

As I tested on my local OSX, `>>` did not work on Safari 10.0.1, but it DID work on Safari TP 16.

**Comment by SebastianZ** [comment]
> I believe at this point having two syntaxes for the same thing would reduce clarity.

I can see that this might be the case if both combinators are mixed within style sheets, though my argument that `a >> b` is more explicit is still valid.

Sebastian

**Comment by zcorpan** [comment]
It was added to webkit in https://bugs.webkit.org/show_bug.cgi?id=140525 with some resistance and a final note:

> I'll nuke ">>" if it goes out of the spec.

cc @BenjaminPoulain

**Comment by TakayoshiKochi** [comment]
Looks like the last comment was made 2+ years ago...
Still, is this dependent on https://github.com/w3c/webcomponents/issues/78 ?

**Comment by anttijk** [comment]
WebKit support for >> was removed in https://trac.webkit.org/r221788
