### ISSUE TITLE
[mediaqueries] media feature for RTL direction

### ISSUE THREAD

**Issue by cookiecrook** [w3c/csswg-drafts#642]
[mediaqueries] media feature for RTL direction

Perhaps:
@media (direction: rtl) { /* hebrew, arabic, etc. */ }

And the none value (ltr could potentially be a synonym for none in the Boolean context?):

(direction: none) == (direction: ltr)
(direction) == (direction: rtl)

**Comment by frivoal** [comment]
Detection of the RTL vs LTR direction (vs vertical-rl vs vertical-lr?) of what?

If you care about the document itself, the [`:dir()` pseudo class](https://drafts.csswg.org/selectors-4/#the-dir-pseudo) should be a better fit.

Can you give concrete examples of what you would use this for, to help evaluate if this already solved by some other mean, and if not, if this would indeed be a good solution to the problem(s) you're trying to solve?

**Comment by cookiecrook** [comment]
Actually :dir() will probably work. Okay to close.

**Comment by aehlke** [comment]
This would still be great to have
