### ISSUE TITLE
[cssom] "For each CSS property property that is a suppor..."

### ISSUE THREAD

**Issue by cscott** [w3c/csswg-drafts#6421]
https://drafts.csswg.org/cssom/#example-a40690cb

> For each CSS property property that is a supported CSS property, the following partial interface applies where camel\-cased attribute is obtained by running the CSS property to IDL attribute algorithm for property\.

It would be nice to have an html anchor for this text, for reference in implementation documentation.

**Comment by emilio** [comment]
I think the right link should be: https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-camel-cased-attribute

Perhaps we can move the definition a bit further up.

**Comment by emilio** [comment]
Would https://github.com/w3c/csswg-drafts/pull/6424 address this for you? It'd make the above link go to the paragraph you quoted.
