### ISSUE TITLE
Add parameter to change the size of box-shadow and text-shadow. [css-backgrounds-3] [css-text-decor-3]

### ISSUE THREAD

**Issue by NagayamaToshiaki** [w3c/csswg-drafts#6423]
* please be specific (in the title and issue) about what you want to change:
By magnifing or shrinking the size of the shadow, we can emulate that of a real environment. And if we can make the text-shadow begger, text-border emulation hack will be easier and reduces artifacts on the edge which is pronounced especially in CJK letters.

You can see the edge wierdness in the title of this page.
https://wiki.dengekionline.com/srwdd/

* please link to the spec section you're talking about, or at least the spec
https://drafts.csswg.org/css-backgrounds-3/#box-shadow
https://drafts.csswg.org/css-text-decor-3/#text-shadow-property

**Comment by SebastianZ** [comment]
The fourth `<length>` parameter of the `box-shadow` property already allows to specify the size of the shadow. In the CSS Backgounds 3 specification you linked to this is called "spread distance".

The level 3 of the CSS Text Decoration specifcation did not have this spread distance, though [Level 4 does specify a spread radius for `text-shadow`](https://drafts.csswg.org/css-text-decor-4/#text-shadow-property) which means the same.

So from specification side there's nothing to change, only browsers and other user agents still need to implement the feature for `text-shadow`.

Here are some links to the implementation issues for the different browsers:
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=655590
* Chrome / Opera / Edge: https://bugs.chromium.org/p/chromium/issues/detail?id=1226531
* Safari: https://bugs.webkit.org/show_bug.cgi?id=76997

Sebastian
