### ISSUE TITLE
[css-images] Typos gradient grammars

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6425]
I suggest the following changes in the "expanded" grammar of [3.2.1. radial-gradient() Syntax](https://drafts.csswg.org/css-images-3/#radial-gradient-syntax) (css-images-3, the note at the very bottom of the section):

<details>
  <summary>Fixed in <a href="https://github.com/w3c/csswg-drafts/commit/09ceac08069c4a344873da073a9b3b389b2400e2">09ceac0</a>
and <a href="https://github.com/w3c/csswg-drafts/commit/8f97e89c5c7b0a853ff87a0a5065cca8d1f95907">8f97e89</a></summary>

```diff
  Expanded with the above definitions, the grammar becomes:

  radial-gradient() = radial-gradient(
-   [ [ circle               || <length> ]                          [ at <position> ]? , |
-     [ ellipse              || <length-percentage>{2} ]            [ at <position> ]? , |
+   [ [ circle               || <length [0,∞]> ]                    [ at <position> ]? , |
+     [ ellipse              || <length-percentage [0,∞]>{2} ]      [ at <position> ]? , |
      [ [ circle | ellipse ] || <extent-keyword> ]                  [ at <position> ]? , |
      at <position> ,
    ]?
-   <color-stop> [ , <color-stop> ]+
+   <color-stop-list>
  )
  <extent-keyword> = closest-corner | closest-side | farthest-corner | farthest-side
```

I believe that `<size>`s are missing ranges, and that a type extending to a color is missing, because `<color-stop>` expands to `<color-stop-length> | <color-stop-angle>`, which only expand to dimension(s)/percentage(s). I think it should be `<color-stop-list>` instead, or that `<color-stop>` should be changed [there](https://drafts.csswg.org/css-images-4/#color-stop-syntax) (css-images-4) to:

```diff
- <color-stop> = <color-stop-length> | <color-stop-angle>
+ <color-stop> = <linear-color-stop> | <angular-color-stop>
```
</details>

**Comment by LeaVerou** [comment]
@tabatkins?

**Comment by cdoublev** [comment]
Also:

> A color stop with two positions is equivalent to specifying two color stops with the same color, one for each position.

But currently two or more stops (`#`) are required:

> Color stops and transition hints are specified in a color stop list, which is a list of two or more color stops interleaved with optional transition hints:
> 
> `<color-stop-list> = <linear-color-stop> , [ <linear-color-hint>? , <linear-color-stop> ]#`

It may be helpfull to note the "implicit" expanded definition:

```
<color-stop-list> =   <color> && <color-stop-length>? [ , <linear-color-hint>? , <linear-color-stop> ]#
                    | <color> && <color-stop-length>{2} , [ <linear-color-hint>? , <linear-color-stop> ]#?
```

Note: `#?` is [not officially valid yet](https://github.com/w3c/csswg-drafts/issues/6085#issuecomment-799898161).

**Comment by tabatkins** [comment]
> but currently two or more stops (#) are required:

`#` does not imply two or more, it implies one or more, same as `+`. It just requires a comma between the repetitions, while `+` doesn't require anything.

> This behavior is not defined but with the current grammars for a color stop list, they assume that when parsing a color stop with two positions, the input list of component values is mutated by pushing a comma and the color between the two positions.

The serialization rules for the gradient functions aren't strictly defined, but the behavior is sensical - giving two positions is defined to be equivalent to providing two color stops with the same color:

> A [color stop](https://w3c.github.io/csswg-drafts/css-images-4/#color-stop) with two positions is equivalent to specifying two color stops with the same color, one for each position.

So browsers are just expanding it into two stops internally, and then serializing them individually rather than re-merging them.

**Comment by cdoublev** [comment]
> `#` does not imply two or more

My previous comment is confusing. `<color-stop-list>` requires two or more `<linear-color-stop>` but the prose in CSS Images 4 allows a single one.

```
<color-stop-list> = <linear-color-stop> , [ <linear-color-hint>? , <linear-color-stop> ]# 
<linear-color-stop> = <color> && <color-stop-length>?
<color-stop-length> = <length-percentage>{1,2}
```

In `radial-gradient(red 0% 50%)`, which is valid, `red 0% 50%` matches the first `<linear-color-stop>` but `, [ <linear-color-hint>? , <linear-color-stop> ]#` has no match but is required.

Maybe it should be `<linear-color-stop> , [ <linear-color-hint>? , <linear-color-stop> ]#?`.

**Comment by tabatkins** [comment]
Ahhh, yes ok that's correct, and yeah your suggested fix is the way to go.
