### ISSUE TITLE
[css-contain-3] Ancestor Layout Loops with Single-Axis Containment

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6426]
In #1031 we identified the need for, and some of the issues with, single-axis containment. Since then Chrome has implemented the basic feature behind a flag – and we've had a chance to explore some of the issues in more depth. We wanted to start a new thread here to provide a collated summary of the issues, and how they relate.

In order for inline-size containment to work, the container has to maintain the same inline-size no matter what happens to the contents inside it – and no matter how much the block-size changes. These are cases where that behavior is difficult to define. We have potential solutions to each individual issue here. But the overarching concern is that all these solutions need to be applied on _arbitrary ancestors of the contained element_, making their impact expensive for browser engines, and unpredictable for authors. 

Hopefully we can attempt some of these solutions in the Chrome prototype, in order to see them in practice.

## Cross-axis overflow and classic scrollbars

Demo: https://codepen.io/miriamsuzanne/pen/yLbNgMx (requires classic scrollbars enabled)

If any ancestor has overflow on the container's block axis, then additional block-size of the contents can trigger a scrollbar on the cross-axis. Classic scrollbars for block-scrolling take up space on the inline-axis, leaving less space for the container.

This is likely to a very common scenario, impacting the majority of sites that uses inline-size containment, since the viewport itself uses auto-scrollbars.

This could be resolved by applying `overflow-gutter: stable` to the nearest ancestor with `overflow: auto` on the container's block axis? However, `overflow-gutter` is currently limited to a single axis (block-scrolling), and might need to handle inline-scrolling as well, in case the scroller has a writing mode orthogonal to the container.

## %-Padding percentages in Orthogonal Writing Modes

Demo: https://codepen.io/miriamsuzanne/pen/PomqWVE

When padding is applied to the block axis in percentages, those values resolve against the inline-size of the parent. By restricting single-axis containment to the inline axis, we eliminate the majority of these issues. However, it's still possible to apply orthogonal writing modes to any arbitrary ancestor with block-padding that would respond to the (now cross-axis) block size of the container.

- This applies to any ancestor with percentage-based block padding orthogonal to the container
- It doesn't matter what elements switch the writing modes, so long as the container & padding are orthogonal

This could be resolved by "zeroing out" any percentage-padding applied to any ancestor on the containers block-axis?

## Auto-sized BFCs effected by floats

Demo: https://codepen.io/miriamsuzanne/pen/mdmJRxW

The auto-sized Block Formatting Context (created by `overflow:hidden`) finds space for itself among various floated elements. However, as the contents expand vertically, the BFC has to contend with additional floated elements, and resizes. Note that:

- The float/s can be "siblings" or even "cousins" of the BFC
- The BFC can be the container, or _any ancestor_ of the container

This could be resolved by adding `clear: both` to all auto-sized ancestor BFCs?

## Aspect ratios (and Orthogonal Writing Modes?)

Demo: https://codepen.io/miriamsuzanne/pen/abWOJYJ

Since aspect-ratio implementations are inconsistent, and may have existing recursion issues (see #6419), I'm not confident that I know what issues here are specific to inline containment. Still it seems like something to keep an eye on - especially when orthogonal writing modes come into play.

This could be resolved in by removing the impact of the preferred aspect ratio? Authors who want to maintain a strict aspect ratio can still do that by applying size containment and defining overflow behavior.

**Comment by lilles** [comment]
I don't understand how the cross-axis overflow case is any different for single-axis containment and container queries than what is currently the issue with overflow:auto and contain:size. Regarding maintaining the same inline-size, we cannot do that even for contain:size, I think.

In this case, the inline size of the #contain element depends on its #spanner content via the scrollbar it triggers:

```html
<!doctype html>
<style>
  #scroller { width: 400px; height: 400px; overflow: auto; }
  #contain { contain: size; border: 2px solid green; }
  #spanner { height: 2000px; border: 2px solid red; }
</style>
<div id="scroller">
  <div id="contain">
    <div id="spanner">Spanner</div>
  </div>
</div>
```

**Comment by anttijk** [comment]
It sounds bit like there simply isn't such a thing as single-axis containment in CSS.

It is not obvious to me that that it is a requirement for a useful container query feature though. Maybe the focus should be in ensuring the algorithm makes forward progress and arrives in stable (though not necessarily entirely self-consistent) end state?

**Comment by dholbert** [comment]
> I'm curious how this solution (Ian's comment above) looks for WebKit and Gecko? This is being proposed for `contain: inline-size` specifically

So if I'm understand correctly, the proposed solution is just to let the following behavior sort of naturally fall out (with no explicit fixup/band-aids needed):
 (1) A `contain:inline-size` container-query-targeted element (let's call this element "foo") gets laid out with a particular inline-size (provided by its parent)
 (2) At this point in layout, Foo can resolve styles for its subtree (based on the container query); then it proceeds to lay its subtree out, figures out its block size, and reports that up to its parent.
 (3) The parent now changes its mind about the inline-size that it provided before (e.g. due to now needing to show a scrollbar, or realizing that floats will intersect badly, etc) and tells Foo to lay itself out again with a new inline size.
 (4) Foo re-resolves its container-query-dependent styles and lays out its subtree again. It happens to now be small enough that the parent might reconsider its decision (e.g. no scrollbar needed after all, or it looks like it could move to an earlier location amidst floats, etc). But the parent doesn't actually get that opportunity.
 (5) So: at the end of this layout, we've got a somewhat-inconsistent-looking layout (where e.g. a scrollbar is visible even though there's no overflow, or where Foo is placed further down than it looks like it would need to be amidst floats, etc)

I think this seems ~fine, though I suspect we may have to go through this same dance on every incremental layout for any change that dirties any nearby boxes.

**Comment by bfgeek** [comment]
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=9775

**Comment by frivoal** [comment]
> a somewhat-inconsistent-looking layout (where e.g. a scrollbar is visible even though there's no overflow

That's unfortunate-but-ok as long as it's somewhat rare. The opposite (i.e. having overflowing content but no room to put the scrollbar) would likely not.

**Comment by fantasai** [comment]
Action items here are:

1. Edit in @bfgeek's proposal.
2. Get @dbaron's sign-off that resulting spec is a acceptable for FPWD.
3. Resolve in CSSWG and publish FPWD.

**Comment by chrishtr** [comment]
There is now a [draft commit](https://github.com/w3c/csswg-drafts/commit/8577aa27f49388ad8e316220aa3be6ecbb6ebec6); however there is one more commit coming that moves the part about avoiding infinite cycles to a non-normative note.

Based on some offline discussions with several people, I think the TL;DR summary of what it's trying to say is:
a. The existing algorithms should not have infinite loops, and if they do it's a flaw in the existing algorithms that needs to be patched.
b. Container query elements are no different than cases that can already be encountered with combinations of floats, scrollbars, images, etc.
c. Therefore container query with single-axis containment elements don't represent anything "new".

Ideally, point (a) would be proved by algorithmic analysis, but unfortunately there is no algorithmic spec for block layout, floats etc; just a set of described "effects" of the layouts. I think it's too much to ask to require going through a very long and difficult task of writing it all out as an algorithm and proving that it halts and has a certain runtime performance. Instead, we should make our best effort to find and resolve problems we find, and guide our work with plenty of tests and implementation experience.

Detailed version of my reasoning:

1. Any element in the DOM has a certain means of determining its sizing based on its contents and external constraints.
2. In particular, for any choice of inline available size, an element has exactly one block size that it would prefer.
3. Therefore, while the relationship between inline available size and block size can vary greatly, it is always a function F mapping inline available size to preferred block size. (*)
4. For all layout algorithms to eventually halt, they must be able to deal with elements with an arbitrary F.
5. A container-query element is no different: it always chooses a given block sizing based on its available inline sizing, and this relationship can be graphed in the same way, and therefore has an F.
6. Therefore, container queries will halt, as long as existing layout algorithms have those properties and are correctly implemented.
7. Ideally, someone would go and write down an exact algorithm for block layout with floats, vertical writing modes, scrollbars, and so on.
8. In the meantime, container queries do not make the situation worse, except to the extent they raise the prominence of currently-obscure/not-costly algorithmic or implementation bugs.
9. While it's a good idea to invest in point 7 (define algorithms) incrementally over time, it doesn't make sense to block container queries on writing down and verifying these algorithms.
10. The best way forward to minimize risk from point 9 is a deep and clear experience with the layout algorithms, good implementation architectures, comprehensive and thorough testing, and interop.
11. Experience with past features tells us that there will be errors found after shipping in algorithm design and implementation, and experience also shows us we'll be able to figure out a solution to them.

(*) Examples: If you graph it in 2D with inline size in the X axis and block size in the Y, the relationship for an <img> would be a straight line up and to the right; a div with text under it would be a piecewise linear curve that bends downward to the right. With sufficient cleverness, you can probably generate cases where it starts going up and then down, and then up again, by combining text and images and floats and flexboxes in various ways (though I don't have an actual example at  hand).

**Comment by tabatkins** [comment]
I just committed 8574e93aa, which rewords and expands on the note about inline-size cycles, hopefully capturing @bfgeek's comments and intention. Mind reviewing, @bfgeek and/or @dbaron?

**Comment by dbaron** [comment]
8574e93aa684f316a0443224fd340cd4248b0054 Mostly looks good to me; I left a few comments on the commit about the examples.

**Comment by fantasai** [comment]
OK, @tabatkins and I made some revisions to this section to a) simplify the note and b) improve the example. The resulting text can be viewed at https://drafts.csswg.org/css-contain-3/#containment-inline-size
CC @dbaron @bfgeek @chrishtr

**Comment by chrishtr** [comment]
New text LGTM.

**Comment by mirisuzanne** [comment]
I think the spec changes above should address both this issue and #1031, pending a resolution to approve this approach.

**Comment by chrishtr** [comment]
@mirisuzanne when you said "should address", you meant it in the "did address" sense, right? Meaning you think the spec text as curently written is enough to resolve #1031 and #6426?

**Comment by mirisuzanne** [comment]
@chrishtr yes

**Comment by bfgeek** [comment]
Yup seems good.
