### ISSUE TITLE
[css-transforms-2] transform-style: preserve-3d should only have effects on transformable elements

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#6430]
As discussed in #1950 and as changed in #3750, css-transforms-2 currently [says](https://drafts.csswg.org/css-transforms-2/#transform-style-property):

> A computed value of preserve-3d for transform-style establishes both a stacking context and a containing block for all descendants.

I tend to think this should only happen for [transformable elements](https://drafts.csswg.org/css-transforms-1/#transformable-element), which are what [`transform-style`'s Applies to line](https://drafts.csswg.org/css-transforms-2/#propdef-transform-style) says it applies to.  It's worth noting that the "Applies To" line isn't really defined to *do* anything other than cause the property [not to have a used value](https://drafts.csswg.org/css-cascade-3/#used).

However, I think the *intent* of this "Applies to" line is that the property only have effects on transformable elements -- i.e., that it shouldn't have effects on non-replaced inlines.  In particular, the effect here would be only the third place in CSS where non-replaced inlines could be a containing block for fixed-positioned elements (the other two being [`filter`](https://drafts.fxtf.org/filter-effects/#FilterProperty) and [`backdrop-filter`](https://drafts.fxtf.org/filter-effects-2/#BackdropFilterProperty)).

So I'd propose changing the wording of the above sentence to instead say:

> A computed value of preserve-3d for transform-style *on a [transformable element](https://drafts.csswg.org/css-transforms-1/#transformable-element)* establishes both a stacking context and a containing block for all descendants.

I think this still fits with the original intent of the wording which is that the effects of [grouping properties](https://drafts.csswg.org/css-transforms-2/#grouping-property-values) not be considered in determining whether to establish a containing block or stacking context.

cc @mattwoodrow @smfr

**Comment by dbaron** [comment]
And based on code inspection, this appears to match [what Gecko does](https://searchfox.org/mozilla-central/rev/94d6086481754e154b6f042820afab6bc9900a30/layout/style/nsStyleStructInlines.h#139).

(I'd like to change Chrome to do the same, because then I won't have to worry about how to fix some [assertion failures](https://bugs.chromium.org/p/chromium/issues/detail?id=1226287).)

**Comment by mattwoodrow** [comment]
Sorry for the slow response. I agree that your proposed wording better reflects the intent, and makes things easier to understand and implement.
