### ISSUE TITLE
[css-logical][css-position] Duplicate property definitions

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#6434]
The following properties are defined both in [css-logical-1](https://drafts.csswg.org/css-logical-1/) and in [css-position-3](https://drafts.csswg.org/css-position/):

- `inset-block-end`
- `inset-block-start`
- `inset-block`
- `inset-inline-end`
- `inset-inline-start`
- `inset-inline`
- `inset`

The specs reference each other and I am not clear how I should read these definitions. Is there an authoritative definition for these properties? Where is it? Or a plan to converge to a signel authoritative definition?

Via https://github.com/w3c/webref/issues/127#issuecomment-874135280

**Comment by fantasai** [comment]
css-logical-1 supersedes CSS2 and css-position-3 supersedes css-logical-1 (which mainly contains these definitions because it had to build on CSS2 without css-position-3 existing).

**Comment by tidoust** [comment]
Thanks, this is good to know. Could the specs themselves be clearer about it? Or could the properties be dropped from css-logical-1 already? Typically, the css-position-3 spec is clear that it supersedes CSS2, but it does not talk about css-logical-1.

**Comment by fantasai** [comment]
@tidoust Done. Thanks for the suggestion. :)
