### ISSUE TITLE
[css-fonts-5] Should serialization/computed value of `font-size-adjust` include the `ex-height` keyword?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6442]
Spec: https://drafts.csswg.org/css-fonts-5/#font-size-adjust-prop

Currently, this says the computed value is:

> the keyword `none`, or a pair of a metric keyword and a `<number>`

However, given that `ex-height` is the default metric to normalize if only a number is specified, when I implemented the keyword+number syntax in Gecko (before this spec text actually appeared), I chose to *omit* the keyword `ex-height` from the `font-size-adjust` serialization, for the sake of backward compatibility.

What do we actually want to do here? Including the metric in all cases is good for consistency and readability, I think, but could possibly be surprising for existing code that operates on `font-size-adjust` based on the original syntax, and expects to see a bare number.

The extended syntax is currently in Nightly, and I am aiming for it to ship in Firefox 92, so it would be good to confirm (sooner rather than later) whether we should change the serialization in our implementation to *include* the `ex-height` keyword. Alternatively, we could modify the spec to say that as the default metric, it should be omitted. Opinions?

**Comment by emilio** [comment]
I think per the principles of serialization removing `ex-height` is the right thing to do. It's both more backwards-compatible and shorter.

**Comment by fantasai** [comment]
This is already required by CSSOM: https://www.w3.org/TR/cssom/#serializing-css-values
