### ISSUE TITLE
[css-backgrounds][css-position-3][css-transforms][css-text-3] Adjust value descriptions to reflect combined <*-percentage> values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#645]
In #263, #264 and #269 I've changed percentage combination values to use the combined [`<*-percentage>` values defined in V&U 3](https://drafts.csswg.org/css-values-3/#percentages), though I've not changed the value descriptions accordingly.

The descriptions of the values should be merged like it's already done in [CSS Fonts 3 (not published yet)](https://drafts.csswg.org/css-fonts-3/) and [CSS Images 3](https://drafts.csswg.org/css-images-3/#valdef-size-length-percentage2).

Sebastian

**Comment by fantasai** [comment]
Fixed.

**Comment by fantasai** [comment]
And fixed the follow-up errors in the commit, thanks. :)

**Comment by SebastianZ** [comment]
Thank *you* for fixing this! 😄 

Sebastian
