### ISSUE TITLE
[cssom] Parsing value should not be seen as side effects free

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6451]
I'm trying to implement `CSSStyleDeclaration` in JS. [Parse a CSS value](https://drafts.csswg.org/cssom/#parse-a-css-value) is invoked by `setProperty` (step 5) and has the following steps:

> 1. Let list be the value returned by invoking parse a list of component values from value.
> 2. Match list against the grammar for the property property in the CSS specification.
> 3. If the above step failed, return null.
> 4. Return list.

How can `getPropertyValue('flex-grow')` return `0` after `setProperty(flex, 'none')` if step 2 doesn't mutate the list (or returns a new list)? If it seems too obvious to add a dedicated note below these steps, please forgive me. I could have posted the following issue on StackOverflow but based on my previous experiences with this kind of topic, I don't think anyone would have answered it.

**Comment by Loirooriol** [comment]
Shorthand expansion is not done in "parse a CSS value", it happens in https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-setproperty

> 8. If _property_ is a shorthand property, then for each longhand property _longhand_ that _property_ maps to, in canonical order, follow these substeps:
>     1. Let _longhand result_ be the result of [set the CSS declaration](https://drafts.csswg.org/cssom/#set-a-css-declaration) _longhand_ with the appropriate value(s) from _component value list_, with the _important_ flag set if _priority_ is not the empty string, and unset otherwise, and with the list of declarations being the [declarations](https://drafts.csswg.org/cssom/#cssstyledeclaration-declarations).
>     2. If _longhand_ result is true, let _updated_ be true.

**Comment by cdoublev** [comment]
Do you mean that the appropriate values for `flex-grow`, `flex-shrink`, `flex-basis`, ie. `0`, `0`, `auto`, should be "expanded" at this step, from the list of component value, eg. `[Identifier('none')]`?

**Comment by emilio** [comment]
Yes, a declaration block only stores longhands and custom property declarations, not shorthands.

**Comment by cdoublev** [comment]
I might not explaining myself well, sorry. I know shorthands don't have a declaration.

Step 1 of `parse CSS value` tokenize the input value and consume tokens into a list of component values, and step 4 returns this list. Step 2 *match* this list. My question is wether it should return a boolean, or if it can mutate or replace the list of component values returned in step 4. For example, can it replace a list with a singe component value `none` by a list with component values `0`, `0,` and `auto` when `flex` is set to `none`?

I believe this is what Chrome does for long properties, eg. [`aspect-ratio`](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/css/properties/longhands/longhands_custom.cc;l=395), and that it [sets longhands in an object available to the parsing scope](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/css/properties/shorthands/shorthands_custom.cc;l=910) in order to use it in the above quoted step 8 of `setProperty`. Does this implementation is strictly spec compliant?

**Comment by Loirooriol** [comment]
In your example, `flex: none` is equivalent to `flex: 0 0 auto`, where the 1st `0` goes to `flex-grow`, the 2nd `0` to `flex-shrink`, and `auto` to `flex-basis`.

But note that shorthands don't always accept values for all their longhands.  For example, take `border: 1px solid black`. It has the values for `border-*-width`, `border-*-style` and `border-*-color` longhands. But it also sets `border-image-source: none; border-image-slice: 100%; border-image-width: 1; border-image-outset: 0; border-image-repeat: stretch`. However, the `border` grammar doesn't accept e.g. `stretch`.

So in general this can't be done just by changing the list of component values. We would need a map associating each longhand with its own list, or something like that.

> Do you mean that the appropriate values for flex-grow, flex-shrink, flex-basis, ie. 0, 0, auto, should be "expanded" at this step, from the list of component value, eg. [Identifier('none')]?

I think that's what supposed to happen, yes, but it's handwaved.

> Does this implementation is strictly spec compliant?

Implementations don't have to follow the specs step by step. If the result is indistinguishable from what you should get according to the spec, then it's fine.

**Comment by cdoublev** [comment]
Thank you. `border` was a perfect example. Some property specifications are not always clear as well, as to whether a specific rule should be handled during parsing or serialization. My reading of the CSSOM specification convinced me that it should be done during serialization. That was before I create a unit test for `flex: none`...

I will let you decide if a note would be required to clarify step 8 of *parse a CSS value*, and to clarify that *the appropriate value(s)* may need to be computed from something/somewhere else than the list of component values. Specs are primarily aimed at browser vendors, but this kind of notes can be very usefull to other implementations by people like me. Otherwise, feel free to close this issue without asking me.
