### ISSUE TITLE
[css-flexbox] Resolving flex item ‘auto’ preferred size for max-content contribution

### ISSUE THREAD

**Issue by andyjakubowski** [w3c/csswg-drafts#6455]
I’m trying to figure out how to resolve an `auto` preferred size of a flex item to calculate its [max-content contribution](https://drafts.csswg.org/css-flexbox-1/#intrinsic-item-contributions) as part of calculating the `max-content` [intrinsic main size of a flex container](https://drafts.csswg.org/css-flexbox-1/#intrinsic-main-sizes).

[§ 9.9.3. Flex Intrinsic Size Contributions](https://drafts.csswg.org/css-flexbox-1/#intrinsic-item-contributions) specifies the following (emphasis mine):

> The main-size max-content contribution of a flex item is the larger of its outer max-content size and **outer preferred size (its width/height as appropriate)** clamped by its flex base size as a maximum (if it is not growable) and/or as a minimum (if it is not shrinkable), and then further clamped by its min/max main size.

My flex item has `width: auto`. [CSS-SIZING-3](https://www.w3.org/TR/css-sizing-3/#valdef-width-auto) defers to the *relevant layout module* to calculate this. But the main size of a flex item is determined via `flex-basis` and the Flexbox layout algorithm. So if `flex-basis` is anything else than [`auto`](https://drafts.csswg.org/css-flexbox-1/#valdef-flex-basis-auto) (in which case it does look at `width` or `height` as appropriate), `width` or `height` seems to be effectively ignored.

How should I resolve a preferred size (`width` or `height`) of `auto` for a flex item? Should I follow the same steps as the steps for determining the *flex base size* outlined in [§ 9.2.3.E Determine the flex base size and hypothetical main size of each item](https://drafts.csswg.org/css-flexbox-1/#algo-main-item)? Where we ultimately look at the `max-content` size of an item if `flex-basis: auto` and `width: auto` (or `height: auto`)?

**Comment by tabatkins** [comment]
Oh jeez, looking at the blame for that section, that text was touched in 1992cf37ee38bac14336c925b65c053984a5c067. It's clear that we *meant* to have the "if it's not auto" rider on *both* contribution calculations, but for some reason accidentally omitted it from the max-content one.

It was present in both in the changelog's quote of the changed text! We just messed up in the actual spec text! Silly of us.

Anyway, thanks for spotting this and bringing it up. It should be clear now that, like for min-content contribution, you'd ignore the specified width in this case and just use the outer max-content size.

**Comment by fantasai** [comment]
Testcase added: https://github.com/web-platform-tests/wpt/pull/30569
