### ISSUE TITLE
[css-fonts] Republish CSS Fonts 4 and 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6462]
There have been a number of [important changes in Fonts 4 since the  17 November 2020 Working Draft](https://drafts.csswg.org/css-fonts-4/#changes-2020-11-17) so I would like to push an updated WD. 

Also we removed the scary **do-not-implement** warning from the ED of Fonts 5, so it would be good to republish that too.

**Comment by svgeesus** [comment]
The CSS Working Group just discussed `Republishing`, and agreed to the following:

* `RESOLVED: Republish CSS Fonts L4 and L5`
* `RESOLVED: Republish CSSOM`

<details><summary>The full IRC log of that discussion</summary>
&lt;fantasai> Topic: Republishing<br>
&lt;fantasai> Rossen_: css-fonts-4 and css-fonts-5<br>
&lt;fantasai> github: https://github.com/w3c/csswg-drafts/issues/6462<br>
&lt;fantasai> Rossen_: I looked over changes, seems fine<br>
&lt;fantasai> Rossen_: Any objections?<br>
&lt;fantasai> RESOLVED: Republish CSS Fonts L4 and L5<br>
&lt;fantasai> Rossen_: Next is updated WD for CSSOM<br>
&lt;chris> note some broken link issues that need to be fixed before publication https://github.com/w3c/csswg-drafts/issues/6463<br>
&lt;fantasai> Rossen_: some PR merged recently<br>
&lt;fantasai> Rossen_: emilio, chris any thing holding back?<br>
&lt;fantasai> chris: Some broken links, don't know what to replace with<br>
&lt;fantasai> github: https://github.com/w3c/csswg-drafts/issues/6446<br>
&lt;fantasai> emilio and chris will look into it<br>
&lt;fantasai> Rossen_: Any objections to republishing?<br>
&lt;fantasai> RESOLVED: Republish CSSOM<br>
&lt;chris> rrsagent, here<br>
&lt;RRSAgent> See https://www.w3.org/2021/07/21-css-irc#T16-08-30<br>
</details>

**Comment by svgeesus** [comment]
Publication request sent 26 Jul, expected 29 Jul.

**Comment by xfq** [comment]
Published:

* https://www.w3.org/TR/2021/WD-css-fonts-4-20210729/
* https://www.w3.org/TR/2021/WD-css-fonts-5-20210729/
