### ISSUE TITLE
[css-fonts-4][varfont] Axis values outside of the min/max range defined in the font's fvar should be clamped, not ignored

### ISSUE THREAD

**Issue by PeterCon** [w3c/csswg-drafts#647]
In section 6.2 of the current [CSS 4 Fonts draft](https://drafts.csswg.org/css-fonts-4/#low-level-font-variation-settings-control-the-font-variation-settings-property), it says,

"axis values greater or less than the range supported by the font, are ignored and therefore have no effect"

However, the OpenType 1.8 spec gives different guidance to OT applications: that values be clamped to the range defined within the font. See the normalization algorithm given in the "Coordinate scales and normalization" section of the [OpenType Font Variations Overview](https://www.microsoft.com/typography/otspec/otvaroverview.htm) chapter.

**Comment by tphinney** [comment]
I have difficulty imagining any circumstance in which ignoring the value entirely would be preferable to clamping to the closest available value in the font. I hope the CSS 4 draft is adjusted to be closer to the OpenType spec.

**Comment by litherum** [comment]
Dup of https://github.com/w3c/csswg-drafts/issues/517

**Comment by litherum** [comment]
It would be wise to migrate your comments to that thread.
