### ISSUE TITLE
[css-easing-1] Changes list out of date

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6477]
The changes list has a (small number of) changes [since 2019-04-30](https://drafts.csswg.org/css-easing/#changes). However, the previous publication was [2021-04-01](https://www.w3.org/TR/2021/CRD-css-easing-1-20210401/).

The changes list should be split in two parts, and updated from the [commit history](https://github.com/w3c/csswg-drafts/commits/main/css-easing-1/Overview.bs).

**Comment by fantasai** [comment]
The changes list is supposed to track since the previous CRS, and that's what the changes list is accurately doing. There's nothing else that's particularly interesting in the commit logs, it's all minor editorial tweaks so far.

**Comment by svgeesus** [comment]
That makes no sense, it is changes since previous publication.
