### ISSUE TITLE
[css-transforms] After #6320 there's no way to get an identity transform for interpolation of perspective

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6488]
In https://github.com/w3c/csswg-drafts/issues/6320 we resolved that we should clamp perspective values to `1px` at least for interpolation. That causes some interesting behavior though.

Consider [this testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=9531):

```html
<!DOCTYPE html>
<style>
body {
  margin: 20px
}

.animation {
  background-color: rgb(255, 255, 255);
  border-radius: 0.5625rem;
  box-shadow: rgb(238, 241, 240) 0px 0px 2px 2px;
  overflow: hidden;
  transition: transform 0.25s ease-in-out 0s, box-shadow 0.25s ease-in-out 0s;
  padding: 10px;
}

.animation:hover {
  transform:perspective(500px) translateZ(1rem);
  transform-style:preserve-3d;
  box-shadow:0 0 5px 5px #a7e5d6;
}
</style>
<div class="animation">
  Test Animation
</div>
```

In Chrome, and in old versions of Firefox (and Firefox after [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1723266) is resolved), that causes a smooth animation because `transform: none` uses the identity transform.

In release versions of chrome and older versions of Firefox, `.animation { transform: perspective(0) translateZ(0) }` was a no-op in the above test-case, but after #6320 `perspective(0)` is `perspective(1px)`, and that's a fairly drastic behavior change. In fact, there's no way an author can get an identity transform into `perspective()` other than by not specifying `transform` at all, which seems unfortunate / wrong.

cc @dbaron @mattwoodrow

**Comment by tabatkins** [comment]
The fact that `perspective(0)` was treated as an identity transform was always a bizarre hack; it's a complete discontinuity in behavior, as this issue shows.

The "identity" perspective is `perspective(infinity)`, right? We could just make that valid.

**Comment by mattwoodrow** [comment]
It looks like we already specify (in the Terminology list) that the identity transform function for perspective is `perspective(infinity)`, which seems correct.

Adding `perspective(infinity)` (or some equivalent token) as an option for explicitly specifying this case sounds like a good idea to me.

**Comment by Loirooriol** [comment]
I guess `perspective(calc(infinity * 1px))` or `perspective(calc(1px / 0))` are already supposed to work, right?

**Comment by tabatkins** [comment]
Those absolutely work (per spec), yes, but *technically* they're not identity since they'll get clamped to the maximum allowed perspective.

**Comment by tabatkins** [comment]
Simon's question in the call about using `infinite` (from `animation-iteration-count`) vs `infinity` (from `calc()` constants) is a good one. I... don't know quite what to do there.

An alternative is to avoid the question with `perspective(none)`, perhaps?

**Comment by mix5003** [comment]
can i ask something?

from this [document](https://www.w3.org/TR/css-transforms-2/). i said identity transform is `perspective(infinity)`. but from this resolved it add `perspective(none)`. is it mean `perspective(infinity)` is change to `perspective(none)` or it mean `perspective(none)` and `perspective(infinity)` both valid?

**Comment by emilio** [comment]
Just `perspective(none)`, afaict. That document needs to be updated.

**Comment by emilio** [comment]
I implemented this in Firefox in https://bugzilla.mozilla.org/show_bug.cgi?id=1725207, tests at https://github.com/web-platform-tests/wpt/pull/30141

**Comment by dbaron** [comment]
I just double-checked with [this test](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%0Adiv%20%7B%0A%20%20width%3A%20100px%3B%0A%20%20height%3A%20100px%3B%0A%20%20margin%3A%2050px%3B%0A%20%20background%3A%20blue%3B%0A%20%20transform%3A%20perspective(100px)%20rotateX(30deg)%3B%0A%20%20transform%3A%20perspective(infinity)%20rotateX(30deg)%3B%0A%7D%0A%0A%3C%2Fstyle%3E%0A%0A%3Cdiv%3E%3C%2Fdiv%3E) that none of Chromium, Gecko, or WebKit implement `perspective(infinity)`.
