### ISSUE TITLE
[css-namespaces-3] Replace CSS 2.1 syntax definition by CSS syntax

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#649]
The [minutes from 2016-10-12](https://lists.w3.org/Archives/Public/www-style/2016Oct/0091.html) resolved on removing the CSS grammar section from CSS 2.2 and instead refer to the CSS Syntax module. Though the CSS Namespaces Module still [uses that grammar for the definition of the @namespace rule](https://drafts.csswg.org/css-namespaces-3/#syntax).

This syntax should be replaced by something like this:

```
@namespace <namespace-prefix>? [ <string> | <url> ];

where
<namespace-prefix> = <ident>
```

Sebastian

**Comment by tabatkins** [comment]
Ping @fantasai since this came up again, and she's convinced it can be an editorial edit if we don't remove the Appendix G-style grammar, and thus wouldn't be too hard to update the Rec with.
