### ISSUE TITLE
`[css-fonts-5]` Add generic `font-family` for symbols/emoji

### ISSUE THREAD

**Issue by ghost** [w3c/csswg-drafts#6495]
We could do with a generic font family (either `ui-symbol` or `ui-emoji`) to expose fonts such as `"Segoe UI Symbol"` and `"Apple Symbols"` as set on the user's computer or browser.

https://www.w3.org/TR/css-fonts-5/#generic-font-families

**Comment by svgeesus** [comment]
Since CSS Fonts 4 just dropped the `emoji` generic font family in favor of the [`font-variant-emoji` property](https://drafts.csswg.org/css-fonts-4/#font-variant-emoji-prop), this does not seem likely.

 - https://github.com/w3c/csswg-drafts/issues/9359
