### ISSUE TITLE
[cssom] Throwing on invalid pseudo-elements in getComputedStyle is not web-compatible

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6501]
I tried to implement the resolution from #2149 in Firefox, and we instantly [found](https://bugzilla.mozilla.org/show_bug.cgi?id=1724674) broken pages because of that.

There are two patterns that show up:

 * `getComputedStyle(something, "height");` (or any other property instead of `height`). Seems like a coding error on the given site, but all browsers agree on not throwing there.
 * `getComputedStyle(something, false);` (which per WebIDL rules gets turned into `getComputedStyle(something, "false");`). This is also an error (because the right thing to use if you want to be explicit about the argument is `null`, not `false`), but it seems throwing there is more harmful than good.

So I propose we need to at least not throw when the string doesn't start with a colon. All browsers agree on returning the non-pseudo-element style there, so I suggest to just spec reality there.

For the cases the string does start with a colon we could:

 * Try to throw (I can come back with data).
 * Not throw, returning the non-pseudo-element style instead (WebKit / Blink behavior): It is consistent with the "string doesn't begin with a colon" case, but it seems a bit unfortunate.
 * Not throw, returning an empty style (`length = 0`) (Firefox behavior).

I think I prefer the third but I'd love to hear opinions.

**Comment by Loirooriol** [comment]
What do these sites do with the `getComputedStyle(something, "height")`? Would it be possible to return an empty style rather that the element style? Possibly with an exception for `"false"`?

**Comment by birtles** [comment]
I was seeing this on https://www.apple.com/jp/ipad-air/ too for what it's worth. (I really wish I made a note of what file/line it occurred on over in https://github.com/webcompat/web-bugs/issues/82685 🤦‍♀️)
