### ISSUE TITLE
[css-variables] Substituting CSS-wide keywords from custom properties themselves

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#6502]
From [substitute a var()](https://drafts.csswg.org/css-variables/#substitute-a-var), Example 13:

> While a var() function can’t get a CSS-wide keyword from the custom property itself—if you tried to specify that, like --foo: initial;, it would just trigger explicit defaulting for the custom property—it can have a CSS-wide keyword in its fallback: [etc]

But what about this case where the cascade won't intercept the value:

```
@property --x {
  syntax: "*";
  inherits: false;
  initial-value: unset;
}

div { color: var(--x); } /* Contains `unset` after substitution, right? */
```

Should we explicitly specify that CSS-wide keywords are not "computationally independent"? Or do we actually want this behavior?

**Comment by tabatkins** [comment]
This behavior is fine; the text you're referencing is correct for unregistered custom props, it's just that registered custom props have *one* way to directly insert CSS-wide keywords.

**Comment by andruud** [comment]
OK, thanks, closing.
