### ISSUE TITLE
[css-inline][css-writing-modes] definition of the central baseline

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#651]
Rescued from an old mail: https://lists.w3.org/Archives/Public/www-style/2015Feb/0446.html

---

The css-inline spec [defines](https://drafts.csswg.org/css-inline/#valdef-dominant-baseline-central) `dominant-baseline: central` as:

> Use the central baseline (halfway between the ascent and descent).

Is "halfway between the ascent and descent" a usable (or correct) definition in vertical writing modes when text-orientation is mixed or upright?

**Comment by kojiishi** [comment]
I think so. Strictly speaking, it depends on the underlying font technology, but I think it's a good abstraction and understandable.

**Comment by frivoal** [comment]
Forgive my ignorance, but how does that work? If you have upright + vertical-rl (for example), isn't the ascent up, and the descent down, while we want a central baseline that's halfway between left and right?

Or do ascent and descent somehow mean left and right in that context?

**Comment by kojiishi** [comment]
> Or do ascent and descent somehow mean left and right in that context?

Exactly. Fonts can have horizontal and vertical metrics. In vertical metrics, baseline is vertical, at the middle of the glyph, and the right half is still called ascent.

See the chart in [this page at Microsoft](https://www.microsoft.com/typography/otspec/gpos.htm). Or the chart in [kanji-database](http://kanji-database.sourceforge.net/fonts/opentype.html) (find a big chat of "漢") has "ascender" and "descender", though, it's Kanji character so maybe a little hard to understand how to apply it to Latin characters. At the bottom of [6.3. Line-relative Directions](https://drafts.csswg.org/css-writing-modes-3/#line-directions) has a picture of baseline in vertical metrics when I got the same question before.

**Comment by frivoal** [comment]
Ok, I understand now. I agree that the spec does required the right thing, but I am not so sure that it is easily understandable. I suppose it is to the people who will have to implement it, as they have to have detailed knowledge about how fonts work, but for an author who is familiar with typography terms and concept but not with font details, it is not obvious that ascent and descent may in some case be sideways measurements.

Could we add a note saying something like "For vertical metrics used for upright characters in a vertical writing mode, the ascent and descent are to the left and right of the glyph rather than up and down as the name may misleadingly suggest."

> At the bottom of 6.3. Line-relative Directions has a picture of baseline in vertical metrics when I got the same question before.

The picture shows where the baseline would be, which is helpful but isn't the problem I had. I was just confused how I could get to a baseline being there on picking the midpoint between ascent and descent, which I assumed would be up and down the character, not left and right.

**Comment by kojiishi** [comment]
Well, it says

> line-over is on right

and [line-over](https://drafts.csswg.org/css-writing-modes-3/#line-over) is defined as

> ascender side or “top” side of a line box

so it should explain if you follow the link, no?

**Comment by kojiishi** [comment]
Expanded the note a bit, appreciate if you could have a look and see if it's easier to understand.

**Comment by frivoal** [comment]
That makes it clear what happens with Open type, but the way it is phrased make it sound like other systems might behave differently, and if they do and have  ascent/descent = up/down, it isn't fully clear if we should follow the ascent/descent = right/left anyway, or if we should follow the font. I understand that we're supposed to use right/left anyway, but I am not sure it is clear (i.e. informatively unambiguous rather than just guessable).

**Comment by kojiishi** [comment]
The `line-over` part is normative, and couldn't find better way to describe it without being redundant. PR is appreciated if you have good idea.

**Comment by kojiishi** [comment]
Allow me to close this since edits were done and no further comments for 2 months. Please feel free to reopen if anyone think text should be improved further.
