### ISSUE TITLE
[css-flexbox] Clarify how to resolve flex item padding percentage values before flex container size is resolved

### ISSUE THREAD

**Issue by andyjakubowski** [w3c/csswg-drafts#6510]
In [4.2. Flex Item Margins and Paddings](https://drafts.csswg.org/css-flexbox-1/#item-margins), the Flexbox spec says that flex item padding percentage values should be resolved against the inline size of the containing block — the containing block being established the flex container’s content box. But there are times when the padding has to be resolved before the flex container’s content box size is calculated. What should such percentage values be resolved against in that case?

For example, imagine a `flex-flow: column wrap` flex container in a horizontal writing mode. In [5. Collect Flex Items Into Flex Lines](https://drafts.csswg.org/css-flexbox-1/#algo-line-break), we use the *outer hypothetical main size* of each flex item to place them into flex lines. But the padding percentage value of such a flex item has to be resolved against the inline size of the flex container, which in this case corresponds to its cross size. And the cross size of the flex container isn’t determined until [step 15](https://drafts.csswg.org/css-flexbox-1/#algo-cross-container).

Empirically, it seems like implementations (Blink, Gecko, WebKit) resolve those padding percentage values against the available inline space for the flex items. Additionally, the CSSWG had this resolution about resolving padding percentage values in Flexbox and Grid after [#2085](https://github.com/w3c/csswg-drafts/issues/2085):
> RESOLUTION: Both flexbox and grid items top and bottom margin and padding percent resolves against the available inline direction.

Is “available inline direction” the same as “available inline space”?

This treatment seems possible if available inline space for flex items is always a definite size. In my experience it is, but it’s not 100 % clear to me based on the spec. I asked a separate question about this: [[css-flexbox-1] When can available space for flex items be infinite?](https://github.com/w3c/csswg-drafts/issues/6476).

Could you please clarify how the spec wants these padding percentage values to be resolved?

**Comment by fantasai** [comment]
Percentage padding is calculated against the available inline space. If this is indefinite, then it resolves to zero during intrinsic sizing and is recalculated during layout, which often can cause overflow. This applies in block layout as well flex and grid. See https://www.w3.org/TR/css-sizing-3/#cyclic-percentage-contribution

Let me know if this answers your question, or if you have further questions or suggestions for clarifications. :)

**Comment by andyjakubowski** [comment]
Having another look at https://www.w3.org/TR/css-sizing-3/#cyclic-percentage-contribution helped, thanks!

To summarize, this is my understanding:
- if we need to resolve a flex item’s percentage padding to calculate the inline size of the flex container—a cyclic percentage—the padding resolves to zero
- if we need to resolve a flex item’s percentage padding for the sake of determining flex item sizes in flex layout, that will be resolved against the inline size of the flex container, which at that point is guaranteed to be definite, and thus the padding will be resolved
- if the flex container’s cross size corresponds to its inline size, then the cross size determination in step 15 should yield the same size we already used for resolving percentage padding in earlier steps
- if the flex container’s cross size corresponds to its block size, that determination may indeed rely on the size of the flex lines, and that’s why it has to be done in one of the last steps
