### ISSUE TITLE
[css-flexbox-1] Proposal: add flex-direction-based aliases for the align/justify-* props

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#6514]
This is an exploratory suggestion; not sure if it's something to actually go for, but wanna talk about it.

So, our (Chrome's) devrel have been doing some surveys about CSS usability in various aspects. Recently they were asking about Flex and the effects of having shipped 'gap' for it. (Spoiler: people like it.)

A persistent complaint showed up in the survey, however - a lot of people are confused by the justify/align-* properties, at least as applied to Flexbox. As far as we can tell, these properties *aren't* particularly confusing in *Grid*. The best we can figure is that people are able to handle the properties when they're mapped to the logical directions (which can, for the most part, be treated as *physical* directions), but they're confused by mapping them to *flex* directions.  The fact that Flexbox uses a different subset of the properties in each axis (all three align-* props, but only *one* of the justify-* props) might also be leading to the confusion - Grid uses all three in both.

(Quick aside: I think the emphasis on flex-relative directions in flexbox was a Big Mistake in the spec. Were I doing it again today I would *absolutely* make a lot of flexbox just rely on existing properties/directions, like just using width/height instead inventing flex-basis.)

We've been thinking over this, and a possible fix is to add aliases to the properties that are *explicitly flexbox-focused* (and, presumably, only work for flex layout?):

* `align-content` could be aliased as `pack-lines`
* `justify-content` could be aliased as `main-align`
* `align-items` could be aliased as `cross-align`
* (`align-self` left as-is?)

Adding these aliases would only be *useful* if they were usable cross-browser, else they would likely just lead to *even more* confusion; if we did something like this, then, we'd want cross-browser agreement and an attempt to ship roughly simultaneously.

Thoughts?

**Comment by ByteEater-pl** [comment]
This would cost much in terms of complexity and cognitive burden. If there are aliases, some authors (including those from the past, present and until support becomes sufficient) will use the original ones with flex, so people will still have to learn them in addition to the aliases. And code containig both will be particularly confusing. Although there are already some aliases in CSS, they're rare and introduced mostly for legacy vendor-prefixed properties implemented by others.

**Comment by rachelandrew** [comment]
I am not keen on this idea for a few reasons.

As @ByteEater-pl says in the thread, this adds an additional burden, as we will end up with both things out there.

It also further encourages people to think of Flex and Grid as these wildly different things. A lot of what I've tried to do in teaching people how to use these layout methods is to show how straightforward it is to switch a component from one thing to another. You don't have to feel tied to flex or grid, if you realize the component is really a grid you can change the formatting context but everything else, in many cases, works the same way. We lose that if we then have these special aliases only for flexbox.

I have something of a theory that the confusion within the existing community is based on how people learned these layout methods, first encountering flexbox and believing these properties were just for flexbox, then encountering them in grid. Teaching beginners, I start with grid and teach alignment in grid, then show how and why it is different in flexbox. This seems to work quite well in giving people a broad understanding. I'm sure they still have to look up when to align and when to justify, but having learned it in a systematic way it isn't baffling. I think we would make it more confusing by introducing these new properties that do the same thing but only in one context.

**Comment by una** [comment]
I appreciate the thought here, but I'm worried this change might add confusion. The existing terms `align`, `justify`, etc. are used in design software to describe placement. I would be hesitant to change that terminology and add aliases, especially as design software is increasingly becoming more GUI/code-enabled.

**Comment by tabatkins** [comment]
Given the significant negative feedback, especially from people experienced in teaching and DevRel, I'm gonna go ahead and retract this. Thanks for the feedback, y'all!
