### ISSUE TITLE
[css-cascade-5] Proposal to disallow interleaving of @layer and @import rules

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#6522]
Regarding empty @layer statements, the current [spec](https://drafts.csswg.org/css-cascade-5/#layer-empty) says:

> Such empty @layer rules are allowed anywhere either @import or other @layer rules are allowed.

And [also](https://drafts.csswg.org/css-cascade-5/#at-import):

> Any @import rules must precede all other valid at-rules and style rules in a style sheet (ignoring @charset and empty @layer definitions), or else the @import rule is invalid.

This allows interleaving @layer and @import rules. I'm proposing to disallow it because:
- There doesn't seem to be a valid use case to interleave these two types of rules
- No interleaving makes it much easier to implement in Chromium. Otherwise, we need to maintain the relative ordering between @layer and @import rules in the [StyleSheetContents](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/style_sheet_contents.h;l=50;drc=068d917a72636ddbb64dfa7ecabe6bac71bd4b26;bpv=1;bpt=1) class, which makes it more complicated without getting any benefit

The exact proposal is that rules in a style sheet must follow this ordering:
1. @charset
2. Empty @layer statements
3. @import
4. @namespace
5. All other rules + empty @layer statements

**Comment by mirisuzanne** [comment]
I don't think this would cause any functional problems - authors can still order layers as they want, and then add imported styles to those layers. But it does make the syntax for that a bit less flexible.

**Comment by tabatkins** [comment]
Yeah, no functionality is lost here, just a bit of flexibility. But I'd be okay with the restriction; it's probably *better* practice to put your `@layer ...;` rule either before or after your imports anyway.

**Comment by mirisuzanne** [comment]
Agenda+ to get a resolution

**Comment by fantasai** [comment]
Not sure why you think there's no loss of functionality. Layers are ordered in the order of first appearance, which means if an `@import` rule is importing into a layer, that layer can't be ordered if we can't allow `@layer` to come before `@import`.

**Comment by fantasai** [comment]
Ah, nevermind. I see we're allowing before as well as after.

**Comment by fantasai** [comment]
@mirisuzanne Your edits also disallow interleaving among `@layer` and `@namespace`, is there a reason for that?

**Comment by mirisuzanne** [comment]
@fantasai That was a request from @xiaochengh, as I understand it had to do with the same parsing/performance concerns mentioned above. Maybe he can speak to it more here.

**Comment by xiaochengh** [comment]
Yes, I requested that the rules should follow the exact ordering I initially proposed.

The reason is that there's no loss of functionality, and the implementation in Chromium gets much simpler.

**Comment by bramus** [comment]
I see that the spec got adjusted in https://github.com/w3c/csswg-drafts/commit/ed81c17716fa789f44cb8edac125f22cdb9a5b9a for this, but I'm a bit confused by the use of the word "They" in the note.

> Note: They are not allowed between (or intermixed with) @import and @namespace rules …

That "They", does it mean:

1. `@layer` statement at-rules (from the title of that section)?
2. `@layer` block at-rules _(mentioned as the last few words just above the note)_?
3. Both

---

A few thoughts that go with all these options:

- If option 1: then the first syntax in EXAMPLE 31 (listed just underneath it) would be invalid, no?
- If option 2: it's pretty unclear to me to know that "They" targets only this type of `@layer` at-rules. It also feels a bit redundant, as this guideline is also noted in another note above it _(“Note: `@layer` block at-rules cannot be interleaved with `@import` rules.”)_.
- If option 3: How would one append extra local CSS to the `theme` layer of EXAMPLE 31? I guess that would only be possible by creating extra sub-layers inside `theme`?

  ```css
  @layer default, theme, theme.overrides, components;
  @layer theme.overrides {
    /* Override theme "base" layer here */
  }
  
  @import url(theme.css) layer(theme);
  ```
  
  Feels weird to first have to write the overrides, and only then load its base layer.

---

I think option 2 is meant, but I'm not really sure reading all comments and logs here, as it's not explicitly mentioned 🤔

**Comment by mirisuzanne** [comment]
@bramus option 1 is the intended behavior, though it's only intended to mean that any `@import` and `@namespace` rules can't have intervening `@layer` statements. The example shows the opposite -- one `@import` between `@layer` statements -- which is allowed. I can try to add more clarity there…

**Comment by bramus** [comment]
Thanks for the clarifications on that, @mirisuzanne. Think I get it now:

```css
/* EXAMPLE 31 */
@layer default;
@import url(theme.css) layer(theme);
@layer components; /* 👈 This @layer statement here will make all subsequent @import rules be ignored. In this example however there are none */

@layer default {
  audio[controls] {
    display: block;
  }
}
```

I see that in https://github.com/w3c/csswg-drafts/commit/d9fdc1e6a7454913783e5fc6267c12b5a7c7b9b5 you changed the text to “A ''@layer'' rule that comes after …”. More precise would be “A ''@layer'' statement at-rule that comes after …”?

---

Winging back to “the @layer block at-rule” described just above it. There it reads in a note:

> Note: @layer block at-rules cannot be interleaved with @import rules.

Is that 1 @import rule in between two @layers block at-rules? If so, I somewhat read between the lines that best practice that's being hinted at is to:
1. Establish a layer order upfront using `@layer` statement at-rules
1. Group your `@import`s after that
1. Append styles to already established layers using `@layer` block at-rules

Would that be something to recommend people to do?

---

_(Apologies if I'm asking too many stupid questions regarding this. Trying to understand things correctly here. Perhaps some code-examples of what is meant by all those limitations could help?  In css-nesting-1 for example I see a lot of these “wrong examples“ with an explanation of what exactly is wrong added to them.)_

**Comment by mirisuzanne** [comment]
@bramus Yes, your summary of best practice is correct. Though another common practice is to avoid using `@import` entirely for performance reasons. :)

Only the empty layer-ordering statements are allowed before `@import`/`@namespace`, but once we encounter an `@import`/`@namespace` rule, then _either type of `@layer` rule_ will make additional `@import`/`@namespace` rules invalid. So I think the current text is correct. Basically, **you can't put anything else between `@import`/`@namespace` rules**, those have to be applied in a single block without intervening rules.

**Comment by bramus** [comment]
Thanks again for the extra input there. Current spec text indeed is correct; wanted to verify if I laid the pieces together correctly :)

**Comment by mirisuzanne** [comment]
@bramus clarified in the example. See 7726486d8
