### ISSUE TITLE
[css-highlight-api] Can errors that trigger `::grammar-error` styling be created programmatically?

### ISSUE THREAD

**Issue by tomayac** [w3c/csswg-drafts#6526]
At Google, we're required to write our interview feedback in gender-neutral language. "TC" is corp. speak for "the candidate" and when a gender-revealing word slips in your feedback, you get a "spelling error" kind of user interface that suggests you correct it.

<img width="544" alt="Screen Shot 2021-08-19 at 14 24 56" src="https://user-images.githubusercontent.com/145676/130071148-f5e736f2-bcf5-4bd0-ab91-297fb69c996f.png">

Since CSS (soon) allows one to style `::grammar-error` ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error) [the [spec](https://drafts.csswg.org/css-pseudo/#selectordef-grammar-error) is down at the time of filing this]), I wonder if the authors of _CSS Pseudo-Elements Module Level 4_ thought of letting developers trigger a grammar error somehow. Right now, it's only for errors detected by the user agent if I understand correctly.

**Comment by emilio** [comment]
Isn't this what the highlight API allows you to do? https://drafts.csswg.org/css-highlight-api/ (though the server seems having trouble atm, cc @plinss).

**Comment by tomayac** [comment]
I looked at the Custom Highlight API, too, but like the _semantics_ that come with something being a grammar error vs. a spelling error.

**Comment by emilio** [comment]
Ah, I see, so this is about triggering built-in highlights with custom ranges, right? Sorry, I misunderstood and thought you only cared about the styling of the range.

**Comment by tomayac** [comment]
This exactly, it's the built-in grammar (`::grammar-error`) or spelling (`spelling-error`) highlighting that I'm after. Simulating the styling behavior is easy (custom highlighting, or even just `text-decoration-style: wavy;`). (Fun fact: our internal tool uses a background image provided in a data URL, don't ask me why).

**Comment by mrego** [comment]
Mmm, ,would [`text-decoration-line: spelling|grammar-error`](https://drafts.csswg.org/css-text-decor-4/#text-decoration-line-property) be good enough for this?

Note that the rendering of `text-decoration: wavy red underline;` is pretty different than how a spelling error is rendering in browsers. Also on Mac spelling errors are more like `text-decoration: dotted red underline` but still they're not exactly the same (codepaths are different).

![Screenshot comparing the rendering of wavy underlines with spelling error in Chromium and Firefox on Linux, and also dotted underline and spelling error on Safari on Mac](https://user-images.githubusercontent.com/11602/135423131-59170815-4cc5-4203-a83b-9c4ab2ad3445.png)


PS: Kind of off-topic, but I'm not able to see any grammar error on browsers these days, only spelling errors appear on editable elements (maybe I haven't tested some browser and OS combination, but I did some tests with Chrome, Edge, Safari and Firefox). Anyway the web engines have still the machinery to support this, but it seems it's not being triggered.

**Comment by frivoal** [comment]
> I looked at the Custom Highlight API, too, but like the semantics that come with something being a grammar error vs. a spelling error.

@tomayac  Have you seen this somewhat recent addition to the custom-highlight api: https://www.w3.org/TR/css-highlight-api-1/#highlight-types

That gives you the flexibility to highlight whatever you want, **and** indicate that it's a spelling / grammar error semantically.

**Comment by tomayac** [comment]
Oh, thanks for the pointer. No, I hadn’t seen this before. I believe this would solve a use case like the one from the initial comment. 👍
