### ISSUE TITLE
[css-contain] Should scrollIntoView scroll to content-visibility: hidden subtree elements

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#6529]
[content-visibility: hidden](https://www.w3.org/TR/css-contain-2/#content-visibility) property skips its contents and notably says that they shouldn't be available to user agent features like find-in-page nor should they be focusable and selectable. 

It also says that if the layout work is done, then the user-agent should retain as much of that state as possible in order to make revealing the contents faster.

[scrollIntoView()](https://drafts.csswg.org/cssom-view/#dom-element-scrollintoview) says (in step 6) that as long as the element has a layout object, we scroll it into view.

The problem is that for content-visibility: hidden contents, we _may_ have a layout object or we may not, depending on whether rendering work as ever been done in that subtree. This means that the behavior of scrollIntoView is inconsistent.

I propose that we call out scrollIntoView explicitly in content-visibility section under hidden and say that calling scrollIntoView on content-visibility: hidden subtrees has no effect (or something similar)

/cc @tabatkins @frivoal

**Comment by tabatkins** [comment]
I agree; we shouldn't make this non-deterministic.

**Comment by vmpstr** [comment]
I think this may be a little more subtle than I first described. The question is do these hidden elements have a layout box? Well, we do want getBoundingClientRect to compute the right value for them since one of the use cases is to measure layout in a hidden subtree. So, when we call getBoundingClientRect we may update the rendering and generate a layout box. 

However, we don't want to do this for fragment link navigation (or any user controlled behavior), since these elements are not meant to be exposed to the user in any way. [Fragment link algorithm, step 3.4](https://html.spec.whatwg.org/multipage/browsing-the-web.html#scroll-to-fragid) uses scroll into view though, so we kind of don't want scroll into view to do anything whether or not there is a layout box generated here.

So the initial proposal is still the same: scroll into view or any scroll into view reliant algorithm has no effect on content-visibility hidden subtree, but the reasoning I think is a bit more subtle

**Comment by chrishtr** [comment]
> The question is do these hidden elements have a layout box?

Yes, the content below a `content-visibility: hidden` element have boxes. This is very important to support the cached-rendering and measurement use cases.

I agree that we should make `scrollIntoView` do nothing for hidden elements, similar to how fragment navigations do nothing. The spec could say, in step 6, "If the element does not have any associated layout box, *or is not available to user-agent features*, then return.". The "not available..." copies the spec text that is [already here](https://drafts.csswg.org/css-contain-2/#valdef-content-visibility-hidden).
