### ISSUE TITLE
[css-animations-2] Should the initial value for animation-duration be auto?

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#6530]
[css-animations-1](https://drafts.csswg.org/css-animations/#animation-duration) defines the initial value of animation-duration to be 0s. However, the web-animations specification [allows for the 'auto' keyword](https://drafts.csswg.org/web-animations-1/#dom-effecttiming-duration) which is useful for scroll-animations and group animations where the duration should be [determined automatically](https://drafts.csswg.org/web-animations-2/#duration).

Since the computed value of 'auto' for regular animations is 0s, it seems to me that we could safely change the initial value of animation-duration to be 'auto', and this would allow using a scroll-timeline animation or possibly a group effect animation without having to explicitly set the auto duration.

@birtles WDYT?

**Comment by flackr** [comment]
The one place I can think of where this would be web visible today is the getTiming() method if you were to call getAnimations() on a fill: forward css animation. e.g. https://jsbin.com/kawubir/edit?css,js,output

**Comment by birtles** [comment]
If I understand correctly, this is about introducing an `auto` keyword to the CSS syntax for `animation-duration` and mapping that to an `'auto'` value in Web Animations. I think that sounds reasonable but, like you mentioned, there is some Web compat risk.

**Comment by flackr** [comment]
@andruud noted this would also be exposed in `getComputedStyle` since we wouldn't have determined it to be 0 yet. This raises the risk of having it be the initial value as usage of `getComputedStyle` is much higher. Typically, developers would usually be reading the duration of elements animations which have durations, but if they did `let duration = parseFloat(getComputedStyle(elem).duration)` this would result in NaN for `"auto"` instead of 0 from `"0s"` :(.

Proposals:

1. We should definitely support specifying the `auto` value in css-animations for animation-duration.

2. I also think ergonomically it would be a much better initial value:
   * Time-based durations don't make sense for scroll linked animations and having to specify `auto` or a time value and rely on the [conversion from a time based animation to a progress based one](https://drafts.csswg.org/web-animations-2/#animations) is an awkward requirement, e.g. `animation: keyframes scroll()` should "just work".
   *  It results in the same duration for time-based animations.

   If we decide that we have to keep `0s` as the initial value we could update the [conversion from a time based animation to a progress based one](https://drafts.csswg.org/web-animations-2/#animations) to effectively convert `0s` animations to 100% as well, but this feels a bit more surprising especially if combined with proportion based delays.

@fantasai FYI

**Comment by fantasai** [comment]
@flackr Edits in https://github.com/w3c/csswg-drafts/commit/2a7cc4b58f903389926cb429af2f42307dced186 ; the main question I have (which isn't clear from the minutes) is whether some of these value conversions should be at computed-value time, resolved-value time, or used-value time. Currently they're specced as used-value, but if we want getComputedStyle() to return something backwards-compatible, it would need to be resolved value.

**Comment by flackr** [comment]
When we resolved we were assuming that it would be backwards incompatible if developers were reading and using the value from the computed style. Since the `auto` is passed as is as to the duration in the underlying animation, see https://drafts.csswg.org/web-animations-1/#dom-effecttiming-duration, I think it makes sense for getComputedStyle to return auto.

**Comment by cdoublev** [comment]
I [proposed](https://github.com/w3c/csswg-drafts/pull/8570) to accept `auto` as `animation-duration` in `animation` shorthand but @fantasai would like a discussion on this. I thought this issue would be appropriate, or maybe #8054 would be appropriate?

Without this change, `animation` would serialize to an empty string when `animation-duration` is `auto`, because its syntax would not allow it to represent that value. I think `auto` does not create ambiguity with other `animation` sub-properties, except `animation-name`, which is defined with lower priority for matching keywords.

**Comment by flackr** [comment]
I think #8054 would be better for `animation` short-hand discussions.

**Comment by fantasai** [comment]
@flackr I'm fine with that, I think the main risk comes from the fact that it's now the initial value. But I'm OK to close the issue and let you follow up with a new one if there is indeed a compat problem.

**Comment by sxzz** [comment]
There is a serious compatibility problem that needs to be considered.

The most recent versions of Chromium and Chrome Canary (version 115) have implemented this proposal.

Vue relied on `animation-duration` to calculate the total transition and animation duration, but it does not account for non-numeric values such as "auto".

This has resulted in the failure of Vue Transition. Try https://vuejs.org/guide/built-ins/transition.html#the-transition-component.

**Comment by fantasai** [comment]
@sxzz Is the issue about the value returned by GetComputedStyle() or something else?

**Comment by sxzz** [comment]
@fantasai Yes, the returning value of `window.getComputedStyle().animationDuration` could be `auto`, instead of the exact value.

**Comment by birtles** [comment]
Why does `window.getComputedStyle().animationDuration` return `auto` when `animation.effect.getComputedTiming().activeDuration` returns the resolved value?

**Comment by flackr** [comment]
I think it's reasonable for the computed style of animationDuration to return the computed timeline / animation dependent duration - similar to the way computed lengths are resolved to their pixel values.

**Comment by andruud** [comment]
@flackr What does that mean exactly? Isn't `auto` always effectively `0s` for time-driven animations?

So it should be enough to say that the [resolved value](https://drafts.csswg.org/cssom/#resolved-values) is the computed value with `auto`s replaced by `0s` when `animation-timeline` is `auto`? (Otherwise resolved value = computed value).

**Comment by flackr** [comment]
> @flackr What does that mean exactly? Isn't `auto` always effectively `0s` for time-driven animations?
> 
> So it should be enough to say that the [resolved value](https://drafts.csswg.org/cssom/#resolved-values) is the computed value with `auto`s replaced by `0s` when `animation-timeline` is `auto`? (Otherwise resolved value = computed value).

Yes, for time-driven animations (without group effects - which aren't shipped yet so we can defer on this part) this is enough.

For scroll driven animations, it *should* be the resolved percentage. E.g. the value you'd get from `animation.effect.getComputedTiming().activeDuration`. However, given we don't support percentages as input to `animation-duration` I think returning `auto` for all other animations for now is reasonable.

**Comment by andruud** [comment]
A given animation-duration can be associated with multiple animation-timelines due to repeats:

```
animation-duration: auto;
animation-timeline: --t1, auto;
```

What is the resolved value of animation-duration in that case?

**Comment by flackr** [comment]
I believe `animation-duration` and other animation properties are auto repeated to match up with the number of defined animation names per https://www.w3.org/TR/css-animations-1/#animation-name so I'd expect the computed style would be `animation-duration: auto, 0s;`

**Comment by fantasai** [comment]
Agenda+ to confirm @andruud's tweak in https://github.com/w3c/csswg-drafts/issues/6530#issuecomment-1587313405

**Comment by gkalpak** [comment]
I see that the latest decision is to retain backwards compatibility for `getComputedStyle().animationDuration` (returning `0s` instead of `auto`), which is great :tada:

I just wanted to mention (mostly for people that might run into this on some beta versions of Chrome/Edge) that the original proposal of having `getComputedStyle()` return `auto` for `animation-duration` breaks [CSS-based animations][1] in the [AngularJS (v1.x) framework][2].

> **Note**
> This only affects **[AngularJS v1.x][2]** (i.e. the old, end-of-life series) and _**not**_ the new **[Angular (v2+)][3]**.

##
I think this might also be useful as a data-point for future backwards compatibility considerations.

Although the AngularJS v1.x series is end-of-life, there are many (mainly enterprise) apps still running on one of the old unmaintained versions or using a patched version from a Long-Term Support provider, such as [XLTS.dev][4].

[1]: https://docs.angularjs.org/api/ngAnimate#css-based-animations
[2]: https://angularjs.org/
[3]: https://angular.io/
[4]: https://xlts.dev/angularjs

**Comment by graouts** [comment]
Should the test associated with this issue, [`scroll-animations/css/animation-duration-auto.tentative.html`](https://github.com/web-platform-tests/wpt/blob/24d22fd1a4/scroll-animations/css/animation-duration-auto.tentative.html), be marked as non-tentative now? [WPT.fyi indicates](https://wpt.fyi/results/scroll-animations/css/animation-duration-auto.tentative.html?label=experimental&label=master&aligned) that Firefox and Safari both pass 5/5, but Chrome and Edge are 4/5.
