### ISSUE TITLE
Media Queries on /TR

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6547]
On [/TR I see MQ5, MQ4, and MQ.](https://www.w3.org/TR/?title=queries&tag=css)

That could be taken to mean that MQ (== MQ3) is the latest, and indeed [the shortname mediaqueries](https://www.w3.org/TR/mediaqueries/) points to MQ3. But MQ4 is the current work and in CR, plus there is work on MQ5.

Shouldn't the shortname point to MQ4 at this point? And maybe update MQ3 wth a warning pointing to MQ4 as the current work?

**Comment by fantasai** [comment]
This seems to have been fixed. @svgeesus ok to close?

**Comment by svgeesus** [comment]
Yes, it was fixed when MQ4 was republished.
