### ISSUE TITLE
[css-nav-1] Spatial navigation explainer conflates keyboard with desktop browser

### ISSUE THREAD

**Issue by fuzzbomb** [w3c/csswg-drafts#6548]
The spatial navigation explainer has a section titled:

> Making life better for users of desktop browsers who use the keyboard to navigate

This currently limits the scope to "desktop" browsers. This likely stems from the fact that most mobile devices don't have built-in keyboards.

However many phones and tablets (iOS, Android, and others) can be operated using a keyboard (typically via Bluetooth). Web pages can be navigated on mobile browsers just like they can on a desktop computer.

I'd propose a simple edit; just drop the part about desktop browsers, so this heading reads:

> Making life better for users who use the keyboard to navigate

**Comment by anawhj** [comment]
@fuzzbomb Makes sense to me. Updated! :)
