### ISSUE TITLE
[css-scrollbars-1] i18n self review

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6554]
Short i18n review checklist is [here](https://w3c.github.io/i18n-drafts/techniques/shortchecklist.html)

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    It does not.
    
2. [x] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

   It does not.

3. [X] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    It does not.

4. [X] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    It does not.

5. [X] _If the spec (or its implementation) sorts text_

    It does not.

6. [X] _If the spec (or its implementation) captures user input_

    It does not.

7. [X] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    It does not.

8. [X] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    It does not.

9. [X] _If the spec (or its implementation) defines markup._

    It does not.

10. [X] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    It does not.

11. [X] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    It does not.

12. [X] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    It does not.

**Comment by aphillips** [comment]
The I18N WG reviewed this self-review and this spec (thank you for requesting a review) and found no issues. Thank you for being internationalized.
