### ISSUE TITLE
[css-values] Define a top-level list

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6557]
[Comma-ellision rules](https://drafts.csswg.org/css-values-4/#comb-comma) are defined in CSS Values as applicable *within a **top-level list** in a property or other CSS value, or a function’s argument list*. 

What defines a **top-level list**? Does the following definition value (from [CSS Images 3](https://drafts.csswg.org/css-images-3/#radial-gradient-syntax)) contain a "sub-level" list? Are `[]` (grouping) the only way to define a sub-level list?

```
<linear-color-stop> , [ <linear-color-hint>? , <linear-color-stop> ]#
```

The spec defines that a comma is *implicitly omissible in some circumstances, when used to separate optional terms*.

**Side notes:** imo, I think it should be *[...] to separate an optional term*, and I raised another [issue](https://github.com/w3c/csswg-drafts/issues/6425) related to the above definition value, among other things, because it prevents a gradient defined with a single color stop due to the first comma that can not be omitted, because the group is not optional.

In the above definition, the second comma can be omitted only if `[ <linear-color-hint>? , <linear-color-stop> ]` defines a top-level list and *all items preceding the comma have been omitted*. If it does not define a top-level list and it is a sub-level list, then the second comma can not be omitted.

Defining a **top-level list** would make things more clear, at least for me, I think. I can't find any other "top-level list" occurrences in CSS Values.

**Comment by tabatkins** [comment]
"top-level" meaning "not nested into a block or function". It doesn't have anything to do with the grammar itself, but rather the CSS constructs in the value.

We use the term "top-level" in other contexts, like in Variables to refer to top-level `!` values.

**Comment by cdoublev** [comment]
I was wrong in my initial comment: CSS Values does include a second occurrence of "top-level list" in *such a type [bearing a property name between quotes] does not include [...] any top-level comma-separated-list multiplier*. I guess my confusion is there, and the meaning of "top-level" is obvious. Thank you tabatkins.
