### ISSUE TITLE
[css-color-adjust-1] print-color-adjust property must be quoted in syntax

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#6558]
I'm not sure if this is a problem with Bikeshed or something else but the `print-color-adjust` property under the `color-adjust` shorthand property must be quoted.  

Currently, it renders as:
`<print-color-adjust>`

But it needs to render as:
`<'print-color-adjust'>`

https://github.com/w3c/csswg-drafts/blob/dfce5cd6ea62fec46979e287ddb8dc91ec9ffea7/css-color-adjust-1/Overview.bs#L724

**Comment by tabatkins** [comment]
That's a Bikeshed issue. I'll close the issue here and migrate this to the Bikeshed repo.
