### ISSUE TITLE
[css-cascade] [css-properties-and-values] [cssom] Define new constants for the new at rules?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6561]
Much like e.g., https://drafts.csswg.org/css-fonts/#om-fontfeaturevalues `@property` and `@layer` should probably define which constants do they return for `CssRule.type`?

I know it's deprecated etc, but we need to return _something_.

**Comment by tabatkins** [comment]
Already defined in your own spec, Emilio ^_^ <https://drafts.csswg.org/cssom-1/#dom-cssrule-type> All at-rules defined after @viewport just return 0 for that attribute (and nothing after @namespace *should* have a constant, or else we should be inlining those constants for 11-14 into CSSOM as well).

Also documented on https://wiki.csswg.org/spec/cssom-constants

**Comment by emilio** [comment]
Whoopsies, I did recall some discussion about this lol.
