### ISSUE TITLE
[css-variables-1] Specification is not clear on usage and behaviour of custom string as a CSS custom property value

### ISSUE THREAD

**Issue by k-j-kim** [w3c/csswg-drafts#6572]
Link: https://www.w3.org/TR/css-variables-1/#syntax

The specification is not clear on defining custom string as a CSS custom property value, and browser implementations are inconsistent.

## Repro:
- https://codepen.io/kj-kim-sfdc/pen/zYzBNyg

## Expected:
- ???

## Actual:
Chrome (Version 93.0.4577.63 (Official Build) (x86_64)):
```
naked:
/2.02106e+7/s/assets/images/logo-alpine-group.svg
double quotes:
"/20210629/s/assets/images/logo-alpine-group.svg"
single quotes:
"/20210629/s/assets/images/logo-alpine-group.svg"
```
Firefox (91.0.2 (64-bit)):
```
naked:
/20210629/s/assets/images/logo-alpine-group.svg
double quotes:
"/20210629/s/assets/images/logo-alpine-group.svg"
single quotes:
'/20210629/s/assets/images/logo-alpine-group.svg'
```
Safari (Version 14.1.2 (15611.3.10.1.5, 15611)):
```
naked:
/20210629/s/assets/images/logo-alpine-group.svg
double quotes:
"/20210629/s/assets/images/logo-alpine-group.svg"
single quotes:
"/20210629/s/assets/images/logo-alpine-group.svg"
```

## Suggestions:
- Specification should be clear on the expected usage and behaviour of strings in CSS custom property value.

**Comment by Loirooriol** [comment]
See #5685, https://drafts.csswg.org/css-variables-1/#serializing-custom-props

> Specified values of custom properties must be serialized exactly as specified by the author. Simplifications that might occur in other properties, such as dropping comments, normalizing whitespace, reserializing numeric tokens from their value, etc., must not occur.
> Computed values of custom properties must similarly be serialized exactly as specified by the author, save for the replacement of any var() functions.

I guess this includes string delimiters.

**Comment by tabatkins** [comment]
The spec is clear, tho the text that makes it precise is fairly recent. See <https://drafts.csswg.org/css-variables/#serializing-custom-props> for details - specifically, implementations must serialize custom properties *exactly* as originally specified.

So yeah, Chrome is buggy here.

**Comment by tabatkins** [comment]
Oh yeah, and didn't think about the quoting character used, but that should indeed be preserved here I suppose. The fact that it's not obviously stems from the same reason that the large integer is printed differently - Chrome is preserving the token values and freshly reserializing them, rather than preserving the input string.

I suspect Safari is doing the same thing, just with a larger threshold for when they flip to serializing integers with scinot, so you only see the string-delimiter difference.
