### ISSUE TITLE
[css-cascade-5] Cascade Layers need CSSOM support

### ISSUE THREAD

**Issue by anttijk** [w3c/csswg-drafts#6576]
CSSLayerRule interface needs to be specified.

**Comment by xiaochengh** [comment]
This is not entirely trivial. Since we have two types of `@layer` rules, the empty statement and the block rule, do we want the same interface for both of them, or different interfaces?

I don't have a strong preference. Just putting the options here for discussion.

---

If we use different interfaces, the following seems pretty straightforward:

```idl
[Exposed=Window]
interface CSSLayerStatementRule : CSSRule {
  readonly attribute CSSOMString names;
};

[Exposed=Window]
interface CSSLayerBlockRule : CSSGroupingRule {
  readonly attribute CSSOMString name; // empty string for anonymous layer
};
```

---

If we use the same interface, it would probably be like

```idl
[Exposed=Window]
interface CSSLayerRule : CSSGroupingRule {
  readonly attribute CSSOMString name;
  readonly attribute boolean isEmptyStatement;

  unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0); // Is this the correct syntax for override?
};
```

We need to override CSSGroupingRule.insertRule() so that it throws an exception when called on empty statements.

**Comment by tabatkins** [comment]
I think we should make them separate objects, since they have quite distinct data models - one vs N names, child rules vs not. They're the same name for authoring convenience, but that doesn't need to translate to them being the same object type.

**Comment by emilio** [comment]
I'd prefer not having two interfaces for this, fwiw... Also, for the `@layer a, b, c;` case we need a sequence of names, not just one name, right?

**Comment by tabatkins** [comment]
Yup, that's what I meant by "one vs N names". @xiaochengh's example supports that, it just exposes the N names as a single CSSOMString rather than as a list of them.

**Comment by anttijk** [comment]
Having two separate interfaces might actually make sense as there is nothing that can be shared.

CSSImportRule also needs an extension.

**Comment by emilio** [comment]
Yeah, I guess that's fine / alright, specially given we've given up on making `CSSRule.type` return something meaningful for these.

**Comment by anttijk** [comment]
On the other hand these interfaces are pretty useless anyway so I'm equally fine with a generic object that exposes nothing but cssText and the tree structure.

**Comment by emilio** [comment]
That'd be totally ok for me too.

**Comment by emilio** [comment]
FYI. Not ideal, but I needed _some_ OM support to make DevTools etc work in Firefox.

What I did for now is implementing it as:

```
interface CSSLayerRule : CSSGroupingRule {};
```

Where `cssRules` will return null for statement layers. Again, probably not ideal, it was just the easiest to implement.

**Comment by anttijk** [comment]
> ```
> interface CSSLayerRule : CSSGroupingRule {};
> ```

Did the same thing in WebKit.

**Comment by xiaochengh** [comment]
Can we prioritize this issue? We need a spec to move forward.

**Comment by mirisuzanne** [comment]
Added agenda+ to get a resolution on the approach.

**Comment by fantasai** [comment]
It seems pretty clear that we'd have (as @xiaochengh outlined above):

```
[Exposed=Window]
interface CSSLayerBlockRule : CSSGroupingRule {
  attribute somethingsomethingforthenames;
};

[Exposed=Window]
interface CSSLayerStatementRule : CSSRule {
  attribute somethingsomethingforthenames;
};
```

But the open question is, what are the somethingsomethingforthenames?

Tab suggests to have .name or .nameText or something on the group rule be a simple string (e.g. "name.subname"), which is pretty straightforward, but then for the statement rule, do we want a single string ("name1, name.subname, name3") or a list of strings ("name1", "name.subname", "name3")?

It feels pretty weird if we have the attribute on these rules both be single strings while the group rule string has commas in it and the other one doesn't. Miriam also thinks it feels more natural to have an array here. We'd prefer something like string .name for the grouping rule, and an array of strings .nameList for the statement rule. (But neither of us knows much about CSSOM interfaces.)

One point that @tabatkins  brought up was that various comma-separated things in the CSSOM (e.g. selectors, conditionText) are represented as a single list. But a) in these cases the comma represents an "or" operator, so the string is not so much representing a list of things as a single combined condition and b) none of these are trying to coordinate with a nearly-identical rule whose corresponding attribute represents a single item of the type represented in that comma-separated list.

**Comment by xiaochengh** [comment]
> We'd prefer something like string .name for the grouping rule, and an array of strings .nameList for the statement rule.

I think this is better than what I previously proposed. I wasn't aware of the array type in IDL.

**Comment by anttijk** [comment]
> We'd prefer something like string .name for the grouping rule, and an array of strings .nameList for the statement rule. 

I like these names and return types. They also match the names WebKit uses internally already.

**Comment by mirisuzanne** [comment]
@anttijk @xiaochengh @emilio let us know if the edits in 6e8482b satisfy the question here.

**Comment by foolip** [comment]
For ease of review, that's https://drafts.csswg.org/css-cascade-5/#layer-apis.

**Comment by xiaochengh** [comment]
b7c7a15c156e2df4528366bf0af8aa1bed36356c lgtm

**Comment by xiaochengh** [comment]
Wait, there's one last thing missing: We need to be able to distinguish whether a CSSImportRule is unlayered or in an anonymous layer.

How about making `layerName` nullable (`readonly attribute CSSOMString? layerName;`), so that it returns `null` when the rule is not layered?
