### ISSUE TITLE
[css-backgrounds] What is the serialization "background-position: top right 10px"?

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#6586]
https://www.w3.org/TR/css-backgrounds-3/#background-position doesn't say how the edge-relative background position values serialize (like `background-position: top right 10px`).

This is tested by css/css-backgrounds/parsing/background-position-x-computed.html and css/css-backgrounds/parsing/background-position-y-computed.html which in Gecko test that `right -10px` serializes as `calc(100% + 10px)` and `bottom -10px` serializes as `calc(100% + 10px)` but the spec does not describe this.

**Comment by emilio** [comment]
FWIW those tests were added in https://github.com/web-platform-tests/wpt/pull/16867. I agree that this is underdefined. The calc() serialization in Gecko just comes from [this line of code](https://searchfox.org/mozilla-central/rev/08c493902519265d570250c8e7ce575c8cd6f5b5/servo/components/style/values/specified/position.rs#317-320) where we remove the keywords when going from specified -> computed value.

**Comment by fantasai** [comment]
The spec defines the computed value as “list, each item a pair of offsets (horizontal and vertical) from the top left origin each given as a computed <length-percentage> value”.

The only way to serialize that would be as a pair of length, percentage or calc() values, possibly with the values 0, 0%, 50%, and 100% converted to equivalent keywords.

**Comment by fantasai** [comment]
This was edited in https://github.com/w3c/csswg-drafts/commit/0742ad6e372782b46cca9708fa293e2b5abab219
