### ISSUE TITLE
[css-values-4] How does an empty url serialize?

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#6587]
https://drafts.csswg.org/css-values/#url-empty says how empty urls (`url()`) are resolved, but not how they are serialized.

Gecko serializes as `url("about:invalid")`, WebKit and Blink serialize as the resolved url (i.e. the base URL).

**Comment by smfr** [comment]
Issue 2211 talked about this, and the IRC log says:
```
<fantasai> TabAtkins: Proposal is that the empty URL, rather than being treated as a relative URL, is treated as an invalid URL
<fantasai> TabAtkins: Computed value is still an empty string, just treated like 'about:invalid'
```

but the test `css/css-values/urls/empty.html` expects that the computed style is the the base URL. @gsnedders @emilio ?

**Comment by emilio** [comment]
Serializing to a valid URL like WebKit / Blink do seems wrong. If we do that then that breaks round-tripping.

I'm not in love with the `about:invalid` behavior, but I think it should be either that or serializing to `url()` / `url("")`.

**Comment by gsnedders** [comment]
This is a duplicate of #6447

**Comment by smfr** [comment]
Closing as duplicate.
