### ISSUE TITLE
[cssom-view] Needs more details for `offsetWidth` and `offsetHeight`

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#6588]
The [`offsetWidth` spec]:
1. Says "the **first** CSS layout box" but great if we can define what the "first" means more clearly.
2. Isn't as clear what to do when the width or height is zero as the [`getBoundingClientRect` spec] is.

From a few quick testing for an inline box:
* When the inline box is line-fragmented, all 3 impls include all fragments.
* When the [inline box contains an in-flow block-level box], Gecko includes it and also inline boxes after the block-level box, while Blink/WebKit ignore them. Blink may try to change this though.
* WebKit includes width of boxes whose height is zero, while Blink/Gecko does not.

[`offsetWidth` spec]: https://www.w3.org/TR/cssom-view-1/#dom-htmlelement-offsetwidth
[`getBoundingClientRect` spec]: https://www.w3.org/TR/cssom-view-1/#dom-range-getboundingclientrect
[inline box contains an in-flow block-level box]: https://www.w3.org/TR/CSS21/visuren.html#:~:text=When%20an%20inline%20box%20contains%20an%20in-flow%20block-level%20box

**Comment by fantasai** [comment]
* It should probably be the **principal** CSS layout box, not the “first” one.
* If all 3 impls include all fragments, then we should update the spec to do so.
* I have no opinion on whether the block-level box should be included, but the fragments after it should be if we're doing any fragments beyond the first at all.

**Comment by chrishtr** [comment]
Agenda+ to propose including the block box that does the splitting: "include the block box doing the splitting, as if it's wrapped in an inline".

The argument in favor of this is that this is how getBoundingClientRect behaves. [Example](https://output.jsbin.com/votalenepa/quiet).

**Comment by dholbert** [comment]
So to clarify... on the points-of-difference from the initial comment here, I *think* the resolution is in favor of doing this:

>     * When the [inline box contains an in-flow block-level box](https://www.w3.org/TR/CSS21/visuren.html#:~:text=When%20an%20inline%20box%20contains%20an%20in-flow%20block-level%20box), Gecko includes it and also inline boxes after the block-level box, while Blink/WebKit ignore them. Blink may try to change this though.

....and maybe also this:
>     * WebKit includes width of boxes whose height is zero, while Blink/Gecko does not.

Is that right?

**Comment by chrishtr** [comment]
Yes. It would be to include the Gecko behavior of your first quoted bullet, and the WebKit behavior of the second.

**Comment by dholbert** [comment]
Testcase for the first bullet-point (inline box containing an in-flow block-level box):
https://jsfiddle.net/dholbert/dbj3gfsL/

@chrishtr  could you (or someone) post a testcase to demonstrate the currently-WebKit-specific behavior that we're aligning with?  I'm not sure I fully understand the scenario there. (I came up with a few examples of what I thought it was discussing, but I couldn't find one where WebKit includes the width where other browsers do not.)

**Comment by dholbert** [comment]
(e.g. I thought maybe the WebKit behavior might be for something like `<span id="test"><canvas style="width:200px;height:0px"></canvas></span>`,  https://jsfiddle.net/dholbert/f4kjdwch/ , but browsers agree on the offsetWidth being 200 there.)

**Comment by chrishtr** [comment]
> @chrishtr could you (or someone) post a testcase to demonstrate the currently-WebKit-specific behavior that we're aligning with for my second quoted bullet point? I'm not sure I fully understand the scenario there. (I came up with a few examples of what I thought it was discussing, but I couldn't find one where WebKit includes the width where other browsers do not.)

I'll ask @kojiishi and get back to you...

**Comment by kojiishi** [comment]
@dholbert Sorry my original description was not clear. In the context of "width of boxes whose height is zero", I meant the "boxes" are "descendant block boxes of an inline box".

https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/normal-flow/block-in-inline-client-rects-001.html
includes 3 test cases, each for `getBoundingClientRect` and `offsetWidth`. The bullet item is about `t1.getBoundingClientRect` test case results 200 for Blink/Gecko while 500 for WebKit.

**Comment by dholbert** [comment]
> @dholbert Sorry my original description was not clear.
> https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/normal-flow/block-in-inline-client-rects-001.html includes 3 test cases, each for `getBoundingClientRect` and `offsetWidth`. The bullet item is about `t1.getBoundingClientRect` test case results 200 for Blink/Gecko while 500 for WebKit.

Gotcha - so WebKit differs from Blink/Gecko on the **getBoundingClient** behavior for this scenario with an empty descendant. But all three are in agreement on how offsetWidth behaves (and in Gecko/Chromium, it behaves consistently between offsetWidth and getBoundingClient).

Here's the live WPT test, FWIW:
Results: https://wpt.fyi/results/css/CSS2/normal-flow/block-in-inline-client-rects-001.html
Live test: https://wpt.live/css/CSS2/normal-flow/block-in-inline-client-rects-001.html

> I didn't find specific mention about the item 2 (when width or height is zero) in the IRC log

I'm not sure it was discussed; in my [question above](https://github.com/w3c/csswg-drafts/issues/6588#issuecomment-1006201558), I was trying to interpret the resolution, which just says to include the dimensions of the box, and doesn't have "unless it's zero height" exclusion.

But, yeah -- I think the point of the resolution was to **clarify how offsetWidth/offsetHeight behave** -- not to change getBoundingClientRect.  So: given that the WebKit-specific behavior here is specific to getBoundingClientRect and disagrees with the existing & uncontroversial (I think?) spec text for that feature (which is not the feature we were intending to modify here), I think it's safe to say we did *not* resolve on matching that WebKit-specific behavior.

i.e. I think the answer to my "....and maybe also this:" above is "no, not also that."

@chrishtr if you could confirm that we're on the same page, that would be helpful - thanks!

**Comment by chrishtr** [comment]
> @chrishtr if you could confirm that we're on the same page, that would be helpful - thanks!

I think your proposal is that `offsetWidth` and `offsetHeight` should include the block that causes the splitting, except that empty (zero-height) boxes are excluded.

Is that correct?

**Comment by chrishtr** [comment]
@dholbert friendly ping on the question above, thanks!

**Comment by dholbert** [comment]
Yes, I think that's essentially right -- I *think* we resolved to exclude the block-box if it's empty, for consistency with how `getBoundingClientRect` behaves.  (And I think this matches Gecko's existing behavior.)

**Comment by chrishtr** [comment]
That seems fine to me for consistency. @kojiishi is that fine from an implementation perspective in Chromium?

**Comment by kojiishi** [comment]
@dholbert:
> I think it's safe to say we did not resolve on matching that WebKit-specific behavior.
> i.e. I think the answer to my "....and maybe also this:" above is "no, not also that."

Thanks, agree.

> if the block box is zero-height, for consistency with how getBoundingClientRect behaves.

Since you said "for consistency," I think you mean "height **or width**", as currently defined in item 3 of the [`getBoundingClientRect` spec](https://www.w3.org/TR/cssom-view-1/#dom-range-getboundingclientrect). Assuming that:

@chrishtr:
> Is that fine from an implementation perspective in Chromium?

Yes, thank you.

**Comment by dholbert** [comment]
Yup, that's what I meant. Sounds like we're all on the same page - thanks!

**Comment by tabatkins** [comment]
Just confirming - @kojiishi, @dholbert, do the edits above look good?

**Comment by dholbert** [comment]
> Just confirming - @kojiishi, @dholbert, do the edits above look good?

Looks good to me, yeah. Thanks!
