### ISSUE TITLE
[selectors-4] "Grid-Structural Selectors" needs clarity as to whether it applies to tables only, or also to CSS Grid (`display: grid`)

### ISSUE THREAD

**Issue by MaximSagan** [w3c/csswg-drafts#6590]
https://drafts.csswg.org/selectors-4/#table-pseudos

Use of the term "grid" suggests we may be dealing with CSS Grid, but all examples deal with `<table>` and its children.
If these selectors do apply to CSS Grid, the spec should probably complement the `:nth-col` pseudo-selector with a corresponding `:nth-row` pseudo-selector (see #1943).

Additionally, if these selectors apply to CSS grid, as the content and structure of CSS Grid rows/columns are defined by the CSS rather than by markup (which is the case for `<table>`), there are [cyclic issues](https://github.com/w3c/csswg-drafts/issues/1943#issuecomment-342578007) that may need consideration.

**Comment by Loirooriol** [comment]
> Column membership is determined based on the semantics of the document language only: whether and how the elements are presented is not considered

makes it clear that CSS styles (including grid layout) are not considered, only the HTML (or whatever the document language) matters.

**Comment by Mint-6263** [comment]
:blush:

**Comment by tabatkins** [comment]
Yup, @Loirooriol got it.
