### ISSUE TITLE
[css-values] cap-height unit?

### ISSUE THREAD

**Issue by tbredin** [w3c/csswg-drafts#660]
I've just found out about the `ch` and `ex` units described here:
https://www.w3.org/TR/css3-values/#relative-lengths

Cap height: This is something that could become extremely useful in vertical rhythm projects such as [Sassline](https://github.com/jakegiltsoff/sassline) and [MegaType](https://github.com/studiothick/megatype), which go to great length to attempt to find this height through other means (plus a lot of manual config adjustment). When combined with `ex` (and a speculative [baseline position](https://github.com/w3c/csswg-drafts/issues/661)), we also start to build up a very useful picture of a font's vertical metrics.  

The best measure of this is usually the height of a capital `H` in any font, but could likely also fall back to `I` or `X`. 

Is this something that might be considered in future?

[Further reading on some existing issues with typographic metrics on the web](http://www.studiothick.com/essays/web-typography-is-broken)

**Comment by simevidas** [comment]
Google has proposed (and is implementing) the [CSS Step Sizing module](https://www.chromestatus.com/feature/5734273533345792), which enables “vertical rhythm using CSS”. What do you think? 😊

**Comment by SelenIT** [comment]
There is also the [CSS Line Grid module](https://drafts.csswg.org/css-line-grid/) that also provides a CSS mechanism for vertical rhythm (including baseline snapping to regular grid lines).

But I believe that having better access to the font metrics from CSS would have more use cases other than that. For example, it can be aligning the icon with text (both top and bottom) or removing extra vertical spacing before text (e.g. in the approach described [in this article](https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62#9406)) without having to use magic numbers for each particular font.

**Comment by fantasai** [comment]
RESOLVED: add cap unit to Values and Units Level 4

**Comment by tabatkins** [comment]
Added.

**Comment by karlhorky** [comment]
Thanks for this proposal for a `cap` unit for allowing font-sizing via the capital heights, really cool!

Does anyone know of any browsers that have considered or started implementation of this? I've been looking for tracking bugs, but haven't been successful...

**Comment by Crissov** [comment]
Apparently none yet. https://caniuse.com/mdn-css_types_length_cap

**Comment by SebastianZ** [comment]
I've now [created a feature request](https://bugzilla.mozilla.org/show_bug.cgi?id=1702924) to implement it in Gecko (Firefox).

Sebastian

**Comment by karlhorky** [comment]
Great, thanks @SebastianZ! Tweeted about it: https://twitter.com/karlhorky/status/1378683467098165248

**Comment by kizu** [comment]
Just wanted to note that this is currently implemented in Firefox!

There was also a ticket in Chromium for some time — https://bugs.chromium.org/p/chromium/issues/detail?id=1201220
And I did not find an existing ticket for Webkit, so I did open it — https://bugs.webkit.org/show_bug.cgi?id=245033
