### ISSUE TITLE
[scroll-animations-1] Serialization of "scroll-offsets: none" for CSSScrollTimelineRule

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#6617]
Based on the spec section of the serialization of CSSScrollTimelineRule for `scroll-offsets` descriptor [1]:
> If the scroll-offsets descriptor is missing, the empty string. Otherwise, the concatenation of the following:
> 1. The string "scrollOffsets:", followed by a SPACE (U+0020), followed by a LEFT SQUARE BRACKET (U+005B).
> 2. For each value in the list for the rule’s scroll-offsets descriptor:
>     1. The result of performing serializes a scroll timeline offset on the value.
>     2. If not the last value, A COMMA (U+002C), followed by a SPACE (U+0020).
> 3. A RIGHT SQUARE BRACKET (U+005D), followed by a SEMICOLON (U+003B), followed by a SPACE (U+0020).

So basically,
`@scroll-timeline test { scroll-offsets: 0%, 100%; }` is serialized as
`@scroll-timeline test { scroll-offsets: [0%, 100%]; }`

However, it seems this section doesn't mention `none` case. Obviously, I think we should also address the `none` case because it is the initial value and the users may specify `none` keyword (so it's not an empty string).
e.g.
`@scroll-timeline test { scroll-offsets: none; }` should serialized as
`@scroll-timeline test { scroll-offsets: none; }` (without left and right square brackets)?

Thanks.

[1] https://drafts.csswg.org/scroll-animations-1/#serialize-a-cssscrolltimelinerule

**Comment by BorisChiou** [comment]
I can upload a PR to update the words if everyone accepts this. (I think this is pretty trivial so perhaps no need to be discussed in the meeting?)

**Comment by tabatkins** [comment]
...wait, what's this about square brackets? We've never used square brackets in CSS values.

Perhaps the serialization text was written based on a misunderstanding of the use of `[]` in the CSS Value Grammar to indicate grouping?

**Comment by BorisChiou** [comment]
The square brackets are also weird to me. Perhaps we should just serialize the list directly:
e.g.
`@scroll-timeline test { scroll-offsets: 0%, 100%; }` is serialized as
`@scroll-timeline test { scroll-offsets: 0%, 100%; }`

**Comment by tabatkins** [comment]
Yes, we should, those square brackets in the serialization rules are definitely an error.

**Comment by flackr** [comment]
scroll-offsets is no longer a part of the scroll-animations-1 spec, and we're currently not planning to have any direct replacement for it.
