### ISSUE TITLE
[css-fonts] [palettes] Remove the none value from font-palette

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6622]
There are a few reasons to remove it:

1. It's unimplementable on Core Text.
2. It [was added](https://github.com/w3c/csswg-drafts/issues/4699) without WG input.
3. Clearly the font creator wants their clients to use the font's color facilities; otherwise they would not have created them.
4. One of the motivations for adding it is false: "Both SVG and COLR fonts must have a regular, uncolored glyph outline available." This is untrue - the fallback might have 0 contours. Many (perhaps even "most"!) of the color fonts we've seen have no outline fallback.
5. Another motivation was misplaced: "Many glyphs in the "emoji" range will only exist in a font with color capabilities" We already have two mechanisms for selecting non-color emoji: both variation selectors and https://drafts.csswg.org/css-fonts/#font-variant-emoji-prop. Text-style emoji is handled with font fallback, not displaying otherwise-unobservable contours inside fonts.
6. If the page author wants a non-color rendering, they can use a non-color font.

**Comment by litherum** [comment]
(Context: I'm implementing `font-palette` now in WebKit.)

**Comment by svgeesus** [comment]
All good points, I'm fine with removing it especially in response to implementer feedback

**Comment by faceless2** [comment]
`font-palette: none` came from my feedback after we implemented. 

We didn't test with a huge number of emoji fonts, but at least Segoe UI (which uses COLR) has useful monochrome outlines in `glyf` as well as well as COLR: here's U+23F0 using both:
![image](https://user-images.githubusercontent.com/989243/134027182-7b5b0edb-9209-474d-b57b-b56af0acb678.png)
`font-variant-emoji` won't help us select them; prefixing U+23F0 with U+FE0E (what we'd get if `font-variant-emoji: text` were implemented) has no effect, this isn't a sequence in the fonts GSUB table.

Obviously one glyph from one font is not be representative, but where SVG fonts are not supported Segoe UI is a likely choice for emoji. It contains useful monochrome outlines; we have a use-case where we need monochrome output; there's no existing mechanism to select them where they exist. `font-palette:none` seemed a reasonable approach.

But I appreciate the world is moving towards SVG fonts; agreed they are far less likely to have a glyf outline, there are some monochrome options available, and we now support them so our need to do this with COLOR fonts is reduced. Ultimately if it can't be implemented by anyone other than us there's no point having it in the standard, so if it's causing a problem we're fine with dropping it.

**Comment by Lorp** [comment]
> But I appreciate the world is moving towards SVG fonts

Chrome is likely NOT going to support OpenType-SVG fonts, but will instead support the new [COLRv1 fonts](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/colr), which will likely be incorporated into OpenType 1.9.

**Comment by litherum** [comment]
Pull request: https://github.com/w3c/csswg-drafts/pull/6646

**Comment by yisibl** [comment]
Maybe `font-palette: none` is useful for COLR+CPAL fonts? Please  @drott have a look.

**Comment by yisibl** [comment]
> (Context: I'm implementing `font-palette` now in WebKit.)

I am very happy to see that WebKit starts to implement font palette. https://bugs.webkit.org/show_bug.cgi?id=230446

**Comment by drott** [comment]
+1 for removing it. The semantics of `font-palette: none` for forcing a contour rendering seem odd because they have nothing to with palettes. I agree with Myles that there are other ways to achieve that for example setting a stylistic set that maps to glyph ids that map to glyph ids without color, or the other ones that Myles lists.

**Comment by khaledhosny** [comment]
With `font-palette: none` one can use the same font to render text with or without colors (there are other uses of color fonts besides emojis) without having to load the font twice or modify it.

For example, https://www.amirifont.org/fatiha-colored.html and https://www.amirifont.org/fatiha.html are the same text and the same rendering except for the colors, but each page had to use a different font. With `font-palette: none` both options can be achieved with the same unmodified font.

Color fonts need to account for environments where color tables are not used, so they should almost always have usable (though potentially degraded) un-colored support.
