### ISSUE TITLE
[css-fonts] [css-device-adapt] [palettes] FONT_PALETTE_VALUES_RULE conflicts with VIEWPORT_RULE

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6623]
https://drafts.csswg.org/css-device-adapt/#css-rule-interface has

```
partial interface CSSRule {
    const unsigned short VIEWPORT_RULE = 15;
};
```

https://drafts.csswg.org/css-fonts/#om-fontpalettevalues has

```
partial interface CSSRule { 
    const unsigned short FONT_PALETTE_VALUES_RULE = 15;
};
```

They probably shouldn't both be 15.

https://developer.mozilla.org/en-US/docs/Web/API/CSSRule/type says `VIEWPORT_RULE` is 15, so we should probably change `FONT_PALETTE_VALUES_RULE` to be something else. 17 seems to be unclaimed?

**Comment by litherum** [comment]
Is this the sort of thing that needs WG input, or can I just reassign it yolo?

**Comment by astearns** [comment]
16 was claimed for a region style rule that we abandoned.

Maybe that part should be omitted or be assigned zero?

See the note at the end of the CSSOM rule enumeration section:

> Note: The practice of using an integer enumeration and several constants to identify the integers is a legacy design practice that is no longer used in Web APIs. Instead, to tell what type of rule a given object is, it is recommended to check rule.constructor.name, which will return a string like "CSSStyleRule".

And the wiki where we used to keep track of these:

https://wiki.csswg.org/spec/cssom-constants

**Comment by litherum** [comment]
Looks like, if we had this, it would be 19. Removing it is fine, too, though.

**Comment by tabatkins** [comment]
Feel free to YOLO remove it, as the wiki page suggests.

**Comment by litherum** [comment]
Pull request: https://github.com/w3c/csswg-drafts/pull/6647
