### ISSUE TITLE
[css-fonts] [palettes] CSSFontPaletteValuesRule's maplike doesn't make much sense

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6624]
An example of `@font-palette-values` [looks like this](https://drafts.csswg.org/css-fonts/#font-palette-values):

```
@font-palette-values Cooler {
    font-family: Bixa;
    base-palette: 1;
    override-color:
        1 #7EB7E4;
}
```

The IDL [looks like this](https://drafts.csswg.org/css-fonts/#om-fontpalettevalues):

```
interface CSSFontPaletteValuesRule : CSSRule {
    maplike<unsigned long, CSSOMString>;
    attribute CSSOMString fontFamily;
    attribute CSSOMString basePalette;
};
```

Making it `maplike` doesn't make a lot of sense now that we have `override-color`. It used to make sense when we had a previous grammar that looked like this:

```
@font-palette-values Cooler {
    font-family: Bixa;
    base-palette: 1;
    1: #7EB7E4;
    2: #8EB7E4;
}
```

... But we replaced that weird syntax with `override-color`, so I think an IDL like this makes more sense:

```
interface CSSFontPaletteValuesRule : CSSRule {
    attribute CSSOMString fontFamily;
    attribute CSSOMString basePalette;
    attribute CSSOMString overrideColor;
};
```

**Comment by litherum** [comment]
CSSFontPaletteValuesRule has `maplike<unsigned long, CSSOMString>` which doesn't work with the `<string>` keys.

**Comment by litherum** [comment]
Order matters in `override-color` because of duplicates; if we keep `maplike` we'll have to figure out what happens to the map if there are duplicates, and what happens to the priority order if you insert a value.

**Comment by tabatkins** [comment]
Agree that with the changed design we should revert the complexity and just expose the `override-color` descriptor in the normal way.

**Comment by litherum** [comment]
I think this is "Needs Edits" because the current thing doesn't make sense.

**Comment by svgeesus** [comment]
Yeah this is just a case of updating the syntax and forgetting to update the IDL.

**Comment by litherum** [comment]
Pull request: https://github.com/w3c/csswg-drafts/pull/6648

**Comment by svgeesus** [comment]
Dangling text still needs to be fixed:

> ```html
> The value of the 'maplike' function [=CSS/parses=] as a <<color>>
> ```

**Comment by litherum** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/b748d044c15ea194f16b9c74a1a2df329eca5225
