### ISSUE TITLE
[css-fonts] [palettes] Should calc() or var() be allowed inside @font-palette-values?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6631]
Should authors be able to do things like `base-palette: calc(3 + 4);`?

This increases the implementation complexity, and I can't think of any use cases for it (since variables are not available in at-rules).

**Comment by Loirooriol** [comment]
Isn't `calc()` available in descriptors for free, reusing the machinery from properties? Firefox and Chromium accept `calc()` in `@counter-style`'s [`pad`](https://drafts.csswg.org/css-counter-styles-3/#counter-style-pad).

**Comment by svgeesus** [comment]
Computed GOTO considered harmful.

Palette numbers are font-specific and are determined by inspecting the font, so at that point they are known and should be considered constant values. Doing computation on them has no realistic use-case that I can see.

Using `calc()` to calculate the number of padding symbols to use for multi-digit counters on the other hand is much more reasonable.

**Comment by tabatkins** [comment]
To be fair, `env()` functions *are* available, and if we (I) ever properly define user-defined env constants, they could reasonably be piped into here.

I'm uncomfortable with special-purpose restrictions like this; they make the language more complex to learn and use. A `<number>` should be a `<number>` anywhere it shows up, ideally.

**Comment by o-t-w** [comment]
I can't think of a use case for calc(). 
Support for var() is very important. It's common to use CSS custom properties to store color values. It's overwhelmingly likely that people will want to use these color variables in conjunction with @font-palette-values.

The following code doesn't work in Safari Technology Preview 134.

```
:root {
    --yellow: lch(93% 132 94);
}

@font-palette-values --Lurid {
    font-family: bungee;
    base-palette: 0;
    override-colors:
        0 lch(76% 132 159.026),
        1 var(--yellow);
}

.lurid {
  font-palette: --Lurid;
 font-family: 'bungee';
}
```

**Comment by faceless2** [comment]
Funny, we've literally just hit the same question about 30 minutes while bring our implementation up to date with recent changes.

I agree with @o-t-w on both points; in particular I think `override-colors` is an area where `var()` is very likely to be wanted by authors, although I realise that it's more complicated than normal as it's used in an at-rule rather than a regular declaration. 

We've implemented it as a special case, reevaluating the @font-palette-values declarations at the point the font is used to expand `var()`.  But then for print output we only have to do it once, so it's not so bad. I don't know how this would work for browsers, where the var could conceivably be animating

**Comment by litherum** [comment]
As long as variables in the palette are evaluated in the context of the root element, and not the element they’re applied to (as in @o-t-w’s example), implementation shouldn’t be too difficult.

**Comment by faceless2** [comment]
This is also related - https://github.com/web-platform-tests/wpt/pull/31517. None of your recent tests covered `currentColor` so I've added a couple with this PR.

If you're going to support currentColor - and I think it's important that we do - then you're necessarily going to be reevaluating these palettes at the time of use.

**Comment by litherum** [comment]
I actually think it's important that we do _not_ reevaluating these palettes at the time of use.

**Comment by litherum** [comment]
Yeah - it's important to us that the colors inside the `@font-palette-values` rule are not re-evaluated at the time of use, but it's okay if `currentColor` will be re-evaluated at the time of use.

**Comment by drott** [comment]
CC @andruud

**Comment by andruud** [comment]
Allowing `calc()` does not really increase implementation complexity, and `env()` seems reasonable to allow as well. (But then let's consider doing that more generally, and not as a special thing for this).

However, allowing `var()` would introduce an awkward and unwanted dependency on the computed style of the root element, which we should probably avoid. It also seems a bit unfortunate from an author's standpoint to deviate from the computed-value-time/element-centric nature that `var()` currently has, and decide that it works in a different way here.

Going in the "author env()" direction seems more approachable, depending on its shape. There are other reasons we may need things like that as well, e.g. https://github.com/w3c/csswg-drafts/issues/6641.

**Comment by drott** [comment]
Filed as #6931, let's continue discussing `var()` there.
