### ISSUE TITLE
[css-fonts] [palettes] font-palette cannot be expanded in the future

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6633]
The grammar for `font-palette` is `none | normal | light | dark | <palette-identifier>`, and `<palette-identifier>` is a `<custom-ident>`. This means that, if the WG wants to add a new value `foo` to the `font-palette` property, it could conflict with a user-created `foo` palette-identifier.

I suppose the natural way to solve this is to say that if there's an `@font-palette-values` rule with the same name as one of the named values to the `font-palette` property, then the `@font-palette-values` rule wins. (This is how `@font-face` names work if there's an installed font with the same name.)

Another alternative solution would be to use a function, like:
```
font-palette: none | normal | light | dark | custom-palette(<palette-identifier>)
```

**Comment by litherum** [comment]
Making the `@font-palette-values` rule win actually might be a feature in its own right - it lets an author redefine what the "light" palette is for a particular font, rather than just using the first palette with the `USABLE_WITH_LIGHT_BACKGROUND` bit set.

**Comment by litherum** [comment]
@tabatkins might have opinions here.

**Comment by svgeesus** [comment]
Good point about future conflicts.

We solved [a similar issue](https://github.com/w3c/csswg-drafts/issues/4654) in the `color()` function by requiring [user-supplied values](https://drafts.csswg.org/css-values-4/#dashed-idents) to use [dashed ident](https://drafts.csswg.org/css-values-4/#typedef-dashed-ident)

**Comment by tabatkins** [comment]
Yeah, there's several possible methods to address this, and we've used all of them, as I outlined last month in [a similar @scroll-timeline issue](https://github.com/w3c/csswg-drafts/pull/6472#issuecomment-902831765):

1. Use dashed-ident for author-defined names, so they're guaranteed safe and separated from CSS-defined ones. (Example: `color()` keywords.)
2. Let the namespaces mingle, but author-defined wins over CSS-defined. (Example: `@counter-style` names)
3. Let the namespaces mingle, but CSS-defined wins over author-defined. (Example: `@font-face` names)

(3) is fine if we expect to expand the set rarely or never, and/or expect that the names we'd add are unlikely to be used by authors. It's better than 2 if there are security or perf reasons to want the predefined names to be well-known and immediately resolveable.
(2) is fine if we don't have the above expectation, but are okay with the possibility that an author naively uses a predefined name but accidentally gets something custom (not realizing that the name has been overridden somewhere else in the page's styles). In the case of @counter-style, we also didn't want to make a big deal of which languages we happened to predefine vs ones we forced authors to implement, for sensitivity reasons.
(1) is always safe and easy, it just clearly separates out author-defined from CSS-defined.

For this, I don't see a particular reason not to go with (1); it seems like the easiest route.

> Making the @font-palette-values rule win actually might be a feature in its own right - it lets an author intentionally redefine what the "light" palette is for a particular font, rather than just using the first palette with the USABLE_WITH_LIGHT_BACKGROUND bit set.

This is legitimate, tho we can mix it up with dashed-ident if we'd like, defining light/dark to be specifically overrideable while the other keywords aren't.  Or we could make them all overrideable; I don't have a strong opinion. CSS doesn't have a precedent.

**Comment by litherum** [comment]
It sounds like one of the things you're saying is that dashed idents are always superior to functions for solving this kind of problem?

**Comment by tabatkins** [comment]
Most of the time, yeah. Functions let you give greater naming context to the keyword, which is useful if you're mixing together multiple user-defined keywords or using them in multiple places that are only loosely connected. In cases like this, tho, dashed-ident is definitely better than a function.

**Comment by litherum** [comment]
dashed ident sounds fine to me.

**Comment by litherum** [comment]
Pull request: https://github.com/w3c/csswg-drafts/pull/6653
