### ISSUE TITLE
[css-fonts] [palettes] How should animating the font-palette property work?

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#6634]
If you animate from `font-palette: light` to `font-palette: dark`, should it flip halfway, or should each of the colors in the palette animate smoothly?

The grammar of the property is `font-palette: none | normal | light | dark | <palette-identifier>`, so if we animate smoothly, intermediate values in the animation might not be representable (without having to construct a new `@font-palette-values` rule).

**Comment by litherum** [comment]
Oh, the property says:

> Animation type: | discrete

So I guess that answers that.

**Comment by drott** [comment]
See #8922 for our proposal for animating `font-palette`.
