### ISSUE TITLE
[css-color-4] Ambiguous definition of D65 white point

### ISSUE THREAD

**Issue by kdrag0n** [w3c/csswg-drafts#6640]
In #5922 (related to https://github.com/LeaVerou/color.js/issues/87), the XYZ <-> sRGB conversion matrices were recalculated to use the sRGB specification's definition of D65: xy 0.3127, 0.3290. The [Sample code for color conversions section of the spec](https://www.w3.org/TR/css-color-4/#color-conversion-code) is currently using the sRGB D65-based matrices. As mentioned in #5922, [matrixmaker.html](https://drafts.csswg.org/css-color-4/matrixmaker.html) was used to calculate the matrices in February.

However, matrixmaker.html was later updated to use ASTM D65 again in commit 55e497b217f03bff5f534744719d6a7b019c18c3, so the calculated matrices are now different from the CSS Color 4 spec. Is this intentional, or is one of them wrong?

I realize that this issue is similar to #6618, but the scope is much smaller and this is likely a trivial fix as compared to the other issue. Feel free to close this issue if you think it's a duplicate.

**Comment by facelessuser** [comment]
I believe this is also being discussed here: https://github.com/w3c/csswg-drafts/issues/6618

**Comment by Myndex** [comment]
Hi @kdrag0n Danny

> I realize that this issue is similar to #6618, but the scope is much smaller and this is likely a trivial fix as compared to the other issue. Feel free to close this issue if you think it's a duplicate.

That is actually what prompted #6618, when I noticed that the matrixes were calculated to a different WP.

I think right NOW the correct white point is from CIE 2004 

> White chromaticity | 0.31272 | 0.32903 | (D65)

It's never ending... example, yesterday I received files for a current film project, with the white point indicated as 0.313, 0.329

😳

**Comment by kdrag0n** [comment]
@Myndex

> I think right NOW the correct white point is from CIE 2004
> > White chromaticity | 0.31272 | 0.32903 | (D65)

Interesting, I've never seen that definition before. Personally, I think it's best to use either sRGB/P3 white (which makes sense for CSS Color 4) or ASTM D65 (seemingly used to derive some modern color appearance models; at least, this is what I observed for ZCAM/Jzazbz) in this case, but I don't think it matters much as long as it's internally consistent.

The reference code for CSS Color 4 is currently using sRGB/P3 white consistently, so nothing is actually wrong with it. It's just odd that matrixmaker.html was changed later and no longer agrees with the sample code or GitHub issues.

**Comment by svgeesus** [comment]
As another data point, an early draft of ISO TC 42/WG 23 **"Part 5: High Dynamic Range and Wide Colour Gamut encoding for still images (HDR/WCG)"** states:

<html>
<body lang="en-US" link="#0000ff" dir="ltr">

Reference 				white | D65 				per ISO 11664-2:2007 | 0.3127 | 0.3290
-- | -- | -- | --

</body>
</html>

**Comment by svgeesus** [comment]
> However, matrixmaker.html was later updated to use ASTM D65 again in commit 55e497b, so the calculated matrices are now different from the CSS Color 4 spec. Is this intentional, or is one of them wrong?

It was. matrixmaker.html has no official status whatsoever (it is just a scratch utility that I threw together), and the fact that it currently has the ASTM white points just reflects the most recent edit that I made while investigating the effect on the various RGB to XYZ and Bradford transform matrices.

**Comment by svgeesus** [comment]
> I think right NOW the correct white point is from CIE 2004

>    White chromaticity | 0.31272 | 0.32903 | (D65)

The values from CIE 15:2004 are indeed what is in the normative part of CSS Color 4, for example [the definition of rec2020](https://drafts.csswg.org/css-color-4/#valdef-color-rec2020). Although, CIE 15:2004 also tells you to go calculate the values yourself (using the 1nm or 5nm spacing, and with details of the resampling algorithm unspecified).

However, Rec BT.2020 actually specified `0.3127 | 0.3290`

@kdrag0n Thanks for raising this, but I'm going to close this as effectively a dup of #6618 if that is okay.
