### ISSUE TITLE
[css-overflow][css21] overflow:hidden SHOULD or MUST not be scrollable?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#666]
Via language that was carried over from css2, `overflow: hidden` is [specified in css-overflow as](https://drafts.csswg.org/css-overflow/#valdef-overflow-hidden) (emphasis mine):

> This value indicates that the content is clipped and that no scrolling user interface **should** be provided by the UA to view the content outside the clipping region. However, the content may still be scrolled programatically, for example using the mechanisms defined in [CSSOM-VIEW]. 

I do not believe that this **should** is intentional, so we ought to replace it with **must**. `overflow: hidden` isn't meant to be scrollable except via script. Or is it?

I'm asking because iOS has a bug where it is scrollable in some corner cases. But if we have **should** rather than **must**, then maybe it is not a bug.

References:
- [demo of the bug](https://bug-153852-attachments.webkit.org/attachment.cgi?id=270644)
- [webkit bug](https://bugs.webkit.org/show_bug.cgi?id=153852)
- [proposed test case](https://github.com/w3c/csswg-test/pull/1079)

**Comment by frivoal** [comment]
Agenda+, because this ought to be easy and then we can move on.

**Comment by smfr** [comment]
I don't think the iOS behavior was intentional. I'm OK with making this a MUST.

**Comment by frivoal** [comment]
Spec updated in to match in commit af1704db040090f3fea9a11c34ffc4bd06fb2ebf
