### ISSUE TITLE
[css-color-5] `in <space>` syntax for `linear-gradient()` et al

### ISSUE THREAD

**Issue by surma** [w3c/csswg-drafts#6667]
The nice thing about `color-mix()` is that it allows you to specify colors in a different color space then the color space in which the interpolation happens. As far as I can tell, `linear-gradient()` et al will always interpolate in RGB space, and I can’t find any changes to `linear-gradient` in CSS Color 4 or 5. Would it be feasible to add a `in <space>` syntax to `linear-gradient()`, similar to what `color-mix()` supports?

Here’s what gradients from blue to green would look like (I used JavaScript to generate these gradients using `color-mix()`):

<img width="1680" alt="Screen Shot 2021-09-22 at 16 31 00" src="https://user-images.githubusercontent.com/234957/134374638-b9a4ca73-b902-4f09-ad12-0484cf502d0c.png">

cc @argyleink

**Comment by svgeesus** [comment]
Yes, there should totally be an `in colorspace` keyword added to gradients, to override the current sRGB default for legacy colors.

I think this is already discussed in [Consider allowing gradients to include a color space for interpolation to take place in](https://github.com/w3c/csswg-drafts/issues/5833) and also [Don't force non-legacy colors to interpolate in a gamma-encoded space](https://github.com/w3c/csswg-drafts/issues/6094) and [Question: in what color space will gradient interpolation occur?](https://github.com/w3c/csswg-drafts/issues/6094)

But that change would happen in CSS Images 4, not in Color 4 or 5.

**Comment by surma** [comment]
Ah good to know. If it’s already decided, then I’m happy to let this be closed.

**Comment by svgeesus** [comment]
Sadly there is a lag between "already decided" and "already in the spec" and you should not be required to be psychic or have attended every call for the last 5 years.

So I'm going to re-tag it to Images 4, and leave it open until done.
