### ISSUE TITLE
[CSS-SCROLLBARS] Some scrollbars aren't accessible for interactions

### ISSUE THREAD

**Issue by gregwhitworth** [w3c/csswg-drafts#6675]
Hello,

We had an [issue](https://github.com/openui/open-ui/issues/404) filed on Open UI about enforcing accessible scrollbars. While we have requested the site from the person that filed it; it does indicate a potentially lax spec text.

In the telecon today regarding this topic (if Open UI was the right venue for such a discussion) we denoted that the spec text could have more text around increased hit-targets or even possibly over-riding the min/max regions to match a "usable" behavior. Likewise I recommend that the following change be made:

> The scrollbar should nonetheless remain wide enough to be usable. 

change to:

> The scrollbar **MUST** be wide enough to be usable when a user begins to interact with it.

As noted we can add in more insights and even potentially recommended dimensions based on studies that I'm sure companies within this group have done to inform the design guidelines for their scrollers.

**Comment by summercms** [comment]
Came across a different issue with a scrollbar - I thought I'd share!

![image](https://user-images.githubusercontent.com/57409060/135094817-4373f70a-df68-45bd-9287-b3ac92b407f4.png)

The scrollbar on the website I thought didn't exist due to it being almost the same colour as the web page.

The CSS Spec should also include WCAG 2.0 level AA requirements.

**Comment by gregwhitworth** [comment]
@tantek so @summercms has provided other examples [here](https://github.com/openui/open-ui/issues/404#issuecomment-926596337) and looking through them they seem to be using `-webkit-scrollbar` to set this. I think we should update the spec as I denote above and have a note that references prefixed scrollers.

**Comment by frivoal** [comment]
I am not convinced that *should* vs *must* here will make much of a difference in this case, as this is not really an objectively testable assertion. But I don't have an issue with the intent of the change either. Agenda+

**Comment by frivoal** [comment]
Addressed in https://github.com/w3c/csswg-drafts/commit/3eec18f4b0c67896245cefaef20689a4d6d71598
