### ISSUE TITLE
[selectors-4] broken link

### ISSUE THREAD

**Issue by gunnarbittersmann** [w3c/csswg-drafts#668]
In <https://drafts.csswg.org/selectors-4/#the-active-pseudo>, the link “list of activatable elements” to <http://www.whatwg.org/html/selectors.html#selector-active> is broken.
Other references to the HTML spec refer the W3C spec. I’m not sure if there a special ist of activatable elements in the W3C spec. Maybe the link should point to <http://w3c.github.io/html/matching-html-elements-using-selectors.html#pseudoclasses>?

**Comment by frivoal** [comment]
Whether we should point to one or the other of the specs is a question I'll leave to others.

The link you highlighted for the w3c spec is the right one.
For the whatwg one, it would be this one instead: https://html.spec.whatwg.org/multipage/scripting.html#selector-active

**Comment by fantasai** [comment]
WHATWG keeps moving their spec around, but seem to have set up redirects now. Should we blanket-update all our links to the WHATWG spec or leave things as-is?

**Comment by xfq** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/2781913171c06f63981080231acf2d59c262941a
