### ISSUE TITLE
[cssom] "Let list be a list of CSS component values belo..."

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#670]
https://drafts.csswg.org/cssom/#serializing-css-values

> Let list be a list of CSS component values belonging to &lt;counter&gt;, omitting the last CSS component value if it is "decimal"\.

Browsers disagree on this it seems. Test at http://w3c-test.org/cssom/serialize-values.html

Should decide which one to do and either fix the spec or the test.

cc @jdm

**Comment by csnardi** [comment]
It looks like Firefox is the only browser disagreeing with the spec.

Probably easiest and makes the most sense to just change the test.

**Comment by emilio** [comment]
cc @upsuper

**Comment by upsuper** [comment]
Firefox isn't the only browser disagreeing with the spec, fwiw. Safari also passes that test which means it has the same behavior as Firefox here. But I agree that the spec makes sense on this, and it also matches the "shortest serialization" principle the group reaffirmed in #1564, so we should update the test and fix Firefox.

**Comment by csnardi** [comment]
I think this can be closed out now, since Firefox has changed and so has the test, so all that is left is WebKit.

**Comment by zcorpan** [comment]
Filed 
https://bugs.webkit.org/show_bug.cgi?id=184256
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16717601/
