### ISSUE TITLE
[css-flexbox] Allow multiple serialized representations of flex-grow|shrink

### ISSUE THREAD

**Issue by svillar** [w3c/csswg-drafts#6706]
Both Firefox and WebKit-based browsers fail [a couple of tests](https://wpt.fyi/results/css/css-flexbox/parsing?label=master&label=experimental&aligned&q=flex-%28grow%7Cshrink%29-computed) because of the way the `flex-grow` and `flex-shrink` properties are serialized.

For example, the specified value is using 2.34e+06 notation while the computed value is 2340000. I think the specs should allow both representations as valid, mainly because of the way engines work. If we only allow the specified value as valid representation then we'll be forcing engines to store that value (or something that refers to the actual notation used to represent the number) just for the `getComputedStyle()` call.

I have a [PR open](https://github.com/web-platform-tests/wpt/pull/28695) since April for WPT tests but I believe the spec editors are the ones to make the call and decide whether or not to allow those multiple representations.

**Comment by svillar** [comment]
Note that this could be generalized to any other property, I'm just unsure about the implications so I preferred to restrict it to these two properties at least as a first step (although it's true it could create some inconsistencies with other props).

**Comment by Loirooriol** [comment]
According to https://drafts.csswg.org/cssom/#serialize-a-css-component-value,

> scientific notation is not used

so the test would be wrong. But this probably needs to change in #6471.

**Comment by tabatkins** [comment]
This is a more generic CSSOM issue; I absolutely do not want to have special rules for number serialization for some properties in particular, unless there's strong webcompat issues forcing our hands.

I'll go ahead and close this in anticipation of #6471 handling this, as Oriol said; if there *are* indeed webcompat concerns for these properties in particular, lmk and we can reopen and discuss.
