### ISSUE TITLE
Editors drafts are down

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-drafts#6725]
https://drafts.csswg.org/css-sizing-4/, for example.

**Comment by svgeesus** [comment]
Down again, during the call

**Comment by plinss** [comment]
Kicked, will be up shortly

**Comment by svgeesus** [comment]
Down just now

**Comment by plinss** [comment]
Kicked, will be up shortly

**Comment by svgeesus** [comment]
Down just now

**Comment by plinss** [comment]
Kicked, will be up shortly

**Comment by svgeesus** [comment]
Down again

**Comment by plinss** [comment]
Up again.

**Comment by svgeesus** [comment]
Thanks!

**Comment by svgeesus** [comment]
Down just now

**Comment by plinss** [comment]
Fixed

**Comment by svgeesus** [comment]
Down again

**Comment by plinss** [comment]
Fixed

**Comment by SebastianZ** [comment]
And again. 😞

**Comment by plinss** [comment]
Fixed

**Comment by SelenIT** [comment]
Unfortunately, the problem returned 😢

Maybe it's possible to create a static copy/cache of the last stable state of the drafts website for such cases?..

**Comment by plinss** [comment]
Fixed. There's already a plan to generate static copies, we just need someone to fund to work of actually doing it.

**Comment by simevidas** [comment]
Nicole Sullivan, who co-leads the Chrome UI Fund, [suggested](https://twitter.com/stubbornella/status/1481656066643402762) that they could potentially fund this work. It might be worth a try.

**Comment by faceless2** [comment]
https://drafts.csswg.org/css-gcpm-3/ is down

**Comment by svgeesus** [comment]
Down again

**Comment by svgeesus** [comment]
Down again

**Comment by simevidas** [comment]
For me, it was down yesterday (~16 hours ago) and it’s down right now. If this is a single, continuous down period, that’s unusually long.

**Comment by svgeesus** [comment]
Ok, different this time. Individual drafts are available if you go directly to them, but the main page says

> CSS Working Group Editor Drafts
>
> No specification drafts in the repository.`

**Comment by svgeesus** [comment]
> For me, it was down yesterday (~16 hours ago) and it’s down right now. If this is a single, continuous down period, that’s unusually long.

![image](https://user-images.githubusercontent.com/2506926/156793353-c6b2cd62-5835-4b2d-a459-aec4d8594abf.png)
