### ISSUE TITLE
[css-borders] accept "px" for pixel values in `border-image-slice`

### ISSUE THREAD

**Issue by jsnkuhn** [w3c/csswg-drafts#6739]
Currently `border-image-slice` only allows pixel values to be used through unit-less number values. I'm guessing there was a reason for this but in practice I have found it just confuses people and leads to them not using `border-image`.

The only concern is that there might be border-image code lying dormant on pages because folks just couldn't figure out why it wasn't working with a "px" value on pages. If folks left in to deal with later it would just start working if "px" support was added. If all of the `border-image`s values were not worked out because they couldn't get the image to show things might appear broken in these cases. 

https://www.w3.org/TR/css-backgrounds-3/#border-image-slice

**Comment by tabatkins** [comment]
I don't recall the exact reasoning, but I'll note that SVG's "abstract units" *are* just `px` anyway in CSS, so yeah, we could just do that.

**Comment by fantasai** [comment]
If we allowed a `<length>` then my expectation would be that it represents that length at the image's native resolution. That means `px` units wouldn't correspond to image pixels, and that would probably be quite confusing.  So I don't think we should do this.

**Comment by jsnkuhn** [comment]
I'm still confused. What is fundamentally different about `border-image-slice` that it requires this unit less value? `border-width: 1px;` doesn't seems to cause any confusion. Even other instances where images are used, like spiriting background images, don't use the unit-less value and there doesn't seem to be an issue?

**Comment by SebastianZ** [comment]
I believe it makes sense to allow pixel values in that case as well. As @jsnkuhn pointed out earlier, the CSS pixels vs. image pixels applies in other situations as well, so authors should already be aware of that.

Sebastian

**Comment by dbaron** [comment]
The basic difference here, I think, is that these values are intended to be image pixels, not CSS pixels.  These are fundamentally different thing.

The example of background image spriting using `background-position` is different -- in that case the use of `background-size` would scale the image and thus change what the `background-position` values mean in terms of image pixels.  In this case things that scale the image do not change the offsets within the image because they are offsets of image pixels, not offsets in terms of CSS lengths.

**Comment by astearns** [comment]
I am going to close this issue because it is not likely that we will introduce an “image pixel” value for this particular case only. But if there are other use cases for representing image pixels in CSS values we could re-open this discussion.
