### ISSUE TITLE
[css-pseudo-4] [css-highlight-api-1] Integrating custom highlights into css-pseudo-4

### ISSUE THREAD

**Issue by dandclark** [w3c/csswg-drafts#6755]
Should the custom `::highlight` pseudos be mentioned among the other highlight pseudos defined at https://drafts.csswg.org/css-pseudo-4/#highlight-selectors?

Custom highlights are different from the other pseudos in that they have their own standalone spec, but it seems like there should be at least a note about them in [css-pseudo-4] where the other highlight pseudos are covered.

I attempted to integrate them here: https://github.com/w3c/csswg-drafts/pull/6754. Not sure if that is the right approach.

cc @sanketj @frivoal

**Comment by frivoal** [comment]
There's a note at the end of https://drafts.csswg.org/css-pseudo-4/#highlight-selectors saying
> Note: A future level of CSS may introduce ways to create custom highlight pseudo-elements.

I'd suggest updating the note to point to css-highlight-api-1, but keeping the two specs separate, at least for now, as they are maturing at different speeds. There are many more things than highlights in css-pseudo, and we should be able to enter (and exit) CR for css-highlight-api-1 faster if we don't tie it to the rest of css-pseudo-4.

**Comment by fantasai** [comment]
@frivoal They kinda depend on each other, right? The highlight API doesn't do a whole lot if you can't paint the highlights you're defining. Cross-referencing the specs seems fine.

**Comment by fantasai** [comment]
@dandclark I merged your PR and added some tweaks. @sanketj would you mind looking things over, and adjusting as you see fit?

**Comment by sanketj** [comment]
@fantasai @dandclark The updates LGTM, thanks!
