### ISSUE TITLE
Scroll anchoring opt out / exclusion API (overflow-anchor)

### ISSUE THREAD

**Issue by skobes** [w3c/csswg-drafts#676]
Scroll anchoring is a mechanism for preventing visible jumps from offscreen content changes, described in detail [here](https://github.com/skobes/ScrollAnchoring/blob/master/explainer.md) and at [https://skobes.github.io/ScrollAnchoring/](https://skobes.github.io/ScrollAnchoring/).

This is a proposal to define the CSS overflow-anchor property as described in the spec.  Please report any concerns about the design here, or under [https://github.com/skobes/ScrollAnchoring/issues](https://github.com/skobes/ScrollAnchoring/issues), or on the [blink-dev intent-to-ship thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/VJmxBRYGVIE/CogbbYWXCAAJ), or on the [tag review thread](https://github.com/w3ctag/spec-reviews/issues/142), or on the [WICG transfer proposal](https://discourse.wicg.io/t/proposal-scroll-anchoring/1752).

**Comment by RByers** [comment]
Note that we're shipping this in Chrome 56 despite failing to get much feedback from other engines.  Given the user [enthusiasm ](https://mobile.twitter.com/simevidas/status/799510987460214785), I suspect there will eventually be more interest.  The actual API surface area is tiny and rarely needed, so I'm optimistic we can continue to incubate, including making breaking changes if it becomes  necessary to get interop in the future.

**Comment by FremyCompany** [comment]
I provided some feedback during last TPAC, but I just had a look and the spec is in much better shape now than it was back then. I am glad Google decided to went with it and get the feature used in the wild. Please report the experiments results further when you have them!

I am not a huge fan of the anchor node heuristic but I want to see the feature being used by more users and get feedback on how often it mistriggers before making another proposal; I don't want to create work just for the sake of creating work.

**Comment by RByers** [comment]
Thanks Francois!  Yeah there are a ton of tough tradeoffs around web compat here.  We will learn a lot more as this makes it to Chrome stable and we get more feedback from users and developers.  We'll keep iterating [here](https://skobes.github.io/ScrollAnchoring/).  

If you think Edge may be interested in working with us more on this, then perhaps we should move the repo to the WICG to get some basic IP protection?  If so just express Microsoft interest [on WICG discourse](https://discourse.wicg.io/t/proposal-scroll-anchoring/1752).

**Comment by FremyCompany** [comment]
I am not aware of such plans and I am not the right person to chime further on this, scroll being a feature that does not belong to the layout team. But a successful experiment would help drive traction, of course.

**Comment by RByers** [comment]
Note the spec and explainer are now here: https://github.com/WICG/ScrollAnchoring

**Comment by xfq** [comment]
Should we close this issue now?
