### ISSUE TITLE
[css-color-4] L as `<percentage>` in `lab()` and `oklab()`

### ISSUE THREAD

**Issue by danburzo** [w3c/csswg-drafts#6761]
In the context of [adding `oklab()` and `oklch()` syntaxes](https://github.com/w3c/csswg-drafts/issues/6642), which use `<percentage>` for the L channel that maps to its canonical `[0, 1]` range, the decision to use `<percentage>` for the L in `lab()` and `lch()` ([previously discussed](https://github.com/w3c/csswg-drafts/issues/4477)) to map to its canonical `[0, 100]` range feels inconsistent.

Since the spec has recently included a [breaking change in the definition of `color(xyz)`](https://github.com/w3c/csswg-drafts/issues/6722), now might be a good opportunity to revisit the decision to use `<percentage>` in `lab()` and `lch()`? (Safari 15 being the only major browser to have shipped all these things.)

The decision also impacts the usage of `color()` if [these color spaces will be allowed as identifiers](https://github.com/w3c/csswg-drafts/issues/6741), since you're allowed to use either `<number>` or `<percentage>` for the Lightness channel. 

I think the simplest way forward is to let `l`, `a`, and `b` in `lab()` and `oklab()` all be `<number>`s on their own scale. Authors already have to consult reference materials for the useful range of a/b/chroma for each theoretically-unbounded color space, so the _L as percentage_ abstraction doesn't do much to ease that, while making interop with non-web applications (if not the Color API) less straightforward.

I don't think consistency with `hsl()` in regards to lightness being a percentage is worth breaking the `<number> = <percentage> / 100` convention present throughout the other color syntaxes.

**Comment by weinig** [comment]
As a point of experience, though no real thought out opinion, when implementing support for OKLab in WebKit this week, this bit me briefly (all the resulting colors were very extremely white) and needed to add a divide by 100.

The only real downside of using a percentage here in my mind is if it trips users up when pasting in component values from another tool (say, something like https://colorjs.io/apps/convert/?color=lime&precision=4 which uses the unit notation).

One concrete thing you might want to consider is updating the sample code to call out this difference.

**Comment by svgeesus** [comment]
> oklch(86.6% 29.1 142.1)
oklch(86.6% 29.1% 142.1)
oklch(86.6% 41.15 142.1)
oklch(86.6% 0.291 142.1)

> Currently, for CSS Color 4 the last of those is correct. The chance that people mess this up in one way or another and end up with an off-by-100 error when simply copying colors into CSS is large.

I literally just made that mistake (again) when adding the section on resolving OKLab and OKLCH values.

> The only real downside of using a percentage here in my mind is if it trips users up when pasting in component values from another tool

Yes, this is exactly my concern

> (say, something like https://colorjs.io/apps/convert/?color=lime&precision=4 which uses the unit notation).

That tool can be and should be updated, because it primarily tracks CSS and other Web Platform rather than color in general. But other tools will _present OKLab values as defined in the OKLab specification_ which frankly should not surprise anyone.

> One concrete thing you might want to consider is updating the sample code to call out this difference.

Good idea.

**Comment by svgeesus** [comment]
We do [already have](https://drafts.csswg.org/css-color/#ok-lab)

> Like CIE Lab, there is a central lightness axis which is usually written as a unitless number in the range [0,1]; for compatibility with the rest of CSS, it is written as a percentage. 100% means an L value of 1.0. L=0% is deep black (no light at all) while L=100% is a diffuse white.

**Comment by svgeesus** [comment]
I expect to further clarify this aspect once https://github.com/w3c/csswg-drafts/issues/6741 is resolved (assiming we resolve to add the reference percentage ranges)

**Comment by svgeesus** [comment]
Spec is now updated: [Lab](https://drafts.csswg.org/css-color-4/#specifying-lab-lch) and [OKLab](https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch)

**Comment by svgeesus** [comment]
> One concrete thing you might want to consider is updating the sample code to call out this difference.

In addition to the clarified spec prose, the sample code now has, for OKLab:

```js
return multiplyMatrices(LMStoOKLab, LMS.map(c => Math.cbrt(c)));
	// L in range [0,1]. For use in CSS, multiply by 100 and add a percent
```

and for CIE Lab:

```js
return [
		(116 * f[1]) - 16, 	 // L
		500 * (f[0] - f[1]), // a
		200 * (f[1] - f[2])  // b
	];
// L in range [0,100]. For use in CSS, add a percent
```
