### ISSUE TITLE
[css-color-4] Defer @color-profile to L5

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6765]
Unlike the other color formats in Color 4, custom color spaces (`@color-profile`) have far less implementor interest, but still complicate a lot of our discussions and hold the spec back.

@svgeesus and I think we should defer this functionality to Level 5. Agenda+ for group resolution.

**Comment by LeaVerou** [comment]
> Only significant issue with punting is that it means we're back to `device-cmyk()` having no way to resolve intelligently; at level 4 we'd have to mandate it resolves in a UA-specific manner, using the naive conversion rules unless the UA has reason to do something different for the user.

What prevents us from punting that as well?

**Comment by tabatkins** [comment]
Punting the entire function? Allowed, I suppose, but I thought it had implementations.

**Comment by LeaVerou** [comment]
> Punting the entire function? Allowed, I suppose, but I thought it had implementations.

Not in browsers AFAIK, but possibly in print formatters.

**Comment by faceless2** [comment]
FWIW it makes no difference to us which level `device-cmyk` is in, or @color-profile.

All other print formatters already have existing (non-standard) cmyk functions, so I'm presuming that the drive to add `device-cmyk` to those is going to be implementation in the browsers.

**Comment by svgeesus** [comment]
A [quick `device-cmyk` test](https://codepen.io/svgeesus/pen/KKvBwXB?editors=0100) fails in Safari 15, Firefox 95 and Chrome 97, and passes in BFO Publisher.

**Comment by svgeesus** [comment]
The [Inkscape documentation](http://tavmjong.free.fr/INKSCAPE/MANUAL/html/Attributes-Fill-Stroke.html#Attributes-Color) seems very out of date (2017, with lots of "not updated for version 0.91") but from what I can see it does _not_ implement `device-cmyk` or  `color()` (and thus, not `@color-profile` either).

**Comment by GPHemsley** [comment]
@svgeesus [`<color>`](https://www.w3.org/TR/css-color-4/#typedef-color) still mentions `<device-cmyk()>` (with a link to css-color-5). The [introduction](https://www.w3.org/TR/css-color-4/#introduction) and the [definition of "rectangular orthogonal color"](https://www.w3.org/TR/css-color-4/#rectangular-orthogonal-color) also still mention CMYK/KCMYGOV/CMYKOGV. Is that intentional, or an oversight?

**Comment by LeaVerou** [comment]
> @svgeesus [`<color>`](https://www.w3.org/TR/css-color-4/#typedef-color) still mentions `<device-cmyk()>` (with a link to css-color-5). The [introduction](https://www.w3.org/TR/css-color-4/#introduction) and the [definition of "rectangular orthogonal color"](https://www.w3.org/TR/css-color-4/#rectangular-orthogonal-color) also still mention CMYK/KCMYGOV/CMYKOGV. Is that intentional, or an oversight?

Oversight.

**Comment by svgeesus** [comment]
Already fixed in the Editors Draft: [introduction](https://w3c.github.io/csswg-drafts/css-color-4/#introduction) and fixed just now in [definition of rectangular orthogonal color](https://w3c.github.io/csswg-drafts/css-color-4/#rectangular-orthogonal-color)

**Comment by GPHemsley** [comment]
> Already fixed in the Editors Draft: [introduction](https://w3c.github.io/csswg-drafts/css-color-4/#introduction) and fixed just now in [definition of rectangular orthogonal color](https://w3c.github.io/csswg-drafts/css-color-4/#rectangular-orthogonal-color)

I take it you've noticed the usual editor's draft links are currently MIA? :)

**Comment by svgeesus** [comment]
> I take it you've noticed the usual editor's draft links are currently MIA? 

They have been intermittently broken for over a year. That is why I linked to an alternative (and reliable) location.
