### ISSUE TITLE
[css-fonts-4] definition for src descriptor and local(), data()

### ISSUE THREAD

**Issue by PeterCon** [w3c/csswg-drafts#677]
The syntax for the @ font-face src descriptor value is given as

[ <url> [ format( <string> # )]? | <font-face-name> ] #

Later in the css-fonts-4 draft, in "Terms defined by reference", it states that <url> is defined in css-values-3. This is a useful addition since fonts level 3 gave no specification for this.

However, css-fonts-3 and the css-fonts-4 draft also discuss use of a src value with "local(...)". The css-values-3 doesn't mention this. Thus, formally per these specs, it's not clear how "local(...)" is syntactically valid, even though it appears that the intent is to allow it.

Thus, the src descriptor syntax should be revised to include <url>|<local>, with the latter defined, or else some external reference should provide that.

**Comment by PeterCon** [comment]
Actually, it was just pointed out to me that local() is accommodated by describing <font-face-name> later on in that section, within prose text. That's easily missed (as I missed it).

**Comment by litherum** [comment]
@PeterCon Is there anything remaining to do here?

**Comment by litherum** [comment]
Closing due to lack of comment form @PeterCon. Feel free to reopen if there is something more to do.

**Comment by PeterCon** [comment]
What I think is unclear is that there isn't a rule for <font-face-name> to be found anywhere; it's just described in prose. In parallel, the syntax for the format parameter could have been given as <format> with its internal syntax described in prose, but that would be less clear than what is currently done by specifying format( <string>#).

Also, I note in the prose that font-face-name must always be enclosed by local() --- so there aren't any variants to deal with.

Hence, I wonder it would be clearer if the src value syntax were given as follows (with appropriate changes in the prose):
[<url>[format(<string>#)]? | local(<string>)]#
