### ISSUE TITLE
[css-fonts-5] How to add new generic font families

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6770]
We agreed [on the 27 Oct 2021 call](https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-953127524) to start a new issue about how to add generic font families. Below is my understanding of the current direction, as a way to start discussion.

There are two ways to go with the future evolution of generics:

1. Deprecate a couple, don't add any more, depend totally on downloaded webfonts
2. Realize that, as @r12a demonstrated, [a large number need to be added](https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-619342561), come up with criteria for adding them and a plan, [perhaps a registry](https://github.com/w3c/csswg-drafts/issues/4566) for trying out new ones, and recognize that these represent _important distinctions_ which are necessary for some languages or scripts and may not be useful, or indeed map to an actual font, outside that usage.

It seems we have broad agreement that option 2 is the way to go. 

This implies that new generics will be steadily added over time, which  as @kojiishi [noted](https://github.com/w3c/csswg-drafts/issues/5001) gives us a potential name-clash problem. @frivoal suggested a `generic()` functional notation which would neatly solve that issue. @jfkthame had also [suggested a functional notation](https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-621124855)

We should avoid being over-specific, as @fantasai mentioned, but also avoid being over-general or drawing forced analogies that do not take into account cultural factors (for example saying that `cursive` means brush drawn and also playful or informal, when [it may mean the exact opposite](https://github.com/w3c/csswg-drafts/issues/4606#issue-538247107), like "official and somewhat archaic government pronouncements"). And as @litherum noted, it is easier to discuss specific families rather than being too meta, once we have a general direction agreed upon.

**In Scope**

 Finding the existing generic categories that particular communities need, and for each one document

- the name
- a description of what it signifies and how it is used
- at minimum ,one font which would be appropriate for that generic. More is better.
- the languages or scripts which are the _primary_ audience for this generic.

Retrospectively applying that procedure to existing and already-proposed generics

Deprecating `fantasy`

**Out of Scope**

User-defined generics (how would content authors discover and use them)

Creating the latest and best completely universal type classification system which can accurately and uncontroversially classify any typeface ever created to an astonishing level of detail, which everyone agrees is the right one

(This spun out from  [meta] [css-fonts] Criteria for generic font families #4910 )

**Comment by cdoublev** [comment]
Before the changes fixing this issue, `<generic-family>` was (and is still) defined as a keyword.

  > **`<generic-family>`**: Each `<generic-family>` keyword represents a generic font choice [...]

Now it is not clear:

  > `<generic-family> = generic( <custom-ident>+ ) | <string> | <custom-ident>+`

Is it intentional to allow `<string>` and one *or more* custom identifiers?

I would prefer to have generic font family names inlined in the value definition or abstracted with `<generic-family-name>` (for example) rather than `<custom-ident>`.

**Comment by xfq** [comment]
The title and label are both for L5, but the change was for L4. Should we change the title and label?

**Comment by svgeesus** [comment]
The new `generic()` functional notation is in Fonts 4. I would expect any new generics which use that syntax to be proposed in Fonts 5, as we are trying to stabilize Fonts 4 and get it to CR.
