### ISSUE TITLE
[selectors] `:empty` selector shouldn't match elements with shadow roots

### ISSUE THREAD

**Issue by lukewarlow** [w3c/csswg-drafts#6771]
The [selectors spec](https://drafts.csswg.org/selectors-4/) isn't currently clear about how the [`:empty`](https://drafts.csswg.org/selectors-4/#the-empty-pseudo) selector works with shadow roots.

The current situation is something I would consider unintuitive behaviour where an element with an (open) shadow root that itself has child elements, matches the `:empty` selector.

See https://jsfiddle.net/hyjfkwqx/. I would expect a red square with a smaller blue square in it, but instead the parent div has display: none applied.

Provided it's web compatible it would be great if the spec (and in turn implementations) could be updated so that the contents of shadow roots are taken into account.

**Comment by fantasai** [comment]
I think we close out this issue as no change based on the reasoning in [Oriol's comment](https://github.com/w3c/csswg-drafts/issues/6771#issuecomment-954141013) above. Does anyone think we need to clarify the spec first?

**Comment by andreififiita** [comment]
Is there any solution workaround for this? i have selectors with :empty that match elements with shadow-root (although  those elements are not empty and they shouldnt match)
