### ISSUE TITLE
[css-pseudo] defaulting ‘color’ in :root highlights

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#6774]
**(was: compat risk for ::selection rules defaulting one highlight color from originating element)**

Highlight inheritance marks a pretty big change for the already-widely-shipped ::selection. The current consensus as of #2474 is that the impls should change, and the value of making highlights behave intuitively outweighs the compat risk.

I don’t mean to relitigate this, but I recently found a concrete (albeit in WPT) example of breakage that I didn’t realise was possible. I don’t think this breakage should block highlight inheritance, but I just want to make sure everyone’s aware of it.

Before web-platform-tests/wpt#30813, css/css-pseudo/active-selection-012.html looked roughly like this ([demo](https://bucket.daz.cat/work/igalia/0/22.html)):

```html
<style>
span { background-color: red; color: fuchsia; }
span::selection { background-color: green; }
</style>
<span>fuchsia on green</span>
```

The test expects ::selection to use a foreground color of fuchsia, default inheriting from the originating element, because the presence of background-color:green suppresses UA default highlight colors via paired cascade. Highlight inheritance broke the test: the ::selection foreground becomes initial, because applicable properties are _never_ inherited from the originating element.

This means that highlight inheritance will break any content where ::selection relies on one highlight color (background-color or color) set explicitly, and the other implicitly inherited from the originating element. I [previously](https://github.com/mozilla/standards-positions/issues/548) [believed](https://lists.webkit.org/pipermail/webkit-dev/2021-July/031917.html) we would only break content that somehow relies on descendants being reset to initial highlight styles (and doesn’t use universal rules).

(cc @mrego, @frivoal)

**Comment by delan** [comment]
(summary for meeting)

> Highlights used to only inherit from the originating element, but now they inherit from the parent’s highlight styles, creating separate “inheritance trees” for each highlight.
>
> We previously resolved that the compat risk was acceptable (#2474), because the old behaviour wasn’t really useful or intuitive anyway, but there’s a new breakage that I don’t think we were aware of, and I just want to check if we’re still happy with the risk.

**Comment by delan** [comment]
@emilio
> emilio: I think the only issue is with the color property
> emilio: all current impls store as computed color
> emilio: otherwise need to go figure it out every time resolving a color for a given style
> emilio: I think the spec doesn't reflect that

We’ve started implementing this in Blink, and we think we’ve found a workaround for this problem that doesn’t complicate things for non-highlight styles or slow down style resolution.

[CL:3506351](https://crrev.com/c/3506351) leaves ‘color’ storage and resolved-color-returning functions like GetCurrentColor and VisitedDependentColor untouched, but adds an inherited flag for whether ‘color’ was ‘currentColor’. If the flag is true, the highlight painting code ignores the incorrectly-resolved ‘color’ in ComputedStyle and grabs it from the next layer below (currently originating, but soon this could be a highlight overlay). ‘currentColor’ is stored as itself for ‘background-color’, so for that, we check if the flag is set *and* the background is ‘currentColor’, and ignore accordingly.

gCS is not implemented yet, but we think it can be done similarly or even simpler, because we’re pretending that the given highlight is active for the whole element and all other highlights are inactive (#6818).

@fantasai
> fantasai: I think the test is correct, actually, and paired cascading is also correct
> fantasai: inheriting all the way up, should get currentColor, not black
> fantasai: though I'm not sure the spec is clear about that

@frivoal
> florian: Delan, can you point out to which bit of the spec made you think that you would go to black rather than originating element?
> florian: wondering if it's ambiguous or wrong

I believed that ‘color’ would become ‘CanvasText’ (usually black) because of these spec texts (emphasis mine):

* [#highlight-cascade](https://drafts.csswg.org/css-pseudo-4/#highlight-cascade): “When any supported property is not given a value by the cascade, its value is determined ***by inheritance*** from the corresponding highlight pseudo-element of its originating element’s parent element (regardless of whether that property is an [inherited property](https://drafts.csswg.org/css-cascade-5/#inherited-property)).”
* [css-cascade-4 #defaulting](https://drafts.csswg.org/css-cascade-4/#defaulting): “[Inherited properties](https://drafts.csswg.org/css-cascade-4/#inherited-property) ***draw their defaults*** from ***[the corresponding highlight of]*** their parent element ***through [inheritance](https://drafts.csswg.org/css-cascade-4/#inheritance)*** [by analogy with the text above]; all other properties take their [initial value](https://drafts.csswg.org/css-cascade-4/#initial-value).”
* [css-cascade-4 #inheriting](https://drafts.csswg.org/css-cascade-4/#inheriting): “For ***[highlight pseudo-elements of]*** the root element [by analogy with the text above], which has no parent element, the [inherited value](https://drafts.csswg.org/css-cascade-4/#inherited-value) ***is the [initial value](https://drafts.csswg.org/css-cascade-4/#initial-value)*** of the property.”
    * [css-cascade-4 #inheriting](https://drafts.csswg.org/css-cascade-4/#inheriting) also says “[Pseudo-elements](https://drafts.csswg.org/selectors-4/#pseudo-element) inherit according to the fictional tag sequence described for each pseudo-element.” but highlights have no fictional tag sequence, and I feel like those are non-normative anyway?
* [css-color-4 #the-color-property](https://drafts.csswg.org/css-color-4/#the-color-property): “Initial: ***CanvasText***”

Have I missed something? If we want the specified value of a :root highlight’s ‘color’ to be ‘currentColor’, which I agree is reasonable, we should say so somehow. A few options come to mind:

1. For highlight pseudos, we redefine the initial value of ‘color’, from ‘CanvasText’ to ‘currentColor’. This would make ‘initial’ and ‘inherit’ and ‘unset’ also mean ‘currentColor’ at the root.
2. For highlight pseudos, we redefine the inherited value of ‘color’ at the root, from the initial value to ‘currentColor’. This would make ‘inherit’ and ‘unset’ also mean ‘currentColor’ at the root, though ‘initial’ would still mean ‘CanvasText’, just like how they work in pre-highlight inheritance impls ([demo](https://bucket.daz.cat/work/igalia/0/39.html)).
3. For highlight pseudos, we redefine defaulting for ‘color’ at the root, from using inheritance to ‘currentColor’. Under this option, ‘initial’ and ‘inherit’ and ‘unset’ would still mean ‘CanvasText’ at the root.
4. For highlight pseudos, we say that root highlights inherit all properties from the next highlight below. Under this option, ‘initial’ and ‘inherit’ and ‘unset’ would still mean ‘CanvasText’ at the root.

I don’t see how option 4 could work, because it would need to be the next active highlight below (making resolved styles entirely dependent on active highlights), and it would need to be the leaf node’s styles for that highlight (making the root styles dependent on descendant styles). Other than that, I don’t have a strong opinion on what would work best… maybe @mrego or @andruud can comment?

**Comment by emilio** [comment]
> @emilio
> 
> > emilio: I think the only issue is with the color property
> > emilio: all current impls store as computed color
> > emilio: otherwise need to go figure it out every time resolving a color for a given style
> > emilio: I think the spec doesn't reflect that
> 
> We’ve started implementing this in Blink, and we think we’ve found a workaround for this problem that doesn’t complicate things for non-highlight styles or slow down style resolution.
> 
> [CL:3506351](https://crrev.com/c/3506351) leaves ‘color’ storage and resolved-color-returning functions like GetCurrentColor and VisitedDependentColor untouched, but adds an inherited flag for whether ‘color’ was ‘currentColor’. If the flag is true, the highlight painting code ignores the incorrectly-resolved ‘color’ in ComputedStyle and grabs it from the next layer below (currently originating, but soon this could be a highlight overlay). ‘currentColor’ is stored as itself for ‘background-color’, so for that, we check if the flag is set _and_ the background is ‘currentColor’, and ignore accordingly.

Hmm, is that really enough? I'm not sure it can just be a flag, because currentColor can be interpolated with other colors, can't it? As in, what if I do `color: color-mix(currentColor, ...)` or other such things?

That is a bit unfortunate in general since it's a whack-a-mole and now all of the decoration code needs to be aware of this flag everywhere, right? So it can't really share much code with the rest of the painting code-paths.

**Comment by delan** [comment]
> I'm not sure it can just be a flag, because currentColor can be interpolated with other colors, can't it? As in, what if I do color: color-mix(currentColor, ...) or other such things?

Blink doesn’t support any advanced color features yet, but I think in that case we would still set the flag, indicating that ‘color’ is _dependent_ on currentColor. Once we know what currentColor will be — for now, that means during paint — we call whichever function we normally call to resolve (and possibly mix) color values.

‘text-shadow’ might prove tricky because it’s a list of shadows, each with a color value, but I think either the current approach (flag for the whole property) or moving the flag into Color (for more granularity) could work. The former is probably faster for us right now, because [unlike WebKit](https://github.com/WebKit/WebKit/blob/59325cece209b5aeca74be983fefd8e342a46ad0/Source/WebCore/platform/graphics/Color.h#L51-L54), our Color is still just a [newtype for rgba32](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/graphics/color.h;l=149-152;drc=e0b5aa26864e3541d9cf6362c2f46fb360ed7530).

> That is a bit unfortunate in general since it's a whack-a-mole and now all of the decoration code needs to be aware of this flag everywhere, right? So it can't really share much code with the rest of the painting code-paths.

Not really, in Blink, as most of the paint code lets the caller pass intermediate structs for text colors (TextPaintStyle) and decoration details (TextDecorationInfo, AppliedTextDecoration). The text fragment painter or highlight overlay painter decides what colors to fill those structs with (using helpers like [HighlightPaintingStyle](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/paint/highlight_painting_utils.cc;l=371-420;drc=d1b317d085e3bd288ffbb65d699a9448d74ca5ba)), but from there the logic is the same.

**Comment by emilio** [comment]
> Blink doesn’t support any advanced color features yet, but I think in that case we would still set the flag, indicating that ‘color’ is _dependent_ on currentColor. Once we know what currentColor will be — for now, that means during paint — we call whichever function we normally call to resolve (and possibly mix) color values.

But that means that you need to preserve the unmixed color in the computed style, which is what you want to avoid to begin with right? Anyways I'm not opposed to that but seems a bit tricky off-hand.

**Comment by delan** [comment]
Thanks @emilio! I think we should consider resolving with option 2 from [my earlier comment](https://github.com/w3c/csswg-drafts/issues/6774#issuecomment-1083055006):

> 2\. For highlight pseudos, we redefine the inherited value of ‘color’ at the root, from the initial value to ‘currentColor’. This would make ‘inherit’ and ‘unset’ also mean ‘currentColor’ at the root, though ‘initial’ would still mean ‘CanvasText’, just like how they work in pre-highlight inheritance impls ([demo](https://bucket.daz.cat/work/igalia/0/39.html)).

**Comment by delan** [comment]
@emilio @fantasai re currentColor disappearing at computed value time, [css-color-4 #resolving-other-colors](https://drafts.csswg.org/css-color-4/#resolving-other-colors) says

> The [currentcolor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor) keyword computes to itself.

which is why this rect is green, not red ([demo](https://bucket.daz.cat/work/igalia/0/36.svg))

```svg
<svg viewBox="0 0 300 150" xmlns="http://www.w3.org/2000/svg">
    <g><rect x="10" y="10" width="10" height="10" /></g>
    <style>
        g { color: red; fill: currentColor; }
        rect { color: green; fill: inherit; }
    </style>
</svg>
```

**Comment by emilio** [comment]
@delan yeah, my point is that that doesn't match how browsers work _for the color property in particular_.

I was going to point how even Chrome doesn't think the computed value is `currentColor` for the color property, but its `computedStyleMap()` is broken:

```html
<span style="color: currentColor; background-color: currentColor"></span>
```

```js
document.querySelector("span").computedStyleMap().get("color").toString() // rgb(0, 0, 0)
document.querySelector("span").computedStyleMap().get("background-color").toString() // rgb(0, 0, 0)
```

Per spec, both should be `currentColor`. In Firefox and pretty sure WebKit, the former would be black.

**Comment by emilio** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1338607 for the bug above.

**Comment by delan** [comment]
#6665 makes the edits for this question.
