### ISSUE TITLE
[css-fonts] Clarify: use of referrers in font fetching and relationship with preloads 

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#6775]
Currently it is not specified how fonts are fetched. [This PR](https://github.com/w3c/csswg-drafts/pull/6715) attempts to fix that.

However, currently there is a behavior mismatch around referrers and fonts.
When fetching web-fonts, Gecko & Chromium send the URL of the stylesheet where the font is defined rather than the URL of the document as the referrer for the font (Safari loads web-fonts without CORS).

It's unclear what this was meant for, but it has the effect of not being fully compatible with preloading (`<link rel="preload">`). Because a preload doesn't have a way to specify a referrer, and the embedding HTML does not always know which stylesheet URL will eventually load the font, this may result in incompatibilities between the preloaded request and the actual request.

Also, browsers today have an out-of-spec "memory cache" or "resource cache" for fonts, where the referrer is not a cache key, so implementations are already depending on a behavior that fetching the same font with different referrers would be identical.

I suggest to not send the stylesheet URL as a referrer to avoid this problem, but I'm not sure of the implications.

**Comment by domfarolino** [comment]
Is there a concrete action item for this issue at this point? It seems that:
 1. @noamr's PR is merged
 2. We agree that resources in non-inline CSS sheets should use the CSS sheet's URL as the referrer
    - Safari apparently doesn't do this?
 4. CORS here shouldn't impact whether the `Referer` is sent (I believe)

The compat risk raised in the OP was (correct me if I'm wrong) that a font preload's referrer will be the Document's URL, while the font's _actual fetch_'s referrer will be a style sheet URL, yet reuse the different-referrer preload response. I guess this only matters when servers send `Vary: Referer`, which I don't think influences the preload cache. But per https://github.com/w3c/csswg-drafts/issues/6775#issuecomment-954517516 it sounds like this is documented now.

Can we just file a bug against Safari for (2) above and close this, or is there something specific that can still emerge from this?
