### ISSUE TITLE
[css-values?] Accept <number> where <integer> is expected

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6786]
Currently there are a lot of places where authors end up having a `<number>` instead of an `<integer>` without realizing, then are puzzled why their code doesn't work.

For example:

```css
--columns: 12;
grid-column-end: span calc(var(--columns) - 8); /* works */
grid-column-end: span calc(var(--columns) / 3); /* fails, IACVT */
```

Same issues with `counter-reset`, `z-index` and the list goes on. 

In fact, clever authors have even come up with [_terrible hacks_](https://twitter.com/anatudor/status/1399849494628425734) for working around this by assigning the number to a registered `<integer>` property and taking advantage of that implicit conversion. Sure, once `floor()` and friends are supported this would be much simpler, but IMO authors should not even have to think about this. A `5` is a `5`, whether it was generated as `4 + 1` or as `15 / 3`. Since `<number>` cannot be disambiguated from `<integer>`, I doubt we have any syntax that depends on them being incompatible. 

**Proposal:** accept `<number>` anywhere an `<integer>` is accepted, after flooring (or rounding, no strong opinion).

**Comment by Loirooriol** [comment]
The spec already says

https://github.com/w3c/csswg-drafts/blob/9a5895f2f47c87e206e5ac05cfa44f5f3319d0cb/css-values-4/Overview.bs#L4160-L4162

**Comment by emilio** [comment]
Yeah, this already works per spec. Firefox implements it correctly afaict, not sure about other browsers, but we have tests for this.

**Comment by LeaVerou** [comment]
> Yeah, this already works per spec. Firefox implements it correctly afaict, not sure about other browsers, but we have tests for this.

Ah, thanks, must be a Chrome bug then. By "we" you meant csswg tests or Gecko tests?

**Comment by Loirooriol** [comment]
Chromium was recently fixed in https://crbug.com/931216
There are tests in WPT, like https://wpt.fyi/results/css/css-values/calc-rounds-to-integer.html
