### ISSUE TITLE
[css-fonts-4] Naming font-technology() supports function

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6791]
In https://www.w3.org/2021/10/20-css-minutes.html#r04 we resolved to add, roughly speaking, a technology() function to the `src` descriptor and an equivalent font-technology() function to `@supports` which would take keywords representing font technology capabilities to check for UA support. We also resolved to open a bikeshedding issue to see if there's a better name for the function, so this is that issue.

**Comment by svgeesus** [comment]
> we resolved to add, roughly speaking, a technology() function to the src descriptor

Defined in CSS Fonts 4: [11.1. Font technologies](https://drafts.csswg.org/css-fonts-4/#font-technology-definitions) and used in CSS Fonts 4: [4.3.1. Parsing the src descriptor](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing)

>and an equivalent font-technology() function to `@supports`

Defined in CSS Conditional 4: [2. Extensions to the @supports rule](https://drafts.csswg.org/css-conditional-4/#at-supports-ext) which links to the definitions in CSS Fonts 4

> We also resolved to open a bikeshedding issue to see if there's a better name for the function

For the record, I think those names are _just fine_. In the context of `src` in `@font-face` there is no need for the `font-` prefix while in the general `@supports` there is; that difference aside, they should be exactly the same, which they currently are. `tech` is tempting, and I could live with it, but `technology` is probably better.

**Comment by drott** [comment]
Names are fine with me, too. Opinions, @jfkthame, @litherum ?

**Comment by LeaVerou** [comment]
FWIW I agree that the name needs bikeshedding, but I do not have any suggestions currently. 
Maybe `font-tech()`? We do tend to avoid abbreviations, but maybe tech = technology is sufficiently established that it's ok? Still a bit too colloquial though.

**Comment by fantasai** [comment]
My suggestion would be `font-ability()`. Formats are also technology. (Everything we do here is technology.) I'm also OK with `font-tech()`, and I agree with @LeaVerou that `font-technology()` is too long.

**Comment by litherum** [comment]
I think `ability` is worse than `technology`, because `COLR` and `SVG` have the same _ability_ but are different _technologies_. Same with shaping - `morx` and `GSUB` are the same _ability_ but are different _technologies_.

**Comment by jfkthame** [comment]
Agree with Myles, I don't favor `ability`; I think `tech[nology]` is a more natural term here.

Personally, I don't think the length of the full `font-technology` form is a problem; clarity is good, and I'm not expecting authors to be typing large numbers of `@supports font-technology(....)` blocks by hand (and if they do need to, copy/paste and autocomplete are a thing....)

**Comment by LeaVerou** [comment]
I think of "ability" as referring to something a being can do and not a property of a group of bytes. Like, a font is not "able" to do anything, it's the tools that read it that are, and this function queries browser support, not font "support", i.e. you can specify `techology(COLRv1)` on a non-color font. It's nonsensical, but not forbidden.

**Comment by drott** [comment]
I am still okay with `font-technology` and `font-tech`, but if it needs to be something shorter, `font-trait`, `font-kind`?

**Comment by litherum** [comment]
"trait" is already a term-of-art and means something else.

**Comment by svgeesus** [comment]
No seeing any proposed names that are better than the current ones. Close?

**Comment by drott** [comment]
Happy to close, I am fine with the current ones.

**Comment by svgeesus** [comment]
Agenda+ to close with no change. No better proposals were made.

**Comment by yisibl** [comment]
Non-native English users, `font-tech()` +1
