### ISSUE TITLE
[mediaqueries][css-conditional] Allow empty functions in <general-enclosed>

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6803]
@andruud wrote in https://github.com/w3c/csswg-drafts/pull/6312#issuecomment-856699290
> The reason Chromium appears to evaluate `not fn()` to false in the [demo](url) is because `not fn()` is actually invalid grammar. (`<any-value>`, requires **one or more** tokens).

Since this is about forwards-compatible parsing and evaluation, it seems to me it would make more sense if `<any-value>` were optional so that empty functional notations would be syntactically valid.

**Comment by andruud** [comment]
Coincidentally, we actually made a ninja-edit for this last week. https://github.com/w3c/csswg-drafts/pull/6799

**Comment by tabatkins** [comment]
Yeah, the grammar was an accidental leftover from when `<any-value>` was *implicitly* optional (but this caused more confusion than it solved). It was always intended that empty functions should be allowed, and the edits are in now to reflect that.

**Comment by fantasai** [comment]
Reopening to get WG approval on this, since it's updating a CR. Should be routine.
