### ISSUE TITLE
[cssom-view] "evaluate media queries and report changes" doesn't specify that MediaQueryListEvent should be used

### ISSUE THREAD

**Issue by jdm** [w3c/csswg-drafts#681]
https://drafts.csswg.org/cssom-view/#evaluate-media-queries-and-report-changes says "dispatch a new event to target using the MediaQueryList interface", which both doesn't mention MediaQueryListEvent and contains the meaningless phrase "using the MediaQueryList interface".

**Comment by zcorpan** [comment]
Thanks, there were two wrongs here. Please review my fix!

**Comment by jdm** [comment]
Looks good!
