### ISSUE TITLE
[fill-stroke] Clarify property definitions applying to "inline boxes"

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#6823]
Several of the properties of CSS Fill and Stroke 3 apply to "inline boxes". Though there's no definition for that in the spec. nor a referene to the [definition in the Display spec.](https://drafts.csswg.org/css-display-3/#inline-box), which I assume is the one that's meant.

Besides that, I wonder whether it's actually correct that they apply to inline boxes. According to their definition, they should rather apply to the text itself or simply to "all elements". E.g. it seems a bit arbitrary that [`fill-origin` applies to all elements](https://drafts.fxtf.org/fill-stroke/#fill-origin) while [`fill-image` only applies to inline boxes and SVG shapes](https://drafts.fxtf.org/fill-stroke/#fill-image). (The latter even claims that its values work the same as for `background-image`, which applies to all elements.

Sebastian

**Comment by Loirooriol** [comment]
See #5303:

> RES0LVED: inheritable properties that apply to inlines also apply to text

So all these "Applies to: inline boxes" should be "Applies to: text"

**Comment by SebastianZ** [comment]
@Loirooriol Thank you for the hint!

I just realized [I already opened an issue for that](https://github.com/w3c/fxtf-drafts/issues/416) earlier this year in the fxtf repository. I closed the other one now.

Sebastian
