### ISSUE TITLE
[css-text-decor] text-underline-offset auto value explanations lacks explicit reference to text-underline-position

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6828]
https://drafts.csswg.org/css-text-decor-4/#underline-offset says:

> **auto**
The UA chooses an appropriate offset for underlines.

> However, this offset must be zero if [from-font](https://drafts.csswg.org/css-text-decor-4/#valdef-text-underline-position-from-font) was specified and the UA was able to extract an appropriate metric to use from the font.

And while 'from-font' here links to text-underline-position, the text does not say it. 

I suggest for the spec to say:

> However, this offset must be zero if [from-font](https://drafts.csswg.org/css-text-decor-4/#valdef-text-underline-position-from-font) was specified for text-underline-position and the UA was able to extract an appropriate metric to use from the font for that.

CC @svgeesus

**Comment by frivoal** [comment]
Thanks. Clarified in https://github.com/w3c/csswg-drafts/commit/66038354d8ea08a8df9c067e04d1c325015038fd
