### ISSUE TITLE
[css3-animations] [css-transitions] animation-delay animatable?

### ISSUE THREAD

**Issue by nyarly** [w3c/csswg-drafts#683]
As a web developer or designer, I'd like to be able to "scrub" animations using transitions. However

1. None of the animation properties are themselves animatable and
1. This is sensible because either 
    1. that would admit to animating an animation property, which makes my head swim, or     
    1. admitting the unique case of a property which is transitionable without being animatable.

But:
The motivating instance is like this:

Suppose you have an animation that discloses an element - scales it vertically, as well as changing it's opacity and color.

You'd like for there to be a style selected with `:hover` on a parent to start that animation.

When the style no longer applies, the animation should reverse in order to hide the element again.

My understanding an experimentation with the current spec is that I could: 

* apply the animation in the :hover style. I get the disclosure animation, but the element simply vanishes when :hover is removed.
* apply in the :hover, and also apply the animation in reverse to a style without :hover. This does what I want, but when the page loads, the element initially is visible and then disappears.

## Proposal

The very generic solution that occurs to me would be: apply the animation to the element, paused. Add `transition-property: animation-delay` and have the :hover class apply `animation-delay: -1 second` with the intention that, when `:hover` is added to the container element, the animation delay would transition, and so the animation would "scrub" forward 1 second. When :hover is removed, the reverse transition would apply, and the "scrub" would rewind the animation back to the hidden state.

## Alternatives

It would also suit my purposes if there were a psuedo-selector for `:lost-hover` or `:hovered.` Then, that selector could be used to apply the reverse animation, and so avoid the page-load vanish behavior.

In some ways, that would be better, since a separate animation might be applied to reverse the action - however, note the complication of needing to share a timeline, as well as somehow tweening between the two animations if `:hover` is removed before the first animation completes. (There's a notion of an algorithm there, but it's still an added complication.) Furthermore, for generality, the implication is for a lost() modifier, which I think complicates the whole thing.

In fact, the "shared timeline" concept was one of the initial drivers for wanting to be able to use transitions to scrub animations, and therefore making animation-delay animatable.

**Comment by birtles** [comment]
Why can't you use transitions for your effect? Transitions give you auto-reversing behavior.

Something like this: http://codepen.io/birtles/pen/aBvPZQ ?

**Comment by nyarly** [comment]
In the motivating case, I did wind up using transitions to do a reduced version of the envisioned effect. With respect, the question might be applied generally to the CSS animations spec: why not do everything with just transitions?

In the motivating case, we wanted to apply some subtle timing effects, and control changes in colors as the menus were disclosed - in other words, we wanted to do things that animations permit but that transitions don't.

But, animations don't allow for the auto-reversing behavior, and giving the requirements, we settled on a less interesting behavior in order to get the reversal. We might've gone on to use Javascript to control the animation instead, but that would've been more complicated and at the time we decided it wasn't worth the effort.

**Comment by birtles** [comment]
There are a lot of times where CSS animations are more appropriate, e.g. an infinitely rotating spinner. Or, an animated cartoon--it doesn't make sense to set the endpoint of each change in the cartoon just to trigger the change, furthermore you might have many different kinds of changes (e.g. the character moves right, then 2s later, moves right again, then later up, then later left -- I can't think of a way to do that declaratively with transitions and even if you could, semantically it would be odd).

Transitions make sense when, in the absence of animation, you'd still want to update the style to its final value anyway. The fact that you can't do A->B->C style transitions is a limitation of transitions we should fix in future. The other subtle timing effects you refer to I presume refer to mid-animation changes? As demonstrated in the codepen, if you're just doing A->B style transitions, you can have different properties transition at different times (and can apply different timing functions to them too).

An auto-reversing feature for CSS animations might make sense too, but I don't think we want to do that by transitioning the animation-delay.

**Comment by nyarly** [comment]
A->B->C is precisely the kind of thing that is a limitation of transitions I was looking to overcome.

Auto-reversal for animations would make sense, but the trick is having them work smoothly as selector conditions change (e.g. :hover or class application etc.) That's effectively the transition behavior, which is what motivated, specifically, the proposal to transition animation-delay.

To be clear: any proposal that allowed for transition-style apply&reverse with animations would be completely satisfactory.

Musing for a moment: wouldn't that mean that transitions could be completely described as animations, and transition properties as they exist now could be described, effectively, as defining a "transition animation" for the element?

**Comment by birtles** [comment]
So I think we need to file two separate issues:

1. css-transitions-2: support A->B->C transitions (i.e. transitioning with midpoint(s) specified)
2. css-animations-2: support reversing (something we might need to consider for scroll effects anyway)

I'm not sure how either will look yet but, yes, ultimately transitions and animations are just variations on a theme. In the Web Animations API, CSSAnimation and CSSTransition both just inherit from Animation and, apart from that, are almost identical. How they are generated is where the difference lies.

**Comment by birtles** [comment]
Filed #2862 and #2863 for this. Please file separate issues for anything not covered by these.

**Comment by nyarly** [comment]
I still think about this issue from time to time. I don't have use cases where either midpoint transitions or reversing animations wouldn't cover the need.

In general though, if transitions and animations are internally the same thing, it seems like their difference is a historical accident that complicates life for browser developers and source authors. Wouldn't a more general solution be a step towards unifying the two approaches? At least, if one approach were a complete superset of the functionality of the other, it would make things easier.

Separately, I'm confused and dismayed that there's not more discussion on these issues. I'm not sure what conclusion to draw from that.
