### ISSUE TITLE
[css-color-5] color-mix() is still referring to <hue-adjuster> which no longer is defined

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6830]
In a few places in the `color-mix()` definition - https://drafts.csswg.org/css-color-5/#color-mix - the spec refers to the no longer defined `<hue-adjuster>` production, usually with a link to https://www.w3.org/TR/css-color-5/#typedef-hue-adjuster.

I believe it should instead be using `<hue-interpolation-method>` defined at https://drafts.csswg.org/css-color/#typedef-hue-interpolation-method.

**Comment by svgeesus** [comment]
It should, indeed.
