### ISSUE TITLE
[css-color-5] color-mix() could benefit from additional examples to understand the behavior of mixing with non-default hue interpolation methods

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6832]
I would have (and I guess still would) found it helpful when implementing `color-mix()` if the spec, https://drafts.csswg.org/css-color-5/#color-mix, included examples of mixing with a non-default hue interpolation method (such as 'longer'). This would help to better understand how they fit in the grammar, how they work and why they might be useful.

**Comment by svgeesus** [comment]
Duplicate with #6833
