### ISSUE TITLE
[css-color-5] color-mix() could benefit from additional examples to understand the behavior of mixing colors with alpha

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6833]
I would have (and I guess still would) found it helpful when implementing color-mix() if the spec, https://drafts.csswg.org/css-color-5/#color-mix, included examples of mixing colors with non-opaque alpha. This would help to clarify things like alpha premultiplication behavior and how that interacts with the additional alpha multiplication that happens when the sum of the percentages does not add up to 100.

**Comment by svgeesus** [comment]
I added a basic, `in srgb` alpha mix example. Will add more.

**Comment by svgeesus** [comment]
I added a second example with an alpha multiplier, and a note not to combine the interpolated alpha with the alpha multiplier before undoing premultiplication.

**Comment by svgeesus** [comment]
@weinig does that address your concern or would you like more examples?

**Comment by weinig** [comment]
This looks great. Thanks. 

(You do have a typo though, "When the percentage **ormalization gnerates** an alpha multiplier").
