### ISSUE TITLE
[css-color-4] Serialization needs to be updated for newly added xyz-d50, xyz-d65, oklab() and oklch() color spaces

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6834]
The serialization section of the CSS Color Module 4 spec, https://drafts.csswg.org/css-color/#serializing-color-values, needs to be update for the newly added predefined color spaces and color functions: `xyz-d50`, `xyz-d65`, `oklab()` and `oklch()`.

At the moment, I am assuming `oklab()` and `oklch()` serialize like `lab()` and `lch()` as specified in https://drafts.csswg.org/css-color/#serializing-lab-lch, but it should probably be made explicit.

For `xyz-d50`, `xyz-d65`, I am assuming that they serialize like `color(xyz ...)` and also have a 16 bit minimum, but again, making it explicit would be good.

One change from the current spec I would like to propose is changing the serialization of `color(xyz ...)` to `color(xyz-d65 ...)` so that we don't have track that this is an alias in the engine past parsing, allow us to canonicalize xyz to xyz-d65 as early as possible.

**Comment by svgeesus** [comment]
Thanks for noticing these areas where not all the consequences of "Resolve to add foo" got reflected in the spec!

> At the moment, I am assuming `oklab()` and `oklch()` serialize like `lab()` and `lch()` as specified in https://drafts.csswg.org/css-color/#serializing-lab-lch, but it should probably be made explicit.

> For `xyz-d50`, `xyz-d65`, I am assuming that they serialize like `color(xyz ...)` and also have a 16 bit minimum, but again, making it explicit would be good.

Yes. I just forgot to do those when I was adding in `oklab` and `oklch`.

> One change from the current spec I would like to propose is changing the serialization of `color(xyz ...)` to `color(xyz-d65 ...)` so that we don't have track that this is an alias in the engine past parsing, allow us to canonicalize xyz to xyz-d65 as early as possible.

That seems reasonable to me. Any counter-opinions?

**Comment by svgeesus** [comment]
Not hearing any counter-proposal, I plan to make the edit to serialize `color(xyz...)` as `color(xyz-d65...)` soon. Shout if you think this is a bad idea @tabatkins @LeaVerou @argyleink @una

**Comment by svgeesus** [comment]
Updated the section on **Resolving values of the color() function** so that the computed value of `color(xyz ...)` to `color(xyz-d65 ...)` which then affects the serialized form.
