### ISSUE TITLE
[css-color-4] Color resolution needs to be updated for oklab() and oklch() color spaces

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6835]
The CSS Color Module 4 spec currently has a section on color resolution for `lab()` and `lch()` colors, https://drafts.csswg.org/css-color/#resolving-lab-lch-values, but it omits anything about `oklab()` and `oklch()`. The section should probably be updated to apply to both sets.

**Comment by svgeesus** [comment]
Thanks for noticing, fixed!
