### ISSUE TITLE
[css-color-4] Consider adding support for interpolation in the srgb-linear color space

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6836]
Now that CSS Color Module 4 has support for linear sRGB, https://drafts.csswg.org/css-color/#predefined-sRGB-linear, I think it would be useful to extend the set of color spaces that can be used for interpolation to include it, https://drafts.csswg.org/css-color/#typedef-rectangular-color-space.

The main use case I can think of is consistent behavior with other parts of the stack (such as WebGL/WebGPU) that might be using linear sRGB.

**Comment by svgeesus** [comment]
This makes sense. The results should be identical to interpolating in `xyz-d65` but indeed, `srgb-linear` was primarily added for consistency with other parts of the open web platform so it makes sense to allow it here too.
