### ISSUE TITLE
[css-cascade] Cross-reference CSS Style Attributes spec

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#6838]
In https://drafts.csswg.org/css-cascade/#cascade-order

> Declarations from **style attributes** are ordered according to the document order of the element the **style attribute** appears on, and are all placed after any style sheets.

This sentence ought to reference https://drafts.csswg.org/css-style-attr/#style-attribute which is the definition of the term "style attribute".

**Comment by cvrebert** [comment]
@tabatkins Doesn't seem to be rendering properly? There's now a literal, unhyperlinked `[!CSSSTYLEATTR]` in https://drafts.csswg.org/css-cascade/#cascade-order

**Comment by tabatkins** [comment]
ah, i spelled the link wrong. Fixed now, thanks.
