### ISSUE TITLE
[css-cascade][css-cascade-5] "source order" undefined

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#6839]
In https://drafts.csswg.org/css-cascade-5/#layering

> [...] or relying on **source-order** to resolve conflicts across layers.
>
> [...], and come first in the **source order**.

A. Please make the (non-)hyphenation of the term consistent.

B. The term "source order" is jargon, but this spec doesn't explain its meaning, nor link to some definition elsewhere. Considering that [other specs also use the term](https://github.com/w3c/csswg-drafts/search?p=1&q=%22source+order%22), but none of them seem to currently contain a definition, it would be good to add a formal definition in a spec. Then all the specs can point at that definition.

**Comment by ByteEater-pl** [comment]
There's [document order](https://www.w3.org/TR/DOM-Level-3-Core/glossary.html) which a number of specs beside DOM use.

**Comment by cvrebert** [comment]
Presumably the modern equivalent of *document order* would be [tree order](https://dom.spec.whatwg.org/#concept-tree-order). But both of those concepts are defined only in terms of nodes. However, AIUI source order also accounts for which declaration comes first within a CSS source code string; and that string could be a single Text node that's the sole child of a `<style>` node, or the content at a URL referenced by a `<link>` tag. So *document order* alone would be insufficient.

**Comment by ByteEater-pl** [comment]
Well, that's where WHATWG went with it (though I don't see a technical reason for changing the established term, however they just seem to get off on spurious deviations), while W3C specs (like e.g. XQuery) use (and sometimes extend as needed) document order.

But you're right, it's for whole nodes. What's needed here are [boundary-points](https://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level-2-Range-Position) and [Comparing Range Boundary-Points](https://www.w3.org/TR/DOM-Level-2-Traversal-Range/ranges.html#Level-2-Range-Comparing) restricted to collapsed Ranges.

**Comment by cvrebert** [comment]
Looking again, another option would be to use [Order of Appearance](https://drafts.csswg.org/css-cascade-5/#cascade-order) instead of "source order". *Order of appearance* 's own definition could perhaps merit improvement, but strictly speaking that'd be a separate issue.

**Comment by mirisuzanne** [comment]
Updated in 5f23b7d
