### ISSUE TITLE
[css-syntax] The url special case in ident-like token parsing could be clearer

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#685]
https://drafts.csswg.org/css-syntax/#consume-ident-like-token says:

> then create a <function-token> with its value set to the returned string and return it

I think this would be clearer as:

> then create a <function-token> with its value set to "url" and return it

but if we want to preserve case, at least a note pointing out that this is talking about the string that matched "url" as opposed to the string that the quotation mark or apostrophe starts would be very helpful.

**Comment by tabatkins** [comment]
I used an explicit variable to make this clear. I also went ahead and fixed the preceding section which has the same structure.
