### ISSUE TITLE
[cssom-view] Proposal: add Element.isVisible[toDocument] to detect if element is visible in the document.

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#6850]
I filed a proposal on https://github.com/whatwg/html/issues/7379 but cross-posting it here, since [cssom-view](https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface) is likely a good place for speccing it if it is a good idea.

The issue above has a full description of the proposal, but the summary is that I would like to propose adding `Element.isRendered()` function to detect whether an element is rendered. Specifically, if it is `display: none` or in such a subtree, or in a subtree of a `content-visibility: hidden` element, then `isRendered()` on that element would return false. Otherwise it would return true

(please see the other issue for discussions of whether things like images that haven't loaded be unrendered as well).

**Comment by emilio** [comment]
Sounds reasonable though it'd be extremely weird that isRendered would return anything that doesn't match https://html.spec.whatwg.org/#being-rendered

**Comment by Loirooriol** [comment]
What about `display: contents`? Related: https://github.com/whatwg/html/issues/1837

**Comment by vmpstr** [comment]
I think having it match https://html.spec.whatwg.org/#being-rendered is reasonable. I'm going to see if we can amend "being rendered" somehow to include `content-visibility` stuff <_<

**Comment by vmpstr** [comment]
After some more discussion here, would you support `isRendered` being something like "returns true if the element is [rendered](https://html.spec.whatwg.org/#being-rendered) and not [skipped](https://www.w3.org/TR/css-contain-2/#skips-its-contents)"

The problem is that we would really like this function to return false for `content-visibility: hidden` subtrees. But it's challenging to amend the being-rendered spec to say that elements in `content-visibility: hidden` subtrees are not rendered, since it's not entirely true. They _may_ not be rendered, but the rendering will be updated for any kind of queries that require the rendering to be updated. 

Would it help if the name is not `isRendered` but something else (although exactly what I don't know)

**Comment by Kaiido** [comment]
I may be bikeshedding here, but I have the feeling that this method should be called something else.  
I fear that by calling this `Element.isRendered` authors will think it's just a getter with no side-effects. However no matter how it's optimized behind the scene, it will at least force a synchronous reflow like any of [these](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).  
So if one were to e.g change the DOM while looping over a list of elements themselves nested deep in a complex tree doing

```js
for (const elem of list) {
  if (elem.isRendered()) {
    elem.before(newElement());
  }
}
```
the styles would get recalculated for the whole page at every iteration of the loop with sensible performance costs.  

I am really not good at naming, but maybe something like `getRenderingStatus()` would make it more obvious that something will happen when calling it, and *maybe* it could also return different values like "not-rendered", "skipped", "rendered" if the distinction is useful?

**Comment by chrishtr** [comment]
I propose we change to `Element.isVisible`, meaning conceptually "visible to the document" (*not* "visible to the user" - `IntersectionObserver` would be needed for that).

Definition:

* Is [rendered](https://html.spec.whatwg.org/#being-rendered)
* Has a used style of `visibility` of `visible`
* Does not [skip its contents](https://drafts.csswg.org/css-contain-2/#skips-its-contents)

I think this is better, because it is (a) clearly defined in terms of the spec, and (b) solves various use cases we've encountered well. Use cases include:
 * Detect whether content is skipped (in order to avoid forcing layout, such as wicg/display-locking#112)
 * Know when an element is visible (e.g. via puppeteer or similar frameworks)

**Comment by josepharhar** [comment]
> Know when an element is visible (e.g. via puppeteer or similar frameworks (also see here))

Here is some [puppeteer code](https://github.com/puppeteer/puppeteer/blob/bbfad6802c1eb8b5b43e568334ba4212698da917/src/common/helper.ts#L271-L281) and some [playwright code](https://github.com/microsoft/playwright/blob/04aa38a6639452df1a34cd7c186ecc2a0f706c40/packages/playwright-core/src/server/injected/selectorEvaluator.ts#L656-L665) that could use this feature to work properly with content-visibility, as well as a [playwright issue](https://github.com/microsoft/playwright/issues/10674) where someone ran into this shortcoming due to [content-visibility in `<details>`](https://github.com/whatwg/html/pull/6466).

**Comment by emilio** [comment]
> I propose we change to `Element.isVisible`, meaning conceptually "visible to the document" (_not_ "visible to the user" - `IntersectionObserver` would be needed for that).

I'm a bit concerned about people expecting the later rather than the former... Though I can't come up with a particularly better name right away...

Another possible concern is that the API would have to update style synchronously, which might defeat the optimizations it's trying to introduce...

**Comment by SebastianZ** [comment]
> I'm a bit concerned about people expecting the later rather than the former... Though I can't come up with a particularly better name right away...

Me too. It could be simply `isVisibleToDocument` if that isn't too long. Alternatively, maybe `isAvailable`?

Sebastian

**Comment by chrishtr** [comment]
Re name: I agree `isVisible` is not a perfect name. `isVisibleToDocument` is descriptive of what it is, that sounds good to me.

Re sync style: this is definitely something to make sure we get right. The is-rendered and `visibility:visible` parts will require sync style recalc, but only if the element is not skipped (i.e not in a skipped `content-visibility` subtree). If the element is skipped, then we can detect that with a sync style update up to ancestors that skip their contents, and then observe that the element is in the subtree with a tree walk. (And if style were already up-to-date, then of course the above computations would potentially be free or mostly free.)

Worst-case performance summary:
* Forces style for non-skipped parts of the document
* Requires an ancestor tree walk for skipped elements up to a non-skipped ancestor

(p.s. I updated the third bullet point of my proposal a few comments back to be accurate about skipped elements)

**Comment by vmpstr** [comment]
> Worst-case performance summary:
> 
> * Forces style for non-skipped parts of the document
> * Requires an ancestor tree walk for skipped elements up to a non-skipped ancestor

I agree. Also note that even if we tie this function only to [being rendered](https://html.spec.whatwg.org/#being-rendered), the style update (of non-skipped parts) would still be required. I think the extra ancestor walk is a small price to pay to let developers reliably check and avoid computation in non-document-visible trees.

Bikeshed: maybe isDocumentVisible instead of isVisibleToDocument?

**Comment by smfr** [comment]
`isVisibleToDocument` is an odd term (why is the document looking at elements?) that might make sense for implementors, but as an author I wouldn't understand it.

If this is about whether `getBoundingClientRect()` will trigger more work, why not use a name that communicate that more clearly?

**Comment by chrishtr** [comment]
> `isVisibleToDocument` is an odd term (why is the document looking at elements?) that might make sense for implementors, but as an author I wouldn't understand it.

How about `isVisibleInDocument` ?

> If this is about whether `getBoundingClientRect()` will trigger more work, why not use a name that communicate that more clearly?

There are two known use cases:

1. Detect if the element is actually visible, e.g. for testing in puppeteer/playwright or similar. Joey linked to examples above.
2. Avoid forcing rendering in a skipped `content-visibility`. e.g. sites would wrap potentially expensive code such as `getBoundingClientRect` in an `isVisibleInDocument`.

**Comment by chrishtr** [comment]
Prior art:

* [jQuery :visible](https://api.jquery.com/visible-selector/#visible1). (Note: meaning: "has a box and width or height greater than zero". CSS `visibility` or `opacity`, as well as clipping, are ignored.)

Types of visibility:

1. Has a box ("is rendered" according to HTML spec terminology)
2. Is not skipped by `content-visibility` ancestors
3. Non-zero `opacity`
4. Full `opacity` (`opacity:1`)
5. `visibility:visible`
6. Not clipped out by a clip or filter
7. Occluded by some other element
8. Not scrolled out of the viewport

Proposal:

Pass an options dictionary to a new `isVisible` API, which returns a dictionary of results. By default, use cases 1 and 2 will be queried. Others would be opt-in via the options dictionary.

The justification for including use cases 1 and 2 by default is that there is no other way to do it at present, and these are the minimum requirements to be even possibly visible. The jQuery API also does this (plus a bit more).

```
// Element.isVisible(opts) -> resultDict

my_element.isVisible({}) -> {hasBox: true/false, isSkipped: true/false}

// possible additions:
my_element.isVisible({trackOpacity: true} -> {hasBox: true/false, isSkipped: true/false, isFullyOpaque: true/false, hasNonZeroOpacity: true/false}
my_element.isVisible{trackVisibilityCSS: true}-> {hasBox: true/false, isSkipped: true/false, visibilityVisible: true/false}
my_element.isVisible({trackViewport: true} -> {hasBox: true/false, isSkipped: true/false, isInViewport: true/false}
my_element.isVisible({trackOcclusion: true} -> {hasBox: true/false, isSkipped: true/false, isOccluded: true/false}
```

`trackOcclusion` would use the [same algorithm as IOv2](https://w3c.github.io/IntersectionObserver/v2/#visibility).This handles use case 4+6+7 together.

IMO we should not add `trackOcclusion`, `trackVisibility`, or `trackViewport` or `trackOpacity` unless there is strong demand. Most/all of the use cases can already be solved with `IntersectionObsever` or checking computed styles, which in the case of `IntersectionObserver` are more performant.

But this design allows them to be added in the future.

**Comment by chrishtr** [comment]
@LeaVerou check out my proposal above. Seems reasonable?

**Comment by chrishtr** [comment]
Here's some accessibility prior art, via @aleventhal.

Chromium [already implements an IsVisible](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/accessibility/ax_object.cc;l=2688?q=ax_object.cc&ss=chromium) value on accessibility objects internally, and exposes it to AT tools directly.

The implementation is equivalent to the pseudocode below. The difference between this and my proposal above is that it checks for aria-hidden and inert.

```
isVisible() { 
  return !isHiddenViaStyle() && !IsAriaHidden() && !IsInert();
}

isHiddenViaStyle() { 
  return isDisplayNone() || isVisibilityHidden() || isContentVisibilityHidden() // *not* content-visibility: auto
}

isVisibilityHidden() {
 return computedStyleOfElementIsVisibiltyHidden()
}

isAriaHidden() {
  return selfOrAncestorHasAriaHidden()
}

isInert() {
  return selfOrAncestorIsInert()
}
```

**Comment by chrishtr** [comment]
I think inert and aria-hidden should also be optional attributes.

```
my_element.isVisible({trackInert: true} -> {hasBox: true/false, isSkipped: true/false, isInert: true/false}
my_element.isVisible({trackAriaHidden: true} -> {hasBox: true/false, isSkipped: true/false, isAriaHidden: true/false}
```

**Comment by dlibby-** [comment]
From a conversation with the Narrator/UIA folks at Microsoft, their perspective is that content that is not visible to a sighted user should not be included in the accessibility tree. This determination is performed by the user agent (and specifically in Chromium by the pseudocode Chris referenced above). Therefore, they don't see the need for any such API at the platform accessibility API level.

However, one part of the proposal that I think I'm missing - what would `isVisible()` return for an element in a `content-visibility: auto` subtree where contents are skipped? Per https://github.com/w3c/csswg-drafts/issues/5857, these elements are included in the accessibility tree (with the caveat that this may expose more than the user will see once the contents are activated). If that is the case, then perhaps an isVisible-like API for ATs could be useful - but given the principles around the decision to include that content, I don't know that we'd want to advise ATs to try and handle it separately than their existing logic.

**Comment by aleventhal** [comment]
I don't think the Narrator/UIA statement is detailed enough.
What about content that's scrolled off? That's not visible to a sighted
user, so shouldn't be included?
What about content that's behind other content in the z-order? Same Q.
What about content that's positioned offscreen (often done intentionally as
a technique to provide additional instructions to screen reader users).

IMO, what browsers do now is useful and works well with screen reader
expectations today. Not sure if there's a need to revisit any of this right
now TBH.
Regarding content-visibility: auto, it needs to be exposed so that screen
reader users can navigate by heading, etc. Unless someone sees a way around
that.

Aaron

**Comment by chrishtr** [comment]
> However, one part of the proposal that I think I'm missing - what would `isVisible()` return for an element in a `content-visibility: auto` subtree where contents are skipped?

Good question. I think skipped descendants of a content-visibility: auto element should return true for isVisible, since if the user scrolled to them, they are indeed visible. And it also aligns with the accessibility code I inlined above, which is a good sign.

**Comment by chrishtr** [comment]
Agenda+ to request resolution for adding isVisible with the default behavior of:

1. Has a box ("is rendered" according to HTML spec terminology)
2. Is not skipped by content-visibility:hidden ancestors

And take a dictionary of optional add-ins for extensibility to more use cases.

**Comment by chrishtr** [comment]
Regarding the return value of this function: I think I was overthinking it. It seems sufficient to just return a boolean. New proposal:

```
isVisible({dictionary}): bool
```

If you pass nothing in the dictionary it returns true if it has a box and is not skipped by `content-visibility:hidden` ancestors.

If you pass one or more things in the dictionary, it *ands* the return value with those visibility checks. I don't think it makes sense to to check more fine-grained things. If a developer for some obscure reason really wants to distinguish, they can call it multiple times with dictionary arguments.

Unless there are objections I'll add this to CSSOM based on the existing resolution.

**Comment by chrishtr** [comment]
This new behavior will also prevent us from having to do any work for `content-visibility:hidden` subtrees regardless of the dictionary value, because it will always return false regardless.

**Comment by tabatkins** [comment]
I can't tell from this discussion what options, if any, we settled on adding initially; there's discussion about several, but each either seems theoretical or is explicitly talked about as "not yet". @chrishtr ?

**Comment by tabatkins** [comment]
Possible options, from the above discussion:

* `trackInert`
* `trackAriaHidden`
* `trackOpacity`
* `trackVisibilityCSS`
* `trackOcclusion`
* `trackViewport`

As far as I can tell, Chris [has said he'd like to add the first two](https://github.com/w3c/csswg-drafts/issues/6850#issuecomment-1027346419), but he'd [prefer not to add the latter four until there's an author request](https://github.com/w3c/csswg-drafts/issues/6850#issuecomment-1011388347).

**Comment by chrishtr** [comment]
I am ok adding inert, aria-hidden, opacity, and visibility now. The other two (occlusion and viewport) have significantly higher implementation runtime cost and I don't want to implement them unless it's very clear `IntersectionObserver` doesn't solve a particular use case, since `IntersectionObserver` is otherwise a more performant solution.

Also: we changed the name to "check" instead of "track", i.e. `checkInert`, etc.

**Comment by tabatkins** [comment]
All right, added those four options. Looks like this closes out the issue resolution, so I'll go ahead and close the issue.

**Comment by josepharhar** [comment]
I ran into some problems while implementing the `trackAriaHidden` option, so I am proposing that we remove it here: https://github.com/w3c/csswg-drafts/issues/7232
