### ISSUE TITLE
Updated WD of CSS Color 4 (for wide review before CR) and CSS Color 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6854]
CSS Color 4 has had [significant changes since the previous publication](https://drafts.csswg.org/css-color-4/#changes-from-20210601) including the incorporation of multiple WG resolutions like adding OKLab/OKLCH, moving `@color-profile` to Color 5, and so on. [Some open issues remain](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Acss-color-4). There are two very complete implementations, WebKit (Safari 15) and BFO Publisher. The spec is close to CR, so I want to republish and advertise wide review. 

CSS Color 5 has also seen [significant changes](https://drafts.csswg.org/css-color-5/#changes-20210601) and is also seeing implementation.

The two specifications should be republished together.

**Comment by astearns** [comment]
The CSSWG just discussed this:

Topic: Color 4 and Color 5 Publication
chris: Fairly major changes with WG consensus, including shifting stuff
chris: significant edits in last 6 months
chris: regular WD
chris: for Color 4, hopefully last publication as a WD
astearns: Any objections?
RESOLVED: Publish Color 4 and Color 5 as WD

**Comment by svgeesus** [comment]
CSS Color 4 [published 15 Dec](https://www.w3.org/TR/2021/WD-css-color-4-20211215/)
CSS Color 5 [published 15 Dec](https://www.w3.org/TR/2021/WD-css-color-5-20211215/)
