### ISSUE TITLE
[css-color-5] Relative color syntax should be updated for new srgb-linear, xyz-d50 and xyz-d65 color spaces allowed in the color() function

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6858]
The section on using relative color syntax with the `color()` function, https://drafts.csswg.org/css-color-5/#color-function, should be updated to include `srgb-linear`, `xyz-d50` and `xyz-d65`.

Specifically, https://drafts.csswg.org/css-color-5/#predefined-rgb should be update to:

```
predefined-rgb = srgb | srgb-linear | display-p3 | a98-rgb | prophoto-rgb | rec2020
```

and https://drafts.csswg.org/css-color-5/#xyz-params should be update to:

```
xyz-params = [ xyz | xyz-d50 | xyz-d65 ] [ <number> | none ]{3}
```

I think that's the right syntax, might make sense to break it out to match the rgb ones into something like:

```
xyz = xyz | xyz-d50 | xyz-d65
xyz-params = <xyz> [ <number> | none ]{3} 
```

There are also some issues in the text below that:

- The section at https://drafts.csswg.org/css-color-5/#valdef-color-x states that it is "conversion to relative, D50-adapted CIE XYZ color space", but the white point is now dependent on which variant is chosen.
- The paragraphs starting "An `<ident>` or `<dashed-ident>` denoting the color space. If this is an `<ident>` it denotes one of the predefined color spaces CSS Color 4 § 10.2 Predefined color spaces: srgb, display-p3, a98-rgb, prophoto-rgb, rec2020, and xyz. (such as display-p3);" should be update for the new color spaces.

**Comment by svgeesus** [comment]
Thanks for your detailed review.

On your last bullet point, it is the title of CSS Color 4 10.2 which needs to be updated.

**Comment by svgeesus** [comment]
Oh actually, Bikeshed is picking up the title of that section from the /TR version of Color 4. The edit to the section title has already been made to the ED of Color 4 so that will fix itself next time Color 4 and 5 get published to /TR which is on the agenda for this week's call
