### ISSUE TITLE
[css-color-5] color-mix() serialization should be updated to cover all interpolation methods

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6859]
The specification for the serialization of `color-mix()`, https://drafts.csswg.org/css-color-5/#serial-color-mix, should be update to cover all the interpolation methods. This means adding:

- `srgb-linear`
- `xyz-d50`
- `xyz-d65`

**Comment by svgeesus** [comment]
Good catch, will do.

**Comment by weinig** [comment]
What is the rationale that `color-mix(in srgb-linear ...)` serializes to `color(srgb ...)` and not `color(srgb-linear ...)`.

**Comment by svgeesus** [comment]
Oh gosh my brain is tired. Yes, of course :facepalm:
