### ISSUE TITLE
[css-syntax] What actually defines handling of url function-token things in property values like background-image?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#686]
https://drafts.csswg.org/css-syntax/#consume-ident-like-token defines that url("foo") should return a function token, but I have yet to find a spec that says what to do with

    background-image: url("foo");

if a function token is returned...  This may not be a syntax issue per se, but it sure does make it impossible to actually implement CSS.

**Comment by tabatkins** [comment]
<https://drafts.csswg.org/css-values/#urls> defines it.

**Comment by SimonSapin** [comment]
https://drafts.csswg.org/css-backgrounds/#image should be changed to link to https://drafts.csswg.org/css-values/#urls
