### ISSUE TITLE
[css-color-5] Clarify serialization of color-mix() using hsl and hwb interpolation methods

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6860]
The spec, https://drafts.csswg.org/css-color-5/#serial-color-mix, is a bit ambiguous about what the serialization behavior of `color-mix(in hsl ...)` and `color-mix(in hwb ...)` should be.

The chart maps `hsl` to the `hsl(h s l)` form and `hwb` to the `hwb(h w b)` form, and I take that to mean we should serialize how `hsl()` and `hwb()` serialize, namely 8-bit `rgb(r, g, b)` or `rgba(r, g, b, a)`, but if that is the intention, it was be good to call that out.

If its not the intention, and they should serialize to actually be the string `hsl( .... )` and `hwb( ... )` that too could use clarification.

**Comment by weinig** [comment]
Thanks for the clarification. I think you could probably wait to see if someone else has the same confusion to make the change. Just one dummy doesn't require it ;).

**Comment by svgeesus** [comment]
Looking at this again, we decided earlier that mixing in the `srgb` colorspace should serialize as `color(srgb r g b) ` to take advantage of the higher minimum precision, compared to `rgb(r g b)`.

Given that, maybe mixing in `hsl` or `hwb` should also serialize to `color(srgb r g b) ` for the same reason?

**Comment by weinig** [comment]
That seems like a perfectly acceptable choice. If a user really wants it in the 8-bit form, they can always do:

`rgb(from color-mix(hsl ...) r g b / alpha)`

(though this begs the question as to whether we should just eliding the components in relative color syntax to make this kind of "casting" work).

**Comment by svgeesus** [comment]
@LeaVerou what do you think?

**Comment by LeaVerou** [comment]
> (though this begs the question as to whether we should just eliding the components in relative color syntax to make this kind of "casting" work).

Not sure I get what you mean here?

**Comment by weinig** [comment]
> > (though this begs the question as to whether we should just eliding the components in relative color syntax to make this kind of "casting" work).
> 
> Not sure I get what you mean here?

I meant, should we support something like:

```
rgb(from color-mix(hsl ...))
```

The effect of this would be to suggest to the engine that only 8 bits per component are needed, and that it wants the `rgb()` style serialization.
