### ISSUE TITLE
[css-cascade-6] First Public Working Draft of `@scope`

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#6865]
@fantasai and I worked on an updated draft of the Scope feature in the [css-cascade-6 Editor's Draft](https://drafts.csswg.org/css-cascade-6/). There are still a range of open questions on the spec, but I think we're on the same page about the general direction – and ready to move this into a Working Draft.

@astearns we can use this issue in place of #5809 for the extended call tomorrow. I'll close that issue again.

**Comment by astearns** [comment]
The CSSWG just discussed this:

Topic: FPWD of Scope
miriam: Brought a scope proposal a few times
miriam: last time I brought it up for FPWD, fantasai wanted to review with me
miriam: we spent some time in September, and published ED with some revisions
miriam: We're both happy with the rough direction, still a lot more to do
miriam: but wanted to get to FPWD and work on it from there
astearns: any concerns about taking on as FPWD?
<TabAtkins> +1
RESOLVED: FPWD Cascade 6
miriam 🥳

**Comment by svgeesus** [comment]
[FPWD of Cascade 6](https://www.w3.org/TR/2021/WD-css-cascade-6-20211221/) 21 Dec 2021
