### ISSUE TITLE
[css-fonts] Updated WD of CSS Fonts 4 and CSS Fonts 5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6868]
[CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/) has had [significant changes](https://drafts.csswg.org/css-fonts-4/#changes-2021-07-29) since the July 2021 WD and should be republished.

[CSS Fonts 5](https://drafts.csswg.org/css-fonts-4/) has also has [a couple of changes](https://drafts.csswg.org/css-fonts-5/#changes) and should be republished so 4 and 5 stay in sync.

(@fantasai will raise a [separate issue about Conditional 4](https://github.com/w3c/csswg-drafts/issues/6889), which also just got updated for `font-technology()` -> `font-tech()`, and should be republished so Conditional 4 and Fonts stay in sync)

**Comment by svgeesus** [comment]
Looks like this issue didn't pick up the discussion on the call just now.

**Comment by fantasai** [comment]
Minutes: https://www.w3.org/2021/12/15-css-minutes.html#t10

**Comment by svgeesus** [comment]
> Before we publish I'd like to make one more edit about how CSS variables interact with font palette values

Latest I can ask for publication is Monday 20th because webmaster is currently wanting 3 working days notice, and FPWD (for Conditional 5) is manual not automatic publication, and we want all three specs to be published the same day as they link to each other.

**Comment by litherum** [comment]
Sure, that should work great. The PR with the edit is at https://github.com/w3c/csswg-drafts/pull/6893 and it looks like you merged it already.

**Comment by svgeesus** [comment]
I prepared Conditional 5 for publication, FPWD is approved and the publication request is sent with publication expected Tues 21st.

Fonts 4 and Fonts 5 have updated changes list, are both set to WD and are both passing pubrules check, so I can do an automatic publication on Tuesday as well.

**Comment by svgeesus** [comment]
[CSS Conditional 5](https://www.w3.org/TR/2021/WD-css-conditional-5-20211221/)
[CSS fonts 4](https://www.w3.org/TR/2021/WD-css-fonts-4-20211221/)
[CSS Fonts 5](https://www.w3.org/TR/2021/WD-css-fonts-5-20211221/)
