### ISSUE TITLE
[css-values] Switch [..]! to ?? combinator

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#687]
Seriously, the `offset` syntax is painful to read. Can we please switch from the ! required multiplier to an "in order, either or both" combinator?

```
[ <offset-position>? [ <offset-path> [<offset-distance> || <offset-rotation>]? ]? ]!
[ / <offset-anchor> ]?
```

vs

```
<offset-position> ?? [ <offset-path> [<offset-distance> || <offset-rotation>]? ] ?? [/ <offset-anchor>]
```

**Comment by fantasai** [comment]
Bleh, sorry, that last bit should have been
```
<offset-position> ?? [ <offset-path> [<offset-distance> || <offset-rotation>]? ] ?? [/ <offset-anchor>]
```

**Comment by ewilligers** [comment]
Also possible, without needing a new combinator, is

`[ <offset-position> | [ <offset-position>? <offset-path> [<offset-distance> || <offset-rotation>]? ] ]
[ / <offset-anchor> ]?`

**Comment by SebastianZ** [comment]
> Also possible, without needing a new combinator, is
> 
> ```[ <offset-position> | [ <offset-position>? <offset-path> [<offset-distance> || <offset-rotation>]? ] ] [ / <offset-anchor> ]?```

That seems wrong, because the right side of the pipe may be omitted completely. The correct syntax would then be (formatted for better readability):

    [
      <offset-position> |
      <offset-path> [ <offset-distance> || <offset-rotation> ]? |
      <offset-position> <offset-path> [ <offset-distance> || <offset-rotation> ]?
    ] [ / <offset-anchor> ]?

This makes the definition a bit long, so I can understand that @fantasai wants to add a new combinator. If one is to be created, I think it would look better like this, though:

    [ <offset-position> ?! [ <offset-path> [ <offset-distance> || <offset-rotation> ]? ] ]
    [ / <offset-anchor> ]?

or to use `?!` as a multiplier:

    [ <offset-position>?! [ <offset-path> [ <offset-distance> || <offset-rotation> ]? ]?! ]
    [ / <offset-anchor> ]?

Sebastian

**Comment by tabatkins** [comment]
Why use `?!`?

**Comment by SebastianZ** [comment]
Because it seems logical for "all items are optional but at least one of them must be present", where `?` symbolizes the optionality and `!` the enforcement of at least one. Also, it conforms with what we currently use, i.e. `[ A? B? C? ]!`.

Sebastian

**Comment by tabatkins** [comment]
After discussion, @fantasai and I decided that it isn't worth pursuing an "inline" combinator for this. There are only two instances in CSS that can currently use it - `<page-selector>` and 'offset' - and then two more instances that could use something similar to it that allowed for separator characters - the `image()` function (needs commas) and the middle production of the the 'border-image' grammar (needs slashes).

Defining the rules for the latter two would be complicated and probably confusing, leaving us with only two instances that can actually use it. So, it's not currently worthwhile to do it.
