### ISSUE TITLE
[css-contain-3] Spec syntax for size queries

### ISSUE THREAD

**Issue by una** [w3c/csswg-drafts#6870]
[Contain level 3](https://drafts.csswg.org/css-contain-3/) adds a `size()` function for querying the parent size. 

I understand this makes it more explicit due to multiple types of queries (i.e. its possible to query  a `style()` in this spec). However, this might be potentially confusing for someone expecting the same experience as `@media`, i.e `@media (min-width: 300px)`.

1. Would it be possible to support both syntaxes (`@container (min-width: 300px)` *and* `@container size(min-width: 300px)`)  to reduce developer confusion and possible frustration? 

2. If we introduce `size()` for `@container`, we should probably also support `size()` for `@media`.

**Comment by SebastianZ** [comment]
The examples within the spec. already indicate that the function names are not needed. E.g. the example in [Size Container Features](https://drafts.csswg.org/css-contain-3/#size-container) looks like this:

```css
@container (width > 40em) {
  h2 { font-size: 1.5em; }
}
```

Though the [syntax definition](https://drafts.csswg.org/css-contain-3/#at-ruledef-container) currently does not allow that.

@una Your examples are missing the colon between property name and value.

Sebastian

**Comment by bramus** [comment]
@SebastianZ The syntax and examples indeed are out of sync. This has been reported in this separate issue: https://github.com/w3c/csswg-drafts/issues/6820

As @mirisuzanne replied in https://github.com/w3c/csswg-drafts/issues/6393#issuecomment-991398233:

>  I'll make sure to update the examples at some point here.

With the holidays around, it'll take some time though.

**Comment by dbaron** [comment]
To follow up to today's call, I think I'd lean towards dropping the `size()` syntax and having only the `()` syntax for size queries, to support both (a) consistency with `@media` and (b) not having multiple ways to write the same thing (which makes the language harder to read).  I'd want to keep `style()`.

**Comment by yisibl** [comment]
Chrome `Remove size() function` in https://chromium-review.googlesource.com/c/chromium/src/+/3497743
