### ISSUE TITLE
[css-cascade] Cascade layers, `!important` and the style attribute

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6872]
I was looking at some of the new cascade features and how `!important` and layers interact, and there are WPT tests that make conflicting interpretations of the spec and reality, in a way that I have no idea how to make the test pass without horrible hacks.

So https://github.com/web-platform-tests/wpt/blob/fea1b24572b53e22e1af873e56607251653df68d/css/css-cascade/layer-vs-inline-style.html asserts that:

> Important inline style > important layered style

Which makes some amount of sense per https://drafts.csswg.org/css-cascade-5/#style-attr, which says that the style attribute gets cascaded separately. However that's clearly not what is going on in browsers, which clearly cascade the style attribute like the last "regular" rule in the same tree as the element (so the `:host` rule in the example below overrides it):

```html
<!doctype html>
<style>
  div { width: 100px; height: 100px }
</style>
<div style="background-color: blue !important"></div>
<script>
  document.querySelector("div").attachShadow({ mode: "open" }).innerHTML = `
    <style>
      :host { background-color: green !important }
    </style>
  `;
</script>
```

So I think the spec is sane, conceptually, but the spec doesn't match the behavior of browsers. I think the behavior of browsers seems ok (otherwise we prevent web components from enforcing styles).

But then if we want the style attribute to behave like it does in browsers (cascading with the other rules of the element subtree) and we want `!important` to behave with layers as the spec says (important layered styles override important unlayered styles) we need some more subtle definition for this. Otherwise I'd expect the "Important inline style > important layered style" expectation to just be wrong.

Either way something needs to change in either the spec or the implementations.

cc @mirisuzanne @fantasai @xiaochengh

**Comment by emilio** [comment]
cc @anttijk

**Comment by emilio** [comment]
So after talking a bit with @anttijk we came to a somewhat "sane" model which is something like "the style attribute is cascaded in a separate layer order for which `!important` doesn't get this reversed-order behavior".

But honestly that's just what I was trying to avoid when filing the issue. And that certainly is not anything even close to what the spec says.

**Comment by xiaochengh** [comment]
I don't see any spec issue in your example.

The [spec](https://www.w3.org/TR/css-cascade-5/#cascade-context) says context (tree scope) is a higher-priority criterion than the style attr, and:

> When comparing two declarations that are sourced from different encapsulation contexts, then for normal rules the declaration from the outer context wins, and for important rules the declaration from the inner context wins.

So `background-color: green !important` from the shadow tree wins, and the div should be green.

**Comment by mirisuzanne** [comment]
That was my understanding as well. In this case, the `context` step is making the proper selection (inner tree wins when important) - and there is no need to consider the `element attached styles` step of the cascade.

**Comment by emilio** [comment]
Yeah I guess I misread that bit from the cascade as "style attribute is sorta its own origin", which was the argument made in https://github.com/w3c/csswg-drafts/issues/6743, but yeah I guess it's clear enough...
