### ISSUE TITLE
[css-values-4] Logical viewport units (vi, vb, etc) and writing-mode propagation

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#6873]
> [&lt;lvi, svi, etc> are] equal to 1% of the size of the large viewport size, small viewport size, and dynamic viewport size (respectively) in the direction of the **root element’s inline axis**.

If writing-mode is propagated from body to the viewport, are these units supposed to resolve according to the propagated writing-mode (e.g. if used on e.g. the root element)? At the time we know what to propagate from body, it's too late to change any interpretation of *i,*b on root.

Can we specify that these units resolve against the _computed value_ of writing-mode on the root element? This is what WebKit did in their implementation.

**Comment by fantasai** [comment]
I think that's probably fine. But now that I'm thinking about it... wouldn't we want it to resolve against the writing mode of the element on which it is used? E.g. if you're sizing a line of text to be 50% of the viewport, you'd want to use `vi` but you'd want it resolving against your own writing mode, not the root's writing mode...

**Comment by fantasai** [comment]
@andruud Agreed on both counts. :)
