### ISSUE TITLE
[css-inline] spec should define behavior when 'initial-letter' and 'float' both set on same element/pseudo-element

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#688]
The definition of [initial letter styling](https://drafts.csswg.org/css-inline/#initial-letter-styling) should specify what happens when <code>float</code> and <code>initial-letter</code> are set on the same element.

Prior to the introduction of initial letter styling, CSS had two types of </code>::first-letter</code> pseudo-elements:  (1) regular inlines and (2) floats.  Now (3) <code>initial-letter</code> creates a third, but I think it should be creating only one more and not two.  In particular, I don't think there should be two different types of initial letter.  (The spec certainly doesn't describe two such types.)

Then there's the question of, given code like:
```css
p::first-letter {
  float: left;
  initial-letter: 3 3;
}
```
which one wins.  That is, do we create a type (2) pseudo-element or a type (3) one.

I tend to think that if we want to allow authors to use various graceful degradation strategies (although they could do more with <code>@supports</code>, I suppose) it's probably better for the newer feature to override the older one, i.e., for the above case to result in the <code>float: left</code> being ignored.

Either way, this should be explicitly specified.

And I think that explicit specification should *probably* result in the computed value that is ignored being changed, although I haven't thought through the details of this at all.

**Comment by dbaron** [comment]
cc @chenpighead

**Comment by fantasai** [comment]
Currently, `float` values other than `none` are defined as causing `display` to compute to`block`, and `initial-letter` doesn't apply to blocks, only to inlines. So the end result is you get a floated `::first-line` pseudo-element if you specify both: `float` takes effect, and `initial-letter-*` is ignored.

@dbaron I think the `float`/`display` rules make this issue invalid. Please reopen if you think a different conclusion is needed.

**Comment by frivoal** [comment]
I agree with your conclusion that it is what happens given the current spec, but it seems to me that the opposite behavior might be helpful to let authors provide simple fallbacks without having to use `@supports`. Example:
```css
p::first-letter {
  initial-letter: 3;
  float: left;
  line-height: 1;
  font-size: 3em;
}
```
Having this do a float-based drop cap in legacy browsers, and an initial-letter based drop cap in newer ones would sound great.

Also, it is what happens in Safari.

**Comment by fantasai** [comment]
@frivoal If we're doing that, then I'd want `initial-letter` to cause `display` to compute to `inline` in that case.

**Comment by frivoal** [comment]
@fantasai that sounds reasonable to me.

**Comment by fantasai** [comment]
Added a note. Closing out~
