### ISSUE TITLE
[css-fonts-4] List additions since Level 3

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6882]
It would be nice to have a list of what's new since Level 3.

**Comment by xfq** [comment]
Do you mean something like:

* https://drafts.csswg.org/css-cascade-4/#additions-l3
* https://drafts.csswg.org/css-color-4/#changes-from-3
* https://drafts.csswg.org/css-contain-2/#l1-changes
* https://drafts.csswg.org/css-grid-2/#changes-2
* https://drafts.csswg.org/selectors-4/#changes-level-3
* https://drafts.csswg.org/mediaqueries-4/#changes-2012

**Comment by xfq** [comment]
If so, here is a brief summary (according to the current Table of Contents and the commit history):

* Added `font-display` descriptor for `@font-face`
* Added `@font-feature-values` rule
* Added font variation properties, including `font-optical-sizing` and `font-variation-settings`
* Added color font support
* Defined `feature-value-name` for `font-variant-alternates`
* Added new `auto` value for `font-weight`, `font-style` and `font-stretch` descriptors
* Added `ui-serif`, `ui-sans-serif`, `ui-monospace`, and `ui-rounded` generic font families
* Added `font-size: xxx-large`
* Added font metric override descriptors
* Added some motivation for generic font families
* Added font feature technology keywords opentype, aat, and graphite
* Added `math` value to `font-size`
