### ISSUE TITLE
[css-overflow-3] Does overflow-clip-margin only affect painting?

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#6884]
In [overflow-clip-margin](https://drafts.csswg.org/css-overflow-3/#propdef-overflow-clip-margin) text, it says

> This property defines the overflow clip edge of the box, i.e. precisely how far outside its bounds the box’s content is allowed to paint before being clipped by effects ...

Can I confirm that this means that this only affects [ink overflow](https://drafts.csswg.org/css-overflow-3/#ink) and not [scrollable overflow](https://drafts.csswg.org/css-overflow-3/#scrollable)?

In other words, I think the following should _not_ produce scrollbars on `.scroller`. Is that right?
```html
<style>
.scroller {
    overflow: auto;
    width: 100px;
    height: 100px;
}
.parent {
    width: 100px;
    height: 100px;
    overflow: clip;
    overflow-clip-margin: 10px;
}
.child {
    width: 200px;
    height: 200px;
}
</style>
<div class="scroller">
  <div class="parent">
    <div class="child"></div>
  </div>
</div>
```

**Comment by emilio** [comment]
I'd expect `overflow-clip-margin` to affect scrollable overflow, since `overflow: clip` does so, fwiw.

**Comment by vmpstr** [comment]
Ok, I think I might just be confused by the use of the word "paint".

It makes sense that this property just expands the clip for both overflows.
