### ISSUE TITLE
[css-values][css-syntax] Double definition of Indentifier

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6885]
Syntax-3 and values-4 both define (CSS) identifiers, which makes it annoying for other specs to cross-ref that term.

Syntax-3 has the more primary definition, which doesn't really depend on anything else:
https://www.w3.org/TR/css-syntax-3/#identifier

The definition in values 4 effectively points back to syntax-3, with a tiny little bit of indirection:
https://drafts.csswg.org/css-values-4/#css-css-identifier

The later should probably changed to just being a reference, rather than a definition.

**Comment by tabatkins** [comment]
After chatting with @fantasai, I switched Syntax to use "ident sequence" (and "ident character" and "ident-start character", leaving "ident" and "identifier" for V&U to use.

**Comment by tabatkins** [comment]
81cd63a04
