### ISSUE TITLE
[css-text-4] Is hyphenate-character stable enough to ship?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#6887]
I'm interested in implementing [the `hyphenate-character` property](https://drafts.csswg.org/css-text-4/#hyphenate-character) in Gecko.

Checking other browsers, I see that both Webkit and Blink have this property, but with the prefixed name `-webkit-hyphenate-character`; the non-prefixed version does not appear to be supported.

So... should we consider `hyphenate-character` stable enough that it's OK to implement and ship as an unprefixed property (and create some corresponding web-platform-tests), or would this be premature?

I see there has been some discussion (e.g. https://github.com/w3c/csswg-drafts/issues/2975) of additional potential values, e.g. to support cases where hyphenation inserts a character *after* the line-break in addition to (or instead of) *before* the break. But I don't think this needs to block shipping of the simple property as currently spec'd; a future extension could still introduce a two-valued syntax, for example, without affecting the current single-valued syntax.

**Comment by drott** [comment]
CC @kojiishi
