### ISSUE TITLE
[css-fonts] Font technology 'incremental' declaration is underspecified

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/csswg-drafts#6892]
CSS Fonts module was recently amended to add support for font-tech properties, including `tech(incremental)` in particular. The [§ 11.1. Font tech](https://drafts.csswg.org/css-fonts-4/#font-tech-definitions) describes this as follows:

> The incremental tech refers to client support for incremental font loading, using either the range-request or the patch-subset method [PFE-report].

Furthermore, the [Example 22](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing) claims to shows how `@font-face` declaration can be constructed for incremental transfer using the range-request method; however, it is not at all clear whether range-request or a patch-subset methods would be applied.

I believe this font-tech declaration is not sufficient and we should allow authors express their preferences for a particular method of incremental font loading. The data analysis section of the [PFE-report](https://www.w3.org/TR/PFE-evaluation/#analysis) (see cost analysis and Figures 17, 20, 23 in particular) makes it very clear that there are major differences between two methods, and the "wrong choice" of incremental font transfer method can have significant adverse effect on font loading time and user experience. Currently, the particular choice of incremental methods is not discussed in the CSS Fonts spec, and it is unclear how user agents would make this determination. The efficacy of incremental loading depends on many factors, including the language of the content and other features - the authors should be able to express their method preferences because the user experience can be significantly affected if the "wrong" incremental method is picked for a specific font in use.

Perhaps the `tech(incremental)` should be extended to allow `tech(incremental-patch)` and `tech(incremental-range)` be declared, in addition to ambivalent `tech(incremental)` itself.

**Comment by svgeesus** [comment]
> I believe this font-tech declaration is not sufficient and we should allow authors express their preferences for a particular method of incremental font loading. 

I agree. All the rest of the `tech()` (and corresponding `font-tech()`) express author preferences and constitute client-led content negotiation. 

> Perhaps the tech(incremental) should be extended to allow tech(incremental-patch) and tech(incremental-range) be declared

I would be fine with those names, which are consistent with the other hyphenated names used there..

**Comment by svgeesus** [comment]
Not hearing any disagreement (but also, no agreement) my plan is to put the two names into the spec and then get review from Web Fonts WG

**Comment by litherum** [comment]
This is being discussed https://github.com/w3c/IFT/issues/57. Let's let that conversation come to a conclusion before making any edits.

**Comment by svgeesus** [comment]
Fair enough, since that issue does not seem close to consensus

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/csswg-drafts/commit/a951f1f2e69e6945c6d44e7eca5809a3e15a8485
