### ISSUE TITLE
[css-cascade-6] What happens to other @rules inside @scope?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#6895]
Same question as https://github.com/w3c/csswg-drafts/issues/6827, but for `@scope`.

Conditional rules + `@layer` should be unproblematic, but we should probably steer away from actually introducing some new scoping semantics for _name-defining_ at-rules. https://github.com/w3c/csswg-drafts/issues/6827#issuecomment-977863129

**Comment by tabatkins** [comment]
Agreed. Suggest we match `@container` and just continue to treat the rules as global.
