### ISSUE TITLE
CSS tests - how to fix?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6896]
This is more of a question. The initial motivation is tests for CSS Color 4 and 5, but I guess it applies to all tests.

The [Implementation report grouped by spec section](https://test.csswg.org/harness/results/css-color-4_dev/grouped/) is very helpful, but is missing tests and test results.

If I look at [the list of test suites]() then Color 4 is listed and Color 5 is not. Also, for Color 4, the [numbering and section titles are incorrect, there are missing sections](https://test.csswg.org/harness/review/css-color-4_dev/).

![image](https://user-images.githubusercontent.com/2506926/146374703-5e3597bb-1097-4719-8d31-c90000602e2a.png)

compared to the [ED ToC](https://drafts.csswg.org/css-color-4/#toc) or the [TR Toc](https://www.w3.org/TR/css-color-4/#toc)

![image](https://user-images.githubusercontent.com/2506926/146375312-5639f47e-e606-4fae-8483-70262262dacc.png)

For example the spec has

- 9.3 Specifying Lab and LCH: the lab() and lch() functional notations [#specifying-lab-lch](https://drafts.csswg.org/css-color-4/#specifying-lab-lch)
- 9.4 Specifying OKLab and OKLCH: the oklab() and oklch() functional notations [#specifying-oklab-oklch](https://drafts.csswg.org/css-color-4/#specifying-oklab-oklch)

tests are listed for 9.3, but none for 9.4 even though they exist.

```
$ grep -l specifying-lab-lch *.*
lab-001.html
lab-002.html
lab-003.html
lab-004.html
lab-005.html
lab-006.html
lab-007.html
lab-008.html
lch-001.html
lch-002.html
lch-003.html
lch-004.html
lch-005.html
lch-006.html
lch-007.html
lch-008.html
```

compare to

```
$ grep -l specifying-oklab-oklch *.*
oklab-001.html
oklab-002.html
oklab-003.html
oklab-004.html
oklab-005.html
oklab-006.html
oklab-007.html
oklab-008.html
oklch-001.html
oklch-002.html
oklch-003.html
oklch-004.html
oklch-005.html
oklch-006.html
oklch-007.html
oklch-008.html
```

Similar issue for [the definition of display-p3](https://drafts.csswg.org/css-color-4/#valdef-color-display-p3) [#valdef-color-display-p3](https://drafts.csswg.org/css-color-4/#valdef-color-display-p3) where there are no listed tests and yet 8 exist currently

```
$ grep -l valdef-color-display-p3 *.*
display-p3-001.html
display-p3-002.html
display-p3-003.html
display-p3-004.html
display-p3-005.html
display-p3-006.html
predefined-005.html
predefined-006.html
```

The situation for CSS Color 5 is even worse, there are tests and there is no listed testsuite at all.

```
$ grep -l css-color-5 *.*
color-contrast-001.html
color-mix-basic-001.html
color-mix-non-srgb-001.html
$ cd parsing/
$ grep -l css-color-5 *.*
color-contrast-computed.html
color-contrast-invalid.html
color-contrast-valid.html
color-mix-computed.html
color-mix-invalid.html
color-mix-valid.html
relative-color-computed.html
relative-color-invalid.html
relative-color-valid.html
```

The [documentation on the wiki](https://wiki.csswg.org/test) is out of date and mostly talks about a Mercurial repository that was last updated in 2018. The actual tests are pulled from WPT, I know. But I can't see what to edit or change to make it see the existing tests or to update the text of headings corresponding to test anchors.

**Comment by svgeesus** [comment]
There is a [test suite management system](https://test.csswg.org/shepherd/) which seems to relate to the old Mercurial repo and lists an even smaller set of tests

![image](https://user-images.githubusercontent.com/2506926/146379384-8a6d6cc5-7568-4d28-96c8-a2c723fd1930.png)

**Comment by svgeesus** [comment]
@fantasai @tabatkins @plinss @florian is there some secret documentation that I missed?

Oh I also found [this page](https://test.csswg.org/suites/css-color-4_dev/) which has a zipfile, but all the files in there are from 19 April 2021.

**Comment by florian** [comment]
You meant to @ mention a different Florian.

**Comment by svgeesus** [comment]
I did, @frivoal

**Comment by plinss** [comment]
Shepherd was built for the old mercurial repo, and hasn't had good data about the actual tests available since they moved to WPT. Shepherd does still share the specification and test suite modules which define the list of knowns specs and test suites for the build system. Shepherd's spec parser is also still running and priovides the anchor database for Bikeshed.

The admin>specs section of Shepherd (and the test harness, and the draft server, since they all use the same Shepherd module) is where you maintain the list of specs. The dates listed are the last seen published dates of spes that have been parsed. The edit button does work (mostly), but you have to scroll to the bottom of the page to see the edit controls. It's only for editing the main spec info tho.

The main problem you're running into is that the nightly builds of the test suites have been failing for some time, so the built test suites are quite out of date. One or more of the tests is causing the build code to crash, here's the latest stack trace:

```
 in: lifecycle/set-composited-layer-position.html
Traceback (most recent call last):
 File "css/tools/build.py", line 385, in <module>
   result = builder.build(args)
 File "css/tools/build.py", line 329, in build
   testSuite.buildInto(workPath, indexer)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Suite.py", line 97, in buildInto
   group.build(format)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Groups.py", line 189, in build
   self.refs.write(format)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Sources.py", line 281, in write
   format.write(source)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/OutputFormats.py", line 99, in write
   source.write(self, source.serializeXHTML())
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Sources.py", line 1447, in serializeXHTML
   nodeList = self.injectNamespaces()
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Sources.py", line 1429, in injectNamespaces
   self._injectNamespace('html', None, 'http://www.w3.org/1999/xhtml', False, nodeList)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Sources.py", line 1417, in _injectNamespace
   elements = self._findElements(namespace, elementName)
 File "/sites/test.csswg.org/builder/web-platform-tests/css/tools/w3ctestlib/Sources.py", line 1410, in _findElements
   elements = self.tree.findall('.//{' + namespace + '}' + elementName)
AttributeError: 'NoneType' object has no attribute 'findall'
```

I don't have the bandwidth to dig into the root cause or fix this right now (see the 'no one is paying me to do W3C work and I'd have to take time away from my paid hourly contracting work that I can't afford to do' issue with the draft server).

**Comment by svgeesus** [comment]
Got it, thanks

**Comment by svgeesus** [comment]
Re-opening because, apparently some funding has happened and some work has been done and the stability of serving [drafts.csswg.org ](https://drafts.csswg.org/)has somewhat improved, so there is some hope that this issue too might be fixed at some future time.

**Comment by plinss** [comment]
There is some funding and there is ongoing work to improve the server’s stability and performance. (As you noted, the DB is no longer falling over, but there’s still work to do on general performance.)

However, the current funding isn’t covering specific improvements to the test infrastructure (aside from porting to Python 3).

I’m happy to leave this issue open for now. If the build fix is something relatively simple it may fall out of the porting and migration (other work is higher priority), but we may need to seek additional funding in the future for more serious changes.

**Comment by foolip** [comment]
@tabatkins said on the web-platform-tests Matrix chat last week that it would be OK if we (the WPT maintainers) drop support for the WPT build system. I tried out what that might look like https://github.com/web-platform-tests/wpt/pull/38976 and started working on https://github.com/web-platform-tests/rfcs/pull/136.

That RFC doesn't have any of the background or detail needed, but I'd like to flag here early that I'm looking at it. If that's a bad idea, please speak up.

**Comment by foolip** [comment]
The Matrix discussion is here:
https://matrix.to/#/!wKNaTuhRJSXtjUVpfk:matrix.org/$XKpyzRSRkkITMqojElJ9UYx7O3Gw__ASWtGqVv0WuUU?via=matrix.org&via=mozilla.org&via=igalia.com

**Comment by plinss** [comment]
The CSSWG's test harness still relies on the build system. So it's a matter of whether or not anyone still relies on the test harness. Last I know of @svgeesus was still using it to create implementation reports, but I don't know if that's still the case. If it's not being used anymore, I'd just as soon not have to support it anymore.

**Comment by svgeesus** [comment]
>Last I know of @svgeesus was still using it to create implementation reports

No, I had to stop doing that because the tests had not been updated (corrections, new tests) for more than 2 years compared to WPT tests which are actively maintained, so they were actively misleading and harmful at this point.

**Comment by tabatkins** [comment]
We've done impl reports using just WPT for a while now, so in practice it's sufficient (but very likely improveable).

> Some of the historical needs for the harness were for tracking fully manual and reference tests, I don't know how/if WPT deals with those these days or if they're still relevant.

Ref tests are just fine in WPT. Fully manual tests pretty much don't, and it's an open issue on how to make them potentially relevant. As they currently exist, they're run so rarely that they're often completely incorrect anyway, so their value is very suspect.

**Comment by svgeesus** [comment]
>so in practice it's sufficient (but very likely improveable).

Yeah, that would be:

 - https://github.com/speced/bikeshed/issues/2216

**Comment by foolip** [comment]
Would it be appropriate to get a WG resolution on this, effectively approving that WPT drops support for the old CSS build system requirements? If so, can someone agenda+ this? I am WG member, so I could join the call where it's discussed if needed.

**Comment by fantasai** [comment]
> Would it be appropriate to get a WG resolution on this, effectively approving that WPT drops support for the old CSS build system requirements?

@foolip Can you define what this means exactly?

> Some of the historical needs for the harness were for tracking fully manual and reference tests, I don't know how/if WPT deals with those these days or if they're still relevant.

IIRC, manual tests aren't managed in any way in WPT, and it's a problem for testing some of our features. I don't buy Tab's argument that the tests are likely broken because they haven't been run; they're much more likely still relevant. And we need *more* such tests, not fewer. There are a lot of platform features that aren't properly tested in WPT *because* they're unreasonable to automate.

@plinss What information is the test harness ingesting from the build system? If it's a manifest file of some kind, we could build an indexer that doesn't actually build the tests (which I agree is a step we no longer need).

**Comment by plinss** [comment]
IIRC the test harness just needs the manifest file from the build system. There may be some dependency on the flat structure of the build output, but I'm not sure if that matters anymore (it's been a while, so I'd have to dig into the code), id so it would probably be east to remove.

I do know that the builds started failing a while back and I haven't had the bandwidth to look into it, but all the relevant code is online so anyone can do it.

To me the bigger concern is that the build code as I last remember it was heavily dependent on the metadata stored in the tests. I don't know what the status of that these days is and what kind of metadata is available from in WPT. Updating/maintaining that may be a bigger deal.

If we do keep the harness, the manifest generator (part of the current build process) also needs to be ported over to Python 3, I really don't want to have to install Python 2 on the new server. There's also the matter of ensuring the old (PHP5) harness code will run on PHP8 for the new server, it might 'just work' or might need some updating.

**Comment by foolip** [comment]
> > Would it be appropriate to get a WG resolution on this, effectively approving that WPT drops support for the old CSS build system requirements?
> 
> @foolip Can you define what this means exactly?

There's the change itself and there's the CSSWG buy-in.

The proposed change is https://github.com/web-platform-tests/wpt/pull/38976, and the part that benefits the WPT project is removing the CSS-specific lints that are about directory structure and file naming, most notably the one requiring globally unique file names. This will make css/ follow the same naming rules as the rest of WPT.

Then there's the build system in css/tools/ that builds the directories ending with `_dev` that end(ed) up on https://test.csswg.org/. I just confirmed that it does run to completion locally:

```
sudo apt-get install python2.7 python2.7-dev
PYTHON=python2.7 ./build.sh
```

This code isn't run in WPT CI and doesn't do any harm, but when it's not running anywhere any longer we'd like to remove it.

Agenda+ and a resolution would be one way to ensure all the right people are aware of the issue, but the mechanism isn't important, I just don't want anyone to be surprised/unhappy if we make the change.

**Comment by foolip** [comment]
Regarding manual tests, when was the last time that manual tests were run using https://test.csswg.org/ and used in an implementation report? It looks like manual tests for CSS are very rarely added to WPT, I count 7 tests over 3 PRs in the past 2 years. https://github.com/web-platform-tests/wpt/issues/19105 is the main issue for supporting manual tests in WPT, but it seems hard to justify doing the work if it's rare. It's still possible to just visit https://wpt.live/css/css-writing-modes/alt-display-vertical-001-manual.html and note the results for one-off cases.

Regarding metadata, what metadata out of the tests are important for the CSSWG? I'm aware of [filtering by spec](https://github.com/web-platform-tests/wpt.fyi/issues/1489) and I think that feature would be broadly useful, but is there more?

**Comment by svgeesus** [comment]
`<link rel=help href="precisespec#reference">` is the most important one.

**Comment by svgeesus** [comment]
This one looks suitable for an async resolution @astearns @atanassov 

Proposed resolution (unless there are objections by 7 March 2023): the unused CSS build system on WPT will be removed.

**Comment by svgeesus** [comment]
>  would filtering that supports `spec:css-writing-modes-3` (using the level if it's in the spec link) be enough?

It is sufficient, but not ideal. One plus (given version-less directories) is that creating an implementation report for `css-foo-n` becomes possible without mixing in results from tests for `css-foo-n+1`.

`feature:foo` is an improvement, certainly; because we want to find features that are poorly or inconsistently implemented.

Two ways to create specific links to testable spec assertions are the `<link rel=help>` to link from test to spec, or alternatively the Bikeshed `<wpt>` element which contains links from spec to test.

**Comment by foolip** [comment]
@svgeesus my idea with `spec:css-writing-modes-3` was that directory names don't matter, only `spec` fields in `META.yml` files and in-test spec links like `<link rel=help href="precisespec#reference">`. But the results would only be as accurate as the metadata. Perhaps the most realistic use of levels would be to carefully fix the links for some next level features, to exclude those from an implementation report of current level spec. (To be able to exclude the _previous_ level features seems like far more work than I imagine anyone would be willing to spend, since that'd often be the majority of tests.)

Getting links via Bikeshed `<wpt>` is an interesting idea though, the data isn't as close at hand as the WPT repo itself, but it doesn't require any impossible engineering feats.

I'm glad that the `feature:foo` idea seems promising! It would also require a lot of metadata maintenance of course, but I think it'd be broadly useful.

**Comment by Ms2ger** [comment]
@svgeesus wrote on 24 March:

> Proposed resolution (unless there are objections by 7 March 2023): the unused CSS build system on WPT will be removed.

I suppose the deadline is incorrect

**Comment by svgeesus** [comment]
Should have been April; but the chairs have not picked up the proposed resolution so it is off anyway.

**Comment by astearns** [comment]
Sorry, I was trying to get to these each Monday but fell behind.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: The unused CSS build system on WPT will be removed.

**Comment by astearns** [comment]
RESOLVED: The unused CSS build system on WPT will be removed.

**Comment by foolip** [comment]
Thanks you @astearns!
