### ISSUE TITLE
drafts.csswg.org is empty currently

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#6906]
https://drafts.csswg.org/ has nothing listed there, and spec address (like https://drafts.csswg.org/selectors-4/) shows the source directory rather than the generated document.

Something is broken?

**Comment by plinss** [comment]
Fixed

**Comment by upsuper** [comment]
@plinss It happens again. Could you have a look?

**Comment by SamB** [comment]
Might be a good idea to pin this issue. I was going to report it myself, but I was looking through the labels to find something to prefix my issue title with, and "meta" sounded good so I went to go see whether it was actually being used for the sort of issue I wanted to report and ...

**Comment by astearns** [comment]
Closing this in favor of #6528 since it’s the one we use most often. I have now pinned it, too
