### ISSUE TITLE
[css-2021] CSS Counter Styles Level 3 is listed in 2.1 and 2.2

### ISSUE THREAD

**Issue by BartolomeSintes** [w3c/csswg-drafts#6908]
CSS Counter Style level 3 is included both in section 2.1 The Official definition and in section 2.2 Fairly stable modules

In CSS 2020 this recommendation was listed in Fairly Stable. If this year is has been upgraded into the Official Definition, perhaps it should be removed from the Fairly stable list.

Thanking you in advance,
Bartolome Sintes

**Comment by frivoal** [comment]
Good catch, thank you for noticing this mistake. We have indeed decided to move it to the official definition, and I just failed to remove it from the fairly stable part while doing that. This has now been corrected in the editor's draft.
