### ISSUE TITLE
[css-logical-props][css-writing-modes] Specify relation of text-orientation with abstract-to-physical mapping

### ISSUE THREAD

**Issue by Manishearth** [w3c/csswg-drafts#691]
In [writing-modes §3 Logical Box Properties](https://drafts.csswg.org/css-logical-props/#logical-box-props), it says

> Which pairs of properties share computed values depends on the computed values of writing-mode, text-orientation, and direction. For a summary of these dependencies, see [Abstract-to-Physical Mappings](https://drafts.csswg.org/css-writing-modes/#logical-to-physical)

The actual linked abstract-to-physical mappings do not mention text-orientation at all. They should, if there indeed is a dependence.

cc @heycam

**Comment by kojiishi** [comment]
Thank you for the good catch, there was a value `text-orientation: sideways-left` in old draft that affected logical properties, but we removed it to prefer `writing-mode: sideways-lr`.

`text-orientation` should be removed from this list.

**Comment by Manishearth** [comment]
Will `text-orientation: sideways` still affect this?

**Comment by kojiishi** [comment]
Ah, no, I missed one other thing, sorry.

`text-orientation: sideways` does not affect this.

However, there's a sentence saying [text-orientation: upright](https://drafts.csswg.org/css-writing-modes-3/#valdef-text-orientation-upright):

> This value causes the used value of direction to be ltr, and for the purposes of bidi reordering, causes all characters to be treated as strong LTR.

Currently only Gecko implements this partially, and no browsers pass tests. See [status](http://kojiishi.github.io/generate-w3c-implementation-report/css-writing-modes-3/status-2016-09.html) Required Tests That Do Not Meet Exit Criteria, item 2.

This was once discussed in the last F2F but we haven't come to the conclusion yet.

**Comment by kojiishi** [comment]
Allow me to revise this again. By reading this again, it says the value changes the used value of direction, so it looks to me that it is correct to say "depends on direction" but not on text-orientation. Does my reading look correct?

**Comment by dbaron** [comment]
I agree that text-orientation can be removed from the list of properties that the mapping depends on.

**Comment by atanassov** [comment]
I too agree, this was a left over from 'sideways-left' value at the time. I'll go ahead and merge the PR.

**Comment by prjnt** [comment]
The text said "depends on the *computed* values of ... and text-orientation.
I suppose that inline-start should be defined in terms of the *used* value of 'direction', which is calculated from the computed values of 'text-orientation' and 'direction' in the current editors' draft of css-writing-modes.

Regardless, the text should be clarified as to computed vs used value of 'direction'.  I.e. if it is decided to differ from the used value of 'direction', then attention should be drawn to this; or if not, then attention should be drawn to the fact that the used value of 'direction' is calculated from the computed values of 'direction' and 'text-orientation'.

**Comment by Manishearth** [comment]
> which is calculated from the computed values of 'text-orientation' and 'direction' in the current editors' draft of css-writing-modes.

Could you point out where it says this? I can't find it.

There should be no dependence of logical properties on text-orientation (in its current form) because text-orientation doesn't affect flow at all. It used to, but it doesn't anymore.

**Comment by prjnt** [comment]
https://drafts.csswg.org/css-writing-modes/#valdef-text-orientation-upright : 
# This value causes the used value of direction to be ltr, ...

**Comment by prjnt** [comment]
[oops, sorry about the unintentional formatting: that was supposed to be a literal hash mark to denote quotation of spec.]

**Comment by Manishearth** [comment]
Huh. That ... doesn't really make sense to me, but I'll go through the entire spec again tomorrow.

**Comment by prjnt** [comment]
My understanding is that with text-orientation:upright and vertical writing, the letters are written top-to-bottom whether they're latin or hebrew (the "all characters ... strong LTR" part).  If that is correct, then it seems reasonable for me for "inline-start" to refer to physical top whether in a dir=ltr latin or dir=rtl hebrew element.

**Comment by fantasai** [comment]
Linking in Peter Moulder's comments from www-style for future reference: https://lists.w3.org/Archives/Public/www-style/2016Dec/0077.html
Also his testcase: http://www.users.on.net/~pjrm/css-tests/logical-props/upright.html

**Comment by fantasai** [comment]
<a href="https://www.w3.org/TR/css-writing-modes-3/#logical-directions">CSS Writing Modes Level 3 &sect;6.2. Flow-relative Directions</a>:
> inline-start
> The side from which text of the inline base direction would start. For boxes with a _used_ `direction` value of `ltr`, this means the line-left side. For boxes with a _used_ `direction` value of `rtl`, this means the line-right side. 

<a href="https://www.w3.org/TR/css-writing-modes-3/#text-orientation">CSS Writing Modes Level 3 &sect;5.1. Orienting Text: the text-orientation property</a>:
> upright
> &hellip;  This value causes the _used value_ of `direction` to be `ltr`, and for the purposes of bidi reordering, causes all characters to be treated as strong LTR.

I think we just need to clarify here that the used value is what's used... this still means the mapping depends only on computed `writing-mode`, `direction`, and `text-orientation`: `text-orientation: upright` basically forces used `direction` to `ltr`, that's all.

**Comment by fantasai** [comment]
Added some notes to the writing-mode spec to make this interaction a little more obvious: d94f20d6a1d0f5db85c0af924d6e37a9bf3e0d23 and b5b39d926d2878bc5211038024496c834b51f02a

**Comment by fantasai** [comment]
Summarized those notes and copied over a few diagrams from css-writing-modes into the Introduction of css-logical-1.

Closing out this issue as editorial, since there were no normative changes.
