### ISSUE TITLE
CSS Color 3: Proposed Changes

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6910]
The [CSS Color 3 Recommendation](https://www.w3.org/TR/css-color-3/) of August 2021 has had enough time for review of the [four Candidate Corrections](https://www.w3.org/TR/css-color-3/#changes) so I would like to request transition to Recommendation with all four becoming Proposed Changes. 

That [makes them normative, triggers an AC review and patent exclusion opportunity](https://www.w3.org/2021/Process-20211102/#change-review), and after that they get folded into an updated Recommendation.

**Comment by svgeesus** [comment]
Although at least 3 of them could be considered editorial rather than substantive which [has a simpler process](https://www.w3.org/2021/Process-20211102/#revised-rec-editorial) so we should discuss that

**Comment by svgeesus** [comment]
Compare 

- [Updating an existing Recommendation with editorial changes](https://www.w3.org/Guide/transitions?profile=REC&rec=editorial)
- [Incorporating candidate corrections (substantive changes) into an existing Recommendation](https://www.w3.org/Guide/transitions?profile=REC&rec=substantive)

so the discussion boils down to "are all of [these changes](https://www.w3.org/TR/css-color-3/#changes) editorial, or is any one of them substantive?


1.    Candidate Correction 1: **Sample HSL values & conversion code.** The samples are explicitly non-normative. The code does not claim to be normative, but does not explicitly say it is informative either.
2.    Candidate Correction 2: **Clarified case-insensitive.** Since all the existing color names are ASCII-only, the clarification that "case insensitive means ASCII case insensitive" has no substantive impact.
3.    Candidate Correction 3: **Removed "Media" from property definition tables** same as all recent specs. I don't think removing `Media: visual` has any substantive impact on the `color` property.
4.    Candidate Correction 4: **Replaced "Call for implementation of dropped features"** That section, which contained no normative statements but called for implementations of dropped features like `@color-profile`, has been replaced by an (explicitly non-normative) forward pointer to the higher-level specs where those features are now defined. So, editorial.

My proposal to the group is therefore that all four of these changes are editorial and so we can follow the "Updating a Rec with entirely editorial changes" route.

If the group finds one or more of these to be substantive, then we need to follow the more lengthy (Last Call for the AC, etc) route for the substantive one(s). The remaining editorial ones can be simply folded in at the same time.

**Comment by frivoal** [comment]
I agree that CC2, 3, and 4 are editorial.

For CC1, I am on the fence. Unless I read the spec to fast, there is no other definition (either inline or by reference) of HSL or of about how one is supposed to go from RBG to HSL or vice-versa, which makes it tempting to consider the conversion code normative. I guess that the intended interpretation is that the normative definition is of HSL is meant to be implied as HSL is a well-know scheme, and the sample code is meant to be informative… In practice, that's what really happened, and I don't think anyone was looking at the ABC code to try and figure out what HSL was, but based on the content of the document alone, this seems tricky to establish?

Does [COLORIMETRY], which is a normative reference, contain a definition of HSL which we could consider to be the normative one? That would provide an out.

**Comment by svgeesus** [comment]
> I guess that the intended interpretation is that the normative definition is of HSL is meant to be implied as HSL is a well-know scheme, and the sample code is meant to be informative

Yes, same as the other sample code.

> Does [COLORIMETRY], which is a normative reference, contain a definition of HSL

No. But the original definition could be added:

Joblove, George H.; Greenberg, Donald (August 1978). "Color spaces for computer graphics" Computer Graphics. 12 (3): 20–25. doi:10.1145/965139.807362. 

https://dl.acm.org/doi/10.1145/965139.807362 (paywall)
https://en.wikipedia.org/wiki/HSL_and_HSV#Joblove

**Comment by svgeesus** [comment]
(Wikipedia btw currently has some stupid edit that HSL was invented in 1938, which is wildly incorrect.)

**Comment by svgeesus** [comment]
I'm certainly going to add the original HSL paper as a normative reference to CSS Color 4. CSS Color 3 just mentioned it in passing as something well known. Should I add it there, too?

**Comment by svgeesus** [comment]
The CSS Working Group just discussed `CSS Color 3: Proposed Changes`, and agreed to the following:

* `RESOLVED: Republish CSS Color 3 REC as editorial update`

<details><summary>The full IRC log of that discussion</summary>[19:06] <fantasai> Topic: CSS Color 3
[19:06] <fantasai> chris: We published an updated REC that includes 4 candidate corrections
[19:06] == mode/#css [+o astearns] by Yves
[19:06] <fantasai> chris: been up for review for a few months
[19:06] <fantasai> chris: minor things like removing 'Media' lines in propdef tables
[19:06] == mode/#css [+o Rossen] by Yves
[19:06] == petercon [~petercon@79c2f29d.public.cloak] has joined #css
[19:06] <argyle> present+
[19:06] <fantasai> chris: Main uncertainty is whether HSL is defined by pseudo-code or if the pseudo-code is informative
[19:07] <fantasai> chris: my interpretation is the latter
[19:07] <fantasai> chris: We did have a bug report that the JS in the examples was wrong, so fixed that
[19:07] <fantasai> chris: and I added the JS from Color 4 to Color 3
[19:07] * Rossen_ ... now I know my ABCs, next time...
[19:07] <fantasai> chris: My assertion is that everyone knows what HSL is, and defined by a paper (which is paywalled, but still)
[19:07] <fantasai> chris: So my interpretation is the code is informative
[19:08] <fantasai> chris: if we can agree as a group that all of those changes are not substantive, we can just republish the thing
[19:08] <fantasai> chris: otherwise have to do full AC review
[19:08] <dbaron> I vaguely remember having to regenerate a color table in the color spec at some point in the past...
[19:08] <fantasai> fantasai: All the things I noticed when reviewing was editorial changes, so just republish
[19:08] <dbaron> Publishing sounds fine to me too.
[19:08] <fantasai> Rossen_: any other opinions?
[19:09] <fantasai> RESOLVED: Republish CSS Color 3 REC as editorial update
</details>

**Comment by svgeesus** [comment]
Publication requested Weds 12 Jan expected Tues 18 Jan

**Comment by svgeesus** [comment]
[Published 18 Jan 2022](https://www.w3.org/TR/2022/REC-css-color-3-20220118/)
