### ISSUE TITLE
[css-color] Consider allowing commas in hwb()

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#6911]
Is there any strong reason not to support it? It'd be consistent with all other colors including `hsl(a)`.

Even if we prefer the comma-less syntax, in practice `hwb()` gets serialized as `rgb(a)()` with commas, and comma syntax is not really going anywhere.

Anyways happy to wontfix this but we almost accidentally ship this because we reused the hsl parser for hwb.

**Comment by svgeesus** [comment]
@tabatkins can explain the desire to move to a commaless syntax better than I can.

I agree that given the maximally-compatible (comma)  serialization form, this can be confusing to authors.

**Comment by SebastianZ** [comment]
If we decide to allow commas in `hwb()`, it should also be allowed in all other new color functions like `lch()`, `lab()`, etc. to be consistent.

Sebastian

**Comment by weinig** [comment]
I'd rather not add this. It would add additional complexity in our parser with no backwards compatibility reason.

**Comment by svgeesus** [comment]
I would prefer not to add commas where they have never historically had them. CSS Color 4 tries had to minimize exposure to the legacy syntaxes, relegating them to "for historical reasons these syntaxes are also supported".

Although serialization does the opposite, for Web compat mostly.

**Comment by devongovett** [comment]
Oops, that's my fault! Sorry @emilio, I totally missed that. Perhaps if this isn't changed, there should be a note in the spec to highlight the difference between hwb and other RGB-based color syntaxes.

**Comment by svgeesus** [comment]
> there should be a note in the spec to highlight the difference between hwb and other RGB-based color syntaxes.

Agreed, here it is:

> 	There is no legacy with ''hwb'', and so
	''hwb()'' does <em>not</em> support an alternate syntax
	that separates all of its arguments with commas.
	Using commas inside ''hwb()'' is an error.

**Comment by svgeesus** [comment]
Close?

**Comment by SebastianZ** [comment]
As I wrote earlier, the same applies to all other new color functions like `lch()`, `lab()`, `oklch()`, `oklab()`, `color()`, and all future functions. So there should be a general note for all of them or one for each function.

Sebastian

**Comment by emilio** [comment]
Yeah, I'm ok wontfixing this fwiw.

**Comment by svgeesus** [comment]
The term `legacy color syntax` is now defined, and each syntactic form either describes its legacy syntaxes, or explicitly states that it doesn't have one and that attempting to use it is an error.
