### ISSUE TITLE
[css-fonts-4] Wide gamut `@font-palette-values` entries and platform limitations

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6916]
https://drafts.csswg.org/css-fonts/#font-family-2-desc

says:

Value: | <'font-family'>
-- | --

linking to

https://drafts.csswg.org/css-fonts/#propdef-font-family

which is:

Value: | [ `<family-name>` \| `<generic-family>` ]#
-- | --

which makes it look like

1) the `font-family` descriptor in `@font-palette-values` should be able to assume a comma-separated list of family names as a value, which I don't think is the case.

2) generic family names are allowed here, which is also not the case according to the prose in 9.2.1.

I suggest to use a different, new value type definition to fix this.

CC @svgeesus @litherum

**Comment by drott** [comment]
Or perhaps by splitting out the separate value definitions / parsing rules for `family-name` and `generic-family` and using only family name here.

**Comment by jfkthame** [comment]
See also #7308, where I also stumbled across this section.

**Comment by jfkthame** [comment]
While my [previous comment](https://github.com/w3c/csswg-drafts/issues/6916#issuecomment-1190556132) is not actually relevant, as I had misread the example, I do think that the `font-family` descriptor in `@font-palette-values` *should* be allowed to take a list of family names.

In most cases, font palette overrides will be targeted at one specific font, but I don't think it's much of a stretch to imagine a suite of decorative fonts designed to work together and with coordinated palettes, in which case it could well make sense to apply the same color overrides to several families.

The somewhat analogous [`@font-feature-values` at-rule](https://drafts.csswg.org/css-fonts/#font-feature-values-syntax) is quite explicit that it *does* accept a list of family names (and the syntax and the prose agree on this!).

I notice that the current `@font-palette-values` implementations in Webkit and Blink do *not* accept a list, only a singular family name. @drott @litherum Would you be open to updating this to accept a list, if the WG agrees to resolve the current ambiguity in that direction?

**Comment by svgeesus** [comment]
The first part of the prose for that descriptor reads like a single family is used, while the second part of the same text explicitly says a list (my emphasis)

> This descriptor defines **the font family name** that this palette applies to. This palette will only ever be applied to **the font** with this name. The value of this descriptor matches the definition of the [<family-name>](https://drafts.csswg.org/css-fonts/#family-name-value) for the [font-family](https://drafts.csswg.org/css-fonts/#propdef-font-family) property. 

> This means that **only named font families** are allowed and rules that including generic or installed fonts in **the list of font families** are syntax errors. If syntax errors occur within **the font family list**, the entire rule must be ignored.

**Comment by svgeesus** [comment]
The spec seems clear that names of installed font families are not allowed:

> rules that including generic or installed fonts in the list of font families are syntax errors

What text were you reading that indicated they were allowed?

**Comment by jfkthame** [comment]
Isn't that implied by "The value of this descriptor matches the definition of the for the [font-family](https://drafts.csswg.org/css-fonts/#propdef-font-family) property"?

**Comment by jfkthame** [comment]
I agree with excluding generic families, incidentally -- which means that "matches the definition of the for the [font-family](https://drafts.csswg.org/css-fonts/#propdef-font-family) property" is not an accurate way to describe the value of this descriptor.

Further, I'm surprised the text says "If syntax errors occur within the font family list, the entire rule must be ignored". Wouldn't it be more normal to ignore the **descriptor** where the error occurs, not the **entire rule**? That seems to be what both Safari and Chrome are doing.

**Comment by svgeesus** [comment]
Aha, okay. Yes that needs to be changed to a new production which is syntactically similar but adds the "no generic font families" restriction.

> Wouldn't it be more normal to ignore the descriptor where the error occurs, 

It would, but (unless there is a later, duplicate, valid) font-family descriptor then the at-rule doesn't apply to anything.

**Comment by jfkthame** [comment]
> It would, but (unless there is a later, duplicate, valid) font-family descriptor then the at-rule doesn't apply to anything.

True; but as currently written, a font-family descriptor with a syntax error (such as a generic name) would cause the entire rule to be dropped, *even if* there's a subsequent, valid font-family descriptor. (Which is not how any existing implementation behaves, AFAICT.)

What about a rule with no font-family descriptor at all? The text currently says:

> [@font-palette-values](https://drafts.csswg.org/css-fonts/#at-ruledef-font-palette-values) rules require a [font-family](https://drafts.csswg.org/css-fonts/#descdef-font-palette-values-font-family) descriptor; if it is missing, the @font-palette-values rule is invalid and must be ignored entirely.

Does this mean that the rule should be dropped at parse time, and not appear in the OM, or it it simply telling us that the rule will not apply to anything and therefore "must be ignored entirely"?

(Existing implementations appear to accept a rule that lacks font-family, and https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/parsing/font-palette-values-valid.html thinks they're valid even though they're pointless. Is that the intention, or are the implementations and the testcase incorrect?)

**Comment by jfkthame** [comment]
Another reason *not* to treat installed font-family names as a syntax error is that this provides a convenient fingerprinting method to probe for what fonts are installed on the user's system.

And another reason is that although a given family name might not have been defined by @font-face *at the time the @font-palette-values rule is parsed*, it might be defined by a later at-rule. Such a name should not be a syntax error here.

**Comment by svgeesus** [comment]
Both  good reasons!

**Comment by svgeesus** [comment]
> Does this mean that the rule should be dropped at parse time, and not appear in the OM, or it it simply telling us that the rule will not apply to anything and therefore "must be ignored entirely"?

I think it means that it won't apply to anything. It will still be in the OM. That text should be clarified.

**Comment by svgeesus** [comment]
OK so here we go:

```html
<h4 id="font-family-2-desc">
Font family: the 'font-family!!descriptor' descriptor</h4>

    <pre class='descdef'>
    Name: font-family
	Value: <<family-name>>#
    For: @font-palette-values
    Initial: N/A
    </pre>

    This descriptor defines the font families that this palette applies to.
    This palette will only ever be applied to the fonts with these family names.
    The value of this descriptor  means that only named font families are allowed
    and rules that including generic fonts in the list of font families
    are syntax errors.
    If syntax errors occur within the font family list, the descriptor must be ignored.
```

So the changes are:

1. Disallow generics in the list
2. Pluralize in the first two sentences, to make clear it is a list and remove the conflict with the next two
3. Stop claiming it is the same as the `font-family` descriptor in `@font-face`
4. Errors result in the descriptor, not the entire rule, being ignored

**Comment by drott** [comment]
>  This palette will only ever be applied to the fonts with these family names.

Not sure if we need to say this, but would it be beneficial if we say that family names listed here should be matched against `@font-face's font-family` defined font families, not for example font family names found in the `name` OT table inside the font?

**Comment by svgeesus** [comment]
We do need to, absolutely.

A problem is that the phrase "CSS font family name matching" is used exactly once (in 4.2. Font family: the font-family descriptor) and not defined anywhere. And apart from 5.1. Localized name matching, 5. Font Matching Algorithm doesn't say much about the list of font families.

**Comment by svgeesus** [comment]
> One copy-editing nit: s/rules that including/rules that include/

Cheers, [fixed](https://github.com/w3c/csswg-drafts/commit/748cb3e2015f6ac87e321e895eb2abe2a3df7f1e)

**Comment by svgeesus** [comment]
@drott @jfkthame is this all done now?

**Comment by jfkthame** [comment]
Looking much better, thanks! I'll try to re-read it once the drafts server is happy again....

One other editorial nit, while you're here: in one of the examples, there's this:
```
			@font-palette-values --ToxicGreen {
			  font-family: Bungeehee;
			  base-palette: 7; /* This is Bungeehee's green palette... */
			  2: lime; /* ...except this is pink, which I overwrite to lime */
			}
```
which is not using the proper override-colors syntax. (I'm guessing it is left over from an earlier draft syntax.)

**Comment by astearns** [comment]
> I'll try to re-read it once the drafts server is happy again....

FWIW @jfkthame, there is an alternative up now at https://w3c.github.io/csswg-drafts/css-fonts-4/

**Comment by svgeesus** [comment]
> not using the proper override-colors syntax.

Cheers, fixed.

**Comment by jfkthame** [comment]
Thanks. A further question: I'm a bit puzzled by the phrasing at https://w3c.github.io/csswg-drafts/css-fonts-4/#override-color where it says:

> Colors provided from CSS (as overrides, or as new entries) may use any supported colorspace.

What does it mean by "as new entries" here? My understanding is that the *only* thing the `override-colors` descriptor can do is to override entries from the base palette; it can't create "new entries". (And if it could, what would be the point, as no glyph description would refer to them?)

**Comment by jfkthame** [comment]
Also puzzled by this (from the same section):

> If the keys of multiple distinct key/value pairs identify the same color index (either by name or by integer), the last key is used for the purposes of rendering.

Specifically, the "by name" option for specifying a color index doesn't exist anywhere in the rest of the spec, AFAICS. The only way for `override-colors` to reference a color index in the palette is by integer. Is this a leftover of an earlier draft that allowed for named palette entries?

**Comment by svgeesus** [comment]
It looks like a leftover at first glance, but I need to did a bit to see where it came from.

**Comment by svgeesus** [comment]
> What does it mean by "as new entries" here? My understanding is that the only thing the override-colors descriptor can do is to override entries from the base palette; it can't create "new entries". (And if it could, what would be the point, as no glyph description would refer to them?)

Exactly. They are all overrides, whether on an existing palette or a new palette. new palettes can be created; new (unused) entries are pointless, as you said.

The main point being made here is that PLTE v0 and v1 are restricted to sRGB only, while the CSS override colors are not.

I will dig a bit in case sometihng else was meant, then reword to that effect.

**Comment by drott** [comment]
I agree "any supported color-space" would be ideal in the long run, but I don't think that's something we can currently implement in Chrome. COLRv0 and COLRv1 rendering to my knowledge is limited to sRGB currently. I am not sure what happens if wider colors are specified as overrides - that would depend on what our CSS Color class returns when it is asked for RGB color values for a differently-specified color.

**Comment by svgeesus** [comment]
> hat would depend on what our CSS Color class returns when it is asked for RGB color values for a differently-specified color.

It would be useful indeed to know what it does, currently.

@litherum what does Safari do (since Safari implements both wide gamut CSS colors and also `override-color` and COLRv0 fonts)?

**Comment by cdoublev** [comment]
I ask the following question here since the following text is the result of https://github.com/w3c/csswg-drafts/issues/6916#issuecomment-1240684141 above, but please let me know if you prefer that I open a separate one.

  > If syntax errors occur within the font family list, the descriptor must be ignored (will still be in the CSS OM, but will not match any font families).

Can you please clarify what *"the descriptor must be ignored"* means?

For this CSS:

```css
@font-palette-values --palette {
  font-family: serif;
}
```

`CSSFontPaletteValues.fontFamily` serializes to empty string in FF and to the specified value between quotes in Chrome (probably a bug).

I would expect it to serialize as specified.

**Comment by drott** [comment]
@cdoublev  `serif` is a generic font name and thus causes a syntax error, which means the UA should ignore this descriptor - which in turns means, treat the `@font-palette-values` at-rule as if `font-family` was not specified. So it would not be applied to any font. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1433586 for Chrome, as we do accept `serif`, which is wrong [according to the edited spec text](https://drafts.csswg.org/css-fonts-4/#font-family-2-desc:~:text=rules%20that%20include%20generic%20fonts%20in%20the%20list%20of%20font%20families%20are%20syntax%20errors).

**Comment by cdoublev** [comment]
> treat the `@font-palette-values` at-rule as if `font-family` was not specified

Ok, thanks. So `CSSFontPaletteValues.cssText` serializes to `@font-palette-values { }` (like in FF) and does not round trip (it would be ignored on a consecutive parse), which I think is probably ok here.

**Comment by svgeesus** [comment]
@drott wrote

> I agree "any supported color-space" would be ideal in the long run, but I don't think that's something we can currently implement in Chrome. COLRv0 and COLRv1 rendering to my knowledge is limited to sRGB currently. I am not sure what happens if wider colors are specified as overrides - that would depend on what our CSS Color class returns when it is asked for RGB color values for a differently-specified color.

Do we have any updated info on this meanwhile?

**Comment by drott** [comment]
> Do we have any updated info on this meanwhile?

If you're asking for specifics of our implementation, [at the lowest level](https://source.chromium.org/chromium/chromium/src/+/main:third_party/skia/include/core/SkFontArguments.h;drc=8c0874163bb6f015d7b326c154db9307d53ca8c3;l=34) when passing to Skia for drawing we store the CSS palette in an `SkColor` type which is an 8888 integer discrete color representation not color-space aware and usually interpreted as sRGB when used. (@bungeman may correct me here). So - we don't allow wide-gamut overrides.

**Comment by svgeesus** [comment]
Renamed the issue to describe the one remaining problem.
