### ISSUE TITLE
[css-color-5] Clarify if relative forms of `rgb()` and `hsl()` only work with the space separated syntax / shortened name form

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6921]
In the relative color syntax additions for [`rgb()`](https://drafts.csswg.org/css-color-5/#relative-RGB) and [`hsl()`](https://drafts.csswg.org/css-color-5/#relative-HSL) the grammar only shows the space separated syntax, but I think it would be good to explicitly state that it is the only form that works with a from clause, and that the legacy is not supported.

Similarly, it would probably be good to be explicit about whether the alternative naming, `rgba()` and `hsla()`, work with the new form.

**Comment by svgeesus** [comment]
Good points I agree this should be explicitly stated.

**Comment by LeaVerou** [comment]
Yeah, RCS should only work with the new syntax, unless it's easier for UAs to implement if it works with both, which I doubt.

**Comment by weinig** [comment]
It was easier to only work with the newer syntax for me, and it looked like that is what the grammar was implying, so that is what is implemented in WebKit.

**Comment by svgeesus** [comment]
> * Relative color syntax only applies to the modern 
	(space separated components, / separator for alpha) syntax.
	It cannot be used with <a>legacy color syntax</a>
	and attempting to do so is an error.

**Comment by svgeesus** [comment]
(That note is added on to "they all follow a common structure" so applies to all RCS syntactic forms)
