### ISSUE TITLE
[cssom][selectors] Define or fix `selectors_group`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6927]
In [CSSOM](https://drafts.csswg.org/cssom/#parsing-selectors):

> ## 5.1. Parsing Selectors
>
> To **parse a group of selectors** means to parse the value using the `selectors_group` production defined in the Selectors specification and return either a group of selectors if parsing did not fail or null if parsing did fail.

I can not find `selectors_group` in Selectors. Does it correspond to `<selector-list>`? When does [**parse a selector**](https://drafts.csswg.org/selectors/#parse-selector) should be used?

**EDIT:** 

I think it should use [**parse a selector**](https://drafts.csswg.org/selectors/#parse-selector), as well as the definition for parsing the prelude of a [style rule in Syntax](https://drafts.csswg.org/css-syntax-3/#style-rules), which is currently:

> The prelude of the qualified rule is [parsed](https://drafts.csswg.org/css-syntax-3/#css-parse-something-according-to-a-css-grammar) as a [`<selector-list>`](https://drafts.csswg.org/selectors-4/#typedef-selector-list). If this returns failure, the entire style rule is [invalid](https://drafts.csswg.org/css-syntax-3/#css-invalid).*

And it should be completed with a validation for nest-containing selector for `@nest`, as explained in my comment below.

**Comment by cdoublev** [comment]
Partially related: neither *parse a group of selectors* and its underlying procedures nor the procedure to set `CSSStyleRule.selectorText` when it represents a **nested** style rule, seems to handle a selector starting with `&`, which I think should be required for a nested style rule's selector to be valid.

**Comment by tabatkins** [comment]
Yeah, that bit of spec is *way* out-of-date; it's still referring to the old Selectors 3 grammar based on the CSS 2.1 Appendix G grammars. :/

**Comment by cdoublev** [comment]
Closing as duplicate of #1511. The specific part related to parsing `@nest` selector is no longer valid.
