### ISSUE TITLE
[selectors] A pseudo-element should start with `::` at its start

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6928]
https://drafts.csswg.org/selectors/#grammar

> `<pseudo-element-selector> = ':' <pseudo-class-selector>`
>
> [...]
> 
> The four Level 2 pseudo-elements (`::before`, `::after`, `::first-line`, and `::first-letter`) may, for legacy reasons, be represented using the `<pseudo-class-selector>` grammar, with only a single ":" character at their start.

I think it should be:

> `<pseudo-element-selector> = ':'{1,2} <pseudo-class-selector>`

Or:

> `<pseudo-element-selector> = '::' <pseudo-class-selector>`
>
> [...]
>
> The four Level 2 pseudo-elements (`::before`, `::after`, `::first-line`, and `::first-letter`) may, for legacy reasons, be represented using the `<pseudo-class-selector>` grammar, with only a single ":" character at their start.

**Comment by dlibby-** [comment]
`<pseudo-class-selector>` is
```
<pseudo-class-selector> = ':' <ident-token> |
                          ':' <function-token> <any-value> ')'
```

which contains the first `:`. So I the spec already represents your second proposal.
