### ISSUE TITLE
[css-animations-2] should `animation-composition` be taken into account when merging keyframes?

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#6935]
The [Keyframes section](https://drafts.csswg.org/css-animations-2/#keyframes) of the [CSS Animations Level 2 spec](https://drafts.csswg.org/css-animations-2/) discusses how `animation-timing-function` applied to individual keyframes should be account for along with the offset to merge keyframes with similar offset and easing.

Should `animation-composition` also be accounted for here such that only keyframes with the same offset, canonical timing function _and_ composite operation be merged?

**Comment by graouts** [comment]
I have WPT coverage in progress in https://github.com/graouts/wpt/commit/3343e4f7b3645cf04c72c5c43cf261a5d6e69801 if anyone is curious as to what this would look like in practice.

**Comment by birtles** [comment]
> Should `animation-composition` also be accounted for here such that only keyframes with the same offset, canonical timing function _and_ composite operation be merged?

I think that makes sense.
