### ISSUE TITLE
[css-images] Require dithering in gradients

### ISSUE THREAD

**Issue by muster-mark** [w3c/csswg-drafts#6947]
Since this bug was fixed (https://github.com/w3c/csswg-drafts/issues/4793) dithering has been allowed in gradients.

However in many cases, gradients are essentially unusable without dithering (if you consider their purpose to create a pleasing aesthetic) since it can cause unsightly banding which does precisely the opposite. This is a huge issue in Firefox, which does not apply dithering despite a bug being open for 11 years.

Is there any reason why the specification shouldn't/couldn't *require* dithering. Care would be needed to define this appropriately, since gradient functions can be used which don't actually create a gradient, and dithering would be undesirable there.

At the very least, could the spec indicate that dithering is a SHOULD rather than a MAY. e.g. something along the lines of "User agents SHOULD employ dithering where necessary to avoid banding effects."

**Comment by smfr** [comment]
Gradient rendering seems like a "quality of implementation" issue. I don't think the spec should have an opinion on dithering (and doing so may be hard for implementations that rely on underlying graphics libraries to render gradients).

**Comment by tabatkins** [comment]
Yup, 100% what @smfr says. This is entirely a quality-of-implementation issue. Gradient rendering is usually deferred to the underlying graphics library, so putting a strict requirement there would make impl on some systems unnecessarily difficult, when non-dithered gradients are still *okay*.

(Also, testing for *allowed* dithering is already tricky; testing for *required* dithering seems impossible except in extreme cases.)

**Comment by muster-mark** [comment]
OK fair enough then, will close this.
