### ISSUE TITLE
[css-transforms-1] Should will-change: transform be treated as transform for background-attachment:fixed?

### ISSUE THREAD

**Issue by wangxianzhu** [w3c/csswg-drafts#6951]
The [current spec](https://www.w3.org/TR/css-transforms-1/#transform-rendering) says:

> Fixed backgrounds on the root element are affected by any transform specified for that element. For all other elements that are effected by a transform (i.e. have a transform applied to them, or to any of their ancestor elements), a value of fixed for the background-attachment property is treated as if it had a value of scroll. The computed value of background-attachment is not affected.

It doesn't mention will-change:transform. However, if we don't treat will-change:transform as transform, future change of transform from initial to non-identity will cause jump of the background.

Current browser behaviors about treating will-change:transform as transform for background-attachment-fixed:
- Firefox: Yes
- Chrome: No, but it will be Yes after https://chromium-review.googlesource.com/c/chromium/src/+/3385337 is landed.
- Safari: No

**Comment by SelenIT** [comment]
I believe that [this paragraph](https://drafts.csswg.org/css-will-change/#ref-for-propdef-will-change%E2%91%A2%E2%91%A0) from [css-will-change] applies here:

> If any non-initial value of a property would _cause rendering differences_ on the element (...), the user agent should use that alternate rendering when the property is specified in `will-change`

(given that [css-transforms] [explicitly states](https://drafts.csswg.org/css-transforms/#module-interactions) that "Transforms _affect the rendering_ of backgrounds on elements with a value of `fixed` for the `background-attachment` property"). So the current behavior of Firefox and planned behavior of Chrome are correct.

**Comment by wangxianzhu** [comment]
I think SelenIT's explanation makes sense. Closing this issue.
