### ISSUE TITLE
[css-syntax-3] Fix outdated example featuring nested media queries

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#6958]
At the very bottom of section [8.1. Defining Block Contents: the `<declaration-list>`, `<rule-list>`, and `<stylesheet>` productions](https://drafts.csswg.org/css-syntax/#declaration-rule-list), I understand from Example 15 that nested media queries are invalid:

> For example, the `@media` rule accepts anything that can be placed in a stylesheet, except more `@media` rules. As such, its grammar is:
>
> `@media <media-query-list> { <stylesheet> }`
>
> It additionally defines a restriction that the `<stylesheet>` can not contain `@media` rules, which causes them to be dropped from the outer rule’s value if they appear.

I may be confused because both sentences mean the same thing to me.

**Comment by tabatkins** [comment]
Correct, the last paragraph is saying that the @media spec places that restriction on the `<stylesheet>` production, which matches the intended behavior listed in the first paragraph.

**Comment by cdoublev** [comment]
But [Conditional](https://drafts.csswg.org/css-conditional-3/#contents-of) defines that nested `@media` are allowed, isn't it?


> #### Example 2
>
> For example, with this set of nested rules:
> ```
> @media print { /* rule (1) */
>   /* hide navigation controls when printing */
>   #navigation { display: none }
>   @media (max-width: 12cm) { /* rule (2) */
>   /* keep notes in flow when printing to narrow pages */
>     .note { float: none }
>   }
> }
> ```
> [...]
>
> ### 3. Contents of conditional group rules
>
> All conditional group rules are defined to take a <stylesheet> in their block, which means they can accept any rule that is normally allowed at the top-level of a stylesheet, and not otherwise restricted.

**Comment by cdoublev** [comment]
Removed in https://github.com/w3c/csswg-drafts/commit/c7ce04119575f469b10c1edb2e30b3bb3236e37e.
