### ISSUE TITLE
[css-color-5] The relative form of of the `rgb()` function should allow `none` as the alpha component

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#6960]
All other the relative color functions allow the alpha component to be specified `/ [<alpha-value> | none] ]?` except the [relative `rgb()` function](https://drafts.csswg.org/css-color-5/#funcdef-rgb) which is currently specified as `[ / <alpha-value> ]?`.

I am guessing this is just a mistake, but if it is intentional, it would be good to call it out in prose as well.

**Comment by svgeesus** [comment]
Thanks! Yes, a mistake.
