### ISSUE TITLE
[mediaqueries-3] Update REC

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6962]
As suggested in https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-1011313466, we should republish MQ3. It used to be generated by the preprocessor we used to use before bikeshed, but that hadn't been run in years on that spec, and some of the edits has been made to the source, some to the output, so I've manually updated the .html file, and stopped using the .src.html.

I have now:
* synced up all the edits that had been done only to .src.html, and applied them to the .html
* discarded the .src.html, since nobody was generating from it and is was just a trap attracting edits into what was effectively /dev/null (and for the reason mentioned by @svgeesus in https://github.com/w3c/csswg-drafts/issues/6900#issuecomment-1012599035)
* Applied all the editorial changes that had been stashed in the [errata](https://www.w3.org/Style/2012/REC-mediaqueries-20120619-errata.html)
  * We may want to debate whether the [case insensitivity change of section 3](https://drafts.csswg.org/mediaqueries-3/#changes-2012) really is editorial, or should be turned into an candidate correction. I think it's editorial because it's merely observing that css, including mediaqueries, is ASCII case insensitive, and not prescribing it.
* Applied, as a [candidate correction](https://www.w3.org/2021/Process-20211102/#candidate-correction) one of the two [normative errata](https://drafts.csswg.org/mediaqueries-3/#c1), but not the other, since it had been overturned by a [2015 resolution](https://lists.w3.org/Archives/Public/www-style/2015Aug/0051.html) (which has already made its way into MQ4 & 5, and is consistent with implementations)
* Updated the bibliography
* Written an updated change section
* Fixed up the markup and styling

So I think we're ready.

We may also want to consider whether we want to elevate the candidate correction to a proposed correction. I think we should, it's been stable for years, and has tests that are passed by all browsers, so there's no reason to hold back.

Either way, we should republish, and a WG resolution is enough for that. This issue is to ask for it.

**Comment by svgeesus** [comment]
> I think it's editorial because it's merely observing that css, including mediaqueries, is ASCII case insensitive, and not prescribing it.

I agree and also, so does CSSWG when the exact same issue was considered editorial for republishing CSS Color 3, which was published today.

**Comment by svgeesus** [comment]
There is a normative reference from Conditional 3 to Conditional 5, for the definition of `supports()`, although [7.5. The CSS namespace, and the supports() function](https://drafts.csswg.org/css-conditional-3/#the-css-namespace) seems to only reference conditional-3 for `supports()` so I am not sure where that is coming from.

**Comment by frivoal** [comment]
> There is a normative reference from Conditional 3 to Conditional 5

@svgeesus Does that have something to do with MQ3, or did you mean to post that in some other issue?

**Comment by svgeesus** [comment]
Guide has [now been updated](https://www.w3.org/Guide/transitions?profile=REC&rec=proposed-corrections) on how to do this.

**Comment by svgeesus** [comment]
Although publication and checker services [are having issues today](https://status.w3.org/)

**Comment by svgeesus** [comment]
Taking a bit longer to squeeze this one through pubrules than usual, so missed the deadline for Tues 08 Mar publication. Now aiming for Thu 10th.

@frivoal Should this spec continue to use the old-style shortname `css3-mediaqueries` or should it be updated to `mediaqueries-3` for consistency with `mediaqueries-4` and `mediaqueries-5`?

**Comment by svgeesus** [comment]
@frivoal ?

**Comment by tabatkins** [comment]
Ah, please match up with `mediaqueries-3`

**Comment by svgeesus** [comment]
That was what I thought, but the current ED does not so I wanted to check first.

**Comment by svgeesus** [comment]
Publication request sent 31 April, publication expected 5 May 2022

**Comment by frivoal** [comment]
@svgeesus Sorry I missed the question. Yes, I agree with what you did on that. Thanks for handling this more-annoying-than-usual publication.

By the way, I just noticed the document links to a (for now empty) separate errata page. That's the historical practice, but [as of Process 2021](https://www.w3.org/2021/Process-20211102/#errata), that's no longer the only option:

> Errata may be documented in a separate errata page or tracking system. They may, in addition or alternatively, be annotated inline alongside the affected technical report text or at the start or end of the most relevant section(s).

I don't believe we've made a decision either way since this became an option, but maybe we should consider switching to inline-only errata? Separate documents can easily go out of sync, and are typically not looked at much.

**Comment by svgeesus** [comment]
> By the way, I just noticed the document links to a (for now empty) separate errata page. That's the historical practice, but [as of Process 2021](https://www.w3.org/2021/Process-20211102/#errata), that's no longer the only option:

I agree that adding a separate blank errata document is pointless and stupid. But pubrules checker still complains if it is not there, so in the interests of not further delaying publication while arguing that the checker should be changed, I did the pointless and stupid thing.

**Comment by svgeesus** [comment]
> Thanks for handling this more-annoying-than-usual publication.

Sorry it took a while. Just [a few edits](https://github.com/w3c/csswg-drafts/commit/fc8a37659b8973a87f8ee7ee74cba42b5d99944c) to get it to be accepted.

[Published 5 April 2022](https://www.w3.org/TR/2022/REC-mediaqueries-3-20220405/) with [orrect history despite shortname change](https://www.w3.org/standards/history/mediaqueries-3)
