### ISSUE TITLE
[css-text-decor-4] Disallow negative spread values on text-shadow

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#6971]
[This thread](http://lists.w3.org/Archives/Public/www-style/2012Jan/0991.html) describes some difficulties in implementing `spread` on `text-shadow`. The gist is that `spread` on `box-shadow` can be implemented via changing rectangle sizes and adjusting corner radii, but `spread` on `text-shadow` would have to be implemented by shadowing the text rendered with an enlarged stroke, which could lead to unexpected shadowing of parts of glyphs in some fonts (I saw issues with Zapfino).

In addition, the stroke-enlarging implementation doesn't allow for negative spread, so I suggest we disallow negative spread on `text-shadow`.

**Comment by smfr** [comment]
Then the question is "parse as invalid" or "clamp to 0". I suggest "clamp to 0".

**Comment by LeaVerou** [comment]
If we clamp to 0, we can never change that behavior, nor can it be tested via `@supports`. What's the argument *for* clamping to 0?

**Comment by smfr** [comment]
Less surprising than parsing as invalid (esp if you copy a value from `box-shadow`) but I don't feel strongly.

**Comment by tabatkins** [comment]
I'm in favor of making it a non-negative range, for the reasons Lea gives. Negative numbers should be invalid if they aren't going to do anything, rather than being silently clamped to a different behavior.

**Comment by bradkemper** [comment]
Couldn't you stroke the alpha channel with a white stroke to create the choke?

Or could you use an erode filter on it?

**Comment by bradkemper** [comment]
Also, Wow! That thread is 10 years old. I'm happy we are returning to this. 

Are you also looking at supporting the `inset` keyword in text-shadow?

**Comment by SebastianZ** [comment]
> Are you also looking at supporting the `inset` keyword in text-shadow?

Just for reference, adding `inset` to the spec. is discussed in #6074.

Sebastian

**Comment by LeaVerou** [comment]
> Also, Wow! That thread is 10 years old. I'm happy we are returning to this.

WAT? The first post was started 16 hours ago…
