### ISSUE TITLE
[css-syntax-level-3] Why is there no definition here on how to parsing pseudo-classes?

### ISSUE THREAD

**Issue by HcySunYang** [w3c/csswg-drafts#6973]
As the title states, I didn't find any tokenization or parsing rules for pseudo-classes in the https://www.w3.org/TR/css-syntax-3/. Can you guys give me some pointers? or some links, or other specs. Thanks. 🙏🏻

**Comment by tabatkins** [comment]
Those aren't generic syntax; they're selectors, and thus defined in the [Selectors spec](https://drafts.csswg.org/selectors/#grammar)

**Comment by HcySunYang** [comment]
@tabatkins Get it, thank you~
