### ISSUE TITLE
Provide a way to pass theming colors (and potentially other info) into SVG images, via e.g. Tab's SVG Parameters spec

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#6988]
@tabatkins has a "SVG Parameters" spec proposal https://tabatkins.github.io/specs/svg-params/ that I'd like to see turned into an official draft, probably under the purview of the CSSWG (since it'd be a way to make information available via CSS).

Here's the elevator pitch, copypasted from the Introduction section of the spec proposal:
> SVG is stylable with CSS, and when used inline in HTML, this capability can be very useful. For example, an SVG icon can take on a different color based on whether the user is hovering it or not, just by appling a :hover rule to it that changes the fill property.
> 
> When the SVG is referenced in a way that doesn’t allow selectors or CSS inheritance from the outer page to apply to it (such as embedding it via img or iframe in HTML), though, this functionality is lost. The only way to change the display of such "external" SVG images is to produce several of them, and change which image you’re referencing. This incurs delay on the page as a new resource is downloaded, and disallows dynamic effects like CSS Transitions.
> 
> SVG Parameters are a way to set CSS custom properties on an "external" SVG image, by passing them through a special fragment scheme on the URL. This gives a limited, but powerful, subset of the customizability that "inline" SVG images have to "external" SVG images.

Mozilla is interested in implementing this feature in Firefox, once there's a CSS spec that's got consensus and seems ready for shipping.  Our primary use-case is to allow our toolbar icons (for add-ons as well as the standard back/forward/home/etc.) to use web standards to style themselves in accordance with the user's chosen browser-theme, beyond just "is it dark or light".  We think there are good uses for this feature on the web in general, too -- anywhere where a web developer might have some SVG assets that are referenced as images (e.g. `<img>` or CSS backgrounds) and where theming/coloring may want to be customized or may evolve over time, this sort of feature might be a good way to set and customize those colors.

Note: one of the core principles of this approach is that it needs to have opt-in from both sides (the outer document as well as the SVG image) in order to avoid data-leakage & unexpected side effects. The spec accomplishes this by: (1) baking the parameter-values into the image URL itself (as part of the fragment identifier or the CSS `url()` function), and by (2) having the image explicitly use the passed-in values (if it cares about them) using an explicit & newly-defined `param()` syntax.

I'm filing this issue to get the conversation started, and hopefully to gain consensus around this being a useful feature worth-speccing, and to find either an existing spec or create a new spec for this to live in. (Note that there's already draft text, in Tab's above-linked github.io space)

**Comment by dholbert** [comment]
(Eventually we should mark this `Agenda+` and we can discuss this feature in a telecon, but perhaps it's worth waiting a bit and gathering asynchronous feedback/thoughts here on github first.)

**Comment by SebastianZ** [comment]
Note that this wouldn't only be useful for SVGs (for which I am currently missing this feature _a lot_) but also HTMLs embedded in iframes. A potential use case for that is to pass theme colors from the embedding document.

Sebastian

**Comment by dholbert** [comment]
It's interesting to think about generalizing this to html and to iframes, however:
(1) you can already sort-of solve this for html and iframes by simply communicating via `postMessage` and JS.
(2) if we nonetheless were to generalize this feature to support html and iframes, then that would complicate or prevent the usage of the spec's current `#param()` syntax for encoding this information in the fragment identifier, since the fragment identifier might change if e.g. someone clicks an in-page link to scroll to an anchor further down in the iframe (and that's not great if that inadvertent in-page navigation causes a bunch of color-variables to be nerfed or changed).

**Comment by dholbert** [comment]
Put another way: I'm hesitant about scope-creep turning this proposal into a huge general-purpose scriptless technique for communicating arbitrary data from an outer context to an inner context (particularly in cases where this communication is already possible via other means).

I want to keep the focus on **making this possible (and ideally ergonomic) for SVG images** (where no such communication can be done at the moment).  Having said that: if the feature lends itself to gracefully support other usages like iframes without much additional complexity/edge-cases-that-need-considering, then that's fine; but consider me a bit skeptical. :)

**Comment by SebastianZ** [comment]
That's fair enough.

Sebastian

**Comment by dholbert** [comment]
For discussion purposes, here's some "prior art" in this neighborhood, i.e. other places where we've got SVG/icons that can be customized externally at the embedding site:

(1) Safari's "pinned tab icons", e.g. `<link rel="mask-icon" href="website_icon.svg" color="red">`
* It's one way to pass a custom color into an SVG icon.
* ...but in an extremely limited context (and via a non-standard mechanism).

(2) "icon fonts" that are monochrome & let you customize the icon colors just by literally setting CSS `color`.
* It's one way to define a reusable icon-set which can be arbitrarily colorized.
* ...but only supports customization of a single color (via CSS 'color') and requires you to package up your icons as a font.

(3) Inline-SVG icon toolkits, with `fill`/`stroke` being customizable at the embedding site.
* This gives us nearly the flexibility that we want...
* ...except that it uses inline SVG injected directly into the DOM.  So this can't be used as a background or as an `img` element, and it accordingly requires a bit more trust, and doesn't benefit as directly from SVG-image rasterization caching benefits ("surface cache" in Firefox).

(4) SVG image files, referenced as images, with a viewbox specified in the fragment identifier, e.g. `<img src="foo.svg#svgView(...)">`
* This is one way to do "SVG Sprites".  It doesn't directly address the use-cases discussed here, but it's an example of how you can already use fragment identifiers to make an SVG image render differently (with cooperation from the SVG, e.g. by placing different components/icons at different predefined locations in the coordinate space).
* This is similar but doesn't give us the flexibility that we're looking for here (passing in values like colors of the brand/theme).

(5) SVG images that render differently in dark mode, per #7213.
* This gives you one bit of information that the image can react to (i.e. it could have a dark version and a light version)
* ...but designers may need to enable more fine-grained customizability than that, and may want to e.g. vary the colors on hover, etc.

**Comment by dholbert** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1782815 on implementing this once we're ready to do so.
