### ISSUE TITLE
[cssom-1] Serialize `CSSKeyframesRule` name depending on its type

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7004]
To [serialize a CSSKeyframesRule](https://drafts.csswg.org/cssom/#serialize-a-css-rule), the name should be serialized as an identifer:

> 2. The serialization as an identifier of the name attribute.
> 3. The result of performing serialize a CSS rule on each rule in the rule’s cssRules list, separated by a newline and indented by two spaces.

But its production rule is `<keyframes-name> = <custom-ident> | <string>`.

```css
@keyframes "my Animation" {
  to { color: green }
}
```
```js
const { styleSheets: [{ cssRules: [{ cssText }] }] } = document
console.log(cssText)
```

Result in Chrome:

```
@-webkit-keyframes my Animation { 
  100% { color: green; }
}
```

Result in Firefox:

```
@keyframes "my Animation" {
100% { color: green; }
}
```

Firefox is missing the indentation but the important thing is that keyframes name is serialized as a string. But I feel like it should be serialized as a string, for round tripping (parsing `CSSKeyframesRule.cssText` should result to a valid `CSSKeyframesRule`.

Also, it is missing a step to concatenate a space and an open curly brace before step 3.

**Comment by Loirooriol** [comment]
> Firefox is missing the indentation

That's a mess, see #4828

> But I feel like it should be serialized as a string, for round tripping

I agree it should round-trip, but it could still be done with an identifier:

```css
@keyframes my\ Animation {
  to { color: green }
}
```

That's valid and is the serialization that you get from https://drafts.csswg.org/cssom/#serialize-an-identifier

**Comment by cdoublev** [comment]
Yes, I realized after creating this issue that the other procedures also have issues or can be optimized eg. by reading `cssText`, `conditionText`, etc... properties. I'm guilty of not (always) looking at the existing issues before creating a new one. I'm really sorry.

I understood from #4828 (thanks for referencing it to me) that the intent is to serialize everything on one line. I will follow this guideline, as well as this issue.
