### ISSUE TITLE
[css-fonts-4] absolute-color in override-colors unspecified

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#7010]
> 9.2.3. Overriding a colors from a palette: The [override-colors](https://www.w3.org/TR/css-fonts-4/#descdef-font-palette-values-override-colors) descriptor

says:

> Value: `| [<integer [0,∞]> <absolute-color> ]#`

But I can't find a reference for `absolute-color`. Has the color spec changed after this? I assume the intention is to allow `<<absolute-color-base>> | currentcolor` but not `| <<system-color>> | <<device-cmyk()>>`. 

CC @litherum @svgeesus 

_Edit:_ See below for clarifications re `currentcolor`.

**Comment by litherum** [comment]
Yes, IIRC the change that added that grammar also modified the color spec.

**Comment by svgeesus** [comment]
Bikeshed reports, on building CSS Fonts 4

> LINE ~6533: No 'type' refs found for `'<absolute-color>'`.
`<<absolute-color>>`

probably because CSS Color 4 has

```html
<pre class='prod'>
	&lt;color> = <<absolute-color-base>> | currentcolor | <<system-color>> | <<device-cmyk()>>

	<dfn>&lt;absolute-color-base></dfn> = <<hex-color>> | <<named-color>> | transparent |
	    <<rgb()>> | <<rgba()>> | <<hsl()>> | <<hsla()>> | <<hwb()>> |
	    <<lab()>> | <<lch()>> |
	    <<oklab()>> | <<oklch()>> |
	    <<color()>>
	</pre>
```

So, the fix is to change Fonts 4 to use the actual exported term :)

**Comment by svgeesus** [comment]
Oh I just noticed

> I assume the intention is to allow <<absolute-color-base>> | currentcolor

If that is correct, I need to make a different edit. Is currentColor to be included?

**Comment by litherum** [comment]
I intentionally omitted `currentColor` . https://github.com/w3c/csswg-drafts/commit/c790f28d628d45d8653eaa8d4dda6a9ef49b80c0 is the edit. You can see how `currentColor` was supposed to be part of the `<color>` production, not the `<absolute-color>` production.

**Comment by svgeesus** [comment]
Okay in that case, what we currently have is correct

**Comment by drott** [comment]
Thanks for fixing the reference.

> Okay in that case, what we currently have is correct

But if it was `<<absolute-color>>` before, and now we use ``<<absolute-color-base>>`, it means dropping `<<absolute-device-cmyk>>` - is that intended (I may have missed a continuation of the conversation in https://github.com/w3c/csswg-drafts/pull/6681#pullrequestreview-765664916.

**Comment by svgeesus** [comment]
Ah, I see. At the time of https://github.com/w3c/csswg-drafts/commit/c790f28d628d45d8653eaa8d4dda6a9ef49b80c0 `device-cmyk()` had a fallback color so it was necessary to split off an `<<absolute-device-cmyk>>` with no fallback.

So yes this needs a further edit to add back `device-cmyk`.

**Comment by svgeesus** [comment]
> The remaining question is whether to add the device-cmyk back, which I guess we should do.

@drott see

 - https://github.com/w3c/csswg-drafts/issues/9555
