### ISSUE TITLE
Clarify that there is no RCS for `rgba()` or `hsla()`

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7018]
@weinig [noted on wpt](https://github.com/web-platform-tests/wpt/pull/32711): 

> Testing that hsla(from ...) and rgba(from ...) are not valid in the relative color syntax (but rgb(from ...) and hsl(from ...) are). Would like confirmation that this is correct

Confirmed, see the grammar at [rgb(from](https://drafts.csswg.org/css-color-5/#relative-RGB) and [hsl(from](https://drafts.csswg.org/css-color-5/#relative-HSL). However, I will add examples with non-unity alpha just to make that clearer.

**Comment by triple-underscore** [comment]
The wording "rgba [legacy color syntax](https://drafts.csswg.org/css-color-4/#legacy-color-syntax)" in the newly added example seems misleading, since the legacy color syntax can be used with both "non-legacy RGB syntactic form" `rgb()` and "legacy RGB syntactic form" `rgba()`.

**Comment by svgeesus** [comment]
No, [legacy color syntax](https://drafts.csswg.org/css-color-4/#legacy-color-syntax) covers _three_ things, of which a separate function for alpha is only one.

**Comment by triple-underscore** [comment]
Ah, I reread the definition, and realized that I had misunderstood it, sorry.

**Comment by svgeesus** [comment]
No problem.
