### ISSUE TITLE
[css-fonts] explicitly specify that font-size-adjust should be either none or a non-negative number

### ISSUE THREAD

**Issue by chenpighead** [w3c/csswg-drafts#702]
According to https://drafts.csswg.org/css-fonts-3/#font-size-adjust-prop, font-size-adjust specifies the aspect value used in the calculation below to calculate the adjusted font size. Since it is an aspect value, maybe we could explicitly specify that font-size-adjust should be either none or a non-negative number.

**Comment by dbaron** [comment]
The spec [already says](https://drafts.csswg.org/css-fonts/#aspect-ratio-value):
> Negative values are invalid.

**Comment by chenpighead** [comment]
Oops. Sorry.

**Comment by AmeliaBR** [comment]
Related: https://github.com/w3c/csswg-drafts/issues/355

It would be really helpful if there was a way to describe non-negative restrictions in the value type declaration, instead of in prose.
