### ISSUE TITLE
[css-contain] Defer style queries to level 4?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#7020]
We are much farther along with the development of (and experimentation with) size-based container queries. I want to make sure we have a plan from the start for how additional container/query types (like style queries) will be handled in the top-level syntax, but we could move the internal details of style-based queries into level 4, if it helps browsers more quickly get interop on the more established size features.

/cc @jensimmons who suggested this approach.

**Comment by fantasai** [comment]
I don't think there's a lot of internal details to sort out wrt style-based queries, so my take would be to just leave them in L3. And be clear that it's OK if browsers ship size queries in a release before they ship style queries.

**Comment by mirisuzanne** [comment]
Yeah, you might be right - at least for the basics of a direct property/value match. It seems like there will be interest in having the ability for more fuzzy matching at some point (checking for ranges on numbers, or contrast on colors, etc) – but I suppose we could delay those questions without delaying the entire feature.
