### ISSUE TITLE
[css-conditional-4] @supports shorthand

### ISSUE THREAD

**Issue by NagayamaToshiaki** [w3c/csswg-drafts#7022]
* please be specific (in the title and issue) about what you want to change:
  If you want to see if the property name is supported, current implementation of `@supports` is redundant.

```
@supports(some-new-feature: value) {
    .foo {
        some-new-feature: value;
    }
}
```

Instead, I would like to write it as:

```
@supports(some-new-feature) {
    .foo {
        some-new-feature: value;
    }
}
```

https://www.w3.org/TR/css-conditional-3/#at-supports

**Comment by fantasai** [comment]
The reason this wasn't done is because properties often acquire new values over time, so it's insufficient to know that the property is supported, you need to know whether that value of the property is supported.

**Comment by tabatkins** [comment]
Yes, this was very specifically omitted on purpose.
