### ISSUE TITLE
[css-fonts-4] `override-colors:` - clarify behaviour of indices outside the font's palette

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#7032]
> For each key/value pair in the value of this descriptor,
    the color with that key in the initial palette (i.e. by using the 'base-palette' descriptor)
    is overwritten by the color specified in this descriptor's value.

I suggest to add:

"A key that is outside the range of indices of the initial palette is ignored."

This helps clarify the intended behavior, as an alternative implementation option is to ignore the whole color-override descriptor. 

WPT test font-palette-23.html tests this already.

**Comment by svgeesus** [comment]
Good catch. This is the only obviously correct interpretation. (A new but unused key could be added, but there would be no point)

**Comment by drott** [comment]
Thanks for the quick fix.
