### ISSUE TITLE
[css-color] `color-interpolation` inherited property to  set default interpolation space

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#7035]
So we're busy adding interpolation syntax through `<color-interpolation-method>` tokens to all CSS features that need interpolation. So far we have it in `color-mix()` and gradients. There is still no syntax to set interpolation color space for transitions & animations yet. We *could* add `transition-interpolation: [ auto | <color-interpolation-method> ]#` and `animation-interpolation: [ auto | <color-interpolation-method> ]#` properties (and corresponding tokens in shorthands), but I was wondering: what if we have an (inherited) property to set default interpolation space across an entire subtree?

Something like

```
color-interpolation: auto | <color-interpolation-method>
```

This would allow authors to set this at the root of a subtree and get their preferred interpolation method as a default across gradients, `color-mix()`, transitions, animations, even SVG.
This would also allow us to remove the mandatory `<color-interpolation-method>` token from `color-mix()`.

Caveat: There is this old [SVG `color-interpolation` property](https://svgwg.org/svg2-draft/painting.html#ColorInterpolation) but I believe it's not really used/implemented. If it turns out that it is, we can include the existing `sRGB` and `linearRGB` as legacy aliases of `in srgb` and `in srgb-linear`.

**Comment by svgeesus** [comment]
The one problem that I see with this is that there is no one right interpolation color space that is good for everything. This will be particularly noticeable when we update Compositing to allow a linear-light colorspace like `xyz-d65` in addition to the current only (and wildly incorrect) option, gamma-encoded `srgb`.

This is why we had `color-interpolation filters` as well as `color-nterpolation`, as they have different initial values and filters needed to operate in alpha-premultiplied `srgb-linear`.

**Comment by fantasai** [comment]
Why do we need the in keyword here? Doesn't seem like we need it, and we don't have such keywords in property values generally.

**Comment by svgeesus** [comment]
Because that is how `<color-interpolation-method>` already works, for `color-mix()` and gradients

**Comment by svgeesus** [comment]
Realization I came to is that this proposal is for setting a default, so if you want a non-default value then we need the `transition-interpolation` or `animation-interpolation` _anyway_. So I will raise a new pair of issues for those.
