### ISSUE TITLE
No good reference for Display P3

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7036]
At the Color Workshop, it was raised that to date, there has been no good, authoritative definition for the Display P3 colorspace. This was unfortunate because it has become a clear de-facto standard for wide (but not super-wide) gamut screens.

Workarounds included 

1. linking to Apple developer documentation, which mentioned Display P3 in passing but did not fully define it; or 
2.  mentioning that the display primaries are the same as DCI P3. 
3. defining everything again, and being vague about whether that was normative or informative

The problem with the second approach is that DCI P3 is defined by a pair of SMPTE standards (smpte-eg-432-1-2010 and  smpte-rp-431-2-2011) which are not free; and also everything else about Display P3 (white point, transfer function, viewing conditions) is different to DCI P3.

The third approach is what CSS Color 4 was doing until today.

**Comment by svgeesus** [comment]
Today agreement was reached and the new [Display P3 specification](https://www.color.org/chardata/rgb/DisplayP3.xalter) went live.

Thanks in particular for Craig Revie (FFEI), Phil Green (ICC Technical Secretary) and Luke Wallis (Apple)  for their contributions towards formally defining this color space.

Note that the linked ICC profile differs slightly from the one commonly distributed with Apple hardware. The visual results will be identical, but the new profile is fully ICC V4 compliant.

**Comment by frivoal** [comment]
Looks great to me, thanks
