### ISSUE TITLE
[css-device-adapt] note/warning about not restricting zoom

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/csswg-drafts#704]
as per https://lists.w3.org/Archives/Public/www-style/2016Sep/0115.html and in light of the addition of a warning about the accessibility/usability concerns of preventing users from being able to zoom in the HTML spec with reference to the `viewport` meta (see https://github.com/w3c/html/commit/29b89343cbc12fa385143de3ddf70144d38b6095 and my subsequent tweak https://github.com/w3c/html/pull/607), i'm wondering if there's any mileage in me submitting a proposed PR with an initial draft note along the same lines for the CSS Device Adaptation spec? /cc @frivoal @stevefaulkner

**Comment by frivoal** [comment]
@patrickhlauke Yes, a PR would be great.
