### ISSUE TITLE
[css-cascade-5] Reword section on layer ordering

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#7041]
The section about layer ordering in css-cascade-5 currently reads:

> Cascade layers are sorted by the order in which they first are declared […]

> The outer layers are sorted first […]

> […] the layout layer will come first in the layer order […]

The resulting lists to go along with the code are always in **ascending weight/priority order** _(lowest prio at the top, highest prio at the bottom)_. For example, for `@layer default, theme, components`, we get:

> 1. default
> 2. theme
> 3. components
> 4. unlayered

In the section about Origins, however, the Origins get represented as a list in **descending priority order** _(highest prio at the top, lowest prio at the bottom)_:

1. Transitions
2. Important UA
3. Important User
4. Important Author
5. Animations
6. Normal Author
7. Normal User
8. Normal UA

While both of these representations are fine by themselves, it’s a bit confusing that they don’t follow the same order. I personally prefer the representation as used in Origins, as it resembles a stack.

---

While writing [my post on Cascade Layers](https://brm.us/at-layer) I tried to follow the representation/order as seen in the spec, suppressing the reflex of using a stack, ending up with a list:

![image](https://user-images.githubusercontent.com/213073/150830385-7b21e00d-34a8-421e-906e-3f80669e72f9.png)

Now, looking at [a new post by Stephanie Eckles on Cascade Layers](https://www.smashingmagazine.com/2022/01/introduction-css-cascade-layers/), I see she did grab to using the concept of something more stack-y in her visualization:

![image](https://user-images.githubusercontent.com/213073/150829310-85b3641b-c0dc-4259-a131-27230a5f3af3.png)

_(Graphic by Stephanie, with the lowest prio at the bottom and the highest prio at the top)_

Just yesterday, [Ahmad Shadeed also published a post on Cascade Layers](https://ishadeed.com/article/cascade-layers/) where he represented things as a stack.

![image](https://user-images.githubusercontent.com/213073/153715781-b0323e89-09d2-4feb-81cb-4c02c280ab9f.png)

_(Graphic by Ahmad, with the lowest prio at the bottom and the highest prio at the top)_

👉 **As other people also seem to have the reflex to represent things as a stack, would it make sense to reword the ordering mechanics of Layers to be in line with that of Origins?**

---

I would suggest to:

- Not use words like “before|after” or “first|last layer” in the spec, but always use words such as “higher|lower priority” (or “higher|lower cascade weight”)
- Use the same ordering as seen with Origins when representing layers in a list; i.e. rank them from high priority at the top to low priority at the bottom

That way, both Origins and Layers use lists in the “lowest prio at the bottom, highest prio at the top” form and visualizations that look like a stack.

As a benefit: If you understand the explanation from one, you also understand the other because they use the same representation.

---

I know it isn’t strictly necessary to update the spec on this — it is clear after all — but I do think people who saw a talk (or read a post) and now want to check the spec will benefit from this, as it removes friction to understand it — It’d be very confusing to, at a first glance, see a different order in the spec after just been having told differently.

**Comment by bramus** [comment]
Just noticed that @mirisuzanne also published [a visualization that approaches it as a stack](https://codepen.io/miriamsuzanne/pen/gOXRzBa)

<img width="626" alt="image" src="https://user-images.githubusercontent.com/213073/153716307-c9384cff-aef6-4a6e-be49-5c5628ea9959.png">

**Comment by fantasai** [comment]
I agree with the intuition of using a stack, but it seems to me that's basically what the spec is doing: in a stack, the first item is at the bottom, and subsequent items are added on top. And the Origins list is the resulting stack, from top to bottom, just like the visuals you're pointing to.

**Comment by tabatkins** [comment]
Yeah, but that's not the order we're using when describing *Layers* lists; there the highest-priority layer is at the bottom (following source order, instead).

**Comment by mirisuzanne** [comment]
To some extent the language of 'first'/'last'/'before'/'after' seems unavoidable, since the layer order is determined by order of appearance. I think that's what lead us to use the same order in our lists initially. But I agree for authors, it can be useful to think of the stack in **priority order** from highest to lowest. I'm not sure if it would add confusion in the spec to have some of the language based around appearance order, and some reversed to show priority?

**Comment by fantasai** [comment]
Tab and I tweaked the normative wording in the spec, I think it should be good now?

(There are still examples with lists of layers in order of appearance, but because these are representing the layer order and not the precedence of rules (which would require distinguishing between normal and !important), I think they should stay as-is.)

**Comment by bramus** [comment]
Thanks. Good to see “cascade weight” be replaced with “cascade precedence” as well there :)
