### ISSUE TITLE
Allow `select[value=""]` as a selector

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#7042]
To style a `<progress>` element based on its value, it's possible to use a selector like this _([demo on CodePen](https://codepen.io/bramus/pen/NWwgZLZ))_:

```css
progress[value="50"] { /* ✅ Works */
	accent-color: lime;
}
```

For `<progress>` elements that's not possible, though:

```css
select[value="1"] { /* ❌ Doesn't work */
  …
}
```

We can work around this using `:has()` _([demo on CodePen, use Safari TP](https://codepen.io/bramus/pen/exrYVW))_:

```css
select:has(option[value="1"]:checked) { /* ✅ Works */
   …
}
```

Would be nice if `select[value="…"]` worked as well, as it's easier to use. It's also specific selector of (0,1,1) vs (0,2,2) using `:has()`).

I know that `value` is not an attribute of `<select>`, but perhaps this could be exposed similar to how JavaScript makes `document.querySelector('select').value` work?

**Comment by bramus** [comment]
Come to think of it: I don't think this is the correct location to file this? One of the whatwg repos seems like a better place?

**Comment by myakura** [comment]
there's a discussion in the WICG forum https://discourse.wicg.io/t/selector-based-on-non-attribute-value-maybe-value-pseudo/5718 so you might want to chime in.

**Comment by bramus** [comment]
Thanks @myakura.

Closing this issue and continuing the discussion over there.
