### ISSUE TITLE
[css-images-4] Long overdue for republishing

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7043]
CSS Images 4 was [last published to /TR in April 2017](https://www.w3.org/TR/2017/WD-css-images-4-20170413/) and the [list of changes since then](https://drafts.csswg.org/css-images-4/#changes-20170413) is extensive. It is long overdue for republication.

1. Is the list of changes up-to-date?
2. Are there must-have, blocking issues that absolutely must be edited into the spec before republication?
3. Any other blockers I might be unaware of?

**Comment by fantasai** [comment]
I suspect the answers to these questions are no, yes, and yes. But it'd require doing triage to say which ones specifically. :) (This is why I didn't tackle it in December, this and Selectors 4 require some serious prep work before publication.)

**Comment by svgeesus** [comment]
Given that we this week we [cleared for pre-CR shipping](https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607) the gradient  use of `<color-interpolation-method>` used in Images 4, it is particularly important that the /TR version is less than 5 years old and actually includes that.

So, given the changes section is up to date, lets _actually publish the thing_ please?

**Comment by svgeesus** [comment]
@tabatkins @fantasai @LeaVerou on the call we didn't assign anyone to actually publish it. Its a WD so the automatic system can be used.

**Comment by fantasai** [comment]
@svgeesus Changes section is not up to date, so I think it needs a closer audit before publishing.

**Comment by fantasai** [comment]
Audit completed.

**Comment by svgeesus** [comment]
\0/

**Comment by svgeesus** [comment]
[Published 17 Feb 2023](https://www.w3.org/TR/2023/WD-css-images-4-20230217/)
