### ISSUE TITLE
[scroll-animations-1] Percentages vs Pixels for Scroll Timeline Values

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7045]
Parts of the ScrollTimeline and ViewTimeline interfaces need to represent values in “time”. In Web Animations 1, this was a raw number representing milliseconds. But for scroll animations, we're operating in a spatial dimension, not the time dimension. What should these “time” values represent?

So far options considered have been:

- progress from the starting scroll position to the ending scroll position
    - additional question in this case is, what represents 100%: 100 or 1.0?
- pixels from the starting scroll position

Web Animations 2 additions to the API allow for values with units, but for compatibility with Web Animations 1 we still need an answer here.

**Comment by fantasai** [comment]
Here are my arguments for pixel-based.
* The closest analog to what time-based timelines do is to make it represent an absolute length, since they represent absolute time.
* Calculating percentage progress from the absolute offset is easy (and vice versa), but going the other way around makes the API feel like it provides the less fundamental bit of information.
* Having the value of .currentTime changing as layout expands the content of the scroller, even though the scroll position (i.e. the current time in absolute terms) is not changing, feels odd.
* For ViewTimelines, using percentage progress also means that the startTime/endTime values are shifting in indirect and nonlinear ways as the amount of scroller content changes, even if the element does not move or change, which also feels uncomfortable.

(The arguments for percentage-based were around mapping animations from one context to another; I unfortunately can't remember exactly what the use case was.)

**Comment by tabatkins** [comment]
For the "values change as the size of the scrollable area changes", do those change your scroll-animation progress as well? Or is progress based directly on the scroll value as an absolute length?

I think we should choose the mapping that most closely matches the behavior in this regard.

**Comment by flackr** [comment]
> Web Animations 2 additions to the API allow for values with units, but for compatibility with Web Animations 1 we still need an answer here.

My presumption was that whichever unit we choose, we wouldn't coerce it into double values, and that Scroll Timeline animations would always use typed units (whether it's percentages or pixels). Time-based animations would continue to use double (milliseconds) so as to be backwards compatible with web-animations-1.

**Comment by flackr** [comment]
> (The arguments for percentage-based were around mapping animations from one context to another; I unfortunately can't remember exactly what the use case was.)

The arguments for percentage-based are:
* We expect that it will be common for developers to take a time-based animation (i.e. with duration, startDelay and other properties specified) and assign it to a scroll timeline. Converting those times to their relative proportions / percentages of the overall animation length is an easy way to explain how we can support this use case and those times only need to be converted once, rather than every time layout changes.
* Currently, keyframes are specified as percentage offsets, so for most animations the percentage time value will map directly to the value specified as the keyframe offset.
* For ViewTimelines, developers currently often use percentages from IntersectionObserver to track elements entering / exiting the view.

**Comment by kevers-google** [comment]
A further argument in support of percentages is that I struggle with calling a length based unit a valid time value.  Perhaps if we had used a more generic term within the web-animations-1 API we could more easily accommodate different units, but we are locked into using currentTime etc.  Percentages can be thought of as a normalized dimensionless time, so this doesn't seem like much of a stretch, but a <length> as a <time> strikes me as odd.  Perhaps I'm just being pedantic, but think we should try to avoid a potential obstacle that makes the animation API less intuitive.

I should add that this does not necessarily need to be an either or situation for setters in the API.  If using CSSNumberish with setters we could decide to allow for different units, provided there is a simple conversion process and consensus on the units for the getters and calculated timing call.  The web-animation-2 spec contains rules for how to convert times to percentages when setting a scroll-timeline to an animation.

**Comment by flackr** [comment]
> For the "values change as the size of the scrollable area changes", do those change your scroll-animation progress as well? Or is progress based directly on the scroll value as an absolute length?
> 
> I think we should choose the mapping that most closely matches the behavior in this regard.

@tabatkins Yes, when the values change as the size of the scrollable area changes, your scroll-animation progress also changes. The values are exactly the progress through the scroll animation. Percentage is direct mapping to animation progress.

**Comment by flackr** [comment]
To summarize, I think we only need to resolve on what the internal time values for scroll linked animations are (i.e. what is returned by currentTime and other API's), as we likely would want to support specified values to include other types (e.g. 100vh for one full viewport of scroll height). Issue #7102 covers whether the API's which access the internal times should return their types.

https://github.com/w3c/csswg-drafts/issues/7045#issuecomment-1039527712 covers the arguments for pixel based time values. https://github.com/w3c/csswg-drafts/issues/7045#issuecomment-1059275621 presents the arguments for percentage based time.
