### ISSUE TITLE
[scroll-animations-1] Scope of Named Timelines

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7047]
In the #6674 proposal, timeline names are attached to scroll containers and elements to create scroll timelines and view timelines, and which can then be referenced by animation properties to create animations.

What should be the scope of these names, i.e. which elements can reference a given timeline by name, and what happens if multiple elements declare the same name?

The current spec defines:

> A named scroll progress timeline or view progress timeline is referenceable in animation-timeline by:
>- the declaring element itself
>- that element’s descendants
>- that element’s following siblings and their descendants
>
> If multiple elements have declared the same timeline name, the matching timeline is the one declared on the nearest element in tree order, which considers siblings closer than parents. In case of a name conflict on the same element, scroll progress timelines take precedence over view progress timelines.

**Comment by andruud** [comment]
Current proposed text is not unreasonable, but I think this is the first time we would introduce a style resolution dependency between siblings? It's probably not ideal for parallel style resolution (which Firefox does, cc @emilio).

Are important use-cases not satisfied if we downgrade to the following?

- the declaring element itself
- that element’s following siblings and their descendants

---
Making these references "global" have been discussed before. (Never mind _how_ for a moment). Is this still on the agenda, or has that idea been discarded?

**Comment by andruud** [comment]
Global timelines would require a newish concept, e.g. current style is resolved according to the timeline state as of the previous style change event. The spec already has some "as of last frame"-behavior, so it's not necessarily a giant leap. If we are unsure about feasibility, it could make sense to have a vendor prototype/investigate before taking a resolution.

**Comment by flackr** [comment]
> Current proposed text is not unreasonable, but I think this is the first time we would introduce a style resolution dependency between siblings? It's probably not ideal for parallel style resolution (which Firefox does, cc @emilio).

I think `counter-increment` already creates such a dependency, see the MDN [example](https://developer.mozilla.org/en-US/docs/Web/CSS/counter#decimal-leading-zero_compared_to_lower-alpha). Note the use of counter-reset could technically be considered a scope to the counter but works globally for all following elements without it.

> Are important use-cases not satisfied if we downgrade to the following?
> 
> * the declaring element itself
> * that element’s following siblings and their descendants
> 
> _EDIT: after reading this ~1 month later: I'm not sure what I meant here, and why this would help. Maybe I meant that the scope could be just the element and its descendants (no siblings)._

Yes, I think @brunostasse touched on one. There are many cases where the animation is outside of the scrolling container.

> Making these references "global" have been discussed before. (Never mind _how_ for a moment). Is this still on the agenda, or has that idea been discarded?

The issue with global namespaces is the lack of reusability. E.g. if you had a tabbed component which used a global named scroll timeline to indicate the active tab, adding a second one would result in a name conflict. Whereas if we have proper name scoping they will each work independently.

One way we could make the use case @brunostasse mentioned work while still having an explicit element and its descendents scope would be for the timeline to be able to be named early but choose the actual descendant scroller it references later. This could be thought of as similar to the `counter-reset` / `counter-increment` and `toggle` / `toggle-trigger` properties. It would require plugging in the eventually found scrolling component to the timeline created earlier.

E.g. maybe this is something like:
```html
<style>
#outer {
  scroll-timeline-name: foo;
}
#scroller {
  scroll-timeline-source: foo; /* Makes this element the source for foo. Last element within the scope to do so wins? */
}
</style>
<div id="outer">
  <div id="scroller"></div>
</div>

**Comment by flackr** [comment]
The other option without introducing an explicit scope would be to make it visible to all subsequent elements in DOM order (i.e. ancestor siblings as well). To make the case @brunostasse brought up work you'd have to put the tabs after the scroller so that the scroller could define the scroll timeline before the tabs. Then you could use grid or flex layout to put the tabs above even though they are declared later. This doesn't seem as nice from a developer standpoint though.

**Comment by andruud** [comment]
@flackr Something like what you propose seems good? I assume that in that model, the timeline established by `foo` would be visible for _descendants_ only? (I.e. not siblings of `#outer`, and if that's what the author wanted, they would instead declare `foo` on the _parent_ of `#outer`). It still requires "as of last frame"-behavior, but like I said we can try to work with that.

**Comment by fantasai** [comment]
Okay, the current state of the spec reflects the resolutions. This is probably fine for now, but we're not addressing all use cases and it might be worth looking into the ability to split the declaration of a timeline (together with its scoping) from its actual attachment to a scroll container.

This would allow authors, for example, to declare a name on a subtree and make it available to all descendants of that subtree, and attach it to a scroll container that is a descendant within the subtree. (At the top level, declaring the name on the root element would make it global.)

Maybe something like `scroll-timeline-attachment: local | defer | ancestor | closest` where:

- `local` has the current behavior of binding the name to this element’s scroll container
- `defer` declares and scopes the name, but does not bind it to a scroll container
- `ancestor` looks up the ancestor chain for a matching timeline name and attaches to that instance; failing a match, declares it locally
- `closest` looks back up the tree including previous siblings for a matching timeline name (same lookup as animation-timeline), and attaches to the first matching instance; failing a match, declares it locally

**Comment by fantasai** [comment]
Minutes discussing [explicit scoping proposal](https://github.com/w3c/csswg-drafts/issues/7047#issuecomment-1239820755) in https://lists.w3.org/Archives/Public/www-style/2022Oct/0021.html

**Comment by bramus** [comment]
@fantasai I think this one can be closed. Discussion of https://github.com/w3c/csswg-drafts/issues/7047#issuecomment-1239820755 can continue in #7759, right?

**Comment by dshin-moz** [comment]
So there has been a bunch of changes since this decision, among them are that timelines are now more visible by default (i.e. No longer need to jump through hoops to refer to descendants' timelines), and that `timeline-scope` is used to limit the visibility, not extend it. 

Does it still make sense that names are flat-tree global? It seems a bit surprising to be able to find a timeline by reaching down into shadow tree(s) from the light tree..
