### ISSUE TITLE
[css-fonts-4] font-palette:light and font-palette:dark are a bit disingenuous

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#7048]
The font [can indicate](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal#palette-type-array) certain palettes as `USABLE_WITH_LIGHT_BACKGROUND` or `USABLE_WITH_DARK_BACKGROUND`.

CSS [says](https://drafts.csswg.org/css-fonts-4/#font-palette-prop):
> light: Some color font formats include metadata marking certain palettes as applicable on a light (close to white) background. This keyword causes the user-agent to use the first available palette in the font file marked this way.

However, a palette that is usable on a light background will probably involve dark colors. Therefore, when you say `font-palette: light` you are usually actually specifying a color palette whose colors are _dark_.

Switching the meaning of `light` and `dark` is probably not the right solution, though - the opentype flags say nothing about the foreground colors of the palettes. Maybe we should just copy the names from OpenType and rename `light` to `usable-with-light-background`? Or `usable-with-background(light)`?

**Comment by tabatkins** [comment]
Hmmmmmm, but `light` matches with the `(prefers-color-scheme: light)` value.

Your suggested names are a *mouthful*, but considering shorter ones, I don't think mentioning "scheme" would help - calling a palette "light color scheme" would probably *also* imply (perhaps even more strongly!) that it involves light colors.

Maybe just rewording the description to more directly reference the concept of light color schemes and referencing the MQ would help, and let us keep the short names? With an example showing off setting the palette to light or dark based on the MQ being light or dark?

**Comment by litherum** [comment]
> Hmmmmmm, but light matches with the (prefers-color-scheme: light) value.

That's a good point! When authors say (prefers-color-scheme: light) they mean the background is light but the foreground is (probably) dark.

I guess the difference is that, at least in _my_ mind, "color scheme" implicitly includes both the foreground and background colors together as a package, but font color palettes only include the foreground.

> Your suggested names are a mouthful

Maybe just font-palette: light-background ??? 🤔

**Comment by drott** [comment]
I have no strong opinion on this, but I tend to agree with Tab that short names can reasonably clearly be associated with the color schemes by the same name. Indeed, _light_ means likely dark colors in the font, but if it's explained to be "_goes with_ light scheme / light background", I think it's reasonably clear and not too verbose. +1 from my side to extending the explanation with an example and making reference to the `prefers-color-scheme` media query.

**Comment by svgeesus** [comment]
I agree that similar names to the existing (light mode, dark mode) naming is clear and not likely to cause confusion.

**Comment by litherum** [comment]
Okay let's close this then.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/76b751b2a6531cf15d73653d4dffcbc133331f00
