### ISSUE TITLE
[selectors-4] Republish

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7053]
The last /TR publication of Selectors 4 was [November 2018](https://www.w3.org/TR/2018/WD-selectors-4-20181121/). The [ED Changes list](file:///C:/Users/Chris/Documents/GitHub/csswg-drafts/selectors-4/Overview.html#changes-2018-11) is very short, and thus incorrect as the [History](https://github.com/w3c/csswg-drafts/commits/main/selectors-4/Overview.bs) is very long.

Spotted because https://www.w3.org/TR/selectors-4/#unknown--webkit--pseudo-elements does not exist and drafts.csswg.org is [down again](https://github.com/w3c/csswg-drafts/issues/6528) which also breaks link-checking and thus, /TR publication.

**Comment by fantasai** [comment]
Ok, finished reviewing the spec and updating the changes list. (Also fixed a few minor regressions.) It's in a publishable state now, although there's still a pile of Needs Edits we might want to run through first.

**Comment by fantasai** [comment]
And published.
