### ISSUE TITLE
[css-logical][css-cascade] `revert`/`revert-layer` with logical properties

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7054]
When setting a logical property to a [css-wide keyword](https://www.w3.org/TR/css-values-4/#common-keywords),

- [`initial`](https://www.w3.org/TR/css-cascade-5/#valdef-all-initial): currently, all the properties in every logical property group have the same initial values, so this just behaves as setting that value. It doesn't matter if it's first resolved into a physical property or not.
- [`inherit`](https://www.w3.org/TR/css-cascade-5/#valdef-all-inherit): resolved in #3029 that logical properties inherit from the same logical property in the parent, even if they map to different physical properties. Note that Blink, Firefox and WebKit don't do that: they resolve into physical, and then inherit the physical.
- [`unset`](https://www.w3.org/TR/css-cascade-5/#valdef-all-unset): currently, all logical properties are non-inherited, so it just behaves as `initial`.

OK, but what about `revert`? Imagine:

- UA origin:
    ```css
    foo {
      margin-inline-start: 100px;
      margin-left: 200px;
    }
    ```

- Author origin:
    ```css
    foo {
      margin-left: 300px;
      margin-inline-start: revert;
    }
    ```
https://www.w3.org/TR/css-cascade-5/#default says:

> Rolls back the [cascaded value](https://www.w3.org/TR/css-cascade-5/#cascaded-value) to the user level, [...]

So do we use `margin-inline-start: 100px`?

> [...] so that the [specified value](https://www.w3.org/TR/css-cascade-5/#specified-value) is calculated as if no [author-origin](https://www.w3.org/TR/css-cascade-5/#cascade-origin-author) rules were specified for this property on this element.

So do we drop `margin-inline-start` and use `margin-left: 300px` from author origin?

Actually, browsers use `margin-inline-start: 200px`.

Blink has `dialog {left: 0; right: 0}` in UA origin. Then, in horizontal ltr, `left: auto; inset-inline-start: revert` behaves like `inset-inline-start: 0`, using the UA value for `left`.

Analogously, Firefox and WebKit have `dialog {inset-inline-start: 0; inset-inline-end: 0}` in UA origin. Then, in horizontal ltr, `inset-inline-start: auto; left: revert` behaves like `left: 0`, using the UA value for `inset-inline-end`.

Similar for `revert-layer`, which actually allows more comprehensive tests: https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10046. It seems that what browser do is:

1. Find the final writing mode.
2. Use it to resolve logical all property declarations into physical ones, in all origins/layers.
3. Revert as usual.

Not unreasonable, but probably not much consistent with `inherit` using the same property instead of resolving into a physical property first (no browser  has implemented that yet).

**Comment by fantasai** [comment]
I think the behavior you describe that browsers have for this case makes sense, and we should just spec it. The goal of `revert` is to remove what the author did in the author origin as if nothing was declared, and reverting to the previous origin's values for the reverted side, whether they came from physical or logical properties in that origin, makes sense.

**Comment by Loirooriol** [comment]
Yes, and BTW Blink has the concept of surrogate properties, which are basically pairs of properties where one should actually be a [legacy shorthand](https://drafts.csswg.org/css-cascade-5/#legacy-shorthand) of the other (e.g. it has a `-webkit-` prefix with slightly different syntax or something), but instead of a shorthand it's implemented as an independent longhand that shares a computed value. They kinda behave like logical/physical properties in the sense that order matters, and the last one wins. For these, `revert` and `revert-layer` don't care which one was specified in the previous origin/layer. This seems reasonable to me:

```css
@layer { #target { -webkit-text-orientation: sideways } }
@layer { #target { text-orientation: revert-layer } }
```
```js
getComputedStyle(target).textOrientation; // "sideways"
```

WebKit has a similar concept of properties like that. Currently `revert` and `revert-layer` only roll back to the same exact property, but I plan to change this in https://bugs.webkit.org/show_bug.cgi?id=238125

**Comment by fantasai** [comment]
@Loirooriol Edited in, please review and let us know if the edits are satisfactory!

**Comment by Loirooriol** [comment]
I'm not sure if the wording is 100% clear, like

```css
@layer { div { block-size: 100px } }
@layer { div { height: 200px } div { height: revert-layer } }
```

The patch says that reverting `height` also reverts `block-size`, but we are keeping `block-size: 100px`, so it may cause some confusion? May benefit from an example.

**Comment by mirisuzanne** [comment]
@Loirooriol example added in the commit above.
