### ISSUE TITLE
[css-text-4] text-spacing: trim-end is better than allow-end for the normal value

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#7055]
https://drafts.csswg.org/css-text-4/#text-spacing-property

In the current draft, the `normal` value is defined as:

> Specifies the baseline behavior, equivalent to `space-start allow-end trim-adjacent`.

About the `space-start` value in this definition, I have proposed to change it to `space-first` in the following issue:

- https://github.com/w3c/csswg-drafts/issues/2462

Now, I add one more suggestion: change `allow-end` to `trim-end` in this definition. So the `normal` will be equivalent to `space-first trim-end trim-adjacent`.

I summarize the reason:

- `trim-end` is typographically better than `allow-end` in most cases
- `trim-end` behavior is simpler and needs less overhead than `allow-end`

### `trim-end` is typographically better than `allow-end` in most cases

In justified text, the end of lines should be aligned visually. The `trim-end` is fine for this purpose, and `allow-end` is not very fine because it makes punctuation at end of lines not alined visually.

Of course, there are cases where `allow-end` is preferable. Traditionally, in Japanese and Chinese typesetting, a grid-like arrangement with solid setting (no inter-character spacing) is preferable. The `trim-end` may add extra inter-character spacing when a fullwidth closing punctuation at end of line is trimmed to half-width. So `allow-end` may be better in this case. However, this will be a less usual case in Web, where the number of characters per line is usually not fixed, and the grid-like arrangement doesn't make much sense.

### `trim-end` processing is simpler and needs less overhead than `allow-end`

To implement the default behavior (`normal`), it is important that the processing needs less overhead.

The `trim-end` processing is simpler, because in this mode, fullwidth closing punctuation can be treated as half-width punctuation plus half-width space which is discarded at line end as like a normal space. On the other hand, `allow-end` is not so simple because processing needs to be changed depending on the position of the fullwidth closing punctuation in the line, and the processing overhead is not very small.

This is what I have found in my recent experience implementing the text-spacing property in [Vivliostyle.js](https://github.com/vivliostyle/vivliostyle.js).

----

FYI, a related blog post on Vivliostyle site: [Line end handling has been evolved to allow multiple typesetting options](https://vivliostyle.org/blog/2022/02/08/Improved-of-line-end-handling-and-support-for-page-progression-direction-in-PDF/)

**Comment by fantasai** [comment]
CC @kojiishi @jfkthame @litherum @r12a

**Comment by fantasai** [comment]
@r12a We no longer have a character grid proposal. Might consider reviving it someday, but there's a lot more fundamental stuff to solve for inline layout first, and my impression is CJK typesetting is moving away from that style rather than towards it.

**Comment by fantasai** [comment]
Internationalization WG recommends adopting this proposal (TPAC 2022-09-13).

**Comment by aphillips** [comment]
I18N recommends that trim-end be the default. See about [here](https://www.w3.org/2022/09/13-i18n-minutes.html#t09)

**Comment by MurakamiShinyu** [comment]
> RESOLVED: Incorporate trim-end behavior into the normal keyword

It's good. Please also incorporate space-first behavior into the normal keyword:

- https://github.com/w3c/csswg-drafts/issues/2462#issuecomment-524820469

In justified paragraph, it is very bad if the line end edge is visually aligned by trim-end but the line start edge is not. The combination of space-start and trim-end looks very unbalanced.
