### ISSUE TITLE
[css-content] Keyword 'document-url' is undefined

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#706]
The keyword `document-url` is included in the [syntax of `<content-list>`](https://drafts.csswg.org/css-content/#typedef-content-list) in the CSS Generated Content Module Level 3, though there is no prose defining its meaning.

Sebastian

**Comment by dauwhe** [comment]
I think this was a hoped-for feature in the 2003 draft. Given that there appears to be no implementation interest, no mentions on www-style, and such things are easily done by JS, I'll remove it.

**Comment by dauwhe** [comment]
Closed via 9d5286e

**Comment by SebastianZ** [comment]
Thanks for the info and for the patch!

Sebastian
