### ISSUE TITLE
[css-color-4] Percentage reference ranges for `lab()`/`oklab()`/`lch()`/`oklch`/`color()`

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7064]
For the call, to see the full proposal in one place, the percentages would be explicitly defined so that 0% to 100% maps as follows::

* `lab.L`: `[0, 100]`
* `lab.a`: `[-125, 125]`
* `lab.b`: `[-125, 125]` (a and b have the same range, for simplicity)
* `lch.c`: `[0, 150]`
* `oklab.L`: `[0, 1.0]`
* `oklab.a`: `[-0.4, 0.4]`
* `oklab.b`: `[-0.4, 0.4]` (see above re: a and b)
* `oklch.c`: `[0, 0.4]`
* `xyz`, `xyz-d50`, `xyz-d65`: `[0, 1.0]`
* predefined RGB: `[0, 1.0]` (not a change, but a clarification)

No-one mentioned hue as a percentage so it remains an angle, in degrees by default if no unit is given.

This gives useful ranges for percentages on all colors, roughly covering the `display-p3` gamut plus a bit, and should minimize the errors in implementations where something was either not divided by 100, or was and shouldn't be, etc (Safari and color.js and PostCSS all had these at various points).

It also means people can paste in `lab`/`lch`/`oklab`/`oklch` values from other software (which does not use percents) without getting an error and without having to remember if L is [0..1] or [0..100].

`lch(29% 66.5 327)` == `lch(29% 44.33% 327)` == `lch(29 66.5 327)` 
`oklch(58% 0.11 110)` == `oklch(58% 27.5% 110)` == `oklch(0.58 0.11 110)`
`color(xyz-d65 0.9504  1.0000  1.0888)`  == `color(xyz-d65 95.04%  100.00%  108.88%)`

_Originally posted by @svgeesus in https://github.com/w3c/csswg-drafts/issues/6741#issuecomment-1041818465_

**Comment by svgeesus** [comment]
from https://github.com/w3c/csswg-drafts/issues/6741#issuecomment-1041893440

The CSS Working Group just discussed `[css-color] Support all existing (non-legacy?) formats in color()?`, and agreed to the following:

* `RESOLVED: Will add this to the color-4 module, after forking to a new issue`

<details><summary>The full IRC log of that discussion</summary>
&lt;emeyer> Topic: [css-color] Support all existing (non-legacy?) formats in color()?<br>
&lt;emeyer> Github: https://github.com/w3c/csswg-drafts/issues/6741<br>
&lt;Rossen_> q:<br>
&lt;Rossen_> q<br>
&lt;emeyer> lea: Looking for consensus for our plan on percentages.  Right now they’re aliased to 0-1 ranges.<br>
&lt;emeyer> …We were thinking o using them for a reference range based on p3 so people can use absolute coordinates if they want, or use percentages if they want something close enough.<br>
&lt;lea> https://github.com/w3c/csswg-drafts/issues/6741#issuecomment-1028141623<br>
&lt;emeyer> s/ o / of /<br>
&lt;emeyer> chris: Mostly I wanted more feedback just to be sure this is what we want to do.<br>
&lt;emeyer> lea: What’s unclear is whether this about the color() function or is it about other things?<br>
&lt;emeyer> chris: It’s about the other things.<br>
&lt;emeyer> Lea: we really need a new issues.<br>
&lt;emeyer> Rossen: We can definitely get a different issue.  Chris, you framed this as a question toward implementors, so let’s hear from them.<br>
&lt;emeyer> Mike Bremford: Changing it isn’t a big deal either way.<br>
&lt;emeyer> TabAtkins: +1 from me as well.  I like this from the perspective of “all color models accept the same input space”.<br>
&lt;lea> Note that this means that color(rec2020 50% 100% 50%) will NOT be equal to color(rec2020 .5 1 .5)<br>
&lt;emeyer> Rossen: Any objections?<br>
&lt;lea> (+1 from me too, in case it's not clear)<br>
&lt;emeyer> …As next steps, we’ll break this out into its own issue, build consensus, and get it into a spec.<br>
&lt;emeyer> RESOLVED: Will add this to the color-4 module, after forking to a new issue<br>
</details>

**Comment by svgeesus** [comment]
Not discussed in today's meeting: the impact on **resolved values** and in particular on **serialization**.

It seems to me that the a,b, C and H values should resolve percentages, so for example an OKLCH Chroma of 70% would serialize as (0.7 * 0.4) = 0.28 while an LCH Chroma of 70% would serialize as (0.7 * 150) = 105. This also makes the serialized form compatible with what was specified previously.

For Lightness though currently the serialized form specifies a percentage. Should it continue to do so, or should the percentages be resolved so an OKLab Lightness of 50% serializes as 0.5 while a CIE Lab Lightness of 50% serializes as 50?

**Comment by svgeesus** [comment]
Currently the spec says, for CIE Lab

```html
        The component values are serialized in base 10;
	the Lightness component is serialized as
	<<percentage>>, while the a and b component values
	are serialized as <<number>>.
```

**Comment by svgeesus** [comment]
> Not discussed in today's meeting: the impact on resolved values and in particular on serialization.

@weinig @smfr @Loirooriol @tabatkins 

( @faceless2 your implementation doesn't serialize )

**Comment by Loirooriol** [comment]
Not the right person to ping, my understanding of colors beyond sRGB is close to null, so not much sure about serializations :)

**Comment by svgeesus** [comment]
@emilio ?

**Comment by Crissov** [comment]
Just to be clear, for _a_ and _b_ axes, this means `0%` is equivalent to some specified *negative* value. 
Also, negative percentages as well as percentages above `100%` are valid and meaningful values, i.e. they must not be clipped.

**Comment by svgeesus** [comment]
> Just to be clear, for a and b axes, this means 0% is equivalent to some specified negative value.

Not my intent, so thanks for spotting the imprecision in the wording. For the a and b axes, the reference range runs from -100%, through 0% corresponding to 0, to +100%.

**Comment by svgeesus** [comment]
Still looking for comments regarding [serialization](https://github.com/w3c/csswg-drafts/issues/7064#issuecomment-1042241604)

**Comment by tabatkins** [comment]
Yes, we should retain compatibility with existing usage (and/or with wide usage outside of CSS) and serialize as numbers.

**Comment by svgeesus** [comment]
Needs changes to WPT parsing/color-computed.html to account for Lightness now serializing as number.
