### ISSUE TITLE
[css-grid-2] Specify behaviour when a sub grids margin/border/padding is larger than the edge tracks maximum size

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#7072]
It appears that the abs-pos-002/3.html subgrid tests, as well as subgrid-mbp-overflow-001/2/3/4 all expect that the padding of the subgrid item is capped at the size of the edge track spanned by the subgrid item.

Minimised testcase showing capping in Gecko: https://jsfiddle.net/r3n0zt6v/

My reading of the spec suggests that we probably shouldn't do this, but there's a lot of tests requiring this behaviour.

It'd be good to clarify the intent here, and figure out how to adjust the tests.

I filed a WPT pull request for some of the tests, but the subgrid-mbp-overflow ones are significantly more involved - https://github.com/web-platform-tests/wpt/pull/32611

**Comment by tabatkins** [comment]
Yes, those tests are definitely broken. Nothing in the spec suggests that the magical margin should be capped by anything. And capping as browsers are currently doing doesn't even rescue the layout in any way; the items in those cells still overflow their tracks. (I could *understand* if it was capped at `track size - max(min-content of items)`, as that could *potentially* be justified as doing something useful, but it's not, and it doesn't do *enough* useful to be worthwhile anyway.)

So yes, if you're willing to fix those WPTs that would be awesome.
