### ISSUE TITLE
[css-grid-2] Should items inside a subgrid establish a baseline for items in the outer grid?

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#7078]
The test baseline-001.html is checking that they do, but the spec doesn't really cover how to handle sub grids wrt baseline.

**Comment by fantasai** [comment]
This is covered in [item (h)](https://drafts.csswg.org/css-grid-2/#subgrid-item-contribution):
> The subgrid’s own grid items participate in the sizing of its in the subgridded dimension(s) and are aligned to it in those dimensions.
> 
> In this process, the sum of the subgrid’s margin, padding, and borders at each edge are applied as an extra layer of (potentially negative) margin to the items at those edges. [...]

Do you think this needs to be clarified? Is there some phrasing you would prefer that would make it clearer that baseline alignment is included in the "aligned" part of the first sentence?

**Comment by mattwoodrow** [comment]
I think it'd be nice if section 11 (alignment and spacing) made reference to subgridded items as being explicitly included (as is done for the track sizing algorithm). I think this applies to both the align/justify properties, as well as the grid container's baseline itself.

Current it just references 'grid items', which are defined as being the in-flow children of the grid container, and having to cross-reference the subgrid section of the spec to override this seems confusing.

**Comment by tabatkins** [comment]
Done!!
