### ISSUE TITLE
[selectors-4] Allow more pseudo-classes following a pseudo-element

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7085]
There is already an issue mentioned in [3.6.3. Pseudo-classing Pseudo-elements](https://drafts.csswg.org/selectors/#pseudo-element-states) (I did not find the corresponding issue on GH):

> A [pseudo-element](https://drafts.csswg.org/selectors/#pseudo-element) may be immediately followed by any combination of the [user action pseudo-classes](https://drafts.csswg.org/selectors/#useraction-pseudos) [...]
>
> ISSUE 3 Clarify that [:not()](https://drafts.csswg.org/selectors/#negation-pseudo) and [:is()](https://drafts.csswg.org/selectors/#matches-pseudo) can be used when containing above-mentioned pseudos.

I think the issue can be completed with:

- all pseudo-classes: when following a pseudo-element explicitly defined to be matchable by this pseudo-class (eg. `::shadow:empty`, `::shadow:defined`, `::shadow-child:first-child`, etc)
- `:where()`: when containing user-action pseudo-classes as arguments
- `:defined`: I'm not sure about this one because it is defined as matching *elements that are fully defined, as dictated by the host language*, not as matching *pseudo-element*

Pseudo-class functions which do not match the corresponding (pseudo-element) sub-classing condition could be considered as matching nothing instead of being invalid.

But I wonder if I'm missing something because: 
- `::before:hover` does not work in Chrome/Firefox (not tested in other browsers)
- [MDN browser compat table](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) includes *Pseudo-element support* with support from early versions of all browsers: is it the support of `:hover` *followed by* a pseudo-element, or the other way around? The french version defines that *the `:hover` pseudo-class can follow any pseudo-element*, but not the english version. Non-english versions are often translations of the english text. 
- I could not find any related issues on Chromium Issues or ~~Mozilla Firebug~~ Bugzilla 
- **EDIT:** I missed the related issue on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1122965) and created an issue on [Chromium Issues](https://bugs.chromium.org/p/chromium/issues/detail?id=1300566)
- Chrome DevTools does not allow to simulate user-action pseudo-classes like `:hover` on a pseudo-element (cf. this [SO issue](https://stackoverflow.com/questions/35743860/how-do-you-set-hover-using-chrome-dev-tools-on-pseudo-elements?rq=1))
- Firefox DevTools allows to set `:hover` but it triggers this state on the originating element

**Comment by SebastianZ** [comment]
> I could not find any related issues on Chromium Issues or Mozilla Firebug

Nice to read Firebug! 😄 One related Firefox/Gecko issue is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1122965

I couldn't find one for Chromium or WebKit.

Sebastian

**Comment by Loirooriol** [comment]
This seems related to #6737 in the sense that some contexts restrict which selectors you can use, then `:is()`/`:where()`/`:not()` should probably be allowed but with their argument obeying the restriction.

**Comment by fantasai** [comment]
Agenda+ to review allowing :is()/:not()/:where()

- after pseudo-elements, when restricted to containing the user-action pseudos (which are already allowed there)
- generically stated, anywhere their arguments are allowed

**Comment by Loirooriol** [comment]
> provided their arguments all adhere to the above restriction

Does this mean that `::before:is(:hover, :first-child)` is completely invalid, or becomes `::before:is(:hover)`?

**Comment by fantasai** [comment]
@Loirooriol Good question, `::before:first-child` is invalid, but since `:is()` has forgiving parsing maybe it should be valid?

**Comment by cdoublev** [comment]
A third option would be to relax all pseudo-classing restrictions on pseudo-element: `::before:first-child` or `::before:not(:first-child)` would be valid and would match nothing, which I think would be identical to forgiving parsing.

**Comment by cdoublev** [comment]
So basically, the basic syntax of the argument of logical combination pseudo-classes following a pseudo-element is now allowed to be a very small subset of `<*-selector-list>` specific to the pseudo-class and the pseudo-element.

It would be nice to define this syntax explicitly, to avoid parsing against `<forgiving-selector-list>` whereas a simple list of user action pseudo-class selectors would be expected. 

I do not think pseudo-elements are focusable so user actions do not even need to be stackable, and the basic syntax of the argument of `:is()` or `:where()` following a pseudo-element could be `<user-action-pseudo-class-selector>#`, which is way more efficient to parse than `<forgiving-selector-list>`, I think.

**Comment by cdoublev** [comment]
I may have misunderstood your resolution. Can you please clarify whether a pseudo-class that is not allowed to follow a pseudo-element should be invalid or should match nothing? Currently, it should be a user action otherwise it is invalid, and it matches nothing if the current action is not defined to follow the pseudo-element (or vice-versa).

I also think to `::before:is(div :>> :hover)` or `::before:is(div **:hover)` assuming `:>` or `**` (cf. #7346, #4565) will ever be defined in Selectors 5, so my previous comment is definitely wrong. If the answer to my previous question is *it should be invalid*, can you clarify that logical combination pseudo-classes following a pseudo-element still accept a `<*-selector-list>`?

Or I should just wait for your edits...

**Comment by tabatkins** [comment]
@fantasai and I fixed in <7d86995cf>

**Comment by cdoublev** [comment]
It is clearer to me now, thanks. This issue is closed but has the "needs testcase" label, so I leave some suggestions below....

---

In [18. Grammar](https://drafts.csswg.org/selectors-4/#grammar), a whitespace should be forbidden between `<compound-selector>` and `<pseudo-compound-selector>`, and between `<pseudo-element-selector>` and `<pseudo-class-selector>`.

```diff
  White space is forbidden:
+ - Between <compound-selector> and <pseudo-compound-selector>.
+ - Between a <pseudo-element-selector> and a <pseudo-class-selector>.
  - [...]
```

Alternatively:

```diff
- White space is forbidden:
-   - [...]
+ White space is forbidden between any components of `<compound-selector>` or `<pseudo-compound-selector>`, 
+ except between `'['`, `<wq-name>`, `<attr-matcher>`, `<string-token>`, `<ident-token>`, `<attr-modifier>`, `']'`.
```

---

Pseudo-elements are forbidden in `:is()`, `:where()`, `:not()`, `:has()`, `:nth-*-child()`, either in prose or with syntax, which is inconsist. 

I suggest to define that `:is()` and `:where()` should take `<forgiving-real-selector-list>` as a list of `<complex-real-selector>`, and `:not()` should take `<real-selector-list>`. This would also allow to clarify the grammar of `:current()`, for which it is not clear whether pseudo-elements are allowed or not (I assume they are not).

```diff
- The matches-any pseudo-class, :is(), is a functional pseudo-class taking a <forgiving-selector-list> as its sole argument.
+ The matches-any pseudo-class, :is(), is a functional pseudo-class taking a <forgiving-real-selector-list> as its sole argument.
```

```diff
- The negation pseudo-class, :not(), is a functional pseudo-class taking a selector list as an argument.
+ The negation pseudo-class, :not(), is a functional pseudo-class taking a <real-selector-list> as an argument.
```

```diff
- Pseudo-elements cannot be represented by the matches-any pseudo-class; they are not valid within :is().
```

```diff
- Pseudo-elements cannot be represented by the negation pseudo-class; they are not valid within :not().
```

```diff
- 1. Parse a list of <complex-selector>s from input, and let selector list be the result.
+ 1. Parse a list of <complex-real-selector>s from input, and let selector list be the result.
```

```diff
+ <real-selector-list> = <complex-real-selector-list>
```

---

The argument of logical combination pseudo-classes following a pseudo-element should be restricted to the same set of pseudo-classes allowed to follow the pseudo-element. For example, `::before:is(type)` shoud be invalid, but I do not think there is a normative definition for this.

```diff
- Note: The logical combination pseudo-classes pass any restrictions on validity of pseudo-classes to their arguments.
+ Note: The logical combination pseudo-class arguments are restricted to the pseudo-classes that are allowed to follow the pseudo-element.
```

**Comment by tabatkins** [comment]
> In [18. Grammar](https://drafts.csswg.org/selectors-4/#grammar), a whitespace should also be forbidden:

Yup, amended the prohibition between top-level components of `<compound-selector>` to also apply to `<pseudo-compound-selector>`, and additionally prohibited it between the components of a `<complex-unit>` (which I just added to make this easier to talk about).

> Pseudo-elements are forbidden in :is(), :where(), :not(), :has(), :nth-*-child(), either in prose or with syntax, which is inconsistent.

I've redefined `<forgiving-selector-list>` to use `<complex-real-selector>`; no need for an additional grammar term. If we ever allow :is()/:where() to do pseudo-elements, we can just change this definition. I also fixed :not() to say its argument is a `<complex-real-selector-list>`.

I've left the prose forbidding pseudo-elements, tho; it's useful to have that called out explicitly rather than just being implicit from the grammar.

> The argument of logical combination pseudo-classes following a pseudo-element should be restricted to the same set of pseudo-classes allowed to follow the pseudo-element.

Ah yes, that text was slightly too restrictive in what it was talking about. Fixed. (It was just a note, and the normative text it was duplicating did have the correct wording.)

> A compound selector preceding a pseudo-compound selector is excluded from the definition of the latter.
> div::before::marker:hover is not defined, only ::before:hover.

I'm not sure where you're getting that from. `div::before::marker:hover` is definitely allowed by the grammar (both now that I've provided `<complex-unit>`, and before when it was just expanded in-place).

The prose definition did make mention of it being preceded by a compound selector, explicitly, which I've fixed as part of another edit. Now it correctly mentions that it can be preceded by a compound or pseudo-compound selector.

**Comment by cdoublev** [comment]
> > A compound selector preceding a pseudo-compound selector is excluded from the definition of the latter.
> > div::before::marker:hover is not defined, only ::before:hover.
> 
> I'm not sure where you're getting that from. `div::before::marker:hover` is definitely allowed by the grammar (both now that I've provided `<complex-unit>`, and before when it was just expanded in-place).
> 
> The prose definition did make mention of it being preceded by a compound selector, explicitly, which I've fixed as part of another edit. Now it correctly mentions that it can be preceded by a compound or pseudo-compound selector.

`<complex-selector-unit>` and the changes in the prose were exactly what I was hoping for. I am bit late, but thank you for all these edits.

If you allow me a last comment, I feel like defining `:is()` as taking `<forgiving-selector-list>` is a bit over-generalized because its argument is highly context-sensitive, as noted in your addition to the introduction of *4. Logical Combinations*.

  > The logical combination pseudo-classes are allowed anywhere that any other pseudo-classes are allowed, but pass any restrictions to their arguments. (For example, if only compound selectors are allowed, then only compound selectors are valid within an `:is()`.)

Maybe something like *Unless otherwise specified for the context, `:is()` is a functional pseudo-class taking a `<forgiving-selector-list>` as its sole argument* would be more helpfull.

Same thing for `:not()`.

**Comment by tabatkins** [comment]
Nah, grammatically it's a forgiving-selector-list. The rules for what selectors are valid inside in that list can vary, is all. No different than the fact that a type selector can be valid per the grammar but contain an unknown namespace, rendering it invalid.

Selectors conflates parsing validity and selector validity when talking about invalid selectors. Doesn't particularly matter which level we address something on, except for readability/understandability purposes.
