### ISSUE TITLE
[css-cascade] Does 'revert-layer' roll back to preshints?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7087]
https://drafts.csswg.org/css-cascade-5/#preshint

> All document language-based styling must be translated to corresponding CSS rules and enter the cascade as rules in either the [UA-origin](https://drafts.csswg.org/css-cascade-5/#cascade-origin-ua) or a special-purpose author presentational hint origin between the regular [user origin](https://drafts.csswg.org/css-cascade-5/#cascade-origin-user) and the [author origin](https://drafts.csswg.org/css-cascade-5/#cascade-origin-author). For the purpose of [cascading](https://drafts.csswg.org/css-cascade-5/#cascade) this [author presentational hint origin](https://drafts.csswg.org/css-cascade-5/#author-presentational-hint-origin) is treated as an independent [origin](https://drafts.csswg.org/css-cascade-5/#origin), but for the purpose of the [revert](https://drafts.csswg.org/css-cascade-5/#valdef-all-revert) keyword it is considered part of the author origin.

What about the `revert-layer` keyword?

**Comment by fantasai** [comment]
It's not the `revert` keyword, so it's treated as an independent origin, and isn't reverted by `revert-layer` in an author style sheet.

IIRC this was intentional.

**Comment by Loirooriol** [comment]
That section was entirely copied from L4 where there is no `revert-layer`, so it's not obvious that this was intentional. Maybe add a note? Also, is it possible to test this? Is there any normative preshint? HTML rendering only says "expected", not "must".

**Comment by Alohci** [comment]
Using `revert-layer` to revert height and width of an image back to the HTML attribute values seems distinctly useful. Chrome and Firefox already do this nicely.

**Comment by Loirooriol** [comment]
OK, filed https://bugs.webkit.org/show_bug.cgi?id=237532

**Comment by tabatkins** [comment]
@Loirooriol Added a clarification. Let us know if the wording works for you, or if you think something different would be better.

**Comment by Loirooriol** [comment]
LGTM
