### ISSUE TITLE
[css-contain-3] section on `content-visibility` is empty, aside from an "issue" block that points back to css-contain-2

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#7089]
css-contain-3 section 7, https://www.w3.org/TR/css-contain-3/#content-visibility , is empty and just contains an issue with a link to the same section in css-contain-2 (which is nonempty there).

Screenshot:
![image](https://user-images.githubusercontent.com/426803/155764773-3727e3b0-ab5c-4a71-8c59-7c74a6bd05f5.png)

Are we intending to add some spec-text there, or is this just copypaste cruft perhaps?

(If there is indeed something TBD there, maybe worth adding some notes to the "issue 12" there?)

**Comment by dholbert** [comment]
note: in the draft spec, the section/issue numbering is different from what I described above; there, the section in question is section 8, with "issue 8" being the in-spec issue that just has a link to css-contain-2.

Link: https://drafts.csswg.org/css-contain-3/#content-visibility
Screenshot:
![image](https://user-images.githubusercontent.com/426803/155815547-d15bf7a1-d48a-45a5-864a-6cafd8be53c1.png)

**Comment by mirisuzanne** [comment]
This is the syntax that I was given for building a 'diff spec' on top of a previous level that is still in development. It's meant to imply that the contents of the previous level can be inserted here, without change. With the intent that, once the previous level is more stable, the content of the section should actually be copied over.

**Comment by dholbert** [comment]
Hmm, ok. I admit to being somewhat-unfamiliar with lifecycle/recommendations for early-stage specs. :)  If this is as-it-should-be, feel free to close-with-no-change.
