### ISSUE TITLE
[css-pseudo] highlight pseudos and emphasis/underline properties

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#7101]
https://drafts.csswg.org/css-pseudo-4/#highlight-styling

> The following properties apply to the highlight pseudo-elements:
> * […]
> * [text-decoration](https://drafts.csswg.org/css-text-decor-4/#propdef-text-decoration) and its associated properties
> * [text-shadow](https://drafts.csswg.org/css-text-decor-4/#propdef-text-shadow)
> * […]

The current spec text could be interpreted as only allowing ‘text-decoration’ and ‘text-decoration-*’ and ‘text-shadow’, which would include line decorations and text shadows, but not emphasis marks or ‘text-underline-position’ or ‘text-underline-offset’. Should we somehow allow those properties more explicitly?

(@fantasai, @frivoal, @mrego)

**Comment by fantasai** [comment]
Clarifying that text-underline* applies is good, and adding `text-emphasis-color` makes sense, but I'm a little hesitant about `text-emphasis` itself. Unlike text decorations, emphasis dots don't overlay each other, it's just a straight-up inherited property. Also they can impact layout. So I don't think we can add anything other than `text-emphasis-color` itself here.

**Comment by mrego** [comment]
Yeah I agree with @fantasai. I don't think `text-emphasis` in general can be applied on highlights due to the layout changes it implies, `text-emphasis-color` should be fine though.

**Comment by delan** [comment]
Makes sense! I’ve updated #7222, pending discussion in the meeting.

**Comment by delan** [comment]
Hmm… [#highlight-text](https://drafts.csswg.org/css-pseudo-4/#highlight-text) says:

> The element’s own text decorations (both [line decorations](https://www.w3.org/TR/css-text-decor/#line-decoration) and [emphasis marks](https://www.w3.org/TR/css-text-decor/#emphasis-marks)) are thus drawn in the pseudo-element’s own [color](https://drafts.csswg.org/css-color-4/#propdef-color) when that is not [currentColor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor), regardless of their original color or fill specifications.

So if originating emphasis marks are recolored to the highlight ‘color’ just like line decorations, rather than using the highlight ‘text-emphasis-color’, and highlights can’t add their own emphasis marks with ‘text-emphasis-style’, then actually I think there’s no need for ‘text-emphasis-color’ on highlights. @fantasai, what do you think?

**Comment by fantasai** [comment]
@delan Allowing `text-emphasis-color` would have an effect: on existing emphasis marks in the text. Whether it's useful to allow that, I don't think it is particularly useful. :)

**Comment by delan** [comment]
@fantasai how would it affect originating emphasis marks, given the following?

> […] Instead the topmost active [highlight overlay](https://drafts.csswg.org/css-pseudo-4/#highlight-overlay) redraws that text (and those decorations) over all the highlight overlay backgrounds using that highlight’s own [color](https://drafts.csswg.org/css-color-4/#propdef-color).
>
> Note: The element’s own text decorations (both [line decorations](https://www.w3.org/TR/css-text-decor/#line-decoration) and [emphasis marks](https://www.w3.org/TR/css-text-decor/#emphasis-marks)) are thus drawn in the pseudo-element’s own [color](https://drafts.csswg.org/css-color-4/#propdef-color) when that is not [currentColor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor), regardless of their original color or fill specifications.

I also think originating emphasis marks get painted not because the highlight inherits ‘text-emphasis-style’, but because we say so in #highlight-painting. ‘text-emphasis-color’ has no effect when ‘text-emphasis-style’ is ‘none’, so by analogy, if we want it to have an effect when ‘text-emphasis-style’ is not applicable, we should probably say so explicitly.

**Comment by delan** [comment]
Yeah, that makes sense. I think we should ignore ‘text-emphasis-color’ for now, or even remove it from the list until we decide to spec that behaviour. I’ve updated #7222 to remove it, but let me know if we should leave it in and somehow say it’s ignored.
