### ISSUE TITLE
[css-color-adjust-1] Replace `<print-color-adjust>` by `<'print-color-adjust'>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7109]
The [color-adjust](https://drafts.csswg.org/css-color-adjust-1/#propdef-color-adjust) property has `<print-color-adjust>` as its value definition:

> **Name:** `color-adjust`
> **Value:** `<print-color-adjust>`

The `<print-color-adjust>` type does not exist. If it should reference the value definition of the `print-color-adjust` property, I think it should be `<'print-color-adjust'>`. From [CSS Values](https://drafts.csswg.org/css-values-4/#component-types):

> types that have the same range of values as a property bearing the same name (e.g., `<'border-width'>`, `<'background-attachment'>`, etc.). In this case, the type name is the property name (complete with quotes) between the brackets.

**Comment by tabatkins** [comment]
This is written correctly in the source; the display is a Bikeshed bug (now tracked at <https://github.com/tabatkins/bikeshed/issues/2240>). I'll close this issue, since there's nothing to do in the source file.

**Comment by tabatkins** [comment]
Wait, that wasn't true, the markup was indeed bad. Fixed.
