### ISSUE TITLE
[css-shapes-1] Interpolation between rectangular shapes

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#7111]
As part of the object-view-box resolutions, I've added rect() and xywh() functions to `<basic-shape>`. Along with inset(), we now have three ways to specify a rectangle.

Should these be mutually interpolatable? That is, should I be able to interpolate between a rect() and an inset()? You *can* express any of them in terms of the other two, even without layout information, just by using calc() and percentages.

If they are, which function should they become during the interpolation, when they differ? Should we prefer one of the three, or use the starting or ending function?

Precedent in this space are the transform functions, where you can interpolate between things like translateX() and translateY(), or translate() and translate3d(). These have a clear "upgrade" path to a more "complete" version of the function, tho: translate() is more complete than translateX() or translateY(); and translate3d() is more complete than any of those. There isn't a similar hierarchy between the rectangle functions to guide us in a choice, tho.

**Comment by tabatkins** [comment]
The expressions, btw:

Given `inset(t r b l)`, you can equivalent write it as `rect(t calc(100% - r) calc(100% - b) l)` or `xywh(r t calc(100% - r - l) calc(100% - t - b))`.

**Comment by astearns** [comment]
Could we go farther and have `rect()` and `xywh()` compute to `inset()`?

**Comment by tabatkins** [comment]
Sounds reasonable to me.

**Comment by tabatkins** [comment]
Done in 8dfa581ef
