### ISSUE TITLE
[css-grid-2] Clarify interaction between subgrid and position:relative

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#7123]
The current spec says that [subgrid containers should always be stretched](https://drafts.csswg.org/css-grid-2/#subgrid-box-alignment), but doesn't say anything about positioning. It does say that the grid itself should be aligned layout wise with the corresponding section of the parent grid.

If I apply `position:relative` and an offset to a subgrid, what should happen?

Should we offset the subgrid container (thus moving the rendering of the background/border etc) while leaving the grid aligned (such that the grid might be outside of the grid container)? Or should the positioning request be ignored, so that the subgrid container always covers the spanned grid tracks.

**Comment by tabatkins** [comment]
We've gone ahead and clarified this - relpos should just work "as normal", shifting the subgrid and its contents after layout has finished.
