### ISSUE TITLE
[css-grid-2] Clarify interaction between subgrid and position:absolute

### ISSUE THREAD

**Issue by mattwoodrow** [w3c/csswg-drafts#7124]
This is somewhat similar to #7123, except for `position:absolute` instead of `position:relative`.

If a subgrid is `position:absolute` should all `top/left/right/bottom` values be ignored, and we should just stretch and position across the corresponding grid area in the parent? Should we (similar to one option for `relative`) try to respect these as much as possible while still forcing the width/height to the stretched value (if both left and right are set, what's the precedence between each of these and the stretched width?)?

What happens if a `position:absolute` subgrid doesn't cover any grid tracks and only covers the padding area of the parent (`grid-row: auto / 1`)? Should this be listed as an explicit reason that the specified value of `subgrid` isn't applied?

**Comment by tabatkins** [comment]
This was technically [already defined in CSS Display](https://www.w3.org/TR/css-display-3/#independent-formatting-context) (abspos forces an IFC, which turns off subgrid), but we clarified it in Position, and added a reminder in Grid 2.

**Comment by mattwoodrow** [comment]
Ah right, totally missed that, so thanks for adding the reminder.

There are a lot of WPTs testing that `position:absolute` works with subgrid, I'll fix this in WebKit and remove those tests (and add new ones to test that various IFC cases aren't subgrids).

**Comment by tabatkins** [comment]
Ah, thanks, that would be wonderful.
