### ISSUE TITLE
[css-shapes] Should the shape be rounded with shape-outside:padding-box shape-margin:10px?

### ISSUE THREAD

**Issue by wangxianzhu** [w3c/csswg-drafts#7127]
The current spec says: This defines a new shape that is the smallest contour (in the shrink-wrap sense) that includes all the points that are the shape-margin distance outward in the perpendicular direction from a point on the underlying shape.

For
```
<div style="width: 100px; height: 100px; float: left;
                    shape-outside: padding-box; border: 50px solid yellow; shape-margin: 40px"></div>
... a lot of text
```
According to the spec, the div should create a 180x180 rectangle with rounded corners with radius=40.

This picture contains the rendered result with non-rounded rect (in Firefox) or rounded rect (in Chrome content_shell with a patch for https://crbug.com/1305037).
<img width="320" alt="Screen Shot 2022-03-10 at 6 53 32 PM" src="https://user-images.githubusercontent.com/9256729/157647418-2c200244-fb56-4140-9c77-9288fd87e178.png">

I'm not sure which one is better, but the latter conforms to the current spec. WDYT?

**Comment by faceless2** [comment]
![image](https://user-images.githubusercontent.com/989243/157683609-3429020a-ac5d-4531-b6d0-6643ac9f881a.png)

We're rendering the same as Chrome, and I agree that's how it's specified.

**Comment by wangxianzhu** [comment]
The Chrome change (crrev.com/984242) implementing the rounded shape has been landed. The tests in the change has been merged in wpt: https://github.com/web-platform-tests/wpt/pull/33269.
