### ISSUE TITLE
[css-variables] Example 5 use of :root 

### ISSUE THREAD

**Issue by aphillips** [w3c/csswg-drafts#7132]
(See Example 5)
https://www.w3.org/TR/css-variables-1/#defining-variables

> A real-world example of [custom property](https://www.w3.org/TR/css-variables-1/#custom-property) usage is easily separating out strings from where they’re used, to aid in maintenance of internationalization:
```
:root,
:root:lang(en) {--external-link: "external link";}
:root:lang(de) {--external-link: "externer Link";}

a[href^="http"]::after {content: " (" var(--external-link) ")"}
```
> The variable declarations can even be kept in a separate file, to make maintaining the translations simpler.

The example used the `:root` to get at the language of the document rather than the contextual `:lang` value. We (I18N) don't understand why that would be desired?

**Comment by svgeesus** [comment]
@tabatkins it looks like [you added that example](https://github.com/w3c/csswg-drafts/commit/e6e2164fdbe0b00c85a92bccf901e82235944184). I know it was 7 years ago but do you remember your reasoning? There are several examples using `:root`.

**Comment by tabatkins** [comment]
Yes, it came directly from this thread: https://lists.w3.org/Archives/Public/www-style/2014Jun/0208.html

**Comment by svgeesus** [comment]
The example also adds an (English) annotation to links where the document language is unspecified, or is not cevered in the various linguistic alternates in that rule.

**Comment by tabatkins** [comment]
It does, yes. Is that relevant or problematic?

**Comment by svgeesus** [comment]
I'm not the one asking the question. @aphillips said:

> The example used the :root to get at the language of the document rather than the contextual :lang value. We (I18N) don't understand why that would be desired?

**Comment by tabatkins** [comment]
Ah, didn't realize it was being said in that context, sorry.

In theory that (basing the choice on the lang of the element using the variable) could be correct, sure, but it could just as easily be wrong, and I suspect that in the scenario this example is envisioning it would *probably* be wrong - if your page is overall in English, you'd probably want "(External link)" even if it's being added to a link in a blockquote in Chinese.

But there are certainly similar examples one could draw up where the opposite would be true, yeah.

**Comment by svgeesus** [comment]
@aphillips does that answer your question?

**Comment by aphillips** [comment]
@svgeesus @tabatkins Thanks! Yes, it does answer the question.

The `:root` is sometimes problematic (it may not be set to the page language). Of course, contextually localizing the value might equally be wrong: @tabatkins comment is reasonable. Our concern is that examples are often followed blindly out of context. Here this is _only_ an example and our comment is editorial. I could be satisfied with the item as is (you are not writing an I18N primer). Others (@r12a) might have additional feedback?
