### ISSUE TITLE
[css-variables] strengthen advice on string identity

### ISSUE THREAD

**Issue by aphillips** [w3c/csswg-drafts#7133]
Defining Custom Properties: the [--*]() family of properties
https://www.w3.org/TR/css-variables-1/#defining-variables

> Different OSes or input methods can sometimes output visually-identical text with different codepoints, so authors should be aware of this potential hazard.

This relates to this requirement:

> Unlike other CSS properties, custom property names are not [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive). Instead, custom property names are only equal to each other if they are [identical to](https://infra.spec.whatwg.org/#string-is) each other.

In Example 2, the spec calls out that the term *identical to* refers to the underlying Unicode code points. The advice to authors could be stronger here. To the above consider adding guidance such as:

> Operating systems, keyboards, or input methods sometimes encode visually-identical text using different codepoint sequences. Authors are advised to choose variable names that avoid potential confusion or to use escapes and other means to ensure that similar appearing sequences are identical. See [Section 2.3](https://www.w3.org/TR/charmod-norm/#normalizationLimitations) in [CHARMOD-NORM] for examples.

Note also our guidance in our specification developers guide [here](https://www.w3.org/TR/international-specs/#spec_n11n) which includes a prototype note.

**Comment by svgeesus** [comment]
The suggested text has been added.

**Comment by svgeesus** [comment]
Additional example added

```css
	--fijord: red;
	--fĳord: green;
	--ﬁjord: blue;

	.test {
		background-color: var(--fijord);
	}
```

**Comment by Loirooriol** [comment]
BTW, `fijord`, `fĳord` and `ﬁjord` look similar but not identical on my PC, both with the "DejaVu Sans Mono" font in the spec and with "Liberation Mono" here in github.

May be better to use something like `à` (U+00E0) vs `à` (U+0061 U+0300)?

**Comment by svgeesus** [comment]
They don't look identical on mine either; the CSS examle was developed from the example in [Section 2.3](https://www.w3.org/TR/charmod-norm/#normalizationLimitations) of [CHARMOD-NORM](https://www.w3.org/TR/charmod-norm/)
