### ISSUE TITLE
[css-color-4] Allow `none` in all legacy color function syntaxes

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7137]
> [4.3. "Missing"/none Color Components](https://drafts.csswg.org/css-color-4/#missing)
>
> If a color with a [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is serialized or otherwise presented directly to an author, then for [legacy color syntax](https://drafts.csswg.org/css-color-4/#legacy-color-syntax) it represents that component as a zero value

The value definition of legacy `<rgb()>`, `<rgba()>`, `<hsl()>`, and `<hsla()>`, do not allow `none`:

```
rgb() = rgb( <percentage>#{3} , <alpha-value>? ) | rgb( <number>#{3} , <alpha-value>? )
hsl() = hsl( <hue>, <percentage>, <percentage>, <alpha-value>? )
```

I mean, if the intent is to not allow it, I feel like it can be stated explicitly, the same way as it is explicitly stated that a color function does not support legacy color syntax. But I do not see any reason to not allow it though.

**Comment by tabatkins** [comment]
Yes, it's intentional to not support it in the legacy syntaxes; they're maintained for backwards compat but aren't encouraged to be used otherwise.

**Comment by svgeesus** [comment]
Also as functionality is added over time, having to support it in all the various legacy syntaxes as well (with all their varying web-compat issues) would be burdensome for implementers while offering no particular benefit for content authors.

**Comment by svgeesus** [comment]
> if the intent is to not allow it, I feel like it can be stated explicitly

Agreeing that it could be stated explicitly.

**Comment by cdoublev** [comment]
Ok, thank you. 

I hope you will forgive me to not create a new issue for the following question: is there also a reason not to allow `none` for `<alpha-value>` in `<color()>`?

```
color() = color( <colorspace-params> [ / <alpha-value> ]? )
<alpha-value> = <number> | <percentage>
```

Other (non legacy) color values allow it:

```
rgb() = rgb( [<percentage> | none]{3} [ / [<alpha-value> | none] ]? ) | ... )
hsl() = hsl( [<hue> | none] [<percentage> | none] [<percentage> | none] [ / [<alpha-value> | none] ]? )
etc...
```

And while I'm on this `none` topic, please note this redundancy:

```
hsl() = hsl( [<hue> | none] ... )
<hue> = <number> | <angle> | none
```
