### ISSUE TITLE
[css-highlight-api] : support Paint API for background of highlight

### ISSUE THREAD

**Issue by nadavsinai-philips** [w3c/csswg-drafts#7139]
It would be useful to support the CSS [Paint API](https://drafts.css-houdini.org/css-paint-api/)

In our use case in Philips we wanted to use the new CSS highlight API together with the existing (draft) Paint API to be able to create custom ranges and maintain a consistent look for those which is more than color or plain background.

however the CSS Paint API does not seem to work when targeting via the ::highlight() selector

**Comment by tabatkins** [comment]
This is, unfortunately, impossible. The ::highlight pseudos, like other non-tree-abiding pseudos, restrict what properties can be used for styling with them, limiting themselves to a small list whose effects do not accidentally expose the exact node structure created by the pseudo-element.  In other words, if you have some text like `"<em>emphasized</em> text bar"`, and you highlight the text "emphasized", we don't expose whether the pseudo-element acts like it had generated the pseudo-tags *around* or *inside* the `em` element.

The `background-image` property (or any other property that takes an `<image>` value) would allow an author to tell which node structure was used, so we don't allow it. And the Custom Paint API works by having the `paint()` function be a type of `<image>`, so it would have similar issues.
