### ISSUE TITLE
[css-animations-1] Use range notation for `<keyframe-selector>` as a percentage

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7140]
[`<keyframe-selector>`](https://drafts.csswg.org/css-animations-1/#typedef-keyframe-selector) is defined as follows:

> `<keyframe-selector> = from | to | <percentage>`
>
> Values less than 0% or higher than 100% are invalid and cause their `<keyframe-block>` to be ignored.

I think it can be explicitly defined with the [CSS bracketed range notation](https://drafts.csswg.org/css-values-4/#css-bracketed-range-notation).

> `<keyframe-selector> = from | to | <percentage [0,100]>`

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-values-4/#numeric-ranges talks about values in properties, so maybe it should be generalized a bit.

**Comment by cdoublev** [comment]
Oh, that is right. 

Actually, I did not want to create this issue because I have a list of those value definitions that can benefit from the range notation, and my intent was to report them in a single issue, as a reference (task list) for spec editors. It is noted that *at the time of writing, the bracketed range notation is new; thus in most CSS specifications any range limitations are described only in prose.* It just came out of my mind yesterday.

I hope you do not mind me closing this issue for now and recreating it later with a link to your comment on extending usage/definition of the range notation to CSS rules (maybe in Syntax).
