### ISSUE TITLE
[web-animations-1][css-animations-2] Bug in handling of auto-rewind state when playing new CSS animations

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#7145]
[CSS Animations Level 2](https://drafts.csswg.org/css-animations-2/#animation-play-state) describes the handling of `animation-play-state` as follows:

> If at any time, including when the animation is first generated, the resolved value of [animation-play-state](https://drafts.csswg.org/css-animations-1/#propdef-animation-play-state) corresponding to an animation is newly [running](https://drafts.csswg.org/css-animations-1/#valdef-animation-play-state-running), the implementation must run the procedure to [play an animation](https://drafts.csswg.org/web-animations-1/#play-an-animation) for the given animation with the auto-rewind flag set to false.

That is, whether or not a new CSS animation is created _or_ updated, the play procedure is run with the auto-rewind flag set to **false**.

However, if we follow [that procedure](https://drafts.csswg.org/web-animations-1/#play-an-animation) through for a _new_ CSS animation, it won't work:

> ...
> 
> 5. Perform the steps corresponding to the first matching condition from the following, if any:
>   - If animation’s [effective playback rate](https://drafts.csswg.org/web-animations-1/#effective-playback-rate) > 0, the auto-rewind flag is true and either animation’s:
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved), or
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) < zero, or
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) ≥ [associated effect end](https://drafts.csswg.org/web-animations-1/#associated-effect-end),
>       - Set seek time to zero.

At this point _auto-rewind_ is false so we skip this step.

>   - If animation’s [effective playback rate](https://drafts.csswg.org/web-animations-1/#effective-playback-rate) < 0, the auto-rewind flag is true and either animation’s:
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved), or
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) ≤ zero, or
>     - [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) > [associated effect end](https://drafts.csswg.org/web-animations-1/#associated-effect-end),
>       - If [associated effect end](https://drafts.csswg.org/web-animations-1/#associated-effect-end) is positive infinity,
>         - [throw](https://heycam.github.io/webidl/#dfn-throw) an "[InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException) and abort these steps.
>       - Otherwise,
>         - Set seek time to animation’s [associated effect end](https://drafts.csswg.org/web-animations-1/#associated-effect-end).
>   - If animation’s [effective playback rate](https://drafts.csswg.org/web-animations-1/#effective-playback-rate) = 0 and animation’s [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved),
>     - Set seek time to zero.

In fact, none of the steps above match so _seek time_ is still unresolved.

> 6. If seek time is [resolved](https://drafts.csswg.org/web-animations-1/#unresolved),
>   - If has finite timeline is true,
>     1. Set animation’s [start time](https://drafts.csswg.org/web-animations-1/#animation-start-time) to seek time.
>     2. Let animation’s [hold time](https://drafts.csswg.org/web-animations-1/#animation-hold-time) be [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved).
>     3. [Apply any pending playback rate](https://drafts.csswg.org/web-animations-1/#apply-any-pending-playback-rate) on animation.
>   - Otherwise,
>     - Set animation’s [hold time](https://drafts.csswg.org/web-animations-1/#animation-hold-time) to seek time.

Again, _seek time_ is unresolved so we don't set the hold time or start time.

> 7. If animation’s [hold time](https://drafts.csswg.org/web-animations-1/#animation-hold-time) is [resolved](https://drafts.csswg.org/web-animations-1/#unresolved), let its [start time](https://drafts.csswg.org/web-animations-1/#animation-start-time) be unresolved.

_Hold time_ is unresolved so we don't touch the _start time_.

> ...
> 
> 9. If the following four conditions are all satisfied:
>     - animation’s [hold time](https://drafts.csswg.org/web-animations-1/#animation-hold-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved), and
>     - seek time is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved), and
>     - aborted pause is false, and
>     - animation does not have a [pending playback rate](https://drafts.csswg.org/web-animations-1/#pending-playback-rate),
> abort this procedure.

Since all these conditions hold, we end up aborting the procedure.

### Why do browsers work at all then?

For Blink, it looks like it uses a different code path for a _new_ animation vs updating an _existing_ animation

- For a _new_ animation it uses the [`play` method](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/animation/css/css_animations.cc;l=1089;drc=1dff2af6ff82513b605efc7ee00d16c23051fc3d) which does _not_ set _auto-rewind_ to false.
- For an _existing_ animation it uses the [`Unpause` method](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/animation/animation.cc;l=1425;drc=ca12161acfe9f64e1b0d96a6836f07c51d0546b9) which _does_ set _auto-rewind_ to false.

Hence it doesn't hit this issue. I believe @BorisChiou looked into WebKit and found something similar.

Gecko doesn't quite follow the spec correctly for step 5 above and so far hasn't hit this issue but in trying to fix step 5 we ran into it.

### Possible fixes

I think there are at least two possible approaches to fixing this:

1. Make the procedure to play an animation ignore the _auto-rewind_ flag if the current time is unresolved
2. Make CSS Animations level 2 distinguish between playing a new animation vs unpausing an existing animation

I think the first option is cleaner and more intuitive -- if you try to play an animation without a current time, it should play from the start, regardless of whether or not you set _auto-rewind_ to false since it's not rewinding.

I think that would be equivalent to changing the following text from:

> If animation’s [effective playback rate](https://drafts.csswg.org/web-animations-1/#effective-playback-rate) = 0 and animation’s [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved),
> - Set seek time to zero.

to just:

> If animation’s [current time](https://drafts.csswg.org/web-animations-1/#animation-current-time) is [unresolved](https://drafts.csswg.org/web-animations-1/#unresolved),
> - Set seek time to zero.

I wonder what else that might break, though?

**Comment by birtles** [comment]
One possible snag I encountered with this is the procedure to seamlessly update the playback rate sets the _auto-rewind_ flag to false.

This somewhat contradicts the note in the spec that says:

> Note: The auto-rewind flag is provided for other specifications that build on this model but do not require the rewinding behavior, such as CSS Animations

since we are now using the flag internally.

Working this through to see if this would actually produce a change in behavior:

* Firstly, we only trigger the play procedure if the "previous play state" of the animation is running
* If the previous play state is running and the current time is unresolved then presumably this could lead to a change in behavior -- but only if updated playback rate was not zero since the condition is "If animation’s effective playback rate = 0 and animation’s current time is unresolved"

An example of where that might come about is if we have:

```js
const animation = div.animate({ transform: 'translateX(100px)' }, 1000);
animation.cancel();
animation.timeline = null;
animation.startTime = 1;
```

Here the current time is unresolved but the `playState` is running.

To be fair, this is already weird. If we were to call `animation.updatePlaybackRate(1)` at this point, nothing would change, but if we were to call `animation.updatePlaybackRate(0)`, we'd end up with a `currentTime` of 0 and an unresolved `startTime`.

With the proposed change, we'd update the `currentTime` to 0 in _both_ cases which is at least more consistent.

If we decide to follow the approach of updating CSS Animations 2, we should also change the condition:

> If animation’s effective playback rate = 0 and animation’s current time is unresolved,

to:

> If animation’s effective playback rate = 0, and the auto-rewind flag is false, and animation’s current time is unresolved,

to make it more consistent with the other branches (and we could hoist the check for the auto-rewind flag to the parent condition).

**Comment by graouts** [comment]
> Hence it doesn't hit this issue. I believe @BorisChiou looked into WebKit and found something similar.

WebKit runs the _play an animation procedure_ with the _auto-rewind_ set to true when it first plays and when it's resumed.

**Comment by graouts** [comment]
@birtles Do you have some WPT coverage to show some examples that would have previously failed (according to the spec that is)?

**Comment by birtles** [comment]
> > I believe @BorisChiou looked into WebKit and found something similar.
> 
> WebKit runs the _play an animation_ procedure with the _auto-rewind_ set to true when it first plays and when it's resumed.

I think if it were using _auto-rewind_ set to **true** for _resuming_, it would fail the following test:

https://hg.mozilla.org/try/rev/73cd7556994f45c2731b973f3e49c874fd77c4a3#l2.3

but I believe when Boris checked it didn't fail that.

> @birtles Do you have some WPT coverage to show some examples that would have previously failed (according to the spec that is)?

There are a couple of tests in https://hg.mozilla.org/try/rev/73cd7556994f45c2731b973f3e49c874fd77c4a3 but to some extent the changes overlap.

The problem with auto-rewind handling being broken means that if any browser actually implemented both CSS Animations and Web Animations per spec, no CSS animation would ever start. In that sense, every CSS animation test covers this.

I thought we could add a test that demonstrates that calling `updatePlaybackRate(0)` vs `updatePlaybackRate(-1)` now behaves consistently, but I believe that difference only every manifested when `currentTime` was unresolved and now we handle that case specifically which is covered by: https://hg.mozilla.org/try/rev/73cd7556994f45c2731b973f3e49c874fd77c4a3#l3.12

**Comment by graouts** [comment]
> > > I believe @BorisChiou looked into WebKit and found something similar.
> > 
> > 
> > WebKit runs the _play an animation_ procedure with the _auto-rewind_ set to true when it first plays and when it's resumed.
> 
> I think if it were using _auto-rewind_ set to **true** for _resuming_, it would fail the following test:
> 
> https://hg.mozilla.org/try/rev/73cd7556994f45c2731b973f3e49c874fd77c4a3#l2.3

Do you know if this test will be upstreamed to WPT?

**Comment by birtles** [comment]
> > I think if it were using _auto-rewind_ set to **true** for _resuming_, it would fail the following test:
> > https://hg.mozilla.org/try/rev/73cd7556994f45c2731b973f3e49c874fd77c4a3#l2.3
> 
> Do you know if this test will be upstreamed to WPT?

Yes, it will be upstreamed once [bug 1758527](https://bugzilla.mozilla.org/show_bug.cgi?id=1758527) is landed.

**Comment by graouts** [comment]
I'm updating the WebKit implementation to match the updated spec behavior in https://github.com/WebKit/WebKit/pull/5626.
