### ISSUE TITLE
[css-color-5] [cssom-1] Exposure of @color-profile in CSSOM

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#7151]
CSS Color 5 defines an at-rule: https://www.w3.org/TR/css-color-5/#at-profile

It doesn't, however, define how this gets exposed via the CSSOM, which I would expect to be specified. Should it just be exposed as an (apparently abstract) [`CSSRule`](https://www.w3.org/TR/cssom/#the-cssrule-interface), or should it have its own interface? If it does, should it be added as a value `type` can return: https://www.w3.org/TR/cssom/#dom-cssrule-type?

**Comment by svgeesus** [comment]
It should, although [the way we do it for `@font-face`](https://drafts.csswg.org/css-fonts-4/#om-fontface) doesn't seem like a good model. Maybe something like:

 **The CSSColorProfileRule interface**

[[Exposed](https://webidl.spec.whatwg.org/#Exposed)=Window]interface CSSColorProfile : [CSSRule](https://drafts.csswg.org/cssom-1/#cssrule) {
  readonly attribute [CSSOMString](https://drafts.csswg.org/cssom-1/#cssomstring) name ;
  readonly attribute [CSSOMString](https://drafts.csswg.org/cssom-1/#cssomstring) src ;
  readonly attribute [CSSOMString](https://drafts.csswg.org/cssom-1/#cssomstring) rendering-intent ;
  readonly attribute [CSSOMString](https://drafts.csswg.org/cssom-1/#cssomstring) components ;
};

although components would be better as a list?

**Comment by SebastianZ** [comment]
> readonly attribute [CSSOMString](https://drafts.csswg.org/cssom-1/#cssomstring) rendering-intent ;

That should be `renderingIntent`.

Sebastian

**Comment by svgeesus** [comment]
> If it does, should it be added as a value type can return: https://www.w3.org/TR/cssom/#dom-cssrule-type?

We didn't discuss that part of the question. Thoughts?

**Comment by svgeesus** [comment]
Interface has been added.
  https://drafts.csswg.org/css-color-5/#the-csscolorprofilerule-interface

@gsnedders @SebastianZ @tabatkins  Does it all look good, ok to close?

**Comment by tabatkins** [comment]
> I get the impression that the [integer enumerations are deprecated](https://www.w3.org/TR/cssom/#dom-cssrule-type) and so we are not adding new ones. Is that correct or should I add this as 16?

Yes, deprecated. Don't add more. (It'll be `0` if you don't say anything special, from the superclass.)

> Does rule.constructor.name get the name from this interface or do I add it somewhere else and if so, where.

It's automatic - the constructor function (which automatically exists) has a name matching the class itself, and that property is automatically set to match.

-------

Overall the IDL looks fine to me.

**Comment by SebastianZ** [comment]
> @gsnedders @SebastianZ @tabatkins Does it all look good, ok to close?

Yep. Thanks!

Sebastian
