### ISSUE TITLE
Exposure of @container in CSSOM

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#7152]
CSS Contain 3 defines an at-rule: https://www.w3.org/TR/css-contain-3/#container-rule

It doesn't, however, define how this gets exposed via the CSSOM, which I would expect to be specified. Should it just be exposed as an (apparently abstract) [`CSSRule`](https://www.w3.org/TR/cssom/#the-cssrule-interface), or should it have its own interface? If it does, should it be added as a value `type` can return: https://www.w3.org/TR/cssom/#dom-cssrule-type?

**Comment by mirisuzanne** [comment]
This is in the [Editor's Draft](https://drafts.csswg.org/css-contain-3/#the-csscontainerrule-interface), and just needs to be published
