### ISSUE TITLE
Exposure of @font-palette-values in CSSOM

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#7153]
c.f. https://www.w3.org/TR/css-fonts-4/#at-ruledef-font-palette-values

It doesn't, however, define how this gets exposed via the CSSOM, which I would expect to be specified. Should it just be exposed as an (apparently abstract) [`CSSRule`](https://www.w3.org/TR/cssom/#the-cssrule-interface), or should it have its own interface? If it does, should it be added as a value `type` can return: https://www.w3.org/TR/cssom/#dom-cssrule-type?

**Comment by svgeesus** [comment]
This has now been added (some time ago, but I just came across this issue):
 https://drafts.csswg.org/css-fonts-4/Overview.html#om-fontpalettevalues
