### ISSUE TITLE
Should CSSRule.type have a value for CSSPropertyRule?

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#7154]
c.f. https://www.w3.org/TR/css-properties-values-api-1/#csspropertyrule and https://www.w3.org/TR/cssom/#dom-cssrule-type

This seems to have a near complete list of values, but doesn't have one for CSSPropertyRule? If this is deliberate, can we add a note so people in future don't believe it's an error, or can we add it?

**Comment by tabatkins** [comment]
Definitely intentional; see <https://wiki.csswg.org/spec/cssom-constants>

There already *is* a note saying that this attribute is legacy, right at the bottom. Do you want it to say something more?

**Comment by gsnedders** [comment]
> There already _is_ a note saying that this attribute is legacy, right at the bottom. Do you want it to say something more?

Be explicit that no new values will be added, and that any implementer introducing support for a new CSSRule should not introduce a new return value there.

While it's clear that it's deprecated, it wouldn't be unprecedented for something like that to continue to have new items added, especially by anyone unaware of the history.

**Comment by tabatkins** [comment]
Done.

**Comment by gsnedders** [comment]
👍
