### ISSUE TITLE
[css-contain-3] style() and :visited

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#7156]
What happens when you try to query a computed value affected by :visited?

E.g.:
```
<a href="">
  <span>Foo</span>
</a>

a {
  display: block;
  container-type: style;
}

a:visited {
  background-color: pink;
}

@container style(background-color: pink) {
  span {
    --visited:true;
  }
}

// gCS(span)[--visited] must not be true
```

Doing the "gCS returns the unvisited situation"-hack is entirely unrealistic in this case. Evaluating against the unvisited background-color is also not a good idea, since we ultimately want to remove the concept of "unvisited alternate reality". Until we fix :visited, we probably need some reasonable stop-gap solution where the query just fails.

**Comment by fantasai** [comment]
Why do we not want to return the unvisited styles?

**Comment by emilio** [comment]
I was going to ask the same as @fantasai fwiw, but she was faster as usual :)

**Comment by andruud** [comment]
There was an ambition[1] to make :visited a normal pseudo-class and _remove_ the hacky "alternate unvisited reality", maintaining privacy through other means. In that world we don't want a special-case which requires unvisited styles to still exist, I think.

[1] Not sure about the status there, cc @tabatkins

**Comment by tabatkins** [comment]
That's still on the back-burner until someone has time to pursue the "path-directed visitedness" idea in code, but I think it would be fine to handle :visited in the current "lie about it" way and then change over if/when we get to that point. (We'll be changing the *rest* of the OM's results about this case, after all.)

**Comment by lilles** [comment]
Style queries are computed style queries, so I'd expect them to lie like getComputedStyle() does.

**Comment by mirisuzanne** [comment]
@andruud Can this be closed as question-answered?
