### ISSUE TITLE
[css-overflow-4][css-overflow-3] What is with scrollbar-gutter and overlay scrollbars now?

### ISSUE THREAD

**Issue by karl-police** [w3c/csswg-drafts#7161]
This goes back to the issue https://github.com/w3c/csswg-drafts/issues/6090

It's about these **classic** and **overlay** scrollbars.

I think ``scrollbar-gutter`` has been implemented into Google Chrome and Firefox, however I am not sure if someone said that ``scrollbar-gutter`` could be used to preserve these overlay scrollbars, but it doesn't seem to be the case, without having ``overflow: overlay``

However, I see people that say, that ``overflow: overlay`` would force people to set their overflow to overlay inorder to have overlay scrollbars. I mean, I guess this is not wrong, however this doesn't solve the fact that there's nothing for scrollbars to overlay over an overflow or something.

``scrollbar-gutter: none`` doesn't exist and was discussed here once https://github.com/w3c/csswg-drafts/issues/4501, and instead someone said that it would be ``scrollbar-gutter: stable`` but I think that's not doing anything noticable either, in combination with any overflow value. Except ``overflow: hidden`` there it shows the "gutter" but no scrollbar.

``scrollbar-width`` doesn't allow numbers apparently. I can't do something like ``10px``.

Reading through this https://drafts.csswg.org/css-overflow-3/#overlay-scrollbars talks about overlay scrollbars, and that a gutter apparently can be removed, but I don't think that's working.

So what's with overlay scrollbars now?

&nbsp;

I am not sure if the browsers implemented it wrongly. I don't even know where an actual working CSS Environment test browser where all features are implemented properly can be found at.

**Comment by karl-police** [comment]
Hm.

Or can there be a scrollbar-gutter: overlay?

**Comment by tabatkins** [comment]
scrollbar-gutter has no inherent connection to overlay scrollbars, and isn't intended to influence any browser's decisions to expose or not expose overlay scrollbars controls.

That said, I'm not actually sure what you're asking about in this issue. Could you restate your question?

**Comment by karl-police** [comment]
> scrollbar-gutter has no inherent connection to overlay scrollbars, and isn't intended to influence any browser's decisions to expose or not expose overlay scrollbars controls.
> 
> That said, I'm not actually sure what you're asking about in this issue. Could you restate your question?

How to make overlay scrollbars without overflow overlay?

**Comment by Maximaximum** [comment]
Yeah, it's kinda ridiculous we still don't have a way to force overlay scrollbars in 2023 😕

**Comment by tabatkins** [comment]
We have browsers explicitly rejecting the ability to force a scrollbar to be overlay. We're not missing this functionality by accident.

(I personally disagree with this, but specs can't force behavior, only help align behavior that implementors agree with.)

**Comment by tophf** [comment]
> We have browsers explicitly rejecting the ability to force a scrollbar to be overlay

Isn't their stance pointless since the page author can draw the overlay scrollbars via JS?
