### ISSUE TITLE
[cssom] getComputedStyle(elm, '::selection') works in WebKit, Blink

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#717]
https://drafts.csswg.org/cssom/#dom-window-getcomputedstyle

The spec only supports ::before and ::after pseudo-elements in this API. WebKit and Blink also support ::selection.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4666

(WebKit needs the timeout, which seems like a bug.)

Gecko/IE/Edge do not support this. (As far as I can tell Edge doesn't support ::selection at all, but IE9..11 does?)

Should Gecko and Edge add ::selection here? Or should WebKit and Blink drop it?

cc @rune-opera

**Comment by FremyCompany** [comment]
Merging with #2149
