### ISSUE TITLE
[css-will-change-1] Republish

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7177]
Will-Change was last published [in 2015 as a CR](http://www.w3.org/TR/2015/CR-css-will-change-1-20151203/). There have been [a few edits](https://github.com/w3c/csswg-drafts/commits/main/css-will-change-1/Overview.bs) since then, mostly generic "affects all specs" type of edits. 

WPT has [174 tests](https://wpt.fyi/results/css/css-will-change?label=experimental&label=master&aligned) with okay interop.

Is this specification still under development and still has implementer interest? Should it be republished as a CRD or should it even go back to WD until there is interest?

**Comment by tabatkins** [comment]
I don't understand what you mean by "until there is interest" - it's widely implemented.

**Comment by svgeesus** [comment]
Okay so it should be republished, then

**Comment by svgeesus** [comment]
Agenda+ to discuss republishing soon as a CRD, then doing the wide review dance in preparation for a CR Snapshot
