### ISSUE TITLE
[css-contain] container-type: block-size referenced on the property syntax, but not defined

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7179]
https://andreubotella.com/csswg-auto-build/css-contain-3/#container-type

Still has `block-size` and `size`, but `block-size` is not defined, should it be there?

Also, if both should be there, presumably `container-type: size` is just an alias for `container-type: block-size inline-size`, right?

**Comment by mirisuzanne** [comment]
That's been removed, it was an accidental hold-over from a previous draft.
