### ISSUE TITLE
[css-contain] Do container names really need to be deduplicated, but only at computed-value time?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7181]
If we take https://andreubotella.com/csswg-auto-build/css-contain-3/#container-name to the letter, the specified value would need to have duplicates, but the computed value wouldn't.

I don't think we have many precedents for such a thing, is there any reason the container-name can't just rename as specified?

Also, if it _needs_ to be deduplicated for some reason, why not doing it at parse time?

cc @mirisuzanne @andruud

**Comment by emilio** [comment]
It seems that Safari's implementation is not deduplicating the identifiers looking at https://wpt.fyi/results/css/css-contain/container-queries/container-name-computed.html, which makes sense to me.

**Comment by andruud** [comment]
> I don't think we have many precedents for such a thing

No precedent for deduplicating computed-value time, or deduplicating in general? Either way should do whatever there's precedent for.

**Comment by mirisuzanne** [comment]
I don't think I have any particular concerns about how or when or even if the property is deduplicated, if the primary effect is the same - duplicate names have no impact. I'm not opposed to making a change here if the spec text can be improved.

**Comment by lilles** [comment]
We went through a similar discussion for color-scheme and ended up not de-duplicating for computed value (issue #3848).

**Comment by mirisuzanne** [comment]
Since this has no impact on the expected behavior for authors, I'm happy to accept it. @astearns I'm not sure if we need a resolution here, or if we can mark this as accepted by editor discretion?

**Comment by astearns** [comment]
I am happy with editor discretion to follow precedent here. If anyone has concerns they can bring them up here or open a new issue.
