### ISSUE TITLE
[css-contain] The interaction between containment on the HTML element, and overflow propagation is insufficiently specified

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#7184]
The note at https://www.w3.org/TR/css-overflow-3/#overflow-propagation says "Using [containment](https://www.w3.org/TR/css-contain-1/#containment) disables this special handling of the HTML [body](https://html.spec.whatwg.org/multipage/sections.html#the-body-element) element."

However, it doesn't say which element `containment` is being applied to in this scenario; it might be the `body` or the `html`.

So the behavior of this scenario isn't very clear:
```
html { contain: layout; }
body { overflow: hidden; }
```

Does `overflow:hidden` propagation from the body to the viewport, or does `containment` on the `html` prevent that propagation?

Test case at https://jsfiddle.net/qj9v0h2t/

**Comment by frivoal** [comment]
It needs republishing, but css-contain-1 gives details at https://drafts.csswg.org/css-contain-1/#c3

> Additionally, when the [used value](https://drafts.csswg.org/css-cascade-5/#used-value) of the [contain](https://drafts.csswg.org/css-contain-1/#propdef-contain) property on either the HTML [html](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element) or [body](https://html.spec.whatwg.org/multipage/sections.html#the-body-element) elements is anything other than [none](https://drafts.csswg.org/css-contain-1/#valdef-contain-none), propagation of properties from the [body](https://html.spec.whatwg.org/multipage/sections.html#the-body-element) element to the [initial containing block](https://drafts.csswg.org/css-display-3/#initial-containing-block), the viewport, or the [canvas background](https://drafts.csswg.org/css-backgrounds-3/#canvas-background), is disabled. Notably, this affects:
> 
> *    [writing-mode](https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode), [direction](https://drafts.csswg.org/css-writing-modes-3/#propdef-direction), and [text-orientation](https://drafts.csswg.org/css-writing-modes-4/#propdef-text-orientation) (see [CSS Writing Modes 3 § 8 The Principal Writing Mode](https://drafts.csswg.org/css-writing-modes-3/#principal-flow))
> 
> *    [overflow](https://drafts.csswg.org/css-overflow-3/#propdef-overflow) and its longhands (see [CSS Overflow 3 § 3.5 Overflow Viewport Propagation](https://drafts.csswg.org/css-overflow-3/#overflow-propagation))
> 
> *    [background](https://drafts.csswg.org/css-backgrounds-3/#propdef-background) and its longhands (see [CSS Backgrounds 3 § 2.11.2 The Canvas Background and the HTML <body> Element](https://drafts.csswg.org/css-backgrounds-3/#body-background))
> 
> Note: Propagation to the [initial containing block](https://drafts.csswg.org/css-display-3/#initial-containing-block), the viewport, or the [canvas background](https://drafts.csswg.org/css-backgrounds-3/#canvas-background), of properties set on the [html](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element) element itself is unaffected.

css-overflow-3, on the other hand, could be clearer.
