### ISSUE TITLE
[css-contain-3] .conditionText and name vs query

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7190]
`.conditionText` is a single string, but there are two parts to the container query: the container name, and the query against it. Both of these form the condition of the rule, but it might be useful to have them represented independently in the API.

Suggestion: `.conditionText` is the entirety of the preamble, add `.containerName` and `.containerQuery` to represent the container name and query independently in the CSSContainerRule interface and the ContainerQueryList interface.

**Comment by mirisuzanne** [comment]
Since we never got official resolution on the existing API (see #7033) I think we should be able to resolve on both at once, potentially?

**Comment by mirisuzanne** [comment]
I think it would be good to get a resolution on this, and merge @andruud's PR if we can.

@atanassov if there's any space in the agenda…

**Comment by SebastianZ** [comment]
For what it's worth, @emilio already [implemented `.containerName` and `.containerQuery`](https://bugzilla.mozilla.org/show_bug.cgi?id=1787173) for Gecko a few days ago.

Sebastian

**Comment by lilles** [comment]
Edits were made in https://github.com/w3c/csswg-drafts/pull/7293

**Comment by lilles** [comment]
Basic tests for containerName and containerQuery in https://wpt.live/css/css-contain/container-queries/idlharness.html
