### ISSUE TITLE
[mediaqueries-3] Spelling issue on 7.1

### ISSUE THREAD

**Issue by chrislachance** [w3c/csswg-drafts#7198]
Small spelling issue on 7.1 Section 3

Seems as though "characterize" is spelled incorrectly.

https://www.w3.org/TR/2022/REC-mediaqueries-3-20220405/#changes-2012

**Comment by frivoal** [comment]
fixed in the editor's draft. @svgeesus can you do an in-place update to propagate that change to the published version?

**Comment by svgeesus** [comment]
Yes, there is _just_ enough time to do that ...  done
