### ISSUE TITLE
Replace "Animatable" with "Animation type"

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#72]
As discussed: https://lists.w3.org/Archives/Public/www-style/2015Oct/0226.html (item 8)

This will probably involve editing all the CSS specs that use this line and updating terms in CSS transitions too.

**Comment by birtles** [comment]
Need to be careful to mark the 'display' attribute as having 'Animation type: none' when doing this. See [Mozilla bug 1264396](https://bugzilla.mozilla.org/show_bug.cgi?id=1264396) for some background.

**Comment by xfq** [comment]
Related: #3198

**Comment by birtles** [comment]
As pointed out by @xfq this has been done in #3198 and others.
