### ISSUE TITLE
[css-values] Make slashes implicitly omissible like commas

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#7200]
For commas in values there is a [definition that says that they are implicitly omissible](https://drafts.csswg.org/css-values-4/#comb-comma) when

* all items preceding the comma have been omitted
* all items following the comma have been omitted
* multiple commas would be adjacent (ignoring white space/comments), due to the items between the commas being omitted.

I believe the same logic should apply to slashes within values.

One explicit case for that is currently discussed in #7142.

Sebastian

**Comment by tabatkins** [comment]
No, this is impossible - the slash is absolutely required in several properties already to avoid ambiguity. In particular, 'font' requires it to distinguish a font-size from a line-height, and 'border-image' requires it to distinguish all four of its longhand components.

**Comment by SebastianZ** [comment]
This change wouldn't touch existing syntaxes because they don't allow leading or trailing slashes nor multiple subsequent slashes without values in between them.

`font` requires `<'font-size'>` to be set at the left side of the slash and `<'line-height'>` on the right side. `border-image` requires either `<'border-image-source'>` or `<'border-image-slice'>` on the left and `<'border-image-width'>` and `<'border-image-outset'>` on the right side.
I.e. in those cases the slash is required and the rules mentioned above do not apply.

Sebastian

**Comment by tabatkins** [comment]
Nope, border-image allows syntax like `0 // 0` (slice and outset specified, width unspecified between them), which would run afoul of the "two commas next to each other" rule.

I misremembered 'font' - the font-size is indeed always required, so the `/ <'line-height'>` wouldn't run afoul of these rules.

Regardless, tho, border-image has an irreconcilable conflict.

**Comment by SebastianZ** [comment]
Oh, you're right. 😞 I misinterpreted the syntax of `border-image` and didn't realize that `0 // 0` is valid.

Though the main point why I came up with this idea was to avoid leading or trailing slashes in values. I'll open a related issue to discuss that.

Sebastian
