### ISSUE TITLE
[css-contain-3] Make container-type:auto the initial value?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#7202]
It's not clear [if/when style queries are going to happen](https://github.com/w3c/csswg-drafts/issues/7185), and there was an intent to [make size queries shippable without style queries](https://github.com/w3c/csswg-drafts/issues/7020#issuecomment-1040817609).

Given that, is `container-type:style` the best initial value? We can't implement a property without support for its initial value, so in order to ship separately we'd need to pick some other _non-standard_ initial value. We can also not _pretend_ to support `container-type:style`, since that breaks `@supports` etc.

Maybe we can make `auto` the initial value, and specify that behaves like `style`? We'd still pretend to support `auto` I suppose, but at least authors would be able to do `@supports(container-type: style)`. Also we'd be able to note in the spec that `auto` can behave like `none` if style queries are not supported.

**Comment by SebastianZ** [comment]
Duplicate of #7066?

Sebastian

**Comment by andruud** [comment]
Not quite, the proposed initial value `auto` would still effectively mean `style` if it's supported. This is just so that we can violate the spec somewhat gracefully while shipping things gradually.

But yes, if we revert on style-by-default (https://github.com/w3c/csswg-drafts/issues/7066), then we can close this as well.

**Comment by SebastianZ** [comment]
I mean, both issues are directly connected with each other. If style queries are completely deferred to a later spec. then `style` cannot be the default value. Though so far it seems like they might stay but be restricted to custom properties.

I didn't follow the discussion about why `style` is the default and not `none`. Choosing `auto` and internally resolving it to `style` or `none` depending on whether style queries are supported sounds reasonable to me, though.

Sebastian

**Comment by SebastianZ** [comment]
Reading through the discussions, with `auto` as initial value we'd still have the issue with values like `size` making the element not a style container anymore.

Sebastian

**Comment by andruud** [comment]
Not relevant anymore since `style` will not be the initial value per #7066. Closing.
