### ISSUE TITLE
[css-sizing][css-contain] Are intrinsic sizing keywords definite with size containment?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7206]
https://andreubotella.com/csswg-auto-build/css-sizing-3/#definite

> A size that can be determined without performing layout

So if I have something like

```html
<div style="height: auto; contain: size; border: solid">
  <div style="height: 50%; background: cyan;">a</div>
</div>
<br><br>
<div style="height: auto; contain: size; contain-intrinsic-size: 100px; border: solid">
  <div style="height: 50%; background: cyan;">a</div>
</div>
```

Should the inner elements resolve `50%` to `0px` and `50px`?

Browsers seem to treat the percentage as [cyclic](https://andreubotella.com/csswg-auto-build/css-sizing-3/#cyclic-percentage-size) so it behaves as `auto`, i.e. they don't consider the parent's `height: auto` as definite. But we can determine the size without performing layout.

https://andreubotella.com/csswg-auto-build/css-contain-2/#sizing-as-if-empty

> The [used](https://andreubotella.com/csswg-auto-build/css-cascade-5/#used-value) [width](https://andreubotella.com/csswg-auto-build/css-sizing-3/#propdef-width) and [height](https://andreubotella.com/csswg-auto-build/css-sizing-3/#propdef-height) of the [containment box](https://andreubotella.com/csswg-auto-build/css-contain-2/#size-containment-box) are determined as if performing a normal layout of the box, except that it is treated as having no content

Does this mean that no content is marked as having a cyclic percentage?

https://andreubotella.com/csswg-auto-build/css-contain-2/#laying-out-in-place

> The [containment box](https://andreubotella.com/csswg-auto-build/css-contain-2/#size-containment-box)'s content (including any pseudo-elements) must then be laid out into the now fixed-size containment box normally.

Does "fixed-size" mean that it's definite?

**Comment by frivoal** [comment]
My intuition would be that `contain: size` should indeed make the size definite, since as you said, it can be determined without layout. Do we want to go with that, or is there a reason to handle this as if there was a cyclic percentage, even though there isn't really a cycle?

**Comment by Loirooriol** [comment]
Maybe add a note in https://drafts.csswg.org/css-sizing-3/#indefinite along these lines:

> Note: intrinsic sizing keywords such as `max-content` are indefinite, even if they can be determined without laying out the children e.g. due to size containment or lack of children.
