### ISSUE TITLE
[css-align][css-grid] Inconsistence on  Baseline Alignment terminology for orthogonal flows

### ISSUE THREAD

**Issue by javifernandez** [w3c/csswg-drafts#721]
The CSS Box Alignment spec states the following when defining the Baseline-sharing group:

https://drafts.csswg.org/css-align/#baseline-terms
> A baseline-sharing group is composed of boxes that participate in baseline alignment together. This is possible only if they
> 
> * share an alignment context whose axis is parallel to their inline axis
> * either have the same block flow direction and baseline alignment preference, or have opposite block flow direction and opposite baseline alignment preference (in other words, the baselines that want to align are on the same side of the alignment context).

Then, in the Section 8.3 Aligning Boxes by Baseline it's stated the following:

https://drafts.csswg.org/css-align/#align-by-baseline
> Given a set of boxes and their baselines that all belong to a single baseline-sharing group, the boxes are baseline-aligned as follows:

Hence, when applying this to a Grid box, we can align the grid items by baseline only if they belong to the same baseline-sharing group. This implies that they share an alignment context whose axis is parallel to their inline axis.

Said this, I want to refer to the already closed issue #373 where it was resolved that orthogonal grid items should synthesize their baseline from their border-box. Let's assume an horizontal grid container with some vertical grid items. Does this resolution imply that we should use such synthesized baseline to align those orthogonal items along the grid's row-axis ? I assume that we can align those orthogonal items align the grid's column axis, but for that case there is no need to synthesize a baseline.

As an example of the issue I'm trying to describe, consider the following grid vs inline-block cases:

```
.row { grid-auto-flow: columns; }
<div class="grid row itemsBaseline"><span>A</span><span class="verticalLR">A</span><span>A</span><span class="verticalLR">A</span></div>

.item { display: inline-block; }
<div><div class="item">A</div><div class="item verticalLR">A</div><div class="item">A</div><div class="item verticalLR">A</div></div>
```

This is the output using both, Chrome (implementation in progress) and Firefox nightly:

![baseline-orthogonal](https://cloud.githubusercontent.com/assets/2230241/20369721/f58f9f78-ac5a-11e6-8d0f-360569139358.png)

**Comment by fantasai** [comment]
> Does this resolution imply that we should use such synthesized baseline to align those orthogonal items along the grid's row-axis ?

Yes, that's the intent.

Though now I'm realizing this doesn't play nice with a mix of first and last baseline items with opposing writing modes! Given vertical-lr items with both first and last baseline alignment, and vertical-rl items with both first and last baseline alignment, to which set do the horizontal-tb items align? @_@ It doesn't have a concept of "first" or "last" in that axis. I suppose we can borrow the writing mode of the item's container (i.e. the grid).

But does that mean we should do that for all writing modes, kindof like we use the parent's writing mode to determine start/end already? (Note, opposing writing modes are an extremely rare case. Orthogonal ones are more common. Though I wouldn't put it past some designer to put opposing vertical writing modes together in a horizontal-script document.)

**Comment by javifernandez** [comment]
> > Does this resolution imply that we should use such synthesized baseline to align those orthogonal items along the grid's row-axis ?
> 
> Yes, that's the intent.

But isn't that intention contradicting the fact that grid items can only be baseline aligned if they belong to the same sharing-group ? What kind of sharing-group those 2 orthogonal items belong to ? Those don't  share an alignment context whose axis is parallel to their inline axis, since they are located in a different column (the axis parallel to their inline-axis).

**Comment by fantasai** [comment]
I think what you just said is a clearer restatement of my own confusion. :) In order to effect the WG resolution, we need to assign them to a baseline-sharing group.

I'm not really convinced the resulting behavior is useful, and I'm not sure what would be. It is merely the most consistent with what happens in inline layout.

**Comment by fantasai** [comment]
Okay, I checked in some changes to address this using my best recollection of what the WG resolved. :) Let me know if it makes sense yet. https://github.com/w3c/csswg-drafts/commit/32792998144d31de4470a783893f1f960b038e6c

**Comment by javifernandez** [comment]
Hi,

On 11/26/2016 02:28 AM, fantasai wrote:
> Okay, I checked in some changes to address this using my best
> recollection of what the WG resolved. :) Let me know if it makes sense
> yet. 3279299
> <https://github.com/w3c/csswg-drafts/commit/32792998144d31de4470a783893f1f960b038e6c>
> 

I'm not sure whether I'm the best one to judge if it makes sense or not,
but it's definitively clearer and consistent with what inline-block does
managing orthogonal flow elements. In
my opinion, the new text is what we need to address these cases.

**Comment by javifernandez** [comment]
On 11/26/2016 02:28 AM, fantasai wrote:
> Okay, I checked in some changes to address this using my best
> recollection of what the WG resolved. :) Let me know if it makes sense
> yet. 3279299
> <https://github.com/w3c/csswg-drafts/commit/32792998144d31de4470a783893f1f960b038e6c>
> 

After analyzing the changes and trying to implement them I've got some additional doubts, 
let's see if we can clarify them with an example. 

> A baseline-sharing group is composed of boxes that participate in baseline alignment together. This is possible only if they
> 
>     * Share an alignment context along an axis perpendicular to their baseline alignment axis.
>     * Have compatible baseline alignment preferences (i.e., the baselines that want to align are on the same side of the alignment context). 

1- What does "baseline alignment axis" exactly mean ? Is it perhaps the grid axis an alignment property with a <baseline-position> value applies to ?  (column-axis in case of align-self and row-axis in case of justify-self)

2- Given that my assumption on the issue 1 is correct, let's consider the following example:

```
<div style="display: grid; align-items: baseline; justify-items: baseline; grid-auto-flow: column;>
    <div style="writing-mode: vertical-lr">A</div>
    <div style="writing-mode: vertical-lr">A</div>
    <div style="writing-mode: vertical-lr">A</div>
    <div style="writing-mode: vertical-lr">A</div>    
</div>
```

The 4 grid items should be baseline-aligned in both row and column axis. In the case of the justify-self baseline, they don't share an alignment context along the column-axis (perpendicular to the one justify-self applies to) since they are all placed in different columns. In the case of the align-self baseline (which operates along the columns-axis), all the grid items share the same alignment context along the row-axis  (1st row), hence they can be baseline aligned together. Since they are orthogonal to the alignment context, we need to synthesize a baseline; per resolution on issue #373 we should use the item's margin-box. The result will be something similar to the picture shown as follows:

![synthesized-orthogonal-baselines](https://cloud.githubusercontent.com/assets/2230241/20809446/62092a14-b806-11e6-9fe5-9facc095a44d.png)

**Comment by MatsPalmgren** [comment]
> ... we should use the item's margin-box

No, when synthesizing a baseline for a grid item the border-box should be used, not the margin-box. See
https://github.com/w3c/csswg-drafts/issues/373#issuecomment-244829198

Other than that, I support the idea to baseline-align these items using a synthesized baseline, because baseline-alignment is what the author specified.  I have filed https://bugzilla.mozilla.org/show_bug.cgi?id=1321655 to fix this in Gecko.

**Comment by javifernandez** [comment]
> No, when synthesizing a baseline for a grid item the border-box should be used, not the margin-box. 
> See #373 (comment)

Yes, sorry, I made a mistake. It's indeed the border-box.

**Comment by javifernandez** [comment]
In the sentence:

https://drafts.csswg.org/css-align-3/#baseline-terms
> For this purpose, boxes that establish an orthogonal flow are treated as having the same block flow direction as their alignment context, 

I think the term "orthogonal flow" is not correct, or at least not accurate. As I understand the concept of baseline-sharing group, it's a group of elements in the same row/column whit "equivalent" writing-mode/preference" **between themselves**. In an horizontal grid container, a column with N vertical
elements, they will belong to different sharing-groups depending in their block-flow (LR vs RL) direction, and of course their respective baseline precedence. Anyway, the issue is that they are all orthogonal but they don't have the same block-flow direction.

Is perhaps that what matters is whether they are orthogonal to their alignment-context ? It's worth mentioning that for the case of grid this is specially confusing, since the term writing-mode hardly applies to a grid-row/column. It d be, perhaps, better to define this sharing-group concept based on the
baseline axis instead of the alignment-context ?

**Comment by tabatkins** [comment]
> I think the term "orthogonal flow" is not correct, or at least not accurate.

Yeah, on review @fantasai and I think you're right - it's not about being orthogonal (vertical items align just fine with each other in a grid *column*), it's about being orthogonal to the axis that's trying to baseline-align.  We've fixed up the language there, let us know if there's anything wrong.

**Comment by javifernandez** [comment]
The text makes more sense now, thanks.
