### ISSUE TITLE
[css-mediaqueries] Should prefers-color-scheme in SVG images be context-dependent?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7213]
Consider this test-case:

```html
<!doctype html>
<div style="color-scheme: light">
  <img>
</div>
<div style="color-scheme: dark">
  <img>
</div>
<script>
  for (let img of document.querySelectorAll("img")) {
    img.src = "data:image/svg+xml;base64," + btoa(`
      <svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
        <style>
          :root { color: blue }
          @media (prefers-color-scheme: dark) {
            :root { color: purple }
          }
        </style>
        <rect fill="currentColor" width="32" height="32"/>
      </svg>
    `);
  }
</script>
```

Right now the rendering of those images match in all browsers, but one could argue that perhaps they should render differently (top blue, bottom purple)?

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1764354, which is what prompted this discussion.

cc @lilles @smfr

**Comment by emilio** [comment]
cc #6988 which is somewhat related.

**Comment by tabatkins** [comment]
Yeah, so basically you're asking if the used color scheme should automatically inherit into nested documents. That's a communication bit, which we try to avoid adding for cross-origin stuff, at least.

(#6988 would allow passing the color-scheme in purposely, if both the outer and inner page successfully handshaked.)

**Comment by emilio** [comment]
Right. My reasoning for doing this for SVG images is that they cannot run script, etc, so it's a much more limited environment. But I guess you're right that they could trigger different image loads to exfiltrate that bit, potentially.

For the record, Gecko does inherit the color scheme into some frames (so that e.g., extension setting popups behave correctly if you have a dark Firefox theme but a light content theme). This is not exposed to regular `<iframe>`s on websites, though.

**Comment by lilles** [comment]
The comment: https://github.com/w3c/csswg-drafts/issues/7213#issuecomment-1099501969 confused me a bit since @emilio's example affects the preferred color-scheme, not the used color-scheme or color-scheme property directly.

This is about changing the preferred color-scheme in the SVG and the SVG root color-scheme would not be affected in another way than through the preferred color-scheme, right?

**Comment by emilio** [comment]
Yeah, that's right.

**Comment by emilio** [comment]
Bringing this up again because I was working on this in https://bugzilla.mozilla.org/show_bug.cgi?id=1738380, and I realized that there's no way to guarantee a transparent background of an iframe without hard-coding the color-scheme.

That is: an iframe with `<meta name="color-scheme" content="light dark">` that ideally has both light and dark mode, can be guaranteed to be transparent, if e.g. the user prefers dark theme but it's embedded on a light page.

That's a bit unfortunate, there's a variety of regressions from my work that would ideally be fixed by just having `<meta name="color-scheme" content="light dark">` (like https://bugzilla.mozilla.org/show_bug.cgi?id=1771047 / https://bugzilla.mozilla.org/show_bug.cgi?id=1772168), but which instead have to coordinate between embedder and embedee.

@smfr / @lilles / @tabatkins, is there any chance you could ping some of the WebKit / Blink security folks about this (since that's the major concern here)? I'll do the same for Mozilla's security folks, but my guess is that since the relevant information is already in the target process, it's not really a big leak...

**Comment by heycam** [comment]
Would this affect SVG images used as CSS `<image>` values too?

**Comment by emilio** [comment]
Probably?

**Comment by smfr** [comment]
> But I guess you're right that they could trigger different image loads to exfiltrate that bit

It looks like no browser allows an SVG image to load subresources, so maybe this isn't a problem?

**Comment by tabatkins** [comment]
All right, embedded SVG text added to MQ5. Left a note about us still discussing this for iframes.

**Comment by emilio** [comment]
We resolved for iframes in https://github.com/w3c/csswg-drafts/issues/7493 didn't we?

**Comment by tabatkins** [comment]
Ah, we did! Thanks, I'll fix it up then.

**Comment by bramus** [comment]
Closing this issue as the necessary edits have made it in. Added the necessary labels to https://github.com/w3c/csswg-drafts/issues/7493, which is concerned with the behavior for iframes.
