### ISSUE TITLE
[css-ui-4] appearance-disabling property origins

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7215]
This is an issue against a detail of the text in https://github.com/w3c/csswg-drafts/pull/6537

> Let |authorProps| be a [=map=] of all properties that have a <a>cascaded value</a> for |element|, where the [=Author Origin=], [=Animation Origin=] and [=Transition Origin=] [=Cascade Origins=] are included and the [=User Origin=] and [=UA Origin=] [=cascade origins=] are ignored, where the key is the property name and the value is that <a>cascaded value</a>.

I don't think it makes sense to include the Transition Origin here. A declaration can only exist in the Transition Origin if there is a related declaration in another origin, as it represents the transition between two declarations outside the Transition Origin. So first, I assert that the Transition Origin doesn't need to be inspected. And second, suppose we were to adopt this spec text and the UA defined a rule like input:focus:hover { border-color: orange; } and gave it a 1s transition. Then for the 1s transition, we'd need to treat the element as having `appearance: none`... which would be absurd.

I think it should be sufficient to inspect the Author Origin and Animation Origin only. And maybe only the Author Origin, as I doubt there's content out there relying on animation rules disabling native `appearance`.

CC @zcorpan @emilio

**Comment by zcorpan** [comment]
cc @andruud @lilles

I see this test http://wpt.live/css/css-ui/appearance-transition.tentative.html which references https://bugs.chromium.org/p/chromium/issues/detail?id=1086732

If I understand correctly, the current chromium behavior is to *not* include the transition and animation origins, but also while a transition or animation is active they don't change whether an author-origin declaration is present. Correct?

**Comment by andruud** [comment]
@zcorpan Yes, a property only counts as "author-styled" if the cascaded value has author origin, and only exactly that origin.

**Comment by zcorpan** [comment]
Thanks, submitted https://github.com/w3c/csswg-drafts/pull/7230

**Comment by zcorpan** [comment]
There was an open PR to test the animation and transition origins at https://github.com/web-platform-tests/wpt/pull/25439
