### ISSUE TITLE
[cssom-view] Remove `trackAriaHidden` from `isVisible`

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#7232]
In https://github.com/w3c/csswg-drafts/issues/6850 `isVisible` was added and it includes a `trackAriaHidden` option. When implementing this in chromium, [I got feedback](https://chromium-review.googlesource.com/c/chromium/src/+/3547516/1..3/third_party/blink/renderer/core/dom/element.cc#b7338) that computing aria hidden correctly requires enabling the accessibility tree and that it shouldn't be done in a method from script like this.

I believe that we should remove `trackAriaHidden` from the options.

cc @tabatkins @chrishtr @vmpstr

**Comment by chrishtr** [comment]
I agree, for this reason and also because accessibility tools teams have told us this feature is not so useful for their use cases.

**Comment by tabatkins** [comment]
Done.
