### ISSUE TITLE
[css-overflow-4] Publish an updated WD

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#7236]
There have been [some changes](https://github.com/w3c/csswg-drafts/commits/main/css-overflow-4/Overview.bs) to the spec since FPWD, but we have never published any update since. Should we publish an updated draft?

**Comment by svgeesus** [comment]
{Published 31 Dec 2022](https://www.w3.org/TR/2022/WD-css-overflow-4-20221231/)
