### ISSUE TITLE
[css-grid] Clarify "Automatic repetitions cannot be combined with intrinsic or flexible sizes"

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7238]
https://drafts.csswg.org/css-grid/#repeat-syntax

> Automatic repetitions ([auto-fill](https://drafts.csswg.org/css-grid/#valdef-repeat-auto-fill) or [auto-fit](https://drafts.csswg.org/css-grid/#valdef-repeat-auto-fit)) cannot be combined with [intrinsic](https://drafts.csswg.org/css-grid/#intrinsic-sizing-function) or [flexible](https://drafts.csswg.org/css-grid/#flexible-sizing-function) sizes.

Effectively, these are false:

```js
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) auto"); // false
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) min-content"); // false
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) max-content"); // false
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) fit-content(0px)"); // false
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) 1fr"); // false
```

However, these are true:

```js
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(1px, auto)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(auto, 1px)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(1px, min-content)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(min-content, 1px)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(1px, max-content)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(max-content, 1px)"); // true
CSS.supports("grid-template-rows: repeat(auto-fill, 1px) minmax(1px, 1fr)"); // true
```

Tested in Blink, Gecko and WebKit.

So I guess the spec should make it clear that these combinations are fine. Basically, it seems the requirement is that for each track, at least one of the min/max track sizing functions should be fixed.

**Comment by tabatkins** [comment]
Okay, clarified the text slightly, and explicitly referred to the grammar for details on what it means. Let us know if this works?

**Comment by Loirooriol** [comment]
Maybe replace "flexible" with "intrinsic flexible"? Since `minmax(1px, 1fr)` is fine.

**Comment by tabatkins** [comment]
No, "flexible" is covered by the "fully", same as "intrinsic", implying the same "at least one argument is fixed".

**Comment by Loirooriol** [comment]
Wouldn't "fully flexible" mean `minmax(1fr, 1fr)` that is invalid right now but there is some issue to add it in the future?

Basically, I don't see how "fully flexible" includes `minamx(auto, 1fr)` but excludes `minmax(1px, 1fr)`.

**Comment by fantasai** [comment]
@Loirooriol In English, "or" is not necessarily exclusive.

**Comment by Loirooriol** [comment]
@fantasai Are you implying that `minmax(auto, 1fr)` is both fully intrinsic and fully flexible?

**Comment by tabatkins** [comment]
No, it's fully "intrinsic or flexible".

**Comment by tabatkins** [comment]
(The point of all this, tho, is that the text is purposely suggestive, not precise, and the grammar is the actual definition of the restriction.)

**Comment by Loirooriol** [comment]
Mm, OK, I see what you mean, seems a misleading wording to me but it defers to the grammar which is clear.
