### ISSUE TITLE
[scroll-animations-1] Rethinking timeline-phase

### ISSUE THREAD

**Issue by kevers-google** [w3c/csswg-drafts#7240]
At present, timelines have a before, active, and after phase, which can be confused with animation-effect phases.  The before and after timeline-phases are exclusive to scroll-timelines. We could consider restricting the phases to active and inactive and simply allow timeline.currentTime to be outside the bounds of 0 to 100%.  Doing so, may also alleviate some of the special casing that is performed when computing the phase of an animation-effect.  A negative value for current time, regardless of units, would naturally result in the animation-effect phase being 'before' (assuming zero delay).  Conversely, a value after effect end (100% for a progress-based animation) would result in an animation-effect's phase being 'after'.  The special casing can be limited to what happens at the effect boundary, where it is conditionally exclusive with a time-based timeline and inclusive with a scroll-timeline.

**Comment by flackr** [comment]
Thanks for filing this! The timeline phase has added considerable complexity (and a somewhat confusing relation to animation phase) to the spec. In particular it needs to be involved in the animation phase calculations and properly held when we pause animations.

I agree that we can dramatically simplify the state logic in the spec by simply allowing time values to extend beyond the 0 to 100% range. As an additional consequence / feature, this would allow using a negative start / end delay to extend an animation beyond the normal range of a an intersection based timeline (e.g. ViewTimeline).

@birtles is there any reason having time values go outside of this range would be problematic?

**Comment by flackr** [comment]
I believe #2066 was the prior discussion that led to adding timeline phases. It's not clear to me that at the time we considered and rejected simply having the timeline extend beyond its scrollable range. The inactive timeline phase is special, however it also produces an unresolved currentTime so it will also not apply animated effects: https://drafts.csswg.org/web-animations-1/#timeline-timeline-inactive-phase

**Comment by birtles** [comment]
> @birtles is there any reason having time values go outside of this range would be problematic?

I'm afraid I can't remember the full context of this discussion but I can't think of any particular issues at this point.

**Comment by flackr** [comment]
It looks like `phase` was added to the [AnimationTimeline interface](https://www.w3.org/TR/web-animations-1/#the-animationtimeline-interface) but no browser currently exposes it ([demo](https://jsbin.com/diqirib/edit?js,output)).

I propose we remove `phase` from the interface, and remove the before and after phases (which were only used by scroll timelines) replacing them by allowing the current time to progress beyond 0 or 100% which would implicitly put the animation in the correct phase.

**Comment by fantasai** [comment]
Edited in. @birtles I renamed active/inactive to “states”, to avoid conflicting with the possible future named phases we're thinking of introducing in #7044. Lmk if the edits look OK to you and @flackr, and if so I'll publish an update to /TR.

**Comment by birtles** [comment]
> Edited in. @birtles I renamed active/inactive to “states”, to avoid conflicting with the possible future named phases we're thinking of introducing in #7044. Lmk if the edits look OK to you and @flackr, and if so I'll publish an update to /TR.

Sure, dropping the timeline phases seems fine. That would bring the spec closer to its previous state: https://www.w3.org/TR/2018/WD-web-animations-1-20181011/#inactive-timeline where we had a concept of an "inactive timeline" but didn't have a "timeline state" concept. In fact, what do you think about simply reverting that text to how it originally was?

(For what it's worth, I'm still hoping we don't use "phase" in #7044 😉)

**Comment by fantasai** [comment]
@birtles Saw your edits in 2d8763d101dfb1e7bfd736158734f92d3481da2d and updated Scroll Animations to match in https://github.com/w3c/csswg-drafts/commit/26396b1afa5cb462e12e59a2818b677a02a89c8b

@kevers-google Would you consider this issue resolved? Should we close it?

**Comment by kevers-google** [comment]
Yes, I would consider this resolved.

**Comment by birtles** [comment]
> @birtles Saw your edits in [2d8763d](https://github.com/w3c/csswg-drafts/commit/2d8763d101dfb1e7bfd736158734f92d3481da2d) and updated Scroll Animations to match in [26396b1](https://github.com/w3c/csswg-drafts/commit/26396b1afa5cb462e12e59a2818b677a02a89c8b)

Thanks!
