### ISSUE TITLE
[css-overflow] overflow-clip-margin might want to set different boxes in the block and inline axes.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7245]
cc @chrishtr @khushalsagar

Gecko has a property similar to `overflow-clip-margin` called `overflow-clip-box` (actually a pair of properties, `overflow-clip-box-{block,inline}`), which we use to implement some of the form control magic that `<input>` and `<textarea>` need for compat (like clipping to the padding box in one edge but to the content-box in another).

It seems like it'd be nice if you could specify the margin in a per-axis basis? We can support the extension internally to remove the Gecko-internal property, perhaps, but if we need it maybe authors need it as well.

If we do this I don't have a strong opinion on whether we should make `overflow-clip-margin` a shorthand or two different longhands.

**Comment by chrishtr** [comment]
+1 to supporting per-axis.

**Comment by Loirooriol** [comment]
If different axes may want different clip margins, different sides may want that too?

**Comment by vmpstr** [comment]
When the property was introduced, we considered adding all of the directions as longhands but decided to add just the one for simplicity: https://github.com/w3c/csswg-drafts/issues/4934#issuecomment-629492599

I think per side makes sense to be consistent with other margin-like things

**Comment by emilio** [comment]
The reason why I think per-axis might be sensible is that `overflow` itself is per-axis, but I guess per-side would also make sense.

**Comment by fantasai** [comment]
We can also start with per-axis and expand to per-side later if there's demand.

**Comment by fantasai** [comment]
If block/inline is what's wanted we can just add those longhands and keep the shorthand as only capable of accepting one value. Then we can expand it out later once we figure out the whole situation with logical/physical shorthands.

**Comment by frivoal** [comment]
Thanks for the edits, looks good to me. Closing.

**Comment by frivoal** [comment]
Looks good to me, except that I think it'd be worth having the ability to use two lengths in the `-inline` and `-block` shorthands.
