### ISSUE TITLE
[css-values-3] 4.3 Real numbers incorrectly summarizes allowed values

### ISSUE THREAD

**Issue by tshinnic** [w3c/csswg-drafts#7248]
Once again I was trying to find the definition for SVG real numbers and the chain of refs led me to CSS Syntax. Specifically I was trying to find the 'rightness' of an emitted "9e-5" or "-1e-4".

Referred to section [4.3. Real Numbers: the &lt;number> type](https://www.w3.org/TR/css3-values/#numbers) from the SVG spec, I followed the &lt;number-token> link to CSS-Syntax-3. Finding the [familiar railroad diagram](https://www.w3.org/TR/css-syntax-3/#number-token-diagram) I was reassured that "9e-5" *was* legal. 

But then when I returned to CSS Values and read the description of valid values, it seems to only allow "1.0e1" and not "1e1". The prose *requires* a '.' decimal point in order to specify an exponent.

Or... was "and optionally an exponent" supposed to *also* apply to the much earlier "an integer"? As written this section seems very ambiguous to this easily-shaken reader.

**Comment by Gutodotado24** [comment]
@@ -1534,17 +1611,17 @@ var gCSSProperties = {
 		other_values: [ "1px", "2em", "5%" ],
 		invalid_values: [ ]
 	},
 	"marker-offset": {
 		domProp: "markerOffset",
 		inherited: false,
 		type: CSS_TYPE_LONGHAND,
 		initial_values: [ "auto" ],
-		other_values: [ "6em", "-1px" ],
+		other_values: [ "6em", "-1px", "-moz-calc(0px)", "-moz-calc(3em + 2px - 4px)", "-moz-calc(-2em)" ],
