### ISSUE TITLE
[css-text-3] Make U+0000 invisible?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7249]
In https://github.com/w3c/csswg-drafts/pull/6983 @litherum writes:

> Chrome and Firefox make it invisible, and WebKit has compat issues about it.
> https://bugs.webkit.org/show_bug.cgi?id=235559

See discussion in that pull request. Opening this issue to track the discussion and

* confirm implementation plans for handling control characters generally
* figure out what we want to do about U+0000 specifically
* figure out if we need any kind of coordinated release of these behaviors

**Comment by jfkthame** [comment]
> Chrome and Firefox make it invisible

To clarify a bit: Chrome (if I understand correctly) just passes the codepoint through to the current font, so it may be invisible or render as tofu depending on the font in use.

Firefox makes it invisible in Release/Beta versions, as the `layout.css.control-characters.visible` setting defaults to `false`, but renders it as a hexbox glyph in Nightly builds as the pref defaults to `true` there. (See https://searchfox.org/mozilla-central/rev/4274cdc16531e42b061d3091e0d146a62ff63b9b/modules/libpref/init/StaticPrefList.yaml#7516-7521.)

I don't think there is any compelling reason to treat U+0000 any differently from other "spurious" control characters; they should all be rendered visible, as per CSS WG resolution. Depending on the current font (as Chrome currently does) is not a robust implementation approach.
