### ISSUE TITLE
[css-color-4] Should premultiplied undefined alpha make other color components undefined?

### ISSUE THREAD

**Issue by facelessuser** [w3c/csswg-drafts#7253]
Reading over the spec, it seems that if the alpha component is `none`, that all the associated color components will also become `none`. This seems unintuitive (at least to me). To me, it would seem that premultiplication should not be performed if alpha is `none`:

```py
>>> Color('color(srgb 1 0 0 / 0.5)').mix('color(srgb 0 0 1 / none)', space='srgb')
color(srgb 0.5 0 0.5 / 0.5)
>>> Color('color(srgb 1 0 0 / 0.5)').mix('color(srgb 0 0 1 / none)', space='srgb', premultiplied=True)
color(srgb 1 0 0 / 0.5)
```

I guess, what I expected to happen was for it to behave as if premultiplied was disabled, because how can you premultiply if you don't know by what to premultiply? This would just take alpha out of the calculation.

```py
>>> Color('color(srgb 1 0 0 / 0.5)').mix('color(srgb 0 0 1 / none)', space='srgb')
color(srgb 0.5 0 1 / 0.5)
>>> Color('color(srgb 1 0 0 / 0.5)').mix('color(srgb 0 0 1 / none)', space='srgb', premultiplied=True)
color(srgb 0.5 0 1 / 0.5)
```

There may be reasons for this, but I am curious if there is something driving this decision, or if maybe it just wasn't considered.

**Comment by svgeesus** [comment]
Alpha being `none` was forgotten about for premultiplication.

> If any component value is [none](https://drafts.csswg.org/css-color-4/#valdef-color-none), the premultiplied value is also none.

That is referring to the color components only, not the alpha. However, we didn't forget for un-premultiplication, if alpha was 0:

> If the alpha value is zero, the un-premultiplied value is the premultiplied value

So I propose to fix that, in premultiplication:

If the alpha value is `none`, the premultiplied value is the un-premultiplied value

and in un-premultiplication:

If the alpha value is zero or `none`, the un-premultiplied value is the premultiplied value

**Comment by facelessuser** [comment]
That sounds great to me!
