### ISSUE TITLE
[css-backgrounds] Specify exact pixel values for border-width: thin, medium, thick

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#7254]
See this Twitter thread: https://twitter.com/tabatkins/status/1522261879762014223

Since browsers agree on 1px, 3px and 5px for border-width: thin, medium, and thick, respectively, it seems to me the spec could require this mapping for all UAs.

cc @tabatkins @bfgeek

**Comment by tabatkins** [comment]
I suspect the current undefinedness was one of those things where browsers didn't agree when we were nailing down 2.1 and we weren't sure they could agree by our deadline.

**Comment by fantasai** [comment]
I think it was intentionally left UA-defined, just like the various font-size keywords. My suggestion would be to put “For Web compatibility, it is recommended that these keywords be mapped to 1px, 3px, and 5px, respectively.” or somesuch.
