### ISSUE TITLE
[cssom-view] step 6 of isVisible() isn't clear

### ISSUE THREAD

**Issue by smaug----** [w3c/csswg-drafts#7256]
"If the [checkVisibilityCSS](https://drafts.csswg.org/cssom-view/#dom-isvisibleoptions-checkvisibilitycss) dictionary member of options is true, and this is invisible, return false."
What does 'invisible' mean? Does it mean the element has been scrolled out of the viewport? Does it mean it has visibility: hidden? or perhaps something else?

https://drafts.csswg.org/cssom-view/#dom-element-isvisible

**Comment by tabatkins** [comment]
That is meant to be a link! Let me see what's wrong with it.

**Comment by josepharhar** [comment]
> Does it mean it has visibility: hidden?

Yes, it's just a check to see if the element which isVisible was called on has a `visibility` value of `visible`: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/element.cc;l=7896-7899;drc=fee93d03eae30739adf15d4bfa29afe22490a94b

**Comment by tabatkins** [comment]
Okay, the link was ambiguous; fixed now. Thanks for the catch!
