### ISSUE TITLE
[css-values] Should trigonometric functions work outside of `calc`?

### ISSUE THREAD

**Issue by Antonio-Laguna** [w3c/csswg-drafts#7265]
Hey there!

I've been reading [the spec for trigonometric functions](https://www.w3.org/TR/css-values-4/#trig-funcs) to implement them on PostCSS Preset Env.

From reading the spec it's not clear that functions shouldn't work only on `calc()`. `pi` and `e` for example have a special note:

> Note: These keywords are only usable within a calculation, such as calc(pow(e, pi) - pi), or min(pi, 5, e). If used outside of a calculation, they’re treated like any other keyword: animation-name: pi; refers to an animation named "pi"; line-height: e; is invalid (not similar to line-height: 2.7, but line-height: calc(e); is).

Webkit's implementation only allows to use inverse trigonometric outside of `calc` since they resolve to `deg` however, even if odd, should it be possible to do `line-height: sin(45deg)` given that it resolves to `.707`?

**Comment by tabatkins** [comment]
Correct, all the math functions resolve to whatever their types are defined as, and are usable anywhere that accepts those types. Your 'line-height' example is perfectly valid per spec; if WebKit isn't allowing that, it's a bug in their implementation.
