### ISSUE TITLE
[cssom-view] isVisible inert option

### ISSUE THREAD

**Issue by josepharhar** [w3c/csswg-drafts#7274]
It was brought up [here](https://github.com/mozilla/standards-positions/issues/634#issuecomment-1119376413) that the inert option of isVisible doesn't really have anything to do with visibility, so perhaps it should be removed from isVisible: https://drafts.csswg.org/cssom-view/#dom-isvisibleoptions-checkinert

cc @chrishtr @tabatkins @vmpstr @smaug----

**Comment by Loirooriol** [comment]
It's a bit of a stretch, but in Blink inert is like `aria-hidden` for accessibility purposes. So it would be checking the visibility for users who use assistive technologies like screen readers? Though if we want that, it should probably check for both `aria-hidden` and inertness, not just the latter.

**Comment by vmpstr** [comment]
Since this is a new API, I propose that we limit the dictionary of options to things that are definitely visibility related. It's easier to then add more options rather than remove questionable options later.

**Comment by josepharhar** [comment]
@tabatkins would you mind removing the checkInert option from the spec? It looks like it's still up here: https://drafts.csswg.org/cssom-view/#dom-isvisibleoptions-checkinert
