### ISSUE TITLE
[selectors] [css-conditional] Detecting :has() restrictions

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7280]
Multiple implementations want to ship the `:has()` selector with a variety of limitations in order to prevent performance footguns and complexity:

  * https://github.com/w3c/csswg-drafts/issues/6399
  * https://github.com/w3c/csswg-drafts/issues/6952
  * https://github.com/w3c/csswg-drafts/issues/7211
  * https://github.com/w3c/csswg-drafts/issues/7212

However, since `:has()` has forgiving parsing like `:is()` / `:where()`, it's not possible to detect these limitations easily, and it won't be possible to do so if we ever remove these limitations.

For `:is()` / `:where()` it's not a problem since it's generally assumed that if the selector is valid outside of them it'll be valid inside of them... But for the limitations that folks are imposing on `:has()` (and which for the record I agree with) this is not true.

Perhaps we should special-case `@supports selector(..)` to _not_ use forgiving parsing? Otherwise the only way to potentially detect this is with script (by reading back the serialization of `:has()` and see if the relevant selectors have been dropped).

cc @byung-woo @anttijk

**Comment by byung-woo** [comment]
> Perhaps we should special-case `@supports selector(..)` to not use forgiving parsing?

I think this is a good way to detect the limitations without losing the benefits of forgiving parsing.

Currently, pseudo-elements are explicitly disallowed inside `:is()` (https://drafts.csswg.org/selectors-4/#matches).

If `@supports` can detect the limitation inside logical combinations, I think we can provides more clear limitation in wpt, something like:
```
@supports selector(:is(::first-letter)) {
 #supports_first_letter_inside_is { color: red }
}
@supports selector(:has(:host)) {
 #supports_host_inside_has { color: red }
}
```

How about others?

**Comment by svgeesus** [comment]
It looks like this would affect [at-supports-046.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-conditional/at-supports-046.html) which assumes forgiving parsing?

**Comment by fantasai** [comment]
@svgeesus No, that test is fine. This is for the contents of the `selector()` function.
