### ISSUE TITLE
[css-anchor-1] Introduce CSS Anchor Positioning

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#7282]
This is a placeholder issue to introduce CSS Anchor Positioning to the CSSWG.

Explainer: https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md
See - https://tabatkins.github.io/specs/css-anchor-position/ for a rough overview of the current thinking.

**Comment by FremyCompany** [comment]
Honestly, I feel like the current API is too complex. 
The "basic" use case requires dozens of lines of code, I'm not sure this makes sense.

You have to do lots of math to do basic behaviors like anchoring always to the bottom right of the anchor without fallback.

**Comment by FremyCompany** [comment]
I am not sure also how this API handles multiple popups that could overlap each other. But maybe that should be a separate issue?
