### ISSUE TITLE
[css-text-decor-4] Clarify thickness constraints

### ISSUE THREAD

**Issue by tcaptan-cr** [w3c/csswg-drafts#7283]
The current thickness constraints for [length](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-thickness-length) and [percentage](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-thickness-percentage) state that 
> The UA must floor the actual value at one device pixel.

This could be confusing and interpreted as performing a `floor` on the actual calculated value, while it is actually rounded to the nearest integer, with a minimum value of one.
Equivalent to: `x = min(1, round(x))`

**Comment by progers** [comment]
@tcaptan-cr found that we now have interop where Firefox, Safari, and Chrome (patch landing now) round the value, rather than flooring. Can the spec be updated to say something like "round to the nearest positive integer"?

**Comment by yisibl** [comment]
If `text-decoration-thickness = 0`, theoretically it shouldn't display an underline, right? 

But currently Chrome and Firefox displays an underline that is less than 1px in size.

```html
data:text/html;charset=UTF-8,
<style>
.test {
   font-family: sans-serif;
   font-size: 50px;
   text-decoration-thickness: 0;
}
</style>
<div class="test" style="text-decoration-line: underline;">text-decoration</div>
<div class="test" style="text-decoration-line: overline;">text-decoration</div>
<div class="test" style="text-decoration-line: line-through;">text-decoration</div>
```

<img width="810" height="456" alt="Image" src="https://github.com/user-attachments/assets/4c511692-4245-422c-a932-2b8c707e954e" />

**Comment by progers** [comment]
@yisibl , the spec resolution here was to floor the actual value at one device pixel.
