### ISSUE TITLE
[css-sizing-4] Section „Percentage Sizing“ is empty

### ISSUE THREAD

**Issue by fabb** [w3c/csswg-drafts#7298]
The section „Percentage Sizing“ is empty, just contains the text „…“:

https://github.com/w3c/csswg-drafts/blob/main/css-sizing-4/Overview.bs#L967

**Comment by Loirooriol** [comment]
It's not the only empty section, it's diff spec over Level 3

https://github.com/w3c/csswg-drafts/blob/9936abdd00b8015434713114e31a55d178b0ab70/css-sizing-4/Overview.bs#L42-L45
