### ISSUE TITLE
[css-text-4] Replace `<length-percentages>` by `<length-percentage>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7301]
The `word-spacing` property is [defined to accept `<length-percentages>` as a value](https://drafts.csswg.org/css-text-4/#valdef-word-spacing-length-percentages). I think it should be `<length-percentage>`, as defined for the *value* field in its definition table.

> **Value:** `normal | <length-percentage>`

> `<length-percentages>` Specifies extra spacing in addition to the intrinsic inter-word spacing defined by the font.

**Comment by SaarthakMaini** [comment]
I think the corresponding issue has already been resolved

**Comment by cdoublev** [comment]
https://github.com/w3c/csswg-drafts/blob/096d87df0d204853f532d19a21d1868f9f456be7/css-text-4/Overview.bs#L7277

**Comment by SaarthakMaini** [comment]
Hello, 
I created a pull request regarding the same but I am getting error checks.
My contribution is non-substantive, so how can my contribution get accepted?
Thank you!

**Comment by fantasai** [comment]
@SaarthakMaini With admin privileges. :) I'm not sure how to do it properly, but anyway it's merged. Thanks for reporting (and fixing) the error. ^_^
