### ISSUE TITLE
[mediaqueries-5] Move the definition of "display mode" back to Manifest spec

### ISSUE THREAD

**Issue by mgiuca** [w3c/csswg-drafts#7306]
(Attn: @frivoal @marcoscaceres )

In #6343, two sections of the Web App Manifest spec were moved into the CSS Media Queries 5 spec:

* "Display modes"
* "The `'display-mode'` media feature"

The resulting negative diff on Manifest can be seen here: https://github.com/w3c/manifest/pull/1022/files

I believe the first of these moves was a mistake and would like to move the "display modes" section back to Manifest where it belongs. Moving the "The `'display-mode'` media feature" section to CSSMQ was correct.

(Apologies that I've just noticed this now. It happened in December as I was planning to go on leave and I have been absent since then.)

**Background**

This started from an off-hand comment by @marcoscaceres in https://github.com/w3c/manifest/issues/975:

> While the CSS crew is here, somewhat unrelated, but related, could we move "display mode media feature" to MQ5?

I believe the intention here was to move *just* the "display mode media feature" to MQ5 (which is correct). However what ended up happening was that *both* the "display modes" and "display mode media feature" section got moved. Essentially, the "display mode media feature" was "remotely" injecting new content into the CSS spec, and I believe the intention was always to move it into CSS when it was ready. But I think moving the entire definition of "display mode" was a mistake.

**Proposal**

Move the "display modes" section (including the definition of the four display modes: browser, minimal-ui, standalone and fullscreen) back to the Manifest spec.

Keep the "The `'display-mode'` media feature" section in the CSSMQ spec, referencing the definition of "display mode" in the Manifest spec.

**Rationale**

The "display mode" section, which defines [display mode](https://www.w3.org/TR/mediaqueries-5/#display-mode) and provides the definition of the four display modes (browser, minimal-ui, standalone and fullscreen) is one of the core concepts of the web app manifest. The Web App Manifest spec is concerned with what it means to be a web app, and largely this revolves around being displayed in a non-browser display mode.

The Web App Manifest spec defines the `"display"` member which can be one of the four display modes, and allows the web app to control which display mode it should be presented in. So far, this is all self-contained within the Manifest spec and has nothing to do with CSS whatsoever. The definition of the display modes is critical to the manifest spec (hence the phrase appears 30 times in the spec).

In addition to this, we defined the `display-mode` CSS media query, which allows pages to query which app display mode they are in. While this is a useful feature, it is ancillary. We could delete the display-mode media query and the entire web app system would continue to function, albeit it would be harder for pages to determine which mode they're in.

Having the entire definition of "display mode" be in the CSS spec makes no sense, because it is a manifest concept that happens to have a CSS media query associated with it, not a CSS concept that happens to be referenced by the manifest spec. It doesn't make sense that the Manifest spec defines the "`display`" member by saying "see the CSS spec".

My practical concerns over this are that it will unnecessarily complicate future discussions around display modes. We (Manifest authors) have plans to add at least two new display modes ([tabbed mode](https://github.com/w3c/manifest/issues/737) and [window controls overlay](https://github.com/WICG/window-controls-overlay/blob/main/explainer.md)), and those discussions should take place in the Web Apps WG, around the Manifest spec. We should not be discussing proposals about new Web App functionality in the CSSWG.

**Comment by mgiuca** [comment]
Created pull requests on both sides to resolve this:

* https://github.com/w3c/csswg-drafts/pull/7307
* https://github.com/w3c/manifest/pull/1039

Before landing either, both should be approved, and there maybe should be a more deliberate lockstep than just landing both at the same time.

@alancutter FYI

**Comment by marcoscaceres** [comment]
I agree, we should move the definitions back into manifest for the reasons that @mgiuca outlines above.

**Comment by ewilligers** [comment]
A couple of proposals involving new display mode values:
https://wicg.github.io/window-controls-overlay/#addition-of-new-window-controls-overlay-display-mode
https://github.com/WICG/manifest-incubations/blob/gh-pages/tabbed-mode-explainer.md
Standards discussions for these will occur in the WebApps WG.

**Comment by mgiuca** [comment]
Thanks for discussing this at the CSSWG.

It looks as though the main issue is that the "fullscreen" display mode media query applies when an ordinary browser page is in fullscreen mode, irrespective of what the manifest says, and therefore it should be described here as well. I will take it on to try and reword it so that this fullscreen logic is fully described in CSS so you don't have to read manifest to learn that. But I still want the core definitions of what these display modes mean to move back to Manifest, since they are the core concept being defined by the manifest spec.

I will update these PRs.

Would it be possible to resolve this on GitHub without further resolution at the CSSWG? The WG meetings seem to happen at inconvenient times for both myself and @ewilligers so it would be good if we can resolve this offline.

**Comment by frivoal** [comment]
@mgiuca If you do want to attend a CSS meeting, and it's merely a matter of inconvenient time, note that we do have an APAC timed call. The next one is on January 5, 0:00 UTC.

But we can certainly try and iterate here as well. I have been a little short on time recently to come up with an edited PR myself, but if you find time to do it, I'm happy to review.

**Comment by frivoal** [comment]
@mgiuca the CSSWG was expecting to review a PR from the Web App Manifest WG to see how much of this you were planning to move back to the Manifest spec, so that we could discuss and iterate from there. Is that your understanding as well? Should we set up a meeting of some kind to discuss it? Are you expecting us to make a proposal?

**Comment by frivoal** [comment]
(ping @marcoscaceres)

**Comment by mgiuca** [comment]
Thanks for checking in @frivoal . I was considering the ball to be in my court on this, I have just had a lot of things going on and this wasn't a top priority for me. Sorry for not making that clear. Still planning to get to it and I think it's important that we eventually have this text in the right place.

**Comment by mgiuca** [comment]
Hi @frivoal 

Just checking if you saw my update to [#7307](https://github.com/w3c/csswg-drafts/pull/7307#issuecomment-1818372599). If you want to discuss this in a CSS-WG session, could it be scheduled. Otherwise I would like to proceed to merge this (and the [counterpart PR on the Manifest side](https://github.com/w3c/manifest/pull/1039)).

**Comment by mgiuca** [comment]
Thank you so much @grorg !
