### ISSUE TITLE
[css-fonts-4] confusing text re: the `font-family` descriptor in `@font-palette-values`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#7308]
The text at https://drafts.csswg.org/css-fonts-4/#font-family-2-desc seems confusing to me:

> This descriptor defines the font family name that this palette applies to. This palette will only ever be applied to the font with this name. The value of this descriptor matches the definition of the [`<family-name>`](https://drafts.csswg.org/css-fonts-4/#family-name-value) for the ['font-family'](https://drafts.csswg.org/css-fonts-4/#propdef-font-family) property. This means that only named font families are allowed and rules that including generic or installed fonts in the list of font families are syntax errors. If syntax errors occur within the font family list, the entire rule must be ignored.

Two issues with this:

(a) The first two sentences make it sound like the descriptor expects a **single** font family name. But the last two sentences refer to the "list of font families" / "font family list". Which is it? Can an author write a single `@font-palette-values` rule that applies to a list of font families, or must each family be addressed by a separate rule?

(b) If the value of this descriptor "matches the definition of the [`<family-name>`](https://drafts.csswg.org/css-fonts-4/#family-name-value) for the ['font-family'](https://drafts.csswg.org/css-fonts-4/#propdef-font-family) property", then it can presumably be the family name of either an installed font or a family defined by `@font-face` rules. But then the text says that "rules that includ[e] generic _or installed_ fonts in the list of font families are syntax errors". So can `@font-palette-values` be used to address an installed font by family name (e.g. "Segoe UI Emoji" on Windows), or is that an error?

I think the answers I'd like to see would be that (a) the `font-family` descriptor accepts a list of font family names, and (b) these may include installed fonts as well as webfonts (i.e. only generics would be excluded). But it's unclear to me what the spec is currently trying to say about these questions.

**Comment by jfkthame** [comment]
Aha - I notice that Example 82 includes this:
```
h3 {
  font-family: Bixxxa, Bungeehee;
  font-palette: --ToxicGreen;
}
```
which suggests that the answer to my question (a) is that a font family *list* is allowed. In that case, I think what needs to happen is for the first few sentences of the text to be made plural.

**Comment by svgeesus** [comment]
Hopefully [fixed by this edit](https://github.com/w3c/csswg-drafts/issues/6916#issuecomment-1240684141)
