### ISSUE TITLE
[css-fonts-4] Should `font-variant-emoji` be included in the `font-variant` shorthand?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#7315]
The spec text for the [`font-variant` property](https://drafts.csswg.org/css-fonts-4/#font-variant-prop) says that it

> is a shorthand for all font-variant subproperties

and its value syntax *almost* reflects this.

However, it does not include the keywords `auto | text | emoji | unicode` that would be the possible values of [`font-variant-emoji`](https://drafts.csswg.org/css-fonts-4/#font-variant-emoji-prop) as specified in the Color Font Support section of the spec.

Is this an accidental omission that should simply be added to the `font-variant` values, or is `font-variant-emoji` *not* supposed to be a subproperty of `font-variant`, despite its name?

My current opinion: the `-emoji` values should be supported by the `font-variant` shorthand; they don't clash with values of any of the other subproperties, and I think authors would naturally assume this should work.

However, this does raise the point that all the other `font-variant` subproperties have the initial value `normal`, so that it's very natural for `font-variant: normal` to set them all to their initial values of the same name. But `font-variant-emoji` is currently specified to have initial value `auto`, and has no `normal`. It would still be possible for `font-variant: normal` to reset it to its initial value (`auto`), but this suddenly seems less intuitive. So I wonder if we should rename this value to `normal` for consistency with the other `font-variant-*` subproperties? (As far as I'm aware, no-one has yet shipped support for `font-variant-emoji`, so renaming the value should be possible without compatibility concerns.)

**Comment by jfkthame** [comment]
Pinging @litherum @svgeesus @nattokirai as editors of Fonts 4 ... was this just an editorial oversight, or is it an issue that needs a CSSWG discussion to sort out?

**Comment by svgeesus** [comment]
I believe this was an oversight, we forgot to update it.

I think renaming `auto` to `normal` as you suggest makes sense, but would like to hear from others.

**Comment by svgeesus** [comment]
I agree with @jfkthame that from an authoring point of view it is consistent with the other font-variant properties and thus, the renaming that happened was correct.

I therefore think it should be included in the shorthand, and reset when the shorthand is used.

I also (still) think we should `auto` -> `normal` for consistency.

**Comment by svgeesus** [comment]
> used to be named something like emoji-presentation (but got renamed to its current name).

> I don’t know why it got renamed to its current name.

It used to be called `font-presentation` and was changed because that name sucked. This was the issue where we changed it

 - https://github.com/w3c/csswg-drafts/issues/1092

**Comment by svgeesus** [comment]
> I believe this was an oversight, we forgot to update it.

Indeed, the [previous CSS WG discussion where we changed the name](https://github.com/w3c/csswg-drafts/issues/1092#issuecomment-322828654) did not consider the impact on the shorthand _at all_ (it was mostly about the values, which we didn't resolve on until later).

**Comment by litherum** [comment]
I have no opinions.

**Comment by svgeesus** [comment]
Hearing no objections, I plan to make the edits as @jfkthame suggested.

**Comment by cdoublev** [comment]
@svgeesus, can you please update the `initial` field from `auto` to `normal`?

https://github.com/w3c/csswg-drafts/blob/a2e50cb70605eac89e4bcb30ca7809633e4b79ec/css-fonts-4/Overview.bs#L6612
