### ISSUE TITLE
[mediaqueries] Reinstate "inverted-colors" somehow

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#732]
In this commit: https://github.com/w3c/csswg-drafts/commit/3abb7e30e5a7ec5f7504f5bc6470cf3c9a123b37
@tabatkins removed inverted-colors

Since there is no media-queries-5 specification yet, can we either make one or put this back into MQ4? WebKit has been shipping with it for a while.

Similarly, it would be nice to merge in #586 (I just implemented it in WebKit)

**Comment by grorg** [comment]
One thing that is annoying about these queries is that they are difficult to test. I've made internal API that fakes the settings. I'm not sure how we could do this in WPT.

**Comment by frivoal** [comment]
https://drafts.csswg.org/mediaqueries-5/#inverted
