### ISSUE TITLE
[css-text] Consider removing `distribute` value for `text-justify` from the spec

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#7322]
Currently there is this note in [this section](https://drafts.csswg.org/css-text-3/#valdef-text-justify-inter-character):

> For legacy reasons, UAs must also support the alternate keyword distribute which must compute to [inter-character](https://drafts.csswg.org/css-text/#valdef-text-justify-inter-character), thus having the exact same meaning and behavior.

Looking at browser support for `text-justify`:
* Chrome only supports the property behind the experimental web features flag
* IE (which used to support this value) is now retired
* Safari has never shipped `text-justify`

...which leaves Firefox being the only browser supporting the CSS property.

I suggest that we remove this note from the spec, since there is no clear win in web compatibility in supporting this.

**Comment by nt1m** [comment]
cc @emilio @dbaron Wdyt?

**Comment by nt1m** [comment]
cc @karlcow @miketaylr too

**Comment by fantasai** [comment]
Note that justification doesn't break pages in the way that, say, a layout bug would, so the compat impact of not having this value is going to be less than breaking/dropping any kind of layout behavior. But it's also very cheap to implement, being just an alias.

This value was in a CR-level spec in the past *and* supported by the most dominant browser of the time, so I'm hesitant to drop it if there's not either a compelling reason or substantial proof that it's not used by some long tail of existing CJK content. https://www.w3.org/TR/2003/CR-css3-text-20030514/#justification-prop

**Comment by fantasai** [comment]
CC @kojiishi

**Comment by karlcow** [comment]
Following the discussion in https://github.com/w3c/csswg-drafts/issues/6156

* in Firefox, @Emilio one year ago made an alias for [Same behavior or alias for `text-justify: inter-character` and `text-justify: distribute`](https://bugzilla.mozilla.org/show_bug.cgi?id=1703984). This has shipped in Firefox 89.
* From a webcompat point of view, we never had a report on webcompat.com about `text-justify: distribute` lacking in a web page.

**Comment by nt1m** [comment]
> Note that justification doesn't break pages in the way that, say, a layout bug would, so the compat impact of not having this value is going to be less than breaking/dropping any kind of layout behavior. But it's also very cheap to implement, being just an alias.

The spec (and [relevant WPT](https://github.com/web-platform-tests/wpt/blob/206237ada6/css/css-text/text-justify/distribute-alias.tentative.html)) specifies it as a parse-time alias, which while not hard to implement, complicates the code unnecessarily, since WebKit does not have such a mechanism (you need to create a custom parsing method, and can't re-use the fast paths). Compute-time is fine though I don't see the benefit of supporting it. Fwiw, Chrome only implements it compute-time.

**Comment by kojiishi** [comment]
Edge has degraded this when it moved to Chromium. If Edge is fine, I think it's a good sign we can remove this safely. /cc @dlibby-

**Comment by kojiishi** [comment]
I agree the bar for removing backward compatibilities should be high, but when one browser successfully removed it, the fact should clear the high bar, right?

**Comment by Loirooriol** [comment]
HTTPArchive could provide some data I guess? @LeaVerou

**Comment by Loirooriol** [comment]
Thanks! Then it seems strange to me to have a `distribute` value for compat, if `distribute-all-lines` is actually used twice as much but it's not in the spec.

**Comment by jfkthame** [comment]
Yeah, interesting. Another point to note, though, is that it appears `distribute` is used 6 times as often as its "preferred" equivalent `inter-character`. Which suggests that removing the compatibility alias would disrupt the great majority of the pages that are requesting this behavior.

**Comment by karlcow** [comment]
It would be interesting to find out which pages contains this property. Coming from a CSS framework? Really used on purpose or just here by default and doing nothing most of the time. 

## `text-justify: distribute-all-lines` seems to happen a lot in China for ie6-8 as a hack.

https://github.com/search?q=%22text-justify%3A+distribute%22&type=issues
https://github.com/search?l=CSS&q=distribute-all-lines&type=Code
https://github.com/search?l=SCSS&q=distribute-all-lines&type=Code

[Example](https://github.com/9958/rinblog/issues/212)

```
 .test1 {
            text-align:justify;
            text-justify:distribute-all-lines;/*ie6-8*/
            text-align-last:justify;/* ie9*/
            -moz-text-align-last:justify;/*ff*/
            -webkit-text-align-last:justify;/*chrome 20+*/
        }
```

Another blog post, [this time Japanese](https://my-terrace.com/css_justify/) to also basically solve the issue in Internet Explorer. 

@LeaVerou Thanks for the data. I wonder if HTTP archive is able to detect the language of the source and we could check the distribution of `distribute-all-lines` and `distribute` by locales.

This is also used by http://justifygrid.com
https://github.com/CrocoDillon/JustifyGrid/blob/bc9e051aca2e13532540238ba03214a8385906c3/Framework/justifygrid.css#L1-L5

which in return seems to have been in a lot of mixins for SASS.


## `text-justify: distribute`

This [stackoverflow](https://stackoverflow.com/questions/18107036/strange-behaviour-when-using-text-align-justify-text-justify-and-right) seems to encourage to use of `text-justify: distribute` for *solving an issue in Internet Explorer* with images creating space. inside a text.

**Comment by kojiishi** [comment]
> Yeah, interesting. Another point to note, though, is that it appears `distribute` is used 6 times as often as its "preferred" equivalent `inter-character`. Which suggests that removing the compatibility alias would disrupt the great majority of the pages that are requesting this behavior.

This is an interesting data, thanks @Loirooriol, and thanks @karlcow for finding it.

It looks like `inter-ideograph` is the winner for the compat, if we're doing this?

|Value|pages|
|---|---:|
|`inter-ideograph`|19,199|
|`distribute-all-lines`|9,186|
|`distribute`|4,446|
|`inter-character`|717|
|`inter-ideographic`|36|

I'm fine not to add the backward compat because the breakage is very minor and not supported by 3 out of 4 browsers for a long time, but if we want, I think a) adding more used values (`inter-ideograph` and `distribute-all-lines`) looks like more desired, and b) as @nt1m pointed out, great if it's not a parse-time alias as neither WebKit nor Blink has such a mechanism. /cc @lilles

**Comment by emilio** [comment]
How do WebKit and Blink not have parse time aliases? It's a matter of turning a consumed value into another, right?

**Comment by nt1m** [comment]
> How do WebKit and Blink not have parse time aliases? It's a matter of turning a consumed value into another, right?

WebKit does, it's just that you have to create a custom parsing function for the CSS property, you can't go through parsing fast paths (which just checks keywords), which is unfortunate.

**Comment by rviscomi** [comment]
> @LeaVerou Thanks for the data. I wonder if HTTP archive is able to detect the language of the source and we could check the distribution of `distribute-all-lines` and `distribute` by locales.

@karlcow let me know if this is what you had in mind

lang code | distribute | distribute-all-lines
-- | -- | --
en | 38% | 48%
ja | 22% | 10%
NULL | 20% | 19%
pt | 4% | 1%
ru | 3% | 2%
fr | 2% | 4%
zh | 2% | 2%
es | 2% | 2%
de | 1% | 2%
pl | 1% | 1%
other | 5% | 9%

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1120896/172174959-5d9b10d2-e2de-46e3-92df-806aa8827e4b.png">

**Comment by Loirooriol** [comment]
> WebKit does, it's just that you have to create a custom parsing function for the CSS property, you can't go through parsing fast paths (which just checks keywords)

Kinda off-topic, but not sure if you are aware of [`CSSParserFastPaths::isPartialKeywordPropertyID`](https://github.com/WebKit/WebKit/blob/d8ee6747d642bdcd1583cb9daacffa78269ec0f6/Source/WebCore/css/parser/CSSParserFastPaths.cpp#L1060). If you return true for `CSSPropertyTextJustify`, then you can keep the current fast path code, and then in `CSSPropertyParser::parseSingleValue` you only have to handle the alias.

**Comment by frivoal** [comment]
Hi @nt1m
We resolved to keep the `distribute` value in the spec, but it can be implemented either by computing to `inter-character` (which Chrome) or by treating it as a parse-time alias (as Gecko does). Would appreciate if you can confirm this is acceptable to you.

**Comment by nt1m** [comment]
Should probably fine to keep it.

**Comment by frivoal** [comment]
tested by https://github.com/web-platform-tests/wpt/pull/37692
