### ISSUE TITLE
[cssom-1][css-cascade-4] Define which longhands a shorthand maps to

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7323]
I would like to know if a shorthand is considered to map to all its sub-properties, including reset-only sub-properties.

> If all properties that map to `shorthand` are not present in `longhands`, continue with the steps labeled `shorthand loop`.

According to the above step from [*serialize a CSS declaration block*](https://drafts.csswg.org/cssom-1/#serialize-a-css-declaration-block), I guess reset-only sub-properties are excluded from the longhands that the shorthand maps to. But from reading [3. Shorthand properties in Cascade 4](https://drafts.csswg.org/css-cascade-4/#shorthand), this is not clearly defined, and I'm not sure how to serialize a shorthand to empty string if one of its reset-only sub-property is declared with a non-initial value.

**Comment by Loirooriol** [comment]
What makes you think they are excluded? I don't think they should behave different just because the shorthand always sets them to the same value.

**Comment by cdoublev** [comment]
I'm sorry because I do not remember why I thought that, and I even wrote the opposite in my personal notes. 

I may have been confused by the serialization of `style.cssText` in Chrome/Firefox after declaring a shorthand then one of its reset-only sub-property to a non-initial value. For example, after declaring `border` to `1px solid black` then `border-image-width` to `1px`, `style.cssText` does not include `border`, even though all its sub-properties are declared, which is better than serializing to `border: ;`.

I'm closing this issue because no clarification is actually required if a shorthand also maps to its reset-only sub-properties. Sorry again.
