### ISSUE TITLE
[css-cascade-6] add a :stylesheet selector to match the current stylesheet

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#7349]
This is derived from both https://github.com/w3c/csswg-drafts/issues/3547 and (in particular) https://github.com/w3c/csswg-drafts/issues/6606, but I've opened a new issue as it's a more specific proposal.

Suggestion is: add a `:stylesheet` pseudo-class selector which functions like `:scope` but matches the element that declared the rule - ie the `<style>` or `<link>`element that created the stylesheet. For programatically created stylesheets, it would match nothing.

* I suspect this would be very easy to implement as the rule should already have a reference to the stylesheet that declared it.
* it would mean the functionality of the old `<style scoped>` syntax could be reproduced. This has been pretty heavily discussed in 3547, it was clearly popular, and while `@scope` is good it doesn't(*) provide a direct replacement for that functionality. `:stylesheet` would do that:

```css
<style>
@scope (* > :stylesheet) {
...
}
</style>
```

(* you could give the `<style>` an id and reference that from the `@scope` rule, so it's technically possible; just not very flexible)

**Comment by tabatkins** [comment]
I think you need `@scope (:has(> :stylesheet)) {...}`, but yeah, that'd work.

Anyway, huh. Slightly funky idea, but I suppose it works and satisfies a need. I'd be fine with it.

**Comment by mirisuzanne** [comment]
It seems to me like all the use-cases for this actually require selecting the parent of the style sheet, which @tabatkins achieves by using the `:has()` selector. I don't know any reason to select the stylesheet itself. Is there a reason we would do this, rather than something like `:stylesheet-parent` or something similar that directly targets the parent?

I suppose this allows you to more generically define _which ancestor_ of the style sheet to select?

**Comment by faceless2** [comment]
> Is there a reason we would do this, rather than something like :stylesheet-parent or something similar that directly targets the parent?

Not really, to be honest. For the use-case I had in mind for this, `:stylesheet-parent` is fine. Only being able to select the parent would remove the ability to distinguish between two sibling stylesheets, and apply selectors to their siblings (for example) - but I don't have a use-case that would require that

**Comment by mirisuzanne** [comment]
Yeah, `:stylesheet` would allow more flexibility around where the stylesheet lives in relation to the scoping element. That might be useful? But it would then require more complex selectors, and flexibility comes with more potential for unclear relationships. 

Agenda+ to hopefully resolve on:

- Add `:stylesheet-parent` (or `:stylesheet`)
- Maybe add a note to bikeshed the name of the selector, if people aren't happy with those names

I think that would also allow us to close #6606
