### ISSUE TITLE
[css-inline] initial-letter should be clearer about how it sinks

### ISSUE THREAD

**Issue by chenpighead** [w3c/csswg-drafts#735]
From [the spec.](https://drafts.csswg.org/css-inline/#valdef-initial-letter-integer), It's not clear  about how an initial letter should sink. I mean, we should specify that `an initial-letter's baseline should be aligned with the Nth line's baseline, where N is the initial-letter's sink argument` or something similar. For example, what would authors like to see if we have 
```<p>This line <img> has a tall image.</p>``` with the p having initial-letter styles and the img having vertical-align style set to top?

Looks like the only implemented vendor, Safari, also has this kind of issue. The rendering result of
```
<style>
div {  max-width: 500px; }
p::first-letter {  -webkit-initial-letter: 3 2; }
</style>
<p>Second paragraph <img style="height: 50px; width: 10px; vertical-align: top; background-color: blue;"/>with a capital initial letter. An initial letter 
does not affect the position of its containing element. For “raised 
caps” or “sunken caps,” the effect is created as if the text around the 
initial letter was pushed down, rather than the letter extending up into
 previous elements.</p>
```
is as follows:

<img width="512" alt="screen shot 2016-11-18 at 5 12 50 pm" src="https://cloud.githubusercontent.com/assets/10356583/20424960/54d44c46-adb3-11e6-8bb7-0fec19cd1c90.png">

It'd be better to clearly specify how an initial letter should sink, an example like above would be great.

**Comment by chenpighead** [comment]
cc @dbaron

**Comment by dbaron** [comment]
How does this issue differ from #719?

**Comment by chenpighead** [comment]
@dbaron, I think #719 is about how an Raised/Sunken initial letter affects the size of the first line box. However, in this issue, it's more about which position we'd like to place/sink an initial letter.

According to [Sizing Initial Letters](https://drafts.csswg.org/css-inline/#sizing-initial-letters), the size of a drop initial is determined by the need to satisfy the required alignment. But, in the same section, it specifies that "The contents of the lines spanned, and therefore any variation in their heights and positions, is not accounted for." Which would lead to this issue.

If we size an initial letter without referencing spanned line-height, and a line is indeed spanned, then which position we should align the initial letter to?

With N as the initial-letter's sink argument, we could

- align the initial letter to the Nth line's baseline (take spanned line-height into consideration)
- align the initial letter to the position that DO NOT take spanned line-height into consideration, as can be seen in the example listed in comment 0.
- something else.

**Comment by dauwhe** [comment]
I'm OK with the behavior exhibited by Safari. The idea was to try to avoid dependencies on the details of what's going on in the lines adjacent to the initial-letter (or on the window width). In particular, we didn't want cycling if some large inline would increase the size of the initial letter, and thus push the large inline to a different line, decreasing the size of the initial letter...

We also want initial letters with the same specs in the same document to be the same size, even if there was a badly-designed superscript or something in an adjacent line some of the time.
