### ISSUE TITLE
[css-gcpm-3] Incorrect `element()` as `newValues` for `content` property

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7351]
GCPM 3 defines [`element()` as `newValues`](https://drafts.csswg.org/css-gcpm-3/#element-syntax) for the [`content` property](https://drafts.csswg.org/css-content-3/#content-property).

I believe `element()` is ambiguous because it can be interpreted as a function component value whose name is `element` with no argument. A terminal or non-terminal must be defined between angled brackets, per the [CSS value definition syntax](https://drafts.csswg.org/css-values-4/#component-types), ie. `<element()>`.

Please forgive me to not create a separate issue for the following... `content` is defined as `normal | none | [<content-replacement> | <content-list>] [/ [<string> | <counter>]+]?` and both `<content-replacement>` and `<content-list>` includes `<image>`. I think `<content-replacement>` can be removed.

**Comment by faceless2** [comment]
This has come up before, see https://github.com/w3c/csswg-drafts/issues/2657. The distinction between the two is valuable, specifically:

* `content-replacement` is a single image - it makes the node a replaced-content node.
* `content-lis`t is a list of one or more items, possibly including images. The node contains replaced content, but is not replaced itself.

The linked-to issue above gives an example.

**Comment by cdoublev** [comment]
Got it, thanks.

**Comment by cdoublev** [comment]
The same problem exists for [`running()`](https://drafts.csswg.org/css-gcpm-3/#running-syntax) defined as a new value for the `position` property. But waiting for an eventual resolution to [retire GCPM as a Note status](https://github.com/w3c/csswg-drafts/issues/6435#issuecomment-1159094975).
