### ISSUE TITLE
[css-shapes-2] Value definition of `shape-padding` is missing `none`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7352]
The initial value of [`shape-padding`](https://drafts.csswg.org/css-shapes-2/#shape-padding-property) is `none` but it is missing from its `value` definition.

> **Name:** `shape-padding`
> **Value:** `<length>`
> **Initial:** `none`

**Comment by astearns** [comment]
Thanks for pointing this out. I think the bug is that the initial value should be `0` *and* the value should be <length-percentage>
