### ISSUE TITLE
[css-color-6] color-contrast() syntax is confusing

### ISSUE THREAD

**Issue by manuelmeister** [w3c/csswg-drafts#7354]
Why do we use `vs` and not just something like this:

```
color-contrast() = color-contrast( <color> [ , <color>#{2,}  [ , to [<number> | AA | AA-large | AAA | AAA-large]]? ]? )
```

Because for me, the following looks like only maroon is tested to AA and only wheat and bisque are compared.
```
color-contrast(wheat vs bisque, darkgoldenrod, olive, sienna, darkgreen, maroon to AA)
```

I think this would be much more readable:
```
color-contrast(wheat, bisque darkgoldenrod olive sienna darkgreen maroon, to AA)
```

**Comment by fantasai** [comment]
Yeah, the grammatical pattern we should follow here is probably linear-gradient() et al.

**Comment by LeaVerou** [comment]
Discussed in NYC F2F, discussion in https://github.com/w3c/csswg-drafts/issues/7359
