### ISSUE TITLE
[css-color-5] Extra `(` in the value definition of `<hsl()>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7362]
There is an extra `(` in the value definition of [`<hsl()>`](https://drafts.csswg.org/css-color-5/#funcdef-hsl).

> `hsl() = hsl(([from <color>]? [<hue> | none] [<percentage> | <number> | none] [<percentage> | <number> | none] [ / [<alpha-value> | none] ]? )`

**Comment by svgeesus** [comment]
Yes there is, thanks for spotting!
