### ISSUE TITLE
[css-background-4] Missing `round` keyword in `value` field of `border-limit`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7367]
`round` is defined as the `initial` value of [`border-limit`](https://drafts.csswg.org/css-backgrounds-4/#border-limit) but this keyword is not included in the `value` definition field.

> **Name:** `border-limit`
> **Value:** `all | [ sides | corners ] <length-percentage [0,∞]>? | [ top | right | bottom | left ] <length-percentage [0,∞]>`
> **Initial:** `round`

**Comment by SebastianZ** [comment]
Fixed by changing the initial value to `all`.

Sebastian
