### ISSUE TITLE
[css-color-5] Custom color profiles: <custom-ident> or <dashed-ident>?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7374]
In general in CSS we use `<custom-ident>` for CSS-internal identifiers, see `@namespace`, `@font-face`, `@counter-style`. Color 5 proposes to use `<dashed-ident>` for color profile names (`@color-profile`), which is inconsistent. Should it be switched to `<custom-ident>` or is there some compelling reason why color profile names need to be different?

**Comment by tabatkins** [comment]
Right, we have dashed-idents specifically for the case where we're mixing them with CSS-defined idents (or would otherwise have parsing ambiguities for some other reason). This is 100% one of those cases, so dashed-ident is required.
