### ISSUE TITLE
[css-background-4] Replace `<position>` by `<bg-position>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7376]
In CSS Backgrounds 4, [`background-position`](https://drafts.csswg.org/css-backgrounds-4/#the-background-position) is defined with `<position>#` and `<position>` is defined with a value that accepts the 3-values form, which has been removed from the definition of [`<position>`](https://drafts.csswg.org/css-values-4/#typedef-position) in CSS Values 4, as explained in #2140. I believe this is the reason why CSS Backgrounds 3 defines [`background-position`](https://drafts.csswg.org/css-backgrounds-3/#background-position) with `<bg-position>#` instead of `<position>#`.

CSS Backgrounds 4 is flagged as *Not Ready For Implementation* but is listed in `w3c/browser-specs` and used by `@webref/css`, which picks the definition of `background-position` from CSS Backgrounds 4 instead of CSS Backgrounds 3 during its curation step, resulting to duplicate definitions for `<position>`. Do you think CSS Backgrounds 4 should not be listed in `w3c/browser-specs`? Otherwise, can `<position>` be replaced to `<bg-position>` in this spec, please?

FYI, @tidoust.

**Comment by fantasai** [comment]
Done
