### ISSUE TITLE
[css-cascade-6] Disallow pseudo-elements in @scope's prelude

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#7382]
I think we should make it a parse error to use pseudo-element selectors in `@scope`'s prelude (like we already do for e.g. `:is/:where`). It's a significant engineering effort to support properly, and it doesn't seem very useful. You could reference the pseudo-scoping-root itself with `:scope`, but not much else.

We should disallow it, at least until there is a point in allowing it.

**Comment by tabatkins** [comment]
Yeah this restriction makes sense.

**Comment by mirisuzanne** [comment]
I agree this makes sense. Could we consider that an 'obvious bugfix', or should we bring it up for (maybe async) resolution?

**Comment by tabatkins** [comment]
Obvious bugfix, imo.
