### ISSUE TITLE
[css-contain-3] Proposal: Add an event to fire when content-visibility: auto state changes

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#7384]
Right now we specify that content-visibility: auto [skips its content when the element isn't relevant to the user](https://www.w3.org/TR/css-contain-2/#valdef-content-visibility-auto). This means that the contents of the element will not be rendered by the UA. This is also a great opportunity for frameworks (e.g React) or general script (e.g. canvas updates) to stop, since the effect of these updates would not be rendered anyway.

However, to coordinate the starting/stopping updates, the UA should give the developer an signal (this proposed event) which would inform script that the rendering state changed.

The name is hard to come up with but I have a couple of proposals in the explainer:
https://github.com/vmpstr/web-proposals/blob/main/explainers/cv-auto-event.md

Happy to hear other suggestions or thoughts about this in general.

**Comment by tabatkins** [comment]
I'm in favor of just being big and verbose - this *is* something very specific and I don't think we should try to claim a generic name for it. So +1 for `ContentVisibilityAutoStateChanged`

**Comment by smfr** [comment]
Can you describe the exact timing of when this event is fired? We don't want it to reveal exactly when the UA does style updates or layout, so I would prefer that it fire during the "update the rendering steps" somewhere.

**Comment by FremyCompany** [comment]
1. Are we sure this is different from an `IntersectionObserver`?
2. How about `ContentVisibilityStateChanged`? This might apply to values other than auto in the future.

**Comment by chrishtr** [comment]
> Can you describe the exact timing of when this event is fired? We don't want it to reveal exactly when the UA does style updates or layout, so I would prefer that it fire during the "update the rendering steps" somewhere.

It should fire during the same timing as `IntersectionObserver` callbacks, i.e. in a posted event loop task after the observer fires. (`content-visibility:auto` is [already defined](https://drafts.csswg.org/css-contain/#cv-notes) in terms of `IntersectionObserver` timings.) 

Therefore the feature would not expose the exact timing of style or layout.

> * Are we sure this is different from an `IntersectionObserver`?

It's not different. But this event allows a web app to subscribe to the implicit UA-internal `IntersectionObserver` without having to (a) add more javascript that duplicates it and slows down the page, and (b) reverse-engineer the (UA-dependent) margin chosen by the UA.

> * How about `ContentVisibilityStateChanged`? This might apply to values other than auto in the future.

This name SGTM.

**Comment by chrishtr** [comment]
As discussed on the call, the event will need a parameter indicating whether the element is now in a skipped or not-skipped state. I suggest we call the event parameter `skipped`.

**Comment by noahlemen** [comment]
This is definitely crucial for being able to leverage `content-visibility:auto` to replace userland implementions of virtual scrollers. 

For example, in our JS-based virtual scroller on Facebook, we use intersection observers to determine visibility – we then use this to control both rendering of the elements, as well as to flag these React components for deprioritized updates.

When attempting to use `content-visibility:auto` to replace this implementation, we currently lose out on the latter. We certainly _could_ continue to use an intersection observer for this aspect of the functionality, but I think that is undesirable for the reasons @chrishtr mentioned.

**Comment by emilio** [comment]
@vmpstr there's other things that affect `c-v: auto` state, like focus and selection. Does the event still fire at `IntersectionObserver` time even when e.g., a descendant gets focus?

**Comment by bgrins** [comment]
@noahlemen I'm curious if the additional ["relevant to the user"](https://www.w3.org/TR/css-contain-2/#relevant-to-the-user) states are desirable for your virtual scroller use case - specifically focused and selected elements. Or do you really only want elements in/around the viewport, and would do work to filter out elements that are focused/selected and not in viewport?

**Comment by noahlemen** [comment]
that's a good question! for the specific virtual scroller i have in mind currently, we are _just_ interested in the "on-screen" case, at least in regards to maintaining parity with the JS-based virtual scroller. i don't think it would be problematic to begin included focused/selected elements, but its not something we currently do as far as i know.

to be clear, would this `ContentVisibilityAutoStateChanged` event respond to changes to an elements "relevant to the user" state based on any criteria, not just the "on-screen" condition?

**Comment by bgrins** [comment]
> to be clear, would this ContentVisibilityAutoStateChanged event respond to changes to an elements "relevant to the user" state based on any criteria, not just the "on-screen" condition?

Yes, I believe so based on the summary in the [explainer]( https://github.com/vmpstr/web-proposals/blob/main/explainers/cv-auto-event.md#css-content-visibility-state-change-event)

> This proposal is to add an event that would fire on a content-visibility: auto element when the rendering state of the element changes due to any of the attributes that make the element [relevant to the user](https://www.w3.org/TR/css-contain-2/#relevant-to-the-user).

Though further down it talks about polyfilling without including `selectionchange` and `focus` events which I think would be necessary to have feature parity, so it'd be good to confirm with @vmpstr:

> Note that even without this event, it is still possible to polyfill the behavior with a combination of IntersectionObserver and MutationObserver. From this perspective, the event does not add a capability to observe new behaviors, but rather an easier way to discover events that are should already be discoverable.

**Comment by bgrins** [comment]
I don't have any particular insights about this, but I do wonder if there's a set of use cases for this to replace Intersection Observer on paper but then in practice it would either not solve the use case, or would require additional hoops due to:

1) wanting to customize threshold options in a way that don't match UA default (is there good data for how frequently these are customized in the wild?)
2) not wanting focused-or-selected-out-of-viewport elements included

**Comment by vmpstr** [comment]
The intent of the event is to respond to any changes that take the element from being relevant to not being relevant (and vice versa). The polyfill would need to consider selectionchange and possibly other events as well, which I realize I haven't mentioned in the explainer. 

I'm curious to hear whether the proximity to the viewport is the _interesting_ thing to observe, or it's strictly required that we don't include things like selection (and other relevant-to-the-user aspects) here. As an example, if there is an off-screen selection, then I can see an argument for why one would want that content to be updated since it can always make it into the copy buffer via ctrl/cmd-c or something similar. Similarly some focused elements (text input) support things like ctrl-a ctrl-c to select the text in there regardless of whether or not the element is on-screen.

**Comment by bgrins** [comment]
Agreed that the event should map to the content-visibility semantics of relevance, and I can see where it would be beneficial for i.e. focused offscreen elements to be included. Though I don't know if that's what developers actually want for certain use cases like virtual scrollers.

For example if a virtual scrolled element is big enough for 10 rows, and a user focuses a text field in a row 1, then scrolls down to row 20 - would that mean that the DOM now has row 1 followed by rows 20-29? If so, is that desireable? I don't know enough about how these are implemented to know.

**Comment by chrishtr** [comment]
> For example if a virtual scrolled element is big enough for 10 rows, and a user focuses a text field in a row 1, then scrolls down to row 20 - would that mean that the DOM now has row 1 followed by rows 20-29? If so, is that desireable?

I think it's desirable, because if it was done by the user, they indicated via focus that they care about the thing being focused. However, if the virtual list was virtualized in chunks,  other chunks between the focused one and the near-screen would not be relevant to the user, and so could be deprioritized by the virtual list script-side implementation (as well as the browser).

Keeping focused elements, even if far off-screen, up-to-date is also important for accessibility APIs.

Virtual scroller implementations can also if they so desire by checking `document.activeElement` and calling `blur` on it. if the element is far off-screen and it therefore makes more sense to unfocus it in the web page UI.

**Comment by bgrins** [comment]
I had a question about the second use case in the explainer:

> Similarly, the developer may want to stop any other script updates (e.g. canvas updates) when the user-agent is not rendering the element.

I may be missing something, but isn't that better served by using an IntersectionObserver? In the sense that you presumably don't want to continue making visual-only updates for elements that are offscreen but focused or highlighted. Which is the behavior with IntersectionObserver already - and in order to achieve this with the new event you'd need to track those states and exempt those elements.

**Comment by chrishtr** [comment]
> I may be missing something, but isn't that better served by using an IntersectionObserver? In the sense that you presumably don't want to continue making visual-only updates for elements that are offscreen but focused or highlighted. Which is the behavior with IntersectionObserver already - and in order to achieve this with the new event you'd need to track those states and exempt those elements.

A focused or highlighted element that is offscreen is much more likely to be brought onscreen sometime soon, and therefore it's a good idea for the developer to keep its canvases up to date.

**Comment by jcsteh** [comment]
I have some concerns regarding accessibility here.

I understand that this event doesn't facilitate anything that isn't already possible with other functionality (e.g. IntersectionObserver and MutationObserver) and that isn't already being done (e.g. by virtual scrollers). However, there's a difference between "authors can already do this" vs "the spec includes something which is intended to be used in a certain way that will fundamentally cause this problem". In the former case, it's reasonable to argue that if an author is doing something a little obscure, they must understand the consequences across the board. In the latter case, the web platform is providing a feature which authors can reasonably expect to "just work".

The primary use case for this feature - stopping DOM updates to a subtree that is not rendered (as outlined in the explainer) - will cause pretty severe problems for a11y. It's not a technical problem with the event itself, but it is a problem with the way that it is intended to be used. The decision was made to expose content-visibility: auto in the a11y tree on the basis that the content was still semantically relevant; it just wasn't visually relevant right now. The intent behind this event fundamentally changes that logic.

I don't think adding a note is sufficient to resolve this. If the primary use case causes problems for a11y, either that use case needs to be normatively forbidden by the spec or the technique needs to be fixed somehow to avoid this problem.

There are likely use cases that don't cause problems for a11y; e.g. stopping computation that wouldn't affect the DOM, stopping canvas updates, etc. Those use cases are fine. While i realise there is often a preference to avoid codifying specific use cases into specs, I think this is potentially warranted when primary use cases might cause significant harm.

**Comment by vmpstr** [comment]
Hey, thanks for your comments and for taking the time to discuss this outside of this thread.

The conclusion we seemed to have reached is that we can proceed with speccing this event, but we should add normative developer guidance in the spec (and mdn) to avoid cases that break the semantic meaning of elements affected by c-v auto. IOW, since currently the content is semantically relevant regardless of whether it's skipped by c-v auto, this event should not be used to break that (e.g. by stopping all updates indefinitely, although deprioritizing the updates is a reasonable use case).
