### ISSUE TITLE
[css-ui-4][css-images-4] `<string>` in `<image-set()>` and `<url-set>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7388]
[CSS UI 4](https://drafts.csswg.org/css-ui-4/#typedef-cursor-url-set) defines `<url-set>` as *a limited version of `image-set()`, where only `<url>` and `<url-set>` can be used in the part of the `<image-set-option>` sub-production which would normally allow `<image>`*.

[CSS Images 4](https://drafts.csswg.org/css-images-4/#funcdef-image-set) defines that *each `<string>` inside `image-set()` represents a `<url>`*.

Is `image-set()` invalid if `<string>` does not represent a valid URL? If yes, I suggest *each `<string>` inside `image-set()` should represents a [valid URL string](https://url.spec.whatwg.org/#valid-url-string) otherwise the function is invalid*.

Is `<string>` valid in `<url-set>`?

I believe there is a small typo in the description of the part of `<image-set-option>` that corresponds to `type(<string>)`, in *an `<image-set-option>` like `url("picture.png") 1x format("image/jpeg")` is valid, [...]*: `format()` should be `type()`.

**Comment by tabatkins** [comment]
> Is image-set() invalid if `<string>` does not represent a valid URL?

No, no more than `<url>` is required to represent a valid URL. You can put whatever nonsense you want inside of there, like `url("foo bar &*[]{}:$?#")` and we'll just feed it to the URL parser and use whatever comes out.  That sentence is just referring to the ability defined in [V&U](https://andreubotella.com/csswg-auto-build/css-values-4/#urls) for a `<string>` to be treated as a `<url>`.

> Is `<string>` valid in `<url-set>`?

Yes. If it's not currently written as such, that's a spec bug.

> I believe there is a small typo

Yup, that's a typo.

**Comment by frivoal** [comment]
https://github.com/w3c/csswg-drafts/commit/887025da9e52a8f19961fb9e298fda9961821f4b addresses the css-ui part of this.  Given that https://github.com/w3c/csswg-drafts/issues/7803 has already landed too, we can now close this.
