### ISSUE TITLE
[css-contain] Clarify what happens when `display: contents` and `contain: style` are used together

### ISSUE THREAD

**Issue by mrobinson** [w3c/csswg-drafts#7392]
Regarding https://drafts.csswg.org/css-contain/#containment-style:

The other types of containment have language like this:
> If the element does not generate a [principal box](https://www.w3.org/TR/css-display-3/#principal-box) (as is the case with [display](https://www.w3.org/TR/css-display-3/#propdef-display) values of [contents](https://www.w3.org/TR/css-display-3/#valdef-display-contents) or [none](https://www.w3.org/TR/css-display-3/#valdef-display-none)), or its principal box is an [internal table box](https://www.w3.org/TR/css-display-3/#internal-table-box) other than [table-cell](https://www.w3.org/TR/css-display-3/#valdef-display-table-cell), or an [internal ruby box](https://www.w3.org/TR/css-display-3/#internal-ruby-box), or a [non-atomic](https://www.w3.org/TR/css-display-3/#atomic-inline) [inline-level](https://www.w3.org/TR/css-display-3/#inline-level) box, paint containment has no effect.

This means these types of containment have no affect when `display: contents` is used. In the case of `contain: style` this text isn't there. Should elements that have `contain: style` and `display: contents` establish a new style boundary? It seems that in Chrome it does, though perhaps with some bugs. In Gecko, this behavior might be a bit trickier to implement.

**Comment by emilio** [comment]
FWIW I think I think this should probably not work:

 * Other counter properties do nothing on `display: contents` elements.
 * Other containment types don't do anything on `display: contents` elements.

**Comment by tabatkins** [comment]
Yeah, I don't think the difference in wording was intentional here, it was just that the definition of the other containments is much more dependent on a box existing so we called out the effects.

I'm happy to say that *no* containment has an effect if you don't have a principal box.

**Comment by dholbert** [comment]
Could we get the spec updated to reflect this?  CC @frivoal; maybe this needs to be on the CSSWG agenda?

Assuming we're in agreement, we need to update at least one WPT since the expectations have changed:
http://wpt.live/css/css-contain/contain-style-counters-002.html

Right now that test has the following note in an assert meta-tag (emphasis added by me):
> In this test, the div#test does not generate a principal box because of 'display: contents'. Despite that particular condition, 'contain: style' **will have an effect** on div#test

If we change the spec as discussed above, then the test should be updated to expect that contain:style has *no* effect.

**Comment by dholbert** [comment]
[Ticking agenda+; I'm assuming this needs csswg discussion/resolution to move forward.]
