### ISSUE TITLE
[css-color-4][css-color-5] Allow `<alpha-value>` to be `none` in `<color()>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7397]
In [4.3. "Missing"/none Color Components](https://drafts.csswg.org/css-color-4/#missing):

> All color functions allow any of their components to be specified as `none`.

The value definition of `<color()>` is `color( <colorspace-params> [ / <alpha-value> ]? )` in [CSS Color 4](https://drafts.csswg.org/css-color-4/#funcdef-color) or `color( [from <color>]? <colorspace-params> [ / <alpha-value> ]? )` in [CSS Color 5](https://drafts.csswg.org/css-color-5/#funcdef-color).

Side question: is it voluntary not to export `<color()>` related sub-productions from CSS Color 5?

**Comment by svgeesus** [comment]
Sorry, not sure what your actual question is.

CSS Color 4 has a definition for [the `color()` function](https://drafts.csswg.org/css-color-4/#color-function).

CSS Color 5 expands that definition, adding two things:

1. [Relative Color Syntax](https://drafts.csswg.org/css-color-5/#relative-color-function) (the `[from <color>]?` part)
2. [Custom color spaces](https://drafts.csswg.org/css-color-5/#custom-color) (via [`@color-profile`](https://drafts.csswg.org/css-color-5/#at-profile)

The Color 4 definition is the current, stable implementation target in browsers. Safari implements RCS, and BFO Publisher implements custom color spaces.

**Comment by svgeesus** [comment]
Aha, I see! Huh, no reason for `data-noexport`.

> `<colorspace-params>` is different in CSS Color 4 and 5.

Yes.

**Comment by svgeesus** [comment]
Might be a bikeshed issue, or might be a difference in the per-spec metadata. See the bikeshed bug I just raised.

**Comment by svgeesus** [comment]
Yes, that one is clearly an oversight; all the other functions which take an optional alpha also allow `none` there.

**Comment by cdoublev** [comment]
Thanks for the info.

> For syntactic forms which support [missing color components](https://drafts.csswg.org/css-color-4/#missing-color-component), the value [none](https://drafts.csswg.org/css-color-4/#valdef-color-none) (equivalently NONE, nOnE, etc), shall be serialized in all-lower case as the string "none".


`none`
