### ISSUE TITLE
[scroll-animations-1] currentTime when scroll range is 0?

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7401]
The spec does not yet include the calculation for the currentTime, however the description of currentTime in the [IDL interface](https://drafts.csswg.org/scroll-animations-1/rewrite#scrolltimeline-interface) suggests that the timeline is only inactive (producing a null time) when the principle box is not a scroll container.

What happens when we have a ScrollTimeline source scroll container with 0 range?

I think the logical conclusion is that this is another case in which the timeline should be considered inactive and return a null time.

**Comment by fantasai** [comment]
Edited in as inactive. Agenda+ to review with the CSSWG.

CC @bramus @mirisuzanne @rachelnabors

**Comment by bramus** [comment]
LGTM

**Comment by mirisuzanne** [comment]
Makes sense to me as well.

**Comment by BorisChiou** [comment]
Inactive timeline sounds reasonable to me as well.

**Comment by fantasai** [comment]
Thanks @flackr, fixed in https://github.com/w3c/csswg-drafts/commit/fdd21a55facb5f49f867d211f7a1b5c18d17f3ad
