### ISSUE TITLE
[css-variables][css-transitions] Clarify transitions on custom properties

### ISSUE THREAD

**Issue by devknoll** [w3c/csswg-drafts#7405]
The [CSS Variables spec](https://drafts.csswg.org/css-variables) says:

> Notably, they can even be transitioned or animated, but since the UA has no way to interpret their contents, they always use the "flips at 50%" behavior that is used for any other pair of values that can’t be intelligently interpolated.

But what does "transitioned" mean here? I assumed it meant that I should be able to write `transition: --bar 1ms`, but this does not appear to be the case: at the very least, WPT does not appear to test for e.g. `transitionend` events on custom properties alone, instead apparently relying on being used in another property (e.g. `color`) to trigger a transition.

It might be useful to explicitly clarify whether custom properties (by themselves, not in conjunction with other properties) should trigger transitions.

**Comment by tabatkins** [comment]
Yes, they definitely trigger transitions. Unsure what needs to be clarified, as transitions triggering when you change a property's computed value is the normal behavior.

If WPT is lacking some tests, that can be fixed.

**Comment by dbaron** [comment]
Transitions don't normally occur on properties that animate discretely; see the [definition of transitionable](https://www.w3.org/TR/css-transitions-1/#transitionable) in the transitions spec.  I think the note in the variables spec should be updated to distinguish between transitions and animations.

**Comment by Loirooriol** [comment]
CSS Transitions says

> The [`all`](https://drafts.csswg.org/css-transitions/#valdef-transition-property-all) value and [`all`](https://drafts.csswg.org/css-cascade-5/#propdef-all) shorthand property work in similar ways, so the `all` value is just like a shorthand that covers all properties.

But the `all` shorthand doesn't include:
 - `direction` and `unicode-bidi` (seems fine since they are not animatable)
 - custom properties

**Comment by devknoll** [comment]
@Loirooriol Thanks for pointing this out. I updated the linked example and my code blocks to prevent any confusion here.

**Comment by devknoll** [comment]
Yup, thank you!
