### ISSUE TITLE
[css-contain-3] Resolving container units inside container query

### ISSUE THREAD

**Issue by anttijk** [w3c/csswg-drafts#7410]
What should happen with something like `@container (inline-size > 30cqi)`? It is not obvious from the spec. Resolve against a parent container (if any)? Treat like `svi`? Something else?

**Comment by mirisuzanne** [comment]
Ideally I think we would resolve the units against a parent contain, if available. Or, framed another way, we would resolve the units normally, from the perspective of container - since that would match handling of other relative units like `em`.
