### ISSUE TITLE
Descriptive text in nth-child selector when using "of" is misleading

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#7411]
https://www.w3.org/TR/selectors-4/#the-nth-child-pseudo

Spec currently defines the syntax as being `:nth-child(An+B [of S]?)` and then says 

> If `S` is omitted, it defaults to `*|*`.

this reads like `nth-child(2n of)` is valid. Perhaps it should be

> If `of S` is omitted it defaults to `of *|*`

**Comment by tabatkins** [comment]
The grammar makes it clear that the `S` can't be omitted on its own. If you *do* omit `S` (validly, along with the preceding `of`), then the defaulting applies.  The prose isn't intended to imply anything more optionality than what the grammar says (and we use this kind of wording elsewhere in properties).
