### ISSUE TITLE
[css-counter-styles-3] Invalid `initial` of `negative`, `prefix`, `suffix`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7417]
In the context of automatic parsing of a CSS value against a value definition, the `initial` field of the [`negative` descriptor](https://drafts.csswg.org/css-counter-styles-3/#descdef-counter-style-negative) should be defined with a value that can be parsed against the `value` field. But the `initial` field is defined with *"\2D" ("-" hyphen-minus)*.

I suggest using `"\2D"` or just `"-"` (I believe [tokenization](https://drafts.csswg.org/css-syntax-3/#consume-string-token) will replace `\\2d` by `-`) and to define in prose that it corresponds to *("-" hyphen-minus)*, or to use some kind of markup (containing *("-" hyphen-minus)*) that provides additional details that `w3c/reffy` can read to separate it from the `initial` value.

FYI, @tidoust.

**EDIT:** the same issue applies to `prefix`, defined with *"" (the empty string)*, and `suffix`, defined with *"\2E\20" ("." full stop followed by a space)*.

**Comment by tabatkins** [comment]
Done. This is editorial so no WG confirmation needed. I also just switched to writing them with the actual characters rather than the escapes, they're all ASCII so I'm not sure why I was being weird about it.
