### ISSUE TITLE
[css-easing-2] Bikeshed function name for custom easings

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#7419]
What should we call the function that allows developers to define custom easings?

<details>
<summary>Feature description</summary>

The arguments are a comma-separated groups of:

- Output (number)
- Start input (optional, percentage)
- End input (optional, percentage)

The values work very similar to `linear-gradient`.

`function-name(0, 0.7, 0.87, 0.98, 1)` - this creates 5 points:

<img width="432" alt="Screenshot 2021-08-23 at 13 11 21" src="https://user-images.githubusercontent.com/93594/130444902-68fde7bc-c8d9-4b10-837f-3e2bd79b931f.png">

Which is equivalent to `function-name(0 0%, 0.7 25%, 0.87 50%, 0.98 75%, 1 100%)`, as points without a 'start input' are given one automatically (using the same process as linear gradients).

The third value, again similar to gradients, can be used to create an extra point using the same output value. So `function-name(0, 0.5 25% 75%, 1)` creates 4 points:

<img width="432" alt="Screenshot 2021-08-23 at 08 52 21" src="https://user-images.githubusercontent.com/93594/130410833-eba70188-f844-47ce-ae5e-82dc078c910d.png">

Output values will typically be 0-1, but can be outside of that, as they can with `cubic-bezier`. A likely usage here will be elastic/spring easings.

Similarly, input values will typically be 0%-100%, but can extend beyond that to provide points for edge-cases where easings are chained.

The ends of the graph automatically extend beyond their specified point using their final angle, so the previous easing (`function-name(0, 0.5 25% 75%, 1)`) would extend like this:

<img width="435" alt="Screenshot 2021-08-23 at 09 00 32" src="https://user-images.githubusercontent.com/93594/130411964-bbc668db-8331-41c8-b75f-42ce76306b89.png">

However, if the final two points are in the same position, the line extends horizontally, so `function-name(0, 0.5 25% 75%, 1 100% 100%)` (the difference being the `100% 100%` at the end), would be:

<img width="433" alt="Screenshot 2021-08-23 at 09 02 27" src="https://user-images.githubusercontent.com/93594/130412244-10550d78-7dc6-4032-95f0-559ab4e7a859.png">
</details>

## Option 1: `linear()`

Why:

- `linear` is already an easing keyword. It would be redefined to be shorthand for `linear(0, 1)`.
- The interpolation is 'linear' between points.
- The syntax is similar to `linear-gradient()`, which starts with `linear` (although there 'linear' mostly refers to direction than interpolation).

Why not:

People seem initially confused by this, as they expect linear to be a single line. When I explain "but it's still linear, but between points", they roll their eyes as if I've found a loophole 😄 

## Option 2: `linear-spline()`

Why:

- 'spline' is often used when interpolating between points.

Why not:

- It often evokes curves, which this isn't really.

## Option 3: `ease()`

Why:

- It's the definition of an easing. Naming similar to keywords `ease`, `ease-in`, `ease-out` etc.
- Leaves the door open for defining a non-linear interpolation between two points, without having to use a new function name. Eg something like `ease(0, ease-out to 0.5, ease-in to 1)`

Why not:

- `ease` already exists as a shothand keyword for `cubic-bezier(0.25, 0.1, 0.25, 1)`, so the keyword usage is pretty different to the function usage.
- Perhaps it won't make sense to add curves this way, and we'd need to find a new function name for that.

## Option 3.5: `easing()`

As above, but avoids the naming clash with the keyword `ease`.

## Option 4: `piecewise()`

Why:

- Closeish to the [mathematical concept](https://en.wikipedia.org/wiki/Piecewise)

Why not:

- It isn't that totally like the concept, as the function always interpolates between points.
- I wasn't aware of the term before someone suggested it. Maybe it's obscure?
- The name doesn't communicate that it produces an easing function.

**Note:** This is a discussion of the function name only, not the format of the function overall.

**Comment by jakearchibald** [comment]
👍 This comment to vote for `linear()`

**Comment by jakearchibald** [comment]
👍 This comment to vote for `linear-spline()`

**Comment by jakearchibald** [comment]
👍 This comment to vote for `ease()`

**Comment by jakearchibald** [comment]
👍 This comment to vote for `piecewise()`

**Comment by jakearchibald** [comment]
👍 This comment to vote for `easing()`

**Comment by jakearchibald** [comment]
I don't think `lerpsequence`/`linearsequence` make it clear enough that this defines an easing function.

**Comment by manuelmeister** [comment]
Why not `linear-steps`?
The interpolation between steps is linear.
With ease I associate a smooth transition of values/speed as for example in After Effects, which is not the case here.

**Comment by tabatkins** [comment]
I don't think it's useful to draw an implicit connection to `steps()`, which does something relatively different. (Technically `steps()` can be reproduced with this function, but the "steps" mean something more than just "segments" - they imply horizontal extension, as if they were steps on a staircase.)

Strongly opposed to `ease()`, as this isn't *remotely* related to the `ease-*` keywords, all of which are specifically about *smoothly curving*. Similarly opposed to `easing()`; it also doesn't match the conjugation of the other values. We already have a function + related keywords group (`steps()` and `step-*`) and this would completely break with the pattern they establish. I'd block this if it came to it.

Mildly opposed to `linear-spline()` - the "spline" doesn't add anything useful, and we've omitted that word from `cubic-bezier()`, which is technically a "cubic Bezier spline".

Would be okay with `piecewise()`, tho I prefer `linear()` over it. It's a little more complex in spelling (I'm always against words with the `ie` compound if they can be avoided, as whether English spells that sound "ie" or "ei" is pretty random.)  I *have* used "piecewise linear" to refer to functions like this; the term doesn't necessarily imply the ability to have C0 discontinuities like `steps()` produces.

`linear()` is definitely the best option. We've done the "keyword and function with same name" variations before (notably in pseudo-classes, but I think elsewhere?), and it fits the "keyword is the obvious default arguments to the function" pattern we use there.

**Comment by jakearchibald** [comment]
> (And note that `steps()` cannot be reproduced with this function anyway - steps produces discontinuous easings while this is always C0-continuous, at least.)

Huh, I thought you could? For example, `steps(3, jump-end)` would be `function-name(0 0% 33.3%, .333 33.3% 66.6%, .666 66.6% 100%, 1 100% 100%)`

> Strongly opposed to `ease()`, as this isn't _remotely_ related to the `ease-*` keywords

They're pretty related, in that they all return easing functions. I think the main problem with `ease` is that it's too different to the keyword.

> Similarly opposed to `easing()`; it also doesn't match the conjugation of the other values.

I guess you're not convinced by future extensions that would make it non-linear, eg `easing(0, ease-out to 0.5, ease-in to 1)`?

> `linear()` is definitely the best option

Fair enough. I guess we'd come up with a different method name if we want to allow non-linear parts.

**Comment by WebReflection** [comment]
Title: Bikeshed function name for **custom easings**

Question: What should we call the function that allows developers to define **custom easings**?

Solution: already in title and question 😜

I mean ... why do we need to find a different name for something that is already described? `custom-ease()` or `easing()` look like a no-brainer to me (former is not in the list though).

**Comment by jakearchibald** [comment]
`cubic-bezier()` also lets you customise easings to some degree. In fact, all of CSS is customisation to some degree, so using the word 'custom' seems tautologous.

**Comment by WebReflection** [comment]
fair enough ... we have the second word left then 😊 ... the one I voted 👋

**Comment by jakearchibald** [comment]
Yeah, I think the choice is coming down to `linear()` vs `easing()`

**Comment by WebReflection** [comment]
imho `ease` should not be on the list for the mentioned reason ... I hope that will be ignored as result.

**Comment by tabatkins** [comment]
> Huh, I thought you could? For example, steps(3, jump-end) would be function-name(0 0% 33.3%, .333 33.3% 66.6%, .666 66.6% 100%, 1 100% 100%)

Oh duh, indeed, that does the job. Not *technically* discontinuous but for all intents and purposes is.

(On that note, is it well-defined what the behavior is at such points? I forget whether steps takes the earlier or later value at its discontinuities, but we should match.)

**Comment by jakearchibald** [comment]
I asked the same question in internal chat and didn't get a certain answer. From my testing it seems like last-point-wins, so that's what I've written in the spec.

**Comment by ollicle** [comment]
How about **facet()**?
To my mind at least, a faceted surface (think cut diamond) fits as a visual representation of how a curve is drawn with linear lines between multiple points.

**Comment by birtles** [comment]
> I agree that `ease()` or `easing()` is not appropriate because this is just one particular way of defining a custom easing function (using linear segments).

Also, the property for using these functions in Web animations is called [`easing`](https://drafts.csswg.org/web-animations-1/#dom-effecttiming-easing) and there has been a proposal to introduce an `animation-easing` property to CSS animations that would allow setting the easing across all keyframes (as opposed to per-keyframe). In either case, a function with `easing` in the name would be a little redundant, as in  `{ easing: 'easing(...)' }` or `animation-easing: easing(...)`.

**Comment by jakearchibald** [comment]
I don't think it's any more redundant than
`background-image: image(…)`

**Comment by tabatkins** [comment]
Yeah, I don't think that redundancy is problematic, I'm just strongly against `ease()` as a name for this feature for other reasons.

**Comment by jakearchibald** [comment]
I'm going to go with `linear()`. I realise that isn't the one that got the highest vote, but I'm swayed by the points against `ease()` and `easing()`.

**Comment by jakearchibald** [comment]
I've applied this change in https://github.com/jakearchibald/csswg-drafts/pull/1
