### ISSUE TITLE
[css-animation] Animation-type: animation-timing-function

### ISSUE THREAD

**Issue by estelle** [w3c/csswg-drafts#7423]
The animation specification lists all the long-hand components making up the `animation` shorthand property as "non animatable". All browsers (Chrome, Edge, Firefox, Safari tested) seem to implement `animation-timing-function` as my understanding of the term "discrete".

In https://codepen.io/estelle/pen/GRxKVgE, note that I was able to "animate" the `animation-timing-function`. It jumps from `linear` to `ease-in` at the 50% mark

**Comment by dbaron** [comment]
I think what you're seeing is the behavior described in [4.1 Timing functions for keyframes](https://www.w3.org/TR/css-animations-1/#timing-functions), which I think is different from the behavior you'd get for discrete animation (where I think you'd get the change halfway between the keyframes, not at the keyframe boundary).

**Comment by estelle** [comment]
thanks!

**Comment by tabatkins** [comment]
Yup, within a keyframe `animating-timing-function` is actually an at-rule-specific descriptor, not the property of the same name. The naming is indeed confusing and unfortunate, but we're stuck with it.
