### ISSUE TITLE
[css 2]: Baseline of an `inline-block` should not use bottom margin edge if `overflow` computes to clip

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7426]
The [spec](https://www.w3.org/TR/CSS22/visudet.html#propdef-vertical-align) for vertical-align clarifies how the baseline should be synthesized for inline-blocks [here](https://www.w3.org/TR/CSS22/visudet.html#propdef-vertical-align:~:text=The%20baseline%20of%20an%20%27inline%2Dblock%27%20is%20the%20baseline%20of%20its%20last%20line%20box%20in%20the%20normal%20flow%2C%20unless%20it%20has%20either%20no%20in%2Dflow%20line%20boxes%20or%20if%20its%20%27overflow%27%20property%20has%20a%20computed%20value%20other%20than%20%27visible%27%2C%20in%20which%20case%20the%20baseline%20is%20the%20bottom%20margin%20edge).

"The baseline of an 'inline-block' is the baseline of its last line box in the normal flow, unless it has either no in-flow line boxes or if its 'overflow' property has a computed value other than 'visible', in which case the baseline is the bottom margin edge."

Its unclear why all overflow values other than visible require using a synthesized value as specified above as opposed to the content-derived baseline. This is likely associated with non visible overflow values creating a scrollable container, in which case `clip` should behave similar to `visible`.

@dbaron

**Comment by Loirooriol** [comment]
Already resolved in https://github.com/w3c/csswg-drafts/issues/6212#issuecomment-833109975
