### ISSUE TITLE
[css-inline] Is initial-letter in-flow or out-of-flow?

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#743]
It doesn't seem to be clear whether initial-letter is in-flow or out-of-flow. More specifically, is the box of initial-letter first-letter contained by its ancestors' box?

For example, if I have:
```html
<style>div::first-letter { initial-letter: 2; }</style>
<div><span style="background: yellow">hello world</span></div>
```
does the first letter "h" has the yellow background as well? Also what if the `span` has `border`?

If the initial letter is out-of-flow, then the background color would not cover the initial letter. I believe it is how WebKit currently implements initial letter (it simply makes initial-letter floating). If the initial letter is in-flow, then initial letter would have the background color as well.

I guess the difference on their effects might not be very important, but it would significantly affect how they would be implemented. I think handling initial letter as out-of-flow is probably easier to implement (as shown by WebKit), but CSSWG should decide whether that is what we want.

**Comment by upsuper** [comment]
#688 might be related. cc @chenpighead @dbaron

**Comment by dbaron** [comment]
I think #719 is probably more related than #688.

I think what needs to be defined here is more subtle than a binary “in flow” vs. “out of flow” choice, though.  I think (per #719) that a raised or sunken initial-letter should make its block taller at the top.  But I think [§3.10.2 Short paragraphs with initial letters](https://drafts.csswg.org/css-inline/#short-para-initial-letter) is relatively clear than an initial-letter makes its block taller at the bottom in some cases but not others.

And I think the spec does define some of the pieces necessary, but probably not all.

That said, I think if the spec does need to make a clear decision on “in flow” vs. “out of flow”, I think initial-letter should be “in flow”.

**Comment by upsuper** [comment]
I tend to agree that it should be "in flow" conceptually, but I would argue that the difference between "in flow" and "out of flow" initial letter should be minor in practice, and it seems to me "out of flow" initial letter is easier to implement for `::first-letter`. (There doesn't seem to be any difference for inline-level first child.)

**Comment by astearns** [comment]
If the initial letter is in-flow is the layout in figure 15 possible? I thought that affecting the line boxes of a subsequent paragraph was part of the motivation for defining an initial letter as out of flow.

On the background question, I think in some cases you'd want the background color of the paragraph to be applied to the initial letter, and in other cases you would not. I expect this could be handled whether or not the initial letter is in-flow by setting the background color of the initial letter to match or diverge.

I've been using the concept of a "first in-flow line box" in line metrics discussions to define the first baseline of a paragraph - which is meant to exclude baselines from floats and initial letters. If we change initial letters to be in-flow, I'll have to come up with a different way to refer to that line box (which isn't an argument for or against making the change to initial letter, just noting more to do if we make the change).

**Comment by jetvillegas** [comment]
CSSWG resolved (on 2017-01-11) to have initial letter boxes be in-flow

https://log.csswg.org/irc.w3.org/css/2017-01-11/#e758211
