### ISSUE TITLE
[scroll-animations-1] Should range of ViewTimeline be clamped to scrollable range?

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7432]
As the spec for [ViewTimeline](https://drafts.csswg.org/scroll-animations-1/rewrite#view-timelines) doesn't include the formula to determine the current time it's not clear what the current expected behavior is when the element cannot scroll fully out of view / into view.

E.g. For a header which starts partially in view such as the [parallax header on the scroll timeline polyfill demo](https://flackr.github.io/scroll-timeline/demo/parallax/), should the animation start at 0% even though the element has already almost left the scrollport, or should it start at the element's current progress through the scrollport (e.g. ~70% since it's about to start scrolling offscreen)?

My opinion is clamping to the actually scrollable range is likely to produce the more expected result, but wanted to ensure we have an open issue to track this until the spec includes the formula / touches on this issue.

**Comment by fantasai** [comment]
I think the effect we should pin our timeline design to is the “fade-in/fade-out” effect. If you want to schedule things to fade in as they scroll onto the screen, and fade out as they scroll off, what kind of effect do you want if the element is half-visible above the fold?

If we need additional behaviors for other use cases, we can add them, but I think that's the one we should be addressing by default.

**Comment by flackr** [comment]
I think what you've proposed (the starting at the element's current offset) is reasonable and arguably simpler to work with. There are many cases where clamping to the scroll range is unintuitive and so I'm good with not clamping being the default.

The parallax header example is a case where without clamping it's much more complex for the developer - i.e. the user will never see the full range specified in the animation. If you look at the [unclamped](https://flackr.github.io/scroll-timeline/demo/parallax/unclamped.html) version of my above linked demo you can see how the parallax header starts shifted down since it's already scrolled almost all the way through the view.

**Comment by flackr** [comment]
One way we could eventually add support for clamped range animations without specifically adding a clamp parameter is to make a way to specify clamped phases or just the clamped phase of a timeline.

E.g. Given the following:
```html
<div id="scroller" style="overflow: auto; height: 200px">
  <div id="title" style="height: 50px;">Title</div>
  <div id="header" style="height: 100px;"></div>
  <div style="height: 1000px;"
</div>
```

Producing roughly the following layout where the header is half the height of the scrollport starting 50px down in the middle:
```
   #scroller
   -----------------
  |  Title          |
  |   ---------     |
  |  | #header |    |
  |  |         |    |
  |   ---------     |
  |                 |
   -----------------

```

The unclamped ViewTimeline will start at 50% (when `#scroller` has `scrollTop = 0`) and progress to 100% (when `#scroller` has `scrollTop = 150`. This means with a naive translation (to shift the header down as you scroll down), it will start shifted down from its initial position. 

We could support these particular cases without needing a clamped attribute on the timeline by adding a clamped / reachable (bikeshed) phase which corresponds to the actually reachable portions of the view timeline (i.e. in this case 50% to 100%).

**Comment by bramus** [comment]
+1 for unclamped. Otherwise demos like https://codepen.io/bramus/pen/xxRZZdK – where the child elements end up halfway in the scroller, thus at 50% animation progress, when reaching the scrollport edges – would no longer be possible.

About the parallax header you mentioned: that one seems more like a use-case for [exit keyframes](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1144946715) applied onto the `.header`? 

```css
@keyframes adjust-header {
  exit 0% { transform: none; }
  exit 100% { transform: translateY(30%); }
}

.header {
  view-timeline: tl-header block;
}

.header .background {
  animation: adjust-header tl-header;
}
```

Or am I overlooking things?

**Comment by flackr** [comment]
I intentionally had the header not quite at the top of the page in my example, as I think in that case the author would want the parallax effect to start immediately, but cover the entire range of motion. I.e. you could imagine a common bit of CSS (not yet accelerated but could be in the future) which would apply parallax to oversized background images:

```css
@keyframes parallax-keyframes {
  from { background-position: bottom; }
  to {background-position: top; }
}
.parallax {
  animation: parallax-keyframes view-timeline()
}
```

Where view-timeline is a hypothetical syntax for an anonymous view-timeline similar to [scroll()](https://drafts.csswg.org/scroll-animations-1/rewrite#scroll-notation). This class could then be applied to any element having an oversized background image resulting in a parallax which (with clamped range) would cover the entire visible range of the image regardless of where on the page the element was.

Anyways, I agree that unclamped should be the default behavior, and I'm not sure this particular case is even important enough to solve now. I was mostly just pointing out that we can easily add a phase to support this use case in the future if it seems important.

**Comment by fantasai** [comment]
Clarified. @flackr Lmk if that seems to cover it, or if you think further clarification is necessary.

**Comment by flackr** [comment]
Looks good, thanks!
