### ISSUE TITLE
[css-overflow-3] how do overflow: clip/hidden combinations interact with rounded borders?

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#7434]
css-overflow-3 [allows](https://drafts.csswg.org/css-overflow-3/#overflow-properties) the possibility that 'overflow' is 'clip' in one axis and 'visible' in the other.  css-backgrounds-3 [says](https://drafts.csswg.org/css-backgrounds/#corner-clipping) that when 'overflow' is not 'visible', the clipping is done to the curve.

When the computed value of overflow is 'clip' in one axis and 'visible' in the other axis, is clipping done to the curve, nd if so, how?

I'd suggest that perhaps the easy answer is no:  if you specify 'clip' in one axis and 'visible' in the other, then 'border-radius' is ignored when clipping.

(Noticed while trying to write edits for #6212.)

**Comment by Loirooriol** [comment]
This is what browsers do https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10438

- Firefox: the overflowing content gets clipped to its own rounded curve.
![](https://user-images.githubusercontent.com/7477678/177150950-6fa6f513-9911-4ecd-83d9-f98171ce5454.png)

- Chromium: `overflow: visible clip` behaves as `clip` if the radius is greater than 0px (so not continuous!)
![](https://user-images.githubusercontent.com/7477678/177151424-6afdf112-c536-4de0-a142-7e73c53bb5aa.png)

- WebKit: bug? The content is not painted at all
![](https://user-images.githubusercontent.com/7477678/177151475-2709df9a-0362-40ca-8aed-cb670db8555c.png)

**Comment by smfr** [comment]
Recent WebKit versions match Chromium's behavior above.

**Comment by dbaron** [comment]
Here's a [modified testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A.test%20%7B%0A%20%20display%3A%20inline-block%3B%0A%20%20vertical-align%3A%20middle%3B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border-radius%3A%2025%25%3B%0A%20%20border%3A%20var(--border)%20solid%3B%0A%20%20overflow%3A%20visible%20clip%3B%0A%20%20margin%3A%200%20var(--border)%3B%0A%7D%0A.test%3A%3Abefore%20%7B%0A%20%20content%3A%20%27%27%3B%0A%20%20display%3A%20block%3B%0A%20%20margin%3A%20calc(-2%20*%20var(--border))%3B%0A%20%20height%3A%20calc(100%25%20%2B%204%20*%20var(--border))%3B%0A%20%20width%3A%20calc(100%25%20%2B%204%20*%20var(--border))%3B%0A%20%20background%3A%20cyan%3B%0A%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%200px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%202px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%205px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2010px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2025px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2050px%22%3E%3C%2Fdiv%3E) with a bit more overflow.

**Comment by smfr** [comment]
New testcase: [testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A.test%20%7B%0A%20%20display%3A%20inline-block%3B%0A%20%20vertical-align%3A%20middle%3B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20border-radius%3A%2025%25%3B%0A%20%20border%3A%20var(--border)%20solid%3B%0A%20%20overflow%3A%20visible%20clip%3B%0A%20%20margin%3A%200%20var(--border)%3B%0A%7D%0A.test%3A%3Abefore%20%7B%0A%20%20content%3A%20%27%27%3B%0A%20%20display%3A%20block%3B%0A%20%20margin%3A%20calc(-2%20*%20var(--border))%3B%0A%20%20height%3A%20calc(100%25%20%2B%204%20*%20var(--border))%3B%0A%20%20width%3A%20calc(100%25%20%2B%204%20*%20var(--border))%3B%0A%20%20background%3A%20cyan%3B%0A%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%200px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%202px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%205px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2010px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2025px%22%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22test%22%20style%3D%22--border%3A%2050px%22%3E%3C%2Fdiv%3E)

**Comment by Loirooriol** [comment]
@smfr My testcase is still broken on latest WebKitGTK.
