### ISSUE TITLE
[css-overflow-3] computed value rules for 'overflow' should not depend on whether something is a replaced element

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#7435]
css-overflow-3 [states rules](https://drafts.csswg.org/css-overflow-3/#overflow-properties) for determining the computed value of the `overflow` property that depend on whether something is a replaced element:

> On non-[replaced](https://drafts.csswg.org/css-display-3/#replaced-element) elements, the [visible](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-visible)/[clip](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip) values of [overflow](https://drafts.csswg.org/css-overflow-3/#propdef-overflow) compute to [auto](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto)/[hidden](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-hidden) (respectively) if one of [overflow-x](https://drafts.csswg.org/css-overflow-3/#propdef-overflow-x) or [overflow-y](https://drafts.csswg.org/css-overflow-3/#propdef-overflow-y) is neither visible nor clip.
>
> On [replaced elements](https://drafts.csswg.org/css-display-3/#replaced-element), all values other than [visible](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-visible) compute to [clip](https://drafts.csswg.org/css-overflow-3/#valdef-overflow-clip).

I didn't think computed values could depend on whether something is a replaced element; I don't think that's known at value computation time (e.g., for `<object>`).

If that's the case, I'd suggest that the non-replaced rule above apply to all elements, and then the replaced rule be handled at used value time.  (This is a behavior change in the behavior of combinations of `visible` on one axis with a value other than `visible` or `clip` on the other axis.  However, I suspect that behavior matches implementations today (at least Gecko's), in so far as the difference in behavior on replaced elements is observable.)

(Noticed while trying to write edits for #6212.)

**Comment by khushalsagar** [comment]
This behaviour for replaced elements is a recent addition to the spec. See discussion [here](https://github.com/w3c/csswg-drafts/issues/7144#issuecomment-1090933632). Since replaced elements need to be clipped by default, we also have UA CSS which depends on the element type to apply the default behaviour (see change [here](https://github.com/tabatkins/html/commit/16943c6e9231a4f5fab89c65ae7ddbe49f40f01b)).

> I didn't think computed values could depend on whether something is a replaced element; I don't think that's known at value computation time (e.g., for <object>).

That's interesting. What are the cases where <object> could be a non-replaced element?

**Comment by dbaron** [comment]
> That's interesting. What are the cases where `<object>` could be a non-replaced element?

Items one and three in [this example](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Aobject%20%7B%20border%3A%20medium%20solid%20fuchsia%3B%20%7D%0A%3C%2Fstyle%3E%0A%3Cobject%3Eone%3C%2Fobject%3E%0A%3Cobject%20data%3D%22http%3A%2F%2Fwpt.live%2Fcss%2Fsupport%2Fblue-100.png%22%3Etwo%3C%2Fobject%3E%0A%3Cobject%20data%3D%22url-not-found%22%3Ethree%3C%2Fobject%3E).  Note that distinguishing items two and three at value computation time is particularly hard, but I think in general it may be difficult to distinguish replaced elements during value computation, just because that's not the sort of information that's expected to be needed during selector matching and value computation.

**Comment by Loirooriol** [comment]
`<img>` can also be replaced or not depending on whether `src` points to a valid image, [example](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3Eimg%20%7B%20border%3A%20solid%3B%20display%3A%20block%3B%20width%3A%20auto%20%7D%3C%2Fstyle%3E%0A%3Cimg%20src%3D%22about%3Ainvalid%22%20alt%3D%22Non-replaced%22%3E%0A%3Cimg%20src%3D%27data%3Aimage%2Fsvg%2Bxml%3Butf8%2C%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Ctext%20x%3D%220%22%20y%3D%220%22%20dominant-baseline%3D%22hanging%22%3EReplaced%3C%2Ftext%3E%3C%2Fsvg%3E%27%3E).

**Comment by khushalsagar** [comment]
Had a discussion with @dbaron today. The current implementation for how overflow is applied to replaced elements is dependent on the element's tag (for example img and object in this case). This is required for any values being supplied by UA CSS and wasn't the part dbaron was concerned about. @Loirooriol please clarify if you disagree.

The concern was with modifying the style at value computation to apply the overrides in the spec. Implementation wise they follow the same pattern as UA CSS and depend on the element's tag. But this runs into the case where the same tag might not be rendered as a replaced element (like when img falls back to alt test).

Given that we need to rely on the element tag to identify a replaced element in UA CSS, it seems reasonable to rely on the element's tag (which is known at value computation time) when applying overrides to its computed value as well. I see some precedent for this in [code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/css/resolver/style_adjuster.cc) but I could only trace back to the spec [here](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3:~:text=The%20font%20element%20is%20expected%20to%20override%20the%20color%20of%20any%20text%20decoration%20that%20spans%20the%20text%20of%20the%20element%20to%20the%20used%20value%20of%20the%20element%27s%20%27color%27%20property).

@tabatkins for an opinion too.

**Comment by Loirooriol** [comment]
@khushalsagar  `overflow: scroll` triggers scrollbars on a non-replaced `img` in both Firefox and Chromium. https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10447

**Comment by khushalsagar** [comment]
Ok. I see the point now. We can avoid regressing the behaviour for img elements by applying the rule for replaced elements at used value time as David suggested. So only when the element is rendered as a replaced element it won't create a scroll container (consistent with the behaviour today).

But `<object>` would still be affected because the UA CSS rule is marked with !important to keep these elements from generating ink overflow based on the discussion [here](https://github.com/w3c/csswg-drafts/issues/7143#issuecomment-1104143059).

**Comment by khushalsagar** [comment]
The spec has been updated and the implementation change is landing in chromium soon. Could we close this issue now?

**Comment by dbaron** [comment]
Agreed that this can be closed since it was fixed in efa32287c6a8a2b04041857be9328989fe98cd79.
