### ISSUE TITLE
[css-color-4] More Section Ordering

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7437]
More suggestions:

1. Combine Foreground Color and Transparency under a top-level section called “Using Color in CSS” or something.
2. Pull Accessibility and Conveying Information by Color up as the first topic in that new section
3. Pull Color Spaces of Tagged Images / Color Spaces of Untagged Colors up as the last topics in that new section.
4. Shove the Resolving and Serializing sections much lower down in the spec, like maybe before Converting Colors, because it's talking about a bunch of syntaxes we haven't defined yet and _this is very confusing_.

This focuses “Representing Colors” on defining the `<color>` syntax, consolidates the color-use sections together, and helps the spec make more sense when read from top to bottom.

**Comment by svgeesus** [comment]
> Combine Foreground Color and Transparency under a top-level section called “Using Color in CSS” or something.

Other specs don't do that, and the entire spec is about using color in CSS.

However, I am sympathetic to the general idea of 

> This focuses “Representing Colors” on defining the <color> syntax, consolidates the color-use sections together, and helps the spec make more sense when read from top to bottom.

and most of your re-ordering suggestions would indeed help with that.

**Comment by fantasai** [comment]
Maybe “Applying Color” ?

**Comment by svgeesus** [comment]
> Maybe “Applying Color” ?

Done

> Shove the Resolving and Serializing sections much lower down in the spec,

Also done
