### ISSUE TITLE
[css-values] calc(): divide length by length to equal number?

### ISSUE THREAD

**Issue by Myndex** [w3c/csswg-drafts#7448]
The https://drafts.csswg.org/css-values/#calc-func does not indicate this implicitly (though it is tangentially implied in an example), though other docs do indicate that using calc() with a divide, requires the divisor to be a number, and not any form of unit. i.e.` calc(1ex / 1em) ` is illegal, and so is ` calc(1ex / 6px) ` only allowed is something like ` calc(1ex / 4) `.

Is there a specific reason that the right side *must* be a number, and can't be a value of the same type/subtype of unit?

I.e. I can see that 10px / 3deg makes no sense, but 10px / 3pt or 10px / 3em seem completely reasonable, but nevertheless will not evaluate.

An example application might be:

```css
span.helv { font-family: Helvetica; }
span.times { font-family: Times; }
span p { font-size: calc(10px / (1ex/1em)); }
```
So that
```html
<span class="helv"><p>This text is set to an x-height of 10px</p></span>
<span class="times"><p>This text is also set to an x-height of 10px</p></span>
```
Both lines here have the same x-height, as the font size is calculated as 10px divided by the x-height ratio, determined from 1ex/1em of the font family (inherited from the parent span). So for Helvetica, the font would be 19.3px, and for times it would be 22.2px.

It seems on the surface at least that dividing a length by a length is reasonable, and would be reasonable that the result was a unit-less number that could be used for further calculations. 

**Related**, the requirement that in a calc() where a multiplication is involved, at least one of the values must be a number, and again, it would seem that 6px * 3px should reasonably equal 12px.

**Related documentation issue:** the docs at Mozilla describe the current limitation more clearly than the CSS spec:  https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by dbaron** [comment]
This limitation was correct for Values & Units Level 3, but was intended to have been removed in Level 4 by #545.  I'm not sure what the implementation status of that change is.

**Comment by tabatkins** [comment]
Yes, the ability to divide by unit'd values (and multiply two units together) is well-defined in V&U 4 (and is built on the algorithms in Typed OM that first defined this).

Implementations are indeed still lacking.

**Comment by Myndex** [comment]
Hi @tabatkins @dbaron 

Doh! My bad... I searched the document and didn't see it mentioned, and as noted is not widely implemented and is still documented as illegal at Mozilla.

The examples are not implicitly demonstrating this either, so this remains a documentation issue here... don't know is etiquette to reopen this as a documentation problem or start a new issue?

ALSO: I'll follow up with a PR for Mozilla, but now my question is what are the current limitations? I only length allowed? What about angle? Again I did not see specific delineations here in the current CSS 4 values doc...

**Comment by tabatkins** [comment]
You're right that there's no examples showing it off, but <https://drafts.csswg.org/css-values/#calc-type-checking> has a note talking about it explicitly, at least.

There are no restrictions. Your expression has to end up with a legal type after handling all the units, but that's it.

**Comment by cdoublev** [comment]
> There are no restrictions. Your expression has to end up with a legal type after handling all the units, but that's it.

How can `[ length → 2 ]` be *legal* when [matched](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-match) against `<length>`?

> A type is said to match a CSS production in some circumstances: 
> - A type matches `<length>` if its only non-zero entry is `«[ "length" → 1 ]»` and its percent hint is null.

**Comment by tabatkins** [comment]
> How can [ length → 2 ] be legal when [matched](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-match) against `<length>`?

I don't understand the question - it *doesn't* match `<length>`, as you show in your following quote.

**Comment by cdoublev** [comment]
Before editing my comment, I did not understood that multiplying two `<length>`s would not produce a `<length>`, but a hypothetical `<area>`. I was also slow to understand why dividing two `<length>`s would produce a `<number>`, or that dividing a `<length>` by `<time>` could produce a hypothetical `<speed>`.

Some examples would have helped me, but I guess it is a bad idea to include hypothetical types in an example.

**Comment by KOEGlike** [comment]
are there any updates?
