### ISSUE TITLE
[css-sizing] URL refers to the wrong draft

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#746]
The URL https://drafts.csswg.org/css-sizing/ redirects to the Level 4 draft, though Level 3 is still in WD stage.
So, for now the URL should refer to the Level 3 draft, i.e. to https://drafts.csswg.org/css-sizing-3/.

Sebastian

**Comment by fantasai** [comment]
This should be fixed now! Thanks~

**Comment by SebastianZ** [comment]
Yes, thank you for the fix!

Sebastian
