### ISSUE TITLE
[css-overflow-3] shorten name of overflow-clip-margin?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7464]
We're planning to add longhands for `overflow-clip-margin` like `overflow-clip-margin-inline-start` etc., and it's getting really long. What about shortening the name to just `overflow-margin`?

**Comment by jfkthame** [comment]
If the property is just `overflow-margin` rather than `overflow-clip-margin`, it might seem more surprising to authors that it does *not* have any effect, for example, on scrollable overflow (as mentioned in the spec):

> Note: This property has no effect on boxes with [overflow: hidden](https://www.w3.org/TR/css-overflow-3/#propdef-overflow) or overflow: scroll, which are not defined to use the [overflow clip edge](https://www.w3.org/TR/css-overflow-3/#overflow-clip-edge).
