### ISSUE TITLE
Rechartering 2022-2024

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7468]
Time goes by fast. I see CSS WG is chartered to **30 Sept 2022** which is less than 3 months away.

https://www.w3.org/2020/12/css-wg-charter.html

Time to get rechartering underway, I guess! 

Looking at the [current charter](https://www.w3.org/2020/12/css-wg-charter.html) and comparing the projected timeline with actuality:

**Timeline**

Q4 2019: REC for CSS Containment Module Level 1 
  **W3C Recommendation**, 22 December 2020 

 Q4 2019: REC for CSS Writing Modes Level 3 
  **W3C Recommendation**, 10 December 2019

Q2 2020: REC for CSS Values and Units Module Level 3 
  Candidate Recommendation, 6 June 2019

Q2 2020: REC for CSS Custom Properties for Cascading Variables Module Level 1
  Candidate Recommendation Snapshot, 16 June 2022

Q2 2020: REC for CSS Flexible Box Layout Module Level 1 
  Candidate Recommendation Snapshot, 16 June 2022

Q3 2020: REC for CSS Cascading and Inheritance Level 3 
  **W3C Recommendation**, 11 February 2021

Q3 2020: REC for Compositing and Blending Level 1 
  Candidate Recommendation, 13 January 2015

Q4 2020: REC for CSS Conditional Rules Module Level 3 
  Candidate Recommendation Snapshot, 13 January 2022

Q2 2021: REC for CSS Backgrounds and Borders Module Level 3 
  Candidate Recommendation Draft, 26 July 2021

Q1 2022: REC for CSS Cascading and Inheritance Level 4 
  Candidate Recommendation Snapshot, 13 January 2022

Q2 2022: REC for CSS Image Values and Replaced Content Module Level 3 
  Candidate Recommendation Draft, 17 December 2020

Q2 2022: REC for Media Queries Level 4 
  Candidate Recommendation Draft, 25 December 2021

**Comment by svgeesus** [comment]
[Draft charter for review by CSS WG](https://w3c.github.io/charter-drafts/2022/css-2022.html)

Changes are:

- Text that came from the charter template updated to use any newer text from [current template](https://w3c.github.io/charter-drafts/charter-template.html)
- Link to new [CSS IPR page](https://www.w3.org/groups/wg/css/ipr)
- Removed mention of closed CSS-A11y TF
- Removed mention of effectively defunct SVG WG
- Removed specs from milestones that we actually got to Rec (as mentioned above)
- Bumped dates by 3 years for the ones that we didn't. (needs discussion of reasonable dates)
- All current specs updated with last publication date, date of exclusion draft, and so on (needs to be updated between now and date of sending to AC for review, if we publish more)
- Added the next three CSS snapshots

Here is [a diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2020%2F12%2Fcss-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fcharter-drafts%2F2022%2Fcss-2022.html) but as usual moved text is handled poorly, and the drafts are listed from oldest to newest so the order is necessarily different and the diff is confused completely for that section.

The first para from Success Criteria was originally template but was changed a fair bit in the current charter, and I am tempted to put it back in the new charter too because it is better.

I also see some places where the W3C database is wrong, for example those embarassing-looking **2009** publications of Transforms 3D and Transforms 2D actually redirect to the [**2019** CR of Transforms 1](https://www.w3.org/TR/css-transforms-1/) and the last publication of Shapes 1 was indeed in **2014** but as a [CR](https://www.w3.org/TR/2014/CR-css-shapes-1-20140320/). Still checking that list.

**Comment by svgeesus** [comment]
Fixed, except for:

- patent policy, because "W3C seeks to issue Web Specifications" is correct (and CSS is one such)
- CSS 2.1 Specification, because that was indeed the whole of CSS at the time

**Comment by svgeesus** [comment]
So, which specifications are likely to make it to Rec in the next year?

I'm thinking CSS Variables 1 and Media Queries 4 are strong candidates

**Comment by SebastianZ** [comment]
Looking at https://www.w3.org/Style/CSS/current-work.en.html, what about the stable specs there? Namely

* CSS Conditional 3
* CSS Backgrounds 3
* CSS Counter Styles 3
* CSS Flexbox 1
* CSS Multi-col 1
* CSS Values 3

I don't know how good their test coverage actually is, but looking at the current ratios of passing tests they seem to be good candidates as well.

The following also seem to be possible candidates as currently being at CR, having a lot of tests and a relatively high passing rate:

* CSS Grid 1
* CSS Will Change 1 (though the [test results](https://wpt.fyi/results/css/css-will-change) aren't shown in the spec. for some reason)
* CSS Cascade 4
* CSS Conditional 4

Sebastian

**Comment by svgeesus** [comment]
Closing because we did, indeed, recharter for 2022-24 :)
