### ISSUE TITLE
[css-syntax-3][css-values-4] Add informative note about tokenization of negative 0 

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7472]
I cannot tell which behavior is "right", if there is one, and I cannot think of an example for which it could matter, but I feel like an informative note (something like the note removed in this [commit](https://github.com/w3c/csswg-drafts/commit/3eeafc30400155ab02e7934c522689ec06f9af1b#diff-fc1c32de78d227c8f0c8008469824444d1ba7f027e48a336125017d40b8f6f6fL3463)) about removing the sign of `0⁻` in [*convert a string to a number*](https://drafts.csswg.org/css-syntax-3/#convert-a-string-to-a-number) is required, especially in regards to calculations because a consequence is that `calc(1 / -0)` is `calc(infinity)` instead of `calc(-infinity)`, which matches the output in JS, which [*performs division according to the rules of IEEE 754-2019*](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-divide), whereas in [Type Checking (CSS Values)](https://drafts.csswg.org/css-values-4/#calc-type-checking):

> Math functions follow IEEE-754 semantics for these operations
>
> - Dividing a positive value by zero produces +∞.
> - Dividing a negative value by zero produces −∞.
>
> [...]
>
> In other words, multiplying or dividing with 0⁻ follows standard sign rules

Can you also please tell me if there is any other difference between *convert a string to a number* and JS `Number()`, please?

**Comment by cdoublev** [comment]
> Note that I didn't remove anything in that commit

I was referring to this part: *Note: that, outside of [=math functions=], ''-0'' just produces a "standard" zero, identical to ''0''-- **CSS as a whole doesn't recognize the concept of signed zeros***.

Without this note, if CSS claims that it obeys IEE754 semantics for *dividing a positive value by zero produces +∞*, I can not know why `calc(1 / -0)` is not `calc(-infinity)`...

> I'm somewhat loathe to put an explicit note or example about this into the spec, because it's a corner case that matters to approximately zero authors.

... but I'm fine with this position, ok.

> For implementors, the right behavior just falls out if they follow the specs.

For a JS implementation of *conversion from string to number*, following the spec does not help. I have to check for `0` and return it if the conversion equals 0.

> I didn't write the algorithm with any regard to JS's algorithm, but I expect they're probably very similar? I know that there's at least one difference, tho - "-0" produces a negative zero in JS, but not in CSS.

I *think* there is no other difference. From reading the [JS spec](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-runtime-semantics-stringnumericvalue), I can only note that `'Infinity'`, and decimal numbers in the exponent part, are valid but they are not allowed by the CSS grammar, therefore it does not matter.

**Comment by tabatkins** [comment]
> For a JS implementation of conversion from string to number, following the spec does not help. I have to return unsigned 0 if the conversion equals 0.

Actually, upon review you're right - the "convert a string to a number" algorithm will, upon seeing `"-0"`, set `s` to -1, `i` to 0, the other parts to their default values, and then the expression at the end will multiply -1 by 0 and yield -0 in any IEEE-754-compatible language.

So that's a bug on my part and should be fixed.

**Comment by cdoublev** [comment]
I came back to this issue after a while and I am not entirely sure of your intention, because of this comment:

  > `-0` looks like it's valid CSS

It is valid CSS.

I assume you do not want to make it invalid, but to remove its sign in *convert a string to number*, right?

Basically:

```diff
  2. An integer part: zero or more digits. If there is at least one digit, 
     let i be the number formed by interpreting the digits as a base-10 integer; 
     otherwise, let i be the number 0.
+    If i is the number 0, set s to 1.
```

So `calc(-1 / -0)` would result to `-infinity`? Alternatively, `-0` could be a special case in [serialize a CSS component value](https://drafts.csswg.org/cssom-1/#serialize-a-css-component-value), but maybe I am missing the reasons why CSS never recognized the sign of 0.

**Comment by tabatkins** [comment]
Right, that commit's irrelevant to this issue.
