### ISSUE TITLE
[css-position] Is the "nearest scrollport" in DOM hierarchy or in containing block hierarchy?

### ISSUE THREAD

**Issue by wangxianzhu** [w3c/csswg-drafts#7483]
https://drafts.csswg.org/css-overflow-3/#nearest-scrollport says:
For convenience, a box’s nearest scrollport is the [scrollport](https://drafts.csswg.org/css-overflow-3/#scrollport) of its nearest scroll container ancestor.

It doesn't say the "ancestor" is in DOM hierarchy or in containing block hierarchy.

For the following case:
```
<div id="outer-scroller" style="overflow: scroll; position: relative">
  <div id="inner-scroller" style="overflow: scroll">
    <div style="position: absolute">
      <div style="position: sticky">
```

Is the nearest scrollport of the stickily positioned element "inner-scroller" or "outer-scroller"?

"outer-scroller" looks to make more sense to me, but I think the spec needs clarification.

**Comment by Loirooriol** [comment]
This is basically #3185

**Comment by MrBirb** [comment]
@wangxianzhu Well you forgot to actually close 😅

**Comment by wangxianzhu** [comment]
Thanks for the heads-up!

**Comment by tabatkins** [comment]
You still didn't close it, but I got you.
