### ISSUE TITLE
[css-values-4] Allow combining number and percentage

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7485]
In CSS Values 4, [10.9. Type Checking](https://drafts.csswg.org/css-values-4/#calc-type-checking):

> Note: In previous versions of this specification, **multiplication and division were limited in what arguments they could take**, to avoid producing more complex intermediate results (such as `1px * 1em`, which is `<length>²`) and to make division-by-zero detectable at parse time. **This version now relaxes those restrictions**.
>
> [...]
>
> Note that `<percentage>`s relative to `<number>`s, such as in `opacity`, are not combinable with those numbers — `opacity: calc(.25 + 25%)` is invalid. **Allowing this causes significant problems with "unit algebra" (allowing multiplication/division of `<dimension>`s)**, and in every case so far, doesn’t provide any new functionality. (For example, `opacity: 25%` is identical to `opacity: .25`; it’s just a trivial syntax transform.)

Is the second note obsolete or is there a reason not to allow combining `<percentage>` and `<number>` when `<percentage>` is resolved relative to `<number>`?

**Comment by tabatkins** [comment]
The note is still valid, and in fact was written after adapting calc() to handle unit algebra. Allowing %s to resolve to an empty type (like numbers) would make a lot of definitely-invalid calculations appear possibly-valid, and you wouldn't know they aren't until you actually resolved the percentage's type.

**Comment by cdoublev** [comment]
> Allowing this causes significant problems with "unit algebra" (allowing multiplication/division of <dimension>s)

I guess numbers have an empty type because they can be used to multiply/divide dimensions/percentages.: *by a number* is implied after *allowing multiplication/division of <dimension>s*. It makes sense, ok.

**Comment by cdoublev** [comment]
I think *combinable* can be clarified a bit more in the corresponding note.

This is not directly related to my initial demand, but it is not obvious to me that eg. `opacity: abs(-50%)` is invalid. I would clarify it with something like *`<percentage>` is not resolved against `<number>` in math functions, even when the context is `<number> | <percentage>`*.

It is not defined that type checking should apply before simplification. Assuming that it applies after, then `opacity: abs(-50%)` becomes valid.
