### ISSUE TITLE
[css-values-4] Incorrect resolved type of math functions representing `<number>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7486]
In CSS Values 4, [10.9. Type Checking](https://drafts.csswg.org/css-values-4/#calc-type-checking):

> Math functions themselves have types, according to their contained calculations:
> 
> - [...]
> - The type of a `sign()` expression is `«[ "number" → 1 ]»`. 
> - The type of a `sin()`, `cos()`, or `tan()` expression is `«[ "number" → 1 ]»`. 
> - [...]
> - The type of a `pow()`, `sqrt()`, `log()`, or `exp()` expression is `«[ "number" → 1 ]»`.
>
> [...]
>
> A math function resolves to `<number>`, `<length>`, `<angle>`, `<time>`, `<frequency>`, `<resolution>`, `<flex>`, or `<percentage>` according to which of those productions its [type](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-type) [matches](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-match).

I do not understand the type defined for these functions. I expect ``«[ ]»`` because from [CSS Typed OM](https://drafts.css-houdini.org/css-typed-om-1/#cssnumericvalue-match):

> A type matches `<number>` if it has no non-zero entries and its percent hint is null.

**Comment by tabatkins** [comment]
Done; I'm assuming this edit is fine since it's exactly what you asked for. ^_^
