### ISSUE TITLE
[css-fonts] Extend font-size-adjust to adjust for average character width

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/csswg-drafts#750]
The [`font-size-adjust` property](https://drafts.csswg.org/css-fonts-3/#font-size-adjust-prop) was initially conceived as a way of ensuring readability when an entire font isn't available (so the ex-height of a fallback font isn't too small) and ensuring a smooth flow when individual characters aren't available in the main font (so they aren't too much larger or smaller than their neighbours).

With dynamic font switching as web fonts download, however, a new problem arises: layout re-flows.  For layout, the most important difference between fonts is not the ex-height, but the different average character widths (aka, the `ch` to `em` ratio, approximately). 

This is visibly demonstrated in Monica Dinculescu's [Font Style Matcher utility](https://meowni.ca/font-style-matcher/) (which was inspired by a discussion in [Helen Holmes' excellent essay on web typography](http://helenvholmes.com/writing/type-is-your-right)).

If you're using scripts to download and apply web fonts, then maybe it's not too much extra work to manually change the font size and letter-spacing when the new font is available.  But ideally, we will get to the point when the browsers do all this smart font-downloading on their own, with only declarative hints from the author ([e.g., with `font-display`](https://tabatkins.github.io/specs/css-font-display/)).  Which means we need a declarative way to indicate how much adjustment would be required.

If `font-size-adjust` is to serve this need, it should allow for adjustments in both the vertical and horizontal dimensions.  A full `font-size-adjust` declaration would then include two values: the target `ex` to `em` ratio, and also the target `ch` to `em` ratio.  A user agent could then adjust not only the rendered font-size of a fallback font, but also the letter-spacing (or variable font-stretch) as required.

Backwards-compatible syntax:

```
font-size-adjust : <number>|none [<number>|none]?
```

Examples:

- `font-size-adjust: 0.5` (adjust so that ex height is half the declared em height, as currently defined)
- `font-size-adjust: 0.5 none` (same, but without the backwards compatibility)
- `font-size-adjust: 0.5 0.7` (adjust so that ex height is half the declared em height, then adjust so that net character width + letter-spacing is 70% of the originally declared em height)
- `font-size-adjust: none 0.7` (don't worry about ex height, just adjust so that net character width + letter-spacing is 70% of the declared em height)

(All of this is separate from the need to have better ways of asking the browser to pick a good fallback font, based on dimensions or features instead of family names. But it would help.)

**Comment by simevidas** [comment]
I’ve made a demo that shows that there’s an issue on the horizontal axis when swapping fonts, and this issue cannot be solved with `font-size-adjust` in its current form.

Note: The demo swaps between the Georgia (system) and Merriweather (web) fonts and due to a difference in the optimal `font-size-adjust` value between Firefox and Chrome, I had to pick; therefore, the demo is **optimized for Chrome** and you need to use Chrome Canary with the ‘experimental web platform features’ flag enabled.

https://jsbin.com/cetezat/edit?html,css,output

**Observations:**

1. By default, when turning on the webfont, the text becomes larger.
2. After adding a `font-size-adjust` value (`.48` seems to be optimal for Merriweather in Chrome), the text size now stays the same on the vertical axis; however, the text becomes noticeably narrower.
3. After adding a `letter-spacing` value, the text now stays more or less the same on the horizontal axis, as well. However, this technique is almost completely useless, since different `letter-spacing` values work best for different texts, and it doesn’t work at all for longer texts. (You can copy-paste some text from Wikipedia via DevTools to see what I mean.)

Therefore, in order to be able to swap fonts with minimal changes to the layout, `font-size-adjust` needs to be extended to work on both axes.

**Comment by astearns** [comment]
I do not think it's possible to avoid reflows by applying a single glyph width adjustment.

With ex height, there's one consistent feature of the font being modified. And even with that benefit it's difficult to come up with the single adjustment that works across browsers (as shown above).

There are a lot of glyph widths in a font, and fonts vary over how widths differ across glyphs. Taking an average width is problematic in a lot of ways, and whatever method you choose to average over a font is almost guaranteed not to match the average over glyph usage in a particular piece of content. And even if you did happen to match the average in a piece of content, the average in each line will vary within that content. So any particular value you choose will still be likely to cause line break changes as the number of lines in the content increases.

**Comment by AmeliaBR** [comment]
@astearns 

You're correct, of course. Except for monospaced fonts, the `ch` unit (or any other measure of average glyph width) is just a rough approximation.  But nonetheless, we have the `ch` unit for exact measurements with monospaced fonts and for approximations elsewhere.  And similarly, approximations could be useful in reducing the extent of reflows if not preventing them completely.

Using a longer text in @simevidas' demo, I found the optimal adjustment for these two fonts was closer to 0.01em (not 0.005em).  Even then, yes, some small words jumped from one line to the next. But the changes averaged out and the overall length of the paragraphs stayed constant.  Without the adjustment, changes accumulated and the total number of lines in the text grew.

But even if the adjustment is never perfect for variable-width scripts, there are many scripts and fonts which are almost completely monospaced, and would benefit from precise horizontal adjustments, especially as variable fonts with adjustable width become available as the native fallback.

**Comment by litherum** [comment]
We are discussing a more general approach to solving this problem in https://github.com/w3c/csswg-drafts/issues/126. Unless you this it's a bad idea, I'd like to unify the issues.

**Comment by AmeliaBR** [comment]
If merging the issues moves it closer to finding a solution, that sounds fine to me.  I am not particularly tied to `font-size-adjust`, I just want a way to specify predictable font dimensions.

**Comment by litherum** [comment]
Merged with https://github.com/w3c/csswg-drafts/issues/126
