### ISSUE TITLE
[css-fonts][css-font-loading] @font-face's font-variant descriptor vs. FontFace's variant attribute

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#7502]
In https://github.com/w3c/csswg-drafts/commit/d3db8697852a6ccc1c8dafcb4aff1f516198bb50, the `font-variant` descriptor of the `@font-face` rule was dropped, resolving https://github.com/w3c/csswg-drafts/issues/2531.

However, the `FontFace` interface still has the `variant` attribute:
https://www.w3.org/TR/css-font-loading-3/#fontface-interface

It's not clear if this is an oversight, or if it makes sense somehow. Should the descriptor be reinstated, or the attribute removed?

WebKit removed both https://github.com/WebKit/WebKit/commit/af1a8ee05741c91cfe065c3b8e695bb786eeb43f, leaving WebKit the only engine without `FontFace`'s `variant` attribute, which is how I came to notice this.

cc @litherum @drott @svgeesus

**Comment by svgeesus** [comment]
> In https://github.com/w3c/csswg-drafts/commit/d3db8697852a6ccc1c8dafcb4aff1f516198bb50, the `font-variant` descriptor of the `@font-face` rule was dropped, resolving https://github.com/w3c/csswg-drafts/issues/2531.

Right.

> However, the `FontFace` interface still has the `variant` attribute:
https://www.w3.org/TR/css-font-loading-3/#fontface-interface

I think that is easily explained: https://github.com/w3c/csswg-drafts/commit/d3db8697852a6ccc1c8dafcb4aff1f516198bb50 happening on Sep 20, 2019 while https://www.w3.org/TR/css-font-loading-3/#fontface-interface was published  22 May 2014 :( and [badly needs to be republished](https://github.com/w3c/csswg-drafts/issues/7065)

However the [current ED](https://drafts.csswg.org/css-font-loading/#fontface-interface) also has the same problem and I agree, the descriptor was removed so the interface should remove it also.
