### ISSUE TITLE
WebAnimation's commitStyles() method should have CEReactions

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#7507]
Since [this method](https://drafts.csswg.org/web-animations-1/#dom-animation-commitstyles) mutates the style attribute, it must have [CEReactions](https://html.spec.whatwg.org/multipage/custom-elements.html#cereactions).

**Comment by rniwa** [comment]
WPT: https://github.com/web-platform-tests/wpt/pull/34869

**Comment by rniwa** [comment]
WebKit has implemented the updated behavior with `CEReaction` IDL extended attribute on `commitStyles` method.

**Comment by emilio** [comment]
I agree this feels like a pretty obvious bugfix. cc @birtles
