### ISSUE TITLE
[css-backgrounds] Missing for background-size/position computation

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#7514]
[background-size](https://drafts.csswg.org/css-backgrounds-3/#background-size) and [background-position](https://drafts.csswg.org/css-backgrounds-3/#background-size) are specified with a lot of examples. However, there is no clear algorithm that turns them into some sort of an absolute size of the background image.

**Comment by fantasai** [comment]
@noamr Can you explain what's unclear? Afaict the sizing requirements are normatively specified in https://www.w3.org/TR/css-backgrounds-3/#background-size

**Comment by noamr** [comment]
> @noamr Can you explain what's unclear? Afaict the sizing requirements are normatively specified in 

I don't remember what this was about exactly. Will close this for now.
