### ISSUE TITLE
[css-grid] Draft URL refers to CR

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#752]
The draft URL https://drafts.csswg.org/css-grid/ (and https://drafts.csswg.org/css-grid-1/) shows the Candidate Recommendation instead of the latest Editor's Draft.

Sebastian

**Comment by SebastianZ** [comment]
The URLs still refer to the CR. Is there some caching involved or does it require other measures?

Sebastian

**Comment by plinss** [comment]
problem on the hg-git sync server, working on it

**Comment by plinss** [comment]
fixed

**Comment by SebastianZ** [comment]
Great! Thanks for the fast fix!

Sebastian
