### ISSUE TITLE
[css-text-decor] [css-pseudo] default ‘text-decoration-color’ of ‘spelling-error’ and ‘grammar-error’

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#7522]
https://drafts.csswg.org/css-text-decor-4/#text-decoration-line-property

> Since [spelling-error](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-line-spelling-error) and [grammar-error](https://drafts.csswg.org/css-text-decor-4/#valdef-text-decoration-line-grammar-error) decorations are entirely UA-defined, the UA may disregard the other [sub-properties](https://drafts.csswg.org/css-cascade-5/#longhand) of [text-decoration](https://drafts.csswg.org/css-text-decor-4/#propdef-text-decoration), as well any other properties typically affecting the appearance of line decorations (such as [text-underline-position](https://drafts.csswg.org/css-text-decor-4/#propdef-text-underline-position), [color](https://drafts.csswg.org/css-color-4/#propdef-color), [stroke](https://drafts.fxtf.org/fill-stroke-3/#propdef-stroke), or [fill](https://drafts.fxtf.org/fill-stroke-3/#propdef-fill)) when rendering these decorations. However, to the extent that honoring any of these properties would be meaningful and practical given the UA’s chosen rendering, the UA should apply them as modifications to its default styling.

This suggests the UA is allowed (but not required) to heed ‘text-decoration-color’ when ‘text-decoration-line’ is set to ‘spelling-error’ or ‘grammar-error’. But if the UA heeds ‘text-decoration-color’, how would it represent the default spelling/grammar decoration color (usually red or green) in [UA rules for spelling/grammar pseudos](https://drafts.csswg.org/css-pseudo-4/#highlight-ua-styles)? The initial value of ‘currentColor’ won’t work.

```css
:root::spelling-error { text-decoration: <color> spelling-error; }
:root::grammar-error { text-decoration: <color> grammar-error; }
```

Do we need to define [system colors](https://drafts.csswg.org/css-color-4/#css-system-colors) for these, or can the UA make up its own internal color values? What do authors do if they want to reliably add decorations that look like native spelling/grammar decorations, including the decoration color?

(@fantasai, @frivoal, @mrego)

**Comment by fantasai** [comment]
Interesting question... and it's particularly tricky if the UA wants to use different colors depending on the `color-scheme`. I think we could go a couple of ways here:
- If the computed `text-decoration-color` is `currentColor`, use the UA-chosen color.
- Introduce a new computed value for `text-decoration-color`, e.g. `auto`, and set that value in the UA stylesheet.
- Don't allow `text-decoration-color` to affect spelling/grammar errors.

I don't have a strong opinion here.

**Comment by frivoal** [comment]
Made the change: https://github.com/w3c/csswg-drafts/commit/ca0eb4018be7952852967eaf72b45fd6412a830d and https://github.com/w3c/csswg-drafts/commit/275186f88149eeb5ad447e08a945b3554ad0e908
