### ISSUE TITLE
[css-easing-2] Is linear() easing in a shippable state?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7533]
The `linear()` easing function defined in #7484 (https://drafts.csswg.org/css-easing-2/#the-linear-easing-function) has gone through a lot of discussion in both the relevant PR and issues, but I think what ended up landing on the spec is pretty straight-forward.

Firefox has an implementation of this function which you can try on Firefox Nightly.

It'd be great to get the Working Group and other implementors to take a look, to see if there's any concern / outstanding issue that would benefit from a bit more bake-time / testing, or if this is something we could ship in the coming months.

I'd personally love at least an extra implementation ongoing, though again in this case it seems like a relatively straight-forward feature that would be great to get in authors' hands :)

cc @jakearchibald / @dshin-moz / @birtles

**Comment by birtles** [comment]
As editor of the easing spec, I'm happy with the state of this feature. I won't be able to join the F2F but consider this a vote in favour of clearing it to ship.

**Comment by jakearchibald** [comment]
@flackr: any rough implementation timeline we can commit to?

**Comment by emilio** [comment]
TAG review: https://github.com/w3ctag/design-reviews/issues/761

**Comment by jakearchibald** [comment]
Thanks @emilio!

**Comment by CanadaHonk** [comment]
FYI: There's a new [Chromium intent to prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/eEb9q68xysU/m/asQClYSPBQAJ) for this now 🎉

**Comment by bramus** [comment]
Given that this shipped in all major browsers, I think we can close this one, @emilio?
