### ISSUE TITLE
`[css-nesting]` `let rec` as an idea for infix decorator-style nesting syntax

### ISSUE THREAD

**Issue by harrisi** [w3c/csswg-drafts#7540]
Spec: https://www.w3.org/TR/css-nesting-1/

I'm reminded of OCaml's `let rec` which I'm somewhat surprised to not see any mention of, neither here (https://news.ycombinator.com/item?id=32248419) nor the GitHub issues. I was originally thinking of only treating nesting from a parent to child but the child to parent relationship does complicate things (especially since it seems much more likely with CSS to need to modify a parent - assigned from a library or framework, presumably - than typical imperative or functional programming). I originally thought a decorator-type syntax where "this definition includes nested elements" would be reasonable, since any user agent or linter or whatever could be in its rights (depending on spec) to look ahead a certain distance. Obviously this wouldn't actually be too reasonable with arbitrarily distant children.

Anyway, I also initially thought I preferred the brackets since it's explicit and some of the best wording is odd to me, but I think after considering my own `let rec` idea I prefer the optional `@nest` syntax because the only odd case which is relevant - and often enough that succinct but obvious syntax is warranted - is the child->parent->* case. That's the only time I'd want a heads up while visibly parsing css.

**Comment by Loirooriol** [comment]
Can you provide some example? I don't know OCaml and I don't understand what you are proposing.

**Comment by harrisi** [comment]
Absolutely. [Here is a good StackOverflow starting point](https://stackoverflow.com/questions/9325888/why-does-ocaml-need-both-let-and-let-rec), and [some more, from a nice online-readable book](https://ocamlbook.org/recursive-functions/).

The basic idea is that OCaml definitions can't (at runtime) be recursive without an explicit `rec` identifier. The typical example I always see is with defining a factorial function.

```ocaml
let rec factorial n =
  if n = 0 then 1
  else n * (factorial (n-1))
```

This will function as expected (for 32- or 64-bit integer values/results, at least). However,

```ocaml
let fact n =
  if n = 0 then 1
  else n * (fact (n-1))
```

throws an error:

```
Error: Unbound value fact
Hint: If this is a recursive definition,
you should add the 'rec' keyword on line 1
```

(from `utop` on my mac).

Again, I do think the current 'optional' `@nest` is my favorite so far, I just couldn't find any discussion relating to OCaml's take on a slightly similar syntax construction and effects.

**Comment by sesse** [comment]
CSS nesting rules are not recursive (which is what “let rec” is about; you can freely nest functions without “rec”, they just can't call themselves), CSS does not use the “let” keyword (partially since it does not deal with assignments in the first place), and OCaml is not familiar syntax to most CSS developers. So I don't see how this would improve the current matters.

**Comment by tabatkins** [comment]
I'm going to go ahead and close this, as OCaml syntax isn't directly relevant for CSS syntax purposes.
