### ISSUE TITLE
Formatting a table in css like excel

### ISSUE THREAD

**Issue by raphael-louis-andress** [w3c/csswg-drafts#7543]
#### 1. Problem
Manipulating a table in css can be tricky if you have a lot of information, you need a class or id in most cases

#### 2. Solution
A solution would be to manipulate the table element of the html according to the position of the content like excel does. This can be done with a pseudoselector I call a data-to-table sorter.

#### 2.1 before.html
```html
<!DOCTYPE html>
<html>
<head>
<style>

table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>
</body>
</html>
```

#### 2.2 after.html
```html
<!DOCTYPE html>
<html>
<head>
<style>

a1:a5, b1:b5, c1:c5 {
  background: blue;
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

</style>
</head>
<body>

<h2>HTML Table</h2>

<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
</table>
</body>
</html>
```

#### 2.3 concept
```css
StartPosition:EndPosition {
 property: value;
}
```

#### 2.4 syntax 
```
a1: a5, b1:b5, c1:c5{
 property: value;
}
```

#### 2.5.1 sample1_after.html
![image](https://user-images.githubusercontent.com/110187513/181875453-bb9e7666-c83a-41da-9f44-036ab965c445.png)

#### 2.5.2 sample2_before.html
![image](https://user-images.githubusercontent.com/110187513/181875491-a2369fb5-1b06-4f20-9c4e-929571e0aa26.png)

#### 2.6.1 sample1.csv
```
Company,Contact,Country
Alfreds Futterkiste,Maria Anders,Germany
Centro comercial Moctezuma,Francisco Chang,Mexico
Ernst Handel,Roland Mendel,Austria
Island Trading,Helen Bennett,UK
Laughing Bacchus Winecellars,Yoshi Tannamuri,Canada
Magazzini Alimentari Riuniti,Giovanni Rovelli,Italy
```

#### 2.6.2 sample2.csv
```
Company,Contact,Country
a1, b1,c1,
a1,b1,c1
a1,b1,c1
a1,b1,c1
a1,b1,c1
a1,b1,c1
```

#### 2.6 concept.png
![image](https://user-images.githubusercontent.com/110187513/181875985-1f03bb30-9a61-4193-8549-ed8055cb080c.png)

#### 2.7 why?
1. don’t need id, class
2. "is fast", "easy"
3. easy and didactic to handle
4. look like something you know, something excel in css
5. is limited by the amount of content
6. If you need to convert an excel document to web format, an interesting alternative would be in my opinion … convert to html with the style in css, what I’m talking about here … is to have a syntax similar to excel to style the table which facilitates web excel formats with css-excel-stylish style

#### 3. Reference
- https://discourse.wicg.io/t/draft-idea-spec-proposal-formatting-a-table-in-css-like-excel/5868
- https://www.w3schools.com/EXCEL/index.php
- https://www.extendoffice.com/documents/excel/3593-excel-convert-cells-to-html-table.html
- https://www.excel-easy.com/
- http://dmcritchie.mvps.org/excel/xl2html.htm
- https://www.youtube.com/watch?v=eT-ZCIb2wqE
- https://www.w3schools.com/EXCEL/index.php
- https://www.w3schools.com/

**Comment by plinss** [comment]
A few problems with your proposal:

1) your syntax is indistinguishable from `tag:pseudo-class`, so that's a non-starter. You'd need some kind of syntax that namespaces your scheme, like a pseudo-class or pseudo-element function. E.g. `:table(x y, x y)`
2) HTML tables are not Excel, there is not a guaranteed regular grid. E.g. rows may have variable numbers of cells, cells may span columns and/or rows, you need to account for that. Do the row/column values go by DOM structure or visual layout (e.g. if a cell is `display: none` is it counted?)
3) Tables on the web can be created with CSS on top of any elements, how does this apply to non-table elements?
4) There's no precedent for Excel-like grid addressing on the web, it would be far more consistent with existing web features to use simple numbered rows and columns (vs numbered rows and lettered columns). The web is the web, we generally don't try to mimic non-web applications.

**Comment by raphael-louis-andress** [comment]
@plinss Hi! How are you? So... thank you for feedback ;D

**Comment by raphael-louis-andress** [comment]
@plinss solution!

#### 1. Overview
#### 1.0 sample0.css
```css
tr{ // all lines/columns
  background-color: #dddddd;
}
```

#### 1.1 sample1.css
```css
column:1 { // all lines by column 1
}
```

#### 1.2 sample2.css
```css
column:1-3 { // all lines by column 1, 2, 3
}
```

#### 1.3 sample3.css
```css
column:1-3, column:4-5 { // all lines by column 1, 2, 3 and column 4, 5
}
```

#### 1.4 sample4.css
```css
tr:1, tr:2, tr:3 { // only-positions (by position column and line)
  background-color: #dddddd;
}
```

#### 1.5 sample5.css
```css
column-row:1-3, column-row:4-5 { // all lines with column 1, 2, 3 and column/line 4, 5
}
```

#### 1.6 sample6.css
```css
col-tr:1-3{ // only-postion with array (by position column)
  background-color: #dddddd;
}
```

#### 2. Reasons
1. Is the same as css grid
2. Can facilitate the creation of grids
3. Column and row oriented
4. Inspirations (syntax): flexbox, css-grid, mediaqueries, box-sizing, selectors, pseudo-selectors.

#### 3. References
- https://www.w3schools.com/css/css_grid.asp
- https://www.w3schools.com/css/css_rwd_grid.asp
- https://www.w3schools.com/css/css_rwd_mediaqueries.asp
- https://www.w3schools.com/css/css_rwd_intro.asp
- https://www.w3schools.com/css/css3_user_interface.asp
- https://www.w3schools.com/css/css3_multiple_columns.asp
- https://www.w3schools.com/css/css3_box-sizing.asp
- https://www.w3schools.com/css/css3_mediaqueries.asp
- https://www.w3schools.com/css/css3_mediaqueries_ex.asp
- https://www.w3schools.com/css/css3_flexbox.asp
- https://www.w3schools.com/css/css3_object-fit.asp
- https://www.w3schools.com/css/css3_object-position.asp
- https://www.w3schools.com/css/css_units.asp
- https://www.w3schools.com/cssref/css_selectors.asp
- https://www.w3schools.com/cssref/default.asp
- https://www.w3schools.com/css/css_rwd_frameworks.asp
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
- https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by Loirooriol** [comment]
To select cells that are in columns 1-5, the spec defines `:nth-col(-n+5)` https://drafts.csswg.org/selectors-4/#the-nth-col-pseudo

More in general, to select cells that are in columns A-B, `:nth-col(n+A):nth-col(-n+B)`.

For rows you can similarly use `:nth-child()` or `:nth-of-type()` in order to count `<tr>`. It may be tricky if you want row indices in the whole table, but you have multiple tbodies and a thead, but should work well in simple cases.

**Comment by Crissov** [comment]
The pseudo-class selector `:nth-col(An+B)` is the solution already available indeed. 

However, I see no reason why there’s no corresponding `nth-row(An+B)` or even `:nth-cell(An+B, Cn+D)` (or independent _n_ and _m_). 

The col selectors apply logically, i.e. whenever a col-spanned `td` or `th` crosses that column, it matches. This is not possible with `tr:nth-child(An+B)` for rows that are crossed by a row-spanned cell.
