### ISSUE TITLE
[css-writing-modes-3] Propose to replace "'text-orientation: upright' to cause strong LTR" with author notes how to do it

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#755]
The [`text-orientation: upright`](https://drafts.csswg.org/css-writing-modes-3/#valdef-text-orientation-upright) has the following text:

> This value causes the used value of direction to be ltr, and for the purposes of bidi reordering, causes all characters to be treated as strong LTR.

This is a proposal to replace this text with notes for authors.

## Background

In TPAC, we discussed [test status](http://kojiishi.github.io/generate-w3c-implementation-report/css-writing-modes-3/status-2016-09.html) and this is one of the "Required Tests That Do Not Meet Exit Criteria". @fantasai expressed that she is not comfortable to exit CR without passing this. Some discussions made there were:

* While this is not needed for joining RTL scripts such as Arabic, it does make sense for non-joining RTL scripts such as Hebrew.
* This is considered as extremely rare, the only use case we saw was building signage.

I then made further investigations as below to come to this proposal.

## Workaround for authors

Authors can get almost the same effect by the following CSS:

```css
.vertical-upright {
  writing-mode: vertical-rl;
  text-orientation: upright;
  unicode-bidi: override;
  direction: ltr;
}
```

Note, this workaround does not work if it has child elements with `dir` attributes, or different values of `unicode-bidi` properties.

## Implementation status

* Blink [crbug.com/663281](http://crbug.com/663281), Edge [9713176](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9713176/), WebKit [wkb.ug/164507](http://wkb.ug/164507) does not implement.
* Gecko [1315892](http://bugzilla.mozilla.org/show_bug.cgi?id=1315892) implements partially, by inserting the RLO (the same effect as the workaround above) if the block has `text-orientation: upright`.
  - It has the same restriction as above.
  - It does not work when `text-orientation: upright` is applied to inline elements.
  - It does not change the used value of `direction`, and therefore other effects (e.g., logical properties, table cell orders, etc.) is not included.

## Proposal

Given there is an easy workaround for authors, and given implementations are very limited, this proposal is to replace the text with a note how authors can get this effect.

I'm fine with other options, such as:

* Keep the text as is, by making the test failures as an exception to exit criteria.
* Make it "should" or "may".

but after reviewing the workaround and status, it looks to me that it's better to let authors know how to do it, rather than keeping the text and non-interoperable behavior.

Thoughts?

**Comment by kojiishi** [comment]
On second thought, the note might be better to recommend `<bdo dir="ltr">`, IIUC that is more preferred, correct?

**Comment by frivoal** [comment]
I think this is a case where we know what the right thing to do is, we know how to spec it, and the only problem is implements not prioritizing it due to it being a corner case.

For such things, I'd suggest marking the feature at risk, with a note that if we fail to get 2 implementations, we'll drop the requirement from must to should for this level (with the intent to bring it back as a must in a later level).

Adding a note for authors telling them how to work around it if a browser does not follow the recommendation sounds useful as well, but I'd want that in addition to the normative prose, not instead of it, as we still want to push implement to do the right thing eventually.

**Comment by kojiishi** [comment]
I agree it is the right thing, but I think making the right thing possible and making the right thing fully automatic are two different things.

In my personal opinion, when it is interoperably possible, and when it is automatic only under certain condition in one implementation, making it fully interoperable looks better for authors to me.

So the proposal is for better for authors, but I'm fine with at risk or other options if people think differently.

**Comment by jfkthame** [comment]
I think it's pretty clear that treating all the characters as strong LTR (so that upright Hebrew letters appear top-to-bottom, for example) is the right thing to do. It's less clear -- at least to me -- that it's desirable for `text-orientation:upright` to affect the used value of `direction`, with all the additional effects that implies (such as on table cell ordering). If an author actually wants *that* result, surely the natural way to achieve it is by specifying the proper (LTR) `dir` attribute, not as a side-effect of controlling the character orientation.

**Comment by jfkthame** [comment]
> I agree upright Hebrew appear top-to-bottom, but less sure about how. Complex cases are like:

    <div class=U><span dir=rtl>ABC</span></div>

> The "ABC" is still strong LTR, correct?

Yes, I think so; and so it appears as

    A
    B
    C

in top-to-bottom order.

    <div class=U>
      ABC
      <span class=R>DEF</span>
      GHI
      <span class=R>JKL</span>
      MNO
    </div>
> 
> The "DEF" and "JKL" are RTL so reordering occurs, as "ABC LKJ GHI FED MNO", correct?

I'm not sure I understand you here, or perhaps I disagree. The characters "DEF" and "JKL" are RTL and so will reorder to "FED" and "LKJ" respectively; but I don't expect them to swap places within the overall-LTR (top-to-bottom) line of text. So the visual result (using lowercase to stand in for glyphs that are rotated 90° clockwise) should probably be:

    A
    B
    C
    f
    e
    d
    G
    H
    I
    l
    k
    j
    M
    N
    O

Does that make sense to you?
 
    <div class=R>
      ARABIC TEXT HAS
      <span class=U>SYMBOL1</span>
      AND
      <span class=U>SYMBOL2</span>
      IN A PARAGRAPH.
    </div>

> The two symbols are strong LTR so reordering occurs, making "SYMBOL2" visually earlier than "SYMBOL1", correct?

Again, I don't think the SYMBOL1 and SYMBOL2 spans will swap places within the overall-RTL paragraph. The ARABIC TEXT... as a whole will run bottom-to-top, so SYMBOL1 will appear (upright, and top-to-bottom if it has multiple characters) first (lower down in the line), and SYMBOL2 will appear higher:

    .
    .
    .
    a
    r
    a
    p

    a

    n
    i

    S
    Y
    M
    2

    d
    n
    a

    S
    Y
    M
    1

    s
    a
    h

    c
    i
    b
    a
    r
    a

(abbreviating your example a bit to save space). Reasonable?

**Comment by kojiishi** [comment]
>> The "ABC" is still strong LTR, correct?

> Yes, I think so; and so it appears as

I thought authors would not want `dir=rtl` be ignored, if that's a false assumption, good.

>> The "DEF" and "JKL" are RTL so reordering occurs, as "ABC LKJ GHI FED MNO", correct?

> I'm not sure I understand you here, or perhaps I disagree.

You're right, sorry, the "ghi" must not be strong. [test on Unicode Utilities](http://unicode.org/cldr/utility/bidi.jsp?a=abc+DEF+ghi+JKL+mno%0D%0Aabc+DEF+%2B+JKL+mno&p=LTR&hack=on)

> Again, I don't think the SYMBOL1 and SYMBOL2

Sorry, again, "and" should not be strong. [test on Unicode Utilities](http://unicode.org/cldr/utility/bidi.jsp?a=ARABIC+TEXT+HAS+s+AND+t+IN+A+PARAGRAPH.%0D%0AARABIC+TEXT+HAS+s+%26+t+IN+A+PARAGRAPH.&p=RTL&hack=on)

**Comment by kojiishi** [comment]
[RESOLVED](https://lists.w3.org/Archives/Public/www-style/2016Dec/0042.html): Add a note along the lines of koji's example telling authors how to work around the lack of correct impl.
