### ISSUE TITLE
[css-color] Should it be possible for UAs to limit the number of colors in contrast-color()

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#7559]
Should there be a note in the spec. that user agents may limit the number of colors allowed in `contrast-color()` for performance reasons? And if so, should it define in which stage of evaluation (parsing, computed value or used value) those restrictions should be applied?

Related to this, are there already notes for other value lists like list-valued properties or gradient lists? And do user agents currently limit the number of values in such lists? 

Sebastian

**Comment by LeaVerou** [comment]
Has there been such an ask from implementors so far? If not, there's no reason to preemptively introduce this restriction.

**Comment by svgeesus** [comment]
Are there similar limits on, for example, the number of backgrounds you can specify?

**Comment by tabatkins** [comment]
There is not, no. We have minimum required limits that apply generically, but no specified maximums aside from a very small set of exceptions (the size of a grid, for example, has an allowed maximum).

**Comment by SebastianZ** [comment]
>  We have minimum required limits that apply generically

That pointed me into the right direction. So thanks!
With [only 20 repetitions required](https://drafts.csswg.org/css-values-4/#component-multipliers), it is actually already possible for UAs to (strictly) limit the number of colors.
And it also answers my question regarding other list-valued properties.

Sebastian
