### ISSUE TITLE
[cssom] Consider making CSSStyleRule.selectorText readonly

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#756]
Setter of `CSSStyleRule.selectorText` is never implemented in Gecko and Edge, Only WebKit (and Blink inheritably) has it.

It doesn't seem to be something highly desired, and when needed, it is also easy to polyfill, and the polyfill isn't supposed to have much performance penalty than what can be done by the browser (rule parsing is cheap, selector matching is unavoidable).

Given these, I suggest we make it readonly in the spec and suggest Blink and WebKit to remove their setter impl.

**Comment by FremyCompany** [comment]
No strong opinion. Would this be difficult to implement in Gecko?

**Comment by upsuper** [comment]
Not necessary difficult. And it seems there is a volunteer going to implement this in Gecko. Closing this.

**Comment by FremyCompany** [comment]
Filed https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11255650/ publicly to keep track of this. I don't expect this to be worked out anytime soon though.
