### ISSUE TITLE
[css-animations-2] Scoping keyframe names between UA and developer styles.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7560]
Currently there is no way to scope keyframe names declared in styles in user-agent origin vs author rules. For example, consider the following declaration in a user agent stylesheet, used [here](https://tabatkins.github.io/specs/css-shared-element-transitions/#animate-a-page-transition)

```css
@keyframes page-transition-fade-in {
  from { opacity: 0; }
}

::page-transition-incoming-image {
    animation: page-transition-fade-in 0.25s both;
  }
}
```

This has 2 problems:

* If the author declares a keyframe with the same name for a different animation, it will incorrectly override the keyframe selected for the rule in the user-agent stylesheet.
* If the keyframe with the same supplied by the author is missing, the declaration in the user-agent stylesheet will be used incorrectly.

We need a way to scope keyframe names between styles in the user-agent origin vs author styles. A couple of options are:

- Come up with a prefix which is reserved for UA rules. It will be an error for author keyframes to use this prefix. This will have compat issues to figure out the right prefix.

- Keep a separate list of keyframes declared in user-agent stylesheets vs author stylesheets. The list chosen when selecting the animation-name depends on where the resolved animation-name came from. This means if the animation-name was specified in a UA stylesheet but overridden by an author style (possibly with the same name), the look up is in author keyframe names.

  One of the caveats with this is script APIs like AnimationEvent include animation-name and which keyframe it corresponds to would be ambiguous. We could add another field to such APIs (bool isUASource) specifying the namespace for the rule.

@flackr @vmpstr @jakearchibald

**Comment by tabatkins** [comment]
Yeah, this seems like a reasonable thing to do. I'd be fine with reserving the single-dash set of names (already used for vendor prefixes), or we could add a function that namespaces an ident, like `ua(page-transition-fade-in)`

**Comment by jakearchibald** [comment]
I'm happy with either of those

**Comment by khushalsagar** [comment]
@tabatkins do you have a preference for a function/prefix vs implicit scoping based on which stylesheet the declaration is in? With the prefix/function every keyframe declaration in a UA stylesheet should have ua(foo) and no keyframe in author stylesheets should have that. So the implicit approach seems more straightforward.

The only downside of implicit is that author stylesheets can not use a keyframe declaration in UA stylesheets but we don't have a use-case for that anyway.

**Comment by tabatkins** [comment]
Carrying around implicit source information that isn't textually reflected in any way isn't great. We ended up doing it for shadow-scoped names, for example, and while I think we ended up on the best overall solution, it's still not great that a no-op that set the current style to itself can actually change the meaning of the style (by changing the tree that you're looking up the reference in).

I'd personally strongly prefer a textual mechanism to differentiate the two. That also avoids problems with scripting APIs, as you listed in the OP, which would need to carry the source data out-of-band.

**Comment by khushalsagar** [comment]
Let me try to clarify the details for the explicit proposal:

* Each keyframe declaration in the UA stylesheet will have a CSS function to scope it:
  ```css
    @keyframes ua(fade-in) {
      from { opacity: 0; }
    }

    div {
      animation: ua(fade-in);
    }
  ```

  > I'd be fine with reserving the single-dash set of names (already used for vendor prefixes)
  
  I think you meant -fade-in instead of ua(fade-in) but turns out that a [single dash is valid syntax](https://jsbin.com/motulamesa/edit?html,output) for custom idents today. I thought we could do --fade-in but double dash is for custom properties. Open to other suggestions though.

* If the same keyframe declaration is used in any stylesheet other than user-agent origin it will rejected at parsing time. This includes both @keyframe and when applying the keyframe to the animation-name property. I'm flexible on the last one though. The limitation avoids the keyframes being used for cases other than what the UA generated them for.

I'm ok with this option too.

**Comment by tabatkins** [comment]
> Each keyframe declaration in the UA stylesheet will have a CSS function to scope it:

We don't necessarily need to tag the `@keyframes` name specially. I was envisioning `ua(foo)` just referring to a `@keyframes foo` in a UA-origin style sheet. But either way works.

> I think you meant -fade-in

Yes, in that part I was referring to just using a custom-ident with a single-dash prefix, rather than a function.

> but turns out that a [single dash is valid syntax](https://jsbin.com/motulamesa/edit?html,output) for custom idents today

It is, yeah, tho I'm not sure what existing usage is. We could potentially ban this naming pattern from the production, or perhaps just a `-ua-` prefix for use here.

> If the same keyframe declaration is used in any stylesheet other than user-agent origin it will rejected at parsing time.

If we went with a special naming convention in the `@keyframes` rule, then yes, it would be invalid to write `@keyframes ua(foo) {...}` anywhere but a UA style sheet.

> This includes both @Keyframe and when applying the keyframe to the animation-name property. 

Sure. As you say, it's not strictly necessary to ban it from being used in `animation-name` outside a UA style sheet, but doing so makes it less likely that pages can depend on precise details of the animation, thus allowing us some freedom to tweak it in the future.
