### ISSUE TITLE
[css-cascade-5]Clarify the behavior of a empty `@layer` before `@import`

### ISSUE THREAD

**Issue by yisibl** [w3c/csswg-drafts#7566]
https://www.w3.org/TR/css-cascade-5/#at-import

> Any [@import](https://www.w3.org/TR/css-cascade-5/#at-ruledef-import) rules must precede all other valid at-rules and style rules in a style sheet (ignoring [@charset](https://www.w3.org/TR/css-syntax-3/#at-ruledef-charset) and empty [@layer](https://www.w3.org/TR/css-cascade-5/#at-ruledef-layer) definitions) and must not have any other valid at-rules or style rules between it and previous @import rules, or else the @import rule is invalid.

Ignoring `@layer` in this case is well understood and uncontroversial:

```css
@layer bar;
@import "foo.css";
```

However, the following case is not specified in the specification. The `@import` will be invalidated in the browser. The [implementation in SWC](https://github.com/swc-project/swc/pull/3842) is the opposite, and the CSS parser implementor may have misunderstood.

```css
@layer {}
@import "foo.css";
```

I think the specification should add an example.

**Comment by Loirooriol** [comment]
See https://drafts.csswg.org/css-cascade-5/#layer-empty

> The [`@layer`](https://drafts.csswg.org/css-cascade-5/#at-ruledef-layer) rule can also be used to define new layers without assigning any style rules, by providing only the [layer name](https://drafts.csswg.org/css-cascade-5/#layer-name):
> 
> `@layer <layer-name>;`
> 
> Such empty [`@layer`](https://drafts.csswg.org/css-cascade-5/#at-ruledef-layer) rules are allowed before [`@import`](https://drafts.csswg.org/css-cascade-5/#at-ruledef-import) and `@namespace` rules (after the [`@charset`](https://drafts.csswg.org/css-syntax-3/#at-ruledef-charset) rule, if any) as well as everywhere `@layer` [block at-rules](https://drafts.csswg.org/css-syntax-3/#block-at-rule) are allowed.

So I guess that the "empty [`@layer`](https://www.w3.org/TR/css-cascade-5/#at-ruledef-layer) definitions" from your quote refers to `@layer` statement at-rules, not to `@layer` block at-rules.

**Comment by yisibl** [comment]
@Loirooriol Yes, indeed, it would be nice to have an example in the specification.

**Comment by fantasai** [comment]
@yisibl There already is an example in https://www.w3.org/TR/css-cascade-5/#layer-empty showing the validity of the first case.

Wrt the empty blocks, clarified that in https://github.com/w3c/csswg-drafts/commit/b14636c2b6ebea0fd1e9dae306351491f910203a Let me know if that works for you!

**Comment by yisibl** [comment]
@fantasai Thanks, this is very helpful and swc will track improvements in this issue https://github.com/swc-project/swc/issues/5643.
