### ISSUE TITLE
[css-animations-1] Invalid syntax for `animation-duration`

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#7570]
The `animation-duration` property lists it's syntax as `<time [0s,∞]>`.  The `s` character is not allowed in the numerical range definition.

https://github.com/w3c/csswg-drafts/blob/5a93662258eb8e17ef19a3b236dcdb79c32c1ad2/css-animations-1/Overview.bs#L507

**Comment by dbaron** [comment]
This seems like a bug in the value definition syntax; I think the unit should be required, since the unit is required in the actual value.

Also see #7572.

**Comment by tabatkins** [comment]
Invalid, per the fix in #7572.
