### ISSUE TITLE
[css-fonts-4] Invalid syntax for 'font-style' property

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#7571]
The font-style property includes the angle type (`deg`) in the numerical range of the `<angle>` type.  This is not allowed per CSS value definition syntax.

https://github.com/w3c/csswg-drafts/blob/5a93662258eb8e17ef19a3b236dcdb79c32c1ad2/css-fonts-4/Overview.bs#L790

**Comment by dbaron** [comment]
This sounds like a bug in the value definition syntax; I think the unit should be required, since the unit is required in the actual value.  In this case, it would also be much less readable without the unit.

See also #7570, #7572.

**Comment by tabatkins** [comment]
Invalid, per the fix in #7572.
