### ISSUE TITLE
[css-transitions-1] Invalid syntax for 'transition-duration' property

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#7572]
The transition-duration property includes the time unit identifier (s) in the numerical range of the `<time>` type. This is not allowed per CSS value definition syntax.

https://github.com/w3c/csswg-drafts/blob/5a93662258eb8e17ef19a3b236dcdb79c32c1ad2/css-transitions-1/Overview.bs#L318

**Comment by pyoor** [comment]
I don't think so as there could be multiple units associated with a ranged type.  Those units are inferred based on the type.  It would be less concise to list each unit everytime the vale type is referenced.

**Comment by dbaron** [comment]
I don't think [5.1. Range Restrictions and Range Definition Notation](https://drafts.csswg.org/css-values-4/#numeric-ranges) is clear either way about what it expects `min` and `max` to be.

I think "multiple units" is a good reason to include the units.  If a value is defined as `<length[1px,∞]>` it should be clear that a value of `0.1in` is still valid (larger than `1px`), while a value of `1.03q` is invalid (smaller than `1px`).

**Comment by pyoor** [comment]
Hmm, I can see how that would be useful.  However, it would still have to be an optional type as `<integer>`, `<number>`, `<percentage>`, and `<ratio>` do not include units.  Additionally, it's somewhat moot for this spec and #7570 as `<time [0s, ∞]>` is 0 whether it is seconds or milliseconds.  #7571 on the other hand, would require a unit in order to calculate the min/max for the other units.

**Comment by cdoublev** [comment]
`<time [0s, ∞]>` should/can be `<time [0, ∞]>`, I agree, cf. [#7400 (comment)](https://github.com/w3c/csswg-drafts/issues/7400#issuecomment-1163491519).

> So long as it's clear, I think the range limitation is fine without units, yeah. 0 and infinity are always clear; numbers/integers are correct anyway, and percentage has a single possible unit so non-zero values are clear too.

The initial argument for `0s` was that it is not a valid `<time>` but that is not necessary and `∞` and `∞s` are not valid `<time>` either. 

It would be nice to have these clarifications in CSS Value.

`<ratio>` expands to `<number [0,∞]> [/ <number [0,∞]>]?` but it may be noted as `<ratio [0,∞]>` in `<mf-value>` and `aspect-ratio` property, so as not to restrict future values which must accept negative ratios, similarly as `<length-percentage [0,∞]>`, noting that `<length-percentage [1px,∞]>` would be problematic when providing a percentage as input and shows some limitations of this range notation.

**Comment by tabatkins** [comment]
All right, clarified the text. Added an example of a `<length [0, 100px]>`, demonstrating both that units are allowed and unitless zeroes are, and added specific text about 0 and infinite values and units (must omit units on infinity, may omit them on zero).

**Comment by Loirooriol** [comment]
I don't like "expressed in any unit" when some units can't be converted into the canonical one at parse time. Filed #7584
