### ISSUE TITLE
[css-pseudo] highlight pseudos and compat stroke/fill properties

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#7580]
https://drafts.csswg.org/css-pseudo-4/#highlight-styling

> The following properties apply to the highlight pseudo-elements:
> * […]
> * [stroke-color](https://drafts.fxtf.org/fill-stroke-3/#propdef-stroke-color), [fill-color](https://drafts.fxtf.org/fill-stroke-3/#propdef-fill-color), and [stroke-width](https://drafts.fxtf.org/fill-stroke-3/#propdef-stroke-width)

[‘-webkit-text-fill-color’](https://compat.spec.whatwg.org/#the-webkit-text-fill-color), [‘-webkit-text-stroke-color’](https://compat.spec.whatwg.org/#the-webkit-text-stroke-color), [‘-webkit-text-stroke-width’](https://compat.spec.whatwg.org/#the-webkit-text-stroke-width), and [‘-webkit-text-stroke’](https://compat.spec.whatwg.org/#the-webkit-text-stroke) are unrelated to those SVG-only properties, but they work roughly the same way and are supported interoperably. WPT even has [a test for ::selection with ‘-webkit-text-fill-color’](http://wpt.live/compat/webkit-text-fill-color-property-003.html). Should we make these properties applicable to highlights?

(@fantasai, @frivoal, @mrego)

**Comment by fantasai** [comment]
This needs a clarifying note.
