### ISSUE TITLE
[css-transforms-2] Potentially invalid syntax for `perspective()`

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#7582]
The CSS Transforms 2 spec currently defines the `perspective()` function as:  
`perspective( <length [0,∞]> | none )`

In the syntax above, the functional notation accepts one of two arguments (using the single bar operator).  Now, I can't find anything specifically in css-values-5 that forbids this, but I believe that these arguments should be wrapped in a group as in:
`perspective( [ <length [0,∞]> | none ] )`

Could some please provide clarification on if this actually is an issue?

https://github.com/w3c/csswg-drafts/blob/77f40b2fa25dcb36dda6915c3eb2571b57405881/css-transforms-2/Overview.bs#L1003

**Comment by tabatkins** [comment]
Yup, that's an error.

**Comment by cdoublev** [comment]
Is it a syntax style error, or more? Where is this style defined?

- [CSS Overflow 4](https://drafts.csswg.org/css-overflow-4/#funcdef-text-overflow-fade) has `fade( <length> | <percentage> )`
- [Filter Effects 1](https://drafts.fxtf.org/filter-effects-1/#funcdef-filter-drop-shadow) has `drop-shadow( <color>? && <length>{2,3} )`

**Comment by tabatkins** [comment]
The [Syntax extension of the CSS grammar](https://drafts.csswg.org/css-syntax/#rule-defs) defines how at-rules and functions (and other things) are written in the grammar. It doesn't have any special rules for functions (or anything else) to automatically create groups in the grammar.

Perhaps it should, tho? Hm.

**Comment by cdoublev** [comment]
> It doesn't have any special rules for functions (or anything else) to automatically create groups in the grammar.

What are the cases (other than function arguments) where a group should be created automatically? Do these rules also explain why a group is created for the types specific to `font-variant-alternates` in the value definition of [`font-variant`](https://drafts.csswg.org/css-fonts-4/#font-variant-prop)?

I guess the reason for creating a group that is not strictly required, is to make a grammar parser produce a nested list with the corresponding value(s). From this perspective, it would have been nice to create groups for the types specific to `font-variant-ligatures`, `font-variant-numeric`, and `font-variant-east-asian`. It would make shorthand expansion easier, imo.

I'm sorry for this noise on a closed issue. Please tell me if I should create a new issue.

Related: #2921 

```
  normal 
| none 
| [
       # font-variant-ligatures
       <common-lig-values> || <discretionary-lig-values> || <historical-lig-values> || <contextual-alt-values> 
       # font-variant-caps
    || [small-caps | all-small-caps | petite-caps | all-petite-caps | unicase | titling-caps] 
    || [
            stylistic(<feature-value-name>) 
         || historical-forms 
         || styleset(<feature-value-name>#) 
         || character-variant (<feature-value-name>#) 
         || swash(<feature-value-name>) 
         || ornaments(<feature-value-name>) 
         || annotation(<feature-value-name>)
       ] 
       # font-variant-numeric
    || <numeric-figure-values> || <numeric-spacing-values> || <numeric-fraction-values> || ordinal || slashed-zero 
       # font-variant-east-asian
    || <east-asian-variant-values> || <east-asian-width-values> || ruby 
       # font-variant-position
    || [sub | super] 
       # font-variant-emoji
    || [text | emoji | unicode] 
 ]
```
