### ISSUE TITLE
css new standard idea

### ISSUE THREAD

**Issue by annopnod** [w3c/csswg-drafts#759]
css new standard idea
**code**
<style>
            #Data{
                width: 100px;
            }
            #Topic{
                width: #Data.width;// #Topic width= 100px;
            }
            #Topic2{
                width: #Data.width + 100px;// #Topic2 width= 200px;
            }

        </style>

**Comment by astearns** [comment]
See Custom Properties: https://drafts.csswg.org/css-variables-1/

Your sample can be expressed as:

<style> :root{ --data: 100px; } #Topic{ width: var(--data); } #Topic2{ width: calc(var(--data) + 100px) } </style>
