### ISSUE TITLE
[css-pseudo] highlight pseudos and non-applicable properties

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#7591]
https://drafts.csswg.org/css-pseudo-4/#highlight-styling

> The [highlight pseudo-elements](https://drafts.csswg.org/css-pseudo-4/#highlight-pseudo-element) can only be styled by a limited set of properties that do not affect layout and can be applied performantly in a highly dynamic environment—and additionally (to ensure interoperability) whose rendering within the [required area](https://drafts.csswg.org/css-pseudo-4/#highlight-bounds) is not dependent on the exact (UA-determined) bounds of the [highlight overlay](https://drafts.csswg.org/css-pseudo-4/#highlight-overlay). The following properties apply to the highlight pseudo-elements:

Given the following example, and ‘font-size’ not being applicable to highlights, with an initial value of 16px:

```html
<style>
    main, aside { font-size: 42px; }
    main::selection { font-size: 69px; }
    *::selection { text-shadow: green 0 1em; }
</style>
<main>Hello, world!</main>
<aside>Goodbye, world!</aside>
```

1. **What is the computed value of ‘font-size’ in main::selection?** In other words, can non-applicable properties participate in the cascade for highlight pseudos? Blink currently says no (it uses a “ValidPropertyFilter” to enforce applicable properties in pseudos), but @andruud says yes (69px) based on [css-cascade #applies-to](https://www.w3.org/TR/css-cascade/#applies-to).

2. **What is the computed value of ‘font-size’ in aside::selection?** In other words, what happens when the highlight cascade does not yield a value for a non-applicable property? Blink currently says we use the initial value (16px). I feel like the originating element’s value (42px) is the most intuitive, but I am also not sure that would be easy to implement, even more so if the answer to question 1 is “yes”.

3. **How far are the ::selection text shadows offset vertically?** Blink says both are 1em times initial (16px), but I feel like in an ideal world it would be 42px or 69px for main::selection, and 42px for aside::selection. Blink’s current behaviour is inconsistent with how shadows would work in a non-highlight-pseudo rule, and a violation of least astonishment.

(@fantasai, @frivoal, @mrego)

**Comment by fantasai** [comment]
That's a very interesting question! I think I lean towards ignoring declarations of non-applicable properties, so you'd get a computed font-size of 42px and a 42px text-shadow offset. I think this would give the most reasonable and useful results, from an author's perspective.

**Comment by andruud** [comment]
But _ignoring_ would get you the initial value (typically font-size:16px), not 42px?

**Comment by schenney-chromium** [comment]
We would like to re-open this issue at the F2F as the chromium implementation has diverged and the result seems to give more intuitive results.

As currently implemented in chromium an element with any highlight pseudo, including ::selection, will use font dependent metrics from _the originating element_ when resolving lengths (such as 1em). As delan says, this aligns with the current spec for ‘forced-color-adjust’ and forced colors mode (see https://github.com/w3c/csswg-drafts/issues/7264).

The existing resolution talks about the root element, saying that font metrics should be taken from the element for highlight rendering, but does not say what would happen at other elements. The implementation in chromium expands the approach to every element in the tree. This avoids unexpected behavior when ::selection would pull metrics from the root while *::selection would pull from the initial value.

**Comment by schenney-chromium** [comment]
Note the resolution did not address the very first question, which is whether to apply the [css-cascade #applies-to](https://www.w3.org/TR/css-cascade/#applies-to) rules. In chromium, _assuming it's feasible_, we will say "yes", you can set a font-size property which will affect font-size-dependent lengths. If there's no font size we use the originating element font. Also, container queries can influence lengths, and there we will also attempt to use the originating element to resolve the container query.

A question came up about shadow trees. Looking at the implementation, it seems chromium uses the shadow root as the originating element for the purpose of forced-color-mode etc. We continue to do that and revisit the implementation if it seems to cause problems.

**Comment by andruud** [comment]
Are these resolutions saying that font-relative units within the highlight resolve against the originating font-size, but font-size itself (on the highlight) is not affected?

**Comment by schenney-chromium** [comment]
To help developers understand which font is used for resolving metrics, we'll be reporting the font size, line height and other related properties on the highlight's getComputedStyle. Sometime in the next week I'll update the spec draft.

**Comment by fantasai** [comment]
@schenney-chromium I merged your PR, but also added a fix-up commit https://github.com/w3c/csswg-drafts/commit/3b3a022fc56f4f6d91b69a88ed79d0f23d374fd1 ; take a look and 1) make sure it's all correct and 2) try to understand why I made the changes I did for next time, and if any of it doesn't make sense ask me about it. :) Hopefully it's all straightforward.

**Comment by schenney-chromium** [comment]
Thanks for landing and correcting. My understanding of the simplified text is that this is a spec, focused more on "what" should happen and not "why". I'll keep that in mind with future edits.
