### ISSUE TITLE
[css-ruby] inlined annotations need to be full size

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#760]
A.2 Inlining Ruby Annotations
https://drafts.csswg.org/css-ruby-1/#default-inline

> The following represents a sample style sheet for rendering HTML and XHTML ruby markup as inline annotations:
> 
> ruby, rb, rt, rbc, rtc, rp {display: inline; white-space: inherit;
> font-variant-east-asian: inherit; text-emphasis: inherit; }

I believe you also need `font-size: inherit;` so that the ruby annotation is the same size as the base text.

**Comment by upsuper** [comment]
I guess you would need `line-height: inherit;` as well.

**Comment by fantasai** [comment]
Quick fix: switch to `font: inherit`. ;)
