### ISSUE TITLE
[css-color-3] the 'opacity' property

### ISSUE THREAD

**Issue by letochagone** [w3c/csswg-drafts#7605]
in the paragraph https://www.w3.org/TR/css-color-3/#transparency , I would like to understand the following text:

>   **If the object has children, then the effect is as if the children were blended against the current background
> using a mask where the value of each pixel of the mask is <alphavalue>**

Is it possible to illustrate it with an example including `div `s with their RGBA and an 'opacity'?

I mean, using , for example, the following formula: Cs = (1 - αb) x Cs + αb x B(Cb, Cs)

**Comment by svgeesus** [comment]
The `opacity` property operates independent of alpha, and apples to an entire subtree.

The effect is as if the whole subtree is rendered to an offscreen buffer, including any alpha transparency. That buffer is then blended against the current background, applying the opacity.

**Comment by letochagone** [comment]
OK, here's an example to see if I understood correctly:
```
<div id="div1" style="background-color: rgba(22, 177, 200, 0.4); opacity: 0.7;">
	<div id="div2" style="background-color: rgba(100,200,50,0.5);"></div>
</div>
```
call:
Cs , as  :  rgba of the div2
Cb , ab  : rgba of the div1
co the resulting color of div2 on div1:
co = Cs **as * opacity** + Cb * **ab * opacity** * ( 1 - **as * opacity** )

co = (100/255, 200/255, 50/255) * 0.5 * 0.7 + (22/255,177/255,200/255) * 0.4 * 0.7 * (1-0.5*0.7)
I think that is correct?
