### ISSUE TITLE
[css-color] Is version-less URL redirect to level 5 intended?

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#7609]
The [ED of CSS color 4](https://drafts.csswg.org/css-color-4/) has a "This Version" link that points at https://drafts.csswg.org/css-color/
The [TR version of CSS Color 4](https://www.w3.org/TR/css-color-4/) also links to https://drafts.csswg.org/css-color/ for the Editor's Draft.

However, https://drafts.csswg.org/css-color/ now redirects to level 5 of the spec, which is a delta spec. Is that intended? Should the redirect rule on drafts.csswg.org be rolled back to rather target level 4, and/or could the URLs in the ED and in next TR revisions be updated to explicitly target `css-color-4`?

(via https://github.com/w3c/webref/issues/689)

**Comment by svgeesus** [comment]
> However, https://drafts.csswg.org/css-color/ now redirects to level 5 of the spec, which is a delta spec. Is that intended?

No, that is not intended, and should be reverted back. I'm not sure why that change happened.

**Comment by fantasai** [comment]
Fixed.

@svgeesus if there's an administrative error, please poke someone on IRC or something, don't just comment and disappear!!
