### ISSUE TITLE
[css-ruby-1] Proportional or fullwidth parens?

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#762]
A.3 Generating Parentheses
https://drafts.csswg.org/css-ruby-1/#default-parens

The CSS code in this section applies ordinary parens '(' and ')' to inline ruby annotations.  Shouldn't they be fullwidth parens?

**Comment by kojiishi** [comment]
Agree it should be.

**Comment by frivoal** [comment]
Ruby is primarily meant for CJK, but it can be used for annotations in any languages, and only CJK uses full width parens. Should the selector be specialized by `:lang()` to use full width parens in CJK, and half width otherwise?

**Comment by kojiishi** [comment]
Why don't we default to CJK when the primary use is CJK?

**Comment by frivoal** [comment]
If we provide a switch, CJK is a finite set of language, while the rest isn't, is its easier to say `if(CJK) {...} else { ..... }` than it is to say `if (en, fr, de, no, it, ru, th, sv, ..................) else { CJK stuff }`, if you forgive my lousy pseudo code.

I don't think it would be too bad if we just applied the styles CJK wants for all languages, and let authors override that if they're using it for something else, but I thought that as the `:lang()` selector let's us express the difference, we might as well do so.

**Comment by r12a** [comment]
I believe that we shouldn't emphasise the idea that ruby markup/styling can be used for non CJ languages, since it's really designed specifically with those in mind (which is why it's called 'ruby' rather than 'glossing' or 'annotation') and it lacks features needed for general glossing.

Appendix A however is an odd beast. As i understand it, subsection A.1 is the default style sheet referred to in the heading of App A, but subsections A2 and A3 are really more akin to guides for content authors (not to mention the fact that they don't work for all markup).  If i'm right, then it seems to me that it's best to use fullwidth parens for this example and we can leave it to the content author to adapt the code for other languages.  (Note that the content author may also choose to use a different type of bracket altogether.)

Also, perhaps we should split Appendix A?

**Comment by upsuper** [comment]
I agree that we shouldn't emphasize usage in non-CJK. Actually I believe ruby is more likely to be used on untagged / mistagged CJK content than any language else.

**Comment by frivoal** [comment]
> Actually I believe ruby is more likely to be used on untagged / mistagged CJK content than any language else

Fair enough.

**Comment by r12a** [comment]
Thanks for the edits.  I'm satisfied with this resolution.  I'll check that the i18n WG agrees, and unless there's an objection, we'll just close our tracker.
