### ISSUE TITLE
[css-sizing-3] drafts.csswg.org/css-sizing-3 leads to a directory index page instead of a rendered document.

### ISSUE THREAD

**Issue by rreno** [w3c/csswg-drafts#7624]
Title.

This breaks links into the css-sizing-3 draft from other drafts such as css-flexbox As an example, the https://drafts.csswg.org/css-flexbox/#intrinsic-sizes directs you to css-sizing-3 to view the definitions in the intrinsic-sizes section of flexbox. That links you to a directory index page.

Latest revision's rendered document available via https://drafts.csswg.org/date/2022-06-29T01:09:58/css-sizing-3/ URL.

**Comment by SebastianZ** [comment]
If you mean the link to https://drafts.csswg.org/css-sizing-3/#intrinsic-sizing, that is working fine for me.

I assume this was a temporary issue related to #6528. Or can you still reproduce the issue, @rreno?

Sebastian

**Comment by rreno** [comment]
No longer reproduces for me either, must have been related. Thank you for checking.
