### ISSUE TITLE
[css-color-5] Example 10, incorrect color function used

### ISSUE THREAD

**Issue by dom111** [w3c/csswg-drafts#7625]
In Example 10 of the Relative Colors section (https://www.w3.org/TR/css-color-5/#relative-colors) there is an example of using the `from` syntax to generate a color with 80% alpha channel, but the `rgb()` definition is used, rather than `rgba()`.

This should be updated to `rgba()` unless I'm missing something from further back that defines this as ok, if so, a note could be added here to clarify.

**Comment by faceless2** [comment]
Since css-color-4 the `rgb()` function can take an alpha value, and the `rgba()` function is now considered a legacy syntax: See https://www.w3.org/TR/css-color-4/#rgb-functions and https://www.w3.org/TR/css-color-4/#legacy-color-syntax

```css
rgb(from var(--bg-color) r g b / 80%);
```
That syntax is correct.

**Comment by dom111** [comment]
Thanks for confirming @faceless2!
