### ISSUE TITLE
[css-backgrounds-3] Use lowercase `currentcolor` for initial property values

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7629]
[`border-<side>-color`](https://drafts.csswg.org/css-backgrounds-3/#border-color) are defined with `currentColor` (camel case) as their initial value, instead of `currentcolor` (lowercase). 

This prevents simplifying the serialization of `border`, `border-color`, `border-<side>`, when making use of the definitions extracted from the spec by `w3c/webref` to compare the `initial` longhand value to the longhand declaration values used to serialize these shorthands.

`currentcolor` always appear lowercase in CSS Color 4. Also, I think it is more accurate to define `initial` fields to a value that matches their serialization as a component of a specified value (keywords serialize to lowercase), not as an input with arbitrary case.

Please tell me if you want me to create a PR, if you agree.

**Comment by svgeesus** [comment]
The note at the end of https://drafts.csswg.org/css-color-4/#currentcolor-color may be instructive. `camelCase` isn't arbitrary.

> This prevents simplifying the serialization of border, border-color, border-<side>, when making use of the definitions extracted from the spec by w3c/webref to compare the initial longhand value to the longhand declaration values used to serialize these shorthands.

webref should probably be applying the CSS ASCII-case-insensitive rule to keywords.

**Comment by cdoublev** [comment]
> webref should probably be applying the CSS ASCII-case-insensitive rule to keywords.

This is one of the two reasons why I wanted to close this issue. I was not sure but I think it is safe to lowercase all `initial` field values. 

The second reason is that simplification of values for serialization is not really defined. There is only *If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.*

Chrome do not simplify `border: medium none currentcolor` whereas Firefox serializes it to `border: medium none`. I think I read somewhere why Firefox removes `currentcolor`. My intention was to omit the initial values in canonical order until only one remains... 

Anyway, I still think that the `initial` field should represent a value as if it were serialized, because this is what the user will see with `console.log(style.borderColor)`, but there are too many open issues much more important than this one.
