### ISSUE TITLE
[css-align] place-items shorthand has wrong grammar

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#763]
https://drafts.csswg.org/css-align/#place-items-property
The grammar allows `auto` in the first (or single) value.
It shouldn't allow it because `align-items` doesn't have an `auto` value:
https://drafts.csswg.org/css-align/#propdef-align-items

So, I think the correct grammar should be:
```
<x> = [ normal | stretch | <baseline-position> | <self-position> ]
place-items:  <x> [ auto | <x> ]?

```
IOW, `auto` should only be allowed as a second value.

**Comment by fantasai** [comment]
I'm assuming nobody implements the `legacy` value. I think we should just get rid of it until we have a clear indication that that's how we want to solve <div align>; that would also get rid of `auto` here.

**Comment by MatsPalmgren** [comment]
> I'm assuming nobody implements the `legacy` value.

Firefox implements all values for `justify-items`, including `legacy` and the special rules about that.

I quick check in Chrome devtools shows that they support `legacy` too.

**Comment by fantasai** [comment]
Ok, wow. I remember dbaron raising concerns about that. Is that replacing the text-align values for implementing <div align> now?

**Comment by MatsPalmgren** [comment]
No, Gecko only supports CSS Align in Grid and Flexbox _layout_ currently.
We do **not** support any of the CSS Align properties in Block/Table/Multicol _layout_ **at all**.
We intend to implement _layout_ support for CSS Align on a "per module" basis, i.e. support
all of it for Block, then support all of it for Table etc.  Doing it all at once is just too much
with Mozilla's limited resources.  We could of course delay Grid and Flexbox support
until we've implemented it everywhere, but that would delay Grid for a year or more
and I don't think anyone wants that.

Note the word _layout_ above though.  The CSS Align properties are fully implemented
and enabled in the style system and that affects all box types, so they will show up as
computed values on blocks etc, it's just that they have no effect on the layout, except
for Grid/Flexbox.

(I think Chrome is taking a similar approach but I don't know the details.)

**Comment by MatsPalmgren** [comment]
The reason behind taking this all-or-nothing-per-module approach is to make it
easier for authors to know where these properties are supported.  For now they
are only supported in Grid/Flexbox layout, and not at all on anything else.  I think
it would be confusing for authors if the properties are supported in varying
degrees in different modules by different UAs.  That would lead to web-compat
problems eventually.  So I'm hoping that other UA vendors take a similar approach.
Perhaps we should coordinate what to support next?  (I think Block layout is the one
we've been discussing for Gecko.)

**Comment by fantasai** [comment]
I agree with your approach, and coordination sounds good.

Wrt `legacy`, I think we need to decide if the approach in the draft is actually one we want to take for handling `<div align>` etc, since that's the only reason it exists. The trickiest part of that is the style layer, though, so if you've already got that sorted maybe it's okay.

**Comment by javifernandez** [comment]
Hi,

On 11/26/2016 05:17 PM, Mats Palmgren wrote:
>     I'm assuming nobody implements the |legacy| value.
> 
> Firefox implements all values for |justify-items|, including |legacy|
> and the special rules about that.
> 
> I quick check in Chrome devtools shows that they support |legacy| too.
> 


Both Chrome/Blink and Safari/WebKit implements legacy keyword.

**Comment by javifernandez** [comment]
Hi,

On 11/26/2016 10:27 PM, Mats Palmgren wrote:
> Note the word /layout/ above though. The CSS Align properties are fully
> implemented
> and enabled in the style system and that affects all box types, so they
> will show up as
> computed values on blocks etc, it's just that they have no effect on the
> layout, except
> for Grid/Flexbox.
> 
> (I think Chrome is taking a similar approach but I don't know the details.)
> 

Our opinion as implementors of the spec in Chrome was to enable the CSS
Alignment feature, replacing the old syntax implemented by FF. The Chrome
community agreed and prioritized web compatibility, so they recommend to
follow what FF eventually does on this regard.  We are not sure what WebKit
will do, though, but we expect to follow the same approach.

Other than that, the 'legacy' implementation introduced several complexities
in the style resolution logic; in the same line than the effort we had
to do to
satisfy the 'auto' value resolution for the self-alignment properties.
Now that
have have got rid of those 'auto' values resolution, it's the perfect moment
to take a decision on this legacy keyword issue.
