### ISSUE TITLE
[css-fonts-4] Define `value` of `src` with a valid value definition

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7632]
The `value` field of [`src`](https://drafts.csswg.org/css-fonts-4/#descdef-font-face-src) is defined with `see prose`. Would it be possible to use a valid value definition according the CSS value definition syntax?

I know that `src` must be parsed in a [specific way](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing), similarly to `<media-query-list>` and `<forgiving-selector-list>`. So I suggest to set its `value` with something like `<font-src-list>` that would reference this specific procedure, which should take advantage of [*parse a comma-separated list according to a CSS grammar*](https://drafts.csswg.org/css-syntax-3/#parse-comma-list) with `<font-src>` as the CSS grammar.

~~Also, I think it could be helpfull for CSS authors to remove invalid items from the serialization, like invalid media query or selector.~~ *edit:* invalid selectors in `<forgiving-selector-list>` and invalid/unknown media queries in `<media-query-list>` are now preserved - https://github.com/w3c/csswg-drafts/issues/8356#issuecomment-1642840607, https://github.com/w3c/csswg-drafts/issues/7595#issuecomment-1284268421.

**Comment by svgeesus** [comment]
Want to make a PR for this?

**Comment by cdoublev** [comment]
Note that one thing I left undefined is the handling of invalid `<font-src>`. Should they be preserved or removed? At parse time? At serialization time? 

Chrome/FF (at least) currently remove invalid `<font-src>`, like in `<forgiving-selector-list>` (at parse time, as [specified in step 2](https://drafts.csswg.org/selectors-4/#parse-as-a-forgiving-selector-list)):

```html
<style>
  @font-face { src: invalid, local(my-font) }
  :is(;, type) {}
</style>
<script>
  document.styleSheets[0].cssRules[0].cssText; // '@font-face { src: local(my-font); }'
  document.styleSheets[0].cssRules[1].cssText; // ':is(type) { }'
</script>
```

But people now wants to preserve invalid selectors (see issue linked in my first comment). 

In `<media-query-list>`, it is more complex because of back-compat.

That said, consistency may not be mandatory.

You may want to specify the current interoperable behavior right now, or wait for the outcome of the corresponding issues for `<forgiving-selector-list>` or `<media-query-list>`.
