### ISSUE TITLE
[css-fonts-4] Some font features should not be disable-able

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#7634]
Inside the [Script development specs](https://docs.microsoft.com/en-us/typography/script-development/arabic) section of the OpenType spec, it shows how [certain features](https://docs.microsoft.com/en-us/typography/script-development/arabic#features) are "always applied" for certain scripts.

One reason for this is that these features are required for legibility.

Another reason for this is, in the words of one of our platform text engineers (specifically about Arabic and `rlig`, which is one of the "always applied" features):

> Some Arabic fonts are fantastically complicated with all sorts of interlocking features, and I can imagine at least one of them will break in completely unexpected ways if `rlig` is not applied.

In the Cocoa ports of WebKit, we ensure that these "always applied" features are, in fact, always applied, regardless of what `font-feature-settings` indicates. We believe this is the best policy for user agents in general. We're not aware of any case where an author would intentionally want their text to be broken/illegible, and there are plenty of situations where an author could shoot themselves in the foot by disabling `rlig` (or others) accidentally.

(This is proposal is relevant to [`css/css-fonts/font-variant-ligatures-11.html`](http://wpt.live/css/css-fonts/font-variant-ligatures-11.html), which the Cocoa ports of WebKit are intentionally failing.)

**Comment by Crissov** [comment]
`font-feature-settings` is a low-level property. It’s there for authors to sort themselves in the foot with. Many do. Let them. 

For higher-level properties I would agree.

**Comment by svgeesus** [comment]
On the one hand, the "r" in `rlig` is for _required_.

On the other hand, there is a need for styling the "incorrect" class

```html
<p>Arabic letters have initial, medial, final and isolate forms
which means that they join together, even when separated by markup:
<span class="correct">ع</span>ع<span class="break">ع</span>
and render like this
<span class="correct">ععع</span>
not like this
<span class="incorrect">ععع</span></p>
```

Although, `zwnj` can always be used for these contrived examples.

**Comment by svgeesus** [comment]
(Example from [ALReq](https://www.w3.org/International/alreq/gap-analysis/#issue222_cursive) although they illustrate it with an image)

**Comment by faceless2** [comment]
We have WPT tests that do this with ZWNJ, eg [text-encoding/shaping-no-join-001.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/text-encoding/shaping-no-join-001.html)

As the only examples so far demonstrate arabic glyph-shaping, we should also consider the case where you might want to turn _on_ a feature, eg `init` or `medi` to show the glyph forms. But it all seems pretty specialised, and while demoing glyph forms in Arabic almost works as a use-case, disabling (for example) `nukt` in Devanagari is going to just give nonsense shapes as I understand it.

Rather than mandate it one way or another, would be it acceptable to add a note to the effect that turning of (or on) rules required that are required for language shaping is not advised and is UA dependent? We've long had this test marked as invalid, as we also don't turn allow turning off `rlig`.

**Comment by litherum** [comment]
If an author really wants to get this wrong, they have ample opportunity:

1. Custom webfonts
2. PUA characters
3. Unicode presentation forms

Doing `font-feature-settings: 'rlig' off` is too easy for an author to do.

Also, I should say, there is nothing a Core Text client can do to disable these features. Even if you tell Core Text to disable them, Core text won't, because, well, they're _always enabled_.

**Comment by litherum** [comment]
(Removing the Agenda+ label to give discussion time on GitHub before this issue makes it to the call.)

**Comment by svgeesus** [comment]
In general, although I tried to see both sides in my earlier comment, I am much more in favor of helping authors to do the right thing. Demonstrating what the wrong thing looks like, is an edge case and can already be done in multiple ways.

**Comment by svgeesus** [comment]
Not mentioned so far, but the fact that the low-level `font-feature-settings ` is not additive, and will reset any feature not explicitly set, makes these sorts of mistakes especially common. So retaining basic legibility by disabling footguns seems like a great default.

**Comment by svgeesus** [comment]
The test mentioned at TPAC [is now marked .optional](http://wpt.live/css/css-fonts/font-variant-ligatures-11.optional.html)
