### ISSUE TITLE
[css-images-3] caniuse box makes both compat table and spec text unreadable

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#7635]
E.g. https://drafts.csswg.org/css-images-3/#repeating-gradients

<img width="289" alt="Screenshot 2022-08-22 at 10 51 02 PM" src="https://user-images.githubusercontent.com/918903/186080561-fd3fd6a1-c97c-4dcc-a17f-7bf109517223.png">

**Comment by litherum** [comment]
cc @tabatkins @fantasai @LeaVerou

**Comment by tabatkins** [comment]
Oh, hrm, it's using the --bg-bordered-block color for its background, which is implemented as a mostly-transparent white in the darkmode colors (so you can more easily see it against any bg). That clearly isn't intended for things that can overlap, so I'll fix.

**Comment by tabatkins** [comment]
Okay, fixed on main, and I'll assemble a new pip release tomorrow.
