### ISSUE TITLE
[css-align] editorial: Inconsistent "Applies to" section for place-items?

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#764]
https://drafts.csswg.org/css-align/#place-items-property

> place-items:
> Applies to: 	block-level boxes, absolutely-positioned boxes, and grid items 

> align-items
> Applies to: 	block-level elements 

> justify-items
> Applies to: 	block containers and grid containers 

This seems rather inconsistent... is it correct?

Anyway, I would prefer if all the new place- shorthands just say "see individual properties"
in all the Initial/Applies to/Inherited/Percentages/... sections as usual for shorthands.

**Comment by MatsPalmgren** [comment]
Thanks for the fix.  I think you should do the same to `place-content` and `place-self`.
https://drafts.csswg.org/css-align/#propdef-place-content
https://drafts.csswg.org/css-align/#propdef-place-self

Also, "Percentages", "Media" and "Inherited" could also use the "see individual properties"
description.  Some shorthand descriptions do so anyway:
https://drafts.csswg.org/css-flexbox/#propdef-flex

Perhaps you should create some kind of template/macro for shorthands that does this
for you automatically and consistently?

**Comment by fantasai** [comment]
I think actually there's a Bikeshed command that fills in missing fields with "see individual properties"; I should probably use that. My concern about this is that, as we use shorthands more and more frequently, it makes it much more difficult for authors who are referencing the specs to look things up. To the extent that the value of the field is simple, I think it's more usable to leave these fields filled in. The main downside is the potential for out-of-sync errors.
