### ISSUE TITLE
[css2][css-align] Last Baseline Alignment of Scrollable Boxes

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#766]
CSS Align had this sentence, which has been sitting around for awhile:

> For the purposes of finding the first (last) baselines of a box, it and all its in-flow descendants with a scrolling mechanism (see the 'overflow' property) must be considered as if scrolled to their origin (final) position.

CSS2.1 had this sentence:

> The baseline of an 'inline-block' is the baseline of its last line box in the normal flow, unless it has either no in-flow line boxes or if its 'overflow' property has a computed value other than 'visible', in which case the baseline is the bottom margin edge.

Myles raised an issue against CSS2.1 https://lists.w3.org/Archives/Public/www-style/2015Mar/0342.html requesting a change to make `overflow` have a less dramatic effect baseline alignment. which the CSSWG later accepted https://lists.w3.org/Archives/Public/www-style/2015Apr/0144.html

I'm reraising this issue because I think the wording in CSS Box Alignment seems to solve Myles' issue in a somewhat more useful way, and perhaps we should reconsider how last-baseline alignment works in the presence of `overflow`.

**Comment by atanassov** [comment]
We discussed this during Feb 8 CSSWG telcon and decided to continue working on the issue here. Removing the Agenda+ label for now.

**Comment by fantasai** [comment]
The concerns from the call were wrt Web compat vs use cases: no browsers implement the css-align wording above, but the CSS2.1 erratum (which is also not interoperably implemented) does not allow useful handling of last-baseline alignment in situations that have overflow.

**Comment by tabatkins** [comment]
In other words, when the content doesn't overflow, Myles' text and Align's text give the same results; when the content does overflow, they give slightly different results, but Align's makes more sense (actually aligns to text).

**Comment by tabatkins** [comment]
Editted this in 4a2cd1f60

**Comment by fantasai** [comment]
Marking as Needs Edits for CSS2.
