### ISSUE TITLE
Not clamping baseline position when scrollable overflow gives weird results

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#7660]
Currently, [the spec defines](https://www.w3.org/TR/css-flexbox-1/#flex-baselines) that the baselines of scrollable flex/grid items are calculated assuming the item is at its initial scroll position. This allows (and impls currently accept) the baseline to be substantially outside of the box itself, if the first line of text is taller than the box.

See [testcase](https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/10643):
```html
<!DOCTYPE html>
<div style="display: inline-flex; border: solid; overflow: scroll; height: 100px; font-size: 200px">
  This<br>is<br>a<br>text
</div>
text
```
Per our (not currently applied to the spec...) resolution in #2781, scrollable inline-blocks should take their baseline from their content, clamped by the bottom edge of the box, precisely to avoid this unintuitive behavior. (That said, for inline blocks specifically, we may be constrained by compat to ignoring the baselines of scrollable boxes and just using the margin edge; but at least it's still within the edges of the box.)

Regardless of inline blocks, we should apply this clamping behavior in flex and grid layout, and to whichever atomic inlines we can.

This would be a change away from cross-browser consistent behavior, but the current behavior is very bad and very unlikely to be relied upon (it requires the first line to be taller than the item). As last-baseline alignment begins to be implemented, however, it will become much easier to trigger.

**Comment by bfgeek** [comment]
One thing I'd like to discuss is the edge to clamp to - I suspect border-box edge will be a little more consistent (e.g. this is typically what we synthesize off).

**Comment by fantasai** [comment]
+1 to border-box edge

**Comment by dholbert** [comment]
Here's a version where the baseline is above the start edge:
```
<!DOCTYPE html>
<div style="display: inline-flex; border: solid; overflow: scroll; height: 100px; font-size: 200px">
  This<br>is<br>a<br>text
</div>
text
```
![image](https://user-images.githubusercontent.com/426803/190486217-03fb9d18-2fbe-4eb3-a0e6-d70faf3c771c.png)

As discussed, the expectation here would be that the border-top should be aligned with the baseline of "text".

**Comment by fantasai** [comment]
Spec text is already at the end of https://www.w3.org/TR/css-align-3/#baseline-export

> If, in the case of a [scroll container](https://www.w3.org/TR/css-overflow-3/#scroll-container) box, the resulting position of a first/last baseline is past a box’s end/start border edge, its position is clamped to that border edge.

It's a little hard to read, so we rewrote it to 

> If the position of a scroll container’s first/last baseline is outside its border edge, that baseline’s position is clamped to the border edge.
