### ISSUE TITLE
[css-grid-1] Application of grid-positioning properties to static position of grid children is inconsistent

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7661]
While drafting https://github.com/w3c/csswg-drafts/issues/7612#issuecomment-1230963091 I noticed that we are introducing a weird inconsistency in the Grid specification:

> The [static position](https://www.w3.org/TR/CSS2/visudet.html#abs-non-replaced-width) [[CSS2]](https://www.w3.org/TR/css-grid-2/#biblio-css2) of an absolutely-positioned child of a [grid container](https://www.w3.org/TR/css-grid-2/#grid-container) is determined as if it were the sole grid item in a [grid area](https://www.w3.org/TR/css-grid-2/#grid-area) whose edges coincide with the content edges of the grid container. However, if the grid container parent is also the generator of the absolutely positioned element’s [containing block](https://www.w3.org/TR/css-display-3/#containing-block), instead use the grid area determined in [§ 10.1 With a Grid Container as Containing Block](https://www.w3.org/TR/css-grid-2/#abspos-items).

In general, an `inset:auto` abspos has a static position which does not change no matter where in its ancestor chain `position: relative` is introduced. But here we are making the application of grid positioning properties to determining the static position conditional on whether it is also the abspos containing block. See [testcase](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A.grid%20%7B%20display%3A%20grid%3B%20grid%3A%20100px%20100px%20%2F%20100px%20100px%3B%20border%3A%20solid%3B%20width%3A%20min-content%3B%20float%3A%20left%20%7D%0A.item%20%7B%20border%3A%20solid%20orange%3B%20position%3A%20absolute%3B%20grid-row%3A%202%3B%20grid-column%3A%202%20%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3Dgrid%20style%3D%22%22%3E%0A%20%20%3Cdiv%20class%3Ditem%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3Dgrid%20style%3D%22position%3A%20relative%22%3E%0A%20%20%3Cdiv%20class%3Ditem%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E)

I don't know if it's Web-compatible, but I think we should not be making it conditional. It should be unconditional: either applying always to grid children’s staticpos calculations, or never applying to them. (I prefer always; it gives the author more power.)

**Comment by Loirooriol** [comment]
I'm not sure it makes sense to obey grid placement properties for the static position, if then they will be ignored for the inset-modified containing block. But no strong opinion.

**Comment by bfgeek** [comment]
One thing to keep in mind is that this will mean that a OOF-grid item can be "placed" in two different grids.

**Comment by tabatkins** [comment]
I feel *very* strongly that the properties should **not** apply to the staticpos if the parent grid container is not the abspos containing block. As Ian says, this means the positioned element would be using a single set of grid-positioning properties in two *entirely different* grids, which is incoherent.

I wouldn't object to *never* using the grid positioning properties for staticpos, but I'm also fine with the current state of affairs. I'm not sure why the conditionality is problematic.

**Comment by tabatkins** [comment]
As I stated in the meeting (and was sidelined for), I will object to an outcome where static position and normal position *both* pay attention to the grid positioning properties, possibly from different grids.

So, given the resolution we *did* get, the only edits that will avoid objection are to say that the grid positioning properties don't affect static position at all.

**Comment by astearns** [comment]
As mentioned in the minutes, the intent is to work through examples and use cases in this issue now. I think edits to the spec should wait on this.

**Comment by bfgeek** [comment]
So grid is in a super strange place at the moment. I was initially agnostic about which was this should go - but now I suspect we want to go with @tabatkins position.

Lets say you have:
```html
<!DOCTYPE html>
<style>
.grid {
  display: inline-grid;
  border: solid 5px;
  padding: 10px;
}
.oof {
  position: absolute;
  width: 15px;
  height: 15px;
  background: lime;
}
</style>

<div class="grid" style="position: static;">
  <div class="oof"></div>
</div>

<div class="grid" style="position: relative;">
  <div class="oof"></div>
</div>

<div class="grid" style="position: relative;">
  <div class="oof" style="grid-row: 1; grid-column: 1;"></div>
</div>
```

With grid (1) we'll use the resolution in https://github.com/w3c/csswg-drafts/issues/3020#issuecomment-415086888 and use the content-box, as the containing-block isn't the grid.

https://drafts.csswg.org/css-grid-1/#static-position
> "The [static position](https://www.w3.org/TR/CSS2/visudet.html#abs-non-replaced-width) [[CSS2]](https://drafts.csswg.org/css-grid-1/#biblio-css2) of an absolutely-positioned child of a [grid container](https://drafts.csswg.org/css-grid-1/#grid-container) is determined as if it were the sole grid item in a [grid area](https://drafts.csswg.org/css-grid-1/#grid-area) whose edges coincide with the content edges of the grid container."

With grid (2) as the grid *is* the containing-block we'll use the padding-box for the static-position (this strikes me as incorrect). As we invoke:
> However, if the grid container parent is also the generator of the absolutely positioned element’s [containing block](https://drafts.csswg.org/css-display-4/#containing-block), instead use the grid area determined in [§ 9.1 With a Grid Container as Containing Block](https://drafts.csswg.org/css-grid-1/#abspos-items).

And grid (3) we invoke the above logic, but use are actually placed in a useful area.

For grid (2) re-using the contianing-block logic is super strange?

**Comment by bfgeek** [comment]
To clarify the three options:

Option (1) - Keep the spec as is. Note this will require undoing the previous resolution as the current algorithm depends on what the abspos containing block is.

*If* the abspos container, is *also* the containing block, pick up the static-position by invoking grid-placement.

Option (2) - Use the content-box always.

We wouldn't invoke the grid-placement algorithm to pick up the static-position. This option aligns with flex - nothing magical happens.

Option (3) - Always invoke grid-placement to acquire the static-position. This would require undoing the resolution in #3020 (as invoking grid-placement for abspos uses the padding-box by default).

**Comment by bfgeek** [comment]
My personal preference is Option (2) at the moment.

**Comment by tabatkins** [comment]
Also my preference. I have a *strong* preference against potentially invoking the grid-placement algo on two distinct grid containers. It wouldn't create the *incoherent* situation of using the same grid-placement property on two different grids that I objected to before, but it would still be confusing if grid-row was resolved against one grid and grid-column against another, if one inset axis was specified and the other was auto.

**Comment by dholbert** [comment]
> Option (2) - Use the content-box always. We wouldn't invoke the grid-placement algorithm to pick up the static-position

This seems probably like the best outcome to me, too.

Just to clarify, though are you saying that all three grids in [your testcase](https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1541037807) should look the same, and should do so regardless of the `grid-row` / `grid-column` properties on the third item?

That seems probably reasonable to me.  The (maybe acceptable) drawbacks that I see are:
(A) If you add `position:absolute` to take a grid item out of flow, then it would now undergo a huge change in its (static) position (moving from its grid cell to a large virtual cell the size of the content area).  Part of the goal of the current setup is that it stays in its same grid cell, aligns the same, etc. regardless of whether its abspos or not.  Maybe this change would be ~fine since the same thing happens for flexbox? (Though in flexbox there's more positioning influence between siblings, so it's more of an obvious thing there.)

(B) For a start-aligned abspos grid item with the grid as its abspos containing block: `top:0` would shift the element further upwards (to the padding box edge).  Though maybe this is ~fine since the same thing happens for flexbox.

(C) (There's also obviously some compat risk with changing behavior here, since the current behavior is interoperable.  Maybe this is edge-casey enough that the impact will be minimal though.)

**Comment by bfgeek** [comment]
> Just to clarify, though are you saying that all three grids in https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1541037807 should look the same, and should do so regardless of the grid-row / grid-column properties on the third item?

Thanks correct.

I suspect this will be web-compatible as folks generally don't rely on static-position that often, and likely less so with grid. We are happy to make the change to test it out.

**Comment by dholbert** [comment]
Thanks! I'm on board with option (2), then.

**Comment by fantasai** [comment]
Fwiw, I disagree with Tab on this one. I don't think it's a problem for each axis to be positioned relative to a different grid. I agree with @dholbert's [concern](https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1561546264) that disabling the grid positioning properties for static positioning results in more of a change in position than may be expected or desired, and it's inconsistent with what the static position is supposed to represent.

My position is that:

- if the grid position in an axis is auto (initial value), then
  - for static positioning, we use the content box (like for flexbox)
  - for abspos positioning, we use the padding box (like for everything)
- if the grid position in an axis is not auto, then
  - for static positioning, we reference the parent grid (if any)
  - for abspos positioning, we reference the containing block grid (if any)

I don't think this is confusing, and it is strictly more powerful than ignoring the grid positioning properties in staticpos, which I'm sure authors will find interesting uses for.

**Comment by bfgeek** [comment]
> for static positioning, we use the content box (like for flexbox)

This isn't how static position works for abspos children in a grid. It'll invoke https://drafts.csswg.org/css-grid-1/#abspos-items which for "auto" grid-positions will use the padding-box (not content-box).
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=11710

Ian

**Comment by tabatkins** [comment]
Also, I think that *in general* everything people want to achieve with static positioning is achieved better, easier, and more reliably with anchor positioning. We obviously need to keep a lot of static position behavior around for compat reasons, but where we're not constrained by compat we should be doing the easiest possible thing, rather than trying to put a lot of effort into figuring out some restricted sort of "most likely to be useful" behavior (with no guarantees it's actually useful).

**Comment by fantasai** [comment]
@bfgeek I think that's a mistake and Grid should have been consistent with Flexbox (and every other layout system) in this regard.

**Comment by chrishtr** [comment]
I synced with @bfgeek just now.

My understanding is that, as compared with option 3, [option 2](https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1551707447) is:

* Substantially simpler to implement
* Solves all use cases we know of
* Avoids problems where elements can potentially invoke grid placement in more than one grid

(And no one is advocating for option 1)

Therefore I think we should go with option 2.

**Comment by fantasai** [comment]
**Summary**

Current behavior (per spec) is that the static position of a grid child depends on whether its parent is the abspos containing block or not. See [simplified testcase](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A.grid%20%7B%20display%3A%20grid%3B%20grid%3A%20100px%20100px%20%2F%20100px%20100px%3B%20border%3A%20solid%3B%20width%3A%20min-content%3B%20float%3A%20left%20%7D%0A.item%20%7B%20border%3A%20solid%20orange%3B%20position%3A%20absolute%3B%20grid-row%3A%202%3B%20grid-column%3A%202%20%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3Dgrid%20style%3D%22%22%3E%0A%20%20%3Cdiv%20class%3Ditem%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3Cdiv%20class%3Dgrid%20style%3D%22position%3A%20relative%22%3E%0A%20%20%3Cdiv%20class%3Ditem%3E%3C%2Fdiv%3E%0A%3C%2Fdiv%3E) from above. No other layout model changes the static position based on the qualities of the abspos containing block, so we have agreement that this shouldn't be conditional.

The two behaviors it switches between are
- using the content box of the grid as the static position rectangle
- using the grid-positioning properties (`grid-area`/`grid-row`/`grid-column`) to determine the static position rectangle

(Specifically, it uses the second behavior iff the parent is also the abspos containing block. See [testcase](https://www.software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%20%20.grid%20%7B%20display%3A%20grid%3B%20grid%3A%201fr%201fr%201fr%20%2F%201fr%202fr%201fr%3B%20width%3A%20100px%3B%20height%3A%20100px%3B%20padding%3A%2010px%3B%20border%3A%20solid%3B%20float%3A%20left%3B%20margin%3A%202px%20%7D%0A%20%20.in-flow%20%7B%20grid-area%3A%202%20%2F%202%3B%20border%3A%20solid%20teal%20%7D%0A%20%20.abspos%20%7B%20position%3A%20absolute%3B%20background%3A%20orange%3B%20grid-area%3A%202%2F2%3B%20%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%20class%3D%22grid%22%3E%3Cdiv%20class%3D%22in-flow%22%3E%3C%2Fdiv%3E%3Cdiv%20class%3D%22abspos%22%3Eabspos%3C%2Fdiv%3E%3C%2Fdiv%3E%0A%3Cdiv%20class%3D%22grid%22%20style%3D%22position%3A%20relative%22%3E%3Cdiv%20class%3D%22in-flow%22%3E%3C%2Fdiv%3E%3Cdiv%20class%3D%22abspos%22%3Eabspos%3C%2Fdiv%3E%3C%2Fdiv%3E%0A).)

**Options**

To make the static position consistent regardless of the abspos containing block, we need to choose one behavior to apply always. The two options advocated for in this issue are:

* use the content box always, ignoring the grid-positioning properties (“Option 2”); see [chrishtr‘s summary comment](https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1581536966)
* honor the grid-positioning properties always, using the content-box edge when they are `auto` (“Option 3′”); see [fantasai’s summary comment](https://github.com/w3c/csswg-drafts/issues/7661#issuecomment-1568842537)

Note the behaviors here are per-axis, and only apply if the `inset` values are both `auto` in that axis (i.e. for calculating the static position). If at least one `inset` is non-auto, then the box is not statically positioned, and the grid-positioning properties are honored with reference to the abspos containing block (and therefore ignored if the abspos containing block is not itself a grid).

**Comment by fantasai** [comment]
Chromium found the newly specced behavior to be Web-incompatible, see https://issues.chromium.org/issues/40272496. Reopening.
