### ISSUE TITLE
Pluralize `feature-*` to `features-*`?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7663]
Originally [raised by @jfkthame ](https://github.com/w3c/csswg-drafts/issues/7633#issue-1346860734):

> (3) A really minor issue, but I have found myself repeatedly writing things like `@supports font-tech(features-opentype)`, and not getting the expected result because the correct keyword is `feature-opentype` (singular). To my mind, the `feature-*` keywords would read more naturally in the plural form (similarly to `font-tech(variations))`. Should we change them to plural, here and in CSS Fonts, before this is widely implemented and webcompat becomes a constraint?

**Comment by drott** [comment]
Yes, I support this. I would even hope we can consider this a minor editing change and proceed with it. @litherum @jfkthame ?

**Comment by svgeesus** [comment]
This change would also affect [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#font-face-src-parsing) and 5 because obviously we would want consistency between Conditional and Fonts specs..

**Comment by svgeesus** [comment]
it is [already plural in Conditional 5](https://github.com/w3c/csswg-drafts/blame/main/css-conditional-5/Overview.bs#L77-L79)

**Comment by drott** [comment]
Thanks, Chris.
