### ISSUE TITLE
[css-contain] Container queries wrongly assume that all elements can be contained

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7667]
See https://drafts.csswg.org/css-contain-3/#container-type

> - `size`
>    Establishes a [query container](https://drafts.csswg.org/css-contain-3/#query-container) for [container size queries](https://drafts.csswg.org/css-contain-3/#container-size-query) on both the [inline](https://drafts.csswg.org/css-writing-modes-4/#inline-axis) and [block axis](https://drafts.csswg.org/css-writing-modes-4/#block-axis). Applies [layout containment](https://drafts.csswg.org/css-contain-2/#layout-containment), [style containment](https://drafts.csswg.org/css-contain-2/#style-containment), and [size containment](https://drafts.csswg.org/css-contain-2/#size-containment) to the [principal box](https://drafts.csswg.org/css-display-3/#principal-box).
> - `inline-size`
>    Establishes a [query container](https://drafts.csswg.org/css-contain-3/#query-container) for [container size queries](https://drafts.csswg.org/css-contain-3/#container-size-query) on the container’s own [inline axis](https://drafts.csswg.org/css-writing-modes-4/#inline-axis). Applies [layout containment](https://drafts.csswg.org/css-contain-2/#layout-containment), [style containment](https://drafts.csswg.org/css-contain-2/#style-containment), and [inline-size containment](https://drafts.csswg.org/css-contain-3/#inline-size-containment) to the [principal box](https://drafts.csswg.org/css-display-3/#principal-box).

While all elements accept style containment, layout containment requires all these conditions:
 - the element generates a [principal box](https://drafts.csswg.org/css-display-3/#principal-box)
 - its [principal box](https://drafts.csswg.org/css-display-3/#principal-box) is not an [internal table box](https://drafts.csswg.org/css-display-3/#internal-table-box) or is a [table-cell](https://drafts.csswg.org/css-display-3/#valdef-display-table-cell)
 - its [principal box](https://drafts.csswg.org/css-display-3/#principal-box) is not an [internal ruby box](https://drafts.csswg.org/css-display-3/#internal-ruby-box) nor a [non-atomic](https://drafts.csswg.org/css-display-3/#atomic-inline) [inline-level](https://drafts.csswg.org/css-display-3/#inline-level) box

Size containment and inline-size containment, in addition to the requirements above, also need:
 - its [inner display type](https://drafts.csswg.org/css-display-3/#inner-display-type) is not [table](https://drafts.csswg.org/css-display-3/#valdef-display-table)
 - its [principal box](https://drafts.csswg.org/css-display-3/#principal-box) is not a [table-cell](https://drafts.csswg.org/css-display-3/#valdef-display-table-cell)

It makes no sense to establish a [query container](https://drafts.csswg.org/css-contain-3/#query-container) for [container size queries](https://drafts.csswg.org/css-contain-3/#container-size-query) if size containment has no effect on the element. Obvious circularity issues.

**Comment by andruud** [comment]
The intent was that an element with `container-type:size/inline-size` is always a query container, regardless of whether or not containment can apply on the element. However, any queries against a query container that "[does not support](https://drafts.csswg.org/css-contain-3/#size-container:~:text=the%20query%20container%20does%20not%20support)" queries along the relevant axis results in "unknown". I prefer keeping it this way, since it makes it possible to answer the question "is this a query container" immediately after the style recalc of an element. If we involve layout box information, we can't answer that question until after layout-tree-building, which is annoying.

But "does not support" is a little vague, and we could minimally also link to https://drafts.csswg.org/css-contain-2/#size-containment-box explicitly.

**Comment by Loirooriol** [comment]
Ah, thanks, I missed

> If [...] the query container does not support [container size queries](https://drafts.csswg.org/css-contain-3/#container-size-query) on the relevant axes, then the result of evaluating the [size feature](https://drafts.csswg.org/css-contain-3/#size-features) is unknown.

That works too. But yeah, the conditions for supporting container size queries are not clear, filed #7702
