### ISSUE TITLE
[css-backgrounds-3] Disallow double `//` in `border-image`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7672]
`0 // 1` is valid according to the [`border-image` grammar](https://drafts.csswg.org/css-backgrounds-3/#propdef-border-image), but I am not sure the original intent was to allow `//`. The grammar has been [modified (10 years ago)](https://github.com/w3c/csswg-drafts/commit/798cf615622b6bf122cc6b365f2f96851f0daff5) to prevent a trailing `/`. I think the following value definition would prevent `//`:

```diff
     <'border-image-source'>
- || <'border-image-slice'> [ / <'border-image-width'> | / <'border-image-width'>? / <'border-image-outset'> ]?
+ || <'border-image-slice'> [ / <'border-image-width'> | [ / <'border-image-width'> ]? / <'border-image-outset'> ]?
  || <'border-image-repeat'>
```

~~There is no WPTs for a similar input.~~ There is an existing WPT and I cannot say if this change would represent a back-compat issue.

Similarly, I am noting that you cannot set `<bg-size>` without defining `<bg-position>`: `<bg-position> [ / <bg-size> ]?`. Alternatively, it could be simplified in a consistent way with:

```diff
     <'border-image-source'>
- || <'border-image-slice'> [ / <'border-image-width'> | / <'border-image-width'>? / <'border-image-outset'> ]?
+ || <'border-image-slice'> [ / <'border-image-width'> [ / <'border-image-outset'> ]? ]?
  || <'border-image-repeat'>
```

**Comment by faceless2** [comment]
It's used in https://github.com/web-platform-tests/wpt/blob/master/css/css-backgrounds/border-image-shorthand-003.htm, which is passing in all browsers: https://wpt.live/css/css-backgrounds/border-image-shorthand-003.htm

**Comment by cdoublev** [comment]
Oh, sorry, I searched for ` // `, but not ` / / `.

**Comment by Loirooriol** [comment]
Also tested in https://wpt.fyi/results/css/css-backgrounds/parsing/border-image-valid.html

**Comment by cdoublev** [comment]
Ok, with some hindsight, considering the fact it is tested, that I probably ignore valid reasons to support this syntax, I prefer to not hold this request any longer. Feel free to re-open it if you think it is worth it. Thanks to both of you for your answers!

**Comment by Loirooriol** [comment]
The 1st time that I saw <code>/ /</code> it also seem surprising to me, but disallowing it could break sites. May be better to forbid in linters?

**Comment by tabatkins** [comment]
Allowing a `//` was indeed intentional, fwiw. I'd have to go dig around in mail archives to find the conversation, as I think this was designed pre-GitHub, but if my memory is correct we explicitly discussed this.
