### ISSUE TITLE
[css-color] Clamping component values at computed-value time vs parsing time

### ISSUE THREAD

**Issue by mysteryDate** [w3c/csswg-drafts#7677]
From https://www.w3.org/TR/css-color-4/#rgb-functions:

> The final argument, the `<alpha-value>`, specifies the alpha of the color. If given as a `<number>`, the useful range of the value is 0 (representing a fully transparent color) to 1 (representing a fully opaque color). If given as a `<percentage>`, 0% represents a fully transparent color, while 100% represents a fully opaque color. If omitted, it defaults to 100%.
> Values outside these ranges are not invalid, but are clamped to the ranges defined here at computed-value time.

All user agents I've tested in fact do the clamping at parsing time:
```
  <!doctype html>
  <style>
    #target {
          color: rgba(400, 400, 300, -300);
    }
  </style>
  <div id="target"></div>
  <pre id="res"></pre>
  <script>
    res.innerText = "specified: " + document.styleSheets[0].cssRules[0].style.color + "\ncomputed: " + getComputedStyle(target).color;
  </script>
  ```
Firefox, Safari and Chrome all give "specified: rgba(255, 255, 255, 0)"

Is there a disadvantage to just doing the clamping at parsing time? It is easier to implement and is already the behavior that we're living with.

**Comment by cdoublev** [comment]
Clamping at parse time may be an exception for sRGB color functions. [CSSOM](https://drafts.csswg.org/cssom-1/#ref-for-alphavalue-def) defines how to serialize `<alphavalue>` (aside: note the missing `-` between "alpha" and "value") as an 8-bit integer (between 0 and 255). This might be the (historical) reason why browsers do clamping at parse time, as noted in [15.2 Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values):

> For compatibility, the sRGB component values are serialized in `<number>` form, not `<percentage>`). Also for compatibility, the component values are serialized in base 10, with a range of [0-255], regardless of the bit depth with which they are stored.

Aside: there is an extra `)` in the first sentence.

But this same section also has...

> The serialized form of the following sRGB values [...] is derived from the computed value and thus, uses either the `rgb()` or `rgba()` form (depending on whether the alpha is exactly 1, or not)

... and I am very confused that I have to use a computed value to serialize a specified value. And [15. Serializing `<color>` Values](https://drafts.csswg.org/css-color-4/#serializing-color-values) starts with:

> This section updates and replaces that part of CSS Object Model, section Serializing CSS Values, which relates to serializing `<color>` values.

Apart from this, there are also math functions, whose value is [clamped at computed value time](https://drafts.csswg.org/css-values-4/#calc-range), eg. `rgb(0, 0, 0, calc(-1))`, and `opacity` is also defined with `<alpha-value>` and its specified value is not clamped.

**Comment by lilles** [comment]
Looking at the serialization part of the spec, it looks like it's focused on computed values and that serializing specified values is overlooked?

https://drafts.csswg.org/css-color-4/#serializing-sRGB-values

**Comment by svgeesus** [comment]
> Looking at the serialization part of the spec, it looks like it's focused on computed values and that serializing specified values is overlooked?

It is, indeed.

**Comment by svgeesus** [comment]
> [CSSOM](https://drafts.csswg.org/cssom-1/#ref-for-alphavalue-def) defines how to serialize <alphavalue> (aside: note the missing - between "alpha" and "value") as an 8-bit integer (between 0 and 255). This might be the (historical) reason why browsers do clamping at parse time, as noted in [15.2 Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values):

All the color serialization stuff got moved from CSSOM to Color 4. It makes sense to move the alpha serialization as well.

The legacy forms and the newer `color()`, `oklab()` etc have different compatibility constraints of course.

**Comment by lilles** [comment]
This is also an issue for lightness. Per the current spec, lab()/lch(), for instance, should clamp negative lightness to 0 at computed value time, not specified/parse time: https://drafts.csswg.org/css-color/#specifying-lab-lch

There are several tests in e.g. https://wpt.fyi/results/css/css-color/parsing/color-valid-lab.html that expects clamping at parse time and conflicts with the current spec.

Also, both WebKit and Blink currently clamp at parse time.

**Comment by Juanmihd** [comment]
Is there any update regarding this?

Should we change the spec to match the tests and assume clamping at parse time? Or are the tests wrong?

**Comment by lilles** [comment]
Summary:

- Clamping at parse time instead of computed time should just affect specified style serialization
- wpt tests expect parse time clamping and do not match current spec
- Safari ships with clamping at parse time
- Chrome wants to ship and currently implements clamping at parse time
- Implementing clamping at computed value time means range checking and clamping has to happen every time we apply a color during style resolution, which is an implementation/performance burden

I propose to resolve on changing the spec to clamp at parse time for the components that currently are specfied to clamp at computed value time.

**Comment by mysteryDate** [comment]
@svgeesus Isn't simply changing the text:
```
Values outside these ranges are not invalid, but are clamped to the ranges defined here at computed-value time.
```
to:
```
Values outside these ranges are not invalid, but are clamped to the ranges defined here at parsed-value time.
```
sufficient?

**Comment by svgeesus** [comment]
It looks like implementations are clamping under-range Lab l and alpha at parse time:
  [`lab(-150% -30 40 / -30)` specified value is `lab(0 -30 40 / 0)`](https://codepen.io/svgeesus/pen/BaPRvOJ)

but over-range Lab l is left unclamped (the spec used to require this, but it was changed a while ago):
[`lab(600% -30 40 / 300);` specified value is `lab(600 -30 40)`](https://codepen.io/svgeesus/pen/MWBmLeg)

**Comment by svgeesus** [comment]
For HWB, both the initial clamp of w and b to [0%, 100%] but also the further normalization on the sum of w and b should be at parse time, right?

> 	If the sum of these two arguments is greater than 100%, then at computed-value time they are further normalized to add up to 100%, with the same relative ratio.

This isn't directly observable, but the specified value (which is in `rgb()`) shows that this normalization must have taken place.

**Comment by svgeesus** [comment]
@mysteryDate @lilles please have a look at [this commit](https://github.com/w3c/csswg-drafts/commit/52c454f05c8061923bd5bdb6bf5814a16ad7a0ed)

I was slightly concerned that "parse-time" doesn't have a convenient spec link, but then again uses of "computed-value time" in this spec weren't linking anywhere either.

Where are these terms defined?

**Comment by fantasai** [comment]
You probably want to just use the terms “computed value” and “specified value”, e.g. “the specified value is clamped to [range]” or whatever. https://www.w3.org/TR/css-cascade-5/#specified

**Comment by mysteryDate** [comment]
@svgeesus Looks good to me!

**Comment by lilles** [comment]
Adding @emilio for Gecko concerns.

@fantasai Isn't specified to late as well? There is something called [declared value](https://www.w3.org/TR/css-cascade-5/#declared). I don't even know if that is the correct term if we want it serialized clamped in the stylesheet serialization.

Is the serialization for <color> in the CSSOM spec relevant?:

https://drafts.csswg.org/cssom/#serialize-a-css-component-value

Regarding `<alpha-value>`, we have existing interop on the opacity property _not_ being clamped for declared values. But also, we have interop on clamping `<alpha-value>` on the specified rbga() values.

See https://codepen.io/lilles/pen/YzjQEzj

**Comment by svgeesus** [comment]
It is relevant, but 2/3 of it points to CSS Color 4 and I have been discussing with @emilio about moving over the remaining portion as well:

> If [<color>](https://drafts.csswg.org/css-color-4/#typedef-color) is a component of a specified value, then return the color as follows:

>    If the color was explicitly specified by the author, then return the original, author specified color value.
    Otherwise, return the value that would be returned if the color were a component of a computed value.

Particularly because that needs to be changed for named colors.

**Comment by svgeesus** [comment]
> There is something called [declared value](https://www.w3.org/TR/css-cascade-5/#declared). I don't even know if that is the correct term if we want it serialized clamped in the stylesheet serialization.

The differences between the declared value, the cascaded value, and the specified value seem to boil down to:

 - resolving aliases such as vendor-prefixed properties
 - defaulting properties with no declared value (inheritance, initial values)

So in the case that there _is_ a declared value on a given element, it seems that will be the specified value. Right?

**Comment by svgeesus** [comment]
> Particularly because that needs to be changed for named colors.

Now [done](https://github.com/w3c/csswg-drafts/commit/64708dfff2e52bf7a223ff192f8f9f28f72d7207)

**Comment by svgeesus** [comment]
Not clear to me whether further clarifications are needed or if this can be closed. Can we get consensus on this before Weds 8 Feb?

**Comment by mysteryDate** [comment]
At chromium we're happy with the language as it.

**Comment by cdoublev** [comment]
> - Clamping at parse time instead of computed time should just affect specified style serialization

It seems to affect color functions taking other colors as arguments, as reported in #10328.

For example, `color(from rgb(306 0 0) srgb r 0 0)` would serialize (as a component of a declared value with) `color(from rgb(255 0 0) r 0 0)` and the computed value would be `color(srgb 1 0 0)` instead of `color(srgb 1.2 0 0)`, if I am not mistaken.

It may be safer to clamp the serialized value rather than affect the parsed value. Maybe it would still be needed for a negative saturation in `hsl()` and a negative whiteness/blackness in `hwb()` (which is now specified in a hidden comment), I am not sure.
