### ISSUE TITLE
[css-align] align-items "Applies to" description is too restrictive

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#768]
It was recently changed from "block-level elements" to "flex containers and grid containers":
https://github.com/w3c/csswg-drafts/commit/ef903beda2146b90f42d3dbfc086b61b9f1009c1

I think this is too restrictive because `align-self` applies to "Absolutely-Positioned Boxes" and "Static Position of Absolutely-Positioned Boxes" too, not just flex/grid items:
https://drafts.csswg.org/css-align/#align-abspos

(It seems to me that `align/justify-items` could actually apply to everything, because they are merely place-holder values for substituting `align/justify-self:auto` in contexts where _those_ properties apply.)

**Comment by fantasai** [comment]
Switched over to all elements as suggested. Thanks for catching this. :)
