### ISSUE TITLE
[css-font-loading] FontFaceSet.load() promise rejections

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#7680]
The spec [says](https://drafts.csswg.org/css-font-loading-3/#dom-fontfaceset-load):

> 3. [Find the matching font faces](https://drafts.csswg.org/css-font-loading-3/#find-the-matching-font-faces) from font face set using the [font](https://www.w3.org/TR/css-font-loading-3/#dom-fontfacesetload-font) and [text](https://www.w3.org/TR/css-font-loading-3/#dom-fontfacesetload-text) arguments passed to the function, and let font face list be the return value (ignoring the found faces flag). If a syntax error was returned, reject promise with a SyntaxError exception and terminate these steps.
> 4. Queue a task to run the following steps synchronously:
>     1. For all of the font faces in the font face list, call their [load()](https://drafts.csswg.org/css-font-loading-3/#dom-fontface-load) method.
>     2. Resolve promise with the result of waiting for all of the [[[FontStatusPromise]]](https://drafts.csswg.org/css-font-loading-3/#dom-fontface-fontstatuspromise-slot)s of each font face in the font face list, in order.

However, this is not, in fact, what (any) browser does. This text indicates that either A) the string passed to `load()` is a syntax error, or B) the promise is resolved (rather than rejected). However, WebKit, Chrome, and Firefox all reject the promise if no fonts were able to be loaded. (WebKit rejects the promise if _any_ font was unable to be loaded, and I'm not sure about the other browsers.)

I suggest we make the spec match what is de-facto true in browsers.

[test.html.zip](https://github.com/w3c/csswg-drafts/files/9480980/test.html.zip)

**Comment by astearns** [comment]
No worries about tagging recent issues or ones that have not gotten replies. If an issue is important to you it is very useful input for the entire group.

**Comment by svgeesus** [comment]
On a related note, (and ideally after we have resolved this issue):

 - https://github.com/w3c/csswg-drafts/issues/7065

**Comment by tabatkins** [comment]
The "fulfill the promise if there are no fonts" is just how Promise.all() normally works when fed an empty list (and in particular is how WebIDL works by default, if you refer to its algorithms; this spec was written before those were established, but I should fix to refer to them). 

Is there a good reason we should diverge from that, or is this just an artifact of browsers doing stuff in idiosyncratic ways before we got good spec algos to encourage consistency?

Note that this is also consistent with the current spec for .check(), which returns true if no fonts need to be loaded at all.

**Comment by litherum** [comment]
> fulfill the promise if there are no fonts

That's not the situation here. The situation is:

1. There are fonts
2. The fonts fail to load

**Comment by tabatkins** [comment]
Oh, I'm confused then. If there *are* fonts, then you return a promise with the result of "waiting for all" the load() promises. The load() promise rejects if the load fails, see <https://drafts.csswg.org/css-font-loading-3/#font-face-load>. So it sounds like WebKit is correct in this regard, rejecting if any of them reject.

**Comment by jakearchibald** [comment]
I'm not 100% sure, but maybe folks are assuming that resolve is the opposite of reject? [It isn't](https://jakearchibald.com/2014/resolve-not-opposite-of-reject/).

```js
const a = Promise.reject(new Error('boom'));
const b = Promise.resolve(a);
```

`b` is a rejected promise.

The opposite of 'rejected' is 'fulfilled'.

If this is the issue, it might have been clearer if the promise operations were linked to their definitions in WebIDL. Eg https://webidl.spec.whatwg.org/#waiting-for-all-promise.

**Comment by tabatkins** [comment]
Yeah, note this fun passage in the intro:

> 	This specification uses {{Promise}}s,
>	which are defined in `<a href="http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts">ECMAScript 6</a>`.
>	HTML5Rocks has some `<a href="http://www.html5rocks.com/en/tutorials/es6/promises/">good tutorial material introducing Promises</a>`.

This was literally one of the first W3C specs to use promises *at all*. ^_^
