### ISSUE TITLE
[css-grid] Mark up minmax() and fit-content() as functions in the spec?

### ISSUE THREAD

**Issue by wbamberg** [w3c/csswg-drafts#7682]
I've been working on displaying the syntax of CSS features on MDN, via the [webref](https://www.npmjs.com/package/@webref/css) package. We do this using a macro that uses fetches the syntax from webref, then tries to render it nicely, like: https://developer.mozilla.org/en-US/docs/Web/CSS/border#formal_syntax.

There are a few places where this isn't working: two that I have found are [`minmax()`](https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-minmax) and [`fit-content()`](https://drafts.csswg.org/css-grid/#valdef-grid-template-columns-fit-content). These look like functions, and the MDN pages are tagged as functions, but in the specs they are not marked up as functions, so they don't appear in webref, and we're not able to show any syntax for them on MDN.

There's more on this here: https://github.com/mdn/content/issues/18780#issuecomment-1216912692 :

> > Finally <minmax()> doesn't seem to have an entry at all although [it is listed as a component of some other types](https://github.com/w3c/webref/blob/a5ca70b00c96c92a519f118141c977711ff8f687/ed/css/css-grid.json#L252-L254). Again, the same applies to some other functions, like <fit-content()>, where we don't see an error because our [fit-content() page](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content) does not attempt to include formal syntax.
> 
> Both `minmax()` and `fit-content()` look like CSS functions but they are not defined as CSS functions (the spec defines them with a `data-dfn-type="value"` and not a `data-dfn-type="function"`). They are rather defined as "simple" values as `auto` or `inherit`. If they were real CSS functions, the definition of `<track-size>` would not be:
> 
> ```
> <track-breadth> | minmax( <inflexible-breadth> , <track-breadth> ) | fit-content( <length-percentage> )
> ```
> 
> ... but rather
> 
> ```
> <track-breadth> | <minmax()> | <fit-content()>
> ```
> 
> Why is that? I don't know :) You may want to ask the CSS working group why they sometimes decide to create functions and sometimes decide to leave them as pure textual syntax. It may not be intentional.

So I wondered whether there's a reason that these features are not marked up as functions in the specs.

**Comment by cdoublev** [comment]
You might be interested by #7380 and https://github.com/w3c/csswg-drafts/issues/2921#issuecomment-1168799492.

`fit-content()` can have different arguments therefore it cannot be defined as a production type, whose value definition must be unique. `w3c/webref` could extract all `value`s but there would be a lot (ie. all keywords). Maybe they could only extract `value`s that are functions.

**Comment by tabatkins** [comment]
Right, the functions should still be *marked* as functions rather than values, but their context-sensitivity (indicated by the presence of the `for` value) means they can't be meaningfully used as productions.

**Comment by cdoublev** [comment]
To be clear, taking the current markup.

| Name            | Markup                                                                           |
| --------------- | -------------------------------------------------------------------------------- |
| `fit-content()` | `data-dfn-type="value" data-dfn-for="grid-template-columns, grid-template-rows"` |
| `minmax()`      | `data-dfn-type="value" data-dfn-for="grid-template-columns, grid-template-rows"` |
| `repeat()`      | `data-dfn-type="function"` |

The first two functions have context-sensitive definitions, are marked with `data-dfn-type="value"`, and cannot be annotated with `<fit-content()>` or `<minmax()>`.

The third has a unique definition, is marked with `data-dfn-type="function"`, and can be annotated with `<repeat()>`.

**Comment by tabatkins** [comment]
Okay, I went ahead and marked up minmax() and fit-content() as functions (and also fixed fit-content() in Sizing, where it had the same issue).

As I said, the context-sensitivity is indicated by the functions have a `for` value, versus generally usable functions that don't have a `for` value.

**Comment by cdoublev** [comment]
There is also a few types defined as `value`, eg. [`<family-name>`](https://drafts.csswg.org/css-speech-1/#valdef-voice-family-family-name) in CSS Speech.
