### ISSUE TITLE
[css-animations-1] CSSKeyframesRule should have index getter

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#7684]
Blink and WebKit has index getter on CSSKeyframesRule. For best interoperability, I recommend adding it to the spec.

See WebKit's IDL for example:
```webidl
[
    Exposed=Window
] interface CSSKeyframesRule : CSSRule {
    attribute [AtomString] DOMString name;
    readonly attribute CSSRuleList cssRules;
    
    undefined insertRule(DOMString rule);
    undefined appendRule(DOMString rule);
    undefined deleteRule(DOMString key);
    CSSKeyframeRule? findRule(DOMString key);

    getter CSSKeyframeRule (unsigned long index);
};
```

**Comment by birtles** [comment]
According to the [WebIDL spec](https://webidl.spec.whatwg.org/#idl-indexed-properties),

> Interfaces that [support indexed properties](https://webidl.spec.whatwg.org/#dfn-support-indexed-properties) must define an [integer-typed](https://webidl.spec.whatwg.org/#dfn-integer-type) [attribute](https://webidl.spec.whatwg.org/#dfn-attribute) named "length".

I think the change needs to be:

```diff
[Exposed=Window]
interface CSSKeyframesRule : CSSRule {
           attribute CSSOMString name;
  readonly attribute CSSRuleList cssRules;

+  getter CSSKeyframeRule (unsigned long index);
+  readonly attribute unsigned long length;

  undefined        appendRule(CSSOMString rule);
  undefined        deleteRule(CSSOMString select);
  CSSKeyframeRule? findRule(CSSOMString select);
};
```

I'm happy to do that and add the necessary WPT if no one objects.

As for `insertRule`, it doesn't appear to be in Gecko or Blink so I suppose either Webkit should drop it or file a separate issue for adding it?

**Comment by cdoublev** [comment]
I am a bit late but I assume the expected rule's order is the order of appearance in `@keyframes`, isn't it? Maybe it would have been usefull to sort them by start time, and fallback to appearance order when two rules have the same start time.

**Comment by birtles** [comment]
> I am a bit late but I assume the expected rule's order is the order of appearance in `@keyframes`, isn't it?

I think so. It's basically just an alias for `cssRules`.
