### ISSUE TITLE
[css-color] Previews in <pre> blocks—rendering bug

### ISSUE THREAD

**Issue by matatk** [w3c/csswg-drafts#7688]
*This comment is from the APA WG and relates to [our review of CSS Color Module Level 5](https://github.com/w3c/a11y-request/issues/29#issuecomment-1236389445).*

The previews inside code example blocks can't expand outside of those blocks, so aren't drawn fully in those cases. Would it be possible to alter the rendering, so that the blocks can expand visually to their usual full size, even when they're in `<pre>` blocks?

**Comment by svgeesus** [comment]
This has been fixed in the editor's draft, see for example

https://drafts.csswg.org/css-color-5/#ex-swop5v2

As a consequence of this fix, the "link to this example" self-link is also visible.

This change will propagate to the /TR version next time it is published.

**Comment by svgeesus** [comment]
@matatk could you confirm that you no longer see this issue, in the Editor's Draft?

**Comment by matatk** [comment]
@svgeesus actually I am still finding this issue, e.g. in [Example 13](https://drafts.csswg.org/css-color-5/#example-077312cb) and others in the Editor's Draft. It seems to be a problem when the code example is just one line high.

The visible self-links are very handy, though looks like the current implementation poses at least one accessibility barrier (lack of clear name), and _might_ have a contrast issue. I have made a note to come back and check this out and file issues and suggestions if needed.

*(Thanks for your quick replies on all of these APA issues; I'll respond as soon as I'm able.)*

**Comment by svgeesus** [comment]
> It seems to be a problem when the code example is just one line high.

OK, I found and fixed it.

**Comment by svgeesus** [comment]
>  have made a note to come back and check this out and file issues and suggestions if needed.

If so, please [file them on Bikeshed](https://github.com/tabatkins/bikeshed) so they get fixed for all specifications, not just this one.

**Comment by svgeesus** [comment]
> might have a contrast issue.

I believe it is fine. Text color is `rgb(3,69,117)` and background is white, so [APCA L<sup>c</sup> is 92.5](https://www.myndex.com/APCA/?BG=ffffff&TXT=034575&DEV=G4g&BUF=A22)

**Comment by matatk** [comment]
> OK, I found and fixed it.

Just to confirm: [Example 13](https://drafts.csswg.org/css-color-5/#example-077312cb) and others in the Editor's Draft are now working for me too; thanks. I had a quick look at several others, and they were all fine. Your fix to the CSS seems comprehensive, so feel free to close this if you too think it's all addressed.
