### ISSUE TITLE
[css-color] Test result indication accessibility

### ISSUE THREAD

**Issue by matatk** [w3c/csswg-drafts#7689]
*This comment is from the APA WG and relates to [our review of CSS Color Module Level 5](https://github.com/w3c/a11y-request/issues/29#issuecomment-1236389445).*

_This is quite possibly a bug in a library you're using, though I couldn't find any pointers after a brief search relating to WPT._

There's a low contrast difference between the two sections of the pie charts. This is particularly apparent in [§4](https://www.w3.org/TR/2022/WD-css-color-5-20220628/#color-function).

Suggestion: use techniques similar to those from [Figure 21 in the Understanding WCAG SC 1.4.11 document](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html#figure-passing-pie-chart), i.e. (1) separating the segments; (2) using more contrasting colours; and/or (3) using hollow and solid segments to ease differentiation.

**Comment by svgeesus** [comment]
Thanks. These inline pie-charts are generated by Bikeshed, and thus affect all CSS specifications and indeed all Bikeshed-generated specifications which reference Web Platform tests. 

So I'm going to open a new issue over there.
