### ISSUE TITLE
[css-color] Accessibility of Figures in §4.4 and §5

### ISSUE THREAD

**Issue by matatk** [w3c/csswg-drafts#7691]
*This comment is from the APA WG and relates to [our review of CSS Color Module Level 5](https://github.com/w3c/a11y-request/issues/29#issuecomment-1236389445).*

**[§4.4 Figure 5](https://www.w3.org/TR/2022/WD-css-color-5-20220628/#fogra51-roundtrip)**

* The `<img>` needs `alt` text such as "A color swatch, in a grid layout".
* The second part is marked up as a `<table>` but doesn't seem to be one semantically (it's just placing the text to match the layout of the color swatch above). Suggest applying `role="presentation"` to the table, to remove the tabular structure semantics (or you could re-code it using `<div>`s and `<span>`s). That would have the effect of linearizing the table from a screen reader perspective, but that would likely be less confusing than encountering a "table" without headers.

**[§5](https://www.w3.org/TR/2022/WD-css-color-5-20220628/#device-cmyk) Figure 6** [doesn't have an `id`]

* The `<img>` needs an `alt` attribute that explains this is a color swatch in a grid formation (as per figure 5) but that circles are imposed on each grid square. The `<figcaption>` does a great job of explaining the rest.
* As with figure 5, this table should have the table semantics removed (or be re-coded using `<div>`s and `<span>`s).

**Comment by svgeesus** [comment]
Thanks for these helpful comments.

I wonder whether adding row and column numbers/letters (to both the image, and also as headers to the table) would help? So someone could talk about row C, column 4 for example?

A linear list of 24 numbers, as a screen reader presentation, doesn't seem al that helpful.

**Comment by svgeesus** [comment]
By the way its a shame that putting a description in the SVG `<desc>` element is wasted effort from an accessibility point of view, it seems screen readers ignore it and also ignore that the text in SVG is actual text: they just say "image".

Here is the `<desc>` for the SVG in figure 5:

```html
<desc>Show the L=50 plane of the CIE Lab color space.
      Two colors to be mixed are visualized on this plane,
      with an arc to show where the intermediate colors lie.
      peru lch(62.253% 54.011 63.677) rgb(80.39% 52.16% 24.71%) lab(62.253, 23.95015324432121, 48.41051828449609)
      lightgoldenrod lch(91.374% 31.415 98.821) rgb(93.33% 90.98% 66.67%) lab(91.374, -4.8174283819125385, 31.043431008590908)
      40% mix is lch(79.7256% 40.4534 84.7634) rgb(87.41% 76.03% 47.64%) lab(79.7256, 3.69213016556943, 40.28455965255785)

</desc>
```

**Comment by svgeesus** [comment]
(Sigh, I keep labelling commits with the wrong issue number, there are two very similar. sorry!)

**Comment by matatk** [comment]
Yes, I agree; the headers you've added are helpful. Part of accessibility is helping to give people an equivalent frame of reference, so they can collaborate—so this sort of coordination (literally) is spot-on.

In theory you shouldn't need the `scope` attribute on the table header cells, and I just tested in the latest Firefox and Chrome, with NVDA and JAWS, and there was no problem with them interpreting which were column and row headers, so the markup you have is fine.

**Comment by svgeesus** [comment]
Given that, I will apply the same fix to the other figure.

**Comment by svgeesus** [comment]
@matatk is this issue now resolved to your satisfaction in the Editor's Draft?

**Comment by matatk** [comment]
@svgeesus your changes are great; thanks. I haven't closed this issue with this comment though, because when I visit [figure 5 in the Editor's Draft](https://drafts.csswg.org/css-color-5/#fig-fogra51-roundtrip) the changes to the images don't show up for me (have tried hard-refreshing).

**Comment by svgeesus** [comment]
That sounds like a local cache issue to me. Could I suggest directly viewing

https://drafts.csswg.org/css-color-5/images/macbeth-roundtrip.svg

and then doing a hard refresh on that?

**Comment by svgeesus** [comment]
@matatk are you seeing the updated figure, now?

**Comment by svgeesus** [comment]
@matatk please confirm?

**Comment by matatk** [comment]
Sorry for the delay. The Editor's Draft is currently inaccessible, but when I follow the link you gave to the files directly ("macbeth-*.svg") I can see the changes are there; thank you! Feel free to close.

**Comment by svgeesus** [comment]
Apologies. Meanwhile please use https://w3c.github.io/csswg-drafts/css-color-5/ until the down-every-day official csswg drafts server is fixed.
