### ISSUE TITLE
[css-color] Color previews are missing from Example 33

### ISSUE THREAD

**Issue by matatk** [w3c/csswg-drafts#7692]
*This comment is from the APA WG and relates to [our review of CSS Color Module Level 5](https://github.com/w3c/a11y-request/issues/29#issuecomment-1236389445).*

**[§4.4 Example 33](https://www.w3.org/TR/2022/WD-css-color-5-20220628/#ex-fogra39-fallback-mq)**: Color previews are missing.

**Comment by svgeesus** [comment]
As it says, immediately after the example:

> Note: This example does not use illustrative swatches, because most of the colors are outside of sRGB.

**Comment by matatk** [comment]
Oops! Apologies; closing.

**Comment by svgeesus** [comment]
No problem!

I mean I could do an OOG one, if it helps.

**Comment by svgeesus** [comment]
I went back and added an  oog swatch
