### ISSUE TITLE
[css-scroll-snap] Clarify aligned snap points where the scroll container is impossible to scroll to are valid (or not)

### ISSUE THREAD

**Issue by hiikezoe** [w3c/csswg-drafts#7698]
So for example, if the scroll container's snapport width is 200px and a child element's width is 100px and the child element's scroll-snap-align is `end`. Then if the child element is positioned at 0px, it's impossible to align the end of the element position, 100px at the scroll container's edge. 

I believe in such cases, the UAs still need to snap the the element itself, but from the spec text it's unclear.

**Comment by johannesodland** [comment]
The spec defines that the used snap position is the position resulting from scrolling as much as possible towards the snap position:

> If a [snap position](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-position) is unreachable as specified, such that aligning to it would require scrolling the [scroll container](https://www.w3.org/TR/css-overflow-3/#scroll-container)’s viewport past the edge of its [scrollable overflow area](https://www.w3.org/TR/css-overflow-3/#scrollable-overflow-region), the used snap position for this [snap area](https://www.w3.org/TR/css-scroll-snap-1/#scroll-snap-area) is the position resulting from scrolling as much as possible in each relevant axis toward the desired snap position.

https://www.w3.org/TR/css-scroll-snap-1/#unreachable

**Comment by hiikezoe** [comment]
Thanks! I wonder why I did miss the part.
