### ISSUE TITLE
[css-ruby-1] Descriptions of space-between and space-around

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#770]
https://drafts.csswg.org/css-ruby-1/#valdef-ruby-align-space-between

My assumption is that the difference between wide-cell and narrow-cell justification described by  example 11 (in the description of space-around) is equally relevant to both the preceding description of space-between.  As it is, it's ambiguous at best, but leans towards not being relevant for space-between, because otherwise you'd expect it to appear in that earlier section.

Use of an example figure also breaks the pattern of previous descriptions to have an example figure rather than just a plain figure for the wide-cell case.  Besides which, i think that it is illustrating important aspects of the model, so should not just be an example.

I suggest, add the text of example 11 to the section that describes space-between (as ordinary text, not an example figure), including the narrow-cell illustration.  (The space-around description already says "As for 'space-between except...", so nothing extra needed there.)

**Comment by frivoal** [comment]
Fixed, thanks for raising this.

**Comment by r12a** [comment]
ednit: "there exists an extra justification opportunities"

Mix of plural & singular.
