### ISSUE TITLE
[scroll-animations-1] Term for concept of timeline phases

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#7701]
In #7044 we [resolved](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1204032112) to add the [concept of named timeline phases](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1175722383):

> * Add the concept of named timeline phases. Certain types of timelines (such as ViewTimelines) will provide such phases. (In the future, other types of timelines may offer named phases, or we might add the ability to have custom named phases.)

However, there are concerns with using the term phases for this, @birtles [pointed out](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1060133970) that [effect phases](https://drafts.csswg.org/web-animations-1/#animation-effect-phases-and-states) would still exist (even if the prior timeline phases concept went away) and have a fairly different meaning. For the css shorthand property we could avoid using the term, however we would still need a name for this concept in the spec and likely need to use this concept name for the interface used for #7589.

So far the only alternative term to phase that has been proposed is cue, so our current options are:
* phase (stick with the current proposed terminology)
  You could think of these as the same as effect phases (ranges of time) and they could even exist alongside before and after phases, though it does feel as if it should be a single active phase at any time which may not continue to be true.

* cue
  Define this new term, representing a range of the timeline time.

In addition to choosing a term we should also decide what to call [the shorthand](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1175722383):
> Add shorthand that expands a phase name to 0% start delay and 100% end delay. E.g. animation-phase: contain expands to animation-delay: contain 0%; animation-end-delay: contain 100%.

This could be any of the options [I proposed on the original issue](https://github.com/w3c/csswg-drafts/issues/7044#issuecomment-1216946378) or we could omit the shorthand entirely. However on further thought I feel like this should be some variation on animation-delay as it could be used to express start and end delay, and currently the end delay is not settable via CSS. My strawman proposal would be to expand the existing `animation-delay` property to accept one (current version, just specify start delay) or two values (start and end delay), where either of those delays can include phases as proposed.

```
animation-delay: <start delay> <end delay>?
```
Where either delay is `<time> | <phase> | <phase> <percent>`. Omitting the `<percent>` would resolve to 0 or 100% depending on whether this is the start or end delay.

**Comment by kevers-google** [comment]
How about "range" instead of "phase" or "cue"?

**Comment by fantasai** [comment]
Cues aren't time ranges, they're points in time. So I think I'd like to veto that idea.

**Comment by flackr** [comment]
So just to update the proposal, we can call the concept timeline ranges.

In CSS, we can make animation-delay a shorthand for specifying start and end delay, and/or a named range, i.e.
```
animation-delay:
    <timeline-range-name> |
    <animation-delay-start> |
    <animation-delay-start> <animation-delay-end>
```
Where:
* When only `<animation-delay-start>` is specified, `<animation-delay-end>` computes to 0 for backwards compatibility.
* `<animation-delay-start>` and `<animation-delay-end>` are `<time> | <timeline-range-name> <percentage>`
* When just specifying `<timeline-range-name>` it will expand to `<timeline-range-name> 0% <timeline-range-name> 100%` to automatically fill the specified range.

Given this, I don't know if we need an `animation-range` property.

**Comment by fantasai** [comment]
@flackr  Current draft is using the term “named timeline range”, fwiw. Maybe review https://drafts.csswg.org/scroll-animations-1/#timeline-ranges again and let me know what you think?

**Comment by flackr** [comment]
Looks good to me!
