### ISSUE TITLE
[css-cascade-6] Can we replace the selector scoping notation with a new parameter in `querySelector()`?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#7709]
CSS Cascade L6 defines a [selector scoping notation](https://drafts.csswg.org/css-cascade-6/#selector-scoping) which is functionally the same as the `@scope` rules, but is designed as a selector syntax rather than an at-rule. There is also an inline issue, noting the purpose of that:

> This notation was added in order to allow scoping limits to be applied within `querySelector()`. Is this something we want to have?

In practice, the selector notation is much more difficult to design in a readable way. The basic syntax is less clear than the at-rule, we haven't yet determined how it interacts with nesting, and it's become a blocker for otherwise-straight-forward issues like #6577. If we don't absolutely need this syntax, and can find another solution for scoping `querySelector()`, I would like to remove it from the spec.

My proposal would be:
- Add a second `lowerBoundary` parameter to both `querySelector()` and `querySelectorAll()`.
- Remove the 'selector scoping notation' from Cascade 6

**Comment by tabatkins** [comment]
In particular, the current second argument to qS() is, effectively, the upper bound of scoping; we could expand the argument to be an options bag with `{upper: [nodes], lower: [nodes]}` to accommodate both directions.

**Comment by mirisuzanne** [comment]
Meanwhile, the other half of the `@scope` feature (proximity awareness) is already available in selectors using the `>>` combinator.

**Comment by mirisuzanne** [comment]
Closing this here, since our spec has been updated - and a new issue is opened on the WHATWG/dom spec.
