### ISSUE TITLE
[css-ruby-1] Treatment of multiple Latin words in space-between & space-around

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#771]
https://drafts.csswg.org/css-ruby-1/#valdef-ruby-align-space-between

I think it would be useful to have some text, and perhaps another illustration, showing what would happen if you have more than one word in narrow-cell annotations.  For space-between, my assumption is that if you have a two word annotation in Latin script over a longer base, the left edge of the word on the left would be flush with the left edge of the base, and the rightmost character of the other word would be flush with the right edge of the longer item.  

The question is what happens between the two words. That could leave a good sized gap in the middle, which is what Firefox does, or cause the browser to stretch the inter-character spacing in order to reduce the gap between the words, which is what Edge does. There is a test for this at:
https://www.w3.org/International/tests/repo/run?base=css-ruby-1&batch=css-ruby&test=ruby-align-property/ruby-align-space-between-104.html

Are either of those correct, or is just one appropriate, or is it specifically undefined?  Either way, i think the spec should say something.

**Comment by upsuper** [comment]
I think Edge's behavior looks better, but I have no idea how that can be speced.

**Comment by fantasai** [comment]
It's controlled by `text-justify`, so if the author or UA prefers inter-character spacing instead of inter-word, that can be specified.

**Comment by r12a** [comment]
> For space-between, my assumption is that if you have a two word annotation in Latin script over a longer base, the left edge of the word on the left would be flush with the left edge of the base, and the rightmost character of the other word would be flush with the right edge of the longer item.

I'm starting to think that this assumption derived from the spec text is incorrect, and that multiple word annotations in Latin text would simply be centred just like single word annotations.  

My previous assumption arose because of the mention of justification being applied.  However, i'm inclined to think that justification is not appropriate if the annotation contains narrow characters (pinyin, english,... ) including spaces – the approach is simply to centre the text.  That way, a space would not send two words to opposite sides of the annotation space.

Note that `space-around` is the default value for `ruby-align`, so i think this divergent behaviour needs to be specified as standard for this value.

Note that Firefox already does this by default if the language of the ruby element is zh-hans/t.

I guess it would be helpful to ask the jlreq & clreq folks to confirm the expected behaviour.

**Comment by r12a** [comment]
> I guess it would be helpful to ask the jlreq & clreq folks to confirm the expected behaviour.

For Chinese, the answer appears to be no justification is expected for multiple word annotations in narrow character text. See https://github.com/w3c/clreq/issues/125

**Comment by fantasai** [comment]
I think we might want to specify explicitly that `text-justify: auto`, when applied in the context of a ruby annotation, does not offer a justification opportunity on space characters. This would get us the right behavior, and the author could opt into either `inter-character` or `inter-word` spacing explicitly if that was wanted.

For base text, though, I think it does need to be spaced out if the annotation is really long.

**Comment by r12a** [comment]
> For base text, though, I think it does need to be spaced out if the annotation is really long.

Yes. This is only about ruby text.

**Comment by himorin** [comment]
For JLReq side: 

- There was one missing Note in English version of simple-ruby (filed as https://github.com/w3c/simple-ruby/issues/53), which states 'base or annotation with Western word space' (nearly equal to multi-word text) is out of scope.
- In JIS X 4051, rule of justification between base text and annotation does not use Western word space as adjustment (see issue https://github.com/w3c/simple-ruby/issues/53).
- Seems no definition in JLReq. 
- In JLReq, [one note](https://w3c.github.io/jlreq/#n121) mentions a case of using far shorter annotation than base text, and a way to set maximum size of leading and trailing spacing as half of base character could be taken for preventing misleading appearance (to tell a correct range of ruby base). See [attached figure](https://w3c.github.io/jlreq/#fig2_3_21) also.
- In certain case of Japanese digital publishing ([list of demands](http://www.ebpaj.jp/images/youbou.pdf) item 155; only in Japanese; see background etc. in [cover page](http://ebpaj.jp/counsel/youbou)), expanding Western word space for justification between base and annotation is included. (similar to one upper item, use Western word space characters for 1-2-1 spacing)
- In [discussion within JLReq TF](https://lists.w3.org/Archives/Public/public-i18n-japanese/2021JanMar/0028.html), **no strong desire was pointed**, but could be similar tendency to CLReq one.
- There are multiple difficult open questions, such as which ones (spaces between words or intercharacter points) to use for adjustment, to align leading and trailing between base and annotation (or to have spacing up to half of width of base character, etc.), and we'd keep out of scope.

**Comment by fantasai** [comment]
Proposal:

* Explicitly specify that `text-justify: auto`, in the context of a ruby annotation, does not offer a justification opportunity on space characters.
* Authors can opt into either `inter-character` or `inter-word` spacing explicitly if that was wanted.
* This does not apply to ruby base text.

@r12a @himorin Do you think this would solve the problem?

**Comment by himorin** [comment]
I believe `text-justify: auto` by default for (multiple) Latin words matches to demands of JL-TF, and also opt-in model matches with demands from digital publishing. So, I agree that proposal would solve the problem (and presented demands).

Note: putting () to a word 'multiple' is just that such configuration also produces the same result for single Latin word case as already mentioned in example 15 of css-ruby spec.

**Comment by r12a** [comment]
> Do you think this would solve the problem?

Seems good to me. Thanks.

**Comment by fantasai** [comment]
[Additional notes](https://github.com/w3c/csswg-drafts/issues/771#issuecomment-1182339573):
- Also remove justification opportunities from bopomofo.

**Comment by frivoal** [comment]
@r12a This has now been edited it. Review appreciated.
