### ISSUE TITLE
Explore using w3c/spec-prod to (auto)publish CSS WG specs to w3c.github.io URLs, in parallel with drafts.csswg.org publication

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/csswg-drafts#7712]
Auto-publishing all CSS specs to https://w3c.github.io/csswg-drafts URLs should be possible — as far as I understand — using the same https://github.com/w3c/spec-prod tooling that many (or most) other W3C repos/groups are using.

Specifically, as documented at https://github.com/w3c/spec-prod/blob/main/docs/examples.md#multiple-specs-in-same-repository:

> If you maintain multiple documents in the same repository, you can provide source-destination pairs to build, validate and deploy each one separately.

So, for example, the CSS specs could be auto-published at URLs such as the following:

- https://w3c.github.io/csswg-drafts/css-shapes-1
- https://w3c.github.io/csswg-drafts/css-fonts-4

…though note that without also doing some additional work beyond what the https://github.com/w3c/spec-prod tooling can do for us, we would not also have anything getting published at the following URLs:

- https://w3c.github.io/csswg-drafts/css-shapes
- https://w3c.github.io/csswg-drafts/css-font

However, I believe the https://github.com/andreubotella/csswg-auto-build/ tooling may provide some way we could borrow to automate publication to those symlink-like URLs.

Note that publishing to https://w3c.github.io/csswg-drafts URLs would not need to be an either-or versus the current publishing to drafts.csswg.org URLs — it could instead just be done in parallel, alongside the current drafts.csswg.org URLs.

The advantage of publishing to https://w3c.github.io/csswg-drafts URLs is reliability. As evidenced by the ongoing record of reports about drafts.csswg.org going down at https://github.com/w3c/csswg-drafts/issues/6528, users are continuing to regularly have problems viewing CSS specs at the drafts.csswg.org URLs.

So we could put the https://w3c.github.io/csswg-drafts publishing mechanism into place so that users have a reliable way to view CSS WG drafts during the period of time while the work is going on to fix the drafts.csswg.org backend.

I realize that specs published at https://w3c.github.io/csswg-drafts URLs may not have all the same features that specs published at drafts.csswg.org URLs have — but, while recognizing that the CSS WG may make use of some additional in-spec features to get their work done, it’s not clear that most web developers and readers in the wider community need or use any such additional features. Instead they just want to be able to read the actual spec text reliably. And auto-publishing to https://w3c.github.io/csswg-drafts URLs will allow us to give that to them.

**Comment by tabatkins** [comment]
And done.

**Comment by tabatkins** [comment]
(Huge thanks to @andreubotella since I just straight up stole all of their code.)

**Comment by andreubotella** [comment]
The code that builds the index of specs for the mirror is using heuristics based on the Bikeshed metadata for each spec (and the `<title>` element for HTML specs) to figure out the name for each spec and to apply various heuristics to determine which level is the current work for each module. Since this mirror setup is now being maintained in this repo, it might make sense to also maintain a JSON file with that data, which could perhaps be also used by @plinss's server.
