### ISSUE TITLE
[css-overflow-4] give scrollbar-gutter the ability to decide whether overlay or classic scrollbars should be used instead of only the user agent

### ISSUE THREAD

**Issue by karl-police** [w3c/csswg-drafts#7716]
Apparently, [scrollbar-gutter](https://drafts.csswg.org/css-overflow/#scrollbar-gutter-property) is finished and there's no possibility to create overlay scrollbars with it. Instead, the scrollbar-gutter definition, it says this:

> Whether [classic scrollbars](https://drafts.csswg.org/css-overflow/#classic-scrollbars) or [overlay scrollbars](https://drafts.csswg.org/css-overflow/#overlay-scrollbars) are used, the appearance and size of the scrollbar, and whether scrollbars appear on the start or end edge of the box, is UA defined.

&nbsp;

I quote "is UA defined". Google Chrome added an experiment with that which can be toggled on the flags. It is an overlay scrollbar, but though it has some issues, and for some reason they gave it some animation and you can't control the style of it.

&nbsp;

Why should only the user agent, be able to decide whether they see Classic Scrollbars or Overlay Scrollbars? So that would mean, the user using the browser would go to the settings to change it.

Aren't there ways to do those overlay scrollbars with the help of javascript or something? So why not give the web developer the choice to make those overlay scrollbars happen? But without JS.

What if the user agent wants to use both or let the website decide?

**Comment by Loirooriol** [comment]
See #6090

**Comment by karl-police** [comment]
> See #6090

What am I supposed to see there?

**Comment by Loirooriol** [comment]
That there was no implementation interest to have a feature to enforce overlay scrollbars, which is pretty close to what you are asking.

**Comment by karl-police** [comment]
> That there was no implementation interest to have a feature to enforce overlay scrollbars, which is pretty close to what you are asking.

implementation interest from who?

**Comment by tabatkins** [comment]
"Implementation interest" means interest from the implementors - that is, browser vendors. In other words, we specifically had some browser vendors object to this as a feature, indicating they would not implement it.

So yeah, #6090 has the details of the conversations that happened around this feature, making this a dupe.

**Comment by karl-police** [comment]
> "Implementation interest" means interest from the implementors - that is, browser vendors. In other words, we specifically had some browser vendors object to this as a feature, indicating they would not implement it.
> 
> So yeah, #6090 has the details of the conversations that happened around this feature, making this a dupe.

Where can I continue this conversation though?
