### ISSUE TITLE
[css-grid] `auto` and `span` should be invalid named cell tokens

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7723]
`grid-template[-areas]: "auto span"` is valid whereas `auto` and `span` are not valid `<custom-ident>` in `<grid-line>` and `<line-names>`. Authors can still use them as named grid areas and reference their lines with `auto|span-start|end` though.

This rule seems mandatory for `<grid-line>` otherwise its parsing would be ambiguous, but not for `<line-names>`. Is it intentional or is it an oversight in [parsing `<string>+` of `grid-template-areas`](https://drafts.csswg.org/css-grid-2/#valdef-grid-template-areas-string)?

> A line name cannot be `span` or `auto`, i.e. the `<custom-ident>` in the `<line-names>` production excludes the keywords `span` and `auto`.

https://drafts.csswg.org/css-grid-2/#named-lines

> In all the above productions, the `<custom-ident>` additionally excludes the keywords `span` and `auto`.

https://drafts.csswg.org/css-grid-2/#typedef-grid-row-start-grid-line

**Comment by tabatkins** [comment]
Intentional, just for consistency.

**Comment by cdoublev** [comment]
So `grid-area: span` is invalid to avoid ambiguity, and `grid-template: [span] 1px` is invalid for consistency. My question is: shouldn't `grid-template-areas: "auto span"` also be parsed as invalid, for consistency?

Considering this design...

```html
<style>
  #container {
    display: grid;
    grid: "auto span";
  }
</style>
<div id="container">
  <div id="item"></div>
</div>
```

... I can place `#item` in row 1 / column 2 with `grid-area: span-start` but not with `grid-area: span`.

**Comment by cdoublev** [comment]
I got it, thanks.
