### ISSUE TITLE
[mediaqueries-5] Define logical evaluation steps for custom media

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#7725]
Aside from a note that these must be evaluated logically I can't find how this must work in detail.

https://drafts.csswg.org/mediaqueries-5/#custom-mq

> The [custom media query](https://drafts.csswg.org/mediaqueries-5/#custom-media-query) is evaluated logically, not treated as a textual substitution. Take the following code snippet for instance:

An obvious case that seems highly problematic is : 

```css
@custom-media --mq screen and (max-width: 30em);

@media print and (--mq) {
  /* two types have been defined, "print" and "screen" */
}
```

With the [PostCSS plugin](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-custom-media#readme) this currently becomes something that feels random and is obviously incorrect :

```css
@media print and (max-width: 30em) {
  /* two types have been defined, "print" and "screen" */
}
```

------

Can the logical evaluation steps be defined in the specification?
This would ensure that we have interop between a PostCSS plugin and what might eventually land in browsers. (ignoring bugs)

Alternatively it might be interesting to simplify the custom media proposal:

1. Only allow `<media-condition>` in `@custom-media`:

```css
/* allowed */
@custom-media --mc (min-width: 300px)

/* not allowed */
@custom-media --mq screen and (min-width: 300px)
```

2. Only allow `<extension-name>` to be used as a full `<media-query>`

```css
/* allowed */
@media screen and (min-width: 300px), --mq {}

/* not allowed */
@custom-media screen and (--mq)
```

**Comment by tabatkins** [comment]
I'm not quite sure what's unclear - you evaluate it as a MQ, rather than textually substituting.

So yeah, your first example will never match, as the custom MQ will only match in screen media, while the second MQ only matches in print media. That's not problematic, it's just always-false.

If you're trying to replicate custom MQs *by doing* text substitution, you need to take care about that - two clashing media types will always result in an always-false, since precisely one media type can be true at a time. So you should handle such a case by subbing in an always-false MQ. If the two media types agree, then you can just drop the one from the custom MQ. If the outer MQ doesn't specify a type a tall, you can promote the custom MQs type to the main rule.

If PostCSS is just dropping the media type from the custom MQ, it's simply wrong.

**Comment by romainmenke** [comment]
I think I get what you mean.
In a browser context the custom media query can be evaluated on its own after which they would be equivalent to using `true` or `false` in the final media query.

```css
@custom-media --modern (color), (hover);

@media (--modern) and (width > 1024px) {
  .a { color: green; }
}

/* when hover or color */
@media (true) and (width > 1024px) {
  .a { color: green; }
}

/* when not hover or color */
@media (false) and (width > 1024px) {
  .a { color: green; }
}
```

I don't think there is a good analogue for this purely with text substitution.
But I will try to patch the plugin so that what is possible works correctly and that other cases throw warnings.

> If PostCSS is just dropping the media type from the custom MQ, it's simply wrong.

It is indeed very wrong at the moment and this is something I am trying to correct for a whole range of plugins. Either they shouldn't be advertised as polyfills for native features or they must follow the spec exactly.

---

Closing as my question was answered and I don't think any changes are needed.

**Comment by romainmenke** [comment]
_In case anyone else working on a preprocessor/fallback tool finds this ticket_

I think it is possible to provide an accurate and complete fallback for custom media.

Any `(--my-custom-media)` should be replaced by `true` if the referenced media query is true and `false` when it is false. (this sounds super obvious but this is non-trivial with text manipulation)

This means that we can leverage nested `@media` rules and conditions that are always `true` or `false` to mimic custom media.

```css
@custom-media --simple-feature-test (min-width: 300px);

@media not (--simple-feature-test) {
    .a {
        order: 3;
    }
}
```

becomes :

```
@media  (min-width: 300px) {
    @media not (max-color:9999943) {
        .a {
            order: 3;
        }
    }
}

@media  not (min-width: 300px) {
    @media not (color:9999943) {
        .a {
            order: 3;
        }
    }
}
```

`max-color:9999943` is something that is always `true`.
`color:9999943` is something that is always `false`.

This example is a bit trivial but the same technique works equally well for more complex examples.
