### ISSUE TITLE
[css-grid] Explain why empty `<line-names>` is allowed

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7726]
[`<line-names>`](https://drafts.csswg.org/css-grid-2/#typedef-line-names) allows an empty set since [this commit](https://github.com/w3c/csswg-drafts/commit/50024d7abd6d5721a8a63fc4a23cddb1531e8151) but there is no meaningfull commit message. I would like to know why `[]` should be allowed, noting that there is a [consensus to remove it](https://github.com/w3c/csswg-drafts/issues/4173#issuecomment-533474227) when serializing `repeat()`. Maybe it could be explained in a note.

**Comment by Loirooriol** [comment]
See https://lists.w3.org/Archives/Public/www-style/2013Nov/0329.html

> The current ED defines line names as:
> `<line-names> = ( <ident>* )`
> do we really want to allow empty line name lists? I guess we don't, and that should be replaced by "<ident>+", shouldn't it?

And https://lists.w3.org/Archives/Public/www-style/2013Nov/0337.html

> No, we need empty line lists for subgrids (they can specify their own names in addition to any names they inherit, and need empty line lists to clarify that they're not naming a particular line).  It doesn't hurt normal grids to allow empty line lists either; it's just equivalent to omitting the parentheses too.

**Comment by cdoublev** [comment]
Thanks. I should make a habit of searching in the public archives...

I do not know subgrid well enough to have an opinion on how usefull it is to explicitly define a subgrid with `subgrid []` vs. `subgrid`.

It's now clear to me, but I will let you decide if this issue should be closed or if it should remain open until a related note is added.

**Comment by Loirooriol** [comment]
The thing with subgrid is that `subgrid [] [a]` and `subgrid [a]` are different, you can't just omit empty `[]`, because it will change the position of following line names.

I guess a note might have been useful for level 1 since it has no subgrid, but current work is now level 2 so it's probably not worth it.
