### ISSUE TITLE
[css-values-4] Level 4 spec erases `<number-percentage>` type defined in level 3

### ISSUE THREAD

**Issue by AtkinsSJ** [w3c/csswg-drafts#7727]
Level 3 defines the [`<number-percentage>`](https://www.w3.org/TR/css-values-3/#typedef-number-percentage) type as follows:

> `<number-percentage>`
>    Equivalent to `[ <number> | <percentage> ]`, where the `<percentage>` will resolve to a `<number>`.

This type is used in the [Filter Effects spec](https://drafts.fxtf.org/filter-effects-1/#funcdef-filter-contrast), and probably in other places too, but I don't actually know off the top of my head.

Level 4 however, does not define `<number-percentage>`, and instead says in a note in [5.6. Mixing Percentages and Dimensions](https://www.w3.org/TR/css-values-4/#mixed-percentages):

> A `<number-percentage>` will never be added, as `<number>` and `<percentage>` can’t be combined in `calc()`.

Whether it can be used in `calc()` or not, it still needs to exist as a type. (Or the inconsistency needs to be resolved some other way.)

**Comment by tabatkins** [comment]
Filter Effects just needs fixing to `[ <number> | <percentage> ]`.

**Comment by svgeesus** [comment]
Fixed with 

 - https://github.com/w3c/fxtf-drafts/commit/fe40e6efc92d644983f538cc72995cf73535ca8c
