### ISSUE TITLE
[css-grid-2] Add link for ambiguous reference.

### ISSUE THREAD

**Issue by tiaanl** [w3c/csswg-drafts#7732]
There is mention here to "See above" when referencing intrinsic sizing.  Up to this point there is not a lot of mention about intrinsic sizing and even the title of the paragraph it is referencing to has no mention of intrinsic sizing.  The title only says: "Sizing Grid Containers".  A link to the actual paragraph would be much more descriptive here:

https://github.com/w3c/csswg-drafts/blob/main/css-grid-2/Overview.bs#L992

Possibly just changing `(See above)` to `(<a>intrinsic-sizes</a>)`

**Comment by fantasai** [comment]
Added a cross-reference, thanks for the suggestion!
