### ISSUE TITLE
[css-ruby-1] Default styling for chinese annotations

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#775]
A.1 Supporting Ruby Layout
https://drafts.csswg.org/css-ruby-1/#default-ua-ruby

the default UA style sheet information includes the following:

```
rtc:lang(zh), rt:lang(zh) {
  ruby-align: center; }
rtc:lang(zh-TW), :not(rtc) > rt:lang(zh-TW) {
  font-size: 30%; }               /* bopomofo */
```

This indicates that all Chinese ruby should implement `ruby-align:center` as the default, rather than that declared in the spec, which is `space-around`.  As clreq mentions centered as standard for pinyin as well as bopomofo, think this merits at least a note in the spec text, rather than just being hidden away in this appendix – especially given that most ruby will be either Japanese or Chinese.

However, the font-size applied to zh-TW of 30% is likely to be problematic, and I'm inclined to think that this shouldn't be in the spec, or if it is, you should draw a little more attention to it so that people wanting to use pinyin with trad chinese are aware that they need to change the font-size setting. Also:
1. traditional chinese with bopomofo may be labelled as zh-Hant
3. given that the browser/font has to be involved in positioning the bopomofo annotations, and that  centring shouldn't apply to the tone marks, perhaps the centring and possibly also the sizing isn't actually needed as a default for bopomofo.  As it is, such a default doesn't actually help unless the browser/font can go the remainder of the way towards representing bopomofo annotations, so it seems redundant in the default stylesheet.

(i think we may have started this discussion before, but i couldn't find it in the cosmic chaos that preceded the advent of github. I don't think we concluded it anyway.)

**Comment by fantasai** [comment]
Handling the centering issue in https://github.com/w3c/csswg-drafts/issues/779

Wrt 30% being problematic:
    * Without it, it seems that bopomofo would not fit very well, right? So on balance it seems better to keep it.
    * Wrt drawing more attention to the 30% default, I think anyone authoring such a page would be several orders of magnitude more likely notice by seeing it rendered in the browser than by noticing a note in the spec. :)
    * Happy to take advice on whether to include zh-Hant, I'm not familiar with which lang tags bopomofo ruby is most likely to be used with. If you're sure we should include zh-Hant, I will include it. But Hant also applies to e.g. Hong Kong, which doesn't use bopomofo, right?
    * The positioning of tone marks is with respect to the base text, and isn't affected by alignment except insofar as that content is adjusted. It doesn't get independently aligned. So this is a non-issue.

So my inclination here is no change, or maybe add zh-Hant. What does i18n recommend?

**Comment by fantasai** [comment]
Note: 30% comes from Taiwan Ministry of Education: https://language.moe.gov.tw/001/Upload/files/SITE_CONTENT/M0001/deploy/html_en/index.html

**Comment by frivoal** [comment]
confirmed with i18n-WG at TPAC on September 13 2022.

**Comment by r12a** [comment]
For centring see https://github.com/w3c/csswg-drafts/issues/779

**Comment by ngnhat** [comment]
https://drafts.csswg.org/css-ruby-1

ruby,
rt {
  unicode-bidi: isolate;
}

to bug fix annotations text
