### ISSUE TITLE
[scroll-animations-1] ViewTimeline values of startOffset/endOffset in RTL writing mode

### ISSUE THREAD

**Issue by ydaniv** [w3c/csswg-drafts#7752]
Currently the spec says: 

> Note: The value of startOffset can be greater than endOffset, for example in the horizontal axis in a right-to-left (rtl) writing mode.

Which would render scroll-animations very awkward when actually having to deal with in RTL mode. Even more so if we're considering that the names of these properties are logical (start/end) and they should work the same for any writing mode.

The issue noted below in the spec says:

> This makes the offsets compatible with the way scrollLeft and scrollTop work, which go negative from zero in RTL scroll containers, is this how we want it to work here?

Which seems less relevant since `scrollTop/Left` are in fact non-logical APIs.

So, I'd expect the logical APIs, `startOffset` and `endOffset`, to behave the same depending on writing mode.

cc @fantasai @flackr

**Comment by flackr** [comment]
In terms of developers writing animations for RTL mode (or other writing modes), the math works the same, i.e. the timeline still goes from 0% to 100% as you go from the writing-mode dependent start to the writing-mode dependent end so it shouldn't make a difference to the way you write effects AFAICT.

I could see an argument for the accessors returning logical coordinates, though the primary reason for reading back the coordinates would be debugging or associating scroll positions with the effect. If we use a system that doesn't match the srcolling APIs then doesn't that make it harder? Maybe this just means we need logical scroll offsets on scrolling boxes.
