### ISSUE TITLE
[css-ui] Tweaking outline-style: auto colors.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7761]
https://bugzilla.mozilla.org/show_bug.cgi?id=1791051 shows an interesting interop difference: https://jsfiddle.net/ht85jacp/

 * Firefox allows customizing auto-style outline using `accent-color`.
 * Chrome allows that using `outline-color`.
 * WebKit doesn't allow that.

I can provide some reasoning to why I implemented the Firefox behavior. `outline-style: auto` is intended to be the OS accent color by default. It behaves more like `appearance: auto` form control borders, so using `outline-color` would be rather weird. On the flip side, using `border-color` on form controls disables native appearance altogether, so maybe it's not that weird.

I have a preference for Gecko's behavior, but I'd be happy to listen to reasoning from Chrome's folks about why they honor `outline-color` instead... I think part of the issue I don't love it is because `outline: auto` would set `outline-color: currentColor`, which seems pretty unfortunate.

**Comment by argyleink** [comment]
> I'd be happy to listen to reasoning from Chrome's folks about why they honor outline-color instead

i can try and uncover why this was done the way it was, see if there was strong reasoning or an accident

**Comment by mfreed7** [comment]
So `accent-color` is [meant for form controls](https://w3c.github.io/csswg-drafts/css-ui/#widget-accent) ("widgets"), and I don't really think it should be used to change the focus ring or outline color on all elements. It is very unfortunate that the spec for `accent-color` was basically written as "do what you like, UA", so this is a grey area. But that was my interpretation of the spirit of the feature. Accent colors are pieces of form controls that typically render as an "accent" to the control. I don't think the outline falls into this category.

I'm curious about your comment that `outline-style: auto` is intended to be the *accent color* - isn't `outline-style` just the style (dotted, solid, etc.) of the outline?

I'm probably missing your point, so help me. But in Chromium, setting `outline-color` by itself just changes the color of whatever outline would normally be drawn. So setting `button {outline-color:red}` is a common way to change the color of focus rings without changing their style or dealing with `:focus-visible` rules. Setting `outline-style:auto` disables the focus ring painting behavior and just turns on the default outline (black 1.5px solid). But this feels fairly easy and works well, I'm not sure why we'd want to push toward `accent-color` for outlines.

**Comment by emilio** [comment]
> I'm curious about your comment that outline-style: auto is intended to be the accent color - isn't outline-style just the style (dotted, solid, etc.) of the outline?

`outline-style: auto`, when originally implemented, was the OS-native outline. In fact the spec still has:

> The auto value permits the user agent to render a custom outline style, typically a style which is either a user interface default for the platform, or perhaps a style that is richer than can be described in detail in CSS, e.g. a rounded edge outline with semi-translucent outer pixels that appears to glow.

So when implementing `accent-color`, I made `outline-style: auto` follow it so that the outline color of widgets was consistent.

> Setting outline-style:auto disables the focus ring painting behavior and just turns on the default outline (black 1.5px solid). But this feels fairly easy and works well, I'm not sure why we'd want to push toward accent-color for outlines.

Well, in Gecko `outline-style: auto` is not just an alias for `black 1.5px solid`. For us, it has two segments (one of 2px, one of 1px) of different colors (accent color + accent-foreground color).

The default UA sheet in the HTML spec has:

```
:focus-visible { outline: auto; }
```

That really expands to `outline-style: auto; outline-color: currentColor; ...`. I don't think `outline: auto` should force black (or lose colors) of the default outline.

**Comment by mfreed7** [comment]
So I think I agree with you that setting `outline: auto` should "go back to native appearance" and not just set an outline that's different than the default. That behavior does feel kind of broken.

But I think that in a similar way, `outline-color` should just change the color of that default appearance, without changing anything else. And that should be the "knob" used to change color of focus rings, instead of `accent-color`. The `accent-color` property is meant to target things that don't already have a property, like widgets within form controls. Since there's already a property that is exactly specific to the outline color (`outline-color`), let's use it.

**Comment by emilio** [comment]
> But I think that in a similar way, `outline-color` should just change the color of that default appearance, without changing anything else. And that should be the "knob" used to change color of focus rings, instead of `accent-color`. The `accent-color` property is meant to target things that don't already have a property, like widgets within form controls. Since there's already a property that is exactly specific to the outline color (`outline-color`), let's use it.

Well, for natively-themed form controls, the accent-color should probably also control the outline color shouldn't it? The same way it might affect the border colors and so on.

The way to make `outline: auto` do the right thing while respecting `outline-color`, would be to change the initial value of `outline-color`, is that what you're proposing?

**Comment by mfreed7** [comment]
> Well, for natively-themed form controls, the accent-color should probably also control the outline color shouldn't it? The same way it might affect the border colors and so on.

I don't know! I think here, too, the user assumes the focus ring is something the *page* provides, and isn't specific to the element. I feel like it'd be weird for a normally-blue focus ring to change to pink when it hit a pink-accented checkbox, for example.

> The way to make `outline: auto` do the right thing while respecting `outline-color`, would be to change the initial value of `outline-color`, is that what you're proposing?

So first, I meant (initially) and I think you meant here, `outline-style: auto`, not `outline:auto`, right? Since `outline` is a shorthand, I'm not sure we should add an `auto` value to that, but maybe.

For `outline-style`, the spec seems pretty clear what `auto` itself means, as you pointed out. However, it says this about the other two:

> As such, this specification does not define how the [outline-color](https://w3c.github.io/csswg-drafts/css-ui/#propdef-outline-color) and [outline-width](https://w3c.github.io/csswg-drafts/css-ui/#propdef-outline-width) are incorporated or used (if at all) when rendering auto style outlines.

Perhaps we should amend that to say something about trying to use `outline-color` as much as possible when `outline-style: auto`? It probably can't be more specific or normative than that, since the UA style (e.g. Firefox's) might include more than one color, or gradients, etc. But I'm in favor of trying to push in that direction.

**Comment by emilio** [comment]
> So first, I meant (initially) and I think you meant here, outline-style: auto, not outline:auto, right? Since outline is a shorthand, I'm not sure we should add an auto value to that, but maybe.

No, I meant `outline: auto`. `outline: auto` expands to `outline-style: auto; outline-color: currentColor; outline-width: medium;`. Since `currentColor` can't be magic, we'd need a different initial `outline-color` of sorts.

> Perhaps we should amend that to say something about trying to use outline-color as much as possible when outline-style: auto? It probably can't be more specific or normative than that, since the UA style (e.g. Firefox's) might include more than one color, or gradients, etc. But I'm in favor of trying to push in that direction.

I think we at least need a fix for `outline: auto` to do the right thing rather than forcing black outlines. I think in Blink what you have in the UA sheet is something like `-webkit-focus-ring-color`, which doesn't follow the spec afaict.

**Comment by mfreed7** [comment]
> > So first, I meant (initially) and I think you meant here, outline-style: auto, not outline:auto, right? Since outline is a shorthand, I'm not sure we should add an auto value to that, but maybe.
> 
> No, I meant `outline: auto`. `outline: auto` expands to `outline-style: auto; outline-color: currentColor; outline-width: medium;`. Since `currentColor` can't be magic, we'd need a different initial `outline-color` of sorts.

Sorry - can you help me with a spec link to the definition for `outline: auto`? I don't see it [here](https://w3c.github.io/csswg-drafts/css-ui/#outline), it just appears to be a normal shorthand for `[ <'outline-color'> \|\| <'outline-style'> \|\| <'outline-width'> ]`, and then those have their own initial values, which are `outline-style: none; outline-color: invert; outline-width: medium;`.

If that's the wrong spec link, help me find the right one, please?

+@lilles for more informed comments here.

**Comment by lilles** [comment]
@mfreed7 `outline: auto` would set `outline-style: auto` because that's the only longhand that accepts the `auto` keyword. The other longhands will be reset to their initial values since there are no values for them in the shorthand. That is, `outline-color: currentColor` and `outline-width: medium`.

**Comment by mfreed7** [comment]
> @mfreed7 `outline: auto` would set `outline-style: auto` because that's the only longhand that accepts the `auto` keyword. The other longhands will be reset to their initial values since there are no values for them in the shorthand. That is, `outline-color: currentColor` and `outline-width: medium`.

Ahh. Thanks!

Ok, I see the problem now. Would a fix be to change the `:focus-visible` UA style to `outline-style:auto` instead of `outline:auto` then?

**Comment by frivoal** [comment]
Edits done, tests pending.
