### ISSUE TITLE
[css-values-4] Viewport Units clarifications

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#7764]
As part of the [Interop 2022 Viewport Investigation Effort](https://github.com/web-platform-tests/interop-2022-viewport/) we noticed there are some aspects not explicitly defined, leaving room for interpretation.

1. [How do Viewport-Percentage lengths behave on browsers with no dynamic UA UI Elements?](https://github.com/web-platform-tests/interop-2022-viewport/issues/12)
  In User Agents that have no dynamic UA toolbars, the Large+Small+Dynamic Viewport all have the same size. This is not explicitly mentioned, and could wrongfully be interpreted as “these User Agents have no dvh/lvh/svh units”.
  
1. [Is `100dvh` clamped between `100svh` and `100lvh`?](https://github.com/web-platform-tests/interop-2022-viewport/issues/14)
  In some browsers we noticed `100dvh` can grow larger than `100lvh` in very specific scenarios. This looks like a browser bug, but it would be good if the spec were backing this up here by explicitly mentioning that the value of `dvh` is clamped between `svh` and `lvh`.

Two minor remarks/clarifications in the spec could solve this.

**Comment by fantasai** [comment]
> https://github.com/web-platform-tests/interop-2022-viewport/issues/12
> In User Agents that have no dynamic UA toolbars, the Large+Small+Dynamic Viewport all have the same size. This is not explicitly mentioned, and could wrongfully be interpreted as “these User Agents have no dvh/lvh/svh units”.

@bramus The spec already states “There are four variants of the [viewport-percentage length](https://www.w3.org/TR/css-values-4/#viewport-percentage-lengths) units, corresponding to four **(possibly identical)** notions of the viewport size.” And is otherwise written that if you have no dynamic UI the definitions have meaning. Do you really think this needs to be called out as a likely point of confusion?

**Comment by tabatkins** [comment]
Re: dvh between svh and lvh, the three definitions are based on the exact same verbiage around "dynamic UI elements", just with one assuming all closed, the other assuming all opened, and the third being "dynamic consideration of". There is no way to interpret this language as allowing dvh to be outside the svh/lvh range, so this looks to just be a simple bug in impls (basing the actual calculations on different data and not realizing they can result in different ranges), not a bug in the spec.

**Comment by bramus** [comment]
If it doesn’t need clarifying then this one may be closed without any changes. Thanks!
