### ISSUE TITLE
[css sizing] auto <length> description may have wrong "otherwise"

### ISSUE THREAD

**Issue by hamishwillee** [w3c/csswg-drafts#7769]
For `contain-intrinsic-size: auto <length>` my understanding is that the intent is that if the content has never been rendered you won't have a remembered value, so you will use the `length` value for size constrained layout. If however you have ever been able to render the content you will have a remembered value for the size, and you'll use that instead. 

The [spec here](https://w3c.github.io/csswg-drafts/css-sizing-4/#valdef-contain-intrinsic-width-auto-length) does not appear to say that.

The first part implies it:

> `auto` [`<length>`](https://w3c.github.io/csswg-drafts/css-values-4/#length-value)
If the element has a [last remembered size](https://w3c.github.io/csswg-drafts/css-sizing-4/#last-remembered) and is currently [skipping its contents](https://w3c.github.io/csswg-drafts/css-contain-2/#skips-its-contents), its [explicit intrinsic inner size](https://w3c.github.io/csswg-drafts/css-sizing-4/#explicit-intrinsic-inner-size) is the last remembered size.

>
> Note: This occurs, for example, when an element with [content-visibility: auto](https://w3c.github.io/csswg-drafts/css-contain-2/#propdef-content-visibility) is off-screen.

My interpretation of that is that you use the remembered value when you are offscreen and have a remembered value and have `auto` set. That makes sense - you're using a remembered value because you can't recalculate one.

But then the spec says:

> Otherwise, its [explicit intrinsic inner size](https://w3c.github.io/csswg-drafts/css-sizing-4/#explicit-intrinsic-inner-size) is the specified [`<length>`](https://w3c.github.io/csswg-drafts/css-values-4/#length-value).

That "otherwise" is all other cases. To me that means that if you are not skipping the contents you will use length. I suspect in most cases you won't be using size containment, but if you are, this means you aren't using the remembered value even if you could. 

---

As an aside, the following paragraph reads as gibberish:

> If an element has an [explicit intrinsic inner size](https://w3c.github.io/csswg-drafts/css-sizing-4/#explicit-intrinsic-inner-size) in an axis, then after laying out the element as normal for [size containment](https://w3c.github.io/csswg-drafts/css-contain-2/#size-containment), the size of the contents in that axis are instead treated as being the explicit intrinsic inner size instead of what was calculated in layout, and layout is performed again if necessary. (If it has an explicit intrinsic inner size in both axises, this implies the first layout can be skipped.)

I may just be completely missing the point but "after laying out the element as normal for [size containment](https://w3c.github.io/csswg-drafts/css-contain-2/#size-containment)"  should means that there is nothing calculated in the layout.

**Comment by Loirooriol** [comment]
> To me that means that if you are not skipping the contents you will use length

Yes, that was deliberate, see #6308.

> the following paragraph reads as gibberish

Yes, see #7519. @tabatkins  said he would add some examples to clarify what the text is trying to say.

**Comment by hamishwillee** [comment]
@Loirooriol Thanks. I don't see how that follows from #6308 . That's about making sure that the onscreen element is not rendered with outdated dimensions. It makes sense not to render using a remembered value. But what I think this text stays is that you would in this case render with `<length>` which is _also_ an outdated dimension in that it's a guess at what the element might be. Right?

I will look at the #7519 examples.

Thanks for considering the comments. I appreciate that they probably seem a bit stupid when you understand all the context.

**Comment by Loirooriol** [comment]
To avoid using the outdated dimension, it's using the specified `<length>` instead of the last remembered size. The `<length>` is not outdated, it's a value explicitly provided by the author, if the author wants another value they can update `contain-intrinsic-size`.

**Comment by hamishwillee** [comment]
Ah! The logic I saw "somewhere" for providing auto was that it helps because getting the `<length>` correct can be difficult and using `auto` is likely to result in values that are closer to the actual rendered size. Thank you.

**Comment by hamishwillee** [comment]
I guess I should outline my concern with a real case. 

Imagine you have an offscreen element that has `content visibility: auto`. It has a remembered value and since it is offscreen and the contents are being skipped, this is value is being used for layout.

The user scrolls the element near to the view so the user agent starts rendering the elements. At this point it starts using the `length` because it is not skipping the child elements. 
1. Wont there potentially be some kind of visual effects due to the switch over?
2. Why ever both user using `auto`? How is it better to store the value  when you're always going to be switching to length at some point?

**Comment by hamishwillee** [comment]
@Loirooriol My concerns here are answered. 

I was mostly concerned about the case when the element is coming into view from offscreen - i.e.  why you would choose not to use the remembered size in this case. You answered this two comments above in https://github.com/w3c/csswg-drafts/issues/7769#issuecomment-1254005385; it's because you're not in size containment anymore so you're not skipping the content. IN other words you're not using the length OR the remembered size.

"remembering" is a way of getting the benefits of size containment when you're offscreen without actually having to "think about it". If something is actually "planned" to be size contained and is visible then using the user-supplied length makes sense.

Thanks for taking the time to spell it out for me. Closing this - I'll keep an eye on https://github.com/w3c/csswg-drafts/issues/7519

**Comment by Loirooriol** [comment]
I think it may be worth discussing whether to improve the case with both `content-visibility: auto` and `contain: size`, so filed #7807.
