### ISSUE TITLE
[cssom-view] Restore `"instant"` IDL enum value of ScrollBehavior

### ISSUE THREAD

**Issue by saschanaz** [w3c/csswg-drafts#7773]
#3074 removed "instant" from the IDL, arguing that it's removed from `scroll-behavior` CSS property. But that enum value is not for CSS but for scroll APIs and is still supported on all engines including Gecko, Blink, and WebKit. It's behavior is different from `"auto"`, per https://w3c.github.io/csswg-drafts/cssom-view-1/#perform-a-scroll:

> 2. If the user agent honors the [scroll-behavior](https://w3c.github.io/csswg-drafts/css-overflow-3/#propdef-scroll-behavior) property and one of the following are true:
> 
>     * behavior is "auto" and element is not null and its computed value of the [scroll-behavior](https://w3c.github.io/csswg-drafts/css-overflow-3/#propdef-scroll-behavior) property is [smooth](https://w3c.github.io/csswg-drafts/css-overflow-3/#valdef-scroll-behavior-smooth)
>     * behavior is smooth 
> 
>    ...then perform a [smooth scroll](https://w3c.github.io/csswg-drafts/cssom-view-1/#concept-smooth-scroll) of box to position. Once the position has finished updating, emit the [scrollend](https://w3c.github.io/csswg-drafts/cssom-view-1/#eventdef-document-scrollend) event. Otherwise, perform an [instant scroll](https://w3c.github.io/csswg-drafts/cssom-view-1/#concept-instant-scroll) of box to position. After an instant scroll emit the scrollend event.

Passing `"instant"` allows devs to force instant scroll regardless of `scroll-behavior` property.

Hi @tabatkins, I think you were confused there, what do you think?

**Comment by saschanaz** [comment]
Can someone else take a look if @tabatkins is busy, perhaps @emilio?

**Comment by emilio** [comment]
Yeah I think that was a mistake.
