### ISSUE TITLE
[css-align-3] Fallback alignment groups with orthogonal items.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#7775]
Consider: https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=10774

```html
<!DOCTYPE html>
<div style="display: flex; flex-direction: column; align-items: baseline; width: 100px; border: solid 3px; direction: ltr;">
  <div style="writing-mode: vertical-rl; background: lime;">line1<br>line2</div>
  <div style="writing-mode: vertical-lr; background: lime;">line1<br>line2</div>
  <div style="background: cyan;">orthog</div>
</div>
```

Here there are two baseline groups. The VRL item goes into one, and the VLR + HTB items go into another. The HTB item goes into the VLR group due to:
https://drafts.csswg.org/css-align-3/#baseline-export
"Otherwise, assume either [horizontal-tb](https://drafts.csswg.org/css-writing-modes-4/#valdef-writing-mode-horizontal-tb) or [vertical-lr](https://drafts.csswg.org/css-writing-modes-4/#valdef-writing-mode-vertical-lr) [writing-mode](https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode), whichever is orthogonal to the box’s own writing-mode."

The VLR group goes to the left, the VRL group goes to the right.

Now consider:

```html
<!DOCTYPE html>
<div style="display: flex; flex-direction: column; align-items: baseline; width: 100px; border: solid 3px; direction: rtl;">
  <div style="background: cyan;">orthog</div>
</div>
```

Here all impelementations (currently) place the orthog group on the right. But this should likely be the left.
There are many WPTs asserting this behaviour.

Is the "Otherwise, assume either" correct? Should it be VRL instead? Should it look at the direction to keep a small amount of consistency? (Is my interpretation correct?)

**Comment by fantasai** [comment]
I think switching between VRL and VLR based on `direction` makes sense, and would be fine with putting that in the spec.

**Comment by bfgeek** [comment]
... and the VLR group would stay on the left, and VRL on the right independent of the `direction` (I assume).

**Comment by fantasai** [comment]
OK, I made a pull request for this: https://github.com/w3c/csswg-drafts/pull/8342

I noticed the following comment in the source code, however:
> `<!-- This pairing is chosen because the most likely case for this situation is CJK. -->`

which might be worth taking into consideration.
