### ISSUE TITLE
[css-fonts] @font-palette-values base-palette descriptor should have a `none` value.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#7780]
Otherwise there's no way to "unset" the palette value. Generally, there should be a way to represent that state.

cc @jfkthame @drott @svgeesus @litherum

**Comment by jfkthame** [comment]
I don't think I understand why there'd be a need for this. AFAICS, according to the spec, the absence of `base-palette` would be equivalent to a specified `base-palette: 0`. So what would be the use-case for `none`?

**Comment by drott** [comment]
@emilio Are you thinking about this case from an CSSOM perspective or so? (Is there a CSSOM representation of `@font-palette-values`? FWIW, the 0-indexed palette in a font is the default palette. To render COLRv0 or COLRv1 glyphs, you can't render without a palette, unless the glyphs only contain the color index `0xFFFF` which represents the foreground color. I haven't tested whether our font stack handles fonts without a CPAL table or without a default palette correctly - so in that sense, I am not sure it would be desirable to reset this state to: "Don't refer to any base palette.". What should be the behaviour if @font-palette-values then sparsely defines a new palette, but some indices are missing - should the corresponding parts of the glyphs be rendered with transparent color?

**Comment by emilio** [comment]
I filed this because in @jfkthame's patches for this rule on Gecko, we're using different state to represent "no base specified", and I assumed that would have a different behavior than specifying any other base. But if that's not the case I guess this is not needed. I did miss the:

> If this descriptor is not present in the @font-palette-values, or if the font does not contain a palette at the index of the value of base-palette, it behaves as if 0 were specified.

bit.
