### ISSUE TITLE
[css-color-4] Does CSS Color normatively require that HTML elements use/match system-colors in the UA stylesheet?

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#7781]
The WPT test [css/css-color/system-color-consistency.html](https://wpt.fyi/results/css/css-color/system-color-consistency.html) seems to require that the UA stylesheet use (or at least match at computed value time) the [system-colors](https://www.w3.org/TR/css-color-4/#css-system-colors) defined in CSS Color 4.

```
      test_computed_value('color', 'ButtonBorder', style.getPropertyValue('border-color'), 'resolves to the same color as the border-color of a ' + element.name);
```

I can't tell if this is a real requirement of the spec, or just something that the spec is suggesting. If it is a real requirement, it would be helpful if the spec was updated to explicitly specify which HTML elements and properties this applies to.

**Comment by svgeesus** [comment]
> For systems that do not have a particular system UI concept, the specified value should be mapped to the most closely related system color value that exists

I think that makes it hard to test, and te descriptions are deliberately vague and non-prescriptive. The actual WPT is fairly conservative, like testing for the color of the canvas.

I think this makes more sense to test together with forced color mode, tbh.

**Comment by svgeesus** [comment]
To answer the specific question as asked: I think that WPT is poor because "most closely related value" is not testable. The spec is giving guidance, not making a hard requirement. 

Closing as question answered and no change to the spec, but feel free to point to this issue as justification when deleting or trimming down that test.
