### ISSUE TITLE
[selectors] Refer to DOM "document element" in :root's definition 

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#7787]
https://drafts.csswg.org/selectors/#the-root-pseudo

> The :root pseudo-class represents an element that is the root of the document.

>
> For example, in a DOM document, the `:root` pseudo-class matches the root element of the [`Document`](https://dom.spec.whatwg.org/#document) object. In HTML, this would be the [`<html>`](https://html.spec.whatwg.org/multipage/semantics.html#the-html-element) element (unless scripting has been used to modify the document).

----

Perhaps in the main definition, but at least in the DOM-specific paragraph, consider referencing DOM's [**document element**](https://dom.spec.whatwg.org/#document-element) term directly. By my reading, it's the precise term for what's colloquially referred to as the "root element". E.g.

> The `:root` pseudo-class represents the document's [document element](https://dom.spec.whatwg.org/#document-element).

Or

> For example, in a DOM document, the `:root` pseudo-class matches the [document element](https://dom.spec.whatwg.org/#document-element).

**Comment by tabatkins** [comment]
Fixed. Assuming commenter is satisfied, as we did exactly what they asked for. ^_^ (Worded slightly differently, but still.)

**Comment by cvrebert** [comment]
I am satisfied. Thanks.
