### ISSUE TITLE
[css-ruby-1] Default ruby centring for more than just zh

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#779]
A.1 Supporting Ruby Layout
https://drafts.csswg.org/css-ruby-1/#default-ua-ruby

the default UA style sheet information includes the following:

```
rtc:lang(zh), rt:lang(zh) {
  ruby-align: center; }
```

This establishes centred display for ruby for Chinese, but there are other language subtags that indicate that text is chinese besides the generic `zh`.  These should presumably also be included here.  

The current list of more specific tags recommended by the IANA subtag registry rather than `zh` is:
`cdo cjy cmn cpx czh czo gan hak hsn lzh mnp nan wuu yue`.

**Comment by upsuper** [comment]
I don't think it's worth adding them. Web content shouldn't use them.

If we really want to take those tags into consideration, we really need a new mechanism to handle macrolanguages, rather than listing everything inside it.

**Comment by patrickdark** [comment]
My experience is that the language is a lot less important than the script for styling purposes. `zh-latn` and `zh-hans` or `zh-hant` have different styling considerations.

**Comment by fantasai** [comment]
It seems to me we might want to just remove this rule, and rely on controlling the justification opportunities instead. The reason Chinese is centered by default here because its annotations tend to be in Latin (Pinyin) or Bopomofo. But when they are in Hanzi, they are not centered, they are spaced out.

**Comment by upsuper** [comment]
(For my own reference, filed [Gecko bug 1691243](https://bugzilla.mozilla.org/show_bug.cgi?id=1691243) for this change)

**Comment by upsuper** [comment]
I had another look at the issue, and it seems to me that bopomofo does have justification opportunities inside, so removing `ruby-align: center` may not work for it. And I think it makes sense for bopomofo to have justification opportunities, as they are like kanas in Japanese that they can mix into a piece of Chinese text, and if such piece of text is justified, bopomofo should behave just like Chinese characters.

But I also agree that when the annotation is Chinese, it seems right to hae it spaced out. Not sure how we can solve this conflict.

**Comment by frivoal** [comment]
(reopening, so that we don't forget to deal with @upsuper's comment)

**Comment by aphillips** [comment]
CSS will ping I18N when text is written for review by CLREQ

**Comment by frivoal** [comment]
@upsuper we've now made edits to deal with https://github.com/w3c/csswg-drafts/issues/779#issuecomment-968197327. Feedback appreciated.

**Comment by upsuper** [comment]
Looks good to me, thanks.
