### ISSUE TITLE
[cssom-view] checkVisibility and filter:opacity(0)

### ISSUE THREAD

**Issue by hcesar** [w3c/csswg-drafts#7795]
Currently, [Element.checkVisibility](https://drafts.csswg.org/cssom-view/#dom-element-checkvisibility) (specifically in checkOpacity section) is not checking for `filter:opacity(0)`.

Is this a deliberate choice or could it be reconsidered?

**Comment by vmpstr** [comment]
Sounds reasonable to consider this. FWIW, the choice was not deliberate

**Comment by fantasai** [comment]
Supposing at some point we had custom filters that were capable of making something transparent, having `opacity()` and its custom equivalent behave differently, even though they're both filters in the `filter` property, seems odd. So I think I'd lean towards not treating it specially.

**Comment by karip** [comment]
It's possible to make an element visible even if it uses `filter: opacity(0)`, like this:

HTML:

    <svg>
      <filter id="flood">
        <feFlood flood-color="green" flood-opacity="0.5"/>
      </filter>
    </svg>
    <div>Hello</div>

CSS:

    div {
      filter: opacity(0) url(#flood);
    }

Here's [jsfiddle](https://jsfiddle.net/qwt2645k/). For these cases, browsers would have to investigate the resulting pixels, which can be expensive.
