### ISSUE TITLE
[css-view-transitions-1] User input should be ignored when rendering is suppressed.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7797]
#7784 details how rendering should be suppressed during a transition. We also need to ignore user input (irrespective of how rendering is suppressed) in this state. That's because the visual state of the Document displayed to the user doesn't align with the DOM state.

Note that the user agent may need to dispatch synthetic events to ensure the input stream observed by the developer makes sense. For instance, the user puts their finger down when rendering is suppressed which causes a [touchstart](https://w3c.github.io/touch-events/#event-touchstart) event. If rendering is unsuppressed while the user finger is still down script would directly see a [touchmove](https://w3c.github.io/touch-events/#event-touchmove) event. It makes sense to dispatch a synthetic touchstart event in this case. But this detail can be left up to the user agent.

**Comment by khushalsagar** [comment]
**Proposed Resolution**: User input is discarded for each Document with [transition suppress rendering](https://drafts.csswg.org/css-view-transitions-1/#document-transition-suppressing-rendering) set.

**Comment by jakearchibald** [comment]
https://user-images.githubusercontent.com/93594/205042084-dd6f02b6-3068-4734-bf80-b51bd47ff5a2.mp4

There are three states in terms of what the user sees:

- The real DOM
- Paused render
- The transition pseudos

With the real DOM, input goes to the real DOM. With the pseudos, input goes to the document element. I don't think we should add a third behaviour for the paused render case.

Throwing input away could cause more of a 'glitch' in the [gesture example](https://twitter.com/jaffathecake/status/1595811562614558720), as dropped events would mean the initial position could be out of sync with actual pointer position.

Doing a hit-test on the real DOM seems risky, as elements might be in completely different places.

So, I vote that we do the same as in the "transition pseudos" state, and send events to the document element.

**Comment by khushalsagar** [comment]
> With the pseudos, input goes to the document element.

Input doesn't necessarily go to the document element for the transition pseudos case. Try the following example:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <style>
    .before {
      background: grey;
    }
    .after {
      background: lightblue;
    }
   
    #target {
      view-transition-name: target;
      contain: layout;
    }
    html {
      view-transition-name: none;
    }
    html::view-transition-new(*) {
      animation-duration: 5s;
    }
  </style>
</head>
<body>
  <script>
    function flip() {
      direct.classList.toggle("before");
      direct.classList.toggle("after");
    }
   
    function doTransition() {
      document.startViewTransition(() => {
        target.classList.toggle("before");
        target.classList.toggle("after");
      });
    }
  </script>
  <button class="before" onclick="doTransition()" id="target">Animate</button>
  <button class="before" onclick="flip()" id="direct">Flip</button>
</body>
</html>

```

Event handlers on DOM elements not participating in the transition continue to work throughout the transition. This is handy if your transitions changes a subset of the page.

The spec intent was to handle the pseudo DOM case the same as we would for hit-testing on any other pseudo-element. For example if the pointer location of the event is `::before`, the event is dispatched to its originating element. But `pointer-events: none` set on the pseudo-element will cause the hit-test to continue to the next possible target. Same way if the pointer location of the event is on any of the generated pseudos, the event is dispatched on their ultimate originating element (the document element). Otherwise it can resolve to a DOM element, if the location is different or the developer adds `pointer-events: none` to the pseudos.

That said, I'm ok with dispatching events to the document element while rendering is paused instead of dropping them entirely. I was hard pressed to think of a use-case where the developer could do anything meaningful with the events. Rendering is paused so its not like visuals can be updated in response to the event. But, if the transition is being driven by a gesture then the curve of the gesture could be used to influence the animation. The developer would need all touch move events to keep track of the curve.

**Comment by khushalsagar** [comment]
> I'm ok with dispatching events to the document element while rendering is paused instead of dropping them entirely.

A point worth clarifying here is that this is only relevant if a hit-test is needed while rendering is paused. There could be a case where the user input starts a scroll gesture, which has locked a target node, and a transition is initiated. The target node for the gesture shouldn't change for the duration of the scroll gesture.

**Comment by jakearchibald** [comment]
That's fair. I think I'm happy with either:

Option 1: Delay events until rendering is unblocked, then hit-test against the pseudos. I think this will be hard to spec 😄 

Option 2: Target events to the document element. I know this isn't 100% like it is when the pseudos are there, as you've detailed above, but I expect cases where the underlying DOM is revealed to be rare, especially once we have scoped view transitions.
