### ISSUE TITLE
[css-grid] Should `grid` shorthand prefer serializing as`<'grid-template'>` or with `auto-flow`?

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7805]
Consider
```js
element.style.cssText = `
    grid-template-rows: none;
    grid-template-columns: 100px;
    grid-template-areas: none;
    grid-auto-rows: auto;
    grid-auto-columns: auto;
    grid-auto-flow: row;
`;
element.style.cssText; // ???
```

The `grid` shorthand can represent these longhands in two different ways:

- ```css
    grid: none / 100px; /* <'grid-template'> */
    ```
    This sets `grid-template-rows: none`, `grid-template-columns: 100px`, and resets the other longhands to initial values.

- ```css
    grid: auto-flow / 100px;
    ```
    This sets `grid-auto-flow: row`, `grid-auto-columns` to the omitted `auto`, `grid-template-columns: 100px`, and resets the other longhands to initial values

Which one should be preferred? Firefox and WebKit (once https://github.com/WebKit/WebKit/pull/4648 lands) prefer serializing as `<'grid-template'>`.

Blink says `auto-flow auto / 100px`, but the serialization of `grid` is very broken in Blink, the logic also seems to prefer `<'grid-template'>` but it mistakenly fails to do so due to some bugs.

**Comment by tabatkins** [comment]
Oooh, good catch. @fantasai and I agree that serializing into the grid-template form is clearer, and especially since it matches two impls (and apparently is intended behavior for a third) we'll clarify the spec.

**Comment by Loirooriol** [comment]
Please review https://github.com/web-platform-tests/wpt/pull/36234 to update a test that was allowing both serializations.
BTW, how do I get the "Peer review is not required for CSS editors" superpower?
