### ISSUE TITLE
[css-shared-element-transitions-1] should animations retarget to new positions smoothly

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#7813]
In [shared element transitions](https://drafts.csswg.org/css-shared-element-transitions-1/) we use CSS animations to change the position and size of the pseudo elements from the "old" values to the "new" values, where new values are taken from the represented element (perhaps once a frame, depending on #7812). 

If the represented element changes position abruptly, this will cause the interpolated position of the pseudo element (that's mid-animation) to also change its position abruptly. 

Now, since these are UA generated animations, we have an opportunity to "smoothly retarget" to the new position by stacking several animations with a "to" keyframe and an implicit "from" keyframe, which would do a c-inf continuity on the path of the pseudo element.

That's adding a bunch of complexity but provides a nice polish for a page that tends to move the target element around with something like a layout shift: the animations would by default be always smooth

Should we do this?

**Comment by khushalsagar** [comment]
I think we can defer this. The whole point of the updateDOM callback is to allow the developer to fetch all resource required for a stable layout.

**Comment by vmpstr** [comment]
removing agenda, since I think the proposal is to not retarget for now, and revisit later
