### ISSUE TITLE
[css-shared-element-transitions-1] Should createDocumentTransition take an init dictionary or a callback

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#7827]
Currently the [shared element transition spec](https://drafts.csswg.org/css-shared-element-transitions-1/#additions-to-document-api) says that createDocumentTransition (modulo any renames in #7788) should take a dictionary, with currently a single member: updateDOM. 

Since updateDOM is a necessary, or at least a very commonly needed callback, should the signature instead be
`createDocumentTransition(callback)` and then if needed we can extend that to `createDocumentTransition(callback, initDictionary)`?

@jakearchibald

**Comment by khushalsagar** [comment]
I have a mild preference for `createDocumentTransition(callback, initDictionary)`. The non-optional parameter followed by an optional dictionary. This matches the `element.animate(keyframes, options)` syntax too.

**Comment by jakearchibald** [comment]
Related https://github.com/whatwg/webidl/issues/1191

**Comment by khushalsagar** [comment]
Discussed this offline today and the conclusion was that createDocumentTransition(callback) is the simpler and preferable syntax. So **proposed resolution**: "createDocumentTransition takes a callback".

@jakearchibald if I'm reading the whatwg issue right, we want to make callback and dictionaries indistinguishable. So we'd eventually be able to change the API to take a dictionary and the existing code (which passes a callback) would still work. So the above resolution is good for when we eventually have more options to switch to a dictionary?
