### ISSUE TITLE
[css-font-4][varfont] hyphens or spaces

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#783]
We have the following syntax for the descriptors:

`font-style: normal | italic | oblique [ <angle> | <angle>-<angle> ] ?`

`font-weight: normal | bold | [ <number> | <number>-<number> ]`

`font-stretch: normal | ultra-condensed | extra-condensed | condensed | semi-condensed | semi-expanded | expanded | extra-expanded | ultra-expanded | [ <percentage> | <percentage>-<percentage> ] `

I am not convinced we need the hyphens. How about making the syntax lighter, and using spaces instead?

`font-style: ... [ <angle> | <angle> <angle> ] ?`

`font-weight: ... [ <number> | <number> <number> ]`

`font-stretch: ... [ <percentage> | <percentage> <percentage> ] `

**Comment by frivoal** [comment]
Sorry, forgot the link. This is currently defined there: https://drafts.csswg.org/css-fonts-4/#font-prop-desc

**Comment by litherum** [comment]
Hyphens are good because they describe a range. Spaces are not good because they look like a sequence of individual values.

**Comment by frivoal** [comment]
Not convinced that this is universal (e.g. Japan would typically rather go for ~ than for - to denote a range), but I'd agree it is understood commonly enough, so why not.

Do we have other things in CSS where we denote a range? I know of unicode ranges, which are their own syntactic mess, but that's due to the combination of - for range and hex numbers, not to - alone. Anything else?

**Comment by davelab6** [comment]
@graphicore did CPS denote ranges?

**Comment by litherum** [comment]
I just realized that using `-` as a separator means you could have something like:

```css
font-style: oblique -20--10;
```

... which is quite yucky. Perhaps `/` is better.

**Comment by aaaxx** [comment]
How about an ellipsis (i.e., three dots)? They're already used for ranges in programming languages and surely make much more sense than a slash.

**Comment by tabatkins** [comment]
Please don't use hyphens to denote a range. They're more familiar in English, but they're hell for the CSS parser, which will happily parse "10%-20%" as `PERCENT(10) PERCENT(-20)`.  You're required to put a token-breaker (whitespace or comment) after the hyphen, and that requirement often isn't clear to authors.

Do not use a `/` - that's used for a specific purpose in CSS (separating two values who are otherwise grammatically undistinguishable). It's not used for decorative purposes.

We don't often add subsyntaxes for this sort of thing; we typically just let there be two values, and the meaning is inferred.  If you *really* think it's unclear, use a keyword - `<angle> [ to <angle> ]?` is clear and has no parsing issues.

**Comment by litherum** [comment]
What are our options?

1. `10% - 20%`
2. `10% 20%`
3. `10% / 20%`
4. ???

Out of the first three, I'm partial to option 2. But there may be other unexplored options.

**Comment by astearns** [comment]
as Tab noted above:

5. 10% to 20%

**Comment by litherum** [comment]
Whoops. Updated.

**Comment by frivoal** [comment]
I prefer 2 (`10% 20%`), I'm ok with 4 (`10% to 20%`).

**Comment by litherum** [comment]
Let's do option 2.

**Comment by Crissov** [comment]
@Litherum You missed @aaaxx’s suggestion: `10%...20%` or `10%..20%`. I believe that is a more friendly syntax for ranges than just spaces, but it has no precedent in CSS.

**Comment by bradkemper** [comment]
Hyphens are not really supposed to be for ranges anyway, except in very casual use. Typographically, an en dash is more appropriate:

http://www.thepunctuationguide.com/en-dash.html

Not that I'm suggesting we use an endash for this CSS use...

**Comment by yisibl** [comment]
The space-separated syntax, when I first saw it, I thought it was two separate values. Looking back at the syntax, it looks like it could be standardized as `10% to 20%`, that's what @litherum  said about [option 4](https://github.com/w3c/csswg-drafts/issues/783#issuecomment-284906759).

For example,  https://drafts.csswg.org/css-values-5/#progress-func

```
<progress()> = progress(<calc-sum> from <calc-sum> to <calc-sum>)
```
