### ISSUE TITLE
[css-fonts] Should `font-palette` be reset by the `font` shorthand?

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#7832]
Currently, [the spec for the `font` shorthand](https://drafts.csswg.org/css-fonts/#font-prop) says that:

>  All subproperties of the 'font' property are first reset to their initial values, including ... 'font-palette'.

However, it appears that neither the WebKit nor Blink implementations actually do this:

```
> document.body.style.fontPalette = "dark"
< 'dark'
> document.body.style.font = "12px sans-serif"
< '12px sans-serif'
> window.getComputedStyle(document.body).fontPalette
< 'dark'
```

Should the spec be revised to reflect implementation reality here, or should this simply be regarded as a bug in those browsers?

**Comment by emilio** [comment]
@litherum @drott was this intentional or an oversight?

**Comment by svgeesus** [comment]
The spec was only [recently clarified](https://github.com/w3c/csswg-drafts/commit/f9d74eef468f1958e501f1c97e4f09b259969e25) to explicitly list all the longhands which are reset by the `font` shorthand. So I suspect that this is simply implementation lag. The [spec is now pretty clear](http://w3c.github.io/csswg-drafts/css-fonts-4/#font-prop):

> All subproperties of the [font](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font) property are first reset to their initial values, including those listed above plus [font-size-adjust](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-size-adjust), [font-kerning](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-kerning), all subproperties of [font-variant](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-variant), [font-feature-settings](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-feature-settings), [font-language-override](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-language-override), [font-optical-sizing](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-optical-sizing), [font-variation-settings](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-variation-settings), and [font-palette](http://w3c.github.io/csswg-drafts/css-fonts-4/#propdef-font-palette).

**Comment by jfkthame** [comment]
And `font-synthesis`?

**Comment by svgeesus** [comment]
Good catch. Do we need to have discussion on a call so we are sure that the list of longhands reset by the `font` shorthand is

a) complete
b) agreed to be what we want?

**Comment by jfkthame** [comment]
I think it'd be worth asking the question, at least. I could imagine authors wanting to set `font-palette`, for example, on the root and not have it affected by shorthand `font` usage elsewhere.

**Comment by fantasai** [comment]
So if I understand correctly, what we have is the following:

**Set Explicitly**
```
font-style
font-weight
font-size
font-stretch (L3)
font-family
font-variant-caps (L2)
line-height
```

**Reset Implicitly**
```
font-size-adjust
font-kerning
font-variant-*
font-feature-settings
font-variation-settings
font-language-override
font-optical-sizing
```

**Cascaded Independently**
```
font-synthesis-*
```

And the question right now is whether `font-palette` belongs in **Reset Implicitly** or **Cascaded Independently**.

Fwiw, I think it'd be helpful to include a Note of any `font-*` properties _not_ reset by the `font` shorthand in the spec, so we're clear that leaving something out is not an oversight.

**Comment by svgeesus** [comment]
> And the question right now is whether `font-palette` belongs in **Reset Implicitly** or **Cascaded Independently**.

Exactly

**Comment by drott** [comment]
As we're currently working on the reset behaviour it'd be good to be able to quote an updated spec text.

**Comment by svgeesus** [comment]
I will try to get this done in the next few days

**Comment by svgeesus** [comment]
Added the list of set explicitly, reset implicitly and cascade implicitly groups.

**Comment by svgeesus** [comment]
@drott please [take a look](https://drafts.csswg.org/css-fonts-4/#font-prop)

**Comment by drott** [comment]
> @drott please [take a look](https://drafts.csswg.org/css-fonts-4/#font-prop)

Thanks, mostly LGTM, I left [two comments here](https://github.com/w3c/csswg-drafts/commit/b060a11d352391ca3545fd020e3f6871b7333d58) regarding extra prose in the beginning and end.

**Comment by cdoublev** [comment]
I do not see `font-variant-emoji` listed as a reset-only sub-property. Is it intentional?

**Comment by svgeesus** [comment]
> I do not see `font-variant-emoji` listed as a reset-only sub-property. Is it intentional?

Not intentional, thanks for noticing, corrected.

> Thanks, mostly LGTM, I left [two comments here](https://github.com/w3c/csswg-drafts/commit/b060a11d352391ca3545fd020e3f6871b7333d58) regarding extra prose in the beginning and end.

The "extra text" at the beginning has been there since CSS1, although I moved it to the start of the section.
I added your suggestion for better text at the end.

**Comment by drott** [comment]
Thanks for the edits, @svgeesus.
