### ISSUE TITLE
[css-nesting-1] Result of invalid selectors in nested rules

### ISSUE THREAD

**Issue by sesse** [w3c/csswg-drafts#7833]
The spec has the following example:

```
.foo {
  color: red;
  @nest .bar {
    color: blue;
  }
}
/* Invalid because there’s no nesting selector */
```

This is ambiguous; in particular, it does _not_ specify whether this is equivalent to

```
.foo {
  color: red;
}
```

or whether it's equivalent to nothing at all. The spec talks about “the rule” being invalid in a number of places, the that could refer to both the parent rule and the nested rule. Which is intended? The best is probably the latter (not the least because it's somewhat simpler to implement :-) ), but the standard needs to be clarified either way.

**Comment by sesse** [comment]
Seemingly a dup of #2880, which I couldn't find before now.

**Comment by tabatkins** [comment]
Yeah, this is a #2880 dupe, and the answer there remains correct - if an @nest is invalid, it gets dropped, but it doesn't affect the parent rule.

**Comment by sesse** [comment]
Despite the dupe, it would be good if the standard could be clarified, because right now, the example seems to suggest otherwise. :-) But #2880 is still open, so.
