### ISSUE TITLE
[css-pseudo] should all highlights have paired defaults?

### ISSUE THREAD

**Issue by delan** [w3c/csswg-drafts#7837]
#6386 asked a bunch of questions about paired defaults, which is the compat behaviour where the UA default ::selection ‘color’ and ‘background-color’ (‘HighlightText’ and ‘Highlight’) are only used when neither were set by the author.

In particular, question 3 asks whether this should apply to the other highlights too, and this issue is meant to resolve that question. Currently ::target-text is the only pseudo with defaults for those properties (‘MarkText’ and ‘Mark’), so it’s the only pseudo that’s affected by this issue.

One reason to say no is that ::target-text doesn’t have the legacy of ::selection that made this rule necessary. One reason to say yes is consistency, since the highlights are already a complicated enough pile of exceptions without adding an exception for just one of them. Another is that the behaviour can be useful for the same reasons it is for ::selection, that is, avoiding situations where the author setting only one of the properties yields an illegible result in another browser with different defaults.

(see also: [fantasai’s comment](https://github.com/w3c/csswg-drafts/issues/6386#issuecomment-886111107), [my comment](https://github.com/w3c/csswg-drafts/issues/6386#issuecomment-887624094), [emilio’s comment](https://github.com/w3c/csswg-drafts/issues/6386#issuecomment-908315479))

**Comment by astearns** [comment]
The bot missed adding the minutes. Here’s a hand-edited version:

RESOLVED: paired defaults apply to all highlights

<details><summary>The full IRC log of that discussion</summary>

> Topic: Paired defaults
> delan: This issue won't affect implementation complexity much, about what makes sense to authors
> delan: some highlight pseudos have default background color and default color
> delan: e.g. ::selection has default colors
> delan: and ::target-text
> delan: but it's not true for e.g. spelling/grammar error, where default styles add squiggly lines but don't change colors
> delan: ::selection has special behavior called "paried defaults"
> delan: rule is there for compat reasons
> delan: means that those default colors only get used
> delan: if neither color nor background was set by the author
> delan: beside compat, has some other benefits
> delan: prevents illegible combination of colors
> delan: e.g. some browsers have light text for selections, and some have dark text
> delan: so question is, should these apply to other highlight types?
> delan: or only to ::selection?
> florian: Point about default colors being relied on makes sense, so I would say yes it should apply to all
> emilio: Gecko doesn't have this magic if the author specifies selection styles
> 1emilio: do you know the state of interop?
> 1delan: it's also in Gecko
> 1emilio: if you specify ::selection  { background: green ; color: green; } we wouldn't magically infer the color
> 1delan: that's separate
> delan: this is if the author only sets one of these properties, does it get the UA color or does it get transparent/currentcolor
> delan: inverting is a separate issue
> florian: If we don't do it we have a risk of browser-dependent illegible things, and that's bad
> fantasai: I think propsoed resolution is, do we apply paired defaults to all highlights
> fantasai: so do we have any objections? if not we can resolve
> delan: so resolution is that they would apply to all fo the highights?
> florian: we have delan, fantasai, and myself agreeing and nobody is pushing back
> Rossen_: I'm not hearing any objections, so let's resolve
> Rossen_: if anyone thinks about this we can come back and change if necessary
> RESOLVED: paired defaults apply to all highlights

</details>

**Comment by delan** [comment]
#6665 assumed we would resolve in favour of ::target-text using paired defaults (see [this thread](https://github.com/w3c/csswg-drafts/pull/6665#discussion_r961007271)), so no edits needed :)

> Some [highlight pseudo-elements](https://drafts.csswg.org/css-pseudo/#highlight-pseudo-element) should have paired default highlight colors—a default [color](https://drafts.csswg.org/css-color-4/#propdef-color) and [background-color](https://drafts.csswg.org/css-backgrounds-3/#propdef-background-color) provided by the UA that are either used or overridden together, see [§ 3.3.1 Paired Defaults](https://drafts.csswg.org/css-pseudo/#paired-defaults). For [::selection](https://drafts.csswg.org/css-pseudo/#selectordef-selection) they should correspond to [HighlightText](https://drafts.csswg.org/css-color-4/#valdef-system-color-highlighttext) and [Highlight](https://drafts.csswg.org/css-color-4/#valdef-system-color-highlight), while for [::target-text](https://drafts.csswg.org/css-pseudo/#selectordef-target-text) they should correspond to [MarkText](https://drafts.csswg.org/css-color-4/#valdef-system-color-marktext) and [Mark](https://drafts.csswg.org/css-color-4/#valdef-system-color-mark).
