### ISSUE TITLE
[css-display] Short 'display: flow' should be Full 'display: block flow'

### ISSUE THREAD

**Issue by lcchueri** [w3c/csswg-drafts#7843]
In [css-display session 2](https://www.w3.org/TR/css-display-3/) , a informative table summarizes values of 'display' with 'Short Display' to 'Full Display', It has nearly all possibilities, except a short 'display: flow' row, which by syntax is a valid option.
So, for completeness, what´s the full value for display ? Should it be 'display: block flow' ?

**Comment by Loirooriol** [comment]
> Note: Following the precedence rules of “most backwards-compatible, then shortest”, serialization of equivalent [display](https://www.w3.org/TR/css-display-3/#propdef-display) values uses the “Short display” column.

So having two entries for `flow` and `block`, it wouldn't be clear which one is the right serialization.

There are also some `list-item` combinations which do not appear in the table, see https://github.com/w3c/csswg-drafts/issues/1493#issuecomment-314572350:

> The table is an informative guide to help authors, not a normative and complete mapping table

But yes, the full value of `flow` is `block flow`, as specified in https://www.w3.org/TR/css-display-3/#inner-model

> If a [`<display-inside>`](https://www.w3.org/TR/css-display-3/#typedef-display-inside) value is specified but [`<display-outside>`](https://www.w3.org/TR/css-display-3/#typedef-display-outside) is omitted, the element’s [outer display type](https://www.w3.org/TR/css-display-3/#outer-display-type) defaults to [`block`](https://www.w3.org/TR/css-display-3/#valdef-display-block)

**Comment by fantasai** [comment]
Closing out based on Oriol's explanation above; marking Commenter Satisfied since you marked a +1 ; let me know if that's a mistake.
