### ISSUE TITLE
[css-anchor] Different grammars per axis is not compatible with logical props

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#7847]
https://drafts.csswg.org/css-anchor-1/#anchor-pos

> The physical [`<anchor-side>`](https://drafts.csswg.org/css-anchor-1/#typedef-anchor-side) keywords (`left`, `right`, `top`, and `bottom`) must only be used in [inset properties](https://drafts.csswg.org/css-logical-1/#inset-properties) corresponding to the same axis: for example, [`top`](https://drafts.csswg.org/css-anchor-1/#valdef-anchor-top) and [`bottom`](https://drafts.csswg.org/css-anchor-1/#valdef-anchor-bottom) are valid in [`top`](https://drafts.csswg.org/css-position-3/#propdef-top) and [`bottom`](https://drafts.csswg.org/css-position-3/#propdef-bottom), but not in [`left`](https://drafts.csswg.org/css-position-3/#propdef-left) and [`right`](https://drafts.csswg.org/css-position-3/#propdef-right). Using wrong-axis keywords makes the function invalid.

But logical properties share the grammar and the computed value with the physical properties, so how does that work? All longhands in a logical property group must have the same grammar.

**Comment by tabatkins** [comment]
> All longhands in a logical property group must have the same grammar.

Hm, where does this requirement come from?

It's fine to change it (and just make the query invalid instead, so it doesn't match anything), but I just want to confirm that this is indeed an issue.

**Comment by Loirooriol** [comment]
Maybe "should" rather than "must"?

Logical and physical properties are paired and each pair shares a computed value. So if they have different grammars, then a property may end up with a computed value that can't be represented by its grammar. I guess it would be possible to serialize it as an empty string, but this would break libraries like html2pdf that iterate all computed values and expect them to work. I think it's a requirement that we should keep to have a sane behavior.

And OK some details can be different like physical properties accepting quirky lengths unlike logical properties, but this is just some aliasing at parse time. Or it might also be fine if the same computed value was represented in different ways by the logical and physical properties. But that's not the case for `anchor()`.

**Comment by tabatkins** [comment]
That's fair, I'll just make it turn the query invalid.

**Comment by tabatkins** [comment]
Done, but I accidentally transposed some digits when referring to this issue. Commit is 6533e07d5

Please let me know if there's anything else you think needs to be done.

**Comment by Loirooriol** [comment]
LGTM
