### ISSUE TITLE
[css-nesting-1] Allow relative selector syntax in `@nest` rules.

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#7854]
This is an alternative proposal to : https://github.com/w3c/csswg-drafts/issues/7834

It only focusses on a single part of the issues brought up there:

> selectors within nested context are incompatible with those outside of nested context, and with syntax within `@scope`, which invites a lot of copy-paste errors when transferring code among these contexts

------

Only nested selectors with a single `&` and if the `&` is located at the start of the selector could currently match elements outside of a nesting context. (correct me if I am wrong)

Can work in different contexts :

- `&.foo`
- `& .foo`
- `& + .foo`
- `& .foo + .bar`
- ...

I am unsure about these :

- `.foo&`
- `.foo &`

These will likely not match anything :

- `& + &`
- `& + .bar ~ &`

What makes sense to copy-paste is already a subset of all possible kinds of nesting selectors. So maybe this can be a "power feature" unlocked by using `@nest` in the current nesting syntax?

`@nest` already unlocks more features in todays nesting syntax.

```css
.foo {
  @nest .bar {
    /* & .bar */
    /* .foo .bar */
  }
}

/* copy-pasted to another context: */
.bar {
  /* :root .bar */
}
```

```css
.foo {
  @nest > .bar {
    /* & > .bar */
    /* .foo > .bar */
  }
}

/* copy-pasted to another context: */
> .bar {
  /* :root > .bar */
}
```

Also valid:

```css
.foo {
  @nest > .bar + & {
    /* & > .bar + & */
    /* .foo > .bar + .foo */
  }
}

/* copy-pasted to another context: */
> .bar + & {
  /* :root > .bar + :root */
  /* this would never match anything but it could be valid for the parser */
}
```

**Comment by FremyCompany** [comment]
FWIWI, if we go with option `1` or `3` in 7877, I would strongly support this change.

**Comment by fantasai** [comment]
@FremyCompany I think we should do this regardless of which option we choose. It's compatible with all of them.

**Comment by romainmenke** [comment]
@fantasai It is only compatible with option 1 as currently discussed.

All other options drop `@nest` completely. https://github.com/w3c/csswg-drafts/issues/7834#issuecomment-1283020374

**Comment by fantasai** [comment]
@romainmenke Yeah, so in option 3 you could just write

```
.foo {
  > .bar {
    /* & > .bar */
    /* .foo > .bar */
  }
}
```

and in option 4 it would be

.foo { } {
  > .bar {
    /* & > .bar */
    /* .foo > .bar */
  }
}
```

or

```
.foo && {
  > .bar {
    /* & > .bar */
    /* .foo > .bar */
  }
}
```

**Comment by romainmenke** [comment]
@fantasai This issues was specifically about adding relative selector syntax in `@nest` within proposal 1.

This as a way to have all the benefits of relative selector syntax without all the downsides of the other proposals.

**Comment by tabatkins** [comment]
Nesting spec now reflects this; retagging to Cascade 6 to track the remaining edits to `@scope`.

**Comment by johannesodland** [comment]
> <emeyer> astearns: Because of the weirdness about descendant selectors, should we define an actual optional syntax for descendant selectors in nest and @scope situations?
> <fantasai> s/allow ing/allowed to be written as relative selectors in/
> <Rossen_> ack astearns
> <emeyer> TabAtkins: I think we should but that should be a different discussion
> <emeyer> Rossen: Please open an issue on that if we don’t already have one, Alan?

Was there an existing issue on descendant selectors? 
Are you considering an explicit [`>>` descendant syntax](https://github.com/w3c/csswg-drafts/issues/641) to be able to do something like this?

```css
.a { >> .b .c { }}
/* .a .b .c { } */

/* As compared to */
.a { .b .c { }}
/* .a :is(.b .c) { } */

```

**Comment by romainmenke** [comment]
@tabatkins This issue was specifically about the now removed proposal 1.

It was very specifically about :

```css
.foo {
  @nest > .bar {
    /* & > .bar */
    /* .foo > .bar */
  }
}
```

Maybe it will be less confusing to open a new issue?

**Comment by tabatkins** [comment]
No, we chose to reinterpret this as a general referendum on relative selectors in places where we allow nesting. Check the minutes of the discussion.

**Comment by mirisuzanne** [comment]
The details of we spec this in `@scope` depends on the resolution of https://github.com/w3c/csswg-drafts/issues/8377 - documenting so these edits can happen together.
