### ISSUE TITLE
[css-shared-element-transitions-1] Define transitions over changing viewport

### ISSUE THREAD

**Issue by bokand** [w3c/csswg-drafts#7859]
Due to various browser UI, a transition can take place where the source and destination pages have a different size initial-containing-block and fixed/layout viewport. Some examples of UI widgets that cause this:

- Mobile URL bar (and related hide-on-scroll browser bars)
- Virtual Keyboard
- Desktop browser scrollbars

For example, most mobile browsers will force a hidden URL bar to be shown when a cross-document navigation occurs. In the other direction, a showing virtual-keyboard will be hidden when a navigation occurs. We should define exactly how transitioning elements are captured, sized, and positioned in these cases to ensure a seamless transition between the two states (i.e. elements should not "jump"). Here's what we're currently implementing which we can use as a starting point for spec text, thoughts welcome.

### Snapshot Viewport

We define the concept of the "snapshot viewport". This is a rect that is a consistent size and position regardless of what UI is currently shown. For example, on mobile browsers, the snapshot viewport overlays any shown UI like the URL bar and virtual keyboard:

![The snapshot viewport overlaying UI in a mobile browser](https://cdn.glitch.global/e61d77ef-db24-481a-87dc-f282612eb078/SET%20-%20Snapshot%20Viewport%20(1).png?v=1665177867435)

On desktop browsers, a common UI widget requiring attention is scrollbars (in particular, left-side vertical scrollbars in RTL writing modes since it shifts the content origin). The snapshot viewport is overlays and fills the full content area:

![The snapshot viewport underlaying scrollbars in a desktop browser](https://cdn.glitch.global/e61d77ef-db24-481a-87dc-f282612eb078/SET%20-%20Snapshot%20Viewport%20Scrollbar%20(1).png?v=1665178343787)

### Positioning

The snapshot viewport serves as the common coordinate space in which transitions take place. Since each shared element's transition is [positioned by its `::page-transition-container`](https://drafts.csswg.org/css-view-transitions-1/#selectordef-page-transition-container-pt-tag-selector), and this element is positioned absolutely within the `::page-transition`, we make `::page-transition` match the snapshot viewport rect:

```CSS
html::page-transition {
  position: fixed;

  /* Dynamically generated based on whether UI is showing or not. */
  left: -15px; /* left-side vertical scrollbar */
  top: -56px; /* mobile URL bar */
  width: 412px;
  height: 1000px;
}
```

When capturing a shared element's "screen space position", use the position relative to the snapshot viewport:

![A shared element's position is captured relative to the snapshot viewport](https://cdn.glitch.global/e61d77ef-db24-481a-87dc-f282612eb078/SET%20-%20Snapshot%20Viewport%20Translate.png?v=1665180555347)

### Root snapshot

To avoid the root snapshot moving or scaling its snapshot is sized to match the snapshot viewport. The page's content is captured at its location within the snapshot viewport and regions of the snapshot covered by browser UI are rendered with the background color (or real page content, if available).

![Content is rendered into the root snapshot at its snapshot viewport location](https://cdn.glitch.global/e61d77ef-db24-481a-87dc-f282612eb078/SET%20-%20Snapshot%20Viewport%20Root.png?v=1665181103842)

**Comment by khushalsagar** [comment]
This LGTM. I'm hoping the spec text can lean on ongoing work for viewport sizes, particularly [large viewport size](https://drafts.csswg.org/css-values-4/#large-viewport-size). @bramus FYI.

**Comment by bramus** [comment]
+1 on using _“snapshot rect”_ as per https://github.com/web-platform-tests/interop-2022-viewport/issues/27#issuecomment-1284471841

**Comment by khushalsagar** [comment]
Here is the short **proposed resolution**:  Use "snapshot viewport" for root element snapshot and UA CSS to size and position [::page-transition](https://drafts.csswg.org/css-view-transitions-1/#selectordef-page-transition) at snapshot viewport.

**Comment by jakearchibald** [comment]
I created a series of examples here https://static-misc-3.glitch.me/set-viewport-examples/ to show how default transitions would handle these browser elements appearing/disappearing.
