### ISSUE TITLE
[css-ruby-1] Change 'collapse' to 'merge' for ruby-merge

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#786]
https://drafts.csswg.org/css-ruby-1/#collapsed-ruby
4.2 Sharing Annotation Space: the ruby-merge property 

I think that a better name for the `collapse` value would be `merge`, ie. ruby-merge: merge; The meaning of `collapse` is not as obvious as `merge`, to my mind.

**Comment by patrickdark** [comment]
Sounds like a good idea. I'm guessing the value is modeled on `border-collapse: collapse`, but in that case the property name and value match.

**Comment by frivoal** [comment]
This issue got duplicated as https://github.com/w3c/csswg-drafts/issues/5004, and was resolved there. Closing.
