### ISSUE TITLE
[css-fonts] Remove `font-variant` descriptor example

### ISSUE THREAD

**Issue by meyerweb** [w3c/csswg-drafts#7864]
In https://github.com/w3c/csswg-drafts/commit/d3db8697852a6ccc1c8dafcb4aff1f516198bb50, the `font-variant` descriptor of the `@font-face` rule was dropped, resolving https://github.com/w3c/csswg-drafts/issues/2531.

Despite this, the latest draft still has an example (https://w3c.github.io/csswg-drafts/css-fonts-4/#ex-descriptor-only-that-rule) specifically about this descriptor.  It should be removed.

**Comment by estelle** [comment]
https://github.com/w3c/csswg-drafts/pull/7863
