### ISSUE TITLE
[css-cascade] Build fails because of the CanIUse label in `inherit`

### ISSUE THREAD

**Issue by andreubotella** [w3c/csswg-drafts#7865]
Since 9b95cab15a325abb5934590e85c830811ba1ba70, building any level of `css-cascade` with bikeshed fails, even with `--force`, because apparently Bikeshed does not recognize the `mdn-api_csspropertyrule_inherits` CanIUse label on the `inherit` keyword. Note that this label is wrong because it refers to the property `inherits` in `CSSPropertyRule` – it should probably be `mdn-css_types_global_keywords_inherit`, but that label also causes the build to fail.

And since the w3c.github.io build will fail on encountering any error code from the Bikeshed build, the mirror is not being updated at all, for any of the specs, after that commit. (Should this be changed?)

cc @fantasai @tabatkins

**Comment by tabatkins** [comment]
The breakage was actually a Bikeshed bug - I wasn't properly bailing when I saw a missing caniuse value, so it bulled forward into a full Python error shortly after, which crashes the entire script. That's fixed now.

I think an actual Python error causing the script to fail is a good thing - those should never occur, so when they do, me being informed of it by the script falling over is a good thing. ^_^ Plain Fatal Errors indeed shouldn't be a problem, and that's already handled by bikeshed being invoked with `-f` by the script.
