### ISSUE TITLE
[css-view-transitions-1] content-visibility: auto elements are relevant to the user during a transition

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7874]
`content-visibility: auto` allows the user agent to minimize the rendering cost for elements which are not [relevant to the user](https://w3c.github.io/csswg-drafts/css-contain-2/#relevant-to-the-user). There are multiple subtle interactions this optimization has with View transitions.

1. Identifying elements with a valid `page-transition-tag` (and other constraints) requires all elements to have up to date style (see logic [here](https://drafts.csswg.org/css-view-transitions-1/#perform-an-outgoing-capture:~:text=associated%20document.-,For%20each%20element%20of%20every%20Element%20and%20pseudo%2Delement%20connected%20to%20document,-%2C%20in%20%5Bpaint%20order)). Offscreen elements can also participate in a transition since the transition might bring them onscreen. So `content-visibility: auto` shouldn't prevent discovery of a tagged element.
 
   The default behaviour would be for the transition to force style update for the whole DOM tree to discover tagged elements. We can add an option going forward (new `contain` keyword?) for the author to indicate that a sub-tree doesn't have tagged elements.

2. If an element with `content-visibility: auto` is tagged, it becomes relevant to the user.

3. If an element with `content-visibility: auto` has a descendant which is tagged, the element becomes relevant to the user. This is because we need to layout/paint the tagged element to render it in its corresponding replaced pseudo-element.

4. If an element with `content-visibility: auto` has an ancestor which is tagged then we have 2 cases:
    * If that ancestor is the root element then `content-visibilty: auto` can continue to apply. This is because the root snapshot is clipped to the viewport. See #7859 for details.
    * If that ancestor is a non-root element then the `content-visibility: auto` node becomes relevant to the user. This is because snapshots for non-root elements are painted in their entirety (modulo hardware constraints).

@vmpstr to validate the summary.

**Comment by khushalsagar** [comment]
We had an offline discussion about this, summarized below. There are 2 different points to resolve for this issue:

1. If an element is participating in a transition, any element in its sub-tree (which has c-v: auto) should become relevant to the user. This makes sense given that the tagged element will be painted into a snapshot. This snapshot's position and scale is animated during the transition (by the pseudo-element its drawn in). So all its content (including the c-v: auto elements) could be in the viewport.

   Given that the snapshot for all non-root elements paints the entire DOM tree underneath, it'll make all c-v: auto elements underneath a non-root tagged element relevant to the user. It's only the root (for which the snapshot is clipped) which can have c-v: auto elements underneath that are clipped out of the snapshot and hence don't need to be made relevant to the user.

   **Proposed Resolution**: An element with `content-visibility: auto` is relevant to the user if it is painted into self or an ancestor's snapshot during a transition.

2. Deciding which elements participate in a transition requires resolving style on all DOM elements so the computed value of `page-transition-tag` property is known. This forces resolving at least style for elements with `c-v: auto`. That defeats the purpose of the optimization. There are 2 choices:

   - By default force style resolution on the whole DOM to find all tagged elements so `c-v: auto` doesn't influence whether a tag works. The developer will have no way to retain the optimization beyond temporarily adding `content-visibility: hidden` if they don't need tags under a DOM subtree to be discovered. We could add a `contain: view-transition` for the developer to directly express that intent.
   
   - Elements under a `c-v: auto` element which is not already relevant to the user can't participate in a transition. "Relevant to the user" can be different across browsers since [margin around viewport is user-agent defined](https://w3c.github.io/csswg-drafts/css-contain/#content-visibility:~:text=The%20element%20is%20%22on%2Dscreen%22%3A%20its%20paint%20containment%20box%27s%20overflow%20clip%20edge%20intersects%20with%20the%20viewport%2C%20or%20a%20user%2Dagent%20defined%20margin%20around%20the%20viewport.).  If the developer wants elements to always be discovered they can switch to `c-v: visible` for the transition.

   **Proposed Resolution**: When traversing the DOM to discover tagged elements only visit elements relevant to the user. Updates step 4 [here](https://drafts.csswg.org/css-view-transitions-1/#perform-an-outgoing-capture:~:text=associated%20document.-,For%20each%20element%20of%20every%20Element%20and%20pseudo%2Delement%20connected%20to%20document%2C%20in%20%5Bpaint%20order%5D(https%3A//drafts.csswg.org/css2/%23painting%2Dorder)%3A,-The%20link%20for) and [here](https://drafts.csswg.org/css-view-transitions-1/#ref-for-create-transition-pseudo-elements%E2%91%A0:~:text=new%20set.-,For%20each%20element%20of%20every%20Element%20and%20pseudo%2Delement%20connected%20to%20document%2C%20in%20%5Bpaint%20order%5D(https%3A//drafts.csswg.org/css2/%23painting%2Dorder),-%3A) changes to "For each element and pseudo-element connected to document and relevant to the user".

**Comment by jakearchibald** [comment]
What happens if you call `getBoundingClientRect` on an element within a hidden `content-visibility: auto` region?

If that gives a result as if the element is not-rendered, then I think View Transitions should also treat the element as not-rendered.

**Comment by khushalsagar** [comment]
`getBoundingClientRect` is fine for the element with `content-visibility: auto` since that element has been styled/laid out. But if you call it for one of its descendants, it forces a style/layout and causes the browser to do work it had optimized out.

**Comment by jakearchibald** [comment]
IMO, when you use `content-visibility`, you opt-in to the feature controlling the render-or-not of particular elements, so I don't think it's an issue that these elements aren't seen by view transitions. Triggering a potentially large layout in the middle of a page switch is definitely a bad thing. I'm still kinda surprised that `content-visibility` de-opts when querying particular layout info. I don't think it should do that, but I guess that's an issue for somewhere else.

We talked about another feature elsewhere https://github.com/WICG/view-transitions/issues/84, that changed the behaviour of elements outside the viewport. If you opt-in to treating outside-viewport elements as "not rendered", then you avoid the heuristic behaviour of `content-visibility`.

Thinking it through, I still think we have the right default - transition things from their original position. That works well for most use-cases.

It doesn't work well for cases like a header transition. If the header can be scrolled away 1000s of pixels, having it transition back to the top is a bad transition. You can work around this with JS pretty easily by tagging the header dynamically if it's in the viewport, but a high-level way of doing that seems reasonable, but I don't think we need it for MVP.

If a grid of items is transitioning in a way that makes them shorter, that may result in additional rows entering the viewport. In this case you really want them to animate from their original positions, even though they were outside the viewport.
