### ISSUE TITLE
[css-2023] Start on CSS Snapshot 2023

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#7883]
We are in the fourth quarter of 2022, so I think we should slowly start talking about the changes necessary to finish up the CSS Snapshot 2022.

Regarding the stability levels, the [current list](https://www.w3.org/Style/CSS/current-work.en.html) doesn't differ much from [the one at the end of last year](https://web.archive.org/web/20211228114806/https://www.w3.org/Style/CSS/current-work.en.html).
There are three specs, though, which made a big leap forward, from (FP)WD to CR:

* [CSS Color Adjustment Level 1](https://www.w3.org/TR/css-color-adjust-1/)
* [CSS Conditional Rules Level 4](https://www.w3.org/TR/css-conditional-4/)
* [CSS Cascading and Inheritance Level 5](https://www.w3.org/TR/css-cascade-5/)

The first one is already part of CSS 2022, the other two should probably be considered.

Also, many of the specs covered by the [Interop 2022](https://wpt.fyi/interop-2022) project can probably be moved to the "Rough Interoperability" section. One of them is definitely CSS Scroll Snap 1, for example.

The goal of this issue is to summarize the things that need to be changed so that the CSS Snapshot 2022 can be published.

Sebastian

**Comment by svgeesus** [comment]
```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/csswg-drafts/css-2022$ bikeshed -f spec
WARNING: Multiple elements have the same ID 'css'.
Deduping, but this ID may not be stable across revisions.
LINE ~363: Couldn't find target document section css:
[[#css|official definition of CSS]]
LINE ~451: Couldn't find target document section css:
[[#css|official definition of CSS]]
 ✔  Successfully generated, but fatal errors were suppressed
```

However I'm only finding one such id in the .bs, the other must be autogenerated:

```html

<h3 id="css">Cascading Style Sheets (CSS) &mdash; The Official Definition</h3>
```

aha the other one is

> 1.1. What is CSS?

> Cascading Style Sheets (CSS)

**Comment by SebastianZ** [comment]
@svgeesus What about the suggested additions above? Should we discuss them on the next call?

Sebastian

**Comment by svgeesus** [comment]
It's a bit late, publication is [already underway](https://github.com/w3c/transitions/issues/471) and [happened today](https://www.w3.org/TR/2022/DNOTE-css-2022-20221122/)

**Comment by astearns** [comment]
We resolved to update the snapshot as needed instead of publishing only once a year, so these changes could still be discussed and added for 2022. Or they could form the basis for an early 2023 update.

**Comment by SebastianZ** [comment]
Fine, so I've set Agenda+ so we can talk about that. And yes, I saw that it got published and that any changes need to be discussed afterwards.

Sebastian

**Comment by astearns** [comment]
Unfortunately we have had higher-priority issues that have pushed this back. Let’s take this up as a 2023 update next month.

**Comment by svgeesus** [comment]
The title of this issue is suggestive, and the issue was closed by accepting the edits, but we don't actually have a WG resolution to clear Relative Color Syntax to ship.

 - https://github.com/w3c/csswg-drafts/issues/7978

Agenda+ to resolve this and to discuss the proposed updates from @SebastianZ

**Comment by svgeesus** [comment]
Some _suggested_ resolutions to discuss on the call:

## Cleared to ship, but not added to snapshot

- Resolved: add [Relative Color Syntax](https://w3c.github.io/csswg-drafts/css-color-5/#relative-colors) from CSS Color 5 to [Safe to Release pre-CR Exceptions](https://www.w3.org/TR/2022/DNOTE-css-2022-20221122/#CR-exceptions)

## Moved to CR in last year

- Resolved: add [CSS Conditional Rules Module Level 4](https://w3c.github.io/csswg-drafts/css-conditional-4/) to [Modules with Rough Interoperability](https://www.w3.org/TR/2022/DNOTE-css-2022-20221122/#rough-interop)

- Resolved: add [CSS Cascading and Inheritance Level 5](https://w3c.github.io/csswg-drafts/css-cascade-5/) to [Modules with Rough Interoperability](https://www.w3.org/TR/2022/DNOTE-css-2022-20221122/#rough-interop) for Cascade Layers

## from [Interop 2022](https://wpt.fyi/interop-2022)

Which ones do people suggest adding, or promoting?

**Comment by svgeesus** [comment]
[CSS-2023 spec created](https://w3c.github.io/csswg-drafts/css-2023/) as copy of CSS-2022.

Resolutions now all edited in.

**Comment by svgeesus** [comment]
[First Note transition requested](https://github.com/w3c/transitions/issues/485)

**Comment by svgeesus** [comment]
Publication request sent 8 Feb, expected Tue 14 Feb.

**Comment by svgeesus** [comment]
[Published 14 Feb 2023](https://www.w3.org/TR/2023/DNOTE-css-2023-20230214/)
