### ISSUE TITLE
[css-color-5] Typo in serialization examples

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#7892]
According to the [color serialization rules in css-color-4](https://drafts.csswg.org/css-color-4/#serializing-color-values), all channels are serialized as numbers (without units), even when those numbers represent [percentages or degrees](https://drafts.csswg.org/css-color-4/#serializing-lab-lch).

However, many of the examples in [css-color-5](https://drafts.csswg.org/css-color-5/#serial) maintain `%` units on eg lightness channels. I imagine that's a typo?

**Comment by svgeesus** [comment]
It wasn't a typo when the example was created. But yes, needs to be updated.
