### ISSUE TITLE
[css-fonts] @font-face doesn't accept individual font-variant-* descriptors

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#790]
https://drafts.csswg.org/css-fonts/#font-rend-desc

the @font-face block accepts the `font-variant` shorthand descriptor, but not the individual `font-variant-*` descriptors. It would be convenient for web authors to be able to specify either of them inside an @font-face block.

**Comment by svgeesus** [comment]
Yes, it would.

**Comment by Crissov** [comment]
… for some of them.

**Comment by svgeesus** [comment]
Given that current implementations don't accept the longhand descriptors being proposed, I think this should be pushed to css fonts 4

**Comment by litherum** [comment]
Sure. 😢

**Comment by fantasai** [comment]
Reopening since this was pushed to css-fonts-4, and we're working on css-fonts-4...

**Comment by svgeesus** [comment]
OK so this just requires:

- adding the individual descriptors
- defining priority if the shorthand and longhand descriptors are both used
- expressions of implementer interest
