### ISSUE TITLE
[css-anchor] anchor-name on elements without a principal box

### ISSUE THREAD

**Issue by lilles** [w3c/csswg-drafts#7914]
The spec says anchor-name applies to all elements. Additionally, [determining the anchor element](https://drafts.csswg.org/css-anchor-1/#target-anchor-element) does not say anything about the element having a box either.

Should the spec say that it applies to elements generating a principal box?

**Comment by tabatkins** [comment]
Sounds good, yeah.

**Comment by tabatkins** [comment]
Done. Assuming satisfied, as this seems to be an obvious bugfix.
