### ISSUE TITLE
[css-flexbox] editorial: typo in Flex Container cross-axis baseline set

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#792]
https://drafts.csswg.org/css-flexbox/#flex-baselines
In the definition of "first/last _cross-axis_ baseline set", bullet 2 says:
> Otherwise, the flex container has no first/last main-axis baseline set, ...

I think "main-axis" should be "cross-axis" there.

**Comment by fantasai** [comment]
Fixed, thanks!
