### ISSUE TITLE
Powerless a,b and chroma for Lightness >= 100%

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#7924]
In a somewhat handwavy piece of spec text that was intended to provide an escape hatch for HDR, we have, for [CIE Lab](http://w3c.github.io/csswg-drafts/css-color-4/#specifying-lab-lch)

> If the lightness of a Lab color is 0%, both the a and b components are [powerless](http://w3c.github.io/csswg-drafts/css-color-4/#powerless-color-component).

and for [Oklab](http://w3c.github.io/csswg-drafts/css-color-4/#specifying-oklab-oklch)

> If the lightness of an Oklab color is 0%, both the a and b components are [powerless](http://w3c.github.io/csswg-drafts/css-color-4/#powerless-color-component).

In the midst of a [long discussion about powerless components, `none` and `NaN`](https://github.com/w3c/csswg-drafts/issues/6107), @tabatkins [wrote](https://github.com/w3c/csswg-drafts/issues/6107#issuecomment-834785792):

> Just black and white. Those colors are singularities for chroma (all chroma values return the same color), while the rest of the neutral axis does have the color change as chroma changes.

I'm wondering it it would be better to also say (as @tabatkins seems to be suggesting, in that older thread) that 

a) Lightness of 100% clamps to 100% 
b) If the lightness of a Lab color is 100%, both the a and b components are [powerless](http://w3c.github.io/csswg-drafts/css-color-4/#powerless-color-component).

Oklab was defined by the author to be specifically SDR; and although Lab has been experimentally extended by Fairchild to L=400, he gave that a different name (`hdr-CIELAB`) and it didn't really catch on. In practice, HDR colors are likely to be specified in `rec-2100-hlg` or `rec-2100-pq`.

**Comment by tabatkins** [comment]
Yeah, the L=400 thing is the only reason I didn't immediately just say that L=100 meant powerless, as I wasn't sure if the components *were* supposed to be able to alter the color above that level.  If Lab is meant to clamp to 100, then we should do that explicitly, and say chroma is powerless there.

**Comment by svgeesus** [comment]
Crucially, the L axis in hdr-CIELAB uses a modified equation compared to CIE Lab:

![image](https://user-images.githubusercontent.com/2506926/197002336-6433d075-c14a-43ed-93a1-90a264c5ac60.png)

It isn't just "extending the range to 400".

The above is equation 23 from 

M.D. Fairchild and P.-H. Chen, "Brightness, lightness, and specifying color in high-dynamic-range scenes and images," _SPIE/IS&T Electronic Imaging Conference,_ San Francisco, 78670O-1 -78670O-14 (2011). [full text PDF](http://markfairchild.org/PDFs/PRO37.pdf)
