### ISSUE TITLE
[css-fonts] Missing serialisation for 0 ranged descriptors inside @font-face

### ISSUE THREAD

**Issue by tursunova** [w3c/csswg-drafts#7925]
In the [spec](https://www.w3.org/TR/css-fonts-4/#font-prop-desc) there is no specification on whether 0 ranged `font-stretch`, `font-style` and `font-weight` descriptors inside `@font-face` rule should be simplified or not. E.g., if `font-weight: 200 200;` is specified inside `@font-face` then it's not clear on whether `rule.style.getPropertyValue("font-weight")` should return `200` or `200 200`. Chrome and Safari are currently returning `200 200` while Firefox is returning just `200`.

The issue was also discussed in the conversation in [WPT PR #36489 ](https://github.com/web-platform-tests/wpt/pull/36489)

**Comment by tursunova** [comment]
Since there is a general rule to serialize things in a simpler form in [spec](https://w3c.github.io/csswg-drafts/cssom/#serializing-css-values):

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

I'm proposing to simplify 0 ranged descriptors inside `@font-face` rule as well.

**Comment by svgeesus** [comment]
That makes sense to me.

**Comment by svgeesus** [comment]
@tursunova sorry for the delay; I added Agenda+ a while ago but we have a backlog, more items to discuss than we can cover in a week.

**Comment by tursunova** [comment]
@svgeesus no worries, thank you for adding Agenda+

**Comment by fantasai** [comment]
@svgeesus I think you can just accept this under Editor Discretion, since it's just a corollary of the serialization principles.
