### ISSUE TITLE
[cssom-view] Should scrollend fire when a scroll hits the end of a scroll container

### ISSUE THREAD

**Issue by dlrobertson** [w3c/csswg-drafts#7927]
[§ 3.1. Scrolling](https://drafts.csswg.org/cssom-view/#scrolling) states:

> Once the position has finished updating, emit the [scrollend](https://drafts.csswg.org/cssom-view/#eventdef-document-scrollend) event.

and [§ 13.2. Scrolling](https://drafts.csswg.org/cssom-view/#scrolling-events) states:

A scrollend event target is added to the Documents [pending-scrollend-event-targets](https://drafts.csswg.org/cssom-view/#document-pending-scrollend-event-targets) on [scroll completed](https://drafts.csswg.org/cssom-view/#scroll-completed), which is defined as:

> Scroll is completed when the scroll position has no more pending updates or translations and the user has completed their gesture.

It is not entirely clear to me what should occur when no more scrolling or translations can occur in the direction of the users scroll direction. For example, (based on my reading of the spec) a scroll container with `overscroll-behavior: none` and a pan gesture that hits the boundary should trigger a scrollend when the gesture completes (once the user lifts their fingers) and the boundary has been hit. I tested this on chromes implementation of scrollend with this example https://dlrobertson.com/examples/scrollend-event.html, and it appears that the scrollend is delayed. Do we include the momentum phase of a pan gesture in the definition of a "user gesture"? Also, should a scrollend be fired for a user scroll for which no scroll can occur?

Feedback on additional info that is nice to have when raising spec questions would be greatly appreciated 😄

**Comment by dlrobertson** [comment]
The wpt test [dom/events/scrolling/scrollend-event-fired-to-element-with-overscroll-behavior.html](https://github.com/web-platform-tests/wpt/blob/master/dom/events/scrolling/scrollend-event-fired-to-element-with-overscroll-behavior.html#L84-L89) seems to conflict with https://github.com/w3c/csswg-drafts/commit/669f10d4e67bf5de31a721f27c78436492142e34. AFAIK no translations are applied and no scrolling occurs due to `overscroll-behavior-y: none`, but the test expects a `scrollend` event to occur.

CC @argyleink

**Comment by argyleink** [comment]
> AFAIK no translations are applied and no scrolling occurs due to `overscroll-behavior-y: none`

confirmed, that test needs an update 👍🏻

**Comment by dlrobertson** [comment]
Test change is posted [here](https://github.com/web-platform-tests/wpt/pull/36681)

**Comment by dlrobertson** [comment]
This can be closed now that https://github.com/web-platform-tests/wpt/pull/36681 was merged.
