### ISSUE TITLE
[css-anchor] Anchor sizes and box sizing

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#7938]
[`<anchor-size>`](<https://drafts.csswg.org/css-anchor-1/#typedef-anchor-size>) = `width | height | block | inline | self-block | self-inline`

Do these dimensions respect the value of the `box-sizing` property or do they always use the border box of the target anchor element?

**Comment by tabatkins** [comment]
D'oh, this is underspecified. It should be the border box.
