### ISSUE TITLE
[mediaqueries-4] change `infinite` in `resolution` descriptor to `infinity` to match css-values

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#7939]
https://www.w3.org/TR/mediaqueries-4/#resolution

```css
@media (min-resolution: infinite) {}

@media (resolution = infinite) {}

@media (infinite = resolution) {}

@media (resolution < infinite) {}

@media (infinite > resolution) {}
```

As far as I know this is currently the only current media description that has a range type while also accepting an `<ident>` value (`infinite`).

_I am assuming that the syntactical ambiguity is ok because browsers would have lists of known media descriptors._

In `css-values` the numeric constant `infinity` is defined.
Should this same constant be used here?

`infinite` -> `infinity`

In a range context this seems more intuitive :

```css
@media (resolution = infinity) {}

@media (infinity = resolution) {}

@media (resolution < infinity) {}

@media (infinity > resolution) {}
```

------

Maybe this is a moot point since `infinity` is a numerical constant so should be allowed anyway with `calc`.

```css
@media (resolution = calc(infinity)) {}

@media (calc(infinity) = resolution) {}

@media (resolution < calc(infinity)) {}

@media (calc(infinity) > resolution) {}
```

**Comment by romainmenke** [comment]
nvm, `infinite` aligns with the keyword used in transitions so also has a precedent.

**Comment by tabatkins** [comment]
Yeah, we ended up with the property-specific keyword form being "infinite", but it felt weird to have `infinite` be a numeric keyword for calc().

**Comment by Loirooriol** [comment]
Note that with `calc` you would need something like `calc(infinity * 1dppx)` in order to get a `<resolution>`, and this won't be the same as `infinite` as noted in https://drafts.csswg.org/css-values-4/#calc-range

> Even properties that can explicitly represent infinity as a keyword value, such as [animation-iteration-count](https://drafts.csswg.org/css-animations-1/#propdef-animation-iteration-count), will end up clamping ±∞, as [math functions](https://drafts.csswg.org/css-values-4/#math-function) can’t resolve to keyword values; the numeric part of the property’s syntax still has a minimum/maximum value.

**Comment by romainmenke** [comment]
relevant : https://github.com/w3c/csswg-drafts/issues/8998
