### ISSUE TITLE
[cssom-view] migration of the scrollend event did not include onscrollend

### ISSUE THREAD

**Issue by dlrobertson** [w3c/csswg-drafts#7949]
The migration of `scrollend` from [WICG/overscroll-scrollend-events](https://github.com/WICG/overscroll-scrollend-events), did not include the `onscrollend` event handler from [Extensions to the `GlobalEventHandlers` interface](https://wicg.github.io/overscroll-scrollend-events/#extensions-to-the-globaleventhandlers-interface). Similar to [onscroll](https://drafts.csswg.org/cssom-view/#dom-visualviewport-onscroll), I believe the `onscrollend` should be the [event handler IDL attribute](https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-idl-attributes) for the [scrollend](https://drafts.csswg.org/cssom-view/#eventdef-document-scrollend) event.

**Comment by dlrobertson** [comment]
CC: @argyleink

**Comment by argyleink** [comment]
nice, thanks for the callout! will work on an update

**Comment by dlrobertson** [comment]
Tests for the event handler content attributes exist in https://github.com/web-platform-tests/wpt/pull/36688

**Comment by dlrobertson** [comment]
This can be closed now that whatwg/html#8433 is merged.
