### ISSUE TITLE
[css-view-transitions-1] CSS selector keywords.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#7960]
Forking this from #7788 to resolve on the exact keywords used in the selector.

1. Property used on DOM elements to tag them for independent animations: `view-transition-name`.

2. The pseudo-element which directly originates from the root element and is the ancestor for all container elements. Options are:
   1. `html::view-transition`
   2. `html::view-transition-root`
   **Proposed Resolution**: `html::view-transition`

3. The pseudo-element which animates the size and position for tagged elements. Options are:
   1. `html::view-transition-container(*)`
   2. `html::view-transition-group(*)`
   **Proposed Resolution**: `html::view-transition-group(*)`

4. The pseudo-element which adds `isolation` for blending. Options are:
   1. `html::view-transition-image-group(*)`
   2. `html::view-transition-pair(*)`
   4. `html::view-transition-effect-group(*)`
   5. `html::view-transition-images(*)`
   6. `html::view-transition-set(*)`
   7. `html::view-transition-image-set(*)`
   8. `html::view-transition-image-pair(*)`

5. The pseudo-element which displays snapshot from the old DOM element. Options are:
   1. `html::view-transition-old(*)`
   **Proposed Resolution**: `html::view-transition-old(*)`

6. The pseudo-element which displays snapshot from the new DOM element. Options are:
   1. `html::view-transition-new(*)`
   **Proposed Resolution**: `html::view-transition-new(*)`

Please comment in case I missed an existing suggestion from #7788 or if you have any other suggestions.
* 1, 5 and 6 have only option which is the proposed resolution.
* 2 has a couple of options but I think we converged on (2.i) so I added that as the proposed resolution.
* 3, 4 need consensus.

Pasting fantasai's [comment](https://github.com/w3c/csswg-drafts/issues/7788#issuecomment-1292315046) on 3,4:

- changing `::view-transition-image-group` to `::view-transition-pair` because it's shorter (and not a hyphenated phrase) and avoids evoking the idea of groups in SVG, which it's not conceptually similar to
- changing `::view-transition-container` to `::view-transition-group` because it's shorter and evokes the idea of groups in SVG (which create hierarchy in the graphic elements)

The downside of using "pair" is that it'll make it awkward if a future change needs a pseudo-element other than old/new under this element. It's not a pair anymore then. ^_^ But no hard preference there, we don't forsee anything that would add more pseudo-elements under this node right now.

I also didn't follow why the the element adding `isolation` isn't conceptually similar to SVG groups but the one which mirrors size/position of the DOM element is. @fantasai could you clarify?

Regarding shorter names, the motivation to use `view-transition-image-group`/`view-transition-image-pair` instead of `view-transition-group`/`view-transition-pair` would be that the latter sounds similar to `view-transition-container`. The "image" keyword there makes it obvious that it's a pair of replaced elements. We could go with `view-transition-image-pair` instead of `view-transition-image-group`.

**Comment by vmpstr** [comment]
Here's my 2c:

* Root: `::view-transition` if fine, since adding `root` is unnecessarily verbose
* Container: Either `container` or `group` is ok with me, but I like the fact that `group` is shorter and easier to type, so that would be my vote
* Wrapper: I still think that we may need a qualifying word like `image` or `effect` in this name, since `view-transition-set`, for example, is too close to `view-transition-group` to not be confusing. `pair` is also a misnomer in some cases, since exit and enter animations would only have one constituent image. I like `view-transition-image-set` or `view-transition-image-list`, since `set` gives me an impression that order doesn't matter. So my vote is for `view-transition-image-list`.
* Old: `view-transition-old` is fine.
* New: `view-transition-new` is fine.

**Comment by fantasai** [comment]
> I also didn't follow why the the element adding isolation isn't conceptually similar to SVG groups but the one which mirrors size/position of the DOM element is. @fantasai could you clarify?

In your extended proposal, this is the element that creates hierarchy, right? That's exactly what groups do in SVG.

> my vote is for view-transition-image-list.

“list” has a very strong implication of “one or more, and probably many of an indeterminate number”, I think. Doesn't seem like a good fit for what is, afaict, only ever going to be two images (one of which might be empty)?

> The downside of using "pair" is that it'll make it awkward if a future change needs a pseudo-element other than old/new under this element. It's not a pair anymore then. ^_^

Are you thinking there will be *three* images in some future revision? @_@

**Comment by khushalsagar** [comment]
> In your extended proposal, this is the element that creates hierarchy, right? That's exactly what groups do in SVG.

By extended proposal I think you mean [Nested transition containers](https://github.com/WICG/view-transitions/blob/main/explainer.md#nested-transition-containers). And yes, this will be the element which will have other container/group elements as children with that proposal.

> Doesn't seem like a good fit for what is, afaict, only ever going to be two images (one of which might be empty)?

With the current API it can be 1 or 2 images. 1 in the case where a `view-transition-name` exists only on the old or new DOM. In that case the other replaced element is not generated. This is different from it being empty since no node (and box in the box tree) will be created for it.

> Are you thinking there will be three images in some future revision? @_@

That comment was just to note a consideration for future flexibility. Given that we have no extension planned that could have more than 2 nodes, please disregard it. The only argument against `pair` (in the comments above) is that it's possible to have 1 replaced element under this element.

**Comment by fantasai** [comment]
> The only argument against pair (in the comments above) is that it's possible to have 1 replaced element under this element.

I think that's fine. It's not an empty image but we're still conceptually transitioning between old and new, it's just that there's no image for one of these. :) Anyway that's my take.

**Comment by khushalsagar** [comment]
Thanks for the feedback @fantasai.

- I don't see any opposition to picking `view-transition-group` for the node which animations size and position. Since this element will have other `view-transition-group` elements as children (with nested transitions) it also builds off a similar concept in SVG. Added that as the proposed resolution in the first comment.

- For the pseudo-element adding `isolation`, I don't see any opposition to using the pattern `view-transition-image-foo`. Having the word image disambiguates it from `view-transition-group` since it can only have 1 or 2 replaced elements as children. The options for foo here are `list`, `pair` or `set` and ideal would be something which indicates that there can be 1 or 2 children
   - `pair`: Con is the case where there is guaranteed to be only 1 child (enter/exit animations).
   - `set`: Con is that set makes it sound like the order of children doesn't matter but it does. Also not clear that there can't be more than 2.
   - `list`: Again, not clear that there can't be more than 2.
   
   I'd be ok with pair or list. @astearns @tabatkins any other suggestions?

**Comment by khushalsagar** [comment]
The spec already names this element as view-transition-image-pair so no edit needed.
