### ISSUE TITLE
[css-color-5] Nested relative colors

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7963]
[3. Relative Color Syntax](https://drafts.csswg.org/css-color-5/#relative-colors) does not define whether nested relative colors are allowed, eg. `hsl(from rgb(from var(--brand-yellow) calc(r - 100) g b) h calc(s - 10%) l)`, and I do not see any example of this in the spec.

Is it fine to assume that this is allowed and that you will later define a maximum of 32 level of nestings, like for math functions?

#3462 addressed maximum parentheses (function and simple block) nestings but only resolved on defining a minimum for calculations.

**Comment by svgeesus** [comment]
Ah, I see the problem. The RCS productions in CSS Color 5 are linking to the definition of `<color>` in CSS Color 4 (which does not include RCS).

Yes, if `<color>` includes `rgb()` and 

```css
rgb( [ from <color> ]? [ <number> | <percentage> | none]{3} 
     [ / [<alpha-value> | none] ]?  )
```

then nesting is possible (and intended). 

We haven't yet discussed a limit on the degree of nesting.

**Comment by LeaVerou** [comment]
Yeah, RCS, as well as things like `color-mix()` or `contrast-color()` all produce `<color>` values, so any `<color>` value could use them.

**Comment by svgeesus** [comment]
https://github.com/w3c/csswg-drafts/commit/c17a10ddc61f91d05c10fcffb63f0d29b86cad5f
