### ISSUE TITLE
[css-align] editorial: wrong links for 'dominant-baseline' and 'alignment-baseline' properties 

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#797]
https://drafts.csswg.org/css-align-3/#baseline-export
> 	(See the `dominant-baseline` and `alignment-baseline` properties in [CSS-INLINE-3].)

The links however points to the SVG spec:
https://www.w3.org/TR/SVG/text.html#DominantBaselineProperty
https://www.w3.org/TR/SVG/text.html#AlignmentBaselineProperty

I think they should link to:
https://drafts.csswg.org/css-inline/#dominant-baseline-property
https://drafts.csswg.org/css-inline/#alignment-baseline-property

BTW, shouldn't all outgoing links in a draft spec point to other draft specs?
And only "freeze" the outgoing links to TR specs once the spec itself is TR?
(As an implementor, I rarely want to see anything but the latest information,
which is in the draft specs, so it's a bit annoying to be led astray when
clicking links to other specs.)

**Comment by MatsPalmgren** [comment]
https://drafts.csswg.org/css-align-3/#align-by-baseline
> (e.g. via the `alignment-baseline` property),

The `alignment-baseline` link there is wrong too, so it's probably worth checking the entire document.

**Comment by fantasai** [comment]
I'm not sure what's going on here. Assigning @tabatkins to investigate...

**Comment by fantasai** [comment]
Should be fixed now. Thanks for the report!
