### ISSUE TITLE
[css-nesting-1] Need to specify error-handling when writing selectors via OM

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#7971]
I need to specify what happens when you insert a nested style rule via the OM with a selector that violates the requirement to not start with an identifier or function, or modify the `.selectorText` of an existing rule to violate it.

I think the `.selectorText` update rule should do the check and, like if you try to set it to anything else that's not a valid selector, just do nothing.

For rule insertion, unsure whether we should silently drop such rules or raise an error.

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/cssom/#insert-a-css-rule throws in case of error:

> 2. If index is greater than length, then [throw](http://heycam.github.io/webidl/#dfn-throw) an [IndexSizeError](https://webidl.spec.whatwg.org/#indexsizeerror) exception.

> 4. If new rule is a syntax error, [throw](http://heycam.github.io/webidl/#dfn-throw) a [SyntaxError](https://webidl.spec.whatwg.org/#syntaxerror) exception.
> 5. If new rule cannot be inserted into list at the zero-index position index due to constraints specified by CSS, then [throw](http://heycam.github.io/webidl/#dfn-throw) a [HierarchyRequestError](https://webidl.spec.whatwg.org/#hierarchyrequesterror) exception.
> 6. If new rule is an `@namespace` at-rule, and list contains anything other than `@import` at-rules, and `@namespace` at-rules, [throw](http://heycam.github.io/webidl/#dfn-throw) an [InvalidStateError](https://webidl.spec.whatwg.org/#invalidstateerror) exception.

So I think it should be the same for nesting.

**Comment by tabatkins** [comment]
Retagging to CSSOM, as that's where the algorithm that needs modification lives. It looks like it should throw a SyntaxError (thanks, @Loirooriol).

**Comment by tabatkins** [comment]
Gonna close this as fixed for now.

* the `selectorText` setter has been specified to "do nothing and return" if you try to set a nested rule's selector to something invalid (like it does with any other invalid selector)
* CSSOM already has a step in its "insert a CSS rule" algo that checks if inserting the rule would violate "a constraint imposed by CSS", so I just added a Note emphasizing that the selector syntax restriction on nested rules counts as such a constraint, so inserting a style rule into a nesting context with an invalid nesting selector will throw a HierarchyError.

**Comment by Loirooriol** [comment]
Blink seems to produce a DOMException, @sesse.

**Comment by cdoublev** [comment]
> Blink seems to produce a DOMException

Agree, whose name is a SyntaxError, and which is produced in *parse a CSS rule* (step 3 of *insert a CSS rule).

**Comment by sesse** [comment]
> Blink seems to produce a DOMException, @sesse.

Which test is this?

**Comment by Loirooriol** [comment]
```html
<!DOCTYPE html>
<style>*{}</style>
<script>document.styleSheets[0].cssRules[0].insertRule("a{}", 0);</script>
```

> Uncaught DOMException: Failed to execute 'insertRule' on 'CSSStyleRule': the rule 'a{}' is invalid and cannot be parsed.

**Comment by sesse** [comment]
I would very much appreciate if people modified the WPT tests when modifying the spec, instead of tagging implementers on GitHub :-) That way, we'd get a bug report that we can put into our regular workflow. (Or filed a bug at crbug.com.)

**Comment by cdoublev** [comment]
I think there was no modification in the specification related to this issue.

https://github.com/web-platform-tests/wpt/blob/e7660882a3b2243f4de86036136a5d527f02f1db/css/css-nesting/cssom.html#L132

Sorry for the noise. =)
