### ISSUE TITLE
[scroll-animations-1] Phases for taller than scrollport subjects

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#7973]
## Our current approach to the phases

I’ve been working on some visualizations for scroll-animations, to visually show how they are measured. For example, for smaller-than-scrollport-subjects:

| <img width="1040" alt="image" src="https://user-images.githubusercontent.com/213073/198655479-62540f31-59e7-48a7-beed-72e07fb7911e.png"> | <img width="1039" alt="image" src="https://user-images.githubusercontent.com/213073/198655230-789bc102-d9aa-47a9-b5e1-0dac9484e170.png"> |
|-|-|

For taller-than-scrollport-subjects, simply making the boxes bigger does not work, because that would mean `contain 100%` comes before `contain 0%`, which is impossible:

| <img width="1038" alt="image" src="https://user-images.githubusercontent.com/213073/198656468-14b8a4a9-2255-4b2b-bdc8-c41430c3c0f8.png"> | <img width="1041" alt="image" src="https://user-images.githubusercontent.com/213073/198656626-6ce6bc0a-5a9a-4300-800f-afb4e1515ceb.png"> |
|-|-|

To solve this, we flipped the edge against which the subject is measured _(note how the darker line on the center two subjects has flipped sides)_:

| <img width="1040" alt="image" src="https://user-images.githubusercontent.com/213073/198657105-4d929c11-a2d8-4da7-b8e1-3561709a7f67.png"> | <img width="1038" alt="image" src="https://user-images.githubusercontent.com/213073/198657359-c3cf1734-3dd5-4988-af7d-bd09e8d9db40.png"> |
|-|-|

With that, we also shortened the range for enter/exit phases, in order to be able to use 1 set of keyframes that has no overlap between the enter-contain-exit phases:

| <img width="1040" alt="image" src="https://user-images.githubusercontent.com/213073/198657738-4664de7a-0161-435d-9085-8d31beb6d395.png"> | <img width="1037" alt="image" src="https://user-images.githubusercontent.com/213073/198658095-e1cf42ae-7fc9-4a88-9af4-f9106d93f2a4.png"> |
|-|-|

## Limitations of the current approach

This comes with two nasty side-effects imo:

1. The entry/exit phases are shortened, because phase change detection  does not happen on the same edge
    | <img width="1039" alt="image" src="https://user-images.githubusercontent.com/213073/198659234-76702d8b-9770-43a0-9ee9-d81723e8c15b.png"> |
    |-|
2. The meaning of enter and exit changes. This can be troublesome for an element that is initially smaller than the scrollport but becomes taller due to a resize.

This problem becomes clear in a demo such as https://codepen.io/bramus/pen/XWEeGZm no longer possible, where it’s not possible to create it using the new phases. 

_(FYI: the demo uses a version of the polyfill that measures things differently to make it work after all)_

## An alternative solution

To solve this, I would like us:

1. To not change the meaning of enter/exit, and have their measurements be done consistently
2. Introduce extra phases to allow the current interpretation of enter/exit for taller-than-scrollport-subjects.

Additionally, I also think we have our names wrong, as the current `enter 100%` for taller-than-scrollport-subjects visually means “it is entirely covering the scrollport”. This does not rhyme well the existing `cover`.

What I would like to propose, are the following phases. I have added the edge/threshold indicators from earlier versions of the spec as that might make thing easier to understand _(this [visualization tool of edges and thresholds](https://codepen.io/bramus/pen/ZEBvVxX) might come in handy)_:

- Smaller than scrollport subjects
    - enter = end 0 → end 1
    - exit = start 1 → start 0
    - contain = end 1 → start 1
    - intersect = end 0 → start 0
- Taller than scrollport subjects
    - enter = end 0 → end 1
    - enter-cover = end 0 → start “1”
    - exit = start 1 → start 0
    - cover-exit = end ”1’ → start 0
    - cover = start 1 → end 1
    - intersect = end 0 → start 0

These visuals summarize the proposed changes:

| <img width="1037" alt="image" src="https://user-images.githubusercontent.com/213073/198672377-1c3038fb-85a8-4d77-a766-5dd68281cff3.png"> | <img width="1038" alt="image" src="https://user-images.githubusercontent.com/213073/198672449-8d5576c3-cb67-4638-9a3e-638a7532bf27.png"> | <img width="1039" alt="image" src="https://user-images.githubusercontent.com/213073/198672528-4dbdb68c-319c-49c1-8354-9a925aff701e.png"> |
|-|-|-|

## The real ask

Maybe we can do a breakout session on this? Some time in the 2nd half of November maybe? Just before/after a WG meeting?

As you might have noticed by now, I have prepared slides for this :) 

/ping All attendees of a previous breakout session: @fantasai @tabatkins @flackr @kevers-google @mirisuzanne @ydaniv @jensimmons @smfr @argyleink

**Comment by ydaniv** [comment]
My main reasoning is that current design maps very cleanly with >90% of intents that I know, and pretty easily. I think the spec is pretty easy to understand, and also for authors to work with.
I also think the main idea of ViewTimeline is to animate along the phases we already define as **intents** to animate along phases of view (enter, exit, entire view, etc), and less so to fully animate across all possible parts of the scroll length. As in view's intent, and not view's length.

**Comment by bramus** [comment]
> The enter/exit phases are defined not based on "am I crossing a threshold", but rather "am I in the process of entering the viewport" where the state of having entered is the "contain" phase.
> 
> And the "contain" phase is not defined as "fully contained by the viewport" for large items because this would mean such items would never reach the contain phase. We could rename it, but basically the "contain" phase as it's defined now is the "I'm fully in the viewport (inasmuch as I can be)" phase.

Thanks for clarifying the definitions. I think `contain` could be renamed, but the only fitting name I found for it is `cover`: _“I am covering the viewport (inasmuch as I can)”_. Unfortunately it’s already used, so would require a rename of the existing `cover`.

> Are there use cases for other phase interpretations? Yes. Should we find ways to enable them? Probably.

What is we allowed authors to define custom animation phases? Something like:

```css
@custom-timeline-phase --long-exit {
    from: start start 1; /* When the start edge of the subject hits the start edge of the scroller, and the subject is 100% (or more in case of taller-than-scrollport-subjects) in-scrollport. */
    to: end start 0;  /* When the end edge of the subject hits the start edge of the scroller, and the subject is 0% in-scrollport. */
}
```

Not sure if we need the thresholds there, and not sure if this would play nice with `@keyframes` that refer to phases.

> If the animation code needs to depend on knowing those relative sizes, or is easy to screw up when they invert on someone else's computer, we've designed a system that will fail depending on the environment a page is loaded in, and that's bad CSS language design.

The example shown doesn’t need to know the size of the subjects nor the scroller. It uses the sibling index of each element to limit when the animation runs, similar to how authors implement staggered animations.

> I also think the main idea of ViewTimeline is to animate along the phases we already define as intents to animate along phases of view (enter, exit, entire view, etc), and less so to fully animate across all possible parts of the scroll length. As in view's intent, and not view's length.

As shown in the example I linked to, this becomes a limitation when animating elements that are not the subject itself. In those cases you sometimes do want to target the “long-enter”/“long-exit”

**Comment by bramus** [comment]
SGTM! 👍

**Comment by fantasai** [comment]
Proposed Resolution: Add `entry-crossing` and `exit-crossing` timeline ranges for while an element is crossing the corresponding viewport threshold.

**Comment by bramus** [comment]
I took a jab at defining these new ranges in https://github.com/bramus/csswg-drafts/commit/392a4deefdc546591ab48ed899aded52bd698467

**Comment by flackr** [comment]
SGTM2

**Comment by bramus** [comment]
@fantasai I’ve reworked the visuals above to include these new phases. Are these the type of visuals that you would like to see in the spec, or are you looking for a different representation?

| <img width="1064" alt="image" src="https://user-images.githubusercontent.com/213073/218341143-2d7b8602-bd8d-42b8-9a98-78529df7f6db.png"> | <img width="1068" alt="image" src="https://user-images.githubusercontent.com/213073/218341151-b74a019b-144b-4301-9357-943e87d7189a.png"> |
|-|-|

If these are considered OK, should they – after refining them a bit more – be included in the spec as an SVG _(cfr. https://drafts.csswg.org/css-view-transitions-1/)_, or do you prefer ASCII art _(cfr. [what you’ve done before](https://github.com/w3c/csswg-drafts/commit/e6ca22a05f0450627ed81e2803ed66e45ca7ea83#diff-2c9a6f64531fbc8999f49d196d504641d843cb1e57a45650cd75b613958b17c9R754))?_

I’ve also got a PR ready to update the spec to reflect [this issue’s resolutions from two weeks ago](https://github.com/w3c/csswg-drafts/issues/7973#issuecomment-1412441312): https://github.com/w3c/csswg-drafts/pull/8388
