### ISSUE TITLE
[css-color] Is relative color syntax ready to ship?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#7978]
https://www.w3.org/TR/css-color-5/#relative-colors

https://www.w3.org/TR/css-color-5/#serial-relative-color

This came up as an Interop 2023 proposal, and there is an implementation in WebKit, and we were wondering if this is ready to ship?

cc @svgeesus @emilio @lilles

**Comment by emilio** [comment]
@nt1m how does the WebKit implementation (and what does the spec say) about `currentColor` and similar usual-suspects?

**Comment by nt1m** [comment]
> @nt1m how does the WebKit implementation (and what does the spec say) about `currentColor` and similar usual-suspects?

I think we'll end up matching what `color-mix()` will be doing (cc @mdubet who will be working on fixing that)

**Comment by svgeesus** [comment]
Yes, matching `color-mix()` seems the way forward.

**Comment by yairEO** [comment]
And for the safe of the record, for me who has no idea what `color-mix()` has implemented, what exactly should happen with `currentColor` & *relative-color*? 

(I came here investigating **especially** this use-case)

**Comment by yairEO** [comment]
My question is this use-case:
```css
div{ background: rgb(from currentColor r g b / 50%) }
```

**Comment by svgeesus** [comment]
Yeah that would serialize as specified; it can't fully resolve because the value of the color property could be different on child elements or child pseudo-elements.

**Comment by svgeesus** [comment]
This needs explicit spec text for resolving the RCS value when `currentColor` is the origin , saying that the RCS serializes as specified so that child elements are handled correctly. There is already similar text in [Resolving `color-mix()` Values](https://drafts.csswg.org/css-color-5/#resolving-mix)for resolving `color-mix()` so as noted by we should re-use that:

> If all [<color>](https://drafts.csswg.org/css-color-4/#typedef-color) parameters resolve to the corresponding colors in their respective color spaces, the computed value is the mixed color, in the specified mixing color space, resolved according to [CSS Color 4 § 14 Resolving <color> Values](https://drafts.csswg.org/css-color-4/#resolving-color-values). Otherwise (if [currentColor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor) was used in the function), the computed value is the [color-mix()](https://drafts.csswg.org/css-color-5/#funcdef-color-mix) function with each <color> parameter resolved according to [CSS Color 4 § 14 Resolving <color> Values](https://drafts.csswg.org/css-color-4/#resolving-color-values), thus preserving inheritance into child elements.

**Comment by svgeesus** [comment]
@nt1m @emilio I added the specific text, does this look good to you and are there any other blockers for shipping RCS?
