### ISSUE TITLE
[css-variables] Serialize shorthand for longhands with equivalent pending substitution value

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7983]
> If all of the component longhand properties for a given shorthand are pending-substitution values from the same original shorthand value, the shorthand property must serialize to that original (`var()`-containing) value.

A shorthand cannot serialize if all its longhands are individually declared to an equivalent value. Why?

I suggest to allow a shorthand to serialize if representations of its longhand declaration values are the same.

```js
style.borderBlockStartWidth = 'var(--custom)'
style.borderBlockInlineWidth = 'var(--custom) /* comment */'
style.borderBlockWidth; // ''
style.borderBlockInlineWidth = 'var(--custom)'
style.borderBlockWidth; // 'var(--custom)'
```

**Comment by cdoublev** [comment]
Hmm, I realized that it is not worth it (authors will rarely declare longhands this way). Sorry.

**Comment by Loirooriol** [comment]
Was `borderBlockInlineWidth` supposed to be `borderBlockEndWidth`?

It's not that it's not worth it. It just doesn't work:

```js
style.cssText = "border-style: solid; --custom: 1px 2px";
style.borderBlockStartWidth = style.borderBlockEndWidth = "var(--custom)";
computedStyle.borderBlockStartWidth; // "3px"
computedStyle.borderBlockEndWidth; // "3px"
style.borderBlockWidth += ""; // Let's assume "var(--custom)"
computedStyle.borderBlockStartWidth; // "1px" !!!
computedStyle.borderBlockEndWidth; // "2px" !!!
```

**Comment by cdoublev** [comment]
> Was `borderBlockInlineWidth` supposed to be `borderBlockEndWidth`?

Yes, sorry.

I will keep note of this example to remind myself why a shorthand cannot serialize when all its longhands are declared with the same subsitution value: the substitution value must be declared on the shorthand. Thanks! (once again)
