### ISSUE TITLE
[css-text-decor] Positional adjustment of line-through and overline

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#799]
Based upon [my comment](https://github.com/w3c/csswg-drafts/issues/711#issuecomment-265879767) in #711:

There should be either another value for [`text-decoration`](https://drafts.csswg.org/css-text-decor/#propdef-text-decoration) / [`text-decoration-line`](https://drafts.csswg.org/css-text-decor/#propdef-text-decoration-line) to get a line crossing through ascenders or, preferably, new properties `text-overline-position` and `text-line-through-position` (or a compound `text-decoration-position`) to adjust the position determined by the font file.

> - `underline`: Each line of text is underlined.
> - `overline`: Each line of text has a line over it (i.e. on the opposite side from an underline).
> - `line-through`: Each line of text has a line through the middle.

The most important reason (in Western typography) to desire `text-decoration-skip: ink;` is that `underline` cuts through descenders of lowercase letters (like _g, j, p, q, y_). However, neither `overline` nor `line-through` regularly cuts through the ascenders of lowercase letters (like _b, d, f, h, [i, j], k, l, t_), because `overline` is usually placed above the ‘H’ height of uppercase letters (possibly without diacritic marks) and `line-through` is set lower than the ‘x’ height of lowercase letters to affect short ones (like _a, c, e, m, n, o, r, s, u, v, w, x, z_), too.

~~~css
s, strike, del {
    text-decoration: line-through;
    text-decoration-skip: ink;
    text-line-through-position: over; /* over unspecified “middle”, i.e. above x-height */
}
~~~

**Comment by fantasai** [comment]
I have no idea what you're requesting here. #711 is closed.

**Comment by Crissov** [comment]
A way to adjust the relative position of "decorative" lines.

**Comment by fantasai** [comment]
We already have that ability in Level 4.
