### ISSUE TITLE
[web-animations-1] Export dfns to expose the effect target of an animation

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8001]
In the [view transitions spec](https://drafts.csswg.org/css-view-transitions-1/) we want to write prose about the element being animated by a specific animation.

It feels like the right prose would be something like:

> 1. Let effect be animation's associated effect.
> 2. If effect is a keyframe effect, and effect's effect target's target element is…

If that's correct, I propose:

- Export [keyframe effect](https://drafts.csswg.org/web-animations-1/#keyframe-effect).
- Create a proper association between "effect target" and "keyframe effect". A lot of prose right now talks about an effect's effect target, but there's no defined association between the two. This association will be exported.
- Export [effect target](https://drafts.csswg.org/web-animations-1/#effect-target), and its [target element](https://drafts.csswg.org/web-animations-1/#target-element) and [target pseudo-selector](https://drafts.csswg.org/web-animations-1/#target-pseudo-selector).

**Comment by birtles** [comment]
> In the [view transitions spec](https://drafts.csswg.org/css-view-transitions-1/) we want to write prose about the element being animated by a specific animation.

The text for [`getAnimations`](https://drafts.csswg.org/web-animations-1/#dom-animatable-getanimations) might be useful here:

> Returns the set of [relevant](https://drafts.csswg.org/web-animations-1/#relevant-animation) [Animation](https://drafts.csswg.org/web-animations-1/#animation) objects that contain at least one [animation effect](https://drafts.csswg.org/web-animations-1/#animation-effect) whose [effect target](https://drafts.csswg.org/web-animations-1/#effect-target) is this object

Or are you trying to go in the other direction? An `Animation` can target `0..n` (pseudo-)elements so I guess it depends on the specific prose in mind.

**Comment by jakearchibald** [comment]
Ohh, the `getAnimations` prose might work out. I'll give it a go, cheers!

> An `Animation` can target `0..n` (pseudo-)elements

Ohhh, I thought the hierarchy was "animation has a single animation effect, if that's a keyframe effect, it has a single effect target". When can it target more than one?

**Comment by jakearchibald** [comment]
The `getAnimations` stuff looks good. Could you export:

- https://drafts.csswg.org/web-animations-1/#relevant-animation 
- https://drafts.csswg.org/web-animations-1/#effect-target
- https://drafts.csswg.org/web-animations-1/#target-element
- https://drafts.csswg.org/web-animations-1/#target-pseudo-selector

Or, create a new exported algorithm for getting the animations for an element + optional pseudo.

**Comment by birtles** [comment]
> > An `Animation` can target `0..n` (pseudo-)elements
> 
> Ohhh, I thought the hierarchy was "animation has a single animation effect, if that's a keyframe effect, it has a single effect target". When can it target more than one?

With a [group effect](https://drafts.csswg.org/web-animations-2/#the-groupeffect-interface) or [sequence effect](https://drafts.csswg.org/web-animations-2/#the-sequenceeffect-interface) from Web Animations level 2. These don't exist yet but the spec has always tried to accommodate their future addition.

That, and the fact that an `Animation` can have a `null` `effect` are why there's not really a concept of "the element targeted by an `Animation`".

**Comment by birtles** [comment]
> Or, create a new exported algorithm for getting the animations for an element + optional pseudo.
> 
> Maybe the latter is better, so if `getAnimations` needs updating, other specs trying to do the same thing won't need to update too.
