### ISSUE TITLE
[web-animations-1] Document associations for document timelines

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8002]
The [default document timeline](https://drafts.csswg.org/web-animations-1/#default-document-timeline) should be `for="document"` since they're per document.

[Document timelines](https://drafts.csswg.org/web-animations-1/#document-timeline) should have a `<dfn for="document timeline">document</dfn>` so their association is properly defined.

**Comment by jakearchibald** [comment]
I don't think that fix is quite right. Now "the **timeline** has a **default document timeline**", which doesn't seem right. It feels like it should be "the **document** has a **default timeline**".

And "the **document timeline** has a **document**".

**Comment by birtles** [comment]
Yes sorry, you're right! I made that change in a real hurry this morning since I'll be away next week and I wanted to take care of this first.

**Comment by jakearchibald** [comment]
I'm happy to get a PR together. I realise I'm being the fussy one 😄
