### ISSUE TITLE
[css-animations] Allow CSSKeyframesRule.name to set reserved values

### ISSUE THREAD

**Issue by Manishearth** [w3c/csswg-drafts#801]
https://drafts.csswg.org/css-animations/#dom-csskeyframesrule-name

> Setting this property to a value matching a CSS-wide keyword or any keyword defined for the animation-name property will throw a SyntaxError exception. 

However, it is already possible to create a keyframes rule with a name matching a CSS-wide keyword using a string -- `@keyframes "initial" {..}` works (See https://drafts.csswg.org/css-animations/#typedef-keyframes-name and Example 2 below it). The DOM setter should be able to create such rules, so we should remove the ability for the setter to throw a syntax error and allow all strings.

cc @canaltinova @dbaron

**Comment by SimonSapin** [comment]
I’m changing Servo’s implementation to not throw, and instead store a value that serializes as a quoted string.

**Comment by birtles** [comment]
I also checked and noticed that Gecko already allows quoted strings and does not throw when setting reserved values: https://codepen.io/birtles/pen/xdRjap

**Comment by dbaron** [comment]
Gecko changed to allow strings in [bug 1320474](https://bugzilla.mozilla.org/show_bug.cgi?id=1320474), which cites #118.
