### ISSUE TITLE
[scroll-animations-1] Duplicate definition of AnimationTimeline

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#8013]
Scroll animations redefines the [`AnimationTimeline` interface](https://drafts.csswg.org/scroll-animations-1/#animationtimeline) but this is already defined [in Web Animations](https://drafts.csswg.org/web-animations-1/#the-animationtimeline-interface). This creates conflicting definitions for readers and in the spec database.

We should probably do the `CSSNumberish` change in Web Animations level 2--in fact we already do but we should probably highlight that it is a change there. Then we should make the additions to the `AnimationTimeline` timeline in Scroll Animations (i.e. `getCurrentTime`) via a `partial interface` and drop the `currentTime` member from there.

(On a side-note, I think `resolveCurrentTime` would be better than `getCurrentTime` since `getCurrentTime` overlaps with the getter for `currentTime`.)

**Comment by birtles** [comment]
Alternatively, it might be simpler to move `getCurrentTime`/`resolveCurrentTime` to Web Animations level 2.

**Comment by fantasai** [comment]
@birtles That entire appendix should move to Web Animations 2. But it's not yet FPWD, so I'm maintaining the stuff needed for Scroll Animations in an appendix of Scroll Animations.

Once WA2 is otherwise ready for FPWD, we should fold in the contents of the appendix, publish, and remove from Scroll Animations.

**Comment by birtles** [comment]
> @birtles That entire appendix should move to Web Animations 2. But it's not yet FPWD, so I'm maintaining the stuff needed for Scroll Animations in an appendix of Scroll Animations.
> 
> Once WA2 is otherwise ready for FPWD, we should fold in the contents of the appendix, publish, and remove from Scroll Animations.

Got it. Anyway to exclude it from the link database? Specs are picking up the definition of `AnimationTimeline` from scroll animations when they really should be pointing to Web Animations.

**Comment by fantasai** [comment]
@birtles I think this is fixed now, if so can you close the issue? If not, let me know which spec to test for errors. :]
