### ISSUE TITLE
[css-ui] Regarding issue 24 in the spec (about the need to support values other than appearance:auto|none)

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#802]
https://drafts.csswg.org/css-ui-4/#appearance-switching
> ISSUE 24 IE supports -webkit-appearance, and also includes the textfield and button values. Presumably this was done due to compatibility problems, so we may need to include it as well.

As far as I can tell, Edge supports `-webkit-appearance:none`, but no other values.  So unless I'm missing something, I think ISSUE 24 can be removed from the spec.  This is the test I used:
https://people-mozilla.org/~mpalmgren/tests/appearance.html

**Comment by frivoal** [comment]
Thanks for the heads up.
My testing confirms this the same. Closing the issue, and converting part of it into a note.
