### ISSUE TITLE
[css-borders-4] Add slashes between individual `border-color` values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8026]
As [mentioned in the change to add the `stripes()` function](https://github.com/w3c/csswg-drafts/pull/7029#issuecomment-1104969215), I believe it makes sense to follow the example of `grid-area` and separate the different longhand values of `border-color` via slashes.

This makes it easier to distinguish them, especially in regard of the aforementioned new function. And it makes the syntax also more future-proof for further extensions.

The existing one-to-four `<color>`s syntax still needs to be supported, of course. Though all new features like the `<1d-image>` values require the values to be separated by slashes. So the suggested syntax is:

```
<<color>>{1,4} | [ <<color>> | <<1d-image>> ] [ / [ <<color>> | <<1d-image>> ] ]{0,3}
```

Examples:

```
border-color: red / yellow / lime / blue;
border-color: stripes(white, silver) / stripes(white, silver) / stripes(black, gray) / stripes(black, gray);
border-color: red / stripes(yellow, orange) / lime / stripes(blue, navy);
```

Sebastian

**Comment by cdoublev** [comment]
Aside: maybe a slash ellision rule and/or a multiplier equivalent to `#` but for `/` separated values instead of `,` separated values, could be defined, in order to make writing and parsing these basic syntaxes easier.

**Comment by Loirooriol** [comment]
Any reason to use `[ <<color>>? <<1d-image>>? ]!` and not `<<color>> || <<1d-image>>`?

**Comment by SebastianZ** [comment]
> Any reason to use `[ <<color>>? <<1d-image>>? ]!` and not `<<color>> || <<1d-image>>`?

The syntax given in the initial comment was actually wrong. It was taken from when I thought of `<color>` as a fallback value for `<1d-image>`. Though we concluded that this doesn't have strong use cases and rather complicates the syntax. So I corrected it to be `<<color>> | <<1d-image>>`.

Sebastian

**Comment by SebastianZ** [comment]
Putting this on the agenda to discuss whether adding slashes - or in general make the syntax more extendable - makes sense.

Sebastian

**Comment by fantasai** [comment]
I'm a bit confused. If the syntax of `border-*-color` is `<color> | <1d-image>`, then why isn't `border-color: <'border-top-color'>{1,4}` sufficient?
