### ISSUE TITLE
[css-ui-4] Nested `<url-set>` should be invalid

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8030]
I think nested `<url-set>` cannot be valid because CSS Images forbids it.

> `<url-set>` is a limited version of `image-set()`, where only `<url>` and `<url-set>` can be used in the part of the `<image-set-option>` sub-production which would normally allow `<image>`.

https://drafts.csswg.org/css-ui-4/#typedef-cursor-url-set

> The `image-set()` function can not be nested inside of itself, either directly or indirectly (as an argument to another `<image>` type).

https://drafts.csswg.org/css-images-4/#funcdef-image-set

**Comment by frivoal** [comment]
Agreed. Closed with https://github.com/w3c/csswg-drafts/commit/887025da9e52a8f19961fb9e298fda9961821f4b
