### ISSUE TITLE
[css-values-4] positive zero has reference(s) or is defined?

### ISSUE THREAD

**Issue by himorin** [w3c/csswg-drafts#8034]
(related to 7472?) Signed zero are used in css-values-4 spec for several kinds of mathematical operation especially ones related to infinite, like [stepped value functions](https://www.w3.org/TR/css-values-4/#round-func), and "negative zero" has its reference for its concept (definition-ish?) as

>Additionally, IEEE-754 introduces the concept of "negative zero", which must be tracked within a calculation and between nested calculations:

in [Type Checking](https://www.w3.org/TR/css-values-4/#calc-type-checking) section (although there is no normative nor informative reference to there), but I could not find any text for positive zero.

It seems for me is should be better to have some clear concept (or definition?) for these signed zero by text or by reference. OR, "negative zero" in cited text above should be "signed zero"?

**Comment by tabatkins** [comment]
I've clarified the text slightly to talk about "signed zero" and then explicitly mentioned that any zero produced by a calculation that isn't defined to be negative zero is instead positive zero.
