### ISSUE TITLE
csswg and fxtf

### ISSUE THREAD

**Issue by letochagone** [w3c/csswg-drafts#8047]
I often ask theoretical questions, they are not 'issues'.
So I think I am not asking the questions in the right place.
 Is there another place in the w3c github?

 Finally what is the difference between fxtf-drafts and csswg-drafts?

**Comment by cdoublev** [comment]
> A Task Force is a subset of a Working Group dedicated to progressing a specific deliverable or set of deliverables on behalf of that group.

> The objective of the CSS-SVG Effects Task Force (FX TF) is to jointly develop features for use in both CSS and SVG

https://www.w3.org/Graphics/fx/

**Comment by tabatkins** [comment]
In practice, the difference is just that the FXTF repo holds a few CSS specs for historical reasons. Questions about those specs in particular should be asked in the fxtf repo, but otherwise everything should be done here in csswg-drafts.
