### ISSUE TITLE
[css-display-3] Display contents on the root element.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#805]
In https://drafts.csswg.org/css-display-3/#valdef-display-contents, there's no explicit mention to how display contents should behave when specified on the root element, i.e., `html { display: contents }`.

There are a few places in the CSS spec where some elements (like the root element, out of flow positioned elements, floats, or child of grid/flex items) get "blockified". It makes sense to allow display: contents on most of these elements, since there are use cases for display: contents under a flex or grid element.

The only shipping implementation so far (Gecko's) allows specifying display: contents on out of flow positioned elements and floats, but not the root. The in-progress blink implementation has aligned with Gecko in this regard, but this should be specified somewhere, in order to prevent compat issues.

cc @rune-opera

**Comment by rune-opera** [comment]
It's actually already specified in https://drafts.csswg.org/css-display-3/#transformations

See the last sentence of that section about contents and the root element.
