### ISSUE TITLE
[css-shapes-1] `shape-image-threshold` lacks examples, tests

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#8051]
[Choosing Image Pixels: the `shape-image-threshold` property](http://w3c.github.io/csswg-drafts/css-shapes-1/#shape-image-threshold-property) has no examples, and also no WPT tests

**Comment by astearns** [comment]
This example mentions and uses shape-image-threshold: http://w3c.github.io/csswg-drafts/css-shapes-1/#example-12b6dfcf
