### ISSUE TITLE
[mediaqueries] Difference between unknown `<mf-value>` and a feature value not matching

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8052]
Can you please clarify what is the difference between *"an unknown `<mf-value>`"* and *"a feature value which does not match the value syntax for that media feature"*, in [3.2 Error Handling](https://drafts.csswg.org/mediaqueries-5/#error-handling)?

> An unknown `<mf-name>` or `<mf-value>`, or a feature value which does not matches the value syntax for that media feature, results in the value “unknown”.

Does *feature value* designate the specified `<mf-value>` or the current user environment value?

**EDIT:** I guess that this sentence makes a difference between matching `<ident>` in `<mf-value>`, and matching `value` in the table definition of the media feature. If so, *an unknown `<mf-name>` or a `<mf-value>` which does not match the value syntax for that media feature, results in the value “unknown”* seems more clear, imo.

**Comment by gsnedders** [comment]
See #7595.

**Comment by cdoublev** [comment]
I am sorry for the duplicate. I did not search properly.

#7595 does not touch on the difference between a `<mf-value>` that is *not matching the syntax* vs. *unknown*. Since you made the change on this sentence, can you please confirm that it corresponds to the difference between *not matching `<ident>`* (ie. the syntax of `<mf-value>`, and *not matching the syntax defined in the value definition of the corresponding `<mf-name>`?

**Comment by gsnedders** [comment]
Ah, sorry, I was quickly looking over this.

> #7595 does not touch on the difference between a `<mf-value>` that is _not matching the syntax_ vs. _unknown_. Since you made the change on this sentence, can you please confirm that it corresponds to the difference between _not matching `<ident>`_ (ie. the syntax of `<mf-value>`, and _not matching the syntax defined in the value definition of the corresponding `<mf-name>`_?

Yes. This is part of what makes the whole thing terribly written (and my change was only intended to clarify the above, but without more cross-references it's hard to actually make clear).
