### ISSUE TITLE
[css-view-transitions-1] CSS selector to differentiate transitions with only old or new images

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8057]
Filing a separate issue to track the use-case identified in the comment [here](https://github.com/w3c/csswg-drafts/issues/7788#issuecomment-1301515920), pasted below:

I'll note that our suggestion doesn't rely specifically on the specific mapping of class/element syntax, but that provides a good example. Whatever the selector-syntax mapping (@FremyCompany's suggestion of IDs might make more sense), the goal is just to allow compound/complex selectors in the function.

One reason for that might be exposing the hierarchy. The more important goal in my mind was the ability to differentiate what happens in these three instances:

1. There is _only a `new` image_.
2. There is _only an `old` image_.
3. There are _both `old` and `new` images_.

The solution mentioned a few times for that is using `:only-child`/`:not(:only-child)` on the element in question. I assume that solution is also possible with the current proposal?

```css
html::view-transition-old(*):only-child {
  /* this is a default exit animation */
}
```

This could be done with `html::view-transition-old(*):only-child` but @jakearchibald highlighted that " it's tricky because what does ::before:only-child mean? We might need to allow-list which pseudos can use :only-child."

**Comment by cdoublev** [comment]
Please forgive me for this aside.

In [3.6.5 Internal structure](https://drafts.csswg.org/selectors-4/#pseudo-element-structure), Selectors says:

> Some pseudo-elements are defined to have internal structure.

And CSS View Transitions says:

> The precise tree structure, and in particular the order of sibling pseudo-elements, is defined in the setup transition pseudo-elements algorithm.

Can I assume that all except `::view-transition-new()` and `::view-transition-old()` have an internal structure? I do not have a good knowledge of CSS View Transitions and it is not easy for me to answer this from reading the above mentioned algorithm.

**Comment by jakearchibald** [comment]
You don't have to assume, it's all defined in https://github.com/w3c/csswg-drafts/pull/8126 😄 

(but yes, `::view-transition-new` and `::view-transition-old` are replaced content, so they never have children)

**Comment by khushalsagar** [comment]
Edits landed in https://github.com/w3c/csswg-drafts/pull/8126.
