### ISSUE TITLE
[css-fonts] Missing serialization of font shorthand for non initial font-palette value

### ISSUE THREAD

**Issue by tursunova** [w3c/csswg-drafts#8062]
Currently in spec for [font shorthand](https://drafts.csswg.org/css-fonts/#font-prop) and [font-palette](https://drafts.csswg.org/css-fonts/#propdef-font-palette) properties there is no specification if the font shorthand property should be serialized or not if font-palette is set to non initial value.

E.g. in the WPT test [font-palette-vs-shorthand](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/font-palette-vs-shorthand.html) it is unclear if the elements with the following styles:
`#a {
    font: 50px colr;
    font-palette: dark;
}` and 
`#c {
    font-palette: dark;
    font-size: 50px;
    font-family: colr;
}` should reset `font` shorthand property to "". Chrome currently doesn't do that but Firefox does.

**Comment by emilio** [comment]
If you can't parse it (so `font: <something-valid>` would always reset to `font-palette: <initial>`), you shouldn't be able to serialize it, otherwise the shorthand wouldn't round-trip and doing `div.style.font = div.style.font` would change the style.

**Comment by drott** [comment]
Right, looks like we agree that we need to describe what should happen to the serialization if any of the resetted but not settable (through the shorthand) properties are non-initial. Not serializing is a sound option. The point of this issue is mostly to make that explicit and not implicitly assume it's not serializable due to the expectation of the result being safe for round-trip'ing.

**Comment by emilio** [comment]
There's nothing specific about `font`. No shorthand should serialize if it doesn't round-trip, and this is spec'd in CSSOM. https://drafts.csswg.org/cssom/#serialize-a-css-value has:

> If there is no such shorthand or shorthand cannot exactly represent the values of all the properties in list, return the empty string.

**Comment by drott** [comment]
But it can serialize all the properties that are in the list:

https://drafts.csswg.org/css-fonts-4/#font-prop

The ones in the list are:

```
[ [ <'font-style'> || <font-variant-css2> || <'font-weight'> || <font-stretch-css3> ]? <'font-size'> [ / <'line-height'> ]? <'font-family'> ] | caption | icon | menu | message-box | small-caption | status-bar
```

`font-palette` is not in that list, but the prose of the spec text defines the side-effect of resetting it.

**Comment by emilio** [comment]
The list comes from:

  https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue

Which has:

>  For each longhand property longhand that property maps to, in canonical order [...]

So it's not about the `font` property syntax, but about the properties `font` maps to, which includes `font-palette`.

**Comment by drott** [comment]
Thanks for the pointer. To me it depends on what that "maps to" is intended to mean. Does it mean all the properties you can set with it (like in the syntax list)? Or all the properties that are affected by it. I believe you interpret it to mean the latter.

**Comment by emilio** [comment]
It's definitely the later. If it's unclear we should definitely clarify it, but if setting `font: <something>` sets the `font-palette` property, it maps to it, right? Defining it in terms of syntax would be inconsistent.

There's precedent here btw, for example the border property always resets the `border-image-*` sub properties, where all browsers agree:

```js
document.body.style.border = "1px solid";
document.body.style.borderImageSlice = "99%"; // Something non-initial
document.body.style.border // ""
```

**Comment by emilio** [comment]
Well, apparently WebKit doesn't, but that seems like a WebKit bug, cc @nt1m @smfr :-)

**Comment by svgeesus** [comment]
Having read through this issue, it isn't clear to me that any spec edits are needed. Or are they?

**Comment by svgeesus** [comment]
Since this issue was last discussed, CSS Fonts 4 [introduced three categories](https://drafts.csswg.org/css-fonts/#font-prop):

1. **Set Explicitly**
    These properties may be set using the [font](https://drafts.csswg.org/css-fonts/#propdef-font) property
2. **Reset Implicitly**
    These may not be set, but are reset to their initial values
3. **Cascaded Independently**
    There are neither set nor reset by the [font](https://drafts.csswg.org/css-fonts/#propdef-font) property

And [font-palette](https://drafts.csswg.org/css-fonts/#propdef-font-palette) is in the third category; neither set nor resent by the `font` shorthand.

> E.g. in the WPT test [font-palette-vs-shorthand](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/font-palette-vs-shorthand.html) it is unclear if the elements with the following styles:
> `#a { font: 50px colr; font-palette: dark; }` and
> `#c { font-palette: dark; font-size: 50px; font-family: colr; }` should reset `font` shorthand property to "". Chrome currently doesn't do that but Firefox does.

If  Firefox till does, that is contrary to the spec. [The test](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/font-palette-vs-shorthand.html) seems to me to be correct.

My conclusion is that the spec is self-consistent and WPT reflects the spec correctly on this point.

**Comment by emilio** [comment]
Yeah this is basically a dupe of https://github.com/w3c/csswg-drafts/issues/7832
