### ISSUE TITLE
[cssom] U+0000 does not need to be replaced when serializing an identifier

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8074]
I think that U+0000 does not need to be replaced in [*serialize an identifier*](https://drafts.csswg.org/cssom-1/#serialize-an-identifier).

> To serialize an identifier means to create a string represented by the concatenation of, for each character of the identifier: 
> - If the character is NULL (U+0000), then the REPLACEMENT CHARACTER (U+FFFD).
> - [...]

The examples below the definition of [`CSS.escape()`](https://drafts.csswg.org/cssom-1/#dom-css-escape) use it in `document.querySelector()` but [this method](https://dom.spec.whatwg.org/#dom-parentnode-queryselector) parses its input with [*parse a selector*](https://drafts.csswg.org/selectors-4/#parse-a-selector), which leads to replacing U+0000 with U+FFFD in [*filter code points*](https://drafts.csswg.org/css-syntax-3/#css-filter-code-points).

**Comment by Loirooriol** [comment]
I think Typed OM can avoid "filter code points":

```js
var v = new CSSKeywordValue("a\u0000b");
v.value; // "a\u0000b"
v.toString(); // "a�b"
```
