### ISSUE TITLE
[css-values] Define `mix()` with `<declaration-value>`

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#8096]
https://drafts.csswg.org/css-values-4/#interpolate

> ```js
> mix( <percentage> ';' <start-value> ';' <end-value> )
> ```
> 
> - [`<start-value>`](https://drafts.csswg.org/css-values-4/#typedef-mix-start-value)
>     The value at the “start” (0%) of the interpolation range. 
> - [`<end-value>`](https://drafts.csswg.org/css-values-4/#typedef-mix-end-value)
>     The value at the “end” (100%) of the interpolation range.

It doesn't say what's the grammar for `<start-value>` and `<end-value>`.

I think they should be defined to be equivalent to [`<declaration-value>`](https://drafts.csswg.org/css-syntax-3/#typedef-declaration-value), or just use `<declaration-value>` directly.

Related: #8091

**Comment by cdoublev** [comment]
**Aside:** 

I think `w3c/reffy` is not able to extract its production rule because its syntax does not have the usual structure `<name> = rule`, ie:

```
mix( <percentage> ';' <start-value> ';' <end-value> )
```

instead of:

```
<mix()> = mix( <percentage> ';' <start-value> ';' <end-value> )
```

Do you want this simplified form to be recognized by `w3c/reffy`?

**Comment by tabatkins** [comment]
> I think they should be defined to be equivalent to [`<declaration-value>`](https://drafts.csswg.org/css-syntax-3/#typedef-declaration-value)

Yes.

> Do you want this simplified form to be recognized by w3c/reffy?

No, we should fix the markup.
