### ISSUE TITLE
[font-loading] FontFaceSetLoadEvent's fontfaces should use FrozenArray

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#810]
https://drafts.csswg.org/css-font-loading/#fontfacesetloadevent

Current IDL:
```WebIDL
[Constructor(DOMString type, optional FontFaceSetLoadEventInit eventInitDict),
 Exposed=Window,Worker]
interface FontFaceSetLoadEvent : Event {
  readonly attribute sequence<FontFace> fontfaces;
};
```

https://heycam.github.io/webidl/#idl-sequence says "Sequences must not be used as the type of an attribute or constant" so this needs to be:
```WebIDL
[Constructor(DOMString type, optional FontFaceSetLoadEventInit eventInitDict),
 Exposed=Window,Worker]
interface FontFaceSetLoadEvent : Event {
  [SameObject] readonly attribute FrozenArray<FontFace> fontfaces;
};
```

`[SameObject]` thrown in because it's true, a drive-by.

A test for this would have to check that `event.fontfaces===event.fontfaces`, and that `new FontFaceSetLoadEvent('type', { fontfaces: x }).fontfaces!==x` but that the array length and members are equal.

Lists of things are fun. @loonybean

**Comment by bzbarsky** [comment]
For what it's worth, Gecko's IDL for this is:

    [Cached, Constant] readonly attribute sequence<FontFace> fontfaces;

which is just missing `[Frozen]` to be functionally equivalent to `[SameObject] readonly attribute FrozenArray<FontFace> fontfaces;`.

The `[Frozen]` thing came up during code review for the Gecko code (the original patch did include it) and was supposed to lead to the filing of a spec issue, because the spec didn't define the behavior of this getter at all.  It looks like the spec issue never got filed.  :(

**Comment by foolip** [comment]
Great! @loonybean did write a test for this that would be easy to put in web-platform-tests, but I guess it's still csswg-test for this spec?

**Comment by bzbarsky** [comment]
Are there web platform tests added for this?

**Comment by foolip** [comment]
@LoonyBean hasn't landed the [Chromium change](https://codereview.chromium.org/2579513005/) for this yet, but it has a test that would be easy to contribute if putting it in web-platform-tests is acceptable. There isn't even a font-loading directory in csswg-test. @gsnedders, please tell us what to do :)

**Comment by heycam** [comment]
Yeah, looks like I forgot to file an issue at the time. :( Although a few months later @rbyers [reported the issue (and I replied to it!)](http://lists.w3.org/Archives/Public/www-style/2015Dec/0298.html), but I guess it never got acted upon.  Anyway, thanks for getting it fixed now, @foolip.

**Comment by gsnedders** [comment]
@astearns do we have any policy on where new testsuites go?

**Comment by astearns** [comment]
We're moving everything to wpt, so if it can go into wpt to begin with I don't see any reason not to do that.

**Comment by foolip** [comment]
@LoonyBean, what happened in the end with the tests for this? Looks like Blink's test in third_party/WebKit/LayoutTests/fast/css/fontfacesetloadevent-constructor.html could easily be upstreamed if we just know where to put it? @gsnedders, maybe you can just ping this issue after csswg-tests are merged instead of us trying to figure out an interim place for the test?

**Comment by gsnedders** [comment]
@foolip can you file an issue for the tests and assign it to me?

**Comment by foolip** [comment]
@gsnedders, https://github.com/w3c/web-platform-tests/issues/4822 is all yours :)
