### ISSUE TITLE
[cssom-view] VisualViewport should probably also include onscrollend

### ISSUE THREAD

**Issue by dlrobertson** [w3c/csswg-drafts#8103]
## Summary

The [VisualViewport](https://drafts.csswg.org/cssom-view/#the-visualviewport-interface) defines [onscroll](https://drafts.csswg.org/cssom-view/#dom-visualviewport-onscroll), but does not include `onscrollend`.

## Implementation notes

Currently the `scrollend` implementations for Chrome and Firefox will fire a `scrollend` event for a user scroll that stays within the layout viewport to the `Document`, but should probably fire to `Window.visualViewport` instead. Currently this is a case where `scrollend` can be fired to the window without a preceding `scroll`.

**Comment by dlrobertson** [comment]
CC @argyleink

**Comment by argyleink** [comment]
if it has scroll events, it should have a `scrollend` event 👍🏻  i can add that to the spec

i'm not sure i 100% follow `Currently this is a case where scrollend can be fired to the window without a preceding scroll` though

**Comment by dlrobertson** [comment]
> i can add that to the spec

Awesome! Thanks for the quick response!

> i'm not sure i 100% follow Currently this is a case where scrollend can be fired to the window without a preceding scroll.

Sorry, I probably should have been more clear. I'm just making a note about the current implementations (Firefox and Chrome) here. Assuming a user:

 1) pinch zoom to make the visual viewport smaller than the layout viewport
 2) scroll but stay within the layout viewport

These steps would __not__ trigger a `scroll` event to be fired to the window, but would trigger `scroll` events to be fired to the [window.visualViewport](https://drafts.csswg.org/cssom-view/#ref-for-dom-window-visualviewport) to be possibly handled by [VisualViewport.onscroll](https://drafts.csswg.org/cssom-view/#dom-visualviewport-onscroll). Currently, both implementations of `scrollend` do not behave like the `scroll` event in the above scenario. The latest versions of Firefox and Chrome that I've tested fire `scrollend` events with the `window` as the target after step 2. After `onscrollend` is added to the `VisualViewport`, this should change.

**Comment by argyleink** [comment]
^ commit made which adds `onscrollend` to the visual viewport. let me know how I did and close this out if resolved 👍🏻

**Comment by dlrobertson** [comment]
Thanks! This does solve the issue of adding the handler, but I wonder if we need something in the actual firing section. E.g. `scroll` has:

> If target is a [Document](https://dom.spec.whatwg.org/#document), [fire an event](https://dom.spec.whatwg.org/#concept-event-fire) named [scroll](https://drafts.csswg.org/cssom-view/#eventdef-document-scroll) that bubbles at target and fire an event named scroll at the [VisualViewport](https://drafts.csswg.org/cssom-view/#visualviewport) that is associated with target.

For `scrollend`, we only have:

> If scrolling was done on a [viewport](https://drafts.csswg.org/css2/#viewport%E2%91%A0), let doc be the viewport’s associated [Document](https://dom.spec.whatwg.org/#document) and target be the viewport. Otherwise, scrolling is done on an element and let doc be the element’s [node document](https://dom.spec.whatwg.org/#concept-node-document) and target be the element.

I think we need to specify that in some cases we need to fire a scrollend event for the `VisualViewport`. The wording of the `onscroll` steps still confuse me a bit. I'm still not sure how they specify that in some cases we should only fire `Document.scroll` and in some cases only `VisualViewport.scroll`. I'm okay with splitting off this addition of some documenting text for firing the scrollend event into another bug though.

**Comment by argyleink** [comment]
> I think we need to specify that in some cases we need to fire a scrollend event for the VisualViewport.

makes sense to me 👍🏻  i'll do some digging and come up with something good

**Comment by argyleink** [comment]
how's this?! https://github.com/w3c/csswg-drafts/commit/2e46f83fce3af30e6128af70488c939f7165b7e7

**Comment by bokand** [comment]
+1, it'd be nice for this to be in normative text. I'm also not a spec expert but I think adding text in the "scrolling is completed" [steps](https://drafts.csswg.org/cssom-view/#scrolling-events:~:text=Whenever%20scrolling%20is%20completed%2C%20the%20user%20agent%20must%20run%20these%20steps) is probably correct.

I added similar text in  [run the scroll steps](https://drafts.csswg.org/cssom-view/#document-run-the-scroll-steps) for the visual viewport:

```
If target is a Document, fire an event named scroll that bubbles at target and fire an event named scroll at the VisualViewport that is associated with target.
```

Rereading this now, I think this says that whenever the document is scrolled we should also fire `scroll` at the VisualViewport, even if the VisualViewport offset doesn't change. I think that's wrong, we should only fire `scroll` at VisualViewport if its offset changes.

I think we want to add VisualViewport to the `pending scroll event targets`:

```
Whenever a VisualViewport gets scrolled (whether in response to user interaction or by an API), the user agent must run these steps:...
``` 

And then the run scroll steps should be:

```
 * If target is a Document, fire an event named scroll that bubbles at target
 * If target is a VisualViewport, fire an event named scroll at it.
```

And then add similar language for the scrollend steps.

@argyleink - if you're already doing work here would you mind making these changes? If not, I could probably squeeze in a PR later this week.

**Comment by argyleink** [comment]
I could attempt to translate the thoughts you dropped above into the spec sure, but I might fall short somewhere.. I'm certainly interested in what you write and I agree with your above assertions, like "we should only fire scroll at VisualViewport if its offset changes". I'd love help, as I'm doing my best but can feel like i'm not super confident.

**Comment by bokand** [comment]
No problem. I should have some time tomorrow, will take a crack at it. Thanks!

**Comment by bokand** [comment]
Turns out I had less time than I thought :/

Anyway, I did finally get to it - please feel free to leave comments on the review!

**Comment by dlrobertson** [comment]
> Anyway, I did finally get to it - please feel free to leave comments on the review!

Thanks for working on this! Read through once, but I'll have to read it a few times to get to the point where I'm comfortable leaving comments 😆
