### ISSUE TITLE
[css-values-4] Calc notation - Exercise 28 - typo

### ISSUE THREAD

**Issue by mateitudor** [w3c/csswg-drafts#8108]
There's a typo right after Example 28: 'altho' → 'although'
https://drafts.csswg.org/css-values-4/#calc-func

**Comment by Loirooriol** [comment]
https://github.com/w3c/csswg-drafts/issues/5850#issuecomment-853458238 resolved to treat this as a typo indeed.

**Comment by fantasai** [comment]
Fixed, thanks for reporting. :)
