### ISSUE TITLE
[css-position-3] Update spec to match css-logical

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#811]
https://drafts.csswg.org/css-logical-props/#logical-prop
https://drafts.csswg.org/css-position-3/#logical-box-offsets-beaso

Both specs define different names for logical counterparts of top/left/right/bottom. I'd be nice to pick one.

I'd prefer the naming from css-logical-props since it's more consistent with other logical props.

**Comment by upsuper** [comment]
I agree that `offset-{inline,block}-{start,end}` is more consistent with the concepts defined in CSS Writing Modes spec.

**Comment by fantasai** [comment]
For sure. css-position needs to be updated, re-assigning.

**Comment by fantasai** [comment]
Edited in.
