### ISSUE TITLE
[selectors-4] Legacy `:` pseudo-element cannot appear before type/subclass selectors

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8122]
Chrome/FF seems to parse `:before#id` or `:before.class` as invalid (instead of valid and matching nothing) but I do not see on which part of the spec this is based.

  > *Pseudo-elements are featureless, and so can’t be matched by any other selector*

This does not make them invalid.

Legacy `:` pseudo-element syntax is defined in `<subclass-selector>` as a `<pseudo-class-selector>`.

  > `<compound-selector> = [ <type-selector>? <subclass-selector>* [ <pseudo-element-selector> <pseudo-class-selector>* ]* ]!`

Subclass selectors can appear in any order while still selecting the same set of elements, but this is not true for a pseudo-element specified with the legacy single `:` syntax.

Therefore I assume that `:before` must be handled as if it has been specified with `::before` and matched `<pseudo-element-selector>`. **If so, it may be helpfull to define it in the spec.**

A [similar confusion](https://github.com/w3c/csswg-drafts/issues/6425#issuecomment-907733117) occurred to me when parsing a `<color-stop-list>`, whose syntax requires two color stops but its grammar accepts an implicit color stop defining two stops with the same color.

**Comment by tabatkins** [comment]
The intent of the additional rule is to say that you can spell a few pseudo-elements with a single colon:

> The four [Level 2](https://www.w3.org/TR/CSS2/selectors.html#pseudo-element-selectors) [pseudo-elements](https://w3c.github.io/csswg-drafts/selectors/#pseudo-element) ([::before](https://w3c.github.io/csswg-drafts/css-pseudo-4/#selectordef-before), [::after](https://w3c.github.io/csswg-drafts/css-pseudo-4/#selectordef-after), [::first-line](https://w3c.github.io/csswg-drafts/css-pseudo-4/#selectordef-first-line), and [::first-letter](https://w3c.github.io/csswg-drafts/css-pseudo-4/#selectordef-first-letter)) may, for legacy reasons, be represented using the [<pseudo-class-selector>](https://w3c.github.io/csswg-drafts/selectors/#typedef-pseudo-class-selector) grammar, with only a single ":" character at their start.

I should probably write that out more clearly. I can just merge that into the grammar itself rather than putting it in prose.

**Comment by cdoublev** [comment]
Thanks, I am satisfied and happy that I do not have to implement a custom validation.
