### ISSUE TITLE
[css-cascade-5] Possible error in @import syntax

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#8123]
The `@import` rule syntax defines a type `<import-condition>` but the following grammar identifies a `<import-conditions>`.  I assumed that this is a typo.

https://github.com/w3c/csswg-drafts/blob/4eaebbdb68d04698ff994356ac1969351a9adfb1/css-cascade-5/Overview.bs#L142

**Comment by tabatkins** [comment]
Yup, it was. (And it was correct in Cascade 4, so I guess someone just didn't copy over the fix.) Thanks!
