### ISSUE TITLE
[css-text] allow line-height to accept aspect-ratio style values

### ISSUE THREAD

**Issue by scottkellum** [w3c/csswg-drafts#8129]
Unitless `line-height` is generally accepted as the best type of value for `line-height`, however this can sometimes be confusing for people to calculate from pixel-based mockups.

## Proposal

Allow `line-height` to accept ratio formatted values similar to `aspect-ratio`. This would let authors easily convert pixel based values to numbers without the need for `calc`. So if a mockup has a font size of `16px` and a line height of `20px`, the CSS author would be able to write `line-height: 20 / 16` instead of `line-height: calc(20 / 16)` or doing the math to write `line-height: 1.25`.

**Comment by Crissov** [comment]
This syntax most likely wouldn’t work with the `font` shorthand property, wherein: `<font-size> / <line-height> <font-family>`.

**Comment by scottkellum** [comment]
@Crissov yeah I wasn't expecting it to work there as that syntax is so specific in formatting.

**Comment by fantasai** [comment]
I really don't think that complicating the `line-height` syntax in order to avoid writing `calc()` around your calculation is appropriate here...
