### ISSUE TITLE
[css-color] `color-mod()` needs a "do not implement" notice

### ISSUE THREAD

**Issue by myakura** [w3c/csswg-drafts#813]
the syntax of [`color-mod()`](https://drafts.csswg.org/css-color/#funcdef-color-mod) currently is:

```
color-mod() = color( [ <color> | <hue> ] <color-adjuster>* )
```

does that mean `color-mod()` overrides `color()` or it was just leftouts from renaming?

**Comment by svgeesus** [comment]
Just hasty renaming.

color-mod needs a new syntax and, possibly, a new name. Meanshile it needs a do-not-implement notice on that section.

**Comment by Crissov** [comment]
A lot of use cases could be solved if `<color>` could be used within `calc()`.

    color-mod(blue w(+ 20%) s(+ 20%))
    calc(blue + hwb(0 20% 0) + hsl(0 20% 0))

**Comment by svgeesus** [comment]
> A lot of use cases could probably be solved if <color> could be used within calc()

Agreed. Authors are already used to calc, so extending it to do color math the same as it does length math now, is an interesting way forward.

**Comment by jonathantneal** [comment]
> color-mod needs a new syntax...

What constitutes this need? Understanding that will make it easier for others to help.

**Comment by jonathantneal** [comment]
@Crissov, your calc syntax fascinates me. I’m trying to imagine how it would handle blending, especially in different colorspaces. Can you imagine how that would look, or do you think at that point calc would fall short?

**Comment by sindresorhus** [comment]
> What is the reason for this need? Understanding that will make it easier for others to help.

Is anyone able to answer this?

**Comment by svgeesus** [comment]
The old syntax has a lot of issues. It is cumbersme and people report difficulty understanding it. It is not perceptually uniform, being tied to sRGB and HLS colorspace. It is device dependent. It does not take into account wide gamut displays and there is no defined result while using them.

**Comment by jonathantneal** [comment]
Thanks, @svgeesus! Let me see if I understand your responses.

> It is not perceptually uniform.

This refers to the [color adjusters](https://www.w3.org/TR/css-color-4/#typedef-color-adjuster)? These adjusters change the channels of RGB, HSL, and HWB. For instance, `red()` adjusts a channel of s**R**GB, while `saturation()` adjusts a channel of H**S**L. However, as far as our minds perceive color, adjusting channels in these spaces produces unexpected results.

> It is device dependent.

This refers how we can’t profile colors without things like [`color()`](https://drafts.csswg.org/css-color/#icc-colors). I’m less sure about this one.

> It does not take into account wide gamut displays and there is no defined result while using them.

This is about not having a good color space or syntax for producing or manipulating all the perceivable colors that newer devices can now display. I’m much less sure about this.

How’d I do? I’m okay with success or failure. One means I might help others. The other means I might learn. 😉

**Comment by svgeesus** [comment]
Closing as all the color-mod stuff is now removed (well, commented out). Just removed the one remaining dangling reference (changes section).
