### ISSUE TITLE
[scroll-animations-1] Are timeline names tree-scoped?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#8135]
I initially thought "yes", but then https://drafts.csswg.org/css-scoping/#shadow-names seemed to only apply to "global names" (i.e. names created by at-rules), which is not quite the case for scroll timeline names.

There's a discussion in https://github.com/w3c/csswg-drafts/issues/7916 in relation to anchor/CQ names, which seems to expect that names (also non-"global" names) are tree-scoped by default?

Either way, it would be good to state it explicitly.

**Comment by fantasai** [comment]
Last time we discussed it, we decided that timeline names would be scoped across the flattened tree: [see minutes](https://lists.w3.org/Archives/Public/www-style/2022Aug/0016.html)

Lmk if you think we should reconsider for some reason

**Comment by bramus** [comment]
Discussion continued in #8192?

**Comment by flackr** [comment]
I'm not sure what to do about this issue, it seems like it was resolved in #7047 (as mentioned by @fantasai above https://github.com/w3c/csswg-drafts/issues/8135#issuecomment-1341721478 ) and there is a separate issue as mentioned by @bramus https://github.com/w3c/csswg-drafts/issues/8135#issuecomment-1400561093 . Do we close this and leave it to those other issues?

**Comment by andruud** [comment]
This is not the same issue as #8192. That affects anonymous timeline lookups as well (`scroll()`), while this does not. Not having tree-scoped timelines does not match @tabatkins' most recent thinking in https://github.com/w3c/csswg-drafts/issues/7916 in my opinion. However, if we're still sure about the https://github.com/w3c/csswg-drafts/issues/7047 decision, then I'm happy to close this issue. Tree-scoped names are painful to implement anyway.
