### ISSUE TITLE
[css-view-transitions-1] Improve spec readability

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#8143]
> View Transitions is a set of API that allow DOM changes to smoothly animate between states.

APIs*

But what I'm reading in the explainer is that it's a way to animate across a lot of node tree mutations at once.

cc @jakearchibald

**Comment by jakearchibald** [comment]
I'm going to take a pass on the spec and add loads of non-normative stuff to hopefully improve readability.

> But what I'm reading in the explainer is that it's a way to animate across a lot of node tree mutations at once.

Couldn't they be said to be two different states? Two states can differ by many tree differences, style differences etc etc.

**Comment by annevk** [comment]
Thanks!

What is the state of a "DOM change"? I think you can say that a node tree is in a particular state, sure, though this is not something the DOM standard does. The DOM doesn't directly store all style information so I'm not sure that would be captured.

**Comment by jakearchibald** [comment]
Feels like the same root issue as #8144

**Comment by annevk** [comment]
Partially, but I think the wording is confusing as well. I don't think you can say that a change has state.

**Comment by jakearchibald** [comment]
Maybe we're reading the word 'state' differently.

The intent here is that the document is in a particular state. Then a change is made, resulting in the document being in some different state.

So, the document has undergone a "state change". The 'update' created the difference between those states by altering the tree/styles/etc.

Feels like, here and #8144, we're looking for a word that communicates that the document model can change, and that it was in some state/form/shape/structure before, and now it's in some different state/form/shape/structure.

**Comment by annevk** [comment]
I understand the intent, but reading that sentence it doesn't convey that to me.

The sentence suggests it's an API that allows DOM changes to do something. What can DOM changes do? They can animate between states. But that's not what this is. DOM changes cannot do anything.

**Comment by annevk** [comment]
Yeah, that looks good. Was struggling myself to come up with that wording.

**Comment by jakearchibald** [comment]
I'll look out for other stuff like that as I update it for readability. That section in particular will change a lot.

**Comment by jakearchibald** [comment]
Renaming this to capture a wider job of improving spec readability via:

- [ ] More detailed intro, detailing phases of a transition. Include links to 'entry points', as in where the process starts.
- [ ] Include a note at the start of each algorithm / section, summarising its purpose (unless it's really obvious)
- [ ] Add domintro sections for the API
- [ ] Add diagrams to other sections where appropriate

**Comment by jakearchibald** [comment]
I think this is complete. @annevk does it look better to you?

- [Revamped intro](https://drafts.csswg.org/css-view-transitions-1/#intro) including [high-level lifecycle](https://drafts.csswg.org/css-view-transitions-1/#lifecycle), and [video examples](https://drafts.csswg.org/css-view-transitions-1/#examples).
- Improved [non-normative sections throughout](https://drafts.csswg.org/css-view-transitions-1/#view-transition-pseudos), including [domintro sections](https://drafts.csswg.org/css-view-transitions-1/#ref-for-dom-viewtransition-updatecallbackdone%E2%91%A0), and [diagrams](https://drafts.csswg.org/css-view-transitions-1/#capture-the-image-algorithm).
- Reviewed naming and grouping of [algorithms](https://drafts.csswg.org/css-view-transitions-1/#algorithms).

**Comment by khushalsagar** [comment]
Friendly ping @annevk. Just checking if there is more work to be done here or we can close the issue.

**Comment by annevk** [comment]
I think this can be closed, yeah. In particular given #8574.
