### ISSUE TITLE
Change flex direction, after the flex container wraps

### ISSUE THREAD

**Issue by manuelmeister** [w3c/csswg-drafts#8153]
I often come across the requirement to grow a flex item, but only If the flex container wraps:

<img width="400" alt="Two states: 1. single line wide flex container with space between the two items. 2. two lines and both flex items grow to full width" src="https://user-images.githubusercontent.com/3001985/204753313-a85f2457-3399-4124-b038-e51e77169622.png">

Usually this comes up with buttons (e.g. submit & cancel) that should be full width, if they are not on one line.

Both currently possible "workarounds" are not desired:
<img width="400" alt="Two possible but not desired workarounds: 1. Flex grow on the items at all times/breakpoints. 2. Non-grow flex items, one on the left and one on the right on a separate line" src="https://user-images.githubusercontent.com/3001985/204753343-6be72ab2-9934-4418-af0c-8b0974541739.png">

Also if there are more than two items. Then it should wrap as well.
<img width="400" alt="Bildschirmfoto 2022-11-30 um 10 15 39" src="https://user-images.githubusercontent.com/3001985/204755720-d355e40f-9c67-4d4c-b7b9-e708e957fb83.png">

I think one way to solve this could be:
```css
flex-wrap: wrap-column;
/* or probably better */
flex-wrap: wrap-direction;
```

This would make the direction of the flex container change upon wrap.

**Comment by ByteEater-pl** [comment]
A general mechanism could be a `::single-line` pseudo-element accepting a subset of properties. Not a pseudo-class, as that wouldn't allow the subset to be proper.

**Comment by manuelmeister** [comment]
@fantasai I imagine people wanting more than just flex-direction.
But I don't want a circular condition issue (like the [`position:sticky` `::stuck` problem](https://github.com/w3c/csswg-drafts/issues/1656))

I realized, this issue is a duplicate of #6366 (which I opened myself 🤦🏼‍♂️)
