### ISSUE TITLE
[css-transitions-2] Specify the phase to use for dispatching events when there is no target effect

### ISSUE THREAD

**Issue by mantaroh** [w3c/csswg-drafts#816]
https://drafts.csswg.org/css-transitions-2/#event-dispatch

 If Web Animation has no target effect, target effect end will be zero, and phase won't be idle. [1]
 So behavior will different from Web Animasions.

[1] https://w3c.github.io/web-animations/#updating-the-finished-state

I think that we will need to be consistent each specification.

 We can treat as 'After' phase in this situation, however,
 Transition can't dispatch correctly following case:

```javascript
   transition.cancel();       // make idle phase
   transition.effect = null;  // make after phase
```

 Above example, we will receive 'transitioncancel', 'transitionrun', 'transitionstart', 'transitionend',
 since phase will change from Idle to After.

 I think we will need to change phase based on current time.

 For example:
  If we cancel the animation, current time will be unresolved, since start time is unresolved.
  So we should set previous phase to idle when current time is unresolved.
  i.e. I think that we will need to change the specification as follow:
```
   If the transition has no target effect,
    If current time is unresolved, the transition phase is 'idle'.
    If current time is less than zero, the transition phase is 'before'.
    Otherwise, the transition phase is 'after'.
```

@birtles 
How do you think about this change?

**Comment by birtles** [comment]
Fixed by https://github.com/w3c/csswg-drafts/commit/c60bcce2202954da486abc2a373b7242409077d1
