### ISSUE TITLE
[css-images] Can't use stripes() as an <image>

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#8161]
https://drafts.csswg.org/css-images-4/#stripes

> If used generically as an [`<image>`](https://drafts.csswg.org/css-images-4/#typedef-image), the painting area is the height of the concrete image size.

This was written when `<1d-image>` was proposed as an `<image>`. This idea was later dropped, so the sentence above doesn't make sense.

**Comment by MrBirb** [comment]
@Loirooriol I cannot find that paragraph anymore. Looks like it was removed.

**Comment by Loirooriol** [comment]
Removed in a71367ac45bd15fbb1727ce7691bb7abee6e0010.
