### ISSUE TITLE
[css-images] Typo: two image

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#8162]
https://drafts.csswg.org/css-images-4/#interpolating-1d-images

> If the two image satisfy both constraints

Should be image***s***

**Comment by MrBirb** [comment]
@Loirooriol I believe this was fixed

**Comment by Loirooriol** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/c5a7edb3a0ee9ec9c02c60879ed0b72700d92c98.
