### ISSUE TITLE
[css-color] Add industry standard color names

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#817]
Similar to #303, add other [naming systems](https://drafts.csswg.org/css-color/#icc-colors), e.g. RAL and HKS, if their licenses allow this.

See also my [message to www-style](https://lists.w3.org/Archives/Public/www-style/2016Jul/0066.html) from 27 July 2016.

**Comment by Crissov** [comment]
For [RAL](http://www.ral-farben.de/content/application-help/all-ral-colours-names.html), this would suggest `color(RAL /* … */)`. 

The *RAL Design* sub-system is an alternative (HCL) notation of [LCH colors](https://drafts.csswg.org/css-color/#specifying-lab-lch), as it seems. So it probably makes no sense to introduce a separate syntax for this, although it would be possible.

    RAL <hhh> <ll> <cc> → lch(<ll> <cc> <hhh>deg)
    color(RAL "000 15 00") … color(RAL "360 92 05")
    color(RAL 0deg 15 00) … color(RAL 360deg 92 05)

The original *RAL Classic* sub-system would work with 4-digit `<<number>>`, but it also has localized names:

    color(RAL 1000) … color(RAL 9023)
    color(RAL "1000") … color(RAL "9023")
    color(RAL "green beige") … color(RAL "pearl dark grey")
    color(RAL "Grünbeige") … color(RAL "Perldunkelgrau")

The *RAL Effect* sub-system is based on a 3-digit number and another character (a digit or the letter `M`) , conventionally concatenated with a hyphen `-`. There are several ways this could be mapped to `color()`.

    color(RAL "110-1") … color(RAL "870-M")
    color(RAL 110 "1") … color(RAL 870 "M")
    color(RAL 110 1) … color(RAL 870 M)
    color(RAL-1 110) … color(RAL-M 870)

Similarly, *RAL Plastics*, is just Classic or Design with an added `-P`. This may constitute a reason for not using `lch()` for Design.

    color(RAL "1000-P") … color(RAL "9016-P")
    color(RAL-P 1000) … color(RAL-P 9016)
    color(RAL "000 15 00-P") … color(RAL "360 70 15-P")
    color(RAL-P 0deg 15 00) … color(RAL-P 360deg 70 15)

**Comment by grorg** [comment]
In my opinion, the point of the color() function is mostly about allowing color-spaces. Adding more naming systems is only going to be useful if:

- all the browsers implement it
- the system produces colors that are visible to the majority of users

We currently have that with our AdobeRGB and Display P3 predefined spaces, to some extent. Do these other systems provide the same?

**Comment by Crissov** [comment]
Every once in a while, CSS needs to add features that are not primarily intended for interactive screen-based webbrowsers.

**Comment by grorg** [comment]
This is already supported. You'd just need to provide an ICC profile for your naming scheme. Of course, you'd then need to get the browsers to support both getting external profiles and whatever the parsing of the arguments requires (you're allowed string arguments to the color function).

**Comment by Crissov** [comment]
Does this resolve #303 then, too?

**Comment by Crissov** [comment]
The WG resolution conflicts somewhat with [inline issue 9](https://drafts.csswg.org/css-color/#predefined):

>  Decided at San Francisco to add a larger set of common predefined spaces like AdobeRGB, ProPhoto RGB, and so on. Also coated and uncoated swop, etc, etc.

A palette of named (LCH) spot colors may not constitute a color space of its own, but the first parameter to `color()` is not restricted to color space names anyway, even if &ndash; as @grorg believes &ndash; that was the main reason for this notation.

The specification should probably include an informative example of *how* this was possible, i.e. the first example in [11. Profiled, Device-dependent Colors](https://drafts.csswg.org/css-color/#icc-colors) should **include a named color** from an ICC profile. 

Also, since browsers do not support external ICC profiles &ndash; but maybe PDF generators do or will &ndash; you cannot &ldquo;already do this&rdquo;, which is the very reason for `rec2020` and `image-p3` being predefined.

**Comment by svgeesus** [comment]
Agreed that some examples of using named colors should be added. And yes, that was the intent of adding them - instead of a centralized list of color names, allow anyone to provide their own names. That also conveniently does not put the implementation in the critical path when some  collections of names have licensing restrictions

**Comment by Crissov** [comment]
Sadly, ICC profiles are not as easy to create as a CSS file, so someone but not "anyone" could put their list up on the web for others to reuse.

**Comment by tabatkins** [comment]
When the "someone" in question is the steward of an industry-standard color profile, they can definitely produce an ICC profile file (or can employ someone who can). It's almost certain they already have, since ICC profiles are industry standards too, and used all over the place.
