### ISSUE TITLE
[css-counter-styles-3] Setting `CSSCounterStyleRule.name` should ignore symbolic counter styles

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8186]
If I am not mistaken, [`CSSCounterStyleRule.name`](https://drafts.csswg.org/css-counter-styles-3/#dom-csscounterstylerule-name) should ignore symbolic counter styles, because they are invalid.

> The keywords `decimal`, `disc`, `square`, `circle`, `disclosure-open`, and `disclosure-closed` are valid `<counter-style-name>`s, but are invalid when used here to name a counter style rule; doing so makes the rule invalid (related issue: #3584).

https://drafts.csswg.org/css-counter-styles-3/#the-counter-style-rule

```diff
-  If the value is not "decimal", "disc", or "none", replace the associated rule’s name with an identifier equal to the value.
+  If the value is not "decimal", "disc", "square", "circle", "disclosure-open", "disclosure-closed", or "none", replace the associated rule’s name with an identifier equal to the value.
```

**Comment by Loirooriol** [comment]
Seems that Blink and Gecko already check that.
Would be better to define the list in a single place, and refer to it from the other place.

**Comment by tabatkins** [comment]
Agreed, that was an oversight in updating. I've switched to defining the list as a term, and referencing it in both places.

Agenda+ to confirm the edit.

**Comment by vitorroriz** [comment]
> Seems that Blink and Gecko already check that. Would be better to define the list in a single place, and refer to it from the other place.

Sounds good. WebKit also checks it.
