### ISSUE TITLE
[scroll-animations] Mention design constraint of not blocking scrolling?

### ISSUE THREAD

**Issue by RByers** [w3c/csswg-drafts#819]
Depending on exactly how your interpret it, the [avoiding cycles](https://wicg.github.io/scroll-animations/#avoiding-cycles) section implies that scrolling may need to block on JavaScript / layout.

For blink (and probably also at least Edge) that is a non-starter.  Ensuring scrolling never blocks on the main thread has been our #1 scroll performance effort for several years, we're unwilling to allow that without an explicit scary-sounding opt-in API and a mitigation strategy (eg. "intervention" that applies on  sites whose performance isn't good enough to permit a reasonable user experience on low end phones).

Is there agreement on this non-blocking design constraint for scroll animations?  If so, perhaps it's worth mentioning in the introduction somewhere?

/cc @majido @flackr @shans

**Comment by birtles** [comment]
Should this be filed over at WICG where the spec currently lives?
https://github.com/WICG/scroll-animations/issues

**Comment by RByers** [comment]
Duh, yes - sorry, [done](https://github.com/WICG/scroll-animations/issues/9).  I just blindly used the "GitHub issues" link which was wrong.
