### ISSUE TITLE
[css-anchor-position-1] Implicit anchor note should be more general

### ISSUE THREAD

**Issue by mfreed7** [w3c/csswg-drafts#8191]
The [draft spec](https://drafts4.csswg.org/css-anchor-1/#implicit-anchor-element) has this note:

> Note: The Popup API, for example, defines an [implicit anchor element](https://drafts4.csswg.org/css-anchor-1/#implicit-anchor-element) for a popup—the element that the popup is attached to.

Three observations/requests:
1. Please rename `Popup` -> `Popover`.
2. Please link to the Popover [explainer](https://open-ui.org/components/popup.research.explainer) or [spec PR](https://github.com/whatwg/html/pull/8221), whichever you prefer.
3. Most importantly: I think the Popover `anchor` attribute is just the first example. I'd actually like to expand that to all HTML elements: I don't see a reason why any element couldn't use an `anchor` attribute to establish an implicit anchor element. Or maybe there is a good reason?

**Comment by mfreed7** [comment]
A few updates:

- The draft spec is now here: https://drafts.csswg.org/css-anchor-position-1
- The rename to "Popover" is roughly complete there.
- The spec doesn't seem to need to link to the Popover spec any longer, so that's "complete" also.
- The only remaining thing is point number 3 above about the `anchor` attribute. The spec now defines an ["implicit anchor element"](https://drafts.csswg.org/css-anchor-position-1/#implicit-anchor-element), and [this HTML spec PR](https://github.com/whatwg/html/pull/9144) makes the link between `anchor` and "implicit anchor reference". So perhaps nothing more needed for the CSS spec either. 

I suppose given the above, this issue reduces to adding an example (using the `anchor` attribute) in place of this existing TODO:

> TODO fill in new popover-related details. This makes the declared element the [implicit anchor element](https://drafts.csswg.org/css-anchor-position-1/#implicit-anchor-element) for the element with the attribute.

**Comment by tabatkins** [comment]
k, I've rephrased the example to be more explicit about just wanting an example with the "anchor" attribute. I'll close the issue, since the rest is handled already.
