### ISSUE TITLE
[scroll-animations-1] Timeline lookup should probably not use flat tree

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#8192]
It was [strongly argued](https://github.com/w3c/csswg-drafts/issues/5984#issuecomment-1059602923) (by @tabatkins) that container queries should _not_ look up the flat tree, to avoid the presence of a container inside the shadow to become an implicit part of the API contract. I don't see why scroll containers should be any different.

Should probably follow container queries and specify that we search shadow-including ancestors (inclusive).

**Comment by fantasai** [comment]
While I 100% agree for container queries, I'm less convinced for this case. We're looking at the nearest scroll container because that's what determines whether you're visible!

I can easily imagine some kind of web-component that implements fancier scrolling behavior of some kind, that we wouldn't want to exclude here. Right?

**Comment by ydaniv** [comment]
I tend to agree with @fantasai on both perspectives. If we do restrict it we lose the ability described above.

The only case I can think of is perhaps if author expected to get an `inactive` timeline for a container inside the shadow but `nearest` continued to look up in the host.
For `ScrollTimeline` that can be mitigated with a named timeline.

`ViewTimeline`s, however, always look for nearest scroll ancestor:

> View progress timelines are segments of a scroll progress timeline that are scoped to the scroll positions in which any part of the associated element’s [principal box](https://drafts.csswg.org/css-display-4/#principal-box) intersects its nearest ancestor scrollport

IMO it should come down to whether we want to allow the author a way of scoping this case.

**Comment by andruud** [comment]
Fine to spec it as flat-tree ancestors, but currently the spec just says "nearest ancestor", which is ambiguous.

**Comment by fantasai** [comment]
@andruud I shifted the note about using the flat tree from https://drafts.csswg.org/scroll-animations-1/#timeline-scope and generalized it into https://drafts.csswg.org/scroll-animations-1/#other-specs as

> Like most operations in CSS besides [selector](https://drafts.csswg.org/selectors-4/#selector) matching, features in this specification operate over the [flattened element tree](https://drafts.csswg.org/css-scoping-1/#flat-tree).

Let me know if this works for you, or if you would like some other clarifications.

**Comment by andruud** [comment]
@fantasai Works for me, thank you. :-)
