### ISSUE TITLE
[scroll-animations-1] Animation.getCurrentTime is easily confused with Animation.currentTime

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#8201]
I think it's confusing to have both `currentTime` and `getCurrentTime`.

Would it be possible to:

1. ~~Move this to the `ScrollTimeline` interface,~~ (Update: I see now that this is proposed to be used for `DocumentTimeline` too--I still don't quite follow the use cases but assuming we want to do that, I guess it should stay on `AnimationTimeline`)
2. Rename it to `getCurrentTimeForRange`, _and_
3. Make the `rangeName` argument non-optional

?

**Comment by fantasai** [comment]
`getCurrentTime` is essentially a replacement for `.currentTime` that returns the same concept, but has more expressivity:  So I think it makes sense to keep the same name.

**Comment by birtles** [comment]
> `getCurrentTime` is essentially a replacement for `.currentTime` that returns the same concept, but has more expressivity: So I think it makes sense to keep the same name.

I don't think we shouldn't do that. We'll confuse authors unnecessarily. We can't deprecate `currentTime` and for the overwhelming majority of use cases it's the right choice. We should be encouraging users to continue using `currentTime` for the sake of compatibility.

For users that need a time for a range, there's `getCurrentTimeForRange` for which the function name spells out what the string argument represents. (If we really must use `getCurrentTime` then it needs to take a property bag, not a string.)

**Comment by birtles** [comment]
I'm afraid I'm still opposed to the current naming.

I don't think ranges are a fundamental concept. The overwhelming majority usage of the API will continue to be for time-based animations and I think we should bias towards that.

- Adding `getCurrentTime` makes using the API harder in the common case. When your editor suggests both `currentTime` and `getCurrentTime` how do you know which one to choose? You have to look them up to find out what their (subtle) distinction is.
- Generally, authors should prefer using `currentTime` because it is more backwards compatible.

If we _must_ have `getCurrentTime` because we expect it to be useful for non-range cases then we really should use a property bag. Doing so is necessary to:

- Make the code readable. How on earth could you guess that the single string argument to `getCurrentTime` represents a range otherwise?
- Make the API extensible. If we're going with something as generic as "get current time", then we'll no doubt want to add further conditions to that query in future and having an API that switches between positional arguments and property bags is an unnecessary wart.

Now that TS/JS language servers are able to automatically refactor positional arguments into property bags, property bags have become much more common so I believe this approach is also idiomatic.

**Comment by bramus** [comment]
After playing with the API a bit, I follow what Brian is saying and think `getCurrentTimeForRange` makes most sense, as that’s what the function essentially does. Other names didn’t cover what the function does.

An alternative name that came up was `getProgressForRange` but I see how reusing `CurrentTime` in the name makes sense because `currentTime` also returns a progress for non-time-based timelines.

Also fine with the property bag approach. To be clear, that would then, for example, be `getCurrentTime({ range: `cover` })`?

**Comment by flackr** [comment]
What is the use case for this API? What would a developer do given the "time" of various phases on the timeline?

Given our discussion in #8669 it seems the thing @bramus would like would be best provided by a more convenient way to get a particular animation's progress.

**Comment by LeaVerou** [comment]
Per the TAG Design Principles, [optional and/or primitive arguments should be accepted through dictionaries](https://w3ctag.github.io/design-principles/#prefer-dictionaries), not positional arguments.
In this case, this would mean `getCurrentTime({ rangeName: "cover" })` (or perhaps `getCurrentTime({ range: "cover" })`). This also allows `.getCurrentTime()` without arguments to continue being equivalent to `.currentTime`, as it should be.

**Comment by yoavweiss** [comment]
Let me know if this requires a separate issue, but I was surprised to see that `getCurrentTime` returns a CSSNumericValue, rather than a [DOMHighResTimestamp](https://w3c.github.io/hr-time/#dom-domhighrestimestamp). I'm guessing that it'd also be worthwhile to hook up its processing/clamping to [current high resolution time](https://w3c.github.io/hr-time/#dfn-current-high-resolution-time)

**Comment by flackr** [comment]
> Let me know if this requires a separate issue, but I was surprised to see that `getCurrentTime` returns a CSSNumericValue, rather than a [DOMHighResTimestamp](https://w3c.github.io/hr-time/#dom-domhighrestimestamp). I'm guessing that it'd also be worthwhile to hook up its processing/clamping to [current high resolution time](https://w3c.github.io/hr-time/#dfn-current-high-resolution-time)

Scroll timelines don't produce millisecond-based times, so we decided that we should future proof APIs with a CSSNumericValue which can represent the difference between milliseconds and percentages. We should still apply the same clamping to those millisecond values in the CSSNumericValue as we do for DOMHighResTimestamp.
