### ISSUE TITLE
[scroll-animations-1] The heading "Reporting Timeline Range Progress: the getTime() method" refers to `getTime` but the method name is `getCurrentTime`

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#8203]
https://drafts.csswg.org/scroll-animations-1/#named-range-getTime

**Comment by bramus** [comment]
I see this got fixed in a commit @fantasai pushed, thus closing issue.

Naming discussion itself is tracked in https://github.com/w3c/csswg-drafts/issues/8201
