### ISSUE TITLE
[scroll-animations-1] Define how the `source` member of a `ScrollTimeline` corresponding to a `scroll()` timeline is updated

### ISSUE THREAD

**Issue by birtles** [w3c/csswg-drafts#8204]
https://drafts.csswg.org/scroll-animations-1/#dom-scrolltimelineoptions-source

I might be misunderstanding how all this works but if I define an anonymous scroll timeline in CSS using the `scroll()` notation, then inspect the corresponding `Animation` object's `timeline` I assume I can inspect the `ScrollTimeline.source` to see what element `root` or `nearest` resolved to.

If I then modify the CSS of an ancestor element such that `root` or `nearest` resolve to a different element, is the same `ScrollTimeline` object updated? If so do we need to specify a procedure for updating the source of a `ScrollTimeline`? Or is a new `ScrollTimeline` minted? In either case we'd need to define it because the result would be observable.

**Comment by fantasai** [comment]
This is a good question, and imho it would make the most sense to mint a new `ScrollTimeline`. @flackr ?

**Comment by bramus** [comment]
Hmm, tricky. I guess there’s something to say for both, but leaning towards updating only the `source` as it essentially still is the same `scroll()` definition.

**Comment by ydaniv** [comment]
Changing `source` will also change `currentTime` and may render the timeline _active/inactive_. Not sure I understand the specifics of minting a new `ScrollTimeline`, but we'll need to reflect more change than just the `source`.

**Comment by fantasai** [comment]
@bramus That also brings up the question of, if I have multiple `scroll()` functions and a named timeline all referencing the same scroll container, do they share the same identity?

**Comment by flackr** [comment]
FYI @kevers-google

In the implementation, we currently use the same timeline instance and it resolves the actual source and returns that from the instance - but it is impossible to construct a JS scroll timeline which refers to the nearest ancestor. From the JS side this doesn't seem too different from how animation timing is updated from CSS except when you updateTiming from the JS side overriding it. Each ScrollTimeline is currently a different instance, especially as different elements have different reference elements in the internal scroll timeline details. The owning element concept also feels similar: https://drafts.csswg.org/css-animations-2/#owning-element - an internal detail that affects the JS behavior but is not exposed.

**Comment by flackr** [comment]
My proposal would be that we spec the chromium behavior. That similar to an animation object, a timeline object is created for the element which defines it and that same object is used until an explicit style change causes us to create a new one.

The source is computed when you ask for it (like computed styles). Normally this occurs once per frame when we update the time but querying from script can result in freshening style and layout to determine the current source. Of course it may be more consistent if we allow the source to be stale just as the time returned is the one most recently used and just as the current time of an AnimationTimeline is the time when the current frame was generated - not the current time.

**Comment by fantasai** [comment]
@flackr I committed https://github.com/fantasai/csswg-drafts/commit/947f69bc456562ac5b1ca451ae8e50cffdbb7010 and filed https://github.com/w3c/csswg-drafts/pull/8541 as a PR because I wasn't quite sure what exactly I should be speccing. Please have a look, and if it looks good rebase+merge and close out this issue. :)

**Comment by flackr** [comment]
Fixed by #8541.
