### ISSUE TITLE
[css-grid-3] Masonry - align-tracks / justify-tracks not defined sufficiently - has issues with spanning items

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#8208]
Unclear is `align-tracks` / `justify-tracks` is a good design see previous issue:
https://github.com/w3c/csswg-drafts/issues/8207

However currently underspecified. Specifically:
1. Unclear how to deal with items which are spanning multiple tracks. I played very quickly with this in Firefox and unclear what was occuring.
2. "stretch" needs to be defined precisely. Specifically you can get into an over-constrained situation with items having max-height specified on them. How to you distribute the excess space when one item hits its max?
3. From talking with web-developers the fact that flexbox flexes based on the content box was confusing, and likely shouldn't be carried forward to other modes. Grid doesn't do this - we shouldn't do this for masonry as well.
4.  Increasing auto-margins isn't how flexbox works, should likely rely on flexbox behaviour here?

Edit - a simple example of the spanning issue: https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=11095

**Comment by lukewarlow** [comment]
These features are being dropped https://github.com/w3c/csswg-drafts/issues/8207#issuecomment-1747805578

**Comment by nt1m** [comment]
I'll close this issue since the feature was removed.
