### ISSUE TITLE
[css-content] Content spec refers to undefined keyword "inhibit"

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#822]
The css-content spec says [the following, about the `normal` value for  the `content` property](https://drafts.csswg.org/css-content/#normal):
>     For an element, this computes to 'contents'.
>     For '::before' and '::after', this computes to 'inhibit'.

But `inhibit` is never defined anywhere.

I think this means to say `none`, rather than `inhibit`?  (The prose about `none` does mention the word "inhibit" several times, so I'm wondering whether this keyword used to be called `inhibit` and was renamed to `none`, and this is just one straggling version of the old name.)

**Comment by dauwhe** [comment]
Yeah, it's a leftover from the 2003 draft. Fixed by @tabatkins via b018082.

**Comment by dholbert** [comment]
Thanks! Looks like it is indeed fixed -- though, the replacement `none` value isn't getting correctly linkified (here or elsewhere in the spec).  I filed #874 on that.
