### ISSUE TITLE
[selectors-4] Clarify :blank

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8220]
See https://github.com/whatwg/html/issues/8451#issuecomment-1349868043

> Rule of thumb: “if it always submits, and would do so with an empty string, it's `:blank`; if it sometimes submits, and is set to not submit, it's `:blank`”. Action buttons (rather than toggle buttons that represent a state) such as `<input type=reset>`, `<button>`, `<input type=submit>`, etc., never match `:blank`.

**Comment by tabatkins** [comment]
Changed the :blank example into a note that reproduces the guidance from the HTML issue (which we expect HTML to adopt).
