### ISSUE TITLE
[css-color-5] Clarification of rgb() syntax

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#8231]
In css-color-5, the third syntax entry indicates that the rgb function can take a mixture of numbers and percentages for the r, g, and b values.  Is that the case? The previous examples seem to indicate that it needs to be in one format or the other.

https://github.com/w3c/csswg-drafts/blob/19e56ae5f3f2cc55dc35df62b0003403ca76b602/css-color-5/Overview.bs#L911-L914

**Comment by svgeesus** [comment]
Previously, `rgb()` required all arguments to be of the same type. The grammar for this was changed by @tabatkins to allow a mixture of types, but only for Relative Color Syntax.

There has been discussion to backport this:

1. to the rest of the `rgb()` and `rgba()` productions in CSS Color 5
2. to the `rgb()` and `rgba()` productions in CSS Color 4.

This requires buy-in from implementers, and would only apply to the new (comma-less) syntax ot the legacy (comma) syntax.

**Comment by svgeesus** [comment]
Related:

 - https://github.com/w3c/csswg-drafts/issues/7721
 - https://github.com/w3c/csswg-drafts/issues/7968

**Comment by GPHemsley** [comment]
See also:
* #7900

**Comment by LeaVerou** [comment]
Yeah, there is no actual reason to force all arguments to be of the same type, and for color formats with less straightforward mapping of percentages to numbers, it could be useful to only specify certain components with percentages and others with numbers. I propose we drop this restriction for all color functions, and not just for RCS.

**Comment by tabatkins** [comment]
I allowed mixing in RCS because the channel variables happen to be percentages, but that's not obvious from the authored syntax and shouldn't restrict authors. That is, `rgb(from red, r, 127, 0)` looks perfectly reasonable, but technically it's mixing percentage and numeric arguments.

This argument doesn't extend to non-relative syntax, where the authored syntax is more obviously a percentage or a number for each argument.

That said, I definitely support loosening the restriction; it seems like a legacy constraint from an earlier age of CSS design.

**Comment by LeaVerou** [comment]
> I allowed mixing in RCS because the channel variables happen to be percentages

Unrelated to this issue, but they should be numbers, not percentages. I think in general in RCS we should always pick number if number is allowed for a component, as it's more flexible. Furthermore, the [actual spec](https://drafts.csswg.org/css-color-5/#relative-RGB) has this bizarre text:

> r, g, and b are all [<percentage>](https://drafts.csswg.org/css-values-4/#percentage-value)s or [<number>](https://drafts.csswg.org/css-values-4/#number-value)s that correspond to the [origin color’s](https://drafts.csswg.org/css-color-5/#origin-color) red, green, and blue channels after its conversion to sRGB. 

How can they be either percentages OR numbers, lol? What was I thinking when I wrote this? 🤣

**Comment by svgeesus** [comment]
The CSS Working Group just discussed ``[css-color-4] `rgba()` is legacy so does not support `none`. Right?``, and agreed to the following:

* `RESOLVED: non-RCS rgb() and hsl() can mix numbers/%s when using the modern syntax (space and slash, not comma).`

<details><summary>The full IRC log of that discussion</summary>
&lt;TabAtkins> chris: We have an old syntax which has commas for everything<br>
&lt;TabAtkins> chris: And a new which is space and slash<br>
&lt;astearns> ack chris<br>
&lt;TabAtkins> chris: We've added a bunch to that new syntax, like RCS<br>
&lt;TabAtkins> chris: But it used to be that everything had to be a % or everything a number, that's from CSS1<br>
&lt;TabAtkins> chris: In RCS you can mix them tho<br>
&lt;TabAtkins> chris: My proposal is that the modern syntax, only, allows mixing %s and numbers.<br>
&lt;TabAtkins> chris: Also the modern syntax can use 'none'. I'd also like to keep that restricted to the modern syntax.<br>
&lt;TabAtkins> chris: We have very good interop on what's currently specified<br>
&lt;TabAtkins> chris: People have argued that for clarity we should extend the capabilities to all syntaxes, but I think it's a bad idea - we have very solid interop as-is.<br>
&lt;TabAtkins> I'm totally fine with this.<br>
&lt;TabAtkins> chris: So proposed reoslution is we backport mixing number/% to the modern syntax of non-RCS rgb() and hsl()<br>
&lt;argyle> +1<br>
&lt;TabAtkins> astearns: Questions?<br>
&lt;TabAtkins> astearns: I assume this is okay with the issue commenters?<br>
&lt;TabAtkins> chris: There's one in the thread who had several suggestions but no strong opinion. Other than that, agreement in the thread.<br>
&lt;TabAtkins> RESOLVED: non-RCS rgb() and hsl() can mix numbers/%s when using the modern syntax (space and slash, not comma).<br>
</details>

**Comment by svgeesus** [comment]
via @danburzo:

> So I find a regex issue posted on a public Discord server. The task seems simple.
>    "Use regex to validate a CSS rgb() string"
> https://emnudge.dev/blog/perfect-rgb-regex/

_laughs in light despair_

**Comment by svgeesus** [comment]
> In css-color-5, the third syntax entry indicates that the rgb function can take a mixture of numbers and percentages for the r, g, and b values. Is that the case? The previous examples seem to indicate that it needs to be in one format or the other.

The legacy formats take one or the other; the modern formats allow a mixture.

**Comment by cdoublev** [comment]
Thanks for your edits.

> The grammar of the [modern color syntax](https://drafts.csswg.org/css-color-4/#modern-color-syntax) [`rgb()`](https://drafts.csswg.org/css-color-4/#funcdef-rgb) and [`rgba()`](https://drafts.csswg.org/css-color-4/#funcdef-rgba) functions are extended as follows:
>
> ```
>         rgb() =  rgb( [ from <color> ]? [ <number> | <percentage> | none]{3} [ / [<alpha-value> | none] ]? )
>        rgba() = rgba( [ from <color> ]? [ <number> | <percentage> | none]{3} [ / [<alpha-value> | none] ]? )
> <alpha-value> = <number> | <percentage>
>```

`w3c/reffy` will extract `rgb()` and `rgba()` value definitions from both CSS Color 4 and CSS Color 5, but it will only keep those of CSS Color 5 (above), whereas they are respectively defined with `[<legacy-rgb-syntax> | <modern-rgb-syntax>]` and `[<legacy-rgba-syntax> | <modern-rgba-syntax>]` in CSS Color 4.

The same problem applies to `hsl()` and `hsla()`. Basically, `w3c/reffy` will loose `<legacy-*-syntax>`.

The choices you made in your edits may be intentional, and the proper definitions can be hard-coded, as an exception. If not, I think the following changes would fix this problem:

> The grammar of the [`<modern-rgb-syntax>`](https://drafts.csswg.org/css-color-4/#typedef-modern-rgb-syntax) and [`<modern-rgba-syntax>`](https://drafts.csswg.org/css-color-4/#typedef-modern-rgba-syntax) functions are extended as follows:
>
> ```
> <modern-rgb-syntax> = rgb( 
>    [ from <color> ]? 
>    [ <number> | <percentage> | none ]{3} 
>    [ / [<alpha-value> | none] ]? 
> )
> <modern-rgba-syntax> = rgba( 
>   [ from <color> ]? 
>   [ <number> | <percentage> | none ]{3} 
>   [ / [<alpha-value> | none] ]? 
> )
>```

I removed the definition of `<alpha-value>` because it is already [defined](https://drafts.csswg.org/css-color-4/#typedef-alpha-value) in CSS Color 4 with mixed `<number> | <percentage>`.

Legacy color syntaxes should not allow to mix them, but I think this is a different problem (#8311) that could be fixed by replacing `<alpha-value>` by `<number>` OR `<percentage>` in the appropriate locations of `<legacy-rgb-syntax>` and `<legacy-rgba-syntax>`:

```
 <legacy-rgb-syntax> = rgb( <number>#{3,4} ) | rgb( <<percentage>>#{3,4} )
<legacy-rgba-syntax> = rgba( <number>#{3,4} ) | rgba( <<percentage>>#{3,4} )
```

**Comment by LeaVerou** [comment]
Thinking out loud, is there value in keeping these legacy syntaxes separate? Wouldn't it be easier for implementations if `rgb()` and `rgba()` are identical aliases of each other?

**Comment by svgeesus** [comment]
We already discussed that; there are a bunch of differences now (not just comma vs. space) between the legacy and modern syntaxes in CSS Color 4:

  https://w3c.github.io/csswg-drafts/css-color-4/#color-syntax-modern

and more in CSS Color 5, which adds RCS:

  https://w3c.github.io/csswg-drafts/css-color-5/#relative-colors

We also have excellent interop on the current legacy syntax, and scripts likely make assumptions about what syntax is allowed. So back-porting all this to the legacy syntaxes is a large change.

**Comment by svgeesus** [comment]
> If not, I think the following changes would fix this problem:

Yes, that would be better than saying it in prose.

**Comment by cdoublev** [comment]
Thanks again for the updates: definitions are correctly extracted from CSS Color 4 and 5.

I am not sure I was right about this in my previous comment:

  > Legacy color syntaxes should not allow to mix them, but I think this is a different problem (may be related: #8311) that could be fixed by replacing `<alpha-value>` by `<number>` OR `<percentage>` in the appropriate locations of `<legacy-rgb-syntax>` and `<legacy-rgba-syntax>`

In my mind, `<number>` and `<percentage>` cannot be mixed in all components, without distinction between color channels and alpha channel. The current definition of the legacy syntax says *components must be specified using either all-`<percentage>` or all-`<number>`, they can not be mixed* but further above, it says _**color** components are separated by commas_ (emphasize added on *color*).


But `rgb(0, 0, 0, 50%)` is valid in Chrome/FF. It seems there is no WPT testing mixing color components as `<number>` and alpha-value as `<percentage>` (or vice-versa).

Do you think *color* should be added before *components* in the sentence *components must be specified using either all-`<percentage>` or all-`<number>`, they can not be mixed*?

**Comment by svgeesus** [comment]
> Do you think color should be added before components in the sentence components must be specified using either all-<percentage> or all-<number>, they can not be mixed?

Yes.

**Comment by svgeesus** [comment]
@cdoublev is it all clear now?

**Comment by cdoublev** [comment]
Yes, it looks goot to me. Thanks!
