### ISSUE TITLE
[cssom-view] Define term “client window”

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#8239]
As a follow-up to Interop2022’s [Viewport Investigation Effort](https://github.com/web-platform-tests/interop-2022-viewport/), I’m filing this issue that came up.

In issue https://github.com/web-platform-tests/interop-2022-viewport/issues/17 it was noted that the term “client window” is used, but not specified.

We suggest to define this term in the spec.

**Comment by cvrebert** [comment]
Duplicate of #430
