### ISSUE TITLE
[css-shapes-1] ellipse() grammar gratuitously inconsistent with radial-gradient()

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#824]
The [`ellipse()` grammar defined in Shapes](https://drafts.csswg.org/css-shapes-1/#funcdef-ellipse) was clearly designed to *resemble* [the grammar of radial-gradient()](https://drafts.csswg.org/css-images-3/#funcdef-radial-gradient), but it's different in small but important ways, for no apparent reason.

In particular, the ellipse part of the `radial-gradient()` grammar is: `<extent-keyword> | <length-percentage>{2}`.  You either say something like "farthest-side", which defines an ellipse, or give lenpers for both axises.

On the other hand, the `ellipse()` function says `[ <extent-keyword> | <length-percentage> ]{2}?` - for *each axis*, you can either provide a keyword or a lenper. So you can do something like `ellipse(farthest-side closest-side)`, to make its width the amount necessary to hit the farthest horizontal side, and its height the amount necessary to hit the closest vertical side.  But you *can't* do `ellipse(closest-side)`.

Given the seniority of the `radial-gradient()` syntax, and the lack of major issues with it, I think we should converge on that as the grammar for `ellipse()`.

**Comment by AmeliaBR** [comment]
There's an additional inconsistency that also applies to the `circle()` function: only `-side` keywords are allowed, not `-corner` keywords.

Was there any reason for not allowing `circle()` and `ellipse()` shape functions to use `closest-corner` and `farthest-corner` to define radii?

**Comment by astearns** [comment]
@AmeliaBR `closest-corner` and `farthest-corner` did not seem necessary for `shape-outside` and `clip-path`, as using those for radii often creates a shape that extends outside the margin box. I'm not against allowing them for consistency's sake, but I don't know that they would get much use.

**Comment by AmeliaBR** [comment]
@astearns  The reference box for sizing a clip-path or shape-outside doesn't need to be the margin-box. A circle sized to the content box's corners could still fit within the margin box. And the shape functions may be adopted for other uses.

But regardless of the strength of use cases, I agree with Tab's original point that consistency is preferred.

**Comment by astearns** [comment]
I should have addressed this a few years ago. Sorry for the delay.

Adding the *-corner keywords should be fine.

My guess is it's still possible to change the `ellipse()` syntax to exactly match radial gradients. If we do that, there will be some breakage. It would be limited to instances of `ellipse()` where two keywords are used (which is likely very small), and the breakage would be limited to having someone's `shape-outside` or `clip-path` no longer apply (both have okay fallbacks).

BUT I think we could change `ellipse()` to allow either what's currently specified OR something matching a current radial gradient:

`<extent-keyword> | [ <extent-keyword> | <length-percentage> ]{2}?`

Then there would be no breakage, no one would get a surprise trying to copy a radial gradient ellipse into an `ellipse()`, we would get the two-keyword case (which is useful for creating ellipses that are the largest that can fit in a reference box), and we could decide whether to extend the radial gradient syntax to match (fully containing the ellipse is less useful there, but still could be good)

**Comment by astearns** [comment]
Hmm. If we allowed two keywords and both *-side and *-corner, then we'd have to define what it means when both keywords were *-corner. It's not immediately obvious to me what the resulting ellipse should be in those cases.

**Comment by AmeliaBR** [comment]
> If we allowed two keywords and both *-side and *-corner, then we'd have to define what it means when both keywords were *-corner. It's not immediately obvious to me what the resulting ellipse should be in those cases.

Oh, that's a good point. And may have been the reason the radial-gradient syntax only allows one keyword.

So the natural superset of the two syntaxes is one or two "side" keywords or lengths, _or_ one "corner" keyword. Which is rather more confusing.

**Comment by tabatkins** [comment]
I can assure you that's not why I wrote radial-gradient the way I did; I just happened to think of the ellipse/circle keywords as an automagical way to write the two sizes.

**Comment by astearns** [comment]
Given that `closest-corner` is defined to create an ellipse with the same aspect-ratio as `closest-side` that passes through the closest corner point we do something similar for the two-keyword form:

`X-corner Y-corner` creates an ellipse with the same aspect-ratio as `X-side Y-side` that passes through both corners

**Comment by tabatkins** [comment]
Agenda+ at @jakearchibald 's request

**Comment by jakearchibald** [comment]
Yay!

**Comment by cdoublev** [comment]
Follow-up on the recent change: is it intentional to not allow mixing an extent keyword and a length/percentage?

`<radial-extent>{1,2} | <length-percentage [0,∞]>{1,2}` vs. `[<radial-extent> | <length-percentage [0,∞]>]{1,2}`

**Comment by astearns** [comment]
Can you open a new issue on this followup, @cdoublev?
