### ISSUE TITLE
[css-animations-2] Define `<timeline-name>` with basic syntax

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8245]
There was a basic syntax for [`<timeline-name>`](https://drafts.csswg.org/css-animations-2/#valdef-animation-timeline-timeline-name) before [this recent change](https://github.com/w3c/csswg-drafts/commit/85f456ad28adb7da7b3ef0c5d58a62756b10b82f). Does this syntax is not valid anymore? Is it possible to define this type with the appropriate syntax?

**Comment by fantasai** [comment]
OK, I fixed it by just inlining `<custom-ident>`. I guess it's an open question whether we should also allow strings?

**Comment by cdoublev** [comment]
Thanks and yes, asked in #8134.
