### ISSUE TITLE
[css-break] Minimum values for `widows` & `orphans` properties should be 1, not 0

### ISSUE THREAD

**Issue by cdumez** [w3c/csswg-drafts#8247]
Minimum values for `widows` & `orphans` properties should be 1, not 0:
- https://w3c.github.io/csswg-drafts/css-break/#widows-orphans

The value range says: `<integer [0,∞]>`, but I think it should be `<integer [1,∞]>`, given that the prose right under the table says:
> Negative values and zero are invalid and must cause the declaration to be ignored.

**Comment by fantasai** [comment]
Thanks for the report! Fixed.

**Comment by Loirooriol** [comment]
This seems superfluous now:

> Only positive integers are allowed as values of [orphans](https://w3c.github.io/csswg-drafts/css-break/#propdef-orphans) and [widows](https://w3c.github.io/csswg-drafts/css-break/#propdef-widows). Negative values and zero are invalid and must cause the declaration to be [ignored](https://www.w3.org/TR/CSS21/conform.html#ignore).

**Comment by astearns** [comment]
It’s OK to say the same thing in grammar and prose (if they actually do match)
