### ISSUE TITLE
[css-nesting] Choose Nesting syntax — Option 3, 4 or 5?

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#8248]
Let’s choose between Option 3, 4, and 5 for CSS Nesting syntax.

With over 2,500 votes, the results of the [latest developer survey](https://webkit.org/blog/13607/help-choose-from-options-for-css-nesting-syntax/) (not counting the last 5 hours) were:
- Option 3 — 80%
- Option 4 — 7%
- Option 5 — 13%

**Comment by jensimmons** [comment]
As I wrote the article, I worried people would skim it too quickly and not see there’s a difference between Option 3 and Sass syntax. So, as a thought exercise, I ran some numbers. 

Let’s imagine a third of the people who voted for Option 3 misunderstood the details, and mistakenly believed they were voting for Sass syntax, changing the results to this:
- Option 3 — 53%
- Sass syntax  — 27%
- Option 4 — 7%
- Option 5 — 13%

Even then, Option 3 is preferred by a majority of those responding.

**Comment by LeaVerou** [comment]
As I mentioned in the call, it would be good to define what kind of "continued refinement" we are looking for and open separate issues.

Some issues we've heard with option 3 are:
1. Some people suggest making `&` mandatory at all times.
2. Others want to go the opposite way, and make it optional in even more cases, this is what #7961 is about.
3. @plinss’s objection was related to how constraining this would be for future syntax; he is concerned that if anything that starts with a selector character is assumed to be a selector this will restrict future extensions significantly, and instead wants to limit what signifies that something is a nested rule. This to me sounds a lot like the previous nesting syntax, but perhaps there is another option. Peter, could you please open an issue so we can discuss?

Is there something else we could refine?

**Comment by tabatkins** [comment]
Mandatory ampersand won't help - `.foo & {...}` still needs to be valid.

**Comment by LeaVerou** [comment]
> Mandatory ampersand won't help - `.foo & {...}` still needs to be valid.

The reasoning of those folks is not to ease parsing, but clarity. `.foo &` still has an ampersand in it.

**Comment by plinss** [comment]
> The reasoning of those folks is not to facilitate parsing, but to improve clarity (as they see it). .foo & still has an ampersand in it.

But requires indefinite lookahead to determine. If we're going to add indefinite lookahead, we can just use the SASS approach.

**Comment by tabatkins** [comment]
No, `.foo &` doesn't require indefinite lookahead. In the current rules, we see it's a style rule on the very first token (`.`).

**Comment by plinss** [comment]
But if the `&` is required, you either have to have indefinite lookahead to find the `&`, or something like `.foo bar baz {...` is going to get rejected, where it could theoretically have been acceptable as a property at some point.

**Comment by tabatkins** [comment]
Right, which is part of why I don't think "required &" does anything useful.

**Comment by dbaron** [comment]
I opened #8251 as a followup for the thing that I was thinking about (in response to Peter's comments) on today's call.

I'd also note that Peter opened #8249, which is distinct from that.

**Comment by Loirooriol** [comment]
Mandatory `&` wouldn't be useless, it would bring clarity to authors writing or reading CSS. E.g. a nested `::before` can be misunderstood as `&::before` or `& ::before`, but it's clear with the `&`.

Personally I plan to always use `&`, and use linting to enforce it if the spec says it's optional. So I prefer a mandatory `&`.

**Comment by SebastianZ** [comment]
And for the record, there was also already some discussion earlier about requiring `&` at the beginning of every nested selector. This avoids lookaheads entirely but also burdens writing nested selectors.

And before somebody asks, `.foo & {...` would be expressed as `& .foo & {...` in that case.

(Note that I don't advocate for that syntax, I just wanted to mention it again, as it seems people forgot about the options that were previously discussed.

Though I am with @Loirooriol here and would always prepend my nested selectors with `&`. And I'd generally avoid putting `&` in the middle of a selector as that rather confuses than helps, IMO.)

Sebastian

**Comment by romainmenke** [comment]
> Some people suggest making & mandatory at all times. We should open an issue on this (and replace this sentence with a reference).

Mandatory `&` in itself is not really interesting I think.
As @Loirooriol said this can be achieved with a linter, so I don't see the point of enforcing this in the specification unless if offers some advantage.

These cases are not helped by mandatory `&` :

- `div:has(> &)` compound selector with `&` in a functional pseudo
- `div &` complex selector with `&` not in the first compound

I am unsure what mandatory `&` is supposed to resolve.

------

> And before somebody asks, .foo & {... would be expressed as & .foo & {... in that case.

Using `&` as a prefix and as as reference to matched elements of the parent block is highly confusing and limiting.

```css
ul {
  & li & {
    /* style only ul elements that are in other ul li elements */
  }
}
```

Is the first `&` a prefix to indicate a style rule or is it a reference to `ul`?

--------

Can someone open an issue for this (as @LeaVerou indicated) and describe the benefits/details of mandatory `&`?

**Comment by SebastianZ** [comment]
> Can someone open an issue for this (as @LeaVerou indicated) and describe the benefits/details of mandatory `&`?

I created #8270 for that now, so we can continue the discussion there.

Sebastian

**Comment by jensimmons** [comment]
I'm going to close this issue, since we succeeded in choosing between Option 3, 4 and 5. Refinement of Option 3 can continue in new issues.
