### ISSUE TITLE
[css-fonts] CSSFontFaceRule  does not seem Web compatible

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#825]
CSSFontFaceRule has a style property, introduced in DOM Level 2 Style.
 
DOM 2 Style says style property is of type CSSStyleDeclaration
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.html#CSS-CSSFontFaceRule
  https://www.w3.org/TR/2000/REC-DOM-Level-2-Style-20001113/css.html#CSS-CSSStyleDeclaration

while CSS3 Fonts says style property is of type DOMString.
   https://drafts.csswg.org/css-fonts/Fonts.html#om-fontface

Informal testing indicates that in browsers (tested Firefox 51, Chrome 57, Edge 14) the style property is an object, per Dom 2 Style. It isn't a DOMString and it is not clear how Web compatible it would be to change the type of the property.

Quick test http://codepen.io/svgeesus/pen/ZBZbbv

**Comment by svgeesus** [comment]
(That test has a separate issue where family == 'sample' works on Chrome and Edge, but family == '"sample"' is needed on Firefox, with double quoting).

**Comment by svgeesus** [comment]
So, is this just a copy paste error in the Fonts 3 spec? If style was CSSStyleDeclaration while family, src, etc were DOMString that would make sense to me, the old one for backwards compat and the new ones for convenience.

**Comment by tabatkins** [comment]
This was no error, it was an intentional "let's fix this better" effort by jdaggett years ago that never panned out.  Old 2.1 spec gave CSSFontFaceRule a .style property, which worked identically to style rules, but jdaggett tried to fix it to just put the valid descriptors directly on the CSSFontFaceRule, like we do with other at-rules.

However, no browser ever picked up the change, including Firefox, which John was nominally in charge of (for the relevant section). :/  This needs to be reverted to match reality, unless browsers actually think they can change their implementation. (I'm pretty sure Chrome's position is that we probably can't.)

**Comment by upsuper** [comment]
I still hope to push forward this change. Could we keep a `style` attribute inside `CSSFontFaceRule` which points to itself, so that we don't use `CSSStyleDeclaration` which includes tons of unrelated properties?

The currently state doesn't make much sense to me.

**Comment by litherum** [comment]
We definitely can't break existing code, which treats it as a CSSStyleDeclaration (using cssText and getPropertyValue()). Given this constraint, I'm not sure that we can do this.

**Comment by SimonSapin** [comment]
We probably need to keep `attribute CSSStyleDeclaration  style` for web-compat. Given that, is it still worth adding new per-descriptor attributes? Either way the css-fonts spec needs changes.

**Comment by upsuper** [comment]
> We definitely can't break existing code, which treats it as a CSSStyleDeclaration (using cssText and getPropertyValue()). Given this constraint, I'm not sure that we can do this.

Ah, `cssText`... probably worth adding a `FontFaceDeclaration`...

**Comment by SimonSapin** [comment]
@upsuper Do you mean something that has all the same methods and attributes as `CSSStyleDeclaration`, but isn’t `CSSStyleDeclaration`? Why is that preferable to `CSSStyleDeclaration`, which is already reused for very different things? (E.g. `Element.style` vs `getComputedStyle()`)

**Comment by upsuper** [comment]
Because `CSSStyleDeclaration`, per the current spec, contains [all other unrelated properties as attributes](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_camel_cased_attribute), which is undesirable in this case.

WebKit and Blink have already been using the new definition for `CSSStyleDeclaration`, but Gecko still splits `CSSStyleDeclaration` and `CSS2Properties` (the latter was the one defined in some early version of spec which includes attributes of properties and inherits from `CSSStyleDeclaration`).

**Comment by foolip** [comment]
I just filed https://bugs.chromium.org/p/chromium/issues/detail?id=709013 for addressing this mismatch between Blink and the spec. I mentioned in the descriptions that all engines still seem to match the old spec, and also that we have a use counter:
https://www.chromestatus.com/metrics/feature/timeline/popularity/1082

Preserving the `style` attribute would be the safest thing unless somebody is willing to investigate how code in the wild is impacted.

**Comment by svgeesus** [comment]
> Preserving the style attribute would be the safest thing unless somebody is willing to investigate how code in the wild is impacted.

Agreed; there seems to be consensus on that point.
I'm not seeing agreement on adding new per-descriptor attributes?

If we wanted to do that, the feature should be moved to css4-fonts. If we don't, is it sufficient to drop the feature and leave it to DOM 2 Style?

**Comment by foolip** [comment]
https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSFontFaceRule is not maintained and I'd consider it a bug if that were the only spec defining `CSSFontFaceRule`.

**Comment by litherum** [comment]
If we’re keeping the .style attribute, then there's no reason to add description attributes. Indeed, redundancy should be eliminated.

**Comment by svgeesus** [comment]
Why isn't this a part of CSS OM?
https://www.w3.org/TR/cssom-1/

**Comment by SimonSapin** [comment]
I think that the CSSOM spec defines interfaces for rules in CSS 2, and later specs that introduce new at-rules define their own OM. For example: https://drafts.csswg.org/css-conditional/#apis

**Comment by svgeesus** [comment]
Which is fine too, I just wanted some clarity on 

1. What should be specified, and
2. Where

**Comment by SimonSapin** [comment]
I think that the conclusion from this thread is that css-fonts should specify a `CSSFontFaceRule` interface similar to DOM Style Level 2, with no new attribute added. (Except probably with `[SameObject, PutForwards=cssText]` added, like `CSSStyleRule`.)

**Comment by SimonSapin** [comment]
The CSS Working Group discussed this today and resolved:

```
RESOLVED: Remove CSS OM section from Fonts Level 3 to Fonts Level 4
RESOLVED: As above, but leave CSSFontFaceRule with a note explaining the current state
```

<details>

```
<fantasai>	Topic: CSS Fonts 3
<dino>	ScribeNick: dino
<Chris__L>	https://www.w3.org/People/chris/fwf/
<dino>	Chris__L: Myles made an interesting font.
<dino>	Chris__L: for each char, it displays a cross or tick depending if a feature is on or off
<dino>	Chris__L: it allows you switch high/low level features on and see the output
<dino>	Chris__L: the link above shows the results of testing
<dino>	Chris__L: staged at the moment because they are easier to see live
<tantek_>	github topic: none
<dino>	Chris__L: the amount of greeniness shows how many implementations we have. red is zero greeniness
<dino>	Chris__L: the one that sticks out is font-variant-east-asian, only Gecko passing
<dino>	Chris__L: chrome passes the low level test, but the syntax isn't hooked up
<dino>	eae: we will try to fix this quarter
<dino>	Chris__L: scroll to the bottom, see the object model. Nobody implements what the spec says, but they do implement stuff from DOM Level 2
<dino>	SimonSapin: iirc, the conclusion was that we'd copy the interface from DOM 2 into the Fonts spec.
<dino>	SimonSapin: and there was only a few attributes missing
<dino>	SimonSapin: I'll make a pull request
<dbaron>	The OM thing is https://github.com/w3c/csswg-drafts/issues/825
<dino>	jdaggett: the OM rule is non-functional. to make it work you have to jam things into the style.
<dino>	jdaggett: you can manipulate unicode range on a style property - this is weird
<dino>	jdaggett: it is badly defined. we are not speccing out what the implementors are implementing.
<dino>	Chris__L: what do you suggest?
<dino>	jdaggett: that implementors follow the spec
<dino>	jdaggett: we should not spec out whacky behaviour on style rules
<dino>	myles_: content that already exists, will access the descriptors inside the rule. So we need a .style property
<dino>	jdaggett: are people actually using this functionality, that's been there since CSS 2. Last time I looked, if you went in and changed the font family, font matching didn't respond correctly.
<dino>	myles_: works in Safari.
<dino>	jdaggett: not in Chrome
<dino>	jdaggett: this is broken in practice.
<dino>	Chris__L: where do we want to go?
<dino>	jdaggett: if you're looking to go to REC, then put something in that says it is not defined and push the OM to CSS 4
<dino>	Chris__L: what you have specced is better, but the implementors don't agree.
<dino>	astearns: we have to move the OM section from Fonts 3 into Fonts 4. any objection?
<dino>	SimonSapin: i am fine with moving the attributes. But the @font-face rule interface exists
<dino>	astearns: we can copy over what is in CSS 2 to Fonts 3, or we can have a section saying that CSS 2 exists but we are not putting it in the spec
<dino>	Chris__L: people seemed to push back that DOM Level 2 is ancient
<dino>	jdaggett: but all the implementations are in the same boat
<dino>	RESOLVED: Remove CSS OM section from Fonts Level 3 to Fonts Level 4
<dino>	SimonSapin: just the attributes?
<dino>	SimonSapin: option - define CSSFontFaceRule, but without any attributes.
<dino>	myles_: why is that valuable?
<dino>	SimonSapin: because you want something to show up in the CSSRules.
<dino>	Florian: is that implemented? pushing it out doesn't mean we don't want it.
<dino>	SimonSapin: CSSFontFaceRule with a style attribute is implemented. The font spec has one attribute for each descriptor.
<dino>	SimonSapin: this comes from DOM Level 2
<dino>	dbaron: if we do this, we should add a note saying that this is actually defined in Fonts 4, but what is currently implemented is defined in DOM Level 2
<dino>	astearns: objections to amending the resolution to leave CSSFontFaceRule and add a Note
<dino>	?
<dino>	RESOLVED: As above, but leave CSSFontFaceRule with a note explaining the current state
```

</details>

**Comment by foolip** [comment]
From the transcript and https://github.com/w3c/csswg-drafts/pull/1247 it's not clear to me what the plan is for having some maintained spec define CSSFontFaceRule in a way that matches implementations.

**Comment by SimonSapin** [comment]
@foolip I think this is a valid concern.

Additionally, DOM Level 2 is somewhat under-specifed: is says there’s a `style` attribute of type `CSSStyleDeclaration`, but `CSSStyleDeclaration` normally deals with properties (including in its methods’ names) but in this case it should be "monkey-patched" to refer to `@font-face` descriptors instead.

For example `unicode-range` is not a property, but this shows “U+0” in at least Firefox and Chromium:

```html
data:text/html,<style>@font-face{unicode-range: U+0}</style><script>document.write(document.styleSheets[0].cssRules[0].style.getPropertyValue("unicode-range"))</script>
```

**Comment by astearns** [comment]
@foolip I'm not clear whether implementations have interoperable behavior in what they currently implement. In the discussion @nattokirai mentioned that something as simple as changing the font family did not work in all browsers.

**Comment by upsuper** [comment]
Gecko doesn't support dynamic change on descriptors of `font-face` rules, but I don't think there is much technical difficulty to implement that.

We support dynamic change for `counter-style`, and those two kinds of rules are handled pretty similarly.

I believe that it doesn't work simply because we didn't implement at the beginning, and we haven't prioritized it.

**Comment by foolip** [comment]
No doubt there are interop problems here, but there are *some* things that implementations seem to agree on. In https://jsbin.com/goqepuw/edit?html,output I managed to write a test where the only thing that fails is that Edge doesn't expose the src.

Perhaps the interface doesn't make sense, but given how long it's been around it's plausible that code out there depends on some subset of this.

**Comment by tabatkins** [comment]
Yeah, I raised this much earlier in reference to Font Loading - I defined the FontFace interface to mimic CSSFontFaceRule, not knowing that the latter is complete specifiction that jdagg was willing to put in the spec but not even make his own browser match. :/

There's definitely some behavioral corners to suss out here; with luck we can actually drop the `.style` down to just the subset of actual `@font-face` descriptors (and thus eliminate those descriptors from the normal style rule's `.style`), but in any case we definitely need a `.style` with those descriptors.

**Comment by litherum** [comment]
I already merged the patch which moves the guts of CSSFontFaceRule to level 4, and it looks like we haven't resolved on whether or not to keep the new attributes or whether to reduce the extra stuff in the CSSStyleDeclaration. Removing the "Needs Edits" label.

**Comment by litherum** [comment]
I think we need a resolution before I can do anything here. Agenda+.

**Comment by dbaron** [comment]
So Gecko doesn't implement the merging of CSS2Properties into CSSStyleDecleration, and the declaration block for @font-face rules doesn't implement CSS2Properties.  See [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0A%40font-face%20%7B%0A%20%20font-family%3A%20foobar%3B%0A%7D%0A%3C%2Fstyle%3E%0A%3Cscript%3E%0Avar%20s%20%3D%20document.getElementsByTagName(%22style%22)%5B0%5D.sheet%3B%0Avar%20r%20%3D%20s.cssRules%5B0%5D%3B%0Adocument.write(r.style.getPropertyValue(%22font-family%22)%20%2B%20%22%3Cbr%3E%22)%3B%0Adocument.write(r.style.fontFamily%20%2B%20%22%3Cbr%3E%22)%3B%0A%3C%2Fscript%3E).  So I think it's reasonable to think that putting all of CSS2Properties into whatever represents the declaration-block for @font-face isn't needed for Web compatibility.

**Comment by dbaron** [comment]
(And I think the issue of not wanting all the bogus properties on CSSFontFaceRule.style was [one of the reasons](https://bugzilla.mozilla.org/show_bug.cgi?id=1290786#c2) we haven't done that merge.)

**Comment by svgeesus** [comment]
I added a few CSS Fonts 3 tests, including @font-face and @font-feature-settings to WPT. The @font-face test is just that the interface exists, the properties are not tested.
https://github.com/w3c/web-platform-tests/pull/6586
@litherum waiting for your review

Happy to add further tests for CSS Fonts 4 in that area, once we agree on this issue.

**Comment by tabatkins** [comment]
@dbaron I'd be okay with a result that we unmerge the CSS2 properties from the CSSStyleDeclaration in general, and reuse that. It still means that `FontFace` and `CSSFontFaceRule` would have different shapes, but oh well, it's shipped and we're stuck with it.

I just really, really want the current "pretend all the descriptors are directly on the interface" specification to either go away or become reality.

**Comment by astearns** [comment]
Some discussion after this noted that we'd probably need to re-introduce the style property into the fonts-3 interface.

**Comment by tabatkins** [comment]
Yeah, in more detail the edits are:

1. Reduce CSSFontFaceRule to just `interface CSSFontFaceRule : CSSRule { attribute CSSStyleDeclaration style; };`
2. Remove [`_camel_cased_attribute`](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-_camel_cased_attribute) from `CSSStyleDeclaration`.
3. Create another interface with `_camel_cased_attribute`, somehow mix it into CSSStyleRule? The DOM2Style spec was extremely hand-wavy about this worked.

**Comment by litherum** [comment]
CSSStyleDeclaration is defined in another spec, so another issue should be raised for it. Do you know where to file it, @tabatkins?

**Comment by tabatkins** [comment]
Yeah, file it against CSSOM.  The (1) in my list is still against the Fonts spec, tho, so this should probably be open.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/commit/15de56bbca63f19259378d468b78db6b80b8ece5 completes (1), right?

**Comment by tabatkins** [comment]
Yeah.

**Comment by litherum** [comment]
https://github.com/w3c/csswg-drafts/issues/1692
