### ISSUE TITLE
[css-text-4] `white-space` shorthand values cannot be fully expressed using its longhands

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#8256]
https://drafts.csswg.org/css-text-4/#white-space-property

See issues 3 & 4.

WebKit assumes that shorthands don't have other side effects than just setting their longhands. So every single of the shorthand values should be expressible in some form by their longhands.

**Comment by Loirooriol** [comment]
It's not ideal (see #8055), but there are the precedents like system fonts, which set longhands to an internal value that serializes to empty string. This could be a temporary solution if you want to implement the longhands.

**Comment by nt1m** [comment]
> there are the precedents like system fonts, which set longhands to an internal value that serializes to empty string.

This means the spec cannot be implemented without implementing the full set of longhands at least, even though `text-space-collapse` & `text-space-trim` are not stable.

**Comment by fantasai** [comment]
@nt1m Is there some particular feature that you want from L4? Sorting this out is on the to-do list, but there hasn't been a lot of interest in the extended white space values...

**Comment by nt1m** [comment]
@fantasai I'm interested in implementing `text-wrap` and `text-group-align` more specifically.

**Comment by fantasai** [comment]
Fixed in https://github.com/w3c/csswg-drafts/pull/8274 @nt1m Please file follow-up issues if you notice anything wrong!
