### ISSUE TITLE
[css-values-4] Clarify minimum calculation terms

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8258]
> UAs must support calculations of at least 32 `<calc-value>` terms and at least 32 levels of nesting (parentheses and/or functions)

Considering the above requirement, does `calc(calc(1 + 2) + calc(1))` include 2, 3, or 5 `<calc-value>`s?

I would be fine with closing this issue as "question answered" with ***32 `<calc-value>` terms without considering nesting***, because that is what it means to me in the absence of any other precision. It would mean that there is 5 terms in my example.

**Comment by cdoublev** [comment]
I re-open this issue because I think the current definition is inapplicable: if you have to support 32 levels of nesting, you have to support 33 `<calc-value>` terms. 

`(1)` matches two `<calc-value>`: the first for the parens, the second for `1`.

**Comment by Loirooriol** [comment]
Note those are minimums, not maximums.

**Comment by cdoublev** [comment]
The title of this issue was incorrect, indeed. 

But I wonder if it should be a maximum, actually. Chrome and Firefox do not limit terms and my laptop froze for 5 minutes when running tests in both browsers at the same time.

**Comment by Loirooriol** [comment]
How many terms did your test have? Maybe file issues in https://crbug.com and https://bugzil.la so that they add implementation limits. But I don't think the spec should impose maximums.

**Comment by cdoublev** [comment]
I think it was a 6 or 7 digits number but I think it depends on the device resources. 

You are probably right: the limit should be defined on the browser side. It seems that I cannot write anything good for today, and I am not thrilled with the idea of crashing my laptop again, but I will file an issue tomorrow after carefull testing.

**Comment by tabatkins** [comment]
While parsing `calc(calc(1 + 2) + calc(1))` you match against `<calc-value>` 5 times - twice at the top level, and three more times nested inside the calcs. So that's the answer for the purposes of this limit. ^_^

**Comment by cdoublev** [comment]
Ok, thanks. I am fine with the current definition since it is an unimportant detail. I understand that the purpose is to avoid processing variadic math functions with each argument defined with 32*32**32 calc values.
