### ISSUE TITLE
[snapshot-2017] Candidate modules for inclusion

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#826]
As requested by @dbaron  on 2016-12-21 CSS call. All modules (CSS and fxtf) sorted by already-there, will-include, and the rest.

https://github.com/w3c/csswg-drafts/blob/master/snapshot-2017-modules.md

**Comment by dbaron** [comment]
I made an edit to that list to fix one duplicate I caught.

Looking through the list of things that aren't included, I think things worth considering to add to the "fairly stable but beware" level (although I'd probably lean against inclusion on some of them) are:
css-align
css-grid
css-ruby
css-text
css-writing-modes
filters-1

We should also think about whether things like cssom, cssom-view, and the houdini specs should be part of a snapshot if they're stable enough.

**Comment by svgeesus** [comment]
> We should also think about whether things like cssom, cssom-view, and the houdini specs should be part of a snapshot if they're stable enough.

I see no reason not to, if they are stable enough.

**Comment by frivoal** [comment]
@dbaron I agree on your list of fairly stable but beware specs (maybe not ruby), but how about also including css-break? implementation is somewhat spotty, but the spec itself seems to me to be in good shape, and quoting the introduction:

> The primary audience is CSS implementers, not CSS authors, as this definition includes modules by specification stability, not Web browser adoption rate.

**Comment by svgeesus** [comment]
Also, snapshot 2015 promises that indices of properties, functions etc are coming:
https://www.w3.org/TR/CSS/#indices

Snapshot 2017 should link to the specific sections:

    2 Properties and Descriptors
    3 Property/Descriptor Values
    4 Functions
    5 At-Rules
    6 Selectors

because the indices are not well known at present.

**Comment by dbaron** [comment]
We just discussed in the WG meeting, and concluded:

Add to primary section:
Writing Modes

Add to rough interop section:
Variables
Text

Add to completed design section:
Align
Grid
Filters
Break

**Comment by frivoal** [comment]
Closed by f1adcde5af3458872b7d74ebe1d6c2a0edf40277
