### ISSUE TITLE
[css-text-4] text-spacing replacing spaces

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8263]
We had at several points (most recently [here](https://github.com/w3c/csswg-drafts/issues/6950#issuecomment-1246643325) and [here](https://github.com/w3c/csswg-drafts/issues/7183) and [here](https://lists.w3.org/Archives/Public/www-style/2022Dec/0001.html)) discussed having the space-inserting values of `text-spacing` replace U+0020 when it's used in place of the appropriate spacing type.

Specific cases that came up:
* replacing U+0020 when it's used instead of non-breaking thin spaces inside French punctuation
* replacing U+0020 when it's used for ideograph-alpha or ideograph-numeric spacing

This issue is to discuss that proposal: whether to make the default, or opt-in via some mechanism.

**Comment by frivoal** [comment]
@fantasai, I think this is ready to close, as addressed by the commit above. Agreed?
