### ISSUE TITLE
[css-view-transitions-1] How to interact with Intersection Observer?

### ISSUE THREAD

**Issue by bakura10** [w3c/csswg-drafts#8269]
Hi,

I am trying to play with the new view transitions API in the context of a multi page website. For now, I am using the meta tag to perform the cross-document transition.

I am however facing an issue that I am not sure if this API is supposed to tackle. We have some on-scroll based animations that are powered by an IntersectionObserver, for instance to stagger items. However, the issue seems that the observer is fired as soon as the page transition _before_ the page transition has actually finished. This can lead to a situation (if the page transition is the same or slower than the animation) where the on scroll transitions are completely ignored.

To illustrate the situation, here is how it looks without any page transition:

https://user-images.githubusercontent.com/1198915/210054932-485d9d4e-1308-4eed-85f8-16832998c3fa.mov

And how it looks with the page transition enabled (slow down to 5s to exhibit the issue). Because the IntersectionObserver runs immediately and fire the animation on each blog post card, when the view transition API replaces the old by new, the animation is already completely finished.

https://user-images.githubusercontent.com/1198915/210055072-05907643-e69d-40f5-8ad7-6c1708113310.mov

Am I trying to use this API in an unintended way here?

Thanks :)

**Comment by khushalsagar** [comment]
Thanks for filing the issue @bakura10. While you're experimenting with the cross-document version I could see this happening with the same-document (SPA) version of the API too.

Let me reiterate to make sure I understand what you're trying to do. You have an IntersectionObserver setup for all items on the new page to do a staggered fade-in/translate animation. The IO is mean to trigger the animation when a new item is scrolled into the visible viewport.

When you add the ViewTransition, the IntersectionObserver fires before the first frame of the new page (which also starts the ViewTransition). So now the ViewTransition animation and the translate/fade-in animation on each item are running in parallel.

You can do a couple of things based on the UX you want and what's easier to integrate with your code:

- If you want to keep using the on-scroll animations to take care of fading in the items on first load, then you can defer registering the IntersectionObserver until the transition animations are done. The MPA API doesn't have it right now but we'll have a promise for this similar to SPA's [finished](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-finished-promise) promise.
   This way the IO events will fire after the transition is done and you can chain any animation which should happen then.

- You could define all animations for the transition using the VT API and only use the on-scroll ones for interactions after page load.

@jakearchibald for a suggestion too.

**Comment by bakura10** [comment]
Hi @khushalsagar ,

Thanks for the answer and for your suggestions. You're correct in your assumption. The issue for now is indeed that, in the context of MPA (for now I am using the meta attribute outline in the documentation) we have no way to access to this finished promise. The only option seems to be artificially delaying the start of the animation, but this is pretty fragile as we would need to hardcode somewhere the artificial delay.

I suppose it is better to not use this API for now until the MPA spec has evolved a bit then ;).

**Comment by khushalsagar** [comment]
Sure. We're actively working on evolving the API shape and landing a prototype in Chromium. The early experimentation and feedback is much appreciated!

The explainer has been updated to include the use-case you mentioned and relying on the `finished` promise for it [here](https://github.com/WICG/view-transitions/blob/main/explainer.md#cross-document-same-origin-transitions:~:text=//%20The%20%60finished%60%20promise%20resolves%20when%20all%20animations%20for%20the%20transition%20are%0A%20%20//%20finished%20or%20cancelled%20and%20the%20pseudo%2Delements%20have%20been%20removed.) I'll update this issue when the script events are available to test in the prototype.
