### ISSUE TITLE
[css-scroll-snap] Is scroll-snap-type: [ mandatory | proximity ] valid CSS?

### ISSUE THREAD

**Issue by whsieh** [w3c/csswg-drafts#827]
Link: https://drafts.csswg.org/css-scroll-snap/

According to the spec, values of `scroll-snap-type` follow the format `none | [ x | y | block | inline | both ] [ mandatory | proximity ]?`, which I understand to mean that values like `x mandatory` or `block` are valid, but `mandatory` alone is not. However, in Section 2 (Motivating Examples) I noticed that `scroll-snap-type: mandatory;` and `scroll-snap-type: proximity;` are utilized. Is the intention to make those valid values for `scroll-snap-type`?

If they are, would it make sense to make the default axis type `both` when only `proximity` or `mandatory` are specified?

**Comment by fantasai** [comment]
Good catch. The CSSWG resolved on requiring the axis arguments (usually you want just one axis or the other, not both--both results in weird scrolling behavior on a normal document). The examples didn't get updated, though.

**Comment by fantasai** [comment]
(Tab and I had originally proposed to use whichever axis is scrollable, defaulting to the block axis if both are, but we couldn't get agreement on that so now it's a required argument.)
