### ISSUE TITLE
[css-overflow-3][css-overflow-4][css-overflow-5] Reshuffling Levels

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8271]
Since @frivoal and I are trying to stabilize CSS Overflow L3 for CR, we'd like to propose the following shuffle of features:

* Shift `line-clamp` and its longhands from L3 to L4.
* Push any extensions to `overflow-*` properties not yet implemented by two browsers to L4.
* Shift all the experimental overflow fragments stuff and the `scrollbar-gutter` extensions appendix from L4 to a new L5 spec.

We're open to suggestions on what to do with the `text-overflow` extensions in L4, whether to keep it there or shift it to L5. It's pretty rough atm, but if anyone is interested we can try to polish it up. https://drafts.csswg.org/css-overflow-4/#text-overflow

**Comment by astearns** [comment]
Could we resolve on this async? The L3->L4 moves seem good to me, and I would be fine leaving the L4-L5 split up to editor’s discretion.

**Comment by fantasai** [comment]
@astearns I'd be interested in getting implementer input on the L4 `text-overflow` question.

**Comment by astearns** [comment]
Switching back to Agenda+, unless we get implementer opinions expressed here before we get to it on a call.
