### ISSUE TITLE
[css-view-transitions-1] UA CSS should size ::view-transition to 0x0

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8278]
Related to the discussion in #7797.

[`::view-transition`](https://drafts.csswg.org/css-view-transitions-1/#selectordef-view-transition) pseudo-element is created for all transitions and sized to the snapshot viewport. This means all user input will resolve to the document element by default (since it will hit this pseudo-element). This doesn't make sense for cases where the root element is not participating in the transition.

UA CSS should add `pointer-events: none` to this element to prevent it from participating in hit-testing.

Note: This issue is about the default behaviour. Developer CSS can toggle the value of `pointer-events`.

@jakearchibald

**Comment by jakearchibald** [comment]
I think this is a reasonable change.

**Comment by astearns** [comment]
This looks reasonable and should probably get in the spec for wider review.

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution : UA CSS should add pointer-events: none to the ::view-transition pseudo-element

**Comment by flackr** [comment]
I think from a developer perspective it would be better to make the `::view-transition` root have 0 size if it has no content participating in the transition. This is the same sort of behavior an element with no content would have - possibly it still has `width: 100%` but no height like a normal block element. Developers can easily style it to be full size and this way if developers apply a background it will by default block events which feels like the expected behavior (e.g. if you have a shade over the background). This also reduces the number of styles we need to apply, as we would otherwise have to apply `pointer-events: none` to the root and `pointer-events: auto;` to all of the descendants.

**Comment by jakearchibald** [comment]
This is a more reasonable change. It prevents the case where the developer applies an opaque backdrop, but clicks still go through to the real DOM underneath, because they didn't set `point-events: auto`.

With this proposal, if the developer successfully creates a backdrop (eg `inset: 0; background: black`, it will also capture clicks, which is ideal.

**Comment by vmpstr** [comment]
I agree that this is a better change and I would propose that we accept that.

Revised proposal: Make `::view-transition` have 0x0 size. Adjust the root element's `view-transition-group` size from `inset(0)` to a calculated size similar to how the size of other view transition elements is calculated.

**Comment by khushalsagar** [comment]
+1 on the new proposal. It is indeed better than what I proposed since we don't want to ignore `::view-transition` from hit testing if it has any content. And now explicit developer CSS would be needed for it to have content.

**Comment by khushalsagar** [comment]
@astearns I'm re-adding the label for async resolution on the updated proposal. Feel free to add CFC or add this to the in-meeting agenda items if you think that's better.

**Comment by vmpstr** [comment]
Just to be explicit about the proposed resolution here:

* Currently we spec `::view-transition` to have `position: fixed; inset: 0`. The new proposed spec for `::view-transition` is `position: fixed; top: 0; left: 0;`. 
* Additionally, the `width` and `height` property of the `view-transition-group` that corresponds to the root element is set to the width and height of the snapshot root.

**Comment by astearns** [comment]
OK, trying again :)

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

**Proposed Resolution**: Make ::view-transition have 0x0 size. Adjust the root element's view-transition-group size from inset(0) to a calculated size similar to how the size of other view transition elements is calculated.

with more specifics from above:

-     Currently we spec ::view-transition to have position: fixed; inset: 0. The new proposed spec for ::view-transition is position: fixed; top: 0; left: 0;.
-     Additionally, the width and height property of the view-transition-group that corresponds to the root element is set to the width and height of the snapshot root.

**Comment by jakearchibald** [comment]
TODO: Go to agenda+ with solution 1.

**Comment by khushalsagar** [comment]
This could use some more input from web developers, @mirisuzanne @ydaniv FYI.

**Comment by fantasai** [comment]
@astearns I think this should go to the regular agenda.

**Comment by ydaniv** [comment]
+1 to @jakearchibald's conclusions, but I keep going to that use-case of driving the transition via user interaction, like dragging with touch. Jake did that one, and if I'm not mistaken that worked fine with current implementation.

One con that until we have real scoped transitions, stuff like transitioning slides in a carousel and loosing interactivity might seem wierd.

But prefer 1.

**Comment by noamr** [comment]
@khushalsagar isn't option 1 already what the current spec says? Anything actionable here?

**Comment by khushalsagar** [comment]
Yup, the resolution aligns with the current spec.
