### ISSUE TITLE
[css-cascade-6] Do we need 'sibling' scopes in @scope?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#8299]
The `@scope` rule defines a scope root selector, and lower boundary selectors - which define a 'scope' as a tree fragment of any matched 'root' and all the descendants up to (and not including) boundary elements or descendants of those boundary elements. In that definition, scopes are always defined by ancestor/descendant relationships.

A few people (including @tabatkins) have suggested that we also need 'sibling' scopes. They would similarly start with a root selector, and allow 'boundary' elements, but the scope would be horizontal rather than vertical: including a root and all subsequent siblings, up to (and not including) and boundary siblings. Boundary siblings, and further siblings after the boundary would be out of scope.

We did resolve at TPAC to add a [proximity-aware sibling combinator](https://github.com/w3c/csswg-drafts/issues/7233) `~~` to parallel the proximity-aware descendant combinator `>>` - so that suggests we might want the same option for scoping itself.

I think there are clear author use-cases here, though I haven't done extensive work collecting those examples. I don't think authors have historically thought of these as 'scope' issues, but it does make sense to me that they require the same functionality turned horizontal. I'm in favor of this, but don't have clever ideas for syntax - maybe a keyword in the `@scope` preamble?

**Comment by bramus** [comment]
I think this can be solved by this selector:

```css
.upper ~ :has(~ .lower) {
	outline: 1px solid red;
}
```

Demo: https://codepen.io/bramus/pen/WNKjZge

The only scenario where this selector fails is when you have two adjacent sets of boundaries, where it now acts greedy: all `<li>`s between the first `.upper` and last `.lower` will be targeted, instead of two separate groups.

```html
<ul>
	<li>outside</li>
	<li class="upper">upper</li>
	<li>inside</li>
	<li>inside</li>
	<li class="lower">lower</li>
	<li>outside</li>
	<li>outside</li>
	<li class="upper">upper</li>
	<li>inside</li>
	<li>inside</li>
	<li>inside</li>
	<li class="lower">lower</li>
	<li>outside</li>
</ul>
```

IUC, the `~~` selector could solve this special case:

```css
.upper ~~ :has(~ .lower) {
	outline: 1px solid red;
}
```

**Comment by romainmenke** [comment]
> the ~~ selector could solve this special case:

But the ergonomics would be different right?

Being able to use `@scope` and writing all styles inside a block makes it easy for authors to work within a set of boundaries without having to think about this with each new selector.

**Comment by bramus** [comment]
> Being able to use `@scope` and writing all styles inside a block makes it easy for authors to work within a set of boundaries without having to think about this with each new selector.

True

**Comment by mirisuzanne** [comment]
This selector workaround also fails in situations where there are no `.lower` elements to end the scope. Instead of selecting everything in the scope, it selects nothing. There are similar selectors that roughly approximate vertical scopes, with very similar limitations. They work sometimes, but they aren't reliable in large component-driven projects, because you don't know when those edge cases might come up. 

But the existence of selectors that get close isn't really the driving question here. Many new features improve on existing patterns. I'm more interested in the use-cases that would drive an author to even consider the selector pattern. Is this form of sibling-scoped selection something that authors need or want? What are example problems that it solves?

**Comment by mirisuzanne** [comment]
Oh, this seems to be a duplicate of #7751
