### ISSUE TITLE
[css-view-transitions-2] Allow passing arbitrary context between Documents for a transition.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8303]
The cross-document VT API has a hook for passing opaque contextual data between pages [here](https://github.com/WICG/view-transitions/blob/main/explainer.md#cross-document-same-origin-transitions:~:text=Add%20opaque%20contextual%20information%20to%20share%20with%20the%20new%20Document.). The idea being that pages can use this to send information from old to new Document for any customization which is not covered by existing APIs. For example, the location where the user clicked, the current scroll offset on the page etc. It's mean to enable flexibility for use-cases we (API designer) might not be thinking of.

The hook is only relevant for MPA since same-document transitions can already do this trivially with context set up outside of the transition API.

**Comment by noamr** [comment]
Perhaps putting something `sessionStorage` during the `navigate` event is good enough for this and we don't need to add this API?

**Comment by noamr** [comment]
I think https://github.com/whatwg/html/issues/10509#issuecomment-2249145080 covers this and we can close this issue?
