### ISSUE TITLE
[css-color-5] Example 11 cannot use source color channel keywords

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8308]
I think `oklab()` cannot use `c` and `h` in Example 11 for [RCS](https://drafts.csswg.org/css-color-5/#relative-colors):

```js
html { --base:  oklch(52.6% 0.115 44.6deg) }
.summary {
  background:  oklab(from var(--base) l c  calc(h + 90));
}
```

**Comment by tabatkins** [comment]
Correct.

**Comment by svgeesus** [comment]
Wow that looks like a copy-paste error to me! Probably my fault from a recent edit. the `oklab` should be `oklch`.

(And yes, obviously)
