### ISSUE TITLE
[css-inline-3]Does "block-end" mentioned by "valdef-leading-trim-start" mean "block-start"

### ISSUE THREAD

**Issue by Clqsin45** [w3c/csswg-drafts#8314]
Hi, I'm reading leading-trim's specification, and wondering whether or not one of the "block-end"s below should be "block-start"? And according to the context where we describe block container, leading-trim-start should use block-start instead of block-end. Is my understanding correct?

### start
For [inline boxes](https://w3c.github.io/csswg-drafts/css-display-4/#inline-box): trims the [block-end](https://w3c.github.io/csswg-drafts/css-writing-modes-4/#block-end) side of the box to match its [content edge](https://w3c.github.io/csswg-drafts/css-box-4/#content-edge) to the metric specified by [text-edge](https://w3c.github.io/csswg-drafts/css-inline-3/#propdef-text-edge) (treating [leading](https://w3c.github.io/csswg-drafts/css-inline-3/#valdef-text-edge-leading) as [text](https://w3c.github.io/csswg-drafts/css-inline-3/#valdef-text-edge-text)).

### end
For [inline boxes](https://w3c.github.io/csswg-drafts/css-display-4/#inline-box): trims the [block-end](https://w3c.github.io/csswg-drafts/css-writing-modes-4/#block-end) side of the box to match its [content edge](https://w3c.github.io/csswg-drafts/css-box-4/#content-edge) to the metric specified by [text-edge](https://w3c.github.io/csswg-drafts/css-inline-3/#propdef-text-edge) (treating [leading](https://w3c.github.io/csswg-drafts/css-inline-3/#valdef-text-edge-leading) as [text](https://w3c.github.io/csswg-drafts/css-inline-3/#valdef-text-edge-text)).

Links:
https://w3c.github.io/csswg-drafts/css-inline-3/#valdef-leading-trim-start

**Comment by fantasai** [comment]
Indeed, yes. Thanks, fixed. :)
