### ISSUE TITLE
[css-grid] Limiting large grids

### ISSUE THREAD

**Issue by tgraham-antenna** [w3c/csswg-drafts#8316]
See:

https://github.com/w3c/csswg-drafts/blob/e31d4f7c48a76873f5c8479f670d3c41cee2beca/css-grid-2/Overview.bs#L1016-L1033

1. Does a UA's limit imply the same number of lines in the positive and negative directions?  The text includes "the range [-10000, 10000]", but the example provides a single number.  If a UA supported grids with at most 250 lines in each dimension, in the following example, which items would be clamped, and where would they be placed?

```
<!DOCTYPE html>
<meta charset="utf-8">
<style>
#grid {
  display: grid;
  grid-auto-columns: 1px;
}

#firstItem {
  background: magenta;
  grid-column: 200 / 300;
  grid-row: 1 / 2;
  order: 2;
}

#secondItem {
  background: yellow;
  grid-column: span 200 / 1;
  grid-row: 2 / 3;
  order: 1;
}

#thirdItem {
  background: lime;
  grid-column: 1 / 2;
  grid-row: 1 / 3;
}
</style>

<div id="grid">
  <div id="firstItem">order: 2</div>
  <div id="secondItem">order: 1</div>
  <div id="thirdItem"></div>
</div>
```

2. It is inconsistent for the text to talk about limiting the number of lines and then the example using a limit to the number of tracks. (It is simple to convert from one to the other, but why should that be necessary for the example?)
3. "which should accommodate lines at in the range [-10000, 10000]" should lose "at".

**Comment by tabatkins** [comment]
> Does a UA's limit imply the same number of lines in the positive and negative directions? The text includes "the range [-10000, 10000]", but the example provides a single number. If a UA supported grids with at most 250 lines in each dimension, in the following example, which items would be clamped, and where would they be placed?

Exactly what the limit is is UA-defined; the spec just requires a minimum range. A UA _could_ use the range [-10000,43500], for example.

For a given maximum track count, the clamping and placement is well-defined by the spec.

> It is inconsistent for the text to talk about limiting the number of lines and then the example using a limit to the number of tracks. (It is simple to convert from one to the other, but why should that be necessary for the example?)

It's purely a matter of which is more convenient to talk about. In this case, talking about tracks allows us to use rounder numbers in the example, which is nicer to read. ^_^

> "which should accommodate lines at in the range [-10000, 10000]" should lose "at".

Good catch, fixed that now.
