### ISSUE TITLE
[css-display] "A run-in box with `display: flow` ..." seems nonsensical

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#832]
https://drafts.csswg.org/css-display/#run-in-layout
> A run-in box with `display: flow` inlinifies its contents. 

I don't understand how you can have a run-in box at all if `<display-outside>` isn't `run-in` ?
( `display: flow` is short for `display: inline flow` is it not?)
Maybe you meant "... when `<display-inside> = flow`" instead?
If so, shouldn't  `<display-inside> = flow-root` run-ins also inlinify its contents?
(i.e. `display: run-in flow-root`)

https://drafts.csswg.org/css-display/#the-display-properties

**Comment by fantasai** [comment]
Looks like an error. That was probably previously `display-inside: flow`.
