### ISSUE TITLE
[css-images] Aligning the grammar of linear color stops with current implementations

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8323]
The [spec](https://w3c.github.io/csswg-drafts/css-images-3/#color-stop-syntax) defines:
````
<linear-color-stop> = <color> && <length-percentage>?
````
But [MDN](https://developer.mozilla.org/docs/Web/CSS/gradient/linear-gradient) shows that all current implementations support an extra syntax, formally:
````
<color> <length-percentage1> <length-percentage2>
````
Moreover, experimenting with Gecko shows the following results:
````
linear-gradient(red, blue, green) // valid syntax

linear-gradient(red, blue 30%, green) // valid syntax
linear-gradient(red, 30% blue, green) // invalid syntax

linear-gradient(red, blue 30% 50%, green) // valid syntax
linear-gradient(red, 30% blue 50%, green) // invalid syntax
linear-gradient(red, 30% 50% blue, green) // invalid syntax

linear-gradient(red, blue 30% 50% 70%, green) // invalid syntax
````
Therefore it seems that the actual syntax of linear color stops is:
````
<linear-color-stop> = <color> <length-percentage>{0,2}
````
Should the spec be edited to reflect this?

Related CSS issue: #6425
Related MDN issue: https://github.com/mdn/content/issues/23718

**Comment by tabatkins** [comment]
It is edited to reflect this, [in Images 4](https://w3c.github.io/csswg-drafts/css-images-4/#color-stop-syntax). ^_^
