### ISSUE TITLE
[css-transitions] Is transitioning of discrete animation typed properties allowed?

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#8332]
(Unless I missed it) the spec doesn't say anything about discrete animation (or non-interpolable) properties.

I created a [test case](https://jsfiddle.net/c54pt17h/) that sets a 2s transition on `list-style-type` and `float` properties. Neither Chrome nor Firefox create a transition for them (so visual changes take place immediately), while I'm expecting visual changes at around 1s.

However, it doesn't make much sense to transition properties that can't be smoothly interpolated, since the whole purpose of CSS transition is to enable smooth transitioning. So if the spec currently allows it, we should just disallow it.

**Comment by Loirooriol** [comment]
This seems covered in https://drafts.csswg.org/css-transitions/#transitionable

> When comparing the [before-change style](https://drafts.csswg.org/css-transitions/#before-change-style) and [after-change style](https://drafts.csswg.org/css-transitions/#after-change-style) for a given property, the property values are transitionable if they have an [animation type](https://drafts.csswg.org/web-animations-1/#animation-type) that is neither [not animatable](https://drafts.csswg.org/web-animations-1/#not-animatable) nor [discrete](https://drafts.csswg.org/web-animations-1/#discrete).

**Comment by xiaochengh** [comment]
Ah, thanks!
