### ISSUE TITLE
[css-align] Is `align-items: flex-start` a subset of the effects of `align-items: start` ?

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8340]
A user requested a PostCSS plugin that would convert `start` to `flex-start` and `end` to `flex-end` for `align-items`.

https://github.com/csstools/postcss-plugins/issues/108

- `start` and `end` are less characters to type
- `flex-start` and `flex-end` have better browser support

When I do a few tests in browsers this seems to work fine.

My concern is that these are listed as separate features in the specification and in MDN documentation. `flex-start` does not appear to be a legacy notation for `start`.

If these are separate features that happen to have the same effect in some cases we should not convert `flex-start` to `start`, even if users prefer short keywords.

**Comment by fantasai** [comment]
They behave differently in flexbox. `flex-start` references `flex-flow`, whereas `start` references only the writing mode.

**Comment by tabatkins** [comment]
Yes, do not convert between them, they're distinct. (But in non-flex contexts, they are indeed identical.)

**Comment by romainmenke** [comment]
I see, thank you 🙇
