### ISSUE TITLE
[css-grid] editorial: typos in Subgrids section

### ISSUE THREAD

**Issue by alligatorio** [w3c/csswg-drafts#835]
https://www.w3.org/TR/css-grid-1/#subgrids

Under Example 27, I think that there are 3 minor typos. The first 2 in the following paragraph:

> If the subgrid has margins/borders/padding, the **the** size of those margins/borders/padding also influence sizing.

Note the duplicate **the**, and I also believe that _influence_ should be _influences_, given the singular _size_ subject. 

Also, the last one in the last paragraph:

> #subgrid { padding: 100px; }

> Then a grid item in the subgrid’s first track acts as if it has an additional 100px of top, left, and bottom **margin** influencing the sizing of the parent grid’s tracks and the grid item’s own position.

I believe that padding should be referenced in that paragraph instead of margin.

**Comment by fantasai** [comment]
Fixed the first one. The second one (padding vs. border) was intentional: the extra space is added outside the visible bounds of the element.
