### ISSUE TITLE
[css-images] Adding logical values for directions in `linear-gradient()`

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8354]
Current syntax for `linear-gradient()` is:
````
linear-gradient() = linear-gradient(
  [ <angle> | to <side-or-corner> ]? || <color-interpolation-method>,
  <color-stop-list>
<side-or-corner> = [left | right] || [top | bottom]
````
And the acceptable values for `<side-or-corner>` make adaptation to different writing modes difficult, e.g. using `<hr>` with a non-zero block size and a linear gradient as its background image. Therefore, it seems useful to make `<side-or-corner>` additionally accept `[block-start | block-end] || [inline-start | inline-end]`.

Relevant section in the spec: https://w3c.github.io/csswg-drafts/css-images-4/#linear-gradients

**Comment by cdoublev** [comment]
You might be interested by #1724.
