### ISSUE TITLE
[css-text-3] Clarify Segment Break Transformation Rules when mutiple segment breaks involve

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#836]
The first rule for collapsing segment breaks is:
> If the character immediately before or immediately after the segment break is the zero-width space character (`U+200B`), then the break is removed, leaving behind the zero-width space.

It is not clear to me what should happen if there are multiple segment breaks involve here. For example, if I have `ZWSP LF LF LF x`, would this rule produce:
1. `ZWSP LF LF x` (with only the first `LF` removed), or
2. `ZWSP x` (with all `LF` removed because of recursively applying this rule)?

(In the first case, the remaining `LF`s would be converted to whitespaces by the last rule there, and the second whitespace would be removed by step 4 of Phase I, so the final result would be `ZWSP WS x`.)

This may also affect the second rule:
> Otherwise, if the East Asian Width property of both the character before and after the line feed is `F`, `W`, or `H` (not `A`), and neither side is Hangul, then the segment break is removed.

If I have `W LF LF W`, should the two `LF`s be removed by this rule?

It seems to me that removing all segment breaks together would be easier for implementation, so I would propose making the rules that way if there are no other concerns.

**Comment by upsuper** [comment]
cc @chenpighead

**Comment by fantasai** [comment]
Amending this to be consecutive segment breaks makes sense to me. Seems like limiting it to only one is an error. The only thing that shouldn't change is that, if there's a space or tab somewhere in that sequence, the sequence becomes a space and not nothing.

**Comment by upsuper** [comment]
For those rules, I don't think there can be any whitespace or tab in their input, because whitespaces should have been removed by step 1 of [Phase I](https://drafts.csswg.org/css-text-3/#white-space-phase-1) if there is any segment break.

**Comment by fantasai** [comment]
Oh, right. Yeah, that's probably more correct. :)

**Comment by fantasai** [comment]
Agenda+ to confirm the fix.
