### ISSUE TITLE
[css-view-transitions-1] UA CSS should add transform-origin to view-transition-group

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8370]
The UA CSS should have the following rule on view-transition-group:

```css
transform-origin: top left;
```

This is because the dynamic transform computed [here](https://drafts.csswg.org/css-view-transitions-1/#setup-view-transition:~:text=A%20transform%20that%20would%20map%20element%E2%80%99s%20border%20box%20from%20the%20snapshot%20root%20origin%20to%20its%20current%20visual%20position.) should be with respect to the top left corner of the element. Given that the element's bounds will also animate during the transition, it makes sense.

**Comment by astearns** [comment]
I’d like to see at least one other person agree to the proposed resolution here before trying the async route. What happens when authors override the UA default? Are there no writing mode or direction concerns with a top left default?

**Comment by khushalsagar** [comment]
> What happens when authors override the UA default? Are there no writing mode or direction concerns with a top left default?

Devs changing the UA default would lead to unpredictable behaviour no matter what the default is. Since the `transform` value computed by the UA for the group will assume a particular value for `transform-origin`. The writing mode/direction is a good point. Its not intuitive for the transform to be relative to the top-left corner for RTL writing mode.

I'm going to close this issue then. The current spec uses the default value of `transform-origin` which is relative to the center of the box. That makes most sense in that it is immune to writing mode/direction.
