### ISSUE TITLE
[web-animations-1] Procedure to reset pending tasks is defined in an unrelated section

### ISSUE THREAD

**Issue by ninevra** [w3c/csswg-drafts#8373]
The [procedure to reset an animation's pending tasks](https://w3c.github.io/csswg-drafts/web-animations-1/#animation-reset-an-animations-pending-tasks) is defined in section [4.4.2](https://w3c.github.io/csswg-drafts/web-animations-1/#setting-the-associated-effect), but only ever referenced in section [4.4.14](https://w3c.github.io/csswg-drafts/web-animations-1/#canceling-an-animation-section).

This appears to be because the procedure was previously referenced in 4.4.2, until 2e56cd7d77f17f9931cd0024be79e498ad1f60bb.

It's not important, but just a tiny bit confusing.

**Comment by birtles** [comment]
Thank you! Hopefully fixed now!
