### ISSUE TITLE
[css-cascade-6] Scoped selectors shouldn't match the scope root unless explicitly requested with :scope?

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#8377]
This was suggested by @bramus in an offline conversation.

In the [current cascade-6 specification](https://drafts.csswg.org/css-cascade-6/), the `@scope` rule defines a 'scope' as a tree fragment that includes the scope root (`:scope`) element, but does not include any lower-boundary elements, or their decedents. Since the scope-root is 'in scope', [it can be matched by scoped selectors](https://codepen.io/miriamsuzanne/pen/BaPORxP):

```css
@scope (div.scope) {
  /* This selector will match the :scope element */
  div { ... }

  /* :scope can be explicitly excluded */
  div:not(:scope) { ... }
}
```

While it's possible to exclude the scope-root from selectors by appending `:not(:scope)` - we could consider doing it the other way around. For example, a 'shadow host' is not matched by selectors in the shadow DOM unless `:host` is explicitly specified. The scope-root would still need to be 'available' to scoped selectors, but it would only match when specifically mentioned:

```css
@scope (div.scope) {
  /* This selector WOULD NOT match the :scope element */
  div { ... }

  /* :scope can be explicitly included */
  div, :scope { ... }
}
```

On the one hand, it may be strange to have an element that is available 'in scope' but not matched by default. On the other hand, authors are likely to expect that matched elements will be 'nested' inside the scope-root selector. In either case, we would have a reasonable workaround for the counter-examples.

**Comment by tabatkins** [comment]
The other way to exclude the scope is just `* > ...`, right? And when nesting you can just do `> ...`, which might be simple enough to be worth leaving it as the way to handle things.

Note that the host element is *unmatchable* except by the `:host` pseudo; it's not contextual in the selector itself. That is, you can't write `:host.foo` - by definition the `.foo` won't match the host element. I suspect that it'll be relatively common to want to match additional selectors against the scope, tho. For host elements we allow that with a functional form - `:host(.foo)`, but we don't (yet?) have a `:scope()` functional form.

I lean weakly towards "no change", then.

**Comment by mirisuzanne** [comment]
I suppose `> *` might imply a starting `&`, which would be treated as `:scope` in this case? But `* > *` could still match the scope root itself.

**Comment by tabatkins** [comment]
Oh duh, right. Well yeah, at least the Nesting version would work by default, yeah.

**Comment by romainmenke** [comment]
> I suppose it's not clear to me if you're allowed to leave the & off those selectors, when not in a nested style rule? Maybe that needs to be clarified? At the very least, all your example selectors seem to be allowed if you start them with &, which is normally implied by a relative selector.

I suggested to allow relative selectors in more contexts here : https://github.com/w3c/csswg-drafts/issues/8010

**Comment by mirisuzanne** [comment]
Digging into this, I'm convinced that authors will expect 'nested by default' behavior - which would better match how nesting works as well. To get there, we don't actually want to _remove_ the scope root from the scope. We only want to imply that the scoped element is prepended as an ancestor, unless otherwise explicitly placed in a selector. This would bring `:scope` and `&` more fully in line. Both already have the same specificity, and the same is-like parent-element matching logic already. 

This is a bit different from the ['virtual' scoping root behavior defined for dom fragments](https://w3c.github.io/csswg-drafts/selectors/#scope-pseudo), the primary use of `:scope` currently. According to the spec, document fragment roots can be mentioned in a scoped selector, but can't be the subject of the selector. If we have to match that behavior, I think it would be too restrictive.

If we go that rout, it's not an exact parallel with `:boundary` or `:scope-end`. On the root side, we're defining an implied ancestor/descendant relationship between selectors. On the lower boundary, we would have an element that is fully _out of scope_ for some selectors, and fully _in scope_ for other selectors. That might also be useful, but it would need a different mechanism for describing the behavior.

**Comment by tabatkins** [comment]
> According to the spec, document fragment roots can be mentioned in a scoped selector, but can't be the subject of the selector. If we have to match that behavior, I think it would be too restrictive.

Yeah, that restriction is only because doc fragments aren't elements, and selectors are defined to operate over elements. It shouldn't be taken as a more general restriction on :scope.

**Comment by mirisuzanne** [comment]
In that case, my proposed resolution is that scoped selectors are implicitly descendants of the scope root element, unless `:scope` appears explicitly in the selector - matching the behavior of nested selectors with or without the explicit `&`.

I think something like `:scope-end` might be useful, but could have it's own issue.

**Comment by mirisuzanne** [comment]
Agenda+ to resolve on that change.

**Comment by andruud** [comment]
+1, this is great. I think it opens up some new ways of optimizing.

> unless :scope appears explicitly in the selector

This means we'll add something like the "nest-containing" concept but for scoped selectors, right?

**Comment by tabatkins** [comment]
I suppose, yeah. A little more annoying to do the "if you see something that even *resembles* a :scope, mark the selector and preserve it in forgiving lists", but not untenable.

Hm, this will require a small edit to Selectors, tho - the restriction against matching the scoping root itself *is* in fact baked into [the matching algorithm](https://drafts.csswg.org/selectors/#match-against-tree), so I'll need to account for this there.

**Comment by mirisuzanne** [comment]
@tabatkins can you clarify that 'anything that even resembles a :scope'? Is that meant to account for using `&` in a scoped context?

The main difference I see here is that `:scope` is intended to match _only_ the root element of a given scope - not to represent all possible matched elements of the scoping selector. I don't think we want `:scope :scope` to match anything (there can't be a second scoping element), while that is possible with `& &`. But that maybe causes a problem for treating `&` like `:scope` in a scoped context.

**Comment by tabatkins** [comment]
"contains the nesting selector" has that special text where we look for an & token *in the original tokens*, before potentially throwing anything out for invalidity, so `:is(:unknown(&), div)` still counts as containing the nesting selector regardless of whether the browser understands the `:unknown()` pseudo or not. (We can't tell that `:unknown()`'s argument is meant to be a selector, after all!) We'd need to apply the same logic to `:scope`.  This is unrelated to anything about match semantics.

----

> But that maybe causes a problem for treating & like :scope in a scoped context.

[As currently specced](https://drafts.csswg.org/css-nesting/#nesting-at-scope), `&` does indeed match all the elements matched by the scope-start selector, rather than something more specific that only matches the single element that happens to be the scoping root for a given element.

**Comment by mirisuzanne** [comment]
That makes sense, yes. 

For matching semantics with `&` in a scoping context, I see a couple options:

1. Scoped `&` is identical to `:scope`, and only matches the root element. It makes the selector _scope-containing_, and `& &` wouldn't match anything. 
2. Scoped `&` refers to the scoping root selector, rather than the scoped element itself. That allows `& &` to be resolved as per usual, but then either:
    a. It continues to make the selector scope-containing, so there is no implied ancestor `:scope`
    b. It is not scope-containing, so a bare `&` would be treated as `:scope &`
3. Revert the pervious decision, and don't allow `&` directly in `@scope`

Laying out those options, I think 2a is the one that would match expectations most accurately.

**Comment by tabatkins** [comment]
Agreed, I think 2a is the clearest - maintains & semantics from general usage, but also interfaces with `@scope` in a reasonable and intuitive way.

**Comment by andruud** [comment]
[Why is it that the second css-nesting comes into the picture there's a list with options and suboptions? :P]

(2a) I'm not sure it's very consistent to disable the implied `:scope` when nothing in the selector actually represents `:scope`. 2b seems more consistent.

**Comment by mirisuzanne** [comment]
Yeah, 2b is semantically 'cleaner' in some ways (both selectors maintain their behavior), but I think this would be very surprising to authors, and not a meaningful way of supporting `&` in a scoped context. Authors will expect these to reference the same elements:

```css
.media {
  & > img { ... }
}

@scope (.media) {
  & > img { ... }
}
```

In the current spec, that works because we don't imply an initial `:scope`. But if we go with 2a, we've broken that expectation.

**Comment by bramus** [comment]
> Authors will expect these to reference the same elements:
> 
> ```css
> .media {
>   & > img { ... }
> }
> 
> @scope (.media) {
>   & > img { ... }
> }
> ```

That’s also the case with option 1, no? The way I read that option, is that inside `@scope (…) { … }` the contents are implicitly wrapped in a `:scope { }` block?

So that this … :
```css
@scope (.media) {
  & > img { ... }
}
```

… equals that:
```css
@scope (.media) {
  :scope {
    & > img { ... }
  }
}
```

That would essentially make `:scope` useless inside `@scope`, as one would need to use `&` instead … but maybe that’s OK?

---

> [Why is it that the second css-nesting comes into the picture there's a list with options and suboptions? :P]

🙈

**Comment by bramus** [comment]
> That would essentially make `:scope` useless inside `@scope`, as one would need to use `&` instead … but maybe that’s OK?

Come to think of it: for `@sibling-scope` that might be weird, as one might want to target the start and end boundaries there. Using `&` for the start boundary and something like `:scope-end` for the end boundary seems inconsistent.

**Comment by mirisuzanne** [comment]
I think in both css nesting and scope we want to think of it as an implicit descendant combinator, not an implicit extra level of nesting.

**Comment by mirisuzanne** [comment]
The proposed resolution here is: 

- Scoped selectors are implicitly descendants of the scope root (this matches css-nesting)…
- Unless they are _scope-containing_, with either `:scope` or `&` explicitly placed in the selector (the matches and expands on css-nesting)
- In a scoped selector, `:scope` refers to the scope root element (cannot match additional nested elements), while `&` refers to the scoping selector (can match additional nested elements).

This builds on (and clarifies) the resolution in #7854 that `&` should be allowed in a scoping context. It also ensures that scope and nesting behave in similar ways where they overlap.

**Comment by bramus** [comment]
Proposed resolution SGTM.

Maybe we can also consider `:scope-end` to target the end boundary along with this as it’s very closely related? Happy to branch off a new issue _([as suggested here](https://github.com/w3c/csswg-drafts/issues/8377#issuecomment-1431650206))_ if we can’t tackle it all in one go.
