### ISSUE TITLE
[css-values-5] Minor problems on `toggle()` and `random-*()` productions

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8384]
**[`toggle()`](https://drafts.csswg.org/css-values-5/#funcdef-toggle)**

`toggle()` cannot be extracted by `w3c/reffy` because it is not defined in a production rule. I do not know if you want to declare it as a function or type. I do not know what difference it makes.

---

**[`random-item()`](https://drafts.csswg.org/css-values-5/#funcdef-random-item)**

I think `<any-value>` is inappropriate in `<random-item()>` and should be replaced with `<declaration-value>?`, because `<any-value>` allows top-level `;` and because custom properties accept empty inputs (like in `<mix()>`, see #8556):

`<random-item()> = random-item( <random-caching-options> ';' <any-value> [ ';' <any-value> ]* )`

---

**[`random()`](https://drafts.csswg.org/css-values-5/#funcdef-random)**

Finally, the trailing `;` in the production for `<random()>` seems to be a typo:

  > `<random()> = random( <random-caching-options>? , <calc-sum>, <calc-sum>, [by <calc-sum>]? );`

**Comment by cdoublev** [comment]
**Aside:** could you please tell me what `q` stands for in `<q-name>` in `attr()` (`q`ualified?), and `<wq-name>` in `<attribute-selector>`, and why different productions are used?

**Comment by tabatkins** [comment]
`<q-name>` is a typo; it should be `<wq-name>`. "wq" is taken from the XML specs, where it stands for "well-qualified", meaning "a namespace + localname pair".

> Similarly, I think `<any-value>` is inappropriate in `<random-item()>`, and should be replaced by `<declaration-value>`

Yes.

> I do not know if you want to declare it as a function or type. I do not know what difference it makes.

A function. It changes how I do some processing in bikeshed, but most notably how they autolink - you can link to a function with `''foo()''`.

> Finally, the trailing ; in the production for <random()> seems to be a typo:

Not necessarily a typo, I just forget whether we separate production definitions with a semicolon or not. ^_^

**Comment by cdoublev** [comment]
I edited the initial comment of this issue to remove my suggestion to replace `<any-value>` with `<declaration-value>` in `toggle()`, since it has been replaced with `<whole-value>`.

I am not sure why this change has not been applied to `random-item()` though.
