### ISSUE TITLE
[CSS2] computed value of line-height

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#8385]
The [CSS2 spec for the `line-height` property](https://w3c.github.io/csswg-drafts/css2/#propdef-line-height) says that its computed value is

> for [&lt;length>](https://w3c.github.io/csswg-drafts/css2/#value-def-length) and [&lt;percentage>](https://w3c.github.io/csswg-drafts/css2/#value-def-percentage) the absolute value; otherwise as specified

which implies that when `line-height` is specified as a &lt;number>, we'd expect its computed value to be the same &lt;number>.

However, none of the browsers I've tried seems to behave this way; they all return an absolute &lt;length> for the computed `line-height`:

Safari:
```
document.body.style.lineHeight = "1.5"; window.getComputedStyle(document.body).lineHeight
"24px" = $1
```

Chrome:
```
document.body.style.lineHeight = "1.5"; window.getComputedStyle(document.body).lineHeight
'19.5px'
```

Firefox:
```
document.body.style.lineHeight = "1.5"; window.getComputedStyle(document.body).lineHeight
"24px"
```

Accordingly, should the spec be updated (or superseded by a new definition of `line-height` in CSS Text or CSS Fonts?) to reflect reality, or is this a bug in all the browsers?

(The only place I've actually seen a &lt;number> returned for the computed value is in the `font` shorthand in Firefox:
```
document.body.style.font = "bold 12px/1.5 serif"; window.getComputedStyle(document.body).font 
"700 12px / 1.5 serif"
```
which is inconsistent with what it returns for the `line-height` longhand on the same computed style, and I propose to fix this in https://bugzilla.mozilla.org/show_bug.cgi?id=1813536.)

**Comment by Loirooriol** [comment]
`getComputedStyle` doesn't provide the computed value, it's the resolved value. See https://drafts.csswg.org/cssom/#resolved-values

> - `line-height`
>     The [resolved value](https://drafts.csswg.org/cssom/#resolved-value) is `normal` if the [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value) is `normal`, or the [used value](https://drafts.csswg.org/css-cascade-5/#used-value) otherwise.

You can see that `1.5` computes as-is via inheritance.

**Comment by jfkthame** [comment]
Oh, of course... never mind, then.
