### ISSUE TITLE
[css-values-5] Require two or more `random-item()`s

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8386]
I am not sure whether the current requirement of one or more random items in [`random-item()`](https://drafts.csswg.org/css-values-5/#random-item) is intentional or if it should be two or more:

```diff
- <random-item()> = random-item( <random-caching-options> ';' <declaration-value> [ ';' <declaration-value> ]* )
+ <random-item()> = random-item( <random-caching-options> ';' <declaration-value> [ ';' <declaration-value> ]+ )
```

Alternatively:

`<random-item()> = random-item( <random-caching-options> [ ';' <declaration-value> ]{2,} )`

**Comment by brandonmcconnell** [comment]
@cdoublev I think one or more would be better, so when we `spread()` values arbitrarily (re #8391), they can contain any non-zero number of values.

**Comment by tabatkins** [comment]
The current restriction is intentional. It's perfectly well-defined to select from a list of length 1, and consistent with the behavior of lengths >1. (As opposed to an empty list, which would have to have some novel behavior.)

**Comment by cdoublev** [comment]
Thank you both for your clarification.
