### ISSUE TITLE
Pardon (about CSS4 images `element`)

### ISSUE THREAD

**Issue by acterhd** [w3c/csswg-drafts#84]
Pardon for propose. We have difficulties with rendering `element()`. I speaked with Chromium devs, I understand that they can only render: `canvas`, `video` or `img`  i.e. paint source based. I beg to divide `element()` to low level functions: subject (i.e. `element()` that capture from DOM) and `source()` (that capture from `CSS.elementSources` i.e. paint sources). For me really difficult understand `element()`. 

https://github.com/w3c/csswg-drafts/tree/master/css-images-4
PLEASE! Merge Paint Sources spec to `source()`. 

Copy: 
https://lists.w3.org/Archives/Public/www-style/2015Dec/0197.html

**Comment by acterhd** [comment]
https://lists.w3.org/Archives/Public/www-style/2015Dec/0197.html

**Comment by tabatkins** [comment]
Please don't open threads in both the mailing list and the GH repo. Closing this.
