### ISSUE TITLE
[scroll-animations-1] animation-range vs animation-duration

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8405]
If `animation-range-start`, `animation-range-end`, and `animation-duration` are all set, and duration doesn't exactly match the available range, what do we do?

Options proposed so far:
* Ignore `animation-range-end`.
* Ignore `animation-duration`.
* Take the smaller duration.

Related question: if `animation-duration` and `animation-range-end` are given but not `animation-range-start`, do we:
* define the range as the normal timeline start through the specified range end? (pins the duration at the start of the timeline)
* scope the animation to the given duration, pin it to the specified `animation-range-end`, and calculate the used value of `animation-range-start` accordingly?

Fwiw, my original interpretation was that the `animation-range` properties each (independently) cut the timeline down to a particular segment, and then duration and delay play within that segment instead of within the whole timeline.

An alternative view would be that `animation-range` is similar to `inset`, `delay` to `padding` or `margin`, and `duration` to `width`, and they operate as a set at the same time.

Which worldview do we want to go with? (Or something else?)

**Comment by flackr** [comment]
> Fwiw, my original interpretation was that the animation-range properties each (independently) cut the timeline down to a particular segment, and then duration and delay play within that segment instead of within the whole timeline.
>
> An alternative view would be that animation-range is similar to inset, delay to padding or margin, and duration to width, and they operate as a set at the same time.

The nice thing about thinking of animation range in this alternative view is that it is effectively css keywords for specifying the animation start time and end time - whereas the former is a new concept.

**Comment by fantasai** [comment]
Thinking about this more while working on the [iteration count edits](https://github.com/w3c/csswg-drafts/issues/8233), I think the model we should go with is:
- The animation is attached to a timeline. But more specifically, it is attached to a timeline _attachment range_. By default this is the entire timeline, which in the case of a scroll-driven timeline is finite, and in the case of a time-driven timeline is infinite. The _attachment range_ is the portion of the timeline that the animation is laid out in (somewhat analogous to a _containing block_).
- The start/end of this attachment range can be controlled with `animation-range`.
- Any resizable aspects of the animation will stretch or squish to fit the attachment range (like flex items inside a flex container). So if the duration is flexible (`auto`), then we fill the whole range. If the duration is inflexible, then we pin the animation to its start point.
- Delays are like margins. They don't change the _attachment range_, but they reduce the amount of space available for the “content” and shift it accordingly. The initial value of a delay is `auto`, which functions like `0` except when there's additional constraints.
- If there's an iteration count, we repeat that many times within the “available space” in the _attachment range_ (reduced by any delays). If the duration is flexible, it is reduced to fit (like multi-col column widths given a `column-count`). If the duration is inflexible, additional iterations may overflow the _attachment range_. However...
- While animation frames outside the _attachment range_ are used for interpolation, they are not part of the _active interval_ of the animation. The animation ends at the end of the _attachment range_ (similar to how content outside a scroll container impacts layout but is not visible).

CC @flackr @birtles

**Comment by flackr** [comment]
@fantasai that is my working model as well (I thought it was the model we had already TBH 😄 ) and would be consistent with the proposed resolution of animation-range "winning" if all three are specified. I agree with all of the points.

**Comment by fantasai** [comment]
> animation-range "winning" if all three are specified

(I would have interpreted that as the range end shortening the duration, not clipping the animation, so I thought they're different.)
