### ISSUE TITLE
[scroll-animations-1] naming the initial value of animation-range

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8406]
This depends a bit on https://github.com/w3c/csswg-drafts/issues/8405 and how we want to think about `animation-range`.

The two keywords under consideration are: `normal` and `auto`.

* `normal` implies a bit more that `animation-range-start/end` take their "normal value". (Currently the initial value uses the start/end of the timeline, so I think it's more appropriate as defined right now.)
* `auto` implies a bit more that an `animation-range-start/end` value is calculated based on something. (This might be more appropriate if we calculate the used value of these properties based on other properties in some way.)

**Comment by flackr** [comment]
`normal` / `auto` only calculate to be the start/end of the timeline for a non-monotonically increasing timeline. Monotonically increasing timelines like the document timeline do not have an end and the start is a long time in the past.

When this default value keyword is used on a regular document timeline animation the range start would be calculated to be the time on the timeline when the animation starts, equivalent to the [animation's start time](https://drafts.csswg.org/web-animations-1/#animation-start-time). The range end would calculate to the effective [animation end time](https://drafts.csswg.org/web-animations-1/#end-time).
