### ISSUE TITLE
[css-overflow-4] Require positive `<integer>` for `max-lines` specified in `*-line-clamp`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8409]
The syntax of [`max-lines`](https://drafts.csswg.org/css-overflow-4/#propdef-max-lines) requires a positive `<integer>` whereas this restriction does not exist for `line-clamp` and `-webkit-line-clamp`.

```diff
  Name: line-clamp 
- Value: none | <integer> <'block-ellipsis'>?
+ Value: none | <integer [1,∞]> <'block-ellipsis'>?

  [...]

- <integer> 
+ <integer [1,∞]> <'block-ellipsis'>?
    Sets max-lines to the specified <integer>, continue to discard, 
    and the block-ellipsis property to second component of the value or to auto if omitted.
```

https://drafts.csswg.org/css-overflow-4/#line-clamp

```diff
  Name: -webkit-line-clamp 
- Value: none | <integer>
+ Value: none | <integer [1,∞]>
```

https://drafts.csswg.org/css-overflow-4/#webkit-line-clamp

**Comment by Loirooriol** [comment]
`CSS.supports("-webkit-line-clamp", "0");` is false in Blink/WebKit.
