### ISSUE TITLE
[mediaqueries-4] any-hover can't be used to detect mixed hover and non-hover capable pointers

### ISSUE THREAD

**Issue by patrickhlauke** [w3c/csswg-drafts#841]
Relates to  https://drafts.csswg.org/mediaqueries-4/#any-input

A more focused successor to https://github.com/w3c/csswg-drafts/issues/737, only covering `any-hover` (as I can now rationalise better why `any-pointer` behaves the way it does, which I tried to more explicitly point out in #842)

`any-hover`, as currently specified, only evaluates to `none` when ALL detected pointing mechanisms are non-hover-capable. This currently makes it impossible to query specifically if some, but not all, of the pointing mechanisms is non-hover-capable (or conversely, to test if ALL detected pointing mechanisms are hover-capable)

Assuming two or more pointing devices are present, you can currently only test:

- at least one of the devices is hover-capable - `any-hover:hover` will evaluate to true (and currently, regardless of whether any of the other pointing devices is non-hover-capable, `any-hover:none` will be false)
- none of the devices is hover-capable - `any-hover:hover` will evaluate to false, `any-hover:none` evaluates to true

Scenarios that can't be tested (as they return the same as the "at least one..." scenario above):

- at least one, but /not/ all, device is non-hover-capable - `any-hover:hover` will evaluate to true, `any-hover:none` will evaluate to false
- /all/ devices are hover-capable - `any-hover:hover` will evaluate to true, `any-hover:none` will evaluate to false

As the UA should be able to ascertain the total number of pointing devices (since it needs to know this in order to properly evaluate `any-pointer`, presumably), it should be possible (and not require some special "we need to define what an input is" additional consideration, which was the major argument against #737) to also change when `any-hover:none` evaluates as follows:

- if ANY inputs are present that are non-hover capable, `any-hover: none` should evaluate to true
- if ANY inputs are present that are hover capable, `any-hover: hover` should evaluate to true
- if ALL inputs that are present are non-hover capable, `any-hover: none` should be true and `any-hover: hover` should be false
- if ALL inputs that are present are hover capable, `any-hover: none` should be false and `any-hover: hover` should be true
- if a mix of hover-capable and non-hover capable inputs is present, both `any-hover: none` and `any-hover: hover` should evaluate to true

Going back to the original scenarios, this would then allow to capture all possible states:

- at least one of the devices is hover-capable - `any-hover:hover` will evaluate to true (as before)
- none of the devices is hover-capable - `any-hover:hover` will evaluate to false, `any-hover:none` evaluates to true (as before)
- at least one, but /not/ all, device is non-hover-capable - `any-hover:hover` will evaluate to true, `any-hover:none` will also evaluate to true; this is a new capability that couldn't be tested before
- /all/ devices are hover-capable - `any-hover:hover` will evaluate to true, `any-hover:none` will evaluate to false; this is also a new capability that couldn't be tested before (with the change to `none`, this now actually gives you confidence in the `any-hover:none` to mean "none of the pointing devices is non-hover-capable)

**Comment by frivoal** [comment]
* This goes against the normal meaning of `none` which is supposed to be true when other values are not. Changing that hurts consistency and understandability, so that's not desirable. An alternative would be better, or you need very strong reasons.

* I am not convinced I understand the use case. Yes, in theory, the more information you have, the better you can make informed decisions. However, if that makes simple cases harder to do correctly (see first point), that's not a good idea. And if we expose more info but still not enough info to make different decisions, we've gained nothing.

I do not understand what use cases would be served by your proposal. Yes, you have strictly more information, but since that's still not an exhaustive list of all the inputs and how they are being used, that's not enough to do fine grained detection of various specific scenarios to which you might want to adapt to.

If you have no idea what the (non-primary) devices are, nor how the user uses them, what can you do differently based on the knowledge that some of them can hover vs all of them can hover?

Thanks to the primary / non primary distinction, you can already know that the normal way of interacting with the device is hover-incapable, but that the user may have additional means of hovering at their disposition. So you know that you should not depend on hovering for essential functions(`hover:none`), but that if you offer additional conveniences based on hover, the user may take advantage of them (`any-hover:hover`). What can you do differently with the additional bit of information you're proposing?

**Comment by patrickhlauke** [comment]
> Thanks to the primary / non primary distinction, you can already know that the normal way of interacting with the device is hover-incapable, but that the user may have additional means of hovering at their disposition. So you know that you should not depend on hovering for essential functions(hover:none), but that if you offer additional conveniences based on hover, the user may take advantage of them (any-hover:hover). What can you do differently with the additional bit of information you're proposing?

with the proposed change, you can detect the opposite situation that may lead you to the same decision.

the primary being hover capable (`hover:hover`), but that other inputs the user may use are not (proposed `any-hover:none`), which can lead you to the same decision - not to rely completely on hover-based interactions, because the user may well be using/switch to using one of the other pointer-based inputs, so perhaps (even though the primary is hover capable) treat it as a convenience.

**Comment by patrickhlauke** [comment]
because if you aknowledge that the "offer hover as a convenience"  scenario is a valid one, then authors should be able to base that decision both when the primary is not hover capable, or if at least one of the secondary inputs is not hover capable (and with the proposed change they can also differentiate the two of course, based on the value of the primary `hover:...`). you could argue "but once authors know the primary is/isn't hover capable, that's all they need", but that still gives undue prominence to what the primary pointer does. authors can of course choose to just go mainly by what the primary does, but this allows them some additional granularity in how they base their final decision.

**Comment by patrickhlauke** [comment]
scenario here would be for instance: laptop with a touchscreen. primary input is the trackpad/mouse (`hover:hover`). the touchscreen is not hover capable. currently authors cannot detect that beyond the primary input which is hover capable there is also a non-hover capable pointer input (the touchscreen). they can decide "ok, since `hover:hover` is true, i'm good to rely on hover. which works fine ("for the majority of the time", if we take the primary pointer to be indeed the one used most frequently), but as soon as the user does switch to using the touchscreen, things will not work, forcing the user to revert back to using the trackpad/mouse.

with the proposed change, authors would be able to see that yes, while `hover:hover` is true, `any-hover:none` is also true. that then leaves authors the ability to say "ok, even though i could just rely on hover-based stuff for the majority of the time, there may well be cases where the user switches to whatever non-hover-capable pointer input the browser also detected...maybe i should cater for this scenario too". they don't have to, but if they do want to, they can detect this situation too (what they then do is up to them...whether they decide to forego all hover-based stuff on the offchance that the user may switch to the secondary pointer, or whether they load in additional styles/show additional controls/load new scripts to make sure non-hover-capable pointers can also be used...that's up to them)

**Comment by patrickhlauke** [comment]
@frivoal ... did the above make sense to clarify my particular desire/use case?

wondering, if there is definitely no chance to change the way `any-hover:none` is evaluated, if there's any mileage in defining an additional value such as `any-hover:mixed`, `any-hover:partial` or similar to signal "some of the pointer devices support hover, others don't"

**Comment by frivoal** [comment]
@patrickhlauke 

In the case of a touch-pad+touch-screen laptop, the touch pad is never very far away, so if some aspects of the UI are only conveniently used with the pad, I do not think users are greatly inconvenienced by being required to use it.

Note that I think that making any essential part of the UI depending on hovering is generally a bad idea, as it is not very discoverable, not very friendly to users with limited skills or ability to use the pointing device, and gets in the way of keyboard users. So I believe that authors should always be very careful before adding anything that needs hover to work, as opposed to taking advantage of hover when it happens without relying on it. The argument is similar for accurate pointing.

However, once an author has taken the decision to build some part of the UI in a way that needs hovering, the presence of a touch screen in addition to the touchpad or mouse is unlikely to affect that decision much, anymore than the presence of a tab key.

On the other hand, on a laptop where the touch screen can be detached from the keyboard+touchpad part and used as a tablet, then the UA would be expected to change the pointer and hover media features to reflect only the touch screen when detached. In this scenario, the inconvenience that would be caused to the user by presenting a hover-only UI would be much greater, and is covered by the current design of the feature.

In my opinion, when it comes to this (or to pointing accuracy), the best practice is for authors to think along these lines:

Case 1:
- Can I rely on hovering / pointing / accurate pointing?
- Probably not, it makes things worse for lots of people
- But I really want to, it simplifies things quite a bit in this particular case, and the alternative is much worse
- Ok then, does the primary input let people do that conveniently?
  - Yes => Ok, but don't go overboard
  - No => don't rely on it then

Case2: 
- Can I use hovering / pointing / accurate pointing to trigger non essential niceties?
- Does it have any negative side effect (visual clutter, increased difficut)?
  - No => do it, regardless of device capabilities. If it doesn't trigger, no big deal
  - Yes, but the trade-off is worth it => Does the user have any device they could actually trigger this with?
    - No => Don't do it then
    - Yes => OK, but don't go overboard.

Neither of these require the ability to detect the situation where the primary device and some (but not all) of the non-primary ones can hovering / point / point accurately. If we could provide this information at no cost to anyone, this would still be worth doing. But in this case, I think that it does have a cost: depending on how we design it would either:
  - make this media feature unusable in a boolean context, if values are `hover` and `no-hover`, neither of which is falsy
  - inconsistent with how other media features work in a boolean context, if `none` and `hover` can be true at the same time
  - be misleading if `none` or `no-hover` **do not** trigger when some of the input devices are neither capable of hovering nor pointing (e.g: a keyboard), as the reasoning you proposed for touchscreen+mouse applies equally well to keyboard+mouse
  - make the feature hard to define if `none` or `no-hover` **do** trigger when some of the input devices are neither capable of hovering nor pointing, as we now need to worry about whether a thing that can neither point nor hover is an input device or not, to know whether it should influence that query

Based on that, I'd rather keep the feature as it is. However, I do recognize that this is subjective ones, and that reasonable people can see disagree.

Unless I have convinced you (in which case you can close the issue), this probably needs a CSSWG discussion and decision.

Marking as "Agenda+" to schedule this for a teleconference.

**Comment by patrickhlauke** [comment]
> However, I do recognize that this is subjective ones, and that reasonable people can see disagree.

Glad to know I'm reasonable :)

In seriousness, I agree that what you outline in terms of how an author should treat hover is reasonable. Plus, with the additional text I added in https://github.com/w3c/csswg-drafts/pull/715 which strongly suggests that authors should still not rely on hover to take account of any other non-hover-capable inputs and the note I added in https://github.com/w3c/csswg-drafts/pull/842/files#diff-86306790afb9d5330bbdda192a7b99f6R1783 we've probably got at least a warning to authors of potential gaps in what they can detect, which would hopefully temper their enthusiasm when `any-hover:hover` evaluates to true.

Nonetheless, I'd be interested in what others in the CSSWG think (to either changing when `any-hover:none` evaluates or the potential for a third partial/mixed value.

**Comment by tantek** [comment]
@patrickhlauke can you add https://drafts.csswg.org/mediaqueries-4/#any-input to the initial issue description at the top! Much thanks. (p.s. I tend to agree with your line of reasoning here and am trying to understand it better)

**Comment by frivoal** [comment]
@patrickhlauke in the log above, pushing the scripting MQs to L5 is not related to this issue.

Other than that, the WG felt that the use cases for being able to detect mixed hover and non-hover capable pointers were not compelling enough to justify the complexity needed to make that work, and decided to close this issue as no change.

However, recognizing that the whole set of pointer/any-pointer/hover/any-hover was not the part of the spec we're most confident it, and that it is possible that as implementations come in contact with reality or as we learn more about use cases, we may still need to adjust, we marked them at risk. That way, if need be, we can pull them to level 5 to tweak them some more without slowing down the rest of the spec.

Since this is a rejection of this issue you raised, I realize this is not the conclusion you were hoping for, but is this a conclusion you are willing to live with?

**Comment by patrickhlauke** [comment]
@tantek done

@frivoal at least the current shortcoming of `any-hover` is documented in the spec, so i'd say for now i can live with it. closing...
