### ISSUE TITLE
What should `getComputedStyle(e).whiteSpace` be?

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#8411]
The [`white-space` property in CSS Text Level 4](https://w3c.github.io/csswg-drafts/css-text-4/#white-space-property) is defined as a shorthand.

It has a special mapping table for existing values of `white-space`, but what should `getComputedStyle(e).whiteSpace` be when longhands are not in the mapping table?

For example:
```css
white-space: normal;
text-wrap: balance;
```
Then what should `getComputedStyle(e).whiteSpace` be?

In the Blink discussion, some thinks it should be an empty string, because the longhands are not in the mapping table. Another interpretation was to return `balance` or `collapse balance none` since it's a shorthand.

Clarification is appreciated in advance.

**Comment by Loirooriol** [comment]
Properties should always serialize into something that's valid according to their grammar, or empty string if not possible.
So in this case it's empty string, just like

```js
document.body.style.cssText = 'border: solid; border-image: url("#a")';
document.body.style.border; // ''
getComputedStyle(document.body).border; // ''

document.body.style.cssText = 'grid: 1px / 2px; grid-auto-flow: column';
document.body.style.grid; // ''
getComputedStyle(document.body).grid; // ''
```

Dang, both computed style cases are broken in Blink/WebKit :facepalm:

**Comment by Loirooriol** [comment]
This is defined in https://drafts.csswg.org/cssom/#serialize-a-css-value

> If there is no such shorthand or *shorthand* cannot exactly represent the values of all the properties in *list*, return the empty string.

**Comment by kojiishi** [comment]
Thanks for the quick answer, it is super clear now. Got the same reply from @dbaron too.
