### ISSUE TITLE
[css-cascade] Define animation type of `all` as `not animatable`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8414]
Some shorthands that have non-animatable sub-properties are defined with `not animatable` as the value of the field *Animation Type* in their definition table, instead of `see individual properties`:

  - `not animatable`: [`animation`](https://drafts.csswg.org/css-animations-1/#propdef-animation), [`transition`](https://drafts.csswg.org/css-transitions-1/#propdef-transition), [`scroll-timeline`](https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline)
  - `see individual properties`: [`all`](https://drafts.csswg.org/css-cascade-5/#propdef-all), [`container`](https://drafts.csswg.org/css-contain-3/#propdef-container), [`view-timeline`](https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline)

`all` seems to be the only shorthand that have both animatable and non-animatable properties. I assume it is not animatable because Chrome/FF do not seem to animate it. Also, I think it would be non-trivial to filter declarations of its non-animatable properties during their expansion.

In practice, a shorthand animation type can be resolved from the animation types of its sub-properties, but it would be clearer to define it as `non animatable`.

**Comment by Loirooriol** [comment]
IMO shorthands should just expand into longhands, and then each longhand can animate according to its type, or not.

WebKit is able to animate `all`: [testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Adiv%20%7B%0A%20%20animation%3A%20anim%201s%20infinite%20alternate%3B%0A%20%20height%3A%20100px%3B%0A%20%20width%3A%20100px%3B%0A%20%20background-color%3A%20green%3B%0A%7D%0A%40keyframes%20anim%20%7B%0A%20%20from%20%7B%20all%3A%20initial%3B%20%7D%0A%20%20to%20%7B%20all%3A%20revert-layer%20%7D%0A%7D%0A%3C%2Fstyle%3E%0A%3Cdiv%3Ea%3C%2Fdiv%3E). `background-color` animates continuously, while `width` and `height` animate discretely between `100px` and `auto`.

**Comment by tabatkins** [comment]
Agreed, shorthands should be treated as an expansion to their longhands and animated as much as possible.

**Comment by cdoublev** [comment]
Right, [step 3 of resolving the effect value of a keyframe](https://drafts.csswg.org/web-animations-1/#the-effect-value-of-a-keyframe-animation-effect)) should discard declarations of non-animatable properties.

But keyframe rules only accepts animatable properties.

```css
@keyframes animation {
  to {
    container: container;
    view-timeline: timeline;
  }
}
```

Should `container` and `view-timeline` declarations be valid, even if all their sub-properties are `not animatable`?
