### ISSUE TITLE
Fatal errors on spec names  `css2`, `css-fonts-3` 

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#8432]
Bikeshed gives fatal errors on CSS-2023 (as it did on CSS-2022):

```
FATAL ERROR: Unknown spec name 'css2' on <index type="value"
FATAL ERROR: Unknown spec name 'css-fonts-3' on <index type="value"
```

I don't understand what the issue s with those two spec names. I tried `css-2` and also `css3-fonts` and got the same errors.

@tabatkins any hints?

**Comment by tabatkins** [comment]
Ah, I catch the css2 error in linking, but index generation goes a different path. The WebRef name for it is `css22`.

And WebRef doesn't index Fonts 3 (they skip a few older specs when the next level is a stable replacement), so I guess we should just remove it?

**Comment by svgeesus** [comment]
The trouble is that the [official definition](https://w3c.github.io/csswg-drafts/css-2023/#css-official) has a normative ref to CSS Fonts 3 (which is a Rec) while CSS Fonts 4, which is indeed a stable replacement and current work, and current implementation target, is nit a CR and is just an informative reference from [rough interop](https://w3c.github.io/csswg-drafts/css-2023/#rough-interop).

**Comment by svgeesus** [comment]
Aha but the indexes are not normative anyway so yeah, that solves it.
