### ISSUE TITLE
[css-conditional-4] Incorrect link pointed by `selector()`

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8433]
The [Additions since Level 3](https://www.w3.org/TR/css-conditional-4/#changes-from-L4) section has the `selector()` link pointing to https://drafts.csswg.org/scroll-animations-1/#valdef-scroll-timeline-source-selector, which is incorrect and misleading. The Editor's Draft [version](https://w3c.github.io/csswg-drafts/css-conditional-4/#changes-from-L4) doesn't have this link, though.

Spec link: https://www.w3.org/TR/css-conditional-4/

**Comment by yarusome** [comment]
Incidentally, the section name is "Additions since Level 3" but the section id is `changes-from-L4`.

**Comment by estelle** [comment]
Was just about to file this same issue.

* The link from the text `selector()` in the abstract points to points to [scroll animation](https://drafts.csswg.org/scroll-animations-1/#valdef-scroll-timeline-source-selector)

* The link from the text `selector()` in the changes section (see https://www.w3.org/TR/css-conditional-4/#changes-from-L4) - points to [scroll animation](https://drafts.csswg.org/scroll-animations-1/#valdef-scroll-timeline-source-selector). 

* The `selector()` function is listed in [terms defined by reference](https://www.w3.org/TR/css-conditional-4/#index-defined-elsewhere). It should instead be listed in [Terms defined by this specification](https://www.w3.org/TR/css-conditional-4/#index-defined-here)
 
These three links should likely point to https://www.w3.org/TR/css-conditional-4/#at-supports-ext or https://www.w3.org/TR/css-conditional-4/#typedef-supports-selector-fn

**Comment by svgeesus** [comment]
Most of these had now been fixed; I added the link to `#typedef-supports-selector-fn`.
