### ISSUE TITLE
[cssom][css-conditional] Should there be an interface for @supports rules?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#844]
https://drafts.csswg.org/cssom/#cssgroupingrule has no concept of `@supports` rules.  Maybe it should.

The way this works in Gecko is that there is a `CSSConditionRule` interface which inherits from `CSSGroupingRule` and has `.conditionText` on it.  Inheriting from this are `CSSMediaRule` and `CSSSupportsRule`; the latter is an empty interface for now.

**Comment by dbaron** [comment]
Also see:
* [Minutes 2012-08-13](https://lists.w3.org/Archives/Public/www-style/2012Aug/0749.html), where the CSSWG resolved to add CSSConditionRule and have a common .conditionText
* [Minutes 2012-09-05](https://lists.w3.org/Archives/Public/www-style/2012Sep/0072.html), where the CSSWG resolved to split CSSConditionRule into CSSConditionRule and CSSGroupRule
* [my email of 2012-12-06](https://lists.w3.org/Archives/Public/www-style/2012Dec/0102.html), explaining some spec prose related to .conditionText
* [@zcorpan's email 2013-06-18](https://lists.w3.org/Archives/Public/www-style/2013Jun/0331.html) suggesting to drop CSSConditionRule

Also note that the Conditional Rules spec has a [section on APIs](https://drafts.csswg.org/css-conditional/#apis) that does add a bunch of these interfaces.

**Comment by bzbarsky** [comment]
Aha, Conditional Rules is what I was looking for

**Comment by tabatkins** [comment]
Issue superceded by #851
