### ISSUE TITLE
[cssom][css-conditional] CSSOM and CSS Conditional Rules disagree on how CSSMediaRule behaves

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#845]
CSSOM has (<https://drafts.csswg.org/cssom/#the-cssmediarule-interface>):

    [SameObject, PutForwards=mediaText] readonly attribute MediaList media;

and CSS Conditional Rules has (<https://drafts.csswg.org/css-conditional/#the-cssmediarule-interface>):

    readonly attribute MediaList media;

which differ in terms of what happens when .media is assigned on a CSSMediaRule.

**Comment by csnardi** [comment]
This seems to be fixed; CSSOM now says "The CSSMediaRule interface is defined in CSS Conditional Rules" and CSS Conditional has been updated to the first code block above.

**Comment by bzbarsky** [comment]
Yep, looks good now.

**Comment by svgeesus** [comment]
(No change to css-conditional, closed by edits in cssom)
