### ISSUE TITLE
[css-fonts-4] `font-feature-settings` and `font-variation-settings` should specify ordering in the computed style

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#8450]
The current specs for [font-feature-settings](https://w3c.github.io/csswg-drafts/css-fonts/#font-feature-settings-prop) and [font-variation-settings](https://w3c.github.io/csswg-drafts/css-fonts/#font-variation-settings-def) specify how tags are deduplicated but does not answer how to sort tags relatively to one another.

In the case of `font-variation-settings`, Chrome and Firefox both sort alphabetically, and Safari will too per https://github.com/WebKit/WebKit/pull/10085.

In the case of `font-feature-settings`, Firefox sorts alphabetically, while Chrome does not. Safari will sort alphabetically as well per https://github.com/WebKit/WebKit/pull/10085.

While the fact that values are de-duplicated is sufficient to ensure correct round-tripping of computed values as specified values, it would be a Good Thing to specify reliable output for computed style. I suggest we use ascending alphabetical sorting to match the existing behavior of Firefox and the new behavior of Safari.

**Comment by graouts** [comment]
Interestingly, the WPT test [css/css-fonts/parsing/font-feature-settings-computed.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/parsing/font-feature-settings-computed.html) has some loose ordering expectation. We should fix this.

**Comment by graouts** [comment]
The [WebKit patch](https://github.com/WebKit/WebKit/pull/10085) includes a change to [css/css-fonts/parsing/font-variation-settings-computed.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/parsing/font-variation-settings-computed.html) which is also being exported to WPT as https://github.com/web-platform-tests/wpt/pull/38492.

**Comment by graouts** [comment]
> Interestingly, the WPT test [css/css-fonts/parsing/font-feature-settings-computed.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/parsing/font-feature-settings-computed.html) has some loose ordering expectation. We should fix this.

Should I make a WPT change to make this test more strict in preparation for an upcoming spec update that involves alphabetical sorting?

**Comment by svgeesus** [comment]
Theoretically you should wait for the spec update but I plan to do that now so go ahead :)

**Comment by graouts** [comment]
> Theoretically you should wait for the spec update but I plan to do that now so go ahead :)

I'll do this tomorrow, generally giving you a few hours to get it done :)

**Comment by graouts** [comment]
The `font-variation-settings` WPT change was made in https://github.com/web-platform-tests/wpt/commit/a13b3f00015ecad599141e82e9f1a5acb575f96a and the `font-feature-settings` change will land with https://github.com/web-platform-tests/wpt/pull/38513.
