### ISSUE TITLE
[css-color-5] Unclear if same-space RCS actually triggers a conversion

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#8452]
In [Section 3](https://w3c.github.io/csswg-drafts/css-color-5/#relative-colors), we have the text:

> If the origin color was originally specified with a different color function, it’s first converted into the chosen color function, so it has meaningful values for the channels.

This seems pretty clear - if you write `oklch(from oklch(0% 50% 150deg) l c h)` no conversion should take place, so the "components that are powerless after color space conversion become missing instead" from Color 4 doesn't apply, and the result is indeed identical to the input color.

But the later individual color-function sections have the text:

>r, g, and b are all `<number>`s that correspond to the origin color’s red, green, and blue channels after its conversion to sRGB.

(or the equivalent for any given set of channels)

This directly says "after its conversion", implying an unconditional conversion happens. I suspect we want to make this more circumspect, like "red, green, and blue channels (after its conversion to sRGB, if necessary)".

(This issue confused a teammate, so it's a real-world issue in the spec's readability.)

**Comment by svgeesus** [comment]
Good catch.

**Comment by svgeesus** [comment]
I gave id="required-conversion" to

> If the origin color was originally specified with a different color function, it’s first converted into the chosen color function, so it has meaningful values for the channels.

Then linked to that from 

> after **conversion, if required**

in all the channel keyword definitions

**Comment by tabatkins** [comment]
Yup, looks great.
