### ISSUE TITLE
[css-backgrounds] [css-masking] [cssom] serialization of the computed value for `background` and `mask`

### ISSUE THREAD

**Issue by graouts** [w3c/csswg-drafts#8453]
Safari is failing some animation WPT tests for the `mask` property because of how it serializes the computed value for that shorthand property. When setting `mask: url("http://example.com/")`, here is what browsers currently return when `getComputedStyle(element).mask` is called:

- Safari: `url("http://example.com/") 0% 0% / auto repeat border-box border-box add match-source`
- Chrome: `url("http://example.com/")`
- Firefox: `url("http://example.com/")`

So it appears both Chrome and Firefox have some logic to disregard initial values in the computed style serialization for `mask`. 

Looking at specs, I couldn't find where this would be specified though. For [`mask`](https://drafts.fxtf.org/css-masking/#the-mask) the _computed value_ entry just says "see individual properties". Looking at the CSSOM spec, I don't see anything specific in the specs for either [`getPropertyValue()`](https://www.w3.org/TR/cssom-1/#dom-cssstyledeclaration-getpropertyvalue) or the [serialize a CSS value](https://www.w3.org/TR/cssom-1/#serialize-a-css-value) procedure about the [computed flag](https://www.w3.org/TR/cssom-1/#cssstyledeclaration-computed-flag) with respect to shorthand properties.

It's also worth looking at the `background` property which is a pretty similar property to `mask` in terms of the various longhand properties it encompasses and how it serializes. Taking the simple `background: url("http://example.com/")`, here is what browsers currently return when `getComputedStyle(element).background` is called:

- Safari: `rgba(0, 0, 0, 0) url("http://example.com/") repeat scroll 0% 0% / auto padding-box border-box`
- Chrome: `rgba(0, 0, 0, 0) url("http://example.com/") repeat scroll 0% 0% / auto padding-box border-box`
- Firefox: `url("http://example.com/")`

So Firefox serializes the computed value for `background` and `mask` with a similar approach. Safari as well, although it makes no attempt to remove initial values for a compact serialization. Chrome uses different approaches.

It seems to me that these cases, and the serialization of shorthands for computed style in general, should be specified.

**Comment by graouts** [comment]
A co-worker pointed me to this bit of the [serialize a CSS value](https://www.w3.org/TR/cssom-1/#serialize-a-css-value) procedure:

> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

So I guess this actually calls out that the Firefox behavior for `background` and `mask` _is_ correct.

**Comment by SebastianZ** [comment]
Yes, that's the point. The serialization algorithm strives for shorter representations of values. So the output in Blink and WebKit is wrong.

And it seems WebKit already has a patch for it: https://bugs.webkit.org/show_bug.cgi?id=252460

Regarding the serialization of `background`, there's also a [WPT for its serialization](http://wpt.live/css/css-backgrounds/parsing/background-shorthand-serialization.html). Though it only tests the serialization of `.style.background` and not the computed value via `getComputedStyle()`. So I guess the WPT test needs to be extended to also cover computed values.

I couldn't find a Blink bug regarding the serialization of `background`, so I created one at https://bugs.chromium.org/p/chromium/issues/detail?id=1417904.

Sebastian

**Comment by SebastianZ** [comment]
Oh, I just realized you are part of the WebKit team, @graouts. So you probably already know about the patch I posted. 😄

As it's an implementation bug, I guess we can close this issue.

Sebastian
