### ISSUE TITLE
[css-color-6] Document has incorrect link to self

### ISSUE THREAD

**Issue by CharlesBelov** [w3c/csswg-drafts#8458]
* please be specific (in the title and issue) about what you want to change:

This version:
    https://drafts.csswg.org/css-color-5/ 

appears incorrect. I would expect it to read:

This version:
    https://drafts.csswg.org/css-color-6/ 

However, this one I'm not sure about and am mentioning it in case it is incorrect as well:

Latest published version:
    https://www.w3.org/TR/css-color-5/ 

* please link to the spec section you're talking about, or at least the spec
[CSS Color Module Level 6](https://drafts.csswg.org/css-color-6) Editor’s Draft, 12 January 2023

**Comment by svgeesus** [comment]
Thanks, this was a copy and paste error.
