### ISSUE TITLE
[css-backgrounds-4] Order of keywords in `border-*-radius` shorthands

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8469]
Currently, the order of the `border-*-radius` shorthand values is defined as top to bottom and left to right for the physical properties and start to end for the logical properties.

Though @Loirooriol [questioned this](https://github.com/w3c/csswg-drafts/pull/7705/files#r985108445) and proposed to rather follow the clockwise order used for the `border-radius` shorthand.

So `border-radius: 1px 2px 3px 4px` would be equivalent to

```css
border-top-radius: 1px 2px;
border-bottom-radius: 3px 4px;
```

instead of

```css
border-top-radius: 1px 2px;
border-bottom-radius: 4px 3px;
```

The question is, do authors rather expect opposite sides to always follow one direction or have a clockwise order?

This question similarily applies to the logical shorthands. Should they always be start to end or should they map differently?

I tend to say one direction, though it also goes against `border-radius`.

Sebastian

**Comment by tabatkins** [comment]
I *really* don't think they should follow the clockwise ordering. The clockwise ordering makes sense *in the context of four values*; if you're only specifying two values it's nonsense, because it gives opposite orders for opposite sides. top and bottom should definitely set the values left->right (or start->end), etc.

**Comment by Loirooriol** [comment]
start->end totally makes sense for logical shorthands. But do we have a precedent for assuming that physical left->right and top->bottom is the natural progression?

**Comment by tabatkins** [comment]
Yes, any property with single-axis values uses that progression unless there's a good reason not to. See 'background-position', for instance - each axis's length is measured from the top/left, with larger values proceeding downward/rightward.

(Note that some seeming exceptions, like the 'right' property, are not based on an axis, but rather on a *side*, and thus are measuring along an outside <-> inside dimension.)

**Comment by Loirooriol** [comment]
Mm, OK, in `background-position` it's not for the purpose of shorthand expansion, but I guess it's close enough.

**Comment by SebastianZ** [comment]
As it seems we agree on this now, let's make this official.

Proposed resolution: Close this issue without changing the spec. I.e. the order for the `border-*-radius` shorthands is always left to right and top to bottom for physical values and start to end for logical values.

Sebastian

**Comment by astearns** [comment]
If there is no spec change, then we do not need a resolution. Particularly since you opened the issue @SebastianZ feel free to close no change and add a 'commenter satisfied' label.

**Comment by SebastianZ** [comment]
Thanks for the hint, @astearns!
