### ISSUE TITLE
[css-page]@page grammar doesn't match surrounding prose

### ISSUE THREAD

**Issue by bzbarsky** [w3c/csswg-drafts#847]
The grammar says:

    @page = @page <page-selector-list>? { <declaration-list> }

but the intent is to allow the "margin at-rules" in there too, not just declarations.

**Comment by SebastianZ** [comment]
FWIW, the [related MDN page does a better job](https://developer.mozilla.org/en-US/docs/Web/CSS/@page#Formal_syntax) in defining the syntax.

Sebastian

**Comment by bzbarsky** [comment]
Usually MDN would get that sort of thing from the spec draft.  Did this use to say the right thing and then get changed?

**Comment by SebastianZ** [comment]
This was done according the notes in issue #632. Prior to that it copied the syntax from the spec.

Wish you a Happy New Year, Boris! 🎉 

Sebastian

**Comment by tabatkins** [comment]
The `<declaration-list>` production allows at-rules (as does `<rule-list>`; the difference is just whether it *also* allows declarations or qualified rules). So the spec is correct as-is.
