### ISSUE TITLE
Duplicated names in color list

### ISSUE THREAD

**Issue by tcicit** [w3c/csswg-drafts#8470]
It has duplicate entries in the list of color names.
It has duplicate entries in the list of color names.

darkslategrey | #2f4f4f | 47 79 79
dimgray | #696969 | 105 105 105
slategray | #708090 | 112 128 144
lightslategray | #778899 | 119 136 153
gray | #808080 | 128 128 128
darkgray | #a9a9a9 | 169 169 169
lightgrey | #d3d3d3 | 211 211 211

**Comment by svgeesus** [comment]
"it"?

**Comment by svgeesus** [comment]
Okay, I am going to assume that you are commenting on CSS Color 4 [6.1. Named Colors](https://www.w3.org/TR/css-color-4/#named-colors), that you believe it has duplicates, and that the list you give above is what you consider to be an un-duplicated list?

If so - there are no duplicates, but for historical reasons the list includes both American English and International English spelling (gray, grey) for some names.
