### ISSUE TITLE
[css-inline-3] `text-edge` and `line-height` have the same conceptual job

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#8477]
[This is one of a series of issues we're filing about the design feedback of `leading-trim` and `text-edge`. As far as we know, these properties are unimplemented in any browser, which means now is a good time to give feedback on their overall design. For each of the issues we're filing, we don't have a fully-formed proposal that would solve the problem, but we do have some avenues of potential mitigation in mind, and we're offering these ideas as a starting point for further discussion.]

`text-edge` and `line-height` both increase/decrease the amount of layout space an inline box takes. Except, because of the interaction described in https://github.com/w3c/csswg-drafts/issues/8476, sometimes one of them is applied, and other times, the other one is applied. But they’re doing the same thing, and have similar effects on the layout size of inline boxes.

A potential solution is to merge the two properties, as described in https://github.com/w3c/csswg-drafts/issues/8478.

**Comment by fantasai** [comment]
See comments in #8476 and #8478. I think the premise of this issue is invalid, and the solution proposed is not workable.

**Comment by litherum** [comment]
Closing.
