### ISSUE TITLE
[css-animations-2] Add Changes section

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8481]
Probably a little [too late for the FPWD](https://github.com/w3c/transitions/issues/488) but I think there should be a Changes section added like in other specs. This makes it easier to grasp what has changed since level 1 of the spec.

Sebastian

**Comment by svgeesus** [comment]
Yes, a "Changes since Level 1" would be helpful.  That could be done now, because FPWD  of CSS Animations 2 is waiting for [an update to CSS Animations 1](https://github.com/w3c/csswg-drafts/issues/8464)

Once the FPWD has been published, changes since last publication should also be added.

**Comment by SebastianZ** [comment]
Thanks for adding the section! I've just [fixed a typo and linked the properties and interface](https://github.com/w3c/csswg-drafts/commit/ed63409e5dfb17803e9d7a1afb95ba20bac108d4) in there, so it's a little easier to skim through it and get to the described changes.

Sebastian
