### ISSUE TITLE
Nit: the text describing the group pseudo-element name is confusing [css-view-transitions-1]

### ISSUE THREAD

**Issue by pes10k** [w3c/csswg-drafts#8486]
This is from the recently requested [PING privacy review](https://github.com/w3cping/privacy-request/issues/107). Its not identifying a privacy issue, not intended to be blocking, and only being offered as a friendly suggestion for where the text in the spec might be clarified.

Currently [Section 2](https://www.w3.org/TR/css-view-transitions-1/#transitions-as-enhancements) of the spec describes each collection of the four pseudo elements as a group, with the first element consisting of the group:

```
Each of the groups is comprised of up to four pseudo elements:

   1. Group…
```

It took me a few reads to make sure this wasn't a typo, and to make sure I understood what was going on in the text. Having the first element of the group be a thing called "group" seems likely to cause unnecessary confusion.  

I imagine changing the names of the psudo-elements would be painful at this point, so as a straw suggestion, what if "Each ~of the groups~ **view transition target** is comprised of up to four pseudo elements…"

**Comment by khushalsagar** [comment]
Thanks for the suggestion @pes10k. The text you mentioned has been reworked and doesn't use that language anymore. You can see the latest version [here](https://drafts.csswg.org/css-view-transitions-1/#transitions-as-enhancements). We still need to republish the latest spec.

@jakearchibald FYI.
