### ISSUE TITLE
[css-rhythm-1] block-step-size/block-step-align splitting odd adjustment amount

### ISSUE THREAD

**Issue by sgill26** [w3c/csswg-drafts#8488]
The spec defines `block-step-align: center` as follows:

> Any extra space resulting from a [block-step-size](https://drafts.csswg.org/css-rhythm/#propdef-block-step-size)-induced adjustment is split, and applied half on either side of the box. 

If the amount of extra space being added is odd, is there a priority of how to split the difference?

```
<div style="width: 50px; height: 50px; background-color:green; block-step-size: 99px;">
</div>
```

I'm assuming here that one side will get 24px added while the other side will get 25px added, is that correct?

**Comment by tabatkins** [comment]
Lengths aren't necessarily integer px amounts - they'd each get 24.5px. The spec intentionally doesn't specify how lengths get rounded to whatever layout precision an impl chooses to use.
