### ISSUE TITLE
[css-animations-2][scroll-animations-1]  Avoid including properties that should be interpolated at boundaries when adding neutral keyframes

### ISSUE THREAD

**Issue by kevers-google** [w3c/csswg-drafts#8491]
Steps 7 and 8 in https://drafts.csswg.org/css-animations-2/#keyframes outline the procedure for adding initial and final keyframes for properties that are missing at the boundaries.  This procedure should be updated such that properties that are missing at 0 or 1, but which should be interpolated at the boundary are not included.

The set of "from" properties should include all properties found in a keyframe with offset <= 0.
Conversely, the set of "to" properties should include all properties found in a keyframe with offset >= 0. 

Keyframes with a timeline offsets can result in computed offsets being outside the 0 to 1 range and should be interpolated at the boundary (see https://github.com/w3c/csswg-drafts/issues/7825).

**Comment by flackr** [comment]
I think this is already covered by the patch to the spec in [scroll-animations-1 Appendix Named Timeline Range Keyframe Selectors](https://drafts.csswg.org/scroll-animations-1/#named-range-keyframes) where it says:

> in these cases the automatic from (0%) and [to](https://drafts.csswg.org/css-shapes-2/#valdef-shape-to) (100%) keyframes are only generated for properties that don’t have keyframes at or earlier than 0% or at or after 100% (respectively).

**Comment by kevers-google** [comment]
Ah perfect.  Didn't check there.
