### ISSUE TITLE
[css-om][css-backgrounds] Serialization of `background: none`

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#8496]
Should `background: none` serialize to `background: transparent` or `background: none` ?

Latest STP serializes as `transparent`, whereas FF serializes as `none`.

@emilio @Loirooriol Wdyt?

**Comment by Loirooriol** [comment]
I guess this fits into the umbrella of #8155.
STP serializes as `transparent` because in https://github.com/WebKit/WebKit/pull/9849 @darinadler interpreted that [`<'background-color'>`](https://drafts.csswg.org/css-backgrounds-3/#propdef-background-color) appears 1st in grammar order. It's not completely clear, but it seems to me that the 1st one is actually [`<bg-image>`](https://drafts.csswg.org/css-backgrounds-3/#typedef-bg-image).

**Comment by darinadler** [comment]
The reason you and I came to different conclusions, I suppose is that `background-color` is the first item in the final layer, and `bg-image` is the first item in the other layers. If there is only a single layer, how does the grammar work, and make it valid without a comma, but `bg-image` counts as first? That’s where we didn’t understand it the same way.

**Comment by Loirooriol** [comment]
Mm, looking at it again, I'm less sure about it :)
If `none` is expected I would change the grammar to

```
<bg-layer>       = <bg-image> || <bg-position> [ / <bg-size> ]? || <repeat-style> || <attachment> || <box> || <box>
<final-bg-layer> = <bg-image> || <bg-position> [ / <bg-size> ]? || <repeat-style> || <attachment> || <box> || <box> || <'background-color'>
```

If `transparent` is expected, I would add a note or something.

**Comment by gsnedders** [comment]
see also #418 more generally about `background` serialisation

**Comment by tabatkins** [comment]
Not captured in the minutes - we're hoping this is web-compatible, since currently if you specify a color and an image, the color will serialize first.

**Comment by darinadler** [comment]
> Not captured in the minutes - we're hoping this is web-compatible, since currently if you specify a color and an image, the color will serialize first.

Not sure that’s quite right: The specification says that, but do any web browsers currently do that?

**Comment by Loirooriol** [comment]
About @fantasai's comment:

```js
var {style} = document.body;
style.background = 'url("") blue';
style.background;
```

Gecko: `blue url("")`
Blink: `url("") blue`
WebKit: `url("") blue`

**Comment by tabatkins** [comment]
k, edit in. Color is now last in the final layer, so a `none` serializes consistently in all layers as `none`.

**Comment by SebastianZ** [comment]
Just to provide a little background why the color was put first in the final layer:

- https://bugzil.la/743392
- https://lists.w3.org/Archives/Public/www-style/2012May/1202.html
- https://lists.w3.org/Archives/Public/www-style/2015Jan/0406.html

So this was initially pushed by me back then. Though I agree it makes sense to have the color at the end for the same reason @fantasai and @LeaVerou gave now and in the past.

Sebastian

**Comment by fantasai** [comment]
@tabatkins Don't just edit and close issues on specs that aren't yours. This needs to go into the Changes list, for example, which you didn't remember to do.
