### ISSUE TITLE
[css-color-5] relative color syntax doesn't specify how to compute channel keywords in other channels

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8499]
_I might be overlooking something and I am not sure how to explain the issue fully.
So apologies in advance if this is a bit vague or if it was already answered._

----

I think there are a few things that are a bit hand-wavy in the current specification.

```css
#a {
  color: rgb(from rgb(0 0 0 / 50%) alpha 128 128 / 0.1);
}
```

Safari TP and WPT seem to agree that this is : `rgba(128, 128, 128, 0.1)`
Somehow the alpha value of `50%` or `0.5` got converted to `128`.

This makes sense if you consider that `50%` of `255` is `128`.
But I don't think the specification mentions the need for this conversion anywhere.

https://drafts.csswg.org/css-color-5/#relative-RGB

> alpha is a [`<number>`](https://drafts.csswg.org/css-values-4/#number-value) that corresponds to the [origin color’s](https://drafts.csswg.org/css-color-5/#origin-color) alpha transparency

So `alpha` should be `0.5`, not `128`, when interpreting the specification naively.

-----

```css
#b {
  color: hsl(from rgb(128 128 128 / 50%) alpha 50% 50% / 0.1);
}

#c {
  color: hsl(0.5 50% 50% / 0.1);
}
```

`#b` seems to be `rgb(0, 0, 0)` (fallback to initial) but the reason isn't clear.  
`hsl` should be able to process hue values of type `<number>`.

`#c` has the same number value as I would expect `alpha` to have and it works perfectly fine : `rgba(191, 65, 64, 0.1)`.

-----

What seems to be missing is a conversion table for when channel keywords are used in other channels.

- using `alpha` in a `r`, `g`, `b`, `h`, ...
- using `r`, `g`, ... in `alpha`
- ...

**Comment by tabatkins** [comment]
There really shouldn't be any channel-specific conversion. Alpha, as a number, takes the range 0-1 wherever it appears; r/g/b take the range 0-255; h takes the range 0-360. These all look like impl bugs.

**Comment by romainmenke** [comment]
The WPT tests : https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html

**Comment by tabatkins** [comment]
Ugh, I think those WPTs dated from when we specified the channels were reflected as `<percentage>`, so it *was* trivially possible to put alpha in r and have it work "as expected". They need fixing to go with the current spec (in specific, a few of the lines like <https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html#L90>).

**Comment by romainmenke** [comment]
ugh, Safari just shipped the old version of the spec in 16.4

**Comment by svgeesus** [comment]
Also, while using channel keywords in odd places is legal and should be tested, there is no actual use case for "set the red to the alpha value" so I agree with @tabatkins that they get used as-is without any magic scaling.

I guess an example "this, not that" would be helpful.

**Comment by romainmenke** [comment]
A premultiplied alpha is not uncommon.
https://codepen.io/romainmenke/pen/QWVPWEJ

```css
#a {
  color: rgb(from rgb(170 30 45 / 50%) calc(r * alpha) calc(g * alpha) calc(b * alpha) / 1);
}
```

---------

>they get used as-is without any magic scaling.
>
>I guess an example "this, not that" would be helpful.

Yeah, that would be ideal.

**Comment by svgeesus** [comment]
[Example added](https://drafts.csswg.org/css-color-5/#ex-no-percentage-magic) (give it a while for the server to update)

**Comment by romainmenke** [comment]
@svgeesus One note on the example.

It seems to be lacking the syntax highlighting present in the other examples.
Making it slightly harder to read.

<img width="833" alt="Screenshot 2023-05-13 at 18 38 20" src="https://github.com/w3c/csswg-drafts/assets/11521496/3ad2ba6c-9b3e-4c63-b30c-4111da475f42">

**Comment by svgeesus** [comment]
So this can be closed. The relevant WPT tests that assumed magic scaling have been corrected, and I assume the WebKit implementation that calculated magic scaling will be fixed at some point so their WPT scores (including Interop 2022 scores) go back up.

**Comment by romainmenke** [comment]
Thank you for following up on this @svgeesus 🙇
