### ISSUE TITLE
[css-shapes] Add a note that a circle with a radius of 0 defines an empty area

### ISSUE THREAD

**Issue by aethanyc** [w3c/csswg-drafts#850]
The following question was raised by @dbaron in Firefox [Bug 1311244 comment 15](https://bugzilla.mozilla.org/show_bug.cgi?id=1311244#c15) during the review of implementing `shape-outside: circle()`.

> if a shape is a circle with a radius of 0, should text flow around that point, or should it flow around nothing?

Both blink and webkit flow the text around nothing. And Firefox is going to do the same. This should make sense because a point without radius doesn't enclose any area.

So it might be worth to add a note for `circle()` and `ellipse()` in [Supported Shapes](https://drafts.csswg.org/css-shapes/#supported-basic-shapes) to explicit says that if the radius of a `circle()` is 0, it defines an empty float area. The same for `ellipse()` if one of its radii is 0.

**Comment by astearns** [comment]
Added clarifying notes with 846a3af
