### ISSUE TITLE
[css-view-transitions-1] Enforce ::view-transition to be fixed position

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8505]
The `::view-transition` pseudo-element is positioned relative to the snapshot root outlined in the spec [here](https://drafts.csswg.org/css-view-transitions-1/#pseudo:~:text=Its%20containing%20block%20is%20the%20snapshot%20root.) irrespective of the value of its `position` property. This was resolved in #7859.

It is also meant to be the containing block for its child pseudo-elements, the `::view-transition-group`, clarified in the spec [here](https://drafts.csswg.org/css-view-transitions-1/#pseudo:~:text=This%20element%20provides%20a%20containing%20block%20for%20all%20%3A%3Aview%2Dtransition%2Dgroup()%20pseudo%2Delements.). This is done by UA CSS setting its `position` property to `fixed`.

It's unclear what should happen if developer CSS modifies the `position` value for this element. We don't have any developer use-case where that's needed. Also the transform value computed by the UA and set on `::view-transition-group` pseudo-elements is in the snapshot root's coordinate space. This relies on these elements being positioned relative to `::view-transition` which itself uses snapshot root as its containing block.

The proposal is to state that the `position` value for `::view-transition` always computes to `fixed`. I'd also be open to using `absolute` since its containing block is not the ICB and the desired behaviour is to make it a containing block for descendants. This is similar to what's done for top layer elements, spec'd [here](https://fullscreen.spec.whatwg.org/#new-stacking-layer:~:text=If%20its%20specified%20position%20property%20is%20not%20absolute%20or%20fixed%2C%20it%20computes%20to%20absolute.).

**Comment by tabatkins** [comment]
I'm fine with either of these - the positioning itself is basically a magic abspos. I guess I lean slightly toward `absolute` just because semantically it's tied to the document (ICB) rather than the viewport. But if there's other reasons to prefer one over the other I'm fine with that.

**Comment by khushalsagar** [comment]
Summarizing an offline discussion on this.

The `position` property on any element can have 2 side-effects:

* It determines whether the element is out of flow and what it's containing block is. Even though `::view-transition`'s ancestor in the DOM hierarchy is its originating element, a.k.a the `documentElement`, we want it to be positioned relative to the the [snapshot root](https://drafts.csswg.org/css-view-transitions-1/#snapshot-root-concept). So the [spec](https://drafts.csswg.org/css-view-transitions-1/#view-transition:~:text=Its%20containing%20block%20is%20the%20snapshot%20root.) states that its containing block is always the snapshot root.
There is no use-case where an author would want to change that. In fact it would be odd to change it since the transform computed for `::view-transition-group` elements is relative to the [snapshot root](https://drafts.csswg.org/css-view-transitions-1/#view-transition:~:text=A%20transform%20that%20would%20map%20element%E2%80%99s%20border%20box%20from%20the%20snapshot%20root%20origin%20to%20its%20current%20visual%20position.).

* It determines whether the element itself is a containing block for its descendants. The `position: fixed` rule in UA CSS on `::view-transition` makes it a containing block for all its `::view-transition-group` child pseudo-elements. 
   
   It's unclear what happens if the author changes `::view-transition` to `position: static`. My read of the explanation [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block:~:text=If%20the%20position%20property%20is%20absolute%2C%20the%20containing%20block%20is%20formed%20by%20the%20edge%20of%20the%20padding%20box%20of%20the%20nearest%20ancestor%20element%20that%20has%20a%20position%20value%20other%20than%20static%20(fixed%2C%20absolute%2C%20relative%2C%20or%20sticky).) is that we'd walk up the ancestor chain until we find a positioned ancestor which will be the root element, so we'd end up with ICB instead of snapshot root. Which is again odd because the coordinate space based on which UA computes transforms for these is the snapshot root.

So there's 2 proposals here:

* `position: fixed` on view-transition pseudos means their containing block is established by the snapshot root. So for example if the author sets `position: fixed` on `::view-transition-old` then it will be positioned relative to the snapshot root instead.

* Enforce that `position: fixed` in UA CSS for `::view-transition` is `!important` so authors can't override it. There is no use-case for them to do it now anyway. The only containing block above `::view-transition` is the snapshot root. And if they want some child to be positioned relative to that, they can use `position: fixed` for it.
   This avoids the need for another special rule for how we select the containing block if authors set `position` to `static` for `::view-transition`.
