### ISSUE TITLE
[css-ui] Consider removing slider-horizontal from <compat-auto>

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#8506]
Firefox doesn't support it and we've never seen a compat issue due to this. I noticed this while looking at Firefox-specific test failures for appearance.

cc @frivoal, do you have the context of why was it needed?

**Comment by emilio** [comment]
Same for `square-button` and `push-button`

**Comment by SebastianZ** [comment]
While implemented across browsers, I also wonder whether `searchfield` is actually needed.

I'm not sure how to interpret the [drastic drop in usage](https://chromestatus.com/metrics/feature/timeline/popularity/2577). Though currently only 0.000309% of pages seem to use it.

Sebastian

**Comment by SebastianZ** [comment]
For what it's worth, the values mentioned by @emilio have also very low usage numbers.

[`square-button`](https://chromestatus.com/metrics/feature/timeline/popularity/2587)
[`push-button`](https://chromestatus.com/metrics/feature/timeline/popularity/2585)
[`slider-horizontal`](https://chromestatus.com/metrics/feature/timeline/popularity/2569)

Sebastian

**Comment by emilio** [comment]
cc @chrishtr, @smfr, does it seem sensible to drop them?

**Comment by chrishtr** [comment]
Removing them from Chromium sounds good to me, given those use counters. @mfreed7 and team are going to look into it.

**Comment by chrishtr** [comment]
@dizhang168

**Comment by nt1m** [comment]
> cc @chrishtr, @smfr, does it seem sensible to drop them?

@pxlcoder, what do you think?

**Comment by zcorpan** [comment]
Looks like `slider-vertical` was already dropped: https://drafts.csswg.org/css-ui-4/#issue-27993a83

**Comment by foolip** [comment]
@frivoal is this something you'll do the spec edits for? I'm asking for https://github.com/web-platform-tests/interop/issues/295, but perhaps we can update the tests separately from the spec change?

**Comment by frivoal** [comment]
Sorry for being slow catching up here. The PR from @zcorpan looks great, so I went ahead and merged it.

**Comment by zcorpan** [comment]
Thanks @frivoal! Tests for this are at https://github.com/web-platform-tests/wpt/pull/40233
