### ISSUE TITLE
[css-text-4] Clarify canonical order of `text-spacing` sub-properties

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8513]
I would say it is `text-autospace` then `text-spacing-trim`.

  > **Name:** `text-spacing`
  > **Value:** `normal | none | auto | <autospace> || <spacing-trim>`
  > **Canonical order:** per grammar

Neither take `normal` or `none`. It is not clear if both take `auto` (cf. #8512). According to [CSSOM](https://drafts.csswg.org/cssom/#serialize-a-css-value):

  > If certain component values can appear in any order without changing the meaning of the value (a pattern typically represented by a double bar `||` in the value syntax), reorder the component values to use the canonical order of component values as given in the property definition table

But the following prose confuse me:

  > This property is a shorthand for setting `text-spacing-trim` and `text-autospace` in a single declaration

  > **`normal`**: [...] Equivalent to `space-first ideograph-alpha ideograph-numeric`

**Comment by fantasai** [comment]
Hm, so I guess the suggestion is to align the order of “normal: [...] Equivalent to space-first ideograph-alpha ideograph-numeric” and “Value: normal | none | auto | <autospace> || <spacing-trim>”?

**Comment by cdoublev** [comment]
> align the order of `space-first ideograph-alpha ideograph-numeric`
  
Not a suggestion but a solution, yes. Another solution would be to explicitly define the canonical order. I do not know what would be the right way to do it, ie. in prose or in a more explicit *Canonical order* (cf. https://github.com/w3c/csswg-drafts/issues/7700#issuecomment-1440764072).

  > align the order of **Value:** `normal | none | auto | <autospace> || <spacing-trim>`

I think the order is fine here. I was refering to `normal | none | auto` to explain my process to resolve the canonical order of sub-properties: these values do not help because they are not specific to either sub-property.

**Comment by frivoal** [comment]
Closed by https://github.com/w3c/csswg-drafts/commit/745c69771015a910534efd0d7a664898c2a729a9
