### ISSUE TITLE
[css-color-4] `hsl()` modern syntax allows `<number>` but seems to be lacking details and WPT tests

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8515]
https://drafts.csswg.org/css-color-4/#the-hsl-notation

```
<modern-hsl-syntax> = hsl( 
    [<hue> | none] 
    [<percentage> | <number> | none] 
    [<percentage> | <number> | none] 
    [ / [<alpha-value> | none] ]? )
```

The prose and the examples don't give any indication or even mention `<number>`.
I also couldn't find any WPT tests, but there are many and I might be overlooking cases where `%` was omitted.

I am assuming this was a recent addition because no browser implements support for numbers in `s` and/or `l`

```css
* {
  background-color: hsl(50deg 0.5 0.5);
  background-color: hsl(50deg 50 50);
}
```

All other color functions that support numbers and percentages have the percentage range in prose or in a section :

```
Percent reference range 	for L: 0% = 0.0, 100% = 1.0
                                for C: 0% = 0.0 100% = 0.4
```

**Comment by cdoublev** [comment]
Also reported in #8322. What makes you think the range would be [0,1] rather than [0,100]?

**Comment by romainmenke** [comment]
> What makes you think the range would be [0,1] rather than [0,100]?

Nothing :)

I added the examples because those are handy to copy/paste for a test in browsers.
I added an example for both [0, 1] and [0, 100].

The percentage reference range is from OKLCH? and purely intended to clarify how other color functions note this information in the specification.

**Comment by svgeesus** [comment]
> I am assuming this was a recent addition because no browser implements support for numbers in s and/or l

Yes this was a [CSS WG resolution 3 weeks ago](https://github.com/w3c/csswg-drafts/issues/7900#issuecomment-1423013714)

> All other color functions that support numbers and percentages have the percentage range in prose

You are right, I need to add it because I had _assumed_ [0..100] but as you say [0..1] is also a reasonable assumption.
