### ISSUE TITLE
[css-cascade-6] Mixed Nesting / Scoping

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8518]
What happens with 
```
selector {
    @scope (otherselector) {
        inner { ... }
    }
}
```

I can think of several possibilities:

- Nest the inner selectors only:
    ```
    @scope (otherselector) {
        selector inner { ... }
    }
    ```
    
- Nest the scoping root only:
   ```
   @scope (selector otherselector) {
       inner { ... }
   }
   ```

- Nest everything:
   ```
   @scope (selector otherselector) to (selector floor) {
       selector inner { ... }
   }
   ```
- Don't allow it.

There's also the impact on specificity to consider...

**Comment by tabatkins** [comment]
This is defined in Nesting: <https://w3c.github.io/csswg-drafts/css-nesting/#nesting-at-scope>

> When the [@scope](https://w3c.github.io/csswg-drafts/css-cascade-6/#at-ruledef-scope) rule is a [nested group rule](https://w3c.github.io/csswg-drafts/css-nesting/#nested-group-rules), an [&](https://w3c.github.io/csswg-drafts/css-nesting/#selectordef-) in the [<scope-start>](https://w3c.github.io/csswg-drafts/css-cascade-6/#typedef-scope-start) selector refers to the elements matched by the nearest ancestor style rule.
>
> For the purposes of the style rules in its body and its own [<scope-end>](https://w3c.github.io/csswg-drafts/css-cascade-6/#typedef-scope-end) selector, the [@scope](https://w3c.github.io/csswg-drafts/css-cascade-6/#at-ruledef-scope) rule is treated as an ancestor style rule, matching the elements matched by its [<scope-start>](https://w3c.github.io/csswg-drafts/css-cascade-6/#typedef-scope-start) selector.

It's equivalent to your second option - the scope-start selector is treated as a nested selector wrt the parent style rule, but the scope-end selector and all child style rules are counted as nested by the scope-start selector. (Using @scope's rules for nesting, but interpreting an `&` as described.)

**Comment by mirisuzanne** [comment]
I suppose it's not too surprising that this removes the specificity of the outer selector. The same would be true if using `&` inside `:where()`.

**Comment by tabatkins** [comment]
Right; again, there should generally be minimal difference between expressing something in nested and unnested form; if unnested, the entire selector goes into scope-start and doesn't apply its specificity to the contained rules.
