### ISSUE TITLE
[css-rhythm-1] Ambiguous animation types

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8521]
CSS Rhythm 1 properties have a mix of *Animation type* and *Animatable* in their definition table. For example:

  > **Name:** [block-step-insert](https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-insert)
  > **Animatable:** no
  > **Animation type:** discrete

I guess all of them are actually animatable, as given by *Animation type*.

If needed, I would be happy to remove all *Animatable* fields in a PR. [Web Animations](https://drafts.csswg.org/web-animations-1/#animating-properties) requires *Animation type*, not *Animatable*.

**Comment by tabatkins** [comment]
Yup, please do.
