### ISSUE TITLE
[css-shapes-1] Define equivalent paths

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#8524]
[Shapes 1](https://drafts.csswg.org/css-shapes-1/#supported-basic-shapes) currently defines all the shapes functions as, well, shapes, which is pretty reasonable for what it was designed for. Over time we've expanded on these functions and their use-cases; notably, we added path() and shape() (declaring that they auto-close to form a closed shape if necessary), but also referenced the functions in places that want to use them *as a path*, like in ['offset-path'](https://drafts.fxtf.org/motion-1/#offset-path-property).

When used as a path, rather than as a shape, we need to define what exactly the path is - where it starts, and how it continues. Currently 'offset-path' does that explicitly (for the set of shape functions it knew about; it's missing a few newer ones), but (a) it seems better to define this alongside the shapes, so lists can't get out-of-date, and (b) I expect that any other uses of shape-as-path would want to use the same definitions.

All the starting-point definitions in offset-path make sense to me; should we move those to the function definitions in Shapes?

**Comment by astearns** [comment]
It sounds OK to me, though I think it’s a bit weird to have the path stuff defined in shapes-1 with no way of testing it without referring to other modules. If `offset-path` is the only place where that is used it might make sense to keep it there until we have another consumer.

**Comment by tabatkins** [comment]
My concern is that the spec drifted out of date pretty readily - we were missing the new rect functions, and won't mention shape() (but that's probably handwaveable, since it's just an alternate version of path()).

But I could be okay with moving these to a normative appendix, with a note that anything missing from the Shapes spec is an error and that this might move to that spec later.

**Comment by tabatkins** [comment]
I went ahead and did that.
