### ISSUE TITLE
[css-values] Specify if serialized calculated angles should always use canonical unit

### ISSUE THREAD

**Issue by CanadaHonk** [w3c/csswg-drafts#8530]
Originating from discussion: https://github.com/web-platform-tests/wpt/issues/38821

Should serialized angles inherit the unit given or always use the canonical unit (deg)?

What is the expected output of this?

```js
target.style.transform = 'rotate(calc(1rad * 2))'; target.style.transform
```

`2rad` or `114...deg`?

Current implementations differ a lot, and no WPT tests for this specifically (preserving angle calc units) exist.

- Blink: `rotate(calc(2rad))`
- Gecko: `rotate(calc(114.592deg))`
- WebKit: `rotate(calc(114.591559deg))`

**Comment by cdoublev** [comment]
I think it should serialize in `deg`:

  > If root is a dimension that is not expressed in its canonical unit, and there is enough information available to convert it to the canonical unit, do so, and return the value.

https://w3c.github.io/csswg-drafts/css-values-4/#simplify-a-calculation-tree

**Comment by dbaron** [comment]
Though it's worth noting that that's specific to the use of `calc()` in this example, and isn't true for all "serialized angles" (quoting the issue title).

**Comment by jfkthame** [comment]
Right, for specified values that don't involve `calc()`, I guess we just rely on [the CSSOM spec](https://www.w3.org/TR/cssom-1/#serializing-css-values), which says that:

> [`<angle>`](https://www.w3.org/TR/css-values-4/#angle-value)
    The `<number>` component serialized as per `<number>` followed by the unit in canonical form as defined in its respective specification.

So
```
target.style.transform = 'rotate(1rad)'; target.style.transform
```
should (and does) return `rotate(1rad)`.

But as soon as `calc()` is introduced, the simplification rules mean the resulting serialization should use `deg`.

**Comment by tabatkins** [comment]
Specified values are still very handwavy in general, yeah. I *think* they're expected, on their own, to preserve the author-provided unit.

But yes, calc() is well-specified to do simplification/canonicalization, so for the example in the OP, Firefox/WebKit are correct. (Modulo the precision, which calc() serialization doesn't specify, deferring to CSSOM serialization of numeric values. I think the difference there is the #7416 issue.)

**Comment by CanadaHonk** [comment]
Thanks all for clarifications and info! Will fix WPT tests in Gecko patch (https://phabricator.services.mozilla.com/D171658). Might add some specifically for this (edge)case if that seems reasonable as well as it isn't that clearly defined/standardised (please say).
