### ISSUE TITLE
[css-text] Rename text-space-trim?

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#8536]
We now have [text-space-trim](https://drafts.csswg.org/css-text-4/#white-space-trim) and [text-spacing-trim](https://drafts.csswg.org/css-text-4/#text-spacing-trim-property) in css-text-4. They accomplish different goals, but have similar names. It might be useful to rename one of them, e.g., change `text-space-trim` to `white-space-trim`?

**Comment by vitorroriz** [comment]
I also think that's confusing.

**Comment by frivoal** [comment]
This has been handled in https://github.com/w3c/csswg-drafts/issues/8273, and `text-space-trim` has indeed been changed to `white-space-trim`.
