### ISSUE TITLE
[css-images-3] clarification on metadata position in specific file formats

### ISSUE THREAD

**Issue by Sxderp** [w3c/csswg-drafts#8543]
https://drafts.csswg.org/css-images-3/#url-metadata

Some file formats require the metadata to be at the end (.webp). I feel it's hostile to ignore the metadata in these files since you cannot change the location, it's part of the image spec. Can we get clarification on whether it should be ignore or not?

**Comment by svgeesus** [comment]
On a related note, PNG originally allowed EXIF to be either before or after the image data. Web browsers ignore EXIF for things like rotation, if it is after the image data. And now that the PNG spec is being maintained again, we made it that EXIF has to be before the image data.

https://w3c.github.io/PNG-spec/#eXIf
https://w3c.github.io/PNG-spec/#5ChunkOrdering

**Comment by svgeesus** [comment]
I agree that "Authors must produce their image files so that such metadata occurs before the image data in the image file." is harsh if the image format only allows it afterwards. Presumably CSS is not requiring the creation of invalid images.

Perhaps

> If the choice exists for a given image format, authors must produce their image files so that such metadata occurs before the image data in the image file.

**Comment by Sxderp** [comment]
Just for some background this issue was spawned from an issue on the Firefox tracker. I argue the spec does not prohibit Firefox from implementing orientation for .webp files. The maintainers seem to think otherwise.

https://bugzilla.mozilla.org/show_bug.cgi?id=1761174#c4

**Comment by tnikkel** [comment]
> Just for some background this issue was spawned from an issue on the Firefox tracker. I argue the spec does not prohibit Firefox from implementing orientation for .webp files. The maintainers seem to think otherwise.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1761174#c4

In case it's relevant, I don't feel that this comment accurately summarizes the discussion in that bug.

**Comment by tnikkel** [comment]
The irc log states that "webp doesn't support incremental decoding", which is false. Both firefox and chrome currently incrementally decode webp. This seemed to be a key part of the discussion, so perhaps it should be revisited?
