### ISSUE TITLE
[css-box-4] Use cases for margin-trim on floats

### ISSUE THREAD

**Issue by sammygill** [w3c/csswg-drafts#8547]
https://w3c.github.io/csswg-drafts/css-box-4/#margin-trim-block

Currently the spec defines trimming for both the block and inline margins on floats. What are some of the intended use cases that would encourage the use of this property? Could we get some potential examples that would highlight the different types of trimming on floats?

**Comment by litherum** [comment]
cc @fantasai (the editor of this spec)

We are bringing this up because implementation is difficult and we're not sure it's warranted. Depending on the use cases, we may propose changes to the property's interaction with floats.

**Comment by bfgeek** [comment]
I've done an analysis for Blink for this feature and agree that margin-trim on floats has significant implementation difficulty (additionally this isn't a "shared heritage" thing, this is with our new engine).

cc/ @tabatkins 

I know previously there was talk of opting-in/out float margin trimming. A forwards compat option might be to (initially) keep margins on floats (only apply to "inflow" content), with a future option to allow trimming on floats.

Ian

**Comment by dholbert** [comment]
Based on my recollection from the last time I looked at float/margin interactions in Gecko, I agree this seems like it'd be non-trivial to implement.  Lacking a use-case, I'm in favor of simplifying or nerfing the effects of this property on floated content.

**Comment by fantasai** [comment]
Edits committed, retargetting at Level 5 for reconsideration.

**Comment by fantasai** [comment]
Actually, let's use #3256 for that.
