### ISSUE TITLE
[css-cascade][css-cascade-6] "source order" terminology regression

### ISSUE THREAD

**Issue by cvrebert** [w3c/csswg-drafts#8550]
https://drafts.csswg.org/css-cascade-6/#scope-effects

This spec uses the term "source order" 3 times: once normatively, once in an example, and once in an inline Issue. These usages appear to be in prose for feature(s) newly added in Level 6.
As established in #6839, the term "source order" is undefined. [Order of appearance](https://drafts.csswg.org/css-cascade-6/#cascade-order) should be preferred instead, since it does have a formal definition.

**Comment by mirisuzanne** [comment]
Fixed in 429947fa2aa (I only found one use of the phrase remaining)
