### ISSUE TITLE
[css-text] Add new small kanas for `text-transform: full-size-kana`

### ISSUE THREAD

**Issue by graphemecluster** [w3c/csswg-drafts#8554]
It has been some years since the addition of the full-size-kana value to the text-transform property.
https://w3c.github.io/csswg-drafts/css-text/#text-transform

With the release of Unicode 12.0 and 15.0, several new small kanas were added to the Small Kana Extension block:
https://www.unicode.org/charts/PDF/U1B130.pdf

These kanas are mainly used in historical Japanese or non-“standard”-Japanese languages (e.g. dialects). For example, the character 圈 (けん ken, “sphere”) is previously pronounced as く𛅑ん (kwen), or くゑん in full-size form.

Thus, I suggest appending the following rows to Appendix G: Small Kana Mappings (https://w3c.github.io/csswg-drafts/css-text/#small-kana):

| Small | Full Size |
| --- | --- |
| 𛄲 U+1B132 | こ U+3053 |
| 𛅐 U+1B150 | ゐ U+3090 |
| 𛅑 U+1B151 | ゑ U+3091 |
| 𛅒 U+1B152 | を U+3092 |
| 𛅕 U+1B155 | コ U+30B3 |
| 𛅤 U+1B164 | ヰ U+30F0 |
| 𛅥 U+1B165 | ヱ U+30F1 |
| 𛅦 U+1B166 | ヲ U+30F2 |
| 𛅧 U+1B167 | ン U+30F3 |

**Comment by frivoal** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/9110c78e787ac8e8f85825dd0e37d0736943cdc5 and https://github.com/w3c/csswg-drafts/commit/615c184f9d5e1a40169b3e8d0ea6cdf5d764270d, tested in https://github.com/web-platform-tests/wpt/pull/41638 and https://github.com/web-platform-tests/wpt/pull/41657

**Comment by graphemecluster** [comment]
Oh, just know that it's a duplicate of #8442. Apologies. (I wonder why though, I believe I did search through the issues before opening one)
