### ISSUE TITLE
[css-grid-2] Computed value for integer repeats on grid-template-columns and grid-template-rows for non-subgrids

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [w3c/csswg-drafts#8555]
I'm working on implementing this in Chromium, and I see that Firefox and Safari have implemented this case differently.

To repro, you can paste this in your browser's address bar and look at the computed value in developer tools:
`data:text/html,<div style="grid-template-columns: subgrid repeat(2, [a]);"></div>`

Firefox reports `subgrid [a][a]`, while Safari preserves the repeat syntax and reports `subgrid repeat(2, [a])`

https://www.w3.org/TR/css-grid-2/#computed-tracks

"The [computed track list](https://www.w3.org/TR/css-grid-2/#computed-track-list) of a [subgridded axis](https://www.w3.org/TR/css-grid-2/#subgridded-axis) is the [subgrid](https://www.w3.org/TR/css-grid-2/#valdef-grid-template-rows-subgrid) keyword followed by a [list](https://infra.spec.whatwg.org/#list) of [line name sets](https://www.w3.org/TR/css-grid-2/#line-name-set) representing each line in that axis."

There's also a section below (https://www.w3.org/TR/css-grid-2/#resolved-track-list-standalone) which explains what to do for `grid-template-rows` on a non-grid, and has an example that expands integer auto repeaters. It doesn't say what to do for when `subgrid` is included, however. It also doesn't say whether to expand for `auto-fill` or `auto-fit` in either case.

I think the most consistent behavior here is to expand the integer auto repeaters, as Firefox does, as that's most consistent with standalone grids. Since `auto-fit` can't be expanded (as this requires grid layout to compute), it makes sense to preserve the specified `repeat(auto-fit, ...)`.

But that's my opinion. I'm curious what the working group thinks, and if this should be clarified more in the spec. I'm happy to implement whichever is preferred in Chromium.

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-grid-2/#resolved-track-list-subgrid

> When an element generates a [grid container](https://drafts.csswg.org/css-grid-2/#grid-container) box that is a [subgrid](https://drafts.csswg.org/css-grid-2/#subgrid), the [resolved value](https://drafts.csswg.org/cssom-1/#resolved-value) of the [`grid-template-rows`](https://drafts.csswg.org/css-grid-2/#propdef-grid-template-rows) and [`grid-template-columns`](https://drafts.csswg.org/css-grid-2/#propdef-grid-template-columns) properties represents the [used](https://drafts.csswg.org/css-cascade-5/#used-value) number of columns, serialized as the [`subgrid`](https://drafts.csswg.org/css-grid-2/#valdef-grid-template-rows-subgrid) keyword followed by a list representing each of its lines as a [line name set](https://drafts.csswg.org/css-grid-2/#line-name-set) of all the line’s names explicitly defined on the subgrid (not including those adopted from the [parent grid](https://drafts.csswg.org/css-grid-2/#parent-grid)), **without using the [`repeat()`](https://drafts.csswg.org/css-grid-2/#funcdef-repeat) notation**.

This was discussed in #4362.

> Since `auto-fit` can't be expanded (as this requires grid layout to compute)

Resolved values from `getComputedStyle()` can depend on layout (e.g. `width: auto` serializes to an absolute length). The internal computed value should preserve `repeat()` indeed, but AFAIK this is only observable via inheritance, interpolation, or TypedOM.

**Comment by KurtCattiSchmidt** [comment]
This isn't quite the case here - since there's no grid layout, there are no used values. This is specifically when `grid-template-columns` is specified on an item *without* `display: grid`. On an item with `dispay: grid`, it makes sense to expand and report used values, which is what we're doing.

However, auto repeats cannot be expanded in this case. I was too broad in saying that it requires *layout*, it actually only requires a grid parent, as auto repeats in sugrid depend entirely in the remaining number of tracks that the subgrid spans in the grid parent (and not layout). If there's no grid parent or subgrid span, this cannot be computed. See https://www.w3.org/TR/css-grid-2/#auto-repeat - "On a [subgridded axis](https://www.w3.org/TR/css-grid-2/#subgridded-axis), the [auto-fill](https://www.w3.org/TR/css-grid-2/#valdef-repeat-auto-fill) keyword is only valid once per [<line-name-list>](https://www.w3.org/TR/css-grid-2/#typedef-line-name-list), and repeats enough times for the name list to match the [subgrid](https://www.w3.org/TR/css-grid-2/#subgrid)’s specified [grid span](https://www.w3.org/TR/css-grid-2/#grid-span) (falling back to 0 if the span is already fulfilled)."

The test mentioned is actually specifically testing that auto repeats *don't* get expanded when there's no grid layout: [grid-template-computed-nogrid.html](https://wpt.fyi/results/css/css-grid/subgrid/grid-template-computed-nogrid.html?label=master&label=experimental&aligned&view=subtest&q=grid-template-computed-nogrid.html%20)

But I saw a discrepancy in how browsers are handling integer repeats there - Safari doesn't expand integer repeats, while Firefox does. I slightly prefer Firefox's interpretation, as expanding integer repeats is closer to what items with valid grid layout end up doing, but it's inconsistent with auto repeats. 

Also, my change in Chromium is updating the aforementioned test (see https://chromium-review.googlesource.com/c/chromium/src/+/4317507) to validate that integer auto repeats *do* get expanded on non-grid's. This matches Firefox but fails in Safari. I'm happy to update Chromium's implementation and the test if this is incorrect.

**Comment by Loirooriol** [comment]
OK, I missed that this was a full example. Then, https://drafts.csswg.org/css-grid-2/#subgrid-listing

> If there is no [parent grid](https://drafts.csswg.org/css-grid-2/#parent-grid) [...] the [used value](https://drafts.csswg.org/css-cascade-5/#used-value) is the initial value, [none](https://drafts.csswg.org/css-grid-2/#valdef-grid-template-rows-none), and the grid container is not a [subgrid](https://drafts.csswg.org/css-grid-2/#subgrid).

Thus we have a standalone axis, not a subgridded axis (it's still a `subgrid`axis though), and https://drafts.csswg.org/css-grid-2/#resolved-track-list-standalone applies.

> Otherwise, (e.g. when the element has [display: none](https://drafts.csswg.org/css-display-4/#propdef-display) or is not a [grid container](https://drafts.csswg.org/css-grid-2/#grid-container)) the resolved value is simply the [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value).

And per https://drafts.csswg.org/css-grid-2/#computed-tracks

> The [computed track list](https://drafts.csswg.org/css-grid-2/#computed-track-list) of a [`subgrid`](https://drafts.csswg.org/css-grid-2/#valdef-grid-template-rows-subgrid) axis is the `subgrid` keyword followed by a [list](https://infra.spec.whatwg.org/#list) of [line name sets](https://drafts.csswg.org/css-grid-2/#line-name-set) and [computed repeat notations](https://drafts.csswg.org/css-grid-2/#computed-repeat-notation) representing the line names specified for that axis.

**Comment by Loirooriol** [comment]
> Also, my change in Chromium is updating the aforementioned test (see https://chromium-review.googlesource.com/c/chromium/src/+/4317507) to validate that integer auto repeats do get expanded on non-grid's.

Then your change seems against the spec. And it's not just inconsistent with `grid-template-rows: subgrid repeat(auto-fill, [a])`, but also with `grid-template-rows: repeat(1, 1px)` which is not expanded for non-grids.

**Comment by KurtCattiSchmidt** [comment]
Thanks, that helps make sense of this a little more. However, I wouldn't consider it a standalone axis either, since it's not a grid. Per https://drafts.csswg.org/css-grid-2/#resolved-track-list-standalone - "When an element generates a [grid container](https://drafts.csswg.org/css-grid-2/#grid-container) box"... which is not the case here. There's no grid container in the test I'm referring to (https://wpt.fyi/results/css/css-grid/subgrid/grid-template-computed-nogrid.html).

Per https://drafts.csswg.org/css-grid-2/#computed-repeat-notation, what does "\<integer\> computed" mean in this sentence:

..."a [repeat()](https://drafts.csswg.org/css-grid-2/#funcdef-repeat) functional notation representing a repeated track list section, with its [\<integer\>](https://drafts.csswg.org/css-values-4/#integer-value) computed and its [\<track-list\>](https://drafts.csswg.org/css-grid-2/#typedef-track-list) represented as a [computed track list](https://drafts.csswg.org/css-grid-2/#computed-track-list) (a computed repeat notation)"

Does "computed" mean "expanded"?

**Comment by Loirooriol** [comment]
Maybe "standalone axis" is not the best terminology if it's not a grid, but the spec covers this case in https://drafts.csswg.org/css-grid-2/#resolved-track-list-standalone

> Otherwise, (e.g. when the element has [display: none](https://drafts.csswg.org/css-display-4/#propdef-display) or **is not a [grid container](https://drafts.csswg.org/css-grid-2/#grid-container)**) the resolved value is simply the [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value).

I think "`<integer>` computed" may mean that e.g. `calc(1em / 1px)` should become `16`.

It doesn't mean that you should expand the repeat. The internal computed value should never do that, only the resolved value from `getComputedStyle` in some cases. This affects interpolation, e.g. `repeat(2, 100px)` and `repeat(1, 200px 200px)` interpolate discretely, even though `repeat(2, 100px)` and `repeat(2, 200px)` would be smooth. See https://drafts.csswg.org/css-grid-2/#repeat-interpolation

**Comment by KurtCattiSchmidt** [comment]
Gotcha, I appreciate the definitive answer here. I'll update the test case (and implementation) to not expand integer repeats in this scenario. Thanks for running through this with me!

My updates will cause Firefox to fail grid-template-computed-nogrid.html, and Chromium and Safari will pass due to this resolution.

**Comment by KurtCattiSchmidt** [comment]
This was fixed in Chromium a few weeks ago by *not* expanding repeats (as @Loirooriol described) in this CL: https://chromium-review.googlesource.com/c/chromium/src/+/4317507. I also updated the test to include this assertion, so Firefox is now failing [grid-template-computed-nogrid.html](https://wpt.fyi/results/css/css-grid/subgrid/grid-template-computed-nogrid.html?label=master&label=experimental&aligned&view=subtest&q=grid-template-computed-nogrid.html%20)
