### ISSUE TITLE
[css-values-4] Allow omitting `<declaration-value>` in `mix()`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8556]
If I am not mistaken, [`mix()`](https://drafts.csswg.org/css-values-4/#funcdef-mix) is valid for custom properties, whose initial value is the guaranteed-invalid value, ie. an omitted value.

  > A `mix()` notation is invalid if either of its `<declaration-value>`s are invalid when interpreted as a whole value for the property the function is used in, or if the property using it is not animatable.

Should `mix()` syntax allow omitting `<declaration-value>` ...

```diff
- <mix()> = mix( <percentage> ';' <declaration-value> ';' <declaration-value> )
+ <mix()> = mix( <percentage> ';' <declaration-value>? ';' <declaration-value>? )
```

... to accept inputs like `--custom: mix(50%; ; on)`?

**Comment by Loirooriol** [comment]
In fact  `mix(50%; ; on)` is using a space so that's already a `<declaration-value>` I think? Omitting it would allow `mix(50%;; on)` I guess.

**Comment by tabatkins** [comment]
Yes, passing a space does indeed satisfy `<declaration-value>`, but I should indeed go ahead and give it `?` since that's also a valid custom property value.
