### ISSUE TITLE
[css-backgrounds-4] Clarify serialization of `box-shadow-*`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8566]
Can you please clarify what should be the result from serializing the specified/computed value of these declarations:

  1. `box-shadow-offset: none`
  2. `box-shadow-offset: 0px 0px`
  3. `box-shadow: none`
  4. `box-shadow: currentColor none`
  5. `box-shadow: currentColor 0px 0px`

I would suggest to serialize 3-5 to `0px 0px` for back-compat, and maybe 1-2 for consistency.

https://drafts.csswg.org/css-backgrounds-4/#propdef-box-shadow
https://drafts.csswg.org/css-backgrounds-4/#propdef-box-shadow-offset

**Comment by SebastianZ** [comment]
Serializing to `0px 0px` is not backwards compatible. Currently, browsers even _expand_ the computed value in some cases, which seems to contradict the [principle to make the serialization as short as possible without changing the value's meaning](https://drafts.csswg.org/cssom/#serializing-css-values).

First, it should be clarified if changes to the serialization can cause web compat issues in this case.

Anyway, here's my take on your question:

1. `box-shadow-offset: none` => specified: `none`, computed: `none` (like for `box-shadow` now)
2. `box-shadow-offset: 0px 0px` => specified: `0px 0px`, computed: `0px 0px` (like for `box-shadow` now)
3. `box-shadow: none` => specified: `none`, computed: `none` (like now)
4. `box-shadow: currentColor none` => specified: `currentcolor none`, computed: `none` (currently invalid, so probably no compat issues; currently: specified: ``, computed: `none`)
5. `box-shadow: currentColor 0px 0px` => specified: `currentcolor 0px 0px`, computed: `rgb(0, 0, 0) 0px 0px 0px 0px` (like now), though if possible to correct, computed: `0px 0px`

Sebastian

**Comment by cdoublev** [comment]
Oh, I did not realize that browsers do not omit `currentcolor` or `0px` (for blur/spread). I am fine with this current state of interop because I am not a fan of the shortest serialization principle for various reasons.

As noted in #8568, I thought it was required/interesting to try to serialize case 4 with a backward compatible value. The other cases depend on this choice. But if backwards compatibility is not required, this issue can be closed. =)

**Comment by SebastianZ** [comment]
Closing this issue without spec. change as of the last comment.

Sebastian
