### ISSUE TITLE
[css-anchor-1] `anchor()` inside an `inset` shorthand

### ISSUE THREAD

**Issue by kizu** [w3c/csswg-drafts#8582]
<details>
<summary>Disclaimer and additional links</summary>

I'm submitting my feedback following my experiments with the current implementation of anchor positioning in Chrome Canary.

I wrote an article about my experiments, but decided to fill most of my feedback as separate issues here.

A quick summary of related links:

- [anchor positioning specs](https://drafts.csswg.org/css-anchor-position-1/)
- [my article with the experiments](https://kizu.dev/anchor-positioning-experiments/)
</details>

In my experiments I often did the following:

```CSS
top:    anchor(--my-anchor top);
right:  anchor(--my-anchor right);
bottom: anchor(--my-anchor bottom);
left:   anchor(--my-anchor left);
```

What I would want to be able to do instead:

```CSS
inset: anchor(--my-anchor);
```

Currently, this does not work, and the specs do not define how the anchors inside the `inset` should behave.

Because the current Chrome Canary implementation does not seem to support `auto` and `auto-same`, I'm unable to check if those would help, but maybe they will? I did not really dig into the fallback stuff yet, so not entirely sure if any of those would solve this use case.

**Comment by johannesodland** [comment]
I agree that having a method to get a four value inset from the anchor would be great.

If we some day could perform operations on 1-to-4-value shorthands, this could become really flexible. 
For example, we could add to the inset shorthand using a function like this:

```css
inset: sum-1-to-4(anchor(--my-anchor, inset), 10px);
```

And we could also find the minimal rectangle that contains a set of anchors:
```css
inset: min-rectangle-1-to-4(anchor(--anchor-1, inset), anchor(--anchor-2, inset));
```

**Comment by tabatkins** [comment]
The `auto-same` keyword should do what you want, yes. It resolves to the same side as the property it's in, so `inset: anchor(--foo auto-same);` will set all four edges to the corresponding edge of the anchor.

(Because none of the insets will be auto, it won't have any fallback implications.)

**Comment by kizu** [comment]
@tabatkins I'm re-reading the specs, and I think the wording in the place about the `auto` and `auto-same` could be improved a bit: from the specs text it _sounds_ like the `inset: anchor(--foo auto-same);` won't work due to this:



> If a positioned element uses the anchor() function with the auto or auto-same keywords in one of its inset properties, **and the opposing inset property is auto**,

and this:

> Automatic anchor positioning is only active if the opposite inset property is auto.

`inset: … auto-same` would feel like it won't work, as it would be not `auto` on the opposing side, but `auto-same`.

In addition to that, I'm wondering if the whole “If this is not the case, the anchor() function represents an invalid anchor query, and the element does not use automatic anchor positioning in that axis” makes it impossible to just use the `auto` and `auto-same` as shortcuts for the “opposing side” and “same side” when the other side is not `auto`, but some specific calculation.

I think, an ability to use `auto` and `auto-same` just as the shortcuts for the sides can be very helpful when defining anchors as reusable custom properties, or as parts of the fallback definitions.

What if we would split the part where the keyword works as the side/opposing side, and where it provides the automatic position-fallback, making the “opposing side needs to be auto” to apply only for the fallback part, keeping the side shortcuts working as is? This would make the `inset` work, and would unlock the keywords for the non-fallback use-cases.
