### ISSUE TITLE
[css-text-4] Does no-autospace replace remove space characters?

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#8590]
8.4. Automatic Contextual Spacing: the [text-autospace](https://drafts.csswg.org/css-text-4/#propdef-text-autospace) property
https://drafts.csswg.org/css-text-4/#text-autospace-property

> The specified spacing is automatically inserted even if there is already a [space](https://drafts.csswg.org/css-text-4/#spaces) (U+0020) at that point;

The spec talks about 'automatic _insertion_', but will it _remove_ 0020 too, if the `no-autospace replace` is used?

**Comment by frivoal** [comment]
The grammar is:
> no-autospace | [ ideograph-alpha || ideograph-numeric || punctuation ] || [ insert | replace ]

by the precendence rules of the `|` and `||` operators, that's equivalent to

> no-autospace | [ [ ideograph-alpha || ideograph-numeric || punctuation ] || [ insert | replace ] ]

So you cannot combine `no-autospace` with `replace`, making this question moot.
