### ISSUE TITLE
[css-conditional] How to check at-rules with @supports()

### ISSUE THREAD

**Issue by CanadaHonk** [w3c/csswg-drafts#8595]
How should at-rules be checked if supported by `@supports()`? (Are they supposed to be able to?) Apologies if already known, couldn't find in spec or another issue.

**Comment by cdoublev** [comment]
See https://github.com/w3c/csswg-drafts/issues/2463#issuecomment-1016720310.

**Comment by CanadaHonk** [comment]
Thanks! Is that in a spec document anywhere yet?

**Comment by cdoublev** [comment]
I do not think so but there are further interesting discussions in #6966. =)

**Comment by CanadaHonk** [comment]
Thanks for the links! Will close this now.
