### ISSUE TITLE
[css-view-transitions-1] Exposing ink overflow rect bounds to script

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8597]
The steps for capturing an element's image during View Transitions involve painting the element and all its descendants in their entirety such that the produced image's bounds are equal to the element's [ink overflow rectangle](https://www.w3.org/TR/css-overflow-3/#ink-overflow-rectangle) bounds. The spec text is [here](https://drafts.csswg.org/css-view-transitions-1/#capture-the-image-algorithm).

The `::view-transition-group` pseudo-element which displays the image has bounds equal to the captured element's border-box. Since the image's natural size is equal to the element's ink overflow area but it needs to be drawn in an element which is smaller than that, we use `object-view-box` to ensure the correct subset paints into the element.

So for example if you have a 100x100 box with a shadow that paints 10px outside this box:

- The ink overflow rect is [-10, -10] 120X120.
- The natural size of the produced image will be 120x120.
- The `::view-transition-group` for this will be sized to 100x100.
- The `object-view-box` set on this group will be `inset (10px, 10px, 10px, 10px)`.

Given that script can read the `object-view-box` on the group, it allow authors to query the value for ink overflow rectangle computed by the UA.

There was an additional risk of fingerprinting if `object-view-box` was affected by where the UA decided to clip the element's painting. But with the resolution in #8561 that is not an issue. Clipping the element's painting is an internal detail, the natural size of the image and its `object-view-box` value is always as described above.

It came up during the discussion in #8561 that its odd that the computed ink overflow rectangle is being exposed to authors. Since there are cases where it is technically infinite and left undefined, see spec text [here](https://www.w3.org/TR/css-overflow-3/#ink-overflow:~:text=Since%20some%20effects%20in%20CSS%20(for%20example%2C%20the%20blurs%20in%20text%2Dshadow%20%5BCSS%2DTEXT%2D3%5D%20and%20box%2Dshadow%20%5BCSS%2DBACKGROUNDS%2D3%5D%2C%20which%20are%20theoretically%20infinite)%20do%20not%20define%20what%20visual%20extent%20they%20cover%2C%20the%20extent%20of%20the%20ink%20overflow%20is%20undefined.). So now authors will see a value for it based on the UA's implementation.

Questions:
- Is the above ok as-is? The value is exposed to script.
- If the value shouldn't be exposed to script, how do we set that up. We can't just elide it from getComputedStyle. An author could do `object-view-box: unset` and learn the value based on how it affects the size of the replaced element displaying this image.

@chrishtr @fantasai FYI.

**Comment by khushalsagar** [comment]
Offline discussion, it sounds like we need to define ink overflow area in the spec precisely for IntersectionObserver anyway. So exposing that here shouldn't be an issue. @dbaron FYI.

**Comment by khushalsagar** [comment]
The IntersectionObserver discussion touching upon this is [here](https://github.com/mozilla/standards-positions/issues/109#issuecomment-443360263) btw.

**Comment by flackr** [comment]
> * If the value shouldn't be exposed to script, how do we set that up. We can't just elide it from getComputedStyle. An author could do `object-view-box: unset` and learn the value based on how it affects the size of the replaced element displaying this image.

If it shouldn't be exposed to script, I think we would keep it as some internal detail associated with the specific replaced element, and combine it with any object-view-box specified by the developer (e.g. similar to an ancestor / descendant transform). There would be no ability to unset the internal object-view-box.

**Comment by fantasai** [comment]
In general, I think we want to say that `object-view-box` operates on the defined bounds of an image; and if the image has stuff that paints outside it, that's painted outside the measured bounds if it's not clipped. For example, for an SVG image, we want to use the viewbox of the SVG image, but an SVG image has a theoretically infinite canvas, and there can be things drawn outside the viewbox; if we're not clipping to the viewbox rectangle, then you'll see those things. But we shouldn't be measuring them when trying to position the SVG inside a replaced element's content area.

**Comment by khushalsagar** [comment]
This sounds fine to me from an implementation perspective. Especially with the resolution we had at #8561, there is already precedent for the natural image size (as exposed to authors via `object-view-box`) to be different from what is actually rendered by the browser.

I'm curious though, are we going with the scrollable overflow rect because ink overflow is undefined? If another feature on the platform (like IntersectionObserver) required us to define the ink overflow extent, would we still use scrollable overflow?

We could just not expose `object-view-box` to authors at all. The natural image size can then be the ink overflow rect and the exact value will stay an internal UA detail. The motivation for exposing it is the assumption that authors would want to customize based on that data. So we should expose the value which authors would actually use, and maybe that is scrollable overflow rect. Just want to ensure that what we choose is based on what makes sense to authors, not based on ink overflow being undefined on the platform today.

**Comment by ydaniv** [comment]
@khushalsagar yes, what @fantasai wrote and your analogy to SVG is exactly what I had in mind:
The viewBox relates to vector elements that are part of the layout and can be measured.
The ink overflow here can be thought of as (and usually is) raster effects that can't be measured and aren't part of the layout, only the paint.
It's usually enough to be able to allow overflow, and not necessary to query it.

**Comment by noamr** [comment]
Sorry but I'm missing how this resolution would work in practice. The SVG analogy doesn't hold (or I'm misunderstanding part of it). Let me explain and correct me if I got some of this wrong (apologies, I'm new to this spec).

Let's say we're transitioning a 100x100 element that's 10px blurry from all sides. This would snapshot a 120x120 image, that according to this resolution would appear to the web developer as a 100x100 image. Let's say that the developer changes the `object-view-box` of the pseudo-element to be the top left quarter (0,0 50x50). What happens to the ink overflow/the blurry part?


Given that * is the blurry part and 0 is the content, which one is it?
```
***
*00
```

or
```
****
*00*
****
```
?

The former doesn't seem like what the developer intended, and the latter would require keeping the filter information as part of the transition so that we could re-apply the blur, which seems like a big change.

In SVG this is not a problem since the ink-overflow bit can be derived from the SVG and CSS. But here all we have is a previously snapshotted image.

**Comment by noamr** [comment]
Ok I think I found my mistake, ink overflow is used at time of capture rather than at time of crop. I can work with that, ignore my previous comment
