### ISSUE TITLE
[css-inline] naming of text-top and text-bottom baselines

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#860]
Should `text-top` be renamed `text-over`? 
Should `text-bottom` be renamed `text-under`?

Maybe it’s better not to use those terms for consistency with legacy [vertical-align](https://drafts.csswg.org/css-inline/#propdef-vertical-align).

**Comment by litherum** [comment]
If they are indeed baselines, we should probably match the terminology in fonts.

https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6bsln.html
