### ISSUE TITLE
[css-backgrounds-3] Computed value of `background-image` wrong

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8604]
The computed value of the `background-image` property is currently defined as "computed `<image>`".
Though the value is actually a list of `<bg-image>`s, i.e. a list of `<image>` values and `none` keywords.

So it looks like this needs to be fixed and say something like

"list, each item either the keyword `none` or an `<image>`"

Sebastian

**Comment by fantasai** [comment]
Fixed, thanks. :)
