### ISSUE TITLE
[css-view-transitions-1] Clarify the size of snapshot when there are nested transitioning elements.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8606]
The spec talks about skipping nested transition elements [here](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics:~:text=For%20each%20descendant%20of%20shadow%2Dincluding%20descendant%20Element%20and%20pseudo%2Delement%20of%20element%2C%20if%20descendant%20has%20a%20computed%20value%20of%20view%2Dtransition%2Dname%20that%20is%20not%20none%2C%20then%20skip%20painting%20descendant.).

And then describes the size of the image to be the ink overflow rect [here](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics:~:text=If%20element%E2%80%99s%20ink%20overflow%20area%20does%20not%20exceed%20an%20implementation%2Ddefined%20maximum%20size%2C%20then%20return%20a%20rectangle%20that%20is%20equal%20to%20element%E2%80%99s%20ink%20overflow%20rectangle.).

There's a couple of things to fix here:
- We only skip painting nested elements which actually participate in a transition, and that could technically exclude some elements which have a `view-transition-name`.  This [issue](https://drafts.csswg.org/css-view-transitions-1/#issue-2bfbc0f2) already mentions this.
- Also, the ink overflow rect for image bounds is excluding the overflow that came from nested transition elements, since those were skipped during paint. This also needs to be explicit.

@jakearchibald @vmpstr FYI.

**Comment by jakearchibald** [comment]
Sounds sensible to me. Although, I'm not sure it's bad if the image bounds are bigger than necessary in some implementations, as long as the object-view-box brings it back down to the border box.

**Comment by khushalsagar** [comment]
Fixed by https://github.com/w3c/csswg-drafts/pull/8819
