### ISSUE TITLE
[cssom-1] [css-cascade] CSSImportRule.sheet not being null conflicts with @import supports()

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#8608]
https://drafts.csswg.org/css-cascade-5/#at-import:

> Additionally, if a [&lt;supports-condition>](https://w3c.github.io/csswg-drafts/css-conditional-3/#typedef-supports-condition) blocks the application of the imported style sheet, the UA must not fetch the style sheet (unless it is loaded through some other link) and must return null for the import rule’s CSSImportRule.styleSheet value (even if it is loaded through some other link).

But https://drafts.csswg.org/cssom-1/#dom-cssimportrule-stylesheet is not nullable.

I think the fix is obvious (just make it nullable). Not sure if that needs a resolution tho?

**Comment by tabatkins** [comment]
CSSOM is CR-level, so yes, normative changes need WG resolution. (But should be quick and easy.)

**Comment by SebastianZ** [comment]
@tabatkins CSSOM is still WD-level, not CR-level.

Sebastian
