### ISSUE TITLE
[css-inline] Should first/last baseline values of `vertical-align` belong to `alignment-baseline` or separate longhand?

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#861]
Do we need to add first and last to [baseline values](https://drafts.csswg.org/css-inline/#transverse-alignment)? 

Note, in this property, these are combinatorial, whereas in the align/justify-self/content properties, it’s singular. Do we want to align the syntaxes wrt hyphens vs. spaces or what?

**Comment by fantasai** [comment]
OK, so we resolved in having them space separated in https://lists.w3.org/Archives/Public/www-style/2016Oct/0130.html

The remaining question is whether they should be incorporated into the `alignment-baseline` longhand, or as a separate property that is also a sub-property of `vertical-align`.

**Comment by dbaron** [comment]
I'd note the link in the initial comment here is to `dominant-baseline` rather than `alignment-baseline`.  Is this issue intended to cover both properties, or only `alignment-baseline` (possibly separated into a new longhand)?

**Comment by fantasai** [comment]
@dbaron Only alignment-baseline. I"ll edit the link...

**Comment by fantasai** [comment]
Edits committed. Went with `baseline-source: auto | first | last` (the `auto` being necessary because *some* working group decided way back when that inline-block and inline-table should have different behaviors...)

**Comment by fantasai** [comment]
Please file new issues for any follow-up, renaming, missing details, etc. :)
