### ISSUE TITLE
[css-contain-4] Make content-visibility animatable

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#8627]
[css-contain Section 4](https://w3c.github.io/csswg-drafts/css-contain/#content-visibility) currently defines the content visibility property to be Animation type: not animatable. Most likely this was done for simplicity since like display it can affect which animations are running. However, as with display where we are better refining the ways in which it is safe to animate (See #6429), we should figure out in which ways content-visibility can be animated.

In particular, just like display it should be possible for an animation to extend the application of `content-visibility: visible` in order to allow content to stay visible while an animation is completing. This would be useful for elements like `<details>` whose contents are `content-visibility: hidden` when closed.

**Comment by chrishtr** [comment]
`content-visibility` was mentioned [here](https://github.com/w3c/csswg-drafts/issues/6429), but we just reailzed it wasn't explicitly covered during the CSSWG agenda on the topic. I don't think it will be at all controversial, so propose an async resolution

**Comment by flackr** [comment]
My simple proposal would be that `auto` and `hidden` are both not allowed by owned animations (e.g. CSS animations), and these two values would be treated as revert, as either of these values could result in a CSS animation no longer running.

**Comment by astearns** [comment]
@flackr can you put a bit more detail into your proposal? I am not entirely sure how to summarize the above for an async resolution.

**Comment by astearns** [comment]
RESOLVED: Make content-visibility animateable as above
