### ISSUE TITLE
[css-contain-3] Conflicting value and computed value for `container-type`

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8643]
In the [definition](https://w3c.github.io/csswg-drafts/css-contain-3/#container-type) of `container-type`, the value of this property is defined to be:

```
normal | size | inline-size
```

whereas the computed value is:

> the keyword `normal` or one or more of `size`, `inline-size`

Should the value be defined as below then?

```
normal | size || inline-size
```

**Comment by Loirooriol** [comment]
No, the grammar is good. `size` already implies `inline-size`, so combining them doesn't make much sense.

The wording is a remnant of 3aed70b094c3ca92eb7d2df1dc49198b8e546031, previously you could have `style size` or `style inline-size`.
