### ISSUE TITLE
[css-values-4] Recursive math functions are inconsistently specified

### ISSUE THREAD

**Issue by AtkinsSJ** [w3c/csswg-drafts#8664]
The spec about math functions is a bit inconsistent, at least from what I can tell. Each math function is described as allowing a `calculation` for its parameters, but that links specifically to the `calc()` definition, whereas the examples show that other math functions are allowed there. The [syntax description](https://drafts.csswg.org/css-values-4/#calc-syntax) does not itself allow any function (including `calc()`) to appear as a parameter to another math function.

So the issues here are:
- The syntax should allow for math functions as part of `<calc-value>`.
- The places that currently link to `calculation` should link elsewhere. The usage of `calculation` includes literal numbers or values, and math functions, as well as calc-like expressions. (Which generally corresponds to `<calc-value>`.)

**Comment by AtkinsSJ** [comment]
This is also a problem with the previous, simpler definition from CSS-VALUES-3. Strictly following the given syntax means that `calc(3 + calc(4 * 2))` is invalid, when it should be valid.

**Comment by tabatkins** [comment]
> Each math function is described as allowing a calculation for its parameters, but that links specifically to the calc() definition, whereas the examples show that other math functions are allowed there.

Specifically, they link to the "calculation" definition, which happens to be placed in the section defining calc(); they're not linking to `calc()` itself. The definition is not calc()-specific; it describes the *argument* to calc() (and the other math functions): "a sequence of values interspersed with operators, and possibly grouped by parentheses (matching the [`<calc-sum>`](https://drafts.csswg.org/css-values-4/#typedef-calc-sum) grammar)"

> The [syntax description](https://drafts.csswg.org/css-values-4/#calc-syntax) does not itself allow any function (including calc()) to appear as a parameter to another math function.

They do. All the grammar definitions eventually bottom out in `<calc-value>`, which is `<number>`/`<dimension>`/etc. Math functions match those productions based on what they contain, as specified in [Type Checking](https://drafts.csswg.org/css-values-4/#calc-type-checking).
