### ISSUE TITLE
[scroll-animations-1] Physical axis names mismatch

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8666]
`scroll-snap-type` uses `x` and `y`, but `scroll-timeline-axis` uses `horizontal` and `vertical`. We should get these aligned. :)

**Comment by fantasai** [comment]
Proposal: rename `horizontal` and `vertical` keywords in Scroll Animations to `x` and `y` to match Scroll Snap (`scroll-snap-type`) and Overflow (`overflow-x/y`).

**Comment by birtles** [comment]
Seems reasonable to me.

**Comment by flackr** [comment]
Sounds good to me.

**Comment by astearns** [comment]
Looks like enough consensus to me :) 

The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Rename horizontal and vertical keywords in Scroll Animations to x and y to match Scroll Snap (scroll-snap-type) and Overflow (overflow-x/y).

**Comment by astearns** [comment]
**Resolved**: Rename horizontal and vertical keywords in Scroll Animations to x and y to match Scroll Snap (scroll-snap-type) and Overflow (overflow-x/y).
