### ISSUE TITLE
[scroll-animations-1] Three-value `animation-range` shorthand notation

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8672]
Currently `animation-range` is [defined with the following syntax](https://drafts.csswg.org/scroll-animations-1/):

```
animation-range: [ <<'animation-range-start'>> <<'animation-range-end'>>? ]#
```

We added the following rules:
* In the longhands, as well as in the shorthand, if a range name is given but the offset is omitted, it defaults to 0% for -start and 100% for -end.
* In the shorthand, if the second value is omitted and the first value has a range name, it copies the range name from the first and takes a 100% offset. (The second value otherwise defaults to the initial value, `normal`).

What we didn't discuss was what happens if two offsets and a keyword were specified, e.g.

```
animation-range: contain 10% 90%;
animation-range: 10% contain 90%;
```

These don't fall under the special range-name duplication rules we decided in https://github.com/w3c/csswg-drafts/issues/8438, so the standard behavior that falls out is:

```
animation-range: contain 10% 90%;
animation-range-start: contain 10%;
animation-range-end: 90%;

animation-range: 10% entry 90%;
animation-range-start: 10%;
animation-range-end: contain 90%;
```

We have several options here:
* Assign the longhand values exactly as specified (see above).
* Extend the range name duplication rule to apply to also apply to double offset values.
    * In this case, such longhand combinations would not have a serialization in the shorthand, unless we made some more explicit serialization like “normal 10%” also valid and equal to “10%”. See [suggestion](https://github.com/w3c/csswg-drafts/issues/8438#issuecomment-1488270914) from @cdoublev.
* Make these types of values (two offsets, one keyword) invalid.

Imho, while making `contain 10% 90%` expand to `contain 10% contain 90%` seems nice, doing that for the analogous `10% contain 90%` makes a bit less sense, and I'm not sure that making “normal” act like a range is a good idea, since it's supposed to represent the absence of a range restriction... And making them invalid seems unnecessary work, since these syntaxes are normal consequences of a basic shorthanding relationship. So I'm inclined to go for the first option. Thoughts?

**Comment by ydaniv** [comment]
I think we need to have a general rule for ranges without names. For example, how does `100px 20vh` expand? Or `20% 80%`?
My suggestion is to always expand a missing name to the full range of the attached timeline. In case of a ScrollTimeline this should work as expected.
In case of a ViewTimeline this would be the entire `cover` range.
For future timelines, say HoverTimeline, this could be the viewport, and so on.
@fantasai I think that's what you meant by using `normal` here?

**Comment by flackr** [comment]
@fantasai I agree with your conclusion that going with option 1 makes sense.

@ydaniv yes that is my understanding as well, the intention is that not specifying a range associates with the "normal" or default range so either of the things you specified would be over the entire scroll timeline range or cover view timeline range.

**Comment by flackr** [comment]
Though thinking about this further, we may want an omitted range with specified value for ViewTimeline to refer to the entire scroll range. This would allow doing things with absolute pixel offsets, allowing things such as what was discussed here: https://github.com/w3c/csswg-drafts/issues/8578#issuecomment-1540705525

**Comment by ydaniv** [comment]
Agreed. Example: animating an element that scrolls into view, becomes sticky, and then remains sticky till end of document, but animates all the way, or until an absolute point:

```css
.sticky {
  position: sticky;
  top: 0;
  animation: hue-rotate both view();
  animation-range: entry 0% 100%;
}
```

**Comment by fantasai** [comment]
@flackr An issue with that is that `animation-range: normal` needs to map to the `cover` range on view timelines; making `animation-range: 10% 90%` use a completely different range than `normal` seems unexpected?

**Comment by ydaniv** [comment]
@fantasai I think it's fine, having a specified `%`'s value that will behave differently from `normal`.

Also need to consider what happens in case of `animation-range: 100px 1000px`, should be the same, right?
