### ISSUE TITLE
css as a replacement for html?

### ISSUE THREAD

**Issue by ghost** [w3c/csswg-drafts#8674]
Hi everyone!

I would like to know if there is interest in having css replace html. When I say that: "if there is interest in having css replace html", ask me if it wouldn't make more sense to use html for text markup. Because a lot of what should be text in the html isn't. The html nowadays is as complex as it was xml, sgml.

One of my concerns today is what part of a hypertext is being held by css. For example CSS animations, import things in CSS. In that sense, I don't imagine that in a few years developers will opt for html or choose this type of file format or text markup format.

Also, a lot of people who have developed stuff on the web have complained a lot about the text markup format called "xml". It was said that xml was a complex and difficult to use format. Over time, some said that html was simplified xml. However, my perception over the years has been that html has become what it shouldn't be: xml.

Now, using the present and future argument. Imagine that something simpler than html is the css format. Although CSS is a visual format and not for hypertext, CSS has many of what HTML lacks, such as flexibility and animations. Some would say the html should just be text, but it's not. If there are hyperlinks within the css, in my opinion the css can definitely replace the html.

It is currently possible with css: import and create components natively and is supported by any current browser. Creating componentization with html is complicated and not always supported by browsers. In that sense, I imagine that the css format is much more applicable to text than html.

From a technical point of view, it's easier to render something visually than it is to create a full layer for the dom (document object model) to make the text dynamic. In my opinion, css+js is more hypertext than html. Today we have with html, several tags, attributes. The browser today has to read large lines of html and render with css and js. Is there no possibility to render just the css without the html?

- Why is html today complex? 
- Why can't it be something simple like css?

**Comment by Crissov** [comment]
> I would like to know if there is interest in having css replace html.

No, none whatsoever. 

I think there have been proposals for markup formats using C(SS)-like curly braces instead of angular brackets before, probably posted on some 1 April. 

~~~~ css
body {
  font-family: sans-serif;
  class: "example";
  h1 {
    content: "Hello world!";
    id: "headline";
    font-size: large;
  }
}
~~~~
