### ISSUE TITLE
[css-color-4] Is color-mod() = color(…) a typo?

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#868]
```
color-mod() = color( [ <color> | <hue> ] <color-adjuster>* )
```

Source: https://drafts.csswg.org/css-color/#modifying-colors

Why is `color-mod` on the left and `color` on the right? Shouldn’t the same identifier be on both sides?

---

Note to self: Notify https://cloudfour.com/thinks/building-themes-with-css4-color-features/

**Comment by Crissov** [comment]
Duplicate of #813.
