### ISSUE TITLE
[css-shapes-1] Optional values shouldn't be serialized

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8695]
Currently the CSS Shapes draft [specifies](https://www.w3.org/TR/css-shapes-1/#basic-shape-serialization):

> To serialize the [<basic-shape>](https://www.w3.org/TR/css-shapes-1/#typedef-basic-shape) functions, serialize as per their individual grammars, in the order the grammars are written in, avoiding calc() expressions where possible, avoiding calc() transformations, omitting components when possible without changing the meaning, joining space-separated tokens with a single space, and following each serialized comma with a single space.

This seems mostly fine, except there's a couple problems:

1. There's an _example_ that says:

   > Omitting components means that some default values do not show up in the serialization. But since [<position>](https://drafts.csswg.org/css-values-4/#typedef-position) always uses the 2- or 4-value form, a default <position> is not omitted.

   which is nonsense, because omitting a default `at <position>` is required by the normative text above.

   This example is then tested in WPT, which shows that we (unfortunately) have interop on the example rather than on the normative text. However, having special rules that go against our general serialization principles without good reason is an anti-pattern. We should be consistent and allow `at <position>` to be omitted from the serialization just like any other optional component.

2. The guidance about “avoiding calc() expressions where possible, avoiding calc() transformations” conflicts with our more generally-applicable rules about serializing `<position>` and `calc()` values, which distinguish specified-value and computed-value serializations in very particular ways.

Proposal:
1. Fix the examples and tests, and file implementation bugs, allowing `at <position>` to be omitted, consistent with our general serialization principles.
2. Remove guidance about `calc()` serialization, allowing the spec to defer to the more specific serialization rules in css-values-4.

**Comment by tabatkins** [comment]
+1 to both of these

**Comment by BorisChiou** [comment]
+1 to the proposal to omit the `at <position>`. This is especially necessary to motion path because `offset-path` doesn't use the standard default for `at <position>` if the component is omitted.

**Comment by tabatkins** [comment]
We definitely need to omit the `at <position>` when it was omitted by the author, for offset-path to work correctly, but we also need to *preserve* the `at <position>` even if it specifies the default value, for the same reason - `circle(at center)` works differently than `circle()` when used as an offset path, because the latter will use 'offset-position' for the default instead.

**Comment by emilio** [comment]
@tabatkins It's a bit weird to have a magic value by omission, I don't think we have many precedents for such thing? None come to mind right now but I haven't tried too hard...

Maybe there should be an `at default` keyword value to represent that magic state?

**Comment by tabatkins** [comment]
We do have some behaviors that can only be expressed by omission. I can't name them off the top of my head, but I know they exist because I've been annoyed by them in the past. I'd be fine with adding such a value, but that's a separate issue.

**Comment by BorisChiou** [comment]
Per https://github.com/w3c/csswg-drafts/issues/8695#issuecomment-1563497665, it'd be great to specify the expected behaviors for interpolation as well, especially for `offset-path`. I noticed there is a [wpt test](https://github.com/web-platform-tests/wpt/blob/dcf2cd7559b2e1502a160b585e0c5f120db754e6/css/motion/animation/offset-path-interpolation-006.html#L58-L70) like this:
`ellipse(10% 10%)` -> `ellipse(40% 50% at 25% 25%)`.

This test expects to do interpolation by assigning `center` as the default value. However, omitted `at <position>` is special, so I expect these two values can not be interpolated (i.e. fall back to discrete animation). So it'd be great to add the omitted `at position` case in [Interpolation of Basic Shapes](https://drafts.csswg.org/css-shapes-1/#basic-shape-interpolation) as well.

**Comment by cdoublev** [comment]
Should `at center`/`at center center` be the only values omitted when serializing a specified value?

I cannot find any WPT tests that omit `<position>` anywhere, and I do not think general serialization principles currently define whether `50%` can be considered equivalent to `center` or more generally, if a keyword can be considered equivalent to a numeric value, when serializing a specified value.

In FF, any combination of `center` and `50%` is omitted as a `<position>` in `conic-gradient()` and `radial-gradient()`, when serializing a specified value.

But still in FF, any combination of `left`/`top` and `0%`, or `0%` alone, are preserved as a `<bg-position>` in `background` or `mask`, when serializing a specified value, whereas `0% 0%` (the initial value of `background-position` or `mask-position`) is omitted.

Also, FF omits `400` as a `font-weight` (its initial value is `normal`) in `font`.

**Comment by emilio** [comment]
@tabatkins @fantasai so to be clear the expected behavior is to always serialize to a `<length-percentage>`?

**Comment by fantasai** [comment]
@emilio The expected serialization of `<position>` is defined in https://drafts.csswg.org/css-values-4/#position-serialization
