### ISSUE TITLE
[css-inline-3] Split `text-line-edge` from `text-box-edge`

### ISSUE THREAD

**Issue by astearns** [w3c/csswg-drafts#8696]
As I understand it, there was a conversation (mentioned in this [comment](https://github.com/w3c/csswg-drafts/issues/8479#issuecomment-1487918127)) between @fantasai and WebKit’s zalan (not sure if there is a GitHub handle for them) around 
splitting what is currently called `text-box-edge` into two properties - one that factors into line box sizing, and another that determines the `text-box-trim` metrics.

Apparently further conversation between zalan and @litherum resulted in this [issue](https://github.com/w3c/csswg-drafts/issues/8478) describing possible changes to `line-height` instead. But from the breakout session discussion I think the current idea is to have separate properties instead of adding more complications to `line-height`.

So I am filing this issue to have a place to discuss the property split.

**Comment by litherum** [comment]
We do not want to split the property into 2 properties. We want https://github.com/w3c/csswg-drafts/issues/8829.

**Comment by litherum** [comment]
Closing in favor of https://github.com/w3c/csswg-drafts/issues/8829
