### ISSUE TITLE
[css-color-5] incorrect WPT tests for omitted alpha in relative color syntax

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8708]
https://drafts.csswg.org/css-color-5/#origin-color

> [Relative color](https://drafts.csswg.org/css-color-5/#relative-color) syntax doesn’t change whether an argument is required or optional. If the alpha value is omitted, however, it defaults to taking from the [origin color](https://drafts.csswg.org/css-color-5/#origin-color) (rather than defaulting to 100%, as it does in the absolute syntax).

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html#L104

```
test_computed_value(`color`, `rgb(from rgb(20%, 40%, 60%, 80%) 0% 10 10)`, `rgb(0, 10, 10)`);
```

```css
rgb(from rgb(20%, 40%, 60%, 80%) 0% 10 10)
```

The alpha channel is omitted, so alpha should be taken from the origin color.
The result should be : `rgb(0, 10, 10, 0.8)`

Maybe this is a fairly recent change to the specification?

-----

I've updated the WPT tests to match the specification : https://github.com/web-platform-tests/wpt/pull/39508

**Comment by romainmenke** [comment]
(forgot to ping @svgeesus )

**Comment by svgeesus** [comment]
> Maybe this is a fairly recent change to the specification?

No, it was [two years ago](https://github.com/w3c/csswg-drafts/commit/f2b9bb17f8565d946c7e4acba7bf24d2ef731f1b#diff-2035345378942a021190ce428e1f91413c366fec038ea7c90ec1a446100c4f5eR655-R658)

> @tabatkins committed on Feb 26, 2021

**Comment by romainmenke** [comment]
@svgeesus I think there is some confusion here.

This issue and the test changes are not related to using `alpha` as a value in other channels or doing any calculations with `alpha`.

So the ranges shouldn't be a factor.

-----

The specification dictates that there is some form of "pass through" for alpha in particular. So this is always the `alpha` from `origin color` that is being used as the final `alpha`.

**Comment by romainmenke** [comment]
The WPT tests were approved and merged, so I think we can close this @svgeesus ?
