### ISSUE TITLE
[css-syntax-3] Restrict validity of substitution values and math functions

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#8717]
In Chrome/FF, `calc(100% / 3) {}` is an invalid CSS keyframe.

However in [CSS Syntax](https://drafts.csswg.org/css-syntax-3/#rule-defs):

  > *CSS Values 4 § 2 Value Definition Syntax* defines how to specify a grammar for properties. This section extends those definitions to also allow specifying a grammar for rules.

Substitution values (`attr()`, `mix()`, `random-*()`, `toggle()`) and math functions may have to be restricted here.

In my opinion, substitution values should be invalid, except as a declaration value for a feature query in `@supports`, and math functions should only be valid in a declaration value.

Related: #7838.

**Comment by tabatkins** [comment]
> Substitution values (attr(), mix(), random-*(), toggle()) and math functions may have to be restricted here.

All of the "substitution values" are invalid by virtue of only being defined in the context of a property on an element.

Math functions are resolveable anywhere, tho. If we don't want to allow them, that's possible, we just need to define the rule grammar accordingly, for example to use `<percentage-token>` rather than `<percentage>`.

**Comment by cdoublev** [comment]
> All of the "substitution values" are invalid by virtue of only being defined in the context of a property on an element.

It is clear to me. I was thinking of the author who would like to understand why they are invalid outside of this context. But ok.

  > Math functions are resolveable anywhere

Actually, I was more interested in this clarification. So they can be a valid [keyframe selector](https://drafts.csswg.org/css-animations-1/#typedef-keyframe-selector)? (If so, this issue can be closed.) Or should a keyframe selector be defined with `<percentage-token>`?

**Comment by tabatkins** [comment]
> So they can be a valid [keyframe selector](https://drafts.csswg.org/css-animations-1/#typedef-keyframe-selector)? (If so, this issue can be closed.) Or should a keyframe selector be defined with <percentage-token>?

Probably the latter, just due to compat.
