### ISSUE TITLE
[css-transitions][css-color] Animating currentColor

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#873]
The definition of [color interpolation](https://drafts.csswg.org/css-transitions/#animtype-color) isn't explicit about what should happen to `currentColor`. Given that it stays as a keyword at computed value time, one could think that it transition / animations between `currentColor` and other colors are meant to be discrete, but all browsers actually interpolate. This should be made explicit in the spec.

This could probably be done by adding the following sentence to the paragraph.

> Interpolating to or from `currentcolor` is possible. The  numerical value used for this purpose is the used value.

**Comment by upsuper** [comment]
I think this is just a dup of #445.

**Comment by frivoal** [comment]
That's right. Thanks.
