### ISSUE TITLE
[css-content] `none` and `normal` values (for `content` property) are never linkified

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#874]
In the css-content spec, the `none` and `normal` values (for the `content` property) are never linkified, but probably should be. I suspect there's some bug in the markup that prevents the correct link target from being inferred/discovered when bikeshed is generating HTML.

Other values of the same property (like e.g. the `contents` value) *are* successfully linkified.

Sample sections of the spec where this is noticeable:
 * In the definition of the `normal` value, two other values are mentioned -- `contents` and `none`. The former is linkified, the latter is not. https://drafts.csswg.org/css-content-3/#valdef-content-normal
 * In the definition of the `contents` value, all three values (`none`, `normal` and `contents`) are mentioned. Again, only `contents` is linkified. https://drafts.csswg.org/css-content-3/#valdef-content-contents

I don't know bikeshed markup very well, but I'm guessing that perhaps the issue is that there's no `dfn-for="content"` attribute, on the `<dl>` parent of the none & normal `<dfn>` tags...? (At least, the correctly-working `contents` value does have a `dfn-for` attribute on its `<dl>` parent in the bikeshed markup.)

CC @tabatkins

**Comment by dauwhe** [comment]
I've been working on this. I think it's a bit better, but there's more to do. This is one of the more interesting specs when it comes to complex definitions. I'll try to get some markup advice at the F2F.

**Comment by xfq** [comment]
All links to `none` (for `content` property) I found have been linkified, and the only `normal` that's not linkified is the second `normal` in the definition of the `contents` value, which isn't bad, because there's already a link to the definition of `normal` in that paragraph. So I guess this issue can be closed?

**Comment by dholbert** [comment]
I just noticed that my https://drafts.csswg.org/css-content/ URLs from comment 0 are now pointing at `css-content-4`.  Back when I filed this, the URL pointed to `css-content-3`, which now lives at https://drafts.csswg.org/css-content-3/ (which is where the `content` property and its `none`/`normal` values are defined).

Anyway: I've edited the original comment here to use links with the version number.  And yes, I agree with @xfq - it looks like this has been addressed (mostly if not entirely).

**Comment by xfq** [comment]
Hmm, I think css-content doesn't have L4 yet?

**Comment by dholbert** [comment]
Oh, sorry, you're right - I had just noticed that https://drafts.csswg.org/css-content/#normal (from my original initial comment) was a broken anchor, and I assumed it was from a level increase and didn't actually look too closely. :)  (and then later updated the anchor target after updating the link to include the level number)

Anyway - the updated links with `-3` are still valid, and this is still fixed, so all is well.
