### ISSUE TITLE
[css-text] Incorrect character for left white square bracket

### ISSUE THREAD

**Issue by xfq** [w3c/csswg-drafts#8749]
https://www.w3.org/TR/css-text-4/#justify-symbols

> As another example, certain full-width punctuation characters (such as U+301A [ LEFT WHITE SQUARE BRACKET) are considered to contain a justification opportunity in Japanese.

The character here is U+005B, rather than U+301A.

**Comment by fantasai** [comment]
Fixed, thanks!
