### ISSUE TITLE
[css-color] [css-color-4] [editorial] inline issues should be captured on GH, linked to

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#875]
https://drafts.csswg.org/css-color/#issues-index

All issues in the editor's draft should be added to GitHub issues (if not here already), and then linked from their inline uses in the draft to the issue on GH (which has discussions etc.) instead of just the summary at the end of the document.

**Comment by svgeesus** [comment]
They are here already, I went through them all and added any that were not here.

I agree they should be linked, I didn't find out how Bikeshed does those links though? Anyone know?

**Comment by xfq** [comment]
Bikeshed has an `Issue(###):` syntax.

Ref:

* https://tabatkins.github.io/bikeshed/#remote-issues
* https://tabatkins.github.io/bikeshed/#metadata-inline-github-issues

**Comment by svgeesus** [comment]
Inline issues fully purged, new issues opend as required for the few that were not already there. Thanks for the feedback!
