### ISSUE TITLE
[css-display] Are text sequences always wrapped with anonymous boxes?

### ISSUE THREAD

**Issue by TKDev7** [w3c/csswg-drafts#8750]
Reading the Display Module, I get the impression that only elements in the element tree generate boxes while text sequences don’t. My guess is that they don’t generate boxes but are wrapped in anonymous boxes and the type of the box depends on the formatting context the text sequence is in?

**Comment by tabatkins** [comment]
You closed this, but just to follow up: right, text sequences aren't boxes, but the formatting context they're in will generate anonymous boxes around them as necessary.
