### ISSUE TITLE
[css-transitions-2] "Suggest an edit for this spec | Github Editor" link is broken

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#8760]
STEPS TO REPRODUCE:
1. Visit https://drafts.csswg.org/css-transitions-2/
2. In the "More details about this document" section at the top: click "Github Editor" (under "Suggest an Edit for this Spec")

ACTUAL RESULTS:
I'm taken to https://github.com/w3c/csswg-drafts/blob/main/css-transitions-2-2/Overview.bs which is 404. (Note the "-2-2" in the URL there.)

EXPECTED RESULTS:
Should be taken to https://github.com/w3c/csswg-drafts/blob/main/css-transitions-2/Overview.bs which is the correct & functional URL for the spec's GitHub editor.

**Comment by birtles** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/c32bba3429847822152a02d6cbd22f072c9243b4
