### ISSUE TITLE
[css-scroll-snap-2] Clarifying scroll-start shorthand values

### ISSUE THREAD

**Issue by DavMila** [w3c/csswg-drafts#8766]
The scroll-snap-2 spec includes scroll-start: https://drafts.csswg.org/css-scroll-snap-2/#scroll-start

The spec currently includes “top”, “bottom”, “left” and “right” as valid values for the scroll-start shorthand but only includes “start”, “center”, “end” and “auto” for the scroll-start-{x, y, block, inline} longhands. Are they simply missing or should the shorthand not have these values?

Assuming they are valid values for the shorthand:
I’m not yet sure what “scroll-start: right”, for example, should mean.
Should it mean “Equivalent to scroll-start-x: 100%” in vertical writing modes but have no effect in horizontal writing modes since the first scroll-start value ought to apply to the block axis (vertical in horizontal writing mode) according to the spec?
If this makes sense, shall I create a relevant pull request editing the spec (https://github.com/w3c/csswg-drafts/blob/main/css-scroll-snap-2/Overview.bs)?

**Comment by fantasai** [comment]
I don't be believe the content of this draft has been vetted by the CSSWG at all... most of the features in it don't seem to be linked to CSSWG discussions.

I've marked it as an Unofficial Draft for now; we'll need to follow up on this later.

**Comment by flackr** [comment]
Each of the features have been discussed in the working group as well as the proposed resolution to start an ED:
scroll-start: https://github.com/w3c/csswg-drafts/issues/6986#issuecomment-1028503857
:snapped, snapChanged and snapChanging : https://github.com/w3c/csswg-drafts/issues/6985#issuecomment-1049029573

**Comment by flackr** [comment]
@DavMila to answer the original question, "left and "right" don't make sense in `scroll-start-y` right? Similarly "left" and "right" would be valid in scroll-start-inline *sometimes*, depending on the writing mode. Since the longhands already imply an axis it's simpler to only have values measured on that axis, but the shorthand can imply the appropriate longhands given the writing mode.

**Comment by DavMila** [comment]
Thanks for clarifying Rob; that makes sense. I think we can close this issue.
