### ISSUE TITLE
Are the different types of trees mentioned in the specs created by user agents or included in the specs to aid understanding?

### ISSUE THREAD

**Issue by TKDev7** [w3c/csswg-drafts#8770]
CSS specifications mention several types of trees, such as the document tree, DOM tree, element tree, flat tree, box tree, and fragment tree. I know that a DOM tree is created by the browser, and you can manipulate it using the DOM API. However, what about the other types of trees? Do browsers create those trees as well, or are they only present in the specifications to simplify comprehension?

**Comment by tabatkins** [comment]
They are specification concepts that only exist internally in browsers (if at all). They're not exposed to public APIs.
