### ISSUE TITLE
Clarification on block box with mixed level boxes

### ISSUE THREAD

**Issue by MrHBS** [w3c/csswg-drafts#8772]
Given a markup like this:
```
<body>
  Some
  <div>Text</div>
</body>
```

Now since block containers can only have block-level or inline-level boxes, I assume the box tree would look like this:
```
block box
  anonymous block box
     anonymous inline box
  block box
```

Is my assumption correct?

**Comment by bfgeek** [comment]
It depends. There are a few different ways of implementing this.

Blink previously did what you describe but now we do:
```
block box
  line box
    Some
  line box
    anonymous block box
      Text
```
(there are other approaches as well).

The reason for this is you may have DOM structure like:
```
<!DOCTYPE html>
<div>
Text <span style="filter:blur(2px)">text
  <div>
    block
  </div>
</span>
</div>
```
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=11591

Making sure the filter applies to the block-in-inline is non-trivial with the first approach.

Ian

**Comment by bfgeek** [comment]
Yeah that section of the css2 spec is bad/over-perscriptive - and lacks experience of these things in practice (esp. that paint affects on inline elements, and how positioning works, etc). Likely that section should have a warning surrounding it.

We've found that the approach described above is significantly simpler, and all the side-effects are exactly the same is the first approach.

Ian

**Comment by bfgeek** [comment]
Blink's old code was exactly the same as WebKit. Gecko also does the first apporach. EdgeHTML I believe had a similar approach to what we do now.

**Comment by Loirooriol** [comment]
Browsers can do whatever they want as long as the result looks like the specified behavior.

**Comment by Loirooriol** [comment]
I guess this can be closed as question answered. To be more explicit, yes, your description in the 1st comment matches https://www.w3.org/TR/CSS22/visuren.html#anonymous-block-level and https://drafts.csswg.org/css-display-3/#block-container 

But once we have a CSS Flow spec, I guess it can be reconsidered whether to follow CSS2 or something like Blink.
