### ISSUE TITLE
[css-view-transitions-2] Don't trigger capture if the navigation doesn't result in Document change

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8782]
A navigation could end with no change in the Document associated with the committed navigation entry, for example fragment navigations or a 204 response. We shouldn't be doing a transition in this case, preferably even capturing of the current Document is not initiated.

This implies that we need to wait until we've received a server response which ensures the navigation will be cross-document before capturing the current Document. This means the current Document has to do at least one render before it is unloaded.

**Comment by noamr** [comment]
Can you share the cost of discarded captures?
I wonder if this requirement is something that's observable to the web developer, e.g. means that there's an extra rAF after receiving the final response and before committing.

**Comment by khushalsagar** [comment]
@noamr can this be closed? The spec text already says we need to wait until the server response before starting capture of the old Document.
