### ISSUE TITLE
[selectors][css-text] Define "content language" in one place

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#879]
From https://github.com/w3c/csswg-drafts/issues/869#issuecomment-271703801

'hyphens' uses https://drafts.csswg.org/css-text-3/#content-language
':lang()' uses https://drafts.csswg.org/selectors/#language

I think there should only be one concept defined here that css-text and selectors should both hook into.

**Comment by annevk** [comment]
See also #2260. Leaving this up to the DOM (or equivalent) makes more sense.

**Comment by fantasai** [comment]
This was fixed in https://github.com/w3c/csswg-drafts/commit/9eed0f927a7a5baea1d86737d15a96c1365cde00 actually, I just typed in the wrong issue number. :(

@annevk The Selectors/CSS Text specifications already defer to the document language on this.
