### ISSUE TITLE
rules for serializing calc() trees sort + and * values by type but not - and / values

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#8803]
If I interpret the [rules for serializing a calc tree](https://drafts.csswg.org/css-values-4/#serialize-a-calculation-tree) literally, they define (in steps 6 and 7) rules for sorting the children of Sum and Product nodes.  The rules for constructing these nodes in the definition of [parse a calculation](https://drafts.csswg.org/css-values-4/#parse-a-calculation) describe how the things preceded by `-` are put in Negate nodes and the things preceded by `/` are put in Invert nodes.

Based on these definitions, it seems like the rules for sorting the children of Sum and Product nodes mean that the terms not preceded by `-` or `/` and that are not `()`-blocks or other math functions appear first, sorted by unit, and then the terms preceded by `-` or `/` or nested in `()`-blocks or other math functions appear afterwards, in the order originally given.

This seems like a strange result.  I would not expect `+` and `-` to be treated this differently.

I have not yet looked into what implementations do, other than noting that [Chromium does not do sorting and the code doesn't really match the spec's structure](https://bugs.chromium.org/p/chromium/issues/detail?id=1180387#c22).

**Comment by dbaron** [comment]
I've started writing [a few tests](https://dbaron.org/css/test/2023/issue-8803) for this, and plan to add some more.

**Comment by dbaron** [comment]
Actually, I think the spec is fine, since the [simplification rules](https://drafts.csswg.org/css-values-4/#simplify-a-calculation-tree) eliminate the unneeded Invert and Negate nodes.  WebKit and Gecko appear to match the spec.

So never mind.

**Comment by tabatkins** [comment]
Sigh, I had a nice comment all written up and was about to send it when you realized the gist of it yourself.

Yeah, between parsing and serialization you're guaranteed at least one simplification pass, which restructures the tree such that serialization does what you expect.
