### ISSUE TITLE
drafts.csswg.org published specs are weeks/months out of date with repo sources

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/csswg-drafts#8809]
A large number of the CSS specs published on drafts.csswg.org are many weeks or even months out of date with their git sources — or in several cases even more than a year out of date.

The following table shows the date when each spec was last published, and compares that with the date for the most-recent commit to the git source for the spec.

Spec URL   | Days since spec<br>last published | Days since source<br> last changed
---------- | ---------------------------: | --------------------------------------:
https://drafts.csswg.org/css-animations-2/	|	66 days ago | [15 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-animations-2/Overview.bs)
https://drafts.csswg.org/css-animations-1/	|	66 days ago | [32 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-animations-1/Overview.bs)
https://drafts.csswg.org/css-backgrounds-4/	|	56 days ago | [28 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-backgrounds-4/Overview.bs)
https://drafts.csswg.org/css-backgrounds-3/	|	58 days ago | [51 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-backgrounds-3/Overview.bs)
https://drafts.csswg.org/css-cascade-5/		|	129 days ago | [20 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-cascade-5/Overview.bs)
https://drafts.csswg.org/css-color-5/		|	68 days ago | [19 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-color-5/Overview.bs)
https://drafts.csswg.org/css-color-4/		|	66 days ago | [24 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-color-4/Overview.bs)
https://drafts.csswg.org/css-display-4/		|	66 days ago | [16 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-display-4/Overview.bs)
https://drafts.csswg.org/css-flexbox-1/		|	108 days ago | [50 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-flexbox-1/Overview.bs)
https://drafts.csswg.org/css-font-loading-3/	|	601 days ago | [34 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-font-loading-3/Overview.bs)
https://drafts.csswg.org/css-fonts-4/		|	61 days ago | [44 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-fonts-4/Overview.bs)
https://drafts.csswg.org/css-grid-2/		|	243 days ago | [53 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-grid-2/Overview.bs)
https://drafts.csswg.org/css-images-4/		|	61 days ago | [1 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-images-4/Overview.bs)
https://drafts.csswg.org/css-images-3/		|	124 days ago | [1 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-images-3/Overview.bs)
https://drafts.csswg.org/css-inline-3/		|	156 days ago | [35 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-inline-3/Overview.bs)
https://drafts.csswg.org/css-lists-3/		|	437 days ago | [53 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-lists-3/Overview.bs)
https://drafts.csswg.org/css-overflow-3/	|	65 days ago | [39 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-overflow-3/Overview.bs)
https://drafts.csswg.org/css-position-3/	|	65 days ago | [38 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-position-3/Overview.bs)
https://drafts.csswg.org/css-pseudo-4/		|	112 days ago | [40 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-pseudo-4/Overview.bs)
https://drafts.csswg.org/css-ruby-1/		|	131 days ago | [53 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-ruby-1/Overview.bs)
https://drafts.csswg.org/css-scroll-snap-1/	|	65 days ago | [16 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-scroll-snap-1/Overview.bs)
https://drafts.csswg.org/css-sizing-3/		|	65 days ago | [53 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-sizing-3/Overview.bs)
https://drafts.csswg.org/css-text-4/		|	65 days ago | [12 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-text-4/Overview.bs)
https://drafts.csswg.org/css-text-3/		|	83 days ago | [12 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-text-3/Overview.bs)
https://drafts.csswg.org/css-transforms-1/	|	445 days ago | [30 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-transforms-1/Overview.bs)
https://drafts.csswg.org/css-transitions-2/	|	66 days ago | [12 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-transitions-2/Overview.bs)
https://drafts.csswg.org/css-transitions-1/	|	66 days ago | [54 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-transitions-1/Overview.bs)
https://drafts.csswg.org/css-values-5/		|	97 days ago | [30 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-values-5/Overview.bs)
https://drafts.csswg.org/css-values-4/		|	61 days ago | [2 days ago](https://github.com/w3c/csswg-drafts/commits/main/css-values-4/Overview.bs)
https://drafts.csswg.org/cssom-view-1/		|	143 days ago | [12 days ago](https://github.com/w3c/csswg-drafts/commits/main/cssom-view-1/Overview.bs)
https://drafts.csswg.org/cssom-1/		|	201 days ago | [10 days ago](https://github.com/w3c/csswg-drafts/commits/main/cssom-1/Overview.bs)
https://drafts.csswg.org/mediaqueries-4/	|	129 days ago | [54 days ago](https://github.com/w3c/csswg-drafts/commits/main/mediaqueries-4/Overview.bs)
https://drafts.csswg.org/scroll-animations-1/	|	58 days ago | [1 days ago](https://github.com/w3c/csswg-drafts/commits/main/scroll-animations-1/Overview.bs)
https://drafts.csswg.org/web-animations-1/	|	67 days ago | [38 days ago](https://github.com/w3c/csswg-drafts/commits/main/scroll-animations-1/Overview.bs)
https://drafts.csswg.org/web-animations-2/	|	67 days ago | [32 days ago](https://github.com/w3c/csswg-drafts/commits/main/web-animations-2/Overview.bs)

It seems reasonable for the wider web-developer community and PR contributors and browser implementors and spec editors to expect that whenever a change is made to any CSS spec source in the git repo, the corresponding drafts.csswg.org spec will get automatically rebuilt and republished.

(That auto-publishing behavior is what was happening with the w3c.github.io/csswg-drafts specs. And speaking from my perspective as an MDN/BCD contributor, I can say it’s the behavior that MDN and BCD maintainers have been relying on when reviewing MDN and BCD PRs related to CSS features — and I can imagine it also being the behavior that other groups of stakeholders are similarly expecting).

**Comment by Loirooriol** [comment]
@plinss

**Comment by plinss** [comment]
Not my issue, drafts.csswg.org is currently proxying w3c.github.io/csswg-drafts for all built specs.

Ping @tabatkins

**Comment by tabatkins** [comment]
I'm confused. I just looked at the top half-dozen, and they're all exactly up-to-date. And as far as I can tell the "temporary fix" isn't relevant to this either, it just puts back the unlevelled versions (which I left broken under the assumption someone would complain if it was an issue; I'll take this as just such a complaint).

But I'm still definitely confused what precisely is supposed to be broken, and how.

**Comment by sideshowbarker** [comment]
> I'm confused. I just looked at the top half-dozen, and they're all exactly up-to-date. 

https://drafts.csswg.org/css-animations-2/ shows _“W3C First Public Working Draft, 2 March 2023”_

<img width="640" alt="image" src="https://user-images.githubusercontent.com/194984/236732004-cad2061e-6388-43e4-990c-64e0eefedf1f.png">

And the `Last-Revised` HTTP header has `Sat, 11 Mar 2023 06:05:07 GMT`

```
$ curl -I https://drafts.csswg.org/css-animations-2/
HTTP/1.1 200 OK
Date: Mon, 08 May 2023 04:14:48 GMT
Server: Apache/2.4.10 (Debian)
Last-Modified: Mon, 8 May 2023 01:50:41 GMT
Last-Revised: Sat, 11 Mar 2023 06:05:07 GMT
```

https://github.com/w3c/csswg-drafts/commits/main/css-animations-2/Overview.bs shows more than a dozen changes have been committed to the spec source since 2 March 2023.

…and so on, down the line, for all the specs listed in the issue description.

**Comment by sideshowbarker** [comment]
> And as far as I can tell the "temporary fix" isn't relevant to this either, it just puts back the unlevelled versions

Yes, to be clear: That’s exactly what it puts back (and all that it puts back). It’s not intended as a fix for the problem of all the drafts.csswg.org published specs being weeks or months out of date with the repo sources.

I’m also confused by why all the drafts.csswg.org published specs are now out of date — because the w3c.github.io/csswg-drafts published specs were not. (And I’m certain that the w3c.github.io/csswg-drafts specs were not similarly out of date, for two reasons:

- I have automated tooling that runs every day, and before the https://github.com/w3c/csswg-drafts/commit/52077ef4b1b0459f2aef3179dcf47a6c3e185012 change was made, it was showing the expected/correct dates for all the w3c.github.io/csswg-drafts. For confirmation of that, see the numbers in the **Repo** column of https://html-now.github.io/  (which was last published before the https://github.com/w3c/csswg-drafts/commit/52077ef4b1b0459f2aef3179dcf47a6c3e185012 change was made).
- I have other automated tooling that runs every day to check for broken URLs and broken fragment IDs in spec URLs in BCD and MDN, and prior to the https://github.com/w3c/csswg-drafts/commit/52077ef4b1b0459f2aef3179dcf47a6c3e185012 change, it wasn’t showing any broken URLs or fragments. But after that change, it started reporting that the `#dom-cssimportrule-layername` and `#dom-cssimportrule-supportstext` fragments for the CSSOM spec were broken. I earlier raised https://github.com/w3c/csswg-drafts/issues/8806 for that.

  And that broken-URL/fragment-reporting tool also started reporting a 404 for the CSS Positioned Layout Level 4 spec. And that’s because there is no spec published https://drafts.csswg.org/css-position-4/ — whereas there was such a spec published at https://w3c.github.io/csswg-drafts/css-position-4/. I earlier raised https://github.com/w3c/csswg-drafts/issues/8807 for that.

**Comment by plinss** [comment]
The 'Last-Revised' HTTP header is a non-standard header that the draft server uses to communicate with Shepherd's spec parser. It's not relevant here.

Those headers haven;t been updated for a while because the git->mercurial sync has been offline for a few weeks. It's not relevant at the moment either because we're not serving anything directly from the mercurial repo at the moment.

**Comment by sideshowbarker** [comment]
> it just puts back the unlevelled versions (which I left broken under the assumption someone would complain if it was an issue; I'll take this as just such a complaint).

See https://github.com/mdn/content/issues/26613. That https://github.com/w3c/csswg-drafts/commit/52077ef4b1b0459f2aef3179dcf47a6c3e185012 change broke every single CSS spec link in every CSS article in MDN article that has a spec link — which is more than 1000 MDN articles.

**Comment by plinss** [comment]
And the git->hg sync was broken because of the github ssh key change, should be fixed now. So the 'Last-Revised' headers should be in sync shortly. Note that this has *nothing* to do with the content of the specs, which apparently has been in sync all along.

**Comment by sideshowbarker** [comment]
> Note that this has _nothing_ to do with the content of the specs, which apparently has been in sync all along.

Given https://github.com/w3c/csswg-drafts/issues/8806, that doesn’t seem to be true.

Please look at these lines in the current source: https://github.com/w3c/csswg-drafts/blob/c5dff3bbba5ace33cecba3b8bc57d1c64c8392c4/cssom-1/Overview.bs#L2043-L2049

…and then look at https://drafts.csswg.org/cssom-1/#the-cssimportrule-interface —
<img width="659" alt="image" src="https://user-images.githubusercontent.com/194984/236735734-748747f7-e46f-48d6-b605-8b258d14bc74.png">

The published spec is missing the `layerName` and `supportsText` attributes, which were added to the spec source last month.

**Comment by sideshowbarker** [comment]
> The 'Last-Revised' HTTP header is a non-standard header that the draft server uses to communicate with Shepherd's spec parser. It's not relevant here.
> 
> Those headers haven;t been updated for a while because the git->mercurial sync has been offline for a few weeks. It's not relevant at the moment either because we're not serving anything directly from the mercurial repo at the moment.

If the `Last-Revised` header can’t be relied on to give the right date, then that means nobody has any way to programatically determine, from the a GET/HEAD request for the spec, when the spec was last published — because for drafts.csswg.org specs, the `Last-Modified` header also doesn’t provide the date when the spec was last published, and never has. That’s why I had created the `timestamps.json` file (but which is now also gone, after the https://github.com/w3c/csswg-drafts/commit/52077ef4b1b0459f2aef3179dcf47a6c3e185012 change).

**Comment by plinss** [comment]
> …and then look at https://drafts.csswg.org/cssom-1/#the-cssimportrule-interface —

Not sure what you're looking at:
![image](https://user-images.githubusercontent.com/2699689/236737111-3d0e4eba-1e80-4563-a3c2-3492ae9170e4.png)

**Comment by sideshowbarker** [comment]
> Not sure what you're looking at:

I was looking at what I posted a screenshot of in https://github.com/w3c/csswg-drafts/issues/8809#issuecomment-1537738161 — and which I gave the URL for. So either something’s changed in the meantime, or else it was caused by caching somewhere, because I now do also see the `layerName` and `supportsText` attributes as expected.

And I also see that https://drafts.csswg.org/css-position-4/ is no longer 404.

**Comment by plinss** [comment]
Also, the 'Last-Revised' header hasn't been served since we started proxying the github.io drafts, so not sure where you're even seeing that

**Comment by sideshowbarker** [comment]
> Also, the 'Last-Revised' header hasn't been served since we started proxying the github.io drafts, so not sure where you're even seeing that

I’m still seeing it right now, just seconds ago, from running `curl` request:

```
$ date
Mon May  8 14:07:32 JST 2023
$ curl -I https://drafts.csswg.org/css-animations-2/
HTTP/1.1 200 OK
Date: Mon, 08 May 2023 05:07:33 GMT
Server: Apache/2.4.10 (Debian)
Last-Modified: Mon, 8 May 2023 04:40:38 GMT
Last-Revised: Sat, 22 Apr 2023 03:27:36 GMT
```

**Comment by plinss** [comment]
And from the US:
![image](https://user-images.githubusercontent.com/2699689/236739544-74e41761-f7da-4073-b906-013089412877.png)

You must have a caching proxy inline somewhere.

**Comment by plinss** [comment]
Or... your DNS is way out of date and somehow you're seeing the old server directly and not the new proxy

**Comment by sideshowbarker** [comment]
> You must have a caching proxy inline somewhere.
> Or... your DNS is way out of date and somehow you're seeing the old server directly and not the new proxy

OK, thanks much — I’m not aware of any relevant caching proxy anywhere, so I guess the only thing it could be is my DNS being out of date. I wasn’t aware there was an old server vs the new proxy, but I’m guessing if there’s an old server that’s not up to date, then the behavior I’m seeing is because I’ve still been getting responses from that old server.

I’ll see what I can do about troubleshooting my DNS — but in the meantime, I guess I should go ahead and close this, since it seeming clear now that has to just be a local problem.

**Comment by sideshowbarker** [comment]
OK, for the record here, it seems I had been getting routed to 173.230.149.95 (which I assume must be the old server) but now I’m finally getting consistently routed to 45.79.94.155 (which I assume must be the correct server, the new proxy).

I have no idea how I “fixed” it — all I did was to run a few tools like dig, traceroute, and mtr.

I hope it was in fact just some weird local issue, and not something caused by some broader network problem that other people (e.g., other people in Japan where I’m connecting from) might also run into. Because if they did run into it, it likely wouldn’t be obvious to them that they were seeing stale content.

Would it be possible to shut down the 173.230.149.95 server so that anybody else who might be still getting routed to it now would see hard 404s rather than stale content?

**Comment by tabatkins** [comment]
> it just puts back the unlevelled versions (which I left broken under the assumption someone would complain if it was an issue; I'll take this as just such a complaint).

Ah actually mea culpa; I'd left those files ungenerated because I'd assumed that the drafts server was still doing the redirecting that it used to, and we didn't need them here. (That is, I thought only `https://w3c.github.io/csswg-drafts/css-backgrounds/` would 404, but `https://drafts.csswg.org/css-backgrounds/` would be fine.) Seems like it's not, so we do indeed need to continue generating and serving the redirects ourselves. Fixing now.

**Comment by tabatkins** [comment]
Fixed by <https://github.com/w3c/csswg-drafts/commit/70fe6743adb2acc684d1aa487a9fd67ce4939b7c>
