### ISSUE TITLE
[cssom][css-variables] Whitespaces in serialization of custom property value and value with variable reference

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#881]
It is currently not clear how whitespaces should be handled in serialization of value of custom property and value of normal property but with varible reference.

For example, if I have the following style rule:
```css
div {
  --a:␣␣x␣␣y␣␣;
  display:␣␣var(--x)␣␣var(--y)␣␣;
}
```
what should be the result of `rule.style.getPropertyValue('--a')` and `rule.style.display`?

Currently, browsers don't agree on the same behavior.

Gecko preserves all whitespaces for both cases, so
* `rule.style.getPropertyValue('--a')` -> `␣␣x␣␣y␣␣`
* `rule.style.display` -> `␣␣var(--x)␣␣var(--y)␣␣`

Blink strips preceding whitespaces for normal property value, and collapses continuous whitespaces into one, so:
* `rule.style.getPropertyValue('--a')` -> `␣x␣y␣`
* `rule.style.display` -> `var(--x)␣var(--y)␣`

Since they are both sequences of tokens, Blink's behavior looks inconsistent to itself. Given that we want to preserve whitespaces for value of custom properties, I suggest we state explicitly that preceding whitespaces of property value with variable reference should be preserved as well.

As of whether continuous whitespaces should be collapsed into one, I don't have strong opinion on. It seems to me collapsing them would add an unnecessary pass for us, I tend to not do that. But I'm open to collapsing behavior or making it unspecified explicitly.

Also note that, the serialization algoritm for "serialize a CSS declaration" also needs to adjust accordingly, because it currently unconditionally appends a whitespace after colon, and prepends a whitespace before `!important`, which would make `cssText` not idempotent when value includes preceding or trailing whitespaces. I propose that we don't add whitespaces if the value is a sequence of tokens.

**Comment by upsuper** [comment]
cc @tabatkins @zcorpan @therealglazou

**Comment by upsuper** [comment]
cc @heycam

**Comment by upsuper** [comment]
Alternatively, to make the output nice, we can say in "serialize a CSS declaration" that, if the value doesn't have any preceding whitespace, than add a whitespace after colon, and if the value doesn't have any trailing whitespace, add a whitespace before "!important".

That would change the value, but `cssText` itself would be idempotent.

**Comment by zcorpan** [comment]
Or never output spaces for custom properties, so the value doesn't change and `cssText` is idempotent.

**Comment by atanassov** [comment]
CSSWG f2f Seattle - resolved to keep syntax as is and for implementations to match the current impl of Firefox. 
@tabatkins to make editorial change to variables spec showing this as an explicit example.

**Comment by upsuper** [comment]
> Or never output spaces for custom properties, so the value doesn't change and `cssText` is idempotent.

Also value with variable reference, which is a sequence of tokens as well, just like value of custom properties.

**Comment by tabatkins** [comment]
> As of whether continuous whitespaces should be collapsed into one, I don't have strong opinion on. It seems to me collapsing them would add an unnecessary pass for us, I tend to not do that. But I'm open to collapsing behavior or making it unspecified explicitly.

The Syntax spec elides information of how many and what types of whitespace characters were parsed; it just emits a whitespace token to represent a run of whitespace. Like with comments, you're allowed to remember exactly what the whitespace was, but you're not required to; you can serialize whitespace tokens out as a single space if you want.

**Comment by upsuper** [comment]
I believe the resolution in #774 overrides the resolution here, and I also agree that is better.
