### ISSUE TITLE
[css-page-4] https://w3c.github.io/csswg-drafts/css-page-4/ URL yields a 404

### ISSUE THREAD

**Issue by tidoust** [w3c/csswg-drafts#8824]
Following changes made to address #8798, I note that https://w3c.github.io/csswg-drafts/css-page-4/ does not redirect to https://drafts.csswg.org/css-page-4/ and instead returns a 404. I suspect that is because the spec needs to be re-generated because it currently exists under [`Overview.html`](https://w3c.github.io/csswg-drafts/css-page-4/Overview.html) instead of `index.html` and GitHub Pages do not understand `Overview.html`.

(I don't know whether the `w3c.github.io` URL is used anywhere to reference that spec. I suspect MDN only references Level 3 for instance)

**Comment by Loirooriol** [comment]
@tabatkins Seems a problem of 8523f13a005f7213c39200e24944f8549e9e5227

**Comment by Loirooriol** [comment]
Sure, but it wasn't the only affected spec, and I will leave this work for the editors.

**Comment by tabatkins** [comment]
Ah, k. Well, I went ahead and fixed Page 4. ^_^
