### ISSUE TITLE
[css-color] interpolating between color spaces

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#883]
How should a transition between "blue" and "color(display-p3 1 0 0)" work?

My current thought is to work out which of the endpoints is in the biggest color space, convert the endpoint in the smaller space to the bigger space (which won't always be 100% accurate), then apply the interpolation.

However:
- how to decide which is the bigger space?
- how to convert from one space to another?

... both in a way that is interoperable between all browsers.

**Comment by svgeesus** [comment]
You are right that the endpoints need to be converted. However, the concept of "biggest" is poorly defined (for example the P3 and AdobeRGB gamuts are roughly the same size, and neither fully encloses the other). Instead, the Working Colorspace is what they are converted to.  The defaut value of that space is sRGB, obviously, but other options will include P3, Rec2020, and Lab/LCH.

**Comment by grorg** [comment]
Note that this affects gradients as well, not just transitions.

**Comment by svgeesus** [comment]
> How should a transition between "blue" and "color(display-p3 1 0 0)" work?

Like this

![image](https://user-images.githubusercontent.com/2506926/99075676-8f1f2c00-25c2-11eb-9178-2f595eafc8b7.png)

[live example](https://colorjs.io/notebook/?storage=https%3A%2F%2Fgist.github.com%2Fsvgeesus%2F59ff507fc2d686a97323cb81cd1d699b)

The "biggest space" is lab, and all colors can be converted to and from that exactly.

**Comment by svgeesus** [comment]
Now documented in the [CSS Color 5 section on interpolating colors](https://drafts.csswg.org/css-color-5/#interpolation)
