### ISSUE TITLE
[css-inline] need to define interaction of initial-letter and text-align other than start

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#884]
Per @frivoal in today's face-to-face discussion, we should make sure the spec produces sensible (?!?) results for the interaction of <code>initial-letter</code> with <code>text-align</code> values other than <code>start</code>

**Comment by frivoal** [comment]
> we should make sure the spec produces sensible (?!?) results for the interaction of initial-letter with text-align values other than start

With `text-align: justify` and `text-align: justify-all`, clarifying that there is no justification opportunity between the initial letter and the adjacent text should be
enough.

For `end` and `center`, this is much more confusing, and it isn't clear there is an actual use case, so we should probably pick the simplest thing to implement.

We could leave the initial letter flush against the start edge anyway, which would be simple, and have the advantage of making sure that no subsequent line goes further towards the start than the initial letter, which may be desirable. This could however leave a large gap between the initial letter and the adjacent text in some cases. This seems especially bad in cases when `initial-letter-wrap` is set to `first` with the first line kerned into the initial letter area.

Moving the initial letter towards the end edge by the largest distance that does not cause overlap with the adjacent text would reduce this problem, but not eliminate it. I do not think it is worth the extra complexity.

One case where it could work without causing problems is if the `<integer>` value of the `initial-letter` declaration is `1`. I that case, There is no particular difficulty in respecting `center` or `end` alignments.

**Comment by upsuper** [comment]
> With `text-align: justify` and `text-align: justify-all`, clarifying that there is no justification opportunity between the initial letter and the adjacent text should be enough.

Should there be justification opportunity between the initial letter and the rest if one or both of them are CJK characters?

> For `end` and `center`, this is much more confusing, and it isn't clear there is an actual use case, so we should probably pick the simplest thing to implement.

Or explicitly leave it unspecified?

**Comment by frivoal** [comment]
> Should there be justification opportunity between the initial letter and the rest if one or both of them are CJK characters?

I don't think so. Especially if initial-letter-wrap is grid, I think it's pretty important that there isn't a justification opportunity. In the other cases, I am less sure, but I wouldn't want one either. You think there should be one?

> > For end and center, this is much more confusing, and it isn't clear there is an actual use case, so we should probably pick the simplest thing to implement.

> Or explicitly leave it unspecified?

That works too, I suppose.

**Comment by upsuper** [comment]
> I don't think so. Especially if initial-letter-wrap is grid, I think it's pretty important that there isn't a justification opportunity. In the other cases, I am less sure, but I wouldn't want one either. You think there should be one?

I have no idea. Probably you're right that it is better no justification opportunity presents there. I think we generally want a flush alignment for all lines beside initial letter in CJK. If we need space there, it should be aligned to grid, rather than having justification opportunity.

**Comment by frivoal** [comment]
> If we need space there, it should be aligned to grid, rather than having justification opportunity.

Agreed. That that can be done with `initial-letter-wrap: grid`.

**Comment by fantasai** [comment]
OK, so the proposal is

- For raised initials (sink = 1), alignment is honored as usual, there are no special considerations.
- For sunk initials, the initial letter box’s start margin edge is anchored to the start edge of the line (after first-line 'text-indent'), and alignment happens afterwards in the remaining space on the line.
- We specify that initial letter suppresses any justification opportunity between the initial letter and subsequent text.
