### ISSUE TITLE
[css-color-5] relative `color()` function isn't immediately clear

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8841]
As far as I can tell there isn't any issue in the specification, it just isn't easy to to immediately understand `color()` in terms of relative color syntax.

-----

different naming :

- in css-color-4 : [`Specifying Predefined Colors: the color() function`](https://www.w3.org/TR/css-color-4/#color-function)
- in css-color-5 : [`Specifying Custom Color Spaces: the color() Function`](https://drafts.csswg.org/css-color-5/#color-function)

At first this seems as if it is a different aspect of `color()`, and it isn't clear that relative color syntax for **predefined color spaces** is also defined within this section.

------

missing/confusing examples :

Examples 28/29 focus on gamut mapping, valid values, ... 
- https://drafts.csswg.org/css-color-5/#ex-2020-oog-p3
- https://drafts.csswg.org/css-color-5/#ex-profoto-bad

But they follow the section that explains relative color syntax for the `color()` function.

There is no example of relative color syntax for the `color()` function.

-----

Is it possible that there was some restructuring done here at some point and that not everything landed exactly where/how it was intended?

**Comment by svgeesus** [comment]
Yeah that whole section starting

> A color which is either an [invalid color](https://drafts.csswg.org/css-color-4/#invalid-color) or an [out of gamut](https://drafts.csswg.org/css-color-4/#out-of-gamut) color can’t be displayed.

is exactly the [same as in CSS Color 4](https://drafts.csswg.org/css-color-4/#color-function), looks like it was copied over with a view to changing it maybe, but it doesn't belong there.

**Comment by svgeesus** [comment]
@romainmenke could you take a look at the now-renamed [Specifying Predefined and Custom Color Spaces: the `color()` Function ](https://drafts.csswg.org/css-color-5/#color-function) to check your issues have been addressed?

The confusing duplicate section has been deleted, and an example added.

**Comment by romainmenke** [comment]
Much clearer, thank you so much.
This is good to close for me 🙇
