### ISSUE TITLE
[scroll-animations-1] Should `none` be part of the list in scroll/view-timeline-name?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#8843]
The `scroll-timeline-name` and `view-timeline-name` properties have this grammar: `none | <custom-ident>#`. That is fine in isolation, but  it's inconsistent with `animation-name`, which has `[ none | <custom-ident> ]#`, and that made me wonder if it's intentional.

If it _is_ intentional, then feel free to close this.

@fantasai

**Comment by ydaniv** [comment]
I think it's intentional since these are timeline declarations that can be matched by definitions of `animation-timeline`'s and are matched by name, and not by position in the list. So it's either a list of names or `none`.

**Comment by tabatkins** [comment]
Yeah, `animation-name`'s use of `none` as any item in the list (which just "turns off" that entry in the list) is pretty odd actually.

**Comment by andruud** [comment]
OK, in that case, how am I supposed to interpret the grammar of `scroll-timeline`:

>`[ <'scroll-timeline-name'> [ <'scroll-timeline-axis'> || <'scroll-timeline-attachment'> ]? ]#`

I'm aware of css-values-4:

> `These types do not include CSS-wide keywords such as inherit, and also do not include any top-level comma-separated-list multiplier (i.e. if a property named pairing is defined as [ <custom-ident> <integer>? ]#, then <'pairing'> is equivalent to [ <custom-ident> <integer>? ], not [ <custom-ident> <integer>? ]#).`

But `scroll-timeline-name` doesn't have top-level comma-separated-list multipliers.

Even if you ignore that, the grammar would suggest that `scroll-timeline: none, none, none` is allowed, even though it's not allowed by the longhand?

> Yeah, animation-name's use of none as any item in the list (which just "turns off" that entry in the list) is pretty odd actually.

Yet if `scroll-timeline` worked like that it seems to answer all my questions, so maybe not that odd. :-)

**Comment by fantasai** [comment]
Hm, yes, it does seem we have a problem. :) I think the two options are:

- Allow `none` as an alternative to `<custom-ident>` in `*-timeline-name`, essentially disables that entry in the coordinated properly list.
- Rework the grammars explicitly so that both `*-timeline-name` and the `*-timeline` shorthand have `none | <whatever>`.

**Comment by ydaniv** [comment]
ah, for coordinating between longhand lists, I see.
So the options mean either keep allowing `none` for `-name` for disabling a single entry, or only allowing it as the entire value for disabling all timelines of that type, right?
Although it won't be necessary in most cases, I guess the first option allows more flexibility, and it may seem strange to developers that they have to remove an entry from all properties to disable it.

**Comment by tabatkins** [comment]
Yeah, I suppose following the animation-name model works. It's weird and I don't particularly like it, but it works slightly better with a few of our abstractions.
