### ISSUE TITLE
[css-position-4] redundant document argument for top layer manipulation algorithms

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#8849]
https://drafts.csswg.org/css-position-4/#top-manip

This sections contains algorithms like "add an element to the top layer, given a Document doc and an Element el". The call sites for these in https://github.com/whatwg/fullscreen/pull/223 and https://github.com/whatwg/html/pull/9093 always pass in the element's node document as the first argument. In HTML there is a *document* variable handy so the invocation looks OK, but in Fullscreen we'll have invocations like this:

> Request removal from the top layer given *element*'s node document and *element*

By having only element as the argument, the call sites will be simpler, and there's no question about whether the document can be some other document.

cc @josepharhar @mfreed7 @tabatkins @nt1m @annevk

**Comment by josepharhar** [comment]
I am ok with this. Anne pointed this out in the HTML PR here: https://github.com/whatwg/html/pull/9093#discussion_r1192056090
