### ISSUE TITLE
[css-scroll-snap-2] Why is scroll-start measured against the width/height of the scrollport?

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#8854]
[css-scroll-snap-2 scroll-start](https://drafts.csswg.org/css-scroll-snap-2/#scroll-start) says that end is equivalent to 100% and that values corresponding to a length greater than the width/height of the scrollport are clamped to the width/height implying that 100% would be the width of the scrollport. This means that `end` would not be the end of the scroll but one page over / down. I think this is probably not the intention, @argyleink ?

**Comment by flackr** [comment]
I expect the values should be measured against / clamped to the scroll range (i.e. scroll length - scroll port size).

**Comment by flackr** [comment]
@DavMila seems like this may be obsolete if we are going for only having `scroll-start-target`?

**Comment by DavMila** [comment]
> @DavMila seems like this may be obsolete if we are going for only having `scroll-start-target`?

Yes, I believe this is obsolete. I'll mark this issue closed.
