### ISSUE TITLE
[css-transitions-2] Put discrete transitions behind new syntax for compatibility

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#8857]
# Problem

@josepharhar implemented #4441 and discovered some compat issues. While it seems to be true that developers don't set up transitions on properties that only have discrete values, there are many cases where developers have transitions set up on properties which sometimes have discrete values. E.g. going to/from `auto` currently results in a discrete interpolation. This means that changes to/from auto currently do not start transitions but with transitions of discrete properties they now do.

Note: We want to support smooth interpolation to/from auto (See #626). If/when we add this, if it just starts intepolating to/from auto and thus starting transitions we would run into the same set of compat issues.

## Example issues

@josepharhar looked through 30 affected sites and found 3 regressions:
[stackoverflow.com](http://stackoverflow.com/)
With discrete transitions for width and height on page load the orange text doesn’t show up for a frame or two:
![image3](https://github.com/w3c/csswg-drafts/assets/366761/3351b136-716d-4787-873c-f3513ccf7e16)

[hpe.com](http://hpe.com/)
With discrete transitions for max-height, the accordions at the bottom don’t slide closed but instead suddenly close with a delay after clicking:
![image1](https://github.com/w3c/csswg-drafts/assets/366761/86497992-9c48-411f-8a4b-128006d2089b)

[fender.com](http://fender.com/)
With discrete transitions for top, the menu bar at the top of the page doesn’t stick to the top of the page but instead teleports to the top after a delay when scrolling:
![image2](https://github.com/w3c/csswg-drafts/assets/366761/fb2362e4-56e2-4220-ad4b-1ea2ca99e9ca)

# Solutions

From what we have seen so far, the compat issues are only for properties which currently sometimes have interpolable transitions (e.g. length properties which are interpolable when specified but not when `auto`). This means that technically the only transitions which need to be avoided may be these. However, it seems ergonomically awkward to make the developer need to think about whether the property is sometimes interpolable and sometimes not. As such, I think we should come up with a new syntax for opting in to discrete transitions. A side benefit, is that explicitly specifying discrete also provides a way to opt in to discrete transitions on `all` without needing a keyword like [discrete-too](https://github.com/w3c/csswg-drafts/issues/4441#issuecomment-545190019).

For comparison, the code necessary to animate out a dialog (animating display and overlay discretely, and opacity) is shown.

Some options (vote for all that you think would be reasonable):

1. 😄 Add an optional `discrete` keyword before each `<single-transition-property>` in the [transition-property](https://drafts.csswg.org/css-transitions-1/#transition-property-property) list. `'<single-transition-property>' = discrete? all | <custom-ident>`. With this change you would need to add discrete before each property you wanted to start discrete transitions on, e.g. `transition: discrete display 0.2s, discrete overlay 0.2s, opacity 0.2s`
2. 🎉 Similar to 1, but make a new longhand `transition-property-mode` which is an auto-extended list. This means that you can specify per property whether it should transition discretely or you can specify `transition-property-mode: discrete` and it will auto-extend and transition all specified properties discretely. e.g. `transition: display 0.2s, overlay 0.2s, opacity 0.2s; transition-property-mode: discrete;` (the discrete is a list that can be specified per property but is auto-extended).
3. ❤️ Add a `discrete` keyword optional keyword which applies to the whole transition-property-list. `transition-property = none | discrete? <single-transition-property>#`. With this, you would opt in to all specified properties transitioning discretely but wouldn't be able to choose per property. e.g. `transition: discrete display 0.2s, overlay 0.2s, opacity 0.2s` (the discrete applies to the entire list in this case)
4. 🚀 Add a `transition-discrete` property specifying which css properties should allow discrete transitions. E.g. `transition-discrete: all;` all properties, `transition-discrete: none; /* initial value */`, `transition-discrete: border-style outline-style text-decoration-style;`. This is similar to 3 in that it decouples the discrete properties from the transitions list which may or may not be desirable, but unlike 3 allows choosing specific lists of properties. See https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1572569359

As mentioned above, if we eventually support non-discrete animation to/from `auto`, we will have the same compat issues if they work with the existing syntax. As such, we should consider whether any of the above syntaxes (or some other not-yet presented option) could be extended for this auto case. E.g. maybe `transition-property-mode: used-value`?

**Comment by mfreed7** [comment]
Thanks for raising the issue! I voted for <span>#</span>2, but wanted to clarify one thing. With option 2, **both** of these would work, and would be equivalent, correct?

```
.version1 {
  transition: display 0.2s, overlay 0.2s, opacity 0.2s;
  transition-property-mode: discrete;
}
.version2 {
  transition: discrete display 0.2s, discrete overlay 0.2s, opacity 0.2s;
}
```

**Comment by flackr** [comment]
> With option 2, both of these would work, and would be equivalent, correct?

Both would work, and in practice they're equivalent (because opacity is never discrete) but syntactically they're different.

They would expand to something like this:
```css
.version1 {
  transition-property-name: display, overlay, opacity;
  transition-property-duration: 0.2s 0.2s 0.2s;
  transition-property-mode: discrete; /* auto-extends discrete */
}
.version2 {
  transition-property-name: display, overlay, opacity;
  transition-property-mode: discrete, discrete, continuous;
  transition-property-duration: 0.2s 0.2s 0.2s;
}
```

Happy to here other options for `continuous`, e.g. `interpolable`, `auto`, `normal`.

**Comment by SebastianZ** [comment]
What happens for interpolatable values? Would the transition also be turned into a discrete one or would the keyword be ignored in that case?

Why should `transition-property` be turned into a shorthand for that? Wouldn't a `transition-mode` property as another longhand for the `transition` shorthand be better? `transition-property` would still be the controlling property for it, of course.

Also, authors should be encouraged to specify the names for the properties they want to transition instead falling back to `all`. Therefore, also the direct combination of both keywords should be discouraged.

Sebastian

**Comment by tabatkins** [comment]
> What happens for interpolatable values? 

They'd function as normal. The `discrete` keyword just enables discrete transitions on the property *as well*.

(If you want "discrete" transitions on interpolable values, provide a linear() timing function yourself.)

**Comment by flackr** [comment]
One question about option 2, currently it looks like the [other property lists are repeated rather than last-value extended when the list is too short](https://drafts.csswg.org/css-transitions/#transition-duration-property:~:text=the%20user%20agent%20must%20calculate%20its%20used%20value%20by%20repeating%20the%20list%20of%20values%20until%20there%20are%20enough). Seems like naively we'd just do the same for `transition-mode`. I don't think this is a deal breaker as the common case will be specifying only a single value or a list for each transition.

**Comment by flackr** [comment]
Proposed resolution: Go with option 2 above, adding a transition longhand for specifying whether the transition should allow discrete interpolation. This will follow the [same convention as the other transition longhands where the list is repeated if shorter than the transition-property list](https://drafts.csswg.org/css-transitions/#transition-duration-property:~:text=the%20user%20agent%20must%20calculate%20its%20used%20value%20by%20repeating%20the%20list%20of%20values%20until%20there%20are%20enough).

Given this is in reference to the [animation-type](https://www.w3.org/TR/web-animations/#animation-type)) it's probably worth sharing some of the terminology. Possible property names:
* `transition-mode`
* `transition-type`
* `transition-animation-type`

Possible property values:
* For referring to interpolable transitions we could use `normal` (as it's the pre-existing mode), or `interpolable` explaining that it is anything animatable and not discrete.
* For referring to including discrete transitions, we could say `discrete` to refer to the specific animation type, or `animatable` as the intention would be that we animate anything that is animatable.

I think my preference would be `transition-type: <normal | animatable>#`. Using animatable rather than discrete because it matches exactly the spec terminology for what will be transitioned - anything that can be animated.

**Comment by fantasai** [comment]
Alternative naming, which I think is maybe a bit more clear?

```
transition-discrete: auto | all | none
```

where

- **all** allows discrete values to animate for all properties
- **auto** allows discrete animation only for properties which only have discrete values (to avoid the compat issue)
- **none** disables transitions for discrete values

**Comment by josepharhar** [comment]
It sounds like we have these potential property names:
1. 😄 `transition-mode`
2. 🎉 `transition-type`
3. ❤️ `transition-animation-type`
4. 🚀 `transition-discrete`

- @fantasai mentioned that "mode" and "type" are vague
- @smfr mentioned that "discrete" is hard for non-native english speakers
- The property values we choose might impose a particular property name and vice-versa

Property values:
1. `normal | discrete`
2. `normal | animatable`
3. `interpolable | discrete`
4. `interpolable | animatable`
5. `auto | all | none`

- @flackr mentioned that `normal | animatable` would be good because using animatable rather than discrete matches exactly the spec terminology for what will be transitioned - anything that can be animated
- Assuming that these property values will appear in a shorthand, I like `discrete` since I think it makes the following easier to understand imo: `transition: discrete display 0.2s, interpolable color 0.5s;`
- If we allow in the future for smooth interpolations between `auto` and `123px` for properties like `height`, would we want to add a new value? Or reuse the opt-in value `discrete`/`animatable`/`all`?

**Comment by flackr** [comment]
> Assuming that these property values will appear in a shorthand, I like discrete since I think it makes the following easier to understand imo: transition: discrete display 0.2s, interpolable color 0.5s;

I can definitely see the value in `discrete` for being easy to type and referring to the changed behavior.

> If we allow in the future for smooth interpolations between auto and 123px for properties like height, would we want to add a new value? Or reuse the opt-in value discrete/animatable/all?

This seems to be a bit of a compat box we have painted ourselves into. If we support smooth interpolations for these it would have to be a new value for this property or a new property to suggest something like that we are transitioning between *used* values.

**Comment by nt1m** [comment]
Does this apply to animations? if not, then `transition-animation-type` is potentially a bit misleading.

**Comment by flackr** [comment]
> Does this apply to animations? if not, then `transition-animation-type` is potentially a bit misleading.

No. This is setting whether discrete is a supported [animation type](https://www.w3.org/TR/web-animations-1/#animation-type) for transitions. It is always supported for css and web animations. If you think that animation type is a poor name we could consider changing that though that touches many specs - but it is admittedly not currently a web developer exposed term.

> The animation-affected properties are defined in the keyframes themselves, not separately in some animation-property, so they are clearly different concepts.

I'm not sure I understand this. There are many `animation-` properties that can be defined in both the element style itself and in the keyframes, e.g. look at [animation-timing-function](https://www.w3.org/TR/css-animations-1/#animation-timing-function). Though, as I mention above the behavior for *animations* is already that discrete properties can animate - so this is only a transition affecting property.

**Comment by flackr** [comment]
Based on the poll in https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1591335579 and the various discussions about terms for the value the proposed resolution is:

Add the longhand property name `transition-animation-type` with the list of values `normal` and `animatable` (associated with the list of transitions), with an initial value of `normal` for compatibility.

Adjustment to the transitionable behavior defined at https://www.w3.org/TR/css-transitions-1/#transitionable:
`normal`: property values are transitionable if they have an [animation type](https://drafts.csswg.org/web-animations-1/#animation-type) that is neither [not animatable](https://drafts.csswg.org/web-animations-1/#not-animatable) nor [discrete](https://drafts.csswg.org/web-animations-1/#discrete). (Current legacy behavior)
`animatable`: property values are transitionable if they have an [animation type](https://drafts.csswg.org/web-animations-1/#animation-type) that is not [not animatable](https://drafts.csswg.org/web-animations-1/#not-animatable).

**Comment by chrishtr** [comment]
Agenda+ to choose the name @flackr suggests above.

**Comment by SebastianZ** [comment]
> Based on the poll in [#8857 (comment)](https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1591335579) and the various discussions about terms for the value the proposed resolution is:

I want to note that I didn't realize before that this was meant as a poll. My reaction was rather to express the good summary. 😊 I've changed my vote now. (And four people is a pretty small group to resolve on, so maybe some more people can express their opinion by voting.)

Sebastian

**Comment by flackr** [comment]
> And four people is a pretty small group to resolve on, so maybe some more people can express their opinion by voting.

Of course, I'd be happy to have more opinions. @josepharhar can you add `transition-interpolation` as an option?

**Comment by josepharhar** [comment]
Sure, I added transition-interpolation to my comment

**Comment by josepharhar** [comment]
Reminder that there is a proposed resolution here: https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1608287805
And a vote on the property name here: https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1591335579 (which also has some different ideas for value names)

We would also like to include this new value in the transition shorthand so you can write something like this:
```css
transition: animatable display 2s, color 3s;
```
which would be the same as:
```css
transition-property: display, color;
transition-animation-type: animatable, normal;
transition-duration: 2s, 3s;
```

I am hoping this will be discussed at the F2F next week if not at the meeting this wednesday.

**Comment by yisibl** [comment]
The specification ultimately chose to add `transition-behavior: allow-discrete`.
I would like to know if developers who set `* { transition-behavior: allow-discrete; }` will affect performance?
