### ISSUE TITLE
[css-transforms] Spec doesn't actually define perspective(0), and behavior is crazy anyway

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#886]
The definition of perspective(n) creates a 4x4 matrix with a component equal to 1/n. At 0 there's a 1/0 in the formula, so clearly this case isn't actually defined.

Edge and WebKit/Blink treat perspective(0) as perspective(inf) (that is, it's an identity transform). This is discontinuous with perspective(small).  Firefox rejects perspective(0) at the grammar level.

In transitions, Blink/WebKit currently transition by converting the perspective(0) into an identity matrix and interpolating that way, so you don't see a discontinuity.  This will change when impls match the new spec change (agreed in the f2f) that perspective() animates *as* a perspective() function; at that point it'll blow up to wacky-distortion and then reset to no distortion at all.

**Comment by tabatkins** [comment]
Resolutions from the f2f:

1. Follow the dang spec, which already specifies that perspective(0) is invalid.
2. Define that perspective()'s arg is clamped from below to a UA-specific limit (so that it's a closed range, which works properly with calc()).

**Comment by smfr** [comment]
Mozilla fixed a compat issue with allowing perspective(0) to be valid:
https://bugzilla.mozilla.org/show_bug.cgi?id=1009150

**Comment by smfr** [comment]
Dup of https://github.com/w3c/csswg-drafts/issues/413 ?

**Comment by smfr** [comment]
Resolved in https://github.com/w3c/csswg-drafts/issues/413
