### ISSUE TITLE
[css-syntax-3] Are the ranges for `non-ASCII ident code point` inclusive or exclusive?

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#8861]
@tabatkins The other ranges in this section are very explicit about being inclusive.

> lowercase letter
> A code point between U+0061 LATIN SMALL LETTER A (a) and U+007A LATIN SMALL LETTER Z (z) **inclusive**.

But `non-ASCII ident code point` doesn't mention this for all the `between X and Y` ranges.

https://drafts.csswg.org/css-syntax/#non-ascii-ident-code-point

Are these inclusive, or exclusive?

**Comment by tabatkins** [comment]
They are indeed also all inclusive.

**Comment by romainmenke** [comment]
Thank you for the very speedy reply :)

**Comment by tabatkins** [comment]
You're welcome; lucky for you I had just pulled up my laptop to make my grocery list for the week and had my inbox up as the current tab. ^_^
