### ISSUE TITLE
[css-anchor-positioning] Anchor positioning spec is hard to read

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#8869]
I'm finding the [Anchor Positioning Spec](https://drafts.csswg.org/css-anchor-position-1/) pretty hard to read and digest. I suggest the following improvements:

* Add a simple example in the Intro with a motivating use case (e.g. tooltip or whatever)
* Have separate sections on computing the anchor element  (default vs explicit) and the length computations
* Describe the anchor element selection constraints (e.g. about it being in the containing block hierarchy) in prose in the section on computing the anchor element.
* Clarify whether "automatic anchor positioning" is about automatic choosing of the anchor element, or automatic position values, or both.
* Give more examples, with pictures, for the length computations

**Comment by tabatkins** [comment]
Yeah, the spec has grown pretty organically as I've worked on it, and could use an editorial reorg. Your suggestions sound pretty good, I'll see what I can do.

**Comment by tabatkins** [comment]
Okay, did a decent reorg. Does it look better to you now?

**Comment by smfr** [comment]
Much better, thank you!

However, this note needs reworking:

> NOTE: The general rule captured by these conditions is that el must be fully laid out before query el is laid out. CSS’s rules about the layout order of stacking contexts give us assurances about this, and the list of conditions above exactly rephrases the stacking context rules into just what’s relevant for this purpose, ensuring there is no possibly circularity in anchor positioning.

Stacking contexts aren't relevant for layout; layout works in terms of formatting contexts. Stacking contexts are a paint-time thing.

**Comment by tabatkins** [comment]
Closing as having been rearranged. We might do more rearranging in the future, but the proximate complaint has been addressed. ^_^
