### ISSUE TITLE
[css-scrollbar] `scrollbar-width` animation type wrong?

### ISSUE THREAD

**Issue by lukewarlow** [w3c/csswg-drafts#8873]
According to the current specification the animation type of scrollbar-width is "by computed value" but this property only supports 3 keywords so I would expect it to be "discrete"?

**Comment by frivoal** [comment]
You're right, this is a leftover from when `scrollbar-width` took `<length>` values. It no longer does, so switching to `discrete` does make sense.

**Comment by frivoal** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/d72cc579a6074b3635ab4907cae31e57a27eb106

**Comment by lukewarlow** [comment]
What test case would be required for this?  I'd be happy to file a PR to the WPT repo for them.

https://github.com/web-platform-tests/wpt/pull/40124/files I've already added it as discrete to the animation property list (change from where I implemented parsing for it in WebKit)

If there's any other tests that need changing let me know

**Comment by frivoal** [comment]
I hadn't seen that test, thank you for the cross reference. That seems to cover it at least at the basic level. Some ref-test would be nice to have too, to confirm that it's doing the right thing not just at the API level, but also visually, but with scrollbars, that can be a little hard to construct.
