### ISSUE TITLE
[css-view-transitions-1] Move CSS View Transitions Level 1 to CR

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8878]
CSS View Transitions L1 is ready to transition to CR. The below is from the W3C template, please let me know if CSSWG requires any additional information.

# Document title, URLs, estimated publication date
CSS View Transitions Module Level 1.

# Abstract
This module defines the View Transition API, along with associated properties and pseudo-elements. View Transitions is a feature that allows developers to create animated transitions between visual states of the [document](https://dom.spec.whatwg.org/#concept-document).

# Status
Status is [here](https://www.w3.org/TR/css-view-transitions-1/#:~:text=on%20paper%2C%20etc.-,Status%20of%20this%20document,-This%20section%20describes).

# Changes
Changes since FPWD are documented [here](https://www.w3.org/TR/css-view-transitions-1/#changes).

# Requirements satisfied
Yes.

# Dependencies met (or not)
N/A

# Wide Review
Horizontal reviews are tracked [here](https://github.com/w3c/csswg-drafts/issues/8109). Currently I18n and security are pending. These reviews were filed for FPWD, no changes affecting these aspects have been made to the spec since. Moving the latest spec to CR can rely on these reviews.

The [Mozilla RFP](https://github.com/mozilla/standards-positions/issues/677) and [Webkit RFP](https://github.com/WebKit/standards-positions/issues/48) are additional links for cross-browser review.

# Issues addressed
List of issues addressed in this spec is [here](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-view-transitions-1).

# Formal Objections
None

# Implementation
Blink implementation is spec compliant except the resolution [here](https://github.com/w3c/csswg-drafts/issues/8505#issuecomment-1505587046), which is in progress. WPTs for the module are [here](https://wpt.fyi/results/css/css-view-transitions?label=master).

# Patent disclosures
None. The spec is listed in ipr [here](https://www.w3.org/groups/wg/css/ipr#:~:text=CSS%20View%20Transitions%20Module%20Level%201)

# Additional Notes
[css-view-transitions-2](https://github.com/w3c/csswg-drafts/issues?page=1&q=is%3Aissue+is%3Aopen+label%3Acss-view-transitions-2) tracks feature requests that we'd like to address in subsequent versions of this module, particularly support for cross-document same-origin navigations.

@noamr

**Comment by svgeesus** [comment]
> Currently I18n and security are pending. These reviews were filed for FPWD, no changes affecting these aspects have been made to the spec since.

That seems a rather bold claim, considering the [amount of changes](https://www.w3.org/TR/2023/WD-css-view-transitions-1-20230525/#changes-since-2022-11-24). I18n should be the ones deciding that these changes don't introduce any I18n issues, not us.

(I agree that Security review is unlikely to produce a result, currently).

> Formal Objections

> N/A

say none, not N/A

> Implementation

> N/A

Either say none, or explain what the current level of implementation is. Clearly _something_ is passing [these WPT](https://wpt.fyi/results/css/css-view-transitions?label=master&label=experimental&aligned) :)

> Patent disclosures

> N/A

Just say none, and link to https://www.w3.org/groups/wg/css/ipr

**Comment by khushalsagar** [comment]
Thanks for the quick review!

> That seems a rather bold claim, considering the [amount of changes](https://www.w3.org/TR/2023/WD-css-view-transitions-1-20230525/#changes-since-2022-11-24). I18n should be the ones deciding that these changes don't introduce any I18n issues, not us.

Sure, happy to have the I18n reviewers make that call. Given that this [review](https://github.com/w3c/i18n-request/issues/196) is still ongoing, is it reasonable to point to the change list instead of starting a new review?

**Comment by svgeesus** [comment]
> is it reasonable to point to the change list instead of starting a new review?

I would say so, yes.

**Comment by khushalsagar** [comment]
Changes since the last discussion:

- All horizontal reviews except security are closed: https://github.com/w3c/csswg-drafts/issues/8109. There's been no response on the security review for more than 6 months.
- All inline issues in the spec have been resolved and edits made to the spec.
- @fantasai did a full review of the spec, all filed issues have been resolved and edits made into the spec. The [remaining](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+is%3Aopen+label%3Acss-view-transitions-1) open issues are editorial.
- An [Editor's draft for L2](https://drafts.csswg.org/css-view-transitions-2/) is WIP for cross-document View Transitions. The ViewTransition object defined in L1 has a [process old state captured](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-process-old-state-captured) callback used by the new algorithms in the L2 spec.

**Comment by khushalsagar** [comment]
All done here.
