### ISSUE TITLE
[geometry] Why does DOMQuad have readonly mutable points?

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#888]
DOMQuad's p1/p2/p3/p4 attributes are readonly, which means there's no setter.  However, the points themselves are DOMPoint, not DOMPointReadonly, so they're mutable.  This seems like a bizarre amalgam?  You *can* mutate the quad's points, you just can't reassign them.

We should either make DOMQuad fully mutable (removing the readonly annotations), or switch them to DOMPointReadonly, rename DOMQuad to DOMQuadReadonly, and if necessary, add a fully mutable DOMQuad as well.

**Comment by fantasai** [comment]
@tabatkins Can you refile this in the correct repo? Thanks~

**Comment by tabatkins** [comment]
This issue was moved to w3c/fxtf-drafts#124
