### ISSUE TITLE
[css-animations] Proposal: Add a way to make the animation timing function apply to the whole animation

### ISSUE THREAD

**Issue by denk0403** [w3c/csswg-drafts#8881]
Spec: [https://drafts.csswg.org/css-animations/#propdef-animation-timing-function](https://drafts.csswg.org/css-animations/#propdef-animation-timing-function)

> When specified in a keyframe, [animation-timing-function](https://drafts.csswg.org/css-animations/#propdef-animation-timing-function) defines the progression of the animation between the current keyframe and the next keyframe for the animating property in sorted keyframe selector order (which may be an implicit 100% keyframe).

According to the spec, the `animation-timing-function` specifies the easing function between each keyframe. However, it's occasionally useful to developers to specify an easing function over the whole animation[[1](https://stackoverflow.com/questions/50910797/can-i-make-the-animation-timing-function-affect-the-whole-animation-rather-than)][[2](https://stackoverflow.com/questions/4534786/is-there-a-way-for-animation-timing-function-to-apply-to-the-entire-animation-in)]. Currently, achieving something like this would require manually calculating progress percentages and the values to apply at those keyframes, which is very tedious. It would be nice if there was built-in support for achieving this effect.

To be honest, when I first started using CSS Animations, I thought the timing function was applied effect-wide, since it's common to specify just once on an `animation` in CSS. It makes me wonder, how many other people have this misconception as well.

### How this would work (example)
```css
.my-element {
  animation-name: move;
  animation-timing-function: linear(0 0%, 0.5 80%, 1 100%) full;
}

@keyframes move {
  from { translate: 0 0; }
  20% { translate: 100px 0; }
  to { translate: 300px 0; }
}
```
Easing functions already map "input progress values" to "output progress values". So in the example above, when the input progress of the easing function is 0.25 (25%), the expected output progress should be 40%. Therefore, if this easing function was applied to the whole animation rather than between keyframes, then at 25% through the animation, the expected computed styles should be those given by `@keyframes move` at 40% progress. In this case, the element would have a computed style of `translate: 150px 0;`

### Syntax
I'm very open to suggestions for syntax/naming, but my idea was to introduce a multi-keyword syntax to `animation-timing-function`. For instance, the new syntax could be something like:
```css
animation-timing-function: [ <easing-function> && <easing-mode>? ]#
```
where `<easing-mode>` is defined as:
```css
<easing-mode> = full | keyframe
```

Another idea is to introduce a new animation style property, called something like `animation-full-timing-function`, which works like `animation-timing-function`, but applies it throughout the whole animation. However, because it's not clear how it should interop with the existing behavior of `animation-timing-function`, `animation-timing-function` should become ignored if `animation-full-timing-function` is present.

**Comment by birtles** [comment]
Yes, this is a real gotcha with CSS Animations. Web Animations already has this feature (you can specify `easing` on either a keyframe or on the animation effect as a whole) so it should just be a matter of mapping the CSS syntax onto the Web Animations effect-level easing. I believe @graouts also had a suggestion for the syntax for this in the past?

**Comment by denk0403** [comment]
Oh interesting, I assumed that specifying `easing` on the animation as a whole had the same behavior as specifying the timing function on an animation in CSS, that is by default it applies the same `easing` to each keyframe. In that case, you are correct that this should simply be a matter of mapping the ability to CSS.

And since Web Animations has separate ways of applying an easing function on the whole animation and per keyframe, then it makes sense to me to copy that design in CSS, and introduce a new animation style property rather than extending the existing `animation-timing-function` syntax.

Does the Web Animations spec then also define the timing behavior when an easing function is present on both the animation as a whole and individual keyframes, such as in the following example?
```js
elt.animate({
        backgroundColor: ["red", "blue"],
        easing: ["steps(5, end)"]
    }, {
        easing: "ease-in-out",
        duration: 5000,
    })
```
If so, can you point me where that is in the spec, if you know?

**Comment by birtles** [comment]
Yes, in Web Animations both types of easing can apply at once.

There is no particular section that says how they combine, but rather it falls out of the calculations in the model (i.e. the effect/iteration easing is used to calculate the [iteration progress](https://drafts.csswg.org/web-animations-1/#the-iteration-progress), and then that is used in [calculating the value of a keyframe effect](https://drafts.csswg.org/web-animations-1/#the-effect-value-of-a-keyframe-animation-effect) where any keyframe easing is used to calculate the _transformed distance_).

There is a little non-normative explanation of the difference in this section: https://drafts.csswg.org/web-animations-1/#processing-a-keyframes-argument

I believe there are also several web platform tests covering this behavior.

(This is also the reason Web Animations' `easing` property defaults to `"linear"` as opposed to `"ease"` like in CSS Transitions. By defaulting to `"linear"` the author can choose where they want to apply easing—to the effect or to the keyframes or to both—without having to reset any default easing.)

**Comment by denk0403** [comment]
Thanks for the pointer @birtles, I learned something new! And the terminology in the Web Animations spec suggests a few more potential names for a new CSS animation property:

- `animation-progress-function`
- `animation-effect-timing-function` (also suggested by @graouts)
- `animation-time-transform`

Personally, I'm starting to like the sound `animation-effect-timing-function`, because it hints that we could also introduce a new animation shorthand called `animation-effect` for specifying various effect-wide animation properties. 

Thus, in my initial example, this would look like:
```css
.my-element {
  animation-name: move;
  animation-effect-timing-function: linear(0 0%, 0.5 80%, 1 100%);
  animation-duration: 5s;
  /* or just... */
  animation-effect: move 5s linear(0 0%, 0.5 80%, 1 100%);
}

@keyframes move {
  from { translate: 0 0; }
  20% { translate: 100px 0; }
  to { translate: 300px 0; }
}
```
which would be semantically equivalent to the following Web Animations code:
```js
document.querySelector(".my-element").animate({
  translate: ["0 0", "100px 0", "300px 0"],
  offset: [0, 0.2, 1]
}, {
  easing: "linear(0 0%, 0.5 80%, 1 100%)",
  duration: 5000,
})
```

**Comment by birtles** [comment]
Thanks @denk0403! I don't have a particularly strong opinion about any this but I would leave towards the shorter naming. I also think having `animation-effect` be a shorthand that somewhat overlaps with `animation` could be confusing and maybe problematic (as it is, we're having a lot of trouble working out how to extend the `animation` shorthand in a way that is backwards compatible).

I liked the suggestion in #6982 of introducing `animation-easing` because it's short and because it offers a path to deprecating/phasing out `animation-timing-function` which I never liked because it's long and overly abstract.

Admittedly, that proposal also has problems when it comes to the `animation` shorthand since presumably we'd need to continue mapping timing functions to the `animation-timing-function` propertly (i.e. keyframe-level easing) unless we introduce new syntax for it.

**Comment by denk0403** [comment]
After some more thought, I don't think `animation-timing-function` should be deprecated in favor of something like `animation-easing`. They would serve different purposes, and there may be use cases for using them together like it's currently possible in Web Animations; it's the developer's discretion. Plus, I don't see an intuitive way one property can play both roles without overriding each other.

And although it's probably outside the scope of this discussion, to solve the shorthand syntax concerns, it could be nice if CSS shorthand properties supported something like [named parameters](https://en.wikipedia.org/wiki/Named_parameter) for dealing with ambiguities. Then if `animation-easing` was added, developers could still use it in shorthand syntax like so:
```css
animation: move 5s -easing=linear(0 0%, 0.5 80%, 1 100%);
```

**Comment by birtles** [comment]
> After some more thought, I don't think `animation-timing-function` should be deprecated in favor of something like `animation-easing`. They would serve different purposes, and there may be use cases for using them together like it's currently possible in Web Animations; it's the developer's discretion. Plus, I don't see an intuitive way one property can play both roles without overriding each other.

I thought @graouts covered that in #6982. Currently, when `animation-timing-function` is specified on a (pseudo-)element, it gets applied to all the keyframes in animations resolved against that element that don't specify `animation-timing-function` themselves.

`animation-easing`, when applied on a _(pseudo-)element_ would always become the effect-level (i.e. iteration) easing. When applied on a _keyframe_, it would be applied to they keyframe. i.e. there's no cascade from (pseudo-)element to keyframes.

**Comment by denk0403** [comment]
> i.e. there's no cascade from (pseudo-)element to keyframes.

Would this be an exception to the default behavior? Perhaps my mental model of `@keyframes` is wrong, but I've always viewed it as that properties do cascade to keyframes, with like successive keyframes getting higher specificities. For instance, the way I see it in the animation below, the background animates from red to blue because the implicit `from` keyframe gets `background-color: red` from the cascade, and tweening to the `to` keyframe effectively just does a CSS transition.
```css
.my-element {
    background-color: red;
    animation: colors 2s 3s;
}

@keyframes colors {
    to { background-color: blue; }
}
```

As a result, I would expect `animation-easing` to similarly cascade to each keyframe, but it would still only describe the easing of the whole animation. And consequently, modifying `animation-easing` within a keyframe would have the outcome of changing the effect-wide timing function for the duration of that keyframe, potentially enabling some very unique animations. Personally, if `animation-easing` did not cascade to keyframes, it would go against my intuition and feel like "another thing I have to remember".

**Comment by birtles** [comment]
I'm not sure, I think the cascading thing is a footgun. In my experience I see people writing:

```
div {
  animation: keyframes 1s ease-in;
}

@keyframes keyframes {
  50% { translate: 50px; }
  to { translate: 0px; }
}
```

and expecting the `ease-in` to apply to the whole thing. I've been on the receiving end of several bug reports along the lines of "it seem to slow down in the middle" due to this problem, some of the reports being from browser engineers themselves.

I think it's better to be explicit. If you specify `animation-easing` on a keyframe, it applies to that keyframe (and has no effect on the iteration easing). If you specify it on the element/animation, it applies to the whole animation iteration. That happens to be identical to Web Animations which reduces the barriers involved in moving between the two.

I don't want to sound too negative but I'm afraid that having `animation-effect` on keyframes affect the iteration easing would introduce cyclic dependencies (you need to apply the iteration easing to determine which keyframes to look up) and would require a fairly thorough redesign of the animation architecture to support the extra coupling between animation effect timing and keyframe effects, and between the timing model and animation model. Sorry for the stop energy there but I'm not sure that's a practical option.

**Comment by denk0403** [comment]
> I don't want to sound too negative but I'm afraid that having `animation-effect` on keyframes affect the iteration easing would introduce cyclic dependencies (you need to apply the iteration easing to determine which keyframes to look up) and would require a fairly thorough redesign of the animation architecture

While I still agree it's probably better to avoid introducing cyclic animation dependencies, I was reading the Scroll-driven Animations spec, and it seems like it also had to worry about the potential of ["layout cycles"](https://www.w3.org/TR/scroll-animations-1/#html-processing-model-event-loop). However, the spec's approach is to not re-sample the animation progress until the next update of the rendering, which sounds a bit like what I meant by allowing the current keyframe to "lag" behind the current iteration easing. So perhaps the aforementioned semantics are already somewhat possible with the current animation architecture, if that's what ends up getting chosen. It certainly provides food for thought.

**Comment by bramus** [comment]
I believe the request in this issue is covered by the resolution in https://github.com/w3c/csswg-drafts/issues/6982#issuecomment-2378038074.

> RESOLVED: add the 'animation-easing' as defined in the issue, and add a new initial value for animation-timing-function to something that computes to ease or linear depending on animation-easing

This aligns with the remark in https://github.com/w3c/csswg-drafts/issues/8881#issuecomment-1567698341 by the OP

> Personally I'm fine … if the new property deprecates animation-timing-function as suggested by @graouts in https://github.com/w3c/csswg-drafts/issues/6982

Hereby closing this issue.
