### ISSUE TITLE
[css-borders] a 5x5 `border-image-slice` option

### ISSUE THREAD

**Issue by jsnkuhn** [w3c/csswg-drafts#8883]
https://drafts.csswg.org/css-backgrounds/#border-image-slice

An option for a 5x5 `border-image-slice` to be used with `border-images-sources` that included centered design elements on their edges.

-----------------------------------------------

some example designs:

https://www.zelda.com/tears-of-the-kingdom/

![image](https://github.com/w3c/csswg-drafts/assets/1286791/461652f0-8104-4dfe-a5f2-7b261f6e92e4)

-------------------------------------------------------------------------------------------

https://ffvii-remake-intergrade.square-enix-games.com/en-us/

![image](https://github.com/w3c/csswg-drafts/assets/1286791/dc51bc7c-d510-4838-a666-3c10de29a76e)

Currently done with a bunch of presentational divs. This one seems even more like it would really need the 5x5 slice. or 3x3 for just the corners and the solid line plus a single ::after for the centered diamond.

-----------------------------------------------------------------------------------------

![image](https://github.com/w3c/csswg-drafts/assets/1286791/2f53f7d2-3ef5-4855-9556-4ba6b61c8d23)

**Comment by tabatkins** [comment]
While a centered bit in the border is probably the most common non-supported fancy border image, it's still pretty far down the long tail. Border image itself is already a relatively little-used property, and the syntax is pretty complex; adding more complexity in the form of two more slices per axis, along with appropriate controls for the new segments, would make it even less readable.

And ultimately, all the added complexity would be in the service of one use-case - putting things in the center of a side. If you wanted to put an image anywhere else, you'd still be unable to. I think the right answer here is to rely on the existing border-image, and Custom Paint to draw in the pattern you want at the exact location and size you want.

**Comment by jsnkuhn** [comment]
The best work around I've found for this so far is just making the side of the `border-image-source` with the centered element much longer than you'd normally think is necessary and then using `border-image-repeat: repeat;`. If the element never gets, for example, wider than the native width of the `border-image-source` it should stay centered and never need to repeat. This works well for SVG images where the "extra" size doesn't add too much to the file size but maybe not so good for raster images.

Also, ran into another example on a much larger site then the others so dropping it in:

https://abcnews.go.com/538 

![image](https://github.com/w3c/csswg-drafts/assets/1286791/9ed865e9-c686-4dbf-9b39-34553e43003c)

**Comment by SebastianZ** [comment]
Border slicing is already hard to understand for authors. And making it even more complex by adding a 5x5 syntax is not the right approach in my eyes.

I think we should rather make a step back, discuss the use cases for positioning border images separately from a possible syntax (maybe in #9714 or a separate issue) and then work out a possible syntax for them.

Therefore, I am going to close this issue. @jsnkuhn Please let me know if you disagree with that!

Sebastian
