### ISSUE TITLE
[css-view-transitions-1] Spec should not define web exposed keyframes

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#8887]
https://drafts.csswg.org/css-view-transitions/#ua-styles defines 2 web exposed keyframes, I don't think the spec should do this, regardless of the prefix.

**Comment by khushalsagar** [comment]
Thanks for bringing this up! Just a heads up, this was last discussed on https://github.com/w3c/csswg-drafts/issues/7560 and would have relevant context.

The main use-case where we've found this useful is additive animations. Authors create effects which need a CSS animation on top of the UA defined one. For example, the UA will add a `transform` animation to move an element from its location in the old DOM to the location in the new DOM which has the keyframe name : `-ua-view-transition-group-anim-target`, where target is the view-transition-name on the 2 DOM elements. If an author wants to do a filter animation on top, they can simply add it by doing the following in their CSS:

```css
::view-transition-group(target) {
   animation: -ua-view-transition-group-anim-target 1s, my-animation 1s;
}
```

The keyframe you linked above is static so its easy for authors to just write their own. But some UA keyframes generated for these elements are dynamic (depending on the size/position of the transitioning elements). And for those authors need to be able to refer the keyframe in their CSS for effects like these.

@argyleink @bramus FYI.

**Comment by khushalsagar** [comment]
@nt1m does the above address the concerns you raised?

**Comment by khushalsagar** [comment]
@annevk the comment thread on the issue itself touches upon some of the complexities associated with hiding this from authors:

- What to do if author stylesheet declares the same keyframe name, which one applies. Do we have to carry around the source of the keyframe and style rule which sets the `animation` property.
- How to hide this from script APIs that can read the keyframe name and keyframe values?

Interestingly, at the time we discussed https://github.com/w3c/csswg-drafts/issues/7560 we were only considering the awkwardness to handle the cases above. We didn't have a use-case where the author needed to refer to these keyframes in their stylesheet. As I mentioned in the comment above, now we've seen developers build transitions which need this to do additive animations.

Can you clarify the concerns with this approach?

**Comment by khushalsagar** [comment]
I'm closing this issue but please feel free to re-open if there is any more feedback or suggestions.
