### ISSUE TITLE
[css-view-transitions-2] Hold paint of old Document until new Document draws a frame

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8888]
During a cross-document navigation, there is a duration when the active Document associated with the browsing context (tab) has been swapped. But there is no visual content from the new Document because it hasn't produced a frame yet. The browser has a few options for what to paint during this duration:

1. Keep the last frame from the old Document onscreen. This has security implications if the navigation is cross-origin.
2. Clear the screen immediately and paint any UA defined color.
3. Display cached rendering of the new Document (if available). This is possible for session history navigations where the browser can cache the rendering of a Document when navigating away from it.

View Transitions require 1 since by design we want the new Document to define the transition animations. The new Document starts by displaying images captured from the old Document's last frame. This is done via the pseudo DOM defined [here](https://drafts.csswg.org/css-view-transitions-1/#setup-transition-pseudo-elements-algorithm). Until the new Document has produced a frame, the browser needs to paint the last frame from the old Document to avoid visual glitches.

There are also no security implications to this since View Transitions are limited to same-origin.

Proposed Resolution: During a cross-document View Transition, the browser must continue to paint the last frame from the old Document until the new Document produces its first frame.

The behavior for such navigations when there is no View Transition is left to the UA (same as current behaviour).

@smaug---- @noamr

**Comment by vmpstr** [comment]
What do existing browsers do in cross document navigations to slow pages?

Also, does CSS define any of these concepts like old documents disappearing and new ones appearing? I would've imagined this should go in the html?

**Comment by khushalsagar** [comment]
> What do existing browsers do in cross document navigations to slow pages?

Used https://foil-persistent-bookcase.glitch.me/page2.html for an example of navigation to a slow rendering page. When going to a new Document (same-origin navigation), all browsers are doing option 1 : "Keep the last frame from the old Document onscreen." When going back/forward, Chrome/Firefox do option 3: "Display cached rendering of the new Document" but Safari still does 1.

> Also, does CSS define any of these concepts like old documents disappearing and new ones appearing? I would've imagined this should go in the html?

Neither html nor CSS defines what should draw in the tab in the period between the navigation finishing and the new Document preparing its first frame. Since VT is standardizing cross-document transitions, makes sense for it to go in that spec but open to suggestions here.
