### ISSUE TITLE
[css-view-transitions-2] security/privacy considerations with cross-origin css

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#8889]
#8048 and linked feature suggest to expose certain information about the navigation (navigation type, previous/next URL) to CSS, e.g. in the form of media queries.

Some security concerns about it that should be discussed and resolved:
As a general rule we don't consider 3rd party CSS as "safe", it can already exfiltrate a lot of information and alter the behavior of the page. However, it is still handled differently than scripts, e.g. `style-src` and `script-src` are separate directives.

When exposing navigation type and previous/next URL to CSS, we give CSS direct observation into the cross-document world. 
The threat model: An existing 3p CSS would now be able to exfiltrate (e.g. by an invisible background image) information about the referrer of its host document.

We should resolve how much this should be a constraint and affect our design, if at all. If we decide that this is not a problem, great!

One potential mitigation would be to have some kind of HTML opt-in to make CSS "navigation aware", to avoid making these changes something that affects existing sites.

**Comment by khushalsagar** [comment]
The features which need navigation specific CSS can be done using script:

* Customize based on destination URL: The user navigates from a list to a details page. The transitioning element needs to be the list item whose details page is the navigation target. You can do that using the [`navigate`](https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent) event which provides you the destination URL.

   ```js
      navigation.addEventListener("navigate", (event) => {
          if (isUrlForItem1(event.destination.url)
             item1.style.viewTransitionName = "hero-image";
      });
   ```

   The same use-case applies when going back from the details page to the list. The new Document needs to know the source URL. Not sure if this is doable using the Navigation API but we can add that (same-origin only).

* Customize based on navigation type: Author doesn't want to do a View Transition for reload. You can do that using [`navigationType`](https://developer.mozilla.org/en-US/docs/Web/API/NavigateEvent/navigationType) on the `navigate` event.

The motivation for navigation specific CSS is to enable handling these use-cases declaratively. This was highlighted during the [TAG review](https://github.com/w3ctag/design-reviews/issues/748#:~:text=were%20our%20thoughts%3A-,We%20like%20that%20MPA%20transitions%20are%20declarative%2C%20and%20would%20love%20to%20see%20a%20declarative%20syntax%20for%20SPA%20transitions%20too,-%2C%20as%20right%20now). @LeaVerou @atanassov FYI.

So I think we should figure out how to securely allow navigation specific CSS. Just want to make it explicit, 3rd party JS is already assumed to have these capabilities and we're not trying to protect against that.

Other than the blanket html opt-in idea above, one other option is to limit navigation specific CSS to stylesheets which are same-origin. We already know the source of a stylesheet. If its fetched from a cross-origin link, then navigation specific CSS is ignored by default. Unless the author adds an opt-in, for example :

```html
<link rel="stylesheet" href="styles.css" navigation-css="enabled">
```

So its an html opt-in but lets the author decide which stylesheets are opted-in. In case some site is using a trusted cross-origin domain for stashing their resources.

**Comment by noamr** [comment]
Related issues: https://github.com/w3c/csswg-drafts/issues/5092 and https://github.com/w3c/csswg-drafts/issues/5136.
/cc @arturjank @mkwest

**Comment by arturjanc** [comment]
Will this feature respect the Referrer Policy (specifically, the current default value of `strict-origin-when-cross-origin`) and not expose the referring URL on cross-origin navigations unless a page relaxes its Referrer Policy?

If so, then my guess is that this is relatively low-risk* and might not need an explicit opt-in. If not, then this would be problematic -- and in that case even an opt-in might not be sufficient because this API would give the destination the ability to learn potentially sensitive information about the embedding page which we don't want to reveal.

[*] The reason this seems low risk is that any CSS that can use at-rules can also use selectors and has the ability to learn information about the structure of the page, attribute values, etc. Learning the origin of the referring page or the destination of a navigation sounds like a less scary capability than what's already possible, even if it technically exposes additional information.

**Comment by noamr** [comment]
> Will this feature respect the Referrer Policy (specifically, the current default value of `strict-origin-when-cross-origin`) and not expose the referring URL on cross-origin navigations unless a page relaxes its Referrer Policy?

Absolutely.

> 
> If so, then my guess is that this is relatively low-risk* and might not need an explicit opt-in. If not, then this would be problematic -- and in that case even an opt-in might not be sufficient because this API would give the destination the ability to learn potentially sensitive information about the embedding page which we don't want to reveal.
> 
> [*] The reason this seems low risk is that any CSS that can use at-rules can also use selectors and has the ability to learn information about the structure of the page, attribute values, etc. Learning the origin of the referring page or the destination of a navigation sounds like a less scary capability than what's already possible, even if it technically exposes additional information.

Great! I wasn't sure if it was more/less scary, but it seemed like "different" information that's usually not exposed to CSS.
