### ISSUE TITLE
[css-transforms-1] Define basis for percentage transform on patterns, gradients, clipPath

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#892]
http://www.w3.org/mid/9B0DDCB4-B480-471F-943A-C5ED00598DFA@adobe.com

During the FX meeting in Hamburg we resolved that percentage values for the 'transform' property should not be ignored. IIRC we did not resolve if percentage values are relative to:

* the user space of the referencing object
* the bounding box of the referencing object
* the size of the resource (pattern/gradient/clipPath size).

I would like to avoid to use the last item since we do not have a definition for the size of clipPath.

Relative to the bounding box seems more natural to me and would be consistent with percentage values for 'transform' on the object itself.

Here is an example:

```
<svg width="500" height="500">
<defs>
    <clipPath transform="translate(20%, 20%)" id="clipping">
        <rect width="20" height="20"/>
    </clipPath>
</defs>

<rect width="200" height="200" fill="green" clip-path="url(#clipping)">
</svg>
```
Going with the first two items of the list, should the clipPath be translated by
* (100px, 100px) or
* (40px, 40px)

**Comment by AmeliaBR** [comment]
I'm not sure what "no change" is supposed to mean.  There is no guidance on this question in either the transform spec or the SVG spec.

SVG 1.1 didn't have transformations on clipPath or mask, but it did have `patternTransform` and `gradientTransform`.  I would expect a transformation on a clip-path or mask to work the same way: as a transformation of the infinite canvas on which the effect is defined, after scaling it according to the size of the shape's bounding box or userSpace, but prior to compositing it with the shape.

However, that doesn't answer the question about percentages.  The SVG 1.1 syntax did not have percentages in transforms, and therefore they didn't need a reference *box*.  However, they did need a reference *origin*.

All the graphical effects do have a reference box (the box used for defining the scale of the effect, whether that was `objectBoundingBox` or `userSpaceOnUse`), albeit one that doesn't fit with `transform-box`.  

For gradients, we even have consistent implementations that *use* that reference box to define the transform origin for scales and rotations.  So if it's a userSpace gradient, the rotation is around the user-space origin.  If it's a bounding-box gradient, the rotation is around the top-left corner of the bounding box (after adjusting for any non-uniform scale transformation created by scaling the effect coordinate space to the bounding box).

For patterns, implementations aren't currently consistent with each other or the spec.  SVG spec bug discussion is here: https://github.com/w3c/svgwg/issues/293
I have a demo/test case here: https://codepen.io/AmeliaBR/details/woKBYp/

_____________________

All of this is in addition to the long-standing issue that we still do not have clear definitions of what `objectBoundingBox` and `userSpaceOnUse` mean when applied to a non-SVG element, or how they interact with reference boxes defined in the mask/clip/fill/stroke properties on the target elements.

**Comment by smfr** [comment]
https://www.w3.org/Graphics/SVG/WG/wiki/Proposals/Bounding_boxes

**Comment by smfr** [comment]
Still needs some thought and spec wording.

**Comment by dirkschulze** [comment]
Ok, looked at this again. Lets limit the issue in question to the `<pattern>` element.

The `<pattern>` element has the attributes `patternUnits`, `patternContentUnits` and `patternTransform`. All 3 attributes influence the coordinate system for drawings.

* `patternContentUnits ` modifies the coordinate space for the content of `<pattern>` (content of the tile)
* `patternUnits` specifies a coordinate space for the pattern tile itself. Namely the `width` and `height` attributes.
* `patternTransform` specifies the coordinate space for the pattern itself. Percentage values get resolved according to the reference box of the referencing element in the local coordinate space of the referencing element (a `<rect>` element for instance).

As a result, according to the current specification text, `patternUnits` do not contribute to the transformation of the `patternTransform`.

@AmeliaBR Do you think this is a breaking change? Do you have an example?

**Comment by dirkschulze** [comment]
It kind of seems that we mix this issue with #893.

Lets keep this issue to the reference box for percentage values. Will repost the above in the other issue.

**Comment by dirkschulze** [comment]
Created another example here: https://codepen.io/krit/pen/LmGyJy

The example has 8 rectangle stripes.
* The first 4 are as width as the viewport.
* The last 4 half the size of the viewport.


Furthermore:
* For the first 2 of each a `transform` property gets applied with percentage values.
* For the last two, `gradientTransform`.

`objectBoundingBox` and `userSpaceOnUse` are used between the 8 rects.

The `transform` property only gets implemented in Blink. The results are not fully conclusive (Blink has an issue with one of the `gradientTransform`s). However, it is save to say that Blink does not use the reference box of the referencing element.

**Comment by dirkschulze** [comment]
We clarified that `gradientTransform` and `patternTransform` apply in the gradient coordinate space or pattern coordinate space respectively. The same space, percentage values of the `x`, `x1`, `x2`, `y`, `y1`, `y2`, `width` and `height` attributes need to get resolved to too.

I'd propose that we ignore the "reference box" specified by `transform-box` not the `pattern`, `linearGradient`, `radialGradient` and `clipPath` elements and reuse the reference box that the above named attributes use. @AmeliaBR any objections to this sentiment? Though, as @AmeliaBR mentioned, this reference box is not entirely interoperable. However, that is an issue of the SVG spec IMO.

**Comment by AmeliaBR** [comment]
> I'd propose that we ignore the "reference box" specified by transform-box not the pattern, linearGradient, radialGradient and clipPath elements and reuse the reference box that the above named attributes use. @AmeliaBR any objections to this sentiment?

That much I support.

And to clarify, for pattern and for mask, you're suggesting to use the "outer" reference box (`patternUnits`/`maskUnits`), not the `*ContentUnits` ?  I think that's the only approach that can logically be applied, since the transformation needs to apply to the full canvas (e.g., after pattern tiling).
