### ISSUE TITLE
[scroll-animations-1] view-timeline-inset as part of view-timeline shorthand?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8926]
There's been an issue marked in the draft for a long time, which is whether `view-timeline-inset` should be a part of the `view-timeline` shorthand or not.

The key question here should be, do we want casual uses of `view-timeline` to reset the inset if it has been set already, or do we want it to cascade independently?

_Note: For `text-decoration`, for example, we allow it to reset most of the line properties (line type, style, color, thickness) but intentionally don't reset the position or offset so that flipping decorations on doesn't change the positioning._

**Comment by fantasai** [comment]
@bramus If it's part of the shorthand, then it _will_ reset. A shorthand _always_ resets all of its longhand properties.

The key question is _whether we want it to reset_: that's what determines whether it belongs in the shorthand or not:
- If it's better for insets to get reset every time the author declares a timeline, then it should be included.
- If it's better for insets to cascade independently, then it should stay separate.

**Comment by flackr** [comment]
I don't have a good sense for how important it is to cascade independently. I could imagine use cases but it's not clear to me whether they're contrived or not. I lean in the direction of including it, as it feels like it should be part of the shorthand, authors don't have to worry about a previously cascaded inset if they set the shorthand, and they can always make their inset rule cascade after if necessary.

**Comment by bramus** [comment]
> @bramus If it's part of the shorthand, then it _will_ reset. A shorthand _always_ resets all of its longhand properties.

Oof, a relief to hear it was me just misunderstanding that part of the question 😅

Still think it should be included as I don’t see a need for the insets to cascade independently.

**Comment by ydaniv** [comment]
I think that it would be actually a very good idea to make `view-timeline-inset` as part of the shorthand. For starters, insets can be specified inside `view()` and then it becomes confusing that they can't be specified in the shorthand.
And second, insets can become very handy for specifying a responsive offset using percentages that are only relative to the scrollport and ignore the subject's size. Now, I'm not sure whether the second point is a case for including them in the shorthand or not - I still think it does.
