### ISSUE TITLE
[css-transforms-1] User coordinate space statement breaks SVG

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#893]
http://www.w3.org/mid/CAFDDJ7yhF7Qn28wVMqb7ra6N9Q=j74OTqHWpjLeYrH=LQwmd4A@mail.gmail.com

In the CSS transforms module, the section "User Coordinate space" has the
following statement:

In particular the patternUnits
> <http://www.w3.org/TR/2011/REC-SVG11-20110816/pservers.html#PatternElementPatternUnitsAttribute>
> , gradientUnits
> <http://www.w3.org/TR/2011/REC-SVG11-20110816/pservers.html#LinearGradientElementGradientUnitsAttribute>
>  and maskUnits
> <http://www.w3.org/TR/2011/REC-SVG11-20110816/masking.html#MaskElementMaskUnitsAttribute> attributes
> don’t affect the user coordinate system used for transformations [SVG11]
> <http://dev.w3.org/csswg/css-transforms-1/#biblio-svg11>.

Links:

   - last published working draft
   http://www.w3.org/TR/2013/WD-css-transforms-1-20131126/#svg-user-coordinate-space
   - current editor's draft
   http://dev.w3.org/csswg/css-transforms-1/#svg-user-coordinate-space

Although the draft spec references SVG 1.1, this would be a *breaking
change* from current SVG behavior.  The SVG definition used for
gradientTransform and patternTransform is as follows:

 This additional transformation matrix is post-multiplied to (i.e.,
> inserted to the right of) any previously defined transformations, including
> the implicit transformation necessary to convert from object bounding box
> units <http://www.w3.org/TR/SVG11/coords.html#ObjectBoundingBox> to user
> space.

Links:
   -
   http://www.w3.org/TR/SVG11/pservers.html#LinearGradientElementGradientTransformAttribute
   -
   http://www.w3.org/TR/SVG11/pservers.html#PatternElementPatternTransformAttribute

Unless there is an overwhelming reason to change this, I would recommend
that the CSS transforms text be updated to state the transformation applies
in the user coordinate system in effect for the element's contents,*
including* any implicit transformations created by patternUnits,
gradientUnits, or maskUnits.

**Comment by smfr** [comment]
@AmeliaBR, I wonder if you might have mis-read this paragraph in the spec:

In particular the patternUnits, gradientUnits and maskUnits attributes don’t affect the user coordinate system used for transformations [SVG11].
Note that it's talking about patternUnits, not patternTransform. I'm not sure what that paragraph is trying to say, however (maybe that patternUnits affects the rendering of the pattern, but not other things rendered in the local coordinate space of the referencing element?)

**Comment by smfr** [comment]
@dirkschulze to figure something out

**Comment by AmeliaBR** [comment]
On re-examination, I suspect the paragraph was trying to distinguish between `patternUnits` vs `patternContentUnits`, and `maskUnits` vs `maskContentUnits`. But then I'm not sure what `gradientUnits` is doing there.

For masks, it might make sense to only transform the mask contents, not the extent rectangle.

But for patterns, you want to transform both the pattern tiles and the pattern contents.  That is what implementations currently do, and a pattern transform would be fairly useless otherwise.  However, implementations are not interoperable in some of the other details of patternTransform, like defining where the origin is and how the transformations interact with a `viewBox`.

**Comment by dirkschulze** [comment]
Ok, looked at this again. Lets limit the issue in question to the `<pattern>` element.

The `<pattern>` element has the attributes `patternUnits`, `patternContentUnits` and `patternTransform`. All 3 attributes influence the coordinate system for drawings.

* `patternContentUnits ` modifies the coordinate space for the content of `<pattern>` (content of the tile)
* `patternUnits` specifies a coordinate space for the pattern tile itself. Namely the `width` and `height` attributes.
* `patternTransform` specifies the coordinate space for the pattern itself. Percentage values get resolved according to the reference box of the referencing element in the local coordinate space of the referencing element (a `<rect>` element for instance).

As a result, according to the current specification text, `patternUnits` do not contribute to the transformation of the `patternTransform`.

@AmeliaBR Do you think this is a breaking change? Do you have an example?

**Comment by dirkschulze** [comment]
Created another example here: https://codepen.io/krit/pen/LmGyJy

The example has 8 rectangle stripes.
* The first 4 are as width as the viewport.
* The last 4 half the size of the viewport.

* For the first 2 of each a `transform` property gets applied with percentage values.
* For the last two, `gradientTransform`.

`objectBoundingBox` and `userSpaceOnUse` are used between the 8 rects.

The `transform` property only gets implemented in Blink. The results are not fully conclusive (Blink has an issue with one of the `gradientTransform`s). However, it is save to say that Blink does not use the reference box of the referencing element.

**Comment by dirkschulze** [comment]
I think my previous statement is incorrect in a way and so is the following spec text:

> In particular the patternUnits, gradientUnits and maskUnits attributes don’t affect the user coordinate system used for transformations [SVG11].

[patternUnits](https://www.w3.org/TR/SVG11/pservers.html#PatternElementPatternUnitsAttribute), [gradientUnits](https://www.w3.org/TR/SVG11/pservers.html#LinearGradientElementGradientUnitsAttribute) and [maskUnits](https://www.w3.org/TR/SVG11/masking.html#MaskElementMaskUnitsAttribute) clearly state that the transform gets applied after the coordinate transformation by those attributes. So, the transforms apply in the pattern space, gradient space or mask space. Only for `<clipPath>`, the coordinate space is the user coordinate space of the target.

I’ll change the spec text to reflect that and simply link to the *units attributes that would define the mapping of pattern space an co.
