### ISSUE TITLE
[css-easing-2] Intended possibility of discontinuity of `linear()`?

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#8933]
[2.1.2 Parsing](https://drafts.csswg.org/css-easing-2/#linear-easing-function-parsing) ensures that points in `<linear-stop-list>` have (not necessarily strictly) increasing inputs. And in [2.1.4 Output of a linear easing function](https://drafts.csswg.org/css-easing-2/#linear-easing-function-output) (irrelevant steps omitted):

> 2. Let *pointAIndex* be index of the last item in *points* with an input less than or equal to *inputProgress*, or 0 if there is no match.
> 
> […]
> 
> 4. Let *pointA* be *points*[pointAIndex].
> 
> 5. Let *pointB* be *points*[pointAIndex + 1].
>
> […] 

Following these steps, `linear(0, 0.6 50%, 0.4 50%, 1)` produces a discontinuous piecewise linear function:

![example](https://github.com/w3c/csswg-drafts/assets/97945148/3e786d8f-410c-4bdd-aa36-6c545f2dfec5)

Is this really intended by the spec? If so, I'll add an example in https://github.com/mdn/content/pull/27167.

**Comment by tabatkins** [comment]
We can't *stop* people from writing linear functions with multiple outputs for the same input, so yes, it's intended by the spec. I'm not certain the old evaluation text actually handled discontinuities properly, but the new text I've written definitely does, and matches your diagram.

(Additionally, if your function *starts* with a discontinuity, or *ends* with one, then inputs before or after the first/last point give a constant output equal to the first/last point.)
