### ISSUE TITLE
[css-text-4] Line limitations for text-wrapping

### ISSUE THREAD

**Issue by Que-tin** [w3c/csswg-drafts#8936]
Chrome currently implemented `text-wrap: balance` in a way where it only works on texts up to four rows because of performance reasons. According to the specs there is no limitation to the number of rows being affected or valid.

Would it make sense to specify how `text-wrap: balance` should behave across browsers before it lands in terms of if there should be limitations?

**Comment by Loirooriol** [comment]
Relevant text from https://drafts.csswg.org/css-text-4/#valdef-text-wrap-balance

> The exact algorithm is UA-defined.
> UAs may treat this value as [wrap](https://drafts.csswg.org/css-text-4/#valdef-text-wrap-wrap) if there are more than ten lines to balance.

**Comment by Que-tin** [comment]
Okay seems like I over read that. But is _may_ the correct word then?
I would expect smth. like:

> UAs shall treat this value as wrap if there are more than ten lines to balance.

To achieve a consistent behaviour across browsers.

**Comment by fantasai** [comment]
No, this is an area where we want UAs to improve over time.
