### ISSUE TITLE
[css-transitions-2] Naming transition mode property and values

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#8939]
In #8857 it was decided to add a new property that controls the transitioning mode for discrete values.

There wasn't a decision yet on how to name this property and what values it can take. So this issue is meant to discuss those options.

@flackr's [suggestions there](https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1580890102) were:

* `transition-mode`
* `transition-type`
* `transition-animation-type`
* `transition-property-mode` ([initial suggestion](https://github.com/w3c/csswg-drafts/issues/8857#issue-1717746858))

for the name and two values, one for default behavior (anything animatable but not discrete) and one for including discrete transitions.

Suggestions for default behavior keywords:

* `normal`
* `interpolable`

Suggestions for keywords that include discrete transitions:

* `discrete`
* `animatable`

Sebastian

**Comment by SebastianZ** [comment]
My vote goes for `transition-type: [ normal | animatable ]#` for the reason [mentioned](https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1580890102) by @flackr and because the names are short and easy to spell.

I'm leaning a little bit more to `-type` than `-mode` for the property name because it is more common, though I don't have a strong preference between those two. The other two suggested names are unnecessarily long.

Regarding the values, `interpolable` might be a little bit hard to spell as it could be mixed with `interpolatable`. On the other hand, it might not be immediately clear to everyone that `normal` means that discrete transitions are excluded. I still lean towards that as it's used in other places, it's easy to spell and it's meaning (as initial value) needs to be learned anyway.
For including discrete transitions, I think `animatable` is the way to go, as `discrete` may confuse people whether it makes transitions of interpolable values also discrete.

I didn't consider any other names yet, so maybe there are even better ones.

Sebastian

**Comment by dbaron** [comment]
I think this was resolved in https://github.com/w3c/csswg-drafts/issues/8857#issuecomment-1646035541 rather than using this separate issue.
