### ISSUE TITLE
[css-nesting] Why does CSSStyleRule not inherit from CSSGroupingRule?

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#8940]
https://drafts.csswg.org/css-nesting/#cssom-style has:

```webidl
partial interface CSSStyleRule {
  [SameObject] readonly attribute CSSRuleList cssRules;
  unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0);
  undefined deleteRule(unsigned long index);
};
```

Why doing that rather than inheriting from `CSSGroupingRule`, which gives you [that](https://drafts.csswg.org/cssom/#the-cssgroupingrule-interface)?

cc @tabatkins @sesse

**Comment by emilio** [comment]
cc @mdubet

**Comment by mdubet** [comment]
I've asked the same question during a WG meeting : https://github.com/w3c/csswg-drafts/issues/8350#issuecomment-1497776457

**Comment by tabatkins** [comment]
I honestly just didn't think about changing the inheritance tree? It feels like doing that to such an old rule *might* have compat implications, but then again CSSMediaRule is just as old and we changed it. So yeah, probably we can just do it this way.

**Comment by emilio** [comment]
This has tests now, and spec text, so closing.

FWIW Gecko shipped this without issues.
