### ISSUE TITLE
[css-anchor-position-1] One of the spec examples has a `anchor-element` mention that's getting interpreted as an HTML element and hence isn't visible

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#8973]
https://drafts.csswg.org/css-anchor-position-1/#example-0b98937b Example 3 has this odd-looking code-comment:

```
    // No  specified,
    // so it takes from 'anchor-default'.
```

If you take a look in devtools or in view-source, you can see that it actually says:
```
    // No <anchor-element> specified
```
...and `<anchor-element>` isn't properly escaped, so it gets treated as an unrecognized HTML tag and disappears from the rendered text.

I'm not handy enough with BikeShed to know the best incantation to avoid this, but I suspect @tabatkins knows what to do.

**Comment by dholbert** [comment]
Relevant line of bikeshed that needs fixing:
https://github.com/w3c/csswg-drafts/blob/bcdd5ccb4d5a7f6f4239465a30b77d50f989a177/css-anchor-position-1/Overview.bs#L306

**Comment by tabatkins** [comment]
Fixed some time ago.
