### ISSUE TITLE
[css-text] Incorrect text-transform capitalize behavior for Catalan geminate Ls

### ISSUE THREAD

**Issue by zipus** [w3c/csswg-drafts#8987]
I've noticed an issue with the text-transform:capitalize property in CSS when used on words containing "l·l" in Catalan (see [Interpunct - Catalan](https://en.wikipedia.org/wiki/Interpunct#Catalan)). When this rule is applied to such words, the CSS interpreter incorrectly treats the interpunct as a word boundary and capitalizes the letter after it.

To illustrate, consider the word "cancel·lar". When text-transform:capitalize is applied, it currently results in "Cancel·Lar". However, according to Catalan language rules, it should be "Cancel·lar" instead. The interpunct is not considered a word boundary, and the second 'l' should not be capitalized.

I propose updating the algorithm used for text-transform:capitalize to respect language-specific case mapping rules such as this one.

**Comment by Loirooriol** [comment]
Relevant spec: https://drafts.csswg.org/css-text-4/#text-transform-mapping

> For [capitalize](https://drafts.csswg.org/css-text-4/#valdef-text-transform-capitalize), what constitutes a “word“ is UA-dependent; [[UAX29]](https://drafts.csswg.org/css-text-4/#biblio-uax29) is suggested (but not required) for determining such word boundaries.

I'm not sure what UAX29 would imply, but Blink and WebKit seem to behave as expected for Catalan, Firefox is wrong indeed (this reminds me of [bug 257073](https://bugzilla.mozilla.org/show_bug.cgi?id=257073)). So filing a bug at https://bugzilla.mozilla.org/ may be a more practical solution.

Interestingly, Firefox considers `canceŀlar` to be a single word, using U+0140 instead of U+006C U+00B7, but the latter is recommended by unicode (and is more convenient to write).

**Comment by r12a** [comment]
@zipus thanks for pointing this out.

I created a Gecko bug report at https://bugzilla.mozilla.org/show_bug.cgi?id=1839354

And will be tracking it as a Catalan gap-analysis report at https://w3c.github.io/eurlreq/gap-analysis/latn-ca-gap#transforms

**Comment by zipus** [comment]
I created already a bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1839308

**Comment by r12a** [comment]
I updated our gap tracker to point to your bug. Thanks.

**Comment by moyogo** [comment]
This is true for other languages as well.

For example some other European languages like Sardinian ("agiuda·nos" capitalized as "Agiuda·nos"), in Gascon Occitan ("in·hèrn", "des·har" capitalized as "In·hèrn", "Des·har"), in one orthography of Arpitan ("ôtrich·ien", "g·eografia" capitalized "Ôtrich·ien", "G·eografia"), in one orthography of Gallo ("ag·rouée" capitalized "Ag·rouée") or even in French in some gender inclusive notations ("un·e" capitalized "Un·e").

Some American languages like Kutenai, Oneida, Onondaga, Tuscarora, Tsawwassen Halkomelem and others are typically not capitalized but borrowed words or names may appear in English or other languages that do capitalize. Sierra de Juárez Zapotec also has the grapheme l·l and does capitalize like Catalan.

**Comment by r12a** [comment]
I wonder whether we can make a general rule that a letter is never capitalised when it follows  ·  word-medially?

**Comment by andjc** [comment]
It is a long standing issue, and isn't limited to casing in CSS. The interpunct isn't classified as a word forming character, so creates all sorts of interesting issues in many places not just casing, and in many programing languages.

**Comment by fantasai** [comment]
@r12a Two questions:

- Is there anything to fix in CSS Text 3?
- Should this issue be escalated to Unicode wrt UAX29?

**Comment by r12a** [comment]
Afaict, the middle dot inside a word should not produce a letter during capitalisation – it isn't a word separator.  I don't see anything to fix in CSS Text.

**Comment by frivoal** [comment]
Tested by https://github.com/web-platform-tests/wpt/pull/41652. Closing.
