### ISSUE TITLE
[css-values] what's the base URL to be used for inline styles?

### ISSUE THREAD

**Issue by jeisinger** [w3c/csswg-drafts#899]
In https://drafts.csswg.org/css-values-3/#relative-urls it is defined how to resolve relative URLs in url(). However, the definition of the base URL only talks about stylesheets. What about inline styles? Or styles derived from presentation attributes?

**Comment by bzbarsky** [comment]
Note that at least for HTML presentational attributes the HTML spec covers this.  For example, for <body background> it says:

> When a body element has a background attribute set to a non-empty value, the new value is expected to be parsed relative to the element's node document, and if this is successful, the user agent is expected to treat the attribute as a presentational hint setting the element's 'background-image' property to the resulting URL string.

The "parsed" bit there returns an absolute URL.

**Comment by jeisinger** [comment]
ah, fair enough. I guess we could make HTML supply the referrer at this point as well.

I also found https://drafts.csswg.org/css-style-attr/#interpret that says that for inline styles, relative URLs have to be resolved relative to the style attribute's element / document.
