### ISSUE TITLE
[css-values-4][cssom] Serialization of <position>

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#8996]
https://drafts.csswg.org/css-values-4/#position-serialization says:

> If only one component is specified:
> The implied [center](https://drafts.csswg.org/css-backgrounds-3/#valdef-background-position-center) keyword is added, and a 2-component value is serialized.

but https://drafts.csswg.org/cssom/#serializing-css-values says:
> If component values can be omitted or replaced with a shorter representation without changing the meaning of the value, omit/replace them.

Which one is right? Personally I have a slight preference of omitting redundant values, unless there's a specific compat reason not to (which is mandated by the CSSOM spec), just for the sake of consistency with serialization of other types.

**Comment by nt1m** [comment]
cc @emilio @fantasai @tabatkins @danielsakhapov

**Comment by Loirooriol** [comment]
https://wiki.csswg.org/ideas/mistakes

> `background-size` with one value should duplicate its value, not default the second one to auto. Ditto `translate()`.

I guess that a reasonable expectation would be that `background-position: 0px` behaves as `background-position: 0px 0px`, so serializing as `background-position: 0px center` can avoid misunderstandings.

See https://github.com/whatwg/compat/issues/28 and #7802.

**Comment by nt1m** [comment]
The citations you linked is for `background-size` (which is 2 sizes), not `background-position`, not sure there's as much confusion for background-position

**Comment by cdoublev** [comment]
> fantasai: a more important reason is the transform-origin syntax, which becomes ambiguous if you only have one value
> fantasai: You wouldn’t be able to consider position as a single value without considering whether or not you have a Z component. That creates a serialization of position cannot be self-contained
> fantasai: The proposal: <position> always serializes at least two values

https://github.com/w3c/csswg-drafts/issues/2274#issuecomment-402322967

**Comment by tabatkins** [comment]
Ah, I forgot about that when I approved the test change that reduced some position serializations. We should capture that in the spec, since it's important.
