### ISSUE TITLE
[css-fonts] Mixed content warning for HTTP w3c_home image

### ISSUE THREAD

**Issue by SimonSapin** [w3c/csswg-drafts#90]
On https://drafts.csswg.org/css-fonts/, Firefox shows a padlock with a yellow warning sign because the document contains an `<img>` element with `src="http://www.w3.org/Icons/w3c_home"`. That `src` should be HTTPS.

I’d send a pull request, but that image is not present in `Fonts.src.html` and I didn’t find how it gets added to `Fonts.html`.

CC @nattokirai

**Comment by nattokirai** [comment]
Fixed. This is in CVS, in the code for Bert's preprocessor. Looks like Bikeshed still emits http anchor links in various places.

**Comment by SimonSapin** [comment]
Looks good, thanks.

![screenshot from 2016-01-19 09-15-26](https://cloud.githubusercontent.com/assets/291359/12413172/382cf6a8-be8d-11e5-892c-7ed0ce1496af.png)
