### ISSUE TITLE
[mediaqueries-5] [css-syntax-3] Unclear how <general-enclosed> is terminated

### ISSUE THREAD

**Issue by tbjgolden** [w3c/csswg-drafts#9002]
When reading a general enclosed expression, it says to consume an `<any-value>` production. However it doesn't mention how to detect how this production terminates. Does it read until the first `)` - or does it also allow nesting parentheses pairs `( ... )` (or indeed `[ ... ]` and other groupings)?

**Comment by cdoublev** [comment]
> However it doesn't mention how to detect how this production terminates.

I terminates with the end of the input. Any CSS input goes through [*consume a list of component values*](https://drafts.csswg.org/css-syntax-3/#consume-list-of-components), which consumes `(...)`, `[...]`, `{...}`, into a single component value.

  > **component value**
  >
  > A component value is one of the preserved tokens, a function, or a simple block.
  >
  > **preserved tokens**
  >
  > Any token produced by the tokenizer except for `<function-token>`s, `<{-token>`s, `<(-token>`s, and `<[-token>`s.
  >
  > NOTE: The non-preserved tokens listed above are always consumed into higher-level objects, either functions or simple blocks, and so never appear in any parser output themselves.
  
https://drafts.csswg.org/css-syntax-3/#preserved-tokens

**Comment by tbjgolden** [comment]
Ah okay - I think I understand now; thank you!
