### ISSUE TITLE
[css-view-transitions-2] MPA support without JavaScript

### ISSUE THREAD

**Issue by DannyMoerkerke** [w3c/csswg-drafts#9007]
I have been playing with view transitions in an MPA with CSS only which currently works in Chrome Canary with the following flags enabled:
- [#enable-experimental-web-platform-features](chrome://flags/#enable-experimental-web-platform-features)
- [#view-transition](chrome://flags/#view-transition)
- [#view-transition-on-navigation](chrome://flags/#view-transition-on-navigation)

The HTML documents also have the meta tag `<meta name="view-transition" content="same-origin">`

I don't see this mentioned anywhere anymore in the [article on the Chrome Developers site](https://developer.chrome.com/docs/web-platform/view-transitions/) anymore so has this support for MPAs been deprecated?
Or will this still be added in the future?

This is my working demo: [https://small-ringed-crest.glitch.me/view-transition1.html](https://small-ringed-crest.glitch.me/view-transition1.html)

**Comment by vmpstr** [comment]
This feature is under active development. We're in the process of putting together a spec draft for this.

We have an explainer for the feature here: https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md
