### ISSUE TITLE
[css-shapes-1] Simplify the animation type of `shape-outside`

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#9009]
The animation type of [`shape-outside`](https://drafts.csswg.org/css-shapes-1/#shape-outside-property) is "as defined for &lt;basic-shape&gt;, otherwise discrete", but the [`clip-path`](https://drafts.fxtf.org/css-masking/#the-clip-path) property in a similar situation has its animation type as "by computed value". [Web Animations](https://drafts.csswg.org/web-animations-1/#animating-properties) seems to have also covered the case needed by `shape-outside` in "by computed value", so it may be OK to simplify the animation type of `shape-outside` as "by computed value".

**Comment by astearns** [comment]
The "By Computed Value" section in Web Animations doesn’t fit one of the discrete cases for shape-outside: we cannot animate between two shapes from image, so that has to be discrete (even though the computed values have the same number of components and are the same type)
