### ISSUE TITLE
[css-transforms-1] How should transforms affect geometry of boxes, w.rt. overflow

### ISSUE THREAD

**Issue by atanassov** [w3c/csswg-drafts#901]
In the case when a child box gets transformed so that it fully fits inside its parent box, does it's size get affected by scrollbars or not?

See example: https://jsfiddle.net/gpqkzth1/

**Comment by smfr** [comment]
We talked about this in Seattle but did not come to a conclusion, if I recall.

**Comment by atanassov** [comment]
Your recollection is correct. The issue here was meant to capture the fact we still need a solution :)

**Comment by smfr** [comment]
The original issue: https://drafts.csswg.org/css-transforms/issues-wd-2013.html#issue-48
Seattle resolution: https://lists.w3.org/Archives/Public/www-style/2017Feb/0054.html
