### ISSUE TITLE
[css-grid-2] `subgrid` specified on grid-template-rows/columns and computed value for standalone axis 

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [w3c/csswg-drafts#9015]
"If there is no [parent grid](https://www.w3.org/TR/css-grid-2/#parent-grid), this value is equivalent to the initial value, [none](https://www.w3.org/TR/css-grid-2/#valdef-grid-template-rows-none), and the [grid container](https://www.w3.org/TR/css-grid-2/#grid-container) is not a [subgrid](https://www.w3.org/TR/css-grid-2/#subgrid)."

https://www.w3.org/TR/css-grid-2/#subgrid-listing

Does this also apply to the computed value for grid-template-rows/columns? That is my understanding, but no implementations are following this. I have a PR open to address this in Chromium ([here](https://chromium-review.googlesource.com/c/chromium/src/+/4647952)), but I wanted to run this by the working group to make sure I'm not missing anything.

To clarify, if an item has `display: grid`, and `grid-template-columns` is set to a value containing `subgrid`, but the item is *not* the child of a parent grid (and thus not a subgrid, but *is* a valid grid), should the computed value of `grid-template-columns` be `none`?

The variations of this are clear - if it's *not* `display: grid`, the computed value is the specified `subgrid` value as specified (not expanding repeaters, etc.), and if it *is* a valid subgrid, the computed value expands repeaters and outputs line names and not sizes. These are both in agreement across implementations.

Here's what I have observed for this scenario:

Blink: Crash (fixed in the above PR to compute to `none`)
Gecko: Reports tracks sizes *without* line names, as if it's a standalone grid (but missing line names). I can see how this *behaves* as if it's `none` by ignoring the line names, but it seems a bit strange.
WebKit: Returns the specified value as if it were not a grid container at all. This seems reasonable to me, but doesn't follow the above referenced line in the spec.

**Comment by KurtCattiSchmidt** [comment]
Note that the above PR adds an official test case for this scenario that only passes in Chromium with my changes. I'm happy to update the behavior in Chromium and the test case if I'm reading this incorrectly.

**Comment by Loirooriol** [comment]
See #6165: no, it should not affect the computed value. But I think it should still affect the resolved value tat you get in `getComputedStyle`. You can check the actual computed value by using inheritance: [testcase](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Adiv%20%7B%20display%3A%20grid%3B%20grid-template-columns%3A%20subgrid%3B%20grid-auto-columns%3A%20100px%3B%20%7D%0Adiv%20%3E%20div%20%7B%20grid-auto-columns%3A%2010px%3B%20%7D%0Aspan%20%7B%20background%3A%20cyan%3B%20%7D%0A%3C%2Fstyle%3E%0ATEST%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20inherit%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%0A%3Cbr%3E%0ASUBGRID%20REFERENCE%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20subgrid%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E%0A%3Cbr%3E%0ANESTED%20GRID%20REFERENCE%3A%0A%3Cdiv%3E%3Cdiv%20style%3D%22grid-template-columns%3A%20none%22%3E%3Cspan%3E.%3C%2Fspan%3E%3C%2Fdiv%3E%3C%2Fdiv%3E).

**Comment by Loirooriol** [comment]
Yes, Firefox seems right. If the specified value has `subgrid`, then https://drafts.csswg.org/css-grid/#computed-track-list

> The [computed track list](https://drafts.csswg.org/css-grid/#computed-track-list) of a [`subgrid`](https://drafts.csswg.org/css-grid/#valdef-grid-template-rows-subgrid) axis is the `subgrid` keyword followed by a [list](https://infra.spec.whatwg.org/#list) of [line name sets](https://drafts.csswg.org/css-grid/#line-name-set) and [computed repeat notations](https://drafts.csswg.org/css-grid/#computed-repeat-notation) representing the line names specified for that axis.

If the element is a grid, this may end up behaving as `none` (standalone axis) or stay as a subgridded axis.

When using `getComputedStyle`, then https://drafts.csswg.org/css-grid/#resolved-track-list applies, so e.g. when `subgrid` behaves as `none` and produces a standalone axis, we get the used track sizes.

**Comment by KurtCattiSchmidt** [comment]
Thank you for clarifying. I will update the implementation in Chromium as well as the test case to match Firefox, as the above referenced PR has landed.

The corollary to this is that if it *behaves* as `none`, that line names defined there should be dropped. Firefox is doing this with the computed style values, and they should also not be inherited into child subgrids. I haven't tested this yet, but I think that Chromium will need some additional work to drop these from both computed style and inheritance. I'll definitely add a test case for that along with the other referenced changes.

**Comment by KurtCattiSchmidt** [comment]
I think it's reasonable to mark this issue as closed from the working group perspective (although there's still some work do be done on my end for the Chromium implementation and tests). Closing out this issue.

**Comment by KurtCattiSchmidt** [comment]
The commits listed above are for the Chromium behavior to match your reply above @Loirooriol. The test was also updated to reflect this, and Blink and Gecko are now in agreement with the above patch.
