### ISSUE TITLE
[css-values-4] Cyclic dependency between `lh` and font-relative units

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#9018]
The [spec](https://www.w3.org/TR/css-values-4/#:~:text=When%20used%20in%20the%20value%20of%20the%20font%2Dsize%20property%20on%20the%20element%20they%20refer%20to) only covers two cases of cyclic dependency:
- Font-relative units used in `font-size`
- `lh`/`rlh` used in `line-height`

There are more cases that are not covered:
1. Font-relative units used in other font properties that affect font selection, e.g., `font-weight: calc(10ex / 1px)`
2. ~~Dependency cycle formed by font properties and `line-height`, e.g., `line-height: 2em; font-size: 1lh`~~

(Edit: 2 is already covered, as `lh` is considered a font-relative length unit)

Right now (1) isn't surfaced in any browser because no one supports `calc(10ex / 1px)` yet. But this will also surface if functions like `atan2()` and `sign()` that can convert a `<length>` into a non-length type is properly implemented. This has also been discussed in #8169 

For (2), currently Blink and WebKit are breaking the cycle by using parent's line height to compute `fon-size` (see (test case)[https://jsfiddle.net/3rojdnsc/]). Gecko hasn't implemented `lh` yet.

I don't have a strong opinion on how exactly the cycle should be broken, and I guess it doesn't matter because there's no real use case with such dependency cycles. We just need a solution for spec completeness.

**Comment by Loirooriol** [comment]
(1) is basically #8169 
(2) was discussed in #2115:

> RES0LVED: define lh unit resolution to be that of the parent when the lh unit is spec on line height or font size

It's already covered in the spec, note that `lh` is considered to be a local font-relative length unit.

BTW, registered properties introduce another cycle: https://github.com/w3c/css-houdini-drafts/issues/1080

**Comment by xiaochengh** [comment]
> (1) is basically https://github.com/w3c/csswg-drafts/issues/8169

Their topics are different, unless we want to repurpose #8169 to discuss dependency instead?

> It's already covered in the spec, note that lh is considered to be a local font-relative length unit.

Thanks for the pointer! Then we don't have an issue here.

> BTW, registered properties introduce another cycle: https://github.com/w3c/css-houdini-drafts/issues/1080

I think this is already covered by https://drafts.css-houdini.org/css-properties-values-api/#dependency-cycles?

However, for backward compatibility reasons, we can't adopt the same approach (i.e., make everything in the cycle invalid) for built-in properties.

**Comment by Loirooriol** [comment]
> I think this is already covered by https://drafts.css-houdini.org/css-properties-values-api/#dependency-cycles?

That only handles registered properties with a syntax of `<length>` or `<length-percentage>`, but with unit algebra we may have cycles with e.g. `<number>` or `<angle>`. See the examples in the issue.

**Comment by andruud** [comment]
Can we simply extend the behavior that font-relative units have in `font-size` to all `font-*` properties? And to any other properties that affect font selection?

**Comment by Loirooriol** [comment]
Anything else to do here after the resolution in https://github.com/w3c/csswg-drafts/issues/8169#issuecomment-1632890687 ?

**Comment by xiaochengh** [comment]
Nope
