### ISSUE TITLE
[css-pseudo] [css-pseudo-4] Draft text: First-Line Text example missing 'styled'

### ISSUE THREAD

**Issue by LarryLACa** [w3c/csswg-drafts#9023]
In the 20221230 Working Draft https://www.w3.org/TR/css-pseudo-4/ (minor typo)
In the example for First-Line Text,
the base HTML text is:
  ... first line will be styled by the ‘::first-line’ pseudo-element.
In the 2 examples for page width impact,
the word 'styled' is omitted from the example:
  ... first line will be by the ‘::first-line’ pseudo-element.

**Comment by SebastianZ** [comment]
Thank you for the hint! I fixed it now.

Sebastian

**Comment by LarryLACa** [comment]
Thanks Sebastian.  In the meantime, I found the Edit option, and created a branch here
   https://github.com/w3c/csswg-drafts/compare/main...LarryLACa:csswg-drafts:patch-1
 with my edits, which I will keep, but abandon for now.

Typical newbee thrashing..
