### ISSUE TITLE
[meta] Get syntax highlighting for Bikeshed files

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#903]
I’m not sure whether you could override Github’s syntax highlighting locally for the whole repository, but it would help if `.bs` files were parsed as either HTML or Markdown files. 

Eventually, it should be added to https://github.com/github/linguist but things like https://github.com/tabatkins/bikeshed/issues/214 would probably have to be fixed first. Alternatively, the file extension could be changed to include `.md` or `.html`.

**Comment by upsuper** [comment]
Given that this repo is marked that 86.3% of the code is HTML, I suspect that GitHub's linguist has already recognized `.bs` files here as HTML. But highlight doesn't use the language from linguist. I guess that relies on some variant of pygments.

Linguist's README says you can use vim or emacs modelines to specify language for highlight of a given file, which is probably something we can actually do.

**Comment by upsuper** [comment]
> I suspect that GitHub's linguist has already recognized `.bs` files here as HTML.

Oh, hmm, no. Linguist actually think those files are plain text, so they are probably not counted as source files at all...

**Comment by fantasai** [comment]
File this against the bikeshed repo, please, as it's more of a bikeshed issue than a CSS spec issue? Thanks~

**Comment by tabatkins** [comment]
I have no idea what I'd do for it in Bikeshed, either. I guess try and bug GitHub to add support for Bikeshed files?  But I don't have a good, official syntax highlighter for them yet anyway, *and* GitHub doesn't have an official issues list anyway.

**Comment by upsuper** [comment]
GitHub's Linguist repo is probably where the issue should go https://github.com/github/linguist

**Comment by Crissov** [comment]
Meanwhile, https://github.com/github/linguist/issues/1792 has been closed and a [`.gitattributes` override](https://github.com/github/linguist#overrides) should work, e.g. treating Bikeshed as Markdown (which includes HTML):

````
$ cat .gitattributes
*.bs linguist-language=Markdown
````

**Comment by tabatkins** [comment]
I've added a `.gitattributes` setting the highlighting language to HTML. I tried Markdown first, but it misfired a good bit, and didn't highlight most of the markup.
