### ISSUE TITLE
[css-view-transitions-1] Question on standardization timeline

### ISSUE THREAD

**Issue by tom-ricci** [w3c/csswg-drafts#9030]
Is there an idea on how much time it will take for to become standardized?

**Comment by SebastianZ** [comment]
What do you mean exactly?

If you mean, when do all main browsers support View Transitions, then you should rather ask the individual browser vendors. Google already shipped a first version in Chrome 111.
If the question is rather when does the specification become a recommendation, then the answer is that it'll probably still take quite a while, even when it is actively being worked on.

Having said that, I am neither an author of that spec., nor am I an implementer.

Sebastian

**Comment by tom-ricci** [comment]
I'm referring to the first question, I'll contact a few major browsers about it instead.
Thank you!

**Comment by SebastianZ** [comment]
For what it's worth, I already created the related feature requests. The one for Firefox some time ago, the one for Safari right now:

* Gecko/Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1823896
* WebKit/Safari: https://bugs.webkit.org/show_bug.cgi?id=259055

Sebastian
