### ISSUE TITLE
[css-images-4] Color stop syntax allows position before color

### ISSUE THREAD

**Issue by wangp** [w3c/csswg-drafts#9032]
https://drafts.csswg.org/css-images-4/#color-stop-syntax suggests that the \<color-stop-length\> can appear before \<color\>. Is that actually the intention?

I saw a comment mentioning the issue in PR https://github.com/w3c/csswg-drafts/pull/3657

**Comment by cdoublev** [comment]
Also discussed in #8021. `<angular-color-stop>` is also concerned.

**Comment by tabatkins** [comment]
Reverted by #8021

**Comment by cdoublev** [comment]
`<linear-color-stop>` and `<angular-color-stop>` are still permutations in CSS Images 4. #8021 only reverted `<linear-color-stop>` in CSS Images 3.
