### ISSUE TITLE
[css-values-4] Wrong determined type for asin, acos, atan, and atan2

### ISSUE THREAD

**Issue by AtkinsSJ** [w3c/csswg-drafts#9034]
In https://drafts.csswg.org/css-values-4/#calc-type-checking, the determined types of all of the trigonometric functions are specified here:

> [sign()](https://drafts.csswg.org/css-values-4/#funcdef-sign) [sin()](https://drafts.csswg.org/css-values-4/#funcdef-sin) [cos()](https://drafts.csswg.org/css-values-4/#funcdef-cos) [tan()](https://drafts.csswg.org/css-values-4/#funcdef-tan) [asin()](https://drafts.csswg.org/css-values-4/#funcdef-asin) [acos()](https://drafts.csswg.org/css-values-4/#funcdef-acos) [atan()](https://drafts.csswg.org/css-values-4/#funcdef-atan) [atan2()](https://drafts.csswg.org/css-values-4/#funcdef-atan2) [pow()](https://drafts.csswg.org/css-values-4/#funcdef-pow) [sqrt()](https://drafts.csswg.org/css-values-4/#funcdef-sqrt) [log()](https://drafts.csswg.org/css-values-4/#funcdef-log) [exp()](https://drafts.csswg.org/css-values-4/#funcdef-exp)
>    `«[ ]»` (empty map).

This means that `asin()`, `acos()`, `atan()`, and `atan2()` will all claim to return a `<number>`, when they actually return an `<angle>`. I believe these four should all return `«[ "angle" → 1 ]»` instead.

**Comment by tabatkins** [comment]
Correct; I might have written that when the functions were defined just over radians? Or I just messed up. Anyway yeah, the arc functions should return angles.

**Comment by cdoublev** [comment]
The wront type is from https://github.com/w3c/csswg-drafts/commit/cc714526b6a1846cc737236d1e60491a5d26b3eb, which fixed #7486. Sorry, because I continued to expect these functions to output an angle but I did not spot the mistake.
