### ISSUE TITLE
[css-values] Please specify how CSS fetches resources

### ISSUE THREAD

**Issue by jeisinger** [w3c/csswg-drafts#904]
https://drafts.csswg.org/css-values-3/#urls allows for referencing external resources via URLs. CSS should also specify how those URLs are fetched (or provide hooks to do so - but for this, it needs to be possible to link back from any <url> to an environment that can fetch). CSS fonts already has some text that goes into this direction: https://drafts.csswg.org/css-fonts/#font-fetching-requirements but that really should be a central place, and the font spec doesn't work for styles not associated with a stylesheet)

**Comment by xfq** [comment]
Related issue: #562

**Comment by tabatkins** [comment]
I'm pretty sure this was indeed a dupe of #562, which is now resolved, so closing this one too.
