### ISSUE TITLE
[css-view-transitions-1] Size animation should use logical properties.

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9057]
We currently use `width` and `height` when setting up the default animation for pseudo-elements [here]( https://drafts.csswg.org/css-view-transitions-1/#setup-transition-pseudo-elements-algorithm:~:text=Set%20capturedElement%E2%80%99s%20group%20keyframes%20to%20a%20new%20CSSKeyframesRule%20representing%20the%20following%20CSS). And for keeping the end state in sync with the DOM elements [here]( https://drafts.csswg.org/css-view-transitions-1/#style-transition-pseudo-elements-algorithm:~:text=Set%20width%20to%20capturedElement%E2%80%99s%20old%20width).

This should probably use logical properties like block-size/inline-size? @noamr @fantasai @vmpstr

**Comment by vmpstr** [comment]
Since we're animating both, I don't think this matters too much. However, width/height are far more used than inline-size/block-size by a wide margin. I feel like if the developer was to customize or see what the values are, they would start with checking width and height.

**Comment by fantasai** [comment]
@vmpstr They map to each other during the cascade, so as long as we're setting both to explicit values, it doesn't really matter which one we use in the UA origin.

**Comment by khushalsagar** [comment]
Great, in that case proposed resolution for this issue is to leave the spec as-is: "use width/height for size animation on ::view-transition-group".

**Comment by noamr** [comment]
Closing as per resolution.
