### ISSUE TITLE
[css-fonts-4]  [OPENTYPE-FONT-GUIDE] reference link is outdated

### ISSUE THREAD

**Issue by vitorroriz** [w3c/csswg-drafts#9067]
The [[OPENTYPE-FONT-GUIDE]](https://drafts.csswg.org/css-fonts/#biblio-opentype-font-guide) link referenced in CSS Fonts Module Level 4 and defined at https://drafts.csswg.org/css-fonts/#informative seems to be outdated. I couldn't find an alternative link for suggesting it as a fix.

The link is pointing to https://www.fontfont.com/staticcontent/downloads/FF_OT_User_Guide.pdf

**Comment by svgeesus** [comment]
Looks like whatever that used to point to is no longer there and the link is being redirected. As this is purely an informative tutorial, easiest would be to just delete the reference.
