### ISSUE TITLE
[css-color-hdr] Add CSS property to limit dynamic range of HDR content

### ISSUE THREAD

**Issue by ccameron-chromium** [w3c/csswg-drafts#9074]
HDR content is great, but there are times when a page may want to limit HDR content to be "not as bright", be that either "keep it all in SDR" or "just a hint of HDR, but not so much that it will look awkward next to SDR content".

A proposed solution is to add a [`dynamic-range-limit`](https://github.com/ccameron-chromium/hdr-headroom-limit/blob/main/EXPLAINER.md) CSS property.

That proposal suggests three qualitative values:
 * `standard`, which limits to standard dynamic range (this name matches the CSS `dynamic range` query).
 * `high`, which means that no limit is imposed (this name matches the CSS `dynamic-range` query)
 * `constrained-high`, which means "not so much that it will look awkward next to SDR content" (this matches the [name used in macOS and iOS](https://developer.apple.com/documentation/uikit/uiimagedynamicrange/uiimagedynamicrangeconstrainedhigh?language=objc)

The exact numerical meaning of values depends on many things that, for fingerprinting reasons, can't be exposed directly, including the current display device's maximum brightness, the current display's SDR brightness, the ambient brightness, etc. In order to allow animation between these qualitative values, a `mix-dynamic-range-limit` functional is added.

**Comment by adixon-adobe** [comment]
This is definitely something we're interested in at Adobe when displaying photo grids, where toning down bright HDR images is desired. I think it'd be reasonable if this only applied to image/video content, so long as it also applies to background images.

**Comment by ccameron-chromium** [comment]
Link to example video is at:
https://photos.app.goo.gl/pAumaUXocDaRo8B56

**Comment by svgeesus** [comment]
New section [2. Controlling Dynamic Range](https://drafts.csswg.org/css-color-hdr/#controlling-dynamic-range) containing:

- [2.1. Introducing Headroom](https://drafts.csswg.org/css-color-hdr/#introducing-headroom) _(non-normative)_
- [2.2. The `dynamic-range-limit` property](https://drafts.csswg.org/css-color-hdr/#the-dynamic-range-limit-property)
- [2.3. Mixing Dynamic Range Limits: the `dynamic-range-limit-mix()` function](https://drafts.csswg.org/css-color-hdr/#dynamic-range-limit-mix)

Function in particular is a bit brief, we didn't discuss much on the call.

Needs more examples

**Comment by ariofrio** [comment]
Something like this is definitely needed! Some considerations related to browser defaults, abuse potential, and accessibility: https://github.com/WebKit/standards-positions/issues/312#issuecomment-2295386694
