### ISSUE TITLE
[css-properties-values-api] [css-cascade] Interaction of @scope and @property

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#9077]
With `@scope` defined in css-cascade-6, should authors be able to register custom properties with `@property` inside the scope, without those properties loitering the global space?

```css
@scope (.card) {
  /* Should --color be local to the scope or not? */
  @property --color {
    …
  }
}
```

If it should be scoped, should that happen automatically or should it be opt-in by means of an extra descriptor during registration?

**Comment by andruud** [comment]
> With @scope defined in css-cascade-6, should authors be able to register custom properties with @property inside the scope, without those properties loitering the global space?

No, we couldn't even do it for ShadowDOM (which is more strict and encapsulating): https://drafts.css-houdini.org/css-properties-values-api-1/#shadow-dom

**Comment by bramus** [comment]
Thanks for the clarification, @andruud. Closing.
