### ISSUE TITLE
[css-transforms-1] Application of transform to inlines

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#908]
https://www.w3.org/mid/b464220dd959f9a9f808dd4aad85288e@gtalbot.org
http://www.w3.org/mid/20140210195906.GA18205@crum.dbaron.org

Behavior is generally agreed-upon, but dbaron wasn't sure that the spect text was complete; asked about display:flex, grid etc.

Need to check that the following text is accurate:

> an element whose layout is governed by the CSS box model which is either a block-level or atomic inline-level element, or whose display property computes to table-row, table-row-group, table-header-group, table-footer-group, table-cell, or table-caption [CSS21]

**Comment by fantasai** [comment]
It is not accurate. Flex items and grid items are not block-level elements. You probably want “boxes that establish a formatting context, block boxes, replaced elements, and “[insert list of internal table/ruby display type you care about]”.

**Comment by fantasai** [comment]
Alternately, “all elements except non-replaced inline boxes, table-column boxes, and table-column-group boxes” (blacklist, rather than whitelist, approach) if that is easier.

**Comment by smfr** [comment]
Is there a master list of all the box types I can consult somewhere? Not sure about the more esoteric things like ruby.
