### ISSUE TITLE
[mediaqueries-5] Detecting "private" hover

### ISSUE THREAD

**Issue by grorg** [w3c/csswg-drafts#9085]
Media Queries has a feature for detecting `hover` capabilities of a device. It distinguishes between `none` (no hover at all) and `hover` (some hover!).

Apple's visionOS has an interaction model that does not give the page any information on the position of the pointer, which is derived from the user's gaze. While this would seem to fall into the `none` category, we have found it important to give the user some feedback on what they are about to interact with. This is implemented with an effect that is rendered by the browser engine and not detectable from the page.

In order to do this, the browser must infer information from the content. In particular what areas of the page are able to be interacted with. We've found through experience that it often requires some tweaks to the design of the page. Here is a video describing the approach and solutions: https://developer.apple.com/videos/play/wwdc2023-10279

For this reason we think we need another value for this media query. We're suggesting `private`, which is a pretty good description of what is happening: the browser is showing a hover effect that is private - only seen by the user, not the page.

Of course, we'd love to hear other suggestions!

**Comment by grorg** [comment]
The pointer on this device is effectively transient. To the page it only exists when it delivers clicks or touches. This isn't the same as a finger though - we found that you still needed some feedback on where you are looking.

**Comment by grorg** [comment]
One flaw here is that it doesn't really tell a developer what they should do about the situation. As I said, we've found instances where a page does want to slightly change its design, but obviously that shouldn't be specific to an Apple device. 

Maybe this is a bit more like the `pointer` query, which has a value of `coarse`.

**Comment by fantasai** [comment]
> Maybe this is a bit more like the pointer query, which has a value of coarse.

Ok, I feel like I have to ask: what's the functional difference (for Web authors) wrt `hover: private` vs `pointer: coarse`? :)

**Comment by fantasai** [comment]
Closing per Dean's instructions.
