### ISSUE TITLE
[css-flexbox] flex-wrap: balance;

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#9086]
With `text-wrap: balance;` becoming available, we’ve had a few requests from authors to have something like `flex-wrap: balance;`

See [this demo right here](https://twitter.com/hypeddev/status/1679171435359617060), which is currently impossible to replicate if it were a flex layout:

https://github.com/w3c/csswg-drafts/assets/213073/7f0ac79e-1b0d-4f24-bded-d263829da290

**Comment by Afif13** [comment]
I can imagine the behavior when dealing with fixed and equal size elements but what about different width elements with a complex flex-grow/flex-basis/flex-shrink configuration?

Will the logic be based on the number of elements (let's try to have the same number on each row) or based on their width (let's try to have the sum of width almost equal on each row)

**Comment by johannesodland** [comment]
There’s already an issue on `flex-wrap: balance`: https://github.com/w3c/csswg-drafts/issues/3070

Could this be a duplicate?

**Comment by bramus** [comment]
Duplicate indeed. Closing.
