### ISSUE TITLE
[css-color-5] Clarification on scaling ranges of color keyword parameters for relative color

### ISSUE THREAD

**Issue by mysteryDate** [w3c/csswg-drafts#9094]
Some web platform tests assume that an alpha of 1, when passed to the lightness channel of `lab`/`lch`, should result in a lightness value of 100:

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-relative-color.html#L420

It appears that the logic for this is that the [0, 1] range for alpha should be mapped onto the [0, 100] range for lightness. I see nothing in the spec stating this should be the case:
https://csswg.sesse.net/css-color-5/#relative-colors
https://csswg.sesse.net/css-color-5/#relative-Lab

In fact, this text seems to imply that numbers are _not_ remapped/normalized:

> Except as specified for individual color functions, (for example, HWB Whiteness and Blackness return [\<percentage\>](https://csswg.sesse.net/css-values-4/#percentage-value)), the [channel keywords](https://csswg.sesse.net/css-color-5/#channel-keyword) return a [\<number\>](https://csswg.sesse.net/css-values-4/#number-value); if they were originally specified as a \<percentage\> or an [\<angle\>](https://csswg.sesse.net/css-values-4/#angle-value), that \<percentage\> is resolved to a \<number\> and the \<angle\> is resolved to a \<number\> of degrees (which is the [canonical unit](https://csswg.sesse.net/css-values-4/#canonical-unit)) in the range [0, 360].

If color keywords inputs _were_ to be mapped to their ranges, many tests are missing from wpt, for example: 
  - Passing `lightness` to other components.
  - Normalizing the `hue` angle.
  - 100% for `a` in `lab` maps to a raw value of 125, should `a` values then be normalized as if they are in the range [0, 125]?
  - The above problem also exists for `oklab`, but with the range [0, 0.4]
  - The interaction of math functions with any of the above.
  
Given that the spec is not explicit about this behavior and it is non-trivial, am I correct in assuming the aforementioned tests are incorrect?

https://github.com/web-platform-tests/wpt/issues/41113

**Comment by romainmenke** [comment]
WPT tests are outdated.

All values are numbers (or hue angles as numbers) and there is no scaling or mapping of ranges.

see : https://github.com/w3c/csswg-drafts/issues/8499

**Comment by svgeesus** [comment]
> Some web platform tests assume that an alpha of 1, when passed to the lightness channel of lab/lch, should result in a lightness value of 100:

Yeah there is no basis for this, and the spec  [warns specifically about assuming this](https://drafts.csswg.org/css-color-5/#ex-no-percentage-magic):

> Beware when using components outside their normal position; when percentages are resolved, there is no "magic scaling" to account for the changed position.
> https://drafts.csswg.org/css-color-5/#ex-no-percentage-magic

So those WPT are wrong.

**Comment by svgeesus** [comment]
Looks like the tests have all been cleaned up (thanks for that!), so this can be closed.
