### ISSUE TITLE
The "Introduction" section of CSS Anchor Exploration is misleading

### ISSUE THREAD

**Issue by mfreed7** [w3c/csswg-drafts#9097]
I'm raising this here on a CSSWG issue because I don't believe there is any other public place to discuss this proposal. It only exists at a private non-comment-able blog post.

I'm speaking about this proposal:

https://fantasai.inkedblade.net/style/specs/css-anchor-exploration/

In the Introduction section of that post, it says:

> This is a rough sketch of ideas. We hope it inspires Google to work with the CSSWG to improve [Anchor Positioning](https://www.w3.org/TR/css-anchor-position-1/) before shipping in Chrome, just as Microsoft worked with the CSSWG to improve Grid Layout into the much-loved system we have today.

That strongly implies that the [existing anchor positioning spec proposal](https://drafts.csswg.org/css-anchor-position-1/) was developed *without* working with the CSSWG somehow. However, we've been working with CSSWG all along:

- We [opened a CSSWG issue](https://github.com/w3c/csswg-drafts/issues/7282) in May, 2022, to start the public brainstorming and discussion. 
- We introduced the proposal at a [live CSSWG meeting on May 25, 2022](https://github.com/w3c/csswg-drafts/issues/7282#issuecomment-1137506735), and actively invited people to comment, get involved, and offer feedback and suggestions.
- We discussed the proposal again [live at CSSWG on September 16, 2022](https://github.com/w3c/csswg-drafts/issues/7282#issuecomment-1137506735).
- We then [discussed various aspects of the proposal in **29+ CSSWG issues**](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue+label%3Acss-anchor-position-1) and adapted the proposal in many, many ways in response to all of this great feedback.
- We requested, and CSSWG resolved, to move the proposal to FPWD [in February 2023](https://lists.w3.org/Archives/Public/www-style/2023Feb/0005.html), and again for good measure [in June 2023](https://lists.w3.org/Archives/Public/www-style/2023Jun/0003.html).

Given these facts, it'd be good to re-word or drop the counterfactual Introduction section. @fantasai @jensimmons @mirisuzanne 

In the meantime, there are several very interesting ideas presented in this new approach, and we appreciate those! We'll need some time to read through them, give them some thought, and come back to the group with some thoughts. If it's possible to make the slides used at the CSSWG F2F public also, that'd be helpful. There were a number of good use case examples in there that we'd like to think about more carefully.

**Comment by kizu** [comment]
I'm joining the request for the slides. I skimmed through the proposal, and some parts are hard to understand without illustrations, especially the tether section. Anything additional to the proposal would help to understand the difference between what is currently implemented in Chrome and what is proposed.

**Comment by kizu** [comment]
Update: just found the slides, from a [mastodon post](https://front-end.social/@jensimmons/110748561449175349):

https://www.icloud.com/keynote/0f5UxcimbeDm24dK6S_Of2YOw#Anchor_positioning_presentation_to_CSSWG

**Comment by fantasai** [comment]
Changed the sentence to

> This is a rough sketch of ideas. We hope it inspires Google to improve [Anchor Positioning](https://www.w3.org/TR/css-anchor-position-1/) before it ships in Chrome.

Let me know if this addresses the concern.

**Comment by mfreed7** [comment]
> Let me know if this addresses the concern.

Yes, I think it does. Thank you for the adjustment. (Also thanks for the ideas on how to improve anchor positioning!)
