### ISSUE TITLE
[css-flexbox] Why is `space-evenly` not included as a value option for `justify-content` and `align-content`?

### ISSUE THREAD

**Issue by codersjj** [w3c/csswg-drafts#9099]
In Flexible Box Layout, `justify-content: space-evenly;` and `align-content: space-evenly;` can be used, so why are they not included as value options in this document?

Here are the relevant links to the spec section: 
https://drafts.csswg.org/css-flexbox/#justify-content-property
https://drafts.csswg.org/css-flexbox/#align-content-property

**Comment by SebastianZ** [comment]
Those definitions were actually moved to https://drafts.csswg.org/css-align-3/#propdef-justify-content and https://drafts.csswg.org/css-align-3/#propdef-align-content, which refer to [`<content-distribution>`](https://drafts.csswg.org/css-align-3/#typedef-content-distribution) that includes `space-evenly`.

So the outdated definitions in CSS Flexbox should actually be removed.

Sebastian

**Comment by codersjj** [comment]
> Those definitions were actually moved to https://drafts.csswg.org/css-align-3/#propdef-justify-content and https://drafts.csswg.org/css-align-3/#propdef-align-content, which refer to [`<content-distribution>`](https://drafts.csswg.org/css-align-3/#typedef-content-distribution) that includes `space-evenly`.
> 
> So the outdated definitions in CSS Flexbox should actually be removed.
> 
> Sebastian

I also saw the relevant definitions in the CSS Box Alignment Module documentation, but what I meant is that the related definitions in the CSS Flexible Box Layout Module should be updated, not removed.:persevere:

**Comment by SelenIT** [comment]
The note [in the section 8](https://drafts.csswg.org/css-flexbox/#alignment) of the Flexbox spec says that a subset of the box alignment properties and values was copied into the Flexbox spec only temporarily, to speed up its development. The CSS Box Alignment spec is supposed to be the single source of truth for the alignment properties and values for all layout mechanisms, and other specs (CSS Flexbox, CSS Grid, etc.) should just refer to it.

**Comment by codersjj** [comment]
> The note [in the section 8](https://drafts.csswg.org/css-flexbox/#alignment) of the Flexbox spec says that a subset of the box alignment properties and values was copied into the Flexbox spec only temporarily, to speed up its development. The CSS Box Alignment spec is supposed to be the single source of truth for the alignment properties and values for all layout mechanisms, and other specs (CSS Flexbox, CSS Grid, etc.) should just refer to it.

It's obvious that I did not read the documentation carefully. Thank you very much, I understand it clearly now.
