### ISSUE TITLE
[css-contain][css-anchor-position] Anchor names should be contained by style containment

### ISSUE THREAD

**Issue by mirisuzanne** [w3c/csswg-drafts#9100]
In a group discussion about scroll animation and the scoping of timeline names, it was mentioned that style containment should likely also contain anchor names. That seems like a clear bugfix - not sure if it needs a resolution.

**Comment by astearns** [comment]
The CSSWG will automatically accept this resolution one week from now if no objections are raised here. Anyone can add an emoji to this comment to express support. If you do not support this resolution, please add a new comment.

Proposed Resolution: Style containment contains anchor names

**Comment by astearns** [comment]
RESOLVED: Style containment contains anchor names
