### ISSUE TITLE
[css-text-4] move "balance | stable | pretty" out of text-wrap

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9102]
While discussing #3473 @fantasai pointed out that the decision of whether to wrap, and of which line breaking algo to use when wrapping ought to be separate, to cascade independently, and therefore to be separate properties.

I agree, and therefore think we should move `balance | stable | pretty` out of `text-wrap`. And likely, that new property is where we should add the new value that solves #3473 (which could be called something like `avoid-oprhans`).

It should be an inherited property.

As for its name, here's a first suggestion to entice people to propose something better: `wrap-style`

**Comment by litherum** [comment]
isn't, like, at least one value of them already shipping?

**Comment by bramus** [comment]
Correct. `text-wrap: balance` shipped in Chrome 114.

https://chromestatus.com/feature/5196960707903488

**Comment by litherum** [comment]
so, like .... 

isn't this impossible?

**Comment by frivoal** [comment]
It was specifically pointed out (by @fantasai ) [during the intent to ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/f5eLz6PIXaI/m/tUoCPTkXAQAJ?utm_medium=email&utm_source=footer) that:

> my concerns are mainly with:
> […]
> c) whether the CSSWG considers this stable enough to ship, or if there are 
unresolved concerns about the design of the feature

@kojiishi 's answer was:

> I understand that the spec is still in early draft, it’s WD, not CR, PR, nor REC. If the spec changes, we can change our implementation accordingly. Even if names were changed or the feature was dropped, not applying `text-wrap: balance` doesn’t cause disasters; it just lays out the same as other browsers

So, while we should not change just for the sake of changing, if there are good reasons to change, my understanding is that Chrome has indicated that this is a risk they were willing to take when shipping early.

**Comment by chrishtr** [comment]
> So, while we should not change just for the sake of changing, if there are good reasons to change, my understanding is that Chrome has indicated that this is a risk they were willing to take when shipping early.

Yes, but there is already [quite a bit](https://chromestatus.com/metrics/css/timeline/popularity/746) of usage in Chromium-based browsers. Making these sites migrate to a new syntax is possible but would need a good enough reason.

I can see why it would make sense to change around `text-wrap` along the lines of what was proposed in this issue, but I don't think it's important enough to cause churn and pain for those developers. To me it  seems like a good thing we could have done, but not that big of a deal to leave it as-is and move on.

For this reason I'm opposed to changing the feature's syntax for the already-shipped values.

**Comment by bramus** [comment]
This seems relevant here: https://github.com/WebKit/WebKit/pull/16723

**Comment by fantasai** [comment]
I agree with @chrishtr that with Chrome having shipped `text-wrap: balance` already, we can't change the name. But we might be able to split these apart anyway, but picking a different name for the `white-space` longhand portion.

**Comment by romainmenke** [comment]
> Yes, but there is already [quite a bit](https://chromestatus.com/metrics/css/timeline/popularity/746) of usage in Chromium-based browsers. Making these sites migrate to a new syntax is possible but would need a good enough reason.

With my css author hat on.

The reason we quickly adopted `text-wrap: balance;` was that is an obvious improvement almost everywhere and it causes no issues in older browsers. You just add it and things look better in latest Chrome but they were never broken elsewhere.

We even added it in a bunch of places before Chrome shipped it in stable because it was so harmless.

I wouldn't mind having to do a find/replace if this was taken out of `text-wrap`.

> churn and pain for those developers

In this specific case I don't think it will cause that.
Nothing will break.

-----

As a maintainer of `postcss-preset-env` and `stylelint` I wouldn't mind making the tools to help other migrate.

**Comment by jfkthame** [comment]
It seems to me that the `balance` value should not be an alternative to `stable | pretty` at all; it's a different type of control.

There are several aspects of wrapping that authors should be able to control independently, something like:

- `text-wrap: wrap | nowrap` -- controls whether wrapping is enabled or not

- `wrap-style: stable | pretty` -- what algorithm to use (should there be an `auto` initial value that lets the UA choose between stable/pretty, potentially based on its own heuristics?)

- `wrap-balance: balance [<number>]` -- asks the UA to try and balance line lengths if the block has no more than `<number>` lines

**Comment by Loirooriol** [comment]
Was `text-wrap-onoff` a placeholder name? It sounds rather weird to me.

**Comment by frivoal** [comment]
Yes, it's a placeholder.

**Comment by frivoal** [comment]
I made the corresponding edits (using a `text-wrap-mode` as the place-holder name: https://github.com/w3c/csswg-drafts/commit/3a1eb8567eee76769d64154f0deba892abdf4360. Feedback welcome.

Will do the corresponding test work shortly.

**Comment by fantasai** [comment]
Agenda+ to bikeshed `text-wrap-mode: wrap | nowrap` longhand (vs `text-wrap-style: stable | balance | pretty | etc.`).

As a reminder the shorthand structure is:
```
text-wrap -> text-wrap-style + text-wrap-mode
white-space -> white-space-collapse + text-wrap-mode
```

This is urgent because implementations are already shipping `text-wrap` as a longhand of `white-space`, and we need the name for `text-wrap-mode` so the rearrangement above can be implemented and shipped ASAP.

**Comment by nt1m** [comment]
I asked property name ideas from ChatGPT, text-wrap-mode was its favourite idea, but it had a couple of other ideas (in no particular order):
- "text-flow"
- "text-wrapping"
- "text-wrap-behavior"
- "text-flow-control"
- "text-wrap-policy"
- "text-wrap-preference"

Not in the list of things ChatGPT suggested, but text-wrap-control might be good.

**Comment by nt1m** [comment]
A few more:
- text-wrap-rule
- text-wrap-allowance
- text-wrap-state

**Comment by jensimmons** [comment]
`text-wrap-behavior` is interesting. 

Although I think Peter had a good reminder, to think about all the other names in CSS, and make sure we are building out a better system, not just another one-off.

**Comment by jensimmons** [comment]
I'm posting questions to Mastodon to see if developers can guess the function of these longhands just from the name (without telling them what each will do): 
https://front-end.social/@jensimmons/111138016628140950

**Comment by LeaVerou** [comment]
Ideas mentioned in the discussion (I’m omitting some GPT ideas that are obviously bad, like e.g. `text-wrap-allowance`):

### Property names

#### Design Notes

- We did vote against making "longhands must start with shorthand + hyphen" a solidified design principle, so we are not bound by it, we can invent a wholly new property name if it improves understandabiity
- Even if we do want to follow the principle, we have two shorthands here that we could use. Starting with `white-space-*` is totally fair game too.
- I don't think we should introduce a whole new prefix, unless we plan to define a new shorthand down the line. E.g. no `text-flow-wrap` without `text-wrap` being a (current or future) shorthand 
- All proposed ideas have focused around enabled being the "active" value and disabled the "negative" value. We should probably explore the design space of properties named after *disabling* wrapping (ensuring to avoid double negatives!). 

#### `text-wrap-*`

* `text-wrap-mode`[^1] (current)
* `text-wrap-enabled`[^2]
* `text-wrap-allow` / `text-wrap-allowed`[^2]
* `text-wrap-policy`[^1]
* `text-wrap-behavior`[^1]
* `text-wrap-preference`[^3]

[^1]: Does not sound like a toggle, but like a way to control the wrapping algorithm (i.e. what `text-wrap-style` does)
[^2]: Binary switch, which we tend to avoid
[^3] Sounds optional, but this property doesn't just *discourage* wrapping, it completely disables it.

#### `white-space-*`

* `white-space-wrap`

#### Not starting with either shorthand

* `text-flow`

### Property values

#### Design Notes

* Obviously not all value pairs go with all possible names
* `wrap | nowrap` have the obvious edge here, as they are consistent with `flex-wrap`, `nowrap` is also consistent with the existing `white-space` values.

#### Value pairs

* `wrap` | `nowrap`
* `auto | never`
* `auto | none`
* `on | off`
* `auto | off`
* `auto | disable`

**Comment by fantasai** [comment]
@LeaVerou My hesitation with `white-space-wrap` is that wrapping is only related to white space in some writing systems, not all of them. In East Asian and Southeast Asian writing systems, for example, wrapping is unrelated to spaces.

**Comment by astearns** [comment]
`text-wrap-allow` seems pretty good to me. Does anyone have a preference for something other than that?

**Comment by jfkthame** [comment]
> `text-wrap-allow` seems pretty good to me. Does anyone have a preference for something other than that?

Seems OK.

With what values? Taking `text-wrap-allow` in isolation, `yes | no` or `on | off` would seem natural; but given that we already have `nowrap` as the "off" value in the `white-space` shorthand, we probably want to keep that the same in the longhand as well.

Then do we use `wrap` for the "on" value? `text-wrap-allow: wrap` feels slightly clumsy, IMO. `normal` would be a possibility (though it's a pity it starts with the same letters as `nowrap`). `auto` is shorter, and reads quite well, I think.

So I'm leaning towards either

     text-wrap-allow: auto | nowrap

or

    text-wrap-allow: wrap | nowrap

where (to my mind) the first reads better, but the second has the advantage of paralleling `flex-wrap`.

**Comment by LeaVerou** [comment]
> @LeaVerou My hesitation with `white-space-wrap` is that wrapping is only related to white space in some writing systems, not all of them. In East Asian and Southeast Asian writing systems, for example, wrapping is unrelated to spaces.

True, but given we already have `white-space`, hasn't this ship sailed?

> > `text-wrap-allow` seems pretty good to me. Does anyone have a preference for something other than that?
> 
> Seems OK.
> 
> With what values? Taking `text-wrap-allow` in isolation, `yes | no` or `on | off` would seem natural; but given that we already have `nowrap` as the "off" value in the `white-space` shorthand, we probably want to keep that the same in the longhand as well.
> 
> Then do we use `wrap` for the "on" value? `text-wrap-allow: wrap` feels slightly clumsy, IMO. `normal` would be a possibility (though it's a pity it starts with the same letters as `nowrap`). `auto` is shorter, and reads quite well, I think.
> 
> So I'm leaning towards either
> 
> ```
>  text-wrap-allow: auto | nowrap
> ```
> 
> or
> 
> ```
> text-wrap-allow: wrap | nowrap
> ```
> 
> where (to my mind) the first reads better, but the second has the advantage of paralleling `flex-wrap`.

I like `auto` for "on", and either `none`, `never`, or `nowrap` for off.

**Comment by nt1m** [comment]
Not a fan that `text-wrap-allow` reflects a boolean. Also I prefer `wrap | nowrap` for paralleling what's already on the web platform.

**Comment by LeaVerou** [comment]
> Not a fan that `text-wrap-allow` reflects a boolean. Also I prefer `wrap | nowrap` for paralleling what's already on the web platform.

So which property name are you a fan of?

**Comment by nt1m** [comment]
Slight preference for `text-wrap-mode` over `text-wrap-allow`.

**Comment by LeaVerou** [comment]
As discussed in the call today, we will try to pilot the [async straw poll process]() in this issue.
In addition to my vote, I've also added usernames for the people who have expressed an explicit preference in the last few comments.

### Async Straw Poll

Please edit this comment, add your at-username next to the option you support and update the count next to it. 

1. Abstain (0): 
2. `text-wrap-allow` (2): @astearns @LeaVerou
3. `text-wrap-mode` (1): @nt1m

**Comment by vmpstr** [comment]
To justify my vote above: `text-wrap-allow: nowrap` to me sounds like "we allow no wrapping" which is a different statement from "we disallow wrapping". Allow in general doesn't sound like an exclusive set unless the keywords sound more boolean like `on` and `off`.

**Comment by LeaVerou** [comment]
> To justify my vote above: `text-wrap-allow: nowrap` to me sounds like "we allow no wrapping" which is a different statement from "we disallow wrapping". Allow in general doesn't sound like an exclusive set unless the keywords sound more boolean like `on` and `off`.

Ouch, that's a pretty good point :/

**Comment by bradkemper** [comment]
I don't see a way to edit the comment, but of the two, I'd prefer `text-wrap-mode: wrap | nowrap`. However, I have a much stronger preference for `white-space-wrap: wrap | nowrap`. People are already used to writing `white-space: nowrap`, in any writing system, and this feels like a simpler mental transition for breaking `wrap|nowrap` into its own property.

**Comment by bradkemper** [comment]
> However, I have a much stronger preference for `white-space-wrap: wrap | nowrap`.

Also, the wrapping still _usually_ only happens where there is white space, so it isn't totally wrong to think of this as a white-space-based property.

**Comment by bradkemper** [comment]
By the way, whatever we call the property, have we considered if `avoid` could be one of the values (i.e. `wrap | no-wrap | avoid-wrap`), instead of having `wrap-inside` as a separate property? It seems to me that `wrap-inside: avoid` is just a slightly relaxed version of `white-space-wrap: nowrap` (or `text-wrap-mode: nowrap`).

**Comment by LeaVerou** [comment]
@bradkemper I edited your vote in, @astearns can we fix the permissions so that Brad can vote in the future?
I also completely agree wrt `white-space-wrap` and I added a note about that for both of us.

+1 for folding `wrap-inside` inside this too.

**Comment by bradkemper** [comment]
@LeaVerou thank you. Should I open a separate issue for folding wrap-inside inside this?

It would mean it would be inheritable, but i think that's better anyway.

**Comment by LeaVerou** [comment]
> @LeaVerou thank you. Should I open a separate issue for folding wrap-inside inside this?

Yes please.

**Comment by bradkemper** [comment]
Done: https://github.com/w3c/csswg-drafts/issues/9448

Also, I have edit power now. Thank you.

**Comment by johannesodland** [comment]
> > However, I have a much stronger preference for `white-space-wrap: wrap | nowrap`.
> 
> Also, the wrapping still _usually_ only happens where there is white space, so it isn't totally wrong to think of this as a white-space-based property.

While the assumption that lines predominantly wrap at white spaces might hold true for English, the proportion of lines wrapping at white spaces can vary significantly from language to language, and even within different types of content.

Take my own language, Norwegian, as an example: we often use long compound words. To ensure proper line endings, it's essential to wrap lines at soft break opportunities within these words. Otherwise, we risk having less than optimal line endings, or “bad rags”. In a casual analysis of a random Norwegian book, I observed that around 20% of the line wraps occurred within words, not at white spaces.

On the web, inputting soft-break characters is quite challenging. This leads to web content in Norwegian (and likely in other languages) often suffering from bad rags. I feel that naming the property `white-space-wrap` could inadvertently perpetuate this bias towards English and neglect the typographical nuances of other languages.

My vote, if I had one, would be for `text-wrap-mode`.

**Comment by bradkemper** [comment]
> On the web, inputting soft-break characters is quite challenging. This leads to web content in Norwegian (and likely in other languages) often suffering from bad rags. I feel that naming the property white-space-wrap could inadvertently perpetuate this bias towards English and neglect the typographical nuances of other languages.

Your point is well taken, but there is little to no chance that we wouldn't consider the needs of non-English languages. We actively work against English bias when designing how the features work. This, to me, is primarily about the name, and whether we make `white-space` (which people are familiar with) into the shorthand that includes `text-wrap` and a wrap-or-not property, or if the new `text-wrap` should be the shorthand, with `white-space` being a sort of alias to it. 

Since we can't go back in time to rename `white-space`, it is more about writing ergonomics to me. I believe the primary use of the `white-space`  has been to write `white-space: nowrap`. It is easier for authors to just add `-mode` to the property name when using its most common value, when they want the space-collapsing behavior to be set separately and inherit separately.

**Comment by yisibl** [comment]
Unfortunately, with Chrome shipping white-space shorthand, once someone uses `white-space: pretty/balance` in Chrome it will be incompatible with the current specification. This is because the implementation in Chrome does not distinguish between `text-wrap-mode` and `text-wrap-style`.

How can we improve this? Do we need Chrome to be updated as soon as possible to match the latest specification?

**Comment by jfkthame** [comment]
> Chrome shipping `white-space` shorthand  ...  `white-space: pretty/balance`

I've just filed https://bugs.chromium.org/p/chromium/issues/detail?id=1501748, as I didn't find an existing bug report about this. It's clearly wrong behavior, and will lead to webcompat pain. 😞

**Comment by yisibl** [comment]
Thanks @jfkthame

**Comment by frivoal** [comment]
Adjusted WPT to make sure that `white-space: balance` and `white-space: pretty` are rejected, as per spec.

**Comment by Findrown** [comment]
> Adjusted WPT to make sure that `white-space: balance` and `white-space: pretty` are rejected, as per spec.
