### ISSUE TITLE
[css-2023] Add !important tiers, such as !important-1, !important-10 like z-indexes

### ISSUE THREAD

**Issue by alexluongfm** [w3c/csswg-drafts#9106]
Add !important tiers to easily allow overriding higher level css with local changes. Where `!important` would default to `!important-1` and higher tiers override lower ones just like z indexes.

More of a quality of life/making life easier change.

**Comment by cdoublev** [comment]
Don't you think that `!important` is often considered as a "code smell" that can now be avoided with `@layer` and `@scope`? And you can still increase the specificity of the selector whose declaration should be more important.

**Comment by tabatkins** [comment]
`!important`, *in general*, shouldn't be heavily used. The [`@layer` rule](https://drafts.csswg.org/css-cascade-5/#layering) is the intended way to handle the sort of specificity conflicts that caused people to overuse `!important` in the past.
