### ISSUE TITLE
[css-transforms-2] Variable `dot` not defined in interpolation of decomposed 3d matrix

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#911]
From https://www.w3.org/Bugs/Public/show_bug.cgi?id=29815: 

In https://drafts.csswg.org/css-transforms/#interpolation-of-decomposed-3d-matrix-values, it says `theta = acos(dot)`. However, `dot` is never defined here.

It probably should be `product`

h/t https://github.com/canaltinova for finding this.

**Comment by dbaron** [comment]
I checked that this agrees with the [relevant Chromium code](https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/geometry/quaternion.cc;l=71-96;drc=d383d0b3e4f76789a6de2a221c61d3531f4c59da).  That checking does require use of the [trigonometric identity](https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Angle_sum_and_difference_identities) for sin(⍺-β).

I'll fix this, and simplify away a "times 1" while I'm there.
