### ISSUE TITLE
[css-nesting] wording `&&` "silly", but useful

### ISSUE THREAD

**Issue by tobymackenzie** [w3c/csswg-drafts#9113]
Not sure if this is the place to bring this up, but:  In the [CSS Nesting spec example 5](https://www.w3.org/TR/css-nesting-1/#example-31845edf), there is an example showing a nested `&&`, describing it as "Again, silly, but can even be doubled up."  The unnested equivalent of that example is:

``` css
.foo { color: blue; }
.foo.foo { padding: 2ch; }
```

It seems less silly when considering that the `.foo.foo` has double the specificity (0-2-0) of the `.foo` selector (0-1-0).  That is a somewhat common technique of increasing specificity without changing anything of the "query" of the selector.  Being able to chain the `&` in a nested selector makes it less verbose and easier to manage this technique, and it might be worth noting this to make it more apparent, or at least dropping the "silly" bit.

**Comment by kizu** [comment]
While this way of handling specificity is very useful ATM, I'm not sure it should be promoted in any way in the specs. Two reasons:

1. Right now, I would always suggest using a `[class]` to bump the specificity of a selector (which usually has a class). This guarantees that changes to the selector won't break the `&&`, and if the preprocessors are involved, can result in a more compact CSS if there are long classNames.

2. Either method of adjusting specificity should go away with time, when we would be comfortable with using `@layer` in our styles and would rely on it more, as using layers is _the_ way to control how things should override each other.

**Comment by tabatkins** [comment]
Yup, specificity hacks can be useful, but aren't recommended in the future. `@layer` is the intended way to handle these sorts of collisions in the futurel

**Comment by tobymackenzie** [comment]
Reasonable.  I see that there is [an issue for supporting that](https://github.com/w3c/csswg-drafts/issues/6323) referenced from the spec, but it is marked as closed.  Is something still planned for supporting this?
