### ISSUE TITLE
[css-contain] unclear about counter() in 'contain: style' context

### ISSUE THREAD

**Issue by danielsakhapov** [w3c/csswg-drafts#9116]
I'm confused a bit about the behavior of content: counter() in the context of 'contain: style'.

The spec [says](https://drafts.csswg.org/css-contain/#example-6932a400):

`However, the counter() and counters() value of the content property is not itself scoped, and can refer to counters established outside of the subtree.`

My interpretation is that we can leave the style containment scope for search of the counter value.
And the example after the text above shows the same.

But the [test](https://wpt.fyi/results/css/css-contain/contain-style-counters-004.html), which all the browsers pass tells the other story, it doesn't allow the access to the reset on body element.

So, my question - is my understanding incorrect? If so, why we can access the 1 for div::before in example, doesn't it cross the style containment boundary?

**Comment by Loirooriol** [comment]
The idea is that you can read across the style containment boundary, but not modify.

**Comment by danielsakhapov** [comment]
Right, but then the wpt test is wrong, isn't it? Counter at div::after should access the 13 from the <body>?

**Comment by Loirooriol** [comment]
TBH the implementations are quite broken (e.g. Blink says 0 for `counter()` but 13 for `counters()`), and the spec seems problematic, see #5175

**Comment by frivoal** [comment]
The test has since been fixed, and the value of the counter on body can indeed be read.

**Comment by frivoal** [comment]
Note: the results of that test might change (for other reasons) depending on the outcome of https://github.com/w3c/csswg-drafts/issues/5175, though current interop suggests that this will remain correct.
