### ISSUE TITLE
[css-borders-4] new `box-shadow` longhands not included in #level-changes

### ISSUE THREAD

**Issue by jsnkuhn** [w3c/csswg-drafts#9122]
The new to CSS borders level 4 individual `box-shadow` properties (`box-shadow-color`, `box-shadow-offset`, `box-shadow-blur`, `box-shadow-spread`, `box-shadow-position`) are not listed in the spec #level-changes section

https://drafts.csswg.org/css-borders-4/#level-changes
https://drafts.csswg.org/css-borders-4/#drop-shadows

**Comment by SebastianZ** [comment]
I know. The changes section still needs to be revised. The `box-shadow-*` longhands are just one part of that. I am going to update it soon.

Sebastian

**Comment by SebastianZ** [comment]
I've updated and corrected the Changes sections of CSS Borders 4 and CSS Backgrounds 4 in https://github.com/w3c/csswg-drafts/pull/9126 including the `box-shadow-*` longhands.

Sebastian
