### ISSUE TITLE
[css-fonts-4] Additional keywords for `font-weight`?

### ISSUE THREAD

**Issue by BenjaminAster** [w3c/csswg-drafts#9128]
Currently, only the numbers `400` (normal) and `700` (bold) have their own [`font-weight`](https://drafts.csswg.org/css-fonts-4/#font-weight-prop) keywords. When wanting to use other font weights (e.g. 600, which is often used as a "not so heavy" alternative to 700/bold), you currently have to use a number for that. I personally think that numbers are very unreadable in this case, especially to newcomers. Seeing a `font-weight: 600` declaration somewhere without knowing the exact "boldness" mappings basically gives no information to the reader, making the DX pretty bad. Would it be feasable to add more keywords to `font-weight` simply as aliases of numbers, e.g.
- `thin` = 100
- `extralight` = 200
- `light` = 300
- `medium` = 500
- `semibold` = 600
- `extrabold` = 800
- `heavy` = 900

**Comment by Loirooriol** [comment]
See #4048

**Comment by BenjaminAster** [comment]
Ah, I didn't see that, thanks!
