### ISSUE TITLE
[css-page-3] Publish an updated WD

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9162]
The current Working Draft is from 2018 and there where [a few substantial changes](https://github.com/w3c/csswg-drafts/commits/main/css-page-3) since then like e.g. the [addition of the `page-orientation` descriptor](https://github.com/w3c/csswg-drafts/commit/82a67e203a336ed8187d0440207aee9a37d8a332).

So I think it should be republished (once the Changes section is updated).

Sebastian

**Comment by svgeesus** [comment]
A little minor cleanup before publication:

- [changes](https://drafts.csswg.org/css-page-3/#changes) needs to be updated
- split Privacy and Security into separate sections

**Comment by fantasai** [comment]
Published: https://www.w3.org/TR/css-page-3/
