### ISSUE TITLE
[css-gcpm-3] Publish an updated WD

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9163]
The published Working Draft of CSS GCPM 3 dates back to 2014. As far as I can see, there were [a lot of](https://github.com/w3c/csswg-drafts/commits/main/css-gcpm-3) [editorial changes](https://github.com/w3c/csswg-drafts/commits/76c77a76dcf0028c495d9f3bec4c8ecff688656a/css-gcpm) and fixes since then and @faceless2 took over as editor.

So I believe it's time to publish an updated version of it.

Sebastian

**Comment by svgeesus** [comment]
+1 to republish. Note that the [list of changes](https://drafts.csswg.org/css-gcpm-3/#changes) needs to be updated first; the changes which removed sections are not editorial. I agree _most_ changes are editorial housekeeping.

**Comment by rachelandrew** [comment]
@svgeesus do you want me to do the changes section? I wasn't clear if you were doing it.

**Comment by faceless2** [comment]
Not at TPAC obviously but was going to ask the same.

**Comment by svgeesus** [comment]
> @svgeesus do you want me to do the changes section? I wasn't clear if you were doing it.

@rachelandrew I was going to do it just to make sure it happened. But if you are up for it, please go ahead!

**Comment by rachelandrew** [comment]
@svgeesus I took a look through the list of outstanding changes, it seems as if the removals of cross references, leaders, and bookmarks sections were already detailed, everything else seems editorial. If I've missed something, let me know, otherwise we can republish the WD.

**Comment by svgeesus** [comment]
Great, thanks for confirming it is up to date.

**Comment by svgeesus** [comment]
Publication requested 22 Jan, expected 25 Jan

**Comment by svgeesus** [comment]
[GCPM 3 published 25 Jan 2024](https://www.w3.org/TR/2024/WD-css-gcpm-3-20240125/)
