### ISSUE TITLE
[motion-1] Publish an updated WD or move to CR

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9165]
Motion Path 1 was last [published in 2018](https://www.w3.org/TR/motion-1/).

At the same time it is part of [Interop 2023](https://wpt.fyi/interop-2023) and received [several substantial changes since then](https://github.com/w3c/fxtf-drafts/commits/main/motion-1), which UAs already started to implement.

Therefore, a new WD should be published. Because it received a bunch of [WPT updates](https://github.com/web-platform-tests/wpt/tree/master/css/motion) and UAs working on interoperability, it may also be moved to CR instead.

Sebastian

**Comment by svgeesus** [comment]
It would be preferable to publish an updated WD soon. Then call for horizontal review.

The, when requesting CR, a recent WD means that it is easier to claim that the spec has had wide review and that the changes between WD and CR are few.

**Comment by astearns** [comment]
ACTION on the editors to ask for wide review once the WD is published

**Comment by svgeesus** [comment]
@fantasai how is publication going?

**Comment by svgeesus** [comment]
So this publication seems to have slipped through the cracks. Meanwhile there have been [lots of updates since 2018](https://github.com/w3c/fxtf-drafts/commits/main/motion-1/Overview.bs). Also @jihyerish  Jihye Hong has changed affiliation to Igalia, and Eric Willigers is no longer in the CSS WG so should be moved to previous editors.

**Comment by svgeesus** [comment]
I [cleaned up the list of editors](https://github.com/w3c/fxtf-drafts/commit/3956ff650d14be8e6d6098ef68ff1885e1514706) but will leave @fantasai to add herself.

**Comment by svgeesus** [comment]
I added [changes since 2018](https://github.com/w3c/fxtf-drafts/commit/61da0d96a2b03c38e59bcf31d7413d50a5e2a4bc)

**Comment by svgeesus** [comment]
> At the same time it is part of [Interop 2023](https://wpt.fyi/interop-2023)

![image](https://github.com/user-attachments/assets/ca773f1c-c91d-41d0-8ed8-41c139153275)

**Comment by svgeesus** [comment]
I added WPT annotations.

**Comment by svgeesus** [comment]
There are currently [11 open issues on motion-1(https://github.com/w3c/fxtf-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Amotion-1) it would be good to address these (or punt them to a future level) before moving to CR

**Comment by svgeesus** [comment]
Publication requested 31 Oct 2024, expected (after publishing moratorium ends) 5 Nov 2024

**Comment by svgeesus** [comment]
[Published 5 Nov 2024](https://www.w3.org/TR/2024/WD-motion-1-20241105/)
