### ISSUE TITLE
[css-anchor-position] Missing letter in example 3

### ISSUE THREAD

**Issue by j9t** [w3c/csswg-drafts#9180]
In [example 3](https://www.w3.org/TR/2023/WD-css-anchor-position-1-20230629/#anchor-default) of the [current CSS Anchor Positioning draft](https://www.w3.org/TR/2023/WD-css-anchor-position-1-20230629/), it seems it should be

```
// Not specified
```

instead of

```
// No  specified
```

**Comment by tabatkins** [comment]
Actually it's `No <anchor-element> specified`, and the `<` wasn't escaped. Fixed.
