### ISSUE TITLE
[css-contain-3] Make `<container-query>` optional in `@container`

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#9192]
Edit: The rationale below is wrong, but the proposal still stands, see https://github.com/w3c/csswg-drafts/issues/9192#issuecomment-1679443058

----

While we have a resolution in https://github.com/w3c/csswg-drafts/issues/7858 to add a function for every container query unit that allow to reference a named container, there is a much more lightweight way that can be implemented right away to make these use cases a little less annoying: making the `<query>` part of container queries optional.

This is real code I had to write yesterday:

```css
@container word-card (width < 100vw) {
	height: min(100cqw / var(--total-aspect-ratio), 40vh);
}
```

The entire reason this container query exists, is to allow me to use `cqw` units for that particular named container. The `(width < 100vw)` query is only there because omitting it would render the rule invalid, as [the spec](https://drafts.csswg.org/css-contain-3/#container-rule) makes this part mandatory. 

```
<container-condition> = [ <container-name> ]? <container-query>
```

Can we just make it optional?

If we’re fine with allowing entirely bare `@container {}` rules, the change could be as simple as:

```
<container-condition> = [ <container-name> ]? <container-query>?
```

if we want at least name OR condition, it [would be](https://drafts.csswg.org/css-values-4/#combinator-multiplier-patterns):

```
<container-condition> = [ <container-name>? <container-query>? ]!
```

**Comment by Loirooriol** [comment]
Note that if you want the condition to be true, `width >= 0` is safer than `width < 100vw`.

Also the grammar would be simpler as `<container-condition> = <container-name> || <container-query>`.

Still, the problem with this proposal is that cq units are not tied to the container query, so even if using `@container word-card`, they can resolve against a different container:

```html
<!DOCTYPE html>
<style>
@container foo (width >= 0) {
  #target {
    width: 100cqw;
    height: 100cqw;
    background: yellow
  }
}
</style>
<div style="width: 200px; border: solid cyan; container: foo / inline-size; --total-aspect-ratio: 1">
  <div style="width: 100px; border: solid magenta; container: bar / inline-size">
    <div id="target"></div>
  </div>
</div>
```

![](https://github.com/w3c/csswg-drafts/assets/7477678/fbb61536-20e1-4bbd-83e6-aaa95c466a51)

The idea is that `cqw(foo)` would allow

![](https://github.com/w3c/csswg-drafts/assets/7477678/bbccdb64-8456-496c-bcf5-4eca9b5f1e0a)

**Comment by LeaVerou** [comment]
> Still, the problem with this proposal is that cq units are not tied to the container query, so even if using `@container word-card`, they can resolve against a different container:

I was not proposing this as an alternative, just as a quick win to make the current situation less painful until `cqw()` and friends can be implemented. And because if `@container name` is useful by itself, it should be allowed.

**Comment by LeaVerou** [comment]
@Loirooriol you are totally right. I'm not sure how in the use case that prompted this I got a different result. I've edited the first post to link to your comment, since I still think making the query part optional would have some (limited) utility.

**Comment by lilles** [comment]
Tests: https://github.com/web-platform-tests/wpt/pull/49093

**Comment by yisibl** [comment]
WebKit has recently added support for this feature.
https://github.com/WebKit/WebKit/pull/54667
