### ISSUE TITLE
[css-anchor-position-1] Allow more properties in position fallbacks

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#9195]
The [current spec](https://drafts.csswg.org/css-anchor-position-1/#accepted-try-properties) only allows inset, sizing and box alignment properties in a `@position-fallback` rule. This doesn't seem enough.

Consider if the first fallback position is horizontally aligned with the anchor, and the next fallback is vertically aligned. We would likely want different margins, borders and paddings.

So I propose adding border, padding and margin properties into the list of allowed properties.

**Comment by xiaochengh** [comment]
After some implementation attempts, it appears that the previous resolution wasn't made with enough care.

Margin properties are fine, but padding and border properties are problematic because they affect the internal layout of the element too much (e.g., intrinsic size, table border collapsing).

Besides, the box alignment properties (other than `justify-self` and `align-self`), which have been allowed since the `@try` rule was first added, also have the same issue.

@bfgeek and I discussed it, and think the only properties that we can safely support now are those affecting only the external geometric constraints of the element, but not anything internal.

(Not until we can properly cascade `@try` rules, which would probably take another year's effort...)

Proposal: Remove padding properties, border properties, and all box-alignment properties except self-alignment properties from position fallback rules. As a result, the remaining allowed rules will be margin, inset, sizing and self-alignment properties.

**Comment by fantasai** [comment]
Current proposal is to accept only:
* [inset properties](https://drafts.csswg.org/css-logical-1/#inset-properties)
* [margin properties](https://drafts.csswg.org/css-box-4/#margin-properties)
* [sizing properties](https://drafts.csswg.org/css-sizing-3/#sizing-property)
* [self-alignment properties](https://drafts.csswg.org/css-align-3/#self-alignment-properties)

**Comment by mfreed7** [comment]
Should be addressed by the current draft spec.
