### ISSUE TITLE
[css-anchor-position-1] Alternative syntax for auto position fallback

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#9196]
The [current spec](https://drafts.csswg.org/css-anchor-position-1/#fallback-automatic) uses `auto` and `auto-same` keywords in the `anchor()` function to create automatic position fallbacks, e.g., `left: anchor(auto); right: auto`.

I think this need to be reworked. Reasons:
- I've heard a lot of complaints that `anchor(auto)` and `anchor(auto-same)` are hard to understand
- `anchor(auto)` uses a special inset value to trigger auto fallbacks, and the generated fallbacks affect inset values only. This will no longer make sense if we allow more properties (like margins) in `@position-fallback`, which I think is likely to happen (see also #9195)

## Proposal

Remove everything about the `auto` and `auto-same` anchor side keywords, and:

### Add a new `position-fallback-auto` property

```
position-fallback-auto: none | flip-block | flip-inline | flip-x | flip-y | flip-both | compass
```

A `none` value means no auto fallbacks are generated.

A `flip-block` value creates a fallback style where, intuitively, all the block-axis values are flipped. Specifically:
- All the `*-block-start` and `*-block-end` property values swapped
- The `align-*` properties are flipped to the other side (e.g., `align-self: start` --> `align-self: end`)
-  In addition, for any `anchor()` function used in the block axis:
   - The anchor side keyword is flipped to the other side (e.g., `inset-block-start: anchor(start)` --> `inset-block-end:anchor(end)`)
   - The anchor percentage is changed to 100% minus that percentage (e.g., `inset-block-start: anchor(30%)` --> `inset-block-end:anchor(70%)`)

The other `flip-*` values for a single axis are similar.

The `flip-both` value creates 3 fallback styles: block axis flipped, inline axis flipped, then both axes flipped.

The `compass` value allows creating fallback positions around the anchor (e.g., top, left, bottom, right). Specifically:
- 1st fallback style swaps the block and inline property values of the base style
- 2nd fallback style is the same "both axes flipped" style as in `flip-both`
- 3rd fallback style swaps the block and inline property values of the previous fallback style

#### Usage in `@try` block

The property can also be used in a `@try` block to create additional fallbacks based on a `@try` block style. This part is similar to the current spec and hence omitted.

### Add new `same` and `opposite` anchor side keywords

The current `auto` and `auto-same` keywords are also useful for non-fallback purposes. For example, `inset: anchor(auto-same)` creates an inset-modified containing block that's the same as the anchor box.

To support this use case, we add `same` and `opposite` anchor side keywords. They are evaluated the same as the current `auto-same` and `auto`, but don't create any fallbacks.

Also, `same` and `opposite` are not swapped in `flip-*` fallbacks.

## Minor discussion topics

- As `flip-both` and `rotate` create multiple fallbacks, maybe we want a syntax to specify the ordering?
- More ways (keywords) to generate fallbacks?

**Comment by tabatkins** [comment]
After putting our heads together, @fantasai and I have this proposal for the "details to be worked out over time":

0. We removed all the automatic magic of creating try options from the spec in #9362, so no fallback options are created unless explicitly.

1. We switched the `position-fallback` property to three associated properties:
    * `position-try-options` which is a comma-separated list of fallback options, either named or generated from the base styles by a transform procedure.
        ```
        position-try-options: 
           none | [ <dashed-ident> | <try-tactic> ]#
        <try-tactic> = flip-block || flip-inline || flip-start
        (initial value: none)
        ```

        The try tactics defined here mirror across the block axis, inline axis, or the start-start to end-end diagonal, respectively.

        We could add "shorthand" keywords here that expand to common sets of options, such as `drop-down` expanding to `flip-inline, flip-block, flip-block flip-inline`, but we're leaving that for later right now.

    * `position-try-order` which specifies how to sort/prioritize the list of options: in specified order, or by largest inset-modified containing block size
        ```
        position-try-order: normal | <try-size>
        <try-size> = most-width | most-height | 
                     most-block-size | most-inline-size
        (initial value: normal)
        ```

    * `position-try-fallback` which specifies what to do if all of the options overflow the inset-modified containing block.
        ```
        position-try-fallback: always || [ first | <try-size> ] | hide
        (initial value: first)
        ```

        By default it'll use the last try-option that worked, and only pay attention to this property if the element is being rendered for the first time. If you specify 'always', it'll instead always use the specified option when they all fail, even if it's different from the last successful option.

        `hide` acts similar to a strong `visibility: hidden` - the element still has a laid-out box and doesn't paint or capture mouse events, but it also doesn't affect scrollable overflow of its container, and can't be overridden on children.

2. We changed `@position-fallback` rules containing `@try` blocks to `@position-try`, which gives a single named style block to reference from `position-try-options`:
    ```
    /* old syntax */
	@position-fallback --foo {
		@try { top: anchor(outside); }
		@try { bottom: anchor(outside); }
	}
	
	/* new syntax */
	@position-try --foo-1 { top: anchor(outside); }
	@position-try --foo-2 { bottom: anchor(outside); }
    ```

3. We added a `position-try` shorthand for convenience
    ```
    position-try: <'position-try-order'>? <'position-try-options'> [, <'position-try-fallback'>? ]
    ```
    For example:
    ```
    position-try: most-width flip-block, flip-block flip-inline, --foo, first;
    ```
    This:
    * specifies three style options (2 auto-generated, one provided by a `@position-try --foo {...}` block) in addition to the base style.
    * sorts all four of these according to which produces the widest inset-modified containing block.
    * if all the options fail on first render, choosing the first one (the widest of the four); on subsequent renders, it uses the most recent successful option (i.e. it tries to be stable).

This system consolidates the fallback system into a single, explicit list, which makes it a lot easier to understand what's happening. Authors who want to package up a particular list can stuff it into a CSS variable.

It also leaves open the possibility of e.g. inlining `inset-area` syntax as one of the `position-try-options` items, similar to the Apple proposal from last July.

**Comment by yisibl** [comment]
Can the new syntax do this easily?

![image](https://github.com/w3c/csswg-drafts/assets/2784308/9d8bc133-9534-4e1b-82d7-15c360312f4f)
![image](https://github.com/w3c/csswg-drafts/assets/2784308/cce5b115-f25a-4bd0-a133-7ab24b08fe60)

Currently, we can used:

```css
.horizontal .tooltip {
  left: anchor(50%);
  top: auto;
  bottom: calc(anchor(top) + 3px);
  justify-self: anchor-center;
}

.vertical .tooltip {
    inset: auto;
    left: calc(anchor(right) + 3px);
    top: calc(anchor(50%));
    align-self: anchor-center;
    justify-self: auto;
}
```

With the current syntax, align-self and justify-self need to be interchanged.

**Comment by tabatkins** [comment]
Well, note that neither of those tooltip positions are compatible with "avoiding overflow", which is the strategy used to decide whether a position is good or not. In fact, they both overflow the input's bounds, and the choice of vertical vs horizontal position seems to have nothing to do with the containing block, either.

So as far as I can tell, the question is moot - that example isn't using fallback at all.

**Comment by mfreed7** [comment]
Should be addressed by the current draft spec.
