### ISSUE TITLE
[css-text-4] split text-wrap: pretty | balance from text-wrap: wrap | nowrap

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9197]
The original intention of the `text-wrap` longhand of `white-space` was to host the `wrap` and `nowrap` values, i.e. control whether or not text wraps.

Along the way we added controls about _how_ it wraps: `balance`, `pretty`. And now people are discussing whether to add more controls here.

But probably the question of *how* something wraps should cascade independently of *whether* it wraps, similar to how `text-justify` is a separate property from `text-align: justify`.

Should we split out these values so that we have:

* white-space
   * white-space-collapse: collapse | preserve | etc.
   * something: wrap | nowrap
* otherthing: normal | balance | pretty | etc.

?

Possible names for these properties (I'm not sold on any of them): `text-wrap`, `line-wrap`, `inline-wrap`, `wrap-style`, `wrap-behavior`, ...

**Comment by fantasai** [comment]
CC @kojiishi

**Comment by chrishtr** [comment]
Hi, is this a dup of #9102?

**Comment by frivoal** [comment]
> Hi, is this a dup of https://github.com/w3c/csswg-drafts/issues/9102?

I'd say it is, yes.
