### ISSUE TITLE
[css-ui-4] influence of outline-width on auto style outlines

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9201]
CSS-UI [claims that](https://drafts.csswg.org/css-ui-4/#outline-style) it's up to user agents to determine whether and how `outline-width` influences the rendering of outlines with `outline-style` auto.

However, this is problematic, for the similar reasons as discussed about color in https://github.com/w3c/csswg-drafts/issues/7761:

`outline: auto` sets `outline-style` to `auto` and `outline-width` to `medium`, and [`medium` means `3px`](https://drafts.csswg.org/css-backgrounds-3/#valdef-line-width-medium).

The default UA sheet in the HTML spec has `:focus-visible { outline: auto; }`, and so, in browsers that want to take `outline-width` into account, it effectively calls for the default rendering of focus outlines to be native outlines *somehow tweaked to be 3px wide*. That seems unfortunate.

I think we should either:
* remove the claim that `outline-width` is allowed to influence the rendering of auto style outlines.
* similarly to what we did in https://github.com/w3c/csswg-drafts/issues/7761, allow `outline-width` to influence the rendering of auto style outlines, but to make that work sensibly, add an `auto` initial value to `outline-width` which computes to `medium` when `outline-style` is anything but `auto`, but lets auto style outlines render at their natural size unless the author has explicitly called for something else.

**Comment by Loirooriol** [comment]
Does any browser let `outline-width` affect the size auto outlines?

**Comment by frivoal** [comment]
As far as I know, neither Safari, Firefox, nor Chrome do it.
As far as my tests could confirm, the only print formatter which does is BFO Publisher.

@faceless2 is this something that matters to you?

**Comment by faceless2** [comment]
If it looks like it might matter to us, it's almost certainly a bug 😁  I thought we simply treated `auto` as `solid` - no impact on width at all.

**Comment by Loirooriol** [comment]
If you treat `auto` as `solid`, then it's normal for it to be affected by `outline-width`. Same for Servo.

I was referring to the native outlines.

**Comment by frivoal** [comment]
Agenda+ to propose removing the claim that `outline-width` is allowed to influence the rendering of auto style outlines

**Comment by Loirooriol** [comment]
I disagree with the test. We (Servo) do not intend to treat `auto` different than `solid` for now, and this is allowed by the spec ("User agents may treat `auto` as `solid`"). `solid` obeys `outline-width`, so we are failing the test.

Please change the test so also accept a different expectation with `div  { outline: solid 100px} div+div { outline: solid 0px }` or such.
