### ISSUE TITLE
[css-color-4] Clarify when to perform the carrying-forward step

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#9220]
https://drafts.csswg.org/css-color/#interpolation-missing

> If any analogous components which are missing components are found, they will be carried forward and re-inserted in the converted color before linear interpolation takes place.

https://drafts.csswg.org/css-color/#interpolation-missing:~:text=Therefore%2C%20the%20carrying%2Dforward%20step%20must%20be%20performed%20before%20any%20powerless%20component%20handling.

> Therefore, the carrying-forward step must be performed before any powerless component handling.

Maybe this would be better, for consistency : 

```diff
If any analogous components which are missing components are found, they will be carried
- forward and re-inserted in the converted color before linear interpolation takes place.
+ forward and re-inserted in the converted color before handling powerless components.
```

------

Unless I am mistaken about the exact content of the `carrying-forward step`.

To my understanding this is when the missing components are re-inserted.

**Comment by romainmenke** [comment]
@svgeesus I think this issue has been resolved by other changes and can be closed.

**Comment by svgeesus** [comment]
Closed by https://github.com/w3c/csswg-drafts/commit/ba2b87bb261410bab5b9e7f8b4f6096625b83820
