### ISSUE TITLE
[css-color-4] `hsl` still has `powerless` hue and saturation when lightness is `0%` or `100%`

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#9221]
https://drafts.csswg.org/css-color-4/#the-hsl-notation

> If the saturation of an HSL color is 0%, then the hue component is powerless. If the lightness of an HSL color is 0% or 100%, the hue component is powerless and the saturation is 0%.

For `oklch` and `lch` this was changed so that only `0` chroma makes `hue` powerless.
Lightness of `0` or `100` is no longer mentioned there

Is it intentional that `hsl` wasn't changed in the same way @svgeesus ?

**Comment by romainmenke** [comment]
@svgeesus could you take a look at this one when you have time?

**Comment by svgeesus** [comment]
> Is it intentional that `hsl` wasn't changed in the same way

Nope, oversight. Thanks once again for your careful eye!
