### ISSUE TITLE
[css-color-4] hue interpolation `longer` when `hue` components are missing

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#9224]
https://drafts.csswg.org/css-color/#hue-interpolation

As far as I could tell it isn't currently defined when the hue angle fixup step should be done.
Only that it should be done before linear interpolation.

The algorithms also don't account for either angle possible being `missing`.

`color-mix(in hsl longer hue, hsl(90deg 50% 50%), hsl(none 50% 50%)`

is this :
- `none` is treated as `0` and `longer` between `90deg` and `0deg` becomes `225deg`
- `none` is replaced with `90deg` before the fixup and becomes `270deg`
- `none` is replaced with `90deg` after the fixup and remains `90deg`

**Comment by romainmenke** [comment]
The same applies in gradients : https://codepen.io/romainmenke/pen/gOZgJNv

WebKit :

<img width="1470" alt="Screenshot 2023-09-08 at 17 09 03" src="https://github.com/w3c/csswg-drafts/assets/11521496/73df9c8e-20ec-4471-94d6-4fa0414f3dd8">

Chromium :

<img width="1470" alt="Screenshot 2023-09-08 at 17 09 14" src="https://github.com/w3c/csswg-drafts/assets/11521496/83941f5e-cf99-4042-bbda-178f4658fb6f">

**Comment by svgeesus** [comment]
> As far as I could tell it isn't currently defined when the hue angle fixup step should be done.
Only that it should be done before linear interpolation.

I think the order could be deduced from the text, such as

>> If a color with a carried forward [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is interpolated with another color which is not missing that component, the missing component is treated as having the other color’s component value.

>> Therefore, the carrying-forward step must be performed before any [powerless component](https://drafts.csswg.org/css-color-4/#powerless-color-component) handling.

but it required a close reading so I have [reworded it into an explicit ordered list](https://drafts.csswg.org/css-color-4/#interpolation) and added the missing steps (premultiplication, and undoing premultiplication):

```html
<ol>
	<li>checking the two colors for [=analogous components=] which will be carried forward</li>
	<li>(if required) converting them to a given color space
			which will be referred to as the <dfn export>interpolation color space</dfn> below</li>
	<li>(if required) re-inserting carried-forward values in the converted colors</li>
	<li>(if required) fixing up the hues, depending on the selected <<hue-interpolation-method>></li>
	<li>changing the color components to premultiplied form</li>
	<li>linearly interpolating each component of the computed value of the color separately</li>
	<li>undoing premultiplication</li>
</ol>
```

So, any carried-forward hues will be re-inserted into the converted colors, before the hue-fix-up stage (otherwise, the required constraints on hue angles would not be met).

Premultiplication [does not affect hues components](https://drafts.csswg.org/css-color-4/#interpolation-alpha).

> `color-mix(in hsl longer hue, hsl(90deg 50% 50%), hsl(none 50% 50%)`

This is 

`none` is replaced (step 3) with `90deg` before the fixup (step 4) and becomes 270deg

**Comment by svgeesus** [comment]
> The same applies in gradients : https://codepen.io/romainmenke/pen/gOZgJNv

WebKit is handling missing hues incorrectly (in general). Blink is handling this case correctly.

**Comment by svgeesus** [comment]
> The algorithms also don't account for either angle possible being `missing`.

I believe they do:

>> If a color with a carried forward [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is interpolated with another color which is not missing that component, the missing component is treated as having the other color’s component value.

>> Therefore, the carrying-forward step must be performed before any [powerless component](https://drafts.csswg.org/css-color-4/#powerless-color-component) handling.

Thus:
- one missing hue - takes the hue from the other color
- two missing hues: both become zero because of powerless component handling

So by the hue fixup stage, there are only numerical values of hue; no `none` remain.

**Comment by romainmenke** [comment]
Thank you, that makes sense to me.

----

Following those steps I get these results :

`longer` :
- `270deg` when mixing `90deg` and `none`
- `180deg` when mixing `none` and `none`

`shorter`, `increasing`, `decreasing`:
- `90deg` when mixing `90deg` and `none`
- `0deg` when mixing `none` and `none`

```css
color-mix(in hsl longer hue, hsl(90deg 50% 50%), hsl(none 50% 50%))
hsl(270deg 50% 50%)

color-mix(in hsl shorter hue, hsl(90deg 50% 50%), hsl(none 50% 50%))
hsl(90deg 50% 50%)

color-mix(in hsl increasing hue, hsl(90deg 50% 50%), hsl(none 50% 50%))
hsl(90deg 50% 50%)

color-mix(in hsl decreasing hue, hsl(90deg 50% 50%), hsl(none 50% 50%))
hsl(90deg 50% 50%)


color-mix(in hsl longer hue, hsl(none 50% 50%), hsl(none 50% 50%))
hsl(180deg 50% 50%)

color-mix(in hsl shorter hue, hsl(none 50% 50%), hsl(none 50% 50%))
hsl(0deg 50% 50%)

color-mix(in hsl increasing hue, hsl(none 50% 50%), hsl(none 50% 50%))
hsl(0deg 50% 50%)

color-mix(in hsl decreasing hue, hsl(none 50% 50%), hsl(none 50% 50%))
hsl(0deg 50% 50%)
```

**Comment by facelessuser** [comment]
@svgeesus So this seems like a surprising revelation. In the past, the resolution of undefined values seemed to be handled during the actual interpolation, not before. Currently, this is exactly how Color.js handles things. Below, we do not get 270deg, but carryforward is also not implemented.

```js
> new Color("hsl(90deg 50% 50%)").mix('hsl(none 50% 50%)', {space: 'hsl', hue: 'longer'});
Color {
  space: <ref *1> ColorSpace {
    id: 'hsl',
    name: 'HSL',
    base: RGBColorSpace {
      id: 'srgb',
      name: 'sRGB',
      base: [RGBColorSpace],
      aliases: undefined,
      fromBase: [Function: fromBase],
      toBase: [Function: toBase],
      coords: [Object],
      white: [Array],
      formats: [Object],
      referred: 'display',
      path: [Array]
    },
    aliases: undefined,
    fromBase: [Function: fromBase],
    toBase: [Function: toBase],
    coords: { h: [Object], s: [Object], l: [Object] },
    white: [ 0.9504559270516716, 1, 1.0890577507598784 ],
    formats: { hsl: [Object], hsla: [Object] },
    referred: undefined,
    path: [ [ColorSpace], [RGBColorSpace], [RGBColorSpace], [Circular *1] ]
  },
  coords: [ 90, 50, 50 ],
  alpha: 1
}
```

But now, the act of carrying forward, which I was under the impression carried forward undefined values only, is also now resolving undefined values with the context of colors before and after it and no longer waiting for interpolation which seemed to be what was implied here?

> If a color with a carried forward [missing component](https://drafts.csswg.org/css-color/#missing-color-component) is interpolated with another color which is not missing that component, the missing component is treated as having the other color’s component value.

Has Color.js always been wrong, or does carryforward fundamentally change this? I have to admit, I can see why browsers may be doing this differently than others. I find it unintuitive that carryforward would resolve the undefined values in this manner.
