### ISSUE TITLE
[css-text] Incorrect statement on normalization of newlines

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#9226]
In [4. White Space Processing & Control Characters](https://drafts.csswg.org/css-text/#white-space-processing) (emphases mine):

> In the case of HTML, each [newline ***sequence*** is normalized](https://html.spec.whatwg.org/multipage/syntax.html#newlines) to a ***single*** line feed (U+000A) for representation in the DOM,[…]

However, [Infra](https://infra.spec.whatwg.org/#normalize-newlines) states that:

> To **normalize newlines** in a string, replace every U+000D CR U+000A LF code point pair with a single U+000A LF code point, and then replace every remaining U+000D CR code point with a U+000A LF code point.

which implies that a sequence of newlines is converted into a *sequence* of line feeds.

**Comment by frivoal** [comment]
Fixed in https://github.com/w3c/csswg-drafts/commit/d5c81eb9859bc9ccc51a594bd9f0de5f7bde076c.

Marking as "testing unnecessary", since this clarification is an editorial clarification to an informative remark as far as this spec is concerned, and HTML/INFRA have their own tests.
