### ISSUE TITLE
[css-text-4] Duplicate in the value definition of `white-space`

### ISSUE THREAD

**Issue by yarusome** [w3c/csswg-drafts#9227]
In [CSS Text 4](https://drafts.csswg.org/css-text-4/#white-space-property), the value of `white-space` is defined as:

```
normal | pre | nowrap | pre-wrap | pre-line | <'white-space-collapse'> || <'text-wrap'> || <'white-space-trim'>
```

But `nowrap` is already included in `<'text-wrap'>`:

```
<'text-wrap'> = wrap | nowrap | balance | stable | pretty
```

**Comment by mhamzanadeem** [comment]
can I work on this issue ?

**Comment by fantasai** [comment]
Done! Thanks for reporting!
