### ISSUE TITLE
[cssom] Should `insertRule()` return or throw a syntax error?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9234]
https://drafts.csswg.org/cssom-1/#dom-cssstylesheet-insertrule

  > 3. Let `parsed rule` be the return value of invoking parse a rule with `rule`.
  > 4. If `parsed rule` is a syntax error, return `parsed rule`.

All mainstream browsers do not return a syntax error but throws a `SyntaxError` `DOMException` when the result of *parse a rule* is a syntax error:

```js
try {
  document.styleSheets[0].insertRule(' ')
} catch (error) {
  error.name // SyntaxError
  error // DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule ' '.
}
```

Furthermore, the Web IDL definition does not allow to return *syntax error*:

```
  unsigned long insertRule(CSSOMString rule, optional unsigned long index = 0);
```

Should the current procedure be updated to this interopable behavior?

**Comment by tabatkins** [comment]
Yeah, that's just an incoherent line. The "syntax error" isn't an reifiable object in any way, just a spec concept to indicate that the parsing failed. It should indeed explicitly throw a SyntaxError DOMException.
