### ISSUE TITLE
[css-viewport-1] Bring the segments property into viewport 

### ISSUE THREAD

**Issue by darktears** [w3c/csswg-drafts#9237]
The `segments` property allows developers to target dual screens and foldable devices by giving information about the segments (or zones) when the browser window is spanned across the screen(s). There is a good set of pictures to demonstrate what we are trying to achieve [here](https://github.com/foldable-devices/demos).

Work was started by Microsoft in WICG to bring a JavaScript API, link [here](https://wicg.github.io/visual-viewport/#dom-visualviewport-segments). The proposed specification adds a `segments` property to the `visualViewport` object. `segments` are only defined when the browser window is maximized. They are also defined in CSS pixels. When the browser window state changes (maximized/resized) one needs to listen for the `resize` events to query the updated `segments`.

Please note that the `segments` property is intended mostly to mirror in JavaScript what’s being available in CSS (see [MQs](https://www.w3.org/TR/mediaqueries-5/#mf-horizontal-viewport-segments)). 

Both APIs, CSS and JavaScript went through TAG reviews [here](https://github.com/w3ctag/design-reviews/issues/689) and [here](https://github.com/w3ctag/design-reviews/issues/690). 

In terms of implementation status, Android and Windows are supported in Chromium based browser (with some caveats). Microsoft Edge does ship the CSS and the JavaScript APIs enabled by default on all platforms. Samsung Internet also is shipping both APIs by default on Android (the only OS they target).

**Comment by tabatkins** [comment]
This seems like a pretty reasonable addition to me. As far as I can tell it's just exposing directly in JS what is already exposed to CSS via the `env()` [viewport segment variables](https://drafts.csswg.org/css-env-1/#viewport-segments), so I can't see any possible concern with this.

**Comment by tabatkins** [comment]
Is this issue asking for review of the `segments` property? Or of the `VisualViewport` class more generally (defined in <https://wicg.github.io/visual-viewport/#dom-visualviewport-segments>). Or is it asking for that spec to be folded into CSSOM? Just unclear what the request for this WG is here.

**Comment by darktears** [comment]
> This seems like a pretty reasonable addition to me. As far as I can tell it's just exposing directly in JS what is already exposed to CSS via the `env()` [viewport segment variables](https://drafts.csswg.org/css-env-1/#viewport-segments), so I can't see any possible concern with this.

You're right, that's exactly this.

**Comment by darktears** [comment]
> Is this issue asking for review of the `segments` property? Or of the `VisualViewport` class more generally (defined in https://wicg.github.io/visual-viewport/#dom-visualviewport-segments). Or is it asking for that spec to be folded into CSSOM? Just unclear what the request for this WG is here.

VisualViewport is already in the CSSOM spec draft (see [here](https://drafts.csswg.org/cssom-view/#visualViewport)). I'm asking to add the `segments` property which isn't there yet.

**Comment by tabatkins** [comment]
Ahhh, I was looking in CSSOM, not CSSOM View (that's a separate spec). Okay, let me just fix the title/labels, I understand now.

**Comment by darktears** [comment]
> Ahhh, I was looking in CSSOM, not CSSOM View (that's a separate spec). Okay, let me just fix the title/labels, I understand now.

My bad, I didn't read carefully the name of the spec.

I'll wait more folks to comment before I put a PR together, especially the editors of the spec.

**Comment by bokand** [comment]
FYI: I moved the visual viewport spec into CSSOM-View but didn't include `segments` since I wasn't sure how widely accepted that was and it was still marked as "experimental". I'm guessing you'd want some support from another engine?

**Comment by darktears** [comment]
@fantasai said 

> Adding new features (or substantially changing existing ones) requires CSSWG approval, not just editor approval... it doesn't seem like https://github.com/w3c/csswg-drafts/issues/9237 has that?

How do I request CSSWG approval on the added property?

**Comment by darktears** [comment]
Summary of the discussions on the PR:
- Exposure to iframes? The CSS MQs are not restricted now (so far, I couldn't find an example where MQs are restricted in iframes). Why this one should be? Developers can still use JavaScript to access the CSS MQ and env() values.
- Should this be part of the VisualViewport API? I think it should, otherwise where?
- Explain more in detail what exactly the FrozenArray of DOMRects returns especially in regard to zooming and panning.
