### ISSUE TITLE
[css-color-5] Does relative colors support current color?

### ISSUE THREAD

**Issue by tiaanl** [w3c/csswg-drafts#9238]
The origin color for the relative color syntax takes a `<color>` so I assume that includes the currentcolor keyword. I don't see a specific mention of this, in the spec but according to wpt (and the implementation in WebKit) currentcolor is not tested/supported.

Most notably if it is supported I guess we should be able to serialize the relative syntax as `rgb(from currentcolor r g b)` and not an already computed color.

**Comment by tabatkins** [comment]
Yup, `currentcolor` is a `<color>` so it should work. If we're lacking tests, that's something that should be fixed.

**Comment by Loirooriol** [comment]
From https://drafts.csswg.org/css-color-5/#resolving-rcs

> Otherwise (if [currentColor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor) was used in the function), the computed value is the Relative Color Syntax function with each `<color>` parameter resolved according to [CSS Color 4 §  14. Resolving `<color>` Values](https://drafts.csswg.org/css-color-4/#resolving-color-values), thus preserving inheritance into child elements.

[nested-color-mix-with-currentcolor.html](https://wpt.fyi/results/css/css-color/nested-color-mix-with-currentcolor.html) is listed as a test, but it's about `color-mix()`, so it should be in https://drafts.csswg.org/css-color-5/#resolving-mix instead?

**Comment by svgeesus** [comment]
[parsing](https://wpt.fyi/results/css/css-color/parsing?label=experimental&label=master&aligned)/[color-computed-relative-color.html](https://wpt.fyi/results/css/css-color/parsing/color-computed-relative-color.html?label=experimental&label=master&aligned) does not test `currentColor`, and should. Same for [parsing](https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&aligned)/[color-valid-relative-color.html](https://wpt.fyi/results/css/css-color/parsing/color-valid-relative-color.html?label=master&label=experimental&aligned)

**Comment by svgeesus** [comment]
> [nested-color-mix-with-currentcolor.html](https://wpt.fyi/results/css/css-color/nested-color-mix-with-currentcolor.html) is listed as a test, but it's about `color-mix()`, so it should be in https://drafts.csswg.org/css-color-5/#resolving-mix instead?

Yes, it should.

**Comment by svgeesus** [comment]
This is covered in [Serializing color-mix() ](https://drafts.csswg.org/css-color-5/#serial-color-mix):

> The serialization of the result of a [color-mix()](https://drafts.csswg.org/css-color-5/#funcdef-color-mix) function depends on whether the keyword [currentColor](https://drafts.csswg.org/css-color-4/#valdef-color-currentcolor) is used in the mix. If so, the result is serialized as the specified value. This allows the correct mixture to be used on child elements whose [color](https://drafts.csswg.org/css-values-5/#valdef-attr-color) property has a different value.)

**Comment by svgeesus** [comment]
[16 `currentColor` in RCS tests which currently, no-one passes](https://wpt.fyi/results/css/css-color?label=master&label=experimental&aligned&q=relative-currentcolor)
