### ISSUE TITLE
[css-box-4] border-radius and border-image should be "border properties"

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#9245]
<https://drafts.csswg.org/css-box-4/#borders> defines the term "border properties", and while it doesn't explicitly list which properties these are, the text implies that it's just the properties set by the 'border' shorthand (-color, -width, -style).

It would be useful to have border-radius and border-image included in this definition, as anything that wants to reference the border properties for some purpose almost certainly wants to reference all of these. (For example, Anchor Positioning was just resolved to allow setting the border properties in fallback styles, and we do indeed intend for -radius and -image to be settable there; there's no good reason to allow setting a border-color but not a border-image.)

**Comment by Loirooriol** [comment]
Note border-image-* are already set by the `border` shorthand

**Comment by tabatkins** [comment]
Ah, you're right, I had forgotten and was going off the textual summary of the border properties in the Box spec.

Still, we could use a more explicit definition of "border properties", and I think it's reasonable to include border-radius in there.

**Comment by fantasai** [comment]
Agenda+ to double-check with the WG that including all the shaping properties (`border-radius`, `corner-shape`, etc.) would make sense here.

**Comment by SelenIT** [comment]
[CSS design mistakes list](https://wiki.csswg.org/ideas/mistakes) states that "`border-radius` should have been `corner-radius`", it seems to make sense since it works without any border. I doubt that including the shape-controlling property into the "border properties" umbrella only because it happened to have "border-" in its name would be a good decision :(

**Comment by fantasai** [comment]
@SelenIT Yeah, I think if we want to go in this direction, it wouldn't be "all border-* properties" but "all properties that affect the size, shape, and rendering of the border area".

But that does leave the 'border-*' properties in the awkward place of not having a dedicated name to refer to them by, so I wonder if we could come up with a new name for the grouping that Tab wants here.

**Comment by tabatkins** [comment]
Even if we *had* named it `corner-radius`, it's still defined in terms of shaping the border box (and then, additionally, the padding and content boxes if necessary), so it's appropriate to include in the "border properties" term imo.

(If the Borders spec specifically needs a term for "the longhand of 'border'" (excluding the radius stuff), well, "the longhands of 'border'" is already a technical term for that grouping. We can dfn it as `'border' longhands` if needed.)

**Comment by GreLI** [comment]
May be it's good idea to add a note, that `border-radius` is not indluded?
