### ISSUE TITLE
[css-fonts-4] Definition of `normal` for font-palette not well-defined or interoperable

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#9281]
https://www.w3.org/TR/css-fonts-4/#font-palette-prop describes the `normal` property value as follows.

> User-Agents attempt to treat the color font as closely as possible to a non-color font. In particular, user-agents use a palette which will yield the best default result for reading. User-agents may take the computed value of the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property into consideration when making this decision. User agents may also construct and use a palette not defined in the font.

I describe below why I find this definition here not well defined and how it lacks interoperability:

### Lack of interop / algorithmic description for discretion of palette choice
* "In particular, user-agents use a palette which will yield the best default result for reading."

Other than with `USABLE_WITH_(LIGHT|DARK)_BACKGROUND` there are not attributes on the palettes in the font that would let the user agent algorythmically choose such a palette. 
https://learn.microsoft.com/en-us/typography/opentype/spec/cpal#palette-type-array

What we can define here is only: "User agents choose the default palette of the color font to render glyphs." 

* "User-agents may take the computed value of the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property into consideration when making this decision. "

Is similarly weakly defined and not helpful or interoperable without an algorithmic description of what should happen. What is the idea here? Should there be some sort of similarity score between a foreground color and a set of palette colors? I suggest to strip this. 

### Lack of interop / algorithmic description for synthetisation of "monochromatic-looking" palette

> "User agents may also construct and use a palette not defined in the font." 

What would be the use case here or how would a user agent be successful with that? Is the idea here to compute a default grayscale palette that matches luminosity of the default color palette of the font?

### Glyph selection preference should be the colored glyph

> "User-Agents attempt to treat the color font as closely as possible to a non-color font." 

I tend to disagree with that. When the font has a color-glyph in `SBIX`, `CBDT/CBLX`, `COLR` or `SVG ` tables, in the spirit of incremental enhancement that glyph should usually be preferred over the monochromatic variant when the UA supports the color font format, as it provides the richer representation. 

There is no useful automatic conversion to a monochromatic glyph from these color glyphs. If the intention is a text representation, the font can either be subsetted to strip color tables, or provide [CMAP format 14](https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#format-14-unicode-variation-sequences) tables with variation sequences to control which glyph should be chosen.

### Glyph choice control available through UVS or should be defined as separate CSS prop

Control over glyph choice i.e. should the rendered glyph come from the `COLR` table or the monochromatic `glyf` table is better controlled by separating the font instances and subsetting the font into two instances, or a separate CSS property for the purpose.

### Proposal

I suggest to reduce the `normal` definition to say:

> User-Agents prefer colored glyphs where available and render the font with the default palette. Monochromatic glyphs should be rendered in the color specified by the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property.

**Comment by drott** [comment]
CC @mdubet @litherum @jfkthame @svgeesus

**Comment by jfkthame** [comment]
> https://www.w3.org/TR/css-fonts-4/#font-palette-prop describes the `normal` property value as follows.
> 
> > User-Agents attempt to treat the color font as closely as possible to a non-color font. In particular, user-agents use a palette which will yield the best default result for reading. User-agents may take the computed value of the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property into consideration when making this decision. User agents may also construct and use a palette not defined in the font.
> 
> I describe below why I find this definition here not well defined and how it lacks interoperability:
> ### Lack of interop / algorithmic description for discretion of palette choice
> 
>  * "In particular, user-agents use a palette which will yield the best default result for reading."
> 
> 
> Other than with `USABLE_WITH_(LIGHT|DARK)_BACKGROUND` there are not attributes on the palettes in the font that would let the user agent algorythmically choose such a palette. https://learn.microsoft.com/en-us/typography/opentype/spec/cpal#palette-type-array
> 
> What we can define here is only: "User agents choose the default palette of the color font to render glyphs."

I'm not necessarily opposed to that simplification, but just trying to understand the intention of the existing text....

"user-agents use a palette which will yield the best default result for reading" -- my assumption is that the UA would choose between palettes tagged "light" and "dark" based on the current background color. So `normal` would behave as `light` if the background is light, and as `dark` if the background is dark. (For some definition of "light" and "dark"....maybe based on levels of luminosity. Maybe only applicable if the background is sufficiently close to the white or black ends of the scale; for mid-range luminosity levels we'd just use the default palette.)

>  * "User-agents may take the computed value of the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property into consideration when making this decision. "
> 
> 
> Is similarly weakly defined and not helpful or interoperable without an algorithmic description of what should happen. What is the idea here? Should there be some sort of similarity score between a foreground color and a set of palette colors? I suggest to strip this.

Possible interpretation: if the computed value of `color` is "light" (again, needs a definition) then choose the palette tagged "dark", and vice versa.

> ### Lack of interop / algorithmic description for synthetisation of "monochromatic-looking" palette
> 
> > "User agents may also construct and use a palette not defined in the font."
> 
> What would be the use case here or how would a user agent be successful with that? Is the idea here to compute a default grayscale palette that matches luminosity of the default color palette of the font?

This seems a bad idea, in general; I can't see how the UA could come up with anything sensible.


> ### Glyph selection preference should be the colored glyph
> 
> > "User-Agents attempt to treat the color font as closely as possible to a non-color font."
> 
> I tend to disagree with that. When the font has a color-glyph in `SBIX`, `CBDT/CBLX`, `COLR` or `SVG ` tables, in the spirit of incremental enhancement that glyph should usually be preferred over the monochromatic variant when the UA supports the color font format, as it provides the richer representation.

+1

**Comment by svgeesus** [comment]
> In particular, user-agents use a palette which will yield the best default result for reading."

That seems weak, and aspirational, and untestable. If the palettes contain the (very minimal) attributes and that data is correct (many fonts have incorrect data, added by tooling or copy-paste) then it is possible that a human would agree that the best choice has been made.

I prefer the simplified version proposed by @drott 

> Possible interpretation: if the computed value of `color` is "light" (again, needs a definition) then choose the palette tagged "dark", and vice versa.

If such a palette exists. Definitions of "light" and "dark" are certainly possible (for example, Oklab L > 0.66 and < 0.33 respectively), and should be coordinated with similar work on `contrast-color`.

>> "User agents may also construct and use a palette not defined in the font."

> What would be the use case here or how would a user agent be successful with that? Is the idea here to compute a default grayscale palette that matches luminosity of the default color palette of the font?

I suspect so (and suggest that a perceptually uniform lightness measure would be better here than luminance (which I suspect is meant: luminosity is a measure of light energy and unrelated to human vision)). In which case the spec should say so.

Alternatively, perhaps it means that a UA stylesheet might contain a palette and the UA will use that. Seems unlikely though as the palette color values and their number will be font-specific.

> "User-Agents attempt to treat the color font as closely as possible to a non-color font."

I don't know what that is trying to say, or how it could be tested.

> User-Agents prefer colored glyphs where available and render the font with the default palette. Monochromatic glyphs should be rendered in the color specified by the [color](https://www.w3.org/TR/css-color-4/#propdef-color) property.

I would be mostly fine with that reduced definition, perhaps with "and _by default_ render the font with the default palette"

**Comment by drott** [comment]
When rephrasing this, we should take #7783 into account, where we've been discussing the interaction with color schemes.

**Comment by svgeesus** [comment]
Talking of preferred glyph selection, I spotted this wording in the intro to [Color Font Support](https://drafts.csswg.org/css-fonts-4/#color-font-support) (my emphasis):

> The [font-palette](https://drafts.csswg.org/css-fonts-4/#propdef-font-palette) property allows selecting one of several different palettes contained in the font, **or alternatively, forcing colored glyphs not to be used**.

_Which_ value forces colored glyphs not to be used? `normal` doesn't do that.

**Comment by svgeesus** [comment]
> User-Agents prefer colored glyphs where available

That applies to all of `normal`, `light` and `dark` though, right? So it should be a general statement, not part of one particular property value.

**Comment by drott** [comment]
> _Which_ value forces colored glyphs not to be used? `normal` doesn't do that.

I think that statement is not correct anymore - perhaps it would have matched the previous definition of `normal` before the edits that I pointed to where it said "User-Agents attempt to treat the color font as closely as possible to a non-color font.". 

> So it should be a general statement, not part of one particular property value.

Yes, I would agree.

**Comment by svgeesus** [comment]
Proposed resolution 1: trim no longer applicable text.

In  [Color Font Support](https://drafts.csswg.org/css-fonts-4/#color-font-support) change
> The [font-palette](https://drafts.csswg.org/css-fonts-4/#propdef-font-palette) property allows selecting one of several different palettes contained in the font, **or alternatively, forcing colored glyphs not to be used**.

to

> The [font-palette](https://drafts.csswg.org/css-fonts-4/#propdef-font-palette) property allows selecting one of several different palettes contained in the font.

Proposed resolution 2: move 

> User-Agents prefer colored glyphs where available

out of the definition of `normal` and make it a general statement in that section.

@drott
