### ISSUE TITLE
[css-backgrounds-3][css-borders-4] Only the principal box should get a shadow

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#9286]
https://drafts.csswg.org/css-backgrounds-3/#shadow-layers, https://drafts.csswg.org/css-borders-4/#shadow-layers

> If an element has multiple boxes, all of them get drop shadows, but shadows are only drawn where borders would also be drawn; see [`box-decoration-break`](https://drafts.csswg.org/css-break-4/#propdef-box-decoration-break).

This is wrong: only the [principal box](https://drafts.csswg.org/css-display-3/#principal-box) should get the shadow. If that box has multiple fragments, then all of them get shadows, according to `box-decoration-break`.

**Comment by Loirooriol** [comment]
As I commented in https://github.com/w3c/csswg-drafts/pull/9296#pullrequestreview-1608524063: I was expecting the behavior to be the principal box since that's the simple choice, but I have tried a table:

```html
<!DOCTYPE html>
<table style="outline: 3px solid cyan; box-shadow: 0 0 0 6px magenta">
  <caption>Tablecaption</caption>
  <tr><td>cell</td></tr>
</table>
```

Both Firefox and Chromium apply the shadow to the table grid box, not to the principal table wrapper box.

So maybe it should be discussed whether this should change? Or say that it's the principal box unless otherwise defined by the relevant spec (https://www.w3.org/TR/CSS21/tables.html#model would imply table grid box, and seemingly https://drafts.csswg.org/css-tables/#global-style-overrides too)

I can't find it now, but I remember some discussion about defaulting properties on a table to apply to the principal wrapper box, with some exceptions that apply to the grid box. Now the default is the grid box, which seems a bit weird.

**Comment by SebastianZ** [comment]
> I can't find it now, but I remember some discussion about defaulting properties on a table to apply to the principal wrapper box, with some exceptions that apply to the grid box. Now the default is the grid box, which seems a bit weird.

https://github.com/w3c/csswg-drafts/issues/324#issuecomment-256482442 and some other comments in that issue indicate that the table wrapper box should be made the default.
@FremyCompany Was this discussed further or even resolved on at some point?

Sebastian

**Comment by FremyCompany** [comment]
I seem to recall that properties default to the grid box. Only when it would not make sense do they apply on the wrapper box. I hate the existence of the two boxes, but I have stopped fighting over it 😂

This is what the spec says at the moment:

> The computed values of properties [position](https://drafts.csswg.org/css-position-3/#propdef-position), [float](https://drafts.csswg.org/css2/#propdef-float), [margin](https://drafts.csswg.org/css-box-4/#propdef-margin)-*, [top](https://www.w3.org/TR/CSS21/visuren.html#propdef-top), [right](https://www.w3.org/TR/CSS21/visuren.html#propdef-right), [bottom](https://www.w3.org/TR/CSS21/visuren.html#propdef-bottom), and [left](https://drafts.csswg.org/css-position-3/#propdef-left) on the table are used on the table-wrapper box and not the table grid box; the same holds true for the properties whose use could force the used value of [transform-style](https://drafts.csswg.org/css-transforms-2/#propdef-transform-style) to flat (see [list](https://drafts.csswg.org/css-transforms-2/#grouping-property-values)) and their shorthands/longhands relatives: this list currently includes [overflow](https://drafts.csswg.org/css-overflow-3/#propdef-overflow), [opacity](https://drafts.csswg.org/css-color-4/#propdef-opacity), [filter](https://drafts.fxtf.org/filter-effects-1/#propdef-filter), [clip](https://drafts.fxtf.org/css-masking-1/#propdef-clip), [clip-path](https://drafts.fxtf.org/css-masking-1/#propdef-clip-path), [isolation](https://drafts.fxtf.org/compositing-2/#propdef-isolation), [mask](https://drafts.fxtf.org/css-masking-1/#propdef-mask)-*, [mix-blend-mode](https://drafts.fxtf.org/compositing-2/#propdef-mix-blend-mode), [transform](https://drafts.csswg.org/css-transforms-1/#propdef-transform)-* and [perspective](https://drafts.csswg.org/css-transforms-2/#propdef-perspective). 
Where the specified values are not applied on the table grid and/or wrapper boxes, the unset values are used instead for that box (inherit or initial, depending on the property).
