### ISSUE TITLE
[css-fonts-4] Which type of font family names are system font names?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9292]
Are they generic family names?

  > There are two types of font family names:
  > 
  > - `<family-name>` [...]
  > - `<generic-family>` [...]

https://drafts.csswg.org/css-fonts-4/#font-family-prop

Or a separate type? About `<family-name>#` in the prelude of `@font-feature-values`:

  > [...] rules that include generic or system fonts in the list of font families are syntax errors

https://drafts.csswg.org/css-fonts-4/#font-feature-values-syntax

FF currently accepts `@font-feature-values caption {}` whereas `caption` is a system font, probably because it wants a `<family-name>` that does not match `<generic-family>`, which does not explicitly include system font names.

---

*aside*

`font-family: caption` is valid, but it has no effect, therefore it maybe a bit misleading to say this:

  > That is why this property is "almost" a shorthand property: system fonts can only be specified with this property, not with `font-family` itself

https://drafts.csswg.org/css-fonts-4/#font-prop

**Comment by cdoublev** [comment]
> About `<family-name>#` in the prelude of `@font-feature-values`:
  > 
  > > [...] rules that include generic or **system fonts** in the list of font families are syntax errors

I suspect *system fonts* should have been replaced by *installed fonts* in https://github.com/w3c/csswg-drafts/commit/e208889cefc2aafbf7b0a007c69c3471a1b387cf, and it should even be entirely removed like in https://github.com/w3c/csswg-drafts/commit/3d1ac3cfd08e8b3a0e2033f1846c8b463999fd77.

But then I wonder if a system font name should be parsed as a valid `<family-name>` in:

  - `font-family` for `@font-face`: there is currently no restriction
  - `font-family` for `@font-palette-values`: generic fonts are currently syntax errors
  - the prelude of `@font-feature-values`: generic fonts (at least) are currently syntax errors

I think `<family-name>` generally excludes generic font names and system font names, but only in `font-family` for a style rule:

  > Any identifier which could be misinterpreted as a pre-defined keyword in the `font-family` value definition, or the CSS-wide keywords, is not allowed.

https://drafts.csswg.org/css-fonts-4/#family-name-syntax

I suspect it should exclude all pre-defined keywords, regardless of the context in which it appears.

**Comment by svgeesus** [comment]
@cdoublev please have a look at

[2.1. Font family: the font-family property](https://drafts.csswg.org/css-fonts-4/#font-family-prop)
and
[2.1.3 Syntax of `<system-family-name>`](https://drafts.csswg.org/css-fonts-4/#system)

to let me know if this is headed in the right direction? I think it is clearer now, defining the three types of font family in one place rather than burying one under the `font` shorthand. I'm not done, but would value a sanity check.

**Comment by cdoublev** [comment]
Looks good, thanks. These clarifications are very helpful.

---

`<<'system-family-name'>>` should be `<<system-family-name>>` in `font` value definition.

I think this is new:

  > `<system-family-name>`: [...] it may not be used with the `font-family` property [...].

But it seems to be matching browser expectations, so I think this is intentional.

**Comment by cdoublev** [comment]
> `<<'system-family-name'>>` should be `<<system-family-name>>` in font value definition.

Can you please fix this? `<<'system-family-name'>>` is referencing an unknown `system-family-name` property.

  > LINK ERROR: No 'property' refs found for 'system-family-name'.

(Bikeshed error report)
