### ISSUE TITLE
[css-fonts-4] Clarify maximum number of `<feature-value-names>` in `character-variant()`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9311]
There it says 2:

  > The character-variant() property value allows two values and styleset() allows an unlimited number.

https://drafts.csswg.org/css-fonts-4/#multi-value-features

But in other places, it says unlimited.

  > **`character-variant(<feature-value-name>#)`**: Enables display of specific character variants [...]

https://drafts.csswg.org/css-fonts-4/#character-variant

  > Example 66:
  >
  > ```
  > p {
  >   font-variant: discretionary-ligatures
  >     character-variant(leo-B, leo-M, leo-N, leo-T, leo-U);
  > }

https://drafts.csswg.org/css-fonts-4/#ex-byzantine-variants

Chrome/FF (at least) accept an unlimited number.

**Comment by svgeesus** [comment]
I don't understand where "allows two values" comes from, it seems clearly wrong.

**Comment by svgeesus** [comment]
Aha, I think this is a mixing up of `character-variant` property and `@character-variant`:

> When two values are listed, the first value indicates the feature used and the second the value passed for that feature. If more than two values are assigned to a given name, a syntax error occurs and the entire feature value definition is ignored.

So the fix is "The `@character-variant` font feature value allows either one or two values"

**Comment by svgeesus** [comment]
Looks like [this was my mistake](https://github.com/w3c/csswg-drafts/commit/5f06f59736d7efe700c083ceb35869bbc883a7bf) when the text was moved from Fonts 3 (which did not use bikeshed) to Fonts 4.

**Comment by cdoublev** [comment]
The text in CSS Fonts 3 was the same. I do not know how to access the old CVS repo to further investigate the initial intent, but I also think that declaration values in `@character-variant` should match `<integer>{2}`; the number of arguments in `character-variant()` is unlimited (there is no `character-variant` property, Bikeshed output `character-variant()` from `'character-variant'`).

**Comment by svgeesus** [comment]
`character-variant` is a value of the [`font-variant-alternates`](https://drafts.csswg.org/css-fonts-4/#propdef-font-variant-alternates) property.

I'm about to push an edit which hopefully clears things up.

**Comment by svgeesus** [comment]
@cdoublev please [take a look](https://drafts.csswg.org/css-fonts-4/#multi-value-features)

**Comment by cdoublev** [comment]
Looks good to me, thank you! So it should be [`character-variant(<feature-value-name>#{2})`](https://drafts.csswg.org/css-fonts-4/#character-variant)?

I was waiting for Tab and Simon answers on how to represent font feature value rules in a production. But now `w3c/webref` can scrap these rule definitions, I think. In this https://github.com/w3c/csswg-drafts/issues/9114#issuecomment-1649700594, I suggested using definition tables, but I am not sure how it could work with these rules. I will keep an eye on this issue.

**Comment by cdoublev** [comment]
I also would like to clarify the expected output when declaring a feature for `@character-variant` with more than two values. Should it be valid but ignored? Or invalid and discarded? For example:

```css
@font-feature-values MM Greek {
  @character-variant { alpha-2: 1 2 3; }
}
```

[`CSSFontFeatureValuesRule.characterVariant.set()`](https://drafts.csswg.org/css-fonts-4/#cssfontfeaturevaluesrule-dfn) requires to throw `InvalidAccessError` so it makes sense to discard it? For example:

Currently, Chrome does not throw this error when using CSSOM, and do not discard it in a stylesheet. Firefox discards it, but does not support `CSSFontFeatureValuesRule.characterVariant` yet. There is no WPT.

I suggest this addition to my suggestion in my previous comment:

  > If more than two values are passed, the feature declaration is [invalid](https://drafts.csswg.org/css-syntax-3/#css-invalid).
