### ISSUE TITLE
[css-fonts-4] Accept all math functions in `@font-palette-values`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9313]
> Functions such as `calc()`, `var()`, and `env()` are valid within the braces of a `@font-palette-values rule`.

https://drafts.csswg.org/css-fonts-4/#at-ruledef-font-palette-values

Obviously, I assume this means they are valid *descriptor values*, not descriptor names. But what is the reason (if any) to only accept `calc()` rather than all math functions?

**Comment by cdoublev** [comment]
Never mind. *Functions such as `calc()`* are valid, which means all math functions are valid, I guess. 

It seems a bit handwavey because I do not think `attr()`, `mix()`, `toggle()`, `random-item()`, should be valid. Maybe *math functions, `var()`, `env()`* should be explicitly allowed, as a restricted set.

**Comment by svgeesus** [comment]
It is a bit wooly, agreed. [Better?](https://github.com/w3c/csswg-drafts/commit/d70e12563eee8e78a434b23dbd2c3f7083a6b66b)

**Comment by cdoublev** [comment]
Satisfied, thanks! :innocent:

Actually [math functions seem to be valid anywhere](https://github.com/w3c/csswg-drafts/issues/8717#issuecomment-1509246256) (sorry to remember it so late) but it does not hurt to allow them explicitly in this context, I guess.
