### ISSUE TITLE
[css-transforms-1] Effect of transforms on background-attachment:fixed

### ISSUE THREAD

**Issue by smfr** [w3c/csswg-drafts#933]
Comment:  http://www.w3.org/mid/42ED583F-AFF2-4D49-B20A-4335C93EEA23@me.com
Response: http://www.w3.org/mid/op.wgl87egg4p7avi@localhost.localdomain
Comment:  http://www.w3.org/mid/CAKA+AxnmG8CynocjdOQR-6WrZDa-uGwGpO74KUMBo0W2x8waWA@mail.gmail.com
Notes:    https://www.w3.org/Bugs/Public/show_bug.cgi?id=15833

**Comment by smfr** [comment]
I think we just need a resolution here.

**Comment by smfr** [comment]
@frivoal do you still have the concerns mentioned in in https://lists.w3.org/Archives/Public/www-style/2012Jun/0674.html, or are you OK with the current spec state?

**Comment by frivoal** [comment]
I am ok with the spec as it is. It's a trade off, and the upsides seem worth it.

**Comment by smfr** [comment]
This was resolved.
