### ISSUE TITLE
[css-anchor-1] Rename `auto` and `auto-same`

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9330]
Trying to decipher anchor(auto) and anchor(auto-same) is dizzying. Can we name them `auto-outside` and `auto-inside` or something?

**Comment by kizu** [comment]
I agree that the `auto` and `auto-same` are hard to understand, and I think the https://github.com/w3c/csswg-drafts/issues/9196 proposes a good alternative of `same` and `opposite` (alongside splitting it from the flipping use case).

**Comment by xiaochengh** [comment]
Yeah, as we already [resolved](https://github.com/w3c/csswg-drafts/issues/9196#issuecomment-1690225805) in #9196, we are going to rename these two keywords and remove auto fallback functionalities from them.

**Comment by fantasai** [comment]
Tab committed this awhile ago, renaming them to `outside` and `inside`, so closing out the issue.
