### ISSUE TITLE
 [css-sizing] Define width:contain

### ISSUE THREAD

**Issue by jetvillegas** [w3c/csswg-drafts#934]
During the 2017-01-13 F2F discussion on CSS Grid issue [523](https://github.com/w3c/csswg-drafts/issues/523) it was proposed that the width property accept a new value 'contain' to enable aspect-ratio-preserving stretching for elements (primarily images) placed in Grid items.

 A proposal (that needs further review) is for the contain-size be the union of:
 min{containing-block-width, max-width}
 min{containing-block-height, max-height}

**Comment by fantasai** [comment]
Drafted in https://drafts.csswg.org/css-sizing-4/#contain-fit-sizing ... reviews welcome. :)
