### ISSUE TITLE
[css-values-4] mix() can not represent retargeted transitions

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#9341]
Say you are transitioning from A to B, and then in the middle of that transition, you retarget to C. If the interpolated values can only be represented with `mix()`, then we'd have `mix(mix(A; B; x%); C; y%)`, which isn't valid.

Can we drop the weird "must be the sole value" and actually give `mix()` a type?

Note: See https://github.com/w3c/css-houdini-drafts/issues/425 for a real example of something that can be transitioned, but not represented.

**Comment by Loirooriol** [comment]
I think that these functions which accept a list of values and behave as one of them should allow the individual values to be things that would normally require to be the sole value.

**Comment by tabatkins** [comment]
Yes, I haven't gotten around to specifying this correctly, but it really should be written as something like `<top-level-value>`, which is only allowed in places that explicitly allow it (such as in `mix()` or as the sole value of a property.

**Comment by tabatkins** [comment]
Okay, defined `<whole-value>` and switched mix() and toggle() to using it.

**Comment by Loirooriol** [comment]
@tabatkins You forgot to replace some `<declaration-value>`:

https://github.com/w3c/csswg-drafts/blob/46b0c7de7009606ecce259004897947be9d20f4e/css-values-5/Overview.bs#L419
https://github.com/w3c/csswg-drafts/blob/46b0c7de7009606ecce259004897947be9d20f4e/css-values-5/Overview.bs#L420
https://github.com/w3c/csswg-drafts/blob/46b0c7de7009606ecce259004897947be9d20f4e/css-values-5/Overview.bs#L430
https://github.com/w3c/csswg-drafts/blob/46b0c7de7009606ecce259004897947be9d20f4e/css-values-5/Overview.bs#L441

**Comment by tabatkins** [comment]
Ah thanks, fixed.
