### ISSUE TITLE
[css-contain][css-anchor-position-1] Should size/layout containment also contain anchor names?

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#9349]
In #9100 we resolved that style containment should contain anchor names. 

The containment spec, non-normatively says the following about the size containment:

> When paired with [layout containment](https://drafts.csswg.org/css-contain-2/#layout-containment), though, possible optimizations that can be enabled include (but are not limited to):
> * When the style or contents of a descendant of the [containment box](https://drafts.csswg.org/css-contain-2/#size-containment-box) is changed, calculating what part of the DOM tree is "dirtied" and might need to be re-laid out can stop at the containment box.
> * When laying out the page, if the [containment box](https://drafts.csswg.org/css-contain-2/#size-containment-box) is off-screen or obscured, the layout of its contents (i.e. "[laying out in-place](https://drafts.csswg.org/css-contain-2/#laying-out-in-place)") can be delayed or done at a lower priority.

I don't believe these optimizations would hold if anchor names are not contained by size or layout containment.

I was thinking about this in context of content-visibility, which would need to contain anchor names in some way, but it also sets style containment so #9100 should be enough to satisfy that concern.

**Comment by tabatkins** [comment]
Layout containment seems like an obvious yes - if we didn't have it contain anchor names, it would defeat the optimizations that layout containment is meant to enable. This is similar to how layout containment prevents you from seeing baselines inside the content.

Size containment seems like an obvious no - size containment just breaks parent/child layout cycles, but doesn't let us actually skip any meaningful work in the general case. Note that size containment *specifically* calls out baseline alignment as something it *does not* stop.

So I suggest we add layout containment to the list of things that scope anchor names, but do not add size containment.
