### ISSUE TITLE
[css-view-transitions-1] Limiting the feature to HTML

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#9357]
The [spec](https://drafts.csswg.org/css-view-transitions-1/) currently describes the feature as being agnostic to the type of document. We use style sheets that are `:root` etc. I think this is great, but we don't know of any implementations planning to support anything other than html. Specifically, since we don't have implementation experience for other document types, we don't know whether all of the features in the spec can be implemented there (does xml have pseudo elements?)

I propose specifically mentioning that this must be supported for html documents, and browser may support this for other document types. Either that, or just flat out limiting this to html? I don't really know of use cases targeting any other document type. Are there compelling use-cases?

**Comment by zcorpan** [comment]
Any document type that can be loaded into a browsing context can also be navigated. An SVG doc can also have CSS styles even without using any HTML elements, and can have links that can cause navigation. I don't know if view transitions work for SVG elements, but you can also have HTML (or MathML) elements in SVG.

Also, if it's limited to "HTML documents", then that excludes XHTML, which seems unnecessary/bad.

HTML's rendering section already says how to handle "unstyled XML", where the UA stylesheet doesn't apply at all: https://html.spec.whatwg.org/multipage/rendering.html#unstyled-xml-documents

So I think having any-namespace rules in the UA stylesheet is fine. There's also precedent for that with fullscreen: https://fullscreen.spec.whatwg.org/#user-agent-level-style-sheet-defaults

**Comment by vmpstr** [comment]
Sounds good. We also discussed this offline a bit and agree that we should keep supporting all document types.
