### ISSUE TITLE
[css-values] Value of rem when document have no root element

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#936]
It is not specced that what should happen when there is no root element in a document, and one tries to compute value of `rem` unit.

For example given the following code:
```html
<!DOCTYPE html>
<iframe src="about:blank"></iframe>
<script>
  window.onload = function() {
    var win = document.querySelector('iframe').contentWindow;
    var doc = document.querySelector('iframe').contentDocument;
    var b = doc.body;
    doc.documentElement.style.fontSize = '24px';
    b.style.lineHeight = '2rem';
    doc.removeChild(doc.documentElement);
    alert('line-height: ' + win.getComputedStyle(b).lineHeight);
  };
</script>
```

Gecko and Edge shows `48px`, and Blink shows empty.

**Comment by tabatkins** [comment]
Fixed now - we folded the root-finding into the same bit as the parent-finding (for 'em' in 'font-size'), and so if there is no root, it ends up looking at the initial values.
