### ISSUE TITLE
[css-anchor-positioning-1] implied auto try blocks are confusing

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9362]
Example 9 in the spec https://www.w3.org/TR/css-anchor-position/#fallback-automatic shows off a "feature" that's super confusing to understand. The code doesn't make sense when you look at it. I understand @xiaochengh's suggestion of having specifying a fallback strategy, but having an implied `@try` blocks generated as "mirror images" of an existing try block because it happens to have an `auto` keyword in one particularly magic place is too much magic.

**Comment by xiaochengh** [comment]
We've also addressed that in #9196's [resolution](https://github.com/w3c/csswg-drafts/issues/9196#issuecomment-1690225805): we'll get rid of `auto` and `auto-same` completely and use a standalone property to generate auto fallbacks.

So I don't think we have any work to do in this issue. Can we close it?
