### ISSUE TITLE
[css-view-transitions-1] Add a11y text to specify how VT works with it

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#9365]
We've had an [early review](https://github.com/w3c/a11y-request/issues/44) for a11y with recommendations to ignore the generated view transition pseudo tree for the purposes of a11y. We should capture that in the spec

We also need to discuss the text in [view transition spec](https://drafts.csswg.org/css-view-transitions-1/#view-transition-stacking-layer) that currently says:

> When a [Document](https://dom.spec.whatwg.org/#document)'s [active view transition](https://drafts.csswg.org/css-view-transitions-1/#document-active-view-transition)'s [phase](https://drafts.csswg.org/css-view-transitions-1/#viewtransition-phase) is "animating", the boxes generated by any element in that [Document](https://dom.spec.whatwg.org/#document) with [captured in a view transition](https://drafts.csswg.org/css-view-transitions-1/#captured-in-a-view-transition) are [invisible](https://drafts.csswg.org/css-display-4/#invisible).

I don't think we want it to say invisible, since 1. it's contents are visible via the pseudo elements and 2., invisible elements means, among other things, that the elements
> are also not rendered to speech (except when [speak](https://drafts.csswg.org/css-speech-1/#propdef-speak) is [always](https://drafts.csswg.org/css-speech-1/#valdef-speak-always) [[CSS-SPEECH-1]](https://drafts.csswg.org/css-display-4/#biblio-css-speech-1))

We'd like those to be available to a11y since otherwise the content would not be available to speech in any way

**Comment by khushalsagar** [comment]
FWIW, this text was changed in https://github.com/w3c/csswg-drafts/pull/9028.

Our goal is to say that elements being snapshotted for a transition don't paint (because we steal their snapshot and show them in the pseudo-elements) and are not interactive. The latter because the hit-test would resolve on the element even though its not painting at that location.

The earlier text lined up better with this intent:

```
The [=new element=] and its contents
(the flat tree descendants of the element, including both text and elements, or the replaced content of a replaced element),
except the |transition|'s [=ViewTransition/transition root pseudo-element=]'s [=tree/inclusive descendants=],
are not painted (as if they had ''visibility: hidden'')
and do not respond to hit-testing (as if they had pointer-events: none) until |new| exists.
```
