### ISSUE TITLE
System Colors should explicitly allow for spoofing

### ISSUE THREAD

**Issue by annevk** [w3c/csswg-drafts#9373]
https://www.w3.org/TR/css-color-4/#css-system-colors is not exactly clear that a user agent can, for privacy reasons, decide not to expose a particular color to avoid the end user being targeted or fingerprinted through that color.

**Comment by emilio** [comment]
cc @svgeesus (see discussion in https://github.com/WebKit/standards-positions/issues/136 for context)

**Comment by svgeesus** [comment]
@emilio thanks!

@annevk wrote:

> Given that we seem to reach different conclusions reading the same specification I opted to file https://github.com/w3c/csswg-drafts/issues/9373.

So there is currently no consensus on how to approach this? Some people want to return hard-coded values (which are then useless and misleading, eg in `color-mix()` others want an `@supports` query to return false (meaning the OS is not going to tell them what the color is) which does seem more reasonable but may not be Web-compatible.

**Comment by emilio** [comment]
I think implementor wise the consensus is the former. They're not useless, they just don't expose the OS preference directly. It's still an accent color for example.

**Comment by emilio** [comment]
Yeah that sounds good.

**Comment by annevk** [comment]
Thanks, that sounds good to me as well. And I agree that it should still allow for testing and still allows web developers to use them in useful ways.
