### ISSUE TITLE
[mediaqueries] Consider `@media supports()`

### ISSUE THREAD

**Issue by zcorpan** [w3c/csswg-drafts#9375]
See https://github.com/whatwg/html/issues/7540#issuecomment-1722080008 and following comments

@zcorpan 

> I think if we want `supports()` to apply to all `media=""` attributes, it should be part of MQ. But processing a media query list instead returns two booleans (supports result, MQ result), so that we can avoid fetching stylesheets where supports is false but do load them when supports is true (regardless of the MQ result).
> 
> This would make `supports()` consistently available (`Link` header, various HTML elements, `@import`, `@media`, constructable stylesheets options bag). Also makes the integration for HTML simpler, and less surgery needed in CSSOM. See [w3c/csswg-drafts#9361](https://github.com/w3c/csswg-drafts/issues/9361)
> 
> Maybe the `supportsText` for `CSSImportRule` wouldn't be needed anymore if it's part of the `MediaList`.

@emilio 

> @zcorpan what does that give you that renaming [this](https://drafts.csswg.org/css-cascade-5/#typedef-import-conditions) to `<style-sheet-condition>` or so and referencing that everywhere doesn't?
> 
> With your proposal it feels rather weird to be able to do `@media supports()`, and you'd need to track the "supports" result across the whole condition tree, which is a bit odd. So we'd need to convert the media query evaluation to track not only true/false/unknown as it does now, but something like always-true/always-false/true/false/unknown.
> 
> To be clear, I think that's doable, but it's probably less straight-forward than the alternative?

@zcorpan 

> I guess my main concern is consistency for web developers about where `supports()` works, and how to expose it in the CSSOM. So maybe first we need to decide whether `@media supports()` should be a thing.

**Comment by romainmenke** [comment]
Also important to take any future conditions into account.
At this time `scope()` is also accepted to be added as an import condition.

So `@media (scope(...))` should then also be a thing.

**Comment by zcorpan** [comment]
For HTML we're reconsidering whether to use `supports()` in the `media` attribute, and may instead use a separate `supports` attribute. See https://github.com/whatwg/html/issues/7540#issuecomment-1725024079

**Comment by mirisuzanne** [comment]
> At this time scope() is also accepted to be added as an import condition.

Not quite. The `scope()` feature is planned as an addition to CSS imports alongside `layer()`, but they are not part of the '[import-condition](https://drafts.csswg.org/css-cascade-5/#typedef-import-conditions)' production. Scope and layer don't determine _if_ the style sheet should be applied, but rather _how_ it is applied.

---

To summarize the two options being discussed: in both cases, `layer` and `scope` and other import modifiers can be added to HTML as new attributes. The issue then is giving authors a way to add support-conditions while those new attributes are poorly supported. For that, we need a way to define support queries in HTML.

1. If we want these support conditions to work on browsers that pre-date the new syntax, then we need to build on an existing conditional attribute. We've discussed `rel` and `type`, but `media` seems to me like a clear winner. It might not be the ideal name for the thing, but it's also not an arbitrary mix of features – we would be defining the 'media' attribute to use the CSS 'import-condition' syntax. It's a syntax production that already exists in a well-defined space, and it already combines both media and support. But that's a tradeoff. How much do we care about failing the import in legacy browsers?
2. Alternately, we can decide (as the WHATWG suggests) that the legacy support issue is temporary, and in the long term we would prefer to have distinct attributes for each type of import condition. The `media` attribute continues to be media-specific, and we add a `supports` attribute. For now, authors will need to polyfill that supports attribute, but that's entirely possible with a little bit of JS, but down the road we get a more clear syntax.

I think either option is a fairly reasonable tradeoff, depending what we want to prioritize. Option 1 gives us better legacy support. Option 2 is a cleaner syntax, but less useful in the short-term.

Looking ahead 5 years, I think the WHATWG is probably right that we don't need to overthink the transition period. Let's go with the cleaner separation of new attributes (option 2). The polyfill would be light-weight and temporary.

**Comment by bramus** [comment]
I’d rather see option 1 land, as with 2 we’ll have the same problem again whenever some new condition gets introduced.

Say – for some weird reason – a `dayofweek` condition gets added. We’d then need a new attribute for it and we’d be doing this whole dance all over again.

---

Taking a step back, you could say the following, since they’re all conditions:

- `@supports` translates to `@if supports(…)`
- `@media` translates to `@if media(…)`
- `@media (prefers-* …)` translates to `@if prefers(…)`

Say there wasn’t any way yet to apply these conditions via HTML yet, I’d come up with a `[condition]` attribute.

```html
condition="supports(…) prefers(…)"
condition="media(…)"
condition="dayofweek(…)" 🤪
```

Lacking such an attribute today, we could reuse `[media]` _(which might need a rename over time?)_ for it instead?

```html
media="supports(…) prefers(…)"
media="media(…)"
```

And yes, `media="media(…)"` is redundant, but over time `[media]` would get renamed to `[condition]` in what I’m suggesting – I see a period of time where UAs would support both to then eventually deprecate `[media]`.

**Comment by zcorpan** [comment]
I would be ok with adding a `condition` attribute and use a CSS-defined import condition, separately from the `media` attribute. This would make it easier to extend import conditions with new things in the future since HTML and CSSOM wouldn't need to be changed again. I like it, actually! Let's call this Option 3.

I don't think extending the `media` attribute is good long-term, nor is having two attributes with the same processing.

**Comment by bramus** [comment]
> I don't think extending the media attribute is good long-term, nor is having two attributes with the same processing.

My suggestion is to make them aliases for a while and then eventually deprecate `media` in favor of the `condition` name.

This to plug the time period in which browsers that don't understand `[condition]` would erroneously load the linked to file.

**Comment by mirisuzanne** [comment]
That approach makes sense to me. To clarify: media queries would be allowed in both the existing `media` attribute and the new `condition="media()"` function (since that function is part of the css `import-condition`? I think that would be better than trying to exclude media conditions from the new `condition` attribute - even though it does allow for some duplication.

**Comment by mirisuzanne** [comment]
I tagged this as closed accepted by resolution. I'm not sure there's anything left to do here on the CSS side. We may also be able to close the issue? This is a signal of CSSWG support for a particular resolution of whatwg/html#7540

The secondary discussion topic that came up is _how should `media` and `condition` attributes interact when both are specified?_ Do we need a new issue in the CSSWG for that, or can that be explored on the WHATWG issue?

**Comment by valtlai** [comment]
I’m not sure, but would `when` be a better name? It would be consistent with the [`@when` at-rule](https://www.w3.org/TR/css-conditional-5/#when-rule) which takes similar (or the same?) syntax.

**Comment by valtlai** [comment]
Okay, I copied the comment there.

**Comment by zcorpan** [comment]
Thanks all. I think we can close this issue with the resolution
> RESOLVED: Do not add `supports()` to @media.

What to do when both are specified was discussed in the HTML issue iirc (failed condition means don't load, no-match media means load but don't apply).
