### ISSUE TITLE
[css-text-4] How to handle `<string>` in `text-align`?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9386]
Should it set `text-align-all`?

  > **Name:** `text-align`
  > **Value:** `start | end | left | right | center | <string> | justify | match-parent | justify-all`
  >
  > This shorthand property sets the `text-align-all` and `text-align-last` properties [...]. Values other than `justify-all` or `match-parent` are assigned to `text-align-all` and reset `text-align-last` to `auto`.

https://drafts.csswg.org/css-text-4/#propdef-text-align

None of the longhands accept `<string>`.

**Comment by Loirooriol** [comment]
The quote implies that `text-align-all` needs to accept `<string>`.
`text-align-last` might accept it too, but it wouldn't make much sense to me.

**Comment by frivoal** [comment]
RIght. This is clearly a spec bug. Values in shorthand with no correspondence in longhands don't make sense.

The intent is clear from this sentence:

> Values other than `justify-all` or `match-parent` are assigned to `text-align-all` and reset `text-align-last` to `auto`.

`<string>` needs to be added to `text-align-all`. Did so in https://github.com/w3c/csswg-drafts/commit/8475bad28d93127fc3e7ba20e0afa69ad10ba70b
