### ISSUE TITLE
[css-fonts] Interaction between font-synthesis-style and variable fonts

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9391]
[The definition of font-synthesis-style](https://drafts.csswg.org/css-fonts-4/#font-synthesis-style) says:

> This property controls whether user agents are allowed to synthesize oblique font faces when a font family lacks oblique faces.

But step 3 of "If the value of font-style is oblique[…]" in [Matching font styles](https://drafts.csswg.org/css-fonts-4/#font-style-matching) says:

> If font-synthesis-style has the value auto, then for variable fonts with a slnt axis a match is created by setting the slnt value with the specified oblique value; otherwise, a fallback match is produced by geometric shearing to the specified oblique value.

Which means that `font-synthesis-style: none` not only turns off browser synthesis of oblique fonts, but also usage of the slnt axis in variable fonts that have it. This is unexpected: the definition of font-synthesis-style talks about its effects when a font family lacks oblique faces, but variable fonts with a slnt axis don't lack oblique, they have a whole range of them. I don't think we should talk about synthesis when the user agent is rendering a font as designed by the font designer.

I'd suggest splitting this step 3 into two distinct ones:
3.1. For variable fonts with a slnt axis, a match is created by setting the slnt value with the specified oblique value.
3.2 If font-synthesis-style has the value auto, a fallback match is produced by geometric shearing to the specified oblique value

**Comment by svgeesus** [comment]
Good catch and, I suspect, not an intended outcome.

**Comment by svgeesus** [comment]
Related: [Testing browser support for slnt and ital axes in variable fonts](https://arrowtype.github.io/vf-slnt-test/)

also

 - https://github.com/w3c/csswg-drafts/issues/3125

**Comment by svgeesus** [comment]
Re-reading this, there seems to be an assumption that geometric shearing and the use of a `slnt` axis are equivalently "synthesis" and equally undesirable. Which is false; the former (faux-oblique) is manipulating the glyph outlines in a way not intended by the font designer while the latter is using a feature provided by the font designer, for the intended purpose.

The edit suggestions are good, but I think that needs to be tightened up (for all the `font-synthesis-*` properties) first.

**Comment by svgeesus** [comment]
@frivoal do these edits address your comment, or is there more to do?

**Comment by svgeesus** [comment]
ping @frivoal
