### ISSUE TITLE
[css-images-4][css-color-5] color-mix() and cross-fade() have different serialization order?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9405]
```
color-mix() = color-mix( <color-interpolation-method> , [ <color> && <percentage [0,100]>? ]#{2})
```
```
cross-fade() = cross-fade( <cf-image># )
<cf-image> = <percentage [0,100]>? && [ <image> | <color> ]
```

The `color-mix()` and `cross-fade()` functions have different grammar orders wrt progress and value, they should probably be synchronized.

**Comment by svgeesus** [comment]
I could make a PR to change cross-fade to conform to the (now widely implemented) `color-mix` serialization order, but:

- is it worth doing?
- are these strictly comparable?

If it is just flipping the order to 

```css
<cf-image> =  [ <image> | <color> ] && <percentage [0,100]>?
```

then maybe that is helpful, but what about the missing `<color-interpolation-method>`? It looks like CSS Images 4 [cross-fade](https://drafts.csswg.org/css-images-4/#cross-fade-function) doesn't discuss what colorspace is used for calculation _at all_. And there are seemingly [no tests](https://wpt.fyi/results/css/css-images?label=experimental&label=master&aligned)?

**Comment by svgeesus** [comment]
Ah, seems I was wrong. It *is* specified, and [calculating in gamma-encoded sRGB is the (only) option](https://drafts.csswg.org/css-images-4/#cross-fade-painting).

> For the purpose of this calculation, each pixel’s color must be in pre-multiplied sRGB.

**Comment by fantasai** [comment]
We probably do want to extend `cross-fade()` to take more arguments controlling interpolation (and maybe you might file a separate issue on that :), but at the very least their syntax should be consistent to the extent that they overlap.

**Comment by svgeesus** [comment]
Three months ago I asked:

> BTW are we talking about changing the syntax in the spec, or [the -webkit- syntax that is actually implemented](https://caniuse.com/css-cross-fade), or both?

This matters, and I have not seen an answer.

The syntax in the spec can be changed (and should be easy to change as no-one implements it).

The syntax that is implemented, complete with `-webkit-` prefix is different, and can't be changed because it is a WebKit compatibility feature.
