### ISSUE TITLE
[css-fonts-4] `<generic-family>` should not accept `<string>` and unrestricted `<custom-ident>+`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9410]
Follow-up on https://github.com/w3c/csswg-drafts/issues/6770#issuecomment-1724819811.

[`<generic-family>`](https://drafts.csswg.org/css-fonts-4/#generic-family-value) went from accepting a restricted list of keywords (generic family names) to accepting either `generic(<custom-ident>+)`, `<string>`, or (unrestricted) `<custom-ident>+`.

But from reading across the issue, I suspect the intent was for it to only acquire `generic(<custom-ident>+)`. Therefore in the comment, I suggested `<generic-family> = generic(<custom-ident>+) | <generic-family-name>`.

[Generic family names](https://drafts.csswg.org/css-fonts-4/#generic-font-families) would be defined `for` `<generic-family-name>` (to allow deriving `<generic-family-name> = serif | sans-serif | ...` from [scraped `<dfn>`s](https://github.com/w3c/webref/blob/3ffa174372ec26eb57143d45c638f51718ea0f84/ed/css/css-fonts.json#L1281-L1365)).

**Comment by svgeesus** [comment]
It should really have been `generic(<custom-ident>)` i.e. a single identifier inside the function. Like `generic(kai)`

But there is a need to do two things: define the syntax for the function, in general, and also define the current list of generic font families. The older ones don't use the functional syntax while the new ones will.

**Comment by svgeesus** [comment]
Relevant on `string` or not:

 - https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-621943691
 - https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-621945054

**Comment by cdoublev** [comment]
Fixed by https://github.com/w3c/csswg-drafts/commit/69f7f7ac1e3eb2ad074edb92bae04d2014bd3612.
