### ISSUE TITLE
[cssom-1] `CSSStyleDeclaration.getPropertyPriority()` for resolved values

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9421]
https://drafts.csswg.org/cssom-1/#dom-cssstyledeclaration-getpropertypriority

Should it return empty string when the computed flag is set, like in Chrome/FF (at least)?

```html
<style>#target { color: red !important }</style>
<script>
  getComputedStyle(target).getPropertyPriority('color') // ''
</script>
```

**Comment by emilio** [comment]
I think this is how it should work per spec, because https://drafts.csswg.org/cssom-1/#dom-window-getcomputedstyle doesn't set the important flag anywhere:

> decls to a list of all longhand properties that are [supported CSS properties](https://drafts.csswg.org/cssom-1/#supported-css-property), in lexicographical order, with the value being the [resolved value](https://drafts.csswg.org/cssom-1/#resolved-value) computed for obj using the style rules associated with doc. Additionally, append to decls all the [custom properties](https://drafts.csswg.org/css-variables-1/#custom-property) whose [computed value](https://drafts.csswg.org/css-cascade-5/#computed-value) for obj is not the [guaranteed-invalid value](https://drafts.csswg.org/css-variables-2/#guaranteed-invalid-value).

Let me know / reopen if that's somehow not your read as well, or if any further clarification is needed.

**Comment by cdoublev** [comment]
Sorry for not being explicit. Would you accept a PR adding this step?

  > 1. If the [computed flag](https://drafts.csswg.org/cssom-1/#cssstyledeclaration-computed-flag) is set, then return the empty string

**Comment by Loirooriol** [comment]
What would this solve? The current steps already produce empty string.

**Comment by cdoublev** [comment]
Nothing (I guess), I suggest it for consistency with `getPropertyValue()` and for the same reason as in #6144.
