### ISSUE TITLE
[css-4-selectors] Still no :Parent selector?

### ISSUE THREAD

**Issue by Nodws** [w3c/csswg-drafts#943]
cmon people we want to stop using js for this simple query

**Comment by SebastianZ** [comment]
See the [`:has()` pseudo-class](https://drafts.csswg.org/selectors-4/#relational).

Sebastian

**Comment by inoas** [comment]
has looks good as it doesn't traverse the tree up. Unidirectional traversal is really a good design choice in CSS.

**Comment by inoas** [comment]
Looking for the day `:has` reports green on http://caniuse.com/#search=%3A%3Ahas

**Comment by tabatkins** [comment]
`:has()` is equally as problematic, from a perf perspective, as "parent" selectors.  This is why `:has()` is marked as part of the [static profile](https://drafts.csswg.org/selectors/#static-profile) - it's explicitly *not* allowed in stylesheets.
