### ISSUE TITLE
[css-text][css-writing-modes] text-orientation:upright and text-autospace

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9430]
Should `text-autospace` have an effect withing a vertical writing mode when `text-orientation` is `upright`?

This test assumes no, and I think that's reasonable, but I cannot find what backs this up in either spec.

https://wpt.fyi/results/css/css-text/text-autospace/text-autospace-vertical-upright-001.html?label=experimental&label=master&aligned

**Comment by frivoal** [comment]
cc: @kojiishi @fantasai

**Comment by xfq** [comment]
According to the requirements of [Chinese](https://www.w3.org/TR/clreq/#mixed_text_composition_in_vertical_writing_mode) and [Japanese](https://www.w3.org/TR/jlreq/#mixed_text_composition_in_vertical_writing_mode), I don't think `text-autospace` should have an effect in vertical writing mode when `text-orientation` is upright.

I think it should at least be mentioned in css-text. I have no strong opinion on whether it's mentioned in css-writing-modes or not.

**Comment by kojiishi** [comment]
8.5.2. Text Spacing Character Classes defines that [non-ideographic letters](https://drafts.csswg.org/css-text-4/#non-ideographic-letters) excludes:
> * is upright in vertical text flow using the [text-orientation](https://drafts.csswg.org/css-writing-modes-4/#propdef-text-orientation) property or the [text-combine-upright](https://drafts.csswg.org/css-writing-modes-4/#propdef-text-combine-upright) property.

Does this serve what you're looking for?

**Comment by frivoal** [comment]
Yes it does, thanks for pointing this out.
