### ISSUE TITLE
[css-text] line-break: strict should use UAX#14 rule?

### ISSUE THREAD

**Issue by makotokato** [w3c/csswg-drafts#9432]
Mozilla is working to replace old line breaking code with [UAX#14 ](https://www.unicode.org/reports/tr14/) compatible line breaking rules. Although Blink and WebKit use ICU4C to implement line breaking, both uses different rules with Unicode Standard Annex (See https://bugzilla.mozilla.org/show_bug.cgi?id=1848049 for details) for ASCII characters when checking behavior.

According to [code comment](https://searchfox.org/wubkat/rev/cd25edd92284ea5ea247483e66b404c0774949b2/Source/WebCore/rendering/BreakLines.cpp#53), it seems to be for a compatibility of old browsers. So when using ASCII character, it doesn't match with UAX#14. Example, https://wpt.fyi/results/css/css-text/i18n/css3-text-line-break-baspglwj-026.html?label=experimental&label=master&aligned is failed on WebKit and Blink now.

So I think that we should use UAX#14 rules if `line-break: strict`. It is clear for line breaking compatibility for future. How do you think?

**Comment by frivoal** [comment]
UAX14 covers a lot of things, much of which is tailorable, some of which is required by css-text, and some of which is overriden by css-text. Could you be a bit more specific about which part of UAX14 you're thinking of adopting?

For what it's worth, I think that what @jfkthame is saying in https://bugzilla.mozilla.org/show_bug.cgi?id=1848049 is very reasonable, and as far as I can tell, is neither required nor forbidden by css-text.

**Comment by fantasai** [comment]
The spec deliberately leaves line-breaking fairly open-ended, and doesn't require UAX14 compatibility, because UAX14 is known to not be an ideal line-breaking implementation, merely a reasonable baseline to start from. So I'm not sure the spec should change here: as Florian says, it allows what Mozilla wants to do already.

**Comment by fantasai** [comment]
@makotokato Is it OK to close this issue, or do you want us to raise it with the CSSWG?

**Comment by birtles** [comment]
I discussed this with @makotokato and based on @jfkthame's feedback I think we'd like to add an informative note regarding the sort of deviations from UAX#14 that implementers might want to consider for compatibility's sake. I can try to draft that next week if I'm available (feel free to steal it from me though) but for now I'd like to keep this issue open.

**Comment by birtles** [comment]
I made up a strawman note over in #9997 (nearly 10,000!). I'll be on leave for the next few weeks so I can't promise I'll be able to address any feedback. Feel free to take it over and fix as you like!
