### ISSUE TITLE
[css-grid-2] Animation / interpolate grid-auto-columns and grid-auto-rows

### ISSUE THREAD

**Issue by flackr** [w3c/csswg-drafts#9440]
In #3201 there were specific animation type rules added for `grid-template-columns` and `grid-template-rows`. In https://crbug.com/1365967 @bramus raised a use case where it would be nice to interpolate `grid-auto-columns` and `grid-auto-rows`.

It doesn't look like any browser supports this today, based on my [simple demo](https://codepen.io/flackr/pen/jOXexzJ) but I don't see why we shouldn't support interpolating the auto properties as well. Given the syntax is only `<track-size>+` I think the animation type may need to be:

```
  Animation type: if the list lengths match, by computed value type per item; discrete otherwise
```

Unless per item animation is already implied by the animation type of a list of track sizes?

@fantasai

**Comment by tabatkins** [comment]
It's already marked as animatable, and lists should default to animating in that fashion. But we went ahead and clarified this based on your comment. ^_^
