### ISSUE TITLE
[css-zoom?] Zoom and replaced element intrinsic dimensions

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9442]
The zoom property has an effect on intrinsic element dimensions ([live](https://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cstyle%3E%0Ap%20%7B%20zoom%3A%202%20%7D%0A%3C%2Fstyle%3E%0A%3Cp%3E%3Cimg%20src%3Dimage%3E), [another demo](http://crisal.io/tmp/zoom-image-size.html)):

```html
<!DOCTYPE html>
<style>
p { zoom: 2 }
</style>
<p><img src=image>
```

That is fine and all, because it matches what you'd get if you specified the size with `width` and `height` (because those would go through the attribute mapping stuff etc).

But I don't think it's explained/defined in https://github.com/atanassov/css-zoom/ or so. What other side-effects does Zoom have? Does it apply to all replaced elements? Presumably it should, since their intrinsic size works in CSS pixels as well?

cc: https://github.com/w3c/csswg-drafts/issues/5623 @chrishtr @lilles @smfr @tabatkins @atanassov @zcorpan

**Comment by chrishtr** [comment]
It does apply to all replaced elements. There is currently a bug that zoom from a document doesn't follow through to iframes, but I plan to fix it soon.

**Comment by zcorpan** [comment]
Also needs to affects size of background images for web compat: https://bugzilla.mozilla.org/show_bug.cgi?id=390936#c106
