### ISSUE TITLE
[css-colors-5] Minor syntax problems

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9445]
1. [`<color>`](https://drafts.csswg.org/css-color-5/#typedef-color) is missing [`<color-mix()>`](https://drafts.csswg.org/css-color-5/#funcdef-color-mix).

2. [`<cmyk-component>`](https://drafts.csswg.org/css-color-5/#typedef-cmyk-component) is missing `none` (also applies to the `<alpha-value>` of `device-cmyk()`).

  > All color functions (with the exception of those using the legacy color syntax) allow any of their components to be specified as `none`.

https://drafts.csswg.org/css-color-4/#missing

3. [`<custom-params>`](https://drafts.csswg.org/css-color-5/#typedef-custom-params) should define a list of whitespace (vs. comma) separated parameters (`+` instead of `#`).

4. `<rectangular-color-space>` is defined in [CSS Color 4](https://drafts.csswg.org/css-color-4/#typedef-rectangular-color-space) with a wider range of values than in [CSS Color 5](https://drafts.csswg.org/css-color-5/#typedef-rectangular-color-space).

**Comment by LeaVerou** [comment]
> 2. [`<cmyk-component>`](https://drafts.csswg.org/css-color-5/#typedef-cmyk-component) is missing `none` (also applies to the `<alpha-value>` of `device-cmyk()`).

At this point, we should probably define tokens for color components and use those instead of repeating them in component definitions, which is error prone.

I.e.:

```
<color-component-percentage>: <percentage> | none
<color-component-number>: <number> | <percentage> | none
<color-component-angle>: <angle> | <percentage> | none
```

Legacy ones can probably stay as-is.

Agreed to all other remarks as well. Would you like to send a PR for 1, 3, 4 or should I (or @svgeesus) make the changes? 


> 4\. `<rectangular-color-space>` is defined in [CSS Color 4](https://drafts.csswg.org/css-color-4/#typedef-rectangular-color-space) with a wider range of values than in [CSS Color 5](https://drafts.csswg.org/css-color-5/#typedef-rectangular-color-space).

These kinds of things crop up so frequently that I'm starting to think Bikeshed needs some kind of templating/abstraction mechanism. Thoughts, @tabatkins ?

**Comment by cdoublev** [comment]
> Would you like to send a PR for 1, 3, 4 or should I (or @svgeesus) make the changes?

Please do the changes. Productions for each color channel do not make the syntax more readable (imo) but it is less error prone, indeed.

```
lab() = lab( <color-component-number>
      <color-component-number>
      <color-component-number>
      [ / <color-component-alpha> ]? )

lab() = lab( [<percentage> | <number> | none]
      [ <percentage> | <number> | none]
      [ <percentage> | <number> | none]
      [ / [<alpha-value> | none] ]? )
```

**Comment by svgeesus** [comment]
Thanks, fixed!

**Comment by cdoublev** [comment]
Nit:

```diff
- device-cmyk() = device-cmyk( <cmyk-component>{4} [ / <alpha-value> | none ]? )
+ device-cmyk() = device-cmyk( <cmyk-component>{4} [ / [ <alpha-value> | none ] ]? )
```

**Comment by svgeesus** [comment]
> However I am not sure its legacy syntax should allow <percentage>.

The [legacy syntax](https://www.w3.org/TR/2011/WD-css3-gcpm-20111129/#cmyk-colors), which was implemented in some CSS to PDF tools, did not allow percentage for the color components (and did not allow alpha at all, in fact).

**Comment by cdoublev** [comment]
Thanks for the grammar additions and the clarification.

I think `[ / <alpha-value> | none ]` allows `/ <alpha-value>` or `none` because *juxtaposition is stronger than the bar*. It should be replaced with `[ / [ <alpha-value> | none ] ]`, which allows `/ <alpha-value>` or `/ none`.

**Comment by svgeesus** [comment]
>  I assume no conversion to the legacy syntax like for rgb/hsl is required for specified value serialization.

For `rgb()` and `hs()`l, that serialization choice (plus the awkward 255 serialization) was driven by decades of backwards compatibility with existing scrips.

For `device-cmyk()`, which currently is implemented solely in CSS to PDF converters which typically do not expose a DOM, there is no such constraint so we can go for a [cleaner solution](https://drafts.csswg.org/css-color-5/#serializing-device-cmyk-values).
