### ISSUE TITLE
[css-fonts] All CSS-wide keywords should be excluded from <family-name> type

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#946]
The spec currently says:
> Font family names that happen to be the same as a keyword value (`inherit`, `serif`, `sans-serif`, `monospace`, `fantasy`, and `cursive`) must be quoted to prevent confusion with the keywords with the same names. The keywords `initial` and `default` are reserved for future use and must also be quoted when used as font names. UAs must not consider these keywords as matching the `<family-name>` type.

It excludes `inherit` and `initial`, but does not excludes other CSS-wide keywords, e.g. `unset`. It should probably say that any CSS-wide keywords should not be matched as `<family-name>` type.

**Comment by tabatkins** [comment]
Yup, this was just a copy over from previous spec-ese that explicitly listed the keywords.
