### ISSUE TITLE
[css-highlight-api-1] Use custom-ident instead of custom-highlight-name

### ISSUE THREAD

**Issue by pyoor** [w3c/csswg-drafts#9483]
Is there a reason this syntax defines a new terminal type of `custom-highlight-name` rather than `custom-ident`?

https://github.com/w3c/csswg-drafts/blob/4a0f2e33b941b05268760f052fcd934218bbbd6b/css-highlight-api-1/Overview.bs#L307

**Comment by cdoublev** [comment]
Fixed by ed29c24bf2172fc132bd4977fe01ca97b60ecd92.
