### ISSUE TITLE
[cssom-view] checkVisibility options have inconsistent naming schemes

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9487]
We have checkOpacity and checkVisibilityCSS. Can we add a CSS suffix to `checkOpacity` ? Or rename to: `checkOpacityProperty` / `checkVisibilityProperty`

cc @josepharhar @vmpstr @smfr

**Comment by rniwa** [comment]
Why do we even need to say "check" in each one of these options anyway? The method is called `checkVisibility`. We don't need to repeat "check" in every option.

**Comment by smfr** [comment]
The term "check" is also problematic. It's a "compute" or "fetch" not a "check". ("Check" can also be interpreted to mean "constrain" or "slow down").

**Comment by nt1m** [comment]
So `computeOpacityProperty` / `computeVisibilityProperty` / `computeContentVisibilityAuto` ?

**Comment by smfr** [comment]
See also https://github.com/w3c/csswg-drafts/issues/7317

**Comment by smfr** [comment]
how about `window.getComputedVisibility()` to parallel `getComputedStyle()`?

**Comment by vmpstr** [comment]
For posterity, the dictionary property names were (somewhat briefly) discussed here https://github.com/w3c/csswg-drafts/issues/6850#issuecomment-1057555124

**Comment by fantasai** [comment]
Current proposal from @nt1m btw is:

- `fooProperty` for CSS `foo` property checks
- `fooBar` for CSS `foo` property checking value `Bar`

For the current values that translates to `opacityProperty`, `visibilityProperty`, and `contentVisibilityAuto`.

Earlier proposals also included values for checking `aria-hidden` and for `inert`.

**Comment by emilio** [comment]
Those are not CSS properties. Presumably those would just be ariaHidden and inert?

**Comment by nt1m** [comment]
> Those are not CSS properties. Presumably those would just be ariaHidden and inert?

Yeah that would make sense. Although I prefer to not add those 2 options in this function, or at least in their current form, I'd prefer something more high level for accessibility.

**Comment by emilio** [comment]
Yeah agreed. Those are orthogonal to this.

**Comment by vmpstr** [comment]
To write the full syntax for posterity, 
```
el.checkVisibility({ contentVisibilityAuto: true })
```
Would mean return true iff `el` has a box, is not `content-visibility: hidden`, and also not skipped due to `content-visibility: auto` 

(bikeshed) I feel like "check" prefix in dictionary fields played a role here that made this a little clearer

**Comment by vmpstr** [comment]
FWIW, I'm good with adding the names proposed in https://github.com/w3c/csswg-drafts/issues/9487#issuecomment-1782109845 as aliases
