### ISSUE TITLE
[css-fonts-4] Remove mentions of invalid `@font-face`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9491]
According to https://github.com/w3c/csswg-drafts/issues/1133#issuecomment-319945737 and [CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#font-face-rule):

  > [...] `@font-face` rules require a `font-family` and `src` descriptor; if either of these are missing, the `@font-fac`e rule must not be considered when performing the font matching algorithm.

Basically, it remains valid but it does not declare a resource (CSSOM allows to update it and to become considered when performing the font matching algorithm). 

But later it is defined as invalid:

  > **Name:** [`font-family`](https://drafts.csswg.org/css-fonts-4/#font-family-desc)
  >
  > [...] It is required for the `@font-face` rule to be valid.

  > **Name:** [`src`](https://drafts.csswg.org/css-fonts-4/#descdef-font-face-src)
  > 
  > [...] It is required for the `@font-face` rule to be valid.

I propose to remove these mentions.

**Comment by svgeesus** [comment]
[CSSWG resolution from 2017](https://github.com/w3c/csswg-drafts/issues/1133#issuecomment-319945737)
