### ISSUE TITLE
[css-images-4] CSS shaders for backgrounds

### ISSUE THREAD

**Issue by ghost** [w3c/csswg-drafts#95]
Here I described suggestion. I think this is theme of CSS4. 
https://github.com/w3c/css-houdini-drafts/issues/130

Copy: 
<hr>

Hello. I suggest make very original feature: CSS background shaders. And shaders of OpenGL ES 3.0. Also, I suggest forbid use vertex shaders, only fragment. If this is theme of CSS4, please, merge this suggestion to CSS4 (or CSS4.1). 

Syntax: 

```
  background-image: custom( /* Forgot CSS custom filter (shaders) syntax */ );
```

Features: 
- Same syntax as CSS custom filters
- Shaders used for painting 
- Not require JS
- Much faster
- Much powerfull

**Comment by tabatkins** [comment]
We don't accept issues from ghosts.  Also, this was already attempted by CSS Shaders in the past, and there were good reasons at the time to reject it, which afaik haven't changed.
