### ISSUE TITLE
[css-flexbox] Percentage height resolution against indefinite containing block size inside nested flex box.

### ISSUE THREAD

**Issue by icecreamx3** [w3c/csswg-drafts#9506]
``` HTML
<div style="background:red;display:flex;flex-direction:column;height:400px;width:400px">
  <div style="background:blue;display:flex;">
    <div style="background:green;width:200px;height:50%">
    </div>
    <div style="background:yellow;width:50%;width:200px;height:200px">
    </div>
  </div>
</div>
```
In the above case, I think the blue `<div>` is the containing block of the green `<div>` and the height of the blue `<div>` is decided by its content size. The height of the green block is percentage and creates a cyclic percentage dependency which I think should follow the description here [https://drafts.csswg.org/css-sizing-3/#cyclic-percentage-contribution](https://drafts.csswg.org/css-sizing-3/#cyclic-percentage-contribution):

> If the cyclic dependency was introduced due to a block-size or max-block-size on the containing block that causes it to depend on the size of its contents, the box’s percentage is not resolved and instead behaves as auto.

If I'm not getting this rule wrong, the height of the green `<div>` should be zero in this case.

However, I tested with Blink, Gecko and Webkit. The heights of green `<div>` are all 100px. And if I remove the height specification on the **red** `<div>`, the heights  of green `<div>` become zero.

Not sure if I am getting the W3C spec wrong or it is a bug on browsers.

**Comment by Loirooriol** [comment]
Not much familiar with flex details, but I think it may be https://drafts.csswg.org/css-flexbox-1/#definite-sizes

> If the [flex container](https://drafts.csswg.org/css-flexbox-1/#flex-container) has a [definite](https://drafts.csswg.org/css-flexbox-1/#definite) [main size](https://drafts.csswg.org/css-flexbox-1/#main-size), then the post-flexing main sizes of its [flex items](https://drafts.csswg.org/css-flexbox-1/#flex-item) are treated as definite.
