### ISSUE TITLE
[css-nesting] Interaction with :host is unfortunate.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9509]
This test-case ([live](https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/12071)) doesn't produce the expected behavior (purple) in any browser:

```html
<!doctype html>
<div id="host">Something</div>
<script>
  host.attachShadow({ mode: "open" }).innerHTML = `
    <style>
      :host {
        background-color: green;
      }
      div {
        background-color: red;
        display: inline-block;
        width: 12px;
        height: 12px;
      }
      :host(#host) div {
        background-color: blue;
      }
      :host(#host) {
        div {
          background-color: purple;
        }
      }
    </style>
    <slot></slot>
    <div></div>
  `;
</script>
```

This is because per spec, the host only matches featureless `:host` selectors, and the `&` (or `:is(:host(..))` for that matter) isn't that.

This is similar to #9153 / #9492 (cc: #8738).

cc: @tabatkins @andruud @mdubet @LeaVerou @fantasai

**Comment by tabatkins** [comment]
That's an impl bug. The spec supports this case.

For `&`:
> The [nesting selector](https://drafts.csswg.org/css-nesting/#nesting-selector) is capable of matching [featureless](https://drafts.csswg.org/selectors-4/#featureless) elements, if they were matched by the parent rule.

For `:is(:host)`:
> A [featureless](https://drafts.csswg.org/selectors/#featureless) element does not match any selector at all, except those it is explicitly defined to match (and [logical combination pseudo-classes](https://drafts.csswg.org/selectors/#logical-combination-pseudo-classes) representing those selectors).

**Comment by emilio** [comment]
We should add tests, though that's a bit complicated impl wise (at least in Firefox), because you need not to match all other selectors inside :is().

**Comment by emilio** [comment]
@tabatkins my read about your second quote is that `:is(:host)` should match but `:is(#foo, :host)` shouldn't, is that right? If so that simplifies the implementation significantly.

**Comment by emilio** [comment]
(That means that nesting inside `foo, :host` would not work as expected perhaps, but that seems more edge-casey than just nesting inside `:host`)

**Comment by tabatkins** [comment]
No, I'd expect `:is(#foo, :host)` to match, just like `#foo, :host` would. That's the point of that line.

**Comment by andruud** [comment]
Yes, I've been wanting to fix this for a while in Blink. In our (implementations') defense, `:is()` not matching the host _was_ the correct behavior at the time. The spec was changed later. :-)
