### ISSUE TITLE
[css-view-transitions-2] Starting a same-doc view transition while a cross-doc view transition is pending

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9512]
The current behavior in the spec is that starting any view transition cancels the active one, which means that the following edge cases might have unexpected results:

- A capture is initiated for a document navigation and script initiates a transition before the document unloads. should we ignore `document.startViewTransition()` calls during a navigation initiated transition?

- On the new Document, script initiates transition before the navigation initiated transition could finish (before `pagereveal`). Given that the navigation initiated transition will be before the first frame of the new Document was rendered, should we ignore it and let the MPA transition go through?

@khushalsagar @bokand @vmpstr

**Comment by vmpstr** [comment]
I agree with both the points. In general I think MPA transition should take "priority" over SPA. Another case is when an SPA transition is already happening while the user initiates an MPA navigation with a transition.

In all of these, we should ensure that the MPA transition runs. In the future, with scoped transitions, we might be able to allow both to run in some cases, but if it's not possible MPA should win.

**Comment by noamr** [comment]
I think that there are good reasons keep the current behavior. e.g. if the author prefers to run an entry animation instead of the MPA transition, go ahead. "last transition wins" is easy to reason about and consistent, while "MPA wins and last transition wins at a lower priority" is more complicated with questionable value.

**Comment by khushalsagar** [comment]
A same-document transition being started before the new Document has produced a single frame *and* we have an MPA transition seems like a bug? If the developer legit wants an entry SPA transition they can abort the MPA transition in `reveal` and then initiate an SPA transition.

I'd be fine with either, whatever would help authors more here.

**Comment by noamr** [comment]
> A same-document transition being started before the new Document has produced a single frame _and_ we have an MPA transition seems like a bug? If the developer legit wants an entry SPA transition they can abort the MPA transition in `reveal` and then initiate an SPA transition.
> 

Is this different/more buggy than starting an SPA transition and then starting a new one before we even got the callback?

**Comment by noamr** [comment]
Looking at the current spec, either way works for me. We can say that the MPA transition only becomes the "active view transition" on page reveal, which means that on page reveal it would skip any existing SPA view transitions (causing their update callback to be fired). In the current spec MPA transition sets the active view transition early, which would mean it would be skipped by an early `startViewTransition`.

**Comment by noamr** [comment]
This is actually a duplicate of #8678.

**Comment by khushalsagar** [comment]
We should keep the MPA transition until we've had at least 1 frame drawn? Otherwise I can't see any reasonable use-case where the author would want to overwrite the MPA transition before that. Doing so will result in an abrupt swap between the 2 Documents.

Once the new Document has drawn 1 frames, it's possible a network update changes its content drastically or the user interacts with the page.

Maybe `reveal` is a reasonable hook for that. Its fired right before we'll draw the first frame. After that point, there can be events where skipping the current transition is the right thing to do.

**Comment by flackr** [comment]
Given that there will be frameworks that sometimes navigate as an SPA and sometimes navigate as an MPA, I think we should be consistent and have the last transition win. In this case, the SPA would cancel the MPA transition, unless / until we work out the details on how to combine transitions.

Starting an SPA before first frame has been rendered is perfectly fine from a spec POV since the API will ensure the current state is rendered before calling the callback to produce the destination state.

**Comment by noamr** [comment]
Summarizing the internal group discussion, the direction is to propose resolving on the current wording of the spec, which means that a `startViewTransition` call that starts at any time after the cross-document view-transition has started would skip the cross-document view-transition. This would make cross-document transitions consistent with same-document transitions in this case.

**Comment by noamr** [comment]
> Does this include startViewTransition calls on the outgoing page that happen after the MPA version has triggered?

For consistency, yes. It means that calling `startViewTransition` during the capture-frame or `pagehide` would skip the MPA transition

**Comment by khushalsagar** [comment]
> It means that calling startViewTransition during the capture-frame or pagehide would skip the MPA transition

Is that the case based on the spec text [here](https://drafts.csswg.org/css-view-transitions-2/#document-setup-cross-document-view-transition:~:text=Clear%20view%20transition%20outboundTransition.). Looks like we clear the outbound VT before `pageHide` is dispatched? But yeah any script which happens to run before the rendering opportunity which is cached will skip it and that's fine.

**Comment by khushalsagar** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/9543 to discuss transition requests when the Document is hidden. I think the `pageHide` case will fall in this category?

**Comment by noamr** [comment]
> Filed #9543 to discuss transition requests when the Document is hidden. I think the `pageHide` case will fall in this category?

No, `pagehide` is only for page unloading or going into BFCache. `visibilitychange` is about hidden documents.

**Comment by khushalsagar** [comment]
Do we not mark the Document hidden before dispatching `pageHide`?

**Comment by noamr** [comment]
> Do we not mark the Document hidden before dispatching `pageHide`?

Yes, we do. sorry, my misunderstanding about #9543.

**Comment by khushalsagar** [comment]
**Proposed Resolution**: startViewTransition overwrites an existing cross-document ViewTransition (in the old or new document).
