### ISSUE TITLE
[css-text][text-spacing] Propose to make `allow-end` as the default behavior for the line end

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#9521]
Currently, the default behavior of line-end for the [`text-spacing-trim`](https://drafts.csswg.org/css-text-4/#text-spacing-trim-property) property is defined as:
> set [fullwidth closing punctuation](https://drafts.csswg.org/css-text-4/#fullwidth-closing-punctuation) with half-width glyphs (flush) at the end of each line

If the author specifies the [`allow-end`](https://drafts.csswg.org/css-text-4/#valdef-text-spacing-trim-allow-end):
> Set [fullwidth closing punctuation](https://drafts.csswg.org/css-text-4/#fullwidth-closing-punctuation) with half-width glyphs (flush) at the end of each line if it does not otherwise fit prior to justification, else set the punctuation with full-width glyphs.

From the dogfood feedback, I'd like to propose to change the default behavior to `allow-end`. We can add a value for the current default behavior if needed.

This proposal is because when you're typing in editable content. The current default behavior trims the last character as you type, making them difficult to distinguish whether it's full-width code point or half-width code point, until users type the next character. Some IMEs on desktop platforms remember which was used last time, making this symptom more difficult.

This happens quite frequently for Japanese/Simplified Chinese/Korean, where the comma and full stops (periods) are in the "closing" shape. Not as frequent for Traditional Chinese.

I don't know the motivation and the past discussions to make the current behavior as the default. If it has big reasons and the WG decided to make a trade-off, could someone please share?

From my current perspective, the feedback looks reasonable to me, and the difference between the current default and `allow-end` looks hardly noticeable, so this looks like a reasonable change.

Thoughts? /cc @fantasai @frivoal @nt1m @vitorroriz @Clqsin45 @MurakamiShinyu @himorin @kidayasuo

**Comment by MurakamiShinyu** [comment]
The current default behavior of line-end was my suggestion:

- https://github.com/w3c/csswg-drafts/issues/7055

However, it is fine to me changing this default, as I commented in https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1783734633.

**Comment by frivoal** [comment]
The change adopted in https://github.com/w3c/csswg-drafts/issues/9511 means that the initial value is now `normal`, and it does have an `allow-end` behavior. I think we can consider this issue solved?

**Comment by kojiishi** [comment]
> I think we can consider this issue solved?

Yes, thank you.
