### ISSUE TITLE
[css-text-4] error in `text-spacing-trim: space-first` definition

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#9532]
https://drafts.csswg.org/css-text-4/#valdef-text-spacing-trim-space-first

> Set fullwidth opening punctuation with full-width glyphs (spaced) on the first line the block container. Otherwise as trim-auto (unless allow-end is also specified).

I think this should be:

> Set fullwidth opening punctuation with full-width glyphs (spaced) on the first line of the block container and each line after a forced line break. Otherwise as trim-auto (unless allow-end is also specified).

"and each line after a forced line break" is necessary in this definition because the `space-first` value exists for compat requirements for existing content, where often `<br>` is used to separate paragraphs. See: https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1780688084

**Comment by fantasai** [comment]
Thanks for catching this regression, fixed.
