### ISSUE TITLE
[css-values-5][various] Better handling of arguments with commas

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#9539]
We've got several in-flight proposals for functions that can take "whole property value" arguments, like `mix()`, `random-item()`, etc. (And now custom functions and mixins, which @mirisuzanne and I are looking into more seriously again.)  Because these arguments can potentially contain commas (say, mixing between two background-image lists), we can't use commas as the argument separator, and the proposals currently all use *semicolons* as the separator instead, as this is guaranteed to never show up at the top-level of a property value.

Even tho I'm the one that started this trend, I don't like it. ^_^ I'd like to find a different solution. The problems are:

* It's obviously a bit inconsistent with existing functions. It's not *terrible*, but it's not good either.
* A lot of userland tools use very simplistic parsers, and divide properties by just splitting on semicolons. This'll break them until they rewrite to be aware of nesting levels for matched parens.
* *Most* uses of these functions don't need the special separator; it's only the rare uses that involve operating on an entire comma-separated list that do. Forcing people to do a weird thing for a case they'll rarely hit isn't great.
* It's not forward-compatible in some cases. We have to design this syntax into the function right from the beginning, and can't ever expand an existing comma-separated function into it (unless we do a grammar split, which is nasty in its own way).
* The `var()` function already lets you take this kind of argument, but because its syntax was designed to take only one, and as the final argument, it can continue to use comma separation. (That is, you can write `var(--foo, blue, red, black)` - that's two args, a `-foo` and a `blue, red, black` list.)

The obvious solution is to add an optional *wrapper* around arguments, which will "hide" the commas from the outer function. It would only be necessary when someone is *actually* passing a comma-separated argument.

I have two possible suggestions, and am happy with either:

* Use `[]`, like `background: mix(50%, url(start), [ url(foo), url(bar) ]);`
* Use a new, generically named function, like `item()`: `background: mix(50%, url(start), item( url(foo), url(bar) ));`

This notation would only be allowed in the functions that can take these problematic values, and if present, would be stripped for the purpose of the actual value. No nesting - if you were mixing a subgridded "line names only" value for grid-template-columns, for example, you'd write it as `grid-template-columns: mix(50%, [[foo bar]], [[baz qux]])`, so the outer `[]` gets stripped and the inner `[]` is part of the actual value.

(I'm rejecting using naked `()` for the same reason we ended up switching away from them for grid lines - it would mess up Sass syntax, and possibly others, *hardcore*, since in Sass it indicates math. I'm rejecting `{}` for "naive userland tools" reasons; again, many just split the text with regexes, and stray `{}` can screw them up. They're already potentially broken for custom props containing these chars, of course, but that's not an official Part Of CSS like this would be.)

Thoughts?

**Comment by romainmenke** [comment]
Naked `()` seems like the most obvious candidate imho, even if that is already a thing in Sass.
It is also the kind of blocks used to group items in supports and media queries, so it's consistent to keep using it for grouping.

Using `[]` seems confusing and I personally always forget that this is a thing for grid and have to look it up each time.

A generic function would not bad, but not as good as naked `()`.

**Comment by Loirooriol** [comment]
You mention `var()`. So let's say somebody is using

```css
.subgrid-2 {
  grid-column: span 2;
  grid-template-columns: subgrid var(--lines-1, [start]) var(--lines-2, [middle]) var(--lines-3, [end]);
}
```

Currently computes to `subgrid [start] [middle] [end]`, you proposal would result in an invalid `subgrid start middle end`, so it would become invalid at computed-value time?

**Comment by tabatkins** [comment]
Nah, I mention var() as an example, but it doesn't need to use this syntax. (But if we do `item()`, especially, it probably could. It just wouldn't ever be *necessary*, since it's a single trailing argument.)

**Comment by tabatkins** [comment]
> Naked () seems like the most obvious candidate imho, even if that is already a thing in Sass.
It is also the kind of blocks used to group items in supports and media queries, so it's consistent to keep using it for grouping.

Like I said, the WG already attempted to use naked `()`, and switched away from it, for exactly the reasons I gave. They're no less true now, and there's no particularly good reason to be inconsistent with our past decision here, so `()` is already off the table.

**Comment by SebastianZ** [comment]
I'd be happy with either bare `()` or a new function. `[]` would also be ok, though I somewhat dislike the double meaning of them regarding the use in `grid-template-*`. (They might not have been the best choice for naming grid lines, though that ship has sailed.)
I think we agree that we should _not_ use `{}`. Not only because of "naive userland tools" reasons but also because they indicate a rule body.

Sebastian

**Comment by fantasai** [comment]
Another possibility is continuing to use `,` as a separator, but allowing authors to upgrade to `;` whenever it's needed for disambiguation. Running across a `;` would invalidate the `,` grammar, and re-interpret the function as using `;` separators. We could even do this across all of CSS for consistency.

**Comment by tabatkins** [comment]
Yeah, I think the "allow comma or semi anywhere" works pretty reasonably, actually. We'd amend the grammar a bit so that commas in functions can also be semicolons (all at once, not on an individual level), but commas are already pretty magical in the grammar anyway.

I'm happy with either approach - "upgradeable" commas or a wrapper. We should get the WG's opinion and fix the Values 5 features accordingly.

**Comment by Loirooriol** [comment]
Regarding the upgradeable commas.

Let's say a property has grammar `<length>#{2,}`. Then `mix(50%, 1px, 2px, 3px, 4px)` is not ambiguous (1st value must be `1px, 2px`, and 2nd value `3px, 4px`).

But later on we relax the grammar to allow `<length>#`. Then `mix(50%, 1px, 2px, 3px, 4px)` suddenly becomes ambiguous!

So even if not ambiguous, I would prefer to forbid values from having a top-level comma when the author uses `,` instead of `;`. With the exception of `var()` to avoid breaking things.

**Comment by fantasai** [comment]
@Loirooriol 100% agree. If there are any commas within the values, you should have to use semicolon for the top level.

**Comment by tabatkins** [comment]
> Let's say a property has grammar `<length>#{2,}`

We simply wouldn't design such a grammar, so any questions about how it would behave aren't relevant, right?

**Comment by Loirooriol** [comment]
Well, let me just tweak it a bit: `cursor: toggle(url(icon1.ico), pointer, url(icon2.ico), move)`.

This is not ambiguous (1st value must be `url(icon1.ico), pointer`, 2nd value must be `url(icon2.ico), move`), but I don't think it should be allowed with that meaning. Somebody who is not familiar with the grammar of `cursor` will probably assume it means `toggle(url(icon1.ico); pointer; url(icon2.ico); move)`. And even if not likely, we will have a problem if at some point we decide to relax the grammar to allow lone urls.

**Comment by fantasai** [comment]
@Loirooriol I think what happens in that case is that the comma is interpreted as a top-level comma (i.e. separating toggle() arguments). Since we don't hit a semicolon, it parses cleanly and we're done.

If the author wants to include commas in their value, then they have to use semicolons to separate top-level arguments. We notice that's happening because as we're parsing the function, we hit a semicolon; that requires us to go back and reparse.

It does mean that you can't pass to a variable-length function a single argument that includes commas, but... that's probably fine?

**Comment by tabatkins** [comment]
Right, I think that @Loirooriol is just saying that they'd prefer we explicitly state that, in cases where you could potentially include a value with commas in it, you can only do so if you use semicolons; we will *never* parse a production that includes commas alongside other comma-separated arguments.

We'd probably address this at the level of where we define functional notation; we'd say that, unless otherwise specified (such as in `var()`), commas *always* separate arguments (aka are top-level in the function's grammar, rather than being claimable by productions) unless a semicolon is present instead. This might require a little bit of review of existing functions, like gradients have commas in their color-list production and will need that explicitly called out as allowed.

(Or maybe we actually reify the concept of "arguments" and say that commas are *solely* for separating arguments, unless semicolons are used instead. But that'd require a larger review of existing spec text. Might still be a good idea, tho.)

**Comment by LeaVerou** [comment]
I think a new generic function is the least weird of the proposed solutions, and the most forwards compatible (I propose `value()`). Special syntax like brackets removes that syntax from the design space for future properties. 

> Another possibility is continuing to use `,` as a separator, but allowing authors to upgrade to `;` whenever it's needed for disambiguation. Running across a `;` would invalidate the `,` grammar, and re-interpret the function as using `;` separators. We could even do this across all of CSS for consistency.

I don’t like this at all.
1. It includes the same cons as semicolons (breaks naive parsers) 
2. It introduces more inconsistency: if authors see a `mix()` with semicolons in the wild, it's not clear it also accepts commas and vice versa.
3. Worst of all: it introduces potential breakage that is hard to track down. E.g. is `mix(50%, var(--foo), var(--bar))` correct? Who knows!

**Comment by Loirooriol** [comment]
Would you require `value()` always or only to wrap values with top-level commas?
Also I don't see the problem with `mix(50%, var(--foo), var(--bar))`, it's typical for `var()` that you don't know whether the result will be valid or not. But at least we know that `mix()` has 3 arguments, and there are already two commas. So it will be valid iff the values of `--foo` and `--bar` are valid for the property, and they do not contain top-level commas.

**Comment by LeaVerou** [comment]
> Would you require `value()` always or only to wrap values with top-level commas? 

This is answered in the OP.

**Comment by kbabbitt** [comment]
I lean towards a new generic function as well. If `;` were allowed as a function argument separator, I could see problems stemming from the inability to put `;` in a variable value. I couldn't come up with a realistic example, but here's a contrived one:

```
.foo { background-image: mix(50%; var(--mix-or-toggle-me)); }

.bar { background-image: toggle(var(--mix-or-toggle-me)); }

:root {
  --bg-a: url(1.png), url(2.png);
  --bg-b: url(3.png), url(4.png);
  --mix-or-toggle-me: var(--bg-a);var(--bg-b); /* oops */
}
```

**Comment by Loirooriol** [comment]
@kbabbitt That can be addressed with #8391 wile keeping `;` as the separator.

**Comment by tabatkins** [comment]
Putting this up on the F2F agenda to discuss. Summarizing the two options:

1. Remove the `;` separator idea. Instead, use some variety of wrapper for the rare cases when you need to provide a value that is, itself, comma-separated. Options:
    1. Use `[]`, like in Grid to wrap line groups.
    2. Use `{}`. (Syntax now disallows `{}` at the top-level, but these will be inside of a function, and thus possible.)
    3. Use `item()` or a similar generically-named function.
2. Make `;` an *optional upgrade*. All functions continue to use `,` as the argument separator, but *also* allow using `;` as a separator. When parsing, assume that `,` is the argument separator at first, but if a top-level `;` is encountered in the function value, re-parse using `;` as the argument separator instead.

**Comment by LeaVerou** [comment]
> Putting this up on the F2F agenda to discuss. Summarizing the two options:
> 
> 1. Remove the `;` separator idea. Instead, use some variety of wrapper for the rare cases when you need to provide a value that is, itself, comma-separated. Options:
>    
>    1. Use `[]`, like in Grid to wrap line groups.
>    2. Use `{}`. (Syntax now disallows `{}` at the top-level, but these will be inside of a function, and thus possible.)
>    3. Use `item()` or a similar generically-named function.
> 2. Make `;` an _optional upgrade_. All functions continue to use `,` as the argument separator, but _also_ allow using `;` as a separator. When parsing, assume that `,` is the argument separator at first, but if a top-level `;` is encountered in the function value, re-parse using `;` as the argument separator instead.

We should consider the user experience not only when writing code, but also when *reading* code. The former is only done once, but the latter is done many times. I’m quite concerned that 2 is prioritizing the former over the latter. A grouping construct makes it obvious what is going on, whereas using a different separator only *some* of the time makes parsing hard not just for parsers, but humans too.

**Comment by kizu** [comment]
I noticed in the agenda that this issue is mentioned alongside https://github.com/w3c/csswg-drafts/issues/6705, but neither issue contains an explicit link to another, so I feel it is worth it to mention it explicitly here, as they essentially talk about the same thing.

Regarding the potential solution, I would prefer the `value()` or `item()` (or any other function) to any syntax-only way. Most of my arguments for this were already mentioned above, but to re-iterate:

1. I don't like the modality of the `;` vs `,`. It might really be confusing for authors, and it won't be trivial to search for “what is this syntax?”.
2. I don't like the `[]`, `{}` etc, for similar reason, plus I don't like the confusion with the `[]` from the grid syntax.
3. Given this new language feature is required only for edge-cases, I am fine with the syntax being more verbose like with `value()`: if we can keep most of the use cases clear and simple, then it is ok to have the edge-case more verbose.

**Comment by LeaVerou** [comment]
Are plain parens an option? Parsing-wise, it should be pretty simple to say "if the first character is a paren, the argument does not end before its closing paren".

**Comment by Crissov** [comment]
If I’m reading the grammar correctly, an ident-token is required before the opening parenthesis, so `--()` is the minimum you can get without letters – but I may well be wrong about that.

**Comment by Loirooriol** [comment]
You definitely don't need an ident before a ()-block. In fact, if you have an ident, you would get a function instead.

```js
CSS.supports("--a", "()"); // true
```

**Comment by astearns** [comment]
Just mentioned in the call, but to highlight this, the argument against bare parentheses is in the first comment above:

> (I'm rejecting using naked () for the same reason we ended up switching away from them for grid lines - it would mess up Sass syntax, and possibly others, hardcore, since in Sass it indicates math. I'm rejecting {} for "naive userland tools" reasons; again, many just split the text with regexes, and stray {} can screw them up. They're already potentially broken for custom props containing these chars, of course, but that's not an official Part Of CSS like this would be.)

**Comment by nex3** [comment]
To clarify, does the resolution here apply to *all* functions? Can I write `var(--foo; blue, red, black)`? Can I write `round(to-zero; -105px; 10px)`? Or will there be a specific set of functions for which semicolons are explicitly allowed?

**Comment by bramus** [comment]
> To clarify, does the resolution here apply to _all_ functions?

That’s also my understanding, as per @tabatkins’s [proposal](https://github.com/w3c/csswg-drafts/issues/9539#issuecomment-1918019555) _(emphasis mine)_:

> 2\. Make ; an optional upgrade. **All functions** continue to use , as the argument separator, but **also allow using ; as a separator**. When parsing, assume that , is the argument separator at first, but if a top-level ; is encountered in the function value, re-parse using ; as the argument separator instead.

**Comment by cdoublev** [comment]
Does it only apply to arguments defined with `#`? Or also those defined with `,`?

Does it apply to legacy color functions? (they do not support features of the modern syntax)

---

In JS, variadic functions like `Array.concat()` requires to explicitly wrap list arguments. It would have been nice to match JS and CSS, since both are the main Web languages. I am not familiar with many other programing languages, but none use `;` as a separator of function arguments.

**Comment by Loirooriol** [comment]
Yeah I recalled there was some principle like that, that's what I tried to say during the call, but didn't remember the details of what it was.

**Comment by tabatkins** [comment]
Like I've said multiple times, we (the Working Group) already had this discussion, and made a decision about bare parentheses. If you want to religitate that decision *in general*, feel free to do so in a different issue. Until then, I'm sticking with the WG's previous decision on this matter.

(And I must emphasize *again* that "Prioritize" does not mean "Value regardless of all other factors". We *regularly* make syntax decisions that harm third-party tools because it's in the best interests of CSS. This *specific* decision was made several years ago, with *substantial* argument, because it would be *catastrophic* for Sass's parsing (and Sass was, and continues to be, one of the most (if not *the* most) used third-party tools), and there were plenty of other options for CSS that were just as good. A prioritization principle is a thumb on the scale, not an argument in and of itself.)

> If the argument is that semicolons as an optional upgrade are better or equivalent in terms of usability, that's one thing and I'm willing to accept it.

And yes, this *is* additionally the argument I'm making. I don't want to waste time relitigating an already-settled decision when it's irrelevant in the first place because we already have a better option *and resolved on it*.

In particular - anything we use for grouping here, we *very likely* want to *never use anywhere else in CSS*. If we did use them somewhere else, then we *once again* have an ambiguous situation, where it's unclear whether the parens are part of the generic function syntax (and won't be read as part of the argument) or it's part of the argument itself; likely we'd end up needing to require people to double-wrap the values so the outer one can be part of the generic function syntax and the inner can be part of the value. That's relatively bad!

Using semicolons (or a few other characters that are similarly restricted from appearing in values due to existing parsing constraints) avoids that entirely, since they simply can't appear in a top-level value at all. Ambiguity is thus impossible.

**Comment by tabatkins** [comment]
> To clarify, does the resolution here apply to all functions? 

Yes.

**Comment by tabatkins** [comment]
All right, spec text pushed. Still need to update the function definitions in the spec, but there's an inline issue mentioning that.

Review of the text appreciated!

**Comment by bramus** [comment]
Text looks good AFAICT.

**Comment by cdoublev** [comment]
> But if only single fonts were needed for each choice, commas could have been used to separate them:
  >
  > `font-family: random-item(serif, sans-serif, monospace);`

I do not see three but only one `<declaration-value>` here, which is valid though, but with a different outcome.

**Comment by Loirooriol** [comment]
Yeah I think comma-containing productions should end when encountering a comma, when used in a function notation that is not re-interpreted with semicolons. We may need an exception for `var()` and `env()`.

**Comment by tabatkins** [comment]
Right, we need a bit of extra text saying that, when used in a function, those comma-containing productions are *not* allowed to contain commas *unless* the function is in semicolon mode.

**Comment by tabatkins** [comment]
Right, and it's stronger than that, actually - `foo(1; 2, 3)` is valid, giving two arguments: `1` and `2, 3`.

For this to work, we need to reify the concept of "arguments", so we can distinguish between "commas that separate arguments" (need to either be all commas or all semicolons) and "commas inside of arguments" (need to be commas, and are part of a singular expression).

**Comment by cdoublev** [comment]
I am worried about cases like `fn(<options>, <argument-list>)` or `fn(<options>, <argument>#)`, and more generally, about how the reification will be translated in terms of the value definition syntax. I am not sure you plan to define `<argument-list>` and `<argument>#` as *implicit* comma-containing productions. But I will simply wait for your changes, do not bother clarifying this now.

  > if a `<semicolon-token>` is encountered, then the functional notation is re-interpreted with all commas in the grammar replaced by `<semicolon-token>`s

Note that you can interpret the functional notation *once*, based on whether the input list of component values has a `<semicolon-token>`. I mean, the *re-* prefix is not mandatory, imo.

**Comment by cdoublev** [comment]
About this [recent change](https://github.com/w3c/csswg-drafts/commit/811d2a0caa828c283d887a307cb166a57592ace4):

  > When a functional notation is parsed, initially [...] any comma-containing productions are not allowed to contain `<comma-token>`s [...]

I am not sure if this is an oversight: as [pointed above](https://github.com/w3c/csswg-drafts/issues/9539#issuecomment-1999808636) by Oriol, it is missing an exception for [`env()`](https://drafts.csswg.org/css-env-1/#funcdef-env) and [`var()`](https://drafts.csswg.org/css-variables-2/#funcdef-var). I am not sure about [`attr()`](https://drafts.csswg.org/css-values-5/#funcdef-attr), [`param()`](https://drafts.csswg.org/css-link-params-1/#typedef-link-param) and [`paint()`](https://drafts.css-houdini.org/css-paint-api-1/#funcdef-paint).

I think it should also not apply for the functional notation used in [`<general-enclosed>`](https://drafts.csswg.org/css-values-4/#typedef-general-enclosed) and [`<pseudo-class-selector>`](https://drafts.csswg.org/selectors-4/#typedef-pseudo-class-selector).

---

Fwiw, after re-reading them, the paragraph quoted in my previous comment and its new version, are no longer confusing: *in the grammar* includes any sub-production. Gradient grammars make this obvious (`<options>, <color-stop-list>`).

However, I would still clarify *in the grammar **of the current input level*** or with an example like `min(0; max(1, 2))`.

---

I presume the comma ellision rules should also apply when commas are replaced with semicolons.

In #8387, I was told that there is no exception in `attr()` but I am not quite clear on why `--optional-block-padding: attr(data-padding,)` should be invalid, and now also why leading/adjacent/trailing commas or semicolons would be invalid in the new subsitution functions taking `<whole-value>` or `<declaration-value>?`.

**Comment by KennethHoff** [comment]
Am I right in understanding that if/when this feature is generally available, using a comma-separator is more-or-less superceded by semicolon-separator? Everywhere we currently use comma we should use semicolon in order to make it less ambiguous? As in, they are entirely interchangeable except that the semicolon-separator additionally allows for "inline parameter list" using the now-available comma?

```css
// Old style
padding: 10,10,10,10;

// New and improved style
padding: 10;10;10;10;
```

**Comment by tabatkins** [comment]
After talking more internally in Chrome, especially in regards to the [`if()` syntax discussion](https://github.com/w3c/csswg-drafts/issues/10064), we'd like to revisit this resolution.

Note that it was resolved *just barely* in favor of the current approach - it went to a straw poll, and the voting was *tied* between "upgradeable commas" and "{} wrapper". (We decided in favor of upgradeable commas based on an instant runoff; it got more first-place votes.) I know that had @andruud attended that meeting, they'd have voted for "{} wrapper" and *against* upgradeable commas; possibly with another set of people we'd have gotten a result that leaned more strongly another way.

We've come to believe that there are a few good arguments against upgradeable commas, and in favor of {} wrapper instead. Some of them are impl-focused, others are author-focused:

1. Upgradeable commas, despite only being required for the handful of "arbitrary substitution functions" (toggle(), first-valid(), random(), mix(), etc), applies to all functions in the entire language. This is for consistency; it's a weird feature, and it would be even weirder, we believed, for it to only apply to a handful of function syntaxes. This means a decent bit of impl work to allow the "reparse upon encountering a semicolon" behavior for all existing functions, to no real author benefit.
2. Reparsing, kinda in general, isn't great for impls. We do it now for Nesting, to an extent, as it was unavoidable, but it would be nice to avoid that elsewhere when possible.
3. {} wrappers are "local" to the single problematic (comma-containing) argument, while comma-upgrading has to be applied to the entire function. Especially with longer functions, this might be easy to miss, causing some separate arguments to accidentally be parsed as a single comma-containing argument.
4. When you have a comma-separated list in the grammar, but the author only needs to supply a single item, *and* that single item has a comma in it, comma-upgrading is kinda screwed. There is *no way* to actually write this function, unless the grammar makes a special allowance for authors to put a bonus "comma" (aka a semicolon) after the last item (which is the current approach in `if()`.

A fuller example for 4 could make things easier to understand. Say you were writing an `if()`, with a single conditional clause that resolves to `"foo.svg", "bar.svg"` when it's true. You'd want to write this as `if(cond(...): "foo.svg", "bar.svg")`, but *that's actually invalid* - the comma is an argument separator instead, so it's actually *two* conditional clauses, one saying `cond(...): "foo.svg"`, and then another saying `"bar.svg"` (which is an invalid conditional clause). The *only* way to resolve this is that the `if()` syntax proposal allows a trailing comma, so you can write it as `if(cond(...): "foo.svg", "bar.svg";)` (with a trailing semicolon), to cause it to be reparsed into a single conditional clause containing a comma. Not only the *UA's* parser has to restart - as a human reading it, I have to spot the trailing semicolon and realize that the earlier comma was actually part of the value rather than an argument separator.

On the other hand, if we used {} wrappers, you'd write it as `if(cond(): {"foo.svg", "bar.svg"})`.

* No reparsing needed
* It's clear from the start of the value that it's being explicitly grouped (*probably* because it contains a comma). 
* No need to realize that there's something weird about this case in particular that you need to work around, you'd just *always* have to wrap comma-containing values in {}.

**Comment by benface** [comment]
Yes please.

**Comment by kbabbitt** [comment]
> 1. Upgradeable commas, despite only being required for the handful of "arbitrary substitution functions" (toggle(), first-valid(), random(), mix(), etc), applies to all functions in the entire language. This is for consistency; it's a weird feature, and it would be even weirder, we believed, for it to only apply to a handful of function syntaxes. This means a decent bit of impl work to allow the "reparse upon encountering a semicolon" behavior for all existing functions, to no real author benefit.
> 1. Reparsing, kinda in general, isn't great for impls. We do it now for Nesting, to an extent, as it was unavoidable, but it would be nice to avoid that elsewhere when possible.
> 1. {} wrappers are "local" to the single problematic (comma-containing) argument, while comma-upgrading has to be applied to the entire function. Especially with longer functions, this might be easy to miss, causing some separate arguments to accidentally be parsed as a single comma-containing argument.
> 1. When you have a comma-separated list in the grammar, but the author only needs to supply a single item, _and_ that single item has a comma in it, comma-upgrading is kinda screwed. There is _no way_ to actually write this function, unless the grammar makes a special allowance for authors to put a bonus "comma" (aka a semicolon) after the last item (which is the current approach in `if()`.

Agree with all of these points and would support re-resolving in favor of "{} wrapper" (it was my preference in the previous straw poll).

**Comment by mirisuzanne** [comment]
I think I may have voted the other way, but agree on review this is more consistently legible.

**Comment by nex3** [comment]
I believe `{}` is likely to have fewer compatibility issues with existing naive tools than `;`, because it doesn't break an assumption that a `;` will always end a CSS property. For Sass specifically, either syntax is easily workable.

**Comment by tabatkins** [comment]
And just to be clear about the actual spec text for this, we wouldn't allow {} wrappers just anywhere, so there's no need to upgrade the parsing of all functions, everywhere. Instead, it would be a change to the definition of the [comma-containing productions](https://drafts.csswg.org/css-values-5/#comma-containing-productions).

Currently (with the "upgradeable commas" feature), they're defined to *not* allow commas, *unless* the function is being reparsed in semicolon mode. (aka, if the function is currently in comma mode, the production ends at a comma or the `)` that ends the surrounding function)

With this change, instead they'd be defined in two branches. The production is either:
* a single {}-block, containing anything. (including commas, or more {} blocks, etc)
* a sequence of component values *other than* commas or {} blocks.

`var()` would get an explicit exemption here, as it needs (but, uh, currently doens't have *specced*) under the current approach. `var(--foo, "foo.svg", "bar.svg")` is valid today (resolving to `"foo.svg", "bar.svg"` is fallback is triggered) and almost certainly needs to be preserved. It doesn't actually run into the parsing issues that otherwise force this syntax feature, so it's just slightly unfortunate that it has to be inconsistent.

To aid in clarity, I'd probably swap them all to a new production, maybe `<any-argument>` (to parallel [`<any-value>`](https://drafts.csswg.org/css-syntax/#typedef-any-value)), which has these restrictions. `var()` would just stay with `<declaration-value>?`, as it has today.

**Comment by Loirooriol** [comment]
> we wouldn't allow {} wrappers just anywhere

So if a function accepts a single parameter, then `f({a})` uses `{a}` as the argument, but then if we add a 2nd optional parameter, then the argument will suddenly change to `a`? Seems bad for forwards compatibility.

**Comment by nex3** [comment]
Would `var(--foo, {"foo.svg", "bar.svg"})` resolve to `"foo.svg", "bar.svg"` or to `{"foo.svg", "bar.svg"}`? If the former, does that mean that `if(cond(...): var(--foo))` resolves to `"foo.svg"` if `cond(...)` is true?

**Comment by andruud** [comment]
Strong +1 to what Tab is proposing here.

> > we wouldn't allow {} wrappers just anywhere
> 
> So if a function accepts a single parameter, then `f({a})` uses `{a}` as the argument, but then if we add a 2nd optional parameter, then the argument will suddenly change to `a`? Seems bad for forwards compatibility.

Good point, but this would only be a problem for functions that accept `{}` in their parameters, right? So maybe there's no need to allow e.g. `rgb({0}, {128}, {0})`, since that's already invalid.

> Would `var(--foo, {"foo.svg", "bar.svg"})` resolve to `"foo.svg", "bar.svg"` or to `{"foo.svg", "bar.svg"}`?

This currently resolves to `{"foo.svg", "bar.svg"}`, and changing that definitely requires a use-counter. We _might_ be able to change this to optionally allow `{}` if we wanted, but we shouldn't rely on it. I highly doubt we'll be able to _require_ `{}`, though.

Related question: it may be too late for `var()`/`env()`, but what about `attr()`?

> If the former, does that mean that `if(cond(...): var(--foo))` resolves to `"foo.svg"` if `cond(...)` is true? If the latter, does that mean that `prop: var(--foo)` is invalid?

I don't think [arbitrary substitution functions](https://drafts.csswg.org/css-variables/#arbitrary-substitution) should be allowed to mess with the grammar of the calling function itself, just like you're not allowed to paste e.g. a fallback into another `var()`: `--fb:, myfallback;  --y: var(--x var(--fb)) /* invalid */`.

So when `--foo` is `"foo.svg", "bar.svg"`, then `--bar: if(cond(...): var(--foo))` is `"foo.svg", "bar.svg"` when the condition is true, and IACVT when the condition is false.

When `--foo` is `{"foo.svg", "bar.svg"}`, then `--bar: if(cond(...): var(--foo))` is `{"foo.svg", "bar.svg"}` when the condition is true, and IACVT when the condition is false.

**Comment by tabatkins** [comment]
> So if a function accepts a single parameter, then f({a}) uses {a} as the argument, but then if we add a 2nd optional parameter, then the argument will suddenly change to a? Seems bad for forwards compatibility.

I'm not sure what you mean by this. What's the grammar for that first argument? If it's a comma-containing production, then `f({a})` would be taking `a` as the argument. If it's anything else, it's almost certain that `{a}` would just be invalid, but if we ever *do* define an actual grammar taking that on purpose, it woudl work as normal.

The presence or absence of a second argument, optional or not, has nothing to do with this, and I'm not sure how you're reading that into what I wrote.

**Comment by tabatkins** [comment]
> Would `var(--foo, {"foo.svg", "bar.svg"})` resolve to `"foo.svg", "bar.svg"` or to `{"foo.svg", "bar.svg"}`? If the former, does that mean that `if(cond(...): var(--foo))` resolves to `"foo.svg"` if `cond(...)` is true? If the latter, does that mean that `prop: var(--foo)` is invalid?

Per my proposal above, the `var()` would resolve to `{"foo.svg", "bar.svg"}`. Then the `if()` gets the var() subbed in, producing `if(cond(...): {"foo.svg", "bar.svg"})`.

But as Anders said, we might be able to (and hopefully can) make var() more subtle, and allow enforcing the {} rules like other locations. (But, as they say, there's no way we can make it *require* {} around commas; it'll still need to allow top-level commas in its fallback for back-compat.)

If that's the case, then the behavior instead becomes:
* The `var()` would resolve to `"foo.svg", "bar.svg"`.
* It then subs into the `if()` to produce `if(cond(...): "foo.svg", "bar.svg")`, which is invalid syntax; the property becomes IACVT.
* The solution would be to write the `if()` as `if(cond(...): {var(--foo)})`. You can do this defensively; it works correctly whether the var() substitutes as a value with commas or not. This is similar to the current specced behavior, where you might need to defensively write your function like `if(cond(...): var(--foo);)` to ensure that *if* the var() substitution contains commas, it works properly (but is also fine if it doesn't).
* (The var() author could also defensively double-wrap their value in {}; only the outer one gets stripped by the grammar. But then it can't be safely used *directly* in properties. Not a good idea in general. Similarly, you shouldn't defensively write your custom property with a {} wrapper in its value, like `--foo: {"foo.svg", "bar.svg"};`, because it then can't be subbed directly into many locations.)

This defensive coding is slightly unfortunate but a required part of how var() (and all other arbitrary-substitution functions) work; they are *intrinsically* passing around raw syntax, not higher-level values. For example, a custom property could be `--foo: cond1(...): val1, cond2(...): val2;`, then used like `if(var(--foo), cond3(...): val3)`.

**Comment by tabatkins** [comment]
> I don't think [arbitrary substitution functions](https://drafts.csswg.org/css-variables/#arbitrary-substitution) should be allowed to mess with the grammar of the calling function itself, just like you're not allowed to paste e.g. a fallback into another var(): --fb:, myfallback;  --y: var(--x var(--fb)) /* invalid */.

Oh, hm, you're probably right actually. You indeed can't sub in arbitrary grammar like that, since var() is *actually* parsed while its surrounding context is left as unparsed tokens. I'll need to give this a little thought.

**Comment by andruud** [comment]
> since var() is actually parsed while its surrounding context is left as unparsed tokens.

Exactly. By default, I'd expect the same from any arbitrary substitution function. I don't think we should deviate for `if()`.

But this is a bit off-topic (we can ask roughly the same questions under upgradeable commas), so maybe we should open a new issue if more discussion is needed on that.

**Comment by tabatkins** [comment]
> But this is a bit off-topic (we can ask roughly the same questions under upgradeable commas), so maybe we should open a new issue if more discussion is needed on that.

Yup, #10947

**Comment by fantasai** [comment]
We resolved on using semicolons in `if()`. Are we still happy with this resolution?

**Comment by nt1m** [comment]
I quite liked @kizu's solution in https://github.com/w3c/csswg-drafts/issues/10064 which I'm surprised wasn't suggested here.

**Comment by Loirooriol** [comment]
@nt1m That was specifically for `cond()`. How would it be in genereal, wrapping the values with `{}`? That's basically the resolution here.

**Comment by tabatkins** [comment]
> We resolved on using semicolons in if(). Are we still happy with this resolution?

Yes. I'm a little *annoyed* that we went with a different syntax for `if()` specifically, when there was no need for it, but it is *slightly* special so whatever. But in general, the curly-brace resolution is still good for everything else.

**Comment by KennethHoff** [comment]
There's no reason we can't change it now though, is it? It hasn't shipped anywhere(?)

**Comment by tabatkins** [comment]
In theory no, but we literally decided on both of these (the new syntax for comma-containing arguments, and the syntax for if()) at the same meeting a few weeks ago, and explicitly handled the former first so it could influence the latter's discussion.

The WG just resolved differently than what I wanted, is all. It happens.

(I'm a little confused why @fantasai is asking if we're still happy about this, for exactly this reason. The two topics were discussed on the same day, immediately following each other, with explicit references between them, so I don't understand why this resolution would be in question.)

**Comment by cdoublev** [comment]
> If it does not start with a "{" token, then it cannot contain commas

`--custom: foo, bar` should remain valid so this restriction should only apply to comma-containing productions **in functions**. And I think `<{-token>` is consumed to a simple block defined with `}` as its ending token, so the condition should be *"if it starts with a simple block whose ending token is `}`"*.

I hope you do not mind that I did not open a separate issue for this.

**Comment by tabatkins** [comment]
> --custom: foo, bar should remain valid so this restriction should only apply to comma-containing productions in functions.

Ah yes, you are completely correct. I accidentally dropped the context that this only applies within functions when I rewrote the text, thanks.

> And I think <{-token> is consumed to a simple block defined with } as its ending token, so the condition should be "if it starts with a simple block whose ending token is }".

Yeah I was wondering which way I should write it. You're probably right that I should just do treat it as a block, since grammars never see the { tokens themselves.

**Comment by cdoublev** [comment]
Based on the current definition of a [non-strict comma-containing production](https://drafts.csswg.org/css-values-5/#non-strict-comma-containing-production):

  - `opacity: var(--custom, 1 {})` is **valid**
  - `opacity: var(--custom, {} 1)` is **invalid**

Both are **valid** in the current version of Chrome and Firefox.

@tabatkins, could you please tell me if breaking backwards-compatibility is intentional?

I am not sure I fully understand the previous comments but I suspect that only a standalone {}-block should act differently.

**Comment by fantasai** [comment]
Re-opening to follow up on @cdoublev's comment.
