### ISSUE TITLE
[css-view-transitions-2] Allow changing `types` using JS after (MPA) transition started?

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9542]
Currently we're only allowing to set the transition types at `startViewTransition`, and they can get changed when revealing the new document in a cross-document view transition.

But perhaps we can allow the author to read or change the types programmatically, as a `DOMTokenList` on the VT object?
Something like this:

```js
document.addEventListener("pagereveal", event => {
  const {viewTransition} = event;
  const hasSlideIn = viewTransition.typeList.has("slide-in");
  if (heroImage.loaded) {
     viewTransition.typeList.toggle("expand-hero", true);
  }
});
```

Note that this is possible to do today using the CSSOM, but not dynamically while the VT is already running.

**Comment by noamr** [comment]
Proposed resolution from internal sync: have a `typeList` attribute in a `ViewTransition` object that can mutate types at any point.

**Comment by bramus** [comment]
Follow-up issue about the `type` argument which was brought up in the meeting: https://github.com/w3c/csswg-drafts/issues/10070
