### ISSUE TITLE
[css-view-transitions-1] Handle startVT/cross-doc transitions when Document is hidden

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9543]
If `startViewTransition` is called while a Document is hidden. Or the document is hidden at any point during the transition's lifecycle, we don't do anything special. We should probably explicitly skip the transition if the Document is hidden.

Not sure what to do with iframes. The UA can stop rendering opportunities if the iframe is far enough for the viewport. Should we assume its hidden?

The spec way of when a Document is hidden can be based on [this](https://html.spec.whatwg.org/#update-the-rendering:~:text=The%20step%20labeled%20Rendering%20opportunities%20prevents%20the%20user%20agent%20from%20updating%20the%20rendering%20when%20it%20is%20unable%20to%20present%20new%20content%20to%20the%20user%20(there%27s%20no%20rendering%20opportunity).) : The step labeled Rendering opportunities prevents the user agent from updating the rendering when it is unable to present new content to the user. If the Document is in this state, skip all ViewTransitions?

**Comment by noamr** [comment]
What would happen given the current spec is that the transition would be delayed until the page is visible or the timeout passes. Perhaps for iframe this is OK, and for explicitly hidden pages we can skip immediately?

**Comment by khushalsagar** [comment]
> What would happen given the current spec is that the transition would be delayed until the page is visible or the timeout passes.

Right now it depends on when the page is hidden. If its before rendering has been frozen then we'll keep waiting for the next frame. If its during rendering frozen then we timeout. And if its after the DOM has been constructed then it will wait until all animations are finished. I'm not sure how we deal with animation progress for hidden Documents but if that's checked when the Document is made visible again then likely we'll discover the transition to be finished then?

> Perhaps for iframe this is OK, and for explicitly hidden pages we can skip immediately?

Sounds reasonable. If the Document is hidden, that probably means the user doesn't care to see an animation when its made visible again. We can render the new DOM directly.

For the iframe case, browsers can stop rendering the iframe if its far off from the viewport. That means sometimes authors might see a timeout error if the iframe goes offscreen right after the transition was initiated. Its rare enough that we can ignore this case. But this was why I was leaning towards using a "rendering opportunity" based definition. So we skip for any case where the Document is not going to produce any more frames.

**Comment by khushalsagar** [comment]
**Proposed Resolution**
Any active transition is immediately skipped when the Document's [visibility state](https://html.spec.whatwg.org/#visibility-state) changes to "hidden". If startVT is called while the Document is in this state, that is also immediately skipped.

It's unclear what to do for offscreen iframes, filed https://github.com/w3c/csswg-drafts/issues/9839 for that.

**Comment by khushalsagar** [comment]
The proposal is for same and cross-document transitions.
