### ISSUE TITLE
[css-selectors-4] The column combinator is not a combinator 

### ISSUE THREAD

**Issue by InSyncWithFoo** [w3c/csswg-drafts#9544]
According to [the grammar](https://drafts.csswg.org/selectors/#grammar) and its name, it is one:

```ebnf
<combinator> = '>' | '+' | '~' | [ '|' '|' ]
```

Yet [&sect; 3.1. Structure and Terminology](https://drafts.csswg.org/selectors/#structure) says it's not:

> A **_combinator_** is a condition of relationship between two elements represented by the [compound selectors](https://drafts.csswg.org/selectors/#compound) on either side. Combinators in Selectors Level 4 include: the [descendant combinator](https://drafts.csswg.org/selectors/#descendant-combinator) (white space), the [child combinator](https://drafts.csswg.org/selectors/#child-combinator) (U+003E, `>`), the [next-sibling combinator](https://drafts.csswg.org/selectors/#next-sibling-combinator) (U+002B, `+`), and the [subsequent-sibling combinator](https://drafts.csswg.org/selectors/#subsequent-sibling-combinator) (U+007E, `~`).

Am I missing something?

**Comment by andruud** [comment]
Huh. Is it an editing mistake?

**Comment by tabatkins** [comment]
It got left in the grammar, yeah.

**Comment by cdoublev** [comment]
I do not understand the change. How `col || td` is supposed to match `<complex-selector>` now that `'|' '|'` is removed from `<combinator`? 

Maybe it could have just been listed in section 3.1. Otherwise, this is no longer required in [18. Grammar](https://drafts.csswg.org/selectors-4/#grammar):

  > White space is forbidden: [...] Between the components of a `<combinator>`.

**Comment by bramus** [comment]
> I do not understand the change. How `col || td` (as in [16.1. Column combinator (`||`)](https://drafts.csswg.org/selectors-4/#the-column-combinator)) is supposed to match `<complex-selector>` now that `'|' '|'` is removed from `<combinator>`?

Yeah, also not following here. Or is the plan to remove the column combinator from selectors-4?

**Comment by tabatkins** [comment]
Clearly I'd just made a *second* mistake, in not realizing that the column combinator was still listed as a feature in the spec. (The utter lack of implementor interest in the years since it was added likely caused me to misremember it as already having been removed.) I'll put it back for now.

**Comment by tabatkins** [comment]
It's not. Tho technically it's still correct: the selectors do *include* those listed ones, there's just more than what's listed. ^_^
