### ISSUE TITLE
[css-2023] Finish up CSS Snapshot 2023

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9566]
As the year is slowly coming to an end, the 2023 snapshot should be wrapped up and published soon.

While there were a lot of spec. updates this year, it seems to me there was one that's fairly stable now, which is [CSS View Transitions Level 1](https://www.w3.org/TR/css-view-transitions-1/).

[CSS Scroll Snap Level 1](https://www.w3.org/TR/css-scroll-snap-1/) should probably be removed from the "Fairly Stable" section because it's already in the "Rough Interoperability" section.

Other specs which were part of the Interop 2023 project might be added as well to the "Rough Interoperability" section. Though that still needs to be checked.

Sebastian

**Comment by svgeesus** [comment]
Agreed, View Transitions 1 is a CR Snapshot and the [test results](https://wpt.fyi/results/css/css-view-transitions?label=experimental&label=master&aligned) show a single implementation doing well.

**Comment by svgeesus** [comment]
> [CSS Scroll Snap Level 1](https://www.w3.org/TR/css-scroll-snap-1/) should probably be removed from the "Fairly Stable" section because it's already in the "Rough Interoperability" section.

Good catch, [fixed](https://github.com/w3c/csswg-drafts/commit/785e1d92b6104bf38c7976ff77ddad9d0c6f5cd4)

**Comment by svgeesus** [comment]
@tabatkins @khushalsagar @jakearchibald thoughts on moving View Transitions 1 to "fairly stable"?

**Comment by khushalsagar** [comment]
Yea, that sounds good to me.

We had 3 minor issues resolved since the last CR snapshot, I've sent a PR for them : https://github.com/w3c/csswg-drafts/pull/9575/. Let me know if you need an up-to-date CR snapshot before making this switch.

**Comment by svgeesus** [comment]
@khushalsagar I merged your PR. As editor, you can commit directly on isses with consensus and resolved discussion.

In terms of updating your spec, that would be a CR Draft and just requires a CSSWG resolution. You can propose an async resolution for stuff like that. However, the snapshot probably won't be published until the end of this year so don't wait for that. And moving specs withing the various buckets of the snapshot requires a CSSWG resolution, too.

**Comment by SebastianZ** [comment]
> > [CSS Scroll Snap Level 1](https://www.w3.org/TR/css-scroll-snap-1/) should probably be removed from the "Fairly Stable" section because it's already in the "Rough Interoperability" section.
> 
> Good catch, [fixed](https://github.com/w3c/csswg-drafts/commit/785e1d92b6104bf38c7976ff77ddad9d0c6f5cd4)

Should have been the other way round, i.e. it should be in the "Rough Interoperability" section as we have an [interoperability of ~96% according to WPT](https://wpt.fyi/results/css/css-scroll-snap?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-scrolling).

Sebastian

**Comment by SebastianZ** [comment]
Adding this to the agenda as the end of the year is approaching.

Topics to discuss:

* Add CSS View Transitions 1 to the "Fairly Stable" section
* Any other specs to add?
* Publish as Group Note
* Aside: Also publish CSS 2022 as Group Note (currently still Group Draft Note)

Sebastian

**Comment by svgeesus** [comment]
> Should have been the other way round, i.e. it should be in the "Rough Interoperability" section 

No, the order (from most complete to least complete) is:

[2.1 Cascading Style Sheets (CSS) — The Official Definition](https://drafts.csswg.org/css-2023/#css-official)
[2.2 Fairly Stable Modules with limited implementation experience](https://drafts.csswg.org/css-2023/#fairly-stable)
[2.3 Modules with Rough Interoperability](https://drafts.csswg.org/css-2023/#rough-interop)

2.2 means "completed design work, and are fairly stable" while 2.3 means "their details are not fully worked out or sufficiently well-specified and they need more testing and bugfixing" i.e. not completed.

See for example 
 - https://github.com/w3c/csswg-drafts/issues/6908

where a spec was moved up from 2.2 Fairly Stable to 2.1 Official (the issue being that it was copied not moved, so occurred in both places).

**Comment by svgeesus** [comment]
Publication requested 5 December, expected 7 December

**Comment by SebastianZ** [comment]
Probably a bit late now but I wonder whether Motion Path 1 should be added to "Rough Interoperability". It's still a WD, though it was [covered by the Interop 2023](https://wpt.fyi/results/css/motion?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-motion) initiative and gained an interoperability of 99% (with Mozilla just having published their [intent to ship the remaining parts](https://groups.google.com/a/mozilla.org/g/dev-platform/c/TNdVbrT-j8o/m/8UUjk6GyAgAJ) of their implementation).

Sebastian

**Comment by svgeesus** [comment]
Certainly too late for this week's publication, but we could squeeze in another one this year if we get consensus to add it. If not, it would be CSS 2024 which I believe we should get started on early in 2024.

**Comment by astearns** [comment]
Let’s use this as the reason to start snapshot 2024

**Comment by svgeesus** [comment]
> Let’s use this as the reason to start snapshot 2024

- https://github.com/w3c/csswg-drafts/issues/9681

**Comment by svgeesus** [comment]
[Published today](https://www.w3.org/TR/2023/NOTE-css-2023-20231207/)
