### ISSUE TITLE
[css-anchor-position][css-position] Fixing the animation problem

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#9598]
Edit: This comment's proposal is out of data, our current proposal is [over here](https://github.com/w3c/csswg-drafts/issues/9598#issuecomment-1836854109).

Issue: Because the inset properties are four separate properties, you can't animate them "together" - instead you can animate each of the four independently, and hope that what you're expressing is reasonable for that to work. That's not always true!

For example, going from `bottom: anchor(top);` to `top: anchor(bottom);` (with the opposite inset being `auto`) will *not* animate properly - it'll be trying to interpolate `top` from `auto` to `anchor(bottom)` (which won't work), and similar for `bottom`. You *can* explicitly write a `top/bottom: 0;` in each case, which will technically animate, but not in a useful way; now, to get things to line up correctly, you'll need to specify `align-self` too:

```css
.first {
  top: 0;
  bottom: anchor(top);
  align-self: end;
}
.second {
  top: anchor(bottom);
  bottom: 0;
  align-self: start;
}
```

...and `align-self` doesn't have animation rules to smoothly animate from `start` to `end` (yet, #9556). (And even if we did, it wouldn't work quite correctly - an `align-self: start 50%;` will center in an IMCB with a top of `(0% + anchor(bottom))/2` and a bottom of `(0% + anchor(top))/2`, and that is very likely *not* halfway between its starting and ending position. In general, this sort of "interpolate a position within an interpolating range" doesn't produce a linear interpolation of the position in an absolute context; it produces a quadratic spline path instead.)

--------

So that's the issue. How do we solve it? Here's my suggestion:

1. Repurpose `inset-area`. In addition to the existing grid-based syntax, add a `[ <side-keyword> <length-percentage> ]{1,4}` production, which similarly defines a rectangle and causes `auto` insets (and `normal` self-alignment) to resolve accordingly. So `inset-area: top anchor(bottom);`, for example.
2. Change the inset-area rules so that, rather than resolving `auto` insets (and `normal` self-alignments) at computed-value time, they resolve at used-value time. This removes the ability to animate the inset properties directly from the inset-area value.
3. Instead, make `inset-area` directly animateable. Add `inset-area-mix(...)`, which represents the interpolated result between two `inset-area` values. This represents whatever insets and alignments would be required to make the position of the element interpolate smoothly between the two endpoints (rather than being a naive interpolation of edges and alignment). So long as all your actual inset properties and self-alignment properties are set to `auto`/`normal`, it'll Just Work.

I still need to give a little more thought to how the new side-based production handles alignment. In the grid syntax I can *pretend* that the default anchor is inside the containing block, so all the grid lines are correctly ordered and I can infer some positioning, but that's more difficult when the edges can indeed be misordered due to positioning. I'm pretty sure there's a good solution here, I just haven't fully worked thru it yet.

**Comment by tabatkins** [comment]
Talking this over with @fantasai, she pointed out that this will create very weird and confusing ergonomics for developers using positioning. So we suggest to rejigger it a bit.

Issues with above proposal:
    * doesn't let you animate from a position specfied with `inset-area` to one specified with inset properties
    * doesn't let you cascade the various positioning bits separately like you can do today (you'd be forced to indirect thru custom props)
    * creates a confusing duplication with the existing `inset` and alignment properties
    
So instead of messing with `inset-area`, the new proposal is to use a new, fairly magical, property
    * provisionally called `position-animation`
    * captures all the relevant data to resolve the element's margin box position (as described above)
    * authors can only specify `split` or `combo`, initial value `split` (for back-compat)
    * `split` gives today's behavior, where insets and alignment properties all animate independently. When animating between `split` and any other value, the interpolated value is `split`.
    * `combo` magically resolves at computed-value time to a package of all the relevant data (a "position package"). The used value of a "position package" is the size and position of the element's margin box, after resolving insets/alignment.
    * getComputedStyle serializes `split` as `split`, and any other computed value as `combo`.
(This way we don't need to expose syntax or serialization of position packages, they're internal to the UA.)
    * There exists a computed-value representation for interpolating two "position package", so that we can represent intermediary states. The used value of the interpolation of two "position packages" is the interpolated position of each margin edge of the box. (This effectively requires the used-value layout information of both packages.) Thus, if both sides are a "position package", the element's actual position animates smoothly between the endpoints.
    
So, authors can write:

```css
.foo { 
    position: absolute; 
    position-animation: combo; 
    transition: position-animation 1s; 
}
.foo.start { 
    top: 0;
    bottom: anchor(top);
    align-self: bottom;
}
.foo.end {
    top: anchor(bottom);
    bottom: 0;
    align-self: end;
}
```

...and when they swap the classes from `.start` to `.end`, it will smoothy animate the element's position, rather than doing a weird unintuitive animation, or not animating at all.

Using this, we can animate all of the following cases:
    * `top: auto` to `top: <length>`
    * `inset-area: <anything>` to `inset-area: <anything>`
    * `top/left/bottom/right` to `inset-area`
    * `anchor(--foo top)` when the element with `anchor-name: --foo;` changes
    * (maybe?) `top: 0` when the element establishing the abspos containing block changes (if we want to include abspos containing block resolution info in the package)

~fantasai and Tab

**Comment by andruud** [comment]
None of the issues listed with the first approach strike me as huge problems, whereas the "position package" proposal introduces a likely problematic layout dependency (the "magic"), and intermediate values that can't be represented. I'm not sure that's a net win as far as "issues" go, and I'm also not sure if this _can_ be reasonably implemented, but it's an interesting direction to explore regardless. Especially if it could solve the anchor change case.

I'm confused by the model as stated, however. We seem to want to do layout of the box ignoring the "position package" (to determine what goes into the package), but then also it's really the position package that has the final say for the size/position?

> provisionally called position-animation

I see the "provisionally", but I'd avoid anything related to "animation" in the property name. The animated aspect of this should come from the act of animating/transitioning the thing, not as an intrinsic part of the property.

> split or combo

I don't think we actually need to have two values. Any interpolated state (that's not at the endpoints) can automatically behave as "combo".

> getComputedStyle serializes split as split, and any other computed value as combo.
(This way we don't need to expose syntax or serialization of position packages, they're internal to the UA.)

It feels so wrong. :-) Would this be the first thing we can't even represent with Typed OM?

**Comment by tabatkins** [comment]
> None of the issues listed with the first approach strike me as huge problems

I think they are pretty reasonable usability issues. Nothing *technically* wrong with what's in the first post, but it's not a great layering.

> a likely problematic layout dependency

The second proposal is exactly identical in terms of power and layout dependency as the first. It allows literally no new abilities, save that it can interact directly with top/left/etc rather than requiring them to be packed into an inset-area value.

Literally, this was intended to be *absolutely nothing* but a movement of syntax; rather than blessing inset-area as "the way to get good position animation" and relying on inset:auto to not override that (which then requires us to recreate top/left/etc in inset-area, so we can actually do the things those properties are good at), we just move the "good position animation" thing to a third property, so we can continue to use top/left/etc as normal *and* still have it interact with inset-area as necessary. If you're reading anything else into this, that's just a failure on our part to communicate it well.

> I don't think we actually need to have two values. Any interpolated state (that's not at the endpoints) can automatically behave as "combo".

No, we have to have `split` because people can animate the inset properties today and get the existing not-particularly-great behavior. And if they got this by specifying `transition-property: all`, then that would apply to the new prop as well, and change their behavior.

**Comment by andruud** [comment]
> Literally, this was intended to be absolutely nothing but a movement of syntax;

Ah, OK. That's not how I read it. But I think I get it now, thanks. Instead of the author explicitly creating the "position package" via inset-area (v2), it's sort of automatically created from the existing inset properties and other stuff known at computed-value time.

However, it does go slightly beyond moving the syntax around if it solves the named anchor change issue. :-)

> No, we have to have split [...]

Right, `transition:all`. I always forget about that.

**Comment by lilles** [comment]
Maybe I should have been able to infer from the discussion above, but what happens if you animate an inset property at the same time as animating the position package?:  `transition-property: top, position-animation`

Just does not interpolate `top` separately if `position-animation` is `combo`?

**Comment by tabatkins** [comment]
> However, it does go slightly beyond moving the syntax around if it solves the named anchor change issue. 

Well, sure, but as we discussed internally, the named anchor change issue should end up being fixed anyway, with proper definition and reference to the machinery driving cq transitions.

> what happens if you animate an inset property at the same time as animating the position package

I'm open to whatever behavior in that case. We could snapshot, or live-update, whatever's more reasonable for impls. There's no user argument for one behavior or another.

**Comment by kizu** [comment]
As a curious sidenote: when I was playing with “polyfilling” the `position-area` using the existing anchor positioning, I did stumble upon several transition issues, mostly related to aligning the popover close to the target based on the side it is shown.

The way I solved it in my case was by having two elements, and having transitions for a) inset properties (which were never `auto`), and the grid columns and rows (as a way to handle the “auto” aligning).

Here is this experiment: https://codepen.io/kizu/pen/zYMmVJd

(this comment is mostly as “as an author I did encounter this issue, would be happy with any solution, and for some cases we _might_ have some workarounds already, though not ideal ones”).

**Comment by tabatkins** [comment]
Okay, further discussion with Anders and Rune led to some more evolution in this idea. They pointed out that the “`inset-area` affects `inset:auto` values” thing can't actually be done at computed-value time, like I hoped, because it relies on the writing mode of the containing block, and the containing block tree isn't built until later. So `inset-area` can't turn into animatable computed values *anyway*.

But, now that we're entertaining the “just make a magic way to animate good” solution, we don't actually need `inset-area` to be itself animatable in the first place. We can return `inset-area` to modifying the containing block itself, like in Apple's [earlier draft](https://fantasai.inkedblade.net/style/specs/css-anchor-exploration/), and still retain the animatability we wanted. This means that the `inset` properties would now *compose with* `inset-area`, rather than being an *alternative to* it.

So @fantasai and I have an expanded Round 3 of the proposal:
    
1. `inset-area` just changes the containing block, and `inset` properties then inset from that modified block (as [proposed by Apple](https://fantasai.inkedblade.net/style/specs/css-anchor-exploration/#area-insets) in July)
	* This is a better separation of functionality.
	* Allows for more powerful offsetting than margins do (because margin %s are always relative to inline avaiable space, while inset %s are relative to their own axis).
	* Lets us fix overconstrained cases when the anchor starts outside of the CB in a more deliberate way (rather than just relying on the 'top'/'bottom' /etc biasing rules).
	* Also addresses the “absolute positioning, but in reference to the element I specify, not the nearest positioned ancestor” use case.
2. `auto` insets always compute to 0 when `inset-area` is non-`none`.
3. `normal` alignment adjusts based on the `inset-area` (per axis):
	* If the `inset-area` is center, or all three tracks: `normal` alignment resolves to `anchor-center`
	* Otherwise: `normal` aligns towards the “missing” areas.
	* Examples: `inset-area: top / all;` would align as `align-self: end; justify-self: anchor-center;`, while `inset-area: top / left center;` would instead use `justify-self: end;`/
4. “Good” interpolation is done by a separate property (provisionally called 'position-animation') that represents the used position, see [positioning package method, above](https://github.com/w3c/csswg-drafts/issues/9598#issuecomment-1817244328).

**Comment by tabatkins** [comment]
> Is that really better than authors having to set insets to 0 explicitly?

Well, without that, you have double-auto inset behavior, which currently implies invoking static positioning (*instead of* actually positioning relative to the anchor, which you're clearly indicating you want).

Are you imagining some additional behavior to make double-auto insets work differently in the presence of inset-area?

> and let the anchored element be positioned according to the alignment given by the inset-area spans?

Note that that's already done in the proposal in item (3), by having inset-area change the behavior of `normal` self-alignment. But it does depend on having a reasonable inset-modified CB set up, which is why the current definition resolves auto insets to 0.

**Comment by tabatkins** [comment]
> I thought the double-auto inset behavior is what I wanted if I didn't apply any inset properties.

Unless we define something else, the double-auto inset beahvior is the "position yourself to the static pos" behavior, which doesn't pay attention to inset-area (or anything else directly position-related). Could you elaborate on what you are expecting the behavior to be?

> I didn't understand how you could possibly get the intrinsic sizing behavior if you forced auto insets to 0

The legacy behavior where absposes stretch to fill their inset-modified containing block is trigger by `align/justify-self: stretch;` (or, currently, `align-self: normal;`, which acts like `stretch` by default). If you use any other alignment, you get the intrinsic sizing behavior, and then it aligns within the IMCB instead. See <https://drafts.csswg.org/css-align/#justify-abspos> for details. 

The proposal here changes `align-self: normal`, when `inset-area` is used, to behave in that latter fashion. No need to explicitly size the element.

**Comment by FremyCompany** [comment]
Also see https://github.com/w3c/csswg-drafts/issues/9862

**Comment by FremyCompany** [comment]
Also see https://github.com/w3c/csswg-drafts/issues/9945

**Comment by astearns** [comment]
Reminder to @frivoal @khushalsagar and @emilio to post the responses we did not have time for in the meeting here

**Comment by khushalsagar** [comment]
Its unclear how we deal with the fact that the anchor's position can change in the middle of the animation. Its possible you're interpolating from top to left, there is an active scroll, and while we're in the middle of the top->left interpolation the position fallback algorithm changes the end state to bottom.

**Comment by dbaron** [comment]
I think the general handling that's in CSS transitions for style changes that happen in the middle of a transition and change the end state ought to handle that sort of case reasonably.  Transitions has a bunch of special cases for the timing of such a change *if* the new endpoint is the old start point, that is, when the original change is being reversed -- but otherwise you should just end up with a regular new transition from the current point in the old transition to the new destination.  As long as the `magic` animation of positions picks up the values from the current point in the animation, I think this ought to animate smoothly from the current position.  (At least, I'm assuming a smooth animation is what's desirable.)

I admit it's not quite smooth in that the old transition stops suddenly while the new one starts smoothly as though the old position were static, but I haven't heard complaints about that behavior for other types of animations.

**Comment by khushalsagar** [comment]
> I think the general handling that's in CSS transitions for style changes that happen in the middle of a transition and change the end state ought to handle that sort of case reasonably.

I agree that as long as the end state of the property being interpolated by the CSS transition is updated when the anchor position changes, it should work. But the model @fantasai was describing had some sort of "reflect"/"override" modes, where in reflect mode the browser is computing the anchor position (using all the fallbacks) as usual. And when the CSS transition is triggered, we switch to an "override" mode where the interpolated position applies until the end of the transition. We don't recompute the anchor position. With this model the anchor position won't retarget until the end of the transition which would be incorrect.

**Comment by andruud** [comment]
> <fantasai> TabAtkins: our implementers think something similar to this is going to work

Yes, but as we've discussed before internally Tab, I don't like the very animation-specific feel of this, nor the magic behavior of `magic`, which serializes as one thing, but "is" another thing. We may have precedent for this, but it feels like a last resort. So I'll propose a tweak to what has been discussed so far. "Boring", because it's less magical.

Boring Position Package
--------

The position/size of the element can be affected by many things:

- left, right, top, bottom
- align-self, justify-self
- inset-area
- sizing properties

But ultimately, it must result in a rect [X,Y,W,H] in some reference frame.

Perhaps we can give the author the power to optionally override this [X,Y,W,H] with a new property, tentatively called `extent` (is that available?). The `extent` property is the thing which _actually_ determines the used position/size of the element, it just happens to resolve to the aforementioned [X,Y,W,H] by default.

`extent: normal | auto | <length>{4}`

- `normal`
  - Initial value. Computes to `normal`.
  - The extent is whatever came out of insets/alignment/sizing, i.e. [X,Y,W,H].
- `auto`
  - Computes to Xpx Ypx Wpx Hpx.
  - This means `auto` is resolved into pixels by "style interleaving", and that transitions can happen whenever `auto` changes to something else.
- `<length>{4}`
  - Computes to those lengths, in pixels. Using this means that inset/alignment/sizing properties don’t actually affect the result.
  - The main purpose of this is not for direct author use, but as interpolated values generated by animation effects.

Unanswered question: What is [X,Y] relative to? (We have to answer this question also for the non-boring position package).

The above would not affect what we need to implement, nor the problems we need to solve vs. the non-boring position package, but I think this results in a less magical API.

Usage:

```
extent: auto;
transtion: extent 1s;
```

**Comment by fantasai** [comment]
@andruud The reason I pushed to have the rects serialize out as `magic` and not be parseable in CSS syntax is that this property effectively overrides everything that affects positioning and layout in CSS regardless of its cascade level. I don't think we should be giving authors access to such a tool, even if we need it internally to make the animations work.

**Comment by emilio** [comment]
I commented on this in the F2F, but I think this is a lot of complexity and magic, to the point where it might be worth punting to L2 along with `::tether`. It's also not so clear to me if this would deal correctly with various edge cases around moving the anchor around or changing the popup contents...

**Comment by FremyCompany** [comment]
A compromise is to support position interpolation but not size interpolation. This can be implemented very efficiently by having the `translate` property be the way the popup's top-left corner (in LTR-TB writing mode) is positioned, and allowing transitions on that property. If however the popup changes design or layout as a result of the positioning, it changes design immediately (pending a better mechanism to deal with it).

I'm not a fan of the "intermediary sizes are just interpolation of a rectangle" thing, it's not efficient and I don't think it makes sense in the vast majority of the cases where it will happen.

**Comment by andruud** [comment]
@fantasai Right, I was a bit surprised by this, as it contradicted what Tab and I discussed a few days before. But I do see the problem.
