### ISSUE TITLE
[css-fonts-5] Do ic-width and ic-height change depending on text orientations?

### ISSUE THREAD

**Issue by shivamidow** [w3c/csswg-drafts#9599]
Related spec: https://www.w3.org/TR/css-fonts-5/#valdef-font-size-adjust-ic-width

The spec defines ic-width as "Normalize the horizontal wide pitch of the font, using the advance width of “水” (CJK water ideograph, U+6C34) divided by the font size.".

My question is simple. Are ic-width and ic-height metrics affected by text orientation?

For your understanding, I drew the problem. 
<img width="826" alt="Screenshot 2023-11-13 at 4 58 12 PM" src="https://github.com/w3c/csswg-drafts/assets/1933045/3bdc0844-9f73-45d9-8e1d-91c1ad42b213">

If we apply `font-size-adjust: ic-width from-font;' to [A], [B], and [C], which should be used for each case, 1) or 2)?

I assume browser engines consistently use 1) for cases (this is gecko's behavior in my investigation [1]) but I want to clarify it. The current Blink and WebKit use 1), 1), and 2) for the three cases, respectively. They simply rely on `ideographicFullWidth` but this value is 1) in the horizontal mode, but 2) in the vertical mode.

As a scale unit, I think `ic-width` and `ic-height` should be consistent regardless of text orientation (i.e., `ic-width` should always be the advance width measured in the horizontal mode, 1)), but I want to make sure.

[1] https://searchfox.org/mozilla-central/source/gfx/thebes/gfxDWriteFonts.cpp#345

**Comment by shivamidow** [comment]
CC'ed @kojiishi @nt1m @jfkthame

**Comment by fantasai** [comment]
No, these are intentionally absolute. See https://github.com/w3c/csswg-drafts/issues/6288
