### ISSUE TITLE
[css-nesting] Specificity of contextually-invalid selectors.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9600]
Consider something like:

```html
<!doctype html>
<style>
p {
  color: green;
}

*, ::before {
  & * {
    color: red;
  }
}

:is(*, ::before) * {
  color: purple;
}
</style>
<p>Which color is this?
```

That's red in browsers, quite surprisingly, because `::before`, even though is invalid when nested (`:is(*, ::before)` or so wouldn't parse it), still contributes to specificity. `p` should win due to specificity otherwise, and the text should be green.

That seems pretty confusing? It's even more confusing when nesting `:has()` etc. But "fixing" it is actually relatively annoying.

What is the expected result here? What should be the expected result of something like nesting `:has()` inside `:has()` which suffers from the same issue? 

cc: @dshin-moz, @andruud, @tabatkins, @LeaVerou, @mdubet

**Comment by Loirooriol** [comment]
This is also exposing the fact that Firefox considers the specificity of a pseudo-element to be the same as a type selector, while Blink seems to treat it as a class selector? I believe this might not be observable before CSS nesting.

```html
<!DOCTYPE html>
<style>
p { border: 20px solid }

*, ::before { & { border-left-color: red; }}
p { border-left-color: green; }

p { border-right-color: red; }
*, ::before { & { border-right-color: green; }}

*, ::before { &.p { border-top-color: red; }}
.p.p { border-top-color: green; }

.p.p { border-bottom-color: green; }
*, ::before { &.p { border-bottom-color: red; }}
</style>
<p class="p">Which color is this border?</p>
```
