### ISSUE TITLE
[css-multicol] Provide a method to strictly specify column-width

### ISSUE THREAD

**Issue by ludela4** [w3c/csswg-drafts#9614]
In a writing-mode: vertical, it's possible to create a website that displays vertical text in a vertical scroll format using columns, as shown in the example below. 

https://jsfiddle.net/bdx6hyjm/3/ 

This is highly convenient for creating pages for smartphones in languages like Japanese, where vertical writing is common. This display format is also commonly used in Japanese newspapers.

However, when creating such vertical writing pages, developers cannot strictly specify the column height (column-width).

This is due to the current specification of column-width:

> The actual column width may be wider (to fill the available space), or narrower (only if the available space is smaller than the specified column width).

In practice, in many cases when displayed in a browser, the screen height seems to be considered as the column-width.

Being able to strictly specify the column-width would be convenient and increase flexibility in layout design.

**Comment by Loirooriol** [comment]
I think this is supposed to work with `justify-content`: https://drafts.csswg.org/css-align-3/#distribution-multicol

> In the case of multi-column containers with a non-[`auto`](https://drafts.csswg.org/css-multicol-1/#valdef-column-width-auto) [`column-width`](https://drafts.csswg.org/css-multicol-1/#propdef-column-width), [`justify-content`](https://drafts.csswg.org/css-align-3/#propdef-justify-content) values other than [`normal`](https://drafts.csswg.org/css-align-3/#valdef-justify-content-normal) or [`stretch`](https://drafts.csswg.org/css-align-3/#valdef-align-content-stretch) cause the columns to take their specified column-width rather than stretching to fill the container. The column boxes are then aligned as specified by justify-content.

But I don't think this has been implemented anywhere.

**Comment by tabatkins** [comment]
Yup, exactly. Already handled by the spec; browsers just need updating.
