### ISSUE TITLE
[css-color-4] Incorrect step in gamut mapping algorithm

### ISSUE THREAD

**Issue by facelessuser** [w3c/csswg-drafts#9618]
I believe step 15 of the GM algorithm is incorrect.

> return current as the gamut mapped color

It should be

> return clipped as the gamut mapped color

The reason why this is incorrect is that the algorithm is reducing chroma until it is reasonably close to a clipped version of itself, such that there should be no noticeable difference. The chroma-reduced color is not guaranteed to be within gamut, but the clipped version is, though the visual difference should be negligable. This was originally the intent in the revised proposal https://github.com/w3c/csswg-drafts/issues/7135#issuecomment-1066121795.

**Comment by svgeesus** [comment]
I agree, this is an error that crept in, it was always supposed to be the clipped value that was returned. The result as currently specified is similar, but has extra pointless work when we already have a result.
