### ISSUE TITLE
[css-values-4] Normalization of arc trigonometric function values

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9625]
The [spec](https://drafts.csswg.org/css-values-4/#funcdef-asin) wants the angle returned by `acos()`, `asin()`, `atan()`, `atan2()`, to be normalized to the appropriate range.

  > The angle returned by `asin()` must be normalized to the range `[-90deg, 90deg]`; the angle returned by `acos()` to the range `[0deg, 180deg]`; and the angle returned by `atan()` to the range `[-90deg, 90deg]`.

  > The `atan2(A, B)` function [...] returns the `<angle>` [...]. The returned angle must be normalized to the interval `(-180deg, 180deg]`

But later in [type checking](https://drafts.csswg.org/css-values-4/#css-nan), it requires to produce NaN for some arguments:

  > Certain argument combinations in math functions are defined to produce NaN (for example, `asin(2)` produces `NaN`)

Can you please tell me how do you make `asin()` (for example) return a value outside of `[-90deg,90deg]`? Argument values outside `[0,1]` return `NaN` in Chrome/FF and the [WPT tests](https://github.com/web-platform-tests/wpt/blob/16c57b53a5883393fce3f7e6843a8d51e195d7e2/css/css-values/acos-asin-atan-atan2-serialize.html).

**Comment by tabatkins** [comment]
The "argument ranges" subsection under the trig functions describes exactly when the function returns NaN rather than an angle: <https://drafts.csswg.org/css-values/#trig-infinities>

**Comment by cdoublev** [comment]
I mean, this normalization requirement may first let a reader expect `asin(2)` to return `-90deg` for example, before reading this section and expecting `NaN`.

I am not an expert in maths; maybe *"`x` must be normalized to `[a,b]`"* does not necessarily mean clamping `x` to `a` or `b`; maybe this is not an expectation that a simple JS developer (like me) will make either. 

I honestly thought it was an oversight.

**Comment by Loirooriol** [comment]
It's not about clamping. The sine is a periodic function, e.g. for any integer `n`, `sin(πn) = 0`.
The arcsine is the inverse function, so `asin(0)` must be one of these `πn`. We have to pick one, that's why CSS chooses the interval `[-90deg, 90deg]`, where we have a single solution. That is, `sin: [-π/2,  π/2] → [-1, 1] ` is bijective.

The image of the sine is the interval `[-1, 1]`, so `asin(2)` doesn't make sense, there is no number `x` such that `sin(x) = 2`. That's why CSS says to return NaN.

**Comment by tabatkins** [comment]
The general pattern thruout the math functions section is that the main section defines the normal behavior, then the "Argument Ranges" subsection defines some special cases. If this somehow isn't clear, we can possibly work on improving the clarity, but the general pattern of "define the normal behavior, then define special cases" occurs all thruout CSS specs, and specifications in general, so I don't see why it would be surprising here in particular.

And yes, as Oriol said, the arcsin of 2 is simply undefined. There is no possible answer for it *anyway*. It definitely is not the case that it's normally outside the [-90deg, 90deg] range and can be clamped to one of the endpoint values. It's also not clamping, in any case; as Oriol says, arcsin is a multi-valued function, so we're selecting the answer that lies in a particular range (which is a standard range, and matches what JS does).
