### ISSUE TITLE
[css-view-transitions-2] Allow empty :active-view-transition() ?

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9626]
In general, if there's reasonable default behavior, we allow omitting arguments, so... should `:active-view-transition()` be equivalent to `:active-view-transition(*)`?

**Comment by ydaniv** [comment]
Basically with empty params it reads as a transition with zero types, unlike `*` which reads as any types. I guess there's a difference. It could be used as selecting the default transition with zero specified types, if that makes sense.

**Comment by nt1m** [comment]
I would prefer allowing `:active-view-transition` over `:active-view-transition()` (as an alias to `:active-view-transition(*)`). The former reads "There is an active view transition" whereas the latter reads as "There is an active view transition with empty arguments". So the former makes more sense as a short syntax for `:active-view-transition(*)`

**Comment by astearns** [comment]
We resolved in https://github.com/w3c/csswg-drafts/issues/9972#issuecomment-1994889933 to have two versions, one which omits arguments and one that must take a type argument
