### ISSUE TITLE
Text-Stroke? 

### ISSUE THREAD

**Issue by jensimmons** [w3c/csswg-drafts#963]
Investigating things, I tripped over `text-stroke` and `text-fill`.  

Listed on Can I Use: http://caniuse.com/#feat=text-stroke
Demo: http://codepen.io/jensimmons/pen/EZWeeb?editors=1100#0

It looks like an experimental implementations of ideas that are in no CSS spec. They are described here: https://compat.spec.whatwg.org/#text-fill-and-stroking. 

Should we be adding this to a CSS spec? Is that already happening? (Where?) Has this already been discussed? (Sorry for the dup.) Are there other preferred techniques for accomplishing this (therefore making these unneeded)? 

These seem like pretty great properties.

**Comment by jensimmons** [comment]
Ah, Twitter is telling me it's somewhere in here: https://drafts.fxtf.org/paint/

**Comment by smfr** [comment]
Yes, it's happening via that draft.
