### ISSUE TITLE
[css-values-4] Nit: comparing `-0` and `+0` in `min()` and `max()`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9631]
`1 / max(-1 * 0, 1 * 0)` results to `-infinity` in Chrome/FF. Similarly, `1 / min(1 * 0, -1 * 0)` results to `infinity`. 

They do not consider `-0 < 0` to be true, like in the JS comparison, and returns the first argument. But in JS, `1 / Math.max(-1 * 0, 1 * 0)` results to `Infinity` and `1 / Math.min(1 * 0, -1 * 0)` results to `-Infinity`.

There is no related WPT test. Can you please tell me what is the expected result?

**Comment by Loirooriol** [comment]
https://drafts.csswg.org/css-values-4/#calc-ieee

> When comparing 0⁺ and 0⁻, 0⁻ is less than 0⁺. For example, `min(0⁺, 0⁻)` must produce 0⁻, `max(0⁺, 0⁻`) must produce 0⁺, and `clamp(0⁺, 0⁻, 1)` must produce 0⁺.

**Comment by cdoublev** [comment]
Ah, I missed it, sorry. Thanks Oriol.

**Comment by Loirooriol** [comment]
https://github.com/web-platform-tests/wpt/pull/43430
