### ISSUE TITLE
[css-values-4] fix definition of <length>

### ISSUE THREAD

**Issue by SofyaPovarova** [w3c/csswg-drafts#9646]
Fix definition of [“\<length\>”](https://drafts.csswg.org/css-values-4/#length-value) and add definitions of units:
1. Add value definition for \<length\>
`<length> = <number><length-unit> | '0'`
2. Define \<length-unit\> value
`<length-unit> = <relative-length-units> | <absolute-length-units>`
3. Define \<relative-length-units\> and \<absolute-length-units\>:
`<relative-length-units> = <font-relative-length-units> | <viewport-percentage-length-units>`
`<font-relative-length-units>`
`<viewport-percentage-length-units>`
`<absolute-length-units>`
4. Refer unit values to the corresponding definitions
Fix dfn-for attribute from "\<length\>" to "\<font-relative-length-units\>" [here](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-values-4/Overview.bs#L1837)
Fix dfn-for attribute from "\<length\>" to "\<viewport-percentage-length-units\>" [here](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-values-4/Overview.bs#L2237C47-L2237C47)
 Add dfn-type and dfn-for attributes to [the absolute table values](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-values-4/Overview.bs#L2371C2-L2371C2)  
 
Motivation: It'll formalize the definition of \<length\> and will allow us to get data that better reflects the specification from the [Webref](https://github.com/w3c/webref). I've also created [the similar issue](https://github.com/w3c/csswg-drafts/issues/9647) for units from [Other Quantities section](https://drafts.csswg.org/css-values-4/#other-units).
 If you'll find these ideas worthy, I'll be happy to submit a pull request.

**Comment by cdoublev** [comment]
Actually it would be `<length> = <dimension-token> | <number-token [0,0]>`, with `<dimension-token>` restricted in prose to tokens whose `unit` property is a length unit, and excluding `<number-token [0,0]>` when the context allow `<number>` or `<integer>` (which have priority). `1px` is a single lexical unit, see [*consume a numeric token*](https://drafts.csswg.org/css-syntax-3/#consume-a-numeric-token).

However [`<dimension-unit>`](https://drafts.csswg.org/css-values-5/#typedef-dimension-unit) could be defined with `<length-unit> | <angle-unit> | ...`.

**Comment by tabatkins** [comment]
As discussed in #9647, this is not a possible way to define lengths, due to the way CSS parses; dimensions are parsed as a single token.

We can discuss the more general issue you're actually to solve in #9648.
