### ISSUE TITLE
[css-values-4] add definitions of units and value to <angle>, <time>, <frequency>, and <resolution>

### ISSUE THREAD

**Issue by SofyaPovarova** [w3c/csswg-drafts#9647]
I suggest adding definitions of units and fixing corresponding value definitions in [Other Quantities section](https://drafts.csswg.org/css-values-4/#other-units).

Example for [\<angle\>](https://drafts.csswg.org/css-values-4/#angles):
1. Add \<angle-unit\> value
2. Fix "dfn-for" attribute from "\<angle\>" to "\<angle-unit\>" for [values list](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-values-4/Overview.bs#L2545C46-L2545C46)
```
<angle> = <number><angle-unit>
<angle-unit>
```
The same can be done for \<time\>, \<frequency\>, and \<resolution\>

**Comment by Loirooriol** [comment]
As @cdoublev mentioned in https://github.com/w3c/csswg-drafts/issues/9646#issuecomment-1829785141, `<angle>` is a single token, so it can't be defined as `<number><angle-unit>`.

**Comment by tabatkins** [comment]
Right, we can't actually do this as it doesn't match with how CSS grammar is structured.

More importantly, tho, what's the motivation behind your request? Are you trying to work around something in some tooling?
