### ISSUE TITLE
[css-color-4] add dfn attributes to deprecated colors list

### ISSUE THREAD

**Issue by SofyaPovarova** [w3c/csswg-drafts#9649]
Can we add `dfn-type="value"` and `dfn-for="<deprecated-color>"` to [the deprecated colors list](https://github.com/w3c/csswg-drafts/blob/7b47e34149ad548e03b81fc2b86420d176e48789/css-color-4/Overview.bs#L6515)?

**Comment by svgeesus** [comment]
Thanks, done!
