### ISSUE TITLE
[css-values] Let B default to 1 in `round(<strategy>?, A, B)`

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#9668]
I get the reasoning for requiring a precision in most cases. However, as I mentioned in https://github.com/w3c/csswg-drafts/issues/2513#issuecomment-565426050, it seems fine to omit it for numbers.

So if B becomes optional, defaulting to 1, it will be possible to do things like
```css
round(2.3) /* 2 */
round(up, 2.3) /* 3 */
```
while `round(2.3em)` will continue being invalid due to the type mismatch between A and B.

**Comment by SebastianZ** [comment]
> while `round(2.3em)` will continue being invalid due to the type mismatch between A and B.

Does it have to be invalid? Isn't it possible to just assume the same type for B in that case? I.e. `round(2.3em)` would be equivalent to `round(2.3em, 1em)`.

Sebastian

**Comment by Loirooriol** [comment]
No, that would be bad. Let's say `1em = 16px`, then `round(2.3em)` should produce the same as `round(36.8px)`. But `round(2.3em, 1em)` is `32px`, while `round(36.8px)` is `37px`. Making it unit-dependent is also not clear for `round(2.3em + 2.3px)`.

It could work by saying that step defaults to one canonical unit, but in `round(2.3em)` authors may get surprised it`s 1px instead of 1em, so better require it.

**Comment by Loirooriol** [comment]
It just seems strange to require the `1` when working with plain numbers, since it's the obvious choice. Like, in English people just say "round x", not "round x to a multiple of 1".

**Comment by SebastianZ** [comment]
> Let's say `1em = 16px`, then `round(2.3em)` should produce the same as `round(36.8px)`.

Converting the unit _before_ rounding is totally unexpected from an author's standpoint.

> we can't have the unit depend on the input (for the reasons given, plus things like round(1em + 10px) that don't have a single unit), and we don't want to default a mystery unit that might violate author expectations.

The point was for rounding when only having a single unit. So, `round(1em + 10px)` would still be invalid. Only `round(2.3em)`, `round(42.8deg)`, or `round(87.39%)` would be valid (being equivalent to `round(2.3em, 1em)`, `round(42.8deg, 1deg)`, and `round(87.39%, 1%)`, respectively).

Allowing to omit B for numbers but not dimensions or percentages may cause confusion.

> Like, in English people just say "round x", not "round x to a multiple of 1".

Not just spoken languages but also also in many programming languages you can omit the precision - or even don't have a way to define one like in JavaScript.

Sebastian

**Comment by jfkthame** [comment]
> The point was for rounding when only having a single unit. So, `round(1em + 10px)` would still be invalid.

Would `round(3.14159em + 2.71828em)` be valid, then? The unit is consistent/clear, but it seems like this could still be tricky/confusing. It looks "obvious" what to do when the units are right there, but what about when you have `round(--var(foo) + --var(bar))`, where `foo` and `bar` are both lengths? Whether the `round` works (and what it means) then depends on how they were defined in this particular context. I think that's getting too obscure and footgun-ish to be useful.

Making the precision default to `1` (as a number) only, in contrast, is clear and simple, while rounding anything other than a number requires being explicit about the unit of rounding.

**Comment by tabatkins** [comment]
> So, round(1em + 10px) would still be invalid. Only round(2.3em), round(42.8deg), or round(87.39%) would be valid (being equivalent to round(2.3em, 1em), round(42.8deg, 1deg), and round(87.39%, 1%), respectively).

That's pretty fragile, and it means that `round(var(--foo))` may or may not be valid, and might round to an unpredictable precision, based on how the value is written somewhere else.

And `round(10em / 3)`? Either that's invalid *too* (and the entire feature starts getting *super* fragile), or we have to rewrite the simplification rules to maintain units as-is when possible.

In-flight edit: lol, @jfkthame makes the exact same points.

---------

Anyway, if impls want to change the defaulting rules to allow a default of `1` for B, I'm fine with that. Agenda+ to discuss it.

**Comment by tabatkins** [comment]
I strongly disagree that rounding to "whole pixels" is the most common case for rounding lengths. I think that's actually an extremely rare case; subpixel lengths are usually just fine to work with. Similarly, rounding to the nearest degree doesn't seem particularly useful for most cases. The canonical unit is quite arbitrary, and generally speaking I don't think people will commonly be rounding to 1 of *any* unit; the rounding precision depends intimately on what one is actually trying to accomplish.

>  the number of decimal places. 

That's just a less powerful version of the current argument, where you're limited to precisions that are a power of 10 of some unit. It also has all the existing problems of a default rounding precision.

> keywords

These either continue to have the existing problems of a default rounding precision, or are equivalent to just providing a trivial value.

**Comment by Loirooriol** [comment]
> Though we could also define that the unit of the first operand is used

This would violate commutativity. And in fact serialization sorts summation operands alphabetically by their units, so this wouldn't roundtrip. And anyways it's seems very unintuitive to me.

**Comment by Crissov** [comment]
It just occurred to me that with keywords in the second parameter, `round()` _could_ also be a place to implement truly physical length measurements. #5986 #614

Either `round(100mm, physical)` or `round(100mm, millimeter)` would give the best approximation of 1 dm the browser can do with the active output device. 

However, authors would probably want arbitrary precision there, which would be crude to support with keywords and always remain incomplete. Treat this as a devil’s advocate proposal then.

**Comment by SebastianZ** [comment]
> It just occurred to me that with keywords in the second parameter, `round()` _could_ also be a place to implement truly physical length measurements. #5986 #614

That's out of the scope of this issue, which is to make B optional in certain cases.
So @Crissov, you might open a new issue to discuss your proposal. Though given https://wiki.csswg.org/faq#real-physical-lengths, before discussing any syntax proposals, you'd first have provide a solution for how to actually address physical sizes.

Sebastian

**Comment by Crissov** [comment]
That is exactly why I did not open another issue. My idea was that if we were to add keywords to the last argument in order to have one of them as an omitable default, we could shoehorn this in as well. 

By the way, I reread the original issue, where much of this had already been discussed, and I rediscovered #4440 which I totally had forgotten about. It is related but also quite different.

**Comment by LeaVerou** [comment]
Strong +1 to defaulting B to 1. It makes sense to require the unit for anything with a unit, and there is no precedent for that in other languages. However, writing `round(8.5, 1)` is *incredibly weird*.

(while we're at it, why are we using commas here? It doesn't match the "we use commas only for repetition" pattern. How about `round(A [ by B ]?)`?)

**Comment by tabatkins** [comment]
We use commas *mostly* for repetition, and *sometimes* for more general argument separation when the grammars would be ambiguous or at least unclear for authors to be adjacent. That latter reason is what applies here (and for all the math functions) - the arguments aren't numbers, they're calculations, and the bounds of a calculation aren't super clear visually on their own.

**Comment by bramus** [comment]
This got cut off from the meeting notes, as the switch to the next topic happened a bit too soon, but we resolved on the PROPOSAL as listed in the meeting notes:

> RESOLVED: Allow the modulus parameter to be optional in the case of rounding numbers and default to 1.
