### ISSUE TITLE
[css-view-transitions-1] Where are the "named elements" map cleaned up?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9669]
I noticed while reading the spec that the "named elements" map is never cleaned up, so it might become stale with elements that no longer have a `view-transition-name`. But it's also possible that I missed something here.

@khushalsagar @noamr @vmpstr @fantasai @tabatkins

**Comment by nt1m** [comment]
Similarly I don't see where the pseudo element tree is being torn down in the algorithms.

**Comment by nt1m** [comment]
Nevermind for the pseudo element tree. "show view transition tree" covers it.

**Comment by noamr** [comment]
What would be the observable effect of specifying this? the map gets populated twice and is no longer in use after setting the pseudo elements style, but I don't know what it would mean that it holds stale elements after this. 

If you change view transition names after capturing the new state it's too late for this view transition as everything is already captured.

**Comment by nt1m** [comment]
@noamr The named elements map is used as input to build the pseudo element tree, so it's rather important that cleanup is specified. Otherwise, implementing as it is means that the pseudo element tree will be built with non-existent groups if you do the following steps:
* start a view transition with A & B having view-transition-names
* wait for it to end
* set `view-transition-name: none` on B
* start another view-transition

-> B gets constructed along with A (even though B has `view-transition-name: none`)

**Comment by noamr** [comment]
> @noamr The named elements map is used as input to build the pseudo element tree, so it's rather important that cleanup is specified. Otherwise, implementing as it is means that the pseudo element tree will be built with non-existent groups if you do the following steps:
> 
> * start a view transition with A & B having view-transition-names
> 
> * wait for it to end
> 
> * set `view-transition-name: none` on B
> 
> * start another view-transition
> 
> 
> 
> -> B gets constructed along with A (even though B has `view-transition-name: none`)

Oh I see. The named element map is associated with a particular ViewTransition object, so starting a new one would ignore any existing one from a previous transition.

**Comment by nt1m** [comment]
Ah right, that makes sense thanks!

**Comment by nt1m** [comment]
I wonder if it makes sense to add a note if this is implicit.

**Comment by noamr** [comment]
> I wonder if it makes sense to add a note if this is implicit.

It's explicit though:

https://www.w3.org/TR/css-view-transitions-1/#viewtransition-named-elements

"A {{ViewTransition}} has the following:"

**Comment by khushalsagar** [comment]
Sounds reasonable @nt1m. Feel free to send a PR or let me know if you'd like me to do that. :)

**Comment by nt1m** [comment]
I sent a PR: #9769
