### ISSUE TITLE
[css-view-transitions-1] Clarify what "return failure" means

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9670]
There are 3 occurrences of "return failure" in the spec. Can we clarify what they mean? Do they throw a JS exception, a console message or just an early return?

**Comment by nt1m** [comment]
cc @khushalsagar @noamr @vmpstr @fantasai @tabatkins

**Comment by noamr** [comment]
We have "If failure is returned" in other algorithms which take this into account.

**Comment by nt1m** [comment]
Ah I missed that, thanks!
