### ISSUE TITLE
[css-view-transitions-1] Is "named elements" map in the right order after "capture new state" algorithm?

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9672]
In "capture new state", there is this step:

> If namedElements[transitionName] does not [exist](https://infra.spec.whatwg.org/#map-exists), then set namedElements[transitionName] to a new [captured element](https://drafts.csswg.org/css-view-transitions/#captured-element) struct.

However, it doesn't mention where to insert the element, which means by default we would be adding it at the end of the ordered map. It is the more convenient default to implement, but is this correct? You might expect to want to preserve the paint order or such (slightly more of a pain to do, but possible)

cc @noamr @khushalsagar @fantasai @tabatkins @vmpstr

**Comment by noamr** [comment]
> In "capture new state", there is this step:
> 
> > If namedElements[transitionName] does not [exist](https://infra.spec.whatwg.org/#map-exists), then set namedElements[transitionName] to a new [captured element](https://drafts.csswg.org/css-view-transitions/#captured-element) struct.
> 
> However, it doesn't mention where to insert the element, which means by default we would be adding it at the end of the ordered map. It is the more convenient default to implement, but is this correct? You might expect to want to preserve the paint order or such (slightly more of a pain to do, but possible)
> 
> cc @noamr @khushalsagar @fantasai @tabatkins @vmpstr

The spec says [here](https://drafts.csswg.org/css-view-transitions-1/#capture-the-old-state) that the iteration on elements should be according to paint order.

**Comment by nt1m** [comment]
> The spec says [here](https://drafts.csswg.org/css-view-transitions-1/#capture-the-old-state) that the iteration on elements should be according to paint order.

That doesn't really answer my question. I'm talking about step 4.6 of "capture new state":

> [For each](https://infra.spec.whatwg.org/#list-iterate) element of every [element](https://drafts.csswg.org/css2/#element) that is [connected](https://dom.spec.whatwg.org/#connected), and has a [node document](https://dom.spec.whatwg.org/#concept-node-document) equal to to document, in [paint order](https://drafts.csswg.org/css2/#painting-order):
> [...]
> * If namedElements[transitionName] does not [exist](https://infra.spec.whatwg.org/#map-exists), then set namedElements[transitionName] to a new [captured element](https://drafts.csswg.org/css-view-transitions-1/#captured-element) struct.

If `namedElements[transitionName]` does not exist, then where in the map do we set this new struct? By default it will be at the end of the map, and it doesn't matter in which order you iterate. 

I'm aware that case is a super edge case, because most of the map will be populated by "capture old state", in the right order, but where the step 4.6. of "capture new state" appends in the map makes a difference.

**Comment by noamr** [comment]
> > The spec says [here](https://drafts.csswg.org/css-view-transitions-1/#capture-the-old-state) that the iteration on elements should be according to paint order.
> 
> That doesn't really answer my question. I'm talking about step 4.6 of "capture new state":
> 

Oops, missed this, sorry.

> I'm aware that case is a super edge case, because most of the map will be populated by "capture old state", in the right order, but where the step 4.6. of "capture new state" appends in the map makes a difference visually.

Yea, this would be an entry animation, which might be more than an edge case.
@vmpstr did we have prior discussions about this?
Also re. what happens when the paint order changes between old & new?

**Comment by vmpstr** [comment]
Yeah, there's a [non-normative note](https://drafts.csswg.org/css-view-transitions-1/#capture-the-old-state:~:text=We%20iterate%20in%20paint%20order) that says that we're ensuring the named elements map has the same order as the paint order. This implies that the new elements that don't exist in the old state are painted as if they had higher paint order (ie paint on top). This is intentional.

I can't find the issue where we discussed this, so it may have been discussed in the PR as part of the initial draft, but here's a summary comment from Khushal: https://github.com/w3c/csswg-drafts/issues/8941#issuecomment-1591769395 Essentially, we have to pick _some_ order, and the one we have is as good as any, and not too complicated.

**Comment by nt1m** [comment]
I'm OK with how the current spec is written (it's actually easier to implement), but I think it would be good to add a note in "Capture new state" as well that this is an intentional choice.

**Comment by khushalsagar** [comment]
Thanks for the suggestion @nt1m. Here's the PR: https://github.com/w3c/csswg-drafts/pull/9768
