### ISSUE TITLE
[css-unit-au] Support for "au" CSS sizing unit

### ISSUE THREAD

**Issue by boutell** [w3c/csswg-drafts#9678]
See:

https://www.w3.org/TR/css-values-3/#absolute-lengths

While excellent for screen and print use, these units are impractical for measurements on an astronomical scale, e.g.:

https://xkcd.com/2863

This would be a new "absolute length" unit, named `au`, per section 5.2 of the spec.

For purposes of the equivalence table, `au` can be listed as 1.496e+13 cm.

**Comment by Loirooriol** [comment]
Concern: "au" means "astronomical unit", but there is potential confusion with "app units" https://docs.rs/app_units/latest/app_units/

Also, one astronomical unit is not that big, so would it be better to add `kpc` (kiloparsec) instead? See https://github.com/w3c/csswg-drafts/issues/2491#issuecomment-377801961

**Comment by boutell** [comment]
Hmm. Good points. Also "au" incorporates "unit," but "unit" is implied in this context. Perhaps just "a" for Astronomical (unit)?

**Comment by tabatkins** [comment]
[checks calendar] hey, it's not April yet

**Comment by md8n** [comment]
`au` can also be confused with:
* Gold - so are we talking about mass here, so is this really about some kind of font weight? or
* Australia - which is also very large (but not as big as 1 Astronomical Unit), and mostly empty
