### ISSUE TITLE
[css-fonts-4] Should the `math` generic font family be renamed `generic(math)`

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#9684]
We have a [`math`](https://drafts.csswg.org/css-fonts-4/Overview.html#math-def) generic font family.

We now also have a `generic()` wrapper function, as used in [`generic(fangsong)`](https://drafts.csswg.org/css-fonts-4/#generic(fangsong)-def) and [`generic(kai)`](https://drafts.csswg.org/css-fonts-4/#generic(kai)-def) and [`generic(nastaliq)`](https://drafts.csswg.org/css-fonts-4/#generic(nastaliq)-def).

Given that `math` generic is still fairly new and not (afaik) implemented, should it be renamed `generic(math)`?

**Comment by SebastianZ** [comment]
> Given that `math` generic is still fairly new and not (afaik) implemented

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#browser_compatibility), Chromium has this since version 109, so when considering to switch to `generic(math)`, we need to check whether it is web-compatible.

Sebastian
