### ISSUE TITLE
[css-values] Add slash as multiplier

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9691]
There are a few places in the specs that define repetitions of one or more values separated by slashes. The most prominent of them being the [placement shorthands in CSS Grid](https://drafts.csswg.org/css-grid-2/#placement-shorthands).

As such repetitions are becoming more common, it might make sense to add a multiplier for it. So syntax definitions become more concise and a little easier to read.

With that, `<grid-line> [ / <grid-line> ]{0,3}` could become `<grid-line>/{1,4}`.

If the multiplier character should actually be a slash as well or another character can be bikeshedded.

(I _think_ this was brought up earlier by someone else, maybe @fantasai, in a PR discussion but I can't remember.)

Sebastan

**Comment by fantasai** [comment]
I'm not sure this is worth doing, because it's not particularly common and adding rarely-used multipliers makes it harder for people reading our syntax, since it's unavoidably unfamiliar.

**Comment by tabatkins** [comment]
Yeah, slashes are already very rarely used, and in general we don't *want* to make it easier to use - they should be reserved only for when we absolutely can't express a reasonable, unambiguous grammar otherwise.

So agreed, close no change.
