### ISSUE TITLE
[css-values] Non-zero mod()

### ISSUE THREAD

**Issue by Crissov** [w3c/csswg-drafts#9693]
Although I originally proposed the `mod()`/`round()` functions, I have not used them much in CSS yet. (They also have not shipped in Chrome and Edge yet.) I recently had to use modulo functions in other languages a lot, though. I realized I often needed the result to be between 1 and _x_ and not between 0 and _x_&minus;1. You can get that by substracting and adding back an offset, but it looks clumsy. 

I am now wondering whether CSS authors would also frequently prefer to get non-zero results from `mod()` and also `rem()`. 
If they do in fact, it would be nice to get this behavior by adding a keyword parameter. 

(I considered to re-question why the behavior of `rem()` is not achieved in the same way, but that is probably a separate issue and now too late to change anyway.)

**Comment by tabatkins** [comment]
I don't think I've ever personally run into this sort of situation. But more importantly, if you *do* need this sort of thing, there's no way for us to infer what your minimum step is, such that the value range can be shifted over by it.

For now, just writing it out (`calc(mod(val - step, max) + step)`) seems sufficient to address this case. If it can be shown there's substantial authoring usage of this sort of pattern, we can reconsider it.
