### ISSUE TITLE
[css-scroll-snap-2] Use present tense for snap event names

### ISSUE THREAD

**Issue by DavMila** [w3c/csswg-drafts#9697]
It was pointed out [here](https://github.com/w3c/csswg-drafts/issues/7442#issuecomment-1214626815) that "snapchanged" (introduced in the scroll-snap-2 [spec](https://drafts.csswg.org/css-scroll-snap-2/#snap-events)) doesn't follow the convention of using present tense to name JavaScript events.

Additionally, [zcorpan](https://github.com/zcorpan) [suggests](https://github.com/w3c/csswg-drafts/issues/7442#issuecomment-1824901288) using names that put the snap events closer, alphabetically, to the `scroll` and `scrollend` events.

To riff off on that suggestion, I propose:
- `scrollsnapchanging` instead of snapchanging, and
- `scrollsnapchange` instead of snapchanged

which reflect not just that snapping is happening but that there is a change in snap targets as is the intention of the events.

**Comment by emilio** [comment]
Fixed by https://github.com/w3c/csswg-drafts/pull/10288
