### ISSUE TITLE
Spec overview at drafts.csswg.org is out of date

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9698]
While the specifications themselves seem to be generated correctly, e.g. https://drafts.csswg.org/css-2024/, the list of specs at https://drafts.csswg.org/ is months behind.

The last changes there are from 2023-07-19, if that's of any help debugging the issue.

Sebastian

**Comment by Loirooriol** [comment]
@plinss

**Comment by Loirooriol** [comment]
BTW, I see a 2023-07-21 09:56:11 PDT.

**Comment by svgeesus** [comment]
I noticed something similar recently. I wanted to see how some recent edits to CSS color 4 looked, and was astonished to see that they were not there, and the draft was dated July!

Compare

 - https://drafts.csswg.org/css-color-4/Overview.html
   21 July 2023

- https://drafts.csswg.org/css-color-4/
  28 November 2023

I suspect that the bikeshed file and the (built on GitHub, then mirrored) index.html are being mirrored correctly and the Overview.html is no longer being generated but whatever was on there from before did not get deleted and is still being served.

@plinss

**Comment by Loirooriol** [comment]
@svgeesus The `Overview.html` being outdated is #8899. But the date matches https://drafts.csswg.org/, so I guess the list is just showing the date from `Overview.html` instead of `index.html`

**Comment by plinss** [comment]
It looks like the webhook from GitHub notifying about pushes has been failing, so the draft server's version has been out of date. Should be fixed now.

**Comment by SebastianZ** [comment]
Yep, works again. Thank you, @plinss!

Sebastian
