### ISSUE TITLE
[css-values] Make min and max value optional in `clamp()`

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#9713]
As we know, we added [`clamp()`](https://drafts.csswg.org/css-values/#comp-func) because doing clamping logic with `min()` and `max()` is counterintuitive.
However, this doesn't only apply when you have *both* a min and a max, it’s _still_ counterintuitive when you only have one of two. I keep finding myself using `clamp()` with dummy min or max values so that I can only use it for max or min respectively, which not only adds cognitive overhead, but also pointless computation.

A nice little improvement could be to make the min and max values optional via `none` keywords:

[Before](https://drafts.csswg.org/css-values/#calc-syntax):
```
<clamp()> = clamp( <calc-sum>#{3} )
```

After:

```
<clamp()> = clamp( [ <calc-sum> | none ] , <calc-sum> , [ <calc-sum> | none ])
```

<details>
<summary>
Alternative syntax: Using empty tokens for the omitted argument
</summary>

```
<clamp()> = clamp( <calc-sum>? , <calc-sum> , <calc-sum>? )
```

Note that this is different from `clamp( <calc-sum>#{2, 3} )`: we still need empty tokens for the missing arguments, otherwise we wouldn't be able to disambiguate. I.e. `clamp(3rem, 10vh)` would not be valid, it would need to be either `clamp(3rem, 10vh, )` or `clamp( , 3rem, 10vh)`.
If we go that route we'd also need to add an exception to require the comma with empty arguments, per normal grammar specification rules the comma would be omitted, making disambiguation impossible.

When I first posted this I thought going the empty token route would be ideal, as `none` seemed too verbose, but I now think the clarity hit is not worth it, especially if we take the editorial challenges into account.

</details>

Hopefully this is such a small change we may be able to wedge it in css-values-4.

Edit: Agenda+ after discussing it with @fantasai and @tabatkins — this seems like such an easy win and pretty uncontroversial so we could move forwards with hopefully very little call time.

**Comment by tabatkins** [comment]
Yup, this makes a lot of sense. The confusion argument for introducing clamp() in the first place still applies when you're only clamping from one side, so making that easy seems like an obvious win.

(I'm pretty strongly opposed to the alternative "just omit the argument, but keep the comma in" syntax, as that violates our comma-elision rules, and those exist for a good reason. But the `none` syntax is great.)

**Comment by ByteEater-pl** [comment]
Why not just use `max` or `min` when you want to clamp from one side? What are the use cases for adding syntax to let `clamp` double as them? Code generation, perhaps?

**Comment by Loirooriol** [comment]
@ByteEater-pl The idea is that `min()` and `max()` can be confusing, e.g. someone wants a calculation like `var(--a) * var(--b) + var(--c)` but enforcing a minimum of 0px. If they are thinking in terms of adding a minimum threshold they might be tempted to use `min()`, but actually they need `max()`.

But I'm not sure if this proposal will really help much, people who misunderstands what `min()` does will probably use it anyway, and people aware of this "gotcha" can just use `max()` indeed.

**Comment by LeaVerou** [comment]
> @ByteEater-pl The idea is that `min()` and `max()` can be confusing, e.g. someone wants a calculation like `var(--a) * var(--b) + var(--c)` but enforcing a minimum of 0px. If they are thinking in terms of adding a minimum threshold they might be tempted to use `min()`, but actually they need `max()`.
> 
> But I'm not sure if this proposal will really help much, people who misunderstands what `min()` does will probably use it anyway, and people aware of this "gotcha" can just use `max()` indeed.

Not necessarily. They might remember there is some weirdness around this, and this frees them from having to do the mental gymnastics. Or they may just reach for `clamp()` without considering `min()` or `max()` because they have internalized that that's what you use to introduce upper and lower bounds, and you use `min()` and `max()` when you need the minimum or maximum number among many. These are distinct use cases, and I'd argue using `min()` or `max()` for the former is actually a workaround, not a primary use case for `min()` and `max()`.

**Comment by ByteEater-pl** [comment]
I'd bet most uses of `max` and `min` are with two arguments, so it does seem primary.

**Comment by tabatkins** [comment]
The fact is still that max()/min() can be confusing to use, depending on what you're going for. If your intention is "use the largest of these two values", then max() is exactly what you need and completely intuitive. If your intuition is "use this value, but clamp it to a maximum of this second value", then the fact that you have to use *min()* for that is easy to get confused about. People *regularly* write that using max(), in my experience, and then are confused why that doesn't work.

So for the "use this value, but clamped above/below by this second value", using clamp() with only one bound makes a lot more sense.
