### ISSUE TITLE
[css-cascade] Clarification on cascade order for font shorthand property

### ISSUE THREAD

**Issue by brad-mccormick** [w3c/csswg-drafts#9744]
I'm looking for clarification on expected behavior when attempting to redefine a CSS custom property defined as a sub property of a font shorthand property. I'm not sure if this would be related to css-cascade or css-font.

In the following example we have defined some custom properties at the :root scope that ultimately are used to construct a typography custom property --font-body-medium-1. That property is then set at the inner class and applied to the div. The font size is also overriden in .inner, however no properties of --font-body-medium-1 can be overriden in this method. I expected that --font-body-medium-1 would be expanded in place in the font property, exposing those sub properties for override via cascade. It seems they are taken out of the cascade or are out of order. What is the expected behavior in this case? This feels like a bug.

```
:root {
  --font-weight-500: 500;
  --font-size-350: 14px;
  --font-line-height-500: 20px;
  --font-family-sans: 'Roboto Flex', Roboto, Helvetica, Arial, sans-serif;
  --font-family-primary: var(--font-family-sans) ;
  --font-body-medium-1: var(--font-weight-500) var(--font-size-350)/var(--font-line-height-500) var(--font-family-primary);
}

.inner {
  --font-size-350: 24px;
  font: var(--font-body-medium-1);
}
```

```
<div class="outer">
  <div class="inner">Some text...</div>
</div>
```

**Comment by cdoublev** [comment]
This is expected: `--font-body-medium-1` is computed in `:root` with its specified value for `--font-size-350`, not with the specified value in `.inner`.

Maybe [this blog post](https://moderncss.dev/how-custom-property-values-are-computed/#inheritable-values-become-immutable) may help you if this is not clear.

```css
:root {
  --color: red;
  --color-root: var(--color);
}
div {
  --color: green;
  color: var(--color-root); /* red */
  background-color: var(--color); /* green */
}
```

**Comment by Loirooriol** [comment]
Seems you want #2749
