### ISSUE TITLE
[css-values-5] Add `resolution` to `<attr-type>`

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#9752]
[`<attr-type>`](https://drafts.csswg.org/css-values-5/#typedef-attr-type) defines different kinds of dimension keywords, though it is currently missing `resolution` for [resolutions](https://drafts.csswg.org/css-values-4/#resolution).

Related to that, `<resolution>` should also be added to the definition of [`<dimension-unit>`](https://drafts.csswg.org/css-values-5/#typedef-dimension-unit). Alternatively, instead of listing all the dimensions, it could just refer to [the definition of `<dimension>`](https://drafts.csswg.org/css-values-4/#typedef-dimension), so there is only one place of truth.

Sebastian

**Comment by tabatkins** [comment]
Now that attr() is defined with `<syntax>`, and `<resolution>` is a valid syntax value, this is handled.
