### ISSUE TITLE
[css-color-5] relative color syntax: numbers vs. percentages in `calc()`

### ISSUE THREAD

**Issue by danburzo** [w3c/csswg-drafts#9759]
With two implementations on stable channels (Safari 16.4+, Chrome 119+) for the relative color syntax, I’m trying to make sense of the incompatible results I’m seeing [on my test page](https://danburzo.ro/demos/color/relative-color-syntax.html), in order to contribute appropriate web platform tests:

1. The only version that works in Safari is `rgb(from #ff6600 calc(100% - r) calc(100% - g) calc(100% - b))` (based, if I remember correctly, on a previous version of the spec?). Should the mixing of `<percentage>` and `<number>` in `calc()` here still produce a valid color? 
2. Am I right to understand that the `<number>` for `rgb()` channel keywords is in the range `[0,255]` and not `[0,1]` and that Chrome supporting `rgb(from #ff6600 calc(1 - r) calc(1 - g) calc(1 - b))` rather than `rgb(from #ff6600 calc(255 - r) calc(255 - g) calc(255 - b))` is incorrect?

**Comment by svgeesus** [comment]
_Commenting in haste; I am on vacation and with an unreliable internet connection._

The relevant parts of the spec are [this](https://drafts.csswg.org/css-color-5/#relative-colors):

> The [channel keywords](https://drafts.csswg.org/css-color-5/#channel-keyword) return a [<number>](https://drafts.csswg.org/css-values-4/#number-value); if they were originally specified as a [<percentage>](https://drafts.csswg.org/css-values-4/#percentage-value) or an [<angle>](https://drafts.csswg.org/css-values-4/#angle-value), that <percentage> is resolved to a <number> and the <angle> is resolved to a <number> of degrees (which is the [canonical unit](https://drafts.csswg.org/css-values-4/#canonical-unit)) in the range [0, 360].

and also 

> Beware when using components outside their normal position; when percentages are resolved to numbers, there is no "magic scaling" to account for the changed position if those numbers are used in a different place.

followed by [this example](https://drafts.csswg.org/css-color-5/#ex-no-percentage-magic)

> For example,

> `color: color(from color(srgb 0 0 0 / 60%) srgb alpha 0.6 0.6 / 0.9);`

> The alpha component is resolved as a [`<number>`](https://drafts.csswg.org/css-values-4/#number-value), giving 0.6; thus the resulting color is `color(srgb 0.6 0.6 0.6 / 0.9)`.

> However, in this second example, again the alpha resolves to 0.6, giving a very different color due to the color component range of 0 to 255 in `rgb()` syntax:

> `color: rgb(from rgb(0 0 0 / 60%) alpha 153 153 / 0.9);`

> which results in `rgb(0.6 153 153 / 0.9)` and not `rgb(153 153 153 / 0.9)`.

The mixing of number and percentage is from an earlier, and incorrect, version of the spec where channel keywords could resolve to either number or percentage as desired. Now the spec is corrected to say that they all resolve to number.

The magical scaling of numbers by 255 was never in the specification; Chrome was incorrect to add it to their implementation.

_I don't have time right now to dig up the issues where this was decided, sorry. Will come back to this once I am back at work._

Adding more WPT would be wonderful. Feel free to ping me for a review.

**Comment by svgeesus** [comment]
It was [this CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/7876#issuecomment-1379264467):

> The CSS Working Group just discussed channel keywords, and agreed to the following:

>    RESOLVED: keywords with multiple specified types result in number

 - https://github.com/w3c/csswg-drafts/issues/7876

**Comment by svgeesus** [comment]
Also

 - https://github.com/w3c/csswg-drafts/issues/8499

**Comment by danburzo** [comment]
Thanks @svgeesus for the references, and sorry for the distraction during your vacation! :-)

**Comment by romainmenke** [comment]
@chrisdavidmills Thank you for linking this here.
I've made a couple of notes.

**Comment by svgeesus** [comment]
@chrisdavidmills it may be worth pointing out in the MDN article that, for all the browser differences you mention, Chromium is correctly following the current specification (and the CSS WG resolutions that produced it) while Safari implemented earlier and implements an older version of the specification.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills it may be worth pointing out in the MDN article that, for all the browser differences you mention, Chromium is correctly following the current specification (and the CSS WG resolutions that produced it) while Safari implemented earlier and implements an older version of the specification.

@svgeesus (also, @romainmenke's feedback on the PR is relevant here) yup, good call. Now that I understand the situation better, I'll document the standard in the MDN docs and point out the Safari differences in the browser compat data.

**Comment by romainmenke** [comment]
I've added a few tests that cover this issue : https://github.com/web-platform-tests/wpt/pull/43931

**Comment by danburzo** [comment]
@romainmenke please note the ranges implemented by Chrome for the RGB components are wrong, numbers should be in the [0-255] range.

**Comment by romainmenke** [comment]
<img width="1443" alt="Screenshot 2024-01-10 at 23 48 05" src="https://github.com/w3c/csswg-drafts/assets/11521496/e22e2b1e-a7fe-4313-b2b2-4611286759af">

Yup, that is also why Chrome fails some of these new tests :)

> Colors do not match. Actual: color(srgb 1.39216 1.43137 1.47059 / 0.81) Expected: color(srgb 0.396 0.435 0.474 / 0.81). Error: assert_array_approx_equals: Numeric parameters are approximately equal. property 0, expected 0.396 +/- 0.01, expected 0.396 but got 1.39216

**Comment by danburzo** [comment]
Ah right, late-night arithmetics malfunction, I misread the intent of the tests, please disregard!

**Comment by mysteryDate** [comment]
> The magical scaling of numbers by 255 was never in the specification; Chrome was incorrect to add it to their implementation.

Oops! My fault. I was mislead by some WPTs, which appear to be incorrect, no?

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html#L79C89-L80C101

I'll get to fixing that asap.

**Comment by svgeesus** [comment]
So, lets work out that test case. There may be some confusion in the spec because the conversion color space (`rgb()`) and the serialization format(`color(srgb)`) have differing requirements here.

`rebeccapurple` is `#663399`  or `rgb(102 51 153)`

In `rgb(from rebeccapurple ...)` [we have](https://drafts.csswg.org/css-color-5/#relative-RGB) r=102 g=51 b=153 a=1.0

In `rgb(from rebeccapurple b alpha r / g)` we have, internally, r=b=153, g=alpha=1.0, b=r=102, a=g=51 so `rgb(153 1.0 102 / 51)`. 

This is where it gets unclear, [CSS Color 4 says](https://drafts.csswg.org/css-color-4/#rgb-functions):

> Values outside these ranges are not invalid, but are clamped to the ranges defined here at parsed-value time.

So we clamp the alpha (in this test case, the only out of range component). Which means this is the same as specifying `rgb(153 1.0 102 / 1)`.

The serialized specified value [must use `color(srgb)`](https://drafts.csswg.org/css-color-5/#serial-relative-color) so it will be serialized as (to whatever precision)

"color(srgb 0.6 0.00392156863 0.4)" with the alpha not serialized as it is 1.

So yes, that subtest is wrong in the green and alpha values.

```js
fuzzy_test_computed_color(`rgb(from rebeccapurple b alpha r / g)`, `color(srgb 0.6 1 0.4 / 0.2)`);
```

But the worrying and unclear thing, to me, is that the whole reason we added the serialization of RCS `rgb()`, `hsl()` and `hwb()` to `color(srgb)` specifically to enable round-tripping of out of gamut values. But the text from CSS Color 4 that I quoted above prevents that, which means that CSS Color 5 needs to specifically say that _RCS versions of those color functions do **not** clamp out of range values._ And then, do we really want unclamped alpha values like that?

**Comment by cdoublev** [comment]
> The serialized specified value [must use `color(srgb)`](https://drafts.csswg.org/css-color-5/#serial-relative-color)

Did you mean the serialized computed value? This is not what I understand from the current text and the example (quoted below), and I would not expect a relative color to be normalized as `color()` at parse time, which would get rid of what the author originally specified.

  > **Example 43**
  >
  > For example, the result of serializing the specified value `OkLcH(from peru  l    c  h)` is the string "oklch(from peru l c h)"

**Comment by romainmenke** [comment]
> And then, do we really want unclamped alpha values like that?

For alpha I would say that unclamped values aren't useful.

**Comment by svgeesus** [comment]
> Did you mean the serialized computed value? 

I did not. Computed values [are clear in the spec](https://drafts.csswg.org/css-color-5/#serial-relative-color). If `currentColor` is not involved, then:

> Otherwise, it is the resolved value, which is a [`<color>`](https://drafts.csswg.org/css-color-5/#typedef-color)

**Comment by svgeesus** [comment]
But yes, I see what you mean. The specified value does not calculate out the values at all, it just normalizes the channel keywords in terms of spaces and case.

So yes, I was indeed calculating computed values above (like the name of the test implies)

_/me gets more coffee_

**Comment by svgeesus** [comment]
@mysteryDate do the fixed WPT need a review or did you fix them upstream?

**Comment by svgeesus** [comment]
So from a spec perspective, it seems there is nothing further to do here.

WPT have been added or corrected.

Chrome has changed their implementation.

@danburzo @mysteryDate close?

**Comment by mysteryDate** [comment]
@mysteryDate do the fixed WPT need a review or did you fix them upstream?

Sorry! I was on vacation for the past three weeks. Tests were changed here: https://github.com/web-platform-tests/wpt/commit/77d184777b6b348771061a5f61500b6088441588

Fine to close
