### ISSUE TITLE
[css-borders] CSS Borders 4 tries to load images that don't exist (they are in Backgrounds 4) 

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#9761]
https://drafts.csswg.org/css-borders-4/#border-color has an example with images like `<img alt="" src="images/multicolor-border.png">`

The problem is that https://drafts.csswg.org/css-borders-4/images/multicolor-border.png doesn't exist, the image is in https://drafts.csswg.org/css-backgrounds-4/images/multicolor-border.png

I guess the images should have moved in #9048

**Comment by SebastianZ** [comment]
Thanks for the hint, @Loirooriol! Fixed it.

Sebastian
