### ISSUE TITLE
[css-fonts-4] How to handle the object replacement character (U+FFFC)

### ISSUE THREAD

**Issue by vitorroriz** [w3c/csswg-drafts#9763]
At https://www.w3.org/TR/css-fonts-4/#char-handling-issues spec defines how to handle the replacement character (U+FFFD):

>  When matching the replacement character U+FFFD, user agents may skip the font matching process and immediately display some form of missing glyph symbol, they are not required to display the glyph from the font that would be selected by the font matching process.

I haven't found anything about the object replacement character (U+FFFC). It would be great if we could define the behavior for that. 

Should the user agent render it? It is up to the user agent? Should it be deleted?

**Comment by fantasai** [comment]
Absent any compat requirements to the contrary, it should be handled just like any other Symbol-category character and rendered according to the available fonts.

**Comment by svgeesus** [comment]
Right, there is nothing special about that particular character, it gets rendered by the font matching process same as any other.

**Comment by australianpokies** [comment]
Thanks for documenting this! Looking forward to updates.
[![Image](https://github.com/user-attachments/assets/3e73c1b5-4016-477e-90e3-6084e649b092)](https://robycasino.pokiesreal.money/)
