### ISSUE TITLE
[css-grid] Clarify behavior of position: fixed grid items

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#977]
Something that keeps coming up is the behavior of grid items set to `position: fixed`.

My understanding of this is that an item set to position: fixed should behave in the same way as one set to position: absolute, so that would correspond to [10.2 With a Grid Container as parent](https://drafts.csswg.org/css-grid/#static-position) which seems to be what the 2 implementations are doing. [CodePen example](http://codepen.io/rachelandrew/pen/xgraOZ?editors=1100#0)

However this is a bit confusing if you haven't made that connection. So if this is correct behavior perhaps a note could be added to clarify that this is how position fixed items will behave. It also seems as if having a fixed item be contained within it's track might be useful - but perhaps that is a different issue.

**Comment by fantasai** [comment]
The CSS2 spec clearly defines fixed positioning as a subset of absolute positioning, so I think that's clear. Calling it out here would make other cases where we don't seem ambiguous.

Wrt restricting it to a track, we only do that if the containing block is a grid container, and in the case of fixedpos, it's the ICB which is not a grid container. (I'm not sure what your use case is here, but `position: sticky` might be a better solution.)
