### ISSUE TITLE
[css-view-transitions-1] What is the snapshot containing block for iframes?

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9786]
The spec [here](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics-algorithm:~:text=However%2C%20the%20captured%20image%20should%20include%2C%20at%20the%20very%20least%2C%20the%20contents%20of%20element%20that%20intersect%20with%20the%20snapshot%20containing%20block.) says that if an element is too large for its entire image to be captured, implementations can clip the image as long as the contents in the snapshot containing block are captured.

But for definition of snapshot containing block is ambiguous for iframes: "all areas of the window that could potentially display page content". The impact it has on clipping of images aside, I think it should be the iframe's ICB. @bokand can explain this better.

But this means we need a better way to decide how to clip the image if the transition is happening in an iframe. The goal with the SCB recommendation was so we at least capture the onscreen content the user is seeing but the whole iframe could be offscreen. I'm thinking the following:

- If the iframe is completely offscreen, just skip the transition. Why animate instead of directly flipping to the new state.
- If its onscreen (fully or partially) use the SCB of the top level frame to decide what should be captured in the images.

**Comment by khushalsagar** [comment]
> Why not just do the simple thing and apply the clip in the same way we do for non-root elements? i.e. take the above definition of the snapshot containing block for an iframe and also clip the root to it.

We already clip the root to SCB, see [here](https://drafts.csswg.org/css-view-transitions-1/#capture-rendering-characteristics-algorithm:~:text=Render%20the%20region%20of%20document%20(including%20its%20canvas%20background%20and%20any%20top%20layer%20content)%20that%20intersects%20the%20snapshot%20containing%20block). This was based on the assumption that SCB is always a reasonable size. That's true for main frames but not iframes since there the SCB can be any bounds chosen by the parent frame.

**Comment by khushalsagar** [comment]
> This information might also need to cross process boundaries so could be out of date. It feels rather complex for something that seems to me like an extreme edge case?

FWIW the info has to be available to cross-process iframes because of IntersectionObserver (which needs to know whether elements in an iframe are visible to the user). But its a fair point that it can be stale. For VT the latency in updating it will be visually noticeable to the user. If this all sounds too complex we can just say that implementations can skip the transition if SCB exceeds an implementation-defined maximum.

**Comment by khushalsagar** [comment]
Actually I forgot about https://github.com/w3c/csswg-drafts/issues/9543 which talks about what to do with iframes which are offscreen. So I'll keep this issue focused on defining an iframe's SCB and how to deal with the case where its very large.

Proposed resolution

- Snapshot Containing Block for an iframe should be that frame's Initial Containing Block
- If the SCB exceeds an implementation defined maximum, the UA can skip the transition

**Comment by bokand** [comment]
> Proposed resolution
> * Snapshot Containing Block for an iframe should be that frame's Initial Containing Block
> * If the SCB exceeds an implementation defined maximum, the UA can skip the transition

This sgtm!
