### ISSUE TITLE
[css-device-adapt-1] broken link to Editor's Draft

### ISSUE THREAD

**Issue by bert-github** [w3c/csswg-drafts#9796]
The latest (29 March 2016) [CSS Device Adaptation Module Level 1](http://www.w3.org/TR/2016/WD-css-device-adapt-1-20160329/) has a link to an [Editor's Draft](https://drafts.csswg.org/css-device-adapt/) that returns 404. (The same link is present in the [previous version](http://www.w3.org/TR/2015/WD-css-device-adapt-1-20151126/) of 26 November 2015.)

I believe the target of that link disappeared in September 2022 or thereabouts.

If the editor's draft was moved to a different URL, maybe somebody can put a redirect at its old address or the WG can publish a new WD with the current URL (or both)? If the editor's draft was accidentally deleted, maybe it can be recreated? (Archive.org has a copy of [August 2022](https://web.archive.org/web/20220828012438/https://drafts.csswg.org/css-device-adapt/).)

**Comment by plinss** [comment]
Redirects added
