### ISSUE TITLE
[cssom-1][css-color-4] Move serialization of `<color>` and `<alpha-value>`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9798]
According to https://github.com/w3c/csswg-drafts/issues/7870#issuecomment-1277889963, how to serialize `<color>` should be removed from CSSOM and how to serialize `<alpha-value>` should be moved to CSS Color 4.

If I am not mistaken, the algorithm for `<alpha-value>` is required when stored internally as an 8-bit integer, which seems to be the case for most browsers (if not all), and helps explaining why `0.499` may be serialized to `0.498`, for example.

**Comment by svgeesus** [comment]
Yes, I see that there is still an [inlline issue wondering what to do about case folding](https://drafts.csswg.org/cssom-1/#issue-d69ea54c) while https://github.com/w3c/csswg-drafts/issues/7870#issuecomment-1277889963 (and subsequent discussion) says that ASCII-lowercase folding is done, as does https://drafts.csswg.org/css-color-4/#serializing-color-values which was then [adopted by CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/7870#issuecomment-1423009016). So that inline issue should be deleted.

**Comment by svgeesus** [comment]
I agree that the algorithm for serializing internal 8-bit alpha values needs to be moved over to CSS Color 4, which currently does not cover that case.

**Comment by svgeesus** [comment]
@emilio what is your preference, should I:

- update css-color-4 then hand the editing baton to you for cssom-1
- send a PR for cssom-1 once css-color-4 is updated
- make the edits in both specs?

**Comment by svgeesus** [comment]
@emilio CSS Color 4 has now been updated to add the 8-bit unsigned alpha serialization logic from cssom-1 in https://github.com/w3c/csswg-drafts/commit/a28b013f2ff408517c0eccf7aa12067ac4f0e14e

I also added a couple of worked examples.

Would you like a PR on cssom-1 to remove it from there, or should I just do it?

**Comment by svgeesus** [comment]
@cdoublev 

> If I am not mistaken, the algorithm for `<alpha-value>` is required when stored internally as an 8-bit integer, which seems to be the case for most browsers (if not all), and helps explaining why `0.499` may be serialized to `0.498`, for example.

0.499 × 255 = 127.245 so if rounded and stored as uint8_t it will be 127
Math.round(50 * 2.55) = 127
So with trailing zeroes omitted it should be serialized as "0.5", no?

**Comment by emilio** [comment]
> Would you like a PR on cssom-1 to remove it from there, or should I just do it?

Either way works for me.

**Comment by emilio** [comment]
(Thanks for taking care of this, I had missed the previous ping)

**Comment by cdoublev** [comment]
> So with trailing zeroes omitted it should be serialized as "0.5", no?

50 * 2.55 = 127.5 but it is 127.499999... because of floating point precision. Rounded up, 127.5 is 128, which is not equal to 127, so the next branch of the algorithm applies.

To be honest, I cannot say I understand all the intricacies of this algorithm and the relation with unsigned 8-bit representation, but `0.498` is the result in Chrome and Firefox.

**Comment by svgeesus** [comment]
@emilio @tabatkins do you know why there is a cssom-specific "rounding up" specified, rather than "round to +infinity" like everywhere else in CSS? Which would give 127 in the example @cdoublev mentioned?

Also do we know the history of this 8bit alpha algorithm, is it baked into Web compat at this point?

**Comment by tabatkins** [comment]
It was added by @zcorpan ten years ago: <https://github.com/w3c/csswg-drafts/commit/1796eb44e47efde910e94b7704c6d85e9cda0781>

I presume we didn't have an obvious precedent at the time so they just wrote something that seemed reasonable.

**Comment by zcorpan** [comment]
Yeah, or I was trying to match implemented behavior in some browser.

**Comment by svgeesus** [comment]
> To be honest, I cannot say I understand all the intricacies of this algorithm and the relation with unsigned 8-bit representation, but `0.498` is the result in Chrome and Firefox.

I [came across this](https://github.com/chromium/chromium/commit/5deed17c9f1446cf0a061d7566e552e8e9bddfaf#diff-1bb6772ac74c6531ba9dd6432fcf301a1d29df66c36bc606e4ab924943ade602R1016) in Chrome:

```
    // Legacy color channels get serialized with integers in the range [0,255].
    // Channels that have a value of exactly 0.5 can get incorrectly rounded
    // down to 127 when being converted to an integer. Add a small epsilon to
    // avoid this. See crbug.com/1425856.
    std::tie(r, g, b) =
        gfx::SRGBToSRGBLegacy(r + kEpsilon, g + kEpsilon, b + kEpsilon);
```

**Comment by cdoublev** [comment]
This is about color channels, not the alpha channel, whose related code appears a few lines below, which is matching the specified algorithm, and which has been introduced the first time in this [commit](https://github.com/chromium/chromium/commit/13a86c2faeebcbc12dd4a7e8dea54318da635c19#diff-9ebe7b1ffff7ac58ac4e82be9f9d7482c19a5cda9ed893a4a47d7d798deaa847).

While digging, I stumbled upon this [commit](https://github.com/chromium/chromium/commit/c285855d6e9d4f24749874c49f9a39a261265d01) message:

  > Previously, rgb() and rgba() parsers were compressing all four color channels and alpha to 8-bit integers. This is no longer necessary, as blink::Color stores the parameters as floats.
  >
  > As we move towards implementing relative color, the more unified the color parsing is, the easier the eventual implementation will be.
  >
  > After some discussion for Interop 2023, it was decided that non-finite color parameters should round-trip and be resolved sanely: http://github.com/w3c/csswg-drafts/issues/8629
  >
  > This new requirement obviously puts us well out of 8-bit integer territory.
  >
  > Unfortunately, there are clearly still some code paths that are independently compressing alpha to be an 8-bit integer and unless we explicitly do this in the parser, many tests fail.

I still do not understand the rounding with 3 decimal places, but maybe things could be simplified now.
