### ISSUE TITLE
[css-viewport-1] Time for FPWD?

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#9799]
Following on from

 - https://github.com/w3c/csswg-drafts/issues/9796#issuecomment-1892586844

There has been no FPWD with the new name, probably it is time for one? There is [an old WD from 2016](https://www.w3.org/TR/2016/WD-css-device-adapt-1-20160329/) that should be redirected to the FPWD.

@frivoal @emilio

**Comment by emilio** [comment]
Sounds good.

**Comment by svgeesus** [comment]
- https://github.com/w3c/transitions/issues/589

**Comment by svgeesus** [comment]
[FPWD published 25 Jan 2024](https://www.w3.org/TR/2024/WD-css-viewport-1-20240125/)
