### ISSUE TITLE
[css-color-5] unclamped alpha through RCS

### ISSUE THREAD

**Issue by romainmenke** [w3c/csswg-drafts#9805]
see : https://github.com/w3c/csswg-drafts/issues/9759#issuecomment-1889541570

@svgeesus said :

> the whole reason we added the serialization of RCS `rgb()`, `hsl()` and `hwb()` to `color(srgb)` specifically to enable round-tripping of out of gamut values. But the text from CSS Color 4 that I quoted above prevents that, which means that CSS Color 5 needs to specifically say that RCS versions of those color functions do not clamp out of range values. And then, do we really want unclamped alpha values like that?

------

I kept coming back to this.
I initially concluded that this behavior isn't useful.

But I wanted to have a better understanding of the implication of either mode.

------

I think there are 2 cases where an unclamped alpha could be observable:
1. calc expressions in RCS
2. interpolation

_I might be wrong here_

https://codepen.io/romainmenke/pen/dyrvGoz

### calc expressions in RCS

```css
rgb(
  /* produce an alpha higher than 1 */
  from rgb(from red r g b / r)
  /* make it smaller */
  r g b / calc(alpha / 2))
```

If the value is clamped then the result must be `0.5`, if it is unclamped it must be `1`.

### interpolation

```css
color-mix(
  in srgb,
  /* produce an alpha higher than 1 */
  rgb(from red r g b / r),
  /* mix it with something semi-transparent */
  rgb(50% 50% 50% / 0.5) 90%
)
```

If the value is clamped then the result must be `rgba(151, 104, 104, 0.55)`, if it is unclamped then it must be `rgb(253, 2, 2)`.

_Other channels are also affected because premultiplying by alpha will have very different results._

----------

Compared to other channels which aren't clamped:

https://codepen.io/romainmenke/pen/OJqpMgr

_Best viewed in Chrome as that implementation is more up to date_

----------

I do think that it is observable that alpha is clamped or not in RCS but I still don't think it enables authors to do something useful.

While clamping will almost always produce the results you would intuitively expect.

There also seems to be interop for clamping alpha in RCS.

@svgeesus thoughts?

**Comment by LeaVerou** [comment]
So it seems that lots of good things come from clamping alpha. What are the arguments *against* clamping?

**Comment by svgeesus** [comment]
None, it happened by accident `¯\_(ツ)_/¯`

**Comment by romainmenke** [comment]
Did it actually happen?

I thought this was mainly something that wasn't fully explored and was maybe lacking some WPT tests.

As far as I can tell both Safari and Chrome clamp alpha.
I also think the spec is quite clear and doesn't imply that alpha isn't clamped.

So could be as simple as adding an extra test and closing this? :)

**Comment by svgeesus** [comment]
> Did it actually happen?

Color 4 says that for `rgb()`, for `r`, `g`, `b`, and `alpha`:

> Values outside these ranges are not invalid, but are clamped to the ranges defined here at parsed-value time.

and for Lab, LH and friends it says

> In Lab, the first argument specifies the CIE Lightness, L. This is a number between 0% or 0 and 100% or 100 Values less than 0% or 0 must be clamped to 0% at parsed-value time; values greater than 100% or 100 are clamped to 100% at parsed-value time.

and does not specify any clamping for `a`, `b`, `C`, `H` or `alpha`.

So RCS, which is currently silent about clamping, needs to say that there is no clamping of color components. And that there _is_ clamping of `alpha`.

And yes, WPT tests would be great once there is a testable assertion in the spec that they can point to.

**Comment by svgeesus** [comment]
How does [that](https://github.com/w3c/csswg-drafts/commit/4429f5f511be30214d2202670f927aeaea264cea) look?

**Comment by romainmenke** [comment]
Thank you for the speedy edits @svgeesus,

Text is clear to me.
The examples had [two typo's](https://github.com/w3c/csswg-drafts/pull/10086) but were otherwise good representations of the behavior.
