### ISSUE TITLE
[css-align] align-content and scroll coordinates

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9807]
In https://www.w3.org/TR/css-align-3/#overflow-scroll-position we write:

> None of this changes how scroll coordinates are assigned: the origin is still where it would be in a [start](https://www.w3.org/TR/css-align-3/#valdef-self-position-start)-aligned container, it just might be initially positioned outside the [scrollport](https://www.w3.org/TR/css-overflow-3/#scrollport).

Wrt scroll coordinates, if we are referring to `.scrollTop`/`.scrollLeft`, I noticed when testing `flex-flow: row-reverse` etc that the initial scroll position corresponds to zero, so I think we should adjust the spec for alignment to be consistent with that: the initial scroll position corresponds to zero, even if that position is scrolled to the writing-mode&ndash;relative "end" of the scroller.

**Comment by frivoal** [comment]
Consistency between row-reverse and alignment seems desirable. I think I could go either way about which of the origin and the initial position gets to be the 0 coordinate, but having the same answer in both cases sounds like the right thing to do.

Are we constrained by compat?

**Comment by Loirooriol** [comment]
I think this is what was being discussed in https://github.com/w3c/csswg-drafts/issues/4957#issuecomment-627004071

**Comment by bfgeek** [comment]
I agree with @Loirooriol - this is what was being described in that issue.
