### ISSUE TITLE
[css-viewport] [cssom] [css-typed-om] Consider adding a way of exposing the effective zoom.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#9809]
Without it, translating global to scaled coordinates is error prone (have to walk the DOM tree upwards multiplying `getComputedStyle(el).zoom`).

My preference would be a member in the computed `CSSStyleDeclaration` (might need a `CSSComputedStyleDeclaration`?) for simplicity, and / or in the `computedPropertyMap` (which IIUC would also need a new interface), but happy to hear other alternatives, maybe just `Element.prototype.effectiveZoom` or such. 

Thoughts?

cc @saschanaz @chrishtr @tabatkins

**Comment by Loirooriol** [comment]
Would this be settable?

**Comment by emilio** [comment]
I don't see a reason to make it settable, a readonly attribute would work.

**Comment by chrishtr** [comment]
Sounds fine to me.
