### ISSUE TITLE
[css-color-4][cssom] Overlap between the definition of resolving color values and serializing <color> component values.

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#982]
Forked from [a comment in another issue](https://github.com/w3c/csswg-drafts/issues/741#issuecomment-275008169)

As discussed at the Seattle F2F, there is some overlap between https://drafts.csswg.org/cssom/#serialize-a-css-component-value and https://drafts.csswg.org/css-color-4/#resolving-color-values.

https://drafts.csswg.org/css-color-4/#resolving-color-values is more specific / clear about which color should resolve to what at what time, but cssom is more specific about how to serialize the various functions once you've decided to do that.

Fixing this redundancy by having css-color-4 just keep the high level logic, and defer to cssom for the string level details of how to serialize the value does not seem particularly good to me, as presumably the new functions added to css-color-4 (and later) will have their serialization in css-color-4 (and later), and then you need to look up to multiple specs to have the full picture.

What I think would be nicer is:
* inline the the details that currently live in cssom into css-color-4
* have css-color-4 normatively state that it supersedes cssom on this topic
* either:
  * leave cssom as is, maybe with a note informatively pointing back to color-4)
  * make cssom normatively reference css-color-4 about this.

 The comment/issue at the bottom of this section of cssom seems to agree:
> One idea is that we can remove this section somewhere in the CSS3/CSS4 timeline by moving the above definitions to the drafts that define the CSS components.

**Comment by svgeesus** [comment]
related to https://github.com/w3c/csswg-drafts/issues/1004 https://github.com/w3c/csswg-drafts/issues/480 https://github.com/w3c/csswg-drafts/issues/1891 https://github.com/w3c/csswg-drafts/issues/585

**Comment by svgeesus** [comment]
I agree that having CSS Color 4 supersede CSSOM is cleaner, particularly since CSSOM currently assumes all values can serialize as either `rgb()` or `rgba()` in other words 8bit-per-component sRGB.

**Comment by svgeesus** [comment]
Having color-4 supersede cssom here was [already proposed and accepted](https://github.com/w3c/csswg-drafts/issues/480#issuecomment-296863660)

**Comment by svgeesus** [comment]
The overlap has now been separated out:

* [Resolving &lt;color> values](https://drafts.csswg.org/css-color-4/#resolving-color-values)
* [Serializing &lt;color> Values](https://drafts.csswg.org/css-color-4/#serializing-color-values)

So the only thing remaining is a PR on CSSOM to remove the color serialization stuff and point to CSS Color 4.
