### ISSUE TITLE
[css-anchor-position]: Question: Why is anchor-size() only valid in a sizing property?

### ISSUE THREAD

**Issue by coderfin** [w3c/csswg-drafts#9827]
Can you help me understand why the [anchor-size() function](https://www.w3.org/TR/css-anchor-position-1/#anchor-size-fn) is limited to being used in a [sizing property](https://www.w3.org/TR/css-sizing-3/#sizing-property)?  It would be useful outside of these properties.

https://www.w3.org/TR/css-anchor-position-1/#anchor-size-valid
https://github.com/web-platform-tests/wpt/blob/master/css/css-anchor-position/anchor-size-parse-invalid.html#L10C4-L10C55

I have a use case where I don't know the `height` or `width` of the _Anchor_ but I would like to apply a `clip-path` to the _Target_ that basically creates a notch in _Target_.

```css
  --anchor-height: anchor-size(--anchor height);
  --anchor-width: anchor-size(--anchor width);
  
  clip-path: polygon(
    0 0,
    0 100%,
    calc(50% - var(--anchor-width) / 2) 100%,
    calc(50% - var(--anchor-width) / 2) var(--anchor-height),
    calc(50% + var(--anchor-width) / 2) var(--anchor-height),
    calc(50% + var(--anchor-width) / 2) 100%,
    100% 100%,
    100% 0
  );
```

![desired-output](https://github.com/w3c/csswg-drafts/assets/1514172/5615d614-575b-4b4b-a17f-88d0a3028451)

**Comment by tabatkins** [comment]
Talking with @bfgeek, we should be able to relax this restriction somewhat, to match the set of properties that are allowed to be used in @position-try. Applying it to a wider set of properties is somewhat problematic, as the properties need to be compatible with "style/layout interleaving".

This would rule out usage in clip-path, tho. We'll have to discuss this further.

**Comment by tabatkins** [comment]
Okay, so two topics:

* Allow `anchor-size()` in any (relevant) "accepted @position-try properties". I think this is fine mechanically, and there are reasonable use-cases for using anchor-size() in inset properties, etc.

* Do we want to add 'clip-path' to "accepted @position-try properties"? It's a paint-time operation, so should be safe impl-wise *I think*, and the use-cases for allowing `anchor-size()` in it make sense. We want to keep the set of properties minimal, but I think clip-path makes a lot of sense for the list.

**Comment by kizu** [comment]
Linking the https://github.com/w3c/csswg-drafts/issues/8586 that proposed a similar thing, alongside a wish to use both `anchor()` and `anchor-size()` for things like `background-position`, `transform` etc.

With `anchor-size()` being an offset, it is understandable that it is weird to have it be present in other properties. But thinking about the use cases I had for this, almost always what we want is a _difference_ between some offsets of any two elements.

Are there any implementation issues in allowing it for properties like `background-position`/`-size`, `transform`, `clip-path` and others where it can make sense, or it just feels odd to have a not useful offset there, usually not making sense by itself outside of calculating with other offsets?

**Comment by cdoublev** [comment]
@tabatkins, I think you should also apply this change in the intro of [4. Anchor-Based Sizing](https://drafts.csswg.org/css-anchor-position-1/#sizing)

  > It is only valid to be used in the sizing properties.

**Comment by tabatkins** [comment]
@cdoublev Yup fixed, thanks.
