### ISSUE TITLE
[css-display] "flow-root" for property "display" is harmful

### ISSUE THREAD

**Issue by laukstein** [w3c/csswg-drafts#983]
"display: flow-root" is harmful:
1. requires to use an extra Element
2. spec doesn't support display multiple values like `display: flex flow-root`

Please implement a new/different property for "flow-root"! Seems any existing property without multiple values support will be harmful ...

How you would want to apply **flow-root** for **flex** Element .selector?

    .selector {
        display: flex;
    }
    <div class=selector></div>

It requires:

    .clearfix {
        display: flow-root;
    }
    .selector {
        display: flex;
    }
    <div class=clearfix>
        <div class=selector></div>
    </div>

If nothing changed, the the old approach is perhaps better:

    .selector {
        display: flex;
    }
    .selector:after {
        content: “”;
        display: block;
        clear: both;
    }
    <div class=selector></div>

Imagine if **flow-root** needed for 2 thousands of Elements - will you require to add in DOM extra 2 thousands Elements only for "clearfix"? ...

**Comment by laukstein** [comment]
What about `min-height: contain-floats` proposal?

**Comment by laukstein** [comment]
The issue discussed also in https://www.rachelandrew.co.uk/archives/2017/01/24/the-end-of-the-clearfix-hack/

**Comment by fantasai** [comment]
I think you are very confused. All display types other than block and inline automatically establish a new formatting context every time, and therefore contain floats. Closing as invalid.

**Comment by laukstein** [comment]
@fantasai, sorry I missed the point of '[formatting context](https://www.w3.org/TR/css-display-3/#formatting-context)' - applied to all display values, except "block", "inline" and "list-item". That makes reason to use "display: flow-root" (that has "block" container) only for elements that natively don't apply `formatting context'.

Please ignore this issue.

BTW any reason why `<fieldset>` has 'formatting context', [example here](http://output.jsbin.com/pobiluyusu/quiet)? It has "block" container. Any more elements/cases like that?

**Comment by fantasai** [comment]
On 01/25/2017 02:32 PM, Binyamin Laukstein wrote:
>
> BTW any reason why |<fieldset>| has 'formatting context', example here <http://output.jsbin.com/pobiluyusu/quiet>? It has "block" container. Any more elements/cases like that?

`<fieldset>` is weird because it is associated with some legacy rendering rules (based on backwards-compatibility requirements 
with the quirkier days of the older Web). There are possibly other such cases; I don't remember off the top of my head.
