### ISSUE TITLE
Query current element style just like container style queries

### ISSUE THREAD

**Issue by jd-solanki** [w3c/csswg-drafts#9834]
Hi 👋🏻 

I'm really excited about new `@container` feature and even more excited about the [style queries](https://developer.chrome.com/docs/css-ui/style-queries) it brought to the table.

With this new API we can query the container and style the children accordion to that query (e.g. `--sunny: true`) however we can only style the children. In modern component based UIs we often want to style the component/element based on the queries like "Button variants => solid, outline, etc". Here's [tweet](https://twitter.com/me_jd_solanki/status/1747486389896372290) explaining my situation with code example.

<img src="https://pbs.twimg.com/media/GEBReB6bEAAFwkz?format=jpg&name=4096x4096" alt="tweet image" />

_(Above is just minimal example, surely we can just use color CSS var for shown example but this to demonstrate the case where we can have multiple styles like bg color, border color, text color and no way to style using style query)_

In above image, I've simple example where I want to style the button based on `--variant` CSS variable/property however I can't directly style the button itself so If we can provide an API for styling the element itself based on some style (this includes all styles like we do with container style query including `font-size`, `color`, etc).

_P.S. I'm new to raising issue here and the spec stuff so pardon me if I made some mistake_ 🙏🏻

**Comment by mirisuzanne** [comment]
That would be nice, but sadly it results in circularity. You are styling the same element that you are querying, and so styles that you apply can change the outcome of the query.

In the example you've shown, it seems simpler to use an attribute like `button-variant='primary'` in place of the custom properties?

**Comment by jd-solanki** [comment]
Attribute is workaround but I'm looking for CSS variable sided solution. Because we can have fallback CSS property for providing default variant. Assume if someone don't pass the button variant then we want it to have fallback of primary. CSS var & proposed solution might come handy.

Feel free to close this if this is out of the scope.

**Comment by ByteEater-pl** [comment]
Maybe there should be a way to set a CSS variable in a cascade layer and mark it so that its value cannot be changed (declarations attempting it are valid but have no effect) in further layers? Then there's no circularity in using such variables in queries within further layers.
