### ISSUE TITLE
[css-ui-4] Transparent accent colors

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9852]
What does it mean for an [accent color](https://drafts.csswg.org/css-ui-4/#widget-accent) to be wholly or partly transparent?

This example shows a series of ratio buttons with black, dark blue, light blue, white, fully transparent, highly transparent dark blue, and slighly transparent dark blue, over a light background, then a dark one.
http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12308

Chrome:
<img width="186" alt="Screenshot 2024-01-25 at 13 42 57" src="https://github.com/w3c/csswg-drafts/assets/113268/7a8d1611-cb18-494d-b5ae-dea0ebbb1b3e">

Safari:
<img width="157" alt="Screenshot 2024-01-25 at 13 43 30" src="https://github.com/w3c/csswg-drafts/assets/113268/95708f0e-5b16-464f-8381-f1fa15044009">

Firefox:
<img width="198" alt="Screenshot 2024-01-25 at 13 44 13" src="https://github.com/w3c/csswg-drafts/assets/113268/f439b4ac-566a-4279-82a4-59b6eba3329b">

In all cases, the accent color is taken into account, and in all cases, reasonable contrast is ensured. So the spec is respected, and this may be all we need.

But I do notice that browsers process the transparency differently:
Chrome and Safari ignore the alpha channel entirely, while Firefox seems to precompose it over white, and use the resulting color as the accent. Note that none of them actually make the accented control transparent (which seems like a good idea in order to manage contrast).

This can result in an accent that is of a visually very different color:
* The 5th radio button (transparent) in Firefox is white (because transparent over white gives white), while it's black in Chrome and Safari (because the `transparent` keyword means transparent black and we're ignoring the alpha channel).
* The 6th button (highly transparent dark blue) in Firefox is light blue, while it's dark blue in Chrome and Safari.

Do we consider this level of variation appropriate to enable differentiation, or should we mandate a particular approach to handling transparency so that authors get more predictable colors?

**Comment by josepharhar** [comment]
I am supportive of changing chromium to match the firefox behavior, assuming that people like the firefox behavior.

> Firefox is white (because transparent over white gives white)

I think you mentioned transposing over white or black based on the color-scheme offline, is that right? I made a quick example and I don't think that firefox is incorporating color-scheme: https://jsfiddle.net/jarhar/5gw86unr/33/

I don't have a preference either way, always transposing over white would make it easier to implement.

**Comment by josepharhar** [comment]
It looks like a chromium bug was already filed for this [here](https://issues.chromium.org/issues/40859651). I also started but didn't finish a [patch](https://chromium-review.googlesource.com/c/chromium/src/+/3851205) to do this a couple years ago 😅

**Comment by josepharhar** [comment]
Proposed resolution: Alpha/transparency in colors provided to the accent-color CSS property should be incorporated by transposing the color on top of white when the computed color-scheme for the element is light or black when color-scheme is dark.

**Comment by alisonmaher** [comment]
Given that we might have more color-schemes in the future, should we consider transposing on top of `Canvas` as opposed to white/black explicitly?

**Comment by tabatkins** [comment]
Yes, definitely composite over Canvas.

**Comment by josepharhar** [comment]
I am implementing transposing on Canvas here: https://chromium-review.googlesource.com/c/chromium/src/+/3851205

**Comment by josepharhar** [comment]
Here is what [this demo](https://jsfiddle.net/jarhar/5gw86unr/36/) looks like with what I've implemented:

<img width="1390" alt="Screenshot 2024-06-13 at 4 57 29 PM" src="https://github.com/w3c/csswg-drafts/assets/7681467/7369515f-c630-402c-aae5-d5737a63dae0">

**Comment by frivoal** [comment]
solved in https://github.com/w3c/csswg-drafts/commit/6993c34d5d2cb82e2c6384e0c0a999d632ce5068

**Comment by frivoal** [comment]
tests in https://github.com/web-platform-tests/wpt/pull/46781
