### ISSUE TITLE
[css-scrollbars] Is the track visible in overlay scrollbars?

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9855]
If the author provides a color for the track (other than transparent), in a user agent set up to use overlay scrollbars, what should happen?

1. The color is ignored, because the track in overlay scrollbars is invisible, and the thumb (when visible) is shown directly over the element
2. The color is used to render the track. The whole scrollbar, track and thumb, may fade in and out as the user interacts with it or not, but when it is visible, all parts of it are visible, and the thumb, if rendered, is always rendered over the track, never directly over the element
3. the color is ignored and the track is invisible while scrolling in general, but used to render the track when the user is interacting with the scrollbar (hovering/clicking)
4. Same as 1, or 3, except that the UA must ensure contrast between the thumb and the element background, by tweaking the color as necessary, when it is painting the thumb directly over the element, without a track.
5. Not defined, up to the UA

I think 5 is not reasonable, because we put the responsibility of ensuring good contrast on the author, which they cannot do if they don't know whether or how the colors are going to be used.

When considering only overlay scrollbars in isolation, I think all of other answers could be considered reasonable. However, authors cannot control nor predict whether classic or overlay scrollbars are going to be used, and this means that 1 is a problem, and to a lesser degree, so is 3. The author may have picked a set of colors whose contrast work well if you use both, but doesn't if you render the thumb against the background of the element instead of against the track.

For instance, imagine a page with a white background, setting up a white thumb against a brightly colored track. With classic scrollbars, the result works. With overlay scrollbars, the thumb is white-on-white, and is invisible.

Currently, Both Firefox and Chrome do 3. Screenshots below are from Firefox using http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12310

Classic scrollbars:
<img width="102" alt="classic" src="https://github.com/w3c/csswg-drafts/assets/113268/11372158-09ae-4bc2-bd82-8142c5f2a59f">

Overlay scrollbars, at rest:
<img width="102" alt="rest" src="https://github.com/w3c/csswg-drafts/assets/113268/306b8205-bf64-4e5b-98ec-e7dafbaf926a">

Overlay scrollbars, scrolling:
<img width="129" alt="scrolling" src="https://github.com/w3c/csswg-drafts/assets/113268/7d8c12bb-2211-45f0-8683-10009d36b322">

Overlay scrollbars, interacting with the bar:
<img width="102" alt="interact" src="https://github.com/w3c/csswg-drafts/assets/113268/b0675858-c8db-4289-ac3e-fcfefa8fbfe0">

As far as I can tell, anything is currently allowed, because the spec says:
> Implementations may ignore any of the colors if the corresponding part do not exist on the underlying platform.

But that doesn't seem compatible with putting authors in charge of ensuring good contrast.

We might want to:
a. Add a requirement to the spec that if the user agent ignores one of the provided colors, then the user agent is responsible for providing good contrast, and it may tweak the color of the part that it isn't ignoring in order to achieve that (option 4 above)
b. Require the user agent to paint always paint a track under the thumb if they're painting the thumb at all (option 2 above)
c. Both of these

My take on this would be that we want at least a.

Note that there's also a separate issue (https://github.com/w3c/csswg-drafts/issues/9853) on whether authors can deliberately pick a transparent color for the track.

**Comment by kizu** [comment]
I agree that we'd want at least “a”:

>  Add a requirement to the spec that if the user agent ignores one of the provided colors, then the user agent is responsible for providing good contrast, and it may tweak the color of the part that it isn't ignoring in order to achieve that (option 4 above)

- - -

> For instance, imagine a page with a white background, setting up a white thumb against a brightly colored track. With classic scrollbars, the result works. With overlay scrollbars, the thumb is white-on-white, and is invisible.

There was [a recent article](https://frontendmasters.com/blog/how-to-fix-the-invisible-scrollbar-issue-in-ios/) by @simevidas about this issue which I feel needs to be mentioned.

**Comment by frivoal** [comment]
My suggestion would be to add minimal normative text, and as well as informative text:

> If the user agent displays the scrollbar without the [=track=], they <em class=rfc2119>must</em> ensure reasonable contrast between the [=thumb=] and what is behind it.
> 
> Note: This is typically relevant in the case of [=overlay scrollbars=], either on platforms where the [=track=] is never displayed, or on platforms where it is only displayed when the scrollbar is being interacted with but not when scrolling with the mouse wheel or the track-pad. This does not apply in cases where the entire scrollbar is hidden as is often the case with [=overlay scrollbars=] while no scroll operation is ongoing <em>and</em> when the scrollbar is not being interacted with either.
> 
> Note: The user agent is free to achieve this by any of a variety of means, depending on the platform, on design choices, or on what is practical to implement, such as:
>  * Doing nothing if it can determine that contrast is already sufficient
>  * Doing nothing if the design and geometry of the thumb ensures that some part of it will always be visible regardless of what is behind it
>  * Adding an outline, shadow, or glow around the [=thumb=] to provide contrast (possibly using the [=track=] color as the contrasting color, or possibly using a different shade of the [=thumb=] color)
> * Adding some texture or geometry to the [=thumb=] so that it's color isn't uniform
>  * Drawing the [=track=] anyway in cases where not doing so yields insufficient contrast
>  * Replacing the [=thumb=] color with the [=track=] color when that provides better contrast
>  * Altering the luminosity of the specified [=thumb=] color while preserving its hue
>  * Disregarding the specified [=thumb=] color altogether and use automatically determined alternative

I think this needs to be a MUST because otherwise authors could pick colors that lead to unusable contrast through no fault of their own.

I think this can be a MUST because it is always possible to implement something that works.

It might be hard to implement given some design choices, but these are choices, and the user agent should be prepared to deal with the consequences of those choices. If the thumb isn't a single flat color with no geometry, no outline, and no shading, then this isn't an issue. If the track is shown whenever the thumb is shown, then this isn't an issue. Yes, user agents can chose to have a flat featureless thumb over no track, but that is what causes this issue, so that choice needs to come with countermeasures.

**Comment by bramus** [comment]
> b. Require the user agent to paint always paint a track under the thumb if they're painting the thumb at all (option 2 above)

Variant of this: give authors control over this behavoir. Something like a `scrollbar-render-track: forced;` which authors can choose to put on `.scroller` or only `.scroller:hover` if they want. This property is similar to [an earlier suggestion of mine to force paint the thumb using `scrollbar-render-track: thumb;`](https://github.com/w3c/csswg-drafts/issues/9785).
