### ISSUE TITLE
[css-scrollbars] Interaction between scrollbar-color and scrollbar-width with ::-webkit-scrollbar

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#9856]
The css scrollbar spec has a section explicitly declaring `::-webkit-*` scrollbar pseudos, and any other similar approach as out of scope: https://drafts.csswg.org/css-scrollbars/#out-of-scope

As documented in multiple previous issues, this is based on the consensus (including implementers) that this approach is a bad idea, and that shipping `::-webkit-*` scrollbar pseudos in the first place was a bad idea / accident which we wish we had avoided.

However, the wpt test suite contains a significant number of tests about the interaction between `scrollbar-color` and `scrollbar-width` with `::-webkit-scrollbar`.

<details><summary>It has 17 tests, for a total of 21 subtests</summary>
<ul class="wpt-tests-list">
     <li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-001.tentative.html">scrollbar-color-001.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-002.tentative.html" >scrollbar-color-002.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-003.tentative.html">scrollbar-color-003.html<small> (2 tests)</small></a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-004.tentative.html">scrollbar-color-004.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-005.tentative.html">scrollbar-color-005.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-006.tentative.html">scrollbar-color-006.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-007.tentative.html">scrollbar-color-007.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-008.tentative.html">scrollbar-color-008.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-009.tentative.html">scrollbar-color-009.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-color-010.tentative.html">scrollbar-color-010.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-010.tentative.html">scrollbar-width-010.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-011.tentative.html">scrollbar-width-011.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-012.tentative.html">scrollbar-width-012.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-013.tentative.html">scrollbar-width-013.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-014.tentative.html">scrollbar-width-014.html</a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-015.tentative.html">scrollbar-width-015.html<small> (2 tests)</small></a><span class="wpt-results"></span>  
     </li><li class="wpt-test"><a class="wpt-name" href="https://wpt.fyi/results/css/css-scrollbars/scrollbar-width-016.tentative.html">scrollbar-width-016.html<small> (3 tests)</small></a><span class="wpt-results"></span>  
    </li></ul>
</details>

These tests are designed to pass if the user agent does not support `::-webkit-scrollbar` at all (which is the case for Firefox), but they do expect a specific behavior if `::-webkit-scrollbar` is supported, and that behavior is not specified anywhere as far as I can tell.

What should we do?
* while keeping `::-webkit-scrollbar` optional / deprecated, specify the expected interaction, maybe in css-scrollbars, maybe in https://compat.spec.whatwg.org/
* delete the tests, to avoid constraining the behavior of a feature we're trying to get rid of
* keep the tests, but mark them as [`.tentative`](https://web-platform-tests.org/writing-tests/file-names.html#:~:text=tests%2C%20like%20%E2%80%9CMUST%E2%80%9D.-,.tentative,-%3A%20Indicates%20that%20a)
* something else?

**Comment by lukewarlow** [comment]
I would prefer to keep them in some form they're useful to make sure that Webkit and chromium match in their behaviour.

**Comment by frivoal** [comment]
[Marking them](https://github.com/web-platform-tests/wpt/pull/44217) as [`.tentative`](http://web-platform-tests.org/writing-tests/file-names.html) for now, which lets us keep them while indicating that they're not part of the spec. We can always decide to do something else later.

**Comment by bfgeek** [comment]
+1 to keeping them - can also use .optional instead of .tentative if needed.

**Comment by frivoal** [comment]
Don't think `.optional` is appropriate, those are for MAY statements, which presumes that there's a spec, which we don't have.

**Comment by frivoal** [comment]
I think we could specify the interaction without specifying the legacy mechanism, by saying that any non-`auto` value of `scrollbar-width` or `scrollbar-height` takes precedence over any non-standard alternative mechanism offered to authors to style the scrollbars.

**Comment by smfr** [comment]
There are two possible interactions I can see between the `scrollbar` style properties and the styled pseudo elements (`::-webkit-scrollbar` etc):

1.  If `::-webkit-scrollbar` pseudos are specified, the UA uses them to render the scrollbars. `scrollbar-width` and `scrollbar-color` are ignored.
2. If `scrollbar-width` or `scrollbar-color` are specified, the UA ignores any `::-webkit-scrollbar` pseudo-elements.

The latter seems preferable for forward progress towards removing `::-webkit-scrollbar` support, so I agree with @frivoal
