### ISSUE TITLE
[css-view-transitions-2] Timing for checking at-rule

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#9867]
The CSS opt-in which decides whether navigating away from a Document will trigger a transition is currently spec'd to be checked at 2 places:

1. When the navigation is initiated. This is being landed in the html spec as a part of sourceSnapshotParams which are cached when the navigation starts: https://github.com/whatwg/html/pull/10002/files#r1464196273. We require it early in the navigation lifecycle for performance reasons.

2. The second spot is here: https://drafts.csswg.org/css-view-transitions-2/#resolve-view-transition-rule-algo:~:text=Resolve%20%40view%2Dtransition%20rule%20for%20oldDocument%20and%20let%20resolvedRule%20be%20the%20result. This runs once we have the final response and before the old Document is unloaded.

I'm not sure doing it at step 2 is a good idea. It'll be racy since the task which runs these steps doesn't have an event which fires before the steps. So there's no way to reliably update the CSS. Also, we're providing an explicit event which has a VT object, the robust way would be to call `skipTransition()` on it. Having this check could encourage authors to opt-out via CSS after the navigation has been initiated instead of the more reliable event way.

**Comment by khushalsagar** [comment]
Summary from offline conversation, there's stages in the navigation's lifecycle where we could read the opt-in: when the navigation is initiated and when we have the final response (the navigation is ready to be committed). Ideally we'd use the latter timing to have the most up-to-date preference from the author. For example, if a media query like `prefers-reduced-motion` changes which opts-out of transitions that should apply.

We have to check the opt-in at the first spot for perf reasons, so the reasonable option would be to keep both. There must be an opt-in at both stages of the navigation for a transition to happen.

**Proposed Resolution**: A navigation has a transition if there is a cross-document opt-in when the navigation is initiated and when its ready to commit.

**Comment by noamr** [comment]
We already do this.
