### ISSUE TITLE
[css-view-transitions-2] Update non-normative notes once `pageconceal` or so is upstreamed

### ISSUE THREAD

**Issue by noamr** [w3c/csswg-drafts#9886]

**Comment by khushalsagar** [comment]
This text could also reference explicit pageconceal and pagereveal events: https://drafts.csswg.org/css-view-transitions-2/#:~:text=(when%20unloading)%20and%20in%20the%20new%20document%20(when%20reveal).

**Comment by khushalsagar** [comment]
remove https://drafts.csswg.org/css-view-transitions-2/#:~:text=boolean%2C%20initially%20false.-,should%20a%20cross%2Ddocument%20transition%20take%20precedent%3F%20See%20%239512,-active%20types

**Comment by khushalsagar** [comment]
Add a non-normative note for algorithms invoked by the html spec. For example: https://drafts.csswg.org/css-view-transitions-2/#resolve-view-transition-rule-algo

**Comment by khushalsagar** [comment]
This should be in L2: https://drafts.csswg.org/css-view-transitions-2/#resolve-view-transition-rule-algo:~:text=Set%20oldDocument%E2%80%99s%20auto%2Dskip%20view%20transitions%20to%20true.

**Comment by khushalsagar** [comment]
Move this to L2: https://drafts.csswg.org/css-view-transitions-1/#viewtransition-process-old-state-captured

**Comment by khushalsagar** [comment]
"Call onReady" should be the last step of https://drafts.csswg.org/css-view-transitions-2/#setup-cross-document-view-transition

**Comment by fantasai** [comment]
(p.s. @noamr please do me a favor and label your issues :)

**Comment by noamr** [comment]
> (p.s. @noamr please do me a favor and label your issues :)

Ack

**Comment by noamr** [comment]
I believe all of this is addressed now.
