### ISSUE TITLE
[css2-testing] change description about canvas background doesn't match the change

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#989]
The [changes section of css2-testing](https://drafts.csswg.org/css2-testing/changes.html) (or [its equivalent on the CSS2.2 WD on TR](https://www.w3.org/TR/2016/WD-CSS22-20160412/changes.html)) has a [change to canvas backgrounds date 2014-07-16](https://drafts.csswg.org/css2-testing/changes.html#s.14.2).

The **change description** does not match the change.  The change description says that the change makes the canvas background undefined, while the actual change to the spec makes the canvas background transparent.  I suspect transparent is correct, although I'm not sure.

**Comment by bert-github** [comment]
On Monday, January 30, 2017 3:32:25 PM CET L. David Baron wrote:
> The [changes section of
> css2-testing](https://drafts.csswg.org/css2-testing/changes.html) (or
> [its equivalent on the CSS2.2 WD on
> TR](https://www.w3.org/TR/2016/WD-CSS22-20160412/changes.html)) has a
> [change to canvas backgrounds date
> 2014-07-16](https://drafts.csswg.org/css2-testing/changes.html#s.14.2)
> .
> 
> The **change description** does not match the change.  The change
> description says that the change makes the canvas background
> undefined, while the actual change to the spec makes the canvas
> background transparent.  I suspect transparent is correct, although
> I'm not sure.

Yes, transparent is correct.

The WG decided first (2014-07-09) that the canvas background was not 
taken from the root element, without saying what it was taken from 
instead. I proposed corresponding errata text that said the background 
was "undefined". The WG reviewed the text and decided[1] (2014-07-16) to 
replace "undefined" by "transparent". I updated the errata accordingly, 
but indeed forgot to update the explanation. I've updated that now, too.

Thanks for the review!

[1] http://lists.w3.org/Archives/Public/www-style/2014Jul/0299.html



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France
