### ISSUE TITLE
[css2-testing] parenthetical sentence should begin with capital letter

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#990]
The [changes section of css2-testing](https://drafts.csswg.org/css2-testing/changes.html) (or [its equivalent on the CSS2.2 WD on TR](https://www.w3.org/TR/2016/WD-CSS22-20160412/changes.html)) has a [change to canvas backgrounds dated 2014-07-16](https://drafts.csswg.org/css2-testing/changes.html#s.14.2).

This change introduces a parenthetical sentence that should begin with a capital letter, but does not:
> (in CSS 2.1, that is the case when the element or an ancestor has 'display: none'.)

**Comment by bert-github** [comment]
On Monday, January 30, 2017 3:33:53 PM CET L. David Baron wrote:
> The [changes section of
> css2-testing](https://drafts.csswg.org/css2-testing/changes.html) (or
> [its equivalent on the CSS2.2 WD on
> TR](https://www.w3.org/TR/2016/WD-CSS22-20160412/changes.html)) has a
> [change to canvas backgrounds dated
> 2014-07-16](https://drafts.csswg.org/css2-testing/changes.html#s.14.2)
> .
> This change introduces a parenthetical sentence that should begin with 
a capital letter, but does not:
> > (in CSS 2.1, that is the case when the element or an ancestor has
> > 'display: none'.)

Fixed.



Bert
-- 
  Bert Bos                                ( W 3 C ) http://www.w3.org/
  http://www.w3.org/people/bos                               W3C/ERCIM
  bert@w3.org                             2004 Rt des Lucioles / BP 93
  +33 (0)4 92 38 76 92            06902 Sophia Antipolis Cedex, France
