### ISSUE TITLE
[css-view-transitions-2] `CSSViewTransitionRule.type` overrides deprecated `CSSRule.type`

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9905]
One may expect `0` from getting [`CSSViewTransitionRule.type`](https://drafts.csswg.org/css-view-transitions-2/#dom-cssviewtransitionrule-type).

  > The [type](https://drafts.csswg.org/cssom-1/#dom-cssrule-type) attribute is deprecated. It must return an integer, as follows:
  >
  > [...]
  >
  > Otherwise, return `0`.

I guess it is ok if it returns the descriptor value, but I would just like to make sure.

**Comment by tabatkins** [comment]
No, this does need fixing. The naming clash is unfortunate, but subclasses shouldn't override an attribute with an incompatible type.

**Comment by noamr** [comment]
OK, proposing `typeList` (like `classList`) as this is a `DOMTokenList`.

**Comment by cdoublev** [comment]
Probably too late but it would have been nice to match the [descriptor](https://drafts.csswg.org/css-view-transitions-2/#descdef-view-transition-type), the [CSS rule attribute](https://drafts.csswg.org/css-view-transitions-2/#dom-cssviewtransitionrule-typelist), and the [argument property for `startViewTransition()`](https://drafts.csswg.org/css-view-transitions-2/#dom-startviewtransitionoptions-type), eg. with `active-type`/`activeType`.

It allows blindly defining descriptors from the specified declarations with [the appropriate algorithm](https://drafts.csswg.org/cssom-1/#css-property-to-idl-attribute), as is usually (always?) the case with other CSS rules mirroring specified declarations and exposed attributes.
