### ISSUE TITLE
[css-backgrounds] - Reappeal for Background Alpha's or Background Opacity | extremely useful for CMS's

### ISSUE THREAD

**Issue by ArvindKumar08** [w3c/csswg-drafts#9910]
In CMS themes, color schemes are often predefined, with RGB / Hex values set in the theme configuration to ensure visual consistency across the site. A background-opacity or background-alpha feature would allow designers and developers to adjust the transparency of these preset colors directly, enhancing the theme's flexibility without the need to redefine RGB values for each instance. This approach minimizes code redundancy, simplifies the design process, and reduces potential for errors, making theme customization more efficient and consistent.

Practical Application in Widgets: Consider the use of widgets or blocks within a CMS-powered site, where the background color needs to blend or contrast with the underlying content or imagery for visual effect or readability. Currently, to change the opacity, developers might have to use RGBA values or overlay elements, which complicates maintaining theme consistency.

CSS Examples:

Current method using RGBA for background color with opacity:

`.theme1.widget-background {
  background-color: rgba(255, 99, 71, 0.5); /* Requires redefining the RGB values with opacity */
}`
`.theme2.widget-background {
  background-color: rgba(255, 255, 71, 0.5); /* Requires redefining the RGB values with opacity */
}`
`.theme3.widget-background {
  background-color: rgba(245, 40, 145, 0.5); /* Requires redefining the RGB values with opacity */
}`
`.theme4.widget-background {
  background-color: rgba(39, 63, 245, 0.5); /* Requires redefining the RGB values with opacity */
}
`

Proposed method with background-opacity:

`.widget-background {
  background-opacity: 0.5; /* Directly adjust only the opacity */
 background-alpha: 0.5; /* Alternative Suggestion */
}
`
This proposed method allows for the background color's opacity to be adjusted independently of its color value, streamlining the development process without the need to go through each theme. Developers can retain the use of the theme's predefined RGB values, ensuring consistency, while easily modifying the transparency level to suit different contexts, such as enhancing readability over varied backgrounds or achieving specific visual effects in widgets and content blocks.

**Conclusion:** Introducing background-opacity or background-alpha into CSS would significantly benefit CMS theme design and customization, offering a more straightforward and efficient way to adjust visual elements. This feature would ensure that theme consistency is easily maintained, reduce coding complexity, and enhance the overall design flexibility and user experience of CMS-powered websites.

**Comment by tabatkins** [comment]
This is addressed by the Color 5 [relative color syntax](https://www.w3.org/TR/css-color-5/#relative-colors), where you can write:

```css
.theme1 {
  --color: rgb(255 99 71);
  color: var(--color);
  background-color: rgb(from var(--color), r g b / 0.5);
  /* Use the --color variable, keeping r g b unchanged, but set the alpha to .5 */
}
```

**Comment by ArvindKumar08** [comment]
Hi @tabatkins , 

I appreciate your quick response on this, please know that this approach was completely taken into account when I posted this issue. Please allow me to explain the scenario that may not have been clear in the beginning.

When you work with WordPress, Kentico, Shopify etc. you usually input the colors in a section where most primary colors are identified. How these CMS's are structured usually take the color from there and pass along the information into a CSS file dynamically generated by the CMS itself. Now imagin the scenario if we only needed to modify the alpha values for the background-color or any color in this matter. 

I dont see the need of re-doing everything that the cms is already doing for you just for the alpha value. Developers/designers should be given the specificity to modify just the alpha value of a color.

I really appreciate your input on this but I believe the CMS development industry may also hope you see the need from this perspective. 

Kind regards.

**Comment by tabatkins** [comment]
The technique I outlined above can be used by CMSes as easily as any other author. For example, they could store the colors you input in custom properties, and then use those custom properties themselves, rather than hardcoding the colors directly into the places where they use them; this way, you *also* get access to those colors, and you can then use relative color syntax as I showed to adjust the color to your needs.

In general, fixing an issue in a framework is both far easier *and* far faster than trying to add a new feature to a browser.

**Comment by Crissov** [comment]
If I understand the use case correctly, you would rather want something like this, but Tab’s points are still as valid:

~~~~ css
.widget-background { 
--background-alpha: 50%; 
  background-color: rgb(from var(--color), r g b / var(--background-alpha)); 
}
.theme1 { --color: #FF6347; }
.theme2 { --color: #FFFF47; }
.theme3 { --color: #F52891; }
.theme4 { --color: #273FF5; }
~~~~
