### ISSUE TITLE
[css-display-4] Is reading-order-items the best name for this property?

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#9921]
Working on [spec edits](https://github.com/w3c/csswg-drafts/pull/9845) for reading order. @bradkemper proposes that the property be named `reading-order` or `reading-flow` not `reading-order-items`.

Summary of discussion so far:

1. The name `reading-order-items` (on the flex or grid container to indicate reading order behavior of direct children) was used as we initially had `reading-order` as a property for the children (with a value of `auto` or `<integer>`. 
2. The current edits do not include a `reading-order` property as it was resolved in [8589](https://github.com/w3c/csswg-drafts/issues/8589#issuecomment-1721504153) that we did not need it.
3. We do intend to leave the possibility of bringing back a property for the children in future, so any naming should keep sensible possibilities for that in mind. 
4. Brad's argument for `reading-flow` is that it makes sure there is no link with the `order` property, which could be confusing.

Question for the group is should we keep `reading-order-items` as the name for the property on the parent, drop the suffix and use `reading-order` or move completely away from mention of order and use `reading-flow`?

**Comment by dbaron** [comment]
I think either of the proposed renames here seems reasonable to me.

I think the initial concern about keeping a property name available for a property on the children isn't a problem with either of them, since I think it would be good for such a property to have an `-index` suffix (like `z-index`).  So a property that went on the children could be `reading-order-index` or `reading-flow-index`, depending on what we decide here.

**Comment by rachelandrew** [comment]
The overwhelming preference from developers I spoke to after presenting on the subject at CSS Day, was that we go with `reading-order`. As we have a `flex-flow` value for the property, I think `reading-flow: flex-flow` would be weird, whereas `reading-order: flex-flow` makes sense. 

I like @dbaron's suggestion for `reading-order-index`, if we needed a property for the children in future.
