### ISSUE TITLE
[cssom-view] Specify document.caretPositionFromPoint in shadow DOM scenario

### ISSUE THREAD

**Issue by siliu1** [w3c/csswg-drafts#9932]
Current spec is vague about the behavior in shadow DOM: https://www.w3.org/TR/cssom-view-1/#dom-document-caretpositionfrompoint

Gecko's current behavior in shadow DOM:
The returned `CaretPosition`'s `offset` is the text offset of the hit tested text node and the `offsetNode` depends on the mode of the shadow tree:
  1. If the tree is created by user agent such as input element, the node is the shadow host.
  2. Otherwise, the node is the hit tested text node even if the tree is closed.

Gecko's existing behavior can address most of the need for web developers. Should we specify the behavior?

Or are there other alternatives that we should consider:
  1. `caretPositionFromPoint` do not pierce shadow DOM. Instead, put the API on `DocumentOrShadowRoot`.
  2. support closed shadow root with a new parameter: `document.caretPositionFromPoint(x, y, closedShadowRoot);`

**Comment by sanketj** [comment]
@zcorpan @fantasai @tabatkins Curious if any of you have any thoughts on how we can better define the behavior of `caretPositionFromPoint` for shadow DOM scenarios?

**Comment by siliu1** [comment]
Asked opinions from web developer's point of view and got some feedback. Web developer's basic requirement is to be able to get a caret position inside shadow roots. The Firefox approach (piercing through the shadow boundary) is acceptable. In fact, sticking to the already existing behavior would allow web developer to simplify the implementation. 

Given that, should we specify the already existing Firefox approach and put it in spec?

**Comment by siliu1** [comment]
Based on all feedback, the best approach seems to be the `getComposedRanges()` style which takes in a set of `ShadowRoots` and `document.caretPositionFromPoint(ShadowRoot ...shadowRoots)` can return position in the given shadow roots.

The alternative approach is to put the API on `DocumentOrShadowRoot`. But the con to this approach is that the usage might be cumbersome to get a position inside nested shadow roots (need to call the API on each level of shadow root).

Web developer needs to adjust the current usage of current API to get position in a shadow root. The existing behavior violates the boundary of closed shadow tree so we should consider fixing it as well.

**Comment by siliu1** [comment]
Created PR https://github.com/w3c/csswg-drafts/pull/10200 to update the spec. @zcorpan would you mind taking a look? Thank you!

**Comment by zcorpan** [comment]
The PR was merged, closing.
