### ISSUE TITLE
[css-nesting-1] Should the parent rule be considered when validating a selector containing `&`?

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#9943]
Follow-up on https://github.com/w3c/csswg-drafts/issues/9940#issuecomment-1941374685. 

Should the nested style rule in `::before { &:first-child {} }` be valid or invalid? `::before:first-child {}` is [invalid](https://drafts.csswg.org/selectors-4/#pseudo-element-states).

This does not seem specified at the moment.

It may be surprising to get different results between the flat/nested versions. But setting `CSSStyleRule.selectorText` would require considering the selector of each parent/nested style rules.

I am also not sure I understand the reasons why `::before:first-child {}` should be considered invalid, instead of as matching nothing.

**Comment by tabatkins** [comment]
It *is* well-specified - nothing makes it invalid, so there's no reason to assume it's invalid.

> I am also not sure I understand the reasons why `::before:first-child {}` should be considered invalid, instead of as matching nothing.

Historical mistake. Selector validity in general should have been done quite differently, but we're stuck with it.
