### ISSUE TITLE
[css-anchor-position-1] Document the reason for excluding base styles from `position-try-order`

### ISSUE THREAD

**Issue by dholbert** [w3c/csswg-drafts#9946]
Spinning this off of #9196 -- @tabatkins mentioned there are design reasons why we're planning to (by default) exclude the base styles from the `position-try-order` sorting.  It would be nice to document those reasons (and the use cases that we're intending this default behavior to address) somewhere in the spec.

**Comment by dholbert** [comment]
As I understand it from chatting with Tab just now: the rough reasoning here is a generalization of how e.g. dropdown-menus work, where they typically default to going downwards as the preferred-direction, regardless of available space, and they stick with that direction until they don't fit.  Only then do they consider the fallback options (which in the case of dropdown menus would be the single option of going upwards instead of downwards), and that's the point at which we might sort among the fallback options to pick `most-width | most-height` one.

**Comment by tabatkins** [comment]
Yup, that's it. In many (most?) cases, your "starting" styles are the ideal presentation you want, and you'll want to use it regardless of available space, so long as it fits.
