### ISSUE TITLE
[mediaqueries][color] dynamic-range is a really ambiguous term and doesn't mention it's about color

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9957]
`dynamic-range` is totally not clear that it's about color, it should have the word "color" in it.

**Comment by dbaron** [comment]
This initially came up in the WG discussion we just had about #9074.

**Comment by svgeesus** [comment]
Similarly, from a theoretical purity perspective, the `color` property should be `foreground-fill-color`. But the spec [describes that](https://drafts.csswg.org/css-color-4/#the-color-property) quite well, so the property name can be short:

> This property specifies the primary foreground color of the element. This is used as the fill color of its text content

So I don't think we need a non-Web-compatible name change to `peak-luminance-dynamic-range` or whatever. Just describe it clearly in the specification.

**Comment by svgeesus** [comment]
So, close?

**Comment by svgeesus** [comment]
> So I don't think we need a non-Web-compatible name change to `peak-luminance-dynamic-range` or whatever. Just describe it clearly in the specification.

Now [defined clearly](https://drafts.csswg.org/css-color-hdr/#defining-dynamic-range)

**Comment by astearns** [comment]
@fantasai please close if you are satisfied with the discussion so far, or add more argument here for your position.

**Comment by svgeesus** [comment]
> @fantasai please close if you are satisfied with the discussion so far, or add more argument here for your position.

I would suggest first reading [2.1. Defining Dynamic Range](https://drafts.csswg.org/css-color-hdr/#defining-dynamic-range)
