### ISSUE TITLE
[cssom] Please remove  _camel_cased_attribute and friends from the IDL index

### ISSUE THREAD

**Issue by Ms2ger** [w3c/csswg-drafts#996]
https://drafts.csswg.org/cssom/#idl-index

Having those listed makes it more annoying to update the idlharness test.

CC @zcorpan

**Comment by zcorpan** [comment]
@tabatkins how do I do this?

**Comment by csnardi** [comment]
These no longer appear to show up in the IDL index, so I think this can be closed. (also related, #2487)
