### ISSUE TITLE
[css-fonts-4] linkable definition of palette-mix() function (not <palette-mix()> type)

### ISSUE THREAD

**Issue by foolip** [w3c/csswg-drafts#9969]
[`<palette-mix()>`](https://drafts.csswg.org/css-fonts/#typedef-font-palette-palette-mix) with angle brackets around it is used in the definition of [`font-palette`](https://drafts.csswg.org/css-fonts/#font-palette-prop)'s value, and I take the angle brackets and URL to mean it's a type, no the `palette-mix()` function itself.

I would like there to be a linkable definition of the function, similar to for `color-mix()`:
https://drafts.csswg.org/css-fonts-4/#funcdef-palette-mix (does not exist)
https://drafts.csswg.org/css-color-5/#funcdef-color-mix (exists)

I suspect that it did work in @drott's https://github.com/w3c/csswg-drafts/pull/9282, but @cdoublev's https://github.com/w3c/csswg-drafts/pull/9381 removed it as duplicate. To avoid flipping back and forth, I'm filing an issue instead of sending a PR.

**Comment by cdoublev** [comment]
I think `font-palette()` should be defined (wrapped in `<dfn>`) [here](https://github.com/w3c/csswg-drafts/blob/f757bd0f993c34a4dd7048726af463d301ecb7b6/css-fonts-4/Overview.bs#L7346).

> This is the function definition pattern I think we should be aiming for:
> 
> ```
> The <dfn>foo()</dfn> function blah bla.
> 
> <pre class=prod>
>   <<foo()>> = foo( ... )
> </pre>
> ```

https://github.com/w3c/csswg-drafts/issues/2921#issuecomment-1823617065

**Comment by svgeesus** [comment]
I agree with @foolip that we should have a linkable definition. @cdoublev would you like to make a PR to define it?

**Comment by cdoublev** [comment]
Yes, sure. #9976
