### ISSUE TITLE
[css-masking] make the behavior of an invalid mask  be consistent with clip-path and filter

### ISSUE THREAD

**Issue by CJKu** [w3c/csswg-drafts#997]
According to css-masking spec,[1]:

> A mask reference that is an empty image (zero width or zero height), that fails to download, is not a reference to an mask element, is non-existent, or that cannot be displayed (e.g. because it is not in a supported image format) still counts as an image layer of **transparent black.**

Transparent black means the masked object disappeared. The way we handle invalid mask is apparently not the same with clip-path and filter. Both clip-path[2] and filter[3] keep the target element visible. I wonder why only masking has different behavior and think it would be better to keep the consistent.

[1] css-masking positioned-mask
https://drafts.fxtf.org/css-masking-1/#the-mask-image

[2] css-masking clip-path
https://drafts.fxtf.org/css-masking-1/#the-clip-path

> If the URI reference is not valid (e.g it points to an object that doesn’t exist or the object is not a clipPath element), **no clipping is applied**.

[3] css filter
https://drafts.fxtf.org/filters/#FilterProperty
> A filter reference to a filter element. For example url(commonfilters.svg#filter). If the filter references a non-existent object or the referenced object is not a filter element, then the whole filter chain is ignored. **No filter is applied to the object**.

**Comment by fantasai** [comment]
This issue was moved to w3c/fxtf-drafts#130
