### ISSUE TITLE
[css-selector-for-is-attribute] Feature Request 

### ISSUE THREAD

**Issue by clarumedia** [w3c/csswg-drafts#9973]
Please accept my apologies if this is already a topic, feature, or I have submitted this request incorrectly.

RFC to support CSS attribute selector to target custom components via the "is" attribute.

<input type="text" is="my-custom-component">

input[is=my-custom-component]
   color:red;
}

FWIW: I prefer the "is" attribute eg: <input type='text' is='my-custom-component'> because I think it degrades better than <my-custom-component> in situations where the JS code may have failed etc.

Many thanks

**Comment by Loirooriol** [comment]
It's hard to tell what you are asking for, this already works:

```html
<style>
input[is=my-custom-component] {
  color: red;
}
</style>
<input is="my-custom-component" value="This is red">
```

**Comment by clarumedia** [comment]
You're absolutely right. My bad !
The "is" attribute rocks !
Many thanks for your response.

**Comment by clarumedia** [comment]
Thank you
