### ISSUE TITLE
[css-scoping-1][css-shadow-parts-1] Can the non-functional `:host` be compound? And should `::part()` select within its own shadow root?

### ISSUE THREAD

**Issue by knowler** [w3c/csswg-drafts#9981]
Currently in all browsers, within a shadow root, a selector such as `:host::part(something)` _will_ select parts within that same shadow root. I’m curious if this is intentional as I cannot tell from the spec that the non-functional `:host` pseudo-class can be a compound selector like this. Admittedly, _this is a nicer API_ than using an attribute selector, so I am happy if that’s the case. Further, in Firefox, a selector like `::part(something)` on its own within a shadow root can select parts within the same shadow root. This seems maybe a bit problematic since then it could select parts within two shadow roots at the same time (e.g. a nested shadow root as well).

[Demo for each case mentioned](https://knowler.dev/demos/2r9dkgZ?codepen)

**Comment by cdoublev** [comment]
[This comment](https://github.com/w3c/csswg-drafts/issues/2423#issuecomment-371463760) probably answers your question about compounding `:host`:

> `:host` will only ever match anything if these hold:
> 
> 1. `:host` appears in the leftmost compound selector.
> 2. `:host` is the only simple selector in that compound.
> 
> "For the purpose of Selectors, a shadow host also appears in its shadow tree, with the contents of the shadow tree treated as its children. (In other words, the shadow host is treated as replacing the shadow root node.)

**Comment by knowler** [comment]
I just found [the Firefox bug for the bare `::part()` selector working in its own shadow root](https://bugzilla.mozilla.org/show_bug.cgi?id=1739682)—looks like that’s not supposed to work even though they’ve set it to `wontfix`. I’m going to close, but to summarize:

1. The compound selector `:host::part()` matching in its own root is valid (and intentional).
2. The bare `::part()` selector matching in its own root is invalid and there’s a bug for Firefox already reported.
