### ISSUE TITLE
[cssom-1][css-color-4] "specified value" here would better be reworded as declared value

### ISSUE THREAD

**Issue by qnighy** [w3c/csswg-drafts#9993]
[Serializing CSS Values](https://www.w3.org/TR/2021/WD-cssom-1-20210826/#serializing-css-values) mentions specified, resolved, computed, and used values for serialization. The specified values are mentioned here with values from CSSStyleSheet or ElementCSSInlineStyle in mind. In css-cascade-5 terminology, however, it corresponds with declared values rather than specified values.

One important difference is with CSS-wide keywords. CSS-wide keywords, such as `inherit`, are serialized as they are within CSSOM APIs like `cssText`. This is unintuitive if they are called specified values, as they should have been resolved to other values in specified values (in the sense of css-cascade-5).

The same argument applies to [Resolving \<color\> values](https://www.w3.org/TR/2024/CRD-css-color-4-20240213/#resolving-color-values).

**Comment by svgeesus** [comment]
Understood. Would you like to make a pull request to correct this?

**Comment by qnighy** [comment]
Yes, I'd love to!
