### ISSUE TITLE
[css-view-transitions-1] Clarify the list of pseudo-elements that can be followed with `:only-child`

### ISSUE THREAD

**Issue by nt1m** [w3c/csswg-drafts#9996]
I'm guessing all the functional pseudo-elements can be followed by `:only-child`, but there are some clarifications I'd like to see:

1. Does it apply to `::view-transition` ? (It would always apply if yes?)

2. Does it apply to `::view-transition-group(...)` / `::view-transition-image-pair(...)` ? (I'm guessing yes)

3. Is an element with only with `display: none` siblings counted? (I'm guessing no)

I guess I can go dig into Chrome's source to get the answer but it would be nice to have this explicitly put in the spec.

**Comment by nt1m** [comment]
@khushalsagar @noamr @vmpstr @bokand

**Comment by nt1m** [comment]
I admit I also have trouble understanding how `:only-child` works for `::view-transition-old/new()`. Would it be possible to define those in terms of a selector matching function and the namedElements map?

**Comment by nt1m** [comment]
It also occurs to me that there's no definition for group/image-pair (even though that one is more obvious)

**Comment by bramus** [comment]
> I admit I also have trouble understanding how `:only-child` works for `::view-transition-old/new()`. Would it be possible to define those in terms of a selector matching function and the namedElements map?

I think the spec is already pretty clear on this. For `::view-transition-old()` it reads _“it is omitted if there’s no “old” state to represent.”_. For `::view-transition-new()` it has a similar thing in place.

In the [intro to the VT pseudos](https://www.w3.org/TR/css-view-transitions-1/#view-transition-pseudos) it shows a diagram of the tree-structure of the pseudos, which makes it clear that `::view-transition-old()` and `::view-transition-new()` are direct children of `::view-transition-image-pair()`. That part also reads _“Either ::view-transition-old() or ::view-transition-new() are absent in cases where the capture does not have an “old” or “new” state.”_

With only one of the `::view-transition-old()`/`::view-transition-new()` pseudos possibly being prevent, authors can use `:only-child` to detect whether there was only a new or only an old snapshot for that specific v-t object. Based on that, they can do different animations.

See https://codepen.io/bramus/pen/mdabWzr for a demo: when you add a card there is only a `::view-transition-new()` pseudo which does a slide-down+fade-in animation. When removing a card there is only a `::view-transition-old()` pseudo which does a slide-up+fade-out animation.

**Comment by nt1m** [comment]
> Either [::view-transition-old()](https://www.w3.org/TR/css-view-transitions-1/#selectordef-view-transition-old) or [::view-transition-new()](https://www.w3.org/TR/css-view-transitions-1/#selectordef-view-transition-new) are absent in cases where the capture does not have an “old” or “new” state.

Oh I totally missed that. Would be good if the spec was more explicit about which property on the captured element struct this relates to. Right now I assume it's "old image" and "new element", but it could be any of the "old" properties :)

**Comment by noamr** [comment]
> > Either [::view-transition-old()](https://www.w3.org/TR/css-view-transitions-1/#selectordef-view-transition-old) or [::view-transition-new()](https://www.w3.org/TR/css-view-transitions-1/#selectordef-view-transition-new) are absent in cases where the capture does not have an “old” or “new” state.
> 
> Oh I totally missed that, thanks! Would be good if the spec was more explicit about which property on the captured element struct this relates to. Right now I assume it's "old image" and "new element", but it could be any of the "old" properties :)

We can add a clarification, why not :)
